### ISSUE TITLE
进入阅读模式再退出后原网页的字体会改变

### ISSUE THREAD

**Issue by xdujiang** [Kenshin/simpread#1]
原网页：
![ori](https://user-images.githubusercontent.com/10143140/27062881-ce1fb3c8-5020-11e7-9079-6bb0a281582a.jpg)

退出阅读模式后的网页：
![after](https://user-images.githubusercontent.com/10143140/27062885-d6f66f6e-5020-11e7-8109-0a5c739ab103.jpg)

chrome 字体设置：
![font](https://user-images.githubusercontent.com/10143140/27062888-dcd61132-5020-11e7-97b6-d03c20a34ce4.jpg)

**Comment by Kenshin** [comment]
我这没有这个问题，看截图应该是 Win 系统吧？什么版本的 Chrome？
你看 进入/退出 后 Html 里面有什么奇怪的东西？
或者 再随便换个 页面 试试。

**Comment by xdujiang** [comment]
@Kenshin 环境是win10 + chrome 57.0.2987.133
测试了一下支持列表里的前六个网站（cnbeta.com，qdaily.com，36kr.com，pingwest.com，jiemian.com，ifanr.com）和v2ex、微信，其中只有36kr的页面进入前和退出后看起来是正常的，其它页面看起来都有字体改变的现象
存成仅html然后用bc对比，两个网页是相同的，存成mhtml后文件有不同，但是不太能看得懂问题出在哪...

**Comment by Kenshin** [comment]
之前的确是有问题，不过问题已经找到了，很容易 Fix，感谢回复~
下个版本会发布！ 👍
