### ISSUE TITLE
对于匹配的站点，是否可以实现自动进入阅读模式？

### ISSUE THREAD

**Issue by airycanon** [Kenshin/simpread#10]
如题，今天在看新闻的时候想到的，阅读量比较大的情况下，每次打开页面都要按一下快捷键，是否可以增加一个配置项，免除这个操作？

不知道技术上有没有问题，例如，打开页面然后自动切换时会不会造成原页面闪一下，等等。

**Comment by Kenshin** [comment]
下个版本会提供此功能，从技术上讲没有问题的。
其实，目前也可以使用  `右键 → 简悦 → 使用阅读模式打开此链接 ` 的方式。

**Comment by izhangzhihao** [comment]
很期待这个功能！

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`
新增加 `选项页-高级设定`，其中包含此功能，详细 [猛戳这里](https://github.com/Kenshin/simpread/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97%EF%BC%88-%E6%93%8D%E4%BD%9C%E6%8C%87%E5%BC%95-%EF%BC%89#%E6%8E%92%E9%99%A4%E5%88%97%E8%A1%A8)
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)

**Comment by izhangzhihao** [comment]
赞赞赞

**Comment by Chihiromis** [comment]
你好 我折腾了好久 我想把一些网站加入自动进入阅读模式 请问这个功能怎么实现 是不是只能关闭自动进入阅读模式 再重新设置白名单？

**Comment by Kenshin** [comment]
@Chihiromis 

选项页 → 高级设定，请看下图：

![Xnip2019-03-31_11-43-52](https://user-images.githubusercontent.com/81074/55284485-4e04e480-53aa-11e9-907b-61884e7e91b8.jpg)

**Comment by woyaojizhu8** [comment]
可以增加 在阅读模式打开时，把当前站点加入白名单的功能 吗？这样就不用手动进入设置复制粘贴网址了

**Comment by Kenshin** [comment]
@woyaojizhu8 
可以考虑此功能，用菜单项来实现。

**Comment by Chihiromis** [comment]
> 你好 我折腾了好久 我想把一些网站加入自动进入阅读模式 请问这个功能怎么实现 是不是只能关闭自动进入阅读模式 再重新设置白名单？

所以这个功能的实现还是需要 关闭自动进入阅读模式。。

**Comment by Chihiromis** [comment]
> 在阅读模式打开时，把当前站点加入白名单的功能 吗？这样就不用手动进入设置复制粘贴网址了

这个功能非常需要呀。。希望可以增加

**Comment by Chihiromis** [comment]
请问这个白名单 要怎么写 
比如这个
https://github.com/Kenshin/simpread/wiki/FAQ
为什么我写成
https://github.com/*/*/wiki/*
不能实现自动进入阅读模式
