### ISSUE TITLE
希望增加对 OneNote for Office  365 Business 账户的支持

### ISSUE THREAD

**Issue by tonghs** [Kenshin/simpread#100]

**Comment by Kenshin** [comment]
这个需要的 `权限` 比较多，似乎无法自行添加 Auth，我需要调查下~

**Comment by tonghuashuai** [comment]
好，希望能够支持，谢谢。

**Comment by zhangchenkai** [comment]
默认是个人版的OneNote https://login.live.com 
希望也能够支持商业版或office365版的OneNote https://login.microsoftonline.com

**Comment by Kenshin** [comment]
@zhangchenkai 

谢谢反馈，会考虑加入商业版。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
