### ISSUE TITLE
设置页标题栏乱码

### ISSUE THREAD

**Issue by Heinodaily** [Kenshin/simpread#1000]
windows10 chrome最新版 简悦2.0
![image](https://user-images.githubusercontent.com/58068595/91147441-d7792d00-e6ea-11ea-8644-d83379f21a3b.png)
标题栏乱码，重启浏览器也是这样

**Comment by Kenshin** [comment]
导出配置文件，重装简悦。

**Comment by Kenshin** [comment]
嗨，请问还有问题吗？没有的话，请关闭这个 issues

**Comment by chaokw** [comment]
2.2.0.520遇到同样问题，chrome浏览器

**Comment by Kenshin** [comment]
> 2.2.0.520遇到同样问题，chrome浏览器

重启浏览器。

**Comment by fidding** [comment]
裂开啊，重装简悦，发现插件并不会重装，还要重头在配置一遍，坑坑坑死我了

**Comment by fidding** [comment]
重装导入之后，插件模块还需要再次点击从配置文件加载才可以（切记切记）

**Comment by eladyhot** [comment]
刚刚购买的高级版本，依然存在乱码问题，重装N次了

**Comment by Kenshin** [comment]
@eladyhot 

是否是乱码跟高级账户无关。一般重启浏览器就可以了，如果还是有问题，请提供你的浏览器详细信息。如果没有使用 Chrome 或 Edge 的话，请使用这两个浏览器。

**Comment by eladyhot** [comment]
好的 答复的很快，非常感谢&nbsp;&nbsp;
我重新安装了，暂时不是乱码
另提供我使用的浏览器信息如下：
Chrome 已是最新版本

版本 113.0.5672.127（正式版本） （64 位）



安信木业-高航
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月21日(星期天) 中午12:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 设置页标题栏乱码 (#1000)





 
@eladyhot
 
是否是乱码跟高级账户无关。一般重启浏览器就可以了，如果还是有问题，请提供你的浏览器详细信息。如果没有使用 Chrome 或 Edge 的话，请使用这两个浏览器。

**Comment by Kenshin** [comment]
@eladyhot 

okay 不是乱码就好，不需要重新安装，重启浏览器就能解决了。（确保真的的关闭浏览器了，Mac 用户需要注意这点）

另外，如果要使用导出功能的话，在选项页 → 服务中进行授权操作。

乱码是个别情况，可以忽略。
