### ISSUE TITLE
延迟加载列表为空后无法自动进入阅读模式

### ISSUE THREAD

**Issue by Frozenbf** [Kenshin/simpread#1001]
![功能已开启](https://user-images.githubusercontent.com/33197567/91150255-bd414e00-e6ee-11ea-8a54-53b4baa8bc1e.png)
![无法自动进入](https://user-images.githubusercontent.com/33197567/91150267-c03c3e80-e6ee-11ea-867d-5dd4bae0f051.png)

**Comment by Kenshin** [comment]
这个功能肯定没问题，你再试试。
还有，看看排除列表与黑名单有没有问题。
还是不行的话，隐身模式仅启用简悦。

**Comment by Frozenbf** [comment]
> 这个功能肯定没问题，你再试试。
> 还有，看看排除列表与黑名单有没有问题。
> 还是不行的话，隐身模式仅启用简悦。

黑名单和排除列表是默认的。打开的是普通窗口，没有使用无痕模式：
黑名单：
google.com
youtube.com
simp.red
simpread.herokuapp.com
simpread-test.herokuapp.com
simpread.ksria.cn
排除列表：
v2ex.com
issue.github.com
readme.github.com
question.zhihu.com
douban.com
nationalgeographic.com.cn
tech.163.com
docs.microsoft.com
msdn.microsoft.com
baijia.baidu.com
code.oschina.net
http://www.ifanr.com
http://www.ifanr.com/news
http://www.ifanr.com/app
http://www.ifanr.com/minapp
http://www.ifanr.com/dasheng
http://www.ifanr.com/data
https://www.ifanr.com/app
http://www.ifanr.com/weizhizao
http://www.thepaper.cn
http://www.pingwest.com
http://tech2ipo.com
https://www.waerfa.com/social

**Comment by Frozenbf** [comment]
v2ex.com
issue.github.com
readme.github.com
question.zhihu.com
douban.com
nationalgeographic.com.cn
tech.163.com
docs.microsoft.com
msdn.microsoft.com
baijia.baidu.com
code.oschina.net
http://www.ifanr.com
http://www.ifanr.com/news
http://www.ifanr.com/app
http://www.ifanr.com/minapp
http://www.ifanr.com/dasheng
http://www.ifanr.com/data
https://www.ifanr.com/app
http://www.ifanr.com/weizhizao
http://www.thepaper.cn
http://www.pingwest.com
http://tech2ipo.com
https://www.waerfa.com/social

**Comment by Frozenbf** [comment]
排除列表里的汉字是发出来自动转换的，正常显示就是默认网址

**Comment by Kenshin** [comment]
emm

导出配置文件，重置/保留 UID 方式，什么仅启用自动进入阅读模式功能，再试试

**Comment by Frozenbf** [comment]
> 嗯
> 
> 导出配置文件，重置/保留UID方式，什么仅启用自动进入阅读模式功能，再试试

![111](https://user-images.githubusercontent.com/33197567/91156160-5cb60f00-e6f6-11ea-84f5-e947aa65ac49.png)
发现问题所在了，这个延迟加载列表里面的网址一旦清空，自动进入阅读模式功能就会失效

**Comment by Kenshin** [comment]
谢谢 Debug 我明天有时间确认下。

**Comment by Kenshin** [comment]
emmm 刚测试了下，很奇怪，我仍旧无法复现你说的情况。

**Comment by Frozenbf** [comment]
> emmm 刚测试了下，很奇怪，我仍旧无法复现你说的情况。


[操作视频.zip](https://github.com/Kenshin/simpread/files/5128525/default.zip)
录了个删除网址前后对比的视频，您可以看一下

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了 **黑名单 · 排除列表 **包含多余回车导致的错误问题。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
