### ISSUE TITLE
ScienceDirect 网站的学术论文无法被检测到

### ISSUE THREAD

**Issue by Yaping-Wang** [Kenshin/simpread#1002]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.sciencedirect.com/science/article/pii/S2590238520303775>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈，先记新站

**Comment by Kenshin** [comment]
嗨，我在五一期间适配了这个网站，除此之外还包括以下几种常见的科研类页面。

- [https://www.sciencedirect.com/](https://www.sciencedirect.com/)
- [https://www.ncbi.nlm.nih.gov/](https://www.ncbi.nlm.nih.gov/)
- [https://journals.biologists.com/](https://journals.biologists.com/)
- [https://www.cell.com/cell/home](https://www.cell.com/cell/home)
- [https://elifesciences.org/](https://elifesciences.org/)
- [https://www.pnas.org/](https://www.pnas.org/)
- [https://science.sciencemag.org/](https://science.sciencemag.org/)
- [https://www.nature.com/]()
- https://www.frontiersin.org/journals

#### 特点

> 简悦适配的这些科研期刊，并不是 **简单的将正文提取出来**，而是 **根据学术文章一般有固定的格式**，如：`title` `abstract` `results` `discussions` `methods` `references` `acknowledgements` `highlights` 进行适配的。

所以，满足一般科研期刊的使用规律，且可显示 **数学公式 LateX** 等仅 **简悦的阅读模式独有的功能**。

#### 如何更新

> 请看 [官方适配源](http://ksria.com/simpread/docs/#/站点适配源?id=官方适配源)，更新后可打开 [这些示例网站](https://github.com/Kenshin/simpread/discussions/2103) 后进入阅读模式查看。

***

关于这部分的说明（以及如何使用）请前往 👉  [https://github.com/Kenshin/simpread/discussions/2103](https://github.com/Kenshin/simpread/discussions/2103) 查看详细说明。

***

没问题的话，请关闭此 Issues ~
