### ISSUE TITLE
某些网站标题不能完整显示，进入阅读模式后无法复制

### ISSUE THREAD

**Issue by Anthorty** [Kenshin/simpread#1004]
第一个问题截图
![image](https://user-images.githubusercontent.com/23048913/91164753-2c746d80-e702-11ea-8d1b-fb828ad01878.png)

**Comment by Kenshin** [comment]
谢谢反馈，请告知具体 URL

**Comment by Anthorty** [comment]
> 谢谢反馈，请告知具体 URL

http://www.people.com.cn/ 人民网任意一篇报道都会复现

**Comment by Anthorty** [comment]
关于第二个问题，复制文本是否需要关闭批注模式？

**Comment by Kenshin** [comment]
需要关闭标注功能。

**Comment by Kenshin** [comment]
关于第一个问题，刚刚测试了下，我这边没有问题

![image](https://user-images.githubusercontent.com/81074/91277722-c9dca980-e7b5-11ea-8b37-373ebe60ea2e.png)


你的分辨率是多大的？

-----

我尊重每个提 Issues 的用户，但由于近期 Issues 太多了，所以没办法进行有效追踪，如果我确定这个 Issues 并不是一个有效问题（或建议）的话，我会关闭这个 Issues

同时也会对这个 Issues 进行反馈，如果有必要的话，你可以随时再开启它。  😉

**Comment by Kenshin** [comment]
补充下，上面截图对应的链接 http://unn.people.com.cn/n1/2020/0826/c14717-31837698.html

**Comment by Anthorty** [comment]
分辨率是2K，2560X1440，刚才测试仍然标题显示不全

**Comment by Kenshin** [comment]
试试其它主题是否也有这个问题？

另外，方便的话，请在 **隐身模式下仅使用简悦的方式** 来排除其它扩展造成的影响。

**Comment by Anthorty** [comment]
> 试试其它主题是否也有这个问题？
> 
> 另外，方便的话，请在 **隐身模式下仅使用简悦的方式** 来排除其它扩展造成的影响。

刚刚测试过，隐身模式下只启用简悦仍然复现

**Comment by Kenshin** [comment]
其它的主题呢？

**Comment by Anthorty** [comment]
> 其它的主题呢？

一行能够显示的，会显示中间一部分，一行显示不了的，只能显示第二行的字（显示不完全）

**Comment by Kenshin** [comment]
好奇怪...

我完全无法复现，另外，简悦的主题从 1.0.0 就存在了，如果真的有这个问题，应该早就被发现了。

要不这样的吧，我仍旧关闭这个 Issues 看看以后是否仍旧有其他人反馈。
