### ISSUE TITLE
代码字号

### ISSUE THREAD

**Issue by 2218675712** [Kenshin/simpread#1009]
希望在不影响其他文字的情况下,
能够自定义调整代码的字号
目前的字号在笔记本上来看还是有些费眼的
并且直接保存在notion里面,在notion中查看代码是没用高亮提示的,用notion自带的插件会就没用这个问题

**Comment by Kenshin** [comment]
代码字号可以通过 **自定义样式** 修改，请在文档中心查找。

导出到 Notion 的问题是因为转换的 Markdown 造成的。（目前没有太好的解决办法）

没问题的话，请关闭这个 Issues

**Comment by Kenshin** [comment]
关于 Markdown 的问题我记在了其它的地方。
