### ISSUE TITLE
1.快捷键不兼容 Surfingkeys 扩展，2.最好能自动进入阅读模式

### ISSUE THREAD

**Issue by sgrjyb** [Kenshin/simpread#101]

**Comment by Kenshin** [comment]
并不是完全不兼容，只是小部分，关联问题 https://github.com/Kenshin/simpread/issues/88
我已经联络 Surfingkeys，Surfingkeys 下个版本即可修复。

***

有自动进入 `阅读模式` 功能， `选项` → `高级设定` 下图：
![image](https://user-images.githubusercontent.com/81074/30470576-ee6cfbac-99ba-11e7-8c91-9cc740cf8be4.png)

**Comment by Kenshin** [comment]
等 Surfingkeys 升级后，应该会好使了，我将关闭这个 issues，有疑问再重新 `Re-open`
