### ISSUE TITLE
似呼设置没有保存

### ISSUE THREAD

**Issue by firstuanl** [Kenshin/simpread#1011]
苏菲，windows10，edge最新
简阅2。0，

设置页面宽度没反应。
稍后阅读，阅读模式，导出pdf提示要在阅读模式
导出语雀，只有批注

PS，老板放firefox版本呀

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈

> 设置页面宽度没反应。

阅读模式下设置的吗？

> 稍后阅读，阅读模式，导出pdf提示要在阅读模式

这个是正常的

> 导出语雀，只有批注

这个也是正常的，你可以在 [标注侧栏](http://ksria.com/simpread/docs/#/%E6%A0%87%E6%B3%A8?id=%e6%a0%87%e6%b3%a8%e4%be%a7%e6%a0%8f) 关闭仅导出标注的选项

**Comment by Kenshin** [comment]
-----

我尊重每个提 Issues 的用户，但由于近期 Issues 太多了，所以没办法进行有效追踪，如果我确定这个 Issues 并不是一个有效问题（或建议）的话，我会关闭这个 Issues

同时也会对这个 Issues 进行反馈，如果有必要的话，你可以随时再开启它。  😉

**Comment by firstuanl** [comment]
1.阅读模式下设置宽度一点反应也没，且下载了2端对齐的插件也不对齐。在一台win7免费用户可以设置宽度，且实时变化。
2.但是没有导出pdf啊？我语文理解错误？
3,不管关闭还是打开仅导出标注的选项，出来的都只有批注？
