### ISSUE TITLE
标注编辑框无响应（待确认）

### ISSUE THREAD

**Issue by daizy008** [Kenshin/simpread#1013]
mark 之后进入备注编辑页面，一旦打字，网页就会卡死。点退出和删除都无效，只能刷新页面

- 操作系统 ** MacOS**

- 浏览器版本 **e.g. Chrome 84.0.4147.135（**

- 简悦版本 **2.0.0**

- 地址：备注页面

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
请问是任意页面吗？还是某个页面？

**Comment by daizy008** [comment]
所有的备注页面
就是给马克内容加笔记的页面

**Comment by Kenshin** [comment]
这就很奇怪了… 方便的话，在隐身模式下仅启用简悦试试。
另外，是否能排除系统慢的影响？

**Comment by daizy008** [comment]
只有这个页面会发生卡死。平时其他地方都没出现过。
最烦记完笔记内容全丢。
我会继续排查的。

Kenshin Wang <notifications@github.com>于2020年8月26日 周三下午8:08写道：
