### ISSUE TITLE
标注的缩略图太小了，导致图片识别度不高

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#1015]
我给一个长图进行标志，但是右侧的缩略图太小了。。
![image](https://user-images.githubusercontent.com/10437293/91282089-71100f80-e7bb-11ea-9e0b-bcbe9fad592b.png)

文章地址：http://liteng1220.com/blog/articles/dumpdex-principle/

**Comment by AriaLyy** [comment]
还有导出标注怎么只能导出到印象笔迹，后续能否增加导出到为知笔记等平台？

**Comment by Kenshin** [comment]
谢谢反馈

1. 侧栏仅作为预览使用，你可以点击标注条，会定位到页面的对应的位置。所以，图片较小也没问题。

2. 你可以看下 http://ksria.com/simpread/docs/#/标注?id=导出标注 与 http://ksria.com/simpread/docs/#/导出到生产力工具  你可以导出标注到简悦支持的生产力工具。

-----

我尊重每个提 Issues 的用户，但由于近期 Issues 太多了，所以没办法进行有效追踪，如果我确定这个 Issues 并不是一个有效问题（或建议）的话，我会关闭这个 Issues

同时也会对这个 Issues 进行反馈，如果有必要的话，你可以随时再开启它。  😉

**Comment by AriaLyy** [comment]
缩略图还是有影响的，如果我标注的缩略图多的话，识别度很低。。
还有标注，只能导出到印象笔记，每次我点导出标注，只会弹出印象笔迹的授权提示。

**Comment by AriaLyy** [comment]
我这只会弹出这个，而我为知已经授权了
![image](https://user-images.githubusercontent.com/10437293/91372082-49fe2000-e845-11ea-8db0-56640aef1ae9.png)

**Comment by Kenshin** [comment]
通过在阅读模式 → 右下角 控制器 → 动作面板 → 选择需要导出的内容，即可。

浮动工具栏的导出仅针对当前标注

建议多看下帮助文档

**Comment by AriaLyy** [comment]
了解，那导出当前标志能否弹出框让用户选择导出到对应的笔记工具呢？感觉明明有一个导出按钮，却只能导出到不会使用的印象笔记，而这按钮却隐藏不了。。。

**Comment by Kenshin** [comment]
选项页 → 高级定制 → 标注，里面有选项可以更改。

**Comment by Kenshin** [comment]
不过，确实不够友好，应该加个使用提示，比较好。
