### ISSUE TITLE
微信公众号的代码在阅读模式都是在同一行

### ISSUE THREAD

**Issue by 2218675712** [Kenshin/simpread#1016]
https://mp.weixin.qq.com/s/hpRl-gv3sRN8stAjM6zbrQ
https://mp.weixin.qq.com/s?__biz=MzI1ODk2Mjk0Nw==&mid=2247486537&idx=1&sn=30e12a527257939e2d1358099c2f483b&chksm=ea016f25dd76e6337d25d4545715210e4b833d601bca7c9dac5c8b92182b2b53db08b6c2e067&scene=126&sessionid=1598445677&key=2449a805bf282387b86f088d7bc7843f0661e194152815185b4229db89ddd1cbf725fdcd08405a45691b380a4e381c6876087207c8fa5497ecc280b5b09d1a24ea92f4fcfa3fc85794732489e38c2f326407661e94f39ce5dff5b424719340f278bba48ef6de2f4e4a9483532f40488cbcf6953489b35dcf8ead2e2aa91da396&ascene=1&uin=MTYwODIxMzUz&devicetype=Windows+10+x64&version=62090529&lang=zh_CN&exportkey=Ado2X0ZXDW5NbvAf7Ff8MIQ%3D&pass_ticket=6Do6k%2BP7ifYmC8wAaa8zZylxU2ZxRzYgEzo2EW105Qw%3D

微信公众号的代码在阅读模式都是在同一行

**Comment by Kenshin** [comment]
谢谢反馈，代码段的问题会集中到 #500 
所以我关闭这个 Issues 了，修复后会通知你。

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了代码段的问题。

<img width="631" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bc673da0-1d07-46d3-a5eb-2ef8809ad338">


***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
