### ISSUE TITLE
增加保存所有的网页内容到 dropbox ？

### ISSUE THREAD

**Issue by sgrjyb** [Kenshin/simpread#102]

**Comment by Kenshin** [comment]
> 所有的网页内容到 dropbox

指什么？

目前支持 `阅读模式` 以 markdown 形式保存到 `dropbox`

**Comment by sgrjyb** [comment]
类似 阅读模式 以 markdown 形式保存到 dropbox ，但增加在 所有网站运行

**Comment by Kenshin** [comment]
下个版本会提供 `聚焦模式`，但也仅限于 `聚焦模式` 与 `阅读模式`。
超出 简悦 范畴的功能应该不会做，这样有违 简悦的初衷~ 😄

**Comment by sgrjyb** [comment]
你用什么保存网页内容？

**Comment by sgrjyb** [comment]
增加 聚焦模式 也够了

**Comment by Kenshin** [comment]
我用 Onenote ，在 `阅读模式` 下足够了。（ 下个版本还会再加入 `聚焦模式` 的导出）
没有其它问题的话，我关闭这个 issuses 了，有需要的话，再重新 Re-open 吧。
