### ISSUE TITLE
高级账户登录被锁

### ISSUE THREAD

**Issue by mmqmzk** [Kenshin/simpread#1020]
现在的情况是我只有 1 个浏览器登录了高级账户，其他的都登不了了。重新导入配置貌似没有用。总是提示登录浏览器过多。我有一台电脑坏了无法登出了，现在想登录的新浏览器跟坏掉的那台是同一个局域网，不知道为什么会出现这种情况，跟 ip 变动或者使用代理有关吗？或者是因为我在手机上登录过（Android kiwi 浏览器可以用 chrome 扩展），网络变动被算作多个设备？

建议一劳永逸改为登录第 4 台设备时自动登出第 1 台设备，以防止设备损坏或丢失造成无法登出的情况。

**Comment by Kenshin** [comment]
谢谢新开 Issues
我会推出自助解锁服务，可以解决你的问题。

另外，简悦的机制跟其它产品不太一样，因为简悦不会 **存储用户自己的个人信息**，所以无法像其它产品的思路一样。

简单的说，用户的配置文件就是个 Key 谁用都行，简悦没办法通过你说的方式来解决共享账户的问题。

**Comment by Kenshin** [comment]
嗨，这个问题还存在吗？因为上线了自助解锁平台，所以我关闭这个问题了。

**

1. 【简悦 · 高级账户平台】已上线，可通过此平台自主解锁 https://simpread.pro/account

2. 未避免再次被锁定，请务必阅读 此文档 http://ksria.com/simpread/docs/#/%E5%B7%B2%E8%B4%AD%E5%BF%85%E8%AF%BB

3. 如果是因为登录了过多浏览器造成的被锁定，请【退出已登录的浏览器】即可。

**Comment by mmqmzk** [comment]
设备损坏无法登出，与损坏的设备在同一个局域网的设备没有被算做同一个。
是不是只能换个 uid 重新买个 Licence，已保存的稍后读能同步到新的 uid 吗？

**Comment by Kenshin** [comment]
> 设备损坏无法登出，与损坏的设备在同一个局域网的设备没有被算做同一个

当然不算作一个了，我从没说过，局域网算一台设备。

***

不需要换 UID 只需要找回 UID https://simpread.pro/account  或者你知道 UID 的话，用我上条给出的地址进行解锁就好了。

***

另外，我详细看了下你第一条的内容，发现有几个误区，简单的说下：

1. 局域网肯定不算作一台设备，原因上面解释了。

2. 不要使用 Kiwi Browser 授权高级账户，因为我从未说过，简悦的标注（尤其是一些高级功能）可以完美支持 Kiwi Browser 你可以安装简悦，但不要启用高级账户功能。

3. 因异常情况而无法登出的话，超过 14 天会自动登出这个设备，也可用 https://simpread.pro/account 自助登出。

但一定要看下上条给出的链接内容。

**Comment by mmqmzk** [comment]
![untitled](https://user-images.githubusercontent.com/2217694/91697101-215a8b00-eba3-11ea-8fd0-cd694d77b082.png)
点这个没有用啊
点解绑所有设备以后确认，没有登出任何设备

**Comment by Kenshin** [comment]
你的 UID 前6位 告诉我，我看下。

**Comment by mmqmzk** [comment]
e4zbsp5f-

**Comment by Kenshin** [comment]
我删除了你的上条信息（因为包含 UID

**Comment by Kenshin** [comment]
抱歉，你的邮件被识别为垃圾邮件了，我才看到。


如果 UID 丢失的话，可以自助找回，留意下面的内容。


【简悦 · 高级账户自助找回平台】 地址 https://simpread.pro/reset （内含使用方法）


请留意：因为 License 与 UID 为私密信息，但平台为开放平台，虽然 License 与 UID 仅你自己知道，但为了确保安全，一共只能 最多找回三次

&nbsp;

BR,
Kenshin

 http://kenshin.wang
------------------

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kun Zhou"<notifications@github.com&gt;; 
发送时间: 2020年8月31日(星期一) 下午4:01
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "Kenshin Wang"<fxblog@gmail.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 高级账户登录被锁 (#1020)





 

 点这个没有用啊
 点解绑所有设备以后确认，没有登出任何设备
 
&mdash;

**Comment by Kenshin** [comment]
另外，你的这个情况太特殊了，我帮你操作下，并且我也要相应调整下程序，搞定后告诉你。

**Comment by Kenshin** [comment]
嗨，应该可以了，你需要重新授权。

以后不要再发生这种问题了。

**Comment by mmqmzk** [comment]
终于好了
👍🏻️

**Comment by Kenshin** [comment]
搞定就好，之前是个 Bug  造成的，所以我手动帮你操作了，以后请使用这个平台自助解锁。

**Comment by songmeixu** [comment]
请求帮助，不知什么问题导致我现在状态很奇妙，没有绑定设备，又不能恢复高级，又不能激活，重装都不行。

---

我以前装过同步到 dropbox 配置，后来卸载了，这次又装，买了高级，上来就用远程配置覆盖掉本地了，结果就出事了，搞了好久。我 90%确定这是 bug 了。老用户不能使用以前的配置？我也不在乎了，重新开始吧，看下啥问题，谢谢！来人了，贴 UID

**Comment by Kenshin** [comment]
@songmeixu 

你既然到找到这个 Issues 了，为什么没有注意到解决方案呢？😂 这个问题可以解决的，并且也不算 Bug

先说解决方案，看这里 https://wj.qq.com/s2/7131520/9679/ 仔细读，肯定会解决你的问题。

再说配置文件的问题，配置文件当然可以使用老版本的，它会自动升级到最新版本。你的配置文件是什么版本的？你用原来的版本的配置文件覆盖到本地？是强制覆盖吗？如果想解决配置文件的问题，最好说下细节。
