### ISSUE TITLE
Chrome 提示跨域访问，无法跟服务端正常交互

### ISSUE THREAD

**Issue by luoxiaohei** [Kenshin/simpread#1022]
![image](https://user-images.githubusercontent.com/7138906/91412603-9a44a480-e87c-11ea-8a48-bcf681a87b4b.png)
错误如图所示，影响到更新个人资料、解锁/恢复高级账号、下载插件等功能。

操作系统 macOS 10.15.6 (19G2021) 
Chrome 版本 85.0.4183.83（正式版本） （64 位）

**Comment by Kenshin** [comment]
emmm

我也升级到了 85 但没有出现 CORS 的问题，你做过什么特别的设置吗？

**Comment by luoxiaohei** [comment]
印象里没做什么额外操作，我尝试把其他扩展都禁用了也不行。

**Comment by Kenshin** [comment]
之前在 84 版本的时候有这个问题吗？

**Comment by luoxiaohei** [comment]
84 版本没遇到这个问题，不过我是今天同时升级的 2.0 的插件和 Chrome，而且我上午正常激活了高级账号，后边装插件的时候就开始提示跨域了。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/91414164-bfd2ad80-e87e-11ea-87aa-a94396afc22e.png)

看看简悦是否是按照上面进行的设置。

另外，导出配置文件后再重新安装简悦（包括：重启浏览器）再试试。

**Comment by luoxiaohei** [comment]
优秀！确实是这个设置影响了。我上午发现 2.0 版本的简悦会影响到内网的一个网站展示，就改成了只点击时允许，改成所有网站允许确实可以了。。。

**Comment by Kenshin** [comment]
搞定就好。

> 我上午发现 2.0 版本的简悦会影响到内网的一个网站展示

试试加到黑名单里面

***

没问题的话，我关闭 Issues 了，有需要再重开
