### ISSUE TITLE
在稍后读当中无法添加标签

### ISSUE THREAD

**Issue by sunshineharry** [Kenshin/simpread#1023]
在`稍后读`功能种，找不到给文章添加标签的入口

![image](https://user-images.githubusercontent.com/52942042/91449721-07246280-e8ae-11ea-9ee4-836828478b77.png)

**Comment by Kenshin** [comment]
有的，请仔细看下稍后读的文档
http://ksria.com/simpread/docs/#/稍后读?id=功能

具体位置在顶栏

**Comment by sunshineharry** [comment]
我在文档当中没找到入口QwQ

我的顶栏是这样的：
![image](https://user-images.githubusercontent.com/52942042/91452917-bf073f00-e8b1-11ea-802d-a32e41b81ca9.png)

求问能给个截图吗？谢谢啦

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/91513882-fc9eb300-e917-11ea-8e54-1d6f95f2d862.png)
![image](https://user-images.githubusercontent.com/81074/91513917-13dda080-e918-11ea-92e2-428215b3209a.png)


标注模式和阅读模式的位置不同

**Comment by sunshineharry** [comment]
找到了，谢谢大佬！！！！
非常感谢！！！
