### ISSUE TITLE
知乎某些图片无法成功显示

### ISSUE THREAD

**Issue by sunshineharry** [Kenshin/simpread#1024]
## 使用环境

- 操作系统 **Windows 10**

- 浏览器版本 **Edge 84.0.522.63 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/148233372>

## 问题

在`稍后读`的`阅读模式`下图片无法正常显示

**截图：**

- 原始页面:
![image](https://user-images.githubusercontent.com/52942042/91453626-916ec580-e8b2-11ea-9a4d-dbd17c58e446.png)

- `阅读模式`页面
![image](https://user-images.githubusercontent.com/52942042/91453768-bd8a4680-e8b2-11ea-80c0-f69a0ee6f219.png)

> 因为页面已经打开很长时间，其他图片都能顺利加载，可以排除网络问题

**Comment by Kenshin** [comment]
谢谢反馈。

你无法加载的图片使用了惰性加载方式。所以，需要将它加入到 [延迟加载](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e5%bb%b6%e8%bf%9f%e5%8a%a0%e8%bd%bd) ，页面加载后，滚动条下拉就可以了。

PS：我看能否用其它方案解决这个问题，你先按照我上面的说的方式。

**Comment by sunshineharry** [comment]
我已经加入 `延迟加载` 了，如下图：
![image](https://user-images.githubusercontent.com/52942042/91515581-1641f980-e91c-11ea-82fa-d50bf60fa421.png)

但还是无法正确显示图片：
![image](https://user-images.githubusercontent.com/52942042/91515613-278b0600-e91c-11ea-9b02-9b1b7ef5edb6.png)

**Comment by Kenshin** [comment]
页面加载后，滚动条下拉过这些图片就可以了。

**Comment by sunshineharry** [comment]
好像还是不太OK，不知道是不是我的操作有问题，我更改了`延迟加载列表`然后进行如下操作，可以看到，图片还是没能正确显示：
![0](https://user-images.githubusercontent.com/52942042/91521509-632ccc80-e92a-11ea-9116-933cdc8fdc91.gif)

**Comment by Kenshin** [comment]
在进入阅读模式前拉动滚动条

**Comment by binsee** [comment]
先标记，之后更新知乎专栏适配，解决此问题

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues

**Comment by binsee** [comment]
发现此问题放入 `puplugin` 中解决更合适

puplugin 中已有的相关代码：

```js
a = (r.parent(), $("<img class='sr-rd-content-img-load'>")),
n = r.attr("src"),
i = r.attr("data-src"),
o = r.attr("data-original"),
s = r.attr("original"),
l = r.attr("data-original-src"),
c = r.attr("data-lazy-src"),
u = r.attr("real_src"),
```

此问题元素：

```html
<img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='260'></svg>" 
data-size="normal" data-rawwidth="400" data-rawheight="260" 
class="content_image lazy" width="400" 
data-actualsrc="https://picb.zhimg.com/v2-781a00c5cfe04f559e9e394ddc031ebf_b.jpg">
```

同页面能正常显示的元素：

```html
<img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='969' height='744'></svg>" 
data-size="normal" data-rawwidth="969" data-rawheight="744" 
class="origin_image zh-lightbox-thumb lazy" width="969" 
data-original="https://pic3.zhimg.com/v2-bddd0f66be7e818f31d20ea38b392bb9_r.jpg" 
data-actualsrc="https://pic3.zhimg.com/v2-bddd0f66be7e818f31d20ea38b392bb9_b.jpg">
```

在一个页面上，同样是懒加载的图片，后者能显示，前者不能显示，原因就是后者的 `data-original` 在 `puplugin` 中被命中了，而前者只有 `data-actualsrc` 没有被收录入 `puplugin`，因此降级使用了 `src` 。

### 解决方式

将 `data-actualsrc` 收录入 `puplugin`，优先级比 `data-original` 低，比 `src` 高即可。

**Comment by Kenshin** [comment]
@binsee 

收到，那我先重开这个 issues 吧

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

新增加了专门针对 [惰性加载图片的解析方案](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e6%83%b0%e6%80%a7%e5%9b%be%e7%89%87%e5%8a%a0%e8%bd%bd)，如下图

![image](https://user-images.githubusercontent.com/81074/121986734-a7119500-cdc9-11eb-94a2-973e1b1e28a6.png)

注意：使用此功能时会出现维基百科的一些问题，解决方案 [请看这里](https://github.com/Kenshin/simpread/discussions/2347)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
