### ISSUE TITLE
微信公众号显示异常

### ISSUE THREAD

**Issue by sunshineharry** [Kenshin/simpread#1025]
## 使用环境

- 操作系统 **Windows 10**

- 浏览器版本 **Edge 84.0.522.63 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s/NuK-gA-YuEn_84sWw0hHbg>

## 问题

1. 在`稍后读`当中出现很多不太愉快的 `·` 符号
2. 在`稍后读`当中原先页面的加粗没能正确显示
3. 代码字体突然缩小（代码会比正常字体缩小了一号）

## 截图

- 原始页面
![image](https://user-images.githubusercontent.com/52942042/91516222-7c7b4c00-e91d-11ea-950d-aee7109b088f.png)

- 稍后读中页面
![image](https://user-images.githubusercontent.com/52942042/91516322-b9474300-e91d-11ea-8ca0-01cc3b0461f3.png)

**Comment by Kenshin** [comment]
谢谢反馈，以及细节的指出。

但这不是简悦的问题，我随便给你找一个你指出的地方

![image](https://user-images.githubusercontent.com/81074/91517841-65d6f400-e921-11ea-80a9-ea8ea5985317.png)

简单点说，这个粗体并没有用正规的 `<b> `或者 **其它加粗的方式实现** 所以在阅读模式中会被删除。
再引申下，订阅号页面几乎每处都充斥这类问题。

关于 **点** 的问题，这算是个 Bug ，这是由于代码高亮解析造成的，你可以把这个URL提交到 https://github.com/Kenshin/simpread/issues/500

***

总结下，稍后读的阅读模式的解析与渲染模式与通过正常页面进入并加载阅读模式不太一样，也就是说，一般正常情况是没问题的，但类似诸如： 动态加载 惰性图片加载 均有问题。

**Comment by sunshineharry** [comment]
啊啊啊明白了，谢谢！

**Comment by sunshineharry** [comment]
#500 已经无法提交了呜呜呜

**Comment by sunshineharry** [comment]
刚刚我又看了一遍您的截图，不知道可不可以解析这段语句
```
font-weight: bold
```
因为我没学过网页这块的内容，所以不知道可不可行

**Comment by sunshineharry** [comment]
刚刚根据 #500 的解决方案，安装了如下插件：
![image](https://user-images.githubusercontent.com/52942042/91520689-7b035100-e928-11ea-8027-a423dee07202.png)

点点同样存在
![image](https://user-images.githubusercontent.com/52942042/91520714-8fdfe480-e928-11ea-9c67-381bf2ef06dc.png)

**Comment by Kenshin** [comment]
> #500 已经无法提交了呜呜呜

我帮你提交了，修复我会通知你。

**Comment by sunshineharry** [comment]
谢谢啦

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
