### ISSUE TITLE
简书文章解析段落出错

### ISSUE THREAD

**Issue by hacker-jerry** [Kenshin/simpread#1029]
例如
![image](https://user-images.githubusercontent.com/57279550/91536468-51a5ed80-e947-11ea-9dbb-bb524222b1ca.png)

然后通过阅读模式解析后
![image](https://user-images.githubusercontent.com/57279550/91536672-a0538780-e947-11ea-84d8-587f8199d92c.png)

这一段代码是上一段的内容，发生了下移。
说明出现问题。

原文文章
https://www.jianshu.com/p/c26bc5ccf604

**Comment by Kenshin** [comment]
谢谢反馈，应该是简书的结构发生变化造成的，我先记下来。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
