### ISSUE TITLE
希望增加 起点中文网，谢谢

### ISSUE THREAD

**Issue by sapqianjin** [Kenshin/simpread#103]

**Comment by Kenshin** [comment]
客气了~

如果只想阅读小说的话，我建议使用另外一款 油猴脚本 https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
虽然界面体验不如 简悦，但胜在支持的小说网址很多，并且有自动翻页功能。
***
如果仍对 简悦感兴趣的话，告诉我，我再适配。 💪

**Comment by sapqianjin** [comment]
谢谢 :)

**Comment by Kenshin** [comment]
鉴于 起点中文网 还是挺大众的，所以还是决定适配下 😅 当然，我仍旧建议你使用 油猴脚本，前提是你经常看小说的话。😏

**Comment by Kenshin** [comment]
已适配，如果你只看起点中文网的话，我建议使用简悦来阅读，毕竟呈现的效果要好些~

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。

**Comment by sapqianjin** [comment]
谢谢，可否将vipreader.qidian.com也加入，格式可以和read.qidian.com相同。

**Comment by Kenshin** [comment]
我没有 vip 无法测试，只是按照你的说法，已经加入。  😳

**Comment by sapqianjin** [comment]
已经OK，谢谢。:)
