### ISSUE TITLE
谷歌浏览器标注导出问题

### ISSUE THREAD

**Issue by BendMoly** [Kenshin/simpread#1030]
进入阅读模式后对部分段落进行标注高亮，之后要点导出标注的时候完全没有一点反应。

请问这个导出标注到底是怎么操作的，我看文档操作还是导出不了。

另外一点建议就是删除稍后读的时候提示删除的弹出框放在下面经常看不到提示，或者交互动作大点引起点注意

**Comment by Kenshin** [comment]
> 关于 标注高亮 导出的问题

可以 [看这里](http://ksria.com/simpread/docs/#/%E6%A0%87%E6%B3%A8?id=%e5%af%bc%e5%87%ba%e6%a0%87%e6%b3%a8) 的说明文档 以及 [详细设定](http://ksria.com/simpread/docs/#/%E6%A0%87%E6%B3%A8?id=%e8%af%a6%e7%bb%86%e8%ae%be%e5%ae%9a) · [导出服务](http://ksria.com/simpread/docs/#/%E5%AF%BC%E5%87%BA%E5%88%B0%E7%94%9F%E4%BA%A7%E5%8A%9B%E5%B7%A5%E5%85%B7)

**Comment by Kenshin** [comment]
-----

我尊重每个提 Issues 的用户，但由于近期 Issues 太多了，所以没办法进行有效追踪，如果我确定这个 Issues 并不是一个有效问题（或建议）的话，我会关闭这个 Issues

同时也会对这个 Issues 进行反馈，如果有必要的话，你可以随时再开启它。  😉
