### ISSUE TITLE
导出为markdown时可否支持自定义图床

### ISSUE THREAD

**Issue by hhhhhliu** [Kenshin/simpread#1031]
在导出为markdown文件时，自动将文件中的所有图片链接替换为自定义图床的图片链接

**Comment by Kenshin** [comment]
谢谢建议，会考虑的。 💪

**Comment by Kenshin** [comment]
![PicGo](https://user-images.githubusercontent.com/81074/182798678-f318f7b7-d637-4faa-acd4-5c1dd2f73710.png)

嗨，简悦增加了 **图床插件** 支持支持国内大多数的图床服务：七牛、腾讯云、阿里云、又拍云、Github、SM.MS、Imgur 图床等，并支持当前转换为图床后，可自动选择一个导出服务，包括：触发插件的动作、导出到本地、导出到生产力工具、Webhook、WebDAV。

详细说明👉https://github.com/Kenshin/simpread/discussions/4306


所以，我关闭此 Issues 了
