### ISSUE TITLE
代码显示样式错乱

### ISSUE THREAD

**Issue by Juveniless** [Kenshin/simpread#1032]
文章地址
https://mp.weixin.qq.com/s/XklGaPCRbSh3fjK90rxkPA

**Comment by Juveniless** [comment]
用了代码插件后，代码会全部挤在一行。

**Comment by Kenshin** [comment]
谢谢反馈，代码高亮会集中到 #500 里面，所以我关闭这个 Issues 了，并在 #500 做了标记。
