### ISSUE TITLE
导出全文时应当包含标注和标签

### ISSUE THREAD

**Issue by DereckZhang** [Kenshin/simpread#1036]
作为知识工作者，1.x的老用户，最近用了2.0表示标注功能深得我心，比印象笔记插件强多了。。但是有一个功能缺失就是标注以后，全文导出到印象笔记时标注就丢了，不能一起保存过去，印象笔记官方插件就可以。考虑到很多网站在墙外，或者没几天就404了，全文带标注保存还是挺有必要的

PS：导出到印象笔记时，开头一行“本文由 简悦 SimpRead 转码，原文地址”能不能有个选项关掉？保存的文章多了觉得还是有点碍眼

**Comment by Kenshin** [comment]
谢谢老用户。 😀 

导出的方式确实只能二选一：

- 仅标注（不含全文）
- 仅全文（不含标注）

没加 **全文 + 标注** 的原因是：跟导出服务有关系，比如，某些服务仅支持 Markdown 就无法使用这种形式了；比如，你说的印象笔记，它对导入到其中的 HTML 极其严格，所以这种情况下也会增加出错的机率。

目前能想到的关于这种模式最好的方式是：离线 HTML，即可包含全文，又可支持标注。

我会考虑出个插件或者下个版本原生支持此功能。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了导出文件只包含 `标注` `全文` 的问题，现在的做法：在导出全文时也包含了标注内容。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
