### ISSUE TITLE
版面宽度调节无效果

### ISSUE THREAD

**Issue by firstuanl** [Kenshin/simpread#1037]
苏菲windows10，edge任何版，及简悦1，2, 版面宽度调节无效果

如图
http://file.mail.10086.cn/share2/fileexpress/filedownload.htm?sendid=90630950084306030822101810905210

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by firstuanl** [comment]
https://cowtransfer.com/s/99a06f2ee0d64c
码
uniqmu

**Comment by Kenshin** [comment]
谢谢反馈。

你试试其它的页面是否也有这样的问题，例如 https://sspai.com/61996

**Comment by firstuanl** [comment]
我也搞不懂情况，其它电脑都正常，就这台电脑，edge正式版及dev版，安装阅悦1.14及2，版面宽度设置在所有页面都没效果。

**Comment by firstuanl** [comment]
删除旧版简悦时会把2.0的账户清掉。

**Comment by Kenshin** [comment]
如果你的 UID 丢失，可以通过下面的方式获取

 【简悦 · 高级账户自助找回平台】 地址 https://simpread.pro/reset （内含使用方法）

请留意：因为 License 与 UID 为私密信息，但平台为开放平台，虽然 License 与 UID 仅你自己知道，但为了确保安全，一共只能 最多找回三次

***

> 删除旧版简悦时会把2.0的账户清

应该不会出现这种情况，Chrome 采用了沙箱方式，而且旧版与 2.0 不能并存。

**Comment by firstuanl** [comment]
奇怪，1.1.4和2.0安装都在扩展里，且相对独立

**Comment by Kenshin** [comment]
关于版面布局无法调整的问题，我已经知道了，因为我偶尔也会用用 Surface Pro

原因是简悦做了特殊限制，导致触屏类的 PC 设备会出现无法调节宽度的问题。

***

请问你需要做个事情吗？可以通过 **自定义样式** 来解决。因为版本调整不是经常做的事情，所以如果你有需求，打开

`chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/custom.html`

然后在自定义 CSS 中填入如下的内容

```
sr-read {
   margin: 20px 18%!important;
}
```

注意：18% 可以改为任何值，也可以改为绝对值，如 20px 等等。

**Comment by firstuanl** [comment]
好的，谢谢
