### ISSUE TITLE
【站点】-国家图书馆电子期刊阅览室

### ISSUE THREAD

**Issue by Dixeran** [Kenshin/simpread#104]
举个例子，这是《看天下》某期的目录
http://nlc.vip.qikan.com/text/Mag.aspx?issn=65545C2E-BB1C-4F32-8CDF-5995EF0BD73F&year=2017&issue=24#wbtext
希望能适配目录进去的内容（可能需要注册登陆才能看见，注册和阅览都是免费的）

**Comment by Kenshin** [comment]
感谢反馈，我明天会看看，适配后会通知你。

**Comment by Dixeran** [comment]
## 附上我在Stylish上写的覆盖样式，不懂会不会有帮助

`.headbox {
    display: none;
}
.banner {
    display: none;
}
#menuHeaderDiv {
    display: none;
}
.search {
    display: none;
}
.box {
    background: none;
    padding: 0;
}
.mediabox {
    padding: 0;
}
.medianav {
    color: #DADCDB;
}
.medianav a {
    color: #DADCDB;
}
.eiboxright {
    display: none;
}
.eiboxleft {
    float: none;
}
.eiboxlefttextbody0 {
    border: 0;
    width: 60% !important;
    max-width: 960px;
    margin: 0 auto;
    background-color: #DADCDB;
    padding: 1cm;
    border-radius: 10px;
}
.eiboxlefttextbody0 img{
    margin: 0 auto;
    display: block;
}
.eiboxlefttextbody0 h2 {
    margin: 0 auto;
    float: none;
    font-size: 1em !important;
}
.eiboxlefttextbody0 h1 {
    margin: 0 auto;
    float: none;
}
.newartbox {
    border: 0;
    padding: 0;
    margin: 0 auto;
}
#zoom {
    line-height: 200% !important;
    font-size: 1.5em;
    margin-top: 20px;
}
#menuFooterDiv {
    display: none;
}
.rearinfo {
    display: none;
}
.icp {
    display: none;
}
h2 img {
    display: none;
}
h1 {
    font-size: 2.25em !important;
}
h2 {
    font-size: 1.75em !important;
    width: 100% !important;
    overflow: hidden;
}
h3 {
    font-size: 1.5em !important;
    margin-top:1cm;
}
h4 {
    font-size: 1.25em !important;
}
div {
    float: none !important;
    width: 100% !important;
    position: relative !important;
}
body {
    width: 100% !important;
    font-family: "Microsoft YaHei";
    background-color: #403E4E;
}`

**Comment by Kenshin** [comment]
我登陆进去了，但你给出的链接无法访问，估计是收费的缘故，我随便打开了一个，界面如下

![image](https://user-images.githubusercontent.com/81074/30527163-307942f4-9c58-11e7-8e30-4e024158e9ab.png)

如果你给出的链接 或者说 绝大多数的页面结构都与上图类似的话，应该可以适配。😊

***

感谢给出 Stylish，顺便修复了下 Stylish 的结构问题，不过简悦与 Stylish 的结构不太一样，并不能用于简悦。如果你喜欢这个 Stylish 页面结构的话，可以通过自定义样式使用，但需要修改 CSS 标签。这部分请看 [自定义样式](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by Dixeran** [comment]
嗯就是这个页面，开发者辛苦啦😊

**Comment by Kenshin** [comment]
已适配~   💪 

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
