### ISSUE TITLE
什么值得买 网站适配问题

### ISSUE THREAD

**Issue by zhl111** [Kenshin/simpread#1041]
https://post.smzdm.com/p/awx43w02/
![image](https://user-images.githubusercontent.com/29135984/91655365-9d40ce80-eae2-11ea-881b-cfcd16a1ba72.png)

**Comment by Kenshin** [comment]
收到，谢谢反馈。

**Comment by binsee** [comment]
隐藏列表更新为可解决：

```
<h1 class='item-name'>
<div class='coupon-card-wraper'> // 站外商品卡片
<div class='brand-card-box'>  // 品牌信息卡片
```

**Comment by binsee** [comment]
已提交适配id：`o5rx7zi0-wBT3s6l8bX`

**Comment by Kenshin** [comment]
谢谢 @binsee

**Comment by binsee** [comment]
关联pr #1067

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
