### ISSUE TITLE
导出文件，代码块内代码出现转义字符

### ISSUE THREAD

**Issue by youtiaoguagua** [Kenshin/simpread#1042]
[维基百科](https://zh.wikipedia.org/wiki/%E5%85%AB%E7%9A%87%E5%90%8E%E9%97%AE%E9%A2%98)

![image](https://user-images.githubusercontent.com/30404329/91656571-6079d500-eaec-11ea-917f-71e399b77c36.png)

**Comment by Kenshin** [comment]
嗨，我解决了这个问题，细节请看 https://github.com/Kenshin/simpread/issues/1064#issuecomment-687972690

# 解决方案如下

我近期要升级一个 **新的版本 2.0.0.90xx** 具体时间未知，但开发时间从今日（ 9/08 ）开始，预计三天时间，因为不是新功能，所以不会花费太长时间，此补丁版修复了从 2.0.0 发布以来的一些问题，比如 **Markdown 转义错误的问题**，细节我会另行通知。

***

如果你可以等待此补丁版的话，建议多等待几天（最迟不超过一周），否则的话，请使用 **[离线版](http://ksria.com/simpread/crx/2.0.0/simpread.zip)** 

离线版解决了 Markdown 转义错误的问题，但离线版无法升级，所以 **请务必在安装离线版后，切勿删除 Chrome 应用商店版**，禁用即可。

同时这个 Issues 我也不会关闭，等新版发布后，我会在这里同时大家，并且关闭 Issues

***

> 注意：此版本 **仅解决了转义问题**，如果有代码高亮的问题，属于这个 **代码高亮插件本身的问题，不涉及到简悦扩展**，等待我的通知。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了 **转义错误的问题**。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
