### ISSUE TITLE
[建议] 动作里面的内容希望可以自定义

### ISSUE THREAD

**Issue by eallion** [Kenshin/simpread#1043]
![2020-08-30_23-20](https://user-images.githubusercontent.com/1698841/91662869-b2842000-eb17-11ea-91dd-99feda5f3965.png)

如图。
在`动作`里面的内容，我基本上只会用到3-4个，常用的只有一个`导出到 GitHub`，希望可以自定义此页面，隐藏不需要的功能，干扰比较严重。

**Comment by Kenshin** [comment]
嗨，你可以试试下面两个插件 #891 #892

我关闭这个 Issues 因为上面两个插件能满足你的需求。

**Comment by binsee** [comment]
另外还有快捷键操作更快一些

1. 先在页面 `aa`进入阅读模式
2. 然后 `sr` 开启快捷键操作 （可在此模式下按 `,` 查看快捷键列表）
3. 使用 `gh` 保存到github
