### ISSUE TITLE
代码段分析出错

### ISSUE THREAD

**Issue by caodaqian** [Kenshin/simpread#1044]
https://mp.weixin.qq.com/s?__biz=MzIxMjE5MTE1Nw==&mid=2653211304&idx=1&sn=92a0fda6de6830b5d5e5a7b62bd8c009&chksm=8c99b872bbee3164a3a08d8645b12926681d0d9143baf0260c2600723a26d68dfb0701fd7253&scene=90&xtrack=1&sessionid=1598837738&subscene=93&clicktime=1598837760#rd

打开插件，导致代码全部缩为一行，不光没有高亮，反而使得排版更差了

**Comment by caodaqian** [comment]
![image](https://user-images.githubusercontent.com/29157472/91680223-21e02b00-eb7d-11ea-9f1b-f96e52b9e481.png)

**Comment by Kenshin** [comment]
谢谢反馈，代码高亮问题，集中会反馈到 #500 所以我关闭这个 Issues 了，修复后统一通知你们。

**Comment by caodaqian** [comment]
麻烦问下这个问题修复了吗？具体是什么统一通知呢？

**Comment by Kenshin** [comment]
抱歉，目前还未修复  😩  
同时这个插件也不是 100% 无法使用，只是部分代码高亮页面导致错误。

但修复它的 Roadmap 一直都在，修复后当然会通知到你。😀
