### ISSUE TITLE
知乎专栏适配的问题，打开阅读模式之后是空白。

### ISSUE THREAD

**Issue by echocherish** [Kenshin/simpread#1045]
阅读模式打开之后是一片空白，https://zhuanlan.zhihu.com/p/34996144 就是这个页面。
而且我想关闭阅读模式的时候，简阅反复提醒我【控制栏面板已开启，已禁用xxxx】我不太记得那个条幅的具体内容了，就会反复出现这个条幅，但是我实际上看不到右下角的红色按钮（如果那个就是控制栏面板），总而言之对新手很不友好啊。

**Comment by Kenshin** [comment]
谢谢反馈。

我没有遇到你的这个问题，但看描述是因为：你同时安装了多个简悦造成的，如：插件版与轻阅版，类似这样的情况，请确认下。

**Comment by Lxianz** [comment]
我也遇到了同样的问题

**Comment by Kenshin** [comment]
@Lxianz 

其他页面没有这个问题吗, 仅仅只是知乎?

**Comment by Kenshin** [comment]
另外，也可试试导出配置文件后，重装简悦。

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
