### ISSUE TITLE
授权notion时出错

### ISSUE THREAD

**Issue by sybhdxb** [Kenshin/simpread#1048]
请注意:获取时出现了问题导致仅成功获取了您的第一个 Notion Page
第一次授权时正常，可以切换page，但是在notion删除修改page后，重新授权只能获取一个page

**Comment by Kenshin** [comment]
谢谢反馈，授权 Notion 使用了它的私有 API 难免出现问题，而当出现问题时，简悦会确保 **仅成功获取了您的第一个 Notion Page** 

你看到的这句话，就是因为这个原因。

***

我不清楚你的 Notion 发生了什么问题导致，我也删除过 Page 但也没发生这个问题，最好的办法是，试着在删除的 Page 再建一个，看看。

或者用 Notion web clipper 建立一个 Page 后，再通过简悦授权它。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
