### ISSUE TITLE
【建议】导出md文档时转换下简书的超连接

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#1049]
简书越来越恶心了，点击文章的超链接只能跳转到简书的页面->进行复制->打开新窗口->粘贴url，才能打开超链接
![image](https://user-images.githubusercontent.com/10437293/91689372-92477600-eb96-11ea-9ae7-696ef63c736f.png)
文章里面的url变成了下面这个
![image](https://user-images.githubusercontent.com/10437293/91689427-aee3ae00-eb96-11ea-8adc-10bf63c8476f.png)
作者能否在导出md文档时，转换下这个url，要不然导出的md文档中，点击跳转还是会到简书那个恶心的界面。
简书真的太恶心！！

**Comment by Kenshin** [comment]
谢谢建议。

每篇简书的文章都有这个吗？我可以出个插件来解决，但建议最好给我个 URL 看下。

**Comment by AriaLyy** [comment]
是的，现在简书，的文章，只要有外部连接都这样了，如：https://www.jianshu.com/p/774dfc1c2fb1

**Comment by Kenshin** [comment]
okay 明白了，我可以出个插件解决，简书这么做确实恶心了。

**Comment by AriaLyy** [comment]
感谢大佬

**Comment by Kenshin** [comment]
嗨，我开发了 [清理链接](https://github.com/Kenshin/simpread/issues/2733) 这个插件，专门可以解决此类问题。

所以，我关闭这个 Issues 了。
