### ISSUE TITLE
【站点】BBC文章页

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#105]
请适配 BBC 文章页，谢谢。

测试页面：

中文： http://www.bbc.com/zhongwen/simp/chinese-news-40056223?ocid=socialflow_twitter
英文： http://www.bbc.com/news/uk-41298116

列表页面貌似没有什么规律。

PS：已请速溶咖啡一杯，请查收。

**Comment by Kenshin** [comment]
☕ 666 ~

其实 BBC 已适配，但由于某些已知原因，暂时未出现在适配列表中~
原因请看 https://github.com/Kenshin/simpread/issues/65 解决办法 https://github.com/Kenshin/simpread/issues/89

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，将关闭 issues 。

增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)

你可以暂时使用这个功能来实现阅读模式。

**Comment by Kenshin** [comment]
新增了一批新站，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

除此之外，还包括一批「不存在」的网站，如上述提及的，具体操作方式请看下图
![image](https://user-images.githubusercontent.com/81074/40884334-501fe6c8-6744-11e8-8d39-3ffa6ed2e41a.png)
