### ISSUE TITLE
对于微信公众号的适配问题

### ISSUE THREAD

**Issue by Bogdanxin** [Kenshin/simpread#1050]
可能我过于吹毛求疵了，也有可能是公众号本身的问题，原文格式和字体标题和使用简悦后差别有点大，我看着不是很舒服
原公众号的样式
![image](https://user-images.githubusercontent.com/56074524/91695541-e35c6780-eba0-11ea-90ba-7a176fce9f1b.png)
使用后的样式
![image](https://user-images.githubusercontent.com/56074524/91695718-29b1c680-eba1-11ea-844a-d0a0f6eca8c3.png)
希望能在适配一下，这样看起来更舒服一些，谢谢！！😀

**Comment by Kenshin** [comment]
谢谢反馈，并不是你吹毛求疵，而是微信订阅号确实不怎么样…

可以看看这个链接我描述的说明 https://github.com/Kenshin/simpread/issues/1025#issuecomment-682305717 

你可以把链接发上来，我看下。

**Comment by Bogdanxin** [comment]
https://mp.weixin.qq.com/s/C4c_X-sgTL9gYuW3ptSBxg

**Comment by Kenshin** [comment]
我知道你的问题了，请看我的截图

![image](https://user-images.githubusercontent.com/81074/92066534-b395a580-edd4-11ea-8668-62f7c046eabf.png)


所以，你更改下主题就好了。（我不是说这个主题有问题，而是这个页面的 HTML 确实不是太好。

**Comment by Bogdanxin** [comment]
okok 谢谢

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了代码段的问题。

![image](https://github.com/Kenshin/simpread/assets/81074/e2499dee-a9cd-41f8-94e6-c223c86e86bd)

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
