### ISSUE TITLE
希望通过购买的方式增加授权电脑的台数~~

### ISSUE THREAD

**Issue by aQuaYi** [Kenshin/simpread#1051]
我在公司有两台电脑，家里有一台式机和一个笔记本~
3个授权不够用
我想过再买一个key，可是又希望可以4个设备都是用同一个坚果云同步。

**Comment by Kenshin** [comment]
谢谢建议，会考虑你的诉求，方便上 TG 吗？能上的话，在选项页 → 关于 里面找到 简悦的群，加进来，跟我私聊。

**Comment by aQuaYi** [comment]
已经加入了group，但未收到回复。

**Comment by Kenshin** [comment]
今天有点感冒 😷，晚上回复你。
