### ISSUE TITLE
Medium 加载不出图片的问题

### ISSUE THREAD

**Issue by demom3b** [Kenshin/simpread#1052]
**请说明发生问题的环境**

- 操作系统 **Windows 10**

- 浏览器版本 **Chrome 85.0.4183.83 64位**

- 简悦版本 **2.0.0**

***

目前2.0.0版遇到问题

- 发现在 Medium 的大部分(可能所有的？没有大范围测试，打开了几个得出的结果)文章，打开简悦试图，文章的图片出现加载不出的情况，给别人相同链接，也得出相同的结果，可以使用这个链接：https://towardsdatascience.com/the-ultimate-skill-learning-how-to-learn-9e2fabdc7f1e ，如下图
![image](https://user-images.githubusercontent.com/1833569/91786582-8614f480-ec3a-11ea-84f5-97686e843801.png)

***

> 备注：此暂时无法稳定复现。

- 利用快捷键 `aa -> sr -> nt` 将文章转存至notion，会触发两次存储，并且只在快捷键操作发生；通过鼠标点击的不会出现这个问题，如下图
![image](https://user-images.githubusercontent.com/1833569/91786346-038c3500-ec3a-11ea-9582-1308def57956.png)
多半情况，只有一次存储时成功的，但是另外一个一直会显示存储中，偶尔会出现两次都存储成功的的结果

**Comment by Kenshin** [comment]
谢谢反馈。

> 问题1

很奇怪，我没有遇到过这个情况，请再确认下，是否仅只是某个页面？还是任意？另外，确保你的浏览器仅安装一个简悦。

还是有问题的话，建议在 **隐身模式下，仅启用简悦** 的方式测试。

> 问题2

Medium 的图片采用了惰性加载的方式，所以会存在这个情况的，我先记下来。跟其他一大批新站一起适配。

***

近期提交的新站确实攒了一堆了。😫

**Comment by demom3b** [comment]
问题一的情况，现在我有多试了几个网站，貌似发生的机率不一定；然后我试了试隐身模式之开启简悦，转存至notion，似乎卡在了上传图片到notion这一步，一直在转圈

**Comment by Kenshin** [comment]
> 问题一的情况，现在我有多试了几个网站，貌似发生的机率不一定

把出现问题的 URL 告诉我。

> 隐身模式卡在图片这个问题，不用理会，你可以把这个选项关闭试试

**Comment by demom3b** [comment]
之前出现问题的是公众号的文章，但是我现在试了好几个公众文章以及，别的网站的，都无法复现问题一了，可能是我重启了浏览器之后又好了？等我下次再遇到这个问题的时候再回来补充吧

**Comment by Kenshin** [comment]
@demom3b 

okay 这样的话，我先改下 Issues 拿掉 **问题1** 的内容，等你有需要的时候，再开个 Issues 也行，这个算记 新站的问题。

**Comment by binsee** [comment]
关联 #1104

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

新增加了专门针对 [惰性加载图片的解析方案](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e6%83%b0%e6%80%a7%e5%9b%be%e7%89%87%e5%8a%a0%e8%bd%bd)，如下图

![image](https://user-images.githubusercontent.com/81074/121986734-a7119500-cdc9-11eb-94a2-973e1b1e28a6.png)

注意：使用此功能时会出现维基百科的一些问题，解决方案 [请看这里](https://github.com/Kenshin/simpread/discussions/2347)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
