### ISSUE TITLE
无法适配当前页面，有个小建议，希望开发者可以适配一下微信读书网页版😊😊😊

### ISSUE THREAD

**Issue by timeslip123** [Kenshin/simpread#1053]
发生问题的地址: <https://weread.qq.com/web/reader/03b32ce0717f2af503b18b2k70e32fb021170efdf2eca12>

**Comment by Kenshin** [comment]
微信读书是可以适配的，但这样做有风险。（因为适配后，就可以导出了...
所以我没有适配这类页面，希望理解。

没问题的话，请关闭这个 Issues 😃
