### ISSUE TITLE
自定义站点适配，无法保存规则

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#1054]
**请说明发生问题的环境**

win 10 , chrome latest and simpread latest

**请描述你的问题**

![image](https://user-images.githubusercontent.com/3938751/91792607-7b615c00-ec48-11ea-95a2-038ba40c767c.png)

通过点击站点编辑器
![image](https://user-images.githubusercontent.com/3938751/91792643-9338e000-ec48-11ea-8cee-8d81750aca8e.png)

找到要切的位置
![image](https://user-images.githubusercontent.com/3938751/91792662-9f24a200-ec48-11ea-8aed-82f75fd43455.png)

简悦自动识别的位置
![image](https://user-images.githubusercontent.com/3938751/91792677-a6e44680-ec48-11ea-8aa1-3660774ce381.png)

修改
![image](https://user-images.githubusercontent.com/3938751/91792686-acda2780-ec48-11ea-8cfd-0225d5d7252d.png)

提示
![image](https://user-images.githubusercontent.com/3938751/91792691-b19edb80-ec48-11ea-8d8b-0102c10d39aa.png)

-----

刷新后发现高亮区域没有保存

**Comment by Kenshin** [comment]
我关闭这个 Issues 在 TG 上已经讨论过了。
