### ISSUE TITLE
新版2.0 无法下载md

### ISSUE THREAD

**Issue by nian8** [Kenshin/simpread#1055]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g. MacOS**

- 浏览器版本 **e.g. Chrome 85**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.cnblogs.com/sanshengshui/p/12669011.html>
其他网站有同样的问题

**请描述你的问题**

点击md下载按钮无反应

浏览器控制台报错
Error handling response: TypeError: Cannot read property 'export' of undefined
    at Object.a [as Action] (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:5:14860)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:13:24461
    at o (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:13:24479)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:13:24609
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:1:29230

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈。

但我这边没有遇到问题，请再重新试试，或 **进入隐身模式，并仅启用简悦** 看看是否其他扩展干扰造成的。

**Comment by nian8** [comment]
有一样的问题，Windows下可以正常使用，是不是需要重新安装？

**Comment by nian8** [comment]
重新安装，正常了

**Comment by Kenshin** [comment]
很奇怪的问题，不过搞定就好。

重装时注意备份配置文件，除非你不是高级账户。
