### ISSUE TITLE
关于部分网站加入稍后读后阅读模式异常

### ISSUE THREAD

**Issue by Zettry** [Kenshin/simpread#1056]
- 操作系统 **Windows 10**

- 浏览器版本 **Chromium 80.0.3987.163**

- 简悦版本 **2.0.0**

- 发生问题的地址 [问题网址](https://juejin.im/post/6857671107818979342)

**请描述你的问题**

阅读模式解析没有问题，显示正常。保存到稍后读后，打开稍后读，点击阅读模式显示异常，如图。
查看报错信息如下：
```
Refused to load the script 'http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**截图**

![image](https://user-images.githubusercontent.com/47747981/91858576-f43dd380-ec9b-11ea-9292-fd5df426b8bf.png)

**Comment by Kenshin** [comment]
谢谢反馈，明天确认下。

不过，这个情况也属正常，因为有些页面确实无法通过这种方式解析。

如：动态加载，图片的惰性加载等。

**Comment by DiamondI** [comment]
遇到了同样的问题。

表现是在稍后读的阅读模式中无法使用标注。

![image](https://user-images.githubusercontent.com/18584660/142832390-7d21d48b-f837-4d52-9f57-bb8efcdb47c3.png)

**Comment by Kenshin** [comment]
@DiamondI 

嗨，你的问题跟这个 Issues 的描述无关，另外截图的提示也与你的问题无关。（截图是代码高亮的问题，不用理会）

你可以这样测试下：

1. 是否每个页面都存在这个问题？如果是的话，导出配置文件后重置（或重新安装）简悦，看看能否解决？
2. 如果只是某个页面的话，请告知 URL，同时删除这个页面的稍后读，再重新加入稍后读，看看。

还有，也一并告知你具体的操作（截图 / 录屏）均可。

**Comment by DiamondI** [comment]
@Kenshin 

是某个页面存在这个问题，URL是 https://xueqiu.com/9508834377/153546613。尝试了删除再重新加入，并没有解决问题。

具体的操作如下：

https://user-images.githubusercontent.com/18584660/143004293-27d88b94-413f-4ef5-9747-12563b3d6cbb.mp4

感谢！:smile:

**Comment by Kenshin** [comment]
@DiamondI 

哈哈，我知道问题了。

因为你的标题和描述不准确造成的，你可以根据下图所示开启标注

![image](https://user-images.githubusercontent.com/81074/143006988-af8fb765-e291-4e69-b697-bde965eb77d8.png)

**Comment by DiamondI** [comment]
@Kenshin 

标注是开启的~ 录屏里可以看到，右上角的标注是开启状态😂。我也怀疑过是没打开标注，尝试过再点击一次标注选项，仍然无法通过鼠标选中唤起标注功能。

我想可能还有别的原因？我试过其他页面（知乎的页面），是可以正常标注的~

**Comment by Kenshin** [comment]
@DiamondI 

唉，抱歉，确实开启了。（我眼晕了...  👿 

这个问题可以通过 https://github.com/Kenshin/simpread/issues/3086#issuecomment-974762978 提到的方式完美解决。

如下图：

![image](https://user-images.githubusercontent.com/81074/143008086-0e13f680-2a17-4d79-8825-666d296d97f6.png)

**Comment by DiamondI** [comment]
@Kenshin 

感谢！这套方案完美解决了这个问题，甚至还在探索的过程中发现和obsidian联动的方式，现在去探索一下~ 赞 👍

**Comment by Kenshin** [comment]
@DiamondI 

哈哈，搞定就好。

如果喜欢折腾的话，简悦有 nnnnn 多的玩法，[这些都是 Obsidian 的玩法](https://github.com/Kenshin/simpread/discussions?discussions_q=obsidian)，而且还有隐藏（未发布）方案，看你能否找到了 

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏

**Comment by DiamondI** [comment]
@Kenshin 

我用的是 Edge 上的~ 在 edge store 上留五星好评啦~ 👍

**Comment by Kenshin** [comment]
@DiamondI 

哈哈，谢谢。

我关闭这个 Issues 了。
