### ISSUE TITLE
Dropbox提示应用被冻结

### ISSUE THREAD

**Issue by Vstory** [Kenshin/simpread#106]
![dropbox](https://user-images.githubusercontent.com/20795557/30538648-96f73394-9ca1-11e7-9703-5875a33c3996.jpg)
 
授权失败，提示`This app is unable to link additional users because it has been frozen pending review.`

**Comment by Kenshin** [comment]
感谢提示，这是正常的（下图），因为 Dropbox 最多只能使用 500 人，接近后，需要申请 `Apply for production`

我已经申请了，需要审核...

![image](https://user-images.githubusercontent.com/81074/30538867-7b31e788-9c35-11e7-99b5-5f0bb48a572b.png)

**Comment by Vstory** [comment]
感谢回复与解答😁

**Comment by Kenshin** [comment]
为了防止其他用户重复提问，我先 Re-open 这个 issues 了，等到审核通过后再关闭。 😃

**Comment by lamtsui0620** [comment]
好的 谢谢

**Comment by Kenshin** [comment]
@Vstory @lamtsui0620 
审核已通过，可以正常使用了~  👏  😘 

![image](https://user-images.githubusercontent.com/81074/30621509-2dcbb22a-9d71-11e7-9c56-2925cc38be49.png)
