### ISSUE TITLE
markdown导出网页内容无反应

### ISSUE THREAD

**Issue by GengchenXU** [Kenshin/simpread#1060]
**请说明发生问题的环境**
Windows2004 chorme浏览器简悦版本 **2.0.0**
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
使用markdown导出文件时无反应，我edge使用的老版本就没问题

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
什么 URL 还是说所有的页面？

**Comment by GengchenXU** [comment]
> 什么 URL 还是说所有的页面？

我又重新安装发现又没问题了，不知道为什么

**Comment by Kenshin** [comment]
没问题就好。

发生问题的版本是全新安装的？还是升级到 2.0.0 ？
如果是后者的话，能否记得是哪个版本升级的？
