### ISSUE TITLE
希望优化一下这个地方的字体颜色，黄底黑色更清晰一些~

### ISSUE THREAD

**Issue by TakakiRey** [Kenshin/simpread#1062]
![image](https://user-images.githubusercontent.com/64317019/92084376-e0a87f00-edf9-11ea-912c-b8e83c5da8b8.png)

**Comment by Kenshin** [comment]
谢谢反馈，这个黄色确实有些问题。

下个版本会修复这个问题。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
