### ISSUE TITLE
看雪论坛阅读模式显示异常

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1063]
看雪论坛帖子页，使用阅读模式时，简悦正常确定了要显示的内容，但页面不显示上半部分内容。

----

## 复现示例

示例页面：https://bbs.pediy.com/thread-261772.htm
站点适配：未使用/使用自行适配规则，都出现此问题

自行适配规则如下：

- ID：`o5rx7zi0-6EdAMUkjZg` （刚提交到 站点集市了，但未经审核通过）
- 标识：`看雪论坛-帖子页`
- 域名：`http*://bbs.pediy.com/thread-*`
- 标题：`[[{$('meta[name=keywords]').attr('content')}]]`
- 描述：`[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]`
- 高亮区域：`[[[$('div.message:first')]]]`

----

## 问题说明

阅读模式效果：

页面不显示上半部分内容
![image](https://user-images.githubusercontent.com/5285894/92114318-35142480-ee23-11ea-9b56-2d8dc797145e.png)

## 问题分析

经过检查css，发现若取消 `.simpread-read-root`  中的 `align-items: center;`样式，则能正常显示：

![image](https://user-images.githubusercontent.com/5285894/92114598-af44a900-ee23-11ea-9992-6200e8137808.png)

![image](https://user-images.githubusercontent.com/5285894/92114732-ec10a000-ee23-11ea-9e00-499e1874f8da.png)

**Comment by Kenshin** [comment]
嗨，谢谢自行适配，我太需要（喜欢）这样动手能力超强的用户了。

***

关于你的问题，可以通过适配编辑器中的 **自定义 CSS** 解决，位置如下：

![image](https://user-images.githubusercontent.com/81074/92191335-1b5ff500-ee96-11ea-8f62-3f1d412bac3f.png)

这个地方的 CSS 仅针对当前适配页面有效，同时也可以使用 **全局的自定义样式** 解决，位置在

选项页 → 高级设定 → 左上角 menu → （点击）自定义样式 即可找到。

***

当然，其实没必要使用全局的定制，只是跟你提了下。😀

**Comment by binsee** [comment]
感谢。增加了如下自定义CSS后解决：

```css
.simpread-read-root {
align-items: baseline;
}
```

**Comment by Kenshin** [comment]
太棒了，我看下会把它放到主适配列表中。

**Comment by Kenshin** [comment]
嗨，周末好，你可以把适配的两个站以 PR 的形式提交给我，我 Merge 后，你可以作为贡献者出现在简悦的 repo 里面，我觉得这样更好。

***

另外，不知道是否对其它待适配的站感兴趣？如果可以的话，你可以随便挑一些感兴趣的站点，地址在 https://twitter.com/wanglei001/status/1301722820922155008?s=19 

最近攒了太多的站，确实也分身乏术。 😂

***

当然，你也可以忽略这些内容。😃

**Comment by binsee** [comment]
好的，稍后我提交pr。
至于适配其他站点，有闲暇时间的话，我也愿意略尽点力。

**Comment by Kenshin** [comment]
👌🏻 从 develop 分支 PR

**Comment by binsee** [comment]
已提交pr #1067 ，但有个commit把全文修改了，在vscode中看不到的空白修改，对比了不是空格缩进和换行符导致的，有点搞不清楚原因。

请教下项目的冒号对齐使用的插件是？我只能手动缩进对齐了

另外在twitter页面找不到要适配的站点列表，可能是因为我不熟悉Twitter的缘故？

**Comment by Kenshin** [comment]
@binsee 

哈哈，抱歉是我给你的 URL 错了。跟 twitter 没任何关系，正确的 URL 是
https://github.com/Kenshin/simpread/labels/new%20site

**Comment by binsee** [comment]
啊哈，ok
