### ISSUE TITLE
markdown 下载代码  *  [ ] _ 都会被添加上转义字符 \

### ISSUE THREAD

**Issue by lzq1126** [Kenshin/simpread#1064]
```
// 归并排序（C-迭代版）
int min(int x, int y) {
    return x < y ? x : y;
}
void merge\_sort(int arr\[\], int len) {
    int\* a = arr;
    int\* b = (int\*) malloc(len \* sizeof(int));
    int seg, start;
    for (seg = 1; seg < len; seg += seg) {
        for (start = 0; start < len; start += seg + seg) {
            int low = start, mid = min(start + seg, len), high = min(start + seg + seg, len);
            int k = low;
            int start1 = low, end1 = mid;
            int start2 = mid, end2 = high;
            while (start1 < end1 && start2 < end2)
                b\[k++\] = a\[start1\] < a\[start2\] ? a\[start1++\] : a\[start2++\];
            while (start1 < end1)
                b\[k++\] = a\[start1++\];
            while (start2 < end2)
                b\[k++\] = a\[start2++\];
        }
        int\* temp = a;
        a = b;
        b = temp;
    }
    if (a != arr) {
        int i;
        for (i = 0; i < len; i++)
            b\[i\] = a\[i\];
        b = a;
    }
    free(b);
}

```

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

代码高亮问题会集中反馈到 #500 我先记录下。

**Comment by p5ydn0** [comment]
> 嗨，谢谢反馈。
> 
> 代码高亮问题会集中反馈到 #500 我先记录下。

有的一些网站会自动加转义字符，有的不会。这个确实是个经常会遇到的 bug。

**Comment by Kenshin** [comment]
@p5ydn0 

收到！

**Comment by p5ydn0** [comment]
新版本好多 bug。

**Comment by Kenshin** [comment]
@p5ydn0

应该就是转义之类的问题，而且这些功能我没改过代码。还有其它问题吗？

**Comment by Kenshin** [comment]
关联问题 https://github.com/Kenshin/simpread/issues/743

**Comment by p5ydn0** [comment]
> @p5ydn0
> 
> 应该就是转义之类的问题，而且这些功能我没改过代码。还有其它问题吗？

有的。

我没有刻意记录，稍微找了下如：

1. 除代码部分外，部分标题中的 `.` 也会自动添加转义字符。举例文章：https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/。
2. 代码部分整体“错位”。就是本应该是在 A 位置的代码模块出现在了 A 之后的 B 位置，整体都“向下错位一个单位”。举例文章：http://liyangbit.com/pythonvisualization/matplotlib-top-50-visualizations/。

这两个都是需要后期花不少时间修正的问题。其它的我后面刻意留意下，然后反馈给你。

***

还有个我想请教的问题是：因为我最近一直在“重度使用”该插件，并且绝大部分文章都是有代码的。所以有没有什么方法能让我先暂时用之前的 1.0 版本，待你将 bug 修复后我再换回来。

我尝试了如下方法均未成功：

* 项目 readme 文件中的 **离线下载** 链接失效；
* 卸载插件后重新通过 Chrome 应用商店安装。

谢谢。

**Comment by Kenshin** [comment]
@p5ydn0 

你说的这两个问题不需要更新版本就可以解决，只是请给我时间来修复这些，前阵子太忙了，一直再做客服，明天开始希望能有时间，我会优先解决转义的问题。

另外，再重申下，你说的这些问题跟 1.x 没有关系，只是跟 代码高亮插件 有关。

我会先确认 1.x 是否存在这些问题，如果确实如你所说，我会给你 zip

**Comment by Kenshin** [comment]
@p5ydn0 

再提一句，有任何关于转义的问题，请告诉我 URL ，越多越好，这样才能更好的解决问题。

而不要「没刻意记录」🙏🏻

**Comment by varg1714** [comment]
> @p5ydn0
> 
> 再提一句，有任何关于转义的问题，请告诉我 URL ，越多越好，这样才能更好的解决问题。
> 
> 而不要「没刻意记录」🙏🏻

https://mp.weixin.qq.com/s/XvtsCF0ciye3bMbnfrh4Vw在这里链接里代码的注释也被加上了转义字符

**Comment by Kenshin** [comment]
@varg1714 

收到，下周修复这个问题。

**Comment by Kenshin** [comment]
找到转义的问题了，罪魁祸首是 https://github.com/domchristie/turndown 这个包导致的，我再想办法解决。

**Comment by Kenshin** [comment]
各位，问题解决了，一个悲伤的事情是：**因为是 library 出现了问题，所以只能下个版本解决**。

不过，我试试用 **插件** 的方式绕过这个问题。

***

### 涉及到的范围

> 全部需要使用 Markdown 的地方均存在此问题。

### 如何处理

> 等我的插件来解决

**Comment by Kenshin** [comment]
罪魁祸首，看下图

![image](https://user-images.githubusercontent.com/81074/92341119-4db85f00-f0ef-11ea-959c-742bbd93b065.png)

**Comment by GengchenXU** [comment]
https://blog.csdn.net/weixin_36888577/article/details/79937886
![image](https://user-images.githubusercontent.com/56543168/92400398-7461ae80-f15e-11ea-8bdf-24c82451c989.png)
![image](https://user-images.githubusercontent.com/56543168/92400406-762b7200-f15e-11ea-8b52-baf565b2ba49.png)

**Comment by Kenshin** [comment]
各位

我近期要升级一个 **新的版本 2.0.0.90xx** 具体时间未知，但开发时间从今日（ 9/08 ）开始，预计三天时间，因为不是新功能，所以不会花费太长时间，此补丁版修复了从 2.0.0 发布以来的一些问题，比如 **Markdown 转义错误的问题**，细节我会另行通知。

***

如果你可以等待此补丁版的话，建议多等待几天（最迟不超过一周），否则的话，请使用 **[离线版](http://ksria.com/simpread/crx/2.0.0/simpread.zip)** 

离线版解决了 Markdown 转义错误的问题，但离线版无法升级，所以 **请务必在安装离线版后，切勿删除 Chrome 应用商店版**，禁用即可。

同时这个 Issues 我也不会关闭，等新版发布后，我会在这里同时大家，并且关闭 Issues

**Comment by p5ydn0** [comment]
> 各位
> 
> 我近期要升级一个 **新的版本 2.0.0.90xx** 具体时间未知，但开发时间从今日（ 9/08 ）开始，预计三天时间，因为不是新功能，所以不会花费太长时间，此补丁版修复了从 2.0.0 发布以来的一些问题，比如 **Markdown 转义错误的问题**，细节我会另行通知。
> 
> 如果你可以等待此补丁版的话，建议多等待几天（最迟不超过一周），否则的话，请使用 **[离线版](http://ksria.com/simpread/crx/2.0.0/simpread.zip)**
> 
> 离线版解决了 Markdown 转义错误的问题，但离线版无法升级，所以 **请务必在安装离线版后，切勿删除 Chrome 应用商店版**，禁用即可。
> 
> 同时这个 Issues 我也不会关闭，等新版发布后，我会在这里同时大家，并且关闭 Issues
> 
> > 注意：此版本 **仅解决了转义问题**，如果有代码高亮的问题，属于这个 **代码高亮插件本身的问题，不涉及到简悦扩展**，等待我的通知。

辛苦了！谢谢！❤️

**Comment by lzq1126** [comment]
非常感谢。请问有什么 qq 或者钉钉、微信交流群吗？可以更方便大家交流。

**Comment by Kenshin** [comment]
@lzq1126 

目前只有电报群 https://t.me/simpread 和 https://t.me/simpreadgroup

**Comment by lzq1126** [comment]
作者，2.0.0.90xx  这个版本啥时候能更新呀？ 等好久啦。

**Comment by lzq1126** [comment]
> @lzq1126
> 
> 目前只有电报群 https://t.me/simpread 和 https://t.me/simpreadgroup

2.0.0.90xx 这个版本啥时候更新呀？

**Comment by Kenshin** [comment]
@lzq1126 

其实早就可以发布了，因为想带来一个更有意思的版本，所以 **滚雪球，越滚越大**...  预计发布时为 2.0.1

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了 **转义错误的问题**。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。

**Comment by p5ydn0** [comment]
@Kenshin 

你好，刚更新后发现，代码“错位” bug 仍然存在。

复现方法：https://realpython.com/regex-python/ —— 保存为 markdown，搜索 `Alternatively`，其下面的代码位置错误。

更多信息：

* macOS Big Sur 11.0.1
* SimpRead 2.1.0

谢谢。

**Comment by Kenshin** [comment]
@p5ydn0 

嗨，代码段错误是 [另外一个问题](https://github.com/Kenshin/simpread/issues/500)，跟转义无关。（PS：我也没说错位也改正了  😅 

此 Issues 仅关于转义错误的修正。

**Comment by p5ydn0** [comment]
> @p5ydn0
> 
> 嗨，代码段错误是 [另外一个问题](https://github.com/Kenshin/simpread/issues/500)，跟转义无关。（PS：我也没说错位也改正了 😅
> 
> 此 Issues 仅关于转义错误的修正。

哦哦，抱歉，那是我没看清。

那错位 bug 的处理优先级会高一点吗？这个感觉也是很核心的。

另外，我刚试了下你之前发的那个离线版，对应部分代码没有错位，但是有些代码导出后会消失。

**Comment by Kenshin** [comment]
> 哦哦，抱歉，那是我没看清。

没关系~

关于错为的问题，是因为 **代码高亮插件** 造成的，你可以关闭这个插件，这样代码高亮没有了。

***

代码高亮插件总是出错的问题在于：**代码高亮的规则太多了，且几乎没有什么规律**，实在没什么好办法确保全部覆盖。

所以，建议在这种情况下，**多使用聚焦模式，而非阅读模式**。

代码高亮与 LateX 之类的问题完全不一样，后者是有规则的，所以很好适配。前者完全没规则，想怎么弄就能怎么弄（高亮）...
