### ISSUE TITLE
mac中浏览器使用阅读模式无法复制文本，使用原始网页可以复制

### ISSUE THREAD

**Issue by xhj872621336** [Kenshin/simpread#1065]
mac电脑使用谷歌浏览器开启阅读模式后无法复制文本，使用原始网页浏览时，可以复制选中文本

**Comment by Kenshin** [comment]
谢谢反馈。

在标注模式中是无法使用 **复制/粘贴** 的，你需要 **暂时关闭** 标注功能，位置在 阅读模式 → 右下角 → 标注 icon

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
