### ISSUE TITLE
导出时因标题包含 Windows 设备文件名字符无法解析的问题

### ISSUE THREAD

**Issue by eallion** [Kenshin/simpread#1066]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **`Win 10 2004`**

- 浏览器版本 **`Chrome 85.0.4183.83 64`**

- 简悦版本 **`2.0.0`**

- 发生问题的地址 <请填写你的地址l>
    - <https://blog.lhwcrt.top/tech/welcome-to-fcitx5/>
    - <https://eallion.com/ubuntu2004/>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

目前遇到的问题是，上述两个网页（其实还有更多，上次的被我修改掉了），通过动作保存到 GitHub 后，不能在其他 Windows 设备上 `Pull` 或者 `Clone`。  
原因应该是文件名包含 Windows 不支持的字符，如：`:`  `|`

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

![批注 2020-09-04 210043](https://user-images.githubusercontent.com/1698841/92242893-15e4c800-eef3-11ea-9f1d-b03cad1291af.png)

**建议**

希望可以加入正则或其他方式，在导出的时候过滤掉或替换掉类似的字符。

**Comment by eallion** [comment]
Ubuntu 20.04.1 无此问题。

![2020-09-04_21-19](https://user-images.githubusercontent.com/1698841/92243680-6e689500-eef4-11ea-8344-965f36ee44c2.png)

**Comment by Kenshin** [comment]
谢谢反馈。

哎，竟然是 Windows 的锅，好久没用了，可以用正则的，但是我不清楚哪些是符合要求的标题...

不过，只能下个版本修复了。

**Comment by Kenshin** [comment]
emmm 我可以出一个插件解决标题的问题，但前提仍旧是我 **需要知道哪些字符是非法** 的...

你的问题跟 https://github.com/Kenshin/simpread/issues/1068 一样，其实只要修改标题就行了，这也是我可以出个插件解决的原因。

**Comment by eallion** [comment]
Google 了一下，大概查得此 Wiki。
- <https://en.wikipedia.org/wiki/Filename#In_Windows>

<table><tbody><tr><th>Character</th><th>Name</th><th>Reason for prohibition</th></tr><tr><td><code>/</code></td><td><a href="/wiki/Slash_(punctuation)" title="Slash (punctuation)">slash</a></td><td>Used as a path name component separator in Unix-like, Windows, and Amiga systems. (For as long as the <a href="/wiki/SwitChar" title="SwitChar">SwitChar</a> setting is set to '/', the DOS <a href="/wiki/COMMAND.COM" title="COMMAND.COM">COMMAND.COM</a> shell would consume it as a switch character, but DOS and Windows themselves always accept it as a separator on API level.)<br>The big&nbsp;solidus ⧸ (<a href="/wiki/Unicode#Architecture_and_terminology" title="Unicode">Unicode code point</a> U+29F8) is permitted in Windows filenames.</td></tr><tr><td><code>\</code></td><td><a href="/wiki/Backslash" title="Backslash">backslash</a></td><td>Used as the default path name component separator in DOS, OS/2 and Windows (even if the <a href="/wiki/SwitChar" title="SwitChar">SwitChar</a> is set to '-'; allowed in Unix filenames, see <a href="#Anc1">Note 1</a>).<br>The big reverse solidus ⧹ (U+29F9) is permitted in Windows filenames.</td></tr><tr><td><code>?</code></td><td><a href="/wiki/Question_mark" title="Question mark">question mark</a></td><td>Used as a wildcard in Unix, Windows and <a href="/wiki/AmigaOS" title="AmigaOS">AmigaOS</a>; marks a single character. Allowed in Unix filenames, see <a href="#Anc1">Note 1</a>.<br>The <a href="/wiki/Inverted_question_mark" title="Inverted question mark">inverted question mark</a> ¿ (U+00BF) and the <a href="/wiki/%E2%81%87" title="⁇">double question mark</a> ⁇ (U+2047) are allowed in all filenames.</td></tr><tr><td><code>%</code></td><td><a href="/wiki/Percent_sign" title="Percent sign">percent</a></td><td>Used as a wildcard in <a href="/wiki/RT-11" title="RT-11">RT-11</a>; marks a single character. Not special on Windows.</td></tr><tr><td><code>*</code></td><td><a href="/wiki/Asterisk" title="Asterisk">asterisk</a><br><i>or</i> star</td><td>Used as a wildcard in Unix, DOS, RT-11, VMS and Windows. Marks any sequence of characters (Unix, Windows, DOS) or any sequence of characters in either the basename or extension (thus "*.*" in DOS means "all files". Allowed in Unix filenames, see <a href="#Anc1">Note 1</a>.<br>The asterisk operator ∗ (U+2217) is allowed in Windows filenames</td></tr><tr><td><code>:</code></td><td><a href="/wiki/Colon_(punctuation)" title="Colon (punctuation)">colon</a></td><td>Used to determine the mount point / drive on Windows; used to determine the virtual device or physical device such as a drive on AmigaOS, <a href="/wiki/RT-11" title="RT-11">RT-11</a> and VMS; used as a pathname separator in <a href="/wiki/Classic_Mac_OS" title="Classic Mac OS">classic Mac OS</a>. Doubled after a name on VMS, indicates the DECnet nodename (equivalent to a NetBIOS (Windows networking) hostname preceded by "\\".). Colon is also used in Windows to separate an <a href="/wiki/Alternate_data_stream" title="Alternate data stream">alternative data stream</a> from the main file.<br>The <a href="/wiki/Colon_(letter)" title="Colon (letter)">letter colon</a> ꞉ (U+A789) and the <a href="/wiki/Ratio#Notation_and_terminology" title="Ratio">ratio symbol</a> ∶ (U+2236) are permitted in Windows filenames.</td></tr><tr><td><code>|</code></td><td><a href="/wiki/Vertical_bar" title="Vertical bar">vertical bar</a><br><i>or</i> pipe</td><td>Designates <a href="/wiki/Pipeline_(Unix)" title="Pipeline (Unix)">software pipelining</a> in Unix, DOS and Windows; allowed in Unix filenames, see <a href="#Anc1">Note 1</a>. The <a href="/wiki/Dental_click" title="Dental click">dental click</a> ǀ (U+01C0) is permitted in Windows filenames.</td></tr><tr><td><code>"</code></td><td><a href="/wiki/Quotation_mark" title="Quotation mark">quote</a></td><td>Used to mark beginning and end of filenames containing spaces in Windows, see <a href="#Anc1">Note 1</a>. <a href="/wiki/Quotation_marks_in_English" title="Quotation marks in English">Curved quotes</a> “ and ″ (U+201C and 201D) are permitted anywhere in filenames.</td></tr><tr><td><code>&lt;</code></td><td><a href="/wiki/Inequality_(mathematics)" title="Inequality (mathematics)">less than</a></td><td>Used to <a href="/wiki/Redirection_(computing)" title="Redirection (computing)">redirect input</a>, allowed in Unix filenames, see <a href="#Anc1">Note 1</a>.</td></tr><tr><td><code>&gt;</code></td><td><a href="/wiki/Inequality_(mathematics)" title="Inequality (mathematics)">greater than</a></td><td>Used to <a href="/wiki/Redirection_(computing)" title="Redirection (computing)">redirect output</a>, allowed in Unix filenames, see <a href="#Anc1">Note 1</a>.</td></tr><tr><td><code>.</code></td><td><a href="/wiki/Full_stop" title="Full stop">period</a><br><i>or</i> dot</td><td>Allowed, but the last occurrence will be interpreted to be the extension separator in VMS, DOS, and Windows. In other OSes, usually considered as part of the filename, and more than one period (full stop) may be allowed. In Unix, a leading period means the file or folder is normally hidden.</td></tr><tr><td><code>,</code></td><td><a href="/wiki/Comma" title="Comma">comma</a></td><td>Allowed, but treated as separator by the command line interpreters COMMAND.COM and CMD.EXE on DOS and Windows.</td></tr><tr><td><code>;</code></td><td><a href="/wiki/Semicolon" title="Semicolon">semicolon</a></td><td>Allowed, but treated as separator by the command line interpreters COMMAND.COM and CMD.EXE on DOS and Windows.</td></tr><tr><td><code>=</code></td><td><a href="/wiki/Equals_sign" title="Equals sign">equals sign</a></td><td>Allowed, but treated as separator by the command line interpreters COMMAND.COM and CMD.EXE on DOS and Windows.</td></tr><tr><td><code></code></td><td><a href="/wiki/Space_(punctuation)" title="Space (punctuation)">space</a><br></td><td>Allowed, but the space is also used as a parameter separator in <a href="/wiki/Command_line" title="Command line">command line</a> applications. This can be solved by quoting the entire filename.</td></tr></tbody></table>

**Comment by eallion** [comment]
起初我也是去仓库里面改文件名，但几次之后就感觉不方便，也不符合 Geek 精神，能用代码搞定的事肯定不愿用笨重的办法去做。

**Comment by Kenshin** [comment]
> 起初我也是去仓库里面改文件名，但几次之后就感觉不方便，也不符合 Geek 精神，能用代码搞定的事肯定不愿用笨重的办法去做。

嗯，不应该用手动方式改。

我用正则把上面的符号都屏蔽掉，完成后插件会通知你。

**Comment by Kenshin** [comment]
嗨，我解决了这个问题，你可以安装相应的插件，细节请看 https://github.com/Kenshin/simpread/issues/1093
