### ISSUE TITLE
导出时因为标题含有特殊字符导致失败

### ISSUE THREAD

**Issue by ifwere** [Kenshin/simpread#1068]
- 操作系统 **MacOS 10.14.6**

- 浏览器版本 **Chrome 85.0.4183.83**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s?__biz=Mzg2OTIyMzY0Ng==&mid=2247483696&idx=1&sn=5fd8a3d57308bdbf993ab7545c141a8e&chksm=cea11c81f9d69597487bf17018dba4d329a491c98abed4d6f1b1a88a83abcd2a2d8cfe18a2c7&scene=178#rd>

**该页面含有较多图片，启用阅读模式后，选择导出为 HTML 或者 离线 HTML 时，会提示马上请稍等，然后无反应，不报错，不下载*

**Comment by Kenshin** [comment]
谢谢反馈，这个问题跟 https://github.com/Kenshin/simpread/issues/1066 类似，都是因为标题含有特殊符号导致的问题。

目前只能下个版本修复，

暂时的解决办法是：你可以手动修改标题，如 **个人使用vpn翻墙是否违法？基于规范性法律文件、案例以及相关计算机技术的分析与讨论**

我可以出个插件来解决这个问题，到时候会通知你。

PS：这个标题的好吓人...

**Comment by Kenshin** [comment]
关联问题 #705

**Comment by Kenshin** [comment]
嗨，我解决了这个问题，你可以安装相应的插件，细节请看 https://github.com/Kenshin/simpread/issues/1093
