### ISSUE TITLE
新浪科技阅读模式失败

### ISSUE THREAD

**Issue by cranelee** [Kenshin/simpread#107]
http://tech.sina.com.cn/t/2017-09-19/doc-ifykywuc6856190.shtml

**Comment by Kenshin** [comment]
😉 感谢提醒，关联问题以及解决方案请看 https://github.com/Kenshin/simpread/issues/90

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> 匹配失败后，自动退出阅读模式，并启动临时阅读模式，可继续生成阅读模式的页面。

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update
