### ISSUE TITLE
进入阅读模式白屏

### ISSUE THREAD

**Issue by Sirius891006** [Kenshin/simpread#1070]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **windows10**，这个问题应该与平台无关，我在windows上的edge和ubuntu虚拟机上使用chrome都遇到同样的问题。设置是通过dropbox同步的。

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 ：所有网页进入阅读模式都不行

设置的快捷键是RR
进入阅读模式之后，网页上全白，无任何信息，键盘退出键也失效，只能关闭网页。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![微信截图_20200905093541](https://user-images.githubusercontent.com/46483844/92294088-511ae180-ef5b-11ea-97fe-d0e771c19299.png)
![微信截图_20200905093517](https://user-images.githubusercontent.com/46483844/92294091-54ae6880-ef5b-11ea-9dea-7be8dccb92a7.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
是每个页面都这样？还是具体的页面？最好把 URL 给我。

另外，请在 **隐身模式下仅启用简悦**，试试，排除其他扩展的干扰。

**Comment by Sirius891006** [comment]
所有网页都这样，这是其中一个网页
https://user.guancha.cn/main/content?id=375155&s=fwzxhfbt

**Comment by Kenshin** [comment]
我看了，我这边是没问题的。所以，还是要测试下上条说的方式。

如果还不行的话，请 导出配置文件后重置简悦

**Comment by Sirius891006** [comment]
请在 隐身模式下仅启用简悦，确实恢复正常了，但是现在不知道是什么插件引起了冲突。

**Comment by Kenshin** [comment]
> 请在 隐身模式下仅启用简悦，确实恢复正常了，但是现在不知道是什么插件引起了冲突。

看了下，估计你是用的护眼模式造成的。

**Comment by Kenshin** [comment]
嗨，没问题的话，我关闭这个 Issues 了。
