### ISSUE TITLE
阅读模式为暗色情况下，标注颜色有错误

### ISSUE THREAD

**Issue by MingzGeek** [Kenshin/simpread#1072]
第二次打开标注过的网页或者说文档时，标注出现bug？
标注过的段落，整段的标点符号都被高亮出
![简悦-反馈](https://user-images.githubusercontent.com/62588730/92296772-9266bd80-ef6a-11ea-8660-2a8b40605b46.png)
来

**Comment by MingzGeek** [comment]
再补充个，主题色为绀鼠和黑鸢时，标注的样式（如下划线，手写体等）会导致字体对比度下降，阻碍阅读。图如下：
![反馈2](https://user-images.githubusercontent.com/62588730/92296895-27b68180-ef6c-11ea-8849-d47f1aabedd5.png)
![image](https://user-images.githubusercontent.com/62588730/92296889-1c635600-ef6c-11ea-8c21-5cef818818f2.png)
![image](https://user-images.githubusercontent.com/62588730/92296899-369d3400-ef6c-11ea-99ec-b4fa8ac44955.png)

**Comment by Kenshin** [comment]
谢谢反馈。

> 第一个问题

确实有这种情况存在，因为标注逻辑是通过上下文来寻找之前的位置，**如果标注内容较少或标注页面的内容重复率很高** 的话，会出现问题。

虽然这种概率很小，并有算法判断，但毕竟无法 100% 避免。

为了避免这种问题，最好的方式是：**标注时内容稍微多些**。

***

> 第二个问题

谢谢反馈，下个版本解决它。

**Comment by MingzGeek** [comment]
你好，非常感谢你能给反馈进行及时的回复，这让快乐粉看到了简悦这个插件（可能即将有桌面，或者APP?）的光明前景
以下是使用的另两个反馈，侧重在应用体验上，而不算BUG：
1、标注侧栏现在已有拖拽式调节顺序按钮，如果还能提供上下文顺序式按钮可能会更好？
原因：有很多时候会反复进行阅读，可能会在前文浏览过但未标注的地方进行标注，然而这样标注的顺序是在标注侧栏的最末端，不便于打印阅读。如果手动调节，又过于麻烦


2、句子标注能否提供按键式的菜单栏选项？
原因：鼠标滑动的过程，已标注过的地方总会自动地弹出标注选项栏，这样偶尔会误触，改变标注情况。而总不可能将标注模式时开时关，较为麻烦。如果能提供点击式菜单栏的切换选项，应该会更好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月5日(星期六) 中午1:01
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"张明-武汉大学"<3537587669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 新版本的标注模式和稍后读结合问题 (#1072)





 
谢谢反馈。
  
第一个问题
  
确实有这种情况存在，因为标注逻辑是通过上下文来寻找之前的位置，如果标注内容较少或标注页面的内容重复率很高 的话，会出现问题。
 
虽然这种概率很小，并有算法判断，但毕竟无法 100% 避免。
 
为了避免这种问题，最好的方式是：标注时内容稍微多些。
 
  
第二个问题
  
谢谢反馈，下个版本解决它。

**Comment by MingzGeek** [comment]
hhh，当然不是恰饭的意思，而是一种，嗯，荣誉和凭借？比如GitHub，3000星？hh
标注是习惯啦，看的时候习惯顺带标注，ipad坏了，手里却还没能换新，拮据且无奈hh
祝越来越好呀~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月5日(星期六) 下午3:12
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"简悦快乐粉"<3537587669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 新版本的标注模式和稍后读结合问题 (#1072)





  
这让快乐粉看到了简悦这个插件（可能即将有桌面，或者APP?）的光明前景
  
猜测你是新用户吧？如果是老用户的话，应该不会有这个疑惑的，简悦是 17年的产物，一直到 2.0（8月份）前都是免费提供给大家使用的。所以，免费的时候没有停止，更何况现在有钱了。（还有，我不是靠简悦来维系生活的，否则应该早就饿死了...
 
 
关于 问题1  我会考虑这个方式。
 
关于 问题2 涉及到了交互，暂时不会有大的调整，因为一旦有新的交互，用户的习惯又要重新适应下。但这不意味着我不会考虑你说的方式。
 
另外一个关于2的问题：我发现你截图中的标注确实太密集了，也容易出现此问题。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
