### ISSUE TITLE
云同步配置文件的建议

### ISSUE THREAD

**Issue by linxilee** [Kenshin/simpread#108]
建议添加Onedrive等不被墙影响的网盘备份

**Comment by Kenshin** [comment]
感谢建议，已经再计划中了（之前也有用户提过），下个版本加入。 😄

其实我加了 Dropbox 之后才发现话它需要科学上网的… 😰😱

**Comment by piumnl** [comment]
@Kenshin 感觉onedrive也不稳定，如果可以希望添加坚果云的同步备份。^_^

**Comment by Kenshin** [comment]
@piumnl 
坚果云早就考虑过，但是它没有 API ...  😂

**Comment by piumnl** [comment]
@Kenshin 诶，`WebDAV ` 上传下载不行吗？>_<

**Comment by Kenshin** [comment]
@piumnl 
可以研究下 WebDAV 能否在 chrome extension 下使用...
话说，你对同步的需求这么强烈。 😸

**Comment by piumnl** [comment]
主要是公司电脑和家里的电脑不同步会有强迫症，每次修改配置都要重复两边。
像 __稍后读__ 没有同步感觉用处就不大了。

作者如此耐心，给个赞！！！>_<

**Comment by Kenshin** [comment]
@piumnl 
客气哈~ 我打算做后台静默同步的功能，但发现一圈也就是 Dropbox 可以支持，其它的 service 大多一段时间就自动过期了...

我也是多台电脑，每次都是最后手动点击同步，换台电脑的话，再点击次同步...  😂

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

增加了 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

以及将配置文件保存到 [坚果云](http://ksria.com/simpread/docs/#/坚果云) 的功能。

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
