### ISSUE TITLE
提取知乎回答，没必要提取评论，不重要

### ISSUE THREAD

**Issue by sher0luo** [Kenshin/simpread#1080]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/21417080>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
<img width="891" alt="截屏2020-09-06 02 17 45" src="https://user-images.githubusercontent.com/70817034/92311182-71907d80-efe7-11ea-8ae3-6de295d93122.png">

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by binsee** [comment]
你遇到的问题是因为当前的匹配规则失效导致的，更新适配规则即可。

**Comment by binsee** [comment]
新适配规则：https://github.com/Kenshin/simpread/issues/894#issuecomment-687647149

**Comment by Kenshin** [comment]
@binsee

等更新完这一批站点时一起发布，目前手动更新方式还没有太好的方案，只能一行一行复制粘贴。

我在站点编辑器里面考虑加个直接读取剪切板更新方式

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
