### ISSUE TITLE
标注的文章标题有问题

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#1085]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本 Chrome 

- 简悦版本 2.0.0

- 发生问题的地址 https://github.com/JsonChao/Awesome-Android-Interview/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%92%8C%E7%AE%97%E6%B3%95/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95.md

**请描述你的问题**
标注的标题有问题，并不是该文章的标题～～
![image](https://user-images.githubusercontent.com/10437293/92352170-0f7f6780-f110-11ea-8b16-9c4bb9d81bf7.png)

**Comment by Kenshin** [comment]
哈哈，看起来这个页面没适配吧。
取的标题有点喜感。😂

**Comment by Kenshin** [comment]
你可以自己改下的

**Comment by AriaLyy** [comment]
好吧～～

**Comment by Kenshin** [comment]
看下图所示，获取的没有问题。

![image](https://user-images.githubusercontent.com/81074/92360536-8b34e080-f11f-11ea-9188-bd9bcf3a91c8.png)
