### ISSUE TITLE
刚买、配置文件被dropbox 老账户的覆盖了、何解？

### ISSUE THREAD

**Issue by songmeixu** [Kenshin/simpread#1088]
请求帮助，不知什么问题导致我现在状态很奇妙，没有绑定设备，又不能恢复高级，又不能激活，重装都不行。

我以前装过同步到 dropbox 配置，后来卸载了，这次又装，买了高级，上来就用远程配置覆盖掉本地了，结果就出事了，搞了好久。我 90%确定这是 bug 了。老用户不能使用以前的配置？我也不在乎了，重新开始吧，看下啥问题，谢谢！来人了，贴 UID

**Comment by Kenshin** [comment]
你又发了一遍... 那之前的我删除吧。

***

你既然到找到这个 Issues 了，为什么没有注意到解决方案呢？😂 这个问题可以解决的，并且也不算 Bug

先说解决方案，看这里 https://wj.qq.com/s2/7131520/9679/ 仔细读，肯定会解决你的问题。

再说配置文件的问题，配置文件当然可以使用老版本的，它会自动升级到最新版本。你的配置文件是什么版本的？你用原来的版本的配置文件覆盖到本地？是强制覆盖吗？如果想解决配置文件的问题，最好说下细节。

**Comment by songmeixu** [comment]
强制覆盖  老=》新 ， 很老

**Comment by songmeixu** [comment]
试过了，没用

**Comment by songmeixu** [comment]
UID: igr8oaz8

**Comment by Kenshin** [comment]
> 试过了，没用

试过哪个方式了？

> 又不能恢复高级，又不能激活

提示什么？

**Comment by songmeixu** [comment]
![image](https://user-images.githubusercontent.com/705582/92379188-a14f9a80-f139-11ea-9566-d43893548445.png)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by songmeixu** [comment]
设备已全部解锁

**Comment by songmeixu** [comment]
就是我现在跟个新用户没区别，你拿啥认识我，UID上来确定了我改不了，我刚买配置文件就同步覆盖了，

**Comment by songmeixu** [comment]
不能退出都，你文档写退出，我都蒙了

**Comment by Kenshin** [comment]
你给我发邮件了，看邮件的回复。

**Comment by Kenshin** [comment]
搞定了告诉我下。

**Comment by songmeixu** [comment]
刚搞定，我的版本被自动转换成功了，👌

**Comment by Kenshin** [comment]
所以说，别着急，你跟开发者直接沟通，有什么解决不了的呢？😅
