### ISSUE TITLE
阅读模式的控制栏消失太快

### ISSUE THREAD

**Issue by airycanon** [Kenshin/simpread#109]
操作系统：Ubuntu 17.04
浏览器： Chromium 60.0.3112.113

鼠标从控制栏的二级菜单向一级菜单移动的过程中，菜单就已经消失了，感觉可以稍微加个延时。
我不会录制屏幕，不知道有没有把问题描述清楚。

**Comment by Kenshin** [comment]
感谢反馈～
不用录屏，之前有用户也反映过这个问题…
因人而异，其实我觉得还好。

未来会加入悬停关闭的功能，关联问题 https://github.com/Kenshin/simpread/issues/70

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经彻底解决了这个问题，此 issues 将关闭。
同时，1.1.1 新增加了 FAP，细节可以通过升级时看到或者 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
