### ISSUE TITLE
能否考虑增加一个选中文字并发送到简悦稍后读的功能

### ISSUE THREAD

**Issue by warmscar** [Kenshin/simpread#1091]
如题，希望大佬可以考虑增加类似这样的功能：选中文字后，鼠标右键/点击简悦图标/快捷键 可以直接将选中的文字添加到简悦稍后读里面。🍺

**Comment by Kenshin** [comment]
谢谢建议

目前通过浮动工具栏做有什么问题吗？你说的这个方式在操作路径上更长一些。

**Comment by warmscar** [comment]
在浏览知乎问题下的回答的时候，阅读模式一直有些问题，所以每次我都是用聚焦模式浏览单个回答。但是聚焦模式没法做标注，所以想到了这个。如果可以在任意网页选中文字发送到简悦稍后读的话可能会方便些。

**Comment by Kenshin** [comment]
知乎的问题，你看能否用 https://github.com/Kenshin/simpread/issues/1080#issuecomment-687729008 的方式解决，我不清楚你是否更新过适配列表，但知乎的答案一般都不会被包含。

其次，我会考虑你的需求，谢谢。

也就说，你希望在不进入阅读模式的前提下也能标注？

**Comment by warmscar** [comment]
对的，就是在不进入阅读模式也可以选中文字直接发送到简悦稍后读。😁

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
