### ISSUE TITLE
"代码段增强"插件不起作用

### ISSUE THREAD

**Issue by kawnnor** [Kenshin/simpread#1095]
浏览器：Microsoft Edge (版本 85.0.564.44)
简悦：2.0.0 （Microsoft 商店安装）
网站：blog.csdn.net
测试地址：https://blog.csdn.net/it18911008884/article/details/78520046

不安装或禁用“代码段增强”插件时，效果如下：
![批注 2020-09-08 161611](https://user-images.githubusercontent.com/15528208/92452403-9572df80-f1f0-11ea-9c52-ec490d787c63.png)

安装了“代码段增强”之后，效果变差了：
![批注 2020-09-08 161651](https://user-images.githubusercontent.com/15528208/92452542-c4895100-f1f0-11ea-9c7c-34e20c863e21.png)

**Comment by Kenshin** [comment]
谢谢反馈

代码高亮插件目前有些问题，导致出现了你截图中的问题，当然并不是每个页面都存在此问题，我先记下来。

由于 **近期反馈这个问题的比较多，为了方便的管理，所以我先关闭此 Issues** 并集中到 #500 里面，修复你的问题后，我会在这里通知你。
