### ISSUE TITLE
知乎全站gif图片解析新方案

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1099]
此issue用于记录适配知乎站点时发现的问题及解决思路

## 概要

示例页面 https://www.zhihu.com/question/27588491/answer/499773760

在看到有关知乎的issue #427 时，发现之前为知乎专栏适配的gif规则时，没有处理问答系统的gif规则，因此使用同样规则适配，但是发现直接套用过去有问题。

- 阅读模式下 GIF小标志 不消失（同样的规则，专栏中不显示，问答中显示。**可能是问答使用了论坛模式缘故？**）

![image](https://user-images.githubusercontent.com/5285894/92486604-e0a3e700-f21e-11ea-93b1-5da30a1c915a.png)

- 且导出为md文件后，会出现图片重复的问题（当前知乎所有解析规则都会出现此问题）

![image](https://user-images.githubusercontent.com/5285894/92487187-88211980-f21f-11ea-8365-3a21238228b6.png)

然后发现另一种思路来更轻易的进行匹配，且应该可全站通用（只要他们用的vue框架一致）。

## 新思路

这是上述页面进入阅读模式后，图片图标的元素

![image](https://user-images.githubusercontent.com/5285894/92487728-39c04a80-f220-11ea-8810-adcf64e99b93.png)

网页中年只显示 `<img>` 标签中的图片，但导出的markdown中却有两个img，那多出的一个从哪来的？答案是从上边的 `noscript` 中提取的。

```html
<figure data-size="normal">
  <noscript>
    <img 
    src="https://pic1.zhimg.com/50/v2-24142c274a200ca02148e605cbcce592_hd.gif?source=1940ef5c" 
    data-caption="" data-size="normal" data-rawwidth="643" data-rawheight="529" 
    data-thumbnail="https://pic2.zhimg.com/50/v2-24142c274a200ca02148e605cbcce592_hd.jpg?source=1940ef5c" width="643" 
    data-original="https://pic3.zhimg.com/v2-24142c274a200ca02148e605cbcce592_r.jpg?source=1940ef5c" />
  </noscript>
  <div>
    <div data-size="normal" data-za-detail-view-path-module="GifItem">
      <div class="sr-rd-content-center">
        <img class="" 
        src="https://pic2.zhimg.com/50/v2-24142c274a200ca02148e605cbcce592_hd.gif?source=1940ef5c">
      </div>
      </svg> //无用，省略掉
    </div>
  </div>
</figure>
```

那么我们需要将被提取到阅读模式下的元素，在 `<noscript>` 和 `<div><img>` 里只保留一个。

由于目前编写的适配规则中添加的代码只能干涉提取规则前的数据，想操作提取到阅读模式下的元素只能通过编写插件方式太过繁琐，在匹配规则中增加 `script` 功能（分为 `before` 和 `after` 两种，执行时间点不同，详情见#1069）也只是刚提出在评估阶段，因此暂时仍旧选择在高亮规则中嵌入处理代码来解决这些问题。

最后由于保留vue框架渲染出的 `img` 容器元素，在实际图片为gif时会比较麻烦，要么阅读模式出gif标志，要么移除gif标志但退出阅读模式后点击gif图片会使网页崩溃（移除gif标志 `<svg>` 会导致 img 容器残缺，vue代码出现异常），因此选择使用 `<noscript>` 的内容替代vue生成的 `img` 容器元素。

代码如下：

```js
[[{(function(){
  $('.RichContent-inner .RichText-gifPlaceholder').each(function(){
    var img = $(this).parent().find('noscript');
    $(this).empty().append(img.text()).find('img').removeAttr('data-original');
    img.remove();
  });
  return $('.RichContent-inner');
}())}]]
```

但这里发现进入阅读模式后，页面显示的是不会动的jpg图而非gif，看一下下边的元素代码

```html
// 经过上述代码处理后，原始页面上的元素
<figure data-size="normal"><div class="RichText-gifPlaceholder">
  <img 
  src="https://pic2.zhimg.com/50/v2-24142c274a200ca02148e605cbcce592_hd.gif?source=1940ef5c" 
  data-caption="" data-size="normal" data-rawwidth="643" data-rawheight="529" 
  data-thumbnail="https://pic2.zhimg.com/50/v2-24142c274a200ca02148e605cbcce592_hd.jpg?source=1940ef5c" 
  class="origin_image zh-lightbox-thumb" width="643" 
  data-original="https://pic4.zhimg.com/v2-24142c274a200ca02148e605cbcce592_r.jpg?source=1940ef5c">
</div></figure>


// 这是阅读模式中的元素
<figure data-size="normal"><div><div class="sr-rd-content-center">
  <img class="" 
  src="https://pic3.zhimg.com/v2-24142c274a200ca02148e605cbcce592_r.jpg?source=1940ef5c">
</div></div></figure>
```

可以发现，阅读模式中是将原始元素中的 `data-original` 字段，作为了 `src` 使用，而原始页面上gif图片的img元素 `data-original` 属性是其预览截图，而非gif动画文件url，其 `src` 字段才是真正的gif文件url。

为什么这样？原因在于简悦 `puplugin` 中的提取规则，在处理 `<img>` 元素时，会从以下属性提取img的url。

以下属性优先级为从低到高：

- src
- original
- data-src
- data-original
- data-original-src
- real_src
- data-lazy-src

而在处理上述的gif图片元素时，`<img>` 标签中的 `src` 存储了gif格式url，但存在另一个更高优先级的属性 `data-original`，其内存的是jpg格式的url，因优先级关系，最终选择了 `data-original` 作为阅读模式中 `<img>` 元素的 `src`。

那么，我们可以移除 `data-original` 属性，但我考虑后选择提取原始元素的 `src` 属性写到新属性 `real_src`，其优先级更高，这样既可。

代码如下：

```js
[[{(function(){
  $('.RichText-gifPlaceholder').parent().find('noscript').each(function(){
    var noscript = $(this).text();
    var img = $(this).parent().empty().append(noscript).find('img');
    var src = img.attr('src') || '';
    if(src.match(/.gif/)) img.attr('real_src',src);
  });
  return $('.RichContent-inner');
}())}]]
```

经过这样处理，在知乎问答页面，进入阅读模式后，原始页面上的gif图片容器元素会被修改，进入阅读模式后便能显示所有gif图片，导出markdown也没有问题了。
但是，目前这个实现算是入侵式的增强了，即修改了原始页面的内容。

## 思考

与之前处理 52破解论坛等Discuz论坛系统部分图片不显示的问题不同，其处理代码需要放在高亮匹配前。本次举例解决知乎页面gif图片问题的思路，其用到的 `<noscript>` 元素在阅读模式元素中存在的。
如果后续在匹配规则中增加了独立的 script(`before` / `after`)功能，上边的代码是可以放在 `after` 后执行的，不对原始页面产生影响。

**Comment by binsee** [comment]
更新匹配规则：

```js
[[{(function(){
  $('figure noscript').each(function(){
    var noscript = $(this).text();
    var img = $(this).parent().empty().append(noscript).find('img');
    var src = img.attr('src') || '';
    if(src.match(/.gif/)) img.attr('real_src',src);
  });
  return $('.RichContent-inner');
}())}]]
```

如果不处理 `<noscript>` 元素，导出的markdown必然会是图片重复的（对于），因此干脆全局使用 `<noscript>` 替代 `<img>` 了。
当适配规则实现 `before` 和 `after` 后，可放入 `after` 以解除入侵式修改。

**Comment by Kenshin** [comment]
perfect solution !

**Comment by binsee** [comment]
当前其实已经可以实现 `before` 和 `after`的效果
- 将代码放入 **高亮规则**  为 `berfore`
- 将代码放入 **隐藏列表**  为 `after`

因此，上述处理代码可以放入 **隐藏列表** ，然后限定jquery语句从 `sr-read` 元素下查询，如 `sr-read figure noscript`。
如此，便只修改了阅读模式中的元素，不会修改到原始页面，即非入侵式修改。

**Comment by Kenshin** [comment]
哈哈，你这属于 Hack 方式，虽然也没啥问题。

BTW，微信读书就是通过类似这种方式支持的。（只是我没有对外发布这个适配站点，避嫌。

**Comment by binsee** [comment]
适配已合并，更新官方主适配源或更新简悦插件至2.1.0版本后，即可在阅读模式中正确显示。

**Comment by binsee** [comment]
知乎页面保存到github后，在github上，部分图片会无法显示，调查后发现是知乎使用的oss问题

见： #2387

**Comment by Kenshin** [comment]
@binsee 

我重新适配了知乎专栏与问答页的内容，算是彻底解决了这个问题，细节可以看下 https://github.com/Kenshin/simpread/discussions/2869
