### ISSUE TITLE
求匹配github的Readme

### ISSUE THREAD

**Issue by shengxinjing** [Kenshin/simpread#11]
非常棒的阅读体验，求匹配github的README

**Comment by Kenshin** [comment]
目前只能匹配有规则的 URL，以及适度的 URL 模糊查询，暂时还没能匹配特别复杂规则的 url，我试试在不更新源码的情况下，是否能成功适配。

**Comment by ksky521** [comment]
已经在pr #16 解决

**Comment by Kenshin** [comment]
下个版本就会包含此更新，感谢建议以及 pr 👍

**Comment by Kenshin** [comment]
![Imgur](http://i.imgur.com/X2qrJA7.png)

`READM.md` 感谢 @ksky521 的加持！

**Comment by ksky521** [comment]
😄 ~

**Comment by shengxinjing** [comment]
赞 感谢三水清大神@ksky521

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`
新增加了 对 `issues` 与 `REAME.md` 的适配。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
