### ISSUE TITLE
某些适配页面无法正常显示

### ISSUE THREAD

**Issue by Dev-Wiki** [Kenshin/simpread#110]
网址: http://bj.people.com.cn/n2/2017/0922/c82840-30762508.html

附图: 
![image](https://user-images.githubusercontent.com/12946956/30724180-e316fe4c-9f6e-11e7-992f-c70d65a3e849.png)

**Comment by Kenshin** [comment]
感谢反馈~  😁 

这个页面的结构与适配页面的结构不一致，但 url 近似而造成的，下个版本会修复这个模糊的提示。

关联问题及修改方案请看 https://github.com/Kenshin/simpread/issues/107 https://github.com/Kenshin/simpread/issues/90

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> 匹配失败后，自动退出阅读模式，并启动临时阅读模式，可继续生成阅读模式的页面。

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update
