### ISSUE TITLE
【无法使用阅读模式】（已购买高级账户）

### ISSUE THREAD

**Issue by pinvshi** [Kenshin/simpread#1102]
无法使用阅读模式
邮件手动选择也不行
添加到白名单也不行
请反馈邮箱怎么办。谢谢。

**Comment by Kenshin** [comment]
估计是你的黑名单多了一些 **多余的回车或为空** 造成的，细节看 https://github.com/Kenshin/simpread/issues/1075
除此以外，也要避免 **延迟加载列表** 与 黑名单一样的问题。

这个 Bug 已经 Fixed 了，下个版本一起发布。

**Comment by pinvshi** [comment]
好的。谢谢。
等下个版本吧，我还是不大弄得好。
还是不行。

**Comment by Kenshin** [comment]
打开 选项页 → 共通，按照下图所示：

![image](https://user-images.githubusercontent.com/81074/92589434-215a3980-f2cd-11ea-8545-9ce2d61ead9a.png)


重置你的配置文件，然后再试试。

**Comment by pinvshi** [comment]
哇！阔以啦！
谢谢大佬
简悦牛B

**Comment by pinvshi** [comment]
但我觉得还是不太灵敏我的浏览器(chrome)
老是要按很多次AA AS 才会出来

**Comment by Kenshin** [comment]
在隐身模式下，仅启用简悦试试，看看是不是其它扩展干扰的？

**Comment by pinvshi** [comment]
好的，谢谢。
我一个一个扩展试干扰源。

**Comment by pinvshi** [comment]
不好意思，又有一个问题了
我重新粘贴密钥登陆高级账户
粘贴后显示“一个账户仅能绑定一个密钥”

**Comment by Kenshin** [comment]
将刚才说的导出的配置文件导入，然后再重新授权。

你可以看这个文档 http://ksria.com/simpread/docs/#/已购必读?id=快速掌握

**Comment by pinvshi** [comment]
OK了，THX棒棒哒~

**Comment by Kenshin** [comment]
搞定就好。
