### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by Superbishop** [Kenshin/simpread#1103]
发生问题的地址: <https://zhuanlan.zhihu.com/p/225120404>

**Comment by Kenshin** [comment]
谢谢反馈

我看了下，这个页面最终会以 Markdown 的形式导入到印象笔记中，导入到印象笔记的结构受印象笔记制约的很厉害，所以经常会出现失败的情况。

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
