### ISSUE TITLE
towardsdatascience.com 无法load大图

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#1104]
https://towardsdatascience.com/negative-binomial-regression-f99031bb25b4

只会显示小图，大图load不出来
![image](https://user-images.githubusercontent.com/3938751/92675878-07fbd080-f353-11ea-8d47-41456a40cb11.png)

**Comment by Kenshin** [comment]
这个站因为没有适配出现了无法自动识别的问题，而且一般来说， 英文类的页面大多都有 惰性加载 的功能，一般来说处理这些图片均存在一定程度的问题。

我先记新站吧。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

新增加了专门针对 [惰性加载图片的解析方案](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e6%83%b0%e6%80%a7%e5%9b%be%e7%89%87%e5%8a%a0%e8%bd%bd)，如下图

![image](https://user-images.githubusercontent.com/81074/121986734-a7119500-cdc9-11eb-94a2-973e1b1e28a6.png)

注意：使用此功能时会出现维基百科的一些问题，解决方案 [请看这里](https://github.com/Kenshin/simpread/discussions/2347)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
