### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by mi-hood** [Kenshin/simpread#1106]
发生问题的地址: <https://note.youdao.com/ynoteshare1/index.html?id=787e2aaa77ec72ee00a1569d94100d23

**Comment by Kenshin** [comment]
谢谢反馈。

首先，这个页面是有道笔记的，基本上相当于整理过的，也就不需要阅读模式了？难道要「俄罗斯套娃」？ 😅 
其次，从技术角度来说，简悦针对具有 iframe 形式的页面一般不做处理，这样会有性能问题。

所以，我关闭这个 Issues 了。 😄
