### ISSUE TITLE
多个 h1 只显示第一个，后面的都没有显示

### ISSUE THREAD

**Issue by zronghui** [Kenshin/simpread#1110]
遇到好几个页面，解析后缺失标题，看的人云里雾里
多个 h1 只显示了第一个，后面的却都没有显示
如 https://www.jianshu.com/p/5027e9d54df7
拜托解决下

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

没问题的话，请关闭这个 Issues

**Comment by zronghui** [comment]
好了，多谢
