### ISSUE TITLE
ios悬浮插件自定义6个按键功能后应该如何重新自定义按键功能呢？

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1112]
没找到选项
![image](https://user-images.githubusercontent.com/15308878/92873710-e7f30c80-f439-11ea-8510-661e7c702a5e.png)

**Comment by Kenshin** [comment]
嗨，我在 #891  做了补充说明，看下图

![image](https://user-images.githubusercontent.com/81074/92880099-402d0d00-f440-11ea-8498-ce298478b1aa.png)

没问题的话，我关闭这个 Issues 了。
