### ISSUE TITLE
疑问：标注模式下不能文本复制操作

### ISSUE THREAD

**Issue by yanjunqi** [Kenshin/simpread#1114]
不知道是不是功能特性，为什么标注模式下不能文本复制操作？
使用插件可以进行划词翻译说明可以获取文本，但划词搜索插件又不能用

**Comment by Kenshin** [comment]
标注时会监控你的鼠标操作，所以会出现这个情况，请先关闭标注模式。

右下角 → 标注 icon 点击即可关闭。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
