### ISSUE TITLE
特殊结构的 HTML 会引起标注后无法高亮的问题

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1116]
https://www.sohu.com/a/66237075_105404
![image](https://user-images.githubusercontent.com/15308878/92916329-fc4a0000-f45f-11ea-8a7d-1a703e0f822f.png)
![image](https://user-images.githubusercontent.com/15308878/92916353-023fe100-f460-11ea-9f0a-e74ad152d38b.png)

**Comment by Kenshin** [comment]
谢谢反馈，明天确认下。

**Comment by Kenshin** [comment]
问题已经找到，与u https://github.com/Kenshin/simpread/issues/1076 一样的问题，都是结构有问题的 HTML 导致的。

我先记 Bug ，修复后会通知你。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
