### ISSUE TITLE
印象笔记导入失败,坚果云导入失败，我就用这两个。

### ISSUE THREAD

**Issue by wingkinger** [Kenshin/simpread#1118]
发生问题的地址: <https://www.bilibili.com/read/cv7563816>
印象笔记，坚果云导入失败

**Comment by Kenshin** [comment]
谢谢反馈，明天确认下。

你能用简悦的同步功能吗？

**Comment by wingkinger** [comment]
你好，感谢你的回复，刚刚重新试了下，功能又一切正常了，同步功能可以用，导入功能也正常了。
出现故障当时忘记截图了，很抱歉无法给你详细的复现步骤。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 晚上8:37
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"wukun"<1812694753@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 印象笔记导入失败,坚果云导入失败，我就用这两个。 (#1118)





 
谢谢反馈，明天确认下。
 
你能用简悦的同步功能吗？

**Comment by Kenshin** [comment]
没事的。

导入到印象笔记存在一定几率的失败，导入到坚果云一般都没发生过错误。

是不同的网页吗？还是同一个？

如果没有问题的话，可以关闭这个 Issues 了。
