### ISSUE TITLE
新站适配：https://www.poemlife.com/

### ISSUE THREAD

**Issue by M1nTT** [Kenshin/simpread#1119]
https://www.poemlife.com/

目前状况：二级页面可以手动进入阅读模式，但无法自动进入。（已将主域名添加进白名单，但二级界面和主界面都无法自动进入阅读模式；每个二级界面域名都不同，无法添加进白名单）

需求： 主界面不需要阅读模式，二级界面自动进入阅读模式，请教一下，该如何操作？看不懂minimatch.

感谢开发者的阅读。

**Comment by Kenshin** [comment]
嗨，谢谢反馈以及自己动手研究。

你可以看下面的代码

域名
```
[[/https:\/\/www.poemlife.com\/index.php\?mod=newshow&id=\d+/]]
```

标题
```
[[{$('body title').text()}]]
```

余下的内容可以自动生成，细节看下图

![image](https://user-images.githubusercontent.com/81074/92985193-f6e1c980-f4e2-11ea-84aa-31a1b47958b4.png)


设置完这些后就可以自动进入阅读模式了。

**Comment by M1nTT** [comment]
Hi, 感谢您的回复

1.当我在“站点管理”里试图点击“保存当前站”时提示：“高亮区域”为必填项。但图中的“高亮区域”代码没有显示完整，我无法输入，能否烦请开发者提供一下完整代码。

2.虽然“描述”提示默认为空，不是必填项，但在图中我看到了“描述“中填了代码，我是否需要手动填写？如果需要的话，能否再次烦请开发者提供完整代码。

3.当我点击“登录到服务器”时显示：获取后台服务失败。 当我填完图中所需的代码时，是否直接点击“保存当前站”就可以了？

感谢您的阅读
祝好！

**Comment by M1nTT** [comment]
Hi,开发者您好！

根据您的提示，我已经成功实现了自动开启阅读模式，但也遇到了一些小问题。

此网站（poemlife.com)的二级界面好像有不同的原始域名，所以此网站只有部分分区才能实现自动打开阅读模式。根据您给的案例，我认为只需要将其他分区的原始域名转换成正则表达网址，然后添加进白名单即可。

但很可惜，我没有相关基础，无法将原始域名后面的部分“82437&str=1339”转化为正则表达网址。

能否烦请开发者予以解答？

如下：
----->

案例：
https://www.poemlife.com/index.php?mod=newshow&id=                11549
[[/https:\/\/www.poemlife.com\/index.php\?mod=newshow&id=        \d+/]]

待解答题目：
https://www.poemlife.com/index.php?mod=showart&id=                  82437&str=1339
[[/https:\/\/www.poemlife.com\/index.php\?mod=showart&id=         ???

---->

感谢您的阅读
祝好！

**Comment by M1nTT** [comment]
![1](https://user-images.githubusercontent.com/33660603/92988940-d9bcf300-f502-11ea-9b2f-8f882f34318f.jpg)

**Comment by M1nTT** [comment]
![2](https://user-images.githubusercontent.com/33660603/92988964-0cff8200-f503-11ea-95ba-ef1c0543ae50.jpg)

**Comment by Kenshin** [comment]
例如这个地址
```
https://www.poemlife.com/index.php?mod=showart&id=82438&str=1896
```

把其中的数字改为 `\d+` 即可，即如下：
```
[[/https:\/\/www.poemlife.com\/index.php\?mod=showart&id=\d+&str=\d+/]]
```
相当于你是两个适配站点，注意标识不要重复就好了。

**Comment by M1nTT** [comment]
已成功，感谢！

**Comment by Kenshin** [comment]
搞定的话，我关闭这个 Issues 了。 😀
