### ISSUE TITLE
希望帮忙适配中国大数据这个网站

### ISSUE THREAD

**Issue by flypigcg** [Kenshin/simpread#112]
中国大数据（http://www.thebigdata.cn/ ） 这个网站内容还不错，更新频率也很高，但是这个网站的排版，字体样式等等确实是太痛苦了。。希望帮忙适配啊~~

**Comment by Kenshin** [comment]
哈，刚看了下，的确如你所说，排版想上个世纪的产物...  😂 
适配完，会通知你。
不过，或许需要稍等几天，因为刚刚更新了一批新站，准备在凑一堆一起更新。

**Comment by flypigcg** [comment]
非常感谢！等待适配的那一天:smile:

**Comment by Kenshin** [comment]
已适配~   
请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。

**Comment by flypigcg** [comment]
十分感谢，效果很赞！
