### ISSUE TITLE
标注完成段的无序列表以后导入印象笔记会缺失回车，黏在一起

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1123]
![image](https://user-images.githubusercontent.com/15308878/92986682-4a5a1480-f4ef-11ea-8b15-57ad8b2a6161.png)

![image](https://user-images.githubusercontent.com/15308878/92986694-5b0a8a80-f4ef-11ea-9ffa-8b97a050f353.png)
顺便希望能支持导入指定默认的印象笔记笔记本里

**Comment by Kenshin** [comment]
谢谢反馈。

导入到印象笔记偶尔是会出现问题，请告诉具体 URL 这样方便排查。

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
