### ISSUE TITLE
新站适配：扇贝阅读

### ISSUE THREAD

**Issue by Alpha-pink** [Kenshin/simpread#1127]
发生问题的地址: <https://www.shanbay.com/news/articles/lptqc>

**Comment by Kenshin** [comment]
谢谢反馈，我先记录新站。

**Comment by Kenshin** [comment]
嗨，此站已经适配，请更新适配列表

![image](https://user-images.githubusercontent.com/81074/130352745-f125619f-2226-4e31-8b7e-cd41b11c347c.png)

### 进阶使用

另外，也可以使用 [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 获得更好的使用方案，如下图：

![iShot2021-08-22 18 57 05](https://user-images.githubusercontent.com/81074/130352775-4ade5777-09bd-453c-bd54-96f80ade844f.png)

### 备注

使用翻译后的结果（双语）支持导出 HTML / Markdown 等格式。
