### ISSUE TITLE
[疑似BUG]从聚焦模式退出后网页显示不正常

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#113]
备注： 如果只是这一个网站的话，请忽略。

地址： https://www.tensorflow.org/programmers_guide/datasets#basic_mechanics
复现：

1. 进入网页
2. 进入聚焦模式
3. 向下继续阅读一段
4. 点击旁边非聚焦区域，退出聚焦模式
5. 回页首，会发现标题向下错位了很大一截

**Comment by Kenshin** [comment]
感谢反馈   👍 
我明天会看下，现在在手机上。

**Comment by Kenshin** [comment]
不知道什么缘故，页面一直打不开（已加梯子），但手机端却能打开...  😰

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
