### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by bambooslip** [Kenshin/simpread#1132]
发生问题的地址: <http://bokekuaiping.blogchina.com/989749387.html>

**Comment by Kenshin** [comment]
谢谢反馈，导入到印象笔记确实有些问题，细节 [请看这里](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1-FAQ?id=%e5%8d%b0%e8%b1%a1%e7%ac%94%e8%ae%b0%e4%bf%9d%e5%ad%98%e5%a4%b1%e8%b4%a5)

**Comment by Liampor** [comment]
我也是 CSDN 的博文到印象笔记 不是失败，或者效果很差。

**Comment by Kenshin** [comment]
@Liampor 

道理是一样的，我也没什么好办法。简单的说，虽然印象笔记有 API 但是市面上没有一款剪藏能比得过它，原因是它的导入方式太过奇葩，因此失败率极高。

它自己的 API 或许可以绕过这些限制...

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/1150

**Comment by Liampor** [comment]
> @Liampor
> 
> 道理是一样的，我也没什么好办法。简单的说，虽然印象笔记有 API 但是市面上没有一款剪藏能比得过它，原因是它的导入方式太过奇葩，因此失败率极高。
> 
> 它自己的 API 或许可以绕过这些限制...

那换个思路，能否在简阅的阅读界面使用他自己的剪藏插件进行收集呢，如果直接进入阅读页面，我发现这个印象的插件点击没反应。然后使用简阅的服务器生成临时网页，可以使用剪藏，但是剪藏下来的效果也很差，主要表现就是字体异常大。。

**Comment by Kenshin** [comment]
@Liampor 

不能… 否则早就这么做了。

我在尝试用其它方式解决，不过暂时无法发布这个版本，请等待。

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
