### ISSUE TITLE
消息中心日期最新排序

### ISSUE THREAD

**Issue by zronghui** [Kenshin/simpread#1134]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

1. 阅读模式下，用 上下 按键读文章，页面会卡顿。不知道是不是每个站点都是这样，至少掘金是的
2.正常逻辑，应该是后面的那个箭头有链接；然而点击前面看起来普通格式的文字才能跳转，用着很不顺手
![image](https://user-images.githubusercontent.com/15062201/93204364-8fe53e80-f788-11ea-8984-7ba200af7998.png)
3. 简阅的消息列表，emmm，希望新的通知放到上面
![image](https://user-images.githubusercontent.com/15062201/93204567-e5b9e680-f788-11ea-9af1-7a03b84315e0.png)

1 算是 bug 吧
2 3 算是建议，就放一起了

**Comment by zronghui** [comment]
Mac Chrome  85.0.4183.102（正式版本） （64 位）

**Comment by zronghui** [comment]
对 2 的补充:
![image](https://user-images.githubusercontent.com/15062201/93206447-ffa8f880-f78b-11ea-89e0-923d2b0c34b1.png)
像这个整个矩形带个链接就很舒服

**Comment by Kenshin** [comment]
谢谢建议。

问题1 之前有个用户也提过，八成算是 Bug

问题2 我也发现了，已经修复，下个版本修复。

问题3 确如你说，下个版本修复。

**Comment by Kenshin** [comment]
嗨，请不要关闭这个 Issues 发布后我在关闭。

**Comment by zronghui** [comment]
好吧，抱歉

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了倒排序以及未读信息有错误的问题。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
