### ISSUE TITLE
Bug：保存文章到语雀，里面的代码中的注释会多转义符

### ISSUE THREAD

**Issue by ZuulAndRibbon** [Kenshin/simpread#1135]
![image](https://user-images.githubusercontent.com/21259910/93213039-f1f87080-f795-11ea-965e-8bd3f900ad5e.png)

**Comment by Kenshin** [comment]
谢谢反馈，这是个 Bug 已经被修复，但只能下个版本发布了，细节请看 https://github.com/Kenshin/simpread/issues/1064#issuecomment-687973442
