### ISSUE TITLE
邮箱未收到兑换码，手机收到了激活码，但是激活码在无法绑定升级到简悦高级账户

### ISSUE THREAD

**Issue by one-white-cold** [Kenshin/simpread#1144]

**Comment by Kenshin** [comment]
请发邮件到 kenshin####ksria.com 附上购买凭证与 License (不要以图片形式给我 License )
并说明 **激活码在无法绑定升级到简悦高级账户** 你是如何操作的？

**Comment by one-white-cold** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我已回复到         kenshin@ksria.com 
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                dragontigerking
                            
                    
                        
                            
                                    dragontigerking@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年9月17日 12:58，Kenshin Wang<notifications@github.com> 写道： 




请发邮件到 kenshin####ksria.com 附上购买凭证与 License (不要以图片形式给我 License )

并说明 激活码在无法绑定升级到简悦高级账户 你是如何操作的？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
