### ISSUE TITLE
导出至onenote时无法选择分区页面

### ISSUE THREAD

**Issue by m-y-name** [Kenshin/simpread#1146]

**Comment by Kenshin** [comment]
谢谢反馈，目前是这样的，未来会考虑更细节的定制化。

**Comment by 0071248** [comment]
为什么**从稍后读导出**到OneNote等笔记,  在笔记里只显示标注的条目内容呀?
还是说我设置的不对?

**Comment by Kenshin** [comment]
@0071248 

是你操作造成的，详细请看 http://ksria.com/simpread/docs/#/标注?id=导出标注 以及以后的内容。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
