### ISSUE TITLE
阅读模式查看 React 文档代码块中高亮部分消失

### ISSUE THREAD

**Issue by JimSunJing** [Kenshin/simpread#1147]
在[React文档页面](https://reactjs.org/docs/hooks-state.html)使用简悦时发现有部分高亮区域代码没有被解析到。
![原网页](https://user-images.githubusercontent.com/37240483/93556686-e5e5fc00-f9ab-11ea-8da7-b1a9a25c8f1c.png)
![阅读模式](https://user-images.githubusercontent.com/37240483/93556761-129a1380-f9ac-11ea-9d5f-ab111ef524ec.png)
简悦版本2.0.0

**Comment by Kenshin** [comment]
谢谢反馈，这是 代码高亮插件 的问题，我会统一整理到 #500 

相同问题尽量开一个 Issues 所以，我先关闭此 Issues 了，修复后会通知你。
