### ISSUE TITLE
怎么激活高级版

### ISSUE THREAD

**Issue by wwwwxxxg** [Kenshin/simpread#1151]

**Comment by Kenshin** [comment]
激活码用了吗？
用了就重新授权！
没用就绑定！

**Comment by wwwwxxxg** [comment]
用了，重新授权不了，说我不是高级用户，之前我没有用Dropbox账户同步过






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 晚上8:41
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "韦熊刚"<1329889549@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 怎么激活高级版 (#1151)





 
激活码用了吗？
 用了就重新授权！
 没用就绑定！

**Comment by Kenshin** [comment]
首次授权会提示注意保留配置文件（UID）
如果丢失 UID 的话，先取回正确的 UID
这里有 https://simpread.pro/help 相关说明

**Comment by wwwwxxxg** [comment]
已经有 uid了还是不行






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 晚上8:48
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "韦熊刚"<1329889549@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 怎么激活高级版 (#1151)





 
首次授权会提示注意保留配置文件（UID）
 如果丢失 UID 的话，先取回正确的 UID
 这里有 https://simpread.pro/help 相关说明

**Comment by Kenshin** [comment]
首先确定你的 UID 是绑定时的，而不能随便什么UID 都可以；其次重新授权后提示什么？（截图给我）

另外看看这里的选项是不是下图所示

![](https://user-images.githubusercontent.com/81074/90757097-c0fc5b80-e30f-11ea-9c02-4f79634a2bf7.png)

**Comment by wwwwxxxg** [comment]
这是我的 激活码5uph-icsom9-kj6or0-qckh
UID	im1w5ope-zyxb-0tya-8nfu-dwc1l3hztjkt






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 晚上9:13
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "韦熊刚"<1329889549@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 怎么激活高级版 (#1151)





 
首先确定你的 UID 是绑定时的，而不能随便什么UID 都可以；其次重新授权后提示什么？（截图给我）
 
另外看看这里的选项是不是下图所示

**Comment by Kenshin** [comment]
UID是私密信息…

我看了你的 UID 是正确的，重新授权提示什么？截图给我

另外，重新授权的方式看这里
