### ISSUE TITLE
简·悦能否支持导出至ulysses？

### ISSUE THREAD

**Issue by PayneSnow** [Kenshin/simpread#1155]
您好，和bear一样，ulysses是众多写作者常用的写作软件。希望您能够增加ulysses扩展，使得一键可以保存ulysses，类似于 Web Clipper这个插件一样 [https://chrome.google.com/webstore/detail/web-clipper/mhfbofiokmppgdliakminbgdgcmbhbac](url)。
![截屏2020-09-20 07 58 21](https://user-images.githubusercontent.com/51922806/93691462-1054c800-fb18-11ea-891a-e91b76af2ae5.png)

**Comment by Kenshin** [comment]
有的，进入 **阅读模式 → （右下角）触发器 → 动作** 栏，看下图

![image](https://user-images.githubusercontent.com/81074/93694137-dba63800-fb3a-11ea-9a08-ac1dc4e36bec.png)
