### ISSUE TITLE
bug：已经购买高级账户，但是显示合辑功能依然无法使用

### ISSUE THREAD

**Issue by PayneSnow** [Kenshin/simpread#1156]
已经购买高级账户，但是显示合辑功能依然无法使用。
如图。求反馈
![截屏2020-09-20 07 59 27](https://user-images.githubusercontent.com/51922806/93691518-d9cb7d00-fb18-11ea-91ca-df62aded537b.png)
![截屏2020-09-20 07 59 49](https://user-images.githubusercontent.com/51922806/93691519-dc2dd700-fb18-11ea-9f2e-40000f704da0.png)

**Comment by PayneSnow** [comment]
其他高级会员功能也是无法正常使用的，尽管显示已经是高级会员。
如图
![截屏2020-09-20 08 12 31](https://user-images.githubusercontent.com/51922806/93691543-3b8be700-fb19-11ea-95ba-ebebe75bcf63.png)

**Comment by Kenshin** [comment]
并不是 Bug 首次绑定后会有重启服务器的提示。

重启后再重新授权就可以了，建议看看 https://simpread.pro/help 以及 Issue 在提示问题置顶的内容 https://github.com/Kenshin/simpread/issues/908
