### ISSUE TITLE
简悦在 Edge 无法使用的问题

### ISSUE THREAD

**Issue by aQ-qwl** [Kenshin/simpread#1158]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows **

- 浏览器版本 **e.g. edge85.0.564.51**

- 简悦版本 **2.0.0**

- 发生问题的地址 <几乎在所有已经适配的网站上>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 
![image](https://user-images.githubusercontent.com/67667585/93692102-6d08b080-fb21-11ea-8591-8ad06268b220.png)

**Comment by Kenshin** [comment]
很奇怪的问题...

我目前的 Edge 是 87 没有遇到你的问题，重新安装后选项页也是白屏吗？

**Comment by Kenshin** [comment]
我分别从 Edge 与 Chrome （全新）安装了 **Edge 85.0.564.60** 也没有发现你说的情况。

**Comment by aQ-qwl** [comment]
以前使用的老版本可以实现插件功能，但是现在就是会点击简悦出现的图标进入阅读模式会白屏，有时候在百度百科尝试好几次能够进入阅读模式界面，但是不能进行其他的标注，高亮或者其他操作，会是因为程序有问题？

**Comment by Kenshin** [comment]
> 以前使用的老版本可以实现插件功能，但是现在就是会点击简悦出现的图标进入阅读模式会白屏，有时候在百度百科尝试好几次能够进入阅读模式界面，但是不能进行其他的标注，高亮或者其他操作，会是因为程序有问题？

你还是没有回复我的问题...

首先，**白屏** 是发生在选项页？还是任意页面？
其次，看你描述，即便重装也不好使？
最后，Edge 与 Chrome 使用了一样的程序，以及它们都是  Chromium 的浏览器，理论上不应该存在你说的问题。

***

我在 Mac 安装了四个 Edge 均未出现你说的情况。

![image](https://user-images.githubusercontent.com/81074/93694669-2cb92a80-fb41-11ea-94b9-0d2a1e45f84c.png)

**Comment by aQ-qwl** [comment]
选项页没有问题，就是打开类似知乎的网址，简悦不是会变红显示可以适配进入阅读模式么，我就点击进入阅读模式，但是就会变成白屏。如果你的没有问题，会不会是我的浏览器出现了问题。我重装的是插件，还没有试过重装浏览器。刚开始用简悦还是可以的，后来过一段时间再用就变成了能进入阅读模式但是不能进行额外的比如将网页下载为PDF等的操作。后来更新到2. 0就成了白屏。有可能是我的浏览器哪里出了问题。我有时间重装试试，麻烦您了

**Comment by Kenshin** [comment]
okay

首先排除是否是其它扩展干扰造成的，

1. 你可以在 **隐身模式下，仅启用简悦** 试试看。
2. （如果上步有问题的话），导出你的配置文件。
3. 重置或重新安装简悦（如果你曾经做过就不用这步了）
4. 看看能否试试其它浏览器，安装简悦 2.0 然后导入（步骤2）的配置文件，看看是否也存在这个问题？

**Comment by aQ-qwl** [comment]
好的，我现在不方便测试，到时候找到问题再告诉您。谢谢，麻烦您了

**Comment by aQ-qwl** [comment]
![image](https://user-images.githubusercontent.com/67667585/93705032-72c7bb80-fb4c-11ea-8dcc-e09fd89c8d4e.png)
我找到问题了，是因为和这个插件有冲突，同时开启这两个插件就会出现白屏。谢谢作者耐心解答，问题已经解决了

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
