### ISSUE TITLE
[特定网站] 某些黑底白字网站使用聚焦模式后显示不正常

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#116]
仍旧没有做大规模测试，如果是单独这个网站的话，请忽略。

地址： https://kwotsin.github.io/tech/2017/01/29/tfrecords.html
复现：
1. 进入网址
1. 进入聚焦模式

现象：
1. 弹出白底白字的聚焦框，几乎无法阅读

**Comment by Kenshin** [comment]
okay，感谢反馈。
刚刚测试了下，已经复现，但应该仅仅只是这个网站的问题。
最近在做 1.0.4，主要是聚焦模式的一些改进，所以测试了大量的网站，均未发生这个问题。

先记 Bug ~

**Comment by Kenshin** [comment]
没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
