### ISSUE TITLE
在不小心鼠标选择到到特别多内容的时候，网页会假死

### ISSUE THREAD

**Issue by Crayon-ShinChan** [Kenshin/simpread#1161]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本 Chrome

- 简悦版本 最新版

- 发生问题的地址 https://www.nature.com/news/sugar-tax-could-sweeten-a-market-failure-1.19646

在不小心鼠标选择到到特别多内容的时候，网页会卡死

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈，确实存在这个问题。
虽然不属于正常使用，我看看能否规避这种情况。

**Comment by Crayon-ShinChan** [comment]
> 谢谢反馈，确实存在这个问题。
> 虽然不属于正常使用，我看看能否规避这种情况。

有时候鼠标不小心划太右边，就会选中太多。我觉得你的产品挺好用的，写论文的时候可以直接给网页做标注，不用下载转换成 pdf，和 notion 搭配使用，在构思 essay 的时候非常好用！

已经购买支持了

**Comment by Kenshin** [comment]
谢谢支持。

你说的这个「误触」问题是个 Bug 我已经修复了，但是只能下个版本发布。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
