### ISSUE TITLE
如何 获取Dropbox 的access token

### ISSUE THREAD

**Issue by gita123456** [Kenshin/simpread#1163]
按步骤操作，在最后一步卡住了
“ 同任意文本编辑器打开的导出文件，搜索 dropbox 复制对应的 access_token 即可”
完全不知道这是什么意思？我是电脑小白

**Comment by Kenshin** [comment]
你是说 JSBox 版的简悦吗？
如果是的话，需要在扩展版中使用授权 Dropbox 的方式获得 Token

**Comment by gita123456** [comment]
我按照操作授权了，但不知道在哪找token

**Comment by Kenshin** [comment]
emmm 我好像知道你的问题了。

1. 确保授权 Dropbox
2. 确保勾选 [同步时是否包含授权服务中的授权码？](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1?id=%e6%8e%88%e6%9d%83%e7%a0%81) 细节看链接的提示
3. 导出配置文件
4. 用任意文本编辑器打开它，并找到 `dropbox` 对应的 `token` 即可。

**Comment by skryoung007** [comment]
求助 我是小白啊，这句话怎么操作呜呜"用任意文本编辑器打开它，并找到 dropbox 对应的 token 即可。"
找了个在线文本编辑器，把下载下来的文件复制进去，然后不知道怎么弄了，没有地方让我输入“dropbox”诶

**Comment by Kenshin** [comment]
@skryoung007 

Dropbox 暂时没法使用了，细节请看 https://github.com/Kenshin/simpread/issues/3871#issuecomment-1133599010
