### ISSUE TITLE
稍后读的同步

### ISSUE THREAD

**Issue by cpp-jiang** [Kenshin/simpread#1168]
//多设备的同步功能基本废了啊,是我的手废了
每次用稍后读之前得另外一台电脑先上传,再这台电脑同步一下,保证不丢失数据
这个问题看来只能自动同步解决

**Comment by Kenshin** [comment]
要养成每次同步的好习惯。 😄 

***

未来会考虑半自动同步方案，同时也会考虑更多方便的方式。

***

自动方案的坑很多，所以暂时不会考虑。

**Comment by Kenshin** [comment]
@cpp-jiang 

> 提交的issue被删除了???付了费表示很心痛
问题 : 稍后读没有自动同步功能很麻烦啊,其他配置还没关系

***

抱歉，你在 https://github.com/Kenshin/simpread/issues/908#issuecomment-696003610 的内容也会被删除。因为内容跟 Issuse 不符。

***

另外，并不是删除当前 Issues，而是关闭了。

**Comment by Kenshin** [comment]
还有，谢谢支持。

我已经回复你的这个问题了 https://github.com/Kenshin/simpread/issues/1168#issuecomment-695969094

**Comment by cpp-jiang** [comment]
丢人了,我之前筛选显示没有,以为被删除了

**Comment by Kenshin** [comment]
> 丢人了,我之前筛选显示没有,以为被删除了

没事。

我再重申下，我只是删除了 https://github.com/Kenshin/simpread/issues/908 关于你的内容，因为 **你的内容与 #908 的主题不符** ，并且你的提问会给其它同样在 #908 的人发 notifacation 打扰到其他人。
