### ISSUE TITLE
[BUG]某些非适配网站出现“阅读模式”（特定网址，不稳定复现）

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#117]
提示： 这个Bug不太好复现

网址： https://kwotsin.github.io/tech/2017/01/29/tfrecords.html
复现：
1. Chrome正常模式，来Github Issue，新建Issue，什么都不写
1. Chrome隐身模式，进入上述网址，右键中只有 聚焦模式
1. 反复进入、退出聚焦模式，同时做一些选中，选中并拖拽，聚焦模式里选中、选中并拖拽，切回正常模式里面打字等操作，但不要刷新
1. __有一定几率__，隐身模式里面那个页面右键里原本“聚焦模式”变成了可以展开的菜单，可以点击“阅读模式”。
1. 但是点击阅读模式后，右上角提示“站点未适配”

**Comment by Kenshin** [comment]
哈，你不进 测试组 都浪费人才了  😈  
接连发现 3个（非常规） 的 Bug  👍 

***
暂时未稳定复现，但 `1.0.4` 会改善 `点击阅读模式后，右上角提示“站点未适配”` 这个界面提示，所以即便发生了这个问题，也不会困扰用户。

关于 `点击阅读模式后，右上角提示“站点未适配”` 的描述请看关联问题 https://github.com/Kenshin/simpread/issues/90

**Comment by Kenshin** [comment]
没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
