### ISSUE TITLE
新站适配 note.youdao.com

### ISSUE THREAD

**Issue by wpc00** [Kenshin/simpread#1172]
发生问题的地址: <https://note.youdao.com/ynoteshare1/index.html?id=0136350c8134c2c7ab33305771cadc50

**Comment by Kenshin** [comment]
谢谢反馈，有道笔记用了 iframe 方式，所以无法适配这样的页面。

另外，有道笔记的页面已经是优化后的了，有什么需要适配的需要吗？

**Comment by Kenshin** [comment]
我关闭这个 Issues 了，有需要请重新开启。
