### ISSUE TITLE
论坛类页面（如知乎）进入阅读模式后显示异常

### ISSUE THREAD

**Issue by kwkwss** [Kenshin/simpread#1175]
![截屏2020-09-2215 46 57](https://user-images.githubusercontent.com/71693212/93856008-fb7c5e00-fcea-11ea-92d3-8807dcd685b5.png)
![截屏2020-09-2215 46 47](https://user-images.githubusercontent.com/71693212/93856028-ff0fe500-fcea-11ea-9f60-277ddb582fc4.png)

如题，知乎进入阅读模式后，标题和简介部分均出现错乱重复。之前使用是正常的，最近才出现这个问题，使用论坛插件后无变化（昨天使用插件后反而字号出现异常，今天再试字号没有问题）。

另外，也去试了下贴吧，没有这个文本重复的问题，但显示效果依然和原来的效果差距较大。

![截屏2020-09-2215 54 48](https://user-images.githubusercontent.com/71693212/93856722-07b4eb00-fcec-11ea-83bb-8a3b0507e727.png)
![截屏2020-09-2215 54 57](https://user-images.githubusercontent.com/71693212/93856726-097eae80-fcec-11ea-8561-ca437e9c6e59.png)

小白求解，十分感谢。

**Comment by Kenshin** [comment]
谢谢反馈，这是因为另外一个 Issues 修改后造成适配站点的问题。

请告知具体的  URL ，我会修改这个适配规则

***

贴吧没有问题的原因是因为它们的适配规则不一样。

**Comment by kwkwss** [comment]
@Kenshin 

https://www.zhihu.com/question/46042153

感谢！

**Comment by Kenshin** [comment]
@kwkwss 

奇怪，我截图出来的内容

![image](https://user-images.githubusercontent.com/81074/93959392-23bb9980-fd8b-11ea-9a10-09192a8b5c7e.png)

你看看下面截图的内容跟你的有什么区别？

![image](https://user-images.githubusercontent.com/81074/93959447-4057d180-fd8b-11ea-9496-ad7630725eea.png)

**Comment by kwkwss** [comment]
@Kenshin 

下面的截图跟我没区别。上面的截图跟我反馈的问题也只是配色主题的差别吧，问题是一样的。麻烦再看看了~

**Comment by Kenshin** [comment]
你给我的第一张截图里面关于 `描述` 的内容明显重复了。
我给你的截图，关于 `描述` 的内容是正确的。

所以，我才说它们不一样。

***

关于你的问题，可以使用下面的方式解决

![image](https://user-images.githubusercontent.com/81074/94093588-216f4300-fe50-11ea-9f27-f618037ad090.png)

清除红框中的内容即可解决

![image](https://user-images.githubusercontent.com/81074/94093608-30ee8c00-fe50-11ea-994e-4f84529b911e.png)

**Comment by kwkwss** [comment]
@Kenshin 

你好。你的截图里，描述部分其实也是重复了两遍...只是不太明显。在站点编辑里把描述清空后整个描述就不显示了。另外标题重复的问题是目前还解决不了吗？谢谢。

**Comment by Kenshin** [comment]
> 在站点编辑里把描述清空后整个描述就不显示了

是的，知乎的页面中没有关于描述的明确字段，我取的方式有点特别，所以造成了重复两遍的问题。

> 标题的重复

抱歉，下面是标题重复的修改，你可以按照上面的步骤修改，只是把 **标题栏** 替换为下面的内容，即可。

```
[[{$($('.QuestionHeader-main').find('h1')[0]).text()}]]
```

**Comment by kwkwss** [comment]
@Kenshin 

非常感谢。展开描述（点击显示全部）后不会有重复。标题问题已解决。辛苦了~

**Comment by Kenshin** [comment]
没事的，搞定就好。描述的问题我再想办法解决。

也抱歉，之前确实没仔细看，造成了一定的 Debug 时间上的浪费。

**Comment by binsee** [comment]
mark一下，之后我也看看。

**Comment by binsee** [comment]
确认是此页面结构和之前适配时测试页面界面有不同，稍后在pr中提交修复。

**Comment by Kenshin** [comment]
@binsee 

🙏 👍

**Comment by binsee** [comment]
可参考 https://github.com/Kenshin/simpread/pull/1097#issuecomment-712211823 更新适配规则。

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
