### ISSUE TITLE
无法顺利进入阅读模式

### ISSUE THREAD

**Issue by ccdgyro** [Kenshin/simpread#1179]
部分网页可以完美支持阅读模式但也有部分网页（已适配）无法正常进入，具体表现为：
1、进入阅读模式后网页卡死，网页无法对鼠标操作做出任何相应（浏览器工具栏可以）；
2、试图通过点击Chrome插件图标或者通过快捷键进入阅读模时网页刷新为空白页并失去响应；
3、进入阅读模式后，按ESC无法顺利退出阅读模式回归原页面，而是刷新为空白页并失去响应；

很喜欢您的设计，也为您的工作尽了一份微博的支持。
但目前个人仅仅能顺利使用聚焦模式，希望阅读模式的问题能得到解决。

**Comment by Kenshin** [comment]
初步怀疑是跟你的其它插件有冲突造成的，你可以用以下几个方式测试：

1.  **隐身模式下，仅启用简悦** 的方式试试
2. 更换浏览器，并重新安装简悦（不做任何配置的改动）

另外，请告知出现问题的 URL （即便是任意页面，也请找一个给我）以及你的系统环境，浏览器版本等信息。

**Comment by ccdgyro** [comment]
谢谢您的解答。
我按照你的建议在无痕模式进行了测试，阅读模式运行完美。
问题确实出在简悦与其他插件的冲突上。

一个典型的URL是：
https://blog.csdn.net/weixin_47723732/article/details/108471452?utm_medium=distribute.pc_feed.none-task-blog-personrec_tag-8.nonecase&depth_1-utm_source=distribute.pc_feed.none-task-blog-personrec_tag-8.nonecase&request_id=5f57fd8334c6f517ae92eb54

**Comment by Kenshin** [comment]
搞定就好。

没问题的话，请关闭这个 Issues

**Comment by ccdgyro** [comment]
问题已经解决。
