### ISSUE TITLE
网站 https://docs.microsoft.com 出现在适配列表，但是好像没有生效

### ISSUE THREAD

**Issue by mockyli** [Kenshin/simpread#118]
网站 https://docs.microsoft.com 出现在适配列表，但是好像没有生效，如下图所示
![image](https://user-images.githubusercontent.com/15032057/30907807-4c9bd7d2-a3ae-11e7-94d4-5141bf86c364.png)

请教，是适配还没有完成抑或是使用方式不对？

**Comment by Kenshin** [comment]
应该是 url 未适配，请看下图：

![image](https://user-images.githubusercontent.com/81074/30909299-3267b786-a346-11e7-9c5d-97507692c9f2.png)

虽然由于未适配造成的，但应该适配才对... 
主要是这类页面的 url 太乱了，很难找出规律  😥  

下个版本会加入 `主动适配` 的方式，这个链接 → https://i.imgur.com/wOnhKuc.gif

**Comment by mockyli** [comment]
cool ! 期待下一版~~

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)
