### ISSUE TITLE
代码增强插件报错

### ISSUE THREAD

**Issue by alleriagit** [Kenshin/simpread#1183]
- 简悦版本 2.0.0

在以下页面进入阅读模式后,弹出代码增强插件运行错误,没有代码增强效果
url:
https://vimsky.com/examples/usage/atomicreferencearray-set-method-in-java-with-examples.html

**Comment by Kenshin** [comment]
谢谢反馈。

我会把这类问题集中到 #500 （近期 Issues 比较多，所以我将关闭这个 Issues，修复后 **会在这里通知你**，
