### ISSUE TITLE
关于稍后读标签系统的一些建议

### ISSUE THREAD

**Issue by tianchenmao** [Kenshin/simpread#1187]
1.稍后读搜索的时候不区分大小写，且只能使用小写来匹配。为了提高匹配的精确性，建议区分大小写，如果是为了保持一定程度的模糊性，也希望小写能匹配小写与对应的大写，大写能匹配大写（现在大写什么都匹配不了）。
2.稍后读搜索的时候，用#匹配标签，但对于标题#开头的就很难匹配，建议增加个转义符什么的，虽然是个小瑕疵，但为了搜索系统的完备性，还是有改进的必要的。
3.简悦的无限层级标签系统是个很赞的功能，但在实际使用时，会有不便利的时候。标签层级较深时，每次新建个标签都要打上半天，因为它采用的是绝对路径的写法，得从根标签一路打下来，实在不方便，建议提供一种相对路径的写法（可能比较困难）。
4.已打的标签不能修改，要改只能删了从头写，建议增加对已打标签（就是打完标签敲完回车的那个状态）就地修改的功能（比如双击进入可修改状态）（也能在很大程度上缓解上面第三点提到的问题，因为可以实现标签的部分复用）

**Comment by Kenshin** [comment]
谢谢建议，都是很棒的方案。

1和2 我会完善这些细节。

3的话，我考虑下如何优化你说的情况。

4的话，可以增加 **双击标签 → 改为文字的方式** 进行二次修改。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

修复了此问题，目前不区分大小写，除此以外，标签的编辑也更容易了。

> 输入后出现联想，使用 Tab 键会自动将联想的条目放入输入框，方便二次编辑。

> 在已经存在的标签上双击，即可进入编辑模式

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
