### ISSUE TITLE
关于稍后读的几个建议

### ISSUE THREAD

**Issue by DZITZGH** [Kenshin/simpread#1188]
A.使用Twinkstar浏览器安装的插件 不知道为什么浏览器中的插件消失了 
B.重新登录高级账号后 使用稍后读 其中的内容都没有了
C.在使用稍后读中 在未读列表中进行标签的添加后 在将文章归档后 标签选项中相关的文章同步消失 可不可以一直保存在标签选项中
D.能不能在稍后读中添加网页的导航页 收藏一些网址

**Comment by Kenshin** [comment]
A. 请问安装的方式是离线版吗？如果是的话，请通过解压缩的方式来安装，不要直接安装 zip 文件，这样会丢失的风险。

B. 稍后读的内容保存在 [配置文件](http://ksria.com/simpread/docs/#/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中，同时也保存在插件的 Storage 中，所以如果未导出或同步的话，有丢失的风险。 你可以试试通过重新安装的方式是否可以找回（ 我也不确定 100% 能找回）

C. 归档的功能优化已经完成了，下个版本发布。（即：你说的方式，在标签中可以查看

D. 简悦的稍后读是基于可以被阅读模式识别的页面，假设某个页面全部都是列表，这种情况即便加入到稍后读，也没办法使用标注等功能。

关于 D 可以有很多类似工具做替代，或者说你的诉求跟稍后读没有太大关系。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了 **问题 C**，请看下图

![image](https://user-images.githubusercontent.com/81074/100058311-00cd6480-2e64-11eb-901e-1205b65785cc.png)

***

问题 B 可以使用 [自动同步](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5) 保存你的配置文件

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
