### ISSUE TITLE
win10的Edge浏览器打开扩展选项内容空白

### ISSUE THREAD

**Issue by clear2yll** [Kenshin/simpread#1189]
![image](https://user-images.githubusercontent.com/40634471/94245984-a8561580-ff4d-11ea-898d-d611b019e520.png)

1. 点击扩展选项只显示左侧菜单栏
2. 点击左侧菜单没有内容，显示空白

**Comment by Kenshin** [comment]
重新安装呢？
另外，请告诉 Edge 是什么版本？

**Comment by clear2yll** [comment]
重新安装之后就好了谢谢

**Comment by Kenshin** [comment]
搞定就好，没问题的话，我关闭 Issues 了。

**Comment by clear2yll** [comment]
发现一个新的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 中午1:07
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"突然冷风吹"<1483782149@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] win10的Edge浏览器打开扩展选项内容空白 (#1189)





 
搞定就好，没问题的话，我关闭 Issues 了。
