### ISSUE TITLE
我把知乎回答剪藏到语雀，发现图片老是重复一张，知乎上只有一张，但是剪藏到语雀就变成两张

### ISSUE THREAD

**Issue by shytime** [Kenshin/simpread#1190]
我把知乎回答剪藏到语雀，发现图片老是重复一张，知乎上只有一张，但是剪藏到语雀就变成两张

**Comment by Kenshin** [comment]
谢谢反馈。

按照下面的设置即可解决

![image](https://user-images.githubusercontent.com/81074/71318028-07ba5d00-24c6-11ea-9c07-760f576c48a5.png)

***

排除列表加入
```
<noscript>
```
即可解决。

***

适配列表我会统一找个时间一起更新。

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869
