### ISSUE TITLE
有没有考虑可以导出到我来笔记？

### ISSUE THREAD

**Issue by BopSun** [Kenshin/simpread#1193]

**Comment by BopSun** [comment]
https://www.wolai.com/ 我来笔记是模仿 Notion 风格的国内笔记应用，虽然还在内测阶段但发展迅速。既然简悦已经支持 Notion 了，后面是否会考虑也支持导出到 我来笔记 呢？

谢谢！

**Comment by Kenshin** [comment]
谢谢建议。

不过，我个人对这种 Copy 类的服务没什么好感度。

纯技术类的角度说，需要 API 的支持，我不反对接入，等它有 API 且你还再用的话，请再告诉我。

我先关闭这个 Issues 了。😃
