### ISSUE TITLE
导入到印象笔记转义问题且转换为 Markdown 后没有保留原文链接

### ISSUE THREAD

**Issue by 18110739061** [Kenshin/simpread#1194]
**20200927103048周日**
2.0的简悦剪藏至印象笔记报错【保存失败，正在优化结构再次保存】，然后保存到印象笔记里的文章排版会很烂，而且还没有原文链接

**截图**
![image](https://user-images.githubusercontent.com/53848822/94354316-9f2f8a80-00ac-11eb-9ba4-6b32c95cea72.png)
![image](https://user-images.githubusercontent.com/53848822/94354319-a060b780-00ac-11eb-9875-9d9bfd55c755.png)
![image](https://user-images.githubusercontent.com/53848822/94354320-a22a7b00-00ac-11eb-99ef-a892cd73b0e4.png)
![image](https://user-images.githubusercontent.com/53848822/94354325-ac4c7980-00ac-11eb-96ba-0b7fde5baf72.png)

**原文地址，请测试下**
URL：https://blog.csdn.net/erdouzhang/article/details/60966428
![image](https://user-images.githubusercontent.com/53848822/94354342-c1290d00-00ac-11eb-80d3-ceb9d95e0204.png)

**Comment by Kenshin** [comment]
谢谢反馈，保存到印象笔记本身就不是很完美，我 [在这里](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1-FAQ?id=%e5%8d%b0%e8%b1%a1%e7%ac%94%e8%ae%b0%e4%bf%9d%e5%ad%98%e5%a4%b1%e8%b4%a5) 已经反复提过了。

至于代码转义的问题是由于另外一个问题造成的，已经修复了，但只能下个版本解决，细节请看这里 https://github.com/Kenshin/simpread/issues/1064#issuecomment-687972690 （里面附有临时解决方案）

新版发布后我会在这里通知你。

**Comment by Kenshin** [comment]
另外，提示下，如果保存失败的话，会使用 Markdown 结构再保存一次，你看到的提示是这个原因。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了 **转义错误的问题**。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。

**Comment by 18110739061** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你好：
          在使用简悦2.0版本时，我将一个界面转存为md格式，具体见截图，问题是其中的图片都下载了两次，请问是什么问题？附上原网址：From Edge：[(5 封私信 / 12 条消息) 2019 年你读了哪些觉得比较好的计算机书籍？ - 知乎](https://www.zhihu.com/question/361165485/answer/1552198278)
    
        
            
        
    
    
        
        

        
    

    在2020年11月24日 15:20，Kenshin Wang<notifications@github.com> 写道： 



简悦已升级到 2.1.0 版本
解决了 转义错误的问题。

简悦 2.1 目前正在做最后一天的折扣 10元，有需要的话请前往购买 👉 https://simpread.pro/price.html

增加了一些新功能：


简悦 · 同步助手
是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：

自动同步
导出到本地任意目录
原生的 PDF · Epub 输出
邮件服务
直接发送到 Kindle
小书签
详见 👉 http://ksria.com/simpread/docs/#/Sync



自动同步
通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步


授权登录
简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录


每日回顾
简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
详见 👉 http://ksria.com/simpread/docs/#/每日回顾


小书签
可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。


RSS 阅读器辅助
为你的【RSS 阅读器】提供：

基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
一键保存到简悦 · 稍后读。
详见 👉 http://ksria.com/simpread/docs/#/RSSReader



稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader


更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs
联系方式：

请订阅简悦的发布通知频道 👉 https://t.me/simpread
简悦的电报群 👉 https://t.me/simpreadgroup


我将关闭此 Issues 如有问题请重开。

**Comment by Captain2021** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    开发者你好：
            最近在使用简悦的的聚焦视图（按aa快捷键触发）的时候，在聚焦之后我想使用zotero的剪藏插件剪藏当前界面，发现不能剪藏了（剪藏过后本地html是一片空白），请问能否支持在聚焦的情况下也可以使用zotero剪藏呢？基本信息：win10专业版Edge 88.0.705.74Zotero Connector拓展 5.0简悦2.1.0具体操作详见蓝奏云视频（https://wws.lanzous.com/i3LjMmzkl3g）    附件中文章地址：http://goosetalk.com/home.html#/share/card?id=12474&signId=RjlagSWQ4E8%3D
    
        
            
        
    
    
        
        

        
    

    在2020年11月26日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你好：
          在使用简悦2.0版本时，我将一个界面转存为md格式，具体见截图，问题是其中的图片都下载了两次，请问是什么问题？附上原网址：From Edge：[(5 封私信 / 12 条消息) 2019 年你读了哪些觉得比较好的计算机书籍？ - 知乎](https://www.zhihu.com/question/361165485/answer/1552198278)
    
        
            
        
    
    
        
        

        
    

    在2020年11月24日 15:20，Kenshin ***@***.***> 写道： 



简悦已升级到 2.1.0 版本
解决了 转义错误的问题。

简悦 2.1 目前正在做最后一天的折扣 10元，有需要的话请前往购买 👉 https://simpread.pro/price.html

增加了一些新功能：


简悦 · 同步助手
是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：

自动同步
导出到本地任意目录
原生的 PDF · Epub 输出
邮件服务
直接发送到 Kindle
小书签
详见 👉 http://ksria.com/simpread/docs/#/Sync



自动同步
通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步


授权登录
简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录


每日回顾
简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
详见 👉 http://ksria.com/simpread/docs/#/每日回顾


小书签
可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。


RSS 阅读器辅助
为你的【RSS 阅读器】提供：

基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
一键保存到简悦 · 稍后读。
详见 👉 http://ksria.com/simpread/docs/#/RSSReader



稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader


更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs
联系方式：

请订阅简悦的发布通知频道 👉 https://t.me/simpread
简悦的电报群 👉 https://t.me/simpreadgroup


我将关闭此 Issues 如有问题请重开。

**Comment by Kenshin** [comment]
嗨，请问使用 **zotero的剪藏插件剪藏** 你是要剪藏到哪里？

**Comment by Captain2021** [comment]
剪藏为html&nbsp;


 
---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2021年3月16日 13:15:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 导入到印象笔记转义问题且转换为 Markdown 后没有保留原文链接 (#1194)




 
嗨，请问使用 zotero的剪藏插件剪藏 你是要剪藏到哪里？

**Comment by Kenshin** [comment]
> 剪藏为html

完全可以用简悦的导出 HTML 功能，还少安装了一个扩展。
