### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by M-Kepler** [Kenshin/simpread#1195]
发生问题的地址: <https://blog.csdn.net/huanghong6956/article/details/91348021>

**Comment by Kenshin** [comment]
谢谢反馈。 🙏 

CSDN 这类 UGC 的页面偶尔会出现你说的情况，这种是没办法通过适配解决的，目前的做法是是：通过手动重新高亮就可以获取正文了。

因此我关闭这个 Issues 了。
