### ISSUE TITLE
希望能支持下有序/无序列表的标记

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1196]
![image](https://user-images.githubusercontent.com/15308878/94367141-4cd38580-010f-11eb-8700-2f0e192af3d0.png)

**Comment by Kenshin** [comment]
标注功能已经支持了（或者说，标注功能可以标注任意内容。

你所说的「不支持」是指什么？

**Comment by tttsong** [comment]
有序列表的数字，无序列表前面的点都无法标记



---原始邮件---
发件人: "Kenshin Wang"<notifications@github.com&gt;
发送时间: 2020年9月28日(周一) 上午10:27
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tsong"<972249606@qq.com&gt;;
主题: Re: [Kenshin/simpread] 希望能支持下有序/无序列表的标记 (#1196)




 
标注功能已经支持了（或者说，标注功能可以标注任意内容。
 
你所说的「不支持」是指什么？

**Comment by Kenshin** [comment]
原来如此...

这个不需要吧？这些都是自动生成的，你可以在标注的详细页里面看到它们（为列表效果）

**Comment by tttsong** [comment]
一般都转出到第三方笔记里，notion里是看不到的，算是值得优化的一个点吧

**Comment by Kenshin** [comment]
你看看导出（仅标注） Markdown 有没有列表？

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
