### ISSUE TITLE
能否优化下PDF导出？

### ISSUE THREAD

**Issue by Circle321** [Kenshin/simpread#1203]
**请说明发生问题的环境**

- 操作系统：Windows

- 浏览器版本：Chrome 84.0.4147.125 64位

- 简悦版本 **2.0.0**

**请描述你的问题**

阅读模式下导出为PDF格式，如果内容有图片，在分页时会被切割，文字也是。感觉像是把一张图片分成几页一样。

如果能够向Android端Edge浏览器导出PDF那样就好了。

**Comment by Kenshin** [comment]
谢谢反馈，会有更好的 PDF 方案。

你试着更改主题为第一个试试，看看能否有所改善？

**Comment by Circle321** [comment]
> 谢谢反馈，会有更好的 PDF 方案。
> 
> 你试着更改主题为第一个试试，看看能否有所改善？

非常抱歉哈！这段时间没用电脑。

不同主题导出PDF是有些差别，不过在页眉和页脚还是会分割文字。

示例网站：[澎湃新闻](https://www.thepaper.cn/newsDetail_forward_9079779)。附图（主题一）：

![20201010220005](https://user-images.githubusercontent.com/54063942/95656949-29afc980-0b44-11eb-954e-0eaa6db7e1a0.png)

PS. 希望高级账户能够查看已激活设备名称。另外，期待网页版上线，加油！

**Comment by Kenshin** [comment]
@Circle321 

没事的，已经有其他用户反馈过了。

关于设备名的需求，可以考虑。

**Comment by JerryCh007** [comment]
同样的问题。图片被切到两个页面上去了，很是尴尬。
是不是可以把选择权给用户，可分页，或单页。
单页类似Safari那样，整个网页生成为一张大的pdf，不一定非得要按纸张分页去切

**Comment by Kenshin** [comment]
@JerryCh007 
已解决了这个问题，下个版本发布。

> 是不是可以把选择权给用户，可分页，或单页。

目前就是这么做的，简悦只是调用了浏览器的打印规则。

**Comment by JerryCh007** [comment]
棒棒哒💯

Kenshin Wang <notifications@github.com> 于2020年10月13日周二 下午2:46写道：

**Comment by Kenshin** [comment]
嗨，抱歉，简悦 2.1 已经发布了，并解决了这个问题。之前忘记关闭此 Issues ~
