### ISSUE TITLE
购买了激活码，换电脑了，但是不能激活了。

### ISSUE THREAD

**Issue by yaleax** [Kenshin/simpread#1204]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
看看重新授权 http://ksria.com/simpread/docs/#/%E9%AB%98%E7%BA%A7%E8%B4%A6%E6%88%B7?id=%E9%87%8D%E6%96%B0%E6%8E%88%E6%9D%83

**Comment by yaleax** [comment]
我已经重新做了系统，那个账户已经找不到了。

是不是就没办法了？

**Comment by Kenshin** [comment]
可以的，看下面的链接
https://simpread.pro
高级账户 → 丢失配置文件后如何找回里面的说明

**Comment by yaleax** [comment]
好了，步骤记录一下：
1. [通过证书找回UUID ](https://simpread.pro/account)
2.解绑已绑定的设备
3.[导出配制文件到本地](chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common)
4.用文本打开然后修改UUID
5.从本地导入配置文件
6.[恢复高级会员](chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#account)

完成！

**Comment by Kenshin** [comment]
谢谢「自救」成功。👍

双节快乐。
