### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by whichone766** [Kenshin/simpread#1210]
发生问题的地址: <https://weread.qq.com/web/reader/4cf3254071d8830a4cfca02kecc32f3013eccbc87e4b62e>

**Comment by Kenshin** [comment]
谢谢反馈。

简悦其实可以适配微信阅读，因为适配后的页面具有导出功能，但为了避嫌，我没有发布这个适配站点。

**Comment by whichone766** [comment]
好的，辛苦了~我还想问下可以加入自动翻页的功能嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月4日(星期天) 下午4:42
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;")ML"<1093731434@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 无法适配当前页面 (#1210)





 
谢谢反馈。
 
简悦其实可以适配微信阅读，因为适配后的页面具有导出功能，但为了避嫌，我没有发布这个适配站点。

**Comment by Kenshin** [comment]
没事的，也谢谢理解，为了避嫌，也只能如此了。

简悦翻页功能有翻页功能，但因为无法做到自动识别下一页，所以对未适配的页面效果是不好的。
如果你经常看小说的话，建议翻翻 Issues 里面有关于看小说的一个油猴脚本。

**Comment by whichone766** [comment]
没事hh&nbsp; 谢谢作者大大~

只是已经习惯了用微信读书看书了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2020年10月4日(星期天) 下午4:47
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: ")ML"<1093731434@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 无法适配当前页面 (#1210)





 
没事的，也谢谢理解，为了避嫌，也只能如此了。
 
简悦翻页功能有翻页功能，但因为无法做到自动识别下一页，所以对未适配的页面效果是不好的。
 如果你经常看小说的话，建议翻翻 Issues 里面有关于看小说的一个油猴脚本。
