### ISSUE TITLE
页面超链接不规范导致导出到生产力工具后链接失效

### ISSUE THREAD

**Issue by OpsDarren** [Kenshin/simpread#1213]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10 专业版 2004 19041.508**

- 浏览器版本 **Microsoft Edge 85.0.564.68**

- 简悦版本 **2.0.0**

- 发生问题的地址 
1. 原文中：https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
2. Notion中：https://www.notion.so/opsdarren/ansible-builtin-shell-d229bd93bdbe4675a1bf89dd783d5856

**请描述你的问题**

使用简悦阅读模式，保存到Notion后，在Notion内查看文章内超链接的源域名会变成Notion的主域名导致链接内容出错无法打开，每个超链接都是一样的问题
- Example
1. 原文中
It is almost exactly like the [ansible.builtin.command](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#ansible-collections-ansible-builtin-command-module) module but runs the command through a shell (/bin/sh) on the remote node.
2. Notion中
It is almost exactly like the [ansible.builtin.command](https://www.notion.so/command_module.html#ansible-collections-ansible-builtin-command-module) module but runs the command through a shell (/bin/sh) on the remote node.

**截图**

![image](https://user-images.githubusercontent.com/30261327/95183071-07dadd80-07f8-11eb-938e-a012be9026e1.png)

![image](https://user-images.githubusercontent.com/30261327/95183012-f396e080-07f7-11eb-8720-3c5296f2da8a.png)

**Comment by Kenshin** [comment]
谢谢反馈。

你可以看下原文，它的链接因为不规范导致的。
我可以出个插件来解决这种问题。

**Comment by binsee** [comment]
此问题请尝试安装插件 **[修复相对路径为绝对路径](https://simpread.ksria.cn/plugins/details/TgxCzObXib)** 来解决

**Comment by OpsDarren** [comment]
谢谢，非常感谢您的回复！

**Comment by Kenshin** [comment]
@binsee 

额，竟然忘记有这个插件了。 😅  

@OpsDarren  抱歉，耽误了一会时间。

**Comment by OpsDarren** [comment]
@Kenshin 不会不会，是我自己没发现这个插件是这么用的，因为其他的插件在各种情景都会自动触发提示安装，但是这个插件不会，所以我也没想过有插件可以解决这个问题😂

**Comment by Kenshin** [comment]
@OpsDarren 

不是每个问题都有提示。不过，这提醒了我，可以加个提示。😂

**Comment by OpsDarren** [comment]
@Kenshin 真心感谢您的付出👍
