### ISSUE TITLE
关于翻译的建议

### ISSUE THREAD

**Issue by liveHub-ping** [Kenshin/simpread#1214]
建议增加首次开启翻译功能之后持续生效翻译功能的选择，不需要每翻译一次选择一次翻译功能，谢谢你。

**Comment by Kenshin** [comment]
嗨，抱歉，漏掉了这个 Issues

这个插件会全文翻译，到依赖于页面的结构规整性，所以你遇到的问题是，页面结构无法满足全文自动翻译造成的。

你可以给我 URL 看看。

**Comment by Kenshin** [comment]
嗨，[全文翻译](https://github.com/Kenshin/simpread/discussions/1593) 更新到了 1.1.0 增加 **段落翻译**，如何使用 [请看这里](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

https://user-images.githubusercontent.com/81074/187070868-c72cc2a9-9584-4b4d-aa8c-2ae88ae4d20a.mp4

除此之外，还增加了：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

***

我关闭这个 Issues 了，有任何问题可随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，划词翻译 1.0.0 版发布了，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4
