### ISSUE TITLE
xpath匹配模式会丢失部分懒加载图片的<noscript>元素

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1215]
测试页面：
- https://www.joomunited.com/zh-cn/%E6%96%B0%E9%97%BB/%E5%9B%BE%E5%83%8F%E5%8A%A0%E8%BD%BD%E6%B8%90%E8%BF%9B%E5%BC%8F%E6%87%92%E5%8A%A0%E8%BD%BD%E5%9C%A8wordpress%E4%B8%8A
- https://towardsdatascience.com/negative-binomial-regression-f99031bb25b4

相关连接： https://github.com/Kenshin/simpread/issues/1108#issuecomment-704360333

测试中发现部分站点在进入阅读模式后会丢失懒加载图片<img>元素对应的<noscript>元素，因此导致无法通过使用 #1108 的通用方式来解决阅读模式中显示懒加载图片问题。
经过跟踪和对比测试，最终发现原因在于 **xpath** 方式提取高亮内容会丢失部分`<noscript>`元素，而使用 **jquery** 方式提取高亮内容则不会丢失`<noscript>`元素。

示例：https://www.joomunited.com/zh-cn/%E6%96%B0%E9%97%BB/%E5%9B%BE%E5%83%8F%E5%8A%A0%E8%BD%BD%E6%B8%90%E8%BF%9B%E5%BC%8F%E6%87%92%E5%8A%A0%E8%BD%BD%E5%9C%A8wordpress%E4%B8%8A

- 使用 **xpath** 适配（未适配/自动适配）时，阅读模式下的图片元素信息
![image](https://user-images.githubusercontent.com/5285894/95249532-654c4a00-084b-11eb-98ad-88e71a42ba04.png)

- 使用 **jquery** 适配时，阅读模式下的图片元素信息
![image](https://user-images.githubusercontent.com/5285894/95249864-ea376380-084b-11eb-9373-543cd76585b2.png)
这里可以看到 `<a>` 标签中出现了 `<noscript>` 元素，其内有一个懒加载图片的 `<img>` 元素数据

由于简悦对于未适配站点默认是临时生成 **xpath** 语句来提取高亮内容，而在未使用jquery的站点上进入阅读模式，便会丢失部分 `<noscript>` 元素。

上述两个站点（另外包括知乎站点），通过使用 `jquery` 语句适配提取高亮内容，结合使用 `修复显示懒加载图片` 插件（等待审核中），已可完美显示懒加载图片。

------

本issue作为记录，不意味着一定需要修复xpath匹配模式，以使xpath和jquery模式处理结果一致，虽然这确实会导致一些困扰。我们需要明白的是，如果xpath方式提取内容与期望的结果有差异，请改用 `jquery` 方式进行匹配。

**Comment by Kenshin** [comment]
嗨，我这几天用电脑不方便，先 Mark 下，明后天回复你。🙏

**Comment by binsee** [comment]
经过测试，xpath匹配模式仅在未适配时，会使用简悦内置的提取引擎，提取信息会与预期有差异。
原因见 https://github.com/Kenshin/simpread/issues/657#issuecomment-707500247

此情况会在对未适配站点进行适配时，且未适配站点存在图片等资源懒加载的情况时，使用xpath提取信息会与预期存在差异。
此时改用jquery语句进行适配调试，或者使用插件清除内置引擎缓存的数据即可。

插件测试代码如下：

```js
console.log( 'SimpRead Plugin debbuger' )

/********************************************
 * SimpRead Plugin debugger, version 0.0.1
 ********************************************/

/**
 * Plugin
 * 
 * @param {string} $$version current testPlugin verison

 * @param {jquery} $read    jquery object
 * @param {jquery} $title   jquery object
 * @param {jquery} $desc    jquery object
 * @param {jquery} $content jquery object
 * @param {jquery} $footer  jquery object
 * @param {jquery} $process jquery object
 * @param {jquery} $toc     jquery object

 * @param {object} Notify
 * @param {func}   $$storage, usage wirte: $$storage( plugin_id, {foo:bar}, callback=>{...}) | read: $$storage( plugin_id, undefined, callback=>{...})
 * @param {func}   highlight function
 * @param {object} browser, include: chrome, browser(firefox)

 * @param {object} current site object
 * @param {object} current simpread.read object
 */
function plugin( $$version, $read, $title, $desc, $content, $footer, $process, $toc, Notify, $$highlight, browser, $$storage, $$current, $$read, $$control, $$save, $$th, $$export, $$ss, $$service, $$waves, $$ui, $$srvnames, $$actionbar ) {
    // debugger;
    (function () {
        //!!!
        // Don't changed section source
        // If duplicate, please copy this section
        // current plugin id
        // const $$id = "h5IhWnpnDx";
        
        //!!!
        ////////////////////////////////////////
console.log('$$current.site after:',$$current.site)
$$current.site.html=''
    })();
}

/**
 * Style
 * 
 * @returns {string} style str
 */
function style() {
    return ``;
}

/**
 * Trigger
 * 
 * @returns {string} style str
 */
function trigger() {
    return ``;
}

// change top to simpread
window.simpread.testPlugin( style, plugin, trigger );
```
