### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by feikulou** [Kenshin/simpread#1216]
发生问题的地址: <https://finance.sina.com.cn/china/gncj/2020-09-21/doc-iivhvpwy8038347.shtml>

**Comment by Kenshin** [comment]
谢谢反馈，导入到印象笔记确实有些问题，细节 [请看这里](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1-FAQ?id=%e5%8d%b0%e8%b1%a1%e7%ac%94%e8%ae%b0%e4%bf%9d%e5%ad%98%e5%a4%b1%e8%b4%a5)

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
