### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by xsx123123** [Kenshin/simpread#1218]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

  买了高级账户  一直  没有办法激活  一直 显示 服务器问题   
<img width="876" alt="截屏2020-10-07 下午8 02 51" src="https://user-images.githubusercontent.com/44941750/95328618-637c9800-08d8-11eb-9551-890af938f273.png">

**Comment by Kenshin** [comment]
嗨，你可以用 https://simpread.pro/help 高级账户对应的 **无法激活高级会员的解决办法（提示服务器错误）** 对应的解决办法。

**Comment by xsx123123** [comment]
你好  我在  少数派 购买了  简悦  高级账户 但是在激活账户是一直显示后台服务器 异常  无法激活

**Comment by Kenshin** [comment]
@xsx123123 

我已经告诉你解决方法了 https://github.com/Kenshin/simpread/issues/1218#issuecomment-704968611
