### ISSUE TITLE
高亮插件提示运行出错

### ISSUE THREAD

**Issue by CodingOX** [Kenshin/simpread#1220]
对应的网址是：https://github.com/redisson/redisson/wiki/7.-%E5%88%86%E5%B8%83%E5%BC%8F%E9%9B%86%E5%90%88
希望有帮助。

**Comment by Kenshin** [comment]
谢谢反馈，高亮问题都会集中反馈到 #500 里面。

我先关闭这个 Issues 修复后会通知到你。
