### ISSUE TITLE
坚果云一直授权失败

### ISSUE THREAD

**Issue by zhangmlcn** [Kenshin/simpread#1221]
坚果云一直授权失败
![image](https://user-images.githubusercontent.com/43921261/95443735-85852180-098f-11eb-905b-09cf584b1441.png)

**Comment by binsee** [comment]
是否有正确填写坚果云账号和应用密码？

**Comment by zhangmlcn** [comment]
> 是否有正确填写坚果云账号和应用密码？
> 
> ![image](https://user-images.githubusercontent.com/5285894/95451988-288f6880-099b-11eb-971f-1c652cfa398e.png)
> 
> 我这边测试是正常的。
不行，试过很多次，都不行。删了再添加应用都不行。。。

**Comment by zhangmlcn** [comment]
> 是否有正确填写坚果云账号和应用密码？
> 
> ![image](https://user-images.githubusercontent.com/5285894/95451988-288f6880-099b-11eb-971f-1c652cfa398e.png)
> 
> 我这边测试是正常的。

之前好不容易成功了一次，结果一直同步不了。然后关了再登录，再也没成功过。

**Comment by binsee** [comment]
请补充一下信息，以供作者参考
系统：
浏览器及版本：
插件版本：


另外，你可以按以下步骤尝试一下：
1. 更新插件到最新版
2. 导出配置文件到本地（备份配置）
3. 重置当前配置
4. 授权坚果云

如果仍然失败，那只能等作者回复了

**Comment by zhangmlcn** [comment]
> 请补充一下信息，以供作者参考
> 系统：
> 浏览器及版本：
> 插件版本：
> 
> 另外，你可以按以下步骤尝试一下：
> 
> 1. 更新插件到最新版
> 2. 导出配置文件到本地（备份配置）
> 3. 重置当前配置
> 4. 授权坚果云
> 
> 如果仍然失败，那只能等作者回复了

系统：win10
浏览器及版本：edge  85.0.564.68
插件版本：2.0.0

重置+清除本地均不能登录

**Comment by binsee** [comment]
我在edge进行了测试，是可以正常授权的

系统：win10
浏览器及版本： edge 85.564.70
插件版本： 2.0.0 （edge商店安装）

测试时全新安装的简悦插件，一次即授权成功。

**Comment by zhangmlcn** [comment]
> 我在edge进行了测试，是可以正常授权的
> 
> 系统：win10
> 浏览器及版本： edge 85.0.564.70
> 插件版本： 2.0.0 （edge商店安装）
> 
> 测试时全新安装的简悦插件，一次即授权成功。

。。但是我这边的确没成功。。

**Comment by binsee** [comment]
你试试看其他软件通过应用授权的方式是否能访问你的坚果云？
比如安卓上的 `MiXplorer` app等支持访问 WebDEV 的

**Comment by zhangmlcn** [comment]
> 你试试看其他软件通过应用授权的方式是否能访问你的坚果云？
> 比如安卓上的 `MiXplorer` 等支持访问 WebDEV 的app

。反复尝试，发现是被本地Adguard拦截了。。
Referrer has been hidden
The IP has been hidden
The User Agent has been hidden
DNT Header has been sent
Authorization header has been blocked

还是第一次发现拦截这个的。。

**Comment by Kenshin** [comment]
@zhangmlcn 

谢谢自查，之前也偶尔有用户遇到这个问题，虽然不知道是否同样的问题导致，但可以作为建议给提示他。

@binsee 
谢谢帮忙 Debug 🙏

**Comment by binsee** [comment]
> > 你试试看其他软件通过应用授权的方式是否能访问你的坚果云？
> > 比如安卓上的 `MiXplorer` 等支持访问 WebDEV 的app
> 
> 。反复尝试，发现是被本地Adguard拦截了。。
> Referrer has been hidden
> The IP has been hidden
> The User Agent has been hidden
> DNT Header has been sent
> Authorization header has been blocked
> 
> 还是第一次发现拦截这个的。。

你这个装的不是浏览器上的Adguard插件，而是`AdGuard for Windows`吧？
看起来是过滤太严格，把请求中的授权信息都给拦截了。

**Comment by zhangmlcn** [comment]
> > > 你试试看其他软件通过应用授权的方式是否能访问你的坚果云？
> > > 比如安卓上的 `MiXplorer` 等支持访问 WebDEV 的app
> > 
> > 
> > 。反复尝试，发现是被本地Adguard拦截了。。
> > Referrer has been hidden
> > The IP has been hidden
> > The User Agent has been hidden
> > DNT Header has been sent
> > Authorization header has been blocked
> > 还是第一次发现拦截这个的。。
> 
> 你这个装的不是浏览器上的Adguard插件，而是`AdGuard for Windows`吧？
> 看起来是过滤太严格，把请求中的授权信息都给拦截了。

嗯，查看了下，之前打开了拦截第三方授权头

**Comment by linmu2020** [comment]
![image](https://user-images.githubusercontent.com/91551058/135111478-13c54f74-10af-4f99-97e6-60c061e896cb.png)
谁能有我愚蠢，一直以为这个地方是在下面绑定按钮中点击出来的。一个小时的尝试后，我才发现这个是要自己填写的。。。。
哭死😭

**Comment by Kenshin** [comment]
@linmu2020 

哈哈，不哭（摸摸头）😂
