### ISSUE TITLE
【enhance】代码高亮插件在部分网站上 “无换行”浓缩成一团

### ISSUE THREAD

**Issue by CodingOX** [Kenshin/simpread#1224]
对应地址：https://www.baeldung.com/redis-redisson
500 那个地址无法回复，所以此处反馈！

**Comment by Kenshin** [comment]
谢谢反馈。

我会把这个 Issues 加入到 #500 里面

同一类型的问题只开一个 Issues，所以暂时先关闭这个 Issues，修复后会 **在这里通知你**。
