### ISSUE TITLE
无法找到导出到OneNote的文章

### ISSUE THREAD

**Issue by xyfx666** [Kenshin/simpread#1226]
无法找到导出到OneNote的文章

**Comment by Kenshin** [comment]
在快速笔记中。
另外，也可以重新授权，Onenote 的授权有点问题，下个版本已修复了。（暂时未发布而已）

**Comment by ghostzhang** [comment]
> 在快速笔记中。
> 另外，也可以重新授权，Onenote 的授权有点问题，下个版本已修复了。（暂时未发布而已）

在快速笔记中找到了，不过还有一个问题，怎么知道是在哪个笔记本里的快速笔记？

**Comment by Kenshin** [comment]
@ghostzhang 

`快速笔记` 应该是在默认笔记本下面的。另外，未发布的版本会保存在 `SimpRead` 也是默认笔记本下面。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
