### ISSUE TITLE
已购高级账户无法使用高级功能

### ISSUE THREAD

**Issue by LythrumSalicaria** [Kenshin/simpread#1229]
开发者您好，非常喜欢简悦这款产品。
我个人使用的Chrome浏览器，昨天购买了高级账户，但是发现合辑、主题变换、标注拖动排序等高级账户的功能仍然无法使用，带有红色的锁子。接连2天测试都是同一结果，请问应该怎么解决呢？

**Comment by Kenshin** [comment]
[取消授权](http://ksria.com/simpread/docs/#/%E9%AB%98%E7%BA%A7%E8%B4%A6%E6%88%B7?id=%E9%87%8D%E6%96%B0%E6%8E%88%E6%9D%83) 后重启浏览器再授权就可以了。

另外，也请看下  https://simpread.pro/help 里面 **高级账户** 的相关说明

**Comment by LythrumSalicaria** [comment]
感谢您的回答，问题已解决

**Comment by Kenshin** [comment]
搞定就好，那我关闭这个 Issues 了。 😀
