### ISSUE TITLE
求阅读模式适配网站https://bohaishibei.com

### ISSUE THREAD

**Issue by Mlearn** [Kenshin/simpread#123]
如题，希望能够加入对 https://bohaishibei.com 这个网站的适配

**Comment by Kenshin** [comment]
okay 刚看了下，没问题，不过需要过几天，或许会跟 1.0.4 一起发布~

**Comment by Kenshin** [comment]
已适配~   
请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
