### ISSUE TITLE
不能禁用快捷键

### ISSUE THREAD

**Issue by nico-zck** [Kenshin/simpread#1230]
希望能够禁用快捷键功能。
付费用户但不是重度使用者，每次出现快捷键冲突的时候，都需先找到冲突功能在设置中的位置，然后又要重新设置成别的快捷键。
频繁更改会造成记忆负担，个人感觉手动操作就行，没必要非要记忆快捷键是什么，然后又担心冲突问题。

**Comment by Kenshin** [comment]
可以考虑。

不过，简悦在页面中的快捷键只有「两组」

这样也会冲突吗？

**Comment by nico-zck** [comment]
三组，还有一组是添加阅读列表。
冲突的确是很好解决，每次换一组快捷键就行。但其实我用简阅快捷键比较少，由于不能禁用，我就一直在换快捷键，于是导致我换完就忘记了。然而，偶尔一次的冲突，总会让我觉得允许禁用或者不设定任何快捷键才是个更好的解决方案吧。


发自我的iPhone

在 2020年10月10日，下午11:16，Kenshin Wang <notifications@github.com> 写道：

﻿

可以考虑。

不过，简悦在页面中的快捷键只有「两组」

这样也会冲突吗？

**Comment by Kenshin** [comment]
是的，「漏掉」了稍后读的快捷键。

***

可以考虑你的建议。 😀

**Comment by fh345392977** [comment]
我感觉什么组合我都能触发。。。。能给个关闭快捷键的选项吗？:sweat_smile:

**Comment by Kenshin** [comment]
@fh345392977 

emmm 我也考虑禁用快捷键这个事情，如确定需求的话，下个版本发布，实现后会通知你。

**Comment by tiancheng2000** [comment]
哈哈，能提高优先级太好了~ 付费前就有这个需求咯☺
我也是玩打字比赛时经常会冲突（AA之类的），其实只需要允许用户把快捷键改成「空」就可以了呢

**Comment by Kenshin** [comment]
@tiancheng2000 

考虑下，看看时间是否允许？

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
