### ISSUE TITLE
CSDN站点目录点击无法跳转

### ISSUE THREAD

**Issue by sanren1024** [Kenshin/simpread#1233]
CSDN站点blog文章，markdown编辑的目录在<code>simpread</code>渲染后点击无法跳转。

1. 打开控制栏显示功能情况下，会显示启用了控制栏无法使用功能；
2. 关闭控制栏显示后，点击会弹出样式设置弹窗，始终无法实现跳转；

情况见图。

![Screenshot-from-2020-10-12-15-34-06](https://user-images.githubusercontent.com/28945129/95718926-b1f7b100-0ca1-11eb-96c7-00477b88ffba.png)
![Screenshot-from-2020-10-12-15-37-23](https://user-images.githubusercontent.com/28945129/95718928-b2904780-0ca1-11eb-968a-cc50c268debe.png)

**Comment by binsee** [comment]
文章内跳转是基于锚点的，简悦提取后的内容锚点仍然是原始页面的，并不会在跳转到阅读模式下的内容里。

如果要使用原始页面目录跳转，你可以试试“**聚焦模式**”而非“**阅读模式**”。

**Comment by sanren1024** [comment]
> 文章内跳转是基于锚点的，简悦提取后的内容锚点仍然是原始页面的，并不会在跳转到阅读模式下的内容里。
> 
> 如果要使用原始页面目录跳转，你可以试试“**聚焦模式**”而非“**阅读模式**”。

Thx!  聚焦模式下可以解决此问题。

<code>聚焦模式</code>的切换方式很不明显，也无法直接从<code>阅读模式</code>进行切换。
