### ISSUE TITLE
我需要原文的这些加粗、颜色的细节，但是在简悦优化下，变成了全黑操作

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#1234]
网页链接：https://blog.csdn.net/weixin_42061636/article/details/107132396
网络原文截图：
![image](https://user-images.githubusercontent.com/37976371/95724164-98a63300-0ca8-11eb-829f-6cf02b98f6f9.png)
但是，简悦的显示是这个样子的
![image](https://user-images.githubusercontent.com/37976371/95724225-a956a900-0ca8-11eb-81bf-2a0f6ef43579.png)

这不是我想要的，是我操作失误了吗

**Comment by binsee** [comment]
简悦是将文章的内容提取筛选为高亮内容，过程中会丢失网页上原本的样式，这是正常的，否则不同网页使用简悦出来会是各种奇奇怪怪的样子。

如果你只是希望此文章有个良好的阅读体验，并保留文章原本的颜色等样式，你可以在网页上右键使用简悦的“聚焦模式”，而非阅读模式。

**Comment by rw1995** [comment]
好的，多谢您的解答，舒服了，哈哈哈哈，已充值会员，此外问一下，能否两台电脑同时浏览器开着同一个高级会员？

**Comment by rw1995** [comment]
@binsee

**Comment by binsee** [comment]
> 好的，多谢您的解答，舒服了，哈哈哈哈，已充值会员，此外问一下，能否两台电脑同时浏览器开着同一个高级会员？

可以，最多支持对三台设备进行授权，请参考 https://github.com/Kenshin/simpread/issues/908#issuecomment-678770898

**Comment by Kenshin** [comment]
@binsee 
🙏  是不是请杯 ☕  给你啊，太帮忙了。

@rw1995 
关于高级账户的相关事宜，建议看下 https://simpread.pro/help

***

另外，没有其它问题的话，我关闭这个 Issues 了。
