### ISSUE TITLE
拖拽排序设置问题

### ISSUE THREAD

**Issue by cpp-jiang** [Kenshin/simpread#1237]
![image](https://user-images.githubusercontent.com/25993096/95736512-ec207d00-0cb8-11eb-9a45-45f9787eae9d.png)
这个开启了之后会自动关闭?
还有不能默认开启么?

**Comment by Kenshin** [comment]
是的，开启后会影响其它功能，因为拖拽事件操作的优先级比较高，同时它并不是一个常用功能。
