### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by najunuoyan** [Kenshin/simpread#1239]
发生问题的地址: <https://note.youdao.com/ynoteshare1/index.html?id=2e3f30220a28c22357453ddbcd9269b0

**Comment by Kenshin** [comment]
谢谢反馈。

这个页面使用了 iframe 方式，所以简悦并不支持此模式（主要是基于性能的考量）
另外，这个页面从某种程度上说，也是优化后的页面了，难道想 **俄罗斯套娃** ？

所以，我关闭这个 Issues 了，有异议的话，可以随时跟我讨论。 😀
