### ISSUE TITLE
爱发电购买问题

### ISSUE THREAD

**Issue by hillmoonbird** [Kenshin/simpread#1242]
在爱发电上付款之后，如何获得兑换码呢？
![image](https://user-images.githubusercontent.com/72114950/96101936-8f1b0600-0f08-11eb-89dd-70a9e3c6a9b9.png)

**Comment by Kenshin** [comment]
嗨，没问题的话，我关闭这个 Issues 了。 😀

**Comment by hillmoonbird** [comment]
好的

发件人: Kenshin Wang
发送时间: 2020年10月15日 18:07
收件人: Kenshin/simpread
抄送: hillmoonbird; Author
主题: Re: [Kenshin/simpread] 爱发电购买问题 (#1242)

嗨，没问题的话，我关闭这个 Issues 了。 😀
