### ISSUE TITLE
站点适配 dedao.cn (得到app 域名变更)

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1246]
发现 `得到app` 站点从原域名 www.biji.com 已重定向到域名 www.dedao.cn

且页面结构有变动，需更新适配。原适配issue #959

**Comment by binsee** [comment]
已提交pr更新适配。

由于页面内容动态加载，在网页载入后自动进入阅读模式时，会无法获取文章内容，内容区会提示`异步加载型页面，本次未能获取到内容元素，请重新进入阅读模式尝试`。
此时，按`Esc`退出阅读模式，看到网页能正常显示文章内容，再 `A A`进入阅读模式，此时即可正常显示文章内容。

**Comment by Kenshin** [comment]
@binsee 

已收到 PR，等发布再关闭这个 Issues

**Comment by binsee** [comment]
适配已合并，更新官方主适配源或更新简悦插件至2.1.0版本后，即可在阅读模式中正确显示。
