### ISSUE TITLE
stackoverflow无法正确识别

### ISSUE THREAD

**Issue by NightAsker** [Kenshin/simpread#1249]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**stackoverflow的内容无法被正确识别，显示正文获取异常，是否重新获取？**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvm>

**stackoverflow无法识别**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
![image](https://user-images.githubusercontent.com/64188869/96256914-0f666780-0fec-11eb-9cfa-c4e897097992.png)

**Comment by Kenshin** [comment]
谢谢反馈，目前是这样的。 😂
修复后，会通知你。

**Comment by Coelancanth** [comment]
> 谢谢反馈，目前是这样的。 😂
> 修复后，会通知你。

请问现在进度如何了😂，我现在还是没法把Stackoverflow/Math etc上的内容保存到简约上。（有时候阅读模式只会收录第二个最佳答案

**Comment by Kenshin** [comment]
我又来了  😂   @binsee 能否帮忙再看下？

**Comment by Kenshin** [comment]
嗨，这个站的适配规则已经更新，请使用下图的方式手动更新，位置在 选项页 → 站点管理

![image](https://user-images.githubusercontent.com/81074/120067368-c8763f80-c0ad-11eb-8706-3b0e6798641d.png)

我关闭这个 issues 了。
