### ISSUE TITLE
wikipedia 进入阅读模式再退出后, 字号变小

### ISSUE THREAD

**Issue by reklanirs** [Kenshin/simpread#125]

**Comment by Kenshin** [comment]
我随便找了一页，比如 https://zh.wikipedia.org/wiki/%E4%BA%8E%E8%B0%A6
前后对比了一下，并没有问题，在你这里是每页都有问题吗？最好告知运行环境。  😀

**Comment by reklanirs** [comment]
进入阅读模式前:
![image](https://user-images.githubusercontent.com/5917301/30996809-87a58fd8-a491-11e7-8c91-974f91a5630e.png)

进入阅读模式再退出后:
![image](https://user-images.githubusercontent.com/5917301/30996822-9d6bb7ca-a491-11e7-8986-351289ff0440.png)

我也觉得很奇怪... 记得之前并没有这个问题
随便在csdn上找了篇文章试了试, 没有问题
环境是OSX10.11.6, chrome canary 63.0.3218.0

**Comment by Kenshin** [comment]
我的截图

![image](https://user-images.githubusercontent.com/81074/30997129-52cdaaee-a48b-11e7-80e5-5ebbc9182cda.png)

![image](https://user-images.githubusercontent.com/81074/30997163-8a61e4c0-a48b-11e7-999f-6b1572fd7684.png)

***
每个页面的情况都不一样，不代表 csdn 没问题，wikipedia 也没问题。
但我这边的截图是没有问题的...  
我的 Chrome 61.0.3163.100 比你的版本低。

**Comment by reklanirs** [comment]
如果只是特例就先无视这个issue吧..  说不定是chrome canary的bug来着
如果过几天问题还在我再汇报

**Comment by airycanon** [comment]
我这边测试也没有重现。
Ubuntu 17.04 
Chromium 61.0.3163.79

**Comment by Kenshin** [comment]
@airycanon
谢谢提示～ 或许是 63 的问题，亦或 61 的问题。 😉

**Comment by dreacter** [comment]
我的测试重现了问题。
具体环境Win 10 x64，Chrome 版本 61.0.3163.100 (x64)。

**Comment by Kenshin** [comment]
@dreacter
哪个 url 还是每个页面？

**Comment by dreacter** [comment]
所有页面都会变小。

**Comment by Kenshin** [comment]
@dreacter
这就奇怪了， Win / Mac 61 版我都测试过…

**Comment by dreacter** [comment]
试着抓了几张图，不知道有没有帮助。。。
问题似乎是图中的“style="font-size: 70%!important'"”导致的。
未使用simpread：
![1](https://user-images.githubusercontent.com/20962101/31052816-5488f806-a6c1-11e7-88b7-39b7b9e1b769.PNG)
使用阅读模式时：
![default](https://user-images.githubusercontent.com/20962101/31052831-7c4ae3e0-a6c1-11e7-9f9a-272043002270.PNG)

退出阅读模式后：

![2](https://user-images.githubusercontent.com/20962101/31052832-7e61548e-a6c1-11e7-8d21-ef97cea04242.PNG)

**Comment by Kenshin** [comment]
@dreacter
好，会有帮助的。 👍

**Comment by reklanirs** [comment]
过了一周, chrome更新了两回, 问题还在 ╮(￣▽￣)╭ 
来源也发现了: 进入阅读模式后, "字体大小"设为"正常"时, 退出后页面字体显示正常;
"字体大小"设为"增大"或"减小"时, 退出后页面字体变小, html属性里多出一个style="font-size: 70%!important"

**Comment by Kenshin** [comment]
@reklanirs 
okay 我再确认下这个问题~

**Comment by airycanon** [comment]
https://github.com/Kenshin/simpread/blob/master/src/service/stylesheet.js#L93
这里把 $( "html" ) 改成 $( "sr-read" ) 是不是就可以了？

**Comment by Kenshin** [comment]
@airycanon 
之前的确有过这个问题，但应该修复了，我再确认下。
这几天在忙别的事情，稍晚些会 merge 你的 pr ~    😢

**Comment by Kenshin** [comment]
@reklanirs 
@dreacter 
的确是一个 Bug，已 Fixed，将会随着 1.0.4 一起发布，感谢反馈~
PS：我之前没有发现的原因是，没有将字体大小改为 `最大`，故而无法重现。 😂 

@airycanon 
> 这里把 $( "html" ) 改成 $( "sr-read" ) 是不是就可以了？ 
并不会解决问题，因为只有把  `font-size: 70%!important;` 放到 `<html>` 里面才会生效。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
