### ISSUE TITLE
请问可以添加   notion动作的快捷按键吗？

### ISSUE THREAD

**Issue by 1tonsilla** [Kenshin/simpread#1254]
目前必须点  ...，然后点动作，然后点N
有点繁琐   我使用notion多，希望可以在悬浮按钮那边添加一个N的快捷按键，这样减少操作步骤  谢谢！

**Comment by Kenshin** [comment]
支持快捷键
键盘输入 s r → , 查看全部快捷键

另外，也可以配合 https://github.com/Kenshin/simpread/issues/891 https://github.com/Kenshin/simpread/issues/892

**Comment by 1tonsilla** [comment]
谢谢啦~我使用了 #891的悬浮菜单

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
