### ISSUE TITLE
http://news.mydrivers.com/1/452/452280.htm使用 阅读模式 解析后 无法正常显示

### ISSUE THREAD

**Issue by winder9090** [Kenshin/simpread#126]
http://news.mydrivers.com/1/452/452280.htm 使用 阅读模式 解析后 无法正常显示

**Comment by Kenshin** [comment]
感谢反馈，中秋快乐～
现在不在电脑旁，我会再确认的。
估计是结构改变了，可以通过修改站点适配器改变的。

**Comment by Kenshin** [comment]
刚看了一下，不太好解决，因为 url 相似的页面结构确差别很大。
下个版本会改善 `无法正常显示` 的逻辑，关联问题请看 https://github.com/Kenshin/simpread/issues/63

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> 匹配失败后，自动退出阅读模式，并启动临时阅读模式，可继续生成阅读模式的页面。

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update
