### ISSUE TITLE
标注浮动工具栏在文字跨行情况下浮现的位置不佳

### ISSUE THREAD

**Issue by kccbc** [Kenshin/simpread#1260]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Chromium 80.0.3987.163**

- 简悦版本 **2.0.0**

- 发生问题的地址 **阅读模式-标注-浮动工具栏 **

**请描述你的问题**

当网页中有大段连续多行文字需要分别标注的情况下，如果后面需标注文字出现跨行情况，标注浮动工具栏会出现在上一个标注区域内，鼠标很难在不触发上一个标注区域的情况下对后续文字进行标注。

**截图**

![QQ截图20201019140103](https://user-images.githubusercontent.com/71060372/96407280-9c3f3a00-1213-11eb-9236-8597a0748899.jpg)

**Comment by Kenshin** [comment]
谢谢反馈，确实在相邻两个标注段落会出现这个问题，我看看能否优化下。

之前也有用户提过这个情况。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
