### ISSUE TITLE
Suggestion: 配置同步到国内的某个盘

### ISSUE THREAD

**Issue by sanren1024** [Kenshin/simpread#1264]
目前**配置同步**只能同步至<code>**Dropbox**</code>，但在绝大多数情况下是没有条件来访问<code>**Dropbox**</code>的，因此建议在国内可以有选择，可以同步到其他位置(有条件，有技术实现)。

**Comment by Kenshin** [comment]
目前支持 [坚果云](http://ksria.com/simpread/docs/#/%E5%90%8C%E6%AD%A5)  😀
