### ISSUE TITLE
能否保留页面原来的 CSS 样式

### ISSUE THREAD

**Issue by childe** [Kenshin/simpread#1267]
非常感谢作者提供了这么好用的插件, 几乎每天都在使用.

请问能不能使用原来页面的 CSS 样式, 而不是使用简悦自己的?

我知道简悦提供了约十个主题可以使用, 也可以自己定制. 但有时候想保留原页面自己的样式. 

仅仅是提出一个想法, 插件已经足够好用了~~

效果如下:

原页面:

![image](https://user-images.githubusercontent.com/2444825/96575854-e1db3000-1303-11eb-9c03-de63125891e9.png)

简悦页面:

![image](https://user-images.githubusercontent.com/2444825/96575876-e99ad480-1303-11eb-8936-ae18f65d8538.png)

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。
但你的这个诉求，是很难实现的。 😭

你可以使用聚焦模式来确保样式和布局不变。

**Comment by childe** [comment]
好的, 再次感谢.
