### ISSUE TITLE
强烈建议加入设备迁移功能

### ISSUE THREAD

**Issue by Amoswuuuu** [Kenshin/simpread#1268]
之前在少数派购买了一个码，在公司电脑登了一下。主要是工作时间不怎么大块阅读，我以为可以迁移，现在自己的笔记本只能无Pro，很痛苦。

**Comment by binsee** [comment]
你可以在 https://simpread.pro/help 查看 **高级账户部分** - **如何授权多台（最多三台）**

**Comment by Kenshin** [comment]
@Amoswuuuu 

请看下 @binsee  的提示，同时简悦也支持解绑功能，可以通过此功能解除不需要登录高级账户的设备。（同样，如何使用请看上面的链接

**Comment by Amoswuuuu** [comment]
> @Amoswuuuu
> 
> 请看下 @binsee 的提示，同时简悦也支持解绑功能，可以通过此功能解除不需要登录高级账户的设备。（同样，如何使用请看上面的链接

好的，感谢~

**Comment by Amoswuuuu** [comment]
> 你可以在 https://simpread.pro/help 查看 **高级账户部分** - **如何授权多台（最多三台）**

感谢

**Comment by Kenshin** [comment]
@Amoswuuuu 

没问题的话，可以关闭个这个 issues 了。 😀

**Comment by Amoswuuuu** [comment]
> 之前在少数派购买了一个码，在公司电脑登了一下。主要是工作时间不怎么大块阅读，我以为可以迁移，现在自己的笔记本只能无Pro，很痛苦。
