### ISSUE TITLE
Assistive Touch - 类似 iOS 的快捷浮动工具         显示不出来了

### ISSUE THREAD

**Issue by 1tonsilla** [Kenshin/simpread#1269]
系统：win10 1909
浏览器：chrome  86.0.4240.75
不知道为啥，昨天用这个插件挺好的，今天发现这个悬浮的工具不显示了，我在插件中心 卸载 然后重新安装也没用，不知道什么情况

**Comment by Kenshin** [comment]
emmm 按道理不太可能。

你是不是更改过分辨率（或类似的事情），有可能是因为定位问题导致出现在屏幕以外的情况。
还有，看看浏览器控制台有没有什么报错信息？

**Comment by 1tonsilla** [comment]
没改过呢。。就是这两天装插件啊 什么的比较多，没有分辨率相关的事情
https://imgchr.com/i/BCUL5Q
我弄个个截图，如果有空可以帮忙看下。。如果比较忙 不好排查也无所谓啦，如果以后有别人反馈 再来看看 反正也不是什么大问题~

**Comment by Kenshin** [comment]
如果你安装了很多插件的话，或许也可以试试 **仅在隐身模式下，仅启用简悦** 试试，也有可能是被其它扩展污染造成的。

看了下你给的截图，似乎没有什么关于简悦的报错信息。

**Comment by 1tonsilla** [comment]
> 如果你安装了很多插件的话，或许也可以试试 **仅在隐身模式下，仅启用简悦** 试试，也有可能是被其它扩展污染造成的。
> 
> 看了下你给的截图，似乎没有什么关于简悦的报错信息。

嗯 隐私模式下我只启动简，但是还是不出现，算啦  反正也不大影响使用 谢谢啦~

**Comment by binsee** [comment]
看起来似乎是webdav配置问题？
你是不是配置了WebDav，检查一下这里配置是不是错了（json文本不标准），清空其配置再试试看。

![image](https://user-images.githubusercontent.com/5285894/96689988-b6b11900-13b5-11eb-93b3-8990c61f519c.png)
![image](https://user-images.githubusercontent.com/5285894/96690003-ba44a000-13b5-11eb-887d-95cd3e8a4617.png)

**Comment by 1tonsilla** [comment]
> 看起来似乎是webdav配置问题？
> 你是不是配置了WebDav，检查一下这里配置是不是错了（json文本不标准），清空其配置再试试看。
> 
> ![image](https://user-images.githubusercontent.com/5285894/96689988-b6b11900-13b5-11eb-93b3-8990c61f519c.png)
> ![image](https://user-images.githubusercontent.com/5285894/96690003-ba44a000-13b5-11eb-887d-95cd3e8a4617.png)

哈哈 我重置当前配置文件，然后重新安装插件，熟悉的悬浮出来啦~谢谢！
另外想请问下，第二张图片，就是那个有webdav的是哪来的啊，我没有上传这张图片呀

**Comment by binsee** [comment]
上述的应该并非引起此问题的原因。

我这边也发现出现此问题，并经过如下尝试解决了无法显示的问题。

### 步骤
1. 打开 简悦选项页 - 插件管理，卸载 `Assistive Touch` 插件
2. 重新安装 `Assistive Touch` 插件
3. 彻底关闭浏览器并重新打开
4. 在任意文章页进入阅读模式，查看是否有显示

----

我刚出去一趟，没来得及发这个，回来你已经解决了哈

另，上边第二张是根据报错信息定位简悦代码中的位置，你可以忽略

**Comment by Kenshin** [comment]
@1tonsilla 
抱歉，你之前给我的截图里面的报错信息是包含了简悦的报错内容，我看漏了...  😅 

一般来说，造成这个问题的可能是插件的配置文件出现了问题，不知道你能否再次复现这个错误，否则先暂时不动这个地方了。

@binsee 谢谢提示。 😀

**Comment by 1tonsilla** [comment]
> 上述的应该并非引起此问题的原因。
> 
> 我这边也发现出现此问题，并经过如下尝试解决了无法显示的问题。
> 
> ### 步骤
> 1. 打开 简悦选项页 - 插件管理，卸载 `Assistive Touch` 插件
> 2. 重新安装 `Assistive Touch` 插件
> 3. 彻底关闭浏览器并重新打开
> 4. 在任意文章页进入阅读模式，查看是否有显示
> 
> 我刚出去一趟，没来得及发这个，回来你已经解决了哈
> 
> 另，上边第二张是根据报错信息定位简悦代码中的位置，你可以忽略

我更彻底啦，给配置文件都清除了，谢谢啦~又见一枚大佬 嘿嘿

**Comment by 1tonsilla** [comment]
> @1tonsilla
> 抱歉，你之前给我的截图里面的报错信息是包含了简悦的报错内容，我看漏了... 😅
> 
> 一般来说，造成这个问题的可能是插件的配置文件出现了问题，不知道你能否再次复现这个错误，否则先暂时不动这个地方了。
> 
> @binsee 谢谢提示。 😀

没事没事~谢谢你们两个大佬 😜
