### ISSUE TITLE
部分CSDN博客标题无法显示

### ISSUE THREAD

**Issue by dreacter** [Kenshin/simpread#127]
http://blog.csdn.net/chinaczy/article/details/5890768
似乎这个版式的CSDN标题为“csdn_top”，而不是规则中的“link_title”。

**Comment by Kenshin** [comment]
可以更改标题的获取（通过设定打开）

**Comment by Kenshin** [comment]
刚看了下，不清楚是否是因为模版改变导致的，解决办法：

- 将 `<span class='link_title'>` 改为 `<h1 class="csdn_top">`
- 将 `<span class='link_title'>` 改为 `<title>` 

第二种办法会获取当前页面的 `<title>` ，一劳永逸的方式。

**Comment by dreacter** [comment]
CSDN正在改版，详见：
http://blog.csdn.net/blogdevteam/article/details/78005911
目前处于过渡期，新老版式并存，“csdn_top”为新版的标题。
等正式改版后再来告知你吧。

**Comment by Kenshin** [comment]
好，在此期间可以用 `<title>`
