### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by yeahsbaby** [Kenshin/simpread#1271]
发生问题的地址: <https://www.toutiao.com/i6883092579194241550/?tt_from=dingtalk

**Comment by Kenshin** [comment]
谢谢反馈。

目前导入到印象笔记确实有些问题，我先记下来。

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
