### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by brizer** [Kenshin/simpread#1274]
发生问题的地址: <https://note.youdao.com/ynoteshare1/index.html?id=532da6c05500c6c0e272b106e8238db6

**Comment by Kenshin** [comment]
简悦无法识别 iframe 中的内容，而且这个页面也是优化过的，所以暂时不支持这类站点。

**Comment by Kenshin** [comment]
没有疑问的话，请关闭这个 Issues 😃

**Comment by brizer** [comment]
OK
