### ISSUE TITLE
高级账户“此密钥已被使用”无法激活

### ISSUE THREAD

**Issue by Jagerx** [Kenshin/simpread#1276]
通过少数派购买

重装系统，重新在EDGE中安装好插件后，注册激活码就激活不了。同样也是浏览器插件Smooth Gestures同步好以后激活码都自动同步好了，都不需要再手动激活！

浏览器登录账号与购买激活时一致
EDGE版本86.0.622.48

**Comment by Jagerx** [comment]
标识部分只读，https://simpread.pro/reset找回的UID也没法替换再激活

**Comment by Kenshin** [comment]
标识可以通过双击的方式全选后 crtl c 复制。

**Comment by Jagerx** [comment]
照着一步一步  导出配置又导入，UID倒是恢复了，再激活又提示“一个账户仅能绑定一个密钥”

本来并用不上所谓的高级账户标注和随后读，付费一则不贵，二则支持。CHROME插件付费的不止您这一个，但是整的最复杂的也就仅此一个

建议可以参考一下Smooth Gestures的激活方式。解决插件同步自动激活问题前我且不激活了，图一简单，奈何玩了个蛋疼

**Comment by Kenshin** [comment]
我会参考下 Smooth Gestures 的做法，谢谢提示。

> 再激活又提示“一个账户仅能绑定一个密钥”还是失败

不要再次绑定，而是第四个 Card → 重新授权，下图所示

![image](https://user-images.githubusercontent.com/81074/96951871-09a6df80-1520-11eb-9075-1ab5bd26b842.png)
