### ISSUE TITLE
最近几天一打开Chrome就提示高级账户被锁定

### ISSUE THREAD

**Issue by AbnerZhang** [Kenshin/simpread#1277]
通过UID查看登录了3个设备，但我只在这台电脑上用过，而且无法查询到登录设备的IP等信息。是怎么一回事？

**Comment by Kenshin** [comment]
请问

1. 是否更改过分辨率或者多屏使用？
2. 是否在同一时间打开过不同的浏览并同时绑定简悦的高级账户功能？

另外，当然不会有 IP 地址了，简悦不会记录你的任何用户信息。

**Comment by AbnerZhang** [comment]
您好！
1、没有改分辨率，但有过多屏
2、没有不同的浏览器，只用在了Chrome上绑定

   我描述不正确，不是IP，就是类似evernote那样，可以看到登录设备的名称，这样可以自己简单排查是否为自己的设备登录。
   今天打开没有提示，目前还正常。回忆了下，因为每天都打开/关闭数次Chrome，具体什么时候会出现提示，没什么规律。另，是否跟翻墙有关系？

**Comment by Kenshin** [comment]
估计跟多屏（且开关浏览器）有关系，跟其它之类的都应该没关系。
请问多屏和单屏的时候，非外接显示器的分辨率是否一致？

> 今天打开没有提示，目前还正常

是因为你在当前的「环境下注册过简悦」（大致是这个意思），所以简悦识别正确。

> 类似evernote那样，可以看到登录设备的名称

因为不想收集用户隐私，所以目前没有此功能。
目前记录了登录时间，鼠标移动到设备名上面有时间显示。不过，可以 **考虑加入设备名的功能**。

另外，简悦的机制导致你的 UID 不会被盗用，盗用也没有任何意义，使用后就会被锁，而只有提供了购买凭证的人才能全部解锁。

**Comment by AbnerZhang** [comment]
您好，两台显示器分辨率的确不一致。这样的话，我尽量在一个显示器内使用一段时间看看

**Comment by Kenshin** [comment]
下个版本会解决多开浏览器（但未使用简悦高级账户功能）的误判问题。
这样你的这种情况会减少很多。
