### ISSUE TITLE
notion授权仅能获取到第一个页面,请问是我用的不对吗?

### ISSUE THREAD

**Issue by MarvinLong** [Kenshin/simpread#1288]
![image](https://user-images.githubusercontent.com/15308801/97552860-ba751900-1a0f-11eb-87a8-93583fb5912d.png)

**Comment by Kenshin** [comment]
简悦授权 Notion **使用了私有 API** 如果你的 Page 之类设置的比较奇怪会存在一定机率的失败，一旦发生后这种问题后，会强制设置为第一个 Page。

**Comment by MarvinLong** [comment]
我用 save to notion 能够检测到我的数据类型的. 
我的第一页确实可能奇怪, 包含了很多table. 不知道是不是第一页就识别错误了.

**Comment by Kenshin** [comment]
`Save to notion` 是官方插件，所以自然没有问题的。 😅 （ 谁怪 Notion 一直没有 API 呢...

***

> 我的第一页确实可能奇怪, 包含了很多table. 不知道是不是第一页就识别错误了.

确有可能...

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4
