### ISSUE TITLE
阅读模式部分文本缺失

### ISSUE THREAD

**Issue by sunboling** [Kenshin/simpread#1289]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://blog.csdn.net/fuliangliang/article/details/524250?fps=1

**Comment by Kenshin** [comment]
谢谢反馈，这个应该是代码高亮插件造成的，我先记录到 #500 （ 同一类似的 Issues 仅开一个，修复后我会在这里通知你。
