### ISSUE TITLE
微信订阅号的样式需要优化

### ISSUE THREAD

**Issue by areyouok1** [Kenshin/simpread#1291]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s?src=11

**Comment by Kenshin** [comment]
请提供完成的 URL
