### ISSUE TITLE
关于简悦导出功能的建议

### ISSUE THREAD

**Issue by tianchenmao** [Kenshin/simpread#1292]
- 目前简悦导出pdf使用的是浏览器自带的打印，效果不佳，但导出markdown效果良好。通过typora等软件把md转成pdf也能迂回地达到目的，但不太方便，希望简悦能提供体验更好的pdf导出功能。
- 另一方面，希望简悦未来能提供将带笔记的网页整个保存下来的功能已应对网址可能失效等潜在风险。

**Comment by Kenshin** [comment]
1. 会有更好的 PDF 方案。
2. 你可以使用 [离线 HTML](http://ksria.com/simpread/docs/#/%E7%A6%BB%E7%BA%BFHTML) 下载

 😄

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，详细 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=pdf)

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。

**Comment by g1021895463** [comment]
对基于Email导出文章相关功能的两个建议：

1.发送至邮箱中的内容中也许可以免去“简 悦「如杂志般沉浸式」的阅读体验”这一标识？
![图片](https://user-images.githubusercontent.com/48684308/147931981-41050cc9-37fd-4b9a-a6ac-965c27e19fdf.png)
在开头仅保留标题+分隔线，对于该文章来自简悦，这一事实的说明可以在文末表述：“本文由 简悦 SimpRead 转码，用以提升阅读体验，原文地址”
![图片](https://user-images.githubusercontent.com/48684308/147932215-5fe50604-b2ed-4192-8b4d-12710811afd8.png)

2.对于发送Email的功能希望可以提供更加强大的导出选项——导出时的可选项部分只会在使用保存到本地的功能时才会生效：例如导出离线HTML时会将标注和正文保存为两个文件，而发送Email则只会发送正文的部分。

![图片](https://user-images.githubusercontent.com/48684308/147932762-5d7858ae-ffaf-4f2e-80c0-f87dc1d81a21.png)
