### ISSUE TITLE
360doc 收藏图片到notion失败。。。

### ISSUE THREAD

**Issue by 1tonsilla** [Kenshin/simpread#1293]
http://www.360doc.com/content/19/0407/19/40717692_827040913.shtml

例如这个网址，另外一款webclipper也失败了。 
但是印象笔记完美收藏成功了，请查看咋回事。。

提示：

This image couldn't be loaded
_lean more_
image109.360doc.com

**Comment by Kenshin** [comment]
导入到 Notion 使用了私有 API 所以不是很稳定。

同时跟（导入到印象笔记）也没法比较，不同的服务，不同的 API。 😀
