### ISSUE TITLE
is:issue is:open 阅读模式

### ISSUE THREAD

**Issue by li19981001** [Kenshin/simpread#1294]

**Comment by Kenshin** [comment]
你想问什么？
因为是无意义的 Issues 我会关闭它，如你需要可以随时重开。

**Comment by li19981001** [comment]
我的阅读模式要么进不去，进不去的情况就是页面变白，进去了也没有办法进行翻页等一系列操作

**Comment by Kenshin** [comment]
1. 确保可以正常进入 `选项页`，如选项页打开后空白，请重装简悦。
2. 上步没问题的话，请在 **隐私模式下，仅启用简悦**，用来排除因为其它扩展造成的影响。

**Comment by li19981001** [comment]
> 1. 确保可以正常进入 `选项页`，如选项页打开后空白，请重装简悦。
> 2. 上步没问题的话，请在 **隐私模式下，仅启用简悦**，用来排除因为其它扩展造成的影响。

我并没有找到隐私模式啊，在`选线页`么？

**Comment by Kenshin** [comment]
Chrome 浏览器自带的 **无痕模式**，
同时设定 `chrome://extensions/?id=jgphnjokjhjlcnnajmfjlacjnjkhleah` 勾选 **在无痕模式下启用**
