### ISSUE TITLE
自定义删除元素功能是否在ROADMAP中, 大概什么时候会发布

### ISSUE THREAD

**Issue by jinxiaoye1987** [Kenshin/simpread#1299]
再覆盖重写 css 全的网站, 偶尔也会有些许元素不想保存, 是否能像之前用的 Reader Mode Pro 一样, 提供 Delete Element 方法, 开启该模式开关后, 鼠标所选元素可以手动删除;

**Comment by jinxiaoye1987** [comment]
已找到 [动作]->[隐藏任意元素]

**Comment by Kenshin** [comment]
嗨，谢谢「自救成功」 😀
