### ISSUE TITLE
设置界面导航的颜色问题

### ISSUE THREAD

**Issue by JokerQyou** [Kenshin/simpread#13]
从设置界面点击“帮助”后会跳转到 Github 的 wiki 页面，这时返回扩展的设置界面，导航栏会出现如下现象。
点击“帮助”两字偏下的位置可以重现。
![image](https://user-images.githubusercontent.com/1465267/27168377-fa61a6ea-51d7-11e7-837a-81a76974f0d9.png)

**Comment by Kenshin** [comment]
我遇到过这个情况，但一直没办法稳定重现... 按照你说的方式，也是偶尔会发生，但估计可以捕捉到。

**Comment by airycanon** [comment]
这个问题我找到原因了，要不我来发个 PR？

**Comment by Kenshin** [comment]
okay，没问题~
