### ISSUE TITLE
少数派和

### ISSUE THREAD

**Issue by willie91** [Kenshin/simpread#1300]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
windows
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
版本 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
- 简悦版本 **2.0.0**
2.0
- 发生问题的地址 <请填写你的地址l>
https://sspai.com/post/63410
**请描述你的问题**
少数派进入阅读模式整个页面就会变得非常卡几乎不可滑动，退出就正常，两台电脑都这样
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
有可能是跟其它扩展冲突导致的，你可以试试 `在隐私模式下，仅启用简悦` 来排查。

**Comment by willie91** [comment]
> 有可能是跟其他扩展冲突导致的，你可以试试`在隐私模式下，仅启用简悦`来排查。

找到了，跟SmoothScroll冲突

**Comment by Kenshin** [comment]
👌

一般都是跟 TOC 类的插件有冲突，你可以在简悦中关闭目录功能，看看能否改善。或者单独使用简悦的目录功能。
