### ISSUE TITLE
简悦 · 插件中心 无法导入配置文件

### ISSUE THREAD

**Issue by 9k01** [Kenshin/simpread#1301]
https://simpread.ksria.cn/plugins/editor/

请求 URL: https://simpread.ksria.cn/users/service/get/iwtarzxg-vc7f-0p53-0s9z-4o9olorwrdhu
{"code":-1,"data":null}

**Comment by Kenshin** [comment]
此功能暂时不对外开放。😅
你有新插件想要开发？

**Comment by 9k01** [comment]
@Kenshin 是啊，有一些自己添加了些功能，是通过修改插件源码做到的，但是这样就错过了更新
“增强解析”的排版的有点太严重了（过滤掉了原本作者的颜色、加粗、斜体），不过滤又达不到想要的效果
建议过滤可以统一字体大小，原来的版式可选择保留（颜色、加粗、斜体）

**Comment by Kenshin** [comment]
>  通过修改插件源码做到的

你是说简悦扩展？还是简悦的某个插件？

如果是前者的话，跟插件编辑器无关。反之后者的话，你可以告诉我是哪个插件？

***

> 过滤掉了原本作者的颜色、加粗、斜体

这些当然是要过滤掉的，否则跟没有使用阅读模式没有区别了。 😅  
从另外个角度说，确实有些样式/颜色是正确的，但也有些是错误的，所以只能全部都过滤掉，更何况前者发生的情况很少。

**Comment by 9k01** [comment]
不好意思用词不准确，我是下载http://ksria.com/simpread/crx/2.0.0/simpread.zip，修改了里面的js实现了某些功能（小众需求：渲染后<body>标签清空，无关css清空，方便我CTRL+S保存到本地）

**Comment by Kenshin** [comment]
如果是这样的话，你自己使用就可以了，不需要提交。

***

> 不过，提示下

简悦 1.0 是开源的， 所以你可以随意使用，留意 [LICENSE](https://github.com/Kenshin/simpread/blob/master/LICENSE) 就可以了。

简悦 2.0 是闭源项目。

没有问题的话，请关闭这个 Issues  😀
