### ISSUE TITLE
百度贴吧广告干扰

### ISSUE THREAD

**Issue by tearslee** [Kenshin/simpread#131]
额,如果开启简阅是没有广告的(似乎是因为我使用了插件),简约开启后反而有了广告

**Comment by tearslee** [comment]
![Uploading TIM截图20171012180948.png…]()

**Comment by Kenshin** [comment]
可以通过 【设定 → 隐藏列表】 把不想显示的内容加入到此，即可不再显示了。_但需要有些编程的知识。_

贴吧应该已经加入了一些默认的隐藏列表，我刚刚试了下，没问题... 或许是你说的其它扩展导致的。

如果无法自行添加的话，请告知 url ，看看到底是什么问题...

**Comment by Kenshin** [comment]
@tearslee 
我看你似乎传了张图片？然后在这里并没有看到... 你又删除了？
