### ISSUE TITLE
文章保存到Joplin失败

### ISSUE THREAD

**Issue by ltop2013** [Kenshin/simpread#1311]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Microsoft Edge 86.0.622.58**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://blog.csdn.net/qq_37960324/article/details/101302172>

**请描述你的问题**
按照指引，已经做好joplin的配置，但是保存到joplin失败
**截图**
![image](https://user-images.githubusercontent.com/6017920/98191031-4c6eab80-1f53-11eb-9103-97f75bdf62f4.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，我刚测试了下应该没有问题，请问你在 Joplin 能看到 **SimpRead** 文件夹吗？

**Comment by ltop2013** [comment]
非常感谢您的回复，在 Joplin 我之前是建了 SimpRead 文件夹的，但是还是同步不过来。以下是我的相关截图
![image](https://user-images.githubusercontent.com/6017920/98321723-c28d1400-2020-11eb-9481-4b5a92e84895.png)

**Comment by ltop2013** [comment]
![image](https://user-images.githubusercontent.com/6017920/98321765-d769a780-2020-11eb-809f-37035b00f77b.png)

**Comment by Kenshin** [comment]
比较奇怪的问题，我反复测试了应该是没有问题的。

***

你也可以这样测试。

1. 删除你在 Joplin 的文件夹。
2.简悦 → 选项页 → 授权 Joplin → 粘贴 Token 后
3. 点击 **验证并绑定 Joplin 的信息**
4. 看看 Joplin 里面是否会自动新建了 SimpRead 文件夹

***

另外，用浏览器访问 http://localhost:41184/ 看看有什么提示？或者说你的系统是否安装了某些 防火墙/广告过滤之类的工具？

**Comment by ltop2013** [comment]
我按照上面的步骤操作了，没有建立SimpRead 文件夹
浏览器访问41184端口是不通的，系统自己开启防火墙了，没有安装其他防火墙或者广告过滤工具

那这个问题是因为我41184端口没有开启么？

**Comment by Kenshin** [comment]
> 浏览器访问41184端口是不通的

浏览器无法访问吗？如果是的话，请确保 41184 畅通。 😀  （ 估计是这个问题造成的

**Comment by ltop2013** [comment]
非常抱歉又得麻烦下。我这系统是mac os 10.15，网上指定端口开放的教程都是老版mac os系统。您有指定41184端口开放的方法么？另：我试了试把系统防火墙关闭，也是无法将文章保存到joplin

**Comment by Kenshin** [comment]
试试 `lsof -i tcp:41184` 看看控制台输出什么内容？

没有内容输出则这个端口号未被占用，反之看看是哪个应用占用了。

**Comment by ltop2013** [comment]
这个命令输过之后，没有任何内容，没有被占用

**Comment by Kenshin** [comment]
emmm

输入 http://localhost:41184/ 后把结果截图给我看下。

**Comment by ltop2013** [comment]
这个是输入http://localhost:41184/的截图
![image](https://user-images.githubusercontent.com/6017920/98507984-9e883780-2299-11eb-8f10-040dee3bb075.png)
还有如果我持续点击joplin按钮，就会出现开始保存信息，会转很久，如下图
![image](https://user-images.githubusercontent.com/6017920/98508132-ead37780-2299-11eb-9711-457bbb7ee1e4.png)

**Comment by ltop2013** [comment]
显示图挂了，不知道这个行不行
<img width="421" alt="WX20201109-144653@2x" src="https://user-images.githubusercontent.com/6017920/98508456-7816cc00-229a-11eb-8ca2-bbfbdbbae6c5.png">

**Comment by Kenshin** [comment]
这就是无法访问 http://localhost:41184 的截图。
但确实你的 41184 端口没被占用…

建议你去问问用 Joplin 的朋友。

**Comment by ltop2013** [comment]
您好，我问了一下其他用mac的朋友，他们表示 http://localhost:41184 无法访问。我网上也查了一下，特意再咨询下，您是不是开启了mac的apache服务呢？多谢

**Comment by Kenshin** [comment]
@ltop2013 

能访问 http://localhost:41184/ 的前提是 **你的朋友也需要安装 Joplin**，访问这个地址后，会在浏览器里面有下面的截图内容

![image](https://user-images.githubusercontent.com/81074/99472938-978db300-2984-11eb-863f-03c80c82e0f8.png)

所以，我确实不太清楚你在 Mac 上是如何配置 Joplin （比如我仅安装了它，但从未使用过，默认就可以访问。

***

还有个方式，Joplin 自带了一个扩展，你安装它的试试，看能否成功导入到 Joplin ？

**Comment by ltop2013** [comment]
困扰我这么久的问题终于解决了，原因我我没有开启joplin的剪切服务。刚才您说到“Joplin 自带了一个扩展，安装一下试试”。准备安装的时候，看见了41184，才意识到自己应该开启剪切服务！开启之后可以顺利剪藏了，多谢。
![image](https://user-images.githubusercontent.com/6017920/99474215-23a0da00-2987-11eb-8bd8-11bbe53756d4.png)
看了下简悦文档，没有开启这个服务的步骤，可能也会卡很多我这样的小白，建议文档里加上这个步骤。
再次感谢您耐心的回复，祝好！

**Comment by Kenshin** [comment]
我的天... 终于解决了。

不过... 为什么我在安装 Joplin 后没有做任何配置就可以使用呢？ 😅 

没问题的话，我关闭这个 Issues 了。

**Comment by sumulige** [comment]
> 困扰我这么久的问题终于解决了，原因我我没有开启joplin的剪切服务。刚才您说到“Joplin 自带了一个扩展，安装一下试试”。准备安装的时候，看见了41184，才意识到自己应该开启剪切服务！开启之后可以顺利剪藏了，多谢。 ![image](https://user-images.githubusercontent.com/6017920/99474215-23a0da00-2987-11eb-8bd8-11bbe53756d4.png) 看了下简悦文档，没有开启这个服务的步骤，可能也会卡很多我这样的小白，建议文档里加上这个步骤。 再次感谢您耐心的回复，祝好！

好人一生平安 谢谢你
