### ISSUE TITLE
导出到Kindle功能

### ISSUE THREAD

**Issue by Diluo001** [Kenshin/simpread#1315]
导出到Kindle,每月仅仅只有30次.有一点太少了.还有其他更多次数的解决办法吗?

**Comment by Diluo001** [comment]
如果是完整的书的话, 30次肯定够用了. 但是文章,30次就太少了.
假如增加不了太多次数的话,还有特别好的,用kindle阅读的办法吗? 导出epub. kindle 也不支持这个格式. 在去转换的话,就太麻烦了.还不如直接电脑看完了.

**Comment by Kenshin** [comment]
导出到 Kindle 使用了第三方服务，之前都是免费的，目前这个服务有次数限制了吗？

**Comment by Diluo001** [comment]
29 / 30 credits left this month 
我发送到了Kindle一次了.所以是29. 这个功能真的是特别好. 适合慢慢看那种长文.

**Comment by Diluo001** [comment]
这个功能好像也不太好用. 太长的文章, 发送到Kindle. 只发送了一部分而已. 就拿知乎的一篇帖子来说,他发送了4分之一. 
好像也没啥作用. 太短了.

不好意思,我才购买和使用,这个简悦不久. 还不太了解全部特性.

**Comment by Kenshin** [comment]
了解...

我想想办法。

**Comment by singurren** [comment]
你好，今天更新简阅发现了简悦 · 同步助手，安装并且尝试了导出到kindle
目前配置如下
![Snipaste_2020-11-23_22-04-30.png](http://ww1.sinaimg.cn/large/006DkSiDly1gkzgmecgv9j31790jwtax.jpg)
两个问题，一是我就只想导出到kindle，但是同步助手要求必须有一个接收邮箱，这个有点不爽，现在两个邮箱设置成了一样了，二就是这样设置完之后，在聚焦页面还是没有动作-导出到kindle
![Snipaste_2020-11-23_22-10-44.png](http://ww1.sinaimg.cn/large/006DkSiDly1gkzgo4lf25j31090kbwqw.jpg)
请确认，谢谢～

**Comment by Kenshin** [comment]
> 一是我就只想导出到kindle，但是同步助手要求必须有一个接收邮箱

因为这个功能使用了你的邮箱，而非服务端的邮箱，这么做的原因是：你可以理解 **同步助手** 是一个专属你自己的服务中心。

****

> 二就是这样设置完之后，在聚焦页面还是没有动作-导出到kindle

明天确认下。

**Comment by feiyu517** [comment]
[我也是经常用简悦发送长文到kindle上慢慢阅读.之前用简悦1.0都正常发送.升级到2.2.0之后,每次发送都弹出错误提示框?请问如何解决?错误如下所示.
嗨，因为你使用了同步助手的自动同步功能，
但并未运行同步助手客户端，才会有此提示 请看这里。

你可以选择以下几个方案：
1．运行 同步助手后 刷新此页面。
2．关闭增强导出选项，点击右侧 关闭选项。
3．选择右侧 忽略，下次再说。

**Comment by Kenshin** [comment]
@feiyu517 

嗨，简单的说明下：

- 1.x 时使用的是**第三方服务**，之前是是免费的，现在有每月30次的限制。

- 2.x 时使用的是**简悦自己的方案**，但属于高级账户功能，如何配置 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=%e5%8f%91%e9%80%81%e5%88%b0kindle)

你提到的提示说明：

> 你选用了**简悦自己的方案，但是没有运行同步助手**

至于，什么是同步助手的话，可以 [看这里](http://ksria.com/simpread/docs/#/Sync)

如果你是基础账户，并且使用第三方服务的话，请关闭下面的选项，位置在：选项页 → 服务

![image](https://user-images.githubusercontent.com/81074/124690412-be492b80-df0c-11eb-89bd-8ce163116651.png)

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
