### ISSUE TITLE
无法自动进入聚焦模式

### ISSUE THREAD

**Issue by Nickszy** [Kenshin/simpread#1319]
虽然在设置中关闭了手动聚焦模式，但发现很多网站依旧无法自动打开聚焦模式。比如在掘金可以自动进入阅读模式，但无法自动进入聚焦模式。

请问是否可以设置白名单之类的，在某些网站自动激活聚焦模式呢？

相比较于阅读模式，我更喜欢聚焦模式，希望能将更多的功能从阅读模式迁移到聚焦模式中。

![image](https://user-images.githubusercontent.com/29924966/98427549-992fbf00-20d8-11eb-868c-b521f213c138.png)

**Comment by Kenshin** [comment]
嗨，目前暂时没有 `自动进入聚焦模式` 的功能。

会考虑下下个版本实现。（已经优化右上角触发器的点击事件

**Comment by Undefinedefity** [comment]
赞同@Nickszy 的说法，希望能多关注下“聚焦模式”，因为此模式在更能专注于内容的同时还可以看到相关推荐（比如CSDN旁边的推荐阅读），以及能够实现页内超链接跳转（CSDN里面）

**Comment by Kenshin** [comment]
@Undefinedefity 

嗨，谢谢建议，非常会考虑的。 😀 

> 能够实现页内超链接跳转（CSDN里面）

在 `阅读模式` 的话，可以通过插件插件实现；聚焦模式的初衷是尽量不改变原页面的内容/结构，所以无法在聚焦模式下使用插件。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
