### ISSUE TITLE
不支持阅读模式

### ISSUE THREAD

**Issue by fengkx** [Kenshin/simpread#132]
http://theory.people.com.cn/n/2013/0417/c40537-21165891.html

**Comment by Kenshin** [comment]
感谢反馈~
先记下来，适配后会通知你。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)
