### ISSUE TITLE
英文引号解析后有一大个空格

### ISSUE THREAD

**Issue by ky-huang** [Kenshin/simpread#1321]
如图，引号后面有一大个空格，看起来很奇怪。。剪藏到印象笔记之后也是这样

<img width="434" alt="Snipaste_2020-11-07_23-27-49" src="https://user-images.githubusercontent.com/60381489/98445128-f5362a00-2150-11eb-998d-51757597eb09.png">
<img width="689" alt="Snipaste_2020-11-07_23-26-55" src="https://user-images.githubusercontent.com/60381489/98445136-fd8e6500-2150-11eb-9530-de227cae00c3.png">

希望能优化一下。。逼死强迫症

**Comment by Kenshin** [comment]
谢谢反馈。

英文页面确实有些问题，我会出一个插件来解决这个问题。

**Comment by Kenshin** [comment]
嗨，这个问题解决了，你可以安装 [英文阅读版面辅助增强](https://github.com/Kenshin/simpread/issues/2840)。

![image](https://user-images.githubusercontent.com/81074/133365550-ba9d9bd6-3d27-4524-8af4-984e48e7387a.png)

> 同时也可以使用下面两个跟英文阅读有关系的内容：

- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H)

- [适配扇贝阅读的适配站点](https://github.com/Kenshin/simpread/discussions/2705)

***

我将关闭这个 issues，有任何问题随时在这里联络我。
