### ISSUE TITLE
微信公众号文章保存到印象笔记总是失败

### ISSUE THREAD

**Issue by gita123456** [Kenshin/simpread#1323]

**Comment by Kenshin** [comment]
谢谢反馈，导入到印象笔记确实有些问题，细节 [请看这里](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1-FAQ?id=%e5%8d%b0%e8%b1%a1%e7%ac%94%e8%ae%b0%e4%bf%9d%e5%ad%98%e5%a4%b1%e8%b4%a5)

**Comment by gita123456** [comment]
还有其他的解决方案吗，给出的解决方案很麻烦

**Comment by Kenshin** [comment]
有个解决方案，但不知道是否可以完美解决。
到时候会在这里通知你。

**Comment by gita123456** [comment]
大概什么时间可以解决？等了很久了


发自我的&nbsp;iPad

------------------ 原始邮件 ------------------
发件人: Kenshin Wang <notifications@github.com&gt;
发送时间: 2020年11月9日 10:50
收件人: Kenshin/simpread <simpread@noreply.github.com&gt;
抄送: gita123456 <365880536@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Kenshin/simpread] 微信公众号文章保存到印象笔记总是失败 (#1323)





 
有个解决方案，但不知道是否可以完美解决。
 到时候会在这里通知你。

**Comment by Kenshin** [comment]
嗨，目前没有时间表。

首先：并不是每个页面都这样 [比如我随便找了一篇就没问题 ](https://mp.weixin.qq.com/s?__biz=MjM5NTA5MzA3NQ==&mid=2654878331&idx=1&sn=195c3f35494e941c9603571be8ae6d6d&chksm=bd3755478a40dc516a37da35438d1a19063233798e5f8545dacf0e6138821e4b25a891ba798a)，只是个别页面，具体是什么原因，我在 https://github.com/Kenshin/simpread/issues/1323#issuecomment-723542036 已经说明了。

其次：这个是老问题，你可以翻翻 https://github.com/Kenshin/simpread/labels/evernote 里面有多少个。

为什么没有解决，我也说过了，这是 **印象笔记本身文档的问题**，暂时还没有找到一个好办法解决它。

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
