### ISSUE TITLE
希望左下角小圆点点击打开，点其他地方关闭，而不是鼠标没有悬停就关闭

### ISSUE THREAD

**Issue by uoox** [Kenshin/simpread#133]
希望左下角小圆点点击打开，点其他地方关闭，而不是鼠标没有悬停就关闭。

鼠标很容易离开小部件。

**Comment by Kenshin** [comment]
感谢反馈~
的确对于一些人有这样的困扰，已经下个版本会改善此功能。

预计会加入一个选项：【鼠标悬停/点击】关闭。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了 控制栏太灵活 这个问题，此 issues 关闭。
同时，新增 一个叫做 `FAP` 的功能，可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
