### ISSUE TITLE
帮忙适配http://www.wowotech.net

### ISSUE THREAD

**Issue by nextcoffee** [Kenshin/simpread#134]
例如网页：[http://www.wowotech.net/x_project/kernel_gpio_driver_porting_2.html](http://www.wowotech.net/x_project/kernel_gpio_driver_porting_2.html)

**Comment by Kenshin** [comment]
okay 适配完会通知你。  😃

**Comment by Kenshin** [comment]
这个博客是你的吗？如果是的话，简悦 `1.0.4` 已发布，将关闭 issues 。

增加了 `主动适配阅读模式` 的功能，你可以通过配置使其主动支持阅读模式，详细请看 [主动适配阅读模式](https://github.com/Kenshin/simpread/wiki/主动适配阅读模式)
