### ISSUE TITLE
发送到onenote显示成功，但打开OneNote没显示新增

### ISSUE THREAD

**Issue by shijie159** [Kenshin/simpread#1344]

**Comment by shijie159** [comment]
1、onenote2016会显示在我的笔记本-快速笔记里，不能自定义保存位置
2、OneNote for win10不显示，只有OneNote2016能找到

**Comment by Kenshin** [comment]
Onenote 确实是保存到 快速笔记里面。
我在 Web 端测试没问题。

你说的是客户端吧？
无法保存的里面有快速笔记吗？

**Comment by shijie159** [comment]
嗯嗯，又看了下能推送到，只是有延迟，软件端能直接推送到，onenote for win10有延迟

**Comment by Kenshin** [comment]
如果是 Desktop App 的话，延迟应该属于正常现象的。
比较它的数据需要从服务端下载，同时也不可能实时下载。

没问题的话，我关闭这个 Issues 了。 😀
