### ISSUE TITLE
微信公众号文章图不显示？

### ISSUE THREAD

**Issue by firstuanl** [Kenshin/simpread#1346]
RT

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
应该不会出现这个问题。
你在隐身模式下，仅启用简悦试试。

**Comment by firstuanl** [comment]
用header editor解决了，
碰到的问题是公众号文章保存本地后用简阅出现图盗连。

**Comment by Kenshin** [comment]
你可以使用 离线 HTML 不仅防盗链，还防 404
