### ISSUE TITLE
关于新设备授权的疑问

### ISSUE THREAD

**Issue by jiangyi0222** [Kenshin/simpread#1347]
设备A（黑屏果）已经刷回Win10（设备B），没有同步过配置文件，有购买证明，lisence，UID，请问如何在Win10 chrome恢复高级账户？

**Comment by Kenshin** [comment]
用配置文件就可以授权设备 B
你丢失了配置文件吗？（内含 UID）
如果丢失的话，可以使用 https://simpread.pro/reset 找回。

另外，也请留意下https://simpread.pro/help 里面高级账户的相关说明。

**Comment by jiangyi0222** [comment]
> 用配置文件就可以授权设备 B
> 你丢失了配置文件吗？（内含 UID）
> 如果丢失的话，可以使用 https://simpread.pro/reset 找回。
> 
> 另外，也请留意下https://simpread.pro/help 里面高级账户的相关说明。


感谢回复！我在提问前尽力地阅读了文档，不过没有找到解决的办法，所以来提issue
在之前的设备上（MacOS chrome）我没有同步过配置文件，所以丢了 ..
现在我已经获取了UID，只不过仍不知道如何使用UID将我现在的（B win10设备chrome）转换为高级账户。

**Comment by Kenshin** [comment]
如果你已经找回了 UID 后，请使用下面的方式：

1. 下载简悦的配置文件

2. 用任意文本文件打开

3. 找到 "uid" 并替换对你已经找回的 UID

4. 在通过简悦导入第三步的配置文件

5. 重新授权

***

下个版本将会把上面的步骤变为一步操作，并内置了 https://simpread.pro/reset

**Comment by jiangyi0222** [comment]
多谢 问题已经解决  简约日常帮助了我很多 很方便 希望越做越好！

**Comment by Kenshin** [comment]
谢谢，搞定就好。
新版会有更方便的登陆/授权方式。
