### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by cfwing** [Kenshin/simpread#1349]
发生问题的地址: <http://yuedu.163.com/book_reader/0fa853e5a3f0448aa33deff8c871ae0e_4>

**Comment by Kenshin** [comment]
嗨，这类「电子书」类的 Reader 将不会被适配，原因：

1. 这类页面的布局已经很好了。
2. 因为涉及到版权。

所以我关闭这个 Issues 了。 😀
