### ISSUE TITLE
simpRead对vimum插件不友好，无法显示链接的内容

### ISSUE THREAD

**Issue by rainplus** [Kenshin/simpread#135]

**Comment by Kenshin** [comment]
的确如此，建议使用 `Surfingkeys` 基本上完美支持 `简悦` 功能上与 vimum  几乎一样。

**Comment by rainplus** [comment]
@Kenshin 下载了。但是习惯了vimum好不习惯啊。。

**Comment by Kenshin** [comment]
我用着还行，话说 Surfingkeys 不会修改 new tab ...

**Comment by rainplus** [comment]
@Kenshin 不是啊，我这边的newtab 变成了Surfingkeys的说明。。

**Comment by Kenshin** [comment]
额，这就奇怪了...

**Comment by klmsj** [comment]
也和cvim冲突

**Comment by Kenshin** [comment]
@klmsj 
是这样的，只要是监听 `<body>` 下面的快捷键操作扩展都会有影响。

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布！

新增加了键盘操作，其中有类似你这样需求的功能，主要是增加了 `f` 键的功能，详细请看 http://ksria.com/simpread/welcome/version_1.0.5.html#keyboard

此 issues 将会关闭。
