### ISSUE TITLE
高级账号锁定问题

### ISSUE THREAD

**Issue by liuyu226** [Kenshin/simpread#1351]
在家中和公司电脑上都绑定了高级账号，确定至有2台电脑绑定，但是因为工作关系，需要经常google一些资料，所以用了一些你懂的方法，然后晚上家中电脑突然弹出说绑定过多，需要退出账号或联系管理员，今天到公司电脑上查看发现绑定了3台电脑，但是我确定是只绑定了2台，所以想问下是绑定是不是还检查了 IP 之类的，这种情况有什么办法解决吗？

**Comment by Kenshin** [comment]
1. 是否在 `同一台设备上使用两个浏览器，并登陆了高级账户？`

2. 是否使用了 `外接显示器` 的设备上登陆了高级账户？

3. 是否曾经在授权设备上更改过分辨率？

***

如果是 **问题1** 的话，这个是 Bug 已经解决了，下个版本发布。

其余的情况请回复我  😀

**Comment by liuyu226** [comment]
1. 同一台设备只使用了 chrome 并绑定高级账户，但有时 chrome 新标签会被误拖拽变成新浏览器窗口；
2. 公司：一台主机+2显示器，WIN10+Chrome； 家：一台MBP,  Chrome
3. 确定分辨率没有调整过
附： ip 地址确实经常变化

**Comment by Kenshin** [comment]
> 公司：一台主机+2显示器，WIN10+Chrome； 家：一台MBP, Chrome

多显示器环境下，也使用了高级账户吗？如果是的话，可能是这个问题，因为多显示会有一定的误判，毕竟硬件环境变化了。

**Comment by liuyu226** [comment]
公司用的电脑是使用了2台显示器，并在 Chrome 上绑定了高级账户，多嘴问一下：这种情况不是应该只判断主机的硬件吗？和显示器也有关系？

**Comment by Kenshin** [comment]
> 多嘴问一下：这种情况不是应该只判断主机的硬件吗？和显示器也有关系？

判断的方式确实以硬件为准，但偶尔会出现偏差。（ 我会改善这个问题）

***

> 我在公司查看账户，发现高级账户正常，没有锁定，但是家里一直提示我异常，

**高级账户正常，没有锁定** 这种情况也是正常的，但不代表不会被锁定。

关于你的问题，其实反馈的描述比较少，简单的说，被锁定有两种情况：

1. 超过三台设备

2. 在不同的设备上同时登录高级账户。

你可以在 http://simpread.pro/account 查看你的账户情况，也可以截图给我（截图时请不包含 UID 等敏感信息

***

最后，谢谢你的耐心反馈，并不是每个遇到类似问题的用户都有这么好的心态。❤ （ 虽然 99% 的情况都是因为没有仔细阅读造成的...  😅

**Comment by liuyu226** [comment]
没事，我不急，能找到问题就好，作者辛苦，66666
![image](https://user-images.githubusercontent.com/26989811/99354462-73c56100-28e1-11eb-82de-dda99481db50.png)

**Comment by Kenshin** [comment]
看截图应该属于 **超过三台授权设备** 造成的。

你可以选择 **解绑全部设备**，然后在有多显示器的设备上，**重新授权** 高级账户就可以了。
不过，请留意：暂时不要在多个显示器的设备上授权多个浏览器（这个问题会在下个版本发布后自行解决）

然后在家的那台设备也需要 **重新授权** 。

***

最后，再登录这个地址，看看你的授权设备是几台。

**Comment by liuyu226** [comment]
收到，感谢作者耐心解答！

**Comment by Kenshin** [comment]
没事，因为多显示器的问题也给你带来了一些困扰。 😉
