### ISSUE TITLE
请支持wolai的剪切

### ISSUE THREAD

**Issue by 1tonsilla** [Kenshin/simpread#1355]
wolai是一款模仿notion的本土化笔记
我本来用notion，可是网速真的太卡了，导致体验一言难尽

希望simpread能支持下...web clipper已经支持了...毕竟买过simpread会员，不打算换成别的插件..希望大大有空开发下，谢谢~

**Comment by Kenshin** [comment]
谢谢购买高级账户。👍

我个人对这种 copy 类的产品没好感！

导出功能是 1.x 就有的功能，也是免费使用，并未在高级账户的功能里面。

不过，从技术角度看，等它有了公开 API 后，我可以考虑加上。
目前没有公开 API 我是不会加的，因为「坑很多」。

所以，等它有了 API 在通知我。 😃

**Comment by 1tonsilla** [comment]
好的..谢谢..
明白的，这种copy确实挺让人烦的，这两天fq加上修改DNS我这边notion速度还是很慢，太捉急了，所以才用这个，以后我看看多花点钱，买好点的服务器fq..哎

**Comment by Kenshin** [comment]
嗨，谢谢理解。 😊 
如果你继续使用它的话，等出了 API 请通知我，我会适配的。

PS：Notion 的慢也确实有些「烦人」。

**Comment by q030p** [comment]
我看帖子是2020年的，三年后的今天，我是否机会看到增加wolai的剪切功能（泪汪汪+双手合十.jpg）
  我是不懂这方面的路人（不知道上面描述的api是啥，如果打扰到了，其他说不好意思）

**Comment by Kenshin** [comment]
@q030p 

> （不知道上面描述的api是啥，如果打扰到了，其他说不好意思）

哈， 小事情，只要是用户任何形式的提问我都会回复。

PS：看下 Issues 已经积累了 5K+  的回复。

PPS：你可以使用复制 Markdown 到剪切板「间接」实现，也没有太大的麻烦。

**Comment by q030p** [comment]
好的，非常感谢！♥



在 2023-10-26 11:23:12，"Kenshin Wang" ***@***.***> 写道：

@q030p

（不知道上面描述的api是啥，如果打扰到了，其他说不好意思）

哈， 小事情，只要是用户任何形式的提问我都会回复。

PS：看下 Issues 已经积累了 5K+ 的回复。

PPS：你可以使用复制 Markdown 到剪切板「间接」实现，也没有太大的麻烦。
