### ISSUE TITLE
代码段增强插件报错

### ISSUE THREAD

**Issue by asukaliy1** [Kenshin/simpread#1358]
加载页面：https://www.cnblogs.com/aspirant/p/8991830.html

报错信息
![image](https://user-images.githubusercontent.com/26673975/99370458-a9c20f80-28f8-11eb-9a24-cf5f25b7c109.png)

**Comment by Kenshin** [comment]
谢谢反馈。

我会把这些相似的问题统一放到 #500 里面，所以我会关闭这个 Issues
当这个问题被解决掉后，会在这里通知你。
