### ISSUE TITLE
微信小程序文档界面出错

### ISSUE THREAD

**Issue by HopeForToday** [Kenshin/simpread#136]
https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxml/event.html

当前页面使用 阅读模式 解析后 无法正常显示，暂时不支持 手动添加，请换用 聚焦模式 或者 将当前页面加入到排除列表 。

**Comment by Kenshin** [comment]
可以将 `mp.weixin.qq.com` 加入到排除列表中，下个版本会改善这个提示方式。
关联问题 https://github.com/Kenshin/simpread/issues/90

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> 匹配失败后，自动退出阅读模式，并启动临时阅读模式，可继续生成阅读模式的页面。

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update
