### ISSUE TITLE
在同一台电脑上，同时使用不同的浏览器登录简悦高级账户的问题

### ISSUE THREAD

**Issue by jxmnhm** [Kenshin/simpread#1361]
- 操作系统 ** MacOS**
- 浏览器版本 **版本 86.0.4240.198（正式版本） (x86_64)**
- 简悦版本 **2.0.0**
- 发生问题的地址 <北京>

我的问题是这样的：

我仅在一台笔记本电脑上安装插件，并未登录其他浏览器，但系统突然提示我“您使用此账户登录了过多的浏览器”，并把我踢下线了，无法登录高级账户。

**Comment by llewok** [comment]
我也有这样问题，我在chrome和edge上安装了，每次打开关闭其中一个浏览器，都会重新自动登陆账号，打开关闭三次以后，就变成我登陆了三个不同的设备，真的很烦

**Comment by Kenshin** [comment]
@jxmnhm 

> 我仅在一台笔记本电脑上安装插件，并未登录其他浏览器，但系统突然提示我“您使用此账户登录了过多的浏览器”，并把我踢下线了，无法登录高级账户。

如果 **你在同一台电脑上，同时使用不同的浏览器登录简悦的高级账户**，这个情况是被锁定的，这个 Bug 已经解决了，下个版本（即将发布）

你目前暂时需要先解锁 https://simpread.pro/account 然后暂时避免我说的情况发生。（ 等下个版本发布后会有提示，到时候这个问题自行解决了。

**Comment by Kenshin** [comment]
@llewok 

如果你也是 **你在同一台电脑上，同时使用不同的浏览器登录简悦的高级账户** 一样的问题，请看

https://github.com/Kenshin/simpread/issues/1361#issuecomment-729332162 给出的解决方式。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了：**同一设备，打开不同浏览器被锁** 的问题。

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
