### ISSUE TITLE
排除名单及黑名单问题

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1362]
将 https://github.com 加入排除名单，阅读.md文档还是自动沉浸阅读。
只有将https://github.com 加入黑名单才能解决，但我并不想加入黑名单，有时候想手动沉浸

**Comment by Kenshin** [comment]
这个问题算是个 Bug 因为 `.md` 的优先级较高导致的，我先记 Bug

***

临时解决方案：你可以把 `github.com` 加入到 `延迟加载列表` 里面。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
