### ISSUE TITLE
Latex部分渲染错误

### ISSUE THREAD

**Issue by Creedowl** [Kenshin/simpread#1363]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://blog.csdn.net/liujian20150808/article/details/72998039>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

该页面前一部分的Latex可以正常渲染，但后面的就不行了，包括一些表格也错位了。已经关闭预加载，采用聚焦模式导出到notion也会有部分渲染错误

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

正常渲染

![image](https://user-images.githubusercontent.com/22554751/99495739-092e2700-29ae-11eb-8fb5-7a6224d0f418.png)

渲染失败

![image](https://user-images.githubusercontent.com/22554751/99495772-16e3ac80-29ae-11eb-837f-cbeec0b1fd06.png)

**Comment by Kenshin** [comment]
LateX 的页面在渲染时如果失败的话，需要将这个页面加入到 [延迟加载列表](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e5%bb%b6%e8%bf%9f%e5%8a%a0%e8%bd%bd) 等加载完在手动进入，你可以试试。

我测试过是没问题的。

**Comment by Kenshin** [comment]
> 已经关闭预加载，采用聚焦模式导出到notion也会有部分渲染错误

不应该 **关闭预加载**，另外保存到 Notion 则跟简悦无关，我记得 Notion 仅支持另外一种 LateX 解析方案。

**Comment by Creedowl** [comment]
我按照 #534 提及的两种方法，对于我尝试的这个页面都无效，会有一半的Latex渲染失败，像我截图里面那样。确定是等页面完全加载完成后才进入的阅读模式，目前是开启预加载，将blog.csdn.net加入了延迟加载列表

<details>

<summary>简悦配置</summary>

![image](https://user-images.githubusercontent.com/22554751/99531912-6c37b200-29de-11eb-9e3a-22ece8d7a050.png)

</details>

这是原式页面

![image](https://user-images.githubusercontent.com/22554751/99531763-3266ab80-29de-11eb-9d22-f575abce1102.png)

这是简悦部分解析失败的

![image](https://user-images.githubusercontent.com/22554751/99531798-414d5e00-29de-11eb-8d5e-46b6e90a4c7c.png)

**Comment by Kenshin** [comment]
应该没有问题。（或许是新版没有问题，下面的 PDF 是我用新版转换后的结果，你可以看下。）
另外，新版已经提交了，希望本周可以审核通过。

[编译原理 FIRST 集、FOLLOW 集、SELECT 集求法通俗解释 & LL(1) 文法判定_多反思，多回顾，要坚持。-CSDN 博客_select 集.pdf](https://github.com/Kenshin/simpread/files/5563947/FIRST.FOLLOW.SELECT.LL.1._.-CSDN._select.pdf)

**Comment by Creedowl** [comment]
感谢，应该是版本的问题，等新版本上线了

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 -简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 -自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 -授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 -每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 -小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 -RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 -稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 -请订阅简悦的发布通知频道 👉 https://t.me/simpread
 -简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
