### ISSUE TITLE
代码段增强运行出错

### ISSUE THREAD

**Issue by Diluo001** [Kenshin/simpread#1367]
这个网站( http://www.cplusplus.com/reference/cctype/ispunct/ )很多网页提示.

![image](https://user-images.githubusercontent.com/41585868/99537216-58904980-29e6-11eb-8e01-f4f209029d14.png)

**Comment by Kenshin** [comment]
谢谢反馈。

在某些页面确实会出现这样的问题，我会把它们统一记录到 #500 并关闭这个 Issues（因为类型相同的太多）

修复后我会在这里通知你。
