### ISSUE TITLE
重新安装或者重置后自动生成新UID且无法退出？

### ISSUE THREAD

**Issue by niuniu326075** [Kenshin/simpread#1368]
edge(chrome内核)重新安装插件后自动生成的新UID，无法退出登录重新恢复登录旧UID，没有账号icon可以点击退出，如图（找不到退出登录的入口）
![image](https://user-images.githubusercontent.com/29769569/99540702-d5bdbd80-29ea-11eb-94f4-2c5a40789684.png)

**Comment by Kenshin** [comment]
你需要将你的 UID 找回 https://simpread.pro/reset
找回后如何配置请看 https://github.com/Kenshin/simpread/issues/1347#issuecomment-729327110

下个版本会集成这个功能，并优化为一步操作。

**Comment by Kenshin** [comment]
谢谢自救成功，其实 https://simpread.pro/reset 找回后下方的文字说明有上传你配置文件的「半自动方案」。

当然，下个版本已经转换为「自动方案」😃
