### ISSUE TITLE
保存到印象笔记，能否指定笔记本

### ISSUE THREAD

**Issue by MatrixFour** [Kenshin/simpread#1371]
尊敬的开发者：
      您好！
      我在使用简悦保存文章到印象笔记的时候，发现不能指定到印象笔记下的某个笔记本。当我进入印象笔记寻找我刚刚的文章时，发现保存到哪个笔记本似乎是随机的。
      能否添加指定笔记本功能？或者设置保存到一个默认的笔记本，我待会儿再来处理文章！

**Comment by Kenshin** [comment]
谢谢反馈。

> 发现不能指定到印象笔记下的某个笔记本。

是的，目前无法指定任意笔记本。所以保存的位置在 **你的默认笔记本**

> 发现保存到哪个笔记本似乎是随机的

应该不是随机的，不清楚你是如何判断的。

> 能否添加指定笔记本功能？

近期暂时没有这个计划。（ 但会提供的此功能的。
