### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by L-QF** [Kenshin/simpread#1372]

**Comment by L-QF** [comment]
操作系统 Win10

浏览器版本版本 87.0.4280.66（正式版本） （64 位）

简悦版本 2.0.0

谷歌浏览器自带选中文字后可以进行“google搜索”，打开阅读模式后，如果开启标注，就不能使用这种方式；

可以的话，能否将两种方式兼容？

**Comment by Kenshin** [comment]
你可以试试 https://simpread.ksria.cn/plugins/details/NupOHRQHZ2 这个插件，能满足你的需求。

PS：没问题的话，请关闭此 Issues ~

**Comment by Kenshin** [comment]
除此以外，你说的方式在进入阅读模式后仍可以使用

![image](https://user-images.githubusercontent.com/81074/99627621-9be2ca80-2a6f-11eb-8beb-87ef8729c616.png)

**Comment by L-QF** [comment]
好的，谢谢！
