### ISSUE TITLE
希望在归档中加入分类的功能，可以进行文件夹/标签管理。

### ISSUE THREAD

**Issue by IcePigZDB** [Kenshin/simpread#1374]
希望在归档中加入分类的功能，可以进行文件夹/标签管理。

**Comment by Kenshin** [comment]
谢谢反馈，会考虑此功能的。👍

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，请看下图

![image](https://user-images.githubusercontent.com/81074/100058311-00cd6480-2e64-11eb-901e-1205b65785cc.png)


## 增加了一些新功能：

 -简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 -自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 -授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 -每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 -小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 -RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 -稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 -请订阅简悦的发布通知频道 👉 https://t.me/simpread
 -简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。

**Comment by Kenshin** [comment]
补充说明下：

即便是归档了，也能在 **标签里面** 找到。

**Comment by IcePigZDB** [comment]
另外想问一下可以进行文章级别的标签吗？不需要标注就能打标签这样，我个人还是想按文章进行管理。

**Comment by binsee** [comment]
> 另外想问一下可以进行文章级别的标签吗？不需要标注就能打标签这样，我个人还是想按文章进行管理。

可以的。在阅读模式标注模式下或稍后读界面中，编辑文章信息，选择标签或输入标签名称按回车。
![image](https://user-images.githubusercontent.com/5285894/100103805-57f12a80-2ea0-11eb-996f-30adb44f70b1.png)

![image](https://user-images.githubusercontent.com/5285894/100103626-19f40680-2ea0-11eb-8d51-5ce606005f51.png)


![image](https://user-images.githubusercontent.com/5285894/100103875-6dfeeb00-2ea0-11eb-8bbe-d360bf675a7c.png)

**Comment by IcePigZDB** [comment]
恍然大悟，感谢😊
