### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by handbye** [Kenshin/simpread#1376]
发生问题的地址: <https://www.mrwu.red/web/3699.html>

**Comment by Kenshin** [comment]
谢谢反馈。

个人站是不会被收录到 `官方适配源` 里面的，但是你可以使用 [站点编辑器](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8) 来自己生成这个适配站点。

没问题的话，请关闭这个 Issues  😀
