### ISSUE TITLE
切换代码高亮插件崩溃

### ISSUE THREAD

**Issue by luo276785794** [Kenshin/simpread#1377]
https://mp.weixin.qq.com/s/b0TlrCacg6YHe-YEdjeQgA 
![image](https://user-images.githubusercontent.com/4277517/99783545-80ea8600-2b55-11eb-9210-e49a780be640.png)

**Comment by Kenshin** [comment]
嗨，周末好。

在某些页面确实会出现这样的问题，我会把它们统一记录到 #500 并关闭这个 Issues（因为类型相同的太多）

修复后我会在这里通知你。

**Comment by luo276785794** [comment]
> 嗨，周末好。
> 
> 在某些页面确实会出现这样的问题，我会把它们统一记录到 #500 并关闭这个 Issues（因为类型相同的太多）
> 
> 修复后我会在这里通知你。

ok
