### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by zpyovo** [Kenshin/simpread#1384]
发生问题的地址: <http://colah.github.io/posts/2015-09-Visual-Information/

**Comment by Kenshin** [comment]
谢谢反馈，因为这个页面并非大众类页面，请使用 [站点编辑器](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8) 自行适配。

没问题的话，请关闭这个 Issues  😀 

***

不过，你应该的第二个反馈这个页面的，这是关于什么内容的网站？

**Comment by zpyovo** [comment]
是个个人博客网站，应该是有什么的插件导致无法转换
