### ISSUE TITLE
“稍后读”的bug

### ISSUE THREAD

**Issue by abcvav** [Kenshin/simpread#1387]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 win10 家庭版

- 浏览器版本 Microsoft Edge 87.0.664.41

- 简悦版本 **2.0.0**

**请描述你的问题**
问题1：在“稍后读”模块中，所有被标注的界面都进入了“未读列表”，但是当我读完将其归档后，原本的标签却随着归档一起消失了，使得我无法通过标签查看已经归档的标记
问题2：基于问题1，如果要使用标签来检索，就只能一直将笔记置于“未读列表”中不归档，但是当标注的数量太多后，
区分哪些读了哪些没读就变得很麻烦了
望解决！

归档前：标签还存在
![1](https://user-images.githubusercontent.com/47599849/99933776-f3967400-2d96-11eb-90b1-5385d64e55b5.png)
归档后：标签不见了
![2](https://user-images.githubusercontent.com/47599849/99933781-f6916480-2d96-11eb-9d7e-41f1ca0fc7c0.png)

**Comment by Kenshin** [comment]
嗨，请升级到 **2.1.0 版** 即可解决这个问题。

这个版本刚刚才发布，你可以试着进入 chrome://extensions/ 更新看下。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，请看下图

![image](https://user-images.githubusercontent.com/81074/100058311-00cd6480-2e64-11eb-901e-1205b65785cc.png)

简单的说，即便是归档了，也能在 **标签里面** 找到。

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
