### ISSUE TITLE
mac big sur Chrome浏览器下无法导出Markdown及pdf、epub文件

### ISSUE THREAD

**Issue by Mrycp** [Kenshin/simpread#1389]
- 操作系统 macos big sur 版本11.0.1

- 浏览器版本 Chrome  87.0.4280.67（正式版本） (x86_64)

- 简悦版本 2.1.0

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html>

**请描述你的问题**

> 稍后读及阅读模式下都无法导出Markdown，提示该功能为实验功能，请提issue。
> 无法导出epub、PDF，点击后提示一闪而过，output文件夹中也已安装同步助手，已安装pandoc。

**截图**
![image](https://user-images.githubusercontent.com/35561057/99941320-c9e64880-2da8-11eb-9b11-3f99d7a8950e.png)
![image](https://user-images.githubusercontent.com/35561057/99941631-5133bc00-2da9-11eb-9769-a79a61cc777d.png)
![image](https://user-images.githubusercontent.com/35561057/99941689-67da1300-2da9-11eb-99a0-5db973685654.png)
![image](https://user-images.githubusercontent.com/35561057/99941708-7294a800-2da9-11eb-8e2e-614a27b3e4d0.png)
![image](https://user-images.githubusercontent.com/35561057/99941866-b2f42600-2da9-11eb-8ac2-28fb4b64f72e.png)

**Comment by Kenshin** [comment]
谢谢反馈。

正在解决在 Big Sur 下面的问题。

**Comment by Kenshin** [comment]
抱歉，因为简悦在发布时，Big Sur 还未发布，Chrome 一直在审核，审核了一周今天才通过。

所以会有一些 Big Sur 的问题。

已经在解决了，因为 **简悦 · 同步助手 不依赖于 Chrome 应用商店，所以无需审核时间**。

**Comment by Kenshin** [comment]
初步怀疑不是 Big Sur 的问题，大概率是代码的问题，明天确认下。

因为我的没有问题，所以，大概率可以规避这个问题。

**Comment by Mrycp** [comment]
> 初步怀疑不是 Big Sur 的问题，大概率是代码的问题，明天确认下。
> 
> 因为我的没有问题，所以，大概率可以规避这个问题。

我更新了APP，重新设置了一遍，上面提到的Markdown、PDF、epub都可以正常导出了。谢谢！

**Comment by binsee** [comment]
> 初步怀疑不是 Big Sur 的问题，大概率是代码的问题，明天确认下。

我在 MacOS Big Sur 和Win10上，都可以复现问题，关键在于 同步助手中 `导出 - 路径` 未设置时，就会导出失败。
这个路径，按其提示，默认未设置时，应当是`同步目录/output`，但实际未设置时就是空路径，导出就失败

**Comment by Kenshin** [comment]
@binsee 

谢谢 🙏 🙏 🙏
如果不是系统的问题我就放心了，稍后就可以修复，修复后我会逐一通知~

**Comment by Kenshin** [comment]
@binsee @Mrycp 

此问题已经解决，但并没有升级版本，如有需要请重新下载。（ 目前仅限 Mac 版，Win 暂时未升级，升级后我会再次通知。

***

下载地址：[坚果云](https://www.jianguoyun.com/p/DdXeyasQwobGBxjK7c0D) |  [TG Channel](https://t.me/simpreadgroup)

***

暂时先不关闭此 Issues 了~

**Comment by Kenshin** [comment]
嗨，我重开了一个 Issues  https://github.com/Kenshin/simpread/issues/1407 来描述这个问题，所以我关闭这个 Issues 了~
