### ISSUE TITLE
印象笔记保存失败

### ISSUE THREAD

**Issue by libingtong** [Kenshin/simpread#139]
印象笔记保存失败

**Comment by Kenshin** [comment]
感谢反馈~
`印象笔记 / Evernote` 的支持度不是很好，[原因](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

个人建议使用 `Onenote` ，如果感兴趣的话，可以看这篇文章 https://sspai.com/post/40754

**Comment by coolhwm** [comment]
这个需求还是比较强烈的

**Comment by Kenshin** [comment]
@coolhwm 
不是很好解决... ENML 忒恶心了...  😭

**Comment by MagisDing** [comment]
@Kenshin 有没有兴趣添加对为知笔记的支持？

**Comment by Kenshin** [comment]
@MagisDing 
为知笔记并没有跟 Web 相关的 API，所以没办法接入它。 😅

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
