### ISSUE TITLE
Mac big sur 11.0.1 下简悦同步助手会导致command+w快捷键无法使用。

### ISSUE THREAD

**Issue by Mrycp** [Kenshin/simpread#1390]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **macos big sur 版本11.0.1**

- 浏览器版本 **Chrome 87.0.4280.67（正式版本） (x86_64)**

- 简悦版本 **2.1.0**

**请描述你的问题**

> MAC系统下安装简悦同步助手会导致系统快捷键command+w无法使用，退出APP后恢复。

**Comment by Kenshin** [comment]
抱歉，因为简悦在发布时，Big Sur 还未发布，Chrome 一直在审核，审核了一周今天才通过。

所以会有一些 Big Sur 的问题。

已经在解决了，因为 **简悦 · 同步助手 不依赖于 Chrome 应用商店，所以无需审核时间**。

**Comment by Kenshin** [comment]
嗨，**command+W** 的问题已经解决了，请重新在  https://www.jianguoyun.com/p/DdXeyasQwobGBxjK7c0D 下载，请注意下载时的版本标识。

另外，请留意其它 同步助手在 Big Sur 下的问题 https://github.com/Kenshin/simpread/labels/sync

**Comment by Kenshin** [comment]
我关闭这个 Issues 了~
