### ISSUE TITLE
简悦 · 同步助手常驻 Dock 栏

### ISSUE THREAD

**Issue by Mrycp** [Kenshin/simpread#1391]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS big sur 11.0.1**

- 简悦同步助手版本 **1.0.0**

**请描述你的问题**

> 简悦同步助手每次打开都提示网络允许
> 点击关闭窗口后无法再次唤起，需重启应用后才能再次进入管理页面

**截图**

**Comment by Kenshin** [comment]
抱歉，因为简悦在发布时，Big Sur 还未发布，Chrome 一直在审核，审核了一周今天才通过。

所以会有一些 Big Sur 的问题。

已经在解决了，因为 **简悦 · 同步助手 不依赖于 Chrome 应用商店，所以无需审核时间**。

**Comment by Kenshin** [comment]
右上角 menubar 可以启动吗？

**Comment by Mrycp** [comment]
> 右上角 menubar 可以启动吗？
通过menubar可以启动，才发现有menubar（我隐藏了状态栏），有menubar建议点击关闭后可以不用在dock栏显示了。常驻dock栏还挺占位的。毕竟的功能看没有常驻的必要。后期如果更改为稍后读的APP再常驻也是合适的。
PS：助手里的快捷键设置好像无效，我设置了SHIFT+j，按了之后没有反应，可能是我设置的有问题吧，我再试试看看。不过这个快捷键不是我刚需，不要紧就是了。

**Comment by binsee** [comment]
@Mrycp 兄弟你uid暴漏了😂😂

@Kenshin MacOS Big Sur 下，快捷键设置了多几种，都没有生效的。不是刚需，我就清空不设置了。

**Comment by Mrycp** [comment]
> @Mrycp 兄弟你uid暴漏了😂😂
> 
> @Kenshin MacOS Big Sur 下，快捷键设置了多几种，都没有生效的。不是刚需，我就清空不设置了。

@binsee 谢谢，已经删除截图

**Comment by Kenshin** [comment]
@Mrycp 

Dock 的常驻选项下个版本加个选项。（等忙完了这几天就可以更新。

> 助手里的快捷键设置好像无效，我设置了SHIFT+j，按了之后没有反应，可能是我设置的有问题吧，我再试试看看。不过这个快捷键不是我刚需，不要紧就是了

你可以看下 https://github.com/Kenshin/simpread/issues/1402 的说明。

***

另外，方便的话 Mac 版的一些其它问题，细节看这里 https://github.com/Kenshin/simpread/issues/1407

**Comment by liyang85** [comment]
烦请添加选项关闭同步助手的 Dock 常驻。

去年底的 issue 了，不是什么大问题，估计开发者可能忘记了，哈哈……

**Comment by Kenshin** [comment]
> 烦请添加选项关闭同步助手的 Dock 常驻。
> 
> 去年底的 issue 了，不是什么大问题，估计开发者可能忘记了，哈哈……

其实没忘，因为都在 Todo 里面，之是确实没有更新新的版本，因为在做简悦其它的事情。 😂

升级后我会在这里通知你们。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 隐藏 Dock 功能来了

![image](https://user-images.githubusercontent.com/81074/172758651-02fb7c7e-41a0-4a2b-ae14-1b8c53f000ed.png)

同时也可自适应 Menubar Icon（仅限 Mac 用户）

![image](https://user-images.githubusercontent.com/81074/172758764-e4dbabd8-f377-47a6-bbd0-8414a991a36c.png)

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
