### ISSUE TITLE
由于后台异常导致恢复购买失败，请稍后再试。

### ISSUE THREAD

**Issue by littlen9ne** [Kenshin/simpread#1395]
RT

**Comment by Kenshin** [comment]
提示服务器问题吗？
方便的话，请截图。

**Comment by robily** [comment]
![由于后台异常 (1)](https://user-images.githubusercontent.com/75737146/101636893-ed76e780-3a66-11eb-93d6-8aabce62921e.jpg)

**Comment by Kenshin** [comment]
@robily 
看看是不是这个问题 https://github.com/Kenshin/simpread/issues/1334

**Comment by robily** [comment]
> @robily
> 看看是不是这个问题 #1334

Edge 浏览器，但本来也已勾选“所有站点”。

**Comment by Kenshin** [comment]
@robily 

现在是否能用了？

**Comment by ForeverYoungPp** [comment]
> @robily
> 
> 现在是否能用了？

我也遇到了这种问题，尝试上面的解决方案，账户成功授权。

**Comment by Kenshin** [comment]
嗨，各位，这是一个非常老的 Issues 了，但忘记 Close 它了。

当你收到这个提示时，我已经关闭了这个 Issues，关于「此问题」的说明：

1. 这不是简悦后端的服务器问题
2. 这是因为你没有开启某个网络权限造成的

解决方案 https://github.com/Kenshin/simpread/discussions/1567
