### ISSUE TITLE
网站无法打开

### ISSUE THREAD

**Issue by DevinFu** [Kenshin/simpread#1396]
今天收到simpreadchrome插件更新，提示可以下载同步助手，就想进入网站下载。
结果发现网站无法打开了，就一直转圈圈，等待很久也无法打开网站。

**Comment by binsee** [comment]
请至坚果云下载使用（需要登陆坚果云账号）  https://www.jianguoyun.com/p/DdXeyasQwobGBxjK7c0D

**Comment by Kenshin** [comment]
@DevinFu 
哪个页面？现在还是这样吗？

@binsee 
🙏 🙏

**Comment by binsee** [comment]
他打开的可能是  
451: DEPLOYMENT_DISABLED: https://simp.red/

![image](https://user-images.githubusercontent.com/5285894/99969583-a8e81c80-2dd5-11eb-8a16-a9946ec7b92f.png)

**Comment by Kenshin** [comment]
@binsee 

😂 这个地址也没有下载链接…

**Comment by DevinFu** [comment]
http://ksria.com/simpread/
这个网址，依然打不开今天
@binsee

**Comment by Kenshin** [comment]
> http://ksria.com/simpread/
> 这个网址，依然打不开今天
> @binsee

能正常访问网络吗？

**Comment by binsee** [comment]
> http://ksria.com/simpread/
> 这个网址，依然打不开今天

打不开是指什么情况，页面上有什么提示？比如`找不到服务器ip地址`什么的，最好是上截图。
我认为是你本地网络或插件之类的问题。

ps：这个站是在github上部署的，美国ip，因此如果你网络受限比较严重，确实可能打不开网站。
