### ISSUE TITLE
[Notice]使用授权登录时的如果配置文件较低则会出现无法登录成功的问题（付解决方案）

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1398]
今日打开chrome发现简悦更新了2.1.0，之后在mac和pc上的edge全新安装简悦2.1.0（要从chrome商店安装，edge商店暂未更新，之前装的edge商店版本）。

在edge上使用坚果云登陆来恢复高级账户，然后登陆成功，但并未自动刷新页面，且未能恢复高级账户。
查看选项后发现只恢复了一部分配置（如授权管理、稍后读列表），而账户信息（uid、昵称、邮箱等）未恢复。

经过排查，发现是chrome上的简悦更新后，未再次向坚果云上同步配置，导致坚果云上配置文件内的版本是`2.0.0`，而edge新安装的简悦`2.1.0`在读取坚果云上的配置文件时，发现配置文件内的版本比当前插件版本旧，因此忽略了部分配置。

对此问题，需要进行优化：在发现已有配置文件比当前版本旧时，提示用户先在已授权设备上同步配置，以确保云端配置是最新版本，再在新设备上登陆恢复授权。

**Comment by Kenshin** [comment]
okay 明白了。

这确实是个缺陷，即：**使用授权登录时的配置文件较低** 会出现登录错误。

但目前只能下个版本解决了。

***

我先把这个 Issues 放到帮助里面。

**Comment by Kenshin** [comment]
#### 临时解决（规避）方案

使用 [授权登录](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E7%99%BB%E5%BD%95) 时，请确保你的同步盘里面的配置文件为 **2.1.0**

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
