### ISSUE TITLE
有退出聚焦或阅读模式的快捷键吗？

### ISSUE THREAD

**Issue by lcx412** [Kenshin/simpread#14]
只找到进入的快捷键，没有退出的……

**Comment by Kenshin** [comment]
下个版本会提供 `esc` 退出方式。
`聚焦模式` 暂时没有快捷键；
`阅读模式` 的退出快捷键是 `double c`；

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`
解决办法：新增 `ESC` 退出方式。
更新日志 请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
