### ISSUE TITLE
【站点】实验楼文档

### ISSUE THREAD

**Issue by liguoqinjim** [Kenshin/simpread#140]
能否帮忙适配实验楼文档页面

如：https://www.shiyanlou.com/courses/63/labs/291/document

**Comment by Kenshin** [comment]
okay，周一我会确认下这个页面是否适合阅读模式。

**Comment by Kenshin** [comment]
不清楚为什么我一直无法注册成功，所以没办法帮你适配，不过 简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)

**Comment by liguoqinjim** [comment]
好的 感谢 临时阅读模式可以用的
