### ISSUE TITLE
无法把内容添加到稍后读

### ISSUE THREAD

**Issue by zhanyu8008** [Kenshin/simpread#1401]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10**

- 浏览器版本 **Chrome 87**

- 简悦版本 **2.1.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

已安装： 简悦 · 同步助手 1.0.0.exe和 Chrome插件
已连接该exe与高级账户。已经从同步助手中把「一键收藏」和「加入到稍后读」加入到Chrome的书签栏。

进入一个网页想把其加入稍后读时，点击这两个中的任一一个，都显示成功，2秒后关闭。但是进入稍后读的未读列表时，却没看到任何内容。已经试过很多网站，请问应该怎么办？

**截图**

![image](https://user-images.githubusercontent.com/10270522/99990385-b5c53a00-2dee-11eb-94fa-e8fcf7634c82.png)

![image](https://user-images.githubusercontent.com/10270522/99990502-d7262600-2dee-11eb-8bbb-b88b1aa33854.png)

![image](https://user-images.githubusercontent.com/10270522/99990696-1ce2ee80-2def-11eb-863b-62d623dd363a.png)

![image](https://user-images.githubusercontent.com/10270522/99990732-2704ed00-2def-11eb-948d-9ffb1c165cf5.png)

**Comment by binsee** [comment]
## 功能说明

同步助手小书签功能，是便于多个浏览器快速添加网页到稍后读，但依赖于同步功能，且简悦插件需要使用 **同步助手** 的同步方案。

1. 浏览器中的简悦插件，与云盘的同步是有时间间隔的，非随时随地都进行同步的
2. 小书签是将网页发送到 **同步助手**，由同步助手将网页写入到配置文件。由安装的网盘同步软件将配置文件同步到云端

## 推荐方案

因此，要实现即时同步，推荐使用以下方案：
1. 开启 **简悦插件** 中`同步助手 - 自动同步`
![image](https://user-images.githubusercontent.com/5285894/99994875-95987980-2df4-11eb-8267-c81516c6bd5e.png)
2. 在 **同步助手** 的同步中，开启`同步服务`，并设置同步文件夹。
![image](https://user-images.githubusercontent.com/5285894/99994933-ac3ed080-2df4-11eb-9e03-ee5c54479943.png)
3. 在云盘同步软件中正确设置，以确保同步上述文件夹
4. 如果经常使用，请确保允许 **同步助手** 与 同步盘 软件的`开机自启`

## 测试

### 测试环境如下

- Win10：
浏览器： Chrome + Edge
都安装简悦插件，并开启了 `同步助手 的同步方案`

- MacOS：
浏览器：Edge + Safari
Edge安装简悦插件，并开启了 `同步助手 的同步方案`

### 测试步骤

#### 测试1

1. Win10上，Chrome 中使用 `一键收藏` 书签，收藏一个页面
2. 2秒后，MacOS 上的 Chrome 中查看 `稍后读`，已经出现了新收藏的页面

#### 测试2

1. MacOS上，Safari中使用 `一键收藏` 书签，收藏一个页面
2. 2秒后，Win10 上的 Chrome & Edge 中查看 `稍后读`，已经出现了新收藏的页面

**Comment by Kenshin** [comment]
@binsee 

谢谢补充说明，我已经把这段放到了 http://ksria.com/simpread/docs/#/Bookmarklet 里面了。

**Comment by zhanyu8008** [comment]
懂了，还要到chrome插件里面开启自动同步，问题解决了，不过确实还是感觉太麻烦，暂时还是不用了，谢谢二位大佬

**Comment by ethanchengyu** [comment]
<img width="935" alt="iShot_2022-06-10_08 12 00" src="https://user-images.githubusercontent.com/25861044/172966585-c602755b-6ccc-459f-bec7-4605f516c43d.png">
请问下这是什么情况，而且使用场景中_MacOS上，Safari中使用 一键收藏 书签，收藏一个页面_,如何在safair中使用一键收藏书签，是拖拽地址到同步助手？

**Comment by Kenshin** [comment]
@ethanchengyu 

需要把书签拖到 Safari 后使用

**Comment by ethanchengyu** [comment]
@Kenshin 谢谢，不知道怎么回事，配置又出问题了，不知道跟我选手动同步有没有关系，我如果改为自动同步，客户端的同步路径不知道怎么选，坚果云simpread同步路径好像是坚果云/simpread，我放在obsidian库中又没法用了，有点苦恼，暂时想着就不用safair阅读～～～感觉自己不知道哪里不对，就是有点乱哈，见谅
<img width="1052" alt="iShot_2022-06-10_09 51 13" src="https://user-images.githubusercontent.com/25861044/172974689-e73c3300-6317-46c9-ad50-962ff22c844a.png">

**Comment by Kenshin** [comment]
@ethanchengyu 

1. 自动同步必须要放在 `<你的路径>/SimpRead` 这个结构下面，大小写也需要一致。
2. 如果使用坚果云实现多设备自动同步的话，需要 `<坚果云>/SimpRead`，否则步骤一的路径就行。
