### ISSUE TITLE
建议：离线 markdown 通过相对路径插入图片（将图片和 md 打包成 zip 下载）

### ISSUE THREAD

**Issue by ky-huang** [Kenshin/simpread#1403]
随便找了个文章试了一下，https://sspai.com/post/63730

导出来的离线 md 文件足足有 5M，Typora 直接挂机，要用 vscode 才能打开。。。

<img width="659" alt="Snipaste_2020-11-24_02-40-46" src="https://user-images.githubusercontent.com/60381489/100001887-bfef3480-2dfe-11eb-9a2e-05ff3d1afa6d.png">
![image](https://user-images.githubusercontent.com/60381489/100001924-ce3d5080-2dfe-11eb-81e5-e44d2c108380.png)

建议可以做成用相对路径插入图片的方式（或者提供一个选项），这样子对 Typora 这类编辑器会稍微友好一些。

**Comment by Kenshin** [comment]
哈哈，我也是测试了 nnnn  个编辑器才发现，只有 VS Code 才能打开它。

因为有了 [同步助手](http://ksria.com/simpread/docs/#/Sync) 所以才有了更多的可能性~

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
