### ISSUE TITLE
阅读模式高亮bug

### ISSUE THREAD

**Issue by hsy0528** [Kenshin/simpread#1406]
-请说明发生问题的环境：阅读模式 选中文本进行高亮

- 操作系统： Windows 10

- 浏览器版本 ** edge Version 87.0.664.41 (Official build) (64-bit)

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://www.1xuezhe.exuezhe.com/Qk/art/81804?dbcode=3&flag=2>

**请描述你的问题**
阅读模式下，对文本进行高亮操作，如果选中的文本上方已被设置为高亮，由于选中文本后，需要将鼠标移动到高亮浮窗中才能点击按钮，而此时高亮浮窗出现在了上方高亮文本的上方，鼠标移动过程中浮窗就会自动变为对已高亮文本的设置。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
1.对以下文本设置高亮，则该文本下方附近的文本就无法高亮（因为浮窗在已经高亮的文本上）
针对一些保险公司不重视微信营销平台建设、没有微信营销平台、或没有专门机构管理等问题，建议总公司领导亲自挂帅，尽快组建专门团队，努力搭建或完善信营销平台。针对微信营销中保险公司处于被动地位问题，保险公司应完善微信营销平台功能，积极开展宣传，在公司网站首页、保险销售网点等地放置二维码，引导客户关注其微信公众号。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![Snipaste_2020-11-24_10-51-58](https://user-images.githubusercontent.com/30423550/100041543-86411c80-2e44-11eb-9e42-c8faa215c409.png)

**Comment by Kenshin** [comment]
> 阅读模式下，对文本进行高亮操作，如果选中的文本上方已被设置为高亮，由于选中文本后，需要将鼠标移动到高亮浮窗中才能点击按钮，而此时高亮浮窗出现在了上方高亮文本的上方，鼠标移动过程中浮窗就会自动变为对已高亮文本的设置。

确实有这个问题，你可以在已高亮的标注点击鼠标试试（会有惊喜）

- 单击 → 可以更改标注颜色

- 双击 → 弹出编辑框

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
