### ISSUE TITLE
简悦 同步助手——希望隐藏Mac程序坞图标，只在菜单栏显示

### ISSUE THREAD

**Issue by PayneSnow** [Kenshin/simpread#1408]
简悦 同步助手——希望隐藏Mac程序坞图标，只在菜单栏显示。

**Comment by Kenshin** [comment]
谢谢反馈，下个版本解决。

**Comment by LoneFireBlossom** [comment]
试了一下好像现在还是不能隐藏dock中的助手图标啊
macOS 10.15.7

**Comment by Kenshin** [comment]
@LoneFireBlossom 

是的，目前的版本还是无法隐藏 Dock  😂

**Comment by LoneFireBlossom** [comment]
是不是可以考虑下支持cmd+W关闭窗口，要不然每次都是要跑到触控板上去点关闭好麻烦
（大部分软件都是能cmd+W关闭的吧）

**Comment by Kenshin** [comment]
> 是不是可以考虑下支持cmd+W关闭窗口，要不然每次都是要跑到触控板上去点关闭好麻烦
> （大部分软件都是能cmd+W关闭的吧）

会的，不过我用的 MBP，机会没有关闭它的场合。  😅 

之前有个 Bug 会导致占用全局快捷键，所以就先下线了。

**Comment by LoneFireBlossom** [comment]
我也是mbp，咱们使用习惯不一样吧
我才用了几个月算是新手。

刚刚试了一下对同步助手，cmd+H/W都没用，emmm，我平时主要用快捷键和触控板，关闭窗口基本上全用快捷键，所以碰到一个快捷键无效软件就感觉麻烦。

---

这么说的话可能因为我这几天重启次数有点儿多（因为电脑老是死机，我还没查出原因），每次重启之后都会看到同步助手，就不得不将其关闭，所以会觉得麻烦，所以才想了上面的问题

**Comment by Kenshin** [comment]
哈哈，支持快捷键是正常的，并不是你的使用问题，而是原本就应该支持关闭才对的。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 隐藏 Dock 功能来了

![image](https://user-images.githubusercontent.com/81074/172758651-02fb7c7e-41a0-4a2b-ae14-1b8c53f000ed.png)

同时也可自适应 Menubar Icon（仅限 Mac 用户）

![image](https://user-images.githubusercontent.com/81074/172758764-e4dbabd8-f377-47a6-bbd0-8414a991a36c.png)

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
