### ISSUE TITLE
添加关闭稍后读快捷键选项

### ISSUE THREAD

**Issue by Benature** [Kenshin/simpread#1409]
因为我使用的快捷键比较多，希望添加关闭稍后读快捷键选项，避免误触等问题

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html>

**Comment by Kenshin** [comment]
谢谢建议，会考虑的。

PS：除稍后读外，其它的功能也没有 **删除快捷键** 功能，

**Comment by smartmimi** [comment]
同样需要“添加到稍后读”快捷键的关闭选项。
个人感觉右键菜单足够了，快捷键在正常操作的时候容易误触。

**Comment by Kenshin** [comment]
@smartmimi 

嗨，新版已经有了解决方案，发布后我会在这里通知你。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
