### ISSUE TITLE
官网1.0.4版本介绍好像有打错字的

### ISSUE THREAD

**Issue by zhihaofans** [Kenshin/simpread#141]
[http://ksria.com/simpread/welcome/version_1.0.4.html](http://ksria.com/simpread/welcome/version_1.0.4.html#senior-foucs-mode)

**更加强大的聚焦模式**  ->  **1**.

的

 **`取保勾选`**

 应该改成

**`确保勾选`** 

 吧

**Comment by Kenshin** [comment]
感谢反馈～
为防剧透，我先关闭这个 issues 了，明天会改正。
话说，你是怎么发现这个链接的？

**Comment by zhihaofans** [comment]
@Kenshin 1.0.4测试版里在未适配网站按快捷键，然后右上角弹出提示，发现 **`临时阅读模式`**这几个字 是个链接，点击后跳转到了 [`Github wiki`](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)，在wiki 里`临时阅读模式`的第一句跳转到这个网页，我在查临时阅读模式怎么用然后就发现了打错字233

**Comment by 23784148** [comment]
哦，原来你用了测试版 1.0.4 …
临时阅读模式感觉如何？
下周就会正式发布了。

**Comment by 23784148** [comment]
额，用另外一个账号发了…

**Comment by zhihaofans** [comment]
@23784148 临时阅读模式挺好用的，就是不能选中区域后再编辑和保存规则有点麻烦，每次都得手动打开临时阅读模式

**Comment by Kenshin** [comment]
@zhihaofans 
`保存功能` 下个版本就会提供~ 选中区域的 `再编辑` 是指什么？

> 下个版本将增加 `自行添加新站` 功能。

**Comment by zhihaofans** [comment]
@Kenshin 抱歉表达能力不好，我的意思是保存前/后编辑站点的规则

**Comment by Kenshin** [comment]
额，原来如此...
下个版本会提供此功能。
使用了 `站点编辑器` 后就会从临时阅读模式 → 阅读模式。
所以，临时阅读模式也不需要使用 `站点编辑器`。

**Comment by Kenshin** [comment]
这个问题已经解决了，顺便 1.0.4 也正式发布了~  😄
