### ISSUE TITLE
ifeve 网站的代码段在阅读模式下显示不出来

### ISSUE THREAD

**Issue by LiWenGu** [Kenshin/simpread#1410]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <http://ifeve.com/starvation-and-fairness/>

**请描述你的问题**

ifeve 网站的代码文本在阅读模式下显示不出来

**截图**

![image](https://user-images.githubusercontent.com/15909210/100074971-53198000-2e7a-11eb-95da-0803dc44d05a.png)

**Comment by Kenshin** [comment]
谢谢反馈，在某些页面确实会出现这样的问题，我会把它们统一记录到 #500 并关闭这个 Issues（因为类型相同的太多）

修复后我会在这里通知你。
