### ISSUE TITLE
无法正常显示V2EX的跟帖。

### ISSUE THREAD

**Issue by qiankunxienb** [Kenshin/simpread#1411]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

V2EX只能显示1楼的内容。后面的跟帖都无法正常显示。如下图所示：

![image](https://user-images.githubusercontent.com/71627005/100080541-e9e93b00-2e80-11eb-84c6-bf72caa515fc.png)

但实际上有很多楼层：

![image](https://user-images.githubusercontent.com/71627005/100080667-12713500-2e81-11eb-83ad-edfd295a4baa.png)

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://v2ex.com/t/728746

**Comment by Kenshin** [comment]
嗨，谢谢详细的截图给我，不过。这是正确的。 😂 

简悦仅捕捉了正文而已，当然没有评论了。否则正文 + 评论的话，跟原页面有什么区别呢？
