### ISSUE TITLE
Win版同步助手未开机自启（特殊环境复现）

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1413]
我的系统上临时目录`%TEMP%`是在**内存盘**上的，每次重启电脑会清空。
而win版同步助手设置开机自启，写入到注册表的程序文件不是下载到的`简悦 · 同步助手 1.0.0.exe`文件，而是其解压到`%TEMP%`目录下的程序文件。
如下图：我的`%TEMP%`目录是`Z:\TEMP\`
![image](https://user-images.githubusercontent.com/5285894/100107426-97217a80-2ea4-11eb-90f1-2382bfb6b995.png)

而我这种临时目录在内存盘上的特殊环境，每次开机时临时目录都是空的，因此出现了，开机后同步助手未能启动的情况。

而对于其他用户，如果使用清理软件清空了临时文件，理论上也会出现开机后找不到程序或程序无法正常运行的情况。

由于`简悦 · 同步助手 1.0.0.exe`文件其实是个特殊的自解压包，因此要么以安装形式将包内文件解压到非临时目录，要么写入注册表时写入`简悦 · 同步助手 1.0.0.exe`文件而非解压到临时目录的程序文件。

-----

更新补充：

我将解包出来的程序复制到固定目录，直接使用`简悦 · 同步助手.exe`，并设置了开机自启。
但开机后，同步助手启动后，弹出了同步助手的界面，并不是以后台静默运行，这点需要优化。

**Comment by Kenshin** [comment]
emmm...

确实没有详细研究过这个事情，因为我以为配置信息会保存在 exe 内部（其实就是个 Chrome localstorage 里面）但具体物理文件保存在哪里，确实需要研究下。

***

有种方式可以解决这个问题，即：将 `localstorage` 的数据保存在 exe 运行环境下（或指定目录）来读取。

**Comment by binsee** [comment]
问题1：

我说的不是配置信息，而是程序包。

从网盘下载的同步助手程序文件是 `简悦 · 同步助手 1.0.0.exe`，其实是个自解压程序，运行后会将内部的压缩包解压，写出以下文件：

```
chrome_100_percent.pak
chrome_200_percent.pak
d3dcompiler_47.dll
ffmpeg.dll
icudtl.dat
libEGL.dll
libGLESv2.dll
LICENSE.electron.txt
LICENSES.chromium.html
locales
resources
resources.pak
snapshot_blob.bin
swiftshader
v8_context_snapshot.bin
vk_swiftshader.dll
vk_swiftshader_icd.json
vulkan-1.dll
简悦 · 同步助手.exe
```

真实的程序文件是 `简悦 · 同步助手.exe`。

而在设置中设置开机自启，设置的是 `简悦 · 同步助手.exe` 而非压缩包  `简悦 · 同步助手 1.0.0.exe`，而前者是解压到了临时目录。如果临时目录被清理过，自然无法找到前者，也就无法运行。


问题2：
同步助手无法静默启动（即开机自启时），这个问题在 win 和 macos big sur上测试都如此。

这个建议给程序增加一个参数，比如 `/min` 之类，启动后直接最小化到托盘。

**Comment by Kenshin** [comment]
@binsee 

了解~ 

> 这个建议给程序增加一个参数，比如 `/min` 之类，启动后直接最小化到托盘。

靠谱的想法！ 👍

**Comment by Kenshin** [comment]
@binsee

嗨，有个事情想跟你聊下，方便给我 kenshin####ksria.com 发个邮件吗？或者加到 TG 群 https://t.me/simpreadgroup 找我私聊也行~

**Comment by zztt** [comment]
我遇到了简悦 同步助手启动时找不到ffmpeg.dll的情况，搜索看到这个issue，后续考虑把它解压缩后放在程序目录中。

**Comment by Kenshin** [comment]
> 我遇到了简悦 同步助手启动时找不到ffmpeg.dll的情况，搜索看到这个issue，后续考虑把它解压缩后放在程序目录中。

嗨，试试 32位 系统的，看看还有没有这个问题？

**Comment by Kenshin** [comment]
嗨，此问题也应该 Fixed 掉了。
