### ISSUE TITLE
代码块丢失

### ISSUE THREAD

**Issue by qiankunxienb** [Kenshin/simpread#1414]
- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://towardsdatascience.com/python-pitfalls-expecting-the-unexpected-2e595dd1306c>

**请描述你的问题**

使用阅读模式以后，文章中的代码块全部丢失。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/71627005/100111475-1913a280-2ea9-11eb-8937-d0d10382d9d2.png)

**Comment by Kenshin** [comment]
谢谢反馈，在某些页面确实会出现这样的问题，我会把它们统一记录到 #500 并关闭这个 Issues（因为类型相同的太多）

修复后我会在这里通知你。

**Comment by binsee** [comment]
这个站点的代码块是懒加载的一个嵌入页面，如下图：
![image](https://user-images.githubusercontent.com/5285894/100249004-11223400-2f77-11eb-972d-b7bfe3666b75.png)

简悦目前不支持处理嵌入页面，因为会产生性能问题。

**Comment by qiankunxienb** [comment]
感谢
