### ISSUE TITLE
mac 简悦同步助手 其他程序的command + w 快捷键无效

### ISSUE THREAD

**Issue by txgyy** [Kenshin/simpread#1415]
mac 简悦同步助手 其他程序的command + w 快捷键无效

**Comment by Kenshin** [comment]
因为我把这个快捷键暂时关闭了，它会 `抢占` 其它 App 的 `command + w`。

你可以使用 `command + q` 来关闭，或者 menubar 上的关闭方式。

**Comment by rayzhang2** [comment]
> 因为我把这个快捷键暂时关闭了，它会 `抢占` 其它 App 的 `command + w`。
> 
> 你可以使用 `command + q` 来关闭，或者 menubar 上的关闭方式。

是的，我也遇到这个问题。

【因为我把这个快捷键暂时关闭了，它会 `抢占` 其它 App 的 `command + w`】这句话不是很理解。

`command + w`是我最常用的快捷键，很顺手。今天发现打开同步助手就不能用了。很难受。
 `command + q` 在浏览器中会关闭整个窗口，而不是标签页。达不到`command + w`只关闭当前标签页的效果。

我希望能自定义APP的快捷键，防止抢占，十分感谢。

**Comment by rayzhang2** [comment]
目前我只能暂时关闭了同步助手。
但是Chrome 插件没关，访问每个页面都会出现这个提示：

![image](https://user-images.githubusercontent.com/61217850/100177195-90c6e900-2f0c-11eb-8fce-45a13e65fc67.png)

**Comment by Kenshin** [comment]
> 【因为我把这个快捷键暂时关闭了，它会 抢占 其它 App 的 command + w】这句话不是很理解。

原因的话，请看 https://github.com/Kenshin/simpread/issues/1390

***

> 我希望能自定义APP的快捷键，防止抢占，十分感谢。

会的。目前暂时只有 `打开稍后读` 是可以定制的。

***

> 目前我只能暂时关闭了同步助手

仅仅只是 `command + w` 无法使用，为什么需要关闭同步助手呢？`command + w` 不需要经常对同步助手使用。

能说下，经常使用 `command + w` 的意义吗？

***

至于截图的问题，可以解决的，因为你开了某个选项，但未开启同步助手而造成的问题，你可以在这里关闭它

![image](https://user-images.githubusercontent.com/81074/100188285-ddb6b980-2f24-11eb-81c7-53b78ff640e6.png)

**Comment by rayzhang2** [comment]
> 仅仅只是 `command + w` 无法使用，为什么需要关闭同步助手呢？`command + w` 不需要经常对同步助手使用。
> 
> 能说下，经常使用 `command + w` 的意义吗？


你好👋 下载新版本后，冲突的问题已解决。感谢！

我是多屏工作的，因为工作内容需要经常查阅各种资料。通常会打开多个Chrome浏览器窗口，每个窗口10几个标签页。
多年保持的习惯，是用 `command + t`开新标签页；用完了就顺手 `command + w`关闭。

前几天因为发现打开同步助手，这个快捷键就失效了。只能暂时先关闭同步助手。
又因为关闭了同步助手，简悦的chrome extension还开着，会不断提醒我“请确保已运行 同步助手”。
被这个问题困扰后来发帖的。

产品很赞，我会继续用的，加油啊开发者大大。

**Comment by Kenshin** [comment]
了解了。

另外，**如果你不是昨天下载的 简悦 · 同步助手**的话，也可以重新下载，新版修复了 Epub 导出错误。

***

PS：没有问题的话，我关闭此 Issues 了~  😃

**Comment by tcqiuyu** [comment]
在这下面跟问一下，我现在同步助手是1.0.1，快捷键是cmdorctrl+shift+N, 这个也经常是我新建文件夹或新建窗口的快捷键，想知道这个是不能自己定义吗？

**Comment by tcqiuyu** [comment]
> > 在这下面跟问一下，我现在同步助手是1.0.1，快捷键是cmdorctrl+shift+N, 这个也经常是我新建文件夹或新建窗口的快捷键，想知道这个是不能自己定义吗？
> 
> 嗨，可以自定义的
> 
> * 第一个 icon → 保存（修改完之后使用）
> * 第二个 icon → 删除全局快捷键
<img width="701" alt="Screen Shot 2022-03-26 at 8 19 13 PM" src="https://user-images.githubusercontent.com/6031166/160239155-430b0008-4c40-49fb-bac1-0c9bd69755f4.png">

奇怪啦，我这里没有显示任何图标

**Comment by tcqiuyu** [comment]
我的是mac版本

**Comment by Kenshin** [comment]
emmm 

试试开全局，可能 icon 的 Host 有点问题…

**Comment by tcqiuyu** [comment]
公司电脑behind proxy，可能是我这边的这个问题，所以这个icon不是存本地的嘛？

**Comment by Kenshin** [comment]
> icon不是存本地的嘛？

是的  😂

**Comment by tcqiuyu** [comment]
> 

我能在别的机器上设置好了再copy过来吗？这个设置是存在哪里的呀？

**Comment by Kenshin** [comment]
> 我能在别的机器上设置好了再copy过来吗？这个设置是存在哪里的呀？

因为同步助手的配置项比较少，所以暂时还没有导出和导入配置的功能。

你试试在我截图的右侧看看能否「忙猜」到 icon？因为即便无法显示 icon 但对应该的功能还是在的。

**Comment by tcqiuyu** [comment]
我点过啦，疯狂点，但都没有用哈哈

**Comment by Kenshin** [comment]
😂😂😂😂😂

换个电脑也顺道换个网络环境了吗？

**Comment by tcqiuyu** [comment]
> 

换个电脑就没有预装公司的vpn了呀哈哈，发愁，这咋办，是不是用不了了

**Comment by Kenshin** [comment]
> 换个电脑就没有预装公司的vpn了呀哈哈，发愁，这咋办，是不是用不了了

只能等下个版本「修复」了... 不过，你能修改 host 吗？我可以考虑修改 host 看看能否解决...

**Comment by tcqiuyu** [comment]
好，我去试试，谢谢！

**Comment by tcqiuyu** [comment]
修改了还是不行呢，但是我的chrome浏览器可以访问cdnjs.cloudflare.com，即使没有加这个host。这个icon是放在这个cdn上的吗？

还有个奇怪的点是每次打开同步助手，会有大概1m的卡顿，然后出现这个提示，我记得以前这种提示只会在第一次运行后出现，点了allow后面就不用再点了。
<img width="264" alt="Screen Shot 2022-03-28 at 8 11 08 PM" src="https://user-images.githubusercontent.com/6031166/160395045-c7eea4a3-c7a4-46a4-9479-eb42ad83bc29.png">
现

**Comment by Kenshin** [comment]
反复提示的解决方案 https://github.com/Kenshin/simpread/issues/2100#issuecomment-850217405

> 修改了还是不行呢，但是我的chrome浏览器可以访问cdnjs.cloudflare.com，即使没有加这个host。这个icon是放在这个cdn上的吗？

是的，我明天再确认下

**Comment by Kenshin** [comment]
确认了，确实使用了 `cdnjs.cloudflare.com` 你能否访问下面的链接？

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css

如果能的话，可能就不是这个问题了，是你的网络环境的问题。  😂

**Comment by Kenshin** [comment]
嗨，我昨天弄反了...

你可以试试正确的方式 https://github.com/Kenshin/simpread/issues/1415#issuecomment-1080505968

**Comment by tcqiuyu** [comment]
哈哈，我想着也是的，重启之后，我可以显示了！谢谢！

**Comment by Kenshin** [comment]
> 哈哈，我想着也是的，重启之后，我可以显示了！谢谢！

 👏  忒不容易了，搞定就好。这也算是我遇到过比较奇怪的疑难杂症了（之一）...

***

不在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 

给个五星好评 + 评价，都对不起我这个 QA 时间。  😂

**Comment by tcqiuyu** [comment]
必须的！这就去哈哈哈哈

**Comment by tcqiuyu** [comment]
抱歉，发现之前已经给过了哇哈哈哈哈

**Comment by Kenshin** [comment]
> 抱歉，发现之前已经给过了哇哈哈哈哈

哈哈，那我吃亏了~  🙏  💪  👏
