### ISSUE TITLE
epub 导出失败，本地已安装 pandoc

### ISSUE THREAD

**Issue by JimmyLv** [Kenshin/simpread#1416]
![image](https://user-images.githubusercontent.com/4997466/100175182-dc779380-2f08-11eb-9874-285bc44e6dd1.png)

![image](https://user-images.githubusercontent.com/4997466/100175141-cec20e00-2f08-11eb-818b-94aa5b546299.png)

还是忍不住想说，产品易用性真的太差了，唉 😌

太多地方值得吐槽，比如这个「同步助手」的设置，这么小的一个折叠项，找了半天

而且每次改了设置，还得重新点一遍「保存配置文件」才能生效，又是反复折腾好几遍。

![image](https://user-images.githubusercontent.com/4997466/100175258-fc0ebc00-2f08-11eb-8b45-f924ad4a517b.png)

真心觉得 简悦的配置，完全跟「简于型，悦于心」的 slogan 大相径庭。

期望 UI 真的该做减法了，而不是无止境的加法，对新用户、甚至老用户都太不友好了。

比如说，我有看到了作者努力做了很多可交互的「新手引导」，下一步、下一步、下一步。

但这种加法完全是本末倒置，因为产品难用，才不得已亲自上场做额外工作来教用户用？

另一条路，应该是直接简化产品，让用户可以用一种最直观的方式使用，还用得着教吗？

**Comment by JimmyLv** [comment]
![CleanShot 2020-11-25-10-26-31](https://user-images.githubusercontent.com/4997466/100176678-b8698180-2f0b-11eb-81e6-a3bb65e6d904.gif)

**Comment by Kenshin** [comment]
嗨，Epub 导出失败，我正在 Check，有可能是特殊标题造成的，你可以试试其它文章或者安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**至于为什么存在这个问题，我稍后会给你回复。**

***

另外至于易用性的问题，迟早是会解决的，但毕竟精力有限，目前只能放在最重要的事情上，虽然我也明白其中的道理。

***

配置的问题目前能做到：一次配置，无需再次改动。

**Comment by Kenshin** [comment]
> Epub 导出失败的问题

此问题已解决，请重新 下载 Mac 版 → [坚果云](https://www.jianguoyun.com/p/DdXeyasQwobGBxjK7c0D)

另外，请确保如下设置无误：请确保 pandoc 在你的 `/usr/local/bin/` 目录下存在，同时也确保此目录在 `$PATH` 下。

`which pandoc` → 查看 pandoc 所在目录

PS：一般使用 `pandoc-xxx-macOS.pkg` 安装的话，自然是 `/usr/local/bin/` 目录。

***

下个版本会包含 `pandoc` 定制化目录功能

**Comment by Kenshin** [comment]
补充下：因为目录有可能包含特殊字符，所以也请安候 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by Kenshin** [comment]
> 比如这个「同步助手」的设置，这么小的一个折叠项，找了半天

下个版本会优化界面上的问题。

***

> 而且每次改了设置，还得重新点一遍「保存配置文件」才能生效

应该不会存在这个问题。

![image](https://user-images.githubusercontent.com/4997466/100175258-fc0ebc00-2f08-11eb-8b45-f924ad4a517b.png)

截图中第二个红框这里，仅在开启自动同步后需要使用（也可以不用使用）

除此以外，应该不会存在反复多次点击的情况。（如果有的话，请指出）

***

目前的产品逻辑是有点糙，但提供的功能是实打实的，等这个版本稳定下来后，我会重构它。

***

希望还是可以多用用 **每日回顾** 等更有意义的功能上，**请再忍受一小段时间，这些问题都是可以解决的**。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
