### ISSUE TITLE
微信公众号导出PDF无图片，显示“此图片来自公众平台，未经允许不可引用”

### ISSUE THREAD

**Issue by Markwongs** [Kenshin/simpread#1418]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
emmm 这是个问题，因为微信订阅号的防盗链机制造成的。

我先记 Bug，有办法解决，但目前 2.1 暂时无法解决这个事情。

**Comment by zhuxiucai** [comment]
> emmm 这是个问题，因为微信订阅号的防盗链机制造成的。
> 
> 我先记 Bug，有办法解决，但目前 2.1 暂时无法解决这个事情。


hi，防盗链我2021年11月23日15:25:25又体验到了，之前正常使用半年了。

**Comment by Kenshin** [comment]
@zhuxiucai 

给个 URL 看看。

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
