### ISSUE TITLE
高级账号: 希望提供一键撤销之前所有设备授权的方案

### ISSUE THREAD

**Issue by hikerpig** [Kenshin/simpread#1419]
换电脑的时候忘了撤销旧设备的授权，现在电脑公司已经回收，这样我的一个设备名额就一直被它占着了。

不知道这个请求是不是有点过分...

**Comment by Kenshin** [comment]
并不过分，你可以在 https://simpread.pro/account 操作。

但有个限制条件：**每周只能使用一次** 这个方式。

**Comment by hikerpig** [comment]
已成功操作，感谢回复。
这个操作我好像没在帮助文档里看到，以为自助平台只是用来找回 UUID 的。

**Comment by Kenshin** [comment]
> 已成功操作，感谢回复。这个操作我好像没在帮助文档里看到

谢谢「自救成功」 https://simpread.pro/help 里面应该有，目前 2.1 版下面有些说明性文字

![image](https://user-images.githubusercontent.com/81074/100204777-414de080-2f3f-11eb-9cf3-3993921248c0.png)

**Comment by hikerpig** [comment]
我不太确定“账户被锁定”与我的情况是否吻合，因为我不是两台电脑**同时**操作导致的账号锁定，而是无法解除某个之前的设备的授权。通读文档下来，感觉这两个概念还是不太一样的？

**Comment by hikerpig** [comment]
![image](https://user-images.githubusercontent.com/2259688/100224982-892d3180-2f58-11eb-93b1-9423707a488e.png)
这才发现这个页面的确有。不过我是通过插件右键菜单进入的 docs http://ksria.com/simpread/docs/#/ ，没有看到哈...

**Comment by Kenshin** [comment]
> 我不太确定“账户被锁定”与我的情况是否吻合，因为我不是两台电脑**同时**操作导致的账号锁定，而是无法解除某个之前的设备的授权。通读文档下来，感觉这两个概念还是不太一样的？

谢谢能「自主思考」，你要知道，有太多用户不懂如何看文档了…

至于你说的问题，确实如此，但逻辑上都是一样的，都是一键退出全部设备。

**Comment by willsyangtx** [comment]
我在 https://simpread.pro/account 操作了解除所有绑定，但是重开浏览器想用licence重新绑定显示：此密钥已被使用。这是怎么回事啊？

**Comment by Kenshin** [comment]
@willsyangtx 

我的回复请看 https://github.com/Kenshin/simpread/discussions/1569#discussioncomment-707211
