### ISSUE TITLE
可不可以支持使用chrome打开本地TXT阅读

### ISSUE THREAD

**Issue by ZGMF-X42S** [Kenshin/simpread#142]
此插件阅读体验非常好，如果能支持本地TXT，那么可以替代所有的阅读软件了。

P.S.问下使用的字体是什么，之前用的SONY 手机也是类似字体，读小说很方便

**Comment by Kenshin** [comment]
感谢反馈~

好想法  👍  👏  

我刚刚简单的实验了下，发现效果还不错。下个版本会支持此功能！

![image](https://user-images.githubusercontent.com/81074/31871467-24d45802-b77a-11e7-81ec-4c644a0141ce.png)

不过，在 Chrome 读 txt 的需求比较少吧...

字体的话，要看你用了什么系统了。

- Mac 下默认应该是 `PingFang SC`
- Win 下默认应该是 `Microsoft Yahei`

当然，还做了其它的一些设置，比如字体平滑等。

**Comment by ZGMF-X42S** [comment]
哈哈，期待更新，在调试中看到了，同时发现了很多大爱的英文字体。
Microsoft Yahei Light 很不错，手机也替换成了相仿的方正兰亭刊黑，很久前索爱手机就差不多是这种字体大爱。

**Comment by ZGMF-X42S** [comment]
另外我也是在看东野圭吾  的小说想到的。。。

**Comment by Kenshin** [comment]
索爱…
好久远的名字，当年的第二款手机就是它，第一款是阿尔卡。
发现都黄了… 😂😱

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，已增加此功能，此 issues 将会关闭。
TXT 阅读器的详细说明请看 http://ksria.com/simpread/welcome/version_1.0.5.html#read-txt

感谢建议~

**Comment by L-QF** [comment]
![image](https://user-images.githubusercontent.com/58257723/87219442-b56f5980-c38d-11ea-95f4-4b32a0ac38a3.png)为什么我的txt不能显示阅读

**Comment by Kenshin** [comment]
@L-QF 

打开 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 并勾选 **允许访问文件网址**
