### ISSUE TITLE
阅读模式的时候旁边的侧边栏没有了？？？怎么调出来？？？

### ISSUE THREAD

**Issue by 1198560751** [Kenshin/simpread#1423]
![image](https://user-images.githubusercontent.com/57899844/100200452-98e94d80-2f39-11eb-9e1e-0d5485125fe8.png)

**Comment by 1198560751** [comment]
就是这个侧边栏，但是我有一个网页没有侧边栏，其他的都有，怎么把那一个网页的侧边栏打开，刚开始是有的，然后退出阅读模式再打开就没了？？？
![image](https://user-images.githubusercontent.com/57899844/100200715-f4b3d680-2f39-11eb-98ae-48084855d32f.png)

**Comment by Kenshin** [comment]
谢谢反馈。

因为你的反馈信息很少，我没办法判断。
显示侧栏的前提是：当前页面已经加入了稍后读。

***

> 刚开始是有的，然后退出阅读模式再打开就没了

造成这个原因有很多，但一般来说，是当前这个页面的配置被覆盖了。

**Comment by 1198560751** [comment]
> 谢谢反馈。
> 
> 因为你的反馈信息很少，我没办法判断。
> 显示侧栏的前提是：当前页面已经加入了稍后读。
> 
> > 刚开始是有的，然后退出阅读模式再打开就没了
> 
> 造成这个原因有很多，但一般来说，是当前这个页面的配置被覆盖了。

怎么可以恢

> 谢谢反馈。
> 
> 因为你的反馈信息很少，我没办法判断。
> 显示侧栏的前提是：当前页面已经加入了稍后读。
> 
> > 刚开始是有的，然后退出阅读模式再打开就没了
> 
> 造成这个原因有很多，但一般来说，是当前这个页面的配置被覆盖了。

怎么可以恢复？？？把侧边栏调出来？？？

**Comment by 1198560751** [comment]
> > 谢谢反馈。
> > 因为你的反馈信息很少，我没办法判断。
> > 显示侧栏的前提是：当前页面已经加入了稍后读。
> > > 刚开始是有的，然后退出阅读模式再打开就没了
> > 
> > 
> > 造成这个原因有很多，但一般来说，是当前这个页面的配置被覆盖了。
> 
> 怎么可以恢
> 
> > 谢谢反馈。
> > 因为你的反馈信息很少，我没办法判断。
> > 显示侧栏的前提是：当前页面已经加入了稍后读。
> > > 刚开始是有的，然后退出阅读模式再打开就没了
> > 
> > 
> > 造成这个原因有很多，但一般来说，是当前这个页面的配置被覆盖了。
> 
> 怎么可以恢复？？？把侧边栏调出来？？？
当前页面已经加入了稍后读
![image](https://user-images.githubusercontent.com/57899844/100202490-570dd680-2f3c-11eb-9fe1-14772c7cc9ba.png)

**Comment by 1198560751** [comment]
当前页面已经加入了稍后读，里面没有侧边栏？怎么可以恢复侧边栏？？？

**Comment by Kenshin** [comment]
> 当前页面已经加入了稍后读，里面没有侧边栏？怎么可以恢复侧边栏？？？

你是说这个下图的页面没有侧栏如何回复？

![image](https://user-images.githubusercontent.com/57899844/100202490-570dd680-2f3c-11eb-9fe1-14772c7cc9ba.png)

如果是的话，请使用下面的方式

![image](https://user-images.githubusercontent.com/81074/100203429-8cff8a80-2f3d-11eb-88cd-9c7c3bacf4e7.png)

**Comment by 1198560751** [comment]
> > 当前页面已经加入了稍后读，里面没有侧边栏？怎么可以恢复侧边栏？？？
> 
> 你是说这个下图的页面没有侧栏如何回复？
> 
> ![image](https://user-images.githubusercontent.com/57899844/100202490-570dd680-2f3c-11eb-9fe1-14772c7cc9ba.png)
> 
> 如果是的话，请使用下面的方式
> 
> ![image](https://user-images.githubusercontent.com/81074/100203429-8cff8a80-2f3d-11eb-88cd-9c7c3bacf4e7.png)


现在就是在这个阅读模式，这个侧边栏没有了，应该怎么调出来？？？

![image](https://user-images.githubusercontent.com/57899844/100203750-f67f9900-2f3d-11eb-8e1b-d39fb1175b04.png)

**Comment by 1198560751** [comment]
> > > 当前页面已经加入了稍后读，里面没有侧边栏？怎么可以恢复侧边栏？？？
> > 
> > 
> > 你是说这个下图的页面没有侧栏如何回复？
> > ![image](https://user-images.githubusercontent.com/57899844/100202490-570dd680-2f3c-11eb-9fe1-14772c7cc9ba.png)
> > 如果是的话，请使用下面的方式
> > ![image](https://user-images.githubusercontent.com/81074/100203429-8cff8a80-2f3d-11eb-88cd-9c7c3bacf4e7.png)
> 
> 现在就是在这个阅读模式，这个侧边栏没有了，请问应该怎么调出来？？？
> 
> ![image](https://user-images.githubusercontent.com/57899844/100203892-24fd7400-2f3e-11eb-98bc-7738d53ae70b.png)

**Comment by Kenshin** [comment]
emmm 你看看 DevTools  是不是有报错。

**Comment by Kenshin** [comment]
你随便找个页面，然后加入稍后读，看看侧栏是否可以出现？

**Comment by 1198560751** [comment]
DevTools ：显示是有报错
![image](https://user-images.githubusercontent.com/57899844/100204860-5a569180-2f3f-11eb-983e-acf466a53374.png)
随便找个页面，然后加入稍后读，侧栏是可以出现的。这个页面我做了一些标注，然后侧边栏没了，也找不到，请问应该怎么调出来？？？

**Comment by Kenshin** [comment]
> 这个页面我做了一些标注，然后侧边栏没了，也找不到，请问应该怎么调出来？？？

你打开原页面看看能否显示侧栏。（如果也不能的话，说明是 Bug，方便的话把配置文件发到这里或者给我邮件，发的时候可以把配置文件中的 UID 删除。（以免爆 ID

然后我重开这个 Issues
