### ISSUE TITLE
github的issue页面可不可以支持一下导出pdf呢 ?  

### ISSUE THREAD

**Issue by yukminnie** [Kenshin/simpread#1424]
比如下面这个页面:

https://github.com/iissnan/hexo-theme-next/issues/47

1, 第一次点击提示获取异常, 是否重新获取

2, 点击重新获取后 , 页面和原来没有丝毫关系了, 变成了这样

![Xnip2020-11-25_18-36-39.png](https://i.loli.net/2020/11/25/8Jv6k2xRumOMXw1.png)

**Comment by Kenshin** [comment]
这个属于 适配站点 的问题，即：当前页面识别正文失败。

简悦的 PDF 是在阅读模式下才能使用的功能，换句话说，这个页面因为没有需要识别的正文而失败。

例如这个页面 https://github.com/iissnan/hexo-theme-next/issues/47 是可以成功导出 PDF 的。

**Comment by yukminnie** [comment]
好吧, 我是想获取下面的回复来着, 谢谢老哥了👍🏻.

**Comment by Kenshin** [comment]
你可以用重新高亮框选你需要的任意部分。
就应该可以使用 PDF 了。
