### ISSUE TITLE
bug反馈：插件失灵

### ISSUE THREAD

**Issue by Bend1031** [Kenshin/simpread#1425]
**发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Chrome  87.0.4280.66**

- 简悦版本 **2.1.0**

**发生的问题**

> 插件失灵，在阅读模式下没有见到有关插件的任何信息

**截图**

![image](https://user-images.githubusercontent.com/40395487/100217258-39496d00-2f4e-11eb-8d78-72f582908afb.png)
图中显示插件已经开启，但是没有见到主动使用的按钮。

**扩展程序窗口开发者模式下显示的错误**
不知道是否和问题有关，仅供参考。
![image](https://user-images.githubusercontent.com/40395487/100217597-9cd39a80-2f4e-11eb-85a1-c934bad31bbf.png)

**Comment by Bend1031** [comment]
![image](https://user-images.githubusercontent.com/40395487/100219371-e02f0880-2f50-11eb-9520-72fe695de207.png)
同时没有插件触发器选项的出现

**Comment by Kenshin** [comment]
谢谢详细的反馈信息。

***

> 扩展程序窗口开发者模式下显示的错误

跟这个无关

***

> ![image](https://user-images.githubusercontent.com/40395487/100219371-e02f0880-2f50-11eb-9520-72fe695de207.png)
> 同时没有插件触发器选项的出现

点击它有什么反映？另外排除法试试安装 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 然后进入阅读模式，看是否生效？

**Comment by Bend1031** [comment]
> > ![image](https://user-images.githubusercontent.com/40395487/100219371-e02f0880-2f50-11eb-9520-72fe695de207.png)
> > 同时没有插件触发器选项的出现
> 
> 点击它有什么反映？另外排除法试试安装 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 然后进入阅读模式，看是否生效？

这个图标是我在edge上测试的时候会出现，在chrome上并没有此图标。

此外安装 模仿Safari样式插件 后并没有显示新的东西，也就是插件无效。

**Comment by Bend1031** [comment]
![image](https://user-images.githubusercontent.com/40395487/100226263-7156ad00-2f5a-11eb-96b9-a776b72eefcb.png)

Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Kenshin** [comment]
请问你是什么浏览器？并告知版本。

如果不是 Chrome 原版的话，能否试试原版？过或 Edge ，并确保不要更改任何浏览器本身的配置。

除此之外，在隐身模式下，仅启用简悦，试试。（排除其它扩展导致的问题）

**Comment by Bend1031** [comment]
Google Chrome 87.0.4280.66

Edge 87.0.664.47 下测试，插件可以正常使用

Google Chrome 隐身模式下，插件依旧无法生效

**Comment by Kenshin** [comment]
emmm...

你在选项页 → 插件管理 → 删除全部插件，然后再重新安装随便一个。

怀疑是配置出现了问题导致。

**Comment by Bend1031** [comment]
还是没用😂

**Comment by Bend1031** [comment]
最新发现是退出账户后清除所有设置，再单独启用插件的话是能够正常使用的。

所以是配置的问题？😂

**Comment by Kenshin** [comment]
@Bend1031 

> 退出账户后清除所有设置，再单独启用插件的话是能够正常使用的。

应该属于 **隐性 Bug** 造成的，一般来说这种问题都无法稳定复现，同时也能规避掉。

所以，你能使用你自己的数据并绕过这个问题吗？

**Comment by Bend1031** [comment]
最后还是通过重新下载安装，重新设置，而不是导入配置文件，所以暂时应该是解决了。

Thanks!

**Comment by Kenshin** [comment]
okay

那先这样，如果以后复现的话，请再重开这个 Issues ~

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
