### ISSUE TITLE
保存到为知笔记时每次重启浏览器都会显示授权已过期

### ISSUE THREAD

**Issue by est7** [Kenshin/simpread#1426]
然后三秒自动重新授权后就可以正常保存了。以为是cookie问题，清理后还是这样，请问这是正常现象吗？

**Comment by HJCFLY** [comment]
我保存OneNote时也是这个问题

**Comment by Kenshin** [comment]
@HJCFLY 

看到你的名字发现，我在少数派回复你了。以下是回复内容：

> 嗨，我刚刚测试了下，Onenote 是可以重新授权的，授权完成后再次点击导入 Onenote 就可以了。

***

@est7 

应该是正常的，为知笔记使用了私有 API 所以不会那么稳定。（ 我的为知笔记到期了，没办法帮你重试...  😅

**Comment by est7** [comment]
@Kenshin 您目前剪藏用的是？能把图片一并上传的笔记类应用试过的只有wiz，notion。notion太慢还有5m限制，虽然wiz已经不太更新了，但是做收集箱用还没发现更好的。

**Comment by Kenshin** [comment]
为知笔记确实不错的，你可以看看这篇文章，是关于各种生产力工具的横向对比。

**Comment by east4ming** [comment]
![image](https://user-images.githubusercontent.com/13358726/103117213-58016780-46a4-11eb-8d2c-719ea5ef6d0a.png)
我的也是这样的情况. 一段时间不用简悦, 即使没有重启过浏览器, 也会提示为知笔记授权过期. 并且跳转到设置页面, 再次自动授权成功.

不影响使用, 但是反复跳转, 影响体验.

**Comment by Kenshin** [comment]
@east4ming 

嗨，因为为知笔记的授权时间较短造成的（这不是简悦的问题）

**Comment by east4ming** [comment]
收到. 谢谢!
那体验确实不太好.
如果是用为知笔记的话, 是不是也可以通过邮件的方式发送啊?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 晚上8:18
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"凯西Casey"<cuikaidong@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 保存到为知笔记时每次重启浏览器都会显示授权已过期 (#1426)





 
@east4ming
 
嗨，因为为知笔记的授权时间较短造成的（这不是简悦的问题）

**Comment by Kenshin** [comment]
@east4ming 

> 是不是也可以通过邮件的方式发送

什么意思？

**Comment by east4ming** [comment]
通过邮件的方式发送到为知笔记:&nbsp;xxxx@mywiz.cn




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 晚上10:32
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"凯西Casey"<cuikaidong@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 保存到为知笔记时每次重启浏览器都会显示授权已过期 (#1426)





 
@east4ming
  
是不是也可以通过邮件的方式发送
  
什么意思？
