### ISSUE TITLE
已成功绑定高级账号，但无法使用，依然有🔒

### ISSUE THREAD

**Issue by Unitary-orz** [Kenshin/simpread#1427]
![Jietu20201126-085118@2x](https://user-images.githubusercontent.com/34275074/100295493-bca5a580-2fc4-11eb-8fc5-82e22ef070e9.jpg)
每次都会弹出高级账户介绍，然后点击获取所有权益，会转到账户界面，但显示我是高级会员
已经重启过浏览器了
![Jietu20201126-085259@2x](https://user-images.githubusercontent.com/34275074/100295742-4ce3ea80-2fc5-11eb-91c1-2cf1f3b1e307.jpg)
![Jietu20201126-085317@2x](https://user-images.githubusercontent.com/34275074/100295751-53726200-2fc5-11eb-8c53-d87ffc6854f5.jpg)

**Comment by Kenshin** [comment]
很奇怪的问题，请问你的这个账户被锁过吗？还是刚刚使用？

另外看下 选项页 → 右上角的登录状态是否如下图所示

![image](https://user-images.githubusercontent.com/81074/100296366-f8416f00-2fc6-11eb-9517-d66627ef729a.png)


如果是的话，选择 **仅授权当前设备** 看能否解决？

**Comment by Unitary-orz** [comment]
确实才刚刚开始使用，`仅授权当前设备`后就解决了，谢谢
