### ISSUE TITLE
设置页面文字有歧义

### ISSUE THREAD

**Issue by jerry011235** [Kenshin/simpread#143]
是否关闭手动聚焦模式？  应改为  是否打开手动聚焦模式？

switch-rang滑到右边，进入某个不适配的网站（如https://www.v2ex.com/ ），图标灰色，点击选中 聚焦模式，可以开启 手动聚焦模式。

另，还是没有实现：
3.能否像 [愉阅](https://chrome.google.com/webstore/detail/happyreader/emjphcoeoofohgimppddgblomjbojnnh) 一样，如果页面有“第二页”字样，能自动提取下一页内容。

**Comment by Kenshin** [comment]
> 是否关闭手动聚焦模式？ 应改为 是否打开手动聚焦模式？

应该如你所说，下个版本会改善...  😣 

> 能否像 愉阅 一样，如果页面有“第二页”字样，能自动提取下一页内容。

应该不太会实现了，或者说 `优先级` 较低。
一般这类的页面大多类似 小说类 网站，如果是的话，建议使用另外一个油猴脚本 https://greasyfork.org/zh-CN/scripts/292-my-novel-reader  更完美的支持小说类网站。

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，修复此问题，此 issues 将会关闭。
