### ISSUE TITLE
知乎文章导入Onenote和Notion出现问题。

### ISSUE THREAD

**Issue by HJCFLY** [Kenshin/simpread#1430]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

系统：win10
浏览器：Google Chrome 版本 86.0.4240.198（正式版本） （64 位）
简悦版本 2.1（最新）

首先是：Onenote需要经常重新授权，其次是笔记导入Onenote后部分图片显示不出来。导入Notion后排版混乱。
知乎文章：https://zhuanlan.zhihu.com/p/63103354
Onenote效果：
![image](https://user-images.githubusercontent.com/38662362/100300282-a00f6a80-2fd0-11eb-9761-d4d44ff2528b.png)
Notion效果：
![image](https://user-images.githubusercontent.com/38662362/100300313-b3223a80-2fd0-11eb-9563-1adfba83b153.png)

**Comment by HJCFLY** [comment]
系统：win10
浏览器：Google Chrome 版本 86.0.4240.198（正式版本） （64 位）
简悦版本 2.1（最新）

**Comment by Kenshin** [comment]
> Onenote 重新授权的问题

这是正常的，请看 https://github.com/Kenshin/simpread/issues/1426#issuecomment-734036168 的说明

> 图片无法显示的问题

猜测是因为缓存之类的问题，我记得也有其他用户遇到过

> Notion效果：

这不是简悦的问题，你可以导出 Markdown 看看效果，Notion 并未支持的 Markdown 并不是完全版。

下图是我导出 Markdown 的效果

![image](https://user-images.githubusercontent.com/81074/100301273-c8986400-2fd2-11eb-8c78-ee379f977f88.png)

**Comment by Kenshin** [comment]
另外，我看了下你提交的版本，请升级到 2.1.0 版本（ Onenote 的问题确实存在于 2.0 版，至于原因也在 https://zhuanlan.zhihu.com/p/63103354 说明了。

**Comment by HJCFLY** [comment]
好的。谢谢。我的简悦已经是2.1.0了。在2.0之前我觉得简悦对Onenote支持很好的啊，现在这种图片显示不出来的问题我该怎么解决呢？sorry啊 ，这问题你在少数派的回复我没看懂

**Comment by HJCFLY** [comment]
我试了一下，导出Markdown效果正常的，可是再把Markdown导入Notion的效果，和从简悦直接导入到Notion里的效果是一样的。都是忽大忽小，太难了

**Comment by Kenshin** [comment]
> 我试了一下，导出Markdown效果正常的，可是再把Markdown导入Notion的效果，和从简悦直接导入到Notion里的效果是一样的。都是忽大忽小，太难了

哈哈，当然了，这是一定的。（导入到 Notion 其实就是 Markdown 导入而已）但我也说过了，这不是简悦的问题。 😅 

***



> 好的。谢谢。我的简悦已经是2.1.0了。在2.0之前我觉得简悦对Onenote支持很好的啊，现在这种图片显示不出来的问题我该怎么解决呢？sorry啊 ，这问题你在少数派的回复我没看懂

emmm 你稍后一段时间看看能否加载出来？或者试试其它页面，如少数派的页面。

PS：既然用过1.x 版的话，我就必须 **解释两句** 了，这个问题不是简悦造成的，跟 Notion 的锅是一个道理。 😅

**Comment by HJCFLY** [comment]
不行哦 还是加载不出来，我将就着用吧

**Comment by Kenshin** [comment]
> 不行哦 还是加载不出来，我将就着用吧

emmm 我明天确认下。

**Comment by Kenshin** [comment]
嗨，你那边正常了吗？

**Comment by HJCFLY** [comment]
sorry啊  不行哦  我觉得这个和公式有关。
Notion，一有公式就会是那样，而且Notion还把其他正常的图片给省略了，我也不知道为啥。
![image](https://user-images.githubusercontent.com/38662362/100517180-e4af2780-31c3-11eb-88ad-811244cf056e.png)
以下是Onenote的图
![image](https://user-images.githubusercontent.com/38662362/100517256-4a9baf00-31c4-11eb-9875-75c9ffbf303c.png)
以下是正常的图
![image](https://user-images.githubusercontent.com/38662362/100517265-5c7d5200-31c4-11eb-9b0d-b86fef0b8b60.png)

**Comment by Kenshin** [comment]
@HJCFLY 

嗨，之前已经说过了，Notion 是无法成功导入包含 Latex 的页面，你可以试试导入 Markdown 也是如此。这不是简悦的问题，而是 Notion 本身的限制。 😅

**Comment by HJCFLY** [comment]
哦 意思是 只要他是用Latex编辑的 就会出问题，Onenote也是同样的原理？

**Comment by Kenshin** [comment]
> 哦 意思是 只要他是用Latex编辑的 就会出问题，Onenote也是同样的原理？

是的，因为大多数的笔记类 App 都无法完美的显示 LateX 的结构，目前从简悦支持的服务来看，比较好的是 **为知笔记**，但是导入后无法编辑。

除此以外，建议试试 Joplin 这个服务也可以完美的显示。

***

多提一句：Onenote Notion 虽然都属于笔记类 App 但它们并不擅长收集。（非要说收集的话，最好的方式还是 **离线 HTML**，此方式也不是 100% 完美。

**Comment by HJCFLY** [comment]
哦 好嘞 谢谢 那这个问题我们以后有可能解决吗?还是说只能等Onenote Notion 它们改变？

**Comment by Kenshin** [comment]
@HJCFLY 

目前只能等它们，我没有什么好办法。（这超出了简悦的范畴。 😅

**Comment by HJCFLY** [comment]
哦 好的吧 谢谢

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
