### ISSUE TITLE
sciencedirect.com 网页加载不全

### ISSUE THREAD

**Issue by chliuhq** [Kenshin/simpread#1440]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://www.sciencedirect.com/science/article/pii/S095965262033136X?via%3Dihub>

**只能显示一小部分网页**

**Comment by Kenshin** [comment]
嗨，我刚测试了下。
这个页面应该可以的（虽然排版感觉不是很好），方便的话，建议给我截图并指出哪里缺少了。

**Comment by Kenshin** [comment]
嗨，我在五一期间适配了这个网站，除此之外还包括以下几种常见的科研类页面。

- [https://www.sciencedirect.com/](https://www.sciencedirect.com/)
- [https://www.ncbi.nlm.nih.gov/](https://www.ncbi.nlm.nih.gov/)
- [https://journals.biologists.com/](https://journals.biologists.com/)
- [https://www.cell.com/cell/home](https://www.cell.com/cell/home)
- [https://elifesciences.org/](https://elifesciences.org/)
- [https://www.pnas.org/](https://www.pnas.org/)
- [https://science.sciencemag.org/](https://science.sciencemag.org/)
- [https://www.nature.com/]()
- https://www.frontiersin.org/journals

#### 特点

> 简悦适配的这些科研期刊，并不是 **简单的将正文提取出来**，而是 **根据学术文章一般有固定的格式**，如：`title` `abstract` `results` `discussions` `methods` `references` `acknowledgements` `highlights` 进行适配的。

所以，满足一般科研期刊的使用规律，且可显示 **数学公式 LateX** 等仅 **简悦的阅读模式独有的功能**。

#### 如何更新

> 请看 [官方适配源](http://ksria.com/simpread/docs/#/站点适配源?id=官方适配源)，更新后可打开 [这些示例网站](https://github.com/Kenshin/simpread/discussions/2103) 后进入阅读模式查看。

***

关于这部分的说明（以及如何使用）请前往 👉  [https://github.com/Kenshin/simpread/discussions/2103](https://github.com/Kenshin/simpread/discussions/2103) 查看详细说明。
