### ISSUE TITLE
关于坚果云 同步，登录 js 报错,无法登录

### ISSUE THREAD

**Issue by yyw92** [Kenshin/simpread#1441]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **e.g. Chrome 87.0.4280.67**

- 简悦版本 **2.1.0**

- 发生问题的地址
坚果同步:chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common 
坚果账户icon 登录

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/20991960/100432773-05e51a80-30d5-11eb-83a2-65701608469a.png)
![image](https://user-images.githubusercontent.com/20991960/100432942-43e23e80-30d5-11eb-8f9b-1b0153ae0fa8.png)

**Comment by Kenshin** [comment]
这个错误跟坚果云登录无关。
请问你是无法登录，还是什么？有什么提示吗？

**Comment by yyw92** [comment]
第一次使用，我直接根据文档去注册坚果云，然后去绑定，一直转圈圈，和登录无提示，不知道是不是其它默的配置问题。
我又重新去试了下， 本地配置都清除了。 在浏览器关掉。重新去操作， 现在绑定上了。

**Comment by Kenshin** [comment]
👌
恭喜「自救」成功，因为给出的信息不多，所以没办法帮忙 check 😂
不过，我从未遇到过这样的问题。

你再后续留意下，有需要再重开它。
