### ISSUE TITLE
新站适配 sciencedirect.com

### ISSUE THREAD

**Issue by chliuhq** [Kenshin/simpread#1446]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://www.sciencedirect.com/science/article/pii/S0022169405002726>

**阅读模式出来只占半屏，而且为什么会打开个网页就自动跳转？？！！！设置里边也找不到怎么关，也没法调**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

![image](https://user-images.githubusercontent.com/38576927/100496720-2ffc1280-3191-11eb-8eea-fa33cbf5965d.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
这个问题与 https://github.com/Kenshin/simpread/issues/1440 类似，都是因未适配而造成的问题。

PS：不过我确实没有遇到截图中的情况，能稳定复现吗？

***

因为类型相似，所以我关闭了 https://github.com/Kenshin/simpread/issues/1440 了，仅在这里讨论。

**Comment by Kenshin** [comment]
不过，也请留意下 #1440 的这个疑问 https://github.com/Kenshin/simpread/issues/1440#issuecomment-735039916

**Comment by Kenshin** [comment]
嗨，我在五一期间适配了这个网站，除此之外还包括以下几种常见的科研类页面。

- [https://www.sciencedirect.com/](https://www.sciencedirect.com/)
- [https://www.ncbi.nlm.nih.gov/](https://www.ncbi.nlm.nih.gov/)
- [https://journals.biologists.com/](https://journals.biologists.com/)
- [https://www.cell.com/cell/home](https://www.cell.com/cell/home)
- [https://elifesciences.org/](https://elifesciences.org/)
- [https://www.pnas.org/](https://www.pnas.org/)
- [https://science.sciencemag.org/](https://science.sciencemag.org/)
- [https://www.nature.com/]()
- https://www.frontiersin.org/journals

#### 特点

> 简悦适配的这些科研期刊，并不是 **简单的将正文提取出来**，而是 **根据学术文章一般有固定的格式**，如：`title` `abstract` `results` `discussions` `methods` `references` `acknowledgements` `highlights` 进行适配的。

所以，满足一般科研期刊的使用规律，且可显示 **数学公式 LateX** 等仅 **简悦的阅读模式独有的功能**。

#### 如何更新

> 请看 [官方适配源](http://ksria.com/simpread/docs/#/站点适配源?id=官方适配源)，更新后可打开 [这些示例网站](https://github.com/Kenshin/simpread/discussions/2103) 后进入阅读模式查看。

***

关于这部分的说明（以及如何使用）请前往 👉  [https://github.com/Kenshin/simpread/discussions/2103](https://github.com/Kenshin/simpread/discussions/2103) 查看详细说明。

***

没问题的话，请关闭此 Issues ~
