### ISSUE TITLE
求适配以下blog，多谢~

### ISSUE THREAD

**Issue by jianshanbushishan** [Kenshin/simpread#145]
https://coolshell.cn/
https://blog.codingnow.com/

另外，提几个小建议：
1. 希望能自己设置阅读模式时显示的宽度，个人感觉窄栏下依然比较宽。
2. 希望能在右键菜单加入保存到稍后读
3. 希望稍后读的列表能同步

**Comment by Kenshin** [comment]
ok，不过，你可以用 `临时阅读模式` ，我刚刚看了下，效果基本上没有问题。

**Comment by Kenshin** [comment]
已适配~   
请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
