### ISSUE TITLE
请问Kenshin大大，何时会上线Linux下的同步助手？

### ISSUE THREAD

**Issue by dycrimson** [Kenshin/simpread#1450]
有打算一年内立项吗？

**Comment by Kenshin** [comment]
那到不会这么夸张。 😂 

等 简悦 · 同步助手 在 win 和 mac 版解决了一些小问题后就会发布 Linux 版。

**Comment by nachifur** [comment]
我使用ubuntu20.04，谷歌浏览器，之前可以导出pdf，现在不行了？
我整了会员之后，还是不行，说是没有运行同步助手？现在从网页不能直接导出pdf？

**Comment by nachifur** [comment]
linux系统下，现在pdf导出没有办法？pdf导出搞得这么复杂，还需要运行桌面的应用-同步助手吗？
太复杂了，会很浪费人的时间，会失去用户的啊，兄弟！

**Comment by Kenshin** [comment]
@nachifur 

之前的 PDF 输出是基于浏览器方式，有很多问题，比如：图片断页，需要手动操作等。
现在的 PDF 输出是基于简悦原生方式，并没有之前的问题。

Chrome 扩展能做的事情很有限，仅比 Web 端多一些而已。所以，简悦 2.1 使用了辅助性的 Destkop App → 同步助手，来实现一些扩展端无法实现的功能。

***

当然，你可以 **使用之前的方式进行 PDF 输出**，如下图：

![image](https://user-images.githubusercontent.com/81074/100597503-7fc90e00-3338-11eb-89aa-898b96f0e27f.png)

另外，**Linux 版的同步助手还没有准备好，所以此功能均无法使用**。

***

谢谢提示，目前确实有些操作上的不便利，不过，还好的是：目前的用户量还在上涨 📈 。（下个版本会解决操作上的不便）

不过，个人觉得 Linux 用户的动手能力应该比较强才对。  😀

**Comment by dycrimson** [comment]
> 有打算一年内立项吗？

谢谢&期待！

感觉PDF不是个好的封装策略，只是市场化做得好……

**Comment by Kenshin** [comment]
> > 有打算一年内立项吗？
> 
> 谢谢&期待！
> 
> 感觉PDF不是个好的封装策略，只是市场化做得好……

嗯，方便展开说说？

**Comment by nachifur** [comment]
> @nachifur
> 
> 之前的 PDF 输出是基于浏览器方式，有很多问题，比如：图片断页，需要手动操作等。
> 现在的 PDF 输出是基于简悦原生方式，并没有之前的问题。
> 
> Chrome 扩展能做的事情很有限，仅比 Web 端多一些而已。所以，简悦 2.1 使用了辅助性的 Destkop App → 同步助手，来实现一些扩展端无法实现的功能。
> 
> 当然，你可以 **使用之前的方式进行 PDF 输出**，如下图：
> 
> ![image](https://user-images.githubusercontent.com/81074/100597503-7fc90e00-3338-11eb-89aa-898b96f0e27f.png)
> 
> 另外，**Linux 版的同步助手还没有准备好，所以此功能均无法使用**。
> 
> 谢谢提示，目前确实有些操作上的不便利，不过，还好的是：目前的用户量还在上涨 📈 。（下个版本会解决操作上的不便）
> 
> 不过，个人觉得 Linux 用户的动手能力应该比较强才对。 😀

好的，多谢，期待linux新的pdf导出（要是能解决断页的问题，这是个亮点，应该突出宣传一下）。window的pdf导出已经可以用了吗？
插件应该还是以方便快捷易用为主，目前好像搞得有点复杂了。文档也有点复杂，软件界面有点复杂。我用了挺长时间，现在还是有点懵。简化操作，简化设计，简悦不简，有失初衷。

**Comment by nachifur** [comment]
另外linux桌面版本，好像挺麻烦，很多linux的版本，版本一换就得重新编译。

**Comment by Kenshin** [comment]
> window的pdf导出已经可以用了吗

是的，还包括 Mac，原生 PDF 确实已经是宣传亮点了。😉

***

界面方面确实需要优化，功能毕竟设置一次即可。

***

觉得稍显复杂是因为大多数功能均可定制化学，以及不需要账户系统，数据由你决定如何存放等特点行程的。因为简悦不是传统意义上的的稍后读，关于此我会出篇文章描述。

其实就是没有理解简悦的运行机制造成的「不适感」。

不过，无论如何都要谢谢提醒。😉

**Comment by nachifur** [comment]
感谢回复发自我的荣耀手机-------- 原始邮件 --------发件人： Kenshin Wang <notifications@github.com>日期： 2020年11月30日周一 晚上10:37收件人： Kenshin/simpread <simpread@noreply.github.com>抄送： William Liu <1476879092@qq.com>, Mention <mention@noreply.github.com>主    题： Re: [Kenshin/simpread] 请问Kenshin大大，何时会上线Linux下的同步助手？ (#1450)

window的pdf导出已经可以用了吗

是的，还包括 Mac，原生 PDF 确实已经是宣传亮点了。😉

界面方面确实需要优化，功能毕竟设置一次即可。

觉得稍显复杂是因为大多数功能均可定制化学，以及不需要账户系统，数据由你决定如何存放等特点行程的。因为简悦不是传统意义上的的稍后读，关于此我会出篇文章描述。
其实就是没有理解简悦的运行机制造成的「不适感」。
不过，无论如何都要谢谢提醒。😉

**Comment by nachifur** [comment]
已经使用了window的同步助手，效果很好，图片不会断掉，点赞！

**Comment by Kenshin** [comment]
> 已经使用了window的同步助手，效果很好，图片不会断掉，点赞！

哈，喜欢就好~ 

另外，也请一并安装此插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U （以防因特殊字符造成无法导出 PDF 等问题

**Comment by nachifur** [comment]
![image](https://user-images.githubusercontent.com/23144348/100847806-38b75600-34bb-11eb-9ea3-e68274234043.png)
我已经关闭这个，但是依然提示我，没有运行同步助手，pdf依然不能导出

**Comment by Kenshin** [comment]
> ![image](https://user-images.githubusercontent.com/23144348/100847806-38b75600-34bb-11eb-9ea3-e68274234043.png)
> 我已经关闭这个，但是依然提示我，没有运行同步助手，pdf依然不能导出

你不是已经导出 PDF 了吗？（我没太理解你的意思）
如果需要使用 原生 PDF 需要运行同步助手以及开启截图的「开关」

**Comment by nachifur** [comment]
我使用window的同步助手可以导出，仅用网页的不能导出发自我的荣耀手机-------- 原始邮件 --------发件人： Kenshin Wang <notifications@github.com>日期： 2020年12月2日周三 傍晚5:24收件人： Kenshin/simpread <simpread@noreply.github.com>抄送： William Liu <1476879092@qq.com>, Mention <mention@noreply.github.com>主    题： Re: [Kenshin/simpread] 请问Kenshin大大，何时会上线Linux下的同步助手？ (#1450)





我已经关闭这个，但是依然提示我，没有运行同步助手，pdf依然不能导出



你不是已经导出 PDF 了吗？（我没太理解你的意思）

如果需要使用 原生 PDF 需要运行同步助手以及开启截图的「开关」

**Comment by Kenshin** [comment]
「仅用网页的不能导出」
什么意思？

**Comment by nachifur** [comment]
![image](https://user-images.githubusercontent.com/23144348/100861205-77a1d780-34cc-11eb-902e-b64d8731d956.png)

**Comment by Kenshin** [comment]
emmm... 

明天确认下。

**Comment by Kenshin** [comment]
@woodgear 

嗨，抱歉 Linux 版本可能会再稍晚些了，目前已当前的大版本更新为主。大致上 Roadmap

> 新（大）版本发布 → （可能持续在较短时间内容发布几个补丁版本） → API 一些更新计划（不会占有太多时间） → Linux / Mac / Win 版的同步助手。

顺利的话，新版发布的一个月后开始。

**Comment by woodgear** [comment]
> @woodgear
> 
> 嗨，抱歉 Linux 版本可能会再稍晚些了，目前已当前的大版本更新为主。大致上 Roadmap
> 
> > 新（大）版本发布 → （可能持续在较短时间内容发布几个补丁版本） → API 一些更新计划（不会占有太多时间） → Linux / Mac / Win 版的同步助手。
> 
> 顺利的话，新版发布的一个月后开始。

2333,我到没什么意见,不过最好还是更新下文档比较好..

**Comment by rebecca1994759** [comment]
希望快点儿上架linux版本吧，那就完美了！

**Comment by woodgear** [comment]
发现文档还是没有更新。。。这会让很多人困惑的。在没有支持之前就不要说自己支持啊 建议将https://simpread.pro/pro.html#synchelper这个网页上的平台支持标识同步下。
额并不是在催或什么。我会时不时的去看看支持的状态。所以希望能正确的反映出当前的状态。

**Comment by woodgear** [comment]
如果有手动修复的方法也可以。。

**Comment by Kenshin** [comment]
@woodgear 

嗨，已经去掉了 `Linux` 的标识，等 Linux 上线后会在这里通知大家。

**Comment by rebecca1994759** [comment]
再次血书求linux版本，没有linux版本的同步助手，高级版几乎没有什么用……

**Comment by Kenshin** [comment]
> 再次血书求linux版本，没有linux版本的同步助手，高级版几乎没有什么用……

哈哈，「血书」夸张了，我目前在休假，回去后就着手开始。

另外，高级版只有导出功能需要同步助手，除此之外的其他高级功能，如：双向链接等都是可以使用的。

**Comment by Kenshin** [comment]
嗨，各位。

同步助手发布了命令行版本，可支持 Linux，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3704)，目前此版本为内测版，有任何问题请 [汇总到这里](https://github.com/Kenshin/simpread/discussions/3704#discussioncomment-2542653)。

PS：等正式版发布后，我还会通过这里告诉大家。

**Comment by Kenshin** [comment]
嗨，各位。

[同步助手 · 命令行](https://github.com/Kenshin/simpread/discussions/3704) 版正式发布  🎉 

![Sync CLI](https://user-images.githubusercontent.com/81074/163512494-3c41c6c3-2158-49f8-9425-27637a3303c8.png)

在使用时如有问题，[请提 Issues](https://github.com/Kenshin/simpread/issues/3740)

**Comment by Kenshin** [comment]
@ihipop 

1. 我没说没有 Linux 版，所以自然会有
2. 命令行版就是「高级版」

**Comment by ihipop** [comment]
> @ihipop
> 
> 1. 我没说没有 Linux 版，所以自然会有
> 2. 命令行版就是「高级版」

@Kenshin

但是现在命令行版本缺一些特色功能 
而且看起来好像是第三方开发的，会持续维护么？缺失的功能会持续增加么？

**Comment by Kenshin** [comment]
@ihipop 

看这里的解释 https://github.com/Kenshin/simpread/discussions/3704#discussioncomment-2655297

另外，PDF 不会加，等 Linux 版。

命令行版本是轻量级的同步助手，以后的新功能当然会跟命令行版同步，但具体以新版发布后的通知。

如果你需要全功能版本，请等 Linux 版。

**Comment by Kenshin** [comment]
@ihipop 

我增加了相关说明，看下图

![image](https://user-images.githubusercontent.com/81074/165877922-2f2ee1d9-b0b2-4df8-8092-6b93947c5807.png)

另外，删除了之前无关的内容，如有需要请在此讨论。

**Comment by Kenshin** [comment]
@ihipop 

同时更新了受众范围

![image](https://user-images.githubusercontent.com/81074/165878128-58d2138d-839f-4cb6-b2dd-d334b8d74f60.png)

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# Linux 版来啦

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
