### ISSUE TITLE
问题如下

### ISSUE THREAD

**Issue by GehirnZ** [Kenshin/simpread#1451]
1.无法通过任何方式登入账号，包括坚果云、Dropbox以及本地配置文件，均显示因为下图或是服务器异常而无法登入（第三方应用登入授权已经授予）
![image](https://user-images.githubusercontent.com/75194695/100534259-d4409080-3247-11eb-8efc-9464c1ef912d.png)

2.已经通过爱发电付款，但没有收到高级账户验证码
![image](https://user-images.githubusercontent.com/75194695/100534229-78760780-3247-11eb-8357-707fa7b17510.png)
付款截图如上

3.同时也无法添加任何插件，均显示添加失败，稍后再试

**Comment by Kenshin** [comment]
嗨，逐一回复你的问题。

***

> 爱发电的问题。

抱歉，爱发电的 Licnese 没有了导致没有给你发码，如果你在爱发电私信我的话，我已经回复你了，并内附了 License （ **如果没有的话，请在爱发电私信我。**

***

> 无法安装插件 以及 无法通过任何方式登入账号 的问题。

估计是你的设置造成的，请看解决方案 https://github.com/Kenshin/simpread/issues/1334

***

没有疑问的话，请关闭此 Issues ~

**Comment by GehirnZ** [comment]
已经解决，感谢！

**Comment by Kenshin** [comment]
搞定就好，我关闭此 Issues 了~

**Comment by GehirnZ** [comment]
好的，谢谢。



---原始邮件---
发件人: "Kenshin Wang"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 下午4:34
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"GehirnZ"<1054112354@qq.com&gt;;
主题: Re: [Kenshin/simpread] 问题如下 (#1451)




 
搞定就好，我关闭此 Issues 了~
