### ISSUE TITLE
将少数派的网址加入排除名单无法取消自动进入阅读模式

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1458]
![image](https://user-images.githubusercontent.com/15308878/100651834-099cc980-3381-11eb-99e5-e13171c325d9.png)

**Comment by Kenshin** [comment]
嗨，你需要加入 `sspai.com` 而不是全域名，

具体为何不生效（全域名）的话，我还需要 Debug 下。

**Comment by Kenshin** [comment]
嗨，抱歉。这几天在整理 Github Issues，看到了这个遗留的问题。

#### 回复

> 这个现象是正常的，当你将 `https://sspai.com/` 加入到 排除列表时，仅当前这个页面无法进入阅读模式，但诸如 `https://sspai.com/post/61996` 这样的页面仍旧可以进入阅读模式。

> 如果将 `sspai.com` 加入排除列表的话，意味着整个域 `sspai.com` 是无法自动进入阅读模式的。
