### ISSUE TITLE
全局快捷键

### ISSUE THREAD

**Issue by empyriumz** [Kenshin/simpread#146]
非常喜欢这个插件，希望作者能否提供全局快捷键功能？
像safari中的阅读模式那样用cmd+shift+r直接进入阅读模式，谢谢！

**Comment by Kenshin** [comment]
感谢反馈~
目前有快捷键支持

- `聚焦模式` 默认为 `A S`
- `阅读模式` 默认为 `A A`

计划未来会加入更多的快捷键支持，比如导出等；其实主要是因为简悦与其它快捷键类的扩展有些冲突，所以并未开放太多的快捷键支持。  😳

**Comment by empyriumz** [comment]
I see, 在chrome插件管理的键盘快捷键那里没找到 还以为没有呢，多谢作者！

在 2017年10月27日 上午10:53，Kenshin Wang <notifications@github.com>写道：
