### ISSUE TITLE
同步助手关闭时，右上角的信息提示【可选择不再提示】

### ISSUE THREAD

**Issue by jiangaq** [Kenshin/simpread#1460]
![image](https://user-images.githubusercontent.com/26076033/100692524-04ae3900-33c6-11eb-82f4-677586e6e579.png)

因为这样就有一种强迫要客户打开同步助手浏览网页的感觉，体验不是最好，因为上网不一定非要同步简悦，只是建议一下，比方说，可以在打开阅读模式的时候，才跳出来提示一下，这样比较合理吧。

**Comment by Kenshin** [comment]
谢谢提示。
确实这里应该仅提示一次。

***

不过，你可以随时关闭这个功能，位置在下图所示：

![image](https://user-images.githubusercontent.com/81074/100693361-aa15dc80-33c7-11eb-9425-d8561261ecd0.png)

***

至于你说的问题，我先记 Bug ~

**Comment by Tony-zf1** [comment]
> 谢谢提示。
> 确实这里应该仅提示一次。
> 
> 不过，你可以随时关闭这个功能，位置在下图所示：
> 
> ![image](https://user-images.githubusercontent.com/81074/100693361-aa15dc80-33c7-11eb-9425-d8561261ecd0.png)
> 
> 至于你说的问题，我先记 Bug ~

记了bug，要修啊，现在还是不断地提示

**Comment by Kenshin** [comment]
@Tony-zf1 

https://github.com/Kenshin/simpread/discussions/1700 https://github.com/Kenshin/simpread/discussions/1692

**Comment by Tony-zf1** [comment]
> @Tony-zf1
> 
> #1700 #1692

认真的说，这两个页面并不能解决问题。

逻辑上讲，提醒“同步助手未打开”这件事，不需要无限次提醒，一次就够了，多次提醒只会影响版面，让人烦躁。其次，同步助手的功能对部分用户来说是一个低频功能，偶尔会用到，但不是“完全用不到”或者“每天都需要用到“，因此解决办法不应该是要么用要么不用，对低频用户来说，每次手动去选项页开启、关闭显然是成本更高的一件事。

我觉得打开浏览器时提醒一次，然后像现在一样，当用户使用某些依赖于同步助手的功能时，再提醒”请确保已运行简悦同步助手“是更好的方式。

谢谢，期待简悦变得更好用。

**Comment by Kenshin** [comment]
@Tony-zf1 

嗨，下个版本确实可以只提示一次。

不过，这个提示有必须要存在的原因是：
因为你选择了同步助手的的同步方案，但未开启同步助手（或因其他问题导致同步助手无法正确给扩展端数据）

所以，造成的问题是：
简悦因配置文件有异常而导致扩展端的异常。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
