### ISSUE TITLE
文本高亮标记默认样式首尾增加间隔

### ISSUE THREAD

**Issue by simadad** [Kenshin/simpread#1464]
### 问题：
> 对`同一行文字`进行`连续地`【两次】`同种颜色`的高亮标记，`默认样式`下，两处高亮标记没有明显的间隔，`看上去`就像整行文字`仅有一个标记`。

##### 对文本高亮标记普通样式的背景色增加一个仅对首尾文字有效的 `margin`，以间隔开相连的两个标记

**Comment by Kenshin** [comment]
谢谢反馈，确实有这个问题，我先记 Bug，但你可以暂时使用下面的方式解决：

```
[sr-annote-bg-color] {
     margin: 0 2px;
}
```

其中 `2px` 可以改成任何数字。

***

把上面的代码加入到 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 即可。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
