### ISSUE TITLE
onenote授权只能维持很短的时间

### ISSUE THREAD

**Issue by g93920079** [Kenshin/simpread#147]
simpread 真的很好用，只是让我苦恼的是，onenote授权时间很短，好多次转存文件时，总是提示授权过期，不知道是什么原因，求助~

**Comment by Kenshin** [comment]
谢谢，你说的问题暂时没有太好的办法，因为 Onenote 授权时间就是这么短… 😭
初步考虑，下个版本增加自动重连机制，这样操作上能方便些。

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，已增加【自动重新授权机制】，此 issues 将会关闭。

关于此功能，请看 http://ksria.com/simpread/welcome/version_1.0.5.html#auto-auth
