### ISSUE TITLE
无法发送到Kindle.

### ISSUE THREAD

**Issue by Diluo001** [Kenshin/simpread#1475]
设置了一天这个功能了.
到现在也没成功. 换了很多个不同网站邮箱.都不行.最后选了163. Kindle 邮件白名单也设置了.
![image](https://user-images.githubusercontent.com/41585868/100893448-5950d180-34f6-11eb-8ea3-a72d3efc03c3.png)
![image](https://user-images.githubusercontent.com/41585868/100893600-7f767180-34f6-11eb-88c6-c0e43a872818.png)
![image](https://user-images.githubusercontent.com/41585868/100949667-b4f67b80-3545-11eb-93cd-bfbdb61e7d13.png)
![image](https://user-images.githubusercontent.com/41585868/100949902-34844a80-3546-11eb-977c-cffa3196e408.png)
![image](https://user-images.githubusercontent.com/41585868/100951473-93978e80-3549-11eb-976f-00f847aa808b.png)

Windows客户端也感觉设置好了.  点保存到Kindle.(我这里没有帮助中说的,导出 - 发送到Kindle按钮) 就显示"开始发送,请稍等". 随后就没有任何提示了.
然后邮箱里也没有 "已发送" 

这个功能是可以用的吗?  我哪一步有设置错了吗?

**Comment by Diluo001** [comment]
也有可能是我亚马逊白名单没设置的关系.
我的亚马逊有outlook邮箱白名单. 但是我却不会设置outlook.的smtp. 
而163的smtp设置比较简单. 但是却没有亚马逊设备的白名单. 而亚马逊设备设置.我无数天都刷不出来.一直卡这里.
![image](https://user-images.githubusercontent.com/41585868/100896623-c4e86e00-34f9-11eb-8f61-ff17241b8c2f.png)

也不知道是否是白名单的问题. 因为 已发送 里什么都没有. 我在研究研究吧.

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/100956594-bf1f7680-3553-11eb-915d-c7ee9d4f7337.png)

![image](https://user-images.githubusercontent.com/81074/100956664-e8d89d80-3553-11eb-9ec3-5fbf2e08f029.png)


***

看截图发现，**位置2** 设置错了，位置2是用于发送邮件功能的，而非用于设置 Kindle（这个问题跟 发送到 Kindle 无关，只是特别说明下。

**Comment by Diluo001** [comment]
我对应了下. 除了位置2.(假如位置2是无关的设置) 其他的全都是对的.
![image](https://user-images.githubusercontent.com/41585868/100957300-2558c900-3555-11eb-85f5-36aaadefe6a9.png)
![image](https://user-images.githubusercontent.com/41585868/100957355-3e617a00-3555-11eb-8899-4bf324565e2e.png)
![image](https://user-images.githubusercontent.com/41585868/100957449-694bce00-3555-11eb-960e-2effd4fa937b.png)

你看.

**Comment by Kenshin** [comment]
emmm

位置2需要设置下，这样可以测试是否正常发送邮件。

另外，**下午我会测试下 163 的信箱问题**。（你要是方便的话，可以试试 QQ 邮箱

**Comment by Diluo001** [comment]
QQ 邮箱有问题. 我的账号注册太早了. 需要去申诉,申请密保手机等,才可以开启SMTP功能. 而这个十分十分麻烦. 要找多位QQ好友验证,要提交身份证. 等等等. 所以我用的163.

**Comment by Kenshin** [comment]
> emmm
> 
> 位置2需要设置下，这样可以测试是否正常发送邮件。
> 
> 另外，**下午我会测试下 163 的信箱问题**。（你要是方便的话，可以试试 QQ 邮箱

按照我说的，163 测试发送邮件成功了吗？

**Comment by Diluo001** [comment]
点保存到Kindle.(我这里没有帮助中说的,导出 - 发送到Kindle按钮) 
这个步骤对吗?

**Comment by Kenshin** [comment]
> 点保存到Kindle.(我这里没有帮助中说的,导出 - 发送到Kindle按钮)
> 这个步骤对吗?

![image](https://user-images.githubusercontent.com/81074/100958253-f9d6de00-3556-11eb-9d16-c5e4a577467e.png)


看上图

**Comment by Diluo001** [comment]
我好像可以了. 邮件和Kindle 都可以收到.
我什么都没有动. 昨天和今天早上弄半天.都没有成功. 你回复后我又点了下. 居然成功了. 真的很奇怪.

谢谢你.

**Comment by Diluo001** [comment]
这还是不对劲哦.  我发送亚马逊 "Amazon.cn：管理我的内容和设备" 这个页面到邮箱, 到Kindle 可以发送成功.
而我找个长文, 异次元的帖子. 就发送不成.  而我昨天和今天早上发送的都是长文 .我在测试测试.

**Comment by Diluo001** [comment]
谢谢作者. 我有找了很多很多 都发送成功了. 我之前只是一直在用异次元的帖子做测试.
https://www.iplaysoft.com/stacksocial.html   拿的这个.就不可以. 

但是没有关系.我本来就不需要发送这个.只是拿来测试用的. 

十分好用的功能.谢谢作者提供如此伟大的功能. 这个帖子我整理下. 把我个人信息的删一下.

**Comment by Kenshin** [comment]
嗨，解决了就太棒了。

（至于原因，我也不清楚 😄 ... 初步怀疑还是你的设置造成的。  😅 

发送到 Kindle 会有失败情况，不知道是否给你退信？应该是受限于 Amazon 的规则造成的。

我先关闭这个 Issues ，如再有问题的话，可随时重开它。

**Comment by dxb22abad** [comment]
gmail 还是不行 还是一直不行呢？
