### ISSUE TITLE
[Notice][Bug] 简悦 2.1 无法使用旧版方式的 PDF 导出功能（附解决方案）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#1477]
![image](https://user-images.githubusercontent.com/23144348/100861205-77a1d780-34cc-11eb-902e-b64d8731d956.png)
点这个不能导出pdf，提示我需要同步助手。
![image](https://user-images.githubusercontent.com/23144348/100861397-bafc4600-34cc-11eb-993c-87c7d70b14c9.png)
我已经关闭这个，问题依然存在

_Originally posted by @nachifur

**Comment by Kenshin** [comment]
### 解决方案：

1. 使用离线版的用户，请重新下载 [离线版 2.1](http://ksria.com/simpread/crx/2.0.0/simpread.zip) **即可解决**。
2. **简悦 · 高级账户** 用户**请使用 2.1 版的原生导出方案**。
3. **简悦 · 基础账户** 不想使用 **方案1** 的话，需要使用 PDF 输出的话，请手动 **<kdb>Ctrl/Command + p</kbd>** 的方案。

**Comment by Kenshin** [comment]
@nachifur 

确认了，这个是 Bug 因为判断的问题造成了，**无法使用 2.1.0 版本之前的 PDF 导出功能**！

解决方案请看上条 👆

**Comment by Kenshin** [comment]
PS：为这个问题我新建了一个 Issues 因此我需要删除 https://github.com/Kenshin/simpread/issues/1450 相关的内容。（因为重复了

**Comment by Kenshin** [comment]
@nachifur 

PS：为这个问题我新建了一个 Issues 因此我需要删除 https://github.com/Kenshin/simpread/issues/1450 相关的内容。（因为重复了

**Comment by nachifur** [comment]
好的，Ctrl + p 可以使用

**Comment by Kenshin** [comment]
嗨，此功能也可以使用 [PDF 辅助增强插件](https://simpread.ksria.cn/plugins/details/Lly3mkuSPz) 解决
