### ISSUE TITLE
高级账户pdf无法导出提示我不是高级账户

### ISSUE THREAD

**Issue by zhuhaoxlj** [Kenshin/simpread#1479]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
高级账户pdf无法导出提示我不是高级账户
**截图**
![image](https://user-images.githubusercontent.com/56185765/100962392-33abe280-355f-11eb-8a3b-7de57a96075c.png)
![image](https://user-images.githubusercontent.com/56185765/100962398-3575a600-355f-11eb-8940-91cb3ea16259.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by binsee** [comment]
@zhuhaoxlj 请将图1删除，UID及个人信息泄露，以后请注意打码哈。

**Comment by Kenshin** [comment]
@zhuhaoxlj 
我看你关闭了 Issues 搞定了吗？

**Comment by zhuhaoxlj** [comment]
> @zhuhaoxlj 请将图1删除，UID及个人信息泄露，以后请注意打码哈。

谢谢

**Comment by zhuhaoxlj** [comment]
> @zhuhaoxlj
> 我看你关闭了 Issues 搞定了吗？

是的
