### ISSUE TITLE
自动适应

### ISSUE THREAD

**Issue by CharMingF** [Kenshin/simpread#148]
chrome还有个插件是 阅读模式。
这个插件能够自动适应很多网站，简悦显然的网站虽然有200多，但是还是太少了。
所以可以参考这种自动适应。

**Comment by CharMingF** [comment]
https://chrome.google.com/webstore/detail/reader-view/iibolhpkjjmoepndefdmdlmbpfhlgjpl

**Comment by Kenshin** [comment]
谢谢建议～
1.0.4 增加了 临时阅读模式，支持任意页面生成阅读模式，你可以试试。
而这个功能类似说的扩展，但是它拥有更好的生成效果。
而适配的 230 个网址，则是完美适配。

**Comment by Kenshin** [comment]
Hi，简悦已经升级到最新的 `1.1.0` 增加了很多新功能，我将关闭此 issues，如需要重新开启它。 😊
