### ISSUE TITLE
notion无法授权

### ISSUE THREAD

**Issue by guobayee** [Kenshin/simpread#1484]
- 操作系统 **MacOS**

- 浏览器版本 **Edge 87.0.664.47**

- 简悦版本 **2.1.0**

- 发生问题的地址 <http://www.woshipm.com/it/4180053.html>

**添加到notion时显示授权已过期，但依照系统提示授权后依然显示授权已过期。清除当前数据和重装简悦都无法解决该问题。**

<img width="418" alt="截屏2020-12-03 下午10 05 51" src="https://user-images.githubusercontent.com/75432327/101031149-7ba92480-35b4-11eb-85bf-a8ed9773bdf0.png">
<img width="1280" alt="截屏2020-12-03 下午10 05 55" src="https://user-images.githubusercontent.com/75432327/101031221-819f0580-35b4-11eb-8046-902a011f0825.png">

**Comment by guobayee** [comment]
**已解决**
不阻止第三方cookie后就可以了

**Comment by Kenshin** [comment]
谢谢自救成功，印象中文档中说了。
我先关闭这个 Issues 了。
