### ISSUE TITLE
保存至github上no found

### ISSUE THREAD

**Issue by fengmao31** [Kenshin/simpread#1485]
![image](https://user-images.githubusercontent.com/19343842/101053740-1b6daf00-35c3-11eb-8e68-8299d9de0d1e.png)

**Comment by Kenshin** [comment]
选项页 → 高级设定 → 授权管理
配置成功了吗？

**Comment by Kenshin** [comment]
刚测试了下，应该可以，请确认你的设置。

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/101122648-f06c7500-362d-11eb-8689-423a0e2f7def.png)
![image](https://user-images.githubusercontent.com/19343842/101122597-d6329700-362d-11eb-96f2-3754383a858d.png)
![image](https://user-images.githubusercontent.com/19343842/101122761-290c4e80-362e-11eb-8fef-0a5ec9007bc4.png)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/101127443-860d0200-3638-11eb-8522-d9e3bd682696.png)

**Comment by fengmao31** [comment]
解决方案：不要前面带https://github.com/。直接用户名和存储库名称。
