### ISSUE TITLE
阅读模式的主题色设置为娟鼠时 Kindle 的底色就会变为黑色

### ISSUE THREAD

**Issue by wabbaf** [Kenshin/simpread#1487]
- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 https://zhuanlan.zhihu.com/p/86419509

**发送到Kindle的文件底色为黑色，文字尺寸很小，效果类似于pdf，但设置里没有选择附件为pdf，包括但不限于上述网页，包括公众号、知乎等网页发送到Kindle后都会是反色的错误效果**

> 发送到
![Xnip2020-12-04_09-51-51](https://user-images.githubusercontent.com/30892328/101111562-6bc22c80-3616-11eb-9164-6d6f43aefc73.jpg)
![WechatIMG65](https://user-images.githubusercontent.com/30892328/101111884-1a666d00-3617-11eb-9ed4-aa447b0b4cf5.jpeg)
![WechatIMG66](https://user-images.githubusercontent.com/30892328/101111891-1d615d80-3617-11eb-8f9a-a4a31e4fd641.jpeg)

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
你是用深色主题吗？

PDF 发送时为 HTML ，并不是 PDF 格式（因为无法调整大小之类的）。

**Comment by wabbaf** [comment]
并没有使用深色主题，在聚焦模式启动前包括聚焦模式启动后所呈现的效果都是白底黑字，而且这个问题经过测试，无论白天还是晚上都会出现，所以应该可以排除是Mac os黑暗模式切换导致的

**Comment by Kenshin** [comment]
很奇怪的问题。

你可以试试导出 HTML 看看颜色是否正确？

**Comment by wabbaf** [comment]
无论是导出为HTML还是离线HTML，在Chrome打开都是正常的效果，还需要提供其他的什么信息吗？

**Comment by Kenshin** [comment]
嗨，我自己测试以及跟其它用户也反馈了你的问题，都没有遇到。

请问你是否开启了「夜间模式」？另外 Amazon 后台也可以单独下载导入的 PDF ，你可以通过此方式下载，看看是否正常？

***

我测试的型号为 **Kindle固件版本5.13.3，型号KPW4** 截图如下

![photo_2020-12-07_10-36-32](https://user-images.githubusercontent.com/81074/101303033-1a18dc80-3878-11eb-82b8-ea524a4014a4.jpg)

**Comment by wabbaf** [comment]
发现问题所在了：当基础设置里阅读模式的主题色设置为娟鼠时，发送到Kindle的底色就会变为黑色。如果改为默认的主题色就会恢复正常，另外想问一下发送到Kindle的文章字体这么小属于正常现象吗？对比正常大小的“标准”二字会明显小了几个字号，如下图：
![IMG_9635](https://user-images.githubusercontent.com/30892328/101319779-77735480-389d-11eb-980f-e8b3db7ce8fa.jpeg)

**Comment by Kenshin** [comment]
>当基础设置里阅读模式的主题色设置为娟鼠时，发送到Kindle的底色就会变为黑色。

哈哈，太不容易了，重要找到问题，我先记 Bug

 ***

关于字体大小的问题的，应该可以在 Kindle 中调整，从我的角度看应该没问题，另也没有其他用户反馈过 Kindle 字体的问题。

**Comment by jiangaq** [comment]
娟鼠主题pdf导出时，也会发生颜色失真现象，换个主题就好了

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
