### ISSUE TITLE
代码段高亮问题

### ISSUE THREAD

**Issue by cpp-jiang** [Kenshin/simpread#1489]
![image](https://user-images.githubusercontent.com/25993096/101173265-3ef53000-367d-11eb-852a-5889547c890f.png)

下面是网页链接
https://mp.weixin.qq.com/s/x_rnXinyYhnfUC6xDX-l8w

**Comment by Kenshin** [comment]
谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
