### ISSUE TITLE
读书 - 豆瓣

### ISSUE THREAD

**Issue by joshua-ch** [Kenshin/simpread#149]
无法正常显示。

**Comment by Kenshin** [comment]
你说的是 https://read.douban.com 豆瓣阅读吗？如果是的话，的确是这样的。
由于这个页面的结构很奇怪，无法单独抽离出来，所以如果使用 `临时阅读模式` 的话，是无法完美呈现效果的，所以我不建议这个页面使用 `简悦`  😫

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***


我随机访问了 https://read.douban.com/reader/column/8180834/chapter/50086449/ 可以自动识别为阅读模式

![image](https://user-images.githubusercontent.com/81074/57358368-dcd5ff80-71a7-11e9-8b05-326e1f416ccf.png)
