### ISSUE TITLE
无法成功保存到 OneNote 的问题。

### ISSUE THREAD

**Issue by Deadline233** [Kenshin/simpread#1490]
最近OneNote保存好像都不行....是微软方面的原因吗？我的是个人国际版的账户...已经有大概1个多月了
——————
站点集市的菜鸟教程网站的适配不是很好 对代码段的支持会有一些遗漏 但是作者没有给出联系方式...我也不知道怎么联系上作者 一同协助改一下代码段...
希望能够强制留下联系方式？或者用加密请求的方式给联系方式吧~不然站点的适配就不会大家协作得那么快了

**Comment by Kenshin** [comment]
> 最近OneNote保存好像都不行....

不行的意思是：授权时间短？还是提示成功，但保存失败？

****

站点集市这个功能还需要很多的优化，在此之前暂时被边缘化了。

你可以试试去掉「菜鸟教程网站」后能否通过智能识别解决？

**Comment by truedevin** [comment]
我的onenote也是，说保存成功，但实际上失败。另外每次都需要重新授权

**Comment by Deadline233** [comment]
> > 最近OneNote保存好像都不行....
> 
> 不行的意思是：授权时间短？还是提示成功，但保存失败？
> 
> 站点集市这个功能还需要很多的优化，在此之前暂时被边缘化了。
> 
> 你可以试试去掉「菜鸟教程网站」后能否通过智能识别解决？

我再试了好多遍，这个OneNote保存都是提示保存失败。偶尔会有保存成功但实际上保存失败的...而且重新授权也不行...

至于像关掉站点集市功能后...对“菜鸟教程”智能识别就更不行了...代码段基本识别不出来~~

还是期待早一点起用站点集市 还有更新吧~毕竟菜鸟教程对我们这些刚入门编程的菜鸟还是挺重要的~~~ @Kenshin

**Comment by Kenshin** [comment]
@truedevin 

emmm 请问是什么版本？2.1 吗？如果是的话，重新授权后会自动重新授权（这是授权时间过短造成的，与简悦无关。

@Deadline233 

**菜鸟教程网站** 我会单独适配它。

***

至于无法保存的问题，我先问问其他用户，之后给你们回复。

**Comment by truedevin** [comment]
> @truedevin
> 
> emmm 请问是什么版本？2.1 吗？如果是的话，重新授权后会自动重新授权（这是授权时间过短造成的，与简悦无关。
> 
> @Deadline233
> 
> **菜鸟教程网站** 我会单独适配它。
> 
> 至于无法保存的问题，我先问问其他用户，之后给你们回复。

授权时间确实太短，昨天授权了今天又要重新授权

**Comment by Kenshin** [comment]
@truedevin 

所以才会有自动重新授权的功能，但 Onenote 经常改后台的返回信息导致经常重新授权失败。

**Comment by Deadline233** [comment]
![image](https://user-images.githubusercontent.com/69841255/104810898-c2846e00-5832-11eb-8309-9340dd7c8a4b.png)
还是有这个问题啊 emmm这已经好多天都是这样了

**Comment by Kenshin** [comment]
@Deadline233 

Onenote 授权的问题已经解决了，但只能随着下个版本发布，如果你有强烈需求的话，我会考虑给你一个离线版。

**Comment by Deadline233** [comment]
下个版本发布大概多久啊~ 看时间吧~~ 我可能下下周必须要用一下？

**Comment by Kenshin** [comment]
@Deadline233 

把邮箱告诉我或在 TG 群里面私聊我，我明天给你离线版。

**Comment by Deadline233** [comment]
> @Deadline233
> 
> 把邮箱告诉我或在 TG 群里面私聊我，我明天给你离线版。

感激不尽~我已经把邮箱地址发到您的gmail邮箱里了~再次感谢~

**Comment by Kenshin** [comment]
@Deadline233 
嗨，我没有在 gmail 看到你的邮件。 😅 
另外，也不要关闭此 issues 因为并没有彻底解决。

**Comment by Deadline233** [comment]
阿这 不知道这个回复能不能收到啊。邮箱地址heyuhang@mails.ucas.ac.cn
再次感谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午10:38
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"宇航"<545199402@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 无法成功保存到 OneNote 的问题。 (#1490)





 
@Deadline233
 嗨，我没有在 gmail 看到你的邮件。 😅
 另外，也不要关闭此 issues 因为并没有彻底解决。

**Comment by Kenshin** [comment]
@Deadline233 
邮件已发

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)


## 评分

Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
