### ISSUE TITLE
t66y 无法导出pdf

### ISSUE THREAD

**Issue by bolnh** [Kenshin/simpread#1491]
- 操作系统 Windows 10

- 浏览器版本 Microsoft Edge 87.0

- 简悦版本 2.0.0

- 发生问题的地址： t66y.com 达盖尔的旗帜文章无法保存pdf

已安装简阅同步助手，测试了其他网站可以保存pdf，唯独草榴不行。

**Comment by Kenshin** [comment]
哈哈，草榴导出 PDF 是看小说吗？ 😂
因为是个例，我先关闭这个 Issues 吧，如还有类似问题，我再重开它。
