### ISSUE TITLE
导出epub失败

### ISSUE THREAD

**Issue by NTDLX** [Kenshin/simpread#1493]
Win10 
谷歌浏览器 
插件2.1 
本地同步助手1.0
已安装pandoc
导出时提示导出失败，此功能为实验性功能吧啦吧啦吧啦。。。
（高级账号）

另外基础账户使用第三方可以导出，但是图片会缺失

**Comment by Kenshin** [comment]
估计是因为标题含有特殊符号造成的，你可以安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

如果还不行的话，请告知 URL 或标题也行。

**Comment by NTDLX** [comment]
安装了，还是不行 
https://www.lightnovel.us/cn/detail/1047731

**Comment by Kenshin** [comment]
可能是个例，因为这个页面太大了？
建议多试试几个页面，我现在在外面，明天确认下这个 URL

**Comment by Kenshin** [comment]
@PhathomBR 

1. 在 https://sspai.com/post/69972 测试
2. 是否安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
3. 是任意 URL 都有问题？还是某个？

**Comment by PhathomBR** [comment]
>1这个太麻烦了，暂时没时间测试
>已经安装了2的插件，还是无法导出
>所有url都无法导出epub，无论是图文还是纯文字

**Comment by Kenshin** [comment]
@PhathomBR

只能让你把 Epub 相关设置都截图了。

**Comment by PhathomBR** [comment]
![微信截图_20230728203148](https://github.com/Kenshin/simpread/assets/43084451/60edb8fa-39b2-4239-ac20-14eea073e90e)
![微信截图_20230728203300](https://github.com/Kenshin/simpread/assets/43084451/2a03295a-dcd3-4e0b-925b-473620d205ee)

**Comment by PhathomBR** [comment]
把相关的软件和插件都删掉重装过一次，还是不行。

不知道是不是调用不到pandoc的问题，卸载和装上pandoc，导出epub都显示导出失败，此功能为实验性功能；
在powershell里pandoc -V是显示正常的，也试过自己加环境变量；

最后只能先把网页导入到Obsidian，再用pandoc插件来导出epub；
Obsdian里只有pandoc plugin插件导出成功（导第一次还是失败，导第二次才成功），插件市场里其他两个插件都导出失败。

**Comment by Kenshin** [comment]
> 不知道是不是调用不到pandoc的问题

肯定是这个问题。

PS：看你的描述，感觉还是你的 `pandoc` 环境有问题。试试手动把 `pandoc` 加入到环境变量中。

**Comment by vanxxxx** [comment]
hh我也是在lk找小说,完全一样的问题,捣鼓了一晚上没有解决,
第三方可以导出但是没图片,用了pandoc会员的导出一直失败,提示实验性功能,有问题提issue~,pandoc手动加进环境变量也没用
![1691420183074](https://github.com/Kenshin/simpread/assets/99182158/9a6f7727-f692-4fb2-8cea-db0d32cd86d1)
![1691420247776](https://github.com/Kenshin/simpread/assets/99182158/6a7e20b1-531e-4d69-a11e-39d04fb281e0)
另外我还测试了一下离线导出html和md文件也显示不出来图片,大概是网站问题,我最后用浏览器插件转成epub看了

**Comment by PhathomBR** [comment]
pandoc手动加进环境变量也没用；
图片这个只能自己手动保存到本地，再用sigil替换epub里的图了；
另外，公司里的WIN10电脑使用网页导出epub倒是一切正常，家里WIN11的不知道什么毛病，估计又是三哥更新系统后加了大便代码。

**Comment by Kenshin** [comment]
@vanxxxx 

图片的问题确实在某些网站即便使用离线 HTML 也不好使。另外，你截图中的内嵌图片格式是错误的，大概率是我说的情况。

@PhathomBR 

win 11  的话，需要保存在非系统目录中。（PS：对开发来说 win 一直很迷... 😂

**Comment by karonque** [comment]
“导出时提示导出失败，此功能为实验性功能吧啦吧啦吧啦。。。”

补充一个原因，win11，norton 阻止了pandoc运行，但是没提示。开始时网页转epub始终是上面的提示。直到在cmd下测试pandoc xx.md -o xx.docx 时，系统栏跳出提示“pandoc未被授权”。用户点了授权后pandoc运行成功，再次测试网页转epub也成功了。

**Comment by Kenshin** [comment]
@karonque 

谢谢提示。 👍
