### ISSUE TITLE
保存到双链笔记

### ISSUE THREAD

**Issue by kunpeng9** [Kenshin/simpread#1495]
目前双链笔记都出来了好几年了，支持双链笔记的插件还不是很多，主要是国内的双链笔记不支持，国外的漫游研究者好像有自己的剪藏插件吧，我记得，之前安装了一通之后，就关闭了，没有再用了【热情冷却下来了，不那么狂热老，依然使用印象笔记国际版】。因为我目前并没有钱买漫游研究者的账户，偶尔用一下漫游研究者中国的公开库，用的不多。
主要还是用国内的双链笔记，葫芦笔记。
什么时候能够支持保存到葫芦笔记、日志序列【logseq】？
【个人认为的排名】目前双链类的最火的依次是漫游者研究者【国外的，主要是外国人用，国内也有用但是相对人口基数来说，很少，从漫游者开始爆红，双链以前也有，但是这个最完善，以前国外也有zettler，但是不是很完善，知道研究者之前没有用过】logseq【国际的，中国人用、外国人也有很多人用】我来【国内的，应该是几个应用里面人数最多的，但是感觉互联网世界里声浪不高】葫芦笔记、roamedit【以前用过，后来没用了】

希望简悦支持的先后或者说紧急程度排序=我来【目前用的web，但是用的久了一点时间之后发现，它也有问题，但是作者迟迟没有修复，问题一直挂着，没有解决】，葫芦笔记、logseq、roamedit、漫游研究者【roam research】。

**Comment by Kenshin** [comment]
嗨，谢谢反馈。 👍 

会考虑支持更多的服务。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
