### ISSUE TITLE
希望可以在阅读时支持chrome插件Liner

### ISSUE THREAD

**Issue by lutein** [Kenshin/simpread#150]
阅读体验非常棒，但是在使用简悦时不能同时使用liner进行重点标注，感到有些遗憾。

**Comment by Kenshin** [comment]
谢谢评价~  😃 
之前有测试过 Liner，由于简悦为了防止 CSS污染，所以没有利用 `<body>` 标签，因此无法在 Liner 下使用。  😩

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

简悦 2.0 包含了自己的 **标注系统**，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
