### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by zysrefuse** [Kenshin/simpread#1505]
发生问题的地址: <https://wenku.baidu.com/view/45c5014d2f60ddccdb38a006.html>

**Comment by Kenshin** [comment]
谢谢反馈，基于某些原因，文库类的页面是不会被适配的。
所以，我关闭这个 Issues 了。

**Comment by zysrefuse** [comment]
明白，利益相关


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kenshin Wang<mailto:notifications@github.com>
发送时间: 2020年12月9日 14:24
收件人: Kenshin/simpread<mailto:simpread@noreply.github.com>
抄送: zysrefuse<mailto:zysrefuse@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Kenshin/simpread] 无法适配当前页面 (#1505)


谢谢反馈，基于某些原因，文库类的页面是不会被适配的。
所以，我关闭这个 Issues 了。

―
