### ISSUE TITLE
支持epub

### ISSUE THREAD

**Issue by yingxincui** [Kenshin/simpread#151]
导出epub，大概类似这样
http://www.jianshu.com/p/f1e44ddf5355

稍后读文章精品汇总导出epub

**Comment by Kenshin** [comment]
谢谢建议  👍 不错，请问这是你的扩展吗？

**Comment by yingxincui** [comment]
不是

发自贺敏杰



发自贺敏杰

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，已增加此功能，此 issues 将会关闭。
