### ISSUE TITLE
代码高亮插件bug

### ISSUE THREAD

**Issue by lhz15621009715** [Kenshin/simpread#1510]
- 操作系统  **Windows10**

- 浏览器版本   **Google Chrome 87.0.4280.88（正式版本） （64 位）**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://blog.csdn.net/dmk877/article/details/50311791l>

**请描述你的问题**

>代码段出现错位问题

**截图**

> 实际：
![图片](https://user-images.githubusercontent.com/49700877/101709689-e5e92a00-3aca-11eb-90ff-887738c0cd0a.png)

> 显示：
![图片](https://user-images.githubusercontent.com/49700877/101710671-f0a4be80-3acc-11eb-9f12-8733dbd54dbd.png)

**Comment by Kenshin** [comment]
谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
