### ISSUE TITLE
动作面板内容消失-定制插件bug

### ISSUE THREAD

**Issue by EveZhangsn** [Kenshin/simpread#1511]
- 操作环境 MacOS. Chrome 87.0.4280.88

- 简悦版本 **2.1.0** 已购高级

**问题**

在使用浮动面板定制器【插件】修改后，阅读模式下的动作面板出现bug，**固定**在了只能显示常用动作的状态（如图）。经过多次刷新，调整设置，重装插件，重装简悦的过程，依旧没有变化。请问有什么处理方法吗？

**截图**
<img width="548" alt="Screen Shot 2020-12-10 at 7 46 53 PM" src="https://user-images.githubusercontent.com/52194306/101771914-9e43bc00-3b25-11eb-9bcd-354cd96b34a3.png">

**Comment by Kenshin** [comment]
嗨，我记得插件有重置功能的？

**Comment by EveZhangsn** [comment]
> 嗨，我记得插件有重置功能的？

感谢这么迅速的回复。您说的重置功能好像需要打开插件的设置界面？现在只显示“常用”，面板里插件设置的入口（之前在最下方）也消失了。我在插件中心里也没有找到重置。另外我试过从禁用插件，也没有效果。

或者麻烦您指点一下还有哪里可以进入设置/重置界面，

**Comment by Kenshin** [comment]
嗨，具体如何查看请看下图

![image](https://user-images.githubusercontent.com/81074/101853918-72fbb400-3b9b-11eb-9bce-186c9097ef41.png)

![image](https://user-images.githubusercontent.com/81074/101853949-7db64900-3b9b-11eb-8104-4f56963cde69.png)

**Comment by EveZhangsn** [comment]
您好，我的问题正在于，对应您的第一个图，我的界面（如问题中截图），看不到插件触发器了。。。

**Comment by Kenshin** [comment]
emm...

哈哈，是不是其它扩展造成的影响？在隐身模式下，仅启用简悦试试。

如果还是不行的话，有个方式可以实现：**修改配置文件**，我再详细跟你说。

**Comment by EveZhangsn** [comment]
刚试了，隐身模式下还是老样子。。。麻烦指点一下修改配置文件的方法吧

**Comment by Kenshin** [comment]
导出配置文件到本地，用文本编辑器打开（最好能格式化下结构，这样看起来舒服点），找到 `plugstorge` 删除掉此节点下的所有内容，再导入到配置文件中。

另外，建议最好备份下。同时方便的话，给我看下，这里面的内容。

**Comment by EveZhangsn** [comment]
神奇的事情发生了，还是老样子。（修改配置重导入，问题依旧，在option里选清除全部插件，插件都没有了，问题还在）

最后我只能彻底重置配置，终于解决了。附上配置文件，感谢您的耐心帮助。
[simpread-config-2020年12月12日 08_50_21 copy.json.zip](https://github.com/Kenshin/simpread/files/5682253/simpread-config-2020.12.12.08_50_21.copy.json.zip)

**Comment by Kenshin** [comment]
嗨，配置文件内含用户信息，我已经下载了并删除了你的提交的配置文件。

另外，请问是高级账户吗？如果是的话，并忘记还原当前配置文件的 UID 为你高级账户的。

**Comment by EveZhangsn** [comment]
非常感谢（我疏忽了），已经恢复高级用户。

**Comment by Kenshin** [comment]
嗨，没问题的话，我关闭此 Issues 了~

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4
