### ISSUE TITLE
备注导出至notion后引用内容和备注内容合并到一起了

### ISSUE THREAD

**Issue by yhkang** [Kenshin/simpread#1512]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Mac**

- 浏览器版本 **Chrome版本 87.0.4280.88（正式版本） (x86_64)**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

![20201211221925](https://user-images.githubusercontent.com/9097097/101914601-758ff500-3bff-11eb-848c-75b73a22c1a9.jpg)

![20201211221852](https://user-images.githubusercontent.com/9097097/101914663-87719800-3bff-11eb-82b1-c8c1231b85de.jpg)

**Comment by Kenshin** [comment]
嗨，请导出 Markdown 到本地看看是否也存在问题？

因为 Notion 对 Markdown 的支持比较奇怪，所以或许会有问题。

**Comment by yhkang** [comment]
> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址 [mp.weixin.qq.com](https://mp.weixin.qq.com/s?__biz=MzU4MzY1MDg5NQ==&mid=2247484418&idx=1&sn=1560859cdfee99f5213e5172900bce60&chksm=fda49f22cad31634487e1d459a0d1ee1c768b60fdee8edbe713442a9510c562efc280414b2ca#rd)

> 独立思考能力 (Independent-mindedness) 似乎更多的是与生俱来的特质（nature) ，而非后天培养的 ( nurture) 
> 
> 这里是备注内容

**Comment by yhkang** [comment]
导出md是上面的内容，看起来正常多了。
不过能否把备注内容成单独段落，不要和原文你内容在一个引用段落里，像下面这样会好一点？

> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址 [mp.weixin.qq.com](https://mp.weixin.qq.com/s?__biz=MzU4MzY1MDg5NQ==&mid=2247484418&idx=1&sn=1560859cdfee99f5213e5172900bce60&chksm=fda49f22cad31634487e1d459a0d1ee1c768b60fdee8edbe713442a9510c562efc280414b2ca#rd)

> 独立思考能力 (Independent-mindedness) 似乎更多的是与生俱来的特质（nature) ，而非后天培养的 ( nurture) 

这里是备注内容

**Comment by Kenshin** [comment]
@yhkang 

考虑一下这个改动~  😀  （ 目前以我个人的测试结果看的话，加上 `> xxx` 是比较好看的一种展示方式，但确实需要跟原文有所区分

没问题的话，我先关闭这个 Issues ~
