### ISSUE TITLE
在稍后读浏览页面时当标题含有特殊字符会出现导出失败的问题

### ISSUE THREAD

**Issue by PeakmanCheung** [Kenshin/simpread#1516]
发生问题的站点都是企鹅家的，以下两个，无论是html、md、pdf都无法导出：
https://mp.weixin.qq.com/s/p4CifR4fAV627j8kHFevHA

https://xw.qq.com/cmsid/20201210A04VQG00

**Comment by Kenshin** [comment]
嗨，收到~
我知道是什么问题了，造成失败的原因是：标题含有特殊的字符导致无法下载成功。你安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件再试试。

另外，Mac 下我测试通过，Win 下没有测试。

**Comment by Kenshin** [comment]
@PeakmanCheung 

哈哈，我也发现这个 Bug 了，需要同步助手帮忙修复了，扩展端需要等下个版本修复才行~

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
