### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by carocaro** [Kenshin/simpread#1517]
发生问题的地址: <https://weread.qq.com/web/reader/8fe327b071fdfc748fe8fe7k19c3222022419ca14e7eef7>
能否解决微信读书web版的适配呢？默认的不论是字体还是行距都好难受啊

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
微信读书是可以适配的，但由于某些原因我没有放这个站点的适配规则，希望可以理解。  😅
