### ISSUE TITLE
简悦中展示与原文章内容不一致

### ISSUE THREAD

**Issue by starsight** [Kenshin/simpread#1518]
问题url：https://juejin.cn/post/6844903911602683918#heading-9

原展示
![image](https://user-images.githubusercontent.com/8342806/102014529-66d94780-3d91-11eb-8d05-190cbdb3e8c5.png)

简悦中展示
![image](https://user-images.githubusercontent.com/8342806/102014540-78225400-3d91-11eb-9b9b-b090f6146b09.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
这是属于 代码高亮问题，我会统一记录到 #500 里面，并关闭此 Issues 修复后会通知你~
