### ISSUE TITLE
导出pdf失败，提示此功能为实验性功能，有需求请提issuses

### ISSUE THREAD

**Issue by ChenYNan** [Kenshin/simpread#1524]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10**

- 浏览器版本 **Microsoft Edge 87.0.664.60 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.52pojie.cn/forum.php?mod=viewthread&tid=1301790&extra=&highlight=%C7%C0%B9%BA&page=1>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

导出pdf失败，提示此功能为实验性功能，有需求请提issuses
**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![QQ图片20201214170518](https://user-images.githubusercontent.com/34770219/102061552-925e3f80-3e2e-11eb-929a-1f8064fae00c.png)

**Comment by Kenshin** [comment]
2.0 版本的 PDF 使用了浏览器自带的功能。
你可以使用 2.1 版本配合 同步助手（仅限高级账户）可以实现完美的 PDF 输出。
如下图：

[华为 mate40pro 抢购自用神器开源 - 请所有人更新最新版修复 BUG - 『精品软件区』  - 吾爱破解 - LCG - LSG - 安卓破解 - 病毒分析 - www-52pojie-cn.pdf](https://github.com/Kenshin/simpread/files/5688131/mate40pro.-.BUG.-.-.-.LCG.-.LSG.-.-.-.www-52pojie-cn.pdf)

***

当然，2.1 版本的 PDF 也存在一些问题：如果图片有防盗链的功能，则在 PDF 中无法显示，我会在下个版本解决这个问题。

**Comment by Ghibni** [comment]
简悦2.1版本，浏览器是edge版本 88.0.705.56，系统是win10，也出现了这样的情况，“导出pdf失败，提示此功能为实验性功能，有需求请提issuses”
请问如何解决啊？

**Comment by Ghibni** [comment]
已经解决了，是特殊字符原因，安装插件后解决了~
