### ISSUE TITLE
高亮侧栏显示bug和相关问题

### ISSUE THREAD

**Issue by hlc1209** [Kenshin/simpread#1526]
1. 如图，看蓝色部分。右侧边栏的内容不全（导出到notion后倒是全的）。左边选区高低不同
![屏幕截图 2020-12-14 205947](https://user-images.githubusercontent.com/45445824/102173193-5b4c5600-3e4f-11eb-8a1b-eb811907f817.png)

2. 高亮模式下选择一些文字会改变其原来的格式，比如字体和加粗属性。

3. 使用仅导出高亮，到notion后，所有文字都是title状态。建议默认普通文本状态，或者自动设置

出现以上问题的link：https://www.zhihu.com/question/24361064/answer/1124883669

**Comment by hlc1209** [comment]
另外，点击浏览器的扩展图标，当前是直接进入阅读模式，能否有选项能调成聚焦模式？阅读模式在很多情况下显得有点“大动干戈”，其实网站内的其他元素也经常是要看的，比如看知乎的时候。聚焦模式往往更普适些

**Comment by Kenshin** [comment]
谢谢反馈~

> 问题1 &2：

是主题的问题，你更换一个主题就好了。（所以也算是 Bug，我研究下，毕竟要保持样式一致。

> 问题3：

Notion 对 Markdown 的支持比较奇怪，建议你导出 Markdown 看看是否也存在问题。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
