### ISSUE TITLE
onenote 无法重新授权

### ISSUE THREAD

**Issue by wshzz001** [Kenshin/simpread#1528]
- 操作系统 **Win10**

- 浏览器版本 **EDGE 版本 87.0.664.60 (官方内部版本) (64 位)**

- 简悦版本 **2.1.0**

- 发生问题的地址 https://blog.csdn.net/zhangshuaizaxia/article/details/50580383

现象：提示onenote需要重新授权，点击授权后跳转到设置界面，提示授权中，几分钟后，没有弹出授权成功或失败的提示，重新打开网页后导出到onenote，依旧提示未授权。

**Comment by wshzz001** [comment]
授权成功了。
方法如下：我这边开了2个EDGE窗口，其中一个窗口始终无法授权成功，在另一个窗口授权，马上就成功了。

**Comment by Kenshin** [comment]
哈哈，搞定就好~

不过，这么「玄学」吗？我从没遇到过你的说的问题。
