### ISSUE TITLE
无法从右键菜单进入阅读模式

### ISSUE THREAD

**Issue by fengyn** [Kenshin/simpread#153]
Chrome 62.0.3202.94下无法从右键菜单中进入阅读模式，快捷键与点击右上角红色图标能正常进入。

**Comment by Kenshin** [comment]
哈，的确~  😀 
这是个 Bug，感谢反馈，下个版本（下周）会修复这个问题~  👍

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，修复此问题，此 issues 将会关闭。
