### ISSUE TITLE
BUG 报告，sspai网页无法看全？

### ISSUE THREAD

**Issue by jiangaq** [Kenshin/simpread#1530]
https://sspai.com/post/58739

无法看整篇文章。

**Comment by binsee** [comment]
仍然是解析页面注释的bug导致
![image](https://user-images.githubusercontent.com/5285894/115111264-13cb0780-9fb2-11eb-8398-2bac41677946.png)

**Comment by Kenshin** [comment]
@binsee 

谢谢提示。

@jiangaq 
目前暂时只能使用聚焦模式，下个版本可能来不及修复这个问题了，但我会出一个补丁版本。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
