### ISSUE TITLE
15日付款，现在还没收到兑换码邮件。

### ISSUE THREAD

**Issue by qinjiong-star** [Kenshin/simpread#1537]

**Comment by Kenshin** [comment]
嗨~

这两天在出差，所以**目前 16 / 17 两天是没有兑换**的。（今天 19点兑换。
如果你是在 **15日19点之后付款的也是一样的情况**。

PS：我关闭这个 Issues 了，如果你着急的话，请通过腾讯问卷的联络方式用腾讯问卷填写的邮件给我发邮件，附上付款的截图。
我看能否给你手动操作。
