### ISSUE TITLE
关于选中文字后悬浮工具条的优化建议

### ISSUE THREAD

**Issue by reikos-day** [Kenshin/simpread#1539]
我使用的是edge简悦浏览器插件2.0版，以下问题很久之前碰到，但最近看来还没有优化，也有可能是我操作有误，故此来反馈并寻求指导。
我的问题与建议如下：
![image](https://user-images.githubusercontent.com/46397379/102569937-4e668580-4121-11eb-94df-1d171ed340f9.png)
图1
1.悬浮工具条的位置问题，如图1所示，目前来看悬浮工具条是在选中文字的中间上方出现，但是这样的位置很尴尬，首先是一般选中完文字后，鼠标是在文字末尾，而工具条很远，需要再移过去点选颜色，当然能顺利点上还是好的，经常遇到点不上的情况，就是当我的鼠标追随工具条过去的时候，会移动到我之前选中的文字中，比如我是想高亮“笔记应该尽可能……”但移过去后，工具条自动切换成“记笔记……”这行文字的，我选不到我想要的
“笔记应该尽可能……”这行文字的工具条。

![image](https://user-images.githubusercontent.com/46397379/102570413-3e9b7100-4122-11eb-87d8-7e72fe8f3ed7.png)
图2
2.添加备注之后的问题
备注显示不全，如图2，并且容易出问题，比如图1，我备注后的内容根本看不到。
3.操作问题
是否有相关的键盘快捷键来进行高亮、备注等操作呢？因为每次选中后，去找悬浮工具条有一个停顿的过程，并且这个过程不算流畅。可否先设置一个“笔”的选择，这样可以连续高亮文本，而至于每次选中文字后都要去点击，使用快捷键来切换到备注等功能。

**Comment by Kenshin** [comment]
谢谢反馈。

> 一般选中完文字后，鼠标是在文字末尾，而工具条很远

确实有你说的情况，也是考虑不足。

不过，目前可以有以下两个弥补方案：

1. 单击 → 在高亮上单击会更换高亮颜色
2. 双击 → 会弹出编辑框。

（当然，我发现个别情况下，单击会被识别为双击，但不清楚是鼠标问题，还是 Bug  😂 

> 备注显示不全

目前确实这样的，因为没法显示完全的备注，备注是没有字数限制的，且还有可能包括换行等操作，再加上以后可能支持更多格式。
所以，这里的备注仅做提示用。

> 相关的键盘快捷键来进行高亮...

你可以使用快捷键 <kbd>sr</kbd> 来查看全部的快捷键一览。

另外，简悦支持连续标注。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
