### ISSUE TITLE
求适配 CBN Weekly

### ISSUE THREAD

**Issue by ImSingee** [Kenshin/simpread#154]
https://www.cbnweek.com/articles/magazine/18073

类似于上面的网址，另外，现在使用「临时阅读模式」生成的这个网站样式太丑了。。

**Comment by Kenshin** [comment]
okay ，适配的版本将会跟 1.0.5 一起发布（预计本周，最迟下周）~
`临时阅读模式` 类似其它同类产品的 `阅读模式` 所以在适配上肯定没有专门适配的好用。 😃

**Comment by Kenshin** [comment]
新增了一批新站，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

除此之外，还包括一批「不存在」的网站，如上述提及的，具体操作方式请看下图
![image](https://user-images.githubusercontent.com/81074/40884334-501fe6c8-6744-11e8-8d39-3ffa6ed2e41a.png)
