### ISSUE TITLE
标注编辑框的结构与样式需要重构

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#1541]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows **

- 浏览器版本 **e.g. edge8**

- 简悦版本 **2.1.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题** 

> 备注框出现重影

**截图**

> 
![无标题](https://user-images.githubusercontent.com/37976371/102580042-c12f2b00-4138-11eb-81ed-349068e35f3d.png)

**Comment by rw1995** [comment]
浏览器是edge最新的， 简悦也是最新的，刚开始我还以为是自己眼睛花了=-=

**Comment by Kenshin** [comment]
哈哈，我感觉我也眼花了... 

我没有通过你的截图看到 **备注的重影**  😂

**Comment by rw1995** [comment]
> 哈哈，我感觉我也眼花了...
> 
> 我没有通过你的截图看到 **备注的重影** 😂

你看见“默认富文本”这个字样了吗，在底部  “某个指定的停止准则后体停止算法”二者有明细的区别

**Comment by Kenshin** [comment]
额...
这个地方「原本」就是存在重影的。 😅 

PS：这里的界面是需要优化了，下个版本发布。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
