### ISSUE TITLE
少数派购买用户输入兑换码之后提示后台服务器出了问题

### ISSUE THREAD

**Issue by zgx1996** [Kenshin/simpread#1543]
少数派购买用户输入兑换码之后提示后台服务器出了问题，详情见以下链接图片
[https://ftp.bmp.ovh/imgs/2020/12/8f98c1b7a5bd1283.png](url)

**Comment by Kenshin** [comment]
嗨，请根据 https://github.com/Kenshin/simpread/issues/1334 修改你的设置。 😀
