### ISSUE TITLE
关于网站文章本身的字体格式，例如加粗，划线，某些高亮和带颜色的段落

### ISSUE THREAD

**Issue by hongbaio** [Kenshin/simpread#1544]
能否保留文章一些本身的布局，例如文字的加粗，强化等等，

**Comment by Kenshin** [comment]
嗨，这是没有办法的事情。
在 HTML 增加一些 `style` 的属性会被删除掉，因为没办法分辨哪些是正确的，哪些是没必要的样式。

如果非要这么做的话，建议使用 **聚焦模式**，而非阅读模式。 

😀

**Comment by hongbaio** [comment]
原来如此，谢谢解答

**Comment by Kenshin** [comment]
哈哈，没事。
