### ISSUE TITLE
笔记导出适配为知笔记私有部署

### ISSUE THREAD

**Issue by TankNee** [Kenshin/simpread#1545]
现在简悦的为知笔记导出好像只能导出到官方的服务器，因为为知开放了私有部署，所以我建议在配置为知笔记项的时候可以加一个私有部署URL的设置。
要是在导出的时候还能选择导出的文件夹就更棒了！
还有登录方式，是否可以参照[WebClipper](https://github.com/webclipper/web-clipper)那个项目的实现？似乎可以直接通过本地cookie来实现登录，而不需要记录账户密码！

**Comment by Kenshin** [comment]
> 私有部署的问题

需要简悦提供什么？仅 URL 就行吗？

> 登录方式

目前就是使用 Cookies 的方案，并没有让用户输入用户名和密码。

***

另外，简悦也不会保存你输入的用户名和密码。甚至在导出时默认也不会包含这些。再甚至简悦后端都没有任何用户的数据（包括稍后读等数据均没有存。

简悦仅有的只是你的高级账户信息与某些你授权后我才知道的信息。

从某种程度上，我比用户还要重视隐私。（简悦的官网已经说的很清楚了。 😀

**Comment by TankNee** [comment]
> > 私有部署的问题
> 
> 需要简悦提供什么？仅 URL 就行吗？

理论上是的，只要把官方的url替换成私有部署的url就行。不然有些私有部署没有买官方的license就没办法同步保存的笔记。

> > 登录方式
> 
> 目前就是使用 Cookies 的方案，并没有让用户输入用户名和密码。
> 

![image](https://user-images.githubusercontent.com/43956168/102704662-5e18d200-42b9-11eb-90c9-3e6422b705b8.png)
为知笔记好像需要输入用户密码？

**Comment by Kenshin** [comment]
私有 URL 功能我先记一下，只能下个版本发布了。

关于登陆的问题，那就是我记错了，应该是有道笔记取 Cookie 
回头看下具体实现流程。😂

**Comment by yangxue088** [comment]
同求这个功能，NAS上私有部署了为知笔记，WebClipper的页面截取能力不强，还是简悦的论坛模式比较好，麻烦大佬关注下。

**Comment by Kenshin** [comment]
@yangxue088 

嗨，可以考虑的。

**Comment by Kenshin** [comment]
@yangxue088 @TankNee 

嗨，我这几天在 Fixed 一些 Bug。

我想试试私有部署的事情，你们请问谁能提供给我测试账户和接口？以及你们是否可以使用 TG 直接找我？方便我调试~

TG 的话，进群 https://t.me/simpreadgroup 找我就好~

**Comment by TankNee** [comment]
@Kenshin 给你发邮件了，请查收

**Comment by Kenshin** [comment]
@TankNee 

okay 收到，我现在测试，且都是少数派的文章，请留意。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

注意：

1. 为知笔记的**授权时间简悦无法控制**，但**增加了过期自动重新授权的机制**。
2. 增加了为知笔记的私有部署方案

![image](https://user-images.githubusercontent.com/81074/121987877-ed67f380-cdcb-11eb-8d4e-b9d05a56bbf9.png)


## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

## 评分

Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
