### ISSUE TITLE
怎样关闭【请确保已运行简悦同步助手】提示

### ISSUE THREAD

**Issue by carocaro** [Kenshin/simpread#1546]
想保持后台运行的东西越少越好，不需要时不会打开同步助手，然后就导致无论打开什么页面的都会跳出这个东西
![Screenshot - 2020-12-20 11 30 54](https://user-images.githubusercontent.com/5353006/102704496-0ed1a200-42b7-11eb-86e2-83a95f90ba81.png)

怎么关掉这东西？

**Comment by Kenshin** [comment]
弹出提示的前提是：**你授权简悦使用了此功能，但没有开启同步助手** 导致的。

在哪里开启此功能的就在哪里关闭它。

请关闭以下选项即可

![image](https://user-images.githubusercontent.com/81074/102704644-2c077000-42b9-11eb-8f1c-4df925bf6b24.png)

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
