### ISSUE TITLE
百度贴吧支持不太好，翻页失效了，每次翻页都会退出阅读模式：

### ISSUE THREAD

**Issue by BinLafeng** [Kenshin/simpread#1547]
**请说明发生问题的环境**

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://tieba.baidu.com/p/4244232993?pn=1>

**请描述你的问题**

> 百度贴吧支持不太好，翻页失效了，每次翻页都会退出阅读模式

**Comment by Kenshin** [comment]
请按照下图所示设置，之后就可以自动进入阅读模式了。

位置在选项页

![image](https://user-images.githubusercontent.com/81074/102734952-21fa7580-437c-11eb-8433-ac1ad1a14a26.png)
