### ISSUE TITLE
无法排除页面

### ISSUE THREAD

**Issue by ImSingee** [Kenshin/simpread#155]
当开启了「自动进入阅读模式」后，设置了排除「mp.weixin.qq.com」后，进入微信公众号后台仍然会试图进入「阅读模式」，并且每一次点击都会提示「当前页面结构改变导致不匹配阅读模式」

**Comment by Kenshin** [comment]
我没有发生你说的问题，操作步骤：

1. 将 `mp.weixin.qq.com` 加入到 排除列表；
2. 虽然访问一个网址 如 https://mp.weixin.qq.com/debug/wxadoc/introduction/ 并没有自动进入阅读模式。

PS：我随机找了几个类似的 url 也没有发生你说的问题，比如：

https://mp.weixin.qq.com/s?__biz=MzIyMTI0MDY1NA==&mid=2651160145&idx=1&sn=6a76f997387d134350033792d4b532f1&chksm=f3ce1270c4b99b66c84aa85d7807919d0a5f284ca78517b54933291a29a9046d61f64b7a7b40&scene=21
https://mp.weixin.qq.com/debug/wxadoc/dev/

另外，请确保你进入的 url 参数里面不不包含 `simpread=read` 因为它的优先级要大于 `排除列表`

**Comment by ImSingee** [comment]
![image](https://user-images.githubusercontent.com/11208082/33008301-82926868-ce0d-11e7-8dc9-9dabe41f6d47.png)
![image](https://user-images.githubusercontent.com/11208082/33008312-8e0b9bf6-ce0d-11e7-9014-26cbbc029a32.png)
![image](https://user-images.githubusercontent.com/11208082/33008329-9dd37bd0-ce0d-11e7-9f29-60e0df673e3e.png)

图三：我的设置；
图一：设置后访问上面的第二个网页的效果
图二：点击右上角的图标试图关闭时，无法关闭

**Comment by Kenshin** [comment]
@ImSingee 
排除列表加错了~

排除列表支持两种方式：
- url e.g. 你截图所示的 url
- host e.g. `mp.weixin.qq.com`

所以，仔细看我之前的留言，加入排除列表的是 `mp.weixin.qq.com` 而非 url ，即可将此域名下的全部 url 禁用自动进入功能。

PS：[排除列表的说明](https://github.com/Kenshin/simpread/wiki/faq#%E6%8E%92%E9%99%A4%E5%88%97%E8%A1%A8)

此 issues 将会关闭~  😀

**Comment by oknixus** [comment]
@Kenshin 你好！我也是遇到了这个问题，然后看了这个issue搞定了；但是发现个问题，比如这个页面：https://developers.weixin.qq.com/miniprogram/dev/
就不行，还是会启用阅读模式。但是其他的页面，比如框架、组件等，就不会启用阅读模式；
![image](https://user-images.githubusercontent.com/4592706/40953193-43ac01a6-68b1-11e8-90df-0189f7d4185c.png)
我是这么设置的

**Comment by Kenshin** [comment]
@oknixus 
把 `index.developers.weixin.qq.com` 加入到排除列表 即可。

你可以通过 阅读模式 → 侧栏 → 站点编辑器 查看当前对应的 name 是什么。

**Comment by oknixus** [comment]
谢谢！明白怎么用了！

**Comment by Kenshin** [comment]
@oknixus 
搞定就好，写的还是不太详细...

**Comment by oknixus** [comment]
已经很棒了！而且还这么热情的回复，真的非常棒！
