### ISSUE TITLE
[适配需求调查]哔哩哔哩笔记功能，用简悦解决笔记导出功能

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#1550]
## 首先
- 这是个需求意见征集，而非提出需求。

我发现个有意思的功能，可能有潜在用户，但不确定有没有真的需要，因此提出来看看，如果确实有人需要，我会来做这个适配，如果没有人需要就跳过。

## 需求说明

在b站发现视频详情页有个存在感薄弱、但实际上有用的笔记功能，可以超便捷的在看视频时对视频内容同步做笔记，但其笔记界面却并不太利于阅读且没有导出功能。

用户笔记列表页面url： `https://space.bilibili.com/{用户uid}/favlist?fid=note`

- 视频播放页做笔记
![image](https://user-images.githubusercontent.com/5285894/102721797-fd7caa00-4337-11eb-91ba-8f6856e309e5.png)

- 笔记列表中查看笔记
![image](https://user-images.githubusercontent.com/5285894/102721799-ffdf0400-4337-11eb-96b4-229cd842a461.png)

## 需求要解决的问题

- 以更利于阅读的版面显示已做的笔记
- 通过简悦的排版显示后，就可以使用简悦来将当前笔记随意导出了（重点目标，因为当前哔哩哔哩没有提供导出功能）

### 附加特性

- 适配需要懒加载，必须要手动按AA进入阅读模式，否则会影响显示笔记列表。
- 阅读模式提取时最好是将插入的视频时间标记转化为指向视频的链接，以保留笔记的关联。**这条需要在js代码中处理**

## 补充

- b站上还有有少数用户想要导出功能的：https://www.bilibili.com/read/cv8229275/ 评论区

**Comment by Kenshin** [comment]
嗨，我觉得非常可以~  🙏 

老办法，你可以用 PR 的方式提给我。

PS：适配后我会马上发布这个站点到官方适配列表，并做一些适度的宣传

**Comment by binsee** [comment]
> 老办法，你可以用 PR 的方式提给我。

今晚提交pr。

**Comment by binsee** [comment]
## 适配特性

- 阅读模式开头增加视频链接
- 笔记中的视频时间点标记将标记为链接，点击后打开视频对应时间点


## 特别提示

- 务必将 https://space.bilibili.com/** 加入排除列表，然后在笔记页面中点击要导出的笔记后，手动AA进入阅读模式
- 由于笔记图片是通过cookie来从服务器获取，因此无法作为外链使用。要在其他地方使用图片请导出为离线html
- 导出的pdf会无法显示图片，可先导出为 **离线html**，打开后再打印为pdf文档


## 显示效果

- 哔哩哔哩笔记页面显示效果
![image](https://user-images.githubusercontent.com/5285894/102804958-75f57080-43f5-11eb-8546-b42a2a2c8001.png)

- 导出为离线html显示效果
![image](https://user-images.githubusercontent.com/5285894/102806053-257f1280-43f7-11eb-8866-8114e7b40548.png)

- 导出为md，使用Typora打开
![image](https://user-images.githubusercontent.com/5285894/102807960-93790900-43fa-11eb-9df3-9b24505baa0d.png)

**Comment by Kenshin** [comment]
嗨，已 Merge PR 并更新了 **官方主适配源**，同时记录上述内容到 https://github.com/Kenshin/simpread/discussions/1583 

PS：以后 Discussions 专门作为 **使用技巧** **通知** **高级账户** 等的专门 QA 渠道（相比 Issues 来说，Discussions 更擅长做这些。

所以，我关闭此 Issues 了~  🙏
