### ISSUE TITLE
什么值得买网站滚动卡顿

### ISSUE THREAD

**Issue by shangfabao** [Kenshin/simpread#156]
什么值得买网站下拉滚动卡顿,不知道什么问题

**Comment by Kenshin** [comment]
感谢反馈~
虽然是极小概率，但的确有这样的情况存在（应该有三名用户反映过）但我这边一直无法重现，所以不清楚是什么问题导致...  😥 

建议将 `post.smzdm.com` 加入到黑名单，然后手动进入需要的页面，看看是否仍有这个问题。

**Comment by shangfabao** [comment]
关闭阅读模式是没有这个问题的,我用的chrome62.0.3202.94

**Comment by Kenshin** [comment]
@shangfabao 
我的意思是，不自启动阅读模式，而是手动进入阅读模式。

**Comment by howei6** [comment]
我也出现这个问题（双击A启动阅读模式），不知道是什么原因。
![default](https://user-images.githubusercontent.com/22789316/33994441-6fa05c36-e115-11e7-9597-e362148e69a1.PNG)

**Comment by Kenshin** [comment]
@howei6 
感谢反馈~ 跟你给出  console 没有什么关系，我再调查下吧。

@shangfabao @howei6 
这个问题比较奇怪，所以最好能提供 url 给我（或许你们觉得 每个 url 都有问题...   😥  ）

**Comment by 9h0st** [comment]
http://blog.csdn.net/carson_ho/article/details/79168523
这个进入阅读模式 滚动时也很卡

**Comment by Kenshin** [comment]
@9h0st
感谢反馈，你的问题估计是 TOC 导致的，我现在没法确认，请问文章生成后的目录是否很长？

**Comment by 9h0st** [comment]
![screenshot](https://user-images.githubusercontent.com/7588390/37325976-f2cd3e6c-26ca-11e8-8b55-6db109993562.png)
目录是这样的 不知道是不是你认为的很长

**Comment by Kenshin** [comment]
@9h0st 
天啊，你是怎么又突然回复这个 issues 的...
的确很长的目录。  😂

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，
具体原因是 TOC（有锚点的功能）与当前页面的功能重复，暂时没有好的解决方案，所以在这个页面无法显示 TOC。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
