### ISSUE TITLE
最近通过google 应用商铺添加，提示错误

### ISSUE THREAD

**Issue by jiedengye111** [Kenshin/simpread#157]

**Comment by Kenshin** [comment]
之前从未有过这个问题，建议用其它方式将 crx 下载到本地，或离线下载。
回复晚了  😢

**Comment by Kenshin** [comment]
@jiedengye111 
访问 https://chrome-extension-downloader.com/ 

输入 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

选择 「Download extension」 

下载后，拖拽到 `chrome://extensions` 即可。（此种方式与从 Chrome webstore 下载一样。）

**Comment by Kenshin** [comment]
以后我会在每个 release 下面加入当前版本的 Chrome webstore 版，方便类似你这样问题的人直接下载。

[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，对应的 release 下载地址：

https://github.com/Kenshin/simpread/releases/tag/1.0.5

此 issues 将会关闭~
