### ISSUE TITLE
chrome简悦插件自动卸载

### ISSUE THREAD

**Issue by abyssedll** [Kenshin/simpread#1578]
**发生问题的环境**

- 操作系统 **Windows 10 v19042.630**

- 浏览器版本 **Chrome 87.0.4280.66（正式版本）（64 位）**

- 简悦版本 **2.1.0**

**我的问题**

> K大好！我的简悦chrome插件，总是过两天就无缘无故自动消失了，非常奇怪。求问如何解决？谢谢！

**截图**

> 截图是在用的所有chrome插件，难道是插件间有冲突？
![微信截图_20201221163153](https://user-images.githubusercontent.com/75288385/102756017-3a818480-43aa-11eb-96fd-669f71aa7981.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

看截图好像是使用的 **离线版本** ？（即：通过开发者模式加载的简悦？）

如果是的话，不要用拖拽安装的方式；
正确的方式：将 `zip` 解压缩到某个文件夹，再通过 **加载已解压的扩展程序** 来加载。

***

初步怀疑使用拖拽的安装方式会把简悦安装到某个临时目录（有可能被你的系统某些防护软件给自动删除了，或者 Chrome 自己删除了...

***

PS：很久没有听到 **K大** 这个词了，难道是老用户？   😀

**Comment by abyssedll** [comment]
好的！的确之前都是拖拽安装的😂现在已经通过 **加载已解压的扩展程序** 安装，观察几日再来反馈：）
因为简悦结缘，**K大**是我出于感谢的尊称，相信以后会成为老用户的😁

**Comment by Kenshin** [comment]
okay 那我先关闭此 Issues  **如果仍旧发生此问题，请再重开**。

PS：**K 大** 是我以前混其它「圈子」时的称谓，哈哈。

**Comment by abyssedll** [comment]
谢谢K大，插件没再被chrome删掉了🤓新年快乐！

**Comment by Kenshin** [comment]
@abyssedll 

搞定就好~ 新年快乐。 😁

**Comment by TrueHOOHA** [comment]
> 谢谢K大，插件没再被chrome删掉了🤓新年快乐！

a大你好

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
