### ISSUE TITLE
标注时有一定机率会被上一行遮挡导致浮动工具条定位错误而无法标注

### ISSUE THREAD

**Issue by fengmao31** [Kenshin/simpread#1580]
1.一行会影响下一行的标注。导致下一行无法标注
2.点击已标注会变色。一直点会循环变。感觉有时候误点标注变色，又得操作变回来，造成了标注工作效率下降。
![image](https://user-images.githubusercontent.com/19343842/102766056-84716700-43b8-11eb-8dbf-574ecebdab3e.png)

**Comment by Kenshin** [comment]
哈哈，你这新开 Issues 的速度比我回复的速度还快...

***

在已标注的位置可通过：

1. 单击 → 改变颜色
2. 双击 → 弹出标注编辑框

的方式得到改善。

**Comment by Kenshin** [comment]
> 点击已标注会变色。一直点会循环变。感觉有时候误点标注变色，又得操作变回来，造成了标注工作效率下降。

话说，为什么要 **无意识的点击已存在的标注** ？ 😅

**Comment by fengmao31** [comment]
这是对插件的热爱啊。
————————————————————————————————————————————————————————
![image](https://user-images.githubusercontent.com/19343842/102767358-6442a780-43ba-11eb-8cd2-69d733b3df91.png)
像这种情况下，选颜色是时候，就会被上一行影响，标注不了
![image](https://user-images.githubusercontent.com/19343842/102767419-7fadb280-43ba-11eb-9774-d7f8e37c194a.png)

**Comment by Kenshin** [comment]
> 这是对插件的热爱啊。

建议你启用 **连续标注**，就可以通过我说的方式（暂时解决）。

***

我先留着这个 Issues 吧，等彻底解决这个问题后再关闭它。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
