### ISSUE TITLE
谷歌扩展程序页面会提示错误

### ISSUE THREAD

**Issue by myly-zyr** [Kenshin/simpread#1582]
<!--**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10 64**

- 浏览器版本 **e.g. Chrome 87.0.4280.88**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>
chrome://extensions/?errors=oilfigpmdcogagnbekppfgmlkbhjbljc
**请描述你的问题**
在谷歌扩展程序页面会提示错误 在全部清除之后仍会重新提示 而且我在使用的过程中出现了简悦随机自动卸载的情况 卸载后只能重新安装 但是这个问题不确定触发场景 不能复现
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![无标题](https://user-images.githubusercontent.com/47034150/102838192-92ff6300-4438-11eb-87e9-60a8307e7151.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by myly-zyr** [comment]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10 64**

- 浏览器版本 **e.g. Chrome 87.0.4280.88**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>
chrome://extensions/
**请描述你的问题**
谷歌扩展程序页面提示错误 并且在全部删除之后仍会重新提示 
同时我使用简悦插件过程中存在随机的自动移除情况 只能重新安装才能使用 该问题的触发条件不确定 但是两次重装之后均会复现  不确定是不是与扩展程序页面提示错误有关
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/47034150/102838575-87f90280-4439-11eb-8eb1-25dd7effad5c.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，不用理会这个问题。
它不会影响任何简悦的使用。

如果它影响了你的使用，请重开这个 Issues ~  😀
