### ISSUE TITLE
阅读模式对CSDN支持有问题

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#159]
__起因：__

CSDN好像比较WS地加了一个“点击阅读全文”功能。个人猜测是为了防止采集的。目前阅读模式对改版后的CSDN支持不好，只能使用聚焦模式

__复现：__

1. 进入CSDN
1. 随便找一个长一点的文章
1. 右键-阅读模式，没反应
1. 点击阅读全文，（登录），右键-阅读模式，没反应

__其他：__

- 开了Adguard插件
- Chrome 版本 62.0.3202.94（正式版本） （64 位） #153

**Comment by Kenshin** [comment]
153 已经修复，上周家里出了些事情需要处理，耽搁了，本周发布。
CSDN 的问题明天会确认，另外用临时阅读模式可以访问吗？如果只是右键的问题，则是 153 导致的。

**Comment by Kenshin** [comment]
@jinyu121 
刚刚看了下，只是标题无法获取到了，其它都 ok，标题

`<span class='link_title'>` 

改为

`<h1 class='csdn_top'>` 

即可。 😀  感谢反馈~
