### ISSUE TITLE
default locale is defined but default data couldn't be loaded

### ISSUE THREAD

**Issue by jiedengye111** [Kenshin/simpread#160]
为什么下载出现这个问题，能给个解决方案吗

**Comment by Kenshin** [comment]
不清楚是什么原因，最好能截图，不过，可以解决，解决方案 https://github.com/Kenshin/simpread/issues/157

**Comment by Kenshin** [comment]
以后我会在每个 release 下面加入当前版本的 Chrome webstore 版，方便类似你这样问题的人直接下载。

[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，对应的 release 下载地址：

https://github.com/Kenshin/simpread/releases/tag/1.0.5

此 issues 将会关闭~
