### ISSUE TITLE
导出pdf提示不是高级账户

### ISSUE THREAD

**Issue by DevinFu** [Kenshin/simpread#1604]
问题现象和issue#1479一样，但那个issue被关闭了并没有说怎么解决，麻烦帮忙看下

**Comment by Kenshin** [comment]
嗨，建议详细说明下，或者看看 https://github.com/Kenshin/simpread/discussions/1567 也有可能是这个问题造成的。

**Comment by DevinFu** [comment]
![image](https://user-images.githubusercontent.com/3973163/103051939-e6a5b400-45d2-11eb-9582-cc36b8542441.png)

错误如截图所示，和 #1479 问题一样，我已经是高级账号了，需要提供用户id给你吗？

**Comment by Kenshin** [comment]
@DevinFu 

其它高级账户的功能都可以使用吗？另外，请问运行简悦 · 同步助手了吗？

另外看下 https://github.com/Kenshin/simpread/discussions/categories/重要通知 里面关于 PDF 的一些使用，看看是否有你需要的？

**Comment by DevinFu** [comment]
其他高级功能可以使用。
上周没安装同步助手，就无法导出pdf。
昨天我安装了同步助手，也同样无法导出pdf。报错原因一样。
我是mac版系统

**Comment by Kenshin** [comment]
emm....
确实很奇怪。不过，感觉应该还是配置错误造成的。
你把全部跟 PDF 有关的选项都截图给我看下。（包括：同步助手）

**Comment by DevinFu** [comment]
![image](https://user-images.githubusercontent.com/3973163/103086634-15964700-4620-11eb-8df9-ec9ffce30ea3.png)
这是chrome插件的设置

**Comment by DevinFu** [comment]
![image](https://user-images.githubusercontent.com/3973163/103086885-cbfa2c00-4620-11eb-8a7e-02e2cc6622af.png)
这是同步助手的设置。

还需要其他设置的截图吗？

**Comment by binsee** [comment]
就是同步助手中导出路径的问题，手动指定一个导出目录，然后再测试应该就可以了

2020-12-24 19:47 GMT+08:00, Devin.Fu <notifications@github.com>:

**Comment by DevinFu** [comment]
我移除插件后重新安装插件后解决了。

**Comment by DevinFu** [comment]
移除插件后重新安装插件后解决了。
