### ISSUE TITLE
简悦 同步助手发送邮件报错

### ISSUE THREAD

**Issue by east4ming** [Kenshin/simpread#1608]
![image](https://user-images.githubusercontent.com/13358726/103114051-38644200-4698-11eb-9572-e91001f5d78a.png)
windows机器.

**Comment by Kenshin** [comment]
请告知详细环境，同时是否Email 发送是否配置成功？（方便截图给我看下，注意隐藏你的密码）

**Comment by east4ming** [comment]
详细环境: (公司电脑)



Email已经配置成功了. (昨晚用个人电脑, 同样配置发送email成功)

谢谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 上午10:32
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"凯西Casey"<cuikaidong@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 简悦 同步助手发送邮件报错 (#1608)





 
请告知详细环境，同时是否Email 发送是否配置成功？（方便截图给我看下，注意隐藏你的密码）

**Comment by Kenshin** [comment]
感觉是不是你公司的环境禁用了某些端口？
你回家后试试是否仍可以成功？

确保同样的配置和是否是一个系统？

**Comment by g1021895463** [comment]
刚踩完坑
我用的是Gmail，也是同样的报错
然后把梯子开成全局后又能发送了
是PAC模式下简悦同步助手的流量不会过梯子导致的？
现在我换回QQ邮箱发送了PAC模式下也正常了

**Comment by Kenshin** [comment]
嗨，谢谢反馈，我已经记录到 https://github.com/Kenshin/simpread/discussions/3269 里面了。

所以，顺道关闭了这个 Issues。
