### ISSUE TITLE
如何远程退出绑定呢？

### ISSUE THREAD

**Issue by 1tonsilla** [Kenshin/simpread#1609]
我看到介绍都是通过 账号--退出，来退出当前会员的

但是我之前绑定的手机格式化后卖了，现在不在我手里，如何给老手机的权限给去掉呢？

**Comment by Kenshin** [comment]
嗨，你记错了吧，简悦不会收集用户的隐私，所以自然也包括：手机号了…（简单说，简悦没有通过手机号退出的概念。）

**Comment by 1tonsilla** [comment]
> 嗨，你记错了吧，简悦不会收集用户的隐私，所以自然也包括：手机号了…（简单说，简悦没有通过手机号退出的概念。）

哈哈，老哥，您误解我意思啦，是因为我之前用两台PC，一台手机登录过VIP账号，然后我现在换了一台手机，我怕如果用新手机登录简约VIP会锁定账号（因为总共就四台设备了），所有我不知道咋操作呢。。

**Comment by Kenshin** [comment]
> 是因为我之前用两台PC，一台手机登录过VIP账号，然后我现在换了一台手机

哈哈，还是没明白你的意思... 手机 → 电脑？

不过，你可以通过登录 https://simpread.pro/account 来踢出全部设备，不过请留意以下提示：

![image](https://user-images.githubusercontent.com/81074/103147990-bce8ba80-4795-11eb-9200-f18541d6104c.png)

**Comment by 1tonsilla** [comment]
是这样哒，我上一台手机是用kiwi，也用简悦登录我帐号了，所以也算占用了一个设备。那台手机闲鱼上格式化后卖啦，所以没法手动退出账号，我怕买的新手机kiwi登录之后，超过3台设备锁定的。 
我看到您的截图，14天未登录会自动删除，看来不需要退出了。

不过感觉整体机制还是复杂一点。。我给uid和json文件都保存下来了，我刚打开您给的链接，想在账户平台里面看看绑定的设备的，发现除了uid还需要输入License..可是我不知道啥是License，我是通过购买少数派激活码激活的。
看到您说uid什么的比较好，什么绑定微信什么的并不好，但是确实增加一些使用成本。。我有一个笔记群，有人推荐用简悦，但是用半天有点摸不着头脑，所以我还是希望以后增加微信或者手机号绑定，哈哈（对了之前用的欧陆词典支持绑定微信，大概也是3台设备吧，然后如果多登陆设备，就自动给上一个设备账号挤掉了，感觉挺方便的）

**Comment by Kenshin** [comment]
嗨，我理解你的问题了，哈哈。

因为一直反复提手机，再加上电脑，我就没往 Kiwi 上面想...

***

License 就是你在少数派的购买兑换码（激活码），因为每个平台的说法都不一样，所以最好统一为它们的英文名字 License  😂 

当然，如果你没有多设备使用的话，等 14 天之后自然就没问题了。

***

再另外，目前不建议 Kiwi Browser 绑定高级账户，因为在 Kiwi 上暂时没有关于高级账户可以方便使用的功能。（如：标注在 Kiwi 的支持度有限）

如果没有其它问题的话，我关闭此 Issues 了~

**Comment by Kenshin** [comment]
哦，补充下：

> 关于使用流程的问题。

会考虑你说的方案，包括 欧陆词典的做法。

***

> 我有一个笔记群

请问是 Q 群？还是微信群？能告知下？我去卧个底~  😊

**Comment by 1tonsilla** [comment]
> 嗨，我理解你的问题了，哈哈。
> 
> 因为一直反复提手机，再加上电脑，我就没往 Kiwi 上面想...
> 
> License 就是你在少数派的购买兑换码（激活码），因为每个平台的说法都不一样，所以最好统一为它们的英文名字 License 😂
> 
> 当然，如果你没有多设备使用的话，等 14 天之后自然就没问题了。
> 
> 再另外，目前不建议 Kiwi Browser 绑定高级账户，因为在 Kiwi 上暂时没有关于高级账户可以方便使用的功能。（如：标注在 Kiwi 的支持度有限）
> 
> 如果没有其它问题的话，我关闭此 Issues 了~

哈哈，对，其实移动端kiwi登陆vip也没什么好用的功能，确实不登录也不影响啥。
---
我说的笔记群就是notion讨论群啦（微信），因为notion官方的网页简藏太不好用了，所以里面有新人问这方面的问题，我们就会提到简悦~另外我还有一个学术讨论微信群，里面有时候也会提到简悦 o(*￣︶￣*)o ，下面是截图图床

https://imgchr.com/i/r7kvRI

（搞学术的人都感觉复杂，确实是有些复杂，虽然一步步能操作过来，但是有时候遇到问题还要回来查看FAQ，有点累。非常感谢大大考虑我提出的方案，哈哈，祝APP越来越火）
----
（另外那个notion群就是普通的notion中文微信群，如果需要的话，我看看怎么能帮您拉到群里。那个学术群是开了个几十的小会员才能加的。。就不好给您拉到群里啦）

**Comment by Kenshin** [comment]
哈哈，关于易用性的问题我会在后续的版本中逐步优化。
虽然有些小问题，但简悦功能上的大方向就在那里。

😁
