### ISSUE TITLE
微信公众号文章 代码段显示错乱

### ISSUE THREAD

**Issue by east4ming** [Kenshin/simpread#1610]
如这个URL: https://mp.weixin.qq.com/s?__biz=MzU4MjQ0MTU4Ng==&mid=2247488793&idx=1&sn=bb2b0ad1402d4af50f2b4211621612b6&chksm=fdb91a04cace93121d8678c8025e197b36d429b199b11cb5b5e66797e30abb73150f03c8bd80&mpshare=1&scene=1&srcid=1225KcUxFSuQkRBbkEIP6LZk&sharer_sharetime=1608866557431&sharer_shareid=ca3338040ec98c721a207c338f2b28ab&key=94e16379e8fc498feaabdaec6fd55924335f8b7e35b32501d20bb08278a559b496e725845e69c7a72e7d58da890eccfef2ed92053b3542250cf0647f1b1fbdddf41cd23a005f698cb1d2129137a958a75de428a0460541763291d82a88c3127c3f30e39c6f20fda78245c4df684c5f570002726a2c4975e0e2ee0ae027d23cd9&ascene=1&uin=MTI2Njc4MTYw&devicetype=Windows+10+x64&version=6300002f&lang=zh_CN&exportkey=AVXgnaIIK%2FQ%2FB0bXI6u%2FjHM%3D&pass_ticket=fbJ51LMqeFwlLKRkU2gsrvzWzJcPJu4rSM3E4HA4idsL3C46fuPzBuRrGh3sX8Bk&wx_header=0

原文代码段显示如下:
![image](https://user-images.githubusercontent.com/13358726/103120888-930b9700-46b4-11eb-92c6-c47b8a036dd6.png)

进入阅读模式显示如下:
![image](https://user-images.githubusercontent.com/13358726/103120905-9ef75900-46b4-11eb-9c5e-e7717fc8b3df.png)

**Comment by Kenshin** [comment]
谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
