### ISSUE TITLE
知乎导出到notion只有标题，没有内容

### ISSUE THREAD

**Issue by wshzz001** [Kenshin/simpread#1611]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **win10**

- 浏览器版本 **版本 87.0.664.66 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/332280919>

**请描述你的问题**

> 这个网页导出到notion,在notion打开发现只有标题，没有内容。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
导出到本地是否正确？
Notion 对 md 的支持度比较奇怪。

**Comment by wshzz001** [comment]
是用同步助手吗？我下载下来了，但是好像不是个exe。
另外知乎的其他文章都能正常导出，目前就遇到这个文章不行。

**Comment by wshzz001** [comment]
下错了，下的MAC的了，现在配置好了之后，pdf的导出是OK的

**Comment by wshzz001** [comment]
另外，我发现个现象，点击导出到Notion之后，马上切换到notion，会发现刚生成页面的时候是有内容的，然后一闪，内容就消失了。您可以自己试一下。

**Comment by wshzz001** [comment]
再次补充，复制marddown到剪贴板，然后在notion新建页面粘贴，可以显示内容，貌似也不是MARKDOWN的锅

**Comment by Kenshin** [comment]
> 另外知乎的其他文章都能正常导出，目前就遇到这个文章不行。

看看这个文章 https://github.com/Kenshin/simpread/discussions/1617

***

> 另外，我发现个现象，点击导出到Notion之后，马上切换到notion，会发现刚生成页面的时候是有内容的，然后一闪，内容就消失了。您可以自己试一下。

***

我刚测试了下，可以成功导入到 Notion （ 但确实没有使用你说的方式，简悦使用了 Notion 一些私有 API 建议不要太过「折腾」它，因为或许会出现问题。

所以，不要使用你说的方式，就是正常的将某个阅读模式下的页面发送到 Notion  （ 我刚测试过，是没有问题的）

***

> 再次补充，复制marddown到剪贴板，然后在notion新建页面粘贴，可以显示内容，貌似也不是MARKDOWN的锅

你是每个页面都无法导入到 Notion 吗？建议看看上条的说明，应该没有问题的

**Comment by wshzz001** [comment]
感谢回复。
1.1617这个是导出到PDF存在问题，我导出到PDF是正常的。
2.我描述里的导出后切换到notion,这个是查看操作，并不会影响到简悦的导出功能。只是说明乐notion在刚接收到简悦的页面的时候是存在内容的，只是不清楚为什么会刷新到内容空白。
3.不是所有页面都无法导入到notion,是偶尔出现类似的页面，知乎，CSDN都有碰到过。

**Comment by Kenshin** [comment]
> 2.我描述里的导出后切换到notion,这个是查看操作，并不会影响到简悦的导出功能。只是说明乐notion在刚接收到简悦的页面的时候是存在内容的，只是不清楚为什么会刷新到内容空白。

最后这个页面是否保存成功了？如果保存成功了，就不用理会这个「情况」。（这是使用 Notion 私有 API 的一些特殊现象

> 不是所有页面都无法导入到notion,是偶尔出现类似的页面，知乎，CSDN都有碰到过。

再遇到这类情况，请先试试导出 Markdown 到本地，如果没问题的话，则是 Notion 的问题。
Notion 对 Markdown 的支持度比较奇怪  😅

**Comment by goodgameyouplay** [comment]
我也遇到了类似的问题。

**Comment by Kenshin** [comment]
@goodgameyouplay 

请告诉具体 URL 另外，请尝试导出 Markdown 到本地；同时是否每篇文章都是如此？
如果导导出 Markdown 没有问题且并不是每篇文章都存在此问题的话，只能说明：Notion 对这篇文章的 Markdown 导入有些异常。

**Comment by goodgameyouplay** [comment]
感谢回复。
我已找不到具体URL。不过导出markdown是正常的。

**Comment by Kenshin** [comment]
@goodgameyouplay 

导出 Markdown 没问题的话，一般可以排除掉是简悦的问题。（因为用了私有 API 且 Notion 对 MD 的支持比较奇怪）
所以，（有可能）等正式版的 API 出来后应该能自动解决。

**Comment by demom3b** [comment]
我用简悦测试了一下这个这个页面，也遇到类似情况 存到剪藏的时候提示了17张图片都上传完成，但是在notion那边，只生成了个untitled 页面，里面除了专栏链接，别的什么都没有，没有正文，没有标题，没有图片

PS：1. 我在知乎回答使用剪藏到notion发生了提示图片上传成功，但是只有文本的情况
2. 随便选了另一个知乎专栏文章，剪藏到notion，10张图片只有5张上传到notion；顺便也测试了 epub，md/离线md，html/离线html；结果是：- epub: 只保存了8/10张
- md没问题 10/10，离线md第一张显示不出 9/10
- html/离线html没有问题 10/10
3. 又试了一个公众号文章，也是和1 一样的情况 untitled ，只有一个链接，别的什么都没有
4. 我试过了 取消notion授权，重新给权限，剪藏，结果一样

**Comment by Kenshin** [comment]
@demom3b 

嗨，谢谢详细测试~

1. Epub 失败的原因是可能因为某个图片没有被正常下载造成的。（多测试几次）
2. 导出到本地肯定不会出现问题，因为它依赖与阅读模式，当阅读模式可以正常加载页面的时候，自然可以成功保存到本地。
3. 关于 https://zhuanlan.zhihu.com/p/332280919 导出的问题，可以看下我刚刚导出的页面 https://www.notion.so/22c63ed658774bada504fc9e9d3ae375 （使用 Notion.so 作为图床）

所以，还是那句话，因为使用了私有 API 不确定每个人能否达到预期效果。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4
