### ISSUE TITLE
bug: 鼠标离开菜单栏后，图标没有自动收缩

### ISSUE THREAD

**Issue by Jackiexiao** [Kenshin/simpread#1613]
- 操作系统 windows 10

- 浏览器版本 chrome

- 简悦版本 **2.0.0**（chrome extension中安装）

![image](https://user-images.githubusercontent.com/18050469/103146920-f0721780-478a-11eb-937a-e98770f57a62.png)

**Comment by Kenshin** [comment]
因为太多了，你离开这些蓝色的图标后再试试。

另外，去插件中心安装 https://simpread.ksria.cn/plugins/details/7gcXYY4HAc 减少一些不用的功能。（尤其是针对 FAB 这种工具栏

**Comment by Jackiexiao** [comment]
![image](https://user-images.githubusercontent.com/18050469/103147746-3206c080-4793-11eb-8211-8def42a404d6.png)

**Comment by Kenshin** [comment]
@Jackiexiao 

嗨，刚才没注意你的 ID 是 Obsidian 的朋友吧。方便的话，可以进 TG 群 https://t.me/simpreadgroup 

***

另外，请留意我给你的回复 https://github.com/Kenshin/simpread/issues/1613#issuecomment-751332824 能有效的降低 FAB icons 的数量~

**Comment by Jackiexiao** [comment]
@Kenshin 恩恩，已用上插件，感谢！
