### ISSUE TITLE
代码高亮解析错误

### ISSUE THREAD

**Issue by Vikiboss** [Kenshin/simpread#1614]
### 代码高亮解析错误

- 页面地址: https://www.liaoxuefeng.com/wiki/1177760294764384/1179610888796448
- 提示截图:

![image](https://user-images.githubusercontent.com/53367348/103154037-fb02d000-47cf-11eb-9638-07c215b9a878.png)

**Comment by Kenshin** [comment]
谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
