### ISSUE TITLE
无法导出文件

### ISSUE THREAD

**Issue by JogerKew999** [Kenshin/simpread#1616]
安装简悦助手后，导出EPUB或PDF，提示为实验性功能，无法导出。
顺带说一下，所有加粗的字体，在简悦中全部被小号字体替代了。本来是重要的提示性文字，在简悦中反而被缩小，这个让人不能理解。

**Comment by Kenshin** [comment]
嗨，请根据这个提示 https://github.com/Kenshin/simpread/discussions/1617 来自行解决。

所以，我先关闭此 Issues 如仍无法解决，请随时重开 Issues ~  🙏
