### ISSUE TITLE
带有滚动条的代码，解析时出现问题，打开增强所有代码在一行显示，关闭增强代码不会分行

### ISSUE THREAD

**Issue by xsyzer** [Kenshin/simpread#1622]
示例网址：https://blog.csdn.net/qq_15037231/article/details/80624064

原始代码：https://s3.ax1x.com/2020/12/28/rolLe1.png
开启增强：https://s3.ax1x.com/2020/12/28/rolOdx.png
不开增强：https://s3.ax1x.com/2020/12/28/ro1ZY8.png

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
