### ISSUE TITLE
同步助手自定义协议跳转

### ISSUE THREAD

**Issue by Quorafind** [Kenshin/simpread#1627]
目前同步助手已经可以实现网页到本地的交互。

但是本地到本地或者本地到网页的端口还缺少，即无法回跳。

由于开发者也在用 Obsidian ，就此提出一个强需求，即默认在系统注册表中注册一个类似`simpleread://` 的协议，然后将每次存下来的文件(此处假定用户默认保存在某个位置)，然后利用同步助手实现跳转打开

因为目前我想要实现同样的链接功能，需要使用`file:///`方式链接，而且并不支持中文长链接，现在同步助手出现后，给了一种可以与本地交互的曙光。

同时，利用上文所说的协议跳转，可以实现另一种可能操作，那就是可以直接跳转到稍后读页面的具体位置

**Comment by Kenshin** [comment]
嗨，谢谢反馈。（我认识你的 ID  😀 

很好的思路，我会考虑实现的。

你可以临时使用这样的方式 👉  `http://localhost:7026/pdf/<导出到 output 文件夹中 html 文件的名字>` 打开任意 HTML

支持中文，如 `http://localhost:7026/pdf/P-A-R-A- 是什么及在 Notion 中的应用`

PS：如使用上述方式出现错误，多刷新几次即可解决。

当然这种方式并不能真正打开 html，但也算是一种折中办法。

***

> 利用上文所说的协议跳转，可以实现另一种可能操作

Deep link 或叫做 URL Scheme 的功能在筹划中（所以不确定是否下个版本会 100% 支持）

**Comment by Kenshin** [comment]
嗨，之前漏掉了这个 issues ，同步助手从 [1.1.0 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-2982511) 开始已经支持 URL Scheme 了，详细说明 [请看这里](https://simpread.pro/docs/#/Sync?id=urlscheme)。
