### ISSUE TITLE
Github 导出相同文件名的文件会出现提示信息不准确的问题。

### ISSUE THREAD

**Issue by MrWQ** [Kenshin/simpread#1628]
一些情况下，简约无法很好的处理。比如这两篇文章
1. https://mp.weixin.qq.com/s/Pd6BEs1Tok0A9EWIGHk9dA
2. https://mp.weixin.qq.com/s/OdF0qZ8JzFW_c1EMNyMbTg
我同时打开这两篇文章，1可以正常保存的有道云笔记和github，2却不可以

1.正常保存到有道云笔记和github
![image](https://user-images.githubusercontent.com/31604279/103252386-9d30dc80-49b7-11eb-8599-2674361791d6.png)
![image](https://user-images.githubusercontent.com/31604279/103252533-3c55d400-49b8-11eb-8f1c-32a70c991a08.png)

2.保存失败，提示授权问题。你可能会说是授权过期了，但是很遗憾的告诉你，我再次保存1还是可以正常保存的，所以我认为不是授权的问题，而是某些情况简阅无法正常处理。
![image](https://user-images.githubusercontent.com/31604279/103252445-ebde7680-49b7-11eb-9e41-a193505c58df.png)
![image](https://user-images.githubusercontent.com/31604279/103252514-2811d700-49b8-11eb-9a2f-64f791fa0fb6.png)

**Comment by Kenshin** [comment]
嗨，我刚测试了提供的这两篇文章，都可以正常保存到 Github
所以怀疑是不是因为标题含有特殊字符造成的问题？
请使用 https://github.com/Kenshin/simpread/discussions/1603 提供的方式再进行测试。

**Comment by MrWQ** [comment]
我安装了插件
![image](https://user-images.githubusercontent.com/31604279/103256356-f7d23480-49c7-11eb-91ad-56bd162c3bf2.png)
发现问题仍然存在
![image](https://user-images.githubusercontent.com/31604279/103256385-19cbb700-49c8-11eb-9431-0d031c352846.png)
然后又出现新的问题，标题乱码
![image](https://user-images.githubusercontent.com/31604279/103256342-e25d0a80-49c7-11eb-9bc4-b6057b7cc406.png)

**Comment by Kenshin** [comment]
> 标题乱码

你是什么版本的 Chrome ？低版本时曾经出现过类似的问题，高版本后就不在发生。

另外，你可以重启浏览器解决。

***

因为我测试了导出到 GIthub 肯定没问题（且我的简悦环境要比一般用户都复杂）所以一般都能排除掉简悦本身的导出问题。

另外，我看到你导出失败的提示，应该是：**你导入的 Github repo 已存在了此文件，无法覆盖导致的。**

**Comment by eightHundreds** [comment]
> 你导入的 Github repo 已存在了此文件，无法覆盖导致的。

请在文档注明,或明确错误提示

**Comment by Kenshin** [comment]
> 请在文档注明,或明确错误提示

谢谢提示，已加入 http://ksria.com/simpread/docs/#/Github?id=备注

这个提示问题，下个版本会修复。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
