### ISSUE TITLE
某些网站按钮不能点击

### ISSUE THREAD

**Issue by lee2333** [Kenshin/simpread#163]
今天登录 https://www.google.com/chromebook/offers/ 发现redeem按钮不能点按（并没有开启阅读模式），停用简阅恢复正常，之前浏览别的网站也有类似问题，不知道算不算bug。

**Comment by Kenshin** [comment]
我看了一下，的确是简悦造成的，但比较奇怪，不清楚是什么原因，这个页面是由 AngularJS 生成。
简悦有自己的 `命名空间`，所以不可能污染到其它部分，之前出现过 CSS 命名空间的问题，但已经修复了，而且跟这个也没有关系...

PS：从未遇到过这种情况... 你说有类似的问题，能否在找个有问题的页面，这样方便分析。

**Comment by lee2333** [comment]
不好意思，我也忘了之前是浏览什么网站出现的这种情况（也不一定和简悦有关），今天是有时间所以每个插件排查了一遍才找出的问题根源，如果再遇到我会反馈给您的。

**Comment by Kenshin** [comment]
没问题，如果有发现随时告诉我。毕竟只是极个别情况，否则我或者其他人早就发发现了~

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 新增加了 `黑名单` 功能，你可以把这个 url 加入到此，在这个页面上不会加载简悦的任何代码，此问题解决。详细说明 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
