### ISSUE TITLE
Joplin授权失败

### ISSUE THREAD

**Issue by dav1ctor** [Kenshin/simpread#1633]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10 1909**

- 浏览器版本 **Chrome 87.0.4280.88**

- 简悦版本 **2.1.0**

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

按要求操作后无法授权Joplin，仅弹出“授权中......"提示框但等待后并不能成功授权，原因未知。Jopin版本：1.5.12（Portable）

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="791" alt="20201229171141" src="https://user-images.githubusercontent.com/20353383/103273008-316f6380-49f9-11eb-9a1d-bab45bdecc2b.PNG">

<img width="960" alt="2020-12-29" src="https://user-images.githubusercontent.com/20353383/103272643-60390a00-49f8-11eb-834a-534477f49198.png">

**Comment by Kenshin** [comment]
谢谢反馈。
请看 https://github.com/Kenshin/simpread/issues/1311 这个内容，看是否能解决？

**Comment by dav1ctor** [comment]
感谢回复。
 #1311 无法解决问题。我这里并不是授权后无法保存到Joplin，而是直接无法授权。已启用Joplin的网页剪辑服务，且端口经检查正常。
<img width="959" alt="20201230110110" src="https://user-images.githubusercontent.com/20353383/103327385-47c7fe80-4a8f-11eb-8794-17c6fed77e61.png">
<img width="960" alt="20201230105611" src="https://user-images.githubusercontent.com/20353383/103327388-4b5b8580-4a8f-11eb-84c2-db2ddd23edc3.png">

**Comment by Kenshin** [comment]
emmm...

看看是否是这个问题导致 https://github.com/Kenshin/simpread/discussions/1567 

也就是说，你可以试试其它服务是否也都无法授权？

**Comment by dav1ctor** [comment]
问题已解决。在关闭Joplin程序后授权成功，之前都是在Joplin开启时进行授权操作。:sweat_smile:
感谢~

**Comment by Kenshin** [comment]
>  在关闭Joplin程序后再进行授权可成功，之前都是在Joplin开启时进行授权操作

额，竟然有这种「限制」？ 没问题的话，我关闭 Issues 了~

**Comment by Sky-seeker** [comment]
- 操作系统Windows 10 1909
- 浏览器版本Chrome 88.0.4324.190
- 简悦版本2.1.0
- Jopin版本：1.7.10
- 
遇到了相同的问题。
解决方法：禁用Jopin的*网页剪辑服务*后再进行授权操作，授权成功后再启用Jopin的*网页剪辑服务*。

**Comment by Kenshin** [comment]
@Sky-seeker 

> 禁用Jopin的网页剪辑服务后再进行授权操作，授权成功后再启用Jopin的网页剪辑服务。

嗨，应该不对的，禁用它的话，就无法授权了，你可以看看 https://github.com/Kenshin/simpread/discussions/1895 给出的几种解决方案

**Comment by Sky-seeker** [comment]
然而情况就是如此。我尝试了 #1895 给出的解决方案，也就是下面这几种，但是都无法授权。也尝试过卸载Jopin提供的网页剪辑插。最后灵光一闪，由*关闭Jopin客户端*联想到关闭*Joplin的剪辑服务*，经测试，成功授权。和预料一致的是*无法保存网页*，重新开启*Joplin的剪辑服务*，文章保存成功。

> 关闭Jopin客户端，
> 开启扩展程序的网站访问权限，
> 启用Joplin的剪辑服务，

**Comment by Kenshin** [comment]
@Sky-seeker 

竟然这么迷？Joplin 看来也不稳定...  😂  

PS：我把你的解决方案也放到了  #1895 里面了。
