### ISSUE TITLE
打开简悦阅读模式后，彩云小译全文翻译失效

### ISSUE THREAD

**Issue by liuluffy** [Kenshin/simpread#1634]
场景描述：浏览外文时会开彩云小译，但打开阅读模式后翻译失效了。
问题：阅读模式是以原 HTML 进行样式优化，彩云小译同样是 三方插件，是否有方法进行兼容？

**Comment by Kenshin** [comment]
谢谢反馈，这个是正常的情况，如何解决的话，请看 https://github.com/Kenshin/simpread/discussions/1561 的几种方案。

**Comment by Kenshin** [comment]
嗨，你可以看这个解决方案 https://github.com/Kenshin/simpread/discussions/3182

***

另外，[全文翻译](https://github.com/Kenshin/simpread/discussions/1593) 更新到了 1.1.0 增加了下面的新功能：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [段落翻译](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

***

我关闭这个 Issues 了，有任何问题可随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，划词翻译 1.0.0 版发布了，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4
