### ISSUE TITLE
希望导出结果去除转码标记

### ISSUE THREAD

**Issue by PayneSnow** [Kenshin/simpread#1635]
![截屏2020-12-30 10 01 39](https://user-images.githubusercontent.com/51922806/103325275-054df400-4a86-11eb-8dd3-09cb6cb0eb10.png)
这时notion转码结果
![截屏2020-12-30 10 01 31](https://user-images.githubusercontent.com/51922806/103325284-1139b600-4a86-11eb-99c1-2d68374e6153.png)
这是ulysses转码结果

希望导出的结果能够去除 标记，像普通的word文档一样

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

会考虑更细致的定制化需求。

**Comment by Kenshin** [comment]
嗨，导入到 Notion 发布了全新的 2.0 版，彻底解决了这个问题。

新版方案彻底去掉了你提到的情况。（因为使用了 Database Page，所以不再需要特别加入 URL）

****

新版功能一览：支持一键授权（不在有繁琐的授权过程），加持简悦完美的阅读模式，同时支持导入带标注色的全文，可以彻底解决你遇到的问题。

![](https://imgs.zhubai.love/5ccaad4e75ac4610b11c966cb45f8484_2072964972706709504.png)

# 🆕 全新 2.0 版

在 2024 年 11 月 16 日，Notion 私有 API 再次出现无法使用的问题，这让我决定**彻底弃用私有 API 方案，全面转向公开 API**。

由于采用公开 API，确保了功能的稳定性，不会再出现无法使用的情况，以下所有功能均基于 2.0 版本的描述。

# 🌟 特色

与其他同类产品相比，**简悦凭借其出色的阅读模式，可以更精准地将全文导入到 Notion**。

由于采用了公共 API，解决了 1.0 版本无法无法正确转换 LaTeX 公式的问题，并提供更安全简便的一键授权方式（相比私有 API，避免了账户泄漏风险）。

此外，还支持以下功能：

1️⃣ 在 Notion Page 显示描述、题图、Favicon、来源、标签、备注

2️⃣ 内置图床

3️⃣ 导入带标注颜色的全文 [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

4️⃣ 导入标注（支持三种方式）

5️⃣ 支持超长文章的导入、[知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229)、[表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74)（使用私有 API 的产品都存在无法使用的问题）

# 📥 导入效果

[https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897](https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897&pvs=74)

# 📚 一站式教程

[https://www.yuque.com/kenshin/simpread/zx3bcz](https://www.yuque.com/kenshin/simpread/zx3bcz)

# 📦 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

如果你需要使用简悦 + Notion 的话，可以直接看 [此配置库](https://www.yuque.com/kenshin/simpread/mwda8s) 。

# 🔌 介绍

导入到 Notion 相关功能分为两个插件：

📗 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

📘 [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU)

# 📖 功能

1️⃣ 可导入当前页面的题图、Favicon、来源等。

![img](https://imgs.zhubai.love/92778b3c8dcc4b1ab1120e1dbf780d33_2072964972706709504.png)

2️⃣ 导入正文到 Notion，因为使用了公开 API，所以可以完美适配 [知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229) · [表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74) 

3️⃣ 导入**带标注色的正文**到 Notion [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

> 此功能需要 **简悦高级账户**，可通过 [**此链接**](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/c6aa20e1b1814399b9e87b569ebdb3b5_2072964972706709504.png)

4️⃣ 内置 Cloudinary 图床

![img](https://imgs.zhubai.love/85901d6d7ed74b598b1b75ab81b59754_2072964972706709504.png)

5️⃣ 在导入可选择任意 Notion

![img](https://imgs.zhubai.love/2864ffa0f9134a4b8c99116cdf12c41f_2072964972706709504.png)

6️⃣ 同步稍后读的标签，并支持加入全局标签（即使当前页面未被标记为稍后读，也可导入已添加的全局标签）。

![img](https://imgs.zhubai.love/0cda01a5740a4c35b80391dc1ac971e5_2072964972706709504.png)

7️⃣ 添加描述（Summary）与稍后读备注（Note）

> 此功能需要 **简悦高级账户**，可通过 [此链接](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/d1d8cbad7ef94f169095039cd18b9b23_2072964972706709504.png)

8️⃣ 去除重复的 Page

![img](https://imgs.zhubai.love/58668edcf264416ea6dc2d97069ce2b0_2072964972706709504.png)

9️⃣ 导入标注

![img](https://imgs.zhubai.love/59ffe6d7a1644d83ab40f2d6bc06597e_2072964972706709504.png)

2.0 版在原来的方案（[标准模式](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)）基础上增加了两个全新的标注模板：

📗 带标注色的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f5881ada61bc11c25596f1d?pvs=74)

📘 按照标注色分类的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f58814da34fd7e2e0cb9d96?pvs=74)

![img](https://imgs.zhubai.love/fc42ca0d3dc94186b02e6737febdde51_2072964972706709504.png)

注意：上述两种标注模板需要**简悦高级账户**权限，可通过 [此链接](https://simpread.pro/price) 升级。

# 🔄 旧版本升级说明

如果你已使用 1.x 版（旧版本），首次升级后会出现如下截图，此时需重新授权 Notion 才能使用。（授权方式与上面一致）

![img](https://imgs.zhubai.love/fea50a3a372d47098655eddf70022cc7_2072964972706709504.png)

# 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可直接 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)  [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

#  🔎 关联 

https://github.com/Kenshin/simpread/issues/4955

***

我关闭这个 Issues 了，有任何问题，请随时在这里讨论~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
