### ISSUE TITLE
配置页面出现乱码

### ISSUE THREAD

**Issue by jerry74** [Kenshin/simpread#1638]
- 操作系统
- MacOS

- 浏览器版本
- Chrome 87.0.4280.88

- 简悦版本
- 2.1.0

**请描述你的问题**
浏览器为繁体中文配置
配置出现乱码
**截图**
浏览器配置
![image](https://user-images.githubusercontent.com/3943094/103347926-6819ac80-4ad3-11eb-9999-d8e81fbdc8e1.png)
配置页面乱码
![image](https://user-images.githubusercontent.com/3943094/103347836-1ec95d00-4ad3-11eb-8d71-83e55c0135eb.png)

**Comment by Kenshin** [comment]
重启浏览器即可解决。

原本是低版本时偶发的问题，后来升级了高版本后就应该没问题，不知道为什么又出现了。
