### ISSUE TITLE
Evernote无法使用

### ISSUE THREAD

**Issue by fansmaker** [Kenshin/simpread#164]
如题。授权成功了，保存时提示稍后再试，不知道什么原因。

**Comment by Kenshin** [comment]
我刚刚随便找个篇文章试了下，没有问题。
提示保存失败吗？还是没反应？
如果前者的话，是正常的，关于保存失败的原因 [请看这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

方便请给出保存失败的 url

**Comment by maonx** [comment]
我这授权成功后，显示保存失败。
失败URL：https://zh.wikipedia.org/wiki/%E5%9F%8E%E5%B8%82%E7%8C%8E%E4%BA%BA#%E6%BC%AB%E7%95%AB

**Comment by Kenshin** [comment]
保存失败的原因请看上条。 😅

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊

**Comment by maonx** [comment]
就还是Evernote用不了，要么就是转换OneNote

Kenshin Wang <notifications@github.com> 于 2018年3月31日周六 上午11:57写道：

**Comment by Kenshin** [comment]
嗯，并不是 Evernote 用不了，而是经常出现保存失败的情况...  😂  个人建议还是早换到 Onenote 比较好。 😀

**Comment by maonx** [comment]
好的，那我去试试

Kenshin Wang <notifications@github.com> 于 2018年3月31日周六 下午12:52写道：
