### ISSUE TITLE
简悦同步助手无法开机自启动

### ISSUE THREAD

**Issue by Zhixiaz** [Kenshin/simpread#1646]
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎11/‎26
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0
* 简悦同步助手 1.00

**简悦同步助手无法开机自启动**
排查后发现，电脑在运行同步助手时会将程序自动解压至临时目录，见图，然后在退出程序后，临时目录会被清空，每次电脑关机重启后后，自启动指向的程序消失，无法自动启动

![Snipaste_2020-12-31_20-15-52](https://user-images.githubusercontent.com/51500882/103410271-95368f80-4ba5-11eb-8d69-ed163b17129e.png)

![Snipaste_2020-12-31_20-16-22](https://user-images.githubusercontent.com/51500882/103410274-97005300-4ba5-11eb-8cb8-a020e172dcbe.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

确实如此，下个版本会解决。
是打包的问题，**exe 其实就是个 zip 所以会自解压到临时目录** 造成的。

**Comment by kubulo** [comment]
<img width="418" alt="Snipaste_2021-02-17_11-02-04" src="https://user-images.githubusercontent.com/74105898/108150484-ad3f7f80-710f-11eb-8b1f-f831cd1a6d90.png">

自启动时每次开机弹出错误提示信息对话框，烦不胜烦，只好关闭自启动了。

**Comment by Kenshin** [comment]
@kubulo 

下个版本解决

**Comment by jokervTv** [comment]
这个问题解决了吗，Windows 11 上也出现了无法自动启动的问题

**Comment by Kenshin** [comment]
@jokervTv 

看这里 https://github.com/Kenshin/simpread/discussions/2011

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 自启动

修复了 Windows 、Mac 版无法自启动的问题，如仍无法自启动，Windows 用户 [看这里](https://github.com/Kenshin/simpread/discussions/2011)。

Linux 环境因为比较特殊，仅能 [使用此方式](https://github.com/Kenshin/simpread/discussions/3957) 实现。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
