### ISSUE TITLE
建议浮动标注栏不需随标注自动弹出

### ISSUE THREAD

**Issue by hh23485** [Kenshin/simpread#1648]
标准的悬浮工具条能不能固定到一个位置，选颜色的时候会碰到别的标注区域就切走了。

有的时候同一段落的文字有多处需要标记，经常选中之后，去点选颜色的时候就会碰到别的标注块，然后悬浮工具条就切换了焦点了。能不能加个固定到某个没有文字的地方，或者不要滑动到就切换焦点，避免这样的误触。

晚上用的时候气的差点砸了鼠标。。。

毕竟作为一个效率工具，不能降低效率。。。

**Comment by hh23485** [comment]
我并不打算使用连续标注，这是两个完全不同的功能。并且连续标注开启之后，你无法在使用划词翻译之类的操作，甚至你只是想复制一段文字都会触发标注。。

**Comment by Kenshin** [comment]
会考虑加入 非自动识别并弹出浮动工具条 的选项。

至于第二个问题，浮动工具条有个 copy 的功能。
如果你需要正常的复制功能，右下角关闭标注即可。

**Comment by Kenshin** [comment]
另外，你也可以在标注上：

- 单击 → 改变颜色
- 双击 → 弹出编辑框

**Comment by qiaogaojian** [comment]
刚升级高级账户, 其他都很满意的, 就是自动识别并弹出浮动工具条这个功能真的很烦

**Comment by pixel233** [comment]
希望可以加入固定浮动工具栏的选项🙏 @Kenshin

**Comment by Kenshin** [comment]
@qiaogaojian @pixel233 

下个版本会加入此功能。

**Comment by LiguangZhang** [comment]
这个标注条自动出现一闪一闪的可烦死了。不能做成word那样, 选中之后再显示吗

**Comment by Kenshin** [comment]
@LiguangZhang 

> 不要区分代码段 图片 正常文本，

这个肯定不会的，能区分不同类型的内容本身就是简悦的特点。但  **选中之后再显示** 可以有，下个版本发布。

**Comment by LiguangZhang** [comment]
@Kenshin 
> 这个肯定不会的，能区分不同类型的内容本身就是简悦的特点。但 **选中之后再显示** 可以有，下个版本发布。
我的意思是鼠标划到代码和图片上不要自动弹出浮动条， 改成选中代码段其中的部分内容后，再弹出浮动条。
如果你觉得默认这样不好的话，提供个开关让用户选择可以自己定制也可以啊。
多谢了， 市面上这样的良心插件太少了， 已经付费了。 小问题可以忽略， 这个浮动条的设计真的是太影响使用了。
我这边需要精读标注的文章只有都是里面代码比较多的，现在划到代码段就自动弹出，快被闪瞎眼了。

**Comment by Kenshin** [comment]
@LiguangZhang 

> 代码和图片上不要自动弹出浮动条， 改成选中代码段其中的部分内容后，再弹出浮动条。

是的，新版就是这样的。

浮动工具条的初衷是为了减少用户的点击，或者说是为了做「快速精读」。即可以：不关注任何操作，直接在页面高亮，然后就可以了。

但确实也没考虑到 **非精读** 的使用场景。

***

基于你刚才指出的场景，我一般的做法是：

> 在有需要高亮的代码段，鼠标停留，然后（稍等不到1秒）就能出现浮动工具条，然后就可以标注了。

如果改为鼠标点击的话

>  在有需要高亮的代码段，鼠标点击 → 选择高亮

整理下来，现在的方案要比你需要的方案，少了 nnnn 次鼠标点击。

**Comment by LiguangZhang** [comment]
@Kenshin 
现在的方案是识别整个代码段， 然后默认标注的是整个代码段。
我说的效果是 我自己划线代码段里的部分内容（比如一个高亮其中的某个变量）， 对整个代码段进行标注对我来说意义不大。
辛苦帮忙支持一下

**Comment by Kenshin** [comment]
@LiguangZhang 

了解你的诉求了，会考虑这种更细颗粒度的问题。 👍

**Comment by Kenshin** [comment]
@LiguangZhang 

> 二来整个代码段的浮动工具条经常跟该代码段里的部分内容的标注产生混乱。

这是「正常」的，因为代码段仅支持整体标注，自然会出现你说的情况。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
