### ISSUE TITLE
【稍后读问题】希望在“稍后读”中增加全文导出功能

### ISSUE THREAD

**Issue by hezhefly** [Kenshin/simpread#1649]
> 首先先感谢作者不懈的努力和灵感开发这么好的作品，并不断努力优化和适配页面；

## 问题：“稍后读”中没有全文导出，正常阅读模式中有

1. “稍后读”模式截图
![image](https://user-images.githubusercontent.com/35137227/103450320-b905ec80-4cef-11eb-8322-f61e61848f5c.png)

2. “阅读模式”截图
![image](https://user-images.githubusercontent.com/35137227/103450331-d0dd7080-4cef-11eb-863d-89c3d75d8102.png)

**Comment by Kenshin** [comment]
嗨，你可以在这里进行导出操作

![image](https://user-images.githubusercontent.com/81074/103452331-3ee26180-4d09-11eb-98f5-b5d0acb67b4a.png)

我关闭此 Issues 了，有需要请重新开启它。
