### ISSUE TITLE
仅导出标注到 Markdown 的结构需要优化

### ISSUE THREAD

**Issue by linyisan** [Kenshin/simpread#1656]

**Comment by Kenshin** [comment]
嗨，简悦 2.1 版已支持包含标注的全文。请确认是否是 2.1 版本。

**Comment by linyisan** [comment]
刚购买了会员，能把高亮与原文结合导出pdf。那么如何把自己附加的笔记/备注与原文一起导出？ @Kenshin

**Comment by Kenshin** [comment]
> 刚购买了会员，能把高亮与原文结合导出pdf。那么如何把自己附加的笔记/备注与原文一起导出？ @Kenshin

想导出什么格式？
仅导出标注的并且是 HTML 的话，会包含备注。

**Comment by linyisan** [comment]
> > 刚购买了会员，能把高亮与原文结合导出pdf。那么如何把自己附加的笔记/备注与原文一起导出？ @Kenshin
> 
> 想导出什么格式？
> 仅导出标注的并且是 HTML 的话，会包含备注。

试过其他导出方式，只有HTML对**原文与标注笔记结合**支持最好，其他的导出，要么只导出原文或标注笔记，要么就两者结合混乱

**Comment by Kenshin** [comment]
简悦的导出其实就两类：

1. HTML
2. Markdown

前者就不用说了，因为 HTML 天然支持丰富的表现形式，所以标注很容易在上面显示。
后者因为天然对富文本结构支持的缺失，导致无法在 Markdown 上方便的表现标注形式。

当然，**仅导出标注到 Markdown** 结构目前看来也有些不合理，下个版本会增强这块的功能。

到时候我会在这里通知你。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
