### ISSUE TITLE
排除列表不生效

### ISSUE THREAD

**Issue by luckykong** [Kenshin/simpread#1657]
这个网页，如果自动进入阅读模式，就会卡死。标签页cpu占用 100%。
[http://www.chongdiantou.com/wp/archives/62664.html](http://www.chongdiantou.com/wp/archives/62664.html
)

如果关闭 “如果当前页面为适配站点，是否自动进入阅读模式？”，而是等页面打开后，手动进入阅读模式，就会正常显示。

网页加入到稍后读里，直接阅读会提示失败。安装同步助手后，稍后读 里会正常显示。

另外，还有个问题，如何禁止这个页面自动进入阅读模式？ 
我在 “排除列表” 里添加 `http://www.chongdiantou.com` ，但是这个网页依然会自动进入阅读模式。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
