### ISSUE TITLE
付款后找不到license

### ISSUE THREAD

**Issue by zongchaowang** [Kenshin/simpread#1660]

**Comment by Kenshin** [comment]
什么渠道？
支付宝直接付款（腾讯问卷）的话，因这几天休假，明天晚上 19 点前统一兑换。

**Comment by zongchaowang** [comment]
找到了，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2021年1月3日(星期天) 晚上10:27
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "Wings"<786738440@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 付款后找不到license (#1660)





 
什么渠道？
 支付宝直接付款（腾讯问卷）的话，因这几天休假，明天晚上 19 点前统一兑换。
