### ISSUE TITLE
medium文章解析后内容不完整

### ISSUE THREAD

**Issue by w91** [Kenshin/simpread#1661]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Mac 10.14.6**

- 浏览器版本 **chrome 87**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://levelup.gitconnected.com/a-module-federation-example-for-react-1fa29d6ac07b>

**请描述你的问题**

文章中嵌入的代码显示不出来，末尾的内容也有丢失

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
