### ISSUE TITLE
稍后阅读出现乱码

### ISSUE THREAD

**Issue by nikochenbycn** [Kenshin/simpread#1663]
![image](https://user-images.githubusercontent.com/13117458/103614495-b6abc880-4f63-11eb-84a6-86b339d5c215.png)
原始页面：https://www.faxingzhan.com/boyfx/shishangnanfa/2258699_5.html
页面中使用阅读模式没有问题，加入稍后阅读后就会是乱码的状态。

**Comment by Kenshin** [comment]
谢谢反馈，这是因为某些页面没有按照 `约定俗成` 的 HTML 来设置它的编码，目前如果仅使用 Chrome 扩展端是无法解决此问题的。

**解决方案**：使用 [简悦 · 同步](http://ksria.com/simpread/docs/#/Sync) 的 [内置解析](http://ksria.com/simpread/docs/#/Sync?id=%e5%86%85%e7%bd%ae%e8%a7%a3%e6%9e%90) 即可解决。

PS：此功能为 高级账户功能，如需要话，[请升级](https://simpread.pro/price.html)
