### ISSUE TITLE
<通过简悦保存至印象笔记时，遗漏了部分内容（貌似是注释格式的文字内容）>

### ISSUE THREAD

**Issue by yuni-shi** [Kenshin/simpread#1664]
- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/85744518>

**请描述你的问题**

> 由简悦保存到印象笔记的内容少了一部分， 应该是少了markdown 的 ' > ' 语法内的内容，
原文是：

不知道大家在生活当中有没有这样的情况，比如

> 孩子似乎情绪不太稳定，一点点小事情就容易发脾气或者很难过.........

今天我就和大家分享一种好方法，让你和孩子轻松愉快成长。

保存后：

不知道大家在生活当中有没有这样的情况，比如

今天我就和大家分享一种好方法，让你和孩子轻松愉快成长。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
原文
![image](https://user-images.githubusercontent.com/16129727/103614598-e955c100-4f63-11eb-85e2-9a0d942112a7.png)

保存到印象笔记中
![image](https://user-images.githubusercontent.com/16129727/103614637-05596280-4f64-11eb-8eb0-b7987f142c67.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
