### ISSUE TITLE
建议！！！

### ISSUE THREAD

**Issue by programmeres** [Kenshin/simpread#1665]
标注功能：建议选中文字再出现标注栏。现在不是这样的危害后很多：鼠标划过文章，一堆标注栏飘过；上一行有标注，选中下一行，出现标注栏，要点击标注栏，因为鼠标滑过上一行，标注栏就没了，反而出现上一行的标注栏。。。。。。。
删除标注：删第一遍闪，删第二遍才真的删（标注栏上的X）右侧的删除按钮一样，倒是不闪了，里面转圈。。。。。

**Comment by Kenshin** [comment]
1. 下个版本有 非自动弹出的选项。
2. 删除操作有个确认删除的过程。

**Comment by programmeres** [comment]
就是闪相当于一个确认删除的动作？只是自己设置的标注，不是无法追溯的回滚的东西，没必要吧。。。。。。。
