### ISSUE TITLE
标注优化

### ISSUE THREAD

**Issue by programmeres** [Kenshin/simpread#1666]
如果删除注解非得加一步确认操作（文字上的标注栏是闪，右侧导航的删除一言难尽，个人觉得不是不可回滚操作，没必要），能不能不要闪，仅图标转圈，逼死强迫症啊，感觉不是产品本身设计，而是页面要崩溃。

**Comment by programmeres** [comment]
要不加个配置也行啊，拜托

**Comment by Kenshin** [comment]
嗨，可以考虑（请不要随便添加相似内容的 issues

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
