### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by EagerD** [Kenshin/simpread#1669]
**请说明发生问题的环境**

- 操作系统 **Win64**

- 浏览器版本 **chrome 87.0.4280.88（正式版本） （64 位）**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#simple

-问题描述：聚焦的快捷键无法设置，保存刷新后一直为空值；阅读模式的快捷键虽然可以正常设置，但在所有网页中使用时均无效。平均3周就会出现一次这个问题，需要重置配置文件才能解决，极为麻烦，希望尽快解决，谢谢。

-图：
![image](https://user-images.githubusercontent.com/44224427/103838484-21761480-50c8-11eb-95a9-37f46d9be5c4.png)
![image](https://user-images.githubusercontent.com/44224427/103838510-3488e480-50c8-11eb-8f98-615312d40989.png)
![image](https://user-images.githubusercontent.com/44224427/103838521-3a7ec580-50c8-11eb-8dc7-2f4cfd252f78.png)
![image](https://user-images.githubusercontent.com/44224427/103838549-4f5b5900-50c8-11eb-9805-b61d42cff220.png)

**Comment by Kenshin** [comment]
快捷键功能是从 1.0.0 就开始的功能了，不会存在无法使用的情况。
请在 **隐身模式下，仅启用简悦** 后再试试。（排除其它扩展造成的干扰）

聚焦模式快捷键无法设置的问题，同样如此，你可以一个按键一个按键的设置，看能否成功？

**Comment by EagerD** [comment]
1. 在隐身模式下，阅读的快捷键亦无效。我的阅读快捷键是a a，在网页页面使用快捷键无效，但通过右键菜单可以进入阅读模式。
2. 聚焦模式的快捷键我试了简悦推荐的各种组合，包括一个按键的，显示都是保存成功，但是刷新后快捷键就又消失了，一直处于无法设置和使用的状态。
这两个问题，请问要如何解决？



好学问
 
发件人： Kenshin Wang
发送时间： 2021-01-07 10:33
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] <请描述你的问题> (#1669)
快捷键功能是从 1.0.0 就开始的功能了，不会存在无法使用的情况。
请在 隐身模式下，仅启用简悦 后再试试。（排除其它扩展造成的干扰）
聚焦模式快捷键无法设置的问题，同样如此，你可以一个按键一个按键的设置，看能否成功？

**Comment by Kenshin** [comment]
emmm... 很奇怪的问题。
请问你用的是什么浏览器？什么系统？

另外，重新安装简悦（保存你的配置文件），在不改变任何配置的情况下，能否使用简悦默认的快捷键进入 `聚焦模式` 或 `阅读模式` 吗？

**Comment by EagerD** [comment]
经过重新安装，聚焦和阅读模式的快捷键都是可以用的，但是经测试，在我“在网页使用快捷键聚焦->再按快捷键更改背景颜色->点击确认后再按了一次快捷键->提示需要页面刷新->刷新后快捷键再次失效”，失效后状态和之前一样，聚焦快捷键页面空白，无法设置。同时阅读模式的快捷键也失效了。

tip：我想起来我之前使用过程中，快捷键失效也是因为进行了上述的操作流程。

我的系统是win10 64位，chrome浏览器。

发件人： Kenshin Wang
发送时间： 2021-01-07 12:26
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] <请描述你的问题> (#1669)
emmm... 很奇怪的问题。
请问你用的是什么浏览器？什么系统？
另外，重新安装简悦（保存你的配置文件），在不改变任何配置的情况下，能否使用简悦默认的快捷键进入 聚焦模式 或 阅读模式 吗？

**Comment by EagerD** [comment]
更正一下我之前的说法：
1.应该不是使用快捷键的过程中产生的问题，因为我后面反复测试了同样的路径，没有问题。
2.发现了疑似本质原因：当我重置后，快捷键是可以正常使用的状态。但是当我开启了同步助手的时候，大约20min后，快捷键自动失效，期间没有使用任何简悦的功能。所以之前我以为的 使用快捷键过程中失效 很可能是刚好简悦助手触发了同步。
（不仅是聚焦和阅读的快捷键失效了，加入稍后读和Esc快速退出的快捷键都不能使用）


 
发件人： EagerD
发送时间： 2021-01-07 13:48
收件人： Kenshin/simpread
主题： Re: Re: [Kenshin/simpread] <请描述你的问题> (#1669)
经过重新安装，聚焦和阅读模式的快捷键都是可以用的，但是经测试，在我“在网页使用快捷键聚焦->再按快捷键更改背景颜色->点击确认后再按了一次快捷键->提示需要页面刷新->刷新后快捷键再次失效”，失效后状态和之前一样，聚焦快捷键页面空白，无法设置。同时阅读模式的快捷键也失效了。

tip：我想起来我之前使用过程中，快捷键失效也是因为进行了上述的操作流程。

我的系统是win10 64位，chrome浏览器。

发件人： Kenshin Wang
发送时间： 2021-01-07 12:26
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] <请描述你的问题> (#1669)
emmm... 很奇怪的问题。
请问你用的是什么浏览器？什么系统？
另外，重新安装简悦（保存你的配置文件），在不改变任何配置的情况下，能否使用简悦默认的快捷键进入 聚焦模式 或 阅读模式 吗？

**Comment by Kenshin** [comment]
> 但是当我开启了同步助手的时候，大约20min后，快捷键自动失效，期间没有使用任何简悦的功能。

当发生此问题时，你可以看下 simpread_config.json 里面搜索 `shortcuts` 并查看对应的内容是什么：

![image](https://user-images.githubusercontent.com/81074/103869024-96246100-507e-11eb-8f55-00a2c70407e9.png)

![image](https://user-images.githubusercontent.com/81074/103869037-9d4b6f00-507e-11eb-87e6-2ec1dfbd4fdd.png)


内容是什么？

**Comment by EagerD** [comment]
恩恩，好的，现在我已经重置了，可以用了。之后再碰到这个问题，我按照你的方法查看一下，到时候再联系你看看能否解决，谢谢。



刁亚兵
 
发件人： Kenshin Wang
发送时间： 2021-01-07 16:24
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] <请描述你的问题> (#1669)
但是当我开启了同步助手的时候，大约20min后，快捷键自动失效，期间没有使用任何简悦的功能。
当发生此问题时，你可以看下 simpread_config.json 里面搜索 shortcuts 并查看对应的内容是什么：
内容是什么？

**Comment by Kenshin** [comment]
okay，再重现的话，请开启此 Issues ~

**Comment by EagerD** [comment]
你好，又出现了聚焦和阅读的快捷键无效的情况了，这次按照你提的方法，我查看了一下代码，发现不知为何focus后面的内容缺失了，最终导致的快捷键无效。我将之前备份的配置文件中的代码复制进去，快捷键使用就恢复正常了。如果问题难以排查的话，之后我用这个方法解决也可以。
复制前：
复制后：
 
发件人： EagerD
发送时间： 2021-01-07 17:23
收件人： Kenshin/simpread
主题： Re: Re: [Kenshin/simpread] <请描述你的问题> (#1669)

恩恩，好的，现在我已经重置了，可以用了。之后再碰到这个问题，我按照你的方法查看一下，到时候再联系你看看能否解决，谢谢。

 
发件人： Kenshin Wang
发送时间： 2021-01-07 16:24
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] <请描述你的问题> (#1669)
但是当我开启了同步助手的时候，大约20min后，快捷键自动失效，期间没有使用任何简悦的功能。
当发生此问题时，你可以看下 simpread_config.json 里面搜索 shortcuts 并查看对应的内容是什么：
内容是什么？

**Comment by Kenshin** [comment]
确实难以排查… 这么看来的话，估计是隐形 Bug 造成的。
你能否留意下，在做什么操作时发生的这个问题？
能否稳定复现？

**Comment by EagerD** [comment]
恩恩，我后面使用过程中多留意一下。
 
发件人： Kenshin Wang
发送时间： 2021-01-07 22:58
收件人： Kenshin/simpread
抄送： EagerD; Author
主题： Re: [Kenshin/simpread] 使用同步助手后会导致阅读模式的快捷键失效[疑似] (#1669)
确实难以排查… 这么看来的话，估计是隐形 Bug 造成的。
你能否留意下，在做什么操作时发生的这个问题？
能否稳定复现？
