### ISSUE TITLE
百家号添加进白名单后无法自动进入阅读模式

### ISSUE THREAD

**Issue by NightRain233** [Kenshin/simpread#1671]
百家号的排版真的垃圾，但有时候还是会不小心点进去看下 ，就想能不能自动进入阅读模式，但是加入白名单也不行，输了baijiahao.baidu.com和https://baijiahao.baidu.com/ 都不行，右键直接将那个百家号页面加入白名单了也不行，求问作者原因？
简悦阅读体验很好，感谢作者的开发

**Comment by Kenshin** [comment]
嗨，你需要将下面的内容加入到 白名单：

`[[/https\:\/\/baijiahao\.baidu\.com\/s\?id=\S+/]]` 即可解决。

PS：关于这块功能的描述细节请看 https://github.com/Kenshin/simpread/discussions/1672

**Comment by NightRain233** [comment]
> 嗨，你需要将下面的内容加入到 白名单：
> 
> `[[/https\:\/\/baijiahao\.baidu\.com\/s\?id=\S+/]]` 即可解决。
> 
> PS：关于这块功能的描述细节请看 #1672

原来时这样，现在可以了，感谢作者回复，辛苦了

**Comment by Kenshin** [comment]
@NightRain233 

没事的，搞定就好。

不过，原则上讲，你添加的内容应该也可以的，但也有可能是隐性 Bug 造成的，我先记录下。看看能否通过 Debug 调查清楚此问题。
