### ISSUE TITLE
使用小书签功能后并未更新到稍后读

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#1676]
windows系统Chrome87.0.4280.88（正式版本） （64 位）使用小书签功能时，尽管弹出窗口显示“已完成新增”，但是在稍后读未读列表里并没有更新，请问是为什么呢？

_Originally posted by @selennna in https://github.com/Kenshin/simpread/issues/533#issuecomment-755984457_

**Comment by Kenshin** [comment]
@selennna 

嗨，我把你「不合规」的那个  Issues 删了，在这里重新生成一个新的 Issues。

***

使用小书签的前提：
需要使用 [自动同步](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5) 功能。

另外，因为描述的相对简单，我没法帮你判断。所以，建议详细描述。

**Comment by selennna** [comment]
已经按照文档中心的要求设置好了，开启了自动同步，一切都设置好了，有窗口显示“已完成新增”，我提供几个截图：
![image](https://user-images.githubusercontent.com/77098191/103882152-5a3cda80-5116-11eb-948d-f5fb32732224.png)
![image](https://user-images.githubusercontent.com/77098191/103881549-8efc6200-5115-11eb-9b26-9efcee066436.png)
![image](https://user-images.githubusercontent.com/77098191/103881549-8efc6200-5115-11eb-9b26-9efcee066436.png)
![image](https://user-images.githubusercontent.com/77098191/103881649-b3583e80-5115-11eb-8209-d36ba5223697.png)
（FR这个标签是存在的）
即便不定制标签，仅使用**一键收藏**和**加入到稍后读**也都是一样的，刷新稍后读后未读列表里仍未能更新刚收藏的内容，但是如果使用常规方法直接添加未读列表是可以实时显示的，不知道我这样说是否清楚？谢谢~

**Comment by Kenshin** [comment]
请问你在本地有 `simpread_config.json` 配置文件吗？（如果使用自动同步的话，会保存在你本地有一份 `simpread_config.json` 文件的。

**Comment by selennna** [comment]
也有的
![image](https://user-images.githubusercontent.com/77098191/103889166-ee13a400-5120-11eb-98cc-db89a8cee719.png)

**Comment by Kenshin** [comment]
emmm...

你在 扩展端 随便找一个页面加入稍后读，看看能否在 稍后读 里面找到？

另外，请问当发生这个问题时，是否存在稍后读？还是说一个（稍后读）都没有？

**Comment by selennna** [comment]
我说了呀，只是小书签这个功能存在问题，但是我 右键-将当前页面加入稍后读 或者用 扩展端加入 都是可以即时显示的。但是我很想用小书签这个功能，可以直接编辑标签，我觉得很方便。

未读列表里有常规方法加入的稍后读。

**Comment by Kenshin** [comment]
这就太奇怪了…

导出文件夹也设置了吗？（虽然应该没关系）
另外看了下文件夹的名字有中文，能否改个英文试试。

加入到稍后读后，提示成功后，看看控制台有什么错误信息。

**Comment by Kenshin** [comment]
话说，我自己也很喜欢小书签的功能，轻量级。

**Comment by selennna** [comment]
啊感谢您耐心回复我，我知道bug在哪里了，因为我是在测试这个功能，忘记那篇文章已经加入到未读列表了...感觉自己好傻- - 现在一切正常了（和文件夹英文中文应该是无关的，特地重新试了一下~）

另外还有一个小问题，邮件每日回顾的设置里，发送的邮件地址和接受的邮件地址我没太懂，我不就是接收方么，那发送的邮件地址应该填写什么呀？

**Comment by Kenshin** [comment]
竟然是这个问题… 😑

发送邮件的需要开启 SMTP 才行，接受的话，也是发送到哪个邮箱。

举个例子：
填入 A 邮箱以及对应的 SMTP 密码，再填入 B 接受邮箱。
通过邮件功能发送邮件的话，就是自动通过 A 邮箱发送到你的 B 邮箱。
也就是说 A 邮箱被简悦帮你代发了。
