### ISSUE TITLE
无法连接到office365的OneNote账号，显示账户不存在

### ISSUE THREAD

**Issue by auniel** [Kenshin/simpread#1677]
![image](https://user-images.githubusercontent.com/37327100/103882924-755c1a00-5117-11eb-97ba-8771ccfc9d92.png)

**Comment by Kenshin** [comment]
嗨，这是「正常的」，简悦仅使用了个人版 Onenote 而已。
当然，这个 Bug 已被 Fixed 掉了，如果不急的话，等正式版发布就可以了。

否则的话，明后天我发布一个离线给无法使用 Onenote 的用户。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
