### ISSUE TITLE
仅导出 Markdown 时的标注结构需要优化

### ISSUE THREAD

**Issue by xiao1201** [Kenshin/simpread#1678]
动作中的`复制 markdown 到剪贴板`复制的内容在obsidian中粘贴为何都会被自动加上引用符号`> `？

![image](https://user-images.githubusercontent.com/8279939/103965909-b4cb4a80-5199-11eb-9f2f-39695fa95329.png)

![image](https://user-images.githubusercontent.com/8279939/103965949-c90f4780-5199-11eb-933b-e57430418f13.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
这是「正常」的情况，因为仅标注的话，就会导出为此结构。

当然，这个结构也是不合理的，下个版本会修复此问题。

**Comment by xiao1201** [comment]
多谢及时回复，希望您可以参考下 `roam-highlighter` 这款插件对于文章标注复制为markdown的方式，蛮好用的，感觉可以和obsidian无缝对接。

**Comment by Kenshin** [comment]
嗨，谢谢提示，会考虑更好的衔接方案。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
