### ISSUE TITLE
能不能提供非chrome商店的下载？

### ISSUE THREAD

**Issue by zhangzzzzzzz** [Kenshin/simpread#168]
能不能提供非chrome商店的下载？本人没有番羽墙软件，不方便Chrome商店下载，但是又想第一时间更新？    还有什么值得买网站浏览时候很卡顿。   最后谢谢作者写出这么好的软件！感谢！

**Comment by Kenshin** [comment]
官网上有下载 http://ksria.com/simpread/ 
或者 https://github.com/Kenshin/simpread/releases/tag/1.0.5 里面有已经下载好的 Chrome webstore 版

另外，提供一个技巧
进入 https://chrome-extension-downloader.com/ 在输入框粘贴需要下载的 Chrome webstore 地址，下载即可。

我将关闭此 issues ，如有其他问题再重新打开它，谢谢使用~  😄
