### ISSUE TITLE
“稍后读”总的网页归档后希望可以缓存网页快照。

### ISSUE THREAD

**Issue by DevinFu** [Kenshin/simpread#1680]
背景是这样的，我在网页上进行标注后，当把其进行归档后，用户场景上我已经消化完这篇文章的知识了，放到归档后方便以后进行复习回顾和查找。
但目前的问题是，在“归档”中用”阅读模式“打开原文时，其内容是从网页获取的，可能该网页已经发生变化甚至已经被删除了。就会导致我的标注失效甚至失去上下文，在知识回顾上造成一定困扰。
所以，希望在归档时，能够保存一份当前的网页快照，这样后续在”归档“中打开”阅读模式“时看到的就是当时的网页快照，避免上述情况的发生。
如果你们此处有什么其他考量或顾虑，期待探讨。
谢谢

**Comment by Kenshin** [comment]
嗨，谢谢建议。

现在有个一个功能：
![image](https://user-images.githubusercontent.com/81074/104003674-aef75880-51dd-11eb-8892-c0e18d6c891e.png)

 详细 [请看这里](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e8%87%aa%e5%8a%a8%e4%bf%9d%e5%ad%98%e5%88%b0%e6%9c%ac%e5%9c%b0)

算是在一定程度上弥补了 404 的问题，下一步会做「网页快照」功能的。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
