### ISSUE TITLE
稍后读：标签何合辑

### ISSUE THREAD

**Issue by Pikachuhere** [Kenshin/simpread#1684]
请问如何给文章添加“标签”以及加入合辑？

**Comment by Kenshin** [comment]
嗨

合辑可以看这里 http://ksria.com/simpread/docs/#/稍后读?id=合辑

标注的标签可以看这里 http://ksria.com/simpread/docs/#/标注?id=标注侧栏 （继续往下看就能解决）

**Comment by Pikachuhere** [comment]
谢谢

**Comment by Kenshin** [comment]
嗨，建议看看 https://simpread.pro/help 里面有很多对新手有帮助的汇总~
