### ISSUE TITLE
阅读模式不能点击空白处退出了吗

### ISSUE THREAD

**Issue by hankin-lab** [Kenshin/simpread#1686]
你好，
之前阅读模式可以点击空白处退出，现在这个功能取消了吗？

**Comment by Kenshin** [comment]
嗨

`阅读模式` 从未有过此功能，或者说你应该是安装了 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 这个插件。
`聚焦模式` 有此功能。

**Comment by hankin-lab** [comment]
你好，是因为这个原因，但是现在这个插件安装不了，有解决解决吗？好些插件都不能安装，mac 系统 macOS Big Sur 11.0.1, M1 芯片

**Comment by Kenshin** [comment]
你可以看下 https://github.com/Kenshin/simpread/discussions/1696 里面提到的解决方案。

**Comment by Kenshin** [comment]
嗨，没有其它问题的话，我关闭此 Issues （当然，你可以随时开启它。
