### ISSUE TITLE
简悦同步助手的通知怎么关闭

### ISSUE THREAD

**Issue by LPLWWS** [Kenshin/simpread#1687]
每次打开网页都会弹出来，很影响使用
![photo_2021-01-10_17-56-08](https://user-images.githubusercontent.com/12853250/104119808-345d4300-536d-11eb-90cf-cc76cd9ebad5.jpg)

**Comment by Kenshin** [comment]
同步助手默认是关闭的，在哪里开启它？就在原位置关闭它。

![image](https://user-images.githubusercontent.com/81074/104120069-f7924b80-536e-11eb-8077-f233260f4708.png)

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
