### ISSUE TITLE
与chrome插件冲突

### ISSUE THREAD

**Issue by lurui45** [Kenshin/simpread#1688]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

与chrome插件[Chromium Wheel Smooth Scroller ](https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb)冲突，打开阅读模式后，滚动页面卡顿。
该插件作用是支持鼠标滚轮平滑滚动页面

**Comment by Kenshin** [comment]
试试这个方案 https://github.com/Kenshin/simpread/discussions/1685

**Comment by Kenshin** [comment]
嗨，没有其它问题的话，我关闭此 Issues （当然，你可以随时开启它。
