### ISSUE TITLE
Simpread's shortcut is not compatible with Vimium

### ISSUE THREAD

**Issue by syhily** [Kenshin/simpread#169]
When I enable the Vimium, the shortcut for Simpread would not work.

**Comment by Kenshin** [comment]
简悦的确跟一些快捷键扩展有冲突，不过 Vimium 应该只限于 `f` 键不好用，其它常用的大多可以使用。
`f` 键的功能在简悦里面已经实现了。
详细请看  [快捷键](https://github.com/Kenshin/simpread/wiki/%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊

**Comment by Kenshin** [comment]
嗨，虽然这是个很古老的 Issues，还是要通知下，最新的解决方案 [请看这里 ](https://github.com/Kenshin/simpread/discussions/3699)。
