### ISSUE TITLE
同步助手的一些疑问

### ISSUE THREAD

**Issue by selennna** [Kenshin/simpread#1690]
在安装了同步助手的应用及配置后，出现了诸多问题：
**1. 浏览器总是弹出同步助手的窗口**
刚安装完同步助手后，我在电脑的任务管理器里把同步助手的开机启动关闭了，此后在浏览器只要打开一个界面就会显示：
![image](https://user-images.githubusercontent.com/77098191/104155110-6f20b300-5421-11eb-9377-6541ce35e1aa.png)
然后我就把开机启动打开了（同步助手里的开机启动也是打开的），但是仍然会有这个弹窗。如何解决不打开同步助手的应用就总会弹窗的问题呢？
以及，
如果要使用浏览器插件的稍后读功能，必须启用同步助手吗？我记得我一开始没有下载同步助手的时候，稍后读可以直接使用的，但是现在反而是，不开启同步助手，就无法把想要剪藏的内容添加到稍后读（添加时显示了“已成功加入未读列表“）。如果不必要的话，请问我这是什么问题呢？

**2. 无法保存到Notion**
这个问题也是在安装同步助手之前没有出现过的，现在不论是启没启动同步助手的应用，都无法保存到Notion（显示了"已成功保存”但是就是未能找到保存的内容）

**3. 从未收到每日回顾的邮件**
发送邮件的地址已开启了SMTP服务

以下是我的设置页面：
![image](https://user-images.githubusercontent.com/77098191/104156815-d429d800-5424-11eb-9d7e-7acd2901f891.png)
![image](https://user-images.githubusercontent.com/77098191/104156872-f1f73d00-5424-11eb-967b-6ec724cf4484.png)
![image](https://user-images.githubusercontent.com/77098191/104156908-01768600-5425-11eb-97c5-bd806510c25f.png)

**Comment by Kenshin** [comment]
嗨，你可以看下这个解决方案 https://github.com/Kenshin/simpread/discussions/1692

***

> 如果要使用浏览器插件的稍后读功能，必须启用同步助手吗？

是否运行它与稍后读无关，同步助手只是一个加强扩展端的桌面应用而已，同步助手的功能你可以看下 http://ksria.com/simpread/docs/#/Sync

> 现在反而是，不开启同步助手，就无法把想要剪藏的内容添加到稍后读

是的，这是因为你没有开启同步助手造成的，细节就在我给你的（第一个）链接中。

**Comment by selennna** [comment]
啊但是这我就不太懂了，既然是否运行同步助手和稍后读无关，那为什么“没有开启同步助手造成”无法把想要剪藏的内容添加到稍后读呢...这些文档文件我都阅读过好多遍了，需要配置的地方都是按照文档设置的，刚升级到高级账户后使用稍后读没有什么问题，但是下载了同步助手后反而就出现了这些问题，而且同步助手的邮件功能我也用不了，弹窗也很扰人，我不想使用同步助手了，但按照您的第二条回复，我也用不了稍后读或剪藏保存到其他工具了嘛？

**Comment by selennna** [comment]
最新又出现了问题...
我没有开启同步助手的desk app，将文章加入了未读列表，当我打开稍后读，不知道为什么我的未读列表里存储的内容全部消失了，只有最新添加的一条；
然后我以为是同步的问题，就打开了同步助手desk app，但是之前储存的未读内容还是没有恢复；
接着我又关闭了desk app，此时再刷新稍后读，连之前的一条未读也不见了...

**Comment by Kenshin** [comment]
> 啊但是这我就不太懂了，既然是否运行同步助手和稍后读无关，那为什么“没有开启同步助手造成”无法把想要剪藏的内容添加到稍后读呢...这些文档文件我都阅读过好多遍了，需要配置的地方都是按照文档设置的，刚升级到高级账户后使用稍后读没有什么问题，但是下载了同步助手后反而就出现了这些问题，而且同步助手的邮件功能我也用不了，弹窗也很扰人，我不想使用同步助手了，但按照您的第二条回复，如果我现在关闭同步助手功能，我也用不了稍后读或剪藏保存到其他工具了嘛？

嗨，关于这个问题，我想之前已经说的很清楚了。

首先，确认你是否需要 **自动同步** 功能？**如果需要的话，必须保证同步助手为开启状态**。否则就会有警示提示。
其次，如果你不需要 **自动同步** 就不要开启此功能。

**自动同步** 与 **非自动同步** 区别在于：

- 前者会把数据保存到本地
- 后者会把数据保存到 Chrome 内部

Chrome 扩展没有权限把数据保存到本地，所以才有了 **同步助手** 功能。

**如果开启了此选项，但并未运行同步助手的话，保存数据会出现错误。（同样我也告诉你了）**

***

你之前的回复一直没有提：**是否有需要把配置文件保存到本地** 的需求。

再提示下：**保存到本地后，需要通过 其它网盘（如坚果云等）作为同步盘，此功能才有意义，否则的话，并没有任何意义**。

***

> 既然是否运行同步助手和稍后读无关

它们确实无关，但你 **不能开启此功能，但不运行同步助手** 这样就会出现https://github.com/Kenshin/simpread/issues/1690#issuecomment-757742572 提到的情况（虽然这个情况很特殊，但确实无法通过简悦规避）

***

非要用一句简单的话说：
开启 **自动同步** 后，同步助手负责保存数据，简悦负责发送数据。（所以需要同步助手一直在运行）

**Comment by selennna** [comment]
好的，我明白了，谢谢您的答复。
我确实没有把文件保存到本地的需求，开启自动同步是为了体验邮件回顾和小书签功能，但是自下载了应用并配置后不仅从未收到过邮件，还连带影响了其他功能的使用。（具体我在主贴更新了，也希望可以解答一下，谢谢~）
授权了坚果云，也用坚果云账号作为第三方账号登陆了，总之就是真的是完全按照文档中心一步一步设置的，之所以弹窗困扰我，倒不是因为我不想既开启同步功能又不启动应用，而是因为**我设置了开机自启，它也没有再自启过**，而我还没有开浏览器之前去手动打开的习惯，所以来发帖询问。不知道这个是什么原因呢？
![image](https://user-images.githubusercontent.com/77098191/104207919-6b198300-546b-11eb-891a-9373ded2032a.png)
![image](https://user-images.githubusercontent.com/77098191/104207451-4ae9c400-546b-11eb-9f41-6ea0fee974e9.png)

**Comment by Kenshin** [comment]
> 开启自动同步是为了体验邮件回顾和小书签功能

每日回顾的功能 **不需要使用同步助手**

小书签的功能 **需要使用同步助手，并且需要开启自动同步** 才行。（因为小书签的功能会把稍后读保存到本地）

***

> 设置了开机自启，它也没有再自启过

这是个 Bug 我在 https://github.com/Kenshin/simpread/discussions/1692 最下方已经描述过了。

***

> 无法保存到Notion

通过你的描述，感觉你的环境比较「乱」。因为之前说过了「同步助手负责读取/保存」数据，所以如果一旦它设置有错误，就会产生很多意想不到的问题。

所以，

1. 你先要确保（弄明白）是否需要 自动同步 的功能。
2. Notion 重新授权
3. 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件
4. 打开一些正常些的页面，如少数派的页面 https://sspai.com/post/61996
5. 测试 Notion 是否成功。

> 每日回顾的功能

同样，需要在同步助手设置 SMTP，此功能无需 **自动同步**，但你也没有截图给我看。（我无法分辨）
另外，根据你上文所说，**没有使用自动同步**的功能，那就需要你 **每次手动同步配置文件到坚果云**。
因为，每日回顾会读取你在坚果云上的配置文件，如没有配置文件或当日没有稍后读，则不会给你发邮件。

**Comment by selennna** [comment]
> 每日回顾的功能 **不需要使用同步助手**
> 小书签的功能 **需要使用同步助手，并且需要开启自动同步** 才行。（因为小书签的功能会把稍后读保存到本地）
谢谢。之前确实没准备开自动同步，是为了使用小书签的功能才开启的，但开启后没有考虑到自动同步会影响其他的一些设置，所以就一直把自动同步和同步助手俩概念弄混淆了...

> 同样，需要在同步助手设置 SMTP，此功能无需 **自动同步**，但你也没有截图给我看。（我无法分辨）
设置了SMTP，那个图可能太糊了，以下是截图：
![屏幕截图 2021-01-12 110733](https://user-images.githubusercontent.com/77098191/104264827-536fe800-54c7-11eb-9a93-3a8d2f241f6b.jpg)

> 另外，根据你上文所说，**没有使用自动同步**的功能，那就需要你 **每次手动同步配置文件到坚果云**。
> 因为，每日回顾会读取你在坚果云上的配置文件，如没有配置文件或当日没有稍后读，则不会给你发邮件。
其实我有点不懂，**读取你在坚果云上的配置文件**这个配置文件指的是我把选项页当前环境的配置文件导出后自己上传到坚果云上嘛？因为我去看了一下，我虽然点了同步，但是我的坚果云里什么也没有...
![image](https://user-images.githubusercontent.com/77098191/104264753-2d4a4800-54c7-11eb-9be5-861240f73990.png)
![image](https://user-images.githubusercontent.com/77098191/104265077-c711f500-54c7-11eb-9d35-be6e69f5f268.png)
![image](https://user-images.githubusercontent.com/77098191/104266804-55d44100-54cb-11eb-8b76-af4dd83b19b2.png)

Notion的解决方案我待会儿再尝试，这儿还有一个昨天遗留的问题，还要麻烦您看一下：
最新又出现了问题...
我没有开启同步助手desk app时，将文章加入了未读列表，当我打开稍后读，不知道为什么我的未读列表里原先存储的内容全部消失了，只有最新添加的一条；
然后我以为是同步的问题，就启动了同步助手desk app，但是之前存储的未读内容还是没有恢复；
接着我又关闭了desk app，此时再刷新稍后读，连之前的一条未读也不见了...

**Comment by Kenshin** [comment]
> Notion的解决方案我待会儿再尝试，这儿还有一个昨天遗留的问题，还要麻烦您看一下：
> 最新又出现了问题...

嗨，其实没必要太纠结这个问题，当你的使用顺序出现错误（或者说使用逻辑出现错误时，有异常情况如你提到的情况是有可能出现的。

至于为什么的话，我已经反复提及过了，**开启同步助手后，同步助手相当于数据库**，所以 **在你没有连接数据库** 做的操作，因此而出现异常，这种情况是很难 Debug 且重现的。

另外，因你的这个问题，我特意写了篇 https://github.com/Kenshin/simpread/discussions/1700 希望你可以看下。

当然同样也希望看完后，仍有些不明白的地方，随时找我（我来补充这个文档）

**Comment by selennna** [comment]
谢谢您的详细回复~
目前同步助手app已经可以自启了，弹窗问题不再困扰，我也对自动同步和同步助手的功能更加了解了，感谢。

**Comment by Kenshin** [comment]
嗨，恭喜 Level up  🎉 

> 目前同步助手app已经可以自启了，弹窗问题不再困扰

方便说说你的实现方式？如果有好的思路，我可以放到公开的地方让更多用户收益~

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

当未开启同步助手时，仍可以使用简悦的最基本功能以及不需要使用同步助手的功能，同时会有下面的提示

![image](https://user-images.githubusercontent.com/81074/121986598-5f8b0900-cdc9-11eb-935a-3f4feef7e1fb.png)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
