### ISSUE TITLE
是否支持移动端一键将公众号文章加入稍后读？

### ISSUE THREAD

**Issue by Simon9511** [Kenshin/simpread#1694]
自己的知识管理习惯是在微信上看到好文章先做收集，之后再批量阅读，所以希望知道是否有方法直接在手机上直接把公众号文章加入至「稍后读」板块呢？

**Comment by Kenshin** [comment]
目前暂时没有关于此的功能，会考虑你的建议。

另外，能否上 TG （如果能的话，请在 TG 私聊我）如果不能的话，请给我发邮件（你能找到我的邮件。  😀

**Comment by Simon9511** [comment]
感谢Kenshin的回复！


今天刚好看了您关于知识管理流程的分享，感觉受益匪浅。现在大部分知识消费都在移动端进行，所以如果简悦能更多的对接移动端app（如微信公众号、知乎），那么将更好的完成“收集”这一过程，嘿嘿！


另外，我不用TG，不知道是否方便加您微信交流嘞～



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上6:30
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"763435633"<763435633@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 是否支持移动端一键将公众号文章加入稍后读？ (#1694)





 
目前暂时没有关于此的功能，会考虑你的建议。
 
另外，能否上 TG （如果能的话，请在 TG 私聊我）如果不能的话，请给我发邮件（你能找到我的邮件。  😀

**Comment by Kenshin** [comment]
可以的，邮件告诉给我你的微信就行。 😄

**Comment by Simon9511** [comment]
我的微信：szm998，感谢Kenshin！～ 😊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上10:40
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"763435633"<763435633@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 是否支持移动端一键将公众号文章加入稍后读？ (#1694)





 
可以的，邮件告诉给我你的微信就行。 😄

**Comment by Kenshin** [comment]
好的，明天加你。😃

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
