### ISSUE TITLE
浏览mdn网站时 出现开启标注自动同步到本地功能时,反复的提示

### ISSUE THREAD

**Issue by thinkles** [Kenshin/simpread#1697]
![image](https://user-images.githubusercontent.com/52523027/104272548-49a2b080-54d8-11eb-9efa-8e671b9b5f12.png)
反复提示 在同步助手打开选项, 但是已经打开过了, 换到在其他网页上开启功能并没有什么异常

**Comment by Kenshin** [comment]
嗨

同步助手是个 App http://ksria.com/simpread/docs/#/Sync
建议看下这个 https://github.com/Kenshin/simpread/discussions/1700 里面有是否需要使用同步助手的一些说明。

如果不想开启同步助手的话，可以直接看如何关闭 https://github.com/Kenshin/simpread/discussions/1692

**Comment by thinkles** [comment]
后台一直有运行同步助手,只有mdn网站会有反复提示这个情况

**Comment by Kenshin** [comment]
emm...

随便给我个链接看看。

**Comment by thinkles** [comment]
https://developer.mozilla.org/zh-CN/docs/Learn

**Comment by Kenshin** [comment]
进入给你我的页面后，并没有出现提示。

请问是进入页面后就会出现提示吗？

**Comment by thinkles** [comment]
进入网站 ,打开标注功能的自动保存按钮 , 进行标注时就会提示让你,打开同步助手的提示,并不会进行本地保存标注
但是,后台是一直在运行的, 我尝试了别的网站,发现别的网站标注自动保存是正常的

**Comment by Kenshin** [comment]
> 进入网站 ,打开标注功能的自动保存按钮 , 进行标注时就会提示让你,打开同步助手的提示,并不会进行本地保存标注
> 但是,后台是一直在运行的, 我尝试了别的网站,发现别的网站标注自动保存是正常的

嗨，刚测试了下，同样没有出现截图中的问题。

请在 **隐身模式下，仅启用简悦** 试试。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
