### ISSUE TITLE
在知乎问答页上不起作用

### ISSUE THREAD

**Issue by solobat** [Kenshin/simpread#17]
比如这个页面， https://www.zhihu.com/question/61081083
我想单独阅读某个答案，选聚焦模式没反应。

**Comment by Kenshin** [comment]
刚刚实验了下，是因为 `聚焦模式` 出现了错误导致，我先记录 Bug，只能下个版本解决掉了。

另外，知乎这种类 `论坛` 的页面暂时适配都不太完美（ 阅读模式 ），后续版本会专门上线适配这类页面的功能。
