### ISSUE TITLE
有没有可能多个文档合成一个epub或发送到kindle

### ISSUE THREAD

**Issue by TheKiteRunning** [Kenshin/simpread#170]
您好，有时候希望阅读一个系列的多个网页，希望合成一个epub文件，或者发送到kindle，请问有可能做到吗，谢谢。

**Comment by Kenshin** [comment]
感谢反馈~
目前暂时没有这样的功能，未来可能也不太会提供这样的功能。虽然也有阅读的诉求，但跟 `简悦` 的宗旨不太一样。（当然，也不是 100% 不可能）

你可以使用 https://epub.press/ 提供的扩展来实现你需要的功能。（ 简悦的 Epub 用的就是这个服务。）

**Comment by TheKiteRunning** [comment]
thanks～
