### ISSUE TITLE
错误弹出窗口

### ISSUE THREAD

**Issue by smartlyb** [Kenshin/simpread#1706]
![Snipaste_2021-01-14_16-53-18](https://user-images.githubusercontent.com/54233778/104568571-371ca880-568b-11eb-9ece-4a2c3d367960.png)

![Snipaste_2021-01-14_17-20-48](https://user-images.githubusercontent.com/54233778/104570815-59172a80-568d-11eb-83e8-68e02b44c533.png)

你好
我已准确定位到此问题，关闭其他应用软件后，打开简悦发现跳出此弹窗，我不知道是环境问题还是应该尝试重新安装解决，使用环境谷歌浏览器，win10 1909
尝试关掉窗口后，并不影响使用，但是每次启动后都会弹出

**Comment by Kenshin** [comment]
嗨，这个问题是因为 7026 被占用导致的。
猜测你是不是有某些防火墙之类的软件？

**Comment by smartlyb** [comment]
看样子可能是这样引起的，但是我并没有找到7026被占用的程序，经过尝试重装好像恢复正常了
