### ISSUE TITLE
https://lingcoder.github.io/OnJava8/ 没有正确识别

### ISSUE THREAD

**Issue by wxxb789** [Kenshin/simpread#1708]
**请说明发生问题的环境**

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://lingcoder.github.io/OnJava8/

**Comment by Kenshin** [comment]
谢谢反馈，但这个站并非大众类型的适配站点，简悦不会收录到 [官方适配源](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E9%80%82%E9%85%8D%E6%BA%90?id=%e5%ae%98%e6%96%b9%e9%80%82%e9%85%8d%e6%ba%90)。

你仍可以使用 [站点适配器](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8) 自行适配。

当然自行适配的前提是需要动一些简单的前端知识。

***

另外，我看了下，这个页面大多数是可以自行识别的，遇到无法识别的话，也可以使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE) 解决。
