### ISSUE TITLE
稍后读内置阅读模式无法导出全文的问题

### ISSUE THREAD

**Issue by GossipRanR** [Kenshin/simpread#1709]
使用稍后读的导出到本地的功能（包括pdf、html、markdown），导出的为标记内容的列表，无法导出带标记的原文。
与[【稍后读问题】希望在“稍后读”中增加全文导出功能](https://github.com/Kenshin/simpread/issues/1649)反馈的一致，但是按照作者的回复并不可行。

**Comment by Kenshin** [comment]
嗨，你应该在 TG 里面说过这个问题吧，谢谢提 issues 

我刚测试了下，使用 https://github.com/Kenshin/simpread/discussions/1712 描述的方法可以临时解决。

***

至于这个 Bug 要等到下个版本才能彻底解决。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
