### ISSUE TITLE
改变主题颜色以及目录的字体太小

### ISSUE THREAD

**Issue by zheshiyigehaomingzi** [Kenshin/simpread#171]

**Comment by Kenshin** [comment]
谢谢建议~  😀 
一般跟样式有关系的问题都可以通过 [自定义样式(https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by zheshiyigehaomingzi** [comment]
就是在电报群里说的那个将绀鼠的背景色加到白瓷里面去

**Comment by Kenshin** [comment]
@zheshiyigehaomingzi 
原来是你...  😀 

写好后，我会在这里通知你。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 关闭。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
