### ISSUE TITLE
隐私协议

### ISSUE THREAD

**Issue by Aspire1Inspire2** [Kenshin/simpread#1719]
请告知用户有关数据收集，使用和分析的相关信息。
注册用户，会员用户，未登录用户分别有什么数据被收集和使用了？是否卖给第三方服务用户数据？

谢谢。

**Comment by Kenshin** [comment]
嗨

http://simpread.pro/privacy.html

里面包含了你需要的一切。（官方说法）

另外，多提一句：

简悦甚至都没有登录系统，更谈何收集用户隐私了... 关于这块的话，你可以看下 https://github.com/Kenshin/simpread/discussions/1704

***

从某种程度上说，我比你们（简悦的用户）更重视（你们的）隐私。
