### ISSUE TITLE
阅读模式内容，无法发送到Kindle

### ISSUE THREAD

**Issue by sun3596209** [Kenshin/simpread#172]
发送到Kindle，提示“开始转码阅读模式并上传到服务器，请稍等‘，”保存到Kindle失败，请稍后再试“

**Comment by Kenshin** [comment]
请告知 url，另外转码有可能会失败，失败时会有提示。
关于 发送到 Kindle 的说明请看 https://github.com/Kenshin/simpread/wiki/发送到-Kindle

**Comment by sun3596209** [comment]
你好，比如说这个网址：https://www.zhihu.com/question/264106433，可以进入阅读模式，但是发送到Kindle的时候，就报错。

**Comment by Kenshin** [comment]
@sun3596209 
额，这是正常的，原因：
- 发送的文本（有可能）超出的最大限制。（因为发送到 Kindle 功能使用了免费的服务器，所以对 size 有大小要求）
- 论坛类 页面发送到 Kindle 是不太友好的（由于结构问题所以转换失败率比较高），建议还是发送单页面内容到 Kindle 比较好。

比如：https://sspai.com 随便的一篇文章都应该没有问题。

**Comment by ddkk3000** [comment]
我也发不了。我看到你们有下载为epub的功能，能不能你们自己做发送到kindle的功能？

**Comment by Kenshin** [comment]
@sun3596209
方便的话，请告知 url ，简悦并没有自己的服务器，它只是是个免费的扩展。

不过，不排除未来会提供收费服务。

**Comment by ddkk3000** [comment]
https://www.zhihu.com/question/21894172

**Comment by Kenshin** [comment]
@ddkk300
请看 最上面我的回复。

**Comment by sun3596209** [comment]
@Kenshin 你好，你发的少数派的网站，也无法发送到Kindle，一样的错误提示。请问，还有其他什么原因？

**Comment by Kenshin** [comment]
@sun3596209 
你好，我刚刚有测了一下，并没问题。请告知 url

**Comment by Kenshin** [comment]
Hi，现在还会发生这样的情况吗？

**Comment by ddkk3000** [comment]
汗，现在没试了，因为kindle不能，我直接放弃了kindle，不用了。
发件人： Kenshin Wang<mailto:notifications@github.com>
发送时间： 2018-03-31 11:08:09
收件人：  Kenshin/simpread<mailto:simpread@noreply.github.com>
抄送：  ddkk3000<mailto:lixiaozhe@live.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [Kenshin/simpread] 阅读模式内容，无法发送到Kindle (#172)

Hi，现在还会发生这样的情况吗？

**Comment by Kenshin** [comment]
放弃了 Kindle ？
如果没有问题的话，我关闭此 issues 了~
