### ISSUE TITLE
csdn剪藏到notion代码段出现数字

### ISSUE THREAD

**Issue by YM199** [Kenshin/simpread#1722]
![1](https://user-images.githubusercontent.com/67450240/104838536-7dc20b00-58f6-11eb-9054-887e016ec9ac.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by Kenshin** [comment]
另外，请告知出问题的 URL 才会记录到 #500 里面

**Comment by YM199** [comment]
> 另外，请告知出问题的 URL 才会记录到 #500 里面
https://blog.csdn.net/liebao_han/article/details/78931683

**Comment by Kenshin** [comment]
收到，已记录
