### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by BlackEven** [Kenshin/simpread#1724]
发生问题的地址: <https://mp.weixin.qq.com/s/rH_TwP7wshehUppGAq4fJQ>

**Comment by Kenshin** [comment]
谢谢反馈，印象笔记一直是顽疾... 我会把这些内容集中到 https://github.com/Kenshin/simpread/issues/302
并关闭此 issues 
当修改后，我会在这里回复你。
