### ISSUE TITLE
高级账户无法导出为PDF

### ISSUE THREAD

**Issue by wang536542** [Kenshin/simpread#1727]
![image](https://user-images.githubusercontent.com/77597683/104865838-092fb080-5978-11eb-917e-ce4367657f7c.png)
![image](https://user-images.githubusercontent.com/77597683/104865845-0c2aa100-5978-11eb-8928-111d4d2a713b.png)

购买高级账户并绑定成功并重启chrome后，无法导出PDF，显示请确保已运行  **简悦 同步助手**，在chrome插件管理里面关闭并重启简悦插件也不行。
![1](https://user-images.githubusercontent.com/77597683/104865916-3bd9a900-5978-11eb-9df6-149130fe020b.png)

**Comment by Kenshin** [comment]
嗨，可以看下 https://github.com/Kenshin/simpread/discussions/1617 https://github.com/Kenshin/simpread/discussions/1566 这两个解决方案。

一般能可以解决你的疑问。

**Comment by wang536542** [comment]
收到，谢谢亲。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午10:55
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"涅槃重生"<674442049@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 高级账户无法导出为PDF (#1727)





 
嗨，可以看下 #1617 #1566 这两个解决方案。
 
一般能可以解决你的疑问。

**Comment by Kenshin** [comment]
没事，搞定后请关闭此 Issues~
