### ISSUE TITLE
选项页面乱码了

### ISSUE THREAD

**Issue by wuhaoharry** [Kenshin/simpread#1730]
选项页面乱码了，而且简悦配置文件保存不了，手动保存了UID。卸载重新安装之后，没法重新填写UID。

![image](https://user-images.githubusercontent.com/41421005/105011792-54c98380-5a78-11eb-9490-2f683d45f4a8.png)

**Comment by Kenshin** [comment]
嗨，这是解决方案 https://github.com/Kenshin/simpread/discussions/1639

**Comment by Kenshin** [comment]
另外，重新安装后，需要修改导入之前的配置文件就可以了。
