### ISSUE TITLE
高级账户导出原生pdf 图片显示不全，右边有一部分被切掉了 也没有边框。（仅限 Windows）

### ISSUE THREAD

**Issue by hwlong** [Kenshin/simpread#1732]
![无标题](https://user-images.githubusercontent.com/13386422/105145619-f4027f80-5b39-11eb-9f83-635dfd2fbc56.png)

**Comment by Kenshin** [comment]
谢谢反馈，请告知 url

**Comment by hwlong** [comment]
https://gitbook.cn/gitchat/column/5dae96ec669f843a1a4aed95/topic/5db16c4dbae3b42c1fa82cd2

**Comment by hwlong** [comment]
可以对比下图片和生成的pdf。

**Comment by Kenshin** [comment]
我这边没有问题。

（可能）这里有个误区，所谓的 高级账户导出 PDF 是指：**使用同步助手的方式导出**

附上我生成的 PDF

[和数据打交道的你，一定要学会 SQL.pdf](https://github.com/Kenshin/simpread/files/5846693/SQL.pdf)

**Comment by hwlong** [comment]
你是怎么导出来的 我刚又试了一遍 还是同样的问题，无论是阅读模式还是聚焦模式！能说一下你的操作步骤吗？

**Comment by Kenshin** [comment]
正常导出。

PS：我怀疑你没有使用高级账户的 PDF 导出功能，建议看看 https://github.com/Kenshin/simpread/discussions/1617 https://github.com/Kenshin/simpread/discussions/1566 http://ksria.com/simpread/docs/#/Sync?id=pdf

**Comment by hwlong** [comment]
步骤我肯定没错，我肯定使用高级账户的 PDF 导出功能，环境是：win10,chrome 87, SimpRead 2.1.0。

**Comment by Kenshin** [comment]
@hwlong 

emmm.... 这不太应该。（问个初级问题，如果使用 高级账户导出 PDF 的话，不会通过浏览器下载 PDF。

另外，也请告知你的操作环境与浏览器版本。

**Comment by hwlong** [comment]
环境上面回复过了，自认为操作没有问题无非是先进入阅读模式或者聚焦模式，然后
![2021-01-26_110443](https://user-images.githubusercontent.com/13386422/105794722-900f0980-5fc6-11eb-95a0-deb7a6b6f4b3.png)，或者
![2021-01-26_110727](https://user-images.githubusercontent.com/13386422/105794833-c9e01000-5fc6-11eb-807f-7a2b0a304506.png)

**Comment by hwlong** [comment]
> @hwlong
> 
> emmm.... 这不太应该。（问个初级问题，如果使用 高级账户导出 PDF 的话，不会通过浏览器下载 PDF。
> 
> 另外，也请告知你的操作环境与浏览器版本。

我知道不会通过浏览器下载PDF，但是页面是渲染在浏览器上，总得从上面读取吧，会不会是浏览器版本不一致导致读取内容不一致？

**Comment by hwlong** [comment]
通过一系列的复杂操作总算是好了，首先页面缩放到90%(总之得小于100%)，然后用阅读模式，聚焦模式还不行，这样导出才能显示全部。
[和数据打交道的你，一定要学会 SQL.pdf](https://github.com/Kenshin/simpread/files/5871036/SQL.pdf)

**Comment by Kenshin** [comment]
@hwlong 
> 但是页面是渲染在浏览器上，总得从上面读取吧，会不会是浏览器版本不一致导致读取内容不一致？

抱歉，使用同步助手的话，还真不是...

***

> 通过一系列的复杂操作总算是好了，首先页面缩放到90%(总之得小于100%)，然后用阅读模式，聚焦模式还不行，这样导出才能显示全部。

还是没理解你的问题所在。因为 PDF 的生成跟这个页面无关，只跟这个页面的文字有关系。

***

我给你没问题的 PDF 是在 Mac OS 下，回头我试试 win 的情况。（再回复你

**Comment by Kenshin** [comment]
此 PDF 是 win 10 Edge 88 导出的，你可以看看。

[和数据打交道的你，一定要学会 SQL.pdf](https://github.com/Kenshin/simpread/files/5871641/SQL.pdf)

**Comment by hwlong** [comment]
哈哈 您仔细看一下pdf中的第一张图，是不是被裁边了？！

**Comment by Kenshin** [comment]
> 哈哈 您仔细看一下pdf中的第一张图，是不是被裁边了？！

emm... 竟然真是，我明天看下 Mac 版是否也这样？

我一直理解的是：「图上下裂开」这个意思。 😂

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
