### ISSUE TITLE
onenote 授权失败问题

### ISSUE THREAD

**Issue by kkwow** [Kenshin/simpread#1735]
chrome 版本 88.0.4324.96（正式版本） （64 位）
停用所有插件，重置浏览器
都无法解决问题。
https://login.live.com/oauth20_token.srf 内容显示以下
`{"error":"invalid_client","error_description":"The provided request must include a 'client_id' input parameter.","correlation_id":"fb96faf4-a967-4646-882d-c2415fad40f9"}`

截图
https://user-images.githubusercontent.com/15723157/105325332-70af5f80-5c07-11eb-8134-c8cdc3ac17b1.png

**Comment by Kenshin** [comment]
emmm

比较奇怪，按道理不应该存在无法授权的情况。能否更换个网络环境试试？

**Comment by kkwow** [comment]
切换 移动热点，联通热点，均无效。 我卸载简悦，重新安装后，授权成功。
新问题：保存onenote，提示保存成功。但是搜索选笔记 无法找到保存的文章。

**Comment by kkwow** [comment]
已订阅。

```
谢谢对简悦的支持。
因为 2.1.0 版购买较多，兑换时间延迟为 48 小时。
```

**Comment by kkwow** [comment]
今天发现无法保存了。 微软显示授权，简悦设置也是授权状态，保存到onenote 就提示 请重新授权。
![image](https://user-images.githubusercontent.com/15723157/105433714-18bf3a00-5c95-11eb-9af1-fb741280df1a.png)
![image](https://user-images.githubusercontent.com/15723157/105433724-1e1c8480-5c95-11eb-91bc-a26b7e03e3ea.png)
![image](https://user-images.githubusercontent.com/15723157/105433731-2248a200-5c95-11eb-9a88-1e6dc95de394.png)

请问我这边是等待后续更新就可以了？  预计多久，我关注一下。

**Comment by Kenshin** [comment]
@kkwow 
截图的问题跟新版授权（时长改动）无关，我还是怀疑你弄「乱」了配置环境。

你可以取消 Onenote 的授权，重新试试。（或老办法，重装简悦）

**Comment by kkwow** [comment]
重装后解决，非常感谢。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
