### ISSUE TITLE
保存到印象笔记中的文章，失去了悦读优化的样式，没能将良好的悦读体验延续，痛心疾首啊

### ISSUE THREAD

**Issue by iamfeiyu** [Kenshin/simpread#1739]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **windows64位 专业版 20H2 版本号最新**

- 浏览器版本 **Chrome  87.0.4280.141**

- 简悦版本 **2021/1/22 最新版**

- 发生问题的地址 https://baike.baidu.com/tashuo/browse/content?id=11fca6ec3dcb276af5c5592b&lemmaId=10529773&fromLemmaModule=pcRight

**请描述你的问题**

> 使用悦读优化页面排版后，将其保存到印象笔记，打开印象笔记发现失去了悦读优化的样式，没能将良好的悦读体验延续，痛心疾首啊

**截图**

![image](https://user-images.githubusercontent.com/25132486/105435239-f7138200-5c97-11eb-83f8-23c464dfce6b.png)
![image](https://user-images.githubusercontent.com/25132486/105435210-e531df00-5c97-11eb-8e79-5c51e1ae8cff.png)
![image](https://user-images.githubusercontent.com/25132486/105435272-08f52500-5c98-11eb-87d1-9ede77de6f8d.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
这是正常的，除了印象笔记自己的扩展能实现此功能外，其余的扩展几乎不能实现。
我会集中把这些问题放到 https://github.com/Kenshin/simpread/issues/302 里面。

因为重复的 issues 太多，所以此 Issues 会被关闭，修复后我会逐一回复你们。
