### ISSUE TITLE
豆瓣一刻页面结构改变，无法适配旧规则

### ISSUE THREAD

**Issue by huLter** [Kenshin/simpread#174]
https://moment.douban.com/post/179618
不过临时模式可用

**Comment by Kenshin** [comment]
感谢反馈，的确页面结构改变导致~
我会修改这个站点的适配规则。
另外，即将发布的 `1.1.0` 可以修改任意的适配规则了，到时候可以它可以自行修改。（暂时还不允许）

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
