### ISSUE TITLE
怎么关闭自动弹出浮动栏的功能 

### ISSUE THREAD

**Issue by qiaogaojian** [Kenshin/simpread#1740]
鼠标移动时自动显示浮动栏一闪一闪的很影响体验, 请问怎么才能选择后才显示而不是自动显示

**Comment by Kenshin** [comment]
下个版本提供 **点击才显示** 的选项。

**Comment by qiaogaojian** [comment]
OK

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
