### ISSUE TITLE
有时会提示 "获取正文失败，是否使用手动框选高亮的方式获取？"  从而无法使用高级功能

### ISSUE THREAD

**Issue by qiaogaojian** [Kenshin/simpread#1744]
有时会提示 "获取正文失败，是否使用手动框选高亮的方式获取？" 无法进入阅读模式,而插件的付费功能进入阅读模式才能使用, 刷新和重新打开标签无法解决问题, 重新打开浏览器后正常

**Comment by qiaogaojian** [comment]
使用提示的手动模式进入阅读模式后图片无法加载 无限loading 
![image](https://user-images.githubusercontent.com/22113252/105476531-b8072000-5cdb-11eb-93e1-5529ae738d34.png)

**Comment by Kenshin** [comment]
> 有时会提示 "获取正文失败，是否使用手动框选高亮的方式获取？" 无法进入阅读模式,而插件的付费功能进入阅读模式才能使用, 刷新和重新打开标签无法解决问题, 重新打开浏览器后正常

> 获取正文失败，是否使用手动框选高亮的方式获取

这是正常的事情，因为未适配页面不是 100% 可以生成阅读模式的。

> 刷新和重新打开标签无法解决问题, 重新打开浏览器后正常 

不应该发生，所以建议给我看看 URL 我来判断下。

**Comment by qiaogaojian** [comment]
刚才又试了一下 应该是两次进入不是同一个界面

**Comment by Kenshin** [comment]
了解，没其他问题的话，可以关闭此 Issues 了。

至于你提到的其他问题，我应该都回复了。

**Comment by qiaogaojian** [comment]
谢谢
