### ISSUE TITLE
使用同步助手导出 PDF 因图片防盗链造成无法显示的问题

### ISSUE THREAD

**Issue by tingtho** [Kenshin/simpread#1745]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10**

- 浏览器版本 **e.g. Chrome 87**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s?__biz=MzIyODI1MzYyNA==&mid=2653541274&idx=1&sn=a367f3f7b78d0b5b21fd3f22bd82b1ad&chksm=f389b94dc4fe305b3bdda415751abcf418004edcf240316c9cf89ec97d12d2065e945634e882&scene=178&cur_album_id=1339183650063220738#rdl>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

同步助手PDF导出功能无法抓取图片，以前导出没有这问题，都是先显示下载图片，然后开始保存，现在没有显示下载图片的提示就直接保存了，然后由于微信的反盗链导致图片无法显示，

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/37473449/105478135-c22a1e00-5cdd-11eb-8cdf-8aa9df59cfe6.png)

**Comment by Kenshin** [comment]
是的，因防盗链造成的，下个版本修复。

你可以暂时使用浏览器自带的导出方式

**Comment by tingtho** [comment]
> 是的，因防盗链造成的，下个版本修复。
> 
> 你可以暂时使用浏览器自带的导出方式

还有简书也有一样的问题

**Comment by huhublog** [comment]
CSDN 也存在一样的问题

**Comment by buildaworld** [comment]
https://www.guancha.cn/
有同样的问题

**Comment by buildaworld** [comment]
试了2个网站，还是一样的问题，期待版本更新，现在暂时用markdown转pdf过渡

**Comment by Kenshin** [comment]
@buildaworld

建议暂时使用浏览器的打印功能，新版发布后我会在这里通知你~

**Comment by buildaworld** [comment]
非常感谢

浏览器打印及另存为pdf都会有文字和图片跨页的问题，所以就暂时用markdown了

**Comment by Kenshin** [comment]
> 非常感谢
> 
> 浏览器打印及另存为pdf都会有文字和图片跨页的问题，所以就暂时用markdown了

是的，但毕竟不是每个页面都存在这个情况，当然这也是我增加自有 PDF 导出的目的。 😅 

其实防盗链的页面并不多（所以，我也没有在最初就发现并 Fixed 掉这个问题的原因），但确实很集中存在于一些常见生成 PDF 的场景。 😂 

没错，我就说的就是：微信订阅号。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
