### ISSUE TITLE
导出标记到 Notion 的 Markdown 结构需要优化

### ISSUE THREAD

**Issue by hxu38691** [Kenshin/simpread#1746]
自动添加的分线栏, 无法批量使用"turn-into"等功能

quote 1
--------
quote 2

没有分线栏的话可以

quote 1
quote 2

**Comment by hxu38691** [comment]
复制到剪切板，再粘贴解决问题。。。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
