### ISSUE TITLE
新站适配：百度网盘文章页

### ISSUE THREAD

**Issue by xfrqh** [Kenshin/simpread#1747]
发生问题的地址: <https://wenzhang.baidu.com/article/view?key=fea5785959b05ac4-1533816340>

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
可以适配这个页面。

PS：百度网盘竟然有这种功能，第一次知道。

**Comment by xfrqh** [comment]
好吧，这个站点可以不管了。
因为百度已经停止了此服务。
你可以打开此网址，点击右上角的”+“新建一篇文章。百度网盘仅会建立快捷方式。
https://wenzhang.baidu.com/

**Comment by Kenshin** [comment]
@xfrqh 
哦，原来如此，现在只是个快捷方式，但我的里面确实存在一些文档。
既然这样的话，我关闭此 Issues 了~
