### ISSUE TITLE
如何通过简悦同步标注到 Readwise

### ISSUE THREAD

**Issue by legend053** [Kenshin/simpread#1749]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Vivaldi 3.5.2115.87 (Stable channel) (x86_64)**

- 简悦版本 **2.1.0**

**请描述你的问题**

*highlight 的网页无法导出到readwise.io. 进入到阅读模式下，高亮了一些段落。我也导出到“稍后读”里。但是，登陆到readwise里，没有看到标注的网页被同步过来。我按照说明进行了设置。也设置了Hypothes.is。在readwise里面也链接了Hypothes.is。*

**截图**
![issue](https://user-images.githubusercontent.com/7464388/105568471-29a49580-5cff-11eb-9f98-3dee7005550c.jpg)

**Comment by Kenshin** [comment]
Mac 系统的话，同步助手是可以直接支持 简悦 → readwise.io 而无需使用 Hypothes 中转。
（我目前就是这么做的）

在 http://ksria.com/simpread/docs/#/Sync?id=下载 打开随便一个下载地址，如 https://onedrive.live.com/?authkey=%21AIsCKC8oZsYQczM&id=11407577D948B8E6%21968&cid=11407577D948B8E6

下载 **简悦 · 同步助手 1.0.0@mac with readwise.io** 此版本即可。

![image](https://user-images.githubusercontent.com/81074/105576048-0fc08c80-5dab-11eb-9aea-afd5f6abb4aa.png)

通过登录   https://readwise.io/api_deets 的到 Token 并填入其中。

![image](https://user-images.githubusercontent.com/81074/105576060-27981080-5dab-11eb-9863-abd84df5027b.png)

勾选下图所示的选项

![image](https://user-images.githubusercontent.com/81074/105576406-88284d00-5dad-11eb-9769-e7cf784f92b4.png)

***

同步 readwise.io 使用了 Hypothes 的「通道」，因为简悦 2.1 发布时还未发布 readwise.io API 故暂时使用这种方式作为「桥接」

当然，我发现这块的文档缺失，我会补齐这块的文档。
另外，扩展端的下个版本会「修复」通过 Hypothes 中转方案（有 readwise.io 的方案）

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
