### ISSUE TITLE
印象笔记授权

### ISSUE THREAD

**Issue by Aaloone** [Kenshin/simpread#175]
授权了好几次，邮件也发了好几封，但是依然然并卵呀，希望作者可惜解决一下，谢谢

**Comment by Kenshin** [comment]
感谢反馈，应该没有问题的。
另外，授权后会有明确的提示，所以在未有明确提示的时候，切勿关闭 `选项页`。

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
