### ISSUE TITLE
高级账户，bilibili专栏导出pdf时图片解析失败

### ISSUE THREAD

**Issue by SigiL71615** [Kenshin/simpread#1751]
- 操作系统 **Windows**

- 浏览器版本 **Chrome 88.0.4324.104（正式版本） （64 位）**

- 简悦版本 **2.0.0**

进入bilibili专栏的阅读模式，专栏图片在阅读模式下解析成功；

但当使用同步助手，选择导出pdf到本地后，专栏图片在本地pdf中解析失败。

**Comment by Kenshin** [comment]
谢谢反馈，估计是因为防盗链造成的问题。
下个版本修复。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
