### ISSUE TITLE
进入阅读模式后代码注释不显示

### ISSUE THREAD

**Issue by crazyshark** [Kenshin/simpread#1754]
浏览网页：http://www.iocoder.cn/JUC/sike/aqs-1-clh/ ，Chrome版本：87.0.4280.141，mac os 10.15.7

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
