### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by MinLonger** [Kenshin/simpread#1755]
- 操作系统 **Win10 64bit 1909 **

- 浏览器版本 **Chrome 88.0.4324.104**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

我在导入配置文件登录高级账户权限时，出现一直只显示导入成功，但就是不激活。重复测试多次一样，重新安装后测试一样。辛苦帮忙解答。谢谢！

![image_1](https://user-images.githubusercontent.com/5369796/105697379-71b1fb00-5f3f-11eb-935b-669d3dd583f3.png)

**Comment by Kenshin** [comment]
嗨，如果无法自动恢复成功的话，试试右上角 → 仅授权当前设备为高级账户。

**Comment by MinLonger** [comment]
我本来想要忍忍的，但后来我别的电脑重装系统后也出现了这个问题.现在只要是新装插件都存在这个问题，不论在哪个电脑上。我尝试过：

**Comment by Kenshin** [comment]
嗨

初步怀疑是这个问题导致的 https://github.com/Kenshin/simpread/discussions/1567

另外，看描述你应该保存了自己的 UID，确保你的在授权或登录时的 UID 为注册时 UID

如何确定 UID：
- 使用 2.1 版本授权时，会自动下载一个配置文件（内含正确的 UID）
- 使用 2.0 版本授权时，则需要手动保存这个配置文件

假定你的 UID 没有问题，请看上面链接给出的解决方案；反之，你可以把你得到的 License 发到我的信箱里面（附上购买凭证）

**Comment by Kenshin** [comment]
请使用 https://github.com/Kenshin/simpread/issues/1950#issuecomment-803236105 提供的 **方案一** 进行操作。

**Comment by MinLonger** [comment]
已经按照作者提示操作并找回高级账户，谢谢！

**Comment by Kenshin** [comment]
搞定就好~
