### ISSUE TITLE
找回UID后无法绑定，提示：此密钥已被使用,点击重新确认或联系管理员

### ISSUE THREAD

**Issue by zjD27** [Kenshin/simpread#1758]
重装了 Chrome，然后想要激活高级账户无法激活，然后按照提示找回了UID，重新点击“绑定高级账户资格”，提示：此密钥已被使用,点击重新确认或联系管理员！
<img width="767" alt="截图2021-01-26_09-47-17" src="https://user-images.githubusercontent.com/37474683/105798149-707adf80-5fcc-11eb-901c-d3b5037e91ea.png"
请问如何解决？
另外：恕我直言
应用付费理所当然，但是一个登录绑定的功能是在坑人，我看了帮助贴找回UID绑定key，那么多多的字，我浪费了一早上也没解决问题，实在浪费时间很，为什么不能第一次激活加一个引导操作，我需要的是你的功能，花钱不是想去看你那些操作提示！
言语过激，抱歉！

**Comment by Kenshin** [comment]
选项页 → 账户 → 找回 UID
然后后自动找回并自动配置并自动授权为高级账户

> 绑定高级账户资格

![image](https://user-images.githubusercontent.com/81074/105809390-8e543e80-5fe4-11eb-9b42-277ef37d04ad.png)
