### ISSUE TITLE
右键菜单添加保存到稍后读

### ISSUE THREAD

**Issue by Quantizen** [Kenshin/simpread#176]
有时并不想当即就读，而是保存稍后读。这时打开阅读或聚焦模式才能在控制栏中调出“保存到 稍后读”，有点过于麻烦。如果右键菜单或点击插件图标能有这个选项最好。

**Comment by Kenshin** [comment]
`阅读模式` 支持快捷键操作，详细请看 https://github.com/Kenshin/simpread/wiki/快捷键

操作步骤：
进入阅读模式 →  sr → rl 
即可。

**Comment by Quantizen** [comment]
这样操作三步过于复杂，而稍后阅读很多时候也是一个主要需求。再者，经测试临时阅读模式下`sr->rl`并不能用。

**Comment by Kenshin** [comment]
`稍后读` 并不是一个独立的功能，它存在的价值需要依附在 `聚焦模式` 或 `阅读模式` 上，所以 `三步` 的第一步无法省略。

另外，临时阅读模式下，`sr → rl` 并没有问题，方便的话，请告知有问题的 url 给我。

PS： 虽然我也经常使用它，但 `稍后读` 并不是一个主需求，因为可以替代它的产品有太多了。如果你频繁使用稍后读的话，建议使用 Pocket / Instapaper 因为这些更强大些。（感谢对稍后读的喜爱~）

**Comment by Kenshin** [comment]
简悦 `1.1.0` 包含了右键发送到稍后读的功能，此 issues 将关闭，如需要重新开启它。 😊
