### ISSUE TITLE
无法选中文字

### ISSUE THREAD

**Issue by haozi2333** [Kenshin/simpread#1762]
- 操作系统 **Win64**

- 浏览器版本 **Chrome 87.0.4280.141**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://sspai.com/post/64749>

**请描述你的问题**

> 所有html标签带有::marker都无法选中

**截图**
![image](https://user-images.githubusercontent.com/16058531/106020750-0c0c6d00-60ff-11eb-97c2-e8d95902f2b5.png)

![image](https://user-images.githubusercontent.com/16058531/106020956-3f4efc00-60ff-11eb-9464-275c39fd416b.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，你可以看下 https://github.com/Kenshin/simpread/discussions/1674 解决方案（及说明）

所以，我关闭此 Issues 了，如有异议请重开它。

**Comment by haozi2333** [comment]
我想表达的意思是无法被标注，无法标注为笔记
