### ISSUE TITLE
当本地没有配置文件时使用同步助手读取配置文件流程需要优化

### ISSUE THREAD

**Issue by Leexiaobu** [Kenshin/simpread#1763]
- 操作系统 **Windows**

- 浏览器版本 **Chrome 87.0.4280.141**

- 简悦版本 **2.1.0**

![gif](https://user-images.githubusercontent.com/20644303/106037930-45020d00-6112-11eb-80a3-a0479fe76529.gif)

**Comment by Kenshin** [comment]
看了下视频操作，应该是你配置错误造成的，建议看看：

https://github.com/Kenshin/simpread/discussions/1700
https://github.com/Kenshin/simpread/discussions/1692

的说明，估计能对同步助手有个基本操作上的了解。

**Comment by Leexiaobu** [comment]
**我通过关闭同步助手客户端的同步选项恢复了**，  

我操作的流程如下：
1.本地客户端开启了自动同步选项，
2.在网页端开启自动同步
3.**没有先通过同步助手保存当前配置文件**就直接先 通过同步助手**覆盖当前文件**（此时同步助手文件夹下无配置文件）。
4.后面我通过同步助手保存配置至本地文件，然后清空了配置文件，重现了此现象。  

**所以我认为根本原因是在无配置文件或者配置文件为空时，仍然读取了配置。**

**Comment by Kenshin** [comment]
> 所以我认为根本原因是在无配置文件或者配置文件为空时，仍然读取了配置。

可以考虑加个判断来加强合法性验证。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
