### ISSUE TITLE
快捷方式冲突

### ISSUE THREAD

**Issue by qiutianhua** [Kenshin/simpread#1764]
在谷歌浏览器上安装简悦后与电脑原来使用的鼠标快捷软件（WGestures软件）有冲突，无法使用关闭快捷方式
![image](https://user-images.githubusercontent.com/35244056/106077882-59afc680-614d-11eb-9fb7-8bb75027a032.png)

**Comment by Kenshin** [comment]
请看 http://ksria.com/simpread/docs/#/快捷键 是不是跟你的某些快捷键冲突了？

PS：请在 **隐身模式下，仅启用简悦** 的方式排除其它扩展造成的干扰。

**Comment by qiutianhua** [comment]
好的&nbsp; 已排查解决了，是我把简悦的快捷键设置成和谷歌浏览器默认的快捷键一样了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 上午10:49
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"LEON"<qiuth123@gmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 快捷方式冲突 (#1764)





 
请看 http://ksria.com/simpread/docs/#/快捷键 是不是跟你的某些快捷键冲突了？
 
PS：请在 隐身模式下，仅启用简悦 的方式排除其它扩展造成的干扰。

**Comment by Kenshin** [comment]
okay 搞定就好，那我关闭此 Issues 了。
