### ISSUE TITLE
导出PDF格式失败

### ISSUE THREAD

**Issue by Lawson332** [Kenshin/simpread#1765]
![image](https://user-images.githubusercontent.com/78124802/106078849-13f3fd80-614f-11eb-9492-a093e184eecc.png)
显示这类问题，如何解决？

**Comment by Kenshin** [comment]
嗨，关于 PDF 的问题，应该是个小 Bug 引起的，但可以绕过去，详细可以看：

https://github.com/Kenshin/simpread/discussions/1566
https://github.com/Kenshin/simpread/discussions/1562
https://github.com/Kenshin/simpread/discussions/1617

这三个解决方案。

***

目前只有一种情况有问题：当页面存在防盗链的图片时，导出时会有问题，此问题下个版本解决。

所以，我关闭此 issues 了，如果无法解决你的问题，请随时重开它，并详细描述无法解决的原因。

**Comment by Lawson332** [comment]
已解决，感谢！
