### ISSUE TITLE
特殊字段情况下无法标注的问题

### ISSUE THREAD

**Issue by haozi2333** [Kenshin/simpread#1766]
> * 操作系统 **Win64**
> * 浏览器版本 **Chrome 87.0.4280.141**
> * 简悦版本 **2.1.0**
> * 发生问题的地址 https://sspai.com/post/64749
> 
> **请描述你的问题**
> 
> > 所有 html 标签带有::marker 都无法添加为   **笔记**
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/16058531/106020750-0c0c6d00-60ff-11eb-97c2-e8d95902f2b5.png)
> 
> ![image](https://user-images.githubusercontent.com/16058531/106020956-3f4efc00-60ff-11eb-9464-275c39fd416b.png)
> 
> > 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
okay 收到。（其实可以不用重建一个新 Issues ） 不过，也无所谓的。 😀

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
