### ISSUE TITLE
无法授权 Notion （提示 415 错误）

### ISSUE THREAD

**Issue by xyfx666** [Kenshin/simpread#1768]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

![image](https://user-images.githubusercontent.com/51446918/106122793-03dd1d80-6151-11eb-9d4b-01ecba998460.png)
无法授权notion

**Comment by zzq96** [comment]
我也是

**Comment by Kenshin** [comment]
嗨，我看了下，似乎是 Notion API 改变造成的。（如果之前曾经授权过 Notion 应该不受其影响，但新授权用户会出现问题。

虽然不是 100% 确定，但基本上就是这个问题。（我重新授权就不行，但用之前的 Token 则没问题）

**Comment by Kenshin** [comment]
@zzq96 @xyfx666

嗨，各位，Notion API 没有问题，可能是不稳定造成的，我今天用昨天没有成功授权的设备重新测试了一次，已经没有问题了！

所以，最大的可能性是：因为私有 API 所以并不稳定...

**Comment by yang478** [comment]
我也是出现了这个问题，而且没有看到解决的方案


操作系统 Win10 1909

浏览器版本 Edge  88.0.705.74 

简悦版本 2.1.0

发生问题的地址 extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by yang478** [comment]
![Snipaste_2021-02-27_16-12-07](https://user-images.githubusercontent.com/55377570/109381662-a0dcd300-7916-11eb-990e-828366b1bf31.jpg)

**Comment by yang478** [comment]
**我看到了解决说明，昨天就无法授权，今天又试了一下，notion依然无法授权，不知道怎么解决，主要是把notion的链接上的内容整理了一下，就成了这样了**
![Snipaste_2021-02-28_14-34-01](https://user-images.githubusercontent.com/55377570/109409993-19549a00-79d2-11eb-912e-f477ccb60b7c.jpg)

**Comment by Kenshin** [comment]
@yang478 

估计是这个问题造成的，细节看 https://github.com/Kenshin/simpread/issues/1894

**Comment by yang478** [comment]
OKay,我试一试，如果可以用再反馈给您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin Wang"<notifications@github.com&gt;; 
发送时间: 2021年2月28日(星期天) 晚上6:19
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;; 
抄送: "断川分海"<1378557527@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Kenshin/simpread] 无法授权notion (#1768)





 
@yang478
 
估计是这个问题造成的，细节看 #1894

**Comment by yang478** [comment]
今天仍然还是无法正常使用，怀疑有可能是最近特殊时期导致？我甚至无法正常上github




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 晚上6:19
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"断川分海"<1378557527@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 无法授权notion (#1768)





 
@yang478
 
估计是这个问题造成的，细节看 #1894

**Comment by Kenshin** [comment]
@xyfx666 

是的，我刚确认了下，确实仍有问题，我问问 Notion 的相关人员吧，尽快给你回复。

**Comment by Kenshin** [comment]
嗨，各位，如果发生 415 错误的话，请看这里的说明 https://github.com/Kenshin/simpread/discussions/1773

我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
