### ISSUE TITLE
浏览器窗口多开，页面渲染错误

### ISSUE THREAD

**Issue by 5iclound** [Kenshin/simpread#1769]
### 窗口1
**正常页面**
![image](https://user-images.githubusercontent.com/49341227/106126556-76252080-6198-11eb-88e2-4ef55838b8d8.png)

**阅读页面**
![image](https://user-images.githubusercontent.com/49341227/106124497-19c10180-6196-11eb-8404-fc09b530bc73.png)
### 窗口2
**正常页面**
![image](https://user-images.githubusercontent.com/49341227/106126477-5f7ec980-6198-11eb-9f6d-eebc695515f3.png)

**阅读页面**
![image](https://user-images.githubusercontent.com/49341227/106124368-fd24c980-6195-11eb-8f6a-4244e4fab0fe.png)
希望作者能修复这个页面多开的Bug，并且支持窗口多开功能

**Comment by Kenshin** [comment]
谢谢反馈，但我没理解你的意思...

图1和图2 → 应该是正常且正确的情况。
图3 → 应该不需要进入阅读模式，也没有进入阅读模式的必要。
图4 → 如何得到的？

**Comment by 5iclound** [comment]
图4在这个网站中使用阅读模式得到&nbsp;https://www.alhelp.net/home/index.html
我再次尝试多开窗口和页面渲染错误并没有关联，而是网站的问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 晚上6:56
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"2645279204"<2645279204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 浏览器窗口多开，页面渲染错误 (#1769)





 
谢谢反馈，但我没理解你的意思...
 
图1和图2 → 应该是正常且正确的情况。
 图3 → 应该不需要进入阅读模式，也没有进入阅读模式的必要。
 图4 → 如何得到的？

**Comment by Kenshin** [comment]
> 图4在这个网站中使用阅读模式得到 https://www.alhelp.net/home/index.html

很显然，此页面不需要使用阅读模式，否则有可能出现问题。

另外，既然没有再出现问题，我关闭此 issues 了~
