### ISSUE TITLE
mac端批注功能文字重影

### ISSUE THREAD

**Issue by LeokuJessica** [Kenshin/simpread#1774]
<img width="1392" alt="截屏2021-01-30 08 29 14" src="https://user-images.githubusercontent.com/62162557/106340865-2cdaeb00-62d6-11eb-92c7-2361fff9c455.png">
<img width="1392" alt="截屏2021-01-30 08 29 22" src="https://user-images.githubusercontent.com/62162557/106340872-2ea4ae80-62d6-11eb-80b9-41f005552f08.png">
如图

**Comment by Kenshin** [comment]
谢谢反馈，下个版本会解决这个问题。（或者你了解 CSS 的话，也可以暂时自行解决。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
