### ISSUE TITLE
印象笔记保存失败

### ISSUE THREAD

**Issue by calaquendiv** [Kenshin/simpread#178]
http://36kr.com/p/5107596.html?ktm_source=feed

主题 绀鼠 仅自定义过中文字体
`"Source Han Serif", STSong,  serif;`

**Comment by Kenshin** [comment]
你好，感谢反馈~

印象笔记有可能会导致保存失败，这个 url 失败的原因

```
Attribute "_src" must be declared for element type "a".
```

并不是由 `自定义样式` 造成的，这部分的原因请参考 [这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊

**Comment by calaquendiv** [comment]
Great 👍👍👍

Kenshin Wang <notifications@github.com> 于2018年9月1日周六 上午11:18写道：
