### ISSUE TITLE
简悦标记图片导出notion失败

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#1786]
标记方式，鼠标悬浮图片上面，点击黄色标注按钮，右边成功展示标注成功，但是导出notion失败
网址：https://www.zhihu.com/market/albums/1161598331242954752/manuscript/1161600009958576128
![image](https://user-images.githubusercontent.com/15308878/106453768-c0720e80-64c4-11eb-8399-78298240eecb.png)
![image](https://user-images.githubusercontent.com/15308878/106453900-f1524380-64c4-11eb-9623-1930319800a8.png)

**Comment by Kenshin** [comment]
你试试在这种情况下，导出 markdown 到本地，看看是否有问题？或者再多测试几次。

导入到 Notion 使用了私有 API

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
