### ISSUE TITLE
使用简悦优化网页小说时只呈现了正文内容而忽略了诸如“下一章”“章节目录”等功能要素。

### ISSUE THREAD

**Issue by yesun123** [Kenshin/simpread#1787]
RT

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。
不过，小说的话，有更好的方案，是个油猴脚本，具体名字请翻翻 issues 这里其它人的留言。

***

当然，简悦支持翻页功能，但需要手动适配。

最后，我关闭此 issues 了。 😀
