### ISSUE TITLE
希望简悦能够支持企业版的onenote

### ISSUE THREAD

**Issue by Elliont** [Kenshin/simpread#1788]
搜索之前的issue，至少在19年就已经有这方面的需求了，希望简悦可以早日把这个功能提上日程，谢谢！

**Comment by Kenshin** [comment]
嗨，已经支持了，下个版本发布，到时候我会这里通知你~

**Comment by Elliont** [comment]
> 嗨，已经支持了，下个版本发布，到时候我会这里通知你~

期待新版本，感谢！

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

**Comment by enron2014** [comment]
请问怎么操作 让其支持企业版的onenote？

**Comment by Kenshin** [comment]
@enron2014 

正常授权就应该可以了。
