### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by quericy** [Kenshin/simpread#179]
Url:[http://www.jianshu.com/p/c0b8b3f921a9](http://www.jianshu.com/p/c0b8b3f921a9)

![image](https://user-images.githubusercontent.com/9134027/34104587-09594856-e42c-11e7-96f4-af481444cab1.png)

Console:
![image](https://user-images.githubusercontent.com/9134027/34104545-d7718006-e42b-11e7-9c0a-1281feffb474.png)

**Comment by 23784148** [comment]
感谢反馈，简书由于改变了结构，所以出现了这个情况，之前已经有用户反馈了，这个问题只能下个版本解决。（本月低发布）

**Comment by Kenshin** [comment]
`1.1.0` 已发布，发布内容 [请看这里](http://ksria.com/simpread/changelog.html#1.1.0)
并修改了这个问题，请通过 请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增/修改) ，此 issues 将关闭。
