### ISSUE TITLE
pixiv 作品页

### ISSUE THREAD

**Issue by xfrqh** [Kenshin/simpread#1790]
发生问题的地址: https://www.pixiv.net/artworks/75097703

点击“查看全部”才让简悦显示所有图片

我调节过“版面宽度”，现在图片会发生不等比变形

**Comment by Kenshin** [comment]
嗨，简悦只有在 有大量文字的页面下才能使用，这是 **阅读模式** 的基础和前提。
虽然简悦的识别比较不错，能识别出各种奇怪的页面，但如果失去这个前提则一点意义都没有。 😀
