### ISSUE TITLE
阅读模式下看不到帮助按钮，稍后阅读界面也完全看不到

### ISSUE THREAD

**Issue by guxianbang** [Kenshin/simpread#1791]
可以弄个问号/?/或者help之类的，不然作为新手很迷茫。
我是用了两三天简悦之后，不小心在稍后阅读界面按下Ecs才发现简悦也支持快捷键的。

**Comment by Kenshin** [comment]
谢谢反馈，确实是疏忽了，会考虑你的建议~ 🙏

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
