### ISSUE TITLE
非同时在线的情况下，是否可以授权超过三台设备？

### ISSUE THREAD

**Issue by jaren-gu** [Kenshin/simpread#1795]
在发起 issue 之前已经看了其它的 issue 换了几个关键字也没找到跟我这种情况类似的。只好发一个了。

情况是这样的，目前我一共授权了三台设备

- 宿舍一台台式
- 宿舍一台笔记本
- 公司一台电脑

然后现在过年回家了，但是没有带上电脑，回去之前也没有取消其他设备的授权，但是我的配置文件通过云盘同步了。

请问这种情况下，我还可以使用配置文件在家里登录上高级账户吗？会不会导致账户被锁定？

感觉这个问题不应该只有我遇到才对，比如说离职，但忘了退出公司电脑的授权，那岂不是永远的少了一个可以授权的设备了吗？

**Comment by Kenshin** [comment]
嗨，被锁定只有一个原因：

> 非同一台设备同时使用 **高级账户** 功能。

***

> 你说的情况，应该无法授权使用。

当已授权三台设备的话，是无法授权第四台设备的。

***

简悦有一套自己的算法，所以有可能可以授权成功，但会被锁，根据你说的情况，你可以按照下面的方式，看看自己账户有几台设备在使用

***

如果发生被锁定的话，也没问题，登录  https://simpread.pro/account 即可解锁，细节可以看 https://github.com/Kenshin/simpread/discussions/1569

**Comment by jaren-gu** [comment]
已经查询了，确实有三台，昨晚也作死登录了一下被锁定了。

这个场景下无解吗？我现在也用不上高级功能，就是希望假期期间的阅读标注可以同步，不然放假回去还得做一次整合。虽说再读一次也是好事（逃

如果无解的话，可以直接关掉 issue 了。

**Comment by Kenshin** [comment]
如果你不用高级账户的话，则没有这个限制。
标注的基础功能是没有使用设备数的限制。

同步的话，看你是通过何种方式同步了？

- 手动同步是基础账户功能，自然没有限制。
- 使用同步助手的话，则需要高级账户功能。

你可以踢掉全部的设备，然后用现在的设备成为高级账户，等你的假期结束，也基本上过了期限，在回去前退出当前账户就行了。（或者即便是忘记退出的话，回公司也再来一遍就行了。

**Comment by jaren-gu** [comment]
nice  

#1569 这个 issue 完美的解答了我的疑惑，谢谢。

**Comment by Kenshin** [comment]
搞定就好，我把这个 Issues 也放到了 #1569 希望让更多的用户「收益」。

😄
