### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by corgile** [Kenshin/simpread#1799]
- 操作系统 win 10

- 浏览器版本 **88.0.4324.104 (Official Build) (64-bit) (cohort: Stable)**

- 简悦版本 **2.0.0**

- 发生问题的地址 https://www.geeksforgeeks.org/maximum-length-chain-of-pairs-dp-20/

代码高亮失败，另外对tab的解析希望优化成tab样式

> 代码高亮问题。😀

**截图**
![image](https://user-images.githubusercontent.com/48396880/106997911-abe08f80-67be-11eb-9286-bb113e65acd4.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
