### ISSUE TITLE
求适配[哔哩哔哩专栏]

### ISSUE THREAD

**Issue by zhihaofans** [Kenshin/simpread#180]
地址:https://www.bilibili.com/read/home

**Comment by 23784148** [comment]
没问题，不过可以用临时阅读模式解决，适配后，我会通知你。

**Comment by zhihaofans** [comment]
@Kenshin 你好，请问哔哩哔哩专栏是已经适配了吗？我打开哔哩哔哩专栏自动进入阅读模式了，但有个不是百分百触发的BUG，图片没载入完毕就进入阅读模式的话会出现有的图片看不到(只有个方框)，得退出阅读模式再手动进入一次才行。当浏览器已经缓存过图片时好像不会出现这个情况。

**Comment by Kenshin** [comment]
的确适配了，只是没有通知，因为想跟 1.1.0 发布时一起通知。
不过，简悦有定期自动导入新适配列表的功能，所以才有了这种情况。
我没有遇到你说的情况，不过的确有这种情况存在，请在测试几个 url  😀 

![image](https://user-images.githubusercontent.com/81074/34372621-0445a1a2-eb11-11e7-8df3-8868b2d88627.png)

上图是清除缓存后进入的效果~

**Comment by Kenshin** [comment]
`1.1.0` 已发布，发布内容 [请看这里](http://ksria.com/simpread/changelog.html#1.1.0)

如仍有问题的话，请重新 打开此 issues  😀
