### ISSUE TITLE
部分网页生成阅读模式时，会发生代码段错位

### ISSUE THREAD

**Issue by ChloroplastYu** [Kenshin/simpread#1802]
- 操作系统 **MacOS 11.2**

- 浏览器版本 **Chrome 88.0.4324.146**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://draveness.me/golang/docs/part1-prerequisite/ch02-compile/golang-compile-intro/>

原网页：
![image](https://user-images.githubusercontent.com/51773819/107019280-7185eb00-67dc-11eb-8aad-91144ad78313.png)

阅读模式：
![image](https://user-images.githubusercontent.com/51773819/107019332-7ea2da00-67dc-11eb-8821-a4c45e46ef3d.png)
**此处缺失了一个代码块，并且会导致后面所有的代码块位置全部混乱**

原网页：
![image](https://user-images.githubusercontent.com/51773819/107019506-b6aa1d00-67dc-11eb-83a3-7dbbc3f8215c.png)

阅读模式：
![image](https://user-images.githubusercontent.com/51773819/107019574-ccb7dd80-67dc-11eb-8107-a158ce9e59e3.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
