### ISSUE TITLE
2.0用户配置文件登录简悦2.1失败

### ISSUE THREAD

**Issue by ouligei6666** [Kenshin/simpread#1803]
卸载重新安装chrome之后， 简悦的配置并不保留， 用之前保存的json配置文件也无法登录， 之后使用找回uid重新登录，
之前的配置文件是在2.0的时候就保存的，2.1不兼容吗？请问之后每次更新小版本都要再存一次配置文件吗？

**Comment by Kenshin** [comment]
嗨，你有几个误区，解答下：

> 请问之后每次更新小版本都要再存一次配置文件吗？

简悦并不是小版本更新，只是小版本号更新，你可以看看 2.0 与 2.1 的区别就知道，基本上是大版本更新。（ 因为我不喜欢玩数字游戏，也就是说，2.1 其实是 3，玩数字游戏是从 Chrome 与 Firefox 的竞争之初开始被「节奏带坏」的...

> 再存一次配置文件

你没有同步设备的需求吗？也就是说，仅在一台设备上使用简悦？

简悦不收集用户的数据，但用户可以通过 坚果云/ Dropbox /  同步助手 来保存你的数据，所以如果你没有保存的话，没了就是没了。

> 不兼容问题

你可以在 2.1 **上传** 2.0 的配置文件，自然会升级到 2.1 版本的配置文件。

> 用之前保存的json配置文件也无法登录

没理解你的意思，如果 UID 正确的话，不存在无法授权的情况。（你可以说下你的操作步骤

> 关于版本的问题

建议保持最新的版本，2.1 是 11月份升级的，你到现在还未升级吗？

**Comment by ouligei6666** [comment]
我没描述清楚, 
很早之前, 我在2.0时期保存了配置文件, 之后就没在2.1版本更新的时候保存新配置文件,  11月份插件也肯定是自动更新到了2.1,  前几天卸载chrome重装了一下(同一台电脑),  用2.0的配置文件死活没法登陆,  总之, 最后通过找回uid成功登陆了,.
既然2.0的配置文件没问题,  我就是没明白2.0的配置文件为什么就是登陆不了....

**Comment by Kenshin** [comment]
@ouligei6666 

> 用2.0的配置文件没法登陆

因为简悦的操作比较灵活，有多种登录（授权）方案，所以方便的话，请描述登录（授权）的步骤。

**Comment by ouligei6666** [comment]
本地保存的配置文件上传登陆

**Comment by Kenshin** [comment]
> 本地保存的配置文件上传登陆

okay，等 QA 阶段我做个测试，到时候会在这里通知你，谢谢反馈。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
