### ISSUE TITLE
恢复高级账户显示后台异常恢复失败

### ISSUE THREAD

**Issue by Rayan-tree** [Kenshin/simpread#1805]
恢复高级账户显示后台异常恢复失败
不是第一次使用，因为最近同步助手不能导出pdf，会显示未运行，所以重置了同步助手一下，结果发现不能和扩展端绑定了。再绑定会显示未运行同步助手，但是同步助手一直是在后台的。然后又去把扩展端重置了，点击恢复高级账户就显示后台异常恢复失败，配置文件还留有。
还有就是有时打开会显示这个
<img width="513" alt="2021-02-05 (7)" src="https://user-images.githubusercontent.com/78608893/107057760-bfb3e200-680e-11eb-8061-4dd30d453f9a.png">

**Comment by Kenshin** [comment]
> 截图的问题

这是 7026 端口被占用的提示，所以确保你的端口没有被占用，重启系统后运行同步助手，看看是否可以运行。

> 点击恢复高级账户就显示后台异常恢复失败

估计是 https://github.com/Kenshin/simpread/discussions/1567 造成的

**Comment by Rayan-tree** [comment]
不好意思，这边看不到图片，能麻烦发一下吗
![image](https://user-images.githubusercontent.com/78608893/107107854-b35f7180-686e-11eb-8e30-077b52ad69d2.png)

**Comment by Rayan-tree** [comment]
不好意思，这边看不到#1567所显示的图片，如果可以的话能麻烦发一下图片吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 中午11:19
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"3446025150"<3446025150@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 恢复高级账户显示后台异常恢复失败 (#1805)





  
截图的问题
  
这是 7026 端口被占用的提示，所以确保你的端口没有被占用，重启系统后运行同步助手，看看是否可以运行。
  
点击恢复高级账户就显示后台异常恢复失败
  
估计是 #1567 造成的

**Comment by Rayan-tree** [comment]
不用了，已经解决了，非常感谢

**Comment by Kenshin** [comment]
@Rayan-tree 

搞定就好，如何解决的能描述下？（以供后人参考~  😂

**Comment by Rayan-tree** [comment]
因为看不到提供的图片，根据提供的地址点进去以后发现是简悦的管理扩展程序界面😂，然后里面也没几个可以更改的地方，就试着把允许访问文件网址勾上，又勾了一个有权在所有网址上访问，接着再去试着恢复高级账户，这回就成功了，然后同步助手也接着绑定成功

**Comment by Kenshin** [comment]
@Rayan-tree 

这个图就是你操作的「步骤」。 😂
