### ISSUE TITLE
简阅助手无法开机启动（附解决方案）

### ISSUE THREAD

**Issue by libiingzhi** [Kenshin/simpread#1807]
RT

**Comment by Kenshin** [comment]
是的，下个版本修复这个问题。

***

`.exe` `.app` 其实是个自解压的程序，所以会有此问题。

**Comment by ttimasdf** [comment]
在文件管理器的路径栏或 Win-R 运行窗口中，输入 `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` 并转到这个文件夹，将同步助手程序按住右键拖过去，在这个文件夹中创建快捷方式即可。

**Comment by Kenshin** [comment]
@ttimasdf 

嗨，谢谢提供解决方案，已将内容整理到 https://github.com/Kenshin/simpread/discussions/2011 这里~

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 自启动

修复了 Windows 、Mac 版无法自启动的问题，如仍无法自启动，Windows 用户 [看这里](https://github.com/Kenshin/simpread/discussions/2011)。

Linux 环境因为比较特殊，仅能 [使用此方式](https://github.com/Kenshin/simpread/discussions/3957) 实现。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
