### ISSUE TITLE
希望保存到 notion 时，可以增加原文链接

### ISSUE THREAD

**Issue by ipez** [Kenshin/simpread#1809]
就像保存到印象笔记一样，有一个 ”原文地址：xx“

**Comment by Kenshin** [comment]
如果保存到 Notion database 的话，是有链接的，可以看看这篇内容 http://ksria.com/simpread/docs/#/Notion

**Comment by ipez** [comment]
好的，谢谢回复。不过要是能在页面正文也保存就更好了。

**Comment by Aaloone** [comment]
那你这个介绍说的就不清楚，你应该是 导出到 **Notion  database** 支持 支持源网址 注意：需要 1.1.4.6022 版本（以上）才可支持

**Comment by Kenshin** [comment]
@Aaloone 

已改。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
