### ISSUE TITLE
博客园印象笔记保存

### ISSUE THREAD

**Issue by Aaloone** [Kenshin/simpread#181]
在博客园使用分享到印象笔记总是失败，会是什么原因呢？

**Comment by Kenshin** [comment]
印象笔记有可能会导致保存失败，这部分的原因请参考 [这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

由于博客园这类 UGC 的页面会导致 html 比较乱，所以发送保存失败的机率非常高。 😟

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
