### ISSUE TITLE
双击键盘dd会自自动添加当前页面到稍后读，如何修改？

### ISSUE THREAD

**Issue by Jzhnakui** [Kenshin/simpread#1812]
由于视频加速的快捷键都是dd，但是我点dd之后，就会把当前页面添加到稍后读中，快捷键发生冲突

![image](https://user-images.githubusercontent.com/49728819/107136729-dc503700-6940-11eb-9023-90ee574ba808.png)

但是谷歌浏览器中的简悦快捷键设置后，这个dd添加到稍后读，一直存在，也找不到怎么更改。

或者有人能安利一个自定义快捷键的video speed插件吗？

**Comment by Kenshin** [comment]
嗨，你可以在 选项页 → 高级设定 → 稍后读 里面更改它。

PS：我已经在 TG 回复你了，所以我先关闭此 Issues 了，有需要的话，请随时重开它。
