### ISSUE TITLE
每次进入阅读模式时因为标签栏与阅读内容风格不统一的问题，导致阅读时注意力不集中

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#1824]
每次进入阅读模式时因为标签栏与阅读内容风格不统一的问题，导致阅读时注意力不集中
需要在按下让浏览器全屏，但是这样不免有些麻烦了
能不能在按下aa时既进入阅读模式也网页全屏

_Originally posted by @210000ling in https://github.com/Kenshin/simpread/discussions/1822_

**Comment by Kenshin** [comment]
@210000ling

你可以隐藏右下角

![image](https://user-images.githubusercontent.com/81074/107348413-ed947180-6b01-11eb-9f1d-e2d2c75385e3.png)

进入阅读模式，可以手动全屏（或快捷键）

**Comment by Kenshin** [comment]
另外，我把 https://github.com/Kenshin/simpread/discussions/1822 帮你新建了一个 Issues  

https://github.com/Kenshin/simpread/discussions/ 是讨论区，，而非 **求助 / QA**  😀 

所以，我删除 Discussions 的内容了。

**Comment by Kenshin** [comment]
@210000ling

另外，我把 https://github.com/Kenshin/simpread/discussions/1822 帮你新建了一个 Issues  

https://github.com/Kenshin/simpread/discussions/ 是讨论区，而非 **求助 / QA**  😀 

所以，我删除 Discussions 的内容了。

**Comment by 210000ling** [comment]
> 每次进入阅读模式时因为标签栏与阅读内容风格不统一的问题，导致阅读时关注不集中
> 需要在点击让浏览器全屏，但是这样不免有些麻烦了
> 能不能在点击aa时既进入阅读模式也网页全屏
> 
> _最初由@ 210000ling发表于[＃1822](https://github.com/Kenshin/simpread/discussions/1822)_



> @ 210000ling
> 
> 你可以隐藏右下角
> 
> ![图片](https://user-images.githubusercontent.com/81074/107348413-ed947180-6b01-11eb-9f1d-e2d2c75385e3.png)
> 
> 进入阅读模式，可以手动全屏（或快捷键）

我的意思是能不能在进入阅读模式时加入按f11的功能，因为用aa呼出阅读模式又fn加f11未免太过于繁琐了吧。

**Comment by Kenshin** [comment]
抱歉，我不觉得你提到的需求属于大众需求。

**Comment by Kenshin** [comment]
@ 210000ling
抱歉，我不觉得你提到的需求属于大众需求。
