### ISSUE TITLE
导出PDF出现出错，存在PDF文件，但文件内容空白仅有报错

### ISSUE THREAD

**Issue by Paustudent** [Kenshin/simpread#1826]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本 Chrome 88.0.4324.150

- 简悦版本 2.0.0

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
导出PDF文件只出现一个空白的PDF文件，文件内容为：Error: ENOENT: no such file or directory, stat '/Users/ywb/Desktop/OneDrive/简悦备份/output/tmp-Does Your Tummy Hurt After Eating Onions An

![](https://zuibang-1257431557.cos.ap-guangzhou.myqcloud.com/20210210192939.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
估计是标题含有特殊字符造成的，看看这个的解决方案 https://github.com/Kenshin/simpread/discussions/1617

或者找一个相对正常的页面，如少数派的页面再试试 https://sspai.com/post/39491

**Comment by paul18755** [comment]
尝试后其他页面正常，可能这个是个例。多谢您的帮助

**Comment by paul18755** [comment]
> 估计是标题含有特殊字符造成的，看看这个的解决方案 #1617
> 
> 或者找一个相对正常的页面，如少数派的页面再试试 https://sspai.com/post/39491

尝试后其他页面正常，可能这是个例，多谢帮助！

**Comment by Kenshin** [comment]
搞定就好，建议可把出错的 URL 给我看看。 😉

**Comment by paul18755** [comment]
https://soyummy.com/tummy-hurt-eating-onions-garlic-why/
您好，这是当时的文章链接
感谢您在春节期间还帮助解决问题
祝您新春快乐!!

发自我的iPhone

**Comment by Kenshin** [comment]
哈哈，没事，我都是利用碎片时间来处理这些事情，等确认后再回复你。

😄

**Comment by Kenshin** [comment]
嗨，我测试了下，应该可以正常导出，你可以看看这个 PDF

[Does Your Tummy Hurt After Eating Onions And Garlic？ This Is Why.pdf](https://github.com/Kenshin/simpread/files/5975155/Does.Your.Tummy.Hurt.After.Eating.Onions.And.Garlic.This.Is.Why.pdf)

你可以有时间试试是否成功导出了，另外竟然是个个例的话，我先关闭此 Issues 了。

PS：假期快乐~
