### ISSUE TITLE
无法保存到pocket

### ISSUE THREAD

**Issue by Joel2561** [Kenshin/simpread#1829]
- 操作系统 **Win64**

- 浏览器版本 **Chrome 89.0.4389.40（正式版本）beta （64 位）/ Edge88.0.705.63 (官方内部版本) (64 位)**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/162296774>

**无法将网页保存到pocket阅读**

**截图**

![image](https://user-images.githubusercontent.com/77143461/107592857-fcd20700-6c48-11eb-9140-58e127a2df8d.png)
![Error](https://user-images.githubusercontent.com/77143461/107592955-3acf2b00-6c49-11eb-9c30-71c71b95d851.gif)

**Comment by Kenshin** [comment]
谢谢反馈，因为 Chrome 版本升级导致的 CORS 问题，已修复了这个问题，下个版本发布。

**临时解决方案：**

> 把这个页面加入到稍后读，然后在稍后读导入到 Pocket 即可。

**Comment by Kenshin** [comment]
下个版本发布后，我会在这里通知你。

**Comment by lipeiyuan** [comment]
Edge遇到同样pocket保存失败的情况

另：稍后读里面好像没看到导入到pocket的选项？

**Comment by Kenshin** [comment]
@lipeiyuan 

无法保存稍后读的问题，下个版本解决了。

PS：稍后读确实缺少 Pocket 的选项... 同样，下个版本修复。

**Comment by MatrixA** [comment]
目前我在Chrome上仍然无法保存到Pocket

**Comment by Kenshin** [comment]
@MatrixA

抱歉，这是个 Bug，已修复了，下个版本发布后就可以了。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
