### ISSUE TITLE
适配不正常

### ISSUE THREAD

**Issue by ImSingee** [Kenshin/simpread#183]
http://www.solidot.org/story?sid=32542

**Comment by Kenshin** [comment]
感谢反馈~
你可以将 `标题` 的内容改为 `<title>` 即可解决。

官方适配源需要等 `1.1.0` 发布时一并更新。

**Comment by Kenshin** [comment]
`1.1.0` 已发布，并修改了这个问题，请通过 请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增/修改) ，此 issues 将关闭。
