### ISSUE TITLE
博客园代码字体显示异常

### ISSUE THREAD

**Issue by guodong2005** [Kenshin/simpread#1834]
![image](https://user-images.githubusercontent.com/45134816/107852057-586ae300-6e49-11eb-8bbe-7923ccda54a1.png)

https://www.cnblogs.com/RabbitHu/p/BZOJ3864.html

**Comment by Kenshin** [comment]
谢谢反馈，你可以这样做，通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决，加入以下代码：

```
sr-rd-content pre {
    font-size: 12px!important;
}
```

其中的 `12` 改成你认为适合的值就好。
