### ISSUE TITLE
能不能在标注栏也使用富文本模式？

### ISSUE THREAD

**Issue by guodong2005** [Kenshin/simpread#1836]
![image](https://user-images.githubusercontent.com/45134816/107869852-acb7a680-6ecd-11eb-9f92-51823cb47c13.png)

这样就美观、直观多了

**Comment by Kenshin** [comment]
嗨，谢谢建议，标注栏可视面积比较小，不太适合做这些事情，你可以点击对应的标注会自动跳到相应的正文位置上。

所以我关闭此 Issues 了~

🙏
