### ISSUE TITLE
希望导出Notion提供附加Tag的选项

### ISSUE THREAD

**Issue by hxu38691** [Kenshin/simpread#1837]
个人使用中会把所有位置的highlight都放到一个highlight collection中，然后添加Tags，但是目前没有办法从简悦highlight中提取Tags。所以希望可以提供附加tag的选项可以在导出到notion中添加颜色，或者在尾部添加 #tag 感觉都行，然后用户可以自己用notion-api提取、加入到collection

**Comment by Kenshin** [comment]
谢谢建议，我也想要此功能...（一个重度 Notion 用户的心声）...

但 Notion 没有 API，等出了后我会最快加入此功能。

 😅   😂

**Comment by KiLien** [comment]
Save to Notion 插件倒是有提供 tag 的选项，不过有时候没法获取页面内容；
看了下官方提供的 API 只有一些 beta 功能，难以支撑开发。。
作者大大用的私有库是指 notion-py 吗？

**Comment by Kenshin** [comment]
@KiLien 

简悦没有使用第三方的 Notion 私有库，纯自己手写解析  😅 

其实，我一直在等 Notion 官方 API 但... 约等于白等。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
