### ISSUE TITLE
稍后读里 无法导出离线的html文件

### ISSUE THREAD

**Issue by Forrest-Zhangchn** [Kenshin/simpread#1838]

**Comment by Forrest-Zhangchn** [comment]
你好，简悦做的非常好，有一个问题想要咨询一下：
我把网页文章收藏到稍后读里，在稍后读里打开阅读模式进行批注阅读，做完阅读笔记后好像无法导出离线的html文件，烦请问一下可能是什么问题呢？具体报错如图片所示。
![Snipaste_2021-02-14_22-28-20](https://user-images.githubusercontent.com/43512142/107879552-781b0d80-6f14-11eb-9bb0-dd6ac4bfc9d0.png)

**Comment by Kenshin** [comment]
谢谢反馈，有可能是标题含有特殊字符造成的，解决方案 https://github.com/Kenshin/simpread/discussions/1617

> 但如果你直接通过 **右键方式加入稍后读** 的话，可能会绕过插件同样也会导致这个问题。

下个版本已经解决了这个问题，目前提供两种临时解决方案：

- 首先安装链接提到的插件，然后进入阅读模式后 → 加入稍后读
- 在稍后读修改标题，去掉一些特殊符号，尽量只保留中英文名称

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
