### ISSUE TITLE
求适配为知笔记

### ISSUE THREAD

**Issue by m1509001** [Kenshin/simpread#184]
求适配为知笔记！求适配为知笔记！求适配为知笔记！

**Comment by Kenshin** [comment]
😄 看来很迫切啊，问题我没有 `为知笔记` 的账户，不清楚它的页面结构是什么？能给个 url ？
或者等 1.1.0 发布后自己添加。（ 1.1.0 有添加新站的功能）

**Comment by Zeroto521** [comment]
**wiznote**支持markdown语法，
扩展下**simpread**的**md**的功能就行了。

**Comment by Kenshin** [comment]
@Zeroto521 

简悦只支持 `通过 url 匹配` `主动适配` `TXT 阅读器` 三种方式，无论哪种方式都是需要知道 `为知笔记` 的页面结果。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) 的功能，希望喜欢~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
