### ISSUE TITLE
导出为PDF文件功能为什么没有了？

### ISSUE THREAD

**Issue by libiingzhi** [Kenshin/simpread#1842]
简悦：
新春快乐！
有个小问题咨询一下：
前几天还可以使用简悦将网页导出为PDF文件，昨天发现这个功能没有了。提示“此功能为实验性功能”，何时可以正常使用？

谨祝新春快乐！

**Comment by Kenshin** [comment]
嗨，春节快乐。

这应该是个 Bug 可以解决的，细节看 https://github.com/Kenshin/simpread/discussions/1617 或 https://github.com/Kenshin/simpread/issues/1838#issuecomment-778910881 给出的方案

**Comment by libiingzhi** [comment]
果然解决。
非常感谢。
祝好！

Kenshin Wang <notifications@github.com> 于2021年2月15日周一 下午2:20写道：

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭此 Issues 了，新版发布后自然会解决提到的问题。
