### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by lmaple0** [Kenshin/simpread#1847]
发生问题的地址: <https://cn.bing.com/images/search?q=imgurl:https%3a%2f%2fshitu-query-bj.bj.bcebos.com%2f2021-02-17%2f15%2fc8619352b7302754%3fauthorization%3dbce-auth-v1%252F7e22d8caf5af46cc9310f1e3021709f3%252F2021-02-17T07%253A40%253A16Z%252F300%252Fhost%252Facf34d0669f4d965c8dd1bfcc135e8627fa58ec0e05a72f932ed1e599f25b15f

**Comment by Kenshin** [comment]
抱歉，你提供的 URL 有误，如果是 bing.com 搜索页面的话，是不需要使用阅读模式的。
