### ISSUE TITLE
这个插件本身比网页上的广告更令人分心。

### ISSUE THREAD

**Issue by szzhiyang** [Kenshin/simpread#185]
**因为它的设置项太繁琐，令人无所适从。**

既然这个插件都叫 **“简”** 了，那么你就应该简化它的设置项，直接将它最完美的一面展现给大家，而不是什么都让大家自己手动配置。

你的 **“简 Tab”** 也存在同样的问题，两款插件的设置项风格与 **“简”** 字完全相悖。

请看看这个插件是怎么做的：

https://www.newfido.com/readerview/

**但是我仍然对你充满着敬佩之情。**

**请你勿忘初心，继续做你想做的事情，我们仍然会支持你。**

**加油！**

**Comment by Kenshin** [comment]
不做任何设置就可以使用（开箱即用）简悦，设置项只是为了满足不同人的定制化（差异化）需求。

就如 Google 一样，你可以直接搜索也可以做细致深入的定制化搜索。

简 Tab 亦然！

虽然我不同意你的观点，但会捍卫你说话的权利！ 😃

**Comment by Kenshin** [comment]
我将关闭此 issues，如有疑问的话，请重新开启。  😃

**Comment by szzhiyang** [comment]
请等一下啊，我想回复你。😀
