### ISSUE TITLE
标注框错行问题

### ISSUE THREAD

**Issue by cyb9009** [Kenshin/simpread#1853]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows10**

- 浏览器版本 **Microsoft Edge  88.0.705.68 **

- 简悦版本 **2.0.0**

**请描述你的问题**

> 相邻的两行句子需要分开标注时，下行的标注框位于上行句子上，光标移动到标注框时速度稍慢会替换成修改上行标注的标注框（我使用触摸板）。希望在有相邻标注的情况时能将下行的标注框显示在句子下面，或者降低灵敏度。

**截图**

> 
![捕获](https://user-images.githubusercontent.com/79251712/108334147-9cc0ff00-720c-11eb-8a7a-5b23a0d7a48c.PNG)

**Comment by Kenshin** [comment]
谢谢反馈，下个版本修复，你可以暂时使用 https://github.com/Kenshin/simpread/discussions/1653 给出的解决方案。

下个版本修复后我会在这里通知你。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
