### ISSUE TITLE
低版本通过第三方授权登录到高版本时无法成功授权

### ISSUE THREAD

**Issue by xlx0406ll** [Kenshin/simpread#1855]
使用坚果云账号进行授权登录一直显示授权失败，账号和密码并没有输入错误

**Comment by Kenshin** [comment]
猜测是这个问题 https://github.com/Kenshin/simpread/discussions/1567 （里面有解决方案

**Comment by xlx0406ll** [comment]
![屏幕截图 2021-02-19 142345](https://user-images.githubusercontent.com/66156446/108466224-43190d00-72be-11eb-97c2-96b005eac36a.png)
![屏幕截图 2021-02-19 142425](https://user-images.githubusercontent.com/66156446/108466232-457b6700-72be-11eb-91c2-aa178c3a773d.png)
再重新安装扩展后还是不能进行授权登录。

**Comment by Kenshin** [comment]
> 使用坚果云账号进行授权登录一直显示授权失败，账号和密码并没有输入错误

emmm... 因为你没有详细说明，所以我没办法判断，下面是个提示：

使用 **坚果云账号进行授权登录** 的前提：你已经 **[授权了坚果云作为简悦的第三方登录](http://ksria.com/simpread/docs/#/%E6%8E%88%E6%9D%83%E7%99%BB%E5%BD%95?id=%e5%85%88%e5%86%b3%e6%9d%a1%e4%bb%b6)** 方式。

**Comment by XYZ-misaka** [comment]
<img width="557" alt="屏幕快照 2021-02-22 10 39 22 PM" src="https://user-images.githubusercontent.com/62983717/108723190-f2740f00-755e-11eb-8e7f-d04b46377bf0.png">
是JavaScript不能在Chrome中使用的问题，希望尽快修复

**Comment by XYZ-misaka** [comment]
我也是坚果云，Chrome 
Google Chrome 已是最新版本
版本 88.0.4324.182（正式版本） (x86_64)

**Comment by Kenshin** [comment]
@XYZ-misaka 

> 是JavaScript不能在Chrome中使用的问题，希望尽快修复

并不是你说的问题引起的（如果你懂点前端的话，就知道这些错误跟你现象无关。

***

这个问题目前除了你们外没有其它用户反馈过，我之前也做过测试，是没问题的。

***

我猜测有可能是版本不一致造成的，使用这个功能（第三方授权）的前提：

1. Chrome 的简悦版本为 2.1
2. 坚果云的配置文件版本也为 2.1

***

所以，你们可以做个如下的测试：

1. 将坚果云的配置文件下载到本地
2. 选项页 → 共通 → 导入配置文件的方式将上步的文件导入
3. 看是否有 **导入文件比较旧，已自动升级为高版本** 之类的提示。
4. （接第二步）导入后，通过选项页 → 右上角 → 仅授权当前设备 的方式登录 **高级账户**。

***

简悦支持多种方式升级为高级账户，简单的说，只要有配置文件的话，就没有任何问题。

**Comment by XYZ-misaka** [comment]
😯，😓，是的，重新同步后可以登录了。

**Comment by xlx0406ll** [comment]
十分感谢

**Comment by Kenshin** [comment]
@XYZ-misaka @xlx0406ll 

搞定就好，确认是 **低版本的问题** 吗？如果是的话，下个版本会修复这个缺陷。

**Comment by XYZ-misaka** [comment]
是的



---原始邮件---
发件人: "Kenshin Wang"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 下午2:44
收件人: "Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送: "XYZ-misaka"<1070372208@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [Kenshin/simpread] 第三方登录授权失败 (#1855)




 
@XYZ-misaka @xlx0406ll
 
搞定就好，确认是 低版本的问题 吗？如果是的话，下个版本会修复这个缺陷。

**Comment by xlx0406ll** [comment]
对的

**Comment by Kenshin** [comment]
okay 谢谢反馈，我先记 Bug

下个版本修复此问题。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
