### ISSUE TITLE
印象笔记授权失败（服务器 503 错误）

### ISSUE THREAD

**Issue by AmintaCCCP** [Kenshin/simpread#1861]
同步不了文章，就试着重新授权，发现接口503了
<img width="696" alt="WX20210220-111559@2x" src="https://user-images.githubusercontent.com/74942183/108582276-1f60d000-736d-11eb-82d0-a2244f0e3c87.png">

**Comment by Kenshin** [comment]
嗨，明天确认下，谢谢提示。

**Comment by Kenshin** [comment]
嗨，这个问题已经解决了，你可以重新试试，没问题的话，请关闭此 Issues ~

**Comment by AmintaCCCP** [comment]
> 嗨，这个问题已经解决了，你可以重新试试，没问题的话，请关闭此 Issues ~

已经修复，谢谢
