### ISSUE TITLE
nike.com 无法有效识别图片分割后的页面

### ISSUE THREAD

**Issue by Fit-yourself** [Kenshin/simpread#1862]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://www.nike.com/cn/a/is-tenacity-born-or-made>

**请描述你的问题**

Nike 官网的博客站点，有图片进行分割，简悦插件无法识别，进入阅读模式仅仅摘取了首段。

**截图**
![image](https://user-images.githubusercontent.com/45476879/108584032-f0e8f200-7378-11eb-9fce-309535197d53.png)

![image](https://user-images.githubusercontent.com/45476879/108584024-e29ad600-7378-11eb-87b6-2f6543881840.png)

**Comment by Kenshin** [comment]
嗨，你可以用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE) 来临时解决，虽然这个站属于大众类的站点，但它似乎大多数页面都没有适配的必要。

**Comment by Fit-yourself** [comment]
> 嗨，你可以用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE) 来临时解决，虽然这个站属于大众类的站点，但它似乎大多数页面都没有适配的必要。

谢谢, 但是进行元素选取的时候，并不是那么顺利。
1. 白色框线 在进行想框选 垂直区域 的时候，消失不见
2. 一直手动扩大框选，后也不见。

那这种情况，能选择多个区域，后以标号汇总吗？

**Comment by Kenshin** [comment]
@Fit-yourself 

哈哈，需要一些技巧性（和运气），可能（算法）不是那么太准确造成的。

**Comment by Fit-yourself** [comment]
好的，哈哈哈。虽然只是想试下能不能适配，但也没有这么地强迫。

**Comment by Kenshin** [comment]
嗨，这是我通过重新高亮得到的结果（还是可以的，只是需要多锻炼锻炼 😄

![simpread-毅力是先天形成的还是后天训练的？- 耐克训练志 - 耐克 (Nike) 中国官网](https://user-images.githubusercontent.com/81074/108616626-ec403e80-7449-11eb-95cf-d5e963e6b537.png)
