### ISSUE TITLE
等宽字体过小

### ISSUE THREAD

**Issue by vCit2dmW** [Kenshin/simpread#1863]
**请说明发生问题的环境**

- 操作系统 **Linux x86_64**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://multipass.run/docs>

**请描述你的问题**

代码块的字体过小，比周围的正文字体小出非常多。

**截图**

![image](https://user-images.githubusercontent.com/22867565/108584954-42e14600-7380-11eb-9ac1-75891c241126.png)

**Comment by Kenshin** [comment]
嗨，解决方案：

1. 可以更换不同的主题
2. 通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决
