### ISSUE TITLE
回复 Kenshin 先生

### ISSUE THREAD

**Issue by szzhiyang** [Kenshin/simpread#187]
**看得出来，你想尽可能地让 SimpRead 满足所有人的需求，这令我十分感动，因为如此为用户着想的开发者真的不多。**

**其实，你可以换种思路来安排 SimpRead 的设置项啊。**

**你可以把几个关键的核心设置项彰显出来，把一些细节上的杂项设置以类似于注册表或者配置文件的形式提供给极客用户去修改。**

**这样，对于小白用户以及不希望在插件设置上折腾的用户来说，软件会非常简单易用；对于极客用户以及有强迫症的用户来说，软件能够最大化地满足他们的严苛需求。**

**你不妨参考一下 [Sumatra PDF](http://www.sumatrapdfreader.org) 的设置安排，它就是这么做的。**

**另外，除了 Windows 和 Sumatra PDF ，Mozilla Firefox 也是这么做的。**

**岂不美哉？**

**Comment by Kenshin** [comment]
感谢你的建议，正因为有你们这样的用户，才是我坚持下去的原因，简悦的财富！

从 1.0.0 开始一直到即将发布的 1.1.0 简悦在界面一直没有变化，唯一增加的是控制栏，这也是我之前所说的「不改初心」。

选项页的项目也是根据类别划分，如：全局、聚焦模式、阅读模式等等。

我会吸纳你的建议，如果你有具体的想法，也可以在这里分享！ 😊

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊

**Comment by szzhiyang** [comment]
Kenshin 先生您好，我另起炉灶，开了 [**issue 274**](https://github.com/Kenshin/simpread/issues/274) 来探讨设置界面的问题。 😄
