### ISSUE TITLE
MAC版同步助手设置不显示主界面后没有入口设置回来

### ISSUE THREAD

**Issue by Atomonkey** [Kenshin/simpread#1879]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS Catalina 10.15.7
- 浏览器版本 Edge 88.0

- 简悦版本 **2.1.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 安装简悦助手完成所有配置，功能都正常，但可能是因为在首页勾选了不显示主界面（或类似的文案）选型，现在启动助手应用后只有docker坞的图标，再也不出现配置界面了，请问如何唤回？

**Comment by Kenshin** [comment]
Mac 右上角有简悦的 icon → 右键即可，如下图

![image](https://user-images.githubusercontent.com/81074/108987162-ed819d80-76cd-11eb-9a3e-1226b65e14d5.png)

**Comment by Atomonkey** [comment]
好的，没注意顶部导航栏，之前搜文档没看到，建议可以加入到帮助文档。

**Comment by Kenshin** [comment]
搞定就好，会考虑的，谢谢提示。
