### ISSUE TITLE
期望“保存”功能能增加 “保存到有道云笔记”

### ISSUE THREAD

**Issue by zhisheng17** [Kenshin/simpread#188]
RT，关爱有道云笔记用户，哈哈

**Comment by Kenshin** [comment]
哈，有道是第一批就作为 API 的服务，但是有道的 Key 申请需要手动，申请后迟迟无法下来，所以到现在一直没有加上...  😂 
Instapaper 也是如此，只是后来它竟然通过了...  😱

**Comment by zhisheng17** [comment]
希望能早点申请通过

**Comment by hooklife** [comment]
同样期待，希望作者可以再尝试申请以下 @Kenshin

**Comment by Kenshin** [comment]
我准备再申请试试…

不过， 1.1.1 会上线一个新功能，可以临时生成一个页面，这样就能使用一些不变使用的功能了，如：有道云笔记。

**Comment by Kenshin** [comment]
最近在弄 iOS 版的简悦，所以， 1.1.1 一直在 delay ，预计下周发布，本周会发布 「iOS」 版。 😃

**Comment by gooppo** [comment]
请问能否增加以markdown的形式导出到有道云 == 目前我都是保存完markdown到本地然后拉到有道云里面 ==

**Comment by remotegithub** [comment]
麻烦大神了，我也是有道云用户，为了来这里提建议加入有道云笔记功能，我大半夜特地点进来注册的账户，祝你越做越好，真的很棒

**Comment by Kenshin** [comment]
@remotegithub 

谢谢对简悦的喜爱，接入后，我会在这里告诉大家。 🙏

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) 的功能，希望喜欢~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
