### ISSUE TITLE
聚焦模式快捷键输入框有问题，阅读模式和稍后读快捷键不管用

### ISSUE THREAD

**Issue by xsyzer** [Kenshin/simpread#1883]
**环境**：
- 操作系统  **Windows10**

- 浏览器版本 **Chrome  88.0.4324.182**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://sspai.com/post/61996>

**问题**

1.**聚焦模式**输入框输入字符和其他两个输入框（阅读模式和稍后读）不一样，两个字符之间没有间隔，而且会报错
2.阅读模式和稍后读输入框正常但是**快捷键不管用**
3.排除输入法的问题，中文输入法大小写都试过，美式键盘输入法大小写都试过，均不管用

**截图**

1.**聚焦模式**输入aa并没有间隔，输入什么都报错，保存之后都为空
![image](https://user-images.githubusercontent.com/53068487/109173815-3c5b3000-77bf-11eb-997f-84b4ce28589b.png)

2.作为对比，**阅读模式**输入aa，有间隔，，不报错，但是快捷键并不管用，页面无响应
![image](https://user-images.githubusercontent.com/53068487/109174218-99ef7c80-77bf-11eb-9bc5-9b326c4fe0b6.png)

**Comment by Kenshin** [comment]
谢谢反馈，但一般来说快捷键是没问题的，否则我自己就能发现。  😅 

***

> 聚焦模式输入aa并没有间隔，输入什么都报错，保存之后都为空

快捷键的设置显示逻辑或许有些不习惯，你可以一个按键一个按键的设置。（比如我刚才就测试了聚焦模式下的 `a
 a` 是正常。

> 作为对比，阅读模式输入aa，有间隔，不报错，但是快捷键并不管用，页面无响应

请在 **隐身模式下仅启用简悦** 试试，排除其它扩展造成的干扰。

***

另外，你也可以翻翻 Issues 里面似乎也有另外一个关于聚焦模式快捷键不好使的 issue 看看能否有所帮助。

还有，简悦也支持浏览器级别的快捷键，实在不行的话，也可以试试 [此方式](http://ksria.com/simpread/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by xsyzer** [comment]
> 谢谢反馈，但一般来说快捷键是没问题的，否则我自己就能发现。 😅
> 
> > 聚焦模式输入aa并没有间隔，输入什么都报错，保存之后都为空
> 
> 快捷键的设置显示逻辑或许有些不习惯，你可以一个按键一个按键的设置。（比如我刚才就测试了聚焦模式下的 `a a` 是正常。
> 
> > 作为对比，阅读模式输入aa，有间隔，不报错，但是快捷键并不管用，页面无响应
> 
> 请在 **隐身模式下仅启用简悦** 试试，排除其它扩展造成的干扰。
> 
> 另外，你也可以翻翻 Issues 里面似乎也有另外一个关于聚焦模式快捷键不好使的 issue 看看能否有所帮助。
> 
> 还有，简悦也支持浏览器级别的快捷键，实在不行的话，也可以试试 [此方式](http://ksria.com/simpread/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by xsyzer** [comment]
把配置重置之后就好了
