### ISSUE TITLE
在绑定joplin时,控制台发生错误

### ISSUE THREAD

**Issue by qiangtou** [Kenshin/simpread#1884]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

在绑定joplin时,控制台发生错误
版本:Joplin 1.7.11 (prod, win32)

修订: f560563d8 (master)
![image](https://user-images.githubusercontent.com/2376645/109174977-51848e80-77c0-11eb-9e1e-e58a6a8d0ce4.png)

**Comment by Kenshin** [comment]
嗨，这应该（大概率）是你设置的问题，你可以翻翻 Github Issues 已关闭的 issues 看看是否能得到帮助或者看看 https://github.com/Kenshin/simpread/discussions/1567 里面的解决方案。

**Comment by qiangtou** [comment]
> 嗨，这应该（大概率）是你设置的问题，你可以翻翻 Github Issues 已关闭的 issues 看看是否能得到帮助或者看看 #1567 里面的解决方案。

![image](https://user-images.githubusercontent.com/2376645/109374654-d4f1cd00-78f1-11eb-900d-a86c15968a56.png)
 已设置但是还是无法绑定成功,查看控制台请求服务已能正常返回我的笔记本列表:

```json
{
    "items": [{
            "id": "114a71aeef9d485f99c298a258c1a989",
            "parent_id": "",
            "title": "Welcome! (Mobile)"
        }, {
            "id": "03795c59885e4938b04380f794495343",
            "parent_id": "",
            "title": "TODO"
        }, {
            "id": "e3cb776c3a01412a801a42e3221c6cb2",
            "parent_id": "",
            "title": "SimpRead"
        }
    ],
    "has_more": false
}
```

请求成功后,一直停在页面没反应

**Comment by Kenshin** [comment]
emmm...

导出配置文件后（一定注意要导出配置文件），选项页 → 共通 → 重置当前配置 再试试。

**Comment by Felix2yu** [comment]
我也碰到这个问题了。按 https://github.com/Kenshin/simpread/issues/1633#issuecomment-752330054 关闭Joplin后点验证就可以了。
建议在Joplin授权的地方加个备注说明吧，这个也太坑了……

**Comment by Kenshin** [comment]
@Felix2yu

谢谢提示，我已经把 Joplin 相关问题整理到了 https://github.com/Kenshin/simpread/discussions/1895 以及对应文档里面了。

@qiangtou 

请按照 https://github.com/Kenshin/simpread/issues/1884#issuecomment-787308930 的提示设置，没问题的话，请关闭此 issues

**Comment by qiangtou** [comment]
问题已解决,
1. 填写token,先别点验证
2. ,确保joplin退出,在程序窗口点关闭后,程序可能还在系统托盘上,要右键托盘图标一并关闭
最好在任务管理器里面查看,确保没有joplin进程
3. 点击验证,等1-2秒就可以了

**Comment by Kenshin** [comment]
@qiangtou 

嗨，谢谢，我已经把你的解决方案放到了 #1895 里面
