### ISSUE TITLE
观止-每日一文 显示问题

### ISSUE THREAD

**Issue by AmorFati-coder** [Kenshin/simpread#1886]
- 操作系统 **Win64**

- 浏览器版本 **版本 88.0.4324.190（正式版本） （64 位）**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://meiriyiwen.com/?20210226>

> 无法正常显示文章标题与作者

**截图**

> ![微信截图_20210226121654.png](https://img10.360buyimg.com/ddimg/jfs/t1/169426/3/8183/3004169/6038767aE6a822c6d/716e642f6bff7d7a.png)
> ![微信截图_20210226121713.png](https://img13.360buyimg.com/ddimg/jfs/t1/162389/17/7981/163898/6038766dE6087a7cc/dfc18d0c6e1dfba3.png)

**Comment by Kenshin** [comment]
谢谢反馈，明天确认后回复你，我在外面，你可以试试 重新框选高亮。

**Comment by AmorFati-coder** [comment]
> 谢谢反馈，明天确认后回复你，我在外面，你可以试试 重新框选高亮。

效果不错，但comment也显示了
![屏幕截图 2021-02-26 192205](https://user-images.githubusercontent.com/71256552/109294447-2a819780-7868-11eb-8e67-33694ca14f6a.png)

**Comment by Kenshin** [comment]
> 效果不错，但comment也显示了。

你可以使用 **隐藏任意元素** 剔除不需要的内容。
另外，这个站感觉不错，可以加入到官方适配源里面，我先记新站。

**Comment by Buliet** [comment]
@Kenshin 大佬
https://meiriyiwen.com/ 这个站点通过隐藏任意元素已解决阅读显示问题
遇到以下问题：
该站点已加入一次稍后读后，刷新页面
不同的文章再加入稍后读，会提示：**已加入未读列表，请勿重新加入。**
需要怎么解决呢

**Comment by Kenshin** [comment]
@Buliet 

哈哈，之前漏掉了这个 Issues 😂 竟然漏掉了这么久...

> 不同的文章再加入稍后读，会提示：已加入未读列表，请勿重新加入。

因为这个网站的 URL 不改变，但每次刷新都有新的文章出现，简悦的稍后读判断标准是以 URL 为基判定标准的。

但有解决方案，我先记录下。

PS：你可以手动给 URL 加入一些「干扰参数」e.g.  `https://meiriyiwen.com/?id=1234` 这样就没事了。

1234 → 随便一个值就行，对应了一个稍后读
1235 → 对应了另外一个稍后读

**Comment by Buliet** [comment]
给力 点赞👍

**Comment by Kenshin** [comment]
嗨，各位。

![pika-1670398742694-1x](https://user-images.githubusercontent.com/81074/206119179-47a44aaf-2fcd-4a7d-b258-c2c8f087f683.png)

每日一文这个站已经完成了适配，并且增加了一个辅助用的插件。

## 📥 站点集市

https://simpread.ksria.cn/sites/details/vtV97Y5sPS

## 📥 插件地址

https://simpread.ksria.cn/plugins/details/z30Xy4ndgg

## 💡 注意

使用同步助手的自动同步后：

• [无法安装插件的解决方案](https://github.com/Kenshin/simpread/discussions/4221)

• [无法安装站点集市的解决方案](https://github.com/Kenshin/simpread/discussions/4859)
