### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by dmcyer** [Kenshin/simpread#1890]
https://t.bilibili.com/495928427589938828?tab=2 
![image](https://user-images.githubusercontent.com/35415011/109339847-33dc2580-78a3-11eb-816b-a75c1550031c.png)

**Comment by Kenshin** [comment]
嗨，这类页面不需要使用阅读模式。

**Comment by Kenshin** [comment]
另外你也可以通过重新高亮的方式来获取正文。
