### ISSUE TITLE
代码段增强插件运行失败

### ISSUE THREAD

**Issue by SsparKluo** [Kenshin/simpread#1891]
[https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/10](https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/10)

**Comment by Kenshin** [comment]
在 Github 上一般是我无法运行此插件的，我先把问题记录到 #500 里面吧。
另外，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
