### ISSUE TITLE
无法将网页添加进稍后读

### ISSUE THREAD

**Issue by haozi2333** [Kenshin/simpread#1896]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win64**

- 浏览器版本 **e.g. Chrome 88.0.4324.190**

- 简悦版本 **2.1.0**

问题:无法将网页添加进稍后读

**Comment by Kenshin** [comment]
抱歉，请详细说明这个问题。

**我先关闭此 Issues**，当你补充完详细说明后，**请随时开启它**。

例如：

> 通过何种操作无法添加到稍后读

**Comment by haozi2333** [comment]
在任何页面，右键后没有添加到稍后读，无论用什么方式都没办法将文章加入稍后读中

**Comment by Kenshin** [comment]
需要开启相关选项 http://ksria.com/simpread/docs/#/右键菜单

**Comment by Kenshin** [comment]
需要开启相关选项 http://ksria.com/simpread/docs/#/右键菜单

**Comment by Kenshin** [comment]
@haozi2333 

进入阅读模式后，使用快捷键加入稍后读呢？
