### ISSUE TITLE
使用后我的翻译插件不好使了

### ISSUE THREAD

**Issue by jpsia** [Kenshin/simpread#19]

**Comment by Kenshin** [comment]
`阅读模式` 为了避免 `被CSS污染`，会在 `<body>` 外生成一个新的标签。

而有些翻译扩展只搜寻 `<body>` 节点中的内容，自然会不好使。（ 准确的说 翻译的结果被 `阅读模式` 遮挡住了。）

如果我能联系到这个扩展的作者，可以跟他沟通一下这个情况。

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [划词翻译](https://simpread.ksria.cn/plugins/details/ohnTKVHz4a) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
