### ISSUE TITLE
请问主题的配置文件都放在哪里

### ISSUE THREAD

**Issue by Glassfire233** [Kenshin/simpread#190]
我想知道里面是如何设定的

**Comment by Kenshin** [comment]
你好，CSS 代码地址在 https://github.com/Kenshin/simpread/tree/master/src/assets/css

- `theme_common.css` 为共通类别；
-  `theme_xxxx.css` 为各个主题；

关于自定义样式 [请看这里](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by Glassfire233** [comment]
@Kenshin 谢谢你的帮助 回复速度真快

**Comment by Kenshin** [comment]
恰好宅在家…  😉 
如果有好的自定义样式也可以分享出来～

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
