### ISSUE TITLE
使用html<u>标签显示的问题无法被标注

### ISSUE THREAD

**Issue by haozi2333** [Kenshin/simpread#1904]
- 操作系统 **Win64**

- 浏览器版本 **e.g. Chrome 88.0.4324.190**

- 简悦版本 **2.1.0**

- 发生问题的地址 <
- https://sspai.com/post/65272
- 问题图片
- 
![image](https://user-images.githubusercontent.com/16058531/109820080-a2d4c800-7c6f-11eb-900d-128cfef41a93.png)
![image](https://user-images.githubusercontent.com/16058531/109820426-ef200800-7c6f-11eb-97fa-13dcb6353b24.png)

可能与这个issue为相同问题
https://github.com/Kenshin/simpread/issues/1766

**Comment by Kenshin** [comment]
嗨，谢谢反馈，下个版本修复。 👍

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
