### ISSUE TITLE
无法适配当前页面 colah.github.io

### ISSUE THREAD

**Issue by ArvinLiubaby** [Kenshin/simpread#1905]
发生问题的地址: <https://colah.github.io/posts/2015-08-Understanding-LSTMs/>

**Comment by Kenshin** [comment]
嗨，很奇怪问问，这个页面有什么特别？印象中已经好几个人用户问了。

PS：好像这个页面里面加了一些「代码」，导致无法识别正文。

**Comment by Kenshin** [comment]
嗨，这个站的适配规则已经更新，请使用下图的方式手动更新，位置在 选项页 → 站点管理

![image](https://user-images.githubusercontent.com/81074/120067368-c8763f80-c0ad-11eb-8706-3b0e6798641d.png)

除此之外，还需要将 `colah.github.io` 加入到排除列表，详情请看 https://github.com/Kenshin/simpread/pull/2237

我关闭这个 issues 了。

**Comment by Kenshin** [comment]
嗨，更正下，`colah.github.io` 在第三方适配源中，如何使用 [请看这里](https://github.com/Kenshin/simpread/discussions/2287)
