### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by gaoyi-ai** [Kenshin/simpread#1906]
发生问题的地址: <https://www.matongxue.com/madocs/7/>

**Comment by Kenshin** [comment]
嗨，抱歉，我无法登录这个页面，你可以试试 http://ksria.com/simpread/docs/#/重新高亮

另外，这个页面不属于大众类的页面，无法收录到官方适配源里面，另外下个版本会有个新功能会改善某些无法识别页面的问题。
