### ISSUE TITLE
阅读模式标注时提示"请在简悦•同步助手中开启此选项”

### ISSUE THREAD

**Issue by OptimusPrimeme** [Kenshin/simpread#1908]
- 浏览器 microsoft edge 版本 89
![剪贴板图片](https://user-images.githubusercontent.com/22427706/110102097-514b4b00-7ddf-11eb-8d7c-58a9cda116b0.jpg)

- 在稍后中标注则正常
- 这个问题之前也遇到过，后来不知道怎么解决，望大佬相助，尝试过重装插件，无用

**Comment by Kenshin** [comment]
嗨，你可以看下 https://github.com/Kenshin/simpread/discussions/1700 https://github.com/Kenshin/simpread/discussions/1692 的说明，可以解决你的问题。

**Comment by OptimusPrimeme** [comment]
谢谢大佬的回复，我一直有按照文档说的来操作的，设置同步文件夹，启用同步方案等；
不知道是不是今天用ccleaner清了缓存的原因还是啥，打开某个页面的阅读模式时一直弹上面的提示，在稍后读中没有这个提示，最后我又重装了插件再删了这个页面上的所有标注就正常了
> 嗨，你可以看下 #1700 #1692 的说明，可以解决你的问题。

**Comment by Kenshin** [comment]
@OptimusPrimeme 

嗨，解决就好。
不过，看你的描述，感觉像另外的问题造成。但由于你重置了，所以暂时没办法 Debug 了。
