### ISSUE TITLE
Edge和Chrome无法开启简悦同步助手，报错

### ISSUE THREAD

**Issue by Anthorty** [Kenshin/simpread#1909]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

Edge和Chrome均无法开启简悦同步助手，打开开关报错。报错截图如下

![image](https://user-images.githubusercontent.com/23048913/110196995-65488880-7e83-11eb-8e4e-0fe8a87b7b2d.png)

**Comment by Kenshin** [comment]
嗨，你的 Chrome 版本有点低。（这有可能会影响 简悦 · 扩展端的使用）

***

单看截图并没有什么信息量，不知道你的系统是什么版本以及安装的是 32 位同步助手版本吗？

建议至少在 Win 10 系统上使用。

**Comment by Anthorty** [comment]
> 嗨，你的 Chrome 版本有点低。（这有可能会影响 简悦 · 扩展端的使用）
> 
> 单看截图并没有什么信息量，不知道你的系统是什么版本以及安装的是 32 位同步助手版本吗？
> 
> 建议至少在 Win 10 系统上使用。

你好，经过检查，Edge浏览器版本为版本 89.0.774.45 (官方内部版本) (64 位)，提示为最新版
Chrome浏览器经过检查，版本为版本 89.0.4389.82（正式版本） （64 位），也是最新版。
目前使用的系统版本为Win10 1909专业版，同步助手版本为64位。
错误提示仍然出现

**Comment by Kenshin** [comment]
emmm

因为我看到提示

> 浏览器版本 e.g. Chrome 78.0.3904.108

所以才觉得版本过低。当然，这只是个「误会」。

***

你是否安装了某些防火墙？或者试试使用 32位 版，看看能否解决？

**Comment by Anthorty** [comment]
> emmm
> 
> 因为我看到提示
> 
> > 浏览器版本 e.g. Chrome 78.0.3904.108
> 
> 所以才觉得版本过低。当然，这只是个「误会」。
> 
> 你是否安装了某些防火墙？或者试试使用 32位 版，看看能否解决？

32位仍然报错，系统安全软件只有火绒，退出后仍报错。

**Comment by Anthorty** [comment]
问题已解决，onedrive同步文件，将json文件内容复写成0000

**Comment by Kenshin** [comment]
很奇怪的问题，请问你是如何解决的？

我想把解决方案整理出来，但不确定是否只是个例而已。

PS：因为解决了这个问题，我先关闭 Issues 吧。
