### ISSUE TITLE
一些小说网站使用阅读模式的时候总是提示当前页面结构以改变 无法匹配阅读模式

### ISSUE THREAD

**Issue by Glassfire233** [Kenshin/simpread#191]
如www.snwx8.com  www.dhzw.org www.aileleba.com
解决的方法是什么

**Comment by Kenshin** [comment]
估计是适配站点的结构改变了，你可以自己通过站点编辑器修改 或 我明天用电脑的时候确认一下。

**Comment by Kenshin** [comment]
搞定就好，没问题的话，我关闭此 issues 。

**Comment by Glassfire233** [comment]
@Kenshin 好的

**Comment by Kenshin** [comment]
你给出的这个站都没有在适配列表中，所以自然无法生成阅读模式。
解决办法：

- 适配列表中增加它们，然后你可以同步过去；
- 自己通过 [站点编辑器](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8) 增加它们；

如果是后者的话，希望你分享这些站的适配文件，以便更多人使用~
