### ISSUE TITLE
保存到 notion 后，显示成功，但回到 notion 后只保存了文章标题，内容为空的

### ISSUE THREAD

**Issue by sqmwin** [Kenshin/simpread#1910]
无论是否勾选了“使用 notion 作为图床”，都会出现此问题。
当显示成功后，第一次进入 notion 导入的页面，是有内容的，但页面会突然刷新成无内容的

**Comment by Kenshin** [comment]
嗨，可以看看 https://github.com/Kenshin/simpread/discussions/1773 给出的解决方案。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4
