### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#1914]
为啥不能线diigo一样，直接同步标柱，还要下一个app才可以？

**Comment by Kenshin** [comment]
嗨，好久没有看到你留言了。

这个问题其实很简单，**简悦 · 同步助手不仅只有自动同步** 而已，它为扩展端提供了无法实现的功能。

作为轻度使用用户来说，你可以直接使用手动同步功能，或有可能不需要使用同步功能。
反之，同步助手为你提供了更多的服务。

***

diigo 的问题在于：数据不再本地；而简悦的优势在于：数据在用户的本地。

**Comment by AriaLyy** [comment]
为了一个同步就要下载一个应用，感觉很浪费系统资源（我本地电脑有太多的同步软件了，坚果云、onedrive、synology、为知），对于我这种轻度用户来说，平时就只有标注需要同步，但是我标注又用的少，
可否增加坚果云自动同步功能？直接把标柱文件同步到坚果云上面，这样体验是否会好一点？

**Comment by AriaLyy** [comment]
并且还有一些问题，我有多台电脑，每台电脑都要下载简阅同步软件，并且还让它一直开启，我才能在多个端同步标注，这感觉～～

**Comment by AriaLyy** [comment]
顺便问下，数据保存在本地的，是否意味着，我清空浏览器缓存，我的笔记信息就丢失了？

**Comment by Kenshin** [comment]
> 为了一个同步就要下载一个应用，感觉很浪费系统资源（我本地电脑有太多的同步软件了，坚果云、onedrive、synology、为知），对于我这种轻度用户来说，平时就只有标注需要同步，但是我标注又用的少，
> 可否增加坚果云自动同步功能？直接把标柱文件同步到坚果云上面，这样体验是否会好一点？

如果只是轻度使用的话，用手动同步方案（即原来的方式就行了，也就是多了步手动操作）

当然，后续会考虑 **轻度使用** 在扩展端端的自动同步方案。（但扩展端能做的很少）

***

> 并且还有一些问题，我有多台电脑，每台电脑都要下载简阅同步软件，并且还让它一直开启，我才能在多个端同步标注，这感觉～～

这很正常啊，比如你经常使用坚果云，那么是不是每台设备都需要安装呢？一个道理。
目前同步助手只提供了单一的同步方案，下下个版本会集成更多同步方案。

另外，同步助手只是为简悦 Desktop 版的前身，未来会有个 Desktop 版的简悦（也就是 同步助手 的真正「形态」）

***

> 顺便问下，数据保存在本地的，是否意味着，我清空浏览器缓存，我的笔记信息就丢失了？

保存在本地，自然就不会出现你说的情况了。本地的意思是：任意路径。

建议看下 [同步助手](http://ksria.com/simpread/docs/#/Sync) 的文档 ，花几分钟了解下，会比你问问题更有效。 

😀

**Comment by AriaLyy** [comment]
同步助手我知道怎么弄，但是对于以前用惯了diigo的人来说，目前简阅的同步方式体验真的有点差。
今天我想从chrome转到edge，打开我的笔迹，一片空白，一脸懵逼。
正是因为我的同步软件太多，我才不希望再加同步软件了。我看了下同步助手保存的文件，发现其只是一个josn文件，感觉扩展应该可以直接将数据生成json，存到chrome的沙盒，然后再将该json同步到坚果云。

**Comment by Kenshin** [comment]
> 可以直接将数据生成json，存到chrome的沙盒，然后再将该json同步到坚果云。

之前说了，如果是轻量级的话，手动即可。（接下来会考虑扩展端的轻量级保存方案）

> 正是因为我的同步软件太多，我才不希望再加同步软件了

这是你个人的问题，跟简悦无关。（换句话说，我就没有你的诉求，但这也只是个人问题）

***

> 正是因为我的同步软件太多，我才不希望再加同步...

我已经重复过一次了，同步助手只是 Desktop 版的前奏版本。另外，你可以不使用用它，完全不妨碍你的标注操作，只是多了步手动同步而已。

**Comment by Kenshin** [comment]
嗨，昨天太忙了，再加上你是老用户，所以再说下你的疑惑。

> 为什么没有在扩展端做自动同步

简悦不收集用户的数据意味着用户如果需要实现同步功能，则使用用户自己的网盘服务，每个网盘服务的容量计费标准都不一样。

比如：坚果云。通过同步助手同步 +  坚果云客户端同步的话，属于增量上传；使用扩展端同步的自然不可能是增量上传。
再比如：扩展端能做的事情其实不多，如果以后要使用 Git 方案的话，就没法弄了。

简而言之，针对重度使用用户来说，同步助手是最好的方案（没有之一），轻度使用用户的话，完全手动就可以了。

***

你的数据会保存在 diigo 中，所以它不需要考虑这些问题，但带来的问题就是：用户没法真正拥有用户自己的数据。（即便是导出，你能把 diigo 导出的数据再导入到其它服务吗？基本上是不太可能的。

**Comment by AriaLyy** [comment]
感谢回复，我理解你的方案和扩展端的限制。
我也知道diigo的问题，因为以前我一直想将diigo的东西导出到为知，一直很难搞。
但是站在用户的角度来看，不需要同步助手就能多端同步应该是最好的体验了吧，当然，这也只是我的看法。
之所以提这个同步问题，还是因为我chrome中已经设置dropbox的同步来，我想当然的以为我的笔记也自动同步到dropbox😂，然后换到edge，配置好dropbox的信息，却发现笔记没了，感觉有点懵，然后看了文档才知道需要个同步助手才能同步～～

最后，还是希望楼主能增加一些轻度用户的同步方案，比如webdav、onedrive、dropbox，我想其它的轻度用户应该也乐意看到这些吧😊

**Comment by AriaLyy** [comment]
😓，刚才重新试着在chrome手动点了下同步dropbox，发现dropbox上的json，有笔迹了，估计是我昨天没有手动点那个同步按钮
![image](https://user-images.githubusercontent.com/10437293/110412694-90231e80-80c7-11eb-805c-d19eeedb1c69.png)
这样看来，是否可以这样，每次用户打开标注，就自动给用户同步一次

**Comment by Kenshin** [comment]
emm...

会考虑你的建议。

你可能没有留意，我之前就反复提到了 **手动更新**，简悦原本就支持手动更新。

**Comment by AriaLyy** [comment]
感谢
