### ISSUE TITLE
建议启用/关闭标注增加全局快捷键

### ISSUE THREAD

**Issue by cpp-jiang** [Kenshin/simpread#1915]
启用/关闭标注对我来说是最高频的操作了, 有时候需要复制文本只能关闭标注, 做笔记又需要启用标注, 经常混合使用就感觉很麻烦

**Comment by Kenshin** [comment]
嗨

其实是有快捷键的，但并不像 `A A` 这样高级别的。（ 你可以通过 `s r` → `,` 查看标注的全部快捷键。

当然，会考虑你的想法，下个版本增加更高级别的快捷键。

**Comment by Kenshin** [comment]
PS：又是老用户的反馈。（今天什么日子，总是有老用户反馈。  😀

**Comment by cpp-jiang** [comment]
按快捷键会老叫我刷新呢?

**Comment by Kenshin** [comment]
@cpp-jiang 

估计是这个 URL 被多个 Tab 打开了，所以有这个情况，确保发生这个问题时，你的 URL（页面）仅对应一个标签页。

例如：在你的浏览器打来了两个标签页，都是 http://simpread.pro/ 当配置文件发生改动时，就会存在这个情况。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
