### ISSUE TITLE
AWS Amplify App 登录界面错误捕获热键

### ISSUE THREAD

**Issue by elephi** [Kenshin/simpread#1918]
声明：这可能是一个非常罕见的问题，我不确定是谁的问题。
如果以后基于 AWS Amplify 的 App 大量增加（概率很大），可能会影响使用者。

故障现象：
1. 访问 https://dev.d1cdwxupk2mejz.amplifyapp.com/
2. 在 Username 或者 Password 中输入带 A S 组合的内容（比如Pass）
3. SimpRead 被触发了（请看右下角 SimpRead 出现了）

上述地址是我正在测试的 Web App，理论上应该一直存在，如果不存在请联系我。

![image](https://user-images.githubusercontent.com/1418703/110490794-8eb61e00-80e8-11eb-8e20-9dc10386049a.png)

**Comment by Kenshin** [comment]
emmm...

确实有这个问题，目前的解决方案是：将 `https://dev.d1cdwxupk2mejz.amplifyapp.com/` 或 `amplifyapp.com`  加入到黑名单，即可。

**Comment by elephi** [comment]
好的，已加黑名单。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

**Comment by elephi** [comment]
Hi Kenshin 我刚才试了一下发现问题在最新版本下还是存在的，不过这不是个大问题，暂时不处理也罢。

**Comment by Kenshin** [comment]
哈哈，因为这是个 Delay 了很久 Issues，我今天 Closed  100+ 个，所以没办法一一说明。

我的意思是

> 增加了禁用全部快捷键的功能，所以算是变相解决了。 😂 

![image](https://user-images.githubusercontent.com/81074/133238613-b13581fe-5500-4a08-b1d0-b64335a02ca3.png)

**Comment by elephi** [comment]
好的，多谢了！
