### ISSUE TITLE
可否提取出样式

### ISSUE THREAD

**Issue by chenhonzhou** [Kenshin/simpread#192]
如何提取出样式，使用到个人网站中.小白求解

**Comment by Kenshin** [comment]
你需要让你的网站支持阅读模式吗？如果是的话，请看 主动阅读模式 。

样式文件以及说明请看 https://github.com/Kenshin/simpread/issues/190

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
