### ISSUE TITLE
解析正文失败，可以给我提 Issues ↗ 如果开启了 内置解析方案 的话，请多刷新几次一般可以解决。

### ISSUE THREAD

**Issue by zhl111** [Kenshin/simpread#1922]
无法解析

- 操作系统 **Windows 10**

- 浏览器版本 **edge**

- 简悦版本 **2.0.0**

- 发生问题的地址 ：如何看待股指期货的升贴水--财经--人民网
http://finance.people.com.cn/stock/n/2014/1105/c390499-25980740.html

**请描述你的问题**：解析正文失败

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**Comment by Kenshin** [comment]
嗨，看了下应该没问题，我先关闭此 issues  你可以告诉我哪里有问题，确认后我会 再次开启它。
