### ISSUE TITLE
导出全文离线html依然只有标注的问题

### ISSUE THREAD

**Issue by NoirTree** [Kenshin/simpread#1924]
环境：

- 操作系统 Windows

- 浏览器版本 Chrome 88.0.4324.190

- 简悦版本 2.1.0

问题：

你好，我很喜欢简阅这款产品！用起来非常顺手，但在导出html/pdf到本地的时候发生了一些问题：

我已按照 [#issue1712](https://github.com/Kenshin/simpread/discussions/1712) 的方法尝试过导出全文，但结果依然只有标注。 具体操作如下：

在阅读模式下关闭此开关，切换到“导出全文模式。
![image](https://user-images.githubusercontent.com/66409637/110814045-09876080-82c4-11eb-8633-762982e78112.png)

在”稍后读--阅读模式“下，点击导出离线HTML
![image](https://user-images.githubusercontent.com/66409637/110814103-1a37d680-82c4-11eb-9a59-8d2b152ba901.png)

这个是导出成功的提示
![image](https://user-images.githubusercontent.com/66409637/110814135-22901180-82c4-11eb-818c-0ae804a64e97.png)

打开该离线HTML，依然只有标注，而不是全文
![image](https://user-images.githubusercontent.com/66409637/110814167-2a4fb600-82c4-11eb-9c78-73b2d6c8635b.png)

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

emm....

抱歉，你说的情况确实存在。  😓  （这是个 Bug 但我确实在 #1712 重现了截图所示的方案，不知道为什么又失效了。

不过，也有 **解决方案**：

> 请 **不要在稍后读 → 阅读模式 里面使用此功能**，在 **原始页面** 上使用就没问题了。

也就是说，暂时需要多操作一步，通过下图打开原页面，再导出。

![image](https://user-images.githubusercontent.com/81074/104690941-4f9aca80-5740-11eb-94f2-7bbdc4638e32.png)

***

这个 Bug 在新版早就 Fixed 掉了，只是还没发布，所以这个 issues  先留着，同时我也会这个解决方案更新到  #1712 里面。

***

搞定后告诉我下。  😀

**Comment by NoirTree** [comment]
哈哈搞定啦，多谢！祝简阅越做越好~

**Comment by Kenshin** [comment]
搞定就好~  😏

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
