### ISSUE TITLE
阅读模式下，导出pdf时候，选择导出批注 和导出全文，生成的pdf会覆盖

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#1925]
![image](https://user-images.githubusercontent.com/38575961/111030155-bcc69580-843b-11eb-98b4-ba0b3a26efd7.png)

![image](https://user-images.githubusercontent.com/38575961/111030166-c6e89400-843b-11eb-8f20-75a9ddb49212.png)

最后生成的pdf只有一个 且会相互覆盖
![image](https://user-images.githubusercontent.com/38575961/111030188-dbc52780-843b-11eb-8811-c6808720fb15.png)

**Comment by Kenshin** [comment]
这是「正常」的情况，因为它们的导出名称一样，会考虑优化这种情况。

**Comment by janciszhang** [comment]
导出pdf的时候，文件为0 kb，不是pdf格式，打不开

<img width="1039" alt="231a2dd2fb66348aa1df48e69c8dae7" src="https://user-images.githubusercontent.com/80568017/111270670-182a9a80-866b-11eb-8700-a18897cd996f.png">

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
