### ISSUE TITLE
导出为pdf时候  为什么有的图片是显示不出来？

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#1926]

**Comment by enron2014** [comment]
原文地址为
https://www.cnblogs.com/ysocean/p/7689146.html#_label1_26


导出的pdf  图片缺失

![image](https://user-images.githubusercontent.com/38575961/111030275-2e9edf00-843c-11eb-9a7e-721856f7be5e.png)

**Comment by Kenshin** [comment]
多测试几次，有可能是网络不稳定造成的。
