### ISSUE TITLE
关于较长篇幅文章导出失败的反馈

### ISSUE THREAD

**Issue by AlanYoungC** [Kenshin/simpread#1928]
- 操作系统   Windows 

- 浏览器版本 Chrome 89.0.4389.82

- 简悦版本 2.1.0

- 发生问题的地址 https://sspai.com/post/65051

过长的文章会直接导致PDF或者EPUB以及离线HTML导出失败。多个网址测试均为如此。希望能够尽快解决

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/53827042/111063577-7c722080-84ea-11eb-879c-9b86061a6fdd.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

并不是简悦的问题，生成 离线 HTML 时，会将图片进行 Base64 编码方式。如果 PC 性能不佳的话，有可能导致转换失败。
另外，当 `size > 3mb` 时，尽量使用 **同步助手** 的导出方案。

比如，你给出的链接，我很容易生成 离线 HTML，图下面的内容，你下载后请改名 `.txt → .html` 

[1419-重度使用这款墨水屏手机之后，谈谈我对电子纸的理解和预测 - 少数派.txt](https://github.com/Kenshin/simpread/files/6136495/1419-.-.txt)

PS：Epub 或 PDF 也均为这种情况。

**Comment by AlanYoungC** [comment]
感谢你的回复！

我检查了一下，是同步助手的文件保存位置丢失了导致。但是偶尔会能够导出小文章但是无法导出大文章的情况。另外附上我的电脑配置
![image](https://user-images.githubusercontent.com/53827042/111072879-78a8c300-8517-11eb-8100-765bf25704cc.png)


但是对于另外一篇少数派的付费文章（该章节可以免费阅读，依然会出现无法导出的问题）
文章地址：https://sspai.com/post/43217`
![image](https://user-images.githubusercontent.com/53827042/111072952-c4f40300-8517-11eb-824a-5ef951e41127.png)

是否简悦内置了版权保护机制呢？

**Comment by AlanYoungC** [comment]
另附
![image](https://user-images.githubusercontent.com/53827042/111073197-c7a32800-8518-11eb-9f5e-d640a5a5222d.png)

**Comment by Kenshin** [comment]
> 另附
> ![image](https://user-images.githubusercontent.com/53827042/111073197-c7a32800-8518-11eb-9f5e-d640a5a5222d.png)

这个图提示的信息是：7026 端口被占用，你重启同步助手就可以了。

PS：至于你的问题，我目前在用 Mac 我找个 Windows 的朋友，问问看是否有这个问题吧。
