### ISSUE TITLE
知乎文章顶部图片

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#1932]
知乎文章顶部图片不能进入阅读模式中，也不能在文章导出的时候与其他图片一同导出
![Snipaste_2021-03-15_17-19-30](https://user-images.githubusercontent.com/74438973/111130853-a2fb8e80-85b2-11eb-9771-557a9a1c3528.png)
![image](https://user-images.githubusercontent.com/74438973/111130913-b3136e00-85b2-11eb-87e6-e06e4b053d4c.png)

**Comment by Kenshin** [comment]
嗨，目前是这样的，并不是每个页面都有题图，所以默认都不会抓取题图。
后续会考虑加个插件实现此功能。

**Comment by Kenshin** [comment]
嗨，这个问题可以使用 [题图插件](https://github.com/Kenshin/simpread/discussions/2487) 解决。
