### ISSUE TITLE
安卓手机Kiwi浏览器下保存操作体验问题

### ISSUE THREAD

**Issue by Atomonkey** [Kenshin/simpread#1934]
环境：安卓版最新Kiwi浏览器安装简悦2.1.0版扩展。
保存到OneNote、语雀等遇到体验问题。
见图：
![Screenshot_20210316_170245820_Kiwi Browser](https://user-images.githubusercontent.com/6678755/111283752-6a26ec80-867a-11eb-844a-f6f2fdb8b09b.jpg)

由于不支持快捷键，保存到前面几个笔记源会被遮挡非常麻烦。
建议考虑以下通用解决方案：
1、保存操作按钮展开后只展示配置的笔记源。
或者
2、在阅读模式中类似浮动标注栏配置一样增加一个默认保存到指定目标服务的设置项。
![image](https://user-images.githubusercontent.com/6678755/111284319-fc2ef500-867a-11eb-8109-43581b336ea0.png)

**Comment by Kenshin** [comment]
嗨，可以试试 https://github.com/Kenshin/simpread/discussions/1601 基本上可以解决你的问题。

**Comment by Atomonkey** [comment]
我的kiwi装不了简悦插件，一直停在“正在安装，请稍候...”  需要做啥配置吗，我把kiwi权限都开了，去广告也都关闭了。

**Comment by Atomonkey** [comment]
掌握规律了，直接在手机上设置不太可行，需要在PC上设置好再同步配置文件过来。

**Comment by Kenshin** [comment]
> 掌握规律了，直接在手机上设置不太可行，需要在PC上设置好再同步配置文件过来。

是的，手机端的问题是，Kiwi 支持的功能不是 100% 覆盖 Desktop 端，所以需要你说的方式。 👍
