### ISSUE TITLE
动作页面图标不显示，其他页面正常（安装阅读模式浮动面板定制器且因  Extension ID 不同导致）

### ISSUE THREAD

**Issue by CNJasonChio** [Kenshin/simpread#1936]
![image](https://user-images.githubusercontent.com/36125147/111422727-18d63600-872a-11eb-8f37-65245e6efd0b.png)
![image](https://user-images.githubusercontent.com/36125147/111422730-1b389000-872a-11eb-8a60-c60d745f741f.png)

**Comment by Kenshin** [comment]
嗨，这是个 Bug 因为你同时使用了不同的简悦造成的，如：Chrome 与 离线版（大致是这个意思）因为使用了「不同」的简悦，造成了 Extension ID 不一致。

解决方案：（不完美）

重置 [阅读模式浮动面板定制器](https://github.com/Kenshin/simpread/discussions/1601) 即可，但一旦在不同的  Extension ID 上同步后仍存在此问题。

预计（此插件）下个版本，解决这个问题，到时候我会在这里通知你

***

PS：这里的不同不是说简悦的版本，而是安装渠道不同。

**Comment by CNJasonChio** [comment]
> 嗨，这是个 Bug 因为你同时使用了不同的简悦造成的，如：Chrome 与 离线版（大致是这个意思）因为使用了「不同」的简悦，造成了 Extension ID 不一致。
> 
> 解决方案：（不完美）
> 
> 重置 [阅读模式浮动面板定制器](https://github.com/Kenshin/simpread/discussions/1601) 即可，但一旦在不同的 Extension ID 上同步后仍存在此问题。
> 
> 预计（此插件）下个版本，解决这个问题，到时候我会在这里通知你
> 
> PS：这里的不同不是说简悦的版本，而是安装渠道不同。

通过重置配置已经解决，多谢回复。可能是因为我从chrome转到了edge。
