### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by JasonNzj** [Kenshin/simpread#1939]
发生问题的地址: <https://blog.csdn.net/hebtu666/article/details/114818801?utm_medium=distribute.pc_category.none-task-blog-hot-5.nonecase

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
