### ISSUE TITLE
高级用户无法导出Markdown或者PDF

### ISSUE THREAD

**Issue by FOkvj** [Kenshin/simpread#1940]
起初还可以，到后面就不行了，搞哪出啊，而且为什么我重启了电脑之后要重新登录？

**Comment by FOkvj** [comment]
rlgl，突然就变成实验性功能了，刚买会员的时候还能导出的，该不会是要再搞一个超级会员吧？是我太年轻了？

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/discussions/1617
