### ISSUE TITLE
阅读模式以及稍后读中的主题颜色能够跟随系统切换

### ISSUE THREAD

**Issue by OptimusPrimeme** [Kenshin/simpread#1943]
- 简悦功能挺好的，用的越来越多，现在很多应用都能够跟随系统切换主题颜色，希望开发者能考虑一下，在使用电脑时候颜色能够更加的一致，体验更上一层楼！👍

**Comment by Kenshin** [comment]
嗨，谢谢对简悦的喜爱和建议，会考虑的。

PS：目前 稍后读 → 阅读模式 可以跟随稍后读的「暗色模式」，即当稍后读使用暗色模式后，进入稍后读的阅读模式，可自动为暗色模式。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
