### ISSUE TITLE
古诗文网显示不全问题

### ISSUE THREAD

**Issue by Celestial-Plato** [Kenshin/simpread#1949]
操作系统 win10 家庭版

浏览器  Microsoft Edge

简悦版本  刚从官网下载的版本    3.19

发生问题的地址 https://so.gushiwen.org/shiwenv_63579de8b4d8.aspx

-------------------------------------------------------------------------------------------------------------------

您好，我在站点集市中寻找站点，未能解决，阅读模式是通过手动点击进入的。

在阅读古诗文网的诗歌时，点击阅读模式，显示的内容不全，原网页下拉内容被截断，译，注选项显示的内容消失。
url('https://so.gushiwen.org/mingju/juv_49ab7b66ed43.aspx')

希望能够这条反馈能被发现，已经支持。祝好。
后续通过框选解决了一部分问题，不过每次阅读新的古诗都需要重新框选，笑哭
![Snipaste_2021-03-19_15-15-43](https://user-images.githubusercontent.com/80942582/111744313-fe38c400-88c5-11eb-9b90-645a02e5550e.png)另外帮助文档不能显示图片，不知道是不是自己的原因，我的Edge和Chrome都不能显示。

**Comment by Kenshin** [comment]
嗨，关于 https://so.gushiwen.org/mingju/juv_49ab7b66ed43.aspx 页面的内容，
因为它是「分段」的，所以无法自动生成阅读模式。

你想要的效果是什么？我可以考虑适配它。

另外，**展开阅读全文** 下面的内容不是隐藏的，而是压根没有显示，所以生成阅读模式后也有些问题。

***

> 帮助文档不能显示图片，不知道是不是自己的原因，我的Edge和Chrome都不能显示。

估计某些图片需要保证网络畅通。

**Comment by Celestial-Plato** [comment]
> 嗨，关于 https://so.gushiwen.org/mingju/juv_49ab7b66ed43.aspx 页面的内容，
> 因为它是「分段」的，所以无法自动生成阅读模式。
> 
> 你想要的效果是什么？我可以考虑适配它。
> 
> 另外，**展开阅读全文** 下面的内容不是隐藏的，而是压根没有显示，所以生成阅读模式后也有些问题。
> 
> > 帮助文档不能显示图片，不知道是不是自己的原因，我的Edge和Chrome都不能显示。
> 
> 估计某些图片需要保证网络畅通。

嗯，想要的效果是在原网页点击展开阅读全文以及译、注、赏得到的内容，在之后点击进入阅读模式后也能够显示，另外如果能把阅读模式中字体样式无法改变的特大号标题去掉就更好了。不过，如果特别麻烦的话，不实现也没关系，在其他网站我用这个插件已经很满意了。
或者，告诉我适配需要哪些知识也可以（不知道用户能不能自己适配），我业余正在学些简单的网页知识，目前，刚刚学到CSS，以上。感谢。
![sp20210319_184633_890](https://user-images.githubusercontent.com/80942582/111769759-8af27a80-88e4-11eb-80c8-612fe52d9ebc.png)
![sp20210319_184641_674](https://user-images.githubusercontent.com/80942582/111769763-8cbc3e00-88e4-11eb-8673-f4bff2b0bc3b.png)
![sp20210319_184654_194](https://user-images.githubusercontent.com/80942582/111769769-8d54d480-88e4-11eb-80c7-00df3581eccb.png)
![sp20210319_185213_816](https://user-images.githubusercontent.com/80942582/111769774-8ded6b00-88e4-11eb-9ae0-a432da18acdf.png)

**Comment by Kenshin** [comment]
嗨，收到，我研究下，这个问题稍微比较麻烦，不是简单的 CSS 可以解决的。

但适配的前提是：你需要先点击 **展开阅读全文** 后才行。

**Comment by Kenshin** [comment]
嗨，呼唤大神 @binsee ~

这个站我想适配下，估计需要在 `include` 插入 JS 代码才能实现。
要是有时间的话，看下？

***

其中 **展开阅读全文** 隐藏的部分是调用了后端，并不是真正的隐藏，所以 **抓取的是它点击之后的内容**。

**Comment by Celestial-Plato** [comment]
> 嗨，收到，我研究下，这个问题稍微比较麻烦，不是简单的 CSS 可以解决的。
> 
> 但适配的前提是：你需要先点击 **展开阅读全文** 后才行。

奥奥，这个没关系，如果能适配的话，希望我点击译和注显示出的内容也有（就是右上角的小圈圈）

**Comment by binsee** [comment]
相关js代码如下，嵌入到 `include` 中使用：

```js
left = $('.main3 .left');
['译文', '赏析', '注释'].forEach(text => {
  left.find(`img[alt='${text}']`).click();
});
left.find("div a:contains('展开阅读全文')").each((i, e) => { e.click() });
```

**Comment by Celestial-Plato** [comment]
> 相关js代码如下，嵌入到 `include` 中使用：
> 
> ```js
> left = $('.main3 .left');
> ['译文', '赏析', '注释'].forEach(text => {
>   left.find(`img[alt='${text}']`).click();
> });
> left.find("div a:contains('展开阅读全文')").each((i, e) => { e.click() });
> ```

感谢

**Comment by Kenshin** [comment]
@Celestial-Plato 

嗨，我已经把这个站合并到了官方适配源，你可以使用 **选项页 → 站点管理 → 手动同步适配列表** 的方式更新，更新后，应该是 341 个适配站点，即可。

没问题的话，请关闭此 Issues ~！

非常感谢 @binsee 的帮助！

**Comment by Celestial-Plato** [comment]
> @Celestial-Plato
> 
> 嗨，我已经把这个站合并到了官方适配源，你可以使用 **选项页 → 站点管理 → 手动同步适配列表** 的方式更新，更新后，应该是 341 个适配站点，即可。
> 
> 没问题的话，请关闭此 Issues ~！
> 
> 非常感谢 @binsee 的帮助！

好的，麻烦了。
