### ISSUE TITLE
印象笔记保存后图片位置错误

### ISSUE THREAD

**Issue by yEs1do** [Kenshin/simpread#195]
在保存 [纸质书还是电子书，我们该如何选择？](https://zhuanlan.zhihu.com/p/27939975) 时，所有内容均保存到了印象笔记中，但是文字部分在前，图片像引用一样在最后出现。
![image](https://user-images.githubusercontent.com/25378493/34466370-a27d6be0-ef0b-11e7-9f2c-c2d771c430cd.png)
![image](https://user-images.githubusercontent.com/25378493/34466372-b99b1c50-ef0b-11e7-9490-e7254f75b718.png)
![image](https://user-images.githubusercontent.com/25378493/34466374-bf9fd974-ef0b-11e7-91fb-1b7f617c3fdb.png)

**Comment by Kenshin** [comment]
感谢反馈～
印象笔记实在是各种奇葩问题… 
近期在休假中，有时间会确认一下，建议换成 Onenote 具体请看其它类似的 issues 问题…

**Comment by Kenshin** [comment]
没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
