### ISSUE TITLE
无法登陆简悦

### ISSUE THREAD

**Issue by goodluck233** [Kenshin/simpread#1950]
我之前在另一台电脑上，充值了高级会员兑换码。现在手里有兑换码和uid，但不能使用另一台电脑，也没有任何文件，请问怎么登录？

**Comment by Kenshin** [comment]
嗨，如果你有 UID 的话，很好解决，解决方案如下：

> 方案一

在需要登录高级账户的浏览器 → 安装简悦 → 打开选项页 → 导出配置文件 → 用任意文本编辑器（打开） → 寻找并替换其中 uid 为正确的 → 导入此配置文件 → 右上角 icon → 仅授权当前设备

> 方案二

在需要登录高级账户的浏览器 → 安装简悦 → 打开选项页的账户选项卡 → 找回 UID → 自动找回

PS：此方式虽然简单，但会浪费一次找回机会（共计三次）

***

建议方案一，虽然看起来步骤很多，实际操作估计不到三分钟即可完成。

**Comment by Kenshin** [comment]
嗨，我把这个问题整理到了 https://github.com/Kenshin/simpread/discussions/1958 请直接查看。
