### ISSUE TITLE
没法上传notion图片了

### ISSUE THREAD

**Issue by dongjinhai** [Kenshin/simpread#1955]
**请说明发生问题的环境**

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

这个网址
https://mp.weixin.qq.com/s/Rpx6DINBNup8n0PumJhMBw
https://www.zhihu.com/question/39948290/answer/883302989
**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![微信图片_20210321180515](https://user-images.githubusercontent.com/18241524/111900896-05033a80-8a70-11eb-8773-a1b1e81190ef.png)

**Comment by Kenshin** [comment]
导入 Notion 使用了私有 API，所以不是很稳定。
我测试了下，是没有问题的，请稍后再试。

关于 Notion API 问题可以看下 https://github.com/Kenshin/simpread/discussions/1773

**Comment by dongjinhai** [comment]
好的，我明天再试试

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4
