### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zheng-yu9** [Kenshin/simpread#1963]
你好，我曾从少数派购买简悦的高级会员，但我只配制坚果云第三方登录后就有事未曾操作。随后我不得已重装了系统，在我重下简悦后UID改变，我成为普通会员。请问我该如何重新登入高级会员账号？
我已经找到自己购买时的UID与License
谢谢

**Comment by zheng-yu9** [comment]
通过阅读#1950我已经解决问题

**Comment by Kenshin** [comment]
恭喜自救成功~

我把 #1950 的内容整理到了 https://github.com/Kenshin/simpread/discussions/1958 :)

没问题的话，我直接关闭此 issues ~
