### ISSUE TITLE
稍候读的所有内容消失了

### ISSUE THREAD

**Issue by alin-alin-alin** [Kenshin/simpread#1964]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

稍候读的所用东西消失了  很恐怖  不知道怎么复原  查了查问题没有看见有人遇到过

**Comment by alin-alin-alin** [comment]
消失不太准确  就之前所有文章的记录  标签  什么的就都没了  类似被回复出厂设置一样

**Comment by alin-alin-alin** [comment]
解决了  在onedrive里头找到.json文件的历史版本  覆盖掉先出现的  就OK了

**Comment by Kenshin** [comment]
okay 搞定就好。

所以，一个具有历史记录的网盘是多么的重要。 😊
