### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by phynex** [Kenshin/simpread#1965]
发生问题的地址: <https://blog.csdn.net/hebtu666/article/details/114827837?utm_medium=distribute.pc_feed.none-task-blog-yuanlijihua_sort_v1-4.nonecase

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
