### ISSUE TITLE
简悦与 Vimium 有冲突

### ISSUE THREAD

**Issue by Neightlurker** [Kenshin/simpread#1966]
阅读模式下使用“Vimium”插件会有肉眼可见的延迟，例如使用 J 向下滚动，从按下按键到屏幕往下滚动会有一种明显的滞后感，很不协调

**Comment by Kenshin** [comment]
嗨，这算是「正常」的事情，阅读模式由于特殊性，所以跟某些扩展会有冲突，如：键盘操作类的，翻译类的扩展。

你可以试着把 [目录](http://ksria.com/simpread/docs/#/%E7%9B%AE%E5%BD%95) 功能关闭，看能否解决？

**Comment by Kenshin** [comment]
补充下，你可以使用 键盘键，看看是否可以？

**Comment by Neightlurker** [comment]
我是在知乎浏览问答时使用的阅读模式，感觉是没有加载目录的，不过用翻页按钮倒是没有这个麻烦了。另外简悦的确与许多插件兼容性不够好，我这还有一个Screen
Shader护眼插件，就好像与简悦完全是对头一般（可能是两者原理类似），只要开启前者，简悦的阅读模式开启后就是一片空白，一个字都没有那种，希望Ken大大能看看

Kenshin Wang ***@***.***> 于2021年3月24日周三 上午10:29写道：

**Comment by Kenshin** [comment]
哈哈，Screen Shader 与简悦也肯定有冲突。

简单的说，简悦使用了一些非规范的技巧，一般比较「懒」的开发者不会全盘考虑，所以有这样的问题。
但如果开发者考虑周全的话，就不会存在问题，例如 Dark Reader 在简悦下就非常完美。

PS：这里不是说谁对谁错，而是凡是对页面的代码有注入行为的扩展，大多有这样的冲突。

**Comment by Neightlurker** [comment]
那看来得使用护眼脚本替代插件了，感谢您的解答。

Kenshin Wang ***@***.***> 于2021年3月24日周三 下午2:25写道：

**Comment by Kenshin** [comment]
okay

没问题的话，我关闭此 issues 了 🙏

**Comment by Kenshin** [comment]
嗨，虽然这是个很古老的 Issues，还是要通知下，最新的解决方案 [请看这里 ](https://github.com/Kenshin/simpread/discussions/3699)。
