### ISSUE TITLE
https://segmentfault.com/a/1190000039187075 稍后读， 无法解析阅读模式

### ISSUE THREAD

**Issue by songtaoxy** [Kenshin/simpread#1967]

**Comment by Kenshin** [comment]
嗨，请使用 稍后读 → [ 内置解析方式](http://ksria.com/simpread/docs/#/Sync?id=%e5%86%85%e7%bd%ae%e8%a7%a3%e6%9e%90) （需高级账户）

当然，不开启这个选项的话，使用默认解析大多数页面是可以的，但少数则无法使用，如你提到的页面。

**Comment by songtaoxy** [comment]
我已经是高级用户, 但是无法开启内置解析功能


开启时, 显示会: 马上解锁权益






&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; 祝:身体健康，工作愉快，事事顺心！      
 &nbsp; &nbsp;--宋涛      
                            
               
  
      姓名:宋涛 
                电话:18519188596 
      ***@***.*** 
      地址:北京.海淀
      邮编:100094


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] https://segmentfault.com/a/1190000039187075 稍后读， 无法解析阅读模式 (#1967)





 
嗨，请使用 稍后读 →  内置解析方式 （需高级账户）
 
当然，不开启这个选项的话，使用默认解析大多数页面是可以的，但少数则无法使用，如你提到的页面。

**Comment by Kenshin** [comment]
重新授权就可以了。

重启浏览器 → 简悦 → 选项页 → 右上角 → 仅授权当前设备
