### ISSUE TITLE
如何修改布局（边距），并适配到所有站点呢？

### ISSUE THREAD

**Issue by focuszane** [Kenshin/simpread#197]
`高级设定` → `自定义样式` 里右边的 `版面布局` ：
![image](https://user-images.githubusercontent.com/30841078/34511055-f977e61c-f093-11e7-9892-0a27ea4da2ec.png)

这个只能应用于**当前用例页面**吗？我想适配到所有的网站（觉得默认的左右边距还是不够窄啊），小白求教。

**Comment by Kenshin** [comment]
搞定就好，补充几点：
- 高级样式的自定义样式是全局样式；
- 站点编辑器中也有一个自定义样式，这个只跟当前适配的站点有关；
