### ISSUE TITLE
选项稍后读打开后一片空白

### ISSUE THREAD

**Issue by weichzh** [Kenshin/simpread#1972]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge 版本 91.0.831.1 (官方内部版本) dev (64 位)**

- 简悦版本 **2.1.0**

**请描述你的问题**

简悦用了一段时间后，选项页打开如图所示不断抖动，怎么也进入不了。稍后读打开直接空白。重新安装后，正常，但经过一段时间又复现。

**截图**

![image](https://user-images.githubusercontent.com/34864632/112618751-715fae80-8e61-11eb-86c5-2864050a8903.png)

![image](https://user-images.githubusercontent.com/34864632/112618817-81778e00-8e61-11eb-8e6e-1aad53371e30.png)

![image](https://user-images.githubusercontent.com/34864632/112619026-c3a0cf80-8e61-11eb-87fb-6d782814148b.png)

选项页issues，控制台空白

![image](https://user-images.githubusercontent.com/34864632/112619122-e8954280-8e61-11eb-8787-106cf54606d6.png)

稍后读issues，控制台空白

**Comment by Kenshin** [comment]
请问，你是否使用了 **同步助手的自动同步** 方式？如果是的话，如果未开启同步助手的话，确实存在这个现象。

因为此功能相当于一个 **数据库**，帮扩展端把配置文件 读取/保存 本地，当未开启同步助手的话，因为无法读取到本地的配置文件，所以出现错误。

**Comment by weichzh** [comment]
> 请问，你是否使用了 **同步助手的自动同步** 方式？如果是的话，如果未开启同步助手的话，确实存在这个现象。
> 
> 因为此功能相当于一个 **数据库**，帮扩展端把配置文件 读取/保存 本地，当未开启同步助手的话，因为无法读取到本地的配置文件，所以出现错误。

使用了，那么该怎么解决呢？

**Comment by Kenshin** [comment]
嗨，很容易解决：
只要在 **开启浏览器前，确保 同步助手 运行** 就可以了。

PS：同步助手自启动有些问题，如 Windows 系统需要把对应的 exe 直接拖到自启动文件夹。

**Comment by OptimusPrimeme** [comment]
> 嗨，很容易解决：
> 只要在 **开启浏览器前，确保 同步助手 运行** 就可以了。
> 
> PS：同步助手自启动有些问题，如 Windows 系统需要把对应的 exe 直接拖到自启动文件夹。

同步助手已经运行了，但是在Edge 中打开稍后读还是一片空白，版本 稳定版 89.0.774.75，今天刚升级，不过也清理过缓存

**Comment by OptimusPrimeme** [comment]
> 嗨，很容易解决：
> 只要在 **开启浏览器前，确保 同步助手 运行** 就可以了。
> 
> PS：同步助手自启动有些问题，如 Windows 系统需要把对应的 exe 直接拖到自启动文件夹。

- 进入阅读模式，标注无法使用：
![image](https://user-images.githubusercontent.com/22427706/114156485-36777380-9955-11eb-86bf-72586c76c6ad.png)

- 进入稍后读，一片空白：
![image](https://user-images.githubusercontent.com/22427706/114156491-38d9cd80-9955-11eb-912b-3b240be76eec.png)

**Comment by Kenshin** [comment]
@OptimusPrimeme 

打开选项页，是否可以正常显示？

截图所示的内容，应该是某些字段未设置造成的错误。

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme
> 
> 打开选项页，是否可以正常显示？
> 
> 截图所示的内容，应该是某些字段未设置造成的错误。

能够正常进入
![image](https://user-images.githubusercontent.com/22427706/114168996-970dad00-9963-11eb-838d-dc4c37f493c1.png)

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme
> 
> 打开选项页，是否可以正常显示？
> 
> 截图所示的内容，应该是某些字段未设置造成的错误。

请问应该怎么解决呢？现在扩展选项能进入，而且我也重装了扩展3次，就是无法进入稍后读以及阅读模式，难道只能说是win10的玄学问题😥？

**Comment by Kenshin** [comment]
@OptimusPrimeme 

可能是因为你不小心「激活」了某个隐藏 Bug 造成的，你可以给我 Email 并附上配置文件。我会查看并 Fixed 这个问题并修改你的配置文件使其可以正常使用。  😅

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme
> 
> 可能是因为你不小心「激活」了某个隐藏 Bug 造成的，你可以给我 Email 并附上配置文件。我会查看并 Fixed 这个问题并修改你的配置文件使其可以正常使用。 😅

已发邮件，有劳大大了，十分感谢！！🌹

**Comment by Kenshin** [comment]
@OptimusPrimeme 

已帮你处理了，并在附上了解决方案与原因~

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme
> 
> 已帮你处理了，并在附上了解决方案与原因~

感谢感谢，都能正常使用了，辛苦了。
不过这种错误和不当的批注操作有关系吗？之前有遇到就是，在一段文本上作了批注，然后想扩大高亮的区域，没有先删掉原来的高亮，就叠了一个新的高亮上去了，这个情况好像是发生错误之前的事，不知道有没有关系。
总之，辛苦了！！👍👍👍

**Comment by Kenshin** [comment]
> 不过这种错误和不当的批注操作有关系吗？

不是很确定，简单的说，标注是一个结构，但你的标注有一项是 `null` 而非 `object` 我不是很确定如何产生的，同时如果这种方式判断的话，会让代码基本不可看...  😅 

> 然后想扩大高亮的区域，没有先删掉原来的高亮，就叠了一个新的高亮上去了

应该不是，就是在保存的时候，出现了未知情况导致的。

***

PS：请问你有使用同步助手吗？或者有多个浏览器同步配置文件的操作？

**Comment by OptimusPrimeme** [comment]
> > 不过这种错误和不当的批注操作有关系吗？
> 
> 不是很确定，简单的说，标注是一个结构，但你的标注有一项是 `null` 而非 `object` 我不是很确定如何产生的，同时如果这种方式判断的话，会让代码基本不可看... 😅
> 
> > 然后想扩大高亮的区域，没有先删掉原来的高亮，就叠了一个新的高亮上去了
> 
> 应该不是，就是在保存的时候，出现了未知情况导致的。
> 
> PS：请问你有使用同步助手吗？或者有多个浏览器同步配置文件的操作？

同步助手一直在用，浏览器基本只用Edge，在别的浏览器上同步配置文件也是很久之前的事了。

**Comment by Kenshin** [comment]
> 同步助手一直在用，浏览器基本只用Edge，在别的浏览器上同步配置文件也是很久之前的事了。

okay 再留意下是否还能复现这个问题。

**Comment by chanity256** [comment]
**请说明发生问题的环境**

- 操作系统 **Mac OS 11.4**
- 浏览器版本 **Version 90.0.818.49 (Official build) (64-bit)**
- 简悦版本 **2.2.0.520**

**请描述你的问题**

1.稍后读打开直接空白。重新安装也没用，打开同样是空白。

2.使用阅读模式时，即使开启标注功能，依旧无法标注。


**截图**
* 稍后读空白

<img width="1440" alt="Screen Shot 2021-07-22 at 09 58 43" src="https://user-images.githubusercontent.com/71577436/126580784-5a1f2fdf-c13e-494b-be2e-b3dd44afcb6f.png">



* 阅读模式无法标注
<img width="1440" alt="Screen Shot 2021-07-22 at 09 59 30" src="https://user-images.githubusercontent.com/71577436/126580820-5efe49c4-22d9-4859-8457-ad7506f8abff.png">

**Comment by Kenshin** [comment]
@chanity256 

嗨，重新安装也不行？应该不会的，另外看截图应该是 Edge 浏览器吧？
PS：最后一个截图看起来并不是重新安装后的效果。

**Comment by chanity256** [comment]
是Edge浏览器。重新安装后也不行，稍后读还是一片白色。阅读模式没办法开启标注模式，不管怎么点击都是灰色的
<img width="183" alt="Screen Shot 2021-07-22 at 15 12 01" src="https://user-images.githubusercontent.com/71577436/126602013-3a17275f-2f88-4495-bf6f-9fe0c0b91523.png">

**Comment by Kenshin** [comment]
@chanity256 

很奇怪的问题，我看你的扩展安装了挺多的，你可以这么做：

1. 删除简悦
2. 重启浏览器
3. 安装简悦
4. 在隐身模式下，仅启用简悦
5. 看看选项页是否可以打开？

**Comment by Kenshin** [comment]
嗨，各位。

同步助手 1.2.0 发布了，内含 `simpread_config.json` 修复功能，以下是这个功能的细节。

> 已运行 1.2.0 版同步助手，可直接访问此地址 http://localhost:7026/database/fixed
> 
> 根据提示修复即可，关于此功能的详细说明 👉 [请看这里](https://simpread.pro/docs/#/数据中心?id=修复配置文件)。

***

> 以下是同步助手 1.2.0 的其它功能。

## 更新日志

[Notion Site](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#86c339b25b15455b9cc043044891351f)

## 🗄 [数据中心](https://simpread.pro/docs/#/数据中心)

内置了一组针对 `simpread_config.json` 的优化、修复、整理、统计工具。

### 地址

http://localhost:7026/database

### 预览

![image](https://user-images.githubusercontent.com/81074/220891702-b15b7551-205e-480d-aedd-9cf72de7f296.png)

### 模块

- [历史记录](https://simpread.pro/docs/#/数据中心?id=历史记录)

- [修复配置文件](https://simpread.pro/docs/#/数据中心?id=修复配置文件)

- [清理配置文件](https://simpread.pro/docs/#/数据中心?id=清理配置文件)

- [查找重复数据](https://simpread.pro/docs/#/数据中心?id=查找重复数据)

- [数据统计](https://simpread.pro/docs/#/数据中心?id=数据统计)

**Comment by Kenshin** [comment]
### 补一个视频操作

https://user-images.githubusercontent.com/81074/221127248-56a5591b-c704-41f0-9f7c-be270f56ab31.mp4
