### ISSUE TITLE
文章结尾出现了不该出现的字符

### ISSUE THREAD

**Issue by mariohide** [Kenshin/simpread#1975]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://cn.reuters.com/article/xinjiang-cotton-nike-adidas-0326-fri-idCNKBS2BI045>

**请描述你的问题**

文章结尾出现了不该出现的字符

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/20430813/112717323-d03b2b80-8f26-11eb-8765-41a5c562dc20.png)

**Comment by Kenshin** [comment]
emm...

我测试了下，没有截图的问题。请在 **隐私模式下，仅启用简悦** 试试。

**Comment by mariohide** [comment]
感谢回复！
我再打开也没问题了...可能是其他什么扩展程序导致的吧...

**Comment by Kenshin** [comment]
okay 没问题就好~
