### ISSUE TITLE
微信适配的一些问题

### ISSUE THREAD

**Issue by fansmaker** [Kenshin/simpread#198]
公众号文章适配的挺好，问题出在了在微信后台也启动阅读模式了。因为主域名是一样的，才造成的问题。

**Comment by Kenshin** [comment]
的确有这样的问题，你可以通过添加 url 通配符的方式将后台不需要的或者把整个 name 添加到黑名单里。

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
