### ISSUE TITLE
【Bug】无法生成分享链接，且无法访问已分享的链接

### ISSUE THREAD

**Issue by liamtao** [Kenshin/simpread#1980]
**系统环境**

- 操作系统 **MacOS 11.2.2**
- 浏览器版本 **Chrome 89.0.4389.90（正式版本） (x86_64)**
- 简悦版本 **2.1**

**问题描述**

1. 对已标注的文章，在稍后读中无法生成共享链接。提示停留在「正在生成分享链接」。不同时间反复尝试，结果一样。
2. 对于以前已生成的共享链接，无法访问。提示长时间停留在「小憩片刻，马上就好」，最后显示「哦，服务器开小差了，请稍后再试！」。比如该篇文章：https://simpread.pro/s/QWKLtRcg

**截图**
问题1
<img width="784" alt="Xnip2021-03-30_08-44-11" src="https://user-images.githubusercontent.com/9836684/112916922-20d3a400-9134-11eb-9d4f-29e0038c0730.png">
<img width="835" alt="Xnip2021-03-30_08-44-42" src="https://user-images.githubusercontent.com/9836684/112916946-31841a00-9134-11eb-86a7-02c24a2c82ab.png">

问题2
<img width="327" alt="Xnip2021-03-30_08-46-42" src="https://user-images.githubusercontent.com/9836684/112917054-77d97900-9134-11eb-8ff9-fb2a2524e78e.png">
<img width="488" alt="Xnip2021-03-30_08-46-31" src="https://user-images.githubusercontent.com/9836684/112917056-7a3bd300-9134-11eb-88a3-340daa3c8ce0.png">

**Comment by Kenshin** [comment]
谢谢反馈，因为服务器的问题导致此功能暂时「下线」，修复后我会在这里通知你。

**Comment by jueshikuangshen** [comment]
请问大佬，分享功能啥时候恢复呀

**Comment by Kenshin** [comment]
> 请问大佬，分享功能啥时候恢复呀

可能暂时都无法恢复了（不是技术问题），请问你需要此功能的需求是什么？

**Comment by jueshikuangshen** [comment]
> > 请问大佬，分享功能啥时候恢复呀
> 
> 可能暂时都无法恢复了（不是技术问题），请问你需要此功能的需求是什么？

我目前在使用一款笔记软件， 想把简悦作为一个整合文章的知识库，给笔记做一些背景补充。如果有分享功能，我可以把某个合辑的链接贴到对应的笔记位置，每次看笔记都会引发新的思考，搜索更多的文章，然后整合到合辑中，对扩展知识面有很大帮助。

当然也可以定制导出，作成知识卡片来滚雪球，但有些专业文章一篇一篇地提取重点可能会断章取义，而且操作不太简便。

最后，我很担心原文被删除，这事蛮常见的，如果能越过原文发布的平台，笔记直接和简悦链接，我会更有安全感！

**Comment by Kenshin** [comment]
嗨，你可以使用 `http://localhost:7026/reading/<合辑的名字>`  的方式来获取内部永久链接。

比如下图就是一个合辑的内容

![image](https://user-images.githubusercontent.com/81074/127727462-f317c9c2-3b34-4552-9012-6d7ffd4b487d.png)

然后使用导出 HTML（或 离线 HTML）就会生成下图的文件

![image](https://user-images.githubusercontent.com/81074/127727486-f070247d-0179-4aa4-89ce-e7d1aa87eccd.png)

![image](https://user-images.githubusercontent.com/81074/127727491-1faca595-00d4-4b69-aa99-9f8e30b75052.png)

然后你访问`http://localhost:7026/reading/<合辑的名字>`  就可以了。

***

实现此方式的前提：

> 需要安装同步并运行同步助手

此方式比分享页的优势

> 因为是内部链接，真正能做到永远存在。

此方式也可以变为永久链接，如 `https://simpread.pro/@<id>/reading/<合辑的名字>`，但同样需要配置。

***

再引申下，上述方式不仅适用于合辑，任意标签，[多种布局](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80) 均支持。

**Comment by jueshikuangshen** [comment]
> 嗨，你可以使用 `http://localhost:7026/reading/<合辑的名字>` 的方式来获取内部永久链接。
> 
> 比如下图就是一个合辑的内容
> 
> ![image](https://user-images.githubusercontent.com/81074/127727462-f317c9c2-3b34-4552-9012-6d7ffd4b487d.png)
> 
> 然后使用导出 HTML（或 离线 HTML）就会生成下图的文件
> 
> ![image](https://user-images.githubusercontent.com/81074/127727486-f070247d-0179-4aa4-89ce-e7d1aa87eccd.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/127727491-1faca595-00d4-4b69-aa99-9f8e30b75052.png)
> 
> 然后你访问`http://localhost:7026/reading/<合辑的名字>` 就可以了。
> 
> 实现此方式的前提：
> 
> > 需要安装同步并运行同步助手
> 
> 此方式比分享页的优势
> 
> > 因为是内部链接，真正能做到永远存在。
> 
> 此方式也可以变为永久链接，如 `https://simpread.pro/@<id>/reading/<合辑的名字>`，但同样需要配置。
> 
> 再引申下，上述方式不仅适用于合辑，任意标签，[多种布局](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80) 均支持。



感谢回答，点击导出没反应，麻烦您看看哪出问题啦？
![截图_20210731122143](https://user-images.githubusercontent.com/47046461/127728532-9b748af9-afda-4d1d-8654-64e15cdcef86.gif)

**Comment by Kenshin** [comment]
> 感谢回答，点击导出没反应，麻烦您看看哪出问题啦？

造成这个问题的情况很多，你可以加一篇稍后读，然后在测试看看能否使用？

**Comment by jueshikuangshen** [comment]
> > 感谢回答，点击导出没反应，麻烦您看看哪出问题啦？
> 
> 造成这个问题的情况很多，你可以加一篇稍后读，然后在测试看看能否使用？

不行啊，点了还是没反应，还有其他可能吗？

**Comment by Kenshin** [comment]
> 不行啊，点了还是没反应，还有其他可能吗？

确实很奇怪，不应该出现这个情况。你可以这样测试：

1. 导出配置文件
2. 重置当前配置文件（下图）

![image](https://user-images.githubusercontent.com/81074/127736952-09828b76-2531-4ec4-ab76-2f9a304fcbed.png)

然后什么都不要更改，加入一篇稍后读，看看能否导出？

**Comment by jueshikuangshen** [comment]
> > 不行啊，点了还是没反应，还有其他可能吗？
> 
> 确实很奇怪，不应该出现这个情况。你可以这样测试：
> 
> 1. 导出配置文件
> 2. 重置当前配置文件（下图）
> 
> ![image](https://user-images.githubusercontent.com/81074/127736952-09828b76-2531-4ec4-ab76-2f9a304fcbed.png)
> 
> 然后什么都不要更改，加入一篇稍后读，看看能否导出？

不好意思忘说了，除了合辑其他的都能正常导出，重置配置文件后用不了合辑的功能，有其他测试的方法吗

**Comment by jueshikuangshen** [comment]
> > 不行啊，点了还是没反应，还有其他可能吗？
> 
> 确实很奇怪，不应该出现这个情况。你可以这样测试：
> 
> 1. 导出配置文件
> 2. 重置当前配置文件（下图）
> 
> ![image](https://user-images.githubusercontent.com/81074/127736952-09828b76-2531-4ec4-ab76-2f9a304fcbed.png)
> 
> 然后什么都不要更改，加入一篇稍后读，看看能否导出？

报告大佬，配置文件重新导入之后，合辑功能恢复了，太神奇了，感谢！

**Comment by Kenshin** [comment]
> 报告大佬，配置文件重新导入之后，合辑功能恢复了，太神奇了，感谢！

emmm 搞定就好，可能是隐形 Bug 或其它什么造成的。因为没法调试，所以无法确定。😂

既然没问题的话，我关闭此 Issues 了。

**Comment by Kenshin** [comment]
还有个小提示：

不要在无关的 Issues 提问，这样会「打扰」到提问者（他会收到邮件）而这个问题跟这个 Issues 无关就会打扰到提问者。

你可以随便新建 Issues，没关系的。

**Comment by Kenshin** [comment]
PPS：太不容易解决这个问题了，方便的话，请在 [Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll?hl=zh-CN&authuser=0) 帮忙五星好评 + 评论吧。💪

PS：已评分的话，请忽略~
