### ISSUE TITLE
导出到语雀的文字没有了颜色标志

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#1986]
下图分别为导出到印象笔记和语雀的效果。
想问下，羽雀是不支持颜色吗？
纠结这个的原因是在于 
导出语雀，速度非常快，可没有颜色
导出印象笔记，速度稍慢，但是有颜色
![Image](https://i.imgur.com/U90i6BZ.jpg)
![Image](https://i.imgur.com/Fxq5nck.jpg)

**Comment by Kenshin** [comment]
嗨，导入到语雀的是 Markdown 自然没有颜色了。  😅
