### ISSUE TITLE
一个小想法

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#1987]
有这么一个场景 假如我看了十篇文章，并且为其中50段文字都打上了“摘要”的标签，但是我后面如果想要聚合所有“摘要”片段呢**（在写作或者写论文 这个场景其实非常常见）**

在做标签的时候   有没有可能把所有属于 该标签下的摘录片段集合在一起？
感觉这样更适合做知识管理
目前的话  含有某个标签的文段其实是分散在各个不同的文章里的

![image](https://user-images.githubusercontent.com/38575961/113091981-a97b3e80-921f-11eb-93e1-d1dc4f9234e3.png)

**Comment by Kenshin** [comment]
嗨，谢谢建议，会考虑的。

目前的解决方式是：将 **摘要** 加入到合辑中，就能在一页里面查看（包括：导出）。（当然目前这么做还有些繁琐，会考虑更好的解决方案。

***

按照你的思路，集中显示的内容，你想以什么形式导出？

- 纯文本
- Markdown

如果是后者的话，你希望的结构是什么？（或者说，是否包含这些内容对应的 URL / Title 之类的？

建议扩展下，直接说你希望得到的结果。

**Comment by enron2014** [comment]
导出的形式想以markdown形式导出 ，如果可以包含对应内容的url以及title会更好
如果只以纯文本导出 不可取 因为有些标记是对图片的标记和加标签

我的理解哈：
标签是对 摘录的片段加的，可是在稍后读里面 点击标签  却是以 文章为单位的，这样其实有些反习惯

目前合辑来解决我上述的那个场景没有问题，但是如果标记了10篇文章，30个“摘要”片段，那么一个一个去 选择，然后加入合辑，感觉还是挺费时费力~~~

简悦好好用，五星好评，希望可以越来越好

**Comment by Kenshin** [comment]
收到你的诉求了，我会好好考虑的。

P.S. 确实目前合辑的使用方式比较「繁琐」。

也谢谢对简悦的喜爱。😄

**Comment by Kenshin** [comment]
哦，忘记更正一个地方了：

> 可是在稍后读里面 点击标签 却是以 文章为单位的，这样其实有些反习惯

列表栏（第二栏）得到的标签结果也包含了标注的标签，假设：有个 `a` 的标签仅作用在标注上，也能通过第一栏的看到这个标签 `a` 

只是因为列表栏的展示受限，所以没有显示出来而已，下个版本会有更好的解决方式。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
