### ISSUE TITLE
扩展 支持沉浸式阅读网页吗？

### ISSUE THREAD

**Issue by clfsoft** [Kenshin/simpread#199]
基本场景
1.普通的阅读一个网页模式
2.读网络小说（连续几百页的）

一个网页被人为分成好几个页面，不说把网页自动拼接起来
  至少，可以有选项自动预先下载下一个或者几个页面。
 这样才是沉浸式的吧。
现在阅读模式 里头显示全文完，有下一页的连接，
然后点击下一页连接进入的还是正常的页面，至少阅读模式的下一页自动进入阅读模式啊。
（，为了几个临时的网站，添加自动阅读模式设定这个也麻烦的）

**Comment by clfsoft** [comment]
具体网站
![snipaste_2018-01-04_03-50-11](https://user-images.githubusercontent.com/1608414/34537249-306a2bd6-f10b-11e7-82a0-aca72a267dcb.png)
http://www.piaotian.com/html/7/7587/4473767.html

**Comment by Kenshin** [comment]
如果只想阅读小说的话，我建议使用另外一款 油猴脚本 https://greasyfork.org/zh-CN/scripts/292-my-novel-reader

对于绝大多数正常的、需要沉浸式阅读的页面都没有分页诉求，除了论坛类页面。
至于你说的自动拼接页面的功能，我会考虑此功能，但需求场景太少了。

**Comment by clfsoft** [comment]
多谢了.推荐的脚本够用了

**Comment by Kenshin** [comment]
好用就好～
在其它方面，简悦更胜任。
