### ISSUE TITLE
[建议] 标注功能的工具栏是否可以减少动画

### ISSUE THREAD

**Issue by esr2587758** [Kenshin/simpread#1990]
在专注阅读划词的时候，标注功能的动画效果（跟随，渐隐）太多了。
干扰阅读。谢谢。

**Comment by Kenshin** [comment]
下个版本修复此问题。

**Comment by esr2587758** [comment]
谢谢，你的快速反馈~ 如果有喜欢的效果的，可以留个配置给他们。

**Comment by Kenshin** [comment]
@esr2587758 

会有选项的，但默认为关闭状态。  😀  
新版发布后，我会在这里通知你。

**Comment by Katemic** [comment]
其他地方如 偏好设置 里面，能不能也添加取消动画效果的功能呢。 或者在动画上面优化一下？  edge+mbp 上用总感觉卡卡的

**Comment by Kenshin** [comment]
嗨，此功能已经有了。

选项页 → 高级设定 → 标注，看下图

![image](https://user-images.githubusercontent.com/81074/127483337-ccf1493c-79e9-486f-b5af-62c0e200b9a3.png)

***

2.1.0 → 2.2.0 里面有不少 Issues 都已被 Fixed 了，但有些忘记 Close 了。
