### ISSUE TITLE
一直提示 请在简悦-同步助手中开启此选项 是咋回事

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#1993]
![image](https://user-images.githubusercontent.com/38575961/113392054-1846cc00-93c7-11eb-9a3b-c73e8a748da8.png)

搜寻过类似的帖子 但是试了下还是无果

**Comment by Kenshin** [comment]
嗨，感觉是不是在标注时出现的问题？如果是的话，估计是你开了某些自动同步的功能导致。

看看 `选项页 → 高级设定 → 标注 & 稍后读` 里面是否开启了跟同步助手有关的功能？

另外，也需要运行同步助手。

**Comment by xulei-shl** [comment]
简悦的高级帐号同步的体验实在是太恐怖了。
 - 要么是浏览器一直弹出如题主所述的问题，设置里的开启的功能根本没有进行，
  - 比如，设置了剪藏自动保存到本地html，但没有
  - 手动在桌面端点保存到离线HTML，客户端又提示当前帐号不是高级帐号，
  - 但鬼知道怎么回事，明明已经绑定，也确实是高级帐号了👿️
但问题是所有的权限设置根本没变过，界面也确实显示是高级帐号绑定成功，第一次好不容易折腾成功了，但第二天再使用就又陷入上述的死循环

**Comment by Kenshin** [comment]
@xulei-shl 

> 但问题是所有的权限设置根本没变过，界面也确实显示是高级帐号绑定成功，第一次好不容易折腾成功了，但第二天再使用就又陷入上述的死循环

确定没有改过任何（系统 /  浏览器）配置？

看你提示的现象，基本上是两个问题：

- （无故）高级账户失效
- 当开启自动同步后，某些功能设置后无效。

建议看看 https://github.com/Kenshin/simpread/discussions/1567 引起的，不知道你具体的环境是什么？（之前有反馈过 Win 下面的一些杀毒类的 App 会修改（或阻止）简悦保存配置文件。

或 https://github.com/Kenshin/simpread/discussions/1692 https://github.com/Kenshin/simpread/discussions/1700

***

多说几句：

要知道如果真的是 Bug ，我自己或其他人早就发现了，不会留到现在。所以，一般各种奇怪的问题都是自身操作造成的。

简悦没有账户系统，也没有保存用户的数据，所以如果要实现自动同步的话，最好首先自己理解简悦的自动同步机制，建议看下 https://github.com/Kenshin/simpread/issues/1994#issuecomment-812802326 对应的内容。

当你理解这个机制后，99.999% 的问题都不会存在了。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

当未开启同步助手时，仍可以使用简悦的最基本功能以及不需要使用同步助手的功能，同时会有下面的提示

![image](https://user-images.githubusercontent.com/81074/121986598-5f8b0900-cdc9-11eb-935a-3f4feef7e1fb.png)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
