### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by zhang1231231231** [Kenshin/simpread#1996]
发生问题的地址: <http://www.360doc.com/content/18/0517/06/37063871_754580980.shtml>

**Comment by Kenshin** [comment]
嗨，这类页面因为会涉及版权问题，所以简悦不会主动适配。
你可以使用站点编辑器自行适配它。

PS：这个页面因为全部都是图片，所以正文提取失败。其它页面是可以自动捕捉到正文的。
