### ISSUE TITLE
网站代码块注释丢失

### ISSUE THREAD

**Issue by cesaryuan** [Kenshin/simpread#1998]
问题描述：在该网站进入阅读模式后，原来的代码块的注释被删除了

问题网站：https://getquicker.net/KC/Help/Doc/webview2

重现步骤：在该网站进入阅读模式

![image](https://user-images.githubusercontent.com/35998162/113498355-c759e380-953e-11eb-80bb-bc71c57c6695.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
