### ISSUE TITLE
网站补充：雪球 xueqiu.com

### ISSUE THREAD

**Issue by Ouxxxxxjoe** [Kenshin/simpread#2]

**Comment by Kenshin** [comment]
okay，稍后我（下午之前）会增加，然后关闭这个 `issues` 后， 通过 [这个方式](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%85%B3%E4%BA%8E%E6%9B%B4%E6%96%B0) 更新。

**Comment by Kenshin** [comment]
https://xueqiu.com 已加，请通过上一条更新。
