### ISSUE TITLE
希望能适配一下知乎

### ISSUE THREAD

**Issue by cstarpc** [Kenshin/simpread#20]
RT，希望能适配一下知乎，毕竟现在知乎用户量还是挺大的~

**Comment by Kenshin** [comment]
知乎已经适配了，但有些问题。
像知乎这种类似论坛一段一段但又不是出自同一用户的内容放到一起不是太友好，以后会有专门适配这种类型的页面主题。

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，改善了 知乎的适配规则。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)

但是暂时没有实现 `专门适配` 的功能，下个版本将会增加此功能。

**Comment by cstarpc** [comment]
感谢适配，发现在知乎页面上使用简悦还有个问题，具体如下：
打开一个具体的问题页面，显示所有回答（所有回答均已展开）以后，聚焦模式和阅读模式均只能对第一个（不一定是赞同数最多的答案，就是排在第一个显示的答案）答案正确识别显示，后面的答案即便鼠标手动移动到该答案处都无法进入聚焦和阅读。估计要好好适配难度非常大。

**Comment by Kenshin** [comment]
目前是这个情况，同时这也是我说的 `专门适配` 问题。

比如：按照你说的情况，全部的页面的答案都分属不同的人，如果把它们的答案放到一起，并且也不显示是谁说的，自然不对。

所以，知乎问答页本质还是属于 `论坛/贴吧` 这种结构，而这类结构需要特殊适配才行，不能单纯的把内容都放一起显示。

**Comment by PuRonglong** [comment]
@Kenshin 还有个问题，gif 图片会失效

**Comment by Kenshin** [comment]
@PuRonglong 
1. 最好能给我一个 url
2. `1.0.2` 版本已经改善了知乎这类论坛型的页面显示结构，如下图：
    ![](http://ojec5ddd5.bkt.clouddn.com/multiple%20page.png?2017-08-07)

`1.0.2` 为测试版，将会跟 `1.0.3` 在本周内发布。

**Comment by PuRonglong** [comment]
@Kenshin URL在这里：
https://www.zhihu.com/question/64466059

**Comment by Kenshin** [comment]
@PuRonglong 
`1.0.3` 已经没有 `图片无法显示的问题` 了，如图：
![image](https://user-images.githubusercontent.com/81074/29801462-59cc12fa-8ca2-11e7-9784-5fc79cfb3fcb.png)

但 `gif 无法播放的问题` 仍旧存在，这是因为知乎用了静态图片替换了 gif 导致，我看看能否解决。（ 估计有困难... ）

关于测试版无法使用问题的解决办法可以 → [看这里](https://github.com/Kenshin/simpread/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97%EF%BC%88-%E6%93%8D%E4%BD%9C%E6%8C%87%E5%BC%95-%EF%BC%89#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85)

如果能等待的话，本周就会将 1.0.3 推送到 Webstore。

**Comment by PuRonglong** [comment]
@Kenshin 谢谢回复，GIF不好解决可以放放，然后给的测试版无法使用的链接里：
![image](https://user-images.githubusercontent.com/8725006/29801661-6cb4e896-8ca3-11e7-9a15-8fd3deff7c11.png)
我是按照这个方法下载的.crx文件然后拖拽进扩展程序里面的，但是会收到如下提示：
![image](https://user-images.githubusercontent.com/8725006/29801693-9681ccf2-8ca3-11e7-95f4-b5d33b2ed468.png)
而在扩展程序的页面里，这个手动添加的扩展程序也是无法选择启用，是灰色的，如下：
![image](https://user-images.githubusercontent.com/8725006/29801743-d48dc9ba-8ca3-11e7-8a9b-1b482f51c954.png)
我的chrome版本是“版本 60.0.3112.101（正式版本） （64 位）“。所以上一个回复里给出了chrome的截图，我再试试别的方法吧，如果不行就还是等正式版更新好了。最后，再次谢谢回复。

**Comment by Kenshin** [comment]
@PuRonglong 
没关系~

- `Windows` 下面的确会出现这种情况，但只有极个别有... 😷  我也不清楚是什么问题...
- `gif 的问题`  如果方便搞定的话，会跟 `1.0.3` 一起发布，否则只能先这样了。

**Comment by Kenshin** [comment]
@PuRonglong @cstarpc 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

此 issues 将关闭~
