### ISSUE TITLE
增加某些网站对"阅读模式"和”聚焦模式“不反应名单

### ISSUE THREAD

**Issue by Zeroto521** [Kenshin/simpread#200]
## 问题
在某些网站需要进行大量的文字输入~~非文本框处~~，这时候频繁出现的**阅读模式**和**聚焦模式**提示很讨厌，在偶尔点击鼠标就自动进入这，_(:3」∠)_
- - - - - 
所有想要增加个不反应名单。

ps：**白名单**貌似没用耶，感觉

**Comment by Kenshin** [comment]
最近在休假，回复并不会太及时。😌

请告知详细的提示说明，这里只能猜测你的问题～

未适配的页面并不会出现任何的提示，除非你（误触）使用了快捷键。

适配页面出现的话，应该是页面结构改变导致的，这就需要站点编辑器了。

**Comment by Zeroto521** [comment]
就是在敲键盘的时候出现的，比如这个[zty](http://zty.pe/)
咱可是键盘党，`vimium`的`i`**插入模式**在这个时候就很有用，禁止vim快捷键。
可以参考这个，搞个这样的**快捷键**，或是白名单。
嗯~感觉还是快捷键方式更好吧。

**Comment by Kenshin** [comment]
@Zeroto521 
我觉得应该叫做「禁用」，即 **禁止简悦加载到当前页面** 的功能比较好，现在的黑名单还是要监听键盘操作，所以出现了你说的情况~

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，

新增加了 `黑名单`，加入此的网址，将不会加载简悦的代码。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
