### ISSUE TITLE
电脑已安装启动同步助手  但是浏览器始终不能识别到  

### ISSUE THREAD

**Issue by lz347396004** [Kenshin/simpread#2000]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**Comment by Kenshin** [comment]
看看是否是 https://github.com/Kenshin/simpread/discussions/1567 引起的。

**Comment by lz347396004** [comment]
> 看看是否是 #1567 引起的。

并不是这个问题引起的 。 现在我已经换上最新的版本 ，还是无法解决问题。

**Comment by Kenshin** [comment]
嗨，建议把你操作步骤，相关系统的信息截图给我，方便我 Debug。

另外，不知道是否安装了某些防火墙类的应用，也试着关闭下（正常情况下并不需要这么操作）
