### ISSUE TITLE
少数派在生成阅读模式后会包含注脚时的内容。

### ISSUE THREAD

**Issue by haozi2333** [Kenshin/simpread#2002]
1. 希望在涉及引用的时候不用加载进去，在选中的时候并不想选中引用中的内容

![image](https://user-images.githubusercontent.com/16058531/113549101-60622a80-9623-11eb-85c9-8739ea80e3ea.png)

2. 希望已经在稍后读的网页可以显示一个标记

**Comment by Kenshin** [comment]
嗨，谢谢建议。

> 希望在涉及引用的时候不用加载进去，在选中的时候并不想选中引用中的内容

这个应该不太会实现，因为「有可能会有人说：我希望加入这个方式 XXXX」。所以最好的方式是：你给我 URL 我看到底是什么问题。

> 希望已经在稍后读的网页可以显示一个标记

可以考虑，但这么做的目的？加入到稍后读的页面，在进入阅读模式时，自然会有侧栏出现；在不进入阅读模式时，添加到阅读模式时，会有「已添加过」的提示。

当然，我个人也倾向于有这么个功能，但一直觉得并没有太大的意义。  😅

**Comment by haozi2333** [comment]
https://sspai.com/post/65556
![image](https://user-images.githubusercontent.com/16058531/113569146-8ea43200-9644-11eb-9497-0754c5e280de.png)
![image](https://user-images.githubusercontent.com/16058531/113569251-bdbaa380-9644-11eb-9ef5-fe72dc17b1a0.png)
在标记文字的时候，引用大多都是文字来源，引用中的文字并没有太大用处，所以希望解析的时候剔除这种形式的引用


信息源推送的文章有时会重复，经常同一篇文章重复添加进稍后读，我添加文章进稍后读的习惯是右键——>简悦——>将当前文章添加进稍后读，觉得有些繁琐，又或者还有其他方式添加吗

**Comment by Kenshin** [comment]
嗨~

> 第一个问题

了解了，会想办法解决这个情况。

> 第二个问题
 
加入稍后读支持快捷键（与更高级别的快捷键）位置在：选项页 → 高级设定 → 稍后读 以及 `chrome://extensions/shortcuts`

**Comment by Kenshin** [comment]
补充下：你试试将下面的内容加入到站点适配器里面，位置：进入阅读模式 → 右下角浮动设置栏 → 动作 → 站点适配器

```
<sup>
```

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
