### ISSUE TITLE
无法和彩云小译同时工作

### ISSUE THREAD

**Issue by yeast0326** [Kenshin/simpread#2004]
简悦版本2.1.0
Chrome版本89.0.4389.114
在彩云小译插件启动后无法在阅读模式中出现中英对照文字，仅有英文原文
在简悦启动后点击彩云小译插件无法将阅读模式内文字更改为中英对照
不知可否修改使二者可以兼容？即在阅读模式下可以使用彩云小译的中英对照网页翻译功能
不胜感激

**Comment by Kenshin** [comment]
嗨，目前确实有这样的问题存在，暂时也「无解」，你可以看看 https://github.com/Kenshin/simpread/discussions/1561 这篇文章的内容。

**Comment by Kenshin** [comment]
嗨，你可以看这个解决方案 https://github.com/Kenshin/simpread/discussions/3182

***

另外，[全文翻译](https://github.com/Kenshin/simpread/discussions/1593) 更新到了 1.1.0 增加了下面的新功能：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [段落翻译](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

***

我关闭这个 Issues 了，有任何问题可随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，划词翻译 1.0.0 版发布了，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4
