### ISSUE TITLE
我已经绑定了高级账户，但是打开稍后读后有些地方仍是被锁状态，在与同步助手链接的时候也是灰色

### ISSUE THREAD

**Issue by castlelong** [Kenshin/simpread#2006]
![image](https://user-images.githubusercontent.com/26018270/113807488-bfbf5800-9753-11eb-8a38-3292479990ae.png)
![image](https://user-images.githubusercontent.com/26018270/113807509-c9e15680-9753-11eb-8092-a8c00c03f5c9.png)

**Comment by Kenshin** [comment]
重启浏览器后，[重新授权](https://github.com/Kenshin/simpread/discussions/1576)

另外，看看是否是 https://github.com/Kenshin/simpread/discussions/1567 引起的？
