### ISSUE TITLE
希望增加 保存到为知笔记 功能

### ISSUE THREAD

**Issue by xiang578** [Kenshin/simpread#201]
我觉得思路可以参考这个 http://note.wiz.cn/url2wiz

**Comment by Kenshin** [comment]
不错，我会研究下。
感谢反馈与建议！

**Comment by Kenshin** [comment]
这几天在休假，今天看了下，你给出的服务是 为知 自己提供的，而它并未提供 API 所以无法参照它的方式。

另外，我没有理解你的意思，为知抓取的页面类似 onenote / evernote 的处理方式，为什么你还需要用阅读模式呢？

比如下图
![image](https://user-images.githubusercontent.com/81074/34859061-f3b2937e-f78e-11e7-957f-a9e310dc21b4.png)

这是经过为知整理后的页面，如果需要阅读模式的话，跳到原文再使用简悦就可以了。

**Comment by xiang578** [comment]
后来发现我想错，抱歉

**Comment by Kenshin** [comment]
okay 没关系，没问题的话，我关闭此 issues 了。  😀
