### ISSUE TITLE
能否把稍后读的阅读模式设为离线html页面？

### ISSUE THREAD

**Issue by elastical** [Kenshin/simpread#2013]
现在的稍后读阅读模式是读取原文链接再打开网页，但部分网站（比如知网的在线阅读论文）的链接是无法再次打开的，会提示登录，但我这边不是用账号登陆而是用校园网直接登入，这种情况阅读模式就完全无法使用了。希望能加一个打开相应离线html页面

**Comment by elastical** [comment]
另外反馈个小问题，在知网的html阅读模式下使用简悦已经很好了，唯一的问题就是每次标题都是读取成了“全文阅读---xml全文阅读---中国知网”，而不是页面中存在的文章标题，大概是没有适配，虽然问题不大，但大概只是修改下模板的问题？所以还是希望有时间能优化一下

**Comment by elastical** [comment]
> 现在的稍后读阅读模式是读取原文链接再打开网页，但部分网站（比如知网的在线阅读论文）的链接是无法再次打开的，会提示登录，但我这边不是用账号登陆而是用校园网直接登入，这种情况阅读模式就完全无法使用了。希望能加一个打开相应离线html页面

测试了一下，连校园网可以打开之前的页面，但不联网不行，还是希望稍后读能支持下离线html吧

**Comment by Kenshin** [comment]
> 另外反馈个小问题，在知网的html阅读模式下使用简悦已经很好了，唯一的问题就是每次标题都是读取成了“全文阅读---xml全文阅读---中国知网”，而不是页面中存在的文章标题，大概是没有适配，虽然问题不大，但大概只是修改下模板的问题？所以还是希望有时间能优化一下

可以优化下，不过.... 知网我应该是无法访问的吧？ 😂 

***

> 现在的稍后读阅读模式是读取原文链接再打开网页，但部分网站（比如知网的在线阅读论文）的链接是无法再次打开的，会提示登录，但我这边不是用账号登陆而是用校园网直接登入，这种情况阅读模式就完全无法使用了。希望能加一个打开相应离线html页面

嗨，新版会有更好的解决方案。

**Comment by elastical** [comment]
> > 另外反馈个小问题，在知网的html阅读模式下使用简悦已经很好了，唯一的问题就是每次标题都是读取成了“全文阅读---xml全文阅读---中国知网”，而不是页面中存在的文章标题，大概是没有适配，虽然问题不大，但大概只是修改下模板的问题？所以还是希望有时间能优化一下
> 
> 可以优化下，不过.... 知网我应该是无法访问的吧？ 😂
> 
> > 现在的稍后读阅读模式是读取原文链接再打开网页，但部分网站（比如知网的在线阅读论文）的链接是无法再次打开的，会提示登录，但我这边不是用账号登陆而是用校园网直接登入，这种情况阅读模式就完全无法使用了。希望能加一个打开相应离线html页面
> 
> 嗨，新版会有更好的解决方案。

好的，感谢😂

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
