### ISSUE TITLE
关于稍后读的两个优化

### ISSUE THREAD

**Issue by OptimusPrimeme** [Kenshin/simpread#2014]
- 当备注文字有一定长度且是一整段没有换行的时候，悬浮框没有对文字进行折叠，而是直接在一行里展示，这样就需要滚动条展示，个人感觉体验和观感有点不佳
![image](https://user-images.githubusercontent.com/22427706/114264002-fc70a500-9a1a-11eb-9b04-9037a9664518.png)
- 在很多文档类型的页面，经常有页面内部跳转，比如标题什么的，从不同标题或者不同位置进入同一页面的时候，简悦并没有当作是同一个页面，然后标注高亮就没展示出来。

希望简悦越来越好！👏

**Comment by Kenshin** [comment]
> 问题一

确实存在，这个部分我也在考虑如何优化，可以折行显示，但总归感觉不是很「实用」。

> 问题二

简悦是以 URL 为检索标准。但我没太理解你的意思，方便给个 URL 看看吗？

**Comment by OptimusPrimeme** [comment]
> 简悦是以 URL 为检索标准。但我没太理解你的意思，方便给个 URL 看看吗？

比如说这两组页面

1. [Url1](https://docs.ankiweb.net/#/editing)，[Url2](https://docs.ankiweb.net/#/editing?id=adding-a-note-type)
2. [Url3](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-5.1)，[Url4](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-5.1#outputs)

其实Url1和Url2都是同一个页面，只是打开的位置不同，但是因为url不同，所以我用Url1打开了页面并作了标注后，如果再从Url2打开该页面，进入阅读模式，之前做的标注就不显示了。Url3和Url4同理。当然其实可以删除掉url用于定位的部分，url就一样了。

**Comment by Kenshin** [comment]
我了解你的诉求了，确实因为 URL 变了导致它们不是一个「稍后读」。

我考虑下如何优化这个事情。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

**Comment by OptimusPrimeme** [comment]
好像这两个问题还是存在。😂

**Comment by Kenshin** [comment]
> 好像这两个问题还是存在。😂

哈哈，因为这是个 Delay 了很久 Issues，我今天 Closed 100+ 个，所以没办法一一说明。

***

第二个问题确实存在。
第一个问题明天试试。

**Comment by OptimusPrimeme** [comment]
> > 好像这两个问题还是存在。😂
> 
> 哈哈，因为这是个 Delay 了很久 Issues，我今天 Closed 100+ 个，所以没办法一一说明。
> 
> 第二个问题确实存在。
> 第一个问题明天试试。

辛苦了

**Comment by Kenshin** [comment]
> 第一个问题

算是解决了，你可以看下面的视频  😂 

![2021-09-15_11-50-58 (1)](https://user-images.githubusercontent.com/81074/133367847-add82317-bff3-4bf2-b796-359f4d3802db.gif)
