### ISSUE TITLE
授权坚果云失败

### ISSUE THREAD

**Issue by engvucen** [Kenshin/simpread#2016]
1. 点击 高级设定 -> 授权坚果云，无法授权成功；
![image](https://user-images.githubusercontent.com/31369318/114279811-0f11cb00-9a69-11eb-9e0b-ddd75b3e9fc3.png)
2. 打开控制台，发现选项的HTML需要优化内容策略；
![image](https://user-images.githubusercontent.com/31369318/114279854-3c5e7900-9a69-11eb-8830-89f9376fdf7b.png)
2.1 Network 看不到请求
![image](https://user-images.githubusercontent.com/31369318/114279902-6f087180-9a69-11eb-92ff-e2c107bbeeef.png)
2.2 但凡是需要请求的，都会失败

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
图二的错误你可以忽略，跟此问题无关，它并不会影响什么。

***

至于你提到的问题，比较奇怪，除了坚果云无法授权成功外，其余的授权都无法使用？

另外，你是否安装了某些防火墙？或者说浏览器做了什么设置？

**Comment by engvucen** [comment]
> 嗨，谢谢反馈。
> 图二的错误你可以忽略，跟此问题无关，它并不会影响什么。
> 
> 至于你提到的问题，比较奇怪，除了坚果云无法授权成功外，其余的授权都无法使用？
> 
> 另外，你是否安装了某些防火墙？或者说浏览器做了什么设置？

1. 已关防火墙；坚果云依然无法授权成功；
2. 其他授权，例如语雀，可以授权成功；

**Comment by Kenshin** [comment]
@engvucen 

emmm... 能否详细说下坚果云授权的步骤（最好有截图）如果类似语雀可以使用的话，基本上就是你操作问题造成的。

我每天都在使用坚果云，肯定不会出错的。

**Comment by engvucen** [comment]
> @engvucen
> 
> emmm... 能否详细说下坚果云授权的步骤（最好有截图）如果类似语雀可以使用的话，基本上就是你操作问题造成的。
> 
> 我每天都在使用坚果云，肯定不会出错的。

1. 再看了一次文档，发现是用 邮箱名 作为用户名的，而不是应用名；
2. 尝试用邮箱名，成功配置；

谢谢大佬耐心解答❤

**Comment by Kenshin** [comment]
@engvucen 

哈哈，破案了~ 没问题的话，我关闭 Issues 了~

**Comment by JsHuang** [comment]
> > @engvucen
> > emmm... 能否详细说下坚果云授权的步骤（最好有截图）如果类似语雀可以使用的话，基本上就是你操作问题造成的。
> > 我每天都在使用坚果云，肯定不会出错的。
> 
> 1. 再看了一次文档，发现是用 邮箱名 作为用户名的，而不是应用名；
> 2. 尝试用邮箱名，成功配置；
> 
> 谢谢大佬耐心解答❤

参考的哪个文档，我也遇到这个问题，不知道哪里配置?dropbox这些授权都可以

**Comment by Kenshin** [comment]
@JsHuang 

http://ksria.com/simpread/docs/#/坚果云
