### ISSUE TITLE
阅读模式适配后原有 header 的 id 失效，文中的跳转链接随之失效。

### ISSUE THREAD

**Issue by TranchBellic** [Kenshin/simpread#202]
阅读模式适配后原有 `标题` 的 `id` 失效，文中的跳转链接（如`href="#header1"`）随之失效。

**Comment by Kenshin** [comment]
请告知具体的 url 。

**Comment by Kenshin** [comment]
没有后续回复的话，我将关闭此 issues，如需要重新开启它。 😊
