### ISSUE TITLE
CSDN LaTex公式解析

### ISSUE THREAD

**Issue by niuniu326075** [Kenshin/simpread#2023]
**请说明发生问题的环境**

- 操作系统 ** Windows **

- 浏览器版本 **Microsoft Edge 89.0.774.75**

- 简悦版本 **2.1.0**

- 发生问题的地址 https://blog.csdn.net/VictoriaW/article/details/70053790

**请描述你的问题**

  在参考已关闭的问题 CSDN文字公式格式混乱 #518 后 ，关闭预加载，对于和该问题中同样的网页，在阅读模式中解析没有问题，但是保存到稍后读或利用同步助手生成PDF，格式出现一些错乱，见图

**截图**

**图1 阅读模式没有问题**
![image](https://user-images.githubusercontent.com/29769569/114422151-98034080-9be8-11eb-8bee-8bf1cdcc2514.png)
**图2 加入到稍后读页面格式错乱**
![image](https://user-images.githubusercontent.com/29769569/114422454-e0baf980-9be8-11eb-9ffb-5228c7ed65d7.png)
**图3 生成PDF格式错乱**
![image](https://user-images.githubusercontent.com/29769569/114422771-27a8ef00-9be9-11eb-8670-3baa6a293300.png)
pdf文件也上传到这里
[计算机视觉之统计形状模型——Active Shape Model_CodeTutor-CSDN 博客_统计形状模型.pdf](https://github.com/Kenshin/simpread/files/6298015/Active.Shape.Model_CodeTutor-CSDN._.pdf)
 
期待您的回复！谢谢

**Comment by Kenshin** [comment]
嗨，这是稍后读在新版中通过同步助手导出的内容，你可以确认是否还存在问题，如存在，请详细截图指出。

[1456-计算机视觉之统计形状模型——Active Shape Model_CodeTutor-CSDN博客_统计形状模型.pdf](https://github.com/Kenshin/simpread/files/6300748/1456-.Active.Shape.Model_CodeTutor-CSDN._.pdf)

**Comment by niuniu326075** [comment]
谢谢你的回复，我看了一下你发的文件pdf，除了有张图片裂了（没加载完成），其他都没有问题。
意思是下个版本会修复这个问题？我目前使用是2.1.0插件，1.0.0同步助手，只需等待新版本发布就行吗？谢谢

**Comment by Kenshin** [comment]
> https://zhuyulab.blog.csdn.net/article/details/101080064

唉，这个页面是 katex 解析的，暂时不支持，仅支持 https://www.mathjax.org/ 方案。

唉，「万恶」的 CSDN 就不能统一下规则吗？

> 有张图片裂了（没加载完成）

偶尔会存在这种情况，重新再导出一次就好了。

> 意思是下个版本会修复这个问题？我目前使用是2.1.0插件，1.0.0同步助手，只需等待新版本发布就行吗？

是的。新版（以及新的同步助手）会同步发布~

**Comment by niuniu326075** [comment]
谢谢 辛苦了

**Comment by Kenshin** [comment]
嗨，我需要重开启这个 Issues 等发布后我会在这里通知并关闭它。  😀

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

注意：

1. `katex` 方案暂时还未支持，仅解决了 `latex` 遗留下来的问题。
2. 凡是需要使用 `latex` 解析方案的页面，都需要加入到 [延迟加载列表](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e5%bb%b6%e8%bf%9f%e5%8a%a0%e8%bd%bd) 后才能生效。


## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by wushuai2000** [comment]
请问简悦导出CSDN的katex公式现在还是乱码的问题什么时候解决啊
