### ISSUE TITLE
博客上的代码行内容无法获取

### ISSUE THREAD

**Issue by laolai** [Kenshin/simpread#2027]
- 操作系统 **Windows MacOS**

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
在这个[网站](https://vircloud.net/exp/od-sync.html)使用简悦，无法获取到代码行的内容

**截图**

- 网站原内容：
![image](https://user-images.githubusercontent.com/3068867/114492664-93bc3f00-9c4b-11eb-9939-68d65e37a970.png)

- 使用简悦后的内容：
![image](https://user-images.githubusercontent.com/3068867/114492716-b189a400-9c4b-11eb-8910-2a52b3d0f901.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
