### ISSUE TITLE
简悦聚焦成功，发送到印象笔记失效

### ISSUE THREAD

**Issue by TheKiteRunning** [Kenshin/simpread#203]
http://www.ilovematlab.cn/thread-3079-1-1.html

![image](https://user-images.githubusercontent.com/24802332/34659660-35766676-f476-11e7-9d5a-d3b5df486882.png)

**Comment by Kenshin** [comment]
感谢反馈，这部分的原因请参考 [这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

**Comment by TheKiteRunning** [comment]
tks
