### ISSUE TITLE
两个问题，1：标注突然全部消失（可能是安装了新插件）2：鼠标移动到图片上会自动出现标注

### ISSUE THREAD

**Issue by YanyingZH** [Kenshin/simpread#2032]
第一个问题我也不知道该怎么贴图，可能是个bug，还好这篇文章我标注的不是很多
第二个问题的图如下，我装了放大图片插件。
![image](https://user-images.githubusercontent.com/44012305/114652095-cb90b880-9d17-11eb-804e-58739215236a.png)

**Comment by Kenshin** [comment]
嗨。

> 1：标注突然全部消失

请问使用了同步助手了吗？另外，一般使用同步助手的话都会辅以自己的网盘，如：坚果云 / Dropbox 等。如果是的话，可以看看它们的历史记录。

PS：同步助手未来会提供自己的历史记录功能，确保不丢失数据。

> 第二个问题的图如下，我装了放大图片插件。

标注栏在移动到图片上会自动显示，这样能减少一步操作。

或者你告诉我你装了什么扩展？我来试试。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
