### ISSUE TITLE
BUG：标注文本时文本摘录错位

### ISSUE THREAD

**Issue by XSeanU** [Kenshin/simpread#2033]
**环境**

- 操作系统 **Windows**

- 浏览器版本 **Edge 89.0.774.75**

- 简悦版本 **2.1.0**

- 复现率 **每次**

**问题描述**

在标注的时候，明显看到标注那一行的高度不一，摘录下来的文本也有错位。
![image](https://user-images.githubusercontent.com/51028862/114809555-fa249700-9ddc-11eb-9df3-13c47b98cc09.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

「错位」的问题因不同的主题导致，你可以更换主题后再看下。

PS：看看能否下个版本修复此问题。

> 摘录下来的文本也有错位。

没理解你的意思，你是顺序有问题？还是什么？
侧栏因为显示区域受限，所以只显示了较简单的内容。

**Comment by XSeanU** [comment]
Hi,


从截图可以看到，右侧的文本顺序和文章不一致，而且这种不一致和左边标注的错位是相关的。

Sean&nbsp;Xu


------------------ Original ------------------
From: Kenshin Wang ***@***.***&gt;
Date: Thu, Apr 15, 2021 3:37 PM
To: Kenshin/simpread ***@***.***&gt;
Cc: XSeanU ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Kenshin/simpread] BUG：标注文本时文本摘录错位 (#2033)

**Comment by Kenshin** [comment]
okay 我理解你说的错位是什么意思了。请问这个标注是正常顺序标注？还是反向顺序标注？

> 在标注一行以内的文本的时候，似乎并没有这个问题。希望能够帮助定位bug。

收到。

***

方便的话，把 URL 给我看下。

**Comment by XSeanU** [comment]
Hi,
抱歉，我留意了一下，似乎每次出现问题都在特定位置。与标注长短没有关系，而似乎与字符和HTML编码有关，
出现问题的网址包括少数派（https://sspai.com/item/186#340, https://sspai.com/item/186#340, etc.），个人博客（https://index.pmthinking.com/19909e5aac3049d887197dcfb1e97fd5）。

Best wishes,
Sean


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Apr 15, 2021 06:53 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Kenshin/simpread] BUG：标注文本时文本摘录错位 (#2033)





 
okay 我理解你说的错位是什么意思了。请问这个标注是正常顺序标注？还是反向顺序标注？
  
在标注一行以内的文本的时候，似乎并没有这个问题。希望能够帮助定位bug。
  
收到。
 
 
方便的话，把 URL 给我看下。

**Comment by XSeanU** [comment]
![image](https://user-images.githubusercontent.com/51028862/114862360-03375780-9e21-11eb-9132-4974826d0fc4.png)

**Comment by XSeanU** [comment]
![image](https://user-images.githubusercontent.com/51028862/114862764-80fb6300-9e21-11eb-8c31-e036cbdd6622.png)

**Comment by Kenshin** [comment]
@XSeanU 

收到~ 

PS：看到你在 Issues 比较活跃哦，不知道能否方便用 TG 呢？

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
