### ISSUE TITLE
新站适配：xie.infoq.cn

### ISSUE THREAD

**Issue by zcyoop** [Kenshin/simpread#2035]
**请说明发生问题的环境**

- 操作系统 **WIndows 10 **

- 浏览器版本 **Cent Browser 版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://xie.infoq.cn/article/8ceb991b174d046bd8c2029c8>

**请描述你的问题**

> 已经将infoq站点添加到延迟加载列表，但是文章仍然无法进行渲染

**截图**

> 
![image](https://user-images.githubusercontent.com/39327876/114838858-b5622580-9e07-11eb-8cf6-31f7eddad50d.png)

![image](https://user-images.githubusercontent.com/39327876/114839139-02de9280-9e08-11eb-8b1b-2170963a1e7e.png)

**Comment by Kenshin** [comment]
嗨，确实如此，看「表现」好像不是延迟加载的问题...

你暂时可以使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)

调查后或修复我会在关闭 Issues ~

**Comment by zcyoop** [comment]
> 嗨，确实如此，看「表现」好像不是延迟加载的问题...
> 
> 你暂时可以使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)
> 
> 调查后或修复我会在关闭 Issues ~

你好，在重新高亮后数据可以进行渲染，但会出现部分信息丢失的现象
![image](https://user-images.githubusercontent.com/39327876/114860881-1d703600-9e1f-11eb-9d85-d4b357f9e37f.png)
![image](https://user-images.githubusercontent.com/39327876/114860898-23661700-9e1f-11eb-892c-cd788486c2dc.png)

**Comment by Kenshin** [comment]
emmm...

我先记新站吧，谢谢反馈~

**Comment by yeuleh** [comment]
我这里也有该问题……
等待支持

**Comment by binsee** [comment]
这个站已经适配并合并了，此issue可关闭。

**Comment by Kenshin** [comment]
@ zcyoop

嗨，这个站已经适配了，使用方式请留意 https://github.com/Kenshin/simpread/pull/2201 提到的：

1. 由于 `InfoQ` 站点是异步加载文章内容，因此需要将 `infoq.cn` 加入到 **排除列表**。（关于为什么添加到`排除列表`，而非 `延迟加载列表`

2. 更新 [官方主适配源](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E9%80%82%E9%85%8D%E6%BA%90?id=%e5%ae%98%e6%96%b9%e9%80%82%e9%85%8d%e6%ba%90)
