### ISSUE TITLE
notion授权失败

### ISSUE THREAD

**Issue by git10135405** [Kenshin/simpread#2038]
edge最新稳定版90
简悦最新版插件
![image](https://user-images.githubusercontent.com/35558611/114992422-51099980-9ecd-11eb-841f-accb2e3223b3.png)

![image](https://user-images.githubusercontent.com/35558611/114992374-43ecaa80-9ecd-11eb-9252-fa55c3336719.png)

**Comment by Kenshin** [comment]
嗨，请看 https://github.com/Kenshin/simpread/discussions/1773 里面的说明。

**Comment by git10135405** [comment]
> 嗨，请看 #1773 里面的说明。

这个不是415的问题，而且我用web Clipper插件却可以正常授权

**Comment by Kenshin** [comment]
emmm....

抱歉，确实如此，并不是我之前给出的问题，这个 Error 是跨域问题的提示。

我在 Edge 版本 91.0.852.0 (官方内部版本) Dev(arm64) 以及 Chrome 测试是没问题的。

你稍后再测试下，或者换个 Chrome 试试（仅测试是否可用而已）

**Comment by git10135405** [comment]
@Kenshin 还是不行，可以参考下[web Clipper](https://github.com/webclipper/web-clipper)插件优化下
![image](https://user-images.githubusercontent.com/35558611/115013416-96d15c80-9ee3-11eb-9d01-18c9f7bea441.png)

**Comment by Kenshin** [comment]
@git10135405 

我不折腾了，用的都是私有 API，其他用户没有反馈过这个问题。
过阵子等 Notion API 出了后，直接上官方版的。

截图是用了 Chrome 吗？

**Comment by git10135405** [comment]
> @git10135405
> 
> 我不折腾了，用的都是私有 API，其他用户没有反馈过这个问题。
> 过阵子等 Notion API 出了后，直接上官方版的。
> 
> 截图是用了 Chrome 吗？

Edge，Notion API 出了，搞起来了吗

**Comment by Kenshin** [comment]
> Notion API 出了，搞起来了吗

没有，Notion API 还比较原始，比如：没有图床的功能。不过，等可完全可以替代私有 API 的话，我会马上移植的。

**Comment by git10135405** [comment]
> > Notion API 出了，搞起来了吗
> 
> 没有，Notion API 还比较原始，比如：没有图床的功能。不过，等可完全可以替代私有 API 的话，我会马上移植的。

有消息了吗😂

**Comment by Kenshin** [comment]
@git10135405 

Notion 的速度一直都很慢... 另外，难道你的授权还是不行？

**Comment by git10135405** [comment]
我说的是api


---原始邮件---
发件人: &quot;Kenshin ***@***.***&gt;
发送时间: 2021年9月23日(周四) 中午12:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] notion授权失败 (#2038)




 
@git10135405
 
Notion 的速度一直都很慢... 另外，难道你的授权还是不行？
 
&mdash;
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by git10135405** [comment]
> @git10135405
> 
> Notion 的速度一直都很慢... 另外，难道你的授权还是不行？

想问的是 Notion API

**Comment by Kenshin** [comment]
没有什么适合的 API

简悦导入到 Notion 的功能，目前来看是够用的。唯一的问题是：偶尔会存在不稳定性。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
另外，此功能就是利用 Notion API 实现的，所以我关闭此 Issues 了~
