### ISSUE TITLE
能否再增加一个更大的字号？

### ISSUE THREAD

**Issue by whwnow** [Kenshin/simpread#204]
现有的大号字体，看起来依然有点小费眼睛。能不能再加几个更大号的字体。
如果能调行高就更好了，好作品，点赞！

**Comment by Kenshin** [comment]
感谢反馈~
你可以通过 [自定义样式](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决你的问题

**Comment by whwnow** [comment]
这种很常用的功能，为什么要增加用户的使用难度呢？我猜一个自定义样式就会吓走很多小白用户

**Comment by Kenshin** [comment]
好吧，你说的也的确有道理 😂

可以在下个版本增加一个选项～

**Comment by whwnow** [comment]
哈哈，点赞！👍

2018-01-21 9:23 GMT+08:00 Kenshin Wang <notifications@github.com>:

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，

新版的字体大小更改改为 多级调节，而非之前的三级。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
