### ISSUE TITLE
关于标注功能的几点建议

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2042]
另外关于简悦的标注功能，我想提几个建议，
1、比如有时候我在一段话里有好几个高亮，当我想要对某个标注打标签的时候，那个自动显示的标注栏总是来回跳转，很难选中，除非开启连续标注进行鼠标双击，
2、建议复制功能支持ctrl+v
3、建议支持annotion或者打标签的快捷键，还有输入完成之后退出编辑界面的快捷键，比如esc,要不然总是在鼠标或者键盘之间切换效率很低

***

另外再请教一个问题，进入阅读模式后，做的高亮或者标注都是自动加入到稍后读的嘛，我在高级选项和帮助文档里没找到相关说明

via @YangWaldon

**Comment by Kenshin** [comment]
嗨，谢谢建议，下面的对此的一一回复~

> 另外再请教一个问题，进入阅读模式后，做的高亮或者标注都是自动加入到稍后读的嘛，我在高级选项和帮助文档里没找到相关说明

加入标注后的稍后读再次进入时会加载对应的标注。（如 https://sspai.com/post/61996 标注后，再次进入这个地址，自然会加载标注

但是，有种特殊情况，如在 https://sspai.com/post/61996 标注后，进入了 https://sspai.com/post/61996#xxx 则会被认为是一个新的页面，自然没有标注了。

***

> 比如有时候我在一段话里有好几个高亮，当我想要对某个标注打标签的时候，那个自动显示的标注栏总是来回跳转，很难选中，除非开启连续标注进行鼠标双击，

下个版本会修改这个逻辑，默认改为 **鼠标点击显示（而非现在的鼠标移上显示）**

> 建议复制功能支持ctrl+v

考虑中ing~

> 建议支持annotion或者打标签的快捷键，还有输入完成之后退出编辑界面的快捷键，比如esc,要不然总是在鼠标或者键盘之间切换效率很低

考虑ing~ 
新版的逻辑：修改完直接 ESC 的话，不会被保存哦，只有点击了保存后才会。

打标签的快捷键 → 即便有快捷键也是弹出标注编辑框。

***

谢谢喜欢简悦。（如 [没有评分，请帮忙评分](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)~  因为看起来你是新用户~

**Comment by YangWaldon** [comment]
> 嗨，谢谢建议，下面的对此的一一回复~
> 
> > 另外再请教一个问题，进入阅读模式后，做的高亮或者标注都是自动加入到稍后读的嘛，我在高级选项和帮助文档里没找到相关说明
> 
> 加入标注后的稍后读再次进入时会加载对应的标注。（如 https://sspai.com/post/61996 标注后，再次进入这个地址，自然会加载标注
> 
> 但是，有种特殊情况，如在 https://sspai.com/post/61996 标注后，进入了 https://sspai.com/post/61996#xxx 则会被认为是一个新的页面，自然没有标注了。
> 
> > 比如有时候我在一段话里有好几个高亮，当我想要对某个标注打标签的时候，那个自动显示的标注栏总是来回跳转，很难选中，除非开启连续标注进行鼠标双击，
> 
> 下个版本会修改这个逻辑，默认改为 **鼠标点击显示（而非现在的鼠标移上显示）**
> 
> > 建议复制功能支持ctrl+v
> 
> 考虑中ing~
> 
> > 建议支持annotion或者打标签的快捷键，还有输入完成之后退出编辑界面的快捷键，比如esc,要不然总是在鼠标或者键盘之间切换效率很低
> 
> 考虑ing~
> 新版的逻辑：修改完直接 ESC 的话，不会被保存哦，只有点击了保存后才会。
> 
> 打标签的快捷键 → 即便有快捷键也是弹出标注编辑框。
> 
> 谢谢喜欢简悦。（如 [没有评分，请帮忙评分](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)~ 因为看起来你是新用户~

多谢回答，已经评价

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
