### ISSUE TITLE
稍后阅读 · 阅读模式在论坛类页面下无法解析（使用内置解析方案）

### ISSUE THREAD

**Issue by JsHuang** [Kenshin/simpread#2049]
网址：
http://bbs.sylixos.com/forum.php?mod=viewthread&tid=3511&extra=page%3D1
开启了内置解析，依然无法正常进入阅读模式
![image](https://user-images.githubusercontent.com/5506543/115351680-11062780-a1e9-11eb-89e9-e6e230f3983a.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

确实如此，估计是因为 `论坛类页面` 造成的，下个版本会有某种方式解决这个问题。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
