### ISSUE TITLE
当前页面结构改变导致不匹配阅读模式，请报告此页面。

### ISSUE THREAD

**Issue by ybbpgfjtey** [Kenshin/simpread#205]
地址：http://www.liushuba.com/files/article/html/60/60257/22473393.html

**Comment by Kenshin** [comment]
感谢反馈～
你可以通过 [站点编辑器](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)改变当前站点的规则。

**Comment by Kenshin** [comment]
你好，小说类网址，建议使用一款 UserScript - My Novel Reader，效果更好~
https://greasyfork.org/zh-CN/scripts/292-my-novel-reader

当然，如果是其它类别的页面，我还是建议使用简悦~
我将关闭此 issues
