### ISSUE TITLE
博客园代码的解析问题

### ISSUE THREAD

**Issue by longbao2214** [Kenshin/simpread#2050]
-->

**请说明发生问题的环境**

- 操作系统 **Windows10**

- 浏览器版本 **Microsoft Edge 版本 90.0.818.41 (官方内部版本) (64 位)**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://www.cnblogs.com/suwings/p/6079178.html>

**请描述你的问题**

原文代码段如图1
简悦解析后的代码段如图2
解析后代码缺失了
请帮看下，谢谢

**截图**

![image](https://user-images.githubusercontent.com/81485217/115389070-39088180-a20f-11eb-8c62-0b7b85414fb9.png)
![image](https://user-images.githubusercontent.com/81485217/115388968-1e360d00-a20f-11eb-9801-95d1b7580367.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
