### ISSUE TITLE
Evernote导入失败

### ISSUE THREAD

**Issue by bush911** [Kenshin/simpread#2052]
发生问题的地址: <http://www.pmlive.com/pharma_news/janssen_will_not_seek_regulatory_approval_for_erleada_plus_zytiga_in_prostate_cancer_1367589?utm_source=pmlive

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
