### ISSUE TITLE
建议：稍后读增加搜索功能

### ISSUE THREAD

**Issue by XSeanU** [Kenshin/simpread#2053]
常常记得自己把一篇文章放进稍候读，但是找不到在哪里——能不能增加搜索功能呢？

**Comment by Kenshin** [comment]
嗨，稍后读支持搜索，位置在下图

![image](https://user-images.githubusercontent.com/81074/115485783-f1720c00-a287-11eb-8bc0-63d612c14828.png)

**Comment by XSeanU** [comment]
抱歉，用了这么久，我傻逼了……
