### ISSUE TITLE
优化一下标注侧栏拖动排序

### ISSUE THREAD

**Issue by OptimusPrimeme** [Kenshin/simpread#2054]
![simpread](https://user-images.githubusercontent.com/22427706/115485448-55480500-a287-11eb-8cd4-19ad146877dd.gif)
如图所示，当标注栏有一定数量的标注，要调整标注排序时，如果想把底部的标注拖动到顶部，滚动条不会自动滚动，只能是，先拖到可视范围内的顶部，再手动滚动后拖到顶部

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

目前确实是这样的，我看看如何优化这里~

**Comment by Kenshin** [comment]
嗨，如果是根据上下文的属性自动排序呢？能否解决你的问题？

**Comment by OptimusPrimeme** [comment]
> 嗨，如果是根据上下文的属性自动排序呢？能否解决你的问题？

上下文的属性是指被标注的部分在文中的先后顺序吗？是的话我觉得是可以的，就是能够按照被标注部分的位置来排序标注

**Comment by Kenshin** [comment]
> 上下文的属性是指被标注的部分在文中的先后顺序吗？是的话我觉得是可以的

是的，就是上下文的位置。这样的话，位置就是「固定」的，跟阅读模式内正文的上下文顺序一致。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
