### ISSUE TITLE
建议简悦同步助手中的“稍后读”快捷键改为可自定义

### ISSUE THREAD

**Issue by ryanliag** [Kenshin/simpread#2059]
在Windows中创建文件夹还有其他程序中也经常会使用到Ctrl+Shift+N，和简悦助手的快捷键有冲突，即使带关闭同步助手的情况下仍然会优先激活助手，希望可以自定义热键。

**Comment by Kenshin** [comment]
嗨，是可以自定义的，是不是跟上个 Issues 一样，应该搞定了？我先关闭这个 Issues 了，有需要再开启它。
