### ISSUE TITLE
通过同步助手无法打开chrome生成的“稍后读”快捷方式

### ISSUE THREAD

**Issue by ryanliag** [Kenshin/simpread#2060]
键入Ctrl+Shift+N后出现：

![image](https://user-images.githubusercontent.com/35890564/115724188-4f4f4280-a3b3-11eb-8254-b317fcf97f39.png)

**Comment by ryanliag** [comment]
抱歉，出现乌龙球，是我配置出错~😂，现在已经好了！

**Comment by Kenshin** [comment]
okay 搞定就好，我关闭此 Issues ~  😃
