### ISSUE TITLE
导出Markdowm实现图片本地保存

### ISSUE THREAD

**Issue by Johnny-Zhang92** [Kenshin/simpread#2061]
导出网页到离线markdown文件，图片无法本地保存。

**Comment by Kenshin** [comment]
嗨，离线 Markdown 是把图片编码到 md 文件里面，所以不存在 `图片无法本地保存` 的问题。

或者说，你可以把 URL 给我看下，我确认下是什么问题。

**Comment by Johnny-Zhang92** [comment]
这个是复制markdown到typora的图片链接：
![image](https://user-images.githubusercontent.com/35098184/115812810-97f31400-a424-11eb-901d-2dee15d0772e.png)
这个是保存离线markdown的图片链接：
![image](https://user-images.githubusercontent.com/35098184/115813146-367f7500-a425-11eb-82e7-7e7f00634aac.png)

![image](https://user-images.githubusercontent.com/35098184/115813122-2cf60d00-a425-11eb-9146-b8bd02b192c9.png)

以上两种方式都指定的是图片的网页链接，而不是将图片下载到本地使用，如下所示：
![image](https://user-images.githubusercontent.com/35098184/115813452-c8877d80-a425-11eb-9a52-bc157d4496b9.png)



> 嗨，离线 Markdown 是把图片编码到 md 文件里面，所以不存在 `图片无法本地保存` 的问题。
> 
> 或者说，你可以把 URL 给我看下，我确认下是什么问题。

**Comment by Kenshin** [comment]
emm...

我知道你的意思了，你是说像下图这样，是吧？

![image](https://user-images.githubusercontent.com/35098184/115813452-c8877d80-a425-11eb-9a52-bc157d4496b9.png)

Typora 的这种形式比较「奇特」，一般情况下这种方式都以 `.textbundle` 存在，虽然本质是一样的。

下个版本会有关此的解决方案，但也是通用方案。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
