### ISSUE TITLE
文章保存到Pocket失败

### ISSUE THREAD

**Issue by Dien-Wong** [Kenshin/simpread#2063]
![image](https://user-images.githubusercontent.com/67217923/115818424-50be5080-a42f-11eb-8e77-5bc0d6ec3f9d.png)
无法使用简悦将文章保存到pocket

**Comment by Kenshin** [comment]
嗨，这是个 Bug 已修复了，下个版本发布后我会在这里通知你~

（因为 Chrome 更新导致 CORS 造成的，也就是说在低版本的 Chrome 则没有这个问题

**Comment by Dien-Wong** [comment]
还是不可以emm，我现在用的是一款较为小众的浏览器Brave，但是也是基于Chromium内核的，不知道和这个是否有关？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kenshin Wang ***@***.***>
发送时间: Friday, April 23, 2021 6:28:37 PM
收件人: Kenshin/simpread ***@***.***>
抄送: Dienekes ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 文章保存到Pocket失败 (#2063)


嗨，这是个 Bug 已修复了，下个版本发布后我会在这里通知你~

（因为 Chrome 更新导致 CORS 造成的，也就是说在低版本的 Chrome 则没有这个问题

―

**Comment by Kenshin** [comment]
@Dien-Wong 

我没说「现在可以」的，新版发布后就可以了。 😅  

PS：跟 Brave 无关，但有用户反馈过某些功能（应该个别情况，细节没记住）在 Brave 无法使用，你在使用时也留意下。

**Comment by Dien-Wong** [comment]
好的，感谢😃

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kenshin Wang ***@***.***>
发送时间: Saturday, April 24, 2021 10:54:25 AM
收件人: Kenshin/simpread ***@***.***>
抄送: Dienekes ***@***.***>; Mention ***@***.***>
主题: Re: [Kenshin/simpread] 文章保存到Pocket失败 (#2063)


@Dien-Wong<https://github.com/Dien-Wong>

我没说「现在可以」的，新版发布后就可以了。 😅

PS：跟 Brave 无关，但有用户反馈过某些功能（应该个别情况，细节没记住）在 Brave 无法使用，你在使用时也留意下。

**Comment by GMN-git** [comment]
请问这个问题修复了嘛？保存到pocket 
Ps:我看有公告说简悦2.1已经发布了，为什么我在edge浏览器还是更新不到喃

**Comment by Kenshin** [comment]
@GMN-git 

嗨，我以为上条信息已经解释清楚了。 😅
2.1 之后的新版才会解决这个问题。（即将发布）

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

## 评分

- Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
- Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
