### ISSUE TITLE
新站适配：MDN

### ISSUE THREAD

**Issue by Joamg** [Kenshin/simpread#2067]
MDN的此页面 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img 解析错误, 经过测试其他页面基本没问题 但只有这个解析错误

**Comment by Kenshin** [comment]
嗨，谢谢反馈，确实仅这个页面存在问题，估计是因为 HTML 含有特殊字符导致解析失败。

下个版本使用了新的方式可以有效的防止这个问题，发布后我会通知你~

**Comment by Joamg** [comment]
你好 这个特定网页依然解析错误

**Comment by Kenshin** [comment]
抱歉，发布的猝不及防，我明天确认下回复你。
