### ISSUE TITLE
偶然发现微信公众号文章显示不全，如提交案例，似乎因为有小程序卡片

### ISSUE THREAD

**Issue by ggtao1983** [Kenshin/simpread#2068]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s/kGMoqjf0NBEOQu5cblw97w

**Comment by ggtao1983** [comment]
![WX20210425-114027](https://user-images.githubusercontent.com/44660084/115990117-371a3600-a5f4-11eb-9c81-a2b6911a1906.png)
配个在simpread里的截图~

**Comment by Kenshin** [comment]
嗨，谢谢反馈~

但你给出的 URL 无法打开，应该是因为微信订阅号的参数造成的，请再告诉我一次。

**Comment by ggtao1983** [comment]
抱歉让久等，通过微信获得了固定连接如下。
https://mp.weixin.qq.com/s/kGMoqjf0NBEOQu5cblw97w

任何意见或问题还请方便沟通，谢谢！

Kenshin Wang ***@***.***> 于2021年4月25日周日 下午7:30写道：

**Comment by Kenshin** [comment]
嗨，确实有识别失败的情况。

下个版本有一个非智能（但很好用）的方式解决，发布我会在这里通知你~

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
