### ISSUE TITLE
在稍后读的界面,每一次标注都会触发提示:"请确保已运行简悦-同步助手"

### ISSUE THREAD

**Issue by HaiweiCode** [Kenshin/simpread#2070]
<
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10 20H2**

- 浏览器版本 **e.g. Microsoft Edge 90.0.818.46**

- 简悦版本 **2.0.0**

- 发生问题的地址 稍后读界面

**请描述你的问题**

> 在稍后读的界面,每一次标注都会触发"请确保已运行简悦-同步助手",会占用整个右侧界面,体验不好

**截图**

![image](https://user-images.githubusercontent.com/20102696/115986748-4beecd80-a5e4-11eb-928c-fa790bedd67c.png)

**Comment by HaiweiCode** [comment]
这个问题解决的方式，是每次进入页面的时候，手动关闭"自动保存到本地"的选项：
![image](https://user-images.githubusercontent.com/20102696/115989519-5794c100-a5f1-11eb-83a9-5ca5b654cc83.png)
希望能够提供统一的配置按钮

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

> 在稍后读的界面,每一次标注都会触发"请确保已运行简悦-同步助手",会占用整个右侧界面,体验不好

下个版本会优化这个地方的提示。

> 是每次进入页面的时候，手动关闭"自动保存到本地"的选项：

如果使用同步助手的时候，有个隐性 Bug 导致会失效，不过，在下图修改。

![image](https://user-images.githubusercontent.com/81074/115991955-a8121b80-a5fd-11eb-9ff5-423baad4cd93.png)

另外，新版已经修复了这两个问题，发布后我在这里通知你~

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

当未开启同步助手时，仍可以使用简悦的最基本功能以及不需要使用同步助手的功能，同时会有下面的提示

![image](https://user-images.githubusercontent.com/81074/121986598-5f8b0900-cdc9-11eb-935a-3f4feef7e1fb.png)

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

## 评分

- Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
- Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
