### ISSUE TITLE
高级账户无法导出HTML/离线HTML/PDF/PNG（因特殊字符造成）

### ISSUE THREAD

**Issue by litao06370** [Kenshin/simpread#2072]
首先,在升级高级账户前,使用了普通账户的导出功能离线HTML和HTML均正常使用.
然后,今天下午刚升级的高级账户后"导出HTML/离线HTML/PDF/PNG"功能均出现异常,详情见图.
最后,我清楚了所有配置文件,也退出了高级账户,用普通账户再次尝试了导出离线HTML,是没有问题的.

不知道这是什么原因,升级了反而基础功能都没法用了。

无法上传图片,我就用文字描述了:
[ 使用的谷歌浏览器,当我在阅读模式标注完成后, 打开"动作 -> 导出 -> HTML/离线HTML" ,
浏览器右上角出现两行提示: " 全部图片已经转换完毕,马上开始下载,请稍等 "    " √已成功保存 "]
我安装了PC端简悦助手,也配置了导出目录.在导出目录和谷歌下载目录中都没有发现应该导出的html文件, 我也用everything在电脑里全局搜索,同样没发现新产生的html文件.

这个问题真是想不通呀

不知能否点开,补充图片链接如下 https://github.com/litao06370/cg-blog/blob/master/%E5%AF%BC%E5%87%BA%E5%A4%B1%E8%B4%A52.png?raw=true

**Comment by Kenshin** [comment]
嗨，不可能存在升级高级账户后基础功能无法使用的情况。 😅 

至于你的问题是，应该（也必然）是配置出错造成的。 😂 

另外，Github 也不存在无法上传图片的情况。 😅 

***

链接能打开，但是没有任何意义，你需要给我配置的截图（包括：同步助手和扩展端）

简单的说，下图都需要配置

![image](https://user-images.githubusercontent.com/81074/116021897-b868db80-a67b-11eb-8d85-80f5b568c338.png)

![image](https://user-images.githubusercontent.com/81074/116021947-d20a2300-a67b-11eb-9b31-7eed910ce4d6.png)

或者也有可能是标题的问题，解决方案 https://github.com/Kenshin/simpread/discussions/1617

***

建议请给出出现问题的 URL 也方便排查。

**Comment by litao06370** [comment]
感谢回答.出现问题的URL如下:https://gitee.com/SnailClimb/JavaGuide#%E5%9F%BA%E7%A1%80

**Comment by litao06370** [comment]
补充一下,你说"不可能存在升级高级账户后基础功能无法使用的情况".

经过我反复确认,此URL:https://gitee.com/SnailClimb/JavaGuide#%E5%9F%BA%E7%A1%80 的内容,在阅读模式下标记后,**普通账户可导出HTML**(在谷歌浏览器的默认下载目录),
而我登录**高级账户**后,**无法导出HTML**(在简悦助手的目录里没有,谷歌浏览器下载目录也没有).

我很确定我**配置正确了简悦助手**,通过其他页面是可以在阅读模式下,自动同步保存html文件到本地的.

**Comment by Kenshin** [comment]
> 补充一下,你说"不可能存在升级高级账户后基础功能无法使用的情况".
> 
> 经过我反复确认,此URL:https://gitee.com/SnailClimb/JavaGuide#%E5%9F%BA%E7%A1%80 的内容,在阅读模式下标记后,**普通账户可导出HTML**(在谷歌浏览器的默认下载目录),
> 而我登录**高级账户**后,**无法导出HTML**(在简悦助手的目录里没有,谷歌浏览器下载目录也没有).
> 
> 我很确定我**配置正确了简悦助手**,通过其他页面是可以在阅读模式下,自动同步保存html文件到本地的,而如上的URL页面在标注时,没有出现自动同步html到本地.

嗨，看看是不是因为标题含有特殊字符造成的？ https://github.com/Kenshin/simpread/discussions/1617

**Comment by litao06370** [comment]
> 嗨，看看是不是因为标题含有特殊字符造成的？ #1617

应该不是,因为我提前做了如下处理:
1,我添加了处理特俗字符的插件,并刷新页面重新尝试导出HTML,仍失败.
2.我也在阅读模式下,修改了右上角的标题(图一),导出HTML仍失败.

另外,我在上面楼层有说过,普通账户可以直接导出HTML在谷歌浏览器默认文件夹,我切换到高级账户后,则失败.所以这也说明,此问题无关特俗字符.

图一:
![c1](https://user-images.githubusercontent.com/43006082/116361152-3c18f880-a833-11eb-92c2-60aa983e4753.png)

**Comment by Kenshin** [comment]
> 我也在阅读模式下,修改了右上角的标题(图一),导出HTML仍失败.

嗨，修改稍后读的标题并不能成为导出时的标题（这是个 Bug，下个版本已修复了）

另外，你给我的 URL 我是可以导出的。

***

另外，其它页面没有这个问题吧？如果仅这个页面的话，看看能否这样操作：

1. 备份当前的配置文件
2. 删除当前页面的稍后读
3. 进入阅读模式（未加入稍后读的情况下）看看能否导出？

**Comment by litao06370** [comment]
> 另外，其它页面没有这个问题吧？如果仅这个页面的话，看看能否这样操作：
> 
> 1. 备份当前的配置文件
> 2. 删除当前页面的稍后读
> 3. 进入阅读模式（未加入稍后读的情况下）看看能否导出？

我用B站的直播客户端,录制了一段视频,复现我描述的问题: https://www.bilibili.com/video/BV1FU4y187CH/


我测试两个页面作为对比:
1. JavaGuide	
(自动同步文件夹中生成了一个空文件,无任何格式
手动导出HTML,也仅仅是一个新的空文件覆盖了之前的文件)
2. 扇贝单词	
(通过PC简悦助手,可自动同步HTML到输出的文件夹中:跟随最新标注的时间生成了最新的HTML文件)

D:\mySoft\jianyue\output 是我设置的简悦助手同步文件夹路径

**Comment by Kenshin** [comment]
嗨，我在 Mac 环境下，无法使用 Win ，**我先帮你问问其他有 Win 环境的用户，然后再回复你**。

另外，单说  https://gitee.com/SnailClimb/JavaGuide 如果生成正确的话，应该是下面这个名字（因为我看到视频里面导出的文件名称都不对）

![image](https://user-images.githubusercontent.com/81074/116496898-aafc5d00-a8d8-11eb-8134-998056fffa7a.png)

如果安装了我提到的插件，进入阅读模式后，应该是下面这个名字

![image](https://user-images.githubusercontent.com/81074/116496934-cbc4b280-a8d8-11eb-9a1b-83e09d839a5c.png)

***

另外，虽然大概率可能是个例，但无论如何都应该谢谢你录屏来说明，要知道并不是每个人都有耐心这么做的。（哪怕他遇到的问题不是简悦的问题）

🙏

**Comment by litao06370** [comment]
> 另外，单说 https://gitee.com/SnailClimb/JavaGuide 如果生成正确的话，应该是下面这个名字（因为我看到视频里面导出的文件名称都不对）
> ![image](https://user-images.githubusercontent.com/81074/116496898-aafc5d00-a8d8-11eb-8134-998056fffa7a.png)

是的,导出的文件名都不正确,所以是内部识别或哪里出现了问题,我特意用了另一个网站导出,与其进行对比(说明本地配置没有问题).
这个问题可能是个例,但是,我在使用普通账户的情况下,是可以直接导出HTML的,视频如下: https://www.bilibili.com/video/BV1fh41127F6
所以这就很奇怪了,在我所演示的这个网页下,普通账户可用的功能,高级账户却出现了问题

**Comment by Kenshin** [comment]
> 通过浏览器下载与通过同步助手下载，其实不太一样。

「破案」了，就是因为某些字符导致在 Windows 下保存失败造成的，新版已经解决了这个问题。

1. 你安装的这个插件并不能 100% 剔除 Windows 下的特殊字符（而 Mac 下没有那么多的特殊字符，所以我一直没遇到
2. 新版同步助手内置了插件的特殊字符排除功能

你可以静等待新版发布就可以了。

PS：至于通过浏览器下载的时候，浏览器会自动剔除这些无效的特殊字符。

**Comment by litao06370** [comment]
> > 通过浏览器下载与通过同步助手下载，其实不太一样。
> 「破案」了，就是因为某些字符导致在 Windows 下保存失败造成的，新版已经解决了这个问题。
> PS：至于通过浏览器下载的时候，浏览器会自动剔除这些无效的特殊字符。
明白了,根本原因是浏览器和简悦,两种方式处理特殊字符时,情况不一样.
嗨,困扰我这么久.
那这个case也Done了

**Comment by Kenshin** [comment]
> 普通账户直接通过浏览器处理,高级账户却直接跳过浏览器了吗(因为要处理更多复杂的格式还是什么原因)

是的。同步助手可以将这个 HTML 保存到本地的任意位置，而基础账户则只能保存到浏览器默认下载目录。

所以，后者比前者更灵活，但因为 Win 和 Mac 系统本身的差异性导致了这个 Bug，等新版发布后，我会在这里通知你。

**Comment by moodykeke** [comment]
同样保存问题，期待上架新版本。

**Comment by Kenshin** [comment]
@moodykeke 

你也是 Windows 也是同样安装了 https://github.com/Kenshin/simpread/discussions/1617 也无法导出？

**Comment by Kenshin** [comment]
@moodykeke @litao06370 

嗨，忘记说了，简悦五一有个抽奖，如果未在 Chrome 或 Edge 五星好评的话，可以试试抽奖。

Chrome https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

Edge https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc

***

### 抽奖方法
1. 每五名用户即赠送一个中奖名额
2. 到截至日后，如不足五名，四舍五入
（划重点）也就是，每五个人就一定有一人中奖。
3. Chrome Webstore 与 Edge 应用商店分别统计，可同时提交评价。

细节请看 https://t.me/simpread/158 也可进群 https://t.me/simpread

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
