### ISSUE TITLE
标签栏不再无限嵌套了

### ISSUE THREAD

**Issue by ferrecize** [Kenshin/simpread#2073]
标签系统似乎出问题了，我的标签现在不再嵌套只有单层了，但以前是正常的，请问该怎么解决呢
![image](https://user-images.githubusercontent.com/48345666/116022929-c1f34300-a67d-11eb-90f4-c95a2ffaacdf.png)
![image](https://user-images.githubusercontent.com/48345666/116022931-c3bd0680-a67d-11eb-8648-bfc7c5eb1d7e.png)

**Comment by Kenshin** [comment]
抱歉，你给出的信息太少了，没法判断。

点击第一个图杂志右侧的 icon 无法反映吗？

**Comment by ferrecize** [comment]
> 抱歉，你给出的信息太少了，没法判断。
> 
> 点击第一个图杂志右侧的 icon 无法反映吗？

对不起，原来是我忘了要点那个箭头了，我一直试图点击文字把下层标签给召唤出来，我是傻子，抱歉

**Comment by Kenshin** [comment]
哈哈，没关系。

我关闭此 Issues 了。
