### ISSUE TITLE
版面宽度失效问题

### ISSUE THREAD

**Issue by runningwaterpro** [Kenshin/simpread#2076]
你好！

版面宽度失效，调整成任何数值，阅读模式下文字始终都是全屏的，如下图：

![微信截图_20210428100337](https://user-images.githubusercontent.com/389973/116335407-69e94780-a809-11eb-839b-2dea5576cbb6.png)

**Comment by Kenshin** [comment]
嗨，给个 URL 看看，另外其它页面也存在这个问题吗？

**Comment by runningwaterpro** [comment]
在我这里所有页面都是这样，随意发两个存在问题的页面吧：

https://www.jianshu.com/p/b9af028efebb
https://netflixtechblog.com/making-the-netflix-api-more-resilient-a8ec62159c2d

另外，浏览器是 Microsoft Edge (Chromium) 版本 90.0.818.46，扩展是在微软应用商店下载的。除扩展外，轻读版也是同样的现象。

**Comment by runningwaterpro** [comment]
不知是否到其他什么影响，刚才试验轻读版，发现 “set_layout: ” 无论怎么设置、保存，刷新后都会变成 116%。

**Comment by Kenshin** [comment]
> 不知是否到其他什么影响，刚才试验轻读版，发现 “set_layout: ” 无论怎么设置、保存，刷新后都会变成 116%。

在同一个浏览器，不要同时使用扩展端与轻阅版。（当然跟此问题无关）

***

请使用以下方式，看看能否解决？

1. 在 **隐身模式下，仅启用简悦** 排除其它扩展的干扰，看看是否可用？
2. 扩展端导出配置（然后重置）看看能否解决？
3. 是否使用同步助手？

我测试了你给我的页面，是可以调整版面宽度的。

**Comment by runningwaterpro** [comment]
之前在隐身模式下仅启用简悦扩展，同样现象。之前的所有操作，扩展和脚本都没有同时启用，是禁用一个、启用一个的。

不知道怎么重置，刚才卸载了简悦扩展，重新安装，默认配置，轻读版禁用，问题如故。

再次试验隐身模式，仅启用简悦扩展，还是一样。

不确定同步助手是什么，假如是扩展的话，没有安装，如果是 Edge 自带的同步功能，是开启的。

![image](https://user-images.githubusercontent.com/389973/116394031-fa00ae80-a854-11eb-9edb-b6d02edc3c71.png)

**Comment by runningwaterpro** [comment]
哈哈，看了一下简悦网站，原来同步助手是个软件呀。

**Comment by runningwaterpro** [comment]
奇怪了，在 Chrome 版本 89.0.4389.90（正式版本） （32 位）上，仅安装暴力猴扩展，之后安装轻读版脚本，版面宽度也不起作用。

**Comment by yanzhaochen** [comment]
简悦（2.1.0）在 Windows 10（19042.928）的 Edge（版本 90.0.818.46（官方内部版本）（64 位））出现同样的问题，版面宽度调整完全不起作用。
而且在所有网页进入阅读模式都无法调整宽度。这个问题已经存在好几个月了。

- 在 隐身模式下，仅启用简悦 排除其它扩展的干扰，看看是否可用？否。
- 扩展端导出配置（然后重置）看看能否解决？否。
- 是否使用同步助手？否。

**Comment by Kenshin** [comment]
@runningwaterpro @yanzhaochen 

嗨，各位，我好像知道原因了，「破案」了。 😂 

是 https://github.com/Kenshin/simpread/issues/2076#issuecomment-828367562 提供的截图给了我思路。

### 造成原因

> 简悦因为会适配手机页面，所以有对应的 CSS 样式方式，但它在 Surface Pro（或某些均有触屏的 Windows 系统）下面会被误判定为「手机端」，所以出现了这个情况。

### 解决方案

通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决，我直接给出解决方案

在自定义样式中加入下面的代码，然后 **刷新进入阅读模式的页面后** 生效。

```
sr-read {
   margin: 20px 13%!important;
}
```

- 第一个值 → 是版面的上下宽度
- 第二个值→  是版面的左右宽度

> 值支持：`xxpx`（绝对值） `xxx%`（相对值）

唯一的缺点：无法手动条件，但好在相对来说屏幕都是固定大小的，这个值基本上不太会经常改动。

另外，新版会有更方便的设置这个值的方案。

***

@yanzhaochen 

看看你的 PC 是否也跟 https://github.com/Kenshin/simpread/issues/2076#issuecomment-828367562 截图中的提示一样 **在右下角**，如果是的话，则是一样的问题。

**Comment by runningwaterpro** [comment]
@Kenshin 通过设置提供的自定义样式，正常了，非常感谢～另外，我的电脑的确是触屏的。

**Comment by yanzhaochen** [comment]
@Kenshin 没错，我的设备是 surface pro 6，通过您提供的方案已成功解决版面宽度问题🙏🏻。由于习惯了简悦开箱即用的便捷，没有使用过自定义样式，通过您的提醒，添加了媒体查询，当浏览器窗口比较宽时，增加两边的空白比例，由此解决了问题。

版面宽度调整的失效之所以会成为一个问题，在我这里是因为当最大化浏览器窗口时，文本版面宽度达到 24 寸屏幕的 90% 会造成阅读困难（每一行字都太长了，个人感觉是 24 寸屏幕的 60% 宽度较为舒适）。

```
@media (min-width: 1400px) {
    sr-read {
        margin: 30px 20%!important;
    }
}
```

感谢您的热心回复，期待下一版本解决这个问题

**Comment by Kenshin** [comment]
@runningwaterpro 

> @Kenshin 通过设置提供的自定义样式，正常了，非常感谢～另外，我的电脑的确是触屏的，推测得丝毫不差呀。

哈哈，我也有 Surface Pro 7 ，因为看到了你的截图再加上之前也有人反馈过这个问题（但他的描述相对准确，所以很容易就判断出来了。


@yanzhaochen 

> @Kenshin 没错，我的设备是 surface pro 6，通过您提供的方案已成功解决版面宽度问题🙏🏻。由于习惯了简悦开箱即用的便捷，没有使用过自定义样式。

简悦的灵活性很强，所以有各种玩法，自定义样式只是早期的功能之一。  😀 

总之，搞定这个「奇怪」问题就好，祝你们有个清闲的小长假~

**Comment by Kenshin** [comment]
@runningwaterpro @yanzhaochen 
嗨，忘记说了，简悦五一有个抽奖，如果未在 Chrome 或 Edge 五星好评的话，可以试试抽奖。

Chrome https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

Edge https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc

***

### 抽奖方法
1. 每五名用户即赠送一个中奖名额
2. 到截至日后，如不足五名，四舍五入
（划重点）也就是，每五个人就一定有一人中奖。
3. Chrome Webstore 与 Edge 应用商店分别统计，可同时提交评价。

如果能上 TG 群的话 https://t.me/simpread 最好，否则抽完奖，我在这里通知你们。

**Comment by runningwaterpro** [comment]
评价并加群了，免费版对我已经是大材小用了，高级版留给他人吧～嘿嘿

**Comment by yanzhaochen** [comment]
😄你们做得太棒啦，已评价并加群~

**Comment by Kenshin** [comment]
@runningwaterpro @yanzhaochen

哈哈，因为我不知道你们的 ID，抽中了就是中了。

谢谢喜欢简悦 & 评分。
