### ISSUE TITLE
在英文界面下，如果标注内容较短，因英文词频较高导致标注位置错误

### ISSUE THREAD

**Issue by litao06370** [Kenshin/simpread#2077]
阅读模式下,使用标注后(图1).
退出阅读模式,重新进入此网页;
标注内容突变了(图2).
问题URL:https://www.shanbay.com/news/articles/ahynn

图1:
![a1](https://user-images.githubusercontent.com/43006082/116338670-b420f780-a80e-11eb-8b02-0cef8077d89c.png)

图2:
![aa2](https://user-images.githubusercontent.com/43006082/116338698-bc793280-a80e-11eb-8edf-f092fe976dd2.png)

**Comment by Kenshin** [comment]
嗨，这是个 Bug  可能在英文环境下，因为词频比较高导致的。

PS：我无法登录这个页面，你试着标注更多的内容，看看如何？

**Comment by litao06370** [comment]
> PS：我无法登录这个页面，你试着标注更多的内容，看看如何？

![b1](https://user-images.githubusercontent.com/43006082/116360001-0cb5bc00-a832-11eb-8234-b3ccb453abdc.png)
![b2](https://user-images.githubusercontent.com/43006082/116360004-0e7f7f80-a832-11eb-8439-3aec519eefa6.png)

**Comment by Kenshin** [comment]
谢谢反馈，确实有个问题，应该就是词频的问题。

我看看能否简单解决掉（因为新版就快发布了，所以有些功能不打算再继续，否则又要延迟发布了。）

请问，如果你经常阅读英文的话，看看其它是否也存在这样的情况。（我刚测试了几个，只有一个有点问题）

**Comment by litao06370** [comment]
> 请问，如果你经常阅读英文的话，看看其它是否也存在这样的情况。（我刚测试了几个，只有一个有点问题）

此网页也会出现问题,比如 https://www.quword.com/ciyuan/s/hypo

**Comment by Kenshin** [comment]
> https://www.quword.com/ciyuan/s/hypo

okay 「素材」够了~

我看能否简单解决它，如果不能的话，我会在大版本发布后，会再发几个补丁版本（请耐心等待，如果还不行的话，等 Fixed 后，我会出一个离线版给你用。

**Comment by litao06370** [comment]
> okay 「素材」够了~
> 
> 我看能否简单解决它，如果不能的话，我会在大版本发布后，会再发几个补丁版本（请耐心等待，如果还不行的话，等 Fixed 后，我会出一个离线版给你用。

拿着这个问题就结束了,
如果有其他需要协助的,我乐意和其他朋友一起,让简悦做的越来越好.
(我也就是前天刚开始使用简悦,并在了解了基本功能后,升级了账户;
喜欢软件中一些有创意的小功能,不过也在使用过程中有一些觉得不太喜欢的界面设置,等新版本发布后再看看吧;
个人也喜欢倒腾这那的 -.-)

**Comment by litao06370** [comment]
> okay 「素材」够了~
> 
> 我看能否简单解决它，如果不能的话，我会在大版本发布后，会再发几个补丁版本（请耐心等待，如果还不行的话，等 Fixed 后，我会出一个离线版给你用。

拿着这个问题就结束了,
如果有其他需要协助的,我乐意和其他朋友一起,让简悦做的越来越好.
(我也就是前天刚开始使用简悦,并在了解了基本功能后,升级了账户;
喜欢软件中一些有创意的小功能,不过也在使用过程中有一些觉得不太喜欢的界面设置,等新版本发布后再看看吧;
个人也喜欢倒腾这那的 -.-)

**Comment by Kenshin** [comment]
修复后我会在这里通知你~

谢谢对简悦的喜欢。至于有问题的地方，如提到的：界面问题，下个版本会更优化的界面。

**Comment by Kenshin** [comment]
嗨，扇贝阅读已经适配，请更新适配列表

![image](https://user-images.githubusercontent.com/81074/130352745-f125619f-2226-4e31-8b7e-cd41b11c347c.png)

### 进阶使用

另外，也可以使用 [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 获得更好的使用方案，如下图：

![iShot2021-08-22 18 57 05](https://user-images.githubusercontent.com/81074/130352775-4ade5777-09bd-453c-bd54-96f80ade844f.png)

### 备注

使用翻译后的结果（双语）支持导出 HTML / Markdown 等格式。

***

PS：至于你说的这个问题其实还存在，不过如果非单词标注的，而是小部分标注的话，是没问题的。

![image](https://user-images.githubusercontent.com/81074/130388927-8902192d-5700-4388-8025-2b1caad1a643.png)

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
