### ISSUE TITLE
推送到Instapper或者Pocket的内容并非简悦处理后的而是原网页

### ISSUE THREAD

**Issue by TheKiteRunning** [Kenshin/simpread#208]
您好，如题，个人利用阅读网页的流程是：简悦看个大概，保存到Instapper或者pocket，用calibre的recipe把多个网页抓成杂志形式。如果直接用Instapper抓，比较凌乱。

简悦有强大的内容抽取功能，请问有没有可能推送到其它平台时，推送内容为简悦抽取的部分，而不是原网页呢。

非常感谢！

**Comment by Kenshin** [comment]
感谢建议~
「推送到其它平台」是指什么？
目前简悦可以将 **整理后的页面** 发送到 生产力工具，当前除了 Pocket Instapaper 这类针对 url的服务。

**Comment by TheKiteRunning** [comment]
您好，其它平台刚好指的是Pocket和Intapaper这类网站，您指的生产力工具是印象笔记这些吗？目前遇到的问题是，收集到印象笔记的一般是参考性资料。对于需要好好思考后整理的资料，更希望先发到Kindle上看。

正如上面所说，我没有直接使用简悦发送到kindle，**一方面发现简悦调用的Kindle服务，并没有将简悦整理后的页面发过去**；另一方面，如[170](https://github.com/Kenshin/simpread/issues/170)所言,更希望将**多个网页一起稍后阅读**。Instapper和calibre 配合可以发送带目录的杂志到Kindle上，便于深入阅读和后期整理。

这个问题似乎又成了问题[170](https://github.com/Kenshin/simpread/issues/170)了，因为您这边整理时并没有新的url～

**Comment by Kenshin** [comment]
回复晚了，最近再休假… 😥

发送到 Kindle 是整理后的页面，但 Pocket / Instapaper 不是整理后的页面。

Evernote / Onenote 也是整理后的页面。

请问，Instapper和 calibre 是如何配合的，能否详细说明？

**Comment by TheKiteRunning** [comment]
您好，calibre自带的杂志抓取功能，里面有instapaper抓取，而且发送到kindle上为杂志格式。
![image](https://user-images.githubusercontent.com/24802332/35480600-b9e5ae7c-044c-11e8-8d7a-b54e0226f44a.png)

![image](https://user-images.githubusercontent.com/24802332/35480628-5149f192-044d-11e8-91cb-88ef6d81fe2d.png)

发送到kindle上的就不截图了，标准的杂志格式。
