### ISSUE TITLE
希望可以给动作加上快捷键

### ISSUE THREAD

**Issue by ryanliag** [Kenshin/simpread#2083]
其实简悦中的大部分功能对于我来说并不会用到，主要的导出方式是本地和notion，所以希望可以允许给这些动作添加快捷键，或者让用户自定义热键，可以让流程便捷很多。
![image](https://user-images.githubusercontent.com/35890564/116495448-7b982100-a8d5-11eb-97d3-3c69e380fd53.png)

另外，如果让用户自定义指定一套动作作为自己的工作流程，只用一次操作即可，这样会更好哦~

**Comment by Kenshin** [comment]
嗨，简悦支持大量的快捷键，你可以在 http://ksria.com/simpread/docs/#/快捷键 查看。

另外，你也可以安装下面两个插件

- https://simpread.ksria.cn/plugins/details/7gcXYY4HAc
- https://simpread.ksria.cn/plugins/details/DxlFcL52iy

所以，我先关闭此 Issues 了，有问题的话，请再重开它。

**Comment by Kenshin** [comment]
嗨，关于工作流的话，新版有更好的方案，所以我重开这个 Issues 发布后会在这里通知你。

**Comment by Kenshin** [comment]
忘记说了，简悦五一有个抽奖，如果未在 Chrome 或 Edge 五星好评的话，可以试试抽奖。

Chrome https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

Edge https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc

***

### 抽奖方法
1. 每五名用户即赠送一个中奖名额
2. 到截至日后，如不足五名，四舍五入
（划重点）也就是，每五个人就一定有一人中奖。
3. Chrome Webstore 与 Edge 应用商店分别统计，可同时提交评价。

如果能上 TG 群的话 https://t.me/simpread 最好，否则抽完奖，我在这里通知你们。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

**[2.2.0.520](http://ksria.com/simpread/changelog.html)** 增加了自动化功能，细节 [请看这里](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%8C%96)

![image](https://user-images.githubusercontent.com/81074/121989014-f78af180-cdcd-11eb-8447-d349ee1ccd97.png)


## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

## 评分

- Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
- Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
