### ISSUE TITLE
获取Notion Page时出错

### ISSUE THREAD

**Issue by ryanliag** [Kenshin/simpread#2084]
如图：
![image](https://user-images.githubusercontent.com/35890564/116495871-61127780-a8d6-11eb-989e-53d1dc4ef57a.png)

在第一次保存Notion时默认获取第一个Page的位置没有问题，但是我如果想要切换Page就会出错，依旧是使用上一次的位置。

**Comment by Kenshin** [comment]
嗨，这是正常的，提示上已经说的很清楚了。

因为使用了私有 Notion API 导致不会很完美，所以当你的 Page 设置比较「复杂」的话，就会出现这个情况，然后默认选择第一个，确保 100% 可以保存成功。

PS：关于 Notion 的其它问题，也可以看下 https://github.com/Kenshin/simpread/discussions/1773 的说明

我先关闭此 Issues 了，有需要请重新开启它。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
