### ISSUE TITLE
pubmed网站看文献用阅读模式不适配

### ISSUE THREAD

**Issue by jierme** [Kenshin/simpread#2089]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4377320/ 在此类网站上打开阅读模式，会丢失大片内容

![image](https://user-images.githubusercontent.com/57268924/116523538-ec0c6580-a908-11eb-8fc1-a25756a5c541.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

新版会有个比较好的解决方案，虽然不是 100% 成功，但效果会好很多。
我先记录下来，可以单独适配这个页面。

请问你经常浏览一些文献类的网站吗？如果是的话，能否多告诉一些？

**Comment by jierme** [comment]
> 嗨，谢谢反馈。
> 
> 新版会有个比较好的解决方案，虽然不是 100% 成功，但效果会好很多。
> 我先记录下来，可以单独适配这个页面。
> 
> 请问你经常浏览一些文献类的网站吗？如果是的话，能否多告诉一些？

1. 此网站下参考文献在阅读模式下的格式错误：
https://journals.biologists.com/bio/article/2/12/1397/34350/Evaluation-of-visible-implant-elastomer-tags-in
![image](https://user-images.githubusercontent.com/57268924/116969911-a75a4300-ace9-11eb-966c-6ea42f89f802.png)

1. sciencedirect在已经有权限访问全文的情况下，阅读模式下文章显示不全
https://www.sciencedirect.com/science/article/pii/S0167876014000026#f0005
阅读模式：
![image](https://user-images.githubusercontent.com/57268924/116970189-19328c80-acea-11eb-97fa-b791f179cc8b.png)
退出阅读模式：
![image](https://user-images.githubusercontent.com/57268924/116970510-b5f52a00-acea-11eb-9d05-d45c0b7d7d15.png)

**Comment by Kenshin** [comment]
谢谢提供一些科研文献类的页面给我，这些网站适配后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，我在五一期间适配了你提到的这些网站，除此之外还包括以下几种常见的科研类页面。

- [https://www.sciencedirect.com/](https://www.sciencedirect.com/)
- [https://www.ncbi.nlm.nih.gov/](https://www.ncbi.nlm.nih.gov/)
- [https://journals.biologists.com/](https://journals.biologists.com/)
- [https://www.cell.com/cell/home](https://www.cell.com/cell/home)
- [https://elifesciences.org/](https://elifesciences.org/)
- [https://www.pnas.org/](https://www.pnas.org/)
- [https://science.sciencemag.org/](https://science.sciencemag.org/)
- [https://www.nature.com/]()
- https://www.frontiersin.org/journals

#### 特点

> 简悦适配的这些科研期刊，并不是 **简单的将正文提取出来**，而是 **根据学术文章一般有固定的格式**，如：`title` `abstract` `results` `discussions` `methods` `references` `acknowledgements` `highlights` 进行适配的。

所以，满足一般科研期刊的使用规律，且可显示 **数学公式 LateX** 等仅 **简悦的阅读模式独有的功能**。

#### 如何更新

> 请看 [官方适配源](http://ksria.com/simpread/docs/#/站点适配源?id=官方适配源)，更新后可打开 [这些示例网站](https://github.com/Kenshin/simpread/discussions/2103) 后进入阅读模式查看。

***

关于这部分的说明（以及如何使用）请前往 👉  [https://github.com/Kenshin/simpread/discussions/2103](https://github.com/Kenshin/simpread/discussions/2103) 查看详细说明。

***

没问题的话，请关闭此 Issues ~
