### ISSUE TITLE
[月光博客]新站点适配

### ISSUE THREAD

**Issue by nuomi1** [Kenshin/simpread#209]
``` json
{
    "name": "williamlong.info",
    "url": "http://www.williamlong.info/archives/*.html",
    "title": "<h1 class='post-title'>",
    "include": "<div id='artibody'>"
}
```

另外的：

1. BUG
**站点管理器** 的 **自定义适配源** 只有 1 条规则的时候，点击无法弹出下拉选项。
2. 建议
在 **站点管理器** 的 **自定义适配源** *或* **网页** 的 **站点编辑器** 添加导出 json 格式的规则的按钮，以便直接提交 issue。
3. 疑问
如上规则的 **url** 中，使用 `http://www.williamlong.info/archives/*.html` 和 `http://www.williamlong.info/archives/` 都可以适配，不知道区别在哪里？
**站点管理器** 新建规则，**域名** 填写 `http*://www.williamlong.info/archives/` 提示 `请输入有效的 url`？

**Comment by Kenshin** [comment]
感谢提交以及反馈～
近期外休假，回复晚了。

Bug 只能稍后改了，估计是边界测试不全造成的。
很棒的建议，我会在下个版本实现。

带*号的根据 https://github.com/isaacs/minimatch 的适配规则，不带*
是我自己写的规则，这部分可以看 https://github.com/Kenshin/simpread/wiki/站点编辑器 的说明

**Comment by Kenshin** [comment]
你好，久等了，已新增此站点，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
