### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by yinandong** [Kenshin/simpread#2092]
发生问题的地址: <https://www.sciencedirect.com/science/article/pii/S0921800921001233>

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~

***

另外，有时间的话，可以探讨下：你存入这个页面到印象笔记的为了什么，转存离线吗？如果只是这个观点的话，可以完全使用 离线 HTML 而没必要使用印象笔记。

因为我看到你提到的链接，猜测你应该是个科研工作者（有此方向的学生），进而想讨论下~
