### ISSUE TITLE
稍后读中选择文本时存在问题。

### ISSUE THREAD

**Issue by KeithTMaxwell** [Kenshin/simpread#2096]
按住鼠标拖动选择文本时，
鼠标接近文本右侧约5个中文附近，
会直接将所有剩下的文本选择。

![image](https://user-images.githubusercontent.com/24669432/116716450-5953ef80-aa0a-11eb-9a0a-696b1dd2aee5.png)

![image](https://user-images.githubusercontent.com/24669432/116716509-6c66bf80-aa0a-11eb-9f86-bde536fa2e44.png)

**Comment by Kenshin** [comment]
谢谢反馈，这算是「正常的」。
侧栏会占有一部分「隐藏空间」，当你的分辨率较小时会误触到它。

**解决方案**：

将侧栏最小化就好了，下图

![image](https://user-images.githubusercontent.com/81074/116767198-4ae4f280-aa61-11eb-8411-9809b71cd2b6.png)

**Comment by KeithTMaxwell** [comment]
感谢回复，如所说的操作，已经解决

**Comment by Kenshin** [comment]
搞定就好~  😁
