### ISSUE TITLE
描述无法隐藏

### ISSUE THREAD

**Issue by Dradows** [Kenshin/simpread#2099]
![QQ截图20210505022032](https://user-images.githubusercontent.com/32986753/117051000-a1477f00-ad48-11eb-9001-3137a323f385.png)
![QQ截图20210505022218](https://user-images.githubusercontent.com/32986753/117051612-524e1980-ad49-11eb-9462-693e1e72a606.png)

如图所示，删掉描述后阅读模式里还是有描述，并且不同页面的描述都变成了添加站点规则那个页面的描述了。
另外还有个问题是 隐藏任意元素 仅在第一次框选的时候有效，一旦刷新或者切换到其他页面后虽然隐藏列表里还有那个规则，可就是不起作用。

最后还有个建议，在这种小说网站左右切页的时候能不能无缝衔接？目前会先打开原网站然后再快速进入阅读模式，可是如果原网站是白色背景而阅读模式是深色背景的话在晚上就相当于屏幕突然闪一下，体验很不好

**Comment by Kenshin** [comment]
嗨，简悦的 `描述` 是必备项目，无法隐藏。但是你可以通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 来实现。

以及 站点的自定义样式 来实现。（建议使用后者，即在：第一个截图的下方加入如下代码：

```
sr-rd-desc {
    display: none;
}
```

> 仅在第一次框选的时候有效，一旦刷新或者切换到其他页面后虽然隐藏列表里还有那个规则

新版可以优化这个过程，当前的版本你需要 将这个站保存下，下次应该就没问题了。也就是第一个图需要保存，如果保存后仍出现，说明你的 URL 填写错误，不过，我看第一个图的填写应该没问题。

***

另外，看小说的话，有个油猴脚本很不错，你可以试试 **My Novel Reader**

**Comment by Kenshin** [comment]
嗨，我看到你又新开了一个 Issues，当前这个 Issues 没问题的话，我关闭它了。
