### ISSUE TITLE
掘金 无法 阅读模式 

### ISSUE THREAD

**Issue by suguohui** [Kenshin/simpread#21]

**Comment by Kenshin** [comment]
感谢回复~

掘金目前包括两种类型的 URL：
- `https://juejin.im/post/*` 如 https://juejin.im/zhuanlan/all 这个栏目下面的网址都适配
- `https://juejin.im/entry/*` 如 https://juejin.im/entry/593e5be18d6d810058995e80 

![Imgur](http://i.imgur.com/IK3m92l.png)

除此以外的页面还未适配。

哪些页面可以被适配取决于当前页面是否具有阅读必要。

不过，现在的确有个问题，当使用 `右键菜单 → 使用阅读模式打开此项目时` 会无法显示，原因是掘金的页面采用了 ajax 加载方式，下个版本 `1.0.1` 会修复这个问题。
当然，如果等页面加载完毕后再进入 `阅读模式` 也可以。
