### ISSUE TITLE
阅读模式生成目录字体过小

### ISSUE THREAD

**Issue by sleeepyy** [Kenshin/simpread#210]
阅读模式生成目录字体过小
![tim 20180116153242](https://user-images.githubusercontent.com/14780887/34976678-92c4626c-fad2-11e7-8eb7-6773c2058edf.png)

**Comment by Kenshin** [comment]
可以通过 自定义样式解决。
之所以为什么没有单独的选项，因为每个人的感受都不一样，或许有人觉得比较大。
所以众口难调，所以最好的办法也是通过自定义样式一次性解决掉。 😊

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
1.1.1 将 TOC 转移到了左侧，解决了偶尔被遮挡的问题。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
