### ISSUE TITLE
隐藏列表不生效

### ISSUE THREAD

**Issue by Dradows** [Kenshin/simpread#2101]
描述问题已经解决，但隐藏列表还是存在问题
在隐藏列表的规则里添加了
```
[['<p>笔趣阁 www.xbiquge.cc，最快更新少年歌行 ！</p>']]
[[`/html[1]/div[1]/sr-read[1]/sr-rd-content[1]/p[1]`]]
[[{$('sr-rd-content p:first')}]]
[[[$('sr-rd-content p:first')]]]
[[{$('sr-rd-content p:first').hide()}]]
```
都无法正确隐藏，倒是在自定义css里添加
```
sr-rd-content p:first-child {
    display: none;
}
```
可以隐藏

**Comment by Kenshin** [comment]
嗨，这个问题我需要确认下，看起来你是想隐藏类似下图的内容吧？

![image](https://user-images.githubusercontent.com/81074/117131093-8e2dc100-add3-11eb-8302-49b47cbbafac.png)

明天给你答复。

**Comment by Dradows** [comment]
是的，第一段 “笔趣阁 www.xbiquge.cc……”




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, May 5, 2021 07:00 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Kenshin/simpread] 隐藏列表不生效 (#2101)





 
嗨，这个问题我需要确认下，看起来你是想隐藏类似下图的内容吧？
 

 
明天给你答复。

**Comment by Kenshin** [comment]
嗨，我简单的测试了下，确实排除列表暂时无法使用，修复后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，确认是因为一个 Bug 引起的，已修复了，但只能下个版本发布后才可以了。

目前的解决方案：

> 就是你说的方式：用 CSS 来解决

**Comment by Kenshin** [comment]
嗨，因为我发现你会适配规则，所以指出几个地方：

> 下面几个方式均没有问题（目前不生效是因为 Bug 引起）

```
[['<p>笔趣阁 www.xbiquge.cc，最快更新少年歌行 ！</p>']]
[[`/html[1]/div[1]/sr-read[1]/sr-rd-content[1]/p[1]`]]
[[[$('sr-rd-content p:first')]]]
[[{$('sr-rd-content p:first').hide()}]]
```

> 下面这个是错误的

```
[[{$('sr-rd-content p:first')}]]

```

因为 `[[{}]]` 是一个 **自执行函数**，所以正确的写法是 `[[{$('sr-rd-content p:first').hide()}]]`

***

> 按照已知 Bug 可以这么写

```
[[{(()=>{setTimeout(()=>{$('sr-rd-content p:first').hide()},200)})()}]]
```

***

另外，如果 **你有自行适配但简悦没有适配** 的页面可以告诉我。我会考虑把它们合并主适配源。
