### ISSUE TITLE
Notion 网页版无法使用阅读模式吗？

### ISSUE THREAD

**Issue by phh95** [Kenshin/simpread#2104]
切换到阅读模式后，Notion 页面的内容丢失了

我的需要是想将 Notion 切换到阅读模式后，借助简悦的导出 Markdown 功能，将 Notion 文档导出为 Markdown

**Comment by Kenshin** [comment]
嗨，我是你微信订阅号的订阅者，很喜欢你的写的 **效率工具指南**。

***

简悦原本不是做这个事情的，但一般来说只要是有正文的话，都可以提取，但 Notion 效果不是很完美。
原因是：Notion 页面不仅只包含文字 / 图片 / 媒体资源，还有一些 Embed 的页面，以及它也包含丰富的布局，导致正文匹配会失败

虽然我也用 Notion，不过还是建议给出一些可以做适配的「样本」，如：不方便的话，在推上私信我也可以~

**Comment by phh95** [comment]
哇，感到真荣幸哈哈哈哈，我刚想去推特给你发私信，不过显示无法向你发私信，我去微博发私信吧

**Comment by Kenshin** [comment]
嗨，专门适配了 Notion 的页面，包括你在私信里面提到的，如何配置请看这里 https://github.com/Kenshin/simpread/discussions/2106

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
