### ISSUE TITLE
能否新增支持连接并授权Wolai笔记？

### ISSUE THREAD

**Issue by kylisss** [Kenshin/simpread#2109]
目前已经支持了Notion等笔记的阅读内容导出功能，能否新增支持Wolai笔记的内容导出？
（Wolai：www.wolai.com，一个国产本地化做的比较好的类Notion块编辑工具）

**Comment by Kenshin** [comment]
嗨，如果它有公开的 API 的话是可以的。
不过，简悦新版有关于此的一些简单「折中」解决方案，发布后我会在这里通知你。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
