### ISSUE TITLE
站点编辑器自动弹出

### ISSUE THREAD

**Issue by FastStonewkx** [Kenshin/simpread#2114]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **  Windows 10 专业版**

- 浏览器版本 ** Chrome 89.0.4389.82**

- 简悦版本 **2.0.0**

- 发生问题的地址 <任意网址> 例子https://blog.csdn.net/weixin_39786569/article/details/116481216?spm=1000.2115.3001.5928

**请描述你的问题**

我是任意文章下，当进入阅读模式，站点编辑器都是无法点击，编辑的甚至是关闭的，除非刷新，推出阅读模式。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/36177654/117473263-57e77180-af8c-11eb-8c2f-dd2700923c06.png)

还有浮动菜单栏也是乱的

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by FastStonewkx** [comment]
我描述的问题，包括使用谷歌的devtool工具都无法关闭这个弹窗，很烦

**Comment by Kenshin** [comment]
我没理解你的意思。

> **站点编辑器是不会无故出现的，除非你点击它或通过快捷键。**

还有种可能性，你是不是同时安装了两个简悦？去 `chrome://extensions/` 看看。

如果你不是高级账户，可以选择重新安装简悦来解决你的问题；反之的话，在选项页 → 共通 → 导出配置文件，然后重装。

***

最后，简悦不会无故出现奇怪问题，除了十几万用户没提过这个问题外。我每天都在用它，除此以外，对于大多数用户来说我使用的方法与手段更复杂，如果出现问题，我将是第一个发现的用户。

**Comment by FastStonewkx** [comment]
感谢提醒，其实说不上来多转了一个。是微软的斯巴达浏览器我也装了一个简悦。删了后就恢复正常了！

但是这个有些bug。只能有一个谷歌浏览器安装这个插件，多安装一个就出问题了吗，理论上应该不受影响的吗。

关键是我使用谷歌浏览器和微软浏览器的场景有些不同，但是也想都使用简悦插件。

**Comment by Kenshin** [comment]
嗯，简悦的一个特点的：页面注入代码。
虽然从代码逻辑上可以判断，但这样会很「繁琐」，且这个问题本身也属于异常情况。

PS：一般，极特殊的情况下是允许出错的，否则代码中加入太多的「不确定性」了。

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/117536549-3212a900-b02e-11eb-9f3a-02cd475d2ff8.png)
我以为解决了，但是好像没有

**Comment by FastStonewkx** [comment]
咋联系你，qq连线看看

**Comment by FastStonewkx** [comment]
还是没有解决，后面再试试吧

**Comment by FastStonewkx** [comment]
重装了，斯巴达浏览器是正常的。谷歌浏览器有问题，可能是我的浏览器是最新内核吧

**Comment by Kenshin** [comment]
> 谷歌浏览器有问题，可能是我的浏览器是最新内核吧

跟这个肯定无关的，我的也是新的。（几乎能肯定的是）还是浏览器的问题。再找找吧~  😅

**Comment by Kenshin** [comment]
哈哈，搞定就好。（太难了...  😅
