### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by mayunchak** [Kenshin/simpread#2119]
发生问题的地址: <https://www.bilibili.com/video/BV1c64y1Z7U6?p=39

**Comment by Kenshin** [comment]
嗨，这个页面没有适配阅读模式的必要，我关闭此 Issues 了~

**Comment by mayunchak** [comment]
好的，谢谢🙏

发自我的iPhone

在 2021年5月9日，下午3:38，Kenshin Wang ***@***.***> 写道：

﻿

嗨，这个页面没有适配阅读模式的必要，我关闭此 Issues 了~
