### ISSUE TITLE
扩展栏按钮交互问题和一些建议

### ISSUE THREAD

**Issue by heartacker** [Kenshin/simpread#212]
当遇到适配好了的网站的时候，发现，点击扩展icon，就可以进入阅读模式。但是进入阅读模式之后。再点一次icon竟然是设置，我觉得这个交互有问题。严重的问题。
第一，这个icon相当于一个开关。点一下进入阅读模式。再点一次退出阅读模式。这是很符合常理和用户习惯的。
至少我到现在一直都是在这样，。已经适应了好几次了还是觉得很难用。
所以所以建议：

- 点击icon
 开启/关闭阅读模式!

- 进入阅读模式之后
背景和内容的背景颜色要分开。这样第一有层次感，第二免得所有东西都是一个背景，让用户抓不到重点。

- 双击背景空白处退出阅读模式。
阅读模式每次退出都是点击有下角，感觉没有那种畅快淋漓的感觉。

- 如果加入了左右分栏或者左右翻页的模式
那么建议左右两边各增加一个按钮。用来翻页。

以上仅仅我体验完之后，结合自己的习惯之后的的建议，当然我也是思考过的。觉得这样可能更好。

谢谢作者。

**Comment by Kenshin** [comment]
感谢反馈！

icon 的点击逻辑是有些问题。

你说的一部分功能已经实现，请看 【设置 → 高级设定】 部分。

双击退出的功能可以考虑实现的。 😃 目前聚焦模式也是这个方式。

样式（主题）的建议可以通过自定义样式解决。（凡事跟样式有关联的建议我都建议通过此方式解决，毕竟审美和观感每个人都不一样。）
如果你有好的自定义样式，可以分享出来，为其他人所用。

左右分栏的设计还在考虑中，当然会参考你的意见。

**Comment by Kenshin** [comment]
请不要关闭此 issues，对我是个提示，并且此功能如果实现，我会关闭它（相当于通知到你）
如果不想得到这个 issues 的消息，请选择 Unsubscribe 即可。
我将重新开启此 issues  😃

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，

右上角的 icon 点击后的动作可选。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
