### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by xiaoyifeng666** [Kenshin/simpread#2120]
发生问题的地址: <https://stackoverflow.com/questions/36302347/leanback-library-how-to-draw-focus-for-items-in-a-verticalgridview-or-horizont

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

这个站的规则改变造成的，修复后会在这里通知你~

**Comment by Kenshin** [comment]
嗨，这个站的适配规则已经更新，请使用下图的方式手动更新，位置在 选项页 → 站点管理

![image](https://user-images.githubusercontent.com/81074/120067368-c8763f80-c0ad-11eb-8706-3b0e6798641d.png)

我关闭这个 issues 了。
