### ISSUE TITLE
Spring官方文档

### ISSUE THREAD

**Issue by HAjiMa666** [Kenshin/simpread#2128]
它的代码块无法高亮显示,用代码增强插件

**Comment by Kenshin** [comment]
在微信订阅号的页面确实有这样的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
