### ISSUE TITLE
简悦能否加入在特定网站上完全禁用的功能？

### ISSUE THREAD

**Issue by corinlee** [Kenshin/simpread#2130]
win10系统，Chromium86版本，简悦2.1版本
打开https://www.kanzhiqiu.com/newreport/ 这个网站时，登陆后页面就会发生崩溃卡死的情况（详见附件图片），经过反复尝试，最终发现是跟简悦插件的冲突
但奇怪的时，崩溃时我并没激活简悦的阅读模式，而是只要简悦插件是启用的状态就会崩溃
由于这个网页经常会用，所以我现在只能把整个简悦插件暂时禁用掉
所以想问K大，如果暂时找不出这个页面的问题出在哪，那我能否设计一个功能，自动在特定网页上屏蔽掉简悦插件，而在其他网页上就不屏蔽？

![微信截图_20210512170016](https://user-images.githubusercontent.com/50066235/117948273-904bce80-b343-11eb-9c58-ca3dc0b249c0.jpg)

**Comment by Kenshin** [comment]
嗨，可以用 [黑名单](http://ksria.com/simpread/docs/#/FAQ?id=%e9%bb%91%e5%90%8d%e5%8d%95) 的方式

将 `kanzhiqiu.com` 加入到黑名单里面就可以了。

**Comment by corinlee** [comment]
> 嗨，可以用 [黑名单](http://ksria.com/simpread/docs/#/FAQ?id=%e9%bb%91%e5%90%8d%e5%8d%95) 的方式
> 
> 将 `kanzhiqiu.com` 加入到黑名单里面就可以了。

感谢答复，加入黑名单就解决了
另外这个问题在ishare.iask.com上也出现了，同样通过黑名单解决了

**Comment by Kenshin** [comment]
哈哈，搞定就好。

没问题的话，我关闭此 Issues 了~
