### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by xuxinsd** [Kenshin/simpread#2131]
发生问题的地址: <http://rmfyb.chinacourt.org/paper/html/2021-05/13/content_204369.htm?div=-1>

**Comment by Joel2561** [comment]
看了一下支持都非常好哇，全文内容都获取到了
![image](https://user-images.githubusercontent.com/77143461/119135634-42387880-ba71-11eb-91c7-9b24bd77b5b0.png)
