### ISSUE TITLE
求助，如何在iOS上使用简悦的稍后读功能？

### ISSUE THREAD

**Issue by samwei12** [Kenshin/simpread#2134]
刚买了简悦的高级账户，主要是看中了稍后读功能的批注相关，然而实际用下来发现，只能在PC上使用，这跟稍后读的碎片化阅读是完全背离的。我目前日常使用的iOS设备，有办法使用稍后读功能吗？？如果不能的话，说实话我感觉我的高级账户基本是废了。。。

**Comment by Kenshin** [comment]
嗨，解释下你的疑惑：

1. 在简悦正规的购买渠道 **已经在明显位置标明了适用的平台**。（所以，不会有支持 iOS 的字样。
2. 简悦会有 iOS，这是毋须质疑的。（但时间线会比较靠后，下面会简单的解释下
3. 简悦是买断制，也就是说，以后推出 iOS 后，已购买用户仍可以使用。

***

简悦已经推出了 API，涵盖了 iOS Android Windows Mac 环境，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/2079)

***

多说一句：

1. 简悦的 **稍后读适合的场景是做深度阅读**。
2. 使用 **稍后读做碎片阅读的场景并不适合简悦**，因为碎片阅读的途径和工具很多，如：各种 RSS 阅读器等。
3. 手机根本就不适合深度阅读甚至于 **标注在手机端使用简直就是个灾难**。

再引申一条：

为什么有使用手机做深度阅读的人群呢？我想这个群体的特点是让 TA 拿着实体按键的黑莓，一样可以做深度阅读，所以跟什么设备无关。

***

最后，[这里记录一些关于简悦 API 的具体使用场景（以及基于简悦的各种新奇玩法）](https://github.com/Kenshin/simpread/discussions/2085)

关于碎片化阅读与深度阅读的使用场景可以看看  https://github.com/Kenshin/simpread/discussions/2085#discussioncomment-732404

**Comment by samwei12** [comment]
可能我的具体使用场景说的不够清楚，我目前的工作流一般是这样：
1. 利用各种rss和微信公众号、知乎等进行信息浏览，
2. 简单了解判断价值后，发送到稍后读软件，例如Pocket
3. 手机上偶尔空闲时间再次进行分类和筛选
4. 电脑上进行深入学习了解，

所以如果可以有更简单的教程直接通过手机微信公众号等发送到简悦的稍后读，我理解也可以满足目前我的需求了。很多稍后读软件在收集方面做得都挺好的。比如Cubox、Pinbox、Pocket等，
有API能够打通当然比较好，但稍显繁琐

**Comment by Kenshin** [comment]
嗨，你的工作流跟我上条说的其实是一样的。
所以，你可以使用 API 来实现，所谓的「繁琐」总共也不会超过5分钟的时间，至少比你打这些字要短。

另外，简悦不是一个单纯的稍后读，作为新用户来说，你可以不了解简悦（和我）。

我从不喜欢重复造轮子，所以既然我做了简悦的稍后读，目前还有这么多的用户，自然有跟其它稍后读不一样的地方。

至于不一样的地方在于：

> 其它的 **稍后读是收藏后不再读**。（所以它们做好了方便收藏的各种手段）

简悦稍后读在于：

> 希望你的稍后读不再不读。会「想尽办法」增加人为的「摩擦力」，让有意义的内容在简悦内化为你自己的知识，这也是简悦作为稍后读却支持导出到其它生产力工具的根本性原因。

> 一般来说，稍后读都会是收藏的终点，也不会有稍后读再可以导出到其它工具。

***

还是那句话，你得理解简悦稍后读的目的，然后再使用它，自然而然就不会觉得奇怪了。

**Comment by samwei12** [comment]
我尝试了一下，切换成坚果云登录，
获取token这一步失败了，
用的是UID方式登录，license是从少数派购买的，
登录时候一直提示 遇到了验证问题

UID：
q1vm2ugd-p6c3-xxex-t7p5-j0q3s2j0xqwe




License：

我就不截全了，

**Comment by Kenshin** [comment]
嗨，UID 也帮你隐去了。

***

至于你的问题，不知道是否对坚果云进行了 [授权登录](https://simpread.pro/api/#/%E5%A6%82%E4%BD%95%E5%BC%80%E9%80%9A?id=%e6%8e%88%e6%9d%83%e5%9d%9a%e6%9e%9c%e4%ba%91) 的操作？

**Comment by samwei12** [comment]
是的 之前是一直用的dropbox   
后来改成用坚果云了，那个授权按钮已经对了，不确定这个有缓存？还是怎么清空重新弄一下，

发自我的iPhone

**Comment by Kenshin** [comment]
> 是的 之前是一直用的dropbox 后来改成用坚果云了，那个授权按钮已经对了，不确定这个有缓存？还是怎么清空重新弄一下， 

嗨，因为你之前提供了 UID，所以我在后台看了下，目前你肯定可以使用 License / UID 方式登录。

**Comment by samwei12** [comment]
可能是公司网络问题吧， 再次在家里尝试成功了，目前已经取得token，但是又遇到了一个新的bug。。。

手机安装捷径，复制公众号链接，点击捷径，提示成功

进入坚果云，发现确实有内容， 且同步时间更新 ，注意看，这里是23：07

手动点击同步配置



这里，时间明明是23：06，且配置中新增了URL



但是提示配置一致，无需更新，因此导致稍后读无任何内容




1. 帮忙看下这个应该算bug吧。。
2. 由于我的公司无法安装坚果云，只能采用手动同步的办法。。。很不方便，是否可以有一些其他方案，例如使用WebDAV，这样我可以在自己的NAS里面使用或者使用坚果云的服务，而不是必须要客户端。

**Comment by samwei12** [comment]
而且还发现了另一个问题，就是配置文件的同步功能，还比较弱，基本不支持增量同步
也就是说，对于拥有多台电脑的人来说（像我基本工作电脑跟家庭使用完全隔离），同步功能基本等于没有
基本上任何改动都会直接提示本地较新或者远程较新，提示覆盖，而不是合并
那么A电脑登录，阅读文章A，点击同步上传
B电脑登录，新增文章B，同步上传，就会把A覆盖掉，只有文章B了，跨设备基本不太可用。。。

**Comment by Kenshin** [comment]
> 基本上任何改动都会直接提示本地较新或者远程较新，提示覆盖，而不是合并

当然不可能出现这个情况了。但是一般来说，API 是对有深度使用简悦的用户提供的。简单的说，一般使用 API 的用户都会开启自动同步方案，自然不会存在你说的问题了。

***

至于你说的 电脑 A 和 B 的问题就是在于：你 **没有使用自动同步方案**。

***

所以，**手动同步的解决方案**：通过 强制覆盖 的方式，如下图

![image](https://user-images.githubusercontent.com/81074/118383678-c2567c80-b632-11eb-9f39-c29b6c428909.png)

当然，使用手动同步的前提是：确保坚果云的数据是最新的，否则就会被覆盖掉。

***

> 有疑问并提出来，其实是好的，其实有些用户因为太固有思维导致了对简悦的使用完全不理解。例如你上面提到的，其实很简单的流程：

1. 购买 License → 注册成为高级账户
2. 使用坚果云作为授权登录方案
3. 在开放平台登录，并获取 Token
4. 下载并配置自动同步
5. 自动同步方案：（确保使用顺序）坚果云客户端 + 同步助手先运行，然后在打开浏览器使用简悦
6. 手动同步方案：使用强制覆盖或手动同步的方式

一共五个步骤，总共配置下来，不会超过5分钟。虽然可能还是有配置时间，但简悦的优势在于：

> 隐私权 + 灵活的收录方式

另外，新版简悦还会在深度阅读上探索的更多，虽然是稍后读，但简悦跟其它稍后读是完全不一样的，稍后读只是个「仓储」而已，每年花个一些订阅费，把一些信息转移到它的仓储里面，久而久之，乱七八糟根本没法整理。

而简悦会帮你将收藏的内容内化为知识（或帮你整理好这些内化的信息）

PS：如果你并不满意你现在的稍后读的使用方式，才建议使用简悦。

***

我在 Pocket / Instapaper 里面有大几千条稍后读，「身受其害」后才开发了简悦的稍后读。

你用的时候就会发现，简悦的使用逻辑之一：是让你不那么顺利的就加条信息进来。通过人为的增加摩擦力，让真正有意义的信息进来。

我会在新版发布后，写一些关于这方面的文章。

**Comment by samwei12** [comment]
有办法不安装客户端，也能自动同步吗？

通过同步助手，自己指定本地的配置文件路径，而不是绑定坚果云
公司限制，有的网盘客户端用不了，有的暂时还能用。。
如果不绑定的话，我可以通过dropbox或者NAS等方式自动同步，

**Comment by Kenshin** [comment]
> 有办法不安装客户端，也能自动同步吗？

暂时没有提供此功能。
