### ISSUE TITLE
插件“代码段增强”运行时出错

### ISSUE THREAD

**Issue by mephisX** [Kenshin/simpread#2136]
![image](https://user-images.githubusercontent.com/30206556/118325235-c486e100-b535-11eb-95d0-7aaba3d7f7ef.png)
网址：https://zh.javascript.info/hello-world

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
