### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by mynameisenthusiasm** [Kenshin/simpread#2138]
网站：
https://www.geeksforgeeks.org/how-to-use-sys-argv-in-python/

结果：
![image](https://user-images.githubusercontent.com/54618402/118345416-e8aee600-b566-11eb-9d3c-66bd888c16f4.png)

**Comment by Kenshin** [comment]
代码高亮出错的吗？

如果是的话嗨，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
