### ISSUE TITLE
能不能对gitbook  kancould这种网站进行自动生成目录 自动添加书签

### ISSUE THREAD

**Issue by hooklife** [Kenshin/simpread#214]
能更方便的阅读 gitbook上的文章了

**Comment by Kenshin** [comment]
看云已经支持了。
Gitbook 还未支持，我记得它们的 url 有规律，这样就能适配了。

**Comment by Kenshin** [comment]
刚刚测试了一下，看云似乎是因为结构改变造成的，我会更新这个站点，另外 Gitbook 应该也没有问题，到时候一起更新。

**Comment by hooklife** [comment]
ok 谢谢～

**Comment by Kenshin** [comment]
避免忘记，我还是 Reopen 比较好。

**Comment by Kenshin** [comment]
你好，久等了，已经增加 Gitbook 适配站点，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
