### ISSUE TITLE
导出的全文包含标注，但是保存在OneNote的全文没有标注，保存在有道云中的全文也不能和标注一起保存呢？

### ISSUE THREAD

**Issue by nihil7** [Kenshin/simpread#2140]
<导出的全文包含标注，但是保存在OneNote的全文没有标注，保存在有道云中的全文也不能和标注一起导出呢？

请问是还没有开发这个功能吗？

**Comment by Kenshin** [comment]
嗨，简单的解释下。

1. 导出到 Onenote 是 HTML，理论上是可以带标注的，但 2.1 版有个 Bug 导致只能导出全文过去。（但这个 Bug 能绕过去，不过新版马上就发布了，建议不要在折腾了。

2. 导入到 有道云笔记 是 Markdown，MD 格式天然对标注不是很友好，所以自然不会有标注。

备注：

上述两个服务，可以导入 **仅标注** 的方案。

**Comment by EternalHXP** [comment]
> 嗨，简单的解释下。
> 
> 1. 导出到 Onenote 是 HTML，理论上是可以带标注的，但 2.1 版有个 Bug 导致只能导出全文过去。（但这个 Bug 能绕过去，不过新版马上就发布了，建议不要在折腾了。
> 2. 导入到 有道云笔记 是 Markdown，MD 格式天然对标注不是很友好，所以自然不会有标注。
> 
> 备注：
> 
> 上述两个服务，可以导入 **仅标注** 的方案。

在标注后, 选择全文+标注
尝试 导出到专注笔记 notion 都没有保存为 先标注文字,后全文, 都是只有全文

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

- 简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

- 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 https://github.com/Kenshin/simpread/issues/2158

**Comment by Kenshin** [comment]
> 在标注后, 选择全文+标注
> 尝试 导出到专注笔记 notion 都没有保存为 先标注文字,后全文, 都是只有全文

![image](https://user-images.githubusercontent.com/81074/119131132-abb58880-ba6b-11eb-8a6f-4f924904f49e.png)

**Comment by Kenshin** [comment]
（接上条

导入到专注笔记的是 Markdown 形式，自然没有无法包含标注的全文。
