### ISSUE TITLE
CSDN 进入阅读模式后点击别人文章前面的目录无法自动跳转

### ISSUE THREAD

**Issue by MJscofield** [Kenshin/simpread#2143]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**chrome mac 阅读模式**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Mac Intel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://blog.csdn.net/m0_46153949/article/details/107152394

**Comment by Kenshin** [comment]
嗨，我这边测试是没问题的。

你可以在 **隐身模式下，仅启用简悦** 试试，排除是否是其它扩展造成的影响。

**Comment by MJscofield** [comment]
你好，我在无痕模式，也就是隐身模式里面，还是没能做到目录段落跳转，在隐身模式中只开启了简悦一个插件功能，mac系统下的最新chrome

**Comment by Kenshin** [comment]
嗨，我好像知道你的问题了，是不是下图的意思？

**Comment by MJscofield** [comment]
> 嗨，我好像知道你的问题了，是不是下图的意思？
> 
> ![image](https://user-images.githubusercontent.com/81074/118440652-90204a00-b71a-11eb-87c9-75bda2034b88.png)
> 
> 如果是的话，这是正常的，文内的目录已经不好使了。

好的，非常感谢您的回复，还以为是我这边哪里出了问题，明白了。

**Comment by Kenshin** [comment]
哈哈，没问题就好。

这样的话，我关闭这个 Issues 了~
