### ISSUE TITLE
请问能否增加一个繁体自动转换为简体的功能

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#2144]
因为很多时候会阅读一些港台的文章

**Comment by Kenshin** [comment]
嗨，可以考虑的。

这个功能放在 To-do 里面好久了。

**Comment by binsee** [comment]
暂时可以用这个插件实现 
[New TongWenTang - Chrome 网上应用店](https://chrome.google.com/webstore/detail/new-tongwentang/ldmgbgaoglmaiblpnphffibpbfchjaeg)

**Comment by tttsong** [comment]
哈哈，浏览器插件我有，但是进入简悦阅读标注就失效了，我需要在阅读，标注的时候都是简体



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: binsee ***@***.***&gt;
发送时间: 2021年5月17日 14:25
收件人: Kenshin/simpread ***@***.***&gt;
抄送: tsong ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Kenshin/simpread] 请问能否增加一个繁体自动转换为简体的功能 (#2144)






暂时可以用这个插件实现
New TongWenTang - Chrome 网上应用店

**Comment by binsee** [comment]
我试了下，确实如此。
使用这个插件，在页面进入阅读模式可以自动转换为简体，标注也是简体的。
但如果先将页面加入稍后读，在稍后读中进入`阅读模式`，将无法转换为简体。

**Comment by Kenshin** [comment]
@binsee @tttsong 

标注的内容存在了配置文件中，所以确实会有问题。如果这样的话，可能简单的插件也不是 100% 能完美解决，单纯的阅读模式，简体 → 繁体是很容易的。

我会考虑考虑的~

**Comment by Kenshin** [comment]
嗨，我制作了 [简繁体切换](https://github.com/Kenshin/simpread/discussions/2517) 这个插件，你可以通过安装此插件来解决。

安装地址 https://simpread.ksria.cn/plugins/details/0sZZtfBYyU
使用方法 https://github.com/Kenshin/simpread/discussions/2517

所以，我关闭这个 issues 了。

**Comment by Kenshin** [comment]
另外，请留意：

1. 此插件无法在稍后读阅读模式中使用
2. 因标注会截取原始字符，所以在简体状态下标注后，再切换到繁体状态，则无法显示标注位置。（繁体状态同理）
