### ISSUE TITLE
[Solidot]修复规则

### ISSUE THREAD

**Issue by nuomi1** [Kenshin/simpread#215]
``` json
{
    "name": "solidot.org",
    "url": "https://www.solidot.org/story?sid=*",
    "title": "<div class='bg_htit'>",
    "include": "<div class='p_mainnew'>",
    "exclude": [
        "[[/src=\\S+(liiLIZF8Uh6yM.jpg)\\S+/]]"
    ]
}
```

``` text
curl -I http://www.solidot.org/story\?sid\=55263
HTTP/1.1 301 Moved Permanently
Date: Thu, 18 Jan 2018 06:45:12 GMT
Server: Apache
Location: https://www.solidot.org/story?sid=55263
Connection: close
Content-Type: text/html; charset=iso-8859-1
``` 

1. 更改了 `url`、`title` 和 `exclude`。
2. ~~网站自动跳转到 `https`，原规则 `http` 依然可以适配，所以这个到底有什么用？建议网站只支持 `http` 的依旧用 `http`，自动跳转 `https` 的用 `https`，两者都支持但不跳转的用 `http*`。要不直接用 `*` 或者去掉算了，还能省点字节（……~~
3. 按照 https://github.com/Kenshin/simpread/blob/master/src/website_list.json 的 `exclude` 编写，`[[src]]` 正则匹配最后多了一个 `'` 单引号，导致匹配失败，去掉后正常？

**Comment by Kenshin** [comment]
感谢适配！

http 与 https 是不一样的，不过这里我设置了一个技巧，我在用手机，等用电脑时，给你详细说明。

简单点说，如果`*`在最后一位的话， http 与 https 的规则一致。

最简单的做法是 http(s)://

**Comment by Kenshin** [comment]
我在用电脑，详细说下 url 的适配规则：

url 的规则分为三种：（假设匹配的 url 为 https://sspai.com/post/39491 ）

- 无 `*` 写法为 https://sspai.com/post/

- 有且只有最后一位是`*` 如 https://sspai.com/post/* 它可以匹配 http 或者 https

- 有且多于一个 `*` 则使用了 [minimatch](https://github.com/isaacs/minimatch) 匹配规则，如 https://sspai.com/*/* 可以匹配 https://sspai.com/post/39491 或者 https://sspai.com/id/39491 等。

为什么有这么多的规则，是因为最开始没有想好 url 的匹配方案，直到找到了 minimatch 但随着使用发现 minimatch 也不是太好用，未来会直接加入正则匹配方式。 

希望使用第三种匹配方案，比如：http(s)://sspai.com/post/* 的方式

不知道能否对你有所帮助~

**Comment by nuomi1** [comment]
强制使用 `*`，使用同一套匹配规则较好。

例如 https://sspai.com/post/ ，直接访问会报错误，此外有些网站会把这样的 URL 定义为文章列表的首页。

简阅会提示页面结构不匹配，但根本就不应该匹配这些 URL。

**Comment by Kenshin** [comment]
嗯，但是为了向下兼容（简悦早期版本没有使用 `*` 的方式）

简悦在向下兼容事情上做了很多工作，为了照顾早期用户，即便简悦的数据结构更改了很多，但仍旧可以导入 1.0.0 的数据！

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
