### ISSUE TITLE
版本更新到2.2后会自动进入阅读模式

### ISSUE THREAD

**Issue by Dradows** [Kenshin/simpread#2156]
确认 如果当前页面为适配站点，是否自动进入阅读模式 这一选项为关，并且白名单为空，但访问了几个站点（包括京东天猫B站github等）全都会自动进入阅读模式

**Comment by Kenshin** [comment]
谢谢反馈，明天确认下，会公布解决方案。

🙏🏻

**Comment by Colin-XKL** [comment]
测试了下，添加到黑白名单功能无法正常工作，把一个站点添加到白名单，但是进后台一看，白名单列表并没有新的项目添加进来

**Comment by Kenshin** [comment]
@Colin-XKL 

请放心，会有解决方案的。因为我一直在使用，并没有出现问题，所以也可以绕过去。

**Comment by Kenshin** [comment]
@Dradows @Colin-XKL 

嗨，这个问题可以解决，这是解决方案 https://github.com/Kenshin/simpread/issues/2159

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，**此问题彻底被解决**，未防止再次发生这类情况。

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
