### ISSUE TITLE
当升级到简悦 2.2.0 少数用户后会自动进入阅读模式（附解决方案）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2159]
## 问题现象

升级到 2.2.0 后，如果你发现 **如果当前页面为适配站点，是否自动进入阅读模式？** 为关闭状态时，且 **白名单** 无任何内容的话，会在任意页面进入阅读模式

![image](https://user-images.githubusercontent.com/81074/118735049-359a0180-b872-11eb-8115-12d7081e4848.png)

![image](https://user-images.githubusercontent.com/81074/118735120-5b270b00-b872-11eb-928e-5c78a745e423.png)

## 解决方案

> 在白名单中加入任何内容，如 `google.com` 即可解决。

![image](https://user-images.githubusercontent.com/81074/118735164-70039e80-b872-11eb-8e65-211259ec2f99.png)

## 影响范围

1. **默认配置文件时，不会影响**

2. 开启 **自动进入阅读模式，不会影响**

3. 未开启  **自动进入阅读模式，但人为清空白名单后会有此问题** （ 使用上面提供的解决方案即可解决）

**Comment by cdchs99** [comment]
你好，在升级到2.2，我出现了该问题，这个办法并没有解决我的问题。我的白名单一直都不是空白的，可是还是会自动进入阅读模式，比如bilibili.com和github.com，这两个页面在simread升级前，我都不会自动进入阅读模式。

**Comment by Kenshin** [comment]
嗨，此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决，以下是相关信息

PS：新版正在审核中，审核通过后，我会再次通知这里。

## 简悦 2.2.0.520 正在审核中

> 因 2.2.0 发布后产生了一些特殊情况下的通用性问题，所以我发布了 **520 补丁版**，用来解决这些通用性问题，520 版本正式发布后，我会在这里通知大家。

## 通用性问题

> 关于通用性错误的细节也可以看 **选项页 → 右下角 → 通知中心** 或 [这里](http://ksria.com/simpread/changelog.html#2.2.0)

- [如果你因为升级到简悦 2.2.0，但无法使用同步助手导出 PDF 的话，请看这里](https://github.com/Kenshin/simpread/issues/2154)
- [使用同步助手 1.0.1 导致 PDF 导出效果不佳的解决方案](https://github.com/Kenshin/simpread/issues/2191)
- [在使用导出服务时发生只导出了标题和描述（附解决方案）](https://github.com/Kenshin/simpread/discussions/2225)
- [任意页面自动进入阅读模式（附解决方案）](https://github.com/Kenshin/simpread/issues/2159)
- [有可能会引起无法使用维基百科的问题（附解决方案）](https://github.com/Kenshin/simpread/issues/2163)
- [如果发现无法使用导出功能（附解决方案）](https://github.com/Kenshin/simpread/issues/2178)
- [未启用标注模式无法复制的问题（附解决方案）](https://github.com/Kenshin/simpread/issues/2199)


## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)


## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## API 失败的情况

> 如果你在使用 API 导致失败的话，请做以下修改：

1. 请不要使用 Dropbox 作为同步盘
2. 请使用严格的目录结构 \`<支持的网盘>/SimpRead/simpread_config.json\` 👉  [如何开通](https://simpread.pro/api/#/README?id=如何开通)
3. 如果无法访问 [https://simpread.pro/developer](https://simpread.pro/developer) 请确保网络畅通即可。

**关于第一条的补充**

> 如果你仅使用 Telegram Bot 的话，可以设置 Dropbox 为同步盘。

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，**此问题彻底被解决**，未防止再次发生这类情况。

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
