### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by xbichon** [Kenshin/simpread#2160]
发生问题的地址: <https://gitbook.cn/gitchat/column/5b1e3647294fb04d7c22b783/topic/5b1fa42a52823b7111033332>

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。
