### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by ZuulAndRibbon** [Kenshin/simpread#2166]
发生问题的地址: <https://mp.weixin.qq.com/s?__biz=MzIyNDM1NzkwNQ==

**Comment by Kenshin** [comment]
我已经看到了你的建议。

抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by binsee** [comment]
本issue发的url无效，建议补发一下完整文章url。
