### ISSUE TITLE
WIKI 页面内容消失

### ISSUE THREAD

**Issue by Cologler** [Kenshin/simpread#2170]
比如 https://zh.wikipedia.org/zh-cn/%E6%97%85%E8%A1%8C%E9%9D%92%E8%9B%99

在进入页面后，未开启阅读模式，内容依旧会消失：

![image](https://user-images.githubusercontent.com/10906962/118763864-24b9b200-b8ab-11eb-98b3-8640975beb31.png)

从浏览器控制台中查看，会发现 dom elements 都不存在。

禁用扩展后恢复正常。

启用扩展前的 elements 树：

![image](https://user-images.githubusercontent.com/10906962/118764306-dd7ff100-b8ab-11eb-975e-312235ceea25.png)

启用扩展后的 elements 树：

![image](https://user-images.githubusercontent.com/10906962/118764374-f9839280-b8ab-11eb-85c0-a6fdf983c36e.png)

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/issues/2163#issuecomment-843687177

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by OrdinaryYZH** [comment]
我也是一个插件一个插件关掉才发现是简悦的问题，忧伤，不过很快搜索issue就找到解决方案了。良心插件，希望能够保持稳定，这次瑕不掩瑜

**Comment by Kenshin** [comment]
@OrdinaryYZH 

嗨，谢谢理解和包容，虽然也没「多大」事情，但确实影响到了一部分使用者。
我会在下周发布一个升级版来解决这个问题。（是静默更新，不会像 2.2.0 这样大版本更新。）

**Comment by Cologler** [comment]
@Kenshin 不是，目前的简阅实现，为什么在未开启阅读模式情况下会修改原页面？

**Comment by Kenshin** [comment]
@Cologler 

为了能更快速进入阅读模式，所以在适配的页面都会做 [预加载](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e9%a2%84%e5%8a%a0%e8%bd%bd%e6%9c%ba%e5%88%b6) 功能，而预加载会对原页面进行一些优化，但因为一个 Bug 导致出现了此问题。

你可以在我提到的链接里面找到解决方案。

**Comment by Cologler** [comment]
> @Cologler 
> 
> 为了能更快速进入阅读模式，所以在适配的页面都会做 [预加载](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%e9%a2%84%e5%8a%a0%e8%bd%bd%e6%9c%ba%e5%88%b6) 功能，而预加载会对原页面进行一些优化，但因为一个 Bug 导致出现了此问题。
> 
> 你可以在我提到的链接里面找到解决方案。

怎样关闭预加载？不光容易引起非预期 bug（预期非活动扩展不会修改原页面），而且会导致打开页面性能下降。今年以来我打开简阅的次数不超过十次，不该为这少于百分之一的可能性去增加每次打开页面的时间。

**Comment by Kenshin** [comment]
@Cologler 
上文给的链接里面有。至于你的诉求，我建议配合白名单机制。如果只是这样使用简悦的话，不如用轻阅版。

**Comment by Kenshin** [comment]
@Cologler 

另外，所谓性能问题，并不存在，你可以试试对你是否有影响？我一般都用 17年的设备做测试性能用。
