### ISSUE TITLE
关于代码高亮的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2172]
1. 代码高亮插件装不上了， edge 浏览器 ， 搞不懂这么基础的功能为啥非得整成插件呢
2. 标注块， 在代码块里标注的（比如标注代码块里的某个变量）， 标注取消不掉
3. 标注块双击功能显示详情的功能不能用了，不清楚是不是需要打开什么开关。
先说上面这几点， 麻烦尽快修复下，非常影响使用

_Originally posted by @liguang-hxd in https://github.com/Kenshin/simpread/issues/2158#issuecomment-843850234_

**Comment by Kenshin** [comment]
@liguang-hxd 

嗨，谢谢反馈。估计是新用户吧，你提到的这几点都跟新版本无关，简单的解释下：

1. 代码高亮并不是每个人都需要的
2. 简悦支持的整个代码块的标注，而非其中某个内容，否则会有问题。

代码高亮是有些问题，我会集中到 #500 里面。

***

> 标注块双击功能显示详情的功能不能用了

没理解是什么意思？

**Comment by Kenshin** [comment]
，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by liguang-hxd** [comment]
@Kenshin 以前可以双击标注块，然后会弹出标注的详情页面，可以加书签，备注等

**Comment by Kenshin** [comment]
> @Kenshin 以前可以双击标注块，然后会弹出标注的详情页面，可以加书签，备注等

你可能记错了... 简悦一直没有双击操作，你可以试试 单击 标注块，我刚刚确认了下，是没问题的。

**Comment by liguang-hxd** [comment]
还有一个建议，我个人觉得对整个代码块整体进行标注的功能没啥用，一般看代码粒度都比较细吧，一般是对某个变量或者某段注释高亮一下， 建议增加个开关让用户自己选择是否需要标注整个代码段整体， 或者直接去掉这个功能。
我这边比较高频词的操作是对某个代码块里的某个单词或者某段注释的描述添加标注。

**Comment by liguang-hxd** [comment]
> > @Kenshin 以前可以双击标注块，然后会弹出标注的详情页面，可以加书签，备注等
> 
> 你可能记错了... 简悦一直没有双击操作，你可以试试 单击 标注块，我刚刚确认了下，是没问题的。

![image](https://user-images.githubusercontent.com/81204050/118779065-4754c680-b8bd-11eb-88b3-b1bff3dbdf60.png)
试了下单击只能出现这个条

以前双击是显示这个
![image](https://user-images.githubusercontent.com/81204050/118779370-8aaf3500-b8bd-11eb-8e47-fd66073372fb.png)
单击是换标注颜色

**Comment by Kenshin** [comment]
明白你的 意思了...

***

更新日志有说明，下图

![image](https://user-images.githubusercontent.com/81074/118779826-04dfb980-b8be-11eb-8d4e-82a5af79ac6f.png)

PS：双击操作是在已标注的内容上才能实现。

***

你可以选择原来的方案：

![image](https://user-images.githubusercontent.com/81074/118779980-2ccf1d00-b8be-11eb-8b65-720b93eb7b0a.png)


***

同样，上面的内容都在更新日志里面有说明 http://ksria.com/simpread/welcome/version_2.2.0.html#custom
