### ISSUE TITLE
简悦 2.2.0 如果发现无法使用导出功能（附解决方案）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2178]
## 问题现象

> 无法使用导出服务，点击导出服务无任何反应。

## 问题原因

> 这种情况一般是 **关闭了标注功能** 造成的，如下图

![image](https://user-images.githubusercontent.com/81074/118800992-1aaba980-b8d3-11eb-9a1d-5c1bb3b1b414.png)

## 解决方案（阅读模式）

> 开启此功能即可。

![image](https://user-images.githubusercontent.com/81074/118801044-29925c00-b8d3-11eb-968e-49c6b430b8ad.png)

## 解决方案（聚焦模式）

> 同样也需要先开启上面这个选项，但是重点：**不能先进入聚焦模式，而是要先进入阅读模式**，然后退出阅读模式后，再进入聚焦模式，就可以导出功能了。

## 后续

我会在 **下周出一个关于这些 Bug 的补丁版本**。

**Comment by Birdling** [comment]
![image](https://user-images.githubusercontent.com/62651551/118817396-c100aa80-b8e5-11eb-87b6-ce3dd17a1268.png)
聚焦模式导出还是不行，没反应，另外阅读模式导出为pdf不是内置的导出pdf，请问是我哪里弄错了吗？

**Comment by Kenshin** [comment]
@Birdling 

找到我的邮箱，把配置文件发给我。

> 阅读模式导出为pdf不是内置的导出pdf

配置错误造成的。

**Comment by Kenshin** [comment]
@Birdling 

导出时用同步助手了吗？

**Comment by Birdling** [comment]
> @Birdling
> 
> 导出时用同步助手了吗？

第二个问题我知道了，同步助手我还没有开通会员，现在在尝试功能。现在就是第一个问题，聚焦模式导出为pdf等没反应。

**Comment by Kenshin** [comment]
@Birdling 

基础账号吗？我明天试试。

你试试阅读模式能否导出 PDF？另外 ，基础账号使用了浏览器自带打印方式。

这个问题与当前 Issues 无关，建议新建 Issues

**Comment by Birdling** [comment]
@Kenshin 
已新建 [Issue](https://github.com/Kenshin/simpread/issues/2180)

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，**此问题彻底被解决**，未防止再次发生这类情况。

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Jason-Study** [comment]
@Kenshin  您好！最近我电脑在CSDN网站上我不能导出为html、markdown了，但可以导出离线html、离线markdown，其他网站正常，另外一台电脑也能正常导出CSDN（都是win10、Chrome浏览器、简悦2.2.0.520）。请问您知道怎么解决吗？加载之前的配置文件，稍后读数据会丢失，不太想这样
