### ISSUE TITLE
站点管理器自定义适配源只有1条时列表不显示

### ISSUE THREAD

**Issue by yobyzal** [Kenshin/simpread#218]
Chrome版本：65.0.3322.3（正式版本）dev （64 位）
simpread版本：1.1.0

问题描述：<站点管理器> - <自定义适配源>只有1条时列表不显示，多条正常。

![_2018-01-21_094732](https://user-images.githubusercontent.com/1258104/35189925-7d6d4fde-fe90-11e7-92b6-59ab52eecc02.png)

**Comment by Kenshin** [comment]
感谢反馈，是有这个 Bug ，下个版本修复。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
