### ISSUE TITLE
稍后读已是阅读模式无法导出pdf，仍显示需要阅读模式

### ISSUE THREAD

**Issue by Birdling** [Kenshin/simpread#2181]
![image](https://user-images.githubusercontent.com/62651551/118827975-708e4a80-b8ef-11eb-96fe-42526eea6ac2.png)

**Comment by Kenshin** [comment]
嗨，这是正常的，基础账号使用的是浏览器自带的 PDF 方式

使用同步助手的方式才可以在此模式下使用。
