### ISSUE TITLE
2.2.0配置变更后一直频繁提示刷新页面，即使刷新也无效，只能重启Chrome

### ISSUE THREAD

**Issue by samwei12** [Kenshin/simpread#2185]
更新2.2.0之后出现，同时导致一些插件无法使用
目前使用了  阅读模式浮动面板定制器

步骤：
1. 删除一个导出，保存之后提示刷新，
2. 刷新之后无法使用，只能重启浏览器，
3. 重启浏览器之后保存的内容完全消失，完全不可用

![2021-05-20 08-47-29 2021-05-20 08_48_36](https://user-images.githubusercontent.com/12758352/118902597-87ad5680-b948-11eb-9757-5e91fca9f515.gif)

环境：
Mac 11.3 (20E232)
Chrome： 版本 90.0.4430.212（正式版本） (x86_64)

**Comment by Kenshin** [comment]
嗨，估计是你双开了这个页面导致的，跟 2.2.0 无关。

同样，插件也不会无故消失的，如果消失的话，重新导入即可。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
关于这个问题，请在跟踪下。另外，版本升级时请问是否使用同步助手？

**Comment by samwei12** [comment]
> 关于这个问题，请在跟踪下。另外，版本升级时请问是否使用同步助手？

没有，我关掉了

**Comment by samwei12** [comment]
> 嗨，估计是你双开了这个页面导致的，跟 2.2.0 无关。
> 
> 同样，插件也不会无故消失的，如果消失的话，重新导入即可。

插件本身没有消失，但是插件里面配置的那些导出选项，全没了

**Comment by samwei12** [comment]
> 嗨，估计是你双开了这个页面导致的，跟 2.2.0 无关。
> 
> 同样，插件也不会无故消失的，如果消失的话，重新导入即可。

我确实没注意是否打开了两个一样网址的该页面，回去再试一下

**Comment by samwei12** [comment]
![image](https://user-images.githubusercontent.com/12758352/118940546-6b7adb00-b983-11eb-8869-40e192590eae.png)

https://simpread.ksria.cn/plugins/details/7gcXYY4HAc

是这个插件，里面的导出选项，刷新之后没了，不确定是不是跟之前你说的那个打开两个页面有关系

刚才在公司电脑安装时候遇到了另外两个问题：

1. 同步配置文件之后，插件没有同步，需要重新安装一遍，我是早上出门家里同步的配置，家里电脑安装两个插件，这里配置文件是否不记录插件信息？
2. 这个插件公司电脑安装不上。点击安装之后无事发生 Chrome 版本 90.0.4430.212（正式版本） (x86_64)

**Comment by Kenshin** [comment]
> 同步配置文件之后，插件没有同步，需要重新安装一遍

插件是不同步的，因为涉及到 size 问题，所以只同步插件的 ID，你可以在恢复它们（另外，插件的配置项是可以同步的，无需恢复

![image](https://user-images.githubusercontent.com/81074/118942295-2a83c600-b985-11eb-80ce-035d30d7a25b.png)

> 这个插件公司电脑安装不上

这个插件其实就是个「钩子」，Chrome 会检测到特殊 URL，然后会做处理（获取插件 ID）→ 从服务器下载插件（安装）。
所以，不知道你公司的环境是否有什么特别的。

还有，导致失败也可能是其它扩展造成的问题，不知道失败的浏览器是否装了什么扩展？能否仅使用简悦。

**Comment by samwei12** [comment]
可以了，从配置文件导入能够安装，多谢

**Comment by Kenshin** [comment]
> 可以了，从配置文件导入能够安装，多谢

没事，新版发布难免有问题，因为简悦的配置项太多了，使用场景太多了，难易覆盖全部。这个版本我内部已经测试了  10+ 个配置文件，结果还是有漏网之鱼...

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，搞定的话，如果网络允许的话，请去 Webstore 帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 吧  😂

**Comment by samwei12** [comment]
已经五星好评支持

**Comment by Kenshin** [comment]
嗨，谢支持。

**Comment by Kenshin** [comment]
> 2.2.0.520 已经正式发布，修复了一些 2.2.0 通用性问题，这些问题细节请看 👉  https://github.com/Kenshin/simpread/issues/2158 或 http://ksria.com/simpread/changelog.html


## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)


## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
