### ISSUE TITLE
开启高级会员后导出PDF调用失败

### ISSUE THREAD

**Issue by hqsiswiliam** [Kenshin/simpread#2187]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- Windows10

- Chrome Version 90.0.4430.212 (Official Build) (64-bit)

- 简悦版本 **2.0.0**

- 安装了同步助手1.0.1

**截图**
![image](https://user-images.githubusercontent.com/5647879/118913535-3b6c1180-b95c-11eb-833c-bfb34578b88e.png)

**Comment by Kenshin** [comment]
嗨，这个提示应该不是 导出 PDF 时提示的吧。另外，也请给出 URL 我方便判断。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by UndertheSkyStone** [comment]
这个issue还是没有修复啊

**Comment by Kenshin** [comment]
@UndertheSkyStone 

修复了，否则我会什么会关闭这个 Issues 如果你仍存在类似的问题，请详细描述并告知 URL

**Comment by neowang0122** [comment]
url: https://mp.weixin.qq.com/s/8CPSNw4eRCmKt52-OCtdLQ，尝试导出为html时出现该问题。

**Comment by Kenshin** [comment]
@neowang0122 

我可以正常导出 PDF，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，并开启下图的选项

![image](https://user-images.githubusercontent.com/81074/163519772-61b23ba4-0731-4c2c-ac90-9a5900ce823d.png)

**Comment by neowang0122** [comment]
好的，试了下确实可以了，感谢！

**Comment by Kenshin** [comment]
搞定就好。
