### ISSUE TITLE
带有视频的页面无法导出 PDF

### ISSUE THREAD

**Issue by solidarity666** [Kenshin/simpread#2188]
Win 10 64位系统，谷歌浏览器 90.0.4430.212(64位)，简悦2.2.0，导出PDF的质量非常差，下面是导出的网址和导出的PDF文件
https://zhuanlan.zhihu.com/p/56197053
[抽象代数学习笔记（一）.pdf](https://github.com/Kenshin/simpread/files/6512842/default.pdf)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

确实这样，**这应该是第一个 1.0.1 版导致 PDF 导出问题的情况**。**2.2.0 的 PDF 肯定要比之前好很多**，这几天太忙了，没有时间详细研究

比如这篇文章 https://blog.csdn.net/VictoriaW/article/details/70053790 导出 PDF 后的效果就很好

[计算机视觉之统计形状模型——Active Shape Model_CodeTutor-CSDN 博客_统计形状模型.pdf](https://github.com/Kenshin/simpread/files/6513491/Active.Shape.Model_CodeTutor-CSDN._.pdf)

另外，不知道是否开启了 **图片代理** 功能，细节请看 https://github.com/Kenshin/simpread/issues/2191

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by solidarity666** [comment]
Hi, 我开启了图片代理，在CSDN上可以，但是知乎上的还是不行，可能是不同网站格式不同的问题；我关了Dark Reader这个插件，字体就正常了，希望对你有帮助。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kenshin ***@***.***>
发送时间: 2021年5月20日 14:50
收件人: ***@***.***>
抄送: Dong ***@***.***>; ***@***.***>
主题: Re: [Kenshin/simpread] 导出PDF问题 (#2188)


嗨，谢谢反馈。

确实这样，这应该是第一个 1.0.1 版导致 PDF 导出问题的情况。2.2.0 的 PDF 肯定要比之前好很多，这几天太忙了，没有时间详细研究

比如这篇文章 https://blog.csdn.net/VictoriaW/article/details/70053790 导出 PDF 后的效果就很好

计算机视觉之统计形状模型――Active Shape Model_CodeTutor-CSDN 博客_统计形状模型.pdf<https://github.com/Kenshin/simpread/files/6513491/Active.Shape.Model_CodeTutor-CSDN._.pdf>

另外，不知道是否开启了 图片代理 功能，细节请看 #2191<https://github.com/Kenshin/simpread/issues/2191>

―

**Comment by shistark** [comment]
知乎上有视频的网页还是无法导出pdf：https://www.zhihu.com/question/267050695/answer/318144092

**Comment by Kenshin** [comment]
@shistark 

是的，这是已知问题，并不是 1.0.1 的问题。带有视频的页面无法使用 PDF

等忙过了这阵子，我再着手优化。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，已重新开启此 Issues

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
> 以下是 2.2.0 的相关介绍，请让我重新介绍一次。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄

**Comment by shistark** [comment]
开发者您好，之前就是因为苦恼于pdf问题而好久没用了简悦了，今天收到邮件还是挺开心的，立刻重新安装了，不过问题完全没解决，不知道是不是我的问题。
如：https://zhuanlan.zhihu.com/p/503737917
https://www.zhihu.com/question/22298352
导出结果是这样的：




我已经按照https://github.com/Kenshin/simpread/discussions/2762来做了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 带有视频的页面无法导出 PDF (#2188)





  
嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。
  

 
下载地址
 
https://simpread.ksria.cn/plugins/details/Lly3mkuSPz
 
演示
 
百度网盘
 
使用前提
  
 
这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 看这里。
 
 
 
使用 wkhtmltopdf 来增强导出 PDF 的定制化功能，因此也需要安装 wkhtmltopdf，安装很简单但需要留意 注意事项。
 
  
名词解释
  
 
1.0.1 版 PDF 方案称为：同步助手基础打印方案
 
 
 
1.0.2 版 PDF 方案称为：同步助手高级打印方案
 
  
优势
  
 
可根据当前阅读模式的 主题、字体样式、字体大小 生成 PDF
 
 
 
支持 自定义字体 · 自定义样式
 
 
 
支持 更细致的打印，如页边距、打印尺寸
 
 
 
自带目录
 
 
 
完美解决因图片防盗链无法成功打印的问题
 
  
劣势
  
无法在稍后读使用
 
需要安装 wkhtmltopdf
 
标注支持度有限，详细说明 请看这里
  
注意
  
 
Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
 
 
 
如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 运行目录。
 
  
附录
 
以下是自定义导出 PDF 的一些截图
 

 

 

 
 
我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄

**Comment by Kenshin** [comment]
@shistark 

当然没有问题了，我是对比这些 issues 提到的问题解决的。

另外，使用高级打印方式时会有下图转换的图片的效果

![image](https://user-images.githubusercontent.com/81074/173213892-57c45bdc-023e-48e1-9d0a-59dae50b54eb.png)

以下是导出的 PDF

[【抽象代数】维数公式.pdf](https://github.com/Kenshin/simpread/files/8885172/default.pdf)

[如何通俗易懂地解释卷积？.pdf](https://github.com/Kenshin/simpread/files/8885177/default.pdf)

**Comment by shistark** [comment]
开发者您好。您这个导出结果是用win10自带的打印效果吧（快捷键pp），我使用简悦导出功能，效果不好。因为我觉得导出功能排版比自带的好多了。这个问题解决不了嘛？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月12日(星期天) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 带有视频的页面无法导出 PDF (#2188)





 
@shistark
 
当然没有问题了，我是对比这些 issues 提到的问题解决的。
 
另外，使用高级打印方式时会有下图转换的图片的效果
 

 
以下是导出的 PDF
 
【抽象代数】维数公式.pdf
 
如何通俗易懂地解释卷积？.pdf

**Comment by Kenshin** [comment]
@shistark 

哈哈，当然不是用浏览器导出了... 是同步助手新的导出方案。

**Comment by Kenshin** [comment]
另外，如果没有解决这个问题的话，我不会通过 Issues 联系你。

**Comment by shistark** [comment]
开发者您好，我还是没搞清楚我的问题出在哪里？如何用简悦导出完整pdf？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 带有视频的页面无法导出 PDF (#2188)





 
另外，如果没有解决这个问题的话，我不会通过 Issues 联系你。

**Comment by Kenshin** [comment]
先随便找个页面，看看能否导出成功 https://sspai.com/post/71200

还有，请仔细看 https://github.com/Kenshin/simpread/issues/2188#issuecomment-1151894533 的内容，内含教程。

有任何问题请直接在 https://github.com/Kenshin/simpread/issues/2188 提问，不要通过 Email 回复我。

**Comment by shistark** [comment]
开发者您好，打扰了！我在github上回复您，已经两天没有消息了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 带有视频的页面无法导出 PDF (#2188)





 
先随便找个页面，看看能否导出成功 https://sspai.com/post/71200
 
还有，请仔细看 #2188 (comment) 的内容，内含教程。
 
有任何问题请直接在 #2188 提问，不要通过 Email 回复我。

**Comment by Kenshin** [comment]
> 开发者您好，打扰了！我在github上回复您，已经两天没有消息了。

近期有点忙，漏掉了这个 Issues

> https://github.com/Kenshin/simpread/issues/2188#issuecomment-1156212703

抱歉，你给的信息太少了，我没法判断。包括你之前的一些回复也同样有类似的情况。

最好能详细说明关于这个功能的相关配置是什么，在什么 URL 上发生了错误，还是全部 URL 都有问题等等，越详细越好。

最后提示下：这个功能不是随便开个选项就能完成的，需要用户自己配置，包括：

1. [同步助手](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)

2. [增强导出](https://kb.simpread.pro/#/page/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)

3. [同步助手高级打印发方案](https://github.com/Kenshin/simpread/discussions/3887)

**Comment by shistark** [comment]
所有网站都不行：
https://blog.csdn.net/baicaiBC3/article/details/122365160
https://zhuanlan.zhihu.com/p/41609577
https://www.zhihu.com/question/22298352

相关配置：














目录我也填了，也保存了，每次打开还是为空。
另一个电脑下载了坚果云，步骤和


同步助手中的一样，其余配置一样，还是报错。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 带有视频的页面无法导出 PDF (#2188)





  
开发者您好，打扰了！我在github上回复您，已经两天没有消息了。
  
近期有点忙，漏掉了这个 Issues
  
#2188 (comment)
  
抱歉，你给的信息太少了，我没法判断。包括你之前的一些回复也同样有类似的情况。
 
最好能详细说明关于这个功能的相关配置是什么，在什么 URL 上发生了错误，还是全部 URL 都有问题等等，越详细越好。
 
最后提示下：这个功能不是随便开个选项就能完成的，需要用户自己配置，包括：
  
 
同步助手
 
 
 
增强导出
 
 
 
同步助手高级打印发方案
