### ISSUE TITLE
希望能优化阅读模式的背景颜色，或者提供自定义阅读模式背景颜色功能。

### ISSUE THREAD

**Issue by lronking** [Kenshin/simpread#2189]
**请说明发生问题的环境**

- 操作系统  MacOS

- 浏览器版本 Chrome 版本 90.0.4430.212（正式版本） (x86_64)

- 简悦版本 2.2.0

**请描述你的问题**

阅读模式的颜色希望增加 #FFFDF1 这个颜色，或者提供类似于Safari阅读模式的黄色（#F8F1E3），现有的颜色在阅读的时候感觉太亮。

**截图**
![iShot2021-05-20 13 32 05](https://user-images.githubusercontent.com/23070757/118924661-fb168e80-b96f-11eb-83d3-dc11d6bcd8ff.png)

**Comment by Kenshin** [comment]
嗨，你可以试试  [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 以及 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 这个插件。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，不知道是否解决了？
