### ISSUE TITLE
简悦 2.2.0 使用同步助手 1.0.1 导致 PDF 导出效果不佳的解决方案

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2191]
## 问题现象

简悦 2.2.0 使用 同步助手 1.0.1 导致 PDF 导出效果不佳，尤其是 **无法显示图片** 的话，如下图：

![image](https://user-images.githubusercontent.com/81074/118930505-68c6b880-b978-11eb-88cb-4ba980d2167d.png)

## 解决方案

> 开启 **图片代理** 即可，位置：选项页 → 服务 → 定制导出

![image](https://user-images.githubusercontent.com/81074/118932199-5b123280-b97a-11eb-9de2-0f604701bf78.png)

## 一个例子

> 比如这篇文章 https://blog.csdn.net/VictoriaW/article/details/70053790 导出 PDF 后的效果就很好

[计算机视觉之统计形状模型——Active Shape Model_CodeTutor-CSDN 博客_统计形状模型.pdf](https://github.com/Kenshin/simpread/files/6513491/Active.Shape.Model_CodeTutor-CSDN._.pdf)

## 更多测试例子

https://github.com/Kenshin/simpread/issues/2023 里面提到的问题都可以通过 **简悦 2.2.0 使用同步助手 1.0.1** 解决。

**Comment by shistark** [comment]
我打开了代理：
![image](https://user-images.githubusercontent.com/42604976/119094073-1ef6d480-ba43-11eb-8c5c-4f7fff32e5c0.png)
未能正确导出该网页
![image](https://user-images.githubusercontent.com/42604976/119094326-77c66d00-ba43-11eb-8aa5-ecbf8506f17d.png)
zhe'pi这篇文章也不能：https://zhuanlan.zhihu.com/p/372031461
![image](https://user-images.githubusercontent.com/42604976/119094409-93317800-ba43-11eb-81a0-10ff7f66b934.png)

**Comment by shistark** [comment]
我又退回2.1了，2.1是可以正确下载的。

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

- 简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

- 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 https://github.com/Kenshin/simpread/issues/2158

**Comment by Kenshin** [comment]
> 我又退回2.1了，2.1是可以正确下载的。

收到，后续我会关注下这个问题，看看是什么情况造成的。

**Comment by Kenshin** [comment]
@shistark 

嗨，我今天 抽时间调查了下这个问题，应该跟 2.1  无关。你确定在 2.1 + 1.0.0 下可以导出？

这个图片其实是一个动态图片，地址 `https://www.zhihu.com/equation?tex=G%3D%28X%2CA%29` 在使用同步助手导出时，可能是知乎做了防盗链处理，所以无法显示。

PS：知乎上的正常图片是没问题的。

**Comment by shistark** [comment]
是的：
![image](https://user-images.githubusercontent.com/42604976/119258912-5198fc80-bbfe-11eb-8004-e2cc459c2745.png)

**Comment by Kenshin** [comment]
@shistark 

这就有意思了... 我明天试试 2.1  + 1.0.0  的方式。

**Comment by shistark** [comment]
麻烦了，很喜欢这个软件，希望越来越好！！！

**Comment by shistark** [comment]
导出的pdf有时候字体显示不完整。
![image](https://user-images.githubusercontent.com/42604976/119436285-756b5800-bd4e-11eb-92f8-3e1273fca206.png)

**Comment by Kenshin** [comment]
@shistark 

看来你是重度 PDF 依赖，发给 URL 我看看，应该是个例。

**Comment by maxvll** [comment]
@Kenshin 导出PDF的时候大部分图片正常显示，有的图片显示不正常(随机的) 导出EPUB时没有图片，导出md和html文件正常

2.2.0 + 1.0.1

![image](https://user-images.githubusercontent.com/49853153/119439063-26c0bc80-bd54-11eb-9ef7-6dfde8a99d33.png)

https://www.bilibili.com/read/cv3220383?from=articleDetail

**Comment by Kenshin** [comment]
@maxvll 

嗨，随机图片失败是正常的（接下来的版本会彻底解决），因为 1.0.1 增加了防盗链机制，所以会有个图片加载时间，所以偶发此问题。

当遇到此问题时，重新导出即可解决。

**Comment by shistark** [comment]
> @shistark
> 
> 看来你是重度 PDF 依赖，发给 URL 我看看，应该是个例。

https://www.zhihu.com/question/31584701/answer/75484502?ivk_sa=1024320u
https://www.zhihu.com/question/24648753

**Comment by Kenshin** [comment]
@shistark 

嗨，关于知乎数学公式图片问题，可以看这个解决方案 https://github.com/Kenshin/simpread/issues/2860 不知道是否可以解决你的问题。

**Comment by Kenshin** [comment]
另外，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869
