### ISSUE TITLE
无法导入到Onenote 和 flomo，可导入Notion但排版不合适

### ISSUE THREAD

**Issue by HJCFLY** [Kenshin/simpread#2194]
批注后如下：
![截图_20212120042157](https://user-images.githubusercontent.com/38662362/118944844-83545e00-b987-11eb-9a0a-9988b991a275.png)

导入Onenote时如下：
![截图_20214520084502](https://user-images.githubusercontent.com/38662362/118944551-3f615900-b987-11eb-8434-d3f405ee47a7.png)

导入flomo时：
![截图_20212120042134](https://user-images.githubusercontent.com/38662362/118944797-77689c00-b987-11eb-837b-0e211c88f01c.png)

Notion里显示如下：
![截图_20212320042324](https://user-images.githubusercontent.com/38662362/118945099-b696ed00-b987-11eb-9bc3-322f6e75b2d6.png)

**Comment by Kenshin** [comment]
嗨，我没有遇到你的问题，请确认是否可以稳定复现。

![image](https://user-images.githubusercontent.com/81074/118948156-99afe900-b98a-11eb-9df3-eb2a024754f7.png)

![image](https://user-images.githubusercontent.com/81074/118948320-c06e1f80-b98a-11eb-8f1c-c5e1eac5cc49.png)


> Notion里显示的问题

你导出 MD 看看有没有问题，没问题的话，就是 Notion 的问题。

***

另外，2.2.0 导出功能有些新更新，或许也可能是这个问题导致的。因为发布的很突然，所以不少文档没来得及写，你稍等几天。我会再通知你。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by HJCFLY** [comment]
幸苦啦！
我试啦 
新页面还是无法导入到Onenote 和 flomo，导入Notion则完全没有排版。原链接是微信文章，比如：https://mp.weixin.qq.com/s?__biz=MjM5MDQ4NjUwMg==&mid=2649198191&idx=1&sn=95c506dde4a079d2840a91b12ca358a8&chksm=be5734e68920bdf04af5ad5f31d8c40acea17e723b1b0eeaa2d3d47d009a0adc5abca44bc953&token=1351484622&lang=zh_CN&scene=21#wechat_redirect
导出markdown可以，打开后格式有一点点错乱，但是属于可以接受的范围。

**Comment by Kenshin** [comment]
嗨，能方便把配置文件通过邮件给我吗？
这样方便调查。

**Comment by Kenshin** [comment]
我我邮件地址在 Github 上就能找到。

**Comment by HJCFLY** [comment]
好的 请稍等

**Comment by HJCFLY** [comment]
已发送，请查收。

**Comment by Kenshin** [comment]
好，我明天确认下。

主要是第一个图无法导出的问题，对吧。

**Comment by Kenshin** [comment]
嗨，你看看是不是这个问题造成的 https://github.com/Kenshin/simpread/discussions/2225

**Comment by HJCFLY** [comment]
这下合适了。我还有一个问题，在标注模式下还是显示的啥都没有，如下图。标注模式下，要想显示内容是不是得在原始界面打开阅读模式 后标注了内容才行？
***@***.***D74F4B.A02AF3F0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kenshin ***@***.***>
发送时间: 2021年5月22日 19:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Kenshin/simpread] 无法导入到Onenote 和 flomo，可导入Notion但排版不合适 (#2194)


嗨，你看看是不是这个问题造成的 #2225<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenshin%2Fsimpread%2Fdiscussions%2F2225&data=04%7C01%7C%7C3e0a83fdb763441e923008d91d169a7a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637572805181723363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3C%2Fk7rUyfrD2zRPmjRE1D5zmQsYbcsTbbrMlVEBFreE%3D&reserved=0>

―

**Comment by Kenshin** [comment]
我无法看到你的图片。
标注模式的使用前提是：需要有标注才行。

**Comment by Kenshin** [comment]
还有，不要通过邮件的形式回复我，在 Github 里面回复我，否则什么都看不到… 😂

**Comment by HJCFLY** [comment]
知道了，谢谢老哥，我还以为必须邮件回复呢，尴尬 哈哈哈
你的意思是：如果想要在稍后阅读的’标注模式‘里显示内容（如下图），就必须提前在原始页面进入’阅读模式‘进行标注。
![image](https://user-images.githubusercontent.com/38662362/119228118-0fab8000-bb44-11eb-80fc-8654423c452b.png)

**Comment by HJCFLY** [comment]
老哥还有个问题：“无法导入到Onenote 和 flomo，可导入Notion但排版不合适”，这个问题仍然存在，配置文件我昨天通过邮件发给你了。多谢！

**Comment by Kenshin** [comment]
应该没问题的。

你先导出配置文件，然后重置，再之后不做任何设置，并且用一些正常的地址访问，比如 少数派的，导出 md 到本地。

Notion 对 md 的支持度有限。

**Comment by HJCFLY** [comment]
我重置了一下，使用少数派的页面：https://sspai.com/post/66717
然后md正常，Onenote正常，但是flomo还是无法导入:
![image](https://user-images.githubusercontent.com/38662362/119230499-0bd12b00-bb4f-11eb-93b6-a04a4fc2aee4.png)
授权也给了：
![image](https://user-images.githubusercontent.com/38662362/119230526-23101880-bb4f-11eb-811c-9a6bf847371f.png)

**Comment by Kenshin** [comment]
嗨，flomo 的问题应该也是你设置造成的（猜测），看下图重点部分

![image](https://user-images.githubusercontent.com/81074/119246301-132a2000-bbb3-11eb-9fef-1fad48ebb6e0.png)

**Comment by HJCFLY** [comment]
哦哦 明白了 谢谢

**Comment by Kenshin** [comment]
> 哦哦 明白了 谢谢

嗨，理解就好。

既然回复了这么多内容，太不容易了，要是方便的话，请一定要去 [Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评哦~

**Comment by HJCFLY** [comment]
那必须的 老哥奥里给
