### ISSUE TITLE
 地址 ：https://segmentfault.com/a/1190000040000927  浏览器中可以打开，加入稍后读后，阅读模式无法打开，配置同步助手也不可以

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2195]
地址 ：https://segmentfault.com/a/1190000040000927  浏览器中可以打开，加入稍后读后，阅读模式无法打开，配置同步助手也不可以
![接口显示](https://user-images.githubusercontent.com/23255790/118945039-aaab2b00-b987-11eb-867c-8e237ef29f5d.jpg)
![错误显示](https://user-images.githubusercontent.com/23255790/118945046-ac74ee80-b987-11eb-9413-9f1f1edc2f86.jpg)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

估计这是个 Bug，这几天太忙了，等过了这几天我详细调查下会给出解决方案的。
