### ISSUE TITLE
官网首页 图文不符

### ISSUE THREAD

**Issue by Phantr4x** [Kenshin/simpread#22]
![image](https://user-images.githubusercontent.com/5728981/27262407-de073758-541b-11e7-9f05-e9622a11e1e0.png)

**Comment by Kenshin** [comment]
感谢发现~

关于这个 `import/export` 的方向问题，是不是没有定论？我不是 Designer 所以，不清楚目前主流标准是什么... 😷

**Comment by Phantr4x** [comment]
其实我也是感觉不合直觉 :joy:

**Comment by Kenshin** [comment]
我专门查了几个 icon search 类的网站，大多是你截图上的方向，所以官网的应该没问题。
但是... 我发现 扩展的设定页面中的 icon 是反的... :sob:

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`，更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
