### ISSUE TITLE
sports.sina.com.cn

### ISSUE THREAD

**Issue by BetterYoung** [Kenshin/simpread#220]
hope match this site, please. thanks

**Comment by Kenshin** [comment]
配置完会通知你，不过，近期在休假。

**Comment by BetterYoung** [comment]
哇~没想到会收到回信~~感谢！



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-01-24 19:09
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
配置完会通知你，不过，近期在休假。

**Comment by Kenshin** [comment]
每条 issues 我都会回复，你这条还算晚了… 😄

**Comment by BetterYoung** [comment]
非常感谢，当时是抱着试试看的想法反馈的~
目前在用 JustRead 扩展，也是有一些适配不完美的。不过页面效果比简悦差不少~



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-01-24 19:13
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
每条 issues 我都会回复，你这条还算晚了… ????

**Comment by Kenshin** [comment]
还是建议使用简悦，你可以对比就知道了。
为了做到差异化，我都是对比过的， 😃

**Comment by BetterYoung** [comment]
嗯，简悦的页面体验确实很优雅，功能和细节也很用心



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-01-24 19:22
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
还是建议使用简悦，你可以对比就知道了。
为了做到差异化，我都是对比过的， ????

**Comment by BetterYoung** [comment]
hello,
    请问如果想在打开官方已经适配的网站时，自动进入阅读模式，是不是只能手动将适配网址列表添加至白名单才可以？



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-01-24 19:22
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
还是建议使用简悦，你可以对比就知道了。
为了做到差异化，我都是对比过的， ????

**Comment by Kenshin** [comment]
选项 → 高级定制
里面有个叫做「自动进入阅读模式」的选项。

**Comment by BetterYoung** [comment]
OK，已经设置好了，谢谢~

**Comment by Kenshin** [comment]
客气哈～
多看看帮助中心，虽然也得也不太详细… 😂

**Comment by BetterYoung** [comment]
设置参数很详细了，是我没仔细看，大致一扫只看到白名单了 



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-02-05 20:38
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
客气哈～
多看看帮助中心，虽然也得也不太详细… ????

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

**Comment by BetterYoung** [comment]
感谢！



hawkeyes.yq@gmail.com
 
From: Kenshin Wang
Date: 2018-03-29 15:11
To: Kenshin/simpread
CC: BetterYoung; Author
Subject: Re: [Kenshin/simpread] sports.sina.com.cn (#220)
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 手动更新 ，此 issues 将关闭。
