### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by youiar** [Kenshin/simpread#2202]
发生问题的地址: <https://www.lanqiao.cn/courses/1/learning/?id=3%3Fsimpread_mode%3Dread>

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

- 简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

- 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 https://github.com/Kenshin/simpread/issues/2158

**Comment by Kenshin** [comment]
> 再说下你的问题。

这个页面没有适配的必要，我直接关闭此 issues 了。

**Comment by youiar** [comment]
了解，不过顺便问一下兑换码什么时候发，20号凌晨买的了


 
---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2021年5月21日 19:08:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 无法适配当前页面 (#2202)




  
再说下你的问题。
  
这个页面没有适配的必要，我直接关闭此 issues 了。
