### ISSUE TITLE
已经开通每日回顾，但是并没有自动给我发邮件，邮件功能是正常的，我可以手动把稍后读发邮件到邮箱，24小时之内有稍后读的新内容

### ISSUE THREAD

**Issue by Karl-Heinrich-Marx** [Kenshin/simpread#2203]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by binsee** [comment]
> 我又重新看了说明，是需要将稍后读的内容手动保存到坚果云吗？24小时内保存到坚果云的稍后读才会在七点左右发邮件吗？

不用手动保存，加入稍后读即可。 详细使用方式见 [每日回顾 - 文档中心 - 简悦 SimpRead - 如杂志般沉浸式阅读体验的扩展](http://ksria.com/simpread/docs/#/%E6%AF%8F%E6%97%A5%E5%9B%9E%E9%A1%BE)

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

- 简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

- 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 https://github.com/Kenshin/simpread/issues/2158

***

谢谢 @binsee 的提示。


不过，这个功能似乎有点 Bug 会导致个别用户无法收到邮件，等忙完了这段时间，我需要 review 下这块的代码。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，已重新开启此 Issues

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
> 以下是 2.2.0 的相关介绍，请让我重新介绍一次。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by jueshikuangshen** [comment]
> 嗨，抱歉，今天一直在处理文档的事情，耽搁了。
> 
> * 简悦 2.2.0 文档已全部更新，细节请看 [简悦 2.2.0 新版本相关问题汇总（如维基百科无法正常显示的解决方案） #2158 (comment)](https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642)
> * 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 [简悦 2.2.0 新版本相关问题汇总（如维基百科无法正常显示的解决方案） #2158](https://github.com/Kenshin/simpread/issues/2158)
> 
> 谢谢 @binsee 的提示。
> 
> 不过，这个功能似乎有点 Bug 会导致个别用户无法收到邮件，等忙完了这段时间，我需要 review 下这块的代码。

请问邮箱服务的`发送邮件地址`和`接受的邮箱地址`有什么区别？？？发送邮箱地址从哪里获取？

**Comment by Kenshin** [comment]
> 请问邮箱服务的`发送邮件地址`和`接受的邮箱地址`有什么区别？？？发送邮箱地址从哪里获取？

一般来说，发送邮件和接收邮件设置为一个即可。发送邮件的意思是：借助你的邮箱发送邮件（而非通过简悦的邮箱）。

**Comment by Kenshin** [comment]
嗨，各位：

> 每日回顾功能已经修复了。

一个建议：使用 QQ 等国内邮箱作为中转邮箱方案，这样效果更好些。

我关闭这个 issues 了。

**Comment by Karl-Heinrich-Marx** [comment]
> 嗨，各位：
> 
> > 每日回顾功能已经修复了。
> 
> 一个建议：使用 QQ 等国内邮箱作为中转邮箱方案，这样效果更好些。
> 
> 我关闭这个 issues 了。

你好，我使用了qq邮箱作为发送邮箱，每日回顾功能可以正常订阅，邮件手动发送正常，且24小时内有新的稍后读，但每晚七点没有自动发送给我的每日回顾邮件，请问还可能是哪里存在的问题。

**Comment by Kenshin** [comment]
> 你好，我使用了qq邮箱作为发送邮箱，每日回顾功能可以正常订阅，邮件手动发送正常，且24小时内有新的稍后读，但每晚七点没有自动发送给我的每日回顾邮件，请问还可能是哪里存在的问题。

嗨，请把你的配置文件发到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）
另外，我会用你的账户测试，所以你的邮箱可能会收到一些每日回顾的邮件。

**Comment by Karl-Heinrich-Marx** [comment]
> > 你好，我使用了qq邮箱作为发送邮箱，每日回顾功能可以正常订阅，邮件手动发送正常，且24小时内有新的稍后读，但每晚七点没有自动发送给我的每日回顾邮件，请问还可能是哪里存在的问题。
> 
> 嗨，请把你的配置文件发到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`） 另外，我会用你的账户测试，所以你的邮箱可能会收到一些每日回顾的邮件。

您好，非常感谢您及时的回复和提供的帮助，我已经将配置文件发送到了help@simpread.pro这个地址，显示已发送成功，很期待能够收到每日回顾的邮件，这个功能我非常喜欢。

**Comment by Kenshin** [comment]
@Karl-Heinrich-Marx 

我已经收到，但只能明天确认了，确认后我会回复你的。（方便的话，请明天增加一些稍后读数据。

**Comment by Kenshin** [comment]
@Karl-Heinrich-Marx 

嗨，我看了下，在坚果云里面的稍后读最新日期，显然不符合 **二十四小时** 以内这个条件。

![image](https://user-images.githubusercontent.com/81074/139634237-66bfd7b1-c538-427a-a2ed-c64ea6c9594c.png)

请保证 `同步盘/SimpRead/simpread_config.json` 是最新的，可以使用：

- https://github.com/Kenshin/simpread/discussions/2754
- [手动同步](http://ksria.com/simpread/docs/#/%E5%90%8C%E6%AD%A5?id=%e6%89%8b%e5%8a%a8%e5%90%8c%e6%ad%a5)

**Comment by Karl-Heinrich-Marx** [comment]
> @Karl-Heinrich-Marx
> 
> 嗨，我看了下，在坚果云里面的稍后读最新日期，显然不符合 **二十四小时** 以内这个条件。
> 
> ![image](https://user-images.githubusercontent.com/81074/139634237-66bfd7b1-c538-427a-a2ed-c64ea6c9594c.png)
> 
> 请保证 `同步盘/SimpRead/simpread_config.json` 是最新的，可以使用：
> 
> * [[新手教程]如何安装和配置同步助手 #2754](https://github.com/Kenshin/simpread/discussions/2754)
> * [手动同步](http://ksria.com/simpread/docs/#/%E5%90%8C%E6%AD%A5?id=%e6%89%8b%e5%8a%a8%e5%90%8c%e6%ad%a5)

非常感谢你的帮助，我忽视了同步助手与坚果云同步文件夹路径的一致性，并在你提供的问题中找到了解决办法，我想不出意外，明天我就能收到每日回顾的邮件了。这是一个非常好的插件，我已经将它推荐给了身边的朋友。

**Comment by Kenshin** [comment]
@Karl-Heinrich-Marx 

哈哈，谢谢推荐，如每日回顾彻底没问题后，别忘记回来知会下，
