### ISSUE TITLE
建议搜索模式可以搜索标记内容~

### ISSUE THREAD

**Issue by moon290** [Kenshin/simpread#2204]
现在搜索似乎只能搜索标签，建议搜索模式可以搜索标记内容，有时候一篇笔记里面包含多个关键词，这样的话方便查找笔记~

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

- 简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

- 简悦 2.2.0 发布后产生了一些通用性问题，细节请看 https://github.com/Kenshin/simpread/issues/2158

**Comment by Kenshin** [comment]
> 再说下你的问题。

你是说列表栏吗？它可以搜索的内容在列表栏已经给出了。

![image](https://user-images.githubusercontent.com/81074/119128253-00ef9b00-ba68-11eb-9653-a0f302973cde.png)

建议使用 [Panel栏的搜素方案](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80?id=%e6%94%af%e6%8c%81%e5%a4%9a%e7%a7%8d%e6%a3%80%e7%b4%a2%e6%96%b9%e5%bc%8f)

此功能基础账户就可以使用。

**Comment by moon290** [comment]
我的意思是 可以搜索用颜色标记的网页的里的内容

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，不知道是否解决了？
