### ISSUE TITLE
简悦导入新版语雀异常

### ISSUE THREAD

**Issue by jswfly** [Kenshin/simpread#2207]
- 操作系统 **Windows 10**
- 浏览器版本 **Chrome 90.0.4430.85**
- 语雀桌面客户端版本  **0.8.13**
- 简悦版本 **2.2.0**

**简悦导入新版语雀异常**
语雀桌面客户端不支持老Markdown,但网页端可以查看
> 
![image](https://user-images.githubusercontent.com/26086558/119083008-c408b180-ba31-11eb-8099-bc7e852bb2e4.png)

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

***

> 再说下你的问题。

我没理解这个意思，你试试将 md 复制到剪切板，看看能否成功？这个问题跟简悦是无关的。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，不知道是否解决了？
