### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by duibuqiqingchun** [Kenshin/simpread#2210]
发生问题的地址: <http://www.jinan.gov.cn/art/2021/5/20/art_1812_4783425.html>

**Comment by Kenshin** [comment]
嗨，抱歉，今天一直在处理文档的事情，耽搁了。

简悦 2.2.0 文档已全部更新，细节请看 https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

***

> 再说下你的问题。

你可以使用 [手动框选](http://ksria.com/simpread/docs/#/%E6%89%8B%E5%8A%A8%E6%A1%86%E9%80%89) 解决这个问题。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。
