### ISSUE TITLE
阅读模式下代码段显示错位

### ISSUE THREAD

**Issue by leemos-xx** [Kenshin/simpread#2211]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **macOS Big Sur**

- 浏览器版本 **e.g. Chrome 90.0.4430.212**

- 简悦版本 **2.2.0**

原始网页这两处代码是在一起的
<img width="746" alt="correct" src="https://user-images.githubusercontent.com/7057406/119102579-c2001c00-ba4c-11eb-8830-cbe5801d15c6.png">

阅读模式下被分开了，导致后续所有的代码块也都错位了。
<img width="866" alt="err" src="https://user-images.githubusercontent.com/7057406/119102601-c7f5fd00-ba4c-11eb-946f-21c9911caedb.png">

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
