### ISSUE TITLE
关于图片防盗链/本地化问题

### ISSUE THREAD

**Issue by NTDLX** [Kenshin/simpread#2213]
当前保存到有道云笔记等软件时，并没有将图片保存下来，只是保存了图片的超链接，希望可以将图片和文字一并保存到有道云笔记，这样可以确保就算原网页失踪了也能正常阅读。
如果不能将图片等多媒体内容一并保存下来，原网页一旦被删除或者无法访问，保存到有道云笔记等软件中文章也无法正常阅读，会出现只有文字没有图片的情况，
希望开发者可以解决此问题，感谢。

**Comment by NTDLX** [comment]
实际上目前即使原网页没被删除也是难以阅读的状态，许多网站有基础的防盗链等措施，如果不能将图片文件一并导出，会出现如下情况。
![image](https://user-images.githubusercontent.com/34884072/119129322-57a9a480-ba69-11eb-8a0e-225f12fda484.png)

**Comment by Kenshin** [comment]
嗨，谢谢建议。

目前具有图床功能的方案：Notion

建议使用导出离线 HTML 的方案，后续会考虑加入各种服务的图床功能。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，已重新开启此 Issues

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
> 以下是 2.2.0 的相关介绍，请让我重新介绍一次。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by NTDLX** [comment]
详细更新记录中提到的许多功能都要用到本地同步助手，个人认为最好集成到浏览器插件里，而非需要用户额外安装客户端。

**Comment by Kenshin** [comment]
> 详细更新记录中提到的许多功能都要用到本地同步助手，个人认为最好集成到浏览器插件里，而非需要用户额外安装客户端。

嗨，收到。（ 我没有说这个功能要做在 同步助手 里面哦~ 原本就应该在扩展端做的。

**Comment by EternalHXP** [comment]
> 嗨，谢谢建议。
> 
> 目前具有图床功能的方案：Notion
> 
> 建议使用导出离线 HTML 的方案，后续会考虑加入各种服务的图床功能。

如果 简悦2.x以后可以提供 导出Markdown文件，图片提供阿里云、腾讯云 图床自动上传转md链接就好了。 
现在各种笔记的保存到笔记功能，都是把图片做到自己内部api里，都没有提供标准的图床+链接功能，限制了笔记的离线和共享流转。

**Comment by Kenshin** [comment]
@EternalHXP 

嗨，确实如你所说，我会考虑的。
这点跟简悦想做的事情很吻合。

**Comment by NTDLX** [comment]
> 嗨，谢谢建议。
> 
> 目前具有图床功能的方案：Notion
> 
> 建议使用导出离线 HTML 的方案，后续会考虑加入各种服务的图床功能。

您好，在使用Notion方案时发现动图GIF会被保存成静态图片。

**Comment by Kenshin** [comment]
> 您好，在使用Notion方案时发现动图GIF会被保存成静态图片。

嗨，给个 URL 看看。

**Comment by NTDLX** [comment]
> > 您好，在使用Notion方案时发现动图GIF会被保存成静态图片。
> 
> 嗨，给个 URL 看看。

https://b23.tv/T2aWmA
文中最后几张图片是GIF

**Comment by Kenshin** [comment]
收到，我刚测试了下，**导出为 md 到本地，是没问题**的，这么看的话，就是 Notion 自己的问题了。

导到本地的内容就是我传给 Notion 的内容。

**Comment by jueshikuangshen** [comment]
> 嗨，谢谢建议。
> 
> 目前具有图床功能的方案：Notion
> 
> 建议使用导出离线 HTML 的方案，后续会考虑加入各种服务的图床功能。

请问“导出离线 HTML 的方案”图片是存储在哪里？原文消失了，图片还能看到吗？

**Comment by Kenshin** [comment]
> 请问“导出离线 HTML 的方案”图片是存储在哪里？

以 base64 的形式存到 HTML 里面。

> 原文消失了，图片还能看到吗？

当然可以看到。

**Comment by jueshikuangshen** [comment]
非常感谢



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2021年7月30日(周五) 下午3:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 关于图片防盗链/本地化问题 (#2213)




  
请问“导出离线 HTML 的方案”图片是存储在哪里？
  
以 base64 的形式存到 HTML 里面。
  
原文消失了，图片还能看到吗？
  
当然可以看到。

**Comment by Kenshin** [comment]
![PicGo](https://user-images.githubusercontent.com/81074/182798678-f318f7b7-d637-4faa-acd4-5c1dd2f73710.png)

嗨，简悦增加了 **图床插件** 支持支持国内大多数的图床服务：七牛、腾讯云、阿里云、又拍云、Github、SM.MS、Imgur 图床等，并支持当前转换为图床后，可自动选择一个导出服务，包括：触发插件的动作、导出到本地、导出到生产力工具、Webhook、WebDAV。

详细说明👉https://github.com/Kenshin/simpread/discussions/4306


所以，我关闭此 Issues 了
