### ISSUE TITLE
关于离线html文件标注问题

### ISSUE THREAD

**Issue by cui-2017** [Kenshin/simpread#2214]
我目前使用环境是用Zotero保存网页，然后用Chrome打开html格式的网页（本地文件格式），然后使用简悦阅读、标注。
本身我的设想是使用简悦对离线的html文件本体上进行高亮等操作，并允许保存在原目录下，但是似乎简悦并不支持在原网站上的标注行为。
其次我注意到保存html格式的文件是我自己选定的某个文件下，但是Zotero（类似于endnote的文献管理软件）是采用文件夹镶嵌的方式，如图所示
![image](https://user-images.githubusercontent.com/64975195/119129149-1d400780-ba69-11eb-8a1d-ef6a53505638.png)
希望未来可以支持html本地文件的标注及在原目录下的自动保存

**Comment by Kenshin** [comment]
嗨，谢谢建议。

> 并允许保存在原目录下，但是似乎简悦并不支持在原网站上的标注行为。

简悦是可以这么做的。目前缺失这方面的教程，但是有文档，你既然可以用 Zotero 的话，估计动手能力比较强，可以看看 

- 稍后读
  - [稍后读 · 离线加载](http://ksria.com/simpread/docs/#/稍后读?id=离线加载)
  - [稍后读 · 自动保存到本地](http://ksria.com/simpread/docs/#/稍后读?id=自动保存到本地)
- 标注
  - [标注 · 自动保存到本地](http://ksria.com/simpread/docs/#/标注?id=自动保存到本地)

更多文档的介绍  https://github.com/Kenshin/simpread/issues/2158#issuecomment-845868642

我后续会加入这方面的教程。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
@cui-2017 

嗨，新文档已经出来，你可以在 https://github.com/Kenshin/simpread/discussions/categories/服务 查看相关教程，跟你有关系的包括

https://github.com/Kenshin/simpread/discussions/2146 https://github.com/Kenshin/simpread/discussions/2220 这两篇。

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，不知道是否解决了？

搞定的话，如果网络允许的话，请去 Webstore 帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 吧  😂
