### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by luxunL** [Kenshin/simpread#2218]
发生问题的地址: <https://www.shanbay.com/news/articles/rvtqx>

**Comment by Kenshin** [comment]
嗨，扇贝阅读的页面之前已经有用户提过了，我把这个 Issues 加到了 https://github.com/Kenshin/simpread/issues/2112 里面了，再加上下面的原因，所以我先关闭这个 Issues 了。

***

抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，此站已经适配，请更新适配列表

![image](https://user-images.githubusercontent.com/81074/130352745-f125619f-2226-4e31-8b7e-cd41b11c347c.png)

### 进阶使用

另外，也可以使用 [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 获得更好的使用方案，如下图：

![iShot2021-08-22 18 57 05](https://user-images.githubusercontent.com/81074/130352775-4ade5777-09bd-453c-bd54-96f80ade844f.png)

### 备注

使用翻译后的结果（双语）支持导出 HTML / Markdown 等格式。
