### ISSUE TITLE
保存到onenote能自己设置保存到哪个分区吗？

### ISSUE THREAD

**Issue by jingouwangzi** [Kenshin/simpread#222]
每次都是自动保存到默认的OneNote介绍及教程这个分区，请问能够自己设置吗？

**Comment by Kenshin** [comment]
简悦为了简化操作步骤目前只保存到默认目录。😔

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
