### ISSUE TITLE
edge 端未更新

### ISSUE THREAD

**Issue by 11-check-it-out** [Kenshin/simpread#2223]
![image](https://user-images.githubusercontent.com/47976614/119215257-24195980-baff-11eb-96cf-65242fbcdfe8.png)

**Comment by Kenshin** [comment]
嗨，是的 Edge 可能会稍晚些发布，下周可能会发布一个 Chrome 的补丁版本，如果时间来得及，会考虑同步上到 Edge

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。
