### ISSUE TITLE
LaTeX 识别相关

### ISSUE THREAD

**Issue by fornewfork** [Kenshin/simpread#2224]
- 操作系统  Windows

- 浏览器版本 Chrome 90.0.4430.212

- 简悦版本 2.2.0

- 发生问题的地址  https://epubs.siam.org/doi/abs/10.1137/20M1365776
数学公式的latex识别失效，如下图
![图片](https://user-images.githubusercontent.com/36132892/119219066-233ff200-bb16-11eb-9156-43be8b577dc2.png)

- 能否考虑添加指定域名或网站，在**不进入阅读模式的情况下**启动latex识别的功能？
原因是我用自动化工具把论文的摘要等信息抓取作为邮件正文发到gmail了，在gmail中阅读时公式也不会自动识别，可能是比较小众的需求。。。
![图片](https://user-images.githubusercontent.com/36132892/119219232-18399180-bb17-11eb-9da4-b4c35f406b0e.png)

**Comment by Kenshin** [comment]
嗨，之前漏掉了这个 issues 。我发现原文似乎也没有被显示出来，如下图（原文）：

![image](https://user-images.githubusercontent.com/81074/119244916-ae1cfd00-bba7-11eb-81f2-f78d03ce1d87.png)

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。
