### ISSUE TITLE
开启「预先加载惰性图片」功能后，知乎无法显示部分动图

### ISSUE THREAD

**Issue by wukong999** [Kenshin/simpread#2227]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Windows 

- 浏览器版本 360极速

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.zhihu.com/question/385302999/answer/1809402376>

**更新后动图不显示啊什么情况啊大佬**

**Comment by Kenshin** [comment]
嗨，确实有点问题，但跟简悦无关。2.1 应该也存在此问题。简单的说，知乎使用的惰性加载图片的逻辑似乎有问题...

不清楚是否是个例？你在观察下，如果每个知乎页面都是如此的话，再反馈给我。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by binsee** [comment]
@Kenshin 这个问题需要重开。

此问题可以在 2.2.0.520 版本，开启 `预先解析懒加载图片` 功能的情况下稳定复现。

在2.2.0版本中，新增了 `预先解析懒加载` 图片这个功能，可以将原本页面上的懒加载图片元素改为非懒加载模式，以便简悦在自动进入阅读模式时能稳定的获取到真实的图片地址。

这里看一下当前知乎问答适配规则中，处理懒加载图片的代码：

```js
[[{(function(){
	$('sr-rd-content figure noscript')
	.each(function(){
		var noscript = $(this).text();
		if(noscript.match(/<img/)) {
			var img = $(this).parent().empty().append(noscript).find('img');
			var src = img.attr('src') || '';
			if(src.match(/.gif/)) img.attr('real_src',src);
		}
	});
}())}]]
```

我在规则中，是在简悦提取高亮后，在简悦提取到的高亮内容节点里对懒加载元素进行处理，不会干扰原始页面上的内容。

而简悦新增的 `预先解析懒加载图片` 功能，是在页面加载后，立即对原始页面上的懒加载元素进行处理，将其转变为非懒加载，然后进入阅读模式。

但当前对知乎的适配中，处理懒加载时，还有额外的一点要注意，就是动态图片gif的处理。见 #1099 

-----------

## 当前的解决方案

当前有以下解决方案，依次是速度最快到最慢：

1. 关闭 `预先解析懒加载图片` 功能
![image](https://user-images.githubusercontent.com/5285894/122590653-6ef1a700-d094-11eb-99cb-8e3140b563c1.png)
2. 更新知乎适配规则，兼容 **开启 `预先解析懒加载图片` 功能** 的情况
3. 简悦的 puplugin 中，处理 img 元素时，按属性优先级选择使用的属性时，自动检测 url 中是否有 `.gif` ，将其优先级最为最高来处理。

**Comment by Kenshin** [comment]
@binsee 

收到，已重开~

**Comment by binsee** [comment]
建议标题改一下： 开启 预先加载惰性图片 功能后，知乎无法显示部分动图

**Comment by Kenshin** [comment]
> 建议标题改一下： 开启 预先加载惰性图片 功能后，知乎无法显示部分动图

Done~

**Comment by binsee** [comment]
修正解决方案3：
> ~简悦的 puplugin 中，处理 img 元素时，按属性优先级选择使用的属性时，自动检测 url 中是否有 .gif ，将其优先级最为最高来处理。~

修正为：
处理img元素时，按优先级选择属性，并保留其他备选url地址，以供站点适配中修正提取错误的img url。

原因见如下懒加载方式：
![image](https://user-images.githubusercontent.com/5285894/123732412-756df300-d8cc-11eb-9667-efd9e2888f17.png)

- 知乎中，gif动图的占位使用了静态缩略图，因此正确的url是带gif的，需要高优先将gif的url视为正确的
- 上图中，使用了gif作为懒加载占位，不能高优先将gif作为正确的结果

**Comment by Kenshin** [comment]
@binsee 

我重新适配了知乎专栏与问答页的内容，算是彻底解决了这个问题，细节可以看下 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
@wukong999 

嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
