### ISSUE TITLE
加入稍后读 导出 PDF自动化

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2228]
同样问题，我是  **加入稍后读**  **导出 PDF自动化** 也无效，本地没有pdf文件

_Originally posted by @JokAlec in https://github.com/Kenshin/simpread/issues/2055#issuecomment-846425347_

**Comment by Kenshin** [comment]
嗨  @JokAlec 我帮你新建了一个 Issues 。

***

首先自动化导出 PDF 是没问题的，因为几乎我明天都在用此功能。

***

但你给出的信息太少了，我没法判断。所以请给出一些必要信息（如果要实现此功能，需要：

1. 同步助手导出目录的配置
2. 自动化的配置
3. 在什么情况下导出 PDF 无效？阅读模式？还是稍后读里面？
4. 什么页面？（另外，请使用毕竟正规的页面，如 https://sspai.com/post/39491 先确保排除页面本身问题
5. 另外，你可以试试使用自动化导出其它功能，如：HTML 看看是否都不好使？

另外，看看这个问题 https://github.com/Kenshin/simpread/discussions/2225

**Comment by Kenshin** [comment]
因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by JokAlec** [comment]
感谢感谢，是我没说清楚

1、同步助手导出目录配置好了，在稍后读中手动导出pdf，html都没有问题
2、自动化配置也做了，也做了其他导出自动化尝试
![image](https://user-images.githubusercontent.com/79049115/119246031-7d8d9100-bbb0-11eb-95c8-79db2d033329.png)

我的操作：
网页按DD快捷键加入稍后读，但是自动化没有运行，output中没有pdf，只能到稍后读手动导出pdf

**Comment by Kenshin** [comment]
我大概知道你的问题了。

如果在未进入阅读模式下 → 加入稍后读 → 是不会触发自动化的，只有在阅读模式下才可以。

**Comment by JokAlec** [comment]
![image](https://user-images.githubusercontent.com/79049115/119246367-9481b280-bbb3-11eb-8f3c-190e13626158.png)
我也刚发现了，非常感谢

**Comment by Kenshin** [comment]
okay 我会在需要的位置加上说明~
