### ISSUE TITLE
此插件影响到HTML5视频的播放

### ISSUE THREAD

**Issue by qq5622005** [Kenshin/simpread#223]
浏览器是chrome，中国大学MOOC下播放视频，使用HTML5播放器，插件会造成，鼠标点击画面任何地方，进度条就会跟着到鼠标的地方，点击静音，进度条也跟着到静音。 之前在爱奇艺看视频时，也有出现点暂停卡顿后无法暂停的情况。我关闭此插件后，就没有再出现过这种问题了。

**Comment by qq5622005** [comment]
切换到Flash播放器就不会。

**Comment by Kenshin** [comment]
感谢反馈～
我先记 Bug 修复后会通知你。

**Comment by Kenshin** [comment]
估计是某些 lib 冲突了，但是我找了半天没有找到一个可以播放的 url ...  😂 能否给个 url
未来会加入不启动名单，加入这个名单的页面都不会启动简悦，这样就不会发生这样的问题了。

**Comment by qq5622005** [comment]
万分抱歉，关了插件我刚试了一下后也会这样。不知道是什么原因。谷歌浏览器也是最新的。可能是某些插件冲突了。浪费了大佬的时间，万分抱歉！

**Comment by qq5622005** [comment]
用Revo Uninstaller Pro完全卸载干净谷歌浏览器再重装就不会发生这种情况了。这是软件PJ链接: https://pan.baidu.com/s/1kXoYnjx 密码: teru

**Comment by Kenshin** [comment]
搞定就好，我将关闭此 issues ，未来加入【不启动名单】后，很容易能排除掉是否是简悦造成的问题。😃
