### ISSUE TITLE
Telegram Bot 收藏稍后读失败

### ISSUE THREAD

**Issue by gerrampard** [Kenshin/simpread#2231]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **IOS**

- 浏览器版本 **N/A**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

https://wechaty.js.org/2021/04/13/wechaty-uos-web/

以及其他任何网页

**请描述你的问题**

简悦 telegram bot 接收到文章网址后 出现 “当前提交的内容未包含任何有效信息。”的提示，无法加入简悦稍后读。

尝试过的操作：
1. tg bot中，删除token，重绑token
2. 重置token
3. 重新授权 dropbox 
4. 云端覆盖简悦配置
 
p.s. MacOS Chrome中 加入稍后读没有问题。之前2.1版tg bot 也正常。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![simpread tg bot](https://user-images.githubusercontent.com/63440768/119249376-acb0fc00-bbca-11eb-9596-56eda29cd966.jpg)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by iamalexblue** [comment]
相同的问题，现在解决了吗老哥
