### ISSUE TITLE
页面适配问题

### ISSUE THREAD

**Issue by clarkance** [Kenshin/simpread#2232]
[脚本之家的页面](https://www.jb51.net/article/131212.htm)
页面代码块识别异常 

![image](https://user-images.githubusercontent.com/27039466/119253242-e130b200-bbe2-11eb-8b53-84d861b1a797.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
