### ISSUE TITLE
非阅读模式下开启标注

### ISSUE THREAD

**Issue by lancerXXXX** [Kenshin/simpread#2233]
有些网站格式不正确，尤其是代码块，例如
[vue3](https://vue3js.cn/docs/zh/guide/component-basics.html#%E8%A7%A3%E6%9E%90-dom-%E6%A8%A1%E6%9D%BF%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

![image](https://user-images.githubusercontent.com/42160297/119254747-bb0f1000-bbea-11eb-98f7-03fe80b78c63.png)

希望批注模式能在显示原页面的情况下使用，例如其他类似的主打批注功能的插件，可以在阅读模式不理想的情况下在原页面下批注

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by Kenshin** [comment]
另外，关于标注的问题。

**简悦希望如果有整篇内容的文章才适合使用简悦的标注**。否则只有一两句话的话，有很多其它工具更适合这种方式。

**Comment by Kenshin** [comment]
> 以下是 2.2.0 的相关介绍，请让我重新介绍一次。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by lancerXXXX** [comment]
> 另外，关于标注的问题。
> 
> **简悦希望如果有整篇内容的文章才适合使用简悦的标注**。否则只有一两句话的话，有很多其它工具更适合这种方式。

我的意思也是整篇的文章，是希望在阅读模式适配的不好的情况下可以选择在原页面标注
因为遇到过有的网站打开阅读模式只剩下标头和footer了，中间的内容不见了，这种情况下无法标注，同时急着标注，不能等待官方适配或者自己慢慢改

**Comment by Kenshin** [comment]
嗨，有解决方案 http://ksria.com/simpread/welcome/version_2.2.0.html#manul

**Comment by lancerXXXX** [comment]
> 嗨，有解决方案 http://ksria.com/simpread/welcome/version_2.2.0.html#manul

OK

**Comment by Kenshin** [comment]
手动方案可以将任意内容生成阅读模式，这样就可以标注了。
同时，也可以纳入简悦的生态系统（各种功能）。

除非你想标注一条内容而已（这种方式完全可以不需要使用简悦）
否则手动方案是最优选择。

**Comment by Kenshin** [comment]
如果这个功能解决了你的诉求，网络允许的话，请去 Webstore 帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 吧  😂

**Comment by lancerXXXX** [comment]
> 如果这个功能解决了你的诉求，网络允许的话，请去 Webstore 帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 吧 😂

可
