### ISSUE TITLE
开通高级账户后导出epub失败

### ISSUE THREAD

**Issue by hqsiswiliam** [Kenshin/simpread#2234]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- **Windows 10**

- **Chrome 90.0.4430.212**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://www.ft.com/content/a2a720c0-8c21-433b-8ebe-9256671a82b6
  - 不过只要开了高级账号，每个地址都有如下描述的问题

**请描述你的问题**

> 开通高级账户后，选择导出epub反而失败，提示说”此功能为实验性功能，如有需求请提Issues“。本机已安装同步助手1.0.1与pandoc了。如果关闭epub的增强导出，反而可以使用。

**Comment by Kenshin** [comment]
嗨，我明天确认下这个问题。

另外，你可以做以下测试：

- PDF 是否可以正常输出
- HTML 是否可以正常输出
- 请使用正常些的 URL 如 https://sspai.com/post/61996

如果可以，说明你提交的 URL 有问题

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by hqsiswiliam** [comment]
测试了这个网址，epub依旧导不出来，PDF与HTML可以（ft.com中也可以导出Pdf和html)。

**Comment by Kenshin** [comment]
emmm 

我大概知道什么问题了。
你看看能否在命令行下运行 pandoc ？

**Comment by hqsiswiliam** [comment]
可以的，运行结果如下：
![image](https://user-images.githubusercontent.com/5647879/119273540-00106200-bc3e-11eb-950d-d684086960bd.png)

**Comment by Kenshin** [comment]
@hqsiswiliam 

嗨，我今天用 win 测试下这个问题。

另外，你之前提到基础账户是可以的，原因是此方案调用了一个第三方服务，跟 pandoc 与 同步助手的方案无关。

我调查后再回复你。

**Comment by Kenshin** [comment]
@hqsiswiliam

嗨，我重现了这个问题，修复后会通知你。

**Comment by Kenshin** [comment]
嗨，问题已经解决，请 [重新下载](http://ksria.com/simpread/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) 同步助手。

**Comment by Kenshin** [comment]
我在 Re-check 之前的 Issues ，不知道是否解决了？

搞定的话，如果网络允许的话，请去 Webstore 帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 吧  😂

**Comment by hqsiswiliam** [comment]
👌👌，好的。感谢，问题已解决。一定会给五星好评的😃😃

**Comment by Kenshin** [comment]
谢谢。 🙏

另外， 简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，**此问题彻底被解决**，未防止再次发生这类情况。

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
