### ISSUE TITLE
无法授权验证同步助手，已运行同步助手但却还是显示没有运行

### ISSUE THREAD

**Issue by Birdling** [Kenshin/simpread#2235]
![image](https://user-images.githubusercontent.com/62651551/119263987-e3f7cb00-bc13-11eb-80d7-d9b95f7e2593.png)
issue上查过，检查了（下图）
![image](https://user-images.githubusercontent.com/62651551/119264014-02f65d00-bc14-11eb-88ec-29f948e88833.png)

**Comment by Kenshin** [comment]
嗨，点击蓝色的验证就行，不用理会这个提示。

点击后会有明确提示。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Birdling** [comment]
> 嗨，点击蓝色的验证就行，不用理会这个提示。
> 
> 点击后会有明确提示。

 点击蓝色按钮无反应

**Comment by Kenshin** [comment]
看看后台保错信息是什么？

**Comment by Birdling** [comment]
从哪里看呢

**Comment by Kenshin** [comment]
右键 → 检查

**Comment by Birdling** [comment]
![image](https://user-images.githubusercontent.com/62651551/119294374-e6473d00-bc86-11eb-8a40-ff34d5937221.png)
哪块复制过来呢？

**Comment by Kenshin** [comment]
点击这里

![image](https://user-images.githubusercontent.com/81074/119295314-23143380-bc89-11eb-881f-e86dde7d0557.png)

然后，把下面出现的结果给我。


你是不是运行了某些防火墙之类的？

**Comment by Birdling** [comment]
![image](https://user-images.githubusercontent.com/62651551/119295844-64f1a980-bc8a-11eb-883e-36db7296201c.png)

没有运行防火墙，ublock Origin插件是灰色的

**Comment by Kenshin** [comment]
emm 太奇怪了。

报错的提示是：访问同步助手服务失败。你看看这个界面是否设置正确了？（windows 上可能界面有些不太一样

![image](https://user-images.githubusercontent.com/81074/119297749-29f17500-bc8e-11eb-91d8-5d52ec412b43.png)

**Comment by Birdling** [comment]
这个是哪里的右键？我也是mac

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/119300910-29f47380-bc94-11eb-8f4e-f133da039525.png)

**Comment by Birdling** [comment]
OK绑定成功了，一直没注意这些，谢谢！

**Comment by Kenshin** [comment]
天啊，太不容易了...  😭 

这个选项默认是开启的。
