### ISSUE TITLE
请问可否在"全文+标注“模式导出pdf时，一并导出全文+标注，并且相应的标注被高亮？

### ISSUE THREAD

**Issue by Phoebeart** [Kenshin/simpread#2238]
请问可否在"全文+标注“模式导出pdf时，一并导出全文+标注，并且相应的标注被高亮？

- 目前导出pdf在文件里看到的效果就是仅有标注，如下图：

![QQ图片20210524091022](https://user-images.githubusercontent.com/84690634/119283508-e7b93b00-bc6f-11eb-8960-e31c60d58fcb.png)

- 目前导出pdf时是否支持达到网页端阅读模式的效果（全文+高亮标注），如下图：

![QQ图片20210524091208](https://user-images.githubusercontent.com/84690634/119283613-27802280-bc70-11eb-84fe-e843e8251458.png)

**Comment by Kenshin** [comment]
嗨，目前 全文 + 标注是需要导出两个文件的，如果你没有做某些设置的话，有可能是一个文件。

全文 + 标注的两个文件分别是：

1. 全文（带标注），类似你第二个截图
2. 仅标签

如果你只是需要带标注的全文，选择 **全文** 即可。

***

这几个名称确实有些歧义，补丁版（即将发布）已经解决了这个问题

![image](https://user-images.githubusercontent.com/81074/119288611-77181b80-bc7b-11eb-9a35-80dd2861152c.png)

关于如何使用 全文 + 标注，可以看 https://github.com/Kenshin/simpread/discussions/2147 教程。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Phoebeart** [comment]
好的谢谢~
