### ISSUE TITLE
A JavaScript error occurred in the main process主进程中发生JavaScript错误

### ISSUE THREAD

**Issue by kunpeng9** [Kenshin/simpread#2239]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
win10
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
Chrome  版本90.0.4430.85（正式版本）（64位）
- 简悦版本 **2.0.0**
当前版本1.0.1
- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
报错弹窗
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/44609485/119291283-c6147f80-bc80-11eb-81c8-6acd1a619d3b.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Joel2561** [comment]
同步助手启动时报错，无法获得端口号问题，部分原因是因为重复启动同步助手。一般重新启动电脑即可解决，不行的话可以在任务管理器中找一找有没有两个进程，关掉重启即可。如果反复发生，考虑关闭同步助手的“随系统启动”选项，然后在系统里设置开机启动（win+R输入%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup将简悦拖动至此）。

**Comment by Kenshin** [comment]
@kunpeng9 

嗨，请按照 @Joel2561 提示的操作即可解决。

接下来我会修复这个 7026 端口占用后的提示信息。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，已重新开启此 Issues

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
## 简悦 2.2.0

> 首先，先说声抱歉，没想到 **2.2.0** 版竟然过了这么久才跟大家见面。不过，好在还是来了。
>
> **2.2.0** 的稍后读并不会像其它稍后读一样：**导入 → 收藏** 即可。它会帮你探索稍后读背后承载的信息之间的关联性，通过这些关联性让 **「你方便将这些信息内化为知识」**。
>
> 所以，**2.2.0** 的简悦有个新口号：**做你知识管理的粘合剂**。
>
> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 单例运行

当同时运行多个同步助手时，仅确保只有一个运行成功，就可以解决 7026 端口因多开同步助手而导致的占用问题。

同时也修复了开机无法自启动的问题。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
