### ISSUE TITLE
Boost文档图片无法显示

### ISSUE THREAD

**Issue by kenkangxgwe** [Kenshin/simpread#224]
http://www.boost.org/doc/libs/1_66_0/libs/graph/doc/quick_tour.html
网站上的图片是gif，但是会被归类为`simpread-hidden`，如果取消`display: none`, 则会一直处于加载状态

**Comment by Kenshin** [comment]
感谢反馈~

Boost 并未加入到适配列表，是临时阅读模式吧，的确有这个问题，我先记 Bug ！

**Comment by Kenshin** [comment]
此问题应该解决了，我关闭此 issue 了~
