### ISSUE TITLE
导出PDF，代码超长会截取

### ISSUE THREAD

**Issue by szxypi** [Kenshin/simpread#2243]
这是导出pdf截图
![image](https://user-images.githubusercontent.com/42827145/119309378-cc1a5880-bca0-11eb-9007-ca941317f837.png)
这是解析的网页截图
![image](https://user-images.githubusercontent.com/42827145/119309458-eb18ea80-bca0-11eb-8004-f63fe91eff55.png)

网页宽度可能和pdf不一样，pdf代码被截断了，希望自动换行显示

**Comment by Kenshin** [comment]
emmm... 确实存在这个情况。

我先记录下，看看后续如何优化。

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by Kenshin** [comment]
嗨，简悦 [2.2.0.520](https://github.com/Kenshin/simpread/issues/2158) 已经发布，已重新开启此 Issues

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

**Comment by Kenshin** [comment]
> 以下是 2.2.0 的相关介绍，请让我重新介绍一次。

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/categories/服务)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 后续

> Edge 版预计本周提交，且直接为 **[2.2.0.520](http://ksria.com/simpread/changelog.html#2.2.0)**

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
