### ISSUE TITLE
onenote

### ISSUE THREAD

**Issue by 406Feng** [Kenshin/simpread#2245]

**Comment by 406Feng** [comment]
onenote频繁授权失效，而重新授权却总是失败，onenote端显示已经授权，简悦端显示授权失败

**Comment by Kenshin** [comment]
请问是什么版本？2.2.0 已经解决了这个问题。

不过，2.2.0.520 正在审核中，建议升级到 520 这个版本。

**Comment by Kenshin** [comment]
> onenote端显示已经授权

是指什么？

**Comment by Kenshin** [comment]
抱歉，因为这次 **Webstore 审核的超级快**，导致 2.2.0 相关的内容没有匹配，所以这两天会超级忙，因为 Github Issues 的机制导致有可能 **[无法看到置顶信息](https://github.com/Kenshin/simpread/issues/2158)**，所以我暂时把这个 issues 先做了关闭处理，等这个 Issues 完毕后，会恢复它。

**Comment by 406Feng** [comment]
你好，问题的原因貌似是没给插件读取权限，用wiki的时候把它关掉了，给了权限授权就正常了

Kenshin Wang ***@***.***> 于2021年5月25日周二 上午9:02写道：

**Comment by Kenshin** [comment]
okay 

PS：wiki的问题，你可以使用黑名单的方式 https://github.com/Kenshin/simpread/issues/2163

另外 520 这个版本已经解决了 https://github.com/Kenshin/simpread/issues/2158 提到的全部问题，目前正在审核中。

审核通过后，会自动更新，且本次为静默更新。
