### ISSUE TITLE
开放平台无法登录

### ISSUE THREAD

**Issue by AmintaCCCP** [Kenshin/simpread#2247]
之前成功登录过一次，后来再也不能登录了。
坚果云和dropbox都试过，配置文件同步都没问题，就是登录不了。
使用UID和short都不行。
之前记录过token，用那个token绑定telegram bot和快捷指令也都用不了

**Comment by luc99hen** [comment]
开放平台登录，需要翻墙

**Comment by Kenshin** [comment]
嗨，关于你的问题已经在 https://t.me/simpread/180 说明了。

另外，有条件的话，请订阅 https://t.me/simpread 或者它的 [RSS 版](https://simpread.pro/subscribe)

**Comment by Kenshin** [comment]
没有问题的话，我关闭这个 Issues 了

**Comment by AmintaCCCP** [comment]
按照说明检查了一遍，仍然不行
> API 失败的情况
> 如果你在使用 API 导致失败的话，请做以下修改：

> 1. 请不要使用 Dropbox 作为同步盘
> 2. 请使用严格的目录结构 <支持的网盘>/SimpRead/simpread_config.json 👉 https://simpread.pro/api/#/README?id=如何开通
> 3. 如果无法访问 https://simpread.pro/developer 请确保网络畅通即可。
![image](https://user-images.githubusercontent.com/74942183/119458011-e15db880-bd6e-11eb-9b38-66c94368f613.png)
![image](https://user-images.githubusercontent.com/74942183/119458097-f8040f80-bd6e-11eb-8f65-3064b71c59c6.png)
![image](https://user-images.githubusercontent.com/74942183/119458164-08b48580-bd6f-11eb-9aa0-c05c93cb69ba.png)

**Comment by Kenshin** [comment]
@AmintaCCCP 

嗨，把你 UID 发到我的邮箱里面，我尽快回复你。或者在 TG 找我私聊也行。

**Comment by AmintaCCCP** [comment]
> @AmintaCCCP
> 
> 嗨，把你 UID 发到我的邮箱里面，�我尽快回复你。或者在 TG 找我私聊也行。

已经发了
