### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by edonyM** [Kenshin/simpread#2248]
发生问题的地址: <https://wiki.mbalib.com/wiki/%E9%B2%8D%E5%BE%B7%E9%87%8C%E4%BA%9A>

**Comment by Kenshin** [comment]
嗨，我感觉还可以啊

![image](https://user-images.githubusercontent.com/81074/119492944-3b23aa00-bd92-11eb-8f4f-1e8d57d17be6.png)

**Comment by edonyM** [comment]
额，是我浏览器的问题，我重启了一下chrome就可以了

**Comment by Kenshin** [comment]
okay 搞定就好。
