### ISSUE TITLE
域名匹配问题

### ISSUE THREAD

**Issue by flyisland** [Kenshin/simpread#225]
例如针对网页 https://www.infoq.com/news/2018/01/Kotlin1718 ，我在临时模式中启动站点编辑器，域名写为 https://www.infoq.com/news/ ，提示说域名不匹配！请问为何这样会是不匹配？

![image](https://user-images.githubusercontent.com/547085/35367414-2482fa3c-01b9-11e8-960d-56538e021ac8.png)

**Comment by Kenshin** [comment]
你应该输入 `ttps://www.infoq.com/news/*/*/*` 或者 `ttps://www.infoq.com/news/**/*`

关于 url 的适配可以看 #215 的讨论，另外建议使用  [minimatch](https://github.com/isaacs/minimatch)  的方案，非`*`方案（之前的方案）都是为了向上兼容~

希望能帮到你~

**Comment by flyisland** [comment]
@Kenshin 多谢，知道了，问题解决！

**Comment by Kenshin** [comment]
搞定就好～
