### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by ermclwyt** [Kenshin/simpread#2250]
发生问题的地址: <https://yeasy.gitbook.io/docker_practice/compose>

**Comment by binsee** [comment]
这个页面提示获取内容异常，是因为页面正文内容过短（低于100字），因此疑似获取失败才提示获取内容异常。
但测试中，实际上已经正确提取了正文并予以显示，因此不需要额外进行适配，对于错误提示，忽略即可。

**Comment by Kenshin** [comment]
谢谢 @binsee 的解释。

@ermclwyt  正是如此。

没问题的话，我关闭此 issues 了。
