### ISSUE TITLE
Webhook 的 {{content}} 占位符未被正确替换

### ISSUE THREAD

**Issue by chenyi1989** [Kenshin/simpread#2252]
配置选项为：
{"name":"FlomoWebhook","url":"https://flomoapp.com/xxx/xxxx/1xxxxxxxxxxxxxxxxx/","type":"POST","headers":{"Content-Type":"application/json"},"fmt":"html","body":{"content":"#收集\n desc3{{desc}}note{{note}}content{{content}}\n------《{{title}}》{{url}}"}}

通过这里的按钮导出：
![image](https://user-images.githubusercontent.com/3119990/119576770-f75d8e80-bdeb-11eb-8b06-8d7a433643cc.png)

导出内容效果为：
![image](https://user-images.githubusercontent.com/3119990/119576862-1fe58880-bdec-11eb-948b-5b03f8937db9.png)

期望其中{{content}}占位符被选中文字内容替换。

**Comment by Kenshin** [comment]
嗨，这个情况不存在，是你看错了或设置错了。

下面是官方例子

```
{"name":"Webhook2Pocket","![image](https://user-images.githubusercontent.com/81074/119588408-511d8300-be03-11eb-9c55-86082e0ae351.png)":"https://maker.ifttt.com/trigger/simpread_webhook/with/key/******","type":"POST","headers":{"Content-Type":"application/json"},"body":{"value1":"{{url}}"}}
```

关于这块的内容，我更新了下文档说明

![image](https://user-images.githubusercontent.com/81074/119588394-49f67500-be03-11eb-8f4a-8fd1c2a13040.png)


细节 [看这里](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=webhook)

**Comment by Kenshin** [comment]
关于这块的转换，你可以看下面的片段代码，希望对你有所帮助。

![image](https://user-images.githubusercontent.com/81074/119589383-3fd57600-be05-11eb-9cb5-9d34d8fee344.png)

**Comment by chenyi1989** [comment]
你的body的值是通过JSON字段取出来的吧？{{content}}前后带英文引号，不会导致JSON格式错误解不了吗？

我的body改成这样以后，点分享就没反应了，我猜测哪里报错了。
"body":{"content":"#收集\note{{note}}content"{{content}}"\n------《{{title}}》{{url}}"}

**Comment by Kenshin** [comment]
应该没问题的，今天稍微有些忙，后续（会尽快）会确认下。

之前有用户使用过 在 Webhooks 里面写 Notion API 都可以成功的。

**Comment by binsee** [comment]
> 你的body的值是通过JSON字段取出来的吧？{{content}}前后带英文引号，不会导致JSON格式错误解不了吗？
> 
> 我的body改成这样以后，点分享就没反应了，我猜测哪里报错了。
> "body":{"content":"#收集\note{{note}}content"{{content}}"\n------《{{title}}》{{url}}"}


json字符串内值中的 `"`需要转义为 `\"`

即：

 `"body":{"content":"#收集\nnote{{note}}content\"{{content}}\"\n------《{{title}}》{{url}}"}`

注意`\note`应该是`\nnote`

**Comment by chenyi1989** [comment]
试过啦，这是现在的配置，下图是效果。
{"name":"FlomoWebhook","url":"https://flomoapp.com/HIDDEN/","type":"POST","headers":{"Content-Type":"application/json"},"fmt":"html","body":{"content":"#收集\ncontent:\"{{content}}\"\n------《{{title}}》{{url}}"}}

![image](https://user-images.githubusercontent.com/3119990/119642546-6a4b2180-be4d-11eb-9e6e-ba3d8e246eb7.png)

**Comment by chenyi1989** [comment]
原样复制你的body内容，这是效果。
![image](https://user-images.githubusercontent.com/3119990/119642875-c2822380-be4d-11eb-992d-a8a2e2f1e1f7.png)

**Comment by Kenshin** [comment]
@chenyi1989 

嗨，抱歉，今天太忙了，一直在处理各种事情，明天我给你回复。

**Comment by binsee** [comment]
@Kenshin 已经通过调试跟踪，是代码bug造成的

- 调试截图

![image](https://user-images.githubusercontent.com/5285894/119660495-e8b1be80-be61-11eb-879d-8f13eba3a13a.png)

- 调试中的代码

```js
b && (d.headers = b),
v = JSON.stringify(v), 
//将json对象序列化后， v.conntent对应的字符串中的英文引号 `"` 被转码为两个字符`\"`，而在正则中 `\"` 需要转码为 `\\"`
v = v.replace(/{{url}}/gi, m).replace(/{{title}}/gi, n).replace(/{{desc}}/gi, o)
  .replace(/{{note}}/gi, g.storage.unread.note || "").replace(/{{tags}}/gi, u)
  .replace(/"{{content}}"/gi, JSON.stringify(t)),
b ? v && (d.data = v) : v && (d.data = JSON.parse(v));
var r = (new e).Render({
```

### 修复方式

源码：
![image](https://user-images.githubusercontent.com/81074/119589383-3fd57600-be05-11eb-9cb5-9d34d8fee344.png)

```js
.replace(/"{{content}}"/gi, JSON.stringify(result));
// 修改为下面的即可
.replace(/\\"{{content}}\\"/gi, JSON.stringify(result));
```

**Comment by Kenshin** [comment]
@binsee 

emmm... 明天抽时间试试。
我之前做过测试，但确实没做过这么「复杂」的 Body 形式。

不过，即便有问题的话，也可以绕过去，因为基础方式没问题，所以可以加个中间 service 做中转。

**Comment by Kenshin** [comment]
@chenyi1989 

嗨，我使用 Webhooks + 定制化导出，做了一个可以定制化 flomo 模板的 API，你可以直接调用这个 API，教程 [在这里](https://github.com/Kenshin/simpread/discussions/2275)

@binsee 

之前那个错误也不算是错误，只是我没有想到，`body` 中可以有复杂的结构，解决方案是使用第三方

***

这个例子写的可能有些粗，等有时间的时候，我再细化 @chenyi1989 按照教程，能否使用？

**Comment by chenyi1989** [comment]
{{content}}占位符是没了，但是内容还是没带过来。

配置
![image](https://user-images.githubusercontent.com/3119990/120089229-e930aa80-c12a-11eb-9d5c-1039df92fcca.png)
原文
![image](https://user-images.githubusercontent.com/3119990/120089237-f64d9980-c12a-11eb-8a63-25ed568e9a4d.png)
效果
![image](https://user-images.githubusercontent.com/3119990/120089241-ff3e6b00-c12a-11eb-94da-6fa07cc9249f.png)

**Comment by Kenshin** [comment]
@chenyi1989 

API 是没问题的，我直接测试过，**你给出的信息太少，我没法判断**，大概率还是因配置有误造成的。

你可以这样测试：打开截图中的这个标注的标注卡，然后在下方找到发送方式，通过此方式发送，看看能否成功？

![image](https://user-images.githubusercontent.com/81074/120090424-0cf8ee00-c135-11eb-8134-ec74d58f1c02.png)

如果没问题的话，说明 flomo 方面的配置 OK，估计你你选择了全文造成的，改为下图：

![image](https://user-images.githubusercontent.com/81074/120090453-3ca7f600-c135-11eb-9f70-0abe3bb38772.png)

**Comment by chenyi1989** [comment]
打开截图中的这个标注的标注卡，然后在下方找到发送方式，通过此方式发送，看看能否成功？
------
你提供的操作方式还是一样的结果，批注内容没被带到flomo里。
![image](https://user-images.githubusercontent.com/3119990/120090650-bab8cc80-c136-11eb-83dd-6063181c7077.png)

**Comment by Kenshin** [comment]
我刚又测试过了，没问题。

不把你的配置文件发给我（我的邮箱在 Github 能找到）
附上当前这个 Issues id，然后告诉在这里告诉我。

最近太忙，每天都 100+ 邮件，没法 check，只能这么办。

**Comment by chenyi1989** [comment]
> 我刚又测试过了，没问题。
> 
> 不把你的配置文件发给我（我的邮箱在 Github 能找到）
> 附上当前这个 Issues id，然后告诉在这里告诉我。
> 
> 最近太忙，每天都 100+ 邮件，没法 check，只能这么办。

done，请查收。

**Comment by Kenshin** [comment]
嗨，我 check 了你的配置文件，是 **配置错误** 造成的，

请仔细看 https://github.com/Kenshin/simpread/discussions/2275

![image](https://user-images.githubusercontent.com/81074/120091781-d1642100-c140-11eb-82b5-d3a9def85989.png)

这个节点对应的说明，模板如何设置，结构如何写等。

![image](https://user-images.githubusercontent.com/81074/120091827-12f4cc00-c141-11eb-8181-f66317f9c0bb.png)

> 你的配置文件，截图中的内容，显然是错误的

![image](https://user-images.githubusercontent.com/81074/120091806-f2c50d00-c140-11eb-82d7-7d94d9fa25ea.png)

**Comment by chenyi1989** [comment]
1. 我看了一下我的配置，“当导出单条标注时，是否使用单条的定制化模板？”这个选项是关闭的，我不清楚为什么一个关闭的选项里的错误配置会影响到另一个配置的结果。
![image](https://user-images.githubusercontent.com/3119990/120100793-481b1180-c175-11eb-9777-57bbc1b230b6.png)
2. 我阅读了https://github.com/Kenshin/simpread/discussions/2275文档的内容，我是应该把“定制化 Markdown 配置”里提到的两个配置项按照教程内容一模一样填上？按照我的理解，Webhook配置里应该已经包含了我需要定制输出的格式了，我不清楚这两个配置的目的是什么，所以没对应的填上。
3. 我尝试了按照上述说明填上了对应配置，点击分享弹出下面这个提示框，就没反应了：
![image](https://user-images.githubusercontent.com/3119990/120101191-5ec26800-c177-11eb-988c-d8a0c106f214.png)

**Comment by Kenshin** [comment]
> 我不清楚为什么一个关闭的选项里的错误配置会影响到另一个配置的结果。

因为这个教程需要使用两个功能，教程中已经说明了。

PS：教程 ≠ 文档，我只在教程中这么写，如果要看为什么这么写的话，请看文档。

***

另外，我有你的配置文件，我来做下吧，然后把配置文件给你。（估计得明天了，今天还有些其它事情要处理。

**Comment by Kenshin** [comment]
emmm

我把配置文件给你发过去了，没问题的话，回复我下~

**Comment by chenyi1989** [comment]
用你提供的配置文件可以用啦，感谢

**Comment by chenyi1989** [comment]
![image](https://user-images.githubusercontent.com/3119990/120131946-04b7b600-c1fc-11eb-9d90-2c105fe29c25.png)
在配置没有改变的情况下，导出到flomo不成功了。中转的服务不稳定？什么时候能提供一个稳定可用的版本呢？

**Comment by Kenshin** [comment]
@chenyi1989 

需要可以正常访问 中转 API 才行，这不是我能决定的，并不是中转服务有问题，而是网络。

**Comment by chenyi1989** [comment]
> @chenyi1989
> 
> 需要可以正常访问 中转 API 才行，这不是我能决定的，并不是中转服务有问题，而是网络。

OK我了解了，就是目前没办法保证在国内正常网络下访问服务的稳定，看起来也没有意愿解决这个问题。

**Comment by Kenshin** [comment]
嗨，其实你可以不用这么理解。

简悦的用户都是通过 Webstore 访问获取的，所以这个问题也不会存在。

另外，由于某些原因，或许在 8月份 会好些。

最后，从这个 Issues 来看，本就属于「编外」功能，只是我觉得你说的有道理，所以才开了这个服务。

希望借此给一些动手能力强的用户提供一种更个性化的服务。

**Comment by chenyi1989** [comment]
> 嗨，其实你可以不用这么理解。
> 
> 简悦的用户都是通过 Webstore 访问获取的，所以这个问题也不会存在。
> 
> 另外，由于某些原因，或许在 8月份 会好些。
> 
> 最后，从这个 Issues 来看，本就属于「编外」功能，只是我觉得你说的有道理，所以才开了这个服务。
> 
> 希望借此给一些动手能力强的用户提供一种更个性化的服务。

如果是这样，在下一版本修复现有Webhook配置存在的问题，可以不需要中转直接访问flomo服务器就行，也就不再需要中转服务了。

**Comment by Kenshin** [comment]
> 如果是这样，在下一版本修复现有Webhook配置存在的问题，可以不需要中转直接访问flomo服务器就行，也就不再需要中转服务了。

从某种角度上说，之前的那个 `Bug` 也不算是，我还再考虑 Webhooks 的通用性问题，但如果修复的话，自然是不需要这么做的。

但一般来说，下个补丁版发布肯定不会在 6月 内。

***

PS：我看你挺好问的，这点挺好。（所以我才以为可能算同行，但看来应该不是，否则不能出现配置错的问题。
