### ISSUE TITLE
聚焦模式下Esc按键无效的问题（疑似）

### ISSUE THREAD

**Issue by leicancun** [Kenshin/simpread#2258]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

---

![image](https://user-images.githubusercontent.com/58691431/119603462-d2830e80-be1f-11eb-98c9-6c8dcff41d8c.png)

功能已启用，目前聚焦模式无效，阅读模式正常，已确认在无痕模式下仅启用简悦的情况下问题依旧存在，排除了按键干扰的可能

问题从2.2.0出现，更新到2.2.0.520版本之后聚焦模式下无法通过esc键退出的问题依旧没有修复，我看到并没有人单独对这个问题提出，特来标记一下

**Comment by Kenshin** [comment]
奇怪... 我可以使用。

你都设置了什么？（方便把配置文件通过邮件的方式给我吗？Github 上能找到我的邮箱地址。

**Comment by leicancun** [comment]
> 奇怪... 我可以使用。
> 
> 你都设置了什么？（方便把配置文件通过邮件的方式给我吗？Github 上能找到我的邮箱地址。

,,,晚了一步,我刚刚重置了🤣重置后目前没有再次出现

**Comment by Kenshin** [comment]
估计是隐性 Bug...

我先关闭这个 issues 吧，有需要你再重开它。
