### ISSUE TITLE
阅读模式解析部分错误

### ISSUE THREAD

**Issue by ImSingee** [Kenshin/simpread#2259]
https://www.jianshu.com/p/1f3ec2f00b03

对于「复制代码」按钮样式有异常（我自己是在暗色模式下，不确定亮色模式下效果）

**Comment by Kenshin** [comment]
嗨，我没有发现「复制按钮」 😅 

![image](https://user-images.githubusercontent.com/81074/119624897-31568100-be3c-11eb-9c4d-71022ad5754f.png)

**Comment by ImSingee** [comment]
![image](https://user-images.githubusercontent.com/11208082/119625721-16384100-be3d-11eb-9ee4-18dd6b890fb0.png)

这……

**Comment by Kenshin** [comment]
奇怪...

你的新版本？还是老用户？

选项页 → 站点管理 → 更新适配列表，看看能否解决？

***

抱歉，2.2.0 首发，稍微有点忙。

**Comment by ImSingee** [comment]
老用户更新了最新版，适配列表也更新了…

我明天看看会不会是其他扩展的冲突问题

**Comment by binsee** [comment]
关闭其他黑暗模式的扩展（如Dark Reader），改用 `黑鸢`这个主题色会复现此问题

![image](https://user-images.githubusercontent.com/5285894/119667896-44cc1100-be69-11eb-85c5-5e9183bd9f50.png)

**Comment by ImSingee** [comment]
@binsee  @Kenshin 

![image](https://user-images.githubusercontent.com/11208082/119668522-d5a2ec80-be69-11eb-9b4e-a87dc02c928a.png)

出现了一件很有意思的事情，刚才我直接点进了这个链接没出现那个复制按钮，再刷新下复制按钮就出来了

而且所有主题也都有这个按钮

**Comment by binsee** [comment]
添加以下内容到简书的隐藏列表即可，之后会提交pr

```js
[[[$('sr-rd-content button[aria-label="复制代码"]')]]]
```

临时操作步骤：
在阅读模式 按 `sr  se`，在弹出的窗口按图示填写，保存后刷新页面即可
![image](https://user-images.githubusercontent.com/5285894/119671417-54008e00-be6c-11eb-9fc4-3e08a2e69da4.png)

**Comment by Kenshin** [comment]
@binsee 

🙏🏻

**Comment by ImSingee** [comment]
@binsee 可以了，非常感谢！！

**Comment by Kenshin** [comment]
嗨，这个站的适配规则已经更新，请使用下图的方式手动更新。

![image](https://user-images.githubusercontent.com/81074/120067368-c8763f80-c0ad-11eb-8706-3b0e6798641d.png)

我关闭这个 issues 了。
