### ISSUE TITLE
印象笔记授权页面一直处于loading中

### ISSUE THREAD

**Issue by HermanHwang** [Kenshin/simpread#2265]
我去印象笔记授权中心那边查看，查看到已经是授权成功的，但是简约这边一直提示是未授权。
![image](https://user-images.githubusercontent.com/16135432/119760937-83031800-bedd-11eb-9a98-91219e437fe9.png)

**Comment by HermanHwang** [comment]
![image](https://user-images.githubusercontent.com/16135432/119761034-ac23a880-bedd-11eb-9357-c23a97941870.png)
印象笔记那边已经是授权过的了

**Comment by Kenshin** [comment]
嗨，看看是不是这个问题导致的 https://github.com/Kenshin/simpread/discussions/1567

PS：不建议使用印象笔记，失败率较高（不是简悦的问题。

**Comment by HermanHwang** [comment]
好吧，看来是印象笔记的问题。
