### ISSUE TITLE
Edge中简悦版本还是2.1.0 望升级

### ISSUE THREAD

**Issue by Ganzhenghao** [Kenshin/simpread#2269]
Edge中简悦版本还是2.1.0
 直接下载crx文件安装 每次打开edge会弹出提示框
 谷歌商店不翻墙进不去 
 着实麻烦  希望升级edge商店的版本

**Comment by Kenshin** [comment]
嗨，抱歉，因为精力有限，我尽量在本周提交到 Edge 通过后我会在这里通知你。

**Comment by drrrMikado** [comment]
Edge 已经审核通过了

**Comment by Kenshin** [comment]
嗨，抱歉忘记关闭这个 Issues 了，Edge 已经发布了~
