### ISSUE TITLE
BBC 中文网改版适配

### ISSUE THREAD

**Issue by jeopsh** [Kenshin/simpread#227]
http://www.bbc.com

**Comment by Kenshin** [comment]
可以通过站点编辑器自行修改。

**Comment by Kenshin** [comment]
新增了一批新站，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

除此之外，还包括一批「不存在」的网站，如上述提及的，具体操作方式请看下图
![image](https://user-images.githubusercontent.com/81074/40884334-501fe6c8-6744-11e8-8d39-3ffa6ed2e41a.png)
