### ISSUE TITLE
微信文章代码显示问题

### ISSUE THREAD

**Issue by itscj1014** [Kenshin/simpread#2272]
这是原来的代码样式，分行清晰：
![image](https://user-images.githubusercontent.com/42897738/119917639-865bd980-bf99-11eb-9345-cf1735ad4c20.png)
这是阅读模式下的代码样式，全部缩到一行了：
![1111111](https://user-images.githubusercontent.com/42897738/119917902-03874e80-bf9a-11eb-9895-731ae38b5112.png)

原文链接：https://mp.weixin.qq.com/s/20t_UtNNwXfynbzxpi7p2Q
希望修复这个代码显示w问题

**Comment by binsee** [comment]
是否有开启 代码增强 这个插件？我前两天在其他站点有发现这个插件会导致此问题。
如果开启了此插件，先禁用看看

**Comment by Kenshin** [comment]
嗨，请使用 @binsee 提供的方案。

这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
