### ISSUE TITLE
高级账户兑换码格式错误问题！

### ISSUE THREAD

**Issue by glongzh** [Kenshin/simpread#2274]
前几天买了高级账号，收到兑换码的邮件（吐槽下，邮件内容一大堆，找兑换码找了半天没找到…原来是在“其他注意事项”的第3点一行小字说：兑换码为问卷提交时填写的，也是 付款时的订单号 202**** 开始的 最后六位，请勿输入错误。。。既然是兑换码邮件，就不能将兑换码写得明显一点？），就是订单号的后6位（即6位数字），但绑定的时候仍然提示“授权码格式错误”。。。到底是啥问题，邮件回复了好几天也没有回复…
![image](https://user-images.githubusercontent.com/1331163/119974756-a6b28500-bfe7-11eb-97e1-c08b2cbbd00d.png)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/119975154-158fde00-bfe8-11eb-83f5-0162189c73d5.png)


进入 https://simpread.pro/code 输入 六位兑换码，得到 License

**Comment by Kenshin** [comment]
抱歉，2.2 发布后，我需要处理各种事情，所以 Email 经常每天都 100+ ，所以我只能以 issues  为主。

而且 Issues 也是唯一 QA 平台

**Comment by glongzh** [comment]
建议将这行字和链接突出显示…毕竟邮件里链接太多了
