### ISSUE TITLE
新浪博客适配

### ISSUE THREAD

**Issue by jeopsh** [Kenshin/simpread#228]
http://blog.sina.com.cn

**Comment by Kenshin** [comment]
感谢反馈，适配后会通知你。

**Comment by Kenshin** [comment]
你好，新浪博客已适配，但目前图片显示有问题，只能下个版本解决此问题  😭 

请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
