### ISSUE TITLE
配置文件遗失且找回超过三次,已发送邮件,望尽快回复

### ISSUE THREAD

**Issue by sche11** [Kenshin/simpread#2280]

**Comment by Kenshin** [comment]
嗨，这次可以了，不用删 Issues 了。  😅 

首先，2.1 开始在绑定时，会自动下载配置文件。
其次，https://simpread.pro/reset 有三次找回机会。

正常来说，这些措施足够了。

***

因 2.2 发布窗空期，每天我要处理 50+ 左右的 Issues 100+ 的 Email，所以我不可能 100% 一一及时回复。

***

你需要重新发邮件给我，并且这样做：

1. 附上这个 issues id **2280** （否则我可能会直接忽略
2. 附上购买凭证的截图，必须要包含购买时的邮箱地址 或 在少数派购买时的订单截图详细信息。
3. 必须要使用第二条对应的邮箱给我邮件。

因今天是周末，我在处理简悦的一些合作事情，所以即便核对成功，也无法兑换，我会在周一做这个事情，如周二 10点前仍没有收到我的邮件，请再次告知于我。

因为我实在是没时间，上述内容缺少的话，我不会回复你邮件了，实在太忙了，请见谅。 😭 

***

我先关闭这个 issues  有任何问题可以随时找我，Issues 是我能回复最快的渠道。

🙏

**Comment by sche11** [comment]
周二10点，没有收到邮件
