### ISSUE TITLE
Vivaldi浏览器中，设置简悦的浏览器快捷键后，使用快捷键不触发

### ISSUE THREAD

**Issue by o-ut-man** [Kenshin/simpread#2284]
![image](https://user-images.githubusercontent.com/34265164/120064793-af1ac680-c0a0-11eb-80ac-a4ec3c575bdf.png)

**Comment by Kenshin** [comment]
你的意思是，设置完后不生效？

我暂时用不了 Vivaldi ，不知道能否则在 Chrome 中试试。

**Comment by o-ut-man** [comment]
> 你的意思是，设置完后不生效？
> 
> 我暂时用不了 Vivaldi ，不知道能否则在 Chrome 中试试。

恩，设置完快捷键后，快捷键不生效。

我这也没有Chrome， 不过我用了Chromium内核的Edge，是可以正常使用的。
在Vivaldi浏览器中，快捷键要设置成全局范围就会生效，只设置浏览器范围就不生效。
其他拓展的快捷键是可以正常生效的。

**Comment by Kenshin** [comment]
> 在Vivaldi浏览器中，快捷键要设置成全局范围就会生效，只设置浏览器范围就不生效。

在 Vivaldi 改成全局就可以了？

**Comment by o-ut-man** [comment]
> > 在Vivaldi浏览器中，快捷键要设置成全局范围就会生效，只设置浏览器范围就不生效。
> 
> 在 Vivaldi 改成全局就可以了？

对...

**Comment by Kenshin** [comment]
Vivaldi 好像对 Chromium 修改的最严重，印象中之前有个类似的问题，但肯定不是快捷键的问题。

既然这样的话，我关闭这个 Issues 了。
