### ISSUE TITLE
微信小程序文档

### ISSUE THREAD

**Issue by WeihanLi** [Kenshin/simpread#229]
https://mp.weixin.qq.com/debug/wxadoc/dev/api/custommsg/receive.html#%E8%BF%9B%E5%85%A5%E4%BC%9A%E8%AF%9D%E4%BA%8B%E4%BB%B6

**Comment by Kenshin** [comment]
你想说什么？

**Comment by WeihanLi** [comment]
希望更好的适配

![image](https://user-images.githubusercontent.com/7604648/35712714-6f1b9f54-07fe-11e8-8f3e-27c3014a43f1.png)

**Comment by Kenshin** [comment]
okay，没问题，不过，刚刚试用了下 临时阅读模式，也是完美支持的。
适配后会通过此 issues 通知你~

**Comment by Kenshin** [comment]
你好，久等了，新增加了 `developers.weixin.qq.com`，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

**Comment by WeihanLi** [comment]
:thumbsup::thumbsup::thumbsup:
