### ISSUE TITLE
如何在稍后读中给文章添加标签？

### ISSUE THREAD

**Issue by liufzhq** [Kenshin/simpread#2291]
如题，当我把文章保存到稍后读以后，我找不到方法给保存的文章加上标签。是不是需要按照什么插件？我使用的是chrome浏览器，mac系统。

**Comment by Kenshin** [comment]
嗨，很多地方都可以。

稍后读，标注侧栏等等地方，如下图：

![image](https://user-images.githubusercontent.com/81074/120150632-dcd94a00-c21d-11eb-8568-15de58da800f.png)

打开后会有下面的界面

![image](https://user-images.githubusercontent.com/81074/120152003-88cf6500-c21f-11eb-97c8-fa53a94cffe0.png)

按照提示填写即可。
