### ISSUE TITLE
同步助手的Linux版本

### ISSUE THREAD

**Issue by blinderjay** [Kenshin/simpread#2293]
- 请问现在还有Linux版本的同步助手可用吗？
- Linux electron 兼容性不是很好，而且使用Linux 的或多或少有点性能癖，建议对于Linux 版本将其设置为 systemd 服务，然后在浏览器浏览dashboard 即可，或者类似dropbox 界面仅仅提供安装和引导，进程并不常驻

期待作者的作品，工具流加油

**Comment by Kenshin** [comment]
嗨，抱歉，之前漏掉了这个 Issues 

目前暂时没有 Linux 版本，当然仍以 Electron 编译的版本为主。

谢谢对 Electron 的一些建议，确实很有帮助，我会重点考虑。

🙏

**Comment by jsfaint** [comment]
如果保持现有的实现，那么可以考虑不用electron做封装，直接用nodejs跑后端代码，前端交给系统里本身的浏览器执行。
毕竟要用简悦肯定会有Chrome或者Edge之类的浏览器

如果要适配更多的平台其实可以考虑用Go写后端，复用现有的前端代码，这样可以脱离nodejs环境。
Go静态编译是真香 😆

**Comment by ZmfCn** [comment]
催更linux版本呀 :pleading_face:

**Comment by Kenshin** [comment]
@ZmfCn 

嗨，别急，马上已在筹备中了。

**Comment by firstuanl** [comment]
催更 linux 非electron版呀

**Comment by Kenshin** [comment]
@firstuanl 

哈哈，别急，已经开始着手了。

**Comment by Zolyn** [comment]
请问Linux版现在进展如何了？

**Comment by Kenshin** [comment]
嗨，各位。

同步助手发布了命令行版本，可支持 Linux，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3704)，目前此版本为内测版，有任何问题请 [汇总到这里](https://github.com/Kenshin/simpread/discussions/3704#discussioncomment-2542653)。

PS：等正式版发布后，我还会通过这里告诉大家。

**Comment by firstuanl** [comment]
吹更firefox

**Comment by Kenshin** [comment]
嗨，[同步助手 · 命令行](https://github.com/Kenshin/simpread/discussions/3704) 版正式发布  🎉 

![Sync CLI](https://user-images.githubusercontent.com/81074/163512494-3c41c6c3-2158-49f8-9425-27637a3303c8.png)

在使用时如有问题，[请提 Issues](https://github.com/Kenshin/simpread/issues/3740)

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# Linux 版来啦

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
