### ISSUE TITLE
同步助手不会自启动（附临时解决方案）

### ISSUE THREAD

**Issue by BopSun** [Kenshin/simpread#2295]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Win10
- 浏览器版本 Chrome  91.0.4472.77（正式版本） （64 位）

- 简悦版本 2.2.0.520

**请描述你的问题**

简悦同步助手在启动项内但是不会自启动。建议程序文件名中不要使用中文或特殊字符。

**截图**

![image](https://user-images.githubusercontent.com/29018648/120245836-18692800-c2a1-11eb-840a-9952217e03a5.png)

**Comment by BopSun** [comment]
同步助手 1.0.1

手动启动后，启动列表状态见下图

![image](https://user-images.githubusercontent.com/29018648/120246001-89a8db00-c2a1-11eb-93e2-dcbe1f73cb6b.png)

**Comment by Kenshin** [comment]
谢谢反馈，同步助手的自启动功能有些问题，接下来会修改此问题。（其实是由另外一个问题导致的，就不在这里详细描述了）

我看你是 Windows 用户吧。如果是的话，最简单的解决方案：将 `.exe` 生成快捷方式然后直接放到自启动文件夹，即可解决。

Issues 里面有关于此的描述，你可以搜索下。

***

这个 Issues 先留着吧，等彻底解决了，我在 Close 它。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 自启动

修复了 Windows 、Mac 版无法自启动的问题，如仍无法自启动，Windows 用户 [看这里](https://github.com/Kenshin/simpread/discussions/2011)。

Linux 环境因为比较特殊，仅能 [使用此方式](https://github.com/Kenshin/simpread/discussions/3957) 实现。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
