### ISSUE TITLE
阅读模式代码块成一行，不换行

### ISSUE THREAD

**Issue by fghbv** [Kenshin/simpread#2297]
网站：https://www.javazhiyin.com/42360.html
![image](https://user-images.githubusercontent.com/65714132/120271086-3eacb900-c2dd-11eb-92d3-019074a5f71d.png)

**Comment by Kenshin** [comment]
嗨，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

你可以暂时禁用此插件。
