### ISSUE TITLE
我的站点更新成https了，求更新

### ISSUE THREAD

**Issue by DullSky** [Kenshin/simpread#230]
我的站点更新成https了，求更新，原网址：http://www.edaoe.com
新网址:https://www.edaoe.com，网站结构不变

**Comment by Kenshin** [comment]
感谢反馈，可以在站点编辑器自行修改。
官方适配源修改完毕后会通知你，请勿关闭此 issues 。

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
