### ISSUE TITLE
b站笔记的适配效果需优化

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2305]
当前b站笔记效果如下

![image](https://user-images.githubusercontent.com/5285894/120589739-e35d0100-c46b-11eb-8cdd-80f205640bf2.png)

存在问题：

1. 视频时间点的样式不好看（前缀`视频时间点：`）
2. 视频截图显示为小图，不利于阅读

**Comment by Kenshin** [comment]
嗨，已经更新到适配列表。
