### ISSUE TITLE
优化同步助手的错误提示

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2308]
目前通过社区渠道能见到的同步助手报错有以下几种：
- 同步助手重复启动导致重复监听TCP端口的报错
  ![image](https://user-images.githubusercontent.com/5285894/120616998-49598080-c48c-11eb-96e7-ea763ec6e7e9.png)

- 未安装 [pandoc](http://ksria.com/simpread/docs/#/Sync?id=pandoc) 导致的报错
  ![image](https://user-images.githubusercontent.com/5285894/120617150-6f7f2080-c48c-11eb-9c3e-048ac7059f3c.png)

我们需要改进，使用更友好的错误提示，并指引解决途径，避免用户一头雾水。

**Comment by Kenshin** [comment]
收到~ 

1.0.2 会包含这些提示，1.0.2 是扩展端之后 **最重要 / 优先级最高** 的事情。

**Comment by Kenshin** [comment]
嗨，此问题也 Fixed 掉了，因为使用了单例运行机制。😄
