### ISSUE TITLE
请去除【娟鼠】主题的代码文字阴影吧

### ISSUE THREAD

**Issue by DullSky** [Kenshin/simpread#231]
个人很喜欢娟鼠这个主题，同时也是一个coder，所以在阅读代码部分，实在是难以忍受text-shadow所造成的阴影，看起来像是重影，不利于快速阅读。如果这是官方的设计理念，也希望增加一个自定义css的功能，让大家可以自定义自己喜欢的样式，除此之外，代码行距颇高，寥寥数行代码已经一页了
![image](https://user-images.githubusercontent.com/15259698/35719037-3541de00-0822-11e8-8889-0d64469a2c74.png)

**Comment by Kenshin** [comment]
你可以进入 设置 → 自定义样式 → 代码段 → 去除「是否启用阴影」即可~

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
