### ISSUE TITLE
代码增强插件出错

### ISSUE THREAD

**Issue by liuyundu** [Kenshin/simpread#2310]
https://mp.weixin.qq.com/s/zW6X1CTnjdb3NX-d7nr6cw ，在浏览这个网站的时候，启动阅读模式，显示代码增强插件出错

**Comment by Kenshin** [comment]
嗨，这是 代码高亮插件 造成的问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

你可以暂时禁用此插件。
