### ISSUE TITLE
单页面应用的不同文章因页面url一样，无法加入稍后读

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2317]
问题站点： B站笔记 https://space.bilibili.com/v/note-list

站点属于单页面应用，笔记为动态加载后动态渲染，加载不同笔记不会切换url，只是渲染数据不同。

简悦稍后读以url作为key来避免将文章重复加入稍后读，而遇到此类单页面应用，就出现了问题。

我们需要解决方案。

目前设想如下：
在适配规则中，人为修正当前页面url，以确保写入稍后读的url不会重复。

**Comment by binsee** [comment]
b站笔记的已经通过修改适配规则解决，可见上边的PR

细节：

1. 原始页面url 
   `https://space.bilibili.com/v/note-list`
2. 进入笔记一的阅读模式，url改变为： 
   `https://space.bilibili.com/v/note-list#低头党福音！如何矫正脖颈使其正常弯曲【Mandell 博士】`
3. 进入笔记二的阅读模式，url改变为：
   `https://space.bilibili.com/v/note-list#先审后播会对日本动画带来什么影响？——日本动画走向世界的必经之路`

因进入阅读模式后，url与文章标题有关，不会重复，因此不同笔记加入稍后读时不会再重复

**Comment by Kenshin** [comment]
最新适配列表已更新，所以我关闭此 Issues ~
