### ISSUE TITLE
b站笔记导出到本地离线html，在「稍后读 - 阅读模式」 显示异常

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2319]
b站笔记加入到稍后读，自动导出离线html。在「稍后读 - 阅读模式」 中打开时，显示异常

1. 开头多了一行『视频连接：xxxx』，且a标签的href信息丢失
2. 视频时间戳的a标签，href信息丢失
3. 视频时间戳的a标签，时间戳文本丢失

- 显示截图：（左离线html，右稍后读）
  ![image](https://user-images.githubusercontent.com/5285894/120813318-5bb4e680-c580-11eb-9e7f-85ff3108ac68.png)

- 元素截图：（左离线html，右稍后读）
  ![image](https://user-images.githubusercontent.com/5285894/120813333-5eafd700-c580-11eb-848f-d7df8af7bfa4.png)

测试文件如下：
[先审后播会对日本动画带来什么影响？——日本动画走向世界的必经之路.zip](https://github.com/Kenshin/simpread/files/6598993/default.zip)

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题，下图

![image](https://user-images.githubusercontent.com/81074/120878944-68722280-c5f2-11eb-8d7c-4f4c552f7664.png)


***

确认下 `output` 文件夹里面的文件，举个例子：

1. 1234-test.html
2. test.html

`1234` 是你的稍后读 id，简悦会优先读取 `1234` 的 HTML，然后没有找到的话，会读标题一致的 HTML。

**Comment by binsee** [comment]
晚上回去测试

**Comment by Kenshin** [comment]
> 晚上回去测试

okay 🙏

**Comment by binsee** [comment]
仍然是此问题。
已经从稍后读中移除，并移除现有的output下文件，重新加入稍后读后，在稍后读中打开问题依旧。

![image](https://user-images.githubusercontent.com/5285894/120897257-be2ce600-c657-11eb-969f-a87d71f2473f.png)

**Comment by binsee** [comment]
有趣的是，我跟踪「稍后读-阅读模式」页面的流程，从同步助手读取到的正常，但进行二次处理渲染后，就出现问题

![image](https://user-images.githubusercontent.com/5285894/120897998-9c356280-c65b-11eb-8788-757048fb736d.png)
![image](https://user-images.githubusercontent.com/5285894/120898154-38f80000-c65c-11eb-925b-9e4110b9049c.png)

后续跟踪调试代码，确定如下问题：
![image](https://user-images.githubusercontent.com/5285894/120900809-99416e80-c669-11eb-9b53-6f875dfe7339.png)

调试视频如下：
https://user-images.githubusercontent.com/5285894/120900884-0bb24e80-c66a-11eb-965e-5765acd30bd3.mp4

**Comment by binsee** [comment]
嗨，我发现了问题所在。
『稍后读 - 阅读模式』中，即使读取的文件来自于同步助手从`output`目录下读取的离线文件，简悦也会按文章所属的站点适配规则，执行隐藏列表规则。
因为b站笔记的适配，隐藏列表中进行一些特殊处理，而在稍后读中无法获取到对应内容，导致页面呈现异常。

**Comment by Kenshin** [comment]
> 嗨，我发现了问题所在。
> 『稍后读 - 阅读模式』中，即使读取的文件来自于同步助手从`output`目录下读取的离线文件，简悦也会按文章所属的站点适配规则，执行隐藏列表规则。
> 因为b站笔记的适配，隐藏列表中进行一些特殊处理，而在稍后读中无法获取到对应内容，导致页面呈现异常。

竟然是这个问题导致... 也就是说我昨天测试的时候应该没有更新适配列表，所以无法重现？

另外，你在 #2327 应该已经 Fixed 了这个问题，是吧。

**Comment by binsee** [comment]
> 另外，你在 #2327 应该已经 Fixed 了这个问题，是吧。

是的，已经修复。

解决方法已另外记录至
https://github.com/Kenshin/simpread/discussions/2328

**Comment by Kenshin** [comment]
okay 已 Merge 到主适配源~
