### ISSUE TITLE
我自己也做了个类似 simpread 的项目，特地邀请您看看，嘻嘻。

### ISSUE THREAD

**Issue by szzhiyang** [Kenshin/simpread#232]
一直都很崇拜您，因此我也自己做了一个公益开源项目 **PerfectWindows**，旨在帮助大家解决使用 Windows 时的痛点，非常实用。

现在我的项目已经足够成熟了，特地邀请您看看我的项目： [GitHub.com/szzhiyang/PerfectWindows ](https://www.GitHub.com/szzhiyang/PerfectWindows )，感激不尽！

**Comment by szzhiyang** [comment]
如果您收到了我的邀请，您可以立即关闭并删除此 issue。

**Comment by Kenshin** [comment]
你好，我看到了，但暂时无法使用，只能等到我回去后了。（我在休假，且只有 Mac 系统）

到时试用完后，会帮你宣传宣传。

提几个建议：

- 最好有（跟他的竞品）对比；
- 截图（最好是动图）
- 如果想去宣传的话，V2EX，少数派，简书 等地方比较不错；

**Comment by szzhiyang** [comment]
其实我也没有打算烦劳您帮我，我只是希望用这种方式表达我对您的感激与敬意，因为效仿您做公益项目带给了我许多快乐！

**Comment by Kenshin** [comment]
哈，客气～
无所谓帮不帮，好东西，能解决问题且小而美的工具自然要让更多人知道。

**Comment by szzhiyang** [comment]
您过奖啦，有了您的鼓励，我感觉我在自己的创意上所付出的一切都很值得！:smile:

**Comment by Cologler** [comment]
@szzhiyang 你这个项目我在知乎看见过。你是不是在知乎提到过这个项目？

**Comment by szzhiyang** [comment]
是的，我觉得 **PerfectWindows** 真的能解开太多人的心结了。

**Comment by szzhiyang** [comment]
@Cologler 你想想，如果人一天到晚都对 Windows 自动更新提心吊胆的，还对 Windows 的某些功能和特性满腹牢骚的，那他们怎么能专心工作？怎么能尽情娱乐？怎么能爱惜自己的电脑？

所以我创造了 **PerfectWindows**，可以一站式地解除人们在使用 Windows 时的痛点，就像 simpread 解除人们在 Web 端阅读时的痛点那样，造福所有 Windows 用户们。:smile:

然而现在知道 **PerfectWindows** 的人数连抱怨 Windows 的人数的零头都不到，这令我相当无奈。:disappointed_relieved:

**Comment by Kenshin** [comment]
@szzhiyang 

刚详细的看了下你的项目，个人觉得有几个地方（或许）可以修改：

- `功能 和 `截图` 最好对应，即截图中的 item → 对应功能上的说明；

- 虽然都是 bat 文件，但由于缺乏必要的安装说明，所以不适用于小白用户；

- PerfectWindows 的重名率太高了，搜索时很难定位到这个项目；（也算是宣传不到位的一个原因之一）

- 虽然是 bat 文件，但也是有好多个，建议弄成 exe 的单文件形式，这样更加绿色；

- 接上条，exe 的另外一个好处是可以显示 Github URL 以及你的一些信息；

- 接上上条，要不就更 Geek 一些，只有 CLI 界面，这样也能更不错；

- 简悦虽然是免费且开源的项目，但简悦是以产品视觉设计并开发的，与其它你能想到的项目一样，所以像让 PerfectWindows  与简悦一样的话，还缺少很多产品维度的辅助，如：LOGO、官网、反馈系统等；

当然，最后一条建议只是针对练手一个产品的思路来说的，或许你无需让 PerfectWindows 成为一个产品，请忽略最后一条~

 😄

**Comment by Cologler** [comment]
@Kenshin 说起反馈系统，不考虑建立个 simpleread-bot github 账号来自动提交 issus 吗？

**Comment by Kenshin** [comment]
@Cologler 
自动提交 Github issues 的用意是什么？

**Comment by Cologler** [comment]
@Kenshin 之前看到一个新浪的页面右上角弹出一个提示说页面布局改变请提交 issus，然后打开了这个项目的 issus 页面……

**Comment by Kenshin** [comment]
@Cologler 
额，这是个好主意，但有这样的 Github boot 吗？之前没有研究过...

**Comment by Cologler** [comment]
@Kenshin 没有这样的工具，但可以很容易做到：

1. 新建个 github 账号，取名为 simpleread-bot
2. 用这个账号申请个 token
3. 集成到扩展中，然后利用它发 issus。

**Comment by Kenshin** [comment]
@Cologler 
Cool Idea~ 真是很棒的想法，这样可以实现很多设想，不仅包括于此，比如：

- 自定义的 `站点编辑器` 的内容；

- 自定义样式；

- 新站适配后，自动 close issues ；

**Comment by szzhiyang** [comment]
@Kenshin 非常感谢您的建议与鼓励！:smile:

其实我的想法是，如果功能完全能用批处理实现的话，还是用批处理完成好一些，这样做能最大程度地保证其透明性。

另外我也想向许多人证明，只要机制设计得当，一组批处理也能像一个 .exe 程序一样简单易用。通过【O】和【X】传递参数以及通过双击切换【O】和【X】都是我自己的创意。如果大家都想着去做 .exe 程序的话，谁能想到批处理还能这么玩呢？:joy:

我一直都很期待做出这么一个帮助人解决心头之患的简单易用的工具。但是我现在才大一，还没有能力做出个好看的 GUI。我不想等了，我想尽可能调动自己当前的能力（虽然非常局限）尽早把它做出来，好让许多满腹牢骚的人迅速脱离苦海。如果人一天到晚都对 Windows 自动更新提心吊胆的话，他们还怎么专心工作，尽情娱乐？

此外，大家可能仍然没有发现这组批处理所蕴含的巨大潜力，这里我就不再详细透露了，嘻嘻。:smile:

**Comment by szzhiyang** [comment]
还有， **PerfectWindows** 所做的功能就注定让它无法拥有功能截图。您不妨回过头来看看它的功能，好像都无法用截图来呈现，我也很无奈啊。:joy:
