### ISSUE TITLE
小书签功能无效（已解决或此问题不存在）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2322]
如题，小书签中的【✄ 加入到稍后读】按钮，可以正常跳到新建界面，但配置完标题和简介后，无法执行新建和删除操作

_Originally posted by @hezhefly in https://github.com/Kenshin/simpread/discussions/2314_

**Comment by Kenshin** [comment]
@hezhefly

嗨，请更新同步助手（如已经是 1.0.1 的话，请重新下载对应的版本）

**Comment by applo** [comment]
确实，我也遇到同样的问题，重新下载了就好了

**Comment by Kenshin** [comment]
嗨，抱歉，忘记关闭这个 Issues 了，如遇到此问题，请重新下载同步助手即可解决。
