### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by JUNIASK** [Kenshin/simpread#2326]
发生问题的地址: <https://baijiahao.baidu.com/s?id=1700112986770258163

**Comment by Kenshin** [comment]
嗨，我测试了下，是可以进入阅读模式的。

请更新适配列表（选项页 → 站点管理 → 手动同步适配列表） 或 [更新到 2.2.0.520](http://ksria.com/simpread/welcome/version_2.2.0.html)。
