### ISSUE TITLE
开启阅读模式后为知剪辑为空白页

### ISSUE THREAD

**Issue by geekrainy** [Kenshin/simpread#233]
如题，由于简悦没有提供保存到为知笔记的方式，但是又希望为知剪辑由简悦排版后的页面，所以就有了在简悦排版后用为知剪辑器剪辑保存的需求。#201

但是发现简悦排版后的页面被为知剪辑后变为空白页，望修复。

**Comment by geekrainy** [comment]
感谢开发这样好用的插件，期待后续的功能更新。: ）

**Comment by Kenshin** [comment]
为了避免忘记，我将重启开启这个 issues

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，

新增加了一个叫做 `生成临时页面` 的功能，生成后的页面可以使用 为知笔记的剪辑功能。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
