### ISSUE TITLE
简悦添加github页面到稍后读，只有缩略摘要，看不到readme.md的具体内容

### ISSUE THREAD

**Issue by MatrixA** [Kenshin/simpread#2332]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统  **Mac OS**

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://github.com/PaoPaoRobot/ICRA2020-paper-list>

**请描述你的问题**
添加到稍后读，只有短短几行内容。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

添加到稍后读，只有短短几行内容。

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by binsee** [comment]
嗨，请更新简悦至当前最新版本 2.2.0.520 ，在这个版本测试是正常的

**Comment by MatrixA** [comment]
好的，感谢
