### ISSUE TITLE
The extension blocks contents about Chinese politicians

### ISSUE THREAD

**Issue by SainoNamkho** [Kenshin/simpread#2333]
I have no opinion about content censorship. But I don't think it's legitimate for an extension to decide what a user is allowed to read. This extension is blocking you from something based on the developer's preference even you never triggered the reading mode.
https://en.m.wikiquote.org/wiki/Li_Peng with 
![image](https://user-images.githubusercontent.com/23036788/120924777-e4aa5a00-c707-11eb-9a6b-d7c2fa6eb995.png)
Reopen it with simpread disabled (I removed the photo to avoid potential infringements)
![image](https://user-images.githubusercontent.com/23036788/120924853-54204980-c708-11eb-98a8-bdb681409d7b.png)
But https://en.m.wikiquote.org/wiki/Deng_Xiaoping is not blocked
![image](https://user-images.githubusercontent.com/23036788/120924982-f6403180-c708-11eb-88a0-3cb4d9c51920.png)

**Comment by binsee** [comment]
嗨，这个是简悦新版本的词法分析引擎的bug导致，并非是与政治有关。

举例 https://en.m.wikiquote.org/wiki/Coast#/random 就是同一站点与政治完全无关的wiki页面，但也会出现问题。由此可证明与政治无关。

解决方式：将站点域名 `en.m.wikiquote.org` 加入到延迟列表即可。

**Comment by SainoNamkho** [comment]
> 嗨，这个是简悦新版本的词法分析引擎的bug导致，并非是与政治有关。
> 
> 举例 https://en.m.wikiquote.org/wiki/Coast#/random 就是同一站点与政治完全无关的wiki页面，但也会出现问题。由此可证明与政治无关。
> 
> 解决方式：将站点域名 `en.m.wikiquote.org` 加入到延迟列表即可。

I can reproduce the problem with the link your provided. And I'm sincerely apologizing for the misunderstanding.
But it doesn't work if I disabled the "增强解析模式" and "预加载机制" totally.
Or it keeps showing a banner of ">配置文件已更新，刷新当前页面后才能生效。" if I simply add the domain to `延迟加载列表`, even on the page of *Deng Xiaoping* which is primarily shown with no trouble.
Is the any switch to avoid changing the original page at all, if I don't activate the simpread manually?

**Comment by Joel2561** [comment]
Try some other Chinese politicians and [sites](https://en.m.wikiquote.org/wiki/Coast#/random) (as listed up there), you'll know it's nothing to do with politics.  Just put `en.m.wikiquote.org` to simpread's "**延迟加载列表**" or, in English **Lazy loading list**, you'll find this in Preference(偏好设置)→advanced setting(高级设定)→Lazy loading list(延迟加载列表)

**Comment by Joel2561** [comment]
Refresh the page or reboot ur browser, the banner should disappear.

**Comment by binsee** [comment]
> Is the any switch to avoid changing the original page at all, if I don't activate the simpread manually?

嗨，我进行了测试，你可以关闭「预先解析一些采用惰性加载的图片」这个功能，即可不再复现上述问题。

![image](https://user-images.githubusercontent.com/5285894/120926712-a4030e80-c710-11eb-9203-748bc8745185.png)

由于我不是作者，没有看过原始代码，因此先前对问题原因的解释是错误的。

正确的引发问题是由于新加入的「解析惰性加载图片」这个试验性机制引发的问题，似乎是由于网络问题导致维基百科会容易触发此问题。

**Comment by SainoNamkho** [comment]
> > Is the any switch to avoid changing the original page at all, if I don't activate the simpread manually?
> 
> 嗨，我进行了测试，你可以关闭「预先解析一些采用惰性加载的图片」这个功能，即可不再复现上述问题。
> 
> ![image](https://user-images.githubusercontent.com/5285894/120926712-a4030e80-c710-11eb-9203-748bc8745185.png)
> 
> 由于我不是作者，没有看过原始代码，因此先前对问题原因的解释是错误的。
> 
> 正确的引发问题是由于新加入的「解析惰性加载图片」这个试验性机制引发的问题，似乎是由于网络问题导致维基百科会容易触发此问题。

非常谢谢你，这个选项能工作。

**Comment by Kenshin** [comment]
@SainoNamkho 

嗨，原本这个问题已经解决了，也谢谢你在得知真相有的一些说明，免得我受到一些不正确看待...  😂 

正因为你的提示，我发现 wiki 旗下的一些域名均存在类似的问题（不是每个页面都存在，而是某些页面存在此问题）

所以，我更改了关于此问题的说明 https://github.com/Kenshin/simpread/issues/2163#issuecomment-843687177

上面这个链接其实一直都存在的。

***

另外，因为标题有很强的误导性，所以即便我修改了标题，也是会留存原始标题的，甚至也被搜索到

![image](https://user-images.githubusercontent.com/81074/120954054-e8c68e00-c780-11eb-8f9a-2add572c0f12.png)

因此，**希望可以争得你的同意的前提下**，允许我删除这个 Issues（因为标题和描述有很强的误导性。
如果你不同意我的做法，也请删除或修改 https://github.com/Kenshin/simpread/issues/2333#issue-912819070 里面的一些内容。

Github Issues 能正常访问很不容易，我不想因为某些误会导致它越来越不纯粹。

**Comment by Kenshin** [comment]
@SainoNamkho 

> Or it keeps showing a banner of ">配置文件已更新，刷新当前页面后才能生效。" if I simply add the domain to 延迟加载列表, even on the page of Deng Xiaoping which is primarily shown with no trouble.

补充下这个问题：

这是因为某个 URL 被双开后造成的，所以最好的做法是：关闭全部的 Tab 页面或重启浏览器。（此问题与本 Issues 无关，只是提示下。

**Comment by SainoNamkho** [comment]
> @SainoNamkho
> 
> 嗨，原本这个问题已经解决了，也谢谢你在得知真相有的一些说明，免得我受到一些不正确看待... 😂
> 
> 正因为你的提示，我发现 wiki 旗下的一些域名均存在类似的问题（不是每个页面都存在，而是某些页面存在此问题）
> 
> 所以，我更改了关于此问题的说明 [#2163 (comment)](https://github.com/Kenshin/simpread/issues/2163#issuecomment-843687177)
> 
> 上面这个链接其实一直都存在的。
> 
> 另外，因为标题有很强的误导性，所以即便我修改了标题，也是会留存原始标题的，甚至也被搜索到
> 
> ![image](https://user-images.githubusercontent.com/81074/120954054-e8c68e00-c780-11eb-8f9a-2add572c0f12.png)
> 
> 因此，**希望可以争得你的同意的前提下**，允许我删除这个 Issues（因为标题和描述有很强的误导性。
> 如果你不同意我的做法，也请删除或修改 [#2333 (comment)](https://github.com/Kenshin/simpread/issues/2333#issue-912819070) 里面的一些内容。
> 
> Github Issues 能正常访问很不容易，我不想因为某些误会导致它越来越不纯粹。

已经修改，抱歉。对于删掉 Issue 我没有问题。

**Comment by Kenshin** [comment]
嗨，我以为收不到这个回复了。 😂  （并不是每个人都能留意 Github Issues 的回复邮件...

既然你同意删除 issues，当你收到这个 issues 回复邮件时，此 Issues 已被删除

另外，我已经看到了你修改后的内容，谢谢你对此事的澄清。其实早在你之前，我就遇到了一个类似的问题，在知乎上也有个学生（感觉你也大概率是个学生）遇到了你一样的问题，且措辞导致了很多误会。

当然，误会解除后，他也选择了同样的做法：删除了知乎的错误言论，并且在 Webstore 进行了澄清。

![image](https://user-images.githubusercontent.com/81074/121324724-92ee1380-c943-11eb-8435-f1ec379cf90f.png)

PS：关于你遇到的问题，我已经记录在 https://github.com/Kenshin/simpread/issues/2333 并且会在全部简悦通知渠道发布它。
