### ISSUE TITLE
阅读模式在少数派文章页面的适配问题

### ISSUE THREAD

**Issue by aoxu** [Kenshin/simpread#2339]
在少数派文章页面使用阅读模式时
如图左上角的目录显示不出文字
我采用的是默认设置，可能是文字颜色不对
文章地址： https://sspai.com/post/67057
![Snipaste_2021-06-07_13-13-46.png](https://i.loli.net/2021/06/07/vCTZziOUSHnGBPW.png)

**Comment by Kenshin** [comment]
嗨，XA技术不宅兄~ 你的头像没有改~

你在 **隐身模式下，仅启用简悦** 试试，看看是否是其它扩展的干扰？

下图是我的效果

![image](https://user-images.githubusercontent.com/81074/120962853-1e747280-c793-11eb-9c5c-cbf0e9890202.png)

**Comment by aoxu** [comment]
忘了这个头像，我按你说的试了一下，问题依旧，如图
补充一下我的环境说明：Windows 10 专业版 20H2，Edge 浏览器稳定版，都是保持更新的
![Snipaste_2021-06-07_13-23-57.png](https://i.loli.net/2021/06/07/lCvNo9YkfVtxJ8H.png)

**Comment by Kenshin** [comment]
emmm 我知道问题了...

> 因为你在少数派开启了 `暗色模式` 造成的，我已经更新了适配规则，你可以重新更新它，即可解决。

![image](https://user-images.githubusercontent.com/81074/120968096-0274cf00-c79b-11eb-8a91-135cc42fb85f.png)

如果仍不好使，请看下图的提示

![image](https://user-images.githubusercontent.com/81074/120968276-3a7c1200-c79b-11eb-9e47-228bdce1e98d.png)

**Comment by aoxu** [comment]
适配规则更新后，验证已解决。
没想到是这个原因，更没想到这都能被你找出来，佩服。

**Comment by Kenshin** [comment]
> 适配规则更新后，验证已解决。
> 没想到是这个原因，更没想到这都能被你找出来，佩服。

哈哈，客气了。
跟 **久病成医** 是一个道理。做 QA 的时候，什么奇葩的情况/问题都遇到过的，印象中似乎有个用户反馈过类似的问题，虽然可能不一样，但给了我一些启示。  😅

**Comment by aoxu** [comment]
> > 适配规则更新后，验证已解决。
> > 没想到是这个原因，更没想到这都能被你找出来，佩服。
> 
> 哈哈，客气了。
> 跟 **久病成医** 是一个道理。做 QA 的时候，什么奇葩的情况/问题都遇到过的，印象中似乎有个用户反馈过类似的问题，虽然可能不一样，但给了我一些启示。 😅

我原打算如果还找不出原因，就要录屏了。如果录屏，肯定能发现是暗色模式的问题，所以问题终究一定能被解决。
