### ISSUE TITLE
您的项目捐助二维码破损了。

### ISSUE THREAD

**Issue by szzhiyang** [Kenshin/simpread#234]
如题。

**Comment by Kenshin** [comment]
感谢反馈～

不清楚为什么，偶尔就有朋友反馈这个问题…

二维码可以看 http://ksria.qiniudn.com/zhifu_m.png

**Comment by szzhiyang** [comment]
您不妨将这个二维码图片放在一个 Repository 下。

**Comment by Kenshin** [comment]
到时候我会更新下。 😃

不过，很奇怪的是并不是每个人都看到残破的图片… 😂

**Comment by Kenshin** [comment]
@szzhiyang 
刚刚更新了下 donate link，请问是否还有这个问题吗？

无误的话，请关闭此 issues  😃

**Comment by szzhiyang** [comment]
很抱歉没能及时回应，问题已解决，麻烦您了。
