### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by marylxd** [Kenshin/simpread#2343]
发生问题的地址: <https://wizardforcel.gitbooks.io/core-python-2e/content/>

**Comment by Kenshin** [comment]
嗨，这个页面的适配是正常的，只是因为正文内容较少，所以才有提示。你可以忽略它。

![image](https://user-images.githubusercontent.com/81074/121003018-98baec00-c7bf-11eb-99b2-8c0eca9f56b1.png)

![image](https://user-images.githubusercontent.com/81074/121003039-a1abbd80-c7bf-11eb-8d9a-936d3ec30042.png)

如果你没有上图的效果，估计需要 [更新适配源](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E9%80%82%E9%85%8D%E6%BA%90?id=%e5%ae%98%e6%96%b9%e9%80%82%e9%85%8d%e6%ba%90)
