### ISSUE TITLE
可以适配一下TIB这个网站嘛

### ISSUE THREAD

**Issue by lizhiwei1996** [Kenshin/simpread#235]
网址是https://www.typeisbeautiful.com/
直接用临时阅读模式经常会丢掉图片。
谢谢啦。

**Comment by Kenshin** [comment]
okay，适配后会通知你~

**Comment by Kenshin** [comment]
你好，此网址的图片的确在设置上比较特殊，所以暂时无法支持，只能下个版本解决~

请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

**Comment by Kenshin** [comment]
当前站已适配，请更新 https://simpread.ksria.cn/sites/details/R9FhffiDqM

***

另更新了一批新站，更新方法

- 点击 ➊ 即可
![image](https://user-images.githubusercontent.com/81074/57358987-2a06a100-71a9-11e9-89c8-18249c6e3fe7.png)

- 分别点击 ➊ ➋ 即可


![image](https://user-images.githubusercontent.com/81074/57359096-676b2e80-71a9-11e9-81ec-ffaadf659013.png)

***

简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
