### ISSUE TITLE
微信文章经简悦处理后，文章阅读效果更差了

### ISSUE THREAD

**Issue by unchangedusername** [Kenshin/simpread#2351]
- 操作系统 **Win32**

- 浏览器版本 **Microsoft Edge  91.0.864.41**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://mp.weixin.qq.com/s/038kpF9sY65QRXcDu-hVkQ>
- 简悦阅读模式处理后，文章多出变白。可读性较未处理前更差
![image](https://user-images.githubusercontent.com/20478302/121328503-f62d7500-c946-11eb-9dde-6260762b19dc.png)

**Comment by Kenshin** [comment]
嗨，原则上说，微信个别文章并不适合使用简悦，如这篇。

因为它有太多太多错误的布局和文字排版了。
