### ISSUE TITLE
建议：允许自定义markdown模板的each内支持\n换行

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2354]
当前自定义markdown模板的each循环内不允许首位出现空内容（空格、换行），因此会使两条标注间没有空行，不利于识别两条标注的分界。

测试的md模板配置：

```
<!--[[flomo]]-->
{{tags}}
Note: {{note}}
-----------------
{{#each}}
{{> |an_html}}
{{an_note}}
{{an_tags}}
{{/each}}
```

稍后读的标注内容：
![image](https://user-images.githubusercontent.com/5285894/121361721-23d6e600-c968-11eb-9339-0c01364f5318.png)

导出到flomo后：
![image](https://user-images.githubusercontent.com/5285894/121363031-28e86500-c969-11eb-9c99-a0e1bdfc188b.png)

可以看到两条标注间没有空行，难以区分边界，不利于阅读。

希望进行优化：
- 允许在`each`循环内支持换行，如允许在模板内插入字符串`\n`，在格式化模板时替换为换行符。
- 或者在循环结尾再加一个换行符（即额外加一个空行）

**Comment by Kenshin** [comment]
> 希望进行优化：

> 允许在each循环内支持换行，如允许在模板内插入字符串\n，在格式化模板时替换为换行符。
> 或者在循环结尾再加一个换行符（即额外加一个空行）

不错的想法，我考虑下。
或者说定制化再灵活些，看看能否进入一些 HTML 模板引擎来做这个事情。

**Comment by Kenshin** [comment]
嗨，Markdown 模板定制化 2.0 发布了，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3725)。

特点
---

- 可完美的支持 Obsidian · Logseq 等任意双链笔记的语法规则，细节请看 [模板库](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)

- 内置 [EJS 引擎](https://ejs.co/#docs) ，所以可以使用 EJS 引擎全部的功能。

- 可在模板中直接编写 Javascript 代码。

- 所见即所得，相比 1.0 在模板中去掉空格或无法空格等问题，2.0 无此问题。

- 兼容 1.0 的 [语法规则](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=markdown)（占位符）。

- 兼容 1.0 [模板](https://github.com/Kenshin/simpread/discussions/2153)。

如何使用
---

> **2.0 仅提供模板解析方案，并未提供导出方案**，所以需要跟插件配合使用，**接下来还会陆续增加更多插件**。

下面的插件均可配合 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件实现自动化方案。

- [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

- [导出 org-mode 文件](https://github.com/Kenshin/simpread/discussions/3775)

安装后需要开启下图所示的选项才可使用

![image](https://user-images.githubusercontent.com/81074/165034089-a8e2987e-7947-4bdc-89e4-5d743fff1f47.png)

模板库
---

- [Obsdian 模板之一](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311)

- [Obsdian 模板之二](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627313)

- [Logseg · Markdown 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627315)

- [Logseg · org-mode 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627320)

更多模板，[请看这里](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)。

模板截图
---

![](https://imgs.zhubai.love/230c79c30d8c47f88c6cd659e2916b1a.png)

![](https://imgs.zhubai.love/831d361aa3bf4c9e90f3fca0cbb681bc.png)
