### ISSUE TITLE
在阅读模式的中的高亮和评论, 在导出到notion后消失了. 

### ISSUE THREAD

**Issue by WangHaiYang874** [Kenshin/simpread#2356]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10**

- 浏览器版本 **edge 91.0.864.41**

- 简悦版本 这几日刚下载的, 没找到版本号, 应该是最新的吧

- 发生问题的地址 额, 好几个导出都是这样的, 比如说 https://slate.com/technology/2016/04/inkys-aquarium-escape-reveals-the-mystery-of-octopus-intelligence.html 

**请描述你的问题**

> 如题😀

- 另外, 设置页面里的字乱码了, 这是啥情况? 如下图: 
![image](https://user-images.githubusercontent.com/43157107/121485523-d78cb400-ca02-11eb-9290-101bd2ce3d28.png)

**Comment by Kenshin** [comment]
嗨

乱码的问题重启浏览器即可解决。
至于 Notion 的问题，你可以看看 https://github.com/Kenshin/simpread/discussions/2225 是否可以解决？（因为 2.2 加入了很多定制化的功能，所以产生此问题的原因比较多，另外也看下 https://github.com/Kenshin/simpread/discussions/1773 这个情况。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
