### ISSUE TITLE
请求优化微信文章代码块部分

### ISSUE THREAD

**Issue by God-xzz** [Kenshin/simpread#2357]
已经安装了代码增强插件打开了，并且打开了增强解析，但是代码部分没有换行，关闭增强解析也是。

附上链接https://mp.weixin.qq.com/s?__biz=MzUwOTg0MjczNw==&mid=2247490395&idx=1&sn=49215a3b51a6768802ba2eae3410e537&chksm=f90d5f05ce7ad613a5200b803580314a298443f98f853a73941ec64ea4a7c90822f1f814cfa9&scene=178&cur_album_id=1429956252289024000#rd

**Comment by Kenshin** [comment]
嗨，请求谈不上，原本就应该优化这里的，但实在是太多各种事情，再加上代码高亮的规则也忒多了，导致问题发生。
代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
