### ISSUE TITLE
Latex公式的问题

### ISSUE THREAD

**Issue by C-E5** [Kenshin/simpread#2358]
* 操作系统: Windows x64
* 浏览器:  Edge 91.0.864.41 (官方内部版本) (64 位)
* 简阅版本: 2.2

问题网址: https://artofproblemsolving.com/community/c4h2586256_prove_that_fx__x_forall_x
我的问题是这个网站的latex解析存在问题。解析出来的公式特别大但是正文字体很小。
![](https://i.imgur.com/Mai4o1P.png)

**Comment by Kenshin** [comment]
谢谢反馈，我明天确认下，看截图感觉 LateX 像图片…

**Comment by Kenshin** [comment]
嗨，你给出的 URL 没有看到类似截图的界面。

另外，通过 URL 得到了我之前说的结论，这个公式是图片，至于你说的问题，应该是 **被识别为图片后，图片尺寸重新设置** 造成的。

你可以通过 **自定义 CSS 方式** 来解决图片的问题，但因为我没有重现你截图的内容，暂时没法帮到你。
