### ISSUE TITLE
聚焦模式或者阅读模式下导出的PDF文档图片无法显示

### ISSUE THREAD

**Issue by wang536542** [Kenshin/simpread#2361]
以简书网址为例，使用同步助手导出PDF文档打开图片无法显示。PS:直接将网页导出为PNG也失败。

而采用导出到有道笔记本的方法可以显示图片，并且可以看到图片是采用网址链接方式加载显示的。、
希望解决直接导出PDF显示图片。可以的话也修复下导出网页为图片功能。

一个小用户。
![1](https://user-images.githubusercontent.com/77597683/121621038-fb510800-ca9d-11eb-8218-773bfad19807.png)
![2](https://user-images.githubusercontent.com/77597683/121621057-00ae5280-ca9e-11eb-9934-d0ae0739ac1a.png)
![3](https://user-images.githubusercontent.com/77597683/121621069-04da7000-ca9e-11eb-9014-63e0f5f3f5d1.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

方便把出问题的 URL 给我看下？（如果 URL 包含视频的话，也会导出失败。

猜测你没有开启 [图片代理](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e5%9b%be%e7%89%87%e4%bb%a3%e7%90%86) 的选项，这是为解决导出 PDF 图片防盗链的问题。

如果上面的选项已经开启的话，试试多导出几次？因为可能有图片加载缓存的问题。

PS：再小的用户也是简悦的用户，无论是否是高级账户。

**Comment by wang536542** [comment]
大神好：链接如下，https://www.jianshu.com/p/567ab815608e&nbsp;
奈斯的geek不多，肯定会员支持。已开启图片代理功能，并多次测试，PDF文档确实不能导出图片；
但导出离线HTML文件是可以带图片的。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 聚焦模式或者阅读模式下导出的PDF文档图片无法显示 (#2361)





 
嗨，谢谢反馈。
 
方便把出问题的 URL 给我看下？（如果 URL 包含视频的话，也会导出失败。
 
猜测你没有开启 图片代理 的选项，这是为解决导出 PDF 图片防盗链的问题。
 
如果上面的选项已经开启的话，试试多导出几次？因为可能有图片加载缓存的问题。
 
PS：再小的用户也是简悦的用户，无论是否是高级账户。

**Comment by Kenshin** [comment]
我测试了下，我这边是没问题的。

请问是什么系统？在 Github 可以找到我的联络方式，标题包含这个 issues id，把配置文件给我，看看是否是配置文件有问题造成的。

**Comment by wang536542** [comment]
大神好：链接如下，https://www.jianshu.com/p/567ab815608e
奈斯的geek不多，肯定会员支持。已开启图片代理功能，并多次测试，PDF文档确实不能导出图片；
但导出离线HTML文件是可以带图片的。
![Uploading image.png…]()

**Comment by wang536542** [comment]
已发送至邮箱fxblog@gmail.com

**Comment by Kenshin** [comment]
收到，因为 2.2 在少数派首发，所以时间上会比较忙，确认后我会回复你~

**Comment by Kenshin** [comment]
嗨，我用你的配置文件没有复现这个问题...
请问，任意页面导出 PDF  均存在此问题吗？

不过，我用的是 Mac 系统，我找几个 Windows 大神帮帮忙吧。

@binsee 感兴趣的话，调查下？

**Comment by binsee** [comment]
我这边测试了，这个网址是正常的。

**Comment by Kenshin** [comment]
@binsee 

收到~

@wang536542

我用你的配置文件也测试通过。

看看 https://github.com/Kenshin/simpread/issues/2361#issuecomment-859270347 里面的描述。

**Comment by wang536542** [comment]
> 嗨，我用你的配置文件没有复现这个问题...
> 请问，任意页面导出 PDF 均存在此问题吗？
> 
> 不过，我用的是 Mac 系统，我找几个 Windows 大神帮帮忙吧。
> 
> @binsee 感兴趣的话，调查下？

测试了下，任意页面都是这样导出PDF图片不显示

**Comment by binsee** [comment]
> 测试了下，任意页面都是这样导出PDF图片不显示

emmm，这就不对劲了。
当前简悦最新版是2.2.0.520
同步助手最新版是1.0.1

你用的是最新版吗？如果不是，请更新最新版本再试试
如果是，那真的不对劲。

**Comment by wang536542** [comment]
> > 测试了下，任意页面都是这样导出PDF图片不显示
> 
> emmm，这就不对劲了。
> 当前简悦最新版是2.2.0.520
> 同步助手最新版是1.0.1
> 
> 你用的是最新版吗？如果不是，请更新最新版本再试试
> 如果是，那真的不对劲。

不好意思，同步助手最更新至1.0.1后问题解决，谢谢！

**Comment by Kenshin** [comment]
哈哈，竟然是这个问题... 看来还是我疏忽了。
