### ISSUE TITLE
每次阅读主题打开都是黑色模式

### ISSUE THREAD

**Issue by slowmande** [Kenshin/simpread#2365]
设置了白色的主题，但打开了新网站还是黑色主题，需要手动切换。其他的字体、字号等都无问题。

**Comment by Kenshin** [comment]
请给个 URL 看看。
另外，是不是你的系统开了暗色模式？2.2 的简悦自带了跟随系统的暗色模式功能，在选项页 → 高级设定 里面

![image](https://user-images.githubusercontent.com/81074/121676714-89051580-cae7-11eb-9768-4d155d18e063.png)

**Comment by slowmande** [comment]
修改了设置就可以了，谢谢

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
