### ISSUE TITLE
希望增加彻底隐藏控制按钮的功能

### ISSUE THREAD

**Issue by yugirichan** [Kenshin/simpread#2369]
![屏幕截图 2021-06-12 004221](https://user-images.githubusercontent.com/54147088/121721731-275c9f80-cb17-11eb-906a-6ae08fe1dbf2.png)
每次进入阅读模式，鼠标不小心移到右下角时，这个控制栏就会自动显示，挺讨厌的。
希望能彻底隐藏这三个按钮，使阅读模式做到彻底的简洁。
![屏幕截图 2021-06-12 004536](https://user-images.githubusercontent.com/54147088/121722051-86221900-cb17-11eb-9e24-6a37646021de.png)

**Comment by yugirichan** [comment]
https://github.com/Kenshin/simpread/issues/9
刚刚看到以前有人提过这个问题，但我还是不知道怎么操作，这个链接里面并没有提到。
我不只是希望这3个按钮表面上隐藏，因为鼠标光标移到右下角时，它们又自动显示了，而且还会附加一个大大的控制栏。我希望鼠标光标移到右下角时，什么都不会显示。

**Comment by Kenshin** [comment]
哈哈，你的需求太 Geek 了，但是可以实现，需要 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 

加入如下代码

```
sr-rd-crlbar {
    display: none!important;
}
```

放到 **选项页 → 高级设定 → 自定义样式 → 左下角最后**，即可。

**Comment by yugirichan** [comment]
> 哈哈，你的需求太 Geek 了，但是可以实现，需要 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)
> 
> 加入如下代码
> 
> ```
> sr-rd-crlbar {
>     display: none!important;
> }
> ```
> 
> 放到 **选项页 → 高级设定 → 自定义样式 → 左下角最后**，即可。

感谢！已解决（除了退出阅读模式不太方便）

**Comment by Kenshin** [comment]
退出的话，可以使用 `ESC` 方案，选项页 → 高级设定 → 全局 里面可以设置。

没问题的话，我关闭这个 Issues 了。
