### ISSUE TITLE
雪球网文章页面不能正确识别

### ISSUE THREAD

**Issue by Hachikoko** [Kenshin/simpread#237]
https://xueqiu.com/8290096439/57019750

**Comment by Kenshin** [comment]
感谢反馈，等我回去后确认下，另外可以通过站点编辑器自行修改。

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
