### ISSUE TITLE
加入到稍后读小书签功能无法正常使用

### ISSUE THREAD

**Issue by Big-god-Yin** [Kenshin/simpread#2374]
win10
edge浏览器
最新版简悦
使用  加入到稍后读小书签，点击新建后，提示已完成新增，但是在稍后读窗口里并没有刚刚试图加入的内容（刷新后也没有）

**Comment by Kenshin** [comment]
嗨，此功能需要配置 同步助手的 [同步方式](http://ksria.com/simpread/docs/#/Sync?id=%e5%90%8c%e6%ad%a5) 与 [自动同步功能](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5)


![image](https://user-images.githubusercontent.com/81074/121793605-536d4300-cc33-11eb-871f-b56ed6cb4252.png)

**Comment by Big-god-Yin** [comment]
成功解决

**Comment by Big-god-Yin** [comment]
非常感谢

**Comment by Kenshin** [comment]
搞定就好，其实文档中已经提示了，可能需要我再补充点。
