### ISSUE TITLE
插件：代码段增强出现问题 高亮失效

### ISSUE THREAD

**Issue by ysj1173886760** [Kenshin/simpread#2375]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

系统ubuntu
浏览器版本 Chrome 90.0.4430.93 64位
简悦版本 2.0.0
地址 https://www.freecodecamp.org/news/building-bots/
打开阅读模式提示代码段插件出现错误
对比发现，代码高亮失效

![image](https://user-images.githubusercontent.com/42030331/121793728-c2976700-cc34-11eb-9873-6bf91748bf00.png)

python代码

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
