### ISSUE TITLE
知乎包含 LateX 时导出原生 PDF 显示异常（CSDN 不支持  katex 加载方案）

### ISSUE THREAD

**Issue by HellowDream** [Kenshin/simpread#2384]
**请说明发生问题的环境**

- 操作系统 windows 10 
- 浏览器版本 edge 最新
- 简悦版本 **2.2.0.520**

- 发生问题的地址 例如这种带公式的 https://www.zhihu.com/question/304499706/answer/544609335

**请描述你的问题**

公式（svg）无法正确显示，表现为 图片裂开

![image](https://user-images.githubusercontent.com/34744812/121901330-e227b000-cd58-11eb-9dc5-e1440a941539.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，知乎的 LateX 好像是它自己的自有方案，我明天确认下。

**Comment by Kenshin** [comment]
嗨，果然是我说的情况，看下图

![image](https://user-images.githubusercontent.com/81074/121983727-606d6c00-cdc4-11eb-856c-a02609419220.png)

简单的点说，它不是图片，但是**因为 PDF 导出时的机制导致触发了知乎的防盗链机制**，所以出现了无图效果。

我先记下来吧，看看如何更好的修复。

**Comment by HellowDream** [comment]
加油，祝早日解决

**Comment by HellowDream** [comment]
CSDN 公式导出也存在异常：

https://blog.csdn.net/Melody1211/article/details/104950998

![image](https://user-images.githubusercontent.com/34744812/122319747-a0af2480-cf53-11eb-89e7-2c049422b736.png)

我记得之前好像在某个issue里见过类似问题，说是csdn有两套latex方案，但是不知道有解决没有。

**Comment by Kenshin** [comment]
@HellowDream 

是没问题的，如下图

![image](https://user-images.githubusercontent.com/81074/122321706-dd304f80-cf56-11eb-8239-9057f8cd6a57.png)

需要将  `blog.csdn.net` 加入到延迟加载列表，你可以看下 https://github.com/Kenshin/simpread/discussions/1553 提供的步骤

**Comment by HellowDream** [comment]
Edge，我尝试了启用和禁用预加载机制的两种解决方案，都失败了（包括#1553中的示例页面）。
这个 确保页面加载完毕 是指 能够看到全部内容即可，对吧？
PS: 我指的是PDF原生导出后公式显示异常，单纯的页面阅读模式一直是正常显示的。

**Comment by Kenshin** [comment]
> 这个 确保页面加载完毕 是指 能够看到全部内容即可，对吧？

是的。

> 我指的是PDF原生导出后公式显示异常，单纯的页面阅读模式一直是正常显示的。

emmm 我看了 PDF，确如你所说。

不过，我知道原因了... 这个页面使用了 `katex` 作为渲染机制，但简悦没有支持它，只支持了 `MathJax` 方案。

![image](https://user-images.githubusercontent.com/81074/122508362-74b7a000-d034-11eb-89bc-f30341e501e4.png)

**下图是  `katex` 方案**
![image](https://user-images.githubusercontent.com/81074/122508376-7e410800-d034-11eb-885e-1c2298887323.png)


你试试 https://blog.csdn.net/VictoriaW/article/details/70053790 这个页面。

PS：CSDN 支持 nnnnn 种高亮规则，还支持不同的公式方案...

**Comment by HellowDream** [comment]
https://blog.csdn.net/VictoriaW/article/details/70053790 ：
 启用预加载，blog.csdn,net不加入延迟列表，进入阅读模式不显示公式；**退出阅读模式原页面仍显示异常**；关闭简悦扩展可以正常显示；
加入延迟列表，阅读模式显示正常：
![image](https://user-images.githubusercontent.com/34744812/122532929-970ce600-d053-11eb-92a0-336adb4d6c16.png)
但是原生导出**显示异常**，不过至少勉强维持二维渲染了：
![image](https://user-images.githubusercontent.com/34744812/122532981-a2f8a800-d053-11eb-9baf-31c71e4f9c30.png)


PS:额外一个疑似bug，修改配置（比如加入删除延迟列表内容）后概率性出现某页面反复提醒配置已更新请刷新的提示，但刷新无效，只会反复提示。只有关闭浏览器可以恢复。（我猜测是，输入后光标没有退出输入框，就是没有在外部重新点一下而是直接切换到其它页面，但感觉这个动作挺不容易注意到）
PPS：csdn确实是。。。。自己格式都不统一

**Comment by Kenshin** [comment]
> 启用预加载，blog.csdn,net不加入延迟列表，进入阅读模式不显示公式；退出阅读模式原页面仍显示异常；关闭简悦扩展可以正常显示；

这是正常的，如果你想要显示 `LateX` 必须要将这个 **URL 或 主域名** 加入到 延迟加载列表 才行。

> 修改配置（比如加入删除延迟列表内容）后概率性出现某页面反复提醒配置已更新请刷新的提示，但刷新无效，只会反复提示。只有关闭浏览器可以恢复。

**因为同一个 URL 双/多开了**，为了防止配置文件被互相覆盖（你可以理解为一个 Tab 拥有一份配置文件），所以加了这个锁功能，但是没有配置双开/多开的情况（毕竟这个情况很少发生。

**Comment by HellowDream** [comment]
知乎的bug啥时候修复啊？

**Comment by Kenshin** [comment]
嗨，知乎数学公式在导出 PDF 时无法显示图片的问题已经解决了，请安装 [此插件](https://github.com/Kenshin/simpread/issues/2860)

因此，我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
另外，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869
