### ISSUE TITLE
关于同步助手的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2385]
mac下，chrome浏览器
安装了同步助手，用的坚果云。

不得不说，同步这一块的设置真是心累啊，搞了半天也不确定有没有同步成功。
1. 选项页中显示的同步方式是：手工同步方式，不知道哪里可以打开自动同步方式。
2. 同步助手中的同步文件夹路径是什么，我的理解应该是chrome浏览器插件生成的数据文件，请问这个数据文件在mac下路径是哪里？
3. 坚果云下面有一个md文件夹，据文档说这个不应该在2.0中出现吧，所谓的output文件夹没有看到。

简悦的文件同步机制是什么样的？我的理解是
浏览器客户端产生的数据文件（我个人建议不要叫做配置文件，把用户绕晕了，无路是什么数据文件统统叫做数据文件就好）
由同步助手读取这些数据文件，完成到坚果云的自动同步？

那么同步助手能够读取mac下的chrome的文件吗？mac下的各个应用的数据文件其他app无法访问吧？

很多问题，很疑惑，很乱，求解答

_Originally posted by @brandbao in https://github.com/Kenshin/simpread/discussions/2383_

**Comment by Kenshin** [comment]
嗨，解答下你的疑问

> 选项页中显示的同步方式是：手工同步方式，不知道哪里可以打开自动同步方式。

选项页往下拉就能看到 

![image](https://user-images.githubusercontent.com/81074/121984723-11283b00-cdc6-11eb-97aa-592d01802675.png)

> 同步助手中的同步文件夹路径是什么，我的理解应该是chrome浏览器插件生成的数据文件，请问这个数据文件在mac下路径是哪里？

其实你提到了，因为 Chrome 沙箱机制导致数据文件仅存在于 Chrome 内部，但通过同步助手设置的路径，可以将这个配置文件保存到本地的任意位置。

比如像我把数据文件保存了到坚果云目录下，就可以使用坚果云来做自动同步了。

![image](https://user-images.githubusercontent.com/81074/121984898-61070200-cdc6-11eb-8c25-efa35cff1763.png)

> 坚果云下面有一个md文件夹，据文档说这个不应该在2.0中出现吧，所谓的output文件夹没有看到。

`md` 是 1.x 时通过导出服务（导出到坚果云时的文件夹名称）
`output` 是 2.x 时通过增强导出服务导出的文件夹名称（虽然可以设置任意位置，但尽量保持与同步文件夹是一个位置）

![image](https://user-images.githubusercontent.com/81074/121985053-9dd2f900-cdc6-11eb-8e57-cc51760f76d0.png)

> 我个人建议不要叫做配置文件

对于新手来说，确实有些困扰，但老用户是知道什么含义的。当然，你说的是有道理的，我也在考虑如何平衡新/老用户间的名词问题。


不知道上面的解释可以解决你的困扰？

**Comment by brandbao** [comment]
谢谢，下面这句话不是很清楚。
“比如像我把数据文件保存了到坚果云目录下，就可以使用坚果云来做自动同步了。”

这句话的意思是将数据文件保存到坚果云的客户端的本地目录下对吧？
路径是不是这样：
1. 同步助手将配置文件保存到本地的任意位置。（目前这个位置是坚果云客户端的本地mac上的某个目录）
2. 然后坚果云读取本地这个目录上的数据，同步到坚果云的云端

是这样一个路径吗？
这样做是为了避免产生云服务费用是吗？

**Comment by brandbao** [comment]
我实验了半天，还是没有搞定
导出那一块需要配置文件路径吗？
主要是我完全不理解整个同步策略是怎样的。
各种设置的名称非常庞杂
没有一个清晰的路径，告诉我们，配置坚果云应该一步一步是怎样做。
以及如何才算配置好，检查哪些才意味着同步成功了。

我个人觉着你们需要一个产品经理帮你们帮所有的用户面东西梳理简单。
即使我也做过开发，但是一头雾水。

**Comment by Kenshin** [comment]
> 这句话的意思是将数据文件保存到坚果云的客户端的本地目录下对吧？
> 路径是不是这样：
> 
> 1. 同步助手将配置文件保存到本地的任意位置。（目前这个位置是坚果云客户端的本地mac上的某个目录）
> 2. 然后坚果云读取本地这个目录上的数据，同步到坚果云的云端

嗨，就是这个意思。

至于目录的话，可以看下图

![image](https://user-images.githubusercontent.com/81074/126638904-2beeec04-7f77-4ddd-9cb4-d9b04bb51e87.png)

**Comment by brandbao** [comment]
如何确定同步成功了？我查看了坚果云云端内容
一个md目录，加上一个.json文件，打开md目录里面什么也没有
我已经做了标记，应该产生了数据了。

**Comment by Kenshin** [comment]
`md` 文件夹是 1.x 时用于通过导出服务导出 markdown 到坚果云时的位置。

标注和稍后读的数据均保存在 `simpread_config.json`

**Comment by brandbao** [comment]
明白了，我的应该同步成功了。谢谢
实在是太复杂了。

**Comment by Kenshin** [comment]
某种程度上跟 Obsidian 的同步方式类似。

简悦是个四年的项目，所以从目前的角度看很多功能都不是最初时就设想好了，虽然 1.0 时就考虑到了现在的一些功能，如：稍后读 1.0 版本就有此功能，但仍无法 100% 考虑到四年后的一些场景。

所以

`md` → 是 1.x 时代导入到坚果云的 md 所在的文件夹。

simpread_config.json 即包含了数据文件也包含了配置文件。
