### ISSUE TITLE
为什么知乎的内容保存在github上面的阅读显示。和语雀的阅读显示不一样？

### ISSUE THREAD

**Issue by baby1128** [Kenshin/simpread#2387]
这个是github的
![QQ图片20210615204844](https://user-images.githubusercontent.com/31163874/122055473-3eeb9f00-ce1b-11eb-8ad0-d572f53da712.png)

这个是语雀的
![QQ图片20210615204818](https://user-images.githubusercontent.com/31163874/122055494-43b05300-ce1b-11eb-9a4e-9df98bc2e0f2.png)

请问我要如何使得知乎的内容保存在github上，阅读模式能显示得和语雀一样观看？

**Comment by Kenshin** [comment]
嗨
导入 Github 与语雀都是 markdown 在语雀能直接预览。
在 Github 也应该被预览才对，截图上显示的 md 原始内容

我明天看下。

**Comment by baby1128** [comment]
@Kenshin 是的，我也觉得应该是一样才对，可是网页的文章是正常的，唯独我把知乎的内容一导入，就不能直接预览了。
麻烦了，谢谢！！！

**Comment by binsee** [comment]
@baby1128 嗨，我确认是文章标题含 `?` 号导致出现非法文件名，导致文件名后缀被忽略导致。
你保存到 github 的文件缺少了 `.md` 的文件后缀名，因此不会作为 `markdown` 进行渲染，而是作为纯文本来显示，即你看到的md原始内容。

请为简悦安装插件，来修复此类问题：https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

测试截图：
![image](https://user-images.githubusercontent.com/5285894/122245359-3e750600-cef8-11eb-8704-a87c68522c4a.png)

**Comment by baby1128** [comment]
@binsee 
谢谢指导。已经安装插件，能正常显示了，但同时又出现另外一个问题。
前面几个图片能正常显示，后面开始就没有图片显示了，检查编辑里面是有图片地址的。
原文地址：https://www.zhihu.com/question/367561102/answer/984965177

截图情况：
![QQ图片20210617091122](https://user-images.githubusercontent.com/31163874/122315367-7c037e80-cf4c-11eb-9cd0-d9bc31268f56.png)
![QQ图片20210617091104](https://user-images.githubusercontent.com/31163874/122315370-7d34ab80-cf4c-11eb-9334-8e2648d591c3.png)

- 图1为阅读预览模式的情况
- 图2为导入github显示的情况

**Comment by Kenshin** [comment]
@baby1128 

我看了下 md 源文件是没问题的

![image](https://user-images.githubusercontent.com/81074/122322047-65165980-cf57-11eb-863d-f88344cc3bb5.png)

**Comment by baby1128** [comment]
@Kenshin 
是的，我也有看到源文件是带有图片地址，但是退出编辑后，还是一样不显示这后面部分的图片，不知道是哪里出了问题

**Comment by Kenshin** [comment]
> @Kenshin
> 是的，我也有看到源文件是带有图片地址，但是退出编辑后，还是一样不显示这后面部分的图片，不知道是哪里出了问题

我看了下，这个图片应该是后台设置为 **无法在线浏览**，你用浏览器打开它，就自动下载了。

**Comment by baby1128** [comment]
@Kenshin 
可是语雀却又是正常的显示呢？好奇怪啊！

**Comment by baby1128** [comment]
@Kenshin 
可是语雀却又是正常的显示呢？好奇怪啊！
语雀截图：
![11](https://user-images.githubusercontent.com/31163874/122357866-aeca6880-cf86-11eb-8d3b-643b2b9a43fc.png)

**Comment by baby1128** [comment]
@Kenshin 
可是语雀却又是正常的显示呢？好奇怪啊！
语雀截图：
![11](https://user-images.githubusercontent.com/31163874/122358071-e0433400-cf86-11eb-8a8b-2dd08e9adb3e.png)

**Comment by Kenshin** [comment]
@baby1128 

估计语雀对外链的图片做了优化，而 Github 就原始的显示方案。

**Comment by baby1128** [comment]
@Kenshin 
好吧，看来只能手动处理了。谢谢~

**Comment by baby1128** [comment]
@Kenshin 
回头再看看，如果还出现，我就自己保存图片下来进行替换吧。。。谢谢了！

**Comment by Kenshin** [comment]
@baby1128 

哈哈，没问题。但应该很难再次发生类似的事情了。（除了你以外没有其他用户反馈过类似的问题。  😅

**Comment by binsee** [comment]
> 估计语雀对外链的图片做了优化，而 Github 就原始的显示方案。

其实语雀和github对于markdow中的图片，都是使用了其自家的服务器做中转缓存的

- github： https://camo.githubusercontent.com/**
- 语雀： https://www.yuque.com/api/filetransfer/images?url=**

测试了下，是github这个中转缓存服务出了问题，可能是缓存命中问题，或者是请求被知乎图床给短暂阻止导致未能缓存到图。毕竟是海外服务器访问国内，访问超时也可能。
此问题无解，只能等github优化。

**Comment by binsee** [comment]
经过深入调查，补充更多细节：

## github上遇到的情况

github上使用了图像代理服务 [camo](https://github.com/atmos/camo) ，来代理所有在github上非github域的媒体文件，目的是提供安全的方式加载混合内容（图片等）。

在github上无法加载的图片，其camo链接为：https://camo.githubusercontent.com/b9c1bb3ab903a4e68812091f4d048b303cc9e0e35e67329d9de17750e48ef165/68747470733a2f2f706963342e7a68696d672e636f6d2f76322d32303865336166636362343037326264393537366266376331326466386639345f722e6a70673f736f757263653d3139343065663563

直接打开，发现服务器回复的不是图片，而是文字报错信息：`Non-Image content-type returned` ，即：返回的 `content-type` 不包含图片，也就是说github的camo服务从图片服务器加载图片时，服务器返回的数据类型不是图片格式的。

## 现在看看知乎这边

知乎上图片使用了懒加载，懒加载中有两种图片url，一种是原图，一种是缩略图（引用）

以一个在github上无法加载的图片举例
![image](https://user-images.githubusercontent.com/5285894/122555402-d562cf00-d06c-11eb-9a4e-c4b6d0ee1189.png)

原始页面中的图片元素代码：

```html
<figure data-size="normal">
	<noscript>
		<img src="https://pic1.zhimg.com/50/v2-208e3afccb4072bd9576bf7c12df8f94_hd.jpg?source=1940ef5c" 
		data-rawwidth="1295" data-rawheight="828" data-size="normal" 
		data-default-watermark-src="https://pic2.zhimg.com/50/v2-ba35f526ba9af03ca9c0fda138a13dcf_hd.jpg?source=1940ef5c" 
		class="origin_image zh-lightbox-thumb" width="1295" 
		data-original="https://pic1.zhimg.com/v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c"/>
	</noscript>
	<img src="data:image/svg+xml;utf8,&lt;svg xmlns=&#39;http://www.w3.org/2000/svg&#39; width=&#39;1295&#39; height=&#39;828&#39;&gt;&lt;/svg&gt;" data-rawwidth="1295" data-rawheight="828" data-size="normal" 
	data-default-watermark-src="https://pic2.zhimg.com/50/v2-ba35f526ba9af03ca9c0fda138a13dcf_hd.jpg?source=1940ef5c" 
	class="origin_image zh-lightbox-thumb lazy" width="1295" 
	data-original="https://pic1.zhimg.com/v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c" 
	data-actualsrc="https://pic1.zhimg.com/50/v2-208e3afccb4072bd9576bf7c12df8f94_hd.jpg?source=1940ef5c"/>
</figure>
```

简悦阅读模式下的图片元素代码：

```html
<figure data-size="normal">
	<div class="sr-rd-content-center">
		<img class="" src="https://pic1.zhimg.com/v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c">
	</div>
</figure>
```

可以看到在原始页面中图片的两种url为：

- https://pic1.zhimg.com/50/v2-208e3afccb4072bd9576bf7c12df8f94_hd.jpg?source=1940ef5c
- https://pic1.zhimg.com/v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c

通过curl分别下载文件，其输出如下： （仅截取有用的meta部分信息）

```cmd
Z:\>curl -vv https://pic1.zhimg.com/50/v2-208e3afccb4072bd9576bf7c12df8f94_hd.jpg?source=1940ef5c
> GET /50/v2-208e3afccb4072bd9576bf7c12df8f94_hd.jpg?source=1940ef5c HTTP/1.1
> Host: pic1.zhimg.com
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Tengine
< Content-Type: image/jpeg
< Content-Length: 29710
< Connection: keep-alive
< Date: Fri, 25 Dec 2020 07:44:18 GMT
< x-oss-request-id: 5FE5985261981A383964FC65
< x-oss-cdn-auth: success
< ETag: "208E3AFCCB4072BD9576BF7C12DF8F94"
< Last-Modified: Sat, 25 Jan 2020 01:10:07 GMT
< x-oss-object-type: Normal
< x-oss-storage-class: Standard
< x-oss-version-id: null
< x-oss-server-time: 113
< x-oss-hash-crc64ecma: 6417278555807076460
< Ali-Swift-Global-Savetime: 1608882258
< Via: cache41.l2cn2180[0,0,200-0,H], cache18.l2cn2180[1,0], cache2.cn1377[0,0,200-0,H], cache15.cn1377[2,0]
< Age: 15133634
< X-Cache: HIT TCP_MEM_HIT dirn:12:124971714
< X-Swift-SaveTime: Wed, 16 Jun 2021 15:01:19 GMT
< X-Swift-CacheTime: 31104000
< Access-Control-Max-Age: 2592000
< X-CDN-PROVIDER: alibaba
< Cache-Control: public, max-age=31536000
< Access-Control-Allow-Origin: *
< Timing-Allow-Origin: *
< EagleId: 2463e42316240158926015918e

Z:\>curl -vv https://pic1.zhimg.com/v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c
> GET /v2-208e3afccb4072bd9576bf7c12df8f94_r.jpg?source=1940ef5c HTTP/1.1
> Host: pic1.zhimg.com
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Tengine
< Content-Type: application/octet-stream
< Content-Length: 170447
< Connection: keep-alive
< Accept-Ranges: bytes
< Date: Thu, 25 Mar 2021 12:06:54 GMT
< ETag: "208e3afccb4072bd9576bf7c12df8f94"
< Last-Modified: Sat, 05 Dec 2020 16:54:11 GMT
< x-cos-hash-crc64ecma: 2362538020500800089
< x-cos-request-id: NjA1YzdjZGVfNmFiNzJhMDlfMTRlNTJfMzNiNzYw
< Ali-Swift-Global-Savetime: 1616674014
< Via: cache16.l2cn2180[0,7,200-0,H], cache29.l2cn2180[8,0], cache20.cn1377[0,0,200-0,H], cache12.cn1377[1,0]
< Age: 7341897
< X-Cache: HIT TCP_MEM_HIT dirn:12:266972746
< X-Swift-SaveTime: Wed, 16 Jun 2021 15:01:21 GMT
< X-Swift-CacheTime: 31104000
< Access-Control-Max-Age: 2592000
< X-CDN-PROVIDER: alibaba
< Cache-Control: public, max-age=31536000
< Access-Control-Allow-Origin: *
< Timing-Allow-Origin: *
< EagleId: 2463e42016240159117433000e
```

对比输出的数据：
![image](https://user-images.githubusercontent.com/5285894/122563336-a9e4e200-d076-11eb-992e-43e508f4b361.png)

可以看到，缩略图（url中包含 `_hd.jpg`）返回的内容类型是图片格式，而原图（url中包含`_r.jpg`）返回的内容类型是二进制数据流，未指定为图片。
而github的camo服务，在加载数据时根据 `content-type` 判断数据是非图片的，因此终止加载数据，而用户端看到的就是图片无法加载。

但是，有意思的是，在github上，部分图片是可以加载的，比如这个： 
- https://pic2.zhimg.com/v2-1cc00aa20bf9d330e16a8a4072d875fa_r.jpg?source=1940ef5c
- 其camo链接为： 
 https://camo.githubusercontent.com/41549b865b36a2700136863d1afa7cba039d207aa6457a103108c563c137074c/68747470733a2f2f706963322e7a68696d672e636f6d2f76322d31636330306161323062663964333330653136613861343037326438373566615f722e6a70673f736f757263653d3139343065663563

知乎页面加载图片的Network截图：
![image](https://user-images.githubusercontent.com/5285894/122569701-98530880-d07d-11eb-9ed6-6bc942486bae.png)


### 图片资源规律

- 静态图片带 `_hd` 是缩略图，带 `_r` 是带水印的大图（相当于原图），文件尺寸
- 动态图片 gif 都是带 `_hd.gif` 的

问题：

通过观察Network记录，发现无论是 `_hd` 或者 `_r` 都有二进制数据流的，没有统一规则，简直头疼。

## 最后

通过查阅一些资料，这个应该是知乎用的oss图床方面的问题，如果向oss上传时能指定 `mime`，这样应该就可以解决了，但知乎自家站点内加载这些图片是没有问题的，他们哪来动力来改这个呢？
ps：知乎好像是用了阿里云和百度云的oss和cdn。


参考： 
- [图片Content-Type的那些事 - 知乎](https://zhuanlan.zhihu.com/p/147865585)

**Comment by baby1128** [comment]
@binsee 
大佬腻害！！！赞赞赞！！！
确实，github是有部分图片可以显示，但是上周我还发现出现个很无语的情况，同样的内容，我第一次备份到github，ABCD（用字母代替图片序号）显示，EFGH不能显示。我删除后再重新导github，BCD显示，AEFGH不能显示了。
通过你的分析，感觉知乎太不稳定了，但是对语雀（其他没测试过，不知道具体情况）又能全部正常支持图片显示，差别太大了了。目前我是一个一个图片保存下来进行替换的。

**Comment by baby1128** [comment]
后续告知一下：我按照上面的解决方案未能解决。还是一样的情况。
所以我是下载图片下来，自己一个一个重新传的！
