### ISSUE TITLE
导出PDF(非调用打印机)方式，显示调用失败，试了好几次都不行

### ISSUE THREAD

**Issue by WanpengMA** [Kenshin/simpread#2388]
![image](https://user-images.githubusercontent.com/48076006/122146769-31213280-ce8a-11eb-93bf-8c18bd76389b.png)

**Comment by Kenshin** [comment]
嗨，请告知 URL  否则我没办法 Check （如因隐私问题，请通过 Github 找到我的  Email 并附上此 Issues id 给我。

**Comment by Kenshin** [comment]
一些简单的提示：

1. 使用稍微正常/简单些的页面测试，如 https://sspai.com/post/67074
2. 请告知具体操作步骤

**Comment by WanpengMA** [comment]
抱歉，刚刚看到邮件，我下午重新下载了同步助手，可能是我之前没有链接好的缘故，就是没有在简悦插件设置页面和同步助手链接，现在已经正常了，谢谢你

**Comment by WanpengMA** [comment]
这完全是我个人的误操作，谢谢你

**Comment by Kenshin** [comment]
> 这完全是我个人的误操作，谢谢你

嗨，没关系，搞定就好，我关闭这个 issues ~
