### ISSUE TITLE
同步助手被Microsoft Defender阻止使用

### ISSUE THREAD

**Issue by RichardUSTC** [Kenshin/simpread#2389]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge 91.0.864.48**

- 简悦版本 **2.0.0**

- 发生问题的地址

**请描述你的问题**
在最新的Windows 10上，简悦同步助手1.0.1 win64版本被Microsoft Defender阻止使用。首先Defender弹窗告知是未知的软件发行者，选择 仍然执行 之后提示无法找到文件。随后不久，exe文件被Defender自动清除。下载地址为简悦帮助文档中的OneDrive链接 https://1drv.ms/u/s!Aua4SNl3dUARh0iLAigvKGbGEHMz?e=LJe6f3。
**截图**

**Comment by Kenshin** [comment]
嗨，如果是通过 [正规渠道下载](http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd) 的话，**请不用理会此问题**，细节可以看 https://github.com/Kenshin/simpread/issues/2168#issuecomment-844655287

另外，也可以试试 32 位系统，看看能否解决误报的问题。
