### ISSUE TITLE
无法从插件中心添加插件

### ISSUE THREAD

**Issue by Freedom-Critical-Code** [Kenshin/simpread#2392]
- 操作系统 windows

- 浏览器版本 .Edge 91.0.864.48

- 简悦版本 **2.2.0.520**

- 发生问题的地址： 插件内

**无法在插件中心添加插件**

https://user-images.githubusercontent.com/74477934/122161285-03e17e00-cea4-11eb-96fb-908b0149a0bf.MP4

**Comment by Kenshin** [comment]
嗨，可以试试 https://github.com/Kenshin/simpread/discussions/1696 提供的解决方案。
