### ISSUE TITLE
导出离线html格式出现错误，导出的文件是个没有扩展名的文件，需要手动改名

### ISSUE THREAD

**Issue by Superhedgehoger** [Kenshin/simpread#2393]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？
如无法解决，请提供 URL

**Comment by Superhedgehoger** [comment]
你好开发者，谢谢你的回复，试了一下还是不可以 最近几个月都有这个问题，我认为问题不在网站上
URL是：https://sspai.com/post/66840
使用导出为离线Html功能后 文件名为 5daec1aa-c90f-4388-af23-f887290c1fe3 没有扩展名



***@***.***
 
发件人： Kenshin Wang
发送时间： 2021-06-16 16:16
收件人： Kenshin/simpread
抄送： Superhedgehoger; Author
主题： Re: [Kenshin/simpread] 导出离线html格式出现错误，导出的文件是个没有扩展名的文件，需要手动改名 (#2393)
嗨，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？
如无法解决，请提供 URL

**Comment by Superhedgehoger** [comment]
我安装了Chrono插件


***@***.***
 
发件人： ***@***.***
发送时间： 2021-06-16 17:29
收件人： Kenshin/simpread
主题： Re: Re: [Kenshin/simpread] 导出离线html格式出现错误，导出的文件是个没有扩展名的文件，需要手动改名 (#2393)
你好开发者，谢谢你的回复，试了一下还是不可以 最近几个月都有这个问题，我认为问题不在网站上
URL是：https://sspai.com/post/66840
使用导出为离线Html功能后 文件名为 5daec1aa-c90f-4388-af23-f887290c1fe3 没有扩展名



***@***.***
 
发件人： Kenshin Wang
发送时间： 2021-06-16 16:16
收件人： Kenshin/simpread
抄送： Superhedgehoger; Author
主题： Re: [Kenshin/simpread] 导出离线html格式出现错误，导出的文件是个没有扩展名的文件，需要手动改名 (#2393)
嗨，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？
如无法解决，请提供 URL

**Comment by Kenshin** [comment]
> 我安装了Chrono插件

跟它有关系，我可以确定了。

**Comment by Superhedgehoger** [comment]
问题居然这么解决了 
没有这封信我还真没想到是别的插件的问题
我先改改设置 再尝试一下 实在不行就关了Chrono插件
感谢！



***@***.***
 
发件人： Kenshin Wang
发送时间： 2021-06-16 18:08
收件人： Kenshin/simpread
抄送： Superhedgehoger; Author
主题： Re: [Kenshin/simpread] 导出离线html格式出现错误，导出的文件是个没有扩展名的文件，需要手动改名 (#2393)
我安装了Chrono插件
跟它有关系，我可以确定了。

**Comment by Kenshin** [comment]
哈哈，搞定就好，因为 nnnn 久之前有用户问过类似的问题，所以我有印象。

我关闭这个 Issues 了~
