### ISSUE TITLE
[需求建议] 可否增加修改标题功能？

### ISSUE THREAD

**Issue by baby1128** [Kenshin/simpread#2394]
在保存内容到github后，标题带有“/”或者“\”，会自动建立文件夹，然后再进行存储，标题变成2段了。
原标题是：【Win10】Win10 系统如何打开/关闭护眼模式
![11](https://user-images.githubusercontent.com/31163874/122182685-1320f580-cebd-11eb-983d-b1d5c3949a97.png)
![22](https://user-images.githubusercontent.com/31163874/122182700-174d1300-cebd-11eb-86a8-43351c0aef80.png)

PS：带有“\”的也是这样，我把内容给删了，忘记截图，

**Comment by baby1128** [comment]
解决了，谢谢~

**Comment by Kenshin** [comment]
嗨，搞定就好，我关闭这个 issues 了
