### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by 1332987** [Kenshin/simpread#2397]
- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html>

**请描述你的问题**
中文乱码
**截图**

![image](https://user-images.githubusercontent.com/40618162/122321697-d7d30500-cf56-11eb-831e-8b550f8a8553.png)

**Comment by Kenshin** [comment]
嗨，重启浏览器即可。
