### ISSUE TITLE
阅读模式下 顶部进度条会被图片遮挡

### ISSUE THREAD

**Issue by Phantr4x** [Kenshin/simpread#24]
目前在 **少数派** 发现这个问题，
截图所在文章链接：[https://sspai.com/post/39495](https://sspai.com/post/39495)

![image](https://user-images.githubusercontent.com/5728981/27330748-55afd9a4-55ed-11e7-9e9f-dadb133d09f4.png)

**Comment by Kenshin** [comment]
感谢反馈 ，的确有这个问题。 😱
新版 1.0.1 会有选项隐藏 阅读进度 的功能，之前很多人反应这个功能比较碍眼…

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`，
解决办法：可以将此 ` 阅读进度` 隐藏。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
