### ISSUE TITLE
简悦同步助手1.0.1版有木马病毒

### ISSUE THREAD

**Issue by wf** [Kenshin/simpread#2400]
**发生问题的环境**

> 简悦的版本

- 操作系统 **Windows 10**

- 浏览器版本 **Microsoft Edge 版本 91.0.864.48 (官方内部版本) (64 位)**

- 简悦助手版本 **简悦 · 同步助手 1.0.1**

**问题**

> 在腾讯微云 https://share.weiyun.com/S8C1bxJ7
下载的1.01的win64版有**木马病毒**，请解决！

**截图**
![image](https://user-images.githubusercontent.com/248352/122349072-7030b000-cf7e-11eb-84f4-57f88914a535.png)

![image](https://user-images.githubusercontent.com/248352/122351124-6c9e2880-cf80-11eb-9dd5-26730007b848.png)

> 一图胜千言

**Comment by Kenshin** [comment]
嗨，这不是木马，而是误报，Windows Defender 的可信度...

细节可以看 https://github.com/Kenshin/simpread/discussions/2129#discussioncomment-876560
