### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by szheng0212** [Kenshin/simpread#2404]
发生问题的地址: <http://www.junshilei.cn/n/drspath/book/base/13227816/0c446861cbea45f48d17a0609d135c33/577460c608cc7a0580ac71f03df8d5aa.shtml?bt=2021-06-17

**Comment by Kenshin** [comment]
嗨，抱歉我没有打开你提供的页面，另外看了这个主网站，也没法打开...

我先关闭这个 Issues 了，请告知细节后可随时开启它。
