### ISSUE TITLE
正在看文章和标注，选择了一下导出方式，让我刷新生效，刷新后什么标注都没了！！！！！

### ISSUE THREAD

**Issue by suerb** [Kenshin/simpread#2408]
正在看文章和标注，选择了一下导出方式，（还没导出，点了没反应）

让我刷新生效，刷新后什么标注都没了！！！！！

**Comment by suerb** [comment]
万字长文+标注，一刷新全没了，我怎么再相信你们这个插件？？？

**Comment by suerb** [comment]
我是高级帐户

**Comment by Kenshin** [comment]
> 让我刷新生效，刷新后什么标注都没了！！！！！

你肯定是做了选项页中选项的操作造成的，否则不会提示让你刷新。
