### ISSUE TITLE
知乎阅读页面无法解析

### ISSUE THREAD

**Issue by ShawnPost** [Kenshin/simpread#241]

**Comment by Kenshin** [comment]
我在外面，暂时无法确认，请问是知乎的问答页面吗？
一般情况下，都可以通过 站点编辑器搞定。

**Comment by Kenshin** [comment]
我随便打开了一个页面 https://www.zhihu.com/question/58664107 并没有发生你说的情况，请告知具体 URL

**Comment by pplps** [comment]
知乎专栏也提示无法启用。
附link——https://zhuanlan.zhihu.com/p/33759668

**Comment by Kenshin** [comment]
@pplps 
什么情况，我没有发现问题，请问你的简悦是什么版本？

![image](https://user-images.githubusercontent.com/81074/37550596-d8c92320-29ca-11e8-9e87-8a42f4f67ea1.png)

**Comment by pplps** [comment]
@Kenshin 
相关信息如图
![2018-03-17_215851](https://user-images.githubusercontent.com/5857781/37556266-8d6f4882-2a2e-11e8-9ec5-e3b290a5ed8a.png)
![2018-03-17_215751](https://user-images.githubusercontent.com/5857781/37556269-97aeef28-2a2e-11e8-8dfd-cad203f7b790.png)

**Comment by Kenshin** [comment]
真是奇怪...
请确认站点编辑器的内容为如下：
![image](https://user-images.githubusercontent.com/81074/37572959-95e49c68-2b4d-11e8-915c-e6e82cd93b9a.png)

**Comment by pplps** [comment]
@Kenshin 
内容相同，一开始以为是adblock的原因，关了之后还是这样。难道是因为我的系统和Chrome都是英文的原因吗？
![44](https://user-images.githubusercontent.com/5857781/37577760-0979e61c-2b6f-11e8-92de-4ae93252ab49.png)

**Comment by Kenshin** [comment]
没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊 
另外，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8)
