### ISSUE TITLE
如何打开本地txt

### ISSUE THREAD

**Issue by 836467095** [Kenshin/simpread#2413]

**Comment by Kenshin** [comment]
嗨，看下图

进入 `chrome://extensions` → 找到简悦 → 详细信息

![image](https://user-images.githubusercontent.com/81074/122703263-bbe7a000-d283-11eb-823d-c546393b40a1.png)

**Comment by 836467095** [comment]
感谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 如何打开本地txt (#2413)





 
嗨，看下图
 
进入 chrome://extensions → 找到简悦 → 详细信息

**Comment by Kenshin** [comment]
👌  搞定就好
