### ISSUE TITLE
建议 Safari 阅读模式「点击空白退出」可更改

### ISSUE THREAD

**Issue by Colin-XKL** [Kenshin/simpread#2414]
**问题：**  
设置页面中 点击空白处退出遮罩 设置项无效

**环境信息：**  
Mac OS Big Sur
简阅浏览器插件 最新版
Microsoft Edge

**Comment by Kenshin** [comment]
嗨，我测试了下应该是没问题的，你能稳定复现？或者说仅某个页面无效？

**Comment by Colin-XKL** [comment]
emmm那可能是那个插件的问题？我日常使用那个 safari阅读模式样式 那个插件。

我再测下
------
邮件发自我的iPhone，如有格式问题请见谅

在 2021年6月21日，11:29，Kenshin Wang ***@***.***> 写道：

﻿

嗨，我测试了下应该是没问题的，你能稳定复现？或者说仅某个页面无效？

**Comment by Kenshin** [comment]
你是进入阅读模式后点击空白？还是聚焦模式？

**Comment by Colin-XKL** [comment]
阅读模式
使用的插件是这个 https://simpread.ksria.cn/plugins/details/tbjTx33iAA

具体表现为点击下图中的灰色区域，就会跳出阅读模式，任何页面都可稳定复现，设置项无效。
![img](https://s1.ax1x.com/2020/07/01/NTRbHP.md.png)

**Comment by Kenshin** [comment]
> 具体表现为点击下图中的灰色区域，就会跳出阅读模式，任何页面都可稳定复现，设置项无效。

下图已经是在阅读模式了，点击灰色部分后出现什么？（正常应该是退出阅读模式）

**Comment by Colin-XKL** [comment]
点击灰色部分后跳出阅读模式。
但是问题在于，设置项里面的 点击空白处退出遮罩 这个设置项对此无效。无论这个设置项是开还是关，上图中点击灰色区域都会退出阅读模式。
我期望的功能是可以设定点击灰色区域不要退出阅读模式，因为经常需要选中复制大段文本啥的，有时候会不小心点到灰色区域。

**Comment by Kenshin** [comment]
> 点击灰色部分后跳出阅读模式。
> 但是问题在于，设置项里面的 点击空白处退出遮罩 这个设置项对此无效。无论这个设置项是开还是关，上图中点击灰色区域都会退出阅读模式。
> 我期望的功能是可以设定点击灰色区域不要退出阅读模式，因为经常需要选中复制大段文本啥的，有时候会不小心点到灰色区域。

晕... 你之前的描述是有歧义的，绕了这么大一个圈...

你说的这个功能是聚焦模式的。

![image](https://user-images.githubusercontent.com/81074/122709927-d3c62080-d291-11eb-94fd-71fcba668dd4.png)

而下图的功能是阅读模式...

![image](https://user-images.githubusercontent.com/81074/122709954-e04a7900-d291-11eb-8e04-14520fc02906.png)

***

至于点击灰色退出是这个插件自带的功能。

当然，我会考虑你的建议。

**Comment by Colin-XKL** [comment]
好吧🤣怪不得一直不生效
还是希望后面的版本能实现点击灰色区域不退出阅读模式😃，谢谢啦


------
邮件发自我的iPhone，如有格式问题请见谅

在 2021年6月21日，13:10，Kenshin Wang ***@***.***> 写道：

﻿

点击灰色部分后跳出阅读模式。
但是问题在于，设置项里面的 点击空白处退出遮罩 这个设置项对此无效。无论这个设置项是开还是关，上图中点击灰色区域都会退出阅读模式。
我期望的功能是可以设定点击灰色区域不要退出阅读模式，因为经常需要选中复制大段文本啥的，有时候会不小心点到灰色区域。

晕... 你之前的描述是有歧义的，绕了这么大一个圈...

你说的这个功能是聚焦模式的。

[image]<https://user-images.githubusercontent.com/81074/122709927-d3c62080-d291-11eb-94fd-71fcba668dd4.png>

而下图的功能是阅读模式...

[image]<https://user-images.githubusercontent.com/81074/122709954-e04a7900-d291-11eb-8e04-14520fc02906.png>

________________________________

至于点击灰色退出是这个插件自带的功能。

当然，我会考虑你的建议。

**Comment by Kenshin** [comment]
@Colin-XKL 

哈哈，下个版本修复后会在这里通知你~

**Comment by Kenshin** [comment]
嗨，Safari 插件更新到 0.0.4 

> 增加了 点击空白处自动退出阅读模式（可更改）

![image](https://user-images.githubusercontent.com/81074/124221582-a2234400-db32-11eb-95ba-87be6bf4a0fd.png)

![image](https://user-images.githubusercontent.com/81074/124221619-b36c5080-db32-11eb-8ff5-5d69173a264c.png)

细节请看这里 https://github.com/Kenshin/simpread/issues/823 请通过下图方式更新

![image](https://user-images.githubusercontent.com/81074/124222190-db0fe880-db33-11eb-9e77-7a9650c39b13.png)

**Comment by Colin-XKL** [comment]
ヾ(≧∇≦谢谢≧∇≦)ノ


在 2021年7月2日，12:49，Kenshin Wang ***@***.***> 写道：

﻿

嗨，Safari 插件更新到 0.0.4

增加了 点击空白处自动退出阅读模式（可更改）

[image]<https://user-images.githubusercontent.com/81074/124221582-a2234400-db32-11eb-95ba-87be6bf4a0fd.png>

[image]<https://user-images.githubusercontent.com/81074/124221619-b36c5080-db32-11eb-8ff5-5d69173a264c.png>

细节请看这里 #823<https://github.com/Kenshin/simpread/issues/823> 请通过下图方式更新

[image]<https://user-images.githubusercontent.com/81074/124222190-db0fe880-db33-11eb-9e77-7a9650c39b13.png>
