### ISSUE TITLE
文章导出印象笔记后，阅读标注没有生效

### ISSUE THREAD

**Issue by wolffy1998** [Kenshin/simpread#2415]
## 运行环境：
    windows10+Edge+简悦2.0

### 说明：
    我在知乎看到一篇文章通过简悦打开阅读，并对上面的内容进行高亮标注，之后再保存到印象笔记。文章已经保存成功了但是原来的标注没有生效，已经在设置中开启了全文+标注导出功能。

**Comment by Kenshin** [comment]
嗨，这是正常的。

因为印象笔记对 HTML 支持有它自己的一套逻辑：ENML，所以基本上是无法支持标注的。
成完美的成功导入到印象笔记已经「很不错」了。  😂
