### ISSUE TITLE
微信公众号导出为 TextBundle 没有图片（因图片 URL 导致正则失败）

### ISSUE THREAD

**Issue by Allwillcome** [Kenshin/simpread#2418]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows **

- 浏览器版本 **e.g. Chrome 版本 91.0.4472.106（正式版本） （64 位）**

- 简悦版本 **最新版本**

- 发生问题的地址 <https://mp.weixin.qq.com/s/lHueOs0mcVEqQyUSQQsjcA>

**请描述你的问题**

> 导出公众号文章为 textbundle，没有图片信息

**截图**
typora 可以显示图片，但和直接保存图片是一样的，而不是像少数派文章导出一样，有个包含图片的文件夹
少数派文章抓取正常
![image](https://user-images.githubusercontent.com/35840764/122788211-af496300-d2e8-11eb-9190-9780769438c3.png)

下面是公众号文章导出显示
![image](https://user-images.githubusercontent.com/35840764/122788152-a193dd80-d2e8-11eb-8266-1c26531cfcd0.png)

![image](https://user-images.githubusercontent.com/35840764/122788032-7f01c480-d2e8-11eb-9bc5-10b51ad14036.png)

**Comment by Kenshin** [comment]
嗨，谢谢提示，确实有这个问题。

应该是这个订阅号里面的图片 URL 地址太特殊导致在生成 Textbundle 时正则失败没有保存图片造成的。

修复后会通知你。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 修复了导出 Textbundle 错误

新版解决了这个问题。😄

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
