### ISSUE TITLE
UI--按钮--的一些建议

### ISSUE THREAD

**Issue by HisenZhang** [Kenshin/simpread#242]
1. 把"退出"按钮和其他的按钮都调成黑白灰色调... 屏幕上一个大红点看着真的很难受... "色彩艳丽" 对于追求简洁明快的一个应用来说 有些花哨.
2. 或者, 把菜单改成快捷键呼出/鼠标移到窗口右下侧呼出.

还有个操作方面的建议
就是把所有的设置都放到extension bar 里面  
要么 全部用快捷键,就像Vim. 好处是高效,坏处是学习曲线陡峭

谢谢有这么个项目, 集成了大量之前使用的extension功能.

**Comment by Kenshin** [comment]
感谢建议～
控制栏可以全部隐藏（也就是你说的方式）

目前支持快捷键，详细看说明文档。 😃

**Comment by HisenZhang** [comment]
Get it. Thanks man.
