### ISSUE TITLE
填入UUID提示格式错误

### ISSUE THREAD

**Issue by YangWaldon** [Kenshin/simpread#2421]
授权我的高级账户的时候，填入密钥，我的理解是填入UUID，但是老是提示格式错误，，，，到底什么是密钥，什么是UUID,我就登陆一下，有必要搞的这么复杂吗？
折腾一番后，终于登陆上我的高级账户了，同步助手我也下载了，但是为什么这里不显示自动同步切换选项？
![image](https://user-images.githubusercontent.com/49675185/122863940-4d274700-d356-11eb-8511-b435a1d5f202.png)
还有我已经按照要求把导出PDF的选项都打开了，插件选项和同步助手选项都设置好了，为什么还是不能导出PDF?
一个插件，功能太庞杂了，折腾了一天也没搞明白这中间的原理

**Comment by Kenshin** [comment]
首先，简悦不是一个扩展，只是目前的部分功能在浏览器而已。

至于你说的自动同步问题，可以看 http://ksria.com/simpread/docs/#/自动同步 

***

一个建议，如果遇到配置上的问题，可以进入 http://ksria.com/simpread/docs/ 然后左上角进行搜索，如你搜索 手动同步，对应的内容中会找到自动同步的说明。（当然最好的方式还是搜索 **自动同步**

![image](https://user-images.githubusercontent.com/81074/122866255-37b41c00-d35a-11eb-9d2b-8bc9791a9a33.png)
