### ISSUE TITLE
访问 BBC 中文网会移除所有正文内容（附解决方案）

### ISSUE THREAD

**Issue by waynerv** [Kenshin/simpread#2424]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Chrome 91.0.4472.106**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://www.bbc.com/zhongwen/simp

**请描述你的问题**

仅启用简悦扩展，访问BBC中文网会移除所有的正文内容；禁用扩展后打开正常。

**截图**

![image](https://user-images.githubusercontent.com/39515546/122873719-b1e99e00-d364-11eb-8379-436fbbc97095.png)

**Comment by Kenshin** [comment]
晕，BBC 也有个问题... 你这样做就能解决

### 方案一

> 把 `bbc.com` 加入到 [黑名单](http://ksria.com/simpread/docs/#/URL%E7%BC%96%E8%BE%91%E5%99%A8?id=%e9%bb%91%e5%90%8d%e5%8d%95)

> 使用后，BBC 的页面无法进入阅读模式

![image](https://user-images.githubusercontent.com/81074/122877474-39d1a700-d369-11eb-8422-ebfd974b7e42.png)


### 方案二

> 禁用 解析惰性图片 选项，如下图：

> 使用后，没有适配的页面，在包含图片惰性加载时无法成功解析。

![image](https://user-images.githubusercontent.com/81074/122877684-769d9e00-d369-11eb-991c-4885a776292e.png)
