### ISSUE TITLE
[BUG]币安文章阅读模式下无法加载图片

### ISSUE THREAD

**Issue by mephisX** [Kenshin/simpread#2427]
- 操作系统 Windows 10 21H1

- 浏览器版本 版本 91.0.864.54 (官方内部版本) (64 位)

- 简悦版本 2.2.0.520

- 发生问题的地址 <https://academy.binance.com/zh/articles/zk-snarks-and-zk-starks-explained>

**请描述你的问题**

> 无法加载图片

**截图**

> ![image](https://user-images.githubusercontent.com/30206556/122948315-67d8da80-d3ad-11eb-8d58-f03d2c6d57fd.png)
![image](https://user-images.githubusercontent.com/30206556/122948361-71624280-d3ad-11eb-9fc3-694e8b752e59.png)

**Comment by binsee** [comment]
这个网站未经适配，图片采用了惰性加载方式，在未浏览到图片时不会加载，直接进入阅读模式会无法显示。
你可以打开试验性功能 `预加载惰性加载图片`，即可解决，但目前此功能已知一些问题，在特定情况下会产生某些副作用，下个版本会修复。
当前可根据自己需要选择。
