### ISSUE TITLE
大纲视图 字体非常小

### ISSUE THREAD

**Issue by HisenZhang** [Kenshin/simpread#243]
如图↓ 页面200% scaling
![image](https://user-images.githubusercontent.com/22415299/36583390-848d9410-18b0-11e8-968e-d753dde40bc8.png)

**Comment by Kenshin** [comment]
感谢反馈，估计 CSS 被污染了，请告知具体 URL。

**Comment by HisenZhang** [comment]
100%时候也是很小的字. 
这是Wiki的英文站
URL https://en.wikipedia.org/wiki/Sweet_Bird_of_Youth

很抱歉本人不怎么会前端, 代码帮不太上, 只能给些建议

**Comment by Kenshin** [comment]
客气哈，修复后贴会通知你。 😃

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
1.1.1 将 TOC 转移到了左侧，解决了偶尔被遮挡的问题。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
