### ISSUE TITLE
你好，乱码问题

### ISSUE THREAD

**Issue by merroneutron** [Kenshin/simpread#2430]
- 操作系统 **
- windows10

- 浏览器版本 **
- chrome

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

稍后读页面一部分内容乱码

**截图**
![image](https://user-images.githubusercontent.com/44427799/123060116-07917980-d43d-11eb-99b0-31af61470b1b.png)

**Comment by Kenshin** [comment]
嗨，重启浏览器即可。
