### ISSUE TITLE
更新到2.2.0后无法授权印象笔记

### ISSUE THREAD

**Issue by ljjylll** [Kenshin/simpread#2432]
**请说明发生问题的环境**

- 操作系统 **Win64**

- 浏览器版本 **版本 91.0.864.54**

- 简悦版本 **2.2.0**

- 发生问题的地址 <extension://ndmfkjlgiiojffgellokfnfjgllebdhf/options/options.html#connect

- 补充：在使用2.1.0前期，是可以将稍后读中的标注分享到印象笔记的，但是在后期的时候就已经不能分享到印象了。现在更新到2.2.0后，连授权都不行，不知道是为什么

**Comment by Kenshin** [comment]
嗨，不会存在这个问题的... 虽然我不怎么喜欢印象笔记。

你可以**先导出配置文件**，然后重新安装简悦，用新的配置文件试试。

**Comment by liu2020xinjian** [comment]
我也遇见同样的问题，重新安装也不行了。

**Comment by Kenshin** [comment]
> 我也遇见同样的问题，重新安装也不行了。

重新安装后也无法授权吗？是不是 https://github.com/Kenshin/simpread/discussions/1567 引起的？

另外，还是那句话不存在无法导入印象笔记的情况，几乎全部这样的问题都是配置造成的。 😂

**Comment by AoZhang** [comment]
> > 我也遇见同样的问题，重新安装也不行了。
> 
> 重新安装后也无法授权吗？是不是 #1567 引起的？
> 
> 另外，还是那句话不存在无法导入印象笔记的情况，几乎全部这样的问题都是配置造成的。 😂

我也遇到了不能授权印象笔记的问题，不是 #1567 的原因。chrome 92.0.4515.159，电脑是 Macbook。

**Comment by AoZhang** [comment]
> > > 我也遇见同样的问题，重新安装也不行了。
> > 
> > 
> > 重新安装后也无法授权吗？是不是 #1567 引起的？
> > 另外，还是那句话不存在无法导入印象笔记的情况，几乎全部这样的问题都是配置造成的。 😂
> 
> 我也遇到了不能授权印象笔记的问题，不是 #1567 的原因，浏览器重启过了，简悦也重新装过。chrome 92.0.4515.159，电脑是 Macbook。
> @Kenshin 还有其它可能的原因吗？

实时证明是我的网络问题，无法访问授权链接，架上代理就ok了

**Comment by Kenshin** [comment]
@AoZhang 

嗨，谢谢提供解决方案，我把这个解决方案也放到 https://github.com/Kenshin/simpread/issues/541#issuecomment-901606863

@liu2020xinjian @ljjylll 可以看看是否是 https://github.com/Kenshin/simpread/issues/2432#issuecomment-901089154 造成的？
