### ISSUE TITLE
什么值得买文章页内嵌视频显示过小

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2442]
什么值得买 站点的文章内嵌视频尺寸过小，需要进行优化。

示例文章：https://post.smzdm.com/p/aekekon4/

- 原文内，内嵌视频显示效果：
![image](https://user-images.githubusercontent.com/5285894/123367623-d8017f00-d5ac-11eb-91d4-6424a6e826e5.png)

- 阅读模式
![image](https://user-images.githubusercontent.com/5285894/123367600-cc15bd00-d5ac-11eb-9903-1997381d06f3.png)

**Comment by Kenshin** [comment]
嗨，我关闭这个 Issues 了。
