### ISSUE TITLE
无法在阅读模式中打开微博的博文页面

### ISSUE THREAD

**Issue by seozed** [Kenshin/simpread#2444]
例如：https://weibo.com/7342904466/Klyxwv95T?ref=home&rid=5_0_202_6666681256638558166_0_0_0&type=comment

这条博文，添加到稍后阅读后，从稍后阅读列表中打开这条微博，就会提示无法解析。
但是在原文中是可以正常解析的。

![截屏2021-06-25 下午1 29 31](https://user-images.githubusercontent.com/4144227/123374286-7562b000-d5b9-11eb-8522-a365d8666028.png)
(从稍后阅读列表中无法解析)

![截屏2021-06-25 下午1 30 57](https://user-images.githubusercontent.com/4144227/123374458-bb1f7880-d5b9-11eb-955c-e1706fc435a3.png)
（在原始页面上是可以解析的）

**Comment by binsee** [comment]
嗨，我这边无法打开你提供的url，提示404。
如果你可以打开，那可能是需要登陆后才能访问的页面。对于这类需要登陆态的页面，稍后读-阅读模式是无法正常显示的，因为简悦不能获取用户的登陆态去请求页面信息。

但高级账户有变通的方法：
1. 可搭配使用同步助手，开启『加入稍后读后自动保存到本地』功能
![image](https://user-images.githubusercontent.com/5285894/123387003-dd20f700-d5c9-11eb-89f6-9c9bbb9f1423.png)
2. 然后在稍后读界面的设置中开启『优先加载本地离线文件』
![image](https://user-images.githubusercontent.com/5285894/123387137-06da1e00-d5ca-11eb-9d74-2b516152e1d5.png)
3. 之后将文章保存到稍后读，打开稍后读后即可正常显示。

**Comment by fasjflafj** [comment]
我也遇到同样的问题。用内置解析方案也不行。

url: 
https://weibo.com/1928552571/Mis1dmvka

**Comment by Kenshin** [comment]
@fasjflafj 

解决方案看这里 https://github.com/Kenshin/simpread/discussions/3515

PS：忘记关闭这个 issues 了 😂

**Comment by fasjflafj** [comment]
> @fasjflafj
> 
> 解决方案看这里 #3515
> 
> PS：忘记关闭这个 issues 了 😂

已经安装了这些适配规则，但是还是报错呀
<img width="863" alt="Snipaste_2022-12-14_16-55-14" src="https://user-images.githubusercontent.com/62693738/207551227-9583a711-7cbd-43d9-90b9-aed559d19c4d.png">
<img width="1489" alt="Snipaste_2022-12-14_16-56-14" src="https://user-images.githubusercontent.com/62693738/207551242-2bd0fc9e-8bce-43e0-9cf5-7e4d7525b501.png">

**Comment by Kenshin** [comment]
@fasjflafj 

emmm

确实如此，以为你提供的 URL 并没有包含在 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/81074/207574100-0b6e0e9f-0cb9-4c3c-b190-b6f379087c00.png">

规则中，所以你提供的 URL 是个啥（ 微博为什么这么多各种各样的 URL 规则 😂

最后一个图的问题：需要配置 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2) 才行。（链接里面有教程）

**Comment by fasjflafj** [comment]
> @fasjflafj
> 
> emmm
> 
> 确实如此，以为你提供的 URL 并没有包含在
> 
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/81074/207574100-0b6e0e9f-0cb9-4c3c-b190-b6f379087c00.png">
> 
> 规则中，所以你提供的 URL 是个啥（ 微博为什么这么多各种各样的 URL 规则 😂
> 
> 最后一个图的问题：需要配置 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2) 才行。（链接里面有教程）


这个页面是从pc端查看微博的时候的每一条微博的详情页。

比如这条：

https://weibo.com/7722844380/MjyPRfUnT

结构就是：

https://weibo.com/用户id/数据id

这个页面的进入方法是在每一条的微博上面点击发布时间（twitter类似）

<img width="1216" alt="Snipaste_2022-12-14_19-28-45" src="https://user-images.githubusercontent.com/62693738/207584128-9b64d68d-4be0-4e37-a7c1-9dac43be08c3.png">

**Comment by Kenshin** [comment]
@fasjflafj 

okay 我研究下。
