### ISSUE TITLE
购买了腾讯问卷15元的高级账户48小时内未收到邮件可兑换的通知(到现在也没有）

### ISSUE THREAD

**Issue by wwToTww** [Kenshin/simpread#2450]

**Comment by wwToTww** [comment]
![image](https://user-images.githubusercontent.com/85620715/123568102-34a3aa80-d7f6-11eb-8821-e44269e00e87.png)

**Comment by wwToTww** [comment]
邮箱为mad20121221@outlook.com

**Comment by Kenshin** [comment]
嗨，抱歉，周末外出，所以**今天晚上 19点前 会进行兑换操作**。
