### ISSUE TITLE
Chrome浏览器适配

### ISSUE THREAD

**Issue by realirissong** [Kenshin/simpread#2451]
你好，不知道是不是我自己的问题，为什么我用chrome浏览器的过程中有许多问题... 有一些墙外的网站打不开阅读模式，有的打开了不能退出、无法高亮。。。 是谷歌兼容不好吗？谢谢答复。

**Comment by Kenshin** [comment]
嗨，你说的这些「问题」肯定是不存在的。  😂  Chrome 是首选的方案，另外也没有其它方案。

你可以试试导出配置文件，然后重新安装简悦。

另外，也可以试试 **在隐身模式下，仅启用简悦** 试试。（排除其它扩展的干扰。

**Comment by realirissong** [comment]
你好！我重新装了一下，还是一样的问题...我添加了一个小视频，希望不太占用你的时间
主要就是






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] Chrome浏览器适配 (#2451)





 
嗨，你说的这些「问题」肯定是不存在的。  😂  Chrome 是首选的方案，另外也没有其它方案。
 
你可以试试导出配置文件，然后重新安装简悦。
 
另外，也可以试试 在隐身模式下，仅启用简悦 试试。（排除其它扩展的干扰。

**Comment by Kenshin** [comment]
嗨，没事的。

另外，请不要在邮件中回复，而是进入 https://github.com/Kenshin/simpread/issues/2451 提问，因为邮件中无法带视频给我。
