### ISSUE TITLE
开启代码增强插件后,csdn某个代码片段消失,之后的每段代码的位置依次上移,导致文章代码段错位

### ISSUE THREAD

**Issue by Ganzhenghao** [Kenshin/simpread#2452]
![image](https://user-images.githubusercontent.com/43715234/123569830-a6c9be80-d7f9-11eb-9716-30f695c8dc20.png)

transient Node<K,V>[] table; 这段代码消失后
其下的代码片段会依次向上补充到消失的位置 使得文章的代码段的位置错位

测试后:只有当代码增强插件开启后才会出现

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win10 x64**

- 浏览器版本 **edge 版本 91.0.864.59 (官方内部版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://blog.csdn.net/lkforce/article/details/89521318#t5>

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
