### ISSUE TITLE
web markdown格式的，没有大纲目录

### ISSUE THREAD

**Issue by creaylei** [Kenshin/simpread#2453]

**Comment by Kenshin** [comment]
嗨，md 并不支持目录功能，所以自然是没有此功能。

**Comment by creaylei** [comment]
可以markdown 也分 h1 h2这种的

**Comment by Kenshin** [comment]
> 可以markdown 也分 h1 h2这种的

emmm 我好像没理解你的意思，你是问：

> 在浏览器打开 md 然后使用简悦渲染为 html 时没有大纲？

**Comment by creaylei** [comment]
就是markdown不是有一二及标签嘛，但是使用【简悦】的时候，并没有生成大纲，这个应该是可以生成的吧

**Comment by Kenshin** [comment]
有的，查看文档 http://ksria.com/simpread/docs/#/目录

**Comment by creaylei** [comment]
![image](https://user-images.githubusercontent.com/21191525/123590715-9592a900-d81d-11eb-81f5-b04d6c823012.png)

可以看到并没有生成呢

**Comment by creaylei** [comment]
啊，不好意思，我的锅，打扰您了。   需要光标悬浮到那里，才会出现。  十分抱歉

**Comment by Kenshin** [comment]
哈，没事的。

**Comment by Kenshin** [comment]
嗨，你应该在 Webstore 评分了吧？因为这个问题根本就不存在，所以把评分改为五星吧？（否则多冤枉？  😅
