### ISSUE TITLE
B站笔记增加笔记链接

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2454]
web版B站笔记是单页应用，无法通过某url跳转到对应的笔记，因此导致多条笔记加入稍后读时会出错。之前通过修改页面hash来曲线解决了此问题。见https://github.com/Kenshin/simpread/issues/2317#issuecomment-854738559

但如此，只解决了不同的笔记加入稍后读的问题。但在稍后读中跳转原文页面，只能跳转到笔记列表，而无法直接跳转到笔记原文页面。

而B站笔记，其实是有独立链接的，只是好像仅用于app客户端，web端没有这个入口而已。

笔记页面目前如图：
![image](https://user-images.githubusercontent.com/5285894/123587593-13a08100-d819-11eb-8b8c-c07287033934.png)
url如： https://www.bilibili.com/h5/note-app?oid=248596846&oid_type=0&pagefrom=fullpage&navhide=1&-Bct.statusbar.mode=0

其url的参数中，有个oid，其实就是b站视频的av号，但现在b站全面使用了bv号，b站笔记功能界面也不例外，因此需要对此进行解决。

只要提取笔记所属视频的bv号，转换为av号，即可得到笔记原文页面的url。

但这里存在一个问题，**站点适配规则中无法修改当前页面的url，这点是否可以在后续中增加操作方式？** @Kenshin

**Comment by binsee** [comment]
@Kenshin 站点适配规则中无法修改当前页面的url，这点是否可以在后续中增加操作方式？ 

只要是为了在未来应对特殊的单页应用。
此条可以列入单独的issue，在后续版本实现。

**Comment by Kenshin** [comment]
@binsee 

哈哈，抱歉，不应该关闭这个 Issues。

**Comment by binsee** [comment]
> 哈哈，抱歉，不应该关闭这个 Issues。

关闭这个issue是没有问题的，因为已经临时解决，后边的问题应该转移到单独的issue里追踪。

**Comment by Kenshin** [comment]
> 关闭这个issue是没有问题的，因为已经临时解决，后边的问题应该转移到单独的issue里追踪。

okay，那你需要的时候，再建~
