### ISSUE TITLE
关于简悦的一些建议

### ISSUE THREAD

**Issue by xkonglong** [Kenshin/simpread#2456]
首先说明一下, 我是付费用户, 我愿意支持作者的辛苦工作. 

不过呢,  升级到2.2之后, 我在使用中, 有太多的抱怨不吐不快, 当然了, 同样作为开发者, 如果辛苦开发的软件被人抱怨,其实心情不会好受.  

但是驱使我写这些的原因, 是我觉得作者的路线错误, 如果只是单纯的bug或者建议, 也许正常反馈反而无所谓了.

---

抱怨开始:

我从没用过这么曲折、婉转、复杂、折中、妥协的软件。 

作者写了大量的帮助文件和提示消息， 而且帮助文件里各种链接以方便跳转， 但是说实话， 一个好用的软件，其实不需要大量复杂的帮助文本。 

比如同步这一项， 作者说“不收集隐私”， 所以各种同步盘折中选项，搞得人焦头烂额。 

看似选项很多， 既有坚果云，又有Dropbox，还有exe程序，但缺点是既不统一，又无法快捷切换。 

这固然是作者一步步实现的渐进过程， 又有扩展的权限无法实现的局限， 其实是缺乏总体的统筹。

大量的功能既不内置，又依靠第三方实现， 也就是说， 我如果想要实现简悦介绍的常见几个功能， 起码要具备以下几点：

1.  坚果云或者某个webdav的服务， dropbox普通用户不用考虑（需要梯子）
2. 安装作者的exe助手，需要同步的话， 还需要开机启动。
3. 如果想其他功能，还需要安装pandoc

说实话， 简悦很强大， 但是太复杂， 我有时候只需要简简单单的打开阅读模式，看看文章，有需要的转存一下，来不及看的加入稍后读， 但是呢， 一个普通用户一方面需要注册好几个服务，另一方面需要安装扩展、软件。

这些服务和扩展的配置又非常复杂，对于有些人来说，搞定webdav的密码都是有难度的。

所以， 我觉得作者设计了这么多弯路，只是为了规避没有自有服务空间这个事情。 那么， 即便基于各种原因，作者不提供这些服务，还不如整合服务后，由用户自己建服务也好，起码单就简悦这个扩展来说，也能一步到位。

**我很钦佩作者对简悦的努力，以及各种新想法和新功能， 只是希望作者能加强易用性，这样才能普惠广大用户。**

发了这么多牢骚和抱怨，有说的不对的，请大家海涵。

**Comment by Kenshin** [comment]
哈哈，没事，也谢谢你的回复，我只是把标题修改了下。

简单的回复下一些需要回复的内容：

> 简悦很强大， 但是太复杂， 我有时候只需要简简单单的打开阅读模式，看看文章，有需要的转存一下，来不及看的加入稍后读。

单纯的说这些功能是不需要「折腾的」。

至于易用性的问题，请放心，我已经在 2.2.xxxx 开始了这些内容的优化与整合。

***

> 接下来说点其它的

你可以把简悦理解为 Roam Research / Marginnote 之类的工具，虽然可以直接上手，但比较还是需要详细研究用法的，对吧。

简悦其实分为两部分：

1. 开箱即用的阅读模式 / 插件 / 稍后读 → 针对不愿意折腾的用户
2. 更强大的本地缓存功能与导出功能 → 针对有意愿折腾的用户

但目前缺失有效的引导。另外一点就是：简悦不是个新项目，而是经历了四年的产品，所以每个版本的侧重点也不同。

***

我欢迎任何形式的观点，只要以客观真实就好，**也谢谢你能写这么多内容**。 💪 

因为这个 issues 是非功能性的话，所以我关闭这个 Issues 了。
