### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by epidemic2019** [Kenshin/simpread#2459]
发生问题的地址: <https://www.toutiao.com/w/i1703137018655757/?tt_from=weixin

**Comment by Kenshin** [comment]
嗨，有个类似 https://github.com/Kenshin/simpread/issues/2458 一样的，我一起回复了

你可以使用 [手动高亮](http://ksria.com/simpread/docs/#/%E6%89%8B%E5%8A%A8%E6%A1%86%E9%80%89) 的方式
