### ISSUE TITLE
“鼠标跟随滑动浏览”不能开关吗？

### ISSUE THREAD

**Issue by packagedgalaxies** [Kenshin/simpread#246]
第一次接触，我想用传统的滚轮或数位板滚动网页。查看了高级设置页面并没发现可以设置此功能的入口。如果有，感谢告知。

**Comment by Kenshin** [comment]
「鼠标跟随滑动」
是指什么？

**Comment by packagedgalaxies** [comment]
指字面意思。已解决。问题出在第三方，不好意思。

**Comment by Kenshin** [comment]
搞定就好~

**Comment by tonnyone** [comment]
那个第三方脚本？我也有遇到这个问题，聚焦模式不能 滚动

**Comment by Kenshin** [comment]
@tonnyone 

试试 `在隐身模式下，仅启用简悦` 如果没有问题的话，看看你是否安装了某些 TOC 类的扩展。
