### ISSUE TITLE
Windows Defender 误杀 同步助手1.0.1

### ISSUE THREAD

**Issue by HellowDream** [Kenshin/simpread#2460]
Windows Defender 误杀 同步助手1.0.1

**Comment by binsee** [comment]
请使用32位版本的，那个不误报。

**Comment by Kenshin** [comment]
@HellowDream 

嗨，只要是 [官方渠道下载](https://simpread.pro/download) 的都没有问题，至于误报的细节可以看看 https://github.com/Kenshin/simpread/discussions/2129#discussioncomment-876560
