### ISSUE TITLE
medium上 加载的github代码无法在阅读模式中打开

### ISSUE THREAD

**Issue by dwSun** [Kenshin/simpread#2461]
如下链接，代码是通过 iframe加载进来的，在阅读模式无法查看。
https://medium.com/dair-ai/building-rnns-is-fun-with-pytorch-and-google-colab-3903ea9a3a79

**Comment by Kenshin** [comment]
嗨，iframe 是不会被解析的，因为会出现套娃情况。

所以我关闭这个 issues 了。
