### ISSUE TITLE
通过同步助手导出时，特殊符号的标题会导出失败

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#2466]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10**

- 浏览器版本 **Chrome 91.0**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://github.com/github/feedback/discussions/4306

**请描述你的问题**

- 文章标题含有特殊符号 `"`，使用同步助手导出为pdf，导出失败。
从同步助手返回的错误如下：

```json
{
    "status": -1,
    "error": {
        "errno": -4058,
        "code": "ENOENT",
        "syscall": "open",
        "path": "E:\\xxx\\坚果云\\SimpRead\\output\\tmp-55-3rd-party \"Tracked In\" should be less prominent · Discussion #4306 · github-feedback.feedback.html"
    }
}
```

经过测试，`"` 符号，在Win平台下为非法文件名，在macOS下为合法。

**截图**

![image](https://user-images.githubusercontent.com/5285894/123770272-c09ffa00-d8fc-11eb-9b2d-bfe99b913d1e.png)

**Comment by binsee** [comment]
更新同步助手到最新的1.0.1后，可以生成pdf，但pdf内容是非预期的

```
Error: ENOENT: no such file or directory, stat 'E:\xxx\坚果云\SimpRead\output\tmp-3rd-party Tracked In should be less prominent · Discussion .html
```

实际生成的临时文件：`tmp-3rd-party Tracked In should be less prominent · Discussion #4306 · github-feedback.feedback.html`
生成pdf时加载的文件：`tmp-3rd-party Tracked In should be less prominent · Discussion .html`

目前怀疑此问题与 #2467 的一样，是由于 `#` 符号需要被转义引发

**Comment by binsee** [comment]
> 目前怀疑此问题与 #2467 的一样，是由于 `#` 符号需要被转义引发

已经确认按此方式可以解决:

```js
//同步助手 src/main/print.js

// pdf.loadURL(url + '/' + title );
// 修改为如下：
pdf.loadURL(url + '/' + encodeURIComponent(title) );
```

**Comment by Kenshin** [comment]
收到，考虑近期升级一次同步助手。

**Comment by Kenshin** [comment]
与 #2467 一致的话，就只留一个吧。

**Comment by Kenshin** [comment]
嗨，此问题也修复了~
