### ISSUE TITLE
QQ群论坛适配

### ISSUE THREAD

**Issue by CharMingF** [Kenshin/simpread#247]
麻烦把http://qgc.qq.com/   这里的群论坛适配下吧

**Comment by Kenshin** [comment]
可以自己添加，有难度的话，我会适配后通知你，感谢反馈~

**Comment by CharMingF** [comment]
![image](https://user-images.githubusercontent.com/7530342/36929964-5abecdd8-1ed3-11e8-9728-1edc3aff04dc.png)
摸索出来了，不过字体太小了，界面的调整字体不起作用，同时自定义css好像也不起作用。

**Comment by CharMingF** [comment]
![image](https://user-images.githubusercontent.com/7530342/36929978-88ac3c26-1ed3-11e8-80e0-31c41f96c8ad.png)

**Comment by Kenshin** [comment]
我改了一下你的方案，如下：
![2018-03-03_133550](https://user-images.githubusercontent.com/81074/36930994-fe541e26-1ee7-11e8-954a-e0d1aebe87cd.png)

![2018-03-03_133532](https://user-images.githubusercontent.com/81074/36930996-022b832c-1ee8-11e8-98e1-39c434e5b78d.png)

**Comment by Kenshin** [comment]
你好，久等了，新增加  `qgc.qq.com`，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
