### ISSUE TITLE
简悦·同步助手在设置快捷键时无法识别command键

### ISSUE THREAD

**Issue by danpliu** [Kenshin/simpread#2471]
系统：macOS Big Sur 11.4
浏览器：Microsoft Edge 91.0.864.59
简悦插件版本：2.2.0.520
简悦·同步助手版本：1.0.1

**Comment by Kenshin** [comment]
嗨，目前是这样设置的，可以后续考虑支持。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 重构了快捷键的相关功能，详细说明 [稍后读快捷键](https://simpread.pro/docs/#/稍后读快捷键)。

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
