### ISSUE TITLE
稍后看页面展示的默认模式

### ISSUE THREAD

**Issue by HGladiator** [Kenshin/simpread#2478]
**一见倾心， 最好的阅读插件。五星好评走起。**

- 操作系统 **Win64**

- 浏览器版本 **e.g. Chrome 90.0.4430.85**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html>

**请描述你的问题**

1. 是否可以增加设置 【稍后看】 页面展示的默认模式， 可以自主选择 阅读模式 还是 标注模式。我喜欢默认阅读模式

**Comment by Kenshin** [comment]
哈哈，谢谢喜欢简悦，至于你说的是可以的，看下图：

![image](https://user-images.githubusercontent.com/81074/124107791-2aa0d680-da98-11eb-84da-ac2249f1b6a2.png)

**Comment by HGladiator** [comment]
这个藏得深,我把花了两小时把所有的提示和功能都看了一遍.都没看到 稍后看的这个设置. 可以的话,希望能增加一个提示.


还有一个问题, bilibili 专栏文章解析失败,[这篇文章](https://www.bilibili.com/read/cv10088316),页面提示让提Issues

**Comment by Kenshin** [comment]
哈哈，抱歉，UE 部分确实需要加强

你可以访问 http://ksria.com/simpread/docs/#/稍后读?id=选项页 里面有关于这个选项的提示。

![image](https://user-images.githubusercontent.com/81074/124211695-228c7980-db20-11eb-9c5b-58c03b206449.png)

> 还有一个问题, bilibili 专栏文章解析失败,这篇文章,页面提示让提Issues

我这边是没问题的，看看通过升级 http://ksria.com/simpread/docs/#/站点适配源?id=官方适配源 能否解决？

**Comment by HGladiator** [comment]
这么良心的开发者,果断买了支持一波, 尽管免费版远远够用了. 

适配源有 bilibili 专栏,我更新了, 可是依然无法解析, 就不知道什么原因, 

不知道是不是因为你是高级会员, 有同步助手内置解析器的原因,我还没收到key,等激活高级会员后再看看
![png](https://i.loli.net/2021/07/02/WSx9aE7s41TlZ2D.png)

**Comment by Kenshin** [comment]
谢谢，还是建议理性购买，哈哈。

> 适配源有 bilibili 专栏,我更新了, 可是依然无法解析, 就不知道什么原因,

你说是稍后读无法查看阅读吧？这是有可能的，稍后读解析需要依赖 [高级账户的同步助手](http://ksria.com/simpread/docs/#/Sync) 功能

![image](https://user-images.githubusercontent.com/81074/124216169-27552b80-db28-11eb-995d-8860f61ca4a0.png)

**Comment by binsee** [comment]
嗨，b站专栏的适配，已经有pr #2468 进行修复，待解决一个问题后就会合并入官方源发布。
如果你比较急的话，可以先在第三方适配源中导入 https://gist.githubusercontent.com/binsee/55acad05b921ba79ac6695a9463f563c/raw/59a9333475691791e7a161302f3e03851dfca50c/read.bilibili.com.json 使用

**Comment by HGladiator** [comment]
开启了高级账户的 启动同步服务, 还是无法解析
![png](https://i.loli.net/2021/07/05/6Le7zoMQ4Z8jxGq.png)


在第三方适配源中 写了 json web url ,点击导入 ,看到成功导入一条.,重启chrome  依然不能解析.

**Comment by binsee** [comment]
> 在第三方适配源中 写了 json web url ,点击导入 ,看到成功导入一条.,重启chrome 依然不能解析.

如果你是说B站专栏的话，请参考 https://github.com/Kenshin/simpread/issues/2470#issuecomment-871962768 操作。测试是可行的。

**Comment by HGladiator** [comment]
我按照教程试了一下， 还是不行，算了不搞了，这个影响不是很大， 已经有#2468，我就不跟这个事了，
