### ISSUE TITLE
字体不够大？站点管理器bug

### ISSUE THREAD

**Issue by CharMingF** [Kenshin/simpread#248]
1. 目前字体只能切换三种，我觉得应该是加大和缩小为每次增加或减小一级，而中间的正常则回归到默认。
目前的大号字体跟正常的差距太小了。
2. 站点管理器的自定义站点无法选择。

![image](https://user-images.githubusercontent.com/7530342/36929899-7320a6f4-1ed2-11e8-96cd-c423c9540424.png)

**Comment by Kenshin** [comment]
`站点编辑器` 的 bug 之前有朋友反馈过，已经记录了。
`加大/减小` 的方式可以考虑，不错的想法~

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
1.1.1 新版将会支持字体大小的多级调整，而非三种级别。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
