### ISSUE TITLE
购买前的一些疑问

### ISSUE THREAD

**Issue by caicaicaich** [Kenshin/simpread#2480]

**Comment by Kenshin** [comment]
嗨，谢谢你能理性购买

> 安装了好几次,每次一点击设置,弹出一堆提示,很有负担,选项页只用侧边的那个菜单就好了,

哈哈，目前没有太好的办法，这些提示只是「友好」提示新用户的一些操作逻辑，但反复安装的话，确实有些困扰。

> 帮助文档,百科,功能

从不同的角度来解决新用户的问题，有些用户喜欢「百科方式」有些喜欢其它方式  😂  不过，新用户的话，我建议看 https://zhuanlan.zhihu.com/p/382683271 这篇（涵盖了你说的这些方式。

>  vip和普通用户的区别能不能简单点说明

https://simpread.pro/price.html 下方已经说的很清楚了。

> 购买vip,能不能做到浏览网页时,加入稍后度,自动同步到notion,稍后图界面标注的图文能不能自动同步到notion

可以，[自动化](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%8C%96)

**Comment by Kenshin** [comment]
嗨，我先关闭这个 Issues 了，有需要请随时开启。
