### ISSUE TITLE
关于如何关闭控制面板模式

### ISSUE THREAD

**Issue by YYXuelangwang** [Kenshin/simpread#2482]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统:  MacOS 11.4

- 浏览器版本  Chrome  91.0.4472.114

- 简悦版本 2.2.0.520

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/591896337>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

我遇到的问题，我不清楚是自己其他插件导致的还是什么情况，所以想在这里寻求些帮助（在所有issue中暂时没发现有相关问题的)
1. 有时候我打开其他网址的时候，提示我当前处在控制面板模式，我尝试在偏好设置中找出关闭控制面板模式，但没有用；
2. 我尝试打开部分网址，给到的是如下图所示，一个长条状；

<img width="950" alt="iii2" src="https://user-images.githubusercontent.com/16287226/124340474-21bf1a80-dbe8-11eb-8c90-8dc542302dcb.png">
<img width="1326" alt="iiii1" src="https://user-images.githubusercontent.com/16287226/124340477-2552a180-dbe8-11eb-9be2-f73a91f51477.png">

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，我怀疑你多开了简悦（如油猴脚本 / Edge 安装 Chrome 版的简悦等等）

你可以在**隐身模式下，仅启用简悦**，排除其它扩展造成的干扰。

另外，你给出的 URL 无法访问，还有这个情况是每个页面都发生？还是仅某个页面？

**Comment by YYXuelangwang** [comment]
非常感谢，找到原因了，果然，我用油猴脚本安装了简阅1.1版本，当我在油猴脚本中删除简阅后，就正常了；

**Comment by Kenshin** [comment]
哈哈，没事，搞定就好。

我关闭这个 issues 了。
