### ISSUE TITLE
无法导出到私有化部署的为知笔记

### ISSUE THREAD

**Issue by gxy8221450** [Kenshin/simpread#2484]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

**Comment by Kenshin** [comment]
嗨，请提供一些有意义的信息，如截图，如是使用私有部署时的授权是否正常等。

否则我没办法帮到你。

**Comment by BaiBaiAi** [comment]
@Kenshin   我可以确定我绑定私有化部署的为知笔记 为https  可是在点击导入为知笔记的时候提示失败 
通过控制台抓包网络请求发  **https 变成了http** 
然后这是浏览器的提示
 `
请求 URL: **http**://wiz.xxxx.cool/ks/note/create/fac0f4c0-4cf9-11ec-8211-43d99acb4148
引用站点策略: strict-origin-when-cross-origin
临时标头已显示 了解详细信息
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Referer`
请问如何解决

**Comment by Kenshin** [comment]
@BaiBaiAi 

嗨，抱歉漏掉了这个 issues... 因为是私有部署，我不知道如何才能帮到你。

如果有可能给我一个私有部署的测试账户？如可行的话，将我需要的内容发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：2484
