### ISSUE TITLE
发现一篇 InfoQ 的文章，图片不显示

### ISSUE THREAD

**Issue by JonasGao** [Kenshin/simpread#249]
我是在这篇文章遇到问题的
http://www.infoq.com/cn/articles/distributed-tracing-microservices?utm_campaign=rightbar_v2&utm_source=infoq&utm_medium=articles_link&utm_content=link_text

在进入到阅读模式后，发现图片不显示。

检查发现是其图片的`data-src`为`"articles/distributed-tracing-microservices/zh/resources/4101-1520271955968.png"`，即开头不是`/`，而根据源码 https://github.com/Kenshin/simpread/blob/master/src/read/read.jsx#L390 所示。会`location.origin + newsrc`，而`location.origin`等于`"http://www.infoq.com"`。最终导致图片地址拼接不正确，出现图片加载失败的问题

如图：
![2018-03-07 16 02 03](https://user-images.githubusercontent.com/4549584/37080356-e920df76-2220-11e8-93a2-5c0fb5f85229.png)

2018-03-07 16:19:41 更新
------

测试发现实际图片地址是`"https://res.infoq.com/articles/distributed-tracing-microservices/zh/resources/4101-1520271955968.png"`，不是理论上拼接出来的`"http://www.infoq.com/articles/distributed-tracing-microservices/zh/resources/4101-1520271955968.png"`

查看 Network 里 html 请求的 response 可以看到`img`的`src`里是直接写成`"https://res.infoq.com/articles/distributed-tracing-microservices/zh/resources/4101-1520271955968.png"`的。猜测并没有使用`lazy`

**Comment by JonasGao** [comment]
好的，谢谢。顺便期待新版本

**Comment by Kenshin** [comment]
@JonasGao 
新版本不会有太大的变化，新版只是为了适配 Firefox 而做出的兼容性改变。（当然也不排除一些新的 feature 进入到 release 通道的情况。 😀 ）

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
