### ISSUE TITLE
api无法使用，三种模式telegram bot/快捷指令/popclip都无法连接上

### ISSUE THREAD

**Issue by RRRAOOO** [Kenshin/simpread#2490]
1.高级版，使用的是坚果云同步，授权登陆了
2.同样的token，telegram bot显示绑定成功了，快捷指令/popclip无法确认是否绑定成功，通过快捷指令/popclip分享内容到简悦，一直提示失败，（快捷指令文字提示失败「两个快捷指令都试了」，popclip一直显示❌；
3.telegram bot显示绑定成功，且显示收藏成功，但是在稍后读里找不到，
<img width="837" alt="截屏2021-07-05 下午11 16 10" src="https://user-images.githubusercontent.com/67641818/124493063-c65b7b00-dde7-11eb-8f85-04aaf8b5f25a.png">

**Comment by Kenshin** [comment]
嗨，一个一个回复。

> Telegram bot

你可以看看坚果云里面的  `simpread_config.json` 是否更新了，因为简悦的同步也依赖与坚果云客户端

> popclip

因为调用了一个服务，所以你需要开全局才能正常使用。

> 快捷指令

这个我一直在用，没有遇到问题，请问你的 iOS 是什么系统？

**Comment by RRRAOOO** [comment]
<img width="1612" alt="截屏2021-07-06 下午1 18 42" src="https://user-images.githubusercontent.com/67641818/124546113-b8940d00-de5c-11eb-80ac-d49f60cd1683.png">
这个应该是更新了， simpread_config.json的位置也检查过。

popclip是指mac的系统权限吗，还是简悦的呢，mac的权限都开过了；

ios用的是ios14.6；

另外有一个疑问： simpread_config.json文件是只有第一次设置的时候会更新吗？因为我发现自动同步助手显示的更新时间是7-6号，但是坚果云上显示的修改时间是7-2号

**Comment by RRRAOOO** [comment]
> 嗨，一个一个回复。
> 
> > Telegram bot
> 
> 你可以看看坚果云里面的 `simpread_config.json` 是否更新了，因为简悦的同步也依赖与坚果云客户端
> 
> > popclip
> 
> 因为调用了一个服务，所以你需要开全局才能正常使用。
> 
> > 快捷指令
> 
> 这个我一直在用，没有遇到问题，请问你的 iOS 是什么系统？

<img width="1612" alt="截屏2021-07-06 下午1 18 42" src="https://user-images.githubusercontent.com/67641818/124546734-aa92bc00-de5d-11eb-8aed-31848e723e6c.png">

这个应该是更新了， simpread_config.json的位置也检查过。
popclip是指mac的系统权限吗，还是简悦的呢，mac的权限都开过了；

ios用的是ios14.6；

另外有一个疑问： simpread_config.json文件是只有第一次设置的时候会更新吗？因为我发现自动同步助手显示的更新时间是7-6号，但是坚果云上显示的修改时间是7-2号

**Comment by Kenshin** [comment]
> popclip是指mac的系统权限吗，还是简悦的呢，mac的权限都开过了；

我的意思是，Popclip 调用了一个服务，而这个服务需要开 **全局** 才能正常访问。

> simpread_config.json文件是只有第一次设置的时候会更新吗？

当然不是了，假设使用 API 保存新的稍后读，每次都会更新 `simpread_config.json` 这个文件。

> 因为我发现自动同步助手显示的更新时间是7-6号，但是坚果云上显示的修改时间是7-2号

后者的时间是从哪里看到的？截图给我看下。

**Comment by RRRAOOO** [comment]
> > popclip是指mac的系统权限吗，还是简悦的呢，mac的权限都开过了；
> 
> 我的意思是，Popclip 调用了一个服务，而这个服务需要开 **全局** 才能正常访问。
> 
> > simpread_config.json文件是只有第一次设置的时候会更新吗？
> 
> 当然不是了，假设使用 API 保存新的稍后读，每次都会更新 `simpread_config.json` 这个文件。
> 
> > 因为我发现自动同步助手显示的更新时间是7-6号，但是坚果云上显示的修改时间是7-2号
> 
> 后者的时间是从哪里看到的？截图给我看下。

<img width="1788" alt="截屏2021-07-06 下午2 44 52" src="https://user-images.githubusercontent.com/67641818/124554788-eed78980-de68-11eb-90b3-3fbeea8c5c01.png">
web版坚果云后台
<img width="929" alt="截屏2021-07-06 下午2 44 07" src="https://user-images.githubusercontent.com/67641818/124554856-fdbe3c00-de68-11eb-905d-df911fe26f32.png">

**Comment by Kenshin** [comment]
如果是自动同步的话，应该以「本地坚果云的时间为主」，这个时间只是参考值。

另外，自动同步功能很重要的一点：**需要安装坚果云客户端**。

如果安装了坚果云客户端后，可以随便在配置文件改动一个选项，然后看看本地与坚果与 Web 端的时间是否一致？

**Comment by RRRAOOO** [comment]
> 如果是自动同步的话，应该以「本地坚果云的时间为主」，这个时间只是参考值。
> 
> 另外，自动同步功能很重要的一点：**需要安装坚果云客户端**。
> 
> 如果安装了坚果云客户端后，可以随便在配置文件改动一个选项，然后看看本地与坚果与 Web 端的时间是否一致？

我刚才试了一下 手动同步到坚果云 simpread_config.json文件已经变为最新了 然后改成了自动同步 授权坚果云登陆
可是在稍后读里 还是没有找到 telegram 上提示保存成功的文章

**Comment by Kenshin** [comment]
你需要这样测试（做），确保这个选项已开启

![image](https://user-images.githubusercontent.com/81074/124572340-294a2200-de7b-11eb-9ee7-2e9ed55574cf.png)

并按照按顺序操作：

1. 坚果云启动
2. 同步助手启动
3. 扩展端不要做任何（操作）
4. 使用 tg bot 添加一条 URL

如果上述步骤没问题的话，稍等片刻，就能在本地收到一条「坚果云」同步成功的信息，如 Mac 上的应该是类似

![image](https://user-images.githubusercontent.com/81074/124572099-f6079300-de7a-11eb-8b87-d4dc52f11261.png)

然后打开稍后读

![image](https://user-images.githubusercontent.com/81074/124572544-4bdc3b00-de7b-11eb-8508-d134a1abbd7c.png)

看看这条信息是否出现在稍后读中？

**Comment by RRRAOOO** [comment]
> 你需要这样测试（做），确保这个选项已开启
> 
> ![image](https://user-images.githubusercontent.com/81074/124572340-294a2200-de7b-11eb-9ee7-2e9ed55574cf.png)
> 
> 并按照按顺序操作：
> 
> 1. 坚果云启动
> 2. 同步助手启动
> 3. 扩展端不要做任何（操作）
> 4. 使用 tg bot 添加一条 URL
> 
> 如果上述步骤没问题的话，稍等片刻，就能在本地收到一条「坚果云」同步成功的信息，如 Mac 上的应该是类似
> 
> ![image](https://user-images.githubusercontent.com/81074/124572099-f6079300-de7a-11eb-8b87-d4dc52f11261.png)
> 
> 然后打开稍后读
> 
> ![image](https://user-images.githubusercontent.com/81074/124572544-4bdc3b00-de7b-11eb-8508-d134a1abbd7c.png)
> 
> 看看这条信息是否出现在稍后读中？

按上述操作进行了测试，坚果云也显示了更新完成，但是在稍后读中还是找不到保存的信息
![IMG_8280](https://user-images.githubusercontent.com/67641818/124708463-e8124a80-df2c-11eb-8322-ce221f4dfedd.PNG)
<img width="471" alt="截屏2021-07-07 下午2 07 47" src="https://user-images.githubusercontent.com/67641818/124708499-f2ccdf80-df2c-11eb-868a-b6ebf9d6a8ae.png">

**Comment by Kenshin** [comment]
同步助手设置同步文件夹了吗？

![image](https://user-images.githubusercontent.com/81074/124746513-87e2cf00-df53-11eb-9532-3190440ee2e1.png)

**Comment by RRRAOOO** [comment]
> 同步助手设置同步文件夹了吗？
> 
> ![image](https://user-images.githubusercontent.com/81074/124746513-87e2cf00-df53-11eb-9532-3190440ee2e1.png)

刚刚设置了，但还是一样，一直弹下面的提示
<img width="744" alt="截屏2021-07-07 下午8 08 12" src="https://user-images.githubusercontent.com/67641818/124756770-6b4c9400-df5f-11eb-8116-30e6c0e5342c.png">

**Comment by RRRAOOO** [comment]
> > popclip是指mac的系统权限吗，还是简悦的呢，mac的权限都开过了；
> 
> 我的意思是，Popclip 调用了一个服务，而这个服务需要开 **全局** 才能正常访问。
> 
> > simpread_config.json文件是只有第一次设置的时候会更新吗？
> 
> 当然不是了，假设使用 API 保存新的稍后读，每次都会更新 `simpread_config.json` 这个文件。
> 
> > 因为我发现自动同步助手显示的更新时间是7-6号，但是坚果云上显示的修改时间是7-2号
> 
> 后者的时间是从哪里看到的？截图给我看下。

另外，popclip的全局权限是指的这里的吗
<img width="634" alt="截屏2021-07-07 下午8 12 59" src="https://user-images.githubusercontent.com/67641818/124757099-d5653900-df5f-11eb-8e06-1c181ec62dfa.png">

**Comment by Kenshin** [comment]
@RRRAOOO 

嗨，你能上 tg 吧（选项页 → 关于 → 里面有 tg 地址）？进群然后找我私聊，我帮你解决。

**Comment by Timor88** [comment]
问题解决了吗,我遇到了同样的问题

**Comment by Kenshin** [comment]
> 问题解决了吗,我遇到了同样的问题

上面的用户问题应该都解决了，你可以看看下 https://github.com/Kenshin/simpread/discussions/categories/developer 里面的一些提示，尤其是 https://github.com/Kenshin/simpread/discussions/2399

**Comment by Timor88** [comment]
已经解决

**Comment by Kenshin** [comment]
> 已经解决

okay 那我直接关闭这个 issues 了。
