### ISSUE TITLE
代码段增强插件在 MDN 特定页面运行时出错，所有代码段无法高亮

### ISSUE THREAD

**Issue by liyang85** [Kenshin/simpread#2492]
出错的 MDN 页面： <https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics> 。除了这个页面，代码段增强插件在其它 MDN 页面都能够正常运行。

这个页面有一行特殊的示例代码，我推测这一行代码可能就是导致出错的根本原因。

```html
<p>My cat is <strong>very grumpy.</p></strong>
```

![image](https://user-images.githubusercontent.com/20695423/124504518-3e32a100-ddfa-11eb-9595-523d18daac78.png)

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by liyang85** [comment]
另一个出错页面：

<https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics>

**Comment by Kenshin** [comment]
> 另一个出错页面：
> 
> https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

收到，我看近期能否修改无法使用代码高亮插件的问题。

**Comment by liyang85** [comment]
刚刚才发现，在 <https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics> 这个页面上，即使「禁用」代码段增强插件，也会出现正文内容丢失的问题。这个问题比较严重，影响到正常使用了，请尽快解决，谢谢。

详见截图：

<img width="1366" alt="Xnip2021-07-07_22-40-09" src="https://user-images.githubusercontent.com/20695423/124779460-62b28880-df74-11eb-9dca-81353f4f6e05.png">

正文我也截了图，供对比：

<img width="856" alt="Xnip2021-07-07_22-37-38" src="https://user-images.githubusercontent.com/20695423/124779558-76f68580-df74-11eb-9264-d9157a386d6b.png">
