### ISSUE TITLE
全文翻译的一些建议

### ISSUE THREAD

**Issue by Lyric714** [Kenshin/simpread#2495]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <http://www.chinadaily.com.cn/a/202107/06/WS60e399c0a310efa1bd65fdb5.html>

**请描述你的问题**

翻译的段落很零星，翻译不全，只有当前页面几段翻译了，有时翻译的会跟少段落

**Comment by Kenshin** [comment]
嗨，你说的是 全文翻译 吗？在个别结构不是很好的页面确实有些问题，至于解决方案可以看看 https://github.com/Kenshin/simpread/discussions/1561 提供的思路。

**Comment by Kenshin** [comment]
嗨，[全文翻译](https://github.com/Kenshin/simpread/discussions/1593) 更新到了 1.1.0 增加了 **段落翻译** 比框选翻译更方便，[细节看这里](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

https://user-images.githubusercontent.com/81074/187070868-c72cc2a9-9584-4b4d-aa8c-2ae88ae4d20a.mp4

除此之外，还增加了：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

***

我关闭这个 Issues 了，有任何问题可随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，划词翻译 1.0.0 版发布了，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4
