### ISSUE TITLE
选项页模式无法进行切换

### ISSUE THREAD

**Issue by SHANGHL29** [Kenshin/simpread#2504]
您好，上次发现选项页可以进行模式切换后就选择了简单模式，想看一下效果，现在发现选项页右边有同步设置方式，可是我点模式切换完全没有动静，只停留在简单模式下，请问这个要怎么才能切换回去呢？

**Comment by Kenshin** [comment]
嗨，[看这里](http://ksria.com/simpread/docs/#/%E7%AE%80%E6%98%93%E6%A8%A1%E5%BC%8F?id=%e5%a6%82%e4%bd%95%e6%94%b9%e5%9b%9e%e9%ab%98%e7%ba%a7%e6%a8%a1%e5%bc%8f) 即可改回去。

确实有点不起眼。  😅

**Comment by SHANGHL29** [comment]
改好了，谢谢您
