### ISSUE TITLE
新站适配：nixCraft(cyberciti.bz)

### ISSUE THREAD

**Issue by leyle** [Kenshin/simpread#2510]
网址： https://www.cyberciti.biz
问题： 进入阅读模式后，图片无法显示。
例子链接： https://www.cyberciti.biz/interview/curl-creator-and-swedish-software-developer-daniel-stenberg/

**Comment by Kenshin** [comment]
嗨，我这边是可以显示的，随便找了篇 https://www.cyberciti.biz/linux-news/rhel-8-4-released-update-upgrade-8-3-to-8-4/#more-1835

![image](https://user-images.githubusercontent.com/81074/125149687-f9499a00-e16c-11eb-8ef4-ed3966d9448c.png)


请确认是否都无法显示图片？

**Comment by binsee** [comment]
这个站的图片，如果不开启『预先解析惰性加载图片』功能，进入阅读模式后确实无法显示。

按如下操作开启即可：
![image](https://user-images.githubusercontent.com/5285894/125157427-80166b00-e19d-11eb-999c-e38182fecaee.png)

**Comment by leyle** [comment]
> 这个站的图片，如果不开启『预先解析惰性加载图片』功能，进入阅读模式后确实无法显示。
> 
> 按如下操作开启即可：
> ![image](https://user-images.githubusercontent.com/5285894/125157427-80166b00-e19d-11eb-999c-e38182fecaee.png)

这样设置，打开那个按钮后，可以正常显示出来图片了，谢谢。

**Comment by Kenshin** [comment]
@leyle 

留意开启此功能会有一些小问题，细节看 https://github.com/Kenshin/simpread/discussions/2347
