### ISSUE TITLE
版本2.2.520，mac平台，保存到OneNote，提示成功，但OneNote中找不到；

### ISSUE THREAD

**Issue by nowpast** [Kenshin/simpread#2512]
版本2.2.520，mac平台，保存到OneNote，提示成功，OneNote中找不到；

但OneNote自己的剪辑共计 clip to OneNote，则可以正常保存到OneNote中；

![image](https://user-images.githubusercontent.com/18032533/125150689-61e84500-e174-11eb-9a6e-c74f0759830b.png)

**Comment by Kenshin** [comment]
需要在 Onenote Web 版查看，看看是否在 `SimpRead` 文件夹？或者稍等一会再看下。

Desktop 版似乎有一些延迟。如果还不行，试试重新授权。

**Comment by nowpast** [comment]
thk，确实都同步在了SimpRead 文件夹下，多谢；  之前一直以为同步在快速笔记中

**Comment by Kenshin** [comment]
> thk，确实都同步在了SimpRead 文件夹下，多谢； 之前一直以为同步在快速笔记中

okay 搞定就好，2.2 之前确实在快速笔记中，2.2 转移到了 SimpRead 里面。

没问题的话，我关闭这个 Issues （另外，不知道你从哪里得到的 **快速笔记**，如果是文档的话，请告知，我需要更新说明。 🙏

**Comment by nowpast** [comment]
可以close了  谢啦
早期用过一段时间 简悦，隐约记得保存在 **快速笔记**；
最近重新用 简悦 ，我再没事翻翻文档

**Comment by Kenshin** [comment]
哈哈，如果是早期用户的话，确实是在 **快速笔记** 中。
