### ISSUE TITLE
导出为手机长截图

### ISSUE THREAD

**Issue by lurui45** [Kenshin/simpread#2514]
目前的导出图片模式，排版不适合手机端阅读。
作者能否新增导出手机长截图模式，方便分享文章到手机端查看，类似下图这种
![Notes_20210710_144912](https://user-images.githubusercontent.com/9017003/125154727-075be280-e18e-11eb-9cd0-a8e62483b5ef.jpg)

**Comment by Kenshin** [comment]
嗨，谢谢建议，可以考虑。

**Comment by Kenshin** [comment]
另外，方便说说具体使用场景吗？

**Comment by lurui45** [comment]
> 另外，方便说说具体使用场景吗？

主要是我在网页端看到不错的文章，想分享给微信上的好友阅读，但是有时候这些文章是墙外看到的，别人并不能直接访问，导出为长截图就方便他们直接手机上阅读了

**Comment by Kenshin** [comment]
嗨，收到，可以考虑你说的场景。

PS：我把上条的某些文字删除了。

**Comment by Kenshin** [comment]
嗨，我制作了 https://simpread.ksria.cn/plugins/details/1MarRdpJum 可以导出适合手机查看的长截图，有任何需求可以随便跟我说。

我先关闭此 Issues 了。
