### ISSUE TITLE
授权Notion导入时仅能获取第一个notion page

### ISSUE THREAD

**Issue by Oscarrr12138** [Kenshin/simpread#2515]
- 操作系统 **MacOS**

- 浏览器版本 **Edge 最新稳定版 & chrome 最新版**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <中国浙江l>

**请描述你的问题**

> 在授权导入notion时显示仅能获取第一个notion page 且再次下拉菜单时仅显示第一个notion page

但我所期望的功能是能够将文章导入我建好的notion database中 或者能够有多个page页面选择

<img width="1693" alt="截屏2021-07-10 下午4 14 23" src="https://user-images.githubusercontent.com/55611654/125156811-016bfe80-e19a-11eb-9081-7ae35085c549.png">

<img width="1920" alt="截屏2021-07-10 下午4 18 57" src="https://user-images.githubusercontent.com/55611654/125156948-ba323d80-e19a-11eb-848c-38ad4e085f8d.png">

**Comment by Kenshin** [comment]
嗨，导入到 Notion 使用了私有 API，会导致一定程度是失败率，而你遇到的这个提示正是因为这个原因导致。

关于你的诉求，可以参考下面的方式：

> 专门建一个read list之类的database 页面 圈保存在那里，保存完，自己去阅读/整理到想要的地方。

毕竟只是导入，将不同的内容导入不同的 Page 虽然看起来似乎比较方便，但并不易于整理。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
