### ISSUE TITLE
新浪网部分网页，无法进入阅读模式

### ISSUE THREAD

**Issue by DavidSongzw** [Kenshin/simpread#252]
新浪网部分网页，无法进入阅读模式。
http://tech.sina.com.cn/i/2018-03-08/doc-ifxpwyhv6801262.shtml

**Comment by Kenshin** [comment]
嗯，的确有这样的情况，你可以通过 `站点编辑器` 修改，或者，我会不定期更新 `官方适配源`。到时候就可以使用了~

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
