### ISSUE TITLE
如何打开txt文件

### ISSUE THREAD

**Issue by Polyhedronalan** [Kenshin/simpread#2523]
如何用simpread打开本地txt文件进行阅读？研究了两个小时没找到在哪呀

**Comment by Kenshin** [comment]
嗨，进入 `chrome://extensions/` 然后看下图设置，即可。

![image](https://user-images.githubusercontent.com/81074/125433267-765f1ca5-5786-4c21-8e37-826db874ff30.png)

![image](https://user-images.githubusercontent.com/81074/125433329-0dadea21-c0fd-45d6-9cd0-5f1aa1a45a04.png)
