### ISSUE TITLE
导出到生产工具和保存为本地文件的样式问题，不能较好的还原为阅读模式下的样式

### ISSUE THREAD

**Issue by listenkeep** [Kenshin/simpread#253]
如题，像导出到生产工具如OneNote后样式几乎没有了，还有导出为MD文档或PDF也有类似的情况，这个我想应该可以实现类似的效果的，如打印时使用更宽更合适的页面设置等，希望能实现这个功能，当然，当前已经实现的也很不错了，使得网页浏览舒适不少，感谢

**Comment by Kenshin** [comment]
感谢反馈~
导出 PDF 时，调用的是 Chrome 自己的打印方案，打印的也是当前页面（即简悦优化后的页面）。
而 MD 只是文本文件并不存在样式。

保存到 OneNote 后并没有样式的原因是 OneNote 就是这么设计的，下图为 Onenote Web Clipper 与 简悦的 裁剪的效果对比（你可以看到用 Onenote Web Clipper 也没有出现样式）

![2018-03-10_10-54-35](https://user-images.githubusercontent.com/81074/37237656-763bf0b2-2451-11e8-97a4-d529b9b4607a.png)

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊

**Comment by XdpAreKid** [comment]
我用ipad的onenote打开也是乱的，mac的onenote的也是乱的，网页版的功能很不错，能不能使用固定格式的存储在onenote或者印象上？？我现在还是下载成epub，然后倒入到icloud里。

**Comment by Kenshin** [comment]
@XdpAreKid 
请问是什么版本？刚测试了并没有你说的情况，另外建议重新开一个 issues ~
是每个导出到 Onenote / Evernote 都是乱码？还是？
