### ISSUE TITLE
一段代码，但是识别成两段

### ISSUE THREAD

**Issue by Gqiangqiang** [Kenshin/simpread#2535]
一段代码，但是识别成两段

网址：https://www.cnblogs.com/gqx-html/p/10967412.html

原始：
![image](https://user-images.githubusercontent.com/45932253/125577316-7059ec37-fb45-45e9-939a-02cdc95e04ee.png)

阅读模式下：
![阅读模式](https://user-images.githubusercontent.com/45932253/125577175-80a4127f-a22d-4880-ac0e-049d6ae16566.png)

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
