### ISSUE TITLE
阅读进度条在碰到白色背景时会被盖住

### ISSUE THREAD

**Issue by YangDou** [Kenshin/simpread#254]
## 我在拖动到代码这里时进度条被盖住了
![image](https://user-images.githubusercontent.com/23449308/37269274-a1776ffe-2604-11e8-9094-8e8ff22703d8.png)
## 到拖动到代码块下面时又恢复正常
![image](https://user-images.githubusercontent.com/23449308/37269380-00a5aa04-2605-11e8-8b57-7511fe962177.png)

**Comment by Kenshin** [comment]
由于设置了 `z-index` 所以目前的确有这种的情况发送，暂时也没有太好的解决办法。
如果不需要滚动条的话，可以将其隐藏。 😂

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
