### ISSUE TITLE
简悦同步助手无法正常浏览Eco_Wiki

### ISSUE THREAD

**Issue by JohnnyWoong** [Kenshin/simpread#2541]
这个我不知道算是适配问题还算是bug, ECO的wiki详细页无法正常读取(会变空白), 即使我不进阅读模式或者聚焦模式也会变空白
![开启简悦同步助手后](https://user-images.githubusercontent.com/5661094/126037215-f1476592-4c55-4104-98e4-60c7aedc0743.png)
![退出简悦同步助手后](https://user-images.githubusercontent.com/5661094/126037240-64403f2b-871e-4679-a1a3-47e42cb87d56.png)
示例页面https://wiki.play.eco/en/Anvil
事实上该站点每个详细页面都有这个问题

**Comment by Kenshin** [comment]
嗨，你需要关闭下面这个选项即可，选项页 → 高级设定 → 词法分析引擎

![image](https://user-images.githubusercontent.com/81074/126053106-bd10e257-5727-4d25-bf4e-e96e4e84d6ae.png)

**Comment by JohnnyWoong** [comment]
是的, 我已经发现了, 所以我Closed issue了, 谢谢

**Comment by Kenshin** [comment]
是的，因为我看到 close 所以不清楚是何种原因，所以回复下。😀
