### ISSUE TITLE
保存时的网络笔记的选项太多了，一般情况也就用到一两个

### ISSUE THREAD

**Issue by featheryus** [Kenshin/simpread#2543]
如果只授权了notion，是不是导保存时，只显示notion就好了，
亦或者，将授权的放置到最上面
再或者，我可以配置哪些显示出来

如图
![截屏2021-07-17 23 56 31](https://user-images.githubusercontent.com/3468779/126042736-13f57fa6-40ab-46ed-9ac3-92b13d88abea.jpg)

**Comment by Kenshin** [comment]
嗨，截图的中 插件 里面就有说明，如下图所示

![image](https://user-images.githubusercontent.com/81074/126052927-0dc539c4-f6e1-40cd-91b2-f6bab7aad3ae.png)

你可以使用 

https://simpread.ksria.cn/plugins/details/7gcXYY4HAc
https://simpread.ksria.cn/plugins/details/rsd4UIcDKY

这两个插件解决。

**Comment by featheryus** [comment]
收到，多谢
