### ISSUE TITLE
git 文档格式错误, 代码位置偏移

### ISSUE THREAD

**Issue by slow-zhang** [Kenshin/simpread#2549]
文档链接 https://git-scm.com/book/zh/v2/Git-%E5%9F%BA%E7%A1%80-%E8%AE%B0%E5%BD%95%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E5%88%B0%E4%BB%93%E5%BA%93

![image](https://user-images.githubusercontent.com/24769636/126096900-5dfc5f9e-00a0-45ba-899f-fdbdab7b336c.png)
![image](https://user-images.githubusercontent.com/24769636/126096905-4ab297bf-5ac1-474e-be72-273450ed11b7.png)

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
