### ISSUE TITLE
阅读模式下CSDN公式显示问题

### ISSUE THREAD

**Issue by heimi98** [Kenshin/simpread#2550]
这个页面 https://blog.csdn.net/Zhaoxi_Li/article/details/104905150 阅读模式下公式显示有问题。
![image](https://user-images.githubusercontent.com/56879067/126137477-519ef074-67b0-43a2-92c8-a8f20d78a254.png)

**Comment by Kenshin** [comment]
嗨，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
