### ISSUE TITLE
QQ邮箱——每日悦读，阅读模式适配问题

### ISSUE THREAD

**Issue by wingkinger** [Kenshin/simpread#2551]
**发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10专业版**

- 浏览器版本 **Microsoft Edge
版本 91.0.864.70 (官方内部版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <mail.qq.com>

**因为QQ邮箱的链接带cookie，复制过来没法打开，所有就无法放出现问题的准确地址，但问题是在所有QQ邮箱“每日悦读”页面里是普遍存在的。**

# 问题1

在QQ邮箱“每日悦读”里所有文章页面“聚焦模式”或者“阅读模式”都没法用快捷键呼出。
![8fd6452f-d10f-452a-8f78-7226b0cdf123](https://user-images.githubusercontent.com/51572592/126147423-5c064557-32d9-44f5-8cd3-c73267314770.gif)

# 问题2

在QQ邮箱“每日悦读”里所有文章页面偶尔呼出手动框选后无法正确识别正文内容。
![image](https://user-images.githubusercontent.com/51572592/126148025-b733e3c1-17ac-43f4-bd8c-3df1a54ce7ae.png)
![手选框2](https://user-images.githubusercontent.com/51572592/126148211-1658ff81-a924-4bd3-bae3-9757ad137b0d.png)

# 结论

我想应该是这个网站的主题页面没有适配的问题。

> 期待你的回复

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，谢谢反馈，我目前在休假，有时间的时候会马上确认。

你可以试试 http://ksria.com/simpread/docs/#/手动框选 能否解决？

**Comment by Kenshin** [comment]
嗨，我已经确认了每日悦读是无法使用简悦的阅读模式。

因为它使用了 ifarme 的方式，简悦（特意禁止）在 iframe 下使用的阅读模式，所以我关闭这个 Issues 了。
