### ISSUE TITLE
同步助手1.01无法更新，且小书签功能异常，无法使用

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2557]
**请说明发生问题的环境**

- 操作系统 *win7*

- 浏览器版本 **e.g. Chrome 73.0.3683.86**

- 简悦版本 **2.2.0.520_0**

-  同步助手 1.01

**请描述你的问题**

>同步助手更新服务不可用

![image](https://user-images.githubusercontent.com/23255790/126443521-1203afe0-4abd-4b18-b4f5-76a6ea93a3af.png)

>小书签功能使用异常 无法提交成功

![image](https://user-images.githubusercontent.com/23255790/126443549-c8673f3a-3742-4de2-b885-4786181a26a0.png)

> 查看ISSUE 1.01 不是最新版本么 官网也只有1.01版本

**Comment by Kenshin** [comment]
嗨，重新下载就可以，不知道是什么时候下载的？

**Comment by Sharewithyou** [comment]
> 嗨，重新下载就可以，不知道是什么时候下载的？

谢谢 重新下载就可以了   我核查了下 我是5.20号版本，最新的是24号版本 但是版本号没有改变

**Comment by Kenshin** [comment]
因为之前上传错了压缩包，前后不到 2个小时，所以我没有更新版本号。😂
