### ISSUE TITLE
coolshell站点无法隐藏“相关文章”

### ISSUE THREAD

**Issue by yushiro** [Kenshin/simpread#2558]
https://coolshell.cn/articles/17416.html

官方自带了coolshell的适配， 但是在“隐藏列表”中的
`<div id='wp_rp_first'>`
这项不起作用， 阅读模式还是会把相关内容显示出来。
<img width="1322" alt="截屏2021-07-21 17 16 15" src="https://user-images.githubusercontent.com/415386/126464252-052685c8-c9fb-4bdd-a759-4ba098ef7f21.png">

**Comment by Kenshin** [comment]
emmm 我没有遇到这个情况，请问你安装了类似 uBlock 之类的扩展吗？如果安装的话，可以试试 https://github.com/Kenshin/simpread/discussions/2500 提供的思路。

**Comment by yushiro** [comment]
把chrome扩展全部关闭， 只留了简悦扩展， 还是老问题， 会显示“相关文章”
chrome版本：91.0.4472.114（正式版本） (x86_64)

我查了原始的html页面， 的确有`<div id='wp_rp_first'>`这项， 但阅读模式里面， 这项内容的id已经被清除
<img width="320" alt="截屏2021-07-22 11 55 22" src="https://user-images.githubusercontent.com/415386/126588097-4f5798a8-baee-4b2c-8a38-4c5bff614b1c.png">

uBlock的模式， 我可以去试试， 但大概率不能满足我， 因为我用“添加到稍后读”的触发器， 然后导出为pdf,md, html等文件

**Comment by yushiro** [comment]
还有， 这个情况， 我mac和window系统都是同样的问题， 可以复现。
win系统也试过把扩展全关， 一样是能看到“相关文章”

**Comment by Kenshin** [comment]
如果不想使用 uBlock 的话，试试 

![image](https://user-images.githubusercontent.com/81074/126588953-908220f3-41fb-4f51-beeb-c84a90aaf411.png)

从功能上说跟 uBlock 是一样的。

**Comment by yushiro** [comment]
嗯， 用“隐藏任意元素”解决了导出的问题。
但是我还是好奇， 为什么“隐藏元素”功能没有起作用， 有什么调试的方法吗？ 我对js和html比较熟悉， 如何配合你来调试？

**Comment by Kenshin** [comment]
嗨，关于隐藏站点的细节，你可以看看 http://ksria.com/simpread/docs/#/站点编辑器?id=对应字段 **exclude** 对应的内容。

![image](https://user-images.githubusercontent.com/81074/126638474-115bec62-30d5-4827-9425-db5b8c6204dd.png)

**Comment by yushiro** [comment]
嗯，语法规则我看过，但就是不起作用。算了，这个问题我先关闭了。

**Comment by Kenshin** [comment]
好，因为我这边一直没有重现截图所示的内容，所以我也没办法判断。
