### ISSUE TITLE
无法添加来自此网站的应用、扩展程序和用户脚本

### ISSUE THREAD

**Issue by wealthe** [Kenshin/simpread#256]
如题，求解

**Comment by Kenshin** [comment]
Chrome webstore 吗？

**Comment by wealthe** [comment]
不是，下载然后拖过去安装的

**Comment by wealthe** [comment]
插件那显示：该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。
现在问题是无法启动这个插件

**Comment by Kenshin** [comment]
请看新手帮助的 [离线安装](https://github.com/Kenshin/simpread/wiki/faq#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85) 
其中【在线下载 Chrome Webstore 方式】的内容。

**Comment by wealthe** [comment]
![image](https://user-images.githubusercontent.com/33892909/37578399-8634e7b6-2b73-11e8-9b61-9a10b45a4c43.png)
无法下载

**Comment by wealthe** [comment]
![image](https://user-images.githubusercontent.com/33892909/37578461-f686d614-2b73-11e8-94ac-2bde1f5abf38.png)
离线下载出现这种情况

**Comment by Kenshin** [comment]
@wealthe 
使用 【在线下载 Chrome Webstore 方式】方式，而非离线下载。

**Comment by wealthe** [comment]
我明白，使用 【在线下载 Chrome Webstore 方式】方式，出现的是
![image](https://user-images.githubusercontent.com/33892909/37578944-a2c44310-2b76-11e8-9fbf-e0b2b7dd7e82.png)

**Comment by Kenshin** [comment]
@wealthe 
晕，为什么我这边没问题，直接给你 crx 吧，就是通过第三种方式下载的~

[SimpRead-Reader-View_v1.1.0.crx.zip](https://github.com/Kenshin/simpread/files/1823770/SimpRead-Reader-View_v1.1.0.crx.zip)

**Comment by wealthe** [comment]
或许是校园网的问题？

**Comment by wealthe** [comment]
非常感谢

**Comment by Kenshin** [comment]
@wealthe 
或许是网络的问题，客气啊，没问题的话，我关闭此 issues 了。 😀
