### ISSUE TITLE
公式未加载出来,仍为代码的形式

### ISSUE THREAD

**Issue by Program120** [Kenshin/simpread#2562]
网页:https://www.cnblogs.com/pinard/p/9128682.html
阅读模式:
![阅读模式图片](https://user-images.githubusercontent.com/38416772/126580901-9c07cf3f-460b-4ac5-9e17-af4a01116d08.jpg)

**Comment by Program120** [comment]
已通过之前提供的方案解决
选项页 → 高级设定 → 词法分析引擎 → 关闭纯粹模式

**Comment by Program120** [comment]
但仍然是存在一些显示问题的
![剪贴板图片 (1)](https://user-images.githubusercontent.com/38416772/126581345-8e100246-4cd3-424a-8db1-e0fbb2bff807.jpg)
![剪贴板图片 (2)](https://user-images.githubusercontent.com/38416772/126581366-f359a062-9ae5-4a95-b824-2fca41f2fc9c.jpg)

**Comment by Program120** [comment]
**额,在尝试过很多次后,突然就好了?**
**目前关闭了纯粹模式,但是未使用延时加载**
![image](https://user-images.githubusercontent.com/38416772/126582666-dff583f6-5c1b-40b2-bcf8-19deabfda8e1.png)

**Comment by Kenshin** [comment]
哈哈，搞定就好。
我刚刚测试了下，关闭纯粹模式是可以使用的。

关闭纯粹模式与加入到延迟加载（并开启纯粹模式）在某种程度上说是类似的。

**Comment by Program120** [comment]
找到问题源头,当开启"如果当前页面为适配站点，是否自动进入阅读模式？"后,自动进入阅读模式,如果当前网页中的公式仍为代码形式而不是经过latex加载后的显示形式,则进入阅读模式后显示的公式仍为代码,而非latex加载后的形式,是这样吗?

**Comment by Kenshin** [comment]
> 找到问题源头,当开启"如果当前页面为适配站点，是否自动进入阅读模式？"后,自动进入阅读模式,如果当前网页中的公式仍为代码形式而不是经过latex加载后的显示形式,则进入阅读模式后显示的公式仍为代码,而非latex加载后的形式,是这样吗?

是的，因为简悦使用的预加载方案，进入页面后就识别，但有些页面是动态加载的，就会存在识别错误。

**Comment by Kenshin** [comment]
接上条，所以加入延迟加载列表后，不会预加载当前页面。同时，加入预加载列表后，无法自动进入阅读模式。

**Comment by Program120** [comment]
好的,感谢您花时间解决这个问题,这个插件用起来真的是,太舒服了!已赞助升级,希望你们越做越好!
![X25OM{RY 8U}%SSUGDQ}TZ2](https://user-images.githubusercontent.com/38416772/126584330-85f86cb0-d248-41f0-aa21-751f9359f2c5.jpg)

**Comment by Kenshin** [comment]
哈哈，这是应该的。

PS：你说的这些功能都是免费使用的。

**Comment by Kenshin** [comment]
另外，没有其他问题的话，我关闭这个 Issues 了，当然你可以随时在这里提问。
