### ISSUE TITLE
插件 代码段增强 运行出错

### ISSUE THREAD

**Issue by sylph520** [Kenshin/simpread#2564]
网站： ”https://www.2ndquadrant.com/en/blog/how-to-get-the-best-out-of-postgresql-logs/“
问题：每次进入简悦阅读模式提示，插件 代码段增强 运行出错，提示“请提交此问题”

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
