### ISSUE TITLE
解决了

### ISSUE THREAD

**Issue by Liergou532** [Kenshin/simpread#2571]

**Comment by Kenshin** [comment]
哈哈，搞定就好。

是什么问题造成的？

**Comment by Liergou532** [comment]
> 哈哈，搞定就好。
> 
> 是什么问题造成的？

点击编辑之后只能对标注内容进行操作，点其他的都不管用。一度以为是页面卡死
有一说一，进入了编辑选项之后操作不太友好，一直选不中自己的标注
![image](https://user-images.githubusercontent.com/78479914/126784557-2cd57700-b188-4acb-8fac-dcdfda11e2ef.png)
>就是这样，只能对标注内容操作，其他的选项一点反馈都没有

**Comment by Kenshin** [comment]
> 有一说一，进入了编辑选项之后操作不太友好，一直选不中自己的标注

能截个图说明下吗？

**Comment by Liergou532** [comment]
**普通状态下，鼠标悬浮就能对标注操作**
![image](https://user-images.githubusercontent.com/78479914/126785978-55f3add7-8d85-4994-8608-2ac5a78addbc.png)
**编辑状态下，鼠标悬浮不能给反馈，而且鼠标滑轮也不反馈**
![image](https://user-images.githubusercontent.com/78479914/126786300-202e9268-69bf-444b-9db3-e303c9a9007f.png)
>是不是这条标注太短了啊    而且我还不知道怎么退出 :(

**其实我是想对这个合集进行编辑**

**Comment by Kenshin** [comment]
> 编辑状态下，鼠标悬浮不能给反馈，而且鼠标滑轮也不反馈

编辑状态是指什么？

**Comment by Liergou532** [comment]
> > 编辑状态下，鼠标悬浮不能给反馈，而且鼠标滑轮也不反馈
> 
> 编辑状态是指什么？

![image](https://user-images.githubusercontent.com/78479914/126856710-a4bc2891-dfe2-494d-872d-3a47316b9722.png)

**Comment by Kenshin** [comment]
emmm 点击编辑后应该是 Popup 是吧，但我还是没理解 https://github.com/Kenshin/simpread/issues/2571#issuecomment-885631041 里面提到两个截图所描述的问题，尤其是

> 编辑状态下，鼠标悬浮不能给反馈，而且鼠标滑轮也不反馈

我理解的编辑状态下是指：点击了编辑后？

**Comment by Liergou532** [comment]
> emmm 点击编辑后应该是 Popup 是吧，但我还是没理解 [#2571 (comment)](https://github.com/Kenshin/simpread/issues/2571#issuecomment-885631041) 里面提到两个截图所描述的问题，尤其是
> 
> > 编辑状态下，鼠标悬浮不能给反馈，而且鼠标滑轮也不反馈
> 
> 我理解的编辑状态下是指：点击了编辑后？

对，点击了编辑，我不能干任何事情，也不能点击其他的侧栏，只能刷新页面

**Comment by Kenshin** [comment]
> 对，点击了编辑，我不能干任何事情，也不能点击其他的侧栏，只能刷新页面

点击编辑后应该是 Popup 类似下图所示

![image](https://user-images.githubusercontent.com/81074/126857329-aa77cc5b-a8e0-47ca-8c2e-42dcd0419466.png)

你可以看看是否每个标注都存在这个情况？
