### ISSUE TITLE
win无法安装同步助手

### ISSUE THREAD

**Issue by lynn0086** [Kenshin/simpread#2574]
我在官网下载了 简悦 · 同步助手 1.0.1@win64，单击安装后，就没有反应了，请问应该怎么办

![image](https://user-images.githubusercontent.com/49804533/126854177-143b4689-8257-4038-97a7-513b6dcb9179.png)

**Comment by lynn0086** [comment]
单击‘仍要运行’后，就没有反应了

**Comment by Kenshin** [comment]
嗨，可以试试 32位系统，应该就没有这个问题了。

**Comment by lynn0086** [comment]
改为32可以了，感谢

**Comment by Kenshin** [comment]
嗨，搞定就好~
