### ISSUE TITLE
towarddatascience.com的文章发现内容丢失

### ISSUE THREAD

**Issue by sylph520** [Kenshin/simpread#2578]
通过简悦阅读模式打开 towarddatascience.com的文章
比如https://towardsdatascience.com/how-to-train-neural-networks-like-a-pro-1d2362768c1 （发现内容丢失，e.g., 以Problem 开头的标题 在阅读模式里面丢失），

![image](https://user-images.githubusercontent.com/4487630/126895074-11f523ac-01b7-41db-95e7-0670ead0dd9d.png)

![image](https://user-images.githubusercontent.com/4487630/126895063-990b5635-1e84-44db-8399-b0fe27062f49.png)
又比如https://towardsdatascience.com/from-making-predictions-to-optimizing-actions-an-introduction-to-policy-learning-2-4-9fc46ba8f3d0

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这个页面是智能识别的，所有一定的失败率，你可以通过下图所示的方式重新获取即可

![image](https://user-images.githubusercontent.com/81074/126899322-1e404d14-4b19-46d9-89af-50652d331a2e.png)

**Comment by sylph520** [comment]
手动确实可以了 👍
