### ISSUE TITLE
无法导出到Notion

### ISSUE THREAD

**Issue by brakye** [Kenshin/simpread#2579]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
因为你没有给出 URL 我没法判断，一般来说这种问题都是因为 https://github.com/Kenshin/simpread/discussions/1773 引起的。

我先关闭此 Issues 有需要请随时开启。

PS：我每天都在使用此功能，所以肯定是没问题的。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
