### ISSUE TITLE
元素匹配支持特殊符号

### ISSUE THREAD

**Issue by xcffl** [Kenshin/simpread#258]
元素匹配目前不支持“|”符号，但这个符号确实会出现在元素的 class 名称中。
例如 wsj.com 的文章，Related Coverage 板块：
![default](https://user-images.githubusercontent.com/2216902/37860715-73fc07ec-2f23-11e8-90ca-5925806adb9e.png)

现在把这个符号排除在外，没办法适配相关站点。希望匹配方式可以修改一下。

**Comment by Kenshin** [comment]
@xcffl 
感谢反馈，你可以使用另外的某一个确定的 class name，本例中，你可以使用第二个 `typ-Insertxxx` 试试。

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
