### ISSUE TITLE
重装系统后，按照帮助文件步骤无法恢复高级用户。

### ISSUE THREAD

**Issue by putiang880** [Kenshin/simpread#2581]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <按照帮助信息操作无法恢复高级用户。>

**Comment by Kenshin** [comment]
请重新说明你的操作过程，或者试试重启浏览器后再授权。

另外，你在 https://github.com/Kenshin/simpread/discussions/1569 的提问已经被删除，因为已经有了这个 Issues，请集中在这里处理。

**Comment by putiang880** [comment]
1，在https://simpread.pro/account中解绑，解绑成功
2，重启浏览器后重新绑定显示序列号已被使用
3，重启电脑，删除配置文件，再重启浏览器重新绑定同样显示序列号已被使用

**Comment by Kenshin** [comment]
嗨，不知道你是否有正确的 UID 和 License 

没有 UID 的话，请使用 https://github.com/Kenshin/simpread/discussions/1571 找回
找回 UID  后，请使用 https://github.com/Kenshin/simpread/discussions/1958 提供的方式

**Comment by Kenshin** [comment]
请使用此方式解决 https://github.com/Kenshin/simpread/discussions/2816
