### ISSUE TITLE
在稍后读中打开文章时，如何关闭提取标题和摘要那个自动出现的绿色标注

### ISSUE THREAD

**Issue by panjingyi** [Kenshin/simpread#2582]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 在稍后读中打开文章时，如何关闭提取标题和摘要那个自动出现的绿色的标注，不是说出现后手动关闭，而是如何设置使其默认不生成这个标注。

****

> 一图胜千言，所以方便的话，可以试着贴图。
![Snipaste_2021-07-26_09-50-37](https://user-images.githubusercontent.com/43982333/126922999-1107b03b-5cd0-4c4a-b5cd-e7633f48bfa0.jpg)

**Comment by Kenshin** [comment]
嗨，这个是标注侧栏，不能关闭，你可以最小化它，如下图所示

![image](https://user-images.githubusercontent.com/81074/126928839-8ecca2d1-a616-43e8-99bf-337460a6d667.png)

![image](https://user-images.githubusercontent.com/81074/126928852-3c5e29b1-61cd-4572-852f-891ecc6f9de7.png)

另外，请问这么做的目的是什么？

**Comment by panjingyi** [comment]
目的就是对于不需要标注的文章，不希望默认自动出现这个影响页面干净，个人觉得设为手动生成更符合实际需求。我只是想问问有没有相关设置项来关闭这个功能，以为自己没找到，非常感谢。

**Comment by Kenshin** [comment]
emmm...

这个不是只是标注栏，而是稍后读的「信息栏」。

你可以试试这个功能：[清爽模式](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e6%b8%85%e7%88%bd%e6%a8%a1%e5%bc%8f)

![image](https://user-images.githubusercontent.com/81074/126930516-6f7613ce-9f89-4cee-aa85-7aef97babe58.png)

![image](https://user-images.githubusercontent.com/81074/126930523-d80b8e13-f4b0-4d04-a106-779e97d71ba9.png)

**Comment by panjingyi** [comment]
好的，既然没有开关，我不纠结于此，只是我个人的需求，清爽模式也挺好的，非常感谢！

**Comment by Kenshin** [comment]
哈哈，谢谢「理解」。

这样的话，我关闭这个 Issues 了。
