### ISSUE TITLE
自定义标题模板设置为{{id}}{{un_title}}{{mode}}后，每次自动化离线html都会有这个错误的提示

### ISSUE THREAD

**Issue by panjingyi** [Kenshin/simpread#2583]
![Snipaste_2021-07-26_09-34-17](https://user-images.githubusercontent.com/43982333/126923280-5e1ed370-53f7-465e-8004-220de2fb96b1.jpg)

**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0**

**请描述你的问题**

> 自定义标题模板设置为{{id}}{{un_title}}{{mode}}后，每次自动化离线html都会有这个错误的提示

**Comment by Kenshin** [comment]
嗨，这个功能我每天都在使用，正常配置的话不会存在这个情况。

方便说下你的操作步骤？另外，请截图看下：

1. `{{id}}{{un_title}}{{mode}}` 的截图
2. 自动化时的配置截图

或者在 Github 找到我的联络方式，然后发邮件附上你的配置并在标题注明 Issues id 我帮你看下。

**Comment by panjingyi** [comment]
操作步骤就是在阅读模式下通过快捷键添加至稍后读
![Snipaste_2021-07-26_11-26-58](https://user-images.githubusercontent.com/43982333/126929268-0db2b5cd-4f95-4b2a-8c86-f9235abb0229.jpg)
![Snipaste_2021-07-26_11-28-08](https://user-images.githubusercontent.com/43982333/126929272-839f6f0a-a856-448b-b4a2-fb5b654af49f.jpg)
![Snipaste_2021-07-26_11-28-26](https://user-images.githubusercontent.com/43982333/126929275-1081995a-384b-4f5e-b52a-8d401bf24604.jpg)

**Comment by Kenshin** [comment]
emm 看截图的话，确实没有问题。

方便把配置文件给我吗？

**Comment by panjingyi** [comment]
[simpread-config-2021年07月26日 12_09_01.zip](https://github.com/Kenshin/simpread/files/6875491/simpread-config-2021.07.26.12_09_01.zip)

**Comment by panjingyi** [comment]
配置文件已发个人邮件

**Comment by Kenshin** [comment]
收到，稍后给你反馈。

**Comment by Kenshin** [comment]
嗨，我用你的配置文件测试了下，是没问题的，可以直接导出 html 与 md（你截图给出的自动化与配置文件不一样。

![image](https://user-images.githubusercontent.com/81074/126934071-3409c42c-addb-4b02-81af-183c77e09946.png)

![image](https://user-images.githubusercontent.com/81074/126934109-5d253a14-a913-488a-ada1-cca57d31320a.png)

![image](https://user-images.githubusercontent.com/81074/126934167-6e11c980-a24f-4f9a-8b6a-3cb4d6ef2b8e.png)

**Comment by panjingyi** [comment]
确实是一个很奇怪的问题，我这里的自动配置确实只设了离线html一个任务。不过我觉得此配置与本问题并不相关，可能还是浏览器环境本身的问题，我有机会换台电脑试试，再次感谢如此高效的回复~

**Comment by Kenshin** [comment]
你给我配置文件里面的自动化相关设置如下图

![image](https://user-images.githubusercontent.com/81074/126936381-48db4f8a-978d-4b1b-abf6-134fa4462cd0.png)


你可以这样做：**导出配置文件后，清除全部设置，再导入**

![image](https://user-images.githubusercontent.com/81074/126936452-2706049c-3b8b-4980-adbc-6ce429ad6892.png)

***

没事的，我喜欢折腾的用户，如果想用好简悦的高级功能，就需要点折腾精神才行。

**Comment by panjingyi** [comment]
我用编辑器打开同一个json文件，和你的贴图不一样
![Snipaste_2021-07-26_16-24-00](https://user-images.githubusercontent.com/43982333/126957815-0b2dcceb-cec1-4920-98bf-67c3d6dad81e.jpg)

**Comment by panjingyi** [comment]
导出配置文件后，清除全部设置，再导入，并没有解决这个问题

**Comment by Kenshin** [comment]
emmm 是不是你给我的配置文件有问题，通过邮件再重发一份。

**Comment by panjingyi** [comment]
已经邮件重新发送配置文件，有空帮我看看。

**Comment by Kenshin** [comment]
嗨，问题已经找到，**你没有开启标注功能，所以加入稍后读后会有错误。**

解决方案：**选项页 → 高级设定 → 标注** 开启它即可。

![image](https://user-images.githubusercontent.com/81074/127091323-38222b97-1923-475a-b5a4-58ce88f13b4d.png)

**Comment by panjingyi** [comment]
已测试，报错没有了，但是离线html文件名中的id字段没有生成，这又是哪里没设置对？

**Comment by Kenshin** [comment]
开启下图的选项 

![image](https://user-images.githubusercontent.com/81074/127095365-77d8f49e-359e-48da-8785-e288e12c8ca1.png)

在任意页面使用快捷键 `d d` 加入稍后读，会出现右侧侧栏，以及本地的文件

![image](https://user-images.githubusercontent.com/81074/127095520-45f70983-31f6-4a16-ba10-8d7ca528fcfc.png)

**Comment by Kenshin** [comment]
另外，我在邮箱里面给你发了一份改好的配置文件，再试试。

**Comment by panjingyi** [comment]
所有问题都已经解决，再请教一下，如何重置文件名id的计数。

**Comment by Kenshin** [comment]
哈哈，搞定就好，太不容易了...

没有帮忙评分的话，请帮忙评分 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll 😂

***

> 所有问题都已经解决，再请教一下，如何重置文件名id的计数。

重置 id 的功能，暂时没有，如有需要只能手动修改 `simpread_config.json` 😂

**Comment by Kenshin** [comment]
另外，我关闭此 Issues 了。
