### ISSUE TITLE
添加目录到标注 功能问题

### ISSUE THREAD

**Issue by sylph520** [Kenshin/simpread#2584]
**请说明发生问题的环境**
- 操作系统 
Window
- 浏览器版本 
Cent Browser (4.3.9.248, Chromium 86.0.4240.198)
- 简悦版本 
2.0.0

- 发生问题的地址 
https://towardsdatascience.com/how-to-train-neural-networks-like-a-pro-1d2362768c1

**请描述你的问题**
标注模式，开启标注自动排序：
如果刚开始标注，使用 添加目录到标注 生成标注，后期添加手动标注 ，标注列表的标注顺序将没有问题。
如果刚开始标注，没有使用添加目录到标注生成标注、已有手动标注的情况下，使用添加目录到标注生成标注 将会把目录标注添加到标注列表的末尾且不能自动更新标注列表顺序。

希望能自动更新 或 一键根据文章中的顺序调整标注顺序的功能选项，谢谢！

**截图**
![image](https://user-images.githubusercontent.com/4487630/126926205-47d817c0-d497-44af-b4ae-ea72c1890fdb.png)
方框内为自动添加的目录标注，均位于标注列表末尾队列。

**Comment by sylph520** [comment]
不好意思，新增一条标注会触发自动调整，2333。

**Comment by Kenshin** [comment]
嗨，确实有这个问题，有个简单的解决方案：当出现此问题时随便增加个标注，目录就重排了。

PS：这个 Bug 修起来稍微有些繁琐，所以优先级不是那么高。

**Comment by Kenshin** [comment]
@sylph520 

哈哈，你发现的时我已经给你回复了 😂  不过，搞定就好。
