### ISSUE TITLE
手动框选模式，加入稍后读，自动化 生成离线html 后，打开稍后读，离线不生效

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2589]
操作系统 Windows7

浏览器版本 e.g. Chrome 78.0.3904.108

简悦版本 2.2.0.520_0

同步助手 1.01

> 手动框选模式，加入稍后读，自动化 生成离线html后（离线文件已生成），打开稍后读，离线不生效

测试链接：https://gohom.win/2016/10/07/how_to_save_knowledge/

![image](https://user-images.githubusercontent.com/23255790/127079989-ea1d0787-2891-46a3-94b0-c2638606d6b7.png)

![image](https://user-images.githubusercontent.com/23255790/127080223-8378c91a-0916-4d84-b418-0eba1675f6de.png)

![image](https://user-images.githubusercontent.com/23255790/127080224-16d84203-ae98-47ad-bbac-1b3d3359a256.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，看看这个选项开启了吗？稍后读 → 左下角 → 选项

![image](https://user-images.githubusercontent.com/81074/127084011-4116eea0-7b9c-49f0-b286-99da34b61e03.png)

**Comment by Sharewithyou** [comment]
开启了 常规的加入稍后读   是可以加载离线的 但是框选的不可以
![image](https://user-images.githubusercontent.com/23255790/127084466-e2f457ad-9b7f-4408-bdda-c298977d3483.png)

**Comment by Kenshin** [comment]
手动框选有两个方式：

1. 在原页面直接手动框选
2. 进入阅读模式后通过下图方式

![image](https://user-images.githubusercontent.com/81074/127087206-ac60d17d-39d4-4b7a-9cda-eb33db5243ed.png)

***

不过我测试了下是可以的，看下面的截图

![image](https://user-images.githubusercontent.com/81074/127087376-0f8542a2-1885-41fd-a9d7-db9ebab7b0b6.png)

![image](https://user-images.githubusercontent.com/81074/127087396-c0927496-783d-4147-901d-c13bae2e210b.png)

![image](https://user-images.githubusercontent.com/81074/127087411-df29115e-3a50-49cf-b79f-38c15a3ad0d5.png)

**Comment by Sharewithyou** [comment]
@Kenshin   我的操作步骤不是这个样子的 如截图流程 测试链接：https://gohom.win/2016/10/07/how_to_save_knowledge/

1，SS 启动框选
![image](https://user-images.githubusercontent.com/23255790/127089360-649eb293-daa1-4646-baf9-b1150ef7bfb5.png)

2，加入本地适配
![image](https://user-images.githubusercontent.com/23255790/127089471-8e3e7c1d-729b-4e3e-80fe-c2c0537fa63c.png)

3，右键加入稍后读 自动化生成离线文件
![image](https://user-images.githubusercontent.com/23255790/127089564-ae7bf77f-8118-441e-8b5a-9ca9595ad21e.png)

4，打开稍后读 无离线

![image](https://user-images.githubusercontent.com/23255790/127089619-691eaa19-6d3d-4b15-b2b7-97463af5e6e4.png)

**Comment by Kenshin** [comment]
嗨，我还是没有重现你说的问题，看下图

![image](https://user-images.githubusercontent.com/81074/127091775-c0d28e9e-db7d-4061-9313-59470759b8a6.png)

![image](https://user-images.githubusercontent.com/81074/127091784-6351bb63-00b3-4d60-85f4-06fecb93d667.png)

***

请问你在这种情况下加入稍后读后，是否出现图一的自动化提示？并且本地生成的离线 HTML 是什么名字？

**Comment by Sharewithyou** [comment]
@Kenshin 
我刚去试了知乎的文章 也出现了离线失败的情况 
![image](https://user-images.githubusercontent.com/23255790/127105477-b9064d36-265e-4aec-9d3c-2a8a30cc6515.png)

两个文章前后添加 前面的可以 知乎的就不行
![image](https://user-images.githubusercontent.com/23255790/127105580-083fadcb-da07-4a34-9a27-865c22ab54bb.png)

本地使用坚果云
![image](https://user-images.githubusercontent.com/23255790/127105651-e78fb3df-0ee0-49b0-a3cd-c49e9e4a2876.png)

好像也只会生成一个文件
![image](https://user-images.githubusercontent.com/23255790/127105752-f6045f23-356e-40e9-952d-448ff42cdefb.png)

**Comment by Kenshin** [comment]
我有可能知道问题了，开启下面的截图所示的选项

![image](https://user-images.githubusercontent.com/81074/127108819-12406ec3-4627-477b-b7c9-409b82777d58.png)

![image](https://user-images.githubusercontent.com/81074/127108841-dee41505-0609-4708-b679-f5b7d298fd64.png)

**Comment by Kenshin** [comment]
另外看看 https://github.com/Kenshin/simpread/issues/2583 提供的一些讨论思路

**Comment by Sharewithyou** [comment]
@Kenshin   我换了一台新电脑  核验上图的配置  刚才配置的就是这样子的  看了下2583的  应该不是一样的

**Comment by Sharewithyou** [comment]
@Kenshin   但是换了新电脑 还是没有成功

**Comment by Sharewithyou** [comment]
我大致知道了 是不是标题里面特殊符号 中横线的问题

**Comment by Sharewithyou** [comment]
我大致知道了 是不是标题里面特殊符号 中横线的问题

**Comment by Sharewithyou** [comment]
![image](https://user-images.githubusercontent.com/23255790/127115168-58984b35-8a21-4dab-bcf4-aaed2c32d7ac.png)

**Comment by Kenshin** [comment]
emmm 有可能

安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件

然后建议按照 https://github.com/Kenshin/simpread/discussions/2146 设置（你现在的方式是按照标题来找，这不是很精准，应该按照 idx 检索比较好。

**Comment by Sharewithyou** [comment]
非常感谢，应该就是特殊符号相关的问题，我已经切换自定义标题，现在已经正常了

**Comment by Kenshin** [comment]
哈哈，搞定就好，太不容易了...

没有帮忙评分的话，请帮忙评分 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll 😂

**Comment by Sharewithyou** [comment]
@Kenshin  5分好评已提交 会持续的提交优化和使用建议的

**Comment by Kenshin** [comment]
> @Kenshin 5分好评已提交 会持续的提交优化和使用建议的

哈哈，谢谢欢迎多提意见。
