### ISSUE TITLE
为什么好像现在掘金上用不这个插件了

### ISSUE THREAD

**Issue by kevinxft** [Kenshin/simpread#259]
提示页面结构已经改变

**Comment by Kenshin** [comment]
你可以通过 `站点编辑器` 修改，或者等待我集中修改它们。（简悦会定时自动同步最新数据）

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
