### ISSUE TITLE
微信订阅号公众号卡片解析出错

### ISSUE THREAD

**Issue by Dig-BOOS** [Kenshin/simpread#2590]
微信订阅号里的公众号卡片解析有问题，卡片以下的文字在阅读模式无法显示

[flomo weekly vol.029 - 不写，就无法思考](https://mp.weixin.qq.com/s?__biz=MzI0MDA3MjQ2Mg==&mid=2247484661&idx=1&sn=61a151c1a4e993b9499944e5f0cfba54&chksm=e9212694de56af8275c905b46bef7dbacfe865af8a4c35f08fa7180f723c888f9f468c1b4e38&mpshare=1&scene=23&srcid=0721X4hvgfY9J1hQDWINvUth&sharer_sharetime=1626862915647&sharer_shareid=516d7e2d441408639c4e0fe0f4372b26#rd)

阅读模式开启前如图所示：
![image-20210727093232369](https://user-images.githubusercontent.com/39302617/127081031-dabc6ea7-77ec-42ae-821a-ca981df15894.png)

阅读模式效果如图：
![image-20210727093411379](https://user-images.githubusercontent.com/39302617/127080995-d14c97ff-f6fe-40e9-9bc8-a647bbe8d45e.png)

**Comment by Dig-BOOS** [comment]
纯粹模式关闭后也无法显示

**Comment by Kenshin** [comment]
谢谢反馈，这个可能需要单独适配它。

我考虑下如何解决。

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了此问题。

除此之外，此插件还优化了以下内容：

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
