### ISSUE TITLE
本地pdf阅读可以？

### ISSUE THREAD

**Issue by jianghudaoshi** [Kenshin/simpread#2591]
打开本地pdf文件时是否有内置阅读器？
<img width="997" alt="截屏2021-07-27 上午11 29 12" src="https://user-images.githubusercontent.com/46910081/127090801-650a1c4a-8aba-436f-9a29-3d7a75658658.png">

**Comment by Kenshin** [comment]
暂时没有提供此功能。很多浏览器内置了 PDF 阅读器，如 Edge 

请问需要简悦这么做的目的是什么？

**Comment by jianghudaoshi** [comment]
我想把所有阅读材料全部搬到浏览器中进行，某些书籍材料可能在线阅读需要付费，从其他渠道下载下来后，导入简悦做笔记，这样在线的离线的笔记都集中到一处

**Comment by jianghudaoshi** [comment]
还有你为什么删我另一个issue？？？不敢和diigo对比？？？做的不好就去改啊，这种行为也太无耻了吧，我没有找茬吧，你主打的就是阅读器吧，既然开启了付费，很多连剪藏插件都能抓到正文的你获取不到，是我不够宽容吗，现在付费软件都这么豪横了嘛？？看这人品退钱应该也是不可能的吧

**Comment by binsee** [comment]
> 还有你为什么删我另一个issue？？？不敢和diigo对比？？？做的不好就去改啊，这种行为也太无耻了吧，我没有找茬吧，你主打的就是阅读器吧，既然开启了付费，很多连剪藏插件都能抓到正文的你获取不到，是我不够宽容吗，现在付费软件都这么豪横了嘛？？看这人品退钱应该也是不可能的吧

我从邮件订阅看到了你被删除的那个issue，作者删除你那个issue应该是因为你在反映问题时使用了不文明用语导致。
有问题好好反馈问题，说明一些细节，可以得到很好的解答，但如果带着情绪用词不当，即使在其他项目也可能会被人不喜。

回答你关于『很多站点无法进入阅读模式』的问题：
1.付费用户使用同步助手托管配置，需要开启同步助手才能正确进入阅读模式。因为配置已经由同步助手托管，不打开同步助手时，插件无法获得配置内容。
2.无法进入阅读模式的站点，确实有，但你可以通过issue反馈有效内容，需要提交无法进入阅读模式的站点url，可以供其他人测试和分析原因，给出解决方案。另外也可以根据提示，使用『手动高亮』的方式来临时应急。
