### ISSUE TITLE
Notion 账号换绑

### ISSUE THREAD

**Issue by yimingio** [Kenshin/simpread#2592]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

出了些问题,主要是我之前用的一个notion账号,最近换了一个,但是无论怎么操作,都只能保存在原来的那个帐号上

**Comment by Kenshin** [comment]
嗨，你可以这样做：

1. 退出 notion.so 之前的账户
2. 取消简悦对 Notion 的授权
3. 重启浏览器
4. 登陆 notion.so 新的账户
5. 在简悦重新授权 Notion

**Comment by GuoYimingac** [comment]
你好,我使用了上述方法但是没有效果,但之后我把浏览器的notion相关的所有cookie全部删掉之后,重新授权,结果就成功了

**Comment by GuoYimingac** [comment]
但是还是只能授权到第一个页面,不知道怎么回事

**Comment by Kenshin** [comment]
> 但是还是只能授权到第一个页面,不知道怎么回事

只能授权第一个 Page 时有提示，因为你的 Notion 结构导致获取全部 Page 失败造成的。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4

**Comment by Qingcizhaoyue** [comment]
> 嗨，你可以这样做：
> 
> 1. 退出 notion.so 之前的账户
> 2. 取消简悦对 Notion 的授权
> 3. 重启浏览器
> 4. 登陆 notion.so 新的账户
> 5. 在简悦重新授权 Notion

确实无法解绑更换Notion账号

**Comment by Kenshin** [comment]
@Qingcizhaoyue 

当然可以... 对于 Notion 账户来说，简悦这边只是保存了这个 Notion 账户的一些必要使用 API 的数据，并没有什么特别的，所以当然可以随时解绑。
