### ISSUE TITLE
阅读模式-部分主题-英文符号显示不正常

### ISSUE THREAD

**Issue by auniel** [Kenshin/simpread#2597]
![image](https://user-images.githubusercontent.com/37327100/127263313-28218d90-b045-43d8-9f58-6301313112b6.png)
![image](https://user-images.githubusercontent.com/37327100/127263359-0faffc26-1b64-4c1c-87c7-1d20a415c90c.png)

有的字体会，有的字体不会 ；有的主题会，有的主题不会。总的来说，细一点的字体or主题，就不会
---

![image](https://user-images.githubusercontent.com/37327100/127263378-90c1ba68-98cc-4dc6-b563-25779ee4f9d6.png)
正文显示正常，批注明显有较大间隔

---

我经常阅读的是英文学术期刊，所以对于英文排版没有什么建议。

这里提出一个思路，某些符号间距太大可能是因为字体。
此前同样的问题在wolai曾经遇到过，同样一段文字里面的引号，在wolai win10默认字体（可能是win10自带雅黑）的配置下，引号存在很大的间隔；强制替换系统字体为苹方，问题消失。
我猜测，原因可能是某些符号，比如引号分为全角、半角，又或者引号分中文引号、英文引号，因此在简悦的阅读主题进行字体转换时，某些英文字体下的引号被转换或者识别成中文，（并类似数字，前后被插入空格）

**Comment by Kenshin** [comment]
嗨，收到，不过建议把 URL 也告诉我下。

**Comment by auniel** [comment]
部分链接如下
https://www.sciencedirect.com/science/article/pii/S0147596714001218#s0030

**Comment by Kenshin** [comment]
收到，优化后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，这个问题解决了，你可以安装 [英文阅读版面辅助增强](https://github.com/Kenshin/simpread/issues/2840)。

![image](https://user-images.githubusercontent.com/81074/133365550-ba9d9bd6-3d27-4524-8af4-984e48e7387a.png)

> 同时也可以使用下面两个跟英文阅读有关系的内容：

- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H)

- [适配扇贝阅读的适配站点](https://github.com/Kenshin/simpread/discussions/2705)

***

我将关闭这个 issues，有任何问题随时在这里联络我。
