### ISSUE TITLE
请问simpread软件的思维导图是用什么软件做的？

### ISSUE THREAD

**Issue by kumiao** [Kenshin/simpread#26]
这个问题无关bug，但是我很想知道作者是用什么软件做的思维导图？不会是Photoshop吧？

**Comment by Kenshin** [comment]
作为一个 Developer 来说，PS 之流的是硬伤... 
脑图是用 https://coggle.it/ 生成的，不错的产品，我已经用了好几年了。

例如：

[![](https://camo.githubusercontent.com/57dfcff6f24a468b3feed71341fc118882a47791/687474703a2f2f692e696d6775722e636f6d2f45374d767651762e706e67)](https://github.com/Kenshin/gnvm)

**Comment by biezhi** [comment]
我也想问这个问题，感谢 ❤️
