### ISSUE TITLE
ubuntu  toc menu font size 

### ISSUE THREAD

**Issue by qsLI** [Kenshin/simpread#260]
![image](https://user-images.githubusercontent.com/6805785/37879407-25dc3508-30ab-11e8-97ef-d22043db2eb1.png)

**Comment by qsLI** [comment]
chrome Version 65.0.3325.181 (Official Build) (64-bit)
ubuntu 16.04 LTS

**Comment by qsLI** [comment]
font size of the toc is to small

**Comment by Kenshin** [comment]
感谢反馈~
你可以通过修改样式解决，或者等待下个版本的发布。 😀

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
1.1.1 将 TOC 转移到了左侧，解决了偶尔被遮挡的问题。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
