### ISSUE TITLE
【更新信息及时获取问题】 目前所有的RSS 链接均无法访问

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2608]
目前的RSS链接都访问不了
![image](https://user-images.githubusercontent.com/23255790/127585762-96cd7c97-b734-4322-9630-dd956760d274.png)

**Comment by Kenshin** [comment]
emm... 

确实有点问题，有时间确实下。

**Comment by Kenshin** [comment]
嗨，我测试了下，应该是没有问题的，需要你的网络畅通。😂

跟 Developer 是一个「问题」，我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
补充一个截图

https://rss.simpread.pro/feed

![image](https://user-images.githubusercontent.com/81074/127653796-e4ee3a2a-9e80-4b83-b4a9-229024f9b854.png)
