### ISSUE TITLE
【代码增强插件问题】微信代码段某些页面的支持有问题，出现多余内容并且没有高亮

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2609]
测试链接：https://mp.weixin.qq.com/s/CrIHmXWSqvVj7hB1alZliw

![image](https://user-images.githubusercontent.com/23255790/127631434-d699f2a7-cf98-43d5-aefb-d124b59b8a7a.png)

**Comment by Kenshin** [comment]
哈哈，你太能提 Issues 了，我还想啥时候提这个呢？

这是个已知 Issue 我统一到了 https://github.com/Kenshin/simpread/issues/500

（因此我会关闭这个 Issues，修复后我会逐一通知大家。
