### ISSUE TITLE
打开阅读列表有个授权码，这是什么？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2610]
@Kenshin 请问大佬，打开阅读列表有个授权码，这是什么？我把UID、license那些都试了一遍还是不对
![image](https://user-images.githubusercontent.com/47046461/127729169-450fb858-d3a8-41e7-86d5-17f7682745a4.png)

另外下面这个配置的教程在哪里，找了一圈没找到
![image](https://user-images.githubusercontent.com/47046461/127729190-9ba52ae5-266f-49f4-92d9-486653d6ed15.png)

_Originally posted by @jueshikuangshen in https://github.com/Kenshin/simpread/issues/2406#issuecomment-890291614_

**Comment by Kenshin** [comment]
@jueshikuangshen

嗨，我把你之前的 Issues 删除了，并新建到了这里。（因为跟之前的 Issues 主题不符）

***

至于你说的问题，授权码是你的密码，你没有设置的话，是不存在的，需要使用 UID 登陆，看下图

![image](https://user-images.githubusercontent.com/81074/127731450-5d11d4c6-5b49-4c18-8a57-139ffe4d5bc3.png)

**Comment by jueshikuangshen** [comment]
谢谢，我发现一个奇怪的现象：
从下图的位置进入个人主页，把ID当成授权码就能登进去。但点击超链接`https://simpread.pro/@<;xxxxx>/reading/<295->`，输入同样的ID却显示密码错误？
![image](https://user-images.githubusercontent.com/47046461/127735055-1af550ba-a209-4f0b-a71a-cf50d0030550.png)


<br>
<br>
<br>

![image](https://user-images.githubusercontent.com/47046461/127735140-9270e03e-d09b-4896-8bb8-6c73bf39a453.png)

**Comment by jueshikuangshen** [comment]
> @jueshikuangshen
> 
> 嗨，我把你之前的 Issues 删除了，并新建到了这里。（因为跟之前的 Issues 主题不符）
> 
> 至于你说的问题，授权码是你的密码，你没有设置的话，是不存在的，需要使用 UID 登陆，看下图
> 
> ![image](https://user-images.githubusercontent.com/81074/127731450-5d11d4c6-5b49-4c18-8a57-139ffe4d5bc3.png)

请问密码在哪里能看到或修改，我登录到简悦开放平台没找到

**Comment by Kenshin** [comment]
登陆 https://simpread.pro/developer 后看下图

![image](https://user-images.githubusercontent.com/81074/127736879-eb88c888-386c-4cb4-ad1b-6a73a8dfc26e.png)

**Comment by SeyeeL** [comment]
> @jueshikuangshen
> 
> 嗨，我把你之前的 Issues 删除了，并新建到了这里。（因为跟之前的 Issues 主题不符）
> 
> 至于你说的问题，授权码是你的密码，你没有设置的话，是不存在的，需要使用 UID 登陆，看下图
> 
> ![image](https://user-images.githubusercontent.com/81074/127731450-5d11d4c6-5b49-4c18-8a57-139ffe4d5bc3.png)

我现在也有这个问题，我第一次登录没有密码，但是选择uid登录除了uid还需要输入liscence，这个liscence是我购买的高级账户的那个码吗，但是好像用过之后就失效了吧

**Comment by Kenshin** [comment]
> 我现在也有这个问题，我第一次登录没有密码，但是选择uid登录除了uid还需要输入liscence，这个liscence是我购买的高级账户的那个码吗，但是好像用过之后就失效了吧

**License 使用一次后，无法再次通过它升级为高级账户**，但不妨碍它的其它途径使用。

> 这个liscence是我购买的高级账户的那个码

是的，至于如何找到它，以及如何开通 API，建议看这个教程（整个过程不会超过5分钟，只是教程写的比较细） https://github.com/Kenshin/simpread/discussions/2757

**Comment by Kenshin** [comment]
@jueshikuangshen

嗨，因为有了 https://github.com/Kenshin/simpread/discussions/2757 这个教程，所以我关闭这个 Issues 了。

**Comment by SeyeeL** [comment]
![image](https://user-images.githubusercontent.com/71479570/132080784-bb8eafa3-e429-48f6-bab9-6936fbafc3ea.png)
uid是在账户里复制的，License是在少数派订单复制的，但是提示错误

**Comment by Kenshin** [comment]
> uid是在账户里复制的，License是在少数派订单复制的，但是提示错误

emmm... 看提示应该还是输入错误，请重新确认输入时 UID / License 的顺序，或者确保你的 UID 正确。
