### ISSUE TITLE
infoq 代码片段的换行会丢失

### ISSUE THREAD

**Issue by yeuleh** [Kenshin/simpread#2617]
如题的问题，例如
https://www.infoq.cn/article/NHEwmQkQWG1zcEigP9Jv
原始模式下代码块如下
![image](https://user-images.githubusercontent.com/2578819/127758340-d8fc8041-a500-4b64-9f96-7424b544d676.png)

阅读模式时代码块全部变成了单行
![image](https://user-images.githubusercontent.com/2578819/127758325-90272742-f056-469c-9e92-661863cb14a9.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
