### ISSUE TITLE
【建议】非常建议对 CSDN 博客 网站进行适配，提升阅读体验

### ISSUE THREAD

**Issue by Ctipsy** [Kenshin/simpread#262]
非常建议对 CSDN 博客 网站进行适配，且该网站的访问量相当高

**Comment by s7ev3n** [comment]
遇到同样问题，blog.csdn.net无法使用

**Comment by Ctipsy** [comment]
@Kenshin   可是打开`CSDN`的博文，依然是原始风格，只能用`临时阅读模式`或`聚焦模式`，难道是我打开的方法不对

**Comment by Kenshin** [comment]
估计是结构改变了，最好能告诉 URL ，这样方便修改。
另外，也可以通过站点编辑器自行修改。

**Comment by Ctipsy** [comment]
@Kenshin  csdn站点：https://blog.csdn.net/

测试博客链接：https://blog.csdn.net/csdnsevenn/article/details/79545851

**Comment by Kenshin** [comment]
好，明天看一下，估计近期要更新一批站点了。

**Comment by ivysrono** [comment]
我怀疑是你适配的 http:// 但访问的是 https://

**Comment by Ctipsy** [comment]
@ivysrono   我也考虑过这个问题，但不确定。   @Kenshin 不过chrome现在不都默认是https://访问吗

**Comment by Kenshin** [comment]
各位，的确是由于 https 引起的，修改方法如下：

![image](https://user-images.githubusercontent.com/81074/37942742-361fbe4c-31a7-11e8-91a2-d23cf108373f.png)

另外，我会更新 csdn 的官方源，不了解如何修改的朋友，到时候我会通知你们~

**Comment by Ctipsy** [comment]
@Kenshin 感谢

**Comment by ivysrono** [comment]
Firefox用户无所谓，自带的阅读模式对csdn支持就很好。

**Comment by Kenshin** [comment]
@ivysrono 
但自带的阅读模式并不能提供更好的服务，而简悦却可以。 😀

**Comment by ivysrono** [comment]
建议把规则独立出来，变成广告过滤这样的列表，让大家可以来贡献规则，甚至维护自己的订阅列表。

**Comment by Kenshin** [comment]
@ivysrono 
已经是这样的了，类似  uBlock 的订阅方式，但主适配列表未分享，分享的只是 `官方次适配列表` 详细请看 [站点适配源](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E9%80%82%E9%85%8D%E6%BA%90)

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
