### ISSUE TITLE
控制栏样式在  ruanyifeng.com 有错误

### ISSUE THREAD

**Issue by lyfer233** [Kenshin/simpread#2626]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 windows10

- 浏览器版本  Chrome 版本 92.0.4515.107（正式版本） （64 位）

- 简悦版本 2.2.0

- 发生问题的地址 http://www.ruanyifeng.com/blog/2019/09/curl-reference.html

**请描述你的问题**

右侧那个栏，有这种黑色图标，而且有菜单栏有偏移。。。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![QQ截图20210802191242](https://user-images.githubusercontent.com/24930135/127853269-39a0c383-989d-42de-a234-88b15bb64f08.png)
![123](https://user-images.githubusercontent.com/24930135/127853360-aa79033f-6c02-44d6-afa0-225037204bce.png)

**Comment by Kenshin** [comment]
嗨，把下面的代码

```
fab ul li {
    list-style-type: none!important;
}
```

加入到 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 里面即可。

**Comment by lyfer233** [comment]
> 嗨，把下面的代码
> 
> ```
> fab ul li {
>     list-style-type: none!important;
> }
> ```
> 
> 加入到 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 里面即可。

OK 完全解决问题~

**Comment by Kenshin** [comment]
嗨，回复效率好高~

PS：我关闭此 Issues 了。
