### ISSUE TITLE
新浪和网易的新闻页貌似都不适配了

### ISSUE THREAD

**Issue by sunwei922** [Kenshin/simpread#263]
新浪和网易的新闻页貌似都不适配了

**Comment by Kenshin** [comment]
有些页面结构改变了，这几天准备集中更新一批了~

**Comment by sunwei922** [comment]
辛苦了，谢谢。

**Comment by Kenshin** [comment]
@sunwei922 
如果懂前端的话，自行修改也可以~

**Comment by sunwei922** [comment]
略懂皮毛，我试试

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
