### ISSUE TITLE
无法保存到印象笔记

### ISSUE THREAD

**Issue by github2016xa** [Kenshin/simpread#264]
使用简悦打开知乎页面后，无法保存到印象笔记，显示保存失败

**Comment by Kenshin** [comment]
感谢反馈，这部分的原因请参考 [这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

**Comment by Kenshin** [comment]
没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
