### ISSUE TITLE
高级账户，无法导出原生PDF？

### ISSUE THREAD

**Issue by qq1120637483** [Kenshin/simpread#2640]
一直报错，请开启同步助手功能

**Comment by qq1120637483** [comment]
![image](https://user-images.githubusercontent.com/57215916/128601157-4f5bdcc3-f377-46cb-b3ae-0a966c389a52.png)

**Comment by qq1120637483** [comment]
就无法开启这个功能！！！

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/discussions/1700

**Comment by qq1120637483** [comment]
我开启同步助手了，你们软件的问题
