### ISSUE TITLE
同步助手已经运行，还是无法验证，还是提示让运行同步助手？

### ISSUE THREAD

**Issue by qq1120637483** [Kenshin/simpread#2641]
同步助手已经运行，还是无法验证，还是提示让运行同步助手？

**Comment by Kenshin** [comment]
嗨，看看是不是 https://github.com/Kenshin/simpread/discussions/1567 引起的？

**Comment by Kenshin** [comment]
如果是跟 https://github.com/Kenshin/simpread/issues/2640 关联问题的话，请不要重新建立新的 Issues。

还有，你给出的信息太少，我没法判断，请给出详细说明或者截图。
