### ISSUE TITLE
导出到notion只有标题

### ISSUE THREAD

**Issue by zydhhh** [Kenshin/simpread#2643]
- 操作系统   Windows 10 

- 浏览器版本 Microsoft Edge 版本 92.0.902.67 (官方内部版本) (64 位)

- 简悦版本 2.2.0

- 发生问题的地址 https://www.economist.com/leaders/2021/08/07/the-chip-shortage-is-a-self-solving-problem

**请描述你的问题**

[此篇文章](https://www.economist.com/leaders/2021/08/07/the-chip-shortage-is-a-self-solving-problem)在导入到notion只有标题， ~~尝试其他页面时没有发生问题，~~ [这篇文章](https://www.economist.com/science-and-technology/2021/08/04/robots-are-poised-to-start-unloading-lorries/21803299)也无法正常导出，导出为markdown都会出现问题，但[这篇文章](https://www.economist.com/science-and-technology/2021/08/04/robots-are-poised-to-start-unloading-lorries/21803299)可以正常导出，都是经济学人网站上的内容，也许是页面内容导致的奇奇怪怪的bug
阅读模式时
![image](https://user-images.githubusercontent.com/25688118/128631973-53172656-dabe-4384-b532-b3e25522952e.png)
导入notion后
![image](https://user-images.githubusercontent.com/25688118/128631990-e7bbc2cc-e092-47b5-8fb1-d954eb7e251f.png)

**Comment by Kenshin** [comment]
嗨，我测试了下，确实有这个问题，因为使用了私有 API，所以有可能不稳定。

你可以这样解决：

1. 复制 md 到剪切板，然后在粘贴到 Notion
2. 通过同步助手导出为 docx，然后在 Notion 再导入

**Comment by zydhhh** [comment]
> 嗨，我测试了下，确实有这个问题，因为使用了私有 API，所以有可能不稳定。
> 
> 你可以这样解决：
> 
> 1. 复制 md 到剪切板，然后在粘贴到 Notion
> 2. 通过同步助手导出为 docx，然后在 Notion 再导入

**Comment by zydhhh** [comment]
> 嗨，我测试了下，确实有这个问题，因为使用了私有 API，所以有可能不稳定。
> 
> 你可以这样解决：
> 
> 1. 复制 md 到剪切板，然后在粘贴到 Notion
> 2. 通过同步助手导出为 docx，然后在 Notion 再导入

貌似问题是由markdown引起的，导出为markdown或复制markdown都只有标题。

**Comment by zydhhh** [comment]
我继续试了一下，发现另一个问题。还是在[此页面](https://www.economist.com/leaders/2021/08/07/the-chip-shortage-is-a-self-solving-problem)，屏蔽任意元素后，刷新页面后也只剩标题，正文内容全都没了；此时重新选取高亮正文区域，刷新后正文内容出现，之后再导出markdown可以正常导出正文内容；但此时由于选取高亮区域时包含了原页面旁边的几个社交媒体图标，阅读模式里也有这几个突兀的图标，手动屏蔽掉后，继续出现之前的问题，只剩标题，貌似软件无法很好识别页面内容

**Comment by Kenshin** [comment]
> 我继续试了一下，发现另一个问题。还是在[此页面](https://www.economist.com/leaders/2021/08/07/the-chip-shortage-is-a-self-solving-problem)，屏蔽任意元素后，刷新页面后也只剩标题，正文内容全都没了；此时重新选取高亮正文区域，刷新后正文内容出现，之后再导出markdown可以正常导出正文内容；但此时由于选取高亮区域时包含了原页面旁边的几个社交媒体图标，阅读模式里也有这几个突兀的图标，手动屏蔽掉后，继续出现之前的问题，只剩标题，貌似软件无法很好识别页面内容

嗨，隐藏任意元素的功能可能有些问题，因为不太够智能，你可以使用 https://github.com/Kenshin/simpread/discussions/2500 提供的思路，应该不会有此问题了。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311

**Comment by Kenshin** [comment]
嗨~

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Notion 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![Notion Configs](https://user-images.githubusercontent.com/81074/196083084-22384ded-73a8-42c4-9b1b-13262ed155ab.png)

> 针对新用户的一步到位的 Notion 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Notion 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Notion

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Notion

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Notion

4️⃣ 导入到 Notion 的内容包含：题图、Favicon、标签、原文地址等丰富的元数据信息

5️⃣ 内置 Notion 测试账户

## 📖 区别

![img](https://imgs.zhubai.love/bd83e21f5c0e43bea0517c88c025211c.png)

## 📘 极速版

🔗 [Github ](https://github.com/Kenshin/simpread-configs/blob/main/notion@base/Getting%20Started.md)| [语雀](https://www.yuque.com/kenshin/simpread/ewaflu)

不需要同步助手，无任何配置，导入全文到 Notion，并支持 Database Page，适合 Notion + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/notion@enhance/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/odhlf2)

不需要同步助手，无任何配置，导入全文到 Notion（包含：题图、Favicon、标签、原文链接等丰富的元数据信息），自动同步标注，适合 Notion + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/notion@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/zuptv2)

需要同步助手，几乎无任何配置，包括基础版全部功能，并具有本地快照功能。

# 📺  引申：导入到 Notion - 简悦官方有声视频教学

![img](https://imgs.zhubai.love/6ed78f485f2c4c21add9244987e39986.png)

高级版的功能也可以看看简悦推出的视频教程，细节 [请看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-3356081) ⤴️。

**Comment by Kenshin** [comment]
👋 嗨

> 比扩展端更好用的 [简悦插件 · 导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) 已经正式发布 🎉 ，以下是这个插件的正式介绍，已经使用过此插件的用户建议重新安装。（功能没有区别，只是细节略做调整）

# 🔌 插件端

插件端拥有比扩展端更灵活的方案，也是简悦官方建议首选方案关于插件端的详细说明 [请看这里](https://simpread.pro/docs/#/Notion)。

## 🔗 链接

[文档](https://simpread.pro/docs/#/Notion) | [知乎](https://zhuanlan.zhihu.com/p/594431249) | [竹白](https://simpread.zhubai.love/posts/2219392676124688384) | [QQ 频道](https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1XeeVt4vu23&contentID=cedma&businessType=2&from=181174&shareSource=5&biz=ka) | [即刻](https://web.okjike.com/originalPost/63aa97be5fe8890be9101e19) | [推特](https://twitter.com/wanglei001/status/1607634103167508482) | [推特社区](https://twitter.com/wanglei001/status/1607633774183079937) | [知乎视频](https://www.zhihu.com/zvideo/1590744209203687424) | [B 站视频](https://www.bilibili.com/video/BV18e4y1j7Ps/)

## 📥 地址

https://simpread.ksria.cn/plugins/details/OpaogjT8KJ

## 🔎 与扩展端的区别

![](https://imgs.zhubai.love/556ec9eff25542aabd318a8803ed70db.png)

通过上表可以看到，除了无法在稍后读中使用外（下个版本支持），扩展端具有的功能，插件端也都具有，但插件端还可支持随时更改不同的 Page 功能。

同时，因为插件的更新不依赖与扩展端，可随时更新，具有更好的时效性。

## ⌨️ 快捷键

1️⃣  `n t` → [一键导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=导入正文)

2️⃣  `q n t` → [选择不同的 Page 后导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=选择任意Page导入)

3️⃣ `z n t` →  [配合自动化辅助增强插件使用](https://simpread.pro/docs/#/Notion?id=当加入稍后读时自动导入)

## 🔌 功能

1️⃣ 可获得 Notion 的个级目录

2️⃣ [图床](https://simpread.pro/docs/#/Notion?id=%E5%9B%BE%E5%BA%8A)

3️⃣ 导入正文到 Notion

4️⃣ [选择不同的 Page 后导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8Fpage%E5%AF%BC%E5%85%A5)

## 💡 用法

1️⃣ 快捷键导入

2️⃣ [手动导入](https://simpread.pro/docs/#/Notion?id=%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5)

3️⃣ [加入稍后读时自动导入](https://simpread.pro/docs/#/Notion?id=%E5%BD%93%E5%8A%A0%E5%85%A5%E7%A8%8D%E5%90%8E%E8%AF%BB%E6%97%B6%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%85%A5)

4️⃣ [在 Assistive Touch 设置 Icon 方便一键导出](https://simpread.pro/docs/#/Notion?id=%E6%94%AF%E6%8C%81-assistive-touch) 

📈 安装与升级
---

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

***

最后，有任何问题可继续讨论。😄

**Comment by Kenshin** [comment]
嗨

> 两个关于 Notion 的相关更新~

# 1️⃣ 祝：[导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) + [导入到 Notoin 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572) 下载量**超 60K！**

![image](https://user-images.githubusercontent.com/81074/212005885-67a4a8bb-9779-4aa2-bbab-15b5d12717bd.png)

# 2️⃣ 导入到 Notion + 导入到 Notoin 辅助增强插件 双叒叕 小幅更新了版本

> 虽然没有新功能，但更新了一些**查找逻辑**，建议升级（如何更新下面有说明）

## 🔌 [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954)  v1.0.3

• `Optimize` 导入到 Notion 逻辑

• `Fix` 当加入稍后读并且修改稍后读标题后仍按照原标题保存的错误

## 🔌 [导入到 Notoin 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572)  v1.2.3

• `Optimize` 题图、Favicon 因不是以 http 导致优化失败的问题。

• `Optimize` 当 Token 或 Page ID 填写错误时的精准提示。

• `Optimize` 使用 `url` 作为增强导出是否是同一 Page 的判断标注。

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过上面的链接安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

3️⃣ 如果已安装上述插件，需要使用 插件管理器升级的话 [请看这里](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C)。

**Comment by Kenshin** [comment]
嗨

## [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) 1.1.0 版发布了 🎉  

### ▎ 如果你在使用简悦导入 Notion 无法使用 Notion 图床的话，请看此解决方案。

### ▎内置 Cloudinary 图床（用来替代 Notion 图床），国内访问速度不错，免费份额足够个人使用。为什么这么做，看下面的说明

***

## 📖  写在前面

Notion 图床使用了 Notion 私有 API（甚至于导入到 Notion 也是如此 ），但 **Notion 私有 API 并没有那么稳定，基本上 Notion 每次大的升级都会造成无法使用的问题，差不多每年 1~2 次。** 比如：

- **2022年7月23日 [标题含有 CJK 字符就会出现无法保存的问题](https://github.com/Kenshin/simpread/issues/4237)**，但好在这次事件 Notion 官方快速修复了。

- **2022年12月6日 [因为 API 后端参数修改导致无法导入到 Notion Page 的问题](https://github.com/Kenshin/simpread/issues/4849)** 导致了「坏」了很久很久（现在已经好使了）

- **2023年9月7日 [发生了 Notion 图床无法使用的问题](https://github.com/Kenshin/simpread/issues/5917)（截至到现在仍未好使）**

因为是私有 API 所以 Notion 官方的任何改动都「合理」，毕竟理论上这些 API 只有 Notion 自己用。

但对于简悦来说就非常被动了，2022年12月6日后为了杜绝这个问题，简悦发布了 [导入到 Notion 插件](https://github.com/Kenshin/simpread/discussions/4954)，脱离了扩展端，因而能更快的响应 Notion API 的无故改动，但毕竟仍受 Notion 的「制约」，进而发生了这次 Notion 图床事件，导致无法使用...

## 💡 解决方案

为了不再一次次的被动，所以在【导入到 Notion 插件 1.1.0 版】 **增加了 Cloudinary 图床方案**，不再绑定 Notion 从而彻底的解决了这个问题。

对于用户来说，仅需要注册 Cloudinary 图床，而注册一个图床的时间远比被动折腾要简单很多。

## 🔐 权限

使用 Cloudinary 图床 **需要调用简悦自己的服务器，所以仅针对高级账户权限**，如有必要 [请升级为高级账户](https://simpread.pro/price)。

## 🗂 Cloudinary 图床

[Cloudinary](https://cloudinary.com/) 是老牌的图床服务，**免费版每月 25 Credit，每个 Credit 可支持 1GB 存储或 1GB 带宽**。

相当于：**每月 13GB 存储**以及 **12GB 带宽**的图床，且**国内访问速度不错**，免费份额足够个人使用。

## 🔌 配置

请看 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995 内有详细说明。

如果你动手能力稍强的话，甚至于都不需要看任何教程，直接注册登录 &  打开 [Dashboard 页面](https://console.cloudinary.com/console) 即可，留意下图

<img width="2942" alt="2023-09-27_11-39-14" src="https://github.com/Kenshin/simpread/assets/81074/29f6003c-c45d-49df-8bc5-f10c6d76253f">

请将 ➊ ➋ ➌ 分别填入。

注意：Folder 文件夹可为空，也可为任意值（ 建议使用 `simpread` ），不必事先在 Cloudinary 创建相应目录。

## 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 🔗 关联

https://github.com/Kenshin/simpread/issues/4955

**Comment by Kenshin** [comment]
嗨，导入到 Notion 发布了全新的 2.0 版，应该可以解决此问题

![](https://imgs.zhubai.love/5ccaad4e75ac4610b11c966cb45f8484_2072964972706709504.png)

# 🆕 全新 2.0 版

在 2024 年 11 月 16 日，Notion 私有 API 再次出现无法使用的问题，这让我决定**彻底弃用私有 API 方案，全面转向公开 API**。

由于采用公开 API，确保了功能的稳定性，不会再出现无法使用的情况，以下所有功能均基于 2.0 版本的描述。

# 🌟 特色

与其他同类产品相比，**简悦凭借其出色的阅读模式，可以更精准地将全文导入到 Notion**。

由于采用了公共 API，解决了 1.0 版本无法无法正确转换 LaTeX 公式的问题，并提供更安全简便的一键授权方式（相比私有 API，避免了账户泄漏风险）。

此外，还支持以下功能：

1️⃣ 在 Notion Page 显示描述、题图、Favicon、来源、标签、备注

2️⃣ 内置图床

3️⃣ 导入带标注颜色的全文 [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

4️⃣ 导入标注（支持三种方式）

5️⃣ 支持超长文章的导入、[知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229)、[表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74)（使用私有 API 的产品都存在无法使用的问题）

# 📥 导入效果

[https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897](https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897&pvs=74)

# 📚 一站式教程

[https://www.yuque.com/kenshin/simpread/zx3bcz](https://www.yuque.com/kenshin/simpread/zx3bcz)

# 📦 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

如果你需要使用简悦 + Notion 的话，可以直接看 [此配置库](https://www.yuque.com/kenshin/simpread/mwda8s) 。

# 🔌 介绍

导入到 Notion 相关功能分为两个插件：

📗 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

📘 [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU)

# 📖 功能

1️⃣ 可导入当前页面的题图、Favicon、来源等。

![img](https://imgs.zhubai.love/92778b3c8dcc4b1ab1120e1dbf780d33_2072964972706709504.png)

2️⃣ 导入正文到 Notion，因为使用了公开 API，所以可以完美适配 [知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229) · [表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74) 

3️⃣ 导入**带标注色的正文**到 Notion [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

> 此功能需要 **简悦高级账户**，可通过 [**此链接**](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/c6aa20e1b1814399b9e87b569ebdb3b5_2072964972706709504.png)

4️⃣ 内置 Cloudinary 图床

![img](https://imgs.zhubai.love/85901d6d7ed74b598b1b75ab81b59754_2072964972706709504.png)

5️⃣ 在导入可选择任意 Notion

![img](https://imgs.zhubai.love/2864ffa0f9134a4b8c99116cdf12c41f_2072964972706709504.png)

6️⃣ 同步稍后读的标签，并支持加入全局标签（即使当前页面未被标记为稍后读，也可导入已添加的全局标签）。

![img](https://imgs.zhubai.love/0cda01a5740a4c35b80391dc1ac971e5_2072964972706709504.png)

7️⃣ 添加描述（Summary）与稍后读备注（Note）

> 此功能需要 **简悦高级账户**，可通过 [此链接](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/d1d8cbad7ef94f169095039cd18b9b23_2072964972706709504.png)

8️⃣ 去除重复的 Page

![img](https://imgs.zhubai.love/58668edcf264416ea6dc2d97069ce2b0_2072964972706709504.png)

9️⃣ 导入标注

![img](https://imgs.zhubai.love/59ffe6d7a1644d83ab40f2d6bc06597e_2072964972706709504.png)

2.0 版在原来的方案（[标准模式](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)）基础上增加了两个全新的标注模板：

📗 带标注色的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f5881ada61bc11c25596f1d?pvs=74)

📘 按照标注色分类的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f58814da34fd7e2e0cb9d96?pvs=74)

![img](https://imgs.zhubai.love/fc42ca0d3dc94186b02e6737febdde51_2072964972706709504.png)

注意：上述两种标注模板需要**简悦高级账户**权限，可通过 [此链接](https://simpread.pro/price) 升级。

# 🔄 旧版本升级说明

如果你已使用 1.x 版（旧版本），首次升级后会出现如下截图，此时需重新授权 Notion 才能使用。（授权方式与上面一致）

![img](https://imgs.zhubai.love/fea50a3a372d47098655eddf70022cc7_2072964972706709504.png)

# 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可直接 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)  [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

#  🔎 关联 

https://github.com/Kenshin/simpread/issues/4955

***

有任何问题，请随时在这里讨论~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
