### ISSUE TITLE
部分语言代码不会高亮 比如Scala?

### ISSUE THREAD

**Issue by Jface001** [Kenshin/simpread#2647]
没有高亮的网站:https://blog.csdn.net/high2011/article/details/52502552
截图如下
原始网页
![image](https://user-images.githubusercontent.com/21217483/128709287-e6208e98-1ad7-416c-ad28-eaf61ca2cd1b.png)

启用后
![image](https://user-images.githubusercontent.com/21217483/128709374-7640f8d5-b40c-4a29-99b2-bc8a76834d13.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
