### ISSUE TITLE
知乎专栏页面结构改变，需要新匹配

### ISSUE THREAD

**Issue by Ctipsy** [Kenshin/simpread#265]
测试网址：https://zhuanlan.zhihu.com/p/25296087

**Comment by billysun76** [comment]
+1

**Comment by Kenshin** [comment]
感谢反馈，今天会集中处理一批无法适配的页面，晚些时候会告诉大家，另外，也可以通过 `站点编辑器` 自己修改~

**Comment by Kenshin** [comment]
你好，久等了，此问题已经修复，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

**Comment by mage0535** [comment]
手动更新后去zhihu打开还是没亮红啊

**Comment by Ctipsy** [comment]
@mage0535   我试了，可以啊

**Comment by Kenshin** [comment]
@mage0535
手动更新了吗，也可以看看 选项页 → 关于，看看是否更新为 24X 个站点了？

**Comment by mage0535** [comment]
单位电脑试的，昨天手动同步过了，也提示为最新的了，昨天一直没红，下班时候习惯性把chrome关了，早上来了后重新打开发现红了，难道更新完还需要重启chrom吗？

**Comment by Kenshin** [comment]
不需要重启 Chrome … 另外，即便是之前结构改变了，它也是为红色的。

**Comment by Kenshin** [comment]
更新完，需要刷新当前页面，并且当前页面唯一（即：没有多开的情况）
正如你说，实在不行就重启大法… 😄😅💊
