### ISSUE TITLE
每次打开同步助手都会报错

### ISSUE THREAD

**Issue by xlx0406ll** [Kenshin/simpread#2652]
![屏幕截图 2021-08-11 162230](https://user-images.githubusercontent.com/66156446/128999949-66bdb064-6824-4f60-b9e4-c51b4981dd33.png)
扩展版本为2.2.0，同步助手版本为1.0.1

**Comment by Kenshin** [comment]
嗨，你应该是双开了（请看右下角是否有两个 ![image](https://user-images.githubusercontent.com/81074/129023665-4e5aac2e-1590-4251-84b6-a0e4bb54bcd9.png)
