### ISSUE TITLE
希望站点编辑器下一页上一页支持点击按钮【执行js代码，比如$(btn).click()】

### ISSUE THREAD

**Issue by XQDD** [Kenshin/simpread#2653]
![image](https://user-images.githubusercontent.com/20871761/129044497-3b55f696-6e95-4a8f-b854-5d9f1110c290.png)

**Comment by Kenshin** [comment]
当你适配了站点适配器的 上/下一页后，点击后自动翻页

![image](https://user-images.githubusercontent.com/81074/129128457-66b69f8c-4f42-42d4-a879-c1aef707875c.png)

![image](https://user-images.githubusercontent.com/81074/129128466-8eb62006-42aa-4678-abdb-7089691df2b8.png)

PS：你想要实现什么样的效果？

**Comment by XQDD** [comment]
这里指定的是链接的值吧而不是直接点击了按钮吧（按钮没有链接==），我直接指定截图中的两个按钮，跳转的到页面很奇怪

**Comment by Kenshin** [comment]
> 这里指定的是链接的值吧而不是直接点击了按钮吧（按钮没有链接==），我直接指定截图中的两个按钮，跳转的到页面很奇怪

我看了下截图的内容，应该是可以的。你要是对适配规则感兴趣的话，把 URL 发给我，我帮你适配下，然后跟你自己的对比下，这样方便你的理解。

**Comment by XQDD** [comment]
https://juejin.cn/book/6844723704639782920/section/6844723704753029133
@Kenshin 可以试试，我试了不行

**Comment by Kenshin** [comment]
emmm

已确认确实有问题，因为掘金的翻页不是 `<a>` 方案，所以有问题，我会出这个插件解决这个问题。

**Comment by Kenshin** [comment]
嗨，掘金小册的插件和适配规则已经完成，如何使用请看这里  https://github.com/Kenshin/simpread/issues/2697
