### ISSUE TITLE
[使用问题] 当使用离线html后，导出到notion，图片为base64，导致图片无法显示的问题

### ISSUE THREAD

**Issue by Sharewithyou** [Kenshin/simpread#2655]
操作系统 Windows7

浏览器版本 e.g. Chrome 78.0.3904.108

简悦版本 2.2.0.520_0

同步助手 1.01

使用流程，加入稍后读，自动化生成离线html，然后在本机进行标注，标注完毕后，将标注同步至notion，通过导出markdown发现，图片取自离线Html的base64，目前notion 并没有识别出来图片，导致图片无法显示且文件体积较大。

如果直接在加入稍后读的流程中配置导出到notion 可以走系统的图床设置

**Comment by Kenshin** [comment]
嗨，你的意思是：

导入到 Notion 时使用了 Notion 自带的图床方案？

***

我刚才做了个测试

![image](https://user-images.githubusercontent.com/81074/129161075-72f130d8-1448-4230-ae12-132a078d96be.png)

加入到稍后读后，离线 HTML 与 Notion 以及标注肯定是没问题的（不是 base64 结构）

请问你能稳定重现吗？

***

离线 HTML，当生成 base64 后全部完毕后，会将 base64 在还原为正常的图片结构。所以，标注时，自然没问题的。

**Comment by Kenshin** [comment]
另外 https://github.com/Kenshin/simpread/issues/2602 你提的 Issues 我回复了你，但没有反馈给我~

**Comment by Sharewithyou** [comment]
可以稳定重现，首先 当导出为离线Html后  离线html文件存储的都是base64的格式
![image](https://user-images.githubusercontent.com/23255790/129170432-ee9a8dd4-66c7-48bb-9601-c8f9692a2807.png)

再去做标注 然后保存markdown  或者再去同步标注到notion 会携带的是base64的格式 导致图片在Notion不可见 
![image](https://user-images.githubusercontent.com/23255790/129170669-228390cd-7dd7-458b-b41c-73ffc9cf9421.png)

**Comment by Sharewithyou** [comment]
> 另外 #2602 你提的 Issues 我回复了你，但没有反馈给我~

除了直接关闭目录  这个我看说的是 下个版本 或者 插件处理  现在有方案了么

**Comment by Sharewithyou** [comment]
> 另外 #2602 你提的 Issues 我回复了你，但没有反馈给我~

除了直接关闭目录  这个我看说的是 下个版本 或者 插件处理  现在有方案了么

**Comment by Kenshin** [comment]
> 再去做标注 然后保存markdown 或者再去同步标注到notion 会携带的是base64的格式 导致图片在Notion不可见

emmm 我明天再试试。

**Comment by Kenshin** [comment]
嗨，我测试了下，确实没有你遇到的问题。

能否把你的自动化截图给我看下，我看看是什么问题。

**Comment by Sharewithyou** [comment]
![image](https://user-images.githubusercontent.com/23255790/129498280-abdc7b41-f9b3-4b32-8211-4315d697eef8.png)
自动化如上

**Comment by Sharewithyou** [comment]
自动化流程原文保存到notion 是没有问题的   然后我在本地进行标注，标注完毕后，修改导出为标注 
![image](https://user-images.githubusercontent.com/23255790/129498718-dab16047-9fd2-4cb2-9a61-2784fe7d82d2.png)
然后导出到Notion
![image](https://user-images.githubusercontent.com/23255790/129498722-9e0340c4-2635-48c1-ab62-a83697be1267.png)
图片导出成了base64 导致notion 不识别

**Comment by Kenshin** [comment]
> 关联问题 [#2664 (comment)](https://github.com/Kenshin/simpread/issues/2664#issuecomment-899183191)

**Comment by Kenshin** [comment]
嗨，我确实没有重现这个问题...

不过，你可以将这两个导出顺序调换下，即：

![image](https://user-images.githubusercontent.com/81074/130553291-f1ae4bbe-4254-4a31-837e-33e1dacbe9c4.png)

在导出离线 HTML 时，会将图片 → base64 当导出后，会自动将 base64 → 图片，所以你可以调换下顺序，看看能否解决。

**Comment by Sharewithyou** [comment]
> 嗨，我确实没有重现这个问题...
> 
> 不过，你可以将这两个导出顺序调换下，即：
> 
> ![image](https://user-images.githubusercontent.com/81074/130553291-f1ae4bbe-4254-4a31-837e-33e1dacbe9c4.png)
> 
> 在导出离线 HTML 时，会将图片 → base64 当导出后，会自动将 base64 → 图片，所以你可以调换下顺序，看看能否解决。

使用场景你可能没有看清楚 ，并不是在初始加入稍后读会有问题，而是只要在导出服务中加了离线Html后，以后的其他导出服务中 就会以base64的格式进行导出，实际的使用场景为 先加入稍后读，导出全文离线html，然后进行有时间的时候进行标注，标注完毕后，再次导出**标注**至notion,就会导致标注的图片因为是base64 导致无法显示

**Comment by Kenshin** [comment]
> 我使用了你提供的配置文件，标注是按照下图设置的。


![image](https://user-images.githubusercontent.com/81074/130601326-601133b3-304b-43ed-a7ab-4e0d026fd8dc.png)

没有复现你说的情况，我再重新说明下：

> 在导出离线 HTML 时，会将图片 → base64 当导出后，会自动将 base64 → 图片。

![image](https://user-images.githubusercontent.com/81074/130601266-6f2faa0c-ee12-4c5c-ab43-ed47f4828051.png)

![image](https://user-images.githubusercontent.com/81074/130601281-8dd17fdd-528f-4ee7-a07c-3fce80a9b3f4.png)

> 这是我录制的一段内容。

https://user-images.githubusercontent.com/81074/130601226-25c58cb1-8fdf-4b84-b0e3-ff0924aa8f20.mp4

> 也就是说，当成功导出离线 HTML 后，会还原为正常图片 URL，再使用其它服务时自然是没问题的。

**Comment by Sharewithyou** [comment]
在网页模式下确实是正常的，折腾了一下，我大致知道问题出现在那个地方了，就是不要在稍后读  本地离线Html 中进行标记，一旦选择了导出离线html,在稍后读中 会优先打开本地的html，这时候，如果在稍后读里面做了标记，就会保存的是本地离线的base64 的图片，逻辑是没有问题的 就是在离线的这个模式中 使用稍后读的方式就不太方便  不知道notion 的私有api 在上传图片的时候，是否可以支持直接传base64的格式并且替换为图床的格式就更方便了 导出到其他平台也一样  对于base64的支持可能不太好 然后本地离线html 也是刚需 不知道后面是否可以考虑下 离线的模式中  导出base64图片的替换问题

**Comment by Sharewithyou** [comment]
> > 我使用了你提供的配置文件，标注是按照下图设置的。
> 
> ![image](https://user-images.githubusercontent.com/81074/130601326-601133b3-304b-43ed-a7ab-4e0d026fd8dc.png)
> 
> 没有复现你说的情况，我再重新说明下：
> 
> > 在导出离线 HTML 时，会将图片 → base64 当导出后，会自动将 base64 → 图片。
> 
> ![image](https://user-images.githubusercontent.com/81074/130601266-6f2faa0c-ee12-4c5c-ab43-ed47f4828051.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/130601281-8dd17fdd-528f-4ee7-a07c-3fce80a9b3f4.png)
> 
> > 这是我录制的一段内容。
> 
>  2021-08-24_18-25-39.mp4 
> > 也就是说，当成功导出离线 HTML 后，会还原为正常图片 URL，再使用其它服务时自然是没问题的。

  在网页端操作是没有问题的 但是 当离线Html后 在稍后读中 默认打开本机文件后  后续对于图片的导出操作就会是base64了 ，逻辑上是没有问题的，但如果后续再想做导出操作，会有不支持base64 以及 文件过大且不好看的问题 , 但是离线html又是刚需，希望能够考虑下 ，是否可以提供导出 base64 - 简单图片路径的方式

**Comment by Kenshin** [comment]
> 在稍后读 本地离线Html 中进行标记

竟然是这个使用情况... 还是问题现象没有描述清楚造成的误差。

***

这个情况肯定不行的了，因为你标注的本身就是只包含 Base64 的页面，在导入到任何生产力工具时都是以 base64 的形式。

**具我所知，目前应该还没有可以支持 base64 导入的生产力工具。**

至于你的的诉求，我认为：

> 离线 HTML 本身就是一种解决方案，没必要在把它导入到其它工具了，你可以把这些离线文件通过同步助手保存到任意网盘即可。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
