### ISSUE TITLE
如何关闭 本文由 [简悦 SimpRead]转码， 原文地址 这一行字

### ISSUE THREAD

**Issue by xingdaining** [Kenshin/simpread#2656]
我在设置里没找到，实在没办法了求助🙏

**Comment by Kenshin** [comment]
嗨，确实没有这个选项 😂 不过，你可以使用 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 自行解决。
