### ISSUE TITLE
麻烦Kenshin查看一下郵箱，时间方便时，予以回覆。

### ISSUE THREAD

**Issue by ericfok1991** [Kenshin/simpread#2659]

**Comment by Kenshin** [comment]
嗨，已经回复你了，处理完后会再次通知你。

**Comment by ericfok1991** [comment]
謝謝

---------
順頌時祺
霍 啟山

------ 原始邮件 ------
来自: "Kenshin Wang" ***@***.***>
收件人: "Kenshin/simpread" ***@***.***>
抄送人: "ericfok1991" ***@***.***>; "Author" 
***@***.***>
发送日期: 2021\8\13 星期五 9:54:24
主题: Re: [Kenshin/simpread] 麻烦Kenshin查看一下郵箱，时间方便时，予以回覆。 (#2659)

**Comment by Kenshin** [comment]
嗨，已经处理完毕，我关闭这个 Issues 了~

**Comment by ericfok1991** [comment]
> 嗨，已经处理完毕，我关闭这个 Issues 了~

沒有收到郵件回覆: (

**Comment by Kenshin** [comment]
> 沒有收到郵件回覆: (

没有邮件，看看你的支付宝就可以了。

**Comment by ericfok1991** [comment]
为什么要看我的支付宝呢？

順頌時祺
霍 啟山

**Comment by Kenshin** [comment]
我每天要收 50+ 的邮件。

所以，我无法对应当前这个 Issues 和 邮件中的回复，请在邮件中附上 Issues id 

（如果你没理解我的回复，大概可能是 Issues 与邮件无法对应上...

**Comment by ericfok1991** [comment]
謝謝Kenshin
Closed #2659 <https://github.com/Kenshin/simpread/issues/2659>.

---------
順頌時祺
霍 啟山

------ 原始邮件 ------
来自: "Kenshin Wang" ***@***.***>
收件人: "Kenshin/simpread" ***@***.***>
抄送人: "啟山" ***@***.***>; "Author" 
***@***.***>
发送日期: 2021\8\13 星期五 13:25:14
主题: Re: [Kenshin/simpread] 麻烦Kenshin查看一下郵箱，时间方便时，予以回覆。 (#2659)
