### ISSUE TITLE
代码高亮出错

### ISSUE THREAD

**Issue by xxxxha** [Kenshin/simpread#2663]
开启“代码段增强”插件后，会改变原始文档中代码段和文本内容的顺序。
例如这边文档：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Functions#sr-toc-11

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
