### ISSUE TITLE
pmcaff申请适配

### ISSUE THREAD

**Issue by asa133** [Kenshin/simpread#2665]
这个网站把正文做进了代码格式，希望能够变成普通格式，现在导出受限。基本都是文本+图片，本身不涉及代码块
网址：https://www.pmcaff.com/
感谢！

**Comment by binsee** [comment]
你指的是此站点的「咖啡日报」栏目下的文章吧？

示例文章： 
- [用户访谈获取的定性数据如何分析？](https://coffee.pmcaff.com/article/1akbJ8mkzl?rts=210814054351_1001_4_0)
- [万字长文：被阿里收购有多好？凉了有多少？](https://coffee.pmcaff.com/article/x1Q9q2bJQP?newwindow=1&rts=210814054400_13_6_0)

导入第三方适配源：
https://gist.githubusercontent.com/binsee/55acad05b921ba79ac6695a9463f563c/raw/coffee.pmcaff.com.json

刷新文章页即可

**Comment by Kenshin** [comment]
嗨，各位。

我已经将此站增加到了官方适配源里面。

@asa133 

请通过下图方式更新

![image](https://user-images.githubusercontent.com/81074/130347875-4ad69ba7-9cce-4746-8169-f6ab591a014d.png)
