### ISSUE TITLE
如何把离线网页变成笔记软件可以引用的外链？

### ISSUE THREAD

**Issue by Karekin** [Kenshin/simpread#2666]
![image](https://user-images.githubusercontent.com/47046461/129354367-9507404e-ce10-44fd-86b1-97f2189a2ec1.png)
<br>
我知道在“稍后读”里打开本地文件可以获取离线网页的外链，类似`http://localhost:7026/reading/342?title=xxx`

但我设置的是“全文（含标注）+标注”，一共两个文件，而通过上述方法只能获取“全文”的外链，当我想在笔记软件里链接“标注”时，该怎么办呢？

**Comment by Kenshin** [comment]
嗨，按照你说的思路，当选择了 **全文（含标注）+标注** 后：

- `http://localhost:7026/reading/342?title=xxx` → 全文（含标注）
- `http://localhost:7026/reading/342?title=xxx@annote` → 仅标注

你可以看下 `output` 文件夹是否存在 `xxxx@annote`。

注意：自定义标题需要按照 `{{id}}{{un_title}}{{mode}}` 下图所示设置

![image](https://user-images.githubusercontent.com/81074/129359173-94edf598-f1a7-450d-b973-f3ff429a7522.png)

**Comment by jueshikuangshen** [comment]
output文件夹里存在“标注”文件，但按照您刚刚说第二个地址打开还是原文，好像这个地址只识别了id(342)，没有识别后面的文件名

![image](https://user-images.githubusercontent.com/47046461/129360270-f82b2a1a-bac8-4715-9385-490991cf68fc.png)

**Comment by Kenshin** [comment]
嗨，抱歉。

正确的 URL 是 `http://localhost:7026/reading/xxx@annote `

不过，这里确实需要优化下，应该等同于 `http://localhost:7026/reading/342?title=xxx@annote` 才符合直觉。

我先记录下，但只能通过升级同步助手修复此问题。

**Comment by jueshikuangshen** [comment]
大佬，为啥打开`http://localhost:7026/reading/342@annote`显示下面的东西
![image](https://user-images.githubusercontent.com/47046461/129361411-d424a931-b9c2-4316-bfe6-76a910ea06b8.png)
<br>
确实有这个标注文件啊
![image](https://user-images.githubusercontent.com/47046461/129361470-4d4c030f-8dc9-4ede-ba57-23a1a9127b1a.png)
<br>
去掉@annote可以打开原文
![image](https://user-images.githubusercontent.com/47046461/129361532-e3d7e027-5b96-40fa-931d-cd6f296ac61c.png)

**Comment by Kenshin** [comment]
`http://localhost:7026/reading/xxx@annote` → `xxx` 是 `title `不是 `id`

**Comment by jueshikuangshen** [comment]
麻烦大佬了，我这里还是打不开，您看看这个地址还有啥问题呀
<br>
![image](https://user-images.githubusercontent.com/47046461/129364513-d83e06d4-b212-4b75-b346-a642559af781.png)

**Comment by Kenshin** [comment]
这是因为你的标题含有特殊的字符导致的，你可以在稍后读中修改标题，比如：
我是标题
然后再导出 离线 HTML ，再试试。

**Comment by jueshikuangshen** [comment]
![image](https://user-images.githubusercontent.com/47046461/129369545-a9f8ce61-aa9d-4366-af8b-4fffac6df805.png)

**Comment by Kenshin** [comment]
奇怪…
这个文件存在于 output 文件夹吧？

还有，你的同步助手是什么时候下载的？如果是近期就没问题（如一个月内）

**Comment by jueshikuangshen** [comment]
文件在ouput文件夹里，原文都可以打开，就是标注打不开；

同步助手是7月30日下载的。

要是可以这么操作就太方便了 😭

**Comment by Kenshin** [comment]
我的是可以的，正常也应该可以的。

把 URL 告诉我下，明天我看下。

或者你把配置文件，这个稍后读的两个 html 也都一起给我，这样更方便。

**Comment by jueshikuangshen** [comment]
好的，发到您邮箱里吗？

**Comment by Kenshin** [comment]
是的， Github 能找到我的邮箱。

**Comment by jueshikuangshen** [comment]
发过去了，请查收，麻烦大佬了！

**Comment by Kenshin** [comment]
没问题，明天给你回复。

**Comment by Kenshin** [comment]
嗨，我没有收到你的邮件（ 抱歉垃圾箱里面也没有，请确认是否发送？

**Comment by Kenshin** [comment]
嗨，抱歉，我之前又说错了...

正确的方式是，正确的方式是标题的全名，如 `342-title@annote`

![image](https://user-images.githubusercontent.com/81074/129431671-26bb87b8-d2b5-4145-84ae-1cf5281816c3.png)

![image](https://user-images.githubusercontent.com/81074/129431679-d0a65bbc-e5ea-44db-9f9c-49823500d2d3.png)

**Comment by jueshikuangshen** [comment]
成功了，谢谢大佬！

**Comment by Kenshin** [comment]
> 成功了，谢谢大佬！

哈哈，其实很简单的，我昨天「傻」了，才折腾了好几次... 下个版本有更简单的方式。

***

好奇问问，你是用双链笔记吗？说说使用场景？

**Comment by jueshikuangshen** [comment]
对，我还在上学，双链笔记里的内容是凝练的知识点，方便快速回顾；有的知识需要补充一些“最新进展”、“热点新闻”等背景信息，我可以链接到简悦的对应合辑里，不断的跟踪完善。

大佬下次更新大概在什么时候，有什么特性？越用越发现简悦功能的强大！非常期待！

**Comment by Kenshin** [comment]
哈哈，不错~

https://github.com/Kenshin/simpread/discussions/2085 里面有很多使用场景，你可以参考下。

***

另外，能否稍微详细说下你的使用场景，我会记录到上面这个链接里面。

还要，如果没有帮忙在 [Webstrore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 评分的话，方便的话，也请帮忙五星好评 + 评论。

***

我目前在休假，下周回去，就可以开始同步助手的更新了。

**Comment by jueshikuangshen** [comment]
报告大佬，之前已经”五星好评 + 评论“了，目前这个使用场景还是设想，等我尝试应用一段时间再记录到链接里。

**Comment by Kenshin** [comment]
哈哈，没事，随时欢迎你深度折腾简悦。 🙂

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [稍后读 · 读取外部文件](https://github.com/Kenshin/simpread/discussions/4625)。

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
