### ISSUE TITLE
稍后读突然打不开了

### ISSUE THREAD

**Issue by Geheil** [Kenshin/simpread#2669]
1.问题

在当前配置文件下，稍后读的界面打不开。同时简悦的阅读模式无法开启或者关闭标注了。

在初始配置文件下，稍后读的界面能打开。

2.情况简介

账户是高级账户。系统是BigSur。浏览器是Chrome。

可能是由于加入了太多的网页到稍后读，一开始是十分卡顿，后面突然崩溃后就无法重新载入了。

会不会是配置文件出了问题呢？

还请开发者指教。一定要能保留住我的笔记!

![image](https://user-images.githubusercontent.com/62799822/129450551-9b303740-55a6-46e3-9c43-99fed5f4f8d6.png)

**Comment by Geheil** [comment]
自己看了下，貌似跟issue#1972很像啊

**Comment by Kenshin** [comment]
嗨，不用着急，只要配置文件还在，就肯定没问题。

当你看到这个 Issues 时**请务必先导出配置文件到本地**

然后，你可以自行排查下：

> 是否使用了同步助手？以及坚果云？如果使用了坚果云可以通过坚果云的历史记录查看任意时间点的记录，试着还原到某个时间，看看能否打开。

如果还是无法解决的话，可以把配置文件通过邮件的方式给我（邮件在 Github 上可以找到），我来帮你解决。

**Comment by Geheil** [comment]
> 嗨，不用着急，只要配置文件还在，就肯定没问题。
> 
> 
> 
> 当你看到这个 Issues 时**请务必先导出配置文件到本地**
> 
> 
> 
> 然后，你可以自行排查下：
> 
> 
> 
> > 是否使用了同步助手？以及坚果云？如果使用了坚果云可以通过坚果云的历史记录查看任意时间点的记录，试着还原到某个时间，看看能否打开。
> 
> 
> 
> 如果还是无法解决的话，可以把配置文件通过邮件的方式给我（邮件在 Github 上可以找到），我来帮你解决。

邮件已经发给你了，谢谢

**Comment by Kenshin** [comment]
收到，搞定后会通知你。

**Comment by Kenshin** [comment]
嗨，应该搞定了，我在邮件中回复你了~

**Comment by Geheil** [comment]
> 嗨，应该搞定了，我在邮件中回复你了~

没收到你发给我的邮件啊

**Comment by Kenshin** [comment]
看看垃圾箱

**Comment by Geheil** [comment]
> 看看垃圾箱

垃圾箱里只有GitHub的对话，没看到配置文件

**Comment by Kenshin** [comment]
我发到了 hello_****c@163.com 这个邮箱

**Comment by Geheil** [comment]
> 我发到了 hello_****c@163.com 这个邮箱

邮箱是对的，但我还是没有收到，翻箱倒柜地找了一遍。要不你发我QQ邮箱504071269@qq.com

**Comment by Kenshin** [comment]
发过去了。

**Comment by Kenshin** [comment]
收到了吗？

**Comment by Geheil** [comment]
> 收到了吗？

邮件已经收到，非常感谢。只是电脑不在身边，估计要晚上回去试试哈。🙏

**Comment by Kenshin** [comment]
没事的，如果配置文件没有问题的话，别忘记关闭这个 Issues （我就知道了~）

PS：如果没有帮忙在 [Webstrore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评的话，请帮忙评分。 😁

**Comment by Geheil** [comment]
> 没事的，如果配置文件没有问题的话，别忘记关闭这个 Issues （我就知道了~）
> 
> 
> 
> PS：如果没有帮忙在 [Webstrore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评的话，请帮忙评分。 😁

成功进入稍后读了，感谢

**Comment by Kenshin** [comment]
哈哈，搞定就好。163 竟然还吃邮件...
