### ISSUE TITLE
希望可以增加对支持的页面，自动进入聚焦/阅读模式

### ISSUE THREAD

**Issue by oknixus** [Kenshin/simpread#267]
如题
谢谢

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/38066332-1e25b172-333a-11e8-8abf-92070437e352.png)

建议看下 WiKi，虽然写的有些不好找，但还是能找到你的答案的。 😃

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
