### ISSUE TITLE
稍后读能不能默认进入阅读模式而不是标注模式

### ISSUE THREAD

**Issue by demacialux** [Kenshin/simpread#2671]
在 设置-稍后读 没有找到可以切换默认进入阅读模式的选项

**Comment by Kenshin** [comment]
嗨，请看这里

![image](https://user-images.githubusercontent.com/81074/129466350-7dd27935-031a-4f50-8ed0-4742fbc4a032.png)

**Comment by in-out** [comment]
必须使用 同步助手吗？
有可能在chrome插件中 实现吗？

**Comment by Kenshin** [comment]
当然不是了。
但是有些动态加载的页面只能通过同步助手来解析。

**Comment by in-out** [comment]
> 当然不是了。
> 但是有些动态加载的页面只能通过同步助手来解析。

在插件的设置里 并没有找到
"稍后读默认进入阅读模式而不是标注模式"的设置
请问chrome如何设置？

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/130038050-72aa663a-e9d5-4ca9-ae33-02c987dd1dac.png)

![image](https://user-images.githubusercontent.com/81074/130038099-ae060a0b-5e0e-488e-a3b7-01175554d9a7.png)

上面的描述在 http://ksria.com/simpread/docs/#/稍后读 里面已经描述的很清楚了。

![image](https://user-images.githubusercontent.com/81074/130038243-6559e4ef-3bba-41d6-92b8-428f96a2a215.png)

**Comment by in-out** [comment]
> ![image](https://user-images.githubusercontent.com/81074/130038050-72aa663a-e9d5-4ca9-ae33-02c987dd1dac.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/130038099-ae060a0b-5e0e-488e-a3b7-01175554d9a7.png)
> 
> 上面的描述在 [http://ksria.com/simpread/docs/#/稍后读](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB) 里面已经描述的很清楚了。
> 
> ![image](https://user-images.githubusercontent.com/81074/130038243-6559e4ef-3bba-41d6-92b8-428f96a2a215.png)

多谢 是我没找到
