### ISSUE TITLE
阅读模式的高级控制面板中关闭插件“为阅读模式增加字数统计”，刷新页面后进入阅读模式一篇空白，清楚页面缓存仍是空白

### ISSUE THREAD

**Issue by melodyjerry** [Kenshin/simpread#2676]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Edge  93.0.961.18 (官方内部版本) beta (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://www.cnblogs.com/chengxiao/p/6059914.html

**请描述你的问题**

插件链接：https://simpread.ksria.cn/plugins/details/kw36BtjGu0
阅读链接：https://www.cnblogs.com/chengxiao/p/6059914.html
仍在启用的其他插件：
![image](https://user-images.githubusercontent.com/47730856/129472975-6ab34820-a0e3-486f-b399-19b33e09a72e.png)

**截图**
![image](https://user-images.githubusercontent.com/47730856/129473061-0e6ae3a3-5525-4c88-bbfc-43f75a885196.png)

**Comment by melodyjerry** [comment]
![image](https://user-images.githubusercontent.com/47730856/129473192-a21fb0c6-5ea6-4534-801f-a0ac756bfd77.png)
明显是有内容，但是被什么东西顶层覆盖了。
试了其他网页的阅读模式正常，怎么排查我的问题？

**Comment by Kenshin** [comment]
你看看控制台是否有报错？
我在外面，回去后试试。

**Comment by melodyjerry** [comment]
@Kenshin 打开开发者工具，元素、控制台全是空白，原网页空白，进入阅读模式也是空白

**Comment by melodyjerry** [comment]
![image](https://user-images.githubusercontent.com/47730856/129476766-1ebeb9e2-f61b-4be6-9e51-6b17b69c8258.png)

**Comment by melodyjerry** [comment]
![image](https://user-images.githubusercontent.com/47730856/129476858-27003956-fa85-4815-8faf-5efa2ab635d1.png)

**Comment by melodyjerry** [comment]
同样是博客园的文章是没有问题，唯独上面那个链接打开全是空白

**Comment by melodyjerry** [comment]
我在稍后读中把这个文章的所有批注删除了，现在可以正常访问了，不知道是批注中什么问题，我只是用了批注中加了文字备注，外部链接那些都没用到，希望作者排查一下，谢谢

**Comment by Kenshin** [comment]
> 我在稍后读中把这个文章的所有批注删除了，现在可以正常访问了，不知道是批注中什么问题，我只是用了批注中加了文字备注，外部链接那些都没用到，希望作者排查一下，谢谢

备注是没问题的，问题肯定出在标注上面，你能记得你对哪些内容做了标注吗？

**Comment by melodyjerry** [comment]
我对四五个文字片段做了标注，没对图片做标注。
我刚才又对那几个内容做了标注，暂时没发现那个异常，好奇怪。

**Comment by Kenshin** [comment]
> 我对四五个文字片段做了标注，没对图片做标注。
> 我刚才又对那几个内容做了标注，暂时没发现那个异常，好奇怪。

因标注后导致浏览器卡死的情况确认出现过，虽然只是个例。
那这个问题先这样，我先关闭这个 Issues 有再次发生后随时重开它。
