### ISSUE TITLE
【界面UI】乱码

### ISSUE THREAD

**Issue by vuuihc** [Kenshin/simpread#2677]
<img width="1150" alt="企业微信20210815-171807@2x" src="https://user-images.githubusercontent.com/3747378/129473627-03da743a-a0dd-4d9b-a07e-785cb618a72c.png">

反馈的“我有GitHub issues账号” 点击也没有反应

**Comment by Kenshin** [comment]
嗨，重启浏览器。

**Comment by Kenshin** [comment]
我先关闭这个 Issues 课，有需要请重开
