### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by Flysky0** [Kenshin/simpread#2678]
发生问题的地址: <https://www.shanbay.com/news/articles/jgicx>

**Comment by Kenshin** [comment]
嗨，扇贝阅读确实有些问题，为什么关闭这个 Issues 了？

**Comment by Kenshin** [comment]
嗨，此站已经适配，请更新适配列表

![image](https://user-images.githubusercontent.com/81074/130352745-f125619f-2226-4e31-8b7e-cd41b11c347c.png)

### 进阶使用

另外，也可以使用 [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 获得更好的使用方案，如下图：

![iShot2021-08-22 18 57 05](https://user-images.githubusercontent.com/81074/130352775-4ade5777-09bd-453c-bd54-96f80ade844f.png)

### 备注

使用翻译后的结果（双语）支持导出 HTML / Markdown 等格式。

**Comment by Flysky0** [comment]
后来通过搜索，看到了其他人已经提出了相关问题，所以关闭了此问题

**Comment by Flysky0** [comment]
> 嗨，此站已经适配，请更新适配列表
> 
> ![image](https://user-images.githubusercontent.com/81074/130352745-f125619f-2226-4e31-8b7e-cd41b11c347c.png)
> 
> ### 进阶使用
> 另外，也可以使用 [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 获得更好的使用方案，如下图：
> 
> ![iShot2021-08-22 18 57 05](https://user-images.githubusercontent.com/81074/130352775-4ade5777-09bd-453c-bd54-96f80ade844f.png)
> 
> ### 备注
> 使用翻译后的结果（双语）支持导出 HTML / Markdown 等格式。

不过图上还存在段尾词汇被截断的问题，希望得到能够修复，我设立了一个新issue #2780
