### ISSUE TITLE
定制化markdown模板的一些疑问

### ISSUE THREAD

**Issue by dflzy** [Kenshin/simpread#2679]
定制化markdown模板，logseq的全文模板，所有内容在一个block中，不能自动分行。

**Comment by Kenshin** [comment]
嗨，为了方便排查，把你的模板给我看下。

**Comment by dflzy** [comment]
①是我的设置如下
![image](https://user-images.githubusercontent.com/76244295/129497373-e26dc165-2896-41d6-81da-1fc102e20cab.png)

②是导出的markdown模板是在简悦的帮助文档中复制过来的【适合 Logseq 的模板（全文）】，地址是https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-1112010
内容如下
#[[excerpt]] [{{title}}]({{url}}) 
- 标签: #[[SimpRead]] {{tags}}
- 阅读时间: [[{{date_format|now|MM,dd,yyyy}} ]]
- 描述: {{desc}}
- 标注:
{{#each}}
^^{{an_html}}^^
{{an_tags}}
#+BEGIN_EXAMPLE
{{an_note}}
#+END_EXAMPLE
{{/each}}

③是导出之后的md文件，放到logseq的文件夹中打开后，所有的内容都在同一个block中，具体效果截图如下：
![image](https://user-images.githubusercontent.com/76244295/129497489-e18cbd32-af58-4cf8-b456-e0bddc6dc900.png)

**Comment by Kenshin** [comment]
收到，我目前在休假，也没有使用 logseq 不过我已经告诉其他使用 logseq 的用户帮忙看下。
有消息后会通知你~

另外，你可以试试着小段的标注，看看是否也存在这个问题？

**Comment by dflzy** [comment]
**全部标注一次性导出，也是所有内容在同一个block内。如下：**

**①是简悦中设置为导出标注**
![image](https://user-images.githubusercontent.com/76244295/129526450-3eadcaa2-3054-41be-a81f-e097b7f63bc6.png)

**②是简悦导出md文档，然后放到logseq的文件夹中，用logseq打开后如下图**
![image](https://user-images.githubusercontent.com/76244295/129526302-4b9e6cc0-8aee-49fb-a042-d6cc177d28e3.png)

**Comment by lyserenity** [comment]
我之前对 logseq 有过测试，由于 logseq 还在不断地迭代，有的更新我不一定有完全追踪到，所以只能先就之前测试的结果（以及记忆）说明一下。

logseq 的 block 是以 heading 为单位，所以如果选择的是 `markdown` 语法，只有以 `#` 开头的会被辨认成 block（换言之，凡是不是以 `#` 开头的，都在 block 里....），所以你如果想要分开，就必须：
```
#[[excerpt]] [{{title}}]({{url}}) 
- 标签: #[[SimpRead]] {{tags}}
- 阅读时间: [[{{date_format|now|MM,dd,yyyy}} ]]
- 描述: {{desc}}

{{#each}}
## 标注

^^{{an_html}}^^
{{an_tags}}

## note

#+BEGIN_EXAMPLE
{{an_note}}
#+END_EXAMPLE
{{/each}}
```
p.s. 我印象中当初测试的时候，该有的换行不能少，所以我 `## 标注` 和 `## note` 下面有多加一行，你可以自己测试看看。因为我用的是 org mdoe ，如果要改成 markdown 测试的话会比较麻烦，要是还有其他问题，我再来重测....

**Comment by Kenshin** [comment]
@lyserenity 

🙏 👍

**Comment by Kenshin** [comment]
嗨，Markdown 模板定制化 2.0 发布了，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3725)。

特点
---

- 可完美的支持 Obsidian · Logseq 等任意双链笔记的语法规则，细节请看 [模板库](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)

- 内置 [EJS 引擎](https://ejs.co/#docs) ，所以可以使用 EJS 引擎全部的功能。

- 可在模板中直接编写 Javascript 代码。

- 所见即所得，相比 1.0 在模板中去掉空格或无法空格等问题，2.0 无此问题。

- 兼容 1.0 的 [语法规则](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=markdown)（占位符）。

- 兼容 1.0 [模板](https://github.com/Kenshin/simpread/discussions/2153)。

如何使用
---

> **2.0 仅提供模板解析方案，并未提供导出方案**，所以需要跟插件配合使用，**接下来还会陆续增加更多插件**。

下面的插件均可配合 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件实现自动化方案。

- [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

- [导出 org-mode 文件](https://github.com/Kenshin/simpread/discussions/3775)

安装后需要开启下图所示的选项才可使用

![image](https://user-images.githubusercontent.com/81074/165034089-a8e2987e-7947-4bdc-89e4-5d743fff1f47.png)

模板库
---

- [Obsdian 模板之一](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311)

- [Obsdian 模板之二](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627313)

- [Logseg · Markdown 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627315)

- [Logseg · org-mode 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627320)

更多模板，[请看这里](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)。

模板截图
---

![](https://imgs.zhubai.love/230c79c30d8c47f88c6cd659e2916b1a.png)

![](https://imgs.zhubai.love/831d361aa3bf4c9e90f3fca0cbb681bc.png)
