### ISSUE TITLE
express返回 413 Payload Too Large

### ISSUE THREAD

**Issue by alanchenup** [Kenshin/simpread#268]
@Kenshin 是否是simpread 后端服务设置了限制呢?

**Comment by Kenshin** [comment]
是的。   😂

**Comment by alanchenup** [comment]
可以稍微调到50M吗,嘿嘿

2018-03-29 15:28 GMT+08:00 Kenshin Wang <notifications@github.com>:

**Comment by alanchenup** [comment]
给你加了个🍗,非常感谢这么好的工具

2018-03-29 15:53 GMT+08:00 Alan Chen <alanchenup@gmail.com>:

**Comment by Kenshin** [comment]
鸡腿不错 👏
免费的服务器… 以后会考虑自建服务器的。 😊

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，重构了 【导出到 印象笔记】的代码，基本上解决了导出总是失败的问题。

同时增加了当导出失败时，以 **Markdown 格式 二次保存** 及 提交到 **待决站点机制** ，确保万无一失。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
