### ISSUE TITLE
建议适配：有知有行

### ISSUE THREAD

**Issue by Kenwind** [Kenshin/simpread#2680]
有知有行：https://youzhiyouxing.cn/materials

这是一个专注于投资者教育的产品，网站上有很多高质量文章。使用「简悦」无法正常进入阅读模式，官方提供的解决方案都试过了，均无法解决。

建议适配，感谢开发者。

**Comment by Kenshin** [comment]
嗨，没问题。
我近期在休假，搞定后会在这里通知你。

**Comment by binsee** [comment]
这个站点的样式有点特殊，需要额外做些处理。
![image](https://user-images.githubusercontent.com/5285894/129636450-fc562c4e-1de8-417b-a2e0-d7b93ef92a36.png)
![image](https://user-images.githubusercontent.com/5285894/129636341-acb2b8ff-a27c-41c4-a92c-110aeba69c1d.png)

部分站点存在body上特意通过class设置了display样式，导致阅读模式屏蔽body时失效，是否有什么方式可以检测到？

**Comment by Kenshin** [comment]
@binsee 

可以用 

```
( () => {
    return html
})()
```

的方式写，把 `tw-flex` 直接从 `body` 删除掉。

**Comment by Kenwind** [comment]
@Kenshin 感谢，休假愉快 :D

**Comment by binsee** [comment]
> @binsee 
> 
> 可以用 
> 
> ```
> ( () => {
>     return html
> })()
> ```
> 
> 的方式写，把 `tw-flex` 直接从 `body` 删除掉。

我没理解你的意思。
这个页面我是找不到`tw-flex`的样式从哪来的，单独做这个站点适配移除此class倒是没问题，但如果有方法可以检测到这种样式来源class就可以出个插件来统一解决这种情况。

**Comment by Kenshin** [comment]
嗨，此站已经适配，请根据下图更新适配规则即可。

![image](https://user-images.githubusercontent.com/81074/130348400-09b84b89-dc36-4339-82c5-760737349260.png)

不过，音频这块没有适配

![image](https://user-images.githubusercontent.com/81074/130348414-855bad51-4eed-4e58-9a0f-0a90d3637169.png)

***

@binsee 

抱歉，我之前理解错了，其实这个问题很容易解决，看下图

![image](https://user-images.githubusercontent.com/81074/130348450-42018fe8-99c1-4434-979d-75d113e48510.png)
