### ISSUE TITLE
手动框选的范围好像无法保存到稍后读？保存后的结果还是原有的网页(有些网页无法识别正文)

### ISSUE THREAD

**Issue by xeuyuuyuex** [Kenshin/simpread#2681]

**Comment by Kenshin** [comment]
可以的，前提是需要设置 https://github.com/Kenshin/simpread/discussions/2146

**Comment by xeuyuuyuex** [comment]
a

**Comment by xeuyuuyuex** [comment]
就是类似这个网页： [https://www.aisixiang.com/data/116260.html](url)
全文后自己选择文本的结果不能存到稍后读，
保存的结果仍然是全文前的

**Comment by Kenshin** [comment]
可以的，请看 https://github.com/Kenshin/simpread/issues/2681#issuecomment-899291336 的说明。

**Comment by xeuyuuyuex** [comment]
已经照着 #2146 配置完成，也显示是本地了……
![image](https://user-images.githubusercontent.com/62622752/129564290-35657fce-eacb-47af-a4d4-2d8ef5a089f0.png)
可是显示的仍然不是框选的文本

**Comment by Kenshin** [comment]
找到你在 `output` 里面的 HTML，打开后，是不是框选的内容？

**Comment by xeuyuuyuex** [comment]
噢噢！可以了
![image](https://user-images.githubusercontent.com/62622752/129566621-96fce29e-a4a8-4fe7-a4c8-96ea6caf8cb1.png)
这个功能自己关闭了

**Comment by Kenshin** [comment]
哈哈，没事的，搞定就好~  👍 我关闭这个 Issues 了~

PS：如果没有帮忙在 [Webstore ](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)五星好评的话，请帮忙评分。🙏
