### ISSUE TITLE
插件：代码段增强   运行出错

### ISSUE THREAD

**Issue by Liergou532** [Kenshin/simpread#2682]
# 2137代码高亮出错 
# 出错网页截图：
![image](https://user-images.githubusercontent.com/78479914/129540938-71496469-7494-4c9e-8b60-8c4441445595.png)
# 出错网页链接：
https://www.huaweicloud.com/articles/41ab50f62469c83926208761581036d2.html

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
