### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by chenqinggang001** [Kenshin/simpread#2683]
发生问题的地址: <https://scms-prod-sh-private.oss-cn-shanghai.aliyuncs.com/course_picture/edu-60502f4c09120.pdf?Expires=1629125823

**Comment by Kenshin** [comment]
抱歉，我无法打开这个 URL，看起来似乎是 PDF ？

如果是的话，简悦不支持 PDF 生成阅读模式。
