### ISSUE TITLE
绑定语雀账号，反复授权

### ISSUE THREAD

**Issue by Yuyang-Hou** [Kenshin/simpread#2687]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，不会有这个问题的，因为你给出的信息太少，我没发判断，等补全必要信息后我再重开这个 Issues 。

**Comment by cpp-jiang** [comment]
我也是点了授权, 显示成功
![image](https://user-images.githubusercontent.com/25993096/147321621-bb817196-5a66-40d3-bf13-6c9a8ebf68ce.png)
dna; 但刷新后导出依然要授权, 
![image](https://user-images.githubusercontent.com/25993096/147321662-2fce3cca-13ae-48d2-b2cf-97ef13b91d78.png)
; 语雀个人页面也没有授权记录
![image](https://user-images.githubusercontent.com/25993096/147321719-1f50e4c4-cfa9-4c26-99ae-c203a48d9f28.png)

**Comment by cpp-jiang** [comment]
> 嗨，不会有这个问题的，因为你给出的信息太少，我没发判断，等补全必要信息后我再重开这个 Issues 。
emmm

**Comment by Kenshin** [comment]
@cpp-jiang 

你可以这样试试

> 在选项页授权，授权成功后，重启浏览器，然后看看选项页 → 服务里面的授权信息是否为勾选状态。

然后再测试导出到语雀。

**Comment by Kenshin** [comment]
@cpp-jiang

哈哈，又有一阵子没看到你了，今天平安夜，提前祝个🎅 🎄 😄
