### ISSUE TITLE
代码里的备注也被高亮了

### ISSUE THREAD

**Issue by LoneFireBlossom** [Kenshin/simpread#2688]
设备：Mac Intel 10.15.7 
浏览器：Chrome目前最新版 92.0.4515.159（正式版本） (x86_64)
简悦版本：2.2.0
问题：我在 https://www.w3schools.com/java/java_conditions.asp 这个页面进入阅读模式，可以看到备注里的关键字也被高亮了，这是不应该的吧？
![image](https://user-images.githubusercontent.com/50087596/129848105-aca03beb-9348-425e-aa18-aeb8bcd2086c.png)

**Comment by Kenshin** [comment]
嗨，这是代码高亮插件造成的，简悦暂时没有人工控制，或者说如果要做到「个性化」是非常麻烦的事情。

况且代码高亮插件的问题还有很多。 😂 

所以，我先关闭这个 Issues 了，如果你觉得有必要可以随时重开它。
