### ISSUE TITLE
站点未适配-掘金小册

### ISSUE THREAD

**Issue by rpishgithub** [Kenshin/simpread#2690]
## 问题描述
**问题:** 站点未适配,每次都需要手动选取正文.
**站点:** 掘金小册
**链接:** https://juejin.cn/book/6857911863016390663/section/6859983339320213511

希望可以尽快对站点进行适配.
也期待后期推出新功能,可以基于手动选取内容对指定域名路径下文章进行自动解析.

**Comment by Kenshin** [comment]
谢谢反馈，会适配掘金的，适配后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，掘金小册的插件和适配规则已经完成，如何使用请看这里  https://github.com/Kenshin/simpread/issues/2697
