### ISSUE TITLE
点击SimpleRead概率性打开官网的问题？

### ISSUE THREAD

**Issue by lupguo** [Kenshin/simpread#2693]
如题，为什么购买了高级账号后，依旧在菜单栏点击Simple Read仍然会概率性打开官网？

**Comment by Kenshin** [comment]
嗨，我没有理解你说的意思，请截图说明。

另外，如果你说的是下图所示，当然会打开官网了

![image](https://user-images.githubusercontent.com/81074/130058200-c6a5b844-1498-4ef8-a0e5-d345a2389bda.png)
