### ISSUE TITLE
Dropbox同步的配置文件无法在新浏览器上解锁

### ISSUE THREAD

**Issue by lfwfd** [Kenshin/simpread#2696]
原来在edge上解锁了高级账户并使用Dropbox同步配置文件，一段时间没有用简悦，重装系统后想要重新启用，绑定Dropbox并恢复配置，无法解锁，下载配置文件到本地导入也无效。现在是重装系统前忘记取消原有的授权，uid知道但是这种情况不知道如何解锁

**Comment by Kenshin** [comment]
嗨，如果确认 UID 是正确的话，可以看 https://github.com/Kenshin/simpread/discussions/1958 提供的方案。

**Comment by lfwfd** [comment]
UID复制过程没注意格式和正确才无法解锁，已经解决

**Comment by Kenshin** [comment]
哈哈，搞定就就好！
