### ISSUE TITLE
希望可以设置隐藏dock栏的选项

### ISSUE THREAD

**Issue by Yuyang-Hou** [Kenshin/simpread#2699]
### 希望可以设置隐藏dock栏的选项。
![Xnip2021-08-21_18-07-23](https://user-images.githubusercontent.com/62137410/130318451-58788989-c637-4e64-a3a9-f16ed6aae9f0.jpg)
macos中dock栏会保留开启的应用，但是同步助手并不会频繁点击，参考很多macos中很多工具类软件，都可以只保留菜单栏图标。如下图，希望可以考虑此功能
![image](https://user-images.githubusercontent.com/62137410/130318515-f83d0281-61ee-44a4-95cf-b190f33de190.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，下个版本就会提供此选项。

**Comment by ygcaicn** [comment]
2022

**Comment by Kenshin** [comment]
@ygcaicn 

即将发布（当然不止此选项）

![image](https://user-images.githubusercontent.com/81074/168532258-642ab40f-9cdf-41a9-9ff4-4831686a4338.png)

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 隐藏 Dock 功能来了

![image](https://user-images.githubusercontent.com/81074/172758651-02fb7c7e-41a0-4a2b-ae14-1b8c53f000ed.png)

同时也可自适应 Menubar Icon（仅限 Mac 用户）

![image](https://user-images.githubusercontent.com/81074/172758764-e4dbabd8-f377-47a6-bbd0-8414a991a36c.png)

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
