### ISSUE TITLE
[建议]对小说站点提供阅读模式的支持

### ISSUE THREAD

**Issue by alexinea** [Kenshin/simpread#27]
[建议]对小说站点（如笔趣阁等）提供阅读模式的支持

小说站点的特点是多广告、需要频繁上下一章的切换，所以特别适合本工具使用。

可以借鉴傲游浏览器的阅读模式：
+ 自动（并预先地）加载后续若干章节；
+ 用户在某章节（第B章）退出阅读模式后，原页面（第A章）在退出时跳转到对应章节的页面（第B章的页面）。

**Comment by Kenshin** [comment]
没问题，只是不太清楚有哪些常见的小说类网站，能否提供几个？

我会把你说的新需求放到 `TO-DO` 里面，但是由于时间和精力有限，所以暂时在上线 `1.1.0` 版本之前不会考虑。

**Comment by alexinea** [comment]
+ http://www.qu.la/
+ http://www.biquge.com.tw/
+ http://www.xxbiquge.com/
+ http://www.biquge5200.com/
+ http://www.piaotian.com/

列举了几个。由于笔趣阁每日流水巨大，所以很多站点都模仿了他（甚至是使用了同一套系统）。

**Comment by Kenshin** [comment]
okay :smirk:
有时间我先把它们加到 适配列表，你说的功能需要等 `1.0.1` 之后实现了~

**Comment by alexinea** [comment]
辛苦上神啦 y( ˙ᴗ. )耶~

**Comment by Kenshin** [comment]
不好意思，上周比较忙，刚刚把这几个站加到了适配列表，请使用 [这个方式](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%85%B3%E4%BA%8E%E6%9B%B4%E6%96%B0) 更新。

如无问题，我关闭这个 issues 了。 😄
