### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by 973339348** [Kenshin/simpread#2701]
我看B站以及知乎里介绍的视频和文章，最后发现坚持使用下去好难。我相信有这样体验的不止我一个，因为我自己有摆弄过wox 以及quicker 所以相对其他人来说弄新软件可能不属于小白的类型，可是弄到简悦我都要跪了

**Comment by Kenshin** [comment]
嗨

首先 B 站根本就没有简悦的官方视频操作，有的话也只是简悦爱好者的一些视频。
其次，简悦在知乎上的唯一官方渠道是 https://www.zhihu.com/column/kenshin 如果你是通过其它知乎途径获取的，跟上条一样，都是简悦的爱好者整理的。

至于如何使用的问题，建议看 https://zhuanlan.zhihu.com/p/382683271 如果真的看进去了，应该足够了。有任何使用上的问题，在这里直接问我就好。
