### ISSUE TITLE
无法绑定印象笔记账号

### ISSUE THREAD

**Issue by HaoliangLi** [Kenshin/simpread#2702]
![image](https://user-images.githubusercontent.com/33981078/130349460-c32253d5-14cc-4bbd-b5ee-5daef1b7e454.png)

无法绑定印象笔记账号，一直停留在上述界面。

- 操作系统 **macOS 11.5.2 (20G95)**

- 浏览器版本 **e.g. Chrome 92.0.4515.131 (Official Build) (x86_64)**

- 简悦版本 **2.2.0**

thanks
***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
嗨，有可能需要保存网络畅通（我从未遇到过这个问题的）
