### ISSUE TITLE
导出html或离线html都没有大纲目录

### ISSUE THREAD

**Issue by pikawindy** [Kenshin/simpread#2706]
请问一下，我设置开启了大纲目录功能，在浏览器也能看到大纲，但导出html和离线html都没大纲，只有一条竖线，这是怎么回事呢？还有请问html和离线html有什么区别，这两个容量大小差好多，我飞行模式打开html也能看到里面的图片啊
![比特截图2021-08-23-20-35-21](https://user-images.githubusercontent.com/63467634/130448587-ef794b76-8dd4-4d3f-9b25-64108e22b709.png)

**Comment by Kenshin** [comment]
嗨，看下图的设置

![image](https://user-images.githubusercontent.com/81074/130547702-72333821-d657-4d28-b0ce-efceeec873ff.png)
