### ISSUE TITLE
http://www.pmcaff.com页面变动无法适配

### ISSUE THREAD

**Issue by noisay** [Kenshin/simpread#272]
提示页面变动无法使用适配

**Comment by Kenshin** [comment]
感谢反馈，到昨天才更新了一批，只能下次再更新了，到你可以自行更改。😄

**Comment by Kenshin** [comment]
你好，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
