### ISSUE TITLE
清除浏览器缓存后打不开稍后读

### ISSUE THREAD

**Issue by xeuyuuyuex** [Kenshin/simpread#2723]
![image](https://user-images.githubusercontent.com/62622752/131008325-07f4bee5-cd31-4f38-8f4a-74267e140d5b.png)

![image](https://user-images.githubusercontent.com/62622752/131008275-b0f422c4-d48f-4c6e-b15c-90f1e8f49461.png)

清除了第三个选项之后，稍后读一直处于空白的状态，
已经尝试重新安装插件，还是这样……

**Comment by Kenshin** [comment]
嗨

同步助手 1.2.0 发布了，内含 `simpread_config.json` 修复功能，以下是这个功能的细节。

> 已运行 1.2.0 版同步助手，可直接访问此地址 http://localhost:7026/database/fixed
> 
> 根据提示修复即可，关于此功能的详细说明 👉 [请看这里](https://simpread.pro/docs/#/数据中心?id=修复配置文件)。

***

> 以下是同步助手 1.2.0 的其它功能。

## 更新日志

[Notion Site](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#86c339b25b15455b9cc043044891351f)

## 🗄 [数据中心](https://simpread.pro/docs/#/数据中心)

内置了一组针对 `simpread_config.json` 的优化、修复、整理、统计工具。

### 地址

http://localhost:7026/database

### 预览

![image](https://user-images.githubusercontent.com/81074/220891702-b15b7551-205e-480d-aedd-9cf72de7f296.png)

### 模块

- [历史记录](https://simpread.pro/docs/#/数据中心?id=历史记录)

- [修复配置文件](https://simpread.pro/docs/#/数据中心?id=修复配置文件)

- [清理配置文件](https://simpread.pro/docs/#/数据中心?id=清理配置文件)

- [查找重复数据](https://simpread.pro/docs/#/数据中心?id=查找重复数据)

- [数据统计](https://simpread.pro/docs/#/数据中心?id=数据统计)
