### ISSUE TITLE
【疑问&建议】适配是否只是页面的一部分

### ISSUE THREAD

**Issue by Ctipsy** [Kenshin/simpread#273]
比如说，知乎，可能一页里面有很多的回答，有些回答也很长。那么简悦一次是否只加载其中的一部分？
不知我的疑问是否表述清晰😄

> 实际操作发现：

需要用户在非阅读模式下，将页面下拉到剩余部分（未来），再开启简悦，才可以继续适配剩余部分

**Comment by Ctipsy** [comment]
另外
阅读模式下，右边的菜单选项，很容易一不小心鼠标挪开，菜单就收回了。
是否需要考虑增加一个关闭按钮来手动控制菜单的展开和收回？
(当然设置里，可以添加选项        “菜单展开”A:自动  B：手动     )😊

**Comment by Kenshin** [comment]
感谢反馈~

1. 知乎并没有像你所说的这样，简悦会自动加载未显示的部分；在阅读模式下，知乎显示为类似论坛的形式，比如访问 https://www.zhihu.com/question/267975876 即可看到。

2. 控制栏 icon 不太好用的问题，会在下个版本解决掉，诚如你说的方式。  😀

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题

- 新增加的 `重新高亮` 可以解决你的需求；
- 控制栏太过灵活的问题也得到了解决；

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
