### ISSUE TITLE
似乎与插件“smoothscroll”冲突

### ISSUE THREAD

**Issue by lurui45** [Kenshin/simpread#2732]
插件“smoothscroll”是一款让chrome网页获得鼠标滚轮平滑滚动的插件，我在开启了阅读模式后发现鼠标滚轮滚动会变得很卡，是否是与该插件冲突了？
平台：win7
chrome最新版
插件最新版

**Comment by Kenshin** [comment]
嗨，确实有这种情况，如果喜欢平滑滚动的话，可以试试 Edge ，它本身就带有平滑滚动的功能。

关于这个问题，可以看看 https://github.com/Kenshin/simpread/discussions/1685 提到的

**Comment by lurui45** [comment]
> 嗨，确实有这种情况，如果喜欢平滑滚动的话，可以试试 Edge ，它本身就带有平滑滚动的功能。
> 
> 关于这个问题，可以看看 #1685 提到的

说起来挺奇怪，似乎目前只有少数派的网页文章会卡顿...这是什么原因

**Comment by Kenshin** [comment]
滚动时会监听某些事件并响应，可能恰好跟少数派冲突了。 ++
