### ISSUE TITLE
为什么微信公众号的文章，aa无法进入阅读模式！而且只能手动框选，我手动框选之后，想要导出，一直在弹出“配置文件已更新，刷新当前页面后才能生效”这个提示！！

### ISSUE THREAD

**Issue by yanxiaowei1997** [Kenshin/simpread#2735]
![image](https://user-images.githubusercontent.com/48235202/131223701-eed095a1-6a43-4973-86e6-a89bc25117f8.png)

**Comment by yanxiaowei1997** [comment]
希望能够解答一下，o(╥﹏╥)o谢谢啦！

**Comment by Kenshin** [comment]
嗨，这是因为你的这篇文章多开了（同一个 URL 在不同的标签页打开了）造成的，关闭相同的或者重启浏览器就行了。
