### ISSUE TITLE
简悦同步助手无法开机自启动

### ISSUE THREAD

**Issue by YangWaldon** [Kenshin/simpread#2737]
![image](https://user-images.githubusercontent.com/49675185/131234155-a28af130-04f0-4cc1-a5b1-b43fd78f9069.png)

**Comment by Kenshin** [comment]
嗨，同步助手的自启动确实有点问题，不过你可以通过 https://github.com/Kenshin/simpread/discussions/1818 https://github.com/Kenshin/simpread/discussions/2011 这两个介绍。
