### ISSUE TITLE
Kenshin 先生您好，以下是我对简悦设置界面的拙见。

### ISSUE THREAD

**Issue by szzhiyang** [Kenshin/simpread#274]
这得从我先前提出的 [**issue 187**](https://github.com/Kenshin/simpread/issues/187) 说起。

我现在自己找到了一个我自认为更好的解决方案，就是 **不浪费设置界面的任何面积，将所有设置项分门别类地、整齐划一地罗列在同一层界面上。**  😄 

这样做的优点非常明显，就是任何人（无论是新手还是高手）都能 **一眼** 找到自己需要调整的设置项，而 **无需一层一层地翻找或者过多地滚动页面**，**指哪打哪**。 😂 

举个栗子，这是我自己制作的 Windows 系统优化工具：

![image](https://user-images.githubusercontent.com/30952626/38160041-a4d5d882-34e8-11e8-9900-da6904948f14.png)

任何人仅需扫视一下这个工具的界面，就能立即获知：

1. 这个工具能帮他们调整哪些 Windows 设置
2. 他们需要调整的 Windows 设置选项在界面的哪个位置
3. Windows 当前的设置状态

可以说，这真的是 **指哪打哪** 的状态了。 😂 

**同理，简悦的设置选项完全也可以这么编排，不同的类别横向排布，同一类别的子项纵向排布，并且能够随着界面的缩放比例以及面积自动做出调整。即便设置项目多到无法塞进浏览器的窗口范围，用户也只需稍微上下或者左右挪动一下页面就能遍览所有设置项目，岂不美哉？** 😂 

**您是我见过的最平易近人的开发者了，所以我将我的这个想法率先分享给您，而还没有告知其他独立开发者。得益于您高超的前端技术，您一定能把这个界面做的比我做的那个界面精美得多。如果您对我的这个想法有任何见解的话，请留言好吗？感激！** 🙏 ❤️

**Comment by Kenshin** [comment]
你好，感谢你的建议，我还是把这个 issue 关闭了，当然，这样并不会影响咱们的讨论。（以后有关类似的讨论也请在这里，不要另外再开 issues）

首先，我并不是一个 Designer ，所以对 UI 没有太多的见解，所以我直接使用了 Google 的 Metarial Design 设计方案。

其次，你提供的 UI 确实不错，但并不适用与简悦，这个 UI 只适用于都是 checkbox 的组件，你可以看看简悦的选项页，里面包含了很多不同类型的控件，除此之外，还有大量的交互。

最后，由于简悦已经使用了 MD 的设计方案，所以我并不会更改它，因为这样会影响用户的视觉统一性。

但是，以后有其它类似的产品，我会考虑你提供的方式，确如你说，简单，明了~   😊

**Comment by szzhiyang** [comment]
您能看到并回复我的想法，我就已经很开心了。 😄 

另外，我还是希望您能解决好页面缩放的问题，因为我现在正处于 **“不缩放字太小，缩放后简悦界面按钮点不了”** 的进退两难的困境中。 😂

**Comment by Kenshin** [comment]
额，是的，缩放问题还没有解决呢，呵呵~ 下个版本会搞定！

**Comment by szzhiyang** [comment]
太好了，好期待，感谢您！ 🙏
