### ISSUE TITLE
稍后读里的阅读模式显示空白

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2740]
<div type='discussions-op-text'>

<sup>Originally posted by **MrTownyp** August 29, 2021</sup>
![image](https://user-images.githubusercontent.com/23568668/131234206-5640d9c0-0d95-4d06-8cdc-894e4118407f.png)
昨天将页面加入“稍后读”，今天打开之后，发现阅读模式是空白，试了一下重新再添加新的页面到“稍后读”里，发现仍然是空白的。该怎么解决？</div>

**Comment by Kenshin** [comment]
嗨，请不要在 Discussions 提 Issues... 所以我把它转移到了这个 Isues，并删除了不合规的内容。

另外，就在你提问的 Discussions 下面就有 [解决方案](https://github.com/Kenshin/simpread/discussions/2727)

![image](https://user-images.githubusercontent.com/81074/131238864-86d7e6b2-9576-48fb-93e4-6eafbc06707f.png)

**Comment by MrTownyp** [comment]
> 嗨，请不要在 Discussions 提 Issues... 所以我把它转移到了这个 Isues，并删除了不合规的内容。
> 
> 另外，就在你提问的 Discussions 下面就有 [解决方案](https://github.com/Kenshin/simpread/discussions/2727)
> 
> ![image](https://user-images.githubusercontent.com/81074/131238864-86d7e6b2-9576-48fb-93e4-6eafbc06707f.png)

好的，多谢
