### ISSUE TITLE
同步助手启动后无法将配置同步到浏览器端,相关的增强导出功能一直调用失败

### ISSUE THREAD

**Issue by Tracker647** [Kenshin/simpread#2743]
购买了高级会员以后就是这样，也没把配置给其他设备，但是功能就是用不了，同步助手相关导出路径也配好了也不行，几天了还是这样, 现在连划线也说调用失败，想退款了

![image](https://user-images.githubusercontent.com/54085641/131250048-ba84ced9-0ee5-45aa-a1ae-8a96c7a6839f.png)

![image](https://user-images.githubusercontent.com/54085641/131250109-3f28a674-c720-4b36-a2b7-75d7468b1e67.png)
![image](https://user-images.githubusercontent.com/54085641/131250119-0e0a5bd1-65bd-45b6-ad7b-64486f1bcd27.png)
![image](https://user-images.githubusercontent.com/54085641/131250122-f955533d-6756-46a6-8c80-d6316886fdf2.png)

**Comment by Kenshin** [comment]
确认你的选项与截图保持一直

![image](https://user-images.githubusercontent.com/81074/131281601-c954750a-e69d-4e32-af45-79d40659df14.png)

![image](https://user-images.githubusercontent.com/81074/131281620-ee3565e7-2d17-452d-8d63-8ab168ed2ee6.png)

![image](https://user-images.githubusercontent.com/81074/131281706-bf61ae8b-9caf-42c0-bb72-6a675acb5d0b.png)

![image](https://user-images.githubusercontent.com/81074/131281749-298a711f-f14c-4165-a7e5-79a70760269a.png)

**Comment by Tracker647** [comment]
同步文件夹的路径要填写数据文件的位置，什么是数据文件，有例子吗？我现在的理解是像坚果云那样自己选择一个文件夹去同步。

**Comment by Kenshin** [comment]
我明天出个教程把，很简单，几本即可搞定。

**Comment by Tracker647** [comment]
教程呢？

**Comment by Kenshin** [comment]
@Tracker647 

https://github.com/Kenshin/simpread/discussions/2754 看下能否通过这个教程配置成功。

**Comment by Kenshin** [comment]
@amymorgen 

谢谢提示 👍

不过，这应该是使用同步助手的先决条件。 😂
