### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by chenlinbei** [Kenshin/simpread#2760]
https://developer.android.google.cn/topic/libraries/data-binding/expressions?hl=zh-cn

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

另外，如果同样是  developer.android.google.cn 相关问题请放到 https://github.com/Kenshin/simpread/issues/2759
