### ISSUE TITLE
按ctrl会自动加入未读

### ISSUE THREAD

**Issue by leegx1998** [Kenshin/simpread#2761]
有一个问题反馈一下，在任何界面按ctrl都会把当前页面加入未读列表，怎么设置这个添加未读的快捷键？

**Comment by Kenshin** [comment]
嗨，谢谢反馈，但应该不会存在此问题。

> 有两个地方可以修改

![image](https://user-images.githubusercontent.com/81074/131639002-900a8cdb-c2e8-4fb9-ae12-f374f0384563.png)

![image](https://user-images.githubusercontent.com/81074/131638804-6c58bc25-7e8d-4a47-974c-94c7fb2b487c.png)

> 进入 `chrome://extensions/shortcuts` 找到简悦

![image](https://user-images.githubusercontent.com/81074/131639094-a95edc6f-eb84-470e-acd9-25b8342a19f5.png)

**Comment by leegx1998** [comment]
感谢反馈，按照提示，已完成修改，祝简悦越来越好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread]按ctrl会自动加入未读 (#2761)





 
嗨，谢谢反馈，但应该不会存在此问题。
  
有两个地方可以修改
  

 

  
进入 chrome://extensions/shortcuts 找到简悦
  

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kenshin** [comment]
哈哈，没事，搞定就好，我关闭这个 Issues 了。

要是觉得简悦不错的，请帮忙在 [Chrome Webstore 五星好评+评论](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)，就是对简悦最大的帮助。
