### ISSUE TITLE
好奇kenshin关于pdf是怎么处理的

### ISSUE THREAD

**Issue by SeyeeL** [Kenshin/simpread#2778]
因为在帮助文档里有看到一句话，说不想对pdf的标注有过多的开发，因为觉得pdf有专业的工具。（凭印象大致复述的）

最近正好在实践渐进式总结，简单说就是对输入的有价值的信息进行一层一层的吸收处理（当然不是所有的信息都值得这应用到每一层），我主要把输入分成两大类，一类是书籍，一类是零散的文章，现在简悦已经可以对后者进行很好的处理了，但是如果是书籍的话，pdf目前在用的主要是zotero，但是不管是书籍还是文章，我比较理想的状态肯定还是不希望割裂，能All in one。

所以好奇一下kenshin对于书籍这类相关的pdf等文件是怎么处理的呢，想交流一下，附上做的一半的图

![image](https://user-images.githubusercontent.com/71479570/131964548-2cf985ef-d1dc-43c9-9bb8-fdc69d6c6ce8.png)

**Comment by Kenshin** [comment]
嗨，你能用 tg 吗？可以的话，方便的话，可以进群 https://t.me/simpreadgroup 找我。

**Comment by Kenshin** [comment]
> 所以好奇一下kenshin对于书籍这类相关的pdf等文件是怎么处理的呢，想交流一下，附上做的一半的图

其实我个人并不赞成 `All in one`，从用户角度看的话，`All in one` 是挺美好的，管理一切（假设同一个场景）。

但是，从载体角度来说，PDF / Epub 与 Web 有截然不同的逻辑。所以我一般使用不同的工具来管理它们。

你可以看看我在知乎的这篇文章，希望对你有所帮助 https://zhuanlan.zhihu.com/p/382129740
