### ISSUE TITLE
在应用于扇贝阅读中的短文中时，行尾的英语单词会被截断

### ISSUE THREAD

**Issue by Flysky0** [Kenshin/simpread#2780]
![image](https://user-images.githubusercontent.com/19644716/132024937-ad6888f1-c59b-461c-af02-6f1ac63d8ca5.png)

**Comment by Flysky0** [comment]
网链接：https://www.shanbay.com/news/articles/brszqe

**Comment by Kenshin** [comment]
嗨，你说的是这个意思吧？

![image](https://user-images.githubusercontent.com/81074/132079878-0507635f-22fb-4680-9db5-19e8a0e99912.png)

简悦对英文的排版还在优化中，解决后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，这个问题解决了，你可以安装 [英文阅读版面辅助增强](https://github.com/Kenshin/simpread/issues/2840)。

![image](https://user-images.githubusercontent.com/81074/133365550-ba9d9bd6-3d27-4524-8af4-984e48e7387a.png)

> 同时也可以使用下面两个跟英文阅读有关系的内容：

- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H)

***

我将关闭这个 issues，有任何问题随时在这里联络我。
