### ISSUE TITLE
简悦 SimpRead 转码的定制化

### ISSUE THREAD

**Issue by catwa1k** [Kenshin/simpread#2782]
简悦是一个很出色的产品，但是我平时是导出来阅读文章，每次开头都有：
本文由 简悦 SimpRead 转码， 原文地址：XXX
这段话，会比较影响用户体验，个人是非常介意的，以为买了高级版就能自定义去掉，搜了下 发现2020就加入TO-DO，现在还不能自定义，比较累
能理解要加原文地址，最起码是可以放在底部，在不影响阅读的前提下，这样每次阅读感觉都先看了 简悦的广告，这样就失去了阅读的兴趣。希望能理解下，继续支持

**Comment by Kenshin** [comment]
嗨，谢谢对简悦的喜欢。简单的解释下你说的问题。

> 简悦加入的 **简悦 SimpRead 转码** 并不是水印，从简悦 1.x （也就是免费使用时）最开始提供此功能时就有。

你可以理解为：

> 导出的内容肯定要有原出处的，所以直接放一个链接并不好看，所以就加上了这些。

关于这些内容大致分为两类：

1. HTML → 会在页脚出标识
2. Markdown → 会在正文开始处标识

Markdown 为什么会在正文开始出标识，主要是我觉得放在页脚不好看...  😂  如下图

![image](https://user-images.githubusercontent.com/81074/132080279-07780bbc-b187-466a-95f8-696d12060319.png)

如果放在页尾的话，感觉不是很好看。

![image](https://user-images.githubusercontent.com/81074/132080305-b7f3b534-fd76-4631-910f-db7ba1c52407.png)

除此之外，还有个问题，无论是 HTML 还是 Markdown 肯定是需要原文链接的，你觉得放到什么地方更好？

***
 
因为我看到你已经在 https://github.com/Kenshin/simpread/issues/1281#issuecomment-912659862 https://github.com/Kenshin/simpread/issues/751#issuecomment-912660927 重复提问了。

所以就关闭这个 Issues 了，不过，并不影响你继续在这里讨论。

**Comment by catwa1k** [comment]
论产品的灵活些，最好是让用户决定放哪，首先转码广告，高级会员可以删除，其次原文连接，让用户决定放在头部还是尾部。这样比较好

**Comment by catwa1k** [comment]
我搜了下 其实不少人对这个问题比较看重，如果决定权能放回到用户身上就更好，也会更多人开高级会员。好看这么看是放头部好看，但是我不想看到他，所以如果有权限可以决定，我会放在底部，本文由 简悦 SimpRead 转码，这段最好也能支持删掉，毕竟用户用习惯咱的产品，知道名字，开了高级会员的能自定义删掉就更好。谢谢

**Comment by Kenshin** [comment]
没想到这么快就回复了，可以考虑你的建议。

PS：其实也没有多少人看中这个问题，毕竟大多数人觉得无所谓的话，是不需要发 Issues，对吧。

当然，我不是说不实现它，这点毋须质疑。只是解释了下所谓很多人反馈的事情。

***

2.2 为什么没有加入这个功能，其实是忘记了。 😂  毕竟也没太多人回复。
还有个原因：简悦目前有太多的定制化了，2.2 为了避免太多，所以优先级比较低的就没有放上来。

***

综上，下个版本会实现它。

**Comment by catwa1k** [comment]
理解，谢谢，继续支持

**Comment by Kenshin** [comment]
哈哈，谢谢支持 🙏

如果方便的话，在 [Webstore 五星+好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 就是对简悦最大的支持。

**Comment by catwa1k** [comment]
当然要支持了，已五星+评价

**Comment by zhl111** [comment]
下个版本什么时候到来啊？我每次都是从不同的网页分批导入的，这个「本文由 简悦 SimpRead 转码」就会反复大量的出现，我很想取消这个title

**Comment by luzhe610** [comment]
什么时候能取消这段文字呢？

**Comment by wintopic** [comment]
2023.3.31还是没取消

**Comment by Borber** [comment]
还是不知道在哪删除这个

**Comment by Kiss-World** [comment]
@Kenshin 你好，这个关闭选项在设置中仍然没有找到，已开通高级会员。我主要是复制markdown到剪贴板

**Comment by Kenshin** [comment]
@Kiss-World 

目前并没有提供这种选项…但通过插件导出的功能均没有你提到的「问题」。

简悦并不会通过对某种功能的「阉割」来区分基础账户或高级账户。

高级账户功能大部分都是针对高阶「玩家」或深度工作流的用户。
