### ISSUE TITLE
导出到Markdown后 表格部分是html源代码，而不是Markdown的表格代码

### ISSUE THREAD

**Issue by skyoflovehc** [Kenshin/simpread#2783]
我看了之前有人提过这个问题，但是显示说2.X版本已解决，但我的版本是2.2.0版本，最近保存网页文章为md后，发现表格还是html格式的，编辑起来不方便，能不能麻烦优化下？

**Comment by Kenshin** [comment]
嗨，2.2 已经解决了这个问题，[细节看这里](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%a1%a8%e6%a0%bc)

![image](https://user-images.githubusercontent.com/81074/132081193-3299ab0c-d458-49e7-95b4-0940e6dc53f9.png)

**Comment by skyoflovehc** [comment]
> 嗨，2.2 已经解决了这个问题，[细节看这里](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%a1%a8%e6%a0%bc)
> 
> ![image](https://user-images.githubusercontent.com/81074/132081193-3299ab0c-d458-49e7-95b4-0940e6dc53f9.png)

按这样设置完，有的表格变为md格式，有的直接显示的就有问题，
![image](https://user-images.githubusercontent.com/16860505/132082169-446dbf68-d428-4ad4-a54d-f33b9ad58168.png)

**Comment by Kenshin** [comment]
是的，有些确实是有问题的，我在文档中做了说明

![image](https://user-images.githubusercontent.com/81074/132082375-88184a66-8c4e-49e7-a5ac-84dd591097a7.png)

这也是为什么会有 `HTML Table` 存在的必要性。
