### ISSUE TITLE
能不能加入连续阅读？

### ISSUE THREAD

**Issue by wolfan** [Kenshin/simpread#279]
在阅读小说之时 <= =>之后又要重新右键，为什么不能有连续阅读呐？
如果还可以增加标记功能就更好了，这样离开或者是错误操作也不用番半天了。

**Comment by Kenshin** [comment]
感谢反馈~
目前简悦暂时没有提供此功能，因为毕竟需要连续阅读的场景不多（当然，除了小说）

如果仅仅是阅读小说的话，我建议使用 User Script https://greasyfork.org/zh-CN/scripts/292-my-novel-reader
包括 `连续阅读` 的功能。

当然，如果是阅读其它方面的文章还是建议使用 简悦。  😊
