### ISSUE TITLE
阅读模式导出 Markdown，表格为 HTML 格式不便于编辑，望支持原生 Markdown 表格

### ISSUE THREAD

**Issue by yanzhaochen** [Kenshin/simpread#2796]
- 操作系统 **Windows 11 家庭版 21H2**

- 浏览器版本 **Microsoft Edge 版本 92.0.902.84**

- 简悦版本 **2.2.0**

> 习惯用 Markdown 作笔记的我发现简悦有导出 Markdown 的功能，非常惊喜！使用过程中发现真的非常方便，特别是还提供了直接复制 Markdown 代码的功能，设计太贴心了，非常实用，表示感谢！

同时发现了一个小问题，就是**导出 Markdown，表格保持了 HTML 的格式，不便于编辑**，演示如下

1.  导出为 Markdown 格式，在 Typora 中显示正常

    ![image-20210905180132803](https://picgo-yanzhao.oss-cn-shenzhen.aliyuncs.com/fabric/image-20210905180132803.png)

2.   但表格为 HTML 格式，不便于编辑

     ![image-20210905180228473](https://picgo-yanzhao.oss-cn-shenzhen.aliyuncs.com/fabric/image-20210905180228473.png)

希望可以直接转换为 Markdown 格式的表格，以便进一步编辑。例如有网站提供了相应功能

-   [johnbeech/html-table-to-markdown-converter: Converts HTML tables to Markdown. Paste in, click Convert. (github.com)](https://github.com/johnbeech/html-table-to-markdown-converter)

-   [markdownTables (jmalarcon.github.io)](https://jmalarcon.github.io/markdowntables/)

    ![image-20210905180859162](https://picgo-yanzhao.oss-cn-shenzhen.aliyuncs.com/fabric/image-20210905180859162.png)

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。🙏

至于你说的功能，是存在的，但是需要 [简单的配置](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%af%bc%e5%87%ba) 下：

![image](https://user-images.githubusercontent.com/81074/132123923-c5b12b09-3583-4e52-9a6a-e3e6a242d634.png)

至于为什么默认为 HTML Table ，主要是当表格过于复杂后，md 无法完美的导出，所以默认才导出 HTML 方案。

**Comment by yanzhaochen** [comment]
原来还有这样的问题，那我按照自己的需要自定义就OK了，简悦真的太棒了

看来是我大意了，没注意到文档里面已经写了。

添麻烦了，感谢回复~

**Comment by Kenshin** [comment]
哈哈，客气了。

你可以试试，如果有无法转换的较复杂的页面，也可以试试你上面提到的这两个方法能否解决，如果可以的话，我可以考虑把优化下这个转换功能。

没有其它问题的话，我关闭这个 Issues，你有需要时随时开启它。

***

PS：

如果方便的话，在 [Webstore 五星+好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 就是对简悦最大的支持。 🙏  😏
