### ISSUE TITLE
一直提示配置已更新，需要刷新，刷新后依然弹提示

### ISSUE THREAD

**Issue by SeyeeL** [Kenshin/simpread#2797]
![image](https://user-images.githubusercontent.com/71479570/132152500-218f5fcb-5ea4-446f-b271-90fde5870630.png)
https://es6.ruanyifeng.com/#docs/promise
按AA进入不了阅读模式

**Comment by Kenshin** [comment]
嗨，因为这个 URL 多开了，关闭相同 URL 的页面或重启浏览器就好。
