### ISSUE TITLE
同步助手在win10上无法正常使用

### ISSUE THREAD

**Issue by hidoos** [Kenshin/simpread#2798]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 win10

- 简悦版本 **2.2.0**
- 同步助手 1.0.1 版本，64位

同步助手，启动之后，就是一个白屏，看了一下开发者工具，发现html里面什么内容也没有，无法正常使用。

![image](https://user-images.githubusercontent.com/1256985/132157553-b4159ac6-94cb-4d8e-bfbf-2e90fcc26c2a.png)

**Comment by Kenshin** [comment]
嗨

请问是通过 [简悦的官方下载中心](http://ksria.com/simpread/wiki/#/Download?id=同步助手) 下载的吗？另外，下载时可以考虑 32 位版本。

**Comment by hidoos** [comment]
@Kenshin 你好，都是从官方提供的渠道下载的，32位版本也试过了，也是同样的问题。
这样吧，我再重新找一台电脑试试，可能和我的电脑环境有关吧。

**Comment by hidoos** [comment]
@Kenshin 我用同事电脑试过了，没问题。看来，确实我电脑环境问题了，我自己再排查一下吧。谢谢！

**Comment by Kenshin** [comment]
@hidoos 

okay 要是修复了这个问题，方便的话，也可以分享上来。

**Comment by hidoos** [comment]
@Kenshin 实在没找到是什么原因，最后我寄出大招，重装系统就可以了😂。

**Comment by Kenshin** [comment]
> @Kenshin 实在没找到是什么原因，最后我寄出大招，重装系统就可以了😂。

哈哈，太「惨」了…
