### ISSUE TITLE
tensorfly临时阅读模式不显示图片

### ISSUE THREAD

**Issue by G-lost** [Kenshin/simpread#280]
初步排查原因
图片源地址

> http://www.tensorfly.cn/tfdoc/images/MNIST.png

临时阅读模式转码地址

> http://www.tensorfly.cn./images/MNIST.png

**Comment by Kenshin** [comment]
临时阅读模式（包括：阅读模式）
的确有这样的情况，主要发生在 lazy load image 时会发生。
目前由于规则没有规律，所以并没有好的办法解决。

**Comment by Kenshin** [comment]
下个版本会改善这个情况，并把这个站也做下官方适配，所以 Reopen 了此 issues~

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

你可以用新版的解析引擎试试，应该可以解决这个问题了，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
