### ISSUE TITLE
阅读的时候会把最底下的内容展开 导致篇幅较长 不好保存

### ISSUE THREAD

**Issue by meihus** [Kenshin/simpread#2801]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E5%8A%A1%E9%99%A2>

**Comment by Kenshin** [comment]
嗨，我没理解你的意思...

**Comment by Kenshin** [comment]
我先关闭这个 issues 等你回复后我再重启开启它。

**Comment by meihus** [comment]
就是维基百科下面有被收缩和展开的内容 在维基上看默认是收缩状态的 但是用简悦看全部都展开了 会使文章变得很长 而且展开的内容并不是自己想要看到的

**Comment by Kenshin** [comment]
> 就是维基百科下面有被收缩和展开的内容 在维基上看默认是收缩状态的 但是用简悦看全部都展开了 会使文章变得很长 而且展开的内容并不是自己想要看到的

嗨，大致了解你的想法了。确实有意思的想法...

> **大家都是希望对隐藏的内容在进入阅读模式后展开...**，而你反其道的做法还是第一次反馈给我。

另外一点，**你给出的页面中我也没有找到你说的隐藏的地方**

**Comment by meihus** [comment]
就是查伦编的部分被自动展开了 我发不了图片 有的查伦编后面很长 突然感觉维基百科不用简悦看也挺舒服的 用简悦就是想保存到有道云笔记里面

**Comment by Kenshin** [comment]
你说的 查伦编 在我这边没有出现，看截图

![image](https://user-images.githubusercontent.com/81074/132281472-05da1d1b-05da-4b4b-8f36-00d5a0cccef1.png)

如果你界面跟我不一样的话，可以试试更新官方主适配源

![image](https://user-images.githubusercontent.com/81074/132281620-0850bc97-42ca-4a69-b601-8bc06a0f54a8.png)

**Comment by meihus** [comment]
感谢 我换了另外的维基百科搜索词 更新了样式 重置了维基百科的设置 问题得到解决

**Comment by Kenshin** [comment]
> 感谢 我换了另外的维基百科搜索词 更新了样式 重置了维基百科的设置 问题得到解决

哈哈，搞定就好。

***

如果方便的话，在 [Webstore 五星+好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 就是对简悦最大的支持。 🙏  😏

**Comment by meihus** [comment]
我是粽子节后第一个评分 高级账户 希望越做越好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 中午12:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 阅读的时候会把最底下的内容展开 导致篇幅较长 不好保存 (#2801)





  
感谢 我换了另外的维基百科搜索词 更新了样式 重置了维基百科的设置 问题得到解决
  
哈哈，搞定就好。
 
 
如果方便的话，在 Webstore 五星+好评 就是对简悦最大的支持。 🙏  😏
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kenshin** [comment]
> 我是粽子节后第一个评分 高级账户 希望越做越好

哈哈，这是老用户了。🙏
