### ISSUE TITLE
保存到为知笔记重复保存问题

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#2802]
你好，我的为知笔记保存，现在每次都被重复保存，即使仅仅在SimpleRead上只显示了一次“已保存到为知笔记”， 但是我在为知笔记中查看，出现了多个相同的笔记。请务必告知我是简悦的问题还是为知笔记的问题
如下图
![image](https://user-images.githubusercontent.com/37976371/132274512-5c550d17-e77e-41b7-a9cd-d1e77ca655ba.png)

**Comment by Kenshin** [comment]
嗨，我刚刚测试了下，没有问题。

你在保存时，右上角提示几次？如果只是一次提问的话，肯定就是保存一次。

你也可以试试：取消授权再重新授权的方式。

**Comment by rw1995** [comment]
> 嗨，我刚刚测试了下，没有问题。
> 
> 你在保存时，右上角提示几次？如果只是一次提问的话，肯定就是保存一次。
> 
> 你也可以试试：取消授权再重新授权的方式。

我重新授权了下，现在可以了

**Comment by Kenshin** [comment]
okay 搞定就好~
