### ISSUE TITLE
代码增强插件报错

### ISSUE THREAD

**Issue by SeyeeL** [Kenshin/simpread#2806]
![image](https://user-images.githubusercontent.com/71479570/132610959-3472f800-aaf1-496d-868a-218f83c0dc66.png)
https://www.zuiyu1818.cn/posts/VScode_Vue.html

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
