### ISSUE TITLE
使用小书签一键收藏，导致simpread.json文件变成1k（无法复现）

### ISSUE THREAD

**Issue by hiforrest** [Kenshin/simpread#2807]
[simpread_config.json.zip](https://github.com/Kenshin/simpread/files/7133131/simpread_config.json.zip)
这是现在的simpread.json，之前有600多k。这次一下把内容都清空造成数据损失，是严重的bug。

**Comment by Kenshin** [comment]
嗨，使用 `simpread_config.json` 最好的方案是配合网盘，一般网盘都具有历史记录功能。

另外，发生此问题的 URL 给我看下。

**Comment by Kenshin** [comment]
补充下：发生问题的 URL 是 `.zip` 里面提供的 URL 吗？

**Comment by hiforrest** [comment]
对，是这个URL：https://www.nosuchfield.com/2020/12/26/How-to-calculate-your-mortgage/

**Comment by Kenshin** [comment]
嗨，我稍后在测试下，你能稳定复现这个问题吗？

**Comment by hiforrest** [comment]
刚试了一下没有复现，该URL正常加入稍后读

**Comment by Kenshin** [comment]
> 刚试了一下没有复现，该URL正常加入稍后读

okay 可能是某些情况下导致了特殊的 Bug，后续的版本会有对数据结构验证性的功能。

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

修复了一个小书签的 Bug，不知道这个 Issues 的内容是否已经修复了，因为很难复现，所以我先关闭这个 issues 了，有需要可以随时重开它。

除此之外，1.1.4 版还包括下面的一些功能：

## 下载地址

- [包含多种渠道下载](http://ksria.com/simpread/docs/#/Sync?id=下载)

## 更新日志

- [更新日志](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792)

## 新增 💄 

### 朗读

将正文转换为语音并播放，与 Edge 内置的大声朗读功能一样，均来自 Microsoft Azure 的语音服务。

<img width="3650" alt="TTS@plugin" src="https://user-images.githubusercontent.com/81074/206418879-c6ba7b85-e706-4741-b0b1-2e5123f2493d.png">    

- 插件端 [朗读](https://github.com/Kenshin/simpread/discussions/4833)

- 内置到 [稍后读极速版的本地快照](http://ksria.com/simpread/docs/#/TTS?id=内置到本地快照)
