### ISSUE TITLE
macOS 上导出网页的时候期望保留原网站的 URL（Finder 中文件的 Where from 字段）

### ISSUE THREAD

**Issue by LudwigWS** [Kenshin/simpread#2808]
- 操作系统 macOS

- 浏览器版本 Chrome Version 92.0.4515.159 (Official Build) (x86_64)

- 简悦版本 **2.2.0**

- 发生问题的地址，任意网站

比如我导出一篇文章为离线 HTML，在 macOS 上 Cmd-I 查看，Where from 字段显示为：chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/，期望保留原网站地址

**Comment by Kenshin** [comment]
嗨，请问是在稍后读中导出的吗？除此之外，这个页面里面也有原文 URL，是否也是错误的？

**Comment by LudwigWS** [comment]
在网页原文，点击插件进入阅读模式。此时在 Chrome 地址栏显示的是原文的地址，点击右下角的三个点，导出以后地址是 `chrome-extension://`。希望能保留这个字段为原地址哈，辛苦～

**Comment by Kenshin** [comment]
emmm

如果是阅读模式（非稍后读中）的话，导出 HTML，在页脚处的 URL 应该是原出处，如下图

![image](https://user-images.githubusercontent.com/81074/132945323-55f807da-1db2-4c44-90ba-0d83fd9eee19.png)

另外，把完整命令告诉我下。

**Comment by Kenshin** [comment]
补充下：

你说的这个情况仅有可能出现在 **通过稍后读导出**。

**Comment by LudwigWS** [comment]
今天又导出了一下，发现不存在此问题了

**Comment by Kenshin** [comment]
> 今天又导出了一下，发现不存在此问题了

哈哈，没问题就好。 👍
