### ISSUE TITLE
同步助手 PDF 导出无内容（附解决方案）

### ISSUE THREAD

**Issue by sunux** [Kenshin/simpread#2818]
## 问题现象

> 导出的 PDF 文件只有一行 `Error: ENOENT: no such file or directory, stat '/Users/xxxxx/tmp-xxxxx`。

**Comment by Kenshin** [comment]
嗨，重新再试一次就可以了。

**Comment by Kenshin** [comment]
补充一点：

> 如果还是不行的话，看看 https://github.com/Kenshin/simpread/discussions/2817  https://github.com/Kenshin/simpread/discussions/1617 这两个解决方案。
