### ISSUE TITLE
CSDN博客在适配站点列表里面，但是我浏览时没有阅读模式？

### ISSUE THREAD

**Issue by qqlovekerry** [Kenshin/simpread#282]
在[适配站点列表](https://github.com/Kenshin/simpread/wiki/%E9%80%82%E9%85%8D%E7%AB%99%E7%82%B9%E5%88%97%E8%A1%A8)里面有`http://blog.csdn.net/`，但是csdn里面的文章（比如[这一篇文章](https://blog.csdn.net/sunhf_csdn/article/details/79848837)）似乎只能使用聚焦模式和临时阅读模式，请问是我理解的不对还是有bug呢？

**Comment by Kenshin** [comment]
请确保适配站点为最新，`选项页 → 共通 → 同步适配列表`
然后刷新你给出的连接，进入阅读模式，试试看。

**Comment by qqlovekerry** [comment]
非常非常感谢！问题解决了。
请问适配站点必须要自己手动更新吗？如果能够是自动更新的话可能用户体验会更好一些。

**Comment by Kenshin** [comment]
不需要手动更新，简悦会定期自己检测，但是毕竟有时间间隔，所以也可以使用手动强制更新。
祝用的愉快~
没有问题的话，我将关闭此 issues 了  😀
