### ISSUE TITLE
加入稍后读后页面样式发生变化

### ISSUE THREAD

**Issue by aoout** [Kenshin/simpread#2821]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Windows

- 浏览器版本 版本 93.0.961.38 (官方内部版本) (64 位)

- 简悦版本 2.2.0

- 发生问题的地址 https://www.zhihu.com/question/305131584/answer/566237106

**请描述你的问题**

这是阅读模式内。

![image](https://user-images.githubusercontent.com/60838705/132929611-22a61290-3e46-4d96-9fc0-e955c9305fb1.png)

这是加入稍后读后。

![image](https://user-images.githubusercontent.com/60838705/132929665-54748cf4-f1af-4237-8b3a-ba15b4055c87.png)

可以发现，不知道为什么露出来了一些html代码。

**Comment by Kenshin** [comment]
嗨，我这边是没问题的，截图如下

![image](https://user-images.githubusercontent.com/81074/132933085-ec8564a0-156d-4d48-a6f3-1ba79a22eb8b.png)

> 请升级适配列表后再试试，留意**适配源的数量为 365**

![image](https://user-images.githubusercontent.com/81074/132933099-a728bad9-9d20-417c-940a-4c3e1db43948.png)

**Comment by aoout** [comment]
@Kenshin 
你好，我指的是在稍后读内，而不是直接进入阅读模式。你的这一张截图貌似不是在稍后读内的。
也就是从这里进入。
![image](https://user-images.githubusercontent.com/60838705/132936312-de9bf95b-03a1-444b-8205-0c139b6293da.png)

那个适配源我在提问之前已经更新过一遍了。

**Comment by Kenshin** [comment]
嗨，抱歉，你描述的很清楚了，只是我思维定势了。 😅 

不过，这是我加入到稍后读里面的效果，同样没问题的。

![image](https://user-images.githubusercontent.com/81074/132936431-f447ad2a-2453-4fff-8fa8-dd37fdc4027a.png)

如果你也在使用同步助手的话，可以试试 https://github.com/Kenshin/simpread/discussions/2146 提到的解决方案，一劳永逸。

**Comment by aoout** [comment]
@Kenshin 
如下图，可以看到，这个页面加载自本地，可是显示依然出现了异常。
![image](https://user-images.githubusercontent.com/60838705/132938295-a0c2b0f6-9492-4eed-ac85-4666d8483862.png)

我选择了使用同步助手内置的解析器后，效果如下：
![image](https://user-images.githubusercontent.com/60838705/132938348-ad1356f0-5c34-4193-87b5-84535904c347.png)

发现，异常得到了修正。
可是，当我打开out文件夹下的本地文件，
![image](https://user-images.githubusercontent.com/60838705/132938394-c99fef52-68ea-45ed-be7d-6281620e7f03.png)
才能够真正看到我想要得到的效果。也就是和你上面所发的一样的效果。
我不知道我们的情况有哪里不一样，以使得我们最终得到的结果不同。

**Comment by Kenshin** [comment]
emmm

1. 刚才的截图是**没有使用在本地加载 HTML** 的方案。

2. 我使用了**使用了本地加载 HTML** 的方案，也得到了跟第一条一样的结论（所以就不在截图了）

3. 你可以把你导出的本地 HTML 发到这里来，我看看。

4. 你是否没有安装类似 uBlock 去广告的功能。

5. 在阅读模式下，然后看看下图是否跟我的一样

![image](https://user-images.githubusercontent.com/81074/132938712-2bd74e3e-4340-4d62-a884-eeba1f7c2536.png)

PS：这跟问题能每次都稳定复现吗？你可以重复操作看看，或者说是否每个知乎都存在类似的问题？

**Comment by aoout** [comment]
@Kenshin 
首先是非常抱歉耽误了你的时间，其次，这样的显示错误的确是因为我没有启用官方适配源造成的。
我没能及时发现问题出自于此的原因在于：
1. 我没能理解为什么阅读模式内显示正常，稍后读内不正常，在控制变量后，所以将目光投向了只与稍后读有关的方向。
2. 我没能理解为什么官方适配源不是默认被选用的。
上面两个不理解，不是在质疑该软件的设计，只是用来表达我之前无知的状态。
最后，感谢你的友善的态度，我之前为高级版付费的不安感彻底消除了。

**Comment by Kenshin** [comment]
哈哈，没事的。

不过，（估计是你新用户）更正一下：

> 阅读模式（也就是你上述反馈的功能）是一直都是免费使用的（从简悦在 2017年发布后一直到 2020年 2.0 收费之前），截至到现在，我每天都会接收到一定数量的 Issues，平均每天至少需要花费半个小时来处理这些内容。

免费阶段都是如何，更何况是现在。 😏  

***

PS：没有其它问题的话，我关闭这个 issues 了。
