### ISSUE TITLE
配置文件版本过低，登陆失败，不知道什么原因？

### ISSUE THREAD

**Issue by Fintinger** [Kenshin/simpread#2822]
### 导入之后出现下图中弹窗，并没有登录上
@Kenshin 

![](https://gitee.com/fintinger/figure-bed/raw/master/img/202109110944458.png)

![](https://gitee.com/fintinger/figure-bed/raw/master/img/202109110938021.png)

**Comment by Kenshin** [comment]
1. 你的导入是只通过配置文件导入？另外，你的配置文件是否是 2.2 版本之前的？如果是的话，这个提示属于正常情况提示。（不用理会）

2. 第二个截图确实有问题，你可以使用 https://github.com/Kenshin/simpread/discussions/2816 提到的方式，再试试。

PS：只要是正常使用没有被锁的话，都不会有问题的。

**Comment by Fintinger** [comment]
是的，我重装一遍扩展之后不再出现上述问题了。

**Comment by Kenshin** [comment]
哈哈，搞定就好。

我关闭这个 Issues 了
