### ISSUE TITLE
插件中心无法下载

### ISSUE THREAD

**Issue by me-for-i** [Kenshin/simpread#2823]
现在插件中心无法下载插件

**Comment by Kenshin** [comment]
嗨，我刚才测试了，是没问题的。（包括：插件官网 与 安装）

是无法安装？还是无法访问  http://simpread.pro/plugins

如果是无法安装的话，解决方案 https://github.com/Kenshin/simpread/discussions/1696

**Comment by me-for-i** [comment]
不好意思，我浏览器之前装了一些改变字体的扩展，扩展下面的图标都被隐藏了，然后我就以为需要点击进入二级菜单再安装，就一直点那个div，我回头关一下扩展就好了


---原始邮件---
发件人: &quot;Kenshin ***@***.***&gt;
发送时间: 2021年9月11日(周六) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 插件中心无法下载 (#2823)




 
嗨，我刚才测试了，是没问题的。（包括：插件官网 与 安装）
 
是无法安装？还是无法访问  http://simpread.pro/plugins
 
如果是无法安装的话，解决方案 #1696
 
&mdash;

**Comment by Kenshin** [comment]
哈哈，没事的。

我关闭这个 Issues 了~
