### ISSUE TITLE
标注浮窗的动画令人恼火

### ISSUE THREAD

**Issue by hiforrest** [Kenshin/simpread#2825]
![动画的问题](https://user-images.githubusercontent.com/2953848/132973159-5aa8d7eb-2cc1-4cf8-bf6c-b09c929a5513.gif)

### 现有动画的问题：

①大幅度和长距离的移动动画给我造成了非常大的干扰，阅读是需要集中注意力的，这个动画很容易让人分心。

②浮窗出现的位置不定，有时候是上方，有时候是右方。

②可以看到，有时候弹窗的位置会随着鼠标指针的位置变化而再变动一次，不应该跟用户捉迷藏，一点也不好玩。

### 建议：

①大幅度减少动画时间，也许0.1到0.4秒之间；或者去掉。大幅度减少移动移动距离，也许4到8像素左右即可；或者去掉。

②浮窗的位置固定出现在选择文字的上方，有时候上方，有时候右方，有时候左方，难以预测。

③杜绝浮窗出现后，鼠标稍微移动位置又变动的情况。

### 参考：
**可以看到文字工具类浮窗应该是准确、快速、稳定、可预期的。**

![动画的参考](https://user-images.githubusercontent.com/2953848/132973190-39d970b1-331b-4d32-9d04-7db907d31429.gif)

**Comment by Kenshin** [comment]
你可以根据

![image](https://user-images.githubusercontent.com/81074/132973323-8dbd6d7b-905d-4373-9a65-79fc8b701237.png)

这些设置

**Comment by hiforrest** [comment]
抱歉刚刚情绪有点激动。
我设置为「鼠标点击时显示」后，浮窗出现位置固定为选区右下方，动画固定位由下至上的移动动画。
但是动画速度「正常」和「快速」没感到明显差别。我认为「快速」可以再快一些，移动距离再短一些。

**Comment by Kenshin** [comment]
@hiforrest 

没事的。

***

> 浮窗出现位置固定为选区右下方，动画固定为由下至上的移动动画。

在右侧显示是因为**离鼠标最近**，鼠标只要稍微移动下就能进行操作。

![image](https://user-images.githubusercontent.com/81074/132977666-6778babf-5f6b-486e-890b-85b2fb0e3fd1.png)


> 「正常」和「快速」没感到明显差别。我认为「快速」可以再快一些，移动距离再短一些。

动画效果主要是**缓动效果**，如果还是觉得快的，可以根据 https://github.com/Kenshin/simpread/discussions/2829 提供的方式修改。

**Comment by hiforrest** [comment]
缩短动画时间后好多了😏

**Comment by Kenshin** [comment]
> 缩短动画时间后好多了😏

为了这个问题，我特意又开了个使用技巧 https://github.com/Kenshin/simpread/discussions/2829

还有，大部分在阅读模式上出现的样式问题，都可以通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决
