### ISSUE TITLE
【疑问】为什么稍后阅读无反应

### ISSUE THREAD

**Issue by Ctipsy** [Kenshin/simpread#283]
在页面右键，选择“打开稍后读”，直接是下图所示结果。 按该功能字面意思，不应该是添加到稍后读列表里吗
![image](https://user-images.githubusercontent.com/31062383/38497166-c5a151da-3c32-11e8-8f5b-7d27a99b07b1.png)

**Comment by Kenshin** [comment]
`打开稍后读` → 意味着是打开...
`保存到稍后读` → 将当前（阅读模式）下的页面保存到稍后读...

后者在阅读模式的控制栏里面~
