### ISSUE TITLE
简悦对英文单引号的排版处理有点问题

### ISSUE THREAD

**Issue by JuneLiao** [Kenshin/simpread#2834]
我在Economist打开简悦看文章时，发现简悦对英文状态下的单引号'处理有点问题，
比如[这篇文章](https://www.economist.com/1843/2021/08/10/the-perfectionism-trap)中wouldn’t的单引号和t隔了三四个空格；排版显示成了wouldn’     t
但是切换不同主题色后，有几个主题色状态下是正常的，
可是导出成pdf或手机截图（用简悦的导出手机截图插件）还是会有显示问题。
开发者可以检测一下，我进入的这个网址

**Comment by JuneLiao** [comment]
![image](https://user-images.githubusercontent.com/77012366/133051276-1b40ff51-c563-427e-8fd1-cb5b41e21176.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，目前对英文的排版确实需要优化，我会出一个相关的插件来解决这个问题。

到时候会在这里通知到你。

**Comment by Kenshin** [comment]
嗨，这个问题解决了，你可以安装 [英文阅读版面辅助增强](https://github.com/Kenshin/simpread/issues/2840)。

![image](https://user-images.githubusercontent.com/81074/133365550-ba9d9bd6-3d27-4524-8af4-984e48e7387a.png)

> 同时也可以使用下面两个跟英文阅读有关系的内容：

- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H)

- [适配扇贝阅读的适配站点](https://github.com/Kenshin/simpread/discussions/2705)

***

我将关闭这个 issues，有任何问题随时在这里联络我。
