### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by sgrjyb** [Kenshin/simpread#284]
1.请删除 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码, 原文地址等 多余内容
2.增加临时阅读模式快捷键选项
3.建议取消聚焦模式(与临时阅读模式重合)
4.给每个功能增加快捷键选项(像surfingkeys)

**Comment by Kenshin** [comment]
1. 可以通过 `自定义样式` 解决；
2. 与 `阅读模式` 一样的快捷键；
3. 并不会取消聚焦模式，很多用户经常会使用 `聚焦模式`
4. 快捷键 [请看这里](https://github.com/Kenshin/simpread/wiki/%E5%BF%AB%E6%8D%B7%E9%94%AE)

感谢建议，个人建议看看 简悦的 [WIKI](https://github.com/Kenshin/simpread/wiki)。   ☺

**Comment by sgrjyb** [comment]
@Kenshin 请把自定义样式 贴给我 ？（小白）
