### ISSUE TITLE
你好，我该怎么获得简悦的token？popclip需要token才能链接

### ISSUE THREAD

**Issue by MatsuriMW** [Kenshin/simpread#2843]

**Comment by Kenshin** [comment]
嗨

打开 https://simpread.pro/developer

![image](https://user-images.githubusercontent.com/81074/133540357-427357a0-8a4e-475d-9366-0c0077b35ca1.png)

点击后会进入 [此页面](https://simpread.pro/api/#/%E5%A6%82%E4%BD%95%E5%BC%80%E9%80%9A)

![image](https://user-images.githubusercontent.com/81074/133540387-5459e6a2-ff88-49df-9068-122797251bd1.png)

根据教程配置就好了。
