### ISSUE TITLE
插件页无法使用，稍后读页面图标全部白色看不清。

### ISSUE THREAD

**Issue by jinwendaiya** [Kenshin/simpread#2848]
Windows 系统 ，版本 93.0.4577.82（正式版本） （64 位），简悦 - SimpRead 2.2.0.520
在chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html  稍后读页面出现图标全白看不清状况，已经误删掉一次文档
![060c6b523977384a8fa9311aedc0069](https://user-images.githubusercontent.com/30795466/133557243-41ca5f90-0961-4b44-aba6-9e6d72627405.png)

还有在插件中心https://simpread.ksria.cn/plugins/  点插件下载毫无反应，如下图
![a55167364ee1a9eb65e4e926e71a90d](https://user-images.githubusercontent.com/30795466/133557354-fcb13cab-908e-4360-9502-fc4986c738ef.png)

**Comment by Kenshin** [comment]
emmm

你的网络是哪里的？这些问题都是因为一个 icons `link url` 未访问成功造成的。

你可以试试访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css 看看能否正常打开？

**Comment by jinwendaiya** [comment]
国内电信网啊，链接是打不开的

**Comment by jinwendaiya** [comment]
![image](https://user-images.githubusercontent.com/30795466/134273075-21b4afb2-fa58-4225-9204-c2c71036eeb0.png)
目前仍是一片白茫茫

**Comment by jinwendaiya** [comment]
@Kenshin

**Comment by Kenshin** [comment]
请问你的网络环境是什么？
另外，请保证你的网络畅通。

盲猜是「成都电信」吗？

**Comment by jinwendaiya** [comment]
嗯是成都电信，网络通畅没问题

**Comment by Kenshin** [comment]
> 嗯是成都电信，网络通畅没问题

果然... 你是不是无法访问 http://cdnjs.cloudflare.com/ 这个页面？如果是的话，想办法访问它就可以了。 😂

**Comment by Kenshin** [comment]
另外，抱歉。（之前漏掉了这个 Issues，多亏你重新 AT 了我一次。

**Comment by Kenshin** [comment]
另外，试试更改 DNS 为 114.114.114.114

**Comment by jinwendaiya** [comment]
多谢大佬，今天恢复正常了，改DNS有效。

**Comment by Kenshin** [comment]
> 多谢大佬，今天恢复正常了，改DNS有效。

哈哈，没问题就好。

- 我把这个记录到 https://github.com/Kenshin/simpread/discussions/2906

没问题的话，我关闭 Issues 了~
