### ISSUE TITLE
解析少了一些东西？是否被隐藏

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#2849]
链接：https://light-city.club/sc/basic_content/static/
原图：
![image](https://user-images.githubusercontent.com/37976371/133562266-45e56a1d-d537-4784-bcc5-1def4a7f8712.png)
解析后的页面：
![image](https://user-images.githubusercontent.com/37976371/133562371-a0ca62bd-a5b6-4755-8082-3ef61c770b2f.png)

请看===》输出栏
如何我能更好的调整呢？

**Comment by rw1995** [comment]
在该blog下，多个代码都会被隐藏，见 const的那些事儿

**Comment by Kenshin** [comment]
嗨，你可以试试把 代码高亮 插件关闭，看看能否改善？

另外，代码高亮插件确实存在一些问题，细节看 #500

**Comment by rw1995** [comment]
> 嗨，你可以试试把 代码高亮 插件关闭，看看能否改善？
> 
> 另外，代码高亮插件确实存在一些问题，细节看 #500

貌似无效，我取消了代码增强插件,但是显示效果依然如此

**Comment by Kenshin** [comment]
okay 我已记录到 #500 代码高亮因为其模式没法掌握，所以不能 100% 完美适配任何页面  😂 

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
