### ISSUE TITLE
知乎数学公式显示有问题

### ISSUE THREAD

**Issue by zackdown** [Kenshin/simpread#2856]
- 操作系统 **Win10 64位**

- 浏览器版本 **Microsoft edge版本 94.0.992.23 (官方内部版本) beta (64 位)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/39281734>

**阅读模式下,无论是否开启词法分析引擎和纯粹模式,公式的出现位置,内部字符大小,背景颜色都出现了问题,在文中"一、交换群"下的例一例二下都能明显观察到这个现象**

**截图**

![公式的背景颜色 位置 大小有问题](https://user-images.githubusercontent.com/71256557/133870069-4c51edc5-8cb2-4b07-89c9-0387dbd9d782.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

> 知乎并没有使用通用的 LateX 方案，而是使用了图片方案。

可以考虑为此专门出个插件来解决。

**Comment by Kenshin** [comment]
嗨，知乎数学公式在导出 PDF 时无法显示图片的问题已经解决了，请安装 [此插件](https://github.com/Kenshin/simpread/issues/2860)

因此，我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
另外，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869
