### ISSUE TITLE
阅读模式下的划词翻译失效

### ISSUE THREAD

**Issue by Daydog** [Kenshin/simpread#2857]
打开阅读模式，沙拉查词等一系列划词翻译失效，在原网页可以使用，这个能完善吗谢谢

**Comment by Kenshin** [comment]
嗨

1. **沙拉查词应该支持简悦了**，请留意沙拉查词的版本是否是最新的。
2. 关于翻译的一些技巧可以看下 https://zhuanlan.zhihu.com/p/410684466 提到的几种解决方案。
