### ISSUE TITLE
知乎公式导入到notion图片过大

### ISSUE THREAD

**Issue by YongxinJackGuo** [Kenshin/simpread#2858]
知乎含有公式的部分，inline的那种，转换到notion里面就变成特别大的图片。例如一个未知数x，转换后到notion中就变成半个屏幕大的图片

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

应该跟 https://github.com/Kenshin/simpread/issues/2856 是一种问题，我看看能否通过插件优化它。

**Comment by Kenshin** [comment]
嗨，知乎数学公式在导出 PDF 时无法显示图片的问题已经解决了，请安装 [此插件](https://github.com/Kenshin/simpread/issues/2860)

因此，我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
另外，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by ladychili** [comment]
更新了适配源、安装了插件。导入notion之后公式直接不见了，只剩图片。

问题页面： https://zhuanlan.zhihu.com/p/74073096


导入效果：

before
![image](https://user-images.githubusercontent.com/27876613/141080452-97c282fa-4172-403a-b492-a76a4a37ee1e.png)

after

![image](https://user-images.githubusercontent.com/27876613/141080706-1db2779a-8589-4a92-9ae8-d8033dddd5cf.png)

**Comment by Kenshin** [comment]
@ladychili 

> 导入notion之后公式直接不见了，只剩图片。

嗨，这不是简悦的问题，知乎公式本来就是一个另类的图片，你可以试试 https://github.com/Kenshin/simpread/issues/2858#issuecomment-922798770 给出的方案

![image](https://user-images.githubusercontent.com/81074/141091151-72e34100-5f74-430b-b144-8d6d92835b64.png)

然后导出 Markdown 到本地，是没问题的

![image](https://user-images.githubusercontent.com/81074/141091054-2b907e0e-4c75-4595-b72f-6d7da9b5074f.png)

Notion 对 Markdown 支持度有限，细节看这里 https://github.com/Kenshin/simpread/discussions/1773

**Comment by ladychili** [comment]
多谢。在 #1430  里了解到了，主要还是Notion的问题。
