### ISSUE TITLE
插件崩溃, 消失, 稍后读都消失了. 百分浏览器cent

### ISSUE THREAD

**Issue by hkdiy** [Kenshin/simpread#2862]
1. 环境
win10系统, cent百分浏览器最新版, 官网下载的简悦2最新版crx文件. 
安装有同步助手

2. 事情经过

2021-09-02 
莫名丢失插件, 

重新安装插件后, 重新召回高级账户. 检查问题时, 在插件界面看到
![image](https://user-images.githubusercontent.com/13012269/133889071-82ff7673-8556-45d3-83df-a0faf614182c.png)
![image](https://user-images.githubusercontent.com/13012269/133889075-b5e31578-4415-4b9b-ac7a-bd9100478ca7.png)
不知道是不是问题所在.

同时 稍候读全部丢失
当时有尝试发issue, 但是失败, 网络实在不行.
2021-09-18 今天继续丢失
尝试几次, 发issue成功.
3.诉求

- 目前还未重新安装插件, 能找回稍候读数据么?
- 问题在哪?
- 稍候读, 在配合自动化保存到本地是否可以避免丢失数据

**Comment by Kenshin** [comment]
嗨，回复下你的问题

> 莫名丢失以及使用 crx 方式

如果使用了拖拽 crx 的方式确实存在这个问题，这不是简悦的问题，因为通过此方式的话，会出现在 Windows 的临时目录下，所以存在风险，关于此的描述请看 https://github.com/Kenshin/simpread/discussions/1645

> 截图提到的错误

不用理会，跟你说的问题无关。同时这些错误也不会引起任何使用上的问题。

> 目前还未重新安装插件, 能找回稍候读数据么?

因为我看你使用了同步助手，所以使用了自动同步方案的话，本地有 `simpread_config.json` 自然没有问题。
否则的话，简悦的稍后读存放在了 Chrome 自己的沙箱系统，如果没有做保存的话，就肯定拿不到了。

简悦提供了：坚果云 / Dropbox 的手动同步方案，以及同步助手的自动同步方案。（但前提是需要你使用它们

> 稍候读, 在配合自动化保存到本地是否可以避免丢失数据

当然可以了，自动化最开始就用作这个方式的，具体如何配置可以看 https://github.com/Kenshin/simpread/discussions/2754 https://github.com/Kenshin/simpread/discussions/2146 https://github.com/Kenshin/simpread/discussions/2147 这三个教程

**Comment by hkdiy** [comment]
按照 #1645 操作方式, 稍候读已经找回. 谢谢

**Comment by Kenshin** [comment]
解决就好。

不过，请导出配置文件后使用 zip 方式安装，除此之外，因为使用了同步助手，所以最好使用自动同步方案。

毕竟你有稍后读，只有自动同步 + 网盘方案才能实现实时同步。
