### ISSUE TITLE
离线安装后无法使用（windows）

### ISSUE THREAD

**Issue by yudiya** [Kenshin/simpread#287]
离线安装后无法使用
系统：windows 10  chrome版本：65.0.3325.181
提示：该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的

**Comment by yudiya** [comment]
![snipaste_2018-04-12_16-47-32](https://user-images.githubusercontent.com/24709058/38666352-3e3141a6-3e71-11e8-8676-f09ccfde1134.png)
如图所示：无法开启

**Comment by Kenshin** [comment]
你好，请使用 [第三种](https://github.com/Kenshin/simpread/wiki/faq#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85) 方式安装，即可解决~

**Comment by yudiya** [comment]
Session expired!
Your session has been expired. Please try again.

**Comment by yudiya** [comment]
用第三种方法。输入地址后提示如下：
## Session expired!
Your session has been expired. Please try again.

**Comment by Kenshin** [comment]
比较奇怪，明天看一下，直接给你下载链接。

**Comment by yudiya** [comment]
谢谢~
我已经想办法翻墙安装好了
请问可以接入有道云笔记吗

**Comment by Kenshin** [comment]
离线文件以后会准备好，而非目前的方式，因为 Chrome 已经不让安装任何非 Webstore 的扩展了，给你造成的困扰，抱歉。

有道暂时不支持，因为它没有公开的 API ，之前申请过，但一直没回复…
