### ISSUE TITLE
导出到 notion 时遇到 <script> 失败

### ISSUE THREAD

**Issue by yeuleh** [Kenshin/simpread#2871]
网页原文在：
https://mp.weixin.qq.com/s?__biz=Mzg4MTYwMzY1Mw==&mid=2247496108&idx=1&sn=969584561f3dd2c814777259a3457563&source=41#wechat_redirect

在大概文章 50% 处，有这样一段话：
> JavaScript 可能阻塞解析。如果 HTML 解析器碰到 <script> 标签，会暂停

导出到 notion 之后，文章会中断在上面 “如果 HTML 解析器碰到”。
推测是因为后面有个 “<script>“ 造成了导出失败

**Comment by yeuleh** [comment]
导出到 notion 之后是如下样子

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2578819/133972079-4d868e1f-2c90-4e54-a041-71624a280da4.png">

**Comment by Kenshin** [comment]
嗨，你可以导出 Markdown 到本地，如果无误的话，就不是简悦的问题。

至于为什么会出现此问题，细节可以看这里 https://github.com/Kenshin/simpread/discussions/1773

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
