### ISSUE TITLE
样式参数数字不显示

### ISSUE THREAD

**Issue by yjmtgb** [Kenshin/simpread#2873]
MacOS 系统中 样式 数字不显示, Chrome 和 Edge 都了,都不显示

Chrome 版本 93.0.4577.82
Edge 版本 92.0.902.84
简悦版本都是2.2.0.520

 <img width="548" alt="截屏2021-09-21 下午3 14 16" src="https://user-images.githubusercontent.com/87890599/134127785-8a389ab1-e6c9-4d58-a7d8-980141acaf35.png">

**Comment by yjmtgb** [comment]
> 请问是任意 URL 还是某一个？如果是后者的话，请告知。

三个浏览器都显示空白, 不仅仅是任意 URL 的阅读模式, 在三个浏览器的设置界面中也都是空白,

系统是 MacOS Big Sur 11.6

**Comment by yjmtgb** [comment]
> > 请问是任意 URL 还是某一个？如果是后者的话，请告知。
> 
> 三个浏览器都显示空白，不仅仅是任意 URL 的阅读模式，在三个浏览器的设置界面中也都是空白，
> 
> 系统是 MacOS Big Sur 11.6

使用的第三个浏览器是 Canary,
Canary 和 Edge 是普通账户, Chrome是高级账户

**Comment by Kenshin** [comment]
emm

你在**隐身模式下仅使用简悦的方式** ，在试试，看看是不是其它扩展干扰造成的。

**Comment by yjmtgb** [comment]
Edge 隐身模式下测试
<img width="670" alt="截屏2021-09-22 下午12 58 01" src="https://user-images.githubusercontent.com/87890599/134285839-7226f14b-37ae-4e4d-972b-a1b28d1981e8.png">

**Comment by Kenshin** [comment]
emmm 真是太奇怪了...


你可以试试 → 进入阅读模式 → 右键  → 检查 → 看看 DeveTools 里面是否有报错？

然后，导出配置文件，然后重置（或重新安装简悦）看看如何？

**Comment by yjmtgb** [comment]
没有发现有用的报错信息, 
chrome 重新安装过一次,依然不显示,
Edge 和 Canary 都是第一次安装, 也不显示

**Comment by Kenshin** [comment]
emmm 你在 Github 上面能找到我的邮箱地址，然后把出现问题的配置文件发给我。（注意：脱敏不需要包含授权码

**Comment by lurenjiamen** [comment]
把字体册中乱码字体删除一下, 就能正常显示.

**Comment by yjmtgb** [comment]
麻烦你啦, 帮忙把 issues 关闭吧

lurenjiamen ***@***.***> 于2021年9月27日周一 上午11:54写道：

**Comment by Kenshin** [comment]
@lurenjiamen 

嗨，谢谢提示。（竟然是这个原因...  😂 

@yjmtgb 

我关闭这个 Issues 了。
