### ISSUE TITLE
稍后读阅读模式

### ISSUE THREAD

**Issue by Cacalous** [Kenshin/simpread#2876]
-->您好，我的问题是稍后读内文章的阅读模式。我尝试了手动框选模式，比较好地进入了阅读模式，于是将其加入稍后读中。但当我在稍后读中打开这个页面的阅读模式时，显示了乱码（众多内含问号的菱形）。我尝试了开关”增强解析模式“，且简悦已经为最新版，但没有奏效，效果如下图。
![1632321552(1)](https://user-images.githubusercontent.com/90713804/134366724-926743ba-cf3a-4569-919a-8a896573045d.jpg)

网站为https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193707.htm#_ftnref2

**Comment by Kenshin** [comment]
嗨，这个页面需要使用同步助手 + 内置解析的方案，在稍后读中需要开启此选项 

![image](https://user-images.githubusercontent.com/81074/134440975-8843fb9e-4099-48de-97fa-12d95367d8d9.png)
