### ISSUE TITLE
感觉原网站的排版比较省空间及合理

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#2877]
感觉原网站的排版比较省空间及合理：
原網站：
![IMG_0016](https://user-images.githubusercontent.com/87223257/134375716-9bfca0aa-bb22-4985-b1e6-74444347ed92.jpeg)
打開簡悅的閱讀模式後：
![IMG_0017](https://user-images.githubusercontent.com/87223257/134376036-0cbbf0d1-28ea-4ddb-aa32-048bd3d433ec.jpeg)

![IMG_0018](https://user-images.githubusercontent.com/87223257/134376088-1a882460-662d-4d58-9593-de35d212afa9.jpeg)
原綢站網址：https://leadingmrk.com/the-most-complete-guide-to-notion/

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

并不是每个页面都需要使用阅读模式，在这种情况下，你可以使用聚焦模式，也支持导出功能的。

PS：这个网站做的不错。
