### ISSUE TITLE
我的简悦无法设置快捷键进入阅读模式。

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2879]
我的简悦无法设置快捷键进入阅读模式。

我用其他插件测试了同一个快捷键，是可用的，也就是说，这大概不是浏览器的问题，而是简悦的问题

环境：edge最新正式版，使用alt+S作为快捷键失效

_Originally posted by @Mirrorgo in https://github.com/Kenshin/simpread/discussions/1506#discussioncomment-1373769_

**Comment by Kenshin** [comment]
@Mirrorgo

嗨，你之前在 https://github.com/Kenshin/simpread/discussions/1506#discussioncomment-1373769 的内容转移到了 Issues 并且删除了原位置的内容。

***

> 我用其他插件测试了同一个快捷键，是可用的，也就是说，这大概不是浏览器的问题，而是简悦的问题

这个测试并不能说明是（或不是）简悦的问题。

***

你需要在**隐身模式下仅使用简悦的方式** 测试看看快捷键是否可用。

另外，请截图给我看下你的快捷键设置。

**Comment by Leftzhf** [comment]
我也是edge，状况一样，进入阅读模式的快捷键用不了，而在Chrome里却没问题

**Comment by Kenshin** [comment]
@Leftzhf 

emmm 理论上不应该的。
EDGE 隐身模式下也有问题吗？

**Comment by Leftzhf** [comment]
> @Leftzhf
> 
> emmm 理论上不应该的。 EDGE 隐身模式下也有问题吗？

没问题了，应该是Edge的问题，重启了下就好了

**Comment by Kenshin** [comment]
@Leftzhf 

okay 没问题就好。

另外，我顺道关闭这个「年久没人理」 的 Issues 了~
