### ISSUE TITLE
特定页面只显示了部分内容

### ISSUE THREAD

**Issue by rollandlau** [Kenshin/simpread#2888]
- 操作系统 macos big sur

- 浏览器版本 Chrome 93.0.4577.82 (正式版本) (x86_64)

- 简悦版本 2.2.0.520

- 发生问题的地址 <https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-19450424.htm>

**请描述你的问题**

开启阅读模式后，只显示了最后的引用部分的内容，而未能显示全部内容

![image](https://user-images.githubusercontent.com/1802446/134757904-817e8cad-f4c3-439c-a99c-1abadacb247b.png)

**Comment by Kenshin** [comment]
嗨，请使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)

另外，也可以使用 https://simpread.pro/help 获取更多简悦的帮助说明

![image](https://user-images.githubusercontent.com/81074/134758007-7d0e4c8e-4529-4c8c-b013-b8f4efc4a3fd.png)
