### ISSUE TITLE
【适配】请求适配煎蛋网

### ISSUE THREAD

**Issue by Ctipsy** [Kenshin/simpread#289]
猎奇资讯类网站，
测试URL：http://jandan.net/2018/04/14/renewable-energy-2.html

**Comment by Kenshin** [comment]
你好，煎蛋已经适配了~
如果你说的是 【轻阅版】的话，确实有问题，煎蛋不允许修改它的 html 所以看到的就是一片白色...
除了煎蛋外，好奇心日报也存在这个问题。

如果你说的是【简悦】的话，请确保你的适配列表为最新，选项 → 关于，看看是否为 249个，或者选择 选项 → 共通 → 手动同步适配列表~

**Comment by Kenshin** [comment]
补充下，简悦会定时同步适配列表，而你发生的问题恰恰处于 `未到时` 而已。
