### ISSUE TITLE
threedots.tech 文章中阅读模式下，有些行的内容不见了。

### ISSUE THREAD

**Issue by leyle** [Kenshin/simpread#2890]
**请说明发生问题的环境**

- 操作系统 **MacOS**

- 浏览器版本 **Vivaldi	4.2.2406.48 (Stable channel) (x86_64)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://threedots.tech/post/common-anti-patterns-in-go-web-applications/

**请描述你的问题**

进入阅读模式后，文章中的 
` Full source: github.com/ThreeDotsLabs/go-web-app-antipatterns/01-coupling/01-tightly-coupled/internal/user.go`
不见了。

**截图**

![image](https://user-images.githubusercontent.com/1290013/134798909-05c4f543-93eb-4b6c-96b8-ce4e7b2be55d.png)

![image](https://user-images.githubusercontent.com/1290013/134798945-5c5a0534-e3ee-476d-a977-71181f75aada.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

如果是未适配的页面有可能存在类似的问题，解决方案：使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)

![image](https://user-images.githubusercontent.com/81074/134800935-036435a5-d05f-4b3a-8496-d3d4f046b8c5.png)

**Comment by leyle** [comment]
> 嗨，谢谢反馈。
> 
> 如果是未适配的页面有可能存在类似的问题，解决方案：使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)
> 
> ![image](https://user-images.githubusercontent.com/81074/134800935-036435a5-d05f-4b3a-8496-d3d4f046b8c5.png)

谢谢，问题解决了。

**Comment by Kenshin** [comment]
搞定就好。😄
