### ISSUE TITLE
无法获得兑换码

### ISSUE THREAD

**Issue by xiaoxiaodie** [Kenshin/simpread#2895]
https://simpread.pro/code
兑换码申请平台没有输入框，浏览器使用Chrome,edge,ie都刷新不出来

**Comment by xiaoxiaodie** [comment]
> 可能跟你的网络环境有关…
> 请告诉我你所在地与网络运营商。
> 
> 另外，能否试试「开全局」如果不行的话告诉我你的邮件地位，我明天单独给你发。

网络环境是成都电信
邮箱724537912@qq.com

**Comment by Kenshin** [comment]
果然是成都电信…

我看到你的邮件了，明天给你。

**Comment by Kenshin** [comment]
嗨，邮件已发，我关闭这个 Issues 了。
