### ISSUE TITLE
请问 “稍候读”保存在本地硬盘什么位置？

### ISSUE THREAD

**Issue by bush911** [Kenshin/simpread#2896]
如题，谢谢
虽然是高级用户，也用了几个月了，目前只用了简单的阅读、标注，google drive导出等基本的功能。
最近换电脑了，账户配置已经迁移成功，就是不知道“稍候读”在哪里保存着，想手动拷贝过去。

谢谢作者，谢谢大家

**Comment by Kenshin** [comment]
嗨，关于你的问题可以看这个文档 [配置文件](http://ksria.com/simpread/docs/#/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

以下是这个链接有关你问题的截图

![image](https://user-images.githubusercontent.com/81074/135013244-b5622d60-de07-4126-9ff5-6e54cced9ac9.png)

***

所以，你需要从旧电脑导出配置文件（即包含了稍后读数据），然后在新电脑上导入即可。
