### ISSUE TITLE
每次打开浏览器就会自动跳出简悦的选项页

### ISSUE THREAD

**Issue by ironkule** [Kenshin/simpread#2897]
如题，什么时候打开浏览器，都会跳出简悦的选项页

**Comment by ZI2104** [comment]
我同样遇到自动跳出选项页的问题
使用Edge浏览器
在一台电脑上出现
同样使用最新版本Edge114.0.1823.43(64位)并登录微软账号同步过Edge选项的另一台电脑没问题
尝试过：
重新安装简悦无效（从Edge商店）
全部关闭其他插件无效
退出重新登陆Microsoft账号无效
没有设置自动清除cookie

**Comment by Kenshin** [comment]
@ZI2104 

这个现象跟是否登录 Microsoft 账户是没关系的，问题还是出在（出问题）的那个浏览器的设置上。
