### ISSUE TITLE
无法开启自动同步，提示未知错误

### ISSUE THREAD

**Issue by SeyeeL** [Kenshin/simpread#2898]
![image](https://user-images.githubusercontent.com/71479570/135016987-7fee18ad-0683-4785-b600-d0fdc463f528.png)
桌面同步助手已打开，已授权验证

**Comment by SeyeeL** [comment]
我的这个文件夹里面有两个config文件，一个是公司的win，另一个生成的config文件命名里有macXXXX，是家里的mac报错，回去自查

**Comment by Kenshin** [comment]
只要存在 `simpread_config.json` 就行。
另外一个 可能是因为冲突造成的备份。

等你的继续反馈。

**Comment by Kenshin** [comment]
截图中的 URL 不一致无所谓。

重新安装同步助手再试试。

**Comment by SeyeeL** [comment]
mac的同步助手好像就是一个app文件，也不在应用程序下载里面，没有什么重新安装之说，我重新再tg里下了新的，从360极速换到谷歌浏览器，还是不行。自查截图见tg

**Comment by SeyeeL** [comment]
同步助手里的文件夹重新选了一次就好啦，谢谢～

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
