### ISSUE TITLE
notion.so页面上开启阅读模式后无法滚动，只有首屏内容可以看

### ISSUE THREAD

**Issue by SeyeeL** [Kenshin/simpread#2899]
rt

**Comment by Kenshin** [comment]
嗨，给个 URL~

**Comment by SeyeeL** [comment]
https://www.notion.so/3a8c5d77b5be42c58719d174bfbfa935

**Comment by Kenshin** [comment]
我刚才测试了这个页面，没有你说的问题。

- 可以根据 https://github.com/Kenshin/simpread/discussions/2106 提示方式更新适配规则。

看看能否解决。

***

不过，确实有另外一个问题：因为 Notion 的结构导致我只适配了大部分正常的 block，细节看上面这个链接。这个页面给出的部分内容没有在适配规则里面。

**Comment by SeyeeL** [comment]
更新后已解决，谢谢

**Comment by Kenshin** [comment]
okay 那我关闭这个 issues 了。
