### ISSUE TITLE
支持 github issues

### ISSUE THREAD

**Issue by vagusX** [Kenshin/simpread#29]
可否支持 github issue的阅读 因为不少人的博客都是在github issue里面

**Comment by Kenshin** [comment]
可以的，下个版本即将提供。
由于 Github issues 的解析与当前版本不一致，所以不能通过远程更新的方式。

**Comment by vagusX** [comment]
@Kenshin 如果能支持 github 中的 readme.md 就更好啦 😁

**Comment by Kenshin** [comment]
没问题的，下个版本（下周发布）会加入。

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`
新增加了 对 `issues` 与 `REAME.md` 的适配。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
