### ISSUE TITLE
百度经验添加至白名单后无法开启自动切换阅读模式

### ISSUE THREAD

**Issue by tzc0120** [Kenshin/simpread#2904]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by tzc0120** [comment]
自己查到原因了，高级设置--延迟加载列表--删除百度就可以了，但为什么其他的可以打开就会自动加载，而百度经验会先打开原始页面，然后才会加载为阅读模式？

**Comment by Kenshin** [comment]
> 自己查到原因了，高级设置--延迟加载列表--删除百度就可以了，但为什么其他的可以打开就会自动加载，而百度经验会先打开原始页面，然后才会加载为阅读模式？

嗨，因为加入到延迟加载才有这种「现象」。

恭喜自己搞定。 👍

**Comment by Kenshin** [comment]
没问题的话，我关闭这个页面了。
