### ISSUE TITLE
简悦2.2个人使用感受与建议

### ISSUE THREAD

**Issue by Jason-Study** [Kenshin/simpread#2913]
我使用简悦2.2一周后。这是我的一些使用感受与建议。

感觉同步助手这个外部应用没啥用，许多操作也比较繁杂。
首先，导出不到指定位置，还是导出到浏览器默认下载路径。
然后，同步助手里打开稍后读的快捷键是全局的，与系统及其他程序快捷键冲突，清空快捷键都没用。
最后，同步助手和坚果云需要一直挂着，才能实现自动同步，虽然没毛病，但我内心感觉是抗拒的，因为会占较多电脑资源，然后就弃用自动同步了。

此外，web里简悦的提示信息如果可以选择显示几秒自动消失就好了，不然提示信息出现频率较高，手动关闭也比较烦。

- 操作系统  Windows10 

- 浏览器版本 Chrome 88.0.4324.96

- 简悦版本 2.2.0

**Comment by Kenshin** [comment]
谢谢反馈。简单的回复下。

> 问题一

当然不会出现这个问题，如果出现了是你配置的问题。留意以下几个选项

![image](https://user-images.githubusercontent.com/81074/135788741-6a90b510-00db-434a-b703-f14e537c6f84.png)

> 问题二

你可以取消全局快捷键。（取消后需要保存以及重启）

> 问题三

同步助手是 Desktop 版的前身。

***

>如果不用同步助手的话，也可以正常的使用简悦的 95% 以上的功能，如果你只是用阅读模式的话，是不需要使用同步助手的。

***

至于配置的问题，虽然配置项较多，但有教程，全程下来不会超过5分钟（不算同步助手的下载）

另外，我非常欣赏下面的这个评价。

![image](https://user-images.githubusercontent.com/81074/135788689-91cb2ab0-2cf0-4106-b295-00025461b0a4.png)

**Comment by Jason-Study** [comment]
好的，感谢您的回复与帮助！

**Comment by Kenshin** [comment]
嗨，没关系的。

有疑问没事情的，我跟很多开发者不一样的地方在于：你只要问，我肯定会回复。（仅限官方渠道，也就是这里）

截止到目前

- 共有 2.6K 的 Issues，我全部都一一回复了，甚至某些还不止回复一次。
- Webstore 上面也有 1.6K 的评价，我也都一一回谢了。

PS：无论多牛掰的产品也都有人不理解和不喜欢，但只要是肯跟我沟通，我都欢迎。
