### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by aixindao** [Kenshin/simpread#2915]
发生问题的地址: <https://docs.qq.com/doc/DYXFudUJqTWhGdlFU>

希望能够提取腾讯文档的内容。

**Comment by Kenshin** [comment]
嗨，谢谢反馈，可以考虑。

能否多给我一些 URL 用作参考。

**Comment by MindYoga** [comment]
> 嗨，谢谢反馈，可以考虑。
> 
> 能否多给我一些 URL 用作参考。

https://docs.qq.com/doc/p/6cebf9b2ccaf26bdb2128485c344ad62888b570c?dver=2.1.27215548
https://docs.qq.com/doc/DYWdXVXRVY3dtdm5u

https://docs.qq.com/doc/p/dd8d21ccebfa988a3bc422a57fe16e7fbdb99ba0?dver=2.1.27215548
https://docs.qq.com/doc/DYVB5WEhQYkRPTGdH

https://docs.qq.com/doc/p/5c5b889168d9a05746bc83266e2c7f50278c6b59?dver=2.1.27215548
https://docs.qq.com/doc/DYWtCeGdCVVNyVmJm

https://docs.qq.com/doc/p/8233b64d15e2f78d8b26c9c0b741d2667fe978ab?dver=2.1.27215548
https://docs.qq.com/doc/DYU1OS2tzeVNjbGlC

https://docs.qq.com/doc/p/fb5562077def0005109d4cd3db3ae9dfb13017a3?dver=2.1.27215548
https://docs.qq.com/doc/DYUtObEVMWENlQ05L

**Comment by Kenshin** [comment]
嗨，谢谢提供 URL，我需要看下腾讯文档的一些说明，是否有适配的风险。

PS：飞书文档就明确指出了「不建议适配等说明」

**Comment by kankan235** [comment]
请问，腾讯文档未来无法适配吗？

**Comment by Kenshin** [comment]
@kankan235 

嗨，**不是不能适配**，而是 **不可以被适配** 😂

我关闭这个 Issues 了~
