### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by MaxwellDing** [Kenshin/simpread#2925]
发生问题的地址: <https://blog.csdn.net/dbzhang800/article/details/6376422?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-2.channel_param

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
