### ISSUE TITLE
掘金的图片导入到语雀无法显示的说明（因使用了 awebp 图片格式）

### ISSUE THREAD

**Issue by ZuulAndRibbon** [Kenshin/simpread#2928]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 *Windows*

- 浏览器版本 **Chrome  94.0.4606.71**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://juejin.cn/post/6844903551446040590

**请描述你的问题**

> 剪裁文章到语雀，文章里面的图片丢失无法显示，代码会多四个字“复制代码”

**截图**

> 
![image](https://user-images.githubusercontent.com/21259910/136659519-4d64dfda-9b42-48f7-bc9d-1f7a05613e64.png)

**Comment by Kenshin** [comment]
抱歉，忘记这个 Issues了。

我刚确认了下，**因为掘金使用的图片格式为 `awebp` 在语雀中不支持这种图片格式造成的。**

例如 https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/dfaec98a1a5b4bf9ada67487c5f7f57c~tplv-k3u1fbpfcp-watermark.awebp

PS：确实很少见到这种图片格式...

这个 Issues 先留着吧，跟简悦无关，等什么时候语雀支持了就可以了。

**Comment by JhonwillBao** [comment]
印象笔记也不行，应该是同样的问题

**Comment by Kenshin** [comment]
@JhonwillBao 

你是说印象笔记无法导入吗？如果是的话，这是另外的问题，原因看这里 https://github.com/Kenshin/simpread/issues/302

**Comment by itscj1014** [comment]
可惜现在还是没有解决

**Comment by luckykellan** [comment]
掘金导出PDF 图片也无法显示，现在有什么解决办法吗？

**Comment by Kenshin** [comment]
@luckykellan 

给个 URL 看下。

**Comment by luckykellan** [comment]
https://juejin.cn/post/7256971663996338213
导出效果如下：
![image](https://github.com/Kenshin/simpread/assets/109934256/d9a3cb58-2150-4a1f-bfe0-a58508a52bf8)

正在尝试使用图床插件解决，有一个与该issue无关的疑问，我使用自动化增加插件，当文章加入稍后读自动导出pdf，在这个过程中怎么配置可以实现「加入稍后读->图片上传图床->使用图床中的图片导出pdf」？

**Comment by Kenshin** [comment]
@luckykellan 

> 加入稍后读->图片上传图床->使用图床中的图片导出pd

不使用快捷键 `d d` 加入稍后读而使用图床的快捷键 `p p` 先将图片转换图床，转换完毕后，再按照下图所示设置。

<img width="869" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/87b8ed96-246c-4cc2-b203-5fb55d4eed0e">

PS：PDF 的问题我稍晚再回复你。

**Comment by Kenshin** [comment]
@luckykellan

确实 PDF 在导出图片时遇到了问题，只能使用你提到的方式「中转」下。

**Comment by luckykellan** [comment]
感谢回复。请问图床的快捷键是否和pdf增强插件的快捷键冲突了？

**Comment by luckykellan** [comment]
补充：无法使用图床插件解决该问题，原因是PicGo无法识别掘金的awebp格式，上传会报错：No mime type found for file。

**Comment by Kenshin** [comment]
@luckykellan 

唉！掘金啊…无语… 😂

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案，解决了你提到的这个问题。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论

**Comment by Kenshin** [comment]
你可以通过图床插件将掘金的图片转换为自己的图床 e.g. Cloudinary 然后在保存到语雀中，就能解决这个问题了~
