### ISSUE TITLE
能否增设“不显示图片”或“仅显示文字”的选项

### ISSUE THREAD

**Issue by BYCL** [Kenshin/simpread#293]
一般来说，版面不保留图片比较“方便”阅读。

请考虑增设这个功能，谢谢。

**Comment by Kenshin** [comment]
emmm... 可以考虑，感谢建议~

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [无图版](https://simpread.ksria.cn/plugins/details/0vnL8VbCgs) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
