### ISSUE TITLE
edge浏览器无法使用简悦的标记功能，也打不开稍后读

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2930]
<div type='discussions-op-text'>

<sup>Originally posted by **jsample-git** October 10, 2021</sup>
谷歌浏览器可以正常使用，edge浏览器最近开始出现无法正常使用的问题：识别网页进入阅读模式后无法标记，打开稍后读是空白网页。
谷歌浏览器是普通账户，edge是高级账户，所以是否是高级账户的问题？
![谷歌浏览器阅读模式](https://user-images.githubusercontent.com/76514193/136680517-6e4f1dcc-e9e6-405b-89d5-f7806398e7d1.jpg)
图1 普通账户·谷歌浏览器阅读模式（正常）

![edge浏览器阅读模式](https://user-images.githubusercontent.com/76514193/136680524-a8f332be-d48d-4b3f-a95e-5011d534100b.jpg)
图2 高级账户·edge浏览器阅读模式（异常）

![谷歌浏览器稍后读](https://user-images.githubusercontent.com/76514193/136680522-b782c521-b9ea-4d93-85ca-75091fbd4c64.jpg)
图3 普通账户·谷歌浏览器稍后读（正常）

![edge浏览器稍后读](https://user-images.githubusercontent.com/76514193/136680525-b17ab882-a78f-43ae-b447-1e28494cf30b.jpg)
图4 高级账户·edge浏览器稍后读（异常）

</div>

**Comment by Kenshin** [comment]
@jsample-git

嗨，请不要在 https://github.com/Kenshin/simpread/discussions 提问，我帮你转移到了这里，并删除了之前的内容。

***

> 这个问题跟是否与高级账户无关的。

稍后读空白应该是稍后读数据有个错误的值造成的，你可以根据 https://github.com/Kenshin/simpread/discussions/2727 提供的方式修改。（我会专门出个功能来自动完成这个方案，但目前只能手动方案）

如果无法手动解决，请在 https://github.com/Kenshin 找到我的联系邮箱，给我一封包含 Issues id 的邮件并附上配置文件。

**Comment by jsample-git** [comment]
> @jsample吉特
> 
> ，马[德西 https://github.com/Kenshin/simpread/discussions，](https://github.com/Kenshin/simpread/discussions)
> 
> > 这个问题跟是否与高级账户无关的。
> 
> 稍后读空白应该是稍后读数据有个错误的值造成的，你可以根据#2727提供的方式修改。（我会专门出个功能来自动完成这个方案，但目前只能手动方案）
> 
> https://github.com/Kenshin

请问，修改完之后还要进一步操作吗（保存再“从本地导入配置文件”）？

**Comment by jsample-git** [comment]
> > 请问，修改完之后还要进一步操作吗（保存再“从本地导入配置文件”）？
> 
> 是的

修改后导入失败，提示“上传失败，配置文件解析失败，请重新确认”。

我的操作步骤是：
简悦“导出配置文件到本地”>>
选中导出的文件《simpread-config-2021年10月10日 17_51_35.json》>>
右键选择"opendlg">>
用记事本打开>>
删掉唯一的“null”>>
保存>>
简悦“从本地导入配置文件”>>
提示“上传失败，配置文件解析失败，请重新确认”
