### ISSUE TITLE
导出  全文+标注   为pdf ，却只有标注

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#2932]
![image](https://user-images.githubusercontent.com/38575961/136697375-cbfddbee-fd78-4a08-90cf-d287073bdbd4.png)

![image](https://user-images.githubusercontent.com/38575961/136697366-2f9d51de-47b0-4611-8b90-3044925a2bcd.png)

![image](https://user-images.githubusercontent.com/38575961/136697390-6129aaa4-4096-40e9-9e83-4422bd52b7c7.png)

**Comment by Kenshin** [comment]
选项页 → 服务 → 定制化导出，需要配置 [自定义标题](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%af%bc%e5%87%ba)。
