### ISSUE TITLE
将标注功能的侧栏收起后，无法再展开

### ISSUE THREAD

**Issue by alexinea** [Kenshin/simpread#2938]
点击 <kbd>A</kbd> <kbd>A</kbd> 后进入阅读模式，开启标注功能，进行标注。然后点击侧栏收起标注，就再也不能把侧栏展开了。

环境：Windows 11 + Microsoft Edge 96.0.1032.0 (官方内部版本) dev (64 位)
简悦：2.2.0

一图胜千言：

![image](https://user-images.githubusercontent.com/980129/137056270-fb5b73d6-379f-4db5-9625-42e4ddc2f46a.png)

**Comment by alexinea** [comment]
分辨率 3000 * 2000，缩放 175%
刷新也不行，甚至关闭重开浏览器也不行。

**Comment by Kenshin** [comment]
看下稍后读是否可以正常打开？如果能的话，请按照下面的方式解决：

1. 右键 → 检查
2. 根据下图的提示修改即可

![image](https://user-images.githubusercontent.com/81074/137061001-e4184803-d4f6-4234-8115-d0ea09447f34.png)


***

可能是你缩放的造成的「遮挡」无法点击。

**Comment by alexinea** [comment]
我刚才在阅读模式下添加到【稍后阅读】。从【稍后阅读】里面点开这篇文章，丢失了所有标注。然后返回原页面，重新开始标注，现在可以收回和展开侧栏了。

我标注的东西都是汉字，不包含代码。

所以可以排除是缩放、代码污染，不排除是汉字间包含了不可见的符号。原因依旧不明……

**Comment by alexinea** [comment]
非常感谢，因为原因暂时不能找到，所以我先 close 掉 issue。回头如果找到原因，我再 reopen 并反馈相关信息 ：）
