### ISSUE TITLE
建议对适配的网站，增加https支持

### ISSUE THREAD

**Issue by zz-zigzag** [Kenshin/simpread#294]
网站在慢慢升级到https，如cnblog，在访问https://www.cnblogs.com 的时候，不显示适配。

**Comment by Kenshin** [comment]
感谢反馈！
你可以通过手动同步适配列表，选项 → 共通 → 手动同步适配列表。
完成后，请确保 选项 → 关于 → 适配网址为 249个 即可解决。

另外，在 `1.1.1` 版本中，将会忽略 https 与 http 的区别~

**Comment by Kenshin** [comment]
我需要重启开启这个 issues 等真正解决这个问题后，才会 Close 它，以便通知到你。 😀

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 关闭。

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
