### ISSUE TITLE
更改主题色不生效

### ISSUE THREAD

**Issue by cpp-jiang** [Kenshin/simpread#2941]
![image](https://user-images.githubusercontent.com/25993096/137261225-8f0b734c-14c4-4aa5-849a-a3d10692e1d7.png)
主题改了保存,刷新页面不会生效, 很早改过一次黑色模式,然后一直是这个

**Comment by Kenshin** [comment]
嗨，请问是否使用了同步助手？

你也可以这样试试

1. 设置暗色模式

![image](https://user-images.githubusercontent.com/81074/137265573-1c117bef-a5bb-4906-b80c-895ede8dde2c.png)

2. 不启用系统的暗色模式

3. 随便进入个页面 e.g. https://sspai.com/post/67074 然后进入阅读模式，在修改主题。（修改后会提示刷新）

看看能否生效？

**Comment by Kenshin** [comment]
> 我这里一样的问题，取消跟随系统设置可解决

谢谢提示，这两天有点时间，明天把这个方案记录下来。

👏

**Comment by Kenshin** [comment]
嗨，我已经把这个方案记录到了 https://github.com/Kenshin/simpread/discussions/2992

如果没有问题的话，我关闭这个 Issues  了。
