### ISSUE TITLE
点击目录标题没有跳转

### ISSUE THREAD

**Issue by WarmingWorld** [Kenshin/simpread#2944]
- 操作系统 
  win64

- 浏览器版本 
  chrome 94.0.4606.81（正式版本） （64 位）

- 简悦版本 
  2.2.0.520

- 发生问题的地址 
  https://sspai.com/post/64749

- 问题 
  点击左侧的目录不跳转到指定的标题位置

**Comment by Kenshin** [comment]
嗨，我刚才测试了下，是可以跳转的。

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭这个 issues  了。
