### ISSUE TITLE
导出失败，此功能为实验性功能，如有需求请提 Issues

### ISSUE THREAD

**Issue by Ghoooooostie** [Kenshin/simpread#2945]
- 操作系统 **e.g.  Windows MacOS**
 Windows 10
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
94.0.4606.54
- 简悦版本 **2.0.0**
2.2.0
- 发生问题的地址 <请填写你的地址l>
https://thinkwon.blog.csdn.net/article/details/101645224
**请描述你的问题**
前几天看csdn的文章 还可以保存为md pdf 刚刚点击保存 就出现下面截图中的错误 实验性功能啥的 简悦为高级账户
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/45316289/137627371-9bc4d489-a66c-4fd6-9d01-549b25ff48a9.png)
![image](https://user-images.githubusercontent.com/45316289/137627390-0eb02369-2915-4418-b4e8-c161be60f75b.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
> 今天换了一下备份的文件夹名字 不知道是不是这个问题

请问，你是使用了同步助手的增强导出？看看文件夹路径是否正确？
另外，多试试几篇不同的文章，如：少数派的，看看是否也有这个问题？

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭这个 Issues 了。
