### ISSUE TITLE
网页代码无法在阅读模式下加载

### ISSUE THREAD

**Issue by yitingdj** [Kenshin/simpread#2946]
问题链接：http://www.wowotech.net/process_management/447.html
问题截图：
![image](https://user-images.githubusercontent.com/18674166/137706249-98807590-1722-4fb7-a3b0-6a38e4e73c25.png)
![image](https://user-images.githubusercontent.com/18674166/137706315-15001ee2-46f0-47a1-a388-9f85fdae942a.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
