### ISSUE TITLE
定制导出到flomo的模板，原来的教程好像失效了

### ISSUE THREAD

**Issue by blazar-x** [Kenshin/simpread#2949]
按照教程配置webhook和定制markdown模板后，并没有效果

**Comment by LPofei** [comment]
好的

**Comment by Kenshin** [comment]
嗨，我以及我找的其他简悦用户测试是没问题的，请详细描述测试过程。

**Comment by NewEarthTask** [comment]
我感觉应该是他在服务里面绑定的时候flomo的时候没有删除https://flomoapp.com/iwh/*******/前面部分，而是直接粘贴进去的。我一开始也出现了同样问题，重新绑定后，仔细看了一下绑定的时候是iwh/*******/，压缩的时候是https://flomoapp.com/iwh/*******/，然后就好了。

**Comment by Kenshin** [comment]
@NewEarthTask 

嗨，谢谢提示，估计是这个问题。

今天是圣诞 🎄 🎅 应该多休息。 😁  💪

**Comment by NewEarthTask** [comment]
😀🎶

Kenshin Wang ***@***.***> 于2021年12月25日周六 14:57写道：

**Comment by blazar-x** [comment]
谢谢，但是不是这个问题，服务地址没问题，我直接能导入到flomo的。就是定制模板怎么试都不行

**Comment by Kenshin** [comment]
> 谢谢，但是不是这个问题，服务地址没问题，我直接能导入到flomo的。就是定制模板怎么试都不行

试试确保「网络畅通」

PS：马上 2022 了，不出意外，这是 2021 倒数第二个回复 Issues 

祝你新年快乐。

**Comment by NewEarthTask** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        额...只能两出大招了，你换台电脑，反正一个账号能绑定三个，如果你换台电脑按照自己的流程可以，那说明可能电脑问题，反之则是操作流程有问题....，如过换台电脑不可以的话，是不是复制粘贴搞错了，单条的粘到了多条批注的模板等等，webhook看成了markdeep.....如果还不行.....额....我就无计可施了...额
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年12月31日 23:04，Kenshin ***@***.***> 写道： 






谢谢，但是不是这个问题，服务地址没问题，我直接能导入到flomo的。就是定制模板怎么试都不行



试试确保「网络畅通」

PS：马上 2022 了，不出意外，这是 2021 倒数第二个回复 Issues

祝你新年快乐。
