### ISSUE TITLE
导入到 Obsidian插件 可以跳转到Obsidian界面 但是无内容保存 插件重装、重置同步助手无数次都无法解决

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#2960]
导入到 Obsidian插件 可以跳转到Obsidian界面 但是无内容保存 插件重装、重置同步助手无数次都无法解决

_Originally posted by @messchow in https://github.com/Kenshin/simpread/discussions/2866#discussioncomment-1518449_

**Comment by Kenshin** [comment]
@messchow

关于这个问题我应该找到原因了，解决方案 [请看这里](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2435327)

**Comment by Kenshin** [comment]
嗨

[导入到 Obsidian 升级到 1.1.0](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)，主要解决了 Windows 系统因字符限制无法使用的问题。 🎉 

## 增加如下功能：

-  `Add` 新的 Metadata
    - `{{url}}`
    - `{{timestamp}}`
    - `{{note}}`

- `Add` [Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)

## Local REST API 导入方案视频

https://user-images.githubusercontent.com/81074/163329889-8269dbba-144b-45c2-a706-2ed716049c4a.mp4

*** 

我关闭此 Issues 了~

**Comment by Kenshin** [comment]
嗨，各位。

导入到 Obsidian 升级到 1.2.0 ，增加了 **重磅功能**：可以不通过同步助手，将标注自动导入到 Obsidian。

## 一站式教程

https://simpread.zhubai.love/posts/2128393555537739776

## 视频

https://user-images.githubusercontent.com/81074/164135947-0552fc11-1b92-4804-a616-df64ae43770a.mp4

**Comment by 15d23** [comment]
https://blog.csdn.net/iracer/article/details/51339377
这个网址无法使用，因为网站标题有特殊符号，请问这个怎么解决?

**Comment by Kenshin** [comment]
> https://blog.csdn.net/iracer/article/details/51339377 这个网址无法使用，因为网站标题有特殊符号，请问这个怎么解决?

安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 如果安装不好使的话，使用 https://simpread.ksria.cn/plugins/details/UEzvAXNSe5 安装

**Comment by 15d23** [comment]
您好，您的邮件己收到，我将在阅读邮件后，尽快给您回复。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by 15d23** [comment]
您好，您的邮件己收到，我将在阅读邮件后，尽快给您回复。

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by 15d23** [comment]
您好，您的邮件己收到，我将在阅读邮件后，尽快给您回复。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
