### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by Laifang** [Kenshin/simpread#2979]
发生问题的地址: <https://m.okjike.com/originalPosts/615faac6b0f47f001056ac1e?s=eyJ1IjoiNTVlZWRhMDU4Mjk2YjQwZTAwZDAyYjBmIiwiZCI6MX0%3D

即刻网站

**Comment by Kenshin** [comment]
嗨，这个站已经适配了，安装地址 https://simpread.ksria.cn/sites/details/ucpaKpybxj

所以，我关闭这个 Issues 了。
