### ISSUE TITLE
导入Obsidian插件无法使用

### ISSUE THREAD

**Issue by FourteenD** [Kenshin/simpread#2980]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows**

- 浏览器版本 **e.g. edge 95.0.1020.30**

- 简悦版本 **2.2.0**

- 发生问题的地址 所有

**请描述你的问题**

> 导入Obsidian插件无法使用,可以显示插件触发器，Advanced Obsidian URI插件已安装

**截图**

> ![202110](https://user-images.githubusercontent.com/53899166/138983424-e49a629f-8d6d-4124-ae10-f25f07e3df9a.gif)

**Comment by Kenshin** [comment]
@1wingedangel

嗨，谢谢帮忙调查，我已经将此问题记录到了 https://github.com/Kenshin/simpread/discussions/2902

@FourteenD 

如果你是 Obsidian 的深度使用者，并且也使用简悦的同步助手，也可以使用 https://github.com/Kenshin/simpread/discussions/2889 提供的方法

**Comment by KYBIN-9** [comment]
> > 经过一些简单的测试，我发现在Windows环境下， Chrome, Vivaldi 和 Edge 无法打开 URL长度超过2046个字符的地址，所以当 Obsidian-advanced-uri 生成的URL超过了2046个字符之后，就无法执行。
> > 重现方式：
> > 
> > * 打开一个页面
> > * 只选择100个字左右的文本（由于页面标题也很长，所以2046个字符基本上只能包含100个字符的正文），右键后 `将选中的内容生成阅读模式`
> > * 导入到 Obsidian，看看能不能运行成功
> > 
> > 对于这个问题的解决方法（目前能想到的）：
> > 
> > 1. 用外部软件来添加笔记。比如用简悦复制Markdown之后，用 Quicker + obsidian-advanced-uri 来生成笔记。用 Quicker 的 `打开网址` 命令亲测可超过2046个字符的限制。
> > 2. 可能这是仅Windows系统才有的限制，换系统环境……
> > 3. Firefox好像没有URL长度的限制，但是你要先生成URL后复制，再粘贴到Firefox才行……那就不如第一条了。
> 
> @1wingedangel 我尝试用提供的方法测了一下确实时这样

请教一下，您说的复制md后，用“Quicker + obsidian-advanced-uri ”来生成笔记，具体怎么操作？quicker动作怎么设置？

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Obsidian 升级到 1.1.0](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)，主要解决了 Windows 系统因字符限制无法使用的问题。 🎉 

## 增加如下功能：

-  `Add` 新的 Metadata
    - `{{url}}`
    - `{{timestamp}}`
    - `{{note}}`

- `Add` [Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)

## Local REST API 导入方案视频

https://user-images.githubusercontent.com/81074/163329889-8269dbba-144b-45c2-a706-2ed716049c4a.mp4

***

我关闭这个 Issues 了，如有问题，随时在这里回复。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.2.0 ，增加了 **重磅功能**：可以不通过同步助手，将标注自动导入到 Obsidian。

## 一站式教程

https://simpread.zhubai.love/posts/2128393555537739776

## 视频

https://user-images.githubusercontent.com/81074/164135947-0552fc11-1b92-4804-a616-df64ae43770a.mp4

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
