### ISSUE TITLE
阅读模式只有标题和描述，http://dysti.dongying.gov.cn/art/2021/10/27/art_38017_10283652.html

### ISSUE THREAD

**Issue by libixi123** [Kenshin/simpread#2988]

**Comment by Kenshin** [comment]
嗨，
你可以使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE?id=%e4%bd%bf%e7%94%a8) 来临时解决。
