### ISSUE TITLE
【TOC】在CSDN滚动页面非常卡

### ISSUE THREAD

**Issue by AlmostFamous1992** [Kenshin/simpread#299]
例如：https://blog.csdn.net/wishfly/article/details/44211515
上下滚动时完全没有平滑滚动的效果，几乎是几行几行地跳动，感觉很卡，别的网站打开阅读模式暂时没发现这个问题
经测试发现是与这个扩展冲突：https://chrome.google.com/webstore/detail/custom-css/ahmppdlkialjlchhgigblbfjailjeneh?utm_source=chrome-app-launcher-info-dialog

**Comment by Kenshin** [comment]
感谢反馈，不过应该是由 TOC 导致的，应该不是你说的这个扩展。
我会在下个版本中解决这个问题。

**Comment by rosuH** [comment]
我这里也遇到了。但没有安装上述插件。
所以可能是 TOC 造成的。不知道能否临时取消 TOC 功能？

**Comment by Zeroto521** [comment]
我这也遇到了同样的问题，只不过当文章很长时，才会卡顿。
¯\\_(ツ)_/¯

**Comment by Kenshin** [comment]
感谢各位的反馈，1.1.1 将会修复这个问题。  😀 
PS：1.1.1 将会在下周发布。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，
具体原因是 TOC（有锚点的功能）与当前页面的功能重复，暂时没有好的解决方案，所以在这个页面无法显示 TOC。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
