### ISSUE TITLE
请问简阅有没有进入一个站点就自动打开阅读模式的功能呢

### ISSUE THREAD

**Issue by shenghansen** [Kenshin/simpread#2999]
请问简阅有没有进入一个站点就自动打开阅读模式的功能呢，如题，最近被csdn的广告烦的要命，想要一进入就立刻开启阅读模式，请问有这个功能吗，有考虑支持这个功能吗？

**Comment by Kenshin** [comment]
当然可以了，选项页 → 高级设定 → 阅读模式，里面有很多选项，其中一个就是可以自动阅读模式。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/140001543-dcd86e6d-b9f5-409a-8698-12fa9c04a762.png)
