### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by dev4mobile** [Kenshin/simpread#30]
与cvim 插件快捷键冲突
![image](https://user-images.githubusercontent.com/6851386/27507821-3c6ebf80-590a-11e7-92e0-acb0cdafbc4f.png)

**Comment by Kenshin** [comment]
是的，之所以没有宣传支持快捷键就是如此。
阅读模式与聚焦模式的快捷键可以自定义，下个版本会增加 esc 退出方式。

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`
解决办法：新增 `ESC` 退出方式。
更新日志 请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
