### ISSUE TITLE
“黑鸾”主题下，选中文字后，黄色高亮遮盖住文字（vox.com）

### ISSUE THREAD

**Issue by hi-yiyang** [Kenshin/simpread#3006]
（简悦版本 2.0.0）
（网站 vox.com）

在黑色主题下，选中文字之后，黄色高亮让文字根本无法看清。另一个暗色主题稍好一些，但也比较难辨认。

![image](https://user-images.githubusercontent.com/51028862/140252148-6fecdec9-90b5-4206-a72e-ba5cae0b0a18.png)

标注的颜色没有这种问题。

![image](https://user-images.githubusercontent.com/51028862/140252641-d013a2aa-e000-470b-abaf-08489ea9fe11.png)

**Comment by Kenshin** [comment]
嗨，这是这个站的样式设置造成的，

> 请将下面的代码

```
sr-read ::selection {
  color: initial!important;
  background-color: #BED6FD!important;
}
```

> 加入到下图位置，即可解决

![image](https://user-images.githubusercontent.com/81074/140277186-78d3c78f-34ec-496b-afea-02e6678acc2f.png)

![image](https://user-images.githubusercontent.com/81074/140277255-341de953-f1c8-4a0d-b7e7-630b8053b058.png)
