### ISSUE TITLE
保存到evernote国际版失败

### ISSUE THREAD

**Issue by vindevil** [Kenshin/simpread#301]
url：
http://t.cj.sina.com.cn/articles/view/6419477121/17ea17281001006f1h?sudaref=www.google.com&display=0&retcode=0

**Comment by Kenshin** [comment]
感谢反馈，这部分的原因请参考 [这里](https://github.com/Kenshin/simpread/wiki/%E6%8E%88%E6%9D%83%E6%9C%8D%E5%8A%A1#%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E4%BF%9D%E5%AD%98%E5%A4%B1%E8%B4%A5)

另外，我在考虑，当发生这种情况时，只保存文本，不知道如何？

**Comment by wystanchen** [comment]
单独保存文本也还是有一定用处，但最好在保存后提示中添加说明。

最好当然是能够联系evernote，看看evernote有没有可能提供协助?

另外希望要么发展成一个社区，要么发展为收费版，现在看到好的有希望的服务，真的怕它死掉。。。

**Comment by Kenshin** [comment]
- 保存为文本的想法，我会单独开个 issues 跟有这方面需求的用户讨论下。

- 联系 evernote 一直无果...   😂 

- 因为 `1.1.0` 版已经上线了一个社区，但可能是宣传以及配套太弱的缘故，不是很活跃，准备 `1.1.1` 或 `1.1.2` 加强这部分的流程和体验。

- 关于简悦的未来，可以看下图（我在 [少数派](https://sspai.com/post/44153) 上的撰文）
![image](https://user-images.githubusercontent.com/81074/39338851-10adad86-49f8-11e8-91a4-49fc1c50ee85.png)

如果觉得简悦不错的话，可以 [请我喝杯星巴克](http://ojec5ddd5.bkt.clouddn.com/zhifu_m2.png)~

PS：如果可以的话，可以加入 [TG 群](https://t.me/joinchat/F6-OaUO4dEoeoSm0q1WUrw)，简悦的一些新信息我会先发布在这里。
