### ISSUE TITLE
开启『简悦』插件，页面打开正常显示约1秒后，自动『白屏』

### ISSUE THREAD

**Issue by mtuwei** [Kenshin/simpread#3012]
- 操作系统：Win10

- 浏览器版本： Edge 95.0.1020.40；Chrome 95.0.4638.69

- 简悦版本 **2.2.0**

- 发生问题的地址：http://www.stats.gov.cn/tjsj/zxfb/202012/t20201231_1811924.html

开启『简悦』插件，此页面打开正常显示一秒后，自动白屏。关闭『简悦』插件，此页面打开后可以正常显示。事实上，不止这一个网址，页面『http://www.stats.gov.cn/tjsj/zxfb/』中的任一页面均存在此问题。

开启『简悦』插件：
![image](https://user-images.githubusercontent.com/32591958/140477664-baaada12-3853-48a5-a26c-8ddb0d06de03.png)

关闭『简悦』插件：
![image](https://user-images.githubusercontent.com/32591958/140477859-7758d6b4-b137-493a-892a-541b598d654e.png)

**Comment by Kenshin** [comment]
emmm

在这个页面无法使用简悦，请加黑名单，操作如下

![image](https://user-images.githubusercontent.com/81074/140479714-730d65f6-f682-408c-871f-30977c9246ad.png)

> 加入 `stats.gov.cn` 到下图所示

![image](https://user-images.githubusercontent.com/81074/140479780-35c88c1f-9a88-41b1-a76b-e4b167b0f6e0.png)

> 保存后，刷新页面后就可以了。

**Comment by mtuwei** [comment]
> emmm
> 
> 在这个页面无法使用简悦，请加黑名单，操作如下
> 
> ![image](https://user-images.githubusercontent.com/81074/140479714-730d65f6-f682-408c-871f-30977c9246ad.png)
> 
> > 加入 `stats.gov.cn` 到下图所示
> 
> ![image](https://user-images.githubusercontent.com/81074/140479780-35c88c1f-9a88-41b1-a76b-e4b167b0f6e0.png)
> 
> > 保存后，刷新页面后就可以了。

暂时已加入黑名单。问题是，我正是想在这个网页使用『简悦』🤣，便于后续操作。请问什么时候能解决这个适配的BUG呢？

**Comment by Kenshin** [comment]
这不是 Bug 而是这个页面的限制造成的。

**Comment by mtuwei** [comment]
> 这不是 Bug 而是这个页面的限制造成的。

所以未来也无法以『阅读模式』打开这个页面，除非网站取消限制，是这样？

**Comment by Kenshin** [comment]
> 所以未来也无法以『阅读模式』打开这个页面，除非网站取消限制，是这样？

可以的，将加入到延迟加载

![image](https://user-images.githubusercontent.com/81074/140595802-39f8f9bb-1e43-482c-8e4f-747644aca2a2.png)

但是需要使用简悦的同步助手功能，并开启下面的选项

![image](https://user-images.githubusercontent.com/81074/140595789-acee2393-e88c-4e6d-80f2-b67fc61c3af7.png)

在稍后读中可以查看和使用

![image](https://user-images.githubusercontent.com/81074/140595791-bfb0ab01-445e-4d59-82f4-b78a9e1467bb.png)

**Comment by mtuwei** [comment]
> > 所以未来也无法以『阅读模式』打开这个页面，除非网站取消限制，是这样？
> 
> 可以的，将加入到延迟加载
> 
> ![image](https://user-images.githubusercontent.com/81074/140595802-39f8f9bb-1e43-482c-8e4f-747644aca2a2.png)
> 
> 但是需要使用简悦的同步助手功能，并开启下面的选项
> 
> ![image](https://user-images.githubusercontent.com/81074/140595789-acee2393-e88c-4e6d-80f2-b67fc61c3af7.png)
> 
> 在稍后读中可以查看和使用
> 
> ![image](https://user-images.githubusercontent.com/81074/140595791-bfb0ab01-445e-4d59-82f4-b78a9e1467bb.png)

明白了，一直在用同步助手的，谢谢！

**Comment by Kenshin** [comment]
没事，搞定就好，我关闭这个 Issues 了。

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏

**Comment by mtuwei** [comment]
> 没事，搞定就好，我关闭这个 Issues 了。
> 
> PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏 💪 😏

已经『五星好评 + 评价』，也有推荐给身边的朋友😉
