### ISSUE TITLE
无法恢复高级账户

### ISSUE THREAD

**Issue by derechoneo** [Kenshin/simpread#3014]
重新绑定配置文件后, 提示后台错误
<img width="586" alt="2021-11-03_083516" src="https://user-images.githubusercontent.com/35890564/140513735-e76ba573-4c0a-46c7-a592-d854569e3dda.png">

**Comment by Kenshin** [comment]
因为授权有很多方案，最好详细描述下。
例如：是在新设备上导入配置文件的方式吗？

如果确认配置文件内含的 UID 没问题的话，重启浏览器，再试试导入，看看能否解决？

**Comment by hiryanl** [comment]
重新安装简悦浏览器插件后, 通过导入配置文件的方式无法授权.
________________________________

**Comment by Kenshin** [comment]
@hiryanl 

你导入的是什么配置文件？请把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3014
