### ISSUE TITLE
notion保存的时候能不能指定notion中的目录?

### ISSUE THREAD

**Issue by goulin** [Kenshin/simpread#3018]
不能指定notion的保存目录

**Comment by Kenshin** [comment]
嗨，当然可以了，你在哪里授权的，就在哪里设置，可以看[教程](http://ksria.com/simpread/docs/#/Notion)

PS：如果仅能指定唯一的 Page，会提示说明原因。

![image](https://user-images.githubusercontent.com/81074/140599834-9d031137-4c64-4b97-b022-b9e6e18879b3.png)

**Comment by goulin** [comment]
看到了,谢谢

**Comment by Kenshin** [comment]
没事的，搞定就好～

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)。
