### ISSUE TITLE
我已经购买高级账号，有些功能还是不可以用

### ISSUE THREAD

**Issue by owen-debug** [Kenshin/simpread#3027]
- 简悦版本 **2.2.0**
![image](https://user-images.githubusercontent.com/55222274/140875679-88b2e105-2294-4290-a0f3-ade6a67b6fef.png)
而且我这里也没有用用户授权登录的选项
![image](https://user-images.githubusercontent.com/55222274/140875787-7f4d4b46-074c-429d-9e88-1a58d3eeffaa.png)
稍后读也显示不是高级账号，请开发者帮忙看看

**Comment by Kenshin** [comment]
嗨，确保你的 UID 是高级账户 UID，如果是的话，看下面的步骤

1. 重启浏览器
2. 打开选项页 → 右上角 → 仅授权当前设备（教程看 https://github.com/Kenshin/simpread/discussions/1576

**Comment by owen-debug** [comment]
谢谢，已解决，我关了...
