### ISSUE TITLE
在有代码段的文章中，简悦不会识别

### ISSUE THREAD

**Issue by owen-debug** [Kenshin/simpread#3028]
![image](https://user-images.githubusercontent.com/55222274/140883341-a0c3f776-7031-4195-9a08-8af20e044ebf.png)
![image](https://user-images.githubusercontent.com/55222274/140883374-18f9fa7e-0ca3-41db-83b5-01c9c903767e.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
