### ISSUE TITLE
代码块遮挡顶部进度条

### ISSUE THREAD

**Issue by kid1412621** [Kenshin/simpread#303]
网站：CSDN
情况如图
![1](https://user-images.githubusercontent.com/26278054/39434920-956770a8-4ccc-11e8-974b-a567579b0b67.png)
![2](https://user-images.githubusercontent.com/26278054/39434923-9677b610-4ccc-11e8-8896-e937913b0527.png)

**Comment by Kenshin** [comment]
谢谢反馈，下个版本解决。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
