### ISSUE TITLE
建议有更简单的选项页方案

### ISSUE THREAD

**Issue by veryqun** [Kenshin/simpread#3031]
但是我只想使用一个易读和标记的插件而已，但是！简悦的设置就像是我们答辩的时候把所有的内容恨不得全搬到用户/评委面前。看到那冗余漫长的设置和没有尽头的帮助文件，我要崩溃了。为什么 现在连一个简单的软件都这么大的学习成本啊。真心觉得简悦应该做做减法，说实话我是一个效率软件控，但是简悦的学习成本还是惊到我了。这么庞大学习成本和软件本身产生的价值很难说有很大优势。
开发者当然，不会对简悦的逻辑丝毫混乱，但是我现在看到那天书一样的设置界面和帮助文档人都要麻了。
我知道这是个好产品，但是希望能做到用户友好一点。
希望简悦粉不要喷我，如果一个小软件有这么大的学习成本我认为是不正常的。

**Comment by veryqun** [comment]
ps. 我说的减法不是功能性缩减，而是设置，配置的逻辑的减法。

**Comment by Kenshin** [comment]
嗨，谢谢你的反馈，建议照单全收，并简单回复下。

首先，从功能上简悦并不是你想的是一个简单的软件。
其次，从功能的体量上说它也并不简单。

如果你用过 MarginNote 的话，可以认为简悦就是 Web 版的 MarginNote，所以你觉得 MarginNote 是个小软件吗？

如果你觉得它是个稍后读，它可以做到很多双链笔记做到的功能，如：双向链接，知识图谱，甚至更复杂的布局，这些都不是一个稍后读拥有的功能。

如果觉得是价格造成的错觉（确实也有用过反馈过，价格改为 1xx 就好了），只能说，等随着功能的完善，自然会涨价。

***

> 关于简化

当然会考虑初级用户的使用体验，请订阅 https://simpread.pro/subscribe 如果有这方面的内容我会推送到各个频道中。

> 关于学习成本

如果你想用阅读模式，然后偶尔标注下，保存到稍后读或者导出到你喜欢的生产力工具，这些内容都不需要配置，甚至这里面提到的功能，也不需要高级账户，开箱即用。

（如果你是高级账户的话，保存好你的配置文件，然后重置或重新安装简悦，什么都不做，看看能否实现我说的功能？完全可以。

你看到的这些所谓「成本」只是用来给更原意折腾的用户玩的。

> 关于减法

选项页的选项优化正在考虑中，但优先级不是很高。

***

PS：为了方便检索，我把你的标题修改了。
