### ISSUE TITLE
使用时的一些疑问

### ISSUE THREAD

**Issue by clancygo** [Kenshin/simpread#3032]
1. dropbox 授权登录的时候提示这个，不明白这个密码指的是什么密码

![image](https://user-images.githubusercontent.com/51086824/140907595-4bc7afc3-a803-4a3d-aa01-5bd24a815acf.png)

2. 进入开放平台后只能看 token （测试通过），其他的功能一开（如设置short密码）就会提示如下信息

![image](https://user-images.githubusercontent.com/51086824/140907768-61d49a82-9f6e-4630-b134-ed047a04a75b.png)

3. 阅读的时候背景是黑的，导出到本地的 html 背景是白色的，很多字都看不清

![image](https://user-images.githubusercontent.com/51086824/140908083-17ada0bc-54b3-40a1-91ab-9eae388817e3.png)

**Comment by Kenshin** [comment]
嗨，你应该是推上的朋友吧

> 第一个问题

不应该发生这个问题，很奇怪，感觉是你的配置文件出现问题导致的，我用过 Dropbox 并没有出现你说的问题。（也没有其他用户反馈过类似问题

你可以这样做（**在本地备份好你的配置文件**），然后重置你的配置文件

![image](https://user-images.githubusercontent.com/81074/140908470-c916c7b6-ae49-4146-8dfb-4a4482b41ed0.png)

重置后，选项页 → 右上角 → [重新授权当前设备](https://github.com/Kenshin/simpread/discussions/1576) → 授权为成为高级账户后 → 重新对 Dropbox 授权，授权后再试试，看能否解决。

> 第二个问题

应该跟第一个问题类似，你可以在**隐身模式下登录开放平台**，试试是否存在这个情况？

> 第三个问题

简悦会读取本地 HTML，但是如果这个 HTML 是通过简悦导出的，就会出现这样的情况，此问题无需解决，用没有安装简悦的浏览器打开这个 HTML 就可以了。

**Comment by Kenshin** [comment]
补充：

如果第一个问题仍无法解决的话，请把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3032

**Comment by clancygo** [comment]
> 补充：
> 
> 如果第一个问题仍无法解决的话，请把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3032

确实没解决，已经发送了

**Comment by Kenshin** [comment]
好，明天确认下。

**Comment by Kenshin** [comment]
我看到你的配置文件了，第一个和第二个是一个问题（暂时不用理会第一个问题）

> 我使用了你提供的配置文件，然后导出到 Dropbox 导出失败，说明你的 Dropbox 授权有问题，这就是第一个问题。

***

你可以这样测试：（因为我看你使用了同步助手）

1. 取消 Dropbox 的授权
2. 找到 `simpread_config.json`
3. 用文本编辑器打开，并搜索 `"secret"` 看看里面的 `"access_token"` 是不是是空值。
4. 如果是的话，重新授权 Dropbox
5. 授权完毕后，测试是否可以正常导出到 Dropbox 中？（随便打开一个 [网址](https://sspai.com/post/67074) 然后按上图所示导出。
6. 如果导出成功，选项页 → 账户 → 授权登录，使用 Dropbox 进行授权。
7. 然后在登录 [开放平台](https://simpread.pro/developer)

***

### 备注

通常不需要上述这些步骤，因为遇到了错误，未免重复错误，才有上述验证，否则只需要：

1. 授权 Dropbox
2. 授权登录

即可。

**Comment by clancygo** [comment]
> 我看到你的配置文件了，第一个和第二个是一个问题（暂时不用理会第一个问题）
> 
> > 我使用了你提供的配置文件，然后导出到 Dropbox 导出失败，说明你的 Dropbox 授权有问题，这就是第一个问题。
> 
> ![image](https://user-images.githubusercontent.com/81074/141043569-1f4438b3-4f7f-41ee-b6cb-3c2a5efe5986.png)
> 
> 你可以这样测试：（因为我看你使用了同步助手）
> 
> 1. 取消 Dropbox 的授权
> 2. 找到 `simpread_config.json`
> 3. 用文本编辑器打开，并搜索 `"secret"` 看看里面的 `"access_token"` 是不是是空值。
> 4. 如果是的话，重新授权 Dropbox
> 5. 授权完毕后，测试是否可以正常导出到 Dropbox 中？（随便打开一个 [网址](https://sspai.com/post/67074) 然后按上图所示导出。
> 6. 如果导出成功，选项页 → 账户 → 授权登录，使用 Dropbox 进行授权。
> 7. 然后在登录 [开放平台](https://simpread.pro/developer)
> 
> ### 备注
> 通常不需要上述这些步骤，因为遇到了错误，未免重复错误，才有上述验证，否则只需要：
> 
> 1. 授权 Dropbox
> 2. 授权登录
> 
> 即可。

![image](https://user-images.githubusercontent.com/51086824/141054208-bb049d14-e2a1-4068-81da-3b7ba13a76e4.png)

可以成功导出，但是授权登录时依然提示密码过长，开放平台也是老样子，脑壳疼。

**Comment by Kenshin** [comment]
> 可以成功导出，但是授权登录时依然提示密码过长，开放平台也是老样子，脑壳疼。

emmm 你是什么时候注册的 Dropbox，这个问题是因为你的 Dropbox 授权位数太长造成的，Dropbox token 位数应该不会这么长...

如果不是常用 Dropbox 的话，请选用坚果云（目前仅有你有此问题，无其他用户反馈。

**Comment by clancygo** [comment]
> > 可以成功导出，但是授权登录时依然提示密码过长，开放平台也是老样子，脑壳疼。
> 
> emmm 你是什么时候注册的 Dropbox，这个问题是因为你的 Dropbox 授权位数太长造成的，Dropbox token 位数应该不会这么长...
> 
> 如果不是常用 Dropbox 的话，请选用坚果云（目前仅有你有此问题，无其他用户反馈。

dropbox授权位数如何查看 可以改吗？我dropbox是主力

**Comment by clancygo** [comment]
> > > 可以成功导出，但是授权登录时依然提示密码过长，开放平台也是老样子，脑壳疼。
> > 
> > 
> > emmm 你是什么时候注册的 Dropbox，这个问题是因为你的 Dropbox 授权位数太长造成的，Dropbox token 位数应该不会这么长...
> > 如果不是常用 Dropbox 的话，请选用坚果云（目前仅有你有此问题，无其他用户反馈。
> 
> dropbox授权位数如何查看 可以改吗？我dropbox是主力

刚才因为授权次数过多，链接被dropbox限制了 将就用得了 感谢作者耐心回复

**Comment by Kenshin** [comment]
> 刚才因为授权次数过多，链接被dropbox限制了 将就用得了 感谢作者耐心回复

没事的，位数过多的问题我已经记录了。不过，改用坚果云后不知道是否配置完成？

***

不过，确实非常建议使用坚果云：

1. 免费账户有1个月的历史记录。
2. 仅保存小文件的话，速度足够快。
3. 支持 Webdav 大部分应用均可接入。

简悦虽然也支持 Dropbox 但因为网络环境复杂，所以在使用 API 时，尤其是生成快照时会较慢。

**Comment by xingyigua** [comment]
![image](https://user-images.githubusercontent.com/17724302/142573676-b9a52e1d-20cf-4bf0-89c1-d9ca163f8fcc.png)
同样遇到这个问题，按上述步骤操作之后仍然提示

**Comment by xingyigua** [comment]
> ![image](https://user-images.githubusercontent.com/17724302/142573676-b9a52e1d-20cf-4bf0-89c1-d9ca163f8fcc.png) 同样遇到这个问题，按上述步骤操作之后仍然提示

token 长度 139

**Comment by Kenshin** [comment]
@xingyigua 

嗨，收到，Dropbox 近期对 Token 做了一些改变造成了这个情况，我正在调查。

如果你对 token 为 `sl` 则是这个问题导致，我会把这个情况公开发到简悦的各种渠道。

请订阅简悦的官方渠道 https://simpread.pro/subscribe 到时候我会在这里和官方渠道通知你。

**Comment by clancygo** [comment]
> > 刚才因为授权次数过多，链接被dropbox限制了 将就用得了 感谢作者耐心回复
> 
> 没事的，位数过多的问题我已经记录了。不过，改用坚果云后不知道是否配置完成？
> 
> 不过，确实非常建议使用坚果云：
> 
> 1. 免费账户有1个月的历史记录。
> 2. 仅保存小文件的话，速度足够快。
> 3. 支持 Webdav 大部分应用均可接入。
> 
> 简悦虽然也支持 Dropbox 但因为网络环境复杂，所以在使用 API 时，尤其是生成快照时会较慢。

根据最新的解决方案，dropbox已经可以授权了，但是授权后，使用dropbox第三方登录时，新跳出的网页会闪退导致无法登录，同时，开放平台也是老样子

**Comment by Kenshin** [comment]
漏掉了这个 issues，你提到的问题已经解决了。

解决方案请看这里 https://github.com/Kenshin/simpread/discussions/3171

***

还要，看来我在 https://github.com/Kenshin/simpread/issues/3032#issuecomment-973791473 告诉你让你订阅简悦通知渠道的事情，也没有订阅...

所以，如果你经常使用简悦的话，请务必订阅简悦的官方渠道 https://simpread.pro/subscribe

**Comment by clancygo** [comment]
> 漏掉了这个 issues，你提到的问题已经解决了。
> 
> 解决方案请看这里 #3171
> 
> 还要，看来我在 [#3032 (comment)](https://github.com/Kenshin/simpread/issues/3032#issuecomment-973791473) 告诉你让你订阅简悦通知渠道的事情，也没有订阅...
> 
> 所以，如果你经常使用简悦的话，请务必订阅简悦的官方渠道 https://simpread.pro/subscribe

订阅了telegram，偶尔去瞥一眼😂

**Comment by Kenshin** [comment]
😂 

解决后回来吼一声~

**Comment by clancygo** [comment]
> 😂
> 
> 解决后回来吼一声~

搞不了，配置文件里面有大量的稍后读信息，而且全部塞在一行，复制到教程里的网站后卡的不行，而且文本也没啥区别，如果跳过这一步也可以直接替换token，但是问题依旧

**Comment by Kenshin** [comment]
@clancygo 

> 配置文件里面有大量的稍后读信息，而且全部塞在一行

如果卡的不行，直接搜索 `secret`  然后找到后面的内容并替换就行了。

![image](https://user-images.githubusercontent.com/81074/145531620-1fc4a278-03a7-4635-b367-3d2538aaacff.png)

**Comment by clancygo** [comment]
> 

换过了，授权可以，第三方登录授权也显示已绑定，但是实际没法用dropbox登录，开放平台依然歇菜
![image](https://user-images.githubusercontent.com/51086824/145541939-d5a8afa5-085b-4a19-b399-d1915d89f90d.png)

**Comment by Kenshin** [comment]
当然可以了，否则我发这个教程干什么...

把你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3032

**Comment by clancygo** [comment]
> Issues ID：3032

已发送

**Comment by Kenshin** [comment]
收到，确认后给你回复。

**Comment by Kenshin** [comment]
@clancygo 

嗨，我看了你的 UID 对应的设置是没问题。

> 没法用dropbox登录

如果是「在新设备上登录简悦账户」的话，有更简单的方式：手动导入你在 Dropbox 的 `simpread_config.json` 即可自动登录并授权。

**Comment by clancygo** [comment]
> @clancygo
> 
> 嗨，我看了你的 UID 对应的设置是没问题。
> 
> > 没法用dropbox登录
> 
> 如果是「在新设备上登录简悦账户」的话，有更简单的方式：手动导入你在 Dropbox 的 `simpread_config.json` 即可自动登录并授权。

搞定了，通过UID+license 登录解决了开放平台的问题

**Comment by Kenshin** [comment]
哈哈，搞定就好。

太不容易了~  😂  竟然回复了这么多次。

***

哈哈，请「务必」在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，这是对简悦最好的帮助。 （本条信息不是自动发的，都是我自己手动打字出来的。😏

**Comment by clancygo** [comment]
> 



> 哈哈，搞定就好。
> 
> 太不容易了~ 😂 竟然回复了这么多次。
> 
> 哈哈，请「务必」在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，这是对简悦最好的帮助。 （本条信息不是自动发的，都是我自己手动打字出来的。😏

不幸的是，我又有问题了，api测试显示504，实际配置时确实无法使用
<img width="432" alt="image" src="https://user-images.githubusercontent.com/51086824/146907007-acfce15a-9a0d-4b9d-a1c4-a19c4585793f.png">

**Comment by Kenshin** [comment]
截图出现的信息，请详细描述操作步骤。
