### ISSUE TITLE
选项页显示乱码

### ISSUE THREAD

**Issue by Jiaming-Zhang** [Kenshin/simpread#3035]
**操作环境**

- 操作系统 ** Windows**

- 浏览器版本 **Chrome 95.0.4638.69**

- 简悦版本 **2.2.0**

**遇到的问题**
之前选项页不乱码，也没进行什么操作，昨晚新打开就乱码了。如下图
小白第一次提问题，购买了高级账户，还在学习中。

<img width="685" alt="Snipaste_2021-11-10_13-02-25" src="https://user-images.githubusercontent.com/53442134/141053346-97d8c163-71c5-4b2c-bd2a-85109c33b4cc.png">

**Comment by Kenshin** [comment]
嗨，重启浏览器就可以了，这个问题在 https://github.com/Kenshin/simpread/discussions/1639 有提到解决方案

PS：新用户的话，建议看看 https://github.com/Kenshin/simpread/discussions 里面的内容，以教程 + 使用场景为主，尤其是教程类的，跟着图文一步步走下来就可以了。

除此之外，也留意下 https://simpread.pro/help 里面的一些链接。

**Comment by Jiaming-Zhang** [comment]
> 嗨，重启浏览器就可以了，这个问题在 #1639 有提到解决方案
> 
> PS：新用户的话，建议看看 https://github.com/Kenshin/simpread/discussions 里面的内容，以教程 + 使用场景为主，尤其是教程类的，跟着图文一步步走下来就可以了。
> 
> 除此之外，也留意下 https://simpread.pro/help 里面的一些链接。

重启ok啦~非常感谢呀！我去好好学习一下！

**Comment by Kenshin** [comment]
搞定就好。 😁
