### ISSUE TITLE
随便测试了几个网页都不能用阅读模式, 还需努力啊

### ISSUE THREAD

**Issue by Germxu** [Kenshin/simpread#304]
和另一个插件-----扩展程序: 阅读模式
对比结果是基本用不了阅读模式, 虽然界面挺好看.......

**Comment by Germxu** [comment]
昨天安装之后因为我看日常的新闻都不支持，今天我测试了一下，百度百家，网易新闻，微信公众平台文章支持良好；凤凰新闻插件显示红色已支持，大部分页面提示页面结构更改而不能使用，[一部分](http://news.ifeng.com/a/20180503/58075680_0.shtml)打开之后右下角[没有退出按钮](http://news.ifeng.com/a/20180503/58074925_0.shtml)．腾讯新闻显示未适配，[话题评论](http://view.news.qq.com)有适配．　[未央网](http://www.weiyangx.com/286581.html)未适配，目前我只看到这么多，相信开发者您做的工作比我多多了，不会没有看到这么多不支持，加油！

**Comment by Kenshin** [comment]
请确保适配站点为最新，`选项页 → 共通 → 同步适配列表`
然后刷新你给出的连接，进入阅读模式，试试看。

> 一部分打开之后右下角没有退出按钮
这个应该是 Bug，下个版本会 Fixed

> 未央网
的确没有适配，适配后，我会通知你。

另外，未适配的页面，可以通过 `临时阅读模式` 解决。
