### ISSUE TITLE
页面里的代码部分丢失

### ISSUE THREAD

**Issue by igilbert** [Kenshin/simpread#3041]
如下页面，渲染时会丢了划线部分的代码
https://www.liaoxuefeng.com/wiki/1252599548343744/1306581182447650  
![image](https://user-images.githubusercontent.com/3793634/141240286-3ebafb70-a5d0-4607-b812-98b37a09df7c.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
