### ISSUE TITLE
建议有更简单使用方案

### ISSUE THREAD

**Issue by gexd79** [Kenshin/simpread#3043]
简悦很好用，而且很便宜，甚至我觉得太便宜了———真心话。

但是，实在太复杂了。授权和同步，都很复杂，且经常出问题。
我使用dropbox登录，使用坚果云进行同步。

就在刚才，我尝试通过dropbox登录，一直不成功。（网络好用，可以登录Google等网站），总是提示授权失败，但不知道为啥失败。通过坚果云登录，提示登录成功但找不到配置文件（这个可以理解，我确定自己之前都是通过dropbox登录的，尝试坚果云只是死马当活马医），后来在坚果云里找到了配置文件，下载到本地才成功登录。成功登录后，我立刻把登录方式由dropbox改成坚果云，这样至少可以减少一个出问题的环节。

稍后读基本没有成功过，坚果云同步文件夹里总会出现两个冲突的json文件，我只是个普通的用户，不是极客，经常被搞到心浮气躁。

总之，太复杂了。我宁愿有一个可以同步所有配置和文件的帐号系统。至于最多支持的设备，定下单价，按照数量收费就是，由用户根据自己需求购买。
ps：其实只要看看关于目前的高级账户有多少问题和解决方案，就知道这套系统有多么复杂了。

**Comment by Kenshin** [comment]
谢谢建议，先照单全收。

接着回复下你的问题

> 我尝试通过dropbox登录，一直不成功。（网络好用，可以登录Google等网站），总是提示授权失败，但不知道为啥失败。

这不是简悦的问题，可能是你的 DNS 有问题，细节看这里 https://github.com/Kenshin/simpread/issues/2996

> 稍后读基本没有成功过，坚果云同步文件夹里总会出现两个冲突的json文件

简悦并不是给极客用的，否则也不需要那么多的教程。

至于你的问题，产生原因很多。简单正如你说，冲突了，就这点来说，任何在线服务都存在这样的问题，只是并不会有真实的冲突文件让你比对。（在线服务出现此问题的现象是：某些新添加的稍后读没有了。）

下个版本会有更好的解决方案。

> 我宁愿有一个可以同步所有配置和文件的帐号系统。

如果你受过印象笔记的迁移问题，就不会这么认为了。

最后，接下来会有针对新手的更简单方案，请订阅简悦的各种渠道 https://simpread.pro/subscribe
