### ISSUE TITLE
使用Assistive Touch插件打印pdf时，Assistive Touch 自己的轮盘会显示在pdf里

### ISSUE THREAD

**Issue by derust** [Kenshin/simpread#3045]
并且分页的时候，最后一句有可能被劈成两半（如图）

![image](https://user-images.githubusercontent.com/64185584/141389143-53edf057-57bc-4d2d-a542-c19dcbc5bcd2.png)

**Comment by Kenshin** [comment]
改，使用 https://github.com/Kenshin/simpread/discussions/2721 这个 PDF 辅助增强插件。

**Comment by derust** [comment]
这个好用，貌似还是有文字中间截断的问题，但能接受

**Comment by Kenshin** [comment]
> 有文字中间截断的问题，但能接受

使用同步助手的 PDF 则没有这个问题，细节可以看 https://github.com/Kenshin/simpread/discussions/2714 的说明。
