### ISSUE TITLE
登录坚果云出现错误

### ISSUE THREAD

**Issue by binjoo** [Kenshin/simpread#3047]
不知道是不是简悦的问题，从chrome换到edge都是这个情况。

![image](https://user-images.githubusercontent.com/219092/141414332-67776b3b-c0db-4f5a-bd59-bab254c345c5.png)

输入错误的坚果云账号密码，会提示账号密码错误，输入正确的，console里面就会出现错误。

搞不懂是哪里出了问题。

**Comment by Kenshin** [comment]
嗨，这个提示跟你说的问题无关，不用理会它。

输入正确后后，右上角会提示的。

**Comment by binjoo** [comment]
我输入的账号和APP密码是正确的，但是右上角只是闪现【正在登陆，请稍等】，然后就消失了。。
如果输入错误的账号和密码，会提示【登录失败】的信息。。

所以，我还是没登录成功。。

**Comment by Kenshin** [comment]
emmm

确定下，是坚果云的帐户和 WebDAV 密码（不是坚果云密码）

另外，是在选项页 → 服务 → 授权服务 → 里面输入的吗？

![image](https://user-images.githubusercontent.com/81074/141433653-627bb74b-39a3-4387-8776-1fc7e7127114.png)

**Comment by binjoo** [comment]
确定是坚果云账户和webDAV密码，这个没错。

但不是在服务中，而是在右上角的登录。
![image](https://user-images.githubusercontent.com/219092/141435098-e90227cc-76c8-4f56-8cd0-cadc6c191338.png)

刚刚试了在服务中绑定，没问题。。

再然后试试登录就没问题了。。

**Comment by binjoo** [comment]
应该是我使用错误，我登陆的地方可能是需要绑定后才能登陆。
不过我没有看到任何提示来告诉我需要绑定。。

**Comment by Kenshin** [comment]
哈哈，搞定就好，下图有提示

![image](https://user-images.githubusercontent.com/81074/141437524-09380cdf-2a8c-432d-ba48-667cf056c9ea.png)

没问题的话，我关闭这个 Issues 了~

**Comment by binjoo** [comment]
看了，没看明白。。😀

谢谢啦。。。

**Comment by Kenshin** [comment]
> 看了，没看明白。。😀
> 
> 谢谢啦。。。

好吧  😂
