### ISSUE TITLE
建议鼠标悬停在图标按钮上时有提示信息

### ISSUE THREAD

**Issue by woncode** [Kenshin/simpread#305]
希望使给所有的图标加当鼠标悬停的提示信息。
进入阅读模式后，鼠标悬停在右下角的“三个点”图标后出现了很多图标，虽然图标都比较形象，但是图标太多，有一些东西还没有接触过，不知道什么意思，鼠标悬停在图标上又没有提示文字，所以只能一个个试错了。

**Comment by Kenshin** [comment]
确实有 tooltip，但有些 Bug，所以某些情况下无法看到…
1.1.1 将会修复这个问题。
你可以看下我的 微博 或 TG 群，有新版的一些视频。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，之前是因为位置错误导致。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
