### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by FLIER001** [Kenshin/simpread#3050]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacM1**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://cn.reuters.com/article/china-official-common-prosperity-1112-idCNKBS2HX0E0?il=0>

**截图**

 
![image](https://user-images.githubusercontent.com/26852784/141454993-9ba33129-5e6e-42ab-94b5-441342c725ce.png)

**Comment by Kenshin** [comment]
嗨，你想说什么？因为没有修改标题，我先关闭这个 Issues 了，有需要请随时重开它。
