### ISSUE TITLE
代码段增强插件在某些网站不正常运行

### ISSUE THREAD

**Issue by teslapatrick** [Kenshin/simpread#3058]
#### 问题：
* 手动框选后，代码增强插件不能正常工作
#### 问题出现页面
* https://leetcode-cn.com/problems/remove-linked-list-elements/solution/203-yi-chu-lian-biao-yuan-su-die-dai-di-eg52b/

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
