### ISSUE TITLE
导出离线markdown文档中图片名称冗长

### ISSUE THREAD

**Issue by PangPangDog** [Kenshin/simpread#3065]
![截图_20213817103815](https://user-images.githubusercontent.com/49577192/142110859-cf1927c3-c923-4c41-91fc-5451a8022265.png)

图片名称长的吓人，希望改进

**Comment by Kenshin** [comment]
哈哈，这是正常的。
离线 Markdown 的图片就是 base 64 格式的，为了就是「离线」。

如果导出 Markdown 就没有这个问题了。

***

如果你对离线的导出感兴趣的话，可以试试

- [Textbundle](http://ksria.com/simpread/docs/#/Textbundle)
- 离线 HTML
- https://github.com/Kenshin/simpread/discussions/2241

**Comment by PangPangDog** [comment]
> 哈哈，这是正常的。 离线 Markdown 的图片就是 base 64 格式的，为了就是「离线」。
> 
> 如果导出 Markdown 就没有这个问题了。
> 
> 如果你对离线的导出感兴趣的话，可以试试
> 
> * [Textbundle](http://ksria.com/simpread/docs/#/Textbundle)
> * 离线 HTML
> * [[Quicker 动作]批量下载 Markdown 中的外链图片并替换成本地离线图片链接（主要应用场景：通过简悦导出 Markdown 到 Obsidian 中） #2241](https://github.com/Kenshin/simpread/discussions/2241)

Textbundle 体验太好了，哈哈，感谢大大

**Comment by Kenshin** [comment]
> Textbundle 体验太好了，哈哈，感谢大大

喜欢就好。

🙏  😏
