### ISSUE TITLE
阅读列表打开出错

### ISSUE THREAD

**Issue by A-PolarBear** [Kenshin/simpread#3066]
按照API官方文档，登录个人中心后，打开阅读列表，显示没有output文件夹。
![screencapture-simpread-pro-bear66-reading-1637131059265](https://user-images.githubusercontent.com/87763549/142148803-a68722ae-b762-44f5-a3e5-6689547e40db.png)

**Comment by Kenshin** [comment]
嗨，因为你给出的信息太少了，我没法判断，建议：

- 先使用 https://github.com/Kenshin/simpread/discussions/3020 测试是否是 API 的问题
- 如果不是的话，确保 `output` 里面有 html 文件才可以预览到。

如果还是不行的话，请将你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3066

**Comment by A-PolarBear** [comment]
请问一下output文件夹在哪里呀👀

**Comment by Kenshin** [comment]
哈哈，你没看教程是怎么摸索到这步的？教程在这里 https://github.com/Kenshin/simpread/discussions/2954 看配置部分

![image](https://user-images.githubusercontent.com/81074/142186385-10f7f027-7add-4b3c-8a07-ee4a8271f4b3.png)

**Comment by A-PolarBear** [comment]
我就是按照这个配置的呀👀
![6C49A439-73F8-4DEF-AB45-CB54F43F7BB9](https://user-images.githubusercontent.com/87763549/142189411-66ebf2ae-363f-490f-887d-a0df9370e85d.png)
移动端的每日回顾就可以打开，但是阅读列表也显示没有output文件夹存在😳

**Comment by Kenshin** [comment]
嗨，截图第二个链接 https://github.com/Kenshin/simpread/discussions/2956

里面有如何配置的说明

![image](https://user-images.githubusercontent.com/81074/142190281-a833c635-8dd6-41e8-8a58-d9d02023c67d.png)

**Comment by A-PolarBear** [comment]
啊非常感谢！！！

**Comment by Kenshin** [comment]
哈哈，没事，搞定就好。
没有问题的话，我关闭这个 Issues 了。

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏
