### ISSUE TITLE
文中有多个代码块嵌入的情况下进入阅读模式代码块位置会发生错位

### ISSUE THREAD

**Issue by HuShiyangchn** [Kenshin/simpread#3069]
右侧为原网页，左侧为阅读模式。如果连续有两个代码块，第二个代码块在阅读模式下会跑到下面去。
![微信图片编辑_20211118112248](https://user-images.githubusercontent.com/55211567/142346305-7630c641-fd20-4ded-beda-3f387c193365.jpg)
![微信截图_20211118112116](https://user-images.githubusercontent.com/55211567/142346313-4df90721-3bdd-4466-b653-f874ccb752a6.png)

问题网页：
http://karpathy.github.io/2021/06/21/blockchain/

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
