### ISSUE TITLE
退出阅读模式重复进入逻辑问题

### ISSUE THREAD

**Issue by quericy** [Kenshin/simpread#307]
微信公众平台任意页面，例如：
https://developers.weixin.qq.com/miniprogram/dev/api/network-request.html

自动自动进入阅读模式，按ESC退出阅读模式
滚动页面后，（由于切换小节导致url中锚点变化）又自动进入阅读模式了

这个逻辑是否可以优化下？对于想临时退出阅读模式的页面，重复进入阅读模式体验不佳

**Comment by Kenshin** [comment]
okay，我确认下~ 下个版本会修复此问题~ 感谢反馈~

**Comment by Kenshin** [comment]
这两天没用电脑，你可以把这个页面加到排除列表，这样就不会自动启动了。

**Comment by Kenshin** [comment]
把 `developers.weixin.qq.com` 加入到 **排除列表** 即可解决。
