### ISSUE TITLE
模式切换问题

### ISSUE THREAD

**Issue by starsight** [Kenshin/simpread#3074]
共通里，点了下模式切换，切成了简洁模式，然后切不回来了

![image](https://user-images.githubusercontent.com/8342806/142443086-31f21ff1-b672-4643-8f3b-a88b538f9cd2.png)

**Comment by Kenshin** [comment]
在左下角

另外，在切换时为简单模式时，会有提示左下角可以切换的。

**Comment by starsight** [comment]
> 在左下角
> 
> 另外，在切换时为简单模式时，会有提示左下角可以切换的。

我把左边的菜单固定住了，因此被隐藏。
谢谢回复，已解决

**Comment by Kenshin** [comment]
哈哈，没事，搞定就好。
