### ISSUE TITLE
进入阅读模式以后不出现右下角控制栏

### ISSUE THREAD

**Issue by HybridRbt** [Kenshin/simpread#3075]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Mac, M1, macOS Monterey 12.0.1**

- 浏览器版本 **Microsoft Edge 版本 95.0.1020.53 (官方内部版本) (arm64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html>

**请描述你的问题**

进入阅读模式以后不出现右下角控制栏。请见截图，这是打开稍后读界面并点击列表中一篇文章以后呈现的界面。在选项中关闭了显示底栏。

**截图**

<img width="1920" alt="截屏2021-11-18 下午12 53 59" src="https://user-images.githubusercontent.com/6162974/142480378-0b7da442-28b4-4bbd-9f17-96ab06e3c862.png">

**Comment by Kenshin** [comment]
嗨，在稍后读的阅读模式中是没有你说的功能的，此阅读模式只是网页阅读模式的一个「子系统」

如果你需要导出的话，上栏就是导出方案。

**Comment by HybridRbt** [comment]
感谢解答！我有此疑问是因为想要设置阅读模式的字体，然后看到有增强英文阅读排版的插件，但我找不到插件说明里的截图里的那些设置界面在哪里。请问这个界面是从哪里调出的呢？或者说这个右下角控制栏是在什么模式下才会出现呢？

Thanks,
Jianfeng

**Comment by Kenshin** [comment]
比如进入 https://sspai.com/post/69972 这个页面，然后点击浏览器右上角简悦的 icon 就能进入阅读模式了

![image](https://user-images.githubusercontent.com/81074/142568329-39edb61f-b700-421e-8f38-1b61d73905df.png)


只有通过 URL 进入的页面才具有你说的这些功能。

**Comment by HybridRbt** [comment]
了解了，原来如此！感谢解答！

Thanks,
Jianfeng

**Comment by Kenshin** [comment]
哈哈，没问题。

我关闭这个 Issues 

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏
