### ISSUE TITLE
有些页面不能全面展示内容（sometimes it can't show all content)

### ISSUE THREAD

**Issue by zhaijiayu12345** [Kenshin/simpread#308]
![](http://p5eoicdyo.bkt.clouddn.com/18-5-8/10021551.jpg)
下面没有滚动轮,导致右面的很多内容不能看到
我看的网页地址 https://www.applysquare.com/topic-en/BJvnjwSFp/

**Comment by Kenshin** [comment]
感谢反馈，这两天没有用电脑，明天我看一下。
请问，你的分辨率是多少？

**Comment by zhaijiayu12345** [comment]
你指的是电脑的分辨率吗？**1920*1080**
我可能在使用**临时阅读模式**的时候，没找到合适的位置选择框框（就是文本的区域），导致文本没有全部显示出来。我又尝试鼠标点击别的区域，发现又能正常阅读了。

这真是一个非常棒的阅读插件，尤其是在看看CSDN博客遇到非常多广告的时候，打开插件，页面一下子就干净了。非常感谢，希望这个插件会变得越来越好，越来越受欢迎！

**Comment by Kenshin** [comment]
临时阅读模式，如果选择不当的话，会有问题。
问你分辨率的问题是因为分辨率也是影响此的原因。
遇到这样的情况，可以用 esc 方式退出。

**Comment by Kenshin** [comment]
谢谢对简悦的支持，近期 1.1.1 版将会发布。😄

**Comment by Kenshin** [comment]
如果没有其它问题的话，我将关闭此 issues ~  😀
