### ISSUE TITLE
聚焦模式无法关闭

### ISSUE THREAD

**Issue by ErronZrz** [Kenshin/simpread#3081]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

- 操作系统 **Win64**

- 浏览器版本 **Microsoft Edge 95.0.1020.53 (64bit)**

- 简悦版本 **2.2.0**

- 发生问题的地址 任何可以打开聚焦模式的地址

**请描述你的问题**

在任何地方，聚焦模式开启后没法关闭，Esc 没有用，也找不到其他关闭的按钮，反而是阅读模式可以用 Esc 轻松关闭。

**Comment by Kenshin** [comment]
请问是每个页面都存在此问题吗？

如果是的话，请把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3081

**Comment by Kenshin** [comment]
emmm

我这边没有问题，估计是跟你其它的扩展冲突了，请在 **隐身模式下仅使用简悦的方式** 。

**Comment by OptimusPrimeme** [comment]
环境基本一样，系统Win11和浏览器均为最新，隐身模式下仅用简悦，依旧无法关闭，也没有控制栏

**Comment by Kenshin** [comment]
@OptimusPrimeme @ErronZrz 

嗨，估计是这个问题造成的 https://github.com/Kenshin/simpread/discussions/3167

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme @ErronZrz
> 
> 嗨，估计是这个问题造成的 #3167

谢谢🌹，解决了

**Comment by Kenshin** [comment]
@OptimusPrimeme 

估计应该是这个问题了，话说，有段时间没看到你 。

没问题的话，我关闭这个 Issues 了。

**Comment by OptimusPrimeme** [comment]
> @OptimusPrimeme
> 
> 估计应该是这个问题了，话说，有段时间没看到你 。
> 
> 没问题的话，我关闭这个 Issues 了。

工作匆忙。另外，最近Edge的沉浸式阅读器好像还可以

**Comment by Kenshin** [comment]
> 工作匆忙。另外，最近Edge的沉浸式阅读器好像还可以

哈哈，它只能解决一部分基础阅读模式的需求。
