### ISSUE TITLE
标注功能，我点击保存没反应，chrome显示javascript 升级浏览器清除缓存依旧没用用

### ISSUE THREAD

**Issue by Skytostop** [Kenshin/simpread#3084]
![image](https://user-images.githubusercontent.com/15011412/142736737-9eb5229d-899c-433a-9787-c214f7fc2672.png)

另外想问下，是只有进入阅读模式后才能标注是不

**Comment by Kenshin** [comment]
emmm

根据上一个 Issues 来说，应该是你的。

***

昨天晚上的 Issues 太晚了，我没法处理。

***

至于你的问题，请问是在稍后读？还是阅读模式下标注的？还有，建议给个 URL 看看。

**Comment by Kenshin** [comment]
如果你看到我的 Email 建议在邮件中附上你的配置文件给我以及你的 IM（ Telegram 最好，微信其次。

**Comment by Skytostop** [comment]
> 

是在阅读模式下的标注，无论哪个URL都是这样，但是点击保存，虽然没反应，实际是有了，但是只能点退出，退出当前页面。

**Comment by Kenshin** [comment]
> 是在阅读模式下的标注，无论哪个URL都是这样，但是点击保存，虽然没反应，实际是有了，但是只能点退出，退出当前页面。

不是高级账户的，重置全部数据或重新安装简悦。

![image](https://user-images.githubusercontent.com/81074/142749969-11aa69f2-085f-46a8-a71a-a6277f92ef39.png)

**Comment by Skytostop** [comment]
你好，我在这里一并回复了吧，首先没有怪晚回复的意思，然后那个评论是我发的，因为虽然当初遇到的问题可能是一些基础问题，但那的确是我从新用户刚开始用的体验，我只是记录下当时自己的感受，恰巧处处是不好的体验，目前已经付费成高级帐户，这个保存的问题还在，当然也可能是chrome的问题。

**Comment by Kenshin** [comment]
先解决这个 issues 的问题，如果是高级账户的话，使用

![image](https://user-images.githubusercontent.com/81074/142750039-37f41688-8f17-47b5-86f7-5a10274f7e13.png)

重置你的配置文件（包括稍后读），另外，也建议先导出配置文件（含稍后读）到本地。

**Comment by Skytostop** [comment]
这个我两个都重置了，也清除了，还重置了chrome，就差卸载重装了，待会儿试试。正常点击保存，窗口应该会消失吧，现在也能用，就是点保存，再点退出。。。
![image](https://user-images.githubusercontent.com/15011412/142750216-cf63b261-b9e6-40fb-817e-f580f3fd2c50.png)

**Comment by Kenshin** [comment]
点击 保存，并不会退出；只有点击退出才会退出。

这么做的目的是为了：避免多次保存 / 反复调用。

这并不是 Bug。

**Comment by Kenshin** [comment]
看来我可以把这个 issues  也关闭了。

***

不过，既然你在 Webstore 提到的问题均不存在的话，建议修改下你的评论内容，以免误导其它用户。

因为：

1. 我还是很希望能付费的，只是目前看来那么多繁复的功能 → 你已经付费了

2. 新手指南 → 我也已经在 https://github.com/Kenshin/simpread/issues/3085#issuecomment-974756073 解释的很清楚了。

3. 我又用标注功能，结果在标注后备注那里，点击保存，怎么点都没反应 → 也就是我刚刚描述的内容。

***

PS：至于评分的话，你修改了我当然高兴，同样你有你自己的评分权利。
