### ISSUE TITLE
设置中心乱码？

### ISSUE THREAD

**Issue by Skytostop** [Kenshin/simpread#3085]
![image](https://user-images.githubusercontent.com/15011412/142738188-59943b89-5c01-4709-991a-ac116b0d75a2.png)

**Comment by Skytostop** [comment]
不知道哪里问题，现在好了

**Comment by Kenshin** [comment]
嗨，重启浏览器就可以了。

PS：看 ID 不知道是否是在 webstore 评论过，如果是的话，请联络我。

**Comment by Kenshin** [comment]
> 关于这个问题，你可以使用以下的方式自查

进入 https://simpread.pro/help

搜索 `乱码` 会得到很多答案

![image](https://user-images.githubusercontent.com/81074/142750072-5391c508-e250-400f-9196-56c293af532e.png)

包括你自己提的以及官方给出的方案（箭头所示）

另外，既然你提到了 [简悦新用户建议（看这一篇就足够了）](https://zhuanlan.zhihu.com/p/382683271) 里面也描述了这个**问题**（很显然，它不能是个常规 Bug）

![image](https://user-images.githubusercontent.com/81074/142750118-c983ab17-f39b-48c5-b3c9-74896c504feb.png)

同样，这篇文章的底部，也有明确的表述说明了帮助中心的入口 https://simpread.pro/help

![image](https://user-images.githubusercontent.com/81074/142750148-9ee4fbd3-b26f-4774-af8f-cf79fb2751ed.png)

**Comment by Kenshin** [comment]
所以，这个 https://zhuanlan.zhihu.com/p/382683271 你可以理解为是一个索引，通过它可以找到你遇到的任何常规性问题。
