### ISSUE TITLE
虎嗅的文章在稍后读中无法正常阅读

### ISSUE THREAD

**Issue by lemonleaves-Tang** [Kenshin/simpread#3086]

**Comment by lemonleaves-Tang** [comment]
虎嗅（www.huxiu.com）的文章在网页模式中可以进入阅读模式，但是在收藏入稍后读后，无法正常显示文章。

**Comment by lemonleaves-Tang** [comment]
![微信截图_20211121132133](https://user-images.githubusercontent.com/65531541/142750702-6a6f9b49-bec4-452a-915f-18c47599ce56.png)

**Comment by lemonleaves-Tang** [comment]
![image](https://user-images.githubusercontent.com/65531541/142750719-025517c6-cc90-48b0-af3e-44fb6bfb4351.png)

**Comment by lemonleaves-Tang** [comment]
原页面手动进入阅读模式没有问题，稍后读无论开启内置解析与否都不能正常显示。

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

在某些页面下确实存在**开启内置解析**也无法成功的情况，虽然是个例，简单的说，这个页面阻止类似爬虫的机制造成的。

解决方案：

- https://github.com/Kenshin/simpread/discussions/2146
- https://github.com/Kenshin/simpread/discussions/2220

**Comment by lemonleaves-Tang** [comment]
好的，问题完美解决了，谢谢。

**Comment by Kenshin** [comment]
搞定就好，没问题的话，我关闭这个 Issues 了。
