### ISSUE TITLE
定制化导出到Obsidian的标注，内部链接无法跳转到指定离线html

### ISSUE THREAD

**Issue by Lynyh22** [Kenshin/simpread#3096]
1.使用模板https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-756801 定制了离线Markdown模板，可正常使用；
![微信截图_20211123103835](https://user-images.githubusercontent.com/94436542/142963620-ccbd65ac-848d-4ff0-aa2b-3e6a746d7529.png)

2.已开启自动化，加入稍后读时自动导出html；
![微信截图_20211123104452](https://user-images.githubusercontent.com/94436542/142964058-263ee0a8-f368-41b5-887c-3848e7eae71c.png)

3.已正确配置导出文件夹；
![微信截图_20211123104753](https://user-images.githubusercontent.com/94436542/142964260-adbc494d-3bc8-49a1-a2d9-27890ccb6725.png)

4.以这篇文章为例https://sspai.com/post/69972 ，流程为进入阅读模式-加入简悦稍后读-在稍后读中进入阅读模式（自动导出到配置的文件夹）-点击复制离线markdown，能正常保存到Obsidian
![微信截图_20211123104955](https://user-images.githubusercontent.com/94436542/142964403-596874e3-439d-4eea-9564-66c5bd860218.png)

5.在Obsidian中点击内部链接跳转结果如下
![微信截图_20211123105120](https://user-images.githubusercontent.com/94436542/142964536-7f580ce2-a61c-4543-b2b2-bef76bbb8b16.png)

6.点击外部链接跳转结果如下
![微信截图_20211123105222](https://user-images.githubusercontent.com/94436542/142964597-0e8d2282-2186-4c03-8d24-e1ee38a47d8f.png)

求指导。

**Comment by Kenshin** [comment]
嗨，把**内部链接**修改下即可。

![image](https://user-images.githubusercontent.com/81074/142964798-3e8ba5e0-d3d9-44d2-8a77-de26c2c818ae.png)

```
http://localhost:7026/reading/
```

另外，第二个截图是**外部链接访问没有找到的提示**，看你的截图外部链接设置是正常的，但需要开通下面的服务与授权

1. [如何开通开放平台](https://github.com/Kenshin/simpread/discussions/2757)
2. [API 快照功能](https://github.com/Kenshin/simpread/discussions/2994)

**Comment by Lynyh22** [comment]
感谢，内部链接解决了，但是外部链接开通了API快照功能后，依旧是404，怀疑是id的问题，想问一下id是昵称吗？

**Comment by Kenshin** [comment]
哈哈，搞定就好，没问题的话，我关闭这个 Issues 了。

PS：感觉你的动手能力不错啊，在不在简悦的 [Telegram 群](https://t.me/simpreadgroup) 在的话，冒个头，认识认识。

***

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
