### ISSUE TITLE
懂车帝，新闻资讯页面，打开后一向下滚动就会报错

### ISSUE THREAD

**Issue by freshcn** [Kenshin/simpread#3106]
https://www.dongchedi.com/article/7034416498898698755

可以试一下，只要向下滚动页面就会报错了，如果设置为黑名单，就能正常的方式了。

**Comment by Kenshin** [comment]
嗨，我没有遇到这个问题。

请在 **隐身模式下仅使用简悦的方式** 看看是不是其它扩展造成的干扰。

**Comment by freshcn** [comment]
嗯，已经试过了。就是通过这个方式验证出来是简悦的。

**Comment by freshcn** [comment]
![image](https://user-images.githubusercontent.com/1764041/143520268-656110a9-796f-4c7b-a1b5-1353712fe786.png)

**Comment by Kenshin** [comment]
emmm 奇怪，看下我这里的录屏

https://user-images.githubusercontent.com/81074/143520559-a4b308c3-2ac7-4315-ae58-84dc99f5431a.mp4

另外，懂车帝任意一个页面都有此问题吗？还是仅这一个？

请告知你的系统与 Chrome 版本。

也可以将当前的配置文件导出到本地后，重置（或重装）简悦后，不修改任何配置再试试？

**Comment by freshcn** [comment]
你是已经进入到了阅读模式，你不要进入到阅读模式里面，直接向下拉，你就能看到那个报错出来了。
我使用的edge  版本 96.0.1054.34 (官方内部版本) (arm64)

**Comment by Kenshin** [comment]
收到，把下图所示的选项关闭即可。

![image](https://user-images.githubusercontent.com/81074/143811580-86c0f577-8615-4ade-b7e1-16f5d9a18dd7.png)

**Comment by freshcn** [comment]
还真是，这个关闭后，就不会再报错了。

**Comment by Kenshin** [comment]
搞定就好。 👍 

这个选项在个别页面确实存在问题，我在考虑优化这个选项的逻辑。
