### ISSUE TITLE
阅读模式失效

### ISSUE THREAD

**Issue by xinci1991** [Kenshin/simpread#3109]
**请说明发生问题的环境**

- 操作系统 ** Windows 10**

- 浏览器版本 **Chrome 96.0.4664.45**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 很多, e.g. https://blog.csdn.net/yanyan19880509/article/details/78335935

打开阅读模式后，一片空白，详见gif

![issue](https://user-images.githubusercontent.com/12273760/143558092-0d8c609a-a697-4b02-8b0e-a7644d9b923d.gif)

**Comment by xinci1991** [comment]
我尝试在隐身模式下单独使用，是没有问题的。

**Comment by Kenshin** [comment]
嗨，我测试了下，不用进入隐身模式就可以的。

估计是你安装的其它扩展造成的干扰，所以在隐身模式下没问题。

是仅这个页面有问题？还是全部？还是 CSDN  的页面？

**Comment by xinci1991** [comment]
> 

不仅仅是CSDN，我觉得可能是有的插件与简悦冲突了吧

**Comment by Kenshin** [comment]
> 不仅仅是CSDN，我觉得可能是有的插件与简悦冲突了吧

那只能逐一排查了，建议使用二分法，一半一半的排查，这样很容易缩小范围。

或者导出配置文件后重新安装简悦。
