### ISSUE TITLE
阅读模式，代码块乱序显示

### ISSUE THREAD

**Issue by iamkissg** [Kenshin/simpread#3112]
Hello，磊神，

我一般默认使用简悦的阅读模式进行阅读，直到看到[这篇文章](https://dantegates.github.io/2019/10/24/tensorflow-2-feature-columns-and-keras.html)：阅读模式下怎么都读不通了。

看起来是代码块下移了：

原文：
![原文](https://user-images.githubusercontent.com/9014580/143659926-2a8931e1-92bb-4e45-b05e-d9599abc2792.png)

阅读模式i：
![阅读模式](https://user-images.githubusercontent.com/9014580/143659970-c29da770-556c-4b64-81d6-cee9e1968f1f.png)

辛苦你看一下，谢谢。

**Comment by Kenshin** [comment]
嗨，代码段确实会有问题，因为不同的页面的代码实现逻辑非常不同，没有什么太好的规律。 😂 

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
