### ISSUE TITLE
仿safari插件无法关闭 "点击空白退出"

### ISSUE THREAD

**Issue by fangyuan99** [Kenshin/simpread#3113]
![image](https://user-images.githubusercontent.com/62874116/143676000-bab0e376-9bb3-4358-851e-197525170c7f.png)
如图，选项为灰色，无法选择，任意界面都是这样

**Comment by Kenshin** [comment]
emmm

1. 可能同时安装了多个插件，先禁用除此插件以外的插件，再试试

2. 可能是其它扩展造成的干扰，在 **隐身模式下仅使用简悦的方式**  试试，同时在正常点的 URL 上使用 e.g. https://sspai.com/post/69972

**Comment by fangyuan99** [comment]
方法2已解决，感谢

**Comment by Kenshin** [comment]
哈哈，搞定就好。

没问题的话，我关闭这个 Issues 了~
