### ISSUE TITLE
阅读模式如何保留原网页颜色等格式？

### ISSUE THREAD

**Issue by fangyuan99** [Kenshin/simpread#3115]
原网页:https://www.bilibili.com/read/cv14096236
<h2>如题，在进入聚焦模式后原网页的颜色信息没有了，可能不能准确的分辨重点内容，请问可以改进一下吗？</h2>

![image](https://user-images.githubusercontent.com/62874116/143724357-8ffcf04c-a80d-4f60-9aee-80fcc6160064.png)

![image](https://user-images.githubusercontent.com/62874116/143724297-5996a5f9-c5e9-4f7d-b7e4-1436d24f1aa5.png)

**Comment by Kenshin** [comment]
嗨，我看了下这个页面的颜色，它是由 CSS 指定的方案。

![image](https://user-images.githubusercontent.com/81074/143729369-2f49cb78-9539-4f73-a9ea-b9bb79491d0b.png)

简单的说，当进入阅读模式后这种 CSS 设置的颜色就「无效」了，你可以使用聚焦模式，可以保留这些颜色

![image](https://user-images.githubusercontent.com/81074/143729396-aabd4e2a-3d78-401a-b495-173c2579b007.png)
