### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by jelly-mazic** [Kenshin/simpread#3116]
发生问题的地址: <https://blog.csdn.net/su83362368/article/details/78502542>

**Comment by Kenshin** [comment]
嗨，使用 [重新高亮](http://ksria.com/simpread/docs/#/%E9%87%8D%E6%96%B0%E9%AB%98%E4%BA%AE)

![image](https://user-images.githubusercontent.com/81074/143763636-78bcaf5f-ca3e-40fc-8ade-434a335b87fa.png)

就可以解决了。

**Comment by Kenshin** [comment]
补充说明下：

因为 CSDN 已经适配过了，但这个页面确实有问题，所以使用上面提到的方式即可。
