### ISSUE TITLE
保存到稍后读没有标题导致无法自动导出到本地

### ISSUE THREAD

**Issue by sandy9707** [Kenshin/simpread#3117]
![image](https://user-images.githubusercontent.com/93817573/143768520-84cfc7a4-a66e-476b-acc1-8bd6785ba2ff.png)
![image](https://user-images.githubusercontent.com/93817573/143768534-ccd6d3eb-c7fd-498d-9985-ce2e95129325.png)
保存到微信的时候可以提取出标题但是不会自动填到标题的地方,只有描述是有字的

**Comment by Kenshin** [comment]
嗨，请提供出问题的 URL

另外，可以自己修改标题，按下图所示

![image](https://user-images.githubusercontent.com/81074/143801299-9894d8a7-9eb8-404e-a431-79155d2aa65e.png)

**Comment by sandy9707** [comment]
我现在一直是自己手动修改标题的,出问题的url为所有微信公众号的网址,比如
https://mp.weixin.qq.com/s/5ZODRzzDrS7VeWLADF4RMg
https://mp.weixin.qq.com/s/5ZODRzzDrS7VeWLADF4RMg
https://mp.weixin.qq.com/s/Nr9UiQ0GgS-OUhSSYIkrsA
https://mp.weixin.qq.com/s/IWG33p9Tdz7nkez5zeh_Fg
![image](https://user-images.githubusercontent.com/93817573/144030784-ef6a1dd7-e58d-4175-a9d0-45f183c5de6a.png)

**Comment by Kenshin** [comment]
我随便找了篇 https://mp.weixin.qq.com/s/5ZODRzzDrS7VeWLADF4RMg 加入稍后读后的效果

![image](https://user-images.githubusercontent.com/81074/144031136-548b2b4e-5ee6-4f8b-abc9-c932963ef086.png)

> 不可能出现问题的，如果出现了，试试以下的排除方式：

1. **隐身模式下仅使用简悦的方式** 

2. 导出配置文件，然后重置（或重装）简悦，之后不做任何改动直接添加稍后读，

3. 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看能否解决？

**Comment by sandy9707** [comment]
1.安装插件,无效果
2.导出配置文件后重置,无效果,同步助手功能保留
3.重装插件,无效果,同步助手稍后读界面不保留,全部重置
这..这咋整啊...
![image](https://user-images.githubusercontent.com/93817573/144064027-df4f1393-60cc-47d7-b670-044e6ef7be14.png)

**Comment by sandy9707** [comment]
![image](https://user-images.githubusercontent.com/93817573/144064162-8126a901-68ea-4980-8060-8691b87167cc.png)

**Comment by sandy9707** [comment]
新的问题出现了,无痕模式稍后读!成功!
为什么啊...无痕下为什么反而可以啊...

**Comment by sandy9707** [comment]
![image](https://user-images.githubusercontent.com/93817573/144065140-a08c0c37-00c3-447c-a767-11e12d41a4c4.png)

**Comment by sandy9707** [comment]
整明白了!!谢谢!!
是油猴里面的一个脚本的问题,叫网页精灵,用来展开全文的.
我早该想到油猴子这个浓眉大眼的问题...
谢谢!!

**Comment by Kenshin** [comment]
哈哈，搞定就好。

没问题的话，我关闭这个 Issues 了。

PS：听说话好像是东北老乡？

**Comment by sandy9707** [comment]
没有问题了,可以关闭了,谢谢解答.
ps:不是东北老乡,但是有东北舍友*2,于是.嘿嘿

**Comment by Kenshin** [comment]
哈哈，原来如此。 😏 

PS：如果没有在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏
