### ISSUE TITLE
我不知道为什么，我的标注模式无法开启了

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#3118]
![image](https://user-images.githubusercontent.com/37976371/143813187-c8ef2cd2-f3ec-4d28-9989-aef9f7d56798.png)
即使我重启电脑也不行，我不确定是什么问题，我在设置中默认是自动进入标注模式的

**Comment by rw1995** [comment]
此外，我的稍后读也无法进入，需要帮助，谢谢~ @Kenshin

**Comment by rw1995** [comment]
![image](https://user-images.githubusercontent.com/37976371/143813360-fc8d0902-0faf-4458-b7e4-3db15d0b6eed.png)

**Comment by Kenshin** [comment]
标注的问题猜测是由于稍后读空白的问题造成的，可以看下解决方案 https://github.com/Kenshin/simpread/discussions/2727

**Comment by rw1995** [comment]
@Kenshin  K大，我解决了空白的问题，但是我的简悦还是无法开启标注模式，它一直是灰的。。
![image](https://user-images.githubusercontent.com/37976371/143822075-aca58152-bc1d-4b16-9ebd-2cef1c837dbf.png)

**Comment by Kenshin** [comment]
> 我解决了空白的问题，但是我的简悦还是无法开启标注模式，它一直是灰的。。

emmm 你可以这样操作下：

1. 在任意页面点击它，如果正常的话，它应该变成下图所示效果

![image](https://user-images.githubusercontent.com/81074/143822747-52edb9ab-e3ce-4e6b-9113-0c74d1cca655.png)

2. 然后重启浏览器

**Comment by rw1995** [comment]
> 1. 在任意页面点击它，如果正常的话，它应该变成下图所示效果

ok，就好使了，之前一直点击灰色的“手电筒”，但是一直点亮不上，真是太奇怪了，也许是因为配置文件的问题吧=-=，不能找到原因，thx~

**Comment by Kenshin** [comment]
😂 

没问题就好~
