### ISSUE TITLE
绑定Dropbox时，提示密码过长导致无法加密，请使用坚果云授权方案

### ISSUE THREAD

**Issue by derust** [Kenshin/simpread#3122]
![image](https://user-images.githubusercontent.com/64185584/143838106-bd84fd08-80ee-4c4e-96b7-741b282118b3.png)

**Comment by Kenshin** [comment]
嗨，**因 Dropbox 修改了 Token 生成的逻辑导致此问题**，我还在调查 & 解决ing

请订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话以及方便的话订阅 Telegram Channel https://t.me/simpread 到时候我会在这里和官方渠道通知你。

**Comment by Kenshin** [comment]
嗨，此问题已经解决，请看解决方案 https://github.com/Kenshin/simpread/discussions/3171

**Comment by derust** [comment]
收到，感谢
