### ISSUE TITLE
关于自动化在使用上的一些求助

### ISSUE THREAD

**Issue by chinyajie** [Kenshin/simpread#3123]
自动同步功能一直不成功，已经充值过重新配置了也还是不行。自动同步到 pocket 失败，自动同步到 pocket 失败，自动同步 readwise 失败。重置后只离线同步本地也失败。

重置前手动同步功时，在稍后读点离线 html，可以后台自动下载到本地目录。重置后也不行了。

<img width="929" alt="CleanShot 2021-11-29 at 20 33 52@2x" src="https://user-images.githubusercontent.com/9836595/143868955-21f279c9-efed-4f36-afe0-5e1f3271f133.png">

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 macos 12

- 浏览器版本 Microsoft Edge 版本 95.0.1020.40 

- 简悦版本 **2.2.0** 同步助手 版本1.0.1 (1.0.1)

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**Comment by Kenshin** [comment]
没理解你的意思…

自动同步与自动同步到 Pocket 是两个功能：

- 前者是需要使用同步助手，说明看这里 http://ksria.com/simpread/docs/#/自动同步

- 后者是自动化功能，说明看这里 http://ksria.com/simpread/docs/#/自动化

至于「失败」的问题，请录屏或截图说明。

**Comment by Kenshin** [comment]
补充一点：

建议重启你的同步助手后再测试。

**Comment by chinyajie** [comment]
> 

是我没说清楚。我指的是自动化功能没有效果，无论是自动化到本地还是 Pocket，截图示最小化配置仅同步本地的情况。
同步助手一直是开启的 简悦 · 同步助手 1.0.1@mac，也重启过多次，无效。

**Comment by chinyajie** [comment]
<img width="938" alt="CleanShot 2021-11-29 at 21 39 35@2x" src="https://user-images.githubusercontent.com/9836595/143877998-04993c84-01e9-4083-9127-9d6abca0591b.png">

**Comment by Kenshin** [comment]
看下这个解决方案 https://github.com/Kenshin/simpread/discussions/2362

**Comment by chinyajie** [comment]
> 

我重新测了下，失败的原因可能与 Edge 浏览器设置有关。当我保存到稍后读后，Edge 浏览器会主动弹出下载框，并提供与简悦助手里配置的不同的下载地址，造成自动化操作失败。我取消自动导出本地后，将自动执行的类型改成导出到 Pocket ，是可以顺利执行的。

另外我昨天一直不成功的原因是我没有进入阅读状态，而是直接右键加入到稍后读的问题，如https://github.com/Kenshin/simpread/discussions/2362 提到的，普通状态下简悦拿不到正文。但这里是否有其他的优化方案，比如后台打开阅读模式获取正文，并在完成自动化操作后关闭后台页面。否则需要额外进入阅读模式，操作流程上不是很流畅。

谢谢。

**Comment by Kenshin** [comment]
> 当我保存到稍后读后，Edge 浏览器会主动弹出下载框

这里「有问题」，你没有开启增强导出，而是使用了浏览器自己的下载方式。

> 普通状态下简悦拿不到正文。但这里是否有其他的优化方案

不能的，未进入阅读模式的话，即便拿到正文，也会存在诸多问题。

如果是Windows 系统的话，可以试试 Quicker 提供的这些方式 https://github.com/Kenshin/simpread/discussions?discussions_q=quicker

**Comment by chinyajie** [comment]
> > 当我保存到稍后读后，Edge 浏览器会主动弹出下载框
> 
> 这里「有问题」，你没有开启增强导出，而是使用了浏览器自己的下载方式。

是的。打开这个开关后可以正常同步到本地了。

**Comment by chinyajie** [comment]
还有个问题要请教下。就是标注同步问题。我查看了 issue 中两个类似的问题做了设置，但是还是无法自动同步标注。我甚至尝试将自动改为手动，手动点击触发，还是不行。

<img width="434" alt="CleanShot 2021-11-29 at 23 14 18@2x" src="https://user-images.githubusercontent.com/9836595/143893868-bb03f0a8-f2fc-4094-9ffb-3c1c1819876d.png">

<img width="710" alt="CleanShot 2021-11-29 at 23 12 42@2x" src="https://user-images.githubusercontent.com/9836595/143893883-1bd985b7-0ace-4548-8905-e7871863b0a6.png">

<img width="211" alt="CleanShot 2021-11-29 at 22 59 43@2x" src="https://user-images.githubusercontent.com/9836595/143893902-b400ba94-02c6-4bac-8b04-6fbad9d5f766.png">


![CleanShot 2021-11-29 at 22 59 07@2x](https://user-images.githubusercontent.com/9836595/143893915-c0e0faf2-d8cf-48db-b657-09c0d64f7e5e.png)

**Comment by Kenshin** [comment]
> 在手动模式下触发按钮只有一个图标，没有文字。

这是因为你的自动化没有添加标题（描述）造成的。

***

至于无法同步 hyp 的问题，确实有点麻烦，感觉比较玄学... 把你的 hyp token 以及配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3123

**Comment by chinyajie** [comment]
> > 在手动模式下触发按钮只有一个图标，没有文字。
> 
> 这是因为你的自动化没有添加标题（描述）造成的。
> 
> 至于无法同步 hyp 的问题，确实有点麻烦，感觉比较玄学... 把你的 hyp token 以及配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3123

已发，谢谢。

**Comment by Kenshin** [comment]
嗨，测试时我会使用你的 hyp token 发一些标注过去，来自 https://sspai.com/post/69972 

另外，根据我的感受，可能是你的授权步骤有问题，我会给你的邮箱发一个视频，你可以根据视频先测试下。

**Comment by chinyajie** [comment]
> 嗨，测试时我会使用你的 hyp token 发一些标注过去，来自 https://sspai.com/post/69972
> 
> 另外，根据我的感受，可能是你的授权步骤有问题，我会给你的邮箱发一个视频，你可以根据视频先测试下。

截止到 12：05，我这边没有收到标注哈。
好的，一会收到视频我照着做一遍看看行不行。

非常感谢。

**Comment by chinyajie** [comment]
截止到 12：05，我这边没有收到标注哈。
好的，一会收到视频我照着做一遍看看行不行。

非常感谢。

________________________________

**Comment by Kenshin** [comment]
哈，别急，我在 12:10 才发的邮件。 😂

**Comment by chinyajie** [comment]
12:18 也没有呢~
________________________________

**Comment by Kenshin** [comment]
emmm

okay，我再测试看看。

**Comment by Kenshin** [comment]
我刚才看到你的配置文件自动化设置的有问题，**你把标注的自动化改为手动方式了**。

![image](https://user-images.githubusercontent.com/81074/143989022-0eb154bb-e808-4ef7-a3c3-e0927e94904f.png)

我现在改成了自动方式，并且增加了一条标注，你可以试试

![image](https://user-images.githubusercontent.com/81074/143989289-394ba735-9d30-4d44-b288-2302668260a1.png)

如果你收到了这个标注的话，那就是授权时的操作问题，请看邮件中的视频。

**Comment by chinyajie** [comment]
应该不是授权的问题，因为我反反复复试过很多次了。
考虑到我的 edge 的插件是自动从 chrome 导入的，而且标记的高亮在正文中显示也有些问题（正文中不显示，右侧标签栏显示），我卸载了简悦，然后去官网重新下载了 edge 版本的插件。然后导入之前的本地配置，再次标注就成功了。

非常感谢你花这么多时间帮我调试，现在用起来效果很好。
________________________________

**Comment by Kenshin** [comment]
哈哈，没问题就好。  😂 

hyp 的问题太玄学了，我也想弄明白，方便「后来者」，可惜又失败了。

另外，我在使用时产生的标注也同步到了 hyp 里面了吗？

**Comment by chinyajie** [comment]
本地存储 + 线上获取：我的个人数据库建构路径 - 少数派
________________________________

**Comment by chinyajie** [comment]
本地存储 + 线上获取：我的个人数据库建构路径 - 少数派
这一篇产生了两条。

________________________________

**Comment by chinyajie** [comment]
发现一个新 case
注释同步的时候，如果先划线然后注释文字，就可以同步成功。如果直接注释文字，虽然在简悦里能自动划线，但是不会同步到 hypothesis 里面。
[cid:d60645da-c373-4251-9728-5125c319b2ce]
________________________________

**Comment by Kenshin** [comment]
> 注释同步的时候，如果先划线然后注释文字，就可以同步成功。如果直接注释文字，虽然在简悦里能自动划线，但是不会同步到 hypothesis 里面。

没理解你的意思。什么叫做「直接注释文字」？你是如何操作的？

**Comment by chinyajie** [comment]
就是图片里红色箭头的操作。如果先 1 后 2 就是划线然后注释，可以同步。如果直接紫色箭头操作，直接写注释内容但不主动划线就不能同步。

________________________________

**Comment by Kenshin** [comment]
哈哈，不要用过邮件的方式回复我，因为看不到附件...

进入 https://github.com/Kenshin/simpread/issues/3123 再回复我。 😂

**Comment by chinyajie** [comment]
> 

![CleanShot 2021-11-30 at 15 36 29@2x](https://user-images.githubusercontent.com/9836595/144014667-5ba35342-d0b6-44fe-a6cd-73e43849b03a.png)
图片里红色箭头的操作。如果先 1 后 2 就是划线然后注释，可以同步。如果直接紫色箭头操作，直接写注释内容，简悦可以自动划线高亮，但不主动划线就不能同步。

**Comment by Kenshin** [comment]
确实是个 Bug，当然并不是严重的 Bug，除了你说的方式外，也有解决方案 https://github.com/Kenshin/simpread/issues/3131#issuecomment-982490260

**Comment by Kenshin** [comment]
另外，这个 Issues 可以 Close 了。

虽然到最后还是没有调查出为什么最开始无法同步 hyp  😂 

***

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏
