### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by Zooooey** [Kenshin/simpread#3130]
发生问题的地址: <https://www.collabora.com/news-and-blog/blog/2019/04/26/an-ebpf-overview-part-3-walking-up-the-software-stack/>

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
