### ISSUE TITLE
你们的用户账户管理做的真的很差，麻烦改进好吗

### ISSUE THREAD

**Issue by kame008** [Kenshin/simpread#3133]
我换了个设备用的同一个谷歌账号登录的Chrome浏览器添加的简悦插件都需要我重新登录自己的简悦账号。完全不能第一眼看到自己的账户登录管理在哪里，找回高级账号也很繁琐，我明明印象笔记存了自己的UID都找不到地方重新登录自己账号，看到那个找回高级账户只能用三次我就很不满，我知道自己UID却不能登录为什么责任要推给用户？！

最鸡肋的就是登录方式，作为一个付费的应用，让用户用自己的常用邮箱注册账号，你们做个用户账号管理很难吗？！什么贵的“用简悦配置文件登录”，你们都没有给已登录用户留下配置文件导出的地方，第三方登录是冷门的坚果云和Dropbox登录，为了用一个阅读插件我还要去注册坚果云和Dropbox？！太可笑了。

还要我去少数派找自己的订单、找到订单里面的激活码、然后再找回自己的UID？！你们做一个切换账号让我自己把UID贴上去验证不就行了？？？

**Comment by gaomind** [comment]
@kame008 非常同意，换设备体验了一下「找回高级帐户」这个功能，难用到令人发指，已经在找其他的替代产品了。
