### ISSUE TITLE
汇总反馈几点使用体验，期待简悦更优秀

### ISSUE THREAD

**Issue by WangChao2021** [Kenshin/simpread#3150]
前天偶然下载其他插件时看到了高分的简悦插件，下载试用了确实很不错，毫不犹豫买了一个高级会员支持作者。

使用了几天，还是发现了一些几点，希望简悦能越来越优秀，提出以下几点使用感受：

1. 识别后的正文内容（如极客时间）缺失；
2. 标注时不能直接修改样式，要等标注完后，二次修改才可修改样式
3. 转阅读模式后希望可以保留加粗的文本内容和列表格式；

## 1. 极客时间自动识别内容有缺失

平时极客用得比较多，经常把一些文章转换阅读模式标注后进行展示，但发现有些内容会直接丢失

文章例子：https://time.geekbang.org/column/article/14256
转换前：

![image](https://user-images.githubusercontent.com/95513088/144694486-5f875d91-61a2-423d-aa8b-b730e9a5e966.png)

 转换后，
![image](https://user-images.githubusercontent.com/95513088/144694499-7a40a022-6162-437d-86cc-986ba834ec21.png)

文章例子：https://time.geekbang.org/column/article/14405
转换前：
![image](https://user-images.githubusercontent.com/95513088/144695304-aaa4f518-db0b-4492-9916-c3ac4cf9dd8d.png)

转换后：
![image](https://user-images.githubusercontent.com/95513088/144695288-9acc3c4e-2212-4832-9f8b-46ec41675df3.png)

## 2. 标注时无法直接通过快捷方式修改样式（有时间真的很不方便）

直接看git图，有时间真的很不方便

![Untitled](https://user-images.githubusercontent.com/95513088/144695716-fc830a1c-9036-4d2b-ae58-d86fcc5f6370.gif)

## 3. 希望转阅读模式后，保留原有的粗体内容列表格式（普通列表和数字列表）

 示例，极客时间，文章：https://time.geekbang.org/column/article/14256
![image](https://user-images.githubusercontent.com/95513088/144695891-6b18bf64-b937-4a5b-bd2c-54c8cf0d3eae.png)

这个问题是一个通用问题，不只是极客时间，手动选择内容，格式有时候也不对

------

**花了近2个小时找 gif 录制工具，注册github账号，最终整理反馈以上几点问题，因为简悦值得让人期待变得更好！！**

**Comment by Kenshin** [comment]
> 嗨，这个站已经适配，下面是使用方法：

***

### 如何安装

1. 打开 https://simpread.ksria.cn/sites/details/wDdKo5U4q1 选择安装即可（全自动）

2. 将 `time.geekbang.org` 加入到延迟加载列表

![image](https://user-images.githubusercontent.com/81074/144700644-ec4471a1-9064-4ce0-9203-c4b862967c48.png)

### 如何使用

进入极客时间的页面 e.g.  https://time.geekbang.org/column/article/14405 通过右上角 icon ![image](https://user-images.githubusercontent.com/81074/144700634-fde60e2f-2052-4dc4-8b24-6b851bbe5f9d.png) 手动进入。

### 为什么不能自动进入

> 极客时间的页面是动态加载，故无法自动进入。

**Comment by Kenshin** [comment]
另外，确认无误后，记得修改你的密码。

**Comment by WangChao2021** [comment]
> 另外，确认无误后，记得修改你的密码。

没想到这么快就适配了，不过极客时间还有几点问题，作者如果有时间可以再进一步优化下，我们账户密码近期都不修改，以给作者进行适配测试 。

1. 进入阅读模式后，无法使用标注
    ![image](https://user-images.githubusercontent.com/95513088/144702330-c2ee1e32-722f-4a30-8b53-c1f48446aca5.png)

2. 转换后的列表格式未得到保留

    ![image](https://user-images.githubusercontent.com/95513088/144702440-c09908ef-d42d-4a53-ae1e-ad7f1ce15861.png)
    转换后：
    ![image](https://user-images.githubusercontent.com/95513088/144702465-a5abdd26-9464-4d66-af27-62c4296cfd6b.png)

    ![image](https://user-images.githubusercontent.com/95513088/144702483-e61daaf5-d9bd-4f42-bcc8-c3cdf7c386ee.png)
    转换后:
    ![image](https://user-images.githubusercontent.com/95513088/144702986-f0d46d79-0687-491e-882a-326078cea18a.png)

3. 引用格式未适配

    ![image](https://user-images.githubusercontent.com/95513088/144703024-8ef82a33-51cd-40ff-9eaa-70382b19d4a0.png) 
    转换后：
    ![image](https://user-images.githubusercontent.com/95513088/144703044-49a3a7ae-8a83-4421-b7ce-b7e1bf4e66b8.png)

4. 代码块未适配

    ![Uploading image.png…]()
    转换后：
    ![image](https://user-images.githubusercontent.com/95513088/144703106-53a4ddb7-0fd7-430b-8961-abd857dac77c.png)

**Comment by Kenshin** [comment]
忘记还个功能需要设置下...

***

> 关闭词法分析引擎上的纯粹模式。

![image](https://user-images.githubusercontent.com/81074/144705419-f20d7b8e-6c36-4c22-8394-447485461def.png)

### 注意

当不使用极客时间的时候，请开启此选项以达到最优优化效果。

**Comment by WangChao2021** [comment]
> 

可以，取消纯粹模式就显示正常了，不过还是没有看到标注工具，不知道为什么，很奇怪。
![image](https://user-images.githubusercontent.com/95513088/144706932-f592abc5-0267-46ff-8f75-336b2a737fc6.png)

纯粹模式关闭和打开还是挺麻烦的，期待后面纯粹模式或者极客时间站点能适配得更完美


**Comment by Kenshin** [comment]
> 期待后面纯粹模式或者极客时间站点能适配得更完美

是的，未来有更好的方式

> 不过还是没有看到标注工具，不知道为什么，很奇怪。

请问在别的页面可以看到吗？e.g. https://sspai.com/post/69972

**Comment by WangChao2021** [comment]
> > 期待后面纯粹模式或者极客时间站点能适配得更完美
> 
> 是的，未来有更好的方式
> 
> > 不过还是没有看到标注工具，不知道为什么，很奇怪。
> 
> 请问在别的页面可以看到吗？e.g. https://sspai.com/post/69972

其他页面都是正常的，不知道极客时间怎么出不来

**Comment by Kenshin** [comment]
> 其他页面都是正常的，不知道极客时间怎么出不来，想测试随时都可用我的账号

估计还有个样式的问题，我刚才无法登录极客时间了，应该你也在登录，等明天的时候看下。

**Comment by WangChao2021** [comment]
> 

我退出登陆了，有时间再处理下吧，感谢！

**Comment by WangChao2021** [comment]
> > 其他页面都是正常的，不知道极客时间怎么出不来，想测试随时都可用我的账号
> 
> 估计还有个样式的问题，我刚才无法登录极客时间了，应该你也在登录，等明天的时候看下。

我退出登陆了，有时间再处理下吧，感谢！

**Comment by Kenshin** [comment]
嗨，我刚才看了下这个问题，是因为极客时间对应某些注入到它页面的内容做了限制造成的。

暂时没有太好的解决方案，但可以通过此方式「绕过去」：

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

**Comment by WangChao2021** [comment]
知道了，极客可以通过这种方式使用

**Comment by Kenshin** [comment]
> 知道了，极客可以通过这种方式使用

哈哈，能解决就好。

PS：还是建议更换下密码。 😁
