### ISSUE TITLE
简悦阅读模式下标记

### ISSUE THREAD

**Issue by Yuying1014** [Kenshin/simpread#3151]
阅读模式下的划线标记和备注功能是我阅读中使用较多的功能。但目前的划线标记生成的右侧列表的顺序无法调整，我更希望这个地方是可以调整排序的。这样我就可以导出预期顺序的标注内容。
使用这个功能的意义在于，一篇文章可能对我而言有用的可能只有其中一部分，我希望通过划线标记将这些部分标记起来后，正确的进行导出。

**Comment by Kenshin** [comment]
嗨，可以的。

请看这里 https://github.com/Kenshin/simpread/discussions/3152
