### ISSUE TITLE
使用阅读模式，代码段格式的文本中，注释被删除了

### ISSUE THREAD

**Issue by Yuying1014** [Kenshin/simpread#3153]
使用阅读模式，代码段格式的文本中，注释被删除了
使用的网站：https://www.liaoxuefeng.com/wiki/1022910821149312/1023020952022784#0
![image](https://user-images.githubusercontent.com/73064390/144702800-77c2d83b-2698-4171-ab14-d58c1e93a4ee.png)
![image](https://user-images.githubusercontent.com/73064390/144702821-1bb2d1dd-daf8-49fd-9020-3fd5bec48ec6.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
