### ISSUE TITLE
同步助手的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3158]
通过压缩包内打卡exe安装的同步助手，重启电脑后会提示：
![Snipaste_2021-12-06_00-56-23](https://user-images.githubusercontent.com/7368227/144756691-9024597e-c646-485d-b5ab-58c2ac2bd1f1.jpg)

而后遇到的问题：
1、无法保存同步助手中设置的快捷键（）：
![image](https://user-images.githubusercontent.com/7368227/144756746-69451906-318f-4a46-aa76-0a45a929a916.png)
2、无法使用稍后读的阅读模式（提示未打开同步助手）：
![image](https://user-images.githubusercontent.com/7368227/144756828-755f19ed-2304-47f5-ad2d-3a26b9c084f0.png)
![image](https://user-images.githubusercontent.com/7368227/144756981-45ecc4ef-9b69-4840-83f4-cd863ee568b4.png)

3、无法设置微博文章为稍后读
![image](https://user-images.githubusercontent.com/7368227/144757093-5e948c9d-9a55-4f2e-b404-0fcdc0c88b32.png)

_Originally posted by @alderol in https://github.com/Kenshin/simpread/discussions/2129#discussioncomment-1752991_

**Comment by Kenshin** [comment]
@alderol

嗨，我把你在 https://github.com/Kenshin/simpread/discussions/2129 的提问转移到这里了，并删除了原位置的内容。

***

> 通过压缩包内打卡exe安装的同步助手，重启电脑后会提示：

试试安装 32 位系统能否解决？另外你的什么系统？

> 无法保存同步助手中设置的快捷键

无法修改吗？还是什么意思？

> 无法使用稍后读的阅读模式（提示未打开同步助手）：

我不清楚第一个问题是否解决了，否则的话，这个问题跟第一个是关联性问题。

**Comment by alderol** [comment]
> @Kenshin 

开发者你好，下面作出回应。
> 
> 试试安装 32 位系统能否解决？另外你的什么系统？
目前系统为win10 21H2，准备尝试一下32位的1.0.1版本，稍后作出回复。

> 无法修改吗？还是什么意思？
在同步助手中修改了全局快捷键后，新设置的快捷键无法使用，原来的Ctrl+Alt+N也无法使用，均会弹出win10无法识别的打卡软件的方式（见截图）。此快捷键仅因为默认快捷键与之前常用的冲突，希望改掉而已。
https://user-images.githubusercontent.com/7368227/144756746-69451906-318f-4a46-aa76-0a45a929a916.png

另外麻烦问一下， 我使用的 Chromium 内核的edge浏览器，没有找到“在浏览器中创建快捷方式”的选项。
![image](https://user-images.githubusercontent.com/7368227/144790305-154a54f7-73d7-428a-ab02-efa69ddadaa6.png)

**Comment by Kenshin** [comment]
> 第二个问题

这么小众的快捷键默认值还能被占用？按照下图所示的提示修改，应该没问题的。

![image](https://user-images.githubusercontent.com/81074/144791056-9f59e250-d156-491b-bbb1-46886db6bfde.png)


> 第三个问题的答案

![image](https://user-images.githubusercontent.com/81074/144790886-1dae52af-3544-4f0c-bcc8-11ae21c62ad0.png)

**Comment by alderol** [comment]
> > 第三个问题的答案
> 
> ![image](https://user-images.githubusercontent.com/81074/144790886-1dae52af-3544-4f0c-bcc8-11ae21c62ad0.png)
第三个问题解决了，谢谢。

发现目前首先应该解决软件安装的问题，重启笔记本后，会弹出以下提示：
![image](https://user-images.githubusercontent.com/7368227/144799336-c8b8e116-2df1-4552-a01c-d15a32fe7dab.png)
我第一遍是在压缩包内，双击安装的1.0.1@win64版本的软件，已经出现了此问题。
上次开机后，我按您的提示，解压后安装了1.0.1@win32版本的软件，目前重启后开始会有上图系统错误的弹窗。

是否有一种方法能够完全卸载两个版本的同步助手，然后再安装一遍呢？（将优先尝试安装32位）目前已经设置了坚果云的自动同步配置。

另外发现一个现象，不知道对解决问题是否有帮助：win64位的压缩包内仅有一个exe ，win32位的压缩包内有一系列文件。
![image](https://user-images.githubusercontent.com/7368227/144799939-dc6675bb-0436-42ec-a815-cf30fee5be37.png)

**Comment by alderol** [comment]
目前进度：
> 
![image](https://user-images.githubusercontent.com/7368227/144882452-648f2a7c-39cc-4c0b-aaec-a81bebb22184.png)
1、通过开机报错定位到的文件夹，找到了两个跟简悦相关的，猜测为64和32位两个版本。删除了文件夹，之后用火绒检测删掉了开机启动项，算卸载完成。

2、正常解压1.0.1@win32位的文件路径，双击安装完成。已经解决了上述开机后报错的问题。

3、发现的第一个问题，插件状态不能保存，设置过的“阅读模式浮动面板定制器”配置，每次打开都会恢复，之后干脆在“动作”处看不到插件触发器了。按https://github.com/Kenshin/simpread/discussions/2342 说明操作后，现在插件触发器中能看到插件，但是配置的项目还是会恢复回默认。
![image](https://user-images.githubusercontent.com/7368227/144883951-3b9c1885-d613-4218-a851-3f84cc050ef4.png)
此时点开设置，选择项是记录了的：
![image](https://user-images.githubusercontent.com/7368227/144884090-2c8a18e3-4825-4f44-af2e-c61ff87fb12f.png)

4、稍后读中的阅读模式一直加载不出文章，提示解析失败：
![image](https://user-images.githubusercontent.com/7368227/144884252-4071ecaf-604f-431b-9c8f-00cef84901b2.png)

5、本来希望通过自动化操作记录文章：
![image](https://user-images.githubusercontent.com/7368227/144884565-8c1787b2-e53c-409e-9cb8-d253a7fc928a.png)
即加入稍后读的文章，自动存入语雀。遇到的问题：①稍后读无法抓取到内容（也可能是抓取到但没有解析显示）②没有进行存入语雀的操作。

6、第五步中未实现的操作，目前临时的解决方案为：打开阅读模式-【s】【r】打开快捷键-【y】【q】调用语雀。此方案的问题是，在语雀中会存入目录中（另一个web Clipper的chrome插件剪藏后，文档都在暂存箱内，是可以正常移动和编辑的），无法做移动，复制，重命名，删除等操作。此问题已反馈给语雀https://www.yuque.com/yuque/topics/39188 不知道是哪里出了问题。

麻烦 @Kenshin 看一下问题，谢谢。

**Comment by Kenshin** [comment]
> 问题3

emm 一般用户遇到时，使用 https://github.com/Kenshin/simpread/discussions/2342 用方案一即可解决了，你可以试试方案四。

> 问题4

请开启稍后读下面两个选项

![image](https://user-images.githubusercontent.com/81074/144959428-24407abf-6da7-406a-a444-7a49a1f08412.png)

以及这个教程 https://github.com/Kenshin/simpread/discussions/2146

> 问题5

自动化是好用的，但要留意这里的说明 https://github.com/Kenshin/simpread/discussions/2362

简单的说，打开 URL → 进入阅读模式 → 使用快捷键 <kbd>d d</kbd> 加入自动化，即可。

> 问题6

在 SimpRead 中的内容也可以移动

![image](https://user-images.githubusercontent.com/81074/144959327-661d8aa2-9404-4c9d-8a9f-812a7eec2a8f.png)

![image](https://user-images.githubusercontent.com/81074/144959351-3a29fbd7-8ffb-42e3-83e6-cdd413e887ce.png)

**Comment by alderol** [comment]
> emm 一般用户遇到时，使用 #2342 用方案一即可解决了，你可以试试方案四。

按问题四操作：
1.导出配置文件(从edge浏览器）
2.重新安装简悦（从chrome浏览器）
3.重启chrome浏览器和同步助手软件
4.安装包含插件触发器的插件（测试安装了“阅读模式浮动面板定制器”和“分栏阅读模式”）

效果：
1、动作页已经按面板定制器的配置进行显示，但是下方没有两个插件的设置显示。
![image](https://user-images.githubusercontent.com/7368227/145075989-977ce02d-c709-4d76-a155-8e064be84d4d.png)
2、插件页显示的已安装插件仅有“分栏阅读模式”一项，完全没显示“面板定制器”插件。
![image](https://user-images.githubusercontent.com/7368227/145076126-9c658d9b-a8aa-478c-ba55-38cea670b8a4.png)

**Comment by Kenshin** [comment]
emmm 你试试这样操作：

1. 关闭自动同步

![image](https://user-images.githubusercontent.com/81074/145141288-d64f5d3f-f943-4adb-893e-07683a74f609.png)

2. 刷新选项页

3. 清除本地全部插件

![image](https://user-images.githubusercontent.com/81074/145141327-9d391ecd-64c7-4e21-a478-7ee6bec9d9b8.png)

4. 安装插件 e.g. 分栏阅读

5. 打开 https://sspai.com/post/69972 这时应该弹出分栏阅读的选项卡

6. 设置它并保存

7. 刷新当前页面确保此插件生效

8. 如生效后，关闭此这个页面的 Tab 并打开选项页

9. 开启自动同步并覆盖本地配置文件（看红箭头）

![image](https://user-images.githubusercontent.com/81074/145141533-2471c931-aa75-441a-8bc8-6599a92765b0.png)

10. 刷新选项页

11. 再次打开 https://sspai.com/post/69972

12. 看看**触发器**和**插件栏**里面是否存在？

<img width="1004" alt="2021-12-08_11-13-05" src="https://user-images.githubusercontent.com/81074/145141977-df613b5b-be36-4e68-a120-784dcbf79a2a.png">

13. 如果存在插件但不存在触发器的话，打开选项页 → 插件管理 → 导入配置文件

![image](https://user-images.githubusercontent.com/81074/145142030-60a17bdc-56c9-45b2-9dbd-8d26be9e4928.png)

14. 导入完毕后，重启浏览器后，看看是否成功了？

PS：此步骤看起来比较多，只是方案一的细调版而已，因为你无法使用方案一，所以才用了此方式。

**Comment by alderol** [comment]
谢谢，按上文的方案一的细调版，在进行到12步时已经解决。后面13 14没有执行。

另外剪藏到语雀使用了，阅读模式的【sr】快捷键操作，效果很满意（做了一些站点编辑器的调整）。

不过自动化的导出到语雀还是没生效，想想我是需要操作微博的文章，需要登录获取内容，所以还是需要进入阅读模式才行，自动化用不了。

**Comment by Kenshin** [comment]
> 自动化的导出到语雀还是没生效

自动化的需要使用快捷键 <kbd>d d</kbd> 这里有个 Bug 细节看这里 https://github.com/Kenshin/simpread/discussions/2362

**Comment by alderol** [comment]
> 自动化的需要使用快捷键 d d
进入阅读模式后d d确实能触发稍后读以及自动化。

**Comment by Kenshin** [comment]
okay 没问题就好。

我关闭这个 Issues 了~

**Comment by alderol** [comment]
辛苦K大这么长时间耐心的解答~

**Comment by Kenshin** [comment]
哈哈，没事的，能解决你（用户）的问题，是件很愉快的事情。

不过，要是可以的话，可以在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 帮忙五星好评 + 评价，这是对简悦最好的帮助。 🙏  💪  😏

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4
