### ISSUE TITLE
CSDN 页面的 字体 类型不可调

### ISSUE THREAD

**Issue by zhuoshuai** [Kenshin/simpread#316]
在 [CSDN](https://blog.csdn.net/szlcw1/article/details/52259668) 上看文章时, 样式中字体更换后没有变化, 而 [cnblog.com](http://www.cnblogs.com/jeffwongishandsome/archive/2012/08/05/2623660.html)里面 的文章则可以.
PS: 相关字体文件已经安装了.

**Comment by Kenshin** [comment]
估计是 `CSDN` 的全局样式导致的，我想想办法~ 感谢反馈~

**Comment by lixi0912** [comment]
@Kenshin  发现 CSS 样式中如果有 inherit 关键字也会导致替换失败，比如：```style="color: inherit;"``` 也会导致字体颜色替换失败，[看这篇](https://mp.weixin.qq.com/s/035SiIDhmbHzbtI1fF4h1g)，主题：紺鼠

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [去掉 CSDN 的字体无法更改的错误](https://simpread.ksria.cn/plugins/details/SumEaxStWE) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀

**Comment by Kenshin** [comment]
这是不可避免的，毕竟 UGC 的东西，其规则几乎无法具有统配型。

等有时间的时候，考虑用正则的方式试试。
