### ISSUE TITLE
每日回顾功能显示已成功开通，但无法收到邮件

### ISSUE THREAD

**Issue by Miaoyifei-mz** [Kenshin/simpread#3175]
如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~ 😀
**请说明发生问题的环境**

简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Mac, M1, macOS Monterey 12.0.1

- 浏览器版本 Chrome 版本96.0.4664.93（正式版本）（arm64）

- 简悦版本 2.2.0

- 发生问题的地址：chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#connect

**请描述你的问题**

每日回顾功能显示已成功开通但无法收到邮件，但可以将单篇文章成功发送到邮箱。

**截图**

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/60280844/145179840-61a93ca4-4e89-4d87-b5ef-456f611d65e4.png">

**Comment by Kenshin** [comment]
接收到每日回顾的条件：

> 你在坚果云 / Dropbox 的配置文件在二十四小时内有稍后读（或标注）

一般来说，使用此功能都需要配合同步助手与客户端（坚果云 or Dropbox），所以你给出的信息太少，我没法判断。

假设确实按照上面所说的也没有收到邮件的话，建议：

1. 更换为 QQ 邮箱
2. 使用坚果云作为同步盘
3. 将你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3175

**Comment by Miaoyifei-mz** [comment]
您好

**Comment by Miaoyifei-mz** [comment]
您好，`help#####simpread.pro`里面的`#`指的是什么呢？

**Comment by Miaoyifei-mz** [comment]
非常感谢Kenshin大大的解答！我之前设置的发件邮箱是 QQ 邮箱，是不是也要把收件邮箱也更改为 QQ 邮箱？之前是使用坚果云作为同步盘且已经授权坚果云登录了。

**Comment by Kenshin** [comment]
嗨，我看了下你的 UID，应该是坚果云没有找到对应的简悦配置文件 `simpread_config.json` 导致。

开通每日回顾前需要：

> 配置自动同步功能，如何配置看这里 https://github.com/Kenshin/simpread/discussions/2754

**Comment by Miaoyifei-mz** [comment]
谢谢您，问题解决啦！

**Comment by Kenshin** [comment]
哈哈，搞定就好。

没问题的话，我关闭这个 Issues 了。

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏

**Comment by silencetopromise** [comment]
> 哈哈，搞定就好。
> 
> 没问题的话，我关闭这个 Issues 了。

大佬，我也遇到了一样的问题。每日回顾功能已开通且按照教程设置完成，但是每天19:10收不到邮件。但也可以在阅读模式中将文章以email发送至我的邮箱。可以帮我也看下嘛？已经将我的uid发送至您邮箱了。谢谢。
