### ISSUE TITLE
智能感知和动手动聚焦模式，也无法识别正文

### ISSUE THREAD

**Issue by DeanShiDirect** [Kenshin/simpread#3181]
http://www.dayanzai.me/about 这个页面的正文内容一闪而过，
用AA快捷键唤醒simpread，提示智能感知失败，接着使用手动聚焦模式，这两个功能都不能识别正文，

正文内容 图床图片
https://i.iluoli.moe/2021/12/09/18db11209050348.jpg

使用simpread，无法看见正文
https://i.iluoli.moe/2021/12/09/724dc1209050619.jpg

**Comment by Kenshin** [comment]
谢谢反馈，选项页 → 高级设定 → 词法分析引擎，按照下图所示关闭此选项即可。

![image](https://user-images.githubusercontent.com/81074/145376681-83b742d2-1b43-4d02-8001-44fad048ce97.png)

**Comment by DeanShiDirect** [comment]
果然这个插件设置问题，谢谢反馈。

**Comment by DeanShiDirect** [comment]
谷歌插件通过您的方法，修改好了。
但是，简悦( SimpRead ) · 轻阅版 油猴脚本 怎么修改呢？

**Comment by Kenshin** [comment]
搞定就好。

> 简悦( SimpRead ) · 轻阅版 油猴脚本

这个脚本已经很久不更新了，也只是简悦 1.x 部分版本的功能。

另外，上面提到的解决方案并不是针对这个油猴脚本的。
