### ISSUE TITLE
定制化导出到Obsidian的标注，外部链接打开 404

### ISSUE THREAD

**Issue by Miaoyifei-mz** [Kenshin/simpread#3189]
提这个问题有些不好意思，因为之前有人提出过类似的问题#3096，但按照里面的方案没有解决问题 o(╥﹏╥)o

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/60280844/145711805-a872cd3a-eebe-4880-a4e1-a85678d5c928.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/60280844/145711810-811cafac-0153-4ba1-b362-b572ccc252c6.png">

按照#3096 里作者大大的方案，开放平台和 API 快照都已开通，API 测试正常
<img width="978" alt="image" src="https://user-images.githubusercontent.com/60280844/145711865-28b93419-2eef-4c56-9c0d-efa85fc02498.png">

求指导

**Comment by Kenshin** [comment]
请问你可以正常访问 `http://simpread.pro/@a2719/reading` 吗？

给出的截图信息量太少了，我没法帮到你。

1. 你可以告诉我，访问什么 URL 出现的 404 ？

2. 访问这个 404 时，output 文件夹有对应的 html 吗？

**Comment by Miaoyifei-mz** [comment]
您好，可以正常访问 `http://simpread.pro/@a2719/reading`
1. 访问这个 URL `https://simpread.pro/@a2719/reading40?title=当我们谈原生家庭的时候我们到底在谈些什么 – 左岸读书#id=1639218047705`出现的 404，404的链接是 `https://simpread.pro/404.html#id=1639218248490`
2. output 文件夹里有 html, 但这个 output 文件夹不在坚果云的根目录 simpread 文件夹下，是我在同步助手中自定义路径的。

**Comment by Kenshin** [comment]
> output 文件夹里有 html, 但这个 output 文件夹不在坚果云的根目录 simpread 文件夹下，是我在同步助手中自定义路径的。

这是「错误」的，配置看这里的说明 https://github.com/Kenshin/simpread/discussions/2958

**Comment by Kenshin** [comment]
另外再补充下，这个功能属于「资料库」的一部分，你可以看下面两个教程：

1. 知识库 https://github.com/Kenshin/simpread/discussions/2221
2. 资料库 https://github.com/Kenshin/simpread/discussions/2956

**Comment by Miaoyifei-mz** [comment]
哦哦，总算是搞明白了，谢谢您！☺。那之后的版本会提供资料库导出路径自定义功能吗？

**Comment by Kenshin** [comment]
哈哈，没事的，搞定就好。我关闭这个 Issues 了。

> 那之后的版本会提供资料库导出路径自定义功能吗？

当然了，只是优先级不会太高。

**Comment by Kenshin** [comment]
哦，对了，又忘了一点...

请订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话以及方便的话订阅 Telegram Channel https://t.me/simpread **如果这个功能适配后** 我会在这里和官方渠道通知你。

**Comment by Miaoyifei-mz** [comment]
哈哈，已经在电报群里潜水好久了~_~

**Comment by Miaoyifei-mz** [comment]
简悦真的非常棒，很好的融入到了我的工作流中，现在已经离不开它了，非常感谢您的创意和工作！

**Comment by Kenshin** [comment]
哈哈，也谢谢你喜欢简悦。

很感谢今日份的正向思考。 💪

**Comment by Kenshin** [comment]
又又又忘了...  😂 

如果有兴趣的话，可以共享下你的 [Obsidian 模板](https://github.com/Kenshin/simpread/discussions/2153) 甚至与 [分享下你的工作流](https://github.com/Kenshin/simpread/discussions/2085)。

PS：如果没有帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，请帮忙评分。🙏  💪  😏

**Comment by Miaoyifei-mz** [comment]
没问题!#^_^#

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
