### ISSUE TITLE
title显示错误.

### ISSUE THREAD

**Issue by luo276785794** [Kenshin/simpread#319]
if(/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)){ document.write("<span class='rich_media_title_ios'>React v16 新特性实践 </span>"); }else{ document.write("React v16 新特性实践"); } React v16 新特性实践

地址:https://mp.weixin.qq.com/s/5KXDVxXgJ1ho5F7Ave8nfA

微信地址的好像都有这个问题

**Comment by Kenshin** [comment]
感谢反馈，我也发现了，明天看看是什么问题，估计是微信的站点编辑器的 title 设置有问题。

**Comment by Kenshin** [comment]
已修复，操作如下：
设定 → 点击「手动同步适配列表」→ 「共享适配列表给 xxx」 即可。
