### ISSUE TITLE
代码块没有被包含在内

### ISSUE THREAD

**Issue by yuzhen1024** [Kenshin/simpread#3194]
- 操作系统 **Win64**
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
- 简悦版本 **2.2.0**
- 发生问题的地址 <https://draveness.me/golang>
- https://draveness.me/golang/docs/part2-foundation/ch03-datastructure/golang-array/

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
