### ISSUE TITLE
有些网站的图片在阅读模式只能显示小图，导出pdf的时候也都是小图

### ISSUE THREAD

**Issue by wunai813914** [Kenshin/simpread#3195]
![1639450200(1)](https://user-images.githubusercontent.com/52577661/145924187-eab5ec11-8b48-4f26-a931-82adf4e2dc1e.png)
https://zhuanlan.zhihu.com/p/112141757
这个是我这边显示的样子，我想知道这个是我设置的问题还是软件本身的问题？有时候确实比较难受，影响了后续的阅读，谢谢了

**Comment by Kenshin** [comment]
哈哈，当然不可能是简悦的问题... 简悦为了知乎适配了很多东西，包括：

1. [完美适配知乎专栏与问答页](https://github.com/Kenshin/simpread/discussions/2869)

2. [知乎阅读辅助增强](https://github.com/Kenshin/simpread/discussions/2861)

你的问题可以试试**隐身模式下仅使用简悦的方式**，排除其它扩展造成的干扰。

**Comment by Kenshin** [comment]
另外，我测试了你提供的 URL 是没问题的。

![image](https://user-images.githubusercontent.com/81074/145925174-f532e7ad-2d38-4731-94d1-8842cec28a4d.png)

**Comment by wunai813914** [comment]
太好了，谢谢，之前好像没看到知乎的这个插件呢

**Comment by Kenshin** [comment]
> 太好了，谢谢，之前好像没看到知乎的这个插件呢

你可以订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread

另外，也可以通过 [检索知识库](https://github.com/Kenshin/simpread/discussions) 的方式来获取更多的相关内容 

![image](https://user-images.githubusercontent.com/81074/146481587-08a6a76e-0e69-497c-a7e3-3a4efdc8efd0.png)
