### ISSUE TITLE
chuansong

### ISSUE THREAD

**Issue by leesudo** [Kenshin/simpread#32]
传送门，最近在用这个看微信公众号
```
{
        "name"    : "chuansong.me",
        "url"     : "http://chuansong.me/n/",
        "title"   : "<h2 class='rich_media_title' id='activity-name'>",
        "desc"    : "",
        "include" : "<div id='page-content'>",
        "exclude" : [
        ]
    }
```

**Comment by Kenshin** [comment]
感谢~已添加，请通过 [这个方式](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%85%B3%E4%BA%8E%E6%9B%B4%E6%96%B0) 更新。

另外，微信公众号的格式都比较奇怪，所以不是每篇文章都能完美显示。 :joy:

**Comment by leesudo** [comment]
thx，我看的内容大部分还是正常的，希望早日加上用户自定义和新增站点功能。

**Comment by Kenshin** [comment]
新版 `1.0.1` 在准备中，预计本周推送。但新版本只增加了一些 v2 反应的细节定制化 以及 issues 的 bug。
再下个版本 `1.1.0` 将会包含你说的功能。
