### ISSUE TITLE
导出pdf时提示  “导出失败，此功能为实验性功能”

### ISSUE THREAD

**Issue by libiingzhi** [Kenshin/simpread#3200]

**Comment by Kenshin** [comment]
嗨，请详细说明操作过程并提供 URL 否则我没法帮到你。

我先关闭这个 Issues 等你补齐后再重开它。

**Comment by h8877** [comment]
我也遇到了相同的问题，链接如下：
https://blog.csdn.net/zat111/article/details/36420903

**Comment by Kenshin** [comment]
@h8877 

[中断、异常、trap 的区别_语暖心扉的博客 - CSDN 博客_中断和异常的区别.pdf](https://github.com/Kenshin/simpread/files/7798962/trap._.-.CSDN._.pdf)

我这边没问题，重新测试下，看看能否稳定复现它。
