### ISSUE TITLE
在自动化导出标注时,偶尔出现导出失败的问题.

### ISSUE THREAD

**Issue by Zhixiaz** [Kenshin/simpread#3217]
- 操作系统  **Windows**

- 浏览器版本 **Edge 版本 98.0.1089.1 (官方内部版本) dev (64 位)**

- 简悦版本 **2.2.0.520**
- 同步助手版本 **1.0.1**

**问题**: 在使用标注自动导出的情况下,随机的会出现如图中红条所示的提示,与提示相伴出现的,是此次标注的html或者markdown格式的本地标注导出失败(我遇到的较多情况是html格式的标注导出失败).
![Snipaste_2021-12-19_22-02-52](https://user-images.githubusercontent.com/51500882/146678057-e53eee76-013d-48eb-a7de-48134fa78bc3.png)
![Snipaste_2021-12-19_22-19-29](https://user-images.githubusercontent.com/51500882/146678215-39e4073a-04c8-4500-9784-542a0d40e443.png)

如果再次尝试标注,又会成功保存.

目前我的自动化导出方案是

![Snipaste_2021-12-19_22-13-59](https://user-images.githubusercontent.com/51500882/146678103-73de3bb0-d162-4ff0-a938-a6554f787192.png)
导出方式是**全文(带标注)+标注**.

**Comment by Kenshin** [comment]
很奇怪的问题... 这个提示的意思是：在一些特殊情况（包括 Bug）你的账户没有成功通过验证而产生的提示。

你的机器性能（配置）是什么？另外这个问题是每个页面都会发生吗？还是特定的页面？

试试先去掉一个本地导出，看看能否有所改善。

**Comment by Zhixiaz** [comment]
处理器是 Intel(R) Core(TM) i5-10200H
RAM是16G
系统版本是 Windows 11 专业版 21H2
我基本是用在读微信的推文.应该和网页页面关系不大. 
可能和机器配置有一些关系,在另一台CPU 是Intel 奔腾 4415U的老机子上,这个问题出现的频率要高一些.
然后如果在标注时,标注间隔比较短的话,出现的频次也比较高.
之前应该没有遇到过这样的问题,记忆里好像是这两周才出现的.而这两周我对系统进行了更新,浏览器也有过更新,不知道是不是和这个有关系.
另外对于去掉一个本地导出,是指只导出标注或者只导出全文吗?我试一试.

**Comment by Kenshin** [comment]
> 另外对于去掉一个本地导出,是指只导出标注或者只导出全文吗?我试一试.

是的，就是 Markdown or HTML 二选一。

> 然后如果在标注时,标注间隔比较短的话,出现的频次也比较高.

验证你的账户确实跟操作频率有关系，**请问你是什么网络？比如：XX省电信这样的**

> 是Intel 奔腾 4415U的老机子上,这个问题出现的频率要高一些.

如果是这个配置的话，或许会可能，所以你改成导出二选一再看看。（自动化相对来说消耗一些性能，所以会出现「奇怪」问题。

>  Intel(R) Core(TM) i5-10200H

你是哪年购买的电脑？

**Comment by Zhixiaz** [comment]
> 请问你是什么网络？比如：XX省电信这样的

网络是浙江省电信网络


>> Intel(R) Core(TM) i5-10200H

>你是哪年购买的电脑？

电脑是今年买的

**Comment by Kenshin** [comment]
okay 那就排除了这台 PC 性能的问题以及网络的问题。（网络这边存疑些，但这个问题也不好调查，一般来说国内应该是没问题的，比较在国内服务商这边。

PS：可以留意下我之前提到的两点。

**Comment by Zhixiaz** [comment]
好的,我先试试,遇到什么新的问题我也会反馈的

**Comment by Kenshin** [comment]
好，我先关闭这个Issues ，你可以随时重开它。
