### ISSUE TITLE
站点管理器-自定义适配 只有一条记录时，点击自定义适配源无反应

### ISSUE THREAD

**Issue by lixi0912** [Kenshin/simpread#322]
版本： 1.1.0
插件：chrome 版本
浏览器版本： 66.0.3359.181
系统： MAC 10.13.2

本地只有适配一个站点时，点击自定义适配源不会弹出选择列表，点击无反应。官方适配源无问题。

**Comment by Kenshin** [comment]
感谢反馈，这是个 Bug，已经修复了，但需要随着 1.1.1 一起发布。
PS：最近在弄 简悦的 JSBox 版，所以 1.1.1 一直在 delay...  😂 顺利的话，下周发布，最迟下两周~

**Comment by Kenshin** [comment]
我先重启开启，等 1.1.1 发布后，我会再次关闭它。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
