### ISSUE TITLE
鼠标右键菜单中没有加入到稍后读应该怎么解决

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3221]
![image](https://user-images.githubusercontent.com/12624910/146866699-f39b7053-5f32-4711-8c06-fd851cc1394d.png)
鼠标右键菜单中没有加入到稍后读应该怎么解决。。。

_Originally posted by @xiang578 in https://github.com/Kenshin/simpread/discussions/2146#discussioncomment-1850660_

**Comment by Kenshin** [comment]
@xiang578

嗨，我删除了原来位置的内容，因为不符合 discussion 的内容。

至于你的答案就在你截图中

![image](https://user-images.githubusercontent.com/81074/146867969-5a80bdf2-2ecc-4a62-8585-4ed399f60371.png)

进入后，找到高级设定 → 右键菜单，就能看到你需要的内容了。

##注意 

https://github.com/Kenshin/simpread/discussions/2362 提到的几种无法使用稍后读的原因。（不包括右键菜单

**Comment by xiang578** [comment]
找到了，感谢。简悦功能实在是太多了。。。我先熟悉一下。

**Comment by Kenshin** [comment]
哈哈，没事的。

选项页（偏好设置）的大部分功能都配有说明文档，而并不是每个用户都需要了解每个功能的。

你可以看看这篇 https://github.com/Kenshin/simpread/discussions/1552 内容。
