### ISSUE TITLE
配置WebDav时遇到了问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3222]
Hi, Kenshin. 按照教程在配置WebDav时遇到了问题，一直提示格式错误。
![image](https://user-images.githubusercontent.com/28707897/146895750-0c03995a-dbf7-491b-bfa8-a1a603f94a84.png)
打开console之后看到这样的错误
![image](https://user-images.githubusercontent.com/28707897/146895798-304d1f93-9e4b-4f8a-aefe-7addfffab3da.png)
是哪里出了问题呢😕

_Originally posted by @luc99hen in https://github.com/Kenshin/simpread/discussions/2275#discussioncomment-1851398_

**Comment by Kenshin** [comment]
@luc99hen

嗨，我删除了原来位置的内容，因为不符合 discussion 的内容。

***

第二个截图可忽略，跟第一个图无关。

至于第一个问题的话，把关键信息改为 `*` 然后给我看下。

**Comment by luc99hen** [comment]
```
{"name":"Webhook2flomo","url":"https://api-wrap.simpread.pro/api/service/flomo","type":"POST","fmt":"md","body":{"endpoint":"https://flomoapp.com/iwh/*****/*****/","template":"#收集\nnote [[note]]\n[[content]]\n------《[[title]]》[[url]] [[tags]]","params":{"url":"{{url}}","title":"{{title}}","desc":"{{desc}}","note":"{{note}}","tags":"{{tags}}","content":"{{content}}"}}}
```
@Kenshin ， 除了API的地址外，我没有对样例里的模板做修改
![image](https://user-images.githubusercontent.com/28707897/146937660-8a6523a3-5d52-439b-b61c-c8a52a91210c.png)

**Comment by Kenshin** [comment]
请仔细看教程…这不是放在 WebDAV 里面的…

😂

**Comment by luc99hen** [comment]
> 请仔细看教程…这不是放在 WebDAV 里面的…
> 
> 😂

我的问题😝，眼拙。抱歉哈

**Comment by Kenshin** [comment]
哈哈，没关系。
