### ISSUE TITLE
开放平台打不开了

### ISSUE THREAD

**Issue by kiss33366684** [Kenshin/simpread#3225]
额就是网址输进去是空白https://simpread.pro/developer
![Screenshot_2021-12-21-21-39-23-694_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/45267048/146939401-a4cfb493-d2da-4309-b991-ffc61e13162f.jpg)

**Comment by kiss33366684** [comment]
额就是网址输进去是空白https://simpread.pro/developer
![Screenshot_2021-12-21-21-39-23-694_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/45267048/146939401-a4cfb493-d2da-4309-b991-ffc61e13162f.jpg)

**Comment by Kenshin** [comment]
我可以打开。

试试更改 DNS https://github.com/Kenshin/simpread/discussions/2990

**Comment by kiss33366684** [comment]
感谢您，确实改了能打开了。












青词昭月
***@***.***

18780250712

---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2021年12月21日(周二) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 开放平台打不开了 (Issue #3225)




 
我可以打开。
 
试试更改 DNS #2990

**Comment by Kenshin** [comment]
哈哈，没问题就好，我关闭这个 Issues 了。
