### ISSUE TITLE
建议：导出obsidian时本地化保存图片

### ISSUE THREAD

**Issue by ernestyao** [Kenshin/simpread#3226]
由于obsidian插件较多，所以个人是在用它做一些文档保存。目前要导出完整的本地版本，最可行的方式是textbundle，然后手工修改markdown标题、调整一下其中的图片引用链接，总体来说比较繁琐。既然已经能支持直接导出到obsidian，能否考虑增加图片的下载？即导出时获得一个markdown文件（.md），一个包含其中图片的文件夹。

只要能在导出时设置图片目录名（或者默认就用网页的标题），那在obsidian里就可以直接使用。

最后还是感谢开发出如此好用的软件。

**Comment by Kenshin** [comment]
谢谢喜欢使用。

至于你的问题，除了你提到的手动修改 textbundle 外，如果是 Windows  系统的话，也可以看看下面几个 Quicker 动作：

- [通过 Quicker 进一步增强定制简悦的 Markdown 导出到 Obsidian 及定制思路](https://github.com/Kenshin/simpread/discussions/3224)
- [用 Quicker 转换 Obsidian 中的离线 Markdown 文档中的图片](https://github.com/Kenshin/simpread/discussions/3132)
- [批量下载 Markdown 中的外链图片并替换成本地离线图片链接（主要应用场景：通过简悦导出 Markdown 到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2241)

更多 Quicker 动作可以 [看这里](https://github.com/Kenshin/simpread/discussions/categories/%E6%9C%8D%E5%8A%A1?discussions_q=category%3A%E6%9C%8D%E5%8A%A1+quicker)。

**Comment by ernestyao** [comment]
感谢答复。是macOS系统，所以无法和Quicker关联。

**Comment by Kenshin** [comment]
哈哈，还有给个未发布的方式，是个 uTools 的脚本 → 用 Python 脚本转换 base64 并存为图片。

可订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会在这里和官方渠道通知你。

**Comment by Kellermaan** [comment]
看到那么多workaround方案，我小心问一句，为啥不一开始提供一个下载离线图片的功能呢，应该也不是很复杂吧。不是抬杠哈。

**Comment by ernestyao** [comment]
> 看到那么多workaround方案，我小心问一句，为啥不一开始提供一个下载离线图片的功能呢，应该也不是很复杂吧。不是抬杠哈。

下载为Textbundle的方案本身就是包含离线图片的，只是Obsidian不原生支持textbundle。下载为markdown时也有一个选择是图片嵌入md文件里，但这个方案似乎比较怪异，不是一个常规使用markdown的形式。

至于是否再开发一个markdown文件+图片文件夹的方案，就看作者评估难度和用户需求了。在开发者和另一位网友的启发下，我用hazel解决了问题，如果您有需要可以参考：[https://www.readern.com/import-textbundle-to-obsidian.html](https://www.readern.com/import-textbundle-to-obsidian.html)

**Comment by Kenshin** [comment]
@ernestyao 

哈哈，谢谢，很完美的回复。

> 至于是否再开发一个markdown文件+图片文件夹的方案，就看作者评估难度和用户需求了

下个版本的同步助手就会有此功能了。

**Comment by ccyousa** [comment]
> @ernestyao
> 
> 哈哈，谢谢，很完美的回复。
> 
> > 至于是否再开发一个markdown文件+图片文件夹的方案，就看作者评估难度和用户需求了
> 
> 下个版本的同步助手就会有此功能了。

下一个版本预计什么时候放出呢？感觉很久没有更新了

**Comment by Kenshin** [comment]
@ccyousa 

哈哈，因为有些新玩意，会有惊喜。

**Comment by Nadir-Echo** [comment]
> @ccyousa
> 
> 哈哈，因为有些新玩意，会有惊喜。

很期待下个版本

**Comment by ccyousa** [comment]
> @Kenshin 
> 嗨，各位，关于这个 Issues 提到的需求，其实有实现了 #3241 ，有需要的话，可以看看。

虽然但是，还是太麻烦了。

**Comment by Kenshin** [comment]
@ccyousa 

麻烦都是相对的，即便配置仅需要几分钟时间，但带来的便利呢？

**Comment by Kenshin** [comment]
嗨，各位。

导入到 Obsidian 升级到 1.2.0 ，增加了 **重磅功能**：可以不通过同步助手，将标注自动导入到 Obsidian。

## 文档说明

https://github.com/Kenshin/simpread/issues/2900

## 一站式教程

https://simpread.zhubai.love/posts/2128393555537739776

## 视频

https://user-images.githubusercontent.com/81074/164135947-0552fc11-1b92-4804-a616-df64ae43770a.mp4

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了，简悦 1.0.2 版来了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 以 md + assets 方式导出

1.0.2 版内置了 以 md + assets 方式导出方案，详细说明 👉 https://github.com/Kenshin/simpread/discussions/4047

# 同步助手 1.0.2 版

https://github.com/Kenshin/simpread/discussions/4049

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
