### ISSUE TITLE
配置稍后读无法加载本地离线文件

### ISSUE THREAD

**Issue by xiang578** [Kenshin/simpread#3227]
按说明 https://github.com/Kenshin/simpread/discussions/2146 配置了稍后读，新的网页加到稍后读时能执行自动化在本地保存网页，但是打开稍后读软件时没有加载本地离线文件。

已经打开优先加载，多次刷新网页没有出现 local 和云的小图标，所以判断没有加载本地离线文件。
![image](https://user-images.githubusercontent.com/12624910/146962012-76b3dd2a-1111-46e6-a6d7-634a9fe0d553.png)

磁盘上确认文件已经存在
![image](https://user-images.githubusercontent.com/12624910/146962175-6e0eeb99-159b-48c1-86d7-49c8a3f6d932.png)

配置页面设置
![image](https://user-images.githubusercontent.com/12624910/146962291-5c3118b3-0a19-4b77-b1b0-5b707122859c.png)

标注相关设置
![image](https://user-images.githubusercontent.com/12624910/146962414-35767a61-1e02-46c4-8ba1-cb9526c33c09.png)

**Comment by Kenshin** [comment]
嗨，你的截图没有体现出：

> 是否【配置自定义标题】了？

**Comment by xiang578** [comment]
自定义标题配置的是
![image.png](https://s2.loli.net/2021/12/22/XeUOkswICvlMNgj.png)

**Comment by Kenshin** [comment]
emmm 奇怪

试试访问 

1. http://localhost:7026/reading/index
2. http://localhost:7026/reading/13

看看显示什么内容？如果什么都没有的话，重启同步助手试试。

**Comment by xiang578** [comment]
感谢，找到出现问题的原因了。我把稍后读的输出设置在 reading 目录，然后配置同步的目录设置在  reading/SimpleRead/，这样就不能使用本地缓存。然后把配置的目录移除出来就可以了。

**Comment by Kenshin** [comment]
哈哈，搞定就好，原来是这个问题...

**Comment by gukejing** [comment]
> emmm 奇怪
> 
> 试试访问
> 
> 1. http://localhost:7026/reading/index
> 2. http://localhost:7026/reading/13
> 
> 看看显示什么内容？如果什么都没有的话，重启同步助手试试。

第一个链接能看到一系列本地缓存的文件，但是后面一个链接显示如下
{"code":404,"message":"没有找到对应的内容"}

**Comment by Kenshin** [comment]
@gukejing 

我把你 https://github.com/Kenshin/simpread/issues/3322 和 https://github.com/Kenshin/simpread/issues/3320 都关闭了。

请在这里集中讨论

***

关于你在这两个 Issues 里面提到的问题，应该还是没有配置成功造成的，你可以从 https://www.yuque.com/kenshin/simpread/pwpnsx 开始配置，包括下图红框的内容，配置的时候仔细看教程的配图说明，共计十五分钟左右即可。

![image](https://user-images.githubusercontent.com/81074/149700455-6d2c600d-cd58-411f-b1ff-d4984bec82b8.png)
