### ISSUE TITLE
飞书文档中，转化后会丢失文章内容，只剩当前屏幕的内容。

### ISSUE THREAD

**Issue by cryschao** [Kenshin/simpread#3229]
飞书文档中，转化后会丢失文章内容，只剩当前屏幕的内容。

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://oy1dnbt144.feishu.cn/docs/doccnJQQpTNccCsCkaGluUxuNre>

![image](https://user-images.githubusercontent.com/3120362/147056923-8895abe3-9787-4353-87b9-87bdb7f2b81a.png)

![image](https://user-images.githubusercontent.com/3120362/147057057-102e0c5f-d90f-4ad0-a7c6-ec9d7ec95c6c.png)

**Comment by Kenshin** [comment]
嗨，飞书文档是不会被主动视频的，因为涉及到版权问题。

比如你截图中就包含了很多「版权水印」。

这并不是技术问题，如果你原意的话，可以自行适配它。
