### ISSUE TITLE
微信文章标题乱码

### ISSUE THREAD

**Issue by ziyangxiami** [Kenshin/simpread#323]
Title显示为：
if(/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)){ document.write("<span class='rich_media_title_ios'> 难道这就是传说中的无人自动驾驶？</span>"); }else{ document.write("难道这就是传说中的无人自动驾驶？"); } 难道这就是传说中的无人自动驾驶？

微信Version. 2.3.13 (10763)
Chrome版本 66.0.3359.181（正式版本） （64 位）

**Comment by Kenshin** [comment]
感谢反馈，已修复此问题，请更新了适配列表，`选项页 → 共通 → 同步适配列表`。
即可解决这个问题。 😀
