### ISSUE TITLE
右下角控制栏，不管是鼠标移上去还是点击，都无法使控制栏显示出来

### ISSUE THREAD

**Issue by wtoufo47** [Kenshin/simpread#3232]
- 操作系统 **Windows 10 21H1*

- 浏览器版本 **chrome 96.0.4664.110**

- 简悦版本 **2.2.0**

- 发生问题的地址 <>

>右下角控制栏，不管是鼠标移上去还是点击，都无法使控制栏显示出来

![Screenshot 2021-12-23 141301](https://user-images.githubusercontent.com/49442907/147196565-d19b8464-1fe9-444d-a005-d1a90e540633.jpg)

> 偶尔进入阅读模式是显示白屏，清除浏览器缓存或重启均无改善

**Comment by Kenshin** [comment]
嗨，可以用以下方式排查：

1. 进入 https://sspai.com/post/69972 并在 **隐身模式下仅使用简悦的方式** 看看能否解决？
2. 此问题是否是任意 URL 均存在？还是某个特定的 URL？
3. 导出配置文件后，重新安装简悦，在不改动任何设置的前提下是否可以解决？

**Comment by wtoufo47** [comment]
测试出来了，是chrome里一个护眼的插件，关闭删除了之后就能一切正常了

**Comment by Kenshin** [comment]
okay 找到问题就好，我关闭这个 issues 了。
