### ISSUE TITLE
无法与维基百科镜像站共存

### ISSUE THREAD

**Issue by zhengqiang-050123** [Kenshin/simpread#3238]
操作系统：Windows10
浏览器版本：具体不知道，但是截至目前最新版
在访问library.ac.cn所提供的维基百科镜像站时，无法加载主体内容，只有页首页脚，使用扩展管理器关闭简悦后恢复正常。
PS：不方便贴图，但进入后在简悦打开的情况下确实无法获取到具体内容

**Comment by Kenshin** [comment]
嗨，不知道为什么你关闭这个 Issues 了，还是提示下，看下图即可解决。

![image](https://user-images.githubusercontent.com/81074/147398427-28d03541-ea98-4cd6-8c96-82b009899811.png)

**Comment by zhengqiang-050123** [comment]
关闭issue是因为其他issue已经提到，问题重复了，但如果是按照黑名单的方式解决维基百科镜像站的问题的话，黑名单内要加入对应镜像站的域名，麻烦添加到#2163的页面中
PS：开发者人很不错

**Comment by Kenshin** [comment]
okay 我会记录下。

今天是 2021 最后一天，提前祝你新年快乐。
