### ISSUE TITLE
[FR] update config without reload page

### ISSUE THREAD

**Issue by Cologler** [Kenshin/simpread#324]
现在更改配置文件需要重新加载页面，有没有可能做到不需要重新加载页面呢？

优点：

* 如果能完全保证注入以后再取消注入以后，页面不变，#307 这个问题也能解决。
* 更容易调试阅读效果。

**Comment by Kenshin** [comment]
感谢意见~
这么做是为了确保当前页面的数据为更改后的数据。

---
当然，从技术层面将是没问题的，只是目前的逻辑：每个页面的数据都是「独立」存在，只有在载入的时候，才拿数据。

---
#307 与你说的并没有什么关系。

---
「调试」阅读效果，如果仅仅只是包含 主题、字体、大小、版面等，1.1.1 版会有更好的解决方案。 😀

**Comment by Kenshin** [comment]
1.1.1 发布的新版本是否能解决你说的 `更容易调试阅读效果。` 呢？
如果解决的话，请关闭此 issues ~
