### ISSUE TITLE
使用坚果云登录返回500了

### ISSUE THREAD

**Issue by chelseachen007** [Kenshin/simpread#3243]
![image](https://user-images.githubusercontent.com/36880000/147447010-d1e484b6-a54a-4c02-928c-d6055081b6d1.png)

**Comment by Kenshin** [comment]
登录什么返回的？

**Comment by chelseachen007** [comment]
> 登录什么返回的？

![image](https://user-images.githubusercontent.com/36880000/147458848-ab02fbc2-0c04-4d91-8c5b-4e4478fc7021.png)
在偏好设置中 => 使用登录=> 坚果云登录后
显示弹框登录成功,正在验证权限。
然后查看xhr 显示500了

**Comment by Kenshin** [comment]
emm

使用此功能的前提是 https://github.com/Kenshin/simpread/discussions/1570

**Comment by chelseachen007** [comment]
首先坚果云授权检查已授权，然后准备检查账户时候发现
![image](https://user-images.githubusercontent.com/36880000/147460563-a27b3e24-a897-4c6b-bdfd-46194bff9e85.png)

但核心问题应该是以下
背景： 知乎文章，功能：批注自动同步到obsidian。
在批注划线的时候显示非高级用户（之前是可以成功同步的）。
![image](https://user-images.githubusercontent.com/36880000/147460764-cde032f0-428e-4091-97e2-fd5cddeea1e5.png)

**Comment by Kenshin** [comment]
> 在批注划线的时候显示非高级用户（之前是可以成功同步的）。

重启同步助手 and 重启浏览器

看看能否解决错误提示的问题？如果不能的话，使用下面的方式：

1. 重启同步助手（如上面已经重启，可不用再重启）
2. 取消当前设备的授权 https://github.com/Kenshin/simpread/discussions/1575
3. 重启浏览器
4. 重新授权当前设备 https://github.com/Kenshin/simpread/discussions/1576

看看能否解决错误提示的问题？

**Comment by chelseachen007** [comment]
按以上操作可以同步了 非常感谢

**Comment by Kenshin** [comment]
okay 搞定就好。

我关闭这个 issues 了~
