### ISSUE TITLE
TXT阅读器无法启动

### ISSUE THREAD

**Issue by kingcharleslzy** [Kenshin/simpread#325]
我下载了一些txt 小说  然后拖到chrome上  但是没法启动txt阅读器模式      请问还需要什么操作？？

**Comment by Kenshin** [comment]
打开 chrome://extensions 找到简悦，
请确保 「允许访问文件网址」 处于勾选状态。

**Comment by Kenshin** [comment]
没问题的话关闭 issue 了。
