### ISSUE TITLE
1.0时的页面元素编辑的功能没有了吗？

### ISSUE THREAD

**Issue by lazeman** [Kenshin/simpread#3250]
如题，原来有这样的功能，可以删除一些不必要的页面元素，现在不行了。

**请说明发生问题的环境**

- 操作系统  Windows

- 浏览器版本 Microsoft Edge 版本 96.0.1054.62 (官方内部版本) (64 位)

- 简悦版本 简悦 - SimpRead 大小: 4.2 MB大小4.2 MB版本: 2 . 2 . 0 . 5 2 0版本2.2.0.520

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，当然有了...

![image](https://user-images.githubusercontent.com/81074/147542711-402fb078-ed65-4496-b1ca-ab386628846b.png)

不止如此，还有这个 https://zhuanlan.zhihu.com/p/448986968 更好用。
