### ISSUE TITLE
使用配置文件登陆时，提示后台异常

### ISSUE THREAD

**Issue by liuyf90** [Kenshin/simpread#3255]
![image](https://user-images.githubusercontent.com/25540464/147712234-bb10c139-d51a-4ae0-9660-a302a2991ba4.png)

**Comment by Kenshin** [comment]
嗨，试试下面的方式：

1. 取消当前设备的授权 https://github.com/Kenshin/simpread/discussions/1575
2. 重启浏览器
3. 重新授权当前设备 https://github.com/Kenshin/simpread/discussions/1576

并且留意这个问题 https://github.com/Kenshin/simpread/discussions/1567

**Comment by liuyf90** [comment]
按#1567的方法解决了

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
