### ISSUE TITLE
对简悦的一些评价及建议

### ISSUE THREAD

**Issue by cscnk52** [Kenshin/simpread#3264]
# 评价

我不想天花乱坠，只想说发生在我身上的真人真事：

> 我是班里的白板管理员，高三了，语文老师让我们在课前默写，默写是在一个网站上的内容，简悦适配了，我以为同学们没注意到，当有一天查个东西上了维基，因简悦的问题暂时关闭了简悦，课前同学们就问我说那个简化页面的东西怎么没了；也有人问过我那个是什么，说批注真好用。

所以好的东西是内化的，润物无声的。

# 建议

-   简悦缺少打印选项

简悦的页面因含有字号等内容，不适合打印出来，虽然关了批注再选择文字使用 chrome 打印还行，但操作还是繁琐，应提供一个打印选项，便于快速打印

- 支持多套外观切换

因为要照顾后排同学，字调得比较大，但平时字体应该比较小，所以应在样式页面直接加入快速配置方案切换，且支持同时切换字体，版面宽度等，并且加入在指定域名或页面切换指定配置方案，或直接加在站点编辑器里

- 版面切换并不是个好选项

在浏览器半屏情况或浏览器窗口宽度较小时，因有版面宽度存在，可能出现一行几个字的情况，影响阅读，应加入固定一行字数的选项

- 控制栏的更多（三个点）按钮不支持单击

因为触摸屏的单击对应左击，而当前为鼠标悬停触发，在触摸屏上表现不好

- 在视频与文章共存的界面，简悦不加载视频

暂时这些，我再想起来更多再提交issue吧，也祝开发者元旦快乐

PS：码比较长的东西还是得看纯纯写作，第一遍在GitHub里编辑因为编辑时间长，节点抽风，连不上了，这是第二遍

**Comment by Kenshin** [comment]
嗨，谢谢反馈，一一回复下：

> 当有一天查个东西上了维基，因简悦的问题暂时关闭了简悦

这是个 Bug 但 2.2.0.520 已经解决了这个问题，同时也可以看 https://github.com/Kenshin/simpread/discussions/2347 解决。

现在不太方便打字，余下的建议我明天再回复你。

***

我看你的描述似乎是学生？而且是高三的学生？你们班都在使用简悦吗？

**Comment by zhengqiang-050123** [comment]
只是我给几个同学推荐了，不过用了的同学都说很不错

**Comment by Kenshin** [comment]
> 只是我给几个同学推荐了，不过用了的同学都说很不错

谢谢推荐，我有一些事情想要了解下，如果你看到后，请发邮件到 kenshin@ksria.com

**Comment by Kenshin** [comment]
哈哈，刚发现关于维基百科的问题你之前已经问过一次了 https://github.com/Kenshin/simpread/issues/3238 

我接着回复一下其它问题：

> 简悦缺少打印选项

你可以试试 https://simpread.ksria.cn/plugins/details/Lly3mkuSPz 提供的方案，如果仍无法满足，可以说说详细的需求，我可以单独考虑为此优化。

> 支持多套外观切换

![image](https://user-images.githubusercontent.com/81074/147864346-0853a60c-cbd3-4c56-bcd2-18602a5c3235.png)

这里可以快速调节，但你提到了更大字体的问题，目前可以使用自定样式解决，但有必要的话，我可以再出个插件更方便的调节。

同时，你说的这个思路也不错，相当于一个模板的概念，导入不同的模板对应不同此场景。

> 版面切换并不是个好选项 & 可能出现一行几个字的情况，影响阅读，应加入固定一行字数的

你看看 https://simpread.ksria.cn/plugins/details/noCdz57Mw6 能否解决你的问题，虽然用途不太一样，但也可以试试。

至于你提到的需求，我在考虑下。「固定一行字数」的话，如果版面过小会出现横向滚动条。

> 控制栏的更多（三个点）按钮不支持单击

emmm 简悦 2.2.0.520 加入了对触屏的支持，并且社区也有不少用户在使用，没有出现你说的问题。

> 在视频与文章共存的界面，简悦不加载视频

确实如此，你可以告诉我一些 URL 我看看能否通过适配解决。

**Comment by zhengqiang-050123** [comment]
- 打印的问题
这个插件还是不太好，因为我字调得很大，打印时a4纸上只有几十个字，并且这个插件打印出来的内容因为有版面宽度存在，纸张有些浪费，应该是打印时重新排版，字体，字号等的设置选项与阅读模式不通用。
其他的几个问题都解决了，就是文字和视频夹杂的网页确实比较少，我只是想起来了，具体链接不知道，这个问题优先级可以稍往后放

**Comment by Kenshin** [comment]
> 这个插件还是不太好，因为我字调得很大，打印时a4纸上只有几十个字，并且这个插件打印出来的内容因为有版面宽度存在，纸张有些浪费，应该是打印时重新排版，字体，字号等的设置选项与阅读模式不通用。

你是通过同步助手打印的吗（使用后的效果为自动生成 PDF）？还是通过浏览器自带方式？（使用后的效果为需要手动选择一些内容）

> 就是文字和视频夹杂的网页确实比较少，我只是想起来了，具体链接不知道，这个问题优先级可以稍往后放

okay 你可以随时在这里回复我，关于这个问题的话，你也可以使用聚焦模式。
