### ISSUE TITLE
数学公式没有在深色模式下优化

### ISSUE THREAD

**Issue by Ryan-Wsy** [Kenshin/simpread#3266]
例如知乎的一些数学公式，在深色模式下，普通文本被很好地渲染成了白色，但是数学公式还是黑的，给阅读带来不便

**Comment by Kenshin** [comment]
知乎的 LateX 是图片，所以这是没办法修改的。

后续有好的解决方案我在通知你。

**Comment by Ryan-Wsy** [comment]
谢谢，加油！祝你们团队越来越好！-------- 原始邮件 --------发件人： Kenshin Wang ***@***.***>日期： 2022年1月2日周日 22:33收件人： Kenshin/simpread ***@***.***>抄送： Ryan-Wsy ***@***.***>, Author ***@***.***>主    题： Re: [Kenshin/simpread] 数学公式没有在深色模式下优化 (Issue #3266)

知乎的 LateX 是图片，所以这是没办法修改的。

后续有好的解决方案我在通知你。

**Comment by Kenshin** [comment]
哈哈 🙏

如果觉得简悦不错的话，请帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，**这是对简悦最好的帮助**。  💪

这不是复制粘贴的，而是我手打的。  😏
