### ISSUE TITLE
joker

### ISSUE THREAD

**Issue by jokerisking** [Kenshin/simpread#3267]
加入稍后读后，提示“解析正文失败，可以给我提 Issues ↗如果开启了 内置解析方案 的话，请多刷新几次一般可以解决。”
但是我也没开启过内置解析啊  
以前加入稍后读pmcaff的文章还可以看，今天加入的就解析不成功了

**Comment by Kenshin** [comment]
嗨，给个 URL 看看。

另外，不开启内置解析的话，确实会存在这个情况，最好开启此功能。

**Comment by jokerisking** [comment]
Dear kenshin:
https://coffee.pmcaff.com/article/3200129291068544/pmcaff?utm_source=forum&newwindow=1 
是这个链接，在稍后读打开就这样了。。


| |
JK
|
|
***@***.***
|
签名由网易邮箱大师定制


On 01/3/2022 10:10，Kenshin ***@***.***> wrote：

嗨，给个 URL 看看。

另外，不开启内置解析的话，确实会存在这个情况，最好开启此功能。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kenshin** [comment]
确实如此。

目前最好的解决办法是使用内置解析（安装同步助手）的方案，除此之外暂时没有其他更好的方案。

另外，你之前说这个网站的某些页面没问题，能否也告诉下？

**Comment by jokerisking** [comment]
也是这个网站 ，我添加其他文章页面进入稍后读就可以正常显示，唯独这个页面不行。。。


| |
JK
|
|
***@***.***
|
签名由网易邮箱大师定制


On 01/3/2022 16:43，Kenshin ***@***.***> wrote：

确实如此。

目前最好的解决办法是使用内置解析（安装同步助手）的方案，除此之外暂时没有其他更好的方案。

另外，你之前说这个网站的某些页面没问题，能否也告诉下？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kenshin** [comment]
哈哈，那真的「没办法」了。  😂
