### ISSUE TITLE
文章保存到joplin时图片尺寸会压缩很多，不清楚是bug还是别的原因？

### ISSUE THREAD

**Issue by gexd79** [Kenshin/simpread#3268]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by gexd79** [comment]
补充一下，win 系统，edge浏览器最新版，没品百科网站，长度超长的图片会被压缩。

**Comment by Kenshin** [comment]
嗨，通常是没有这种问题的，但最好给个 URL 看看，个别网站对图片的处理可能有一些其它方案。

**Comment by mingming1248** [comment]
这个问题是joplin导致的，跟剪辑软件没关系，我换了好几个剪辑软件都这样

**Comment by Kenshin** [comment]
@mingming1248 

嗨，谢谢提示，这样的话，我直接关闭 Issues 了  💪  🙏  👍
