### ISSUE TITLE
标题显示异常

### ISSUE THREAD

**Issue by adamweixuan** [Kenshin/simpread#327]
原文链接是 https://mp.weixin.qq.com/s/RDnf637MY0IVgv2NpNVByw,浏览器是 chrome 66.0.3359.181
<img width="1045" alt="image-20180531161337828" src="https://user-images.githubusercontent.com/7525242/40770591-b738ae7a-64ed-11e8-833f-4c8b2b70a9ba.png">
这是什么原因?

**Comment by Kenshin** [comment]
感谢反馈，关联问题 https://github.com/Kenshin/simpread/issues/323
按着上述的操作即可解决。
