### ISSUE TITLE
如果多台设备同步数据，在不使用同步助手的情况下是否只能手动操作？

### ISSUE THREAD

**Issue by baalchina** [Kenshin/simpread#3270]
假设在办公室和家里都用chrome插件的简悦，在办公室将网页加入阅读模式并且做了标注。回到家想继续阅读并标注，是否只能在离开办公室的时候手动同步到同步盘（假设我使用的是坚果云），回到家再同步回来？

因为刚才尝试同步的时候，不小心在坚果上覆盖了，结果发现之前的阅读模式和标注都没了。。。

谢谢！ps，不知在这里提问是否合适，如果不合适烦请关闭。

**Comment by Kenshin** [comment]
嗨，当然在这里提问了，这是简悦唯一的 QA 渠道。 😁 

至于你说的问题：

> 目前是这样的，如果不使用同步助手的话，只能使用手动同步方案。

如果只是轻量级使用简悦的话，手动同步足够了，如果是标注等功能的话，还是建议使用同步助手。

至于你说的覆盖问题，试试在坚果云的历史记录中能否找回来？
