### ISSUE TITLE
印象笔记/Evernote的授权都无法打开

### ISSUE THREAD

**Issue by baalchina** [Kenshin/simpread#3271]
在服务->授权管理里，无论是印象笔记还是evernote都无法打开，点击按钮打开之后右上角有提示，但是没有任何反应：
![image](https://user-images.githubusercontent.com/3983019/147946685-feaf8f57-d7a5-4710-9832-9249a0757c8b.png)

但是其他授权都没问题，都可以弹出一个新窗口进行认证。

系统windows10/chrome 96.0.4664.110。

**Comment by Kenshin** [comment]
嗨，解决方案看这里 https://github.com/Kenshin/simpread/discussions/2791
