### ISSUE TITLE
codeforce 适配问题

### ISSUE THREAD

**Issue by chenboshuo** [Kenshin/simpread#3272]
我做了以下配置
![image](https://user-images.githubusercontent.com/43953268/147999946-33da74d7-c920-4cdd-a312-ff749637b76b.png)

其中标题项我设置为`<div class="title">`,高亮区域我设置为`<div class="problem-statement">`

但是导致阅读模式打不开，
例如
[这个网页](https://codeforces.com/contest/20/problem/A#)
标题位于
```
#pageContent > div.problemindexholder > div.ttypography > div > div.header > div.title
```
正文位于
```
#pageContent > div.problemindexholder > div.ttypography > div
```
按照我配置导致阅读模式无法打开，
请问我的问题在哪里，谢谢关注

**Comment by Kenshin** [comment]
嗨，单纯的说 `https://codeforces.com/contest/20/problem/A#` 这个规则

不应该使用 `https://codeforces.com/*`  正确的适配时

`https://codeforces.com/contest/*/*/*` 或 `https://codeforces.com/contest/20/*/*`

**Comment by chenboshuo** [comment]
配置成功，十分感谢
