### ISSUE TITLE
【userscript】能否再次双击A时自动退出简阅，而非用esc？

### ISSUE THREAD

**Issue by realliyifei** [Kenshin/simpread#3274]
我觉得，双击A-启用-双击A-退出，比较符合通常的习惯。谢谢！

或者提供一个个性化的启用/退出的快捷键功能也成。

**Comment by Kenshin** [comment]
嗨 

ESC 退出不是更方便些？（毕竟就在键盘左上角，左手区很容易使用。

当然，你说的方式确实也符合习惯。
