### ISSUE TITLE
【userscript】目前不支持知乎

### ISSUE THREAD

**Issue by realliyifei** [Kenshin/simpread#3275]
知乎的使用频率还是很高的，我看[站点集市](https://simpread.ksria.cn/sites/)是支持的。请问是最近的bug吗？

**Comment by Kenshin** [comment]
嗨，UserScript（也就是轻阅版）对部分站点的支持不是很好，请使用插件版。

另外轻阅版应该不支持站点集市，同时也只是 1.x 的部分功能。

我关闭这个 Issues 了，有任何问题的话，可以重开它。

**Comment by realliyifei** [comment]
好的，谢谢。我明白轻阅版是阉割版，但知乎文章和微信公众号文章的使用频率还是蛮高的，望有空时能迁移过来。

我目前主力是Safari，而插件版应该还不支持safari吧？不知未来有否支持的打算？

**Comment by Kenshin** [comment]
> 但知乎文章和微信公众号文章的使用频率还是蛮高的

某些页面会阻止一些代码的运行，比如扩展端能运行的页面，UserScript 就不行。

> 我目前主力是Safari，而插件版应该还不支持safari吧？不知未来有否支持的打算？

会有 Safari 版本的。
