### ISSUE TITLE
使用坚果云WEBDAV登录问题

### ISSUE THREAD

**Issue by MusherM** [Kenshin/simpread#3276]
尝试使用坚果云webdav登录，显示登录成功，正在检测授权，就卡在那儿了
阅读issues之后尝试下载json文件本地登录，成功了，只是希望作者修复一下这个webdev登录的问题

**Comment by Kenshin** [comment]
嗨，谢谢提示。

不过，坚果云登陆并没有问题，使用此功能的前提是 [授权登陆](https://github.com/Kenshin/simpread/discussions/1570)

**Comment by MusherM** [comment]
好的 感谢回复

发自我的iPhone
