### ISSUE TITLE
外部链接跳转到的页面无法登录

### ISSUE THREAD

**Issue by liang0802** [Kenshin/simpread#3277]
**请说明发生问题的环境**

@Kenshin  打扰了，但靠我自己实在解决不了了

- 操作系统 ** Windows **

- 浏览器版本 ** Microsoft Edge 96.0.1054.62 (官方内部版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <[请填写你的地址l](https://simpread.pro/@%3Cliang0802%3E/login?redirect=reading/11-Obsidian%20%E9%85%8D%E5%90%88%E7%AE%80%E6%82%A6%E5%AE%9E%E7%8E%B0%E6%96%B9%E4%BE%BF%E7%9A%84%E6%9D%A5%E6%BA%90%E5%BC%95%E7%94%A8%EF%BC%88%E7%BD%91%E9%A1%B5%EF%BC%89%20-%20%E7%9F%A5%E4%B9%8E#id=1641379025953)>

**请描述你的问题**
按照指示设置了官方模板中的第一个模板作为导出为.md时的模板
![image](https://user-images.githubusercontent.com/72696563/148222202-8774d494-3eb5-4f57-81c9-87a00aaf9bcb.png)
在导出的md文件中打开外部链接
![image](https://user-images.githubusercontent.com/72696563/148222864-96f89cad-6161-4e9a-b4ff-9aad78723198.png)
输入密码登陆时显示
![image](https://user-images.githubusercontent.com/72696563/148222932-44c63499-327a-4cf8-a562-33c44f3c0a2b.png)
而当我换用email登陆，输入验证码后并没有成功登录
![image](https://user-images.githubusercontent.com/72696563/148223672-086f3718-81da-422b-8fb3-32bd3687a4d4.png)
而是跳转到了
![image](https://user-images.githubusercontent.com/72696563/148223718-4793a36e-e5d0-4e5a-8b63-f9c5f64e8a53.png)

**Comment by Kenshin** [comment]
嗨，并不存在打扰，这里本来就是 QA 渠道。

至于你的问题，需要看下下面两个教程：

 - [知识库](https://www.yuque.com/kenshin/simpread/lglfy2)
 - [开通 API](https://github.com/Kenshin/simpread/discussions/2757)

根据这两个教程就能解决你的问题。

**Comment by China-liang** [comment]
根据这两个教程配置完成后，外部链接还是无法打开，显示画面如下
![image](https://user-images.githubusercontent.com/72696563/148344327-51124942-e75e-49f8-8834-9a0146c8e7a4.png)

**Comment by Kenshin** [comment]
进入开放平台，然后根据下图所示设置

![image](https://user-images.githubusercontent.com/81074/148344732-95b94a4c-3a32-4e4e-9f61-aaad13581a73.png)

**Comment by China-liang** [comment]
![image](https://user-images.githubusercontent.com/72696563/148346491-001a3fc6-b477-486d-865c-f500b22166e4.png)
这个我打开了

**Comment by Kenshin** [comment]
emmm 

把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3277

**Comment by liang0802** [comment]
今天我又看了遍文档，发现我之前导出路径设置错了。
实在不好意思m(._.)m

**Comment by Kenshin** [comment]
哈哈，没事的。（乌龙见多了，已见怪不怪了。 😂 

不过，你要是能在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

我就更爽了。
