### ISSUE TITLE
mac上启用同步助手导出的PDF图不可见，正文为白底浅色字体，阅读不方便。

### ISSUE THREAD

**Issue by goodniuniu** [Kenshin/simpread#3278]
- 操作系统 **MacOS 10.15.7**

- 浏览器版本 **Version 96.0.4664.110 (Official Build) (x86_64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 
阅读的页面链接为：https://mp.weixin.qq.com/s?__biz=MzAxNTY0NjEzNg==&mid=2247486064&idx=1&sn=c1748bebf6eecf2550089b375a83cb56&chksm=9b81a6a7acf62fb1bab4fead7ff9d34c7822dc697f77ea690bfd7af0fa0118b3f1e24fefcf47&mpshare=1&scene=1&srcid=0901cIa5tI4TfmnpD79bazoy&sharer_sharetime=1598954036094&sharer_shareid=7125c06b0fe98b972a022497973e5fc5&key=8723f2e63c89806b4bb9253f1b1bd350aa4bba36353d22cddc9b6e82c3b62ac360fd5260fd07888d26b3863f6211fdebd8a9e869a5b28d0b27241962adce545ca0893befe857b7fad6b7bf14836531321eca1aae12ce64b617ddc07d2bb9d011913a40f62e2f3083054a131759864f3edfee561fd55b81c40263765e1b557247&ascene=0&uin=MjY2OTI1MDMyOQ%3D%3D&devicetype=iMac+MacBookAir6%2C1+OSX+OSX+10.13.4+build(17E199)&version=11020012&lang=zh_CN&exportkey=A0WWirVizhrJaraw2Iby884%3D&pass_ticket=vEMkZLwRhfrpRwnmL6up28SX%2Bn0AGvjKmws4IDtNv6wfIORF5I1rmtw2oIyewfaZ&wx_header=0

**请描述你的问题**

在mac上启用同步助手导出的PDF图不可见，正文为白底浅色字体，阅读不方便。请协助解决，谢谢。

**截图**
![image](https://user-images.githubusercontent.com/5173986/148237107-9f5f8016-a7b3-4a45-9d1d-d2edf1f8beae.png)

**Comment by goodniuniu** [comment]
研究了一下，可以通过调整阅读模式中的“主题颜色”解决白底浅色的问题了，但是pdf中仍是不能抓到图片（多次尝试过，也分了不同的网页，如这篇https://zhuanlan.zhihu.com/p/281085595

![image](https://user-images.githubusercontent.com/5173986/148243063-17698c48-3bd9-4112-bb2d-897a079774b9.png)

**Comment by Kenshin** [comment]
> 正文为白底浅色字体，阅读不方便

是的，在深色主题下确实存在这个情况。（你已自救成功

> 但是pdf中仍是不能抓到图片

如果使用同步助手的话，请开启下面的选项

![image](https://user-images.githubusercontent.com/81074/148316342-149e1714-900f-49f1-99c3-11909dcd37a4.png)

**Comment by goodniuniu** [comment]
已经开启了，还是未能解决，是还有什么地方配置对的缘故吗？测试页面为https://mp.weixin.qq.com/s?src=11&timestamp=1641442260&ver=3541&signature=t0Hc7qF5PH-ewA3yRB9XyETGJ*wklMFuftzRwkkPDP0R695UtyDplitQlxe*BAytaRyKLlhiMZBsVbEskJLQWnIzpgrd6Ct9aYzee1r3dvIe9nczUmqPDy8Ta7uvV2d5&new=1
使用保存到PNG是可以读到图片的，PDF还是如下：
PDF：
![image](https://user-images.githubusercontent.com/5173986/148337550-76a8bc44-7e62-4942-a1f2-c8f5a9cb89ba.png)
PNG：
![simpread-芒格持仓阿里翻倍，什么信号？](https://user-images.githubusercontent.com/5173986/148337666-8bc9e46b-0610-4140-8dd9-d52883d517f8.png)

**Comment by Kenshin** [comment]
我这边是没问题的，你可以试试不同的公众号，看看是否每个都这样？


[芒格持仓阿里翻倍，什么信号？.pdf](https://github.com/Kenshin/simpread/files/7820068/default.pdf)

**Comment by goodniuniu** [comment]
谢谢反馈，我再试一试。请问基于同步助手的机制是什么呢？和本地proxy有关系吗？但是也试过把所有的本地proxy都关掉了。。。

**Comment by Kenshin** [comment]
> 请问基于同步助手的机制是什么呢？

这个很难一两句话解释清楚，不过跟你的网速 / PC 性能有些关系，但只要不是配置太差的话，是 100% 没问题的。

> 和本地proxy有关系吗？

跟我让你开启的这个功能有关系的

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
