### ISSUE TITLE
站点编辑器不起作用

### ISSUE THREAD

**Issue by HEI201** [Kenshin/simpread#328]
有些网站simpread没有适配的，我在站点编辑器添加了规则，刷新后并没有起作用。这个是bug还是我操作不当？

**Comment by Kenshin** [comment]
估计是操作不当…
建议方便的话，把你新建的站点贴出来。

另外，在选项 → 高级设定 → 站点管理器
打开后，是否能看到你新建的站？

**Comment by HEI201** [comment]
我尝试了一下其他的网站，可以了。是我的操作不当。有些网站的目录结构太复杂了，那个域名的部分很难填正确。

**Comment by Kenshin** [comment]
确实有这样的弊端，主要是 minimatch 也不太好调试。
可以加强部分的调试方式…
