### ISSUE TITLE
关于「沙拉查词」的「生词本」功能 无法正常显示问题

### ISSUE THREAD

**Issue by MJhin11** [Kenshin/simpread#3285]
**全屏状态下的阅读/聚焦模式**

- 操作系统 ** Windows **

- 浏览器版本 **Edge 97.0.1072.55 (官方内部版本) (64 位)**

- 简悦版本 **2.0.0.520**

**使用「沙拉查词」的" 添加进入「生词本」" 功能时，它的那个编辑 生词 界面会卡在源页面，不会呈现于「简悦」之上。如果要使用该功能，则需要退出阅读模式，回到源页面进行操作。繁琐了些许，望有办法改进**

![红箭头所指功能](https://user-images.githubusercontent.com/88275721/148537028-8fe1f0e5-a1ff-44a6-bbfd-c6b5e0ef4df3.png)
![全屏后状态](https://user-images.githubusercontent.com/88275721/148537042-79ee03f2-371f-4049-af96-1dc2e56f1d7e.png)

**Comment by MJhin11** [comment]
偶然间已解决。

设置 「独立查词窗口」快捷键即可

**Comment by Kenshin** [comment]
哈哈，恭喜自救成功，我关闭这个 Issues 了。

**Comment by YELLOWHOMEIN** [comment]
> 

您好，具体怎么设置呢？没有找到，不好意思刚用沙拉词典还不熟。

**Comment by MJhin11** [comment]
> > 
> 
> 您好，具体怎么设置呢？没有找到，不好意思刚用沙拉词典还不熟。


路径分三步走，以下为图例。

Tips:在第三步有两个选择，按「个人需求」设置即可

- 3.1适合**广搜词汇**

- 3.2适合**精准翻译**

首先，打开并找到该扩展-进入「扩展选项」后页面，随即找到图中关键点：
![屏2_LI](https://user-images.githubusercontent.com/88275721/151566959-e9322345-84ca-4951-a3d0-2c34980787d7.jpg)


最后就Okay啦~
![解决办法1_LI (2)](https://user-images.githubusercontent.com/88275721/151567405-cac4c6df-5588-4b3c-a5e1-363b2afefe39.jpg)

**Comment by Kenshin** [comment]
@MJhin11 

哈哈，谢谢解答，我考虑把这个 issue 升级到知识库里面的内容。 💪

**Comment by Kenshin** [comment]
各位，上述内容已经记录到 https://github.com/Kenshin/simpread/discussions/3366
