### ISSUE TITLE
求助：进入Live Editor后，没有浮动的摘录看板 

### ISSUE THREAD

**Issue by ZackWFC** [Kenshin/simpread#3291]
大佬你好。
最近在进入Live Editor后，没有浮动的摘录板 ，同时选中文字并点击工具栏倒数第2项（也就是摘录到浮动看板）后，浮动摘录看板也没有出现，同时网页就死机了，再过一会会提示网页无响应，请问我应该怎么解决呢，谢谢！
![image](https://user-images.githubusercontent.com/18433218/148689678-ba447b80-eef0-4f63-8709-c224fe3bd252.png)

**Comment by Kenshin** [comment]
嗨，看起来应该是某些原因导致错误导致的。

你可以这样测试下：

1. **隐身模式下仅使用简悦的方式**  用以排除其它扩展的干扰
2. 换个正常点的页面 URL e.g. https://sspai.com/post/69972

另外，这个问题是每个网页都存在？还是个例？

**Comment by ZackWFC** [comment]
我检查了一下，发现只有知乎的网页有这种情况。然后我用您推荐的隐身模式排查了一下，发现可能是与TamperMonkey里面的知乎增强脚本发生了冲突。我关掉以后就正常了。
谢谢！

**Comment by Kenshin** [comment]
哈哈，没问题就好，我关闭这个 Issues 了。
