### ISSUE TITLE
带斜杠的 网页，下载出现错误

### ISSUE THREAD

**Issue by dwSun** [Kenshin/simpread#3293]
https://www.cnblogs.com/sandwichnlp/p/11612596.html

网站标题带斜杠，输出的离线 markdown，文件存储的时候，会出现多级目录，同时图片下载无法进行。

**Comment by Kenshin** [comment]
嗨，是使用了同步助手吧？你可以试试 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，专门解决这个问题的。

**Comment by dwSun** [comment]
解决了，谢谢

**Comment by Kenshin** [comment]
搞定就好，你不小心又重开这个 Issues 了~

**Comment by dwSun** [comment]
> 嗨，是使用了同步助手吧？你可以试试 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，专门解决这个问题的。

文件名问题倒是解决了，不过图片还是有问题，下载不了。
我这里用的是离线 markdown。

**Comment by Kenshin** [comment]
> 文件名问题倒是解决了，不过图片还是有问题，下载不了。

URL 给我看下。

**Comment by dwSun** [comment]
https://www.cnblogs.com/sandwichnlp/p/11612596.html

这个，离线markdown 图片下载之后都是一串 base64编码

**Comment by Kenshin** [comment]
离线 Markdown 的图片本就是一串 base64，另外我看了下载的 base64，应该是这个页面的图片格式有问题造成的。

![image](https://user-images.githubusercontent.com/81074/149463000-7c6ceb1b-b07d-4068-b47b-f151ac912984.png)
