### ISSUE TITLE
同步助手能否支持下 Linux？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3297]
如果是基于electron技术，能否支持下linux呢？本人长期使用 archlinux，浏览器是 firefox
目前在用obsidian，很想使用 simpread pro版，但没找到有支持

_Originally posted by @amitbha in https://github.com/Kenshin/simpread/discussions/2754#discussioncomment-1944518_

**Comment by Kenshin** [comment]
@amitbha 

嗨，我帮你把问题转移到这里了。

***

因为某些 Linux 用户说 Electron 会非常影响性能，所以这个事情一直在 Delay 中。

但即便这样，简悦暂时也不支持 Firefox  😂

**Comment by amitbha** [comment]
我还装了 ms edge，这个支持吧？

**Comment by Kenshin** [comment]
> vscode、obsidian 都是基于 electron 的，性能都还不错。资源占用虽然会大点，但对于现代电脑不算什么问题 我还装了 ms edge，这个支持吧？

okay 我会考虑下~

PS：Edge 当然支持了。

PPS：你有 Telegram 吗？如有必要能否帮忙做一些测试？

**Comment by amitbha** [comment]
没用过电报，只用过 tox，因为没朋友，已弃

**Comment by amitbha** [comment]
测试没有问题

**Comment by Kenshin** [comment]
okay 那就等需要的时候在通过这里联络你。

**Comment by Kenshin** [comment]
嗨，各位。

同步助手发布了命令行版本，可支持 Linux，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3704)，目前此版本为内测版，有任何问题请 [汇总到这里](https://github.com/Kenshin/simpread/discussions/3704#discussioncomment-2542653)。

PS：等正式版发布后，我还会通过这里告诉大家。

**Comment by Kenshin** [comment]
嗨，[同步助手 · 命令行](https://github.com/Kenshin/simpread/discussions/3704) 版正式发布  🎉 

![Sync CLI](https://user-images.githubusercontent.com/81074/163512494-3c41c6c3-2158-49f8-9425-27637a3303c8.png)

在使用时如有问题，[请提 Issues](https://github.com/Kenshin/simpread/issues/3740)

**Comment by amitbha** [comment]
点赞 👍 
不过没说具体使用步骤。是在后台运行，为浏览器扩展提供专业版功能吗？

**Comment by Kenshin** [comment]
> 点赞 👍 不过没说具体使用步骤。是在后台运行，为浏览器扩展提供专业版功能吗？

可以后台运行，当然是高级账户功能，给你的链接里面有详细说明 https://github.com/Kenshin/simpread/discussions/3704

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# Linux 版来啦

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
