### ISSUE TITLE
是否考虑以下几个增强阅读体验的配置

### ISSUE THREAD

**Issue by archonwang** [Kenshin/simpread#33]
1. 字间距配置
2. 行间距配置
3. 段落间距配置

**Comment by Kenshin** [comment]
感谢建议 :+1:
之前有过类似的考虑，但只是想通过 `自定义主题` 的方式呈现。
具体是根据主题自定义？还是全局自定义？暂时没有想好...  :sob:

**Comment by archonwang** [comment]
@Kenshin 
实际上还有一些配置
比如：
自定义样式
阅读背景色配置
自动在数字、英文和汉字连接位置添加空格
自动缩进
等等。。。

近期有个项目需要用到阅读体验设计，目前正在同步整理类似阅读体验方面的内容，参考了您的产品，有很多的灵感，感谢~~~

**Comment by Kenshin** [comment]
数字，汉子空格等，我用 pangu.js 很强大；
自定义主题下个版本发布；
配色都是我找的，自己感觉舒服而已；
自动缩进还未研究，如果有此研究可以分享一下；
中文排版还参考了 http://typo.sofi.sh/

请问你的项目是自己，还是公司的？如果感兴趣的话，有时间的话，可以一起做简悦。

**Comment by archonwang** [comment]
@Kenshin ，

公司的项目，在进行产品设计时考虑加入了增强阅读体验的设计。

自己擅长的是测试、质量管理、项目管理和产品设计，很少会编码——基本上忘得差不多了。

看到你的产品，感觉做得很用心，体验方面比一般的阅读级产品更深入一些。个人比较喜欢。so关注了。

如果不嫌我的技术烂，可以一起参与这个产品做一些我力所能及的事情。谢了~~

**Comment by Kenshin** [comment]
哈，太好了。
希望能在阅读体验对简悦上有所帮助，这就很棒了。
我目前在休假，等回去的时候再联络你。 😄

**Comment by archonwang** [comment]
@Kenshin , OK

**Comment by Kenshin** [comment]
我在 Telegram 上建立了一个群 https://t.me/simpread 有时间可以加下。 :smile:

**Comment by Kenshin** [comment]
@archonwang 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

`自定义样式`中包含了很多关于中文设定的选项 此 issues 将关闭~

**Comment by archonwang** [comment]
@Kenshin 
收到，这一版的功能丰富很多了。相信在阅读体验这层上会有较大的该善。
谢谢。
