### ISSUE TITLE
简悦同步助手将文章保存到稍后读可能导致 Windows 11 系统重启

### ISSUE THREAD

**Issue by shyrz** [Kenshin/simpread#3301]
**请说明发生问题的环境**

- 操作系统 **Windows 11**

- 浏览器版本 **Chrome 98.0.4758.9 x64 dev**

- 简悦版本 **2.2.0**

- 发生问题的地址

**请描述你的问题**

最近用简悦同步助手将文章保存到稍后读可能会导致 Windows 11 系统重启，不知道要怎么 debug😅

- 点击保存后，设置好的自动化任务没有触发
- 点击保存后，过一会儿（几秒到一两分钟不等）系统卡住重启

**Comment by binsee** [comment]
已经通过查看系统日志，排除简悦问题，疑似电脑系统本身问题，因为存在各种软件、驱动、系统、磁盘报错。

**Comment by Kenshin** [comment]
@binsee 

谢大神帮忙调查。

@shyrz 

自动化的问题我在这里再发一次 https://github.com/Kenshin/simpread/discussions/2362

PS：很巧合，这个链接也是 @binsee  提供的。 😉

因为不是简悦的问题，且调查清楚了，我关闭这个 Issues 了。
