### ISSUE TITLE
插件无法下载

### ISSUE THREAD

**Issue by zdshq** [Kenshin/simpread#3304]
插件下载一直停留在下载页面  用的是Android平板

**Comment by Kenshin** [comment]
嗨，Android 平板（一般是 Kiwi Browser）上不支持使用插件，你可以在 PC 的扩展端导入插件，然后「同步」到 Android 平板。

然后使用下图的方式解决

![image](https://user-images.githubusercontent.com/81074/149120593-e965b4cd-7913-4566-8c09-93ac095dc1b9.png)

**Comment by Kenshin** [comment]
关于 Kiwi Browser 的使用说明可以看看 https://zhuanlan.zhihu.com/p/415622477
