### ISSUE TITLE
可以通过Raindrop.io标记最喜爱的，自动导出Markdown到Obsidian么？求助

### ISSUE THREAD

**Issue by FreakLimo** [Kenshin/simpread#3310]
RT

**Comment by Kenshin** [comment]
哈哈，首先 Raindrop.io 是个「在线服务」，而 Obsidian 是个「本地服务」，所以不可能存在这种流程，但可以折中下。

1. 通过 Raindrop.io 标记 → 简悦 API → 自动生成快照到本地。

2. 在简悦中导入 Obsidain，这里是 [各种方案](https://github.com/Kenshin/simpread/discussions?discussions_q=obsidian)
