### ISSUE TITLE
关于高级账户自动化配置问题

### ISSUE THREAD

**Issue by NECONIHAO** [Kenshin/simpread#3312]
如题，我只是一个简悦新手，我想要标注后自动发给我的邮箱一封邮件，但这貌似有点困难，因为我还有其他几个自动化，当我仅仅划过一个句子”标注“，简悦就会自动完成我后面的所有自动化，包括发送到邮箱，发送到有道云笔记、离线图片、html...但我仅仅希望发送到邮箱。其他的几个自动化我想 手动 添加到稍后读才触发。
不知道我哪里配置有问题，希望好心人给我一份你们配置的例子。
![0K`9M~H~ODUL E_UZG2O1FX](https://user-images.githubusercontent.com/97306577/149583109-de03edf6-62b3-45d3-af4d-8ac57bf63891.png)

另外，我有使用同步助手，配置到处文件是链接的坚果云的简悦文件夹，不知道是不是这里有问题。
![ZCZF Y@$_N(0`FX ZH}NFZV](https://user-images.githubusercontent.com/97306577/149583805-ee96460d-7f3e-40d1-8a12-b7cc4725dea6.png)
![T0Z %@1CH1(5PI 30VZ2_OR](https://user-images.githubusercontent.com/97306577/149583867-f6d65eb5-dfb1-47a7-9edf-2115dbc941c8.png)

**Comment by Kenshin** [comment]
嗨 https://github.com/Kenshin/simpread/issues/3313 第二个问题我放到这里回复了，当你看完下面的内容，自然第二个问题也就回复你了。

***

> 标注按下图所示设置即可。

![image](https://user-images.githubusercontent.com/81074/149609115-dbacc9b0-1b73-44e2-81b6-92ce260808a3.png)

> 简悦就会自动完成我后面的所有自动化，包括发送到邮箱，发送到有道云笔记、离线图片、html

你的自动化设置是没问题的

![image](https://user-images.githubusercontent.com/81074/149609170-2fafdd67-323b-4bf5-917d-343e2242f129.png)

另外并不会出现你说的问题，但有一类情况可能会出现你说的情况：

当前的 URL 不是稍后读，而是正常的阅读模式，当你在第一次「画线」（标注）时，会触发稍后读。（这个现象会让你误以为是标注）

你需要做的是：

1. 首先，通过快捷键 <kbd>d d</kbd> 加入稍后读
2. 然后，再标注

这时，再标注的内容会发送到你的邮件，但这里还有个问题：**你标注一次就发送邮件一次**。

所以，最好的方式是：当标注完毕后，再通过下图方式发送 Email

![image](https://user-images.githubusercontent.com/81074/149609305-fa5ab88f-f3c8-427d-8260-76b7f02e24c9.png)

**Comment by NECONIHAO** [comment]
好的，大概知道了。

**Comment by Kenshin** [comment]
okay 那我关闭这个 Issues 了，有问题你再随时开启它。
