### ISSUE TITLE
关于稍后读问题

### ISSUE THREAD

**Issue by NECONIHAO** [Kenshin/simpread#3313]
进入稍后读后，有阅读模式和标注模式，当我选择阅读模式后，划过句子，依然会进行标注，但我没有看见关闭的选项，仅有一个【关闭连续标注】可我仅仅想进行复制等操作。

另外，希望可以进行多个标注后出现【完成】按钮才算结束一次操作，现在的模式，标注自动化发送邮件保存等，会只能发送标注一句话的版本，后面进行的标注不会再发送（理解再发送邮件就太多了）

**Comment by Kenshin** [comment]
嗨，看下面的回复

> 入稍后读后，有阅读模式和标注模式，当我选择阅读模式后，划过句子，依然会进行标注，但我没有看见关闭的选项，仅有一个【关闭连续标注】可我仅仅想进行复制等操作。

通过下图所示的 icon 关闭它就可以正常的使用复制功能

![image](https://user-images.githubusercontent.com/81074/149605183-8b1fe43a-d361-469b-b266-3f2d81ad5f0f.png)

> 标注自动化发送邮件保存等

这个问题应该跟  https://github.com/Kenshin/simpread/issues/3312 是一样的，我统一在 https://github.com/Kenshin/simpread/issues/3312 回复。
