### ISSUE TITLE
关于同步助手的一些疑问和不成熟建议

### ISSUE THREAD

**Issue by baalchina** [Kenshin/simpread#3314]
先说下我使用简悦的主要场景：
1、会在不同设备上阅读文章，并且做标记，希望标记能在不同设备间同步。
2、已经安装了同步助手，坚果云客户端

目前对于同步助手的使用有点困惑在于，我在新设备上老是会覆盖之前的配置，造成好不容易标记好的内容没了....

我的操作大概是，在电脑1和2上同步助手都配置成功了，虽然中间丢了点数据但是好在不多。我发现当我有新标记的时候，坚果云程序会提示我simplereader_config.json有变化，这没问题，至少我知道我的数据被同步到（坚果云的）服务器端了。

然后今天一台新电脑3，因为浏览器插件同步的原因所以默认简悦插件已经装好了，我想装个同步助手，按照正常配置配置好，点击覆盖配置文件，发现之前在1、2电脑上的稍后读和标注都没了。。。我确认我仔细看了说明，选择的是从同步助手覆盖浏览器配置---如果我没理解错的话，应该就是把之前1、2电脑上的配置覆盖到我的新3号电脑。并且我打开稍后读，发现之前至少应该有2个的稍后读也不见了。。。可为损失“惨重”。。。。

说了这么多，提两个意见，这也是简悦我现在不太敢在多台机器上用的原因：

第一，所有的同步的配置文件是否就一个simplereader_config.json？包括稍后读、标注？不考虑大小、效率的问题，这样感觉也太不安全了，一不小心覆盖了整个数据都没了，尤其稍后读、标注这些。可否将稍后读、标注以独立文件形式来处理？这样即使数据覆盖、冲突，也不会全部丢失。例如一个url一个文件来处理。或者有其他更方便高效地方式也可以。

第二，同步的逻辑略显复杂。可能是我没仔细看文档，手动同步，同步助手，坚果云，webdav，一不小心就造成数据覆盖丢失。可否优化下逻辑？并且最重要的，如果发现不一致，一定要提示用户？比如，“发现服务器上的配置文件更新，是否要覆盖？”

一点浅薄的建议，还望考虑！简悦是非常不错的软件，目前对于个人来说，可能最大的缺陷就是上手稍微复杂了点。。。

**Comment by Kenshin** [comment]
嗨，谢谢建议，我一一回复下。

> 丢失 `simpread_config.json` 的解决方案

看这里 https://github.com/Kenshin/simpread/discussions/3165

> 多设备使用简悦（以及同步助手）的方案

看这里 https://www.yuque.com/kenshin/simpread/dgmm5q 

> 所有的同步的配置文件是否就一个simplereader_config.json 等问题。

会考虑将配置文件与数据文件分来，但目前这么做也有好处：这个文件就像你的账户一样，方法转移和「携带」。
至于数据的问题，以后确实会区分：配置数据与稍后读（标注）数据。

> 多台机器上用的原因

或许你可能没理解简悦的同步机制，可以粗略的看下 https://www.yuque.com/kenshin/simpread/yvowrx 就明白了，其实很简单。

### 最后

> 只要使用坚果云，并每次操作都开着坚果云 + 同步助手的情况下，就不会存在丢失配置文件的问题，可以使用坚果云的历史记录功能。

同样，坚果云比自建服务的优势可以看 https://www.yuque.com/kenshin/simpread/wavq29 的描述。

### 一个教程

你可以在 https://www.yuque.com/kenshin/simpread 看到我整理的全部关于简悦的教程。（这些教程并不是每个人都需要做，按需使用即可）
