### ISSUE TITLE
自动同步无法开启？

### ISSUE THREAD

**Issue by baalchina** [Kenshin/simpread#3315]
Windows 11+chrome 97，已按装同步助手，高级账户。

已知:
1、在设置里验证同步助手提示已绑定无需重复绑定；
2、点击启用自动同步右上角弹出提示已启用；
3、然后无论点不点下面的通过助手覆盖本地文件，都提示成功没有变化；
4、此时上面的同步方式仍然显示手动同步，但时间显示的是同步盘（坚果云）同步到本地的配置文件时间
5、但是重新打开浏览器之后，显示同步方式仍然是手动同步，做任何配置操作，都发现没有自动更新本地的simplereader_config.json文件。

请问如何排查呢？谢谢。

**Comment by Kenshin** [comment]
嗨，看这里的解决方案 https://github.com/Kenshin/simpread/discussions/2011

**Comment by baalchina** [comment]
> 嗨，看这里的解决方案 #2011

hi，不是助手没启动，是chrome插件里的自动同步无法启用。

我刚才测试了一下似乎可以了，就是打开chrome，然后启用自动同步，不要点击下面的两个覆盖配置文件，并且在自动提示的增强导出里开启几个功能，再打开chrome就可以了。不知道是哪个操作生效了。。。

**Comment by Kenshin** [comment]
> 我刚才测试了一下似乎可以了，就是打开chrome，然后启用自动同步

选项页开启 **自动同步** 后，需要覆盖（看下图）

![image](https://user-images.githubusercontent.com/81074/149617945-a33e012e-19ed-4d52-80ef-fe498fb5f1a4.png)

关于 **自动同步** 的使用步骤，可以 [看这里](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5)。
