### ISSUE TITLE
用户体验——“本文由 简悦 SimpRead 转码

### ISSUE THREAD

**Issue by helberg1984** [Kenshin/simpread#3318]
首先，我对开发者表示感谢，一个好的工具需要创造者付出很多精力和汗水，这也是我很早付费支持的原因，虽然并不算贵。
这工具一直吃灰，最近开始有需求，结果发现每次转码出来都会在文章前面挂上一条广告，本文由 简悦 SimpRead 转码， 原文地址www.baidu.com~
当然，你们可以说是版权，可以说是发展需要，但是我觉得好带你们尊重一下用户体验的话，就应该早早把转码决定权交给用户。真正好的作品应该是一切从体验出发，而不是只在乎自己的恶趣味。
我看到开发者以往回复说在markdown格式下喜欢把这个广告挂在头上，因为那样他觉得好看
我可以表示自己的鄙视吗？
你开发作品是给你自己用的吗？
用个产品，让人感觉是被你绑架了一样，这种体验很差劲！

**Comment by Kenshin** [comment]
下个版本或再下个版本会有自定义 Markdown 样式的功能。
