### ISSUE TITLE
自定义标题无法保存

### ISSUE THREAD

**Issue by gukejing** [Kenshin/simpread#3320]
正在配置稍后读，需要自定义标题格式，按照要求输入{{id}}{{title}}，却没有保存，里面空空如也。刷新重新输入，只保留了{{id}}。

**Comment by gukejing** [comment]
另外发现保存本地html文件后，id不出现，只保留了网页的标题

**Comment by gukejing** [comment]
刚才莫名就都好了，也保存了好几个网页在本地，能从本地载入。重新启动浏览器，一页回到解放前

**Comment by Kenshin** [comment]
转移到 https://github.com/Kenshin/simpread/issues/3227
