### ISSUE TITLE
产生离线html文件无编号，导致稍后读无法从本地读取

### ISSUE THREAD

**Issue by gukejing** [Kenshin/simpread#3322]
按照 #https://github.com/Kenshin/simpread/discussions/2146 配置好，一直发现无法产生带有编号的离线html文件，尝试了文件有
[https://mp.weixin.qq.com/s/lK5gB1K3ZqXXt14sWuvHfg](url)
[https://www.weihengag.com/home/article/detail/id/12378.html](url)
[https://www.merriam-webster.com/words-at-play/sympathy-empathy-difference](url)

后来尝试了
[https://baike.baidu.com/item/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E5%BE%BD/639583#:~:text=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E5%BE%BD%E4%B8%8A%E7%9A%84%E5%9B%BE%E6%A1%88%E5%9D%87%E6%9C%89%E5%85%B6%E8%B1%A1%E5%BE%81%E6%84%8F%E4%B9%89%E3%80%82%20%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E7%9A%84%E5%9B%BD%E5%BE%BD%E8%B1%A1%E5%BE%81%E7%9D%80%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E8%87%AA%E2%80%9C%E4%BA%94%E5%9B%9B%E2%80%9D%E8%BF%90%E5%8A%A8%E4%BB%A5%E6%9D%A5%E7%9A%84%E6%96%B0%E6%B0%91%E4%B8%BB%E4%B8%BB%E4%B9%89%E9%9D%A9%E5%91%BD%E6%96%97%E4%BA%89%E5%92%8C%E5%B7%A5%E4%BA%BA%E9%98%B6%E7%BA%A7%E9%A2%86%E5%AF%BC%E7%9A%84%E4%BB%A5%20%E5%B7%A5%E5%86%9C%E8%81%94%E7%9B%9F,%E4%B8%BA%E5%9F%BA%E7%A1%80%E7%9A%84%20%E4%BA%BA%E6%B0%91%E6%B0%91%E4%B8%BB%E4%B8%93%E6%94%BF%20%E7%9A%84%E6%96%B0%E4%B8%AD%E5%9B%BD%E7%9A%84%E8%AF%9E%E7%94%9F%E3%80%82](url)
而且[https://www.merriam-webster.com/words-at-play/sympathy-empathy-difference](url)也可以了，很是奇怪。

**Comment by Kenshin** [comment]
转移到 https://github.com/Kenshin/simpread/issues/3227
