### ISSUE TITLE
不知道是否bug：标注功能的备注文字无法输入空格

### ISSUE THREAD

**Issue by baalchina** [Kenshin/simpread#3324]
大致就是箭头所指位置：

![image](https://user-images.githubusercontent.com/3983019/149722742-7e6661de-d373-4f65-9539-ba25febbe6e0.png)

这里的文字无法输入空格。

版本：WIndows 10/Chrome  97.0.4692.71

Thanks.

**Comment by Kenshin** [comment]
emmm 没有问题，看下图

![image](https://user-images.githubusercontent.com/81074/149723423-1c1a9cf1-6088-49ba-9a28-0365b8ecc187.png)

**Comment by baalchina** [comment]
![image](https://user-images.githubusercontent.com/3983019/149726296-2a371e83-1c5e-4c12-af0b-3693b0b44a0e.png)
不能呢。。。

你好，无论在“你”前，”你”后，还是最后的“好”之后，都无法打空格。

**Comment by Kenshin** [comment]
> 发现了，我这个是极客时间无法插入空格，但时换了别的网站就ok了。

原来如此...  😂 

PS：你可以在稍后读中再修改，我关闭这个 Issues 了~
