### ISSUE TITLE
【稍后读】导航栏【灵感回顾】功能疑问

### ISSUE THREAD

**Issue by mtuwei** [Kenshin/simpread#3325]
**环境**

- 操作系统：Win10
- 浏览器版本： Edge 95.0.1020.40；Chrome 95.0.4638.69
- 简悦版本 2.2.0

**问题**

> 网页添加了‘br’标签，但【导航栏】中【灵感回顾】右侧无提示信息，点击【灵感回顾】，【列表栏】显示为空

**截图**

> 点击'br'标签，网页在【列表栏】正常显示
![image](https://user-images.githubusercontent.com/32591958/149789482-8d8f53ec-cec2-427b-856b-5dee6c3e55ef.png)

> 【导航栏】中【灵感回顾】右侧无提示信息，点击【灵感回顾】，列表栏显示为空
![image](https://user-images.githubusercontent.com/32591958/149788943-cb44c33b-7bd6-4dc8-a2da-c4ee23446dfd.png)

**Comment by mtuwei** [comment]
查了最新的帮助文档，发现改成了'dr'。

**Comment by Kenshin** [comment]
哈哈，是的。

是 `d r` 而不是 `b r` 请问哪里还有说明是 `b r` 我需要更新下。

PS：这个功能是跟 个人中心 的灵感回顾一起使用的，这个功能属于 beta 版，暂时没对外宣传用法，过阵子会「回炉」改造下。

**Comment by Miaoyifei-mz** [comment]
@Kenshin [少数派介绍2.2这篇文章](https://sspai.com/post/67074)里还是b r

**Comment by Miaoyifei-mz** [comment]
@Kenshin 还想再提一个小小的建议：现在点击标签列表，只能跳转到对应的文章。如果可以跳转到对应的批注就更好啦。

**Comment by Kenshin** [comment]
> @Kenshin [少数派介绍2.2这篇文章](https://sspai.com/post/67074)里还是b r

收到，但我没法修改了...  😂 

> 现在点击标签列表，只能跳转到对应的文章。如果可以跳转到对应的批注就更好啦。

你是说搜索得到的内容？还是什么？

**Comment by Miaoyifei-mz** [comment]
@Kenshin 就是如果给某条批注加标签的话，点击标签只能跳转到这条批注对应的文章，不能直接显示这条批注。

**Comment by Kenshin** [comment]
> @Kenshin 就是如果给某条批注加标签的话，点击标签只能跳转到这条批注对应的文章，不能直接显示这条批注。

应该是可以的，建议最好截个图给我看看。
