### ISSUE TITLE
保存的html&发送的邮件图片不显示（仅限酷安）

### ISSUE THREAD

**Issue by NECONIHAO** [Kenshin/simpread#3329]
先说明，暂时只发现 酷安 出现此状况，之前的其他网址导出的邮件都有图片。
![image](https://user-images.githubusercontent.com/97306577/149960253-62462a55-d0ff-4001-8377-8654119f2715.png)
在阅读模式里的时候显示没有问题
![JTZYJQJQ6HM~EY60F3SH7HQ](https://user-images.githubusercontent.com/97306577/149960371-4da85ba1-01a1-4662-88fa-44e173d4faef.png)

发送的邮件是这样
![image](https://user-images.githubusercontent.com/97306577/149960509-b101b89d-11b7-4ada-9ce8-52a581fba090.png)
这个图片代理开启了的

**Comment by Kenshin** [comment]
> 暂时只发现 酷安 出现此状况

某些网站会阻止将图片转换为字符串，所以可能是这个问题造成的，建议给我个 URL。

只是个例的话，没有「修复的必要」。

PS：发送 Email 不需要离线 HTML，你可以把自动化的顺序调整下，先发送 Email 再离线 HTML。

**Comment by NECONIHAO** [comment]
网址是https://www.coolapk.com/feed/32883179?shareKey=ZjEyYjQzMGFlMTk5NjFlNjAwMGU~&shareUid=2370903&shareFrom=com.coolapk.app_4.2

麻烦那不用修复了吧，这个网站本身也对网页版做了限制，必须手机分享才能打开。

**Comment by Kenshin** [comment]
这个页面可以单独导出 **离线 HTML**

[在酷安浅谈我当精神股东的经历，以及我对如何走出数码圈饭圈化的个人拙见 来自 用户 Xa1733RE01 - 酷安.html.zip](https://github.com/Kenshin/simpread/files/7894364/Xa1733RE01.-.html.zip)
