### ISSUE TITLE
能不能增加适配观察者网：www.guancha.cn。

### ISSUE THREAD

**Issue by kahrpba2100** [Kenshin/simpread#333]
自己设计的不好看。

教程里面title、include怎么找也不是很懂。。

**Comment by Kenshin** [comment]
没问题，适配后会通知你~

**Comment by Kenshin** [comment]
你好，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。
