### ISSUE TITLE
logseq 请求适配

### ISSUE THREAD

**Issue by eallion** [Kenshin/simpread#3331]
https://wiki.geekplux.com/#/page/eczema

这类 logseq 的页面请求适配一下阅读模式。

**Comment by Kenshin** [comment]
嗨，这类页面的问题是：我觉得没有适配阅读模式的必要，因为它是 Outline 这种层级显示方案。

虽然可以将其转换为段落方式，但还是没有普适性。

我先留着这个 Issues ，再考虑下。

PS：logseq 有自己的 Publish site 功能了？

**Comment by eallion** [comment]
他这个页面本身排版可能也有问题，层级太多了。

我印象中 Logseq 很早的版本就支持这个功能了。后来转到 Obsidian 了。

**Comment by Kenshin** [comment]
> 我印象中 Logseq 很早的版本就支持这个功能了

哈哈，我还是第一次知道...

这个页面确实层级太多了，除非有类似文章类的 logseq 页面才有适配的意义。
