### ISSUE TITLE
插件获取失败，请稍后再试

### ISSUE THREAD

**Issue by focusv** [Kenshin/simpread#3333]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win10**

- 浏览器版本 **e.g. Chrome 97**

- 简悦版本 **2.2.0**  未启用同步助手

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#plugins?install=VQOZdNET2d>

已尝试https://github.com/Kenshin/simpread/discussions/1696  https://github.com/Kenshin/simpread/discussions/2990
网络环境正常 github内容可下载
安装插件均显示“插件获取失败，请稍后再试”

**Comment by Kenshin** [comment]
emmm 这就很奇怪了...

导出你的配置文件，然后重新安装简悦，什么都不要操作，直接安装（获取）插件看看。

**Comment by wonghuahua** [comment]
简悦同步助手 的桌面版不能下载，微云的链接不能打开

**Comment by Kenshin** [comment]
@wonghuahua 

我刚才测试了没有问题 https://share.weiyun.com/S8C1bxJ7 可以直接打开，请检查下你的网络环境。

**Comment by wonghuahua** [comment]
> 
最终在onedrive下载成功啦，微云的链接我换了热点，也挂了外网，还是无法打开页面，不晓得是否只是我一个人的问题。
辛苦作者大大啦~

**Comment by Kenshin** [comment]
@wonghuahua 

微云用正常的网络就好...  😂

不过，问题搞定就好。

**Comment by Jface001** [comment]
我存在相同的问题，安装任何插件都会提示
获取失败，请稍后重试，截图如下
![image](https://user-images.githubusercontent.com/21217483/150556388-07dddb44-219a-4c3d-beb9-1ca68996c075.png)

**Comment by Kenshin** [comment]
@Jface001 

看提示并没有这个插件 ID，请告诉我你是如何安装的？另外，试试 #1696 #2990 这两个解决方式。

**Comment by Jface001** [comment]
> #2990

感谢回复！抱歉没有描述清楚。 #1696 #2990  均已尝试验证，问题依旧存在。
Chrome版本：版本 97.0.4692.71（正式版本） (arm64)
系统版本：macOS 12.1
简悦版本:2.2.0.520
操作：偏好设置-插件管理-查找更多插件-任意插件（例如代码段增强/浮动面板定制器）
问题：点击安装会转跳到 偏好设置-插件管理界面，并且右上角有错误代码提示。
- 代码段增强：

![image](https://user-images.githubusercontent.com/21217483/150625977-3bb6b691-9887-4b05-9f6a-79f57e9a5872.png)
- 浮动面板定制器
![image](https://user-images.githubusercontent.com/21217483/150625993-b8ebd04a-2e44-43c0-aaa4-da69d33f02fa.png)

**Comment by Kenshin** [comment]
@Jface001

还是之前说的

> 看提示并没有这个插件 ID

你可以这样测试下：

1. 导出配置文件（用作备份）
2. 重新安装简悦
3. 安装后什么都不要操作直接安装插件
4. 看看能否成功？

如果还是无法成功的话，我怀疑是其它扩展造成的干扰，你可以把除了简悦以外的扩展全部关闭，再试试。

**Comment by Kenshin** [comment]
@menhuan 

安装失败 
![image](https://user-images.githubusercontent.com/20064040/150778831-6e5c7118-7b58-4c71-bc10-417bd30bbbd6.png)

**Comment by Kenshin** [comment]
@menhuan 

我把之前的内容转移到了这里了，因为这个用户遇到的问题一样…

很奇怪的问题，试试 https://github.com/Kenshin/simpread/issues/3333#issuecomment-1019087174 提到的方式，能否解决？

**Comment by focusv** [comment]
我放弃了现存的配置文件，卸载插件后重新安装解决了。如果再将原来的配置文件导入，就会出现插件安装失败。

**Comment by Kenshin** [comment]
@focusv 

把有问题的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3333

**Comment by focusv** [comment]
可能是权限问题。当取消“所有网站上“可更改和读取数据时，插件无法安装。选择“所有网站上“可更改和读取数据，又可以安装插件

**Comment by Kenshin** [comment]
@Jface001 

估计你也是这个问题 https://github.com/Kenshin/simpread/issues/3333#issuecomment-1022247377

**Comment by menhuan** [comment]
我的默认就是所有网站上可更改和读取数据

**Comment by Kenshin** [comment]
@menhuan 

试过 https://github.com/Kenshin/simpread/issues/3333#issuecomment-1020095711 提供的方式了吗？

**Comment by menhuan** [comment]
我试了下那个权限获取，原先是所有网站，取消，再改成所有网站，问题解决了

**Comment by menhuan** [comment]
> @menhuan
> 
> 试过 [#3333 (comment)](https://github.com/Kenshin/simpread/issues/3333#issuecomment-1020095711) 提供的方式了吗？
我试了下那个权限获取，原先是所有网站，取消，再改成所有网站，问题解决了

**Comment by Kenshin** [comment]
@menhuan 

搞定就好，我把上述问题记录到了 https://github.com/Kenshin/simpread/discussions/1696

**Comment by Cass998** [comment]
> 可能是权限问题。当取消“所有网站上“可更改和读取数据时，插件无法安装。选择“所有网站上“可更改和读取数据，又可以安装插件

这个是浏览器设置里权限吗，我在edge里没有找到诶

**Comment by Kenshin** [comment]
@Cass998 

![image](https://user-images.githubusercontent.com/81074/151337804-0aa1833e-9e66-416b-b1cb-a026a7318db9.png)

**Comment by Cass998** [comment]
![image](https://user-images.githubusercontent.com/45821602/151393939-407f1153-d4ea-4342-9749-89bb2184d348.png)
![image](https://user-images.githubusercontent.com/45821602/151394150-46ea3854-5119-4d88-ba40-fd6be4831f60.png)
您好，我已经按照你的图勾选了相应的选项，并且重新启动了edge，任然没用。

**Comment by Kenshin** [comment]
@Cass998 

试试 #1696

**Comment by Cass998** [comment]
> @Cass998
> 
> 试试 #1696

#1567#1696 的方法都试了，没有用欸。

**Comment by Kenshin** [comment]
@Cass998 

找个干净的浏览器（其实没必要，仅针对你的问题而使用的方式），重新安装，然后什么都不设置，也没法使用吗？

**Comment by Cass998** [comment]
> @Cass998
> 
> 找个干净的浏览器（其实没必要，仅针对你的问题而使用的方式），重新安装，然后什么都不设置，也没法使用吗？

我现在的情况是，两个电脑的两个浏览器中，chrome浏览器可以安装插件，但edge浏览器就不行。
两个浏览器共用一个配置文件就不行吗

**Comment by Cass998** [comment]
> @Cass998
> 
> 找个干净的浏览器（其实没必要，仅针对你的问题而使用的方式），重新安装，然后什么都不设置，也没法使用吗？

而且应该不是权限的问题，我的edge浏览器是“点击时”，不是“在所有网站上”。但可以安装并运行插件

**Comment by Cass998** [comment]
> @Cass998
> 
> 找个干净的浏览器（其实没必要，仅针对你的问题而使用的方式），重新安装，然后什么都不设置，也没法使用吗？

算了，我不折腾了。以后我手动同步配置文件，从chrome导入插件到edge

**Comment by Kenshin** [comment]
@Cass998

> 我现在的情况是，两个电脑的两个浏览器中，chrome浏览器可以安装插件，但edge浏览器就不行。 两个浏览器共用一个配置文件就不行吗

emmm 看上面这个描述，你遇到的问题跟 #3333 （跟本 issues 无关...

你应该使用了同步助手，安装插件后没有显示？如果是的话，解决方案 https://github.com/Kenshin/simpread/discussions/2342

**Comment by Jface001** [comment]
@Kenshin 感谢认真解答~ 之前的几个方式都没能安装成功。昨晚再次尝试莫名其妙成功
个人猜测是网络代理问题
再次感谢，新年快乐~

**Comment by Kenshin** [comment]
@Jface001 

搞定就好，插件系统是在国内的，可以看看 https://github.com/Kenshin/simpread/discussions/2990 里面提到的方式。

**Comment by heliarmk** [comment]
> > @Cass998
> > 找个干净的浏览器（其实没必要，仅针对你的问题而使用的方式），重新安装，然后什么都不设置，也没法使用吗？
> 
> 我现在的情况是，两个电脑的两个浏览器中，chrome浏览器可以安装插件，但edge浏览器就不行。 两个浏览器共用一个配置文件就不行吗

我也遇到了同样的问题，发现是安装的adBlock导致的。替换一个就可以了。。

**Comment by Kenshin** [comment]
> 我也遇到了同样的问题，发现是安装的adBlock导致的。替换一个就可以了。。

嗨，谢谢提示 🙏

不过，你遇到的问题我也是第一次看到有用户反馈，理论上简悦跟 adBlock 应该没冲突（因为我在使用 uBlock，没法 100% 判断）。

所以，虽然提到了「同样的情况」，但能否详细描述下你的问题（也就是使用 adBlock 后的问题现象？
