### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by MakerFace** [Kenshin/simpread#3334]
发生问题的地址: <https://link.zhihu.com/?target=https%3A//my.oschina.net/lzugis15/blog/4799507>

**Comment by binsee** [comment]
外链跳转页面，没适配的必要。

**Comment by MakerFace** [comment]
直接加入黑名单吗，每次都得按esc退出再点击跳转

**Comment by binsee** [comment]
你那边会自动进入阅读模式吗？我这边未能复现
如果是的话，可将 `link.zhihu.com` 加入黑名单列表

![image](https://user-images.githubusercontent.com/5285894/150314078-90270d71-680e-4d56-a67a-47e90758f9af.png)

**Comment by MakerFace** [comment]
好的，我尝试一下，非常感谢

**Comment by Kenshin** [comment]
@MakerFace 

可以装这个插件 https://github.com/Kenshin/simpread/discussions/2734 解决跳转的问题。

**Comment by MakerFace** [comment]
@Kenshin 这个插件很棒！

**Comment by Kenshin** [comment]
@MakerFace

哈哈，必须地。

关于知乎的玩法 [还很多](https://github.com/Kenshin/simpread/discussions?discussions_q=%E7%9F%A5%E4%B9%8E)，可以去探索探索。
