### ISSUE TITLE
站点管理器只包含一个自定义适配源，无法选择编辑

### ISSUE THREAD

**Issue by EliYao** [Kenshin/simpread#334]
![image](https://user-images.githubusercontent.com/7480584/41097595-1edef848-6a8b-11e8-9c66-364453741e31.png)

**Comment by Kenshin** [comment]
谢谢反馈，这是个 Bug，下个版本修复（下周发布新版）

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 将关闭。
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
