### ISSUE TITLE
阅读列表页显示“未知错误”

### ISSUE THREAD

**Issue by liamtao** [Kenshin/simpread#3342]
【现象】
当通过「简悦个人中心」进入「阅读列表」后，页面显示“额，发生未知错误，请稍后再试”。

【背景】

1. 「收藏助手」相关设置运行良好。(即坚果云、API等设置应该都没问题)
2. 「同步助手」已把导出的路径设为坚果云根目录/SimpRead/output/。且导出html运行正常，可同步至坚果云线上。

【补充】
进入「每日回顾」页面，同样会显示“额，发生未知错误，请稍后再试”

不知是否相关，Chrome Console会显示以下错误（不过报错时间会晚于页面展示）：
content.js:82923 Uncaught (in promise) Error: Failed to find player
    at playerRejector (content.js:82923:19)
    at content.js:3022:7

**Comment by Kenshin** [comment]
试试登录 [开放平台](https://simpread.pro/developer)，然后开启下图的选项

![image](https://user-images.githubusercontent.com/81074/150629991-fc05cdee-84d8-482a-9768-ee2a499b9693.png)

**Comment by liamtao** [comment]
顺利解决，谢谢大佬！

**Comment by Kenshin** [comment]
哈哈，搞定就好~

我把这个解决方案放到了 https://github.com/Kenshin/simpread/discussions/3344
