### ISSUE TITLE
简悦同步助手在Windows11系统中可能会导致搭载AMD显卡的笔记本蓝屏

### ISSUE THREAD

**Issue by Mickychen00** [Kenshin/simpread#3346]
经过多次控制变量，我发现是简悦同步助手每次开启后，就极容易点关机后立即蓝屏。开机不开机同步助手、不运行同步助手，就没有发现这个问题。请问该如何解决呢？期待您的回复

**Comment by Kenshin** [comment]
emmm

好久没用 Win 了，也没有其他用户反馈类似问题，简悦 Windows 11 用户还很多，出现这种问题的话，早就有用户反馈了，但不排除是个例。

@binsee 帮忙看看？

**Comment by binsee** [comment]
需要更多信息，才能做进一步判断。
之前群里有一个win11用户反应经常保存到稍后读后过一段时间容易出现直接死机重启，请对方提供了系统日志后发现是对方硬件有问题，总掉硬盘导致系统崩溃重启。

我觉得此处遇到的问题可能类似，因为我也是win11，日常没遇到这些情况。请补充以下内容：
1. 蓝屏时的照片。蓝屏画面中的错误码可以帮助判断问题来源
2. 或提供系统日志，建议进tg群，私聊发送。（如果没有tg的话，可以上传到 [奶牛快传](https://cowtransfer.com/)  这类临时网盘，然后在issue中回复告知）
   操作步骤：
    1. 右键「此电脑」，在菜单中选「管理」
    2. 在「计算机管理」窗口左侧选择「计算机管理(本地) - 系统工具 - 事件查看器 - Windows日志 - 系统」
    3. 右键点击 「系统」，选择「将所有事件另存为」，导出到文件
    4. 打包压缩导出文件，私聊发送
    5. 最好能告知出现过死机的时间，方便快速定位。

**Comment by sylph520** [comment]
额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。蹲个后续。

链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Mickychen00** [comment]
> 额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。好像是20220227晚上9点多吧。蹲个后续。
> 
> 链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦

您说对了，我也是AMD的核显（5800H）。不过自从我停用简悦同步助手后，就再也没有出现过这个问题。您要不也试试？然后反馈一下。

**Comment by sylph520** [comment]
> > 额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。好像是20220227晚上9点多吧。蹲个后续。
> > 链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 您说对了，我也是AMD的核显（5800H）。不过自从我停用简悦同步助手后，就再也没有出现过这个问题。您要不也试试？然后反馈一下。

5800H +1， 🤣🤣🤣 我上面的回复附上了事件查看器的文件，然后dump文件分析的结果是dxgmms2.sys的问题，所以我的排查列表第一项都是显卡问题。太专业的分析我也不太会。

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053573831 https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053575733
https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053584978

嗨，抱歉各位，因为我一直在使用 Mac 系统，所以没办法帮忙 @binsee 请帮忙看下上面三个链接中的回复。

**Comment by binsee** [comment]
> https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053573831 https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053575733
> https://github.com/Kenshin/simpread/issues/3346#issuecomment-1053584978
> 
> 嗨，抱歉各位，因为我一直在使用 Mac 系统，所以没办法帮忙
> 
> @binsee 请帮忙看下上面三个链接中的回复。

最近工作比较忙，我可以周末看看

**Comment by binsee** [comment]
> 额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。最近一次蓝屏好像是20220227晚上9点多吧。蹲个后续。
> 
> 这是事件查看器的文件 链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦

@sylph520 方便发到不限速的网盘吗？比如阿里云盘、腾讯网盘之类的

**Comment by sylph520** [comment]
> > 额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。最近一次蓝屏好像是20220227晚上9点多吧。蹲个后续。
> > 这是事件查看器的文件 链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> @sylph520 方便发到不限速的网盘吗？比如阿里云盘、腾讯网盘之类的

👌 微云传了一个 链接：https://share.weiyun.com/e5SZchqM 密码：wxkucs

**Comment by helongjk** [comment]
> emmm
> 
> 好久没用 Win 了，也没有其他用户反馈类似问题，简悦 Windows 11 用户还很多，出现这种问题的话，早就有用户反馈了，但不排除是个例。
> 
> @binsee 帮忙看看？

我win10，也有同样的问题，关机或者重启win的时候会发生蓝屏。

**Comment by binsee** [comment]
> > > 额，我好像也出现了不知道有没有关系，一直在排查，有过怀疑，但是还是认为是amd核显的原因大些。但是实在太频繁了，后来重置了win11, 但是好像还有问题，昨天又重装了核显驱动，蓝屏代码是KERNEL_MODE_HEAP_CORRUPTION。最近一次蓝屏好像是20220227晚上9点多吧。蹲个后续。
> > > 这是事件查看器的文件 链接: https://pan.baidu.com/s/1GRuRWOxlisBImzZ-dTxTbA 提取码: sb45 复制这段内容后打开百度网盘手机App，操作更方便哦
> > 
> > 
> > @sylph520 方便发到不限速的网盘吗？比如阿里云盘、腾讯网盘之类的
> 
> 👌 微云传了一个 链接：https://share.weiyun.com/e5SZchqM 密码：wxkucs

```
计算机已经从检测错误后重新启动。检测错误: 0x0000013a (0x0000000000000011, 0xffffaa8f0e202140, 0xffffaa8f317f8bc0, 0x0000000000000000)。已将转储的数据保存在: C:\WINDOWS\MEMORY.DMP。报告 ID: ef023240-a6e1-4fd1-907f-e410b4a4476f。
```

参考： [Bug 检查 0x13A：KERNEL_MODE_HEAP_CORRUPTION](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/debugger/bug-check-0x13a--kernel-mode-heap-corruption)

这是个内核中的错误，照说得由驱动或系统服务之类的才会触发，但同步助手只是普通权限运行，不应该会引发这种程度的错误才对。

我在你的日志文件中发现无线网卡的驱动似乎工作不正常，你可以关注下。

如果你使用了坚果云，可以试试先彻底关闭坚果云，然后正常使用简悦，看看是否会复现问题。坚果云是我唯一能想到的与简悦有关，且涉及到系统服务的东西了。

PS：最近刚换工作，很忙，这个issue就一直没顾上回复。

**Comment by binsee** [comment]
补充一下，通过和另一位用户发来的日志对比，发现有个共同点，基本上都是为设备加载驱动失败后导致死机的。
而两份日志都出现了一个共同的设备 **WindowsHelloFaceSoftwareDriver** ，请检查下 `hello face` 相关的驱动与软件。

**Comment by ivicever** [comment]
我也遇到了同样的问题，在打开了简悦同步助手之后过段时间会蓝屏。跟上面几位一样，我也是AMD的CPU，5700G。

附上我的系统事件，以供参考，2022-03-18下午那几次Error就是蓝屏的时候。传输链接：https://cowtransfer.com/s/912aa35bc63d4a 或 打开【奶牛快传】cowtransfer.com 使用传输口令：pym6ev 提取；

多次尝试修改各种设置，发现有个临时的解决办法，在稍后读的设置中关闭了“是否使用简悦·同步助手内置的解析器？”之后就不再有蓝屏现象了。可能也是个找bug的途径。

**Comment by Kenshin** [comment]
> 多次尝试修改各种设置，发现有个临时的解决办法，在稍后读的设置中关闭了“是否使用简悦·同步助手内置的解析器？”之后就不再有蓝屏现象了。可能也是个找bug的途径。

谢谢，很有帮助 @ivicever

**Comment by Kenshin** [comment]
嗨，各位。

同步助手发布了命令行版本，应该可以暂时解决 AMD 的蓝屏问题，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3704)，目前此版本为内测版，有任何问题请 [汇总到这里](https://github.com/Kenshin/simpread/discussions/3704#discussioncomment-2542653)。

PS：等正式版发布后，我还会通过这里告诉大家。

**Comment by Kenshin** [comment]
嗨，各位。

如果不想使用 命令行方案的话，可以试试下面来自简悦社区群用户的方案：

1. 更新显卡驱动
2. 把开机自动启动简悦助手关掉，等到用简悦的时候手动开启。

这样好像就没出现过内核奔溃的事情了。

**Comment by Mickychen00** [comment]
看到大家对这个问题的共同反映，我忽然想讲一讲之前我因为这个蓝屏问题遇到的尴尬事情。我算是最早反映这个Bug的简悦高级版用户。
去年12月份，我新购买的搭载AMD5800H的笔记本频繁蓝屏，有时候运行时候蓝屏，有时候关机时候瞬间蓝屏。因此，1月初我去了一趟海淀新技术大厦找卖家维修（快速重装系统），以为能解决问题，不过后来发现还会是蓝屏。因此我就采用“控制变量”的方法不断试验，发现了简悦同步助手引起蓝屏的疑似可能性，因此在社区向kenshi提了这个Issue。不过：
如果对北京海淀1月疫情还有印象的人，应该回想起来在银行工作的最初确诊病例。没错，这个银行就在海淀新技术大厦，我于1月16日被通知隔离14天。作为外地人的我，当时真的绝望，因为直接会被隔离至除夕，这就没法回家过年了。
不过庆幸的是，那里确诊病例是在我去大厦之后接触的阳性国际快递，所以两天后就被接触隔离了，算是不幸中的万幸。
我觉得是单纯的“点背”，不过也希望简悦同步助手能优化得更好。避免因为软件bug被防控隔离（神奇的逻辑链条...）
最后感谢kenshi和binsee的耐心帮助，期待早日完美解决这个问题。
PS：更新最新驱动可能不好使，目前笔记本不再敢打开同步助手了。期待大家更好的解决方案。

**Comment by Kenshin** [comment]
@Mickychen00 

你可以试试命令行的方案，也是官方发布。

**Comment by Kenshin** [comment]
嗨，各位。

[同步助手 · 命令行](https://github.com/Kenshin/simpread/discussions/3704) 版正式发布  🎉 

![Sync CLI](https://user-images.githubusercontent.com/81074/163512494-3c41c6c3-2158-49f8-9425-27637a3303c8.png)

在使用时如有问题，[请提 Issues](https://github.com/Kenshin/simpread/issues/3740)

**Comment by sylph520** [comment]
谢谢解决方案！！！

**Comment by qiaogaojian** [comment]
非AMD显卡也会蓝屏重启, 我用的无显卡cpu i59400f, 显卡华硕的2060s. 我也是排除定位了好久确定是同步助手的原因, 然后来查找相关的issue.

**Comment by Kenshin** [comment]
@sylph520 

这个还第一次遇到... 可以试试 https://github.com/Kenshin/simpread/issues/3346#issuecomment-1099825767 提供的方案。

或者试试 32 位版本。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 解决了蓝屏问题

> 虽然系统日志并没有指出就是因同步助手引起。

此版本已经让 AMD 显卡的用户测试了半个月+，没有在发生同样类似的问题。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄

**Comment by jokervTv** [comment]
很遗憾，windows 11 amd r7-5800h 问题依旧，关机容易蓝屏，使用命令行版本问题消失

**Comment by Kenshin** [comment]
@jokervTv 

在发布前，我已经找了 nnn 个用户内测了，都是没问题的，下图是今天的用户使用后的回复。

![image](https://user-images.githubusercontent.com/81074/172831177-50adb3a3-aca7-4376-a5ba-aa52d46f1bed.png)

而且根据 @binsee 的测试，其实跟同步助手没有关系，至少日志没有关于简悦的问题。😂

另外... 据说 AMD 的用户某些连 ADB  都有问题...

![image](https://user-images.githubusercontent.com/81074/172831423-8543c3ba-9edc-4347-819c-c8c2b9c8cfaa.png)

![image](https://user-images.githubusercontent.com/81074/172831488-83cce007-3af9-44f6-9441-e6494fa7fe6f.png)

**Comment by jokervTv** [comment]
> 

哦哦，好吧，看来是无福消受了，只能用命令行版本了

**Comment by dagon007** [comment]
我的也出现这样的情况，是联想的AMD核显笔记本 小新14+ 2021ACN版本。运行同步助手1.12版本，一开始是关机蓝屏，然后逐步变成了打开不久就蓝屏了。关掉了这个同步助手就不再出现蓝屏。

**Comment by Kenshin** [comment]
@dagon007 

是不是设置了同步助手的自启？把自启动功能关了。另外，新版本发布了，你的第二个还反馈这个问题的用户。（确实很奇怪...

**Comment by zc910704** [comment]
你好
确实有这个问题，硬件是5600G，版本是 简悦 · 同步助手-1.2.0@win64  目前最新的了。dump显示KERNEL_MODE_HEAP_CORRUPTION,  内核态的栈

```
fffff90c`de2f72a8 fffff803`70da2654     : 00000000`0000013a 00000000`00000011 ffffa005`82010140 ffffa005`879fbae0 : nt!KeBugCheckEx
fffff90c`de2f72b0 fffff803`70da26b4     : 00000000`00000011 00000000`00000000 ffffa005`82010140 ffffa005`96bb0350 : nt!RtlpHeapHandleError+0x40
fffff90c`de2f72f0 fffff803`70da22d1     : 00000000`01400020 ffffffff`ffffffff 00000000`00000009 ffffa005`947f93c0 : nt!RtlpHpHeapHandleError+0x58
fffff90c`de2f7320 fffff803`70cac3de     : 00000000`ffffff00 00000000`00000004 ffffa005`8c781920 00000000`00000009 : nt!RtlpLogHeapFailure+0x45
fffff90c`de2f7350 fffff803`70a41689     : ffffa005`82010380 fffff803`70a342ff 00000000`00000000 00000000`00000000 : nt!RtlpHpLfhSubsegmentFreeBlock+0x198a6e
fffff90c`de2f73e0 fffff803`7129b1b0     : ffffa005`879fbae0 00000000`00000006 ffffa005`8c781940 00000000`00000001 : nt!RtlpHpFreeHeap+0x159
fffff90c`de2f7480 fffff803`6ab7850d     : 00000000`32616956 00000000`00000000 00000000`00000006 00000000`00000020 : nt!ExFreePoolWithTag+0x1a0
fffff90c`de2f7510 fffff803`6ab7769c     : 00000000`00000005 ffffa005`87f7c000 00000000`00000001 ffffa005`8c781920 : dxgmms2!VidMmInterface+0x3ac4d
fffff90c`de2f7550 fffff803`743dbb4e     : ffffbb88`5b569760 fffff90c`de2f77b0 ffffbb88`5b569950 ffffbb88`5b569950 : dxgmms2!VidMmInterface+0x39ddc
fffff90c`de2f75f0 fffff803`743db535     : ffffbb88`5b569760 fffff90c`de2f77b0 ffffbb88`5b569901 fffff90c`de2f77b0 : dxgkrnl!DXGDEVICE::DestroyDevice+0x142
fffff90c`de2f7670 fffff803`743dc56b     : ffffbb88`5b569760 ffffbb88`54ef27e0 ffffa005`95fdbd30 fffff90c`de2f77b8 : dxgkrnl!DXGDEVICE::DestroyAllDeviceState+0x1d1
fffff90c`de2f76e0 fffff803`743daf67     : ffffbb88`5b569760 ffffa005`8b80c700 ffffbb88`5b569760 ffffa005`00000000 : dxgkrnl!ADAPTER_RENDER::DestroyDevice+0x103
fffff90c`de2f7760 fffff803`743dae06     : ffffbb88`5b569760 fffff90c`00000001 ffffbb88`5b569760 ffffbb88`5b569760 : dxgkrnl!ADAPTER_RENDER::DestroyDeviceNoLocksInternal+0x83
fffff90c`de2f7870 fffff803`743da95e     : ffffbb88`5b569760 fffff90c`de2f7b20 00000000`00000002 00000000`00000000 : dxgkrnl!ADAPTER_RENDER::DestroyDeviceNoLocks+0x92
fffff90c`de2f78a0 fffff803`743d9c5b     : 000001e6`8c9b6248 ffffa005`8c6e8080 000001e6`8c9b6248 00000000`00000020 : dxgkrnl!DxgkDestroyDeviceImpl+0x346
fffff90c`de2f7a70 fffff803`70c3e0e8     : ffffa005`8c6e8080 ffffa005`8c6e8080 00007ffc`ae8acfc0 00000000`00000000 : dxgkrnl!DxgkDestroyDevice+0xb
fffff90c`de2f7aa0 00007ffc`b3934ed4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x28
000000c0`f4dfe4c8 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ffc`b3934ed4
```
看栈确实也是显示相关的问题， 但是没在electron的库里找到相关issue。
如果有需求我可以提供dump

**Comment by binsee** [comment]
> 看栈确实也是显示相关的问题， 但是没在electron的库里找到相关issue。 如果有需求我可以提供dump
根据上下文
如果你有动手能力，可以试着关闭简悦的开机自启

**Comment by zc910704** [comment]
> > 看栈确实也是显示相关的问题， 但是没在electron的库里找到相关issue。 如果有需求我可以提供dump
> 
> 根据上下文猜测的可能是自启过程引发的问题，可以进行以下测试： 如果你有动手能力，可以试着关闭简悦的开机自启，然后在任务计划中创建一个开机启动后延迟半分钟、1 分钟之类延迟触发，启动简悦。这样重启几次看看是否会复现问题？

我这没启动开机自启。
32位在退出程序的时候也出现了一次。有时间可以试一下你说的这个。
