### ISSUE TITLE
今早稍后读打不开

### ISSUE THREAD

**Issue by gukejing** [Kenshin/simpread#3352]
就空白页面，刷不出来。阅读模式正常，后台也运行着助手。
环境：Win 10
浏览器：Edge, Chrome
加入稍后读，提示已经加入，不过没有生成本地文件（我使用了本地同步的功能）。

**Comment by Kenshin** [comment]
可以使用以下两个解决方案：

1. https://github.com/Kenshin/simpread/discussions/3165
2. https://github.com/Kenshin/simpread/discussions/2727

有能力的话，首选方案二，方案一比较简单，但没有二精准。
