### ISSUE TITLE
CSDN阅读模式图像无法左对齐

### ISSUE THREAD

**Issue by Ives-king** [Kenshin/simpread#3353]

**Comment by Ives-king** [comment]
https://blog.csdn.net/qq_40477151/article/details/103917156#2_install___CMinGWD_20

![image](https://user-images.githubusercontent.com/95950765/150939344-58b16225-ae1a-4832-906a-4f34f042a5d7.png)

**Comment by Kenshin** [comment]
嗨，简悦的阅读模式本就是居中效果的。
