### ISSUE TITLE
曾经自定义了站点高亮区域, 删除自定义站点后, 官方适配源还是不起作用

### ISSUE THREAD

**Issue by Tokubara** [Kenshin/simpread#3356]
操作系统: MacOS 10.15.7
chrome版本: Version 92.0.4515.131 (Official Build) (x86_64)
简悦版本: chrome商店最新, 2.2.0

以前打开www.stackoverflow.com, 默认高亮区域不满意(没有问题, 只有第一个回答), 重新调整. 后来得知有官方适配源, 更新了, 感觉效果很不错, . 但是现在打开www.stackoverflow.com, 仍然是以前指定的高亮区域在起作用. 打开chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/sitemgr.html, 删除了自定义站点, 结果打开新的www.stackoverflow.com, 新的站点编辑(就是官方的)仍然不起作用, 要么是最早我没编辑之前的站点(只有第一个回答), 要么是我编辑过的(丑的很), 出现这几个的都有, 简直就是随机的.

![image](https://user-images.githubusercontent.com/32409331/151131300-b25d2b2b-9b7d-4822-a034-80c754be1947.png)
这张图说明, 没有自定义适配源(已删除).

这是在关闭设置后, 打开stackoverflow某个网页查看到的站点编辑器. 两者并不一致.
![image](https://user-images.githubusercontent.com/32409331/151131602-e6dd24d2-9b6f-405a-8e6f-9873bc2fb489.png)

**Comment by Tokubara** [comment]
请问如何切换到官方适配源呢? 我咋就不显示"官方适配源 已启用"

**Comment by Kenshin** [comment]
@Tokubara 

点击它
