### ISSUE TITLE
沙拉查词的 anki联动功能无法在简悦使用

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [Kenshin/simpread#3359]
您好！我阅读英语网站的时候，希望能够用沙拉查词对生词进行标记。虽然沙拉词典在简悦阅读模式可以正常查词，但是使用沙拉词典的anki自动同步功能时就无法正常弹出。不知道是什么原因呢？
![image](https://user-images.githubusercontent.com/27610409/151175560-108bc313-3199-47f1-896c-7f681944bfd3.png)

![image](https://user-images.githubusercontent.com/27610409/151175726-d9dad74e-e943-4dbe-b5d3-eb83f7d07c88.png)

**Comment by YELLOWHOMEIN** [comment]
要退出阅读模式才会弹出下面的这个图。不知道是什么原因呢？

**Comment by OverflowCat** [comment]
@YELLOWHOMEIN 你可以在 Stylus 里写个用户样式指定简悦阅读界面的 `z-index`：

```css
.simpread-read-root {
    z-index: 10;
}
```

![image](https://user-images.githubusercontent.com/20166026/151192469-09a806d3-1c12-4e59-9be5-125b0a54ac34.png)

记得在下方章节处填写生效规则以在任意网站生效。

![image](https://user-images.githubusercontent.com/20166026/151192910-3ddcee58-96f5-445a-8ae2-81d05b7d800a.png)

**Comment by Kenshin** [comment]
@YELLOWHOMEIN 

嗨，除了 @OverflowCat 提到的方式外，也可以看看 https://github.com/Kenshin/simpread/issues/3285 是否能帮到你？

**Comment by YELLOWHOMEIN** [comment]
感谢！按@OverflowCat 的方法解决了，虽然我从来没有用过 stylus

**Comment by Kenshin** [comment]
各位，上述内容已经记录到 https://github.com/Kenshin/simpread/discussions/3366
