### ISSUE TITLE
Feature Request：为插件“导入到 Obsidian”增加变量：url

### ISSUE THREAD

**Issue by bobwng** [Kenshin/simpread#3368]
现在插件 [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902) ，提供了四种关键字，但是没有网页链接。

建议增加一个新的关键字/变量：url，代表网页的url，以便保存到Obsidian中，便于日后追溯。

**Comment by Kenshin** [comment]
嗨，导入到 Obsidian 升级到 1.1.0，增加了如下功能，主要是包含了你要的 `{{url}}`

-  `Add` 新的 Metadata
    - `{{url}}`
    - `{{timestamp}}`
    - `{{note}}`

- `Add` [Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)

## Local REST API 导入方案视频

https://user-images.githubusercontent.com/81074/163329889-8269dbba-144b-45c2-a706-2ed716049c4a.mp4

***

当看到此 Issues 并且没有问题的话，请 Close 它。

**Comment by bobwng** [comment]
Thank you very much~! It works very well in my mac!!!

**Comment by Kenshin** [comment]
嗨，我顺道也关闭了 https://github.com/Kenshin/simpread/issues/3678

不过，我对你提到的 https://github.com/Kenshin/simpread/issues/3678#issuecomment-1089989933 & https://github.com/Kenshin/simpread/issues/3678#issuecomment-1090000504 方便很感兴趣，不知道是否有什么进展？

**Comment by bobwng** [comment]
这段时间工作比较忙，暂时没有进展。过段时间空一些到telegram上与您一起讨论讨论

**Comment by oldwinter** [comment]
刚纳闷儿导入的文章没有url，来社区看看，就发现了近期刚解决哈哈。感谢2位的讨论，使得产品更好，也使得我进一步优化了我的工作流。

**Comment by Kenshin** [comment]
@oldwinter 

嗨，留意下[通知频道](https://simpread.pro/subscribe)，此插件明天会有个「大更新」。

**Comment by Kenshin** [comment]
嗨，各位。

导入到 Obsidian 升级到 1.2.0 ，增加了 **重磅功能**：可以不通过同步助手，将标注自动导入到 Obsidian。

## 一站式教程

https://simpread.zhubai.love/posts/2128393555537739776

## 视频

https://user-images.githubusercontent.com/81074/164135947-0552fc11-1b92-4804-a616-df64ae43770a.mp4
