### ISSUE TITLE
维基百科的匹配模式会丢掉原文的图片。

### ISSUE THREAD

**Issue by kahrpba2100** [Kenshin/simpread#337]
无论中英文维基百科网站原文若是带有图片，在阅读模式下都会被省略，有时候会造成阅读障碍。
而且每次一进具体页面的阅读模式都会自动弹出具体的设定页面，是不是适配没做完？
![default](https://user-images.githubusercontent.com/7860684/41225485-75305de0-6da1-11e8-988d-ddf845cac300.png)
![2](https://user-images.githubusercontent.com/7860684/41225492-7a37dcdc-6da1-11e8-8770-664e4bce80a1.PNG)

另外前几天适配的观察者网，有时候网站文章会带有分页。但进入阅读模式后就看不到分页（1、2、3）标志了，会导致漏掉内容。(http://www.guancha.cn)
就像这样：
![default](https://user-images.githubusercontent.com/7860684/41225633-d5d6fbae-6da1-11e8-8efb-d230c8236d8e.png)
![2](https://user-images.githubusercontent.com/7860684/41225696-f6a0d8a0-6da1-11e8-9b28-875b492513ba.PNG)
nengbunen能不能增加哪怕是一个分页提示也好。

最后，阅读进度的提示条能不能减少1px，达到那种想看就有，不注意就不存在的境界，就像github的载入条一样。现在的有点粗了。

感谢作者的辛勤工作带来这么好用的产品。~

**Comment by Kenshin** [comment]
感谢这么详细的截图~

1. 维基百科由于每个页面结构太过复杂，所以暂时并不能很完美的显示阅读模式；

2. 「每次一进具体页面的阅读模式」 
     你可以把 `zh.wikipedia.org` 加入到 排除列表，这样只有手动进入方式了。

3. 适配的时候确实没有注意到分页，但你可以自己修改配置文件，或者等我下次发布时，把分页加上。

4. 「阅读进度的提示条的宽度」可以通过自定义样式解决，详细 [看这里](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by kahrpba2100** [comment]
好的，等更新好了。

**Comment by Kenshin** [comment]
http://www.guancha.cn

暂时加不上分页，因为它的写法无法通过适配规则自动获取...

zh.wikipedia.org 的问题我会考虑下个版本解决掉。

**Comment by amitbha** [comment]
如果能把 onclick 属性移到自己按钮上，是不是就可以了？

**Comment by Kenshin** [comment]
是的。

简单点说，只要是页面的规则比较大众就可以适配成功，这个问题与你刚刚发的 linux 的问题一样，都是页面「太不按照规则」造成的。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
