### ISSUE TITLE
可否加一个删除页脚的选项

### ISSUE THREAD

**Issue by harisonkhlil** [Kenshin/simpread#3370]
<img width="962" alt="CleanShot 2022-02-02 at 12 49 11@2x" src="https://user-images.githubusercontent.com/70578017/152094812-ac74fb42-feb9-4fc7-a41e-56b021da85fd.png">
或是会员享有此功能。
春节快乐🧨

**Comment by Kenshin** [comment]
嗨，春节快乐。

不需要那么「麻烦」，只需要使用 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 就行了。

```
sr-rd-footer {
    display: none!important;
}
```
