### ISSUE TITLE
知乎回答导出PDF，会出现页尾与下页首文字被切掉一半高度

### ISSUE THREAD

**Issue by helloyan** [Kenshin/simpread#3375]
问题如主题，附件是例子
[有没有可能我们的英语教材根本就不适合让我们学好英语-.pdf](https://github.com/Kenshin/simpread/files/8007881/-.pdf)

**Comment by Kenshin** [comment]
嗨，请给出 URL，另外是否使用了同步助手导出方案？

**Comment by Kenshin** [comment]
补充下：如果没有使用后者的话，这算是「正常」情况，调用的 Chrome 自带打印 PDF 方案就存在这个问题，而同步助手方案则能有效降低这个问题的发生。

**Comment by helloyan** [comment]
https://www.zhihu.com/question/511386158
使用的同步助手

**Comment by Kenshin** [comment]
已确认，确实存在类似的问题，我看看如何优化。

不过，并不是每个页都存在类似问题，你可以多试试其它非论坛类，看看是否存在此问题。

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄

**Comment by helloyan** [comment]
是我哪里用的不对吗，上面的知乎链接，我打印出来的效果和之前并没有区别

**Comment by Kenshin** [comment]
> 是我哪里用的不对吗，上面的知乎链接，我打印出来的效果和之前并没有区别

哈哈，那就肯定是不对的，如果使用 PDF 高级打印方案的话，成功导出后会在右上角有提示打开 PDF，如果没有这个提示，则用的不是此方案。

**Comment by helloyan** [comment]
找到设置地方打开后好了

不过目前仍然无法导出PDF，附上日志，随便一个页面都是如此，系统Win1
[simpred_sync.log](https://github.com/Kenshin/simpread/files/8882976/simpred_sync.log)
0

**Comment by helloyan** [comment]
![image](https://user-images.githubusercontent.com/1699033/173207954-bfc83a96-c187-4966-9f1f-7b5a25cd4a6c.png)
debug了一下，好像图上断点位置的参数应该都是对的，最后的问题是没能生成html文件，和日志里提示一致

**Comment by Kenshin** [comment]
@helloyan 

嗨，我昨天看到你的日志了，但忘记回复了 😂 

估计是你没有安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件造成的。

**Comment by helloyan** [comment]
装了以后报其他的错了，而且日志文件没有内容追加进去了
![image](https://user-images.githubusercontent.com/1699033/173232353-70642072-44b4-4f0d-97cc-9fa674d4bb6f.png)

**Comment by Kenshin** [comment]
操作什么功能出现的这个错误的？详细说下你的步骤。

另外，这个功能是没问题的步骤明天给你看下导出的 PDF

**Comment by helloyan** [comment]
就是上面的导出PDF，目前仍未成功，使用的打印按钮
![image](https://user-images.githubusercontent.com/1699033/173236147-9bc40661-b4ee-4e40-ae6e-97f9bcff2ee5.png)

**Comment by Kenshin** [comment]
在插件中也能导出，试试这个方式。

**Comment by helloyan** [comment]
哪个插件可以导出

**Comment by helloyan** [comment]
会有个 ‘本地版本与安装版本不一致，是否安装新版本？“ 提示，但是很快自动刷新掉了，然后插件安装不上

**Comment by helloyan** [comment]
另外忘记补充说了，我用的是opera，除了application不能装其他跟chrome应该是一样的

**Comment by Kenshin** [comment]
emm 最好用 Chrome 确认下是否可用。

插件安不上的问题可以通过 https://github.com/Kenshin/simpread/discussions/2342 解决。

**Comment by helloyan** [comment]
测试了chrome一样的情况，怀疑插件配置问题，如何可以只导出高级账户信息，其他的配置一律清空

**Comment by Kenshin** [comment]
选项页 → 共通 里面有个重置（非清除）的选项。

**Comment by Kenshin** [comment]
okay 搞定就好。

至于你遇到的问题，我也不清楚，因为没法调试。

**Comment by helloyan** [comment]
chrome没有问题了，opera仍然是之前的错误，有时间可以看看，其他的功能opera都是正常的
