### ISSUE TITLE
增加衬线字体的支持？

### ISSUE THREAD

**Issue by huLter** [Kenshin/simpread#338]
是否可以增加衬线字体的支持呢？毕竟长时间阅读的话感觉衬线比较舒服。现在的话只能通过自定义样式来使用衬线字体。

**Comment by Kenshin** [comment]
明天发布 1.1.1 可以方便的在阅读模式页面更改自定义字体样式。
另外，增加了新字体：「思源宋体」。

**Comment by huLter** [comment]
那就方便很多了。十分感谢！

**Comment by Kenshin** [comment]
已升级到 1.1.1 此 issues 将关闭。
