### ISSUE TITLE
提示扩展端需要先确保你的账户为高级账户后才能使用此功能

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#3381]
已经是高级账户了，为什么还是会提示这个？
![image](https://user-images.githubusercontent.com/8450915/152688154-6bce0ed2-62a1-4082-8b95-4dd1ef13cfe0.png)

**Comment by Kenshin** [comment]
嗨，估计是你首次绑定时没有重启浏览器造成的，你可以这样做：

1. https://github.com/Kenshin/simpread/discussions/1575 （如果你的界面与链接提示不太一样，则直接第二步
2. 重启浏览器
3. https://github.com/Kenshin/simpread/discussions/1570

**Comment by zz-panacea** [comment]
> 嗨，估计是你首次绑定时没有重启浏览器造成的，你可以这样做：
> 
> 1. [取消授权（取消当前设备的高级账户资格） #1575](https://github.com/Kenshin/simpread/discussions/1575) （如果你的界面与链接提示不太一样，则直接第二步
> 2. 重启浏览器
> 3. [授权登录（如何使用第三方登录简悦的高级账户） #1570](https://github.com/Kenshin/simpread/discussions/1570)

按照这个步骤操作后, 还是会提示扩展端需要先确保你的账户为高级账户后才能使用此功能. 请问如何解决呢?

**Comment by Kenshin** [comment]
@zz-panacea 

有可能你的 UID 不是高级账户 UID。你可以通过 https://www.yuque.com/kenshin/simpread/bvcunx 找回你的高级账户 UID。
