### ISSUE TITLE
建议在edge浏览器上的语音发音能支持微软的在线发音xiaoxiao.

### ISSUE THREAD

**Issue by monywoex** [Kenshin/simpread#3386]
在微软的edge浏览器上的语音朗读的xiaoxiao在线语音发音引擎听起来特别的自然,目前可否在已有的语音发音功能上支持调用这个在线发音?

**Comment by hellozgl** [comment]
支持，也有这样的想法。目前的简悦版本好像还没有TTS功能吧？

**Comment by Kenshin** [comment]
嗨，各位，简悦本来就可以支持此功能，细节看 https://github.com/Kenshin/simpread/discussions/3387
