### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by dw12278** [Kenshin/simpread#3396]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **Chrome 98.0.4758.88**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://www.liaoxuefeng.com/wiki/1252599548343744/1306581182447650>

**请描述你的问题**

> textarea组件内容没有获取到

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/19491217/153561216-58cc8e2c-2c4f-4381-ade9-a7fa9c7756b5.png">
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/19491217/153561343-cf7a0063-ef4a-4325-9790-234f00b41a94.png">

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是代码段的问题，会集中在 #500 处理。

关闭此 Issues 修复后会通知你~
