### ISSUE TITLE
能不能扩大图片？

### ISSUE THREAD

**Issue by mokongh** [Kenshin/simpread#34]
在煎蛋网看图集（比如没品+4chan笑话集）的时候，图片太小或太长会导致看不清图片内容，希望添加点击图片查看原图之类的功能orz

**Comment by Kenshin** [comment]
可以的，这个功能已经在 TO-DO 里面了，只是暂时没有在 REAME.md 里面写出，README.md 只是下个版本的功能。

![Imgur](http://i.imgur.com/fzpcvwy.png)

感谢建议~

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [Lightbox](https://simpread.ksria.cn/plugins/details/VQOZdNET2d) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
