### ISSUE TITLE
微信md显示java代码有问题

### ISSUE THREAD

**Issue by luo276785794** [Kenshin/simpread#340]
https://mp.weixin.qq.com/s/GBGlttLgQA2XrMcRTUUTOw

关键字和方法名之间没有空格.
publicvoidmethod()

**Comment by Kenshin** [comment]
这仅仅是个例，你可以增加自定义样式，调整 word-spacing 的值即可解决。

![image](https://user-images.githubusercontent.com/81074/41389220-1609dd28-6fc2-11e8-8bdb-293d5c334be3.png)
