### ISSUE TITLE
站点集市安装适配站点失败

### ISSUE THREAD

**Issue by wongtx** [Kenshin/simpread#3401]
在【站点集市】选择适配网站进行安装时，点击安装，跳出“当前站点已安装成功，两秒后自动刷新”。随后在【站点集市】中看到还是空空如也。（见下图）是高级用户账号，确保已刷新。
![image](https://user-images.githubusercontent.com/46996862/153687022-e052fb0b-4489-4eec-a6e3-8afb8692a294.png)
![image](https://user-images.githubusercontent.com/46996862/153687096-487abeaf-2fa9-4e2c-a365-9f77717ce75a.png)

**Comment by Kenshin** [comment]
是不是使用了同步助手？如果是的话，解决方案 https://github.com/Kenshin/simpread/discussions/2342 （跟插件是一样的步骤）

**Comment by wongtx** [comment]
已尝试推荐的方法。已恢复正常，感谢Kenshin

**Comment by Kenshin** [comment]
Cool 搞定就好，我关闭这个 Issues 了~

对了，最近有个简悦用户的抽奖活动，感兴趣的话，可以试试手气 [2022 年度抽奖活动开始啦](https://zhuanlan.zhihu.com/p/465758152)
