### ISSUE TITLE
mac 版同步助手网络连接的请求每次启动时都会弹出

### ISSUE THREAD

**Issue by sheng-chen** [Kenshin/simpread#3407]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS Monterey Version 12.2.1**

- 浏览器版本 **Chrome 98**

- 简悦版本 **2.2.0**

**请描述你的问题**

> 两个问题：
1. 每次打开 mac 版同步助手， macbook 都会弹出请求：是否允许同步助手网络连接？
即使我在防火墙里已经设置了允许同步助手网络连接，仍然会弹出。我电脑上的其它软件都没有这个问题。
2. 在不显示窗口界面的情况下，同步助手也会在 Dock 中常驻，这完全没必要，应该隐藏 Dock 中的图标。

**截图**
<img width="256" alt="CleanShot 2022-02-12 at 16 53 49@2x" src="https://user-images.githubusercontent.com/33170624/153718414-54a1cc7f-e4a7-4426-8002-f4f400f6acf5.png">

**Comment by Kenshin** [comment]
> 每次打开 mac 版同步助手， macbook 都会弹出请求：是否允许同步助手网络连接？

解决方案 https://github.com/Kenshin/simpread/issues/2100#issuecomment-850217405

> 在不显示窗口界面的情况下，同步助手也会在 Dock 中常驻

下个版本解决。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 解决网络使用时反复提示的问题

新版运行后应该没有此问题了。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
