### ISSUE TITLE
天涯论坛头像无法加载

### ISSUE THREAD

**Issue by amitbha** [Kenshin/simpread#341]
firefox 60.0
simpread 1.1.1

头像一直在转圈，无法加载。删掉头像匹配轨则，正文无法显示。
看来规则之间有莫名的关联。
只显示头像名称也做不到。

**Comment by amitbha** [comment]
试了多个页面，均是如此
不过天涯论坛确实没头像，跟其它论坛不一样，只有名字
但没有只显示名称的功能

**Comment by Kenshin** [comment]
没有发现你说的情况（虽然站点适配器里面有头像的代码，但那只是为了让其显示 论坛类页面的设定而已）

![image](https://user-images.githubusercontent.com/81074/41389289-7fc373f0-6fc2-11e8-853f-c1d09a14c5aa.png)

**Comment by amitbha** [comment]
我的是这样的
![default](https://user-images.githubusercontent.com/4060625/41419808-8c20e926-7025-11e8-8efe-12289f47a563.png)

**Comment by Kenshin** [comment]
请确保 简悦 为 1.1.1 同时，请更新更新同步适配列表。

我怀疑是你之前修改了 全局的适配规则，造成的。

**Comment by amitbha** [comment]
确实是1.1.1版，浏览器火狐
在配置里清除了数据，同步了适配列表
但还是如此

**Comment by Kenshin** [comment]
emmm 
虽然不知道你的问题是为什么，但可以有办法绕过这个问题，加入如下代码：

```
sr-rd-mult-avatar {
   display: none!important;
}
```

位置在：
![image](https://user-images.githubusercontent.com/81074/41446552-cb5e30d2-7082-11e8-933a-56388bff2c80.png)

**Comment by amitbha** [comment]
可以了 ☻
