### ISSUE TITLE
微信公众号文章字体很虚

### ISSUE THREAD

**Issue by dwSun** [Kenshin/simpread#3421]
https://mp.weixin.qq.com/s?__biz=MjM5MDE0Mjc4MA==&mid=2651105737&idx=1&sn=ec42e8bc83975912a80644e06b8cea6f&chksm=bdb9519a8aced88c118183a6219eaf5d41281c99610c824c77ef604efc02372c7930adfefb19&scene=21#wechat_redirect

<img width="803" alt="image" src="https://user-images.githubusercontent.com/5899962/153819288-a89af472-8fa4-4fac-b112-84328233cf95.png">

如图，不管选哪个配色方案，似乎字体的颜色都是固定的。
csdn 和知乎没有碰到类似的问题

**Comment by dwSun** [comment]
通过 #2561 解决了

**Comment by Kenshin** [comment]
> 不管选哪个配色方案，似乎字体的颜色都是固定的。

哈哈，恭喜自救成功，但这个问题不是简悦的，确实可以暂时通过关闭功能解决，但其它页面建议还是以开启它为主。
