### ISSUE TITLE
如何取消显示摘要？

### ISSUE THREAD

**Issue by sheng-chen** [Kenshin/simpread#3423]
请问如何**默认取消**摘要显示？摘要就是下图中标题下的以省略号结尾的那一行。每次打开一个网站都会显示。

<img width="895" alt="NBA Dennis Schröder zu den Houston Rockets getradet Was sind nun die Optionen des Deutschen? 2022-02-14 at 17 41 49" src="https://user-images.githubusercontent.com/33170624/153907310-ab92b237-040b-49d0-a67a-f12715c474ab.png">

**Comment by Kenshin** [comment]
嗨，你可以使用这个插件 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v
