### ISSUE TITLE
android端支持问题

### ISSUE THREAD

**Issue by tk1302700** [Kenshin/simpread#3424]
你好，我想问一下简悦对于android端近期有开发计划吗？还是只能使用作者目前推荐的KIWI浏览器？另外考虑支持思源笔记吗？

**Comment by Kenshin** [comment]
嗨，肯定有原生的 App 计划的，你可以订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会官方渠道通知你。

至于思源笔记的，你可以使用 复制 MD 到剪切板来做个中转，可以支持任意 App 的。
