### ISSUE TITLE
代码段增强插件报错提示

### ISSUE THREAD

**Issue by wyrain** [Kenshin/simpread#3428]
转码网址：
https://mp.weixin.qq.com/s/st0KdsRpSb-ekoJNcp_Ruw
报错提示：
![e28e902908e388259d198da9cee5673](https://user-images.githubusercontent.com/20262079/153992454-b7be826f-e4fc-4714-87c5-56fbf8afcc52.png)
原始网页截图（部分）：
![be26d44b54f4e0ebeaa6fd600bcd810](https://user-images.githubusercontent.com/20262079/153992629-668801a0-3ce1-4d50-96f8-f32a6b202442.png)
转码后网页截图(部分)：
![f61083ae2d1753cf9b1d0317ad91bd0](https://user-images.githubusercontent.com/20262079/153992561-2c67168d-0a27-4a88-a468-22542afbbac4.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
