### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by veitchzheng** [Kenshin/simpread#3434]
代码块显示效果![image](https://user-images.githubusercontent.com/20170306/154186502-07606f2d-dac9-432d-9ac9-4142b67cb962.png)
原效果：![image](https://user-images.githubusercontent.com/20170306/154186531-73e5f5fb-d25c-4ec6-89df-6b3471657182.png)

**Comment by veitchzheng** [comment]
页面地址:https://mp.weixin.qq.com/s/CEh5ZPTPzP51H-sBa9RjlQ

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
