### ISSUE TITLE
高级账户已启用同步助手导出PDF仍提示升级为高级账户无法本地导出PDF

### ISSUE THREAD

**Issue by zztt** [Kenshin/simpread#3435]
- 操作系统 windows10 x64

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 简悦助手x64 1.01

- 问题描述：

已经购买的高级账户，并且绑定激活，已下载并启用同步助手。
打开网页阅读模式，尝试导出PDF提示升级为高级账户，显示打另存为PDF的窗口，无法本地导出PDF。
当时购买高级账户就是想有更好的PDF导出效果。
<img width="1920" alt="Snipaste_2022-02-16_20-09-49" src="https://user-images.githubusercontent.com/4332986/154262267-b4221e03-df08-43b0-b6fe-72c6e259e98d.png">

**Comment by Kenshin** [comment]
嗨，我看到你又 Close 这个 issues 是搞定了吗？

**Comment by zztt** [comment]
抱歉，已经搞定了，所以close issue，谢谢。

Kenshin Wang ***@***.***> 于2022年2月17日周四 10:50写道：
