### ISSUE TITLE
关于标注的一些建议

### ISSUE THREAD

**Issue by windily-cloud** [Kenshin/simpread#3437]
先阐述一下我的工作流：
1. 左边窗口使用浏览器查找资料，右边窗口开obsidian，复制核心概念和回链地址，以列表形式放置在obsidian中。
2. obsidian通过excalidraw自动化脚本，生成核心概念的类似思维导图的页面。拖动并组织核心概念，不清楚的通过回链回到浏览器中。
3. 将已有组织概念重新归纳形成永久笔记。

简悦带给我的提高：
1. 阅读模式提高web可读性，根据h1,h2生成标注，进一步提高了效率。
2. 能自定义模板，保存注释标注到本地，非常丝滑。

痛点：
1. 阅读模式只能开在单页面上，但阅读文档，搜集材料，往往需要不同站点跳转，这时候阅读模式压根不可用。
2. 回链只能回到原网页，不能定位到具体的字段。如果需要定位，还需要开阅读模式，再点击对应的字段。

不成熟的想法：
1. 针对第一个痛点，我想能不能在popup页面上添加一种新的标注类型，即全局标注。普通页面也能右键或选择和弹出菜单标注和注释，标注和注释保存在storege中，这样跳转任意页面都不会丢失。点击popup页面显示当前已有标注。当然，如果能像侧边栏那样会更好。
2. 针对第二个痛点，text  fragment能轻松的定位到任意页面任意位置——这是关于该方法的描述：[text-fragment-W3C Report](https://wicg.github.io/scroll-to-text-fragment/#generating-text-fragment-directives)。生成text fragment的链接已有方法，见：[text-fragment拓展](https://github.com/GoogleChromeLabs/link-to-text-fragment)。

总结一下我的想法：多个不同域的网页共用同一标注，提取网页任意位置text fragment的链接，发送到obsidian中。

如果我哪里说得不恰当你能指出，或者你有任何的建议，我都非常高兴。赞美简悦的话我就不多说了👍👍👍，本来想自己上手弄，结果看了一天浏览器扩展开发，不得要领。

**Comment by Kenshin** [comment]
嗨，谢谢使用简悦以及你的想法，分别一一回复下。

> 阅读模式只能开在单页面上，但阅读文档，搜集材料，往往需要不同站点跳转，这时候阅读模式压根不可用。

不可用的意思是指什么？无法进入阅读模式吗？如果是的话，往下看有关于此的说明。

> 回链只能回到原网页，不能定位到具体的字段。如果需要定位，还需要开阅读模式，再点击对应的字段。

不需要进入阅读模式，你可以看看 https://github.com/Kenshin/simpread/discussions/3350 里面的视频，简单的说：

简悦可以将阅读模式以快照（包含标注）的形式保存在你的本地，然后利用链接提到的方式，外链到 Obsidian，从 Obsidian 点击后直接查看。

要想实现这点，链接中已经提到了：需要使用知识库，如何配置也可以 [看这里](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)。

> 我想能不能在popup页面上添加一种新的标注类型，即全局标注。普通页面也能右键或选择和弹出菜单标注

会考虑的，但目前的标注还是建立在阅读模式基础上，但你可以使用 https://github.com/Kenshin/simpread/discussions/3233 它能让任意内容都可以进入阅读模式

> text fragment能轻松的定位到任意页面任意位置——这是关于该

text fragment 方案的弊端是：一旦你在页面点击了，它的「高亮」就消失了。不过，简悦是支持 text fragment 方案的，但因为弊端所以我没有太宣传它。

**Comment by windily-cloud** [comment]
谢谢你的回答，我发现我看文档还是看得不够仔细，你提点了一下我才发现`{{an_org_uri}}`就是text fragment，这就解决了我第二个问题。与此同时，我通过自动化方案，解决了在标注的同时同步到ob文件里，简悦真的很牛逼。

> 不可用的意思是指什么？无法进入阅读模式吗？如果是的话，往下看有关于此的说明。

我这里说的不可用指的是频繁切换网址，进入阅读模式有点麻烦。我知道可以设置自动进入阅读模式，但有些文档（如vue的官方文档）不进入阅读模式阅读体验可能更好一点。
![image](https://user-images.githubusercontent.com/30640638/154689384-384fbfa2-eae5-40de-87f3-b00442f44a39.png)
会出现：
1. 代码块行号错位
2. 原网页中嵌入的codepen在线编辑会被忽略。
3. 原网页的导航在阅读模式被清除，需要退出阅读模式导航到其它页面，再进入阅读模式。

![image](https://user-images.githubusercontent.com/30640638/154689682-988b7ae8-847b-4bbd-9b77-899911bb3d67.png)

简悦阅读模式适配这样小众的网站，没什么必要。如果能在普通模式下标注就能自主选择阅读体验相对更好且更方便的方案，而且这样的话能全局标注（许多不同的网站标注在同一地方），所以我觉得在普通模式下标注是另一个好的选择。

普通模式下标注我觉得有几个优点：
1. 我所谓的全局标注：这在搜集材料的时候很有用
2. 一切皆能标注和定位：标注github的wiki，issue等，标注vue文档，MDN文档这样内置了奇奇怪怪东西等。
3. 无须进入阅读模式：免除阅读模式的进入退出操作，也对阅读模式不适配的网页提供一种解决方案 。

至于你提到的text fragment的弊端，我觉得这和简悦阅读模式是一个互补的操作。有些时候我只要定位到内容就好了，我点击回链看的应该就是高亮处，高亮消失了也无所谓。

再次感谢你的回答。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3437#issuecomment-1044632400

okay 收到，确实存在你说的情况，我会优化它。

> 谢谢你的回答，我发现我看文档还是看得不够仔细

哈，不能这么说，文档写的并不是很完美，而且因为我提到的「缺陷」问题，导致我从未谈过其这个事情。（从我的角度看，能根据上下文的简单提示，找到文档中具体的说明，已经很🐂 掰了。

> https://github.com/Kenshin/simpread/issues/3437#issuecomment-1044566813

至于你提到的适配问题，确实如你所说，并不是每个页面都 100% 适合阅使用读模式。以及你的设想，我会考虑的。

另外，你能否使用 Telegram ？如果可以的话，请进群 https://t.me/simpreadgroup 然后私聊我。

**Comment by windily-cloud** [comment]
我已经在tg私聊大佬了，并分享了我目前阅读流程的使用体验，现在唯一限制我的就是全局标注了。哈哈，简悦真好用，我得写个流程发到obsidian的论坛上。

**Comment by Kenshin** [comment]
> 我已经在tg私聊大佬了，并分享了我目前阅读流程的使用体验，现在唯一限制我的就是全局标注了。哈哈，简悦真好用，我得写个流程发到obsidian的论坛上。

（如果能那就太棒了！）必须地~  💪  👍

**Comment by hellozgl** [comment]
telegram的群链接能发一下吗，之前加过几次都加不进去，不知道什么原因。但其他的tg群都能正常加入 @Kenshin

**Comment by windily-cloud** [comment]
> 如果可以的话，请进群 https://t.me/simpreadgroup 然后私聊我。

@hellozgl 这不就是链接吗？

**Comment by Kenshin** [comment]
@hellozgl 进去后需要有个验证 Bot，估计你没有验证导致的。
