### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by fqy-fqy** [Kenshin/simpread#3440]
发生问题的地址: <https://wenku.baidu.com/view/0309d4a6944bcf84b9d528ea81c758f5f71f2953.html?fr=income11-wk_app_search_ctrX-search>

**Comment by Kenshin** [comment]
嗨，这类页面是不可以被适配的，我关闭这个 Issues 了。

抱歉，之前漏掉了这个 issues  😂
