### ISSUE TITLE
无法识别此页面

### ISSUE THREAD

**Issue by SkysCrystal** [Kenshin/simpread#3443]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **win10**

- 浏览器版本 **Chrome 98.0.4758.102**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://blog-issei.vercel.app/nobelium_tips>

**请描述你的问题**

无法正确识别，基于 [Nobelium](https://github.com/craigary/nobelium) 生成的博客页面的正文内容。无法快速保存页面内容至 Notion 。

**截图**
![image](https://user-images.githubusercontent.com/49473463/154841957-c8301a41-7a91-48c3-9b5c-4dab36e9671c.png)

**Comment by Kenshin** [comment]
这是我的截图

![image](https://user-images.githubusercontent.com/81074/154878849-fd76842c-d8a5-4269-9942-350679b12837.png)

看起来是没有问题的。

**Comment by SkysCrystal** [comment]
我现在打开也显示没问题了，谢谢！

**Comment by Kenshin** [comment]
okay 没问题就好。
