### ISSUE TITLE
设置标题出现乱码

### ISSUE THREAD

**Issue by ZED21King** [Kenshin/simpread#3444]
该问题的截图（最近这几天都这样，重装了也没用）：
<img width="1265" alt="微信图片_20220221123657" src="https://user-images.githubusercontent.com/100110105/154889983-41fcdd69-5fd8-4f38-81a2-26263f7caef1.png">

**Comment by ZED21King** [comment]
并且，会有些服务授权失败，比如Notion、坚果云等
![Uploading 1.png…]()

**Comment by ZED21King** [comment]
并且，会有些服务授权失败，比如Notion、坚果云等
<img width="395" alt="1" src="https://user-images.githubusercontent.com/100110105/154890553-102a681f-6e2a-476d-8fb5-fd73f5a59fd8.png">

**Comment by Kenshin** [comment]
乱码的解决方案 → https://github.com/Kenshin/simpread/discussions/1639

Notion 的解决方案 → https://github.com/Kenshin/simpread/discussions/1773

调用失败的解决方案 → https://github.com/Kenshin/simpread/discussions/1567

**Comment by ZED21King** [comment]
> 乱码的解决方案 → #1639
> 
> 概念的解决方案 → #1773
> 
> 调用失败的解决方案 → #1567

好的谢谢老哥

**Comment by Kenshin** [comment]
哈，客气了。 😀 

遇到问题可以去 https://github.com/Kenshin/simpread/discussions 翻翻，基本上都能找到解决方案。

**Comment by ZED21King** [comment]
嗯嗯，好的，我还想问下ipad的阅读器模式，有没有类似pc端一样，右下角有这种能快速导出到有道云笔记，云盘这类的功能？
![3](https://user-images.githubusercontent.com/100110105/154901220-53105dad-3a1c-4285-ad4f-4b3baf401a92.png)
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/100110105/154901252-3b15162c-6ae8-436c-b361-61f0055757ca.png">

**Comment by ZED21King** [comment]
嗯嗯好的，不过我还想问下ipad的阅读器模式，有没有类似像pc端一样，右下角有这种能快速导出到有道云笔记，云盘的这种功能，而不必再点击分享，找到JSBox，选择简悦阅读器，才有一些功能，重点是还没有有道云笔记的导出功能；
![3](https://user-images.githubusercontent.com/100110105/154902798-08e84981-9a66-4a55-b1f2-c41bcc1844af.png)
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/100110105/154902814-ff96bcf9-55a7-4ef1-b24d-04f06163ead1.png">
<img width="617" alt="4" src="https://user-images.githubusercontent.com/100110105/154902886-0d937499-5096-458e-aa09-7eba0deabe4f.png">

**Comment by Kenshin** [comment]
> 不过我还想问下ipad的阅读器模式，有没有类似像pc端一样，右下角有这种能快速导出到有道云笔记

这个模式下右下角应该有控制栏吧？但你说的有道暂时没有支持。
