### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by bitterandbetter** [Kenshin/simpread#3445]
发生问题的地址: <https://mp.csdn.net/mp_blog/manage/article?spm=1000.2115.3001.5448>

**Comment by Kenshin** [comment]
嗨，这个页面我没法访问，所以无法判断。

至于无法适配的解决方案，你可以看看提供的 [解决方案](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22read+mode%22)

另外，如果这个页面只能特定的用户访问，是不会被适配的。
