### ISSUE TITLE
正文字体全部变为灰色的问题

### ISSUE THREAD

**Issue by MusherM** [Kenshin/simpread#3448]

**Comment by Kenshin** [comment]
请把地址给我，否则我没法判断。

**Comment by MusherM** [comment]
> 请把地址给我，否则我没法判断。

不是个别网站的问题 所有网站都这样
电脑是m1 mac 刚安装的时候没什么问题 不知道为什么突然就这样了

**Comment by Kenshin** [comment]
跟 Mac M1 无关，因为我也是。

emmm 我大概知道什么问题了，是不是你改了系统的暗色模式？

看看这个解决方案 https://github.com/Kenshin/simpread/discussions/3164

**Comment by MusherM** [comment]
收到，确实是macOS的暗色模式问题，为了正常使用简悦的浅色阅读模式，已经关了系统的自动切换深色模式了，感谢回复

**Comment by Kenshin** [comment]
小事情，搞定就好
