### ISSUE TITLE
微信文章行内公式图片解析错误

### ISSUE THREAD

**Issue by hacker-jerry** [Kenshin/simpread#3449]
如图，
<img width="983" alt="image" src="https://user-images.githubusercontent.com/57279550/155054897-173d15a0-0ef6-48e2-b710-7719e25e3f51.png">
行内公式巨大，关闭预加载也没有用，希望作者可以解决一下，已经购买了高级会员。

**Comment by hacker-jerry** [comment]
文章链接：https://mp.weixin.qq.com/s/xiIx7oETktJRQ3GLkozQjA

**Comment by Kenshin** [comment]
嗨，收到。

微信公式是图片，但结构和逻辑都不一样，所以很难统一，你可以试试 https://github.com/Kenshin/simpread/discussions/2561 能否解决。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
