### ISSUE TITLE
开启 simpread，https://noto.so/dashboard 页面会挂（需要注册）

### ISSUE THREAD

**Issue by futantan** [Kenshin/simpread#3450]
关闭 simpread 则没有问题

**Comment by SkysCrystal** [comment]
发现确实存在这个问题。 
显示 `Application error: a client-side exception has occurred (see the browser console for more information).`
刷新数次，会有一到两次可以正常显示。

**Comment by futantan** [comment]
https://demo.vercel.pub/
这个网站也会有同样的问题。是不是 simpread 有 windows 上的一些属性和 nextjs 冲突了？

**Comment by Kenshin** [comment]
嗨，各位，我测试了下，确实有这个问题，解决方案

选项页 → 高级设定 → 词法分析引擎，关闭下图选项即可。

![](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)

详细可以看下 https://github.com/Kenshin/simpread/discussions/2347 的简单说明

**Comment by futantan** [comment]
感谢 @Kenshin ！
我想定位一下技术上的原因，目前我使用的是 NextJS，图片是使用的 next/image
是这个造成的问题吗？如果是的话，考虑到 NextJS 作为最流行的 React 框架，是否可以考虑做兼容？
因为Simpread 的用户量极大，我自己也是用户，作为一个开发者，都定位了半天，而作为普通的用户的话，是很难找到解决拌饭的，我们可能就直接损失了这个用户，因为网页直接不可用了。

**Comment by Kenshin** [comment]
@futantan 

哈哈，不是 next/image 这个问题，所以更谈不上  NextJS 这个情况了。

问题很简单，我当时不知道怎么抽筋了，做了一个傻X逻辑，细节看 https://github.com/Kenshin/simpread/discussions/2347

![image](https://user-images.githubusercontent.com/81074/155254173-00df16aa-fa6e-4618-aaa8-4b2b27501a2b.png)

简悦目前**除了这一个地方外，其余代码均不涉及到对原页面代码的改动**。而 https://demo.vercel.pub/ 应该有防止代码改动的逻辑，所以出现了错误提示。

如果你关闭了这个选项，则原页面的内容都不会被改动。

**Comment by futantan** [comment]
明白这个问题的原因了。
https://demo.vercel.pub/  的代码在： https://github.com/vercel/platforms 业务上并没有防止代码改动的逻辑。
我的网站中（noto.so）也没有，我猜测是 NextJS 做了这件事情。上面说的选项，是默认开启的吗？

我关注的点在于，一个普通的 Simpread 用户，在访问我们网站的时候，能够正常使用。
（比如 Simpread 有没有默认的黑名单之类的机制，当然这只是我拍脑门想的一个解法）

**Comment by Kenshin** [comment]
> 只能自己填写，

是的。但这个功能从去年五月份出现到现在，除了维基系的外，这是我遇到的第二次反馈，影响面非常小。


> 比如 Simpread 有没有默认的黑名单之类的机制，当然这只是我拍脑门想的一个解法

不用拍脑门，我在很多年前我就拍过了，所以 黑名单 / 白名单 / 排除列表（不自动进入阅读模式）全都有了，细节 [看这里](http://ksria.com/simpread/docs/#/URL%E7%BC%96%E8%BE%91%E5%99%A8)。

**Comment by Kenshin** [comment]
补充下：

> 维基系的网站直接免疫此问题，维基旁系的网站也都可以通过之前的提示解决掉。

**Comment by futantan** [comment]
<img width="1144" alt="CleanShot 2022-03-13 at 13 17 15@2x" src="https://user-images.githubusercontent.com/6268441/158046194-811600be-3552-48f3-b908-813d1db114ee.png">
很多用户都遇到了这个问题。我有什么解决办法吗？
监测到这个错误，提示用户 simpread 不兼容？

**Comment by futantan** [comment]
上面的是 sentry 的截图，22 个用户，发生了 37 次

**Comment by Kenshin** [comment]
> 上面的是 sentry 的截图，22 个用户，发生了 37 次

嗨，我不是说过 https://github.com/Kenshin/simpread/issues/3450#issuecomment-1048408406 解决方案了吗？

请问你的 noto 的负责人吗？如果是的话，可以试试帮忙把这个问题贴到这个 issues  或通过你们的渠道告诉大家，如有需要我可以帮忙在简悦的渠道发布一下。

**Comment by Kenshin** [comment]
另外，noto.so 的负责人是 JimmyLv 吗？如果是的话，我也可以联系他。

**Comment by futantan** [comment]
有没有用户感知不到的处理方式？

**Comment by Kenshin** [comment]
> 有没有用户感知不到的处理方式？

暂时没有，解决方案：

1. noto.so 修改下结构
2. 简悦升级

后者近期肯定不会有升级，升级计划肯定在 Roadmap 中。
