### ISSUE TITLE
新站适配：news.mydrivers.com

### ISSUE THREAD

**Issue by wangkiyo** [Kenshin/simpread#3453]
**请说明发生问题的环境**

操作系统 Windows 10

浏览器版本 Chrome 95.0.4638.69

简悦版本 2.2.0.520

发生问题的地址 https://news.mydrivers.com/1/816/816367.htm

**请描述你的问题**

打开这个页面的时候，会跳出广告页
https://m.zhuanzhuan.com/u/recovery/index.html#/index?recoveryFrom=91

**截图**

那就截个动图吧

![360ChromeX_tUxUkx5cb0](https://user-images.githubusercontent.com/45029102/155297259-4302cb4f-116f-4820-96a7-6cb1f3222f06.gif)

**Comment by Kenshin** [comment]
收到，首先这肯定不是简悦的「广告」，简悦是不会有这些东西的。 😂 

简单的研究了下，这是个空白的链接，看下图

![image](https://user-images.githubusercontent.com/81074/155300045-29e90f8a-a1d7-430e-8e24-40a1c0d9a0d4.png)

在进入阅读的时候把这个内容也生成了阅读模式

![image](https://user-images.githubusercontent.com/81074/155300097-592ae144-54e9-4286-b979-db42bb1e3e5f.png)

简悦为了方便加载图片，当图片加载失败的时候，会重新加载它，所以点击触发了这个「广告」

![image](https://user-images.githubusercontent.com/81074/155300180-a0644f88-9fb4-48c9-b1a8-dbd72bcb1405.png)

## 解决方案

适配这个页面就没问题了。

***

适配后我会在这里通知你。

**Comment by wangkiyo** [comment]
首先谢谢 Kenshin 的回复。
我很肯定这个不是简悦的广告，因为广告页的代码在原站点里。
另外这个站的长文，有上一页下一页的文章，有时也会显示错位，并且无法翻页，比如这个：
https://news.mydrivers.com/1/819/819252.htm

**Comment by Kenshin** [comment]
嗨，你可以自己试试 [站点编辑器](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8) 提供的说明。

**Comment by wangkiyo** [comment]
@Kenshin 研究了个把星期的“站点编辑器”，始终未能掌握精髓，以此网页（https://news.mydrivers.com/1/820/820888_1.htm）为例，想去除此区块内容
![image](https://user-images.githubusercontent.com/45029102/158987400-3317db7f-b9a9-4144-a40c-f38466aef2b5.png)
在“隐藏列表”加入了
```
<p class='end'>
[[[$('.end')]]]
[[[$('.end').parent()]]]
[[[$('sr-rd-content .end')]]]
[[[$('sr-rd-content .end').parent()]]]
```

以上种种都不行，使用“隐藏任意元素”后，添加的类似这种形式的定位会因为不同网页的div元素问题定位错误。
```
[[`/html[1]/div[1]/sr-read[1]/sr-rd-content[1]/a[1]`]]
[[`/html[1]/div[1]/sr-read[1]/sr-rd-content[1]/div[1]/div[1]/div[1]/ul[1]`]]
```

自定义CSS使用 `p.end{display:none;}`应该也是因为定位元素的问题无法实现。

如若有空，还望帮忙看看。
如果可以增加一个执行自定义js可能也是个不错的思路

**Comment by Kenshin** [comment]
嗨，试试 `[['<p>- THE END -</p>']]`

![image](https://user-images.githubusercontent.com/81074/158992905-addb96d9-fa36-40bd-90ab-bb4bb146c5d3.png)

另外看你的描述，是否了解一些 JS 和 CSS 基础？如果是的话，可以使用 JS 来写获取方案，如果对这块感兴趣的话，可以发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3453

我给你 Demo 和使用说明

**Comment by wangkiyo** [comment]
看到了官方的适配了，但是一直都会有一个
![image](https://github.com/Kenshin/simpread/assets/45029102/3bab558a-19fd-416f-a371-c55aac931058)
是否可以看看适配方案，我来进行调整，使用起来问题不大，但是总归有点不够完美

**Comment by Kenshin** [comment]
哈哈，这也是老用户了，没想到你还能连上这个 Issues 😂

***

> 我自己自定义之后，一直有一个副标题（应该是description）一直存在... 理论上不应该会出现与页面内容无关的内容

我没太理解你的意思，你是想隐藏掉 description 吗？也就是下图所示

<img width="817" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/18450383-a125-4b65-a885-f1dc40fe0b55">

如果是的话，需要使用另外一个插件 https://github.com/Kenshin/simpread/discussions/2620

简悦默认会一直显示「描述段落」，一般获取自下图所示的内容

![SCR-20240417-qcsr](https://github.com/Kenshin/simpread/assets/81074/0dfbe56e-2527-4993-a212-f02ddca5e0ad)

**Comment by wangkiyo** [comment]
其实并不是这个意思，是我自定义规则后，不知道哪里来的description的内容，不管打开哪个新闻，提取出来的都是这个“性能、温度超常发挥！……”的描述，我取值的正则是这么写
[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]

**Comment by Kenshin** [comment]
> 不管打开哪个新闻

是 `news.mydrivers.com` 下面的网站均这样吗？还是任意网页？

我使用关键词 `性能、温度超常发挥` 检索了下网页源代码，没有发现这段内容 😂

PS：**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by wangkiyo** [comment]
只有驱家，而且我用官方的就没问题，自定义才会出现，找不到原因在哪里，难道是本地配置文件的问题？

**Comment by wangkiyo** [comment]
"websites": {
		"custom": [],
		"local": [
			[
				"https://news.mydrivers.com/*/*/*.htm",
				{
					"active": true,
					"desc": "[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]",
					"excerpt": "性能、温度超常发挥！技嘉钛雕AORUS Gen4 7000s 1TB SSD评测",
					"exclude": [],
					"include": "<div class='news_info'>",
					"name": "驱家新闻",
					"paging": [
						{
							"prev": "[[{$(\"a:contains('上一页')\").attr('href')}]]"
						},
						{
							"next": "[[{$(\"a:contains('下一页')\").attr('href')}]]"
						}
					],
					"title": "<title>"
				}
			],
			[
				"https://news.mydrivers.com/1/816/816906_2.htm",
				{
					"desc": "[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]",
					"excerpt": "性能、温度超常发挥！技嘉钛雕AORUS Gen4 7000s 1TB SSD评测",
					"exclude": [],
					"include": "<div class=\"news_info\">",
					"name": "news.mydrivers.com",
					"title": "<title>"
				}
			]
		],
		"person": []
	}

**Comment by wangkiyo** [comment]
删除后再重新导入可以了，终于可以开心地糟蹋这个站了

**Comment by Kenshin** [comment]
😂

`excerpt` 是未适配时自动获取的「描述」段落，我也不知道怎么会被写入到配置文件中，可能是极低概率的 Bug 导致，应该完全无法复现。 

<img width="652" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5490ca86-ab7c-4cba-b2b2-613bb593df99">

我关闭这个 Old Issues 有任何问题随时在这里讨论。

***

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
