### ISSUE TITLE
可否增加开关：「显示描述」

### ISSUE THREAD

**Issue by elephi** [Kenshin/simpread#3454]
期望：提供设置开关，允许用户在阅读模式下，不显示描述区域

<img width="1071" alt="iShot2022-02-23 15 09 57" src="https://user-images.githubusercontent.com/1418703/155347256-b8c48e68-1a23-4bc6-acc8-cdd076d1379e.png">

我没有找到类似功能设置，我尝试修改自定义样式，字体设置为0，但是仍然会显示灰色区域。

谢谢！

**Comment by Kenshin** [comment]
嗨，你可以直接使用 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v 这个插件来删除描述。

另外，插件系统提供了很多个性化的设置，你可以翻翻。https://github.com/Kenshin/simpread/discussions 也提供了各种生产力工具的联动等内容。
