### ISSUE TITLE
coolshell 网站阅读模式下，代码显示排版异常

### ISSUE THREAD

**Issue by jyq920203** [Kenshin/simpread#3456]
https://coolshell.cn/articles/17757.html
这篇文章中的代码显示的排版异常。

**Comment by jyq920203** [comment]
<img width="1080" alt="截屏2022-02-24 10 48 46" src="https://user-images.githubusercontent.com/9977948/155448230-9b9352d1-eec1-46a7-a57e-3302f34c67fd.png">

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

另外，试试把代码高亮插件禁用看看效果如何？
