### ISSUE TITLE
对于网站Stackoverflow, 只能提取到各楼层的信息, 但提取不到各楼层之内的其它用户的回复信息

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3461]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息
- 操作系统 Windows
- 浏览器版本 Edge 98.0.1108.56
- 简悦版本 2.2.0
- 发生问题的地址 https://stackoverflow.com/questions/50395044/can-packages-be-shared-across-anaconda-environments

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
- 原始页面:
![图片](https://user-images.githubusercontent.com/65625632/155838787-b9f1d5e7-40ec-413d-8869-11b8490e6e20.png)
- 阅读模式:
![图片](https://user-images.githubusercontent.com/65625632/155838854-e1a03312-eac7-4267-98ae-b15876b9c60a.png)

**Comment by Kenshin** [comment]
目前就是这么「设计」的，其实这个页面并不适合使用阅读模式。

但因为并不是每个「楼」的回复都有意义，所以采取了论坛类页面的处理方案。

**Comment by Kenshin** [comment]
> 能否考虑添加一个选项, 允许用户在指定网站上提取各楼层的回复, 因为这种情况使用手动框选添加各楼层之内的信息实在太麻烦了.

哈哈，之前漏掉了这个 issues ，我现在回复下。

这个还是有点太「麻烦」（不是技术上的，而是我不清楚如何更好的实现而已  😂 

可以作为一个插件来考虑，我先记录下。

**Comment by XMB-7** [comment]
其实针对这类论坛网站, 可以暂时先展示给用户一个提示, 告诉用户当前过滤掉了一些潜在有用的信息, 如有需要可以退出阅读模式进行查看.
否则的话, 对于这类网站, 自动进入阅读模式, 会导致用户根本不知道有些潜在的有用信息直接就被过滤掉了.
至于通过何种路径实现, 可以慢慢尝试.
或许允许用户手动往已生成的阅读模式里追加更多的文本框是一个思路.

**Comment by Kenshin** [comment]
> 其实针对这类论坛网站, 可以暂时先展示给用户一个提示, 告诉用户当前过滤掉了一些潜在有用的信息, 如有需要可以退出阅读模式进行查看. 否则的话, 对于这类网站, 自动进入阅读模式, 会导致用户根本不知道有些潜在的有用信息直接就被过滤掉了. 至于通过何种路径实现, 可以慢慢尝试. 或许允许用户手动往已生成的阅读模式里追加更多的文本框是一个思路.

哈哈，可以的。

其实我觉得这类似页面不应该使用阅读模式，从某种角度上说，也算具有互动性的页面。而这类页面都不应该使用阅读模式，或者说主动阅读模式。

**Comment by XMB-7** [comment]
我对清爽阅读没什么需求, 有更好, 没有也行. 所以我用阅读模式其实单纯就是为了做笔记. 
然而现在的问题是, 不进阅读模式就记不了笔记, 而进了阅读模式, 对于某些网站, 就可能漏掉看不到某些信息...
所以感觉确实需要斟酌一下怎样处理最合适.

**Comment by Kenshin** [comment]
@XMB-7 

这里面有个「误区」或者说使用上的区别，简悦希望有深度阅读的页面才进行保存、标注、备注等；反之的话，有很多第三方工具。

不是技术上的问题，而是使用理念上的思考。

**Comment by XMB-7** [comment]
呃, 我觉得可能使用理念确实不一样, 简悦对我而言就是一个收集碎片信息的地方, 经常一篇文章, 就那么三五句是有价值的, 就好比一个论坛帖子, 只有那么一个楼层的回复是有用的. 这个时候就必须要做标注. 你只收藏而不把这几句话给高亮了, 回头再看就又得重复一遍从垃圾里面找金子的过程, 纯属浪费时间.
如果要做深度阅读, 我确实会换其它工具.

**Comment by Kenshin** [comment]
> 所以对我而言, 用简悦几乎必做笔记, 而不值得记笔记的网页也压根进不了我的稍后读.

哈哈，确实是个好习惯，我基本上也这么做。

> 简悦对我而言就是一个收集碎片信息的地方, 经常一篇文章, 就那么三五句是有价值的, 就好比一个论坛帖子

有个解决方案针对页面少量需要标注的内容情景下，可以试试将任意高亮的内容生成阅读页面，当需要标注时，使用 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 提到的方案可以在稍后读直接进入高亮选中的页面。

![image](https://user-images.githubusercontent.com/81074/162150850-13973291-75c5-4105-bdd1-ea5e980b4447.png)
