### ISSUE TITLE
含有行数的代码块解析时出现问题

### ISSUE THREAD

**Issue by handbye** [Kenshin/simpread#3465]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

- 操作系统 ** Windows **

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

代码块出现以下问题
![image](https://user-images.githubusercontent.com/26617058/155920841-8bb983c8-e5ca-4bc0-874f-fbe70643e390.png)

原文：
https://mp.weixin.qq.com/s/8pZ0P5txrQAq_jwf8GU92A
![image](https://user-images.githubusercontent.com/26617058/155920913-7b4ea114-5243-42d8-a38b-32cf08bfae7a.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
