### ISSUE TITLE
填完之后没有提交按钮？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3467]
填完之后没有提交按钮？
![image](https://user-images.githubusercontent.com/11496107/155971751-de030aa2-5080-4e0d-b8f1-89bb51360d83.png)

_Originally posted by @chenyusheng in https://github.com/Kenshin/simpread/discussions/2906#discussioncomment-2264909_

**Comment by chenyusheng** [comment]
按钮 太隐晦了，完全没 get 这是个 button ，我还打开 F12 看页面代码😂

**Comment by Kenshin** [comment]
okay 收到，考虑改改~
