### ISSUE TITLE
已经是高级账户，但是不能绑定同步助手

### ISSUE THREAD

**Issue by yxkongfu** [Kenshin/simpread#3468]
授权按钮是灰色的。

![image](https://user-images.githubusercontent.com/91581312/156102730-3d8a6fbd-fa0e-49ab-9c77-b9c3d71c02b1.png)
![image](https://user-images.githubusercontent.com/91581312/156102756-a1484651-e12f-429c-b304-c69472006eb4.png)

**Comment by Kenshin** [comment]
嗨，简单的说，在首次绑定时提示需要重启浏览器，所以在个别情况下存在这个问题。

解决方案 https://github.com/Kenshin/simpread/discussions/2816
