### ISSUE TITLE
Firefox 60.0.2 (64 位) 无法启用 「ESC」 退出方式

### ISSUE THREAD

**Issue by HueLiu** [Kenshin/simpread#347]
浏览器版本60.0.2 (64 位) ，已经在全局中启用 「ESC」 退出方式，为防止其他的扩展不兼容和影响我把除了 简悦 以外的都关闭禁用。进入阅读模式后无法用「ESC」 进行退出，只能按左下角的图标退出。

**Comment by Kenshin** [comment]
并不是「不兼容」的问题，而是 Firefox 中无法使用快捷键，我在 README.md 中有提及。
不能使用的原因是，目前简悦的一些结构无法让 Firefox 监听到 keyboard 。

暂时还没有任何办法可以解决~

**Comment by HueLiu** [comment]
好的谢谢。只是好奇为什么「AA」和「AS」可以检测到，「ESC」就不行了。

谢谢你的回复~

**Comment by Kenshin** [comment]
也谢谢你的理解~
「AA」和「AS」是因为在 `<body>` 标签内，可以被检测到，但 `阅读模式` 在 `<html>` 标签内，在 Firefox 检测不到了。（它只能检测  `<body>` 的键盘事件）

**Comment by Kenshin** [comment]
嗨，各位，简悦 for Firefox 版正式发布了~

<img width="808" height="455" alt="Image" src="https://github.com/user-attachments/assets/58297ed1-551a-4fd1-b603-f42e7b4d9dbc" />

# 📚 支持浏览器

Zen browser · Firefox Nightly · Firefox Developer Edition · Firefox · Librewolf

# 🔗 如何使用 & 简悦 CRX 下载

[https://github.com/Kenshin/simpread/discussions/7279](https://github.com/Kenshin/simpread/discussions/7279)

注意：请不要使用 Chrome Webstore 下载的 crx，请使用专门为 Firefox 适配的 crx（上面链接有下载地址）

# ✅ 完美支持

- 阅读模式 / 聚焦模式

- 安装插件

- 更新站点

- 稍后读 / 标注

# ✳️ 需配合 [同步助手 1.5.0](https://n.simp.red/posts/648) 后支持

- 自动同步

# ❎ 不完美支持

快捷键暂时无法使用，但你可以使用 **全局快捷键解决无法进入阅读模式和加入稍后读的问题**，也可以使用 **Assistive Touch 解决简悦插件快捷键无法使用的问题**，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16470898)

# 在 Firefox 正式版使用简悦

如果你不希望更换上述浏览器，在 Firefox 也可以正常使用，但需要一些技巧，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16446625) 

# 最后

有任何问题统一在 [https://github.com/Kenshin/simpread/issues/7037](https://github.com/Kenshin/simpread/issues/7037) 讨论

我关闭这个 issues 了~
