### ISSUE TITLE
导出md的问题-请问可以自动在图片和文字之间增加空行吗?另外有时图片会被识别为标题的一部分

### ISSUE THREAD

**Issue by lin0kin** [Kenshin/simpread#3476]
- 操作系统 **Windows 10**

- 浏览器版本 **Edge 98.0.1108.62**

- 简悦版本 **2.2.0.520**

**请描述你的问题**

1. 请问可以自动在图片和文字之间增加空行吗?

![image](https://user-images.githubusercontent.com/30078096/156541329-fb2256fe-e25c-439e-b947-ce4abb12ad46.png)

2. 另外有时图片会被识别为标题的一部分

![image](https://user-images.githubusercontent.com/30078096/156541375-5d4f913e-5155-4faf-a916-fbc534510422.png)

**Comment by Kenshin** [comment]
给个 URL 看看。

另外，我顺道改了下你的第二个图片，原来的「太吓人」了...

**Comment by lin0kin** [comment]
> 给个 URL 看看。
> 
> 另外，我顺道改了下你的第二个图片，原来的「太吓人」了...

不好意思, 图片选的不太好

[抖音基于Flink的推荐系统演进历程](https://flink-learning.org.cn/article/detail/5a04e13152a445f67df767908069a521?tab=suoyou&page=1)

**Comment by lin0kin** [comment]
> > 不好意思, 图片选的不太好
> 
> 小事情而已。
> 
> > [抖音基于Flink的推荐系统演进历程](https://flink-learning.org.cn/article/detail/5a04e13152a445f67df767908069a521?tab=suoyou&page=1)
> 
> 这个 URL 与截图给出的不一样，我没法判断，我是说把截图对应的 URL 给我。

不好意思, 没有原链接, 换了这个链接的截图

**Comment by Kenshin** [comment]
那就没办法了...

另外，我根据你给出的 URL 导出了 Markdown，是没问题的，看下面的截图

![image](https://user-images.githubusercontent.com/81074/156541924-ffbd0068-f021-4206-bf1b-34c6d69f0cfc.png)

同时，我把这个这个文章也导出了 md 给你看下。

[抖音基于Flink的推荐系统演进历程.txt](https://github.com/Kenshin/simpread/files/8176795/Flink.txt)

**Comment by lin0kin** [comment]
> 那就没办法了...
> 
> 另外，我根据你给出的 URL 导出了 Markdown，是没问题的，看下面的截图
> 
> ![image](https://user-images.githubusercontent.com/81074/156541924-ffbd0068-f021-4206-bf1b-34c6d69f0cfc.png)
> 
> 同时，我把这个这个文章也导出了 md 给你看下。
> 
> [抖音基于Flink的推荐系统演进历程.txt](https://github.com/Kenshin/simpread/files/8176795/Flink.txt)

不好意思, 能测试一下 复制markdown 到剪切板 吗? 我用这个功能时出现的这个两个问题

**Comment by Kenshin** [comment]
> 不好意思, 能测试一下 复制markdown 到剪切板 吗? 我用这个功能时出现的这个两个问题

只要是导出 Markdown 背后的代码都是一样的，只是表现形式不一样而已，另外已经测试是没问题的。

**Comment by lin0kin** [comment]
> > 不好意思, 能测试一下 复制markdown 到剪切板 吗? 我用这个功能时出现的这个两个问题
> 
> 只要是导出 Markdown 背后的代码都是一样的，只是表现形式不一样而已，另外已经测试是没问题的。

好吧, 是 live edit 这个插件的问题

**Comment by Kenshin** [comment]
> 好吧, 是 live edit 这个插件的问题

emmm 原来如此，Live Editor 在修改的时候，确实有可能会把图片和文字变成一行。

**Comment by lin0kin** [comment]
> > 好吧, 是 live edit 这个插件的问题
> 
> emmm 原来如此，Live Editor 在修改的时候，确实有可能会把图片和文字变成一行。

麻烦大佬修复一下

**Comment by Kenshin** [comment]
> 麻烦大佬修复一下

okay
