### ISSUE TITLE
无法通过api保存本地快照

### ISSUE THREAD

**Issue by haozhuren** [Kenshin/simpread#3478]
你好，我正在使用简悦2.2高级账户，但是遇到了如下问题。我按照帮助中的这篇文章(https://github.com/Kenshin/simpread/discussions/3024) 进行了设置,目前实现了当文章保存到pocket时自动保存到简悦稍后读，但是并没有在本地产生快照。我以为是自动化设置的问题，但是经过检查发现，我已经在自动化流程中配置了保存到稍后读后自动保存快照的功能。
此外这里还有两个信息或许可以帮助解决这个问题
1.我发现在阅读模式下，通过快捷键DD把文章加入稍后读，本地是可以产生快照的（这或许也能说明我的自动化配置没有问题）。
2.API配置页面的测试是通过的（返回了201，并且坚果云也产生了快照）

**Comment by Kenshin** [comment]
嗨，你可以这样自查下：

1. 坚果云 Web 端的 `output` 文件夹里面更新了 Pocket 的快照了吗？

2. URL 需要确保在国内正常访问

3. 在使用 Zapier 的时候，有一个步骤是测试（下图），如果测试通过**步骤一** 里面会有快照（如果你开了坚果云客户端就能得到这个快照）

![image](https://user-images.githubusercontent.com/81074/156686329-13c4e839-cbf0-4949-8af7-d6a432307640.png)


另外，如果是因为步骤一的问题，可以看看 [自动同步](https://kb.simpread.pro/#/page/61f3d233-2dd8-40db-8daa-55f9dfdf6a7e)

**Comment by haozhuren** [comment]
> 嗨，你可以这样自查下：
> 
> 1. 坚果云 Web 端的 `output` 文件夹里面更新了 Pocket 的快照了吗？
> 2. URL 需要确保在国内正常访问
> 3. 在使用 Zapier 的时候，有一个步骤是测试（下图），如果测试通过**步骤一** 里面会有快照（如果你开了坚果云客户端就能得到这个快照）
> 
> ![image](https://user-images.githubusercontent.com/81074/156686329-13c4e839-cbf0-4949-8af7-d6a432307640.png)
> 
> 另外，如果是因为步骤一的问题，可以看看 [自动同步](https://kb.simpread.pro/#/page/61f3d233-2dd8-40db-8daa-55f9dfdf6a7e)

你好，我根据这篇文章（https://github.com/Kenshin/simpread/discussions/3020） 的方法进行了测试，是没有问题的，output文件夹内也有快照生成，因此我认为我的自动同步的配置应该是正确的。 此外，我根据你提供的第三条方案在zapier里测试的时候，zapier上返回的值是201，坚果云也提示我simpread-config.json有更新，但是除此之外，并没有快照在output生成。我测试时保存的文章是知乎上的文章，在国内是可以正常访问的

**Comment by Kenshin** [comment]
> zapier上返回的值是201，坚果云也提示我simpread-config.json有更新

说明你的配置没问题，是不是下图的问题导致的？

![image](https://user-images.githubusercontent.com/81074/156699854-f99fcaa0-9375-4e39-8e63-d07b1aa9d968.png)

**Comment by haozhuren** [comment]
> > zapier上返回的值是201，坚果云也提示我simpread-config.json有更新
> 
> 说明你的配置没问题，是不是下图的问题导致的？
> 
> ![image](https://user-images.githubusercontent.com/81074/156699854-f99fcaa0-9375-4e39-8e63-d07b1aa9d968.png)

我使用的是1.0.0应该不存在这个问题，这是我的设置
<img width="967" alt="image" src="https://user-images.githubusercontent.com/47451948/156721056-1127057e-2220-4d72-8bcf-e5bc715bbfa6.png">

**Comment by Kenshin** [comment]
选择了 1.0.0 自然没有快照了，否则要 1.0.1 版本干什么？ 😂 

当然，非要说的话，也确实有歧义...可能教程的描述需要明确指出

![image](https://user-images.githubusercontent.com/81074/156722511-44c9d441-c709-4618-8bd3-64ec5796193e.png)

**Comment by haozhuren** [comment]
谢谢，问题解决了

**Comment by Kenshin** [comment]
搞定就好

也算是有收获 https://github.com/Kenshin/simpread/discussions/3024 捉了一个 🐛 

我关闭这个 Issues 了。

***

PS：哈哈，当客服太不容易了，这个 issues 也算是回复比较多的之一了，请在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价~

PPS：你的动手能力还是不错的，如果教程严禁些，完全没必要提 Issues 的，如果有更多关于简悦的用户，欢迎回复我。

***

简悦适配了 Pocket 页面，这个功能还未对外发布，你可以试试 https://simpread.ksria.cn/sites/details/XTWT9dd73G

安装完毕后，需要将 `getpocket.com` 加入到延迟加载列表

![image](https://user-images.githubusercontent.com/81074/156725604-9772b125-32fd-4eb3-97e6-fc647b149dab.png)
