### ISSUE TITLE
[FR] add current domain into whitelist

### ISSUE THREAD

**Issue by Cologler** [Kenshin/simpread#348]
在上下文菜单添加「把当前域名/站点添加到白名单/排除列表」菜单项。

![snipaste_2018-06-15_21-26-50](https://user-images.githubusercontent.com/10906962/41470307-d24750da-70e2-11e8-9a77-fb21f3658bed.png)

**Comment by Kenshin** [comment]
谢谢建议。
我也有考虑过这个方式，只是有些用户不想菜单栏被「污染」所以，暂时并没有提供此功能。

其实可以类似 聚焦模式 菜单项的方式，可以关闭。（但我也不太想让用户做太多的选择...

**Comment by Cologler** [comment]
因为每次要进入设置，然后找到白名单/排除列表，再加上填写 url 模式，加起来的时间大概要 20 秒以上。

**Comment by Kenshin** [comment]
确实有些麻烦，如果要设置名单的话...

**Comment by woyaojizhu8** [comment]
这个功能可以有啊。本来就有菜单，只是增加一个菜单项，算不上污染吧。

**Comment by Kenshin** [comment]
竟然漏掉这个 issues 了…

简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，其它更新包括：

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

我要关闭这个 issues

**Comment by woyaojizhu8** [comment]
新版的“将当前页面加入白名单”功能，是真的只是将当前页面地址加入白名单啊，同一网站的其他页面是不会生效的啊。这个issue，还算不上解决吧，只能说开始做了。
另外，这个功能要完善，还得有更多选项吧，比如像各种广告屏蔽扩展选取元素屏蔽的时候那种URL通配符选择模式。
例如在 https://post.smzdm.com/p/a4w0pdxk/ 选择“将当前页面加入白名单”，提示“https://post.smzdm.com/p/a4w0pdxk/”，“https://post.smzdm.com/p/*”，“https://post.smzdm.com/*” 三个选项，选择后还可以更详细修改。

**Comment by Kenshin** [comment]
@woyaojizhu8 

谢谢建议。不过，你的建议有些化简为繁了。
你说的这些可以在选项页里面做这些操作。（甚至可以做更多，只是多操作几次

你说的方式会增加相当复杂的前端交互，我指的不是编码上的难度。

***

简悦只提供两种级别的处理：

– 针对初级用户的无任何配置的使用

– 针对高级玩家的自定制功能

***

换句话说，不是每个用户都有你这样的诉求。

解决你的诉求的方案：通过插件的个性定制化定制。

这些功能（插件）只针对个别用户的诉求。

***

我会通过插件的方式实现，然后会通知你。😄

**Comment by woyaojizhu8** [comment]
@Kenshin 
目前的“将当前页面加入白名单”功能，恐怕没有什么意义，因为只针对单个页面的话，一般没有人有对某一个URL自动开启阅读模式的需求，一般都是针对站点比较常见。我是看到你做了这样一个功能，以为是更完善的功能的一个开始，所以说了点想法。
一个网站，他也有可能不是全部都是适合阅读模式的文章，它有可能 example.com/a/* 是新闻文章，适合阅读模式，而example/bbs/*是论坛，不适合阅读模式，所以我才提出了那个通配符匹配的需求。当然你也可以认为这是高级玩家的自定制功能，适合用插件实现。就拿我通配符匹配思路的来源 广告屏蔽扩展来说，像adblock plus就是把选取元素隐藏功能做成了另外的扩展，而ublock origin则是把功能集成到了它本体，这不妨碍有很多初级用户使用它们，装上后不配置直接用。
可能我表达能力差让你觉得复杂了，其实思路理清就不复杂，这种功能增加并不会对初级用户造成妨碍，初级用户仍然可以无任何配置使用。

**Comment by Kenshin** [comment]
你的表述并没有问题。

***

>
