### ISSUE TITLE
反映一个错别字(如图所示)

### ISSUE THREAD

**Issue by Kukmoon** [Kenshin/simpread#3481]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Opera 84.0.4316.21 （基于 Chromium 98.0.4758.10）**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

在界面上发现一个错别字，应该是“请**勿**更改这里”，作者写成了“请**误**更改这里”。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

![图片](https://user-images.githubusercontent.com/16938012/156759616-b64c4c93-c2fb-442d-820c-529e84f7321f.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈，错别字都会集中到这里 https://github.com/Kenshin/simpread/discussions/2268#discussioncomment-2298741 ，我直接关闭这个 Issues 了~
