### ISSUE TITLE
开通开放平台后出现登录失败，需要在哪里重新设置？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3484]
开通开放平台后出现登录失败，需要在哪里重新设置？
![image](https://user-images.githubusercontent.com/86549958/156778518-6d8200b6-b729-4d27-880a-4eedc7755ee5.png)

首次登录的时候是选择UID和License方式登录的，但是之后每次进入https://simpread.pro/developer 这个链接就变成了上图的情况，我也不清除在哪里能切换登录方式。
今天在配置的时候还碰到了一个问题，LiveEditor插件保存设置之后刷新界面使用的还是保存之前的设置。期待您的指导，谢谢！
![LiveEditor](https://user-images.githubusercontent.com/86549958/156865196-9182d838-fdf1-44bc-97fe-abe715e1f220.gif)

_Originally posted by @mdzz2048_

**Comment by Kenshin** [comment]
@mdzz2048

嗨，我把你的问题重开了个 issues 

***

> 首次登录的时候是选择UID和License方式登录的，但是之后每次进入https://simpread.pro/developer 这个链接就变成了上图的情况，我也不清除在哪里能切换登录方式。

之后每次进入时使用的是什么方式？

> 在配置的时候还碰到了一个问题，LiveEditor插件保存设置之后刷新界面使用的还是保存之前的设置

可能是配置互相覆盖了，你改完 Live Editor 保存后，重启浏览器，或者确保在改动配置时只有一个 Tab （建议重启，最简单）

**Comment by mdzz2048** [comment]
之后每次进入没有出现这个有登录选项的界面，直接进入那个有token的界面。尝试了重新安装简悦和重启浏览器还是这样。
![image](https://user-images.githubusercontent.com/86549958/156866173-517b8424-5a6f-467a-80f4-e3089557d665.png)
这个是操作录像
![开放平台](https://user-images.githubusercontent.com/86549958/156866429-0c04a4db-e5e6-4817-b2b9-8ce2c072b9df.gif)

**Comment by Kenshin** [comment]
emmm

登录开放平台前需要 [先开通](https://kb.simpread.pro/#/page/%E5%BC%80%E9%80%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0) 看看你与教程的开通过程有没有什么区别？

确保开通前提和步骤都没问题的话，在**隐身模式下** 登录 https://simpread.pro/developer 然后使用 UID / License 的方式登录。

如果还有问题的话，把你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3484

**Comment by mdzz2048** [comment]
隐身模式下登录解决了，谢谢！
错误原因是昨天设置的时候没有设置ID，只设置了short

**Comment by mdzz2048** [comment]
隐私模式下登录重新设置解决问题了，非常感谢！

**Comment by Kenshin** [comment]
okay 搞定就好，我关闭这个 issues 了。
