### ISSUE TITLE
文章加入稍后阅读后，通过阅读模式打开，显示   它可能已被移动、编辑或删除。

### ISSUE THREAD

**Issue by qiyueliuhuo** [Kenshin/simpread#3486]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** MacOS**

- 浏览器版本 **Microsoft Edge
版本 98.0.1108.62**

- 简悦版本 **版本 2.2.0.520**

- 发生问题的地址 (https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-021-01691-8)

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
显示   它可能已被移动、编辑或删除。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/15904121/156958647-98c53105-5817-4d0f-82ba-98ca85c0db54.png">

**Comment by Kenshin** [comment]
嗨，有下面两个解决方案：

1. 开启稍后读的 [内置解析](http://ksria.com/simpread/docs/#/Sync?id=%e5%86%85%e7%bd%ae%e8%a7%a3%e6%9e%90)（需要使用同步助手）
2. 配置 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)，一劳永逸。
