### ISSUE TITLE
b站专栏解析不出来

### ISSUE THREAD

**Issue by ganansuan647** [Kenshin/simpread#3489]
阅读了，但是看不懂该怎么用
https://www.bilibili.com/read/cv15545953?spm_id_from=333.1007.0.0
阅读模式可以用，稍后读里不行，这个白名单在哪里？

**Comment by Kenshin** [comment]
嗨，有下面两个解决方案：

1. 开启稍后读的 [内置解析](http://ksria.com/simpread/docs/#/Sync?id=%e5%86%85%e7%bd%ae%e8%a7%a3%e6%9e%90)（需要使用同步助手）
2. 配置 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)，一劳永逸。
