### ISSUE TITLE
希望可以设置“动作”的显示与否。

### ISSUE THREAD

**Issue by chrvip** [Kenshin/simpread#3492]
现在“简悦”，默认打开的各种“动作”太多，其中大多是用不到的，希望能有一个地方设置为某个动作“显示/不显示”，这样可以保持界面的简洁，方便使用。
![image](https://user-images.githubusercontent.com/536916/156982076-36edc496-499d-4f12-ad5d-f9f7caa16d46.png)

**Comment by Kenshin** [comment]
嗨，当然可以了，你打开的页面 → 插件栏就有关于此的介绍

![image](https://user-images.githubusercontent.com/81074/156984410-3196ba9a-5731-4234-b6d4-c8463c538bb3.png)
