### ISSUE TITLE
如何改变PDF导出样式

### ISSUE THREAD

**Issue by fmxh** [Kenshin/simpread#3497]
PDF导出样式怎么调整，以下是我的需求
![image](https://user-images.githubusercontent.com/101099038/157007441-26ccbef3-4e2c-43df-b002-3ffe972e94ff.png)
不想要这里的边框线。
![image](https://user-images.githubusercontent.com/101099038/157007727-321519db-a50f-4fe3-958b-c0c4c7969f7d.png)
同时也想要这里的编辑时间

这是网址：https://www.zhihu.com/question/326133011/answer/1954385569

**Comment by Kenshin** [comment]
嗨，暂时不支持 PDF 的定制化，后续的版本会考虑加入的。

**Comment by Kenshin** [comment]
> 那目前有办法去掉那个边框线吗？

在主题上很容易去掉，使用 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 就行，但如果使用简悦自带的 PDF 导出功能，可能会失效，所以只能使用浏览器方案。

你可以使用这个插件 [PDF辅助增强](https://simpread.ksria.cn/plugins/details/Lly3mkuSPz) 来协助你。

***

另外，你要的是下图的效果吗？

![image](https://user-images.githubusercontent.com/81074/157157053-6935e2f6-8d30-4d1e-9089-217675495889.png)

至于下图的编辑也可以使用 [Live Editor](https://simpread.ksria.cn/plugins/details/y8Mai5IBwN) 搞定

![image](https://user-images.githubusercontent.com/81074/157156934-92fecae0-672b-49fb-ab0d-39900b7f845e.png)

**Comment by Kenshin** [comment]
另外，如果只是这一个页面的话，我可以帮你转换下。

**Comment by fmxh** [comment]
非常感谢你的回答，我想要的不仅仅是这个界面。
简悦的PDF导出的布局相交于原生的要更好看些，同时文字被上下切割的情况少了很多。
希望后面可以自定义页面呈现的内容(比如上面的编辑时间)，然后再使用简悦的 PDF 导出功能。

**Comment by Kenshin** [comment]
> 比如上面的编辑时间

嗨，使用 [Live Editor](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22live+editor%22) 就可以对页面进行编辑。

另外，对 PDF 的自定义功能会考虑的。

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
