### ISSUE TITLE
稍后读 未读条目 显示问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3499]
<div type='discussions-op-text'>

<sup>Originally posted by **Umfs** March  8, 2022</sup>
大家好，我尝试了EDGE 和 CHROME，都遇到了如下问题。

在稍后读的阅读栏上方，共有X个未读条目永久显示，占据了1/3的可读空间。请看截图。
![Screenshot 2022-03-07 134803](https://user-images.githubusercontent.com/4309255/157098890-888d4c8f-6bca-4584-9f2d-d0d6c26c38fc.jpg)
</div>

**Comment by Kenshin** [comment]
@Umfs

嗨，我帮你从 Discussions 的位置转移到了 Issues ，因为发错位置了。

***

在回复下你的问题，这个现象是因为稍后读的某些数据错误导致的，解决方案：

1. https://github.com/Kenshin/simpread/discussions/3165
2. https://github.com/Kenshin/simpread/discussions/2727

方案一更简单；方案二精细但需要自己动手

**Comment by Umfs** [comment]
谢谢你的快速回复。我今晚就试试看。

**Comment by Kenshin** [comment]
哈哈，客气了，我也已经在推上回复你了。

有问题随时在这里沟通~

**Comment by Umfs** [comment]
看到了，谢谢你。请问有计划推出安卓版原生应用吗？

**Comment by Kenshin** [comment]
当然会有自己的客户端~
