### ISSUE TITLE
是否考虑增加发送到KINDLE的功能

### ISSUE THREAD

**Issue by april25th** [Kenshin/simpread#35]
是否考虑增加发送到KINDLE的功能？

**Comment by Kenshin** [comment]
如果要实现的话，应该需要个服务器做中转，近期版本暂时不会考虑。
但是之后的版本肯定会加强 `生产力` 方面的功能。

目前毕竟是免费的项目，如果成本不高的话，当然会考虑此功能。

**Comment by xiuluo** [comment]
@Kenshin 可以考虑基于GAE，KindleEar就是基于GAE的

**Comment by Kenshin** [comment]
@xiuluo  KindleEar 是个好东西，有时间弄明白它！

**Comment by Kenshin** [comment]
@april25th 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

没有使用 @xiuluo 的方案，暂时使用了一个则中的方式，详细说明请看 [发送到 Kindle](https://github.com/Kenshin/simpread/wiki/%E5%8F%91%E9%80%81%E5%88%B0-Kindle)，此 issues 将关闭~
