### ISSUE TITLE
作者哥哥，简悦会屏蔽一起扩展，比如翻译扩展，这个有没有办法加白名单？

### ISSUE THREAD

**Issue by oknixus** [Kenshin/simpread#350]
如题，求解答！
简悦真是太好用了，感谢作者哥哥！！！🌺🌺🌺

**Comment by Kenshin** [comment]
请问用的是什么翻译扩展？

**Comment by oknixus** [comment]
我用的是，划词翻译：
https://github.com/Selection-Translator/crx-selection-translate

**Comment by Kenshin** [comment]
我知道了，我会在下个版本想办法解决这个问题~ 谢谢反馈！

**Comment by Kenshin** [comment]
先不要关闭此 issues 这样新功能上线后我会在这里通知你~

**Comment by oknixus** [comment]
已经关了，哥🙂

**Comment by oknixus** [comment]
😆不好意思，看成您要我先关闭这个issue了，抱歉

**Comment by zYeoman** [comment]
@Kenshin 不如简悦自带个翻译功能？

类似[这个](https://github.com/ninja33/ODH)

**Comment by Kenshin** [comment]
@zYeoman 
我会想办法支持翻译，或者联系插件的作者。  😀

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [划词翻译](https://simpread.ksria.cn/plugins/details/ohnTKVHz4a) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
