### ISSUE TITLE
新站适配：新版 MDN

### ISSUE THREAD

**Issue by Lanttcat** [Kenshin/simpread#3501]
e.g. https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot

**Comment by Kenshin** [comment]
嗨，谢谢反馈，适配后会通知你~

**Comment by Kenshin** [comment]
嗨，这个站已经更新，具体规则 [请看这里](https://github.com/Kenshin/simpread/discussions/5418#discussioncomment-5495675)
