### ISSUE TITLE
功能请求: 删除当前稍后读(包括标注)时, 双击垃圾箱图标直接同意.

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3503]
目前要想删除阅读模式里的所有标注, 需要点击屏幕右侧的删除图标, 然后把鼠标移动到屏幕下方的位置点击同意, 稍微麻烦了一点.
建议可以和删除某条标注一样, 双击删除图标即可完成删除操作.
如果实在担心用户因此引发误操作, 那么建议至少把出现在下方的同意选项挪到出现在右侧删除图标的上方.

**Comment by Kenshin** [comment]
> 目前要想删除阅读模式里的所有标注, 需要点击屏幕右侧的删除图标, 然后把鼠标移动到屏幕下方的位置点击同意

okay 感觉「双击」删除思路不错，谢谢建议~

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~


解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
