### ISSUE TITLE
学术类网站/页面比较痛苦

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#351]
举个例子： https://zhuanlan.zhihu.com/p/31426458

在 阅读模式 后
1. 所有行内公式（因为被转换成了图片）单独成段落居中显示
1. 大图没有设置max-width 100%，导致超出页面边界 （显示器竖起来、页面宽度窄一点看效果更明显）

建议：
1. 想办法区分“一图片一段”还是“行内图片”，分别进行处理
1. 加入“两边对齐”的选项（论文排版看习惯了……囧）
2. 大图设置max width 100%。如果是一段一图，不受text-indent控制。
3. 针对大图，加入LightBox灯箱

图有点极端，这个设置的话上面的问题会很明显。

![2018-06-24 15-37-11](https://user-images.githubusercontent.com/7346324/41816984-be5a5b06-77c4-11e8-8b2e-224397536258.png)

**Comment by Kenshin** [comment]
谢谢反馈~

正如你说，是由于 `行内居中` 造成的，目前没有太好的解决办法。在 1.1.2 我会尽量解决。

---
截图中出现的问题不应该存在，所以的图片我都设置了。下图是我截图：
![image](https://user-images.githubusercontent.com/81074/41826835-eb7508da-785e-11e8-9eea-477345ce6d3b.png)
请问能否稳定复现？
PS：看起来是因为你的布局设置的太窄了... 你可以加宽布局。

---
`两边对齐`
是指什么？

---
下个版本会提供 `LightBox` 的功能。

**Comment by jinyu121** [comment]
稳定复现步骤：

1. 你需要两块显示器，一块横着，一块竖着
1. 再横显示器上打开页面，进入一阅读模式
1. 将窗口拖放到另一块显示器上
1. 八阿哥就跳出来了

---

`两边对齐`指的是……给你个例子吧：

![2018-06-25 14-30-52](https://user-images.githubusercontent.com/7346324/41833812-71ac6856-7884-11e8-9a47-6c64d0f331aa.png)

再看一下单独左对齐的：

![2018-06-25 14-33-46](https://user-images.githubusercontent.com/7346324/41833911-d373fd7e-7884-11e8-9e2d-6c45f854524c.png)

不过这个可能比较难做，或者使用latex js 脚本实现。（代价好大啊）

**Comment by Kenshin** [comment]
你说的问题应该是 image 没有 resize 造成的，除非监听 resize 事件，否则很难解决。

---
两端对齐是下图的效果吧？
![image](https://user-images.githubusercontent.com/81074/41838540-474badc4-7893-11e8-8a0e-db5db5ba487a.png)

如果是的话，用 `自定义样式` 可以解决。

但这样有个问题，单词被折断了。你给出的页面最好给我个 链接，我来试试~

**Comment by jinyu121** [comment]
可以看一下这个效果 https://codepen.io/HugoGiraudel/pen/3983209536be8ee1fde113ab7a00473e

截图是LaTeX生成的PDF里面截出来的……论文排版好像默认会line-break后在单词中间加`-`。HTML的话，上面那个CSS好像效果已经很不错了。

**Comment by Kenshin** [comment]
@jinyu121 
看起来你应该会 CSS，这样的话，更简单了，有两种办法：

- 全局自定义样式，位置 选项页 → 高级设定 → 自定义样式 → 左侧下方（自定义CSS）

- 当前适配的页面，位置 进入阅读模式 → 右侧控制栏 → 站点编辑器（动作面板）→ 设定（下面第一个 icon，站点编辑器） → 弹出 Dialog → 下方（自定义 CSS）

填入你认为需要的 css 代码，刷新当前需要生效的页面即可。

**Comment by jinyu121** [comment]
前

![2018-06-26 10-44-46](https://user-images.githubusercontent.com/7346324/41886219-12063076-792e-11e8-9d9e-44350e7826d9.png)


后

![2018-06-26 10-41-26](https://user-images.githubusercontent.com/7346324/41886233-19e5cf72-792e-11e8-97c5-12da88e1adaf.png)


CSS

```
sr-rd-content{
  text-align: justify;
}
sr-rd-content p {
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  -ms-hyphens: auto;
  hyphens: auto;
}
```

希望能合并到你的代码里（或者加自定义开关）

----

图片问题你要自己处理啊～期待下一个版本～

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***


截图即是当前的效果

![image](https://user-images.githubusercontent.com/81074/57218673-7bd3ed80-7028-11e9-833b-fb52ab8434dd.png)

**Comment by Kenshin** [comment]
> 稳定复现步骤：
> 
> 1. 你需要两块显示器，一块横着，一块竖着
> 2. 在横显示器上打开页面，进入阅读模式
> 3. 将窗口拖放到另一块显示器上
> 4. 八阿哥就跳出来了
> 
> 解决办法可能是检测到窗口变化后再render一次？
> 
> `两边对齐`指的是……给你个例子吧：
> 
> ![2018-06-25 14-30-52](https://user-images.githubusercontent.com/7346324/41833812-71ac6856-7884-11e8-9a47-6c64d0f331aa.png)
> 
> 看起来很整齐是不是？
> 
> 再看一下单独左对齐的：
> 
> ![2018-06-25 14-33-46](https://user-images.githubusercontent.com/7346324/41833911-d373fd7e-7884-11e8-9e2d-6c45f854524c.png)
> 
> 不过这个可能比较难做，或者使用latex js 脚本实现。（代价好大啊）另外记得好像某个CSS属性加上去也可以做到的。忘掉了忘掉了。

嗨，两端对齐的功能，我用插件实现了，地址 https://simpread.ksria.cn/plugins/details/VCAENkqLbO
