### ISSUE TITLE
模式切换不见了

### ISSUE THREAD

**Issue by Aevit** [Kenshin/simpread#3510]
之前点了一次切换为简单模式，现在想切回原本的模式去绑定简悦同步助手，找不到入口了

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/1490969/157656759-2f29890c-a90a-41a1-9f4a-9d78f9b1e34f.png">

**Comment by Kenshin** [comment]
哈哈，你截图的左下角就有选项，细节可以 [看这里](http://ksria.com/simpread/docs/#/%E7%AE%80%E6%98%93%E6%A8%A1%E5%BC%8F)
