### ISSUE TITLE
新站适配：机核GCORES

### ISSUE THREAD

**Issue by Alkaidcc** [Kenshin/simpread#3522]
问题：图片无法解析
链接：https://www.gcores.com/articles/121924
原站：
![image](https://user-images.githubusercontent.com/54631354/157996034-18958258-3007-4f6d-84c9-f18681534234.png)
阅读模式：
![image](https://user-images.githubusercontent.com/54631354/157996092-d0ec6dec-93a1-4c09-aae1-2e3b07801b45.png)

**Comment by Kenshin** [comment]
okay 收到。

会单独适配这个网站，适配后会在这里通知你~

另外，也可订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会在这里和官方渠道通知适配的新站。

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/68hAvoc6pC 安装。

同时因为这个站是动态加载的，所以需要将 `cores.com` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

PS：如果在使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装此站点。
