### ISSUE TITLE
新站适配：coke.do

### ISSUE THREAD

**Issue by invisprints** [Kenshin/simpread#3524]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **Edge 99.0.1150.39 (正式版本) Beta(x86_64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <http://coke.do/issues/85-1070393?utm_campaign=Issue
<img width="1135" alt="截屏2022-03-12 下午11 05 50" src="https://user-images.githubusercontent.com/15833553/158023436-26654abd-a5bc-43d9-88ea-8fc5966b90e2.png">
内容抓取不全

感觉简悦目前对newsletter类的适配还不是很好，包括简悦自己的[newsletter](http://newsletter.simpread.pro/issues/vol-009-667752)也是抓取不全

**Comment by Kenshin** [comment]
嗨，确实是这样的，因为 Revue 的结构比较特别，所以需要单独适配它，这个站放在 Todo 里面好久了，适配后我会在这里通知你。

另外，也订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会也会在官方渠道通知。

**Comment by Kenshin** [comment]
嗨，这个站已适配，如何使用请看 https://github.com/Kenshin/simpread/discussions/3533 的描述。
