### ISSUE TITLE
无法将网页文章保存到notion

### ISSUE THREAD

**Issue by MrZhuChina123** [Kenshin/simpread#3526]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)。

**Comment by Kenshin** [comment]
嗨~

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Notion 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![Notion Configs](https://user-images.githubusercontent.com/81074/196083084-22384ded-73a8-42c4-9b1b-13262ed155ab.png)

> 针对新用户的一步到位的 Notion 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Notion 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Notion

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Notion

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Notion

4️⃣ 导入到 Notion 的内容包含：题图、Favicon、标签、原文地址等丰富的元数据信息

5️⃣ 内置 Notion 测试账户

## 📖 区别

![img](https://imgs.zhubai.love/bd83e21f5c0e43bea0517c88c025211c.png)

## 📘 极速版

🔗 [Github ](https://github.com/Kenshin/simpread-configs/blob/main/notion@base/Getting%20Started.md)| [语雀](https://www.yuque.com/kenshin/simpread/ewaflu)

不需要同步助手，无任何配置，导入全文到 Notion，并支持 Database Page，适合 Notion + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/notion@enhance/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/odhlf2)

不需要同步助手，无任何配置，导入全文到 Notion（包含：题图、Favicon、标签、原文链接等丰富的元数据信息），自动同步标注，适合 Notion + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/notion@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/zuptv2)

需要同步助手，几乎无任何配置，包括基础版全部功能，并具有本地快照功能。

# 📺  引申：导入到 Notion - 简悦官方有声视频教学

![img](https://imgs.zhubai.love/6ed78f485f2c4c21add9244987e39986.png)

高级版的功能也可以看看简悦推出的视频教程，细节 [请看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-3356081) ⤴️。
