### ISSUE TITLE
简悦 · 同步助手在 Windows下无法随系统自动启动

### ISSUE THREAD

**Issue by excelsior222** [Kenshin/simpread#3527]
- 操作系统 **Windows 10 家庭中文版 20H2**

- 浏览器版本 **Chrome 99.0.4844.51（正式版本64 位）**

- 简悦版本 **2.2.0.520**

**请描述你的问题**

> 同步助手1.01已经开启【随系统启动而启动】，但每次仍需要手动启动

**Comment by Kenshin** [comment]
嗨，这是添加自动启动的方案 https://github.com/Kenshin/simpread/discussions/1818
