### ISSUE TITLE
MathJax丢公式

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#353]
页面： http://akosiorek.github.io/ml/2017/10/14/visual-attention.html
阅读模式之后，所有公式都丢了。

页面： https://haoyu.love/blog518.html
阅读模式后，公式没有解析

可能的解决办法： 
1. 获取MathJax加载完毕后的页面HTML，而不是服务器上直接获取下来的HTML。
1. 引入MathJax，在进入阅读模式后拿MathJax 解析一下

----

测试： 

When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

-- 例子来源于 https://www.mathjax.org/#demo ，但好像Github的Markdown不对公式进行渲染？

**Comment by Kenshin** [comment]
应该是 MathJax 造成的，但不可能仅仅为了这个情况，简悦 import MathJax ~

不过，1.1.2 有更好的办法解决这些问题。（ 但不清楚能否解决你这个问题，毕竟有些麻烦...）

**Comment by Fankbai** [comment]
例如：
$$ H(X)=-\sum_{i=1}^n p(x_i)log(p(x_i))$$
是无法展示的。

**Comment by jinyu121** [comment]
回复： 
第一个链接里面的公式都OK的
第二个链接里面的公式都不显示

**Comment by Kenshin** [comment]
嗨，今天研究了下 MathJax 的问题，目前暂时无法用 插件的方式解决，但可以通过以下的方案完美解决：

- 进入阅读模式；
- 右侧控制栏 → 动作 → 设定 → 重新选择高亮

即可解决。

造成的原因是：MathJax 在生成公式时会有个 Delay 而在生成阅读模式时，还未生成公式。

**Comment by jinyu121** [comment]
也就是说，可以先让公式渲染出来，然后再进入阅读模式？
如果是这样的话……先记录当前阅读百分比，然后快速跳转到end（这中间应该会触发MathJax的加载吧）。然后跳回来，最后进入阅读模式。——不知道可行不？

**Comment by Kenshin** [comment]
只要是 open issues 我都会关注的，尤其是打了标记的。

其实目前无法渲染的是一个 `Bug` 造成的。

为了加快进入阅读模式，所以简悦会在页面 loading 完毕后，分析一些 dom ，而这时 MathJax 还未被渲染出来，这就造成了无法使用的问题。

所以临时解决办法如我所说~

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

例如 https://github.com/Kenshin/simpread/issues/412 即是解析 LaTeX 后的效果。
