### ISSUE TITLE
无法导入备份配置，不知道为什么突然就坏了。就保存了下配置。

### ISSUE THREAD

**Issue by zhongwencool** [Kenshin/simpread#3530]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  MacOS**

- 浏览器版本 **e.g. Microsoft Edge**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
无法导入配置
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/3116225/158054340-84bc35a6-0271-48e9-8715-5e8f5dd7f0e9.png">

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，看看下面两个解决方案

- https://github.com/Kenshin/simpread/discussions/3165
- https://github.com/Kenshin/simpread/discussions/2727

首先方案一，简单；方案二更精细修复。

**Comment by zhongwencool** [comment]
配置文件是可以下载的。点击就下成功了，是打开共通选项，一片空白，没有导入配置这个项

**Comment by Kenshin** [comment]
> 配置文件是可以下载的。点击就下成功了，是打开共通选项，一片空白，没有导入配置这个项

请仔细看我给出的链接内容，不是**下载**，而是恢复。

如果你已经使用了恢复方式的话，留存好你的配置文件，然后重装简悦，在通过手动导入的方式导入也可以解决。

**Comment by Kenshin** [comment]
搞定了？

**Comment by zhongwencool** [comment]
> 搞定了？
重装简悦，但是无法安装插件了，不过不影响使用，就这样吧。

**Comment by Kenshin** [comment]
> 无法安装插件了，不过不影响使用，就这样吧。

使用同步助手无法安装插件的话，看下 https://github.com/Kenshin/simpread/discussions/2342
