### ISSUE TITLE
新站适配：适配具有上下页的公众号

### ISSUE THREAD

**Issue by lzcer** [Kenshin/simpread#3532]
- 操作系统 **Windows **

- 浏览器版本 **e.g. Chrome 99.0.4844.51**

- 简悦版本 **2.0.0**

- 发生问题的地址 https://mp.weixin.qq.com/

**请描述你的问题**

> 阅读微信公众号文章时无法适配出下一篇和上一篇的链接，且通过【站点编辑器】->【前、后一页】来编写jquery语句来实现
原因：微信页面没有使用jQuery，并且无法通过脚本加载jQuery，因为微信做了校验，如果第三方引入，会终止渲染包括上/下一篇的内容
推荐解决方案：
方案一：在【站点】-> 【隐藏任意元素】的平级增加【放行渲染任意元素】，来对微信自带上/下一篇链接放行
方案二：对【站点编辑器】->【前、后一页】支持执行原生js(经实验现版本无法执行 )，如 document.getElementById('js_album_next').click()

**Comment by Kenshin** [comment]
我很少用公众号，它什么时候有的 **下一篇和上一篇**。（也可能我很少留意到...

另外，简悦实现了上一页和下一页的功能，它属于 [站点适配规则](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)，可以通过定制和自己写 JS 代码实现（内置了 jQuery）

你要是了解 JS 的话，可以根据上面的链接自己试试编写。

另外，方便的话，给我看几个有上下页的公众号

**Comment by lzcer** [comment]
简悦实现的此功能我发现了，但是实际使用发现必须要使用jQuery的语法，而实际上微信公众号页面是不提供jQuery的，也无法通过插件去插入jQuery，因为会校验完整性
可以使用原生的js来实现公众号自己的【下一篇】的调用
方法：
document.getElementById('js_album_next').click()
document.getElementById('js_album_prev').click()
而简悦提供的此功能无法解析原生js，至少无法解析上述内容，填充内容如下




运行结果：页面底部未渲染两个翻页按钮
而写入jQuery语法内容：





运行结果：成功渲染按钮





按钮执行结果：



另外提供一个可以翻页的公众号文章：
https://mp.weixin.qq.com/s/Ako2R8bk7S1jf4Imp8mqCQ


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 微信公众号优化（附推荐方案） (Issue #3532)





 
我很少用公众号，它什么时候有的 下一篇和上一篇。（也可能我很少留意到...
 
另外，简悦实现了上一页和下一页的功能，它属于 站点适配规则，可以通过定制和自己写 JS 代码实现（内置了 jQuery）
 
你要是了解 JS 的话，可以根据上面的链接自己试试编写。
 
另外，方便的话，给我看几个有上下页的公众号。

**Comment by Kenshin** [comment]
> 简悦实现的此功能我发现了，但是实际使用发现必须要使用jQuery的语法，而实际上微信公众号页面是不提供jQuery的，也无法通过插件去插入jQuery，因为会校验完整性

跟微信没关系，简悦自带了 jQuery，如果你会 JS 的话，我可以告诉你使用方式，我简单的描述下：

> 你需要在简悦的域里面才能生效

![image](https://user-images.githubusercontent.com/81074/158056985-065ad565-a60c-46d7-ae4c-20081c899198.png)

另外，你给出的链接太少了，我不清楚是否每个公众号都是一样的方式，方便的话，多提供几个 URL 才能做参考。

**Comment by lzcer** [comment]
切换了Console中的域确实可以执行正常jquery语法了，从Console中也可以成功触发切换章节，只是在简悦插件中配置该语句无法实现切换章节，正如上个邮件反馈的那样，实际触发会往链接后面拼接一个对象，然后丢失页面。
不清楚是否是我的写法有问题

另外提供的链接是为了方便你做测试，至于其他拥有翻页功能的公众文章我暂时也没办法提供
其实简单的解决方案是让配置项支持原生js，当然，目前插件内置jQuery，统一jQuery语法也是非常合理，只是就目前来看还存在bug
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 晚上7:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 微信公众号优化（附推荐方案） (Issue #3532)





  
简悦实现的此功能我发现了，但是实际使用发现必须要使用jQuery的语法，而实际上微信公众号页面是不提供jQuery的，也无法通过插件去插入jQuery，因为会校验完整性
  
跟微信没关系，简悦自带了 jQuery，如果你会 JS 的话，我可以告诉你使用方式，我简单的描述下：
  
你需要在简悦的域里面才能生效
  

 
另外，你给出的链接太少了，我不清楚是否每个公众号都是一样的方式，方便的话，多提供几个 URL 才能做参考。

**Comment by Kenshin** [comment]
> 只是在简悦插件中配置该语句无法实现切换章节

你需要使用 [简悦提供的适配规则](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)，而不是直接写 JS... 

我再说一次，适配是没问题的，只是你使用的方式不对。  😂 

既然仅找到这一个页面，就先搁置吧，我需要更多的类似方式才能判断是否具有共性，因为公众号的并不是一个 100% 一样的结构页面。

（仅仅只是提示）还有，不要通过 Email 回复，因为如果你截图的话，是没办法出现在这里的，需要进入  https://github.com/Kenshin/simpread/issues/3532 再回复我。

PS：灯海寻尸别追了，是个坑，我去年就掉里面了...

**Comment by lzcer** [comment]
>（仅仅只是提示）还有，不要通过 Email 回复，因为如果你截图的话，是没办法出现在这里的，需要进入 https://github.com/Kenshin/simpread/issues/3532 再回复我。
> 你需要使用 [简悦提供的适配规则](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)，而不是直接写 JS...
> 我再说一次，适配是没问题的，只是你使用的方式不对。 😂


明白了，我会重新补充一下截图。
我确实是使用的这个规则配置的
![image](https://user-images.githubusercontent.com/49141481/158099049-d53dcd83-7b14-4008-85fa-81b09ef60f14.png)
实际运行结果确实渲染了翻页按钮，但是点击按钮触发的事件不对，如下：
![image](https://user-images.githubusercontent.com/49141481/158099139-7392a014-20c6-41cf-bb09-c4f533470217.png)
你可以尝试一下，或者如果是我打开方式不正确，辛苦提供一个正确的语句我试下

**Comment by Kenshin** [comment]
抱歉，之前漏掉了这个 Issues ，你可以通过下面的方式插入任何

`[[{}]]`

[适配规则文档](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)已经说明了这点

![Uploading image.png…]()
