### ISSUE TITLE
文章添加到稍后阅读「导出失败，此功能为实验性功能……」

### ISSUE THREAD

**Issue by Hulkhao** [Kenshin/simpread#3535]
环境：高级账号+同步助手
网址举例：
https://www.zcool.com.cn/work/ZNTgyNzA2MzI=.html
https://www.zcool.com.cn/work/ZNTgyMDEzOTI=.html

**Comment by Kenshin** [comment]
嗨，请使用快照的方式或稍后读内置解析方案，最简单的方式是 [配置知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 一步到位
