### ISSUE TITLE
用户手册的优化问题

### ISSUE THREAD

**Issue by wandan** [Kenshin/simpread#3538]
软件是个好软件，但是把用户手册弄得如此复杂——一个页面上N个链接，点进去又是三句话加一句「详细操作请查看……」，完全不考虑用户体验吗？我只是想绑定一下高级帐户，居然花了一个小时。

**Comment by Kenshin** [comment]
嗨，可以试试新版教程 https://kb.simpread.pro
高级账户的使用在购买时就已经有详细说明

**Comment by wandan** [comment]
抱歉，实在看不下去。想请教如下几个问题：

- 绑定本机的浏览器之后，手动导出配置文件，是否就可以在任意情况（3台以内）下激活高级帐户？
- 配置文件是否包含标注、稍后读等使用过程中积累的内容？如果是，是否意味着需要经常手动导出配置文件？如果不是，该如何保存在本机积累的标注、稍后读等内容呢？
- 自动同步功能是否一定需要安装坚果云？
- 同步助手的安装包下载能不能稍微优化一下？一种下载到一半就不动了，一种一定要账号，还有一种完全没看到下载链接。
