### ISSUE TITLE
zerohedge进入阅读模式没有高亮文章部分

### ISSUE THREAD

**Issue by TyrianXia** [Kenshin/simpread#354]
非常好用的插件，感谢。目前www.zerohedge.com这个网站的配适有点问题，自己不会编，希望能调整一下。
另外，一个小建议，能不能让临时阅读模式一直存在，这样对很多网站，我就可以一开始手动选高亮区域，而不用进入阅读模式再调。

**Comment by Kenshin** [comment]
感谢反馈~

www.zerohedge.com 并未适配，只是「智能识别」出正文了，但显然，识别的有问题。

我会单独适配这个页面，适配后会通知你~

**Comment by Kenshin** [comment]
已添加此站，由于是 E 文，以防不测，我将它加到了 `第三方适配列表` 中。
导入方式：选项页 → 站点管理 → 加载第三方适配列表 → 导入第三方适配列表 即可。

**Comment by TyrianXia** [comment]
太感谢了！
