### ISSUE TITLE
简悦 · 稍后读部分图标加载失败的Bug

### ISSUE THREAD

**Issue by excelsior222** [Kenshin/simpread#3540]
**请说明发生问题的环境**

- 操作系统 **Windows 10 家庭中文版 20H2**

- 浏览器版本 **Chrome 99.0.4844.51（正式版本64 位）**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <SimpRead 简悦 · 稍后读>

**请描述你的问题**

常规网络情况下，在稍后读页面，反向链接和阅读模式两个按钮的图标无法正确加载；开启VPN后，有时可以正确加载，有时不可以。

**截图**

![1](https://user-images.githubusercontent.com/93578207/158296339-32df4267-7542-4efb-b751-b517985d6921.png)

![2](https://user-images.githubusercontent.com/93578207/158296354-e5eac142-0459-4bbb-9579-456e45c4ebb2.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

也不算是 Bug，icon 使用了 https://fontawesome.com 的 CDN 方案，你可以试试 更改 DNS 的方式，看看能否解决。

详细描述可以看这里 https://github.com/Kenshin/simpread/discussions/2906

**Comment by excelsior222** [comment]
非常感谢，确实是成都电信的网络，使用评论区的DNS 223.5.5.5，已经解决了~

**Comment by Kenshin** [comment]
okay 解决就好。

另外，设置 DNS 也不仅仅只是为了简悦，更可以避免其它的「污染」。
