### ISSUE TITLE
代码增强运行报错

### ISSUE THREAD

**Issue by onenovice** [Kenshin/simpread#3544]
发生网页http://ourjs.com/detail/529ca5950cb6498814000005?mode=light
截图
![image](https://user-images.githubusercontent.com/37800761/158341980-7c75f339-d1bb-4429-aaec-36ac3d89a30e.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
