### ISSUE TITLE
高级用户登录使用

### ISSUE THREAD

**Issue by dennes2020** [Kenshin/simpread#3546]
我有一台台式机两台笔记本，高级帐户授权，可以同时开机使用其中两台电脑的简悦稍后读吗？

**Comment by Kenshin** [comment]
> 可以同时开机使用其中两台电脑的简悦稍后读吗？

不可以的，**同一个账户（人）不能同时存在并使用于两台设备上**，会被锁。

但下面的方式是没问题的：

- 不同时间段使用两太电脑
- 同一台电脑，多个浏览器同时使用。

**Comment by dennes2020** [comment]
我理解您的这个设定的用意，但我经常需要把单位的电脑24小时开机，在家里通过vpn访问，这个时候就是两台电脑同时使用了。按照您现在的设置，我如果关闭单位电脑安装了简悦的浏览器，用另外的没有安装简悦插件的浏览器，同时在家里使用安装了简悦的浏览器高级帐户，这样就没问题了吗？


Kenshin Wang ***@***.***> 于2022年3月16日周三 18:40写道：

**Comment by Kenshin** [comment]
> 但我经常需要把单位的电脑24小时开机，在家里通过vpn访问，这个时候就是两台电脑同时使用了

你误解我的意思了，上面可能有一个情况太少见了，我就没说（你可能恰恰是这个情况）

下面这种行为也是被允许的

>  同时开两台包含高级帐户的设备，但只有一台设备有高级帐户相关功能活跃。

简单的说，**只要不是高级帐户功能在同一时间活跃就完全没问题**，比如：

1. A 电脑登陆高级帐户
2. B 电脑登陆高级帐户
3. A 电脑使用高级帐户功能 a b c
4. B 电脑同时使用没有任何高级的功能 d e f

这种也没问题。

**Comment by dennes2020** [comment]
明白了，谢谢你的耐心解答！

Kenshin Wang ***@***.***> 于2022年3月18日周五 11:42写道：

**Comment by dennes2020** [comment]
我如果多买几个高级用户，在多台电脑上授权，收藏到稍后读的网文能够在不同高级账号之间同步吗？

liu feng ***@***.***> 于2022年3月18日周五 16:03写道：

**Comment by Kenshin** [comment]
> 明白了，谢谢你的耐心解答！

没事的。

> 我如果多买几个高级用户，在多台电脑上授权，收藏到稍后读的网文能够在不同高级账号之间同步吗？

不能的，但简悦会推出更多设备的版本，目前是三设备，以后可以通过累加的方式增加更多设备，你可以先填写此调查问卷 https://wj.qq.com/s2/7093035/87a2/ 等出了此功能后，优先给内测用户测试。

**Comment by Kenshin** [comment]
另外，方便的话，请帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

这是对简悦最好的帮助了～
