### ISSUE TITLE
自动同步含备注标注到 Readwise 结构错乱（不含备注则无此问题）

### ISSUE THREAD

**Issue by byheaven** [Kenshin/simpread#3548]
同步助手启用readwise的标注导出，在简悦进行标注，并添加笔记后。笔记的内容也会出现在原文标注部分一起同步到readwise，见下图：
![telegram-cloud-photo-size-5-6167837800771202841-y](https://user-images.githubusercontent.com/30173023/158734989-fd1920a5-05b6-4222-b9fa-678420f55079.jpg)

**Comment by byheaven** [comment]
另外，希望能够将简悦中对标注打的Tag也同步到Readwise(API应该是支持的)

**Comment by Kenshin** [comment]
okay

**Comment by Kenshin** [comment]
@TrumpTan 

我建议新建一个 Issues 录屏并附上你的 URL 给我看下，先测试正常点的页面 e.g. https://sspai.com/post/69972 是否存在这个问题，然后再测试你遇到问题的 URL 并告诉我。

你的问题跟 Readwise 无关。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 修复了备注也会导入到 Readwise 的问题

新版解决了这个问题。😄

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
