### ISSUE TITLE
稍后读打卡后页面空白

### ISSUE THREAD

**Issue by Joeyy886** [Kenshin/simpread#3549]
chrome打开稍后读的独立窗口，显示不出来内容
![image](https://user-images.githubusercontent.com/100665395/158803193-d1a5f0a9-feaf-403c-be3b-719ae07fd309.png)
![image](https://user-images.githubusercontent.com/100665395/158803316-879bc48e-7b84-4eda-a3b7-2bd7629c8e8f.png)

**Comment by Kenshin** [comment]
估计是数据出错造成的，请问你遇到这个问题的前使用了什么方式保存稍后读？

解决方案

1. https://github.com/Kenshin/simpread/discussions/3165
2. https://github.com/Kenshin/simpread/discussions/2727

首选方案一，简单些；方案二更精细些。

**Comment by Joeyy886** [comment]
之前一直是chrome里网页右键保存的，今天重新打开突然又好了，也不清楚什么原因。先看看上面两个链接，自己研究一下，谢谢。

**Comment by Kenshin** [comment]
> 之前一直是chrome里网页右键保存的，今天重新打开突然又好了，也不清楚什么原因

这样的说，可能是之前突然同步助手「死掉了」造成的，在遇到类似问题，看上面给出的链接 100% 都能解决。

没问题就好，我关闭这个 Issues 了~
