### ISSUE TITLE
保存页面到印象笔记失败

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [Kenshin/simpread#355]
页面地址：https://zhuanlan.zhihu.com/p/36214840?utm_source=com.evernote&utm_medium=social&utm_member=MDdiNjU5YmVhMDgyY2ZlYTkzMDcwZThjNjVhZDY0N2U%3D

**Comment by Kenshin** [comment]
谢谢反馈，关于 Evernote 的问题请看系列关联问题 https://github.com/Kenshin/simpread/issues?q=is%3Aissue+is%3Aopen+label%3Aevernote

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，重构了 【导出到 印象笔记】的代码，基本上解决了导出总是失败的问题。

同时增加了当导出失败时，以 **Markdown 格式 二次保存** 及 提交到 **待决站点机制** ，确保万无一失。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
