### ISSUE TITLE
自定义导出无法使用稍后读加载本地缓存文件

### ISSUE THREAD

**Issue by samwei12** [Kenshin/simpread#3554]
**请说明发生问题的环境**

MacOS： 11.6
Chrome： 99.0.4844.74 
简悦版本 2.2.0

**请描述你的问题**

使用场景： 简悦阅读模式或者稍后读--》标注---》导出HTML +Markdown到本地---》Logseq 查看标注

1. 使用自定义导出，标题为 `{{un_title}}{{mode}}`
2. 使用自动化标注后直接导出 HTML 跟 Markdown 到本地（这里我选了 NAS 的同步目录）
3. 使用 Hazel 规则导出 xxx@annote.md 到 Logseq 目录

问题：
1. 如果标题使用 `{{title}}{{mode}}` 生成的文件分别为 xx.md@annote 和 xx.md 而不是像  `{{un_title}}{{mode}}` 一样是 xx@annote.md （这个 bug 我重置所有配置之后，不再复现）
2. 因为我没有使用坚果云（公司屏蔽），所以无法使用  `{{id}}{{un_title}}{{mode}}` ，否则导出的标注文件中，跳转地址会找不到 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/12758352/158931038-1651f5b7-5517-456c-ae1f-04e8157b21a9.png">

补一张图：
![image](https://user-images.githubusercontent.com/12758352/158934327-3795462c-c47a-4960-afe2-93283e992db6.png)

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/12758352/158934288-d12340b0-b7cd-44cd-baac-51cd9b426477.png">

3. 因为 1 和 2 的原因，导致稍后读无法加载本地缓存的 HTML 文件，规则不符合 `id title.html`   
<img width="988" alt="image" src="https://user-images.githubusercontent.com/12758352/158931480-005d21f4-47e0-4355-955f-d7aac31b2ac1.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/12758352/158931609-72061b56-2a48-45a3-9a41-8e17a6572bcc.png">

update: 看了一下，上图的  `-`  在稍后读中转换成了 `|`
那么: `un_title` 代表的就是稍后读标题，那么为什么按照这个格式保存下来的文件，跟稍后读里面打开加载的逻辑反而会不一样？ 必须要 `title` 或者 `idx-title`？  

**预期**
1. 是否能够支持直接按照 title 来加载缓存，而不是要求有 id
2. 如果必须要有 id，那么非坚果云是否能够使用类似格式，而且能够正常在 Logseq 中进行标注跳转 html
3. 希望简悦不要跟坚果云绑定太死，虽然坚果云确实很好用，但用不了坚果云也不应该导致很多功能用不了，是否可以有一些其他替代方案，比如 iCloud、NAS、WebDAV 等

另外，简悦--》Logseq 非常的棒，1+1>2了，十分感谢，期待能够解决稍后读本地缓存问题，就更完美了

**Comment by samwei12** [comment]
补充一下，目前自动化中如果选择手动模式，那么在动作那里，点击自动化流程无任何反应，

<img width="994" alt="image" src="https://user-images.githubusercontent.com/12758352/158932308-24df11ea-4be3-4514-8c5c-1ca0ab215054.png">

为什么不希望自动化呢？ 因为每一次标注都会全量保存 6 次，html（用于标注）、markdown（用于 logseq）、textbundle（用于离线永久保存） 各两次，速度非常慢

**Comment by Kenshin** [comment]
> 因为我没有使用坚果云（公司屏蔽），所以无法使用 {{id}}{{un_title}}{{mode}} ，否则导出的标注文件中，跳转地址会找不到

使用 `{{id}}{{un_title}}{{mode}}` 与坚果云无关，也就是说不使用坚果云也能这么设计，只是需要保证 `xxx/SimpRead/output`  目录结构的存在，才能使用 `http://localhost:7026/reading/xxx`

坚果云的加持是为了使用外部链接（类似 Dropbox 也是目前官方支持的方案）

> `http://localhost:7026/pdf/xxx`

这里需要改成 `http://localhost:7026/reading/xxx` 注意 pdf → reading 的区别

> 是否能够支持直接按照 title 来加载缓存，而不是要求有 id

`title` → 原文标题
`un_title` → 稍后读标题

这两者是可以不同的，你可以使用 `title`。

> 网盘的选择问题

简单的说下

1. 简悦可以支持任何网盘，甚至 iCloud 都可以
2. 知识库依赖于  `xxx/SimpRead/output` 结构
3. 坚果云和 Dropbox 是为了可以使用 [外部永久链接](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E8%B5%84%E6%96%99%E5%BA%93) 而做的，目前仅支持这两个网盘，如果你不使用此功能就不限于何种网盘。

***

简单的描述下，其实你遇到两个误区：

1. 使用 `{{id}}{{un_title}}{{mode}}` 与坚果云无关，你可以不使用坚果云，注意结构一致即可。

4. `http://localhost:7026/pdf/xxx` → `http://localhost:7026/reading/xxx` 结合 `{{id}}{{un_title}}{{mode}}` 就没问题了。

***

> 目前自动化中如果选择手动模式，那么在动作那里，点击自动化流程无任何反应

这里确实是个 Bug，但可以这么解决：

![image](https://user-images.githubusercontent.com/81074/158935912-c5595646-442a-4e6f-a877-698696b235f5.png)

在阅读模式下，使用下图的方式手动导出

![image](https://user-images.githubusercontent.com/81074/158935952-1732f818-4cba-46cf-88a7-88271dc3ca98.png)

**Comment by samwei12** [comment]
请教下，我按照你说的之后，出现了 404 问题，
同步文件夹配置
<img width="900" alt="image" src="https://user-images.githubusercontent.com/12758352/158979530-931cd458-f263-4c80-bf1d-26906f6eff95.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/12758352/158979585-cc104644-bcfc-4ed8-9678-6160c83fb1f0.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/12758352/158979625-6f72409b-f901-4655-96a1-b9de6ed4d6a1.png">

同时插件也进行了配置，pdf改为reading
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/12758352/158979839-f824e503-8599-45d9-b112-11c8ea882791.png">
<img width="925" alt="image" src="https://user-images.githubusercontent.com/12758352/158979866-1bbb99ba-853c-4e54-8848-3b936c950786.png">

报错 404
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12758352/158979936-06fa9e67-8a68-4fd8-ab13-e854377e87e9.png">

**Comment by samwei12** [comment]
https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B
我看这里文档是说一定要坚果云根目录的
<img width="681" alt="image" src="https://user-images.githubusercontent.com/12758352/158981117-bf7e2fe5-d210-4f26-b3c8-6dc769cbe1bc.png">

所以我放到本地文件夹其他路径，但保持 `xx/SimpRead/output` 是可行的吗？能够访问到 http://localhost:7026/reading/xx ?

**Comment by samwei12** [comment]
补充：

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/12758352/158982350-90a8abe4-52c9-45bd-9fb4-db3019c7c89f.png">

看起来我的 localhost 还是认了 pdf ，而不认 reading，这里配置改动是否存在问题，好像没生效

**Comment by samwei12** [comment]
尝试了多次删除本地全部数据，重新导入配置，不生效

**Comment by Kenshin** [comment]
> 报错 404

emmm 不应该的，你试试访问 http://localhost:7026/reading/index 返回什么结果？

**Comment by samwei12** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/12758352/158984626-9890c01c-0742-420d-ad18-f01fd22d42db.png">

**Comment by Kenshin** [comment]
emmm 收到，我调查后回复你～

**Comment by samwei12** [comment]
好的， 我尝试过卸载插件重装，没起作用，还是返回空文件列表

**Comment by samwei12** [comment]
update:
1. 尝试过卸载重装简悦助手，无效
2. 卸载插件重装，无效
3. 更改端口号为 7027，无效
4. 删除全部配置，使用坚果云，按照教程里面一步步来，无效
 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/12758352/159168833-6ee15db7-7130-4429-b2b5-afa0798c58db.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/12758352/159168842-af206f7b-dcfb-4c23-9ad8-a7b3f3f601e1.png">


查看了一下本地端口：
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12758352/159168637-ef4a90a5-793a-4179-a743-47f4424fbea2.png">

感觉也不像是端口占用问题
<img width="1896" alt="image" src="https://user-images.githubusercontent.com/12758352/159168694-edfbc41d-ae33-49ce-a4b3-f42945da67c1.png">

现象： 
1. 能够正常访问 7026 端口，但 index 里面为空
2. 导致本地知识库完全无法使用，本地标注文件链接无法访问；且稍后读无法加载本地缓存文件

感觉就像是这个文件夹下面的内容没有访问到，缺少日志信息，没有办法进一步定位了，
系统：MacOS 12.2.1 (21D62)， 不确定是否有关

希望尽快排查一下，没有办法使用知识库，简悦就跟 Evernote 或者 Cubox 没啥区别了，无法整理标注、笔记并内化，多谢。

ps： 发现另一个 bug，自定义标题，在第一篇文章时候会有问题，没有 0- 前缀

**Comment by Kenshin** [comment]
嗨，今天稍晚些确认。

**Comment by Kenshin** [comment]
> 删除全部配置，使用坚果云，按照教程里面一步步来，无效

你使用了坚果云？然后也不好使？这 100% 不可能...

> 系统：MacOS 12.2.1 (21D62)， 不确定是否有关

应该没关系。

> 发现另一个 bug，自定义标题，在第一篇文章时候会有问题，没有 0- 前缀

是的，已经记录到 https://github.com/Kenshin/simpread/discussions/3098 （并附有解决方案

**Comment by Kenshin** [comment]
1. 我记得你之前使用 http://localhost:7026/pdf/xxx （xxx 请更换为 output 文件夹的任意文件名称） 是可用的？

![image](https://user-images.githubusercontent.com/81074/159199889-6df62e7b-cd0f-45bc-bdeb-543e4a47650d.png)

![image](https://user-images.githubusercontent.com/81074/159199903-e84863da-fc00-4d64-b062-1f36a4fea847.png)

2. 你的 output 文件夹里面有没有隐藏文件？另外同步助手是什么时候下载的？

**Comment by samwei12** [comment]
> 你使用了坚果云？然后也不好使？这 100% 不可能...

确实是的。。我把插件整个卸载重装了，可以看我上一条回复，对应的文件夹目录就是坚果云，跟本地目录报同样的问题

> 2\. 另外同步助手是什么时候下载的？

我是 1.0.1 版本，而且昨天尝试卸载重装了

> 2\. 你的 output 文件夹里面有没有隐藏文件？

没有，但有下载的 textbundle 格式文件，应该没影响吧

> 1. 我记得你之前使用 http://localhost:7026/pdf/xxx （xxx 请更换为 output 文件夹的任意文件名称） 是可用的

是的，现在依然可用，我就这么用的。。但有俩问题，上面提到了， 1. 自定义标题不能带 id，pdf 这个链接会跳不到，只能用 {{un_title}}{{mode}} ，用 {{title}} 都不行，因为 @annotate 加的位置不对，  2. 稍后读不能加载本地缓存文件，很费劲

**Comment by samwei12** [comment]
> 1. 我记得你之前使用 http://localhost:7026/pdf/xxx （xxx 请更换为 output 文件夹的任意文件名称） 是可用的？
> 
> ![image](https://user-images.githubusercontent.com/81074/159199889-6df62e7b-cd0f-45bc-bdeb-543e4a47650d.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/159199903-e84863da-fc00-4d64-b062-1f36a4fea847.png)
> 
> 2. 你的 output 文件夹里面有没有隐藏文件？另外同步助手是什么时候下载的？

感觉我打开方式不对。。。我的 pdf 后缀也不能像你这样，能够通过 id 定位打开，应该是同一个问题，id 的检索跳转出问题了

**Comment by Kenshin** [comment]
emmm 你这样做：

1. 把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3554
2. `ouput` 除了 `.html`  文件外不要有任何其余内容，包括任何隐藏文件，然后再试试 http://localhost:7026/reading/index

> 我的 pdf 后缀也不能像你这样

先不用理会这个问题，我只是记得你说 http://localhost:7026/pdf/xxx 可以访问（但找了上面的回复，似乎没有截图印证。
用排除法，先确定 http://localhost:7026/pdf/xxx 我说是否可以访问。

> 同步助手下载时间

如果要是近期下载就没问题，如果是去年五月份的话，就有可能有问题。

**Comment by samwei12** [comment]
> > 2. 你的 output 文件夹里面有没有隐藏文件？
> 
> 没有，但有下载的 textbundle 格式文件，应该没影响吧

破案了。。。就是这个问题， textbundle，被当作了文件夹，而不是一个单独文件，然后导致 index 那个文件索引出问题了，把textbundle 导出干掉之后，就可以正常出现索引了

<img width="461" alt="image" src="https://user-images.githubusercontent.com/12758352/159213271-371cfa9e-341d-47cf-9e2e-98f29398cee0.png">

**Comment by samwei12** [comment]
终于能用上了。。不过 textbundle 还是挺想要的。。毕竟 404 之后靠本地缓存 html 肯定是不靠谱的。
但好歹能用了，多谢

**Comment by Kenshin** [comment]
> 终于能用上了。。不过 textbundle 还是挺想要的。。毕竟 404 之后靠本地缓存 html 肯定是不靠谱的。 但好歹能用了，多谢

太不容易了...

关于 Textbundle 的问题，可以看下面的解决方案：

1. 简悦支持导出 Textbundle（估计你应该知道这个方式
2. 可以使用 Hazel 自动将 Textbundle 转移到 `SimpRead` 下面非 `output` 文件夹，知识库里面有 [不少这样的例子](https://github.com/Kenshin/simpread/discussions?discussions_q=hazel)
3. 同步助手接下来的版本会解决 Textbundle 以及支持更多方案
4. 如果防止 404 的话，可以使用 **离线 HTML**，当然 Textbundle 也是个办法

> 去年五月份的话，就有可能有问题。

同步助手解决了隐藏文件的问题，但还是「中招」在 Textbundle 这个事情上...

***

这个 Issues 也算是 2.1K Issues 最多的之一了，至少能进 5% 了 ...

不来个 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，都「对不起」这么多回复  😂

**Comment by samwei12** [comment]
必须好评，
补一个小 bug，自动化流程中，配置了加入稍后读就导出 html，但实际使用下来，使用快捷键添加稍后读没有起效，
不过还好，不是很影响使用

**Comment by samwei12** [comment]
挖坟了。。
<img width="859" alt="image" src="https://user-images.githubusercontent.com/12758352/159218104-c69b52c9-ae1b-4177-8d81-6e107167f8da.png">

**Comment by samwei12** [comment]
我记得之前尝试过离线 html 的，刚才试了一下，果然还是有问题
1. textbundle 并不会下载图片到本地，所以网页挂了，很有可能变成无图的，约等于 md 格式了，意义不大
2. 离线 html， 图片始终下载不到本地， 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/12758352/159219296-a9b80997-5c51-4d1b-aba4-a995407ce295.png">
约等于无法使用

我不确定具体的下载逻辑，但之前我用过 simplefileZ 之类的插件，下载速度还是挺快的。

**Comment by samwei12** [comment]
希望本地持久化保存网页的方案能够更完善一点

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3554#issuecomment-1073550720

肯定不会有问题的，每天都有 nnnn 用户在使用此功能以及 Textbundle，给个 URL 我看看，或者**隐身模式下仅使用简悦的方式** 试试。

> https://github.com/Kenshin/simpread/issues/3554#issuecomment-1073542233

竟然是老用户  👍 

> 自动化流程中，配置了加入稍后读就导出 html，但实际使用下来，使用快捷键添加稍后读没有起效，

快捷键 `d d` 加入稍后读，肯定没问题的，但确实有个 Bug https://github.com/Kenshin/simpread/discussions/2362

***

PS：看你的动手能力也很强，建议看看 https://github.com/Kenshin/simpread/discussions/ 里面的内容，尤其是 https://github.com/Kenshin/simpread/discussions/categories/重要通知 里面的通用性 Bug （以及解决方案）

**Comment by samwei12** [comment]
> 实现自动化的前提是：进入阅读模式后。未进入阅读模式时，仅可以加入稍后读，无法触发自动化。

确实可以了！



> 肯定不会有问题的，每天都有 nnnn 用户在使用此功能以及 Textbundle，给个 URL 我看看，或者**隐身模式下仅使用简悦的方式** 试试。

这个我现在环境确实不行，也有可能是被公司的墙屏蔽了，晚上我回家之后再尝试一下，

**Comment by Kenshin** [comment]
okay 有问题随时沟通~

**Comment by Kenshin** [comment]
哦，对了。

忘记确认了：不使用坚果云应该也可以使用 http://localhost:7026/reading/index 对应的功能。

**Comment by Kenshin** [comment]
嗨，昨天有简悦用户推荐了 https://www.cnblogs.com/samwei12/p/jian-yuelogseq-da-jian-ben-de-hua-ge-ren-zhi-shi-k.html 这篇文章，我准备转载到简悦的推送渠道，并添加到 https://github.com/Kenshin/simpread/discussions/2085 里面。

***

另外，下图这个疑问也可以解决，解决方案 👉  https://github.com/Kenshin/simpread/discussions/3241

![image](https://user-images.githubusercontent.com/81074/163917123-5e95e4db-3187-4159-bf83-417bde11a824.png)

**Comment by xiang578** [comment]
所以有计划让同步助手原生支持 textbundle 吗

**Comment by Kenshin** [comment]
@xiang578 

你怎么翻到这么老的 issues .... 而且你的问题跟这个 issues 完全无关 😂 

简悦早就支持了 [Textbundle](https://simpread.pro/docs/#/Textbundle) 方案，不止如此，还支持 [assets + md](https://simpread.pro/docs/#/Sync?id=assets-md) 方案

**Comment by xiang578** [comment]
> 



> @xiang578
> 
> 你怎么翻到这么老的 issues .... 而且你的问题跟这个 issues 完全无关 😂
> 
> 简悦早就支持了 [Textbundle](https://simpread.pro/docs/#/Textbundle) 方案，不止如此，还支持 [assets + md](https://simpread.pro/docs/#/Sync?id=assets-md) 方案

刚好看到他写的文章，然后使用 textbundle 格式保存稍后读的文章，发现 http://localhost:7026/reading/index 页面没有这篇文章的信息，另外直接用 http://localhost:7026/reading/xx 形式也无法访问。

**Comment by Kenshin** [comment]
@xiang578

> html 格式是用来在稍后读里阅读，然后textbunble格式是给其他知识库软件使用？

是的，本地快照仅支持 HTML。Textbunble 仅仅只是一种导出格式。
