### ISSUE TITLE
稍后读导出自定义标题失效导致无法正常根据内外部链接自动跳转正确标注位置

### ISSUE THREAD

**Issue by DelmarHuang** [Kenshin/simpread#3559]
**请说明发生问题的环境**

- 操作系统 **macOS 12.3**

- 浏览器版本 **Microsoft Edge
版本 99.0.1150.46 (正式版本) (x86_64)**

- 简悦版本 **2.2.0**

自定义导出的标题不带序号。原本已经成功配置，但是睡了一觉起来之后就失效了，期间什么都没修改。重置了配置文件，跟着语雀教程重新配置一遍仍然失效。所有文章都是无法带序号。

* 自定义模版：

```
#[[excerpt]] [{{title}}]({{url}}) 
- tags: #[[SimpRead]] {{tags}}
- read date: [[{{date_format|now|yyyy_MM_dd}} ]]
- desc: {{desc}}
{{#each}}
- [📌](<{{an_int_uri}}>)  {{an_html}}
{{>|an_note}}{{an_tags}}
{{/each}}

```
* 单条导出模板
```
{{#each}}
[{{an_text}}](<{{an_ext_uri}}>)
{{/each}}
```

* 文章链接：https://mp.weixin.qq.com/s/Fbko9j7DGroYLO-sZq9mzA

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

* 导出错误截图
<img width="789" alt="image" src="https://user-images.githubusercontent.com/54244063/159122011-f65a77af-1618-43a8-a3b2-93230bc03a77.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54244063/159122071-9d2b255b-d54d-492a-85b2-5113e5db7d43.png">

* 共通页设置
<img width="951" alt="image" src="https://user-images.githubusercontent.com/54244063/159121575-fc2a8d4d-b1d1-43ec-ae5e-6c28ac456e3d.png">

* 高级设定
<img width="908" alt="image" src="https://user-images.githubusercontent.com/54244063/159121643-6a1fc6c8-9ce2-49b7-a291-b357a296a24b.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/54244063/159121651-2158cbba-fc22-4791-8b8e-fe6d54f06bba.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/54244063/159121658-ec17ea97-8be6-48f8-a6be-d7bae15d1a1b.png">

* 服务
<img width="992" alt="image" src="https://user-images.githubusercontent.com/54244063/159121675-403d15dd-db1e-449e-b586-c6d895f3fad8.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/54244063/159121686-f80381d7-7e98-41ea-8117-80d910d9f601.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/54244063/159121705-f81453aa-93fd-4526-9707-02825eb43e2e.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/54244063/159121712-8d9ffe62-8d3e-4804-b592-2a95193ae91b.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/54244063/159121727-b55bc700-2df6-4302-b0cf-7b1b4a1e0213.png">

* 稍后读设置
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/54244063/159121782-04d2a020-0ca0-4310-8b45-8adc59cb0c1a.png">

* 同步助手设置
<img width="700" alt="image" src="https://user-images.githubusercontent.com/54244063/159121801-f8adac1c-1468-4951-9eb9-0c9926ce052b.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/54244063/159121814-0a34a095-10a2-479c-b9bc-ffa46a50b544.png">

* 坚果云设置
<img width="792" alt="image" src="https://user-images.githubusercontent.com/54244063/159121861-26c1486b-525b-4bd4-a831-e97acc0f42f9.png">

**Comment by Kenshin** [comment]
emmm

导出带需要的前提是：**加入稍后读**，如果只是单纯的使用导出功能的话，是不会带序号的。

看了下你的配置应该是没问题的，你可以试试**加个稍后读的自动化**，然后试试。

如果确实是通过加入稍后读触发但没有带序号的话，请发你的配置文件到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3559

**Comment by DelmarHuang** [comment]
> emmm
> 
> 导出带需要的前提是：**加入稍后读**，如果只是单纯的使用导出功能的话，是不会带序号的。
> 
> 看了下你的配置应该是没问题的，你可以试试**加个稍后读的自动化**，然后试试。
> 
> 如果确实是通过加入稍后读触发但没有带序号的话，请发你的配置文件到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3559

流程没错，先加入的稍后读再自动导出。已发邮箱，麻烦了！

**Comment by Kenshin** [comment]
收到，明天确认下。

**Comment by Kenshin** [comment]
1. 第一个稍后读确实无序号，这是个 Bug，解决方案 https://github.com/Kenshin/simpread/discussions/3098

2. 我根据你提供的配置文件再次添加一个新的稍后读就可以了。

3. 根据这个现象也跟「是睡了一觉起来之后就失效了，期间什么都没修改」 并没有关系...
