### ISSUE TITLE
反馈：BBC中文网，聚焦模式-导致图片消失

### ISSUE THREAD

**Issue by CaiJie0611** [Kenshin/simpread#356]
http://www.bbc.com/zhongwen/simp/sports-44572646
下图↓没聚焦之前
![image](https://user-images.githubusercontent.com/31266850/42063786-eaa09dde-7b65-11e8-8c64-750a349bebb9.png)
下图↓聚焦之后
![image](https://user-images.githubusercontent.com/31266850/42063809-09a70588-7b66-11e8-9357-9b98466c3a3e.png)

其他页面均有此问题。

**Comment by Kenshin** [comment]
谢谢反馈，因为 BBC 的图片设置比较奇怪，所以在排除列表中把它去除了...
我看看能否有好的办法解决掉。

**Comment by Kenshin** [comment]
当前站已适配，请更新

***

更新方法

- 点击 ➊ 即可
![image](https://user-images.githubusercontent.com/81074/57358987-2a06a100-71a9-11e9-89c8-18249c6e3fe7.png)

- 分别点击 ➊ ➋ 即可


![image](https://user-images.githubusercontent.com/81074/57359096-676b2e80-71a9-11e9-81ec-ffaadf659013.png)

***

简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
