### ISSUE TITLE
【Logseq】維基百科 自動化離線 MarkDown 產生無意義之頁面。

### ISSUE THREAD

**Issue by bs10081** [Kenshin/simpread#3561]
## 操作環境
- 操作系统 **macOS 12.3**

- 浏览器版本 **Chrome 99.0.4844.74 (Official Build) (x86_64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://en.wikipedia.org/wiki/Color_depth?oldformat=true

## 問題敘述

通過標註的方式進行自動化 離線 MarkDown 至 Logseq 時，造成了過多的無意義頁面產生，原因初步推斷為維基百科內文中的上標數字會被轉換為`[[1]]`，進而使得 Logseq 判定為頁面，如截圖所示。

期望能解決，感恩。

### 截图
<img width="1178" alt="CleanShot 2022-03-20 at 01 19 32@2x" src="https://user-images.githubusercontent.com/38148679/159131879-b12d3810-7f14-489d-97a3-ee0314525e20.png">

![CleanShot 2022-03-20 at 01 19 54@2x](https://user-images.githubusercontent.com/38148679/159131882-0c1a265b-7cef-42be-ad35-a4f897904851.png)

**Comment by OverflowCat** [comment]
导出的 ref 还是链接到原维基百科页面，没多大用途，可以试试移除所有上标后再进入阅读模式：

```js
document.querySelectorAll("sup[id^='cite_ref']").forEach(ele => ele.remove());
```

**Comment by Kenshin** [comment]
@bs10081 

抱歉，不知道为什么之前漏掉了这个 issues ，暂时使用 @OverflowCat 提供的方式，我看看能否通过插件来解决它。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
