### ISSUE TITLE
Medium 文章 gist 代码不显示

### ISSUE THREAD

**Issue by devlinlin** [Kenshin/simpread#3562]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://tech.olx.com/clean-architecture-and-mvvm-on-ios-c9d167d9f5b3>

Medium 文章 gist 代码在简悦模式下不展示

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

原文：
![image](https://user-images.githubusercontent.com/19910304/159155063-65de53aa-a36d-4d80-b1e6-2d7bab3b0d88.png)
简悦：
![image](https://user-images.githubusercontent.com/19910304/159155064-544f06e5-1559-4607-af32-c385ab9cf2f5.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
emmm

Gist 的嵌入目前暂时没有太好的解决方案，也算是代码段的问题，会集中在 #500 并关闭此 Issues 修复后会通知你~
