### ISSUE TITLE
信息错乱/消失

### ISSUE THREAD

**Issue by devlinlin** [Kenshin/simpread#3563]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://labuladong.github.io/algo/2/20/44/>

在这片文章中发现代码块与其对应的上下文与原文不一致

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/19910304/159155220-92540aba-aeab-46a3-bb87-4efeec9fc445.png)
![image](https://user-images.githubusercontent.com/19910304/159155224-6bcf4f59-4f6a-4220-a4b7-1357dda3b183.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，这个问题代码高亮插件的问题，你可以先禁用代码高亮插件，看看能否解决？

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
