### ISSUE TITLE
已经是高级会员，但是无法开启“同步助手客户端”

### ISSUE THREAD

**Issue by difeiqi** [Kenshin/simpread#3564]
已经是高级会员，但是无法开启“同步助手客户端”。

说明，已经参照：https://github.com/Kenshin/simpread/discussions/2816  
描述的方法操作了，仍然无效，包括重启浏览器。

环境说明： 我安装的是vivaldi浏览器（chrome内核）

目前我的右上角包含菜单是
![右上角](https://user-images.githubusercontent.com/101982253/159167500-e5cf3373-321c-4138-a59b-2c76995cb0cb.png)
：
登陆
仅授权当前设备
绑定您的高级账户资格
升级您的高级账户
找回您的高级账户

与上面超链接只有2个的选项不同，因此没敢尝试“ 解除当前设备的授权 ”

**Comment by Kenshin** [comment]
试试第二个选项。

**Comment by difeiqi** [comment]
谢谢，就是这个，还要再【仅授权当前设备】一下才行

**Comment by Kenshin** [comment]
搞定就好，其实 https://github.com/Kenshin/simpread/discussions/2816 里面描述了这个过程，如果你跟你的不一样，忽略

![image](https://user-images.githubusercontent.com/81074/159198457-bec7a377-79dd-476b-8ea9-9a4cd6456955.png)

然后继续看下面的步骤就行。

![image](https://user-images.githubusercontent.com/81074/159198484-db80ccec-9a55-42da-b759-b7e6f0e3c2cd.png)
