### ISSUE TITLE
简悦内部插件无法使用

### ISSUE THREAD

**Issue by BadgerBoss** [Kenshin/simpread#3565]
**发生问题的环境**

- 操作系统 **MacOS**
- 浏览器版本 **版本 99.0.4844.74（正式版本） (arm64)**
- 简悦版本 **2.2.0**

**问题**

1. 插件无法使用。
<img width="893" alt="2022-03-20 23 07 33" src="https://user-images.githubusercontent.com/29444674/159169039-6f5537c0-24e2-43ff-9b8c-68d02f972e90.png">
<img width="331" alt="2022-03-20 23 08 02" src="https://user-images.githubusercontent.com/29444674/159169045-afeb7382-0e9a-49fa-bbd7-27e04ce7ea4a.png">

2. 稍后读里丢失收藏文章，但离线文件还是保留着。
<img width="309" alt="2022-03-20 23 09 44" src="https://user-images.githubusercontent.com/29444674/159169098-4b4a20e3-0e92-4572-a145-2869dd8dc546.png">
<img width="100" alt="2022-03-20 23 09 51" src="https://user-images.githubusercontent.com/29444674/159169099-84a3b7ef-2f88-4168-8a63-87e5fee120e8.png">

**Comment by Kenshin** [comment]
你是新导入的配置文件吗？

1. 是不是没有开启自动同步（也就是说你的浏览器的配置文件是旧的）
2. 如果使用坚果云的话，即便丢失也可以找回 https://github.com/Kenshin/simpread/discussions/3165
3. 插件「无效」的问题，也可以通过 https://github.com/Kenshin/simpread/discussions/2342 解决。

不过，我感觉你应该是问题一，还是说你之前的配置文件是旧的？

给出的信息太少了，不是指结论信息，而是如何产生问题的信息，我没法精准判断。

简单的说：只要你有配置文件，且如果还用了坚果云，不会存在任何丢失问题，只是如何导入的方式。

**Comment by BadgerBoss** [comment]
问题解决了。

确实是浏览器的配置和外部配置不同步的问题。
1. 插件不能显示，按照操作成功显示出来了。
2. 稍后读也是通过手动同步浏览器配置到本地解决。

感谢！！！

**Comment by Kenshin** [comment]
哈哈，搞定就好，我关闭这个 issues 了～

坚果云还是比较不错的，免费帐户的历史记录有一个月的，基本上不会出现任何真正意义的丢失问题。

***

哈哈，最好的「感谢」是：请在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价。 🙏  💪  😏

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
