### ISSUE TITLE
Simpread将文章转到Obsidian无法生成backlinks

### ISSUE THREAD

**Issue by Yapwn** [Kenshin/simpread#3567]
问题具体来说是这样，我根据SimpRead给出的文档进行的设置：
![](https://raw.githubusercontent.com/CNMKYBW/BlogDataBase/master/Obsidian20220321112006.png)

这是我的配置：
![](https://raw.githubusercontent.com/CNMKYBW/BlogDataBase/master/Obsidian20220321112259.png)

但是最后在Obsidian并没有得到想要的效果：
![](https://raw.githubusercontent.com/CNMKYBW/BlogDataBase/master/Obsidian20220321112345.png)

不知道是哪个环节出了问题？

**Comment by Kenshin** [comment]
嗨，把你的配置发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3567

**Comment by CNMKYBW** [comment]
就把配置图片发一下是吗？

**Comment by Kenshin** [comment]
是配置文件

**Comment by CNMKYBW** [comment]
如何导出配置文件呢？

**Comment by CNMKYBW** [comment]
好的，我找到了，谢谢了

**Comment by Kenshin** [comment]
> 好的，我找到了，谢谢了

哈哈，刚想给你回复，就收到了你的回复。

我确认完会在这里通知你～

**Comment by CNMKYBW** [comment]
哈哈哈，好巧，已经发送了，请查收！辛苦了！

**Comment by Kenshin** [comment]
嗨，抱歉今天临时有些事情外出了，明天确认~

**Comment by Yapwn** [comment]
没事，你有时间看看就行

**Comment by Kenshin** [comment]
我使用了你的配置文件，得到了下面的截图

![image](https://user-images.githubusercontent.com/81074/159471071-19d2c02f-5631-48ec-98c5-82dd252062b8.png)

这是正常的，看下图，双链已经生成了

![image](https://user-images.githubusercontent.com/81074/159471279-b87868e1-e41e-47f1-924f-1492be4f1847.png)

如果你再导出 `146-开源、可定制的网页批注工具——Hypothesis@annote` 这个文件就可以了。

![image](https://user-images.githubusercontent.com/81074/159471493-d620675c-8414-41d9-80bb-fb1c1ab002d8.png)

导出后在 Obsidian 里面的查看效果。

![image](https://user-images.githubusercontent.com/81074/159471673-9590dbdb-8fd0-4387-a808-aa8ff2bdd703.png)
