### ISSUE TITLE
扩展选项交互bug

### ISSUE THREAD

**Issue by oneuser-coder** [Kenshin/simpread#3568]
**原因** 右下角的“帮助中心”和“给我反馈”两个按钮，展开卡片默认前者置于后者之上
**背景** 卡片需要手动点击原button关闭不能自动关闭的背景
**结果** 先点击_帮助中心_再点击_给我反馈_，会导致后者卡片被部分遮挡。

**Comment by Kenshin** [comment]
嗨，我把这个内容转移到了 https://github.com/Kenshin/simpread/discussions/3107#discussioncomment-2400404 并关闭此 Issues ～
