### ISSUE TITLE
插件没法使用的问题

### ISSUE THREAD

**Issue by difeiqi** [Kenshin/simpread#3569]
我的插件界面是这样的：

![我的插件](https://user-images.githubusercontent.com/101982253/159207707-2c5af76d-443d-454c-826d-978b629078e3.png)

官方教程：https://simpread.ksria.cn/plugins/details/7gcXYY4HAc
这个里面的插件界面是图标，与我的不同，
![官方插件](https://user-images.githubusercontent.com/101982253/159207755-21ee300c-28c3-4d29-95a6-fa7260f817af.png)

而且我的插件list里面，没有“插件触发器”的大菜单。

还有点比较奇怪，
每当我点击：【服务-》辅助管理-》阅读模式浮动面板定制器】的时候，都会弹出下载插件的页面，
![下载插件](https://user-images.githubusercontent.com/101982253/159207849-797ca81a-ae6d-4467-9762-76b6e38aa039.png)
实际上这个插件我已经下载过了，但感觉没有起到作用，系统没有识别出来，每次都让我重新下载安装

更奇怪的是，在【插件管理】中，已经能识别我安装的插件了：
![插件管理](https://user-images.githubusercontent.com/101982253/159207925-297a9e8c-17bb-46e9-852e-d2506533b586.png)

似乎插件并没有生效。。。。
还是我哪里什么配置要修改一下的？

**Comment by oneuser-coder** [comment]
有关第一个，这是可以更改的**选项**
路径：插件选项页-高级设定-阅读模式-高级控制面板的布局
![image](https://user-images.githubusercontent.com/57286891/159208623-4f1b88ff-62d5-49d5-b273-c9331c21e814.png)

**Comment by difeiqi** [comment]
我切换了图标模式，但是最下面还是没有看到“插件触发器”的栏目

**Comment by Kenshin** [comment]
1. 你的第一个界面是正确的，也就是说这个插件的文档未及时更新。
2. 插件触发器无法出现的问题，是不是你使用了同步助手？如果是的话，可以看 https://github.com/Kenshin/simpread/discussions/2342 解决方案

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

***

我关闭这个 issues 了。

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
