### ISSUE TITLE
如果按照步骤仍无法使用 API 的话，请看这里的解决方案

### ISSUE THREAD

**Issue by Fluoxetine-int** [Kenshin/simpread#3576]
### Discussed in https://github.com/Kenshin/simpread/discussions/2282

<div type='discussions-op-text'>

<sup>Originally posted by **Kenshin** May 29, 2021</sup>
> 当按照使用 [如何开通](https://simpread.pro/api/#/%E5%A6%82%E4%BD%95%E5%BC%80%E9%80%9A) 配置后，使用 API 时出现调用成功，但 `simpread_config.json` 未更新的解决方案。

## 可能是 `simpread_config.json` 路径错误造成的。

虽然，同步助手可以设置为任意路径，但 API 的话，则严格要求路径为 `<同步盘>/SimpRead/simpread_config.json`  否则会出现无法正确更新  `simpread_config.json` 的问题。

![image](https://user-images.githubusercontent.com/81074/136163969-5a577949-1268-4994-8274-052a82736c08.png)

</div>

**Comment by Kenshin** [comment]
嗨，我帮你把 https://github.com/Kenshin/simpread/discussions/2282#discussioncomment-2411852 转移到了这里。

***

这个情况时因为坚果云版本冲突造成的，简单的解释

你的客户端与坚果云 Web 端的 simpread_config.json 冲突产生的。

产生此问题的原因

使用 API 调用时也同时在操作浏览器里面的简悦。

解决方案

也很简单，在调用 API 时不要使用浏览器，一般来说，简悦的 API 都是跟 Mobile 环境有关系，为了解决在手机端无法收藏的问题。同样，一般这种情况都是在非使用 PC（浏览器）时的行为。

所以，只要保证：

白天使用电脑时，就不要同时使用 API 调用；反之也一样。

**Comment by Fluoxetine-int** [comment]
明白了，感谢回复！！

**Comment by Kenshin** [comment]
哈哈，小事情~
