### ISSUE TITLE
稍后读导出多了个标注，稍后读中未显示该标注

### ISSUE THREAD

**Issue by Asura-one** [Kenshin/simpread#3579]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本 Chrome 99.0.4844.74

- 简悦版本 2.2.0

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

打开稍后读，点击信息可查看标注数量，信息中显示是3个，而稍后读中标注模式和阅读模式显示的标注都是2个。而导出的`MarkDown`中显示是3个标注，和图谱中显示内容一致。

**截图**

![image](https://user-images.githubusercontent.com/19581386/159443863-58d98e24-ecfe-4690-84df-851c07205923.png)

<img width="878" alt="image" src="https://user-images.githubusercontent.com/19581386/159444078-0045545e-808b-45ec-a7d1-9b65c357e944.png">

![image](https://user-images.githubusercontent.com/19581386/159444221-dcbf0b55-0745-4f4e-9284-8f67f1aac8e1.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
emmm

请问在原页面查看时，右侧侧栏里面有几个标注信息？

PS：猜测可能是因为标注错误导致某个标注没有显示。

**Comment by Asura-one** [comment]
是这个吗？

![image](https://user-images.githubusercontent.com/19581386/159606485-ae74cdc5-4b50-478f-a9e1-4cd0d3e25dcc.png)

**Comment by Kenshin** [comment]
不算是，但也可以...

估计还是因为在标注时某个标注「错误」导致了没有在正文出现的奇怪情况。

解决方案：

1. 可以忽略这个问题，毕竟只是个例，或者说你在留意下这个情况。
2. 导出配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3579

**Comment by Kenshin** [comment]
嗨，你的邮件被误判了，我今天才发现...  😂 

我看了你的稍后读里面的数据，应该是你在代码段标注时出现了标注错误造成的。（当然这里不是说你标注时的问题，而是产生的数据是错误的。）

但恰好这两处标注指向了一个位置，因此才没有产生错误。

这属于非常少见的情况，可以忽略掉，你可以删除这个稍后读再重新添加，或者压根不用理会那个「存在但无法显示的标注」

PS：我直接关闭这个 issues 了~

***

方便的话，请在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

这是对简悦最好的帮助。 🙏  💪  😏
