### ISSUE TITLE
站点动作失效

### ISSUE THREAD

**Issue by Zeroto521** [Kenshin/simpread#358]
[某网站](http://www.pythoner.com/56.html)进入阅读模式后，各个动作都点不动了。

> v1.1.1

**Comment by Kenshin** [comment]
谢谢反馈，这是由于 `自动识别正文` 并没有提取正确造成的。
你可以为这个页面自己建一个适配即可解决。

**Comment by Kenshin** [comment]
请问是否还存在这个问题？没问题的话，请关闭这个 issues ~
