### ISSUE TITLE
解析掘金的某篇文章然后选择“复制Markdown到剪贴板”，然后粘贴到typora发现文章前面一部分内容缺失

### ISSUE THREAD

**Issue by LinnyR** [Kenshin/simpread#3580]
问题1.解析掘金的某篇文章然后选择“复制Markdown到剪贴板”，然后粘贴到typora发现文章前面一部分内容缺失；
问题2.解析之后在浏览器上看起来排版是没有问题的，但是一旦导出markdown开头部分格式就乱了。

这是这篇文章的地址，您测试一下是不是也有这个问题呢
https://juejin.cn/post/6938385978004340744

黏贴后
![image](https://user-images.githubusercontent.com/38827394/159481136-c47cc63b-6376-4b90-9fbd-ab489fcde9f6.png)

**Comment by Kenshin** [comment]
嗨，已解决此问题。

1. 更新 [官方主适配规则](https://github.com/Kenshin/simpread/discussions/2870)
2. 进入此文章后，确保你的与下图一致

![image](https://user-images.githubusercontent.com/81074/159613924-99d2dec9-e6ca-486a-bd55-e9e97b7e91ef.png)
