### ISSUE TITLE
希望能够增加微信端保存各种文章的能力

### ISSUE THREAD

**Issue by difeiqi** [Kenshin/simpread#3583]
我搜了下，好像简悦既没有公众号小程序，也没有原生的APP，
举个例子，Notion或者Pocket有原生APP，一些文章我总是可以用IOS自己浏览器打开，然后分享到这些独立的APP中，
想问下简悦可以支持这种么，或者将来计划支持？

**Comment by Kenshin** [comment]
是这样的

1. 简悦很少涉及到封闭环境，所以我不玩微信那套东西。
2. 你可以使用 [同步助手](https://kb.simpread.pro/#/page/%E6%94%B6%E8%97%8F%E5%8A%A9%E6%89%8B) 或 [Telegram bot](https://kb.simpread.pro/#/page/61f63f40-e012-4800-b29c-7164dd632457) 实现各种手机上的收藏功能。
3. 会有自己的 App

**Comment by difeiqi** [comment]
好的，
非常期待单独的app
