### ISSUE TITLE
手机kiwi浏览器无法绑定_授权_安装插件

### ISSUE THREAD

**Issue by zheeer** [Kenshin/simpread#3584]
手机浏览器Kiwi  Browser.安装简悦后阅读模式暂未发现异常。但是安装插件是总是显示'安装完成后自动关闭'的界面后就没反应了。用dropbox和坚果云进行授权或是登录账号时也是显示'授权成功后自动关闭'的界面后就没反应了。

**Comment by Kenshin** [comment]
嗨，这是正常的，Kiwi 无法使用授权功能，你需要在 PC 上先授权然后在「同步」到 Kiwi 上，细节可以看下 https://zhuanlan.zhihu.com/p/415622477

**Comment by Yusei-StarDust** [comment]
少教一步啊，傻傻如我後來才發現需要勾選 服務>授權碼>同步時是否包含授權服務中的授權碼的這個選項_(:з」∠)_ 不然在Kiwi上還是需要重新授權，偏偏Kiwi上授權沒用(つд⊂)

**Comment by Kenshin** [comment]
@Yusei-StarDust 

已更新~

**Comment by Yusei-StarDust** [comment]
> 已更新~

~~教程文件太多實在找不到在哪裡更新www~~可以指點一下迷津嗎ヾ(•ω•`)o

**Comment by Kenshin** [comment]
@Yusei-StarDust 

你不是解决了吗？

另外，我说的更新是指更新 https://github.com/Kenshin/simpread/issues/3584#issuecomment-1092417994 里面的内容到 https://zhuanlan.zhihu.com/p/415622477

**Comment by Yusei-StarDust** [comment]
我想說有沒有新的不知道的內容來學習一下，功能實在太多了_(:з」∠)_

**Comment by Kenshin** [comment]
> 我想說有沒有新的不知道的內容來學習一下，功能實在太多了_(:з」∠)_

有啊

1. 订阅 https://simpread.pro/subscribe 里面的渠道，每次更新我都会同步更新这些渠道，但最好能订阅 https://t.me/simpread

2. 教程中心 https://kb.simpread.pro/ （需要配置时使用它，也内含了新手入门）

3. https://zhuanlan.zhihu.com/p/451790929 这是知乎上面的新手入门

4. https://github.com/Kenshin/simpread/discussions/2085 里面是技巧汇总，比较高级，但都有教程指导。

当然，如果你只是想用阅读模式、插件、这类的基本上没有门槛。
