### ISSUE TITLE
阅读列表文章无法打开

### ISSUE THREAD

**Issue by excelsior222** [Kenshin/simpread#3585]
**请说明发生问题的环境**

- 操作系统 **Windows10 & iOS**

- 浏览器版本 **Chrome 99.0.4844.51（正式版本64 位）& Safari**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <简悦 · 阅读列表>

**请描述你的问题**

阅读列表的目录可以正常同步，但是点击文章标题后无法打开，iOS端网页加载进度条长时间卡在1/10的位置，Windows的网页则是一直转圈圈的状态，较长时间后500报错

**截图**

![image](https://user-images.githubusercontent.com/93578207/159661840-c567d3ef-95f1-429d-a04c-06fb0e52ec90.png)
![image](https://user-images.githubusercontent.com/93578207/159665439-d22bde2e-49a3-4dca-919c-1869951fa55b.png)

**Comment by Kenshin** [comment]
emmm 奇怪的问题。

1. 在 PC 端试试在**隐身模式下** 登录阅读列表， 能否成功？
2. 在某个 URL 点击右键看看它的 URL 是什么？e.g. 下图的 URL

![image](https://user-images.githubusercontent.com/81074/159681362-483ef048-db0c-4cbf-bed2-0f47325f241f.png)

**Comment by excelsior222** [comment]
> emmm 奇怪的问题。
> 
> 1. 在 PC 端试试在**隐身模式下** 登录阅读列表， 能否成功？
> 2. 在某个 URL 点击右键看看它的 URL 是什么？e.g. 下图的 URL
> 
> ![image](https://user-images.githubusercontent.com/81074/159681362-483ef048-db0c-4cbf-bed2-0f47325f241f.png)

确实有些奇怪，上周查看阅读列表的时候还没有出现这个问题，文章都可以很快速地打开

- 隐身模式下还是会出现同样的500报错
- https://simpread.pro/@excelsior/reading/22-Notion%20%E5%8F%B3%E4%BE%A7%E8%BE%B9%E6%A0%8F%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9B%AE%E5%BD%95?token=<我的token码>

**Comment by Kenshin** [comment]
> 图一的问题

换个没有安装简悦的浏览器试试就正常了，这是因为简悦扩展与阅读列表的样式冲突了，即便用黑名单也暂时无法解决。

> 速度慢的问题

是不是这个页面的 size 很大？或者是离线 HTML ？
同时试试更换你的 DNS 看看能否改善？

**Comment by excelsior222** [comment]
嗨，Kenshin，有两天没查看Github消息了，所以回复晚了，抱歉~ @Kenshin 

1. 之前存的是离线HTML，换成HTML之后打开速度变快了，不过出现一个新的小问题，部分保存成HTML的文件打开后图片无法正常加载（尺寸过小或者无法加载出来），如下图所示：

离线HTML图片效果
![image](https://user-images.githubusercontent.com/93578207/160084625-f5fab1f8-9906-4d87-b0c3-a6cbfc367402.png)

HTML（本地文件打开）图片效果
![image](https://user-images.githubusercontent.com/93578207/160084466-a7d1987d-0896-4716-a9ca-863e3ae44e8a.png)

HTML（Windows网页端阅读列表打开）图片效果
![5dad97383863ac1a919b6eae0c5d20e](https://user-images.githubusercontent.com/93578207/160084879-86e56090-03b5-476a-a958-7b92780e3fbc.jpg)

HTML（iOS端阅读列表打开）图片效果
![image](https://user-images.githubusercontent.com/93578207/160085635-2f79258e-c6f7-47c9-bfea-00ceaa79c50e.png)


2. 还有个小疑问：HTML和离线HTML最的主要区别是什么呢？离线HTML我理解就是，断网或者源网页被删除之后，依旧可以查看，文本和图片应该都是储存在本地的；HTML版本的话，假如源网页无法正常访问，是否文字和图片都不能查看？

**Comment by Kenshin** [comment]
哈哈，没事的。你可以把 Github 注册的邮箱改成你自己经常使用的就可以了，我偶尔会收到半个月（甚至）更多时间的回复。  😂 

> 之前存的是离线HTML，换成HTML之后打开速度变快了，不过出现一个新的小问题，部分保存成HTML的文件打开后图片无法正常加载（尺寸过小或者无法加载出来），如下图所示：

可能需要重新生成一次 HTML 后再试试，或者随便找个 URL  导出 HTML e.g. https://sspai.com/post/69972

> HTML和离线HTML最的主要区别是什么呢？

离线 HTML 是将网络的图片以字符串的形式存放在了 HTML，可以避免 404，但使用阅读列表打开它的话，确实会很「慢」，因为一个 HTML 文件大概至少 `1mb` 

***

另外，没有其它问题，我先关闭这个 issues 了，但你仍可以随时回复我。

**Comment by excelsior222** [comment]
> 可能需要重新生成一次 HTML 后再试试，或者随便找个 URL 导出 HTML e.g. https://sspai.com/post/69972

不同站点的尝试情况：

1. 少数派，通过加入稍后读后【自动化】指令导出的HTML，不管是本地还是在阅读列表打开，图片都可以正常显示

2. B站专栏，反复删除又添加了几次稍后读，通过【自动化】指令导出的HTML文件都出现同一种情况——本地文件打开，图片可以正常加载，阅读列表打开，全部图片都是空白；在稍后读阅读器中手动导出HTML，尝试5次，其中2次成功让通过阅读列表打开的图片全部加载正常，其余3次失败

3. 部分野生网站，情况同B站专栏

4. 微信公众号文章，通过【自动化】指令导出的HTML文件，在稍后读阅读器中，大部分图片显示正常，公众号头像图片会显示【此图片来自微信公众平台，未经允许不可引用】，全文最后一张图片显示空白（本地打开的HTML文件中这些都是正常显示的），手动导出HTML后恢复正常（但感觉这里有点背离了配置自动化的初衷，每次都还要手动再保存一次HTML）
![0c08f78c9b8369fdb7411b89ce12a2b](https://user-images.githubusercontent.com/93578207/160229424-722c53c1-65e5-49c3-9143-01a9bf3416d5.png)

总结：
目前通过自动化指令，快速储存网页为本地存档的知识库使用是没有问题的；但作为资料库，想通过阅读列表在移动端查看，有点不方便，存离线HTML会有部分文章加载过慢或失败的问题，存HTML会有部分图片无法显示的问题


### 过程中又发现了两个关于稍后读的小问题：

1. B站专栏在【稍后读】中解析失败
https://www.bilibili.com/read/cv15652610
已经打开内置解析器的情况下，刷新了十次左右，还是报错
![c389a8c457d5c211de7adec7855508c](https://user-images.githubusercontent.com/93578207/160229319-b0c95044-3d9f-4fde-ac90-5cf49393e0be.png)

2. 已经在选项页关闭了增强解析的选项，在【稍后读】中还是以打开增强解析的方式展示，所以就有部分微信公众号文章在【稍后读】中无法查看，必须打开源链接，然后再进入阅读模式查看

**Comment by Kenshin** [comment]
1. 把有问题（阅读列表不显示图片）的 URL 给我看下。

2. B站等相关问题，需要开启下面的选项

   ![image](https://user-images.githubusercontent.com/81074/160234899-cb1aeff0-ca82-46d8-972c-d2494b593f1a.png)

因为你使用了阅读列表的功能，所以直接在稍后读使用读取快照功能就可以了，这是最简单的方式。

**Comment by excelsior222** [comment]
> 1. 把有问题（阅读列表不显示图片）的 URL 给我看下。

https://www.bilibili.com/read/cv15652610
http://www.gamelook.com.cn/2020/09/395664


> 2. B站等相关问题，需要开启下面的选项
>    ![image](https://user-images.githubusercontent.com/81074/160234899-cb1aeff0-ca82-46d8-972c-d2494b593f1a.png)
> 因为你使用了阅读列表的功能，所以直接在稍后读使用读取快照功能就可以了，这是最简单的方式。

读取快照功能是指优先加载本地的离线文件这个功能吗，还是有一个单独功能按钮呀？
已经把上面两个选项都开启了，但是有篇微信公众号的文章还是存在加载不太正确的情况。因为之前发现打开增强解析微信公众号文章显示效果有点问题，所以我把它关了，但是在稍后读里呈现出来的解析效果和我关增强解析选项之前的一样，具体链接如下：
https://mp.weixin.qq.com/s/Iub3hdAgifzvmLYJa5ck0A

**Comment by Kenshin** [comment]
> 要求多端同步收藏,所以不能使用同步助手

就是这个选项，没有其它选项。

试试开启下图的选项

![image](https://user-images.githubusercontent.com/81074/160266859-bfc7aff6-fa10-4d38-86d3-d85926ff258f.png)
