### ISSUE TITLE
Save to evernote

### ISSUE THREAD

**Issue by yu-b14** [Kenshin/simpread#359]
The pages of Zhihu is not supported for saving to Evernote.

**Comment by Kenshin** [comment]
论坛类页面都不支持 `Evernote`

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，重构了 【导出到 印象笔记】的代码，基本上解决了导出总是失败的问题。

同时增加了当导出失败时，以 **Markdown 格式 二次保存** 及 提交到 **待决站点机制** ，确保万无一失。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
