### ISSUE TITLE
插件代码段增强报错，在访问Github的readme.md时

### ISSUE THREAD

**Issue by zhoujunxuan** [Kenshin/simpread#3593]
操作系统-Windows 10 专业版
浏览器-edge 版本 99.0.1150.46 (正式版本) (64 位)
简悦及代码度段增强 均为当日最新版

问题说明：
当在GitHub的README页面启动阅读模式时，网页右上角弹出提示（如下方截图所示），按指引提交问题反馈。

访问链接：https://github.com/johnrosen1/vpstoolbox/blob/master/README.md
访问模式：A A （阅读模式）
![image](https://user-images.githubusercontent.com/37800586/159956979-96dbe273-5f4e-4f05-ae5f-e3286c93d5fc.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
