### ISSUE TITLE
稍后读页面的所有icon图标无法正常显示

### ISSUE THREAD

**Issue by gujin03** [Kenshin/simpread#3597]
如图所示
![image](https://user-images.githubusercontent.com/38389059/160072093-1e1e6011-45e6-4aea-a06f-e3e31e450bbf.png)

**Comment by gujin03** [comment]
![image](https://user-images.githubusercontent.com/38389059/160072196-c85f1821-5b7f-450a-99bc-e7e812fc8eea.png)
右侧栏

**Comment by Kenshin** [comment]
嗨，解决方案看这里 https://github.com/Kenshin/simpread/discussions/2906

**Comment by gujin03** [comment]
我和上面@DruculaC这位情况一样，在公司用的专线出现的此种情况。 算了先不解决了，将就着用。

**Comment by Kenshin** [comment]
@gujin03 

一样的解决方案，需要修改你的 DNS，因为这些 icon 使用了 cloudflare 提供的线路。
