### ISSUE TITLE
开启简悦插件后notion的模板库网站会报错

### ISSUE THREAD

**Issue by lesir831** [Kenshin/simpread#3599]
操作系统 **Win11**

浏览器版本 **Edge 99.0.1150.52/Vivaldi5.1.2567.57 (Stable channel) （64 位） **

简悦版本 **2.2.0**

打开网站https://www.notion.so/templates 会报以下的错误 **Application error: a client-side exception has occurred (see the browser console for more information).**

经过排查已确定是简悦引起的，我没有使用简悦的阅读模式以及加入稍后读列表等操作，我使用未安装其他扩展的Vivaldi浏览器安装简悦插件并且不打开简悦进行任何操作的情况下打开上述网站问题依旧。

**Comment by Kenshin** [comment]
嗨，请使用 https://github.com/Kenshin/simpread/discussions/2347 提供的方式解决。

**Comment by Kenshin** [comment]
搞定就好~
