### ISSUE TITLE
能否像EasyReader一样可选页面部分进入阅读模式

### ISSUE THREAD

**Issue by jerry011235** [Kenshin/simpread#36]
EasyReader：https://chrome.google.com/webstore/detail/easyreader/boamfheepdiallipiieadpmnklbhadhc

2.这个扩展按钮图标能否自定义在地址栏末端？（这样点起来更方便，有时候扩展太多，眼花缭乱）
3.能否像 [愉阅](https://chrome.google.com/webstore/detail/happyreader/emjphcoeoofohgimppddgblomjbojnnh) 一样，如果页面有“第二页”字样，能自动提取下一页内容。

**Comment by Kenshin** [comment]
1. 未来的版本会有类似 EasyReader 的功能，已提上开发日程。😄
2. 新版 Chrome extension API 已经限时了在地址栏出现的功能，在稍低版本的 Chrome 安装简悦，自然就是在地址栏的右端，如 Chrome 42 等低端版本。
3. 此功能如同 `1` 一样，在开发列表中了，但具体哪个版本发布，我会根据开发周期而定。（总不能有个太长的开发周期...）😄

感谢建议~

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `临时阅读模式` 与 `高级聚焦模式` 均具有类似的功能，详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.0.4)
