### ISSUE TITLE
#暗色模式+高亮文字 → 无法看清高亮文字（如图）

### ISSUE THREAD

**Issue by PolarisPolaris** [Kenshin/simpread#3600]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/43163254/160164315-204c12b2-4b6e-492e-ba99-a37bd8ed77a6.png">

- 操作系统 ** MacBook Air (M1, 2020) | macoOsS Monterey Version 12.3**（最新版本）

- 浏览器版本 ** Version 99.0.4844.84 (Official Build) (arm64)**（最新版本）

- 简悦版本 **最新**

**Comment by Kenshin** [comment]
解决方案请看这里 https://github.com/Kenshin/simpread/discussions/3164
