### ISSUE TITLE
出现"当前配置文件出错导致无法打开选项页，你可以通过以下方式解决："

### ISSUE THREAD

**Issue by sandy9707** [Kenshin/simpread#3608]
普通的一个早上,我打开简悦的偏好设置,出现了如下语句
```
当前配置文件出错导致无法打开选项页，你可以通过以下方式解
决：
1。 下载当前配置文件（点击右侧）；                                 下载
2。 重装简悦，点击这里 查看简悦的下载地址；
3。将 下载后的配置文件导入简悦 即可自动修复此问题。
```
我自从上次依靠坚果云创造知识库并尝试使用个人中心进行阅读和每日回顾后很久没有打开设置了(个人中心运行的很好)
按照提示我尝试下载了配置文件并重装简悦,但是并没有解决问题.
我现在要做什么,谢谢你Kenshin.

**Comment by Kenshin** [comment]
嗨，试试此方式 https://github.com/Kenshin/simpread/discussions/3165 基本上能解决你的问题。

> 个人中心进行阅读和每日回顾后很久没有打开设置了(个人中心运行的很好)

哈哈，这个做法很有意思，你很久不用扩展端了吗？只用阅读列表？

**Comment by sandy9707** [comment]
扩展端是指哪些?
我平常用量最大的是加入稍后读后自动化同步到本地和语雀,本地文件直接用obsidian阅读和编辑.
因为不太能用的惯标注功能所以一直处于放置状态,也因此很少会打开"稍后读"应用查看.
简悦对我而言最大的意义是"保存"而非"批注",所以知识库的建立对我来说可以很轻松的将看到的东西保存到开放中心而不去仔细的阅读信息,如果需要修改我习惯放到obsidian中.

根据方式 #3165 的说法,本问题的原因是同时使用了同步助手和坚果云进行同步,那么应该如何解决这个问题呢,关闭同步助手/坚果云之一的配置同步吗?
谢谢
抱歉刚刚直接回复了邮件,我已成功从坚果云的历史中恢复了配置文件,现在正在检查如何关闭坚果云的自动同步而仅采用同步助手的.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/93817573/160267863-479cda86-83e7-49c9-8659-079f6553381f.png">

**Comment by Kenshin** [comment]
恢复的历史记录一般都没问题的，但...

> 抱歉刚刚直接回复了邮件,我已成功从坚果云的历史中恢复了配置文件,现在正在检查如何关闭坚果云的自动同步而仅采用同步助手的.

我没理解你的意思... 

你使用的「我自从上次依靠坚果云创造知识库并尝试使用个人中心进行阅读和每日回顾XXXX」方式就是应该使用简悦的自动同步与坚果云，但你提到的「现在正在检查如何关闭坚果云的自动同步而仅采用同步助手的.」

又是怎么回事？

**Comment by sandy9707** [comment]
就是这个问题出现的原因不是因为同时开启了两个同步吗,我想要以后不会出现这个问题需要做什么或者不能做什么.
我想要知道这个,谢谢.

**Comment by Kenshin** [comment]
嗨，产生这个问题的原因很多，下个版本会加强对 `simpread_config.json` 的错误结构兼容问题。

一般都是发生在通过 API 导入的情况，一旦发生后使用我之前提到的方式 100% 能解决问题。因为简悦的保存坚果云的频次很高，基本上不会出现丢失数据的情况。

即便一旦丢失的话，也可以随时联系我，把配置文件给我，我会手动帮你恢复。

**Comment by sandy9707** [comment]
扩展端是指哪些?
我平常用量最大的是加入稍后读后自动化同步到本地和语雀,本地文件直接用obsidian阅读和编辑.
因为不太能用的惯标注功能所以一直处于放置状态,也因此很少会打开"稍后读"应用查看.
简悦对我而言最大的意义是"保存"而非"批注",所以知识库的建立对我来说可以很轻松的将看到的东西保存到开放中心而不去仔细的阅读信息,如果需要修改我习惯放到obsidian中.

根据方式 #3165 的说法,本问题的原因是同时使用了同步助手和坚果云进行同步,那么应该如何解决这个问题呢,关闭同步助手/坚果云之一的配置同步吗?
谢谢

Kenshin Wang ***@***.***> 于2022年3月27日周日 12:28写道：

**Comment by Kenshin** [comment]
> 根据方式 [#3165](https://github.com/Kenshin/simpread/discussions/3165) 的说法,本问题的原因是同时使用了同步助手和坚果云进行同步,那么应该如何解决这个问题呢,关闭同步助手/坚果云之一的配置同步吗?

不是的，你理解错了。我的意思是：你可以使用 https://github.com/Kenshin/simpread/discussions/3165 提供的方式还原数据。

并不存在「关闭同步助手/坚果云之一」这个逻辑。
