### ISSUE TITLE
加入稍后读时如何修改标题？

### ISSUE THREAD

**Issue by linjunhe** [Kenshin/simpread#3612]
我想要保存离线的html（防止文章404）和高亮。

在“服务-自动化”中，设置了
1. “当加入稍后读后，导出到离线html”
2. “当加入标注后，导出到html”

有时候文章标题不合适，需要修改。
但是这样设置后，一加入稍后读，就已经导出了离线文件。
而在稍后读中修改标题时，不会同时修改离线html（或者html，markdown，textbundle）的文件名。
有什么解决办法么？
或者是有没有办法在添加进稍后读前提前修改标题？

**Comment by Kenshin** [comment]
嗨，目前没有好的解决方案，只能是当修改完标题后，手动导出一次。

不过，也可以使用下面的方案：

首先，可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 在加入稍后读前事先修改你的标题。

其次，你可以稍等几天，下周会有个新的插件发布，也可以改善此方式。

但我个人建议是首选方案，因为这样不会在本地出现旧的 `.html` （改标题之前的 html 文件）

**Comment by linjunhe** [comment]
@Kenshin  谢谢回复！期待新插件！

Live Editor可以修改标题，但是只要使用Live Editor，代码块增强插件的对代码块的渲染就会消失。有没有办法重新渲染？

另外想请教一下，有的html页面已经排版很不错了，有没有办法不使用简悦渲染，自动化保存原始html页面（而不是阅读模式的页面），在原始html页面上高亮？

**Comment by Kenshin** [comment]
> Live Editor可以修改标题，但是只要使用Live Editor，代码块增强插件的对代码块的渲染就会消失。有没有办法重新渲染？

这个暂时没有办法，不过，我考虑更新 Live Editor，让它仅支持简单的编辑模式。（不会破坏页面结构，但也无法提供富文本编辑功能

> 另外想请教一下，有的html页面已经排版很不错了，有没有办法不使用简悦渲染，自动化保存原始html页面（而不是阅读模式的页面），在原始html页面上高亮？

简悦的一切功能都建立在阅读模式基础上，所以是没办法提供你说的方式。（这不是技术的问题，而是简悦需求定位的事情）

**Comment by linjunhe** [comment]
好的，谢谢！

**Comment by Kenshin** [comment]
小事情，适配后通知你~

**Comment by Kenshin** [comment]
不过，顺道评个分

[Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价就好了~  🙏  💪  😏

**Comment by linjunhe** [comment]
已经评价啦

**Comment by Kenshin** [comment]
> 已经评价啦

 🎉  虽然我好像没有看到  😂

**Comment by linjunhe** [comment]
> > 已经评价啦
> 
> 🎉 虽然我好像没有看到 😂

我修改了一下 应该是可以看到 我这边看是modified xx secs ago

**Comment by Kenshin** [comment]
哈哈，你这也太认真了…

😂 👍

**Comment by Kenshin** [comment]
> 另外想请教一下，有的html页面已经排版很不错了，有没有办法不使用简悦渲染，自动化保存原始html页面（而不是阅读模式的页面），在原始html页面上高亮？

嗨，Live Editor 1.1.3 版发布了，增加了 [简易模式](https://github.com/Kenshin/simpread/discussions/2852#discussioncomment-2489840) 不会破坏正文结构，但也无法提供富文本编辑功能。

![](https://user-images.githubusercontent.com/81074/161367170-9c5faeec-fde8-4f94-a042-6a03d925fd7a.png)

PS：我关闭此 Issues 了。
