### ISSUE TITLE
简悦同步助手无法自启

### ISSUE THREAD

**Issue by Steven212121** [Kenshin/simpread#3613]
我下载了桌面端的简悦同步助手之后无法开机自启，每次都要手动（已经点了开机自启选项）
![image](https://user-images.githubusercontent.com/50981872/160270764-64bb29d6-5b5b-454e-b311-9ebfc77307e6.png)

**Comment by linjunhe** [comment]
可以试试[这个](https://github.com/Kenshin/simpread/discussions/1818#discussion-3104527)  #1818

**Comment by Steven212121** [comment]
谢谢！

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭这个 issues 了~
