### ISSUE TITLE
稍后读标注时语序错乱

### ISSUE THREAD

**Issue by Darkluna999** [Kenshin/simpread#3614]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 11**

- 浏览器版本 **edeg **

- 简悦版本 **2.2.0**

- 发生问题的地址 
    - https://zhuanlan.zhihu.com/p/371496530
    - 绝大部分知乎加粗字体，不清楚其他网站是否同样

**稍后读标注时语序错乱**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/53258301/160274177-09b63f69-7b4f-471f-8676-109cbf9e31a9.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
emmm 我没有遇到你说的问题

![image](https://user-images.githubusercontent.com/81074/160276221-ddc57f4b-316e-457b-90b5-3c398ce0ab6f.png)

你试试按照前后正序标注，e.g. 从 `比较....开始`

**Comment by Darkluna999** [comment]
是的我就是从比较开始划了一下的

**Comment by Darkluna999** [comment]
好奇怪啊。。。只有在跨越加粗字体的时候才有这种情况

**Comment by Darkluna999** [comment]
![image](https://user-images.githubusercontent.com/53258301/160281608-43b0a73e-bf35-4d9c-bf5a-3459953e8ae4.png)

**Comment by Kenshin** [comment]
> 好奇怪啊。。。只有在跨越加粗字体的时候才有这种情况

我明天再试试

**Comment by Darkluna999** [comment]
我把其他插件都关掉了也不行，有没有可能跟我用的edge canary有关

**Comment by Kenshin** [comment]
我的没问题

![image](https://user-images.githubusercontent.com/81074/160317938-a9ab112a-c6da-4866-b5bc-66db46d69175.png)

> 有没有可能跟我用的edge canary有关

应该有可能... 不建议使用 Canary 版，太激进了，我是开发人员，都只敢用 Dev 版，Canary 的问题太多了...
