### ISSUE TITLE
选项页无法打开

### ISSUE THREAD

**Issue by re-f** [Kenshin/simpread#3617]
高级帐户，在新的 mac 上导入dropbox的配置，再打开同步助手，此时“选项页”无法打开，关闭哦同步助手后能打开。与常见问题中的问题6现象不一样，具体查看下图。已经重装过chrome插件，仍然有相同问题
![simpleread](https://user-images.githubusercontent.com/8351089/160335641-3a4b42e8-3193-4591-8fa0-196b076b4b5d.gif)

**Comment by Kenshin** [comment]
嗨，你可以使用 https://github.com/Kenshin/simpread/discussions/3165 还原到正确的历史记录。

**Comment by re-f** [comment]
dropbox上历史记录显示的是3月15日最近都没做变更。
![image](https://user-images.githubusercontent.com/8351089/160344561-a57abfc0-5071-41f8-b95a-30131f6b2356.png)

我对比了最近两份配置，只有少数选项不一样，配置的格式上是没什么问题的
![image](https://user-images.githubusercontent.com/8351089/160345710-1742d22d-cb3c-4620-a969-b0a72696a8f0.png)

**Comment by Kenshin** [comment]
将你认为正常的配置文件下载到本地，再导入到简悦。

看看能否解决？

**Comment by re-f** [comment]
不可以，我导入了最初始化的配置，仍然无法使用。

备注：我在检查 配置中是否有 “null”，文件中是不存在的l。

**Comment by Kenshin** [comment]
> 不可以，我导入了最初始化的配置，仍然无法使用。

emmm 很奇怪，不太可能...只要你的 Dropbox 是最新的数据就没问题。

试试重新安装简悦再导入？

**Comment by Kenshin** [comment]
发送配置文件到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3617

**Comment by re-f** [comment]
已发送

**Comment by Kenshin** [comment]
okay 确认后回复你。

**Comment by re-f** [comment]
有进展了么？

**Comment by re-f** [comment]
我搞定了，我关了同步助手，然后将配置到处重新覆盖了一份

**Comment by Kenshin** [comment]
emmm...

你的邮件被误判为垃圾邮件了，不过还好搞定了。

PS：确实有误判的情况，但很少见，印象中也就三次。
