### ISSUE TITLE
插件『代码段增强』运行时出错

### ISSUE THREAD

**Issue by xilin** [Kenshin/simpread#3618]
在显示 https://clang.llvm.org/docs/Modules.html 页面时，提示
![image](https://user-images.githubusercontent.com/543395/160342239-17ffa114-7bf6-4856-8691-aa7e92133b68.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
