### ISSUE TITLE
插件市场和稍后阅读不能正常显示

### ISSUE THREAD

**Issue by chipsflying** [Kenshin/simpread#3619]
操作系统  Windows10

浏览器版本 Chrome 版本 99.0.4844.51（正式版本） （64 位）

简悦版本 2.2.0.520

发生问题的地址 <(https://simpread.ksria.cn/plugins/)>

插件中心不能正常显示，所以也不能安装插件。

**截图**
![image](https://user-images.githubusercontent.com/102506599/160342116-0fbd946a-8d01-4abc-ba7d-5f65c77205d2.png)

另外，我觉得在稍后读的界面里也有图标没有正常显示吧？
（没看过别人截图，但是猜测不会是故意设计的结果。）

![image](https://user-images.githubusercontent.com/102506599/160343144-a6361aab-68b5-4648-8ecb-8397a0278fe9.png)

**Comment by Kenshin** [comment]
嗨，这是因 `cdnjs.cloudflare.com` 无法访问造成的问题，确保可以正常访问  `cdnjs.cloudflare.com` 。

- 扩展端暂时没法「修复」
- https://simpread.pro 相关页面均已经恢复
- https://simpread.ksria.cn/plugins/ 暂时没有恢复，稍晚些恢复

关联问题 https://github.com/Kenshin/simpread/issues/3616

**Comment by Kenshin** [comment]
嗨 https://simpread.ksria.cn/plugins/ 已经恢复

**Comment by chipsflying** [comment]
cdnjs.cloudflare.com 确实无法访问，使用图标还是不在。
但是插件市场可以正常使用了，谢谢！

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/1415#issuecomment-1080506139

试试这个方式
