### ISSUE TITLE
简悦官方模版是否有问题，反复跳登录框

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3621]
简悦官方模版是否有问题，反复跳登录框

_Originally posted by @MuMu360121 in https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2450819_

**Comment by Kenshin** [comment]
@MuMu360121

我把你的问题转移到了这里，并删除了原来的位置。

***

另外，官方模板当然不会有问题了... 也不能存在你说的问题  😂

**Comment by MuMu360121** [comment]
> 
知道问题了，貌似是notion的登录功能在我这边出了点状况，之前点击模版是先跳转登录，点击邮箱登录码点击确认之后再次跳回了登录页面，后面换了个账号测试了下解决了

**Comment by Kenshin** [comment]
okay 没问题就好。
