### ISSUE TITLE
关于知乎盐选内容的适配问题

### ISSUE THREAD

**Issue by MuMu360121** [Kenshin/simpread#3626]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **EDGE**

- 简悦版本 **2.2.0**

**请描述你的问题**

最近因看上知乎盐选上的一个内容，因此开了一个月盐选会员，但是用简悦的过程中发现图片加载效果不佳，图片下方总是显示“加载中···”字样，并且原有的标题层级机构也没有了，尝试通过添加延迟列表的方式，将测试页面完整加入，但依然存在上述问题。
测试地址：https://www.zhihu.com/market/paid_column/1126555867432284160/section/1126842676666134528
                  https://www.zhihu.com/market/paid_column/1126555867432284160/section/1126822078351028224
效果：
![2022-03-29 10 11 27](https://user-images.githubusercontent.com/1499007/160518856-12a8c024-2c06-4487-b9ed-e4776db1f7ef.jpg)
第二个测试地址页面简悦效果：
![c5fecdb5-594c-4887-bcb3-59c44d458081](https://user-images.githubusercontent.com/1499007/160519094-021b0c87-8291-4a19-b57b-c5ee0302248a.png)
原始页面效果：

![0b330b48-7953-4be1-a1b7-98f2a698cc78](https://user-images.githubusercontent.com/1499007/160519218-fbcf877d-6689-47be-a143-25f28956e279.png)

【问题】：1、图片下方有加载中字样
                  2、缺少了标题

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

我这边是没问题的，看下图

![image](https://user-images.githubusercontent.com/81074/160524110-1591e8e2-3054-4c38-a598-abee15b1a06c.png)

![image](https://user-images.githubusercontent.com/81074/160524131-7b422025-13d1-426d-aedf-54172f210066.png)

站点使用此模式识别

![image](https://user-images.githubusercontent.com/81074/160524199-7a45f0b6-1ef8-4a04-8b70-1cca7572ed3d.png)

考虑到盐选的版权属性，所以简悦是不会主动适配这种页面的，所以我关闭这个 Issues 了。

**Comment by MuMu360121** [comment]
谢谢老板百忙之中抽空回复，实际上你的第一张截图当中，自动模式下，第一第二张图是OK的，到了下方第三张图开始又开始显示了“加载中”，简悦不主动适配这种付费页面的行为我理解，如果能提供优化方案，仅用于改善个人阅读体验就更好了
![f48f7907-ccce-4ef6-9432-e06fcc8218cd](https://user-images.githubusercontent.com/1499007/160526339-3f880882-79c2-4dcc-93dd-a704bfe546a4.png)
![QQ20220329-111851](https://user-images.githubusercontent.com/1499007/160526370-5150972d-8e81-436e-a535-a9d277cdfe7e.png)

感谢

**Comment by OverflowCat** [comment]
@Kenshin 我这里智能识别不能生效，点击后没有任何反应。

@MuMu360121 使用 [SingleFile 扩展](https://github.com/gildas-lormeau/SingleFile) 将网页保存到本地后，打开离线的网页文件再进入阅读模式没有此问题。一般遇到有多余内容的情况都可以试试此方法。

![image](https://user-images.githubusercontent.com/20166026/161585077-4ed35975-d5ef-446d-ba4a-20183dceeee6.png)
