### ISSUE TITLE
插件代码段增强运行出错

### ISSUE THREAD

**Issue by DidRanyeStudyToday** [Kenshin/simpread#3627]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Chrome 99.0.4844.84**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://www.cnblogs.com/HPhone/p/3459957.html

**请描述你的问题**

开启代码段增强插件时，第一段代码完全显示不出来，且全页面代码高亮失效。关闭插件后是正常的。

**截图**

![image](https://user-images.githubusercontent.com/51332690/160527472-67d23faa-bd38-4666-b5a6-6ef2a0a24ed2.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

你可以试试暂时将此插件关闭，看看能否解决？（除没有代码高亮外）
