### ISSUE TITLE
https://index.pmthinking.com/ 这个网页是不支持么？

### ISSUE THREAD

**Issue by marshloloXX** [Kenshin/simpread#3628]
加了白名单也不支持
用阅读模式打开后 无法阅读
当时就是为了看这个产品沉思录，买的简悦高级版。但是hao xai好像都进不去。。页面里面的其他文章链接也无法正常使用，鼠标也无法拖动，页面无法上下移动，就是卡在这个界面
<img width="1356" alt="截屏2022-03-29 下午2 10 16" src="https://user-images.githubusercontent.com/101887751/160544812-f39a8cb6-ac76-4ffd-965a-f13de48e2a68.png">
用

**Comment by marshloloXX** [comment]
当时就是为了看这个产品沉思录，买的简悦高级版。但是hao xai好像都进不去。。页面里面的其他文章链接也无法正常使用
<img width="1203" alt="截屏2022-03-29 下午2 09 25" src="https://user-images.githubusercontent.com/101887751/160544709-cd20b352-e21e-4c09-939e-f190463eb9e0.png">
，

**Comment by Kenshin** [comment]
嗨，应该可以的，请给个具体 URL

**Comment by Kenshin** [comment]
更正下：

准确的说，这个站是 Notion，简悦对[ Notion 是支持](https://github.com/Kenshin/simpread/discussions/2106) 的，但支持的 Block 有限，所以并不是每个页面都能完美使用。

这种带有版权方案的页面，简悦一般不会主动适配的。

**Comment by marshloloXX** [comment]
> 更正下：
> 
> 准确的说，这个站是 Notion，简悦对[ Notion 是支持](https://github.com/Kenshin/simpread/discussions/2106) 的，但支持的 Block 有限，所以并不是每个页面都能完美使用。
> 
> 这种带有版权方案的页面，简悦一般不会主动适配的。

好的谢谢～

**Comment by Kenshin** [comment]
PS：我也是产品沉思录的用户，你可以这样试试

比如访问这个页面 https://index.pmthinking.com/4d92410d370849c1be0bde496b6d60bb

使用此方式可以手动进入阅读模式

![image](https://user-images.githubusercontent.com/81074/160549447-7509a39e-cebc-43bd-bb64-8e1bfece9eba.png)

进入阅读模式的效果

![image](https://user-images.githubusercontent.com/81074/160549419-5c997063-a765-4efe-8582-ced321a6a46e.png)

注意：只有页面结构清晰的才行，想下面的结构就没法使用

![image](https://user-images.githubusercontent.com/81074/160549844-e714bf18-33b8-41d6-96f7-9d456332c20e.png)

![image](https://user-images.githubusercontent.com/81074/160549958-ba327d4e-802d-451e-ba58-9eaf88498b29.png)

**Comment by marshloloXX** [comment]
> PS：我也是产品沉思录的用户，你可以这样试试
> 
> 比如访问这个页面 https://index.pmthinking.com/4d92410d370849c1be0bde496b6d60bb
> 
> 使用此方式可以手动进入阅读模式
> 
> ![image](https://user-images.githubusercontent.com/81074/160549447-7509a39e-cebc-43bd-bb64-8e1bfece9eba.png)
> 
> 进入阅读模式的效果
> 
> ![image](https://user-images.githubusercontent.com/81074/160549419-5c997063-a765-4efe-8582-ced321a6a46e.png)
> 
> 注意：只有页面结构清晰的才行，想下面的结构就没法使用
> 
> ![image](https://user-images.githubusercontent.com/81074/160549844-e714bf18-33b8-41d6-96f7-9d456332c20e.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/160549958-ba327d4e-802d-451e-ba58-9eaf88498b29.png)

好的谢谢已经尝试成功～ 感谢

**Comment by Kenshin** [comment]
> 好的谢谢已经尝试成功～ 感谢

小事情，但还是那句话，这种类型的页面是不会主动适配的。 😁 

***

趁热打铁，觉得简悦帮到你的话 👉  [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

这是对简悦最好的帮助。

**Comment by marshloloXX** [comment]
> > 好的谢谢已经尝试成功～ 感谢
> 
> 小事情，但还是那句话，这种类型的页面是不会主动适配的。 😁
> 
> 趁热打铁，觉得简悦帮到你的话 👉 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价
> 
> 这是对简悦最好的帮助。

已五星好评！

**Comment by Kenshin** [comment]
哈哈，谢谢~
