### ISSUE TITLE
快捷键及默认发送临时页面到evernote

### ISSUE THREAD

**Issue by TheKiteRunning** [Kenshin/simpread#363]
翻看wiki好像没有看到临时页面的快捷键，不知能否考虑设置，谢谢。

能否让用户自定义不同类型网站的默认动作逻辑呢，比如一般如果我在简悦阅读视图下发送到evernote时，更愿意剪裁临时页面。

再次感谢

**Comment by Kenshin** [comment]
确实忘记加它了...   😂 

`用户自定义不同类型网站的默认动作逻辑`

没有太理解你的意思，能否详细说明。

**Comment by TheKiteRunning** [comment]
比如我用简悦看一个stackforum的页面，如果单纯浏览的话，没有必要打开临时页面的，毕竟需要鼠标点击+延迟3s。换言之，如果我打开了临时页面，肯定对应了下一个动作，对我来说，这个动作是发送到印象笔记或者kindle。然而，现有的转成临时页面之后，需要再次激活简悦插件，才能完成后续动作。

**Comment by Kenshin** [comment]
emmm
意思是：进入临时页面后也自动进入阅读模式？

`临时阅读页面` 一般对应了某些无法使用的功能，比如： Evernote 的剪裁、或简悦暂时未支持的服务，如：有道云笔记、为知 等。

**Comment by TheKiteRunning** [comment]
对，至少能够直接调用阅读模式下可配套的那些功能。比如我打开临时阅读模式的目的是evernote的剪藏，那么这时候仍然希望用阅读模式下的快捷键自动发送过去，而不是又切换到everntoe的剪藏插件。

**Comment by Kenshin** [comment]
可以考虑~ 谢谢建议！

**Comment by TheKiteRunning** [comment]
感谢更新，不过发送到evernote仍然失败，出错后导出markdown也是：http://ksria.com/simpread/changelog.html#1.1.2

**Comment by Kenshin** [comment]
@TheKiteRunning 
哪个 URL ？

**Comment by TheKiteRunning** [comment]
@Kenshin 基本上没有成功的网页～比如

http://ksria.com/simpread/changelog.html#1.1.2

https://matplotlib.org/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py

备注：

我装了一些简悦的插件：

![image](https://user-images.githubusercontent.com/24802332/45015485-761aa800-b054-11e8-982e-332798d0f638.png)

浏览器上启用了几个插件，包括一个广告拦截，油猴和stylish：
![image](https://user-images.githubusercontent.com/24802332/45015512-90ed1c80-b054-11e8-8417-d11d1e813b9d.png)

**Comment by Kenshin** [comment]
我测了 https://matplotlib.org/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py

在转换为 Markdown 可以保存成功，下图是印象笔记的内容：

![2018-09-04_151240](https://user-images.githubusercontent.com/81074/45015740-33a59b00-b055-11e8-92d6-fadda291c177.png)

***

你选择的页面其实太复杂了，不太适合 印象笔记 ... 你可以试试常规一些的。

**Comment by TheKiteRunning** [comment]
哈哈，简单的网页好像也不行，我把浏览器和简悦的所有插件都关了，还是不行：

![image](https://user-images.githubusercontent.com/24802332/45017276-c9dbc000-b059-11e8-9d47-69128bef1ff0.png)

浏览器版本：Version 3.5.3.50 (Official Build) (32-bit) (**Chromium** 67.0.3396.99)。测试的链接包括：
- https://matplotlib.org/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py
- https://zhuanlan.zhihu.com/p/22737822
- https://blog.csdn.net/watfe/article/details/53420789
- https://www.jianshu.com/p/ccd4596c04aa

**Comment by Kenshin** [comment]
@TheKiteRunning 

很奇怪，估计是你的个例，因为我测试了发到这里的全部关于 Evertnote 解析失败的 url。

你试着重新授权 印象笔记 看看。

还有一个方式也可以方便的实现 → https://github.com/Kenshin/simpread/wiki//授权服务#临时页面 
这样保存到 印象笔记的内容 都是整理后的。

**Comment by TheKiteRunning** [comment]
哈哈，重新授权仍然不行，第二种可以～

**Comment by Kenshin** [comment]
@TheKiteRunning 
好奇怪的问题... 你可以这么做，导出配置 → 清除全部数据 → 导入配置。
