### ISSUE TITLE
少数派页面，一直提示：配置文件已更新，刷新当前页面才能生效

### ISSUE THREAD

**Issue by marshloloXX** [Kenshin/simpread#3630]
mac OS
chrome 99.0.4844.84（正式版本） (x86_64)
简悦版本 2.0

地址： https://sspai.com/post/72022

问题： 无法进入阅读模式，一直弹窗：“配置文件已更新，刷新当前页面才能生效” 。
然后我刷新页面  。 还是继续提示继续弹窗

<img width="488" alt="截屏2022-03-29 下午3 30 01" src="https://user-images.githubusercontent.com/101887751/160557537-cee62618-d403-40c2-b502-675a441f399b.png">

**Comment by Kenshin** [comment]
同一个 URL 多开了，重启浏览器就行了。

**Comment by marshloloXX** [comment]
> 同一个 URL 多开了，重启浏览器就行了。

厉害了！谢谢大佬！

**Comment by Kenshin** [comment]
> 厉害了！谢谢大佬！

哈哈，太客气了~ 小事情而已。

***

不过，趁热打铁P  👉 请在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

就更完美了~ 🙏  💪  😏
