### ISSUE TITLE
通过快捷键无法添加页面到稍后读

### ISSUE THREAD

**Issue by Shawnli1874** [Kenshin/simpread#3632]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
- MacOS 12.3

- 浏览器版本 **e.g. Chrome 78.0.3904.108**
- 99.0.4844.74

- 简悦版本 **2.0.0**
- 2.2.0.520

- 发生问题的地址 <请填写你的地址l>
- 所有

**请描述你的问题**
浏览器已设置「加入当前页面到稍后读」的快捷键，但按下快捷键后什么都没发生，打开稍后读里面也没有
但是「打开稍后读」的快捷键是有用的，只是添加页面的没有用

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35032661/160571289-36bbe0d2-8850-47ff-bf32-a982a4204bac.png">

**Comment by Shawnli1874** [comment]
重启浏览器后生效了 🤦‍♂️

**Comment by Kenshin** [comment]
哈哈，搞定就好。

不过，留意这里有个 Bug https://github.com/Kenshin/simpread/issues/3601
