### ISSUE TITLE
如何在正常网页右键，快速保存到notion中？

### ISSUE THREAD

**Issue by difeiqi** [Kenshin/simpread#3633]
现在需要先进入简悦页面，再通过功能键保存到notion，
能否在下的邮件菜单中，就直接把页面存到notion呢？
![快速进notion](https://user-images.githubusercontent.com/101982253/160628013-616c7f9d-4c06-4710-9281-7e40ef4c5847.png)

**Comment by Kenshin** [comment]
哈哈，并没有此功能。

**Comment by Kenshin** [comment]
这里有一些简悦使用 Notion 的方式，你可以看看 https://github.com/Kenshin/simpread/discussions/2586
