### ISSUE TITLE
定制化导出到Obsidian的标注，内外部链接无法正确跳转

### ISSUE THREAD

**Issue by Lynyh22** [Kenshin/simpread#3634]
https://github.com/Kenshin/simpread/issues/3096#issue-1060785112

之前已配置成功，开放平台和API都已开通，所有配置都没动过，现在在Obsidian里点内部链接和外部链接分别显示以下页面
![微信截图_20220330102215](https://user-images.githubusercontent.com/94436542/160738035-741b8ee2-fc0f-4a5b-97d3-30325cd2a8c8.png)
![微信截图_20220330102228](https://user-images.githubusercontent.com/94436542/160738059-2fd7e6fe-e750-4831-b9a5-8e21cc97f1d0.png)

求指导！

**Comment by Kenshin** [comment]
把 `output` 的内容仅保留 `3-xxxx.html` 后再试试

**Comment by Lynyh22** [comment]
> 把 `output` 的内容仅保留 `3-xxxx.html` 后再试试

![微信截图_20220330143522](https://user-images.githubusercontent.com/94436542/160766825-27c8e930-8fd7-4bb5-af1c-0e2dd7008f18.png)
请问在哪里修改？

**Comment by Kenshin** [comment]
我的意思是：

仅保留 `output` 文件夹的中 `3-xxxx.html `其它文件都转移到其它地方后再试试

**Comment by Lynyh22** [comment]
尝试了你说的方法，还是不行。
我给Obsidian新建了一个本地的库，同步助手也改了，现在库里只有这一个文件
![微信截图_20220330160937](https://user-images.githubusercontent.com/94436542/160783494-541c59d9-99f7-491c-8c86-af999c412cd1.png)
在Obsidian点内外部链接依旧显示上面截图的内容。

**Comment by Lynyh22** [comment]
我尝试了你说的方法，新建了一个output路径，让里面只有一个文件，还是不行。

**Comment by Lynyh22** [comment]
我尝试了一下把Obsidian的库建在坚果云的Simpread-output下，点击内部链接不会出现https://github.com/Kenshin/simpread/issues/3634#issue-1185764432截图那样了，但是是空白页，点击外部链接依旧显示截图的内容。
刚刚确认了一下，https://simpread.pro/@lynyh22/reading/ 是可以正常访问的

**Comment by Kenshin** [comment]
也就是说，外部链接没问题了？内部链接呢？

**Comment by Lynyh22** [comment]
😂并不是，依然都有问题，内部链接现在是无任何内容的页面，连错误信息也没有，外部链接还是404。

**Comment by Kenshin** [comment]
按照 [建立知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 对比下你自己的。

不可能出现问题的。

**Comment by Lynyh22** [comment]
我对照过了。
这个是我的output文件夹
![微信截图_20220330192924](https://user-images.githubusercontent.com/94436542/160824805-4f8bced7-2fd9-4e5a-a88b-a2f362e63995.png)
我对照了文章里的这一步
![微信截图_20220330192936](https://user-images.githubusercontent.com/94436542/160824872-8feb2d89-ba87-40b3-b4e1-772e73aaf93a.png)
这是我打开的http://localhost:7026/reading/3
![微信截图_20220330192955](https://user-images.githubusercontent.com/94436542/160824999-310867f2-4e45-4ce2-9651-3c3d2f5276b9.png)
yi一片空白

**Comment by Kenshin** [comment]
emmm 太奇怪了，试试

1. 随便打开 https://sspai.com/post/69972 进入阅读模式然后加入稍后读，生成一个本地文件，假设名字叫 `4-xxx.html`

> 在一个没有安装简悦的浏览器，并在隐身模式下

2. 访问 http://localhost:7026/reading/4
3. 访问 http://localhost:7026/reading/index

看看如何。

**Comment by Lynyh22** [comment]
出现了个新问题。。。进入阅读模式然后加入稍后图，自动化没有生成本地文件

**Comment by Kenshin** [comment]
> 进入阅读模式然后加入稍后读，自动化没有生成本地文件

快捷键 `d d`

还有之前的问题解决了？

**Comment by Lynyh22** [comment]
没有，全都没解决。

**Comment by Kenshin** [comment]
> 没有，全都没解决。

把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3634

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
