### ISSUE TITLE
简悦 · 同步助手 小二 无法使用

### ISSUE THREAD

**Issue by cdchs99** [Kenshin/simpread#3636]
## 问题
简悦 · 同步助手 小二 无论发送指令还是url都收不到反馈
![IMG_5966](https://user-images.githubusercontent.com/47968720/160966437-9b21288c-a9af-40d8-a670-d506c62b4873.JPEG)

## 描述
#2919 这里没有包含我的问题
我使用坚果云进行同步，当我发送链接给小二时，坚果云没有产生任何的更新或者冲突
上个礼拜，还能正常使用

## 环境
ios 15.4
telegram 8.6

**Comment by Kenshin** [comment]
哈哈，抱歉，这几个月的流量超的太狠了，明天自动恢复正常。

**Comment by Kenshin** [comment]
嗨，Telegram bot 已经恢复了~

**Comment by zhaoxian-afra** [comment]
@Kenshin 现在bot又用不了了。无论发送什么都没有回应。
