### ISSUE TITLE
导出为离线html时，导出文件名的bug

### ISSUE THREAD

**Issue by HWZen** [Kenshin/simpread#3639]
- 操作系统 **Windows**

- 浏览器版本 **Eage 99.0.1150.55**

- 简悦版本 **2.2.0**

- 发生问题的地址 <[C++11\14\17\20新特性介绍](https://www.jianshu.com/p/8c4952e9edec)>

**在导出为离线html时，若导出的网页标题包含反斜杠``\``，会导致导出的文件名不完整，只包含最后一个反斜杠后的内容**

**截图**
![image](https://user-images.githubusercontent.com/46065109/161045651-99026e40-05e8-4e6c-9a19-cb9fc6e54dc2.png)

**Comment by Kenshin** [comment]
嗨，试试这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
