### ISSUE TITLE
代码字体问题

### ISSUE THREAD

**Issue by briarbear** [Kenshin/simpread#364]
感觉很多网站的代码字体显示太小了

**Comment by Kenshin** [comment]
你可以使用 [自定义样式](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决它。  ☺

**Comment by zld** [comment]
代码字体大小自定义后不生效的问题应该已经好久了，第一次用简阅时就遇到了，今天又试了下还是不行。
SimpRead Version: 1.1.2
Chrome Version:  69.0.3497.81

只在【自定义样式】预览页生效，在简书等实际用到的地方还是很小
![image](https://user-images.githubusercontent.com/2616502/45146832-2bd12c80-b1f6-11e8-9b98-5f533d772286.png)
![image](https://user-images.githubusercontent.com/2616502/45147045-a601b100-b1f6-11e8-8fa9-a53748c93ae1.png)

不善前端，没法调试提PR，抱歉啦
感谢SimpRead这个项目，希望越做越好~

**Comment by Kenshin** [comment]
@zld 
告诉我发生问题的 URL 现在已经是 1.1.2 版本了，一般情况下是可以彻底解决的。

**Comment by zld** [comment]
@Kenshin 
我这边简书的任何文章都一样，比如这个 [https://www.jianshu.com/p/3ab6b26628a8](https://www.jianshu.com/p/3ab6b26628a8)
我自定义代码字号14后，刷新页面重新使用依然是12号字。Styles里可以看到我自定义的字号是失效状态

**Comment by Kenshin** [comment]
@zld 
你可以在 font-size 后面加上 `!important`，强制设置对应的大小。
另外，请使用 CSS3 font-size 值，例如： `14px!important` 等，而非数字。

**Comment by zld** [comment]
@Kenshin 
非常感谢，可以了，是我没写px引起的。
