### ISSUE TITLE
简悦同步助手无法开机自启+提示系统错误问题

### ISSUE THREAD

**Issue by zhen03** [Kenshin/simpread#3642]
（首先抱歉我不太会用github，不知道这么发布在这儿对不对……如果有错误请原谅并纠正，谢谢！）
我的简悦同步助手打开了开机自启、并且按照自己需求同步logseq的教程设置完毕了，用起来也没有什么问题；但是我每次打开电脑都得手动点开同步助手不可，而且这两次开机之后都自动跳出了下方这个系统错误提示对话框，不知道二者之间有没有关联？
![20220401_091918](https://user-images.githubusercontent.com/102536517/161183957-3a17e164-22f9-4877-bcdf-3a428c52bea0.png)
（系统：win10；浏览器：Chrome）

**Comment by Kenshin** [comment]
> 首先抱歉我不太会用github，不知道这么发布在这儿对不对……如果有错误请原谅并纠正，谢谢！

哈，发到这里是正确的。

关于 Windows 开机自启的方案，可以试试 https://github.com/Kenshin/simpread/discussions/2011 解决办法。

**Comment by Kenshin** [comment]
至于截图的问题，确实也有用户反馈过，只是个别。

你看看我刚才提到的方式能否还会出现此问题？

**Comment by zhen03** [comment]
谢谢！按您说的方法操作完毕之后今天再开机自启就成功了、并且也没有再跳这个提示啦，开心~
以及简悦真的太好用了（美貌与实力兼具的那种好用），感谢作者大大的开发——！

**Comment by Kenshin** [comment]
哈哈，搞定就好~

觉得简悦不错的话，请帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价~

 💪  🙏 

另外，最近 Chrome webstore 一直在抽风（删我的评论），我正在跟他们联系，所以能否当评价完之后能否把你的评论截图给我（删除掉 ID）我会跟他们反馈这个问题。

**Comment by zhen03** [comment]
OK！应该的哈哈哈，截图如下↓
![image](https://user-images.githubusercontent.com/102536517/161363689-bacffbf6-eeb4-4635-8701-5e1cbfa0c184.png)
删评论可真是……，希望chrome那边可以尽快解决_(:3」∠)_

**Comment by Kenshin** [comment]
嗨，已收到你的截图，为免 ID 泄漏，我已删除了相关内容，请放心。

🙏
