### ISSUE TITLE
CSDN文章PDF以及MD导出失败

### ISSUE THREAD

**Issue by linyiverycool** [Kenshin/simpread#3644]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 
Windows 11 专业版

- 浏览器版本
100.0.4896.60（正式版本） （64 位）

- 简悦版本 ****
2.2.0

- 发生问题的地址 <请填写你的地址l>
https://blog.csdn.net/firestarway/article/details/39698835

**请描述你的问题**
一些网页的文章导出PDF和MD出错。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/45316289/161200919-e4bc8868-6e48-4735-927d-54d6f6664ea6.png)
![image](https://user-images.githubusercontent.com/45316289/161201003-339e85f4-4be7-41df-9c0c-11cd3c3689f0.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，我没有你遇到的问题，请问是使用了同步助手吗？

如果是的话，建议安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决。

[STC 8051 单片机扩展 SRAM 介绍、使用以及配置_YaHa201286 的博客 - CSDN 博客_单片机 sram.sram.pdf](https://github.com/Kenshin/simpread/files/8395148/STC.8051.SRAM._YaHa201286.-.CSDN._.sram.sram.pdf)

[STC 8051 单片机扩展 SRAM 介绍、使用以及配置_YaHa201286 的博客 - CSDN 博客_单片机 sram.txt](https://github.com/Kenshin/simpread/files/8395152/STC.8051.SRAM._YaHa201286.-.CSDN._.sram.txt)

**Comment by linyiverycool** [comment]
![image](https://user-images.githubusercontent.com/45316289/161207509-96327ad8-9a91-4529-a5bf-b54b70b0dd50.png)
你好，安装插件之后仍然是这样。
![image](https://user-images.githubusercontent.com/45316289/161208113-de7dc09f-2910-46f1-bfa3-af95026a7359.png)

**Comment by Kenshin** [comment]
emmm

你的这个截图有点问题... 你是什么版本的简悦？另外使用了同步助手的增强导出？

![image](https://user-images.githubusercontent.com/81074/161215291-e9f76613-b984-4d67-85b0-f16fad6d3670.png)

**Comment by linyiverycool** [comment]
![image](https://user-images.githubusercontent.com/45316289/161359963-599f44a3-d2f7-4cc3-baf0-034d8f26bd8a.png)
使用了同步助手以及增强导出功能

**Comment by Kenshin** [comment]
1. 版本应该没问题，如果是从 Chrome or Edge 应用商店下载的话。

2. [这个截图](https://user-images.githubusercontent.com/45316289/161201003-339e85f4-4be7-41df-9c0c-11cd3c3689f0.png) 提示你并没有使用增强导出，但你却说使用了增强导出。

3. 确认你的增强导出跟 [教程](https://kb.simpread.pro/#/page/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA) 是否一致？

4. 使用其它页面 e.g. https://sspai.com/post/71739 看看是否还存在这个问题？

**Comment by linyiverycool** [comment]
你好，我已经解决了。我重新安装了该软件，将同步助手的路径修改了一下，已经可以正常运行。谢谢。

**Comment by Kenshin** [comment]
> 你好，我已经解决了。我重新安装了该软件，将同步助手的路径修改了一下，已经可以正常运行。谢谢。

哈哈，搞定就好~

PS：如果觉得简悦不错的话，请在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价，这是对简悦最好的帮助。 🙏  💪  😏
