### ISSUE TITLE
能否添加一个<导出文章到思源笔记>的功能

### ISSUE THREAD

**Issue by linyiverycool** [Kenshin/simpread#3645]
你好，能否添加一个<导出文章到思源笔记>的功能嘛。辛苦您了。

**Comment by Kenshin** [comment]
嗨，你可以使用将 Markdown 复制剪切板后支持任意双链笔记。

![image](https://user-images.githubusercontent.com/81074/161206606-9c527441-e114-4399-9296-2d2dd4d9c1f1.png)

**Comment by Kenshin** [comment]
![Siyuan](https://github.com/Kenshin/simpread/assets/81074/a8f839b4-90e5-4fbe-8ae9-da73b48c888c)

嗨，各位。

导入到思源笔记的插件已发布。

### 下载地址

https://simpread.ksria.cn/plugins/details/XxuF7bPTbo

### 功能

- 定制思源笔记地址（适用于 Docker 用户）

- 新建笔记本（留空则新建 SimpRead 名称的笔记本）

- 查看并选择任意笔记本
   
- 自定义导入路径

- [思源图库](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- [assets 定制](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025979) 包括：`{{title}}` 与 `{{date}}`

- [将阅读模式的图片转换为思源图床](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- 导入全文到思源笔记

- 快捷键

- [自动化](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025982)

- 在导入前可选择任意笔记本或路径

### 如何安装

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

### 注意事项

如果你使用了 Docker 版，并且域名不是 `localhost` 的话，可能会有问题。


***

我关闭这个 issues 了，但有任何使用疑问均可在 https://github.com/Kenshin/simpread/issues/5555 继续再此讨论。 😄

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
