### ISSUE TITLE
好久没更新了

### ISSUE THREAD

**Issue by heimi98** [Kenshin/simpread#3646]
简悦快一年没更新了，怎么回事？

**Comment by Kenshin** [comment]
嗨，并没有你说的问题。

1. 2021年10月份更新了一次 API 2.0
2. 简悦每周都有更新，建议订阅 https://simpread.pro/subscribe 得到最新的简悦信息。
3. 每天我都会处理 nnn 个来自 Github Issues 的内容。

或者严格意义上说，简悦并不是一个具体的工具，而是一种生产力工具流程。

至于更新频率，可以看

1. https://www.zhihu.com/column/kenshin
2. https://rss.simpread.pro/feed

或者看看这个截图也行

![image](https://user-images.githubusercontent.com/81074/161221573-df6e4c9b-0605-4606-9dd0-a58781fb303a.png)
