### ISSUE TITLE
字体无法更改

### ISSUE THREAD

**Issue by mochen001** [Kenshin/simpread#3649]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows**

- 浏览器版本 **版本 100.0.4896.60（正式版本） （64 位）**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <[请填写你的地址l](https://www.huxiu.com/article/517739.html)>

**字体无法改变**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![snipaste_20220402_092149](https://user-images.githubusercontent.com/37462792/161360446-609d4c93-bb1e-44ba-94ab-0429abf76597.png)
![snipaste_20220402_092216](https://user-images.githubusercontent.com/37462792/161360451-25aa969f-1aad-4407-b417-1ea151d80f4c.png)

改变了两种字体都没变化，浏览器扩展只开了这一个，其他的都关闭了，不知道还有啥影响
> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，关于字体无法更改的一些说明 https://github.com/Kenshin/simpread/discussions/1864

另外，如果你喜欢折腾字体的话，可以试试 https://github.com/Kenshin/simpread/discussions/2519 提供的方式。

关于更改字体 [更多的介绍](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3Atheme+)
