### ISSUE TITLE
新站适配：财新网

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3650]
首先[pocket](https://getpocket.com/my-list)有问题
![image](https://user-images.githubusercontent.com/13709836/161255340-a99b10b5-5cd2-46a1-a4d5-f10a922b204d.png)

另外，想要自己改进一下财新网的规则，但是遇到本问题，即**智能识别优先级高于自定义规则**, for example: https://pmi.caixin.com/2022-04-01/101864263.html

![image](https://user-images.githubusercontent.com/13709836/161255168-c72f7ee3-f23d-4db1-b58b-f9c77821b057.png)

_Originally posted by @AuroraDysis in https://github.com/Kenshin/simpread/issues/2470#issuecomment-1085788740_

**Comment by Kenshin** [comment]
@AuroraDysis

嗨，我帮你重新建立了一个 Issues 并删除了原来的内容，因为跟那个 Issues 无关。

***

> Pocket 的问题

可以适配，细节看这里 https://github.com/Kenshin/simpread/discussions/3502

> 财新网的问题

这个页面需要手动适配，适配后会在这里通知你。

***

建议订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候有新站适配的话，我会通过这个渠道通知。

**Comment by AuroraDysis** [comment]
@Kenshin 

> Pocket 的问题
> 可以适配，细节看这里 https://github.com/Kenshin/simpread/discussions/3502

非常感谢

> 财新网的问题
> 这个页面需要手动适配，适配后会在这里通知你。

https://github.com/Kenshin/simpread/blob/a2a829851731bab28ef4eeac550eafe943f732ad/src/website_list.json#L2031-L2040

可问题是，财新网已经存在在官方源里面了

<img width="324" alt="image" src="https://user-images.githubusercontent.com/13709836/161375896-bae19998-eb0c-4708-92a4-fa0611030b2a.png">

我自己也写了一个第三方规则导入，想要改进，这个智能识别的意思应该是均未生效

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/blob/a2a829851731bab28ef4eeac550eafe943f732ad/src/website_list.json#L2033

改为

`http*://*.caixin.com/*/*.html`

**Comment by AuroraDysis** [comment]
确实是这个问题，非常感谢

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 issues 了~

**Comment by julian20220130** [comment]
报告一个与财新相关的（可能是）bug
https://international.caixin.com/2024-10-30/102251355.html
比如这篇文章，在我这边是无法显示文中任何图片的。
此外，财新的文章在进入阅读模式后，都会被系统增加一句话：
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/f6e8366f-51d5-4bc0-bc5d-4e8fc8e8adb5">
此外，在财新中，有些页面的文字是无法选中复制的，例如
https://weekly.caixin.com/2023-03-11/102007110.html?sourceEntityId=102243720
那么这篇文章在进入阅读模式后同样无法选中、复制和标注。不知道能否通过技术手段解决。
谢谢

**Comment by Kenshin** [comment]
@julian20220130 

嗨，谢谢反馈~

> 财新的文章在进入阅读模式后，都会被系统增加一句话：

是下图原因造成的。

<img width="1375" alt="image" src="https://github.com/user-attachments/assets/72aef0cf-5f60-46a1-9df4-b032a96ccde2">

> 比如这篇文章，在我这边是无法显示文中任何图片的

适配相关问题，因为 **财新网** 的结构改变造成的，可以重新适配，但有个问题，我没有帐号，所以... 😂

如果你有帐号的话，可以告诉我，看看能否解决。

> 无法复制的问题

理论上可以解决，但简悦不会干扰任何网站的规则... 但并不耽误导出等操作。（如果是因为无法标注的话，可以先加稍后读解决）

不过，应该有第三方工具 e.g. 油猴脚本来解决无法复制的问题。

**Comment by julian20220130** [comment]
谢谢。账号我私信你，非常感谢能够重新适配！
无法复制的问题，装了一个脚本试了一下没有解决，但用超级复制super copy这个浏览器插件是能够破解的，但或许是改变了网站规则，破解后的网页进入阅读模式后依旧无法标注和复制。但无论破解与否，导出都是不影响的，所以问题也不大。

**Comment by Kenshin** [comment]
> 账号我私信你

Cool~ 可以 [进群](https://t.me/simpreadgroup) 然后私聊我，或者 Email （ 打开 https://github.com/kenshin 左侧下方）找到地址。

Email 方式的话，发送我请告诉我~

**Comment by julian20220130** [comment]
已发送Email

**Comment by Kenshin** [comment]
okay 收到 👍

最迟明天解决~

**Comment by Kenshin** [comment]
@julian20220130 

我适配了下~

选项页 → 站点管理 → 更新主适配源

<img width="930" alt="image" src="https://github.com/user-attachments/assets/ab09163e-b00d-4d9e-922f-8cc9d2c29eea">

因为它的订阅才能看到，为了获得更好的效果，需要将 `caixin.com` 加入延迟加载列表

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/754310e5-2186-4303-9fe0-20b5357ccf74">

最后重启浏览器，然后手动进入阅读模式。

有任何问题再讨论~
