### ISSUE TITLE
导入到滴答清单

### ISSUE THREAD

**Issue by Green-Danny** [Kenshin/simpread#3651]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

-建议：能否在动作项中添加 " 保存到滴答清单 "

**Comment by Kenshin** [comment]
okay 可以考虑

导入到滴答的只能是链接

请问，你这么做的目的是什么？通过滴答来做 Todo 吗？还是？想了解下。

**Comment by Green-Danny** [comment]
我是看到web clipper插件可以保存文章到滴答清单，想着也在简悦中实现这一目的，如果只是链接的话，那确实意义不是很大

**Comment by Kenshin** [comment]
哈哈，导入功能并不需要接入每个 App 的，这显然没有意义。

如果你有使用 GTD （滴答）来管理稍后读，约束自己的稍后读不要越积越多习惯，这或许才是导入到滴答的意义。

**Comment by Cleverambo** [comment]
同有这个需求。我补充一下，滴答清单的每一个任务都可以在后面附加md，功能其实相当完善：
![C9177CA5-0790-4BEE-B696-C9A49AB1EB40](https://user-images.githubusercontent.com/36615067/174999989-a0c75fd2-ce61-4444-9ffc-1bb1c354ce68.png)
Green-Danny提到的[Web Clipper](https://www.bing.com/fd/ls/GLinkPing.aspx?IG=CE546155D36F4645BE9D0166B794D4C6&&ID=SERP,5131.1&SUIH=IlTH8HMmfRtnMF5o-VukYw&redir=aHR0cHM6Ly9jaHJvbWUuZ29vZ2xlLmNvbS93ZWJzdG9yZS9kZXRhaWwvd2ViLWNsaXBwZXIvbWhmYm9maW9rbXBwZ2RsaWFrbWluYmdkZ2NtYmhiYWM)确实可以实现保存全文到滴答清单，美中不足的是我得装两个插件，而且它的文章解析稍微弱了一点，经常需要手动点选。
所以麻烦开发者再考虑一下下_(:з」∠)_

**Comment by Cleverambo** [comment]
> 

我的意思是，不要被「清单」这个名字限制住了，其实它在功能性上完全可以作为md编辑器使用，既然支持Bear，那么支持其他md编辑器也很自然吧。
除此之外，定时提醒也和稍后阅读很很配，还能[配合艾宾浩斯遗忘曲线使用](https://sspai.com/post/59522#!)。
不过具体有多少人会这样用滴答清单，我不清楚，所以仅仅作为一个建议

**Comment by Kenshin** [comment]
@Cleverambo 

我之前测试过（导入滴答）这个功能，但没有发布，我考虑下你提到的思路。

PS：我是滴答的老用户。 😂

**Comment by Kenshin** [comment]
@Cleverambo

我知道滴答可以导入 md，我的意思是除了导入外，能否结合滴答的 GTD 特性研究出一套方案，这样感觉更好些。

**Comment by xulei-shl** [comment]
> 哈哈，导入功能并不需要接入每个 App 的，这显然没有意义。
> 
> 如果你有使用 GTD （滴答）来管理稍后读，约束自己的稍后读不要越积越多习惯，这或许才是导入到滴答的意义。

不知道最新版的简悦是否支持，并没有搜索到相关教程。🤝🏻
使用场景：阅读模式下，加入稍后读，自动创建滴答清单任务（类似todoist的自动化方案）

**Comment by Kenshin** [comment]
@xulei-shl 

下周会有惊喜。😄

**Comment by Kenshin** [comment]
嗨，各位。

导入到滴答清单的插件已经发布了，详细说明 https://github.com/Kenshin/simpread/discussions/4281

我关闭这个 Issues 了，如果在使用时有任何疑问，可随时在这里跟我讨论。
