### ISSUE TITLE
插件造成BBC中文网文章页面内容无法加载

### ISSUE THREAD

**Issue by baldachin** [Kenshin/simpread#3652]
如题，BBC中文网所有文章点开后会出现短暂可以看到内容，之后完全空白的情况。
经过排查发现此问题由简阅插件引起，关闭插件后可正常加载，开启插件即无法加载（Chrome和Edge均存在此问题）。
例如此地址 https://www.bbc.com/zhongwen/simp/world-60950216
![Snipaste_2022-04-02_12-13-26](https://user-images.githubusercontent.com/1262195/161365960-08ecff64-58ad-423b-9363-fc91352dd90c.png)

**Comment by Kenshin** [comment]
嗨，可以这样解决

请打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)

**Comment by baldachin** [comment]
确认有效

**Comment by Kenshin** [comment]
哈哈，当然是没问题的了。
