### ISSUE TITLE
新站适配：微软文档

### ISSUE THREAD

**Issue by tianhuahao** [Kenshin/simpread#3653]
**从原网页转换到阅读模式**

- 操作系统 **Win64**

- 浏览器版本 **Microsoft Edge版本 99.0.1150.55 (正式版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://docs.microsoft.com/zh-cn/visualstudio/ide/customizing-window-layouts-in-visual-studio?view=vs-2022>

**重要内容丢失**

![image](https://user-images.githubusercontent.com/102142500/161366014-354fd17f-96e0-4465-8f1e-b0b7709714bb.png)

**Comment by Kenshin** [comment]
哈哈，标题还夸张了，吓我一跳，这个站适配后就没问题了。  😂 

适配后我会通知你，也可订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会官方渠道通知。

**Comment by tianhuahao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月2日(星期六) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 新站适配：微软文档 (Issue #3653)





 
哈哈，标题还夸张了，吓我一跳，这个站适配后就没问题了。  😂
 
适配后我会通知你，也可订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会官方渠道通知。
 
—哦，抱歉，我是新手，不太熟悉这些操作

**Comment by Kenshin** [comment]
> 哦，抱歉，我是新手，不太熟悉这些操作

小事情~

**Comment by Kenshin** [comment]
嗨，这个站已经更新，具体规则 [请看这里](https://github.com/Kenshin/simpread/discussions/5418#discussioncomment-5495675)

**Comment by tianhuahao** [comment]
哇，做的好

**Comment by Kenshin** [comment]
解决你的问题就好。
