### ISSUE TITLE
medium 文章进入阅读模式，代码部分丢失

### ISSUE THREAD

**Issue by taseikyo** [Kenshin/simpread#3654]
https://medium.com/@dgqypl/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E5%9C%A8go%E8%AF%AD%E8%A8%80%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-f9478039a1b4

原文：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/23132915/161369721-3037ee60-bec8-4814-8202-72ab5b6758e2.png">

阅读模式：
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/23132915/161369715-a13b619f-1ed3-4cb9-8ff1-41385e4f704c.png">

**Comment by Kenshin** [comment]
嗨，这是 iframe 造成的，而且 medium 的代码高亮千奇百怪... 根本没有任何规律，所以不是很好办。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
