### ISSUE TITLE
自动化保存调用失败的问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3655]
<img width="360" alt="截图_20225302035355" src="https://user-images.githubusercontent.com/38662362/161373009-296739ba-73bb-42fc-a2de-14e4f9175900.png">
请问这个原因是为啥？

_Originally posted by @HJCFLY in https://github.com/Kenshin/simpread/discussions/2146#discussioncomment-2490211_

**Comment by Kenshin** [comment]
@HJCFLY

我将你的问题转移到了这里，并删除了原来的内容。

***

因为你给出的信息太少，没法判断。

这是 [知识库的教程](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)，请对照下跟自己的区别。

**Comment by HJCFLY** [comment]
<img width="705" alt="截图_20220602070622" src="https://user-images.githubusercontent.com/38662362/161380390-7cf28d7c-9328-486d-af77-de81f42f9b5c.png">
<img width="664" alt="截图_20220602070647" src="https://user-images.githubusercontent.com/38662362/161380400-5e58827e-f6ea-42f3-9dfa-d09ad9498792.png">
<img width="756" alt="截图_20220702070703" src="https://user-images.githubusercontent.com/38662362/161380408-bf28c26f-76b9-4968-92fc-f4cff6ef3ff4.png">
<img width="547" alt="截图_20220702070727" src="https://user-images.githubusercontent.com/38662362/161380428-78e88d3e-b276-4d5c-9533-66ef337054ec.png">
<img width="705" alt="截图_20220702070757" src="https://user-images.githubusercontent.com/38662362/161380438-905ac256-019f-4167-9d12-04745ba3498c.png">
<img width="505" alt="截图_20220802070834" src="https://user-images.githubusercontent.com/38662362/161380454-8a2cb56a-0ba4-4aa1-9fb6-e4f6ed05b950.png">

**Comment by HJCFLY** [comment]
<img width="425" alt="截图_20221202071202" src="https://user-images.githubusercontent.com/38662362/161380569-0d40dc00-48eb-47f4-978b-c623a7c49556.png">
 然后就没了 请问为啥啊

**Comment by Kenshin** [comment]
1. 试试安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
2. 请告知出问题的 URL 还是每个都有问题？
3. 请试试一些正常点的页面 e.g. https://sspai.com/post/71739

**Comment by HJCFLY** [comment]
我尝试了那个页面，还是不行。插件也安装了。
<img width="508" alt="微信截图_20220403123023" src="https://user-images.githubusercontent.com/38662362/161411636-18a61b7e-fb8d-43ed-9333-24f44dccd3c9.png">
![image](https://user-images.githubusercontent.com/38662362/161411645-9a52cd0c-220c-499b-87cf-9690a52a08c3.png)

**Comment by HJCFLY** [comment]
我是win11  谷歌浏览器

**Comment by HJCFLY** [comment]
> 我尝试了那个页面，还是不行。插件也安装了。 <img alt="微信截图_20220403123023" width="508" src="https://user-images.githubusercontent.com/38662362/161411636-18a61b7e-fb8d-43ed-9333-24f44dccd3c9.png"> ![图片](https://user-images.githubusercontent.com/38662362/161411645-9a52cd0c-220c-499b-87cf-9690a52a08c3.png)

然后 显示开始下载后就没反应了。
![image](https://user-images.githubusercontent.com/38662362/161411694-a41a1f72-cc96-4fd0-b1df-e1cc7088f2e5.png)
本地文件夹里，并没有相应的HTML文件

**Comment by HJCFLY** [comment]
最后是这个界面，本地文件夹里没有任何文件。
![image](https://user-images.githubusercontent.com/38662362/161411694-a41a1f72-cc96-4fd0-b1df-e1cc7088f2e5.png)

**Comment by Kenshin** [comment]
把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3655

不过，可能不会马上给你回复。

**Comment by Kenshin** [comment]
哦，你还可以这样做：

1. 仅关闭同步助手的自动同步功能。
2. 然后安装我说的插件。

看看能否解决？

**Comment by Kenshin** [comment]
再补充一点：

自动化方案只添加 HTML，其余都不要

![image](https://user-images.githubusercontent.com/81074/161415920-ac059d06-9ef3-4158-9c10-af8f5aab2212.png)

**Comment by HJCFLY** [comment]
你刚刚说的办法我都试过了，还是不行：

是否是它的原因
<img width="727" alt="截图_20222003042059" src="https://user-images.githubusercontent.com/38662362/161418868-743f5cab-cbd1-4534-97ff-b774fc215d2f.png">
当我点击它开启后会有如下提示：
<img width="453" alt="截图_20222003042035" src="https://user-images.githubusercontent.com/38662362/161418851-de656c64-a05f-451e-9ec5-e1b5c93abf12.png">

**Comment by HJCFLY** [comment]
我找到问题原因了 ， 新电脑这里没有给授权。
<img width="777" alt="截图_20222603042625" src="https://user-images.githubusercontent.com/38662362/161419038-a9985e43-1ace-4877-8df0-7a6bf572c032.png">
感谢作者耐心解决！

**Comment by Kenshin** [comment]
我的天....  😂  😂  😂 

终于解决了！

***

你要不在  [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 来个五星好评 + 评价

都「对不起」这么多次的 QA  😅  😏

**Comment by HJCFLY** [comment]
<img width="925" alt="截图_20221303081357" src="https://user-images.githubusercontent.com/38662362/161427555-d6cd4aa9-5cef-4f66-93f6-b9c5890cc074.png">
我太菜了 哈哈哈  早就评论好了，我老用户了，就是没仔细琢磨 哈

**Comment by Kenshin** [comment]
> 我老用户了，就是没仔细琢磨 哈

哈哈，老用户  👍 +1111。

> 我太菜了 哈哈哈 

小事情，做 QA 啥事情都能碰到，总归一句话「你（用户）不用放弃你，我就不放弃你」， 没啥问题是解决不了的，尤其是其他人都能使用的功能。  😏

**Comment by HJCFLY** [comment]
感谢老哥的耐心！也祝简悦越来越棒！
