### ISSUE TITLE
Firefox扩展无法打开站点编辑器

### ISSUE THREAD

**Issue by marcosteam** [Kenshin/simpread#366]
环境：Ubuntu 18.04，最新版Firefox
现象：打开一个临时阅读模式的网站，点击站点编辑器后，没有弹出编辑器窗口，且所有侧边按钮均无法点击。且关闭临时阅读模式后无法重新进入。刷新后可正常加载。

**Comment by Kenshin** [comment]
请问能否复现？方便的话，请告知 url ~

**Comment by Kenshin** [comment]
谢谢反馈，Firefox 目前的版本是 1.0.xx，之前提交过 nnn 次 1.1.1 都被各种原因驳回了...

新版应该没有这个问题了。

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，下载地址 https://addons.mozilla.org/zh-CN/firefox/addon/simpread/

由于 Firefox 会经常 「以无法比对源代码」的方式下架 简悦，所以请尽快更新。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀

**Comment by Kenshin** [comment]
嗨，各位，简悦 for Firefox 版正式发布了~

<img width="808" height="455" alt="Image" src="https://github.com/user-attachments/assets/58297ed1-551a-4fd1-b603-f42e7b4d9dbc" />

# 📚 支持浏览器

Zen browser · Firefox Nightly · Firefox Developer Edition · Firefox · Librewolf

# 🔗 如何使用 & 简悦 CRX 下载

[https://github.com/Kenshin/simpread/discussions/7279](https://github.com/Kenshin/simpread/discussions/7279)

注意：请不要使用 Chrome Webstore 下载的 crx，请使用专门为 Firefox 适配的 crx（上面链接有下载地址）

# ✅ 完美支持

- 阅读模式 / 聚焦模式

- 安装插件

- 更新站点

- 稍后读 / 标注

# ✳️ 需配合 [同步助手 1.5.0](https://n.simp.red/posts/648) 后支持

- 自动同步

# ❎ 不完美支持

快捷键暂时无法使用，但你可以使用 **全局快捷键解决无法进入阅读模式和加入稍后读的问题**，也可以使用 **Assistive Touch 解决简悦插件快捷键无法使用的问题**，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16470898)

# 在 Firefox 正式版使用简悦

如果你不希望更换上述浏览器，在 Firefox 也可以正常使用，但需要一些技巧，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16446625) 

# 最后

有任何问题统一在 [https://github.com/Kenshin/simpread/issues/7037](https://github.com/Kenshin/simpread/issues/7037) 讨论

我关闭这个 issues 了~
