### ISSUE TITLE
关于 Android 使用简悦的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3660]
另外我还有一个问题想问一下，我在Android上安装了简悦，但是配置与PC的不一样，我想同步稍后读数据但不想同步配置文件，是否有办法解决呢？

在阅读模式中是否有快速进入稍后读的方法（不使用快捷键）？

谢谢！

_Originally posted by @BopSun in https://github.com/Kenshin/simpread/discussions/2974#discussioncomment-2493143_

**Comment by Kenshin** [comment]
@BopSun 

我帮你新建立了一个 issues 并删除了原来位置的内容。

***

> 在阅读模式中是否有快速进入稍后读的方法（不使用快捷键）？

没有。不过，可以考虑出一个插件来实现，我先记录下。

> 我在Android上安装了简悦，但是配置与PC的不一样，我想同步稍后读数据但不想同步配置文件，是否有办法解决呢？

没有，好奇问问这么做的理由是什么？

**Comment by BopSun** [comment]
我在PC上使用同步助手，但是手机中无法使用。包括一些功能手机上用不到就关闭了。因此部分设置会与PC的配置不同。

当我在手机上阅读做标记并自动加入稍后读后，需要同步稍后读记录，但是我担心同步时连手机上的配置也一起同步了。这样的话我在pc上就需要反复重新设置配置文件。显得非常的麻烦。

如果可以仅自动同步稍后读记录，配置可以手动同步或不同步就没有这个问题了。

**Comment by Kenshin** [comment]
okay 理解你的需求了，但目前确实没有好的解决方案，我先留着这个 Issues，有后续解决方案会在这里通知你

至于另外一个问题，等插件完成了会通知你。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题，可以使用此功能 https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887 来解决单条稍后读导出和导入的问题。

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
