### ISSUE TITLE
稍后读离线模式下，无法正常加载图片

### ISSUE THREAD

**Issue by ForeverYoungPp** [Kenshin/simpread#3663]
**请说明发生问题的环境**
- 操作系统 **Windows**
 版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎4/‎12
操作系统内部版本	19044.1586
体验	Windows Feature Experience Pack 120.2212.4170.0

- 浏览器版本 **Chrome 100.0.4896.60**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://mp.weixin.qq.com/s/nCBghUVrmbis_8bVN7C4OA

**请描述你的问题**

稍后读读有离线缓存，在离线的时候图片加载不出来
1. 添加到稍后读
2. 点击右上角的 **离线 HTML** 
3. 等待文件导出成功后，断开网络，重新刷新 **稍后读** 
4. 在阅读模式下图片无法正常加载出来（离线）

**截图**

![image](https://user-images.githubusercontent.com/33747394/161430264-e1317565-7947-4b94-a471-9f0f47862b70.png)
![image](https://user-images.githubusercontent.com/33747394/161430442-59d1837f-1cff-4206-bc30-6e503104ff9c.png)
![image](https://user-images.githubusercontent.com/33747394/161430480-6e03f3cf-f676-4425-ba9f-818de6689874.png)

**Comment by Kenshin** [comment]
嗨，你需要配置 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 从而实现：在稍后读加载离线文件的目的。

目前的操作仍是通过网络读取图片，而非从本地。
