### ISSUE TITLE
leetcode解答 无法正常进入阅读模式

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#3664]
https://leetcode-cn.com/problems/number-of-islands/solution/dao-yu-lei-wen-ti-de-tong-yong-jie-fa-dfs-bian-li-/

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/38575961/161441941-1b18bfb4-0663-4919-a004-c0a96a55fcac.png">

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/38575961/161441956-d059dabf-d6a5-48c6-8fb6-6a2e620a85d5.png">

**Comment by Kenshin** [comment]
嗨，此类网站都是无法在稍后读中的，需要配置 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 后才能使用。
