### ISSUE TITLE
标注同步至 Hypothesis 时，备注的内容被放入了高亮的内容中

### ISSUE THREAD

**Issue by OverflowCat** [Kenshin/simpread#3666]
**请说明发生问题的环境**

- 操作系统 **Windows 11**

- 浏览器版本 **Chrome 99.0.4844.82**

**请描述你的问题**

标注同步至 Hypothesis 时，**备注的内容被追加在高亮的内容的末尾**，导致 Hypothes.is 扩展在显示来自简悦的标注时，无法准确判定高亮的结束位置，同时也带来 Hypothesis 和其他软件（比如 Logseq）联动时的不便。

![image](https://user-images.githubusercontent.com/20166026/161480128-f192b812-ad91-49d0-a3a2-829f5e6b4e76.png)期望的效果

![image](https://user-images.githubusercontent.com/20166026/161480289-93e57bf8-d5e0-459c-b949-2bb6535e87f1.png)
目前的效果

**Comment by Kenshin** [comment]
收到，应该跟 https://github.com/Kenshin/simpread/issues/3548 是关联问题，我看看如何解决。

**Comment by OverflowCat** [comment]
今天确实还遇到了一个结构错乱的问题，就是高亮的内容里含有特殊样式的话，会把周围的相同单词也高亮上。（需要标注好后第二次进入阅读模式）

![image](https://user-images.githubusercontent.com/20166026/161484062-9c6e84ba-2803-47e2-a615-7439d0bce844.png)
[这个高亮的句子](https://limpet.net/mbrubeck/2019/02/07/rust-a-unique-perspective.html#:~:text=Depending%20on%20the%20type%20of%20the%20value%2C%20assigning%20a%20value%20to%20a%20new%20variable%20will%20either%20move%20it%20or%20copy%20it.) 中的「copy」是粗体，第二次进入阅读模式后，下一句中的「copy」这个单词也都被高亮了。

**Comment by Kenshin** [comment]
> 今天确实还遇到了一个结构错乱的问题，就是高亮的内容里含有特殊样式的话，会把周围的相同单词也高亮上

英文中因为字频比较高，确实有存在这种可能性，虽然不大...

**Comment by Kenshin** [comment]
1.0.2 版本解决了这个问题，我直接关闭这个 issues 了。😄
