### ISSUE TITLE
请问有没有使用简悦实现渐进式总结的方法或最佳实践

### ISSUE THREAD

**Issue by Shawnli1874** [Kenshin/simpread#3667]
希望能保留原文和 highlight，并导入到 Roam Research 或 Obsidian 以便做进一步的总结

**Comment by Kenshin** [comment]
嗨，如果没问题的话，我关闭这个 Issues  了。

另外，如果你对工作流感兴趣的话，可以订阅：

1. 简悦的官方渠道 https://simpread.pro/subscribe
2. Telegram Channel https://t.me/simpread
3. 简悦的官方知乎专栏 https://www.zhihu.com/column/kenshin
4. 简悦的 Newsletter https://simpread.zhubai.love/
