### ISSUE TITLE
保存到印象笔记失败

### ISSUE THREAD

**Issue by yinliuhui** [Kenshin/simpread#367]
这个地址https://post.smzdm.com/p/547036/

提示“保存失败，请稍后再试”

win10专业版 版本1709，浏览器cent（版本 3.5.3.50（正式版本） （32 位） (Chromium 67.0.3396.99)）

**Comment by Kenshin** [comment]
谢谢反馈，1.1.2 会降低转换的失败率。

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，重构了 【导出到 印象笔记】的代码，基本上解决了导出总是失败的问题。

同时增加了当导出失败时，以 **Markdown 格式 二次保存** 及 提交到 **待决站点机制** ，确保万无一失。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
