### ISSUE TITLE
极客时间文章内标题缺失

### ISSUE THREAD

**Issue by TrillStones** [Kenshin/simpread#3670]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://time.geekbang.org/column/article/68319>

**请描述你的问题** 

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
标题缺失

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="511" alt="image" src="https://user-images.githubusercontent.com/32927876/161710770-18a2e750-57e3-443c-98c2-1f593bafc8e1.png">

图片中的“查询缓存”标题不见了

**Comment by Kenshin** [comment]
emmm 你是怎么进入这个页面的？

这个适配规则可能已经失效或者我没有权限查看导致的...

![image](https://user-images.githubusercontent.com/81074/161712482-eb0b7951-0518-4c4d-86fc-96eae2f8d76a.png)

**Comment by TrillStones** [comment]
> emmm 你是怎么进入这个页面的？
> 
> 这个适配规则可能已经失效或者我没有权限查看导致的...
> 
> ![image](https://user-images.githubusercontent.com/81074/161712482-eb0b7951-0518-4c4d-86fc-96eae2f8d76a.png)

要付费才能看到这个页面。我看了下，现在标题有了，是因为修复了吗？真快！

**Comment by Kenshin** [comment]
> 要付费才能看到这个页面。我看了下，现在标题有了，是因为修复了吗？真快！

哈哈，当然没有修复了，即便我修复了，你怎么能无感就自动好使？之前不好使可能恰好而已，官方适配过这个站点的。
