### ISSUE TITLE
扩展端需要先确保你的账户为高级账户后才能使用此功能，这是什么原因？

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#3671]
我把其他浏览器上面的账户退出了，也还是这样？
![image](https://user-images.githubusercontent.com/8450915/161722073-58199332-4b7b-4beb-978b-68921bf85af7.png)

**Comment by Kenshin** [comment]
嗨，这个提示跟你的操作无关，试试 https://github.com/Kenshin/simpread/discussions/2816 此方式。
