### ISSUE TITLE
极客时间文字下面有虚线

### ISSUE THREAD

**Issue by TrillStones** [Kenshin/simpread#3672]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://time.geekbang.org/column/article/69636>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

文字下面有虚线，怎么去掉？

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="1113" alt="WeCom20220405-175003@2x" src="https://user-images.githubusercontent.com/32927876/161728168-3ba12c0f-b886-47c3-9cfa-1056cd8c3a86.png">

<img width="1026" alt="WeCom20220405-175101@2x" src="https://user-images.githubusercontent.com/32927876/161728198-48528f9d-409f-43c6-b049-9dd46052c000.png">

**Comment by Kenshin** [comment]
哈哈，你这自问自答了，我直接关闭这个 Issues 了。

**Comment by TrillStones** [comment]
> 哈哈，你这自问自答了，我直接关闭这个 Issues 了。

不是的，实际剪裁的，还是会出现虚线。因为他们页面初始化的时候是默认展示这些虚线的。

<img width="1663" alt="WeCom20220405-182948@2x" src="https://user-images.githubusercontent.com/32927876/161735026-ca33e34b-2f7e-4588-a5c6-e5f62b03a334.png">

**Comment by Kenshin** [comment]
> 方案二我提供账号密码给你看OK吗？大佬

okay 将账户和密码发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3672
