### ISSUE TITLE
标注功能和稍后阅读功能都无法使用了

### ISSUE THREAD

**Issue by ANNOARK** [Kenshin/simpread#3674]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Vivaldi 5.1.2567.73**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://sspai.com/post/72475> 与网址并无关系，这里只是列举了下方 gif 中演示的网址

**标注功能突然无法启用，同时稍后阅打开后也变成了空白页** 
今天才购买和使用简悦，起初是可以使用标注功能的，也配置好了和 Logseq 的同步。但是，再次打开一个网站时，突然发现标注功能无法使用了，点击右下角的按钮也无法切换开启/关闭，原先网站的标注也看不到了（有时按钮显示为红色的启用，有时显示为灰色的未启用，无论哪种实际上都未启用）。

![SimpRead反馈](https://user-images.githubusercontent.com/43340211/161770162-c881b724-961e-4dfe-983c-bd7863e44a33.gif)

稍后阅功能变成了空白页，下面贴上的是【稍后阅-F12开发者页面-控制台】的代码，不知道有没有帮助

![image](https://user-images.githubusercontent.com/43340211/161770131-781c000f-f2ed-4c33-9b46-cf854222f394.png)

**Comment by Kenshin** [comment]
嗨，试试此方式 https://github.com/Kenshin/simpread/discussions/3165 100%可以解决

**Comment by Kenshin** [comment]
请问你的问题解决了吗？

**Comment by ANNOARK** [comment]
已经解决啦，试过了 #3165 的方法，依旧是无效。最后是重装了插件就好了。

**Comment by Kenshin** [comment]
> 已经解决啦，试过了 #3165 的方法，依旧是无效。最后是重装了插件就好了。

搞定就好，如果使用同步助手 + 坚果云的话，还是建议使用历史记录，这样能还原的更好。
