### ISSUE TITLE
手机端无法安装notion导出增强插件

### ISSUE THREAD

**Issue by sherlockmj** [Kenshin/simpread#3676]
![4d749d56d69988282cf46a265e112ca](https://user-images.githubusercontent.com/32857102/161899507-7e55af0a-ea6f-4d8f-975d-24c38e1e0a60.jpg)
![1828502e754339fdca94239c497645a](https://user-images.githubusercontent.com/32857102/161899534-b729da28-86ba-4904-bc2e-1c2c9fc13903.jpg)
使用的狐猴浏览器。一直卡在正在安装插件

**Comment by Kenshin** [comment]
嗨，请使用 https://zhuanlan.zhihu.com/p/415622477 提供的方式安装。

简单的说，在 PC 安装然后将配置导入到手机的简悦。

PS：之前听过狐猴浏览器，感觉如何？

**Comment by sherlockmj** [comment]
只是一款可以使用插件的浏览器，暂时没有比较突出的部分，我先试试kiwi，先谢过

**Comment by Kenshin** [comment]
> 只是一款可以使用插件的浏览器，暂时没有比较突出的部分，我先试试kiwi，先谢过

刚才给出链接的方式跟 Kiwi 没有关系，狐猴也能使用。

**Comment by sherlockmj** [comment]
但是狐猴安装插件不成功，一直卡在那个界面


| |
18811151689
|
|
***@***.***
|
在2022年4月6日 13:26，Kenshin ***@***.***> 写道：

只是一款可以使用插件的浏览器，暂时没有比较突出的部分，我先试试kiwi，先谢过

刚才给出链接的方式跟 Kiwi 没有关系，狐猴也能使用。

**Comment by Kenshin** [comment]
> 但是狐猴安装插件不成功，一直卡在那个界面

我不是告诉你解决方案了吗？ https://github.com/Kenshin/simpread/issues/3676#issuecomment-1089828984

**Comment by sherlockmj** [comment]
![989552b78556ef4b2ff3dba15de0a86](https://user-images.githubusercontent.com/32857102/161911617-0d80e86f-1527-4bbf-a459-72d1bac3eb58.jpg)
![e229047d49c330a8c163d5878d43211](https://user-images.githubusercontent.com/32857102/161911627-62d102ad-ce47-4456-b6f3-42a904978e56.jpg)

您好kiwi在安装notion增强导出插件时，也无法成功

**Comment by sherlockmj** [comment]
可以进入稍后读，但是无法单独安装notion导出增强插件

**Comment by Kenshin** [comment]
如何安装此插件，请看 https://zhuanlan.zhihu.com/p/415622477 的操作方案，我已经说第三次了...  😂

**Comment by sherlockmj** [comment]
额，我能安装上简悦并且可以打开稍后读，但是简悦里的插件“导入到 Notion 辅助增强”，在安装时候显示不成功，您提供方案只是在手机端安装简悦，并没有给出安装“导入到 Notion 辅助增强”失败的解决方案

**Comment by Kenshin** [comment]
> 额，我能安装上简悦并且可以打开稍后读，但是简悦里的插件“导入到 Notion 辅助增强”，在安装时候显示不成功，您提供方案只是在手机端安装简悦，并没有给出安装“导入到 Notion 辅助增强”失败的解决方案

1. 请在 PC 端安装 导入到 Notion 辅助增强并配置它
2. 配置后请导出配置文件
3. 将导出的配置导入到手机端的简悦里面
4. 在手机端中打开选项页 → 插件管理 → 导入配置文件的插件

**Comment by sherlockmj** [comment]
感谢答疑，已经解决了。我每次都是没点击这个插件管理 → 导入配置文件的插件，而是直接去下载所以导致不成功。谢谢耐心答疑

**Comment by Kenshin** [comment]
> 感谢答疑，已经解决了。我每次都是没点击这个插件管理 → 导入配置文件的插件，而是直接去下载所以导致不成功。谢谢耐心答疑

哈哈，忒不容易了，搞定就好。  😂  我说你「拧巴」啥呢，原来如此...

***

不来个 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星好评 + 评价

都「对不起」这么拧巴的一个 Isues  💪  😏

**Comment by sherlockmj** [comment]
![image](https://user-images.githubusercontent.com/32857102/161985812-f25328e4-a6d8-46ff-8ef2-f112df4cdfd1.png)
已好评！用的edge

**Comment by Kenshin** [comment]
哈哈，谢谢好评。

另外，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)。
