### ISSUE TITLE
开放平台用坚果云登入时显示：服务器发生错误

### ISSUE THREAD

**Issue by Mr-Hejinyin** [Kenshin/simpread#3677]
开放平台用坚果云登入时显示：服务器发生错误，请稍后再试。
我已经授权坚果云作为登入方式了。

**Comment by Kenshin** [comment]
嗨，服务器是没问题的。

有可能还是你的配置文件，重新再试试。

建议可以对比下，开通开放平台的[教程](https://kb.simpread.pro/#/page/%E5%BC%80%E9%80%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0) 有没有什么区别。

**Comment by Mr-Hejinyin** [comment]
WebDAV全程应该用邮箱登入，但【服务-授权管理】那用WebDAV 应用名也能完成授权，让我误解了。
已经搞好了。

**Comment by Kenshin** [comment]
okay 搞定就好。

另外，服务 → 授权管理 → 坚果云 里面已经说的很清楚了，是 Email 地址。

但坚果云那边的确实通过应用名也能调用成功...  😂
