### ISSUE TITLE
[Feature Request] 允许插件“导入到 Obsidian”自定义文件名

### ISSUE THREAD

**Issue by bobwng** [Kenshin/simpread#3678]
插件 https://github.com/Kenshin/simpread/discussions/2902 ，暂不支持自定义文件名，能够允许自定义文件名？

背景：我的文档都是加了时间、日期作为前缀，得以统一管理，否则还需要进一步的加工文件名。

btw，这个插件公开源码了吗？如果可以的话，我们是否可以做贡献？

**Comment by Kenshin** [comment]
okay 没问题，可以考虑的。

至于标题的格式化，是否可以参考 [简悦的 Markdown 格式化语法](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%E6%A0%87%E9%A2%98)

![image](https://user-images.githubusercontent.com/81074/161922352-bc0c4ffa-a7b5-432b-83e5-9575fd5b23ce.png)

还是有其它要求？

> 这个插件公开源码了吗？如果可以的话，我们是否可以做贡献？

没有开源，但这个插件本身也没有什么内容，如果有需要可以分享给你，只是不知道你想要实现什么其它功能？
另外，你提到了「我们」是指哪些人？

**Comment by bobwng** [comment]
我的mac上，加上同步助手后，配置同步怎么都调不好。所以只能从这个插件的方向上入手了。

另外建议同步助手的下一版可以开启debug，将尽量多的一些信息保存到日志里面。这样出问题后，可以更好的确定问题根源，或者反馈到您。

> 没有开源，但这个插件本身也没有什么内容，如果有需要可以分享给你，只是不知道你想要实现什么其它功能？
> 另外，你提到了「我们」是指哪些人？

主要是想，这样能够更好的汇聚社区的资源，否则都是您一个人在跟进。

不过这样的话，CI等一系列工具链都要弄起来，整套系统可能也会比较耗时间，否则还是难以判定社区的修改是否好用。另外，还有一点，是不是一定要发布到您的插件站点上，才能自己发布插件啊？能不能像tampermonkey那样，自己把一个js“拖到”浏览器里面，就可以安装/发布了？只是希望共享给大家的时候，才是需要发布到您的插件网站上？ :)

**Comment by bobwng** [comment]
我的目标是将网页导出到ob后，将图片也保存到本地，并且赋予有意义的命名，最后在md文件名里面加上时间日期。这样，一共使用了下面几个Obsidian插件/组件：

- Templater
  - 自定义函数，调用python脚本下载远程图片，并且替换md的文件内容，将图片链接指向本地。
  - 内置函数，改名，以便将时间日期加入到文件名中
  - 内置函数，将下载日期加到metadata中。
    - 因为日期、时间出现在不同位置，而“导入到Obsidian”一个tag只能解析一次，所以还是需要Templater来辅助
- 简悦
  - 导出到OB
     - 同时使用了自定义模版，将上面需要调用Templater的功能，都放到了模版里面

现在整个场景还差改名没完成，如果改名和下载远程图片同时启动的话，会导致替换md的文件内容的时候失败，因为出现了竞争，导致找不到改名后的文件。

**Comment by bobwng** [comment]
我的意向中的“导入到Obsidian”模版：

```
---
title: {{title}}
url: {{url}}
up: '[[<% tp.file.creation_date("YYYY-MM-DD") %>]]'
tags: {{tags}}
summary: {{desc}}
created: {{date}}
---
<% tp.user.imageToLocal() %> <% tp.file.rename(tp.file.creation_date("YYYY-MM-DD__HH-mm ") + tp.file.title) %> 
```

**tp.user.imageToLocal()**就是我用来下载远程图片的自定义Templater函数。

**Comment by Kenshin** [comment]
嗨，请问你能上 Telegram 吗？如果可以的话，请进群（选项页 → 关于 → 里面有 Telegram 群地址）并直接私聊我。

**Comment by Kenshin** [comment]
嗨，导入到 Obsidian 升级到 1.1.0，增加了如下功能，主要是包含了你要的 `{{url}}`

-  `Add` 新的 Metadata
    - `{{url}}`
    - `{{timestamp}}`
    - `{{note}}`

- `Add` [Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)

## Local REST API 导入方案视频

https://user-images.githubusercontent.com/81074/163329889-8269dbba-144b-45c2-a706-2ed716049c4a.mp4

***

当看到此 Issues 并且没有问题的话，请 Close 它。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.2.0 ，增加了 **重磅功能**：可以不通过同步助手，将标注自动导入到 Obsidian。

## 一站式教程

https://simpread.zhubai.love/posts/2128393555537739776

## 视频

https://user-images.githubusercontent.com/81074/164135947-0552fc11-1b92-4804-a616-df64ae43770a.mp4

**Comment by Manley314159** [comment]
在导入到obsidian插件中，SimpRead Sync高级导入方案，自定义导出标题部分，我定义的格式为：{{now|yyyymmdd}}：{{title}}，结果最近就发现有异常，有时候可以正常增加前面的日期部分，有时候又失效只有网页原始的标题。插件的设置等都没有改变过。请问如何解决？

另外在metadata部分，我设置有{{now|dddd}} 以显示星期，但是只能显示为英文，能否可以用户自主选择输出的语言？

**Comment by Kenshin** [comment]
> 在metadata部分，我设置有{{now|dddd}} 以显示星期，但是只能显示为英文，能否可以用户自主选择输出的语言？

我在 https://github.com/Kenshin/simpread/issues/6833#issuecomment-2509572215 已经回复你了。

> 在导入到obsidian插件中，SimpRead Sync高级导入方案，自定义导出标题部分，我定义的格式为：{{now|yyyymmdd}}：{{title}}，结果最近就发现有异常，有时候可以正常增加前面的日期部分，有时候又失效只有网页原始的标题。插件的设置等都没有改变过。请问如何解决？

标题不建议修改，因为会有 Bug（如你遇到的情况），因为稍后读的标题需要是 `idx-xxxx` 这种形式。

如果你不使用稍后读方式的话，建议请详细描述你的问题。

最后，如仍需讨论，请在 https://github.com/Kenshin/simpread/issues/6833 提交，而不是这里。
