### ISSUE TITLE
无法打开选项页

### ISSUE THREAD

**Issue by YB-Kang** [Kenshin/simpread#3680]
![image](https://user-images.githubusercontent.com/55050981/161914670-f0b6d20c-f7a8-4b2a-87b8-edcbd98cdc7b.png)

打开选项页显示配置出错，我按照提示重装简悦，尝试用配置文件登录和坚果云登录都没办法。

我打开一个网页，阅读模式能进入，我尝试标注显示我是基础用户，里面的插件也没看到了。

请问老师我该怎么解决这个问题？

**Comment by Kenshin** [comment]
嗨，我看你 Close Issues 是解决了这个问题吗？

**Comment by YB-Kang** [comment]
> 嗨，我看你 Close Issues 是解决了这个问题吗？

是的，很抱歉。发完这个 issues 才看到 https://github.com/Kenshin/simpread/discussions/3165 这个回答，成功解决了我的问题。

**Comment by Kenshin** [comment]
哈哈，小事情，搞定就好。
