### ISSUE TITLE
很多网站遇到  a client-side exception has occurred

### ISSUE THREAD

**Issue by booooodv** [Kenshin/simpread#3681]
访问很多网站遇到

![image](https://user-images.githubusercontent.com/35971518/162114064-8dbf1b45-2955-459c-b5ca-6b64b4baf28f.png)

![image](https://user-images.githubusercontent.com/35971518/162114143-239f00d9-f172-483b-be07-1f89dbbe1032.png)

关了简阅就好了

notion 官网

Mirror 文章

**Comment by Kenshin** [comment]
嗨，你可以这样做即可解决

选项页 → 高级设定 → 词法分析引擎

![image](https://user-images.githubusercontent.com/81074/162114497-8408d175-6983-479c-b3ce-ed26be48eff5.png)

另外，我知道 Notion.so 会有影响，但 Mirror 文章建议给出例子我看下，目前没有收到关于它的问题。

**Comment by booooodv** [comment]
https://mirror.xyz/veporns.eth/NExU4FBskswpC_oieF5sQcpGCY0JtdUOADFtVhol15s

**Comment by booooodv** [comment]
关闭惰性加载图片可以解决

**Comment by Kenshin** [comment]
> 关闭惰性加载图片可以解决

哈哈，当然了，肯定没问题的。

> https://mirror.xyz/veporns.eth/NExU4FBskswpC_oieF5sQcpGCY0JtdUOADFtVhol15s

这个没问题，我能正常进入

![image](https://user-images.githubusercontent.com/81074/162115525-44ebdc85-c00b-4341-b45b-4dd11eec3ded.png)

**Comment by Kenshin** [comment]
> https://mirror.xyz/veporns.eth/NExU4FBskswpC_oieF5sQcpGCY0JtdUOADFtVhol15s

我重现了这个问题，应该跟网络加载的速度有关造成的。

我会单独适配这类网站的。

**Comment by booooodv** [comment]
辛苦了，简悦真值

**Comment by Kenshin** [comment]
> 辛苦了，简悦真值

哈哈，谢谢喜欢简悦，要是原因的话，请帮忙在 Chrome Webstore 评分。

请打开 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 然后通过下图的方式帮忙五星好评~

![image](https://user-images.githubusercontent.com/81074/162151782-135df66c-7d65-4662-91d7-1cef14890b47.png)
