### ISSUE TITLE
部分网站 Notion 增强触发失败

### ISSUE THREAD

**Issue by llity** [Kenshin/simpread#3686]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://en.eagle.cool/blog/post/eagle-5-birthday-event/>

**notion 增强触发失败**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/11771112/162381380-c39d1ffc-edf2-4aca-8012-b3b8e1d5d903.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
@llity

**Comment by zhaolx1116** [comment]
操作系统win10
Chrome 版本 109.0.5414.120（正式版本） （64 位）
简悦版本 2.2.0.520

notion 辅助增强触发失败（尝试了知乎、微信公众号文章、少数派），一直是等待状态
![image](https://user-images.githubusercontent.com/21086063/215817056-e91e8fe2-e989-4189-84cf-6e735adc8d14.png)

**Comment by Kenshin** [comment]
@zhaolx1116 

1. 如果不是一周内安装的 Notion 辅助增强，请重新安装它。
2. 导入到 Notion 使用了什么方式？现在有两种导入方案：扩展端内置与[插件端](https://github.com/Kenshin/simpread/discussions/4954)

**Comment by zhaolx1116** [comment]
1.重新安装不起作用问题依旧存在
2.导入用的插件端。导入成功，但触发辅助增强一直是等待状态
![image](https://user-images.githubusercontent.com/21086063/216043544-b4923bb3-b281-4a07-abed-e7325bc13dcb.png)

**Comment by zhaolx1116** [comment]
新建page用官方模板重新配置授权后，测试没问题。谢谢啦～

**Comment by Kenshin** [comment]
@zhaolx1116

哈，搞定就好。

**Comment by 0xJohnX** [comment]
> @zhaolx1116
> 
> 不知道你导入的 Page 里面有多少内容？建议用一个新的 Page 做测试，这个 Page 可以使用 [简悦官方模板](https://simpreadpublish.notion.site/e784eba882da452eb8f300e6cd6b195d)，然后重新授权等操作。
> 
> 最后再使用 https://sspai.com/post/69972 测试。
> 
> 另外，在配置新的 Page 期间建议不要开过多的 Tab，配置完后重启浏览器，确保不会因为配置互相覆盖而导致失败。

我这里的情况类似，但是在测试页面没有问题。
换回之前的 Page 又会一直等待状态，导入的 Page 有 近 2000 条内容，从 1 月 19 日开始 增强功能就失效了。

**Comment by 0xJohnX** [comment]
> @zhaolx1116
> 
> 不知道你导入的 Page 里面有多少内容？建议用一个新的 Page 做测试，这个 Page 可以使用 [简悦官方模板](https://simpreadpublish.notion.site/e784eba882da452eb8f300e6cd6b195d)，然后重新授权等操作。
> 
> 最后再使用 https://sspai.com/post/69972 测试。
> 
> 另外，在配置新的 Page 期间建议不要开过多的 Tab，配置完后重启浏览器，确保不会因为配置互相覆盖而导致失败。

我这里的情况类似，用的插件端，在测试页面没有问题。
换回之前的 Page 又会一直等待状态，导入的 Page 有 近 2000 条内容，从 1 月 19 日开始 增强功能就失效了。

**Comment by Kenshin** [comment]
@0xJohnX 

增强导出并不是失效...否则 Issues 会炸，21年7月份和12月份的事件可见一斑...

你的问题大概率在于：

1. 失效的 Page 可能是因为 Database 结构改变造成的（但你给出的信息太少，我没法判断）
2. Notion API 无法支持这么多的 Page 检索...

再者说：

> 一个在线「存储」放个 2000+ 个子 Page 并不是一个好方案，更何况 Notion 的速度有目共睹...

解决方案：

在同级建立相同的 Page，尽量减少每个 Database 存放过多的 Page。

**Comment by 0xJohnX** [comment]
👌好的，谢谢

**Comment by denden846** [comment]
操作系统：win10
浏览器：edge 版本 115.0.1901.203 (正式版本) (64 位)
简悦版本： 2.2.0
用的插件端
notion辅助增强优化失败
![screenshot20230817](https://github.com/Kenshin/simpread/assets/129040040/38788725-edb5-44bd-a8e5-e055b2c2bb95)

**Comment by Kenshin** [comment]
@denden846 

极端情况下，标注到 Notion 确实有可能出问题，所以找个正常点的页面 e.g. https://sspai.com/post/69972 仅标注文字段落的前提下测试下是否正常。

如果仍有问题的话，请 https://github.com/kenshin/simpread/issues/new 并讨论。

**Comment by denden846** [comment]
> @denden846
> 
> 极端情况下，标注到 Notion 确实有可能出问题，所以找个正常点的页面 e.g. https://sspai.com/post/69972 仅标注文字段落的前提下测试下是否正常。
> 
> 如果仍有问题的话，请 https://github.com/kenshin/simpread/issues/new 并讨论。

用了测试的页面，依旧失效orz
![screenshot20230819](https://github.com/Kenshin/simpread/assets/129040040/1cad6769-3b17-4646-b4a2-394c6f8ac849)

**Comment by Kenshin** [comment]
@denden846 

正文呢？如果正文也失败的话，说明你的配置有问题。
