### ISSUE TITLE
关于Notion 辅助增强的安全性

### ISSUE THREAD

**Issue by geekbb** [Kenshin/simpread#3689]
我是小白，我看到在使用Notion 辅助增强时，需要“获得 Notion API Token”，在这一步操作成功后，是不是就可以读取到我关联的工作区所有Notion文档了？关于隐私和安全性，我还是很重视的，请作者解答
<img width="680" alt="image" src="https://user-images.githubusercontent.com/46196358/162443757-0677116e-35b0-4ffa-becc-92fccd91b66b.png">

**Comment by Kenshin** [comment]
1. 你的 Notion Token 只能访问当前的 Workspace
2. 导入数据自然需要读写你的 Page 权限

你可以这么做
授权的 Workspace 只有一个 Page。

另外，你要是稍微了解过简悦的话，就会知道：
为了保障用户的隐私性，简悦没有账户系统，也没有保存用户的数据。

所以，我比你（用户）还要重视隐私和安全性。
