### ISSUE TITLE
简悦导出标注至supermemo

### ISSUE THREAD

**Issue by gg-s-dd** [Kenshin/simpread#3691]
悟性太低，作为有一点电脑基础的使用者，按教程配置的6个小时，反复失败。我想要的很简单，就是标注后，导出文字及内部链接，我使用quicker再导出到sm中，方便回溯上下文，反复失败，失去信息，总是复印不上链接，然后提示我> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 来自 chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/unreader/loader.html?url=https://sspai.com/post/72459 > 我也不知道这玩意有啥用
另外，我不知道整那么多教程原因是什么？logseq的，语雀的等等等等，又是导图又是反复的链接gitub，花了呼哨，看的一片乱套

**Comment by Kenshin** [comment]
导入到 supermemo 不需要配置任何内容，安装简悦和[对应的插件](https://simpread.ksria.cn/plugins/details/6FIqWZpXRD)就能使用。

**Comment by gg-s-dd** [comment]
> 导入到 supermemo 不需要配置任何内容，安装简悦和[对应的插件](https://simpread.ksria.cn/plugins/details/6FIqWZpXRD)就能使用。
简悦的理念是非常棒的，我也很认同，各种灵活的接口与设置够感受到作者的勤劳与用心，我非常想要有效的利用好它。只是因为被复杂的界面，再加上反复的重复操作（总是莫名其妙的保存不上)被弄的迷失了方向，感觉到烦躁，实在不好意思。这个对应的插件之前我看过，但它与我自己实际的需求不太相符。不管怎样，简悦是一款非常棒的插件，只是需要我们踏下心思好好研究。
正在看着您的bili与知乎上的分享，也希望能够尽快熟悉这款插件，从繁杂的设置中做好自己的需求，祝：越来越好。

**Comment by Kenshin** [comment]
哈哈，小事情而已。

> 关于「再加上反复的重复操作（总是莫名其妙的保存不上)被弄的迷失了方向」

给出几个建议：

1. 不要同时多开多个 Tab 一次操作，因为会互相覆盖配置。（这不是简悦的问题，就比如：打开两个一样的文档，同时编辑，同时保存一样，

2. 只开两个：一个选项页（A）；一个进入阅读模式的页面（B），即可。当 A 改动后刷新 B使其使用最新的数据；反之也一样。

3. 使用同步助手后，如果非常频繁的保存和设置项，就先关闭自动同步功能，等配置稳定了（毕竟不需要随时改动，只是配置一次），在开启自动同步。
