### ISSUE TITLE
高级账户购买问题

### ISSUE THREAD

**Issue by kevenlau** [Kenshin/simpread#3697]
在购买高级账户的选项中，选择了腾讯问卷的那一个，为什么一直都没有得到响应

**Comment by Kenshin** [comment]
没有问题，你可以直接访问 https://wj.qq.com/s2/6918802/ffc8/ 购买

**Comment by kevenlau** [comment]
我昨晚已经买了，但似乎我的qqmail一直都没有收到任何的反馈

**Comment by Kenshin** [comment]
购买前已经告诉你了

![image](https://user-images.githubusercontent.com/81074/162605348-67865894-77ad-4d3b-bd58-7c9d4e0f0db7.png)

**Comment by kevenlau** [comment]
我当时没有关注到这些，表示抱歉

**Comment by Kenshin** [comment]
哈哈，小事情而已~

你不是第一个，也不会是最后一个。 😂
