### ISSUE TITLE
保存到onenote公式不显示

### ISSUE THREAD

**Issue by BMXDa** [Kenshin/simpread#3698]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **  Windows10**

- 浏览器版本 ** Microsoft Edge
版本 100.0.1185.36 (正式版本) (64 位)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <https://www.zhihu.com/question/24591127/answer/28341708>

**请描述你的问题**
保存到onenote后，公式不显示
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![1649573083(1)](https://user-images.githubusercontent.com/101966143/162605920-3063c0de-8a18-4b79-82ed-ef7337859469.jpg)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，知乎公式与其它的方式不同，导入后肯定有问题，这不是简悦的问题。

你可以试试 https://github.com/Kenshin/simpread/discussions/2861 提供的方式能否解决？
