### ISSUE TITLE
Read later list only shows two entries

### ISSUE THREAD

**Issue by bafmag** [Kenshin/simpread#37]
When I added three pages to the read later list (RLL), the third one is not shown in the RLL. After I added that page again, it appeared, but the second page that I added disappeared. Moreover, when I tried to add the  second page again, it noticed that it had already been added, but the page did not show in the RLL. So the read later list only shows two entries.

**Comment by Kenshin** [comment]
Sorry, reply late.  :pensive:
 just tested, did not find the problem you said, can you be able to reproduce?

**Comment by fapbod** [comment]
Today I reproduced it. I opened two webpages, A and B, and pressed the hot-key "a a", followed by saving to read later list, but only to find one newly added page there, let's call it Page A. Then I added page B again, this time, B appeared in the list, but A disappeared.
Is there any log file for troubleshooting?
