### ISSUE TITLE
稍后读界面标题与离线内容不对应的问题（附解决方案）

### ISSUE THREAD

**Issue by WeiCJ2020** [Kenshin/simpread#3700]
- 操作系统 **Windows**

- 浏览器版本 ** Edge 100.0.1185.36 (正式版本) (64 位)**

- 简悦版本 **2.2.0.520**

在如下**配置**中会出现稍后读界面标题与离线内容不对应的问题.
开启离线html的自动化任务
开启稍后读加载离线文件
开启自定义标题{{id}}{{title}}

**问题描述:**
1. 当加入一个[title-1]网页时, idx被设置为100, 此时output文件夹中有一个100-[title-1].html的文件
2. 当这个网页收藏被删除时, output中的离线文件并没有被删除,此时json文件中的最大的idx是99.
3. 新增加一个[title-2]网页时, 其idx又会被设置为100, 并新增一个100-[title-2].html的文件.
4. 此时打开稍后读, 标题是[title-2], 但是加载的离线内容是100-[title-1].html

**截图**
![image](https://user-images.githubusercontent.com/20920396/162611807-b276ced6-a50c-4150-9b6e-bc8f97ad0a7a.png)

**Comment by WeiCJ2020** [comment]
目前先写了一个脚本, 自动比对output文件夹中的文件和simpread_config.json, 然后删除多余的离线HTML文件. 可以暂时解决这个问题.

**Comment by Kenshin** [comment]
哈哈，不错啊，能否贡献下？

**Comment by WeiCJ2020** [comment]
> 哈哈，不错啊，能否贡献下？
我用quicker比较多, 就只是写了个一个简单, 如果大佬可以把这功能集成到同步助手里面就非常好了

![image](https://user-images.githubusercontent.com/20920396/162613783-6763e556-ab0e-413b-98ba-ab9e88fbfe30.png)

**Comment by Kenshin** [comment]
> 我用quicker比较多, 就只是写了个一个简单, 如果大佬可以把这功能集成到同步助手里面就非常好了

哈哈，当然已经记录了。

***

把 Quicker 贡献上来吧  ~

***

你是不是昨晚在群里面提过这个问题？（然后自问自答给解决了~

**Comment by WeiCJ2020** [comment]
重新写了一下逻辑, 处理了一下特殊字符和其他类型的文件
[简悦：离线文件清理](https://getquicker.net/Sharedaction?code=23ac807e-b4af-4025-b1b2-08da1a9d9852)
[[Quicker动作]清理已删除页面的离线文件](https://github.com/Kenshin/simpread/discussions/3702)

**Comment by Kenshin** [comment]
哈哈，太棒了，明天在 Channel 里面发一下。

能否录个屏（使用过程）？

**Comment by WeiCJ2020** [comment]
> 哈哈，太棒了，明天在 Channel 里面发一下。
> 
> 能否录个屏（使用过程）？

好的, 录了一个
![使用说明_20220410](https://user-images.githubusercontent.com/20920396/162625834-eacbda07-d6d8-40b7-86cc-c198374bf98e.gif)

**Comment by Kenshin** [comment]
收到，今天有点忙，不确定能 100% 推送到简悦的渠道，最迟在明天也会推送。

**Comment by WeiCJ2020** [comment]
> 收到，今天有点忙，不确定能 100% 推送到简悦的渠道，最迟在明天也会推送。

么事么事, 这个功能用的人应该也不多,

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 自动覆盖旧文件的功能

开启此功能后，会解决**界面标题与离线内容不对应的问题**，这样就不需要额外使用 Quicker 了。😄

![image](https://user-images.githubusercontent.com/81074/172759226-42737101-3a90-4e4e-97ff-b3a6cd0ef750.png)


## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
