### ISSUE TITLE
稍后读，阅读模式解析不出来。

### ISSUE THREAD

**Issue by ilo-l** [Kenshin/simpread#3705]
**小提示**

稍后读，阅读模式解析不出来。
![image](https://user-images.githubusercontent.com/103417546/162704282-356012d1-6457-4c14-adde-5aa4f60b97c5.png)

已选
![image](https://user-images.githubusercontent.com/103417546/162704491-4dd90933-5751-41a3-99b8-a20167225d33.png)

**Comment by Kenshin** [comment]
嗨，解决方案：

1. 使用 [内置解析](http://ksria.com/simpread/docs/#/Sync?id=%e5%86%85%e7%bd%ae%e8%a7%a3%e6%9e%90)
2. 使用 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)（一劳永逸）

**Comment by Kenshin** [comment]
> 我是用了简悦同步助手的内置解析了，就是用不了阅读模式。

「用不了阅读模式」指的是最开始的截图吗？如果是的话，这算是正常的，简单的解释下：

「内置解析方案」你可以理解为一个网络爬虫帮你爬取页面，但有些页面对爬虫是不允许的，所以才有此问题，虽然可能不多见，但也不是遇不到。

最好的方案在 https://github.com/Kenshin/simpread/issues/3705#issuecomment-1094904110 里面描述了，是方案二。

因为你已经使用了同步助手，使用方案二并不是一个很麻烦的事情。
