### ISSUE TITLE
财新网财新周刊部分界面无法选中标注

### ISSUE THREAD

**Issue by wangjinbao6** [Kenshin/simpread#3709]
财新网财新周刊部分界面原界面限制选中，打开阅读模式后 无法选中，并无法标注。
例子：
https://weekly.caixin.com/2022-04-08/101867019.html?p0#page2

**Comment by Kenshin** [comment]
嗨，这个问题在群里面页面被 Fixed 掉了。

简单的说下：

简悦不会主动改变原页面的结构（甚至主动改变其功能），所以此问题对于简悦来说是「无解的」，但你可以使用「油猴脚本解除网页限制」来解决此限制。
