### ISSUE TITLE
建议 markdown导出的时候能不能选择把图片也下载到本地？

### ISSUE THREAD

**Issue by kerhbal** [Kenshin/simpread#371]
如题，
想要把网页本地保存成markdown，导出后图片还是在网上的，万一404了就找不回来了
感谢~

**Comment by Kenshin** [comment]
纯离线保存？
可以考虑下，谢谢建议~

**Comment by cangling** [comment]
大佬 ，图片本地保存非常重要啊！现在不论是保存到本地还 Dropbox ，都只是个链接。希望下个版本能实现！感谢！

**Comment by woyaojizhu8** [comment]
目前 https://addons.mozilla.org/zh-CN/firefox/addon/maoxian-web-clipper/ 这个扩展选择markdown模式可以保存，包括图片

**Comment by Kenshin** [comment]
增加了 【离线下载为 HTML】 插件 👉https://github.com/Kenshin/simpread/issues/508

Markdown 的离线下载也在开发中~

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [离线下载](http://ksria.com/simpread/docs/#/离线HTML) 的功能，希望喜欢~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by kerhbal** [comment]
老板，请问firefox上的简悦下线是暂时的吗，找不到了

**Comment by Kenshin** [comment]
> 老板，请问firefox上的简悦下线是暂时的吗，找不到了

是的，细节详细请看  https://github.com/Kenshin/simpread/issues/628  的说明。

近期考虑准备直接放 **源代码 · 开发者模式** 提供。
