### ISSUE TITLE
设置知识库后打开链接出现{"code":404,"message":"没有找到对应的内容"}

### ISSUE THREAD

**Issue by gg-s-dd** [Kenshin/simpread#3717]
设置知识库后打开链接出现{"code":404,"message":"没有找到对应的内容"}

**Comment by Kenshin** [comment]
确保设置无误的话，再确保 `output` 文件夹只存在 `.html` 文件。

**Comment by gg-s-dd** [comment]
***@***.***都能正常生成，没有问题，引出的链接也是按照模板设置，也没有问题，output没有其他类型文件



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年4月12日(周二) 晚上6:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 设置知识库后打开链接出现{"code":404,"message":"没有找到对应的内容"} (Issue #3717)




 
确保设置无误的话，再确保 output 文件夹只存在 .html 文件。

**Comment by Kenshin** [comment]
把 `output` 的内容截图给我看下。

**Comment by gg-s-dd** [comment]
---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年4月12日(周二) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 设置知识库后打开链接出现{"code":404,"message":"没有找到对应的内容"} (Issue #3717)




 
把 output 的内容截图给我看下。

**Comment by gg-s-dd** [comment]
![Quicker_20220412_195544](https://user-images.githubusercontent.com/103298102/162957549-8a1bb9c2-2a46-445a-a155-33c8af2fa250.png)
![Quicker_20220412_195624](https://user-images.githubusercontent.com/103298102/162957569-468c4343-d913-4889-889d-c885ab747f4e.png)

**Comment by Kenshin** [comment]
不可能是错误的，截图给我看下。

1600 只是序号而已，不可能当然都是 1600 了…😂

**Comment by gg-s-dd** [comment]
![没有内容](https://user-images.githubusercontent.com/103298102/163066907-e0610bfd-2a43-421a-9b2e-69acc7efc42b.png)

**Comment by Kenshin** [comment]
你为什么访问 `http://localhost:7026/reading/5` 呢？之前的提示不是告诉你访问 `http://localhost:7026/reading/4` 吗？

你给我的截图只有 `4-xxx` 访问 5 当然不好使了。

建议看下 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 的教程（里面内含了 `4 / 5` 的说明）

**Comment by gg-s-dd** [comment]
不好意思造成误解，4我昨天就实验了，提示的就是404错误。之所以是5，是因为我早晨的时候又重新实验了一篇文章，想再看看是否好用。5同样不好用，所以就把5的截图发上去了。

**Comment by Kenshin** [comment]
访问  http://localhost:7026/reading/index 把截图给我看下。

**Comment by gg-s-dd** [comment]
![tmp5EB9](https://user-images.githubusercontent.com/103298102/163091649-60827077-e4c7-4bc3-a745-4e361b9017c2.png)

**Comment by Kenshin** [comment]
我让你浏览器访问 http://localhost:7026/reading/index  😂 然后给我截图。（我没说文件夹的截图...

**Comment by gg-s-dd** [comment]
![tmpAF81](https://user-images.githubusercontent.com/103298102/163092008-9ca7f00e-6abf-44a6-98af-118917722bb6.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3717#issuecomment-1097503734

看截图好像多个空格？看下图的内容跟你是否一致？

![image](https://user-images.githubusercontent.com/81074/163092193-c4490613-06a5-40bf-9727-aafb3c7c38f8.png)

另外，随便找个 `4-xxx.html` 然后重命名，看看 `4` 前面是不是多了个空格？

**Comment by gg-s-dd** [comment]
对我们非编程人员来说，github访问好慢，而且总是连接不上，现在又连接不上了，稍等下我上传哈

**Comment by gg-s-dd** [comment]
![tmpC649](https://user-images.githubusercontent.com/103298102/163093333-99a8b08e-b80a-4935-a2d2-cd52bd099264.png)

**Comment by gg-s-dd** [comment]
我的设置与您的一样，也是没有空格的。

**Comment by gg-s-dd** [comment]
![tmp75EC](https://user-images.githubusercontent.com/103298102/163093649-aff88ae4-496f-42b0-985b-ac53c9ecbdee.png)
确实多了个空格

**Comment by Kenshin** [comment]
> ![tmp75EC](https://user-images.githubusercontent.com/103298102/163093649-aff88ae4-496f-42b0-985b-ac53c9ecbdee.png) 确实多了个空格

应该就是这个问题了，确认下你的 https://github.com/Kenshin/simpread/issues/3717#issuecomment-1097510683 是否正确？

另外，建议在测试时把除简悦外的扩展先都关闭，避免影响。

**Comment by gg-s-dd** [comment]
我除了idm与沙拉查词，未启动其他扩展。请问有其他解决办法么？

**Comment by Kenshin** [comment]
> 我除了idm与沙拉查词，未启动其他扩展。请问有其他解决办法么？

配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3717

**Comment by gg-s-dd** [comment]
已发送

**Comment by Kenshin** [comment]
你的配置设置错了，我已经帮你改过来了，覆盖原来的文件后，刷新选项页生效。

![image](https://user-images.githubusercontent.com/81074/163122770-da757178-2e28-4e51-869e-d1106c925ceb.png)

注意：覆盖原文件后最好重启浏览器。

**Comment by Kenshin** [comment]
我把你之前的那个 Issues 删除了，请在这里讨论。

看下 [资料库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E8%B5%84%E6%96%99%E5%BA%93) 的配置教程，然后多生成几个稍后读，然后再试试。

不要测试 `reading/0` 这样的。

**Comment by gg-s-dd** [comment]
使用内部链接放置到supermemo的reference当中后，没有办法直接访问，但使用bookxnote生成的外链bookxnotepro://opennote/?nb={034d078c-b8c0-4551-9358-9832d1fabee

d}&book=8fd3b0ea3556d1e78af118060c7ebf78&page=333&x=245&y=615&id=915，这种格式的，就能够直接访问。所以我考虑是不是简悦也可以通过外链访问来实现类似目的。目前，连接外链时却提示这样的错误，我尝试过新建，重启浏览器。![tmpE899](https://user-images.githubusercontent.com/103298102/163159643-d1883e50-533b-441d-b6bc-ba25e0b5b632.png)

**Comment by gg-s-dd** [comment]
呼……终于弄好了，太谢谢你了，耽误了你这么久的时间。万分感谢

**Comment by Kenshin** [comment]
哈，竟然是个 4月份 Issues 隔了这么久才回复 😂

不过，竟然解决了  💪  👍 

***

隔了这么久，不帮忙来个五星 + 好评 吗 ？ 😂 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by it-520** [comment]
> 
@gg-s-dd 所以请问一下这是怎么解决的呀

**Comment by Kenshin** [comment]
@it-520 

你应该是没有配置知识库，看这里的教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by TangXuhe219** [comment]
你好，请问一下所有的配置都对的，为什么标注之后文件名前面的{{id}}数字一直没有啊？

**Comment by Kenshin** [comment]
@TangXuhe219 

那就不对呗 😂 检查下 https://www.yuque.com/kenshin/simpread/wkswh7#phV3U 与你的配置是否一致？
