### ISSUE TITLE
高亮标注文字后，特定高亮文字附近出现混乱

### ISSUE THREAD

**Issue by GinnyJourney** [Kenshin/simpread#3723]
**问题环境**

- 操作系统 **Win10**

- 浏览器版本 **Microsoft Edge 100.0.1185.39**

- 简悦版本 **2.0.0** （使用中始终保持同步助手开启，且同步助手内置解析功能为开启状态，同步助手设置如下）

- 发生问题的地址 
&nbsp; https://www.nature.com/articles/s41467-021-25801-2 
&nbsp; https://www.nature.com/articles/s41928-019-0313-3

<img width="526" alt="捕获" src="https://user-images.githubusercontent.com/39979569/163112302-05ddc0fb-a837-4139-9086-174a36a9a9d8.PNG">

**问题描述**

> 在首次访问网页并添加高亮标注后关闭，再次访问网页时，某些高亮处出现混乱，具体如下图所示；
> 问题出现有一定概率，目前仅在三四个网页（都是nature子刊系列网站）的特定段落处发现；
> 混乱高亮的侧边标注栏的条目内容在再次访问时没有异常；

<img width="696" alt="捕获1" src="https://user-images.githubusercontent.com/39979569/163108848-7ddd722a-d4bd-451f-b9d6-40f03de6710f.PNG">
<img width="691" alt="捕获" src="https://user-images.githubusercontent.com/39979569/163108853-436cbcff-7b21-48b9-8367-2a9861d14103.PNG">

**Comment by Kenshin** [comment]
okay 确实有可能有此问题，因为英文的词重率比中文高并且跟标注的结构也有一定关系，印象范围不大，我只收到过一次这样的 Issues 。

比如扇贝阅读上就没有此问题。

PS：你可以试试标注稍长点的内容。

**Comment by GinnyJourney** [comment]
哈哈，好的谢谢~~ 会尝试一下更长标注的标注方式。
btw 这是期刊官网，感觉在官网上阅读文章会更加顺手，如果能优化一下这个bug使用体验会更好呢~

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~


解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~

**Comment by GinnyJourney** [comment]
收到收到，谢谢你！！
---- 回复的原邮件 ----
发件人 Kenshin ***@***.***> 日期 2024年07月06日 12:50 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [Kenshin/simpread] 高亮标注文字后，特定高亮文字附近出现混乱 (Issue #3723) 
嗨，久等了~
稍后读辅助增强 经过漫长的测试，现在已经发布了 🎉 😄
这个插件可以解决此 Issues 提到的问题~
解决了什么
使用了 Live Editor 修改了原页面的内容或 图床插件 将当前页面的图片转换为图床后会导致：与原页面内容不同，当再次进入这个页面时，如果仍读取原页面就【不合理】了。
此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。
一般来说配置了简悦的本地快照方案用户，建议使用此功能。
功能说明
进入阅读模式后，将本地快照的内容还原到阅读模式
进入阅读模式后，当稍后读没有本地快照时自动生成本地快照
稍后读侧栏支持双击删除方式
黑名单
一键设置本地快照
临时禁用本地快照
导入和导出
详细说明
#5943
安装与升级
没有【使用同步助手 · 自动同步】的话，可通过 此链接 安装。
已经【使用同步助手 · 自动同步】的话，请使用 插件管理器 安装。
我关闭这个 Issues 了，有任何问题可以在这里随时讨论~

**Comment by Kenshin** [comment]
哈，小事情。

这个 Issues 有点「老」了，其实这个插件发布了一阵子，只是不知道为什么漏掉了（还不少… 😂）。

所以，陆续看到不少老用户反馈还挺高兴。
