### ISSUE TITLE
AMD 显卡 + 同步助手在使用时会出现蓝屏现象

### ISSUE THREAD

**Issue by shawnzcy** [Kenshin/simpread#3729]
打开同步助手，电脑经常蓝屏，然后就重启。win11系统

**Comment by Kenshin** [comment]
请看此关联 Issues https://github.com/Kenshin/simpread/issues/3346 包含解决方案。

**Comment by Kenshin** [comment]
@shawnzcy 

没问题，试过去掉自启动以及内置解析了吗？

**Comment by shawnzcy** [comment]
> @shawnzcy
> 
> 没问题，试过去掉自启动以及内置解析了吗？

试过了，还是会重启。

**Comment by Kenshin** [comment]
okay 那只能等我的调查了，因为不是每个 AMD 都有此问题的。

**Comment by shawnzcy** [comment]
> 

好的 谢谢，现在还不是重度用户，没有同步助手虽然不方便但是也可以满足日常使用

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 解决了蓝屏问题

> 虽然系统日志并没有指出就是因同步助手引起。

此版本已经让 AMD 显卡的用户测试了半个月+，没有在发生同样类似的问题。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
