### ISSUE TITLE
在高级设定里面如何保存对黑名单的更改？

### ISSUE THREAD

**Issue by alextooter** [Kenshin/simpread#373]
比如我不希望在m.weibo.cn启用自动阅读模式，所以把它加入黑名单

在添加了m.weibo.cn这一行之后，如何保存呢？试了各种方法也没用。

这里的设计让人摸不着头脑。。

**Comment by alextooter** [comment]
我用的firefox 62.0b16，macOS 10.14beta

黑名单添加https://m.weibo.cn/之后，关闭页面，再次打开设置，新添加的url就不存在了。
没达到自动保存的效果呀。

**Comment by Kenshin** [comment]
是这样的，Firefox 的版本为 1.1.0.3022 在这块是有 Bug 的。
但 新版 1.1.1 已经解决了这个问题。
可惜无奈的是， Firefox 审核一直都不通过...  😂 

PS：建议使用 Chrome 版，假设仍旧喜欢 Firefox 的话，我可以先提交 1.1.1（Firefox 会自动过审核），然后会指派一个人做二次审核（每次都在这里挂掉）
所以有个时间差，你可以利用这个时间差 更新到 1.1.1 就能解决了。

如果想这么做的话，请告知我，自动上线后，我会在这里通知你。

**Comment by alextooter** [comment]
不用这么麻烦你了，我关闭自动阅读模式了。

我等审核通过吧。感谢回复。
