### ISSUE TITLE
自动化无法执行

### ISSUE THREAD

**Issue by yyyzl** [Kenshin/simpread#3730]
![image](https://user-images.githubusercontent.com/60340799/163194788-9a34c0c8-2e2b-441d-aaba-459f1039b364.png)
![image](https://user-images.githubusercontent.com/60340799/163194866-37fc043a-6ef5-44e2-804b-221cc50c3a32.png)
当我选择到加入稍后读为啥没有自动保存到notion呢~正常的手动点击保存到notion是可以的，notion辅助增强也是能够自动运行的。在稍后读中点击保存到notion也能够保存，就只是自动化无法实现，想询问下您的意见？
我的简悦版本是2.2.0.520，导入到Notion辅助增强插件版本是1.1.1
我的浏览器是edge，版本是100.0.1185.39

**Comment by Kenshin** [comment]
嗨，请使用 快捷键 `d d` 或右键菜单加入稍后读

**Comment by yyyzl** [comment]
> 嗨，请使用 快捷键 `d d` 或右键菜单加入稍后读

谢谢您的解答

**Comment by Kenshin** [comment]
搞定就好。
