### ISSUE TITLE
无法使用高级帐户功能

### ISSUE THREAD

**Issue by xulu199705** [Kenshin/simpread#3732]
- 操作系统 **macOS 12.3.1**
- 浏览器版本 **Chrome 100.0.4896.88 (arm64)**
- 简悦版本 **2.2.0**
- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

已激活高级帐户⬇️
<img width="832" alt="image" src="https://user-images.githubusercontent.com/17242727/163326802-8448fe93-5cee-4820-b77c-bc2bbe2366dd.png">

以增强导出和自动化的配置区域为例，无法使用这些高级帐户功能⬇️
<img width="841" alt="image" src="https://user-images.githubusercontent.com/17242727/163326990-1ca064ea-e335-4cd0-94d6-626aecee4362.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/17242727/163327045-7e788a53-cca8-4efb-aa6f-9abf3c2fad0a.png">

**Comment by Kenshin** [comment]
嗨，请使用此方式解决 https://github.com/Kenshin/simpread/discussions/2816

升级高级账户后，提示重启浏览器。
