### ISSUE TITLE
使用小书签会覆盖配置文件（不稳定复现，且仅存在于一键收藏）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3734]
有一种情况不是这个原因, 似乎是遇到了bug.
最近多次经历稍后读空白的问题, 然后忽然发现整个配置文件都变成1k了, 这就导致连简悦的配置页面都打不开, 而不再仅仅是稍后读的问题.
![图片](https://user-images.githubusercontent.com/65625632/163324248-6ec347a0-7d1b-4936-9b3d-730ffd93009d.png)
目前比较怀疑是同步助手的小书签有bug, 用小书签添加稍后读的时候有概率会导致该问题, 比如这里应该就是在添加B站视频的时候出了问题, 这个条目把其它的全覆盖了, 建议排查一下.
我这边再试试放弃使用小书签, 改用快捷键进行添加稍后读, 看看问题是否还会出现.

***

411KB, 大约200篇稍后读加注释吧. 几乎可以确定这个bug跟文件大小无关, 我这个远远比11MB小, 但是依然遇到了问题.

_Originally posted by @XMB-7 in https://github.com/Kenshin/simpread/discussions/2727#discussioncomment-2564537_

**Comment by Kenshin** [comment]
同步助手的“加入到稍后读”小书签在我这里基本上是可以正常使用的（虽然它有时候不太稳定，比如显示成功了，但是我去稍后读中看却没有，应该是配置文件太大的缘故？），但是 一键收藏 小书签，每次点击它之后，都会把我的配置文件重置。

***

当我再次用回之前备份好的11MB的配置文件之后，再次尝试一键收藏小书签，弹窗提示成功之后，又把我的配置文件重置回1KB了，这次我打开看了一下这个1kb的文件，里面只有这么几行代码，甚至连配置信息都被清除了
![image](https://user-images.githubusercontent.com/49675185/163304027-cd16bcd6-a9c5-4113-8be4-7677db629ee1.png)
这就很迷了，这次也没涉及到API呀

_Originally posted by @YangWaldon https://github.com/Kenshin/simpread/issues/3726_

**Comment by Kenshin** [comment]
@YangWaldon  @XMB-7 

嗨，各位，我把这个问题转移到这里了。

***

@XMB-7 可以试试不使用  **一键收藏小书签** 看看是否还存在此问题？

@YangWaldon 看起来跟 `simpread_config.json` 无关，确定只存在于  **一键收藏小书签** 吗？

**Comment by XMB-7** [comment]
我试试不用小书签, 是否还会出现这一问题. 我这边是看概率的, 不是用小书签就一定出问题, 所以可能需要测试几天. 
顺带发现浏览器插件的快捷键设置可能出问题了, 这四个里面只有打开稍后读好使, 其它三个设了都无响应, 当前环境win11 edge浏览器.
![image](https://user-images.githubusercontent.com/65625632/163359065-48f25450-d0a3-4a25-8877-91d696c0a19a.png)

**Comment by Kenshin** [comment]
@XMB-7 

> 我试试不用小书签, 是否还会出现这一问题. 我这边是看概率的, 不是用小书签就一定出问题, 所以可能需要测试几天.

没理解这句话的意思？这个 issues 是讨论小书签的问题，并仅限 **一键收藏**。

**Comment by XMB-7** [comment]
> 这个 issues 是讨论小书签的问题，并仅限 **一键收藏**

你能确定bug必然是由小书签导致的吗, 我只能说从我这边看, 最怀疑是由小书签引发的. 而且也并不仅仅是一键收藏的问题, 我也用了自定义生成的小书签, 结果依然出现了配置文件被覆盖的情况, 并不像另一位用户说的只有一键收藏才出问题.

**Comment by Kenshin** [comment]
@XMB-7

如果你遇到的问题是发生在使用小书签过程中的，当然是小书签的 Bug。

当然我只是说：如果你的问题跟小书签有关系，可以在这里讨论，否则的话，可以新开个 Issues 来讨论你的问题。

***

另外，目前除了 @YangWaldon 发现在操作小书签有配置覆盖情况外，我没有收到关于任何覆盖配置（误操作不算）的 Issues。

**Comment by XMB-7** [comment]
> 但是 一键收藏 小书签，每次点击它之后，都会把我的配置文件重置

这位用户的这个经历我这边没有. 我的问题是用了小书签之后, 绝大多数情况都是正常的, 只有小概率会把我的配置文件重置, 所以这会让我当场发现不了, 刻意几次剪藏一下检查一下, 都没有问题, 完了不定什么时候想打开稍后读了, 才发现配置文件被清空了.
而且这件事也很好验证, 我已经发了我的故障配置文件, https://www.bilibili.com/video/BV1E3411t7Wo, 十有八九就是收藏它才导致了配置文件被覆盖. 那你也试一下剪藏这个网址不就好了(记得备份配置文件), 目前我这边再次剪藏这个网址并不会使我配置文件被覆盖, 如果你的行为和我一致, 那就说明并不一定是小书签引发的bug, 起码跟那位用户所说的一试一个准并不相同.

**Comment by Kenshin** [comment]
> 而且这件事也很好验证, 我已经发了我的故障配置文件

发到我的信箱了？另外这个 https://www.bilibili.com/video/BV1E3411t7Wo  没有必要使用简悦的稍后读，也无法使用阅读模式。

> 那你也试一下剪藏这个网址不就好了(记得备份配置文件),

okay 我明天测试下。

> 我同样怀疑是同步助手的bug, 

同步助手不会有这种 Bug，它只负责存储，不负责改变任何内容。

**Comment by XMB-7** [comment]
> 发到我的信箱了？
你如果要, 我给你发也行, 一共就那么一行代码, 直接看不就完了么... 最重要的url就在图上, 剩下的信息跟其它正常条目又没有区别, 我也说了里面没有null.
> 另外这个 https://www.bilibili.com/video/BV1E3411t7Wo 没有必要使用简悦的稍后读
我有自己使用简悦的方式, 我习惯把关于同一主题的视频文章书籍等等集合在稍后读里, 然后再统一整理到ob之中.
> 同步助手不会有这种 Bug，它只负责存储，不负责改变任何内容
我只是提一个可能, 你如果确定本地端的配置文件和浏览器端的配置文件在一个对另一个同步覆盖的时候不会出这种问题, 那就排查其它方面, 小书签依然是最大的可能, 但根据我的使用经历, 起码不像那位用户说的那么好排查.

**Comment by Kenshin** [comment]
@XMB-7 

我不需要你的配置文件，我以为你的意思是发配置文件给我了。

至于排查的话，等我确认后会给你们反馈。

**Comment by XMB-7** [comment]
试了几天，暂时没有再发生配置文件被覆盖的问题。除了没再使用任何一种小书签，我还把配置文件的存储路径从onedrive挪出来了，不确定后者起了多大作用。

**Comment by XMB-7** [comment]
似乎偶然之间发现问题所在了, 用小书签添加B站视频至稍后读, 会覆盖掉配置文件, 试了两个视频, 我这边都可以稳定复现. 
但用快捷键是完全能正常将B站视频至稍后读的.
估计是小书签对某一类的网站支持出了问题, 不确定是否仅仅是B站, 然后用户有时候用快捷键, 有时候用小书签, 这才导致不能稳定复现.

**Comment by Kenshin** [comment]
@XMB-7 

谢谢测试。 💪 

> 用快捷键是完全能正常将B站视频至稍后读

是指什么情况？在原页面使用 `d d` 加入？

> 用小书签添加B站视频至稍后读, 会覆盖掉配置文件, 试

是每个 B站视频链接都这样吗？（我还没测试  😂

**Comment by XMB-7** [comment]
> 是指什么情况？在原页面使用 d d 加入？

是的.

> 是每个 B站视频链接都这样吗？

当时添加某一B站视频, 立即发现配置文件被覆盖, 然后我从浏览器端恢复配置文件, 随机又试了一个视频, 配置文件依然被覆盖. 然后再恢复, 再用`d, d`添加, 一切正常.

然而过了十分钟吧, 我忽然想到尝试再用小书签去添加其它B站视频, 但此时就无法复现这个bug了, 试了四个视频都能正常用小书签添加, 或许是进行过一次正常添加后就把某些异常给覆盖了. 因此只能提供一个大致思路, 或许测试B站视频更有可能触发这个bug.

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3734#issuecomment-1103457864

收到~

**Comment by XMB-7** [comment]
这回好像真碰到症结了. 只要连续添加稍后读, 就会出现配置文件被覆盖的问题. 比如打开三个网页, 对一个点小书签之后立即切换到第二个第三个再点小书签. 
感觉应该是当一个稍后读还没有添加完毕, 就收到添加第二个稍后读的指令时, 配置文件的写入就会出问题, 导致变成1kb.

**Comment by Kenshin** [comment]
@XMB-7 

> https://github.com/Kenshin/simpread/issues/3734#issuecomment-1107528027

快速添加确实（概率上）存在问题，因为小书签是读取物理文件再写入（跟数据库的方式完全不一样），所以当 `simpread_config.json` 稍大，加上快速保存会概率性保存失败的问题。

另外，这个问题跟 B站解析错误无关。

***

> https://github.com/Kenshin/simpread/issues/3734#issuecomment-1099064396

你提到的 B站问题应该是在解析时 URL 时出现了错误造成的，但我确实没有重现出来。

### 视频演示

1. 快速添加，但注意：一键收藏时有个窗口，需要等窗口保存成功自动关闭后再添加第二个（也就是你之前提到的快读保存问题的应对方案）

2. 视频中提到的三个链接 [链接1](https://www.bilibili.com/video/BV1E3411t7Wo) [链接2](https://www.bilibili.com/video/BV19i4y1U7jQ) [链接3](https://www.bilibili.com/video/BV1hT4y1D73m) 均为 B站，且我这边没有任何问题。

https://user-images.githubusercontent.com/81074/164953368-8f20fe94-33e4-4ff7-bc93-d35a974ec34e.mp4

至于我的 `simpread_config.json` **12.1MB** ，应该比一般用户都大些，也没有发生你提到的问题。

![image](https://user-images.githubusercontent.com/81074/164953435-1aadb333-7ba5-4cee-b183-8c8fee9a5d6d.png)

**Comment by Kenshin** [comment]
@XMB-7 

哦，忘记问了，这里还是没有回复我，还有此问题吗？

**Comment by XMB-7** [comment]
> 快速添加，但注意：一键收藏时有个窗口，需要等窗口保存成功自动关闭后再添加第二个

目前看症结就是这个. 在一个添加窗口尚未消失的2s范围里, 再用小书签去添加另一个稍后读, 就会同时往配置文件里写入多条数据, 就有概率导致数据丢失.
所以我换了使用小书签的方式,  现在一律弹出新窗口, 添加完就等弹窗自动小时并切回原页面, 这样就强制避免了在2秒内添加多个稍后读的情况, 然后这个问题就再也没出现过.
建议把这条注意事项直接写到使用文档里面, 同步助手的小书签部分.

**Comment by Kenshin** [comment]
> 目前看症结就是这个. 在一个添加窗口尚未消失的2s范围里, 再用小书签去添加另一个稍后读, 就会同时往配置文件里写入多条数据, 就有概率导致数据丢失.

okay 果然是这个问题。

> 所以我换了使用小书签的方式, 现在一律弹出新窗口, 添加完就等弹窗自动消失并切回原页面, 这样就强制避免了在2秒内添加多个稍后读的情况, 然后这个问题就再也没出现过.

 👍 

> 建议把这条注意事项直接写到使用文档里面, 同步助手的小书签部分。

已记录 https://github.com/Kenshin/simpread/discussions/3852

综上，我关闭此 Issues 了。

**Comment by YangWaldon** [comment]
可是我的情况呢？我从来没有在弹出的窗口消失之前再进行别的操作啊······，但是配置文件还是会被重置呀，“等待弹出的窗口关闭”这明显不是通用的问题解决办法吧

**Comment by Kenshin** [comment]
@YangWaldon 

建议

1. 是否稳定复现？还是某个  URL
2. 最好录屏给我。

**Comment by Kenshin** [comment]
@YangWaldon 

我的配置文件大概是 12mb ，使用此功能没问题。你的多大？

**Comment by YangWaldon** [comment]
12.3MB，之前我反应的关于API的问题，也是因为配置文件太大=

**Comment by Kenshin** [comment]
@YangWaldon

我在 Debug 小书签的功能，从代码分析角度只能重现 @XMB-7 的问题。

还是希望能给我视频看看具体什么问题。

**Comment by YangWaldon** [comment]
https://github.com/Kenshin/simpread/issues/3726#issuecomment-1098681462
👆面是我之前做过的测试，我觉的没有必要录视频了呀，上面的截图已经表明了每次操作一键收藏小书签，都会导致配置文件重置，录视频看到的也只是点击小书签，配置文件重置，然后我通过OneDrive的历史文件版本恢复，再点击小书签，又重置。跟在那个url或者网页下面操作没有关系

**Comment by XMB-7** [comment]
@YangWaldon 
你把本地同步断了试试. 先在浏览器侧添加几个稍后读, 再把同步打开, 看看本地配置文件是否异常, 如果没异常, 那就再把本地同步断了, 再添加几个稍后读, 再打开同步, 再看. 
最好找你确定出问题的网址试. 如果这么弄没事, 而始终保持同步开启有事, 那估计就还是"在一定时间范围内, 不能多次往配置文件里写信息"的问题.

**Comment by YangWaldon** [comment]
> 你把本地同步断了试试. 先在浏览器侧添加几个稍后读, 再把同步打开, 看看本地配置文件是否异常, 如果没异常, 那就再把本地同步断了, 再添加几个稍后读, 再打开同步, 再看.
最好找你确定出问题的网址试. 如果这么弄没事, 而始终保持同步开启有事, 那估计就还是"在一定时间范围内, 不能多次往配置文件里写信息"的问题.

好的我试试

**Comment by YangWaldon** [comment]
@Kenshin ① 按照上面的朋友的建议试了试，把同步助手断开，将当前网页加入到稍后读之后，再打开同步助手，将浏览器配置文件通过同步助手同步到本地，本地的配置文件不会重置
② 但是，如果在开启同步助手的情况下，使用“一键收藏”小书签，就会导致配置文件重置，**再重申一次，与具体网页无关，只要是使用这个小书签，无论什么网页，都会导致本地配置文件重置**  ⇢  录屏如下
③ API有问题我可以不用api，但是本地的稍后读都有问题的话，用起来真的很难受，比如我想保存一个网站到稍后读中，想把简悦的稍后读用作一个我自己的网站的收藏地，都不能方便地进行操作······

https://user-images.githubusercontent.com/49675185/168500983-b38e5f89-e62d-42de-84ac-629dbf2dd271.mp4

**Comment by Kenshin** [comment]
emmm

1. 你好像没有使用坚果云，而是 Onedrive？试试把 Onedrive 的同步功能暂停，或者把 `simpread_config.json` 转移到非 Onedrive 目录。

2. API 没有问题...

3. 小书签只是稍后读的一种加入方式，而不是唯一方式，所以稍后读当然可以正常使用 😂 大部分使用者都是在阅读模式中加入稍后读，一般来说小书签是给无法使用 Chrome 的用户准备的收藏稍后读方案。

4. 当 `simpread_config.json` 变为 1k 时，看看里面的内容是什么？

还有一个办法：把你的  `simpread_config.json`  发给我，我调试下看看是否是什么情况。

**Comment by YangWaldon** [comment]
刚才将配置文件的路径改成了非OneDrive路径之后，通过简悦同步助手将浏览器中的配置文件导出到了这个本地路径，尝试了一下小书签，在弹窗结束后配置文件依然被重置了，截图如下
![image](https://user-images.githubusercontent.com/49675185/168514634-06a98f13-b28b-465e-a950-62bfc37bf703.png)

**Comment by Kenshin** [comment]
okay 如果愿意的话，请把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3734

**Comment by Kenshin** [comment]
另外

1. 视频中只测试了一键保存。另外的方式，比如完整保存？
2. 试着从同步助手重新添加书签，然后再测试下。

**Comment by XMB-7** [comment]
我觉得吧, 小书签可能没问题, 是本地同步助手有问题.
昨晚刚发现一个问题, 标注明明做了却显示不出来, 然后点击也不跳转, 编辑也无用, 相当于不存在. 如果断开本地同步, 再进入同一页面, 则一个标注都不显示. 这充分说明标注信息就保存在本地的配置文件里, 而就是这个保存出了问题, 丢失了一部分数据.
![图片](https://user-images.githubusercontent.com/65625632/168517040-05a596a0-6c22-41fb-a35e-afb403f7065f.png)
我还在看是否能够复现这个问题, 如果能的话就提一个issue. 因为如果这个问题也是稳定出现的, 再结合小书签, 那我感觉基本是本地同步助手的同步功能出了问题.

**Comment by Kenshin** [comment]
> 标注明明做了却显示不出来, 然后点击也不跳转, 编辑也无用, 相当于不存在

这个问题跟同步助手无关，只是标注的问题。

**Comment by YangWaldon** [comment]
我在整理稍后读中的条目与文件夹中离线html文件的匹配，发现有好多离线html前面的序号都是重复的，下图只展示了一张截图，实际上还有很多其它重复的，这是为什么啊······
![image](https://user-images.githubusercontent.com/49675185/168758900-b218024f-399e-4af6-ba19-68bfc2f833de.png)

**Comment by YangWaldon** [comment]
而且我刚发现，我刚刚在阅读模式中做的标注，虽然产生了离线文件（一共四个，但是在稍后读中居然检索不出来这个条目），如下图所示，真的崩溃······
![image](https://user-images.githubusercontent.com/49675185/168760366-ea9da504-eddc-4bbb-9642-25c13c9f93b7.png)

**Comment by YangWaldon** [comment]
更加诡异的是，今天产生的离线html的序号居然处于昨天产生的html文件序号之间······
![image](https://user-images.githubusercontent.com/49675185/168761611-5d280304-74be-4082-b9da-f6c9c1d2b599.png)

**Comment by Kenshin** [comment]
@YangWaldon 

这是已知 Bug

1. 当删除稍后读时，不会删除本地 HTML
2. 假设被删除稍后读的序号如果是 1234，新添加的稍后读序号仍是 1234

> 这个问题会在下个版本解决。

同步助手会解决 `1234-title1` 和 `1234-title2` 的重复性问题。

![image](https://user-images.githubusercontent.com/81074/168762970-de03e5fa-6d25-4ea7-82c0-b41bfb3381a5.png)

**Comment by YangWaldon** [comment]
下个版本什么时候更新？

**Comment by YangWaldon** [comment]
更新的时候会不会给一个功能，自动检查一遍文件夹中有哪些html文件是废弃的，然后给一个删除的选项？

**Comment by YangWaldon** [comment]
> @YangWaldon
> 
> 这是已知 Bug
> 
> 1. 当删除稍后读时，不会删除本地 HTML
> 2. 假设被删除稍后读的序号如果是 1234，新添加的稍后读序号仍是 1234
> 
> > 这个问题会在下个版本解决。
> 
> 同步助手会解决 `1234-title1` 和 `1234-title2` 的重复性问题。
> 
> ![image](https://user-images.githubusercontent.com/81074/168762970-de03e5fa-6d25-4ea7-82c0-b41bfb3381a5.png)

我想了下，这个说法解释不了为什么我明明进入阅读模式，也做了标注，离线文件也产生了，但是稍后读中检索不出来这个条目的问题，这不是一个bug

**Comment by Kenshin** [comment]
@YangWaldon 

1. 这篇文章是不是被存档了？
2. 试试搜索 `计时器`

还有... 我有 2xxx 个稍后读，也没出现一个这样的问题，甚至于都没有一个用户问跟你类似的问题。😂

![image](https://user-images.githubusercontent.com/81074/168787419-db37feaf-30e8-4942-89f1-71036618d353.png)

另外，搜索的话，建议更适合的工具，如 `Anytxt` 等。

**Comment by Kenshin** [comment]
还有，我也感慨下，这个 Issues（你们两个）遇到的问题，是全部 `3+K` Issues 最难缠的。😂

很少出现，这么频繁的隐性 Bug
