### ISSUE TITLE
在阅读模式下，打开稍后阅读中的文章，显示正文解析失败，如果开启了 内置解析方案 的话，请多刷新几次一般可以解决。请问内置解析方案如何开启

### ISSUE THREAD

**Issue by santiagoTOP** [Kenshin/simpread#3736]

**Comment by santiagoTOP** [comment]
在阅读模式下，打开稍后阅读中的文章，显示正文解析失败，如果开启了 内置解析方案 的话，请多刷新几次一般可以解决。请问内置解析方案如何开启

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/3712
