### ISSUE TITLE
[功能请求] 优化对代码块的高亮标注的连续视觉显示

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3738]
目前的显示效果
![图片](https://user-images.githubusercontent.com/65625632/163501421-92f4b5a8-82f7-4787-81d9-020d7cf224aa.png)

期待的显示效果
![图片](https://user-images.githubusercontent.com/65625632/163501689-26c5b0c0-a85c-4188-a634-7154159dca28.png)

**Comment by Kenshin** [comment]
更换个主题试试。

**Comment by XMB-7** [comment]
什么主题, 浏览器的主题吗?
我通过本地助手打开的稍后读也这样.
![图片](https://user-images.githubusercontent.com/65625632/163510387-d45458af-a902-4f46-a637-630bd64abea2.png)
我发的第二个图片并不是简悦的标注. 所以你那边的简悦标注对代码块是连续显示的, 而我这边是断裂的?

**Comment by Kenshin** [comment]
> 你那边的简悦标注对代码块是连续显示的, 而只有我这边才是断裂的?

具体问题（URL）具体分析，不一定。

***

但通过第二个截图来说，我大概知道问题了，因为这个断裂的是个 独立的 html 标签，在标注时有一些「算法」导致这种情况，我看看如何优化。

**Comment by XMB-7** [comment]
感谢. 读代码文档的时候, 里面代码块用的特别多, 如果高亮全都是断裂的, 视觉效果就很差. 尤其是一行里面好几个代码块的情况, 高亮完基本就没法看了.

**Comment by Kenshin** [comment]
看了下这个页面，这不是标注的问题，而是纯粹的主题问题，一般来说，为了更好的显示行内代码段，主题都会对做一些样式设置。

可以通过 [自定义样式](https://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决

![image](https://user-images.githubusercontent.com/81074/163520284-525c41b1-a852-4ca2-8c04-130c6ea6d1c6.png)

```
sr-rd-content li code, 
sr-rd-content p code {
    padding: 0;
    margin: 0;
    border: 0;
}
```

但这么做，全部类似的代码都没有「隔开」的效果了。

**Comment by XMB-7** [comment]
了解了, 我研究一下css. 请问css有办法设置成第二张截图那样么, 既保留代码块的显示, 又没有让高亮断裂.
![图片](https://user-images.githubusercontent.com/65625632/163524519-ae992e56-8994-4425-a643-2be585008c21.png)

**Comment by Kenshin** [comment]
你可以试试 `background-color: xxxx` 但可能仍需要再调整 CSS 语法。

**Comment by XMB-7** [comment]
> 具体问题（URL）具体分析，不一定。

请问有没有简悦能够正常显示代码块标注的url, 目前我好像还真没遇到过能正常显示的, 如果有的话, 那我似乎可以照着抄它的css代码.
