### ISSUE TITLE
求助 已经打开了客户端，但仍然不能完成验证

### ISSUE THREAD

**Issue by xigua222** [Kenshin/simpread#3746]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/52056870/163670916-b0b2439b-9be6-4f82-8dee-3df8d69c61c5.png">
求助 已经打开了客户端，但仍然不能完成验证

**Comment by Kenshin** [comment]
嗨，有以下几个方案，你可以试试

1. https://github.com/Kenshin/simpread/discussions/1567

2. 如果是首次升级成为高级账户的用户，需要重启浏览器，或者使用 https://github.com/Kenshin/simpread/discussions/2816 此方式，确保你的账户真的为高级账户。

我能想到的造成此问题的就只有这两个情况。

**Comment by xigua222** [comment]
尝试1567的方案解决了，非常感谢您！

**Comment by Kenshin** [comment]
Cool 搞定就好，我关闭这个 Issues 了，遇到常规性问题，可以直接检索 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5)，一般都能 100% 解决。
