### ISSUE TITLE
邮件服务无法绑定

### ISSUE THREAD

**Issue by unixq** [Kenshin/simpread#3747]
Hi Kenshin，我用outlook邮箱成功绑定了高级账户。但是在设置邮件服务，试图尝试邮件导出以及每日回顾的过程中，发现屡屡失败。我尝试了使用gmail和outlook作为发件箱，因官网找不到SMTP登录密码作罢。现在尝试用qq邮箱（follow你的教程）+开通了IMAP/SMTP服务授权码。但是对应的收件箱里还是收不到邮件导出以及每日回顾的内容，作为发件箱的QQ邮箱里也没有对应的邮件。请问还有什么办法可以使用邮件的功能？谢谢！

**Comment by Kenshin** [comment]
嗨，你可以根据每日回顾的 [配置教程](https://kb.simpread.pro/#/page/%E6%AF%8F%E6%97%A5%E5%9B%9E%E9%A1%BE) 自查下，简单的说，如果收到 Email 的话，需要保证：

1. 坚果云的授权
2. 坚果云中的数据 simpread_config.json 是24小时内有内容的。（一般使用同步助手 + 坚果云）
3. Email 的相关信息正确

**Comment by Kenshin** [comment]
okay 搞定就好~  👍
