### ISSUE TITLE
保存到onenote的博文，原来文章中代码的颜色为什么没有呢

### ISSUE THREAD

**Issue by elmmmm** [Kenshin/simpread#3748]
保存到onenote的博文，原来文章中代码的颜色为什么没有呢？颜色一起要是能一起保存了多好~

**Comment by Kenshin** [comment]
嗨，这个不是简悦的问题，导入到 Onenote 的内容并不受到简悦的控制。  😂 

不过，好奇问问，可以手动后续在 Onenote 中修改吗？
