### ISSUE TITLE
simpread_config.json文件同步异常

### ISSUE THREAD

**Issue by faivny** [Kenshin/simpread#3755]
高级账户,简悦 2.2.0 版本,mac 平台
mac 本地使用同步助手,本地同步与网页端同步配置没有问题,当网页端修改任意配置都可及时同步.
网页端与坚果云貌似没有自动同步,等待时间半小时左右,我决定本地,网页,坚果云三方是不是应该都是可以及时同步的?还是我哪里的设置有问题.
手动使用坚果云同步时,点击强制覆盖配置文件到坚果云,结果是本机文件被坚果云上的simpread_config.json覆盖...

另使用自动化中遇到的问题.
自动化动作, 添加到稍后读时,同步文件导离线 markdown.但是没有反应,设置成手动,然后点击时可以的.能否帮忙解释一下?

**Comment by Kenshin** [comment]
- 自动同步
- 同步助手
- 坚果云

同时开启，就没有问题。不要以选项页 → 共通，里面的时间为参考，以本地 simpread_config.json 与坚果云 Web 端里面的时间为一致就可以。

**Comment by faivny** [comment]
更新时间和现象倒是匹配的, 但是里头的数据不对的, 比如, 我在本地收藏了文章, 那么本地的 json 立刻更新了:
问题是:
1. 坚果云长时间没有更新.
2. 没有触发自动化.

**Comment by Kenshin** [comment]
1. 这个就要看你的坚果云了，这个没办法控制。如果你的 simpread_config.json 变化的话，坚果云肯定是秒传。
2. 使用快捷键 `d d` 或右键菜单加入没问题，细节看 https://github.com/Kenshin/simpread/discussions/2362

**Comment by faivny** [comment]
问题 2使用快捷键可以了,
问题 1, 我之前以为是需要利用简悦网页中设置的坚果云 webdev 就可以自动化地进行同步了,发现其实我需要在本地设置坚果云的客户端,然后同步助手的同步路径指向这里. 这样确实是多端自动同步了.
但是有了一个新问题.

我在 iphone 上利用快捷方式收藏,收藏文章自动加入simpread_config.json后,这种方式是没有办法触发自动化地, 而我需要在此时调用自动化将文章全文放到 kindle 和本地 obsidian 中,这个触发动作是否合理?需要进行多余的配置么?或者有别的办法实现此自动化?

**Comment by Kenshin** [comment]
> 我之前以为是需要利用简悦网页中设置的坚果云 webdev 就可以自动化地进行同

哈哈，我在 https://github.com/Kenshin/simpread/issues/3755#issuecomment-1101413955 已经明确说了三个步骤缺一不可。

> 我在 iphone 上利用快捷方式收藏,收藏文章自动加入simpread_config.json后,这种方式是没有办法触发自动化地, 而我需要在此时调用自动化将文章全文放到 kindle 和本地 obsidian 中,这个触发动作是否合理?需要进行多余的配置么?或者有别的办法实现此自动化?

自动化行为是扩展端行为，不支持服务器端行为。后续会考虑一定的服务器端行为，但从技术角度没法做到跟扩展端一样好用，即便做的话，顶多算「能用」。

还有一点：简悦的首选使用方案是希望用户可以在 PC 做深度阅读，所以一切功能都是围绕这个思路进行的，通过 API 在各种端收藏，汇总到简悦，在 PC 做深度阅读，有必要时标注并自动导入到你需要的笔记。

非 PC 端再如何，也没办法做到 PC 这样的方便。

**Comment by faivny** [comment]
嗯, 这个思路我可以理解, 我的深度阅读会在两个地方, 1 是 PC,2 是 kindle, 我决定给自己增加一个流程,在手机端收藏的文章, 在稍后读中再进行一次过滤,我已经试过了, 在这个窗口直接调用自动化按钮又可以了.

这样的话, 如果我能在 PC 上查看完毕的, 就查看完成. 当然我在 PC上大部分时候并不能专心查看...
那么我就再在稍后读里挨个过滤一下我真的要发送到 kindle 读的文章,目前感觉也可以接受.

此问题可以关闭.

**Comment by Kenshin** [comment]
> 在稍后读中再进行一次过滤,我已经试过了, 在这个窗口直接调用自动化按钮又可以了.

只要是在扩展端端就可以使用自动化（你可以将某些自动化设置为一个特殊服务，如何使用 [看这里](https://github.com/Kenshin/simpread/discussions/2151)
