### ISSUE TITLE
简阅safari的扩展可否通气一下开发进度

### ISSUE THREAD

**Issue by hellozgl** [Kenshin/simpread#3756]
使用简阅很久了，一直对阅读模式赞不绝口。但由于mac系统下，使用safari相比edge和chrome而言都流畅很多，对系统占用也很低，所以一直想将插件迁移到safari中来，搜索了一下作者的issues，发现safari在开发过程中，但不知能否先行放出safari的插件，这对广大苹果用户而言是一大好消息。也不知道现在开发到什么进度了，能否通气一声用户呀。
简阅在油猴上的脚本，轻量版基本没有什么效果。所以很迫切地希望safari扩展尽快推出。作者辛苦，加油。

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦，别急。

如果有能使用的话，我会优先给这里的用户。
