### ISSUE TITLE
怎么用安卓手机访问收藏助手

### ISSUE THREAD

**Issue by wannaAC** [Kenshin/simpread#3757]
如题，看那个https://github.com/Kenshin/simpread/discussions/2921#discussioncomment-1505901 wiki还是没明白在哪安装，我的id和token在哪里查看

**Comment by Kenshin** [comment]
嗨，[看这里的教程](https://kb.simpread.pro/#/page/%E6%94%B6%E8%97%8F%E5%8A%A9%E6%89%8B) 

需要开通 [开放平台](https://kb.simpread.pro/#/page/%E5%BC%80%E9%80%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)
