### ISSUE TITLE
提供的简阅助手下载链接一个都打不开

### ISSUE THREAD

**Issue by tcigvl** [Kenshin/simpread#3758]
就是提供的简阅助手下载链接一个都打不开，有其它途径吗？
或者邮箱发一个？
286790168@qq.com

- 操作系统 **Win10**

- 浏览器版本 **edge**

- 简悦版本 **...**

- 发生问题的地址 <chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**Comment by Kenshin** [comment]
嗨，都好使的。

[腾讯微云](https://share.weiyun.com/S8C1bxJ7) 提取码：pqaytk

![image](https://user-images.githubusercontent.com/81074/163909775-500279f9-092b-4a3e-a26d-1d6ac08f416f.png)

**Comment by tcigvl** [comment]
这个我只能说确实打不开，找了好几个人帮忙试了下也不行。应该是微云的锅，我自己分享出去的都打不开！！！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Kenshin Wang ***@***.***>
发送时间: Tuesday, April 19, 2022 10:43:54 AM
收件人: Kenshin/simpread ***@***.***>
抄送: tcigvl ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 提供的简阅助手下载链接一个都打不开 (Issue #3758)


嗨，都好使的。

腾讯微云<https://share.weiyun.com/S8C1bxJ7> 提取码：pqaytk

[image]<https://user-images.githubusercontent.com/81074/163909775-500279f9-092b-4a3e-a26d-1d6ac08f416f.png>

―

**Comment by Kenshin** [comment]
没问题，隐身登录可以打开且下载。

![image](https://user-images.githubusercontent.com/81074/163918577-f45fa9fb-c22e-4e74-b34b-283f23c85282.png)
