### ISSUE TITLE
同步助手打开稍后读的快捷键Ctrl+Shift+N与Windows文件资源管理器产生冲突

### ISSUE THREAD

**Issue by pzzzling** [Kenshin/simpread#3759]
**请说明发生问题的环境**

- 操作系统 Windows 10

- 浏览器版本 Edge 100.0.1185.44

- 简悦版本 2.2.0.520

同步助手打开稍后读的快捷键Ctrl+Shift+N与Windows文件资源管理器新建文件夹的快捷键冲突，这会导致同步助手打开时无法在资源管理器里面使用Ctrl+Shift+N新建文件夹……

请问可以提供一个修改快捷键的功能吗

![image](https://user-images.githubusercontent.com/39448739/163917173-326f8a1f-94fe-4c64-b365-07e2fa569fad.png)

**Comment by Kenshin** [comment]
可以的

![image](https://user-images.githubusercontent.com/81074/163918756-1ae18f1b-cf0e-4b8b-b7c4-540d06b7a5f6.png)

但你的截图没有这个 icon，能否确保网络畅通？然后重启同步助手，再试试。

**Comment by pzzzling** [comment]
您好，还是不行……已经确认网络是畅通的，还是无法修改快捷键

**Comment by pzzzling** [comment]
之前发现无法自动导出，检查了一下发现没有在扩展里面配置好同步助手，现在已经配置好了但还是无法修改快捷键

**Comment by Kenshin** [comment]
确定能正常访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css 吗？

**Comment by pzzzling** [comment]
不好意思……可能是我这边网络的原因，cloudflare没法正常访问（直接拒绝连接了）
设置代理之后就好了，非常感谢~

**Comment by Kenshin** [comment]
okay 小事情，下个版本会改为国内版本，我也没想到会涉及到 `cloudfoundry.com`  😂
