### ISSUE TITLE
这个页面保存到印象笔记失败

### ISSUE THREAD

**Issue by geewit** [Kenshin/simpread#376]
https://blog.csdn.net/wangjunsheng/article/details/80921824

**Comment by Kenshin** [comment]
这是有两个问题造成的：

- 某些不被 Evernote 识别的 标签没有被正则掉；
- post 过去的数据太大（因为用了免费的后台，有 size 限制）

第一个问题在 1.1.2 会被解决掉。
第二个问题只能等到自建服务器时才能解决；

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，重构了 【导出到 印象笔记】的代码，基本上解决了导出总是失败的问题。

同时增加了当导出失败时，以 **Markdown 格式 二次保存** 及 提交到 **待决站点机制** ，确保万无一失。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
