### ISSUE TITLE
[Feature]支持 Flowus

### ISSUE THREAD

**Issue by ajiangstudy** [Kenshin/simpread#3765]
请问会支持flowus吗，最好可以支持flowus的图床，近期有如此打算吗

**Comment by Kenshin** [comment]
嗨，会考虑的。

**Comment by sherlockmj** [comment]
好期待flowus，带时候自动化，notion一份flowus一份就真正放心了

**Comment by Kenshin** [comment]
嗨，我需要重新打开这个 Issues。  😀

**Comment by sherlockmj** [comment]
大概什么时候会支持呀，急！！！

**Comment by kezi000** [comment]
同求，期待支持flowus

**Comment by ChaoSSSSSSSSSSS** [comment]
> 嗨，我需要重新打开这个 Issues。 😀

希望能将新的双链体系结合上。

**Comment by yaleimeng** [comment]
同期待中。notion的本地文件导入太差了，各种图片丢失。flowus本地md和html的zip包导入都很棒。

**Comment by Xrkorz** [comment]
催一下

**Comment by Kenshin** [comment]
嗨，各位，忘记通知大家了。

导入到 FlowUs 已经发布了，以下是相关内容：

***

为了照顾新用户，简悦推出的教程，含：简悦扩展端下载、购买高级账户、绑定高级账户、安装导入到 FlowUs 插件、授权、使用的全过程。

## 地址

https://flowus.cn/share/4a925a4f-1830-4988-9c89-ba91aaeb5429

## 简悦 与 FlowUs 的联动玩法汇总：

1️⃣ [适配 FlowUs 文章页与分享页](https://zhuanlan.zhihu.com/p/591720721)

2️⃣ [导入到 FlowUs](https://zhuanlan.zhihu.com/p/591724904)

3️⃣ [配置库（已包含上面两个用法）](https://www.yuque.com/kenshin/simpread/tyar733q5gfbgw8g)

## 📺 视频

[知乎视频](https://www.zhihu.com/zvideo/1586342219220520960) | [B 站](https://www.bilibili.com/video/BV1MP4y1Q7iE)
