### ISSUE TITLE
新站适配：百度百家号

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3767]
### Discussed in https://github.com/Kenshin/simpread/discussions/3766

<div type='discussions-op-text'>

<sup>Originally posted by **zhoujunxuan** April 20, 2022</sup>
在尝试从[百家号文章](https://baijiahao.baidu.com/s?id=1664363697286264009)中获取内容时，发现图片无法获取

原始网页如下
![image](https://user-images.githubusercontent.com/37800586/164185243-4802bb03-176b-4e33-b05f-9e0762fed2d1.png)

阅读模式如下
![image](https://user-images.githubusercontent.com/37800586/164185354-f4da86b9-d48f-40c0-8d67-0c6ad3515545.png)

测试浏览器为：edge
浏览器版本号：100.0.1185.39 (正式版本) (64 位)

大佬有空帮忙看下这个网站，谢谢</div>

**Comment by Kenshin** [comment]
@zhoujunxuan

嗨，我帮你新建了一个 Issues 转移到这里并删除了原来位置的内容。

***

可能是这个页面的结构发生改变造成的，我会重新适配的。

目前可以使用下图的方式临时解决

![image](https://user-images.githubusercontent.com/81074/164189715-254f65c5-610a-445b-8ef5-1b80ec8de77c.png)

**Comment by zhoujunxuan** [comment]
我试了下，选中后，选择"将选中内容生成阅读模式"页面没反应

**Comment by liang2214** [comment]
我这样整了下，能显示图片了

![屏幕截图 2022-10-10 225908](https://user-images.githubusercontent.com/95778719/194897148-9d99e6a8-52bd-40ad-a4fa-fd9375126cd8.png)

**Comment by Kenshin** [comment]
嗨，这个站点已更新，请通过 https://github.com/Kenshin/simpread/discussions/2870 更新，并留意下图的说明

![SCR-20230330-pa8](https://user-images.githubusercontent.com/81074/228804557-dd38e20a-662c-4b91-b299-444ae67eca5f.png)
