### ISSUE TITLE
请求支持 MathJax 解析，请求适配 IEEE

### ISSUE THREAD

**Issue by linsui** [Kenshin/simpread#377]
MathJax 只能显示源码，无法渲染，希望可以增加这一功能

**Comment by Kenshin** [comment]
可以考虑加一个，搞定后会通知你。

**Comment by Kenshin** [comment]
嗨，今天研究了下 MathJax 的问题，目前暂时无法用 插件的方式解决，但可以通过以下的方案完美解决：

- 进入阅读模式；
- 右侧控制栏 → 动作 → 设定 → 重新选择高亮

即可解决。

造成的原因是：MathJax 在生成公式时会有个 Delay 而在生成阅读模式时，还未生成公式。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

例如 https://github.com/Kenshin/simpread/issues/412 即是解析 LaTeX 后的效果。
