### ISSUE TITLE
合辑跨电脑无法同步问题

### ISSUE THREAD

**Issue by gujin03** [Kenshin/simpread#3773]
- 操作系统 **Windows10**

- 简悦版本 **2.2.0**
我在Mac上编辑了合辑信息，mac和win上同时都正常使用同步助手+坚果云客户端的情况下
<img width="273" alt="image" src="https://user-images.githubusercontent.com/38389059/164453343-201faf43-e338-4f16-88aa-6e5e56f1e674.png">
在win上是看不到这个合辑的，simpread_config.json这个文件两台电脑也是保持同步的，那么问题来了，这个合辑数据到底是保存在哪里的呢？如何才能实现同步呢？谢谢。

**Comment by Kenshin** [comment]
可以先自查下：

1. 看看下图的内容是否开启？
2. 进入稍后读后，右键 → 检查，看看有没有报错？

   ![image](https://user-images.githubusercontent.com/81074/164584249-6e81e8d9-860a-4cc0-be58-7fe134710e1b.png)

3. 如果还是不行，先保留配置文件，重新安装有问题的那台设备，然后通过下图导入。

   ![image](https://user-images.githubusercontent.com/81074/164584450-689cb4f9-8a97-459e-9cd6-084b6019bf8d.png)

**Comment by gujin03** [comment]
重置后解决了

**Comment by Kenshin** [comment]
搞定就好。
