### ISSUE TITLE
导出模板，循环{{#each}}没有识别

### ISSUE THREAD

**Issue by Alexzz96** [Kenshin/simpread#3777]
我是想导入obsidian，用ob的标注块视觉上区分一下。
但是发现，标识循环的没有触发，是哪里不对吗？

# 导出

```
> [!example]- 参考资料
> - [! 原文地址 [{{host}}]({{url}})
> - 标签 ：{{tags}} 
> - 建立时间：{{create}}
> - 关联阅读：{{> |backlinks}}
> -  外部引用：{{> |refs}}

> [!quote]- 概览
> - {{desc}}

***

{{#each}}

> [!info]- 信息 
> - 时间：{{an_create}}
> - 标签：{{an_tags}}
> - 引用： [{{an_text}}](<{{an_ext_uri}}>)
> - 链接
> 	-  [原链接](<{{an_org_uri}}>)
> 	- [内部链接](<{{an_int_uri}}>)
> 	- [外部链接](<{{an_ext_uri}}>)

> [!abstract]+ 原文
>- {{  >|an_html}}

> [!TIP] 备注
> - {{note}}

***

{{/each}}
```

**Comment by Kenshin** [comment]
嗨，看起来没问题，但你提交时的结构不对，我帮你整理了下，但不确定是否是你那边的模板。

另外，这是 [模板库](https://github.com/Kenshin/simpread/discussions/2153)，里面不少案例，你可以参考下。

**Comment by Kenshin** [comment]
emmm  看起来感觉像放错位置了，正确的位置看下图的位置

![image](https://user-images.githubusercontent.com/81074/164702798-499963b1-7eab-4216-a191-3138d1bf3af8.png)

**Comment by Alexzz96** [comment]
不会呀 我就是放这里的，难道还有别的问题会导致导出失败么。
![image](https://user-images.githubusercontent.com/103805220/164708189-ec3da98a-7edc-4a6d-ba35-043997ced914.png)

**Comment by Kenshin** [comment]
我明天试试你的模板。

另外，你可以试试模板库里面的模板，看看如何。

**Comment by Alexzz96** [comment]
> 我明天试试你的模板。
> 
> 另外，你可以试试模板库里面的模板，看看如何。

谢谢 模板库里的是可以的，之前我用的就是模板库，最近在自定义导出。

**Comment by lyserenity** [comment]
> 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/32646062/164743374-7bdb16a6-dc50-4a9c-87b8-e1a2564bf4eb.png">

 在 ``{{#each}}`` 里要用 ``{{an_note}}``。不过依旧有 bug ，猜测可能是占位符跟某些符号交互出现了问题，所以我直接帮改了一份（测试过了）：

 ```
> [!example]- 参考资料
> - [! 原文地址 [{{host}}]({{url}})
> - 标签 ：{{tags}} 
> - 建立时间：{{create}}
> - 关联阅读：{{> |backlinks}}
> -  外部引用：{{> |refs}}

> [!quote]- 概览
> - {{desc}}

***

{{#each}}

> [!info]- 信息 
> - 时间：{{an_create}}
> - 标签：{{an_tags}}
> - 引用：[{{an_text}}](<{{an_ext_uri}}>)
> - 链接
>    - [原链接](<{{an_org_uri}}>)
>    - [内部链接](<{{an_int_uri}}>)
>    - [外部链接](<{{an_ext_uri}}>)

> [!abstract]+ 原文
{{  > - |an_html}}

> [!TIP]  备注：
{{  > - |an_note}}

***

{{/each}}
```

**Comment by Alexzz96** [comment]
> > 
> 
> <img alt="image" width="399" src="https://user-images.githubusercontent.com/32646062/164743374-7bdb16a6-dc50-4a9c-87b8-e1a2564bf4eb.png">
> 
> 在 `{{#each}}` 里要用 `{{an_note}}`。不过依旧有 bug ，猜测可能是占位符跟某些符号交互（或是某处）出现了问题，所以我直接用你的模版帮改了一份（测试过了，但格式可能会有部分出入，可能需要自行调整）：
> 
> ```
> > [!example]- 参考资料
> > - [! 原文地址 [{{host}}]({{url}})
> > - 标签 ：{{tags}} 
> > - 建立时间：{{create}}
> > - 关联阅读：{{> |backlinks}}
> > -  外部引用：{{> |refs}}
> 
> > [!quote]- 概览
> > - {{desc}}
> 
> ***
> 
> {{#each}}
> 
> > [!info]- 信息 
> > - 时间：{{an_create}}
> > - 标签：{{an_tags}}
> > - 引用：[{{an_text}}](<{{an_ext_uri}}>)
> > - 链接
> >    - [原链接](<{{an_org_uri}}>)
> >    - [内部链接](<{{an_int_uri}}>)
> >    - [外部链接](<{{an_ext_uri}}>)
> 
> > [!abstract]+ 原文
> {{  > - |an_html}}
> 
> > [!TIP] 备注：
> {{  > - |an_note}}
> 
> ***
> 
> {{/each}}
> ```

确实可以了，谢谢。估计是哪里写的不对 哈哈哈

**Comment by Alexzz96** [comment]
大佬 有一个排版上的小问题请教一下
当我用这种格式，{{desc}} 描述会把部分内容排到ob的标注格式之外，这个有办法解决吗？

下图是导入前后

![image](https://user-images.githubusercontent.com/103805220/164861543-3fe536f8-ee44-4213-b0a1-2577e379b66e.png)
![image](https://user-images.githubusercontent.com/103805220/164861532-1857056d-5287-4b57-a901-7ffbcf23c8a2.png)

**Comment by lyserenity** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/32646062/164862828-42795f49-5b61-4dfd-80eb-f3705eba6c56.png">

你可以用 ``{{> - |desc}}`` 试试看，因为我没有在用 ob ，所以不好测试 😂

**Comment by Kenshin** [comment]
@Alexzz96 

嗨，如果有因模板结构导致的问题，暂时可以忽略，下周有个新方案，可以更好的使用 Markdown 定制化模板。

**Comment by Alexzz96** [comment]
> @Alexzz96
> 
> 嗨，如果有因模板结构导致的问题，暂时可以忽略，下周有个新方案，可以更好的使用 Markdown 定制化模板。

好的大佬 等下周了 
基本上模板的问题就是，复制进来的文本格式会误触markdown换行啊，引用啊这类。

**Comment by lyserenity** [comment]
> > @Alexzz96
> > 嗨，如果有因模板结构导致的问题，暂时可以忽略，下周有个新方案，可以更好的使用 Markdown 定制化模板。
> 
> 好的大佬 等下周了 基本上模板的问题就是，复制进来的文本格式会误触markdown换行啊，引用啊这类。

这个问题应当下周能解决，墙裂推荐订阅 https://simpread.pro/subscribe，「拦截」第一手消息 ！

**Comment by Kenshin** [comment]
嗨，Markdown 模板定制化 2.0 发布了，详细 [请看这里](https://github.com/Kenshin/simpread/discussions/3725)。

特点
---

- 可完美的支持 Obsidian · Logseq 等任意双链笔记的语法规则，细节请看 [模板库](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)

- 内置 [EJS 引擎](https://ejs.co/#docs) ，所以可以使用 EJS 引擎全部的功能。

- 可在模板中直接编写 Javascript 代码。

- 所见即所得，相比 1.0 在模板中去掉空格或无法空格等问题，2.0 无此问题。

- 兼容 1.0 的 [语法规则](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=markdown)（占位符）。

- 兼容 1.0 [模板](https://github.com/Kenshin/simpread/discussions/2153)。

如何使用
---

> **2.0 仅提供模板解析方案，并未提供导出方案**，所以需要跟插件配合使用，**接下来还会陆续增加更多插件**。

下面的插件均可配合 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件实现自动化方案。

- [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

- [导出 org-mode 文件](https://github.com/Kenshin/simpread/discussions/3775)

安装后需要开启下图所示的选项才可使用

![image](https://user-images.githubusercontent.com/81074/165034089-a8e2987e-7947-4bdc-89e4-5d743fff1f47.png)

模板库
---

- [Obsdian 模板之一](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311)

- [Obsdian 模板之二](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627313)

- [Logseg · Markdown 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627315)

- [Logseg · org-mode 版](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627320)

更多模板，[请看这里](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600)。

模板截图
---

![](https://imgs.zhubai.love/230c79c30d8c47f88c6cd659e2916b1a.png)

![](https://imgs.zhubai.love/831d361aa3bf4c9e90f3fca0cbb681bc.png)
