### ISSUE TITLE
『稍候读』自动化导出到 obsidian 的问题

### ISSUE THREAD

**Issue by xQmQ** [Kenshin/simpread#3778]
## 描述

根据 #2902 以及[知乎文章](https://zhuanlan.zhihu.com/p/501251603)设置有关稍候读及标注的自动化导出，然后进行以下操作

1. 打开阅读模式，加入『稍候读』
2. 点击『稍候读』的编辑，添加标签 or 备注等
3. 对内容划线进行标注

执行 1 操作，正常，ob 里生成对应文件，有正确的内容

![image](https://user-images.githubusercontent.com/56010105/164705152-d6313ac3-e7ef-4620-b5d7-90a855446120.png)

执行 (1 && 2) || (1 && 3) 操作后，ob 里 对应文件存在，但是所有内容被清空

![image](https://user-images.githubusercontent.com/56010105/164705193-87e979cc-20ee-4c3b-9b66-5fc93d6a975a.png)

## 关于我的设置

![image](https://user-images.githubusercontent.com/56010105/164703090-7afd9df1-600f-4cb7-8eb4-f9cbe721b5ed.png)

![image](https://user-images.githubusercontent.com/56010105/164703561-b7bcd256-300e-4475-9095-19a31ccd14dc.png)

![image](https://user-images.githubusercontent.com/56010105/164704489-f33180db-e47d-4afa-9798-bef57d2a5a1f.png)

**Comment by xQmQ** [comment]
## 我的需求

当执行 **加入稍候读 || 修改稍候读的信息 || 添加标注 || 修改已有标注** 的时候，可以自动导入到 ob 中

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3778#issuecomment-1106423908

当然，这个插件就是做这个事情的。

***

至于你提到的问题，肯定是不存在的，但不排除是某些 Bug 引起，明天确认下。

另外，方便的话，可以先自查下：

1. 加入稍后读时，使用快捷键 `d d`，
2. 然后开始标注（先不要使用标注编辑功能），只是单纯的标注

看看能否正常？（只是测试而已）

另外，你提到的问题能否稳定复现？如果还是不行的话，建议录屏给我看下。

**Comment by xQmQ** [comment]
我这里可以稳定复现。因为我的 edge 浏览器上有 vim 插件，所以 dd 快捷键用不了，一直用『右键菜单』的方式加入稍候读

这个视频我关闭了 vim 插件，并根据你提供的步骤，经过多次尝试，都可以复现

（原视频太大了，压缩以后画质不太好）


https://user-images.githubusercontent.com/56010105/164711018-c980f64d-c8c7-43df-bf4b-6581631cc003.mp4

**Comment by Kenshin** [comment]
好，我明天试试。

**Comment by 1wingedangel** [comment]
我猜测是因为导出文件名里不含有占位符{{mode}}，导致添加标注的时候 `导出全文到Obsidian` 和 `导出标注到Obsidian` 这两个自动化操作出现了冲突导致。添加 {{mode}} 占位符后 obsidian 里会出现全文和标注两个md文件，就不会被清空了。

**Comment by xQmQ** [comment]
> 我猜测是因为导出文件名里不含有占位符 `{{mode}}` ，导致添加标注的时候 `导出全文到Obsidian` 和 `导出标注到Obsidian` 这两个自动化操作出现了冲突导致。添加 `{{mode}}` 占位符后 obsidian 里会出现全文和标注两个md文件，就不会被清空了。

我当初删除占位符`{{mode}}`是因为自动化导出全文后会创建一个附属的 `@annote` 的空白笔记，当时不了解这个文件作用，于是把`{{mode}}`删除了。

刚才根据再次做 了尝试，大致了解相关的东西了。对工作流做了一下梳理，后续再优化一下就行

问题得到解决了，感谢两位的帮助，谢谢

**Comment by Kenshin** [comment]
@xQmQ 

搞定就好。

> 我当初删除占位符`{{mode}}`是因为自动化导出全文后会创建一个附属的 `@annote` 的空白笔记，当时不了解这个文件作用，于是把`{{mode}}`删除了。

`{{mode}}` 属于 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 的一部分功能，再未彻底了解简悦的高端玩法的情况下，不要随便修改。

`xxx@annote` 并不是一个空白的文件，里面是基于 Markdown 的稍后读和标注内容，当没有标注时，也会存在稍后读数据。

你可以根据 [官方模板库](https://github.com/Kenshin/simpread/discussions/2153) 找到一个适合自己的模板，不设置模板的话，会使用一个默认模板。

***

另外，下周会发布一个新的模板方案，你可以留意下。最好订阅 https://simpread.pro/subscribe 发布后我也会通知这里。
