### ISSUE TITLE
gitlab 的官方文档进入阅读后 按钮不可用

### ISSUE THREAD

**Issue by xmeng1** [Kenshin/simpread#378]
https://docs.gitlab.com/ee/ci/quick_start/
![2018-08-25_08-50-12](https://user-images.githubusercontent.com/5753142/44616239-12b69c00-a844-11e8-8b9b-9592256bf188.png)

**Comment by Kenshin** [comment]
已修复此问题，同时增加了 GitLab 适配规则到站点集市 https://simpread.ksria.cn/sites/details/HRruQUd3f4
