### ISSUE TITLE
微信订阅文档导入语雀，代码块空格乱码为"<0xa0>"

### ISSUE THREAD

**Issue by Mz-peng** [Kenshin/simpread#3781]
你好，我在使用简悦收藏文档的时候遇到问题了。

- 操作系统 ** Windows10**

- 浏览器版本 **Chrome 100.0.1185.50**

- 简悦版本 **2.0.0**

- 发生问题的地址 https://mp.weixin.qq.com/s/5d38HrrpyChFhZwIqXEQcw

**将这个文档导入语雀保存，然后从语雀把这个代码块复制出来，代码块复制出来的空格乱码了。**

![image](https://user-images.githubusercontent.com/42714753/164896877-a45ccb23-9a32-4798-a080-c618db9581de.png)

![image](https://user-images.githubusercontent.com/42714753/164896830-7c553112-0e7a-44ea-b432-c1662d3fa714.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
