### ISSUE TITLE
用户个人界面入口在哪里？

### ISSUE THREAD

**Issue by hype1type** [Kenshin/simpread#3783]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，简悦不保存用户数据，也就没有所谓的个人界面。

你想要什么个人界面入口做什么？

唯一类似你提到的个人界面的话，看下图

![image](https://user-images.githubusercontent.com/81074/164953042-dc3fab2a-40de-4b0f-9633-ce7d81415bff.png)

**Comment by hype1type** [comment]
谢谢您的回复，我本意是找不到您这张图片对应的网页，所以希望在官网上能直接跳转到这个页面，刚刚才在【扩展选项】这里找到。谢谢您的回复

**Comment by Kenshin** [comment]
okay 搞定就好。

只要留存好 `simpread_config.json` `UID` `License` 就是你（用户）的全部用户数据了。
