### ISSUE TITLE
请教Kenshin一个小小问题：灵感回顾的dr是哪一个或两个单词的缩写呢？谢谢

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3785]
### Discussed in https://github.com/Kenshin/simpread/discussions/3784

<div type='discussions-op-text'>

<sup>Originally posted by **gujin03** April 24, 2022</sup>
问Kenshin一个问题：灵感回顾的dr是哪一个或两个单词的缩写呢？谢谢
我理解的r random，不知是否正确，d是哪个单词呢？</div>

**Comment by Kenshin** [comment]
@gujin03 

嗨，我把你的问题转移到这里了，并删除了原位置的内容。

挺意思的问题，其实 `dr` 的含义是：`Daily review` 

这个功能目前仅算 beta 版，需要回路重造。（当然，并不是不能用，只是它应该更好用。

**Comment by gujin03** [comment]
got thanks
