### ISSUE TITLE
关于简悦稍后读的本地客户端

### ISSUE THREAD

**Issue by lenxvp** [Kenshin/simpread#3786]
简悦的稍后读是否有开发成本地客户端的计划或者是否有哪些方式例如API或者数据结构等可以支持开发者开发成本地客户端？
想把简悦稍后读作为个人的网页资料库，但简悦目前的稍后读灵活度还不太够

**Comment by Kenshin** [comment]
嗨

1. 会有客户端

2. 早就有了 [API](https://kb.simpread.pro/#/page/%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E4%BB%8B%E7%BB%8D) 

3. 这是 [各种联动方案](https://github.com/Kenshin/simpread/discussions/2085) 如果动手能力强，绝对让你玩整月。

4. 简悦的数据结构都是开放的，均在 `simpread_config.json` 有需要的话，可自行查看。

5. 如果你是开发人员，或者想开发一些功能的话，随时在这里回复并告诉我你的想法。
