### ISSUE TITLE
高级账户无法绑定,提示后台异常

### ISSUE THREAD

**Issue by wzhich** [Kenshin/simpread#3789]
![image](https://user-images.githubusercontent.com/16451063/164985242-c118c215-6964-4f2f-9ba7-ad664b6a13ab.png)
如图,新购license无法绑定, 多次重试仍然报错

**Comment by Kenshin** [comment]
哈哈，看样子自己搞定了，以后有任何问题，请先查阅 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5) 基本上都能解决你的问题。
