### ISSUE TITLE
Logseq 和简悦的同步

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3795]
大神，请教个问题，按照少数派教程已关联logseq和简悦，

问题：简悦中每做一次标记，logseq就会链接一次（比如我标记了10次，那么logse就会有10次链接）如下图：

请问有没有办法，可以只关联一次，我是用hozel把简悦的md文件导入到logseq下面page文件夹

望指教！

<img width="1400" alt="WechatIMG922" src="https://user-images.githubusercontent.com/50163102/165102849-27ccfbf8-d7f1-4b84-b8e8-22dbec7a3be4.png">

_Originally posted by @JasonYe89 in https://github.com/Kenshin/simpread/discussions/3794_

**Comment by Kenshin** [comment]
@JasonYe89

嗨，我帮你把问题转移到这里，并删除了原来位置的内容。

**Comment by lyserenity** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/32646062/165207977-d714fcde-6256-44fe-8bcd-7039ed23065d.png">

你可以看一下 pages/ 里面有没有藏有多个 md 文件（包含 pages/ 里的文件夹），如果都没有就试试 re-index ，logseq 在 index 上有点点问题....

**Comment by JasonYe89** [comment]
问：我没理解你的问题，你是把 output 作为 Logseq 的库文件夹了吗？

  @@方便详细说明具体配置方式 @Kenshin 

答：是的，我把 simpread > output 下的md文件，通过hozel规则自动传输到logseq > pages文件夹中

       现在是可以关联引用过来，但是会出现重复的文件（如图所示）

      我的诉求是想要在简悦不管标记多少次，最终只在logseq出现一次引用，谢谢

<img width="857" alt="Snipaste_2022-04-26_21-47-41" src="https://user-images.githubusercontent.com/50163102/165314839-527d6fd7-9829-4a84-871d-23df9a492e0e.png">

**Comment by JasonYe89** [comment]
@lyserenity 确实有很多@annote-数字 文件（如图所示）

另外你说的re-index 功能在哪里，我貌似没有这个功能，谢谢指教


<img width="739" alt="1" src="https://user-images.githubusercontent.com/50163102/165315460-5f1acbf1-7492-4dcb-92e1-93e5daeb92e9.png">

**Comment by lyserenity** [comment]
那这跟 re-index 没太大的关系了，pages/ 里有多个 md 文件那当然会有多个连结。
 这应该跟 Hazel 的设定有关。我猜大概会有个跟覆盖文件或是创建 copy 之类有关的设定
 
 p.s. logseq 的 re-index 在客户端：
 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/32646062/165316497-6f7a0b48-fc9d-465e-9f4d-a8d4ea7c03ee.png">


> @lyserenity 确实有很多@annote-数字 文件（如图所示）
> 
> 另外你说的re-index 功能在哪里，我貌似没有这个功能，谢谢指教
> 
> <img alt="1" width="739" src="https://user-images.githubusercontent.com/50163102/165315460-5f1acbf1-7492-4dcb-92e1-93e5daeb92e9.png">

**Comment by Kenshin** [comment]
@JasonYe89 

把你的 Hazel 设置的自动化截图看下。

**Comment by Kenshin** [comment]
@JasonYe89 

看我的 Hazel 设置

![image](https://user-images.githubusercontent.com/81074/165428910-da5a216d-e3a8-4ecc-a7f3-ea2950197411.png)

**Comment by JasonYe89** [comment]
@Kenshin 

规则如下
<img width="990" alt="3" src="https://user-images.githubusercontent.com/50163102/165429012-10fd0f4f-1e77-4259-9a7d-1ccc71bb9345.png">
<img width="990" alt="2" src="https://user-images.githubusercontent.com/50163102/165429028-3c233de5-c838-4d4a-93ee-2d9d80696a4a.png">
，

**Comment by Kenshin** [comment]
@JasonYe89 

那应该没问题，你可以自己做个测试，标注个页面，看看 `xxx@annnote.md` 是覆盖还是增量？

**Comment by JasonYe89** [comment]
谢谢大神，已解决

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 issues 了~

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
