### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by kytad** [Kenshin/simpread#3796]
发生问题的地址: <https://blog.csdn.net/QQ_2767376626/article/details/112983018>

**Comment by Kenshin** [comment]
嗨，此页面可以正常适配，请问有什么问题吗？我先关闭这个 Issues 了。

![image](https://user-images.githubusercontent.com/81074/165206380-bbe47e09-267a-4ffb-a4b4-9548bb3fc22a.png)
