### ISSUE TITLE
悬浮窗大量留白会挡住页面操作按钮

### ISSUE THREAD

**Issue by cksdxz1007** [Kenshin/simpread#3797]
简悦悬浮按钮上方有大片空白，会挡住页面的操作按钮无法操作，把悬浮窗移开才能点击
![Xnip2022-04-26_14-21-08](https://user-images.githubusercontent.com/21142070/165234855-3dc4c853-595c-4b4d-bc58-71da88c39163.jpg)
![Xnip2022-04-26_14-22-00](https://user-images.githubusercontent.com/21142070/165235034-9fd35048-906c-447f-a5ea-75d6a93af27d.jpg)
![Xnip2022-04-26_14-22-28](https://user-images.githubusercontent.com/21142070/165235053-ee9ec831-bd3a-40bd-a089-f7e1185681cc.jpg)

**Comment by Kenshin** [comment]
嗨，看起来应该是你同时安装了 **油猴脚本** 导致的。

**Comment by cksdxz1007** [comment]
> 嗨，看起来应该是你同时安装了 **油猴脚本** 导致的。

我确实是安装了油猴脚本，那这个有办法解决吗

**Comment by Kenshin** [comment]
1. 油猴和扩展端只能留其一。

2. 不建议使用油猴脚本，功能仅是 1.x 的部分而已。
