### ISSUE TITLE
导出到logseq里的MD文件的标签和描述不同步

### ISSUE THREAD

**Issue by chipsflying** [Kenshin/simpread#3799]
-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows10**

- 浏览器版本 **Chrome 100.0.4896.60（正式版本） （64 位）**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

在稍后读中修改了文章的标签和描述，也写了备注。手动把生成的XX@annote.md文件放到logseq文件夹中。logseq能自动读出该文件，但是标签和描述都没有和稍后读中的同步。请问这是我的设置出了问题，还是原本就是这么设计的？

![image_1650969528816_0](https://user-images.githubusercontent.com/102506599/165285680-f1888231-9ff5-4ecf-919a-b5db543aceb7.png)
![image_1650969547777_0](https://user-images.githubusercontent.com/102506599/165285750-a06277ea-5243-4460-b257-68bfd7865c70.png)

**Comment by Kenshin** [comment]
> 在稍后读中修改了文章的标签和描述，也写了备注。手动把生成的 `XX@annote.md` 文件放到logseq文件夹中

看截图似乎是在稍后读中添加的备注 / 标签吗？如果是的话，稍后读的编辑并不能触发自动化，需要手动导出。

![image](https://user-images.githubusercontent.com/81074/165286392-2beb8f83-c825-4a6e-9f4f-614f367eb509.png)

所以，最好的方案：

1. 在阅读模式中编辑。
2. 同时使用 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件，确保你的每个操作都能自动化导出。

**Comment by chipsflying** [comment]
明白了，谢谢！

**Comment by Kenshin** [comment]
okay 我关闭这个 issues 了。

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
