### ISSUE TITLE
【建议】 论坛每楼层的内容添加分隔符。 

### ISSUE THREAD

**Issue by lqzhgood** [Kenshin/simpread#38]
例如 chiphell.com 里面进入阅读模式后，基本无法区分 各楼层的内容，我看完一篇帖子还以为都是楼主一个人写的。。。。。
现在好像就是用 <br> 分割，看不出什么效果。

建议 每个楼层的内容用 div 包裹，有 class，配合即将开放的 自定义主题
这样用 伪类 :after  可以直接添加 hr 等分割线样式。

**Comment by Kenshin** [comment]
感谢建议以及直接给出的解决方案！ :thumbsup:

目前的确有这种情况，除了 chiphell 外，还有 知乎 贴吧 等类似 BBS 的结构都存在此问题。
新版本会增加这类结构的适配。

关于这方面的讨论，可以看  https://github.com/Kenshin/simpread/issues/20

**Comment by Kenshin** [comment]
`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

可以使用 `自定义样式` 来修改正文的字体，此 issues 将关闭~
