### ISSUE TITLE
在阅读模式下无法利用扩展进行划词翻译，求解决方法。

### ISSUE THREAD

**Issue by hqz0502** [Kenshin/simpread#380]
在阅读模式下无法利用扩展（沙拉查词）进行直接划词翻译，必须先退出阅读模式，使用起来十分不便，请问有解决的方法吗？感谢！

**Comment by kedup** [comment]
无解啊

**Comment by Kenshin** [comment]
1.1.2 会在一定程度上解决这个问题，1.1.2 本周发布~

**Comment by Kenshin** [comment]
`1.1.2` 已经发布，新增加了 [插件中心](https://simpread.ksria.cn/plugins/) 
其中 [划词翻译](https://simpread.ksria.cn/plugins/details/ohnTKVHz4a) 可以在一定程度上解决这个问题。

除此之外，其它新增功能请看 更新日志 http://ksria.com/simpread/changelog.html#1.1.2 & http://ksria.com/simpread/welcome/version_1.1.2.html

我将关闭此 issues。  😀
