### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by RoweMann** [Kenshin/simpread#3800]
发生问题的地址: <https://wenku.baidu.com/view/62275910ec630b1c59eef8c75fbfc77da369975b.html?re=view>

**Comment by Kenshin** [comment]
谢谢反馈，适配后我会在这里通知你。

**Comment by Kenshin** [comment]
嗨，抱歉上面的内容错了，百度文库是不可以被适配的，我关闭这个 Issues 了。

**Comment by RoweMann** [comment]
哦哦哦哦这样子，非常感谢

**Comment by Kenshin** [comment]
哈哈，小事情。
