### ISSUE TITLE
语雀授权失败

### ISSUE THREAD

**Issue by wyrain** [Kenshin/simpread#3801]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10 20H2 专业版**

- 浏览器版本 **Chrome 101.0.4951.41（正式版本） （64 位）**

- 简悦版本 **2.2.0**

- 发生问题的地址 任意网址

**请描述你的问题**

简要: 语雀授权后, 弹出了简悦的已连接生产力工具页面, 但实际上在语雀查询到并没有授权成功.
详情: 保存到语雀的功能一直都是OK的, 直到昨天(2022.04.26)突然不行了, 保存时页面右上角一直提示正在保存到语雀, 等多久都是在保存中转圈圈. 我找遍设置后觉得可能是授权问题, 于是关闭了语雀授权并在语雀删除了授权, 然后重新开启并申请授权, 情况就变成一保存就提示没授权, 按提示去申请授权, 简悦弹出了已连接生产力工具, 再保存还是弹没有授权, 在语雀放确实是没有成功授权的.

**截图**

![image](https://user-images.githubusercontent.com/20262079/165426637-1837e8f1-2913-4862-80c5-9086eca304fb.png)
![image](https://user-images.githubusercontent.com/20262079/165426711-9d36c61a-071e-4693-98b7-3e822ccb66c8.png)
![image](https://user-images.githubusercontent.com/20262079/165426772-dd104cc5-4b08-4e2c-95c0-1238c0c99b0f.png)
删除旧授权前还有张"无限转圈圈提示保存中"的图, 现在删掉了旧授权已经没法截取到了

**Comment by Kenshin** [comment]
嗨，我测试了下，是没问题的。

你可以这样试试：

1. 在选项页 → 服务 → 语雀中授权。
2. 不要在阅读模式下授权。

另外，是不是你的网络环境有问题？或者稍晚些在测试下。

**Comment by wyrain** [comment]
网络环境是没有问题的, 其他任意网站均可打开.
尝试您的建议后, 仍然失败了但有了提示:
![image](https://user-images.githubusercontent.com/20262079/165429675-bda96d21-eb27-4af2-9e2a-731fcf01b15a.png)

**Comment by wyrain** [comment]
已使用Edge浏览器成功授权并使用保存功能, Chrome下还是不行, 不知道是缓存问题, 还是我Chrome插件和油猴脚本装多了, 影响了一些想不到的地方.

**Comment by Kenshin** [comment]
> 已使用Edge浏览器成功授权并使用保存功能

你可以将下图的选项打开，然后 Edge 的配置，再导入到 Chrome 即可。

![image](https://user-images.githubusercontent.com/81074/165443188-ff6d5c86-f748-4a2b-9a57-22555ab1dfc3.png)

**Comment by wyrain** [comment]
好的, 感谢你如此快速积极的处理反馈

**Comment by Kenshin** [comment]
@wyrain 

哈哈，客气了，要是有可能的话，请帮忙在 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星好评 + 评论。

最近因为几个无聊的人，Edge 被刷了几个低分。最好能在评论中说说「有问题提问并及时反馈」这个事情。

虽然不太在意 Edge 的评分，但还是像门口的广告一样「烦人」。

**Comment by wyrain** [comment]
一定好评, 好东西不该被埋没

**Comment by FeMiner** [comment]
mac chrome遇到同样的问题

**Comment by Kenshin** [comment]
@FeMiner 

emmm 这个问题跟简悦其实无关，我也不清楚为什么无法授权，因为只有个别用户反馈过类似情况。

你可以这样测试下：

1. 登出语雀

2. 取消简悦的语雀授权

3. 重启浏览器

4. 登录语雀

5. 简悦这边重新授权（请通过选项页 → 服务 → 授权）

试试，如果还是不行的话：

1. 确定你的语雀账户有什么特别的？

2. 重新注册一个语雀账户

**Comment by wyrain** [comment]
确实不是简悦的问题, 我自己怀疑是浏览器缓存的问题.
你可以换个浏览器试一下以验证问题是出在浏览器, 还有就是这里最好是选在所有网站上
![image](https://user-images.githubusercontent.com/20262079/169743048-e7fa0f69-c2e9-4876-b8d4-4dd92d95eb15.png)

**Comment by Kenshin** [comment]
@wyrain 

哈哈，谢谢帮忙  😏  👏

**Comment by FeMiner** [comment]
@Kenshin 我试了Edge浏览器也授权不成功，另外我试了另一个插件Web Clipper一键授权能获取Access Token但是请求也显示没权限，但是使用我在语雀后台直接生成的Access Token是生效的，简悦这边是否也考虑加入直接配置Access Token的功能， 语雀那边反馈处理不及时，不想更换账号

**Comment by FeMiner** [comment]
> 我直接修改配置文件也OK了

**Comment by Kenshin** [comment]
@FeMiner 

okay 欢迎自救成功。但问题确实很奇怪。😂

> 我在语雀后台直接生成的Access Token是生效的

能否把这段简单的说明下，我放到 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5) 中。

**Comment by FeMiner** [comment]
![image](https://user-images.githubusercontent.com/3765770/173047820-cba0b5df-eeba-4a74-959a-452e8b827c8a.png)
我抓包看了一下自动授权能正常拿到Access Token，而且语雀也发邮件提示授权成功，但是在账号设置->授权里却查不到授权，所以我在语雀账号设置->Token手动生成了一个Access Token填到了简悦导出的配置文件里再导入简悦就OK了

**Comment by wyrain** [comment]
> ![image](https://user-images.githubusercontent.com/3765770/173047820-cba0b5df-eeba-4a74-959a-452e8b827c8a.png) 我抓包看了一下自动授权能正常拿到Access Token，而且语雀也发邮件提示授权成功，但是在账号设置->授权里却查不到授权，所以我在语雀账号设置->Token手动生成了一个Access Token填到了简悦导出的配置文件里再导入简悦就OK了

这确实是目前最合适的解决方案了,  我之前换个浏览器又可以授权时, 作者也建议我导出Edge的配置给Chrome用, 也是你这个思路

**Comment by Kenshin** [comment]
嗨，各位，我已经将此方案记录到了 https://github.com/Kenshin/simpread/discussions/4052 🙏
