### ISSUE TITLE
关于自动同步的疑问

### ISSUE THREAD

**Issue by Arvin-Chan** [Kenshin/simpread#3803]
我下载了自动同步助手，运行了一下就退出了，之后在浏览器里，再想保存到坚果云，就一直是导出失败了，之前一直都是正常的，可以直接发送到坚果云。 是因为我下了同步助手并运行了一次的原因么？

**Comment by Arvin-Chan** [comment]
![image](https://user-images.githubusercontent.com/36808222/165500237-eaf5e819-6c07-480d-aa87-29c038618511.png)

**Comment by Arvin-Chan** [comment]
“手动同步”配置里，点击 “同步到你的坚果云账户”，也一直是同步中，不能成功

**Comment by Kenshin** [comment]
嗨，使用了同步助手就需要开启它，建议看看下面的教程。

1. 试试 32 位的同步助手。
2. 配置 [同步助手](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)
3. [同步方案](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%8A%E5%85%B6%E5%90%8C%E6%AD%A5)

**Comment by Arvin-Chan** [comment]
> 嗨，使用了同步助手就需要开启它，建议看看下面的教程。
> 
> 1. 试试 32 位的同步助手。
> 2. 配置 [同步助手](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)
> 3. [同步方案](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%8A%E5%85%B6%E5%90%8C%E6%AD%A5)

你好，但是我下载同步助手，并没有想要开启它，为了运行一下，看一下配置，还是想用浏览器里的保存的，可以恢复或者初始化么？ 我已经退出，但是仍旧在浏览器里保存到坚果云失败，我如何卸载同步助手？ 删除.exe的执行文件即可么？删除后可以正常的在浏览器里上传么？需要我调整什么配置么？

**Comment by Kenshin** [comment]
你下载的是什么版本的同步助手？
同步助手不需要卸载，直接删除文件夹就行。

选项页 → 共通 → 关闭自动同步就行了？

**Comment by Kenshin** [comment]
请在这里讨论

**Comment by Kenshin** [comment]
看看是不是这个问题 https://github.com/Kenshin/simpread/discussions/1567

**Comment by Arvin-Chan** [comment]
好的，不好意思，你把那个issue删了吧

**Comment by Kenshin** [comment]
使用坚果云的前提，请输入坚果云的 Email 与 坚果云 WebDAV 的密码。

**Comment by Arvin-Chan** [comment]
授权了的，这些我都知道，我是一枚菜鸟程序员（捂脸），基本的一些操作我都明白，之前同步都是没问题的（没有下载自动同步助手运行那一下之前）

**Comment by Kenshin** [comment]
看看 https://github.com/Kenshin/simpread/issues/3803#issuecomment-1110932280 

如果还是搞不定，把配置文件导出，重装简悦，在重新授权坚果云。

还是不行的，把配置文件发到 help#simpread.pro 只能明天帮你看看了。

还有，你的截图跟同步助手的使用无关。

**Comment by Arvin-Chan** [comment]
![image](https://user-images.githubusercontent.com/36808222/165520381-da416947-8045-4af5-ac92-c2ab6bcc7651.png)

**Comment by Arvin-Chan** [comment]
嗯嗯，好，我重装一下试试

**Comment by Kenshin** [comment]
看 https://github.com/Kenshin/simpread/issues/3803#issuecomment-1110954626

大概率是

1. 坚果云 Email / WebDAV 错误
2. 你的网络问题

**Comment by Arvin-Chan** [comment]
我重置了配置，重新授权，已经可以了，谢谢大佬。 还有一个问题想咨询一下，就是我现在是有谷歌账号的，如果换了台设备，在chrome上登陆谷歌账号，插件会自动同步，那插件里的内容会同步么？比如我的那些标签~

**Comment by Kenshin** [comment]
搞定就好。

不会自动同步 Chrome 的同步很坑，如果不使用自动同步的话，只能使用手动同步。

关于同步有很多方式，可以看 [这篇](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%8A%E5%85%B6%E5%90%8C%E6%AD%A5)
