### ISSUE TITLE
不管选什么阅读主题，阅读模式都是 黑茑模式

### ISSUE THREAD

**Issue by Friensility** [Kenshin/simpread#3804]
- 操作系统 **e.g.  Windows10**

- 浏览器版本 **e.g. Microsoft Edge 100.0.1185.50 (正式版本) (64 位)**

- 简悦版本 **2.0.0**

**选择了默认阅读模式主题，不管选了什么主题，阅读模式都是 黑茑模式**

下方为阅读模式时 样式截图。没有选项有阴影选中样式，看起来没有主题被选中
![阅读模式时的样式似乎没有主题被选中](https://user-images.githubusercontent.com/58850167/165507224-bea0c4d0-e74c-4db6-b5e5-74763ce41e18.jpg)

**Comment by Kenshin** [comment]
嗨，估计开了 「暗色模式」吧？

选项页 → 高级设定 里面有相应选项。

**Comment by Kenshin** [comment]
没有的话，我关闭这个 Issues 了。
