### ISSUE TITLE
我关闭了自动同步，删了下载的自动同步文件夹，但是还是一直导入中，一直不成功，好着急

### ISSUE THREAD

**Issue by Arvin-Chan** [Kenshin/simpread#3805]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Arvin-Chan** [comment]
转圈圈转了一分多钟了，还是同步中。。。

**Comment by Kenshin** [comment]
不要重复提相同的 Issues

**Comment by Arvin-Chan** [comment]
我刚才运行的同步助手的版本是1.0.1

**Comment by Kenshin** [comment]
请在 https://github.com/Kenshin/simpread/issues/3805 讨论，因为重复内容，我删除此 Issues 了。
