### ISSUE TITLE
选项页无法打开问题

### ISSUE THREAD

**Issue by Caizaifa** [Kenshin/simpread#3810]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/18107069/165738854-b0c74078-107f-4d9d-bcc0-f8a8a9eb3a6d.png">
按照步骤重新安装导入配置文件后,选项页面还是无法打开,在mac端vivaldi浏览器中,打开同步助手的情况下!!!不知道如何解决、

**Comment by Kenshin** [comment]
嗨，试试此方式 https://github.com/Kenshin/simpread/discussions/3165

**Comment by Caizaifa** [comment]
> 

感谢🙏已解决
