### ISSUE TITLE
在新设备导入同步的本地配置文件后，打不开选项页面了，一直卡在logo界面

### ISSUE THREAD

**Issue by jpcnmm2** [Kenshin/simpread#3813]
如下图：
![image](https://user-images.githubusercontent.com/83856390/165876456-0e40dd8c-e7dd-481e-895f-d11a6a907db4.png)

**Comment by jpcnmm2** [comment]
> emmm
> 
> 1. 是不是用了同步助手，如果是的话，重启同步助手后再试试。
> 2. 确定导入的配置文件是可以正常使用的？（而非之前旧的吗？

确实是因为同步助手的原因，解决了，谢谢

**Comment by Kenshin** [comment]
搞定就好，有任何使用问题，可以看看看 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5)

我关闭这个 Issues 了。
