### ISSUE TITLE
csdn的一篇博客解析不了，麻烦作者看下什么原因

### ISSUE THREAD

**Issue by LinnyR** [Kenshin/simpread#3815]
[https://blog.csdn.net/forezp/article/details/69696915](https://blog.csdn.net/forezp/article/details/69696915)

**Comment by Kenshin** [comment]
我这边可以

![image](https://user-images.githubusercontent.com/81074/165896538-c5487107-34d9-474b-bd01-94af0073c4f5.png)

1. 请告诉解析不了的含义（截图 / 视频）
2. **隐身模式下仅使用简悦的方式**

**Comment by LinnyR** [comment]
就是很奇怪，打开第一篇博客进入后图标不变色，点突变也没反应，而进入第二篇，第三篇博客就能变成红色，我试了360极速浏览器x和chrome都出现这种情况。
![image](https://user-images.githubusercontent.com/38827394/165898112-d9b9f49c-ee0b-4466-aa09-ab8053f99a33.png)
![image](https://user-images.githubusercontent.com/38827394/165898193-23ffaf42-024a-4348-a7c0-6ff7836c75b0.png)

**Comment by LinnyR** [comment]
隐身模式下可以了(๑•̀ㅂ•́)و✧

**Comment by Kenshin** [comment]
可能是其它扩展造成的干扰。

另外，不变红的话，也可以通过阅读模式的快捷键进入。

没问题的话，我关闭 Issues 了~
