### ISSUE TITLE
Live Editor没有找到Live Editor选项界面

### ISSUE THREAD

**Issue by www766** [Kenshin/simpread#3826]
请问磊哥，简悦2.2 付费用户 安装Live Editor后打开状态，阅读模式下，阅读模式 → 控制栏 → 动作 → 插件触发器没有找到Live Editor选项界面，EDGE浏览器最新版版本 101.0.1210.32 (正式版本) (64 位)，什么原因请指教？[拜托]感谢！

**Comment by Kenshin** [comment]
嗨，是不是使用了同步助手？如果是的话，你需要这样做：

1. 关闭自动同步
2. 重新安装 Live Editor
3. 设置并确认设置正确
4. 开启自动同步（下面的链接有相关说明）

官方折腾指南 👉 https://github.com/Kenshin/simpread/discussions/3696

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4
