### ISSUE TITLE
增加对本地html文件的标注和锚点功能！

### ISSUE THREAD

**Issue by www766** [Kenshin/simpread#3828]
功能建言：可否增加对本地html文件的标注和锚点功能？
祝磊哥五一节快乐！

**Comment by Kenshin** [comment]
嗨，其实一直都是可以的，你可以读取本地 HTML，并使用阅读模式，但无法加入稍后读（因为个 Bug 导致，功能都在的） 😂 

修复这个 Bug 后我会通知你的~

五一宅家快乐。

**Comment by www766** [comment]
@Kenshin 可是磊哥我用EDGE打开本地html（保存了国家税务局的一个离线html制度），简悦扩展是灰色的（不是红色可用状态）不可以使用阅读模式啊？请问具体需要怎么使用

**Comment by www766** [comment]
@Kenshin 还有多数简悦用户都是普通大众，不是开发人员，加上github上来时好时坏非常不稳定，反馈问题很受阻，也阻挡了很多人员的反馈之声，**可否在Gitee开一个反馈地址**呢？国内人员访问反馈也方便。给大佬添麻烦了。

**Comment by Kenshin** [comment]
> 可是磊哥我用EDGE打开本地html（保存了国家税务局的一个离线html制度），简悦扩展是灰色的（不是红色可用状态）不可以使用阅读模式啊？请问具体需要怎么使用

看这里 https://github.com/Kenshin/simpread/discussions/1689

> 反馈问题很受阻，也阻挡了很多人员的反馈之声，可否在Gitee开一个反馈地址呢

可以考虑，我先调查下。

**Comment by angel126** [comment]
> 嗨，其实一直都是可以的，你可以读取本地 HTML，并使用阅读模式，但无法加入稍后读（因为个 Bug 导致，功能都在的） 😂
> 
> 修复这个 Bug 后我会通知你的~
> 
> 五一宅家快乐。

请问一下，针对本地html 文件，标注保存的稍后阅读是否有修复了？
![image](https://user-images.githubusercontent.com/8450915/187115418-485391f9-183c-48dd-85d0-a357870cb88b.png)
之前提的高亮标注在用了，目前还不错，感谢更新。

**Comment by Kenshin** [comment]
@angel126 

嗨，暂时没有，我一直在三亚被「封控」ing...

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [稍后读 · 读取外部文件](https://github.com/Kenshin/simpread/discussions/4625)。

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。

**Comment by YB-Kang** [comment]
@Kenshin 希望可以增加对简悦导出的本地快照，进入阅读模式的支持。以前重置过josn文件，稍后读的数据没了，本地快照还在，但就没办法修改标注，也没办法导入到obsidian使用。
