### ISSUE TITLE
增加对思源笔记的双链导出支持!【为什么要使用开源 json 格式进行存储笔记而不是 md】

### ISSUE THREAD

**Issue by www766** [Kenshin/simpread#3829]
功能建言：可否增加对思源笔记的双链导出支持！（或者有默认官方导出样式的md，方便思源直接导入【多数普通用户还是不会自己设置样式啊。。。】）
虽然思源笔记是.sy文件格式，但实质是 json 格式，
[这里](https://ld246.com/article/1619080345258)思源笔记对md的局限性和产品路线前瞻性进行了探讨， [这里](https://www.yuque.com/deerain/gannbs/kbczzv)是[笔记与写作工具深度测评]专栏作者对思源笔记各笔记之间的深度对比。相信目前各项功能的完善优化，会有更多人员转投思源笔记。
恳请磊哥出手，适配下思源笔记，以享网友，感谢！

**Comment by Kenshin** [comment]
okay 我会严重考虑的。（对它的呼声很高！ 😀

**Comment by Kenshin** [comment]
嗨，各位~

久等了，预计周末在这里发测试版。

我会把思源相关的功能都整理到 https://github.com/Kenshin/simpread/issues/5555 同时，有一些关于思源笔记功能的需求调研，要是有可能的话，请 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1563812818 并回复下你们的使用方式。

**Comment by Kenshin** [comment]
嗨，各位。

导入到思源笔记的插件已经可以内测了，如何使用以及讨论请前往 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566016251

**Comment by Kenshin** [comment]
![Siyuan](https://github.com/Kenshin/simpread/assets/81074/a8f839b4-90e5-4fbe-8ae9-da73b48c888c)

嗨，各位。

导入到思源笔记的插件已发布。

### 下载地址

https://simpread.ksria.cn/plugins/details/XxuF7bPTbo

### 功能

- 定制思源笔记地址（适用于 Docker 用户）

- 新建笔记本（留空则新建 SimpRead 名称的笔记本）

- 查看并选择任意笔记本
   
- 自定义导入路径

- [思源图库](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- [assets 定制](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025979) 包括：`{{title}}` 与 `{{date}}`

- [将阅读模式的图片转换为思源图床](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- 导入全文到思源笔记

- 快捷键

- [自动化](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025982)

- 在导入前可选择任意笔记本或路径

### 如何安装

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

### 注意事项

如果你使用了 Docker 版，并且域名不是 `localhost` 的话，可能会有问题。


***

我关闭这个 issues 了，但有任何使用疑问均可在 https://github.com/Kenshin/simpread/issues/5555 继续再此讨论。 😄
