### ISSUE TITLE
安装插件后如何使用?

### ISSUE THREAD

**Issue by monkey-sking** [Kenshin/simpread#383]
安装插件后如何使用?

**Comment by Kenshin** [comment]
呵呵，还没开始写这块的文档。😓
其实无需干扰，安装后就能使用了。

你安装的是什么插件？

由于插件的说明已经很清晰了，而且很常规，所以没加说明。

过两天会加入插件的说明。

**Comment by Kenshin** [comment]
嗨，新版简悦发布~

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
