### ISSUE TITLE
Edge设置插件快捷键，请问“全局”和“在Edge中”有什么区别？

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3830]
如图所示，简单在百度和谷歌都找了一下，没找到答案。一开始还以为设为全局能让我在火狐里用edge的快捷键来添加稍后读，实际试了一下果然不行。所以请问有人知道这两个设置选项有什么区别吗？感谢。
![image](https://user-images.githubusercontent.com/65625632/166248337-2fac8707-6dd7-43ac-a1d5-6139fd0ddb1d.png)

**Comment by Kenshin** [comment]
全局的意思是指：在不关闭 Edge 的前提下，比如把浏览器最小化后，仍能使用。

但我不建议使用全局快捷键（即截图里面的快捷键）

**Comment by Kenshin** [comment]
昨晚忘记补充「不希望这么做的原因」：系统快捷键会与其他 App 的快捷键有重复的嫌疑，出问题后也很难排查。
