### ISSUE TITLE
反馈简悦开放平台问题

### ISSUE THREAD

**Issue by www766** [Kenshin/simpread#3831]
简悦开放平台授权码登陆BUG：

1、该页面居然输入**授权码是明文显示**！https://simpread.pro/developer

2、该页面EDGE**不能记录下cookies，每次均需要输入id和授权码**

3、该页面通过定制化导出功能支持导入到任意双链笔记，配置好后外部链接https://simpread.pro/developer/@id/reading/ ，通过双链笔记**点击此外部链接，居然每次进入404页面**显示法外之地，在思源笔记内点击外部链接**无法直接访问到资源**。

**Comment by Kenshin** [comment]
1. 授权码不是密码，也无法只通过授权码登录。
2. 当然不会有 cookies，就是因为安全性，你登录后，其他人随时可以打开此页面。
3. 显然你没有配置好。

关于第三点，需要看下此处 [教程](https://kb.simpread.pro/#/page/%E9%98%85%E8%AF%BB%E5%88%97%E8%A1%A8) 来配置后才能使用。
