### ISSUE TITLE
腾讯微云无法下载同步助手

### ISSUE THREAD

**Issue by 785808591** [Kenshin/simpread#3834]
腾讯微云的分享下载地址无法打开，无法下载同步助手
![image](https://user-images.githubusercontent.com/38028486/166438506-b72eb0ea-9e7e-4e82-b9a7-91d6f19cbbdd.png)

**Comment by Kenshin** [comment]
可以正常下载

![image](https://user-images.githubusercontent.com/81074/166441950-bbf0aa7d-393a-4f12-a8ba-c16b06cce820.png)
