### ISSUE TITLE
导出到obsidian功能在m.thepaper.cn下无法使用

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#3837]
问题链接：https://m.thepaper.cn/baijiahao_17919561?sdkver=771db3e7
使用简悦打开后，按快捷键/菜单方式操作【导出到obsidian】，界面无任何反馈。Obsidian无任何动作。
其他网页访问和保存正常，不知何故。
想知道在哪里能看到运行的日志。

**Comment by Kenshin** [comment]
嗨， 我测试了下是没有问题的。

试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？

**Comment by shadu120** [comment]
![2022-05-04_20-54-48](https://user-images.githubusercontent.com/3023471/166685436-234f97a7-674a-44cf-9b0a-19c34cba2bb8.gif)

**Comment by shadu120** [comment]
Chrome版本 100.0.4896.127（正式版本） （64 位）
在用的其它扩展有：Instapaper、ADB、Eagle、Raindrop

**Comment by shadu120** [comment]
感觉像是本地Obsidian Local REST API的问题。

![request2](https://user-images.githubusercontent.com/3023471/166687382-56ee5b39-5d26-41c5-ae41-4a9e499646ab.jpg)

![request3](https://user-images.githubusercontent.com/3023471/166687386-5a75925e-4ada-4a2c-87ce-25846e3ba4c9.jpg)
![request1](https://user-images.githubusercontent.com/3023471/166687373-ae40774d-ca41-4871-83a7-5b1ed3d82fe7.jpg)

**Comment by shadu120** [comment]
从抓包看，安装了你提供的特殊字符修正插件后，好像并没有生效，提交的标题仍然包含 双引号。
![request4](https://user-images.githubusercontent.com/3023471/166689189-3fb04681-f636-44e1-9f68-32e1ce6d88d0.jpg)
![request5](https://user-images.githubusercontent.com/3023471/166689270-14f89247-99b0-477f-bfee-bed7a3e59ecc.jpg)

**Comment by Kenshin** [comment]
是不是使用了同步助手？
如果是的话，先关闭自动同步，然后再安装这个插件后确认无需。

最后再开启自动同步并覆盖本地配置文件。

**Comment by shadu120** [comment]
参考#3844

我做了恢复后，插件OK，双引号被去除了。
重新加载Obsidian保存全文成功，保存批注失败。

然后再重拾，发现两个保存又挂了，http://127.0.0.1:27123/一直pedding，跟刚开始那会儿一样。
也不知道是不是Local API的问题，沮丧。。。

**Comment by shadu120** [comment]
同步助手我已经停了。

同步助手还有个问题：开了第一个在状态来没看到，又开了一个，直接报错。应该做单进程检查的。
Windows 11

**Comment by Kenshin** [comment]
配置完毕后，重开就行了。
同步助手不需要停，除非你不需要用对应的功能。

至于你说的 Local API 问题，可以重启试试。

我的建议是：在折腾配置时确实容易出现未知问题，这很正常，无论是简悦还是 Obsidian。

**Comment by Kenshin** [comment]
另外，多开的问题我已经记录了。

**Comment by shadu120** [comment]
今早电脑重启后，都工作正常。
用到下午时候，发现到Obsidian又偶尔不灵了。
也不知道是不是我电脑问题。等解封后去公司用Mac试试看。
先close吧。

**Comment by Kenshin** [comment]
大概率是你的问题，因为这个情况只有你反馈，这个功能用户数量还可以，以及我每天都用它做测试，也没有发生什么问题。
