### ISSUE TITLE
在阅读模式下批注，设置批注相关选项后刷新页面将会丢失已完成的所有批注，稍后读中该页面也会消失（取消收藏）

### ISSUE THREAD

**Issue by keQsia** [Kenshin/simpread#3838]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

1. 不会出现你说的问题
2. 大概率是这个问题造成的 https://github.com/Kenshin/simpread/discussions/3696
