### ISSUE TITLE
Chrome浏览器点击阅读模式后除了背景外所有内容消失

### ISSUE THREAD

**Issue by Troygem** [Kenshin/simpread#3840]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Chrome （已是最新版本）版本 101.0.4951.54（正式版本） （64 位）**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**点击阅读模式后各个网页点击阅读模式后除了背景图外所有内容都消失**

**查看了下插件信息，发现有错误，重新安装也没用**

**截图**

![1](https://user-images.githubusercontent.com/73052612/166654422-c8bd94bb-f75d-4989-bedb-2c486a45cc23.png)
![2](https://user-images.githubusercontent.com/73052612/166654428-95198e73-6103-4667-ad84-cc9fa59b0340.png)
![3](https://user-images.githubusercontent.com/73052612/166654432-0f4c7aba-31f8-49b7-92e3-a430064ba073.png)

**Comment by Kenshin** [comment]
1. 这个错误跟你的现象无关，甚至于这不算是个问题
2. **隐身模式下仅使用简悦的方式** ，你的插件安装的太多了，需要排除法。
3. 在隐身模式下，试试其它页面 e.g. https://sspai.com/post/69972

**Comment by Troygem** [comment]
> 1. 这个错误跟你的现象无关，甚至于这不算是个问题
> 2. **隐身模式下仅使用简悦的方式** ，你的插件安装的太多了，需要排除法。
> 3. 在隐身模式下，试试其它页面 e.g. https://sspai.com/post/69972

隐身模式下可以正常使用了，谢谢解答

**Comment by Kenshin** [comment]
okay

可以试试使用二分法方式，排除插件，看看是哪个出现了问题。

我关闭此 Issues 了。
