### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by xiangwanggege** [Kenshin/simpread#3841]
发生问题的地址: <https://wenku.baidu.com/link?url=UrgJYAdX6uoUc_flj48PQKfVDQrbM-JHDqlj16XB0kEX67uGlcNtOTwxskoDXuoXTY1V1AFVG4DapNWH3upiQXyTlsmKpCHYrVrTk-OsbdXCle_xY1J3zVRfmukOaVTR>

**Comment by Kenshin** [comment]
嗨，此类页面是不可以被适配的，我关闭这个 Issues 了~
