### ISSUE TITLE
导入到Obsidian插件的选项参数保存后无法生效。

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#3844]
尝试修改Local REST API 的Token。
修改后点击保存，提示保存成功。
刷新页面，再看Token，居然没有变化……
![request6](https://user-images.githubusercontent.com/3023471/166692648-a26ce37e-58c8-451d-8cc6-33069421c286.jpg)
![request7](https://user-images.githubusercontent.com/3023471/166692669-7b83b0ad-7ee6-4a5b-93e2-a53cb4bafbe8.jpg)

**Comment by Kenshin** [comment]
是不是使用了同步助手？

如果是的话，先关闭自动同步，然后再安装这个插件后确认无需。

最后再开启自动同步并覆盖本地配置文件。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
