### ISSUE TITLE
使用同步助手部分插件不能正常工作

### ISSUE THREAD

**Issue by xlshiz** [Kenshin/simpread#3845]
**发生问题的环境**

- 操作系统 **Linux**

- 浏览器版本 **Microsoft Edge 101.0.1210.32**

- 简悦版本 **2.2.0**

**请描述你的问题**

使用同步助手 · 命令行版后，**阅读模式浮动面板定制器**和**Lightbox Gallery**两个插件在阅读模式的**动作->插件触发器**中消失了

**Comment by Kenshin** [comment]
嗨，这个问题跟同步助手无关，解决方案 https://github.com/Kenshin/simpread/discussions/2342

每个插件的说明底部都有此链接的相关说明。

**Comment by xlshiz** [comment]
感谢，已按照说明解决。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4
