### ISSUE TITLE
ibm developworks 进入阅读模式图片不能加载

### ISSUE THREAD

**Issue by oska874** [Kenshin/simpread#385]
https://www.ibm.com/developerworks/cn/linux/l-netlink/index.html
进入阅读模式，图片不显示

**Comment by Kenshin** [comment]
它的图片用了相对位置造成加载时发生了 url 错误，所以隐藏了图片。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
