### ISSUE TITLE
导出pdf时图片丢失

### ISSUE THREAD

**Issue by zodiackiara** [Kenshin/simpread#3851]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows10 1909版本

- 浏览器版本 **Edge 版本 101.0.1210.32 

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <[请填写你的地址l](https://www.bigbrosci.com/2017/12/02/ex10/)>

**请描述你的问题**
通过简悦同步助手导出pdf时网页中的图片丢失，但是原网页图片可以手动复制和下载，而且通过md转docx图片不会丢失，应该不是防盗链的问题，如果是bug请尽快修复吧谢谢。
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/61863753/167235964-b36efa41-769d-473c-9c54-3aade4b246b3.png)
![image](https://user-images.githubusercontent.com/61863753/167235984-2191d908-d94c-49fb-aef4-71b47a87f8dc.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
可以的，需要开启下面的选项 

![image](https://user-images.githubusercontent.com/81074/167239328-724ba097-807b-4869-b8f3-9d9be92f2ac6.png)

**Comment by zodiackiara** [comment]
不好意思，我在确认图片代理开启的情况下重新导出pdf，也的确存在同样的问题。
![image](https://user-images.githubusercontent.com/61863753/167749625-1ec76295-9713-4403-8444-d423204ca8bd.png)
![image](https://user-images.githubusercontent.com/61863753/167749892-0c8f4b4f-26f3-4d5c-a30e-602ed2189d4e.png)
[这是原文地址：](https://www.bigbrosci.com/2017/12/02/ex10/)

**Comment by Kenshin** [comment]
我没有遇到这个问题，看下图

![image](https://user-images.githubusercontent.com/81074/167835006-fb60a15d-be69-4809-98fe-3300659bdeb5.png)

请问能稳定复现吗？或确定开启此功能了吗？

**Comment by zodiackiara** [comment]
确定开启了此功能，但还是会出现部分图片丢失的问题，能够稳定复现。

**Comment by Kenshin** [comment]
emmm 你是什么网络环境？可以多测试些页面，e.g.  https://sspai.com/post/69972 少数派的。

另外，会考虑升级此功能以应对类似你这样的情况。

**Comment by zodiackiara** [comment]
![image](https://user-images.githubusercontent.com/61863753/168407701-4815f859-473d-4e35-bf24-2df87be40641.png)
我用的是交大的千兆校园网，这是测试少数派网站的pdf导出截图，问题的奇葩之处在于，它只有这一张图片无法显示，其他图片是能够导出的，目前也不知道问题出在哪里。
目前通过md转docx再手动转成pdf能够凑活使用，只是比较麻烦，希望问题能够尽快解决，谢谢！

**Comment by Kenshin** [comment]
> 我用的是交大的千兆校园网

这个功能在某种程度上也依赖与网络情况，你可以多测试几次。

> md转docx再手动转成pdf

不用这么麻烦，你可以这样：

1. 直接转换为 markdown 用 Typora 打开再导出 PDF
2. 使用 https://simpread.ksria.cn/plugins/details/Lly3mkuSPz 直接通过浏览器导出 PDF
3. 使用 [自定义导出](http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%af%bc%e5%87%ba)，直接导出 docx

另外，我之前说了，会考虑优化这里的逻辑。

**Comment by zodiackiara** [comment]
好的谢谢建议，第一个方法目前很好用，期待后续更新！

**Comment by Kenshin** [comment]
小事情，我需要重开这个 Issues 😄

***

要是喜欢简悦的话，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 然后在下图，帮忙五星好评。 😏  🙏 

![image](https://user-images.githubusercontent.com/81074/168410264-ee4bed7a-5d6f-47fc-909a-4dd64e505596.png)

**Comment by zodiackiara** [comment]
好的，已好评~

**Comment by Kenshin** [comment]
Cool 3ks~

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
