### ISSUE TITLE
右侧一直显示图片转换中

### ISSUE THREAD

**Issue by chipsflying** [Kenshin/simpread#3854]
在阅读模式中，一直显示这几个“图片转换中”，我查看网页上的图片并不多，而且有时候我甚至没有标记图片。
是最近才出现的情况，以前没有发现，所以是我设置上有什么问题吗？
https://sspai.com/post/70641
![image_1651643691880_0](https://user-images.githubusercontent.com/102506599/167275252-b142b649-9605-4393-afb0-9882c923220b.png)

**Comment by Kenshin** [comment]
嗨，建议通下面三个方式自查下：

1. 这个截图看起来是导出离线 HTML 时的提示
2. 导出离线 HTML 不会进入阅读模式后自行运行。
3. 如果你设置了自动化，只有当加入稍后读时才会执行。

**Comment by chipsflying** [comment]
加入稍后读再进入阅读模式目前确实没有再出现这种情况，看来是这原因，谢谢！

**Comment by Kenshin** [comment]
> 加入稍后读再进入阅读模式目前确实没有再出现这种情况

（不加入稍后读）直接进入阅读模式呢？

**Comment by chipsflying** [comment]
https://sspai.com/post/72697
特意试验了一下，还是会转圈。
![uTools_1652018943219](https://user-images.githubusercontent.com/102506599/167300428-c9c9e3ff-d98e-4eca-b380-618f3d73090e.png)

**Comment by Kenshin** [comment]
emmm 你没理解我的意思，我是问：

1. 访问非稍后读的页面有问题吗？
2. （看你的截图）访问稍后读的页面，进入后就是截图的效果？

建议给我录屏说明。

**Comment by chipsflying** [comment]
就是在一个页面直接点击浏览器右上简悦的插件图标进入的状态，这应该是阅读模式吧。

https://user-images.githubusercontent.com/102506599/167320231-0d4b255f-0cc0-4c7f-b076-165c443ac348.mp4

**Comment by Kenshin** [comment]
我知道你的问题了...

不要在标注时 **使用离线 HTML**，在自动化设置那里有说明

![image](https://user-images.githubusercontent.com/81074/167329862-05da944d-88e7-401b-82e5-cedfc85f2026.png)

如果你想使用离线 HTML 的话，标注完手动导出离线 HTML。

***

PS：这个视频的演示也跟你最开始的描述完全不一样...  😂

**Comment by chipsflying** [comment]
好的，麻烦了，谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Kenshin ***@***.***>
发送时间: 2022年5月9日 10:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Kenshin/simpread] 右侧一直显示图片转换中 (Issue #3854)


我知道你的问题了...

不要在标注时 使用离线 HTML，在自动化设置那里有说明

[image]<https://user-images.githubusercontent.com/81074/167329862-05da944d-88e7-401b-82e5-cedfc85f2026.png>

如果你想使用离线 HTML 的话，标注完手动导出离线 HTML。


PS：这个视频的演示也跟你最开始的描述完全不一样... 😂
