### ISSUE TITLE
{{an_org_uri}} 锚点功能的问题

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3859]
测试链接: https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E6%8A%80%E5%B7%A7

---

1.1 设置如下:
- ![1652030650919](https://user-images.githubusercontent.com/65625632/167309578-cea4c67f-2738-496e-96d1-1126f653c61c.png)
- ![1652030696275](https://user-images.githubusercontent.com/65625632/167309593-0b74a0e8-3076-499b-8e3d-798147ad8383.png)
- ![1652030740704](https://user-images.githubusercontent.com/65625632/167309604-fe0606dc-5cd8-471d-a6ae-b78239427a8d.png)

1.2 操作如下:
- ![1652030790853](https://user-images.githubusercontent.com/65625632/167309611-91bbfbc5-8302-4639-9797-af3d785dbf0c.png)

1.3 结果如下:
- ![1652030905247](https://user-images.githubusercontent.com/65625632/167309621-1cbf39b3-3f59-4a4a-833a-b3d527ba67da.png)

---

2.1 修改设置如下:
- ![1652032112047](https://user-images.githubusercontent.com/65625632/167309727-f2fa31c4-a4cc-4378-972b-311e485a21f4.png)
- ![1652032147841](https://user-images.githubusercontent.com/65625632/167309729-4ca0260b-d4ac-4c50-89b6-72433a59e1f7.png)

2.2 操作不变, 结果不变, 图略.

---

3.1 继续修改设置如下:
- ![1652031583346](https://user-images.githubusercontent.com/65625632/167309925-cf337363-fd73-44bf-8558-bb4de36cc7c4.png)
- ![1652031808362](https://user-images.githubusercontent.com/65625632/167309948-f0a33608-5612-4a44-b134-58fc98a2c3c5.png)

3.2 操作不变, 图略.

3.3 结果改变如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167328444-ca3df5b4-50d6-414a-9970-2bb782a28c5a.png)
- ![1652032958490](https://user-images.githubusercontent.com/65625632/167309997-78da90b8-04ec-4e76-9d38-5b83247ffcbc.png)

3.4 这就说明有一个默认存在的标注模板, 强行覆盖了用户对于标注的引用链接的自定义. 用户必须自己写一个模板把它覆盖掉, 然后才能使用引用链接. 但这是不太合理的, 因为这分明是两个图标功能的事.
- ![1652032500330](https://user-images.githubusercontent.com/65625632/167310103-36e3cf2b-ca8f-40f5-aedf-ff6c38257ec3.png)

完了引用链接还不能正常自动地定位到标注的位置.

---

4.1 继续修改设置如下:
- ![1652033222180](https://user-images.githubusercontent.com/65625632/167310203-d5f57c88-0be8-4f35-94c9-77b23b260e4a.png)

4.2 操作不变, 图略.

4.3 结果改变如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167311909-497bb064-90d8-4143-868a-97e2909bcee6.png)

---

5.1 继续修改设置如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167310420-baefc697-0c82-4206-b145-0d37bc11b43c.png)

5.2 操作不变, 图略.

5.3 结果改变如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167310482-6ddb938a-af32-4fdb-a8b1-39daee7adfac.png)
- ![图片](https://user-images.githubusercontent.com/65625632/167310508-e536e787-cbd0-461f-b088-9fa3e51a6b08.png)

5.4 所以结合上述两次试验, int ext org, 三者功能完全紊乱, 就没一个好使的. 前两个好歹还在本地文件以及云盘文件上跳转一下, 虽然没跳转对地方. 而最后一个则干脆就不跳转.

---

6.1 继续修改设置如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167310617-c3dabb49-1614-4a3d-beed-e39b41745048.png)
- ![图片](https://user-images.githubusercontent.com/65625632/167310731-ed6c5ec2-459b-49a4-a7ae-89d45600f56e.png)

6.2 操作改变如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167310803-3a9be0cc-621b-4da1-b152-af74e3c147cd.png)

6.3 结果改变如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167310844-d83a433b-5867-435e-b4e0-ae541b8d1b16.png)
- ![图片](https://user-images.githubusercontent.com/65625632/167311077-4685bec8-fb03-41df-8a91-4890b6373948.png)

总之, 想获取所有标注的原始链接简直太难了, 调了一晚上, 一开始还以为模板哪里写的不对, 后来一步一步测, 最后发现应该是出了bug, 麻烦测试一下吧.
最愁人的是, 之前误打误撞不知道怎么设置好使的, 现在硬是怎么试也回不去了...

**Comment by Kenshin** [comment]
嗨，谢谢这么精细的测试。

这个功能是没问题的，但建议使用 Markdown 模板增强插件，我之前应该跟你说过。

![image](https://user-images.githubusercontent.com/81074/167331242-d32a8095-f15d-43fe-922a-98fde52727c3.png)

***

至于你的问题，可能是因为使用了「引用链接」和「单条导出」造成的，细节再详细确认下。

另外，截图中也有明显错误，**Markdown 模板开启在留空** 肯定会引起异常情况。

**Comment by XMB-7** [comment]
设置如下:
- ![1652064684541](https://user-images.githubusercontent.com/65625632/167332584-80da6349-7376-4649-bec9-b7441dd28477.png)
- ![图片](https://user-images.githubusercontent.com/65625632/167332694-b39eed0e-4283-4b45-9c82-f98304bfe6d2.png)
- ![1652064216260](https://user-images.githubusercontent.com/65625632/167332610-a872a617-06d2-4576-a26e-dbd8de4fb67e.png)
- ![1652064640455](https://user-images.githubusercontent.com/65625632/167332733-1209404a-2176-4cc9-bed7-82549178c1cd.png)
- ![1652064426042](https://user-images.githubusercontent.com/65625632/167333109-abb27696-087c-4f7f-adf2-8fc8c03441c1.png)

如你所说, 开了引用链接, 关了单条导出, 而且保证自定义模板开启但不留空, 同时启用Markdown模板增强插件, 然后取最后一个标注的导出结果到obsidian打开uri. 

结果如下:
- ![图片](https://user-images.githubusercontent.com/65625632/167332956-f03570f5-7487-4887-8ee6-8486e58d0b5e.png)
- ![1652064495779](https://user-images.githubusercontent.com/65625632/167333175-478445dd-9717-4bf1-bd72-69da7ac9009d.png)

最后依然没能正常跳转.

**Comment by Kenshin** [comment]
emmm

我明白你的问题了。

`{{an_org}} `在某些情况下确实有问题，此功能是要严格保障页面结构不能乱掉的，但简悦的阅读模式会改变页面结构。

另外，**Link to Text Fragment** 功能其实并不好用，因为点击后它的「标记」就消失了。

点击的意思是：失去焦点，因此也不仅仅只是点击。并且，一旦原文消失了（这是太正常不过的事情了...）它的作用就等于零。

**所以，最好的解决方案：**

使用 `{{an_int_uri}}` 内部链接，利用同步助手生成永久内链，建议看下 https://github.com/Kenshin/simpread/discussions/3188 的描述。

如果你觉得 `http://localhost:7026/reading/xxx` 有局限性，需要使用外部链接的话，也可以。如果你觉得需要配置阅读列表有点麻烦，也有解决方案。

外部链接解决方案（新）：

原计划本周应该有个新功能上线，但我不确定是否 100% 可以发布，但功能已经可以使用了，你可以自己试试 https://github.com/Kenshin/simpread/discussions/3823

**Comment by XMB-7** [comment]
我其实已经配置了外部链接了, 但有些应用场景必须要用原始链接. 比如飞书妙记, 我需要在obsidian里面点某个标注, 然后直接跳到飞书视频页面去定位播放那句话...这个光跳转到本地导出文件或云盘导出文件是没用的, 所以我才花了很长时间去调这个东西, 没有硬需求, 我就用外部链接了.
而且这个之前是好使的, 我就是心血来潮想改一下模板, 好家伙这一改完不好使了, 怎么也整不回去, 头疼. 我准备稍后换台电脑试试.

**Comment by Kenshin** [comment]
了解你的诉求了。

> {{an_org_uri}} 在某些情况下确实有问题，此功能是要**严格保障页面结构不能乱掉**的，但简悦的阅读模式会改变页面结构。

你可以试试，只标记 **较短且只有中文的内容**，如下图

![image](https://user-images.githubusercontent.com/81074/167336169-13b57bc3-1818-4f8c-9634-5d7e6cdb9461.png)

使用锚点功能是可以使用的。

![image](https://user-images.githubusercontent.com/81074/167336073-ef03332e-d057-4425-afbc-0fa19cb84596.png)
