### ISSUE TITLE
JSbox 版无法分享到Pocket

### ISSUE THREAD

**Issue by kerHbal** [Kenshin/simpread#386]
桌面版本已设置好Pocket，用官方方法同步了JSbox和桌面版的配置，JSbox版的点开以后Pocket还是灰的

**Comment by Kenshin** [comment]
桌面版 进入 选项页 → 高级设定 → 全局 → 开启「同步时是否包含授权服务中的授权码？」 才能将授权码输出。

因为私密性的缘故，默认授权码是不会保存的。

**Comment by kerHbal** [comment]
哦哦我之前改那个貌似没被保存，现在好了
