### ISSUE TITLE
导出markdown时 二级标题 的标记错误

### ISSUE THREAD

**Issue by qiaogaojian** [Kenshin/simpread#3861]
使用导出markdown功能, 二级标题的标记是 - 而不是#, 导致的问题是在Obsidian里渲染异常, 如下图:
![image](https://user-images.githubusercontent.com/22113252/167336676-2e7c1f25-96cd-4102-bb08-de6500c50156.png)
![image](https://user-images.githubusercontent.com/22113252/167336798-2730ece0-c2d5-4259-abed-80ce7ee6eab6.png)
其他级别的标题标记是 # 没有这个问题.

**Comment by Kenshin** [comment]
你是使用了 Markdown 辅助增强插件吗？

在下图设置

![image](https://user-images.githubusercontent.com/81074/167338139-3a204e6d-4006-4242-89d5-886f9b96afa2.png)

```
{"headingStyle":"atx","hr":"---"}
```

Markdown 辅助增强模板有详细说明。

**Comment by qiaogaojian** [comment]
感谢, 试了一下问题解决了

**Comment by Kenshin** [comment]
okay 搞定就好。
