### ISSUE TITLE
配置Markdown 模板辅助增强插件未找到启用按钮

### ISSUE THREAD

**Issue by zzzzssssyyyy** [Kenshin/simpread#3862]
![image](https://user-images.githubusercontent.com/74309824/167337453-9deb451f-8af4-49c1-8385-e4dee703abab.png)实在是找不到这个开启界面在哪里

**Comment by Kenshin** [comment]
看下图

![image](https://user-images.githubusercontent.com/81074/167338038-5e0f20b7-5593-4ab6-a848-9c1d98bc757f.png)

![image](https://user-images.githubusercontent.com/81074/167338059-1207029f-5d97-4db0-b075-c260f2928cc4.png)

**Comment by zzzzssssyyyy** [comment]
omg，在偏好设置里找了半天
