### ISSUE TITLE
iOS版JSbox找不到设置菜单

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#3866]

**Comment by shadu120** [comment]
![FA9CC364-5415-4C51-8658-28FC7B93A169](https://user-images.githubusercontent.com/3023471/167443037-9e709427-1fe8-4ea9-8616-20be6abd2869.png)

ipamini6 15.4.1
找不到设置的菜单。

**Comment by shadu120** [comment]
因为没办法设置系统参数，包括我的token，所以也没办法存储数据？只能一个一个URL复制过去查看吗？

**Comment by Kenshin** [comment]
嗨，不是在阅读模式上设置，如何设置，请看 JSBox 的 [功能介绍](http://ksria.com/simpread/docs/#/JSBox)。

**Comment by shadu120** [comment]
确认了，我的问题。
这个要安装两个东西：【简悦】 和【 简悦阅读器】，我想简单了。。

**Comment by Kenshin** [comment]
小事情，没问题就好~

**Comment by htyfy126** [comment]
JSbox现在的  Safari浏览器扩展是付费功能  那么ios用户不能使用简悦了吗？ 还有别的方法吗？

**Comment by Kenshin** [comment]
@htyfy126 

> JSbox现在的 Safari浏览器扩展是付费功能

请通过 JSBox 确认，而不是这里 😂

> ios用户不能使用简悦了吗

简悦会有 iOS 客户端的。

简悦的 JSBox 版只是简悦扩展端 1.x 部分功能
