### ISSUE TITLE
进入阅读模式后，导出不管是html还是markdown都显示 导出失败，该功能是实验性功能？

### ISSUE THREAD

**Issue by amymorgen** [Kenshin/simpread#3867]
如题 不管是html还是markdown，离线的也导出不了，只有png是能导出的，
url：https://zhuanlan.zhihu.com/p/356247565 
高级账户导出功能就是不正常，卸载了所有插件，重置了设置，就是不可以。
返回到基础版本，可以顺利导出
而且我之前设置好了，能够顺利使用就去洗澡了，中间间隔了20分钟左右，浏览器重启就不可以了。
![Clip_20220509_233322](https://user-images.githubusercontent.com/70929238/167446212-b2b5d45e-34d5-4707-85fd-613908ebea02.png)
。

**Comment by Kenshin** [comment]
看起来有可能是下面的问题造成的：

1. 没有绑定同步助手
2. 使用 [此方式](https://github.com/Kenshin/simpread/discussions/2816) 重新获得高级账户权限。

**Comment by amymorgen** [comment]
非常感谢，我晚上试一下然后给您反馈。

发自我的iPad

**Comment by Kenshin** [comment]
小事情，你可以这么做：

1. 使用 [此方式](https://github.com/Kenshin/simpread/discussions/2816) 重新获得高级账户权限。
2. 关闭浏览器
3. 打开同步助手
4. 重启浏览器
5. 授权并配置同步助手，[教程](https://github.com/Kenshin/simpread/discussions/2754)

**Comment by amymorgen** [comment]
成功了，但是重新授权和重启浏览器都不行，最后是加了一步 重置同步助手的配置，在加上重新授权成功的，仅供参考，在此感谢。

 

发件人: ***@***.*** ***@***.***> 代表 Kenshin Wang
发送时间: 2022年5月10日 11:06
收件人: Kenshin/simpread ***@***.***>
抄送: amymorgen ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 进入阅读模式后，导出不管是html还是markdown都显示 导出失败，该功能是实验性功能？ (Issue #3867)

 

小事情，你可以这么做：

1.	使用  <https://github.com/Kenshin/simpread/discussions/2816> 此方式 重新获得高级账户权限。
2.	关闭浏览器
3.	打开同步助手
4.	重启浏览器
5.	授权并配置同步助手， <https://github.com/Kenshin/simpread/discussions/2754> 教程

**Comment by Kenshin** [comment]
okay 搞定就好，我会记录你提供的方案。
