### ISSUE TITLE
人民网一直出现问题无法解决

### ISSUE THREAD

**Issue by raining1123** [Kenshin/simpread#387]
http://cq.people.com.cn/n2/2018/0904/c365402-32011073.html
http://js.people.com.cn/n2/2018/0904/c360300-32010627.html
例如以上页面，总是显示以下提示：
![image](https://user-images.githubusercontent.com/17892238/45040395-82285900-b098-11e8-91bc-423e7bbc4ff8.png)
更新后又显示“更新后仍无法适配此页面，是否提交？”

**Comment by Kenshin** [comment]
这是由于人民网某些页面的结构改变造成的，更新的前提是已经适配了这种新改变。

你可以等我更新或自行更新。

**Comment by Kenshin** [comment]
已经更新，点击 [更新] 即可完成获取新的适配规则。
