### ISSUE TITLE
目录和标注 与正文重叠

### ISSUE THREAD

**Issue by Huxzhi** [Kenshin/simpread#3870]
- 操作系统 ** MacOS**

- 浏览器版本 **Chrome 100**

- 简悦版本 **2.2.0**

- 发生问题的地址 chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

**目录和标注 与正文重叠**

**截图**

![image](https://user-images.githubusercontent.com/49866441/167543378-b0ec511f-9499-49cb-aadc-e43fc53a72f8.png)

**Comment by Kenshin** [comment]
在较小分辨率下确实存在这个情况。

看下图的临时解决方案

![image](https://user-images.githubusercontent.com/81074/167545582-a35010fb-170d-4715-98fc-7c2d42c3a276.png)

另外，你的分辨率的多大？

**Comment by Huxzhi** [comment]
正文部分

![image](https://user-images.githubusercontent.com/49866441/167546376-d38cf2dd-39d4-4308-a90f-a762d899fcbd.png)

整体宽度

![image](https://user-images.githubusercontent.com/49866441/167546729-5c70a969-be96-4a26-8e54-f62e962d9929.png)


应该不算小了吧，

 我看目录和标注都是固定宽度，能不能正文两边都空出这么多宽度

**Comment by Huxzhi** [comment]
- 目录的开关有没有快捷方式，调整要到高级设置那里去
- 或者增加一个 宽栏 和 窄栏 模式 
    类似 我来
    ![image](https://user-images.githubusercontent.com/49866441/167548186-e5f6d4e8-c67b-45fb-a72a-acac5d9019ea.png)

**Comment by Kenshin** [comment]
谢谢建议，已经记录这个问题了，也有解决方案的，只是暂时的版本没法解决。 😂 

稍后读的临时解决方式

![image](https://user-images.githubusercontent.com/81074/167560620-998b41fe-8dc7-4fb5-8477-543b178bd503.png)
