### ISSUE TITLE
iPad Mini6 JSbox设置dropbox配置失败：“导入发生了错误，请稍后再试！”

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#3871]
在设置简悦配置时，提示信息：“导入发生了错误，请稍后再试！”

已经确认dropbox上已经有simpread_config.json文件，且配置中的access_token是正确的。
复制过程中确认了没有空格。

难道和Dropbox的中文路径`/home/应用/SimpRead/simpread_config.json`有关？

![微信图片_20220510134242](https://user-images.githubusercontent.com/3023471/167556865-5f70cf59-650e-4f4e-8d91-6ab8feb84dda.png)
![微信图片_20220510134524](https://user-images.githubusercontent.com/3023471/167556871-3887b647-f10c-4ea1-ac43-828c62830aa3.jpg)

**Comment by Kenshin** [comment]
emmm 看起来应该没问题...

不过，Dropbox API 改过一次，不知道是否是因为这个原因导致...

你试试直接把 simpread_config.json 直接放到阅读器根目录下，看看能否好使？

**Comment by Kenshin** [comment]
> 按照你的方法，的确配置文件生效了，而且能够保存文档到Dropbox

Cool

> ipad上保存到dropbox的文档，在Chrome稍后阅读中没看到。两者不是自动同步？

不（算）是，原因：

1. 你的数据在 Dropbox
2. 简悦的同步助手虽然支持 Dropbox 的同步，但我说了 https://github.com/Kenshin/simpread/issues/3871#issuecomment-1121976779 导致此方式无法使用，详细说明 https://github.com/Kenshin/simpread/discussions/3171
3. JSBox 的功能只是 1.x 而已，虽然

有种情况（有可能）能实现自动同步：

1. 使用 Dropbox 客户端
2. 开启同步助手的自动同步
3. 当扩展端添加稍后读后，会通过 1和2 自动同步到你的 Dropbox 上面。

但... 这样似乎没有太大的意义，因为 JSBox 没有反向更新的必要。

**Comment by shadu120** [comment]
经过这两天使用，最后一句很赞同，那就先这样吧：）

**Comment by Kenshin** [comment]
哈哈，没问题。

**Comment by sunshineynwa** [comment]
出现了同样的问题，Dropbox的授权码是SL开头的，应该是所谓的临时Token，想借贴了解一下怎么解决？@Kenshin 帖子里面提到的“把 simpread_config.json 直接放到阅读器根目录下” 具体是指JSBox里面的那个目录，是本地脚本目录下的”简悦“、”简悦阅读器“，还是脚本共享目录或者应用根目录呀？目前不导入可以使用，但是不能导出。。。大谢！

**Comment by Kenshin** [comment]
@sunshineynwa 

> Dropbox的授权码是SL开头的，应该是所谓的临时Token，想借贴了解一下怎么解决？

暂时没办法解决了，Dropbox 自己玩的规则，没有永久性 Token 了，细节看 https://github.com/Kenshin/simpread/discussions/3171

> 是本地脚本目录下的”简悦“、”简悦阅读器“，还是脚本共享目录或者应用根目录呀？

简悦 和 简悦阅读器 都放一份试试。

**Comment by qin-gao-tfs** [comment]
> @sunshineynwa
> 
> > Dropbox的授权码是SL开头的，应该是所谓的临时Token，想借贴了解一下怎么解决？
> 
> 暂时没办法解决了，Dropbox 自己玩的规则，没有永久性 Token 了，细节看 #3171
> 
> > 是本地脚本目录下的”简悦“、”简悦阅读器“，还是脚本共享目录或者应用根目录呀？
> 
> 简悦 和 简悦阅读器 都放一份试试。

还是可以解决的. 家里手机电脑一个wifi , 电脑chrome 使用 http server 200 插件, 把本地的 simpread_config.json 丢到 http server 下面. 使其可以被 http://localhost:****/simpread_config.json  方式访问. 随后跑到 jsbox 里面修改简悦代码, 点击最左边icon, 找到main.js 打开. 里面找到 dropbox url , 替换成http://localhost:*****   , 然后把 POST 改成 GET 就可以了.

**Comment by Kenshin** [comment]
@qin-gao-tfs 

Cool~

PS：`http server 200` 是什么？我在 Chrome webstore 搜索了下，没有发现这个扩展。

**Comment by qin-gao-tfs** [comment]
> @qin-gao-tfs
> 
> Cool~
> 
> PS：`http server 200` 是什么？我在 Chrome webstore 搜索了下，没有发现这个扩展。

Web Server for Chrome , 图标是 200 OK!
