### ISSUE TITLE
Assistive Touch 找不到 webhook 的动作

### ISSUE THREAD

**Issue by winter60** [Kenshin/simpread#3875]
插件Assistive Touch 找不到webhook的动作，如果还没有这个功能可否增加一下呀~

**Comment by Kenshin** [comment]
收到，更新后我会通知你~

**Comment by Kenshin** [comment]
嗨，Assistive Touch 升级到 1.1.0 增加了如下功能：

- `Add` 加入了 `插件` `Webhook` 方案

- `Add` 图标在原来的 `font awesome` 和 `http` 的基础上加入了 `svg` 与 `base64`

- `Add` 找回 Assistive Touch

终于可以关闭这个 Issues 了。😁
