### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by pokemon15139** [Kenshin/simpread#3884]
发生问题的地址: <https://pieterhugo.com/THE-JOURNEY>

**Comment by Kenshin** [comment]
嗨， 这种全是照片的页面没有适配的必要，我关闭此 Issues 了。

**Comment by pokemon15139** [comment]
请问这种搜刮到notion有好的办法吗 经常文字注释会错行

**Comment by Kenshin** [comment]
这个页面肯定不行，但如果都是文字居多的（也就是有正文存在）的页面，一般来说是可以直接进入阅读模式的，如果无法识别的话，可以看下 https://github.com/Kenshin/simpread/discussions/3340 解决方案。
