### ISSUE TITLE
改进请求：自定义样式里设定字重后原文的加粗格式消失

### ISSUE THREAD

**Issue by TientJan** [Kenshin/simpread#3885]
简悦某个原始样式中字比较浅，我偏好稍微粗一点的字，就将字重自定义为400

![image](https://user-images.githubusercontent.com/42082682/167992810-aa339e62-c17e-4a75-bb29-a457dcd9191d.png)

![image](https://user-images.githubusercontent.com/42082682/167992767-97546a5a-d2d5-4c0a-93b6-cbafee78e52c.png)
然后原来文本中加粗的部分，字重也变成了400，失去了加粗强调的效果
![image](https://user-images.githubusercontent.com/42082682/167992904-06bc6f9f-2789-49bc-a1ea-b73e1d597bb6.png)
希望能改进一下自定义样式的功能，使得加粗体保持效果不变~

——————————
**更新**：我又测试了一下，发现这个问题是在知乎中有，而 CSDN 中是能够正常显示加粗体的

**Comment by Kenshin** [comment]
嗨，造成这个情况的有下面几种：

1. 某些主题对加粗是有区别对待的，你可以更换不同的主题测试效果。
2. 某些看起来加粗的字体使用了非常正常方案，所以在阅读模式中把它过滤掉了，常见公众号等。

情况1：可以使用 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 来解决
情况2：建议给出 URL 一般来说使用下面的方式也能解决（但不建议这么用）

![image](https://user-images.githubusercontent.com/81074/167995337-c170fb53-53b9-49ff-bfc7-e6924acacd89.png)

**Comment by TientJan** [comment]
感谢回答！
试了一下，确实跟样式有关，但是9个样式中只有一个样式能够正常显示加粗…
但是还有疑惑，如果是跟样式有关系的话，那为什么有的样式在自定义字重前可以显示加粗，自定义字重后就显示不了呢？如果我想用某个喜欢的样式改变字重同时保留加粗效果，有什么办法嘛~

**Comment by Kenshin** [comment]
建议给我 URL 我才好判断。 😂

**Comment by TientJan** [comment]
https://zhuanlan.zhihu.com/p/50422245
知乎上的文章都是这种情况，就随便选一个了~

**Comment by Kenshin** [comment]
类似这样？

![image](https://user-images.githubusercontent.com/81074/168015630-7927c0f8-0966-4dcf-8c13-4eda3b84502e.png)

```
sr-rd-content b {
    font-weight: 500!important;
}
```

![image](https://user-images.githubusercontent.com/81074/168016098-6d53b308-8d75-4767-970c-b106ddf6fcad.png)

**Comment by TientJan** [comment]
感谢感谢~这样就解决了

**Comment by Kenshin** [comment]
哈哈，搞定就好。

我关闭这个 Issues 了。
