### ISSUE TITLE
CSDN代码运行时出错

### ISSUE THREAD

**Issue by Calvin1874** [Kenshin/simpread#3888]
可以识别出代码段，但无法显示代码段的字体颜色区别。[出错的链接在这里](https://blog.csdn.net/ma15732625261/article/details/81978637)
然而该文引用的原文的代码显示是正常的

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
