### ISSUE TITLE
apple 开发文档异常

### ISSUE THREAD

**Issue by linsyorozuya** [Kenshin/simpread#389]
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html

**Comment by Kenshin** [comment]
已添加到站点集市 https://simpread.ksria.cn/sites/details/L4mUzheafw

PS：由于这个链接中文档的代码段写的不是很好，所以请最好在根据你当前实际的主题进行更改。
