### ISSUE TITLE
hi 你好，我购买了高级账户，但是可能没有绑定邮箱，也没有记录UID。在电脑重装系统后，我无法登陆高级会员了。请问应该怎么做？

### ISSUE THREAD

**Issue by LinLuning** [Kenshin/simpread#3890]

**Comment by Kenshin** [comment]
嗨，你需要：

1. 找回 License https://github.com/Kenshin/simpread/discussions/2756
2. 通过 License 找回 UID https://github.com/Kenshin/simpread/discussions/1571

即可解决。
