### ISSUE TITLE
代码块显示异常(启用/未启用代码增强插件都如此)

### ISSUE THREAD

**Issue by WithmeJun** [Kenshin/simpread#3891]
- 操作系统 **Win11**

- 浏览器版本 **Microsoft Edge版本 101.0.1210.39 (正式版本) (64 位)**

- 简悦版本 **版本2.2.0.520**

- 代码块行数显示异常
- 原始代码块
![tmp8EC1](https://user-images.githubusercontent.com/43625897/168037461-186881d3-225a-4dab-b8c0-00f33808e956.png)
-阅读模式代码块
![tmpE147](https://user-images.githubusercontent.com/43625897/168037544-f3ad7c4f-9483-47fd-91eb-5f830395a111.png)

- 发生问题的地址 <https://web.qianguyihao.com/04-JavaScript%E5%9F%BA%E7%A1%80/45-jQuery%E7%9A%84%E4%BB%8B%E7%BB%8D%E5%92%8C%E9%80%89%E6%8B%A9%E5%99%A8.html

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
