### ISSUE TITLE
请问同一网站拥有多个完全相同的本地适配源正常吗, 能删吗

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3894]
![image](https://user-images.githubusercontent.com/65625632/168216105-5806f4ab-9cd4-4e08-a033-cf5310df781c.png)
不知道是怎么出来的, 其它网站有本地适配源也是单一的, 只留一个删掉其余的应该没影响吧? 
顺便问下, 这里面的高亮区域指的是什么.

**Comment by Kenshin** [comment]
> 不知道是怎么出来的, 其它网站有本地适配源也是单一的, 只留一个删掉其余的应该没影响吧?

没有影响，因为这些域名有具体指向性（即具体的 URL）的，只有通过下图（或你的截图）点击保存生成的，但正常情况程序会判断 URL 唯一性，所以我也不确定是如何生成的。

![image](https://user-images.githubusercontent.com/81074/168228013-1a97a7d9-88fb-4207-9517-2fac988f84e4.png)
