### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by imhlq** [Kenshin/simpread#3899]
发生问题的地址: <https://www.bbc.com/zhongwen/simp>

**Comment by Kenshin** [comment]
嗨，我看到你关闭了这个 Issues 是自行解决了？

**Comment by imhlq** [comment]
> 嗨，我看到你关闭了这个 Issues 是自行解决了？

我提交之后，看到类似的issue，我就不重复提交了 2333 #3821

**Comment by Kenshin** [comment]
> 我提交之后，看到类似的issue，我就不重复提交了

哈哈，谢谢。（省得我再搜索关联了  👍 

要是支持的话，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 然后在下图，帮忙五星好评。 😏  🙏 

![image](https://user-images.githubusercontent.com/81074/168410264-ee4bed7a-5d6f-47fc-909a-4dd64e505596.png)

**Comment by imhlq** [comment]
> 

嗯嗯，刚还买了一波会员，作者加油！

**Comment by Kenshin** [comment]
哈哈，谢谢支持。

PS：阅读模式相关的功能是基础功能，不用高级账户即可。  😏
