### ISSUE TITLE
导出的 HTML 可以在 iPhone 下浏览

### ISSUE THREAD

**Issue by WuhanSy** [Kenshin/simpread#390]
首先我想说，非常好的项目，在此感谢开发者！
1.生成html文件，并没有很好的适配移动端。用Iphone打开html文件时，显示图片时尺寸过大
2.裁剪成图片时，也出现了同样没有适配移动端的问题，图片模糊，影响使用

**Comment by Kenshin** [comment]
1. 确实没有适配移动端。
2. 图片模糊估计是尺寸造成的。（我不是很理解你说的 `图片模糊` 是什么意思）

同样，这两个需求并没有移动端使用的诉求，所以自然对移动端不是 `友好`。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [离线下载](http://ksria.com/simpread/docs/#/离线HTML) 的功能，通过此功能下载的 HTML 增加了手机端的适配。

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
