### ISSUE TITLE
[功能请求] 使用Live Editor简易编辑的结果能保存进本地适配源, 或是扩充本地资料库的标注功能.

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3902]
目前, 隐藏元素是能自动保存的, 亦即自动添加进本地适配源. 但Live Editor的简易编辑却无法自动保存或者说添加进本地适配源, 不知能否做到. 
目前我用Live Editor简易编辑之后都会本地导出, 以此来保存内容修改的结果. 但是发现这种方式对于二次修改非常不友好. 比如要想对一篇稍后读进行二次标注修改, 就得进入阅读界面, 但由于内容修改压根不进本地适配源, 所以之前的内容修改直接重置了, 所以要想在进行标注修改的同时保留之前所做的内容修改, 就必须手动把之前的内容修改重新复现一遍, 然后再本地导出, 这是极其繁琐的.
所以不知道能否做到, 把内容修改也保存到本地适配源, 就类似除了高亮区域和隐藏列表以外再加一栏保存某些文本框的内容修改.
![image](https://user-images.githubusercontent.com/65625632/168413018-27a807b2-643d-4f40-a46d-0401b6ea17a1.png)

---

另外还有一个思路是允许用户在用浏览器打开本地导出html并进入阅读模式时可以添加标注. 同时提示用户禁止后续再在原始页面上做标注修改.
![image](https://user-images.githubusercontent.com/65625632/168413169-3c06ea8d-a786-4b0b-b729-ac7d2d5c0b43.png)
换而言之就是, 一旦用户使用live editor修改了原始页面上的任何文本内容, 那么后续的所有标注改动都只能发生在本地的资料库里. 
这样也能达成预期的功能.

**Comment by Kenshin** [comment]
emmm

如果是隐藏元素的话，可以考虑；但如果是修改内容的话，可能「很麻烦」。

不过，你的诉求我理解，我看看能否用其它方式解决这个问题。

**Comment by XMB-7** [comment]
> 换而言之就是, 一旦用户使用live editor修改了原始页面上的任何文本内容, 那么后续的所有标注改动都只能发生在本地的资料库里.

或许第二种方案更实际一些, 毕竟修改文本内容还可能涉及到修改带有标注的文本内容. 如果要保证修改后的标注仍与原始页面上的标注一一对应, 感觉处理起来可能更加麻烦. 
所以还不如割裂开, 如果用户想要修改文本内容, 那就直接到本地的资料库里面用简悦来二次标注本地导出的html文件, 然后通过外部链接即可正常查看自行修改的结果.
如果不能对本地文件进行二次标注, 而只能通过打开原始链接然后进入阅读模式再进行二次标注的话, 感觉较难实现保留下来之前的修改结果.

**Comment by Kenshin** [comment]
其实（有可能）不用那么麻烦，如果加载的是直接加载的修改后的内容就行了。

但我不确定能否实现… 😂

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
