### ISSUE TITLE
打开浏览器总是跳出简悦的设置页

### ISSUE THREAD

**Issue by lanxiang-gua** [Kenshin/simpread#3905]
win端chrome，浏览器的首页设置并非简悦。如何设置才能让设置页不跳出来？

**Comment by Kenshin** [comment]
emmm 不应该的，请问：

1. 你是什么版本的简悦？
2. 从什么渠道安装的？
3. 什么浏览器？
4. 你的浏览器禁用了什么权限或者类似的操作？

**Comment by lanxiang-gua** [comment]
1. 是2.2.0版
2. google插件商店下的，少数派买的会员
3. chrome浏览器
4. 浏览器没有禁用什么权限，除了关闭了一些隐私权限
5. 看来正常设置不会跳出来，我自己研究研究。我平时用同步obsidian功能都是正常的，其他功能很少用。

**Comment by Kenshin** [comment]
1 ～ 4 没问题。

最好能明确说明什么情况「跳设置页」，方便的话，录屏更好。

一般在阅读模式使用某些导出功能的时候，如果授权失效，会提示自动授权，并新开设置页。

也就是说，只有你操作了某些功能，并出现提示才会出现选项页。

还有一种情况：你「误把」插件的选项页当做「设置页」

**Comment by lanxiang-gua** [comment]
很简单的情况，只有打开浏览器时会出现，使用浏览器时不会跳出来。首页设置检查过是正常的，不是插件页。而且也不是每次打开浏览器都会出现（也许是浏览器抽风）

你说的导出功能那里，我能理解这种情况，之前设置导出到obsidian时出现过，也已经解决了，目前导出功能是正常的。

也就是说，在我并没有使用插件时，设置页会偶尔随着浏览器的打开而跳出。

最后，打扰了，感谢作者的回复。

**Comment by Kenshin** [comment]
> 只有打开浏览器时会出现

emmm 还有种情况有可能会造成这个问题：在 Cookies / 历史记录的数据等类似内容被清除后。

**Comment by lanxiang-gua** [comment]
破案了应该是的，想起来我有装TrackOff的软件，自动清除cookies

**Comment by Kenshin** [comment]
> 破案了应该是的，想起来我有装TrackOff的软件，自动清除cookies

 😂 它有 黑名单 / 白名单 机制吗？

**Comment by lanxiang-gua** [comment]
有的，我把 ksria.com 加进白名单就没跳出来过了

**Comment by Kenshin** [comment]
okay 解决就好~

另外，还有 `simpread.pro` `simpread.ksria.cn`
