### ISSUE TITLE
[bug] 手动或者暂定自动化, 自动化增强插件却依然起效.

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3906]
在如下设置下, 添加标注, 依然会自动进行导出. 只有把这个插件禁了, 才能实现预期的暂停自动化的效果.
将自动化设为手动也是一样的结果. 

![图片](https://user-images.githubusercontent.com/65625632/168425397-15c46cc9-20c1-478c-ae7d-a38b64a37f1a.png)
![图片](https://user-images.githubusercontent.com/65625632/168425402-f95db5f4-990a-48f9-b647-ed8f3ae61362.png)

**Comment by Kenshin** [comment]
okay 明天确认下。

**Comment by Kenshin** [comment]
你的意思是指：

> 禁用 1 后但是 2 3 4 仍可以使用？

如果是的话，这是正常的。因为这个插件的「级别」比自动化高，而且 234 只能其实跟 1 无关。

不过，跟之前的几个建议一样，确实有实际场景且合理，我会考虑的。

**Comment by casparlin322** [comment]
我觉得他可能是说：即便没有设置任何自动化方案，进行“保存到 简悦.稍后读”的操作，仍然会执行”之前设置过的自动化操作”，除非把这个插件禁用了。
因为我也遇到了相同的问题，我已经想上图一样把自动化操作都删除了，现在保存稍后读，还是会触发保存到notion，保存到html等操作。

**Comment by Kenshin** [comment]
> 因为我也遇到了相同的问题，我已经像上图一样把自动化操作都删除了，但是现在保存稍后读，还是会触发保存到notion，保存到html等操作。

正常操作不能出现这个情况，如果能稳定复现的话，只有一种情况：

> 删除完自动化后，并没有刷新当前页面而直接再次使用。
