### ISSUE TITLE
notion授权失败与inoreader内无icon显示

### ISSUE THREAD

**Issue by zwbpu** [Kenshin/simpread#3909]
1. 使用简悦授权notion，在昨晚能够授权但仅能授权一个page，根据GitHub教程尝试解决后，notion无法授权，随后根据帮助（GitHub）尝试解决问题，仍无法授权。其显示：点击授权notion，提示授权中（右上角弹窗），但是经过一段时间等待后无授权成功弹窗弹出。、
2. 最近新接触RSS，使用inoreader进行RSS收集、阅读。尝试收集进入简悦稍后读（RSS内嵌已打开），但是进入inoreader页面无icon显示，即使通过简悦帮助文档内的路径进入inoreader也无法显示（使用的是列表模式--点击文章--进入全文阅读）。阅读的内容是通过Werss提供的微信公众号订阅源

**Comment by Kenshin** [comment]
> 问题一 

你可以使用 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2345217 提到的方式，另外 https://github.com/Kenshin/simpread/discussions/1773 和 https://github.com/Kenshin/simpread/issues/3603 里面也有一些其他用户的解决方案，你也可以参考下。

> 问题二

解决方案请看这里 https://github.com/Kenshin/simpread/discussions/1507

**Comment by zwbpu** [comment]
> > 问题一
> 
> 你可以使用 [#1773 (comment)](https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2345217) 提到的方式，另外 #1773 和 #3603 里面也有一些其他用户的解决方案，你也可以参考下。
> 
> > 问题二
> 
> 解决方案请看这里 #1507


问题一：尝试使用了您的方法（暂时还未使用notion增强插件，所以其中部分方法未尝试），并没有解决其问题。在其他issue里看到他人提供控制台，于是也截了几张图，麻烦您稍微看一下。如果需要，配置文件也能够通过Telegram与您沟通。
1. 使用同步助手，添加配置文件，尝试授权notion
![使用同步助手](https://user-images.githubusercontent.com/79553396/168459131-515dce9e-d4ab-4b24-8a11-5ec3643007d8.png)
2. 未使用同步助手，添加配置文件，尝试授权notion
![授权高级账户](https://user-images.githubusercontent.com/79553396/168459150-03bab430-2a32-499d-8d76-da69b1b876be.png)
3. 参照方法二：重新安装后未进行任何操作（未导入配置文件，未打开同步助手），尝试授权notion
![Snipaste_05-15_13-42](https://user-images.githubusercontent.com/79553396/168459171-6e62f041-0f21-4fd4-bbd5-faf9ae7cc839.png)

**Comment by Kenshin** [comment]
嗨，你可能没有理解解决方案。

1. 同步助手和授权 Notion 无关
2. 你截图的内容恰恰说明了因为你的 Notion Page 结构特别造成的（这不是你的问题，因为简悦使用了私有 API 造成的）

所以，解决方案还是使用 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2345217 除此之外，在配置时，先不要使用同步助手，同时看看下面的方式：

1. https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2347194

2. https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358

如果还是不行，建议新注册个账户，然后试试 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358 提到的解决方案一

PS：比你复杂的情况，通过上面这些方式都能解决 https://github.com/Kenshin/simpread/issues/3897#issuecomment-1126628806
