### ISSUE TITLE
😭安装之后默认配置可以用，但是配置以后就无法进入阅读模式

### ISSUE THREAD

**Issue by geekyouth** [Kenshin/simpread#391]
安装之后默认配置可以用，但是配置以后就无法进入阅读模式。

黑名单和白名单都是空的，为什么爱范儿文章无法进入阅读模式呢？

![image](https://user-images.githubusercontent.com/12899262/45263692-fb40fb00-b460-11e8-96bb-2f9b0b6ee3c9.png)

急得我直跺脚💨😤

**Comment by Kenshin** [comment]
最简单的办法：

**重新安装** 或 **清除数据（即：恢复初始化）**

***

初学者可以看 http://ksria.com/simpread/docs/#/入门指南（-操作指引-）

以及 http://ksria.com/simpread/docs 相关的文档。

**Comment by geekyouth** [comment]
初始化以后，数据丢失，我想同步数据到云端

**Comment by Chihiromis** [comment]
我也有这个问题 每次设置完就不能使用了 要清除数据。。请问有解吗

**Comment by Kenshin** [comment]
@Chihiromis 

很奇怪的现象，你这样做：
- 重新安装
- 在确保能有的情况下，导出配置
- 然后按照你认为无法使用的方式配置
- 确保重现问题后，导出配合

把两份配置文件给我，我看看是什么问题。

**Comment by Chihiromis** [comment]
[simpread-config-2019年03月29日 15_59_12.zip](https://github.com/Kenshin/simpread/files/3021546/simpread-config-2019.03.29.15_59_12.zip)

你好 非常感谢你的回复 这是我的配置文件 第一次上传文件。。不知这样可以吗 

每次我清除数据后 重新设置好是没问题的 可以正常运行 但如果我再次设置 稍作修改 不过是基础设置 还是高级设置 一刷新后 简悦就不能用了 任何网站都是灰色的。。。

**Comment by Chihiromis** [comment]
配置文件重新导入 也会引起这个问题 即简悦在任何网站都是灰色的无法使用 只能清楚数据

**Comment by Kenshin** [comment]
@geekyouth @Chihiromis 

有可能是个 Bug （ 只能说是疑似... ） 但下个版本会解决这个问题。

临时解决方案：

***

选项页 → 高级设定 → 黑名单 加入任意一个内容，如不存在的网址 `ssss.com` 即可解决。下图

![image](https://user-images.githubusercontent.com/81074/55284655-82c66b00-53ad-11e9-88a8-62d334f964ba.png)

**Comment by Chihiromis** [comment]
好的 那我还是设置的差不多就好了 不然一不小心又得重新设置

**Comment by Kenshin** [comment]
@Chihiromis 
下个版本就会修复这个问题，下个版本预计下周发布。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，其它更新包括：

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)

**Comment by ccdgyro** [comment]
您好。很喜欢您的想法，但我在打开阅读模式后，网页界面就卡死了，请问有是否有其他用户也遇到过类似的问题呢？

**Comment by Kenshin** [comment]
@ccdgyro 

请告知具体 URL 还是说，每个页面都有这个问题？

**Comment by Kenshin** [comment]
@ccdgyro 

我在 https://github.com/Kenshin/simpread/issues/1179 回复你了。
