### ISSUE TITLE
谷歌简悦插件设置页面乱码

### ISSUE THREAD

**Issue by fidding** [Kenshin/simpread#3912]
![image](https://user-images.githubusercontent.com/10766926/168465851-e03c664e-b721-49f2-8746-5c1673e7bcb8.png)

**Comment by Kenshin** [comment]
嗨，重启浏览器即可。

**Comment by Kenshin** [comment]
嗨，我看到你的 https://github.com/Kenshin/simpread/issues/1000#issuecomment-1126904735

提示下：这种情况重启浏览器，而不是重装简悦。 😂

**Comment by fidding** [comment]
重启浏览器试了下并不行，我已经重新安装了(配置导出导入)。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 谷歌简悦插件设置页面乱码 (Issue #3912)





 
嗨，重启浏览器即可。

**Comment by Kenshin** [comment]
哈哈，3月份的 Issues 今天才回复~ 😂
