### ISSUE TITLE
同步助手无法启动

### ISSUE THREAD

**Issue by keQsia** [Kenshin/simpread#3913]
同步助手无法启动，打开显示下面的报错信息：
Uncaught Exception:
Error::ENOENT::no such file or directory,open '\l?\C:\Users\...
\AppData\Local\Temp\1sxsAgFtMOHpKypqb9CL9sFC5BF\resources\a...\package.json
at Object.openSync(fs.js:462:3)
at Object.func [as openSync](electron/js2c/asar.js:140:31)
at Object.readFileSync(fs.js:364:35)
at Object.fs.readFileSync(electron/js2c/asar.js:542:40)
at Object.internalBinding.internalModuleReadJSON(electron/js2c/asar.js:664:19)
at readPackage (internal/modules/cjs/loader.js:256:34)
at readPackageExports(internal/modules/cjs/loader.js:308:15)
at applyExports (internal/modules/cjs/loader.js:450:20)
at resolveExports (internal/modules/cjs/loader.js:513:23)
at Function.Module.findPath (internal/modules/cjs/loader.js:637:31)

**Comment by Kenshin** [comment]
嗨，使用 22位版本，解压缩到任意目录，即可解决。

**Comment by iFryRice** [comment]
> 
请问，在遇到上述问题对同步助手进行重新配置之后，开机无法自动启动，需要怎么解决吗？

**Comment by Kenshin** [comment]
@iFryRice 

开机自启的解决方案 https://github.com/Kenshin/simpread/discussions/2011

另外，新版同步助手会解决无法自动的问题。

**Comment by iFryRice** [comment]
> @iFryRice
> 
> 开机自启的解决方案 #2011
> 
> 另外，新版同步助手会解决无法自动的问题。

问题已解决，感谢提醒。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 单例运行

当同时运行多个同步助手时，仅确保只有一个运行成功，就可以解决 7026 端口因多开同步助手而导致的占用问题。

同时也修复了开机无法自启动的问题。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
