### ISSUE TITLE
标注的开关图标没有找到

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3915]
标注的开关图标也没有找到，是什么原因？正常右侧有标注那些开关按键？这个是什么原因？
![image](https://user-images.githubusercontent.com/8450915/168471592-8c0dd970-4ae6-4315-bee9-f31cfdf423ff.png)

_Originally posted by @angel126 in https://github.com/Kenshin/simpread/discussions/3914_

**Comment by Kenshin** [comment]
@angel126

我把你的问题转移到了这里，并删除了错误位置的内容。

***

因为你给出的信息太少，我没法判断。

先导出你的配置文件，然后选项页 → 共通 → 重置你的思´数据（不是清除全部数据）。

再看看你的问题是否出现？然后根据 https://github.com/Kenshin/simpread/discussions/3768 的提示设置你的选项。

如果你没有稍后读数据的话，上面的方式就没问题，否则一定要实现备份好你的配置文件。

然后再通过这里联系我，我帮你还原稍后读数据。

**Comment by angel126** [comment]
感谢指导，目前重置以后可以了，工具栏重新出现了!
[image](https://user-images.githubusercontent.com/8450915/168512104-88c6f735-9022-4a38-8717-57f0e2568c37.png)
之前的配置，是需要重新配置还是可以恢复？稍后读的数据应该如何还原？

**Comment by angel126** [comment]
感谢指导，目前重置以后可以了，工具栏重新出现了!

![image](https://user-images.githubusercontent.com/8450915/168512359-3dbd70f7-0558-4762-80cb-ee09ce34f70b.png)

之前的配置，是需要重新配置还是可以恢复？稍后读的数据应该如何还原？

**Comment by Kenshin** [comment]
> 是需要重新配置还是可以恢复？

因为没有多少配置项，或者仍可以通过教程重新设置一次，用不了多长时间。

> 稍后读的数据应该如何还原？

可以的，但需要有一定动手能力，或者把正确和错误的配置文件给我（不要发到这里），我建议你自己试试，如果不愿意的话，我来帮你弄。（但没法马上帮你处理。

所以，你看如何选择？

**Comment by angel126** [comment]
是在没有办法恢复配置，那也只能重新做一次，其实不熟悉重新做一次还是很费时间，这个希望以后可以优化。
稍后读数据恢复，具体应该怎么做，我先试试吧？
是这个教程吗？https://github.com/Kenshin/simpread/discussions/2727

**Comment by Kenshin** [comment]
> 是这个教程吗？https://github.com/Kenshin/simpread/discussions/2727

不是的。

简单的说，打开旧配置文件，需要通过 https://jsoneditoronline.org/ （或类似 JSON 格式化工具）对内容进行格式化。

然后找到 `unrdist`  `collections` 前者是稍后读数据；后者是合辑数据，将这两个内容复制到新配置文件，保存。

![image](https://user-images.githubusercontent.com/81074/168517558-73aa835c-a6f5-493b-af93-0c2e910786ff.png)

接下来：

1. 没有使用同步助手的话，直接导入新配置文件后即可。

2. 使用同步助手的话，覆盖原来位置的 simpread_config.json 然后刷新选项页，看看稍后读是否正确，即可。

***

下个版本会解决这个手动过程。

**Comment by angel126** [comment]
好像搞不定，我直接把内容复制到新的，没成功，如果不太着急的话，是可以等下个版本到时候，可以恢复稍后读的内容是吗？或者我怎么发给你，方便帮忙？

**Comment by Kenshin** [comment]
我为此专门写了一个教程，你可以看下 https://github.com/Kenshin/simpread/discussions/3940

如果还是搞不定的话，把新旧配置配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3915

今天在出差，有点忙，只能做到尽量处理。

**Comment by angel126** [comment]
邮件昨天已发，如果有空的话，请帮忙看看。按着3940的教程操作没有成功。
![image](https://user-images.githubusercontent.com/8450915/169700379-f149d264-4aa9-4778-bf9a-417091cba469.png)

**Comment by Kenshin** [comment]
好，搞定后我会通知你。

**Comment by Kenshin** [comment]
嗨，我给你回复邮件了，请通过下图方式导入

![image](https://user-images.githubusercontent.com/81074/169945735-6d219aa4-25f4-4f46-9633-d5c2b80d0a1a.png)

导入后，选择开启自动同步并覆盖本地的配置文件

![image](https://user-images.githubusercontent.com/81074/169945786-ad67897c-eda2-4133-bcb0-7e2e0010407c.png)

覆盖后，重启浏览器，确认你的问题是否已经修复了。

**Comment by angel126** [comment]
![image](https://user-images.githubusercontent.com/8450915/169960908-88969778-4f7c-437c-9c48-25e75fd6de4c.png)
导入失败是为啥？

**Comment by Kenshin** [comment]
我确认了一次给你的配置文件没有问题。
