### ISSUE TITLE
同步配置文件的问题

### ISSUE THREAD

**Issue by KK-3458** [Kenshin/simpread#3916]
一开始，我是在Windows电脑上首次购买登录成为高级账户的，而且由于新手，东搞西搞也是设置了一些参数
然后回到家想在自己的mac电脑也同步数据过来，但由于自己心急，没看仔细，胡乱一通瞎搞结果把同步助手以及坚果云里面的原先在Windows电脑配置好的配置文件给重置了，然后自己又得重新来一通设置唉累
结果现在回到办公室了，想要把这个在mac里面同步好的配置文件覆盖到我的microsoft edge浏览器中，结果死活覆盖不了，这到底是怎么一回事呢唉，help me！！！！

mac的配置
<img width="265" alt="Snipaste_2022-05-15_20-27-18" src="https://user-images.githubusercontent.com/66560506/168473595-f6ab422f-79ff-4740-b950-ca595d12ad8d.png">
![Snipaste_2022-05-15_20-24-17](https://user-images.githubusercontent.com/66560506/168473631-5a87a70e-5fc3-490b-8065-d3da655e9de8.png)

windows同步助手设置
![image](https://user-images.githubusercontent.com/66560506/168473446-55f26c70-2ede-4525-b449-059c9b83ceaa.png)
对应坚果云的设置
![image](https://user-images.githubusercontent.com/66560506/168473474-e2522e84-3ee1-41ae-93e2-175a49d17033.png)

问题就是在mac配置好的数据同步不过来，怎么回事呢？
登录使用配置文件登录，配置环境用的是同步文件里的数据，也没用啊

**Comment by Kenshin** [comment]
嗨

你可以使用历史记录还原到任意时间点的数据 https://github.com/Kenshin/simpread/discussions/3165

在新的电脑，分别安装同步助手与扩展端，然后将坚果云的配置文件下载到本地，然后在手动导入简悦就行了。

也有自动方案，但对于你来说，这是最简单的方案。

**Comment by Kenshin** [comment]
简悦的数据导入很灵活，建议看下

[这篇教程](https://kb.simpread.pro/#/page/%E5%A4%9A%E8%AE%BE%E5%A4%87%E5%90%8C%E6%AD%A5%E6%96%B9%E6%A1%88)

**Comment by KK-3458** [comment]
不好意思，我想说明的一点就是它并没有出现提示配置文件损坏的红色框框哦！
反而，我导入网盘里之前在mac配置好的配置文件的时候，并没有同步过来之前在mac上的设置，我知道一部分原因可能是因为之前在mac的时候没有选择服务里的那个同步授权码，但是我的定制导出、增强导出、自动化也都没有同步，这是怎么一回事呢？究竟是怎样才能做到导入配置文件，然后简悦的配置就都跟之前电脑配置的一样了？
ps，昨晚无法实现在windows电脑的配置同步，所以我还是自己在那台电脑又去设置配置了
pps，我现在mac和window电脑设置的同步文件都是坚果云里面的同一个（两个电脑都有安装同步助手），也都配置了自动方案（当加入标注的时候会自动导出html），然后标注了之后在简悦的稍后读就能看到我标注的这篇文章了 （比如24小时回顾以及一周回顾），但是在A电脑的稍后读不能看到B电脑的稍后读文章，就是它们两者的稍后读不回同步，那这样是不是只要把标注的都加入稍后读就都能在两台电脑稍后读看到了，emm能不能实现自动化，加入批注的时候都加入稍后读？
emm我也只是个新新手，很多都不懂， 但也很想搭建一个自己的知识管理系统，希望可以多多指教啦～～～谢谢！！

**Comment by Kenshin** [comment]
emmm 听你的描述似乎是因为自动同步没有开造成的。

建议根据教程从新设置（或比对你的配置与教程有什么区别）

1. [配置同步助手](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)

2. [配置增强导出](https://kb.simpread.pro/#/page/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)

3. [配置知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)

确保你的配置没有任何问题的情况，再看下 [同步配置文件的方式](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%8A%E5%85%B6%E5%90%8C%E6%AD%A5)

**Comment by KK-3458** [comment]
对的，抱歉真的，我没有检查，mac的自动同步被我改来改去没有打开。。。然后打开了就好了
谢谢简悦，感觉真的挺好用~点个赞~~
不过小白入门还是要有点耐心的哈哈哈

**Comment by Kenshin** [comment]
哈哈，小事情。

简悦是那种非常灵活的产品，甚至于我都不会「要求」用户用唯一的方式来使用简悦。所以，可能对用惯了直接上手 App 的用户来说，可能需要个思维转变。

但简悦都大量的适合初级用户的保姆级教程，再加上使用了坚果云的历史记录，所以随便怎么折腾都 OK。

建议折腾配置的时候（毕竟你的配置不需要总是变来变去，对吧），看看这篇官方出品的折腾守则 https://github.com/Kenshin/simpread/discussions/3768

***

要是喜欢简悦的，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图，请帮忙五星 + 好评

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by KK-3458** [comment]
好的，感谢~
