### ISSUE TITLE
同步助手报错，无法启动

### ISSUE THREAD

**Issue by oopo0** [Kenshin/simpread#3917]
之前是正常使用的，今天系统启动后同步助手即报错，无法正常启动，之前的配置也失效了。

同步助手报错如下：
![图片](https://user-images.githubusercontent.com/67009994/168510446-3ec088b7-0350-4fdd-a0a8-1a8f18530197.png)
![图片](https://user-images.githubusercontent.com/67009994/168510476-af4ecf17-fec1-4d9a-8aeb-a7c4507b898c.png)

简悦版本：
![图片](https://user-images.githubusercontent.com/67009994/168511079-963ababf-8cc3-4ab9-8c67-0ad833e7201c.png)

浏览器版本：
![图片](https://user-images.githubusercontent.com/67009994/168511333-79fa0236-ed35-40d5-8c11-aafef164cda5.png)

系统如下：
![图片](https://user-images.githubusercontent.com/67009994/168510813-c37977ea-5d17-4ca1-9869-46a9ce29da26.png)

**Comment by Kenshin** [comment]
报错是因为 7026 端口占用造成的，简单的说，应该是同步助手运行了不止一次。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 单例运行

当同时运行多个同步助手时，仅确保只有一个运行成功，就可以解决 7026 端口因多开同步助手而导致的占用问题。

同时也修复了开机无法自启动的问题。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
