### ISSUE TITLE
起点小说网乱码

### ISSUE THREAD

**Issue by kid-y** [Kenshin/simpread#3927]
干净的阅读起点小说网的小说时，点击阅读模式，全是乱码。

**Comment by Kenshin** [comment]
嗨，我随便找了个页面 e.g. https://read.qidian.com/chapter/AV3GOV0RM6Q3v1oFI-DX8Q2/6zcbnuLz0kL4p8iEw--PPw2/

是没问题的。

![image](https://user-images.githubusercontent.com/81074/168713974-41db8724-0598-4b28-884b-ee7ed45d5c5d.png)

在 **隐身模式下仅使用简悦的方式** 或者告诉我出问题的 URL

**Comment by kid-y** [comment]
我刚发视频，由于文件过大，被退回了。
普通章节是可以直接使用，但是在收费章节中，启动阅读模式就会乱码，safari浏览器的阅读模式也会乱码。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 起点小说网乱码 (Issue #3927)





 
嗨，我随便找了个页面 e.g. https://read.qidian.com/chapter/AV3GOV0RM6Q3v1oFI-DX8Q2/6zcbnuLz0kL4p8iEw--PPw2/
 
是没问题的。
 

 
在 隐身模式下仅使用简悦的方式 或者告诉我出问题的 URL

**Comment by Kenshin** [comment]
不要通过邮件发，进入 https://github.com/Kenshin/simpread/issues/3927 提交视频。（当然也不能过大，好像 10m 限制）

**Comment by kid-y** [comment]
https://user-images.githubusercontent.com/67737889/168717100-c0cd19c9-3bff-4589-b208-e4754344df50.mov

**Comment by Kenshin** [comment]
okay 视频看到了。

> 普通章节是可以直接使用，但是在收费章节中，启动阅读模式就会乱码，safari浏览器的阅读模式也会乱码。

emmm 一般来说，有「付费墙」的页面都不会被主动适配，如果主动适配肯定能解决，所以我也帮不了你。😂

**Comment by kid-y** [comment]
好吧，感谢你的回复。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 起点小说网乱码 (Issue #3927)





 
okay 视频看到了。
  
普通章节是可以直接使用，但是在收费章节中，启动阅读模式就会乱码，safari浏览器的阅读模式也会乱码。
  
emmm 一般来说，有「付费墙」的页面都不会被主动适配，如果主动适配肯定能解决，所以我也帮不了你。😂
