### ISSUE TITLE
提示「插件：代码段增强」功能出错

### ISSUE THREAD

**Issue by RoweMann** [Kenshin/simpread#3929]
使用阅读模式访问[此网站](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)时候，提示插件：代码段增强」功能出错。
提示如下图所示：
<img width="595" alt="74c397d5e218f108e2dd83d15b43e300" src="https://user-images.githubusercontent.com/84637248/168718098-b1c6bc14-9562-4388-862d-a66e3a24756d.png">

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
