### ISSUE TITLE
聚焦模式高亮在某些网页元素上不生效

### ISSUE THREAD

**Issue by DiamondYuan** [Kenshin/simpread#393]
复线方法
1 打开百度 https://www.baidu.com/
2 开启聚焦模式
3 鼠标放到百度的图标上

解决方案
提高 css 的优先级 不提pr了。

```
.simpread-highlight-selector{
    background-color: #fafafa !important;
    outline: 3px dashed #1976d2 !important;
    opacity: .8 !important;
    cursor: pointer !important;
    transition: opacity .5s ease !important;
}
```

**Comment by Kenshin** [comment]
3ks

你可以自己把这段加到你的配置文件中 → [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

解决了此问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
