### ISSUE TITLE
我的高级账户不能找回

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3930]
我的高级账户不能找回

_Originally posted by @dahulun in https://github.com/Kenshin/simpread/discussions/1573#discussioncomment-2764180_

**Comment by Kenshin** [comment]
@dahulun

我帮你新建了一个 issues ，解决方案看这里 https://github.com/Kenshin/simpread/discussions/1571

**Comment by Kenshin** [comment]
@dahulun

请不要随便在教程里面提问，我已经帮你把问题转移到了这里，请录屏说明。

另外，我没有 QQ。

**Comment by dahulun** [comment]
这是我的激活码：k9sg-bniy8w-ptkli9-hqxn，我已经重新UID，按照你的教程操作一遍还是不行。我也不会录屏，你看看有没有其他办法帮助我激活，谢谢了。

**Comment by Kenshin** [comment]
兑换码不要暴露出来.... 我帮你把 reset 次数减少了一次。

在 选项页 > 账户 > 找回 UID → 输入你刚才给我的兑换码，即可。

![image](https://user-images.githubusercontent.com/81074/168744632-d8a0840a-07b5-4ed3-8647-b4f5e947e12e.png)

如果无法使用，请截图告知。

**Comment by dahulun** [comment]
![image](https://user-images.githubusercontent.com/100451422/168747638-0259bf83-c0b2-4743-b104-7d05e35db1f7.png)
我重新找回一次，下载一个配置文件，还是没有激活

**Comment by Kenshin** [comment]
....

刚才不是跟你说了吗？ **选项页 > 账户 > 找回 UID → 输入你刚才给我的兑换码**（把 k9sg-**** 填入 ）

![image](https://user-images.githubusercontent.com/81074/168744632-d8a0840a-07b5-4ed3-8647-b4f5e947e12e.png)

**Comment by dahulun** [comment]
我是按照你说的填入找回了，找回后提示我下载文件

**Comment by Kenshin** [comment]
> 我是按照你说的填入找回了，找回后提示我下载文件

刚才被你绕晕了，这个步骤没问题（你做的没错），当找回到 UID 后，用文本编辑器打开这个配置文件，找到 UID 对应的内容，然后根据 https://github.com/Kenshin/simpread/discussions/1958 更改 UID 后会自动授权的。

**Comment by dahulun** [comment]
是用记事本打开吗？
![image](https://user-images.githubusercontent.com/100451422/168749871-8e05a6ad-ef36-4e7f-a89e-babe5d7373ab.png)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/168750667-91e2d8dd-b94f-412d-9d45-da72543810b2.png)

上面 `ellq1agp-xxx` 就是你的 UID

**Comment by dahulun** [comment]
https://github.com/Kenshin/simpread/discussions/1958按照这里介绍的方法，输进去UID还是不能激活

**Comment by Kenshin** [comment]
你随便给我个配置文件，放这上面就行了，我给你配置....

**Comment by dahulun** [comment]
{"version":"2.2.0","option":{"version":"2017-04-03","create":"2022年05月17日 10:37:47","update":"","sync":"","save_at":"jianguo","notice":true,"esc":true,"br_exit":false,"secret":false,"preload":true,"shortcuts":"enable","darkmode":"auto","auto_mode":"read","lazyload":["baidu.com","weibo.com","youtube.com"],"uninstall":true,"menu":{"focus":true,"read":true,"manual":true,"option":true,"link":false,"list":true,"whitelist":false,"exclusion":false,"blacklist":false,"lazyload":false,"unrdist":true},"origins":[],"blacklist":["google.com","youtube.com","simp.red","simpread.herokuapp.com","simpread-test.herokuapp.com","simpread.ksria.cn","https://www.oschina.net/"],"plugins":[],"annote":{"shortcuts":"M M","trigger":true,"off":true,"autosave":false,"export":false,"exp_mode":"","exp_name":"html","color":1,"style":0,"keyboard":"Q Q","event":"click","effect":"normal","order":"manual","savelocal":false,"hypothes":false,"link":"[{{an_text}}]({{an_int_uri}})"},"unreader":{"shortcuts":"D D","show":"senior","sidebar":true,"theme":"default","mode":"annote","autoiframe":false,"sametheme":false,"bottom":true,"exports":{},"offline":false,"openmode":"evergreen","search":true,"savelocal":false,"savetype":"ofhtml"},"manual":{"shortcuts":"S S","site":"confirm","mode":"read","select":true},"urlscheme":true,"remote":{"port":7026,"sync":false,"parse":false,"export":{"plain":false,"epub":false,"pdf":false,"mail":false,"kindle":false,"attach":"none"},"rss":false},"export":{"title":{"custom":false,"template":""},"html":{"layout":"normal","toc":false,"proxy":false},"markdown":{"custom":false,"template":"","tag":"","tag_sep":"","int_uri":"","ext_uri":"","single":false,"single_tmp":"","format":"","backlink":""},"markdeep":{"custom":false,"template":""},"custom":[],"webhooks":[]},"automated":[]},"focus":{"version":"2016-12-29","bgcolor":"rgba( 235, 235, 235, 0.9 )","controlbar":true,"mask":true,"highlight":true,"opacity":90,"shortcuts":"A S","auto":false},"read":{"version":"2017-03-16","progress":false,"auto":false,"controlbar":true,"fap":true,"fap_layout":"list","highlight":true,"shortcuts":"A A","toc":true,"toc_hide":true,"theme":"github","fontfamily":"default","cleanup":true,"pure":true,"lazyimg":true,"whitelist":[],"exclusion":["v2ex.com","issue.github.com","readme.github.com","question.zhihu.com","douban.com","nationalgeographic.com.cn","tech.163.com","docs.microsoft.com","msdn.microsoft.com","baijia.baidu.com","code.oschina.net","http://www.ifanr.com","http://www.ifanr.com/news","http://www.ifanr.com/app","http://www.ifanr.com/minapp","http://www.ifanr.com/dasheng","http://www.ifanr.com/data","https://www.ifanr.com/app","http://www.ifanr.com/weizhizao","http://www.thepaper.cn","http://www.pingwest.com","http://tech2ipo.com","https://www.waerfa.com/social"],"fontsize":"","layout":"","actionbar":{},"custom":{"title":{"fontFamily":"","fontSize":"","color":""},"desc":{"fontFamily":"","fontSize":"","color":""},"art":{"fontFamily":"","fontSize":"","color":"","fontWeight":"","wordSpacing":"","letterSpacing":"","lineHeight":"","textIndent":""},"pre":{"textShadow":""},"code":{"fontFamily":"","fontSize":""},"css":""}},"websites":{"person":[],"custom":[],"local":[]},"statistics":{},"user":{"uid":"ellq1agp-pq2l-vqd4-jbjg-ytfuur27w607","name":"","contact":"","email":"","avatar":"","rule":1},"notice":{"latest":0,"unsee":0,"read":[]},"unrdist":[],"collections":[],"plugstorge":{}}

**Comment by Kenshin** [comment]
删除简悦，重启浏览器

下载 [simpread-config-2022年05月17日 15_58_41.json.zip](https://github.com/Kenshin/simpread/files/8706335/simpread-config-2022.05.17.15_58_41.json.zip)

解压缩后，安装简悦，通过下图导入

![image](https://user-images.githubusercontent.com/81074/168760790-f8e371e6-afc5-4c9a-8d61-2021257145af.png)

提示成为高级账户后，重启浏览器

**Comment by dahulun** [comment]
谢谢啊！可以了，我以后遇到这种情况把你发的文件导入就可以了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 我的高级账户不能找回 (Issue #3930)





 
删除简悦，重启浏览器
 
下载 simpread-config-2022年05月17日 15_58_41.json.zip
 
解压缩后，安装简悦，通过下图导入
 

 
提示成为高级账户后，重启浏览器

**Comment by Kenshin** [comment]
> 谢谢啊！可以了，

小事情。

> 我以后遇到这种情况把你发的文件导入就可以了吧

不可以，我给你的配置文件是初始的，你导入后数据都没了，注意（经常）留存（导出）你自己的配置文件就好。

**Comment by dahulun** [comment]
是在箭头那里导出激活高级用户的文件吧
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 我的高级账户不能找回 (Issue #3930)





  
谢谢啊！可以了，
  
小事情。
  
我以后遇到这种情况把你发的文件导入就可以了吧
  
不可以，我给你的配置文件是初始的，你导入后数据都没了，注意（经常）留存（导出）你自己的配置文件就好。

**Comment by Kenshin** [comment]
这里

![image](https://user-images.githubusercontent.com/81074/168768522-7aff4d2d-a814-4576-ab57-42e06620d167.png)

**Comment by Kenshin** [comment]
我把敏感信息（ UID 和 License）删除了，以防外泄。

**Comment by dahulun** [comment]
你好，我现在导出PDF，需要同步助手，目前不能同步




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 我的高级账户不能找回 (Issue #3930)





 
我把敏感信息（ UID 和 License）删除了，以防外泄。

**Comment by Kenshin** [comment]
> 我现在导出PDF，需要同步助手，目前不能同步

请详细描述你的问题（截图），另外同步助手的 [教程](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)

**Comment by dahulun** [comment]
如需同步，必须安装坚果云吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 我的高级账户不能找回 (Issue #3930)





  
我现在导出PDF，需要同步助手，目前不能同步
  
请详细描述你的问题（截图），另外同步助手的 教程

**Comment by Kenshin** [comment]
是的
