### ISSUE TITLE
导入到 Obsidian 支持本地图片方案

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3935]
请问 Local REST API 方案 是不是也不支持导入 图片，只能选择 同步客户端的方案

_Originally posted by @jianmj in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2765343_

**Comment by Kenshin** [comment]
@jianmj 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

此方式 Local REST API 当然可以导入图片了，如果出现了导出问题，请提供 URL

**Comment by jianmj** [comment]
抱歉，我描述不清楚，我的意思是想将网页图片同步到本地存储，拿 [oschina 地址](https://www.oschina.net/news/196126/chrome-cannot-be-updated-in-russia-andriod)测试了下，发现 图片是引用外部地址

**Comment by Kenshin** [comment]
> 抱歉，我描述不清楚，我的意思是想将网页图片同步到本地存储

哈哈，小事情，目前不支持。

但也会有方案的，我重开这个 issues，支持的时候我会在这里通知。

***

建议订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我也会在这些渠道通知~

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了，简悦 1.0.2 版来了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 以 md + assets 方式导出

1.0.2 版内置了 以 md + assets 方式导出方案，详细说明 👉 https://github.com/Kenshin/simpread/discussions/4047

# 同步助手 1.0.2 版

https://github.com/Kenshin/simpread/discussions/4049

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 注意

Linux 版用户有些小瑕疵

1. 只能通过 Menubar 隐藏窗体。
    
    ![image](https://user-images.githubusercontent.com/81074/172758244-a0e613e1-7ef9-4b7d-99b8-9cb6c6109ae2.png)
    
2. 在切换 Tab 时窗体会有闪动

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
