### ISSUE TITLE
Markdonw 模板辅助增强的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#3936]
## 问题描述
插件 *自动化辅助增强* 在标注内容变化时似乎是将当前网页内的所有标注信息都覆盖到文件中，导致我在文件中添加的一些文本丢失

### 详细描述
我在 *Markdwon 模板辅助增强 选项* 处添加了元数据格式（如下图），
![image](https://user-images.githubusercontent.com/45873697/168790464-a6a874b3-9818-4e6b-8f56-aca1ed5e55f4.png)

在 *导入标注到 Obsidian* 后在生成的文件处填写了 aliases 的元数据：
![image](https://user-images.githubusercontent.com/45873697/168792298-b2dd6e87-4799-4dfa-a44e-291fa743b0ba.png)

接着往网页再添加标注，
![image](https://user-images.githubusercontent.com/45873697/168792640-580c011d-6b98-43d9-b4f0-6df19f616970.png)
与此同时，别名处变回空了
![image](https://user-images.githubusercontent.com/45873697/168792718-5d747e92-4940-4815-a2de-3d03e82947d7.png)

### 建议
希望修改网页标注时不要把元数据也覆盖掉

_Originally posted by @HardwayLinka in https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2766664_

**Comment by Kenshin** [comment]
@HardwayLinka

嗨，我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 在标注内容变化时似乎是将当前网页内的所有标注信息都覆盖到文件中，导致我在文件中添加的一些文本丢失

当然，目前的方案当然是单向更新。从技术角度考虑，根本不太能做到差值更新，原因很简单：

每个模板都不一样，所以很难通过对比新旧内容实现差值更新。（我测试过这种方案，完全行不通。

目前市面上全部的导入服务，比如从 **服务 A → 服务 B** 这样的，都是单向更新的。

***

其实是要上一个差值更新的功能，但优先级很低，因为并不太方便。

**Comment by HardwayLinka** [comment]
> @HardwayLinka
> 
> 嗨，我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> > 在标注内容变化时似乎是将当前网页内的所有标注信息都覆盖到文件中，导致我在文件中添加的一些文本丢失
> 
> 当然，目前的方案当然是单向更新。从技术角度考虑，根本不太能做到差值更新，原因很简单：
> 
> 每个模板都不一样，所以很难通过对比新旧内容实现差值更新。（我测试过这种方案，完全行不通。
> 
> 目前市面上全部的导入服务，比如从 **服务 A → 服务 B** 这样的，都是单向更新的。
> 
> 其实是要上一个差值更新的功能，但优先级很低，因为并不太方便。

如果给每篇导入的 markdown 设置别名会不会简单一点呢？
因为像每篇导入的 markdown 的名字都很长，而且文件名没有代表性，不能很准确、精炼地描述：
![image](https://user-images.githubusercontent.com/45873697/168831062-d0759f9a-3c31-4a21-aea3-b54a3d0316d5.png)

如果要设置链接，那么就得从头开始输入 markdown 名，然而笔记多的时候不可能输入 markdown 名：
![image](https://user-images.githubusercontent.com/45873697/168830222-226811d8-3fe9-429a-843b-e38a55474912.png)

**Comment by Kenshin** [comment]
可以设置别名，占位符 `{{note}}` 细节看 https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2577616

官方首发的模板库里面也有描述 https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311

**Comment by Kenshin** [comment]
备注是需要自己填的

![image](https://user-images.githubusercontent.com/81074/168944582-fcdd437d-ee59-4ee1-ae7d-b1b33bdc79a1.png)

**Comment by HardwayLinka** [comment]
> > 
> 
> 这样设置吗？那要在哪里输入别名呢？ ![image](https://user-images.githubusercontent.com/45873697/168846095-ed2708c7-7621-471b-bc1f-24fc0c93bc06.png)
> 
> 输出的 markdown 里 {{note}} 处是空的，我需要从哪里输入别名？ ![image](https://user-images.githubusercontent.com/45873697/168848650-7f7ba4a1-94bb-4f2a-b073-3e04fb1adb09.png)
> 
> 在输出的 markdown 里吗 ![image](https://user-images.githubusercontent.com/45873697/168846529-3ee53c05-89cc-4079-95c9-2caf1242dddb.png)
> 
> 这样不就还是会被覆盖 /(ㄒoㄒ)/~~

想给网页添加别名的朋友可以按以下方法来操作：
![image](https://user-images.githubusercontent.com/45873697/168942157-168d3785-5b34-4717-b11a-d8d69ba6f3b7.png)

图2 👇
![image](https://user-images.githubusercontent.com/45873697/168943283-3342594c-0d41-4b4e-a4d0-975b4662342f.png)

根据 *图2*，把文章信息对应的占位符写进
![image](https://user-images.githubusercontent.com/45873697/168944495-50c02e81-c522-49cf-849f-cca241d5de77.png)

然后回到 *图2* 填写信息
![image](https://user-images.githubusercontent.com/45873697/168944465-e5b6f83c-df63-4c0a-b4f5-cc257d4314cc.png)

连按 3 下 b 就刷新了当前网页对应的 markdown 了，可以看到生效了：
![image](https://user-images.githubusercontent.com/45873697/168944752-2aee2f17-2b6b-44ff-a6fd-147926ce62a7.png)

**Comment by Kenshin** [comment]
哈哈，不错的指导，我已经放到了文档中 https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2772096

有任何问题随时在这个 Isues 里面提，我先关闭这个 Issues 了
