### ISSUE TITLE
PDF 导出支持暗色主题

### ISSUE THREAD

**Issue by WZR031** [Kenshin/simpread#3945]
操作系统win64 edge浏览器 支持的markdown中图片似乎是以base64存储的，会造成文本的冗余，可否设置图片导出为连接形式？如edge插件markdownloadload

**Comment by Kenshin** [comment]
嗨，我没理解你的问题…

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

首先，在 Email 中发截图的形式回复，我看不到你发的截图。😂 
所以，请进入此 [Issues](https://github.com/Kenshin/simpread/issues/3945) 来讨论和截图。

不过，我「脑补」了下缺失的图片，大概知道你的诉求了。

1. 你用的这个插件转换后的图片只是在线图片而已。

2. 简悦当然有相似的功能，叫做**导出 Markdown**。

3. 你用的是叫做**导出 离线 Markdown** 的功能，这种功能可以将在线的图片转换为 base64（字符串）防止图片 404，但缺陷是在 Obsidian 预览效果不太好。

解决方案：

1. 你可以导出 .textbundle 结构的文件到 Obsidain，然后通过某些方式修改为 Obsidian 可以预览的图片，[教程1](https://github.com/Kenshin/simpread/discussions/3241) 和 [教程2](https://github.com/Kenshin/simpread/discussions/2360)

2. 如果你使用同步助手的话，下周（最迟再下周）会发一个更方便的功能，类似下图

    ![image](https://user-images.githubusercontent.com/81074/169189829-bbb79a6d-f8c4-495f-b5e4-805de49a6daf.png)

关于与 Obsidian 各种使用技巧，可以 [看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=textbundle+label%3Aobsidian)。

**Comment by WZR031** [comment]
好的那我已经完美解决了自己的诉求，就不issue给您增加工作量了哈哈
感谢你的及时回复！
还有个小问题，个人比较喜欢用暗色主题，但是这样导出pdf和白底割裂感就过强，所以我导出时都需要换到亮色主题
这样会导致我频繁切换颜色，而最右下角悬浮标没有那么便捷
个人目前使用assistive touch，但似乎没有快速更改主题颜色选项
请问有什么方法可以便捷调整主题吗，或者设置为每次导出自动切换成某亮色主题
辛苦幸苦！昨天一遇到简悦就立刻购买支持了hhh




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 关于离线 Markdown 的一些疑问 (Issue #3945)





 
嗨，谢谢喜欢简悦。
 
首先，在 Email 中发截图的形式回复，我看不到你发的截图。😂
 所以，请进入此 Issues 来讨论和截图。
 
不过，我「脑补」了下缺失的图片，大概知道你的诉求了。
  
 
你用的这个插件转换后的图片只是在线图片而已。
 
 
 
简悦当然有相似的功能，叫做导出 Markdown。
 
 
 
你用的是叫做导出 离线 Markdown 的功能，这种功能可以将在线的图片转换为 base64（字符串）防止图片 404，但缺陷是在 Obsidian 预览效果不太好。
 
  
解决方案：
  
 
你可以导出 .textbundle 结构的文件到 Obsidain，然后通过某些方式修改为 Obsidian 可以预览的图片，教程1 和 教程2
 
 
 
如果你使用同步助手的话，下周（最迟再下周）会发一个更方便的功能，类似下图
 

 
  
关于与 Obsidian 各种使用技巧，可以 看这里。

**Comment by Kenshin** [comment]
> 我已经完美解决了自己的诉求，就不issue给您增加工作量了哈哈

使用了什么方式？（好奇问问

> 个人比较喜欢用暗色主题，但是这样导出pdf和白底割裂感就过强

同步助手下个版本解决，已进入 Release 阶段，就快了。所以下面的问题也已经不太重要了。

> 个人目前使用assistive touch，但似乎没有快速更改主题颜色选项

assistive touch 会升级更多快捷方案支持，「快速更改主题颜色选项」的话，可以试试快捷键，看下图

![image](https://user-images.githubusercontent.com/81074/169205324-d03dc7b7-69cf-4e65-8d31-d9d1fbb8f9d8.png)

**Comment by WZR031** [comment]
解决方式：
也不是什么方式啦，主要就是现在理解了markdown与离线markdown区别
因为我个人会把ob当成一个私人化很重的阵地，一些精品好文章我会直接存到zotero，ob里面信息都是经过我的重构转码的，所以对工作流的自动联动目前要求并不高
所以markdown对我来说够用，这样就可以删去原来那个插件


暗色主题：
好的好的，如果你指的是下版本解决暗色主题的显示问题，那确实我也不需要换底色了hhh
而且个人目前更偏向本地html形式，这样长文有目录，非常方便，而且zotero虽然无法识别但是也可很好保存


最近我会尝试快捷键，再次感谢开发者！！！😋


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 关于离线 Markdown 的一些疑问 (Issue #3945)





  
我已经完美解决了自己的诉求，就不issue给您增加工作量了哈哈
  
使用了什么方式？（好奇问问
  
个人比较喜欢用暗色主题，但是这样导出pdf和白底割裂感就过强
  
同步助手下个版本解决，已进入 Release 阶段，就快了。所以下面的问题也已经不太重要了。
  
个人目前使用assistive touch，但似乎没有快速更改主题颜色选项
  
assistive touch 会升级更多快捷方案支持，「快速更改主题颜色选项」的话，可以试试快捷键，看下图

**Comment by Kenshin** [comment]
哈哈，小事情。

***

要是喜欢简悦的，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图，请帮忙五星 + 好评

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

或在 Edge 帮忙五星好评  😏

**Comment by WZR031** [comment]
edge chrome都在用，已经两个都五星好评了😉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] PDF 导出支持暗色主题 (Issue #3945)





 
哈哈，小事情。
 
 
要是喜欢简悦的，进入 chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll 通过下图，请帮忙五星 + 好评
 

 
或在 Edge 帮忙五星好评  😏

**Comment by Kenshin** [comment]
太感谢了。 🎉  💪

**Comment by WZR031** [comment]
HHH还想问一个小问题，目前想要导出本地然后保留目录的话，个人目前是用离线html，效果完美
想问下导出的pdf支持目录跳转吗，目前好像还没有该功能
日后会开发吗（不开发也无所谓的hhh，html效果真的很好）






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] PDF 导出支持暗色主题 (Issue #3945)





 
太感谢了。 🎉  💪

**Comment by Kenshin** [comment]
> 想问下导出的pdf支持目录跳转吗，目前好像还没有该功能

新版 PDF 会有目录跳转以及... 定制化以及主题。😄

**Comment by WZR031** [comment]
新版是啥时候😍
是之前说的和暗色修复一起推新吗，那个不是已经测试阶段了嘛，那岂不是一两周就可以体验到了😜




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] PDF 导出支持暗色主题 (Issue #3945)





  
想问下导出的pdf支持目录跳转吗，目前好像还没有该功能
  
新版 PDF 会有目录跳转以及... 定制化以及主题。😄

**Comment by Kenshin** [comment]
> 是之前说的和暗色修复一起推新吗，那个不是已经测试阶段了嘛，那岂不是一两周就可以体验到

是的~

**Comment by Kenshin** [comment]
> 嗨，各位，更强大的 PDF 导出方案来了，此 Issues 的问题都可以使用此方式解决。

![pdf](https://user-images.githubusercontent.com/81074/172984438-e3c2d4a4-c870-4691-8b3d-d064d4d7e6e1.png)

## 下载地址

https://simpread.ksria.cn/plugins/details/Lly3mkuSPz

## 演示

[百度网盘](https://pan.baidu.com/s/1a2ONidboUASR92N-Xkllmg?pwd=f3y5#list/path=/SimpRead/pdf)

## 使用前提

1.  这是同步助手 1.0.2 版对应的功能，如果想要使用它，需要安装 1.0.2 版的同步助手，详细说明可以 [看这里](https://zhuanlan.zhihu.com/p/525999909)。
    
2.  使用 `wkhtmltopdf` 来增强导出 PDF 的定制化功能，因此也需要安装 `wkhtmltopdf`，安装很简单但需要留意 [注意事项](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。

## 名词解释

*   1.0.1 版 PDF 方案称为：同步助手基础打印方案
    
*   1.0.2 版 PDF 方案称为：同步助手高级打印方案
    
## 优势

1. 可根据当前阅读模式的 [主题、字体样式、字体大小](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735661) 生成 PDF

2. 支持 [自定义字体](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735667) · [自定义样式](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2735664)

3. 支持 [更细致的打印，如页边距、打印尺寸](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058)

4. 自带目录

5. 完美解决因图片防盗链无法成功打印的问题

## 劣势

1. 无法在稍后读使用
2. 需要安装 wkhtmltopdf
3. 标注支持度有限，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2749985)

## 注意

1.  Windows 11 用户不要将 wkhtmltopdf 安装在默认盘和默认目录，这会出现权限问题导致无法使用。
    
2.  如果将 wkhtmltopdf 安装在非默认目录，需要手动设置它的 [运行目录](https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490)。
    
## 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
