### ISSUE TITLE
#bug#设置界面偶尔抽风乱码

### ISSUE THREAD

**Issue by Flora-air** [Kenshin/simpread#3947]
Chrome版本 Version 101.0.4951.64 (Official Build) (x86_64)
macOS 12.3.1
简悦版本2.2.0.520从谷歌商店下载的 
会偶尔遇到一些设置界面乱码

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/62434508/169201243-40ded56f-9337-4247-a636-fd3742c1e120.png">

但是刷新一下 过一会儿就又好了 很奇怪
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/62434508/169201995-3949d2fe-8934-4f97-9794-8a71cd40b151.png">

**Comment by Kenshin** [comment]
嗨，确实如此，遇到此问题时，重启浏览器就行了。

PS：我也不确定是什么问题，大概率是 Chrome 的 Bug 造成的，因为 Chrome 某个版本是好用的，但它更新的太频繁了... 😂
