### ISSUE TITLE
如何使该插件对某个网站关闭

### ISSUE THREAD

**Issue by tianhuahao** [Kenshin/simpread#3948]
不需要使用简悦的网站怎么关闭插件功能，防止干扰‘

**Comment by Kenshin** [comment]
1. 简悦不会主动运行。（也就是不会主动进入阅读模式）
2. 除非你加入了白名单，也只有在进入正文时才会自动进入阅读模式。

你可以使用：

1. 黑名单，在不需要的页面加入黑名单

2. 不启用自动进入阅读模式的功能，然后使用白名单机制，让需要的页面自动进入。
