### ISSUE TITLE
是否有可能加入批量导出的插件呢？

### ISSUE THREAD

**Issue by Marzlik** [Kenshin/simpread#395]
您好，一直在找可以把网页，尤其是知乎上的的一些回答或者专栏可以转为markdown之类离线保存的，发现简悦导出的md格式最舒服，不过因为之前已经收藏了很多回答了，所以想请教下是否有可能实现知乎收藏批量转为md的插件呢，或者是自己爬取好这些回答的地址，然后用简悦进行排版导出也行。谢谢。

**Comment by Marzlik** [comment]
另外刚才看到官网有个小疏漏，在更多功能等你发现那里的图标中，上传和下载的两个图标反了。
![snipaste_2018-09-20_10-33-05](https://user-images.githubusercontent.com/26034645/45790552-46a8a400-bcc0-11e8-9296-895511bfa04e.png)。

**Comment by Kenshin** [comment]
有可能实现知乎收藏批量转为md的插件
> 如果是你说的「插件」指的是简悦的话？暂时并不能提供这样的功能，简悦的插件系统主要针对于进入 `阅读模式` 后的一些操作。

自己爬取好这些回答的地址，然后用简悦进行排版导出
> 简悦暂时并不支持批量导出 MD 的功能。 😂 

上传和下载的两个图标反了
> 其实它们并没有反，只是上传的 icon 的箭头应该向下，才更加直观... 其实这两个 icon 确实有误导人的问题，等有时间改下，3ks！

**Comment by Marzlik** [comment]
感谢及时回复，那么想请教下聚焦模式下导出为MD格式是如何实现的呢？（其他导出为md格式的插件或者软件的排版很丑，几乎没法看）    
自己在编程上几乎没什么基础，还麻烦您说下大致思路，剩下的自己慢慢摸索，谢谢。

**Comment by Kenshin** [comment]
一两句话没办法解释清除，相关的代码在 https://github.com/Kenshin/simpread/blob/master/src/focus/focus.js

相关代码 
- L108 `Focus.prototype.GetFocus()` 
- L33 `Focus.prototype.Render()`

估计对你的需求帮助不大~

**Comment by Kenshin** [comment]
增加了 【离线下载】 插件 👉https://github.com/Kenshin/simpread/issues/508

不知道是否可以解决你的疑问，如可以解决，请关闭此 issues ~
