### ISSUE TITLE
官网的帮助文档无法打开，谷歌插件（.crx）下载不了

### ISSUE THREAD

**Issue by ougee123** [Kenshin/simpread#3956]
![7e509a691d813295513fb12df555555](https://user-images.githubusercontent.com/105893047/169498073-4f89ba10-7396-435e-a547-d5452f0659c2.png)
页面状况如上图，官网其他网页能够正常打开。同步助手因此也无法下载。谷歌插件原来能够下载但是压缩包里没有crx文件，请问是怎么用的

**Comment by Kenshin** [comment]
1. 请使用通过 [Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 下载

2. 帮助文档可以打开。

建议，确保网络畅通，或者请使用 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 版本

**Comment by Kenshin** [comment]
嗨，我优化了文档的网络，你可以再试试，建议在隐私模式下访问（因为有可能会有缓存导致你访问的仍是旧的

- https://simpread.pro/docs

- https://simpread.pro/download
