### ISSUE TITLE
使用了同步助手的自动同步功能但并未运行

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#3958]
请问，这个是什么原因？关闭重启了同步程序和浏览器，也还是不行？

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
是不是没授权造成的…

使用同步助手的前提，需要通过扩展端先授权（激活）

**Comment by angel126** [comment]
![image](https://user-images.githubusercontent.com/8450915/169628046-0d7a5b46-0e57-435a-ab8e-3e2601bc15eb.png)

在本地的html 出现这样的错误，互联网上的没有这个问题，我看了权限也打开了

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Kenshin** [comment]
第一个截图的意思是说：你需要运行 [同步助手客户端](http://ksria.com/simpread/docs/#/Sync)，你的截图没有体现出是否运行了同步助手客户端。

**Comment by angel126** [comment]
![image](https://user-images.githubusercontent.com/8450915/169639772-31449821-5ed1-44fd-862c-f0fa0e2897ff.png)

**Comment by Kenshin** [comment]
emmm 这就奇怪了...

1. 重置同步助手。

2. 导出配置文件，然后重装简悦（重启浏览器）

3. 运行同步助手。

4. 导入配置再进行授权同步助手。

**Comment by angel126** [comment]
![image](https://user-images.githubusercontent.com/8450915/169700190-0b830206-4fce-48d0-b014-83f6253e160a.png)
导入以后，卡在这个见面，无法进入配置页面？？是哪里出问题了？

**Comment by Kenshin** [comment]
重启同步助手，如果重启无效还是这个的话，应该有你的配置文件有问题…

既然给我发了邮件，就不要改动配置文件了，否则我给你的也是旧的。

另外，根据你这两个 Issues 反馈，建议如果稍后读不太重要的话，最好重置你的配置文件。

**Comment by angel126** [comment]
这个故障以后，就重置了配置文件，然后出现后面本地文件无法标注的问题，早上我又重新重置配置文件，设置自动化的时候出现这个调用失败，这个是什么原因，不用理会还是那里又出现问题？
![image](https://user-images.githubusercontent.com/8450915/169730232-42bf8be6-87fa-4556-a61a-088069c57806.png)

**Comment by Kenshin** [comment]
1. 确保你重置后的配置 UID 是之前注册高级账户时的 UID

2. 看看同步助手下图是不是没有绑定？

   ![image](https://user-images.githubusercontent.com/81074/169739043-b6c636e8-85d6-4353-8b72-b28c6bd64f3d.png)

3. 请详细说明你的自动化设置。

***

根据你的之前的种种描述，你的配置文件基本是乱的...（因为出现了这种奇怪的问题

1. 确定你的配置文件中的 UID（选项页 → 高级账户 → UID ） 是否是正确的。

2. 同步助手 → 重置

    ![image](https://user-images.githubusercontent.com/81074/169739239-00f6dd6d-eec3-4cf0-b953-2236c3c011e2.png)

3. 按照这个 [教程](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B) 重新配置。

**Comment by angel126** [comment]
可以了，同步没有绑定，多谢。

**Comment by Kenshin** [comment]
okay 那我关闭这个 Issues 了

另外，稍后读合并的事情还需要处理吗？（我看你反复重置了 nn 次配置文件）
