### ISSUE TITLE
notion 无法导入授权。用新手教程中的方法一至三 均无用

### ISSUE THREAD

**Issue by Adam384342** [Kenshin/simpread#3963]
![image](https://user-images.githubusercontent.com/52620561/169699986-761b3836-ea35-4287-8e5a-1a805e0a0f7a.png)
一直卡在这个页面  刷新后就取消了
![image](https://user-images.githubusercontent.com/52620561/169700042-20a1e28b-ff82-4b0b-98e0-9a318e99b757.png)

**Comment by Kenshin** [comment]
是指 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358 提到的方案吗？

包括新注册 Notion 也不行？

**Comment by Adam384342** [comment]
是的

**Comment by Kenshin** [comment]
嗨，如果是新注册 Notion 也没法使用，请检查你的参与步骤，或者录屏给我。

新用户绝对不会有任何问题。

**Comment by Adam384342** [comment]
https://www.bilibili.com/video/BV1H5411X73A/   视屏

**Comment by Kenshin** [comment]
我看了视频

1.  是否 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2758232 造成？

2. 没有体现出退出 Notion 后重启浏览器。（手机看不太清楚）

3.  还是搞不定把你临时注册的 Notion 发到 如果还是搞不定的话，把新旧配置配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3963

另外，还有个事情需要你帮忙，我看到你的 Webstore 首页有简悦的推荐？能否截整个的图给我发过来？

**Comment by Kenshin** [comment]
嗨，现在还能看到吗？如果能的话，把 Webstore 的 URL 与截图发到这里。如果邮件已经包含截图的话，就给我 URL 即可。

我看视频的 URL 有点跟我的不一样…

另外，邮件是否也包含了你的配置文件？

**Comment by Adam384342** [comment]
https://chrome.google.com/webstore/category/extensions?utm_source=chrome-ntp-icon
![image](https://user-images.githubusercontent.com/52620561/169848868-e66636b1-03db-4d0f-b97c-e1dda6a43f5e.png)
就是正常的谷歌应用商店  我卸载简悦后就会出现在主页上。
邮件包含配置文件。

**Comment by Adam384342** [comment]
![image](https://user-images.githubusercontent.com/52620561/169853487-4faeda3b-0a49-4ccd-be50-9e69190267bf.png)

**Comment by Adam384342** [comment]
你可以试试卸载  应该就能在商店看到了

**Comment by Kenshin** [comment]
嗨，我把跟这个 Issues 无关的内容删除了。

邮件我收到了，但是没有看到 Notion 的账户和密码。我需要你的 Notion 账户才能判断你的问题是什么。

你可以把新注册的账户和密码（改个简单的）给我，搞定后我会把正确的配置文件给你。

**Comment by Adam384342** [comment]
已补发

**Comment by Kenshin** [comment]
好，明天给你。

**Comment by Kenshin** [comment]
配置文件给你了。

根本就没问题...为什么不按照官方给出的方案配置呢？你的 Notion 账户里面根本就不能保存成功，因为没有符合保存到 Page 😂

![image](https://user-images.githubusercontent.com/81074/170175512-ad8b3f0b-b8ff-4fd1-865a-448d5cb46885.png)

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
