### ISSUE TITLE
mac m1 chrome快捷键失效问题

### ISSUE THREAD

**Issue by KK-3458** [Kenshin/simpread#3968]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本  101.0.4951.64（正式版本） (arm64)

- 简悦版本 2.2.0.520

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

之前设置了快捷键，点了就可以进入阅读模式或者加入稍后读，现在按了都没反应是怎么回事啊？？是不是因为我用太多次导致失效了呢==

**截图**

> 一图胜千言，所以方便的话，可以试着贴截图

<img width="704" alt="image" src="https://user-images.githubusercontent.com/66560506/169749106-4ceea277-fee1-4f80-b1ca-7af22bbb15db.png">
然后很奇怪的就是会突然跟我说pei zhi配置文件已经更新，需要刷新再打开，然后我就得刷新几次才能进入阅读模式，明明我没有去动那个选项的配置。。不过，有可能是之前配置文件时候不懂，文件位置以为在坚果云根目录的不行（就是打开坚果云直接就能看到的文件夹），然后就把这个配置文件复制到其中一个文件夹里面了，改来改去的，可能系统产生了冲突吧【后来这个放到坚果云根目录文件夹里面的坚果云配置文件夹也被神奇的自动出现在打开坚果云就能看到的文件夹了。。。】
help！please help！！～～
thanks a lotttt～～～

**Comment by Kenshin** [comment]
> 之前设置了快捷键，点了就可以进入阅读模式或者加入稍后读

试试快捷键 `d d` ，另外截图中全局快捷键，有个 Bug（可能是 Chrome 的锅），在使用时需要将当前窗口激活状态。所以，不建议使用全局快捷键，简悦内置的快捷键就可以替代。

> 配置文件已经更新，需要刷新再打开

造成这个情况需要同时满足：改动配置项 & 同一个 URl 多开了 Tab，最简单的解决方案：重启浏览器。

***

另外，建议把配置文件放到 `<坚果云根目录>/SimpRead/` 下面。

**Comment by KK-3458** [comment]
好的，我试试看，谢谢～～～

**Comment by Fan-Xiaohua** [comment]
我有相同的问题，浏览器快捷键设置后不起作用。

**Comment by Kenshin** [comment]
@Fan-Xiaohua 

什么浏览器？

**Comment by Fan-Xiaohua** [comment]
> @Fan-Xiaohua
> 
> 什么浏览器？
使用的是支持m1pro芯片的chrome浏览器最新版本。简悦自己的快捷键是支持的。

**Comment by Kenshin** [comment]
@Fan-Xiaohua

![](https://user-images.githubusercontent.com/66560506/169749106-4ceea277-fee1-4f80-b1ca-7af22bbb15db.png)

你说的这个无效吗？如果是的话，在 Chrome 窗体处于激活状态下测试。（这可能是 Chrome 的 Bug

**Comment by Fan-Xiaohua** [comment]
> @Fan-Xiaohua
> 
> ![](https://user-images.githubusercontent.com/66560506/169749106-4ceea277-fee1-4f80-b1ca-7af22bbb15db.png)
> 
> 你说的这个无效吗？如果是的话，在 Chrome 窗体处于激活状态下测试。（这可能是 Chrome 的 Bug

请问什么是chrome窗体处于激活状态呢？我在win上在这个界面下使用快捷键是可以的。

**Comment by Fan-Xiaohua** [comment]
重新下载最新的chrome，问题解决

**Comment by Kenshin** [comment]
.... 😂

你的 Chrome 出了什么问题？
