### ISSUE TITLE
[功能请求] 对于PDF辅助增强插件, 新增两条设置

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#3969]
其一是允许用户选择是仅导出原文还是导出连原文带标注. 
![image](https://user-images.githubusercontent.com/65625632/169796177-5b501d87-8f94-4fa5-ae18-577a98954240.png)

---

其二是允许取消显示一级目录之中的导出到PDF的图标. 最好是能选择把悬浮球给固定到那个位置.
![image](https://user-images.githubusercontent.com/65625632/169796372-1a97fb79-9491-4cc3-9b72-3141e11b7ed5.png)

**Comment by Kenshin** [comment]
> 是允许用户选择是仅导出原文还是导出连原文带标注.

这个功能可以在选项页 → 高级设定 → 标注中设定

![image](https://user-images.githubusercontent.com/81074/169798411-c82e336c-14af-46ca-a9c6-19331e5d1ddc.png)

当然，此插件的新版会有类似的选项。

> 允许取消显示一级目录之中的导出到PDF的图标

你的意思是：截图红框的 icon 可以隐藏？

> 悬浮球给固定到那个位置

可以考虑，但如果同时都出现呢？所以应该有个判断（位置就那几个，哈哈）

![image](https://user-images.githubusercontent.com/81074/169798756-c62e979a-6c14-4b62-b911-815c167bf610.png)

**Comment by Kenshin** [comment]
补充下：

> 是允许用户选择是仅导出原文还是导出连原文带标注.

是希望这两个文件 `xxx.pdf` 与 `xxx@annote.pdf` 任选其一的意思？

**Comment by XMB-7** [comment]
> 这个功能可以在选项页 → 高级设定 → 标注中设定

我的意思是虽然在阅读模式下做了标注, 但导出为PDF的时候不要标注. 亦即新加一个"全文(不含标注)"的选项.

---

> 你的意思是：截图红框的 icon 可以隐藏？

是的, 我把”导出为pdf“放进悬浮球了, 所以希望此时可以取消显示悬浮球外的“导出为pdf”图标按钮. 
至于固定悬浮球位置, 可以按编号来, 一共就那些地方, 假如位置编号如图所示, 
![image](https://user-images.githubusercontent.com/65625632/169801252-8b1ec8c4-bd90-41c0-878c-fdcc9f02cb69.png)
顺次下排即可, 4号位如果被占了, 就把悬浮球放到5号位.

**Comment by Kenshin** [comment]
> 但导出为PDF的时候不要标注. 亦即新加一个"全文(不含标注)"的选项.

okay 新版会有

至于位置的话，我考虑下你的诉求。

**Comment by Kenshin** [comment]
嗨，我关闭这个 issues 了。
