### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by CaiJie0611** [Kenshin/simpread#397]
阅读模式及聚焦模式下，页面右侧显示长条形空白。
问题网址：http://www.15yan.com/topic/bian-ji-tui-jian/cGXM8gIMLVy/

![2018-09-26_042803](https://user-images.githubusercontent.com/31266850/46041265-ee9cf200-c144-11e8-8996-90e969018616.png)

![2018-09-26_043109](https://user-images.githubusercontent.com/31266850/46041771-34a68580-c146-11e8-92fe-0795d0ffa348.png)

**Comment by Kenshin** [comment]
1. 这个站没有被适配，只是通过 `智能适配` 自动实现；
2. 白色区域是一个 `<div>` 引起的；
---
解决办法：
1. 侧栏 → 动作 → 隐藏任意元素；

2. ![](https://user-images.githubusercontent.com/81074/45801615-fb55bc00-bce6-11e8-8188-f0843bb663f3.png)

3. 我适配这个站后会告诉你。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

可惜这个站已经关闭了...
