### ISSUE TITLE
文章名带有 *"\/<>:|? 会导致导入 Obsidian 失败

### ISSUE THREAD

**Issue by HardwayLinka** [Kenshin/simpread#3972]
哈喽，您的插件对我帮助很大，但是最近我在使用中遇到了一个问题，相关描述如下：

## 环境
* win11
* chrome  101.0.4951.67（正式版本） （64 位）
* 简悦版本 **2.2.0**

## 问题描述
文章名带有 *"\/<>:|? 会导致导入 Obsidian 失败

比如：
![image](https://user-images.githubusercontent.com/45873697/169934402-e19727ed-2899-42bb-99b9-57d4311529a2.png)

猜测原因应该是文章名带有 *"\/<>:|? 因为在 Obsidian 内会提示：
![image](https://user-images.githubusercontent.com/45873697/169934515-38808418-e536-45db-b4e6-5d5a9e661f19.png)

**Comment by HardwayLinka** [comment]
## 补充
虽然我改了文件名设定，但似乎没有生效
![image](https://user-images.githubusercontent.com/45873697/169936136-9b66ca47-f446-4a34-8b82-d83ec51ed2e8.png)

这是 Obsidian 端的报错：
![image](https://user-images.githubusercontent.com/45873697/169936232-3773605b-96ce-458a-bcb8-5c8572c73706.png)

**Comment by Kenshin** [comment]
谢谢喜欢使用简悦，试试安装这个插件能否解决？
 
![image](https://user-images.githubusercontent.com/81074/169937370-c4f9d97a-09bb-432d-a939-391feaa03d4c.png)

> https://github.com/Kenshin/simpread/issues/3972#issuecomment-1135330453

至于这个问题，截图的旁边就有链接会指向占位符的说明，应该没有 `{{type}}` 这个占位符吧，你在哪里看到的？

**Comment by HardwayLinka** [comment]
解决了，感谢~
{{type}} 是在这里看到的：
![image](https://user-images.githubusercontent.com/45873697/169938116-f691c1c8-838a-4a7f-8f77-0c6fbcf320f8.png)

**Comment by Kenshin** [comment]
哈哈，搞定就好。

> {{type}} 是在这里看到的：

哈哈，以链接处为主。截图里面的内容属于另外一个功能。

**Comment by Kenshin** [comment]
要是喜欢简悦的，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图，请帮忙五星 + 好评 😄

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
