### ISSUE TITLE
最新beta版本，快进快捷键按了之后无法显示快进速度

### ISSUE THREAD

**Issue by BryceMicheal** [Kenshin/simpread#398]
最新beta版本，快进快捷键按了之后无法显示快进速度

**Comment by Kenshin** [comment]
确定没发错 issues ？请告知具体细节。

**Comment by BryceMicheal** [comment]
版本：beta4
issues：在iina中使用的是Movist Default快捷键，以前按cxz（快进后退还原键）都可以正常显示在视频窗口左上方，现在不显示了快进速度了，不知为何，不是因为更新了mac系统的原因，在更新了iina后出现了此问题。

**Comment by BryceMicheal** [comment]
> 确定没发错 issues ？请告知具体细节。

版本：beta4
issues：在iina中使用的是Movist Default快捷键，以前按cxz（快进后退还原键）都可以正常显示在视频窗口左上方，现在不显示了快进速度了，不知为何，不是因为更新了mac系统的原因，在更新了iina后出现了此问题。

**Comment by Kenshin** [comment]
这里是 SimpRead · 简悦的 repo ，你发错地方了，我将关闭此 issuse~

**Comment by BryceMicheal** [comment]
sry。。。

**Comment by Kenshin** [comment]
没事~
