### ISSUE TITLE
简悦在每个页面都会生成一堆css样式能不能关闭

### ISSUE THREAD

**Issue by Yody011** [Kenshin/simpread#3981]
![简悦生成css](https://user-images.githubusercontent.com/58850167/170093134-7bc38776-6fde-459a-bd44-d54fb7df1360.jpg)
关闭预加载也没用。我能不能只在进入阅读模式时再加入样式？或者指定白名单？

**Comment by Kenshin** [comment]
嗨，这些样式不会给 `body` 下的内容产生影响，只会作用于 `sr-read` 以及简悦的专属 `Class`

加入黑名单后简悦才会自动删除这些样式。

PS：如果你使用 Chrome 开发的话，建议将开发环境与生产环境区别开。

**Comment by Yody011** [comment]
> 嗨，这些样式不会给 `body` 下的内容产生影响，只会作用于 `sr-read` 以及简悦的专属 `Class`
> 
> 加入黑名单后简悦才会自动删除这些样式。
> 
> PS：如果你使用 Chrome 开发的话，建议将开发环境与生产环境区别开。

对，我就是开发页面看到这这些预加载样式很碍事。这么区分开发生产环境呢

**Comment by Kenshin** [comment]
> 开发页面看到这这些预加载样式很碍事

很简单啊，用两个浏览器，比如：Chrome 和 Edge

因为我也是开发者，而且简悦的功能（阅读模式）很特殊，所以我会很注意不污染 `body` 这个事情。
但并不是每个扩展都能做到这点，所以在开发的时候，如果将生产环境与开发环境混用的话，将会是个噩梦...

我一般都用三个浏览器：

- Chrome 正常使用
- Edge Dev 开发环境
- Chrome Canary 测试环境

**Comment by Yody011** [comment]
> 我一般都用三个浏览器：
> 
> * Chrome 正常使用
> * Edge Dev 开发环境
> * Chrome Canary 测试环境
学到了，谢谢。

（小声）你讲话一股英文机翻味

**Comment by Kenshin** [comment]
> 你讲话一股英文机翻味

哈哈，只要不是说我客服味就好。😂
