### ISSUE TITLE
阅读模式下，添加自定义图片尺寸功能

### ISSUE THREAD

**Issue by cescbamboo** [Kenshin/simpread#3982]
当前图片显示的尺寸较大，（应该就是按照原本文章图片的默认尺寸设置的？）对于那种图片比较多的图文并茂的文章，图片画幅过大导致图片之间的文字变得不明显。比如少数派的这篇文章，https://sspai.com/post/69525 本身配图比较大因为可能想让读者在设置的时候能更清晰地参考图片中的内容，但是我用标注功能标记了一些我认为的关键的文字之后，保存下来，其实我之后如果再回顾的话，我会更关注我标记的那些文字而不是图片了，但是鼠标拖动页面滚轴的时候，图片又多又大导致文字不是很突出。如果可以自助定义图片尺寸，比如统一调整为75%，可能会有很好的效果。

**Comment by Kenshin** [comment]
okay 收到，我会在 https://simpread.ksria.cn/plugins/details/VQOZdNET2d 加入定制图片尺寸的功能。

**Comment by cescbamboo** [comment]
多谢~

**Comment by AlexanderTZPV** [comment]
这个issue有方案了吗

**Comment by Kenshin** [comment]
@AlexanderTZPV 

早就有了 https://github.com/Kenshin/simpread/discussions/1598

PS：忘记 Close Issues 了~ 😂

关联 Issues https://github.com/Kenshin/simpread/issues/3982
