### ISSUE TITLE
关于『导入到 Obsidian』失效

### ISSUE THREAD

**Issue by Noicdi** [Kenshin/simpread#3983]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows10 21H2**

- 浏览器版本 **Microsoft Edge 101.0.1210.53 (正式版本) (64 位)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 [测试网页](https://www.xqmq.icu/posts/6159a89c.html)

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

以前成功设置了『导入到 Obsidian + Local REST API 导出 + 自动化辅助增强 + markdown 辅助增强』四个插件，实现了稍后读和标注导入到 Obsidian

但是有一段时间没有使用（近半个月），再次按照以往的工作流程使用时，无法正常导出，即测试页面加入稍后读并修改标签备注等信息，没有正常导入到 Obsidian

然后手动点击触发器，导入全文和标注到 Obsidian，没有任何反应

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

![gif](https://xqmq--blog-image.oss-cn-shenzhen.aliyuncs.com/blog-image/2022-05-25-11-04-33.gif)

gif 较大，GitHub 可能无法显示，麻烦下载这个[链接](https://xqmq--blog-image.oss-cn-shenzhen.aliyuncs.com/blog-image/2022-05-25-11-04-33.gif)

**Comment by Kenshin** [comment]
1. 是否使用了同步助手？

2. 测试一些正常的页面 e.g. https://sspai.com/post/71576

2. Obsidian 插件会偶尔抽风，建议新建个库，然后只安装 Local REST API 看看能否解决？

3. 导出配置文件，然后重新安装简悦。

PS：看你的博客应该也是动手能力很强的用户，你可以逐一排错。

**Comment by xQmQ** [comment]
> 1. 是否使用了同步助手？
> 2. 测试一些正常的页面 e.g. [sspai.com/post/71576](https://sspai.com/post/71576)
> 3. Obsidian 插件会偶尔抽风，建议新建个库，然后只安装 Local REST API 看看能否解决？
> 4. 导出配置文件，然后重新安装简悦。
> 
> PS：看你的博客应该也是动手能力很强的用户，你可以逐一排错。

> 我设定的工作流程里，一篇文章加入稍后读时不会导入全文到 Obsidian，只有修改了文章标签和备注等信息，才会在 Obsidian 中生成一个@annote

导出的问题通过 4 解决了，但是 2 和 3 出现了很奇妙的现象，只是提一下

1. 未使用
2. 测试这个页面的时候，先加入稍后读，然后修改了标签和备注，Obsidian 生成了 @annote，但是进行标注时，又失效了，标注无法导出；奇妙的是，在 ob 中删除文件，然后重新加入稍后读，ob 中就没有@annote 生成了，彻底失效
3. 新建仓库，生成了 @annote，但是标注失效，重复第二步中的操作，彻底失效
4. 这里是成功的，但是出现了新的问题

新的问题是，对于 [sspai.com/post/71576](https://sspai.com/post/71576) 等少数派的文章，整体工作流程正常，但是测试自己博客、GitHub 的 md、知乎文章（暂时测试了这些），又失效了

**Comment by xQmQ** [comment]
发完上文，重新测试了一下少数派的文章，也失效了？？？

我很好奇什么情况，接下来我会重新执行 4，然后测试少数派文章，查看是否正常

**Comment by xQmQ** [comment]
重新安装插件后，执行了以下测试：

1. 选择网站打开，进入阅读模式
2. 进行标注，正常的工作流程会自动导出标注到 obsidian
3. 随机选择多个平台的文章进行测试；被测试过的、正常的文章和平台也会重新随机测试
4. 以上所有进行测试的文章都可以自动解析出阅读模式，无需用户动手选区

『工作正常』指修改标签、备注、打标注等操作自动导出到 Obsidian
『工作异常』指以上操作在 Obsidian 中不会生成 md 文件

工作正常的平台：少数派、知乎文章、阮一峰科技爱好者周刊（暂时测试这么多）
工作异常的平台：[自己的博客](https://www.xqmq.icu/posts/5942db24.html)、[GitHub md](https://github.com/zijie0/HumanSystemOptimization/blob/main/README.md)、竹白（暂时测试这么多）

现在的问题是，同样处于阅读模式下的文章，都可以标注等操作，有的可以导出，有的不可以。

**Comment by Kenshin** [comment]
okay 谢谢详细测试。

试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 插件能否你的博客问题解决？

竹白应该没问题，你可以试试简悦的竹白 https://simpread.zhubai.love/  （欢迎订阅，哈哈）

Github 可能有点问题，它会阻止一些 http 调用，我稍晚在调查下。

**Comment by xQmQ** [comment]
自己的博客还是不行，但是这个无所谓，一般也不会标注自己已发布的内容（笑

（有用 rss 订阅 telegram 的频道，做的真的很棒

主要是 GitHub，可能需要作者帮忙多看看，麻烦啦

感谢回复

**Comment by Kenshin** [comment]
okay 收到，有进一步消息我会通知你~

> 有用 rss 订阅 telegram 的频道，做的真的很棒

哈哈，有订阅就好 😄

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
