### ISSUE TITLE
Edge特定网页错误

### ISSUE THREAD

**Issue by pplps** [Kenshin/simpread#3988]
打开
https://www.notion.so/product/notion-for-education
这个网址会显示：
Application error: a client-side exception has occurred (see the browser console for more information).
关闭简阅就恢复正常

操作系统 
-  Windows 11
浏览器版本 
- Microsoft Edge
版本 101.0.1210.53 (正式版本) (64 位)
简悦版本
- 版本2.2.0.520
- 
截图
![1](https://user-images.githubusercontent.com/5857781/170241918-be52f04c-be06-46ca-8fdb-895234f94f73.png)

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题

![image](https://user-images.githubusercontent.com/81074/170244056-ead7a71f-7423-4c43-8069-7655949347df.png)

> 但你可以通过下面的方式解决

打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![image](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)
