### ISSUE TITLE
请问标注时自动保存的离线html文件是图片都无法加载的吗？

### ISSUE THREAD

**Issue by KK-3458** [Kenshin/simpread#3989]
您好，如题，想着问问看是本来设置的就是这样还是说我哪里设置错误了呢？希望能得到解答，真的很感谢！～～
ps，上次的开多个窗口导致快捷键失效问题，在你的解答之后关掉一个窗口，快捷键就能使用了，在这里也一起感谢！～～

**Comment by KK-3458** [comment]
是在这篇文章https://sspai.com/post/72022看到的，里面说简悦是可以一旦经过标注，就能保存为离线网页，但是我没有设置markdown，如果设置markdown，这样是不是离线的markdown网页就能看到图片了？

**Comment by Kenshin** [comment]
> 标注时自动保存的离线html文件是图片都无法加载

当然不是，正常情况肯定是可以加载的。

1. 需要使用自动化，并设置 导出 离线 HTML
2. 在标注过程中，不建议设置自动化导出 离线 HTML，因为会占用很大的性能。（每次标注都会转换一次）
3. 在标注完毕后，你可以使用 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 具体例子 [看这里](https://github.com/Kenshin/simpread/discussions/3596#discussioncomment-2441614)。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3989#issuecomment-1137110172

不建议使用 离线 Markdown，比如 Obsidian 不会很好的识别它。

**Comment by KK-3458** [comment]
好的，感谢～
那不选离线html是不是万一原网页没了，自动化保存下来的html文件就不能看到图片？但是文字是可以看到的吧？

**Comment by Kenshin** [comment]
> 那不选离线html是不是万一原网页没了，自动化保存下来的html文件就不能看到图片？但是文字是可以看到的吧？

是的，所以最好的方式：加入稍后读自动导出离线 HTML，标注时不用离线 HTML 标注完毕后再统一导出一次。

**Comment by Kenshin** [comment]
如果没有其它问题，我关闭此 Issues 了。

要是有可能的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by KK-3458** [comment]
暂时没有，好的，马上去🐶

**Comment by KK-3458** [comment]
emm，还有个其他的小问题，就是会出现一些网页它进入阅读模式的那个效果emm不是跟好（比如说之前遇到豆瓣评论原文是有分段的，但进入阅读模式却是很多个小段连成一大片的一大段一大段的。。）【也许跟我多开个tab有关。。】emm请问这个怎么解决呢？
ps：不知道close还能看到我的信息不？。。

**Comment by Kenshin** [comment]
> 不知道close还能看到我的信息不？。。

当然能，你可以随时在这里跟我讨论。😄

至于你说的问题，建议最好给出 URL 。

另外，看下以下几个方案：

- https://github.com/Kenshin/simpread/discussions/2561
- https://github.com/Kenshin/simpread/discussions/1554
- https://github.com/Kenshin/simpread/discussions/3340

如果偶尔遇到识别不好的，如果你不保存的话，其实没太大所谓，你可以把 URL 给我看看。否则的话，上面几个链接可以完美的解决任意问题。

**Comment by KK-3458** [comment]
emm今天刚好遇到这种豆瓣识别不好的评论文章了
在这里贴上它的URL，麻烦帮忙看一下～～
https://book.douban.com/review/5012104/

**Comment by Kenshin** [comment]
> 种豆瓣识别不好的评论文章了

解决方案 https://github.com/Kenshin/simpread/discussions/2561

**Comment by KK-3458** [comment]
hi，你好
我想问一下那个简悦的活跃列表跟存档列表是有什么区别呢？存档就是信息处理好放入这个列表存档这个意思是吗。。

**Comment by Kenshin** [comment]
> 我想问一下那个简悦的活跃列表跟存档列表是有什么区别

存档列表 → 你可以理解为：不想看也不想删的稍后读。
活跃列表 → 非存档列表的稍后读。

简悦没有归档的概念，因为基于数字花园理论来说，不需要存档。任何稍后读的内容都会被再次的重新提取（标注）。

所以当一个稍后读被存档后，其流程上并不符合数字花园概念。

**Comment by KK-3458** [comment]
哦哦好的，感谢解答～

**Comment by Kenshin** [comment]
小事情~

**Comment by KK-3458** [comment]
hi，开发大大，我又来了
我想稍微问一下，能不能增加标注的颜色呢？
比如紫色
上次在一个插件pagenote上面看到它里面的画笔颜色，感觉蛮喜欢的（它下面的是它本身搭配好的画笔颜色）
<img width="391" alt="image" src="https://user-images.githubusercontent.com/66560506/171841242-ec247efe-5898-4a91-8c65-91585af594f3.png">

**Comment by KK-3458** [comment]
嘿嘿，我又来了
想问一下为什么改了标注的样式以及排序的格式之后不久，它会自动给恢复到默认的格式呢？😂
这是什么原因呢？难道是因为浏览器打开太多标签页了？
<img width="837" alt="image" src="https://user-images.githubusercontent.com/66560506/173221929-1f12c289-e733-4fb3-bbdd-cb53ac5e4568.png">

**Comment by Kenshin** [comment]
> 想问一下为什么改了标注的样式以及排序的格式之后不久，它会自动给恢复到默认的格式呢？😂

可能是在某一次改动后配置互相覆盖了。

当更改选项页或者正常页面下标注的选项后，最稳妥的方式是重启浏览器，确保全部页面使用最新改动的数据。

这方面的细节可以看看 https://github.com/Kenshin/simpread/discussions/3768

**Comment by KK-3458** [comment]
好的，感谢～

**Comment by KK-3458** [comment]
今天下载了新版的同步助手，发现现在同步不了【坚果云里面的output文件没有写入，但是网页里面的稍后读有记录】。。emm是怎么回事呢？windows版本的同步助手更新是下载新版，然后退出旧版本，再在解压的文件里面点击同步助手这个应用程序来运行——这样操作是对的吗？还是得删除旧版本，但是我在应用程序里面想要寻找简悦助手来删除，发现找不到这个程序，那该怎么删除呢？。。

**Comment by Kenshin** [comment]
> windows版本的同步助手更新是下载新版，然后退出旧版本，再在解压的文件里面点击同步助手这个应用程序来运行——这样操作是对的吗

没问题

> 我在应用程序里面想要寻找简悦助手来删除，发现找不到这个程序，那该怎么删除呢？。。

同步助手是个绿色 exe，不需要通过此方式删除。

> 同步不了【坚果云里面的output文件没有写入，但是网页里面的稍后读有记录】

感觉应该是你的自动同步关了，看下图开启它。（注意留存你的配置文件

![image](https://user-images.githubusercontent.com/81074/173308094-a0009ac5-c894-4926-b200-1cd3b6ac88d7.png)

**Comment by Kenshin** [comment]
> 刚刚看了一下，没有哦那个自动同步一直是开的，

重启系统，然后确保运行 1.0.2 版。

> 发现现在同步不了【坚果云里面的output文件没有写入，但是网页里面的稍后读有记录】

还有，如果自动同步开着的话，这句话什么意思？

**Comment by KK-3458** [comment]
就是我到坚果云里面的output文件里发现没有生成我刚保存到稍后读的网页文件
我把1.0.1版本删掉，然后重启试试

**Comment by KK-3458** [comment]
![image](https://user-images.githubusercontent.com/66560506/173320204-8a5f0d99-d35d-43de-bad1-a34f9c740388.png)
Ps，这种算是保存到坚果云根目录下吗？

**Comment by KK-3458** [comment]
> 直接使用下面的方式生成 HTML，看看能否在 output 下面

没有耶，output里没有

**Comment by KK-3458** [comment]
emm重启还是解决不了问题，直接点击导出html output文件里面没有

**Comment by Kenshin** [comment]
> 这种算是保存到坚果云根目录下吗？

当然不算...

你之前使用过这个功能吗？建议看下这个 [教程](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93) 会告诉你如何配置 能导出到 output 的功能。

**Comment by KK-3458** [comment]
不算的话，还是能同步起来的之前😂现在就不行了。。

**Comment by KK-3458** [comment]
那现在要怎么办，重新在根目录下面建立文件，把之前的都搬过来吗？

**Comment by KK-3458** [comment]
我看到你的说明里面说只能选择坚果云的根目录而且名字不能更改，那现在去改不知道还有没有意义呢。。

**Comment by KK-3458** [comment]
> 无论你怎么修改，只要按照 <坚果云>/SimpRead 这么做就是正确的。
按照这个做了，output还是没有新文件出来😥

**Comment by KK-3458** [comment]
wuhu，现在变成这样了5
<img width="529" alt="image" src="https://user-images.githubusercontent.com/66560506/173345928-baa08476-72c4-4eaa-9a32-3b063a25f2aa.png">

**Comment by Kenshin** [comment]
看这个图 https://github.com/Kenshin/simpread/issues/3989#issuecomment-1153604131

**Comment by KK-3458** [comment]
不理解这两个按钮有什么区别又有什么作用唉。。

**Comment by Kenshin** [comment]
[看教程](https://kb.simpread.pro/#/page/%E9%85%8D%E7%BD%AE%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)

不用管为什么，跟着教程做… 就用你熟悉的 1.0.1

**Comment by KK-3458** [comment]
回不去了，现在两个电脑都只能用1.0.2的了，就差一步，windows电脑批注了能同步到mac电脑，但是mac的批注了同步不了到windows电脑😥

**Comment by Kenshin** [comment]
哈哈，太不容易了… 😂 显然这个问题跟同步助手没关系…

再用回 1.0.2 版同步助手。

**Comment by KK-3458** [comment]
emm用着用着突然之间又出现这个
<img width="516" alt="image" src="https://user-images.githubusercontent.com/66560506/174935121-9b36d2a1-a5de-4279-b3e1-a073c7236183.png">
为什么会这样呢？🥲把浏览器重启也没用🥲
但是我用了浏览器一个插件one tab收集之前没看完的网址，这个one tab页面会让它一直开启，还有trello。。
<img width="185" alt="image" src="https://user-images.githubusercontent.com/66560506/174935603-b425f52b-39c3-4262-a332-2055923516a6.png">
help！～～

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/3989#issuecomment-1162587837

你使用什么功能的时候出现了这个情况？最好详细描述产生问题时的操作以及提示出现的地方（阅读模式、还是稍后读）

**Comment by KK-3458** [comment]
https://scientist-with-logic.github.io/
点进去这个github生成的博客网址会出现这种错误，但是刚刚试了一下微信公众号的就还可以
是在阅读模式下标注
如果是进入阅读模式，然后加入稍后读，在稍后读里面标注，也会出现这种错误，这种情况下好像只能导出为pdf，用别的软件标注了吧

**Comment by KK-3458** [comment]
用简悦的导出pdf也失败了。。🥲

**Comment by Kenshin** [comment]
你还没有告诉我导出什么时出现的错误提示？

**Comment by KK-3458** [comment]
我不是配置了标然后注自动导出功能吗，一般的在进入阅读模式阅读时候标注，就有保存成功的框框提示，生成对应的html文档，一个原文一个标注的，但是这个网址里面内容一标注就会出现失败这样的提示，也没有生成对应的html

> <img alt="image" width="516" src="https://user-images.githubusercontent.com/66560506/174935121-9b36d2a1-a5de-4279-b3e1-a073c7236183.png">

**Comment by Kenshin** [comment]
把出现 URL 告诉我，具体的。

另外，是否安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U ？没有的话，需要安装它。

**Comment by KK-3458** [comment]
https://scientist-with-logic.github.io/%E4%BD%A0%E8%BF%99%E4%B9%88%E5%A4%9A%E5%B9%B4%E5%81%9A%E4%B8%8D%E5%A5%BD%E7%A7%91%E7%A0%94-%E5%8F%AF%E8%83%BD%E6%98%AF%E5%9B%A0%E4%B8%BA%E4%BD%A0%E5%AF%B9%E7%A7%91%E7%A0%94%E6%9C%89%E7%9D%80%E5%BE%88%E5%A4%A7%E7%9A%84%E8%AF%AF%E8%A7%A3/
这个
emm安装了你说的这个插件好像还是一样🥲

**Comment by Kenshin** [comment]
我大概知道了，这个 URL 的标题有问题，你可以在加入稍后读后，通过侧栏修改标题，让它更短点，就应该没事了。

**Comment by KK-3458** [comment]
对的，谢谢！～～

**Comment by KK-3458** [comment]
大大，怎么好像突然有bug还是哪里出错了？
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/66560506/175772603-f13dabbf-4d8c-4236-9875-9a3fa25dbf9d.png">
怎么图标都变成空白了？

**Comment by Kenshin** [comment]
刷新下，或者保障你的网络畅通。
