### ISSUE TITLE
使用简悦配置文件登录后，登录页面弹窗一直保持静止，且没有任何提示

### ISSUE THREAD

**Issue by wqnjmu** [Kenshin/simpread#3994]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/7597862/170649104-ec7d342b-4c76-43ec-8bd0-fdcc83dce47b.png">

**Comment by wqnjmu** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/7597862/170649576-696913ff-754d-4fe1-aee1-5a6859cb0d63.png">
看了下浏览器报错，不知道和截图的内容有没有关系，如果有关系，能否帮忙处理，谢谢

**Comment by Kenshin** [comment]
嗨

浏览器报错跟这个无关，你使用的是什么版本的浏览器？

另外，试试通过下图的方式导入

![image](https://user-images.githubusercontent.com/81074/170663380-4a16a7f0-23df-402f-a051-e93e54ec71d2.png)

**Comment by wqnjmu** [comment]
![Uploading image.png…]()
试了您提供的导入方式，导入后刷新页面，到账号中查看还是普通用户

**Comment by Kenshin** [comment]
okay 首先确保能导入，然后使用 https://github.com/Kenshin/simpread/discussions/1576 恢复对当前设备的高级账户授权。

**Comment by wqnjmu** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/7597862/170806301-055adbad-e56b-41f5-accc-7b2928befc20.png">
导入后，按您提供的页面提示恢复，点击后就出现以上弹窗

**Comment by Kenshin** [comment]
截图说明你导入的配置文件包含的 UID（用户信息）不是高级账户。

首先，你需要找回 License https://github.com/Kenshin/simpread/discussions/2756
其次，找回 License 后使用 https://github.com/Kenshin/simpread/discussions/1571 恢复购买时的 UID

**Comment by wqnjmu** [comment]
在咨询问题之前，我已经找回了账号信息，导出为json文件，然后按文件登录和您这边的指示，都不行。账号是去年在少数派上面买的，很久没用，但现在想好好用起来。非常感谢
<img width="253" alt="image" src="https://user-images.githubusercontent.com/7597862/170807500-34930a9d-15f7-41b6-9c43-f79324095d68.png">

**Comment by Kenshin** [comment]
有这个文件后，用任意文本编辑打开它，然后找到 UID，使用 https://github.com/Kenshin/simpread/discussions/1958 提到的方式恢复即可。

**Comment by wqnjmu** [comment]
已经按uid绑定刷新网页，页面显示我还是基础权限
<img width="868" alt="image" src="https://user-images.githubusercontent.com/7597862/170809593-32638cb0-70b0-4f1d-a434-8441baf355c2.png">

而实际看已经解锁了，我的账号没有换过设备，不知道为什么一直无法成功使用
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7597862/170809583-83a4f55a-13b2-43d2-8633-43ad391365b4.png">

**Comment by Kenshin** [comment]
把你的配置文件和正确的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：3994

我帮你设置。
