### ISSUE TITLE
代码高亮出错

### ISSUE THREAD

**Issue by Ttdjs** [Kenshin/simpread#3997]
CSDN阅读模式代码高亮插件会导致页面内容顺序和原页面出现颠倒
例子：
url:https://itsoku.blog.csdn.net/article/details/113977261#comments_20961987
原网页：
![image](https://user-images.githubusercontent.com/44637000/170743621-7a2c1b77-f18e-4ab7-bd0d-7f88381894dd.png)
阅读模式排版后：
![image](https://user-images.githubusercontent.com/44637000/170743832-a334a4ec-3dd2-41c1-bc70-31fec6b5fc8f.png)
其中doCreateBean函数代码块位置上移了

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
