### ISSUE TITLE
保存到Notion失败，显示请稍后再试，这种情况一周多了，保存到Evernote有时成功有时失败

### ISSUE THREAD

**Issue by YIQIFENGFAA** [Kenshin/simpread#3998]
**请说明发生问题的环境**

- 操作系统 **Windows10 **

- 浏览器版本 **Edge版本 99.0.1150.30 (官方内部版本) (64 位)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <保存到Notion>

**保存到Notion失败，显示请稍后再试，这种情况一周多了，保存到Evernote有时成功有时失败**

**![image](https://user-images.githubusercontent.com/79069626/170802988-8e88189e-aa6d-4f3e-a06f-5368707b09f7.png)**

**Comment by Kenshin** [comment]
嗨，Notion 无法保存的问题，建议重新授权，如果无法授权的话，试试 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2345217

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
