### ISSUE TITLE
https://www.oschina.net/code/snippet_262246_9601

### ISSUE THREAD

**Issue by TonyAble** [Kenshin/simpread#4]
不能正常显示。

**Comment by Kenshin** [comment]
![Imgur](http://i.imgur.com/I2GzPaI.png)

由于 `oschina` 的 URL 规则比较奇怪，所以采用了模糊查询方式，所以有些 URL 的确没有被适配，但也能显示 `阅读模式` 的icon，我会稍后加入 这个 url 的适配。

然后关闭这个 `issues` 后， 你可以通过 [这个方式](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%85%B3%E4%BA%8E%E6%9B%B4%E6%96%B0) 更新。

**Comment by Kenshin** [comment]
我已经加入了适配列表，但由于 oschina 有模糊匹配的情况，所以即便是从网络更新也会出现无法适配的情况，这算是个 bug，所以只能下个版本才能修复。

还好的是 https://www.oschina.net/code/list 
> “代码分享” 将于近期关闭，请将代码分享到码云 https://git.oschina.net ，谢谢合作

这个功能即将下线...

**Comment by TonyAble** [comment]
233

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`，
解决办法：增加  `https://www.oschina.net/code/list` 到适配列表。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
