### ISSUE TITLE
希望能适配Hexo搭建的站点

### ISSUE THREAD

**Issue by jostyee** [Kenshin/simpread#40]
用Hexo的站还是挺多的，现在只能聚焦模式

**Comment by Kenshin** [comment]
感谢建议~

阅读模式的适配是根据 URL，而非 Blog Framework，比如有两个 Hexo Blog：
http://www.a-hexo.com
http://www.b-hexo.com

但如果适配了 A 站，那么 哪怕 B 和 A 的结构一模一样，也没有办法让 B 站也同样适配，因为它们的 URL 不一样。
除此以外，简悦目前暂时没有办法识别 A 和 B 由哪种 Framework 生成。

下个版本将开放 `自行添加阅读模式` 功能， 或许有可能通过 `人工干扰` 的方式实现你说的方式，但前提也仅仅是 A 和 B 的页面结构一致...

**Comment by jostyee** [comment]
变动的主要是theme，正文结构应该都还是差不多的。

**Comment by Kenshin** [comment]
okay，如果这样的话，可以研究研究~

**Comment by Kenshin** [comment]
刚刚研究了一些 hexo 的页面结构，结果比较失望，目前 hexo 并没有什么唯一性标识能证明 某个页面是由 hexo 生成的，并且标题与正文的 html 结构差别太大。
所以之前的设想并不成立，但仍会考虑这类特殊的网址适配方案。

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 关闭。

增加了 `智能适配模式` 详细 [请看这里](https://github.com/Kenshin/simpread/wiki/%E6%99%BA%E8%83%BD%E9%80%82%E9%85%8D%E6%A8%A1%E5%BC%8F)

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
