### ISSUE TITLE
增强未知网站的命中率

### ISSUE THREAD

**Issue by helloyan** [Kenshin/simpread#400]
能否参考 https://chrome.google.com/webstore/detail/reader-view/iibolhpkjjmoepndefdmdlmbpfhlgjpl 的实现，他的命中率感觉非常高，例如 http://blog.sciencenet.cn/blog-3247035-1138248.html

**Comment by Kenshin** [comment]
谢谢建议~
你可以在多试试其它未适配的网站就会发现，简悦的「命中率」更高一些。
如果不是的话，请告知 URL

**Comment by helloyan** [comment]
后面我再留意看看。

**Comment by helloyan** [comment]
https://wallstreetcn.com/articles/3396449

**Comment by Kenshin** [comment]
https://simpread.ksria.cn/sites/

**Comment by helloyan** [comment]
你试试搜wallstreetcn是搜不到的
另外做个自动检测把，打开站点集市支持的域名提示用户进行安装

**Comment by helloyan** [comment]
https://www.whitehouse.gov
另外，简悦是否可以在阅读模式下支持其他的脚本应用，比如油猴的脚本

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

增加了 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)  大幅提高了智能识别的适配率，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
