### ISSUE TITLE
阅读模式失效、稍后读打不开

### ISSUE THREAD

**Issue by zzzzssssyyyy** [Kenshin/simpread#4003]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统MacOS

- 浏览器版本 **edge101.0.1210.53 (正式版本) (arm64)**

进入阅读模式后，右上角的侧栏不出现，且无法进行标注，右下角的启用/停用标注按钮无效。
<img width="258" alt="image" src="https://user-images.githubusercontent.com/74309824/170903899-0d20dd5a-eae9-4a1f-b902-df9fba070f21.png">

另外稍后读见面打开是空白的，出问题之前有频繁的标注、取消标注，点击侧栏标注的行为，不知道跟这个问题是否相关。

**Comment by Kenshin** [comment]
嗨，使用 https://github.com/Kenshin/simpread/discussions/3165 就可以解决。

> 出问题之前有频繁的标注、取消标注，点击侧栏标注的行为，不知道跟这个问题是否相关。

有，但不是绝对，也就是说这么操作不是 100% 能产生这种问题，只是有可能会产生这个问题。

**Comment by zzzzssssyyyy** [comment]
已经解决了，感谢🙏

**Comment by Kenshin** [comment]
okay 搞定就好~
