### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by delores0217** [Kenshin/simpread#4006]
发生问题的地址: <https://www.kaggle.com/code/charel/learn-by-example-active-inference-in-the-brain-1/notebook>

**Comment by Kenshin** [comment]
嗨，这个页面有 `iframe` 所以导致失败了，请问这是个什么网站（服务）？

**Comment by delores0217** [comment]
您好~我发现这个网站似乎是类似于jupyter notebook 这样的东西，里面嵌入的iframe应该是代码块&markdown的组合。自己点了一下发现网站本身似乎就可以编辑然后跑代码这样子，因为一开始主要是想复制一下里面的latex公式所以用网站自带的编辑模式解决了。


刚刚访问了一下原始网站https://www.kaggle.com/，发现确实是一个jupyter的环境hhh。
不知道这种适配起来是不是会很麻烦~

 

PS反馈居然这么快！！！我狠狠夸开发者！！！
















在 2022-05-30 16:12:33，"Kenshin Wang" ***@***.***> 写道：

嗨，这个页面有 iframe 所以导致失败了，请问这是个什么网站（服务）？

**Comment by Kenshin** [comment]
哈哈，谢谢喜欢简悦。😄 

我关闭这个 Issues 了。

***
要是有可能的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
