### ISSUE TITLE
【功能建议】希望稍后读中文章在阅读模式下可以使用“导出至obsidian”插件及相关自动化

### ISSUE THREAD

**Issue by IamApoorStudent** [Kenshin/simpread#4008]
如题，在稍后读中处理页面时无法使用配置好的相关自动化流程，导致我每次都需要打开源页面→（退出聚焦模式）→进入阅读模式，
既然阅读模式下已经加载了全文内容，那激活插件在技术上应该是可以实现的
如果标注模式也能支持导出至ob（有修改时自动化更新）最好了

**Comment by Kenshin** [comment]
嗨。

1. 自动化可以应用于稍后读。
2. 自动化辅助增强无法用于稍后读。

> 标注模式也能支持导出至ob

当然可以，建议看下 https://github.com/Kenshin/simpread/discussions/2902 的相关说明。
