### ISSUE TITLE
csdn博客文章无法自动加载其余部分

### ISSUE THREAD

**Issue by Fankbai** [Kenshin/simpread#401]
我已经使用“stylus”插件自动加载文章其他部分，但是使用simpread时，却无法加载进去其他部分内容，最先面显示“阅读更多”，不过点击后没有任何反应。

**Comment by Kenshin** [comment]
这是自然的，简悦会与某些插件有冲突，尤其是 `改变页面外观` 的扩展。

**Comment by Debatrix** [comment]
我使用的是firefox浏览器 没有安装改变页面外观的插件（也没有自动加载的） csdn使用阅读模式时也无法加载其他内容 阅读更多点击后没有效果

**Comment by Kenshin** [comment]
@Debatrix 
请问发 URL 上来

这个问题也可能是 csdn 的结构改变造成的，解决办法请看上面。

**Comment by Gittry** [comment]
@Kenshin  https://github.com/Kenshin/simpread/issues/401#issuecomment-437228614
带格式的适配有点问题，而且退出阅读模式后会造成原始界面排版问题

**Comment by Kenshin** [comment]
@Gittry 
带公式的情况暂时没办法解决，你可以看看 https://github.com/Kenshin/simpread/issues/418 的讨论。

`退出阅读模式后会造成原始界面排版`
你可以试试这个插件 https://simpread.ksria.cn/plugins/details/5Y3hZ88GmU
PS：我没有遇到你说的情况。

**Comment by Gittry** [comment]
@Kenshin 
确实重复出现了。
1. chrome下关闭了所有插件，打开https://blog.csdn.net/aws3217150/article/details/53840029显示正常；
2. 打开简悦插件，刷新页面后公式显示不正常，退出阅读模式，页面公式排版很乱；
![image](https://user-images.githubusercontent.com/7457523/48684273-dc42b000-ebeb-11e8-989d-21bc74b43048.png)

3. 关闭简悦，再刷新，页面恢复正常。

**Comment by Gittry** [comment]
好的

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

增加了 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎) 以及 [LaTeX 识别](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)  ，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
