### ISSUE TITLE
访问 mirror.xyz 的问题

### ISSUE THREAD

**Issue by sirs05** [Kenshin/simpread#4010]
之前这篇报错过，但好像今天不报错了。
https://viewdao.mirror.xyz/6CGlYphepRspxrFoTGcESaDvH7rVrz4pvGzONaHy4V8

**Comment by Kenshin** [comment]
嗨，抱歉漏掉了这个 Issues 试试下面的方案

请打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![image](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)

**Comment by sirs05** [comment]
是的，关闭以后可以解决。感谢

**Comment by Kenshin** [comment]
okay 搞定就好。
