### ISSUE TITLE
[bug] 在本地稍后读中优先打开本地HTML，备注会被视为正文，同时导致无法正常显示标注

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4012]
能稳定复现，随便找网页都这样，但不确定是否一直这样，似乎之前并没如此。
![image](https://user-images.githubusercontent.com/65625632/171321760-90ad86e9-d8f8-41f2-a131-96536ff9d7a4.png)
![image](https://user-images.githubusercontent.com/65625632/171321929-3be8c315-8599-4369-b6b4-a3c94f0b9649.png)
![image](https://user-images.githubusercontent.com/65625632/171321542-8394f45c-ace7-4344-835b-9075c0af1092.png)
至于导出的HTML在浏览器侧打开是能够正常显示标注与备注的，所以问题在于本地稍后读无法正常加载本地HTML。

**Comment by Kenshin** [comment]
嗨，这个问题已经可以被 Fixed 了，通过同步助手即可，同步助手这两周就会发布。

不过，你要是感兴趣的话，给 `help#####simpread.pro` 邮箱里面发邮件（注意 `#` → `@`）并注明这个 Issues ID：4012

我会提前把 rc 版先给你用用。（你应该是 windows 系统，对吧）

**Comment by XMB-7** [comment]
好的，我刚刚想到可以尝试在本地稍后读里面二次修改本地HTML，如果每次都在已导出的HTML的基础上做二次修改，就不必担心偶发的标注丢失问题了，然后就发现了这个bug。
那我稍后发一下邮件，麻烦把修复版提前给我发一份吧，感谢，若能如预期一样绕过标注丢失问题，我就不用再去折腾配置文件了。ps.是windows系统

**Comment by Kenshin** [comment]
嗨，Email 已发

新版不仅只是修改了这一处地方，你可以多测试测试。

**Comment by XMB-7** [comment]
在浏览器稍后读导出HTML。在浏览器打开，备注正常。在本地稍后读打开，备注正常。
![image](https://user-images.githubusercontent.com/65625632/171545855-d5f3dfc2-e733-42b2-8a5c-5e0ff84ce69b.png)

---

但在本地稍后读导出HTML，就会出现问题。导出的HTML在浏览器打开，备注就已经异常了。在本地稍后读打开，备注依然异常。
![image](https://user-images.githubusercontent.com/65625632/171545951-3754f7a8-e472-47a0-85dc-30f88e928f25.png)
![image](https://user-images.githubusercontent.com/65625632/171545882-cf9590db-357f-4237-b3cf-a900cd76c8a7.png)

**Comment by Kenshin** [comment]
> 但在本地稍后读导出HTML，就会出现问题。

是指什么操作？具体 URL 是什么？

> 导出的HTML在浏览器打开，备注就已经异常了。

直接打开这个 HTML 吗？

**Comment by Kenshin** [comment]
我好像知道你说的问题了。

> 在 **稍后读的阅读模式导出 HTML** 有问题，是吧？

**Comment by XMB-7** [comment]
> 在 稍后读的阅读模式导出 HTML 有问题，是吧？

是的
![image](https://user-images.githubusercontent.com/65625632/171565493-47af637a-0797-44ed-a5ca-8c6043fb27d9.png)

**Comment by Kenshin** [comment]
我修复了你提高的问题，通过下图方式下载，可以点击 **检查更新**。

![image](https://user-images.githubusercontent.com/81074/171572265-11c1e98c-6373-4f58-9b05-fea644e32ea6.png)

**Comment by XMB-7** [comment]
请问修复之后的版本号有改变吗, 我这边点击检查更新没有弹出任何提示.
![简悦_·_同步助手_0yQEcaisbU](https://user-images.githubusercontent.com/65625632/171670977-0221c38e-c939-4fde-bf9b-21e911351628.gif)

**Comment by Kenshin** [comment]
邮件已发~

**Comment by XMB-7** [comment]
收到, 感谢. 试了一下, 备注问题已修复, 目前已能通过本地稍后读的阅读模式直接修改本地HTML文件, 估计可以帮我绕过浏览器稍后读的标注丢失问题, 太有用了.

---

顺带发现一点小瑕疵, 本地稍后读导出HTML似乎没能读取全局自定义样式.
我修改css将第三号标注颜色从蓝色改为紫色. 在浏览器稍后读中导出本地HTML之后, 用浏览器直接打开本地HTML, 能够正常显示紫色. 但在本地稍后读的阅读模式中导出本地HTML, 再用浏览器直接打开, 紫色将恢复为蓝色.
这将导致, 在手机等其它设备上通过阅读列表查看稍后读, 显示效果不如本机上的好.
![image](https://user-images.githubusercontent.com/65625632/171782315-2a20d621-ec3f-41ef-9523-afb6b9b6a652.png)
![image](https://user-images.githubusercontent.com/65625632/171781974-e2e98140-b5e1-4a26-a1a0-1254646bad14.png)

**Comment by Kenshin** [comment]
> 我修改css将第三号标注颜色从蓝色改为紫色. 在浏览器稍后读中导出本地HTML之后, 用浏览器直接打开本地HTML, 能够正常显示紫色. 但在本地稍后读的阅读模式中导出本地HTML, 再用浏览器直接打开, 自定义紫色将恢复为蓝色.
这将导致, 在手机等其它设备上通过开放平台阅读列表查看稍后读, 显示效果不如本机上的好.

确实没有关于自定义样式的保存，我考虑下，当前版本已经 Release 了，暂时不想加更多的功能，而且标注颜色的自定义这块确实也有点问题，可以作为 Feature 处理。

另外，把你改颜色的代码放上，我看看。

**Comment by XMB-7** [comment]
> 另外，把你改颜色的代码放上，我看看。

我不太懂css, 就是照着网上css片段例子改的. 改了第1号标注的颜色, 改了第3号标注的颜色和图标颜色. 或许把变量从类内局部修改换成全局修改可能会解决?
```
sr-annote {
    --sr-annote-color-1: #ffea80;
    --sr-annote-color-3: #d1c5f2;
    padding: 3px 0;
    background-color: transparent;
    font-size: inherit;
    cursor: pointer;
}
[sr-annote-bg-color][data-color-type="3"] {
    --sr-annote-color-3: #d1c5f2;
    background-color: var(--sr-annote-color-3);
}
```

**Comment by Kenshin** [comment]
okay

标注颜色涉及的地方比较多，所以不是简单的自定义样式可以 100% 解决的，这也是没法放到当前版本的原因，不过你的做法倒是给我了一些思路。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 解决了备注的问题

😄 你应该早就用上了，但还是建议使用正式版。😄

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
