### ISSUE TITLE
简悦插件导致访问https://www.notion.so/desktop网址访问异常

### ISSUE THREAD

**Issue by LinnyR** [Kenshin/simpread#4015]
出现的问题报错：Application error: a client-side exception has occurred (see the browser console for more information).
![image](https://user-images.githubusercontent.com/38827394/171553893-724f3c09-ca90-40cf-a7c2-d014fcfb9446.png)
关闭简悦插件后
![image](https://user-images.githubusercontent.com/38827394/171554143-998a8877-aa8c-4865-95c3-29058d4d3347.png)

刚开始以为是油猴插件和ublock插件的问题，就把两个插件都关了，问题依旧，然后尝试关闭简悦插件，网页就能打开了，通过控制台也没有看出什么问题。

**Comment by LinnyR** [comment]
目前就只发现这个网址，其他的不知道还有没有

**Comment by Kenshin** [comment]
嗨，可以使用下面的方式解决

请打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![image](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)

目前发现 Notion、noto.so 与 ~~维基百科~~（已彻底解决
