### ISSUE TITLE
阅读模式图片无法显示

### ISSUE THREAD

**Issue by jackson348** [Kenshin/simpread#4018]
![image](https://user-images.githubusercontent.com/70902056/171778619-09b8c159-1174-48e9-a350-3e8ca7fb59bd.png)
点击重新加载也无法显示

**Comment by Kenshin** [comment]
嗨，请告知具体 URL

**Comment by jackson348** [comment]
https://kns.cnki.net/KXReader/Detail?invoice=cXy3UdBHYzwcpfA99nVkEMIrFBOYFdUtQ6LFizYseK1a14DeRo1%2FLxunPxS6uItw%2Ft2%2FRnOEFW1WeDRFNKw6jY4nb3BFIovp9Wp3FIAswu5%2BHYYJAlrmauBdV%2FIJfsqT%2FHZfzGVTnTXscWcZPeOvTnWQnFYvHopXmH3%2BdTHqG9k%3D&DBCODE=CJFD&FileName=CLDB202105011&TABLEName=cjfdlast2021&nonce=12FB154A4FA44D5695B2766FB75C93EB&uid=&TIMESTAMP=1654224917109

**Comment by Kenshin** [comment]
嗨，知网的话，请使用 https://github.com/Kenshin/simpread/discussions/3537 提到的方案。
