### ISSUE TITLE
少数派阅读模式表格过长时候显示不全

### ISSUE THREAD

**Issue by wangjinbaor** [Kenshin/simpread#4021]
在少数派一篇文章时候，在阅读模式中显示不全，而且会超过阅读范围
![image](https://user-images.githubusercontent.com/58154171/171989469-6aa26457-7353-483f-8f57-1f20bf567675.png)
如果更长就会超过显示范围
![image](https://user-images.githubusercontent.com/58154171/171989488-7f80e11c-7aa3-4fab-b01c-8b990c147f8b.png)

**Comment by Kenshin** [comment]
嗨，把 URL 给我看下。

**Comment by wangjinbaor** [comment]
> 嗨，把 URL 给我看下。

https://sspai.com/post/72756
是付费专栏

**Comment by Kenshin** [comment]
我能看到，但我没有遇到你说的问题。

1. 建议请详细告诉我出问题的表格，或者截图截取的大一些 😂 这篇文章太长了，我根据你的截图根本没法定位。

2. 你在使用什么主题，你可以试试更换主题看下。

**Comment by wangjinbaor** [comment]
![图片](https://user-images.githubusercontent.com/58154171/171990714-7c203e62-597a-4fec-ab1e-fb86436abed4.png)
![图片](https://user-images.githubusercontent.com/58154171/171990726-2dc3ec8c-a52a-43b9-9476-a5406a9498f2.png)

**Comment by wangjinbaor** [comment]
> 我能看到，但我没有遇到你说的问题。
> 
>     1. 建议请详细告诉我出问题的表格，或者截图截取的大一些 😂 这篇文章太长了，我根据你的截图根本没法定位。
> 
>     2. 你在使用什么主题，你可以试试更换主题看下。

更换主题后依然是这样
![图片](https://user-images.githubusercontent.com/58154171/171991468-97dc3abc-f3f3-4cfa-98fb-b199154c90f5.png)
再次更换
![图片](https://user-images.githubusercontent.com/58154171/171991491-c703e299-5a52-434e-b372-d8b9fc979796.png)

**Comment by wangjinbaor** [comment]
> 我能看到，但我没有遇到你说的问题。
> 
>     1. 建议请详细告诉我出问题的表格，或者截图截取的大一些 😂 这篇文章太长了，我根据你的截图根本没法定位。
> 
>     2. 你在使用什么主题，你可以试试更换主题看下。

表格定位
![图片](https://user-images.githubusercontent.com/58154171/171991551-8b5b3fcf-7182-4b5d-9224-e4a7bf3ed20b.png)

**Comment by Kenshin** [comment]
将下面的代码

```
sr-read figure {
    overflow-x: scroll;
}
```

加入到下图，保存后刷新当前页面

![image](https://user-images.githubusercontent.com/81074/171991630-a51bbe02-2b9a-4903-917c-c992ac30fa66.png)

效果如下

![image](https://user-images.githubusercontent.com/81074/171991668-2d760bc8-d7f2-48bd-a946-d361f2e831a8.png)

**Comment by wangjinbaor** [comment]
好的，已解决，谢谢

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
