### ISSUE TITLE
简悦同步助手首次打开弹窗无法消失问题

### ISSUE THREAD

**Issue by xozoz** [Kenshin/simpread#4024]
> 环境

- os: macos monterey
- 同步助手：1.0.1(mac)

> 问题

- 每次首次打开简悦同步助手，都会弹出，“是否允许同步助手使用本地网络"的警告弹窗，且该弹窗，即使点击了允许也不会消失

<img width="268" alt="CleanShot 2022-06-05 at 21 13 20@2x" src="https://user-images.githubusercontent.com/21237993/172052178-fccbdeed-37c5-4290-b870-a2314fedbe5e.png">

- 而且非常流氓的是，即使我强制退出了同步助手，该弹窗还是不会消失

> 已经采用的解决方案

- 重启电脑后，再次打开同步助手，仍旧复现

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/issues/2100#issuecomment-850217405

另外，下周会有新版发布，应该会彻底解决这个问题。

**Comment by Kenshin** [comment]
> 嗨，各位，确实等的太久了。

![welcome-synchelper](https://user-images.githubusercontent.com/81074/172756557-608b3e22-085f-43da-b2c7-d008503db009.png)

# 解决网络使用时反复提示的问题

新版运行后应该没有此问题了。

## 下载地址

https://simpread.pro/download

## 更新说明

1. [Telegram Channel](https://t.me/simpread/407)

2. [Notion](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#15e6f9d3f41f483b8e005ddf3b23e255)

## 如何升级

1. 打开同步助手后会自动提示升级。
2. 通过上面的下载地址手动升级。

# 不止如此

1.0.2 版还增加了以下新功能：

- [PDF 高级打印方式](https://github.com/Kenshin/simpread/discussions/3887)，自带目录结构、提供了定制化服务，包含主题、字体、页边距等细节。

- [日志输出](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)。

- 将导出文件导出到任意文件夹的 [增强导出方案](http://ksria.com/simpread/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)。

不止如此，**优化和修复 60+ Isues**，包括：修复自启动无效、隐藏 Dock 栏，Menubar icon 颜色自适应等，墙裂建议用户升级。

# 附录

以下是自定义导出 PDF 的一些截图

![image](https://user-images.githubusercontent.com/81074/172757646-37b4e8ee-19c7-4f99-ba39-3fbdecc50c3e.png)

![image](https://user-images.githubusercontent.com/81074/172757663-f773c9aa-9650-46ec-84e2-c08e868c6244.png)

![image](https://user-images.githubusercontent.com/81074/172757678-7e00bdbe-aefc-4713-9648-55e6ff87993b.png)

# 彩蛋

同步助手 1.0.2 发布后即将进入「快车道」 更新的新版已经在测试了。😄

***

我关闭这个 Issues 了，有任何问题，仍可随时在这里讨论。😄
