### ISSUE TITLE
Linux 命令行版本 同步助手 Logseq 知识库 搭建

### ISSUE THREAD

**Issue by Chefback** [Kenshin/simpread#4025]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Arch Linux**

- 浏览器版本 **Chrome 101**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

1.跟着这个[https://zhuanlan.zhihu.com/p/489510457](链接)一步一步做，但是在批注后并没有看到以@annote结尾的md 和 html 文件，
不知道是命令行版本的问题还是我设置的问题。
2.想加入 simpread 电报群，提示被adminban了。

**截图**
> 一图胜千言，所以方便的话，可以试着贴图。
![2022-06-05_22-32.png](https://s2.loli.net/2022/06/05/tRgLE5JYQpw4lcU.png)

**Comment by Kenshin** [comment]
> 问题一

命令行版本具有此功能。至于你的问题，应该还是你配置的问题，看下面的截图

![image](https://user-images.githubusercontent.com/81074/172084704-2a433b57-603a-4095-9ab5-3fabcb3d3afc.png)

> 想加入 simpread 电报群，提示被adminban了。

估计是你忘记验证了，加我 @kenshin726

**Comment by Chefback** [comment]
> > 问题一
> 
> 命令行版本具有此功能。至于你的问题，应该还是你配置的问题，看下面的截图
> 
> ![image](https://user-images.githubusercontent.com/81074/172084704-2a433b57-603a-4095-9ab5-3fabcb3d3afc.png)
> 
> > 想加入 simpread 电报群，提示被adminban了。
> 
> 估计是你忘记验证了，加我 @kenshin726

好的，我再试试

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
