### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by XMTangHu** [Kenshin/simpread#403]
该网页阅读模式无法显示完整。[https://blog.csdn.net/yangzhao0001/article/details/48707407](https://blog.csdn.net/yangzhao0001/article/details/48707407)

**Comment by XMTangHu** [comment]
![tu](https://user-images.githubusercontent.com/13711691/46647590-7cf08980-cbc3-11e8-8de7-26db9014ee7e.png)

**Comment by XMTangHu** [comment]
配置为ESC退出时，`阅读模式`实际操作无法退出，但`聚焦模式`可退出。

**Comment by Kenshin** [comment]
`ESC` 退出并没有问题，请确认是否是 Chrome 浏览器，Firefox 快捷键在 `阅读模式` 下均无法使用。

可以通过重选选取高亮区域来框选 → 右下角控制器 → 动作面板 → 第一排第二个 icon 即可。

**Comment by XMTangHu** [comment]
嗯 了解。

**Comment by Kenshin** [comment]
没有问题的话，我关闭此 issues 了~  😀
