### ISSUE TITLE
[bug?] 本地配置文件不包含已安装的插件以及插件的具体配置

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4032]
如题, 前两天在备份了本地配置文件之后, 在浏览器上重置了配置文件.
现在再导入备份的本地配置文件, 发现简悦配置, 稍后读等等信息都恢复了, 但已安装的插件以及插件的具体配置丢失.

**Comment by Kenshin** [comment]
嗨，我看你关闭了这个 issues 是解决了吗？

1. 插件配置是会被正常导出的。
2. 插件本身是不会被导出的，因为太大了，会导致导出文件过大。
3. 配置文件导入后会有提示重新获取插件。

可能因插件触发器缘故导致（隐含 Bug，小概率、不确定及不稳定发生）有可能导致 1 没有被导出。

**Comment by XMB-7** [comment]
解决了, 还需要手动导入一下插件. 因为我没有在浏览器上导入配置文件, 而直接在坚果云上恢复了历史版本. 所以对于这种途径, 或许给出一个提示会更好.

**Comment by Kenshin** [comment]
其实是有提示的，但因为高级账户缘故，导入后会重新刷新浏览器来获取高级账户权限，导致提示信息就没有了。

我已记录这个情况了。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0，包含了 **手动导出全部插件配置到本地的功能**。

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4
