### ISSUE TITLE
阅读模式解析错误：有的代码块在解析后丢失

### ISSUE THREAD

**Issue by Edge-coordinates** [Kenshin/simpread#4033]
在这个网址：[宽爬行 — Scrapy 2.5.0 文档](https://www.osgeo.cn/scrapy/topics/broad-crawls.html),  
这是解析后的内容：  
![image](https://user-images.githubusercontent.com/68896486/172516581-1602d6a1-dc52-4be5-8b90-223c4f42c9f7.png)  
这是原内容：  
![image](https://user-images.githubusercontent.com/68896486/172516618-78f0a66d-df02-484f-8c3c-f1be36ef1d6f.png)
发现有不少`请使用`后面的代码块没了。。。

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
另外，试试关闭代码高亮插件。

代码段的问题很难有通用性的解决方案。
