### ISSUE TITLE
[bug?] PDF辅助增强插件, 导出PDF无法忽视标注

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4038]
之前我提了一个FR, 希望能在导出PDF时忽略标注和备注.
然后看到今天的wkhtmltopdf方案, 里面恰好就有这样一条设置, 但是试了一下, 似乎无效. 或许是我误解了这一功能? 
ps.wkhtmltox已正确配置.
![image](https://user-images.githubusercontent.com/65625632/172802660-aebfe290-341d-40d7-be4e-df8c54e1a6cf.png)
![image](https://user-images.githubusercontent.com/65625632/172802821-7b1113d8-0337-4c2e-9e6e-afbdc4b59ac4.png)

**Comment by Kenshin** [comment]
就是这个意思，不应该有标注色才对，而且我测试是没问题的。

留意下需要选择导出方案

![](https://user-images.githubusercontent.com/81074/172297297-23633dcf-1495-4b4c-bef8-2b3dd5ece036.png)

**Comment by XMB-7** [comment]
> 留意下需要选择导出方案

这个没问题

有没有可能是因为我下载了wkhtmltox的压缩包, 完了配置了环境变量?

**Comment by Kenshin** [comment]
再确认下，应该不会有问题的。

另外，留意下：先保存后再导出。

PS：要是其他用户反馈，第一反映肯定是操作（步骤）问题，但你... （瑟瑟发抖 😂

**Comment by XMB-7** [comment]
我又把配置文件重置了，这个问题跟稍后读界面异常问题都没了，配置文件一恢复，俩问题又都回来了。猜测可能是已安装的插件之间(或许是某些插件配置之间)相互冲突，我再测测。

**Comment by Kenshin** [comment]
你发错 Issues 了吧？😂

虽然我知道你说的是什么…

**Comment by XMB-7** [comment]
我大概知道问题是什么了，应该是PDF增强插件与浮动面板定值插件和悬浮球插件冲突，因为后两者有旧版的“导出为PDF”的相关设置选项，但新版的却已经变为了“PDF”。
我把插件全清了然后安装PDF增强并设置, 就没有问题. 所以目测使用这个新功能需要把那俩插件给删了重新安装并设置.
![image](https://user-images.githubusercontent.com/65625632/172876386-712951df-99d7-4ce1-9381-ee028983ab28.png)

**Comment by Kenshin** [comment]
> 应该是浮动面板里的导出为PDF和右下角的打印功能按钮行为不一致。进而导致PDF增强插件与浮动面板定值插件和悬浮球插件冲突，因为后两者都含旧版的“导出为PDF”的相关设置选项。

理论上没关系...

> 又遇到了插件设置保存不下来的问题,

这不是你 Issues 描述的问题，这个问题可以通过：

1. 取消自动同步
2. 设置各种插件行为
3. 设置完毕后，重启浏览器
4. 开启自动同步并覆盖本地的配置文件

来解决。

**Comment by XMB-7** [comment]
你可以试一下, 把配置文件重置, 只安装PDF增强, 然后随便找个网页.
![image](https://user-images.githubusercontent.com/65625632/172974987-5776b3cf-5100-4129-b707-1c3d160cb754.png)

而且问题似乎出自浮动面板设置器, 因为我记得昨晚测试好使的时候, 这个“导出为PDF”名叫“PDF”处于最后一行, 但现在显然不是, 即便我已经重置了配置文件, 似乎它依然在读取我曾经的插件设置.

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/172976048-f1641a36-d8dd-4434-b64f-5ba8659cc173.png)

上图这两个的行为一定是当然不一样。

上面的只能使用：浏览器 PDF 和 基础 PDF，而高级 PDF 是这个插件也就是下面 icon 对应的功能。

**Comment by XMB-7** [comment]
> 上面的只能使用：浏览器 PDF 和 基础 PDF，而高级 PDF 是这个插件也就是下面 icon 对应的功能。

呃, 那我如果把下面这个功能按钮给隐藏了, 不就调用不了高级PDF了么, 那隐藏这个功能按钮的选项本身的存在性就不合理了...

**Comment by Kenshin** [comment]
出错的问题，看看是不是 https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490 造成的？
另外看出错信息，应该是路径写错了

![image](https://user-images.githubusercontent.com/81074/172986769-a68f9910-3d59-4d93-a992-54ca7db7d34e.png)

> 呃, 按我理解, 似乎不存在既使用基础PDF又使用高级PDF的需求, 即便有需求, 到插件设置里调换即可, 所以对PDF的设置应该是全局统一的, 这俩按钮应该干的是一个活. 然后用户就能选择是在浮动面板外面调用, 还是在浮动面板里面, 还是在悬浮球里.

不是这么理解的。

第一个 icon 是内置的功能，仅可使用浏览器或 1.0.1 版的 PDF 功能。
第二个 icon 是插件的功能，所以这个插件叫做「PDF 辅助增强」，第一个 icon 没法使用 1.0.2 对应的高级 PDF 功能。

所以第一个 icon 永远无法调用 1.0.2 版的功能，除非扩展端版本升级才能解决。

**Comment by XMB-7** [comment]
一开始我是设了环境变量的, 结果也报错.
![image](https://user-images.githubusercontent.com/65625632/172989996-61909676-21f6-4746-b7c0-77eab74e0f7a.png)
然后手动设置了wkhtmltox路径(现在补上\之后), 也还报错.
改了输出路径也没用, 加了管理员权限也没用.
或许真是不能放C盘, 但我手头的笔记本一共就256G没做分区, 得换个电脑测试.

**Comment by Kenshin** [comment]
你是 Win 11 吗？

如果只有一个盘的话，换其它非 Windows 的目录。

**Comment by XMB-7** [comment]
我把wkhtmltox放到移动硬盘里也不行, 先这样吧, 看别人好像都正常, 可能是我这边的问题, 我最近也准备换电脑了.

> 所以第一个 icon 永远无法调用 1.0.2 版的功能，除非扩展端版本升级才能解决

有没有意向在未来版本把所有功能全都插件化呢, 类似开源插件bilibili evolved, 插件本身就是一个空壳子, 全部的功能和相关设置都以插件形式存在. 
因为目前必需的插件很多了, 远远超出推荐数量的6个, 比如悬浮球, 浮动面板定值器, PDF增强, 导入obsidian, markdown模板增强, live editor, 自动化增强, 代码增强, 英语阅读增强, 删除描述. 算上其余可用可不用的, 我总共安装的插件得有25个左右.

**Comment by Kenshin** [comment]
> 我把wkhtmltox放到移动硬盘里也不行, 先这样吧, 看别人好像都正常, 可能是我这边的问题, 我最近也准备换电脑了.

只有个别用户不行 😂

> 目前必需的插件很多了, 远远超出推荐数量的6个

这个数字只是个提示，不具有任何实际问题，但确实安装多了会引起性能问题，但好在目前大多数情况下，系统都是性能过剩。

我目前安装了 56 个（开着的大概 50+ 😂

![image](https://user-images.githubusercontent.com/81074/173045703-26ed7c24-dd9e-4a65-a57f-c7066b0cb11e.png)

**Comment by Kenshin** [comment]
嗨，我先关闭这个 Issues 了~
