### ISSUE TITLE
Pandoc 导出失败，此功能为实验性功能

### ISSUE THREAD

**Issue by ethanchengyu** [Kenshin/simpread#4039]
<img width="957" alt="iShot_2022-06-10_09 59 12" src="https://user-images.githubusercontent.com/25861044/172975157-a8285e72-10e9-4a6a-906b-1cc3d0aad3b2.png">
--
配置应该都没问题，可是动作后这样提示了，不知道怎么回事

**Comment by Kenshin** [comment]
嗨，通过 [此教程](https://kb.simpread.pro/#/page/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA) 来判断你的是否正确。

另外，小书签的问题也在这里说吧，跟那个 Issues 已经彻底无关了。

**Comment by ethanchengyu** [comment]
> 嗨，通过 [此教程](https://kb.simpread.pro/#/page/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA) 来判断你的是否正确。
> 
> 
> 
> 另外，小书签的问题也在这里说吧，跟那个 Issues 已经彻底无关了。

这个问题跟双链那个一样（知识库建立的其中一步），配置跟着做，可是还是提示错误

**Comment by Kenshin** [comment]
竟然间隔了 20+ 天...

1. 你调用了什么服务导致的？（截图所示）
2. 关闭自动同步，安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 在开启自动同步，并覆盖本地

看看能否解决？

**Comment by ethanchengyu** [comment]
> 竟然间隔了 20+ 天...
> 
> 1. 你调用了什么服务导致的？（截图所示）
> 2. 关闭自动同步，安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 在开启自动同步，并覆盖本地
> 
> 看看能否解决？

我竟然也是20+才想起这个问题哈
1.如下图
<img width="998" alt="image" src="https://user-images.githubusercontent.com/25861044/176683121-2a524337-64cd-458e-b6e6-17dc5645861c.png">

2.试过了，还是上图的错误

**Comment by Kenshin** [comment]
1. 试试导出 Epub 功能是否可用？
2. 你的 `pandoc` 能直接运行吗？

如果 `pandoc` 能运行的话，试试随便导出一个 `.md` 然后改名为 `aaa.md` 然后进入这个目录，直接使用 

`pandoc aaa.md -o aaa.docx` 看看是什么效果？

**Comment by Kenshin** [comment]
emmm 你使用的是什么版本的同步助手？以及你的系统是？

**Comment by ethanchengyu** [comment]
> emmm 你使用的是什么版本的同步助手？以及你的系统是？

同步助手1.1.1
系统如下
<img width="299" alt="image" src="https://user-images.githubusercontent.com/25861044/176881909-da9686dd-7f4e-49db-a36e-80285301e3b5.png">

**Comment by Kenshin** [comment]
1. 你的 pandoc 是安装在默认环境下吗？
2. 使用 `pandoc --version` 得到 pandoc 的默认目录，把它加入到环境变量中。比如 bash or zsh

**Comment by ethanchengyu** [comment]
情况如下，不知道是不是已经在环境变量中？
<img width="606" alt="image" src="https://user-images.githubusercontent.com/25861044/176883134-9e0d5733-a1f2-4854-b236-359efef8016e.png">

**Comment by ethanchengyu** [comment]
我是按照以下步骤操作安装的，

> 请确保 pandoc 在你的 /usr/local/bin/ 目录下存在，同时也确保此目录在 $PATH 下。一般情况下 /usr/local/bin/ 都会存在于 $PATH 下。可以使用如下命令检验：which pandoc → 查看 pandoc 所在目录PS：一般使用 pandoc-xxx-macOS.pkg 安装的话，自然是 /usr/local/bin/ 目录。
<img width="356" alt="image" src="https://user-images.githubusercontent.com/25861044/176883708-ba28879c-32c6-4cd1-8ed7-faaa4cb58f36.png">

**Comment by Kenshin** [comment]
emmm 

我好像重现了这个问题，如果确认有问题的话，我会在这里通知你。

但只能下个版本修复了，预计下周。

**Comment by Kenshin** [comment]
okay 已确认。

很奇怪，在我的开发环境没问题，但编译后确实有问题... 😂

**Comment by ethanchengyu** [comment]
好的，不然耽误了你好多时间

**Comment by Kenshin** [comment]
哈哈，没事。

因为这是个 Bug（ 跟另外一个功能有关系），但我确实已经修复了... 但问题发生应该就是近期 😂

你要是着急的话，修复完我先编译个版本给你。

**Comment by ethanchengyu** [comment]
不着急的，出来了能用就行哈

**Comment by Kenshin** [comment]
嗨，[1.1.1702 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-3067829) 已经发布了，修复了此问题。

[下载地址](http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd) 

我关闭这个 Issues 了，有任何问题随时在这里讨论。
