### ISSUE TITLE
[Firefox] 反馈问题（无法获取）

### ISSUE THREAD

**Issue by CaiJie0611** [Kenshin/simpread#404]
1.插件是6月才更新的，想要查找是否更新，但firefox扩展市场搜索不到简悦，如图↓
![default](https://user-images.githubusercontent.com/31266850/46807829-7ae22280-cd9d-11e8-8ae7-9eac5fb6e945.png)
![default](https://user-images.githubusercontent.com/31266850/46807772-5be39080-cd9d-11e8-9810-5865f00ddb02.png)

**Comment by Kenshin** [comment]
请问你的 Firefox 版本是否是 1.1.2 如果是的话，就是最新版。

发生这个问题的原因是 ，Mozilla 把简悦下架了，原因是他们更新了一些政策 https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page 导致的，我正在协调重新上架（需要时日...）

或者，我会考虑不上架到 Mozilla 的 Add-on 里面，直接提供下载地址...

**Comment by CaiJie0611** [comment]
原来这样，我的版本是1.1.1的，能否提供最新的插件文件。

**Comment by Kenshin** [comment]
请方便的话，立即更新版本到 1.1.2.1025 否则几天后就会被下架...  😂 
下载地址 https://addons.mozilla.org/zh-CN/firefox/addon/simpread/

**Comment by Kenshin** [comment]
嗨，各位，简悦 for Firefox 版正式发布了~

<img width="808" height="455" alt="Image" src="https://github.com/user-attachments/assets/58297ed1-551a-4fd1-b603-f42e7b4d9dbc" />

# 📚 支持浏览器

Zen browser · Firefox Nightly · Firefox Developer Edition · Firefox · Librewolf

# 🔗 如何使用 & 简悦 CRX 下载

[https://github.com/Kenshin/simpread/discussions/7279](https://github.com/Kenshin/simpread/discussions/7279)

注意：请不要使用 Chrome Webstore 下载的 crx，请使用专门为 Firefox 适配的 crx（上面链接有下载地址）

# ✅ 完美支持

- 阅读模式 / 聚焦模式

- 安装插件

- 更新站点

- 稍后读 / 标注

# ✳️ 需配合 [同步助手 1.5.0](https://n.simp.red/posts/648) 后支持

- 自动同步

# ❎ 不完美支持

快捷键暂时无法使用，但你可以使用 **全局快捷键解决无法进入阅读模式和加入稍后读的问题**，也可以使用 **Assistive Touch 解决简悦插件快捷键无法使用的问题**，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16470898)

# 在 Firefox 正式版使用简悦

如果你不希望更换上述浏览器，在 Firefox 也可以正常使用，但需要一些技巧，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16446625) 

# 最后

有任何问题统一在 [https://github.com/Kenshin/simpread/issues/7037](https://github.com/Kenshin/simpread/issues/7037) 讨论

我关闭这个 issues 了~
