### ISSUE TITLE
语雀无法授权了（个例）

### ISSUE THREAD

**Issue by metisky** [Kenshin/simpread#4043]
语雀无法授权了

**Comment by Kenshin** [comment]
大部分用户没有问题，但确实有个别用户反馈。我也不知道为什么 😂

因为我没有问题，所以没法 Debug

**Comment by wyrain** [comment]
> 语雀无法授权了

可以试试我这个issue下, 另外一位大兄弟的解决方案
https://github.com/Kenshin/simpread/issues/3801#issue-1216697765

**Comment by Kenshin** [comment]
@wyrain 

嗨，谢谢提示 🙏 如果确保能解决，我会放到 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5) 中。

**Comment by metisky** [comment]
> 语雀无法授权了

经测试以下方法可行：
1、 在语雀的下图区块（账户设置-token）生成一个token
![image](https://user-images.githubusercontent.com/45676415/173167209-ee9938d8-475f-42e5-ae32-5cfe1fe440c9.png)

2、生成token后将该token进行复制
3、进入简悦-共通，导出配置文件
4、用text打开该配置文件，在配置文件中找到"yuque":{"access_token":"   在后边将该token复制
![image](https://user-images.githubusercontent.com/45676415/173167271-905087be-76c5-4168-aa27-3184171a32a0.png)
5、进入简悦-共通，将该配置文件进行导入即可。


作者可以联系我workyzx@gmail.com进行远程复现问题

**Comment by Kenshin** [comment]
@metisky 

Cool 搞定就好  👍 

>  workyzx@gmail.com进行远程复现问题

先谢谢了。🙏

其实也没法有效调试，最好的方式是我能用你的语雀账户测试。

**Comment by wyrain** [comment]
> 

你拿他账户也没用，应该是浏览器在某种情况下把本地配置里的token搞掉了，不然无法解释我换个浏览器又行了，以及家里电脑不行公司电脑又行了这两种情况，跟电脑、网络、账户没关系，跟浏览器和本地配置有关系。

**Comment by Kenshin** [comment]
@wyrain 

语雀使用了正常的 API 获取方案，跟 Cookies 等都没有关系，而且获取后的 Token 是存放在简悦的数据环境中的。

@metisky 

试试安装一个全新的浏览器，然后什么都更改的前提下使用。

**Comment by Kenshin** [comment]
@wyrain @metisky 

嗨，各位，我已经将此方案记录到了 https://github.com/Kenshin/simpread/discussions/4052 🙏
