### ISSUE TITLE
[bug] 将B站视频页面加入稍后读, 查看的时候将会自动播放该视频, 只能通过进程关闭

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4046]
如题, 在稍后读中点击查看一篇视频页面, 将会进行自动播放, 此时看不到解析的页面, 但能听到声音. 关了稍后读没用, 必须到任务管理器里面把相应进程关了才行. 其它视频平台页面没试, 或许同样如此.
![image](https://user-images.githubusercontent.com/65625632/173167354-372a99dd-44d9-48ad-8248-37c2d03717fe.png)

**Comment by Kenshin** [comment]
嗨，这不算是 Bug，因为目前并不支持这种方案。😂

所以我关闭这个 issues 了，但你之前提的 https://github.com/Kenshin/simpread/issues/4037 我想到个解决方案，但不太确定。

有类似想法或问题可以直接放到上面的链接中。
