### ISSUE TITLE
稍后读页面启动报错崩溃

### ISSUE THREAD

**Issue by caosbad** [Kenshin/simpread#4048]
![image](https://user-images.githubusercontent.com/10805199/173175286-a23f72a9-4efb-4eb0-afdd-57dd7ee6c01f.png)
之前在阅读文章进行大量标注之后，曾经出现过标注信息丢失的情况，再然后就导致稍后读页面卡死，MacOS 系统，开启了同步助手，在不同的浏览器测试得到了同样的报错，猜测是因为数据问题导致，启动阶段出现异常，影响了稍后读的加载。

**Comment by Kenshin** [comment]
嗨，是否使用了 同步助手 + 坚果云？如果是的话，可以通过坚果云的历史记录还原，可以看此教程 https://github.com/Kenshin/simpread/discussions/3165

**Comment by caosbad** [comment]
删掉了 null 值，已经恢复了，非常感谢

**Comment by Kenshin** [comment]
Cool~ 搞定就好，同步助手会内置此功能，省去了手动修改的过程。😄
