### ISSUE TITLE
请问为什么经过我手动“高亮和隐藏元素”的页面 ，当我保存到稍后读之后，在稍后读里又变成了没有经过调整的页面版式？

### ISSUE THREAD

**Issue by e9on** [Kenshin/simpread#4050]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
如果要实现你说的方式，需要配置知识库，这是 [教程](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)

**Comment by e9on** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/38707987/173211086-0376a001-be47-4db9-86d3-85c4c78634d2.png">
按照你提供的教程设置了，也显示了本地资源图标，但是稍后读阅读模式点进去加载的依然不是我调好的本地版式

**Comment by Kenshin** [comment]
@e9on 

Issues Close 后也能使用，请不要重复的建立相似内容，直接在这里讨论。

> 按照你提供的教程设置了，也显示了本地资源图标，但是稍后读阅读模式点进去加载的依然不是我调好的本地版式

这个图对应的是正确的，但你需要在使用 Live Editor 编辑后重新导出 HTML，另外下图的选项开了吗？

**Comment by e9on** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/38707987/173213922-b3023bcc-a53f-4959-a729-6ef3ed7c80fa.png">
已经选了

**Comment by e9on** [comment]
Screen Recording 2022-06-12 at 12.12.44 PM.mov

**Comment by e9on** [comment]
https://user-images.githubusercontent.com/38707987/173214116-14c11500-8d30-40a7-850e-e855d16a98cd.mov

**Comment by e9on** [comment]
默认的版式，把我认为重要的作者信息和来源隐藏了。所以我要手动调整，并且希望稍后读加载经过调整本地的HTML文件。不知道为什么，就是不加载本地文件？已经按照教程一步一步来了，是遗漏掉了什么选项吗？

**Comment by Kenshin** [comment]
emmm

我看到你的视频了。也就是打开本地 HTML 是没问题的，对吧？但稍后读内加载的就是原文（未优化的？

你的本地文件是否是 `id-title.html` 这样的结构？例如 `1234-xxx.html` ？

知识库配置时需要确保上面这个结构存在。

另外，我看了下如果是读取本地 HTML 的话，除了上面你提到的 icon 外还有下面的标识

![image](https://user-images.githubusercontent.com/81074/173214787-96522ca3-b597-403b-a30c-fac13687d6ac.png)

**Comment by e9on** [comment]
>的本地文件是否是 id-title.html 这样的结构？例如 1234-xxx.html ？
本地的文件结构是title.html.
id并没有自动生成（我的理解是ID是自动生成的，不知道对不对）
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/38707987/173222084-8c10db4f-53e1-493c-baa8-a5431ec450b8.png">

**Comment by e9on** [comment]
`{"version":"2.2.0","option":{"annote":{"autosave":false,"color":1,"effect":"normal","event":"click","exp_mode":"","exp_name":"html","export":false,"hypothes":false,"keyboard":"Q Q","link":"[{{an_text}}]({{an_int_uri}})","off":true,"order":"manual","savelocal":false,"shortcuts":"M M","style":0,"trigger":true},"auto_mode":"read","automated":[{"id":1655017079286,"name":"当保存到稍后读执行","color":"#fff","bgColor":"#195bf7","icon":"<i class=\"fas fa-project-diagram\"></i>","type":"auto","target":"unreader","action":[{"id":1655017079286,"value":"html"},{"id":1655017080859,"value":"pdf","disable":false}]}],"blacklist":["google.com","youtube.com","simp.red","simpread.herokuapp.com","simpread-test.herokuapp.com","simpread.ksria.cn","https://www.oschina.net/"],"br_exit":false,"create":"2022年06月12日 13:36:07","darkmode":"auto","esc":true,"export":{"custom":[],"html":{"layout":"normal","proxy":false,"toc":false},"markdeep":{"custom":false,"template":""},"markdown":{"backlink":"","custom":false,"ext_uri":"","format":"","int_uri":"","single":false,"single_tmp":"","tag":"","tag_sep":"","template":""},"title":{"custom":true,"template":"{{id}}{{un_title}}{{mode}}"},"webhooks":[]},"lazyload":["baidu.com","weibo.com","youtube.com"],"manual":{"mode":"read","select":true,"shortcuts":"S S","site":"confirm"},"menu":{"blacklist":false,"exclusion":false,"focus":true,"lazyload":false,"link":false,"list":true,"manual":true,"option":true,"read":true,"unrdist":true,"whitelist":false},"notice":true,"origins":[],"plugins":[],"preload":true,"remote":{"export":{"attach":"none","epub":true,"kindle":true,"mail":false,"pdf":true,"plain":true},"parse":false,"port":7026,"rss":false,"sync":true},"save_at":"jianguo","secret":false,"shortcuts":"enable","sync":"2022年06月12日 15:24:28","uninstall":true,"unreader":{"autoiframe":false,"bottom":true,"exports":{},"mode":"annote","offline":true,"openmode":"evergreen","sametheme":false,"savelocal":false,"savetype":"ofhtml","search":true,"shortcuts":"D D","show":"senior","sidebar":true,"theme":"default"},"update":"2022年06月12日 15:24:28","urlscheme":true,"version":"2017-04-03"},"focus":{"auto":false,"bgcolor":"rgba( 235, 235, 235, 0.9 )","controlbar":true,"highlight":true,"mask":true,"opacity":90,"shortcuts":"A S","version":"2016-12-29"},"read":{"actionbar":{},"auto":false,"cleanup":true,"controlbar":true,"custom":{"art":{"color":"","fontFamily":"","fontSize":"","fontWeight":"","letterSpacing":"","lineHeight":"","textIndent":"","wordSpacing":""},"code":{"fontFamily":"","fontSize":""},"css":"","desc":{"color":"","fontFamily":"","fontSize":""},"pre":{"textShadow":""},"title":{"color":"","fontFamily":"","fontSize":""}},"exclusion":["v2ex.com","issue.github.com","readme.github.com","question.zhihu.com","douban.com","nationalgeographic.com.cn","tech.163.com","docs.microsoft.com","msdn.microsoft.com","baijia.baidu.com","code.oschina.net","http://www.ifanr.com","http://www.ifanr.com/news","http://www.ifanr.com/app","http://www.ifanr.com/minapp","http://www.ifanr.com/dasheng","http://www.ifanr.com/data","https://www.ifanr.com/app","http://www.ifanr.com/weizhizao","http://www.thepaper.cn","http://www.pingwest.com","http://tech2ipo.com","https://www.waerfa.com/social"],"fap":true,"fap_layout":"list","fontfamily":"default","fontsize":"","highlight":true,"layout":"","lazyimg":true,"progress":false,"pure":true,"shortcuts":"A A","theme":"github","toc":true,"toc_hide":true,"version":"2017-03-16","whitelist":[]},"websites":{"custom":[],"local":[["https://faxin.cn/lib/syyl/syylContent.aspx?gid=D21003",{"name":"faxin.cn","title":"<title>","desc":"[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]","include":"[[`//*[@id='ctl01']/div[3]/div[2]/div[3]/div[2]/div[2]/div[1]`]]","exclude":["[[`/html[1]/div[1]/sr-read[1]/sr-rd-content[1]/span[1]`]]","[[``]]"]}]],"person":[]},"statistics":{"read":2},"user":{"avatar":"","contact":"","email":"","name":"","rule":2,"uid":""},"notice":{"latest":0,"read":[],"unsee":0},"unrdist":[{"url":"https://faxin.cn/lib/syyl/syylContent.aspx?gid=D21003","title":"协议离婚条件的财产分割协议的性质和效力 - 法信 - 懂法，更懂法律人","favicon":"","img":"","desc":"","create":"2022年06月12日 15:24:28","idx":0,"annotations":[],"tags":[],"note":""}],"collections":[],"plugstorge":{}}`

**Comment by Kenshin** [comment]
okay 我确认完告诉你。

**Comment by e9on** [comment]
我找到重现bug（不知道算不算bug）的方式了。就是第一个网页是不生效的，收藏第二个网页才开始按`{{id}}{{un_title}}{{mode}}`自定义标题。

**Comment by Kenshin** [comment]
> 我找到重现bug（不知道算不算bug）的方式了。就是第一个网页是不生效的，收藏第二个网页才开始按`{{id}}{{un_title}}{{mode}}`自定义标题。

哈，竟然是这个问题。 算是已知 Bug ，已经记录在 [问题清单](https://github.com/Kenshin/simpread/discussions/categories/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5) 里面了。

现在应该没问题了吧？

**Comment by e9on** [comment]
终于解决了，因为我一直都是用同一个网页在测试的，谢谢！

**Comment by Kenshin** [comment]
okay 搞定就好。
