### ISSUE TITLE
稍后读开启内置解析后，阅读模式加载不出来

### ISSUE THREAD

**Issue by CASCfans** [Kenshin/simpread#4055]
- 操作系统 Windows 

- 浏览器版本 Chrome 版本 102.0.5005.115（正式版本） （64 位）

- 简悦版本 2.2.0.520

**请描述你的问题**
- 无论是维基百科还是知乎文章，收藏到稍后读里，启用同步助手内置解析。在稍后读的阅读模式都加载不出来，一直显示“小憩片刻，马上就好”（之前自带解析知乎文章有的图片加载不出来，才打开的内置解析）
- 已经是高级账户，且按说明文档一步步操作

![image](https://user-images.githubusercontent.com/51940140/173274782-d733d7c3-83fd-440a-8987-83eda300890f.png)
![image](https://user-images.githubusercontent.com/51940140/173274810-9dbdd8e6-01cd-4a9b-8054-762c79e699cb.png)

![image](https://user-images.githubusercontent.com/51940140/173274675-2a9d445b-f067-4651-85da-c53df223562f.png)
![image](https://user-images.githubusercontent.com/51940140/173274733-eee0881b-546c-4e45-942d-276296e07173.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是一个 Bug，下个版本修复。（未发布的版本已经解决了这个问题，最迟下周发布）

但一般来说使用同步助手的用户都会配置 [知识库](https://kb.simpread.pro/#/page/%E5%BB%BA%E7%AB%8B%E7%9F%A5%E8%AF%86%E5%BA%93)，包括我 😂 所以一直没有发现这个 Bug

**Comment by Kenshin** [comment]
嗨，通过助手升级到 1.1.0 这个 Bug 已经被 Fixed 掉了。

***

关于 1.1.0 的介绍可以 [看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-2982511)。

以下是新功能的简单介绍：

- [稍后读 · 极速版](https://github.com/Kenshin/simpread/discussions/3864)

- [标注嵌入模式](https://github.com/Kenshin/simpread/discussions/4070)

- [URL Scheme](http://ksria.com/simpread/docs/#/Sync?id=urlscheme)

***

以下是基于 1.1.0 版的稍后读 · 极速版在 MenubarX 上的使用效果

https://user-images.githubusercontent.com/81074/174518777-adf0715c-69ec-4203-a800-aa0093b6db92.mp4

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
