### ISSUE TITLE
增强导出EPUB失败，其余功能正常。

### ISSUE THREAD

**Issue by kiroroa** [Kenshin/simpread#4056]
- 操作系统  Windows 10

- 浏览器版本 Microsoft Edge 102.0.1245.39 (正式版本) (64 位)

- 简悦版本 2.2.0.520

- 简悦同步助手版本 1.0.2

- 发生问题的地址 <浏览器阅读模式下增强导出EPUB失败>

**1. 同步助手配置**
![SharedScreenshot](https://user-images.githubusercontent.com/107384888/173288600-06d7f041-4908-4369-a12d-253b815e9b37.jpg)
![SharedScreenshot1](https://user-images.githubusercontent.com/107384888/173288608-26e30066-b971-4794-b59d-05803a746b53.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/107384888/173288612-a527f89c-6d51-4588-8743-455e237120ce.jpg)

**2.浏览器插件配置**
![SharedScreenshot4](https://user-images.githubusercontent.com/107384888/173288648-f0388202-aa41-4acc-b7dc-7a9f81248213.jpg)

**3.pandox**
![SharedScreenshot5](https://user-images.githubusercontent.com/107384888/173288689-993f274f-ea45-4768-914a-c9e5c1dcbf1d.jpg)

**4.阅读模式下导出EPUB失败**
![SharedScreenshot3](https://user-images.githubusercontent.com/107384888/173288739-6c2397a6-888e-4654-902f-235bc67ce59f.jpg)

**Comment by Kenshin** [comment]
嗨，请告知具体 URL。

我随便找了个页面测试 https://sspai.com/post/73698 是没问题的。

**Comment by Kenshin** [comment]
嗨，我发现问题了，预计下个版本修复，尽量在本周发布，最迟下周。

**Comment by kiroroa** [comment]
好的谢谢！辛苦了。
刚想回复您给的这个链接也转化不了epub，但是单独在cmd面板上调用pandoc是可行的。
![test](https://user-images.githubusercontent.com/107384888/173306581-15a0bf54-4cc7-43ac-889e-712910bb962d.png)

**Comment by Kenshin** [comment]
嗨，这个 Bug 已经 Fixed 掉了。（当然暂时还没有发布

**Comment by Kenshin** [comment]
嗨，通过助手升级到 1.1.0 这个 Bug 已经被 Fixed 掉了。

***

关于 1.1.0 的介绍可以 [看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-2982511)。

以下是新功能的简单介绍：

- [稍后读 · 极速版](https://github.com/Kenshin/simpread/discussions/3864)

- [标注嵌入模式](https://github.com/Kenshin/simpread/discussions/4070)

- [URL Scheme](http://ksria.com/simpread/docs/#/Sync?id=urlscheme)

***

以下是基于 1.1.0 版的稍后读 · 极速版在 MenubarX 上的使用效果

https://user-images.githubusercontent.com/81074/174518777-adf0715c-69ec-4203-a800-aa0093b6db92.mp4
