### ISSUE TITLE
能否去掉"本文由 简悦 SimpRead 转码，原文地址"这一栏

### ISSUE THREAD

**Issue by Zacharry** [Kenshin/simpread#4063]
我知道这么好的拓展插件，值得宣传，如果没有购买高级版服务的，理应加上这个水印，但是对于我们付费的用户而言（就算你再贵点也行也能接受），这个体验实在是太糟糕了，我希望可以有一个插件或者新版本可以去掉这个水印，另外新版本什么时候发布呢，已经很久很久没有更新了喔

**Comment by Kenshin** [comment]
嗨，会考虑的。

至于更新的疑问可以看下图

![image](https://user-images.githubusercontent.com/81074/173972247-417b53e8-cde9-4805-9abe-7955da451e7b.png)

简单的说，简悦每周都有更新，比如本周更新了同步助手。

**Comment by Kenshin** [comment]
补充一点：上面截图对应的内容来自 [更新日志](https://simpread.pro/changelog.html) 内含订阅链接。
