### ISSUE TITLE
Latex 加载不出来（个例，仅限此站）

### ISSUE THREAD

**Issue by Ye2222** [Kenshin/simpread#4064]
版本：Edge 2.2.0
URL：https://jackwish.net/blog/2019/gemm-optimization.html
![image](https://user-images.githubusercontent.com/78542233/173972007-25542955-c16b-4522-abe9-fe115d7e0850.png)
![image](https://user-images.githubusercontent.com/78542233/173972120-6fc4e689-186e-49a7-97ed-745cba4ce802.png)

**Comment by Ye2222** [comment]
已经关闭了预加载，添加延迟加载列表也试过了

**Comment by Kenshin** [comment]
嗨，确实如此。虽然是 MathJax 但是不知道它加了什么「魔法」在里面... 我后续追踪下这个问题。

PS：不需要关闭预加载。

**Comment by Ye2222** [comment]
将Mathjax渲染换成SVG，然后重新高亮选取高亮区域就可以加载出来
![image](https://user-images.githubusercontent.com/78542233/173974805-f7ba8cfd-05b4-47b6-8b52-306b1ac050dd.png)
![image](https://user-images.githubusercontent.com/78542233/173974826-0bbae1b5-e9be-4da2-bbe1-d53ca9b4c6e1.png)

**Comment by Kenshin** [comment]
Cool~

估计是它的默认设置造成的，MathJax 确实比 Katax 灵活和方便。😂

**Comment by Kenshin** [comment]
这样的话，我关闭这个 issues 了。
