### ISSUE TITLE
为知笔记绑定 bug

### ISSUE THREAD

**Issue by bighaidao** [Kenshin/simpread#4069]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

macos  2.0 

## 1
背景是我基于 docker 搭建了为知笔记本地部署服务。 然后配置绑定，如图
![image](https://user-images.githubusercontent.com/1301460/174234867-9f2cd19a-c648-4c4e-809e-00f68adb14cf.png)

## 2
但是发现一个 bug， 我没法再正常页面导入笔记， 开启chrome 开发者权限，地址变成 http ，而 http 被干掉了。 我好奇为啥我配置的是 https，但是变成 http 了。
![image](https://user-images.githubusercontent.com/1301460/174234986-81abefb9-7b95-42ac-98e9-27fda78afeaf.png)

## 3 
然后我导出配置文件，发现有个host 和kbServer 地址不一样的问题。很奇怪
![image](https://user-images.githubusercontent.com/1301460/174235252-d23ff136-a37b-4597-b8f8-4fc13fc82638.png)

然后我手动改配置文件，导入后 总是提示不是最新，要重新刷一次。。。。  导致整个 wiz 无法用。

麻烦大佬看看，帮忙解决一下。

**Comment by Kenshin** [comment]
> 导入后 总是提示不是最新，要重新刷一次

嗨，这个问题最简单的方式是重启浏览器。（导入手动修改后的配置重启浏览器）

至于你说的问题，我后续确认下。

**Comment by bighaidao** [comment]
> 



> > 导入后 总是提示不是最新，要重新刷一次
> 
> 嗨，这个问题最简单的方式是重启浏览器。（导入手动修改后的配置重启浏览器）
> 
> 至于你说的问题，我后续确认下。

重启不行，还是提示授权已过期。 导致自己修改的配置无法生效。

麻烦看下这个是不是 bug。。。 所有方法都试了

**Comment by Kenshin** [comment]
收到。

**Comment by bighaidao** [comment]
> 



> 收到。

hi, @Kenshin , 本地的配置文件在哪  我可以手动改一下吗？ 我理解改了应该就OK 了。。。

**Comment by Kenshin** [comment]
> 本地的配置文件在哪

emmm 你不是找到了配置文件了吗？选项页 → 共通 → 导出 → 修改 → 导入的方式。

**Comment by bighaidao** [comment]
> 页 → 共通 → 导出 → 修改 → 导入的方式。

不过这种方式导入 会让 simpread 认为不是最新的，然后会重新授权刷新，变成老样子了。。。。

**Comment by bighaidao** [comment]
![image](https://user-images.githubusercontent.com/1301460/174520762-c39236fd-349c-4ef9-baf6-e9548b711b0e.png)

重新适配了下，发现还是不行。 看了chrome 的日志，好像和安全有关

**Comment by Kenshin** [comment]
嗨，为知笔记的问题，请集中到 https://github.com/Kenshin/simpread/issues/2419 
讨论，另外，这是一个解决方案 https://github.com/Kenshin/simpread/issues/2419#issuecomment-1169471712。
