### ISSUE TITLE
“神经现实”网站深色主体适配有误

### ISSUE THREAD

**Issue by heptaspirit** [Kenshin/simpread#407]
[https://neu-reality.com/](url)
该网站文章，使用深色主题时，文章字体颜色依然为黑色，只有高亮为白色。
这使得该网站无法使用深色主题，否则文字难以阅读。

**Comment by Kenshin** [comment]
这个网址并没有被适配，只是自动适应了而已，所以出现了你说的问题。

PS1：感觉这个网站不错，觉得适配它，适配后，我会通知你。
PS2：你可以通过 「自定样式」 解决这个问题。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

现在的效果：

![image](https://user-images.githubusercontent.com/81074/57354336-c75bd800-719d-11e9-8093-63257b3e9711.png)

另外，这个站不错，我已经把它适配了，地址 https://simpread.ksria.cn/sites/details/pFkjQSKxC7
