### ISSUE TITLE
如何卸载chrome插件

### ISSUE THREAD

**Issue by edwards19900128** [Kenshin/simpread#4071]
想重新安装一遍,请问一下如何卸载...找了好久都没能找到卸载的入口
<img width="225" alt="image" src="https://user-images.githubusercontent.com/11594850/174262136-9031e494-16db-4b67-b6da-b5db18e4a4dc.png">

**Comment by Kenshin** [comment]
嗨，你使用的是 UserScript 版，请通过相应的方式删除它。

**Comment by edwards19900128** [comment]
> UserScript

谢谢大佬回答~充值了个会员鼓励一下~下次亿定把信息整理用起来...

**Comment by Kenshin** [comment]
哈哈，「付费」回复思路不错。
