### ISSUE TITLE
同步助手不能绑定

### ISSUE THREAD

**Issue by lenxvp** [Kenshin/simpread#4072]
操作系统：win10   
浏览器Edge 102.0.1245.41 (正式版本) (64 位)    
简悦：2.2.0.520   
简悦助手1.0.2   

看到简悦助手更新到1.0.2就去更新，但更新了之后发现不能绑定同步助手，之前是已经绑定成功的，尝试重置同步助手配置再绑定也是不行，退回1.0.1也不行了，重置了简悦扩展配置和重装扩展的，改同步助手端口号，重启浏览器等试了也还是不行
![Snipaste_2022-06-17_15-48-03](https://user-images.githubusercontent.com/14134959/174261408-16e34b67-b9db-457a-aa9a-d33b42acd25f.png)

![Snipaste_2022-06-17_16-27-51](https://user-images.githubusercontent.com/14134959/174261040-37017c56-4745-4683-92ae-84f9e76a380a.png)
![image](https://user-images.githubusercontent.com/14134959/174262320-dece5891-bb37-4464-a3cd-5a92bc8ccdcd.png)
![image](https://user-images.githubusercontent.com/14134959/174262873-8ad6b1b3-8853-47a5-88f4-c7f1e5ceb60b.png)

**Comment by lenxvp** [comment]
发现升了1.0.2后好像不能退到1.0.1了，是不是又其他的缓存配置文件在？
![image](https://user-images.githubusercontent.com/14134959/174266657-75ef28f3-f59d-424f-97df-7fa99b504bc3.png)
但这界面应该是1.0.1没有错的

**Comment by lenxvp** [comment]
发现后台又打印错误
![image](https://user-images.githubusercontent.com/14134959/174267514-0cda76af-4d96-4f88-a942-bbd034960156.png)
检查了端口占用情况
![image](https://user-images.githubusercontent.com/14134959/174268273-cd2046b0-1dd3-4d29-a201-23f21ce13090.png)
😂

**Comment by lenxvp** [comment]
上一步用1.0.1的，改回1.0.2再试，能检查到端口了：
![image](https://user-images.githubusercontent.com/14134959/174269816-9eb8e7c0-06dd-476b-a66a-fda25c516ce4.png)

扩展控制台报错：
![image](https://user-images.githubusercontent.com/14134959/174269790-9e3bd889-b3ea-4872-a13e-c64cd9da0ff9.png)

**Comment by Kenshin** [comment]
嗨，搞定就好。

不过，虽然支持更改端口号，但不建议这么做了，为了简化操作，简悦的很多功能都是默认 `7026` 端口。

另外，升级同步助手是无感操作，用户无需重新设定，怀疑是否是系统造成的，因为你是第一个告知升级后需要重新配置的。
