### ISSUE TITLE
导出为离线markdown文件，图片没有保存到本地

### ISSUE THREAD

**Issue by fanrongqitiancai** [Kenshin/simpread#4073]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
当我在阅读模式或聚焦模式下点击保存为离线markdown文件，页面的图片没有被保存到本地。在markdown文件的相同目录没有。是需要解锁高级用户么？还是需要设置那里？

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/9015263/174326114-37f78c3a-586e-4d1f-873b-fb19f9c74154.png)
> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，这个功能当然没问题了，建议看下 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920473 的说明。

**Comment by fanrongqitiancai** [comment]
简悦 2.0 版本，安装了 导出 md + assets 格式  插件。但是，阅读模式下，点击动作的 导出 md + assets 格式  不能执行，是需要高级帐号么？

**Comment by Kenshin** [comment]
@fanrongqitiancai 

是的，因为需要通过同步助手。如果是基础账户的话，可以使用**离线 Markdown**
