### ISSUE TITLE
恢复默认快捷键

### ISSUE THREAD

**Issue by huanghuanhuahuh** [Kenshin/simpread#4078]
修改了快捷键后, 忘记了默认快捷键是什么, 请问可以在有快捷键的功能旁增加 "默认快捷键为(**)" 这样的字段吗
不好意思刚刚犯傻了, 在 "帮助手册-辅助功能-快捷键" 找到默认快捷键

**Comment by Kenshin** [comment]
哈哈，小事情，解决就好，我关闭这个 issues 了。😄
