### ISSUE TITLE
关联Notion服务配置page时，建议增加三级页面选择

### ISSUE THREAD

**Issue by backnero** [Kenshin/simpread#4079]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

关联NOTION服务时，默认page无法选择第三级页面，日常notion会在workplace中创建一个父级页面，在此页面下创建多个database page，建议配置时可以选择到第三级或多级；

另外，通过聚焦模式抓取发送失败的情况蛮多，大部分文章正文部分仅显示，本文由简悦转码的提示；

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
嗨

> 关联NOTION服务时，默认page无法选择第三级页面，日常notion会在workplace中创建一个父级页面，在此页面下创建多个database page，建议配置时可以选择到第三级或多级；

你可以随便在二级目录建立一个你需要的 Page，当授权成功后，可随时转移这个 Page  到任意位置。

> 通过聚焦模式抓取发送失败的情况蛮多，大部分文章正文部分仅显示

不建议在聚焦模式下使用此功能，请使用阅读模式。

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
