### ISSUE TITLE
书签： 书签在右侧显示的时候，图标可否显示各个网站的图标?提供一个开关设置是否可行？

### ISSUE THREAD

**Issue by waihoyu** [Kenshin/simpread#408]
书签： 书签在右侧显示的时候，书签的图标都是统一的，如果书签比较多的话，不能够一眼识别出来，希望作者提供相应的设置项，勾选了设置项就启用网站的图标。

**Comment by Kenshin** [comment]
谢谢反馈，可以考虑这个建议~

**Comment by waihoyu** [comment]
> 谢谢反馈，可以考虑这个建议~
> 
> 另外，你发错地方了吧... 这里是 SimpRead repo...
抱歉哈！
