### ISSUE TITLE
能否支持原文基础上直接批注？或进入阅读模式后但排版样式等同原文且支持批注？

### ISSUE THREAD

**Issue by aoxinagzhefixedweights** [Kenshin/simpread#4082]
Kenshin Wang，
您好，非常感谢您开发了2.0版这么好的知识管理工具，感觉“”阅读+笔记“”成系统了，阅读背后的产品设计理念，也从您这里学习到很多知识管理的理念、方法和工具。
有一个点比较困惑，简悦工具，能否支持原文基础上直接批注？或进入阅读模式后但排版样式等同原文且支持批注？有时候，原版排版布局不错，想要快速阅读且标注、加入稍后读，日后再回查、整理，需要这个功能。
我在设置选项中，找了好久，都没有找到能实现上述效果的设置，或者折中曲线的办法。
请大神指导赐教。

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦

> 能否支持原文基础上直接批注

并不支持此方式。

其一，简悦的一些行为都是建立在阅读模式基础上的，包括：插件系统等等，这么做的目的除了是不会干扰原页面外，还有可以通过阅读模式快速形成本地快照，并保证每个页面的视觉都是统一的。

其二，我希望使用标注的场合：具有深度阅读需求，如果用户只对某个页面的某（些）内容感兴趣的话，有很多其它类似工具可以实现。

其三，简悦的标注是为了系统学习，所以才通过阅读模式排除干扰。

**Comment by aoxinagzhefixedweights** [comment]
感谢简悦大神的细致回复。（#4085问题,网络错误没有提交成功，我二次操作所致，歉意）
我临时用“选中文本，快捷键SS进入阅读模式，标注，退出阅读模式“”，算半自动解决了此需求。
这个需求，使用场景倒也不多，主要是做专题阅读时，虽然大多是深度阅读（阅读模式），但偶尔还是会检索下相关碎片化资料，这些资料中，有很启发人的点，虽然很小。但想把他们整合到深度阅读的标注中，关联在一起，组合到稍后读的合辑中形成专题(专辑)，再遇到很小但很有启发意义的点也是整合到专辑中，即”标注不是主要目的，主要目的是知识切片（slice）的整合。
再次感谢大神Kenshen.

**Comment by Kenshin** [comment]
> #4085问题,网络错误没有提交成功，我二次操作所致，歉意

哈哈，小问题而已。😄

> 关于专题阅读

除了你说的合辑方案确实是个不错的解决方案。

>
