### ISSUE TITLE
关于简约同步助手的“打开稍后读”快捷键

### ISSUE THREAD

**Issue by Y1YU** [Kenshin/simpread#4086]
简悦同步助手，打开稍后读的快捷键是 ctrl+shift+N，

但这是一个高频使用的快捷键，其他应用也很常使用到。比如windows的新建文件夹，vscode的新建窗口

有修改快捷键或者禁用这个快捷键的方式吗

**Comment by Kenshin** [comment]
可以随时修改快捷键，修改后重启即可生效。

**Comment by Y1YU** [comment]
请问在哪里进行修改呢，在桌面应用好像没找到修改的方式

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/174701044-0077ad0d-110b-49f9-8d2f-63ee48ee1f68.png)

看上图。
