### ISSUE TITLE
已购高级账户，看了文档还是不太懂不太会用，几个疑问详见描述

### ISSUE THREAD

**Issue by riptideT** [Kenshin/simpread#4087]
1、阅读了这篇https://sspai.com/post/72022 （简悦 +Logseq 个人知识库搭建 | 从零开始完全指南），内容大概看懂了，不太明白配置坚果云的作用，就是为了方便通过坚果云同步配置文件吗？如果不安装坚果云，就指定一个本地硬盘目录，如果其他电脑需要使用拷贝配置文件过去使用是不是也可以？
2、高级账户可以最多绑定三个设备，如果有10个设备，可不可以在10个设备之间来回的切换解绑和绑定？
3、使用免费版+同步助手，有关这篇文章里实现的功能https://sspai.com/post/72022 （简悦 +Logseq 个人知识库搭建 | 从零开始完全指南）可不可以实现，大概就是通过简悦阅读和批注，然后导出md到本地logseq目录进行联动？

4、chrome浏览器简悦插件，少数派网站上的文章如果里面内嵌有视频，插件图标就不变红无法使用阅读模式？比如上面提到的这篇就不行https://sspai.com/post/72022 （简悦 +Logseq 个人知识库搭建 | 从零开始完全指南）。

望百忙之中给予指教！

**Comment by Kenshin** [comment]
嗨

> 不太明白配置坚果云的作用，就是为了方便通过坚果云同步配置文件吗？

是的

> 如果不安装坚果云，就指定一个本地硬盘目录，如果其他电脑需要使用拷贝配置文件过去使用是不是也可以？

当然。

关于这两个问题的话，可以看下 语雀手册中关于配置文件的简单说明 https://www.yuque.com/kenshin/simpread/ebwu7g 看完你就彻底理解了。

> 高级账户可以最多绑定三个设备，如果有10个设备，可不可以在10个设备之间来回的切换解绑和绑定？

是的，你可以在无数个设备上安装并使用简悦，但高级功能仅能使用三台设备，你可以通过解绑来实现切换不同的设备。

> 使用免费版+同步助手，有关这篇文章里实现的功

不可以，同步助手的使用前提就是高级账户功能。

> 少数派网站上的文章如果里面内嵌有视频，插件图标就不变红无法使用阅读模式

应该可以使用，跟是否有视频无关，你可以重启浏览器并只进入 https://sspai.com/post/72022 看看右上角是否变红？另外，在未变红前，也可以使用快捷键进入阅读模式。

**Comment by riptideT** [comment]
感谢，这下明白了！

简悦图标未变红，也可以使用快捷键AA进入阅读模式，技能已get。

**Comment by Kenshin** [comment]
哈哈，小事情。

虽然它的价格比较便宜，但简悦的功能比较多。建议多翻翻 https://github.com/kenshin/simpread/discussions 里面的各种技巧。

😄

**Comment by riptideT** [comment]
嗯嗯！

**Comment by riptideT** [comment]
已在Chrome应用中心五星好评，不好意思评论晚了，最近比较忙，加之网络及Google账户登录出现了一些问题

**Comment by Kenshin** [comment]
哈哈，没事 🙏

不过确实太久了。😂
