### ISSUE TITLE
为知笔记经常连接失败

### ISSUE THREAD

**Issue by a1751504** [Kenshin/simpread#4088]
系统：synology DSM 7.0.1 ---- docker部署的服务端
为知笔记镜像版本：latest

---
1.同样的参配情况下 经常会连接失败，偶尔能连接成功
2.重启浏览器就需要重新授权，比较麻烦（我还用notion，就没有这个问题）

![X 7N$9ZLTFI`8$){QUZ6FD](https://user-images.githubusercontent.com/31113826/174745566-e0d662cc-714d-4703-b84b-1f0b18578d0c.png)

---
如果需要我提供更多信息，请告知

**Comment by Kenshin** [comment]
emmmm

1. 配置为知笔记后，重启浏览器，确保你的配置 100% 生效不会被覆盖。
2. 看看是否还存在这个问题。

另外，一个有意思的情况 https://github.com/Kenshin/simpread/issues/4069 这个用户也是自建方案，但无论如何都没法成功连上。

要是方便的话，你告诉他你的步骤。

**Comment by Kenshin** [comment]
另外，补充下：为知笔记授权时间的问题不是简悦控制的。

**Comment by bighaidao** [comment]
> 

对，我是用威联通部署的， 通过类似的配置，可以访问通，但是没法导入相关文章。折腾了很久

**Comment by a1751504** [comment]
> > 
> 
> 对，我是用威联通部署的， 通过类似的配置，可以访问通，但是没法导入相关文章。折腾了很久

另外，我今天发现进入简悦的阅读模式后可以使用思源的剪藏插件进行剪藏，虽然会丢失标注和部分css样式，但是在没有适配思源之前，这应该算是最折中的办法了，相信你也是想要完美本地化才进行云端部署的。

给你一点思源对为知优劣势对比：
优点： 
1.轻量化，部署快，秒启动，占用内存差不多是为知的1/10
2.可以将img进行本地化，虽然是awepb格式(相较于为知通过简悦剪藏是保存了html的情况本地化更彻底)
3.思源的开源能看得到未来，为知是该弃用了
4.bug少（用为知客户端一周，已经发现大大小小七八个bug）
缺点：
1.界面不如为知好看
2.多用户为知更好
3. 不确定.sy格式的未来...


另外，还恳求作者大大能适配思源，苦其本地化方案久矣，现在就缺带标注和样式的剪藏了，哈哈
@Kenshin

**Comment by Kenshin** [comment]
@a1751504 

思源也支持私有部署吗？

**Comment by Kenshin** [comment]
如果思源支持私有部署的话，我会考虑的。

PS：思源的收费方式是什么情况？

**Comment by a1751504** [comment]
> 如果思源支持私有部署的话，我会考虑的。
> 
> PS：思源的收费方式是什么情况？

根据我这段时间使用下来，私有部署是没有任何收费的，所有的功能除了额外提供的云端功能和微信推送外和vip没有区别
付费可以提供云来多备份一份，以及云端图床
![image](https://user-images.githubusercontent.com/31113826/174984834-284f7e57-d2c1-4de6-a9ef-00146efece03.png)



既然我已经使用本地部署了，只要将docker文件夹同步一份到自己的云也是一样的，应该没有额外付费的必要（支持作者例外）

**Comment by a1751504** [comment]
另外，没有订阅的话，就无法使用移动端app访问私有部署的数据，只有订阅后通过云端同步才可以。
这对于部署的方式算是个痛点

**Comment by a1751504** [comment]
> > > 
> > 
> > 
> > 对，我是用威联通部署的， 通过类似的配置，可以访问通，但是没法导入相关文章。折腾了很久
> 
> 另外，我今天发现进入简悦的阅读模式后可以使用思源的剪藏插件进行剪藏，虽然会丢失标注和部分css样式，但是在没有适配思源之前，这应该算是最折中的办法了，相信你也是想要完美本地化才进行云端部署的。
> 
> 给你一点思源对为知优劣势对比： 优点： 1.轻量化，部署快，秒启动，占用内存差不多是为知的1/10 2.可以将img进行本地化，虽然是awepb格式(相较于为知通过简悦剪藏是保存了html的情况本地化更彻底) 3.思源的开源能看得到未来，为知是该弃用了 4.bug少（用为知客户端一周，已经发现大大小小七八个bug） 缺点： 1.界面不如为知好看 2.多用户为知更好 3. 不确定.sy格式的未来... 4. 目前好像没法在移动端app里连接私有部署的数据库，只能使用网页访问
> 
> 这是我实在没办法用为知获得舒适的体验才推荐思源，我确实也是转思源了，给为知提建议完全没有任何回应。望后来的大佬高抬贵手。。。
> 
> 另外，还恳求作者大大能适配思源，苦其本地化方案久矣，现在就缺带标注和样式的剪藏了，哈哈 @Kenshin

之前说的是错的，其实就算打开了阅读模式，使用思源剪藏插件的时候读取的并不是阅读模式页面，而是原页面，在此纠正

**Comment by a1751504** [comment]
> > [#4088 (comment)](https://github.com/Kenshin/simpread/issues/4088#issuecomment-1162822804)
> 
> 这么看的话，还是很不错的。
> 
> 我之前没有支持的原因是：思源使用了私有格式，简悦一般不会支持私有格式的方案。
> 
> 所以，关于 `.sy` 具体是什么？有没有了解？

我对 .sy没有了解，但是我觉得可能可以拿思源的剪藏逆向一下
https://github.com/siyuan-note/siyuan-chrome

**Comment by bighaidao** [comment]
> > 对，我是用威联通部署的， 通过类似的配置，可以访问通，但是没法导入相关文章。折腾了很久
> 
> 我现在使用http:// 进行连接
> 
> 我是docker部署后使用群晖内置nginx携带ssl转发并暴露至外网，默认和你一样使用https进行容器访问
> 
> 一点经验：（踩过的坑）
> 
> > 1. 在首次部署时要等待整个项目部署完成，过程中不要去访问应用网页页面。日志差不多增加了6800条，大概花费25分钟（不知道是不是个例，我是8400T+32G内存，按道理不会性能瓶颈）如果中途中断过，又重新启动容器，会导致诸多bug
> 
> > 2.使用admin登陆为知，系统管理里将单点登录关闭（默认是关闭的）
> 
> > 3.不要使用admin账户进行保存，注册一个账户后把允许注册关闭
> 
> 你可以清除cookie后再重启浏览器试试
> 
> 总的来说，这个问题就是为知server的锅。你如果还想了解点啥，可以提问
> 
> @bighaidao

@a1751504    我的问题我提在这个下面。https://github.com/Kenshin/simpread/issues/4069 

可以连接上，但是没法剪切文章同步到为知。 也不知道是不是 server 的锅。 
我后面试试思源， 但是思源 simpread 好像没有接口同步呢？

我现在没法办，只好通过 webdav 的方式，剪切到服务端。

**Comment by a1751504** [comment]
@bighaidao 
我看过你的问题，但是无法精准定位问题所在，极大概率是wiz server的锅。

能用webdav就先用着吧，毕竟就算你能剪藏到为知也是html格式，无法图片本地化

暂时 simpread 还没有思源的剪藏。无法适配思源的话，我的高级账户就白买啦，大概率吃灰了

所以跟我一起催催作者吧，嘿嘿

**Comment by bighaidao** [comment]
> @bighaidao 我看过你的问题，但是无法精准定位问题所在，极大概率是wiz server的锅。
> 
> 能用webdav就先用着吧，毕竟就算你能剪藏到为知也是html格式，无法图片本地化
> 
> 暂时 simpread 还没有思源的剪藏。无法适配思源的话，我的高级账户就白买啦，大概率吃灰了
> 
> 所以跟我一起催催作者吧，嘿嘿

嗯嗯，希望作者能修复下。  我的诉求很简单，有个本地部署的笔记，simpread 可以自动导入。 折腾了都或多或少bug不断。

**Comment by Kenshin** [comment]
> 希望作者能修复下。 我的诉求很简单，有个本地部署的笔记，simpread 可以自动导入。 折腾了都或多或少bug不断。

哈哈

1. 大概率是为知的锅，具体原因我也不知道，这个自建方案也是另外的用户的需求，当时测试时，我用他的账户是没问题的。

2. 按照你的需求，其实 Obsidian 就能满足，使用 https://github.com/Kenshin/simpread/discussions/4047 导入方式，即可将 图片本地化。

3. 思源的话，我会研究下，看看如何支持。

**Comment by bighaidao** [comment]
> > 希望作者能修复下。 我的诉求很简单，有个本地部署的笔记，simpread 可以自动导入。 折腾了都或多或少bug不断。
> 
> 哈哈
> 
> 1. 大概率是为知的锅，具体原因我也不知道，这个自建方案也是另外的用户的需求，当时测试时，我用他的账户是没问题的。
> 2. 按照你的需求，其实 Obsidian 就能满足，使用 [更好的离线 Markdown 方案：以 md + assets 方式导出 #4047](https://github.com/Kenshin/simpread/discussions/4047) 导入方式，即可将 图片本地化。
> 3. 思源的话，我会研究下，看看如何支持。

我是个懒人，本来想要个自动步枪，作者你给了我一个 ak47。。。 又得折腾了。。。

**Comment by Kenshin** [comment]
@bighaidao

我觉得使用 Obsidian 比你的自建方案肯定简单。😂（也就是方案2）

**Comment by a1751504** [comment]
@Kenshin @bighaidao 
但是思源笔记真的太好用了，虽然学习成本也有一些，可也比obsidian轻量化并简单太多了（主要是我不想用obsidian了，有主观因素，所以想着能够适配思源就好了，但是我太菜了，没法提PR）
我对思源不满意的地方就在于表格（主要是表格，而且没有优化的打算）和一些小逻辑的处理
而且平均三四天就有一版更新，真的算是很勤快的了

声明：我真不是托，真是我觉得好。我用过十几款笔记软件了。notion是我觉得最好的，表格就是用了notion的被惯坏了，但无奈不支持本地部署，我就准备需要表格的就放在notion，整个学习体系就都在思源了

下面贴几张图给你们看看吧

思源新手一定要使用集市里的主题，减少了百分之三四十的软件学习成本（主题里包含了很多页内样式适配）
![YMA%`415ASIS~{EI_B~H~`V](https://user-images.githubusercontent.com/31113826/175762764-403a7f64-87ff-4dc5-a20b-d3c864a1e5de.png)

占用50+M内存，多的时候最多也就100+，刚运行13分钟是因为我刚刚又更新了一次（前面说的为知平均在500-800M之间）
![50KAJ)V%2G05GDE DCY3SDY](https://user-images.githubusercontent.com/31113826/175762834-ca7e6e88-25bd-4199-9ea3-29c7ec15c61d.png)

**Comment by bighaidao** [comment]
> 



> @Kenshin @bighaidao 但是思源笔记真的太好用了，虽然学习成本也有一些，可也比obsidian轻量化并简单太多了（主要是我不想用obsidian了，有主观因素，所以想着能够适配思源就好了，但是我太菜了，没法提PR） 我对思源不满意的地方就在于表格（主要是表格，而且没有优化的打算）和一些小逻辑的处理 而且平均三四天就有一版更新，真的算是很勤快的了
> 
> 声明：我真不是托，真是我觉得好。我用过十几款笔记软件了。notion是我觉得最好的，表格就是用了notion的被惯坏了，但无奈不支持本地部署，我就准备需要表格的就放在notion，整个学习体系就都在思源了
> 
> 下面贴几张图给你们看看吧
> 
> 思源新手一定要使用集市里的主题，减少了百分之三四十的软件学习成本（主题里包含了很多页内样式适配） ![YMA%415ASIS~{EI_B~H~V](https://user-images.githubusercontent.com/31113826/175762764-403a7f64-87ff-4dc5-a20b-d3c864a1e5de.png)
> 
> 占用50+M内存，多的时候最多也就100+，刚运行13分钟是因为我刚刚又更新了一次（前面说的为知平均在500-800M之间） ![50KAJ)V%2G05GDE DCY3SDY](https://user-images.githubusercontent.com/31113826/175762834-ca7e6e88-25bd-4199-9ea3-29c7ec15c61d.png)

@a1751504 
思源这个搭建很快，几分钟搞定。确实资源很省，惊喜的是还能够用剪切到服务器。
 但是怎么说呢 有点简约而且简单了。 并且没有客户端可以使用。。

反正没有个完美的方案。。头疼

我在想啊，是否可以请求 @Kenshin ,把稍后读直接在服务端部署。。 这样岂不美哉

**Comment by a1751504** [comment]
> @a1751504 思源这个搭建很快，几分钟搞定。确实资源很省，惊喜的是还能够用剪切到服务器。 但是怎么说呢 有点简约而且简单了。 并且没有客户端可以使用。。
> 
> 反正没有个完美的方案。。头疼
> 
> 我在想啊，是否可以请求 @Kenshin ,把稍后读直接在服务端部署。。 这样岂不美哉

@bighaidao 
确实如你所说，服务器搭建的话不开会员就用不了客户端。。。只能开会员才能借助云端同步到客户端。。。暂时没有计划解决 https://ld246.com/article/1655963319590


我用下来，缺点还有这些：
1.快捷键冲突,。  暂时没有计划解决 https://ld246.com/article/1655963319590
2.小屏设备浏览器打开可能有些难受
3.table用起来难受（和notiopn比较）
4.代码块的增强无法实现   https://ld246.com/article/1656345164406
其他都没啥问题

上面我的问题连成为issue的资格都没有，哈哈
目前我用的设备是ipad + windows，个人觉得没啥割裂感...


 另外，我感觉上面提到的使用思源的剪藏插件来逆向的难度应该不会很大，望@Kenshin  有空了能研究研究 /抱拳
https://github.com/siyuan-note/siyuan-chrome （再贴一次）

**Comment by a1751504** [comment]
现在看来适配思源是很麻烦了。。。
因为思源编辑器的css样式是根据主题进行设置的，毕竟默认的主题不好用，大部分人都是使用了主题的。所以会有样式冲突
而且，思源的编辑器目前来看还是不太好用的。深度使用后完全不像我说的割裂感不强，其实，很强-，-

想要应用阅读模式的css过去的话。。。那么就需要反适配简悦，需要单独注入css。。。这就变得复杂了。（前提是想要将简悦阅读模式的美化效果也剪藏过去）

使用这段时间以来，我觉得至少百分之80是做的很好的，但是就是剩下这部分，在我看来真的很不舒服，而且我的问题都是无法解决，或者没有解决的计划

思源的作者已经很努力了，我由衷敬佩。但是，和我想要的富文本编辑器还有蛮大差距，我会继续 当副软件轻度使用，希望有适配我的想法的那天

关于简悦适配，我不催了

此贴完结。

**Comment by Kenshin** [comment]
@a1751504 

emmm 你提到的「适配思源」是指导入到思源？还是阅读模式适配？

前者的话，需要 API 支持。
后者的话，需要给我一个 URL 我瞧瞧。

**Comment by a1751504** [comment]
> @a1751504
> 
> emmm 你提到的「适配思源」是指导入到思源？还是阅读模式适配？
> 
> 前者的话，需要 API 支持。 后者的话，需要给我一个 URL 我瞧瞧。

@Kenshin 
我指的是导入到思源，并且携带阅读模式自定义的那些样式和标注。但好像无法成功携带进去

https://github.com/siyuan-note/siyuan-chrome/blob/main/popup.js
![image](https://user-images.githubusercontent.com/31113826/177719480-68398444-f97e-4445-ab2e-79f88bbad9eb.png)

**Comment by Kenshin** [comment]
@a1751504 

思源自己的导入可以加样式？给我截个图看看。

**Comment by a1751504** [comment]
> 

以我目前的了解，导入时携带不了样式的。它的样式来源是思源本身的配置。
所以我的意思是简悦的样式导不进去....

**Comment by a1751504** [comment]
@bighaidao 
思源的论坛里有人给了些方法的，但是没细说，你可以去找找，我找不到了。标题应该是`客户端为啥不能用`什么的

我也想用客户端，快捷键确实是难以言说的痛。想想还是不折腾了，也怕同步出错啥的，而且也不够及时

**Comment by a1751504** [comment]
> > 导入时携带不了样式的。它的样式来源是思源本身的配置。 所以我的意思是简悦的样式导不进去....
> 
> 假设能导入的话，这样不就行了吗？你想要导入简悦的样式？

所以我想要的适配就是简悦能新增一个  保存到思源  的服务
然后最好能带样式。

我的理解是，样式可能是能带进去的，但是无法被思源识别。思源只认识并使用自己的样式

**Comment by Kenshin** [comment]
@a1751504 

okay 大致了解你的想法了。

PS：思源自己导入的内容，然后在它那边是带自己的样式？（它的设计思路挺有意思啊，通常的做法是：尽量保留原文的样式，它正好想法 😂

**Comment by a1751504** [comment]
@Kenshin 是的。但也许，它本来就没有想要兼容外部的css吧
主题是可自由编辑的，确实扩展性已经很强了。虽说对没有编程基础的人难度比较大

这是某一个主题中的h3标签的css样式
![image](https://user-images.githubusercontent.com/31113826/177756548-a69d6b08-3f90-491e-b415-b1b4428a06b4.png)

**Comment by Kenshin** [comment]
@a1751504 

ok 我大概了解了。

**Comment by Kenshin** [comment]
![Siyuan](https://github.com/Kenshin/simpread/assets/81074/a8f839b4-90e5-4fbe-8ae9-da73b48c888c)

嗨，各位。

导入到思源笔记的插件已发布。

### 下载地址

https://simpread.ksria.cn/plugins/details/XxuF7bPTbo

### 功能

- 定制思源笔记地址（适用于 Docker 用户）

- 新建笔记本（留空则新建 SimpRead 名称的笔记本）

- 查看并选择任意笔记本
   
- 自定义导入路径

- [思源图库](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- [assets 定制](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025979) 包括：`{{title}}` 与 `{{date}}`

- [将阅读模式的图片转换为思源图床](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- 导入全文到思源笔记

- 快捷键

- [自动化](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025982)

- 在导入前可选择任意笔记本或路径

### 如何安装

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

### 注意事项

如果你使用了 Docker 版，并且域名不是 `localhost` 的话，可能会有问题。


***

我关闭这个 issues 了，但有任何使用疑问均可在 https://github.com/Kenshin/simpread/issues/5555 继续再此讨论。 😄

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
