### ISSUE TITLE
PDF 增强插件开启 wkhtmltopdf 后 LaTeX 应缩放至与正文成比例

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#4090]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Chrome 102.0.5005.115**

- 简悦版本 **2.2.0**

**请描述你的问题**

- PDF 增强插件导出的 PDF 中 LaTeX 字体很小

**截图**

![image](https://user-images.githubusercontent.com/88515612/174837756-601938a4-4803-4ff4-aab5-f063a23d64b9.png)
![image](https://user-images.githubusercontent.com/88515612/174837953-326b77c4-d0cc-46c4-b251-cf9a33b2ffda.png)

**Comment by Kenshin** [comment]
嗨，需要给出 URL 我才能判断。

**Comment by abd-liac** [comment]
(因为我这里的情况是全局可复现的, 就没有提供 URL)
[例子](https://zhuanlan.zhihu.com/p/156881503)
PDF 增强插件开启 wkhtmltopdf, 选项全默认
看起来是 latex.img (CSS selector) 不会随着字体大小 scale, 所以导致了不协调.

**Comment by Kenshin** [comment]
试试安装 https://github.com/Kenshin/simpread/discussions/2861

发布这个功能中有个例子就是知乎公式的。

**Comment by abd-liac** [comment]
已安装, 结果一致

**Comment by Kenshin** [comment]
[高考前最后3分，爱要不要！.pdf](https://github.com/Kenshin/simpread/files/8972293/3.pdf)

这是我导出的 PDF

**Comment by abd-liac** [comment]
[高考前最后3分，爱要不要！.pdf](https://github.com/Kenshin/simpread/files/8977343/3.pdf)
这是我清空配置后的结果, 有什么可以 debug 的方向吗

**Comment by Kenshin** [comment]
建议看下 https://github.com/Kenshin/simpread/issues/4104 里面的对话，跟你类似的问题，看看有没有什么能帮到你的 。

**Comment by abd-liac** [comment]
结果一致, 虚拟机新环境一样复现;
能麻烦重置配置导出试试吗, 问题应该是存在的

**Comment by Kenshin** [comment]
@abd-liac 

1. 安装 https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ
2. 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

肯定是没问题的，简悦用户使用知乎的人数也不少，有问题的话，不会仅报告一例。

建议在不使用自动同步的前提下安装这两个插件，然后再测试。

**Comment by freshchild** [comment]
@abd-liac 

导出的全局自定义样式加一段：

```css
sr-rd-content .latex{
    /* 看你情况 */
    height: 18px;
}
```

会不会好点？
