### ISSUE TITLE
简悦同步助手启动报错，然后window蓝屏~

### ISSUE THREAD

**Issue by HuangJiaxin8** [Kenshin/simpread#4095]
![image](https://user-images.githubusercontent.com/51071489/174973758-df218c1d-d5ca-488c-bb9b-8feca765ce06.png)
同步助手1.02和1.10版本报错。如图所示。

然后window10蓝屏，错误代码：KERNEL_MODE_HEAP_CORRUPTION

**Comment by Kenshin** [comment]
emmm

你这个问题是解压缩到临时目录造成的，如果使用了 1.1.0 版是没有这个问题的。

确定使用了此版本吗？

**Comment by HuangJiaxin8** [comment]
我一开始使用的是1.0.1版本，今天打开，发现让我更新到1.1.0，一更新，不一会二就蓝屏了。然后试试1.0.2版本，还是不一会而就蓝屏了。然后下载回1.0.1，打开后，还是显示当前版本为1.0.2，一分钟内后还是蓝屏。重启电脑后，下载1.0.0版本，打开软件还是1.0.0，继续蓝屏。接着打开电脑，打开软件，界面还是显示为1.0.2版本，快速点击重置配置，重启软件后终于显示为1.0.0.目前运行正常了，不敢更新1.0.2版本以上的了。  ps：我是在onedrive下载。
![image](https://user-images.githubusercontent.com/51071489/174997946-8381d000-0c44-4629-be96-b534d8b68f87.png)

**Comment by Kenshin** [comment]
简悦的不同版本共享一套数据方案，所以当使用旧版本时，确实需要通过 **重置当前配置** 修改为当前运行版本的配置环境。

但这个错误确实太奇怪了，因为确实有 AMD 显卡导致蓝屏的问题，但都通过 1.1.0 版本彻底解决了。😂 

根据 Windows 的错误日志分析，其实蓝屏跟简悦也没有直接关系，至少崩溃日志没有报告过同步助手的问题。

如果你只是使用 1.0 的功能就先这样吧，我先关闭这个 issues 后续追踪下，等再新的版本时我再联系你测试。
