### ISSUE TITLE
阅读模式下部分代码块不显示，开启代码高亮后显示，但代码块与其他段落顺序错位

### ISSUE THREAD

**Issue by Darkluna999** [Kenshin/simpread#4098]
阅读模式下部分代码块不显示，开启代码高亮后显示，但代码块与其他段落顺序错位

* [源页面](https://mp.weixin.qq.com/s/wvmJNx_tD1NnMNns_2FFaQ)
![image](https://user-images.githubusercontent.com/53258301/175057316-459c9b8f-c984-4015-a84c-0f2679bff1fa.png)

* 未开启代码高亮
    * 多行代码块显示为空白
    ![image](https://user-images.githubusercontent.com/53258301/175057466-2a9e66f7-13ab-413b-9a3f-fe0ca6adf050.png)    
    * 尾端多行代码块引其后无文本，之前插入了无序列表
    ![image](https://user-images.githubusercontent.com/53258301/175058275-1f1cdd15-ef7e-44e8-a748-baf767ecdcc1.png)

* 开启代码高亮
    * 所有代码块提前了一段，上述两种问题得以修复
    ![image](https://user-images.githubusercontent.com/53258301/175057209-46ff7fd6-9632-456c-b9a3-acc3653bf681.png)

**Comment by Kenshin** [comment]
@Darkluna999 

嗨，#500 是代码高亮的集中汇总，因为每条信息都会发送 Email，所以为了防止打扰其他用户，我关闭了编辑的权限。

我会把代码段的问题集中在 #500 

并关闭此 Issues 修复后会通知你~
