### ISSUE TITLE
可否考虑在字体选项中增加宋体

### ISSUE THREAD

**Issue by royink** [Kenshin/simpread#41]
如思源宋体。

**Comment by Kenshin** [comment]
可以考虑的。
目前添加的字体大多数本地都会存在的字体。
另外，新版本会上线自定义主题功能，这样能满足更灵活的定制化。

**Comment by Kenshin** [comment]
@royink 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

可以使用 `自定义样式` 来修改正文的字体，此 issues 将关闭~
