### ISSUE TITLE
[功能请求] 本地同步助手新增两个自设快捷键, 打开稍后读极速版, 以及以独立窗口打开稍后读极速版

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4100]
如题.

**Comment by Kenshin** [comment]
OK

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [稍后读快捷键](https://simpread.pro/docs/#/稍后读快捷键)。

<img width="746" alt="image" src="https://user-images.githubusercontent.com/81074/203219897-52414518-4415-4a1d-b8cd-d20ef1d90a17.png">

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
