### ISSUE TITLE
稍后读阅读模式中知乎部分图片无法显示

### ISSUE THREAD

**Issue by freshchild** [Kenshin/simpread#4104]
[示例页面](https://zhuanlan.zhihu.com/p/421089170)：

- 直接访问：
    ![image](https://user-images.githubusercontent.com/31954237/175244653-7bf074b3-ae67-4652-bf6b-2f3fa770083b.png)
- 稍后读阅读：
    ![image](https://user-images.githubusercontent.com/31954237/175245054-75138405-a667-47fb-88ea-21945a72c33e.png)
    （其中图片地址是 `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='336' height='206'></svg>`）

阅读模式下是正常的，Chrome Version 102.0.5005.115

**Comment by freshchild** [comment]
> 嗨，试试 [知识库](https://zhuanlan.zhihu.com/p/532227053) 方式，将知乎保存到本地快照

……快照是指导出至本地的文件吗？如果是的话那么至少在我这里导出 HTML/Markdown（包括离线）结果是一样的：

![image](https://user-images.githubusercontent.com/31954237/175290582-37f6b2d2-8d5d-4891-bac2-a00d509504c5.png)

> 阅读模式下是正常的，Chrome Version 102.0.5005.115

这里搞错了，阅读模式也有相同的问题，只是我之前测试时第一张图正常显示而已。

**Comment by freshchild** [comment]
> 试试安装 #2861

![image](https://user-images.githubusercontent.com/31954237/175300585-d51eed41-a75a-4a81-b7a6-09fd9bdbdac0.png)

**Comment by freshchild** [comment]
似乎没用？

**Comment by freshchild** [comment]
> 试试安装 #2861

![image](https://user-images.githubusercontent.com/31954237/175300585-d51eed41-a75a-4a81-b7a6-09fd9bdbdac0.png)

似乎没用？

**Comment by Kenshin** [comment]
看看插件触发器有没有相关选项，如果没有，先关闭自动同步，安装并设置后再开启自动同步并覆盖本地。

**Comment by Kenshin** [comment]
[SSD可靠性指标MTTF、MTBF、AFR解析.pdf](https://github.com/Kenshin/simpread/files/8972291/SSD.MTTF.MTBF.AFR.pdf)

这是我导出的 PDF

**Comment by freshchild** [comment]
> 看看插件触发器有没有相关选项，如果没有，先关闭自动同步，安装并设置后再开启自动同步并覆盖本地。

确认是这个问题，现已解决，谢谢。

另外多插一句，未启用 “预先解析采用惰性加载的图片” 似乎会出现相似的症状，不过和该 issue 无关就是。

**Comment by Kenshin** [comment]
搞定就好

> 未启用 “预先解析采用惰性加载的图片” 似乎会出现相似的症状，不过和该 issue 无关就是。

应该是无关的，知乎的公式图片比较特殊，所以需要特殊的插件来专门处理这个事情。
