### ISSUE TITLE
1. twitter 主动适配阅读模式 不能显示帖子 ，有些显示红色图标的页面并不完整支持

### ISSUE THREAD

**Issue by ghost** [Kenshin/simpread#411]
>## -2. 建议在 <chrome-extension://> 进入阅读模式， 这样就不会和 surfingkeys 快捷键起冲突 ！

**Comment by Kenshin** [comment]
1. `twitter 主动适配阅读模式 不能显示帖子`
请启动 `黑名单/排除列表` 机制，twitter 不需要使用 阅读模式。

2. `与 surfingkeys`
你想表达什么？详细描述。
进入阅读模式后，会出现与其它一些扩展出现冲突的情况，目前没有太好的解决办法。
建议使用 `生成临时页面` 。 ☺

**Comment by iwanfu** [comment]
@Kenshin 

阅读模式使用  <chrome-extension://>开头的网站

## 与 surfingkeys 的 Markdown语法是什么？用的什么 Markdown编辑器？
