### ISSUE TITLE
[bug] 稍后读极速版, 每对本地快照做一次保存, 就额外生成一组导航图标按钮

### ISSUE THREAD

**Issue by XMB-7** [Kenshin/simpread#4112]
如题. 对本地快照做了四次修改和保存, 现在头尾各有5行导航图标按钮. 每次保存退出重进都会多出一组.
![image](https://user-images.githubusercontent.com/65625632/175447213-b32c1c8a-8ff4-478d-95ee-38b35728095d.png)
![image](https://user-images.githubusercontent.com/65625632/175447223-29955a4f-3873-4adb-9cd0-afecb3e18dc9.png)

**Comment by Kenshin** [comment]
emmm 应该没有问题，因为有关于剔除这些内容的代码。

你可以测试下：从阅读模式或扩展端的稍后读重新生成 HTML，然后再测试。

**Comment by XMB-7** [comment]
就当前这个issue页面, 我先弄成有三份导航按钮的样子, 然后重新生成快照, 可以看到导航栏恢复唯一, 然后按照演示即可看到保存一遍就多一组导航.
https://user-images.githubusercontent.com/65625632/175452295-b4860f25-5254-45d5-bb86-264d15a5037d.mp4

**Comment by Kenshin** [comment]
okay 我一会确认下。

**Comment by Kenshin** [comment]
已确认，下周发布 1.1.1 版修复此问题。

**Comment by XMB-7** [comment]
刚刚发现, 稍后读极速版, 使用live editor, 并不需要手动点击保存, 本地快照就会自动更新(需要刷新一下). 
如此一来这个保存就没必要存在了, 毕竟不点也能自动保存, 而且还会导致无法放弃本次修改, 亦即不存在改了但不将修改保存的情况. 感觉不太合理, 所以不确定这是否也是一个bug, 还是跟设置了自动化有关.

**Comment by Kenshin** [comment]
>  使用live editor, 并不需要手动点击保存, 本地快照就会自动更新.

肯定没有这个功能，看看如何复现它？

**Comment by XMB-7** [comment]
还是当前这个issue页面, 加入稍后读, 导出本地快照, 用浏览器打开本地快照, 再用极速版打开本地快照.
然后你会发现, 当我用后者修改之后, 并没点保存, 切换到前者刷新两下, 前者内容就跟着变了. 
其实感觉这样用起来也挺方便的, 唯一问题就是改后悔了没法撤销, 除非去坚果云恢复历史记录.

https://user-images.githubusercontent.com/65625632/175757550-735dcf9c-743f-480a-8149-db35e1b074a5.mp4

**Comment by Kenshin** [comment]
看到了视频了...

你少说了一个步骤：标注后会自动保存当前 HTML 与标注数据，如果修改完不添加标注的话，当然不会保存了。

**Comment by XMB-7** [comment]
> 如果修改完不添加标注的话，当然不会保存了

但问题是, 添加文字和添加标注, 对用户而言不是一码事么, 不都是对本地快照的修改么. 
所以现在是要细分出来, 添加文字的修改就不进行自动保存, 然后添加标注的修改就进行自动保存, 这样做是有什么特殊意义吗.

**Comment by Kenshin** [comment]
emmm

极速版与扩展端读本地快照是一套逻辑（与代码）

> 比如我在极速版里给ABC中间加了111, 那此时扩展端上是显示不出来我在本地快照上做的这个标注的, 因为在非本地快照的原始页面里不存在A111BC.

极速版修改后，会保存到本地（无论什么方式），扩展端的稍后读读的也是本地快照，当然可以正常显示极速版的改动。

**Comment by XMB-7** [comment]
你说的这个扩展端指的是本地稍后读, 还是网页稍后读啊, 你说的是前者吗, 我想说的是后者.

**Comment by Kenshin** [comment]
> 既然改了本地快照, 就不要跟网页阅读模式做标注互通, 因为这种互通做不到完美复现用户自己的改动.

这个确实，比如原网页的阅读中 → 通过 Live Editor 修改 → 标注的内容，没法正常的显示在原文阅读模式的标注上。

但稍后读内置的阅读模式与极速版它们是可以想通的。

**Comment by Kenshin** [comment]
再引申下，这个也很好理解：

通过 Live Editor 修改后，就不是原（阅读模式正）文了，当然就不好使了。

阅读模式只是用来阅读和浏览的场合。当有深度阅读需要时，就该稍后读（标注）这套逻辑上场了。

**Comment by XMB-7** [comment]
这个我理解, 但我想说的不是这件事. 我又琢磨了一下, 差不多把逻辑给捋明白了.
现在是这样, 没有极速版稍后读之前, 整个标注系统都是以原始页面为核心的, 因为根本就改不了本地快照, 因为本地稍后读就没有集成live editor功能. 而现在有了极速版稍后读之后, 整个标注系统多出来一个中心, 那就是本地快照, 你在本地快照上的修改无法完美呈现在原始页面上(包括本地稍后读但没开启优先加载本地快照), 这就导致两个核心无法百分百打通, 出现了笔记割裂现象.
比如有一篇全新的文章, 没有做过任何标注, 现在我给它加入阅读列表, 然后导出本地快照.
接着我用极速版打开本地快照, 对ABC做了标注, 此时在网页阅读模式里, ABC也会同步显示出标注. -- (1)
然后我觉得ABC写得不好, 我又用live editor给改成A111BC, 此时极速版里对A111BC的标注显示没有问题, 但网页阅读模式里面原有的ABC标注没变. --(2)
所以我的意思是, 既然已经对本地快照做了修改, 那么这个修改就不要再跟原始页面同步了, 既然无法百分百打通, 那就索性别打通了. 就有点类似于, 你对一个文件做了副本, 然后副本上的所有修改跟原文件一点关系都没有, 如果在副本上的修改也能部分地反应到原文件上, 那还要副本干嘛. 
对于此例, 在本地快照里对ABC做标注, 此时(1)处如果是网页阅读模式里面干脆就没有对ABC的标注, 那么自然也就不会出现(2)处的问题了. 亦即无论我在本地快照里做什么标注, 打开网页阅读模式, 里面都应该一个标注也没有. 本地快照是本地快照, 原始页面是原始页面, 二者的标注相互独立, 不要做任何的互通. 
用户想看自己高度定值的笔记(包括文字修改与基于文字修改之上的标注), 就直接去稍后读极速版或者本地稍后读(打开优先加载本地快照), 而打开原始页面就应该是一篇空白, 而不应该是对自己本地快照的笔记的残缺复现. 因为这种残缺复现没有意义.
我觉得这套业务逻辑或许更好一些, 不知道说明白没有.

**Comment by Kenshin** [comment]
嗨，通过助手升级到 1.1.1 这个 Bug 已经被 Fixed 掉了。

***

关于 1.1.1 的介绍可以 [看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-3028669)。

## 新增 💄 

### [Logseq SimpRead Sync](https://github.com/Kenshin/simpread/discussions/4117)

![Logseq Sync@bigger](https://user-images.githubusercontent.com/81074/175864374-746239ba-263b-4983-8130-a16dabaae653.png)

将简悦的标注与稍后读集成到 Logseq 进而实现：**集文章标注实时同步到 Logseq、本地快照实时保存到本地、管理你全部的稍后读于一身的 Logseq + 简悦全流程化一站式解决方案**。

https://user-images.githubusercontent.com/81074/175864600-3a67f269-8118-4e54-a853-a9928ba80044.mp4
