### ISSUE TITLE
进入阅读模式使用sr进入快捷键后，每个功能都会执行三次

### ISSUE THREAD

**Issue by kiroroa** [Kenshin/simpread#4116]
_**环境**_
- 操作系统 Win10

- 浏览器版本 Microsoft Edge102.0.1245.44 (正式版本) (64 位)

- 简悦版本 2.2.0

- 同步助手 1.1.0

_**问题描述**_

1.  在阅读模式下按下sr进入快捷键时，使用常用功能如`ma`（发送邮件）时，邮件会收到三封来自简悦的邮件，如下图
![三个邮件](https://user-images.githubusercontent.com/107384888/175752565-0a5fee48-fc23-41c7-9f57-56f26e15476a.png)

2.同样，按下`ep`（保存为epub）时，屏幕会出现三次保存成功，如下图
![sr三个截图](https://user-images.githubusercontent.com/107384888/175752615-a1b08b7b-0ede-416d-b7be-fe2ea06bc170.png)

3.按下`kd`（发送到kindle），kindle会收到三个文档， 
![5d208c5e8e2c923c6b03f9ff990ccb8](https://user-images.githubusercontent.com/107384888/175752722-e8449cb3-498e-4298-9781-4384bc4a0cb9.jpg)

> 测试链接：https://www.36kr.com/p/1798536241251336

**Comment by Kenshin** [comment]
我测试了下，是没问题的。

是不是退出又进入了阅读模式？另外，试试其它页面，然后下载 HTML 看看能否稳定复现？

**Comment by kiroroa** [comment]
谢谢，刚刚又试了试这个页面和其他网页，没有问题了，估计就是网络有一点抽风。

**Comment by Kenshin** [comment]
okay 没问题就好，我关闭这个 issues 了。
