### ISSUE TITLE
Inline 的公式被单独成行

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#4119]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 简悦版本 **2.2.0**

- 发生问题的地址 [例子](http://lanqi.org/everyday/33188/)

- Inline 的公式被单独成行, **包括阅读模式和 Markdown 导出**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

现状 ![image](https://user-images.githubusercontent.com/88515612/175779867-1f9f4925-402b-40f6-840a-68c8d8d9ddb8.png)
期望 ![image](https://user-images.githubusercontent.com/88515612/175779874-ec04977b-6339-4b31-a21b-fa04f2e16e37.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，目前看确实如此，除非单独适配它。
