### ISSUE TITLE
能否提供了可以添加公式的js，不然类似于cnblog的公式加载不出来

### ISSUE THREAD

**Issue by Kingtwo** [Kenshin/simpread#412]

**Comment by Kenshin** [comment]
例如？说一下具体的 URL

**Comment by Kingtwo** [comment]
等我找到了，我给你反馈

**Comment by Kingtwo** [comment]
类似这个页面：https://www.cnblogs.com/pinard/p/6437495.html
公式被整成这样了：$$J(W,b,a,y) = -y \bullet lna- (1-y) \bullet ln(1 -a)$$
其实只要加载个公式的js，如mathjax就行了

**Comment by Kenshin** [comment]
目前确实无法加载 `mathjax` 我看看能否使用 plugin 的方式解决它。我重新打开这个 issues 了

**Comment by Kenshin** [comment]
嗨，今天研究了下 MathJax 的问题，目前暂时无法用 插件的方式解决，但可以通过以下的方案完美解决：

- 进入阅读模式；
- 右侧控制栏 → 动作 → 设定 → 重新选择高亮

即可解决。

造成的原因是：MathJax 在生成公式时会有个 Delay 而在生成阅读模式时，还未生成公式。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


*** 

比如上述描述的链接，现在可以显示为

![image](https://user-images.githubusercontent.com/81074/57219010-6612f800-7029-11e9-9503-d5a7956b432c.png)
