### ISSUE TITLE
使用SimpRead Unread Sync无法在obsidian自动同步标注

### ISSUE THREAD

**Issue by aurecooo** [Kenshin/simpread#4120]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows**

- 浏览器版本 **Yandex**

- 简悦版本 **2.2.0**

**请描述你的问题**

> 根据https://zhuanlan.zhihu.com/p/531924705 操作在obsidian加入SimpRead Unread Sync插件，在浏览器把文章加入稍后读且标记后，坚果云目录下有生成全文&标注的html和md，但是**打开obsidian却无法在SimpRead文件夹下自动同步文章的标注（重新打开也无），看文件obsidian/SimpRead目录下也没有刚刚标注文章的md文件**

尝试的解决方法：通过 Command Support搜索今日的稍后读打开相应文章，或者手动同步并重启obsidian才会出现相关标注

示例：No.25为刚在稍后读中做上标记的文章

**![image](https://user-images.githubusercontent.com/108189475/175781954-5461122a-b90a-40aa-88e7-3ff1fee7e463.png)**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，是可以通过 SimpRead Unread Sync 导入的，可以看下 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2677707 的说明（教程）

**Comment by aurecooo** [comment]
我已经安装导入Obsidian插件，并使用SimpRead Sync导出，但在我做了标记之后obsidian/SimpRead中仍未出现相关文章

**Comment by Kenshin** [comment]
emmm 更换为 Chrome 浏览器后测试（我不确定是否是这个问题造成的。

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。
