### ISSUE TITLE
除了JSBOX的方法，是否有其他方式，可以在iOS上阅读使用稍后读？

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#4121]
除了JSBOX的方法，是否有其他方式，可以在iOS上阅读使用稍后读？

如果不行，请问iOS的APP版本，大概什么时候上线？

**Comment by Kenshin** [comment]
试试 [阅读列表](https://kb.simpread.pro/#/page/%E9%98%85%E8%AF%BB%E5%88%97%E8%A1%A8)（也就是资料库方案）

**Comment by Kenshin** [comment]
另外，补充下：资料库方案也支持 [自建方案](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22self+built%22)
