### ISSUE TITLE
新电脑如何迁移旧电脑的稍后读内容

### ISSUE THREAD

**Issue by FanDannn** [Kenshin/simpread#4123]
您好，从mac转移至windows11，简悦高级账户配置文件已顺利同步，但新电脑稍后读是空白的。请问如何转移旧电脑的稍后读内容？有手动迁移方案或云同步方案吗？谢谢！

**Comment by Kenshin** [comment]
1. 配置文件包含稍后读数据。

最简单的做法：
1. 旧电脑 → 选项页 → 共通 → 导出配置文件
2. 新电脑 → 选项页 → 共通 → 导入配置文件

即可。
