### ISSUE TITLE
Markdown模板辅助增强预览不出来，也没起到效果

### ISSUE THREAD

**Issue by Ye2222** [Kenshin/simpread#4126]
按照教程配置Ob+Markdown导出
![image](https://user-images.githubusercontent.com/78542233/175805242-97ea6cdb-d7f8-48bd-8f98-3eaac659770f.png)
![image](https://user-images.githubusercontent.com/78542233/175805322-6a14a506-aa0f-46b2-b818-236c20d9f76a.png)

预览不出来，导出这里没起到效果
![image](https://user-images.githubusercontent.com/78542233/175805302-6b4596ad-15e8-49dd-9f0e-f457828a5b24.png)

**Comment by Kenshin** [comment]
在存在标注时，选择「测试」然后右侧应该是有内容才是正确的，否则就是设置错误。

使用 F12 然后点击「测试」，看看有什么报错？

另外，暂时不要使用 md + assest 的方式。

**Comment by Ye2222** [comment]
设置出现了点错误，已经搞定了，麻烦你了

**Comment by Kenshin** [comment]
没问题就好。
