### ISSUE TITLE
进入阅读模式后，文章中部分图片缺失，不显示。

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#4127]
如题，进入阅读模式后，以下图片便没有显示，请问如何解决？
![image](https://user-images.githubusercontent.com/82427022/175807401-e943c93c-0439-43b7-907f-eb97775a853d.png)

原地址：https://www.niaogebiji.com/article-33614-1.html

**Comment by Kenshin** [comment]
嗨，使用手动方式，看下图。更多方式可以看这里 https://github.com/Kenshin/simpread/discussions/3340

![image](https://user-images.githubusercontent.com/81074/175809501-b827b217-8e82-4e6b-91fa-323ba0660f64.png)
