### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by mengqingmeng** [Kenshin/simpread#413]
http://colah.github.io/posts/2015-08-Understanding-LSTMs/
这个网站使用阅读模式后，图片不显示

**Comment by Kenshin** [comment]
这个站没有别适配，同时 `智能识别` 出现问题造成的。
你可以自行适配这个站，或者等我有时间来适配下。 😀

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

解决了图片无法显示的问题，同时，你可以使用重新高亮的方式来生成阅读模式。

**Comment by Kenshin** [comment]
嗨，这个站的适配规则已经更新，请使用下图的方式手动更新，位置在 选项页 → 站点管理

![image](https://user-images.githubusercontent.com/81074/120067368-c8763f80-c0ad-11eb-8706-3b0e6798641d.png)

除此之外，还需要将 `colah.github.io` 加入到排除列表，详情请看 https://github.com/Kenshin/simpread/pull/2237

我关闭这个 issues 了。

***

PS：这是一个创建于 18年的老 Issues，我都不舍得关它  😅

**Comment by Kenshin** [comment]
嗨，更正下，`colah.github.io` 在第三方适配源中，如何使用 [请看这里](https://github.com/Kenshin/simpread/discussions/2287)
