### ISSUE TITLE
知乎公式 Height 过高

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#4131]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 简悦版本 **2.2.0**

- 发生问题的地址 [example](https://zhuanlan.zhihu.com/p/120039061)

知乎公式 Height 过高
从[这里](https://github.com/Kenshin/simpread/issues/4089#issuecomment-1166263264)拆分的, height 看起来不是 css 控制的, 不知道为什么产生了不一致的行为

![image](https://user-images.githubusercontent.com/88515612/175819964-2f223e51-94c2-40a5-8e2f-2c8e23974b7c.png)

**Comment by Kenshin** [comment]
请问这个截图是进入阅读模式后就这样吗？试试更换主题看看能否解决？

我在 https://github.com/Kenshin/simpread/issues/4089#issuecomment-1166427825 已经回复你了。

另外，感觉并不需要新建个 Issues 还是回到 https://github.com/Kenshin/simpread/issues/4089 讨论比较好。

我先关闭这个 Issues 吧。
