### ISSUE TITLE
在开启自动同步后，加载本地文件会出现错误的提示

### ISSUE THREAD

**Issue by leicancun** [Kenshin/simpread#4132]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows **

- 浏览器版本 **e.g. Chrome 103.0.5060.53 **

- 简悦版本 **2.2.0**

**请描述你的问题**

在已开启同步助手的情况下，使用阅读打开本地文件时只要更换主题色或者修改字体大小之类的改变样式的操作，就会弹出同步助手未运行的提示，在其他在线网页上运行时并不会弹出同步助手提示，已确认不是#1567，

还有一个小问题，经常出现图标丢失或者显示为小方块的情况，具体为自动化的图标和插件的图标

最后！！！催更！！！

**截图**

![image](https://user-images.githubusercontent.com/58691431/175820856-205aa63e-92d6-4b37-b010-b55794d8768a.png)

![image](https://user-images.githubusercontent.com/58691431/175820865-a80647c7-09b5-437e-95f3-a4a5523dec0c.png)

![image](https://user-images.githubusercontent.com/58691431/175821024-10d052cd-62f9-4164-8456-cde9109ef58f.png)

![image](https://user-images.githubusercontent.com/58691431/175821148-85476f9f-1ca8-4b17-ae2d-dccbf2367773.png)

![image](https://user-images.githubusercontent.com/58691431/175821151-716593f4-b751-4acb-8871-4df54c7e0800.png)

**Comment by Kenshin** [comment]
> 经常出现图标丢失或者显示为小方块的情况，具体为自动化的图标和插件的图标

这些图标使用了第三方的 URL ，某些网站屏蔽了这些 URL 导致的，比如微信公众号就有这个「毛病」。

> 使用阅读打开本地文件时只要更换主题色或者修改字体大小之类的改变样式的操作，就会弹出同步助手未运行的提示，在其他在线网页上运行时并不会弹出同步助手提示，已确认不是https://github.com/Kenshin/simpread/discussions/1567，

这是个已知 Bug，解决后会通知你，但这不是同步助手的锅。😂

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [稍后读 · 读取外部文件](https://github.com/Kenshin/simpread/discussions/4625)。

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
