### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by Kenneth-liu-github** [Kenshin/simpread#4133]
发生问题的地址: <https://www.dedao.cn/course/article?id=BM30m4na5NkyKQPQDXjvDg7Eowd2GW>
### 问题：无法直接将网页中的「正文+标注」保存到「印象笔记」。需要转码为MD格式。后在印象笔记见导出笔记，但「标准」中的「备注」内容嵌入到正文，无法从格式区分正文和备注。该问题在保存至 OneNote的动作中复现。

*** 
#### 环境：
* MacOS 10.15.17
* Chrome:102.0.5005.115（正式版本） (x86_64)
* 印象笔记：版本 9.5.23 
* OneNote:16.62
* 简悦：2.2.0.520,高级用户。

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~

**Comment by Kenneth-liu-github** [comment]
Thanks, 已经解决了，多谢
