### ISSUE TITLE
突然有个建议~

### ISSUE THREAD

**Issue by CaiJie0611** [Kenshin/simpread#414]
在知乎或其他新闻网页浏览时，我使用最频繁的是聚焦模式，看到一些值得截图存放时，需要另外调出截图软件进行自定义滚动截图（耗时且繁琐），相反，聚焦模式能够一键聚焦主要内容，特别希望能够提供类似一键截图的模式，能够快捷完美截取聚焦模式的内容。不知是否可以实现。
![image](https://user-images.githubusercontent.com/31266850/47713622-b4f46500-dc75-11e8-82c4-be55612f181e.png)

**Comment by Kenshin** [comment]
有这样的功能，侧栏 → 导出 → PNG 即可。

**Comment by CaiJie0611** [comment]
感谢回复，之前聚焦模式下侧边栏是无法浮出选取的，特地试验了下，不知是不是BUG，反馈下。
如下图↓，开启“是否一直显示右下角的侧边栏”后，无法显示选取。
![snipaste_2018-10-31_23-28-19](https://user-images.githubusercontent.com/31266850/47799812-fbc18800-dd65-11e8-8533-d77c533bfa6b.png)
![snipaste_2018-10-31_23-30-04](https://user-images.githubusercontent.com/31266850/47799817-febc7880-dd65-11e8-901a-83c5a059d05a.png)


如下图↓，关闭“是否一直显示右下角的侧边栏”后，可以自动浮出选取。
![snipaste_2018-10-31_23-31-13](https://user-images.githubusercontent.com/31266850/47799853-1693fc80-dd66-11e8-93bb-5740aec0af9c.png)
![snipaste_2018-10-31_23-33-18](https://user-images.githubusercontent.com/31266850/47799858-198eed00-dd66-11e8-857c-5eaa81015dc8.png)

**Comment by Kenshin** [comment]
不算是 Bug 但每个网页的情况不太一样，请告知发生问题的 URL  我确认下~

**Comment by CaiJie0611** [comment]
“是否一直显示右下角的侧边栏”在开启的情况下，我登录了以下网页：
https://www.jiemian.com/article/2586120.html
https://www.bbc.com/zhongwen/simp/world-46052304
https://www.thepaper.cn/newsDetail_forward_2588374
https://mp.weixin.qq.com/s/eyAe5Zcwj5h_H2K6qpY6Og
我再试了诸多网页，情况如我所述，都是光标移到侧栏无法浮出选取，基本没成功的。关闭了所有扩展后在试，也无效。


PS：简悦1.1.2.1025，chrome 70.0.3538.77（正式版本） （64 位）

**Comment by Kenshin** [comment]
再此谢谢调查~

这应该是个 Bug 不过可以用过如下方式解决：

选项页 → 高级设定 → 自定义样式 → 自定义CSS（左下角）填入 ↓

```
.sr-controlbar-bg sr-rd-crlbar fab-bg {
        z-index: 2147483646;
}
```

保存后刷新即可解决~

**Comment by Kenshin** [comment]
嗨，这个问题应该解决了，我关闭此 issue 了~
