### ISSUE TITLE
Logseq SimpRead Sync 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4140]
好吧，我又遇到了问题，
当我在logseq中输入<iframe src="http://localhost:7026/unread?embed=logseq" width="100%" height="500px"/>之后，渲染之后什么都没有出现
当我在浏览器中输入http://localhost:7026/unread/2234??embed=logseq 的时候，弹出的网页中并没有这个设置按钮的选项，这是为什么？
![image](https://user-images.githubusercontent.com/49675185/176168421-0033947e-245c-4c24-92d2-15920ea62e17.png)
弹出的网页中只有一个离线html文件，好像也无法对它做标注
![image](https://user-images.githubusercontent.com/49675185/176168732-d87d459f-ddf6-4584-8095-2312762d9a2f.png)

_Originally posted by @YangWaldon in https://github.com/Kenshin/simpread/discussions/4117#discussioncomment-3039367_

**Comment by Kenshin** [comment]
@YangWaldon

我新建个 Issues 

这个功能需要同步助手 1.1.1 版。

另外 http://localhost:7026/unread/2234??embed=logseq 地址有问题的，正确的是

http://localhost:7026/unread/2234?embed=logseq

**Comment by YangWaldon** [comment]
用的就是111版同步助手，访问正确的地址也是同样的结果

**Comment by Kenshin** [comment]
emmmm

访问 http://localhost:7026/reading/2234 有值吗？

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/176182916-34268743-e72c-440e-9396-c013d9b4fa60.png)
访问 http://localhost:7026/reading/2234 有值吗？  ⇢  得到的是这个页面

**Comment by Kenshin** [comment]
既然能正常访问，应该没问题的…

浏览器访问 http://localhost:7026/unread/2234 是什么？

**Comment by Kenshin** [comment]
访问 http://localhost:7026/unread/2234?embed=logseq

就会在左上角看到这个选项了…

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/176199954-0be9af11-a1f2-4bdb-b5f9-a65ba85fdc29.png)
并没有

**Comment by Kenshin** [comment]
那肯定不是 1.1.1 版的同步助手。

另外，看截图也不太对… 应该有返回剪头

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/176201291-b8d19ade-c4b8-402b-a218-ff514f14d0c2.png)
我没必要骗你啊，你看应用程序的时间

**Comment by Kenshin** [comment]
打开同步助手界面，右下角有版本提示。

我是根据你的截图推测的，跟其它无关。

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/176204614-da08c6cc-b356-404c-8d9a-20285ef3f60a.png)

**Comment by YangWaldon** [comment]
我重启电脑之后，再次访问http://localhost:7026/unread/2234，提示错误
![image](https://user-images.githubusercontent.com/49675185/176207008-9945aac8-45d8-498c-a535-e05ca6ee03d0.png)
但是访问http://localhost:7026/reading/2234是正常的

**Comment by Kenshin** [comment]
第一个错误，刷新下就行了。

你随便加个稍后读，然后生成本地快照。

在访问 http://localhost:7026/unread/xxx 试试

**Comment by YangWaldon** [comment]
这是刷新解决不了的啊，我提交问题之前，肯定是刷新了好几次无果才提交的

**Comment by YangWaldon** [comment]
今早重启计算机，按照上面说的，新加了一个稍后读，访问http://[localhost:7026/unread/2254](http://localhost:7026/unread/2254)，还是提示错误
![image](https://user-images.githubusercontent.com/49675185/176336279-09a43bf6-eb07-4a69-9a06-d6a01230fa8f.png)
此时的简悦是处于运行状态的
![image](https://user-images.githubusercontent.com/49675185/176336342-80bc8364-efb7-44a4-bc82-25afcffc92a6.png)

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/176336897-7bd78478-6a8e-4ccc-bd0a-5ffc3ffb28f9.png)
![image](https://user-images.githubusercontent.com/49675185/176336909-d8ffea9e-9330-47e7-b408-9ffd25dd1ff3.png)

**Comment by Kenshin** [comment]
唉，又是个奇葩问题...

访问 http://localhost:7026/reading/2254 没问题？但是访问 http://localhost:7026/unread/2254 不行？

`output` 肯定有 `2245-xxx` 这个 HTML 吧？把这个文件直接给我。

另外，看下面的截图是不是自动同步关闭了？

![image](https://user-images.githubusercontent.com/81074/176352403-2f41bb2d-3062-4a25-adae-49a3e53f84ce.png)

还有，访问 http://localhost:7026/unread/ 看看是什么内容？

***

如果 http://localhost:7026/unread/2254 正常访问的话，应该有下面的效果

![image](https://user-images.githubusercontent.com/81074/176352530-cff4c0dd-5129-41e9-b96a-4d13ddd32b70.png)

![image](https://user-images.githubusercontent.com/81074/176352572-c800971b-447a-4656-bd65-01f14545c95a.png)

**Comment by YangWaldon** [comment]
这个功能还需要依赖自动同步吗？我的自动同步确实没打开

**Comment by Kenshin** [comment]
好吧，破案了。

需要自动同步。（否则没法读到稍后读的数据...

**Comment by YangWaldon** [comment]
好吧，我的原因，好长时间不用自动同步方案了，因为感觉一开这个选项简悦就变得很慢，各种模式加载都很慢，比如一个选项页加载出来就需要十几秒

**Comment by Kenshin** [comment]
我记得之前告诉过你，自动同步需要通过读写取本地文件（跟浏览器截然不同的方式）

较慢是因为需要确保数据读取成功而设置的方式，跟读取的本地配置文件大小有关系。

**Comment by YangWaldon** [comment]
好的，另外再提一个疑问，我记得之前哪个版本已经说，现在在稍后读中删除条目，对应的离线html也能相应的删除了，但是最近几个版本我都试了，在稍后读中删除条目之后，对应的本地html文件还存在，这是怎么回事儿呀
我就不创建新的issue了，就在这里问一下了
这个功能我是开启了的
![image](https://user-images.githubusercontent.com/49675185/176562598-99a1ae74-aadc-4c33-a63e-f26258178b09.png)
在GitHub上我也只看到这么一个说明，搞不懂是什么意思
![image](https://user-images.githubusercontent.com/49675185/176562660-2e740850-4725-4e6f-8a24-ff9e267341bf.png)

**Comment by YangWaldon** [comment]
还有一个问题，就是生成的md格式的page，会有一些非markdown格式的0的文件，如图所示
![image](https://user-images.githubusercontent.com/49675185/176566672-490d869f-efdd-4beb-ac6b-184a8228c305.png)

**Comment by Kenshin** [comment]
> 我记得之前哪个版本已经说，现在在稍后读中删除条目，对应的离线html也能相应的删除了，但是最近几个版本我都试了，在稍后读中删除条目之后，对应的本地html文件还存在，这是怎么回事儿呀

删除的功能是存在的，但扩展端没有对应的动作，这个功能会放到自动化辅助增强来做，但这几天应该没有时间。

![image](https://user-images.githubusercontent.com/81074/176578926-5d456ce3-adc8-493c-87f0-1efb75fe7b40.png)

截图的功能是这个意思：

1. 你删除了 1234 的稍后读，这时 1234-aaa.html 还在。
2. 你有添加了新的稍后读，它还是 1234 开头的稍后读，但名字应该是  1234-bbb.html
3. 这个功能会自动删除 1234-aaa.html

> https://github.com/Kenshin/simpread/issues/4140#issuecomment-1170599660

用 `alias` 试试

> https://github.com/Kenshin/simpread/issues/4140#issuecomment-1170614545

打开 http://localhost:7026/unread/2208?embed=logseq 按照下图选择 **测试**，看看右侧是否有内容出现？

![image](https://user-images.githubusercontent.com/81074/176579510-e5be5829-35f4-4266-950d-e09d06dc368f.png)

**Comment by Kenshin** [comment]
> 按照这个逻辑来说，则必须是在删除稍后读中最新的条目时，等再添加新的条目的时候，旧的html才会被删除，那我要是删除稍后读中处于中间位置的条目的时候呢？这个中间的条目对应的html如何自动删除？

![image](https://user-images.githubusercontent.com/81074/176809559-dd6c2305-fdf3-49a8-9b58-0e68f5b06611.png)

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
