### ISSUE TITLE
assests插件导出title命名bug

### ISSUE THREAD

**Issue by Darkluna999** [Kenshin/simpread#4142]
url: https://mp.weixin.qq.com/s/ZrcbnX2nC47XupdVsyD-Rw

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/53258301/176358575-5d09f9d0-552b-497a-a9a1-943b76eccada.png)

导致此问题的原因猜测可能是页面标题中的`|`，在win环境下不允许文件名中存在此符号

**Comment by Kenshin** [comment]
试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by Darkluna999** [comment]
经测试。。失败，还是那个报错，似乎修复插件并没有生效

**Comment by Kenshin** [comment]
关闭自动同步后再安装插件。（安装后再启用自动同步并覆盖本地）

**Comment by Darkluna999** [comment]
！成功了，多谢K佬

**Comment by Kenshin** [comment]
哈哈，搞定就好。K 佬... 听着好奇怪 😂

***

来个五星 + 好评 😏😉 吧~

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`

![image](https://user-images.githubusercontent.com/81074/176375591-40d856d7-c86b-4939-b7eb-323506deacaa.png)

**Comment by Kenshin** [comment]
> 我一直跟别人喊你K佬的，没想到吧

没想到 😂 叫 K 大的多些。

谢五星~

**Comment by Darkluna999** [comment]
合并同类项==>K大佬

**Comment by Kenshin** [comment]
🌚  😂
