### ISSUE TITLE
求助，双链配置还是有问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4145]
求助，双链配置还是有问题，配置、功能一步一步来的应该都没错，然后同步助手版本是1.1.1，浏览器用的vivaldi
![image](https://user-images.githubusercontent.com/25861044/176421752-f5675fb0-ee00-4b28-aa45-c2529dd4636c.png)
![image](https://user-images.githubusercontent.com/25861044/176421807-9ce912fd-7ddc-40d8-8729-53bc7ed7375c.png)
![image](https://user-images.githubusercontent.com/25861044/176421851-ddd02047-7c79-4dec-9d86-6c63609d5ae2.png)

_Originally posted by @ethanchengyu in https://github.com/Kenshin/simpread/discussions/3188#discussioncomment-3047608_

**Comment by ethanchengyu** [comment]
问题1:当操作至使用步骤时，出现下图错误，但output已有稍后读文章
<img width="494" alt="image" src="https://user-images.githubusercontent.com/25861044/176424724-bae20cd8-bd71-4a57-a1ee-a6352cc37321.png">
问题2:一站式教材又操作了一遍，目录结构设置如下，还是不行
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/25861044/176425496-7d36c656-ec14-4bb1-9578-4f8ca36783d6.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/25861044/176425652-e720cb9f-5fd8-41ca-bb1b-118ac7b9f2cd.png">

**Comment by Kenshin** [comment]
试试访问 http://localhost:7026/reading/index 看看有没有值？

如果有值的话，则说明配置成功。

**Comment by ethanchengyu** [comment]
> 试试访问 http://localhost:7026/reading/index 看看有没有值？
> 
> 
> 
> 如果有值的话，则说明配置成功。
![image](https://user-images.githubusercontent.com/25861044/176446691-3633c5ef-f906-4397-afb8-6ab3373821f2.jpeg)
这样？

**Comment by Kenshin** [comment]
我知道你的问题了… 你的 output 中没有 HTML 

此功能需要有 HTML 才能访问。

**Comment by ethanchengyu** [comment]
> 我知道你的问题了… 你的 output 中没有 HTML 
> 
> 
> 
> 此功能需要有 HTML 才能访问。

output中有html呀，不知道是不是你说的问题
![image](https://user-images.githubusercontent.com/25861044/176562081-8e1c616c-179c-4edc-b1f4-bd0ea677c9f6.png)

**Comment by Kenshin** [comment]
> output中有html呀，不知道是不是你说的问题

手机上字太小了... 😂

试试访问 http://localhost:7026/reading/47 

另外，最早的截图中有 http://localhost:7026/reading/1600 访问失败，除非你有 `1600-xxx.html` 否则肯定是访问失败

**Comment by ethanchengyu** [comment]
> > output中有html呀，不知道是不是你说的问题
> 
> 手机上字太小了... 😂
> 
> 试试访问 http://localhost:7026/reading/47
> 
> 另外，最早的截图中有 http://localhost:7026/reading/1600 访问失败，除非你有 `1600-xxx.html` 否则肯定是访问失败

可以访问47和有编号的，但是外部链接还是不行。
<img width="822" alt="image" src="https://user-images.githubusercontent.com/25861044/176680716-b19028bc-850c-4fb3-a8dd-7395d405a45d.png">

**Comment by Kenshin** [comment]
那就配置没太大问题，重新对比下 https://www.yuque.com/kenshin/simpread/ieu1w6 资料库的教程。

在隐身模式下登陆阅读列表，看看有没有问题。

注意：坚果云的结构与配置教程一致，且 output 有内容。

**Comment by ethanchengyu** [comment]
真的就没看出来有啥问题，还是不行🧐

**Comment by Kenshin** [comment]
把 uid 发送到 `help#####simpread.pro` 邮箱（注意 `#` → `@`）并注明这个 Issues ID：4145

我明天帮你看下

**Comment by ethanchengyu** [comment]
> 把 uid 发送到 `help#####simpread.pro` 邮箱（注意 `#` → `@`）并注明这个 Issues ID：4145
> 
> 
> 
> 我明天帮你看下
不好意思，邮件发了忘跟你说了，还没处理

**Comment by ethanchengyu** [comment]
你好，请问能帮我看一下吗

**Comment by ethanchengyu** [comment]
> 问题1:当操作至使用步骤时，出现下图错误，但output已有稍后读文章 <img alt="image" width="494" src="https://user-images.githubusercontent.com/25861044/176424724-bae20cd8-bd71-4a57-a1ee-a6352cc37321.png"> 问题2:一站式教材又操作了一遍，目录结构设置如下，还是不行 <img alt="image" width="1179" src="https://user-images.githubusercontent.com/25861044/176425496-7d36c656-ec14-4bb1-9578-4f8ca36783d6.png"> <img alt="image" width="632" src="https://user-images.githubusercontent.com/25861044/176425652-e720cb9f-5fd8-41ca-bb1b-118ac7b9f2cd.png">

你好，这个问题还是一直未解决，能看一下吗？

**Comment by Kenshin** [comment]
抱歉，这之前在休假，然后又被隔离在三亚...

关于你的问题，安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 在**隐身模式下，仅启用简悦的方式** 然后使用 https://sspai.com/post/69972 这个测试地址试试。
