### ISSUE TITLE
显示“不小心调用失败，请不要担心，请重新再试” 的疑问

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#4147]
如题，更新1.1.1版本后，一直显示“不小心调用失败，请不要担心，请重新再试”

**Comment by Sssugus** [comment]
并没有使用任何导出方式，是稍后读中所有文章都无法打开。在另一台1.1.0版本的电脑就可以正常打开。

**Comment by Kenshin** [comment]
emmm 看看 1.1.1 版本的账户哪里有没有值？

![image](https://user-images.githubusercontent.com/81074/176577357-ef273963-eff9-4045-9ef9-bbec6baa9a99.png)

没有的话，需要重新绑定。

**Comment by Kenshin** [comment]
另外，稍后读里面的如何设置的？下图位置

![image](https://user-images.githubusercontent.com/81074/176577471-8412c410-0fbb-4acb-8560-f4ef09229d0d.png)

**Comment by Sssugus** [comment]
已解决，重新配合同步助手后显示正常。

**Comment by Kenshin** [comment]
Cool 搞定就好，我关闭这个 issues 了~
