### ISSUE TITLE
长文章卡顿

### ISSUE THREAD

**Issue by 68813044** [Kenshin/simpread#415]
https://post.smzdm.com/p/659396/
你们会吗？

**Comment by Kenshin** [comment]
有用户也偶尔遇到过这种情况，解决办法是 选项页 → 高级设定 → 阅读模式
去掉 `是否自动生成大纲（目录）？ ` 

我会单独为这种情况出一个插件，到时候会通知你。（请不要关闭此 issues ~

**Comment by 68813044** [comment]
> 有用户也偶尔遇到过这种情况，解决办法是 选项页 → 高级设定 → 阅读模式
> 去掉 `是否自动生成大纲（目录）？ `
> 
> 我会单独为这种情况出一个插件，到时候会通知你。（请不要关闭此 issues ~

谢谢你的回复，关闭了自动生成大纲后，滚轮滑动不会卡顿了，但是手拉滑动条还是会卡顿。

**Comment by Kenshin** [comment]
按照你说的，确实有些，但不明显，不清楚 `色魔张大妈` 用了什么黑魔法...

**Comment by Kenshin** [comment]
嗨，请在试试 smzdm 提的这篇文章卡顿的问题是否存在？

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

解决了此问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
