### ISSUE TITLE
为知笔记无法授权的问题

### ISSUE THREAD

**Issue by llyzot** [Kenshin/simpread#4150]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows**

- 浏览器版本 **e.g. Chrome  103.0.5060.66**

- 简悦版本 **2.2.0**
![image](https://user-images.githubusercontent.com/26666662/176483701-177ee817-75ae-4607-be89-a4f23eef6951.png)

使用的自建服务器docker安装的wiz笔记
按照github上先登入wiz笔记网页版，再授权，也是无法正常授权

![image](https://user-images.githubusercontent.com/26666662/176484122-41d7aacb-0463-45dc-8331-35844066e448.png)

![image](https://user-images.githubusercontent.com/26666662/176484613-387d8716-47ed-4854-b7ad-cec1f228e8bf.png)

**Comment by Kenshin** [comment]
应该可以解决，细节看 https://github.com/Kenshin/simpread/issues/2419 的描述。

另外，也请在上面提到的链接讨论，我关闭这个 issues 了。
