### ISSUE TITLE
关于移动端使用收藏助手收藏知乎回答，在移动端无法在阅读列表中解析的问题。

### ISSUE THREAD

**Issue by lalaniu85** [Kenshin/simpread#4152]
首先，表达一下我的佩服。使用开放平台之后，只要是有网址的页面都可以进行稍后读，我觉得太牛了。而且在我的电子书上使用起来也是毫无压力。可以说是完全替代稍后读app。

但是，我用在知乎移动端的时候，发现一个问题。

下面是我的录屏。使用手机将知乎一个回答添加到收藏助手，可是在移动端的阅读列表一直是解析中。

https://user-images.githubusercontent.com/103034960/176646590-ecc56eca-9ff4-4061-919a-872a93ecacc1.mp4

哪怕过了一会儿，在pc端可以看到稍后读页面，手机端在阅读列表依然无法阅读。不清楚是什么原因。
<img width="1420" alt="截屏2022-06-30 17 43 44" src="https://user-images.githubusercontent.com/103034960/176646378-858e3e8f-44b6-4338-b4cc-6a67396b2745.png">

![WechatIMG136](https://user-images.githubusercontent.com/103034960/176646737-260f984f-f142-4048-8f16-f32129a78a44.jpeg)

补充一点，我尝试用过电脑直接进行稍后读操作，手机端是可以直接看到稍后读内的知乎答案的。

**Comment by Kenshin** [comment]
哈哈，谢谢喜欢简悦。

> 而且在我的电子书上使用起来也是毫无压力。可以说是完全替代稍后读app。

不知道是否方便录屏（在电子书上的使用效果），我瞧瞧？

> 知乎的问题

是这样的，通过 URL 加入的稍后读不是 100% 能解析成功，某些国内的网站会阻止这个事情（你可以理解为：它们误判断简悦为爬虫），所以会出现这个问题。

我先记录下，看看如何能规避（修复）下这个问题。

**Comment by Kenshin** [comment]
补充下：

1. 是否是全部知乎 URL 都有此问题？（猜测应该全部...
2. PC 端在稍后读中，可以通过配置 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的方式保存快照，这个快照肯定会在阅读列表成功查看。

**Comment by lalaniu85** [comment]
我用的是文石leaf。录屏效果：

https://user-images.githubusercontent.com/103034960/176822685-6b1616cc-c8d7-4cf0-ab50-6d031fc28e66.mp4

整体还是相当不错的，虽然电纸书不可避免会慢一点，但是完全不影响效果，而且我是把收藏助手当成一个初筛，在电纸书上浏览过后，标注等还是要到电脑上完成。

**Comment by Kenshin** [comment]
Cool~ 我能转发到其它地方吗？如推或即刻等？

竟然是彩色墨水屏？好评！

> 阅读列表每次都要输密码。我估计是和电纸书内存太小有关

密码是可以被浏览器记录的，但可能文石的浏览器有限制造成的，但你可以使用

`https://simpread.pro/@xxx/reading/?token=xxx` 的方式直接免密码登录。

**Comment by lalaniu85** [comment]
转发没问题，但是并不是彩色墨水屏。实际看的时候还是普通墨水屏，只是录屏出来是彩色的，录屏的软件是内置的。
登陆的话，我用收藏助手一直是免密码的，但是阅读列表不知道为什么总是要密码。所以我怀疑是内存太小。

**Comment by Kenshin** [comment]
> 转发没问题，但是并不是彩色墨水屏。实际看的时候还是普通墨水屏，只是录屏出来是彩色的，录屏的软件是内置的。 登陆的话，我用收藏助手一直是免密码的，但是阅读列表不知道为什么总是要密码。所以我怀疑是内存太小。

我说的嘛...在京东搜了下这个设备，没发现是彩色墨水屏 😂

> 阅读列表不知道为什么总是要密码

把 `https://simpread.pro/@xxx/reading/?token=xxx`  加入 favicon 再试试，应该没问题的。

**Comment by lalaniu85** [comment]
谢谢，ok了

**Comment by Kenshin** [comment]
哈哈，搞定就好，我关闭这个 Issues 了。

PS：你的视频我已转发到推和即刻上面了。（打码打的很及时。 👍 

***

要是喜欢简悦的，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图，请帮忙五星 + 好评 😄

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
