### ISSUE TITLE
导入到ob失败

### ISSUE THREAD

**Issue by zhaosky** [Kenshin/simpread#4153]
![Snipaste_2022-06-30_18-50-30](https://user-images.githubusercontent.com/9800648/176659810-26a57889-d23e-484e-bff3-d50342e8bfbb.png)

**Comment by Kenshin** [comment]
1. 关闭自动同步
2. 安装此插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
3. 开启自动同步并覆盖本地配置文件

即可。

**Comment by zhaosky** [comment]
> 1. 关闭自动同步
> 2. 安装此插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
> 3. 开启自动同步并覆盖本地配置文件
> 
> 即可。


还想问下标注的话只能导出html吗？为什么在导出到obsidian除了全文可以导出，其他有时候提示导出成功，但是没导出文件，有时候提示导出失败。

**Comment by Kenshin** [comment]
> 标注的话只能导出html吗

都可以，看你怎么选。

> 为什么在导出到obsidian除了全文可以导出，其他有时候提示导出成功，但是没导出文件，有时候提示导出失败。

描述的不是很详细，我没法判断。

导入 ob 有很多方案，常用的有两种，建议看下 https://github.com/Kenshin/simpread/discussions/4151 提到的一站式教程，对比下你的配置有什么区别。

**Comment by zhaosky** [comment]
> 导入 ob 有很多方案，常用的有两种，建议看下 #4151 提到的一站式教程，对比下你的配置有什么区别。
感觉教程可以整理下，把失效的去掉，不然折腾了好久，发现截图的配置和现在的页面压根不一样，配置项找又不好找。

**Comment by Kenshin** [comment]
> 感觉教程可以整理下，把失效的去掉，不然折腾了好久，发现截图的配置和现在的页面压根不一样，配置项找又不好找。

没有失效的教程，例如？

**Comment by zhaosky** [comment]
> > 感觉教程可以整理下，把失效的去掉，不然折腾了好久，发现截图的配置和现在的页面压根不一样，配置项找又不好找。
> 
> 没有失效的教程，例如？
![Snipaste_2022-07-01_16-50-24](https://user-images.githubusercontent.com/9800648/176860673-c45f8c90-084b-4aeb-a2f0-df8c5e6360a4.png)

如上图所示，找了半天找不到，其他地方也有这样的，第一次看一脸懵逼。

**Comment by Kenshin** [comment]
> 如上图所示，找了半天找不到，其他地方也有这样的，第一次看一脸懵逼。

1. 这个图确实是旧的
2. 但这个图跟你提到的问题无关

如果想配置 知识库 的话，使用 https://www.yuque.com/kenshin/simpread/wkswh7 比较好。

PS：一个五年的项目了，有些旧版本的内容，但确实忘记更新了，但这些只限文档的说明，一般对于新手来说，直接看教程，而教程都是新的。
