### ISSUE TITLE
导入到obsidian时能否将图片保存在本地或者转换成base64保存在md文件中?

### ISSUE THREAD

**Issue by blog2i2j** [Kenshin/simpread#4154]
各位大佬好, 我想用简悦把网页导入到obsidian中, 已经按照教程配置了两种方案, 均可以完美导入. 但发现任何一种方案对图片只是引用原网址, 请问有没有什么插件可以在导入到obsidian时下载图片保存到本地文件夹, 或者可以像保存离线HTML一样, 直接把图片转成base64编码保存在md文件里?

**Comment by Kenshin** [comment]
必须可以啊！

https://github.com/Kenshin/simpread/discussions/4041

**Comment by blog2i2j** [comment]
good, 谢谢指导, 已经搞定了. 原来隐藏的这么深.
简悦真的好用, 但很多的东西配置起来太复杂了.

**Comment by Kenshin** [comment]
有教程。
灵活就肯定不可能不需要配置。

就像 Obsidian，没有插件的话，就是个 Markdown 编辑器 + 图谱而已，甚至 Markdown 不如其它专门做编辑器的 App。

但有了插件就不同了，插件的话，有些简单，有些也超级复杂。
