### ISSUE TITLE
在标注嵌入模式，有没有遇到过这种在标签中输入后文字后回车添加错误的情况

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4156]
在标注嵌入模式，有没有遇到过这种在标签中输入后文字后回车，添加不了标签的问题。

![SCR-20220630-x34](https://user-images.githubusercontent.com/28049338/176722418-0b5189c0-59bc-4c75-868d-7a96871c4152.png)

_Originally posted by @liangenhao in https://github.com/Kenshin/simpread/issues/4128#issuecomment-1171390242_

**Comment by Kenshin** [comment]
@liangenhao

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

我好像也遇到过，我先 Mark 下这个情况。

**Comment by Kenshin** [comment]
@liangenhao

嗨，[1.1.1702 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-3067829) 已经发布了，修复了此问题。

[下载地址](http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd) 

我关闭这个 Issues 了，有任何问题随时在这里讨论。

**Comment by liangenhao** [comment]
在标注嵌入模式，添加新标签的场景，比如原来已经有两个标签了，此时想新增一个标签，在输入框输入文字 发现写错了，点击删除一个字，会把前一个标签给删除。
