### ISSUE TITLE
遇到的几个问题求解答

### ISSUE THREAD

**Issue by FanDannn** [Kenshin/simpread#4159]
您好，感谢插件作者和官方支持！
问题如下：
1. 使用obsidian42-brat方式安装simpread-obsidian-plugin，每次重启obsidian都需要手动开启simpread-obsidian-plugin，否则命令面板里没有simpread相关操作，请问有让他自动开启的办法吗？
2. obsidian命令面板中输入sr后显示的simpread相关操作，如图：
<img width="477" alt="d2b2170a30e5824f2fd07de51a1b096" src="https://user-images.githubusercontent.com/37014400/176830030-a940a09d-e5d8-4d43-a666-85901ca67f0f.png">
点击“查询本周的稍后读”，跳转至如下页面：
<img width="482" alt="825d80ec59a0a920689ec68b8ddf78b" src="https://user-images.githubusercontent.com/37014400/176830222-00c80341-8a20-4a53-905f-4bbf741c94d5.png">
但是点击其中任何文章都没有反应
3. 在SimpRead文件夹下找到稍后读的md文件，点开任何一个，内部链接无法打开，显示如图：
<img width="663" alt="image" src="https://user-images.githubusercontent.com/37014400/176832481-eb97de7b-bc39-45aa-a6da-85345ad27287.png">
不知道是不是我的操作有问题，我的目标是在obsidian里打开稍后读的文章，做批注。

----

当前电脑系统是windows11，obsidian版本是最新0.14.15，简悦同步助手版本1.1.1

再次感谢！

**Comment by Kenshin** [comment]
@FanDannn

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

谢谢喜欢使用简悦。

> 问题1

按道理不应该啊，我没有遇到过这个问题，也没有用户报告过这个情况。

> 但是点击其中任何文章都没有反应

点击后会创建当前稍后读对应的文献笔记，也就是 1234-xxx@annote.md 但确实没有任何提示信息，你可以收到把某个文件删除，然后再通过此方式，会发现它被创建了。

> 在SimpRead文件夹下找到稍后读的md文件，点开任何一个，内部链接无法打开

内部链接依赖与本地快照，如果你没有本地快照的话，当然显示不了。

这个功能叫做 知识库，你可以看这个 [一站式教程](https://www.yuque.com/kenshin/simpread/wkswh7)

**Comment by Kenshin** [comment]
客气了~

> 问题3

根据我给你的链接就可以配置成功，留意路径设置即可。
