### ISSUE TITLE
Obsidian快速阅读中，Live Editor 开启后仍可以标注

### ISSUE THREAD

**Issue by Plus-xu** [Kenshin/simpread#4164]
开启了进入稍后读默认打开标注系统后，在标注内容上用LE进行网页内容修改，会导致稍后读库崩溃，OB内链接原文失效，所有标记内容消失，网页端进入不了稍后读，显示空白
![image](https://user-images.githubusercontent.com/52371609/176876606-f66c454a-07d9-4d76-9542-a7cd36cf46bd.png)

标注消失，因为无法打开稍后读库，读取不到本地html
![image](https://user-images.githubusercontent.com/52371609/176876829-b7a15f4c-6657-44c3-b7cd-7e793fc68bf8.png)

**Comment by Kenshin** [comment]
嗨，[1.1.1702 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-3067829) 已经发布了，修复了此问题。

注意：是修复了 Live Editor 开启后仍可以使用标注的问题，而不是你提到的另外一个问题。

[下载地址](http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd) 

我关闭这个 Issues 了，有任何问题随时在这里讨论。
