### ISSUE TITLE
vivaldi稍后读快捷方式无法创建问题

### ISSUE THREAD

**Issue by ethanchengyu** [Kenshin/simpread#4166]
- 操作系统 **MacOS**

- 浏览器版本 **vivaldi5.3.2679.61 (Stable channel) (arm64) **

- 简悦助手版本 **1.1.1**

**地址1的稍后读chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html无法创建快捷方式，即无法调用同步助手的快捷方式，如下图**

<img width="692" alt="image" src="https://user-images.githubusercontent.com/25861044/176905410-6e89b722-5fdd-4af6-aaf5-b896218e561f.png">
**地址2的稍后读http://localhost:7026/unread/可以创建快捷方式，如下图**
<img width="462" alt="image" src="https://user-images.githubusercontent.com/25861044/176905834-dfd27732-c919-483c-9d57-da2793626a34.png">

问题是我一般用地址1的稍后读，功能更多一些。

**Comment by Kenshin** [comment]
嗨，我感觉可能是位置建立错了，[正确的方式](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%88%9b%e5%bb%ba%e5%bf%ab%e6%8d%b7%e6%96%b9%e5%bc%8f)

**Comment by ethanchengyu** [comment]
> 嗨，我感觉可能是位置建立错了，[正确的方式](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%88%9b%e5%bb%ba%e5%bf%ab%e6%8d%b7%e6%96%b9%e5%bc%8f)

具体是指什么位置？我就是按照[正确的方式](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%88%9b%e5%bb%ba%e5%bf%ab%e6%8d%b7%e6%96%b9%e5%bc%8f)进行操作的，没有看出来哪里有问题

**Comment by Kenshin** [comment]
我问了下，好像是不能 😂

不过你愿意折腾的话，可以装个 Chrome / Edge 单独做这个事情…

简悦可以做到不同浏览器共享一套数据。

**Comment by ethanchengyu** [comment]
嗯，看了你的工作流我从edge转到vivaldi，觉得挺好用的，然后调用稍后读会再次启动edge程序哈，所以想有没有办法解决呢。看来目前就想这样吧😂

**Comment by Kenshin** [comment]
哈哈，我的工作流是把 vivaldi 当做 Web 应用的 App 常面开着一些常用 Web 

正常使用的话，还是 Chrome
