### ISSUE TITLE
更新同步助手后，可读取列表，但重复弹出“调用失败”提示，无法查看稍后读内容。

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#4167]
更新同步助手后，可读取列表，但重复弹出“调用失败”提示，无法查看稍后读内容。

![Snipaste_2022-07-02_00-07-34](https://user-images.githubusercontent.com/82427022/176931458-f0677521-0bb8-490f-ad80-3ab3f98f55ee.png)
![Snipaste_2022-07-02_00-07-53](https://user-images.githubusercontent.com/82427022/176931477-361752d3-e8c1-4fde-8ec7-be43e006bf83.png)
![Snipaste_2022-07-02_00-08-10](https://user-images.githubusercontent.com/82427022/176931486-7c849336-27c9-47b3-9cf5-eb5995c3be61.png)

**Comment by Kenshin** [comment]
重新绑定你的同步助手。

位置在：选项页 → 共通 → 同步助手
