### ISSUE TITLE
点击导出md+asset到obsidian时同步助手出错

### ISSUE THREAD

**Issue by blog2i2j** [Kenshin/simpread#4168]
![image](https://user-images.githubusercontent.com/10300179/176983611-2d5e6e2e-1b9e-48a9-aa84-d0d0e29f6a20.png)

我是导入这个网页

https://lqktz.github.io/2019/05/26/vdex/

好像我有点明白了, 应该是文件名包含了不可用的"|"引起的.

**Comment by blog2i2j** [comment]
暂时加了一个插件解决了, 但希望简悦能够直接集成这个功能, 这个太常用了. 还要先装插件让人不可思议了.

**Comment by Kenshin** [comment]
> 暂时加了一个插件解决了, 但希望简悦能够直接集成这个功能, 这个太常用了. 还要先装插件让人不可思议了.

对你是常用的，但简悦有很多只是用来阅读模式的用户，他们会觉得奇怪。

**Comment by Kenshin** [comment]
建议看看 https://github.com/Kenshin/simpread/issues/4154#issuecomment-1172822602 的描述。

**Comment by blog2i2j** [comment]
> > 暂时加了一个插件解决了, 但希望简悦能够直接集成这个功能, 这个太常用了. 还要先装插件让人不可思议了.
> 
> 对你是常用的，但简悦有很多只是用来阅读模式的用户，他们会觉得奇怪。

保存成文件的过程中才去除不可使用字符, 其他情况下不变.
当然只是一个建议.

**Comment by Kenshin** [comment]
okay 会考虑你的建议。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
