### ISSUE TITLE
请问，能否加入保存到“为知笔记”的功能

### ISSUE THREAD

**Issue by shurasea** [Kenshin/simpread#417]

**Comment by xcffl** [comment]
API 可以看这里：https://github.com/xcffl/WizWebClipperWE/blob/master/scripts/wiz/WizConstant.js

**Comment by Kenshin** [comment]
emmm 这样的话，我可以研究下 🙏 ~

**Comment by AriaLyy** [comment]
mark下，急需为知笔记的保存

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) 的功能，希望喜欢~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by xcffl** [comment]
> 嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本
> 
> 已增加导出到 [为知笔记](http://ksria.com/simpread/docs/#/%E4%B8%BA%E7%9F%A5%E7%AC%94%E8%AE%B0) 的功能，希望喜欢~
> 
> > 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**
> 
> 本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：
> 
>     1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/%E6%9C%89%E9%81%93%E4%BA%91%E7%AC%94%E8%AE%B0) · [为知笔记](http://ksria.com/simpread/docs/#/%E4%B8%BA%E7%9F%A5%E7%AC%94%E8%AE%B0) · [Notion](http://ksria.com/simpread/docs/#/Notion)
> 
>     2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了
> 
>     3. [截图](http://ksria.com/simpread/docs/#/%E6%88%AA%E5%9B%BE)功能
> 
>     4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/%E7%A6%BB%E7%BA%BFHTML)
> 
>     5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=%E5%AE%9A%E5%88%B6)
> 
>     6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95?id=url%E7%BC%96%E8%BE%91%E5%99%A8)，提供此项功能的效率。
> 
>     7. 升级了词法分析引擎，包括：
> 
> 
>     * 代码段可识别更多类型
> 
>     * 阅读模式可识别特殊结构
> 
>     * 适配站点增加 URL 的正则表达式支持
> 
> 
> 更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html
> 
> 插件方面：
> 
>     * 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看
> 
>     * 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

That's fantastic!
