### ISSUE TITLE
md + assets  导出问题

### ISSUE THREAD

**Issue by Hulkhao** [Kenshin/simpread#4170]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **win10 LTSC**

- 浏览器版本 **Microsoft Edge  版本 103.0.1264.44 (正式版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址：https://www.zhihu.com/question/38568101/answer/2479340380

**阅读模式  手动导出 md + assets 。有成功导出**
**在打开上面页面时，多次尝试导出，仍然导出出错**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**问题截图**

![image](https://user-images.githubusercontent.com/23330380/177021030-c7f3fed6-0d9c-4c13-8ce1-29d5d0fc1b35.png)

![image](https://user-images.githubusercontent.com/23330380/177021037-27baa246-6ff3-4f03-8012-6ab22eec6e64.png)

**另外，《md + assets  》能不能整合到自动化导出里，集成导出呀？昨天配置了一天。**

**Comment by Kenshin** [comment]
嗨，需要安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by Hulkhao** [comment]
安装好这个插件了，浏览器重启过。
是先关闭同步，配置好后同步覆盖浏览器配置的方法。

现在的情况是：浏览器端绿色消息弹框「保存成功」，但系统依旧弹窗报错。
![Snipaste_2022-07-03_12-39-34](https://user-images.githubusercontent.com/23330380/177025029-80815afb-0f24-45d6-a522-e14b8183971b.png)
![Snipaste_2022-07-03_12-39-25](https://user-images.githubusercontent.com/23330380/177025031-cb45e407-8b2a-46fd-8969-66db451c9207.png)

**Comment by Kenshin** [comment]
emmm 把 URL 给我看下。

或者试试其它页面 e.g. https://sspai.com/post/69972 看截图应该是安装成功了，如果安装成功的话，标题会有变化。

**Comment by Hulkhao** [comment]
遇到问题的页面是：https://www.zhihu.com/question/38568101/answer/2479340380

我自己猜测是不是“/”造成的路径问题
我找了个标题带“/”的页面：https://www.zhihu.com/question/398288784
保存下来的文件名是这样的
![image](https://user-images.githubusercontent.com/23330380/177030907-227663e4-a0e8-409b-82e0-adcad65f239a.png)
不过这个页面内容保存是正常的。

再次尝试上面那个页面，依旧报错

**Comment by Kenshin** [comment]
emmm

如果成功安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 标题应该是下面的形式

![image](https://user-images.githubusercontent.com/81074/177034147-d810569a-d82d-42d0-ab3c-036bf10dde00.png)

如果你的不是，就先使用 https://github.com/Kenshin/simpread/discussions/2342 提到的方式安装它。

**Comment by Hulkhao** [comment]
一周没用simpread，今天试了一下，好像正常了😂😂😂

谢谢K大

**Comment by Kenshin** [comment]
哈哈，竟然神奇的好使了，好使就好。😂

请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Hulkhao** [comment]
edge用户飘过，我PC的地址是 edge://extensions/?id=clgdhlhfiocphghdkdbgdlmfaafccfmc 😜

**Comment by Kenshin** [comment]
哈哈，那就去 https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN 😀

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
