### ISSUE TITLE
阅读模式目录显示不完整

### ISSUE THREAD

**Issue by Edge-coordinates** [Kenshin/simpread#4171]
![image](https://user-images.githubusercontent.com/68896486/177021284-f4ba775d-09fb-47e3-a879-dfcbeaa7f167.png)

> [站点URL](https://wizardforcel.gitbooks.io/core-python-2e/content/23.html)

目录只显示前面的一小部分，功能性降低。。。

**Comment by Kenshin** [comment]
嗨，这是没问题的，简悦的阅读模式不是以原文的左侧为基准，而是以正文为基准

![image](https://user-images.githubusercontent.com/81074/177023741-b03f477b-cd17-4811-906d-c61085733b0f.png)

**Comment by Edge-coordinates** [comment]
> 嗨，这是没问题的，简悦的阅读模式不是以原文的左侧为基准，而是以正文为基准
> 
> ![image](https://user-images.githubusercontent.com/81074/177023741-b03f477b-cd17-4811-906d-c61085733b0f.png)

不，我的意思是，例如`20.7.1　Mulitipart 表单提交和文件的上传`，简悦只显示了`20.7.1　Mulitipart 表单提交...`,而且没有任何展开选项，导致我找具体内容很不方便。。。
