### ISSUE TITLE
是否能通过关键字搜索已添加入稍后读的内容？

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#4173]
是否能通过关键字搜索已添加入稍后读的内容？比如我有一个关键词叫“自动出价”，是否可以搜索该关键词，弹出所有包含“自动出价”的文章？

**Comment by Kenshin** [comment]
嗨，当然可以了。

你可以把这个关键字变成标签，或者在备注中描述它，然后通过 [此方式](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80?id=%e6%94%af%e6%8c%81%e5%a4%9a%e7%a7%8d%e6%a3%80%e7%b4%a2%e6%96%b9%e5%bc%8f) 检索或者  [这里](https://github.com/Kenshin/simpread/discussions/3864)。
