### ISSUE TITLE
标注自动化时的通知优化

### ISSUE THREAD

**Issue by shuaimeng** [Kenshin/simpread#4177]
如标题。

可能是我还没学会如何使用，但找了一圈没找到怎么关闭。

**Comment by Kenshin** [comment]
这个是自动化的提示，你应该使用了标注的自动化，所以才会有此提示。

不过，确实没法关闭它，我会考虑出个插件解决这个问题。

**Comment by shuaimeng** [comment]
ok，好的。主要我经常标注时，使用半屏状态的chrome，文字本身周边的空间不大。如果频繁标注，侧边就会一直在自动化服务过程中不断出现”已完成。。。“，会遮挡我看内容

**Comment by Kenshin** [comment]
如果较频繁的标注，不太建议使用自动化方案，可以试试：自动化辅助增强插件

当标注完后，更改稍后读的元数据才触发自动化，比较好。

看看这里 https://github.com/Kenshin/simpread/discussions/3596

**Comment by Kenshin** [comment]
嗨，[自动化辅助增强插件](https://github.com/Kenshin/simpread/discussions/3596) **更新到 1.1.1** 解决了这个问题

## 📚 新增

【当触发自动化时优化右上角提示信息】

<img width="575" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5902e5d6-e4a7-468e-bcdf-237db30c8f25">

开启后，仅在标注并触发自动化时生效，会优化：`已成功保存。` `正在保存` `已成功保存到XXX` `正在导入` 等反复出现的提示。

## 💡 注意

极端情况下，如：安装了太多的插件并使用同步助手的自动同步以及连续标注时，会在浮动工具条显示时稍有卡顿问题。

注意：仅为个例，在测试期间除了我，几乎没有用户反馈过类似问题。

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/DH9l5jblPH) 安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 关联

https://github.com/Kenshin/simpread/issues/3595

***

我关闭这个 Issues 了有任何问题随时在这里讨论
