### ISSUE TITLE
指定站点标注自动增强导出失败，其余站点正常

### ISSUE THREAD

**Issue by Darkluna999** [Kenshin/simpread#4180]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 指定站点标注自动增强导出失败，其余站点正常 https://www.yiibai.com/powershell/powershell-start-process.html

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/53258301/177517798-8db23c53-740c-4eb2-9ddf-8474aa110db8.png)

**Comment by Darkluna999** [comment]
啊啊，不好意思可能是网络问题多发了一份，无论是加入稍后读/标注/自动插件导出时均出现如上报错

**Comment by Kenshin** [comment]
> 不好意思可能是网络问题多发了一份

小事情。

> 无论是加入稍后读/标注/自动插件导出时均出现如上报错

我知道是什么问题了，看下图

![image](https://user-images.githubusercontent.com/81074/177530661-f39b7812-6677-418d-a6af-d7ac5a863b81.png)

修改后，再次标注。或者手动导出 HTML 到本地，应该就没事了。

**Comment by Darkluna999** [comment]
不。。还是不行欸

**Comment by Kenshin** [comment]
emmm 随便修改个标题，然后手动导出一次 HTML。

**Comment by Darkluna999** [comment]
装了啊，生效的

**Comment by Darkluna999** [comment]
我随手搓了一串字母就好使了，实际上去掉这部分的两个空格就好使。。
![image](https://user-images.githubusercontent.com/53258301/177559663-52a21403-022c-4790-afef-80d15cca1511.png)

**Comment by Kenshin** [comment]
emmm 可能你这个空格并不是纯粹的空格，你可以试试：删除原来的空格后再加上新的空格。

当然，不愿意折腾的话，就算了。😂

**Comment by Darkluna999** [comment]
是的没错，就是这俩空格的问题，但是我检查过编码没有问题，玄幻

**Comment by Kenshin** [comment]
是的，就是跟这堆空格有关系，Mac 上没问题，但 Win 就不行了。

我不是 https://github.com/Kenshin/simpread/issues/4180#issuecomment-1176059489 告诉你了嘛，你也优化了这里 😂

后续的对话，可能误会彼此的疑问了，导致咱们讨论的是另外的事情了。
