### ISSUE TITLE
notion.so并未提供API，所以会出现授权失败的情况。

### ISSUE THREAD

**Issue by Leo-Ni88** [Kenshin/simpread#4184]
**环境**

- 操作系统 **MacOS**

- 浏览器版本 **Chrome 103.0.5060.114（正式版本） (x86_64)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <江苏南京>

**请描述你的问题**

> Notion 授权失败。提示：**notion.so并未提供API，所以会出现授权失败的情况。**

**截图**
![image](https://user-images.githubusercontent.com/65437462/177945676-98a83157-bcd1-41d9-9520-87b9773750c8.png)

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
