### ISSUE TITLE
重装系统通过云端覆盖配置文件后，无法打开偏好设置（选项页）

### ISSUE THREAD

**Issue by iFryRice** [Kenshin/simpread#4188]
**系统配置：**
- 操作系统 ：Win11
- 浏览器版本： Microsoft Egde 版本 103.0.1264.49 (正式版本) (64 位)
- 简悦版本 2.0
- 简悦·同步助手：1.1.702（下载后还未进行配置）

**问题描述：**
重装系统通过云端覆盖配置文件后，无法打开偏好设置（选项页），始终显示如下页面。

**截图**
![image](https://user-images.githubusercontent.com/102138235/178086504-184af76c-2748-4c41-bb5c-e26ec6393c3b.png)

**Comment by iFryRice** [comment]
删除拓展重装后，继续选择坚果云云端文件覆盖后，仍然显示上述页面。

**Comment by Kenshin** [comment]
试试

1. 重启同步助手。
2. 试试其他时间的历史记录 https://github.com/Kenshin/simpread/discussions/3940

**Comment by iFryRice** [comment]
您好，配置解决好了，现在发现另一个问题，只要打开同步助手（1.1.1 或是 1.1.702），选项页就打不开了；或者说，想要打开选项页就需要先退出同步助手..

**Comment by Kenshin** [comment]
是不是新版本需要重新绑定？
看看新版的通用里面有没有账户信息？

**Comment by iFryRice** [comment]
重新进行了配置后，问题解决了，谢谢大佬的解答

**Comment by Kenshin** [comment]
哈哈，搞定就好，我关闭这个 issues 了。

一般来说同步助手的版本升级都不需要重新绑定的，配置可以直接升级的。😂

***

方便的话，请进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 

通过下图，帮忙五星 + 好评  😏 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
