### ISSUE TITLE
导出 PDF 的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4189]
您好，买了一个高级版，按照教程都设置好了，但是pdf不能导出，一直显示“正在保存到本地，请稍等”，怎么解决呀

_Originally posted by @godjianghao in https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-3109705_

**Comment by Kenshin** [comment]
@godjianghao

请不要在无关的 Issues 提问，请在这个 Issues 提问。

还有请详细描述你的问题，如：URL 配置项等。

我先关闭这个 Issues 你可以继续留言。

**Comment by Kenshin** [comment]
添加几个设置的截
![同步助手配置 jpg](https://user-images.githubusercontent.com/108951682/178090019-0ceef4b3-6b00-4df4-bb4b-ce895aecf9b4.png)
![插件配置 jpg](https://user-images.githubusercontent.com/108951682/178090030-c20b88b5-6856-43ac-8233-137ebcddb44f.png)
![文件夹路径](https://user-images.githubusercontent.com/108951682/178090033-00459e19-5d21-4a49-8214-b52cf6f92228.png)
图

**Comment by Kenshin** [comment]
@godjianghao

请在 https://github.com/Kenshin/simpread/issues/4189 链接讨论。

***

1. 试试 https://sspai.com/post/71200 看看能否成功？
2. 需要安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件。

**Comment by godjianghao** [comment]
安装了插件，打开了你发的链接还是不能成功，真是奇怪

![1 jpg](https://user-images.githubusercontent.com/108951682/178100533-cc186c19-65e0-4008-90d2-7659524a27ef.png)

**Comment by Kenshin** [comment]
要不试试这个高级打印方案吧 https://github.com/Kenshin/simpread/discussions/3887

你的方式是：高级账户基础打印方案，有些弊端。

**Comment by godjianghao** [comment]
![1](https://user-images.githubusercontent.com/108951682/178111027-7643d3f7-c245-4b22-981d-beca2c34d394.png)
第一步安装，就失败了。w11安装到c和d盘都不行。
