### ISSUE TITLE
无法生成共享链接

### ISSUE THREAD

**Issue by PolarisPolaris** [Kenshin/simpread#4195]
https://user-images.githubusercontent.com/43163254/178303590-48386339-3ab1-4f98-8bfb-48facd82bf60.mp4

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** MacBook Air (M1, 2020).macOsS Monterey, Version 12.4**

- 浏览器版本 ** Version 103.0.5060.114 (Official Build) (arm64)**

- 简悦版本 **最新**

**请描述你的问题**

从激活简悦开始，一直都无法生成「分享链接」，具体情况请见 视频。
注意，视频中多次点击「生成」按钮，主要是为了演示功能的异常。
实际上，即使点击一次，一直等待，简悦也照样无法生成分享链接。

**Comment by Kenshin** [comment]
嗨，此功能已经下线，暂时也不会上线。

至于原因的话，属于众所周知的缘故 😂

**Comment by PolarisPolaris** [comment]
这样说的话，应该是某股东方的神秘力量的干扰了。😆

**Comment by Kenshin** [comment]
哈哈，简悦有一些 [自建方案](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22self+built%22)，你可以看看。
