### ISSUE TITLE
当文章标题带有“/”时，保存到Github会自动截去“/”前面的内容创建子目录，导致标题不完整

### ISSUE THREAD

**Issue by RiverTwilight** [Kenshin/simpread#4196]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10**

- 浏览器版本 **e.g. Chrome 103.0.5060.114**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

如题，[文章](https://sspai.com/post/74155)原标题为“**iOS /** iPadOS 16 公测版来了：新系统升降级指南 & 注意事项”，保存后变成“iPadOS 16 公测版来了：新系统升降级指南 & 注意事项”

![image](https://user-images.githubusercontent.com/52880665/178478663-52b58a6d-9667-4b39-87aa-6e126f90b24f.png)

![image](https://user-images.githubusercontent.com/52880665/178478763-b5175dc9-96c7-4b58-8863-8ee75f6965e4.png)

**Comment by Kenshin** [comment]
嗨，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，看看能否解决？

**Comment by RiverTwilight** [comment]
> 嗨，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，看看能否解决？

可以了，谢谢。

**Comment by Kenshin** [comment]
搞定就好~
