### ISSUE TITLE
CSDN网站上我不能导出为html、markdown了，但可以导出离线html

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4197]
@Kenshin  您好！最近我电脑在CSDN网站上我不能导出为html、markdown了，但可以导出离线html、离线markdown，其他网站正常，另外一台电脑也能正常导出CSDN（都是win10、Chrome浏览器、简悦2.2.0.520）。确认开启了加载标注模式，请问您知道怎么解决吗？加载之前的配置文件，稍后读数据会丢失，不太想这样

_Originally posted by @Jason-Study in https://github.com/Kenshin/simpread/issues/2178#issuecomment-1181560653_

**Comment by Jason-Study** [comment]
@Kenshin 
您好！找到原因了，是用了一个油猴“链接助手”插件导致的，关了就没问题了。

**Comment by Kenshin** [comment]
哈哈，原来如此，搞定就好。

****

有个事情，可能需要帮忙下。

隔离在三亚，且被一个一星评价恶心到了，要是简悦能帮到，请帮忙五星 + 好评 （否则请忽略这条）

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
