### ISSUE TITLE
chrome无法使用

### ISSUE THREAD

**Issue by WHATSAF** [Kenshin/simpread#420]
安装后没有做任何操作，重启浏览器，打开任意网站该插件都没反应

```
操作系统:win10 pro 17134.407
chrome版本:70.0.3538.102
chrome已有插件:Calm, React Developer Tools, SmoothScroll, 划词翻译
```

**Comment by Kenshin** [comment]
访问 https://sspai.com/post/39491 后在右上角是否显示红色的 icon ？
如果显示的话，点击它，看看是否能进入阅读模式？
如果能的话，请先看下新手入门  http://ksria.com/simpread/docs/

**Comment by Kenshin** [comment]
1. 选项页 → 共通 → 手动同步适配列表。

看看有什么提示？

2. 选项页 → 关于 → 中间部份有一行字 `简悦已经适配了 xxx 类网址` 

看看是否为 0 ？

上述步骤完成后，请在试试之前告诉你的方法。

另外，你是从哪里下载的 简悦？

**Comment by WHATSAF** [comment]
@Kenshin 
1.提示：适配列表已同步至最新版本
2.适配了276类网址
从chrome商店下载的

**Comment by Kenshin** [comment]
这就比较神奇了... 不可能出现你说的情况。
你试试把其它扩展禁用了什么效果。

**Comment by WHATSAF** [comment]
@Kenshin 重新安装了可以了。。
打扰了。
