### ISSUE TITLE
最新版chrome简悦同步助手验证无法点击（已开通高级账户）

### ISSUE THREAD

**Issue by thestarx** [Kenshin/simpread#4204]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Chrome 103.0.5060.114*

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <请填写你的地址l>
chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common
**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
最新版chrome简悦验证没有反应，edge可以，不过我因为chrome是主力，不会更改

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/97114131/178757342-6be2f87c-d70d-43ee-a41d-5532a7113cf2.png)

**Comment by Kenshin** [comment]
不要重复新建 Issues

简悦不会区分浏览器，所以无论是 Chrome 还是 Edge 都没问题。

既然你的 Edge 没问题，就确认下 Chrome 与 Edge 的在设置上有什么区别？

一般需要开通网络权限等。

**Comment by Kenshin** [comment]
另外，将 Edge 的配置导出再导入到 Chrome 里面，一般来说会自动授权。

**Comment by thestarx** [comment]
![image](https://user-images.githubusercontent.com/97114131/178885229-b482496d-b8f1-48ca-af9b-cc9eb84b4170.png)
![image](https://user-images.githubusercontent.com/97114131/178885297-4337b99f-4b59-4233-8abb-893599f69cee.png)
通过您说的办法，依然无法得到解决，如果还有更好的办法，感谢你的回复

**Comment by Kenshin** [comment]
emmm

先看下 是否是 https://github.com/Kenshin/simpread/discussions/1567 造成的。

然后试试下图的方案

![image](https://user-images.githubusercontent.com/81074/178892577-7390dfcc-23f0-4858-a1cb-ab2605ea7799.png)

**Comment by thestarx** [comment]
试了次方案，还是不能使用同步助手

**Comment by Kenshin** [comment]
你确定在同一个电脑上 Edge 好使，但 Chrome 不好使？

如果是的话，肯定跟你在 Chrome 上的设置（跟简悦无关）的有关系。

**Comment by iFengZhao** [comment]
我昨天购买的高级账户，使用chrome，有同样的问题，无法验证。原本以为整个服务的使用可以非常简约，没有想到如此复杂难搞。非常令人失望。
