### ISSUE TITLE
简悦在 Firefox 被下架的相关讨论（及解决办法）

### ISSUE THREAD

**Issue by heptaspirit** [Kenshin/simpread#421]
firefox附加组件市场找不到“简悦”和“simpread”，现在无法安装，只能暂时使用chrome
firefox版本是否下架？

**Comment by Kenshin** [comment]
抱歉，目前暂时无法使用 Firefox 版本，因为被各种奇葩原因下架... 我正在联络他们（估计够呛...  😂

**Comment by heptaspirit** [comment]
居然是被那边下架了，也是服了……
希望能尽早解开吧，不知道他们是有什么新政策。

**Comment by pgain2004** [comment]
一个月了，虽然扩展本身也没有更新（作者似乎在忙别的事），但还是希望能尽快恢复上架

**Comment by Kenshin** [comment]
@pgain2004 
即便上架也会再次下架，Firefox 新上的策略很恶心。

因为跟 Apple 一样是人工审核，所以...

**Comment by Roger-WIN** [comment]
暂时用轻阅版的脚本代替吧。

**Comment by Kenshin** [comment]
各位，我明天会重新提交一次，然后 Firefox 的自动审核会通过，到时候我会在这里通知大家，请大家尽快下载。

等到人工审核（一般 2 ~ 3 天后）会再次以各种诡异缘故下架...

**Comment by Kenshin** [comment]
各位，Firefox 版已重新上架，地址 https://addons.mozilla.org/zh-CN/firefox/addon/simpread/ 
请尽快下载~

**Comment by seahime** [comment]
没有离线版供下载么？

**Comment by Kenshin** [comment]
@seahime 

https://github.com/Kenshin/simpread/issues/666

**Comment by bruceye** [comment]
又找不到下载了，请放个离线版的

**Comment by wookaooo** [comment]
Firefox的[开发者版]和[Nightly]版，将xpinstall.signatures.required改为false，即可使用非签名的附加组件。

**Comment by stucash** [comment]
> Firefox的[开发者版]和[Nightly]版，将xpinstall.signatures.required改为false，即可使用非签名的附加组件。

你的意思是就能搜到简悦了吗？如果还是需要使用离线安装包那也没辙呀。。

**Comment by stucash** [comment]
> Firefox的[开发者版]和[Nightly]版，将xpinstall.signatures.required改为false，即可使用非签名的附加组件。

OK 我还以为是能搜到简悦了, 你这个方法也无法搜到简悦; 至于离线安装包, 只要有, 什么版本都可以装呀; 还是说你手里有一个非签名的版本?

**Comment by ttimasdf** [comment]
FYI 可以通过以下方法获取 Chrome Web Store 的 CRX 包。 https://github.com/Kenshin/simpread/issues/666#issuecomment-2611480233

> 通过 Chrome API 获取最新版 简悦插件， https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133.0&acceptformat=crx2,crx3&x=id%3Dijllcpnolfcooahcekpamkbidhejabll%26uc

**Comment by Kenshin** [comment]
@ttimasdf 

我没太理解你的方案？现在可以在 FF 下直接使用 crx 包？

**Comment by ttimasdf** [comment]
> 我没太理解你的方案？现在可以在 FF 下直接使用 crx 包？

@Kenshin 

能，名字改成 zip 就能跑，功能用起来好像都没什么问题，不过还是上面帖子里那种临时载入的方式，火狐一重启就没了

**Comment by Kenshin** [comment]
@ttimasdf 

> 能，名字改成 zip 就能跑，功能用起来好像都没什么问题，

Cool

> 不过还是上面帖子里那种临时载入的方式，火狐一重启就没了

 🌚  真是理解不了 FF 的「点」在哪里？我只能认为这种方式是为了安全，但用户手动加载的为什么会划归为「非安全」模式...

不过，对某些长期不关机的用户来说（Mac arm 版），影响也不算是太大~

**Comment by ttimasdf** [comment]
> 🌚 真是理解不了 FF 的「点」在哪里？我只能认为这种方式是为了安全，但用户手动加载的为什么会划归为「非安全」模式...

一拍脑袋我能想到这几个理由，

- 用户 click 一个按钮加载代码，跟程序模拟用户 click 一个按钮加载代码，安全程度大概等于在密码锁旁边用纸条贴个密码😂
- 允许远程加载代码实质上等于绕过审核，因为开发者任何时候都可以更新，审核就形同虚设了，而且审核跟数字签名一起作为一道防线，允许热加载，插件的数字签名也没有意义了。所以火狐的策略实际对用户来讲更好
- 远程加载的代码**非常黑箱，非常不安全**。开发者工具里看不到热加载代码中发出的 HTTP 请求，也无法在其中打断点调试。被中间人劫持或者供应链攻击的话，连开发者本人都不一定发现得了。
- 火狐插件商城的 policy 里确实是这么写的，禁止热加载代码。即使不在 AMO 上架（Self-distribution）也不行。

[Add-on Policies | Firefox Extension Workshop](https://extensionworkshop.com/documentation/publish/add-on-policies/)

> All add-ons are subject to these policies, regardless of how they are distributed.
> ...
> # Development Practices
> The following requirements are of particular importance:
> ...
>     Add-ons must be self-contained and not load remote code for execution.

**Comment by Kenshin** [comment]
😂

一直 Get 不到 FF 所谓安全的点。

**Comment by ttimasdf** [comment]
先从坏人的角度思考一下怎么做坏事，再从好人的角度再去想想怎么反制坏人的手法，再从坏人的角度想想怎么绕过反制，恭喜你你就入行了😈

上个月的 CSDN 定向挂马，前两天的 B 站投毒，跟我们现在说的其实都是差不多的技术。 ~~这套技术去做黑产比写插件来钱快多了（逃~~

**Comment by Kenshin** [comment]
从浏览器扩展 **手动选择路径并加载 `.zip`** 是用户行为，并没有任何 API 或其它可以绕过的方案。

如果 FF 觉得这样也算有风险的话... 😂

**Comment by Kenshin** [comment]
嗨，各位，简悦 for Firefox 版正式发布了~

<img width="808" height="455" alt="Image" src="https://github.com/user-attachments/assets/58297ed1-551a-4fd1-b603-f42e7b4d9dbc" />

# 📚 支持浏览器

Zen browser · Firefox Nightly · Firefox Developer Edition · Firefox · Librewolf

# 🔗 如何使用 & 简悦 CRX 下载

[https://github.com/Kenshin/simpread/discussions/7279](https://github.com/Kenshin/simpread/discussions/7279)

注意：请不要使用 Chrome Webstore 下载的 crx，请使用专门为 Firefox 适配的 crx（上面链接有下载地址）

# ✅ 完美支持

- 阅读模式 / 聚焦模式

- 安装插件

- 更新站点

- 稍后读 / 标注

# ✳️ 需配合 [同步助手 1.5.0](https://n.simp.red/posts/648) 后支持

- 自动同步

# ❎ 不完美支持

快捷键暂时无法使用，但你可以使用 **全局快捷键解决无法进入阅读模式和加入稍后读的问题**，也可以使用 **Assistive Touch 解决简悦插件快捷键无法使用的问题**，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16470898)

# 在 Firefox 正式版使用简悦

如果你不希望更换上述浏览器，在 Firefox 也可以正常使用，但需要一些技巧，[详细说明](https://github.com/Kenshin/simpread/discussions/7279#discussioncomment-16446625) 

# 最后

有任何问题统一在 [https://github.com/Kenshin/simpread/issues/7037](https://github.com/Kenshin/simpread/issues/7037) 讨论

我关闭这个 issues 了~
