### ISSUE TITLE
知乎公式文字对不齐

### ISSUE THREAD

**Issue by Anz-03** [Kenshin/simpread#4212]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://zhuanlan.zhihu.com/p/45810014>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Anz-03** [comment]
![image](https://user-images.githubusercontent.com/106299500/179206245-ad92f95c-db6c-43ff-892d-aefa058406ad.png)
![image](https://user-images.githubusercontent.com/106299500/179206271-b13a0c44-5014-4267-b045-a8e54f4b529a.png)

**Comment by Kenshin** [comment]
是没问题的，试试安装这个插件 https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ

![image](https://user-images.githubusercontent.com/81074/179214424-789682e9-df73-430d-95e9-f2da6a482f8e.png)

**Comment by Kenshin** [comment]
嗨，抱歉，之前没有看到 https://github.com/Kenshin/simpread/issues/4212#issuecomment-1185411780 这个内容。

目前只能做到这种程度，因为阅读模式与原网页还是有很多区别的。
