### ISSUE TITLE
中文版wiki显示正常，英文版wiki异常

### ISSUE THREAD

**Issue by Anz-03** [Kenshin/simpread#4215]
https://zh.wikipedia.org/zh-hans/%E7%9B%B8%E4%BC%BC%E7%9F%A9%E9%99%A3 https://en.wikipedia.org/wiki/Matrix_similarity

**Comment by Kenshin** [comment]
嗨，试试下面的方案

打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![image](https://user-images.githubusercontent.com/81074/120952856-6f2da080-c77e-11eb-8e1a-0f6d9da8e40f.png)

**Comment by Anz-03** [comment]
> 

还是不行
![image](https://user-images.githubusercontent.com/106299500/179386251-79b83594-a39e-4e26-af01-b07fc7516311.png)
![image](https://user-images.githubusercontent.com/106299500/179386269-57c25493-7da8-49e0-96e5-657c11d807be.png)

**Comment by Kenshin** [comment]
我大概知道你的问题的，你是问「阅读模式效果不好吧？」

如果是的话，建议看下 https://github.com/Kenshin/simpread/discussions/3196 这个方案。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，解决了此类问题。

<img width="659" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6cd65278-3645-4a53-bd95-097d40eafb6c">

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
