### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by bournewang** [Kenshin/simpread#4217]
你好，
**npm install** 之后，
运行**npm run ext_dev** 为什么会爆一堆  Cannot resolve module 的问题：

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./ext/contentscripts.js in /Users/wangxiaopei/work/simpread

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./ext/background.js in /Users/wangxiaopei/work/simpread

ERROR in multi vendors
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wangxiaopei/work/simpread/src/module/modals.jsx in /Users/wangxiaopei/work/simpread
 @ multi vendors

ERROR in ./src/service/export.js
Module not found: Error: Cannot resolve module 'mdgfm' in /Users/wangxiaopei/work/simpread/src/service
 @ ./src/service/export.js 24:13-29

ERROR in ./src/service/export.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wangxiaopei/work/simpread/src/vender/puread/plugin.js in /Users/wangxiaopei/work/simpread/src/service
 @ ./src/service/export.js 42:16-35

ERROR in ./src/vender/mduikit/tooltip.jsx
Module not found: Error: Cannot resolve module 'mintooltip' in /Users/wangxiaopei/work/simpread/src/vender/mduikit
 @ ./src/vender/mduikit/tooltip.jsx 10:0-21

ERROR in ./src/options/options.js
Module not found: Error: Cannot resolve module 'mduikit_css' in /Users/wangxiaopei/work/simpread/src/options
 @ ./src/options/options.js 9:0-22

ERROR in ./src/options/options.js
Module not found: Error: Cannot resolve module 'intro_css' in /Users/wangxiaopei/work/simpread/src/options
 @ ./src/options/options.js 13:0-20

**Comment by bournewang** [comment]
插件模式不能满足我的需求，我希望编辑程序更灵活的添加内容，希望指点一二。
npm run server 和run develop是可以成功的。

**Comment by Kenshin** [comment]
嗨，目前开源的只是 1.x 版的功能。

**Comment by bournewang** [comment]
1.x 也是同样的错误无法编译
