### ISSUE TITLE
稍后读的文章无法完全删除

### ISSUE THREAD

**Issue by BazzJiang** [Kenshin/simpread#4219]
使用步骤：
1.从Pocket添加文章到稍后读
2.打开浏览器插件，从坚果云同步配置数据(这里可以正常获取第一步添加的文章)
3.从稍后读删除该文章
4.在设置里面点击【强制覆盖配置文件到坚果云】，运行成功
5.再次同步坚果云的数据到本地，发现第三步删除的文章又变回来了。

**Comment by BazzJiang** [comment]
应该是缓存问题，稍后读文章删除之后，不会马上生效

**Comment by Kenshin** [comment]
嗨，应该跟 https://github.com/Kenshin/simpread/issues/4218 是一个问题吧？

如果使用了自动同步，其实步骤4是没有意义的，步骤4的功能是针对手动同步而设置的。
