### ISSUE TITLE
无法从一台设备上登出账户

### ISSUE THREAD

**Issue by qiankunxienb** [Kenshin/simpread#4224]
我是高级用户，因为要更换电脑，我需要从老电脑上登出简阅的账户。但是提示如下：
<img width="633" alt="image" src="https://user-images.githubusercontent.com/71627005/179399547-03cc4d9d-274c-4680-8ca5-a194b9621a26.png">

**Comment by Kenshin** [comment]
选项页 → 右上角，细节看这里 https://github.com/Kenshin/simpread/discussions/1575

**Comment by qiankunxienb** [comment]
依然是这个报错

**Comment by qiankunxienb** [comment]
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/71627005/179403165-46ffedbe-3aff-4d18-a33b-d8f08e5297ff.png">

**Comment by Kenshin** [comment]
试试 https://github.com/Kenshin/simpread/discussions/1576 然后再登出。

另外，其实我不用管这个问题，未登陆的设备在 15 天后自动登出。
