### ISSUE TITLE
用于 Deeplink 的单条标注外链方案配置后无法按模板生成引用

### ISSUE THREAD

**Issue by cameron-chen** [Kenshin/simpread#4229]
**请说明发生问题的环境**

- 操作系统 **Windows 10**

- 浏览器版本 **Version 103.0.1264.62 (Official build) (64-bit)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html>

**请描述你的问题**

按照教程 [用于 Deeplink 的单条标注外链方案 #3350](https://github.com/Kenshin/simpread/discussions/3350) 中的方案二配置了 Deeplink。出现的问题是，导出的标注并不按照模板格式。

例如，我设置引用链接模板：`[{{an_text}}](<{{an_ext_uri}}>)`。但导出的引用是：

```
> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 来自 chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/loader.html?url=https://yihui.org/cn/2005/01/rush/

> 标签：  
> #sheep/谢益辉# blog

> 去的尽管去了，来的尽管来着，去来的中间，又怎样的匆匆呢？
```

**截图**

具体配置
![image](https://user-images.githubusercontent.com/60129542/179556891-724119cb-0d3f-4065-b2fb-ab9c286556d7.png)

**备注**

Kenshin 同时也建议了使用 notion 导出增强插件。我看了一下插件的应用场景：适用于文章全文或者标注自动化导出到 notion。

这里描述一下我的使用场景：我的笔记系统基于 notion 建立，主要的需求是在上面手打笔记。其中来自网页的引用希望能够做到快速引用，即能够一键复制需要引用的内容和对应的链接。参考的模板可能是：`{{an_text}} - [source](<{{an_ext_uri}}>)`。

在 issue 里没有找到类似问题，故开一帖。

**Comment by Kenshin** [comment]
收到，我近期在休假，稍晚帮你看下。

**Comment by Kenshin** [comment]
嗨，你的问题中，你用了什么模板？这个问题跟你使用的模板有关系。

另外一个问题，这个功能应该在阅读模式中使用，而不是稍后读。

***

此功能需要配置知识库、开启自定义 Markdown 模板、内部链接、外部链接。

![image](https://user-images.githubusercontent.com/81074/189294593-405bb3c0-daae-4b19-8d95-407d76ebfe92.png)

![image](https://user-images.githubusercontent.com/81074/189294737-1086ec88-70bc-48df-9582-39d5c781ebf6.png)

![image](https://user-images.githubusercontent.com/81074/189294668-b0138e78-3105-480c-b83e-ee3075c88960.png)

**Comment by cameron-chen** [comment]
问题解决了，感谢！

反馈一下：
- 问题出在自定义 Markdown 模板，我开启了模版，但是没有填写内容 `{{/each}}`。填写之后功能正常运行。
- 测试之后，deeplink 在稍后读和阅读模式都能使用。
- 建议：建议在 #3350 中提醒添加自定义 Markdown 模版语句。单纯依靠这个教程，可能不会在 Markdown 自定义模板中添加`{{/each}}`。

另， #3350 可能有个错误。如图，原话：
> 方案一「占用」了导出单条标注时的模板，所以建议使用方案一的方式，但方案一有更多定制模板样式的空间。

可能是想说：
方案一「占用」了导出单条标注时的模板，所以建议使用**方案二**的方式，但方案一有更多定制模板样式的空间。

![image](https://user-images.githubusercontent.com/60129542/189343157-a3b47212-57ef-4d13-b6ca-e4e5b607e065.png)

**Comment by Kenshin** [comment]
哈，搞定就好。

你提到的其实有说，可能不太详细，我会再着重提示下。
