### ISSUE TITLE
自动化服务无法设置（readwise 和hypothesis不能点击，被广告覆盖，怎么操作都无法使用）

### ISSUE THREAD

**Issue by michaelyyq** [Kenshin/simpread#4231]
[screen-capture.webm](https://user-images.githubusercontent.com/16754788/179749012-3f57733d-33f4-43ae-86cf-d7dbdd85bc1b.webm)

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
[screen-capture.webm](https://user-images.githubusercontent.com/16754788/179749300-f9ddb9ac-f007-4dce-8418-cd14fea455ba.webm)

**Comment by michaelyyq** [comment]
市面上的笔记类的工具用了不少，这个是最难用的，为了和readwise或hypothesis同步，购买了高级账户，结果，被弹窗占用，也不知道什么鬼设计。

**Comment by Kenshin** [comment]
首次购买后，需要重启浏览器，但是你没有重启。
提示的也不是广告，而是因为没有重启浏览器而无法成为高级账户的一种提示。

解决方案 https://github.com/Kenshin/simpread/discussions/2816

**Comment by michaelyyq** [comment]
#2816 仅授权当前设备，有用。这个设计也很奇怪哈。

**Comment by Kenshin** [comment]
当使用新设备时就使用 https://github.com/Kenshin/simpread/discussions/1576 授权。

这么设计是为了方便解绑当前设备的高级账户权限。
