### ISSUE TITLE
md+assets的功能如何能与WebDav导出相结合?

### ISSUE THREAD

**Issue by miaolinvip** [Kenshin/simpread#4235]
我是使用群晖nas的用户,有自建的WebDav服务器, 通过简悦的WebDav文档,已经成功的实现了一键发送到家里的nas服务器上面.  但是发过来的只有md文件,所有图片均为链接, 单独的使用md+assets的功能,又无法接入WebDav,请问一下如何可以将两个功能合为一个功能按钮?

**Comment by Kenshin** [comment]
暂时不能。

不过，如果路径可以设置的话，应该也没问题，也就是在你的电脑上可以访问群晖的路径。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨
> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了定制 assets 路径的功能，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696)。

![](https://user-images.githubusercontent.com/81074/202892148-b6ede303-f882-4362-9399-e047523d265a.png)

打开 https://simpread.ksria.cn/plugins/details/BvjrJA6eh5 可自动安装。如果使用同步助手的话，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

### 除此之外比较重要的更新

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
