### ISSUE TITLE
因标题含有 CJK 字符导致导入到 Notion 失败的说明以及解决方案

### ISSUE THREAD

**Issue by damonflycloud** [Kenshin/simpread#4237]
自从昨天起 使用简悦保存文章到notion会发现只保存了文章标题,文章内容是空白的,麻烦帮忙看下是什么问题

**Comment by Maoqie** [comment]
+1，一直卡在”正在保存到Notion，请稍等“，Notion里只有一个Untitled的空白页。

**Comment by sisibeloved** [comment]
+1，Chrome无法保存，重新安装了一个Edge，也是一模一样的现象

**Comment by Kenshin** [comment]
关联问题 https://github.com/Kenshin/simpread/issues/4239 https://github.com/Kenshin/simpread/issues/4240

**Comment by Kenshin** [comment]
各位，以及 @jon9527 @tttsong 

可以试试 https://www.kali.org/blog/kali-vm-builder-weekly/ 这个页面能否正常导入？

**Comment by tttsong** [comment]
> 各位，以及 @jon9527 @tttsong
> 
> 可以试试 https://www.kali.org/blog/kali-vm-builder-weekly/ 这个页面能否正常导入？

可以

**Comment by Kenshin** [comment]
@tttsong 

再试试少数派的文章是否能保存？例如 https://sspai.com/post/69972

**Comment by 11yiyang** [comment]
> @tttsong
> 
> 再试试少数派的文章是否能保存？例如 https://sspai.com/post/69972

两个链接都不能保存，一直显示「正在保存到Notion，请稍等」，一直重复请求getTask，Notion页面只是多了两个Untitled文件

**Comment by Kenshin** [comment]
@11yiyang @tttsong

请问是什么地方的网络？

**Comment by Zhao-Lian** [comment]
测试结果：kali 可以正常保存，sspai 只会生成空空白页
网络：北京电信
浏览器：Win10 Edg/103.0.1264.62
会一直请求getTasks, 这是接口返回的结果
`{
  "results": [
    {
      "id": "f0a3bd3a-c8e0-4216-84c9-6fd5dd566184",
      "eventName": "importFile",
      "request": {
        "fileURL": "https://s3-us-west-2.amazonaws.com/temporary.notion-static.com/0069bde9-d390-481a-a7e6-14be34783c0a/%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8__%E7%BA%BF%E4%B8%8A%E8%8E%B7%E5%8F%96%EF%BC%9A%E6%88%91%E7%9A%84%E4%B8%AA%E4%BA%BA%E6%95%B0%E6%8D%AE%E5%BA%93%E5%BB%BA%E6%9E%84%E8%B7%AF%E5%BE%84.md",
        "fileName": "本地存储 + 线上获取：我的个人数据库建构路径.md",
        "importType": "ReplaceBlock",
        "pageId": "80cae439-11d4-489e-943d-31c055c658a0"
      },
      "actor": {
        "table": "notion_user",
        "id": "b6f6d14f-46ae-4b8f-8557-2ae2faf1a09f"
      },
      "state": "failure",
      "rootRequest": {
        "eventName": "importFile",
        "requestId": "f0a3bd3a-c8e0-4216-84c9-6fd5dd566184"
      },
      "headers": {
        "ip": "193.36.132.222"
      },
      "error": "NotFound"
    }
  ]
}`

**Comment by wqddg** [comment]
> 各位，以及 @jon9527 @tttsong
> 
> 可以试试 https://www.kali.org/blog/kali-vm-builder-weekly/ 这个页面能否正常导入？

不可以


我的也出现无法保存问题  notion

**Comment by 11yiyang** [comment]
> @11yiyang @tttsong
> 
> 请问是什么地方的网络？

广东电信。使用手机移动开热点，朋友的移动宽带也是一样，无法保存。getTasks返回的内容和[上面](https://github.com/Kenshin/simpread/issues/4237#issuecomment-1192201555)差不多

**Comment by 11yiyang** [comment]
> @11yiyang @tttsong
> 
> 请问是什么地方的网络？

再次尝试，https://www.kali.org/blog/kali-vm-builder-weekly/可以保存，https://sspai.com/post/69972无法保存

**Comment by Kenshin** [comment]
各位，基本上可以确认了。

关于近期 Notion API 无法使用的几点说明：

1. 简悦端没有做任何改动。
2. 此问题因为 Notion API 的某台服务器问题造成。（疑似）
3. 影响的只是国内网站的保存。
4. 外网的 URL 在保存时均不受此问题影响。

以往的经验：Notion API 日常抽风，只是这次影响范围比较大。
有进一步的消息我会在这里通知大家。

最新：我准备联络 Notion 但因为他们目前是周末，所以可能需要多几天的时间。

**Comment by Kenshin** [comment]
嗨，各位，关于此问题的最终结论与解决方案。

> 近期发生了导入到 Notion 失败的问题，经过初步检查发现并不是简悦的问题，经过用户提示和我的测试终于找到了原因。

💢 问题原因找到了

1️⃣ 并不是外网可以保存但国内的网站可以保存。

2️⃣ 如果标题是 CJK 字符就无法保存（也就是仅标题为字母或数字的可以保存）

🙋‍♂️ 初级临时解决方案

使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 将需要导入到 Notion 的网页标题改为英文即可。

💁‍♂️ 中级临时解决方案

（因为不确定）我会在 [Notion 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572) 将上面的解决方案自动化。

也就是当导入完毕后，把英文标题在自动改为正常的标题。

🤦‍♂️ 终极解决方案

我已经联络 Notion，希望 Notion 可以彻底解决此问题。

**Comment by Kenshin** [comment]
嗨，各位，我升级了 Notion 辅助增强插件，临时解决了此问题，如何解决 [请看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-3211220)。

## 视频演示

https://user-images.githubusercontent.com/81074/180594879-13d9e3f0-3497-4c97-8a33-6d8187cbe46f.mp4

## 后续

如果 Notion 彻底解决这个问题我会在这里通知大家。

**Comment by sherlockmj** [comment]
请问notion增强导入全文支持快捷键吗

**Comment by Kenshin** [comment]
@ sherlockmj

当然… 建议看下说明文档。

**Comment by cangyuyao** [comment]
和简悦无关但是是个相关问题，前几天导入csv一直failed最后发现是文件名带了CJK，以为是本来就不支持还写了feedback说他们连个提示都没有，怎么会有这种bug……

**Comment by Kenshin** [comment]
@cangyuyao 

是的，之前有个用户也反馈说 CJK 文件名无法导入了… 😂

**Comment by Kenshin** [comment]
嗨，各位。

Notion 已经彻底解决了[【因标题含有 CJK 字符导致导入到 Notion】](https://github.com/Kenshin/simpread/issues/4237)的问题，所以此 Issues 我关闭了。

同时 Notion 辅助增强升级到 1.2.2 也去掉了 1.2.1 版为此设置的功能，请各位升级。

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311

**Comment by jon9527** [comment]
开发者你好，目前我已经基本弄懂简悦的工作流程。确实解决了我工作生活中的很多问题。notion剪藏功能确实牛逼，比我使用的任何导入工具都厉害。logseq自动标注导出也正常。但目前遇到个问题，我日志用的星期格式，但是我不知道简悦标注markdown如何设置星期格式。每次点击简悦的标注日期都不能链接到日志。另外标签默认简悦，能否加其他标签？每次我都得手动加标签，query才能查询到标注，很麻烦。
<img width="613" alt="Snipaste_2022-08-09_22-17-55" src="https://user-images.githubusercontent.com/71954782/183674726-683e28ab-d4a5-4b74-a7c5-3389c75515f8.png">

**Comment by Jie-alt** [comment]
> 各位，以及 @jon9527 @tttsong
> 
> 可以试试 https://www.kali.org/blog/kali-vm-builder-weekly/ 这个页面能否正常导入？

不行啊

**Comment by Kenshin** [comment]
@Jie-alt 

这个 Issues 的问题已经被 Notion 官方解决了，而且很久之前就解决了…

所以，请不要在无关的 Issues 提问，有问题请 https://github.com/Kenshin/simpread/issues/new/choose 讨论

**Comment by Kenshin** [comment]
嗨，各位。

导入到 Notion 发布了全新的 2.0 版，支持一键授权（不在有繁琐的授权过程），加持简悦完美的阅读模式，同时支持导入带标注色的全文，可以彻底解决你遇到的问题。

![](https://imgs.zhubai.love/5ccaad4e75ac4610b11c966cb45f8484_2072964972706709504.png)

# 🆕 全新 2.0 版

在 2024 年 11 月 16 日，Notion 私有 API 再次出现无法使用的问题，这让我决定**彻底弃用私有 API 方案，全面转向公开 API**。

由于采用公开 API，确保了功能的稳定性，不会再出现无法使用的情况，以下所有功能均基于 2.0 版本的描述。

# 🌟 特色

与其他同类产品相比，**简悦凭借其出色的阅读模式，可以更精准地将全文导入到 Notion**。

由于采用了公共 API，解决了 1.0 版本无法无法正确转换 LaTeX 公式的问题，并提供更安全简便的一键授权方式（相比私有 API，避免了账户泄漏风险）。

此外，还支持以下功能：

1️⃣ 在 Notion Page 显示描述、题图、Favicon、来源、标签、备注

2️⃣ 内置图床

3️⃣ 导入带标注颜色的全文 [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

4️⃣ 导入标注（支持三种方式）

5️⃣ 支持超长文章的导入、[知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229)、[表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74)（使用私有 API 的产品都存在无法使用的问题）

# 📥 导入效果

[https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897](https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897&pvs=74)

# 📚 一站式教程

[https://www.yuque.com/kenshin/simpread/zx3bcz](https://www.yuque.com/kenshin/simpread/zx3bcz)

# 📦 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

如果你需要使用简悦 + Notion 的话，可以直接看 [此配置库](https://www.yuque.com/kenshin/simpread/mwda8s) 。

# 🔌 介绍

导入到 Notion 相关功能分为两个插件：

📗 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

📘 [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU)

# 📖 功能

1️⃣ 可导入当前页面的题图、Favicon、来源等。

![img](https://imgs.zhubai.love/92778b3c8dcc4b1ab1120e1dbf780d33_2072964972706709504.png)

2️⃣ 导入正文到 Notion，因为使用了公开 API，所以可以完美适配 [知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229) · [表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74) 

3️⃣ 导入**带标注色的正文**到 Notion [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

> 此功能需要 **简悦高级账户**，可通过 [**此链接**](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/c6aa20e1b1814399b9e87b569ebdb3b5_2072964972706709504.png)

4️⃣ 内置 Cloudinary 图床

![img](https://imgs.zhubai.love/85901d6d7ed74b598b1b75ab81b59754_2072964972706709504.png)

5️⃣ 在导入可选择任意 Notion

![img](https://imgs.zhubai.love/2864ffa0f9134a4b8c99116cdf12c41f_2072964972706709504.png)

6️⃣ 同步稍后读的标签，并支持加入全局标签（即使当前页面未被标记为稍后读，也可导入已添加的全局标签）。

![img](https://imgs.zhubai.love/0cda01a5740a4c35b80391dc1ac971e5_2072964972706709504.png)

7️⃣ 添加描述（Summary）与稍后读备注（Note）

> 此功能需要 **简悦高级账户**，可通过 [此链接](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/d1d8cbad7ef94f169095039cd18b9b23_2072964972706709504.png)

8️⃣ 去除重复的 Page

![img](https://imgs.zhubai.love/58668edcf264416ea6dc2d97069ce2b0_2072964972706709504.png)

9️⃣ 导入标注

![img](https://imgs.zhubai.love/59ffe6d7a1644d83ab40f2d6bc06597e_2072964972706709504.png)

2.0 版在原来的方案（[标准模式](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)）基础上增加了两个全新的标注模板：

📗 带标注色的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f5881ada61bc11c25596f1d?pvs=74)

📘 按照标注色分类的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f58814da34fd7e2e0cb9d96?pvs=74)

![img](https://imgs.zhubai.love/fc42ca0d3dc94186b02e6737febdde51_2072964972706709504.png)

注意：上述两种标注模板需要**简悦高级账户**权限，可通过 [此链接](https://simpread.pro/price) 升级。

# 🔄 旧版本升级说明

如果你已使用 1.x 版（旧版本），首次升级后会出现如下截图，此时需重新授权 Notion 才能使用。（授权方式与上面一致）

![img](https://imgs.zhubai.love/fea50a3a372d47098655eddf70022cc7_2072964972706709504.png)

# 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可直接 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)  [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

#  🔎 关联 

https://github.com/Kenshin/simpread/issues/4955

***

有任何问题，请随时在这里讨论~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
