### ISSUE TITLE
小书签功能无法修改标题问题

### ISSUE THREAD

**Issue by liangenhao** [Kenshin/simpread#4238]
- 操作系统 **MacOS 10.15.5**

- 浏览器版本 **Microsoft Edge 103.0.1264.62 (正式版本) (x86_64)**

- 简悦版本 **2.2.0**

**请描述你的问题**

通过小书签功能加入稍后读，收藏时弹出收藏对话框，修改标题不生效。

**Comment by Kenshin** [comment]
emmm 应该没问题，请问能稳定复现吗？另外试试描述、备注等是否可以修改？

**Comment by liangenhao** [comment]
> emmm 应该没问题，请问能稳定复现吗？另外试试描述、备注等是否可以修改？

描述和备注可以修改，标题无法修改，百分百可以复现。

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

**修复了小书签无法修改标题的问题**

除此之外，1.1.4 版还包括下面的一些功能：

## 下载地址

- [包含多种渠道下载](http://ksria.com/simpread/docs/#/Sync?id=下载)

## 更新日志

- [更新日志](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792)

## 新增 💄 

### 朗读

将正文转换为语音并播放，与 Edge 内置的大声朗读功能一样，均来自 Microsoft Azure 的语音服务。

<img width="3650" alt="TTS@plugin" src="https://user-images.githubusercontent.com/81074/206418879-c6ba7b85-e706-4741-b0b1-2e5123f2493d.png">    

- 插件端 [朗读](https://github.com/Kenshin/simpread/discussions/4833)

- 内置到 [稍后读极速版的本地快照](http://ksria.com/simpread/docs/#/TTS?id=内置到本地快照)
