### ISSUE TITLE
url minimatch bug

### ISSUE THREAD

**Issue by NihilityT** [Kenshin/simpread#424]
域名不支持协议通配`http*://`，提示`请输入有效的 url`。
![minimatch bug](https://user-images.githubusercontent.com/21163191/48762844-e4334a80-ece6-11e8-9185-a482892421c3.png)

**Comment by Kenshin** [comment]
谢谢反馈，确实是个 Bug，下个版本会修复此问题。
临时解决办法：

- 导出配置文件，在配置文件中修改；
- git-scm.com 会强制 https 所以这里直接写 https 即可；

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

解决了此问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
