### ISSUE TITLE
notion

### ISSUE THREAD

**Issue by SgAriFool** [Kenshin/simpread#4243]
notion忽然只能保存文章的标题，内容完全没有了，以前可以正常保存

**Comment by SgAriFool** [comment]
notion的保存忽然只能保存题目，内容完全没有，以前可以正常保存

**Comment by Kenshin** [comment]
嗨，关于此问题的说明 https://github.com/Kenshin/simpread/issues/4237#issuecomment-1192226010

请通过 #4237 讨论，我关闭这个 URL 了。

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
