### ISSUE TITLE
已登录，依然无法正常使用，重装也是这样，不知道是什么原因

### ISSUE THREAD

**Issue by itangqiao** [Kenshin/simpread#4248]
<img width="2555" alt="2022-07-24 08 45 34" src="https://user-images.githubusercontent.com/44393379/180627560-602ebadb-0837-4db6-8839-708c87f9e8ab.png">

**Comment by Kenshin** [comment]
emmm 感觉是被 CSS 污染了，你把这个稍后读删除。

另外，这个稍后读也并不是使用简悦。

**Comment by itangqiao** [comment]
环境：Edge最新版，Chrome都试过，Mac OS最新系统，M1 Max
关闭所有插件，InPrivate模式，重装插件，Chrome商店和Edge商店里的都试过，很多网页也试过都是这样，一模一样的情况。

**Comment by Kenshin** [comment]
emmm 我大概知道是什么问题了。

你试试访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/fontawesome.min.css 能否正常打开？

**Comment by itangqiao** [comment]
这个链接确实打不开~ 然后呢~

**Comment by Kenshin** [comment]
1. 你的截图其实没有问题。
2. 稍后读有部分 icon 需要能成功打开 https://github.com/Kenshin/simpread/issues/4248#issuecomment-1193240595 提到的链接。

解决方案 https://github.com/Kenshin/simpread/discussions/2906

**Comment by itangqiao** [comment]
不知道这个cdn是啥情况，确实访问不了，用的DNS也是阿里的233，有线无线都试了，hosts清除了cdnjs.cloudflare.com，也还是访问不了~😔 笔记本的无线的连接访问是正常的

**Comment by Kenshin** [comment]
你可以试试更换其它的 CDN 看看能否改善。

问下，你是什么地方的什么网络环境？之前有部分成都用户遇到过类似的问题，但都通过上面的链接解决了，已经很久没有人提了这个情况了。

**Comment by itangqiao** [comment]
深圳电信1000M，有线走的OpenWrt旁路由(白群晖虚拟机-软路由)，无线WiFi 走的一个普通的荣耀硬路由，挂/不挂梯子都试了。

**Comment by itangqiao** [comment]
挂梯子可以，但是要全局才行，因为这个cdn不在规则里面😌 真是奇怪了

**Comment by itangqiao** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/44393379/180632521-583871bb-726e-4525-957e-0859b81adcc0.png">
不太明白，为啥掘金总是这样一张空图~

**Comment by Kenshin** [comment]
> 挂梯子可以，但是要全局才行，因为这个cdn不在规则里面😌 真是奇怪了

应该不用全局。反正搞定就好 😂

> https://github.com/Kenshin/simpread/issues/4248#issuecomment-1193246061

这个问题的话，建议在原页面进入阅读模式后标注，但你更建议使用 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 方案，一劳永逸，且简悦的很多扩展功能都跟此功能有关。

**Comment by itangqiao** [comment]
欧克，能跑就行
嗯 我试试知识库，感谢大佬的耐心解读~

**Comment by Kenshin** [comment]
小事情。

稍后读解析方案对付一般的页面还行。所以最好的方式还是我说的 知识库 方案。

**Comment by Kenshin** [comment]
我关闭这个 Issues 了，你可以随时继续在这里跟我讨论。

***

以下内容为手动输入，非自动完成。😂

要是有可能对话，进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图，请帮忙五星 + 好评  😏 这是对简悦最大的帮助了。

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by itangqiao** [comment]
![image](https://user-images.githubusercontent.com/44393379/180735950-25ecc9c6-dd28-461a-8e1c-4a65def9f961.png)
知识库建立好了，但是遇见了 稍后读不加载本地html文件的问题，我该勾选的地方，我检查了好几遍都勾上了的。

**Comment by itangqiao** [comment]
![image](https://user-images.githubusercontent.com/44393379/180736658-b1e162f9-a10d-409a-a63c-f22593630106.png)
始终显示在线链接

**Comment by Kenshin** [comment]
直接访问 http://localhost:7026/reading/index 看看是什么内容？

**Comment by Kenshin** [comment]
我知道问题了

看 https://user-images.githubusercontent.com/44393379/180735950-25ecc9c6-dd28-461a-8e1c-4a65def9f961.png output 名字错了。
