### ISSUE TITLE
关于同步助手命令行的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4249]
via https://github.com/j1g5awi/simpread-sync/issues/1#issuecomment-1193140487

***

> https://github.com/j1g5awi/simpread-sync/pkgs/container/simpread-sync
> 
> 你可以测试下，仓库下提供 docker-compose.yml，请修改 `command: /usr/bin/simpread-sync --sync-path /data` 处进行配置。

刚才在Win上的测试环境中简单测试了下：
- 开启容器后，需要去简悦的设置面板同步下手动同步浏览器配置文件到同步助手容器内
- 点击单独的导出动作，可以正常的输出文件
- 自动化任务不生效：
  ![image](https://user-images.githubusercontent.com/21117946/180610657-f4cb458d-9379-440b-abad-b3584a83dffb.png)
  设置了加入稍后读后自动触发自动导出的自动化任务，添加任意文章到稍后读后，同步助手并没有自动导出，只是同步了浏览器的配置文件
  ```
  simpread-sync-simpread-sync-1 | 2022/07/23 15:09:10 sync config from browser
  ```
  将自动化任务设置为手动触发后，手动在动作中触发该自动化任务，可以自动导出
  ```
  simpread-sync-simpread-sync-1 | 2022/07/23 15:07:26 save file: 成功脱坑群晖入坑威联通.md
  simpread-sync-simpread-sync-1 | 2022/07/23 15:07:28 save file: 成功脱坑群晖入坑威联通.html
  ```
- 简悦无法设置同步助手的地址，待会我去简悦仓库那边开个FR的issue

**Comment by Kenshin** [comment]
@jimlee2002

嗨，我把 Issues 转移到这里了，在这里讨论吧。

> 自动化任务不生效：

你需要使用 `d d` 或右键加入稍后读后才能触发自动化。

**Comment by jimlee2002** [comment]
自动化没问题了，感谢，这条issue可以关了

**Comment by Kenshin** [comment]
okay 没问题就好。
