### ISSUE TITLE
NOTION导入失败，持续显示正在保存到notion

### ISSUE THREAD

**Issue by sherlockmj** [Kenshin/simpread#4250]
![image](https://user-images.githubusercontent.com/32857102/180629959-28acc75d-e558-4a5e-8ee0-8e5ec1e6610b.png)
持续了约有1小时，并没有反应。
可以授权到NOTION并且指定保存到特定界面。
大佬帮忙看看

**Comment by Kenshin** [comment]
嗨，问题原因和解决方案看这里 https://github.com/Kenshin/simpread/issues/4237

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/issues/4237#issuecomment-1193078226

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
