### ISSUE TITLE
使用“插件管理器”后，每次进入阅读模式提示 “第一次使用阅读模式，建议看看新手帮助” 的提示横幅

### ISSUE THREAD

**Issue by Stark-X** [Kenshin/simpread#4254]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Windows 10

- 浏览器版本 Edge 103.0.1264.71

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

使用“插件管理器”后，每次进入阅读模式提示 “第一次使用阅读模式，建议看看新手帮助” 的提示横幅，点击“老司机”后，下一次进入也一样会提示

**Comment by Stark-X** [comment]
#4221

**Comment by Kenshin** [comment]
emmm 我没有复现。

当点击「老司机」后，重启浏览器后依旧提示吗？

**Comment by Stark-X** [comment]
这两天没再出现了，不确定是不是因为我之前重启过一次浏览器

如果再出现问题，我再开启

**Comment by Kenshin** [comment]
okay

**Comment by Xm798** [comment]
出现了同样的问题，每次进入阅读模式均会弹出横幅，已重启浏览器，无法解决。

<img width="573" alt="image" src="https://user-images.githubusercontent.com/48074861/181672013-7d0ad41b-2f96-464e-b8cc-50e8edaf1e96.png">

**Comment by Kenshin** [comment]
> 出现了同样的问题，每次进入阅读模式均会弹出横幅，已重启浏览器，无法解决。
> 
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/48074861/181672013-7d0ad41b-2f96-464e-b8cc-50e8edaf1e96.png">

点击「老司机」也是如此？如果是的话，点击后「老司机」后，打开插件管理器，点击**保存插件的配置到本地**。

**Comment by Xm798** [comment]
> > 出现了同样的问题，每次进入阅读模式均会弹出横幅，已重启浏览器，无法解决。
> > <img alt="image" width="573" src="https://user-images.githubusercontent.com/48074861/181672013-7d0ad41b-2f96-464e-b8cc-50e8edaf1e96.png">
> 
> 点击「老司机」也是如此？如果是的话，点击后「老司机」后，打开插件管理器，点击**保存插件的配置到本地**。

点击老司机，打开插件管理器点击保存插件的配置到本地后（坚果云提示文件更新成功），重启浏览器，再次进入阅读模式依然会弹出横幅。前两天还没有这个问题，今天突然出现了。

**Comment by q609464692** [comment]
+1

**Comment by q609464692** [comment]
操作系统 Windows 11

浏览器版本 Edge 115.0.1851.0 (正式版本) dev (64 位)

简悦版本 2.2.0.520

按上述方法试了都不行，使用chrome Dev版有同样的问题，且问题发生在**自动进入阅读模式**。
当使用aa手动进入阅读模式时则不会弹提示

**Comment by Kenshin** [comment]
@q609464692 

嗨，你应该使用了同步助手了吧？如果是的话，请使用 [此方式](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%E4%BF%AE%E5%A4%8D%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 修复这个问题。

**Comment by q609464692** [comment]
> @q609464692
> 
> 嗨，你应该使用了同步助手了吧？如果是的话，请使用 [此方式](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%E4%BF%AE%E5%A4%8D%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 修复这个问题。

Hi 照此方式已解决，谢谢

**Comment by Kenshin** [comment]
@q609464692 

哈，解决就好。
