### ISSUE TITLE
简悦+logseq 知识库同步服务 无annotate Markdown文件

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4261]
### Discussed in https://github.com/Kenshin/simpread/discussions/4259

<div type='discussions-op-text'>

<sup>Originally posted by **hmaccelerate** July 26, 2022</sup>
按照https://sspai.com/post/72022 这个教程，我本地知识库文件夹里没有只有标注的markdown文件，麻烦看看是怎么回事？谢谢！
@Kenshin 
![image](https://user-images.githubusercontent.com/8213368/180904226-8d17b187-76a6-436c-919e-f1297110106f.png)
</div>

**Comment by Kenshin** [comment]
@hmaccelerate

我帮你建立一个新的 Issues 来讨论这个问题

看起来应该是知识库没有设置成功，对比下 https://www.yuque.com/kenshin/simpread/wkswh7 与你的自己的有什么区别。

**Comment by hmaccelerate** [comment]
我的配置：
![image](https://user-images.githubusercontent.com/8213368/180905389-9fbd6008-5872-4085-8864-bedf2ef89b3e.png)
![image](https://user-images.githubusercontent.com/8213368/180905432-19a52581-5796-4235-a1ba-91c5e4d6a076.png)
![image](https://user-images.githubusercontent.com/8213368/180905475-303559fb-0937-4b6e-81f1-f5aa9341c4e0.png)

**Comment by hmaccelerate** [comment]
> @hmaccelerate
> 
> 我帮你建立一个新的 Issues 来讨论这个问题
> 
> 看起来应该是知识库没有设置成功，对比下 https://www.yuque.com/kenshin/simpread/wkswh7 与你的自己的有什么区别。

谢谢大佬，我看看

**Comment by hmaccelerate** [comment]
> @hmaccelerate
> 
> 我帮你建立一个新的 Issues 来讨论这个问题
> 
> 看起来应该是知识库没有设置成功，对比下 https://www.yuque.com/kenshin/simpread/wkswh7 与你的自己的有什么区别。

hi kenshi, 我试了你的教程，还是没有标注的Markdown文件导出。我这里没有配置坚果云，只是想单纯的把网页和标注Markdown文件保存到本地

**Comment by Kenshin** [comment]
你试试多添加几个稍后读再试试。

另外

1. 使用 <kbd>d d</kbd> 加入稍后读，同时会形成自动化导出
2. 然后在标注，会生成标注文件

**Comment by hmaccelerate** [comment]
> 你试试多添加几个稍后读再试试。
> 
> 另外
> 
> 1. 使用 d d 加入稍后读，同时会形成自动化导出
> 2. 然后在标注，会生成标注文件

好的 非常感谢

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
