### ISSUE TITLE
同步助手稍后读快捷键无法正常设置或清空

### ISSUE THREAD

**Issue by Xm798** [Kenshin/simpread#4265]
- 操作系统 **MacOS**

- 简悦版本 **同步助手1.1.2**

**请描述你的问题**

1. 清空同步助手稍后读快捷键并保存后，仍然占用 Command+Shift+N，导致 Chrome 新建无痕窗口不可用，且**同步助手的提示窗口不会到前台显示**，导致完全不知道快捷键已被抢占。
2. 无法设置使用 Option 组合快捷键，会输入特殊字符；无法设置使用 Command 快捷键，会无任何反应，继续按其他键甚至出现了 字母+字母+字母 这种奇怪的不可能实现的快捷键组合。
3. 无法设置使用 Control+Shift+Option+字母 的快捷键组合，字母完全无法识别。

**截图**

### 问题 1 截图

<img width="700" alt="image" src="https://user-images.githubusercontent.com/48074861/181061283-b27e0c4b-af1f-4b4b-8212-fd42073e0c9c.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/48074861/181061325-d877c643-d6f0-4b0f-b66a-49ce695dacab.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/48074861/181061567-d4c0cbab-56e1-48d3-a1ce-bfd03e72f44a.png">

### 问题2截图：

<img width="700" alt="image" src="https://user-images.githubusercontent.com/48074861/181062511-da917a0d-3880-4076-877e-27627784d016.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/48074861/181062601-19e2d092-3045-453a-ad85-b3b39292dcf8.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/48074861/181063179-94618d4f-657e-4011-8cbe-593067d9e4c3.png">

**Comment by Xm798** [comment]
重启同步助手后，问题1消失。但既然必须要重启才可以设置快捷键，就不该弹出提示“快捷键设置成功”，而是应该提示“请重启同步助手”，且其他应用在不重启的情况下均可正常修改快捷键，因此重启应该不是必要选项。

**Comment by Kenshin** [comment]
okay

我先记录下这个现象，修复后会在这里通知你~

**Comment by crazythq** [comment]
+1！
请问能否增加一个快捷键开关的选项，我的快捷键已经够多了，会有冲突。。

**Comment by Kenshin** [comment]
> +1！ 请问能否增加一个快捷键开关的选项，我的快捷键已经够多了，会有冲突。。

如果你指的是扩展端的话，当然支持，细节可以 [看这里](http://ksria.com/simpread/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE) 。

**Comment by crazythq** [comment]
> > +1！ 请问能否增加一个快捷键开关的选项，我的快捷键已经够多了，会有冲突。。
> 
> 如果你指的是扩展端的话，当然支持，细节可以 [看这里](http://ksria.com/simpread/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE) 。

不，我指的是同步助手(win64)

**Comment by Kenshin** [comment]
@crazythq 

考虑下个版本实现。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [禁用快捷键](https://simpread.pro/docs/#/稍后读快捷键?id=禁用快捷键)。

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
