### ISSUE TITLE
保存到notion，getTasks显示notFound

### ISSUE THREAD

**Issue by gavinup** [Kenshin/simpread#4267]
![image](https://user-images.githubusercontent.com/30076575/181139177-2025125c-e723-430e-8596-db2dbf10a5ac.png)

保存到notion，一直卡在这里

**Comment by Kenshin** [comment]
嗨，问题原因和解决方案看这里 #4237 解决方案 https://github.com/Kenshin/simpread/issues/4237#issuecomment-1193078226

**Comment by Kenshin** [comment]
另外，关于这个问题我在简悦的各种渠道通知了，甚至于选项页 → 右下角的消息中心都有提示。

**Comment by Kenshin** [comment]
嗨

Notion 已经彻底解决了[【因标题含有 CJK 字符导致导入到 Notion】](https://github.com/Kenshin/simpread/issues/4237)的问题，所以此 Issues 我关闭了。

同时 Notion 辅助增强升级到 1.2.2 也去掉了 1.2.1 版为此设置的功能，请各位升级。

**Comment by Kenshin** [comment]
![Cover](https://user-images.githubusercontent.com/81074/183604683-129f7d27-df72-4958-9e2b-c562e60cba1a.png)

# 视频教程

> 嗨，各位。这是简悦官方推出的一个有声视频教程系列，感谢简悦资深社区用户 @Joel2561 倾情献声，虽然简悦有详尽的图文教程，但为了满足视频用户的需求，特此制作了视频教程。

## 📺 B站

https://www.bilibili.com/video/BV1Ga411P75h

## 📺 知乎视频

https://www.zhihu.com/zvideo/1540303153152438272

## 💡 一点想法

视频教学是非常繁琐且复杂的事情，原本简悦已经有了很多图文教程了，为了满足希望看视频的用户，简悦社区资深用户 Yu jiale 特意为此制作了视频教程。

无论是我还是 Yu jiale 都是第一次制作这种类型的教程，不足之处，望大家理解。

制作教程不易，期间花费的心血就不说了，希望有 B站/知乎 账户的用户，请帮忙三连。🙏

## 📖 文章

上面的视频教程对应的文章 👉 https://zhuanlan.zhihu.com/p/486247311
