### ISSUE TITLE
微博头条文章加入阅读模式白名单无效

### ISSUE THREAD

**Issue by canxer314** [Kenshin/simpread#4268]
以此网址为例
 https://weibo.com/ttarticle/p/show?id=2309404794756122148923&mark_id=999_reallog_mark_ad%3A999%7CWeiboADNatural
![image](https://user-images.githubusercontent.com/4979384/181144791-32402d06-b5cb-4ab2-9d9e-37c09602ea11.png)

白名单中设置
![image](https://user-images.githubusercontent.com/4979384/181144749-91cc37d1-3d88-4077-b490-1a6f64a518de.png)

刷新页面后未能生效

**Comment by Kenshin** [comment]
试试 `https://weibo.com/ttarticle/p/show?id=*`

另外，不建议这个页面加入白名单，这个页面可能是动态获取的，加入白名单可能效果不好。

**Comment by canxer314** [comment]
> 试试 `https://weibo.com/ttarticle/p/show?id=*`
> 
> 另外，不建议这个页面加入白名单，这个页面可能是动态获取的，加入白名单可能效果不好。

还是没有生效，很奇怪

**Comment by Kenshin** [comment]
emmm 你看看排除列表有没有 weibo.com 之类的。

**Comment by canxer314** [comment]
> emmm 你看看排除列表有没有 weibo.com 之类的。

woc我终于找到了，在默认的延迟加载列表里，关掉就好了😭

**Comment by Kenshin** [comment]
哈哈，原来如此。
