### ISSUE TITLE
无法导入obsidian，也无法使用md+assets

### ISSUE THREAD

**Issue by kidwithsword** [Kenshin/simpread#4273]
![image](https://user-images.githubusercontent.com/71314792/181191976-6a0b6dc5-3800-409d-bef6-b9d29bac29d0.png)

**Comment by Kenshin** [comment]
安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 

如果无法安装插件或没有插件触发器的话，使用 https://github.com/Kenshin/simpread/discussions/4221 安装

**Comment by kidwithsword** [comment]
感谢回答，我尝试了别的网页，确实是标题的原因。但是这个插件我无法安装，通过4221的插件管理器也无法安装……

**Comment by Kenshin** [comment]
哦，你是不是加了稍后读？

如果是已经加入稍后读的话，标题需要在稍后读修改。

另外，成功安装完这个插件后，标题会有变化，你可以确认下。

**Comment by kidwithsword** [comment]
你好，我没有添加稍后读。现在的问题是无法安装这个改标题的插件，通过插件管理插件也无法安装。

发件人: Kenshin Wang ***@***.***>
发送时间: 2022年8月3日 17:13
收件人: Kenshin/simpread ***@***.***>
抄送: kidwithsword ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 无法导入obsidian，也无法使用md+assets (Issue #4273)


哦，你是不是加了稍后读？

如果是已经加入稍后读的话，标题需要在稍后读修改。

另外，成功安装完这个插件后，标题会有变化，你可以确认下。

―

**Comment by Kenshin** [comment]
1. 关闭自动同步
2. 重启浏览器
3. 安装这个插件
4. 重启浏览器

如果没问题的话，使用插件管理器，按下图所示操作，然后重启浏览器

![image](https://user-images.githubusercontent.com/81074/183369005-70f71f5e-c969-427b-884f-c0d8f9bc8ab4.png)

如果还是不行，就在步骤2和3之间，加上清除全部插件。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by kidwithsword** [comment]
Cool


发件人: Kenshin Wang ***@***.***>
发送时间: 2022年10月11日 15:01
收件人: Kenshin/simpread ***@***.***>
抄送: kidwithsword ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 无法导入obsidian，也无法使用md+assets (Issue #4273)


嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：Obsidan 配置库。

细节请看下面。

________________________________

[img]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F093ac4351ff1633e5a52a8277978ec67ab9921093f65c019c6231cfb25cb8719%2F68747470733a2f2f696d67732e7a68756261692e6c6f76652f63363236363738666636623634646431616339646664616536636636643138382e706e67&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577626939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hugoc1eCzJzJi0oQkCuDPEf8XEHUPfqSqpuM8I8iBzg%3D&reserved=0>

针对新用户的一步到位的 Obsdian 配置库。

🗂 配置库

简悦 · 配置库<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yuque.com%2Fkenshin%2Fsimpread%2Fds8zk0&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577626939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yl%2BKeh7jx3RkrOtuirxBs9D7mhFBrqbJlyPlrCMhYpU%3D&reserved=0> 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

📚 Obsidian 配置库
📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

📖 区别

[img]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F56dd1b1346d73b07f4ef51c044b2cffba62654a0e9fc6facde3165f2b7a24605%2F68747470733a2f2f696d67732e7a68756261692e6c6f76652f66346135316438653866623434303132383162303766383262663062633764312e706e67&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577626939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=boJ2nzsswXKRjGo%2B1Km7BlaZiXyqEEBlLHm00SeYd9E%3D&reserved=0>

📘 极速版

🔗 Github<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenshin%2Fsimpread-configs%2Fblob%2Fmain%2Fobsidian%40little%2FGetting%2520Started.md&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zEl4U%2BuWJuWGv4P14nKAOsVKbj9nxttXLk4s6XzLf4U%3D&reserved=0> | 语雀<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yuque.com%2Fkenshin%2Fsimpread%2Fxkuecp&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZpL41Gj5PfHP%2ByXtNLdXKbpy6Jdn4EtkR7uC7HGgaAY%3D&reserved=0>

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

📙 基础版

🔗 Github<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenshin%2Fsimpread-configs%2Fblob%2Fmain%2Fobsidian%40localrestapi%2FGetting%2520Started.md&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iAnHkaJtCMf8%2FNXIl%2Fji5J909VoTYeaHmJO1q4X%2FtZk%3D&reserved=0> | 语雀<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yuque.com%2Fkenshin%2Fsimpread%2Fcg33gh&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KaVZXCUu4kHpj7fkPaCM5UUT2GAJd297Qs9J60BTMmk%3D&reserved=0>

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

📗 高级版

🔗 Github<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenshin%2Fsimpread-configs%2Fblob%2Fmain%2Fobsidian%40sync%2FGetting%2520Started.md&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hTmuJY6DfVjPjW8Z%2B%2B%2BcaLZt2KgRaOFbvR6ZrFJci9I%3D&reserved=0> | 语雀<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yuque.com%2Fkenshin%2Fsimpread%2Fwq35mh&data=05%7C01%7C%7Cce8cd15dd3874bd65c2408daab56564f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638010684577783151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K4rjWlMef1H86wDbheZQjE%2BrP8aQqd3CRgjYuy31L8g%3D&reserved=0>

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
