### ISSUE TITLE
每次更改完进入阅读模式还是显示最右侧的黑色主题

### ISSUE THREAD

**Issue by lovelylion-jojo** [Kenshin/simpread#4278]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win64**

- 浏览器版本 **Version 4.3.9.248 (Official Build) (64-bit) (Chromium 86.0.4240.198)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
随便进入一个页面 e.g. https://sspai.com/post/69972 进入阅读模式，然后按下图更改，**更改后重启浏览器**。

![image](https://user-images.githubusercontent.com/81074/181406553-a261503b-bf22-4a88-b653-43e0c0a098ce.png)
