### ISSUE TITLE
稍后读界面图标不显示

### ISSUE THREAD

**Issue by thzcgo** [Kenshin/simpread#4279]
发生问题的环境

操作系统 Windows11

浏览器版本 Microsoft Edge  103.0.1264.71 (正式版本) (64 位)

简悦版本 2.2.0.520

![image](https://user-images.githubusercontent.com/68227269/181412610-46b2c534-e7c4-41b1-9806-a258862428ce.png)

发现一些报错，不知是否与这里有关
![image](https://user-images.githubusercontent.com/68227269/181413885-c54747cc-0677-4a68-b6b6-7830eba3292e.png)

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/2906
