### ISSUE TITLE
同步助手 ENOENT 無法消除

### ISSUE THREAD

**Issue by turboted** [Kenshin/simpread#4283]
MacOS 12.5
Chrome 103.0.5060.134
同步助手 1.1.1.702
簡悅版本 2.2.0
NG網址 https://aithinker.blog.csdn.net/article/details/117319590
OK網址 https://aithinker.blog.csdn.net/article/details/117299812

進入NG網址後，使用導入md + assets 到 obsidian 報錯如附圖，按下[點擊提交問題]，此button 不會消失，造成 同步助手無法使用進入OK網址後，使用導入md + assets 到 obsidian 使用正常，可以保存

**Comment by Kenshin** [comment]
安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 后看看能否解决。

**Comment by turboted** [comment]
可以了，不報錯了，非常感謝
另外想問一下，導入md + assets 到 obsidian 可以增加快捷鍵嗎 ?

**Comment by Kenshin** [comment]
可以的，几乎每个插件都支持快捷，并指出了每个插件的快捷键。

![image](https://user-images.githubusercontent.com/81074/181682614-1be9a486-c02e-467f-a7ba-4977e1679f5a.png)

**Comment by turboted** [comment]
可以了，感谢

**Comment by Kenshin** [comment]
哈哈，小事情。

***

要是有可能的话，请帮忙给简悦五星 + 好评，这样才是对简悦最大的帮助。

请进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 

通过下图  😏 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
