### ISSUE TITLE
同步助手1.1.2在mac上无法安装

### ISSUE THREAD

**Issue by jumbotponq** [Kenshin/simpread#4284]
提示“无法打开简悦，同步助手.app。因为无法验证开发者
macOS无法验证此App不包含恶意软件

**Comment by Kenshin** [comment]
只要是简悦指定的下载地址下载就没问题。
随便 Google 下，就能找到解决方案 https://www.macjb.com/article/229012.html

**Comment by jumbotponq** [comment]
> 只要是简悦指定的下载地址下载就没问题。 随便 Google 下，就能找到解决方案 https://www.macjb.com/article/229012.html

我是在官网指定的百度网盘下载的啊。
