### ISSUE TITLE
添加标记备注的字体

### ISSUE THREAD

**Issue by lumen1201** [Kenshin/simpread#4286]
![Screenshot (13)](https://user-images.githubusercontent.com/110223483/181708870-2279ff43-72fd-4deb-b28d-3025c46139e4.png)

**Comment by Kenshin** [comment]
可以用 CSS 解决，明天告诉你。

**Comment by Kenshin** [comment]
```
dialog-content * {
    text-shadow: none!important;
}
```

随便进入一个阅读模式，安装下图设置

![Uploading image.png…]()
