### ISSUE TITLE
只能搜文章标题有些局限了。能不能再加一个搜索文章内容的功能？

### ISSUE THREAD

**Issue by lumen1201** [Kenshin/simpread#4288]

**Comment by Kenshin** [comment]
可以的，看下 [这里的说明](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80?id=%e6%94%af%e6%8c%81%e5%a4%9a%e7%a7%8d%e6%a3%80%e7%b4%a2%e6%96%b9%e5%bc%8f)。
