### ISSUE TITLE
加了标签后，稍后读里并没有出现任何标签，反复试了好几次都是这样

### ISSUE THREAD

**Issue by lumen1201** [Kenshin/simpread#4289]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by lumen1201** [comment]
备注可以加，但是标签加不上

**Comment by Kenshin** [comment]
肯定是没问题的，看下图的提示

![image](https://user-images.githubusercontent.com/81074/181756315-0e51107f-7181-42c2-a698-e2495a968a60.png)
