### ISSUE TITLE
更改字体大小之后，链接文字不会更改

### ISSUE THREAD

**Issue by FrankSFLYS** [Kenshin/simpread#429]
我将字体大小设置得比较大，但是链接文字不会同步更改，如图所示
![snipaste_2018-12-01_18-38-58](https://user-images.githubusercontent.com/10843159/49327178-b678bc00-f598-11e8-82a3-5f929e4e3e2b.png)
![image](https://user-images.githubusercontent.com/10843159/49327181-c2647e00-f598-11e8-8914-e64d5f7a0ebe.png)

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

由于使用了 新的词法分析引擎，所以此问题应该得到了解决，如仍有问题的话，请重新开启此问题。
