### ISSUE TITLE
阅读模式下可否只标注不解析网页数据？

### ISSUE THREAD

**Issue by Shadow-None** [Kenshin/simpread#4293]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS

- 浏览器版本 Chrome 103.0.5060.134 (Official Build) (x86_64)

- 简悦版本 **2.2.0**

- 发生问题的地址 https://lilianweng.github.io/posts/2021-07-11-diffusion-models/

**请描述你的问题**

上述网址无法解析latex，所以在想是否存在开关可以控制 阅读模式 下**不对网页内容进行解析**。比如可以对这个网址不进行内容解析，就**如同 Hypothesis 一样只保留标注功能**。

**Comment by Kenshin** [comment]
不可以的，简悦的标注是建立在有深度阅读的基础上，如果只是标注某些内容的话，可以有很多其它工具，如你所说的 Hypothesis 。
