### ISSUE TITLE
代码显示不正常，行号会分离出来

### ISSUE THREAD

**Issue by lovertechnology** [Kenshin/simpread#4297]
网页：https://interviewguide.cn/notes/03-hunting_job/02-interview/01-01-01-%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html
![image](https://user-images.githubusercontent.com/50872586/181901066-00063b54-cf03-4bc1-b89f-2a65561534e7.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，简悦对代码段的识别确实有些问题，因为代码段的高亮方案太多了，很难有统一方案。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
