### ISSUE TITLE
后台服务器出现了问题 点击重试

### ISSUE THREAD

**Issue by Aprix3858** [Kenshin/simpread#4298]
如图 输入licence后
![image](https://user-images.githubusercontent.com/103914941/181906067-8d60c126-1299-415d-b321-0b71b5a1cc44.png)

**Comment by Kenshin** [comment]
嗨，这是你的设置造成的，点击红条会告诉你如何设置。

**Comment by Aprix3858** [comment]
Read







------------------ 原始邮件 ------------------
发件人: Kenshin Wang ***@***.***&gt;
发送时间: 2022年7月30日 19:01
收件人: Kenshin/simpread ***@***.***&gt;
抄送: Aprix3858 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Kenshin/simpread] 后台服务器出现了问题 点击重试 (Issue #4298)





 
Closed #4298 as completed.
