### ISSUE TITLE
求适配

### ISSUE THREAD

**Issue by DullSky** [Kenshin/simpread#43]
求适配www.edaoe.com，里面的书单里面的内容很不错

**Comment by Kenshin** [comment]
没问题，但我在休假，回去后再做适配。

**Comment by DullSky** [comment]
好的，谢谢，谢谢

**Comment by airycanon** [comment]
我已经提交了一个 PR，适配了这个站点。 #44

**Comment by Kenshin** [comment]
@airycanon
感谢提交 pr，回去后 merge 👍

**Comment by Kenshin** [comment]
@DullSky @airycanon 

已添加，请使用 [方式](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%85%B3%E4%BA%8E%E6%9B%B4%E6%96%B0) 更新。
