### ISSUE TITLE
目录的存在导致部分文字复制不成功，紧挨目录的文字无法选中

### ISSUE THREAD

**Issue by ERTUPO** [Kenshin/simpread#430]
![2018-12-3 10-13-51](https://user-images.githubusercontent.com/38196065/49349229-aff75b00-f6e4-11e8-889a-4818a02490e6.png)

![tim 20181203101621](https://user-images.githubusercontent.com/38196065/49349284-e339ea00-f6e4-11e8-9fea-b71edcd67f42.png)

目录也会被选中
一般往上选应该选择上面的文字对吧

**Comment by Kenshin** [comment]
emmm 这是个问题，我想想看能否解决掉，谢谢反馈！

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

我在清理一些 issues 这个问题可以插件来解决 https://simpread.ksria.cn/plugins/details/UsayAKSuwe

如仍存在此问题，请重新开启。
