### ISSUE TITLE
导出PDF显示“服务调用失败”

### ISSUE THREAD

**Issue by JonnyH5** [Kenshin/simpread#4300]
- 操作系统 **MacOS**

- 浏览器版本 **Edge Version 103.0.1264.77 (Official build) (arm64)**

- 简悦版本 **2.2.0**  （同步助手版本 1.1.2）

- 问题：尝试使用导出PDF功能，始终提示我“服务调用失败”。尝试各种办法均失败，唯独调用Ctrl+P是可以正常使用的。

**截图**
<img width="469" alt="image" src="https://user-images.githubusercontent.com/110314453/182005393-9fb3d192-e690-4da4-8cf3-0acff7f98cfe.png">

**Comment by JonnyH5** [comment]
所有网页下，导出PDF服务均失败。

**Comment by Saber813** [comment]
一样的, 昨天晚上还可以 我是

**Comment by Kenshin** [comment]
试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件。

还有，建议使用 https://github.com/Kenshin/simpread/discussions/3887 方案。

**Comment by Kenshin** [comment]
@Saber813 

跟哪天没关系... 这些都是本地功能，不是网络功能。

**Comment by JonnyH5** [comment]
> 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/110314453/182011873-e193a1cf-cf5e-427d-a83b-7bf739d3abbc.png">

两个插件完全之前就已经完成安装了，刚刚尝试3887方案，还是不成功

**Comment by JonnyH5** [comment]
解决成功了！说来惭愧……应该是中间我尝试重置配置来解决之前的问题，结果忘记再次绑定账号导致的问题，目前我尝试了几个网页，一切正常！十分感谢！！

**Comment by Kenshin** [comment]
哈哈，小事情，搞定就好。

***

要是有可能的话，请帮忙给简悦五星 + 好评，这样才是对简悦最大的帮助。

请进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 

通过下图  😏 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
