### ISSUE TITLE
有关Logseq同步助手中的模板2.0无法生效的问题

### ISSUE THREAD

**Issue by sokouu** [Kenshin/simpread#4302]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统  Windows 

- 浏览器版本  Chrome 103.0.5060.134

- 简悦版本 2.2.0

- 发生问题的地址[<https://taizihuang.github.io/wmyblog/html/108908611.html>]

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

按照 Logseq SimpRead Sync 一站式标注及管理解决方案 一文的设置, 打开扩展的定制导出选项, 导出内容为图一(填入模板2.0的官方Logseq标注模板). 关闭扩展的定制导出选项, 导出内容为图二. 

初步判断同步助手的Logseq导出模板没有生效, 因此生成的标注是按照模板1.0的格式, 没有颜色. 但使用 Logseq 设置项 中的 生成全部按钮, 是可以正常生成模板2.0的标注的. 如图三与图四.

目前使用 导入到obsidian & Markdown 模板辅助增强 & 自动化辅助增强 来进行替代解决.

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![tmpA467](https://user-images.githubusercontent.com/36170508/182015104-a72dd0c4-baf2-4e0b-9c58-6339c864184b.png)
![tmp68D](https://user-images.githubusercontent.com/36170508/182015115-6cdaccbb-2605-415d-a21c-486c3a4508e2.png)
![tmpCFE5](https://user-images.githubusercontent.com/36170508/182015036-aeac00f8-e808-47ef-8575-8ad9fad09d0f.png)
![tmp9D60](https://user-images.githubusercontent.com/36170508/182015141-20006c77-8039-4408-b92c-a2914432b4da.png)

**Comment by Kenshin** [comment]
https://user-images.githubusercontent.com/36170508/182015036-aeac00f8-e808-47ef-8575-8ad9fad09d0f.png

这个选项是在 Logseq 侧栏打开的吧？如果在这个位置设置的话，需要在 Logseq 右侧编辑标注，如下图

![img](https://user-images.githubusercontent.com/81074/175770233-7f807907-92ae-46e7-afb5-615890927a51.png)

如果在浏览器 → 简悦的阅读模式下也实现同样效果的话，需要安装 https://github.com/Kenshin/simpread/discussions/3775

**Comment by sokouu** [comment]
了解, 我的目的就是需要在浏览器的阅读模式下实现, 但我logseq用的是Markdown, 是否就无法使用org-mode了?

**Comment by Kenshin** [comment]
> 了解, 我的目的就是需要在浏览器的阅读模式下实现, 但我logseq用的是Markdown, 是否就无法使用org-mode了?

是的，我会考虑升级 org-mode 让它跟 Logseq SimpRead Sync 具有一样的功能。

**Comment by sokouu** [comment]
好的, 期待!

**Comment by Kenshin** [comment]
我需要开启这个 issues 😁

**Comment by Kenshin** [comment]
嗨，这个 [插件](https://github.com/Kenshin/simpread/discussions/4321) 发布了，跟 [导出 org-mode](https://github.com/Kenshin/simpread/discussions/3775) 一样的逻辑，只是导出为 `.md` 文件。

你可以直接使用这个插件了，而不需要使用 导入到 Obsidian。

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
