### ISSUE TITLE
请问插件触发器，插件选项页没有出现是什么原因？

### ISSUE THREAD

**Issue by Lusenlan** [Kenshin/simpread#4304]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨， 每个插件的说明都包含了这个问题的解决方案 https://github.com/Kenshin/simpread/discussions/2342

**Comment by Lusenlan** [comment]
现在token和ID都配置完成了，就是无法实现导出Notion增强功能，无法把图标，标签一同导入到Notion指定的那个Page那里



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年7月31日(周日) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 请问插件触发器，插件选项页没有出现是什么原因？ (Issue #4304)




 
Closed #4304 as completed.

**Comment by Kenshin** [comment]
截图详细说明你的问题。

**Comment by Lusenlan** [comment]
---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年8月3日(周三) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 请问插件触发器，插件选项页没有出现是什么原因？ (Issue #4304)




 
截图详细说明你的问题。

**Comment by Kenshin** [comment]
请不要在 Email 中回复，请进入 https://github.com/Kenshin/simpread/issues/4304 回复，否则我看不了图片。

**Comment by Lusenlan** [comment]
![1abb55716e4f395080d6901cef93e61](https://user-images.githubusercontent.com/104048109/182578264-844e42de-ba03-4e67-9555-2b6ea4f1fa83.jpg)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/182584805-f7ca603d-8bcb-4e2c-a5aa-e8f655e747b8.png)

**Comment by Lusenlan** [comment]
已开启

**Comment by Lusenlan** [comment]
![image](https://user-images.githubusercontent.com/104048109/182598679-3d1c872e-06b5-4df6-b3eb-17c8d2ec9fb1.png)

**Comment by Kenshin** [comment]
确保 https://sspai.com/post/69972 这个没有保存过，然后用这个地址测试。

**Comment by Lusenlan** [comment]
![image](https://user-images.githubusercontent.com/104048109/182599596-cb34e6ea-ba5a-4b6a-8cd9-7afb9567a3da.png)

**Comment by Lusenlan** [comment]
![image](https://user-images.githubusercontent.com/104048109/182599795-a38c2e6a-dcc5-4ce0-8b0d-7ce3c970b3bb.png)

**Comment by Lusenlan** [comment]
你好，请问我在github上的截图会被别人看到，我这才想到可能会泄露个人信息，有没有什么方法撤回？



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年8月3日(周三) 晚上7:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 请问插件触发器，插件选项页没有出现是什么原因？ (Issue #4304)




 
确保 https://sspai.com/post/69972 这个没有保存过，然后用这个地址测试。

**Comment by Kenshin** [comment]
我可以帮你删除，但应该没有暴漏任何个人信息。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Lusenlan** [comment]
和notion clipper插件有关吗？



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年8月3日(周三) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 请问插件触发器，插件选项页没有出现是什么原因？ (Issue #4304)




 
我可以帮你删除，但应该没有暴漏任何个人信息。

**Comment by Kenshin** [comment]
> 和notion clipper插件有关吗？

无关

**Comment by Lusenlan** [comment]
好嘞，谢谢



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年8月3日(周三) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 请问插件触发器，插件选项页没有出现是什么原因？ (Issue #4304)




 
我可以帮你删除，但应该没有暴漏任何个人信息。

**Comment by Kenshin** [comment]
小事情~

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
