### ISSUE TITLE
阅读模式下飞书链接里的文章提取不完整。

### ISSUE THREAD

**Issue by lx111lx** [Kenshin/simpread#4305]
RT。 经过试用，飞书的文章通常只能提取前半部分，本人是重度飞书知识库使用者，希望作者能优化飞书相关功能~

**Comment by Kenshin** [comment]
嗨，飞书并不希望可以让它的文档进入阅读模式，所以简悦不会适配它。

比如 Dark mode 也无法在飞书上使用，使用时会有提示。
