### ISSUE TITLE
AMD 同步助手，蓝屏（个例）

### ISSUE THREAD

**Issue by zhangjx007** [Kenshin/simpread#4308]
设备配置：
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	32.0 GB 

华硕天选2plus 

版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎10/‎17
操作系统版本	22000.795

只要一运行同步助手，过一会电脑就蓝屏。

![Snipaste_2022-08-01_14-23-15](https://user-images.githubusercontent.com/110375200/182085762-8f85d98b-2c4b-4435-8708-ff3e23b908e5.png)

**Comment by Kenshin** [comment]
什么版本的同步助手？
建议不要设置自启动，另外看看这个命令行的版本 https://github.com/Kenshin/simpread/discussions/3704

**Comment by zhangjx007** [comment]
> 什么版本的同步助手？ 建议不要设置自启动，另外看看这个命令行的版本 #3704

1.1.2版本
