### ISSUE TITLE
后台服务器出现了问题，点击重试

### ISSUE THREAD

**Issue by Aprix3858** [Kenshin/simpread#4315]
如图 能具体说一下怎么设置吗 或者提供一下🔗链接 内容太多了找不到 按题主说的点击红条没有反应，或者说我红条点错了？不是图片上的红条吗

![image](https://user-images.githubusercontent.com/103914941/182380771-25c01221-6175-4bc9-8a4f-616304b7124f.png)

**Comment by Kenshin** [comment]
看这里的解决方案
