### ISSUE TITLE
为知笔记一直授权失败

### ISSUE THREAD

**Issue by heimi98** [Kenshin/simpread#4318]
为知笔记一直授权失败，怎么解决？使用的是官方的。

**Comment by Kenshin** [comment]
看这个 https://github.com/Kenshin/simpread/discussions/2407 https://github.com/Kenshin/simpread/discussions/2989

**Comment by Kenshin** [comment]
嗨，另外我看你提了好几个 Issues ，如果的相似问题的话，可以在同一个 Issues 提问，即便我 Close 了也能继续讨论。
