### ISSUE TITLE
爱发电续费问题

### ISSUE THREAD

**Issue by lixudong96** [Kenshin/simpread#4323]
我在爱发电购买一次发送了key给我, 我送朋友了.
我自己再续费一次没有发送key

**Comment by lixudong96** [comment]
就是我买两份 , 只给了一个key

**Comment by Kenshin** [comment]
嗨，我看到了你购买两份，只是有一份因为库存没有了所以没有自动给你，但我已经手动给你了，你在爱发电私信查看就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 中午11:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 爱发电续费问题 (Issue #4323)





 
就是我买两份 , 只给了一个key

**Comment by lixudong96** [comment]
> 嗨，我看到了你购买两份，只是有一份因为库存没有了所以没有自动给你，但我已经手动给你了，你在爱发电私信查看就可以了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Kenshin/simpread" ***@***.***&gt;; 发送时间:&nbsp;2022年8月4日(星期四) 中午11:57 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [Kenshin/simpread] 爱发电续费问题 (Issue #4323) 就是我买两份 , 只给了一个key — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的 感谢
