### ISSUE TITLE
简悦插件导入滴答清单时出现大量意义不明标签

### ISSUE THREAD

**Issue by sherlockmj** [Kenshin/simpread#4324]
原文链接https://www.zhihu.com/question/279012198
![image](https://user-images.githubusercontent.com/32857102/182791137-7af6f305-2308-46c4-bf2f-dbb8b8338d7a.png)
![image](https://user-images.githubusercontent.com/32857102/182791171-bc76b520-82c6-4d0e-9526-d81b989c34a2.png)
请问如何规避此类问题

**Comment by Kenshin** [comment]
emmm 确实如此，估计是滴答清单自己的机制，简悦没有做这方面的设置。😂

**Comment by yoghurtdewdew** [comment]
可多个设置/插件 导入滴答清单前 是否自动移除原文中含有#的内容？是直接清除还是在#后加空格防止丢失内容？逻辑有点类似于清除页面链接，这个相当于清除页面标签，就把所有标签都去掉，导入其他地方也会涉及到被打各种标签，这些标签手动清楚起来不太容易 😂
