### ISSUE TITLE
列表元素丢失

### ISSUE THREAD

**Issue by dwSun** [Kenshin/simpread#4325]
https://medium.com/machine-learning-in-practice/my-curated-list-of-ai-and-machine-learning-resources-from-around-the-web-9a97823b8524

上述链接中的 top writers，直接打开阅读模式，会丢失其中的很多列表项目，但是重新高亮就好使了。

**Comment by Kenshin** [comment]
你给出的链接没问题，我就不截图了。

> 上述链接中的 top writers，直接打开阅读模式

你是说 https://medium.com/tag/artificial-intelligence/top-writers 这个链接？如果是的话，这个页面不需要使用阅读模式。
