### ISSUE TITLE
配置完图床插件之后，导出服务只有一个选项（无动作）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4326]
配置完图床插件之后，导出服务只有一个选项（无动作），请问是需要开启什么额外配置才能使用吗？
![图床选项](https://s2.loli.net/2022/08/05/BJ6w1jNAz8d7tVG.jpg)

_Originally posted by @dudukee in https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-3329814_

**Comment by Kenshin** [comment]
@dudukee

点下图的三角没反应吗？

![image](https://user-images.githubusercontent.com/81074/182990439-dc83dd54-69e4-4a58-9b61-e33f7a19991d.png)

**Comment by dudukee** [comment]
@Kenshin 不好意思，我一直没点箭头。一直在尝试点『无动作』区域😂😂😂

**Comment by Kenshin** [comment]
哈哈，没事。

我关闭这个 Issues 了。

***

要是有可能的话，请帮忙五星 + 好评 😏 是对简悦最大的帮助。

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
