### ISSUE TITLE
保存了一些稍后读，再打开同步，之前保存的丢失了

### ISSUE THREAD

**Issue by daizhenzhong** [Kenshin/simpread#4327]
忘了事先开网盘同步的开关，先把一些页面加入了稍后读，后来打开了同步开关，然后之前加入稍后读的丢失了。
有办法找回吗？

**Comment by Kenshin** [comment]
emmm 应该没有办法...

所谓的「丢失」就是因为你读取了旧的本地数据，所以它会覆盖浏览器的新数据。
