### ISSUE TITLE
知乎的插件的配色疑问

### ISSUE THREAD

**Issue by zhang9192** [Kenshin/simpread#4328]
想问下我安装了知乎的插件，但是每次打开知乎的阅读模式，配色都有问题，需要重新选择一次主题之后，才能正确适应配色，这是为啥？

**Comment by Kenshin** [comment]
1. 知乎插件不会引起颜色问题。
2. 配色问题估计是：你使用了暗色模式造成的，看看 https://github.com/Kenshin/simpread/discussions/3162 能否解决。

另外，请截图告知具体的问题，这样方便判断，除知乎外，其余页面是否也存在类似问题？

**Comment by zhang9192** [comment]
我截图了，请看下，图片 1 是我每次进入论坛后启动插件的默认状态
图片2 是我手动刷新配色后才能正常显示的效果
<img width="1731" alt="Snipaste_2022-08-06_23-19-20" src="https://user-images.githubusercontent.com/52191461/183255338-a027ff3e-bec1-4982-81e5-03b457863ccb.png">
<img width="1710" alt="Snipaste_2022-08-06_23-19-33" src="https://user-images.githubusercontent.com/52191461/183255346-6ecd1586-f742-40de-89a0-0cb36525293d.png">

**Comment by Kenshin** [comment]
其它页面有这个问题吗？

**Comment by zhang9192** [comment]
有 &nbsp;chiphell &nbsp;知乎 &nbsp;都有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kenshin Wang ***@***.***&gt;
发送时间: 2022年8月7日 11:00
收件人: Kenshin/simpread ***@***.***&gt;
抄送: zhang9192 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Kenshin/simpread] 知乎的插件的配色疑问 (Issue #4328)





 
其它页面有这个问题吗？

**Comment by Kenshin** [comment]
你是触屏的 PC 吗？

**Comment by zhang9192** [comment]
不是，MacBook pro M1max




Brian
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月7日(星期天) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 知乎的插件的配色疑问 (Issue #4328)





 
你是触屏的 PC 吗？

**Comment by Kenshin** [comment]
选项页 → 高级设置 → 暗色模式，关闭这个选项。

另外，你的系统使用了暗色模式吗？是全部页面都存在这个问题吗？
