### ISSUE TITLE
保存到印象笔记样式丢失

### ISSUE THREAD

**Issue by zhuoshuai** [Kenshin/simpread#433]
>  现在在网页的「阅读模式下」, 点击保存至印象笔记, 文章的排版在印象笔记里「惨不忍睹」, css样式已经丢失. 而将网页通过「生成临时页面」功能生成「临时网页」, 通过「临时网页」------> chrome的「印象笔记」插件  ------> 「印象笔记」的流程, 在印象笔记的效果就会好很多.

**能不能直接通过 html ---> enml, 而非 html --> markdown  ----> enml**

**Comment by Wilbur-211** [comment]
![1](https://user-images.githubusercontent.com/40929954/51435352-5c4eca00-1cb0-11e9-89b5-ffe870c9c4d0.png)
![2](https://user-images.githubusercontent.com/40929954/51435355-62dd4180-1cb0-11e9-9155-26b73fbb64e6.png)
这个问题我也遇到了，这是少数派的简悦介绍文章，在打开阅读模式下和不打开的情况下，使用Chrome印象笔记剪藏拓展剪藏后，在印象笔记PC端打开的样式对比图

**Comment by Kenshin** [comment]
@Wilbur-211 

抱歉，回复晚了~ 
但我没有遇到你说的问题，这是我在 Web 版的印象笔记查看刚刚发送过去的页面。

![image](https://user-images.githubusercontent.com/81074/51719668-5dec0980-2085-11e9-800b-77034a6863a5.png)
