### ISSUE TITLE
知乎中的公式导入obsidian出现问题

### ISSUE THREAD

**Issue by rickerGG** [Kenshin/simpread#4330]
- 操作系统 Windows11 
- 浏览器版本edge103.0.1264.77
- 简悦版本 2.2.0
- 发生问题的地址https://zhuanlan.zhihu.com/p/517865976
比如这个网页从知乎导入到obsidian中公式显示错误，并且知乎中的公式无法选中并标识
![image](https://user-images.githubusercontent.com/88519512/183247049-94fac425-07e9-4131-a41a-cb98dc5a5fd7.png)
比如这个图片中矩阵显示出来了，但是他的原始代码还显示在下面
并且离线阅读的情况下，之前的公式无法显示
![QQ截图20220806193423](https://user-images.githubusercontent.com/88519512/183247223-b3581c55-f7bd-4c17-862a-1bfbeee89520.png)

**Comment by Kenshin** [comment]
嗨

1. 知乎公式并没有使用的它自己的一套显示逻辑，你可以安装这个插件 https://github.com/Kenshin/simpread/discussions/2861
2. 即便如此，也没法在 Notion 中正常显示，这不是简悦的问题，你可以将安装完插件后的页面导出 Markdown 是可以正常查看的。

**Comment by rickerGG** [comment]
我是刚用这个简悦插件，而且对网页编码也不太了解，我问了群里使用简悦比较早的人，他看了知乎阅读辅助增强，说是转换成base64，要是导出Markdown还需要再转一次码，这个我不太了解，所以他们说向开发者提问一下。麻烦开发者了。
![image](https://user-images.githubusercontent.com/88519512/183247751-57ff9a2a-12b9-4c0f-b6b8-544c6035a138.png)

**Comment by rickerGG** [comment]
群里的人认为出现的问题
![image](https://user-images.githubusercontent.com/88519512/183247850-74da9f0f-48ab-464b-9205-ccce802007eb.png)

**Comment by Kenshin** [comment]
Base64 不需要在转换就能直接在 Markdown 使用…

但能否在 Obsdian 完美查看就是另外的事情，跟简悦无关了。

明天给你截图看下

**Comment by rickerGG** [comment]
好的好的，麻烦您了。但还有个问题，就是我用了知乎增强辅助阅读，但还是没有标注高亮公式，只能标注周围的文字，不知道是不是我的方法错了。
![image](https://user-images.githubusercontent.com/88519512/183250654-3d9d8059-40ae-4b03-ae65-92f0f74c2bd1.png)

**Comment by Kenshin** [comment]
我知道问题了，知乎又改了公式规则... 等我更新插件吧。

**Comment by rickerGG** [comment]
好滴，麻烦你了

**Comment by Kenshin** [comment]
这个问题解决了，解决方案 https://github.com/Kenshin/simpread/issues/4333#issuecomment-1207332617

另外，因为有好几个相似的 Issues，所以讨论的话，也请去 https://github.com/Kenshin/simpread/issues/4333 集中讨论。
