### ISSUE TITLE
知乎公式文章导出markdown

### ISSUE THREAD

**Issue by TheGodOfKing** [Kenshin/simpread#4332]
![image](https://user-images.githubusercontent.com/32014745/183253432-77598325-592c-4bea-915e-1a4a5dead734.png)

**Comment by Kenshin** [comment]
给 URL

**Comment by TheGodOfKing** [comment]
@Kenshin 
https://zhuanlan.zhihu.com/p/517865976
https://zhuanlan.zhihu.com/p/413150417

**Comment by Kenshin** [comment]
试试安装 https://github.com/Kenshin/simpread/discussions/2861 

知乎公式比较特别，不是常规的方案。

**Comment by TheGodOfKing** [comment]
试过了哇，这么多base64图片笔记直接卡死，我群里的粉丝都等这你修复下呢
![image](https://user-images.githubusercontent.com/32014745/183255206-61e9954b-28f4-4e1b-99d2-ba60238c4b1c.png)

**Comment by Kenshin** [comment]
> 我群里的粉丝都等这你修复下呢

什么群？

我研究下这个问题。

**Comment by Kenshin** [comment]
我知道问题了，知乎又改了公式规则... 等我更新插件吧。

**Comment by TheGodOfKing** [comment]
> > 我群里的粉丝都等这你修复下呢
> 
> 什么群？
> 
> 我研究下这个问题。

627574819

**Comment by TheGodOfKing** [comment]
> 我知道问题了，知乎又改了公式规则... 等我更新插件吧。

好的，谢谢，可以给群里粉丝一个答复了
![47C3F2C2CADF0D543FCA84B328410210](https://user-images.githubusercontent.com/32014745/183273391-2d9515d8-64b6-4753-95a2-476a89b5bdd2.gif)

**Comment by Kenshin** [comment]
这个问题解决了，解决方案 https://github.com/Kenshin/simpread/issues/4333#issuecomment-1207332617

另外，因为有好几个相似的 Issues，所以讨论的话，也请去 https://github.com/Kenshin/simpread/issues/4333 集中讨论。

**Comment by Kenshin** [comment]
@TheGodOfKing 

嗨，开学季简悦正在搞一个抽奖活动，要是有可能的话，希望可以在你的群里面发个介绍。 😁

## 抽奖内容

> 简悦目前正在开学季抽奖，奖品包括：FLowUs、画图本、简悦高级账户等，感兴趣的话，可以试试手气，规则很简单 👉 https://simpread.zhubai.love/posts/2177402534795317248

**Comment by TheGodOfKing** [comment]
@Kenshin 好的没问题

**Comment by Kenshin** [comment]
@TheGodOfKing

Cool~
