### ISSUE TITLE
知乎导出md后latex公式代码问题

### ISSUE THREAD

**Issue by nightlye** [Kenshin/simpread#4333]
md中出现重复的代码，并且重复的代码不带$导致无法渲染。
测试文章：https://zhuanlan.zhihu.com/p/517865976
导出的md文件：https://github.com/nightlye/my_test/blob/main/%E6%B5%8B%E8%AF%95.md
![image](https://user-images.githubusercontent.com/53067795/183253789-64dd949c-4122-4754-b02a-c78c73fdfd09.png)

**Comment by Kenshin** [comment]
试试安装 https://github.com/Kenshin/simpread/discussions/2861 

知乎公式比较特别，不是常规的方案。

**Comment by nightlye** [comment]
这个不是很符合需求，最好还是获取带latex代码的md文件就行了。知乎用户量还是很大，这方面可以专门适配一下。

**Comment by Kenshin** [comment]
我知道问题了，知乎又改了公式规则... 等我更新插件吧。

**Comment by Kenshin** [comment]
这个问题解决了：

1. 请更新知乎插件 https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ 

2. 如果使用同步助手无法安装插件或无法升级插件的话，可使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/2342) 安装。

安装新版知乎插件后，按照 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890 给出的方案调整即可解决。

**Comment by nightlye** [comment]
感谢感谢！

**Comment by TheGodOfKing** [comment]
@Kenshin 完美！！！！！！！！！！！！！！
![BMUR(04EJQ)UUKZV2IQKNNR](https://user-images.githubusercontent.com/32014745/183282246-76263cbe-7e72-4624-8844-146d7cd476b8.png)
![40C431AE9A345F73775BAF13F0243A0E](https://user-images.githubusercontent.com/32014745/183282264-0807ebe8-7c35-4691-8ff3-3b3a29c7007f.gif)

**Comment by Kenshin** [comment]
哈哈，这是我在三亚封控里面改的...

不给个忙五星 + 好评 😏 都「对不起」这次整个海南岛全域封控的 事情。😱

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by TheGodOfKing** [comment]
@Kenshin 已给
![image](https://user-images.githubusercontent.com/32014745/183282630-7519ad10-585b-44bb-b872-4372b0433937.png)

**Comment by Kenshin** [comment]
@TheGodOfKing 

小事情，可以在你的群里多帮忙宣传下简悦。

PS：你的群是做什么？

**Comment by TheGodOfKing** [comment]
@Kenshin 没问题，在B站做了视频帮你宣传了
https://www.bilibili.com/video/BV1NV4y1E7e4?share_source=copy_web&vd_source=3f22ba9ed40ee4c59a0d9f4af1a3704e
群是做anki和supermemo记忆卡片的。

**Comment by Kenshin** [comment]
@TheGodOfKing 

Cool 做的不错，已三连。👍 

另外，好奇问问，你了解 anki 抓取网页的自定义方式吗？如果能做自定义的话，可以试试将抓取简悦优化后的页面。

**Comment by TheGodOfKing** [comment]
@Kenshin 谢谢三连，还没研究过，不太了解。

**Comment by jy324** [comment]
@Kenshin 为什么我用这个测试链接导出失败了😢
阅读模式能够识别
![image](https://user-images.githubusercontent.com/74438973/184536632-036a2b1b-bff5-4cf9-806b-4724939ef5a6.png)
插件配置也没有问题
![image](https://user-images.githubusercontent.com/74438973/184536699-db0db54e-326d-46df-b3b3-2813d4aa1475.png)
![image](https://user-images.githubusercontent.com/74438973/184536753-77be0a90-2f42-4a7a-81d5-013bc0cfa4b9.png)
但是typora公式无法解析
![image](https://user-images.githubusercontent.com/74438973/184536774-25ba92bb-9ca9-44e5-a733-3ee8e809b5da.png)

**Comment by Kenshin** [comment]
@jy324 

试试 Obsidian

**Comment by jy324** [comment]
@Kenshin 
哦哦好了，Obsidian显示出公式了
但是typora是不能识别的是吗？
PS：刚刚想去提新issue所以把之前的一条给删掉了🤣

**Comment by Kenshin** [comment]
> typora是不能识别的是吗？

Typora 估计需要开启相关选项。

**Comment by jy324** [comment]
找到了，勾选这个内联公式的选项就行。
![image](https://user-images.githubusercontent.com/74438973/184662023-bb91627b-477e-4098-9ccc-c21bc662e2e6.png)

**Comment by Kenshin** [comment]
@jy324 

Cool

**Comment by henflower** [comment]
发现对行间公式的导出仍然有问题，在公式末尾的$$前会加两个反引号\\$$导致整个排版发生错误。测试网址：https://zhuanlan.zhihu.com/p/47858230
![image](https://user-images.githubusercontent.com/110607018/185778441-5eafe60a-bd28-4177-bf4d-68c242743392.png)

**Comment by Kenshin** [comment]
@henflower 

公式太多了... 请详细告知出问题的地方。

**Comment by henflower** [comment]
@Kenshin 可以以章节1.1图片下方的几行公式为例，这一篇导出基本都是$$+公式+$$的格式，都出现了错误。
![image](https://user-images.githubusercontent.com/110607018/185779522-02c751af-ee72-455a-9f65-4874ae396327.png)

**Comment by Kenshin** [comment]
@henflower

![image](https://user-images.githubusercontent.com/81074/185788240-e1859142-dc45-47f7-a725-2124fdad0f8c.png)

这是我在 ob 中的预览效果，感觉没什么问题。

![image](https://user-images.githubusercontent.com/81074/185788235-7c35c75d-c95f-4614-975b-0504cc09b19e.png)

**Comment by henflower** [comment]
@Kenshin 在关闭所有extensions打开该页面后，该页面的源码公式后边就包含这两个转义符，单独使用简约导出用MD功能也会在结尾$$前有//。使用的是最新的520版本，试了几个知乎专栏行内公式的网页都是这样，不排除是其他因素产生的我的个人问题。最后，感谢您一直以来的开发和维护，配合obsidian对我的学习生活帮助很大。
![Screenshot 2022-08-21 213924](https://user-images.githubusercontent.com/110607018/185789986-fd9f10b1-4ae8-428c-843a-93667da29967.png)
，

**Comment by Kenshin** [comment]
@henflower

你试试在隐身模式下，导出 md看看有没有问题。

另外，你用什么编辑器查看的 md ？

**Comment by Kenshin** [comment]
@henflower 

今天太晚了，明天给你发个我导出的 md 看看有没有什么区别。

PS：简悦能给你带来便利，我也很高兴。

**Comment by jy324** [comment]
@henflower 我使用obsidian导入就是正常的
![image](https://user-images.githubusercontent.com/74438973/185827452-b0fe4541-59fe-4218-b0cf-a37e448343ba.png)

**Comment by henflower** [comment]
@jy324 @Kenshin 我发现我切到阅览视图也能正常显示，到编辑模式就因为那个多出来的\\不正常了

**Comment by Kenshin** [comment]
> @jy324 @Kenshin 我发现我切到阅览视图也能正常显示，到编辑模式就因为那个多出来的\不正常了

那无所谓，ob 的编辑模式和预览模式是不一样，你就当是个 ob 的 Bug 就好了。😂

**Comment by Kenshin** [comment]
@henflower @jy324 

要是简悦帮助到你的话，请帮忙五星 + 好评  😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
