### ISSUE TITLE
打开自动同步后，所有插件都用不了

### ISSUE THREAD

**Issue by greedyhao** [Kenshin/simpread#4336]
- 操作系统 Windows 
- 浏览器版本 Edge 103.0.1264.77
- 简悦版本 **2.2.0**

安装完插件之后，一打开同步助手的自动同步功能后，有的插件就看不到了

![image](https://user-images.githubusercontent.com/25771942/183281170-031b00fb-bb42-4a3e-9f48-291e600cf71a.png)

开启同步后

![image](https://user-images.githubusercontent.com/25771942/183281379-a6120285-64aa-46bd-a656-bf3379af26a5.png)

![image](https://user-images.githubusercontent.com/25771942/183281383-6dfd0530-e41d-4f84-9045-adf0432ee47a.png)

**Comment by Kenshin** [comment]
嗨，试试下面两个步骤，应该没问题的。

1. 开启自动同步后需要覆盖本地配置文件

   ![image](https://user-images.githubusercontent.com/81074/183282316-9cd1989c-acc5-4c28-9798-5db5a9681659.png)

2. 使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装插件
