### ISSUE TITLE
自动化辅助增强无法保存设置

### ISSUE THREAD

**Issue by DelmarHuang** [Kenshin/simpread#4338]
**发生问题的环境**

- 操作系统 **macOS**

- 浏览器版本 **EDGE 103.0.1264.77**

- 简悦版本 **2.2.0**

- [发生问题的地址 <请填写你的地址l>](https://forum-zh.obsidian.md/t/topic/1425)

**你的问题**

想把稍后读的标注同步到Notion中，于是按照教程设置自动化辅助增强，但每次设置完刷新后重新打开阅读模式，都会把上次设置的内容清空干净然后弹窗要我重新设置。每次都点了保存，都显示保存成功，但实际上一点用都没有

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54244063/183307812-35bb562f-eb0e-4c5a-93c5-02b3e2cc3323.png">

PS: 文章能正确导入Notion中

**Comment by Kenshin** [comment]
嗨，使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装，这个链接有教程，根据教程就好，或者看这里的教程 https://zhuanlan.zhihu.com/p/542938535

**Comment by DelmarHuang** [comment]
> 嗨，使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装，这个链接有教程，根据教程就好，或者看这里的教程 https://zhuanlan.zhihu.com/p/542938535

我就是通过插件管理器安装的，先点了安装，再点导入。然后再刷新还是一样的。

**Comment by DelmarHuang** [comment]
> emmm 估计是反复安装插件造成的，试试清除全部插件，然后在使用插件管理器试试。

按这个走一遍之后更糟糕了😂之前的插件设置全丢，重新保存设置也不行。重新进入阅读模式会要求再设置一遍：
![image](https://user-images.githubusercontent.com/54244063/183440009-a18477a5-9717-489e-ab4e-3e19b9a486fc.png)
