### ISSUE TITLE
提示不是高级账户

### ISSUE THREAD

**Issue by greedyhao** [Kenshin/simpread#4339]
- 操作系统 Windows
- 浏览器版本 Edge 103.0.1264.77
- 简悦版本 2.2.0

https://github.com/Kenshin/simpread/issues/4335#issuecomment-1207376011 后续

配置完成自动化后，提示说不是高级账户，但是在账户的页面看到已经是高级账户了
![image](https://user-images.githubusercontent.com/25771942/183294185-ea5b05f4-36fe-4f9a-9e46-8b5ddf09d58a.png)

![image](https://user-images.githubusercontent.com/25771942/183294093-5df802a8-5f6f-4eed-9e13-a065a0d0e90f.png)
![image](https://user-images.githubusercontent.com/25771942/183294130-68540463-6ab1-4e50-bd04-b955cb6de5c8.png)

**Comment by greedyhao** [comment]
重新登录后，高级账户正常

**Comment by Kenshin** [comment]
嗨，搞定就好。
