### ISSUE TITLE
有关pocket标注的同步

### ISSUE THREAD

**Issue by sokouu** [Kenshin/simpread#4341]
作者你好, 请问pocket的标注有可能实现吗? pocket的同步加入已经可以实现了. 因为手头有kobo电纸阅读器, 内置pocket服务, 可以边阅读边标注, 很方便. 如果能实现同步到简悦中就太好了.

**Comment by Kenshin** [comment]
emmm 

这个应该比较麻烦，即便能导入也没办法做到实时，并不是每个应用都能跟简悦一样开放。

**Comment by sokouu** [comment]
的确, 思考了下, 还是转变工作流简单哈哈.

**Comment by Kenshin** [comment]
哈哈，确实如此。

不过，Kobo 电纸阅读器应该可以使用简悦，试试安装 Kiwi Browser。

**Comment by sokouu** [comment]
很可惜, Kobo是封闭系统, 不是安卓...

**Comment by Kenshin** [comment]
哈，我一直以为是 Andorid 系统。😂
