### ISSUE TITLE
「稍后读」在本地已有html的情况下依然解析失败

### ISSUE THREAD

**Issue by famiji** [Kenshin/simpread#4345]
文章通过Telegram Bot或者Pocket推送到「稍后读」，文章为经济学人或者纽约时报等404网站的文章，但一些文章（通过Pocket推送的）左下角显示已本地保存，也可以成功打开本地html文件，但解析依然失败，配置已经按教程一步步配置成功，可以保存非外网文章，想请问下是什么问题，或者还是功能未适配？

**Comment by Kenshin** [comment]
嗨，我记得在群里算是解释了这个问题，我关闭这个 Issues 了。
