### ISSUE TITLE
华尔街日报(wsj)的amp站点无法加载图片

### ISSUE THREAD

**Issue by sokouu** [Kenshin/simpread#4346]
作者你好, wsj的amp站点, 默认似乎无法加载图片. 在手动框选后, 仅显示缩略图(如图), 这种情况在少数派等网站也有见过, 似乎让网页加载一会儿再进入阅读模式就没问题.

**Comment by sokouu** [comment]
https://cn.wsj.com/amp/articles/%E7%BE%8E%E5%9B%BD%E8%AE%AE%E5%91%98%E5%AF%BB%E6%B1%82%E6%8E%A8%E5%87%BA%E6%95%B0%E5%AD%97%E7%BE%8E%E5%85%83%E4%B8%8E%E4%B8%AD%E5%9B%BD%E7%AB%9E%E4%BA%89-11660021805

**Comment by Kenshin** [comment]
嗨，可以直接进入阅读模式的，你给出的页面在图片下面才是正文。

PS：不要发这样的图片到 Github Issues 上面，只是个善意提示，原因不需要过多解释。
