### ISSUE TITLE
能否增加禁用盘古之白选项

### ISSUE THREAD

**Issue by cangyuyao** [Kenshin/simpread#4350]
盘古之白或许有益正规文章排版，但对于解析有误的地方（盘古之白本身也有很多issue）、部分固定用语、日期时间、 特殊网络语、或者( *´艸`) 这类颜文字来说只是增加了很多不必要的空格。视觉效果也不佳。

能否增加一个禁用盘古之白的选项？

![image](https://user-images.githubusercontent.com/3854729/183668106-f479a7a2-6626-4f14-bd96-ae49d858e047.png)
![image](https://user-images.githubusercontent.com/3854729/183664554-478c0605-f9ac-495e-8dcc-35b55f4853eb.png)
![image](https://user-images.githubusercontent.com/3854729/183662771-7be898f2-03f2-4069-97e7-624ad2ea2d17.png)
![image](https://user-images.githubusercontent.com/3854729/183669175-da7e662a-4512-41ed-a5ba-8612b5dc2144.png)

**Comment by Kenshin** [comment]
可以试试黑名单，位置在：选项页 → 高级设定 → 黑名单。

**Comment by cangyuyao** [comment]
> 可以试试黑名单，位置在：选项页 → 高级设定 → 黑名单。

黑名单只是完全禁用简悦吧？我只是想在必要的页面上不插空格……

**Comment by Kenshin** [comment]
> 黑名单只是完全禁用简悦吧？

是的。

> 只是想在需要的时候禁止触发插空格……

我没理解你的意思，你也可以试试排除列表。

**Comment by cangyuyao** [comment]
> > 只是想在需要的时候禁止触发插空格……
> 
> 我没理解你的意思，你也可以试试排除列表。

我的意思是，需要用到聚焦或阅读模式、但中西文间不需要（不能）多插入空格的情况。

**Comment by Kenshin** [comment]
> 中西文间不需要（不能）多插入空格的情况。

明白了，暂时没有这个功能，你可以在这里关闭词法分析引擎，但并不适用随时关闭或者 xxx名单之类的。

![image](https://user-images.githubusercontent.com/81074/183847368-f2afc7aa-2042-46f3-b64b-fb673d2f1ebb.png)

**Comment by cangyuyao** [comment]
> 明白了，暂时没有这个功能，你可以在这里关闭词法分析引擎，但并不适用随时关闭或者 xxx名单之类的。

关闭词法分析不能停用盘古之白，把 contenscripts.js 的`.plugin.pangu&&this.plugin.pangu.spacingElementByClassName(e)`删了可以。本来是不想用这么破坏性的方式的，总之我先这么用着了😂

**Comment by Kenshin** [comment]
哈哈，好吧，不支持这种形式，但暂时也就这样吧。
