### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by Luddiss** [Kenshin/simpread#4351]
发生问题的地址: <https://jxt.zj.gov.cn/art/2021/6/3/art_1562871_58926656.html>

**Comment by Kenshin** [comment]
可以手动完成适配的，根据提示后的操作就可以了。

![image](https://user-images.githubusercontent.com/81074/183805273-6fca3fec-0e9a-4e07-a7fd-a23c4b5533e1.png)
