### ISSUE TITLE
关于 Logseq 定制化的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4352]
开发者你好，目前我已经基本弄懂简悦的工作流程。确实解决了我工作生活中的很多问题。notion剪藏功能确实牛逼，比我使用的任何导入工具都厉害。logseq自动标注导出也正常。但目前遇到个问题，我日志用的星期格式，但是我不知道简悦标注markdown如何设置星期格式。每次点击简悦的标注日期都不能链接到日志。另外标签默认简悦，能否加其他标签？每次我都得手动加标签，query才能查询到标注。
<img width="613" alt="Snipaste_2022-08-09_22-17-55" src="https://user-images.githubusercontent.com/71954782/183674726-683e28ab-d4a5-4b74-a7c5-3389c75515f8.png">

_Originally posted by @jon9527 in https://github.com/Kenshin/simpread/issues/4237#issuecomment-1209455325_

**Comment by Kenshin** [comment]
@jon9527 

我新建了一个 Issues 来讨论这个问题。

**Comment by lyserenity** [comment]
1. 如果是想要连结到 Logseq 的 Journal，首先要查看一下日期（logseq) 的格式：
    <img width="940" alt="image" src="https://user-images.githubusercontent.com/32646062/183809795-b0e90691-c547-4113-b30a-4ce2169f4589.png">

    然后，要能跳转到日志，格式是 `[[<日期格式>]]`，按提供的图里应该是：`time:: [[2022-07-26]]`

2. 标签的部分，是用内置的？还是[Markdown 模板辅助增强](https://github.com/Kenshin/simpread/discussions/3725) 
    只要按照教程，应该是没什么问题才是，还是有什么特殊需求？

**Comment by jon9527** [comment]
1.我日期格式用的是这个[image: image.png]
但是在 time:: [[{{date_format|now|yyyy-MM-dd}} ]]设置成 time::
[[{{date_format|now|yyyy-MM-dd EEEE}} ]]并不能链接到日志。
2.标注导出用的markdown模板：
tags:: #[[SimpRead]] {{tags}}
type:: [[Literature Notes]]
time:: [[{{date_format|now|yyyy-MM-dd}} ]]
source:: [{{title}}]({{url}})
desc:: {{desc}}

{{#each}}
- > [📌](<{{an_int_uri}}>) {{an_html}}

{{  - |an_note}}{{an_tags}}
{{/each}}
——————————————————
目前问题tags:: #[[SimpRead]]
{{tags}}后面如何写，可以把我每次标注的标签直接导出生成双链，这样我就可以在logseq里面直接用query语法查询。
，

肥肥 ***@***.***> 于2022年8月10日周三 12:19写道：

**Comment by lyserenity** [comment]
在 github 上看不你图片的附件。

1. 日期
    <img width="359" alt="image" src="https://user-images.githubusercontent.com/32646062/183827604-82dd285d-ed92-4006-a3ec-14e5823e1f5f.png">

    你这边多了个空格，当然没有办法正常连结。
    因为你用的是内置的模版机制，日期格式有限制，可以这样设（注意本行最后要留一个空格）：
    `time:: {{date_format|now|[[yyyy-MM-dd hh.mm:ss]]}} `

2. 关于 tag
    > {{tags}}后面如何写，可以把我每次标注的标签直接导出生成双链，这样我就可以在logseq里面直接用query语法查询。
    {{tags}} 跟 {{an_tags}} 是不同的东西，前者以文章为对象，后者是标注为对象。
    
    你问 {{tags}} 但又说是标注，令人摸不着头脑.... 😂

   如果你是想把 {{tags}} 让每一个标注都自动继承，那你必须用 [Markdown 模板辅助增强](https://github.com/Kenshin/simpread/discussions/3725) 这个插件，内置的 “应该” 做不到这件事......

**Comment by jon9527** [comment]
好的，谢谢您的解答。我在好好研究下。模板是粘贴别人分享的。简悦这个软件功能太强，但对于我们这种小白来说还需要时间。

**Comment by Kenshin** [comment]
@jon9527 

okay 我先关闭这个 Issues 了，有任何问题仍可以继续在这里讨论。😁

简悦这边有很多现成的模板，你可以在这些大佬设置的模板基础上调整，并不会太麻烦。

**Comment by Kenshin** [comment]
@jon9527 

请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
