### ISSUE TITLE
新站适配：微博文章页

### ISSUE THREAD

**Issue by UID2424736971** [Kenshin/simpread#4353]
发生问题的地址: <https://weibo.com/ttarticle/p/show?id=2309404784600026317494>

**Comment by Kenshin** [comment]
嗨，谢谢反馈，之前是可以适配的，估计是微博文章页调整造成的，我先记录下，适配后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，安装这个适配规则 https://simpread.ksria.cn/sites/details/74QskZHJPq 即可解决。
