### ISSUE TITLE
代码行数显示异常

### ISSUE THREAD

**Issue by lovertechnology** [Kenshin/simpread#4355]
![image](https://user-images.githubusercontent.com/50872586/183828301-5589a7f3-4ef3-40bb-bd09-2253853d77fa.png)
看代码前面的行数会跳出代码框，独立成行。需要优化。

**Comment by Kenshin** [comment]
嗨，简悦对代码段的识别确实有些问题，因为代码段的高亮方案太多了，很难有统一方案。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by lovertechnology** [comment]
https://interviewguide.cn/notes/03-hunting_job/02-interview/01-01-04-%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html
这是原网页

**Comment by Kenshin** [comment]
okay
