### ISSUE TITLE
调用失败

### ISSUE THREAD

**Issue by dennes2020** [Kenshin/simpread#4358]
macbook air m1芯片，edge打开网页。在右键选择保存到稍后度的时候，提示“嗨。不小心调用失败了，请不要担心，请重新再试”，反复尝试，都这样提示。网页无法保存到稍后读。

**Comment by Kenshin** [comment]
跟什么芯片无关。

1. 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
2. 试试添加 https://sspai.com/post/69972
3. 调用失败感觉是你使用自动化时造成的，你做了自动化？

**Comment by Kenshin** [comment]
你可以继续在这里讨论，尽量详细描述下加入稍后读时做了什么自动化，截图给我。

**Comment by dennes2020** [comment]
没有添加自动化。按照您的建议安装插件后依然不行。现在“设置”——“
<img width="1425" alt="截屏2022-08-11 14 25 14" src="https://user-images.githubusercontent.com/71048096/184076171-76f8c30b-7617-49fe-bc54-f089ba3c1948.png">
通用”中好些选项打不开了。

**Comment by dennes2020** [comment]
<img width="1012" alt="截屏2022-08-11 14 30 49" src="https://user-images.githubusercontent.com/71048096/184076354-5f445a33-982c-4d05-8100-835bdcc592e8.png">

**Comment by dennes2020** [comment]
我是否卸载这个插件，然后重新安装、设置回好？

**Comment by Kenshin** [comment]
我知道了... 

你使用了同步助手，但没有激活验证它，这是 [教程](http://ksria.com/simpread/docs/#/Sync?id=%e9%aa%8c%e8%af%81)

**Comment by dennes2020** [comment]
我的设置——共通这个部分没有图中标示的部分，点“同步”“自动同步”等都没有反应
<img width="795" alt="截屏2022-08-11 14 37 56" src="https://user-images.githubusercontent.com/71048096/184077722-a64dff01-99bb-4eae-ab77-81e918343ba0.png">

**Comment by dennes2020** [comment]
以前别的计算机上的内容也能同步过
<img width="598" alt="截屏2022-08-11 14 43 29" src="https://user-images.githubusercontent.com/71048096/184078098-7af5db66-a0e3-4c1f-a72c-ffd730f8c627.png">
来

**Comment by Kenshin** [comment]
试试 https://github.com/Kenshin/simpread/discussions/1576 这个方式。

**Comment by dennes2020** [comment]
现在可以收藏到稍后读了，谢谢！
