### ISSUE TITLE
导出全文到 Obsidain 失败

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4359]
不使用同步助手方案

保存某些网站会失败，有办法查看日志吗？
也不知道因为什么失败了
![image](https://user-images.githubusercontent.com/4424520/183615118-11ef9476-8689-4635-a303-60301b7098d4.png)

***

试过了，还是不行

请帮忙测试下看看是哪里的问题，以上是我保存的文章地址
https://www.gcores.com/articles/154604

我的obsidian版本0.15.9
简悦版本，高级账户

使用的功能是
![image](https://user-images.githubusercontent.com/4424520/184055115-87b6fa44-7516-4037-be62-8b5daa4245e3.png)

_Originally posted by @murazi in https://github.com/Kenshin/simpread/discussions/1631#discussioncomment-3356367_

**Comment by Kenshin** [comment]
@murazi

我把讨论转移到这里了。

***

我是 Windows 系统，可以正常的导入

![image](https://user-images.githubusercontent.com/81074/184060983-d0586f8c-4666-4ca2-9bdd-b7c3722116bd.png)

**Comment by murazi** [comment]
我也是Windows，能介绍下你的“导入到 obsidian 选项”的参数吗？

我又试了几次，尝试禁用启用几个选项，都找不到原因，还是失败

![image](https://user-images.githubusercontent.com/4424520/184068089-ab1c949a-95bb-4e5f-968a-b58a0ee7d6ab.png)

**Comment by murazi** [comment]
> @murazi
> 
> 我把讨论转移到这里了。
> 
> 我是 Windows 系统，可以正常的导入
> 
> ![image](https://user-images.githubusercontent.com/81074/184060983-d0586f8c-4666-4ca2-9bdd-b7c3722116bd.png)

你所保存的，是不是不包含图片？
该网站的文章图片似乎是读取不到

**Comment by Kenshin** [comment]
我怀疑是 https://github.com/Kenshin/simpread/issues/4360 问题造成的。

如果你没有需要保存的数据，请重置全部配置数据，然后先不要使用自动同步功能，按照 https://github.com/Kenshin/simpread/issues/4360#issuecomment-1211592305 提的提示配置

**Comment by Kenshin** [comment]
关于 Ob 的问题就在这里说吧。

快捷键是支持的

![image](https://user-images.githubusercontent.com/81074/184090570-e8560082-542f-47de-8302-66e4ea32c928.png)
