### ISSUE TITLE
几个简悦的使用疑问

### ISSUE THREAD

**Issue by murazi** [Kenshin/simpread#4360]
帮助文档打不开，另外我没有Notion账号也不用Notion

安装了图床插件，也配置过PicGO
但插件这里是没有像插件里介绍的那样，这里是没有图床的选项，另外我确认开启了图床插件
![image](https://user-images.githubusercontent.com/4424520/184071279-b38bae45-733b-4026-81ec-9d41f5c3e5cd.png)

关于这个选项，我希望精简我的动作栏菜单
![image](https://user-images.githubusercontent.com/4424520/184073553-8916091b-27f1-4856-bc65-110aa7e473a0.png)
点击该菜单，会跳转到插件的服务选项卡
然后我把这里的分类选项挨个看了一遍
![image](https://user-images.githubusercontent.com/4424520/184071675-5a91facc-b8f4-4369-9eeb-4a34392fe467.png)

**Comment by Kenshin** [comment]
1. 关闭自动同步
2. 重新安装你需要的插件

你遇到的问题在每个插件的说明中都有提示，比如导入到 Obsidian

![image](https://user-images.githubusercontent.com/81074/184075157-9bca899f-2438-49e3-a042-2e8daa556f1a.png)
