### ISSUE TITLE
Chrome 扩展程序不是自带同步的吗，而且是无配置无感知的

### ISSUE THREAD

**Issue by bowencool** [Kenshin/simpread#4361]
应该是轻度使用的最佳方式了吧

**Comment by Kenshin** [comment]
Chrome 扩展的同步不是很好用，经常丢数据，我在 1.0.0 最初版本时就放弃了这个方案。

**Comment by bowencool** [comment]
能不能保留这种方式，让用户自己选择呢？毕竟是0配置的，对新人无疑非常友好

**Comment by bowencool** [comment]
我也是刚接触，我想快速体验一下同步的功能，来确定要不要开会员

**Comment by Kenshin** [comment]
> 能不能保留这种方式，让用户自己选择呢？毕竟是0配置的，对新人无疑非常友好

你可以理解这种方式类似 iCloud 你不知道它什么时候运行，什么时候同步，是否 100% 同步成功了，iCloud 的同步质量就不用再说了吧。

不想使用自动同步的话，使用手动同步，是一样的。
