### ISSUE TITLE
添加到白名单无法自动进入阅读模式

### ISSUE THREAD

**Issue by vitalQ** [Kenshin/simpread#4362]
文章链接：https://baijiahao.baidu.com/s?id=1740850553573212669
![01](https://user-images.githubusercontent.com/37363257/184094167-1c1575c1-7e22-4531-b58d-95bd68268803.png)
![02](https://user-images.githubusercontent.com/37363257/184094178-8daa9c26-23cd-42ae-aac3-8f388a099628.png)

无法打开网页后自动进入阅读模式，手动进入阅读模式是没问题

**Comment by Kenshin** [comment]
百度在延迟加载列表里面，另外不建议将百度百科加入到白名单，不一定 100% 好使。

![image](https://user-images.githubusercontent.com/81074/184119994-af7b6116-58fa-4417-84ff-ee20f91ae65c.png)

**Comment by vitalQ** [comment]
> 百度在延迟加载列表里面，另外不建议将百度百科加入到白名单，不一定 100% 好使。
> 
> ![image](https://user-images.githubusercontent.com/81074/184119994-af7b6116-58fa-4417-84ff-ee20f91ae65c.png)

延迟加载列表里已经移除百度，但还是不行，我白名单加入的是百家号，百家号也不建议加入到白名单吗

**Comment by Kenshin** [comment]
哦，抱歉，百家号应该没问题。

你直接加 `baijiahao.baidu.com`

**Comment by vitalQ** [comment]
> 哦，抱歉，百家号应该没问题。
> 
> 你直接加 `baijiahao.baidu.com`

可以了，我明白了，我之前加的是` https://baijiahao.baidu.com` 这样不行，把前面`https://`去掉就好了，感谢。

**Comment by Kenshin** [comment]
使用方案不一样的，你在设置的地方有链接可以打开相应的说明。

**Comment by vitalQ** [comment]
> 使用方案不一样的，你在设置的地方有链
接可以打开相应的说明。

我试了一下，我用的是文档里写的链接，确实无法通过**url**规则来进入阅读模式，只有**主域名**规则才能自动进入阅读模式，您看看是否我哪里设置的不对

![微信截图_01](https://user-images.githubusercontent.com/37363257/184277636-0bedf68f-d79f-4347-bd25-a7982be8ef01.png)
![微信截图_02](https://user-images.githubusercontent.com/37363257/184277698-4392262e-8147-4869-b9a3-b5c9a733af0a.png)

**Comment by Kenshin** [comment]
你最后一个截图的白名单设置有错误，简书是 `https`

**Comment by vitalQ** [comment]
> 你最后一个截图的白名单设置有错误，简书是 `https`

简书用了`https`确实可以自动进入阅读模式了，但是百家号直接添加url还是不行，添加百家号主域名就可以，不知道是不是有特殊处理。
正则表达式我试了一下也是不行，从简阅文档中心复制来的，是不是表达式有不对 `[[/https:\\/\\/movie.douban.com\\/subject\\/\\d+\\/?/]]`
测试链接是这个：https://movie.douban.com/subject/30267255/

![01](https://user-images.githubusercontent.com/37363257/184280186-2d5923e5-6492-4547-8a4d-14e85f449208.png)
![02](https://user-images.githubusercontent.com/37363257/184280197-185b79bd-b44b-4147-83f8-e160e5bfad33.png)

**Comment by Kenshin** [comment]
emmm 正则确实有错误，正确的是

`https:\/\/movie.douban.com\/subject\/\d+\/?`

至于百度的问题，你可以使用另外一个方案

`https://baijiahao.baidu.com/s?id=*`
