### ISSUE TITLE
导出 org-mode 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4364]
开发者我在这一步怎么没看到.org文件导出？插件都安装了。要同步助手配置的吗？

_Originally posted by @jon9527 in https://github.com/Kenshin/simpread/discussions/3775#discussioncomment-3374879_

**Comment by Kenshin** [comment]
@jon9527 

哪一步？请详细说明，包括截图以及操作步骤等。

**Comment by jon9527** [comment]
放弃了，用1.0方案了，配置太复杂了。
