### ISSUE TITLE
新站适配：语雀

### ISSUE THREAD

**Issue by kkwow** [Kenshin/simpread#4365]
语雀阅读的时候，文章图片识别出来了，能否禁止识别图片文字

**Comment by Kenshin** [comment]
> 禁止识别图片文字

没理解你的意思

**Comment by kkwow** [comment]
默认语雀效果 ![Snipaste_2022-08-12_16-45-01.png](https://s2.loli.net/2022/08/12/bsn6ecx1aU8ZIW3.png)

简悦 显示效果![Snipaste_2022-08-12_16-42-40.png](https://s2.loli.net/2022/08/12/dIs31LvjJkCNwlT.png)

你好，简悦会解析图片里面的文字。这样会导致大量无效内容。能否禁止识别图片文字。

**Comment by Kenshin** [comment]
emmm

我大概知道你的问题了，试试安装 https://simpread.ksria.cn/sites/details/QF22ZcE8n5 看看能否解决？

**Comment by kkwow** [comment]
> emmm
> 
> 我大概知道你的问题了，试试安装 https://simpread.ksria.cn/sites/details/QF22ZcE8n5 看看能否解决？

我安装的就是这个插件，我刚刚卸载后，重新安装，并且重启浏览器，问题依旧。

**Comment by Kenshin** [comment]
把遇到问题的 URL 给我看下。

**Comment by kkwow** [comment]
> 把遇到问题的 URL 给我看下。

https://www.yuque.com/agiso/aldstb/kpzrdc

**Comment by Kenshin** [comment]
emmm

好像语雀的规则改变造造成的，我先记录下。

**Comment by kkwow** [comment]
> emmm
> 
> 好像语雀的规则改变造造成的，我先记录下。

非常感谢，那我这边就等待你们更新。

**Comment by Kenshin** [comment]
嗨，目前这个功能改为插件实现 https://github.com/Kenshin/simpread/discussions/4380 你可以试试，应该没问题。
