### ISSUE TITLE
[Feature]Lightbox Gallery 当图片过大时可更改图片尺寸

### ISSUE THREAD

**Issue by Xm798** [Kenshin/simpread#4367]
在部分页面中，如果出现手机截图这种尺寸比较大的图片，会导致阅读模式下图片特别长，滚动三四屏全是图片的情况。目前是否具有调整图片最大尺寸的功能呢（或者限制最大高度/宽度）

阅读模式
![CleanShot 2022-08-12 at 21 43 10@2x](https://user-images.githubusercontent.com/48074861/184366253-6bf4ac82-8b9f-435d-ae38-14ed43c9d020.png)

少数派原文
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/48074861/184366526-ca350085-a854-4430-a4ee-2a1939a69caf.png">

**Comment by Kenshin** [comment]
嗨，这是在手机上使用简悦？还是什么情况？

**Comment by Xm798** [comment]
> 嗨，这是在手机上使用简悦？还是什么情况？

这是在电脑浏览器中使用的简悦～

**Comment by Kenshin** [comment]
URL 给我看下。

**Comment by Xm798** [comment]
> URL 给我看下。

https://sspai.com/post/74308

不过这是一篇付费文章

**Comment by Kenshin** [comment]
没事，我能看到。

不过，我理解你的需求了，我考虑下。

**Comment by Xm798** [comment]
十分感谢！🙏

**Comment by Kenshin** [comment]
小事情，我已记录。

***

近期被一个一星恶心到了，一个一星能抵得上 nnn 多五星。

要是简悦解决了你的问题，请帮忙五星 + 好评 🙏

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Xm798** [comment]
已经五星好评，辛苦啦～

**Comment by Kenshin** [comment]
太感谢了~

**Comment by Kenshin** [comment]
嗨，Lightbox Gallery 1.0.2 版已经发布了，增加了 [定制最大高度的功能](https://github.com/Kenshin/simpread/discussions/1598#discussioncomment-3480036)。

你可以通过打开 https://simpread.ksria.cn/plugins/details/VQOZdNET2d 直接升级。

如果使用了同步助手导致无法安装插件的话，请看这里的 [解决方案](https://github.com/Kenshin/simpread/discussions/2342)。
