### ISSUE TITLE
导入到Obsidian插件的设置逻辑是否有待改进

### ISSUE THREAD

**Issue by ntlv1** [Kenshin/simpread#4369]
导入Obsidian插件的设置界面，“导入全文”一项中有一个子选项“是否使用md+assets方式”。

鉴于md+assets方式本身已经有独立的触发器，这样的选项设置让我误以为“是否使用md+assets方式”一项控制的是“导入md+assets到Obsidian”这一触发器的开关，而“导入全文到Obsidian”触发器依然使用的是方式1/2/3。然而实际上当勾选此选项时，方式1/2/3已经被覆盖掉了。

md+assets方式，我觉得更像是一种独立的方式，与方式1/2/3没什么关系，放在“导入全文”一项中作为一个子选项令人有点混乱，如果列为方式4会不会更加合理呢。

当然也可能是我没有get到这种设置逻辑的设计思路，所以我把issue列为“不会使用等新手问题”，就是个建议，请开发者考虑下。

**Comment by Kenshin** [comment]
哈哈，你可以这么理解：

1. assets + md 单独的插件不仅支持 Obsidian，任意 Markdown 编辑器都可以，比如 Typora
2. 将这个功能集成到 Obsidian 插件后，可以方便 Obsidian 使用。
