### ISSUE TITLE
阅读模式全文导出

### ISSUE THREAD

**Issue by h-dengmin** [Kenshin/simpread#4371]
请问是否可以支持：在阅读模式下将全文导出为Markdown时，可以自定义导出格式，如在全文内容前自定义添加title, tag标签等。

目前只看到导出标注时支持自定义格式。其实如果全选标注也可以实现，但就是比较麻烦。是不是有更好的解决方案？

**Comment by Kenshin** [comment]
当然可以，但这个功能专门是包含在 导出 Obsidian 插件里面的，你可以看下这个插件的使用说明 https://github.com/Kenshin/simpread/discussions/2902

**Comment by h-dengmin** [comment]
找到了，感谢！！！

**Comment by Kenshin** [comment]
小事情。

***

近期被一个一星恶心到了，一个一星能抵得上 nnn 多五星。

要是简悦解决了你的问题，请帮忙五星 + 好评 🙏

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by h-dengmin** [comment]
非常抱歉我的google账号没有评价权限，我会尝试在Edge浏览器的扩展上给上五星评价。

此外还有一个延伸性问题。当我使用简悦的Obsidian插件+Obsidian端的Sync插件联动时，想要导出阅读模式下的全文，但导出的md文件名都只能是{{title}}（我想改成{{date}}-{{title}}），我多次尝试修改了 Obsidian 端插件的 Customize Title 但都没有设置成功。

**Comment by Kenshin** [comment]
> 我会尝试在Edge浏览器的扩展上给上五星评价。

先谢谢了，不过我刚知道竟然有没有评价权限的，是什么情况？

> 我多次尝试修改了 Obsidian 端插件的 Customize Title 但都没有设置成功。

是保存后不生效吗？如果是的话，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装这个插件，链接有提示如何使用

**Comment by h-dengmin** [comment]
> 先谢谢了，不过我刚知道竟然有没有评价权限的，是什么情况？
![image](https://user-images.githubusercontent.com/54652741/184472881-8b6eb140-1018-4424-aef7-a741fdeadcb4.png)

另外我已经在Edge端提交评价了。

>是保存后不生效吗？
按我的理解，在简悦端的OB插件中选择第三种方式Sync导出时，文件名好像是要在OB端的Sync插件中的Customize Title中设置，而简悦端OB插件中的文件名设定好像是仅在稍后读模式中生效（阅读模式和稍后读模式应该是两种不同的模式）。
然后我出现的问题是修改Sync插件中的文件名设置但不起作用。

**Comment by Kenshin** [comment]
> 文件名好像是要在OB端的Sync插件中的Customize Title中设置

是的，这个地方的定制化，参数你可以看下 https://github.com/Kenshin/simpread/discussions/2889#discussioncomment-2831868

其实你而已在 metadata 中以别名的方式指定它

**Comment by h-dengmin** [comment]
所以文件名命名是只能用以下的参数吗？

![image](https://user-images.githubusercontent.com/54652741/184474193-1da1c2a2-fe6a-4d7d-adf0-a3e924c27ffd.png)

我想我明白我问题的原因了。因为我不用稍后读模式，而Customize Title里面的参数基本上都是稍后读模式的参数，只有{{title}}是针对阅读模式（原页面）的，而我甚至添加了不在该参数范围内的参数（如{{date}}，{{now}}），所以结果就只有标题。

我看到说“为了简化操作，去掉了{{now|<格式化>}}”，这个功能保留下来还是蛮好的，可以有更大的定制化空间。

ps: 很多时候如果我不用稍后读就没有稍后读id和其他一系列参数，就限制了阅读模式导出的一些很基本的定制化功能（甚至是简单的文件名定制化）。想必会有一些人和我有相同的习惯（以时间+标题作为文件名），希望恢复去掉的{{now|<格式化>}}。

**Comment by Kenshin** [comment]
你可以用 `alias` 的方式，这个方式可以使用更详细的日期方案。

而文件名就用简悦默认的方案。

**Comment by h-dengmin** [comment]
好吧

**Comment by Kenshin** [comment]
后续的版本会加入你的需求。

**Comment by h-dengmin** [comment]
非常感谢！

**Comment by Kenshin** [comment]
哈，客气了~
