### ISSUE TITLE
插件的排版

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#4374]
![image](https://user-images.githubusercontent.com/15308878/184478045-8ce56689-3f89-4323-8b3d-c7fa55eaf4b4.png)
![image](https://user-images.githubusercontent.com/15308878/184478097-ef550bc7-f177-4439-9b6e-e9cca2c86c4d.png)
![image](https://user-images.githubusercontent.com/15308878/184478113-62923da3-0274-4f88-9268-0ae696cd7887.png)

**Comment by Kenshin** [comment]
会考虑的，但这么比较并不合理，这个页面是论坛类页面，它可以抓取到很多内容，所以呈现的是论坛类页面的特点。

比如我随便找几个截图

![image](https://user-images.githubusercontent.com/81074/184479271-cbea58ae-7f7f-46c4-adb2-eca62bf2007c.png)
