### ISSUE TITLE
标注的建议

### ISSUE THREAD

**Issue by lovertechnology** [Kenshin/simpread#4376]
直接在原网页标注作为备选方案，不需要重新排版，免去排版的很多bug，意思就是随便打开一个网页，不用进入阅读模式，直接可以对网页进行同样的标注和注释。

**Comment by Kenshin** [comment]
嗨，谢谢建议，目前并不支持此方式。

其一，简悦的一些行为都是建立在阅读模式基础上的，包括：插件系统等等，这么做的目的除了是不会干扰原页面外，还有可以通过阅读模式快速形成本地快照，并保证每个页面的视觉都是统一的。

其二，我希望使用标注的场合：具有深度阅读需求，如果用户只对某个页面的某（些）内容感兴趣的话，有很多其它类似工具可以实现。

其三，简悦的标注是为了系统学习，所以才通过阅读模式排除干扰。

**Comment by Kenshin** [comment]
非要这么做的话，建议使用 Hypothesis 这应该是目前最好用的原文标注了，简悦也能跟它联动。

细节 https://github.com/Kenshin/simpread/discussions/2085#discussioncomment-926749

**Comment by lovertechnology** [comment]
可以作为一个最备选的方案嘛。
因为我看日常网页，一些教程网页，不是csdn，涉及到代码的，其排版比较影响阅读体验。除了行数和代码分离，代码中间不能做标注，还有代码段和正文的顺序错乱的问题，这种时候只能退出阅读模式。当影响了知识的获取，反而只专注于阅读模式的沉浸性，就有些本末导致啦。

**Comment by lovertechnology** [comment]
我尝试一下 Hypothesis ，谢啦~

**Comment by lovertechnology** [comment]
Hypothesis不太好用，相比之下PageNote是最好用的网页标注，不过要100块钱，太贵啦hhh

**Comment by Kenshin** [comment]
Hypothesis 还是挺好用的，看看它的用户数就知道了，但可能不适合你，这很正常。

就比如即存在 Obsidian 也存在 Logseq 一个道理。

至于代码段则是另外一个问题。简悦是只能做代码段的标注，如果你需要对某些内容标注的话，还是建议用更专业的工具。
