### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by xxxfhy** [Kenshin/simpread#4382]
**环境**

- 操作系统 **Windows 11**

- 浏览器版本 **Edge 104.0.1293.54 (正式版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <[https://zhuanlan.zhihu.com/p/30666881>

**从https://zhuanlan.zhihu.com/p/30666881 跳转至偏好设置时乱码**

**![image](https://user-images.githubusercontent.com/40598925/184545394-3a0fe3c4-709f-43b2-ab84-2b359ad8b85a.png)**

**Comment by Kenshin** [comment]
嗨，重启浏览器就可以了。
