### ISSUE TITLE
导出md + assets 格式插件报错

### ISSUE THREAD

**Issue by Robertxjf** [Kenshin/simpread#4384]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **  Windows **

- 浏览器版本 **Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

导出md + assets 格式 错误，之前是好的； 现在突然提示如下
同步助手运行时发生了错误,错误信息: ENOENT: no such file or directory, open
'D:\OneDrive - Fast(Document(NoteBooklogseqlsimpReadVassets)chfs在linux和windows下的使用教程lassets(2.png"
怀疑是图片转化服务突然出错

**截图**
![image](https://user-images.githubusercontent.com/56734082/184585836-12083a0f-42e2-46f5-bc13-b0b11153888a.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 应该可以解决。

**Comment by xiaojzh** [comment]
遇到相同问题，并且安装了插件，还是无法解决

**Comment by Kenshin** [comment]
@xiaojzh 

请告知具体 URL

**Comment by xiaojzh** [comment]
> 嗨，安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 应该可以解决。



> @xiaojzh
> 
> 请告知具体 URL

URL：https://www.cnblogs.com/mikewolf2002/ 对这篇进行操作，实际上我遇到所有网站都失败
图片：
![image](https://user-images.githubusercontent.com/75264401/191168289-dfa770b5-c095-401d-97d5-ae8def588dbf.png)

**Comment by Kenshin** [comment]
@xiaojzh 

看起来应该是没有设置对路径造成的，如何设定路径，请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
