### ISSUE TITLE
能否考虑增加预设关键词，高亮显示网页内容的关键词和所在的句子

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#4389]
https://github.com/yiminzme/Multi-Highlight ；类似这样，但是他只支持关键词高亮，整个句子高亮还不行

**Comment by Kenshin** [comment]
有意思的想法，我考虑下。

一般来说，关键词够了，你这么做的意义是什么？

**Comment by angel126** [comment]
> 有意思的想法，我考虑下。
> 
> 一般来说，关键词够了，你这么做的意义是什么？

方便快速浏览，现在内容太多抒情，通过关键词，可以比较快速的阅读结论和观点，之后在考虑通篇阅读。
只是关键词的话，感觉观看的时候，眼睛还是有疲劳，句子的话，可能会更舒适（猜想）

**Comment by Kenshin** [comment]
你想如何设置关键字？毕竟每个页面的内容都不一样的。

**Comment by angel126** [comment]
关键词就是预先设置好的，打开的页面只要包含这些关键词，就会通过不同的颜色标注出来，[Multi-Highlight](https://github.com/yiminzme/Multi-Highlight)目前这个已经实现了这个功能，就是在simread里面失效了，同时我还希望能够对关键词的所在句子也能重色出来（按标点符号截断即可，就是关键词所在句子），类似我们读书用色笔标注出来。
![image](https://user-images.githubusercontent.com/8450915/185007153-75e8b93c-7a78-4d30-adb7-cbf388d5d162.png)
![image](https://user-images.githubusercontent.com/8450915/185007160-9b2b07ea-9c3b-4e6b-885d-a00e5a4e24cf.png)

**Comment by Kenshin** [comment]
okay 我研究下。

**Comment by angel126** [comment]
嗯嗯，多谢费心

**Comment by Kenshin** [comment]
小事情，我已记录了，有后续进展我会在这里通知你~

***

要是简悦帮助到你的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by angel126** [comment]
嗯，好评啦。。

**Comment by Kenshin** [comment]
嗨，你需要的关键词高亮可以了 https://github.com/Kenshin/simpread/discussions/4416 

你可以试试效果。

PS：如果无法安装的话，可以看 https://github.com/Kenshin/simpread/discussions/2342 的解决方案。

***

另外，能否根据这个插件来简单写写《基于这个插件的工作流（也就是给你带来了一些什么方便）》也就是在 https://github.com/Kenshin/simpread/issues/4389#issuecomment-1216336739 的回复基础上稍微扩写点内容。
