### ISSUE TITLE
图片链接拼接错误

### ISSUE THREAD

**Issue by NihilityT** [Kenshin/simpread#439]
网址：https://acl.readthedocs.io/en/latest/zhCN/ch3-cn.html
图片链接：https://acl.readthedocs.io/en/latest/_images/Figure-3.1.png

![qq 20190111161019](https://user-images.githubusercontent.com/21163191/51021088-7eaf5c00-15bb-11e9-8a25-307c99203bc5.png)
![qq 20190111161003](https://user-images.githubusercontent.com/21163191/51021085-7e16c580-15bb-11e9-885f-66e9de8be3b4.png)
https://github.com/Kenshin/simpread/blob/master/src/vender/puread/plugin/beautify.js#L347
已提交修复 PR #440 。
``` JavaScript
if (newsrc.startsWith( "//" )) {
	newsrc = location.protocol + newsrc;
} else if (newsrc.startsWith( "../" )) {
	let newdir = location.href;
	while (newsrc.startsWith('../')) {
		newsrc = newsrc.substr(3);
		newdir = newdir.replace(/[^\/]+$/, '')
			       .replace(/[^\/]+\/$/, '');
	}
	newsrc = newdir + newsrc;
} else {
	newsrc = location.origin + newsrc;
}
```
另有一个疑问，为什么要修改图片的链接？有什么地方是不修改显示不出来的吗？

**Comment by Kenshin** [comment]
谢谢反馈~
为什么关闭了 PR？

`为什么要修改图片的链接？有什么地方是不修改显示不出来的吗？`
是的，具体是哪个页面忘记了...

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，其它更新包括：

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)

**Comment by Kenshin** [comment]
补充下，这个问题，已经彻底解决了，用了一些 [无聊的技巧](https://stackoverflow.com/questions/14780350/convert-relative-path-to-absolute-using-javascript)
