### ISSUE TITLE
文档无法打开

### ISSUE THREAD

**Issue by THU-Pieris** [Kenshin/simpread#4393]
文档打不开。就是这个链接: http://ksria.com/simpread/docs/ 

- 操作系统 macOS 12.5

- 浏览器版本 Safari 15.6 (17613.3.9.1.5)

- 发生问题的地址 http://ksria.com/simpread/docs/

尝试了各种网络环境，Chrome和Safari，但还是无法打开该网址。坐标美国东部。浏览器提示连接不安全，尝试手动输入https后得到截图2。浏览器提示证书配置错误，不知道是否和这个有关。（点击「继续前往」仍然无法打开）

**截图**
<img width="1552" alt="截屏2022-08-16 下午7 01 40" src="https://user-images.githubusercontent.com/49369792/184999789-c014f4bc-b065-4bdd-a57d-576c54dfb852.png">

![截屏2022-08-16 下午7 02 57](https://user-images.githubusercontent.com/49369792/185000289-8a387f81-d1b7-4679-9824-f5a27162e481.jpg)

**Comment by Kenshin** [comment]
嗨 

http://ksria.com/simpread/docs/ 确实是没有加 `http`，所以使用 `https` 肯定的错误的。

这个站放在 Github Page 上，但对用的 cdn 则是在国内，所以如果你肉身在国外的话，有可能会有点问题。

你试试访问 https://cdn.bootcdn.net/ajax/libs/slick-carousel/1.8.1/slick.css 能否打开？

**Comment by THU-Pieris** [comment]
> 嗨
> 
> http://ksria.com/simpread/docs/ 确实是没有加 `http`，所以使用 `https` 肯定的错误的。
> 
> 这个站放在 Github Page 上，但对用的 cdn 则是在国内，所以如果你肉身在国外的话，有可能会有点问题。
> 
> 你试试访问 https://cdn.bootcdn.net/ajax/libs/slick-carousel/1.8.1/slick.css 能否打开？

你好，链接522了。。
<img width="1552" alt="截屏2022-08-16 下午11 13 10" src="https://user-images.githubusercontent.com/49369792/185026782-f8fa1385-326a-4c62-b9b3-dfe89dfe1d0c.png">

**Comment by Kenshin** [comment]
哈哈，链接超时了。

没办法，原来用的是 jsDelivr 但在国内不让用了... 😂

**Comment by THU-Pieris** [comment]
> 哈哈，链接超时了。
> 
> 没办法，原来用的是 jsDelivr 但在国内不让用了... 😂

所以我有什么能访问的办法吗？比如不用cdn，直接访问gh pages

**Comment by Kenshin** [comment]
你需要了解或查看什么功能？

http://ksria.com/simpread/docs/ 大部分都不是教程类的功能，所以针对新用户的话，可能用处不是很大。

**Comment by THU-Pieris** [comment]
> 你需要了解或查看什么功能？
> 
> http://ksria.com/simpread/docs/ 大部分都不是教程类的功能，所以针对新用户的话，可能用处不是很大。

不是新用户hhh用了两年多了。很早就买了，配置了不少东西，不过电脑重装之后全丢了，想再对着弄一遍。
然后当下最迫切的功能是同步。。之前配置的坚果云同步，然后今天弄的时候弹出的warning指向了以上的链接

**Comment by Kenshin** [comment]
同步助手的下载地址我现在给你

1. Onenote https://1drv.ms/u/s!Aua4SNl3dUARh0iLAigvKGbGEHMz?e=LJe6f3

2. Box.net https://app.box.com/s/q7hz86hkeqgoc7mkofxaxu5eiup88j32

**Comment by Kenshin** [comment]
另外，这个问题应该是今天开始遇到的。

一个英国用户也遇到了这个问题。

**Comment by Kenshin** [comment]
> 不是新用户hhh用了两年多了。很早就买了，配置了不少东西，不过电脑重装之后全丢了，想再对着弄一遍。

如果只是教程的话，可以看 https://www.yuque.com/kenshin/simpread 上面的内容。

**Comment by THU-Pieris** [comment]
弄好了，感谢

**Comment by Kenshin** [comment]
小事情，我想想办法看看能否把 http://ksria.com/simpread/docs/ 放到其他地方，并使用 jsDelivr 方案。

**Comment by Kenshin** [comment]
嗨，我增加了一个备份站，你可以帮忙测试下 http://ksria.com/simpread/docs2

**Comment by THU-Pieris** [comment]
> 嗨，我增加了一个备份站，你可以帮忙测试下 http://ksria.com/simpread/docs2

可以正常访问了

**Comment by Kenshin** [comment]
okay 没问题就好。

***

要是简悦帮助到你的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨，我在考虑切换某些 CDN 环境，方便的话，帮忙测试下。

请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？同时请告知速度如何？

**Comment by THU-Pieris** [comment]
> 嗨，我在考虑切换某些 CDN 环境，方便的话，帮忙测试下。
> 
> 请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？同时请告知速度如何？

啊啊， #4401 也是我提的😹刚刚测了一下结果和昨天差不多。

**Comment by Kenshin** [comment]
哈哈，不小心「乌龙」了… 😂

预计下周（最迟再下周）发布。
