### ISSUE TITLE
logseq插件的使用疑问

### ISSUE THREAD

**Issue by hello-wesley** [Kenshin/simpread#4400]
该配置的都配置了
增强同步也有，标注的annote.md文件也可以自动发到logseq的page 里了
插件下载了，点击没有反应，里面是空的，不是说可以自动识别出简悦的文件吗
<img width="1041" alt="截屏2022-08-17 19 34 02" src="https://user-images.githubusercontent.com/67411838/185108677-8d2f5045-3526-4a34-8353-d03395b9cbf4.png">
教程里这个添加是什么意思呢，输入到浏览器里显示的这个
<img width="319" alt="image" src="https://user-images.githubusercontent.com/67411838/185108865-315067c9-99ab-4fe2-90ab-5353c796fdf5.png">

**Comment by lyserenity** [comment]
`http://localhost:7026/unread/<id>?embed=logseq`

先确认你有本地快照，然后 2448 是 id，你可以用 1 试试，同时确认你的本地文件名开头有 `<id>-` 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/32646062/185117448-44c7d3da-f28e-422b-aded-7bfeccf2e54d.png">

**Comment by hello-wesley** [comment]
谢谢你对非技术人的耐心回复

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
