### ISSUE TITLE
外网访问 bootcdn.cn 失败造成部分 Icon 无法显示

### ISSUE THREAD

**Issue by THU-Pieris** [Kenshin/simpread#4401]
- 操作系统 MacOS

- 浏览器版本 Safari 15.6 (17613.3.9.1.5)

- 简悦版本 2.2.0.520
- 插件版本1.1.2

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

无法自定义同步助手的稍后读快捷键。

**截图**

<img width="812" alt="截屏2022-08-17 上午10 31 05" src="https://user-images.githubusercontent.com/49369792/185164045-d2d56d6f-ba9b-47d8-bd75-32c808708a8d.png">

**Comment by Kenshin** [comment]
😂

我知道是什么问题了，跟 https://github.com/Kenshin/simpread/issues/4393 是一样的，因为使用了国内的 CDN 所以没法使用。

正常应该是下面的效果

![image](https://user-images.githubusercontent.com/81074/185280213-fb608776-2c2d-41f2-9e8f-451c17c2194e.png)

你可以在你的版本找到相同的位置，然后试试能否点击保存。

**Comment by THU-Pieris** [comment]
点了半天没有反应(￣Д￣)ﾉ

**Comment by Kenshin** [comment]
你是 Mac 系统的话，如果想调出稍后读，还是有很多其他办法的，比如 Alfred 等。

这个问题我在考虑下，如何优化。

**Comment by THU-Pieris** [comment]
> 你是 Mac 系统的话，如果想调出稍后读，还是有很多其他办法的，比如 Alfred 等。
> 
> 
> 
> 这个问题我在考虑下，如何优化。

嗯嗯麻烦了，其实主要问题是它抢占了其它我常用的快捷键..就很难受。比如Safari打开新的无痕标签页；finder里新建文件夹

**Comment by Kenshin** [comment]
> 其实主要问题是它抢占了其它我常用的快捷键..就很难受。比如Safari打开新的无痕标签页；finder里新建文件夹

okay 没问题，这本来就是应该做的。没料到国内的 CDN 对外网这么不友好...

**Comment by Kenshin** [comment]
嗨，请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？我测试了下，应该可以正常访问，同时请告知速度如何？

**Comment by THU-Pieris** [comment]
> 嗨，请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？我测试了下，应该可以正常访问，同时请告知速度如何？

嗯嗯，可以访问。速度还不错，见截图
<img width="2560" alt="Snipaste_2022-10-29_10-22-17" src="https://user-images.githubusercontent.com/49369792/198836669-de056878-4fdf-4d84-8ab1-c8c3a96083af.png">

**Comment by Kenshin** [comment]
Cool 那我就更换为这个方案。

下个同步助手发布包含此功能。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 切换 Font Awesome CDN 为 https://staticfile.org/ 方案。

除此之外，还增加更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

![image](https://user-images.githubusercontent.com/81074/203220124-d73767b8-c374-4390-b631-fecc46cbf3c5.png)

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
