### ISSUE TITLE
新站适配：马同学

### ISSUE THREAD

**Issue by YU-7** [Kenshin/simpread#4403]
发生问题的地址: <https://www.matongxue.com/madocs/8>

**Comment by Kenshin** [comment]
嗨，我没法登陆这个页面，你可以试试 https://github.com/Kenshin/simpread/discussions/3340 提到的几种方案，应该可以。

**Comment by YU-7** [comment]
哦，不好意思这个页面好像需要微信扫码才能登陆，高亮的方法我试过了不行

**Comment by Kenshin** [comment]
不需要付费吗？非付费的话，可以考虑适配的。

**Comment by YU-7** [comment]
是一个类似于个人的博客，里面也有付费的内容的，也有免费的，我看的这个是免费的

**Comment by Kenshin** [comment]
okay 我开启这个 Issues 并记录下。
