### ISSUE TITLE
段落翻译功能是否可以改变交互逻辑

### ISSUE THREAD

**Issue by henflower** [Kenshin/simpread#4407]
经常阅读保存英文资料，使用全文翻译翻译特定段落需要先找到左侧按钮再选择段落再取消，在标记和全文间切换有些麻烦。最近发现一个叫LegeReader的Chrome插件，是和简悦一样进行页面重排（不过做的很烂）。当光标移动到某一段落上时，会在段落末尾出现段落翻译的按钮。![image](https://user-images.githubusercontent.com/110607018/185524859-7c14a402-3abb-4e39-8fe1-a3f353e9f0d5.png)
段落翻译的交互逻辑可以改成在侧边按钮打开段落翻译后在移动到的段落末尾出现小按钮，并为高亮句子自动生成其翻译（类似Zetero的PDF翻译插件那种，打开翻译则在导出标注时将原句和翻译直接绑定）。
另：为什么我在澳大利亚打不开你们的官网和官方文档，插件的页面加载也特别慢。

**Comment by Kenshin** [comment]
> 为什么我在澳大利亚打不开你们的官网和官方文档，插件的页面加载也特别慢。

应该是这两天出现的问题，因为部分 JS Lib 换用了国内的  CDN 导致，文档的话，可以看 http://ksria.com/simpread/docs2 这个是专门针对外网用户准备的。

关于上面这链接的推送，建议订阅 https://simpread.pro/subscribe 有任何新功能都会通过此方式推送。

***

关于你的建议是希望在每个段落的末尾提供 icon ？

> 为高亮句子自动生成其翻译

会考虑你的建议。

**Comment by Kenshin** [comment]
嗨，[全文翻译](https://github.com/Kenshin/simpread/discussions/1593) 更新到了 1.1.0 增加了你提到的功能，如何使用，[细节看这里](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

https://user-images.githubusercontent.com/81074/187070868-c72cc2a9-9584-4b4d-aa8c-2ae88ae4d20a.mp4

除此之外，还增加了：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

***

我关闭这个 Issues 了，有任何问题可随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，划词翻译 1.0.0 版发布了，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4

**Comment by Kenshin** [comment]
嗨，我在考虑切换某些 CDN 环境，方便的话，帮忙测试下。

请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？同时请告知速度如何？
