### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by bolecodex** [Kenshin/simpread#4408]
发生问题的地址: <https://contracts.amazon.com/agreement?token=453c11d7-3f90-4ef2-951d-f578cf59d1d7>

**Comment by Kenshin** [comment]
嗨，这个链接我没法访问，你可以试试这几个功能 https://github.com/Kenshin/simpread/discussions/3340

如果不是有正文的页面，其实不适合使用简悦。
