### ISSUE TITLE
关闭阅读模式头部的引用块

### ISSUE THREAD

**Issue by TTtrace** [Kenshin/simpread#4409]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/39454079/185726040-7d8374ed-8c37-46d7-a0a6-67bf8ce88bd3.png">

如图，进入阅读模式后生成这样一个大的引用块，其内容往往是文章第一句话。然而实际上这句话其实很难说是文章的主题，所以想问下能在哪里把这个关闭呢？

**Comment by Kenshin** [comment]
嗨，你可以试试 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v 这个插件。

如果无法安装的话，[解决方案](https://github.com/Kenshin/simpread/discussions/2342)。
