### ISSUE TITLE
在【自定义样式】-【白练】中，设定的正文字体颜色，保存后，字体颜色不生效

### ISSUE THREAD

**Issue by Benson1997** [Kenshin/simpread#4411]
如题。
因为子自定义全局样式中，设置了背景色为绿色，所以希望将字体颜色设置为纯黑，提高一下页面整体的对比度，看的比较舒服点。默认的深灰色的字体颜色，看着感觉有点模糊。
几个默认的主题，都没有纯黑色字体的。所以也没办法通过将背景色设置到其他默认主题上来实现。

**Comment by Kenshin** [comment]
> 设定的正文字体颜色，保存后，字体颜色不生效

字体不生效有可能是没有刷新或者因为页面的 CSS 互相污染造成的。

你可以使用一些其他方式解决这个问题，自定义样式可以看 [这几个例子](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3Atheme)
