### ISSUE TITLE
保存的知乎文章在稍后读阅读模式中空白

### ISSUE THREAD

**Issue by Lackel** [Kenshin/simpread#4412]
使用Chrome插件保存知乎文章到稍后读，进入稍后读阅读模式页面空白，其他页面保存正常。
![image](https://user-images.githubusercontent.com/39994881/185733184-b4c1ded7-a54f-48a3-a7c6-1126ed53bec1.png)

**Comment by Kenshin** [comment]
嗨，知乎这类页面比较特殊，需要配置 [知识库](https://www.yuque.com/kenshin/simpread) 后使用
