### ISSUE TITLE
动作-导出所有功能都不能执行

### ISSUE THREAD

**Issue by IOSure** [Kenshin/simpread#4413]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/38939899/185765763-2eee57ab-86c7-4533-afa9-d1d056f07c04.png">

**Comment by Kenshin** [comment]
是不是用了同步助手，但没有激活它？看看你的同步助手是否正常显示你的 UID？如何激活的话，看这里 https://github.com/Kenshin/simpread/discussions/2754

**Comment by IOSure** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/38939899/185823065-d3085db4-40d8-480e-bb8f-55165774cfa7.png">
谢谢了！，真是麻烦了，是我的问题。
我是用oneDrive同步obsidian，每次导出到了obsidian库中。
我之前设置电脑语言是“英语”，前一段时间改为了“中文”，所以导致onedirve的本地路径地址随着机器自动改为了中文，如下：/Users/wangshuo/Library/CloudStorage/OneDrive-个人/Obsidian/简悦
简悦同步导出设置，还是英文，OneDrive-Personal，所以每次导出都报错。

**Comment by Kenshin** [comment]
哈哈，原来是导出路径出错了~

没问题就好，一般来说你最开始提的问题都是常规设置的问题，不会出现问题的，否则早就被发现了。

***

要是简悦帮助到你的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
