### ISSUE TITLE
不知道动了什么设置，在微信公众号文章上面，进入阅读模式，提示配置更改，刷新后使用，但是刷新后仍然跳出这个页面，刷新后还是不行。

### ISSUE THREAD

**Issue by zhaoyundi** [Kenshin/simpread#4414]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
重启浏览器。

因为同一个 URL 开了多个。
