### ISSUE TITLE
关于定制导出的问题

### ISSUE THREAD

**Issue by pencilboxshotmail** [Kenshin/simpread#4415]
在使用简悦同步助手+logseq+坚果云的方案时，阅读标注和稍后阅读标注定制导出到output文件夹，生成的文件名自动有数字前缀（如“5-Pro-Trump wins in blue states threaten GOP hopes in November - AP News.html”）。这导致在logseq中无法打开标注页面，提示“Error: ENOENT: no such file or directory, stat 'C:\Users\Sean Penn\Nutstore\1\SimpRead\output\Pro-Trump wins in blue states threaten GOP hopes in November - AP News.html'。 
但是当把文件名前的数字前缀”5-“去掉后，则能正常在logseq中正常打开。

在创建定制导出时，使用相关设置及模板如下：
”当导出到本地时，是否开启自定义标题功能？————是
然后请在弹出的框中复制粘贴这段代码：{{id}}{{un_title}}{{mode}}
是否开启自定义 Markdown 模板功能？——————是
模板：
#[[excerpt]] [{{title}}]({{url}}) 
- tags: #[[SimpRead]] {{tags}}
- read date: [[{{date_format|now|yyyy_MM_dd}} ]]
- desc: {{desc}}
{{#each}}
- [📌](<{{an_int_uri}}>)  {{an_html}}
{{>|an_note}}{{an_tags}}
{{/each}}
当导出单条标注时，是否使用单条的定制模板？————是
模板：
{{#each}}
[{{an_text}}](<{{an_ext_uri}}>)
{{/each}}

我不知道哪里出了问题？应该怎样处理？
求大神指导。

**Comment by lyserenity** [comment]
你是看了哪篇教程？可以的话，提供一下，有点不确定你想要达到的效果是什么，不容易对症下药。

我先假设下，你想要 logseq 里的右侧边栏打开标注的文件，可以先测试下：

1. 有运行同步助手
2. output 里有文件 
3. 先试看看在浏览器里打开 `http://localhost:7026/unread/1?embed=logseq` 这个链接，看看有正常显示文章内容：
    （先确定 output/ 里有个 `1-XXXXXXX.html` 的文件）

如果有报错或是跳出任何提示，都截个图贴上来.....

**Comment by Kenshin** [comment]
@lyserenity 

应该是这篇 https://sspai.com/post/72022

**Comment by pencilboxshotmail** [comment]
@lyserenity 
lyserenity，没错，是 [lyserenity](https://github.com/lyserenity)攻略

> @lyserenity
> 
> 应该是这篇 https://sspai.com/post/72022

**Comment by pencilboxshotmail** [comment]
看的是这篇 https://sspai.com/post/72022教程。
然后按照您说得，在浏览器里打开 http://localhost:7026/unread/1?embed=logseq 这个链接，正常显示没文章，没有报错。
可是当1-XXXXXXX.html，变成 5-XXXX.html时，在logseq中报错。
md文件能够正常生成，见下图。
![image](https://user-images.githubusercontent.com/111672485/185869778-6ca00e9c-87f9-42c3-8745-e44b7d0e8624.png)
logseq中点击标注报错见下图。
![image](https://user-images.githubusercontent.com/111672485/185870371-6153b3cd-79e4-48fa-a38e-eca6ad3edbae.png)


> 你是看了哪篇教程？可以的话，提供一下，有点不确定你想要达到的效果是什么，不容易对症下药。
> 
> 我先假设下，你想要 logseq 里的右侧边栏打开标注的文件，可以先测试下：
> 
> 1. 有运行同步助手
> 2. output 里有文件
> 3. 先试看看在浏览器里打开 `http://localhost:7026/unread/1?embed=logseq` 这个链接，看看有正常显示文章内容：
>    （先确定 output/ 里有个 `1-XXXXXXX.html` 的文件）
> 
> 如果有报错或是跳出任何提示，都截个图贴上来.....

**Comment by lyserenity** [comment]
你可以看一下 📌 的链接，里面的 title=XXXXX.html ，xxxxx 是不是包含空格，如果是的话可能会有问题。

你可以去下载[这个插件](https://simpread.ksria.cn/plugins/details/tMGXrU1v0U) 试试，如果还是不行就找作者来回答你 😓

**Comment by pencilboxshotmail** [comment]
@lyserenity 我试了一下，似乎是简悦自动化功能引起的。简悦在自动化时（如图）标注后导出的.html文件和.md文件都会在文件名自动加入序号（如“15-简悦 +Logseq 个人知识库搭建 - 从零开始完全指南.html”）。似乎因为这个原因，导致在md文件中，无法访问从 @annote 的 markdown 文件里面复制出来的 localhost 链接（如实际链接为http://localhost/:7026/pdf/简悦 +Logseq 个人知识库搭建 - 从零开始完全指南#id=1661696662912），因为md文件中的指向的html文件名是不带序号的。请问这个如何处理？谢谢大佬！
![image](https://user-images.githubusercontent.com/111672485/187079814-a5b4ab84-9013-45d5-bec8-67e3a7747f15.png)
