### ISSUE TITLE
Instapaper 加星后自动保存到简悦的稍后读的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4420]
![image](https://user-images.githubusercontent.com/3283576/186072272-8a91b78a-8bd3-4cbe-85c9-23cd0545b54d.png)
indx 编号 一直没有变化是什么原因？

_Originally posted by @yaogjim in https://github.com/Kenshin/simpread/discussions/3034#discussioncomment-3453075_

**Comment by Kenshin** [comment]
@yaogjim

嗨，我新建了一个 Issues 来讨论。

***

感觉是同时加多个星造成的，你可以试试仅加一个星，等确定更新后再加另外一个（只是用来测试而已）

**Comment by yaogjim** [comment]
我重置配置，清空内容，然后index恢复正常了。

**Comment by yaogjim** [comment]
instapaper 用webhook到api中，在阅读列表中可以看到内容。
在 稍后读看不到，是因为什么？

-----

**Comment by Kenshin** [comment]
是不是没有配置读取本地快照？看看 [这个教程](https://www.yuque.com/kenshin/simpread/wkswh7)

**Comment by yaogjim** [comment]
感谢回复，是我的问题。
坚果云同步没有开好。

**Comment by Kenshin** [comment]
哈哈，小事情，搞定就好。

看起来动手能力比较不错~ 👍 我关闭这个 Issues 了。


***

要是简悦帮助到你的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by yaogjim** [comment]
👌
