### ISSUE TITLE
适配机核网

### ISSUE THREAD

**Issue by murazi** [Kenshin/simpread#4421]
例：https://www.gcores.com/articles/155207

试了几次，大部分文章无法读取图片，只能读取出文字

极个别文章可以读取出图片，试过手动高亮，有的能选出图片，但会出现莫名其妙的文章内容

**Comment by Kenshin** [comment]
收到，适配后会在这里通知你~

**Comment by xiang578** [comment]
日常来催一下，目前还没有这个问题。另外关联的 https://github.com/Kenshin/simpread/issues/3522

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/68hAvoc6pC 安装。

同时因为这个站是动态加载的，所以需要将 `cores.com` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

PS：如果在使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装此站点。

**Comment by Kenshin** [comment]
@murazi 

图片的问题果然 😂 ... 

> 机核网的图片有个幻灯片式的播放器

给个 URL 瞧瞧。

**Comment by murazi** [comment]
> @murazi
> 
> 图片的问题果然 😂 ...
> 
> > 机核网的图片有个幻灯片式的播放器
> 
> 给个 URL 瞧瞧。

嗯嗯
https://www.gcores.com/articles/164574#nopop_97qf1
比如这个链接，图片比较多，拉到最下面，会有一个幻灯片占位，左右切换可以选择图片

**Comment by Kenshin** [comment]
好，我先 Mark 下
