### ISSUE TITLE
腾讯问卷购买了高级账户的咨询

### ISSUE THREAD

**Issue by ajdre2015** [Kenshin/simpread#4427]
![QQ截图20220826084947](https://user-images.githubusercontent.com/12594155/186793369-521778fa-7889-41cd-873a-64228a82ea24.png)

**Comment by Kenshin** [comment]
嗨，我看到你的提交信息了，应该没问题。

同时你应该收到了来自 `licen***@simpread.pro` 的邮件，请通过这个邮箱给我发个邮件，我会把兑换码手动给你的。
