### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by haiyihanmam** [Kenshin/simpread#4429]
东西都是最新的，是高级账户 在这个场景下导出pdf失败，期待回复。

**Comment by haiyihanmam** [comment]
同一个网站的文章，另一个标题能保存，这个标题不能保存

**Comment by Kenshin** [comment]
出错的 URL 给我。

另外，保存 PDF 是有可能出错的，所以建议使用 https://github.com/Kenshin/simpread/discussions/3887

**Comment by haiyihanmam** [comment]
http://jhsjk.people.cn/article/32240855

**Comment by haiyihanmam** [comment]
![image](https://user-images.githubusercontent.com/94858991/186942641-5e7be88f-be5f-4842-8d8f-db7f89b2e490.png)
安装插件后，仍然无法使用，请看图

**Comment by haiyihanmam** [comment]
http://jhsjk.people.cn/article/32308911

**Comment by Kenshin** [comment]
我测试了下，都没问题的，你可以使用 [PDF 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3887) 使用浏览器打印方式或者基础或高级方案都可以。

![image](https://user-images.githubusercontent.com/81074/187012295-2adb34c3-dcb9-46c7-9457-7b9a4bb29aa4.png)

**Comment by haiyihanmam** [comment]
您没有问题，我为什么会报错啊，这截图总不能骗人呀



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2022年08月27日 11:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Kenshin/simpread] 报错 (Issue #4429) |

Closed #4429 as completed.

**Comment by Kenshin** [comment]
所以，我让你按照 https://github.com/Kenshin/simpread/issues/4429#issuecomment-1228630397 试试。

或者试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 。

另外，如果你使用我提高到 PDF 辅助增强插件的话，使用浏览器打印方案也能成功导出。

**Comment by haiyihanmam** [comment]
我忘记说了，后来反馈的图就是增强插件报的错。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2022年08月27日 12:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Kenshin/simpread] 报错 (Issue #4429) |

所以，我让你按照 #4429 (comment) 试试。

或者试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 。

另外，如果你使用我提高到 PDF 辅助增强插件的话，使用浏览器打印方案也能成功导出。

**Comment by haiyihanmam** [comment]
我再试试#4429



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2022年08月27日 12:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Kenshin/simpread] 报错 (Issue #4429) |

所以，我让你按照 #4429 (comment) 试试。

或者试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 。

另外，如果你使用我提高到 PDF 辅助增强插件的话，使用浏览器打印方案也能成功导出。
