### ISSUE TITLE
稍后读，无法打开

### ISSUE THREAD

**Issue by wongtx** [Kenshin/simpread#4430]
如题，昨晚就就无法打开，尝试重启也无解。稍后读访问的地址是 extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/unreader/main.html

**Comment by wongtx** [comment]
![image](https://user-images.githubusercontent.com/46996862/187003335-22d05b23-13bc-489e-a2a0-193f4f5bfbdf.png)

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2727 如果是因为配置文件出错的话，请看这里 https://github.com/Kenshin/simpread/discussions/3165

**Comment by wongtx** [comment]
感谢。删除null字段都恢复

**Comment by Kenshin** [comment]
okay 搞定就好。

另外，能否回忆出错的 URL 是如何添加的吗？

**Comment by wongtx** [comment]
我是直接在json文件内搜索null字段，选择在annotation（annotator?）键对应的值字典中的null。写到这里，我突然明白你的问题了，我试着去找找。好像是少数派的这篇 **https://sspai.com/post/71274** 具体位置没有排查（排查成本太大了）

**Comment by Kenshin** [comment]
谢谢排查。

我的意思问 https://sspai.com/post/71274 这个链接以什么形式加入的？API？Telegram？扩展端加入？还是？

**Comment by wongtx** [comment]
是通过网页加入的稍后读（应该是扩展端吧？）

**Comment by Kenshin** [comment]
> 是通过网页加入的稍后读（应该是扩展端吧？）

那出错的可能性应该很小，你在多留意下~

**Comment by Kenshin** [comment]
哈哈，我喜欢这么 Nice 的用户。🙏
