### ISSUE TITLE
稍后读内容无法同步到ob

### ISSUE THREAD

**Issue by wongtx** [Kenshin/simpread#4431]
前段时间配置了最新的简悦插件以及工作流配置，实现了不论是直接在网页阅读还是在稍后读都可将标注内容同步到ob。但是，在今天使用过程中，出现了mull字符导致稍后读空白问题（已解决）后，稍后读的标注内容无法同步只ob。

**Comment by Kenshin** [comment]
这个问题跟 https://github.com/Kenshin/simpread/issues/4430 无关。

既然配置过一次，可以试试 check 下你的流程跟教程有什么区别。

另外，通过简悦导入到 Obsidian 的方式有很多，所以最好是根据教程对比下。

**Comment by wongtx** [comment]
目前我检查过流程所有的配置，均正常。网页直接进入阅读模式后，标注同步是正常的。但是加入稍后读的文件，却无法正常同步标注。具体如图。目前实在想不到其他的原因了
![Snipaste_2022-08-27_18-00-57](https://user-images.githubusercontent.com/46996862/187026036-9c6d7232-299e-49ac-8b2b-81f03341f56b.png)

**Comment by Kenshin** [comment]
看截图是通过稍后读来同步的，如果你使用了 导入到 Obsidian 的话，是不支持通过稍后读导出的，你可以在原文的阅读模式上测试下。

**Comment by wongtx** [comment]
谢谢，我的疑问解除了。我的确是通过稍后读进行批注的，网页阅读批注是正常的。希望未来可以支持稍后读界面的批注同步。再次感谢简悦的开发人员

**Comment by Kenshin** [comment]
接下来的版本会解决这个问题。

如果用 obsidian simpread sync 的话，其实可以试试 https://github.com/Kenshin/simpread/discussions/2889


***

要是简悦帮助到你的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by wongtx** [comment]
我用的是edge，已在微软商店评价

**Comment by Kenshin** [comment]
👍 😁
