### ISSUE TITLE
高级账户绑定设备的问题

### ISSUE THREAD

**Issue by YangWaldon** [Kenshin/simpread#4432]
最多绑定3台设备，难道同一个电脑的两个浏览器也是两个设备吗？我最多就绑定过3个浏览器，可是为什么我今早将本地配置文件导入到浏览器之后（操作了多次），就提示我账户绑定设备超过次数，需要退出登录才行。
虽然我的问题已经在[简悦 · 高级账户平台](https://simpread.pro/account)得到了解决， 解锁了全部设备之后  ⇢  再次将本地配置文件导入到浏览器中就可以了。
但是我还是想搞明白这个问题的原因是什么，以防下次再遇到

**Comment by Kenshin** [comment]
> 同一个电脑的两个浏览器也是两个设备吗？

不是，同一个电脑的不同浏览器算一个设备。

但如果你的硬件参数（一般来说的显示器的分辨率或者多显示器）会有误判的情况，但极偶尔情况会因为「导入到浏览器之后（操作了多次）」被 Ban。
