### ISSUE TITLE
utools里搜索到稍后读 打开是否支持用浏览器打开？

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#4433]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38575961/187058348-181ea249-7f3c-46bb-8c15-ea2faca57a67.png">
 
目前点击 好像是直接 打开一个 不可编辑不可复制的窗口
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/38575961/187058369-d56065c0-b33b-413e-bcf6-3490411bca4e.png">

能否该窗口 支持选中文字 复制 或者 直接可以浏览器打开

**Comment by Kenshin** [comment]
> 打开是否支持用浏览器打开

可以的，在 uTools 里面设置 https://github.com/Kenshin/simpread/discussions/3108

**Comment by enron2014** [comment]
> > 打开是否支持用浏览器打开
> 
> 可以的，在 uTools 里面设置 #3108

这里设置吗  我已经输入了谷歌浏览器的全路径 可是为何还是不行呀
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38575961/187059400-e2d6b423-bf29-4e6e-987a-44f140dc3ade.png">

**Comment by Kenshin** [comment]
关闭使用 URL Scheme

**Comment by enron2014** [comment]
> 关闭使用 URL Scheme


URL Scheme 已关闭
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38575961/187061926-04c63084-9636-43d6-85e3-b965a53b102e.png">




但是 点击后 毫无反应
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38575961/187061909-340e0ff5-d5d6-4cdb-b8d2-d564c01049c6.png">

**Comment by Kenshin** [comment]
把浏览器的也取消了，使用默认值。

**Comment by Kenshin** [comment]
嗨，我发现你提了好多 Issues 但大部分被解答后都没有下文，所以我关闭了它们，也包括这个 Issues

有任何疑问可以随时在这里讨论。
