### ISSUE TITLE
搜索不到文中的关键词

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#4434]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/38575961/187058591-3e3b8b77-c3b1-45ac-9474-cfe8ee67a2fc.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/38575961/187058606-ccee9685-8f77-4ac5-a782-938aea8599fc.png">

可是明明文中是有这个关键词的
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/38575961/187058630-83d16c72-5447-42b2-bfe8-60e55d1963d1.png">

**Comment by Kenshin** [comment]
没理解你要搜索的内容是什么（截图没有体现出来）

**Comment by enron2014** [comment]
> 没理解你要搜索的内容是什么（截图没有体现出来）

稍后读里 有一篇文章  文章里有 “自定义”这个关键词

但是当我在这里搜索这个关键词的时候 并搜不到这篇文章
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/38575961/187059097-6c90ac83-fb6e-44d3-9137-fbb279d4e0e8.png">

**Comment by Kenshin** [comment]
点击**了解更多**，可以知道搜索方案。

如果你想搜索的是全文的话，暂时还不支持全文搜索，你可以使用 Devonthink 等第三方工具辅助搜索 https://github.com/Kenshin/simpread/discussions/3235

**Comment by Kenshin** [comment]
嗨，我发现你提了好多 Issues 但大部分被解答后都没有下文，所以我关闭了它们，也包括这个 Issues

有任何疑问可以随时在这里讨论。

**Comment by Kenshin** [comment]
要是简悦帮助到你的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
