### ISSUE TITLE
obsidian中稍后读极速版无法显示微信公众号文章的图片

### ISSUE THREAD

**Issue by Airmansy** [Kenshin/simpread#4435]
obsidian中点击内部链接，稍后读极速版无法显示微信公众号文章的图片
![image](https://user-images.githubusercontent.com/112327874/187075968-0ebf3625-304e-416b-911e-86c3691f152a.png)
但是在极速版中做批注时如果选中图片，左边标注中又能正常显示
![image](https://user-images.githubusercontent.com/112327874/187076416-cb32d19f-6b65-41d9-974b-97a5ce2f7f1a.png)
请问要怎么在稍后读极速版中显示图片？

**Comment by Kenshin** [comment]
嗨，这是因为 wx 的图片有防盗链的功能导致的，有两个方案：

1. 使用 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将图片转换为你自己的图床。
2. 本地快照使用离线 HTML 方式。

我建议使用方案一。

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
