### ISSUE TITLE
使用Local REST API 导入方案标题名含有斜杠'/'导致保存失败

### ISSUE THREAD

**Issue by GeigerCounts** [Kenshin/simpread#4441]
url : https://github.com/grpc/grpc
阅读模式生成的标题名：grpc/grpc: The C based gRPC (C++, Python, Ruby, Objective-C, PHP, C#)

[github.com-1661841893512.log](https://github.com/Kenshin/simpread/files/9450497/github.com-1661841893512.log)

**Comment by Kenshin** [comment]
嗨，你可以安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 来解决这个问题。

**Comment by GeigerCounts** [comment]
[github.com-1661852967151.log](https://github.com/Kenshin/simpread/files/9451775/github.com-1661852967151.log)
安装后标题修改了，还是会保存失败

**Comment by Kenshin** [comment]
嗨，测试了下，确实如此。

你可以使用 SimpRead Sync 导入方式，我刚测试过了，是没问题的。

我先重开这个 Issues ，但 Github 比较特别，不确定是否可以解决。

**Comment by Kenshin** [comment]
嗨，这个问题已经 Fixed 掉了，请通过 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 重新安装（升级）这个插件。

如果无法安装或插件触发器失效，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

**Comment by GeigerCounts** [comment]
真棒👍

**Comment by Kenshin** [comment]
竟然隔了这么久才回复。 😂

***

请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
