### ISSUE TITLE
简悦如何对离线html文件进行标注？

### ISSUE THREAD

**Issue by adolis** [Kenshin/simpread#4444]
![image](https://user-images.githubusercontent.com/8793721/187612971-27e07c53-97be-415f-a91e-7859d6e2f5b0.png)

如上图，离线的Html文件无法使用简约进行阅读或者批注。

**Comment by Kenshin** [comment]
嗨，其实一直都是可以的，你可以读取本地 HTML，并使用阅读模式，但无法加入稍后读（因为个 Bug 导致，功能都在的） 😂 

修复这个 Bug 后我会通知你的~

关联 https://github.com/Kenshin/simpread/issues/3828

**Comment by adolis** [comment]
> 嗨，其实一直都是可以的，你可以读取本地 HTML，并使用阅读模式，但无法加入稍后读（因为个 Bug 导致，功能都在的） 😂
> 
> 修复这个 Bug 后我会通知你的~
> 
> 关联 #3828

我现在是离线文件的时候，都没办法使用简约阅读模式，这个插件是黑的😂😂

**Comment by Kenshin** [comment]
看下 https://github.com/Kenshin/simpread/discussions/1689 就能读本地了，如果用了同步助手的话，就会出现我之前提到的错误，否则没问题。

**Comment by adolis** [comment]
> 

cool！！！ 非常感谢

**Comment by Kenshin** [comment]
哈，看来没有使用同步助手？

**Comment by adolis** [comment]
> 哈，看来没有使用同步助手？

我有用呢，我从简悦同步到obsidian都完成了

**Comment by Kenshin** [comment]
okay 但使用了同步助手，就会遇到我最开始说的 Bug，目前只能下个版本解决，但我会考虑用其他方式实现。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
