### ISSUE TITLE
关于购买的疑问

### ISSUE THREAD

**Issue by Daemonson** [Kenshin/simpread#4446]
请问未注册账号的情况下购买支付完成后，多久给邮箱发送邮件？无法登陆，也无法使用邮箱找回注册码

**Comment by Kenshin** [comment]
嗨，你是指通过腾讯问卷方式购买吗？如果是的话，在购买前已经标出了：非实时发送兑换码，24 ~ 48 小时。

昨天晚上 20 点之前刚发了一批，如果你是在这个时间段购买的话，应该是明天晚上 20 点之前。

**Comment by Daemonson** [comment]
好的，非常感谢

Kenshin Wang ***@***.***> 于2022年9月1日周四 10:52写道：

**Comment by Kenshin** [comment]
小事情~

你可以先使用阅读模式以及插件相关功能，这些都是免费使用的。
