### ISSUE TITLE
知乎gif适配问题

### ISSUE THREAD

**Issue by Zeroto521** [Kenshin/simpread#445]
## 问题描述

1. 当知乎（无论**专栏**或者是**问答**）存在gif图时，需要在未适配前进行**点击**，适配后才能进行动画**演示**。
2. 存在多张gif图时，仅能同时演示一张gif图（这个是知乎的锅）

## 示例站点

https://zhuanlan.zhihu.com/p/44240004

**Comment by Kenshin** [comment]
确实有这个问题，因为知乎把 gif 转了一次，简悦在生成阅读模式的适合抓取失败造成的...

谢谢反馈，我先记 Bug~

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，解决了此问题。

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869
