### ISSUE TITLE
导入到Obsidian插件失效

### ISSUE THREAD

**Issue by iFryRice** [Kenshin/simpread#4450]
版本号：简悦(同步助手)-1.1.2，插件版本 - 1.3.1，Obsidian客户端 v0.15.9，Win11
插件先前配置没有问题，可以正常使用，最近突然开始不能导出全文以及批注，以下是错误截图，请问我还需要提供哪些信息吗？
![image](https://user-images.githubusercontent.com/102138235/188058782-ef121bd2-6eee-4200-aba7-8877be683034.png)
![image](https://user-images.githubusercontent.com/102138235/188058484-d0c4d1b1-4fcd-4fdf-97b5-a9fa8ec43d84.png)
![image](https://user-images.githubusercontent.com/102138235/188058563-90339df2-ba7e-406e-b6e0-3352158b9ba5.png)

**Comment by iFryRice** [comment]
![image](https://user-images.githubusercontent.com/102138235/188059188-3e3415e4-6820-4107-891c-ab50d03f55e6.png)
有的站点可以，有的不可以...（请忽视这个Yaml，貌似哪里出了Bug）

**Comment by Kenshin** [comment]
嗨，导入全文使用的是什么方式？尽量（跟这个插件有关的）截图全面些，我才好判断。

另外，Obsidian 并不是很稳定，你可以新开一个库，然后仅安装相关插件看看排除 Obsidian 的问题。

给我一个好使的 URL，以及不好使的 URL

**Comment by iFryRice** [comment]
导入全文是 Local REST API 的方案，配置如图：
![image](https://user-images.githubusercontent.com/102138235/188063073-385e7cf8-f98e-497d-98f8-b13f681ae9af.png)
URL(导入失败)：https://www.jianshu.com/p/b1614a073087 
URL(成功，但是微信公众号的文章抓取之后，YAML区title那里不太对劲，还没有搞清楚是哪里出了问题)：https://mp.weixin.qq.com/s/e7JBmNiA2tDwNLyR76-yOg ；https://www.zhihu.com/question/28358499

**Comment by iFryRice** [comment]
> ![image](https://user-images.githubusercontent.com/102138235/188059188-3e3415e4-6820-4107-891c-ab50d03f55e6.png) 有的站点可以，有的不可以...（请忽视这个Yaml，貌似哪里出了Bug）

导入全文的时候，目前发现的是 只有 微信公众号的文章 YAML 部分Title 有问题

**Comment by Kenshin** [comment]
试试安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看能否解决？

> https://mp.weixin.qq.com/s/e7JBmNiA2tDwNLyR76-yOg

标题是因为这篇公众号使用了不规范的标题造成的，算是个例。

**Comment by iFryRice** [comment]
> 试试安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看能否解决？
您好，安装了插件，重新加载页面，依然提示 保存失败 。

**Comment by Kenshin** [comment]
okay 抱歉，之前乌龙了，我使用了

![image](https://user-images.githubusercontent.com/81074/188092657-85fb376b-b063-4a93-a274-43f6004192cf.png)

你提到的方式确实有问题，这个问题是因为 Local REST API 造成的，已记录。

建议使用截图提到的方案。

修复后我会在这通知你~

**Comment by iFryRice** [comment]
好的好的，我去看看新的同步方式，谢谢大佬的耐心解答~

**Comment by iFryRice** [comment]
>  ![](https://user-images.githubusercontent.com/81074/188092657-85fb376b-b063-4a93-a274-43f6004192cf.png)

刚刚去切换成了这种同步方式，简书的那个网站（https://www.jianshu.com/p/b1614a073087）还是不能够正常导入到Ob，去尝试了简书其他的网站，是可以正常导入的。

**Comment by Kenshin** [comment]
> 刚刚去切换成了这种同步方式，简书的那个网站（https://www.jianshu.com/p/b1614a073087 ）还是不能够正常导入到Ob，去尝试了简书其他的网站，是可以正常导入的。

应该没问题的，但你可以看下图，但提示确实有点问题，所以你确认下是否正确导入了。

![image](https://user-images.githubusercontent.com/81074/188125805-23716dc8-544c-462f-9937-fd42144d9264.png)

**Comment by iFryRice** [comment]
> 但提示确实有点问题

发现 ” 提示在Ob中没有找到相关文件 “ ，但是文件列表中确实出现了这个文件....

**Comment by Kenshin** [comment]
> 发现 ” 提示在Ob中没有找到相关文件 “ ，但是文件列表中确实出现了这个文件....

哈，是的，我稍后会优化这里，跟之前你提到的 Bug 一样~

**Comment by Kenshin** [comment]
嗨，这个问题已经 Fixed 掉了，请通过 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 重新安装（升级）这个插件。

如果无法安装或插件触发器失效，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
