### ISSUE TITLE
qq word在线文档，应该怎么加载？

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#4451]
发生问题的地址: <https://docs.qq.com/doc/DSGFPYW5saFdFY2xo>
试过手动识别，把网页放入延迟加载也不行
请问应该如何操作呢？还是QQ DOC 无法使用？

**Comment by Kenshin** [comment]
嗨，虽然大概率可以适配，但因为涉及到版权等问题，一般这类页面都不会收录和官方适配的。

**Comment by angel126** [comment]
自用，笔记谈不上版权呀？
