### ISSUE TITLE
导入到obsidian和导出 org-mode插件问题

### ISSUE THREAD

**Issue by LZS12** [Kenshin/simpread#4452]
- 插件里已经安装窃没有禁用，但阅读模式里动作里不显示。
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/87900516/188170111-3a534cbe-a38f-4915-8585-978ea2e926e8.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/87900516/188170149-849c1570-0d96-46e7-b710-bd03ab141ff8.png">

**Comment by Kenshin** [comment]
嗨，这是一个简悦的隐性 Bug，解决方案看这里 https://github.com/Kenshin/simpread/discussions/2342

或者直接使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 直接安装。

**Comment by LZS12** [comment]
谢谢，已解决。

**Comment by Kenshin** [comment]
Cool ~ 搞定就好。

PS：简悦近期在搞一个年中抽奖活动，感兴趣的话，你可以试试手气 https://simpread.zhubai.love/posts/2177402534795317248
