### ISSUE TITLE
关于如何安装和配置同步助手的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4454]
兄弟，你那个坚果云的目录没太写清楚（也可能是我第一次用不在明白，可以写清楚些

_Originally posted by @mhton1 in https://github.com/Kenshin/simpread/discussions/2754#discussioncomment-3537157_

**Comment by Kenshin** [comment]
@mhton1 

嗨，我新建了个 Issues 来讨论这个问题。

***

不过，其实我没有理解你的问题在哪里？关于坚果云的目录来说其实很简单，安装坚果云，然后设定同步目录就行了，

但这个目录的名称必须是 `SimpRead`  比如

`C:\Users\xxxx\Documents\xxx\Nutstore\SimpRead`

**Comment by mhton1** [comment]
是我当时糊涂了，不太清楚，现在已经开始探索开发中心了。当时就是以为要现在本地建目录，再同步到坚果云，再在同步助手上选目录。

**Comment by Kenshin** [comment]
哈哈，欢迎探索，开放平台的话，可以看这个教程 https://github.com/Kenshin/simpread/discussions/2757

**Comment by Kenshin** [comment]
另外，简悦目前在搞一个年中抽奖，感兴趣的话，可以试试手气，详细说明 https://simpread.zhubai.love/posts/2177402534795317248
