### ISSUE TITLE
标题无特殊字符，导入obsidian失败。

### ISSUE THREAD

**Issue by B1INGO** [Kenshin/simpread#4455]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **版本 105.0.5195.52（正式版本） (x86_64)**

- 简悦版本 **当前最新版**

- 发生问题的地址  https://pytorch.org/docs/stable/tensors.html#torch.Tensor

**请描述你的问题**

> 导入obsidian时，显示保存失败。此页面标题并无特殊字符。
同网站另一个页面可以正常导入。https://pytorch.org/docs/stable/nn.html
**截图**
![截屏2022-09-03 12 13 20](https://user-images.githubusercontent.com/20365172/188255430-fb3fd08d-b64b-4551-8d3b-7964a411bad3.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，我测试了下，是可以导入的

![image](https://user-images.githubusercontent.com/81074/188255751-c8b02193-6742-400f-a6e9-2efde2718c3b.png)

但使用了这种方案

![image](https://user-images.githubusercontent.com/81074/188255822-352bf322-f26c-40f5-b70a-7554add40886.png)

但这个页面因为没有适配，再加上结构并不规整，导致获取的正文内容不是很好。

PS：使用 `Local REST API` 确实没有正确导入

**Comment by B1INGO** [comment]
我使用的确实是：Local REST API 
习惯用方式2⃣️的导入方式。还是希望修复一下这个问题。


| |
BINGO
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2022年09月3日 12:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 标题无特殊字符，导入obsidian失败。 (Issue #4455) |

嗨，我测试了下，是可以导入的

但使用了这种方案

但这个页面因为没有适配，再加上结构并不规整，导致获取的正文内容不是很好。

PS：使用 Local REST API 确实没有正确导入

**Comment by Kenshin** [comment]
嗨，这个问题已经 Fixed 掉了，请通过 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 重新安装（升级）这个插件。

如果无法安装或插件触发器失效，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

**Comment by B1INGO** [comment]
使用的模式：手动选中正文，使用选中内容生成阅读模式。
效果：此方法显示的正文完整。
更新插件后使用 local rest api 确实可以成功导入。
但是导出不完整。
1⃣️原文有多个表格，导出后只有一个表格。
2⃣️原文不仅有表格，还有正常的文字段落。导出的只有表格。


| |
BINGO
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2022年09月3日 14:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 标题无特殊字符，导入obsidian失败。 (Issue #4455) |

嗨，这个问题已经 Fixed 掉了，请通过 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 重新安装（升级）这个插件。

如果无法安装或插件触发器失效，请使用 插件管理器 安装。

**Comment by Kenshin** [comment]
导的问题我之前说了，这跟之前遇到的 Bug 无关，你可以使用下图的方式解决，虽然不完美，但可以获取到正文。

![image](https://user-images.githubusercontent.com/81074/188266826-8998be17-4dd2-4233-9550-748cc7dbc30d.png)

**Comment by B1INGO** [comment]
好的，感谢。



| |
BINGO
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2022年09月3日 18:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 标题无特殊字符，导入obsidian失败。 (Issue #4455) |

导的问题我之前说了，这跟之前遇到的 Bug 无关，你可以使用下图的方式解决，虽然不完美，但可以获取到正文。

**Comment by Kenshin** [comment]
小事情~
