### ISSUE TITLE
导出markdown时 代码未换行,还望大佬看看,谢谢啦

### ISSUE THREAD

**Issue by xfhy** [Kenshin/simpread#446]
导出markdown时 代码未换行,还望大佬看看,谢谢啦

**Comment by Kenshin** [comment]
例如呢？发个网址过来~  😀

**Comment by xfhy** [comment]
例如:  https://blog.csdn.net/xiao__gui/article/details/8188833,,,谢谢大佬

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

你可以使用 [代码高亮](https://simpread.ksria.cn/plugins/details/klGUASLasg) 插件来实现你给出链接的效果。

![image](https://user-images.githubusercontent.com/81074/57268783-b9cc2280-70b7-11e9-9e18-24dbed909127.png)
