### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by Carrotist** [Kenshin/simpread#4467]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win11**

- 浏览器版本 **edge105.0.1343.27 **

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://www.yuque.com/daluobuzai/kegao/dz2k7m>

**请描述你的问题**

> 无法自动识别

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
使用 https://github.com/Kenshin/simpread/discussions/4380
