### ISSUE TITLE
导出markdown时英式单引号错处理为中式单引号

### ISSUE THREAD

**Issue by ChenWeird** [Kenshin/simpread#447]
英文页面，原文是单引号的情形，如 it's not the same.
采用simpread保存为MD时，用vim打开会变成中式引号。

**Comment by Kenshin** [comment]
谢谢反馈~ 每篇英文均是如此吗？

**Comment by ChenWeird** [comment]
几乎都是如此

**Comment by Kenshin** [comment]
我随机测试了 https://www.sciencedaily.com/releases/2019/01/190128125314.htm
没有发现你说的问题

![image](https://user-images.githubusercontent.com/81074/51879140-38c10900-23ad-11e9-86ce-9f43d296b933.png)

**Comment by ChenWeird** [comment]
看来好像是我错了，但我看这个页面的内容 https://serialized.net/
在网页上看像是英文的单引号，用simpread看就变成中文的单引号。

不知是原文本身的问题，还是simpread的问题？
我经常使用这个功能，经常碰到这个问题，以至搜索替换都成了标准工作。

**Comment by Kenshin** [comment]
@ChenWeird 

你给出链接的截图

![image](https://user-images.githubusercontent.com/81074/51888902-ccf19700-23d2-11e9-9e0d-adb1b72e4f9e.png)

![image](https://user-images.githubusercontent.com/81074/51888954-02968000-23d3-11e9-975c-17bc5f773e14.png)

[Archive.zip](https://github.com/Kenshin/simpread/files/2806363/Archive.zip)

附件是这两个链接的 md 文件，你可以比对下。

**Comment by ChenWeird** [comment]
上述Archive.zip附件的内容就存在我所述的问题：用vim等编辑器查看就特别明显。

**Comment by Kenshin** [comment]
@ChenWeird 

emmm 或许我没理解你的问题，建议最好发个图上来。

**Comment by ChenWeird** [comment]
我录制了相应视频，刚才通过邮件发了附件，但在网页这里好像看不到，为此再发一个下载链接：

[Simpread中英式引号视频下载](https://pan.baidu.com/s/1T2cLjjCb1N_71sPUfqMBBg)

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

优化了 导出到 Markdown 的各种问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)

**Comment by llinfeng** [comment]
请问，英文的单双引号如何正确显示？是不是我有个配置没弄好？ 附：[原文链接](https://www.psychologytoday.com/us/blog/master-your-success/202004/how-connect-meaningfully-in-virtual-meeting)

![image](https://user-images.githubusercontent.com/5890407/91061335-0ebbe100-e5fa-11ea-9fc3-0f6ceba72df2.png)

**Comment by Kenshin** [comment]
@llinfeng

嗨，谢谢找到了这个 Issues 并在此提问。最近有太多重复的 Issues 了，所以看到这个方式，觉得一股清流。 👍 

下面的效果如何？


![image](https://user-images.githubusercontent.com/81074/91112970-0f667d00-e6b7-11ea-800b-1543ba202703.png)


如果你觉得不错的话，可以试试这样的方式，打开
`chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/custom.html`

将下面的代码加入到 **自定义 CSS**

```
sr-rd-content p, sr-rd-content p * {
    text-align: left!important;
    font-family: "Adobe Garamond Pro", Georgia, "Times New Roman", Times, serif, -apple-system, system-ui, "Segoe UI", "Droid Sans", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Droid Sans Fallback", "Microsoft YaHei", sans-serif, sans-serif!important;
    font-size: 21px!important;
}
```

另外，如果你经常浏览英文页面的话，多请多发现些这样的问题，一并告诉我。

***

我会出一个专门用于浏览英文页面布局的插件来解决这个问题。

**Comment by llinfeng** [comment]
单、双引号的问题治好了。——这个customized CSS，是同步到Dropbox里面的哦？【这里有/没有设备数量限制？】

再有类似问题，我会来这里继续贴截图哈。

**Comment by Kenshin** [comment]
@llinfeng 

没问题，原来是你，我记住你了，哈哈。

**Comment by llinfeng** [comment]
其实你的截图里面还有个英文rendering的问题——你看标题，`ti`和`me`分作两行；正文中，感觉也在固定width的地方插入newline？

**Comment by llinfeng** [comment]
新的单引号作全角符号——[链接地址](https://today.duke.edu/2020/08/desire-be-group-leads-harsher-judgment-others?utm_medium=email&utm_source=other&utm_campaign=opencourse.GdeNrll1EeSROyIACtiVvg.announcements~opencourse.GdeNrll1EeSROyIACtiVvg.wUvDClTXTUeTVaPnzQNGHQ) 截图：

![image](https://user-images.githubusercontent.com/5890407/91579158-3328fd80-e919-11ea-80c1-83cc7e30adb7.png)

**Comment by Kenshin** [comment]
这不是全角的问题，估计是排版的问题，我明天确认下。

**Comment by llinfeng** [comment]
[新链接](https://www.michigandaily.com/section/opinion/op-ed-university%E2%80%99s-summer-lies) - 这些单双引号好烦人。再，下面高亮工具跑来跑去的事情，也有相应issue描述了吧？
![Visual_Motion_highlight_SimpleRead](https://user-images.githubusercontent.com/5890407/92192357-d60adb80-ee33-11ea-9500-5401252b721c.gif)

**Comment by Kenshin** [comment]
@llinfeng 

最近在解决 [同时开启多台设备被锁的解决办法](http://ksria.com/simpread/docs/#/%E5%B7%B2%E8%B4%AD%E5%BF%85%E8%AF%BB?id=%E5%90%8C%E6%97%B6%E5%BC%80%E5%90%AF%E5%A4%9A%E5%8F%B0%E8%AE%BE%E5%A4%87%E8%A2%AB%E9%94%81%E7%9A%84%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95) 这个问题，这几天会看下这个问题。

**Comment by llinfeng** [comment]
新的单双引号link: <https://www.rollingstone.com/music/music-features/being-james-brown-rolling-stones-2006-story-234764/?print=true>

**Comment by Kenshin** [comment]
嗨，这个问题解决了，你可以安装 [英文阅读版面辅助增强](https://github.com/Kenshin/simpread/issues/2840)。

![image](https://user-images.githubusercontent.com/81074/133365550-ba9d9bd6-3d27-4524-8af4-984e48e7387a.png)

> 同时也可以使用下面两个跟英文阅读有关系的内容：

- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H)

- [适配扇贝阅读的适配站点](https://github.com/Kenshin/simpread/discussions/2705)

***

我将关闭这个 issues，有任何问题随时在这里联络我。
