### ISSUE TITLE
使用知末网站的时候，会导致所有图片看不见。

### ISSUE THREAD

**Issue by zzhzzh7** [Kenshin/simpread#4470]
不确定这算不算适配问题，edge浏览器，简阅插件关闭后就可以正常看图，开启插件时图片是不可见的。

https://news.znztv.com/detail/14910479/0
随便一个链接

![image](https://user-images.githubusercontent.com/57969479/189042979-12afc3b5-f591-4f77-86e3-147827e3fbbb.png)
![image](https://user-images.githubusercontent.com/57969479/189043100-2091c98d-034a-4077-ab4d-7597556fcae7.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，是个 Bug，解决方案：

打开选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

![image](https://user-images.githubusercontent.com/81074/189045964-30949578-e688-4b08-9b94-5e854fcc39e6.png)
