### ISSUE TITLE
无法保存含有表格的微信文章到 notion

### ISSUE THREAD

**Issue by feimiao** [Kenshin/simpread#4473]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Chrome 105.0.5195.102**

- 简悦版本 **2.2.0**

- 发生问题的地址 <[含有表格的微信文章](https://mp.weixin.qq.com/s?__biz=MzU4MDc2NzUzNw==&mid=2247490387&idx=1&sn=ee31028bd86c4279391b18624aaa7ef8&chksm=fd50810dca27081b1ac1d25edc2c6a0cefd70732b524a72817115195420a44a6bdce6e45568a&mpshare=1&scene=1&srcid=0908gYhxvh15TN4WF8o8IOzg&sharer_sharetime=1662630564926&sharer_shareid=26561f792ec0744266fe9fe46fbfb4e0#rd)>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

无法保存含有表格的微信文章到 notion

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

![image](https://user-images.githubusercontent.com/18380365/189256187-ea525591-c4ec-418c-8960-808e87d2b67b.png)

**Comment by Kenshin** [comment]
嗨，这不是简悦的问题，你可以试试导出 Markdown，是没问题的，因为 Notion 对 md 支持度有限造成的。

如下图

![image](https://user-images.githubusercontent.com/81074/189260248-97148659-61cc-459f-a5f1-62b6f2ad0b47.png)

然后再把这个文件导入到 Notion 看看能否则解决？
