### ISSUE TITLE
阅读模式及聚焦模式无反应

### ISSUE THREAD

**Issue by L-TheShy** [Kenshin/simpread#4476]
**请说明发生问题的环境**

- 操作系统 ** Windows **

- 浏览器版本 **edge105.0.1343.33**

- 简悦版本 **2.1.0**

- 发生问题的地址 <https://csdnnews.blog.csdn.net/article/details/126774888?spm=1000.2115.3001.5927>

**知乎 csdn等所有网站的阅读模式点击后都变成无内容，但若是添加到稍后读，则里面的阅读模式可用**

![image](https://user-images.githubusercontent.com/75104030/189558411-54b72b5e-2bd5-457e-9ac9-fa2d9e042f72.png)

![image](https://user-images.githubusercontent.com/75104030/189558812-b78b837e-62bb-4da5-b0f1-efe11c38d65f.png)
![image](https://user-images.githubusercontent.com/75104030/189558845-bc1d668e-abc0-4cef-8836-94d4df7a83f0.png)

**Comment by Kenshin** [comment]
嗨，进入 https://sspai.com/post/71576 然后使用 F12 看看 DevTools 里面是否有报错，截图给我。

另外，我看你应该只有一个稍后读，也可以试试重置全部配置文件。

![image](https://user-images.githubusercontent.com/81074/189562562-c69f5278-f34d-4040-8c06-84e24cd6b0e8.png)

**Comment by L-TheShy** [comment]
![image](https://user-images.githubusercontent.com/75104030/189565822-af0686d7-79f1-4520-a59f-c04d142f27e2.png)

重置全部配置文件无变化。

**Comment by Kenshin** [comment]
之前看截图好像只有一个扩展，但看你的报错应该还有其他扩展。

隐私模式下，仅启用简悦后在测试刚才告诉你的链接。

**Comment by L-TheShy** [comment]
确实有其他扩展 在上方隐藏起来了
隐私模式下，仅启用简悦----这一步是在哪呢

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/189567405-a6049eed-0b50-43b6-b75a-e7fc92594845.png)

**Comment by L-TheShy** [comment]
无痕窗口好像禁用了所有插件，不知道是不是下面那个截图
![image](https://user-images.githubusercontent.com/75104030/189568097-2649bdc6-f00d-480c-88c1-7066ac14577a.png)

**Comment by Kenshin** [comment]
进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`

![image](https://user-images.githubusercontent.com/81074/189568922-6cc1e186-3beb-4c0f-9051-d011f3d71eed.png)

**Comment by L-TheShy** [comment]
感谢  无痕模式下尝试了一下  可以正常使用了  不过有没有办法找出和哪个插件不兼容吗
![image](https://user-images.githubusercontent.com/75104030/189569800-b369f1ff-3f5b-4e42-bb20-2b59f6cdf1db.png)

**Comment by Kenshin** [comment]
打开 `chrome://extensions/` 搜索 `gnjlo` 看看是哪个插件？把它禁用了。

**Comment by L-TheShy** [comment]
谢谢 是油候

**Comment by Kenshin** [comment]
哈哈，小事情，搞定就好。

看起来动手能力比较不错~ 👍

要不评个分？请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by L-TheShy** [comment]
必需好评

**Comment by Kenshin** [comment]
哈，谢谢。👍
