### ISSUE TITLE
浏览器插件配置信息无法同步

### ISSUE THREAD

**Issue by glqzk** [Kenshin/simpread#4477]
我通过简悦同步助手， 把A设备的配置信息同步到了B设备， 但是我发现 关于插件中 服务的部分（例如 flomo  notion API的配置等， 没有实现同步），请问这些配置需要每一个设备都重新设置一遍吗？

**Comment by Kenshin** [comment]
这些授权信息是隐私信息，默认不会保存到配置文件中，需要手动开启。

![image](https://user-images.githubusercontent.com/81074/189575632-c4f4e2d6-4136-4152-aad7-e24eafb1f20b.png)

**Comment by glqzk** [comment]
![image](https://user-images.githubusercontent.com/30902475/189576248-ab672964-1c36-4337-9d76-f86813680d31.png)
我在A设备开启了这一个功能，在手动的把文件上传云端覆盖报错，  
在B设备中， 我强制下载云端文件，覆盖本地配置， 但是在B设备中  【服务】这个模块，仍然和A设备不同

**Comment by Kenshin** [comment]
> 我在A设备开启了这一个功能

然后将配置文件保存到本地，然后在手动导入到 B 设备。（或者在 A 设备强制保存到坚果云，如果有错误，截图给我看下）

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了

5️⃣ 导入配置导致的各种插件问题均不再发生。（因底层架构改变造成这些奇怪错误均自动消失）
