### ISSUE TITLE
正常功能突然就变成实验性功能了

### ISSUE THREAD

**Issue by netveil** [Kenshin/simpread#4478]
![image](https://user-images.githubusercontent.com/36220045/189614957-aa282b27-4c3d-4317-862e-a5a7ef283d10.png)

**Comment by Kenshin** [comment]
是不是使用了同步助手？感觉有可能是你的同步助手绑定「掉了」。

使用 https://www.yuque.com/kenshin/simpread/xi8yds 重新绑定同步助手。

**Comment by Kenshin** [comment]
如果同步助手没问题的话，看看这个解决方案 https://www.yuque.com/kenshin/simpread/sw4m21

**Comment by Kenshin** [comment]
没问题就好。

你是刚升级或近期刚升级的新版本吗？

**Comment by Kenshin** [comment]
> 简悦能不能支持一下ANKI的闪卡导出 ，比如我在稍候读里面看到有关内容制作闪卡

可以，但我不知道如何制作闪卡，或者你也可以说说具体使用上的想法。

**Comment by Kenshin** [comment]
确实是个很好的想法，实现上应该也不会很麻烦。

但因为我从不很少涉足这些内容，所以缺少如何制作闪卡的一些基本概念。 😂

最好的方案是：找到一个可以制作闪卡的工具，这样我可以参考下。

**Comment by Kenshin** [comment]
补充下：

1. 我看到你的链接了，有没有第三方制作闪卡的工具？
2. 也说说你希望在简悦中实现的闪卡功能。

**Comment by Kenshin** [comment]
好，我先研究下。

**Comment by YUEGUNAG** [comment]
您好，我不太会用github，所以就在这里反馈了。

https://www.gushiwen.cn/mingju_602.aspx
https://www.cnblogs.com/pinard/p/9426283.html
上述两个网址都会显示“导出失败，此功能为实验性”，第二个在网页端批注时同步助手出错“同步助手运行时发生了错误，错误信息：ENOENT:no such file or directory,open”

我用的同步助手是1.1.2win64，绑定什么的都正常，因为其他网页都能正常用，比如“‘百度知道”。
                                                                                                                                                                谢谢！
