### ISSUE TITLE
关于增加常用动作快捷键的建议

### ISSUE THREAD

**Issue by glqzk** [Kenshin/simpread#4480]
开发者您好， 我在使用简悦种，有大量的操作是需要同步到notion或者同步到flomo的，但是每次我都需要点侧边栏，在点动作，在选到对应的按钮很麻烦， 不知道是否有快捷键，或者是否有开发计划？

**Comment by Kenshin** [comment]
嗨，你可以使用快捷键或者这个插件 https://simpread.ksria.cn/plugins/details/rsd4UIcDKY

也可以看看插件中心的各个插件 https://simpread.pro/plugins
