### ISSUE TITLE
简悦同步助手页面无法进入

### ISSUE THREAD

**Issue by jasonni** [Kenshin/simpread#4482]
http://ksria.com/simpread/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD
这连结点了一直显示 Loading...，导致无法下载助手😢

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/2990#discussioncomment-3612914 提到的解决方案。

你在国外吗？

**Comment by jasonni** [comment]
对，我在国外，用上述方案可以解决，谢谢
