### ISSUE TITLE
插件自动化辅助增强的无法成功保存配置内容

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#4483]
**请说明发生问题的环境**

- 操作系统：  **Windows 10 与 MacOS**

- 浏览器版本：
  - **Windows： 105.0.5195.102，x64**
  - MacOS：忘记了

- 简悦版本： **2.2.0**

**请描述你的问题**

问题：无法保存插件“自动化辅助增强”的配置。每次保存后重新打开都是空。

已尝试过的方案：

方案1. 使用 Windows 重置简悦扩展，安装插件管理器（开启自动同步），通过插件管理器安装：导入到 Obsidian、Markdown 模板增强、自动辅助增强；

方案2. 使用 Windows 重置简悦扩展，安装插件管理器（关闭自动同步），通过插件管理器安装：导入到 Obsidian、Markdown 模板增强、自动辅助增强；
 
方案3. 使用 MacOS 重置简悦扩展，安装插件管理器（开启自动同步），通过插件管理器安装：导入到 Obsidian、Markdown 模板增强、自动辅助增强；

方案4. 使用 MacOS 重置简悦扩展，安装插件管理器（关闭自动同步），通过插件管理器安装：导入到 Obsidian、Markdown 模板增强、自动辅助增强；

以上方案，无论是否使用“插件管理器”保存配置内容到本地，都无效。

**截图**

![image](https://user-images.githubusercontent.com/11768760/189822943-3f4dc174-a0fc-4196-9633-12ef132d4a6c.png)

**Comment by Kenshin** [comment]
嗨，使用插件管理器的全部配置保存功能 https://github.com/Kenshin/simpread/discussions/4221#discussioncomment-3164863

**Comment by Kenshin** [comment]
另外一个解决方案：先关闭自动同步，然后安装你需要的插件，然后再开启自动同步并覆盖到本地。

**Comment by HasonHuang** [comment]
这2个方法都试过，也是不行。
而且使用“插件管理器”将“全部配置保存到本地”后，自动同步功能会被开启。

**Comment by Kenshin** [comment]
不应该哦，我测试过各种极端情况。

> 使用“插件管理器”将“全部配置保存到本地”后，自动同步功能会被开启。

是的，这是插件管理器的特性，因为它就是为了解决无法安装插件准备的。

***

你试试关闭自动同步，然后正常的安装插件后再配置。

**Comment by HasonHuang** [comment]
1. 重置扩展，然后恢复高级账号。
![image](https://user-images.githubusercontent.com/11768760/189834124-a89aaee7-f9e4-42ae-96b0-30b62ca73dd1.png)

2. 安装插件管理器： 
![image](https://user-images.githubusercontent.com/11768760/189834332-50044cd6-116f-4e73-8e6a-4b98e929c8ae.png)
![image](https://user-images.githubusercontent.com/11768760/189834833-2fdc1506-0f41-42a2-9ec8-e1745259dc8b.png)

3. 使用管理器安装 3 个插件：
- 导入到 Obsidian
- 自动化辅助增强
- Markdown 辅助增强
![image](https://user-images.githubusercontent.com/11768760/189836343-837ba2c9-b43c-4dc7-9ff6-283f9fdac956.png)
![image](https://user-images.githubusercontent.com/11768760/189836774-8db7c838-8938-4b6e-b2cf-fde8cf659b14.png)

保存全部插件配置到本地：
![image](https://user-images.githubusercontent.com/11768760/189836931-d4a09644-2363-4a83-9f02-4d9144fb0c39.png)

4. 因为上一个步骤保存后导致自动开启同步，这里手动停止同步：
![image](https://user-images.githubusercontent.com/11768760/189837272-d8db2330-bc74-4c94-879b-0c2546b72281.png)
（刷新页面确认停止成功）

5. 打开新文章，分别配置：
配置 “导入到 Obsidian” 插件：
![image](https://user-images.githubusercontent.com/11768760/189837894-2ba8a73d-ee43-4576-bcb0-595c52d62636.png)

配置 "自动化辅助增强” 插件：
![image](https://user-images.githubusercontent.com/11768760/189838122-fb455f82-698d-4b57-b3a5-910ec03338e3.png)

6. 保存全部插件配置到本地：
![image](https://user-images.githubusercontent.com/11768760/189838260-8901cf11-0062-4109-9876-8bb339e99d9b.png)

7. 刷新页面检查：
![image](https://user-images.githubusercontent.com/11768760/189838468-93dfe734-dc75-4950-9ddf-460c5e47a965.png)

![image](https://user-images.githubusercontent.com/11768760/189838604-519918e7-7c75-4846-96b6-341549865143.png)

**Comment by Kenshin** [comment]
emmm 你可以这样做：

1. 选项页 → 插件管理 → 清除全部插件
2. 选项页 → 共通 → 重置
3. 重启浏览器
4. 不要开自动同步
5. 不使用插件管理器，分别安装这几个插件（每安装一个就配置一个，不要同时安装多个）
6. 重启浏览器

确保配置都成功了，再开启自动同步。

**Comment by HasonHuang** [comment]
> emmm 你可以这样做：
> 
> 1. 选项页 → 插件管理 → 清除全部插件
> 2. 选项页 → 共通 → 重置
> 3. 重启浏览器
> 4. 不要开自动同步
> 5. 不使用插件管理器，分别安装这几个插件（每安装一个就配置一个，不要同时安装多个）
> 6. 重启浏览器
> 
> 确保配置都成功了，再开启自动同步。

使用这个方式可以成功保存了。

> 实际上我的第一步是删除磁盘上的配置文件。

**Comment by Kenshin** [comment]
搞定就好~

> 实际上我的第一步是删除磁盘上的配置文件。

emmm 我会在文档中加强这方面的说明

***

现在你可以通过插件管理器 https://github.com/Kenshin/simpread/discussions/4221#discussioncomment-3164863 将配置保存到本地。

然后重启浏览器，这样就完成了自动同步的开启和插件配置的保存。

**Comment by HasonHuang** [comment]
@Kenshin 不开启自动同步时，插件配置正常。
重启浏览器，开启自动同步后（同时点击`覆盖本地配置文件`），“自动化辅助增强”插件**配置丢失**。

**Comment by Kenshin** [comment]
我是说「通过插件管理器 https://github.com/Kenshin/simpread/discussions/4221#discussioncomment-3164863 将配置保存到本地。

然后重启浏览器，这样就完成了自动同步的开启和插件配置的保存。」

而不是通过我选项页的开启自动同步。

**Comment by HasonHuang** [comment]
**仍然无效，我佛了。**

我的重试方案A：
1. 按前面说的重置 - 重启浏览器 - 激活；
2. 无同步 - 安装插件管理器 - 分别安装其他插件；（成功保存）
3. 重启浏览器 - 仍然成功保存；
4. 进入插件管理器 - 保存全部配置到本地；
5. `自动化辅助增强` **配置丢失**。

我的重试方案B：
1. 按前面说的重置 - 重启浏览器 - 激活；
2. 无同步 - 分别安装其他插件；（成功保存）
3. 安装插件管理器；
4. 重启浏览器 - 仍然成功保存；
5. 进入插件管理器 - 保存全部配置到本地；
6. `自动化辅助增强` **配置丢失**。

**Comment by Kenshin** [comment]
方案 B 是正确的

在你的操作步骤的基础上增加：（理论上不需要这么步骤，以防万一...

1. 关闭自动同步
2. 重启浏览器
3. 选项页 → 插件管理 → 从配置文件导入插件
4. 删除自动化辅助增强
5. 重启浏览器
6. 安装插件管理器
7. 通过插件管理器安装自动化辅助插件
8. 配置自动化辅助
9. 配置后不要重启浏览器，然后通过插件管理器保存全部插件配置到本地
10. 重启浏览器

然后用文本编辑器打开 `simpread_config.json` 搜索 `DH9l5jblPH` 如果插件配置被保存后，应该可以搜索到两个位置有这个 ID。

**Comment by HasonHuang** [comment]
如果是在我步骤后继续操作，此时`插件管理器`已安装。无法进行你的第六步：
> 6. 安装插件管理器

**Comment by Kenshin** [comment]
那就不需要步骤六后再试试。

**Comment by Kenshin** [comment]
太神奇了，你的唯一一个遇到此问题的用户。

你是什么系统？浏览器的版本是什么？

另外，关闭自动同步后就好使了？

PS：你遇到的问题其实是因为某个隐性 Bug 造成的，表现就是你在插件点保存，但没有保存到本地，数据仍在浏览器中。虽然是个别问题，但可能由于 Chrome 的版本升级造成了这个隐性 Bug 表现的次数较多。

后续我会修复这个问题。

***

你可以再试试：确保你的配置文件中有跟上图一样有自动化辅助增强的数据，然后重装简悦（不要重置），然后通过选项页 → 共通 → 从本地导入配置文件。

保存后会自动成为高级账户，然后刷新选项页。

然后你重启浏览器，再测试下自动化辅助增强，如果没问题的话，就开启自动同步功能，并将浏览器数据保存到本地。

最后再试试。

**Comment by HasonHuang** [comment]
> 你是什么系统？浏览器的版本是什么？

分别下面的系统操作，出现相同问题：
- Windows 10 x64, Chrome 105.0.5195.102
- MacOS 12.5, m1 pro, Chrome 97.0.4692.99

> 关闭自动同步后就好使了？

是的，禁用 `自动同步` 的情况下，插件配置能成功保存、显示。
但是，开启后自动同步后，json 文件里有配置内容，不能正常显示。


> 你可以再试试：确保你的配置文件中有跟上图一样有自动化辅助增强的数据，然后重装简悦（不要重置），然后通过选项页 → 共通 → 从本地导入配置文件。

在前面的第 15 步后继续操作，配置文件内容部分丢失（ 101 KB -> 4 KB）：

16. 卸载扩展 - 重启浏览器 - 安装扩展（配置文件保留了插件内容）

17. 从本地导入配置文件 - 刷新页面（此时，**默认打开了自动同步、配置文件内容被覆盖**）

   配置文件的 `plugin` 数组值正确，但插件对应的配置内容丢失，阅读模式里全部插件失效。

![image](https://user-images.githubusercontent.com/11768760/190068281-ac17cc87-ff2c-4e7b-a3f3-3b1c99a52874.png)

![image](https://user-images.githubusercontent.com/11768760/190068526-3cf6f9f9-0a42-490f-a7ac-8a2f9ab58c65.png)

**Comment by Kenshin** [comment]
> 步骤17

导入的配置文件应该是默认关闭自动同步的配置文件。

总之你的问题在于：没有把插件配置保存到本地，所以读取本地配置文件后因为没有插件配置所以出错。

先不要使用自动同步了，使用手动同步方案，如果不是太经常迁移数据的话。

**Comment by Kenshin** [comment]
你再按照我说的导入有插件配置的配置文件。确保导入的插件可以使用，再开自动同步并覆盖到本地。

**Comment by Kenshin** [comment]
> 问题1

轻量级方案不需要 https://www.yuque.com/kenshin/simpread/ifioux

高度集成化方案需要 https://www.yuque.com/kenshin/simpread/fr8zo5

> 问题2

配置知识库 https://www.yuque.com/kenshin/simpread/wkswh7 即可，不需要自动同步

> 问题3

暂时不支持 assets 的定制化

> 问题4

内部链接（也就是知识库方案）不支持 assets 方式，如果不考虑标注对应的话，则没问题。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0。

主要增加了针对插件设置不生效的解决方案。

安装此插件后无需人工干预，自动解决。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

***

建议，你可以重新试试，我关闭这个 Issues 了。

**Comment by Xm798** [comment]
> 自动保存插件配置
> 2.0.0 增加的新功能，专门解决当插件配置保存不生效的问题，无需人工干预。

今天复现了该问题，最新版插件管理器依然无法做到“自动解决”。

> 现在你可以通过插件管理器 https://github.com/Kenshin/simpread/discussions/4221#discussioncomment-3164863 将配置保存到本地。

无法生效。

**Comment by Kenshin** [comment]
@Xm798 

100% 可以的。

不过，可能有个更好的方案适合你。

***

针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Xm798** [comment]
> 100% 可以的。

实测确实不可以

https://user-images.githubusercontent.com/48074861/196334377-915b9105-a4e6-4135-8855-472d905be1ca.mp4

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
