### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by Astolfoo** [Kenshin/simpread#4487]
发生问题的地址: <http://kw.beijing.gov.cn/art/2022/5/19/art_736_629636.html>
辛苦作者大大❤️

加载后会有简略内容（如图），以及提示错误，但如何选取都提取不出来
![Screenshot - 2022-09-15 11 27 19](https://user-images.githubusercontent.com/35960773/190307157-5dc0429d-03dd-459c-9e20-452c04e4dde5.png)

**Comment by Kenshin** [comment]
嗨，可以使用下图的方式

![image](https://user-images.githubusercontent.com/81074/190311804-a55fe7be-0c21-4cab-93e7-450f01614432.png)

**Comment by Kenshin** [comment]
这是导出效果

![image](https://user-images.githubusercontent.com/81074/190311875-f2869ae2-24ce-4185-afce-cfff785304ae.png)

**Comment by Astolfoo** [comment]
收到，尝试了下没问题！！
点赞作者大大，高效又专业！！太赞啦~~感谢感谢

> 这是阅读模式效果
> 
> ![image](https://user-images.githubusercontent.com/81074/190311875-f2869ae2-24ce-4185-afce-cfff785304ae.png)

**Comment by Astolfoo** [comment]
找了一圈，我理解应该是chrome商店中（偷笑~）已五星好评！！感谢作者大大~~您辛苦啦。

**Comment by Kenshin** [comment]
> 找了一圈，我理解应该是chrome商店中（偷笑~）已五星好评！！感谢作者大大~~您辛苦啦。

哈哈，理解的... 完全没错误（是不是太隐晦了 😂
