### ISSUE TITLE
全文翻译可以按照 Google 翻译的方式显示

### ISSUE THREAD

**Issue by 47898077** [Kenshin/simpread#4488]
我有大量阅读维基百科的需求，并且为了保证后续不再重复阅读并提高效率，需要进行标注。
但是阅读英文和中文的速度差异巨大，因此我需要用chrome的内置翻译对单个词条的页面进行全文翻译后阅读，在使用简悦对其标注的过程中出现了一下几个问题。

- 在翻译后的页面上标注，刷新页面后无法在被标注的文本上保留，侧边栏的标注内容仍然是保留的。
- 为了避免不保留高亮的问题，在翻译后的页面阅读，在未翻译的页面标注，可以保留高亮，但是刷新页面后再次全文翻译，被标注的文本会重复出现两行。而且标注生成的markdown也是英文，这使得稍后读功能对我来说失去了意义。
- 稍后读只有英文界面，无法保留翻译后的界面，再次阅读需要开启第三方翻译软件，而且很难全文翻译，这更使得稍后读功能对我来说没有意义。

我希望作者能给予我以下的帮助
  1. 在翻译后的中文页面标注文本的高亮能在刷新后保留，这样同时也能解决标注生成的markdown是英文的问题。
  2. 稍后读可以同时保留翻译前后的中英文页面，或者提供类似google全文翻译的功能。
      顺带一提，简悦阅读模式内置全文翻译插件可以提供的那几家翻译API在学术方面的准确性有点糟糕。

再次感谢作者的工作与帮助，我非常认同你制作简悦的大部分理念。

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

> 问题1

简悦的标注是根据原文的结构进行锚定的，如果原文结构改变了就会出现标注不出现的问题。

解决此问题的方式是：使用 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7)，就能将当前中英文翻译的页面保存到本地（快照），然后在稍后读中就能正常的看到了，包括导出包括中英文的 Markdown。

当然稍后读的问题在于无法使用插件系统。

> 问题2

这个暂时应该不可以，这不是简悦的问题，而是 Chrome 本身就不支持这么做。

> 简悦阅读模式内置全文翻译插件可以提供的那几家翻译API在学术方面的准确性有点糟糕

DeepL 应该效果不错，或者你希望接入什么翻译？

***

关于英文阅读，简悦做了很多功能，你可以看 https://github.com/Kenshin/simpread/discussions?discussions_q=%E8%8B%B1%E8%AF%AD+label%3Alanguage 里面的提示。

包括：全文翻译、生词本、专门适配英文阅读页面。

***

维基百科的话，可以试试 https://github.com/Kenshin/simpread/discussions/3196

***

**Comment by 47898077** [comment]
再次尝试了一下内置全文插件提供的那几个api
一方面，免费的准确性不太好
另一方面，翻译后会改变文章排版，虽然一行英文一行中文在翻译不够通顺的时候很好用，而且插件本身也提供了提取其中中文部分的功能，但是翻译后会改变文章排版，甚至会改变文本内容。这方面确实没有chrome内置的翻译好用。

**Comment by Kenshin** [comment]
> 但是翻译后会改变文章排版，甚至会改变文本内容。这方面确实没有chrome内置的翻译好用。

太抽象了，建议可以截图告诉我 Google 哪里好用。

另外你说的内置 Google 翻译吧？它只能将全部英文翻译成中文，全文翻译插件也可以做到这点，而且还是双语对照。

**Comment by 47898077** [comment]
这是chrome内置翻译的结果
![image](https://user-images.githubusercontent.com/48744843/190352622-404f6daa-1618-40e3-a60a-e16130338d56.png)
这是简悦内置全文翻译插件的结果
![image](https://user-images.githubusercontent.com/48744843/190352935-b4bfd82c-4827-4041-b8fa-01900eb5b773.png)
这是插件上只显示中文的结果
![image](https://user-images.githubusercontent.com/48744843/190353358-5a202b53-beeb-4842-83d7-0dc8d063d635.png)

**Comment by Kenshin** [comment]
我好像知道你的诉求了

图二和图四是分别是全文翻译后的结果，我考虑下这个优化

***

图二如果使用知识库的方式后就能在稍后读中以中文形式保存了。但前提是：

1. 先翻译
2. 再标注

**Comment by 47898077** [comment]
好的，我会去试试知识库的方式，并且试试Modern for Wikipedia
再次感谢。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，解决了此类问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
