### ISSUE TITLE
因标题包含换行符导致无法下载

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4489]
您好，我不太会用github，所以就在这里反馈了。

https://www.gushiwen.cn/mingju_602.aspx
https://www.cnblogs.com/pinard/p/9426283.html
上述两个网址都会显示“导出失败，此功能为实验性”，第二个在网页端批注时同步助手出错“同步助手运行时发生了错误，错误信息：ENOENT:no such file or directory,open”

我用的同步助手是1.1.2win64，绑定什么的都正常，因为其他网页都能正常用，比如“‘百度知道”。
                                                                                                                                                                谢谢！

_Originally posted by @YUEGUNAG in https://github.com/Kenshin/simpread/issues/4478#issuecomment-1247706528_

**Comment by Kenshin** [comment]
@YUEGUNAG 

嗨，我新建了一个 Issues 讨论你的问题。

试试安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

看看能否解决？

**Comment by YUEGUNAG** [comment]
安装了这个插件，没解决

**Comment by YUEGUNAG** [comment]
加入稍后读：HTML
加入标注：markdown、HTML

**Comment by Kenshin** [comment]
> https://www.gushiwen.cn/mingju_602.aspx

这个页面是没问题的。

> https://www.cnblogs.com/pinard/p/9426283.html

确实无法导出，因为是标题包含了换行符和其他字符的缘故，你可以试试在稍后读中修改标题，然后再试试导出。

我先记录下，看后续是否可以优化这种情况。

**Comment by YUEGUNAG** [comment]
我试试，多谢！

**Comment by Kenshin** [comment]
小事情~

**Comment by justin201802** [comment]
那个插件并没有解决问题， 我也遇到类似的问题， 从同步日志来看， 就是文件名包含非法字符
访问的页面： 

```https://www.cnblogs.com/laozhang-is-phi/p/10483922.html```

```
[2022-09-16 16:32:20.417] ERROR (on AA): write: F:\工作机同步目录\SimpRead\output/tmp-95-从壹开始 [Ids4] 之一║ 授权服务器 IdentityServer4 开篇讲 & 计划书
    
IdentityServer4 for OpenID Connect 和 OAuth 2.0.html 
    error: {
      "errno": -4058,
      "code": "ENOENT",
      "syscall": "open",
      "path": "F:\\工作机同步目录\\SimpRead\\output\\tmp-95-从壹开始 [Ids4] 之一║ 授权服务器 IdentityServer4 开篇讲 & 计划书\n    \nIdentityServer4 for OpenID Connect 和 OAuth 2.0.html"
    }
[2022-09-16 16:35:27.335] INFO (on AA): write: F:\工作机同步目录\SimpRead\output/95-从壹开始 [Ids4] 之一║ 授权服务器 IdentityServer4 开篇讲 & 计划书
    
IdentityServer4 for OpenID Connect 和 OAuth 2.0.html
```

**Comment by Kenshin** [comment]
@justin201802 

你的这个页面比较特殊，它在标题中加入了换行符导致的.... 有个简单的解决方案：先加入稍后读，然后修改稍后读的标题，然后在导出，应该就没问题了。
