### ISSUE TITLE
手机同步能否改用其他icloud之类

### ISSUE THREAD

**Issue by ChenWeird** [Kenshin/simpread#449]
已经购买了JSBox，并安装了简悦及其阅读器，但同步配置需要Dropbox，国内无法使用。
能否改用其他网盘或者Synology NAS、FTP等自己的服务器？

**Comment by Kenshin** [comment]
并不一定需要 Dropbox 才能使用。只是同步过来的配置文件可以跟 Chrome 保持一致而已。

接下来会考虑，通过局域网直接同步的方案。 😀

**Comment by ChenWeird** [comment]
收到！感谢！
