### ISSUE TITLE
阅读模式下读取本地快照

### ISSUE THREAD

**Issue by YB-Kang** [Kenshin/simpread#4491]
请教老师一个问题，比如，下图是我打开的本地 HTML 页面，蓝色高亮那段话我用 live editor 的简易编辑稍微修改了，也高亮了。

![image](https://user-images.githubusercontent.com/55050981/190421625-96fe2e30-befb-41d2-bd37-91940bdf8b73.png)

但是当我下次打开时，不会从本地加载，显示的是原文，高亮也没了

![image](https://user-images.githubusercontent.com/55050981/190420498-55f79344-2e0e-4f78-927c-73e5f1222c7a.png)

这是哪里出问题了。ps. 我不用 live editor 修改原文也一样高亮都显示不出来

**Comment by Kenshin** [comment]
> 但是当我下次打开时，不会从本地加载，显示的是原文，高亮也没了

图二打开的是浏览器的阅读模式吧？如果是的话，浏览器的阅读模式下，只能加载原文（而非使用 Live Editor）优化后的界面。

如果你使用了知识库的话，优化后的页面可以通过稍后读看到。

PS：我会考虑把阅读模式的内容也显示为本地快照方案。

**Comment by YB-Kang** [comment]
没事，辛苦了！
---
是的，建议打开阅读模式优先读取本地快照，如果没有本地快照再直接读取原文。

用 live editor 修改后，简悦极速版的阅读模式是直接读取本地快照的。
但浏览器，不管是从原始网页，还是从扩展端的稍后读进入阅读模式，都是读取原文。
这样的话，一旦用 live editor 修改后，就只能用简悦极速版做高亮和文字的增删。
因为浏览器是读取原文的，标注或改动后通过自动化功能，会覆盖掉之前用 live editor 所做的更改。

我目前比较习惯用浏览器阅读，因为可以改 css 样式，阅读体验很好。
更重要的是我近视，但我不习惯戴眼镜，希望简悦极速版可以改字号。
另外，在夜间模式下，简悦极速版的高亮度太高，文字几乎看不清楚。

---

还有个问题，我上面说的主要是阅读模式下读取本地快照的问题，高亮没问题。
![image](https://user-images.githubusercontent.com/55050981/190845207-36cb6ef4-fc24-4945-9728-be938221a4b6.png)

可是我前面截图的页面来自飞书妙记，我标注后，第二次打开所有高亮都定位不出来，简悦极速版也一样。
![image](https://user-images.githubusercontent.com/55050981/190845181-a92e81f0-b8a0-4758-ac7f-e832b263d6b7.png)

Ps.我有安装「飞书妙记」适配站点。

**Comment by Kenshin** [comment]
> 用浏览器阅读，因为可以改 css 样式，阅读体验很好。

会把这个些功能带到其它方案的，包括字号等。不过，极速版跟本地文件的字号应该是一致的才对。

> 飞书妙记的问题

你是在阅读模式下标注，然后重新进入阅读模式后丢失标注吗？（我没太理解你的使用流程，最好详细说说。

PS：然后通过 https://github.com/kenshin/simpread/issues/new 来讨论这个功能~

**Comment by YB-Kang** [comment]
第一个问题我理解了，就是我得改电脑系统的字号。

第二个问题我已提交新的 issues。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
