### ISSUE TITLE
无法登录阅读列表

### ISSUE THREAD

**Issue by dav1ctor** [Kenshin/simpread#4492]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win11 21H2**

- 浏览器版本 **Chrome 105.0.5195.102**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chttps://simpread.pro/@id/reading/?token=<token>>

**请描述你的问题**

> 我不知道授权码是指哪个码，尝试了一系列可能的码之后都弹出图中红框所示内容。改用Email登录并输入正确的验证码后，又自动跳转回该登录页面，同样登录失败。
> 坚果云授权登录已开启，开放平台可以正常登录，相关功能也已按照要求开启，API测试显示通过。收藏助手可以正常使用。

**截图**

> ![image](https://user-images.githubusercontent.com/20353383/190443645-07dcb94c-7cdf-4c3d-a116-77454d3b40b4.png)
> ![image](https://user-images.githubusercontent.com/20353383/190445799-eed7594e-780c-4818-9e48-884a0b6eb50a.png)

**Comment by Kenshin** [comment]
嗨

1. 在隐私模式下登录，可能由于你反复登录造成的问题。
2. 如果你能登录进去后，设置你的用户名和密码，然后在方案1的前提下， 用户名 / 密码的方式登录

![image](https://user-images.githubusercontent.com/81074/190841870-723f2b96-f78d-4465-8ad9-c5bd4c7ae464.png)

**Comment by dav1ctor** [comment]
试了下还是登录不了
