### ISSUE TITLE
官网 `http://ksria.com/` 各种`521`错误，无法正常打开

### ISSUE THREAD

**Issue by cowfox** [Kenshin/simpread#4496]
例如这个 URL `https://simpread.pro/#synchelper` 就会出现这类的错误：
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/4998114/190697268-355fa37d-e591-4f25-8109-aeb7761cea6c.png">

**Comment by Kenshin** [comment]
嗨。

1. 没有这个问题。
2. 简悦的官网不是 http://ksria.com/ 而是 https://simpread.pro （国内、阿里云）或者 http://ksria.com/simpread/ （Github page ）而这两个网址都可以正常打开。
3. `https://simpread.pro/#synchelper` 这个地址也可以正常打开，但你是从哪里获得到的？

给你看下截图 `http://ksria.com/simpread` 的联通效果。

![image](https://user-images.githubusercontent.com/81074/190841708-cbdf33c1-431b-49d6-9048-ec487acae1b4.png)

所以

1. 你是什么网络环境？
2. 在隐私模式下，再看看。

**Comment by cowfox** [comment]
感谢回复~ 
人在美国。
刚才试了一下速度测试：
```
http://ksria.com/simpread/
```
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/4998114/190842070-8002ac60-45b3-4956-bdbf-ad06df2d493c.png">

```
simpread.pro
```
 这个是好的
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/4998114/190842110-4e6d4c17-47d5-49f1-947f-f659aec3030c.png">

**Comment by Kenshin** [comment]
emmmmm

那访问 http://ksria.com/simpread/ 不应该有问题才对，它 Host 在 Github Page 上。

另外不要用你截图的那个，不太好使，我随机找了几个测试工具 e.g. https://www.36ce.net/

我找几个国外的朋友再试试。

另外，肯定是没问题的，否则不可能只一例报告。

***

确实有个别用户存在访问简悦（国内 IP）困难的问题（但不是你提到的问题），因为你在国外，所以顺便提示下。

解决方案 https://github.com/Kenshin/simpread/discussions/2990#discussioncomment-3612914

**Comment by cowfox** [comment]
感谢回复~ 
我感觉应该是 CDN 的访问问题，都是`521`这个错误。
```
net::ERR_ABORTED 521
```
不过，感谢您提到了网站是 Github 的 page，所以我在代码里找到网盘的下载链接了~ 😁

**Comment by Kenshin** [comment]
哈哈，在 http://ksria.com/simpread/docs2 里面就有下载链接。

**Comment by Kenshin** [comment]
嗨，我在考虑切换某些 CDN 环境，方便的话，帮忙测试下。

请问你访问 https://cdn.staticfile.org/font-awesome/6.2.0/css/fontawesome.min.css 是否正常？同时请告知速度如何？

**Comment by logic-leoshi** [comment]
不开 VPN 的话访问也没有问题~ 速度挺快的 ~ 
不过毕竟文件也不大，也就 20K~
