### ISSUE TITLE
设置选项的显示问题

### ISSUE THREAD

**Issue by lonelykid** [Kenshin/simpread#45]
![image](https://user-images.githubusercontent.com/2936633/28190595-b7cd63cc-67f9-11e7-8ad4-16dc2a1029cf.png)
这个是我使用不当么？上面有一个选项看不到了。另外操作的时候也不大方便，必须小心翼翼向上／向左移动，一不小心光标离开一点，就得重新开始....

**Comment by Kenshin** [comment]
未显示的 icon 应该是被遮挡住了，的确有人反应控制栏太活了…
上述两个问题可以解决。不过，只能下个版本一起发布了。

**Comment by Kenshin** [comment]
@lonelykid 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

优化了控制栏的数量，如果没有问题的话，请关闭此 issues
