### ISSUE TITLE
阅读列表安装安卓手机问题反应

### ISSUE THREAD

**Issue by starrycrown** [Kenshin/simpread#4501]
我用的安卓的dege进入阅读列表，自动弹出应用到桌面，点击后显示正在安装，然后就没了，没有列表已添加到主屏幕，然后主屏幕也确实吗，没有

**Comment by Kenshin** [comment]
嗨，这里有关于 Android 版的安装方法 https://github.com/Kenshin/simpread/discussions/2954#discussioncomment-1517975

有任何问题可以继续通过此 Issues 讨论~
