### ISSUE TITLE
阅读模式正常，加入稍后读后“解析正文失败”

### ISSUE THREAD

**Issue by Scaresec-Lancer** [Kenshin/simpread#4503]
系统环境：
 - Windows 10 
 - Chrome 105
 - 简悦 2.2.0.520 无同步助手

发生的问题页面：https://segmentfault.com/a/1190000042280443

问题描述：阅读模式开启正常，加入稍后读，在稍后读打开阅读正文显示 “解析正文失败”，反复添加进稍后读还是相同情况。

**截图**

![image](https://user-images.githubusercontent.com/89342497/190935928-613f122f-342e-4158-ac2c-60e55ed37dd7.png)

**Comment by Kenshin** [comment]
嗨，某些页面因为动态加载导致，这是正常的，但你可以使用 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的方式彻底解决这个问题。
