### ISSUE TITLE
【插件配合使用问题】

### ISSUE THREAD

**Issue by Rvishny** [Kenshin/simpread#4505]
使用全文翻译插件时，由于浮动图标不能移动，导致其被自动生成的目录覆盖，无法点击。
![Dingtalk_20220919114127](https://user-images.githubusercontent.com/57344700/190946286-02d8f505-fa38-4132-b93c-9978b140a61c.jpg)

**Comment by Kenshin** [comment]
嗨，你是什么时候下载的全文翻译插件，我优化过这个地方。

不过，最好还是提供出问题的 URL 给我看下。

**Comment by Rvishny** [comment]
更新插件后已能正常使用，谢谢。



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2022年09月19日 11:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Kenshin/simpread] 【插件配合使用问题】 (Issue #4505) |

嗨，你是什么时候下载的全文翻译插件，我优化过这个地方。

不过，最好还是提供出问题的 URL 给我看下。

**Comment by Kenshin** [comment]
okay 搞定就好，我关闭这个 issues 了~

**Comment by Kenshin** [comment]
请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了

5️⃣ 导入配置导致的各种插件问题均不再发生。（因底层架构改变造成这些奇怪错误均自动消失）
