### ISSUE TITLE
代码显示插件有问题，有一部分CSDN代码内容会被忽略掉而不显示

### ISSUE THREAD

**Issue by HaoyuTec** [Kenshin/simpread#4507]
代码显示插件有问题，有一部分CSDN代码内容会被忽略掉而不显示

**Comment by Kenshin** [comment]
嗨，简悦对代码段的识别确实有些问题，因为代码段的高亮方案太多了，很难有统一方案。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
