### ISSUE TITLE
请问仿Safari的插件怎么调背景颜色？

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#4508]
我想把图1默认调成图2，还有阅读背景好像自定义里面没有调色选项，一共需要调两个颜色
![image](https://user-images.githubusercontent.com/15308878/191442203-10eb36fe-9af7-416e-93c3-839a25cf4317.png)

![image](https://user-images.githubusercontent.com/15308878/191442463-c69fd613-069b-434a-9681-8543ac94344c.png)

**Comment by Kenshin** [comment]
嗨，抱歉，之前漏掉了这个 Issues

你可以将

```
.simpread-read-root {
    background-color: #F0F1F2!important;
}
```

加入到下图所示位置

<img width="461" alt="image" src="https://user-images.githubusercontent.com/81074/191886649-4b19b2cc-2775-4c94-8e6c-f80195819cf0.png">
