### ISSUE TITLE
请问edge浏览器可以发送到onenote了么？我是surface，在这个上面用chrome很耗电，只敢用edge

### ISSUE THREAD

**Issue by ddkk3000** [Kenshin/simpread#451]
我在台式机上，下面这个功能几乎是没有问题的：

![mark](http://cache.lixiaozhe.com/image/20190208/YaG6rnigerV4.png?imageslim)

不过我在surface上没有chrome浏览器（chrome太耗电了，移动设备无法承受，而且它对于触屏支持不佳，更不用说手写笔了），按照官方的说明似乎我只能用油猴脚本中的简悦的简装版，似乎没有这个功能。我想问的是：有没有更为完整的使用简悦的方法呢？因为，有人说edge的插件与chrome实际上是通用的。

我有另外一个问题，这个问题应该只是我玩设置上的（但我不知道哪里有问题），它的内容是：chrome插件里的如上图功能经常失效，比如：

![mark](http://cache.lixiaozhe.com/image/20190208/GkeFco9Buzew.png?imageslim)

或者说我几乎就没成功过几次，为什么呀。我确定我绑定的是没问题的。

**Comment by Kenshin** [comment]
谢谢反馈，春节快乐。

目前在 EDGE 确实只有油猴脚本，并不支持导出功能。

EDGE 支持 Chrome 扩展应该是「未来」的才会支持。

第二幅截图的问题应该是你的简悦版本较低造成的，请问是什么版本？

**Comment by ddkk3000** [comment]
我chrome的插件是自动更新的，怎么还会有版本问题？怎么手动解决呢？

版本号如图：

![mark](http://cache.lixiaozhe.com/image/20190208/5Q9KaGhLOQvX.png?imageslim)

________________________________

发件人： Kenshin Wang<mailto:notifications@github.com>
发送时间： 2019-02-08 19:54
收件人： Kenshin/simpread<mailto:simpread@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [Kenshin/simpread] 请问edge浏览器可以发送到onenote了么？我是surface，在这个上面用chrome很耗电，只敢用edge (#451)

谢谢反馈，春节快乐。

目前在 EDGE 确实只有油猴脚本，并不支持导出功能。

EDGE 支持 Chrome 扩展应该是「未来」的才会支持。

第二幅截图的问题应该是你的简悦版本较低造成的，请问是什么版本？

―

**Comment by Kenshin** [comment]
版本没问题…

第二个截图是在做什么操作发生的？

**Comment by ddkk3000** [comment]
操作过程：![mark](http://cache.lixiaozhe.com/image/20190208/2gapNv6nF29C.gif)

**Comment by ddkk3000** [comment]
http://cache.lixiaozhe.com/image/20190208/2gapNv6nF29C.gif

**Comment by Kenshin** [comment]
我以为是 印象笔记 的导出有问题，没想到是 Onenote…

我目前在休假，无法排除原因，你确定获取到授权后，试试访问 https://sspai.com/post/39491

看看能否保存？

**Comment by ddkk3000** [comment]
谢谢。我不用印象app。无法保存你回复中的链接内容到onenote。我确定授权了(截图见：http://cache.lixiaozhe.com/image/20190209/5HWM5h4nLk1Q.png)，因为我偶然也能成功导出到onenote。

________________________________

发件人： Kenshin Wang<mailto:notifications@github.com>
发送时间： 2019-02-09 20:40
收件人： Kenshin/simpread<mailto:simpread@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [Kenshin/simpread] 请问edge浏览器可以发送到onenote了么？我是surface，在这个上面用chrome很耗电，只敢用edge (#451)

我以为是 印象笔记 的导出有问题，没想到是 Onenote…

我目前在休假，无法排除原因，你确定获取到授权后，试试访问 https://sspai.com/post/39491

看看能否保存？

**Comment by Kenshin** [comment]
回复这么快？
这样的话，需要等到我回去才能看看，我找时间问问其他用户。

**Comment by ddkk3000** [comment]
刚好看到邮件了。好的，感谢。

________________________________

发件人： Kenshin Wang<mailto:notifications@github.com>
发送时间： 2019-02-09 20:49
收件人： Kenshin/simpread<mailto:simpread@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [Kenshin/simpread] 请问edge浏览器可以发送到onenote了么？我是surface，在这个上面用chrome很耗电，只敢用edge (#451)

回复这么快？
这样的话，需要等到我回去才能看看，我找时间问问其他用户。

**Comment by Kenshin** [comment]
现在应该没有这个问题了，我将关闭这个 issue ~ 有问题的话，请重开它。
