### ISSUE TITLE
通过简悦导出B站笔记到Obsidian时报错

### ISSUE THREAD

**Issue by EternalHXP** [Kenshin/simpread#4510]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
调试好 简悦 导入obsidian的插件
可以保存 少数派 (含图)的文章 到obsidian (图片为assets模式).
但在b站笔记时就不行.

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
![image](https://user-images.githubusercontent.com/28817885/191462029-e30d1141-f09e-4832-ae1a-c0034910135e.png)
![image](https://user-images.githubusercontent.com/28817885/191462173-9cb68626-e3c4-44c7-832d-6a5c180c9b7b.png)

**截图**
![image](https://user-images.githubusercontent.com/28817885/191461673-ed2cf12c-11d5-4fa7-9a7a-70bf11239967.png)

> 一图胜千言，所以方便的话，可以试着贴图。

报错信息
[2022-09-21 16:56:11.826] INFO (on HXP-Y9000): write: C:\xxx\01-Inbox/「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ 
            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？/「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ 
            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？.md
[2022-09-21 16:56:11.827] ERROR (on HXP-Y9000): write: C:\xxx\01-Inbox/「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ 
            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？/「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ 
            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？.md 
    error: {
      "errno": -4058,
      "code": "ENOENT",
      "syscall": "open",
      "path": "C:\\xxx\\「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ \n            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？\\「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？ \n            「珂学原理」No-106「线性代数，为何如此难学」矩阵究竟是什么？.md"
    }

**Comment by Kenshin** [comment]
嗨，我知道你的问题了。

问题的原因是：标题包含了非法字符（仅限 Windows 系统）。

你需要在导入到 Obsidian 之前，使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改标题，最好把全部标题都删了，然后重新输入标题。

另外，确保 Obsidian 插件为 1.3.3 你可以直接 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 安装，如果提示更新则选择更新即可。

**Comment by EternalHXP** [comment]
试过 Live Editor了. 标题改后, 保存没问题, 但是图还是挂了....
![image](https://user-images.githubusercontent.com/28817885/191511690-cea55acd-e49d-476d-a6ee-b9b33909138b.png)
![image](https://user-images.githubusercontent.com/28817885/191512101-5ab3b726-9bee-464a-836f-eadcc41d3239.png)

**Comment by EternalHXP** [comment]
另外 , 除了第一个笔记外, 
切换到其他笔记, 标题都会混入 第一个笔记的标题
且同时 图片存入obsidian时都会挂掉
![image](https://user-images.githubusercontent.com/28817885/191514309-c5322d3f-9d79-4c87-9d0b-7fb0f235da19.png)
![image](https://user-images.githubusercontent.com/28817885/191514414-54a082f4-72be-4c26-b7e1-73f68d6b8301.png)

**Comment by EternalHXP** [comment]
感觉不只是 标题的问题. 像是B站笔记的图片下载不太好用.

**Comment by Kenshin** [comment]
emmmm 我明天看下。

你看看 https://github.com/Kenshin/simpread/discussions/1583 里面的说明。

**Comment by EternalHXP** [comment]
[> ](https://github.com/Kenshin/simpread/issues/4510#issuecomment-1253795582)



> emmmm 我明天看下。
> 
> 你看看 #1583 里面的说明。

可以先不用帮忙看啦. 今天我先 按 1583 再检查一下 B站笔记相关流程再到这里回复.

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696)。

<img width="527" alt="image" src="https://user-images.githubusercontent.com/81074/203234319-2cd4d083-f521-498b-a9c9-4d5f6d85628e.png">

打开 https://simpread.ksria.cn/plugins/details/BvjrJA6eh5 可自动安装。如果使用同步助手的话，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

### 除此之外比较重要的更新

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。

**Comment by Kenshin** [comment]
当选择了 [Base64 方案](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920120) 后，就可以正常导入到 Obsidian 里面了。

![image](https://user-images.githubusercontent.com/81074/203234418-3ca3833f-5c4f-4a3b-827f-492034668b8e.png)

功能已经内置到以下两个插件中

- [导出 md + assets 格式](https://github.com/Kenshin/simpread/discussions/4041)

- [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

这是导入后的效果

<img width="847" alt="image" src="https://user-images.githubusercontent.com/81074/203234514-e0f46a59-ba8d-4083-8589-5e5b31727462.png">

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
