### ISSUE TITLE
网页内图片以离线方式导出，同步助手出现错误：No such file or directory

### ISSUE THREAD

**Issue by nbduzh** [Kenshin/simpread#4511]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统：Windows 10 专业工作站版 21H2

- 浏览器版本： Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)

- 简悦版本： 2.2.0

- 发生问题的地址： [内网穿透，Frp、Zerotier | 易学教程 (e-learn.cn)](https://www.e-learn.cn/topic/3761158)

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

进入阅读模式解析正常，`复制Markdown到剪切板`也能正常导出
![image](https://user-images.githubusercontent.com/24581860/191690277-6373b9ca-eff7-474a-b8df-b46476824aa9.png)

Markdown`导入md + assets到obsidian`提示“保存成功”，如图：
![image](https://user-images.githubusercontent.com/24581860/191689955-a60bb312-d8b1-464b-b117-f1d4291a6ed0.png)
![image](https://user-images.githubusercontent.com/24581860/191688303-faafafe1-c494-410c-b096-e5e39b8a9fa0.png)

但是其实并未导入到obsidian，出现如下错误（图片导出全部出现错误，文中有几张图片就出现几次错误）：
![image](https://user-images.githubusercontent.com/24581860/191688595-8659d0c7-dcdb-4ddd-b8c4-498e88b72a17.png)
![image](https://user-images.githubusercontent.com/24581860/191688931-14bdad11-eeb4-4faf-9014-268a4f3586f8.png)
![image](https://user-images.githubusercontent.com/24581860/191689082-a0c2f0df-16f8-4615-85c6-d0ded47f5165.png)

此网页内的图片以*附件的形式*会导出会出现错误，若是以*url的形式*导出则正常。

`原因应该是此网页的标题中包含字符“ | ”，而文件夹名称不能包含此字符，文件夹创建失败，导致出现错误。`

==想请教这种标题包含特殊字符的情况要如何解决？==

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，解决方案

1. 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件
2. 如果无法安装插件的话，使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装插件。

**Comment by nbduzh** [comment]
谢谢您的帮助！


    但是安装了此插件后，虽然把符号改成了“-”，但是导出时还是出现错误提示：
原因是预导出新建的文件夹名称中并没有“-”符号，导致路径不匹配。


未安装此插件前此处是“_”


最后通过Live Editor将此网页标题的”-“符号删除后才导入成功。


希望能更新https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，改进此问题，感谢！




在 2022-09-22 16:17:46，"Kenshin Wang" ***@***.***> 写道：

嗨，解决方案

安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件
如果无法安装插件的话，使用 插件管理器 安装插件。

**Comment by Kenshin** [comment]
emmm

> 但是安装了此插件后，虽然把符号改成了“-”，但是导出时还是出现错误提示：
原因是预导出新建的文件夹名称中并没有“-”符号，导致路径不匹配。

并不应该会出现这样的问题，导出时的文件夹名称为标题，也就是标题是什么样的，文件夹的名称即是什么样。

**Comment by nbduzh** [comment]
不好意思，搞错了。


预导出的新文件夹并没有创建成功，可能标题还是有特殊字符。


提供网站网址，可以实际试一下：


内网穿透，Frp、Zerotier | 易学教程 (e-learn.cn)


`https://www.e-learn.cn/topic/3761158`







在 2022-09-23 11:17:12，"Kenshin Wang" ***@***.***> 写道：

emmm

但是安装了此插件后，虽然把符号改成了“-”，但是导出时还是出现错误提示：
原因是预导出新建的文件夹名称中并没有“-”符号，导致路径不匹配。

并不应该会出现这样的问题，导出时的文件夹名称为标题，也就是标题是什么样的，文件夹的名称即是什么样。

**Comment by Kenshin** [comment]
嗨，简悦发布了一个新功能，可能适合你：[配置库](https://github.com/Kenshin/simpread/discussions/4531)，其中包含了已经配置好的，具有 [离线 HTML 的配置包](https://github.com/Kenshin/simpread/discussions/4531#discussioncomment-3844897)，你可以直接使用，看看是否还有这个问题吗？

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
