### ISSUE TITLE
公众号公式解析错误（公式错误）

### ISSUE THREAD

**Issue by Aaloone** [Kenshin/simpread#4514]
https://mp.weixin.qq.com/s/oHSavY5rkDYCEP5b83aHQg
公式解析有错误，公式无法导出到Notion

**Comment by Kenshin** [comment]
嗨，谢谢反馈，因为公众号的公式比较特殊，暂时不支持造成的。

我先记录下这个问题~

**Comment by QuinnYates** [comment]
不只是公众号的公式解析有错误，这个网站上的公式解析也有错误： https://www.lianxh.cn/news/df7f59b5f18a8.html

**Comment by Kenshin** [comment]
@QuinnYates 

是这样的，简单的解释下。

简悦只适配了使用最广泛的一种公式解析方案：MathJax，而你给出的 URL 和公众号均没有使用这种方式，而是使用了一种我从未见过的 `svg` 方案，所以在进入阅读模式后会被识别成图形而导致的问题。

**Comment by TheTruthYouKnow** [comment]
> @QuinnYates
> 
> 是这样的，简单的解释下。
> 
> 简悦只适配了使用最广泛的一种公式解析方案：MathJax，而你给出的 URL 和公众号均没有使用这种方式，而是使用了一种我从未见过的 `svg` 方案，所以在进入阅读模式后会被识别成图形而导致的问题。

这个方案在简书中也有遇见过，阅读模式会识别为png图片导致无法正常查看。
示例链接：https://www.jianshu.com/p/e833969b7702

**Comment by Kenshin** [comment]
@TheTruthYouKnow 

并没有遇到你说的问题。

<img width="1272" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9dbb629a-cb62-4c7b-a7a4-9f83bcef0ba0">

导入到 Notion 的效果

<img width="891" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/77fc62fa-9eea-4fb6-a49a-e5e450e2c6fa">

**Comment by TheTruthYouKnow** [comment]
@Kenshin 导出md+assets。使用的是模板配置。

**Comment by Kenshin** [comment]
@TheTruthYouKnow 

你的问题跟这个 Issues 无关，我测试了下，确实如此。

因为有些网站对图片有严苛的防外链方案，虽然从技术上可以解决，但简悦理论上要尊重这些网站的规则。

常规方案：离线 HTML、PDF、md + assets 方案都不能满足的话，是不会专门适配这种规则的。

PS：以后有问题建议新建 Issues 除非 100%  是一致性问题，否则你翻出来一个非常久远的 Issues 会打扰到其他用户 😄

**Comment by TheTruthYouKnow** [comment]
@Kenshin 好的，非常感谢提醒，我目前还在学习使用github的issue的功能，还不够熟悉issues的规则，按照我个人笔记的规则，相似的问题都是统一放一个文档进行保存的，而github貌似不是这样，是单独列举，以后我会注意点的XD

**Comment by Kenshin** [comment]
@TheTruthYouKnow 

哈，小事情。你把 Issues 当作一个 QA 平台就好。只是因为有 Email 提醒功能，所以当你发 comment 在这个 Issues 中的用户都可以接收到 Email。

虽然有办法取消，但一旦有相关的人就可能收不到 Email 😂

> 按照我个人笔记的规则，相似的问题都是统一放一个文档进行保存的

这当然没错，很经典的数字花园方案。😄

单独一个 Issues 的话，如果有有相似问题我会把对应的链接贴上就会有下图的效果

<img width="466" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c328244c-4da0-47c8-a194-ba17da821e20">

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了此问题。

<img width="689" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/eda922c9-d423-4495-9a5f-ff5088f86343">


***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
