### ISSUE TITLE
请问维基百科的公式都是渲染为图片吗？能像现在知乎那样渲染吗？

### ISSUE THREAD

**Issue by 47898077** [Kenshin/simpread#4515]
维基百科进入阅读模式后
![image](https://user-images.githubusercontent.com/48744843/191825962-786b1f5d-483c-41c6-b372-88b7b1d862cb.png)
知乎进入阅读模式后
![image](https://user-images.githubusercontent.com/48744843/191826392-29c89219-3b35-478a-848d-705127015a1a.png)

**Comment by Kenshin** [comment]
嗨，维基百科的公式应该只是图片，而知乎则是公式，所以它们有本质区别。

建议给个 URL 确认下。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
