### ISSUE TITLE
在vercel托管的网页能否支持markdown

### ISSUE THREAD

**Issue by sche11** [Kenshin/simpread#4516]
在vercel托管的网页能否支持markdown?这样可以使用自动化,加入稍后读保存到GitHub,同步到vercel的托管网站上,这是非常便捷的.但我实际试图在vercel上打开我同步的md文件时,A server error has occurred. FUNCTION_INVOCATION_FAILED. 我注意到你的教程上止给出html的示例,我想这也许是不支持的格式的问题,希望你能帮到我.
我在 https://github.com/Kenshin/simpread/discussions/3960#discussioncomment-3711660 提到相同的问题

**Comment by Kenshin** [comment]
嗨，我已经在 https://github.com/Kenshin/simpread/discussions/3960#discussioncomment-3713870 直接回复你了。
