### ISSUE TITLE
[Feature] assets + md 自定义文件夹，每篇文章的图片一个单独的文件夹

### ISSUE THREAD

**Issue by llity** [Kenshin/simpread#4517]
类似typora的自定义图片保存位置。
![IMAGE 2022-09-23 15:16:41](https://user-images.githubusercontent.com/11771112/191909545-162a0b41-9754-49a1-903d-5c3b634b11c4.jpg)

**Comment by Kenshin** [comment]
okay 

我研究下 Typora 的方案。

**Comment by llity** [comment]
好呢 :)
<img width="720" alt="image" src="https://user-images.githubusercontent.com/11771112/191914079-2d40ede4-790a-462f-98a4-326a0af07e19.png">

**Comment by Kenshin** [comment]
截图的选项不是类似下面的结构吗？

<img width="294" alt="image" src="https://user-images.githubusercontent.com/81074/191921811-d4c1024e-e7fd-4fee-b3fc-cf2a5958d283.png">

**Comment by llity** [comment]
是自定义的一个目录。图片和md是分开的。
<img width="382" alt="image" src="https://user-images.githubusercontent.com/11771112/191924066-b4c9fc6e-1834-44ae-8f08-6c2dc135f7bf.png">

**Comment by Kenshin** [comment]
好，我研究下~

**Comment by blog2i2j** [comment]
这个好处就是文件直接放在主目录下, 然后专门一个文件夹放图片(obsidian就可以设定附件目录了). 然后左侧目录看起来干净

**Comment by Kenshin** [comment]
> 这个好处就是文件直接放在主目录下, 然后专门一个文件夹放图片(obsidian就可以设定附件目录了). 然后左侧目录看起来干净

@blog2i2j 

也就说，把全部 md 的图片都放在一个文件夹中？

**Comment by llity** [comment]
> > 这个好处就是文件直接放在主目录下, 然后专门一个文件夹放图片(obsidian就可以设定附件目录了). 然后左侧目录看起来干净
> 
> @blog2i2j
> 
> 也就说，把全部 md 的图片都放在一个文件夹中？

是的，如typroa

**Comment by Kenshin** [comment]
@llity 

那删除 md 呢？这个 md 对应的图片不太方便一并删除吧？

**Comment by llity** [comment]
开发一个插件，应该能把附件一起删除

**Comment by Kenshin** [comment]
> 开发一个插件，应该能把附件一起删除

@llity 

太「麻烦」了 😂 已经超出了同步助手的工作范畴了，虽然我理解这种方案，但弊端还是非常明显的。

**Comment by llity** [comment]
那就手动删除吧，几乎不会删笔记。

**Comment by Kenshin** [comment]
@llity 

会考虑的。

**Comment by sche11** [comment]
> @llity
> 
> 那删除 md 呢？这个 md 对应的图片不太方便一并删除吧？

这就如同zotero的插件zotefile(用于规范命名),删除文件夹后,重名的文件无法一起删除,不过可以写一个脚本,定时索引文件夹的文件,当某个文件不存在时(比对),删除对应的重命名文件.

**Comment by Kenshin** [comment]
@sche11 

哈，思路不错~

**Comment by sche11** [comment]
> @llity
> 
> 那删除 md 呢？这个 md 对应的图片不太方便一并删除吧？

这个obsidian插件可以解决,可以删除未被使用的图片.[oz-clear-unused-images-obsidian](https://github.com/ozntel/oz-clear-unused-images-obsidian)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨，各位。

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696)。

![](https://user-images.githubusercontent.com/81074/202892148-b6ede303-f882-4362-9399-e047523d265a.png)

打开 https://simpread.ksria.cn/plugins/details/BvjrJA6eh5 可自动安装。如果使用同步助手的话，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

### 除此之外比较重要的更新

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。

**Comment by llity** [comment]
这个不开启同步助手也行吧？我按照教程配置了但是保存还是失败了

**Comment by llity** [comment]
@Kenshin 谢谢，能像notion一样不需要助手保存图片就好了。

**Comment by llity** [comment]
![image](https://user-images.githubusercontent.com/11771112/220508629-efad74f7-e5e7-497a-a142-3ac7f23f78ee.png)
还是保存失败。

**Comment by Kenshin** [comment]
emmm 看起来没问题，但为了方便排查，建议还是逐一试试。

1. 导入到 Obsidian 是否好用（不启用 assets + md 的前提下）

2. 把 assets + md 设置到一个正常的目录下（非 iCloud）并暂时不要使用 `custom` 方案，使用默认的方案。

3. 然后在设置 custom 为一个正常目录。

如果以上都没问题的话，再按照你预期的设置。

**Comment by llity** [comment]
1. 不启用 assets + md 的前提下正常导入
2. 非iCloud目录也不行，默认方案。
3. 2步已经不行了，3也不成功
<img width="1821" alt="image" src="https://user-images.githubusercontent.com/11771112/220590376-43fadb4c-7936-4d86-b7b1-5a246b8e09e8.png">

**Comment by Kenshin** [comment]
emmm

1. 使用 https://sspai.com/post/69972 测试。
2. 去掉截图中的内容

    <img width="465" alt="image" src="https://user-images.githubusercontent.com/81074/220593037-4df81392-9f2e-417d-832f-cfa074175bba.png">

3. 改为同步助手增强导出方案 e.g. `{"extension":"assets", "path":"/Users/xxx/xxx/Obsidian@simpread/Inbox" }`

    <img width="659" alt="image" src="https://user-images.githubusercontent.com/81074/220593637-5a6f77ec-3efc-4e65-992a-5fdbfa4655ac.png">

**Comment by llity** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/11771112/220604006-597cfb4c-8e82-4500-a0ef-256848cc9bd3.png">
测试失败，和ob的插件有关系吗？不行就暂时不用此功能了。

**Comment by Kenshin** [comment]
> 测试失败，和ob的插件有关系吗？不行就暂时不用此功能了。

没关系，是跟同步助手有关系。

一个提示：你使用了 方案二，跟 https://github.com/Kenshin/simpread/issues/4517#issuecomment-1439839629 无关，这是方案三的功能。

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/81074/220604652-7a7e8099-e930-423d-a7f2-628363a0fe50.png">

**Comment by llity** [comment]
我就用的首选方案。确实不行，后面换一台电脑试一试。真是头疼

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
