### ISSUE TITLE
不希望显示右下角的控制栏

### ISSUE THREAD

**Issue by zhoujitongxue** [Kenshin/simpread#4523]
阅读模式下关闭了显示右下角的控制栏，但是每次鼠标移动到右边就会显示控制栏，请问怎么可以在鼠标移到到右边也不会显示控制栏

**Comment by Kenshin** [comment]
暂时没有这种功能，右下角控制栏是阅读模式的核心。

但你可以通过自定样式解决。

```
sr-rd-crlbar {
    display: none!important;
}
```

加入到下图所示位置

![image](https://user-images.githubusercontent.com/81074/192174049-7a82f06c-0dbc-4797-bf51-84060920c21a.png)
