### ISSUE TITLE
无法自动导出全文到 Obsidian

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#4525]
**请说明发生问题的环境**

- 操作系统: **MacOS**

- 浏览器版本: **Chrome 105.0.5195.125**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**问题**

加入稍后读或添加标注后：**没有自动导入全文到 Obsidian；**

> - 会自动生成标注文件；
> - 手动点击插件可以导出全文；
> - 手动输入 `ob` 快捷键可以导出全文；

**截图**
1. 加入稍后读；
<img width="640" alt="image" src="https://user-images.githubusercontent.com/11768760/192150844-caef0ddc-68a3-485f-965a-ec6739c06f15.png">
2. 只有扩展的自动化生成 HTML：
<img width="640" alt="image" src="https://user-images.githubusercontent.com/11768760/192150942-e5b05a99-3eeb-4db4-9825-f307cd103bbe.png">

**我的配置**
- 开启导入全文
<img width="640" alt="image" src="https://user-images.githubusercontent.com/11768760/192151201-a9a1a094-7a90-493c-bf53-ffab1645fb4f.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/11768760/192151111-59a41c15-2b96-4af1-9670-739759efa9e3.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/11768760/192151275-cf333742-4831-4609-89f7-314364538ae7.png">

- 全文的保存目录为 Obsidian 文件夹：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11768760/192151375-f9e8e896-95c2-4865-bb8f-6d22bc99d320.png">

- 自动化插件配置：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11768760/192151447-88be42aa-4402-44c6-9794-d922fbd13968.png">

- 手动触发导出全文：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11768760/192151533-7569b9a8-ac62-43a9-83c4-2276a6d7de79.png">

- 成功导出全文：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11768760/192151586-d0368bc0-9d9f-4e3d-976a-42aca5b91386.png">

**Comment by Kenshin** [comment]
加入稍后读后，打开 DeveTools 看看有没有报错？

<img width="325" alt="image" src="https://user-images.githubusercontent.com/81074/192174199-0e3b27a4-121b-4800-8ad8-cfb845e17165.png">

感觉应该你是使用了 Markdown 2.0 模板造成的错误，你可以试试 https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2983977 这个模板。

**Comment by HasonHuang** [comment]
已解决，确实是模板问题。

加入稍后读时报错：
<img width="915" alt="image" src="https://user-images.githubusercontent.com/11768760/192176330-433ac783-e25a-41ce-986b-2160323fef02.png">

**Comment by Kenshin** [comment]
搞定就好~

**Comment by Kenshin** [comment]
嗨，针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。
