### ISSUE TITLE
Chrome 浏览器偶尔崩溃

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#4526]
**请说明发生问题的环境**

- 操作系统: **MacOS**

- 浏览器版本: **Chrome 105.0.5195.125**

- 简悦版本 **2.2.0**

**问题**

在阅读模式、稍后读里使用快捷键 `cmd + w` 关闭标签页，偶尔出现浏览器崩溃（浏览器自动关闭），表现为：
- 卡顿一小会；（约 1 秒内）
- 浏览器自动关闭；

> 升级最新版的`插件管理器`前没有出现过。

**截图**

已安装插件：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11768760/192151848-049cb6b8-a0fa-4877-99d5-4647a30ed881.png">

**Comment by Kenshin** [comment]
嗨，简悦不会引起此问题，所以：

1. 任意一个 URL 都存在这个问题？
2. **隐身模式下仅使用简悦的方式** （用来排除是否是其它扩展造成的干扰）

另外，进入阅读模式后，关闭标签页的话，可以试试 https://simpread.ksria.cn/plugins/details/CqJNpaqbja 进入使用快捷键 `x x` 关闭标签页。
