### ISSUE TITLE
行间距定义成了原文的行间距

### ISSUE THREAD

**Issue by xcffl** [Kenshin/simpread#453]
![screenshot_20190215_115331](https://user-images.githubusercontent.com/2216902/52833622-8c359580-30d5-11e9-8eb0-6e4e13208f34.png)

阅读视图面板上的「行间距」选项似乎定义成了设定原文的行间距，而非阅读视图下每行的间距。
例如上图中，修改行间距只会修改「have already been invited」之间的间距，而不会改变「use cases」之间的间距。

**Comment by Kenshin** [comment]
（疑似）因为折行的缘故？

我在外休假，能处理的时候会回复你，谢谢反馈～

**Comment by Kenshin** [comment]
我刚刚回来，测试了下，并没有你说的问题。
有问题的 URL 方便的话，发上来看看。
