### ISSUE TITLE
已标注的页面在刷新后，段落中的重复词语全部被高亮

### ISSUE THREAD

**Issue by hi-yiyang** [Kenshin/simpread#4534]
- 操作系统 **Windows**

- 浏览器版本 **Chrome 105.0.5195.127**

- 简悦版本 **2.2.0.520**

- 发生问题的地址
  https://www.science.org/doi/full/10.1126/science.1227289
  https://www.sciencedirect.com/science/article/pii/S0960982218305657?via%3Dihub

**请描述你的问题**

示例一：如图，这两个段落的特殊词语在未被标注处也全部被高亮了。其余段落正常。

![image](https://user-images.githubusercontent.com/51028862/192890155-6971f2b0-9012-40d5-9ded-2d4427d98f24.png)

示例二：如图，段落中的数字“9”和逗号被全部高亮了。其余段落正常。

![image](https://user-images.githubusercontent.com/51028862/192890477-f4ff94c3-4a91-4881-bf4b-a99483a66099.png)

标注时没有问题，页面刷新后问题稳定复现。

**Comment by Kenshin** [comment]
嗨，英文类页面因为字重的缘故，在极限情况下确实会发生这样的问题，我先记录下。

PS：但仅仅只是极端情况。

**Comment by hi-yiyang** [comment]
增加一个语雀的example. 
https://www.yuque.com/deerain/gannbs/bzoyql

![image](https://user-images.githubusercontent.com/51028862/193562730-10565cdf-5ef7-428a-8451-1ab56161d8c8.png)

只高亮一次“图床”“base 64”的情况下，所有关键词全部高亮。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~


解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
