### ISSUE TITLE
PDF 导出功能，无法在扩展端切换成「同步助手高级打印方案」

### ISSUE THREAD

**Issue by TYZRPVX** [Kenshin/simpread#4536]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/7645818/192955344-05f9b5fd-ea55-4ead-a448-3d2b67e20b05.png">

在扩展端找不到对应的设置入口

参考文档: https://github.com/Kenshin/simpread/discussions/3887

**Comment by Kenshin** [comment]
嗨，这个功能是需要安装对应插件的

<img width="423" alt="image" src="https://user-images.githubusercontent.com/81074/192962407-d250670a-2481-4c14-b857-335785d79fef.png">

https://github.com/Kenshin/simpread/discussions/2721

如果使用了同步助手的话，请通过 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装插件

**Comment by TYZRPVX** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/7645818/192992368-66a19fb6-c38a-4975-bcc5-bfdca40063ab.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/7645818/192992395-174e4102-b37f-4d7d-b9ba-f9ed99094ae3.png">

@Kenshin   已经确认安装了 pdf 插件，同步助手也打开了开关，但是**扩展端**还是找不到对应的设置入口

**Comment by Kenshin** [comment]
嗨，我已经告诉你了

你需要的选项并不在同步助手中，而是下图

<img width="836" alt="image" src="https://user-images.githubusercontent.com/81074/192999872-88f43169-a1b4-43ae-8d2d-eaccaed2c804.png">

如果你没有发现插件触发器的话，使用下图所示的方式解决

<img width="381" alt="image" src="https://user-images.githubusercontent.com/81074/192999658-2ebb70c9-7bcc-4a3b-bf97-71b6a09e104d.png">

**Comment by TYZRPVX** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/7645818/193001425-b7a25434-cf94-4d0c-988b-d87257ef2504.png">

可能我没表述清楚。现在的问题是**点击红框位置的选择，无法进行切换**，已经确认打开了桌面端同步助手，并打开了对应开关

**Comment by Kenshin** [comment]
点击红框里面的 **三角形** 图标

<img width="602" alt="image" src="https://user-images.githubusercontent.com/81074/193007599-dd09fe37-2663-4ba7-b3c5-d50506a71edd.png">

**Comment by Kenshin** [comment]
绕了半天，竟然是这个问题... 😂
