### ISSUE TITLE
导入到 Obsidian 插件配置里的“是否使用md+assets方式？”开关和路径配置在刷新页面后就没了

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4538]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows 11**

- 浏览器版本 **Microsoft Edge 版本 105.0.1343.50 (正式版本) (64 位)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 导入到Obsidian 插件配置里的“是否使用md+assets方式？”开关和路径配置在刷新页面后就没了

**截图**
配置保存
> ![image](https://user-images.githubusercontent.com/3283023/192992987-25c3a0d3-839b-4d8b-a92b-c510c1b761bc.png)
配置保存后，刷新网页，重新进入阅读模式打开插件选项，就变成下面这样了
> 
![image](https://user-images.githubusercontent.com/3283023/192993041-ffbd949b-97cb-4c98-b9ab-6c36a2938a4b.png)

**Comment by Kenshin** [comment]
嗨，这是个 Bug。

可以通过 [插件管理器](https://user-images.githubusercontent.com/81074/192999658-2ebb70c9-7bcc-4a3b-bf97-71b6a09e104d.png) 解决，链接内含解决方案，请留意下使用说明。

**Comment by iblogc** [comment]
> 嗨，这是个 Bug。
> 
> 可以通过 [插件管理器](https://user-images.githubusercontent.com/81074/192999658-2ebb70c9-7bcc-4a3b-bf97-71b6a09e104d.png) 解决，链接内含解决方案，请留意下使用说明。

好的，我试下
