### ISSUE TITLE
扩大聚焦范围

### ISSUE THREAD

**Issue by tiancheng2000** [Kenshin/simpread#454]
在需要手动聚焦的页面，希望能增加类似“+”“-”这样的、不需要依赖于鼠标点击来选择聚焦范围的方式，理由是有些区域范围的<div>是不可见的，能被精确点击到的可能只是它的一个子集，
（可请参见这一页面：http://www.ggzzchina.com/News_Show.php?id=102）
印象笔记的“剪藏”插件，已经实现了该功能，界面设计上可以参考这个，或者请作者提示一下大致的修改范围，我（虽然还没有Chrome插件开发经验）或许也可以代为修改+测试一下的 😂🙏
![5cde329b-b0b4-45c8-ba57-5ada75610419 png](https://user-images.githubusercontent.com/3139658/53320260-0fde5600-3910-11e9-852d-3a48fdb8d787.jpg)

**Comment by Kenshin** [comment]
谢谢建议，我不错的想法。

我会加到 To-do 里面。

**Comment by tiancheng2000** [comment]
感谢您的尽心投入，令大家收益！～🙏

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

增加了 [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

谢谢你的建议~ 我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)

**Comment by tiancheng2000** [comment]
撒花!～ 不过在我的两个环境中(Win10，Chrome 65.0.3325.146)，却都无法看到如帮助中所示的控制栏？
1. 试过提问中的链接，或是简书的个人首页，按AS进入聚焦模式，将聚焦在错误的Block中，且不显示控制栏
2. 试过直接选中页面中一个段落，也并不显示控制栏（也没有“手动聚焦模式”之类的右键命令出现😉）
3. 试过F11进入全屏模式，也均未能看到控制栏
不知是何原因呢？
![image](https://user-images.githubusercontent.com/3139658/60406400-370fa180-9be8-11e9-9b34-4e0b0d9a1fac.png)

**Comment by tiancheng2000** [comment]
撒花!～ 不过在我的两个环境中(Win10，Chrome 65.0.3325.146)，却都无法看到如帮助中所示的控制栏？
1. 试过提问中的链接，或是简书的个人首页，按AS进入聚焦模式，将聚焦在错误的Block中，且不显示控制栏
2. 试过直接选中页面中一个段落，也并不显示控制栏（也没有“手动聚焦模式”之类的右键命令出现😉）
3. 试过F11进入全屏模式，也均未能看到控制栏
![image](https://user-images.githubusercontent.com/3139658/60406400-370fa180-9be8-11e9-9b34-4e0b0d9a1fac.png)

**Comment by Kenshin** [comment]
emmm...

这个功能并未在 **聚焦模式** 下实现，而是阅读模式... 详细请看  http://ksria.com/simpread/docs/#/手动框选?id=二次确认

**Comment by tiancheng2000** [comment]
uh?…是不是哪里不对了呢（阅读模式和帮助链接显然我也都是核实过的）
原来问题的根源是……我才想起右下角菜单里还有个“重新选择高亮区域”功能😂
的确，进入阅读模式—> 选择右下角菜单 > 动作 > "重新选择高亮区域"图标—> 再次退回全页面、出现了“手动框选模式”！～
