### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by lkjhgfdsallx** [Kenshin/simpread#4540]
发生问题的地址: <https://cwl.eduexam.cn/Learn/Index/151>

**Comment by Kenshin** [comment]
嗨，因为需要登录，所以我无法查看，但一般来说这类页面是不会被适配的。

不过，你可以使用下图的方式一般都能解决。

![image](https://user-images.githubusercontent.com/81074/193180630-8e1fe582-3980-4e20-a165-bf829f33a71b.png)
