### ISSUE TITLE
插件[导入到Obsidian]唤起ob不能定位到应对的文章

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4541]
请说明发生问题的环境

简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

操作系统 ** Windows 11**

浏览器版本 Microsoft Edge 版本 105.0.1343.50 (正式版本) (64 位)

简悦版本 2.2.0

发生问题的地址 <请填写你的地址l>

请描述你的问题

插件【导入到Obsidian 】里，导入方式选择`方案二`在导入成功后点击右上角的“已经保存到Obsidian,是否打开？”选择能打开ob并定位到对应的文章页面，但选择`方案三`同步成功点击消息打开ob并不能定位到对应的文章，只是简单的切换ob界面到前台。
![image](https://user-images.githubusercontent.com/3283023/193216599-6ab5fd71-283e-4a69-8ae0-48a089dfb42a.png)
![image](https://user-images.githubusercontent.com/3283023/193216946-200ab73c-9b7d-42cb-a27f-875f5705cbed.png)

**Comment by Kenshin** [comment]
目前是这样的。

简单的说，方案三使用了 Obsidian SimpRead Sync 模式，导入后由这个插件 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/81074/193221664-86efee15-e291-4fbc-9234-635486500280.png">

所以不需要在插件端设置

<img width="620" alt="image" src="https://user-images.githubusercontent.com/81074/193221942-3f8da1ee-6309-4ca1-ae06-89321c9ec404.png">

***

不过，这样吧，我觉得还是恢复定位比较好，我修改完会在这里通知你。

**Comment by Kenshin** [comment]
这个问题解决了，重新安装 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 即可。

**Comment by iblogc** [comment]
@Kenshin 谢谢，可以跳转了🤝
