### ISSUE TITLE
高级账户是否可以移除 Notion 正文小尾巴

### ISSUE THREAD

**Issue by sankoshine** [Kenshin/simpread#4543]
保存到Notion之后，正文最后有一个小尾巴

> \> 本文由简悦 SimpRead 转码

是否可以考虑对高级账户去除？或者对 Notion 去除……

Notion 保存之后大部分用户都是自己阅读的

**Comment by Kenshin** [comment]
1. 这种算是免责声明而不是广告，简悦不需要这种形式的推广也没有任何形式的推广。
2. 下个版本会有正文定制化的功能。
