### ISSUE TITLE
在ob的SimpRead UnReader视图里进行标记导致ob里的标注样式样式改变

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4546]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 11**

- 浏览器版本 **Microsoft Edge 105.0.1343.50 (正式版本) (64 位)*

- 简悦版本 **2.2.0**

**请描述你的问题**

在浏览器端标记自动导入到ob后，样式显示正常，如下图
![image](https://user-images.githubusercontent.com/3283023/193224691-fcf9d6a2-a2fe-4dea-a69f-6498f192b381.png)

标注的源文本为
```
> [!srhl6] [[SR8@放弃纠结、拥抱妥协，重器轻用就是高效 - 少数派|📄]] <mark style="background-color: #ffb7da">Highlights</mark> [🧷](<http://localhost:7026/unread/8#id=1664525897474>) [🌐](<#id=1664525897474>)   
> 败可以「草木竹石均可为剑」，如果换
> ^sran-1664525897474
```

在ob里打开SimpRead UnReader进行标识，后样式变为下图
![image](https://user-images.githubusercontent.com/3283023/193224831-083bf88b-91a6-46e3-b3e0-f85057f73f6e.png)

标注的源文本变为
```
> [📌](<http://localhost:7026/reading/8#id=1664525897474>) <mark style="background-color: #ffb7da">Highlight</mark> 
> 败可以「草木竹石均可为剑」，如果换

^sran-1664525897474
```
去浏览器端再去标识一次样式恢复

**Comment by Kenshin** [comment]
嗨，这不是 Bug，而是：

1. Markdown 模板辅助增强插件
2. Obsidian SimpRead Sync

这两个地方都可以设置模板。

你在这两个地方设置的模板使用同一个即可（即：Markdown 模板辅助增强插件对应的模板）

**Comment by iblogc** [comment]
@Kenshin 看到这个回答的时候我已经研究明白了并把两个地址的模板改成了同一个，然后我又我去提新bug了😂
