### ISSUE TITLE
导入到 Obsidian 插件 Metadata 信息定制问题

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4547]
请说明发生问题的环境

简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

操作系统 Windows 11

浏览器版本 *Microsoft Edge 105.0.1343.50 (正式版本) (64 位)

简悦版本 2.2.0

插件【导入到 Obsidian】

问题一：导入全文的 Metadata 信息里的 定制标签的前/后缀 功能不生效，如图
![image](https://user-images.githubusercontent.com/3283023/193242485-ba3407e0-ddd4-4c08-b420-c4623fe085ff.png)
![image](https://user-images.githubusercontent.com/3283023/193242500-e7debc9b-89db-4157-aa22-f3ec4ef65575.png)

问题二：Metadata 信息里的 summary 有方法把内容里的换行去掉吗，因为在 yml 里会导致格式不合法，如图
![image](https://user-images.githubusercontent.com/3283023/193243082-62198215-32aa-44ca-9d82-d870b37d6d4b.png)
![image](https://user-images.githubusercontent.com/3283023/193243142-1a54209e-fcec-43cb-90cb-4021def645da.png)

**Comment by Kenshin** [comment]
> 问题一

我没有遇到这个问题，请问是否可以稳定复现？

> 问题二

不错的想法，可以考虑

**Comment by iblogc** [comment]
@Kenshin 
问题一我这边百分百复现

**Comment by Kenshin** [comment]
你把 Meta 的代码发上来，我看看。

**Comment by iblogc** [comment]
@Kenshin 
```
---
url: {{url}}
title: {{title}}
date: {{date}}
tag: {{#|tag| }}
tag1: {{tags}}
summary: {{desc}}
---
```

**Comment by Kenshin** [comment]
使用你提供的 Metadata 没有问题

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/81074/194705086-2977bd62-a1d3-48a3-858c-c66b459fc9be.png">

![image](https://user-images.githubusercontent.com/81074/194705045-3af545df-473c-46b8-860a-747b10ad4a72.png)

**Comment by iblogc** [comment]
我把上面的配置重新复制进去保存，换了篇文章，进阅读模式，重新标注，自动导入ob，还是不行😢
![image](https://user-images.githubusercontent.com/3283023/194705400-a4f39ec7-e429-41d5-841a-deb06806c9bc.png)
![image](https://user-images.githubusercontent.com/3283023/194705408-a47508fe-c7da-4b26-9b31-fddcf0e01aac.png)
![image](https://user-images.githubusercontent.com/3283023/194705496-6a9ceb91-1af0-44c3-81bc-400fe58084a9.png)

**Comment by Kenshin** [comment]
明白你的问题了…

首先，截图对应的不是 Metadata… Metadata 只针对与正文（稍后读）…选项的文档已经说的很清楚了。

你可以添加稍后读的标签，然后导出到 Obsidian 

如果还是没理解的话，录屏给我你的操作。

**Comment by iblogc** [comment]
我明白了，稍后读有另一个标签，刚刚可以了，但tag和tags是包含关系是吗（如图）
![image](https://user-images.githubusercontent.com/3283023/194736167-b5121b7d-899f-4978-903f-d6773e20630c.png)
![image](https://user-images.githubusercontent.com/3283023/194736588-374f0d2b-3a66-40aa-8a8c-92a919e86cbe.png)

**Comment by Kenshin** [comment]
> 但tag和tags是包含关系是吗

不是... 不清楚你是如何出现的，能否复现？（不出意外的话，应该不是 Bug，因为也用户量还不错，如果是 Bug 的话早就被发现了。😂

**Comment by iblogc** [comment]
我找了一篇新文章操作录屏下了，情况还是一样，是我操作哪里不对吗？
[20221009143232.webm](https://user-images.githubusercontent.com/3283023/194741772-8c26067b-2309-4ff9-8667-0a0db17df166.webm)

**Comment by Kenshin** [comment]
emmm 你按照我说的方式试试：

1. 加入稍后读
2. 添加稍后的标注

**Comment by Kenshin** [comment]
嗨，Obsidan 配置库发布了，针对新用户或不喜欢配置的用户。

细节请看下面。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by iblogc** [comment]
> 嗨，Obsidan 配置库发布了，针对新用户或不喜欢配置的用户。
> 
> 细节请看下面。
> 
> ![img](https://camo.githubusercontent.com/093ac4351ff1633e5a52a8277978ec67ab9921093f65c019c6231cfb25cb8719/68747470733a2f2f696d67732e7a68756261692e6c6f76652f63363236363738666636623634646431616339646664616536636636643138382e706e67)
> 
> > 针对新用户的一步到位的 Obsdian 配置库。
> 
> ## 🗂 配置库
> [简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。
> 
> ## 💡 特点
> 用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。
> 
> ## 💁‍♂️ 受众
> 新用户或者不想使用手动配置的用户。
> 
> ## 📝 如何使用
> 1️⃣ 下载
> 
> 2️⃣ 修改为自己的 UID
> 
> 3️⃣ 将必要的文件夹复制粘贴到相应位置
> 
> ✅ Done！
> 
> ## 📚 Obsidian 配置库
> ## 📝 特点
> 1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian
> 
> 2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian
> 
> 3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian
> 
> 4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注
> 
> ## 📖 区别
> ![img](https://camo.githubusercontent.com/56dd1b1346d73b07f4ef51c044b2cffba62654a0e9fc6facde3165f2b7a24605/68747470733a2f2f696d67732e7a68756261692e6c6f76652f66346135316438653866623434303132383162303766383262663062633764312e706e67)
> 
> ## 📘 极速版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)
> 
> 不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。
> 
> ## 📙 基础版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)
> 
> 需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。
> 
> ## 📗 高级版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)
> 
> 需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

@Kenshin 这个是不是发错地方了😂

**Comment by iblogc** [comment]
> emmm 你按照我说的方式试试：
> 
> 1. 加入稍后读
> 2. 添加稍后的标注

添加完稍后读后，我到稍后读页面添加标注吗？因为阅读页面没有文章标注前提下右侧是没有下面这个显示的所以加了不文章标注
![image](https://user-images.githubusercontent.com/3283023/195064751-482fa845-f685-41c7-9cd6-e298aa22f125.png)

**Comment by Kenshin** [comment]
> 添加完稍后读后，我到稍后读页面添加标注吗？因为阅读页面没有文章标注前提下右侧是没有下面这个显示的所以加了不文章标注

没理解你的问题... 😂

**Comment by iblogc** [comment]
@Kenshin 你好，我想问下，我正常添加了稍后读标标注和文章内容标注的情况下
![image](https://user-images.githubusercontent.com/3283023/195066472-92bba419-94ae-42a5-9069-e39b0326c32d.png)

tag: {{#|tag| }}
tag1: {{tags}}
这两个标签应该分别显示什么内容才是正常的

**Comment by iblogc** [comment]
> > 添加完稍后读后，我到稍后读页面添加标注吗？因为阅读页面没有文章标注前提下右侧是没有下面这个显示的所以加了不文章标注
> 
> 没理解你的问题... 😂

我意思是加稍后读后，这个阅读模式界面是没有地方添加稍后读标注的
![image](https://user-images.githubusercontent.com/3283023/195068298-bb8ad388-7bb9-4a2c-b9ba-4cfedb7b10e7.png)
所以按你的步骤我是不是要到稍后读界面上添加稍后读标注
![image](https://user-images.githubusercontent.com/3283023/195068585-b2770f50-7d95-44cd-87ac-2437070c3af6.png)

**Comment by Kenshin** [comment]
> 我意思是加稍后读后，这个阅读模式界面是没有地方添加稍后读标注的

把 URL 给我看下，另外试试其它页面加入稍后读后是否有标注侧栏？

**Comment by iblogc** [comment]
https://www.iplaysoft.com/kingsoft-cloud-tech-font.html
其它页面也不会出现，我以为这是正常的😁
我是这样加稍后读的
![image](https://user-images.githubusercontent.com/3283023/195078223-0b8776a2-d000-470f-9d37-bd8ca594d4bf.png)

**Comment by Kenshin** [comment]
我明天看下。

不过，如果稍后读不多，还在调整配置的话，建议直接使用 https://github.com/Kenshin/simpread/issues/4547#issuecomment-1274172284 一步到位，省得折腾了。

**Comment by iblogc** [comment]
我用插件管理器导出了下全部配置到本地后，加入稍后读会有右侧侧栏出来了。
```
---
url: {{url}}
title: {{title}}
date: {{date}}
tag: {{#|tag| }}
tag1: {{tags}}
summary: {{desc}}
---
```
我在侧栏里添加稍后读的标注 tag 和tag1都会有这个标注，
![image](https://user-images.githubusercontent.com/3283023/195257704-4f7077ee-a8f3-4f33-bda3-3f484ed69db1.png)
![image](https://user-images.githubusercontent.com/3283023/195257631-1d8feca3-6100-4af3-ac47-40697f4d6898.png)

我再添加一个文章内容的标注，只会出现在tag1里
![image](https://user-images.githubusercontent.com/3283023/195257504-30ba1e99-333c-4691-a28b-62a146345e55.png)
![image](https://user-images.githubusercontent.com/3283023/195257612-3596f145-e997-4503-b3ab-30eb99223869.png)

这样是正常的吗😂

**Comment by iblogc** [comment]
> 我明天看下。
> 
> 不过，如果稍后读不多，还在调整配置的话，建议直接使用 [#4547 (comment)](https://github.com/Kenshin/simpread/issues/4547#issuecomment-1274172284) 一步到位，省得折腾了。

我看了你写的这篇配置文章，里面所提到的我都已经配置过了，不想再换折腾，感觉目前除了一些小问题已经能用了😂
小问题如下：
1. 上面所提的`{{#|tag| }}``{{tags}}`内容不一致问题
2. 有时会出现在浏览器阅读模式页面删除文章内容标注后，刷新页面标注重新出现
3. 文章内容标注后有时并不会同步到ob的xxx@annote文件里
2、3为低概率，我昨天碰到了，但复现不出来😂

顺便确认几个问题
1. 同步助手里的【一键收藏】书签工作就是把网页添加到【稍后读】里是吗？
![image](https://user-images.githubusercontent.com/3283023/195259836-21ab25c2-52e9-4a2c-82db-723db4a4980e.png)

2. [阅读列表]是所有添加到稍后读内容都会展示吗？
![image](https://user-images.githubusercontent.com/3283023/195259857-dcd129fb-efbc-4f29-a8a7-522d529ffa8d.png)

3. 我删除了稍后读里的一篇文章，阅读列表里的内容我还是要去output文件夹删除html文件才行并不会自动删除是吧？

**Comment by Kenshin** [comment]
> 有时会出现在浏览器阅读模式页面删除文章内容标注后，刷新页面标注重新出现

可能是操作太频繁，触发了保存机制，导致保存成功。（我会通过升级同步助手的算法来改善这个情况）

> 上面所提的{{#|tag| }}``{{tags}}内容不一致问题 https://user-images.githubusercontent.com/3283023/195257504-30ba1e99-333c-4691-a28b-62a146345e55.png

这个图的说明有点问题，标注的标签不会出现在稍后读中。

> 文章内容标注后有时并不会同步到ob的xxx@annote文件里

这个应该不会，只要你设置了自动化辅助增强的话，应该不会，如果会的话，应该也是个例。

> 同步助手里的【一键收藏】书签工作就是把网页添加到【稍后读】里是吗？

是的，但只包含 URL 不包含快照，这个功能是为了让其它浏览器用户也能使用简悦而开发的，你应该用不到。

> [阅读列表]是所有添加到稍后读内容都会展示吗？

不是，是加入到 `output` 中的内容会显示出来，如果恰好用了自动化的话，其实 `output` = 稍后读

**Comment by iblogc** [comment]
@Kenshin 好的，谢谢

**Comment by Kenshin** [comment]
嗨，看到你很积极（提供了好几个 Issues）

欢迎加入我刚刚建立的 wx 群 👏 👏 （进群后，把你的群昵称改为 Github ID，这样我就知道你是谁了~）

![image](https://user-images.githubusercontent.com/81074/196584759-5bf41dd2-193e-4e93-8ee9-921ba0714df2.png)

如果方便的话，也可以进 Telegram 群（里面已经有 2K+ 的小伙伴）

![image](https://user-images.githubusercontent.com/81074/196584825-986c986c-d609-4e25-8543-0efb11dcfbfa.png)

**Comment by iblogc** [comment]
几年前就加了 Telegram 群😂，wx群之前不知道，我加下

**Comment by Kenshin** [comment]
哈，竟然 nnnn 久之前就进过 Telegram 群 😂

**Comment by Kenshin** [comment]
我的天，我翻了下这个超长的 Issues 才知道讨论什么，太久了 😂

PS：解决就好，我关闭这个 issues 了。

**Comment by lisasuosuo** [comment]
提示这个telelgram群是private的，是不能进吗？
