### ISSUE TITLE
导出离线 html 代码块展示异常

### ISSUE THREAD

**Issue by TYZRPVX** [Kenshin/simpread#4549]
![image](https://user-images.githubusercontent.com/7645818/193298901-11927cee-4c92-4541-af7b-836d85952d18.png)

https://zhuanlan.zhihu.com/p/98977969 示例知乎专栏的 url，启动阅读模式，导出离线 html，代码块很难看清晰

**Comment by Kenshin** [comment]
嗨，导出的 HTML 不要通过安装简悦的浏览器查看，因为其中的样式会互相干扰，你可以使用另外的浏览器或者隐私模式下查看。

PS：如果使用了同步助手后，并 [配置了知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 后可以使用 http://localhost:7026/reading/xxx 的方式查看。

**Comment by TYZRPVX** [comment]
试了一下，还有一个曲线救国方式，使用 https://github.com/Kenshin/simpread/discussions/4519 里面的 web server 插件，然后进入阅读模式，问题就解决了。

不过有一个问题，为什么“其中的样式会互相干扰”，是不是没打开阅读模式时，简悦可以不加载自己的样式，规避离线 html 展示的问题？ @Kenshin

**Comment by Kenshin** [comment]
> 还有一个曲线救国方式，使用 #4519 里面的 web server 插件，然后进入阅读模式，问题就解决了

emm 是的，这种方式也可以。

> 为什么“其中的样式会互相干扰”，

简悦会预先加载一些内容这样当进入阅读模式时会比较快，如果将这个页面加入黑名单的话，简悦会先加载然后自我删除（判断的基准是以简悦的代码为检索条件）。

而导出的 HTML 本身就含有了简悦的样式和相关代码，因此刚才说的判断会失效，同时也会产生出现主题互相覆盖的问题。

**Comment by TYZRPVX** [comment]
![image](https://user-images.githubusercontent.com/7645818/193402861-5b99813c-80f4-4c6a-9b98-e31f9c2751da.png)

已经开启了标注功能，但是 web server 打开的离线 html，选中文本无法展示标注的横栏 @Kenshin  可以帮忙再看看吗 😂

**Comment by Kenshin** [comment]
这份 `.html` 是怎么生成的？通过简悦？还是？

**Comment by TYZRPVX** [comment]
> 这份 `.html` 是怎么生成的？通过简悦？还是？

是的，通过简悦，我把这个文件上传一下 

https://1drv.ms/u/s!At1PfpZbqkImgQ63q-EJvlyrygqc?e=glbFTH

**Comment by Kenshin** [comment]
emmm  感觉有点「绕」了…

已经用简悦导出的 HTML 可以用 #4519 的方式查看。

如果需要标注的话，可能有点问题，因为跟之前解释的差不多。

所以，最好是这个 HTML 已经存在稍后读的前提下，就能正常使用标注了。
