### ISSUE TITLE
对于有 Latex 公式的文章支持问题

### ISSUE THREAD

**Issue by Chlience** [Kenshin/simpread#455]
对于有 Latex 数学公式的文章，阅读器将会把它还原，如 Σ 将会被还原为 $\sum$，望适配

**Comment by Kenshin** [comment]
关联问题 https://github.com/Kenshin/simpread/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+MathJax

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 


***

例如 https://github.com/Kenshin/simpread/issues/412 即是解析 LaTeX 后的效果。
