### ISSUE TITLE
Arc 浏览器无法通过小窗模式打开稍后读，点击弹出窗口后浏览器崩溃

### ISSUE THREAD

**Issue by QuarterHeaven** [Kenshin/simpread#4550]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 MacOS 12.6

- 浏览器版本 Arc Version 0.70.0 (34916) Chromium Engine Version 106.0.5249.62

- 简悦版本 **2.0.0**

- 发生问题的地址 稍后读页面或任何页面按下稍后读快捷键

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

在稍后读页面按下小窗模式按钮，或者直接通过插件打开稍后读，弹出小窗后立刻消失，并在 tab 中出现 Untitled Tab，点击 Untitled Tab 以后浏览器崩溃。

这是一个还在内测的浏览器，我不知道你们是否方便测试，如果可以的话希望能够解决这个问题。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

https://user-images.githubusercontent.com/41909950/193301062-915bd37b-b73d-4051-8f4a-d95eb56017f8.mov

**Comment by Kenshin** [comment]
嗨，这不是简悦的问题，而是 Arc 的问题。

另外，使用了 Arc 后，并不需要使用此功能。
