### ISSUE TITLE
求适配网站：https://kexue.fm

### ISSUE THREAD

**Issue by fangd123** [Kenshin/simpread#4551]
目前的适配结果很奇怪，框选后没有效果，https://kexue.fm/archives/9119

**Comment by Kenshin** [comment]
嗨，这个页面确实没法用过手动模式生成阅读模式，很奇怪，我先记录（研究）下。

**Comment by guopenglife** [comment]
求适配。

**Comment by xubuild** [comment]
一直没适配啊。。。

**Comment by lclichen** [comment]
```
<div class="Post">
```
可能更美观一些~

**Comment by Kenshin** [comment]
嗨，抱歉，漏掉了一个这么「老」的 Issues 😂

这个站已经适配了

### 更新适配规则

选项页 → 站点管理 → 根据下图所示更新

<img width="939" alt="image" src="https://github.com/user-attachments/assets/6bae3ca5-b078-40dc-accb-bbcbda4b51fe">

将 `kexue.fm` 加入延迟加载列表（因为有 MathJax 公式）

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/32570bb2-a703-468d-a9f3-09c0aea0a037">

重启浏览器，手动进入阅读模式，效果如下。

![image](https://github.com/user-attachments/assets/bde0df7f-66a1-4eb3-bbbd-3cd01c546dbb)
