### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by jzzzvnpy** [Kenshin/simpread#4552]
发生问题的地址: <https://mbd.baidu.com/newspage/data/videolanding?nid=sv_10239112084673521187

**Comment by Kenshin** [comment]
嗨，这类页面不需要适配，我关闭这个 Issues 了~

**Comment by jzzzvnpy** [comment]
大佬，我收到了您的回复，感谢。
但我没理解这类页面不需要适配，那怎么消除&nbsp; 视频声音&nbsp; 是 两个呢？
打扰了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2022年10月3日(星期一) 晚上6:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 无法适配当前页面 (Issue #4552)





 
嗨，这类页面不需要适配，我关闭这个 Issues 了~
 
&mdash;
