### ISSUE TITLE
增强导出可能需要增加配置属性

### ISSUE THREAD

**Issue by shaomingbo** [Kenshin/simpread#4553]
目前[增强导出](https://github.com/Kenshin/simpread/discussions/2958#discussioncomment-2713824)只支持通过`extension`来配置导出方案。但，同一个`extension`会对应全文和标注2种内容。本来Hazel 能解决此问题，但看到同步助手正在尝试给出解决方案，故提议希望通过增加配置属性，来让该功能更完善。

- 场景：我在使用Logseq 的时候，只希望导入`*@annote.md`，而不是`*.md`全部导入。
- 高级设定-导出时可选，选`标注`可以解决此问题。但这种设定会导致在访问内部地址时404。

**Comment by Kenshin** [comment]
收到，可以考虑~ 👍

**Comment by asong2022** [comment]
请问下为什么我只能导出*@annote.md，不能导出全文的md呀

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [稍后读 · 读取外部文件](http://ksria.com/simpread/docs/#/Sync?id=增强导出)。

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

### 除此之外比较重要的更新

- `assets + md` 对媒体资源（图片）位置的定制化，需要配合以下两个插件使用：

  - 空白 [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)

  - 空白 [导出 md + assets 格式](https://simpread.ksria.cn/plugins/details/BvjrJA6eh5)

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。
