### ISSUE TITLE
在阅读模式下 DD 后，在稍后读下打开，则是双声音，请问怎么能解决

### ISSUE THREAD

**Issue by jzzzvnpy** [Kenshin/simpread#4555]
月球其实不在太空？我们都被假象迷惑，月球真实的位置被找到 https://mbd.baidu.com/newspage/data/videolanding?nid=sv_3994281261578910030&sourceFrom=pc_feedlist

AA---阅读模式---DD---稍后读---阅读模式---打开对应的标题，出来的视频声音是  重复的双声音。请教一下，能怎么解决？

**Comment by Kenshin** [comment]
嗨，同一个问题 https://github.com/Kenshin/simpread/issues/4552 不要反复新建 Isues，issues 即便关闭了也可以讨论。

***

这个页面不需要使用阅读模式，使用后效果也非常不好。（因为是视频类的页面）

你提到的两个声音是因为：原页面一个，阅读模式的页面一个。解决方案就是我说的，不要进入阅读模式。

**Comment by jzzzvnpy** [comment]
哦哦，老大这样教，我就明白了，谢谢老大 。




阿Q/:+拍卖行
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月5日(星期三) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 在阅读模式下 DD 后，在稍后读下打开，则是双声音，请问怎么能解决 (Issue #4555)





 
嗨，同一个问题 #4552 不要反复新建 Isues，issues 即便关闭了也可以讨论。
 
 
这个页面不需要使用阅读模式，使用后效果也非常不好。（因为是视频类的页面）
 
你提到的两个声音是因为：原页面一个，阅读模式的页面一个。解决方案就是我说的，不要进入阅读模式。

**Comment by Kenshin** [comment]
哈，小事情~ 😄

**Comment by jzzzvnpy** [comment]
请教大佬：
&nbsp; &nbsp; 如何把两个&nbsp;simpread_config.json合并&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 谢谢，致敬 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2022年10月5日(星期三) 中午12:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 在阅读模式下 DD 后，在稍后读下打开，则是双声音，请问怎么能解决 (Issue #4555)





 
哈，小事情~ 😄
 
&mdash;
