### ISSUE TITLE
保存批注到Ob显示成功，但在Ob中找不到对应文件

### ISSUE THREAD

**Issue by iFryRice** [Kenshin/simpread#4557]
在网页中使用Ob插件同步批注到Ob提示已同步成功，但在ob中未能找到相关文件。
![image](https://user-images.githubusercontent.com/102138235/194014222-27d6f2f2-5bad-4440-a383-dd3f3f5a41cf.png)

![image](https://user-images.githubusercontent.com/102138235/194013356-a5f124f4-b8f7-4bf4-ad10-5394d40b71fd.png)

![image](https://user-images.githubusercontent.com/102138235/194013304-0934c979-d319-484d-9dd1-7e23f6531b72.png)

插件配置如下：
![image](https://user-images.githubusercontent.com/102138235/194014154-7970fa7f-8877-43f9-b64a-1493e1ff64c9.png)

## 使用版本如下：
- 系统：win11
- 简悦·同步助手 1.1.2
- Obsidian v0.15.9 
  - SimpRead Unreader Sync 插件版本：2.1.0

**Comment by Kenshin** [comment]
应该是下面的设置写错了

<img width="755" alt="image" src="https://user-images.githubusercontent.com/81074/194039000-52859c94-f3f8-4f40-a636-9cec8d5a76ba.png">

如果是多级文件夹的话，先不要用多级目录，先以一级目录为主，确保设置成功后再测试多级目录。

***

十一期间简悦推出了一个新功能（目前为社区内测）

## 🔗 地址

https://github.com/Kenshin/simpread-configs#obsidian

## 📚 配置库

简悦配置库是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900

*** 

我关闭这个 Issues 了，有任何事情随时讨论。

**Comment by Kenshin** [comment]
嗨

导入到 Obsidian 升级到 1.5.3 专门针对 Obsidian 1.9 版本的 Metadata 规则做了升级。

***

Obsidian 1.9 引入全新的  [Bases](https://help.obsidian.md/bases) 功能，所以对 Frontmatter（ Metadata ） 的 Key 进行了严苛规则，如果你在使用简悦官方 Obsidian 模板，需要修改以下两个关键字：

- `tag` → `tags`

- `alias` → `aliases`

也就是全部变更为 **复数形式**。

# 🔗 详细说明

[永久链接](https://n.simp.red/posts/639) | [GitHub](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207) | [知乎](https://zhuanlan.zhihu.com/p/1941856337265951325) | [Newsletter](https://newsletter.simpread.pro/p/simpread-obsidian-19)

# 📝 简悦 Obsidian 模板

已经全部更新，如果有任何遗漏，[请通知我](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-14173207)。

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Obsidian](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Aobsidian) 查看更多用法

# 🔎 关联

https://github.com/Kenshin/simpread/issues/2900
