### ISSUE TITLE
在js现代教程网页版中，代码高亮提示失败

### ISSUE THREAD

**Issue by jiangyi0222** [Kenshin/simpread#4559]
https://zh.javascript.info/primitives-methods
打开简悦，其中代码并未高亮，提示失败提交issues，插件只装了这三个，其中一个禁用
![image](https://user-images.githubusercontent.com/66870696/194267087-081999bf-cf5e-4fdc-b3c0-7a455e075dfe.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

另外，不建议在这个页面使用阅读模式，因为进入阅读模式后，代码段都没法调试

**Comment by jiangyi0222** [comment]
谢谢，您回答真迅速。
用过许多付费软件，其中简悦是让我觉得投资最值得的了！

**Comment by Kenshin** [comment]
PS：不知道老用户是否帮忙评分，先谢过了~

没帮忙的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by jiangyi0222** [comment]
😘已好评

**Comment by Kenshin** [comment]
哈，Gogogo~
