### ISSUE TITLE
Live Editor 工具栏显示问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4567]
### Discussed in https://github.com/Kenshin/simpread/discussions/4566

<div type='discussions-op-text'>

<sup>Originally posted by **DrWatson777** October  8, 2022</sup>
使用 Live Editor插件的时候出现Live Editor 工具栏显示问题，只是固定在最下面，可以点击使用，请问是哪里设置的问题吗？

![Quicker_20221008_151735](https://user-images.githubusercontent.com/90584120/194696311-f9819f6a-2f6e-42a0-b1a9-e4f2b89f1d14.png)
</div>

**Comment by Kenshin** [comment]
@DrWatson777

嗨，不要在不相干的地方 Issus，我帮你新建了一个 Issues，并删除了原来位置的内容。

***

仅仅只是某个 URL 有问题吗？还是任意 URL，如果只是某个的话，试试 https://sspai.com/post/69972 是否正常？

然后在**隐身模式下仅使用简悦的方式** 在确认是否是其它扩展造成的干扰。

**Comment by DrWatson777** [comment]
非常感谢，很好用的工具。试了 https://sspai.com/post/69972 是正常的，我再试试其它。

**Comment by Kenshin** [comment]
小事情，在留意下。

我先关闭这个 Issues 了，你可以继续在这里讨论，有需要我再重开它。
