### ISSUE TITLE
建议大幅精简功能代码

### ISSUE THREAD

**Issue by lenny20** [Kenshin/simpread#457]
我喜欢简约高效，请简阅勿忘初心。
从脑图看，某些功能不是必须的，有不少功能可以自动判断，最终代码约200K比较合适。
Chrome 很早就不支持扩展了，希望能做一个可放于书签栏的JS按钮，可以再简化一些。
希望考虑，谢谢！

**Comment by Kenshin** [comment]
建议使用 简悦 · 轻阅版 http://ksria.com/simpread/#lite 😃

**Comment by lenny20** [comment]
留意到这个版本名称，但Chrome不支持扩展，没法用吧？可否做成书签栏的JS按钮？

**Comment by Kenshin** [comment]
Chrome 什么时候不支持扩展了？
另外，建议看看轻阅版的使用说明。

**Comment by lenny20** [comment]
无法安装和添加，几年前开始的事

**Comment by Kenshin** [comment]
建议：

1. 尽量使用原生 Chrome，而非国产魔改的各种浏览器；
2. 能正常访问 https://chrome.google.com/webstore/category/extensions
3. 可以看看这篇文章，它会教你如何安装 crx 文件 https://sspai.com/post/52767

希望上述内容对你有帮助，我将关闭此 issues 如有问题请重开~  😀
