### ISSUE TITLE
DEVONthink 无法打开简悦导出的 md 文件

### ISSUE THREAD

**Issue by kathleensun** [Kenshin/simpread#4570]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS 版本 12.6**

- 浏览器版本 **Chrome  105.0.5195.125**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 我使用简悦，将网页内容保存到 坚果云 / simread /md 文件夹，然后用 DEVONthink 索引这个文件夹；
   我发现，在 DEVONthink 中索引的 md 文件都无法预览，且打开是空白，转换为其他格式，依然是空白，但是用外部 APP，比如 Typora，都可以正常打开。

**截图**

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202210091109473.png)

**Comment by Kenshin** [comment]
我也在用 dt 并没有遇到你说的情况，也是用的 Indexed 方案，看下图

<img width="792" alt="image" src="https://user-images.githubusercontent.com/81074/194736478-7af83b43-3ae6-4ab5-8649-03c6947f33a5.png">

**Comment by kathleensun** [comment]
我把索引删除，然后重新索引，问题依然存在。

不知道为什么，DEVONthink 无法预览和打开文件，空格预览倒是可以看见文本信息。

倒是也有解决办法，就是用typora转换下格式，就是麻烦了些。

**Comment by Kenshin** [comment]
> 倒是也有解决办法，就是用typora转换下格式，就是麻烦了些。

转换什么格式？

我发给你一个 `.md` 你看看能否正常显示？

[1-本地存储 + 线上获取：我的个人数据库建构路径.txt](https://github.com/Kenshin/simpread/files/9741376/1-.%2B.txt)

另外，你随便发上来无法在 dt 查看的 `.md` （改名为 `.txt` ）我瞧瞧。

**Comment by kathleensun** [comment]
我用  typora 导出为 html，在 dt 里就可以正常预览和阅读了。
[我将笔记转化为知识（和知识转化为内容）的简单过程 - 通过 Ev Chapman - 2022年7月 - 他的.txt](https://github.com/Kenshin/simpread/files/9741450/-.Ev.Chapman.-.2022.7.-.txt)

上面这个文件是在 dt 中无法查看的，我把 .md 修改为 .txt 了。

非常感谢！！

**Comment by kathleensun** [comment]
另外，文件我下载了，把 .txt 修改为 .md，放进索引文件夹，同样无法显示；

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202210092005694.png)

空格键预览可以看到文件内容；

**Comment by Kenshin** [comment]
我明天试试你提供的文件，你既然没法使用我给你的话，感觉还是你的环境或 dt 有问题…

但我确实不知道是什么问题，你的系统和 dt 版本是什么？

另外，简悦也能导出 HTML 的。

**Comment by kathleensun** [comment]
系统是 macOS Monterey, 版本 12.6

dt是最新版 3.8.6

简悦也能导出HTML，我试了，但是带图片的 HTML，文件比较大——其实这也没什么是吧，但是我有点介意，可能是以前硬盘不够大留下的后遗症。

我比较了一下，简悦导出的 html 大概在 4-5M/文件（普通网页），保存为md，通过 typora 转为 html, 文件大小在 60k 左右，当然只比较了几个文件。因为通过简悦保存的网页是我收件箱比较重要的信息来源，且保存在坚果云，我希望这个文件夹不至于太大。

非常感谢你费心回答我，毕竟看起来好像是只有我遇到这个问题，我搜索都没有看到别人问相同的问题。

再次感谢！

**Comment by Kenshin** [comment]
嗨，你提供的文本是没问题的，看下图。（理论上也不应该出问题 😂

<img width="951" alt="image" src="https://user-images.githubusercontent.com/81074/194791863-58280885-58fb-4191-9eac-c5835948c65b.png">

至于你提到的 `.html` 问题应该是你使用了 **离线 HTML** 造成的，这是正常的，因为离线 HTML 会把图片以 `base64` 的方式保存到 HTML 中，用来防止图片 404 的问题。

<img width="472" alt="image" src="https://user-images.githubusercontent.com/81074/194792282-d9821ed6-8d44-4eb5-8eb3-25376c8fe6ba.png">

所以，你可以分别导出这两种 HTML 试试区别。

另外一个提示：因为简悦只包含正文，所以导出的 `.html` 会比其它方式更小。

我先关闭这个 Issues 了，但你可以随时在这里继续跟我讨论。

**Comment by kathleensun** [comment]
好的，非常感谢你的回复。
