### ISSUE TITLE
请问百度文库是否仍然无法适配

### ISSUE THREAD

**Issue by hellozgl** [Kenshin/simpread#4571]
环境：
win10 x64
edge浏览器
出错网页：https://wenku.baidu.com/view/d97005eabaf3f90f76c66137ee06eff9aef849fe.html

这类百度文库，或者页面有限制，非付费用户无法直接右键复制文字的网站，是否仍然无法适配阅读模式呢？

**Comment by Kenshin** [comment]
嗨，百度文库是不会被适配的，凡是涉及到版权类的页面都是如此。

页面有限制的不算这类。
