### ISSUE TITLE
开发者您好，想咨询一个使用问题

### ISSUE THREAD

**Issue by Maxateng** [Kenshin/simpread#4572]
开发者您好，您开发的产品真的非常的戳我[赞同][赞同][赞同]完美符合我对浏览器中该有功能的设想！就是想问一下，导出为PDF到本地，显示的是保存成功，但是在下载管理器中，看不见本地，也搜索不到，那是保存到哪里了呢？

**Comment by Kenshin** [comment]
嗨，我已经在 B 站回复你了。

你是不是使用了同步助手的功能？如果是的话，看看同步助手的导出文件夹（你自己设置的）里面有没有这个文件？

***

另外，简悦十一期间上线了一个新功能：配置库，应该适合你，也就是说用户直接下载简悦官方已经设置好的配置包，然后简单的改动下就行了。

比如，你刚才提到了 PDF，简悦就有专门的针对 [PDF 的配置库](https://github.com/Kenshin/simpread-configs/blob/main/pdf/Getting%20Started.md) 你按照说明设置下基本上就能使用了。

其它剪藏相关的库可以看下 https://github.com/Kenshin/simpread-configs#剪藏版

> 关于配置库的介绍

## 📚 配置库

简悦配置库是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

***

我关闭 Issues 了，有任何配置库的问题可以随时在这里跟我讨论。

**Comment by Kenshin** [comment]
PS：配置库已经发布了，可以直接 [看这里](https://github.com/Kenshin/simpread-configs) 或 [知乎](https://zhuanlan.zhihu.com/p/572115260)

要是喜欢简悦的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨，各位。

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Logseq 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221007_1665118121.png)

> 针对新用户的一步到位的 Logseq 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📦 Logseq 配置库

因为 Logseq 与 Obsidian 在插件 API 的支持度有限，所以并没有轻量级使用方案，根据 Logseq 支持的文件格式区别两种方案。

这两种方案均需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Logseq 中标注，适合 Logseq + 简悦的重度用户。

### 🔌 功能

1️⃣ 支持在 Logseq 中标注

2️⃣ 加入稍后读，自动保存本地快照

3️⃣ 加入标注时，自动将标注内容导入本地快照和 Logseq

4️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Logseq

### 📖 区别

![img](https://imgs.zhubai.love/66078e55f4764b3eaf1a7c1f7cc64c28.png)

### 📙 Org Mode 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@orgmode/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/mdgp9n)

### 📗 Markdown 版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/logseq@md/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/tukkeo)
