### ISSUE TITLE
微信公众号文章请求适配

### ISSUE THREAD

**Issue by xLI4n** [Kenshin/simpread#4574]
https://mp.weixin.qq.com/s?__biz=Mzg3NTczMDU2Mg==&mid=2247483673&idx=1&sn=e89c800d7a801688dfc33f604e57636e&chksm=cf3c42f4f84bcbe20ef9c12bf07ea7b7895009267b7c625ad43202b0729482731f6813001f5c&scene=178&cur_album_id=2206970536067497985#rd

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

公众号已经已经被适配了。

你提交的 URL 属于代码段问题，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
