### ISSUE TITLE
打开同步助手导致本地的simpread_config被覆盖

### ISSUE THREAD

**Issue by iam1maker** [Kenshin/simpread#4576]
3个月左右没有打开过同步助手，期间一直有往稍后读里添加文章，今天打开简悦同步助手导致本地的simpread_config被覆盖，本地simpread_config被覆盖为三个月之前的simpread_config，导致大量数据丢失。

不打开同步助手，就不让使用网页稍后读的阅读模式，打开同步助手如果不先打开坚果云就会把本地数据覆盖掉，这是什么逻辑？

**Comment by Kenshin** [comment]
> 不打开同步助手，就不让使用网页稍后读的阅读模式

没有「这回事」，你遇到的情况是：你打开了自动同步，但没有使用同步助手。

> 今天打开简悦同步助手导致本地的simpread_config被覆盖

在开启自动同步时会有提示，但你可能没有留意提示对应的操作。

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/81074/194842627-1b1eb076-6979-425b-94a8-be554a8a42bb.png">

> 期间一直有往稍后读里添加文章

即便没有自动同步，也可以手动同步。

<img width="900" alt="image" src="https://user-images.githubusercontent.com/81074/194842829-513bed0d-8f65-4c79-a44d-2205609aefe7.png">

**Comment by iam1maker** [comment]
> 没有「这回事」，你遇到的情况是：你打开了自动同步，但没有使用同步助手。
![Snipaste_2022-10-11_00-19-17](https://user-images.githubusercontent.com/34645690/194911497-82fc0554-915c-492a-8b8b-e78c42114449.png)

> 即便没有自动同步，也可以手动同步。
那么不手动同步，那么确实存在配置文件被覆盖的情况对吧，那么在没有同步数据到云盘，在下次打开同步助手存在覆盖风险的时候，要么有相应的功能，要么有相应的提示对吧，而不是数据说丢就丢了。

看了一圈下来，丢数据的情况也不是我这里第一次发生了。

**Comment by Kenshin** [comment]
简悦接下来会做基于同步助手的历史记录，但也只是在同步助手中实现。

相应的提示已经存在了，不过会考虑覆盖配置时的提示说明。
