### ISSUE TITLE
自动进入阅读模式时所有图片显示都特别小

### ISSUE THREAD

**Issue by Burgess-Hu** [Kenshin/simpread#4578]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

你好，最近遇到了一个新问题，在自动进入阅读模式的情况下，所有的图片会变得特别小，退出阅读模式再重新进入后就恢复正常了，很奇怪，比如这样：
![image](https://user-images.githubusercontent.com/22239064/195071476-dc92ee72-caaa-4b69-baaa-2fa5ef04468b.png)
另外，在阅读模式下能否完整显示较长的目录（鼠标经过时显示），有些文章可能看看目录就知道大概的内容，但是目录被折叠后就不太方便了。
感谢开发了这么好的产品！

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

你是不是用了「简/繁体」转换的插件？如果是的话，需要禁用这个插件，这个插件会造成这个情况。

**Comment by Burgess-Hu** [comment]
确实使用了简繁体转换的插件，现在问题完美解决了，开心！
感谢回复的这么快，哈哈。太敬业了，希望简悦越做越好，会一直用下去的！

**Comment by Kenshin** [comment]
这个插件近期会更新，到时候会通知你。

***
喜欢简悦的话，请帮忙五星 + 好评， 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Burgess-Hu** [comment]
好的，期待更新，作为一个老用户，之前早就五星好评过了，哈哈哈！
感谢这么晚的回复，早点休息！

**Comment by Kenshin** [comment]
哈，谢谢老用户的五星。 👍
