### ISSUE TITLE
请问为什么onenote每次都是保存失败，然后重新授权又好了

### ISSUE THREAD

**Issue by jingouwangzi** [Kenshin/simpread#458]
我一般过几天保存一篇文章到onenote，但是会提示保存失败请稍后重试，重试也没用，只能重新对onenote进行授权才行，这是什么问题？

**Comment by Kenshin** [comment]
应该是 Onenote 的授权过期造成的（它的授权时间很短），不过提示的信息似乎有问题，之前会提示授权过期。

我确认下，谢谢反馈。

**Comment by Kenshin** [comment]
是否还存在这个问题？否则我关闭这个 issue 了~

**Comment by jingouwangzi** [comment]
1.1.2，问题仍然存在，“保存失败，请稍后重新再试”，不知道您能不能重复这个问题。

**Comment by Kenshin** [comment]
> 1.1.2，问题仍然存在，“保存失败，请稍后重新再试”，需要重新授权OneNote，不知道您能不能重复这个问题。

嗨，这个问题下个版本会搞定。是因为 Onenote 后台返回的内容变了，导致判断失败。
你可以先在 选项页中重新授权，即可。

这个提示应该是：授权已过期，请重新自动授权（点击会自动重新授权）

**Comment by jingouwangzi** [comment]
好的，多谢！

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，解决了此问题。

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
