### ISSUE TITLE
自动进入阅读模式

### ISSUE THREAD

**Issue by Xm798** [Kenshin/simpread#4583]
- 简悦版本 **2.2.0.520**

**请描述你的问题**

今天想要配置 Obsidian 联动，由于一站式配置文档缺少一些设置细节，导致没办法顺利配置，无奈之下迫不得已使用了配置库。

根据配置库的指引，卸载重装了扩展，Obsidian 正常，但是目前所有网站均会自动进入阅读模式，#2157 和 #2159 解决方案无效。甚至创建 issue 都要进入阅读模式。

尝试了在白名单中加入一些内容，无效；尝试卸载重装，无效；导致网页都没办法正常浏览了，只能禁用扩展。

**Comment by Xm798** [comment]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/48074861/195342164-e6a297ba-429c-4928-8e34-b583f7fa58a5.png">
将 * 加入排除列表，少数派依然会自动进入阅读模式。

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/48074861/195342340-934cf29c-0c27-49be-9d7e-1ec9694cd8b1.png">

**Comment by Xm798** [comment]
> 将 * 加入排除列表，少数派依然会自动进入阅读模式。

微信公众号同样自动进入阅读模式。

配置中选择的是自动进入聚焦模式，但还是只会进入阅读模式。

**Comment by Xm798** [comment]
> 将 * 加入排除列表，少数派依然会自动进入阅读模式。

`*` 似乎不起作用，知乎、Cnblog等等均会自动进入阅读模式。

**Comment by Xm798** [comment]
感谢回复！

1. 关闭【自动进入阅读模式】后可以了
2. “所有网站均会自动进入阅读模式”中“所有网站”本意指的是适配的网站
3. 刚才重新回去看了两遍一站式的文档，发现确实是全面的，当时忽略了“导入到 Obsidian 插件”的配置

另外，

1. 自动进入阅读模式的适配范围是不是有些太大了？例如 Github issues 进入阅读模式后完全无法阅读，感觉并没有进入阅读模式的必要。
2. 能否为选项页加入搜索功能呢？现在找一个选项感觉有些麻烦。

再次感谢！

**Comment by Kenshin** [comment]
> “所有网站均会自动进入阅读模式”中“所有网站”本意指的是适配的网站

并没有这句话... 自动进入阅读模式的功能上写的很清楚了。

<img width="820" alt="image" src="https://user-images.githubusercontent.com/81074/195469800-cc836a6e-c76d-45cb-9902-0e2ef111dacf.png">

> 自动进入阅读模式的适配范围是不是有些太大了？例如 Github issues 进入阅读模式后完全无法阅读

配置库会优化这里。

> 选项页加入搜索功能呢

后续会加入的，但有更好的解决方案。

**Comment by Kenshin** [comment]
嗨，基于你的问题，我优化了配置文件，目前是下面的方案，细节可以看 https://www.yuque.com/kenshin/simpread/wq35mh#noUmI 

每个配置包都是如此。

***

当前配置包没有开启 **如果当前页面为适配站点，自动进入阅读模式** 的功能，如果需要开启请进入选项页 → 阅读模式，按下图所示开启。

![image-20221013091327937](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221013_1665623607.png)

当前配置库仅配置了少数派的白名单，例如进入 https://sspai.com/post/69972 后会自动进入阅读模式，白名单的位置在选项页 → 全局 → 白名单

![image-20221013091625016](https://cdn.jsdelivr.net/gh/23784148/upload-images@main/typora/20221013_1665623785.png)

**Comment by Xm798** [comment]
> 嗨，基于你的问题，我优化了配置文件，目前是下面的方案，细节可以看 https://www.yuque.com/kenshin/simpread/wq35mh#noUmI

十分感谢！

**Comment by Kenshin** [comment]
小事情，关于白名单的用法也包含在这个链接了。

***

要是喜欢简悦的话，请帮忙五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
