### ISSUE TITLE
代码高亮插件不工作了

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#4585]
## 问题描述

CSDN或博客进入阅读模式，代码高亮插件没有显示出来，也没有高亮代码。

> 再次安装也不显示。

## 截图

配置文件：
<img width="250" alt="image" src="https://user-images.githubusercontent.com/11768760/195372248-08e5bd71-04e8-4b9a-87c6-34a92669c9dd.png">

插件不显示：

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/11768760/195372404-336f6ae7-c586-47c2-be8d-c9b001e32368.png">

**Comment by Kenshin** [comment]
嗨，简悦对代码段的识别确实有些问题，因为代码段的高亮方案太多了，很难有统一方案。

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
