### ISSUE TITLE
ob配置 @annote.md内链接无法打开对应html

### ISSUE THREAD

**Issue by LeokuJessica** [Kenshin/simpread#4586]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 macos

- 浏览器版本 edge最新

- 简悦版本 最新

**请描述你的问题**
在清空了稍后读和本地文件的情况下, 
保存新的文章

output文件夹的这篇文章为[3]
Obsidian@simpread的文件夹这篇文章序号为[2]
稍后读保存文章刷新后出现了一篇"本地存储 + 线上获取：我的个人数据库建构路径",在output和Obsidian@simpread中没有出现
当点击本地链接的时候:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/62162557/195474193-5704a601-5562-4dfc-b694-7670e3ec3f38.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/62162557/195473859-12f8e223-7c79-497d-959b-e16c3e981404.png">

![31665621762_ pic](https://user-images.githubusercontent.com/62162557/195474284-bc8c34aa-26e5-48af-9464-eb3225cdd2bd.jpg)

补充:
在原来四篇文章中保存新的一篇,也是打开本地链接的时候显示上一篇的(操作过了 2-3次)

**Comment by LeokuJessica** [comment]
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/62162557/195475050-407e42a6-562c-4925-ba50-07987b53ad8f.png">

**Comment by Kenshin** [comment]
嗨，你是使用的 [Obsidian 配置库](https://www.yuque.com/kenshin/simpread/psugef) 方案吗？

我看到你好像把：

1. Obsidian 库文件夹
2. output 文件夹
3. simpread 同步文件夹

都放到了一起？

如果是话，把这些目录都跟我说下，然后试试：

1. 同步文件夹和导出文件与 Obsidian 分开

    <img width="677" alt="image" src="https://user-images.githubusercontent.com/81074/195479991-5cb1db80-4bcf-488e-8deb-d4a46a05663a.png">

2. Obsidain 不要用太多层级

    <img width="366" alt="image" src="https://user-images.githubusercontent.com/81074/195480093-5fb5e89f-86c1-4a38-9e9a-491798557413.png">

    <img width="288" alt="image" src="https://user-images.githubusercontent.com/81074/195479886-3e33c132-4b1d-444d-9850-de800041c00b.png">

**Comment by Kenshin** [comment]
我测试了下，把简悦的配置文件放到 ob 里面，是没问题的（也不应该有问题才对）

<img width="277" alt="image" src="https://user-images.githubusercontent.com/81074/195492790-22732842-72a7-4b74-89d6-0549d7601641.png">

但一定要保证下面的结构，即 `simpread_config.json` 与 `output` 同级

![image](https://user-images.githubusercontent.com/81074/195492511-64f4170b-2ffa-4bb2-9829-31e99cc074be.png)

1. Obsidian SimpRead Sync config
2. 同步助手 → 同步 → 同步文件夹路径
3. 同步助手 → 导出 →  导出路径

请留意这三者的关系

![SCR-20221013-fta](https://user-images.githubusercontent.com/81074/195492357-83e551a0-e4f3-4e2d-b091-b4443fc6d24f.png)

**Comment by Kenshin** [comment]
PS：我把上面的内容更新到了 https://www.yuque.com/kenshin/simpread/wq35mh#RDfuN
