### ISSUE TITLE
设置了同步助手开启自动同步以后无法进入稍后读和偏好设置了

### ISSUE THREAD

**Issue by hq1998916** [Kenshin/simpread#4587]
![微信截图_20221013112650](https://user-images.githubusercontent.com/107688885/195493047-45e5080e-75d6-43a5-aabe-0f96fb16b0b7.png)
![微信截图_20221013112702](https://user-images.githubusercontent.com/107688885/195493061-3575cbaf-486a-46c1-b09f-91d91ba60af9.png)

我设置了同步助手开启自动同步以后无法进入稍后读和偏好设置了，这是怎么回事？

而且我还想问合辑中不是来自同一篇文章的标注是否可以进行排序呢，比如我现在第一条是来自a文章，第二条来自b文章，我想把第二条排在第一条上面要怎么搞呢？

**Comment by Kenshin** [comment]
> 我设置了同步助手开启自动同步以后无法进入稍后读和偏好设置了，这是怎么回事？

1. 重启同步助手
2. 确定你的同步路径下有 `simpread_config.json` 吗？
3. 退出同步助手，在进入选项页，看看里面的数据都还在吗？

**Comment by hq1998916** [comment]
没有用，并且经常出现莫名其妙我就不是高级账户了导入uid之后恢复高级用户但是我保存的所有东西都不见了，之前手动同步的配置导入但是并不是高级用户。就经常处于用几天突然变成普通用户了导入配置也是普通用户，只有导入uid才能恢复高级用户但是导入了就所有数据都不见了，不懂为啥一定要弄得这么麻烦，我已经丢失了n次保存的东西了！
![image](https://user-images.githubusercontent.com/107688885/195767387-6ff43764-e88d-442c-b9db-64382d60b7e0.png)
如图，我13号的时候是高级用户然后手动同步在坚果云里的配置，今天莫名就变普通用户了再导入这个配置还是普通用户，只能选择导入最原始的内涵uid的那个文件才可以变高级用户。

**Comment by hq1998916** [comment]
搞得一个登录同步这种很基本的功能都很麻烦，就这个莫名其妙就同一台设备同个浏览器莫名其妙就昨天打开高级用户今天就变普通用户，这种情况都遇到三回了！！！ 每次都得回退到初始才可以，心累了。用这个软件得看一堆教程文档啥的，就不能搞简单一点吗

**Comment by Kenshin** [comment]
> 只有导入uid才能恢复高级用户

> 今天莫名就变普通用户了再导入这个配置还是普通用户

是你的操作有误，如果你的 UID 没有变化只是「掉了高级账户的」话，使用 https://www.yuque.com/kenshin/simpread/sw4m21 就能恢复权限。并不需要重新导入数据，重新导入数据的话，当然会出现丢失的情况。
