### ISSUE TITLE
AA 快捷键无法进入阅读模式，禁用/重开简悦 Chrome 插件可以恢复，但一会儿又失效

### ISSUE THREAD

**Issue by TYZRPVX** [Kenshin/simpread#4588]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/7645818/195495732-9c7ce411-459a-4e5c-9044-01f3e57eda03.png">

* 快捷键未自定义过
* 禁用 vimium 仍复现，应该不是快捷键冲突

**Comment by Kenshin** [comment]
嗨，试试下面的方案。

1. **隐身模式下仅使用简悦的方式** ，确保不会别其它扩展干扰。
2. 更改其它快捷键

**Comment by TYZRPVX** [comment]
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/7645818/195565181-78ef1f76-5500-41f2-b78f-6f194574e3f1.png">

1. 隐身仅开启简悦，同样有问题
2. AS AA 都不可以，修改快捷键也有问题

**Comment by Kenshin** [comment]
看看这里的设置。

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/81074/195597353-cbaf4152-09fc-4699-aa47-98e50129196d.png">

另外，导出配置，然后重新安装简悦，看看有没有问题？

**Comment by Kenshin** [comment]
神奇的问题… 😂

我也「学」了一招
