### ISSUE TITLE
导入 md + asset 到Obsidian，保存失败

### ISSUE THREAD

**Issue by liangfeng093** [Kenshin/simpread#4589]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows **

- 浏览器版本 **Chrome 106.0.5249.103**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <https://sspai.com/post/76153>

**请描述你的问题**

> 导入 md + asset 到Obsidian，保存失败。
> 我试了好几个网站，都不行。是不是配置有问题？
> 保存全文到Obsidian是没有问题的

**截图**
![image](https://user-images.githubusercontent.com/25739714/195496539-ae42b1db-1d2d-4622-bf1e-129158c07181.png)

![image](https://user-images.githubusercontent.com/25739714/195496644-cc7aedbf-5519-4df5-9007-623e2d5ec9b5.png)

**Comment by Kenshin** [comment]
嗨，你可以直接使用简悦提供 [资源库](https://github.com/Kenshin/simpread/discussions/4531#discussioncomment-3844881)，适合你的方案：

1.  https://github.com/Kenshin/simpread-configs/blob/main/obsidian%40localrestapi/Getting%20Started.md
2. https://github.com/Kenshin/simpread-configs/blob/main/obsidian%40sync/Getting%20Started.md
3. https://github.com/Kenshin/simpread-configs/blob/main/assets/Getting%20Started.md

如果还需要使用 Obsidian 标注的话，就试试前两个方案。
