### ISSUE TITLE
定制化md模板无效

### ISSUE THREAD

**Issue by lin0kin** [Kenshin/simpread#4591]
- 操作系统 Windows 10 

- Edge 106.0.1370.42

- 简悦版本 2.2.0.520，edge 商店下载

- 以这个地址为例<https://kb.simpread.pro/#/page/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA%E5%8A%9F%E8%83%BD>

定制导出md模板无效。没有使用同步助手，右键导出md到剪贴板或者本地md文件，都没有使用设置的模板

**截图**

设置了模板

![image](https://user-images.githubusercontent.com/30078096/195513467-9215208e-5df6-414a-ba27-bec33d93e1ab.png)

导入ob后

![image](https://user-images.githubusercontent.com/30078096/195513721-4217b888-ec7d-4720-be81-7e685fd1afab.png)

**Comment by Kenshin** [comment]
嗨，这里有个新方案，应该会适合你，有任何问题，可以随时在这里继续讨论。

***

简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。

细节请看下面，几分钟就能配置成完成。

***

![img](https://imgs.zhubai.love/c626678ff6b64dd1ac9dfdae6cf6d188.png)

> 针对新用户的一步到位的 Obsdian 配置库。

## 🗂 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

## 💡 特点

用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。

## 💁‍♂️ 受众

新用户或者不想使用手动配置的用户。

## 📝 如何使用

1️⃣ 下载

2️⃣ 修改为自己的 UID

3️⃣ 将必要的文件夹复制粘贴到相应位置

✅ Done！

## 📚 Obsidian 配置库

## 📝 特点

1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian

2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian

3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian

4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注

## 📖 区别

![img](https://imgs.zhubai.love/f4a51d8e8fb4401281b07f82bf0bc7d1.png)

## 📘 极速版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)

不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。

## 📙 基础版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。

## 📗 高级版

🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)

需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

**Comment by lin0kin** [comment]
> 嗨，这里有个新方案，应该会适合你，有任何问题，可以随时在这里继续讨论。
> 
> 简悦官方针对新用户或不喜欢配置的用户，发布了一个新功能：**Obsidan 配置库**。
> 
> 细节请看下面，几分钟就能配置成完成。
> 
> ![img](https://camo.githubusercontent.com/093ac4351ff1633e5a52a8277978ec67ab9921093f65c019c6231cfb25cb8719/68747470733a2f2f696d67732e7a68756261692e6c6f76652f63363236363738666636623634646431616339646664616536636636643138382e706e67)
> 
> > 针对新用户的一步到位的 Obsdian 配置库。
> 
> ## 🗂 配置库
> [简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。
> 
> ## 💡 特点
> 用户仅需要下载对应的配置库，修改里面的 UID 为自己的高级账户 UID，即可实现简悦的各种高级操作。
> 
> ## 💁‍♂️ 受众
> 新用户或者不想使用手动配置的用户。
> 
> ## 📝 如何使用
> 1️⃣ 下载
> 
> 2️⃣ 修改为自己的 UID
> 
> 3️⃣ 将必要的文件夹复制粘贴到相应位置
> 
> ✅ Done！
> 
> ## 📚 Obsidian 配置库
> ## 📝 特点
> 1️⃣ 加入稍后读，自动将本地快照和 Markdown 导入到 Obsidian
> 
> 2️⃣ 加入标注时，自动将标注内容导入本地快照和 Obsidian
> 
> 3️⃣ 改变稍后读或标注的元数据时，自动将改动的内容保存到本地快照和 Obsidian
> 
> 4️⃣ 在 Obsidian 中直接内置好了简悦的标注系统，可直接在 Obsidian 实现标注
> 
> ## 📖 区别
> ![img](https://camo.githubusercontent.com/56dd1b1346d73b07f4ef51c044b2cffba62654a0e9fc6facde3165f2b7a24605/68747470733a2f2f696d67732e7a68756261692e6c6f76652f66346135316438653866623434303132383162303766383262663062633764312e706e67)
> 
> ## 📘 极速版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@little/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/xkuecp)
> 
> 不需要同步助手，无任何配置，支持 Markdown 形式的快照，自动同步标注，适合 Obsidain + 简悦的尝鲜用户。
> 
> ## 📙 基础版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@localrestapi/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/cg33gh)
> 
> 需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，适合 Obsidain + 简悦的轻量级用户。
> 
> ## 📗 高级版
> 🔗 [Github](https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md) | [语雀](https://www.yuque.com/kenshin/simpread/wq35mh)
> 
> 需要同步助手，几乎无任何配置，支持本地快照，自动同步标注，可在 Obsidian 中标注，适合 Obsidain + 简悦的重度用户。

因为同时再用多个ob 库和legseq, 需要使用复制md到剪切板的功能, 即是使用配置库, 右键导出好像也不能应用模板

**Comment by Kenshin** [comment]
**右键导出**是指什么？

另外，刚才说了，目前不建议使用 Markdown 1.0（也就是你提到的模板方案了，有很多弊端），配置库里面的是 2.0 方案。

**Comment by lin0kin** [comment]
> **右键导出**是指什么？
> 
> 另外，刚才说了，目前不建议使用 Markdown 1.0（也就是你提到的模板方案了，有很多弊端），配置库里面的是 2.0 方案。

说错了， 是复制 markdown 到剪贴板。

并没有在使用稍后读，偶尔使用标注。2.0 方案是指markdown模板辅助增强吗？好像只对这两个里面起效。

**Comment by Kenshin** [comment]
> 2.0 方案是指markdown模板辅助增强吗

是的。目前这个方案只能在阅读模式下使用，暂时无法在稍后读中使用。

另外，我明天再详细看下你的问题~

**Comment by lin0kin** [comment]
> > 2.0 方案是指markdown模板辅助增强吗
> 
> 是的。目前这个方案只能在阅读模式下使用，暂时无法在稍后读中使用。
> 
> 另外，我明天再详细看下你的问题~

十分感谢，主要就是阅读界面使用复制markdown到剪贴板时，导出的markdown也想能使用模板

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/1851 提到的方案。

**Comment by lin0kin** [comment]
> 嗨，试试 #1851 提到的方案。

谢谢回复. 一开始就是按照这个配置的.
昨天晚上试了从chrome store 下载插件, 还有换用chrome 浏览器, 都无法应用模板, 也不能导出标注

**Comment by Kenshin** [comment]
emmmm 导出你的配置文件，用文本编辑器打开它，把你的配置文件中 `"uid"` 对应的内容删除，然后改名为 `.txt` 发上来，我瞧瞧。
