### ISSUE TITLE
代码中的注释怎么无法保留下来

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4596]
### Discussed in https://github.com/Kenshin/simpread/discussions/4595

<div type='discussions-op-text'>

<sup>Originally posted by **liang31555** October 13, 2022</sup>
代码中的注释无法保留下来，比如这个地址：[https://subingwen.cn/qt/qt-basetype/#6-2-QTime](url)</div>

**Comment by Kenshin** [comment]
@liang31555

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by liang31555** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
