### ISSUE TITLE
在知乎内使用阅读模式只会高亮第一个答案

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#46]
在知乎内使用阅读模式只会高亮第一个答案，其他答案不能高亮。

建议高亮整个答案区域。

#20

**Comment by Kenshin** [comment]
感谢反馈，下个版本会改善这个问题。
参考 #20

**Comment by Kenshin** [comment]
@jinyu121 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

知乎类已经支持更丰富的论坛类页面，此 issues 将关闭~
