### ISSUE TITLE
觅道文档验证提示失败

### ISSUE THREAD

**Issue by Yimien** [Kenshin/simpread#4603]
今天下午时我在一台电脑上尝试了验证是通过，也可以正常地将文档导出，但是晚上回到家时，因为忘记同步配置文件，于是尝试再次配置，但是却一直提示失败。
![image](https://user-images.githubusercontent.com/42413155/195862154-9616bb49-cb90-4ef7-9676-e89d2bd5c156.png)
![image](https://user-images.githubusercontent.com/42413155/195862395-38fa1abe-00dc-4389-b9fe-65d8926162db.png)

已经按提示创建了名为SimpRead的文集，里面的文章是用官方插件剪藏，因此可以判断站点和token没有问题
![image](https://user-images.githubusercontent.com/42413155/195862716-e0f12f87-5953-469b-8bee-65c1d23d3c8c.png)

**Comment by Kenshin** [comment]
emmmm

是不是安装简悦之后没开权限？

**Comment by Yimien** [comment]
呃，请问是需要开什么权限？🤔

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/discussions/1567

但大概率跟你的问题无关...

建议还是重新安装简悦然后再配置下，试试。

另外，我也不确定是否是 觅道文档 抽风导致的 😂

**Comment by Yimien** [comment]
授权应该是开着的
![image](https://user-images.githubusercontent.com/42413155/195973960-f48ff9d9-7dd6-42d3-af7f-059cf9a381f1.png)
![image](https://user-images.githubusercontent.com/42413155/195973988-61414ccb-2dcc-4e0d-a068-ef2ce7586d00.png)

也已经重装了，是可以验证通过的，觅道文档是布在家里的NAS上，嫌麻烦直接用ddnsto外网访问的，在本地用接口调试工具可以请求成功，用在线工具访问需要验证，不知道是不是这个原因，但是用觅道官方的插件就可以剪藏，用简悦就验证失败，而且在另一台电脑简悦就能验证通过，完全搞不懂😂

**Comment by Kenshin** [comment]
> 用在线工具访问需要验证，不知道是不是这个原因

有可能，你可以把访问的 URL 验证给我，我看看。

**Comment by Yimien** [comment]
我刚准备发链接，然后随手试了下，竟然验证通过了，因为是新用户，所以我又用旧用户试了下，可以验证通过，但导出时会提示失败，我干脆把旧用户删除，重新建了个同名的，结果这次验证通过，也可以保存了🤣

**Comment by Kenshin** [comment]
好吧，我也不知道怎么就可以了 😂 忒不容易了... 

我关闭这个 Issues 了~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
