### ISSUE TITLE
Mindmap下载markdown格式文件问题求助，谢谢。

### ISSUE THREAD

**Issue by numberking2022** [Kenshin/simpread#4605]
Mindmap选项-->下载，下载文件扩展名是txt（导入到XMind不能正确展示导图的好像），请问markdown格式文件在哪里下载呢？谢谢啦

**Comment by Kenshin** [comment]
嗨，估计是你用了某些下载类的扩展造成的，简悦通过此方式导出的就是 `.md` 格式。

你可以在 **隐身模式下仅使用简悦的方式** 试试
