### ISSUE TITLE
标注的疑问

### ISSUE THREAD

**Issue by starrycrown** [Kenshin/simpread#4606]
AA，进入阅读模式后，进行标注时，后一条会取代前一条，而且不显示标注颜色，只能先将文章放入稍后读，在稍后读的后台进入阅读模式才能实现正常的标注。

**Comment by Kenshin** [comment]
哈哈 😂

当然不可能出现这个情况了…

建议录屏给我或者在进入 https://sspai.com/post/69972 隐身模式下，仅启用简悦试试。

**Comment by starrycrown** [comment]
泪目，live editor的冲突，我这不知道为啥没有提示0.0

**Comment by Kenshin** [comment]
1. 在没有标注的前提下，使用 Live Editor 修改后并退出后可以标注，但再此进入阅读模式后就没法显示标注了，因为进入的内容还是 `le` 修改前的内容。

2. 在有标注的前提下，不建议使用 `le` 因为会破坏上下文结构导致标注显示失败。

所以，你需要：

1. 在稍后读中继续标注（前提是需要使用知识库方案，教程可以看 https://www.yuque.com/kenshin/simpread/wkswh7
2. 在 Obsidian 中标注（如果对这种方式感兴趣的话，可以看看 https://www.yuque.com/kenshin/simpread/wq35mh 提供的方案。

**Comment by starrycrown** [comment]
好的，非常感谢，学习使我快乐......

**Comment by Kenshin** [comment]
方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by starrycrown** [comment]
已经10星好评了

**Comment by Kenshin** [comment]
😁 👍

PS：不小心点错了…我再 Close 一次。
