### ISSUE TITLE
公众号全文导入到Ob时标题乱码

### ISSUE THREAD

**Issue by h-dengmin** [Kenshin/simpread#4608]
利用 Chrome 浏览器简悦端的 “导入到 Obsidian 插件“ 与 OB 端的 “SimpRead Sync插件” 联动时（均已更新到了最新版本），将微信公众号文章全文导入到Ob会出现标题乱码，示例如下图所示：

![image](https://user-images.githubusercontent.com/54652741/196088008-206954cc-026a-4b10-83b5-25877ef03b8e.png)

同时，插件触发器的图标也有所改变。如下图所示：

![image](https://user-images.githubusercontent.com/54652741/196089019-8c98eb1e-9ccc-4eb3-ad82-637ca30279ca.png)

猜测是对公众号文章的标题读取出现了问题。

**Comment by Kenshin** [comment]
嗨，把出问题的 URL 给我瞧瞧。

**Comment by h-dengmin** [comment]
严格意义上来说也不能算是乱码，就是标题里多了一些 TAB 和换行符（第一张截图）。
我试过两三个公众号文章，都有相同的问题。以下给出第一个截图的 URL：
https://mp.weixin.qq.com/s/9ChYvLJoJGjKA5ffBMT17g

PS：这个问题是在更新到obsidian v1.0 之后出现的。

**Comment by Kenshin** [comment]
我知道是什么问题了，标题里面含有非法字符造成的

<img width="809" alt="image" src="https://user-images.githubusercontent.com/81074/196095213-4ae53ea0-7d0a-4951-bee9-8b4c08344d6c.png">

但奇怪的是，如果进入了阅读模式后，会自动优化标题，去掉这些，不应该存在这个问题才对，同时导入到 Obsidian 的内容也就没问题了。

<img width="786" alt="image" src="https://user-images.githubusercontent.com/81074/196095331-c871b4ab-4668-420f-a401-8310ef0f6c46.png">

***

你的插件都是什么时候安装的？留存好你的配置文件，然后通过插件管理器重新安装，但要留意下图的说明

<img width="506" alt="image" src="https://user-images.githubusercontent.com/81074/196095639-e7081e2e-a3dd-41ff-a87a-2d1b7fd08474.png">

如果还不行的话，使用插件管理器安装题图和 Safari 样式这两个插件。（**注意：按照插件管理器正常的方式安装**）

还是不行的话，把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4608

然后回复我，我看看。

**Comment by h-dengmin** [comment]
用第二种方法解决了，感谢！！

**Comment by Kenshin** [comment]
也就是安装了「题图和 Safari 样式」这两个插件吗？

**Comment by h-dengmin** [comment]
对的

**Comment by Kenshin** [comment]
嗨，你之前安装过 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 吗？

<img width="281" alt="image" src="https://user-images.githubusercontent.com/81074/196153059-c91e0094-538b-4e05-a9be-82e6f8994014.png">

**Comment by Kenshin** [comment]
okay 解决就好。

其实你感兴趣的话，可以尝试下 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-3846217 提供的配置包，里面自动包含了刚才提到的这些插件。

或者资源库里面其它的方案 https://www.yuque.com/kenshin/simpread/ds8zk0

**Comment by h-dengmin** [comment]
好的，非常感谢！👏👏👏

**Comment by Kenshin** [comment]
哈，方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by h-dengmin** [comment]
之前已经🌟过啦

**Comment by Kenshin** [comment]
哈，谢谢评分~
