### ISSUE TITLE
增加对思源笔记的联动，

### ISSUE THREAD

**Issue by Lin-dreamer** [Kenshin/simpread#4609]
### obsidian和简悦的联动的效果很好
[高级版 · 语雀 (yuque.com)](https://www.yuque.com/kenshin/simpread/wq35mh)obsidian和简悦的联动，可以实现下面三个功能：
	1. 在阅读模式下加入稍后读，会自动生成本地快照  
	2. 在阅读模式下标注时，标注内容会自动同步到 Obsidian（轻量级使用简悦 + Obsidan）  
	3. 在 Obsidian 中也可以内嵌简悦的标注，同时也自动更新到 Obsidian 内的标注文档中（重度使用简悦 + Obsidan）

### 思源笔记实现上述效果的可能
有没有可能思源笔记也实现上面的效果，思源笔记的文件是`.sy`后缀，本质是`json`格式
		- 
![思源笔记的文件格式是json](https://user-images.githubusercontent.com/59968140/196089926-30e2f8e2-8d29-4e84-bfe6-2762d71e0e28.png)

[siyuan/API_zh_CN.md at master · siyuan-note/siyuan (github.com)](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md)这个是思源笔记的API

**Comment by Kenshin** [comment]
收到，谢谢提供 API，搞定后我会在这里通知你~

**Comment by yaleimeng** [comment]
同期待中。

**Comment by Kenshin** [comment]
嗨，各位~

久等了，预计周末在这里发测试版。

我会把思源相关的功能都整理到 https://github.com/Kenshin/simpread/issues/5555 同时，有一些关于思源笔记功能的需求调研，要是有可能的话，请 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1563812818 并回复下你们的使用方式。

**Comment by Kenshin** [comment]
嗨，各位。

导入到思源笔记的插件已经可以内测了，如何使用以及讨论请前往 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566016251

**Comment by Kenshin** [comment]
![Siyuan](https://github.com/Kenshin/simpread/assets/81074/a8f839b4-90e5-4fbe-8ae9-da73b48c888c)

嗨，各位。

导入到思源笔记的插件已发布。

### 下载地址

https://simpread.ksria.cn/plugins/details/XxuF7bPTbo

### 功能

- 定制思源笔记地址（适用于 Docker 用户）

- 新建笔记本（留空则新建 SimpRead 名称的笔记本）

- 查看并选择任意笔记本
   
- 自定义导入路径

- [思源图库](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- [assets 定制](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025979) 包括：`{{title}}` 与 `{{date}}`

- [将阅读模式的图片转换为思源图床](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- 导入全文到思源笔记

- 快捷键

- [自动化](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025982)

- 在导入前可选择任意笔记本或路径

### 如何安装

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

### 注意事项

如果你使用了 Docker 版，并且域名不是 `localhost` 的话，可能会有问题。


***

我关闭这个 issues 了，但有任何使用疑问均可继续再此讨论。 😄
