### ISSUE TITLE
阅读模式下，文章的标点符号丢失

### ISSUE THREAD

**Issue by smallrock** [Kenshin/simpread#461]
比如个地址：
https://juejin.im/post/5a0a39c25188254d2b6da2a3

![image](https://user-images.githubusercontent.com/5387059/54730568-a2e37680-4bc4-11e9-9f80-824b0a9aa435.png)

版本：1.1.2

**Comment by Kenshin** [comment]
我没有遇到这个问题... 下图

![image](https://user-images.githubusercontent.com/81074/54730903-69136f80-4bc6-11e9-809d-366c7403d2cd.png)

**Comment by smallrock** [comment]
恩 清空本地配置后就好了，应该是装了插件中间的某个插件引起的

**Comment by Kenshin** [comment]
搞定就好。

你说的「清空本地配置」是指简悦的吗？

**Comment by smallrock** [comment]
是的

**Comment by Kenshin** [comment]
okay 理论上应该不会出现你说的情况，因为简悦的这些插件我也都安装了。我先关闭这个 issues 如果再重现的话，请 Reopen 即可。

**Comment by Kenshin** [comment]
嗨，不好意思。

我找到 `标点符号` 丢失的问题原因了，是使用了 [汉字标准格式](https://simpread.ksria.cn/plugins/details/IZ7nDPIJr5) 造成的问题。

现在已修复此问题，你可以 [删除 /更新](http://ksria.com/simpread/docs/#/插件系统 ) 这个插件。

**Comment by Kenshin** [comment]
嗨，不好意思。

我找到 `标点符号` 丢失的问题原因了，是使用了 [汉字标准格式](https://simpread.ksria.cn/plugins/details/IZ7nDPIJr5) 造成的问题。

现在已修复此问题，你可以 [删除 /更新](http://ksria.com/simpread/docs/#/插件系统 ) 这个插件。
