### ISSUE TITLE
与 Obsidian 联动存在的一系列问题

### ISSUE THREAD

**Issue by Xm798** [Kenshin/simpread#4612]
## 版本信息

- 操作系统 **MacOS**

- 浏览器版本 **Chrome 106.0.5249.119**

- 简悦版本 **2.2.0.520**

### 问题1：SimpRead Unreader Sync 插件设置文件夹无效

在插件中设置 Base folder 为 SimpRead-Auto，然后将文章使用 dd 加入稍后读，发现被加入到了 SimpRead 文件夹中。

<img width="692" alt="image" src="https://user-images.githubusercontent.com/48074861/196328587-fbd55529-8b4d-4cec-bfd0-c7fc34d93868.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/48074861/196328292-2b08e6f8-0765-4292-9b27-cb5ba58c7046.png">

在阅读模式下进行标注，发现文章也被加入到了 SimpRead 文件夹中。

<img width="481" alt="image" src="https://user-images.githubusercontent.com/48074861/196328531-d7f8b70a-c7b5-4b21-a10a-2c99a7b4204c.png">

### 问题2：自动化辅助增强 配置无法生效

https://github.com/Kenshin/simpread/issues/4483#issuecomment-1281769856

### 问题3：`@annote` 格式不会更新标注

阅读模式下，更新标注，手动使用快捷键 obuu 更新，提示保存成功，但事实上并没有。

<img width="2049" alt="image" src="https://user-images.githubusercontent.com/48074861/196329938-ff724c36-94b9-4b2d-a164-3795a22f202f.png">

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/48074861/196329977-e033cb09-e97e-44d3-8897-e27a30d18d23.png">

### 问题4：Ob 模板不生效

```
---
title: "{{title}}"
alias: 
<% if ( unread.note && unread.title != unread.note ) { %>  - "{{note}}"
<% } %>  - "{{title}}"
created-date: {{create|yyyy-mm-dd'T'HH:MM:sso}}
type: Simpread
<% if (unread.img) { %>banner: "<%- unread.img %> "
banner_icon: 🔖
<% } -%>
tag: {{ |tag| | }}
idx: {{idx}}
---

# {{title}}
<%
let ifURI = "http://localhost:7026/unread/"+unread.idx
%>
> [!example]- [🧷内部链接](<<%= ifURI %>>) [🌐外部链接](<<%= unread.url %>>)    
> URI:: [🧷](<<%= ifURI %>>) [🌐](<<%= unread.url %>>) 
> intURI:: [🧷内部链接](<{{int_uri}}>)

%%
> [!example]+ **Comments**  
> ```dataview
> TABLE 
>     WITHOUT ID
>     link(Source, dateformat(date(Source), "yyyy-MM-dd")) as Date___, 
>     regexreplace(rows.Comments,"^@@\[\[.+?\]\]\s","") as "Comments"
> FROM "journals"
> WHERE  contains(cmnt, this.file.name)
> FLATTEN cmnt as Comments
> WHERE contains(Comments, this.file.name)
> GROUP BY file.link as Source
> SORT rows.file.day desc
> ```
>  **Description**:: {{desc}}
%%

> [!md] Metadata  
> **标题**:: [{{title}}]({{url}})  
> **日期**:: [[{{create|yyyy-mm-dd}}]]  
<% if ( unread.annotations && unread.annotations.length > 0 ) { %>
## Annotations

{{annotations}}
<% } -%>
<% if ( unread.tags && unread.tags.includes('Highlights') ) { %>
![[<%% tp.file.title %>_mentions#Highlight Mentions]]
<% } -%>
<% if ( unread.refs ) { %>
## Reference   
{{-|refs}}  
<% } %> 
```

```
---
title: "{{title}}"
alias: 
<% if ( unread.note && unread.title != unread.note ) { %>  - "{{note}}"
<% } %>  - "{{title}}"
created-date: {{create|yyyy-mm-dd'T'HH:MM:sso}}
type: Simpread
<% if (unread.img) { %>banner: "<%- unread.img %> "
banner_icon: 🔖
<% } -%>
tag: {{ |tag| | }}
idx: {{idx}}
---

# {{title}}
<%
let ifURI = "http://localhost:7026/unread/"+unread.idx
%>
> [!example]- [🧷内部链接](<<%= ifURI %>>) [🌐外部链接](<<%= unread.url %>>)    
> URI:: [🧷](<<%= ifURI %>>) [🌐](<<%= unread.url %>>) 
> intURI:: [🧷内部链接](<{{int_uri}}>)

%%
> [!example]+ **Comments**  
> ```dataview
> TABLE 
>     WITHOUT ID
>     link(Source, dateformat(date(Source), "yyyy-MM-dd")) as Date___, 
>     regexreplace(rows.Comments,"^@@\[\[.+?\]\]\s","") as "Comments"
> FROM "journals"
> WHERE  contains(cmnt, this.file.name)
> FLATTEN cmnt as Comments
> WHERE contains(Comments, this.file.name)
> GROUP BY file.link as Source
> SORT rows.file.day desc
> ```
>  **Description**:: {{desc}}
%%

> [!md] Metadata  
> **标题**:: [{{title}}]({{url}})  
> **日期**:: [[{{create|yyyy-mm-dd}}]]  
<% if ( unread.annotations && unread.annotations.length > 0 ) { %>
## Annotations

{{annotations}}
<% } -%>
<% if ( unread.tags && unread.tags.includes('Highlights') ) { %>
![[<%% tp.file.title %>_mentions#Highlight Mentions]]
<% } -%>
<% if ( unread.refs ) { %>
## Reference   
{{-|refs}}  
<% } %> 
```

加入到库中的实际效果：

<img width="763" alt="image" src="https://user-images.githubusercontent.com/48074861/196330171-0de0a332-c90c-41f8-8fe7-f23ebc5700ce.png">

<img width="759" alt="image" src="https://user-images.githubusercontent.com/48074861/196330183-64f21769-cfda-4903-955e-488ee99d9e3c.png">

**Comment by Kenshin** [comment]
嗨，你可以先使用 https://github.com/Kenshin/simpread/issues/4483#issuecomment-1281773658 提到的配置包，先确保配置正确。

然后在将 Obsidian 端的内容手动跟你的已存在的库合并。

注意：

1. 确保只开一个存在 SimpRead Sync 的库（多个 simperad sync 插件会导致端口冲突）
2. 暂时先只用一级目录

**Comment by Xm798** [comment]
就是使用的配置库，刚配置好的时候没问题，今天出现了问题。

**Comment by Xm798** [comment]
> 暂时先只用一级目录

我理解的 SimpRead-Auto 就是一级目录，是我理解有问题吗？是说一级目录是库的根目录？

**Comment by Kenshin** [comment]
我看了下你的问题，大多都是配置库已经存在的功能，并没有添加新的插件。

所以，有个建议：

1. **务必先留存好你的目前的数据**。（简悦 + Obsidian）
2. 再按照配置库的方案重新来一次（因为有了第一次的经验，用不了几分钟）
3. 确保步骤2没问题的话，再按照你的个性化定制设置。（文件夹名称、模板等）

另外，

1. 你提到的模板需要在两边同时设置。
2. `SimpRead-Auto` 就是一级目录，没错。

**Comment by Kenshin** [comment]
嗨，在这个 Issues 上面讨论吧。

https://user-images.githubusercontent.com/48074861/196334377-915b9105-a4e6-4135-8855-472d905be1ca.mp4

还是先以我刚才说的测试方案为准。

PS：视频我看了，现象确实如你所说。

**Comment by Xm798** [comment]
重新配置后确实又可以了，但每次出问题都要重新配置着实是有些麻烦。

暂时先用着，希望不要再出问题了TAT

**Comment by Kenshin** [comment]
> 但每次出问题都要重新配置着实是有些麻烦。

当然不需要每次配置 😂... 目前使用这套方案的用户除了你还没有出问题的呢。

再出错的话，留意下出错前你做了什么操作。
