### ISSUE TITLE
为什么频繁出现“当前未获取任何正文，请重新选取”的提示？

### ISSUE THREAD

**Issue by AlmostFamous1992** [Kenshin/simpread#4613]
打开很多网站后都会在右上角出现这个提示，我尝试关闭自动进入聚焦模式等功能，依然如此
随便举个例子，比如这个：https://www.163.com/news/article/HJV1T3ED000189FH.html?clickfrom=w_yw
请问如何关闭这个提示？
![image](https://user-images.githubusercontent.com/37547449/196337824-47786ffe-da4e-4c08-b2d3-faf60aab3514.png)

**Comment by Kenshin** [comment]
你给出的链接进入阅读模式后，没有看到这个提示

<img width="977" alt="image" src="https://user-images.githubusercontent.com/81074/196342488-e1c1d60c-10db-436e-b915-62fe78f9f9b5.png">

这个提示只是一个提示用，一般来说有两种情况发生：

1. 确实没有获取到正文
2. 正文的内容很少（比如 20 个字以内）

暂时没有关闭它的功能，但近期会推出一个插件来关闭。

一般来说，很难发生频繁的提示的情况，除非你每次看到的内容都是上面两种情况之一。

**Comment by AlmostFamous1992** [comment]
我是频繁地出现这个提示，所以不知道是什么原因。而且不需要进入阅读模式，是正常浏览网页的时候出现的

**Comment by Kenshin** [comment]
emmm 是不是其它扩展造成的干扰？

**隐身模式下仅使用简悦的方式** 看看能否稳定复现？

**Comment by AlmostFamous1992** [comment]
我试了下，在隐身模式下也可以复现

**Comment by Kenshin** [comment]
emmm

主要是你提供的信息太少了，我没法判断...

你是用 Edge 吗？Edge 可以安装两个简悦（是不是这个问题？）

你用了同步助手了吗？建议考虑重置下配置环境。

1. 留存好你的数据（导出配置文件到本地）
2. 选项页 → 账户 → 复制你的 UID
3. 重新安装简悦
4. 使用 https://www.yuque.com/kenshin/simpread/pkq3d1 重新设置你的高级账户

然后在不使用同步助手的前提下，使用（或安装插件）

**Comment by AlmostFamous1992** [comment]
我用的是修改版的Chrome，也没有使用同步助手等。我尝试重新安装插件，然后打开自动进入聚焦模式，并关闭启用手动聚焦模式。就能稳定复现这个问题
![image](https://user-images.githubusercontent.com/37547449/197399707-9015e74a-f1e5-448a-94a3-89cbb17d7d82.png)
