### ISSUE TITLE
关于加入 Pocket 后自动保存到简悦的稍后读的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4614]
您好，遇到一个奇怪的问题，昨天配置完一切正常，今天跟另一台电脑同步配置全乱了，重置后再配置zapier无法发送到随后读，zapier一切正常返回201，不报错。尝试删除重建也不行，但是同时创建ios捷径，使用一切正常，可以自动加入随后读

_Originally posted by @trusun in https://github.com/Kenshin/simpread/discussions/3024#discussioncomment-3905031_

**Comment by Kenshin** [comment]
@trusun

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

如果捷径正常的话，则说明 API 没有问题。

zapier 可能有些延迟，一般来说重新配置后也不会出现问题，你可以稍晚在测试下。

**Comment by trusun** [comment]
非常感谢你的回复，已经正常了，是zapier的问题，昨天下午怎么配置都不行，晚上再试就正常了，谢谢你！

**Comment by Kenshin** [comment]
小事情，我关闭这个 Issues 了。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
另外，我看到你的动手能力不错，欢迎加入我刚刚建立的 wx 群

![image](https://user-images.githubusercontent.com/81074/196584759-5bf41dd2-193e-4e93-8ee9-921ba0714df2.png)

以及 Telegram 群（里面已经有 2K+ 的小伙伴）

![image](https://user-images.githubusercontent.com/81074/196584825-986c986c-d609-4e25-8543-0efb11dcfbfa.png)

**Comment by trusun** [comment]
已五星好评，telegram错过了入群验证消息，不允许再加了🤦🏽‍♂️，方便的话可以邀请一下吗？非常感谢 @trusun

**Comment by Kenshin** [comment]
嗨，你可以重新加一次了，另外也可以订阅 https://t.me/simpread 这个 Channel

**Comment by trusun** [comment]
Ok了，谢谢！

**Comment by Kenshin** [comment]
小事情~
