### ISSUE TITLE
从知乎导入到OBSIDIAN时，公式之后紧跟一个该公式的代码

### ISSUE THREAD

**Issue by glareheaven** [Kenshin/simpread#4615]
将知乎内的科研类文章导入OBSIDIAN时，除正常显示的公式之外，在其之后紧跟一个该公式的代码（似乎是latex格式），几乎每个公式都是如此，导致文章看起来非常奇怪，难以正常阅读，麻烦尽快修正下（在简悦的阅读模式网页下，公式是正常的，导入后才出现问题）。
![image](https://user-images.githubusercontent.com/35155992/196577712-32095e65-daee-427d-8c5c-ab01e1477885.png)

- 操作系统 **win10**

- 浏览器版本 ![image](https://user-images.githubusercontent.com/35155992/196578174-18b1debf-d283-47c4-8957-0e84f7c93aae.png)

- 简悦版本 **2.0.0**，“导入到Obsidian”插件的版本为1.3.3

- 发生问题的地址 <请填写你的地址l>

示例网页（在该网页上导入OB时出现异常）：
https://zhuanlan.zhihu.com/p/29846048

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

将知乎内的科研类文章导入OBSIDIAN时，除正常显示的公式之外，在其之后紧跟一个该公式的代码（似乎是latex格式），导致公式看起来非常奇怪，文章难以正常阅读，麻烦尽快修正下（在简悦的阅读模式网页下，公式是正常的，导入后才出现问题）。
![image](https://user-images.githubusercontent.com/35155992/196577712-32095e65-daee-427d-8c5c-ab01e1477885.png)

**Comment by Kenshin** [comment]
嗨，是没问题的，看下图

<img width="902" alt="image" src="https://user-images.githubusercontent.com/81074/196584120-948d8e15-fb29-4580-bb3f-479aeddd6058.png">

但你能需要安装 https://github.com/Kenshin/simpread/discussions/2861 这个插件以及 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

**Comment by glareheaven** [comment]
已经正常了，非常感谢

**Comment by Kenshin** [comment]
小事情，解决就好~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
