### ISSUE TITLE
知乎与维基百科的公式导出会重复

### ISSUE THREAD

**Issue by hubery055** [Kenshin/simpread#4617]
https://zhuanlan.zhihu.com/p/42692080
https://zh.wikipedia.org/wiki/%E4%BB%BF%E5%B0%84%E5%8F%98%E6%8D%A2
会出现重复两边的情况吗，如下图：
![image](https://user-images.githubusercontent.com/46236062/196605585-c0632e54-273b-402b-8fc6-94dca15e1e77.png)
知乎会在后面重复，维基百科会在前面重复。
注意，维基百科的公式本来是不支持latex的，都是图片，也没有办法解析。后来我使用了维基百科自带的设置：
![image](https://user-images.githubusercontent.com/46236062/196605997-dcb7c7a8-b909-4408-9208-12d750651673.png)
并且使用了https://greasyfork.org/zh-CN/scripts/404735-latex这个脚本对latex公式进行显示。
这是一个临时解决方案，希望能适配一下维基百科，至少解决一下现在知乎的公式bug。
谢谢

**Comment by Kenshin** [comment]
嗨

> 知乎的问题

请使用 https://github.com/Kenshin/simpread/discussions/2861 提到的方案，即可解决。

> 维基百科的公式问题

这个油猴脚本不错，我一会看看。

我建议使用 https://github.com/Kenshin/simpread/discussions/3196 提到的方式查看维基百科。

然后将下面代码

```
sr-rd-content math {display: none;}
```

加入到下图

![image](https://user-images.githubusercontent.com/81074/196619420-2e25959d-ffdf-4164-9153-8c9cd4f9381f.png)

得到的效果如下

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/81074/196619518-251fdf1e-9403-4157-b645-a926642b2fbb.png">

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

![image](https://github.com/Kenshin/simpread/assets/81074/72d63b20-5061-4ce8-a3ce-408847c387c0)

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
