### ISSUE TITLE
自动化导出为html的问题

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4619]
简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

操作系统 Windows 11

浏览器版本 Microsoft Edge  106.0.1370.47 (正式版本) (64 位)

简悦版本 2.2.0

设置 > 服务 > 自动化
![image](https://user-images.githubusercontent.com/3283023/196611828-59aa4496-ed1b-403c-9a98-153d6934d5a5.png)
设置了添加稍后读和标注后自动导出`html`的功能
打开网页，快捷键`aa`进入阅读模式
1. 简悦菜单栏选择“保存到简悦·稍后读”后，**没有导出`html`**
![image](https://user-images.githubusercontent.com/3283023/196612129-f414aca7-3d50-4ebf-8817-e0f04462d89e.png)
2. 选择“导出为HTML”后，成功导出了`html`，但名字不对，缺少了`id`
![image](https://user-images.githubusercontent.com/3283023/196612283-518880a2-e2be-46dc-9fd4-4cf81302230d.png)
![image](https://user-images.githubusercontent.com/3283023/196612513-7ca06421-892b-4ae8-afe8-7a152a5b2ecd.png)
3. 在阅读界面进行文章标注后导出了新的`html`文件，这里有两个问题，一个是`id`变了，另一个是`id`和`title`中间有两个`-`
![image](https://user-images.githubusercontent.com/3283023/196612643-5409279e-7a7f-4919-857e-1f9d18c3d598.png)

**Comment by Kenshin** [comment]
> 简悦菜单栏选择“保存到简悦·稍后读”后

暂时不要使用这种方式，使用快捷键 `d d` 细节看这里 https://github.com/Kenshin/simpread/discussions/2362

> 问题 2 和 3

感觉是你的设定有错误，选项页 → 服务 → 定制导出，看看跟下图是否一样？

<img width="871" alt="image" src="https://user-images.githubusercontent.com/81074/196618613-821e657a-995e-4acd-831e-c7361b4f0f6a.png">

**Comment by iblogc** [comment]
现在可以了，谢谢，就是这两个地方的配置格式不一样（一个要带`-`一个不需要带）感觉会让人产生误会
![image](https://user-images.githubusercontent.com/3283023/196651163-106ff1cb-2ea6-45d3-82ef-f60a3e2ccb05.png)
![image](https://user-images.githubusercontent.com/3283023/196651172-ed304850-d985-4254-bba6-ca2dc48bf774.png)

**Comment by Kenshin** [comment]
okay 我关闭这个 Issues 了。

关于提到的 **问题1**，也可以使用 https://simpread.ksria.cn/plugins/details/rsd4UIcDKY 解决。

<img width="865" alt="image" src="https://user-images.githubusercontent.com/81074/196665768-962d7462-66ee-4cfa-92b6-cbc103acfc8c.png">

刚刚增加了一个快捷键支持（上图所示）。

**Comment by iblogc** [comment]
@Kenshin 这个快捷键设置在哪里，刚刚找了下没找到

**Comment by Kenshin** [comment]
如果你使用了同步助手，请通过 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装这个插件（链接有安装使用说明）

安装后，会在右下角有个 Icon 下图所示

<img width="321" alt="image" src="https://user-images.githubusercontent.com/81074/196667239-aa478e0b-aa80-434f-8c48-8dcc204a55a5.png">

**Comment by iblogc** [comment]
找好了，谢谢🤝
