### ISSUE TITLE
towardsdatascience 无法使用 assets 方案导入

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#4620]
比如这个文章
https://towardsdatascience.com/all-about-categorical-variable-encoding-305f3361fd02

1. 正文显示错误，我手动选择，然后清除了一些元素
![image](https://user-images.githubusercontent.com/3938751/196614981-ff92f0f6-ccb3-4bd9-9f82-655f7896fa4f.png)

2. 然后保存到稍后读， 稍后读-阅读模式  
![image](https://user-images.githubusercontent.com/3938751/196615197-04a2ca3b-2fd8-49b3-808f-66d029b0964d.png)
 
3. 手动点击 导出全文到obsidian , 显示的不是手动选择清理过的正文  （后来发现这个是稍后读导出的内容）
![image](https://user-images.githubusercontent.com/3938751/196615284-478a23e7-82e3-4445-9c96-7cc3d843c67b.png)

4. 手动点击 导出全文到obsidian ， 正常
5. 导出 asset 和 正文到 obsidian , 出现转圈无法导出
![image](https://user-images.githubusercontent.com/3938751/196617931-48c9c244-ea12-4de7-9316-bf85d70d2755.png)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/203216859-7b20f782-8821-45c6-b95e-993195de136f.png)

嗨

> [同步助手 1.1.3 版](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)  发布啦  🎉 
> 
> 内置了此功能，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696)。

<img width="527" alt="image" src="https://user-images.githubusercontent.com/81074/203234319-2cd4d083-f521-498b-a9c9-4d5f6d85628e.png">

打开 https://simpread.ksria.cn/plugins/details/BvjrJA6eh5 可自动安装。如果使用同步助手的话，请使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 安装。

### 除此之外比较重要的更新

- 读取本地文件，可将本地任何 `.html` `.md` 加入到稍后读，详细说明 [请看这里](http://ksria.com/simpread/docs/#/外部文件)。

- 稍后读外部访问，方便第三方工具接入，详细说明 [请看这里](http://ksria.com/simpread/docs/#/稍后读外部访问)。

- 更换文档地址源，方便不同网络环境的用户使用 [请看这里](http://ksria.com/simpread/docs/#/Sync?id=文档地址源)。

- [浅色主题](http://ksria.com/simpread/docs/#/Sync?id=主题) 以及 [自动暗色模式](http://ksria.com/simpread/docs/#/Sync?id=暗色模式)。

- 同步助手的增强导出规则 `type`，可区分全文和标注，[详细说明](http://ksria.com/simpread/docs/#/Sync?id=增强导出)

  ```
  {"extension":"assets", "path":"/Users/xxxx/Documents/Obsidian@simpread/Inbox", "type":"page"}
  {"extension":"md", "path":"/Users/xxxx/Documents/Obsidian@simpread/SimpRead", "type":"annote"}
  ```

详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4192563)。

**Comment by Kenshin** [comment]
当选择了 [Base64 方案](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920120) 后，就可以正常导入到 Obsidian 里面了。

![image](https://user-images.githubusercontent.com/81074/203234418-3ca3833f-5c4f-4a3b-827f-492034668b8e.png)

功能已经内置到以下两个插件中

- [导出 md + assets 格式](https://github.com/Kenshin/simpread/discussions/4041)

- [导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

这是导入后的效果

<img width="770" alt="image" src="https://user-images.githubusercontent.com/81074/203247508-da18535c-ce60-497d-8752-eb887963eadd.png">
