### ISSUE TITLE
希望能够兼容Online Dictionary Helper

### ISSUE THREAD

**Issue by qiqiu1** [Kenshin/simpread#4622]
噢噢，现在可以了，原来是ODH反应速度太慢了

**Comment by Kenshin** [comment]
哈，没问题就好，我关闭这个 Issues 了。

PS：这是英译英的扩展？

**Comment by qiqiu1** [comment]
> 哈，没问题就好，我关闭这个 Issues 了。
> 
> PS：这是英译英的扩展？

是很好用的可以连接anki的词典
