### ISSUE TITLE
关于 Notion Page 适配简悦的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4623]
安装报错：414 Request-URI Too Large

_Originally posted by @SeasonPilot in https://github.com/Kenshin/simpread/discussions/2106#discussioncomment-3922733_

**Comment by Kenshin** [comment]
@SeasonPilot 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

没理解你的意思，哪里出现这个提示？

**Comment by SeasonPilot** [comment]
> 

https://simpread.ksria.cn/sites/details/PYK6c7l880

**Comment by Kenshin** [comment]
可以正常安装，你是用手机 Kiwi 之类的吗？

**Comment by SeasonPilot** [comment]
> 
Mac
Chrome 已是最新版本
版本 106.0.5249.119（正式版本） (x86_64)

**Comment by SeasonPilot** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 晚上6:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 关于 Notion Page 适配简悦的疑问 (Issue #4623)





 
可以正常安装，你是用手机 Kiwi 之类的吗？

**Comment by Kenshin** [comment]
你在国内？还是国外？这个站放在了阿里云上面。

1. https://simpread.ksria.cn/sites/ 
2. http://simpread.pro/plugins
3. http://simpread.pro

你试试访问，看看什么效果？

**Comment by SeasonPilot** [comment]
> 你在国内？还是国外？这个站放在了阿里云上面。
> 
> 1. https://simpread.ksria.cn/sites/
> 2. http://simpread.pro/plugins
> 3. http://simpread.pro
> 
> 你试试访问，看看什么效果？

![image](https://user-images.githubusercontent.com/61238101/196929549-36ddbc8b-d687-4be3-8866-ccf7a72fb092.png)
好像和同步助手有关，我把同步助手退出后好像安装成功了

**Comment by SeasonPilot** [comment]
> 

我再打开 同步助手 后，刷新这个 站点管理页面后 组件就不显示了
![image](https://user-images.githubusercontent.com/61238101/196930159-b678889a-88f0-42b2-a7d8-7ed0a7c39ae8.png)

**Comment by Kenshin** [comment]
emmm 是这个问题 😂

解决方案：

1. 关闭自动同步
2. 安装这个站点（以及其它站点）
3. 开启自动同步并覆盖到本地

<img width="888" alt="image" src="https://user-images.githubusercontent.com/81074/196934505-9d50c79b-8882-47aa-a472-9b3d84efb105.png">

**Comment by Kenshin** [comment]
另外，补充下：如果是插件的话，使用 [插件管理器](https://github.com/Kenshin/simpread/discussions/4221) 即可。（链接内含使用方法，很简单，安装这个插件就行了。）

**Comment by SeasonPilot** [comment]
> emmm 是这个问题 😂
> 
> 解决方案：
> 
> 1. 关闭自动同步
> 2. 安装这个站点（以及其它站点）
> 3. 开启自动同步并覆盖到本地
> 
> <img alt="image" width="888" src="https://user-images.githubusercontent.com/81074/196934505-9d50c79b-8882-47aa-a472-9b3d84efb105.png">

感谢，问题已经解决了

**Comment by Kenshin** [comment]
小事情，解决就好~
