### ISSUE TITLE
语雀不能绑定

### ISSUE THREAD

**Issue by 1360410765** [Kenshin/simpread#4627]

**Comment by Kenshin** [comment]
没问题，请详细描述你的问题…

**Comment by 1360410765** [comment]
>跳转后点击确认授权回来之后还是没有授权，让重新授权诶。。。

**Comment by Kenshin** [comment]
在选项页 → 服务 → 授权管理里面授权。

**Comment by 1360410765** [comment]
> 
也是不行，在授权完成后，回来那个
![image](https://user-images.githubusercontent.com/56229241/197383846-762b195a-9928-4392-a181-1897da547d0f.png)
是绿了，但是刷新一下又没了、、就是直接没有授权上

**Comment by Kenshin** [comment]
测试了下，是没问题的。

你是否用了同步助手？如果是的话，暂时先关闭自动同步后再试试。

等没问题的话，在开启同步助手并覆盖到本地。

**Comment by 1360410765** [comment]
> 

确实是自动同步导致的诶，已经好了，不过我有出现新的问题、、、
![动画](https://user-images.githubusercontent.com/56229241/197391294-55a2fadd-e8bc-4f10-8208-9b7a9e50f040.gif)
不能标注了。。。点击这个按钮不会切换，会在下一次启动的时候切换，但是不论是开了没开标注模式，都不会弹出标注窗口了。

**Comment by 1360410765** [comment]
> 

![image](https://user-images.githubusercontent.com/56229241/197393247-65629751-ef02-40d4-bda5-d635f643668a.png)
JS错误

**Comment by Kenshin** [comment]
你有多少个稍后读？看起来好像是某个稍后读的数据结构错误造成的。

**Comment by 1360410765** [comment]
我只有一个，我把它给删除了就可以标注了、、但是感觉以后有隐患。。

**Comment by Kenshin** [comment]
当然没有所谓的隐患了 😂 ...

简悦也不止你一个用户。

1. 只要正常操作当然没问题。
2. 如果使用自动同步的话，可通过坚果云的历史记录还原任意版本。
3. 简悦的同步助手接下来会加入数据的验证功能，确保数据结构的准确性。

**Comment by 1360410765** [comment]
> 

嗯尽快吧。。。目前知乎的文章支持的不是很好，主要是公式问题。
请问同一台电脑的不同浏览器算一个设备吗？我想换Chrome试试，目前Edge用着一直有小问题。

**Comment by Kenshin** [comment]
知乎已经适配的很好了，但你需要使用 https://github.com/Kenshin/simpread/discussions/2861

Edge 跟 Chrome 都一样，目前你遇到的两个反馈问题都是操作不当造成的。
