### ISSUE TITLE
关于知乎辅助增强的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4638]
https://zhuanlan.zhihu.com/p/161277762
可以在这篇文章上试试。。。
我导出md后Obsidian上显示如下
![image](https://user-images.githubusercontent.com/56229241/197728184-84ae1ad9-3aa4-43e0-a66a-4b46add4e766.png)

_Originally posted by @1360410765 in https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3958354_

**Comment by Kenshin** [comment]
@1360410765

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

是没问题的，仔细看下图的说明

<img width="886" alt="image" src="https://user-images.githubusercontent.com/81074/197748754-135f6fdd-9b48-4a43-b567-adbe5a62dc17.png">

导入到 ob 的效果

<img width="857" alt="image" src="https://user-images.githubusercontent.com/81074/197748864-5bda8c79-1f8a-4f38-81bf-0ccea2147dad.png">

**Comment by 1360410765** [comment]
> @1360410765
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 是没问题的，仔细看下图的说明
> 
> <img alt="image" width="886" src="https://user-images.githubusercontent.com/81074/197748754-135f6fdd-9b48-4a43-b567-adbe5a62dc17.png">
> 
> 导入到 ob 的效果
> 
> <img alt="image" width="857" src="https://user-images.githubusercontent.com/81074/197748864-5bda8c79-1f8a-4f38-81bf-0ccea2147dad.png">

真的很奇怪，我就是都拉到最下面了，然后阅读模式标注时没问题，显示的都正常，但是导出后就不对了，不论是html，markdown还是pdf，就是会有
![image](https://user-images.githubusercontent.com/56229241/197764964-71c366e8-4603-4126-b8f0-0c0c7286e83a.png)

这是我生成的临时页面你可以看一下
https://simpread.herokuapp.com/view/73994827033.html

**Comment by Kenshin** [comment]
不用通过临时页面分享，既然叫临时页面，有效性不会超过2个小时。

> 我就是都拉到最下面了

拉到底下的意思是让这个页面的公式都加载（知乎改过几次公式规则... 现在的规则比较麻烦些）

另外，先不要标注（如有标注请先删除或者直接删除稍后读），直接导出 HTML 或 Markdown 看什么情况。

**Comment by 1360410765** [comment]
![image](https://user-images.githubusercontent.com/56229241/197926126-4c889a04-fadc-479f-9824-dc49215f4233.png)
没有标注，导出就是这样了
[机器学习方法—优雅的模型（一）：变分自编码器（VAE）.md](https://github.com/Kenshin/simpread/files/9865718/VAE.md)

**Comment by Kenshin** [comment]
[机器学习方法—优雅的模型（一）：变分自编码器（VAE）.txt](https://github.com/Kenshin/simpread/files/9865766/VAE.txt)

这是我导出的，你看看，留意下面的说明。

<img width="475" alt="image" src="https://user-images.githubusercontent.com/81074/197927918-392d0c41-92f5-4f7f-a11b-15a8aa4d64f7.png">

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/81074/197928049-8139b756-42ae-44a2-9b1a-ab7d69084f7e.png">
