### ISSUE TITLE
gitbook的阅读模式错误

### ISSUE THREAD

**Issue by blue-bird1** [Kenshin/simpread#464]
我在 https://wizardforcel.gitbooks.io/ds-ipynb/content/ 阅读时,标题变成了`Introduction 数据科学 IPython 笔记本 results matching ""No results matching""`
![Screenshot_11.png](https://i.loli.net/2019/03/28/5c9ba875aaa46.png)

**Comment by Kenshin** [comment]
谢谢反馈。
凡是跟阅读模式获取失败的问题，都可以通过手动方式解决，如下图：

![Xnip2019-03-28_09-43-19](https://user-images.githubusercontent.com/81074/55123547-02e69980-513e-11e9-88b1-62d6d78e31c5.jpg)

PS：如果有对 JS 简单了解的话，你可以用简悦配置出任何你想要实现的样式。
