### ISSUE TITLE
不好意思，在加入简悦电报群的时候，不小心点错了答案，应该联系谁😭？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4642]
不好意思，在加入简悦电报群的时候，不小心点错了答案，应该联系谁😭？

_Originally posted by @Aspyrine in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-3976513_

**Comment by Kenshin** [comment]
@Aspyrine 

点错答案后会告诉你找管理的.... 把你的 tg id 告诉我。

**Comment by Aspyrine** [comment]
@Kenshin EAnomn

**Comment by Kenshin** [comment]
我已联系了你，并把你的 tg id 这条 Issues 删除了。
