### ISSUE TITLE
代码高亮丢失 <output-package> 

### ISSUE THREAD

**Issue by SeasonPilot** [Kenshin/simpread#4643]
notion 转阅读模式丢失` <output-package> ` 尖括号内的内容

`# generate-groups.sh <generators> <output-package> <apis-package> <groups-versions>`

**Comment by Kenshin** [comment]
嗨，试试导入 md 到本地，看看是什么情况？如果没问题的话，就说明是 Notion 本身的问题，因为 Notion 对 Markdown 的支持度不是 100% 兼容。

如果不是的话，请提供 URL 我瞧瞧。

**Comment by SeasonPilot** [comment]
> 
导出的md 也丢失了`<output-package>` 尖括号内的内容

**Comment by Kenshin** [comment]
okay 那就是另外的问题了，跟代码高亮规则有关系，我会统一记录到 #500

请提供出错的 URL

**Comment by SeasonPilot** [comment]
> okay 那就是另外的问题了，跟代码高亮规则有关系，我会统一记录到 #500
> 
> 请提供出错的 URL

https://www.notion.so/fee5979b024745ebb527575058c5978f

**Comment by Kenshin** [comment]
okay
