### ISSUE TITLE
同步助手2.0目前win11无法兼容问题

### ISSUE THREAD

**Issue by galigaga123** [Kenshin/simpread#4644]
同步助手1.1.2目前win11无法兼容,无法正常启动请问能够解决一下吗？

**Comment by Kenshin** [comment]
嗨，应该没问题的....

请截图说明下。另外，你在使用 1.1.2 之前是什么版本？

**Comment by galigaga123** [comment]
![Snipaste_2022-10-29_15-43-23](https://user-images.githubusercontent.com/72644242/198820605-4e0aeb6c-64e5-4978-a5b6-95e3e189f7
![Snipaste_2022-10-29_15-43-33](https://user-images.githubusercontent.com/72644242/198820609-6358bec3-cf21-4d37-b1a5-bbba53e8e627.png)
d7.png)
![Snipaste_2022-10-29_15-43-44](https://user-images.githubusercontent.com/72644242/198820617-2e7d6027-2a53-41e5-9dff-976f6683170d.png)
![Snipaste_2022-10-29_15-45-51](https://user-images.githubusercontent.com/72644242/198820618-e8003c96-0303-4719-8ee8-de160f300294.png)
我之前没用最新安装的1.1.2版本不行，然后回退了几个版本安装都是不行的，同步助手无法正常启动，进厂看到是启动了的，也没法绑定用户

**Comment by Kenshin** [comment]
最后一个截图是同时运行了3个同步助手，这显然不对...

重启电脑，然后双击 `.exe` 如果无法运行的话，肯定会有提示之类的。

因为你没法运行同步助手，当然无法绑定了。

**Comment by galigaga123** [comment]
重启还是一样的，会有多个进程存在而且没有任何提示
