### ISSUE TITLE
简悦再导入到notion时，并不能找到对应联系人，如下图

### ISSUE THREAD

**Issue by amumu3792** [Kenshin/simpread#4645]
![tmp2949](https://user-images.githubusercontent.com/116877199/198547831-13acee0f-29c7-4c7b-94a6-ec2e66a68150.png)

**Comment by amumu3792** [comment]
你们再notion上的教程说要那个密钥 输入找不到人啊

**Comment by Kenshin** [comment]
嗨，Notion 修改了 integration 的方式造成的，看这个视频 https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2419554
