### ISSUE TITLE
win11同步助手无法启动问题

### ISSUE THREAD

**Issue by galigaga123** [Kenshin/simpread#4649]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.   Microsoft Windows 11 家庭中文版 10.0.22000

- 浏览器版本 **e.g. Chrome 106.0.5249.121

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 双击启动同步助手无法正常启动，进程存在也无法绑定用户。😀

![Snipaste_2022-10-29_15-43-23](https://user-images.githubusercontent.com/72644242/198820943-3d4f5e7d-c6de-4cfb-8b25-f934b6f9a444.png)
![Snipaste_2022-10-29_15-43-33](https://user-images.githubusercontent.com/72644242/198820946-497840b8-ea5e-4a55-aefc-54474ecfbde6.png)
![Snipaste_2022-10-29_15-43-44](https://user-images.githubusercontent.com/72644242/198820947-361ada25-2433-4b06-991c-81be41d6099c.png)
![Snipaste_2022-10-29_15-45-51](https://user-images.githubusercontent.com/72644242/198820949-a156c879-ab68-41aa-a1d5-e699381201b4.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，同一个问题请不要重复提问 😂 请在 https://github.com/Kenshin/simpread/issues/4644 讨论。
