### ISSUE TITLE
设置后就无法使用

### ISSUE THREAD

**Issue by Chihiromis** [Kenshin/simpread#465]
每次设置完就不能用了（原本适配的站点 图标也是灰色的 按快捷键也不开启阅读模式） 导入配置也无法使用 请问这是啥问题吗 我设置了好久。。最后只能清除数据重新使用

**Comment by Kenshin** [comment]
请看关联问题 https://github.com/Kenshin/simpread/issues/391#issuecomment-477598880
同时也根据上个链接的关联问题，把你的配置文件给我。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，其它更新包括：

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
