### ISSUE TITLE
跨设备导出时文章id重复

### ISSUE THREAD

**Issue by xmingsir** [Kenshin/simpread#4652]
**请说明发生问题的环境**

- 操作系统 2台设备都是 MacOS，两台设备使用的是OneDriver 进行同步。

- 浏览器版本 **版本 106.0.5249.119（正式版本） (x86_64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 <请填写你的地址l>
   - http://www.ruanyifeng.com/blog/2022/10/weekly-issue-228.html
   - https://mp.weixin.qq.com/s/isr__DKMb7XV1E6zE8Z3Kw

**请描述你的问题**
跨设备导出时id重复（期望是自增id）。在定制导出时，设置为`{{id}}{{un_title}}{{mode}}`。
具体如下图所示。导致最后访问离线文档时会错乱。

**截图**
截图为logseq 中显示的效果。
![截屏2022-10-29 下午9 38 57](https://user-images.githubusercontent.com/100058976/198834662-0ec97dc5-9411-4215-8b04-361739922946.png)

**Comment by Kenshin** [comment]
嗨，多台设备的话，需要确保开着坚果云，也就是说

A 电脑 → 加入稍后读 → 生成编号 10 本地快照 → 坚果云同步 → B 电脑（的坚果云自动同步10编号的文件）→ B 电脑 → 加入稍后读 → 生成 11 本地快照。

以此类推。

**Comment by Kenshin** [comment]
补充一点：看你的描述感觉像 simpread_config.json 没有正确同步造成。

PS：OneDriver 的同步可能有点问题，最好先关闭它的自动同步，等需要时（如关机前）再开启。

这不是简悦的问题，好像它同步小文件时确实有点问题，之前有用户提过类似的情况。（但很你的现象不太一样，但结果类似）
