### ISSUE TITLE
关于自动导出 output 序号的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4654]
### Discussed in https://github.com/Kenshin/simpread/discussions/4653

<div type='discussions-op-text'>

<sup>Originally posted by **starrycrown** October 29, 2022</sup>
之前配置obsidian与简悦打通，成功。后来发现电脑1同电脑2在使用自动同步时，设置错了output文件，电脑2在output里面创建了output,发现后更正。之后出现电脑1进行稍后度，电脑2不同步，电脑1进行的稍后读电脑1可以同步，后来发现数量不对，检查output,发现电脑1的稍后度，下载到本地的序号没有按照之前的排序下去（电脑1已经到169，而电脑2还在159）（新的稍后读），而且更严重的时，电脑2在追赶电脑1时一直再覆盖，最严重的时电脑1昨天还是169，今天又跳转到了162，不敢在继续使用了</div>

**Comment by Kenshin** [comment]
@starrycrown

多台设备的话，需要确保开着坚果云，也就是说

A 电脑 → 加入稍后读 → 生成编号 10 本地快照 → 坚果云同步 → B 电脑（的坚果云自动同步10编号的文件）→ B 电脑 → 加入稍后读 → 生成 11 本地快照。

以此类推，但一般没有同时即使用 A 电脑又使用 B 电脑的情况…

**Comment by Kenshin** [comment]
再多说一点：既然你提到了 Obsidian ，简悦跟它的同步是一样的道理，只是多了个 simpread_config.json 你可以把它当做是本地快照的「索引」。

**Comment by starrycrown** [comment]
@Kenshin 
坚果云确实也是在同步，但是两电脑的本地编号各不同，电脑A到20，电脑B才15，然后逐步替换，我好些稍后度都没了
![C65I3}ALEZM8(8$RDLJDNXH](https://user-images.githubusercontent.com/113831219/198839101-920db613-86fa-4638-86a4-401b3d08d92c.png)

**Comment by Kenshin** [comment]
这两台电脑是同时在同步吗？

另外，看你描述的现象还是因为 simpread_config.json 互相覆盖造成的…

使用坚果云的历史记录 https://github.com/Kenshin/simpread/discussions/3165 看看能否找回？

**Comment by starrycrown** [comment]
没有，上班的时候家里电脑时关闭的，这个是可以肯定的。那我之后是直接清除一端的数据，在重新登录简悦，重新设置同步助手，这样子可以吗？
因为按我的理解的话， simpread_config.json是核心配置，两端的配置相同的话，应该不会出现这种情况，除非是我的核心配置除了问题
我有点怀疑是之前同步obsidian时，合并过一次稍后度，用了Visual Studio Code合并过，但当时我确实改了每一个的序号的，不知道是不是那里出了问题

**Comment by Kenshin** [comment]
> 按我的理解的话， simpread_config.json是核心配置，两端的配置相同的话，应该不会出现这种情况

是的。

两端相同配置是指：A 和 B 都使用同一份 `simpread_config.json` 而这个文件是通过坚果云同步的。

> 我有点怀疑是之前同步obsidian时，合并过一次稍后度，用了Visual Studio Code合并过，但当时我确实改了每一个的序号的，不知道是不是那里出了问题

有可能（我就说嘛，如果是按照 https://github.com/Kenshin/simpread/issues/4654#issuecomment-1295855930 的描述，不可能出现问题。

> 我有点怀疑是之前同步obsidian时，合并过一次稍后度

如果你用的配置库方案，其实不需要合并稍后读，直接将你稍后读替换 `unrdist` 就行。

> 在重新登录简悦，重新设置同步助手，这样子可以吗？

其实没有太大意义，你的问题是 A 和 B 在同步时序号有问题。所以，如果你有原来的稍后读，就按照我说的替换掉通过配置库方案设置后  `simpread_config.json` 里面的  `unrdist` 就行。

然后重启浏览器，再加入一个新的稍后读，看看它的编号是否是最新的。
