### ISSUE TITLE
简悦同步助手无法取消稍后读的快捷键

### ISSUE THREAD

**Issue by ab503044120** [Kenshin/simpread#4656]
简悦通同步助手 ctl + shift + n 和idea的快捷键冲突
按那个×取消,然后点击保存无法取消稍后读的快捷键

![image](https://user-images.githubusercontent.com/5219122/198881867-f176d810-8cf0-46e8-a4db-3227f2c37d93.png)
期望: 可以取消快捷键

简悦通同步助手版本: 1.1.2
系统: windows 10

**Comment by Kenshin** [comment]
嗨，先「×」再保存，然后重启同步助手。
