### ISSUE TITLE
公众号包含公式后阅读模式需要优化

### ISSUE THREAD

**Issue by Harzva** [Kenshin/simpread#4657]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

-->

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows 

- 浏览器版本 
![image](https://user-images.githubusercontent.com/49864959/198959978-4324d440-a3aa-4951-a0f8-3f06288c94db.png)

- 简悦版本 **2.0.0**

- 发生问题的地址 [<请填写你的地址l>](https://mp.weixin.qq.com/s/UXka4dH_VcVUS6tIGVZJ9Q)

**请描述你的问题**

![image](https://user-images.githubusercontent.com/49864959/198960115-592b6388-b6bb-495b-b808-3461a7833896.png)

上面是阅读模式下错误的显示
下面是原本的显示
![image](https://user-images.githubusercontent.com/49864959/198960232-ac1115e9-e523-4378-b54d-594f016c3a5f.png)
对字符的处理有问题例如上面出现的给定一个图像样本，xi  可能那是个图片

**Comment by Kenshin** [comment]
嗨，谢谢反馈，这是公众号公式造成的，暂时没有太好的解决方案，解决后我会在这里通知你~

**Comment by Harzva** [comment]
![image](https://user-images.githubusercontent.com/49864959/198970025-82bec157-7625-4971-8268-56f49c858930.png)

暂时解决了配置如下就是把那些都关了
![image](https://user-images.githubusercontent.com/49864959/198970055-6de87b70-f747-46b0-a4d8-a34575087533.png)
同步到obsidian的笔记还是没有字符，丢失了xi
![image](https://user-images.githubusercontent.com/49864959/198970175-0806928f-3c1e-4b5c-9b18-4f9459a75219.png)

**Comment by Harzva** [comment]
辛苦

**Comment by Kenshin** [comment]
> 暂时解决了配置如下就是把那些都关了

是可以这样，但治标而已 😂 还是等通用方案吧。

**Comment by Harzva** [comment]
大佬 ，我目前采用的方式2，想采用方式3但出问题了，显示我本地同步的端口一直出现被占用。而且我不小心点了阻止弹窗之前是显示弹窗但不自动关闭软件现在软件一打开因为端口弹窗问题直接退出了。

![image](https://user-images.githubusercontent.com/49864959/198970479-b5448333-1ed7-4928-9c1c-51cec16a776e.png)
![image](https://user-images.githubusercontent.com/49864959/198970822-48f51c5a-3d44-4e93-8790-b2fdfefd116a.png)

此外方式2的笔记导出始终是空的不知道为啥。

**Comment by Kenshin** [comment]
> 端口占用问题

最好的办法是重启电脑。😂

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，修复了此问题。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
