### ISSUE TITLE
 2.2.0.520导出问题

### ISSUE THREAD

**Issue by l739217783** [Kenshin/simpread#4658]
新版本2.2.0.520，反馈个问题，不知道其他人会不会

导出全文（标注）+标注，只能导出标注
如果单选其中任何一个（全文或者标注）没有问题
如果标注选项选择了全文（标注）+标注，无法同时下载两个，只会下载一个标注的HTML文件

自动化导出、手动导出（动作中的导出HTML）均不行
尝试许久后，发现问题所在，基础账户反而可以，登录高级账户就会复现这个问题

**Comment by Kenshin** [comment]
嗨，你提到的这些问题对应的功能在使用前需要配置 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 方案（链接就是教程）

但我建议你直接使用 [配置库方案](https://www.yuque.com/kenshin/simpread/ds8zk0) 一劳永逸。

**Comment by l739217783** [comment]
感谢，问题已解决



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年11月1日(周二) 上午10:44
收件人: ***@***.***&gt;;
抄送: "Kokuan ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread]  2.2.0.520导出问题 (Issue #4658)




 
嗨，你提到的这些问题对应的功能在使用前需要配置 知识库 方案（链接就是教程）
 
但我建议你直接使用 配置库方案 一劳永逸。

**Comment by Kenshin** [comment]
搞定就好 👌
