### ISSUE TITLE
关于聚焦模式

### ISSUE THREAD

**Issue by Chihiromis** [Kenshin/simpread#466]
你好。。我还是想保留as这个快捷键的 不知会不会麻烦你 能不能说如何禁用GitHub的快捷键 我按as的时候 会定位到GitHub的搜索框 而不是触发聚焦模式 谢谢

**Comment by Chihiromis** [comment]
还有一个问题是。。如果聚焦模式选错了 是不是只能刷新页面 重新选择了？

**Comment by Kenshin** [comment]
> 还有一个问题是。。如果聚焦模式选错了 是不是只能刷新页面 重新选择了？

不需要刷新，可以退出的，右下角选择退出即可。

建议多看看选项页中的 `高级设定` 。如果有不清楚的也可以直接找我。 😀 

> GitHub快捷键冲突

我不清楚如何修改 GitHub 的快捷键，甚至于我都不知道关于 GitHub 的快捷键 是 AS 这件事情。 😅

**Comment by Chihiromis** [comment]
> > 还有一个问题是。。如果聚焦模式选错了 是不是只能刷新页面 重新选择了？
> 
> 不需要刷新，可以退出的，右下角选择退出即可。
> 
> 建议多看看选项页中的 `高级设定` 。如果有不清楚的也可以直接找我。 😀
> 
谢谢 这个设置 成功了

**Comment by Chihiromis** [comment]
> 
> > GitHub 快捷键冲突
> 
> 我不清楚如何修改 GitHub 的快捷键，甚至于我都不知道关于 GitHub 的快捷键 是 AS 这件事情。 😅

GitHub快捷键是 s 然后光标就会定位到搜索栏。。然后与悦读 聚焦模式快捷键冲突了 我还用了vimium 所以重新设置聚焦模式快捷键是超容易冲突。。 小白一个 没Google到如何禁用网站自带的快捷键 😂

**Comment by Kenshin** [comment]
@Chihiromis 

修改 `A S` 是最简单办法，你可以修改为不冲突的即可。

***

我目前设置快捷键

- `1 1` → `阅读模式`
- `2 2` → `聚焦模式`

目前没有遇到什么问题。

**Comment by Chihiromis** [comment]
好的 感谢呀

**Comment by Chihiromis** [comment]
> @Chihiromis
> 
> 修改 `A S` 是最简单办法，你可以修改为不冲突的即可。
> 
> 我目前设置快捷键
> 
> * `1 1` → `阅读模式`
> * `2 2` → `聚焦模式`
> 
> 目前没有遇到什么问题。

我改成 a z了。。 1 2不知是不是又冲突了 没反应
