### ISSUE TITLE
在该网站显示代码高亮插件出错

### ISSUE THREAD

**Issue by ProudBenzene** [Kenshin/simpread#4663]
url：https://github.com/Yaozhuwa/easy-typing-obsidian/blob/master/README_ZH.md
在该网站显示代码高亮插件出错，要求提交链接。
谢谢您的付出！

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
