### ISSUE TITLE
[corb]新版chrome谷歌浏览器在 阅读模式 下无法使用 划词翻译 插件

### ISSUE THREAD

**Issue by shenqidezhengge** [Kenshin/simpread#467]
* 最新版谷歌浏览器在阅读模式下无法使用 **划词翻译** 插件, 划词后会显示"无法连接到服务器, 请稍后测试" (准确完整的文字我忘了......).
* 原因貌似是向百度翻译发送请求被拒绝, 谷歌浏览器也给出了说明[Cross-Origin Read Blocking (CORB)](https://www.chromestatus.com/feature/5629709824032768).
* 重新装回老版本的chrome能解决问题.
* 但希望能及时修复, 以便我们能及时更新谷歌浏览器, 谢谢!

**Comment by Kenshin** [comment]
谢谢反馈，我也遇到了同样的问题，我先记 Bug 解决会后通知到你。

不清楚新版又增加了什么安全限制...

**Comment by AriaLyy** [comment]
mark下，表示也遇到了

**Comment by Kenshin** [comment]
此问题已修复，请重新下载 https://simpread.ksria.cn/plugins/details/ohnTKVHz4a

***

简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
