### ISSUE TITLE
pdf导出 带目录

### ISSUE THREAD

**Issue by chs33** [Kenshin/simpread#4670]
如果可以的话 希望同步助手基础打印方案在导出pdf时 可以选择在插入目录与否的选项，这样导出的pdf可以自动支持跳转。效果就像阅读模式里的目录 只是把它在阅读模式里是在页面的左上角 pdf里移到文章标题下方（我不懂css不知道这个请求是否已经可以通过css在基础打印方案里实现）

理论上上面这个需求应该是可以通过同步助手高级打印方案里设置wkhtmltopdf来解决的，只是基础方案的效果已经完全符合我的审美（所以强迫症只差一点点），我发现用wkhtmltopdf生成的目录极其丑陋（就单独生生的在生成新的第一页在原有pdf前），而且还得调教wkhtmltopdf其他排版。

不知道实现难度几何?（希望这个要求不是太过分😂）

**Comment by Kenshin** [comment]
嗨，

PDF 高级打印模式直接就带目录的.... 

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/81074/199877253-7553fdb4-c6eb-4fd2-9225-adebb6626398.png">

**Comment by chs33** [comment]
看到了， 不过高级模式默认的样子打出来和初级模式不一样（个人很喜欢初级模式打出来的样子），而且也没有了末尾”原文地址“的部分

**Comment by Kenshin** [comment]
> 过高级模式默认的样子打出来和初级模式

需要自己调整，因为很多都可以定制化，细节这个 https://github.com/Kenshin/simpread/discussions/3887

**Comment by chs33** [comment]
请问有初级模式的样子模板可以参考吗

**Comment by Kenshin** [comment]
就是改个主题... 给你的链接里面有哦。

**Comment by chs33** [comment]
那如果想在末尾加上”原文地址“的部分呢？
