### ISSUE TITLE
知乎公式导出到notion时下标_和上标^缺失

### ISSUE THREAD

**Issue by jh-yi** [Kenshin/simpread#4671]
知乎的公式导出到markdown时正常，但导出到notion时没有下标_和上标^

例子如图：(Source: https://zhuanlan.zhihu.com/p/410776234)

本应是：X = [x_1^T; x_2^T; x_3^T] 
![image](https://user-images.githubusercontent.com/32620561/199866168-4035fd5f-96e2-4d07-bd38-00c3dc581209.png)
Notion中为：X = [x1T; x2T; x3T] 

已尝试#2860的插件及新版方案依旧不行。

提前感谢!

**Comment by Kenshin** [comment]
嗨，如果导出 Markdown 正常的话，就不是简悦的问题。

Notion 对 Markdown 的支持度不是 100% 完整。

你可以试试通过 Notion 直接导入 Markdown 文件看看能否解决。

**Comment by jh-yi** [comment]
请问有可能支持一下上下标之类的功能吗？出现的频率太高，每个都手动调整太久了。据我所知，导入到notion的其他方法里，官方Save to
Notion和Notion Saver也是丢失公式，但是第三方插件Klipper就可以很好适配公式。谢谢！

**Comment by Kenshin** [comment]
这是 Notion 的事情… 😂

至于你说的方式我会试试。
