### ISSUE TITLE
没有渠道下载同步助手

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#4672]
http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd
这个网站已经下载不到同步助手了

![image](https://user-images.githubusercontent.com/10437293/199872146-15b2d940-c43c-4cd6-916b-b34aaea42328.png)

进电报群又要15s内回答问题，一不小心点错了，就被永久封禁

现在已经完全没有渠道下载同步助手了！！！！！

**Comment by jy324** [comment]
http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd

**Comment by jy324** [comment]
https://app.box.com/s/q7hz86hkeqgoc7mkofxaxu5eiup88j32 
这个链接不行？

**Comment by Kenshin** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/81074/199876138-8e7f7436-a38c-4f94-9e61-513c6b811db6.png">

@AriaLyy 

前面这两个可以的。（话说，好久没看到你了~）

PS：某些网盘这是愿意操没用的心....

**Comment by Kenshin** [comment]
> 进电报群又要15s内回答问题，一不小心点错了，就被永久封禁

谁说永久的？被禁止后，可以联系我哦。（应该会有提示说联系管理员...

**Comment by AriaLyy** [comment]
> 

已经在电报下了，国内的网配合公司的深信服，真的是操
