### ISSUE TITLE
导出到坚果云，无法保存内容

### ISSUE THREAD

**Issue by kathleensun** [Kenshin/simpread#4673]
Hi,发现了新问题：

【问题描述】：
1. 简悦 2.0 pro版本；
2. 已运行“同步助手”
之前“简悦”保存到“坚果云”，是网页内容md，现在导出的文件，完全不含内容

变成这样：
![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202211041930156.png)

导出为离线markdown，也是一样的

只有导出为带格式的html，才是正常文件。

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202211041931129.png)

以前没有发生或这样的情况，都是保存到“坚果云”，就可以自动保存为带格式的md文件。

**Comment by Kenshin** [comment]
嗨

你导入的 Markdown 的内容是标注的内容，而不是全文。

如果你使用了同步助手大概率也使用了坚果云客户端，所以也不需要通过这种方式导入，直接导出 Markdown 就行了。

**Comment by kathleensun** [comment]
不不不，没有明白我的意思，我同时开了“同步助手”和“坚果云”。

之前，我选择“保存到坚果云”，

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202211051649634.jpg)

**会有完整的md文件保存下来，现在只有**

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202211041930156.png)

我没有标注任何内容。

无法保存完整网页

**Comment by Kenshin** [comment]
感觉你的问题是 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 设置有误造成的，如果没有太多稍后读的话，建议你直接使用 https://www.yuque.com/kenshin/simpread/fiyku3 提到的方案。

**Comment by kathleensun** [comment]
研究了一下

![](https://kkshuhua-1258487004.cos.ap-beijing.myqcloud.com/202211051829185.png)

这里关闭就可以了。

**Comment by Kenshin** [comment]
Cool
