### ISSUE TITLE
PicGo图床

### ISSUE THREAD

**Issue by jh-yi** [Kenshin/simpread#4674]
1. 使用插件：PicGo配置正常，平时用也没问题。但是在阅读模式中“导入图片到图床”时所有图片变成了第一行无法显示的样子（第二行是平时PicGo正常上传的情况）。

![image](https://user-images.githubusercontent.com/32620561/200086864-105d86e7-36a7-4bee-b613-20e3183a0eea.png)

2. 不用插件：虽然在服务中勾选使用notion.so作为图床之后，保存到notion时可以自动上传图片。但如何在复制markdown到粘贴板前也自动上传图片？

**Comment by Kenshin** [comment]
> 问题1

PicGo 是根据图片的 URL 的某些规则来生成对应的文件名，在某些页面如果这个规则得到的 URL 是一样的，对应的文件名就会一样，因此就会出现覆盖的问题。

> 问题2

复制 Markdown 到剪切板是没有这个功能的，但你可以使用 Typora 的功能，如下图来解决你的需求。

<img width="501" alt="image" src="https://user-images.githubusercontent.com/81074/200097989-54525759-86ee-452f-a38a-45b73b93044d.png">

**Comment by jh-yi** [comment]
> 

可是所有通过图床插件上传的图片都无法显示，我打开图片看了一下，基本都变成：
![image](https://user-images.githubusercontent.com/32620561/200114606-eaa87133-7ac4-472a-bf13-7bad819d54d1.png)
请问是配置有问题吗？

**Comment by Kenshin** [comment]
随便一个 URL 都不行吗？ e.g. https://sspai.com/post/69972

使用后这个图片的地址会被替换为你的图床地址，这个 URL 是什么？

还有，你用的 PicGo 是什么版本？

**Comment by jh-yi** [comment]
PicGo是2.3.1-beta.6版本。

我刚才把图床插件卸载再重新安装之后，在动作里已经找不到添加到图床选项了
[image: image.png]

**Comment by Kenshin** [comment]
> 我刚才把图床插件卸载再重新安装之后，在动作里已经找不到添加到图床选项了

解决方案 https://www.yuque.com/kenshin/simpread/fcw60u

***

PS：版本好像没问题，我也用的是这个 😂

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
