### ISSUE TITLE
win11不能导出PDF的问题。

### ISSUE THREAD

**Issue by wingXIII** [Kenshin/simpread#4677]
你好：
        之前的系统是win10的，简悦高级版导出PDF是好用的，但是我将系统升级win11后，导出PDF就是提示不小心调用失败了，报错信息如下：
Error handling response: TypeError: Cannot read properties of undefined (reading 'error')
    at eval (eval at c (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:6:17653), <anonymous>:257:66)

请问这个要怎么解决，日常已经离不开简悦了！！！

**Comment by Kenshin** [comment]
嗨，不要在不想干的地方反复提问   😂 

***

至于你的问题，是不是因为下图的原因？

<img width="683" alt="image" src="https://user-images.githubusercontent.com/81074/200284569-a9b0f4fa-8c1d-413f-8cab-baa12424ca64.png">

**Comment by wingXIII** [comment]
收到，非常感谢耐心回复！

**Comment by Kenshin** [comment]
解决了吗？
