### ISSUE TITLE
掘金文章导出到语雀图片加载失败

### ISSUE THREAD

**Issue by zhisheng00** [Kenshin/simpread#4678]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **edge最新版**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://juejin.cn/post/7161672523573100551 掘金文章的图片导出到语雀加载不出来>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/113188607/200318636-e243b5eb-0902-4503-b5ac-7bb0175afcec.png)
> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
emmmm

1. 导出 Markdown 后图片可用吗？
2. 其它页面有这个问题吗？例如少数派的页面有这个问题吗？

**Comment by zhisheng00** [comment]
导出markdown图片显示正常，其他页面也正常，目前只发现掘金有这个问题
---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2022年11月7日 23:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 掘金文章导出到语雀图片加载失败 (Issue #4678) |

emmmm

导出 Markdown 后图片可用吗？
其它页面有这个问题吗？例如少数派的页面有这个问题吗？

**Comment by Kenshin** [comment]
掘金的任意页面都有问题吗？如果是的话，估计它的图片有「防盗链」的功能。

建议使用离线方案，如：离线 HTML、PDF、assets + md 等。
