### ISSUE TITLE
电脑重装后  导入备份的配置文件 显示版本冲突后 持续冻结在选项图上

### ISSUE THREAD

**Issue by jinboowu** [Kenshin/simpread#4680]

**Comment by Kenshin** [comment]
估计你导入的配置文件名字叫做 `simpread_请勿遗失xxx.json` 吧？如果是的话，这个文件不是用来导入的，内含了你的 License 和 UID。

你需要导入的是 `simpread_config.json` 或 `simpread-config-2022年xx月xx日 xx_xx_xx.json` 的文件才可以。

**Comment by jinboowu** [comment]
simpread-config-2022年xx月xx日 xx_xx_xx.json  按这个格式导出的备份文件，发生冲突  
用1年前的备份恢复了，但数据也没了

**Comment by Kenshin** [comment]
有没有用过坚果云？如果用过坚果云的话，它有历史记录，可以通过历史记录还原。https://github.com/Kenshin/simpread/discussions/3940
