### ISSUE TITLE
标注功能 强化

### ISSUE THREAD

**Issue by Sukariui** [Kenshin/simpread#4682]
建议：当前标注功能还需要进入阅读模式，是否可以直接在网页标注
理由：有些网页资源看过了，过了一段时间忘记看过了再看了一遍，浪费了时间，直接添加标记之后，就知道这个网页看过了，如果有批注的话还能知道是什么时候看过的

**Comment by Kenshin** [comment]
嗨，简悦是基于阅读模式的产品，所以肯定是要进入阅读模式后才能标注的，这不是技术决定的，而是设计思路。

换句话说：简悦是希望有深度阅读诉求的前提下再使用它，否则的话，原文标注建议使用 Hypothesis （这是最好的原文标注产品，全免费。
