### ISSUE TITLE
同步助手 正式版 1.1.2网盘链接失效

### ISSUE THREAD

**Issue by sdivens** [Kenshin/simpread#4683]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
下面 [两个下载链接](http://ksria.com/simpread/docs/#/Sync?id=%e4%b8%8b%e8%bd%bd) 可在国内使用

<img width="621" alt="image" src="https://user-images.githubusercontent.com/81074/200513407-5ad289d4-ec34-40f1-9b4f-6a91b7b0277e.png">
