### ISSUE TITLE
导入到 logseq 后标注色不生效

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4694]
导入到logseq后[:p {:style {:background-color不起作用

_Originally posted by @hozorro in https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-4104582_

**Comment by Kenshin** [comment]
@hozorro

嗨，我帮你新建了一个 Issues 讨论。

跟 https://github.com/Kenshin/simpread/issues/4693 重复了，统一到这个链接里面。

**Comment by lyserenity** [comment]
抱歉，问了大佬之后才发现我模版写错了.....hiccup 的正确写法是：
``[:p {:style "background-color:#FF6F00;"} "test"]``

所以模版是：

```
<%
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
    color  = colors[ annote.color ];
let url    = 'http://localhost:7026/unread/' + unread.idx + '#id=' + annote.id;
%>
## [📌](<<%= url %>>) Highlights {{an_tags}}
> [:p {:style "background-color:<%= color %>"} "{{an_text}}"]

<% if (annote.note) { %>
>> {{an_note}}
<% } %>
### reference
<%- (annote.refs)? "> refs: " + annote.refs : "" %>

> backlinks: {{an_backlinks}}
```

**Comment by hozorro** [comment]
haha，刚看了hiccup语法https://github.com/weavejester/hiccup/wiki/Syntax我也已经知道了。

**Comment by hozorro** [comment]
> 抱歉，问了大佬之后才发现我模版写错了.....hiccup 的正确写法是： `[:p {:style "background-color:#FF6F00;"} "test"]`
> 
> 所以模版是：
> 
> ```
> <%
> let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
>     color  = colors[ annote.color ];
> let url    = 'http://localhost:7026/unread/' + unread.idx + '#id=' + annote.id;
> %>
> ## [📌](<<%= url %>>) Highlights {{an_tags}}
> > [:p {:style "background-color:<%= color %>"} "{{an_text}}"]
> 
> <% if (annote.note) { %>
> >> {{an_note}}
> <% } %>
> ### reference
> <%- (annote.refs)? "> refs: " + annote.refs : "" %>
> 
> > backlinks: {{an_backlinks}}
> ```

大佬还有一个问题，这里面的an_note前面的">>"应该本意是进一个层级，但是实际生成的内容中由于自动在这一行前面加了一个空行，导致导出之logseq后an_note并没有进一个层级。这个在模板设置窗口上点击”测试“可以看出来。请问大佬怎样在生成实际到处内容时前面不要自动加个空行？

**Comment by lyserenity** [comment]
```
<% if (annote.note) { %>
```
理论上把这行前面的空行删掉就可以了，因为我 logseq 用的是 org，又懒得新建 markdown 来测试，所以要麻烦你自己测试一下...🤣

**Comment by Kenshin** [comment]
@hozorro 

嗨，我更新了模板，可以直接使用 https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-3819505
