### ISSUE TITLE
导入obsidian插件，标注导入时空白的问题。

### ISSUE THREAD

**Issue by zhaoyundi** [Kenshin/simpread#4696]
感谢大佬。
利用导入obsidian插件。正文、附件都可以正常导入，但是我导入标注时，是空白。
![image](https://user-images.githubusercontent.com/44336996/201107050-ceae14c0-c7b2-43fa-a5e8-1612ae1ab61b.png)

![image](https://user-images.githubusercontent.com/44336996/201106914-ef174bfb-cce9-4214-a654-b3d1f36a94f5.png)

我已经看到了其他有关标注的高级功能，但是实在过于复杂，想先问问在这里有没有可以解决的简单办法？
谢谢您。

**Comment by zhaoyundi** [comment]
> 嗨，如果是新用户的话，建议直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef
目前obsidian和logseq我都在用，并且有了一些东西。之前我没有用过配置库，但我想把简悦的东西给融入到现有的资料里面。
标注空白的问题已经解决了，但是我发现obsidian的模板的链接，都无法正常导回简悦，请问这个怎么解决？

**Comment by zhaoyundi** [comment]
链接的问题已经解决。
服务-自动化，当加入标注时，导出到HTML。

**Comment by Kenshin** [comment]
Cool 自行解决也行。😄  👍
