### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by streamDream** [Kenshin/simpread#4698]
发生问题的地址: <https://blog.csdn.net/george_xiaoqiao/article/details/73274705?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0-73274705-blog-103498881.pc_relevant_aa

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
