### ISSUE TITLE
求适配Wordpress默认主题

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#47]
Wordpress默认主题都很有特点的。比如HTML里面都会含有`wp-content/themes/年份的英文`。

工作量：从2010开始到2017，每年一个主题，好像工作量不会太大吧……这样做就和#40 一样，一次就能适配很多站点了。

**Comment by Kenshin** [comment]
感谢建议～
我想到了一个解决办法，但不一定靠谱，需要回去后才能实验。
我在外面休假…
如果方便的话，最好给我一些 Wordpress 站，这样可以做个参考。

**Comment by Kenshin** [comment]
刚刚确认了几个 Wordpress 的站，并没有你说的

> wp-content/themes/年份的英文

这个情况。

但似乎某些站的结构比较相似，比如 标题 和 正文 具有相同的 html 节点，但它们的域名不可能有任何规则。

虽然目前的简悦是不支持这种情况的，未来可以增加这类网站，但前提是如何来识别某个页面是否是 Wordpress，目前唯一可以利用的是 

`<meta name="generator" content="WordPress 4.8">`

但似乎不是每个站都有这个 htm 标识，同时也只是某些站才具有上述的相同标识。

**Comment by jinyu121** [comment]
那就给你几个特征吧：

| 主题年份 | 特征 | 预览链接 | 
| --- | --- | --- |
| 2017 | `id='twentyseventeen-fonts-css'` | [这里](https://wp-themes.com/twentyseventeen/) |
| 2016 | `id='twentysixteen-fonts-css'`  | [这里](https://wp-themes.com/twentysixteen/) |
| 2015 | `id='twentyfifteen-fonts-css'` | [这里](https://wp-themes.com/twentyfifteen/) |
| 2014 | `id='twentyfourteen-lato-css'` | [这里](https://wp-themes.com/twentyfourteen/) |
并且路径里面也会有`wp-content/themes/twentyXXXXX`字样

注意，这里只讨论__默认主题/年份主题__。其他主题可能删去了这些特征。

**Comment by Kenshin** [comment]
@jinyu121 
okay，我会参考你的建议，通过检索特定字符这个方案可行。
因为适配的逻辑改变了， `适配某类站` 而非通过 `url判断` 这个功能可能需要 1.1.0 之后才会去做。

话说，使用 Wordpress 默认主题的站很多吗？我昨天在测试时，应该一个都没找到...

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 关闭。

增加了 `智能适配模式` 详细 [请看这里](https://github.com/Kenshin/simpread/wiki/%E6%99%BA%E8%83%BD%E9%80%82%E9%85%8D%E6%A8%A1%E5%BC%8F)

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
