### ISSUE TITLE
原网页包含视频内容，即使重新定位高亮或通过live editor清除视频元素，加入稍后读之后，依旧无法读取本地缓存。

### ISSUE THREAD

**Issue by doggyone** [Kenshin/simpread#4701]
- 操作系统 **MacOS 13.0.1**

- 浏览器版本 **Arc 浏览器 0.76.0 (35707)”

- 浏览器Chromium Engine Version **107.0.5304.110**

- 简悦版本 **2.2.0**

- 发生问题的地址 ：任意包含视频的网页，例如简悦的包含视频演示的 github 演示页面 [https://github.com/Kenshin/simpread/discussions/2146]

----

**请描述你的问题**

1. 首先对于包含视频的网页，直接进入阅读模式，一般都会解析错误。
这时候通过：
- “重新选定高光区域”
- 或先通过选定网页内容后开启阅读模式
- 甚至是在前两者的基础上进一步通过 live editor删除视频元素
之后再添加到稍后读页面。

2. 可以确认此时知识库和资料库以及其他导出相关的设置都是正确的，因为其他纯文字及图片的网页，是可以加载本地 html 的，即显示 local以及显示“本地 html”的图标

3. 同时可以确认，1.的所有操作后，本地 output 文件夹中的 html 文件是导出成功的，通过浏览器打开该文件，其呈现的形式与我编辑后的内容及样式是一致的

4. 此时回到稍后读页面，查看添加的网页，其并不会加载本地 html，而是加载原网页

**Comment by Kenshin** [comment]
嗨，把出问题的 HTML 发上来，另外把出问题的 URL 也发上来。

**Comment by doggyone** [comment]
网页是这个，因为默认无法正确解析网页，所以通过选中部分内容生成阅读模式https://github.com/Kenshin/simpread/discussions/2852

文件的话因为issue提交不了 html 格式的文件，麻烦把 txt 后缀改回 html 后查看，不知道是否会影响。
[Live Editor · Discussion #2852 · Kenshin-simpread.txt](https://github.com/Kenshin/simpread/files/9990267/Live.Editor.Discussion.2852.Kenshin-simpread.txt)

**Comment by Kenshin** [comment]
好，我明天确认下。

**Comment by doggyone** [comment]
请问下有确认结果了吗？

**Comment by Kenshin** [comment]
我现在确认下，稍等~

**Comment by Kenshin** [comment]
嗨，这是我在稍后读的阅读模式下读取你给我的本地快照，是没问题的。（留意箭头）

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/81074/201568624-81c7768c-870e-40d2-acd7-57277a64a1f0.png">
