### ISSUE TITLE
pdf导出的效果跟页面不一样

### ISSUE THREAD

**Issue by TrillStones** [Kenshin/simpread#4702]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://blog.csdn.net/halfclear/article/details/77573956>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

实际文章里是这样的：
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/32927876/201304466-cc30e53e-7287-4139-9ccb-3ea5d5a4fbfb.png">

导出的pdf是这样的：
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/32927876/201304584-93d64218-a71d-444b-a225-57b60bfdf1b7.png">

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，截图对应的功能是使用浏览器的 PDF 打印方案，其实跟简悦没有太大的关系。

不过，一般来说含有代码段的页面效果都不是 100% 完美。

***

你可以试试 [PDF 高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)，这是导出效果

[Java中的Date和时区转换_halfclear的博客-CSDN博客.pdf](https://github.com/Kenshin/simpread/files/9989361/Java.Date._halfclear.-CSDN.pdf)
