### ISSUE TITLE
安卓手机上使用时，自动翻页功能在阅读模式下失效

### ISSUE THREAD

**Issue by Architect-yuan** [Kenshin/simpread#4703]
按照教程下载kiwi浏览器、安装简悦和东方永页机，最后可以正常导出到生产力工具，不进入阅读模式的话网页也可以自动翻页，然而一旦进入阅读模式，自动翻页功能就失效了，只能显示第一页的内容，导致没法完整导出网页内容。（试了几个论坛类网站都有这个问题：qzzn、地铁e族等）

**Comment by Kenshin** [comment]
emmm

估计 Kiwi 上可能没法使用翻页功能，因为从未考虑过这种场景，先确保在 PC 端可以正常使用。

翻页功能依赖于页面的结构，而 PC 与 手机端的结构大概率不一样。
