### ISSUE TITLE
重复授权notion，无法保存

### ISSUE THREAD

**Issue by 44maker** [Kenshin/simpread#4704]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 [<请填写你的地址l>](https://websec.readthedocs.io/zh/latest/intranet/windows/persistence.html#section-2)

授权到notion后打开网页阅读，选择保存到notion，显示要重新授权，然后跳转页面显示授权成功关闭页面，但是再次点击保存到notion又是跳出来重新授权，无限循环。
还有一个问题，就是能不能把每个标题旁边的链接删除，复制markdown的时候很麻烦
![image](https://user-images.githubusercontent.com/101875427/201473020-def249d7-cd21-459f-9c5b-dafdcce562cf.png)

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/101875427/201472921-93684c87-0927-4ef1-9681-f8c80409b344.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

在选项页中授权，如果无法授权到你需要的 Page 使用 https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358 中的快速解决方案。
