### ISSUE TITLE
简悦阅读列表，获取失败请确保output文件夹的存在

### ISSUE THREAD

**Issue by Steven7920** [Kenshin/simpread#4705]
https://simpread.pro/@id/reading/?token=<token>
通过这个链接替换为我的id和token后，打开的时候出出现获取失败请确保output文件夹的存在的情况，是哪里配置的问题吗。
在简悦开放平台已经打开了通过密码方式打开阅读列表
该如何解决

**Comment by Steven7920** [comment]
上面的问题解决了了。。我坚果云中创建了output文件夹后就可以打开了
想要把稍候读同步到手机端，就需要一直开着坚果云吗。因为我发现当我关闭坚果云和同步助手后，添加新的稍后读文章，并没有在手机端接收到

**Comment by Kenshin** [comment]
> 想要把稍候读同步到手机端，就需要一直开着坚果云吗

是的，细节 [请看这里](https://simpread.pro/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5?id=%e6%b3%a8%e6%84%8f%e4%ba%8b%e9%a1%b9)。

但如果使用 API 功能来收藏 URL 时（ e.g. [收藏助手](https://kb.simpread.pro/#/page/%E6%94%B6%E8%97%8F%E5%8A%A9%E6%89%8B) ）这个是服务器行为，则不需要，但这种方式有「弊端」，细节可以 [看这里](https://kb.simpread.pro/#/page/api%E5%BF%AB%E7%85%A7)。
