### ISSUE TITLE
对于在 Chrome 中打开的本地 HTML 文件，右键菜单无法调出简阅的阅读模式

### ISSUE THREAD

**Issue by shelmingsong** [Kenshin/simpread#4708]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 10 & MacOS 13**

- 浏览器版本 **Chrome 107.0.5304.107**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 本地HTML文件

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

对于在 Chrome 中打开的本地 HTML 文件，右键菜单无法调出简阅的阅读模式。

请问这个功能是目前不支持么，可以通过什么方式来实现这个功能。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

如图，Chrome 打开本地 HTML 文件时，没有简阅的阅读模式。

![image](https://user-images.githubusercontent.com/20255892/201517384-7831b08f-3a6d-4806-961d-b6f84b581bac.png)

**Comment by Kenshin** [comment]
嗨 [看下这个教程](https://simpread.pro/docs/#/%E6%89%93%E5%BC%80%E6%96%87%E6%9C%AC%E6%96%87%E4%BB%B6)

另外，这个功能在接下来的同步助手中有更方便的方案，预计下周发布。

建议订阅简悦的官方渠道 https://simpread.pro/subscribe 以及方便的话也一并订阅 Telegram Channel https://t.me/simpread 到时候我会在这里和官方渠道通知。

**Comment by shelmingsong** [comment]
@Kenshin 可以了，感谢！虽然右键菜单里还是没有，但浏览器应用栏上的简悦图标已可点击并进入阅读模式~
