### ISSUE TITLE
高级账户在第二台设备无法导入

### ISSUE THREAD

**Issue by zhoulukuan** [Kenshin/simpread#4711]
在macbook保存配置文件到网盘，而后在win10下导入配置文件失败，浏览器均为edge。
选择同步的配置文件导入后界面卡住，重启浏览器后无法打开偏好设置界面以及稍后读界面。卡住的页面如下：
![QQ截图20221114234328](https://user-images.githubusercontent.com/16110591/201703496-861f0c93-8052-453d-aef2-40b56634aea1.png)

想请问下是什么问题，如何解决呢？

**Comment by Kenshin** [comment]
嗨，我看你 Close 了，是解决了？

**Comment by zhoulukuan** [comment]
> 嗨，我看你 Close 了，是解决了？

是的，导入错了，重新根据教程来了一遍之后解决了问题，谢谢

**Comment by Kenshin** [comment]
okay 没问题就好~
