### ISSUE TITLE
关于同步助手的疑问

### ISSUE THREAD

**Issue by Mingmingshuai** [Kenshin/simpread#4715]
两个问题：

1. 配置导入到obsidian选项，使用local Rest API, 从obsidian 插件中复制的token，粘贴好，保存，显示保存成功，但是再次打开，会发现，token栏为空

**Comment by Mingmingshuai** [comment]
另外一个问题是站点集市，打开站点集市加载后，显示成功安装，但是站点集市栏显示无任何站点

**Comment by Kenshin** [comment]
关闭同步助手的自动同步，然后操作这些，完毕后再开启自动同步功能，并覆盖到本地。

不过，建议直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef
