### ISSUE TITLE
同步助手能否开机静默启动？

### ISSUE THREAD

**Issue by hozorro** [Kenshin/simpread#4716]
设置了随系统启动，每次启动后都会弹出界面，能否设置启动后不弹出界面，直接驻留系统栏？

**Comment by Kenshin** [comment]
嗨，看看下面的选项。

<img width="664" alt="image" src="https://user-images.githubusercontent.com/81074/202068523-2f5129d8-bde5-45cb-ae57-43047f296f32.png">

**Comment by hozorro** [comment]
唉，年纪大了。

**Comment by Kenshin** [comment]
😂 太逗了~
