### ISSUE TITLE
请给阅读助手增加代理功能

### ISSUE THREAD

**Issue by xtz136** [Kenshin/simpread#4717]
**请说明发生问题的环境**

- 操作系统: linux

- 浏览器版本: Chrome 107.0.1418.23

- 简悦版本: 2.2.0.520

- 发生问题的地址: https://hmarr.com/blog/go-allocation-hunting/

**请描述你的问题**

我这里的网络访问上诉网站有问题. 我已在浏览器安装 Proxy SwitchyOmega, 能正常打开这个页面.
问题是在稍后读里面进去这个文章的阅读模式失败, 当我设置系统代理后正常打开阅读模式.
我猜测是使用了助手的内置解析引擎, 但是助手无法获取这个页面导致失败了. 虽然开系统代理能解决问题, 但是有点繁琐.
所以能否给助手增加代理功能?

**Comment by Kenshin** [comment]
嗨，不用那么麻烦，你应该用了同步助手，如果是的话，直接使用读本地快照的方案就行了，如何设置 https://www.yuque.com/kenshin/simpread/wkswh7
