### ISSUE TITLE
稍后阅读提示解析错误

### ISSUE THREAD

**Issue by qszy1210** [Kenshin/simpread#4718]
刚购买, 体验稍后阅读, 就提示解析错误了. 页面链接如下 https://www.waerfa.com/simpread-review

这个链接是友站采访小哥的地址.

**Comment by Kenshin** [comment]
嗨，解决方案有两个：

1.  [阅读模式解析器](https://simpread.pro/docs/#/稍后读?id=阅读模式解析器)

2. [本地快照](https://www.yuque.com/kenshin/simpread/xr9wb8b4ap5rrzba) 方案，这是 [一站式教程](https://www.yuque.com/kenshin/simpread/wkswh7)
