### ISSUE TITLE
阅读模式报错

### ISSUE THREAD

**Issue by xmhwws** [Kenshin/simpread#4719]
阅读模式报错：

插件 代码段增强（包括：高亮 支持 CSDN 等特殊情况的代码段） 运行时出错，可以的话，请 [提交此问题](https://github.com/Kenshin/simpread/issues/new) 😁

链接：https://mp.weixin.qq.com/s/KwLpThyls24p5Zbc15p8_g

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
