### ISSUE TITLE
页面保存到本地的问题

### ISSUE THREAD

**Issue by woyaojizhu8** [Kenshin/simpread#472]
我原本用scrapbook x（旧Firefox）和webscrapbook（新Firefox）来保存网页，因为其他各种软件的网页剪辑效果都不如它们，包括简悦支持保存到的那些云笔记类服务，各种浏览器自带的保存网页功能，还有打印为PDF等。而且我喜欢保存到本地，不喜欢云笔记。但是用简悦开启阅读模式后就没法用webscrapbook保存，用火狐自带保存网页功能保存也是各种格式缺失错位。似乎简悦自定义了很多标签，非标准html标签，导致网页剪辑工具不认识？
简悦自带里面有一个保存为markdown是保存到本地的，如果能完整保存也可以，虽然要额外装个markdown编辑器。但是此功能又不能保存页面内资源比如图片。
所以能不能改进一下，让页面有办法较完整地保存到本地呢？

**Comment by Kenshin** [comment]
谢谢反馈，可以考虑这个功能。
目前，你可以使用这个办法实现你的要求 https://github.com/Kenshin/simpread/issues/473 

> 唯一的问题是，需要多点击两次鼠标。

**Comment by Kenshin** [comment]
此问题已经解决。

增加了 【离线下载】 插件 👉https://github.com/Kenshin/simpread/issues/508

我将关闭这个 issues 如有需要请重开~
