### ISSUE TITLE
同步助手增强导出功能求解惑

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4727]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **360极速浏览器 内核版本:95.0.463869**

- 简悦版本 **22.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 您好/泪奔我是在增强导出里面写了好几个导出语录2个是导出md，1个是导出html的，发现路径或者增强导出这里应该有4处导出，导出发现，最后只有1个位置导出了。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/118357167/202401019-0be04ab1-6e07-4478-846c-e5e974cd98a8.png)

**Comment by Kenshin** [comment]
嗨，这个功能是不会有什么问题的 😂 建议详细截图，如果使用了配置库方案，也请告知使用了哪种配置库。

PS：太能提 Issues 了~ 😂

**Comment by asong2022** [comment]
{"extension":"md", "path":"C:\\Users\\阿松\\Nutstore\\1\\SimpRead\\Logseq@simpread\\pages"}
{"extension":"html", "path":"C:\\Users\\阿松\\iCloudDrive\\我的知识库\\收集箱"}
{"extension":"md", "path":"C:\\Users\\阿松\\iCloudDrive\\iCloud~com~logseq~logseq\\pages"}

**Comment by asong2022** [comment]
Logseq 的md配置库

**Comment by asong2022** [comment]
意思是这个extension句子能不能在增强导出里面写好几句，每句都对应一个path

**Comment by asong2022** [comment]
增强导出能否写多个extension，每句都对应一个path，使得一次自动化可以导出很多个位置的md和html。
像我如下这样子的语句可以吗？
{"extension":"md", "path":"C:\Users\阿松\Nutstore\1\SimpRead\Logseq@simpread\pages"}
{"extension":"html", "path":"C:\Users\阿松\iCloudDrive\我的知识库\收集箱"}
{"extension":"md", "path":"C:\Users\阿松\iCloudDrive\iCloudcomlogseq~logseq\pages"}

**Comment by Kenshin** [comment]
哈，这个问题，我已经回复你了。

**Comment by Kenshin** [comment]
> 谢谢！！简悦配置好了！我就去学logseq了！

哈哈，没问题，有问题随时回来提 Issues

**Comment by asong2022** [comment]
谢谢。刚刚弄了多个增强导出的语句。。改成1个语句的导出还是不行了我只能重删了重头开始，再也不在增强导出里面写多个导出了。。顺便把导出位置放在icloud了。icloud导出的话是不是同步盘还是要用坚果云的？

**Comment by Kenshin** [comment]
> icloud导出的话是不是同步盘还是要用坚果云的？

不使用 API 功能的话，什么网盘都无所谓~

**Comment by asong2022** [comment]
> 

我按照您提示的，把同步放在坚果云，但导出文件和增强导出和logseq的库都放在icloud。现在就是我在手机上收藏，现在知道不会同步了，那会导致我电脑端里序号错乱吗？

**Comment by asong2022** [comment]
> > icloud导出的话是不是同步盘还是要用坚果云的？
> 
> 不使用 API 功能的话，什么网盘都无所谓~

我按照您提示的，把同步放在坚果云，但导出文件和增强导出和logseq的库都放在icloud。现在就是我在手机上收藏，现在知道不会同步了，那会导致我电脑端里序号错乱吗？

**Comment by Kenshin** [comment]
> 我按照您提示的，把同步放在坚果云，但导出文件和增强导出和logseq的库都放在icloud。现在就是我在手机上收藏，现在知道不会同步了，那会导致我电脑端里序号错乱吗？

只要使用 API 就必须要严格按照 https://www.yuque.com/kenshin/simpread/wkswh7#q78BG 的方式设置。

你的提到的方案是可以使用的，但通过 API 收藏的内容的快照会自动加入到 `坚果云/SimpRead/output` 里面。

至于序号的话，不会有问题的，因为读的同一个 `simpread_config.json`
