### ISSUE TITLE
拓展端发送邮箱和自动化命令不一致

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4728]
**请说明发生问题的环境**
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息
- 操作系统 **Windows**
- 浏览器版本 **360极速浏览器 内核版本:95.0.463869**
- 简悦版本 **22.0**
- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
> 自动化加了稍后读发送mail，但是使用过程中是标注了发mail，dd反而不会发mail，求帮助！！

**Comment by Kenshin** [comment]
在阅读模式中，使用快捷键 `d d` 加入稍后读时肯定是没问题的。

录屏或者确定是否可以重现？

**Comment by asong2022** [comment]
我已经重装了，现在暂时不会出现这样子的现象

**Comment by Kenshin** [comment]
okay 解决就好。

PS：你的动手能力其实不错的。👍

**Comment by asong2022** [comment]
谢谢！！您能否解惑一下#4727，这个是真的困扰我，，找不出原因就一直在原地打转

**Comment by Kenshin** [comment]
> 您能否解惑一下https://github.com/Kenshin/simpread/issues/4727，这个是真的困扰我，，找不出原因就一直在原地打转

这个问题解决了吧？一下子这么多 Issues … 😱 😂
