### ISSUE TITLE
简悦手机收藏如何在电脑稍后读中阅览

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4729]
https://simpread.pro/@asong ，请问下在手机收藏之后，会不会在电脑浏览器的稍后读中出现呢？我在手机收藏了，只能在这个网页上看见，只能在坚果云上看到，但是在简悦的稍后读里面没有找不到。

是不是要开启坚果云的一直同步功能才可以？

**Comment by Kenshin** [comment]
> 是不是要开启坚果云的一直同步功能才可以？

是的

教程可以看 https://www.yuque.com/kenshin/simpread/ieu1w6

**Comment by asong2022** [comment]
已经开启，谢谢您！！

**Comment by asong2022** [comment]
手机收藏的公众号文章，内容很多缺失，这个是我什么没设置好吗

**Comment by asong2022** [comment]
手机上有什么能不怎么丢失内容的剪藏方法呀

**Comment by Kenshin** [comment]
公众号的图片有图床限制，所以需要在 PC 端保存成本地快照的方式。

至于这个「问题」 [在这里](https://kb.simpread.pro/#/page/6371d376-34b6-4167-8cac-7e4ad4d614d7) 明确指出了。

**Comment by asong2022** [comment]
谢谢
