### ISSUE TITLE
稍后读如何设置成刚打开里面的文章先看到的是阅读模式

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4730]
稍后读如何设置成刚打开里面的文章先看到的是阅读模式，我现在打开稍后读的文章首先呈现的都是标注模式
![image](https://user-images.githubusercontent.com/118357167/202403089-32bf0c07-570d-4420-900d-80499553f091.png)

**Comment by Kenshin** [comment]
https://simpread.pro/docs/#/稍后读?id=选项页 可以设置。

**Comment by asong2022** [comment]
谢谢
