### ISSUE TITLE
如何清除同步助手的数据

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4731]
因为我实在太新手了，出现的问题太多，我想着能不能完全清除各个（浏览器的简悦、同步助手的、云同步的），重新安装来解决问题，昨天重装的时候发现，同步助手删除了文件夹，重新解压，数据还是原来的。

**Comment by Kenshin** [comment]
打开同步助手，在通用选项卡里面就有重置的功能。

**Comment by asong2022** [comment]
通用的重置重置不了啊

**Comment by Kenshin** [comment]
什么叫做重置不了？重置后有什么表现？

**Comment by asong2022** [comment]
可以了！！我昨天重置了忘记重启了

**Comment by Kenshin** [comment]
okay 没问题就好。不应该出现问题的~

**Comment by asong2022** [comment]
> okay 没问题就好。不应该出现问题的~

浏览器的简悦数据是如何重置的呢，是只要把配置文件重置了就算浏览器的简悦crx重置了？

**Comment by Kenshin** [comment]
> 浏览器的简悦数据是如何重置的呢，是只要把配置文件重置了就算浏览器的简悦crx重置了？

建议看看 [这个文档](https://simpread.pro/docs/#/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 以及 https://simpread.pro/docs/ 里面的你感兴趣的内容，大部分的疑问都会得到解决。

**Comment by asong2022** [comment]
> > 浏览器的简悦数据是如何重置的呢，是只要把配置文件重置了就算浏览器的简悦crx重置了？
> 
> 建议看看 [这个文档](https://simpread.pro/docs/#/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 以及 https://simpread.pro/docs/ 里面的你感兴趣的内容，大部分的疑问都会得到解决。

谢谢
