### ISSUE TITLE
自动保存后如何默认读取本地文件？

### ISSUE THREAD

**Issue by zhoulukuan** [Kenshin/simpread#4734]
按照教程配置了稍后读之后自动保存，但是发现在简悦页面里似乎读的不是本地缓存？如何更改成默认读取本地文件？
![image](https://user-images.githubusercontent.com/16110591/202477831-6b3296f1-4645-4321-ada6-85f392a89c4a.png)

ps：看了下在知识库方案里似乎有提到读取本地文件的内容，如果不需要和双链笔记联动，只需要读取本地文件，可以实现吗？

**Comment by Kenshin** [comment]
> 如果不需要和双链笔记联动，只需要读取本地文件，可以实现吗？

当然~

可以对比下你和这个教程 https://www.yuque.com/kenshin/simpread/wkswh7 在设置上的区别

或者直接使用 [配置库的剪藏包](https://www.yuque.com/kenshin/simpread/any457)
