### ISSUE TITLE
保存html问题

### ISSUE THREAD

**Issue by asong2022** [Kenshin/simpread#4737]
不适配的网站能否设置剪藏原格式html，手机能否设置剪藏原格式html到坚果云

**Comment by Kenshin** [comment]
> 不适配的网站能否设置剪藏原格式html

使用 https://github.com/Kenshin/simpread/discussions/1554 至于其它的阅读模式技巧，可以 [看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22read+mode%22)。

> 手机能否设置剪藏原格式html到坚果云

理论上就是原格式。

**Comment by asong2022** [comment]
> > 不适配的网站能否设置剪藏原格式html
> 
> 使用 #1554 至于其它的阅读模式技巧，可以 [看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22read+mode%22)。
> 
> > 手机能否设置剪藏原格式html到坚果云
> 
> 理论上就是原格式。

![image](https://user-images.githubusercontent.com/118357167/202694667-7e73a7ae-c6ff-451a-94e0-457a7cfee7c5.png)
这是什么原因呀

**Comment by asong2022** [comment]
怎么样做才能让稍后读里的文章显示已保存到本地这个图标呀

**Comment by asong2022** [comment]
![image](https://user-images.githubusercontent.com/118357167/202695128-1c1b4037-f0ac-42f1-83ee-a90218e10fce.png)
微信文章阅读模式是这样子，根本稍后读读不了呀

**Comment by asong2022** [comment]
> ![image](https://user-images.githubusercontent.com/118357167/202695128-1c1b4037-f0ac-42f1-83ee-a90218e10fce.png) 微信文章阅读模式是这样子，根本稍后读读不了呀

关闭纯粹模式就可以了！谢谢！

**Comment by Kenshin** [comment]
个别公众号的文章确实有这个问题，也确实可以使用这个方式解决。

PS：感觉文档看的差不多了！👍

**Comment by Kenshin** [comment]
你算是发 Issues 最密集的用户之一了，哈哈。

这种 QA 方式再多的提问都没问题。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by asong2022** [comment]
> 你算是发 Issues 最密集的用户之一了，哈哈。
> 
> 这种 QA 方式再多的提问都没问题。
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

我是开发模式安装插件的，也可以评价吗！，图片我裂开了。。

**Comment by Kenshin** [comment]
> 我是开发模式安装插件的

为什么是开发者模式，你没法使用 Chrome webstore 吗？

PS：只有通过 Chrome Webstore 安装后才能评价

**Comment by asong2022** [comment]
> > 我是开发模式安装插件的
> 
> 为什么是开发者模式，你没法使用 Chrome webstore 吗？
> 
> PS：只有通过 Chrome Webstore 安装后才能评价

是啊我进不去chrome的网站耶

**Comment by Kenshin** [comment]
哈哈，乌龙了~

不过，可以帮忙在 [Edge 评分](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 

 😂  🌚  💪

**Comment by asong2022** [comment]
> 哈哈，乌龙了~
> 
> 不过，可以帮忙在 [Edge 评分](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
> 
> 😂 🌚 💪

评价了！想问下您，我如果是看课程做笔记、看期刊看微信公众号推文做笔记的话想选一个软件当长远的笔记，logseq、obsidian、浮墨、思源、word等软件中的哪一个呢，您能从您的高度看我的使用环境给点建议吗

**Comment by Kenshin** [comment]
> 想问下您，我如果是看课程做笔记、看期刊看微信公众号推文做笔记的话想选一个软件当长远的笔记，logseq、obsidian、浮墨、思源、word等软件中的哪一个呢，您能从您的高度看我的使用环境给点建议吗

这个问题很「大」，先建议看下 https://sspai.com/post/71576 的内容，会帮助接下来的回复。

我一般不挑笔记工具，目前为止，Notion Logseq Obsidian 都在用。

- Notion → 项目管理，帮我管理简悦的项目。

- Logseq → 开放平台的相关文档都是通过它生成的 https://kb.simpread.pro/

- Obsidian → 我私人的知识管理

**Comment by asong2022** [comment]
> > 想问下您，我如果是看课程做笔记、看期刊看微信公众号推文做笔记的话想选一个软件当长远的笔记，logseq、obsidian、浮墨、思源、word等软件中的哪一个呢，您能从您的高度看我的使用环境给点建议吗
> 
> 这个问题很「大」，先建议看下 https://sspai.com/post/71576 的内容，会帮助接下来的回复。
> 
> 我一般不挑笔记工具，目前为止，Notion Logseq Obsidian 都在用。
> 
> * Notion → 项目管理，帮我管理简悦的项目。
> * Logseq → 开放平台的相关文档都是通过它生成的 https://kb.simpread.pro/
> * Obsidian → 我私人的知识管理
> 
> 虽然也有一些很好用的笔记，但目前上面三个足够用了，所以我并不会把时间都放在研究新笔记这个事情上。

谢谢！！我现在不知道如何把长视频利用好，因为看视频获取知识的性价比蛮低了，视频很多是花时间把他下载了却没有看过，很多视频讲的很好可惜耗时太长，不能快餐，也不知道怎么对他做笔记，以前没有了解笔记软件的时候还以为是在word上或者在notability上做笔记，现在刚接触这些软件，不知道哪个适合我对于知识库的整合。下午再去了解了一下，现在就是偏向于Zotero+obsidian或者logseq吧，不知道对于我的知识来源（我的知识来源：①线下学习②公众号③视频④电子书籍⑤b站等网站）来说，这样子的组合是不是可行。我不涉及项目，不分享的话，感觉学习多种笔记软件的成本有点大，暂时想把笔记做出我的知识库知识花园，那是不是应该选择obsdian或者logseq还是flomo、flowus呢？滴答清单印象笔记中的企业微信的同步方式还是很吸引我的。因为微信是我线上的获取信息的最重要的来源。

您的简悦，通过电报bot同步，能不能有企业微信的同步方式

**Comment by asong2022** [comment]
> > 想问下您，我如果是看课程做笔记、看期刊看微信公众号推文做笔记的话想选一个软件当长远的笔记，logseq、obsidian、浮墨、思源、word等软件中的哪一个呢，您能从您的高度看我的使用环境给点建议吗
> 
> 这个问题很「大」，先建议看下 https://sspai.com/post/71576 的内容，会帮助接下来的回复。
> 
> 我一般不挑笔记工具，目前为止，Notion Logseq Obsidian 都在用。
> 
> * Notion → 项目管理，帮我管理简悦的项目。
> * Logseq → 开放平台的相关文档都是通过它生成的 https://kb.simpread.pro/
> * Obsidian → 我私人的知识管理
> 
> 虽然也有一些很好用的笔记，但目前上面三个足够用了，所以我并不会把时间都放在研究新笔记这个事情上。

因为我是word用户，所以所有的md格式或者all in one的笔记对于我都算是新笔记，我10月发现了滴答清单发现了剪藏，发现了印象笔记的剪藏很好用，买了印象笔记的会员，但正如您说的一样，印象笔记的笔记方式就是再也不读，卡片堆积，客户端臃肿，但是基于微信剪藏公众号的功能真的让我心对。于是我便发现了singlefile和简悦，通过简悦认识了这些新笔记，所以我以前就觉得笔记记载word上复看的效果比较差，格式的结构要思考很久，和整合知识无关的操作太多，和知识无法达成笔记-源文件的协同。所以我想在这个月底选一个适合我需求的，能整合出我的知识库的一个软件或几个软件，真的不想让网络上这么好的资源这么好的学习材料白白成为过眼云烟，消失了。可是在我的视角下，我没有您这种高屋建瓴，到底哪个或几个软件组合，是能满足我这样子的需求长期可持续的。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4737#issuecomment-1320817022

我从来通过视频学习，只通过书籍（包括电子版）学习。

> 到底哪个或几个软件组合，是能满足我这样子的需求长期可持续的。

一般来说，我建议使用具有以下几点的产品：

1. 基于本地化的产品 → 隐私性会得到保障

2. 国外产品 → 不解释 😂 

3. 使用共有格式的 → 比如 `.md` `.html` 等，而不是私有格式

比如：Obsidian、Logseq 都能满足上面的需求。

**Comment by asong2022** [comment]
> 

谢谢！决定就obsidian或者logseq了，哪个和zotero更兼容就哪个了！

**Comment by Kenshin** [comment]
我不用 zotero，但我据我所知 Logseq 跟适合跟 zotero 配合。

**Comment by asong2022** [comment]
> 我不用 zotero，但我据我所知 Logseq 跟适合跟 zotero 配合。

谢谢！！
