### ISSUE TITLE
simpread sync无法在安卓版obsidian上启用

### ISSUE THREAD

**Issue by TheAnts2022** [Kenshin/simpread#4738]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **安卓

- 浏览器版本 **狐猴浏览器 可拓浏览器

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> simpread sync无法在安卓版obsidian上启用

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，此功能需要配合 [同步助手](https://simpread.pro/docs/#/Sync) 所以并不适合在 Android 等设备上使用。
