### ISSUE TITLE
会员三次激活

### ISSUE THREAD

**Issue by qingshanshi** [Kenshin/simpread#4739]
我重装系统前，没有退出登录，只有第一次导出的"simpread-key-内含UID，请勿遗失.josn"，并在重装系统以后通过该文件恢复了会员资格。但是这个会占用三台设备吗？因为重装系统，也无法再退出了。

**Comment by Kenshin** [comment]
> 只有第一次导出的"simpread-key-内含UID，请勿遗失.josn"，并在重装系统以后通过该文件恢复了会员资格。

不要通过这个文件恢复高级账户，这是错误的。这个文件里面包含了你的 UID 与 License 仅此而已。

如果知道自己的 UID 后，使用 https://www.yuque.com/kenshin/simpread/pkq3d1 恢复。

> 但是这个会占用三台设备吗？因为重装系统，也无法再退出了。

如果是同一个设备，应该没问题。另外，当某个设备登录超过 14 天会自动踢出。
