### ISSUE TITLE
今天就使用了一次插件后，就开始报错配置文件

### ISSUE THREAD

**Issue by doggyone** [Kenshin/simpread#4740]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/50585454/202843637-937ef962-f021-426e-a181-e558e18a727d.png">
- 重装简悦导入配置无法解决问题
- 重装简悦导入两天前（最近的一次使用时）的配置文件，依旧出现问题

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/3165 提到的方案，只要是使用了同步助手以及坚果云，并一直开着坚果云的话，基本上都能解决。

**Comment by doggyone** [comment]
你好，尝试了使用最近几次的坚果云备份的历史版本，重装导入后均无法解决，已经将配置文件发送到 #3165 中所提到的邮箱中。

**Comment by Kenshin** [comment]
okay 我明天确认完回复你。

**Comment by doggyone** [comment]
请问有后续的解决方案或者能告知一下问题出现的原因吗？




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月19日(星期六) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 今天就使用了一次插件后，就开始报错配置文件 (Issue #4740)





 
okay 我明天确认完回复你。

**Comment by Kenshin** [comment]
嗨，问题已经修复，把正确的配置文件给你了。

重新安装简悦 → 导入正确的配置文件 → 开启自动同步 → 并覆盖本地配置文件

***

发生问题的是最后（最新）的稍后读，我看到应该是通过 API 加入的，你是通过什么途径加入的？

**Comment by doggyone** [comment]
如果是 API 方式的话，应该是通过 iOS 端的捷径的方式加入的。&nbsp;


Charlez
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2022年11月21日(星期一) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 今天就使用了一次插件后，就开始报错配置文件 (Issue #4740)





 
嗨，问题已经修复，把正确的配置文件给你了。
 
重新安装简悦 → 导入正确的配置文件 → 开启自动同步 → 并覆盖本地配置文件
 
 
发生问题的是最后（最新）的稍后读，我看到应该是通过 API 加入的，你是通过什么途径加入的？

**Comment by Kenshin** [comment]
> 如果是 API 方式的话，应该是通过 iOS 端的捷径的方式加入的。

okay 我研究下这个 API

PS：你可以进入到 https://github.com/Kenshin/simpread/issues/4740 回复，用 Email 回复也没问题，但格式比较奇怪 😂

**Comment by doggyone** [comment]
好的👌不好意思，以为还是在通过 help 邮箱沟通

**Comment by Kenshin** [comment]
哈哈，小事情~ （因为有经验了，所以估计你应该不知道可以在 Issues 回复 😂
