### ISSUE TITLE
同步助手运行不了，运行可执行文件后只能短暂的在任务栏看到图标，过一会就自己消失了

### ISSUE THREAD

**Issue by linxialiuyu** [Kenshin/simpread#4741]
- 操作系统 **Windows 11 家庭中文版  22H2  22621.819

- 简悦同步助手版本  1.1.2

- 发生问题的地址  同步助手

![image](https://user-images.githubusercontent.com/55418956/202884824-8232a190-533e-41cf-abb4-d1bf54e3fe60.png)

**Comment by Kenshin** [comment]
😂

很奇怪的问题，消失后什么提示都没有么？通过任务管理器也差不到同步助手的进程吗？

我看你的截图似乎安装了某些杀毒 or 防火墙，试试暂时关闭它们。

**Comment by linxialiuyu** [comment]
没有提示，就是微软自带的安全中心，也都关了，还是一样……任务管理器也查不到

**Comment by Kenshin** [comment]
@binsee 

帮忙看看这个问题 😂
