### ISSUE TITLE
关于Markdown 模板辅助增强的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4742]
安装后需要开启下图所示的选项才可使用 里面提到的 「是否启动markdown。。。」在哪里设置，配置页找了好久没有找到 @Kenshin

_Originally posted by @xiang578 in https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-4184848_

**Comment by Kenshin** [comment]
@xiang578

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

同时更新了 [说明文档](https://github.com/Kenshin/simpread/discussions/3725)，看下图所示

<img width="880" alt="image" src="https://user-images.githubusercontent.com/81074/202887091-9c2de9df-b6c1-46ac-9912-e9ae9e30cc6b.png">

**Comment by xiang578** [comment]
感谢

**Comment by xiang578** [comment]
还有一个问题，也是和模板辅助增强相关的。

目前，我在 mac 上装有简悦同步助手，logseq 中喜欢以 md 格式保存文件。
通过浏览器访问 `http://localhost:7026/unread/100?embed=logseq` 阅读和高亮，标注数据会以我定义的格式保存到 logseq。
但是，如果换成在稍后读中标注，就不会自动导入到logseq中。如果在自动化里面，设置标注后导出 md 文件，保存文件就不是我想要的格式。

所以想问一下，自动化中标注后导出  md 文件，可以使用 markdown 模板辅助来定义模板吗？

**Comment by Kenshin** [comment]
> 如果换成在稍后读中标注，就不会自动导入到logseq中

在稍后读的阅读模式下标注是无法触发这个自动化的。

> 自动化中标注后导出 md 文件，可以使用 markdown 模板辅助来定义模板吗？

可以的，使用 [将标注以 MD 2.0 模板形式导出](https://github.com/Kenshin/simpread/discussions/4321) 即可。

***

其实你也可以使用配置库方案，里面专门有 [Logseq 配置包](https://github.com/Kenshin/simpread/discussions/4531#discussioncomment-3844896)

**Comment by xiang578** [comment]
> > 如果换成在稍后读中标注，就不会自动导入到logseq中
> 
> 在稍后读的阅读模式下标注是无法触发这个自动化的。
> 
> > 自动化中标注后导出 md 文件，可以使用 markdown 模板辅助来定义模板吗？
> 
> 可以的，使用 [将标注以 MD 2.0 模板形式导出](https://github.com/Kenshin/simpread/discussions/4321) 即可。
> 
> 其实你也可以使用配置库方案，里面专门有 [Logseq 配置包](https://github.com/Kenshin/simpread/discussions/4531#discussioncomment-3844896)

感谢我参考一下你给的链接。
