### ISSUE TITLE
我的简悦在谷歌浏览器每次点完保存为离线HTML时，总是显示图片转换已完成，稍后下载。然后就没有下文了。

### ISSUE THREAD

**Issue by visitor896** [Kenshin/simpread#4743]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by visitor896** [comment]
操作系统 ：Windows 10

浏览器版本：MicroSoft Edge 107.0.1418.52 (正式版本) (64 位)

简悦版本：2.0.0

发生问题的地址：https://mp.weixin.qq.com/s?__biz=MzUyMzUyNzM4Ng==&mid=2247486772&idx=1&sn=1e126c9f2c9610724cb0166c986c2ae5&chksm=fa3a7881cd4df197f61ef0b23bda2f49569fd010196a6b2ff9075a745de57c87c860de317f24&scene=21#wechat_redirect

**Comment by Kenshin** [comment]
嗨，这个页面的图片太大了，导致离线 HTML 导出失败。（这是我见到的唯一例子）...

解决方案：

1. 使用 [assets + md 方案](https://github.com/Kenshin/simpread/discussions/4041)

2. 关闭同步助手的增强导出，仍使用离线 HTML，然后通过浏览器导出。

   简悦（扩展端） → 选项页 → 服务 → 增强导出，关闭下图的选项。

   ![image](https://user-images.githubusercontent.com/81074/202889513-bdfc65d1-77c0-4cef-9954-390afbebfe33.png)

**Comment by visitor896** [comment]
依然不行😂

在 2022-11-20 14:44:10，"Kenshin Wang" ***@***.***> 写道：


嗨，这个页面的图片太大了，导致离线 HTML 导出失败。（这是我见到的唯一例子）...

解决方案：

使用 assets + md 方案

关闭同步助手的增强导出，仍使用离线 HTML，然后通过浏览器导出。

简悦（扩展端） → 选项页 → 服务 → 增强导出，关闭下图的选项。

**Comment by visitor896** [comment]
里面的图片有很多是动图

在 2022-11-20 14:44:10，"Kenshin Wang" ***@***.***> 写道：


嗨，这个页面的图片太大了，导致离线 HTML 导出失败。（这是我见到的唯一例子）...

解决方案：

使用 assets + md 方案

关闭同步助手的增强导出，仍使用离线 HTML，然后通过浏览器导出。

简悦（扩展端） → 选项页 → 服务 → 增强导出，关闭下图的选项。

**Comment by Kenshin** [comment]
> 依然不行😂

确实....

但我使用 [assets + md](https://github.com/Kenshin/simpread/discussions/4041) 方案成功导出了。
