### ISSUE TITLE
阅读模式将代码段顺序搞错了

### ISSUE THREAD

**Issue by xmhwws** [Kenshin/simpread#4744]
链接：https://mp.weixin.qq.com/s/0i2y_1WHryXhGPqiltwDiw

阅读模式将代码段顺序搞错了：

![1668953982576](https://user-images.githubusercontent.com/42903751/202907370-a741e671-d5fd-4b25-bedc-22b6455c7428.jpg)

原文：

![image](https://user-images.githubusercontent.com/42903751/202907450-89401bce-16f3-4030-82c6-0810521ff0b4.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
