### ISSUE TITLE
首次购买，无法绑定高级账户

### ISSUE THREAD

**Issue by Solitario119** [Kenshin/simpread#4749]
今天上午购买了高级账户，按教程绑定license，一直报错”**一个账户仅能绑定一个密钥**“，但之前从未绑定过

**Comment by Kenshin** [comment]
嗨，请问是什么途径购买的？

把购买凭证截图（一般是支付宝付款，并带有详细付款信息）以及你的兑换码发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4749

然后在这里告诉我，我确认下~

**Comment by Solitario119** [comment]
你好，邮件已经发送啦
