### ISSUE TITLE
自动化以 textbundle 保存失败

### ISSUE THREAD

**Issue by xiang578** [Kenshin/simpread#4750]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

macos，同步助手 1.1.3

**请描述你的问题**

使用同步助手 1.1.3，新网页加入稍后读后，自动化以 textbundle 格式保存出错。
比如这个网页，https://zhuanlan.zhihu.com/p/356960700 ， 看 log 错误信息是，`write: textbundle image faild https://pic2.zhimg.com/v2-ce0805ae163cb19513c071c830e2912d_r.jpg` `error: {}`

从本地文件来看，这张报错的图片已经下载下来，但是 markdown 文本没有保存。

<img width="960" alt="image" src="https://user-images.githubusercontent.com/12624910/203279595-4b645a84-213e-44d0-9ac6-5b62164a3979.png">

**截图**
今天下午添加的 10 多篇文章都失败了。

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/12624910/203279047-5fb3d9ef-c4fa-4d2d-8a89-38939d7852a8.png">

**Comment by Kenshin** [comment]
嗨，确实如此。

我已修复这个问题，请重新下载你需要的同步助手。（版本号没有更改，因为2个版本间隔时间太短了）
