### ISSUE TITLE
obsidian 批注无法导入

### ISSUE THREAD

**Issue by hacker-jerry** [Kenshin/simpread#4752]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Mac M1**

- 浏览器版本 **Vivaldi | 5.5.2805.38 (Stable channel) (arm64)**

- 简悦版本 **2.2.0**

- 发生问题的地址 [知乎](https://www.zhihu.com/question/568189518/answer/2770082248)

按照教程设置好增强导出的快捷键后，只显示已导出，但obsidian内无内容。

如图
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/57279550/203315510-be10517f-5442-43df-b80d-d48439efd42d.png">

控制台输出如下：

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/57279550/203315712-589bf474-a5b0-452d-a841-03fa7ee3e131.png">

设置如下：
<img width="816" alt="image" src="https://user-images.githubusercontent.com/57279550/203315928-2a2b8b95-c502-4d7a-898d-9627b6cbcd35.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/57279550/203316035-10beaaed-aadb-4a59-85cc-a5f8bf60e338.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/57279550/203316095-cd519f3c-f8a3-44de-961f-cce49eeb5dce.png">

**Comment by Kenshin** [comment]
嗨。建议直接使用配置库方案 https://github.com/Kenshin/simpread/discussions/4531#discussioncomment-3844881
