### ISSUE TITLE
md + assets 无法导出

### ISSUE THREAD

**Issue by richex-cn** [Kenshin/simpread#4756]
**请说明发生问题的环境**

- 操作系统 **Windows**

- 浏览器版本 **Chrome 107.0.5304.107**

- 简悦版本 **2.2.0.520**

- 同步助手 **1.1.3**

**请描述你的问题**

1. **导出 md + assets 插件**的**设置导出根目录**选项留空。

    ![Snipaste_2022-11-23_10-04-51](https://user-images.githubusercontent.com/25103518/203456455-6931213a-65ec-4ec0-9292-9846de472680.png)

2. **同步助手 - 导出 - 路径**已填写路径，例如：`d:\path\to\SimpRead\output`，且本地已存在该目录，参考文档 
https://github.com/Kenshin/simpread/discussions/2958

    ![Snipaste_2022-11-23_10-12-07](https://user-images.githubusercontent.com/25103518/203456977-42e2c9e0-cf9c-4a48-8ec8-53e35fdef077.png)

3. 在阅读模式使用**导出 md + assets**，提示保存成功，但上述配置的 `output` 目录为空。

    ![Snipaste_2022-11-23_10-00-16](https://user-images.githubusercontent.com/25103518/203456053-a4b1229a-e48d-455c-82e3-81c2b3593b4b.png)

---

另外，考虑到用户体验建议尽量能做到开箱即用，按照同步助手的提示，在不进行任何路径配置的情况下，能够正常运行是最好的，但目前不论是否设置路径，仍然无法正常导出。

![sp20221123_100855_385](https://user-images.githubusercontent.com/25103518/203457102-93861ec5-ce3f-4394-9c05-833b10c6059e.png)

**Comment by Kenshin** [comment]
1. `d:\path\to\SimpRead\output` 此路径是否存在？

2. 在第一个红框设置后，**仍需要訾呵第二个红框中设置**，细节 https://github.com/Kenshin/simpread/discussions/2958#discussioncomment-2713824

***

> 考虑到用户体验建议尽量能做到开箱即用，按照同步助手的提示

不设置路径打算保存到什么地方？你有什么好建议？

**Comment by richex-cn** [comment]
1. 路径是存在的，这里建议同步助手能够自动创建目录应该会更好用。
    
    ![Snipaste_2022-11-24_17-43-02](https://user-images.githubusercontent.com/25103518/203751276-bd9a325c-037e-4ed4-b582-432a08cbcb28.png)

2. 上图是我尝试的设置，在浏览器中导出 md + asset 仍然不工作。
    另外在**路径**中尝试设置了带双反斜杠 `\\` 的路径  `d:\\path\\to\\SimpRead\\output` 也是如此。

3. 按照同步助手**导出 - 路径**输入框的 placeholder 提示：**默认在同步位置下的 output 文件夹，可更改为任意位置。**假设我设置**同步文件夹路径**为 `d:\path\to\SimpRead`，则当**导出 - 路径**选项不填时，路径默认应该是 `d:\path\to\SimpRead\output`，如果不填无法工作，那么 placeholder 的提示也许有误或存在歧义。
    增强导出的 placeholder 是“**默认所有的文件都在 output 文件夹内**”也是如此。

**Comment by Kenshin** [comment]
> 同步助手能够自动创建目录应该会更好用。

会考虑的。

> 问题2

试试把 path 不设置值 `{"extension":"textbundle", "path":""}` 如果正常的话，会保存到  `d:\path\to\SimpRead\output\textbundle` 文件夹下。

> 问题3

我测试了下 不设置 output 文件夹，是没问题的。（下图所示）

<img width="679" alt="image" src="https://user-images.githubusercontent.com/81074/203762821-7c71bfee-7a9d-41fc-9f1b-9e8b320b22cc.png">

至于 Win 的话，我找人帮忙测试下。

**Comment by onepieceYJ** [comment]
测试了三种情况：
- path 不加内容 {"extension":"textbundle", "path":""}
![L WDT_H)67XPG_RHQW0`U9F](https://user-images.githubusercontent.com/118979884/203778319-52a800db-0450-4841-a55e-ba2c74c10022.png)

- path有路径信息
![3$GP)1O@TQ9O48V3XTA%IZD](https://user-images.githubusercontent.com/118979884/203778413-b0ed723f-f41f-49cb-bfad-c2cd1d117352.png)

- output 不写值 
![IFXU` PNA~D3QO(HAYT HB4](https://user-images.githubusercontent.com/118979884/203778453-3c694291-0232-4eb5-bba7-146278e20a98.png)
均可以导出md+assert到output文件夹

![UBJS$WKSL 3YIUN1)Z5D%NA](https://user-images.githubusercontent.com/118979884/203779078-bf2275da-2eab-4f7d-a0f0-007d3faf4a4a.png)

![CD_R{Q7$5M4_B6MZ@I7@{U4](https://user-images.githubusercontent.com/118979884/203778886-d21483e0-84ea-4198-983b-14d37a3aeb04.png)

**Comment by Kenshin** [comment]
@onepieceYJ 

第一种方式应该在 output 下面建立 textbundle 文件夹吧？

**Comment by onepieceYJ** [comment]
不好意思疏忽了，重新测试了一下，path不加内容还是能默认导出到output
![20221124203657(1)](https://user-images.githubusercontent.com/118979884/203786675-9703cd66-e234-4758-8df3-c98be8648421.png)

**Comment by Kenshin** [comment]
@onepieceYJ 

emmm 跟 Mac 的结论不太一样… 你试试修改为任意一个非 output 目录，是否成功？

**Comment by onepieceYJ** [comment]
![O9YJ8R0DU K4P DQ@3549$3](https://user-images.githubusercontent.com/118979884/203880608-f5270418-0e03-46ef-8980-a46efe4dc571.png)
![8_ LMX1@15JL3ZVS66ZNKED](https://user-images.githubusercontent.com/118979884/203880761-1703c0ec-0eb4-404f-8f2a-0bee044cdd59.png)
还是不能保存到textbundle下

**Comment by Kenshin** [comment]
@onepieceYJ 

我的意思是在 `path` 设置目录，看看能否正常导入到 `path` 设定的目录下。

**Comment by onepieceYJ** [comment]
![20221125194111](https://user-images.githubusercontent.com/118979884/203978430-14698099-fcfc-45a2-86a5-2956eb427c42.png)
![${ 7L@A~31ULY5I FJNY%(O](https://user-images.githubusercontent.com/118979884/203978879-7250c751-7a75-4784-8c1d-183e37845493.png)

这样设置既不能导入到textbundle下，在output里也找不到

**Comment by Kenshin** [comment]
@onepieceYJ 

emmmm 有点问题…我研究下，先重开这个 Issues

**Comment by richex-cn** [comment]
花了点时间做了些尝试，问题原因竟然和高级账户授权有关，点击**仅授权当前设备**并重启浏览器后恢复正常。具体见如下视频演示：

https://user-images.githubusercontent.com/25103518/204107941-193a4e92-98b1-4b29-998b-5fbd969750c4.mp4

> 视频中导出 Markdown 提示不是高级账户时，就是出现该问题描述的导出 md + assets 无法工作的时间，视频在录制时忘记点击进行演示了。

所以目前这个 issue 的问题对我而言已经解决，有几个点需要作者处理了：

1. 视频演示中点击“仅授权当前设备”后，多次刷新仍然无法进入阅读模式。
2. 导出 md +assets 似乎没有像导出 Markdown 那样的高级账户授权检测，而是直接给出保存成功的提示。

另外上面讨论的导出 textbundle 问题，在成功解决这个 md + assets 问题后，不论是否设置 path 或者导出路径，都能够正常导出。

**Comment by Kenshin** [comment]
> 视频演示中点击“仅授权当前设备”后，多次刷新仍然无法进入阅读模式。

因为这个 URL 多开了，重启浏览器就可以了。

> 导出 md +assets 似乎没有像导出 Markdown 那样的高级账户授权检测

okay 谢谢反馈，我记录下。

> 上面讨论的导出 textbundle 问题，在成功解决这个 md + assets 问题后，不论是否设置 path 或者导出路径

**也就是当 `path` 设置路径后，可正常的导入到对应的目录中，而不是仍然导出到 output 文件夹？**

**Comment by richex-cn** [comment]
> URL 多开了，重启浏览器

建议优化这类情况，或者只是给个重启浏览器的提示也好，否则当用户遇到这种情况如果没有想到重启浏览器，会直接影响到使用体验和效率。

> textbundle 测试结果如下：

| 同步文件夹路径          | 导出路径   | 增强导出                                        | 结果                             |
| ----------------------- | ---------- | ----------------------------------------------- | -------------------------------- |
| `"d:\path\to\SimpRead"` | `""`       | `{"extension":"textbundle", "path":""}`         | `d:\path\to\SimpRead\textbundle` |
| `"d:\path\to\SimpRead"` | `"d:\tmp"` | `{"extension":"textbundle", "path":""}`         | `d:\tmp\textbundle`              |
| `"d:\path\to\SimpRead"` | `""`       | `{"extension":"textbundle", "path":"d:\\tmp"}`  | `d:\tmp`                         |
| `"d:\path\to\SimpRead"` | `"d:\tmp"` | `{"extension":"textbundle", "path":"d:\\tmp1"}` | `d:\tmp1`                        |

**Comment by Kenshin** [comment]
> 建议优化这类情况，或者只是给个重启浏览器的提示也好，否则当用户遇到这种情况如果没有想到重启浏览器，会直接影响到使用体验和效率。

已经在 Todo 里面了。

另外看下图所示应该是正确的，谢谢测试。

至于你说 assets + md 验证的事情，我一会确认下，会直接更新插件版本的，会在这里通知你~

**Comment by Kenshin** [comment]
补充下：在发布功能前你做的这些我都已经测试过，但基于本地环境的产品毕竟跟 Online 产品的使用环境区别还是很大的。

所以，当用户发生问题后我都会一一确认。

**Comment by Kenshin** [comment]
md + assets 已经升级到 1.1.1 增加了权限认证。（跟 Markdown 模板辅助增强一致）

可以使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 升级。

我关闭这个 issues 了。
