### ISSUE TITLE
小书签无法修改稍后读标题

### ISSUE THREAD

**Issue by NNGTHB** [Kenshin/simpread#4758]
![动画](https://user-images.githubusercontent.com/115760745/203467678-7fb06000-e9d0-4c6d-bb15-c0050fcb2296.gif)
通过同步助手中的小标签将页面加入稍后读时，稍后读标题无法被修改。

**Comment by Kenshin** [comment]
emm 确实如此 😂 我记录下。

修复会会通知你，不过只能是下个同步助手了。（昨天刚发的新版

**Comment by NNGTHB** [comment]
好的感谢😀

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

**修复了小书签无法修改标题的问题**
