### ISSUE TITLE
稍后读无法解析阅读模式

### ISSUE THREAD

**Issue by IOSure** [Kenshin/simpread#4759]
@Kenshin 

![image](https://user-images.githubusercontent.com/6913871/118751919-bf5ac680-b894-11eb-9395-d7118b0cb7eb.png)

![image](https://user-images.githubusercontent.com/6913871/118751923-c1bd2080-b894-11eb-8886-08778c746589.png)

_Originally posted by @doersa in https://github.com/Kenshin/simpread/issues/2165#issuecomment-843714496_

<img width="572" alt="Screenshot 2022-11-24 at 05 23 08" src="https://user-images.githubusercontent.com/38939899/203650612-1b4e472e-3843-4909-8eb2-d47efe382b6a.png">

报错就是如同上图。

具体出现问题的网页时B站和Obsidian中文论坛。
下面是参考两个网页：
B站：https://www.bilibili.com/read/cv19825216
Obsidian中文论坛：https://forum-zh.obsidian.md/t/topic/11439/3

其它网页没有出现上图问题，而且在稍后读中也可以进入阅读模式。 
还有，我都是内容都导出到了本地html，用浏览器打开也没有问题。

谢谢！

**Comment by Kenshin** [comment]
嗨，解决方案有两个：

1. 打开 [稍后读的内置解析](https://simpread.pro/docs/#/稍后读?id=阅读模式解析器)

2. 使用 [知识库方案](https://www.yuque.com/kenshin/simpread/lglfy2)（比方案一好很多）
