### ISSUE TITLE
增加对百度 百家号 的支持

### ISSUE THREAD

**Issue by Mlearn** [Kenshin/simpread#476]
发现简悦在百家号的文章中开启之后，不管如何调整字体的大小，正文字体都不会有变化，字体很小。只有文章标题会变化。
能增加对百家号的适配支持吗？

![GIF](https://user-images.githubusercontent.com/7379015/56105239-d6b87e80-5f6d-11e9-9baa-e47e97099374.gif)

谢谢。

**Comment by Kenshin** [comment]
我这边没有这个问题，比如你访问的页面 https://baijiahao.baidu.com/s?id=1630614143904040181&wfr=spider&for=pc

![image](https://user-images.githubusercontent.com/81074/56105636-cdc8ac80-5f6f-11e9-98ab-3ecfa04b9a50.png)

可能是某些「变种浏览器」或其它扩展引起的，你可以在隐身模式下试试。

**Comment by Mlearn** [comment]
奇怪，我用的是官方 Chrome 浏览器。试了隐身模式下也不行。

**Comment by Kenshin** [comment]
emmm 你全局设置了什么字体么？
另外，试试其它页面也有同样的问题吗？

**Comment by Mlearn** [comment]
全局字体？chrome 内的吗？没有啊。
令，所有百度百家号的文章都是这个问题。
从百度首页下拉推荐的文章中点进去看的，开启简悦都是这样的。

**Comment by Kenshin** [comment]
我随机测试了几篇

https://baijiahao.baidu.com/s?id=1617198926017201140&wfr=spider&for=pc
http://baijiahao.baidu.com/s?id=1603979765801588490&wfr=spider&for=pc
http://baijiahao.baidu.com/s?id=1597050944905910801&wfr=spider&for=pc

均未出现你说的问题。

**Comment by Mlearn** [comment]
奇了怪了。。。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

因为增加了新的词法分析引擎，所以不太依赖与适配列表了，我关闭此问题了，如有问题再重新开启。
