### ISSUE TITLE
同步助手启动报错

### ISSUE THREAD

**Issue by L-TheShy** [Kenshin/simpread#4760]
- 操作系统 **e.g.  Windows 10*

- 浏览器版本 **e.g.edge107.0.1418.56 **

-同步助手版本 **1.1.3**

- 发生问题的地址 <请填写你的地址l>
- 
同步助手下载后每次启动电脑会报错

![image](https://user-images.githubusercontent.com/75104030/203662797-91b9cba5-b005-4cf1-8763-b78cc2a70655.png)

**Comment by Kenshin** [comment]
请不要解压缩到临时目录。

**Comment by L-TheShy** [comment]
我是解压到d盘的 但是这个报错在c盘 我按照这个路径去找才知道是同步助手报错的

**Comment by Kenshin** [comment]
emmm 这就奇怪了

解压缩后，运行就报这个错误吗？

**Comment by L-TheShy** [comment]
解压缩不报错 解压出来的exe文件也能运行 就是会在c盘临时文件里面自动创建一个同步助手一样的文件夹 然后电脑一开机c盘那个就报错  c盘中的temp之前强制删除过一次  然后下载新版同步助手后 又出现在temp里了

**Comment by Kenshin** [comment]
试试 32 位的。

另外，暂时不要使用「开机自启」的功能。

**Comment by L-TheShy** [comment]
ok
