### ISSUE TITLE
稍后读的标注在本地配置文件中存在缺失

### ISSUE THREAD

**Issue by CanoNandMacaroN** [Kenshin/simpread#4765]
用简悦做外刊精读笔记时常会遇到：已经标注过的内容，在稍后读页面刷新后消失的问题。利用Ob同步插件导出到Obsidian的标注一开始是全的，随着刷新再用插件同步会丢失很多标注。查看本地配置文件后发现确实没有记录进去。是由于标注的内容太短（主要是单词和短语）还是使用了自动同步的问题？
现在不得不先自动化导出标注来存一份md备份了，不然一刷新就会丢内容😭。

**Comment by Kenshin** [comment]
emmm 很少见的问题。

> 是由于标注的内容太短（主要是单词和短语）

只能说有这个情况（但也极少见。

***

建议试试在 Obsidian 中标注，看看是否仍有这个问题？

**Comment by Kenshin** [comment]
> 现在不得不先自动化导出标注来存一份md备份了，不然一刷新就会丢内容

emmm 这是什么意思？我没太看懂你的做法。

**Comment by CanoNandMacaroN** [comment]
> > 现在不得不先自动化导出标注来存一份md备份了，不然一刷新就会丢内容
> 
> emmm 这是什么意思？我没太看懂你的做法。

就是在自动化设置一下加入标注自动时导出markdown文件的选项，这样可以确保我做完整篇标注后有一个存档。因为我主要用Obsdian里面的简悦插件直接同步，有时候不小心同步一次，就会少很多内容，方便重新标注。。。

**Comment by CanoNandMacaroN** [comment]
> emmm 很少见的问题。
> 
> > 是由于标注的内容太短（主要是单词和短语）
> 
> 只能说有这个情况（但也极少见。
> 
> 建议试试在 Obsidian 中标注，看看是否仍有这个问题？

Obisian里面标注经常会有标注显示不全的问题，就是明明标注过了，但是再次内部链接打开就是没有这个标注，但是打开稍后读页面查看确实是有标注的，所以我一般在稍后读里标注。
见图：
![image](https://user-images.githubusercontent.com/93785833/203766808-c7d0a77a-4a7d-4563-97f4-de72ece3e7f5.png)
这里我标注了walmart，但是在Obsidian里看不见，稍后读里可以看见😢

吞标注这个问题我比较频繁遇见，基本上每篇笔记都有，我总结下来的就是，标注单词，同时标注里的注释越长越容易写不进配置文件（有时候单词下面会写很长的注释（相关用法、短语、例句），一般这种就很容易挂掉。）🥺

**Comment by Kenshin** [comment]
> 有时候单词下面会写很长的注释（相关用法、短语、例句）

在遇到这个问题时，把配置文件、HTML、URL 都发给我。

目前我得到的用户反馈类似问题的结论是：因为英文单词的词频比较高，所以当较短文字时确实存在这个情况。（不是每个都会出现，还要跟具体的页面结构有关系。

**Comment by CanoNandMacaroN** [comment]
> > 有时候单词下面会写很长的注释（相关用法、短语、例句）
> 
> 在遇到这个问题时，把配置文件、HTML、URL 都发给我。
> 
> 目前我得到的用户反馈类似问题的结论是：因为英文单词的词频比较高，所以当较短文字时确实存在这个情况。（不是每个都会出现，还要跟具体的页面结构有关系。

👌

**Comment by HopeLHP** [comment]
[Html有标注+稍后读没标注.zip](https://github.com/Kenshin/simpread/files/11522047/Html.%2B.zip)
url：http://www.gov.cn/zhengce/zhengceku/2023-04/03/content_5749824.htm
![image](https://github.com/Kenshin/simpread/assets/70339118/12c7a586-920b-4eca-ad53-d69c6a7f11f5)
接这个issue，这个带备注的标注永远无法再稍后读中同步，html有，稍后读没有，ob插件里面的内部稍后读界面却有（有时候会没有）。很多标注都会有这种情况，稍后读扩展显示有这个标注，但原文里不会链接这个标注，html里面有。可能稍后读里面数据的来源不是html。
另外上述的url，好像进入阅读模式会出现双倍内容呈现，就是文章出现了两遍。

**Comment by Kenshin** [comment]
@HopeLHP 

标注的定位是根据页面的内容而检索的，如果页面内容改变的话，定位就会消失。

所以：

1. **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰，重新找个页面进行标注，看是否可以稳定复现。
2. 在简悦导出的 HTML 中标注，一般都可以避免。
3. 如果原页面使用了 Live Editor 改变页面结构，也会出现这个情况。

**Comment by CanoNandMacaroN** [comment]
> @HopeLHP
> 
> 标注的定位是根据页面的内容而检索的，如果页面内容改变的话，定位就会消失。
> 
> 所以：
> 
> 1. **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰，重新找个页面进行标注，看是否可以稳定复现。
> 2. 在简悦导出的 HTML 中标注，一般都可以避免。
> 3. 如果原页面使用了 Live Editor 改变页面结构，也会出现这个情况。

确实，修改页面结构会导致原有标注不同步。所以live editor最好在开始标注之前使用。我目前的解决方案就是修改后导出本地html再通过同步助手对本地html标注。另外，对较短单个单词的标注还是会经常出现无法写进配置文件的情况。不过我现在基本上是把单词标注部分转移到单词app内了，只对长句子标注，目前很稳定。

**Comment by Kenshin** [comment]
@CanoNandMacaroN 

> 对较短单个单词的标注还是会经常出现无法写进配置文件的情况

确实有这个情况，因为英文的词重率比较高。解决这种方式只能更换其它算法，这算是预期性 Bug

如果你划比较长的内容就没问题，如果只是标注单词的话，会有问题，尤其是介词。

如果非要标注比较短的单词其实没必要使用简悦的标注功能，或者使用简悦的生词本来自动标记也可以。

**Comment by HopeLHP** [comment]
> 3\. 如果原页面使用了 Live Editor 改变页面结构，也会出现这个情况。

@Kenshin 我是不是可以这样理解，如果稍后读界面支持使用编辑页面功能，例如live editor，那就能把数据写入配置文件，后续的标注在稍后读完成再导出，就不用担心后续的链接丢失。

**Comment by Kenshin** [comment]
> 如果稍后读界面支持使用编辑页面功能，例如live editor，那就能把数据写入配置文件

是的，但这样有些「复杂」。

所以，最好的方案：

1. 不要在加入标注前修改页面内容。
2. 如果非要修改的话，当某个段落已经存在标注的话，不要修改。（反之，某个段落没有存在标注，则可以修改。
