### ISSUE TITLE
在vivaldi右键点击简悦图标出现的菜单显示异常

### ISSUE THREAD

**Issue by simple1988** [Kenshin/simpread#4768]
在vivaldi右键点击简悦图标出现的菜单有两个选项变成空白且点击没有反应
![image](https://user-images.githubusercontent.com/70116313/203804077-ff30dc98-8ee2-47a5-a89f-2ec235ee193b.png)
<html>
<body>

Vivaldi | 5.5.2805.44 (Stable channel) （64 位）
-- | --
操作系统 | Windows 10 Version 21H2 (Build 19044.2251)
简悦 | 2.2.0.520

</body>
</html>

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

这不算是 Bug 这是魔改 Chrome 的后遗症，因为简悦没做什么特别的设置。 😂

**Comment by simple1988** [comment]
好的谢谢，不过也不影响使用，只是看起来不太习惯😂

**Comment by Kenshin** [comment]
暂时只能这样，因为之前由用户反馈过，我一顿折腾白发现可能是这个问题… 😂
