### ISSUE TITLE
保存出错

### ISSUE THREAD

**Issue by 11422** [Kenshin/simpread#4769]
[Window Title]
simpread-sync_project_workflow

[Content]
同步助手运行时发生了错误，错误信息： ENOENT: no such file or directory, open 'H:\Users\xxxx\xxxx\Obsidian@simpread\Inbox\WPF 开发登录窗口之——添加密码完善登录窗口_dotNET 跨平台的博客 - CSDN 博客\assets\1669304093066.png'

[点击提交此问题] [关闭]

**Comment by Kenshin** [comment]
把出错的 URL 给我，并告诉我是使用什么功能出现的错误… 😂
