### ISSUE TITLE
手动点击自动化不生效的问题

### ISSUE THREAD

**Issue by MegaDom** [Kenshin/simpread#4770]
快捷键可以触发自动化，鼠标点击无法触发自动化。

我已经配置了加入稍后读的自动化：
![image](https://user-images.githubusercontent.com/107259784/203838916-3d362685-4b12-4c3b-893a-7d51556741f6.png)

但是当进入阅读模式后，使用鼠标依次点击  ... - 动作 - 暂存 - 保存到简悦·稍后读，并不能触发自动化。

但是我在Chrome里面设置了快捷键，在阅读模式里面，使用快捷键Ctrl+G加入简悦稍后读，这时候就可以自动触发自动化。请问如何修复鼠标点击无法触发自动化的原因啊？

![image](https://user-images.githubusercontent.com/107259784/203839112-d7279d34-6530-44c4-8aee-29cd2fc7088c.png)

**Comment by Kenshin** [comment]
嗨

这是个 Bug 细节 https://github.com/Kenshin/simpread/discussions/2362
也就是说，只能通过**快捷键或右键菜单加入稍后读**时才能触发。

不过，这个 Bug 实现了另外一个功能：即有些 URL 只想加入稍后读并不需要触发自动化的场景，比如：只是将某些 URL 做暂存用。

另外，也可以使用 https://github.com/Kenshin/simpread/discussions/2362#discussioncomment-4233529 提到的方案。

**Comment by MegaDom** [comment]
> 嗨
> 
> 这是个 Bug 细节 #2362 也就是说，只能通过**快捷键或右键菜单加入稍后读**时才能触发。
> 
> 不过，这个 Bug 实现了另外一个功能：即有些 URL 只想加入稍后读并不需要触发自动化的场景，比如：只是将某些 URL 做暂存用。
> 
> 另外，也可以使用 [#2362 (comment)](https://github.com/Kenshin/simpread/discussions/2362#discussioncomment-4233529) 提到的方案。

谢谢！Assistive Touch完美解决了我的问题，谢谢！

**Comment by Kenshin** [comment]
小事情，解决就好~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by MegaDom** [comment]
好滴！
