### ISSUE TITLE
在稍后读里面手动实现获取文章或标注的Scheme URL

### ISSUE THREAD

**Issue by IOSure** [Kenshin/simpread#4771]
在Obsidian中 只需要执行命令：Advanced URl: copy URI for current file
就可以获取当前页面的URI，如下所示：
obsidian://advanced-uri?vault=ObsidianMain&uid=af65a80e-1d80-42ae-bb5f-7e17053e9f93

对于简悦，并不想稍后读中的内容全部自动导入到Obsidian中。而是想让简悦作为资源仓库。
在简悦稍后读中比较重要的文章或标注，我只需要获取它的URl，然后粘贴到Obsidian等笔记软件中就可以。

当需要参考的时候，可以直接点击URI跳回到对应的文章或标注。 在简悦稍后读阅读和标注就可以。
谢谢！

**Comment by Kenshin** [comment]
嗨

暂时没有直接 **点击某个按钮就能复制永久链接的功能**，但下面的方式仍可以实现你的诉求。

> 而是想让简悦作为资源仓库。

实现这点很容易，简悦本身就支持此方式，在简悦中叫做 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2)。

你可以自己配置它，这是 [一站式教程](https://www.yuque.com/kenshin/simpread/wkswh7) 新用户的话，也可以直接使用 [剪藏库](https://www.yuque.com/kenshin/simpread/any457) 方案。

当使用后，会出现下图所示的 Icon，点击右侧箭头会打开这篇稍后读的永久链接

<img width="340" alt="image" src="https://user-images.githubusercontent.com/81074/203914096-47247cf4-8764-48ac-abb4-44c83e51342b.png">

> 当需要参考的时候，可以直接点击URI跳回到对应的文章或标注

简悦同步助手支持 [URL Scheme](https://simpread.pro/docs/#/Sync?id=urlscheme)，你可以在知识库的基础上使用 [此方式](https://simpread.pro/docs/#/稍后读极速版) 手动获取 URL Scheme 或者 URL 均可。

细节的话，可以看看 [永久链接](https://www.yuque.com/kenshin/simpread/egvhm7)
