### ISSUE TITLE
导入到Obsidian出现的一些疑问

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#4773]
1. 加入稍后读时并没有导出全文，但annote和本地html快照都存在
![image](https://user-images.githubusercontent.com/74438973/203983261-99d8ef5b-951b-43a6-b233-22738e43112f.png)
![image](https://user-images.githubusercontent.com/74438973/203983313-869f5fb6-43f9-4bcf-b8a4-e4829f4d94be.png)
2.同步助手中已设置增强导出路径，但 md+assets 只将图片导出到正确位置，而原文的markdown并没有出现在Inbox文件夹中，而是在output文件夹中
![image](https://user-images.githubusercontent.com/74438973/203983868-3139c610-ea3d-489d-85a2-2f182f07a0b5.png)

**Comment by Kenshin** [comment]
> annote和本地html快照都存在

HTML 本地快照不是全文？是指标注的 HTML ？

> 问题2

可能确实有点问题，我明天研究下。

关联问题 https://github.com/Kenshin/simpread/issues/4756?notification_referrer_id=NT_kwDOAAE8srA0OTAyNzE0Mzc1OjgxMDc0#event-7892859223

**Comment by jy324** [comment]
> HTML 本地快照不是全文？是指标注的 HTML ？
既有全文也有标注，这个没问题

**Comment by jy324** [comment]
> 2.同步助手中已设置增强导出路径，但 md+assets 只将图片导出到正确位置，而原文的markdown并没有出现在Inbox文件夹中，而是在output文件夹中
我试了试，修改路径对保存在什么位置没有影响，一直保存在output文件夹下。

**Comment by Kenshin** [comment]
> 既有全文也有标注，这个没问题

那就是问题1 没事了吧？

问题2 明天我再确认下。

**Comment by jy324** [comment]
> 那就是问题1 没事了吧？

就是请您看看，在这样的配置下，如果进入一个页面的阅读模式，不加入稍后读直接标注，是不是不能保存markdown全文？
根据我的测试，进入阅读模式以后如果直接标注，md原文是不会被保存的；如果加入稍后读再标注，md原文是能保存的

**Comment by jy324** [comment]
关于问题1，我其实就是想询问一下，
```
o b u n
o b u u
o b a a
o b a c
```
这组快捷键，是不是在直接标注的情况下不会将原文导入Obsidian，只有先加入稍后读，才能导入md原文

**Comment by Kenshin** [comment]
> 这组快捷键，是不是在直接标注的情况下不会将原文导入Obsidian

这组快捷键是针对标注的，而不是原文的。

而通过这个插件导入全文的话，有很多方案，下图是其中一种。

<img width="602" alt="image" src="https://user-images.githubusercontent.com/81074/204072000-4327f7d3-fd3a-4d28-841c-d3830bc1297e.png">

**Comment by jy324** [comment]
> 而通过这个插件导入全文的话，有很多方案，下图是其中一种。

开启这个是不是直接标注的时候不能导出原文？

**Comment by Kenshin** [comment]
> 开启这个是不是直接标注的时候不能导出原文？

最好的方式是：先加稍后读然后在标注，而不是通过先标注。因为自动化辅助增强插件使用时需要有一些「钩子」，才能触发。

**Comment by jy324** [comment]
> 最好的方式是：先加稍后读然后在标注，而不是通过先标注。因为自动化辅助增强插件使用时需要有一些「钩子」，才能触发。

我这里会出现标号不统一的情况，先加稍后读然后在标注 会使用两个编号
![image](https://user-images.githubusercontent.com/74438973/204076672-78ddc011-1c80-4d30-8f7e-ec0ade38a60a.png)
![image](https://user-images.githubusercontent.com/74438973/204076689-1a70fa20-6e33-48b0-9975-17929b75e47f.png)

**Comment by jy324** [comment]
但是在稍后读中是一篇文章

**Comment by jy324** [comment]
这个是已知bug吗？还是我配置的问题

**Comment by Kenshin** [comment]
> 这个是已知bug吗？还是我配置的问题

😂 肯定是配置问题... 关于序号的配置可以对比 https://www.yuque.com/kenshin/simpread/wkswh7 有什么区别？

**Comment by jy324** [comment]
好滴，我去看看。

**Comment by jy324** [comment]
> 好滴，我去看看。

说起来挺奇怪的，我用Assistive Touch 保存稍后读就会出现之前说的问题，用快捷键就是正常的，是钩子的问题吗？

**Comment by jy324** [comment]
> 好滴，我去看看。

说起来挺奇怪的，我用Assistive Touch 保存稍后读就会出现之前说的问题，用快捷键就是正常的，是钩子的问题吗？

**Comment by Kenshin** [comment]
> 我用Assistive Touch 保存稍后读就会出现之前说的问题，用快捷键就是正常的，是钩子的问题吗？

不是，肯定还是设置的问题 😂 因为除了你没有人反馈过这个问题，而且我也在用 Assistive Touch 

关于加入稍后读的一些问题，可以瞧瞧这里 https://github.com/Kenshin/simpread/discussions/2362

**Comment by Kenshin** [comment]
关于问题2 应该是「解决了」，你可以试试 https://github.com/Kenshin/simpread/issues/4756#issuecomment-1328176076 提到的方案。

另外 md + assets 也升级到了 1.1.1 修复了一个非高级账户权限的错误，细节 https://github.com/Kenshin/simpread/issues/4756#issuecomment-1328183261

我关闭这个 Issues，有问题仍可以直接通过这里讨论~

**Comment by jy324** [comment]
啊，好像两个问题都解决了，感谢👍
虽然是莫名其妙解决的就是了🤣

**Comment by Kenshin** [comment]
哈哈，解决就好，可能是玄学 😂

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by jy324** [comment]
大概一年之前就已经写过好评了~😍

**Comment by Kenshin** [comment]
哈哈，谢老用户的好评~

**Comment by ChasLui** [comment]
如何实现标注/稍厚读自动执行导入md+assets到Obsidian, 目前自动化中没有`导入md+assets到Obsidian` 选项

**Comment by Kenshin** [comment]
@ChasLui 

> 如何实现标注/稍后读**自动**执行导入md+assets到Obsidian, 目前自动化中没有`导入md+assets到Obsidian` 选项

自动化里面当然没有这个选项，这个选项在 【导入到 Obsidian 】插件里面。

<img width="814" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e6fd8d0c-5276-4b28-b870-150d162da36c">

详细说明 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604

上图的链接也能在 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 插件说明里面看到。
