### ISSUE TITLE
arm 架构macos下chrome浏览器，打开简悦自己的帮助中心，点击“阅读模式”白屏

### ISSUE THREAD

**Issue by cyg056** [Kenshin/simpread#4774]
![image](https://user-images.githubusercontent.com/19517553/204029203-a44bfca7-0d8d-4459-98d4-022302f11d9b.png)

**Comment by Kenshin** [comment]
跟什么架构没关系… 😂

我没有遇到这个问题，在隐私模式下仅启用简悦试试。
