### ISSUE TITLE
不开启阅读模式的时候加入稍后读不能显示标注栏

### ISSUE THREAD

**Issue by ertongnihaoa** [Kenshin/simpread#4775]
目前不开启阅读模式的时候加入稍后读不能显示标注栏（开启阅读模式的时候加入稍后读可以正常显示标注栏并修改），如何设置或者可以修正吗

**Comment by Kenshin** [comment]
嗨，我没有遇到这个情况，选项页 → 高级设定，把你的标注与稍后读都截图给我瞧瞧。

**Comment by ertongnihaoa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月26日 12:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 不开启阅读模式的时候加入稍后读不能显示标注栏 (Issue #4775)
        
      
    
  
  

嗨，我没有遇到这个情况，选项页 → 高级设定，把你的标注与稍后读都截图给我瞧瞧。

**Comment by Kenshin** [comment]
进入 https://github.com/Kenshin/simpread/issues/4775 后提问，通过 Email 是没法看到你的截图（如果有的的话）。

**Comment by ertongnihaoa** [comment]
![image](https://user-images.githubusercontent.com/92298052/204072338-66fb875b-af70-4e08-93f8-6f8e7e4b6075.png)
![image](https://user-images.githubusercontent.com/92298052/204072342-6c4e3c7c-d5e0-4bf9-aa9d-53893732d5aa.png)
![image](https://user-images.githubusercontent.com/92298052/204072345-73f8b0cc-1e37-4b73-9ce2-e5f21955c892.png)
![image](https://user-images.githubusercontent.com/92298052/204072348-de0df520-2a13-4dad-a3d8-938a2413347c.png)

**Comment by Kenshin** [comment]
emmm

我明白最后一个图的疑问了：

在不进入阅读模式时，可以加入稍后读，但没有侧栏，只有进入阅读模式后才能看到标注侧栏。

也就是说：**简悦的全部功能都以阅读模式为基准**。
