### ISSUE TITLE
知乎专栏导出PDF文件的公式无法正确显示的问题

### ISSUE THREAD

**Issue by chcling** [Kenshin/simpread#4778]
网址：https://zhuanlan.zhihu.com/p/42704781
系统：Macos Monterey
无配置导出相关插件
打开增强导出PDF功能

问题描述：知乎专栏的内容在阅读模式下显示正常，但是在使用PDF导出之后只有公式代码。如下图
<img width="500" alt="image" src="https://user-images.githubusercontent.com/105404173/204075047-1f2e6c4f-ea99-4764-bb1b-3e1652c860bd.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/105404173/204075074-ec67357b-6ef3-484e-94fc-8e3cf75f9c12.png">

默认打印模式下导出PDF的话是可以解析公式并显示完美的。是不是因为我的配置问题？搜索issue后也没有遇到相应的问题，麻烦作者解答。

**Comment by chcling** [comment]
# 附加问题
Markdown导出后公式显示也不完美，具体见图
<img width="624" alt="image" src="https://user-images.githubusercontent.com/105404173/204077128-2f2d80c9-1de2-4004-8e26-92eef3b249b3.png">

**Comment by Kenshin** [comment]
关于知乎加载公式后如何显示的细节可以看看 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

> 问题1

确实有点问题，可能知乎这种方式并不适合使用 PDF 高级打印方案。目前 PDF 高级打印方案只有你提到了这个问题。

> https://github.com/Kenshin/simpread/issues/4778#issuecomment-1327996615

这个肯定没问题，看下图在 Obsidian 中预览，如果你用的是 Typora 应该开启相应选项

<img width="778" alt="image" src="https://user-images.githubusercontent.com/81074/204083426-bae7b1c5-9c9d-422d-a521-c4a015afc4d0.png">

**Comment by chcling** [comment]
请问您是直接选择导出为Markdown吗，需不需做其他的更改，或者在obsidian中做什么配置呢？
<img width="906" alt="image" src="https://user-images.githubusercontent.com/105404173/204133825-a8c65733-fd61-484a-8dca-2822880369bb.png">
我这里直接导出后使用obsidian打开，也是会在公式后面多出一行letex公式的文本。

**Comment by Kenshin** [comment]
你可以看看 ob 相关的选项。

另外，可以把有问题的 md 发上来我明天看看。

**Comment by chcling** [comment]
好的，导出的md文件如下。
[GoogLeNet, Maxout and NIN.md.zip](https://github.com/Kenshin/simpread/files/10098345/GoogLeNet.Maxout.and.NIN.md.zip)

**Comment by Kenshin** [comment]
> 好的，导出的md文件如下。 [GoogLeNet, Maxout and NIN.md.zip](https://github.com/Kenshin/simpread/files/10098345/GoogLeNet.Maxout.and.NIN.md.zip)

确实有点问题，估计你没有使用 https://github.com/Kenshin/simpread/issues/4778#issuecomment-1328019104 提到的优化方案。

这是我导出的效果 [GoogLeNet- Maxout and NIN.txt](https://github.com/Kenshin/simpread/files/10100214/GoogLeNet-.Maxout.and.NIN.txt)

**Comment by chcling** [comment]
> 

感谢您的解答，使用知乎辅助插件后导出的md文件已经没有了问题。☕️

**Comment by Kenshin** [comment]
Cool ，解决就好~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
