### ISSUE TITLE
obsidian+内部链接标注，@ANNOTE页面无法实时刷新，部分标记不能被收录

### ISSUE THREAD

**Issue by meishiwanwan** [Kenshin/simpread#4779]
在obsidian中用内部链接标注，刚开始几条可以即刻同步，随着标注的增加，@ANNOTE页面就必须重新打开刷新才能显示标注
今天遇到新的问题，已经标注+重新打开，刷新，一直不显示标注的内容
请问该如何解决
![image](https://user-images.githubusercontent.com/45850781/204085704-59d7d298-b9dc-4dd3-b3cd-abbe52864e99.png)

**Comment by Kenshin** [comment]
emmm

> 随着标注的增加，@annote页面就必须重新打开刷新才能显示标注

是右侧？还是左侧？另外，你用的什么版本的 Obsidian ？

> 已经标注+重新打开，刷新，一直不显示标注的内容

在扩展端打开稍后读，看看能否显示？如果不能的话，可能是配置文件出现了问题，你可以把配置文件通过 tg 发给我。

**Comment by Kenshin** [comment]
嗨，[Obsidian SimpRead Unreader 更新到 2.1.1](https://github.com/Kenshin/simpread-obsidian-plugin/releases/tag/2.1.1) 已经修复了此问题~
