### ISSUE TITLE
一打开浏览器就进入简悦选项页

### ISSUE THREAD

**Issue by joflians** [Kenshin/simpread#4781]
自从重装了 Edge，一打开浏览器，就会进入简悦的选项页。简悦和 Edge 都是最新版。

这个问题，有人提过。我并没有开自动清除 cookies 的功能。

**Comment by Kenshin** [comment]
确实有用户提过，但应该就他自己而且后来也「无故」没问题了… 😂

你的电脑有什么限制吗？

试试安装其他浏览器或者 Edge 开发版，再试试。

**Comment by joflians** [comment]
用开发版没事了，普通版没有限制啊。

**Comment by Kenshin** [comment]
> 普通版没有限制啊

应该还是你的系统（或类似）有什么限制造成的。
Edge 有不少简悦用户，目前只有你反馈这个问题。
