### ISSUE TITLE
购买简悦高级账户出现了异常

### ISSUE THREAD

**Issue by Josiahzz** [Kenshin/simpread#4782]
我之前通过微信支付购买了高级账户，然后通过调查问卷方式把自己的支付单号给提交了，然后到现在邮箱也没收到信息，不知道是不是我的操作出现了问题，希望官方帮我解决一下。求求啦，这是我的微信支付账单

**Comment by Kenshin** [comment]
嗨

腾讯问卷购买时会提示不是实时发送兑换码，今天晚上 19 点前会发送。

但你的截图是爱发电购买的订单，通过爱发电购买的话，在私信里面查看。

如果私信里面没有的话，说明兑换码没有了，我会在今天13点前手动给你。
