### ISSUE TITLE
无法适配当前页面-微信读书

### ISSUE THREAD

**Issue by rpishgithub** [Kenshin/simpread#4783]
发生问题的地址: <https://weread.qq.com/web/reader/b12323f0722ff8d7b12c9db>

**Comment by Kenshin** [comment]
嗨，微信读书是不可以被适配的，我关闭这个 Issues 了。

**Comment by rpishgithub** [comment]
> 嗨，微信读书是不可以被适配的，我关闭这个 Issues 了。

可惜了,谢谢大大回复.

**Comment by Kenshin** [comment]
不是简悦无法适配，而是有版权的页面都不可以被适配，如：百度文库、微信读书、飞书文档等。
