### ISSUE TITLE
CSDN 一篇文章解析时会自动跳转到其他页面（个例）

### ISSUE THREAD

**Issue by GlodenBoy** [Kenshin/simpread#4784]
https://blog.csdn.net/wltsysterm/article/details/120456779

该页面进入到净化模式时会进入到其他页面

**Comment by Kenshin** [comment]
净化模式 → 阅读模式 😂

我明天确认下

**Comment by Kenshin** [comment]
试试将下图所示的选项关闭。

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/81074/204183236-cd5aa4cb-e270-4f62-90f6-aaac065c66af.png">
