### ISSUE TITLE
pdf配置库方案配置后显示导出失败

### ISSUE THREAD

**Issue by zhoulukuan** [Kenshin/simpread#4785]
参考教程：https://www.yuque.com/kenshin/simpread/omehxx
**本地html文件保存以及读取顺利，但无法生成pdf。图片转化完成后，显示导出失败，如图：**
![image](https://user-images.githubusercontent.com/16110591/204142581-3f48558b-caa6-406e-bc71-98e93211fa13.png)
![image](https://user-images.githubusercontent.com/16110591/204142356-fbd3f700-4770-46e1-ab54-1b42a8b28078.png)

**其它配置均已按照文档所示完成，win10环境，edge浏览器：**
![image](https://user-images.githubusercontent.com/16110591/204142409-8bc5f2a6-b4af-462a-8563-66804ed18849.png)
![image](https://user-images.githubusercontent.com/16110591/204142468-12e2af97-cd3e-49da-b53f-54de5856f963.png)
![image](https://user-images.githubusercontent.com/16110591/204142510-84be9c0d-1c1e-477a-9fbe-7540ae8bfaa3.png)

**Comment by Kenshin** [comment]
emmm 估计还是你的配置错误造成的。

1. PDF 辅助增强插件的细节可以看看 https://github.com/Kenshin/simpread/discussions/3887 里面有一些重点提示，尤其是 https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750490 提到了位置的相关测试。

2. 使用 https://sspai.com/post/69972 测试。

3. 当步骤1和2没问题，但还是有错误时，打开 `F12` 看看控制台的输出是什么，然后给我。

**Comment by zhoulukuan** [comment]
@Kenshin 控制台关于wkhtmltopdf的报错：
VM119:257 
        
       pdf wkhtmltopdf error  {killed: false, code: 1, signal: null, cmd: 'D:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf --mar…\\logseq\\SimpleRead\\output\\放弃纠结、拥抱妥协，重器轻用就是高效.pdf"'}cmd: "D:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf --margin-left 10 --margin-right 10 --margin-top 10 --margin-bottom 10 \"E:\\note\\logseq\\SimpleRead\\output\\tmp-放弃纠结、拥抱妥协，重器轻用就是高效.html\" \"E:\\note\\logseq\\SimpleRead\\output\\放弃纠结、拥抱妥协，重器轻用就是高效.pdf\""code: 1killed: falsesignal: null[[Prototype]]: Object
eval @ VM119:257

**Comment by Kenshin** [comment]
在 `cmd` 下直接运行 `wkhtmltopdf -V` 看看是什么？

另外，感觉你应该是设置错目录了。

<img width="214" alt="image" src="https://user-images.githubusercontent.com/81074/204199976-0b816a04-5751-489e-bb3f-98af309bdace.png">


看下图（刚才的链接里面已经特意提示了。

<img width="886" alt="image" src="https://user-images.githubusercontent.com/81074/204199887-d6a5c67a-7fda-412d-8441-f6c5397103c5.png">

**Comment by zhoulukuan** [comment]
@Kenshin cmd运行结果：wkhtmltopdf 0.12.6 (with patched qt)
我这边文件目录和bin子目录都设置过了，好像都不太行。直接设置文件目录也会报错：
![image](https://user-images.githubusercontent.com/16110591/204206403-36892948-ff38-43c6-a828-fec15d37a4dc.png)

**Comment by Kenshin** [comment]
看起来这个目录有问题

<img width="337" alt="image" src="https://user-images.githubusercontent.com/81074/204209173-bcd6e7de-9ed4-4f53-97d9-05fcf0bbac67.png">

显然不太可能存在 `D:\Program Files\wkhtmltopdf\wkhtmltopdf` 这样的目录。

**Comment by zhoulukuan** [comment]
@Kenshin 看起来确实是路径的问题，我把插件里的地址删掉，又把wkhtmltopdf加入了环境变量中，目前已经可以正常导出了

**Comment by Kenshin** [comment]
哈哈，搞定就好。
