### ISSUE TITLE
【2022.11.28】使用插件【导入到 Notion辅助增强】，剪藏的图片会被自动放大。

### ISSUE THREAD

**Issue by verygeili2013** [Kenshin/simpread#4788]
使用notion增强插件，剪藏的图片会被自动放大。不管是页面内的图片，还是图标、头像，都会被放大。

剪藏网址：https://sspai.com/post/77008

原网页效果
![image](https://user-images.githubusercontent.com/110316339/204172679-b4883554-1cee-44b5-8cdf-105a1449fda8.png)

剪藏后notion里面的效果
![image](https://user-images.githubusercontent.com/110316339/204172608-117cc427-e38b-48b3-bdc2-04d0d57e232a.png)

其他页面的剪藏效果
![image](https://user-images.githubusercontent.com/110316339/204173239-7a69a09d-3cfa-407b-8996-7d578422b8ce.png)

我增强插件的设置如下：

![image](https://user-images.githubusercontent.com/110316339/204172951-ad48662b-d0a3-4b61-86d3-140620f0a15b.png)
![image](https://user-images.githubusercontent.com/110316339/204172995-8431bf2d-c9cd-49eb-8b82-4de428b171f8.png)

**Comment by verygeili2013** [comment]
第二个bug是，使用插件的快捷键 ent，会无法剪藏。直接点击面板的notion图标来剪藏，则没有问题。
![image](https://user-images.githubusercontent.com/110316339/204173595-17f38da4-b0ac-49da-afdb-9d8985e332fb.png)

**Comment by Kenshin** [comment]
> 问题1

这个图太小了，上传后自然出现你提到的情况。你可以将这个页面导出 Markdown，然后在手动导入到 Notion，会发现跟通过简悦导入是一样的。（下图就是我上传 md 后的效果

<img width="840" alt="image" src="https://user-images.githubusercontent.com/81074/204186814-46ca93e2-a3ac-4e98-a896-8c0bd8846972.png">

> 问题2

我这边没有问题，你可以试试**隐身模式下仅使用简悦的方式**。

另外，建议使用 https://github.com/Kenshin/simpread/discussions/1600 提到的方案 https://github.com/Kenshin/simpread/discussions/1600#discussioncomment-3930672 ，比如我的设置

<img width="393" alt="image" src="https://user-images.githubusercontent.com/81074/204187325-50ddd5f1-d0ad-403b-ada5-20e9ca2a5f5b.png">
