### ISSUE TITLE
[corb]导出html文件异常

### ISSUE THREAD

**Issue by Lezon** [Kenshin/simpread#479]
以前用的好好的，最近无论哪个网页导出html文件都异常。能导出文件，但是数据大小为0KB，打开文件一片空白。
![chrome_2019-04-19_09-39-44](https://user-images.githubusercontent.com/42294271/56400659-9c115780-6287-11e9-9229-c257368f6a8a.png)

**Comment by Kenshin** [comment]
谢谢反馈，这是 Chrome 升级后的一个 `跨域错误` 造成的。
简单的说，Chrome 在升级后增加了一些安全措施导致。

下个版本会修复此错误~

**Comment by Lezon** [comment]
`大佬辛苦了`
 ^ _ ^

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
