### ISSUE TITLE
使用导出到Notion，进度一直不动

### ISSUE THREAD

**Issue by 8kita** [Kenshin/simpread#4790]
![QQ截图20221128113026](https://user-images.githubusercontent.com/104564630/204188968-dee04181-2732-40d1-bb5b-45e842543691.png)

**Comment by Kenshin** [comment]
试试 https://sspai.com/post/69972 这个页面。

Notion API 偶尔抽风的，我刚才这边是没问题的。

**Comment by 8kita** [comment]
这个页面也是一样，进度不动

**Comment by Kenshin** [comment]
> 这个页面也是一样，进度不动

1. 在**隐身模式下仅使用简悦的方式** 试试。
2. 先关闭 Notion 图床，看看是否可以正常导入到 Notion

然后建议稍晚时再测试试试。

**Comment by 8kita** [comment]
啊成功了，非常感谢！！

**Comment by Kenshin** [comment]
是关闭图床？还是什么其它方式？

**Comment by 8kita** [comment]
关闭图床，重新授权之后就好了
