### ISSUE TITLE
Telegram Group 无法加入，提示 This channel is private

### ISSUE THREAD

**Issue by richex-cn** [Kenshin/simpread#4791]
[订阅中心](https://simpread.pro/subscribe) Telegram Group 无法加入，提示 **This channel is private**。

如下图，这是什么原因？

![Snipaste_2022-11-28_13-21-20](https://user-images.githubusercontent.com/25103518/204200247-34ac6caa-a45f-4b07-bd09-157466ca19bb.png)

**Comment by Kenshin** [comment]
我也不清楚，个别用户就是没法进来 😂 估计是你们个人的设置，我问了很多人都没有解决。

也可以进入 [QQ 频道](https://pd.qq.com/s/5jp0meyfc)
