### ISSUE TITLE
稍后读显示快照的格式错误

### ISSUE THREAD

**Issue by xiang578** [Kenshin/simpread#4793]
原始页面：https://threadreaderapp.com/thread/1543128685288378368.html ，保存为离线 html 格式化后，在稍后读里面打开快照显示格式错误。

下图框出来的几个部分没有自动换行
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/12624910/204207712-60f73941-8abe-4a6e-b819-27d7353586d2.png">

通过 http://localhost:7026/reading/316 打开这个快照又显示正常。

<img width="944" alt="image" src="https://user-images.githubusercontent.com/12624910/204207933-ec84cafc-a7a8-47b3-8c38-a76967d1e0ef.png">

**Comment by xiang578** [comment]
这是保存的快照
[316-《福格行为模型》是一本神书。??在我做习惯主题阅读的过程当中，我看了超过 10 本相关的书。??直到我精读此书才知道大多数畅销书作者和我一样：框架大致正确，执行上最核心 - 要命的细节几乎都被忽略了，有些甚至根本就是错的。??我会不断更新这个 thread，做为我研究习惯 2-3 年的总结贴。.html.zip](https://github.com/Kenshin/simpread/files/10101029/316-.10.-.thread.2-3.html.zip)

**Comment by Kenshin** [comment]
感觉你在稍后读中没有设置读取本地快照功能。

看看 [这个链接](https://www.yuque.com/kenshin/simpread/wkswh7#VThyw) 里面的配置与你的区别。

**Comment by xiang578** [comment]
> 感觉你在稍后读中没有设置读取本地快照功能。
> 
> 看看 [这个链接](https://www.yuque.com/kenshin/simpread/wkswh7#VThyw) 里面的配置与你的区别。

感谢，查了一下是两台设备配置文件冲突导致的。

**Comment by Kenshin** [comment]
搞定就好~
