### ISSUE TITLE
obsidian内嵌标注模式菜单栏无法打开

### ISSUE THREAD

**Issue by NNGTHB** [Kenshin/simpread#4794]
![动画](https://user-images.githubusercontent.com/115760745/204240240-c4c15fa7-3a52-4b8a-adac-b166cd6c9d92.gif)
obsidian1.0.3，simpread sync 2.1.1版本，在2.1.0版本也出现这样的问题

**Comment by NNGTHB** [comment]
把除了简悦插件以外的插件都关了，但还是上面那种情况；奇怪的是我新开一个库只装简悦插件却能正常打开，可能有其他配置还是文件啥的出问题了吧

**Comment by Kenshin** [comment]
因为没有用户反馈过这个问题 😂

你可以试试把你的 Obsidian 的插件再手动转移到没问题的库，看看如何？

**Comment by NNGTHB** [comment]
ok，也不麻烦

**Comment by Kenshin** [comment]
哈哈，好。迁移完回头说下。

**Comment by NNGTHB** [comment]
把文件和插件迁移过去后能正常打开了

**Comment by Kenshin** [comment]
okay 没问题就好。

PS：Obsidian 一直都挺不稳定的 😂 之前因为版本升级导致 Obsidian SimpRead Sync 的某个功能不好使了...

**Comment by NNGTHB** [comment]
哈哈哈大佬看我之前的issue，很早之前就五星了😂

**Comment by Kenshin** [comment]
哈哈，谢谢老用户 😄
