### ISSUE TITLE
notion同步导入批注，会出现很多个重复的

### ISSUE THREAD

**Issue by A-hongchen** [Kenshin/simpread#4797]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/71955305/204297358-1ca0bf02-12c8-469f-9bf2-f3606cdad631.png">

没有使用同步助手，只是同步到notion。刚开始的时候是只有两个重复的，后面越来越多，到提问时已经出现了五个重复的。中间也有正常的。

**Comment by Kenshin** [comment]
emmmm 


刷新当前页，进入阅读模式后不要退出阅读模式，再试试。

**Comment by A-hongchen** [comment]
不知道什么原因，刷新以后
<img width="112" alt="image" src="https://user-images.githubusercontent.com/71955305/204305063-7255651d-99f5-48ab-859d-5e5914b7f564.png">
bu xiang 不会直接这样出现阅读模式，而是
<img width="88" alt="image" src="https://user-images.githubusercontent.com/71955305/204305212-f50ba9a4-0091-46ed-b235-0c6233bbfc97.png"> 不出现 阅读模式选项，退出这个网页，然后重新打开，就可以进入阅读模式。但是不能说没有效果，确实有的可以正常使用，有的更离谱，如这个：
<img width="2240" alt="image" src="https://user-images.githubusercontent.com/71955305/204305557-a6fc74ad-798a-4958-b21c-a5f839c27ce8.png">
目前还没有尝试别的网页，一直在看自己订阅的付费newsletter，不知道是不是收费的，平台做了限制还是怎样（不太懂技术问题）

**Comment by Kenshin** [comment]
重启浏览器，然后打开 https://sspai.com/post/69972 测试。

另外，把遇到问题的 URL 告诉我下。

**Comment by A-hongchen** [comment]
你发的正常，https://xiaobot.net/p/card

**Comment by A-hongchen** [comment]
> 重启浏览器，然后打开 https://sspai.com/post/69972 测试。
> 
> 另外，把遇到问题的 URL 告诉我下。

是这个里面的文章

**Comment by A-hongchen** [comment]
> 你发的正常，https://xiaobot.net/p/card

这个里面的文章

**Comment by Kenshin** [comment]
> 你发的正常，https://xiaobot.net/p/card

我看不了这个页面的内容。

另外，一般来说有版权限制的页面也不太适合使用简悦，简悦不会主动适配。

PS：你可以试试 https://github.com/Kenshin/simpread/discussions/1554 提到的方案，一般来说都可以解决。

**Comment by A-hongchen** [comment]
好的，谢谢帮助！

**Comment by Kenshin** [comment]
小事情，你可以把 xiaobot.net 加入到延迟加载列表，然后试试链接里面给出的方案2

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/81074/204515320-e260c1b5-697b-4169-bc05-c07bf65d7be2.png">

如果能解决的话，告诉我一声~

**Comment by A-hongchen** [comment]
根据你发的，添加延迟加载，右键使用所选范围进入阅读模式，无法进入

**Comment by Kenshin** [comment]
那就没办法了 😂

简悦虽然可以 100% 通过规则，但不会主动适配这种页面的，因为有版权。

**Comment by A-hongchen** [comment]
非常理解，这种本身就不适合。其他页面适配已经超级好了，已经做的很棒了！非常感谢你的帮助！！！

**Comment by Kenshin** [comment]
哈哈，谢谢理解。（我看了几篇小报童的，感觉用我跟你说的方式应该可以，但还是不折腾了，尊重版权。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by A-hongchen** [comment]
必须好评！
<img width="854" alt="image" src="https://user-images.githubusercontent.com/71955305/204518310-5e425302-7cb8-431d-bc2e-5889abb6abda.png">
阅读去了，再次感谢你的支持和帮助！

**Comment by Kenshin** [comment]
谢谢支持 😄

**Comment by Kenshin** [comment]
看到你的头像了 S.H.I.E.L.D. 可还好~
