### ISSUE TITLE
清理知乎正文中指向站内搜索的链接

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#4799]
![image](https://user-images.githubusercontent.com/74438973/204433697-4d518608-56d0-4205-bb25-43d4ace7ffe4.png)

![image](https://user-images.githubusercontent.com/74438973/204433274-4cb470bb-c93c-418f-8ffe-a73191ab6b85.png)
希望在进入阅读模式及导出时去除掉这些链接

**Comment by Kenshin** [comment]
嗨，可以试试这个插件 https://simpread.ksria.cn/plugins/details/1VIRZ7VGc3 另外把这个 URL 给我我瞧瞧。

**Comment by jy324** [comment]
https://www.zhihu.com/question/524614207/answer/2412604403

**Comment by Kenshin** [comment]
明白了~

这个插件没法解决这个问题，我考虑下，把这个功能集成到 [知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) 里面。

**Comment by Kenshin** [comment]
嗨，[清理链接](https://github.com/Kenshin/simpread/discussions/2734) 升级到 1.0.2 版，增加了 [清理正文全部超链接](https://github.com/Kenshin/simpread/discussions/2734#discussioncomment-6371147) 功能。

![image](https://github.com/Kenshin/simpread/assets/81074/226246a5-38e8-4920-b222-49f0cf3dffe7)

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/1VIRZ7VGc3) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 有任何问题仍可以在这里跟我讨论~
