### ISSUE TITLE
一个高聚焦模式下的鼠标形态BUG

### ISSUE THREAD

**Issue by jinyu121** [Kenshin/simpread#48]
OS： Debian 9
浏览器： Chrome

复现过程：

1. 找一个正文中带有链接的网页
1. 右键，聚焦模式
1. 鼠标移动到链接上，鼠标仍然是“指针”，而不是“小手”
1. 在高亮的区域里面随便点击一下
1. 鼠标再次移动到链接上，鼠标变成了“小手”

**Comment by Kenshin** [comment]
okay 我回去看下。 😶

**Comment by Kenshin** [comment]
@jinyu121 
测试后重现了你说的情况，估计是 **由于使用右键菜单导致 Chrome 失去焦点** 了，如果你用快捷键的话，则没有这个问题。

如果是这样的话，算不算 Chrome 的bug... 😜 😄

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
