### ISSUE TITLE
稍后读文章消失

### ISSUE THREAD

**Issue by richex-cn** [Kenshin/simpread#4801]
**发生问题的环境**

- 操作系统 **Windows 11**

- 浏览器版本 **107.0.5304.122**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 `chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html`

使用了坚果云自动同步。

**请描述你的问题**

在连续收藏了了一些文章后，出现原本打开稍后读显示的文章有 13 个，收藏后变成 8 个，部分文章莫名消失。

期间只是每次加入稍后读之后打开稍后读页面检查确认有被加入。

这个不太好确定准确的复现步骤，所以先提一下这个问题的存在。

这是第二次出现类似情况了，前一次是多次提示成功加入稍后读，但打开稍后读页面并未找到。

**截图**

![](https://user-images.githubusercontent.com/25103518/204687643-9711ebe0-228f-4043-8b4f-90fbc4e0c6c1.png)

![](https://user-images.githubusercontent.com/25103518/204687684-c1077096-4656-43f4-b337-df5f4d13567b.png)

**Comment by Kenshin** [comment]
emmm 看你的描述，应该是隐性 Bug 因此不是很好排查，所以建议你最好能留意到出现问题前你操作的步骤。

正常使用肯定不会有这种情况 😂

***

关于加入稍后读的操作，我说个首选方式：**进入阅读模式后，使用快捷键加入稍后读 → 才会触发快捷键**，其它方式也可以，但你这边既然发生了这个问题，所以还是建议按照我说的方式加入。

不知道是否使用了同步助手的自动同步方案，如果是的话，使用 https://github.com/Kenshin/simpread/discussions/3165 能够找回任意时间点的稍后读数据。
