### ISSUE TITLE
logseq和简悦的同步，output文件夹和简悦的插件都能看到原文和批注，但是logseq不读取

### ISSUE THREAD

**Issue by amelia01x** [Kenshin/simpread#4803]
不知道是不是因为logseq主文件在icloud

**Comment by Kenshin** [comment]
> logseq不读取

你怎么也得截图或简单的操作视频吧... 否则我怎么判断 😂

**Comment by amelia01x** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/103746991/204726253-ad2b4291-2804-412d-9523-f61f510643c9.png">
页面能查到，但是不出现在日志页

**Comment by lyserenity** [comment]
要看你 logseq 的设置而定，预设是只有在 journals/ 里，且符合特定日期格式的文件才会出现日志中

**Comment by amelia01x** [comment]
> 

怎么修改，让日志里面可以看到博呢？

**Comment by lyserenity** [comment]
你有没有效果图，比如你是看了哪篇教学文里的展示图？还是你心中有个想要达到的成果，你可以模拟一下然后截个图，这样比较好接下来的讨论....

**Comment by amelia01x** [comment]
https://sspai.com/post/72022,我之前用的是这个方案

**Comment by amelia01x** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/103746991/204756956-cea95795-1b55-45aa-9795-49ef0e5471bc.png">
之前的效果

**Comment by lyserenity** [comment]
所以你的意思是图中的这块不见了？是以前生效过但现在失效了？
<img width="702" alt="image" src="https://user-images.githubusercontent.com/32646062/204758645-abafbebd-e89e-41af-842f-d6c80207164d.png">

我要先说明一下，只有标注的文件（也就是 ``XXXX@annote.md``) 可以有这效果，“原文的快照”是没办法的。
如果你的模版是这个，然后又没效果——没出现在日志里：
```
#[[excerpt]] [{{title}}]({{url}}) 
- tags: #[[SimpRead]] {{tags}}
- read date: [[{{date_format|now|yyyy_MM_dd}} ]]
- desc: {{desc}}
{{#each}}
- [📌](<{{an_int_uri}}>)  {{an_html}}
{{>|an_note}}{{an_tags}}
{{/each}}
```
你可以确认下 logseq 的设置是不是这个：
<img width="759" alt="image" src="https://user-images.githubusercontent.com/32646062/204760349-90a0b847-e499-4925-9da3-43b83d988433.png">
