### ISSUE TITLE
印象笔记授权失败

### ISSUE THREAD

**Issue by AllenHongMa** [Kenshin/simpread#4804]
你好，印象笔记授权之前好好地，最近重新安装了插件，然后授权就一直失败

**Comment by Kenshin** [comment]
印象笔记的授权不是简悦这边的问题，而且我不建议使用印象笔记，因为它的 API 各种问题...

**Comment by AllenHongMa** [comment]
好的，谢谢，我反馈给印象笔记开发者，体验太次了











迈开脚步，跟着感觉走，就对了。

---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年12月1日(周四) 上午10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 印象笔记授权失败 (Issue #4804)




 
印象笔记的授权不是简悦这边的问题，而且我不建议使用印象笔记，因为它的 API 各种问题...

**Comment by Kenshin** [comment]
其实建议使用 Notion 或过一阵子可以试试 FlowUs 都是不错的选择方案。
