### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by jingrenjushi** [Kenshin/simpread#4805]
发生问题的地址: <https://vpn.jlu.edu.cn/https/6a6c7576706e6973746865676f6f642154ac1e86e498d8af2f993f82e040443f2d2a/epub/reader?ssid=96180320

**Comment by Kenshin** [comment]
我没法访问你提供的页面，可以试试 https://github.com/Kenshin/simpread/discussions/1554 能否解决？
