### ISSUE TITLE
简悦助手导致蓝屏（AMD 个例）

### ISSUE THREAD

**Issue by niuniuyer** [Kenshin/simpread#4806]
前天刚刚付费，在使用简悦同步助手时导致蓝屏，同时使关机/重启时也会导致蓝屏

**Comment by Kenshin** [comment]
使用了什么版本的同步助手？是不是 AMD 的显卡？

**Comment by niuniuyer** [comment]
确实平时应该是用amd的集显，但关闭自启，手动启动后关机如果不退出依然会导致蓝屏

**Comment by niuniuyer** [comment]
使用的就是最新版的同步助手1.13

**Comment by Kenshin** [comment]
> 手动启动后关机如果不退出依然会导致蓝屏

也就是说：

1. 关闭自启动
2. 关机前退出同步助手

没有蓝屏？

**Comment by niuniuyer** [comment]
是这样的，目前还没有遇到蓝屏，对了，在同步助手里点同步里的几个按键也有几率导致蓝屏

**Comment by Kenshin** [comment]
emmm

你能把你的显卡详细信息发上来吗？

**Comment by niuniuyer** [comment]
cpu是AMD Ryzen 9 4900HS
独显是英伟达2060mq

**Comment by Kenshin** [comment]
okay 我研究下~
