### ISSUE TITLE
某社区路过，求适配

### ISSUE THREAD

**Issue by lgaying** [Kenshin/simpread#481]
cao ,,,榴，作者有没想法
同意的走起，小说页面
@Kenshin

**Comment by Kenshin** [comment]
😄我可以把它放到 `第三方适配` 里面。
搞定通知你~

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

你可以用新版 解析引擎 试试，我先关闭此 issues 如有需要，我再重新打开它。

***

详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
