### ISSUE TITLE
添加站点集市中的站点后，页面刷新无效

### ISSUE THREAD

**Issue by jochne** [Kenshin/simpread#4810]
**发生问题的环境**

- 操作系统 **Mac Intel 12.6**

- 浏览器版本 **Chrome 版本 107.0.5304.121（正式版本） (x86_64)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://simpread.ksria.cn/sites/install/vdmq0t08-EpXEBYOuq7?site=%7B%22id%22:%22vdmq0t08-EpXEBYOuq7%22,%22bgColor%22:%22#5334f5%22,%22category%22:%22%E6%8A%80%E6%9C%AF%22,%22color%22:%22#fff%22,%22create%22:%222018/08/06%2016:37:21%22,%22domain%22:%22EpXEBYOuq7%22,%22title%22:%22Design%20Code%22,%22site%22:%7B%22desc%22:%22%5B%5B%7B$('#section-body').find('.wrapper').text()%7D%5D%5D%22,%22exclude%22:%5B%22%22%5D,%22include%22:%22%3Csection%20id='content-body'%3E%22,%22name%22:%22chapters.designcode.io%22,%22title%22:%22%3Ctitle%3E%22,%22url%22:%22https://designcode.io/*%22,%22avatar%22:%5B%7B%22name%22:%22%22%7D,%7B%22url%22:%22%22%7D%5D,%22paging%22:%5B%7B%22prev%22:%22%22%7D,%7B%22next%22:%22%22%7D%5D%7D,%22view%22:4401,%22download%22:3537%7D

**Comment by Kenshin** [comment]
嗨

是不是使用了同步助手？如果是的话，先关闭同步助手的自动同步，然后在安装站点集市的站点，然后再开启自动同步并覆盖到本地，即可。
