### ISSUE TITLE
站点安装不了

### ISSUE THREAD

**Issue by AllenHongMa** [Kenshin/simpread#4813]
你好，点击安装站点，刷新之后站点没有安装上，请问怎么解决呢？

**Comment by Kenshin** [comment]
嗨

关闭自动同步，然后安装站点集市的站点，安装确认无误后，重启浏览器并开启自动同步以及覆盖到本地。

<img width="877" alt="image" src="https://user-images.githubusercontent.com/81074/205037065-ee923551-b1c3-46c2-99bb-a1a48ce74ebf.png">

**Comment by AllenHongMa** [comment]
谢谢，我试试看看能不能成功











迈开脚步，跟着感觉走，就对了。

---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年12月1日(周四) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 站点安装不了 (Issue #4813)




 
嗨
 
关闭自动同步，然后安装站点集市的站点，安装确认无误后，重启浏览器并开启自动同步以及覆盖到本地。
