### ISSUE TITLE
markdown全文导出没有metadata

### ISSUE THREAD

**Issue by hujie12306** [Kenshin/simpread#4818]
都是最新版本
效果
![image](https://user-images.githubusercontent.com/61086637/205232580-fa9c4875-27f0-4997-9fe2-a438eef28910.png)
该导出估计采用的是
![image](https://user-images.githubusercontent.com/61086637/205232661-0fc24eb6-3785-44a0-ac7e-6e3793f85132.png)
我的相关设置
![image](https://user-images.githubusercontent.com/61086637/205232943-2cf81fcf-6828-488e-bbba-5ba59ef1bd97.png)

![image](https://user-images.githubusercontent.com/61086637/205232935-6f338d09-5cf1-4f8e-b7b9-e562575f201f.png)

![image](https://user-images.githubusercontent.com/61086637/205232906-613ff166-16ba-4956-9a3d-f1ccd11f477e.png)

![image](https://user-images.githubusercontent.com/61086637/205232889-2a738863-430a-4b68-90e9-0ac92b132f43.png)

**Comment by Kenshin** [comment]
emmm

试试把 `o b` 去掉，然后使用 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590606 提供的方式。

**Comment by hujie12306** [comment]
![image](https://user-images.githubusercontent.com/61086637/205234329-aa1290ba-f9d3-4a22-bfc9-ddb767a44ccb.png)
这个是开启的状态
o b去掉之后仍然是同样的效果
![image](https://user-images.githubusercontent.com/61086637/205234610-3e1a628d-fbe9-49c4-ab9b-36a7b60b7964.png)
![image](https://user-images.githubusercontent.com/61086637/205234761-8ccd121d-63a6-457a-a95d-089add6cf612.png)

**Comment by Kenshin** [comment]
emmm

试试手动通过下图方式

<img width="535" alt="image" src="https://user-images.githubusercontent.com/81074/205243786-55b728c2-2053-420d-93cc-c9d1f1a7c1a0.png">

**Comment by hujie12306** [comment]
手动功能正常运行
但自动导出仍然出错，他现在应该是按照选项页里增强导出功能里的自动同步来运行的采用的模板也是定制导出里设置的模板

**Comment by hujie12306** [comment]
但是如果把增强导出里的自动导出功能关掉，加入稍后读时不会自动导出全文

**Comment by hujie12306** [comment]
修改稍后读的标签等数据可以按照正常的模板来导出

**Comment by Kenshin** [comment]
选项页 → 服务 → 自动化

这里面是否设定了关于 Markdown 的内容？

如果还是不行，把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4818

然后告诉我，我瞧瞧。

**Comment by hujie12306** [comment]
> 选项页 → 服务 → 自动化
> 
> 这里面是否设定了关于 Markdown 的内容？
> 
> 如果还是不行，把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4818
> 
> 然后告诉我，我瞧瞧。

关于这个，我在前面提到过
![image](https://user-images.githubusercontent.com/61086637/205274789-eff31aef-53f7-4de7-8260-3d7c2ecb6b86.png)
本次的问题是会自动导出，但是按照定制导出的模板导出的

**Comment by Kenshin** [comment]
我知道（大概）问题了...

使用此方式不需要设置自动化，你把自动化对应的 Markdown 删除后再试试。

**Comment by hujie12306** [comment]
> 我知道（大概）问题了...
> 
> 使用此方式不需要设置自动化，你把自动化对应的 Markdown 删除后再试试。

这个我前面也提到过
![image](https://user-images.githubusercontent.com/61086637/205285723-8327353c-6d26-4014-a8ba-2229c35baa2b.png)

经过更仔细地测试，我发现以下现象（此时，自动化对应的 Markdown 已删除）
- 进入阅读模式后通过快捷键加入稍后读，可以自动导出全文。但是当进行标注时，obsidian内获得的全文会消失。
   - 此时对稍后读标签进行修改，可获得全文，并且之后再进行标注操作，获得的全文不在消失
-  进入阅读模式后直接进行标注（同时简悦会自动将页面加入稍后读），obsidian中不会出现对应的正文markdown。

**Comment by Kenshin** [comment]
好，我明天看看你的配置文件再回复你。

**Comment by hujie12306** [comment]
OK
&nbsp;


沐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 晚上9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] markdown全文导出没有metadata (Issue #4818)





 
好，我明天看看你的配置文件再回复你。

**Comment by Kenshin** [comment]
耽搁了几天 😂

我已经把正确配置的文件发给你了，留意 Email。

我只修改了一个很小的的地方，在自动化辅助增强这里把，第一个输入库的 `o b` 去掉了，除此之外：

1. 导入到 Obsidian 我修改了库名称和文件夹名称
2. 我关闭了自动同步功能。

你通过**选项页 → 共通 → 导入本地配置文件**导入，暂时不要开启自动同步，但确认无误后再开启自动同步，并覆盖浏览器配置到本地。

**Comment by hujie12306** [comment]
> 耽搁了几天 😂
> 
> 我已经把正确配置的文件发给你了，留意 Email。
> 
> 我只修改了一个很小的的地方，在自动化辅助增强这里把，第一个输入库的 `o b` 去掉了，除此之外：
> 
> 1. 导入到 Obsidian 我修改了库名称和文件夹名称
> 2. 我关闭了自动同步功能。
> 
> 你通过**选项页 → 共通 → 导入本地配置文件**导入，暂时不要开启自动同步，但确认无误后再开启自动同步，并覆盖浏览器配置到本地。

我用着和之前一样，先这样吧，最近有点忙，闲了再折腾

**Comment by Kenshin** [comment]
那就是你自己环境的问题了

1. 删除简悦再重新安装。
2. 清空同步助手的增强导出的内容
