### ISSUE TITLE
cnblog文章的代码块字体无法调整大小

### ISSUE THREAD

**Issue by LuckyTanka** [Kenshin/simpread#482]
![image](https://user-images.githubusercontent.com/29697608/56847241-30745d80-690b-11e9-9aff-50342310b65d.png)

**Comment by Kenshin** [comment]
谢谢反馈，CSDN 这类网页在页面布局上会比较没任何规律。

你可以通过自定义样式解决这个问题。

另外，请告诉我详细 URL ，这样方便调查。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，其它更新包括：

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

你可以开启 `纯粹模式` （默认开启） 来改善此功能，如有异议请再 Reopen issues ~
