### ISSUE TITLE
印象笔记适配站点

### ISSUE THREAD

**Issue by AllenHongMa** [Kenshin/simpread#4820]
你好，通过手动打开检悦适配影响笔记网页端的时候滚动鼠标不能上下移动页面，请问怎么解决呢
本来不想用印象笔记的，但多年老用户，数据都在上面，没办法。所以多次向你请教问题，抱歉。

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/3472 能否解决？

**Comment by AllenHongMa** [comment]
您好，我加了app.yinxiang.com，但奇怪的是每次手动进入简悦阅读模式，配置文件中的这个域名就被自动踢出了。
还有一个问题想请教一下，印象笔记的认证和保存你调用的是国内印象笔记的的api吗，刚我联系了下印象笔记开发者
他们说你调的可能是国外的Evernote导致被wall了，我真的是刚需，配合印象笔记和简悦。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 印象笔记适配站点 (Issue #4820)





 
嗨，试试 #3472 能否解决？

**Comment by Kenshin** [comment]
试试加 `app.yinxiang.com` 后重启浏览器。

> 配合印象笔记和简悦。

简悦导入到印象笔记的成功率不是很高，不是简悦的问题，而是因为他们 API 文档以及特殊格式 ENML 的缘故。

个人不建议使用通过简悦导入到印象笔记，单纯的说印象笔记的自己的剪藏也非常不错。

***

如果非要使用简悦的话，建议试试 https://github.com/Kenshin/simpread/discussions/3471 提供的方案。

**Comment by AllenHongMa** [comment]
好的，谢谢，请问liver editor 我点复制到原文没什么反应，还是阅读模式，怎么解决呢？麻烦您了，今天



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 印象笔记适配站点 (Issue #4820)





 
试试加 app.yinxiang.com 后重启浏览器。
  
配合印象笔记和简悦。
  
简悦导入到印象笔记的成功率不是很高，不是简悦的问题，而是因为他们 API 文档以及特殊格式 ENML 的缘故。
 
个人不建议使用通过简悦导入到印象笔记，单纯的说印象笔记的自己的剪藏也非常不错。
 
 
如果非要使用简悦的话，建议试试 #3471 提供的方案。

**Comment by Kenshin** [comment]
我测试了下，没问题。

你可以通过 https://sspai.com/post/69972 测试看看。

Tips：不需要通过 Email 回复，直接进入 https://github.com/Kenshin/simpread/issues/4820 回复就行。
