### ISSUE TITLE
开放平台确保有output文件夹且已点击授权，但仍测试失败

### ISSUE THREAD

**Issue by jochne** [Kenshin/simpread#4822]
每次重制token后有一两次可以正常，但是之后都会无法访问授权
{
  "code": 404,
  "message": "Request failed with status code 503"
}

![](https://img.chne.tech/uPic/2022/12/02/19_58_18_FUzMU9.png)
![](https://img.chne.tech/uPic/2022/12/02/19_59_36_H4Rwtp.png)

**Comment by jochne** [comment]
然后什么都没有操作隔一会重新请求，又会正常。

{
  "code": 201
}

**Comment by jochne** [comment]
隔了一会接了个电话，再请求又不行了555（中间没有修改任何配置）
{
  "code": 404,
  "message": "Request failed with status code 503"
}

**Comment by jochne** [comment]
补充直接发起坚果云授权调用：
<img width="977" alt="image" src="https://user-images.githubusercontent.com/21233677/205292382-bfc7c4c0-c805-4044-b1e2-2fe0abdbbcca.png">

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/21233677/205292318-a37af347-5f6f-4045-b722-2471a2c5e73a.png">

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4822#issuecomment-1335143238

再哪里测试出现的这个结果？

开放平台的教程可以看 https://www.yuque.com/kenshin/simpread/ieu1w6

**Comment by jochne** [comment]
开放平台内的测试教程，发送一个测试post那里

Kenshin Wang ***@***.***>于2022年12月2日 周五20:58写道：

**Comment by Kenshin** [comment]
> 开放平台内的测试教程，发送一个测试post那里

不用用是反复测试… 😂

用隐私模式登陆开放平台，能登陆的话，基本上就说明成功了…

**Comment by jochne** [comment]
主要是访问阅读列表这些，会无法正常访问到坚果云
<img width="981" alt="image" src="https://user-images.githubusercontent.com/21233677/205301016-9a924a0b-a2b4-411e-a495-b6adc7189081.png">

**Comment by Kenshin** [comment]
把你坚果云 web 端截图我瞧瞧，应该是结构错误。

应该还是这个教程里面的步骤有问题…  https://www.yuque.com/kenshin/simpread/ieu1w6

你你使用的开放平台功能不需要也无法使用手动同步。

**Comment by Kenshin** [comment]
你使用的功能属于复合功能，需要两个配置方案。

https://www.yuque.com/kenshin/simpread/wkswh7 和 https://www.yuque.com/kenshin/simpread/ieu1w6

留意下 https://www.yuque.com/kenshin/simpread/wkswh7#q78BG 的说明

<img width="870" alt="image" src="https://user-images.githubusercontent.com/81074/205415444-7bb3f4e6-af8c-41ac-aeee-c1a2c6e96102.png">

**Comment by jochne** [comment]
> https://www.yuque.com/kenshin/simpread/wkswh7#q78BG

 @ Kenshin 如下，确认是正常配置的，关键是偶尔成功，偶尔提示output不存在。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/21233677/205442860-c35b2b9c-6625-4fba-b29d-921f389b77c4.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/21233677/205442875-b110e5c2-9dbb-4e37-88b0-eb4c62a34885.png">

**Comment by jochne** [comment]
@Kenshin 更换了一个新的坚果云账号后，使用一切正常，不再会出现授权读取失败的问题。能否请您帮忙看下之前的坚果云账号是什么原因导致问题呢？

**Comment by Kenshin** [comment]
emmm 把你的 UID 以及方便的话，出问题的坚果云账户和密码送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4822

然后告诉我，我明天瞧瞧。
