### ISSUE TITLE
同样设为开机启动，如何确保坚果云在同步助手之前启动？

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#4823]
![image](https://user-images.githubusercontent.com/69069739/205296464-7ec882cc-745a-4bc5-82dc-cb86852afc02.png)

**Comment by Kenshin** [comment]
如果是开机的话，不需要这么「精细」。

这句话的意思是指：非开机情况下，只有保障这个方式前提下，浏览器读到的数据是通过坚果云同步过来的新数据。
