### ISSUE TITLE
远程数据同步失败,请稍后再试!

### ISSUE THREAD

**Issue by jochne** [Kenshin/simpread#4824]
**请说明发生问题的环境**

- 操作系统 **MacOS**

- 浏览器版本 **Chrome 108.0.5359.71（正式版本） (x86_64)**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

**请描述你的问题**

手动同步时，点击同步到坚果云均无效

**截图**

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/21233677/205304179-8b69487d-b11a-4dda-bcb6-6877742753ef.png">
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/21233677/205304244-fa9ea2bd-2bc5-459c-912d-35e585e477d9.png">

已尝试关闭和重新授权坚果云，能够授权成功但无法同步。。
<img width="949" alt="image" src="https://user-images.githubusercontent.com/21233677/205304396-6f582aca-a4c2-480a-baab-89d5e3646a42.png">

**Comment by Kenshin** [comment]
看看是不是 https://www.yuque.com/kenshin/simpread/tmmwhl 造成的？

PS：坚果云授权时的密码不是你的登陆密码。

**Comment by jochne** [comment]
> https://www.yuque.com/kenshin/simpread/tmmwhl

如果密码错误，是不可能在服务中授权成功的，现在是授权成功但是同步时失败。（相关issue的特征：https://github.com/Kenshin/simpread/issues/4822，在插件中调用坚果云同步失败时，开放平台中同时也不可用，二者正常时会同时正常）
<img width="846" alt="image" src="https://user-images.githubusercontent.com/21233677/205442953-c191b5a8-9dc9-4a78-9ae4-da434bfdd1a8.png">
