### ISSUE TITLE
添加到稍后读的网页如何加标签、分类

### ISSUE THREAD

**Issue by Georgeqzb** [Kenshin/simpread#4825]
谁知道稍后读怎么分类加标签啊，我把一个网页保存到了稍后读，但是没法归类，标签添加不了，我不知道哪里的问题，翻了使用文档没找到

**Comment by Kenshin** [comment]
进入阅读模式后，通过快捷键 `d d` 加入稍后读，然后就在标注侧栏进行操作。

<img width="296" alt="image" src="https://user-images.githubusercontent.com/81074/205415559-16c9418f-46d3-4cf4-9e99-ad5561e9d1e9.png">

**Comment by Georgeqzb** [comment]
谢谢作者大大，我把同步助手都配置完了，才发现我的问题，我在添加标签的时候没按回车，直接点保存，才一直创建不了，我对自己也是服气了

**Comment by Kenshin** [comment]
😂 每个标签栏都有下面的这句话...

<img width="785" alt="image" src="https://user-images.githubusercontent.com/81074/205430847-74c4065f-3734-4902-9bbc-1292cc048590.png">

**Comment by Georgeqzb** [comment]
这……是我傻乎乎，习惯把回车=确认=保存了，于是就死命点保存，绝了。

**Comment by Kenshin** [comment]
哈哈，小事情。解决你的问题就好，我之前还很奇怪，你问的问题都是基本操作，应该没有人问过 😂

**Comment by Kenshin** [comment]
遇到个无脑喷子… 😡

***

要是能使用 Chrome 的话，请帮忙对简悦五星 + 好评 🙏

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Georgeqzb** [comment]
好的好的

**Comment by Kenshin** [comment]
太感谢了。 👍 🙏
