### ISSUE TITLE
无法适配当前页面腾讯文档

### ISSUE THREAD

**Issue by AllenHongMa** [Kenshin/simpread#4826]
发生问题的地址: <https://docs.qq.com/doc/DQVd5UXRyZ0VXSGxC?

**Comment by Kenshin** [comment]
嗨，此类页面是可以被适配的，我关闭这个 Issues 了。

**Comment by AllenHongMa** [comment]
> 嗨，此类页面是可以被适配的，我关闭这个 Issues 了。

您好，腾讯文档整个页面获取不到，适配了没法获取全部正文，麻烦优化下，谢谢

**Comment by Kenshin** [comment]
我刚才说了，腾讯文档、百度文库、飞书文档、微信读书这类有版权的页面都不会别主动适配的。

**Comment by Kenshin** [comment]
这不是简悦的问题，而是需要版权方的规则。

你可以使用 https://github.com/Kenshin/simpread/discussions/1554 自行试试。
