### ISSUE TITLE
同步助手与电脑端稍后读数据不互通

### ISSUE THREAD

**Issue by childeyouyu** [Kenshin/simpread#4828]
先放上我在手机端和浏览器的内容
[
![{D 5JNOV3IE 44$UB2AY8(7](https://user-images.githubusercontent.com/89082776/205439823-97bd1063-bd31-4808-b4af-934535462ac3.png)
](url)
[]
![~X_6R7`32PHP_VB{72UOHIF](https://user-images.githubusercontent.com/89082776/205439835-79facffe-4c08-45b8-9450-31d781aea2f6.jpg)
(url)
我最开始是通过帮助文档开通了开放平台并登录手机端，但是后面无论是使用收藏助手、telegram机器人还是手机直接保存，内容都只能在手机上看见，稍后读里没有。

**Comment by Kenshin** [comment]
emmm 估计扩展端没有设置「自动同步」

看看这里的教程的对比你的有什么区别？尤其是自动同步相关的步骤。 https://www.yuque.com/kenshin/simpread/pwpnsx

**Comment by childeyouyu** [comment]
> emmm 估计扩展端没有设置「自动同步」
> 
> 看看这里的教程的对比你的有什么区别？尤其是自动同步相关的步骤。 https://www.yuque.com/kenshin/simpread/pwpnsx

好的我已经解决了这一问题，是我的坚果云同步有问题，非常感谢！

**Comment by Kenshin** [comment]
小事情，解决就好，我关闭这个 issues 了。

***

这两天遇到了恶意低分的用户... 要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
