### ISSUE TITLE
滴答清单导入一直卡在授权界面

### ISSUE THREAD

**Issue by rjs520** [Kenshin/simpread#4829]
![image](https://user-images.githubusercontent.com/87847751/205446242-33069fb7-f375-4e1d-8ad5-636abdb33c30.png)
滴答清单一直卡在授权界面

**Comment by Kenshin** [comment]
什么浏览器，之前说在 少数派的页面也不行吗？

要是有可能的话，试试 Edge 

另外，其他插件能正常使用吧？

**Comment by rjs520** [comment]
其他插件暂时没有测出问题，谷歌浏览器，之前说的在少数派页面也不行



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2022年12月3日(周六) 晚上11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 滴答清单导入一直卡在授权界面 (Issue #4829)




 
什么浏览器，之前说在 少数派的页面也不行吗？
 
要是有可能的话，试试 Edge
 
另外，其他插件能正常使用吧？

**Comment by Kenshin** [comment]
嗨，你可以再试试，应该没问题了。

**Comment by Kenshin** [comment]
我关闭这个 Issues 了

***

无故被恶意刷了两个两星… 要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
