### ISSUE TITLE
请问是否支持关闭阅读模式中的描述显示？

### ISSUE THREAD

**Issue by richex-cn** [Kenshin/simpread#4830]
![image](https://user-images.githubusercontent.com/25103518/205451365-606dbabe-1e5d-4841-8db6-b4016856e227.png)

**Comment by Kenshin** [comment]
嗨，这个插件应该可以满足你的需求。

https://simpread.ksria.cn/plugins/details/vrjJ4aJ8v

**Comment by richex-cn** [comment]
@Kenshin 链接似乎无法打开，跳转到了 http://ksria.com/simpread/404.html

**Comment by Kenshin** [comment]
https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v

**Comment by richex-cn** [comment]
尝试了导出 MD, PDF, HTML 都不包含描述，插件页面中的这一段描述是不是不正确？

![image](https://user-images.githubusercontent.com/25103518/205491413-57cb3bb0-890b-4772-8725-5d0bbd1c4eb4.png)
