### ISSUE TITLE
知乎回答页阅读模式解析错位

### ISSUE THREAD

**Issue by ProudBenzene** [Kenshin/simpread#4835]
网站示例：https://www.zhihu.com/question/28190855/answer/2756803888

打开阅读模式后，按理来说本来应该解析有这几张图片的文章：![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/202212042244421.png)

但是事实上解析的却是这个回答下方，还处于折叠状态的这个回答：![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/202212042245273.png)![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/202212042246405.png)

尝试过右键「将选中内容在阅读模式中打开」，依然无效，麻烦大大看一下是我的操作失误还是插件问题🤔

其他知乎回答页面也有遇到过类似错位问题。

**Comment by Kenshin** [comment]
没有问题，看下图

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/81074/205541857-0a2026ce-572a-4167-975b-b2d955c1d33d.png">

然后看你的这里是否跟下图一样？

<img width="513" alt="image" src="https://user-images.githubusercontent.com/81074/205541895-f14fca71-d486-4f1c-a601-dc28ae1f7937.png">

不一样的话，可切换。

选项页 → 站点管理，看下图，选择手动同步适配规则

<img width="902" alt="image" src="https://user-images.githubusercontent.com/81074/205542054-e1becf50-8110-4809-86da-a200de9bcfe0.png">

最后重启浏览器，如果还是不行的话，**隐身模式下仅使用简悦的方式** 看看是否是其它扩展造成的干扰？
