### ISSUE TITLE
知乎公式导出markdown或者pdf，解析出现问题，重复出现

### ISSUE THREAD

**Issue by cwbctr1** [Kenshin/simpread#4836]
已经把github中相关的解决方案都尝试了一遍，包括：
1. 将 zhuanlan.zhihu.com 加入到延迟加载列表中
2. 安装知乎阅读辅助增强插件
3. 将知乎下滑到最低部，保证所有公式都已正常渲染。

以上几种方式都测试过（同时采用、分别采用、组合采用，尝试了各类所有可能的解决手段及各种手段的组合情况）均无法实现正常解析公式。

网址：https://zhuanlan.zhihu.com/p/450089282
**阅读模式下显示正常：**
<img width="767" alt="image" src="https://user-images.githubusercontent.com/22217228/205506765-40ba74a1-b6ac-418d-b35c-4bfaec822633.png">

**obsidian中公式出问题**
<img width="759" alt="image" src="https://user-images.githubusercontent.com/22217228/205506829-6c49aa4f-dc19-445a-9988-070f7f4dec49.png">

**稍后读中公式出问题**
<img width="808" alt="image" src="https://user-images.githubusercontent.com/22217228/205506875-936c4235-222c-4399-bd35-04ac4033a826.png">

**导出的PDF公式出问题**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/22217228/205506896-8973b5b3-d128-4171-9802-17a0fb2c9d48.png">

**已加入延迟加载列表**
<img width="456" alt="image" src="https://user-images.githubusercontent.com/22217228/205507155-5cefcf90-0648-4062-b444-b081f01059dc.png">

**已安装知乎阅读辅助增强**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/22217228/205507195-4966e464-e32e-4203-b20f-636948331db0.png">

**已保证所有公式在网页中已经正常渲染**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/22217228/205507227-c7baf31c-2ac1-48aa-848e-3e6e4d01e0a0.png">

**Comment by Kenshin** [comment]
emmm  我这边没有问题

![image](https://user-images.githubusercontent.com/81074/205542300-67021eeb-59cf-41c0-a6be-669b889dcf28.png)

另外，PDF 应该是不行，它跟 Markdown 行为不一样，如果你非要使用 PDF 的话，可以试试将 Markdown → PDF

下面是我导出的效果。

[拉格朗日恒等式在圆锥曲线化简中的妙用.txt](https://github.com/Kenshin/simpread/files/10150401/default.txt)

**留意下**

把 `zhuanlan.zhihu.com` 加入延迟加载列表，然后重启浏览器，确保延迟加载列表里面的值生效。

加入延迟加载后的效果是这个页面不会自动进入阅读模式。

**Comment by nachifur** [comment]
> “可以试试将 Markdown → PDF”。

输出方式中没有“->Markdown → PDF”。现在依然不支持知乎文章的pdf保存吧？

**Comment by Kenshin** [comment]
> 输出方式中没有“->Markdown → PDF”现在依然不支持知乎文章的pdf保存吧？

我的意思是：通过第三方工具 e.g. Typora 打开这个 md 然后手动转换为 PDF

**Comment by nachifur** [comment]
> > 输出方式中没有“->Markdown → PDF”现在依然不支持知乎文章的pdf保存吧？
> 
> 我的意思是：通过第三方工具 e.g. Typora 打开这个 md 然后手动转换为 PDF

好吧，刚搜了一下`Typora`，需要付费哈。

个人刚刚尝试的可行替代方案（导出带公式的知乎文章）：
simpread（+知乎阅读辅助增强）->导出`.md`->vscode中打开（Markdown Preview Enhanced）->右键预览页面->open in browser->浏览器打印pdf。

**Comment by nachifur** [comment]
非常期待：使用simpread一键导出带公式的知乎文章！

> > 输出方式中没有“->Markdown → PDF”现在依然不支持知乎文章的pdf保存吧？
> 
> 我的意思是：通过第三方工具 e.g. Typora 打开这个 md 然后手动转换为 PDF

**Comment by Kenshin** [comment]
> 非常期待：使用simpread一键导出带公式的知乎文章！

emmm 我研究下。 😂

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
