### ISSUE TITLE
公众号页面无法标注（某个页面）

### ISSUE THREAD

**Issue by bxz400** [Kenshin/simpread#4837]
https://user-images.githubusercontent.com/48462903/205536851-95cf0ec6-1233-4ac3-a25f-c5db5f2df084.mov

- 操作系统  MacOS

- 浏览器版本 edge 版本 107.0.1418.68 (正式版本) (arm64)
- 简悦版本 最新版

**请描述你的问题**
加载微信公众号界面，文字无法标注，但图片可以标注。而且，类似情况不止一次出现，不局限于微信公众号，但以公众号为主。
有时候重新进入几次就可以标注，有时候完全无法操作。
所以，这是平台问题呢？还是简悦的问题呢？

**Comment by Kenshin** [comment]
请告诉出问题的 URL，另外其它网页，如 少数派的 e.g. https://sspai.com/post/69972 也存在你说的问题吗？

**Comment by bxz400** [comment]
> 请告诉出问题的 URL，另外其它网页，如 少数派的 e.g. https://sspai.com/post/69972 也存在你说的问题吗？

https://mp.weixin.qq.com/s/PiAK7Oe0-gFmqU0Krg6W3Q
https://mp.weixin.qq.com/s/4ixStCBwTjWmp1YzkxdwfQ
这两个都有问题。以前出现过类似问题，但那些网页我都没记下来……
少数派这个链接没有任何问题。

**Comment by Kenshin** [comment]
我测试了你视频提到的位置是没问题的。

<img width="997" alt="image" src="https://user-images.githubusercontent.com/81074/205546088-c20f3ff2-fbc1-4220-af00-24700b21dbe8.png">

在**隐身模式下仅使用简悦的方式** 看看是不是其它扩展造成的干扰。

**Comment by Kenshin** [comment]
Cool 解决就好。
***

无故被恶意刷了两个两星   👿  … 要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
