### ISSUE TITLE
导出到 obsidon 时文件名问题

### ISSUE THREAD

**Issue by wnlei** [Kenshin/simpread#4841]
使用导出全文到 obsidian 选项，发现导出的文件里面没有前面的 「5-」这样的序号，但批注里面有。
<img width="960" alt="2c972f5881a127e773e2c4b5804e07c" src="https://user-images.githubusercontent.com/76551489/205564256-13af846f-2c71-4b22-9ff2-885151391bfd.png">
<img width="712" alt="5759ffa52439fc5c8c6d77ecc4ed583" src="https://user-images.githubusercontent.com/76551489/205564277-692c2b96-87fb-4943-8e3c-8e62864df525.png">
求助是否哪里还需要再进行设置？非常感谢！

**Comment by Kenshin** [comment]
这个功能叫做 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2)，教程 [看这里](https://www.yuque.com/kenshin/simpread/wkswh7)

除此之外，导入到 Obsidian 用的哪种方式？每种方式的设置略有不同。

如果动手能力强的话并且没有太多稍后读数据的话，可以试试 [Obsidian 配置库](https://www.yuque.com/kenshin/simpread/psugef) 方案。

PS：对应的教程里面也有如何合并 Obsidian 库的说明

**Comment by wnlei** [comment]
哦。
我看了导出时命名的方式，是在加入稍后读以后，保存时才会有前面的序号。想请教一下，如果不加入稍后读，有没有方法设置成前面也有序号。
谢谢！
