### ISSUE TITLE
同时设置了原文和标注导出不同目录，原文生效了，标注还是进入了默认目录

### ISSUE THREAD

**Issue by isFire** [Kenshin/simpread#4842]
如图，我设置了原文进 Original 目录，标注放到 Annote 目录，但是实际情况是原文导出到了正确目录，标注导出位置在父目录
![telegram-cloud-photo-size-5-6082650109457314358-y](https://user-images.githubusercontent.com/31426767/205582879-63ab67d7-0f82-486b-8051-3f253050d996.jpg)
![image](https://user-images.githubusercontent.com/31426767/205582904-6bf2b677-2cbf-44a6-8b41-e55533f50236.png)

**Comment by Kenshin** [comment]
设置有问题...

1. 目前的版本暂时不支持同时设定两个相同的 `extension` 也就是你截图中设置了两个 `md` 是没法判断的，只有第一个 `md` 生效了。

2. 如果第一个 `md` 是原文的话，需要加 `type` 当省略 `type` 时，会同时包含全文和标注。（这点在文档中说明）

如果想要实现你的诉求，第一个 `md` 改成 `assets` 也就是使用 **md + assets 方式** 避免了我说的问题1

**Comment by isFire** [comment]
> 设置有问题...
> 
> 1. 目前的版本暂时不支持同时设定两个相同的 `extension` 也就是你截图中设置了两个 `md` 是没法判断的，只有第一个 `md` 生效了。
> 2. 如果第一个 `md` 是原文的话，需要加 `type` 当省略 `type` 时，会同时包含全文和标注。（这点在文档中说明）
> 
> 如果想要实现你的诉求，第一个 `md` 改成 `assets` 也就是使用 **md + assets 方式** 避免了我说的问题1

好的，感谢感谢

**Comment by isFire** [comment]
> 设置有问题...
> 
> 1. 目前的版本暂时不支持同时设定两个相同的 `extension` 也就是你截图中设置了两个 `md` 是没法判断的，只有第一个 `md` 生效了。
> 2. 如果第一个 `md` 是原文的话，需要加 `type` 当省略 `type` 时，会同时包含全文和标注。（这点在文档中说明）
> 
> 如果想要实现你的诉求，第一个 `md` 改成 `assets` 也就是使用 **md + assets 方式** 避免了我说的问题1

主要是看文档上面写这个多个示例，然后以为是可以配置多个来着

**Comment by Kenshin** [comment]
> 主要是看文档上面写这个多个示例，然后以为是可以配置多个来着

okay 谢谢提示，我会优化下文档说明。

***

无故被恶意刷了两个两星   👿  … 要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
