### ISSUE TITLE
搜索引擎结果页联动

### ISSUE THREAD

**Issue by woniuxia** [Kenshin/simpread#4844]
希望在搜索引擎进行搜索时，可以检索已剪藏的文章，显示在右边，帮助解决搜索问题

**Comment by Kenshin** [comment]
嗨

你提到的功能最早就是简悦的功能…

细节 [看这里](https://simpread.pro/docs/#/%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%8C%B9%E9%85%8D?id=%e6%90%9c%e7%b4%a2%e5%bc%95%e6%93%8e%e5%8c%b9%e9%85%8d)
