### ISSUE TITLE
系统暗黑模式下进行剪藏时 Logseq 内建标注和独立窗口编辑标注内容对比对不足

### ISSUE THREAD

**Issue by KanswerG** [Kenshin/simpread#4846]
1. 在暗黑模式下打开原文并进行剪藏后打开logseq对应内容
<img width="453" alt="截屏2022-12-06 12 02 17" src="https://user-images.githubusercontent.com/76435190/205810891-b496429e-deb5-4a81-ae36-6fab1c4cf9e4.png">
2. logseq内置右侧标注页面，对比度非常低，看不清楚
<img width="520" alt="截屏2022-12-06 12 03 57" src="https://user-images.githubusercontent.com/76435190/205810876-36b0a8e3-e206-4885-9e15-136ea06afd09.png">
3. logseq内置独立标注页面，问题同上
<img width="1019" alt="截屏2022-12-06 12 03 41" src="https://user-images.githubusercontent.com/76435190/205810886-74b59544-916f-4f56-b853-99f44f08c840.png">

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

本地快照和标注系统增加了**自动暗色模式**功能，所以此问题自动修复了。

![2023-01-05_11-06-05](https://user-images.githubusercontent.com/81074/210696804-95b7cf81-ae71-4a69-a74a-b63cdefd3b1c.gif)

除此之外，1.1.4 版还包括下面的一些功能：

## 下载地址

- [包含多种渠道下载](http://ksria.com/simpread/docs/#/Sync?id=下载)

## 更新日志

- [更新日志](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792)

## 新增 💄 

### 朗读

将正文转换为语音并播放，与 Edge 内置的大声朗读功能一样，均来自 Microsoft Azure 的语音服务。

<img width="3650" alt="TTS@plugin" src="https://user-images.githubusercontent.com/81074/206418879-c6ba7b85-e706-4741-b0b1-2e5123f2493d.png">    

- 插件端 [朗读](https://github.com/Kenshin/simpread/discussions/4833)

- 内置到 [稍后读极速版的本地快照](http://ksria.com/simpread/docs/#/TTS?id=内置到本地快照)
