### ISSUE TITLE
导入到 Notion 出现无法导入的情况（附解决方案）从 2022年12月6日 开始出现此问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4849]
> 今天（ 2022年12月6日）开始导入到 Notion 会出现无法导入的情况

# 2022年12月26日更新

此问题已经解决，解决方案 https://github.com/Kenshin/simpread/issues/4849#issuecomment-1364940026

## 先说原因

Notion API 发生错误导致，跟今年 6 月份发生的问题一样，均为 Notion 官方导致 😂

我已经联络 Notion 官方，有后续说明我会在这里更新。

## 问题现象

进入阅读模式 → 右下角 → 动作 → 导出 Notion 

![image](https://user-images.githubusercontent.com/81074/205895663-fbe90780-da21-426c-9c70-16919eff9b93.png)

导入后会发生无法导入的情况，如下图

<img width="317" alt="image" src="https://user-images.githubusercontent.com/81074/205895098-e8609358-3385-49fc-886b-d2d97914c06d.png">

## 临时解决方案

此问题仅出现在 Database Page，当为普通 Page 时则无法这个问题，所以再为彻底解决前需要如下操作

新建一个叫做 **来自简悦的稍后读 Page** 的普通 Page

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/81074/205896152-132538f8-fcd9-44dd-94c1-1ada1a1172ab.png">

选项页 → 服务 → 授权管理，找到刚才新建的 Page 并选择授权它。

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/81074/205896301-a70c84b1-ca4e-47b8-8d40-2d2418e469df.png">

## 效果

https://user-images.githubusercontent.com/81074/205899196-73d10c16-a07c-4a79-918b-61059285ad77.mp4

## 后续

然后可以手动将这个 Page 在转移到原来的 Database 里面，**当手动拖拽到 Database 后仍支持 [导入到 Notion 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572)，但需要手动触发。**

https://user-images.githubusercontent.com/81074/205901114-004b7b76-8deb-4008-9748-c35c65b809ca.mp4

**Comment by est7** [comment]
notion真难顶

**Comment by maxpowerduncan** [comment]
这样确实能解决保存到notion的问题，但貌似图床就全部不能用了，全部图片都保存不下来

**Comment by Kenshin** [comment]
@maxpowerduncan

图床可以使用，并不受此影响。

**Comment by maxpowerduncan** [comment]
不行呢，到notion上只有一张图片，正文内的图片都没了

**Comment by uf1y** [comment]
以后只能靠手工拖拽到旧的页面了？

**Comment by Kenshin** [comment]
> 以后只能靠手工拖拽到旧的页面了？

并不是「以后」都这样，我联络了 Notion 等后续结果。

**Comment by Cyber-H** [comment]
请问NOTION有回应了吗？手动不是很方便啊。感谢。

**Comment by Kenshin** [comment]
> 请问NOTION有回应了吗？手动不是很方便啊。感谢。

当然没有…如果有进一步消息的话，肯定会在这里和简悦渠道大家的。

**Comment by jadetexy** [comment]
没有在 Notion查到这篇文章，解决方案请看这里

**Comment by MegaDom** [comment]
> > 请问NOTION有回应了吗？手动不是很方便啊。感谢。
> 
> 当然没有…如果有进一步消息的话，肯定会在这里和简悦渠道大家的。

作者大大，我发现“导入标注到Notion”这个功能是可以导入到Notion的database里面的，这个功能与“保存到Notion”有特别大的不同吗？ 从这个角度看能不能绕开这个问题呢？

**Comment by Kenshin** [comment]
@MegaDom 

导入全文 → 私有 API（所以有图床功能）
导入标注 → 共有 API

此次问题为私有 API 修改造成的问题，所以导入标注是没问题的。

**Comment by difeiqi** [comment]
保存是可以保存，但只能把网页存到“来自简悦的稍后读”这个普通page里面，
我以前是保存到一个database里的，
然后需要把“来自简悦的稍后读”这个普通page里面保存的网页，手工再拖到以前的database中。

大家也是这样的操作么？

**Comment by MegaDom** [comment]
> 保存是可以保存，但只能把网页存到“来自简悦的稍后读”这个普通page里面， 我以前是保存到一个database里的， 然后需要把“来自简悦的稍后读”这个普通page里面保存的网页，手工再拖到以前的database中。
> 
> 大家也是这样的操作么？

是的。

拖到database后，再用“导入标注到Notion”可以继续补全保存的图标、来源等信息

**Comment by Kenshin** [comment]
嗨，各位。

因为这两天感觉（估计 🐑 了）等我好一些后会解决这个问题。

**Comment by MegaDom** [comment]
> 嗨，各位。
> 
> 因为这两天感觉（估计 🐑 了）等我好一些后会解决这个问题。

请务必保重身体！

**Comment by OscarZs** [comment]
救，没看到这个，配了一晚上以为那里漏了...
自己配下配置都试过了

**Comment by Kenshin** [comment]
@OscarZs 

Notion 不给我回信，就只能自己解决了，等我不🐑 后舒服点了就开始解决…

**Comment by OscarZs** [comment]
辛苦了，我还以为是我的问题🤣

**Comment by Kenshin** [comment]
嗨，各位：

🐑 了后第五天，预计明天给出解决方案。

**Comment by Kenshin** [comment]
# 「修复」了 Notion 无法导入的问题

嗨，各位 Notion 用户。

> 简单的复盘下这个问题的始末。

2022年12月6日开始出现，得到用户报告后，我马上就通过 Notion 的朋友告知了 Notion 官方，**但一直到现在都没有没有得到反馈**，因严格意义来说并不算是 Bug，而 API 修改 Notion 也没有通知（私有 API 缘故），所以简悦就显得有些「被动了」。

迫于「无奈」，每次修改后简悦只能被动修改，为了避免这种情况的反复发生，所以我决定：

>  将**导入到 Notion 插件化**，专门用于这种情况。

## 🔌 导入到 Notion 插件

## 📥 下载地址

https://github.com/Kenshin/simpread/discussions/4954

## 🖥  同步助手用用户

可通过 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装

## 🌐 非同步助手用户

通过上面的链接安装。

## 📚 功能

插件具有扩展端全部功能，包括 Notion 图床，除此之外还具有：[在导入正文时可选不同的 Page 功能 ](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4496059)。

## 🔎 反馈

有任何使用上的疑问，请在 https://github.com/Kenshin/simpread/issues/4849 集中讨论，不要重复建 Issues 。

## 💡 最后

现在放出来先给群里的用户内测，如果没有问题预计明天或今天稍晚时对外发布。

**Comment by xchyyb** [comment]
已成功安装并配置导入到 Notion 插件，现在可以像以前一样正常导入了，感谢 @Kenshin

**Comment by Kenshin** [comment]
@xchyyb 

Cool，解决就好。 👍 

PS：对部分用来说，还有个大杀器：[在导入正文时可选不同的 Page 功能 ](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4496059)。

**Comment by Cyber-H** [comment]
已成功安装并配置开始使用，现在可以像以前一样正常导入了，感谢 @Kenshin，我的理解是插件管理群配置只需要第一次就可以吧，后续还是正常使用动作里面的导出到NOTION。刚测试了可以，不知道是否正确，谢谢作者啦，

**Comment by Kenshin** [comment]
@Cyber-H 

是的，插件管理器只是帮你把插件成功安装到使用同步助手的扩展端而已，安装后就可正常使用插件了。

**Comment by MegaDom** [comment]
太棒了，配置完成已经完美恢复了！

**Comment by Kenshin** [comment]
@MegaDom 

解决就好。

**Comment by Kenshin** [comment]
嗨，各位。

> [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) 已经正式发布 🎉 ，以下是这个插件的正式介绍。


# 🔌 插件端

插件端拥有比扩展端更灵活的方案，也是简悦官方建议首选方案关于插件端的详细说明 [请看这里](https://simpread.pro/docs/#/Notion)。

## 📥 地址

https://simpread.ksria.cn/plugins/details/OpaogjT8KJ

## 🔎 与扩展端的区别

![](https://imgs.zhubai.love/556ec9eff25542aabd318a8803ed70db.png)

通过上表可以看到，除了无法在稍后读中使用外（下个版本支持），扩展端具有的功能，插件端也都具有，但插件端还可支持随时更改不同的 Page 功能。

同时，因为插件的更新不依赖与扩展端，可随时更新，具有更好的时效性。

## ⌨️ 快捷键

- `n t` → [一键导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=导入正文)

- `q n t` → [选择不同的 Page 后导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=选择任意Page导入)

- `z n t` →  [配合自动化辅助增强插件使用](https://simpread.pro/docs/#/Notion?id=当加入稍后读时自动导入)

## 🔌 功能

1️⃣ 可获得 Notion 的个级目录

2️⃣ [图床](https://simpread.pro/docs/#/Notion?id=%E5%9B%BE%E5%BA%8A)

3️⃣ 导入正文到 Notion

4️⃣ [选择不同的 Page 后导入全文到 Notion](https://simpread.pro/docs/#/Notion?id=%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8Fpage%E5%AF%BC%E5%85%A5)

## 💡 用法

1️⃣ 快捷键导入

2️⃣ [手动导入](https://simpread.pro/docs/#/Notion?id=%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5)

3️⃣ [加入稍后读时自动导入](https://simpread.pro/docs/#/Notion?id=%E5%BD%93%E5%8A%A0%E5%85%A5%E7%A8%8D%E5%90%8E%E8%AF%BB%E6%97%B6%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%85%A5)

4️⃣ [在 Assistive Touch 设置 Icon 方便一键导出](https://simpread.pro/docs/#/Notion?id=%E6%94%AF%E6%8C%81-assistive-touch) 

📈 安装与升级
---

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

***

最后，我将关闭这个 Issues，有任何问题可继续讨论。

**Comment by imdigi** [comment]
回来点个赞，这次更新插件以后，重复剪藏一篇文章时，之前没有加载到的图片会直接更新出来。挺好的~~~

**Comment by Kenshin** [comment]
@imdigi 

哈哈，是的。

所以我才说「插件方式比扩展端的剪藏效果更好」😄

**Comment by Kenshin** [comment]
嗨，各位。

> 两个关于 Notion 的相关更新~

# 1️⃣ 祝：[导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) + [导入到 Notoin 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572) 下载量**超 60K！**

![image](https://user-images.githubusercontent.com/81074/212005885-67a4a8bb-9779-4aa2-bbab-15b5d12717bd.png)

# 2️⃣ 导入到 Notion + 导入到 Notoin 辅助增强插件 双叒叕 小幅更新了版本

## 🔌 [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954)  v1.0.3

• `Optimize` 导入到 Notion 逻辑

• `Fix` 当加入稍后读并且修改稍后读标题后仍按照原标题保存的错误

## 🔌 [导入到 Notoin 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572)  v1.2.3

• `Optimize` 题图、Favicon 因不是以 http 导致优化失败的问题。

• `Optimize` 当 Token 或 Page ID 填写错误时的精准提示。

• `Optimize` 使用 `url` 作为增强导出是否是同一 Page 的判断标注。

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过上面的链接安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

3️⃣ 如果已安装上述插件，需要使用 插件管理器升级的话 [请看这里](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C)。

**Comment by Miaoyifei-mz** [comment]
@Kenshin 您好，我在使用自动导入到notion插件的过程中，授权完成后刷新页面，还需要再进行授权。重新安装插件也无法解决。

**Comment by Kenshin** [comment]
@Miaoyifei-mz 

如果是显示下图的内容，则是正常的。（已经成功授权）

<img width="511" alt="image" src="https://user-images.githubusercontent.com/81074/212253232-bb5d3458-3651-4e95-9145-8756fc4e60fc.png">

另外，是否使用了自动同步功能？如果是的话，请使用 https://github.com/Kenshin/simpread/issues/4849#issuecomment-1379927538 提到的方案

<img width="456" alt="image" src="https://user-images.githubusercontent.com/81074/212253453-682313b2-6aef-438c-be9f-232230d1932d.png">

**Comment by Kenshin** [comment]
@Miaoyifei-mz 

小事情，解决就好 😄

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  

### ▎ 如果你在使用简悦导入 Notion 无法使用 Notion 图床的话，请看此解决方案。

### ▎内置 Cloudinary 图床（用来替代 Notion 图床），国内访问速度不错，免费份额足够个人使用。为什么这么做，看下面的说明

***

## 📖  写在前面

Notion 图床使用了 Notion 私有 API（甚至于导入到 Notion 也是如此 ），但 **Notion 私有 API 并没有那么稳定，基本上 Notion 每次大的升级都会造成无法使用的问题，差不多每年 1~2 次。** 比如：

- **2022年7月23日 [标题含有 CJK 字符就会出现无法保存的问题](https://github.com/Kenshin/simpread/issues/4237)**，但好在这次事件 Notion 官方快速修复了。

- **2022年12月6日 [因为 API 后端参数修改导致无法导入到 Notion Page 的问题](https://github.com/Kenshin/simpread/issues/4849)** 导致了「坏」了很久很久（现在已经好使了）

- **2023年9月7日 [发生了 Notion 图床无法使用的问题](https://github.com/Kenshin/simpread/issues/5917)（截至到现在仍未好使）**

因为是私有 API 所以 Notion 官方的任何改动都「合理」，毕竟理论上这些 API 只有 Notion 自己用。

但对于简悦来说就非常被动了，2022年12月6日后为了杜绝这个问题，简悦发布了 [导入到 Notion 插件](https://github.com/Kenshin/simpread/discussions/4954)，脱离了扩展端，因而能更快的响应 Notion API 的无故改动，但毕竟仍受 Notion 的「制约」，进而发生了这次 Notion 图床事件，导致无法使用...

## 💡 解决方案

为了不再一次次的被动，所以在【导入到 Notion 插件 1.1.0 版】 **增加了 Cloudinary 图床方案**，不再绑定 Notion 从而彻底的解决了这个问题。

对于用户来说，仅需要注册 Cloudinary 图床，而注册一个图床的时间远比被动折腾要简单很多。

## 🔐 权限

使用 Cloudinary 图床 **需要调用简悦自己的服务器，所以仅针对高级账户权限**，如有必要 [请升级为高级账户](https://simpread.pro/price)。

## 🗂 Cloudinary 图床

[Cloudinary](https://cloudinary.com/) 是老牌的图床服务，**免费版每月 25 Credit，每个 Credit 可支持 1GB 存储或 1GB 带宽**。

相当于：**每月 13GB 存储**以及 **12GB 带宽**的图床，且**国内访问速度不错**，免费份额足够个人使用。

## 🔌 配置

请看 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995 内有详细说明。

如果你动手能力稍强的话，甚至于都不需要看任何教程，直接注册登录 &  打开 [Dashboard 页面](https://console.cloudinary.com/console) 即可，留意下图

<img width="2942" alt="2023-09-27_11-39-14" src="https://github.com/Kenshin/simpread/assets/81074/29f6003c-c45d-49df-8bc5-f10c6d76253f">

请将 ➊ ➋ ➌ 分别填入。

注意：Folder 文件夹可为空，也可为任意值（ 建议使用 `simpread` ），不必事先在 Cloudinary 创建相应目录。

## 📈 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 🔗 关联

https://github.com/Kenshin/simpread/issues/4955

***

我关闭这个 Issues 了，有任何问题随时在这里讨论。

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
