### ISSUE TITLE
果壳网未正确适配和一些小问题+请求适配bolide.lamost.org+36kr需要更新

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Kenshin/simpread#485]
1. 
果壳网描述内容应该是
`[[{$('meta[name=Description]').attr('content')}]]`
其中，Description中的D应该是大写而不是小写
此外，果壳网的描述框有问题（适配完之后）
![2019-5-4 12-23-37](https://user-images.githubusercontent.com/20567492/57173776-8eeb8f80-6e67-11e9-8f91-8bd8922ceaed.png)

2.
请求适配bolide.lamost.org

3.
36kr更新了，旧的高亮区域等已经没用了

**Comment by Kenshin** [comment]
嗨，谢谢反馈，本周要更新一批新站，到时会通知你。

**Comment by Kenshin** [comment]
36kr.com 与 guokr.com 的错误已修复。

bolide.lamost.org 已经可以在新版中自动适配，无需单独适配。

***

更新方法

- 点击 ➊ 即可
![image](https://user-images.githubusercontent.com/81074/57358987-2a06a100-71a9-11e9-89c8-18249c6e3fe7.png)

- 分别点击 ➊ ➋ 即可


![image](https://user-images.githubusercontent.com/81074/57359096-676b2e80-71a9-11e9-81ec-ffaadf659013.png)

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
