### ISSUE TITLE
阅读模式图片上传丢失

### ISSUE THREAD

**Issue by Airmansy** [Kenshin/simpread#4851]
**微信公众号文章阅读模式下图片显示正常**
![1](https://user-images.githubusercontent.com/112327874/205933830-0fc81933-722e-42b9-a493-b51d96902c65.jpg)

**上传图床过程中，阅读模式中原本能看到的图片消失**
![2](https://user-images.githubusercontent.com/112327874/205934050-76ec343b-bb39-482f-b190-87d026e77c70.jpg)

**图片上传成功，同时触发自动化加入稍后读**
![3](https://user-images.githubusercontent.com/112327874/205934541-69474d77-7dd1-4c8b-a608-c1115c710fbd.jpg)

**到OB中极速模式下图片看不到**
![4](https://user-images.githubusercontent.com/112327874/205934714-3b4d16e7-a8d8-4e5b-9dec-5e67ecfe5c02.jpg)

**Comment by Airmansy** [comment]
https://mp.weixin.qq.com/s?__biz=Mzg4OTc1ODc4Nw==&mid=2247547029&idx=1&sn=5fe6c613ca274b21ca6652f1438aca98&chksm=cfe48db9f89304af4005db84899f890beb74def9946f7ee3f3b08e41fb33c21894c2fb75bc1d&mpshare=1&srcid=07245zKfP16Q7wI8uLKNorNq&sharer_sharetime=1658669293120&sharer_shareid=8063c387da0dfa3b98faea6460eb60f5&from=singlemessage&scene=1&subscene=10000&clicktime=1670338295&enterid=1670338295&sessionid=0&ascene=1&fasttmpl_type=0&fasttmpl_fullversion=6448500-zh_CN-zip&fasttmpl_flag=0&realreporttime=1670338295729&devicetype=android-30&version=28001e55&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&exportkey=n_ChQIAhIQopZcbx9aflr85SjJDEyVORLuAQIE97dBBAEAAAAAAF4uLiKF2yoAAAAOpnltbLcz9gKNyK89dVj0D%2BtNuuN75lKLNvIBcCeo4uARC%2BL0LztIzzLNS40aAkDYCpvELDGyfQvQR2Hj%2BTtkaafAzYELwsc8O0o%2F0guRI%2FtfCnZunO4mfFlL3FYlNQVw06qUTGQZ6yWrpURlcJIHHL2wipn%2BYwoCP98tvqFYYMxkjr18l5dHsMRvbDh4HdA%2F%2BSr0Ip%2FqjvpL8YV4fuj4OCJlaZ4NMJEE00rcgXMk54bc9NcnpLzdgm2OXz%2BL0JSRlb4cCSMSm7TU0Cb50YaMUIt%2BQCrLRKo%3D&pass_ticket=2mM5d7rqY5zYjDbTJcWsSyIGOiiggx%2FIj7q8KLXdzDDCg0mTvm4%2F8Ie8NrO1eQYE&wx_header=3

发自坚果 R2

Kenshin Wang ***@***.***> 于 2022年12月6日 下午10:36写道：


公众号的图片有限制，因为你用了 Notion 图床，所以没问题。

导入到 Obsidian 则会触发这个限制，所以你需要使用 md + assets 方式<https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604>

另外，最好把公众号的 URL 我发过来。

―

**Comment by Kenshin** [comment]
导入到 Obsidian 是没问题的

<img width="925" alt="image" src="https://user-images.githubusercontent.com/81074/206080310-542e488a-b505-4058-8398-d23e96359d41.png">

但最好使用我之前说的 md + assets 方案。
