### ISSUE TITLE
简悦同步助手（MAC）无法打开

### ISSUE THREAD

**Issue by PenguinDang** [Kenshin/simpread#4853]
-->

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统  MacOS 13.0.1 

- 浏览器版本 edge版本 108.0.1462.41 (正式版本) (arm64)

- 简悦版本 2.2.0.520
- 同步助手版本1.1.3

- 发生问题的地址 <请填写你的地址l>

简悦同步助手（MAC）无法打开，反复删除重装后仍无法打开。但仍然可以同步，只是无法打开应用程序页面。

**Comment by Kenshin** [comment]
Mac 菜单栏里面有个 icon 打开它也不行吗？

**Comment by PenguinDang** [comment]
不行的，后台有在运行，但是上面的状态栏里都不会有icon

**Comment by PenguinDang** [comment]
哦哦，可以了，我用bartender给隐藏了

**Comment by Kenshin** [comment]
okay 没问题就好 😄

***

要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
