### ISSUE TITLE
简悦稍后读无法打开

### ISSUE THREAD

**Issue by jsntn** [Kenshin/simpread#4856]
- 操作系统 **Windows 10**

- 浏览器版本 **Vivaldi 5.5.2805.50 (Stable channel) (64-bit)**

- 简悦版本 **2.2.0**

- 同步助手版本 **1.1.3**

- 发生问题的地址 chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

**问题描述**

> 在先启动了同步助手的情况下，简悦稍后读无法打开，如下图，

![20221207095805](https://user-images.githubusercontent.com/1805410/206076020-20ec43d4-24a1-44f7-8484-f747cb5a842e.jpg)

关闭同步助手后，可以打开，如下图，

![20221207095850](https://user-images.githubusercontent.com/1805410/206076132-ce0105ff-7681-432a-9e81-3574c77e74bd.jpg)

**Comment by jsntn** [comment]
似乎不是这个原因，因为我试了手动方式，没有找到 null 呢，

![image](https://user-images.githubusercontent.com/1805410/206084669-8184f040-28c0-460b-8300-22bb1eb706fc.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4856#issuecomment-1340569574

是的。你可以试试历史记录 https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a 还原。

**Comment by jsntn** [comment]
> > https://github.com/Kenshin/simpread/issues/4856#issuecomment-1340569574
> 
> 
> 
> 是的。你可以试试历史记录 https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a 还原。

嗯嗯，等我试一下。

只是我的坚果云的历史记录相对较旧了，我会试着先和导出的对比一下。

回头来更新结果。😀
