### ISSUE TITLE
升级到 1.1.2.5005 如发现个别网站（如 CSDN ） 效果不佳，请看这里

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#486]
![image](https://user-images.githubusercontent.com/10437293/57216163-ab332c00-7021-11e9-8eb5-ec270b058782.png)

如图所示，代码内容出现在了代码行数字下面。

url地址：https://blog.csdn.net/gyw520gyw/article/details/52692810

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/57216355-36142680-7022-11e9-958e-bdd217019803.png)
😓，要关闭这个纯粹模式才能正常

**Comment by Kenshin** [comment]
这不算是错误。
CSDN 的界面太奇葩了，各种高亮支持，你可以按照上图进行设置，或者通过一些自定义样式把多余的部分隐藏掉。

**Comment by Kenshin** [comment]
我把这个 issues 置顶了，顺便改了个名字。  😊 

***

也可以使用 [代码高亮](https://simpread.ksria.cn/plugins/details/klGUASLasg) 插件来实现高亮功能。

**Comment by AriaLyy** [comment]
👍

**Comment by Kenshin** [comment]
嗨，周末好~

此问题已经解决了，详情请看 https://github.com/Kenshin/simpread/issues/500

我将关闭此 issue 如有问题请再重新开启。
