### ISSUE TITLE
每日一文辅助增强插件不生效

### ISSUE THREAD

**Issue by NNGTHB** [Kenshin/simpread#4862]
![20221207172905](https://user-images.githubusercontent.com/115760745/206142753-eb07ea65-847a-4568-a416-886ea0a0d449.png)
![20221207172947](https://user-images.githubusercontent.com/115760745/206142782-6b20f1ff-1ac1-4f49-8c8f-2fdc2e4b0a0b.png)
![20221207173058](https://user-images.githubusercontent.com/115760745/206142807-6b6245c1-c019-4cb4-a1ac-e3d140244e7e.png)

安装适配源和插件后仍没有显示出~~作者~~和题图，没显示作者是因为安装了删除描述插件🤐，关掉后正常。题图设置看看对否

![20221207174915](https://user-images.githubusercontent.com/115760745/206146332-15533df3-fa7f-4f36-ac9a-90bbebd25565.png)

![动画](https://user-images.githubusercontent.com/115760745/206143957-acbaa763-0c7a-4efc-bc94-92f3e14116e7.gif)

另外live editor会变成这样，是个bug吗😂

**Comment by Kenshin** [comment]
> live editor会变成这样，是个bug吗

不算是 Bug 因为 Live Editor 在这个页面上的某些内容被「污染」了。

> 作者没有显示

是不是你安装了 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v 这个插件？如果是的话，这个插件会干扰这个功能。

> 题图的问题

应该是你设置的问题，我增加了点对题图的定制化说明，细节 https://github.com/Kenshin/simpread/discussions/4857#discussioncomment-4329529

**Comment by NNGTHB** [comment]
ok，重新设置好题图后一切正常

**Comment by Kenshin** [comment]
Cool~
