### ISSUE TITLE
新人求助

### ISSUE THREAD

**Issue by ColdOxygen** [Kenshin/simpread#4866]
简悦持续更新，并且支持插件，新人非常期待简悦的体验。深度体验前，请教下是否支持全文搜索所有进入过阅读模式的网页？

**Comment by Kenshin** [comment]
嗨

> 请教下是否支持全文搜索所有进入过阅读模式的网页？

不支持。

因为你的这个需求不现实也不实际，要实现你的需求就需要把你的每个使用过阅读模式的页面都「保存」下来，这样才能实现你说的方式。

1. 这些保存的内容量太大了。
2. 并没有意义。
3. 隐私也没法得到实现。

但简悦可以做到：

1. 加入稍后读或标注后可以将当前阅读模式的正文保存到本地。

2. 标注的内容可以通过简悦内置的功能检索到。

3. 稍后读的本地快照，可以通过第三方工具 e.g. DEVONThinks、AnyTxt 检索到。

4. 加入稍后读的数据可以在 [搜索引擎](https://simpread.pro/docs/#/搜索引擎匹配) 中查看到。

**Comment by ColdOxygen** [comment]
谢谢K大的解释，有本地快照也够我用了。

**Comment by Kenshin** [comment]
哈哈，你这多了多久才回复 😂

关于之前提到的方式叫做 [知识库](https://www.yuque.com/kenshin/simpread/xr9wb8b4ap5rrzba) 这个链接里面含有一些说明和教程。

你可以对着配置下
