### ISSUE TITLE
面板定制器的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4867]
求教一下，那个面板定制器的勾选要怎么保存下来，谢谢啦。

_Originally posted by @1Eg0d in https://github.com/Kenshin/simpread/discussions/2342#discussioncomment-4334126_

**Comment by Kenshin** [comment]
@1Eg0d

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

如果使用自动同步的话，看下这个教程 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by 1Eg0d** [comment]
对不起，年底工作较忙，没有来看邮件，我没有在电脑上使用同步助手，只是单纯的想设置一下向joplin的导出在更明显的位置。另外，手机上使用kiwi安装拓展的zip，总是两三次就会发现拓展被清理掉了，拓展版本为2.2.0.520，kiwi相关如图，谢谢。
![Screenshot_2023-01-01-23-42-47-999_com kiwibrowser browser](https://user-images.githubusercontent.com/79033292/210176606-9375d854-1b08-4c7b-9acf-1c57f1ee5028.jpg)

**Comment by Kenshin** [comment]
> 只是单纯的想设置一下向joplin的导出在更明显的位置

那使用 https://www.yuque.com/kenshin/simpread/fcw60u 就行。

> 手机上使用kiwi安装拓展的zip

建议直接安装 Chrome 或 Edge 应用商店版本。`zip` 版在 PC 端如果不自解压的话，经常会被清理掉。这么看的话，手机端也说一个道理。
