### ISSUE TITLE
咨询：稍后读原文HTML和标注HTML覆盖问题

### ISSUE THREAD

**Issue by ibetax** [Kenshin/simpread#4869]
![](https://user-images.githubusercontent.com/62380280/206364868-d2f90ee2-2159-48b8-922e-af80f61609e9.png)
若同时设置了“稍后读”和“标注”的自动化导出到本地的HTML。

将文章添加到稍后读后，本地可以成功保持HTML。

![](https://user-images.githubusercontent.com/62380280/206365379-ee6597c0-4dc7-464b-b58c-3edebf694436.png)

但是在稍后读阅读，并添加标注后，会生成新的HTML，然后将**覆盖**掉稍后读生成的HTML（也就是原文）。

![](https://user-images.githubusercontent.com/62380280/206365730-cda28788-cd4d-4210-af55-6a755d989ebf.png)

有什么办法能同时保留两者吗？也就是标注能否在原文的HTML中生成？

另外，右上角的这个弹窗能默认隐藏吗？

![](https://user-images.githubusercontent.com/62380280/206365475-cf1bc88e-d6bc-4aaa-8bee-6eb27c763739.png)

**Comment by Kenshin** [comment]
嗨

你需要使用 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2) 方案，教程 [看这里](https://www.yuque.com/kenshin/simpread/wkswh7)。
