### ISSUE TITLE
1.1.2.5005导致youtube加载出错

### ISSUE THREAD

**Issue by sailtao** [Kenshin/simpread#487]
启用插件后youtube视频与页面的很多元素无法加载，新标签页打开无问题

**Comment by Kenshin** [comment]
youtube 没必要使用阅读模式，所以你可以把  youtube.com 加入到 [黑名单](http://ksria.com/simpread/docs/#/FAQ?id=%E9%BB%91%E5%90%8D%E5%8D%95) 

或者通过 [右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu) 直接加入到黑名单。

**Comment by sailtao** [comment]
只是浏览器启用了插件，并未对youtube使用阅读模式

**Comment by Kenshin** [comment]
谢谢回复。

虽然可以通过黑名单解决这个问题，但确实比较奇怪的情况…

你能稳定复现吗？

**Comment by sailtao** [comment]
能够稳定复现，刚刚重新启用了插件，再打开youtube后，点击所有菜单都无效，点击视频可以跳转到播放页面，但视频与页面的很多元素无法加载，将youtube.com加入黑名单后访问正常

**Comment by Kenshin** [comment]
黑名单肯定没问题的。😃

明天我再研究下，现在在外面呢。

**Comment by Kenshin** [comment]
这是我根据你的提示，进入（随机找了一个视频） https://www.youtube.com/watch?v=opLIsewMgBA  的界面

![image](https://user-images.githubusercontent.com/81074/57347830-41806280-7186-11e9-97bd-21b3e4c45351.png)

提示：
- 把 youtube.com 从黑名单移除；

- 进入 url

- 并未使用 简悦

**Comment by sailtao** [comment]
我把问题复现，并把操作过程录屏了，请从下方地址查看。
https://drive.google.com/file/d/1xtq0ipwimmIfF5COfJrwZoKP3NAYNXGy/view?usp=sharing

**Comment by Kenshin** [comment]
1.1.2.5005（含以上） 如果遇到 youtube.com 无法访问的话，请按照如下设置

解决办法
---
把 `youtube.com` 加入到 [黑名单](http://ksria.com/simpread/docs/#/FAQ?id=%E9%BB%91%E5%90%8D%E5%8D%95) 即可。

Chrome && Firefox
---
![image](https://user-images.githubusercontent.com/81074/57832466-52664f00-77ea-11e9-8217-3b58687b72ca.png)

Tampermonkey
---
![Xnip2019-05-16_14-44-14](https://user-images.githubusercontent.com/81074/57832546-7aee4900-77ea-11e9-9865-7e9de1e064fe.jpg)


暴力猴 
---
![Xnip2019-05-16_14-47-51](https://user-images.githubusercontent.com/81074/57832529-745fd180-77ea-11e9-9800-61da97f334f4.jpg)

**Comment by xiantang** [comment]
很窒息 没办法看youtube 希望能对代码进行优化 排查了很多的插件 终于找到了问题

**Comment by Kenshin** [comment]
@xiantang 

下个版本会解决这个问题。

**Comment by xiantang** [comment]
@Kenshin  也就是无法复现 bug 是吧。可以将域名为 `youtube` 的页面进行 block 吧

**Comment by Kenshin** [comment]
@xiantang 
当然可以了~ 你可以让这个 [issue 上面的描述](https://github.com/Kenshin/simpread/issues/487#issuecomment-492942360)。

**Comment by Songkeys** [comment]
先以为是浏览器问题、缓存问题……然后找了好久的插件，最后发现是这个导致的……太难受了，希望尽快修复一下。感谢～

**Comment by Kenshin** [comment]
各位，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，解决了此问题。

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

**Comment by Losk-x** [comment]
> 各位，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，解决了此问题。
> 
> 除此之外，1.1.3 还增加了如下的功能：
> 
> * 更友好的 [新手入门](http://ksria.com/simpread/guide)
> * 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/%E5%9D%9A%E6%9E%9C%E4%BA%91)  [语雀](http://ksria.com/simpread/docs/#/%E5%AF%BC%E5%87%BA%E5%88%B0%E7%94%9F%E4%BA%A7%E5%8A%9B%E5%B7%A5%E5%85%B7)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)
> * [消息中心](http://ksria.com/simpread/docs/#/%E6%B6%88%E6%81%AF%E4%B8%AD%E6%96%87) · [帮助中心](http://ksria.com/simpread/docs/#/%E5%B8%AE%E5%8A%A9%E4%B8%AD%E5%BF%83)
> * [预加载](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%E9%A2%84%E5%8A%A0%E8%BD%BD%E6%9C%BA%E5%88%B6) [延迟加载](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%E5%BB%B6%E8%BF%9F%E5%8A%A0%E8%BD%BD) [智能感知](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%E6%99%BA%E8%83%BD%E6%84%9F%E7%9F%A5) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/%E6%89%8B%E5%8A%A8%E6%A1%86%E9%80%89?id=%E4%BA%8C%E6%AC%A1%E7%A1%AE%E8%AE%A4)
> 
> #### 优化了
> * 导出到 Markdown 的若干问题
> * Onenote 授权失败过期的提示错误
> * 无法获取 知乎 Gif 的错误
> * TOC 的若干问题，如某些页面的卡顿，无法跳转等
> 
> 详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)

已经完美解决了可以从默认黑名单移除了吗，今天第一次在youtube用简悦稍后读半天没反应，差点提issue了，好险提前查到这。请问黑名单中的google和oschina还有什么潜在问题吗？还是说也已经修复可以从黑名单中移除。

**Comment by Kenshin** [comment]
@Losk-x 

在这类页面让不需要使用阅读模式的，所以官方给出了黑名单。

另外，

1. 因为一直没有移除它们（默认值），我不确定是否仍存在你提到的问题。
2. 这个 Issue 已经很老了…

**Comment by Losk-x** [comment]
> @Losk-x
> 
> 在这类页面让不需要使用阅读模式的，所以官方给出了黑名单。
> 
> 另外，
> 
> 1. 因为一直没有移除它们（默认值），我不确定是否仍存在你提到的问题。
> 2. 这个 Issue 已经很老了…

感谢回复👍。在chrome简单测试发现对页面无干扰，可以正常使用稍后读功能

**Comment by Kenshin** [comment]
@Losk-x

哈，没问题就好。
