### ISSUE TITLE
微信文章代码块换行不生效

### ISSUE THREAD

**Issue by zhjingyuan** [Kenshin/simpread#4870]
解析后的代码块
![image](https://user-images.githubusercontent.com/58380355/206370379-f7e46da3-8586-45ae-aa89-95058f2ce9fb.png)
解析前的代码块
![image](https://user-images.githubusercontent.com/58380355/206370476-843477d1-7393-49fc-b25b-03659d778adf.png)

**Comment by zc910704** [comment]
微信的代码块还有这个问题  https://mp.weixin.qq.com/s/ls6witGgoql79osW68BFlg

**Comment by Kenshin** [comment]
@zc910704 

okay wx的代码段规则有很多种 😂 这又是一个新的...

**Comment by Kenshin** [comment]
嗨，简悦 2.3.0.728 发布了，增强了微信公众号对代码高亮的适配逻辑，此问题已解决。

***

除此之外，还有以下重点更新

🔗 [永久链接](https://n.simp.red/posts/666) | [更新日志](https://simpread.pro/changelog.html#2.3.0.728) | [知乎专栏](https://zhuanlan.zhihu.com/p/2071612555815039958) | [Newsletter](https://newsletter.simpread.pro/p/simpread-230-728)

📚 728 版解决的问题

本版聚焦「更好看、更好用、更少打扰」，从用户视角你会感觉到：

- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

### 💡 新手建议 · 推荐插件

在对应场景可智能提示启用增强插件，包括：

- [知乎阅读辅助增强](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ)（访问知乎相关页面时）
- [微信公众号辅助增强](https://simpread.ksria.cn/plugins/details/N3EznnUXeV)（访问微信公众号时）
- [阅读模式优化](https://simpread.ksria.cn/plugins/details/xZVbwW4C5A)（小红书等）
- [Discourse 辅助增强](https://simpread.ksria.cn/plugins/details/hXZJKhhrMI)（访问 Discourse 页面时）
- [Lightbox Gallery 2](https://simpread.ksria.cn/plugins/details/TmZSYtz5lA)（多图页）
- [代码段增强](https://simpread.ksria.cn/plugins/details/klGUASLasg)（正文含代码块时）

### 🔌 新添加插件

- [导出 HTML (不含 CSS) 用于 SuperMemo 的导入](https://simpread.ksria.cn/plugins/details/6FIqWZpXRD)
- [阅读模式优化](https://simpread.ksria.cn/plugins/details/xZVbwW4C5A)（文本两端对齐转移到此插件）
- [修复标题因为特字符导致无法下载的问题](https://simpread.ksria.cn/plugins/details/tMGXrU1v0U)
- [代码段增强](https://simpread.ksria.cn/plugins/details/klGUASLasg)
- [标注以 MD 2.0 模板形式导出](https://simpread.ksria.cn/plugins/details/8jnsO2OtHW)
- [导出 org-mode](https://simpread.ksria.cn/plugins/details/etyod6A5ZT)
- [Discourse 辅助增强](https://simpread.ksria.cn/plugins/details/hXZJKhhrMI) 
- [无图版](https://simpread.ksria.cn/plugins/details/0vnL8VbCgs)

### 📗 优化插件

- [阅读模式优化](https://simpread.ksria.cn/plugins/details/xZVbwW4C5A) 可一键开启「两端对齐」，段落观感更整齐
- [Markdown 模板辅助增强](https://simpread.ksria.cn/plugins/details/HD9GmoatXd)：简单模板导出不再依赖本地 Obsidian 辅助
- [导出简悦知识库](https://simpread.ksria.cn/plugins/details/zOzpvOzM4a)：等标签多选体验与系统其它输入框对齐，更顺手
- [自动化辅助增强](https://simpread.ksria.cn/plugins/details/DH9l5jblPH)：重构了自动化辅助增强插件，现在对自动化监控的更快更精准
- [代码段增强](https://simpread.ksria.cn/plugins/details/klGUASLasg)：高亮更少挤成一行或整段失效；可自定义代码字号
- [微信公众号辅助增强](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 可顺带开启代码高亮
- [图床](https://simpread.ksria.cn/plugins/details/VdMfVaXlni)[PDF 辅助增强](https://simpread.ksria.cn/plugins/details/Lly3mkuSPz)：修复防盗链图片无法使用的问题
- [全文翻译](https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H) 等个别插件在 MV3 下的启动错误

### 🔗 关联

https://github.com/Kenshin/simpread/issues/7329
