### ISSUE TITLE
在我的动作里面找不到noiton增强

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4872]
在我的动作里面找不到noiton增强, 但是别的插件有, 这是咋回事呢
![image](https://user-images.githubusercontent.com/13315821/206379156-53ff6c6e-12f1-42c0-b29d-828f774daef5.png)
![image](https://user-images.githubusercontent.com/13315821/206379228-98736f91-05a6-4d75-b530-61a4f937beef.png)

_Originally posted by @efaun in https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-4340392_

**Comment by Kenshin** [comment]
@efaun

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

解决方案请看 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by efaun** [comment]
解决了, 谢谢👍

**Comment by Kenshin** [comment]
解决就好～

**Comment by Kenshin** [comment]
要是方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by efaun** [comment]
已五星好评 😏

**Comment by Kenshin** [comment]
谢谢支持 👏👍
