### ISSUE TITLE
Logseq 标注面板的问题

### ISSUE THREAD

**Issue by lyserenity** [Kenshin/simpread#4876]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/32646062/206625806-75a0f380-4cb7-4152-9b56-ec3a579b4daa.png">

当标注面板的备注如图所示（第一行留白（空格或是换行符），笔记从第二行开始），按下保存后，在浏览器操作在跟 logseq 的效果不同：

- **浏览器：正常效果**
  <img width="1031" alt="image" src="https://user-images.githubusercontent.com/32646062/206626966-fc06ecad-02fc-4241-897e-b30b4d8a2424.png">
（截图时文章有点问题，所以用另一篇替代）
- **Logseq：第一行的空白行不见了**
  <img width="503" alt="image" src="https://user-images.githubusercontent.com/32646062/206626373-49030c6c-e4df-4418-9032-2dc90c1d954e.png">

**Comment by Kenshin** [comment]
木有重现

> 第一图

是在 Logseq 添加备注的？

> 第二个图

**浏览器：正常效果** 是在正常的阅读模式下的预览？

> 第三个图

是在 Logseq 中的预览？

***

如果是上述步骤的话，我没有重新，步骤1在 Logseq 的备注加入空格后，理论上这个空格应该被自动删除。

**Comment by lyserenity** [comment]
试试看：在 logseq 里的标注面板的第一行留空白行，第二行才开始有文字 >> 保存，看看效果是什么？

在浏览器里不管是从原文进入阅读模式，或是从“稍后读”的标注面板操作都是正常的（我想达到的）效果，但是 logseq 是只要按保存之后，第一行的空白行会被吃掉....

**Comment by Kenshin** [comment]
> 在 logseq 里的标注面板的第一行留空白行

如下图

![image](https://user-images.githubusercontent.com/81074/207005987-5b9e26d2-2478-4827-917e-9a6e62da106e.png)

效果如下

<img width="261" alt="image" src="https://user-images.githubusercontent.com/81074/207006106-80b8586a-b0e2-4874-a945-c8372b5e5087.png">

> 但是，如果在普通的阅读模式下修改备注，则会出现下图所示

<img width="318" alt="image" src="https://user-images.githubusercontent.com/81074/207005968-1e4304d9-197c-4300-a2cf-e04a41aebd3a.png">

但在 Logseq 也没问题（跟上图一样，我就不截图了

😂

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

本地快照和标注系统增加了**自动暗色模式**功能，所以此问题自动修复了。

![2023-01-05_11-06-05](https://user-images.githubusercontent.com/81074/210696804-95b7cf81-ae71-4a69-a74a-b63cdefd3b1c.gif)
