### ISSUE TITLE
个别情况下，简悦在 Github 的blob模式下存在一些问题

### ISSUE THREAD

**Issue by retanoj** [Kenshin/simpread#488]
参考链接：
https://github.com/retanoj/xxx/blob/master/README.md

**Comment by Kenshin** [comment]
谢谢反馈，下个版本会解决这个问题。

**Comment by retanoj** [comment]
同时，测试得出在md转html过程中，对如下内容也会触发XSS。
`# simple`
`![img](h"onerror="alert(/first/);"")`
`![img](h>"onerror="alert(/second/);"")`
`[<img src=x onerror="alert(1);">imgimg](http://www.baidu.com)`
看起来像是puread库的问题

**Comment by Kenshin** [comment]
回头研究下。

**Comment by Kenshin** [comment]
我还是先把这个 issues 关闭了。（但，问题会解决掉  😄 解决后，通知你~

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

解决了此问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
