### ISSUE TITLE
插件管理器安装后，可能存在的相应配置无法同步的问题

### ISSUE THREAD

**Issue by freshchild** [Kenshin/simpread#4884]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 Windows 11

- 浏览器版本 Chrome 108.0.5359.99

- 简悦版本 2.2.0.520

- 同步助手版本 1.1.3

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

根据 [语雀](https://www.yuque.com/kenshin/simpread/fcw60u) 上的说明，关闭自动同步 - 重启浏览器 - 安装，中间保证只有一个选项页是打开的，然后在插件触发器里能看到插件管理器——到这里都是正常的，但一旦重新启动自动同步并再次打开阅读模式，插件触发器里的插件管理器将消失，不过插件列表里插件管理器仍然存在。此时查看同步后的 `simpread_config.json`，似乎在 "plugins" 里查不到插件管理器（UEzvAXNSe5）。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by freshchild** [comment]
补充：问题之前是可以复现的，不过现在似乎解决了。刚才在测试过程中无意尝试了**从配置文件导入插件**（自动同步处于开启状态）：

![image](https://user-images.githubusercontent.com/31954237/206860237-545434ae-24f2-4ae8-8013-420022223b6a.png)

之后就能在插件触发器内正常看到插件管理器了，同步的 `simpread_config.json` 也能查到插件管理器（UEzvAXNSe5）。总之我先把 issue 关掉，如果这个问题触发的原因完全是我操作有误的话麻烦踢我一脚，谢谢。

**Comment by Kenshin** [comment]
嗨，恭喜自救成功，简单的解释下。

> 但一旦重新启动自动同步并再次打开阅读模式

使用插件管理器后**不需要手动启用自动同步功能**，通过插件管理器**安装插件后会自动启用同步助手的自动同步**

> https://github.com/Kenshin/simpread/issues/4884#issuecomment-1345278162

通过这种方式导入当然是没问题的，但比如插件管理器的方式快捷。 😄

**Comment by Kenshin** [comment]
> 原来如此，是我想当然了

小事情，其实教程里面说了这点

<img width="503" alt="image" src="https://user-images.githubusercontent.com/81074/207030726-ae5bb8a0-5046-40df-9c38-a60ce8c30d2f.png">

> 假设因为某些原因需要停止同步的话，就只能通过关闭本地的同步助手上的同步功能

如果不需要使用自动同步的时候，就在选项页 → 共通 → （关闭）自动同步

<img width="899" alt="image" src="https://user-images.githubusercontent.com/81074/207030886-0271020d-f811-4902-a4ca-52756fb9f10f.png">

并没有 **卸载插件管理器** 这个事情。

你把这个过程（通过插件管理器安装插件）想复杂了。

**Comment by Kenshin** [comment]
> 我安装完插件管理器回到选项页，这时这个开关（选项页 → 共通 → （关闭）自动同步）是没有打开的

是的，你的结论没错。

然后…使用插件管理器安装插件后，会「帮你自动」打开自动同步功能。

也就是说，通过插件管理器安装后，重启浏览器后就会发现：选项页 → 共通 → 自动同步，是自动开启状态。

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
