### ISSUE TITLE
请问如何让导出的文件不带`@annote`字样？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4886]
请问如何让导出的文件不带`@annote`字样？在`Markdown 模板辅助增强 选项`中已经删掉了，但是导出的文件名还是会有。

_Originally posted by @StrollStars in https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-4371216_

**Comment by Kenshin** [comment]
@StrollStar

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

`@annote` 用于区分文章 or 标注的，所以我没太理解你的诉求…

如果使用 Obsidian 的话，可以使用 alias 方式

**Comment by StrollStars** [comment]
@Kenshin 感谢作者，如果同步导出全文和标注，标注的文件名会在原文的文件名后增加`@annote`字样，由于我只导出标注，所以想在导出的文件名中去掉`@annote`。

**Comment by Kenshin** [comment]
alias 是 Obsidian 用法，不过跟你的需求无关。
你的问题，我明天确认下。

你在导入到 Obsidian 时用了什么方式？

**Comment by StrollStars** [comment]
@Kenshin 用了[Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262)
简悦插件：导入到 Obsidian、Markdown 模板辅助增强
Obsidian插件：Local REST API

**Comment by StrollStars** [comment]
发现修改成其他名字也不行，估计不是受这个选项的影响。

**Comment by Kenshin** [comment]
> 那`Markdown 模板辅助增强`插件中的`请输入反向链接的标题`是影响的哪里？

一般指的是，双链笔记中的名称 e.g.  `[[xxx]]` 这个名字，但这个名字也跟`导入到 Obsidian`插件中`文件名设定` 有关系。

> 如果我想把`@annote`改成其他比如`的笔记`可以吗？

可以，但不建议这么做，因为简悦的很多功能依赖与 `@annote` 的标志。比如 [同步助手的增强导出](https://simpread.pro/docs/#/Sync?id=%e5%a2%9e%e5%bc%ba%e5%af%bc%e5%87%ba)

提示：标题的修改依赖与稍后读，如果不加稍后读的话，暂时无法修改标题，关联 https://github.com/Kenshin/simpread/issues/4883 后续会优化下。

**Comment by StrollStars** [comment]
@Kenshin 想再问下，是不是导出分两种，一个是在阅读模式导出，一个是在稍后读导出。
> @Kenshin 用了[Local REST API 导入方案](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2564262) 简悦插件：导入到 Obsidian、Markdown 模板辅助增强 Obsidian插件：Local REST API

这个是阅读模式的导出对吗？

**Comment by Kenshin** [comment]
> 这个是阅读模式的导出对吗？
> 一旦做了标注，就会自动加入稍后读是吧？

是的。
