### ISSUE TITLE
建议修改模板字体颜色

### ISSUE THREAD

**Issue by StrollStars** [Kenshin/simpread#4887]
[Obsdian 模板之一](https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311)导入后，由于字体本身是白色的，5种高亮颜色又偏淡，所以叠加在一起就让高亮英文文字不太明显。如下图：
![阅读](https://user-images.githubusercontent.com/10942225/206907673-fdcf0a61-c296-4461-8fcb-5fa6ef00b460.png)
其实我不太明白这是不是Obsidian的锅，因为它在编辑模式下是这样的：
![编辑](https://user-images.githubusercontent.com/10942225/206907697-54b559d5-ad3e-4792-a0ea-8718d2ad0cc2.png)

PS：本地7026端口提供的是什么服务？我点击高亮前面的链接显示“无法显示此页”。

**Comment by StrollStars** [comment]
Obsidian很奇怪，编辑模式和阅读模式看到的还不一样，真是所见非所得。

**Comment by Kenshin** [comment]
> Obsidian很奇怪，编辑模式和阅读模式看到的还不一样，真是所见非所得。

其实 Obsidian 小 Bug 也不少 😂

***

你把下面的代码修改下后再试试。

```
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
```

改成

```
let colors = ['#004daa', '#80761d', '#517579', '#517080', '#547534', '#805b6d' ],
```

**Comment by Kenshin** [comment]
PS：看到你提了好多个 Issues 说明 **真 · 认真用了**  😄

**Comment by Kalay1995** [comment]
obsidian用户遇到类似的问题, 但是我主要在obsidian中编辑离线html, 离线网页太亮了, 无论是在浏览器中查看还是obsidian中查看, 作者提供的方式应该是仅用来修改发送到obsidian时的颜色, 不能修改离线网页标注颜色, 能否开放接口允许自定义颜色，或者提供一个解决方案

我的let_colors存在且仅存在于 "HD9GmoatXd":{"annote_tmpl":"<%\nlet colors这个位置, HD9GmoatXd应该是为obsidian服务的插件。

win11 22H2 暗色模式, 简悦version 2.2.0, obsidian最新版v1.1.9
![image](https://user-images.githubusercontent.com/14127267/210916481-99578e8b-231c-4319-8a51-45ba4429aa90.png)

**Comment by Kenshin** [comment]
@Kalay1995

抱歉，漏掉了这个 Issues，这个问题已经解决了。

[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

本地快照和标注系统增加了**自动暗色模式**功能，所以此问题自动修复了。

![2023-01-05_11-06-05](https://user-images.githubusercontent.com/81074/210696804-95b7cf81-ae71-4a69-a74a-b63cdefd3b1c.gif)

除此之外，1.1.4 版还包括下面的一些功能：

## 下载地址

- [包含多种渠道下载](http://ksria.com/simpread/docs/#/Sync?id=下载)

## 更新日志

- [更新日志](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792)

## 新增 💄 

### 朗读

将正文转换为语音并播放，与 Edge 内置的大声朗读功能一样，均来自 Microsoft Azure 的语音服务。

<img width="3650" alt="TTS@plugin" src="https://user-images.githubusercontent.com/81074/206418879-c6ba7b85-e706-4741-b0b1-2e5123f2493d.png">    

- 插件端 [朗读](https://github.com/Kenshin/simpread/discussions/4833)

- 内置到 [稍后读极速版的本地快照](http://ksria.com/simpread/docs/#/TTS?id=内置到本地快照)

**Comment by Kalay1995** [comment]
> 

同步助手版本号在哪看, 自动暗色模式在哪里设置, 我是上周才开始用的简悦, 应该都是最新版本, 都是默认配置, 用的obsidian自动配置高级版

全都暗色模式, 在线网页颜色很合理, 离线网页太亮, let_colors修改之后markdown颜色也正常了。目前就是存在离线网页颜色太亮的问题

**Comment by Kalay1995** [comment]
> > 
> 
> 同步助手版本号在哪看, 自动暗色模式在哪里设置, 我是上周才开始用的简悦, 应该都是最新版本, 都是默认配置, 用的obsidian自动配置高级版
> 
> 全都暗色模式, 在线网页颜色很合理, 离线网页太亮, let_colors修改之后markdown颜色也正常了。目前就是存在离线网页颜色太亮的问题

找到了, 我是1.1.3 升级下试试

**Comment by Kalay1995** [comment]
> > > 
> > 
> > 
> > 同步助手版本号在哪看, 自动暗色模式在哪里设置, 我是上周才开始用的简悦, 应该都是最新版本, 都是默认配置, 用的obsidian自动配置高级版
> > 全都暗色模式, 在线网页颜色很合理, 离线网页太亮, let_colors修改之后markdown颜色也正常了。目前就是存在离线网页颜色太亮的问题
> 
> 找到了, 我是1.1.3 升级下试试

更新1.1.4之后, 这个问题解决了, 但是有了新问题, 目录体验不如之前流畅 #4996
