### ISSUE TITLE
同步导出原文和标注的问题

### ISSUE THREAD

**Issue by StrollStars** [Kenshin/simpread#4888]
配置
---
简悦插件：导入到 Obsidian、Markdown 模板辅助增强
Obsidian插件：Local REST API

实现
---
导入全文到 Obsidian：正常
导入标注到 Obsidian：正常

需求
---
1. 在不依赖同步助手的情况下，可否做到同步导出原文和标注，并且标注能够链接到原文上？
2. `自动化辅助增强`插件需要吗？这个插件是不是用来设置快捷键的，如果我没有键盘操作需要可以不装？

**Comment by Kenshin** [comment]
1. 上述功能已经不需要同步助手了。

2. 需要，除非你不需要自动化，全手动操作（非自动）的话，则不需要。

**自动化辅助增强** 正如它的字面意思，比如：当加入稍后读后，触发导入全文到 Obsidian；标注时触发导入标注到 Obsidian

如果不需要这些自动化方案的话，则不需要这个插件。

**Comment by StrollStars** [comment]
@Kenshin 我的问题还没解决，我现在想要手动同步导出全文和标注。
安装了**自动化辅助增强**插件（没设置快捷键），在扩展设置的标注中也选择了**全文（含标注） + 标注**，但是导出依旧只有标注。

**Comment by Kenshin** [comment]
> 安装了**自动化辅助增强**插件（没设置快捷键），在扩展设置的标注中也选择了**全文（含标注） + 标注**，但是导出依旧只有标注。

没理解... 你不是之前就成功了吗？下图就是你的描述...

<img width="420" alt="image" src="https://user-images.githubusercontent.com/81074/207216103-7a74532b-c25d-4141-89e9-88ec21baf4f8.png">

**Comment by StrollStars** [comment]
@Kenshin 对，两个单独到处都没问题，但是我想点一次同时导出原文和标注，并且标注链接原文，是不是要借助同步助手才能完成？

**Comment by Kenshin** [comment]
当前可以实现，明天给你方案。

**Comment by Kenshin** [comment]
加入稍后读后，自动导入全文，看下图。

<img width="611" alt="image" src="https://user-images.githubusercontent.com/81074/207501874-1848cab2-0a58-4189-83af-6af48a184ba5.png">

当标注时自动导入 Obsidian 的配置 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590606

**Comment by StrollStars** [comment]
@Kenshin 看了下这个选项已开启，https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590741 中说明：只有通过快捷键或右键加入才有效，通过标注加入稍后读无效，也就说要先手动加入稍后读，然后再标注才行，但是我如此操作了Obsidian中没有出现新的文章或标注。
PS：第一点右键写错了，写成了邮件。

扩展选项的**标注**中，**导出时可选**，这个选项是起什么作用的？

**Comment by Kenshin** [comment]
> 第一点右键写错了，写成了邮件。

谢谢 Fixed~

> 但一直未能成功到处原文带标注或标注带原文。

标注和稍后读需要使用不同的标题，否则会互相覆盖，你看看 [这里](https://www.yuque.com/kenshin/simpread/wkswh7#QqIGc) 跟你的设置有区别吗？

**Comment by StrollStars** [comment]
@Kenshin 我看了下[自定义标题](https://www.yuque.com/kenshin/simpread/wkswh7#phV3U)部分，对第一幅图和第三幅图进行了设置（另两幅图已设置），刷新了页面没有出现我要的效果：手动导出标注时同时导出原文并链接。
后面两部分是针对加入稍后读和标注进行自动导出，不是我的需求，所以没有设置。

**Comment by Kenshin** [comment]
> @Kenshin 我看了下[自定义标题](https://www.yuque.com/kenshin/simpread/wkswh7#phV3U)部分，对第一幅图和第三幅图进行了设置（另两幅图已设置），刷新了页面没有出现我要的效果：手动导出标注时同时导出原文并链接。 后面两部分是针对加入稍后读和标注进行自动导出，不是我的需求，所以没有设置。

有两个解决方案：

1. 把配置文件给我，我帮你看看
2. 使用 https://www.yuque.com/kenshin/simpread/xkuecp 里面的配置好的方案，你可以用另外一个浏览器测试安装这个配置库，然后对比这两个配置有什么区别。

感觉你的动手能力不错，我建议方案2，通过这个方式能 100% 了解这个功能的运行机制，方便定制。

**Comment by StrollStars** [comment]
@Kenshin 因为考虑到需要高级账户，所以直接在使用的浏览器上测试了极速版方案，但我好像忘记了之前的阅读记录导出，是不是寻不回来了？
我导入了极速版方案，发现做标注能自动同步到Obsidian，但是不会出现原文，原文还是需要手动导出。
目标任务改变，我先想办法把失去的标注补回来吧😂

**Comment by Kenshin** [comment]
> 我好像忘记了之前的阅读记录导出，是不是寻不回来了？

没有保存吗？或者导出到本地或者使用同步助手（在本地会有）否则的谁都没办法找回 😂

> 我导入配置文件前没有解除设备授权，导入后恢复了高级账户资格，没有解除授权有关系吗？

如果只是同一个电脑的话，不需要解绑，仍然会识别为一台设备。

> 发现做标注能自动同步到Obsidian，但是不会出现原文，原文还是需要手动导出。

原文的话应该以 Markdown 的形式导入到 Obsidian 里面才对。

导入标注时，是不是文件格式为 `123-xxxx@annote.md` 方式的？

**Comment by StrollStars** [comment]
> 原文的话应该以 Markdown 的形式导入到 Obsidian 里面才对。
**导入全文到 Obsidian**是这个效果。

> 导入标注时，是不是文件格式为 `123-xxxx@annote.md` 方式的？
**导入标注到 Obsidian**是这个效果。

**Comment by Kenshin** [comment]
我感觉还是需要把配置文件给我，你的问题又绕回去了 😂

**Comment by StrollStars** [comment]
@Kenshin 确实是绕回去了，现在悲剧的是，原来的配置文件我也没有了😂
PS：你的表情是怎么发的？我是通过查维基，比较麻烦。

重新配置了下已达成效果，ID标注在邮件主题中。

**Comment by Kenshin** [comment]
> 重新配置了下已达成效果

那还需要我吗 😂

输入法的话，手机用讯飞，电脑用小狼毫

**Comment by StrollStars** [comment]
> 那还需要我吗
我表述有误，我的意思是重新配置达到了重置配置前的效果，您方便的时候帮忙看下。😂

> 输入法的话，手机用讯飞，电脑用小狼毫
Google Play居然找不到讯飞了。
原来小狼毫的方框是有用的😂不过感觉它有点像停更了。

**Comment by Kenshin** [comment]
我收到了你的邮件，但邮件里面没有包含配置文件 😂

**Comment by StrollStars** [comment]
@Kenshin 麻烦你再看下

**Comment by Kenshin** [comment]
解决了，其实很简单，被你绕来绕去绕晕了 😂

安装 [自动化辅助增强](https://simpread.ksria.cn/plugins/details/DH9l5jblPH) 插件就行了。

<img width="543" alt="image" src="https://user-images.githubusercontent.com/81074/208286237-0f39834b-32e9-465f-828d-76c710842776.png">

然后 Obsidian 那边应该不需要改动什么。

**Comment by StrollStars** [comment]
@Kenshin 我看了下，没有达成效果，还是各归各导哎。

**Comment by Kenshin** [comment]
我帮你配置下吧，就以你发给我有的邮件的配置文件为基准，但得明天了。

**Comment by StrollStars** [comment]
@Kenshin 没关系，我不急，你方便的时候就行。
但我在意的是，导入极速版也不行，估计得依赖同步助手。

**Comment by Kenshin** [comment]
> @Kenshin 没关系，我不急，你方便的时候就行。 但我在意的是，导入极速版也不行，估计得依赖同步助手。

哈，你怎么由绕回去了... 我之前已经说了，不需要同步助手 😂

解决方案有两个：

1. 直接使用极速版配置包 https://www.yuque.com/kenshin/simpread/xkuecp （我看你也没有几个稍后读数据）

2. 等我给你配置好了。（但你的配置文件里面的内容不如配置包）

**Comment by StrollStars** [comment]
@Kenshin 谢谢你多次帮助我，耽搁你的宝贵时间了。
就如我上面所说
> 导入极速版也不行

也就是说极速版也达不到同步导出。算了，我就导标注吧，剩下的用其他途径实现。

**Comment by Kenshin** [comment]
我明天配置下极速版方案，因为还有个用户问类似的问题。
