### ISSUE TITLE
高亮插件没有背景框

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#489]
使用高亮插件的：
![image](https://user-images.githubusercontent.com/10437293/57425264-40663880-724d-11e9-83c8-468cc0ef54c5.png)
没有使用高亮插件的：
![image](https://user-images.githubusercontent.com/10437293/57425381-79061200-724d-11e9-9994-f7144ad1352a.png)

url地址：https://zhuanlan.zhihu.com/p/57243775

**Comment by AriaLyy** [comment]
还有一个问题，临时页面没有的代码没有高亮
![image](https://user-images.githubusercontent.com/10437293/57425424-b1a5eb80-724d-11e9-8357-652d86cdcb88.png)
这是临时页面的url：https://simpread.herokuapp.com/view/2019050994530579036.html

**Comment by Kenshin** [comment]
谢谢反馈。

简悦有 `深浅` 两类主题，所以我在高亮插件上把背景色去掉了，同时有些主题带有边框，有些不带有边框。

也就出现了截图所示的问题。 你可以通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决它。

***

临时页面没有高亮的原因是：没有加入高亮代码的 <link> 造成的。

同时，临时页面的样式也有些旧了，我会找个时机，更新下这个问题。

**Comment by AriaLyy** [comment]
👍
建议高亮插件能根据主题来设置边框的颜色，毕竟不是所有人都写得来css😂

**Comment by Kenshin** [comment]
已经在 `TO-DO` 里面了，下个版本会更新。

**Comment by Kenshin** [comment]
@AriaLyy 

临时页面的 `代码高亮`  功能已经加上了。

另外，代码段的背景色只能下个版本解决~

**Comment by AriaLyy** [comment]
临时页面的代码高亮貌似没生效。。
![image](https://user-images.githubusercontent.com/10437293/57991409-4e377b80-7ae1-11e9-8e3a-74acbd0060e6.png)

**Comment by Kenshin** [comment]
@AriaLyy 

应该是可以的，前提是：原页面已经安装 代码高亮 的插件才行。

这么做的目的是：
阅读模式的高亮 = 临时页面的高亮

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/57992210-8d67cb80-7ae5-11e9-84c7-c9a2fb9cd54f.png)
原页面已经安装并启用了高亮插件了

**Comment by Kenshin** [comment]
@AriaLyy

URL 和 生成的临时页面 URL  也给我看下~

**Comment by AriaLyy** [comment]
原url: https://blog.csdn.net/gyw520gyw/article/details/52692810
临时页面url：https://simpread.herokuapp.com/view/2019052069971683650.html

**Comment by Kenshin** [comment]
@AriaLyy 

可以了，之前是一个正则的判断未考虑周全造成的。
https://simpread.herokuapp.com/view/2019052089398309221.html

你需要重新生成临时页面。

**Comment by AriaLyy** [comment]
可以了，👍

**Comment by Kenshin** [comment]
嗨，代码段背景色的问题也已经解决，详细请看 https://github.com/Kenshin/simpread/issues/500

我将关闭此 issues
