### ISSUE TITLE
左岸读书站点编辑器异常

### ISSUE THREAD

**Issue by Buliet** [Kenshin/simpread#4893]
https://www.zreading.cn/archives/8872.html

通过站点编辑器设置：
![image](https://user-images.githubusercontent.com/32899664/206985891-d44b2032-e818-4b70-95aa-6e8d62c5a057.png)
结果显示：
![image](https://user-images.githubusercontent.com/32899664/206986022-0bcc4bce-febe-4f85-898d-eb9ce1958093.png)

设置的标题和描述 似乎没起作用，是我操作的问题么

**Comment by Kenshin** [comment]
嗨

按下图所示设置

<img width="458" alt="image" src="https://user-images.githubusercontent.com/81074/206990103-dc1df4e7-7adc-4286-b2c3-02765dc8cb9e.png">

设置完后重启浏览器，进入阅读模式后，如下图所示则说明设置成功

<img width="479" alt="image" src="https://user-images.githubusercontent.com/81074/206990229-dfc12985-b824-4b07-a38b-93d4e1d5c141.png">

**Comment by Buliet** [comment]
大佬 @Kenshin 两侧是箭头么，←→ 检测输入非法，也不是 <-->
从帮助文档中也没找到类似的表示，还请进一步说明下
<img width="253" alt="image" src="https://user-images.githubusercontent.com/32899664/207000559-96bc8d25-53cb-4918-96c7-6c504deee77c.png">

目的是 
"语不惊人死不休（313）为什么需要攒钱？因为「风水轮流转」。" **作为标题**
"2022-12-09 . 阅读: 2,827 views"  **作为描述**

**Comment by Kenshin** [comment]
进入阅读模式，然后下图所示打开

<img width="322" alt="image" src="https://user-images.githubusercontent.com/81074/207004992-72fda300-baf3-460d-a209-d0a1ece366ee.png">

那个「箭头」不是箭头 😂 而是 `<div class="xxxx">`

**Comment by Buliet** [comment]
😅 感谢大佬的耐心说明
就是【描述】还是不行，【标题】相比智能识别，去掉了末尾的【 – 左岸读书】
<img width="906" alt="image" src="https://user-images.githubusercontent.com/32899664/207013694-cb734497-7094-4ca9-98ac-4a2efa176515.png">
