### ISSUE TITLE
在使用【导出md+assets 格式】时，同步助手提示no such file

### ISSUE THREAD

**Issue by willwell929** [Kenshin/simpread#4895]
- 操作系统 **Windows**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**，同步助手1.1.3

- 发生问题的地址：https://www.bilibili.com/read/cv6958636?from=search&spm_id_from=333.337.0.0

1、在使用【导出md+assets 格式】时，同步助手提示以下截图一错误，无法导出图片。
2、在使用【导出md+assets 格式选项】时，选择BASE64方案后保存，刷新后发现插件设置重置为HTTP方案，无法保存。

截图一：
![image](https://user-images.githubusercontent.com/20971750/207030120-ec1206d4-92e1-4bfa-bd89-ab803aac8816.png)
截图二：
![image](https://user-images.githubusercontent.com/20971750/207030747-427bb6b9-e0f5-4b3a-8df5-3e860febc4b0.png)

**Comment by willwell929** [comment]
> 
![image](https://user-images.githubusercontent.com/20971750/207042777-9aa104b1-798d-4061-a3c7-d51a8de6c009.png)
使用base64方案后，就开始提示如上图所示的错误，请问如何解决呢？



> 嗨
> 
> 1. B站的话，只能使用 `Base64` 方案。
> 2. 如果插件设置无效的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 解决。

**Comment by Kenshin** [comment]
> 发现问题了，是文件路径名称中，包含有"_"符号

我明天看下。

**Comment by willwell929** [comment]
> > 发现问题了，是文件路径名称中，包含有"_"符号
> 
> 我明天看下。

我发现在【图片的导出位置方案】选择【4、Custom】时，是无法使用${filename}这个参数的，只能定义一个固定的相对路径，不能使用filename生成新的目录来存储。这是我的使用方法不对么？

**Comment by Kenshin** [comment]
> 我发现在【图片的导出位置方案】选择【4、Custom】时，是无法使用${filename}这个参数的

是的，自定义图片路径就是一个正常的绝对路径，无法使用相对路径。

<img width="865" alt="image" src="https://user-images.githubusercontent.com/81074/207217481-87075a45-b2d0-4866-bb0d-999381371610.png">
