### ISSUE TITLE
导出的稍后读文章的静态html在线打开会被简悦修改样式

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#4900]
本地html文件打开样式
![image](https://user-images.githubusercontent.com/3283023/207225176-2ca4110b-8be7-4ede-873c-40aa5758c832.png)

![image](https://user-images.githubusercontent.com/3283023/207225066-077ae37f-4a6b-499d-b849-c417790f9beb.png)

在简悦 阅读列表 打开在线的样式
![image](https://user-images.githubusercontent.com/3283023/207225162-da403207-58da-436c-ab55-5f2645eb7431.png)

在浏览器打开在线的外部资料库里的html
![image](https://user-images.githubusercontent.com/3283023/207225242-79ce55f8-3686-418d-a2d4-90fa28b5f20b.png)

禁用简悦插件后，样式就和本地html文件打开的样式一样了
![image](https://user-images.githubusercontent.com/3283023/207225367-3cb8d95b-c2b5-423e-96df-6004b1573f1d.png)

PS: 顺便问下导出的html可以自定义样式吗，在手机上看时，左右两边空白间距有一点多。

**Comment by Kenshin** [comment]
> 在简悦 阅读列表 打开在线的样式

不算是 Bug 或者说算是已知 Bug，因为都含有简悦的样式，所以会互相干扰 😂

> 顺便问下导出的html可以自定义样式吗

简悦专门为手机适配了导出方式，理论上应该是优化过的。

**Comment by iblogc** [comment]
![a5e86f3106f13c3a939610fa2aa46ed](https://user-images.githubusercontent.com/3283023/207234539-57f01dcc-548c-41d2-a64f-ac75c1109ee1.jpg)
忘了贴手机上的图了，左右空白有一点多，不知道是不是我个人感觉😂

**Comment by Kenshin** [comment]
> 忘了贴手机上的图了，左右空白有一点多，不知道是不是我个人感觉😂

应该是个人感觉 😂

至于自定义样式应该可以生效的，但在手机阅读上是不生效的，因为简悦专门适配了手机阅读界面。
