### ISSUE TITLE
导出到obsidian暗色下网页高亮过亮

### ISSUE THREAD

**Issue by h21565897** [Kenshin/simpread#4906]
- 操作系统 Windows 12

- 浏览器版本 **edge 108.0.1462.46 **

- 简悦版本 2.2

- 发生问题的地址 obsidian

导出到obsidian然后在obsidian内查看源网页时非常亮
![image](https://user-images.githubusercontent.com/62277434/207379113-7dcb237a-cace-43f7-a1ba-6fc36864f93a.png)
稍后读里面看没有这个问题

**Comment by Kenshin** [comment]
嗨，这是个 Bug，解决方案 https://github.com/Kenshin/simpread/discussions/3164

另外，下个同步助手会自动解决这个问题。

**Comment by h21565897** [comment]
我参考了 #3164 仍然没有解决，我在稍后读中没有遇到这个很亮的问题，本地网页暗色标注会非常亮，本地的网页保存的时候暂时没有对标注色进行处理吗

**Comment by Kenshin** [comment]
> 参考了 https://github.com/Kenshin/simpread/discussions/3164 仍然没有解决

这个方式应该可以解决。
很简单，就是把主题色改为暗色，然后手动导出一次本地 HTML。

另外，预计预计下周发布新的同步助手。

**Comment by h21565897** [comment]
emmmm，可能是奇怪的兼容性问题吧，我又删除同步文件夹下面的网页试了下，仍然很亮。还有就是向您提个小需求，在稍后读中看文章加标注后能否也触发加入到obsidian的逻辑

**Comment by Kenshin** [comment]
> 可能是奇怪的兼容性问题吧，

你把 URL 发上来我瞧瞧。

> 还有就是向您提个小需求，在稍后读中看文章加标注后能否也触发加入到obsidian的逻辑

这个需求会在下个版本实现，你可以在 [稍后读极速版](https://simpread.pro/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB%E6%9E%81%E9%80%9F%E7%89%88) 标注，这是一个简化的稍后读，但可以满足你的诉求。

**Comment by Kenshin** [comment]
嗨，[同步助手 1.1.4](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792) 发布了。

本地快照和标注系统增加了**自动暗色模式**功能，所以此问题自动修复了。

![2023-01-05_11-06-05](https://user-images.githubusercontent.com/81074/210696804-95b7cf81-ae71-4a69-a74a-b63cdefd3b1c.gif)

除此之外，1.1.4 版还包括下面的一些功能：

## 下载地址

- [包含多种渠道下载](http://ksria.com/simpread/docs/#/Sync?id=下载)

## 更新日志

- [更新日志](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-4340792)

## 新增 💄 

### 朗读

将正文转换为语音并播放，与 Edge 内置的大声朗读功能一样，均来自 Microsoft Azure 的语音服务。

<img width="3650" alt="TTS@plugin" src="https://user-images.githubusercontent.com/81074/206418879-c6ba7b85-e706-4741-b0b1-2e5123f2493d.png">    

- 插件端 [朗读](https://github.com/Kenshin/simpread/discussions/4833)

- 内置到 [稍后读极速版的本地快照](http://ksria.com/simpread/docs/#/TTS?id=内置到本地快照)
