### ISSUE TITLE
配置文件错误

### ISSUE THREAD

**Issue by h21565897** [Kenshin/simpread#4907]
- 操作系统 win12

- 浏览器版本 edge 108.0.1462.46 
- 简悦版本 2.2
- 发生问题的地址 obsidian

事情是这样的，用着用着突然标注功能开始报错，表现为无法启用标注，并且标注无法正确显示
![image](https://user-images.githubusercontent.com/62277434/207392893-d554daf1-c1b2-4b33-ba79-f69483384016.png)
个人猜测是同步助手的问题，在吧同步助手关闭后，标注可以用了，但是之前的标注也没了，重启同步助手，问题仍然存在，然后我直接删了本地的配置文件重启同步助手，问题暂时解决，就是之前的标注全不见了。此时在导出到obsidian的时候，全文导出正常，但是标注导出不正常，在导出报错一次之后，之前的标注报错开始重现。
![image](https://user-images.githubusercontent.com/62277434/207393260-b4a5bc6a-e52c-4a87-ac3a-5dfdce169eca.png)
分别是标注功能不正常的报错，和导出标注时候的报错

**Comment by Kenshin** [comment]
> 第一个图的问题

是因为数据结构错了，你可以使用历史记录还原 https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a

接下来的版本会增加数据结构完整性的验证

> 在吧同步助手关闭后，标注可以用了，但是之前的标注也没了

是的，关闭同步助手后因为使用了浏览器的「配置文件」但这个数据也是初始化的，所以自然没有问题。

> 此时在导出到obsidian的时候，全文导出正常，但是标注导出不正常，在导出报错一次之后，之前的标注报错开始重现。（第二个图）

这个错误是模板的错误，所以你可以把模板贴上来我瞧瞧。

不过，在重新测试时，确保已经使用历史记录还原了正确的数据。

**Comment by h21565897** [comment]
> 这个错误是模板的错误，所以你可以把模板贴上来我瞧瞧。
关于模板使用的是obsidian高级版整合包

> 不过，在重新测试时，确保已经使用历史记录还原了正确的数据。
没有云端同步，现在我如何可以fix这个问题，在干掉本地文件后从浏览器过来的同步的配置文件也会工作不正常，时间点就是在第一次点导出标注之后，貌似只有删掉整个配置覆盖重装吗

**Comment by Kenshin** [comment]
> 没有云端同步，现在我如何可以fix这个问题

很奇怪，如果你用了**obsidian高级版整合包** 那就应该使用了坚果云方案才对...（虽然不是必须项

导出配置文件到本地，然后使用 https://github.com/Kenshin/simpread/discussions/2727 提到的方式手动解决。

如果还是不行的话，发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4907

我帮你看看，发送邮件后回复我下~

**Comment by h21565897** [comment]
删除null之后fix了，感谢

**Comment by Kenshin** [comment]
小事情，解决就好~

接下来会内置自动化修复方案。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
