### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by Soywei00** [Kenshin/simpread#4909]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://utgd.net/article/8193>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/16738821/207541690-0f979f5b-5989-42c6-ac23-32ce82b59518.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，使用 https://github.com/Kenshin/simpread/discussions/1554 即可解决。

**Comment by Kenshin** [comment]
不过，这个站挺有意思，考虑适配它。

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/9aR6G3qt9y 安装。

同时因为这个站是动态加载的，所以需要将 `utgd.net` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

**Comment by Soywei00** [comment]
感谢适配

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Kenshin ***@***.***>
发送时间: 2023年3月30日 18:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Kenshin/simpread] 新站适配：utgd.net (Issue #4909)


嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/9aR6G3qt9y<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsimpread.ksria.cn%2Fsites%2Fdetails%2F9aR6G3qt9y&data=05%7C01%7C%7Ca4394de55e7340abd87c08db31087671%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638157684658697074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NyaCwHeu9yo6%2BzopEeAsjAzW2gT8I%2B1vGuFSbR%2Bz9J8%3D&reserved=0> 安装。

同时因为这个站是动态加载的，所以需要将 utgd.net 加入到延迟加载列表，如何使用 #5414<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenshin%2Fsimpread%2Fdiscussions%2F5414&data=05%7C01%7C%7Ca4394de55e7340abd87c08db31087671%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638157684658697074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WwdsHe5bwANSXz3KftswcPIzE6C6qUaoiWEQN52DVAQ%3D&reserved=0>

―

**Comment by Kenshin** [comment]
小事情，我也经常看这个站，但其实可以不用适配就能使用的。😄
