### ISSUE TITLE
自定义样式中代码段的字体大小设置无效

### ISSUE THREAD

**Issue by invisprints** [Kenshin/simpread#491]
在访问 csdn blog 或 stackoverflow 或简书中，发现在自定义样式中代码段设置的字体大小没有效果。
如在下面两个网址中
[CSDN](https://blog.csdn.net/masibuaa/article/details/16105073)
[stackoverflow](https://stackoverflow.com/questions/15339657/training-custom-svm-to-use-with-hogdescriptor-in-opencv)

按照[这个](https://github.com/Kenshin/simpread/issues/364)设置也没有解决
<img width="354" alt="code" src="https://user-images.githubusercontent.com/15833553/57447909-c654a480-728a-11e9-81e7-be462f43f372.png">

macOS Chrome 1.1.2版简悦

**Comment by Kenshin** [comment]
请问你使用了简悦自己的代码高亮插件了吗？

**Comment by invisprints** [comment]
插件开启和取消状态下字体大小设置都没有效果

**Comment by Kenshin** [comment]
方便的话， URL 给我看看

**Comment by Kenshin** [comment]
> 方便的话， URL 给我看看

嗨，上面这条信息发错了。我来解释下这个情况。

***

如果你使用了 [高亮插件](https://simpread.ksria.cn/plugins/details/klGUASLasg) 确实调整大小有些问题。

因为这个插件使用了第三方库 https://highlightjs.org/ 生成的代码高亮功能。

你可以通过 [自定义样式](http://ksria.com/simpread/docs/#/自定义样式) 来解决它，加入如下的代码

```
sr-rd-content pre,
sr-rd-content pre *  {
    font-size: <你认为需要的数字>px!important;
}
```

如图

![image](https://user-images.githubusercontent.com/81074/57497242-7668f280-7309-11e9-86f5-20ec62d3e8cd.png)

![image](https://user-images.githubusercontent.com/81074/57497293-a1ebdd00-7309-11e9-83a3-9922160d03e3.png)

**Comment by invisprints** [comment]
已解决，非常感谢！
简悦极大提升了网页的阅读体验，我已经推荐给周围的许多人！

**Comment by Kenshin** [comment]
搞定就好。
谢谢喜欢简悦，周末愉快。😀
