### ISSUE TITLE
如何去掉保存文件里的“本文由 简悦 SimpRead 转码”这段话

### ISSUE THREAD

**Issue by popecat** [Kenshin/simpread#4911]
保存离线的文件，段首都有“本文由 简悦 SimpRead 转码， 原文地址 www.toutiao.com”这段话，总觉得怪怪的，可不可以删掉“本文由 简悦 SimpRead 转码“这段

**Comment by Kenshin** [comment]
关联 https://github.com/Kenshin/simpread/issues/4911 😄
