### ISSUE TITLE
需求：导出为本地PDF、Markdown等文件时，支持文件名格式化

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#4914]
目前output文件夹下的存放的的pdf、md、html文件很多，缺少有序的文件名，导致查找、浏览、管理很不方便，尤其是对一些自动化工具不友好，所以期待文件名称生成规则支持一定的格式化，至少让带个日期或这个ID吧～～

**Comment by Kenshin** [comment]
哈哈，必须可以解决，[看这里](https://simpread.pro/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)
