### ISSUE TITLE
新站适配：百家号

### ISSUE THREAD

**Issue by ftyh2005** [Kenshin/simpread#4918]
发生问题的地址: <https://baijiahao.baidu.com/s?id=1752335469304901238

**Comment by Kenshin** [comment]
嗨，简悦是适配过百家号的，但它应该改变结构了，我先记录下。

**Comment by Kenshin** [comment]
嗨，这个站点已更新，请通过 https://github.com/Kenshin/simpread/discussions/2870 更新，并留意下图的说明

![SCR-20230330-pa8](https://user-images.githubusercontent.com/81074/228804557-dd38e20a-662c-4b91-b299-444ae67eca5f.png)
