### ISSUE TITLE
高级账户疑问

### ISSUE THREAD

**Issue by libiingzhi** [Kenshin/simpread#4922]
刚刚购买的高级账户。绑定后再进入就弹出一个粉色对话框：您还不是高级账户，请先购买高级账户。无论什么操作都是这个粉色的“您还不是高级账户……”

**Comment by Kenshin** [comment]
首次绑定提示你重启浏览器，但你没重启
解决方案 https://www.yuque.com/kenshin/simpread/ga970q

**Comment by libiingzhi** [comment]
问题依旧。[

**Comment by Kenshin** [comment]
确保 https://www.yuque.com/kenshin/simpread/tmmwhl

先使用 https://www.yuque.com/kenshin/simpread/hdcwoq
再使用 https://www.yuque.com/kenshin/simpread/sw4m21

如果还不行的话 https://www.yuque.com/kenshin/simpread/bvcunx

还是不行的话，就是其他问题造成的了。

**Comment by libiingzhi** [comment]
以上均无效。

**Comment by Kenshin** [comment]
不可能...除非你并不是高级账户...

这样吧，把你的 UID 与 License 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：4922

然后在这里告诉我，我给你看看。

**Comment by libiingzhi** [comment]
邮件已发送。辛苦了。

**Comment by Kenshin** [comment]
没有看到邮件 😂

**Comment by libiingzhi** [comment]
又发了一次。

**Comment by Kenshin** [comment]
我看了你的账户没有任何问题。

如果你没有任何稍后读数据的话，试试下面的方式：

1. 删除简悦
2. 重启浏览器
3. 安装简悦（不要打开任何网页）
4. 安装完之后使用 https://www.yuque.com/kenshin/simpread/pkq3d1 并输入你的 UID 

   <img width="276" alt="image" src="https://user-images.githubusercontent.com/81074/208287381-005d3307-60fc-425b-b14d-7ae52ad78bfd.png">

5. 正常的话，会自动授权为高级账户。

6. 重启浏览器。

**Comment by libiingzhi** [comment]
成功！
非常感谢！

**Comment by Kenshin** [comment]
本来这个步骤 https://github.com/Kenshin/simpread/issues/4922#issuecomment-1356259901 就应该没啥问题的 😂 

不过我所谓的了，解决就好~
