### ISSUE TITLE
“稍后读”界面内阅读原文无法正常显示LaTeX公式的问题

### ISSUE THREAD

**Issue by Sagi-Rastar** [Kenshin/simpread#4928]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows11 21H2**

- 浏览器版本 **Microsoft Edge 108.0.1462.54 (正式版本) (64 位)**

- 简悦版本 **2.2.0.520 （未启用预加载机制）**

- 发生问题的地址 <https://www.zhihu.com/question/26448935/answer/1189713815>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀  

您好，最近在尝试使用“简悦稍后读”导入知乎的含有LaTeX公式的网页时（图1），在稍后读界面内使用“阅读原文”功能似乎无法正常显示LaTeX公式。  

尝试了一下csdn之类的一些别的含LaTeX公式的文章站点，在“简悦稍后读”中没有出现类似于下述图2一样的问题。

另外顺便一提，在导出含LaTeX公式知乎文章的markdown格式时，在所有LaTeX公式后面似乎都会跟一串公式的源码（图3），请问这样正常吗？

**截图**
![image](https://user-images.githubusercontent.com/109590409/208287132-96e50e87-7fff-49a6-b136-969f4010ee48.png)
> 图一，原知乎文章

![image](https://user-images.githubusercontent.com/109590409/208286999-e171f7ab-9290-47eb-8e86-41a6a1c4a488.png)
> 图二，原知乎文章导入至“稍后读”中之后使用阅读全文模式

![image](https://user-images.githubusercontent.com/109590409/208287182-e9203425-70fd-4efc-96d9-f73660d1460c.png)
> 图三，原知乎文章导出md格式之后，在vscode内查看的情况

**Comment by Kenshin** [comment]
嗨

这种情况下，需要使用 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2) 方案，链接内含教程。

知乎的公式显示可以看 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890 的解决方案。
