### ISSUE TITLE
简悦默认情况下会引起youtube视频无法播放

### ISSUE THREAD

**Issue by davoola** [Kenshin/simpread#493]
安装完简悦后，默认情况下，打开youtube首页后，点击视频无法跳转至视频网址，点击播放按妞会提示“出了点问题，请稍后重试。（播放ID：xxxxxxxx)”，禁用，即可正常播放。或者在简悦设置里，
把默认的“在所有网站上”改成“点击时”即可

**Comment by Kenshin** [comment]
关联问题，请访问 https://github.com/Kenshin/simpread/issues/487 即可解决。

谢谢反馈。

**Comment by heloook** [comment]
解决了我的问题。感谢
