### ISSUE TITLE
Obsidian Sync配置方案自定义标题错误

### ISSUE THREAD

**Issue by jkunlin** [Kenshin/simpread#4930]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **win11**

**请描述你的问题**

使用Obsidian Sync配置方案，关闭“是否加载标注模式”后，用DD快捷键加入稍后读，提示自定义标题错误

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

导入配置方案，选项页--高级设定--标注--是否加载标注模式（选择否）
打开网页，点击插件进入阅读模式，快捷键DD，提示“自定义标题错误”

**Comment by Kenshin** [comment]
> 选项页--高级设定--标注--是否加载标注模式（选择否）

当然了 😂 这个功能需要开启这个选项才行。

关闭它你是有什么「特别」的用法吗？

**Comment by jkunlin** [comment]
有些网页只是临时看看，希望鼠标是选择模式，同时并不希望保存，但是目前的配置是：打开阅读模式后，用鼠标选择文字会自动标注，然后保存文件到本地。

**Comment by Kenshin** [comment]
> 有些网页只是临时看看，希望鼠标是选择模式，同时并不希望保存

鼠标选择模式是指？

另外，你可以在进入阅读模式选择暂时关闭它。（支持快捷键 `m m`）

<img width="199" alt="image" src="https://user-images.githubusercontent.com/81074/208346837-c04d0db0-80bc-45a7-9e3a-3ca856064510.png">

**Comment by Kenshin** [comment]
或者关闭下面的选项

<img width="882" alt="image" src="https://user-images.githubusercontent.com/81074/208346942-58ab3fe1-0f6f-402d-912d-95eab017d66b.png">

**Comment by jkunlin** [comment]
有没有可能默认就是关闭的状态，我这边大部分场景只是简单看看，需要标注和保存的场景相比之下并不多

**Comment by jkunlin** [comment]
> 

鼠标出于选择模式，是指正常浏览网页时，鼠标的状态：可以选择、复制、右键等

**Comment by Kenshin** [comment]
> 有没有可能默认就是关闭的状态，我这边大部分场景只是简单看看，需要标注和保存的场景相比之下并不多

刚才告诉你的两个方案都可以。

建议 https://github.com/Kenshin/simpread/issues/4930#issuecomment-1357074928 然后有需要的时候用快捷键打开它。

**Comment by jkunlin** [comment]
> > 有没有可能默认就是关闭的状态，我这边大部分场景只是简单看看，需要标注和保存的场景相比之下并不多
> 
> 刚才告诉你的两个方案都可以。
> 
> 建议 [#4930 (comment)](https://github.com/Kenshin/simpread/issues/4930#issuecomment-1357074928) 然后有需要的时候用快捷键打开它。

“关闭连续标注”不能解决问题，这种情况下，沙拉查词仍然无法使用。
使用快捷键MM的方式可以，但是有没有可能默认就是关闭，每次多一步操作挺繁琐的。

**Comment by jkunlin** [comment]
> > 使用快捷键MM的方式可以
> 
> [#4930 (comment)](https://github.com/Kenshin/simpread/issues/4930#issuecomment-1357074928) 这个功能是可以关闭的，也就是默认是关闭状态。

我这边导入配置文件后，默认是开启的。
如果关闭的话，“选项页--高级设定--标注--是否加载标注模式（选择否）”，那么用快捷键DD导出到稍后读，会提示“自定义标题错误”
