### ISSUE TITLE
阅读模式可以正常打开，稍后读中提示正文解析错误

### ISSUE THREAD

**Issue by haylinlin** [Kenshin/simpread#4936]
**请说明发生问题的环境**

- 操作系统 **Windows 10 21H2**

- 浏览器版本 **Chrome 108.0.5359.125（正式版本） （64 位）**

- 简悦版本 **2.2.0.520**

- 发生问题的地址 https://view.inews.qq.com/a/20220422A0905H00

**请描述你的问题**
地址可以正常进入阅读模式，但是在“稍后读”中打开失败，提示【无法解析正文】（应该与浏览器无关，Edge中相同操作也是一样的结果）
![image](https://user-images.githubusercontent.com/106876389/208479160-1ccf6398-0f46-49cb-b805-441bf0738153.png)

**Comment by Kenshin** [comment]
嗨，稍后读的阅读模式个别页面确实存在这样的问题，所以最好的方案是使用 [知识库](https://www.yuque.com/kenshin/simpread/lglfy2) 的方式，这样稍后读的阅读模式读的就是你在本地的快照了。

链接中内含教程。
