### ISSUE TITLE
词法分析引擎建议：标题与索引

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Kenshin/simpread#494]
1.标题可以参考safari的阅读器，不只是提取`title`，在之前还会先抓取网页上是否有其他的标题的元素，比如`h1`，有的网站还是`h1 class='title'`、`div class='title'`甚至是在meta中抓取标题元素。

主要是大部分网站上的标题元素总是带有一些过多的东西，比如xx网，虽然没什么大影响，但特别影响页面的整齐和美观。

2.很多网站都可以使用`[[{$('meta[name=Description]').attr('content')}]]`作为索引，简洁概括整个网站的内容。

索引从阅读上看其实也不是很重要的，但是可以增强使用的体验。

**Comment by Kenshin** [comment]
谢谢建议。

---

你说的这些简悦已经实现了，但只限于 [精准适配](http://ksria.com/simpread/docs/#/适配站点)

当使用 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎) 适配时，只提取了 `<title>`
和 `正文` 而已。

下个版本，会加强 `title` 和 `description` 的提取。

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

你提到的建议已经包含在最新版里面，谢谢建议~ 我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
