### ISSUE TITLE
从Chrome插件点击稍后读，不是进入未读列表，而是进入偏好设置的稍后读选项

### ISSUE THREAD

**Issue by a471640241** [Kenshin/simpread#4942]
**请说明发生问题的环境**
不管从Chrome右键菜单还是右上角的按钮点击稍后读，都会进入偏好设置的稍后读选项，昨天我刚用的时候还是进入稍后读的界面

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- win和mac都是存在这个问题

- Chrome 最新版 108.0.5359.124（正式版本） (arm64)

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
嗨，我没理解你的问题

> 都会进入偏好设置的稍后读选项

最好截图给我看看...

**Comment by a471640241** [comment]
![image](https://user-images.githubusercontent.com/11511810/209076389-be116724-0f68-4a38-8c1c-85c039a10687.png)
点击[打开稍后读]进入的是这个界面，而不是之前有一个阅读列表的那个界面，我现在已经进不去了

**Comment by a471640241** [comment]
找到了，以前点击打开稍后读，会进入下面这个地址
chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html
![image](https://user-images.githubusercontent.com/11511810/209076644-03c80287-2c88-4925-ac3e-9ccfc41f92e7.png)

**Comment by Kenshin** [comment]
嗨，看这里的解决方案

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/81074/209102617-25940323-01b0-460e-92b6-7152d6473932.png">
