### ISSUE TITLE
同一设备多次登录，无法恢复高级账户

### ISSUE THREAD

**Issue by JJcdomat** [Kenshin/simpread#4943]
已登录设备 | 暂无任何授权设备
-- | --
解绑设备 | 是否解绑全部设备？
当前状态 |  
剩余解锁次数 | 0 次
锁定时间 | 2022/12/15 11:09:16
解除锁定时间 | 16小时后

先使用obsidian配置同步助手同步，后在测试网盘同步的过程中无法恢复高级账户。提升：**您使用此账户登录了过多的浏览器，请联系管理员或登出已登录的设备。** 但目前仅在同一台电脑的同一个浏览器上恢复过高级账户。现在也无法退出已登录的账号，也无法正常恢复。

**Comment by Kenshin** [comment]
> 先使用obsidian配置同步助手同步，后在测试网盘同步的过程中无法恢复高级账户

emmm 你是不是没有更改导入后的配置文件的 UID？

**Comment by JJcdomat** [comment]
...成功了。我怎么记得第一次领取高级账户后，再用同步助手我好像没有这么操作........

**Comment by Kenshin** [comment]
导入配置库的文件需要修改 UID 。

配置库中的 UID 是 Demo ，否则就会出现这个问题。

**Comment by JJcdomat** [comment]
但是我在导入配置库文件后可以正常使用了。可能是中途某次操作把文件内uid删了？

**Comment by Kenshin** [comment]
切记：只要确保操作 https://www.yuque.com/kenshin/simpread/wq35mh#74e49885 这个步骤就行。
