### ISSUE TITLE
坚果云里多了名称为“md”的空文件夹

### ISSUE THREAD

**Issue by sw6633** [Kenshin/simpread#4946]
暂时无法复现，昨晚8点多出现的，在simpread文件夹下面，不是我新建的，当时没有用电脑，坚果云是前几天刚注册的。

删掉之后没有重新出现。

**Comment by Kenshin** [comment]
因为你使用了导入 md 到坚果云，所以会产生这个文件夹。

**Comment by sw6633** [comment]
> 因为你使用了导入 md 到坚果云，所以会产生这个文件夹。

但是我确定当时没有导入md到坚果云，而且那个时间点我没有用电脑或者手机。

**Comment by Kenshin** [comment]
还有一种情况，你可能使用了同步助手的增强导出。

在留意下吧，不是什么大问题 😂
