### ISSUE TITLE
关于导入到 Obsidian 的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4949]
嗨，K 大。有个使用中的问题想咨询一下你，翻了一遍 Obsidian 导入相关的 discussions 没看到我这种情况（希望我没漏掉什么）

背景：使用 Obsidian 前一直是通过简悦阅读模式进行标注，再导出标注为离线 html 文件保存到 Notion。现在转向了 Obsidian，然后根据「配置库」实现了自动导入 Obsidian，并且把之前稍后读的 json 配置文件也加上了。

问题：比如 idx 为 25 的这篇文章《写给更年轻的人》，进入阅读模式发现有自己之前的标注内容，但是导入到 Obsidian 之后，只有下图这两个 .md 文件：

<img width="693" alt="image" src="https://user-images.githubusercontent.com/35889526/209152349-6a37a046-80e6-47bf-b3f6-6411fee7ff1a.png">

当我在标注的 Markdown 文件里想点击高亮链接时，发现因为没有文章 html 源文件，导致加载失败。

错误信息是：

```json
{"code":404,"message":"没有找到对应的内容"}
```

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/35889526/209152724-e88c8a22-b37a-41ab-9ab1-a2e167b6bbbe.png">

想问问 K 大针对这种情况有没有什么办法能让之前的标注笔记原文也和「配置库」里的例子一样，实现标注 .md 文件高亮可以跳转到 output 文件夹里的 html 源文件。

_Originally posted by @Wonz5130 in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-4476083_

**Comment by Kenshin** [comment]
@Wonz5130

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

这个问题的因为 `idx` 为 25 的没有对应的本地快照。

在这个 `idx` 为 25 的原页面，重新生成一次本地快照。

<img width="472" alt="image" src="https://user-images.githubusercontent.com/81074/209273810-33991c67-e086-42cb-b3e0-f8b8c7d337db.png">

**Comment by Wonz5130** [comment]
> @Wonz5130
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 这个问题的因为 `idx` 为 25 的没有对应的本地快照。
> 
> 在这个 `idx` 为 25 的原页面，重新生成一次本地快照。
> 
> <img alt="image" width="472" src="https://user-images.githubusercontent.com/81074/209273810-33991c67-e086-42cb-b3e0-f8b8c7d337db.png">

非常感谢！刚试了下已经可以了～

**Comment by Kenshin** [comment]
okay 解决就好。

这两天 🐑 了，回复会比较慢

PS：我好像认识你的 ID，但又找不到你提过 Issues  😂

***

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Wonz5130** [comment]
> okay 解决就好。
> 
> 这两天 🐑 了，回复会比较慢
> 
> PS：我好像认识你的 ID，但又找不到你提过 Issues 😂
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

K 大多注意休息～

我年初就评分啦。年初加了您 Telegram 好友，也说 ID 比较眼熟来着（我全网统一 ID，活跃在即刻和少数派😄）

**Comment by Kenshin** [comment]
哈，谢谢老用户的评分。

PS：可能对你的头像很眼熟~

**Comment by Wonz5130** [comment]
有可能，头像也是几乎全网统一哈哈哈哈哈哈哈
