### ISSUE TITLE
tech.qq.com 文章提取不完整

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Kenshin/simpread#495]
http://tech.qq.com/a/20131208/003959.htm

阅读模式下正文提取不完整
聚焦模式没问题

**Comment by Kenshin** [comment]
我使用 `1.1.2.5005` 版本，并没有发生你说的问题。

请确保升级到最新版，以及更新 [适配列表](http://ksria.com/simpread/docs/#/%E7%AB%99%E7%82%B9%E9%80%82%E9%85%8D%E6%BA%90?id=%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5)

**Comment by mgdgfbhevdyeh** [comment]
确认有问题
关闭“词法分析引擎”后正常

**Comment by Kenshin** [comment]
比较奇怪。
升级适配列表了吗？

把有问题的地方导出 PNG 给我看看。

**Comment by mgdgfbhevdyeh** [comment]
最新的列表
![simpread-网络谜团：一只令全球密码专家着迷的 “蝉”](https://user-images.githubusercontent.com/20567492/57699076-a73e8400-7689-11e9-930e-0706cd4b7101.png)

**Comment by Kenshin** [comment]
问题已经重现...

不过，很奇怪的问题，我找找原因，解决后通知你。

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，

新增加了 [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) 解决了此问题。

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)

**Comment by mgdgfbhevdyeh** [comment]
Thanks!
