### ISSUE TITLE
导出到notion辅助增强失败

### ISSUE THREAD

**Issue by zys1346** [Kenshin/simpread#4951]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge 108.0.1462.54 (正式版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

导出到notion辅助增强失败，并且我非常确认我填写的id都没错，尝试了提到的办法都不可以

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

![image](https://user-images.githubusercontent.com/60969400/209419923-7a097de2-59df-4bc9-bfcd-80c02c5e5b57.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

这不是简悦的问题，具体原因以及解决方案请看这里 https://github.com/Kenshin/simpread/issues/4849

因为已经记录，为了避免重复，我关闭这个 Issues 了，但你仍可以回复。

Notion 有任何进展都会通知到这里。

PS：我这两天 🐑 了，等好了后会找一个更好的办法来彻底解决这个问题。
