### ISSUE TITLE
知乎导出markdown latex公式

### ISSUE THREAD

**Issue by AlieZVzz** [Kenshin/simpread#4952]
## 知乎导出latex公式重复
已经按照 #2861 的方案将zhuanlan.zhihu.com添加至延迟加载名单中，阅读模式中公式显示正常，但导出为markdown时latex公式重复，一个公式带$$，另一个不带

**Comment by AlieZVzz** [comment]
https://user-images.githubusercontent.com/47358078/209426365-77c071c4-9ec4-4828-9eb4-26ff52e16d78.mov

**Comment by Kenshin** [comment]
嗨，给我个 URL 瞧瞧。

**Comment by AlieZVzz** [comment]
https://zhuanlan.zhihu.com/p/37121528

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题

<img width="724" alt="image" src="https://user-images.githubusercontent.com/81074/209464617-0defef8b-5d07-47bd-8038-b3a4cbab9329.png">

这是我导出后的效果，测试环境很干净，没有多余的内容。

[马尔可夫链蒙特卡罗算法（MCMC）.txt](https://github.com/Kenshin/simpread/files/10299751/MCMC.txt)

另外，加入延迟加载列表后，刷新页面确保生效。

**Comment by eromoe** [comment]
https://zhuanlan.zhihu.com/p/60835095

我也有同样的问题，前端页面我已经滚动到底部，让知乎渲染完latex ，但是导出到obsidian 还是出现

![image](https://user-images.githubusercontent.com/3938751/215300419-ff01c32a-aa43-44a2-b23a-2ef5562e0038.png)

**Comment by Kenshin** [comment]
@eromoe 

[傅里叶变换中的不确定性原理（二）.txt](https://github.com/Kenshin/simpread/files/10529011/default.txt)

我这边是没问题的，这是我导出的效果，同样也是导入到 Obsidian

> 前端页面我已经滚动到底部，让知乎渲染完latex ，但是导出到obsidian 还是出现

不仅如此，还要加入到延迟加载列表

<img width="1708" alt="image" src="https://user-images.githubusercontent.com/81074/215305846-e1e66572-1e53-45da-87b0-37949ca1d182.png">

不过，知乎的部分公式确实有问题，但我测试了你提供的 URL 是没问题的 😂

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
