### ISSUE TITLE
豆瓣论坛解析问题

### ISSUE THREAD

**Issue by Arwenleo** [Kenshin/simpread#4953]
**请说明发生问题的环境**

- 操作系统 Windows10

- 浏览器版本 Edge108.0.1462.46

- 简悦版本 2.2.0

- 发生问题的地址 https://www.douban.com/group/topic/30274505/?_i=1890595QtcIcui,1890618QtcIcui

**请描述你的问题**
在解析该豆瓣链接指向的网页时：评论解析出错
原网页是一个论坛式的网页，楼主在评论中更文（类似百度贴吧或者随缘居）

**截图**
原网页：
![image](https://user-images.githubusercontent.com/71969794/209439411-6584dbda-3567-43fb-a2f8-819e5d1df416.png)

剪藏后：
![image](https://user-images.githubusercontent.com/71969794/209439394-c0663369-ffed-4877-b3f0-ca920df35a8a.png)
也可能出现这种效果：
![image](https://user-images.githubusercontent.com/71969794/209439450-3d3e0ad8-6eaf-4fd7-a431-bd639d11d9d3.png)

**Comment by Kenshin** [comment]
谢谢反馈，我明天瞧瞧。

**Comment by Kenshin** [comment]
嗨，我看到的就是论坛类页面

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/81074/209464399-cb7c24cb-deb3-4045-b223-4a2f69210497.png">

看看你的下图所示内容，要跟我的一直，不一致的话，点击对应的 icon 调整。

<img width="475" alt="image" src="https://user-images.githubusercontent.com/81074/209464431-06959c4b-d93b-492f-af76-bb90ffe0ea5e.png">

还是不行的话，根据下图所示更新适配规则

<img width="910" alt="image" src="https://user-images.githubusercontent.com/81074/209464460-222f4b13-1090-4dfc-9195-b16b8f4ee788.png">

**Comment by Arwenleo** [comment]
您好，谢谢您的回复！我已经完全按照您图中所示更新了适配站点，并启用了官方适配源。出问题的地方并不是您截图的论坛主楼，而是评论内容，就是在您看到的界面继续往下滑。

**Comment by Kenshin** [comment]
> 出问题的地方并不是您截图的论坛主楼，而是评论内容，就是在您看到的界面继续往下滑。

看到效果了.... 你看看其它类似页面有没有这个问题？
