### ISSUE TITLE
如何删除站点适配？

### ISSUE THREAD

**Issue by ollwow** [Kenshin/simpread#4956]
好多网站都自动加载阅读模式。
但是看白名单设置里，我又没有加任何一个网站。

如何才能一劳永逸，让所有网站都不要自动加载？
我想加载时自己去加载就好。

**Comment by ollwow** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/64347257/209466244-7ce2dd22-21ca-4e6d-90c6-3ce33c8cfbed.png">
找到了这个页面，但？难道要我一个一个删除？绝了。

**Comment by Kenshin** [comment]
因为你来了自动进入阅读模式，关闭他就行了…

**Comment by Kenshin** [comment]
另外，自动进入阅读模式默认就是关闭的，是你自己开启它的。

**Comment by ollwow** [comment]
> 好多网站都自动加载阅读模式。 但是看白名单设置里，我又没有加任何一个网站。
> 
> 如何才能一劳永逸？

我记得我之前不是这样写的？你为啥改我的帖子？

**Comment by Kenshin** [comment]
方便其他用户通过关键字搜索，只留下有用信息，
每个 issues 我都会这么处理。
