### ISSUE TITLE
关于 Supermemo 的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4957]
- 选 “导出 HTML（不含 CSS）用于 SuperMemo 的导入”，导入 Supermemo 后，图片挂了，但不会弹出脚本错误提示。
- 选 “导出不含 CSS 的离线 HTML”，导入 Supermemo 后，图片都挂了，而且会弹出脚本错误提示。
- 选 “导出离线 HTML”，导入 Supermemo 后，图片没挂，但样式混乱，而且会弹出脚本错误提示。

_Originally posted by @Stardusten in https://github.com/Kenshin/simpread/discussions/3377#discussioncomment-4495483_

**Comment by Kenshin** [comment]
@Stardusten 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

我不用 Supermemo，这几个跟 Supermemo 有关系的插件都是在 Supermemo 用户的帮助下建立的，他们说没问题，而且除了你也没有反馈过类似的问题。

最好问问使用过的这个插件的用户看看是什么情况。

**Comment by Stardusten** [comment]
解决了，是 supermemo 本身不支持 base64 编码的原因。

**Comment by Kenshin** [comment]
Cool

解决就好~
