### ISSUE TITLE
windows同步助手热键冲突

### ISSUE THREAD

**Issue by Rui0x** [Kenshin/simpread#4959]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 11**

- 浏览器版本 **e.g. Edge 109**

- 简悦版本 **2.2.0.520**

**请描述你的问题**

Windows下面同步助手 打开稍后读 的快捷键是 ctrl+shift+n, 和edge浏览器的打开新的隐私窗口冲突了。能不能改一下，或者允许自己设置？

**Comment by Kenshin** [comment]
一直都能改

<img width="683" alt="image" src="https://user-images.githubusercontent.com/81074/209525897-bc5883c1-954b-40ae-8911-c2e91bc4dbbd.png">

**Comment by Kenshin** [comment]
小事情~
