### ISSUE TITLE
导航目录无法点击跳转

### ISSUE THREAD

**Issue by fantasticfbaby** [Kenshin/simpread#496]
掘金阅读模式生成的导航目录无法点击跳转

**Comment by Kenshin** [comment]
谢谢反馈，确实存在这个问题。

**Comment by Kenshin** [comment]
谢谢反馈，确实存在这个问题。

**Comment by chiperman** [comment]
我这边也是，我以为是我设置问题，已经重新安装了

**Comment by Kenshin** [comment]
@chiperman 

你的也是掘金吗？如果不是的话，请告诉我具体 URL

**Comment by chiperman** [comment]
@Kenshin https://www.cnblogs.com/PyLearn/p/7777873.html#%E7%AC%AC%E4%B8%89%E7%A7%8D%E6%96%B9%E6%B3%95-4
实际上我在好几个网页都遇到了这个问题，只是目前我这几天使用这个网页比较多，印象比较深刻。

**Comment by Kenshin** [comment]
@chiperman 

应该是 Bug 造成的。
我看能否用 插件的方式解决它。

**Comment by Kenshin** [comment]
@fantasticfbaby @chiperman 

各位，此问题已修复，请安装对应插件 https://simpread.ksria.cn/plugins/details/UsayAKSuwe 即可解决。

我关闭此 issues 如有需要请重新开启~
