### ISSUE TITLE
自动化增强无法正常生效

### ISSUE THREAD

**Issue by ajiangstudy** [Kenshin/simpread#4961]
![image](https://user-images.githubusercontent.com/32857102/209752087-2eb1f558-3009-4a18-bb70-d5c1a47c339f.png)
您好我的自动化增强插件，在aa→dd之后，没有加入到Notion和flowus，能协助排查一下吗？或者如何能彻底删除这个自动化插件，从新部署

**Comment by Kenshin** [comment]
嗨

是 `n t` （留意空格... 😂

**Comment by Kenshin** [comment]
另外，在更正一点：

不是 `n t` 而是 `z n t` 教程里面 [有说明](https://simpread.pro/docs/#/Notion?id=%E5%BD%93%E5%8A%A0%E5%85%A5%E7%A8%8D%E5%90%8E%E8%AF%BB%E6%97%B6%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%85%A5)
