### ISSUE TITLE
请求：正文导入到ob增加一个设置来去除文中的所有外链

### ISSUE THREAD

**Issue by ProudBenzene** [Kenshin/simpread#4963]
有网站比如知乎和B站，会自动给一些词加上在他自己站内搜索的外链，很烦，希望在导入的时候可以自动取掉文章中所有的外链。

**Comment by Kenshin** [comment]
收到~

**Comment by Kenshin** [comment]
嗨，之前漏掉了这个 Issues 😂

[清理链接](https://github.com/Kenshin/simpread/discussions/2734) 升级到 1.0.2 版，增加了 [清理正文全部超链接](https://github.com/Kenshin/simpread/discussions/2734#discussioncomment-6371147) 功能。

![image](https://github.com/Kenshin/simpread/assets/81074/226246a5-38e8-4920-b222-49f0cf3dffe7)

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/1VIRZ7VGc3) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/2733

***

我关闭这个 Issues 有任何问题仍可以在这里跟我讨论~
