### ISSUE TITLE
你们的文档里无法查看图片

### ISSUE THREAD

**Issue by Pil0tXia** [Kenshin/simpread#4965]
问题链接：https://ksria.com/simpread/docs/#/双向链接

所有路过图床等第三方图片都失效了

建议自建图床

**Comment by Kenshin** [comment]
没有问题，我一会问问其他用户。

你可以试试 https://simpread.pro/docs

**Comment by Pil0tXia** [comment]
抱歉，是代理的问题，开直连就能正常显示了。

**Comment by Kenshin** [comment]
okay 没问题就好。
