### ISSUE TITLE
建议：阅读模式的浮动面板打开时默认为动作页

### ISSUE THREAD

**Issue by clytiee** [Kenshin/simpread#4966]
现在浮动面板打开时默认是第一页：“样式”，但是我很少去调整样式，高频使用的是“动作”页下面的导出功能。
找了半天没找到哪里可以修改这个设置的，因此提一个issue，如果没有该功能，希望可以增加。

另外，自定义导出方式里添加的导出，在插件“阅读模式浮动面板定制器“里是看不到的，因此无法添加到“动作”页的“常用”下。

**Comment by Kenshin** [comment]
有两种解决方案：

- https://github.com/Kenshin/simpread/discussions/1600 首选

- https://github.com/Kenshin/simpread/discussions/1601

**Comment by clytiee** [comment]
Assistive Touch解决了这个问题，安装过程有点曲折，删除了2个插件后这个插件才生效。

**Comment by Kenshin** [comment]
> 安装过程有点曲折，删除了2个插件后这个插件才生效（不确定是哪个插件导致的）

应该没关系，插件之间是互为沙箱的。

不生效具体是指什么？

**Comment by clytiee** [comment]
> > 安装过程有点曲折，删除了2个插件后这个插件才生效（不确定是哪个插件导致的）
> 
> 应该没关系，插件之间是互为沙箱的。
> 
> 不生效具体是指什么？

不生效就是在阅读模式下看不到那个浮动的层，在浮动面板的动作下的插件触发器里也看不到这个插件。

按照教程安装了插件管理器后也不行，所以就删掉了不用的那2个插件，不知道是不是删除插件这个操作触发了什么（而不是这2个插件本身和新插件冲突）。

**Comment by clytiee** [comment]
我刚把这2个插件又安装了一下，在动作的插件触发器下还是看不到，装完插件刷新下页面不够吗？

**Comment by Kenshin** [comment]
你是不是使用了同步助手的自动同步功能？

如果是的话，需要通过 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装插件。

**Comment by clytiee** [comment]
> 你是不是使用了同步助手的自动同步功能？
> 
> 如果是的话，需要通过 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装插件。

是的。哦，我还以为只要安装了插件管理器就行了，不知道需要通过它来安装。
明白了。

**Comment by clytiee** [comment]
我刚才又试了下，没有通过插件管理器安装的插件，在我删除一个插件后，也可以用了。
删除插件确实有用。

**Comment by Kenshin** [comment]
> 在我删除一个插件后，也可以用了。

理论上这个操作的「行为」跟使用插件管理器是一样的... 😂
