### ISSUE TITLE
代码框会显示两次代码

### ISSUE THREAD

**Issue by XingKong0927** [Kenshin/simpread#497]
发现c语言的代码会显示两次代码，如链接：https://blog.csdn.net/nka_kun/article/details/80487535 ，（截图如下），望解决此问题

![image](https://user-images.githubusercontent.com/39764884/57674985-46945480-7653-11e9-9b69-f0effb5501f8.png)

**Comment by Kenshin** [comment]
谢谢反馈~

`csdn` 的代码解析方案很恶心，因为我不清楚它到底有多少种解析方案...（仅仅是它，我适配了 4~5 类方案了，这又是新的一类方案！

你可以把 [代码解析的选项](http://ksria.com/simpread/docs/#/%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E5%BC%95%E6%93%8E?id=%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD) 关闭，虽然这样会让一些代码段看起来不太好看。

下个版本会解决这个问题。

**Comment by Kenshin** [comment]
嗨，周末好~

此问题已经解决了，详情请看 https://github.com/Kenshin/simpread/issues/500

我将关闭此 issue 如有问题请再重新开启。
