### ISSUE TITLE
用同步助手+Obsidian, 高级版自动配置库且配置成功, 目前遇到阅读模式颜色不生效及markdown只保存annote不保存源网页两个问题

### ISSUE THREAD

**Issue by Kalay1995** [Kenshin/simpread#4970]
1. 阅读模式颜色在chrome配置页设置了白色, 但是不生效, 仍然是黑色。 各种保存重启同步过
2. 只有在如下操作的时候原文markdown才会保存到obsidian:
    a. 打开obsidian, chrome中打开新网页, 在无任何标注前提下, 进入阅读模式(1中的情况, 永远是默认的黑色), 添加到稍后读。此后再标注就能正常同步
    b. 如果不打开obsidian, 不会同步到obsidian。此时使用obsidian中插件手动同步功能, 则只会将annote版同步过来, 并且之前保存的markdown网页全都被清除了。。。
    c. 如果网页先标注再稍后读, 则只会同步annote版markdown到obsidian, 没有源网页

**Comment by Kenshin** [comment]
> 阅读模式颜色在chrome配置页设置了白色, 但是不生效, 仍然是黑色

应该是你使用了系统暗色模式造成的，选项页 → 高级设定 → 暗色模式，关闭这个暗色模式。

> 如果不打开obsidian, 不会同步到obsidian

当然了，这个功能的使用前提就是需要开着 Obsidian

> 如果网页先标注再稍后读, 则只会同步annote版markdown到obsidian, 没有源网页

这个也是正常的，因为你使用了自动化辅助增强，它对形成稍后读的一些顺序有要求。

**Comment by Kalay1995** [comment]
![image](https://user-images.githubusercontent.com/14127267/210042566-42deb82d-efc5-47e3-a7eb-63164e19cd7f.png)
那我要怎样把这里的背景也设为黑色呢, 离线的html文字是黑色, 背景是白色, 很难受

**Comment by Kenshin** [comment]
把这个截图对应的 URL 给我看看

**Comment by Kalay1995** [comment]
https://zhuanlan.zhihu.com/p/409627700
我的系统是暗黑模式

**Comment by Kalay1995** [comment]
> 把这个截图对应的 URL 给我看看

在配置页设置了颜色为黑色之后就好了, 第一次配置没成功, 第二次成功了, 感谢开发者, 我的问题解决了

**Comment by Kenshin** [comment]
小事情，解决就好~

😄
