### ISSUE TITLE
代码高亮出错 && 建议

### ISSUE THREAD

**Issue by xmhwws** [Kenshin/simpread#4971]
https://www.wolai.com/tSuXUdV3Hg7mt7cayrqZpi

重新高亮选区才能有内容，代码块压缩成一团了，而且代码框也没了

简阅：
![image](https://user-images.githubusercontent.com/42903751/210037076-166c4346-aad0-48ae-b76e-6c313a28e0d2.png)

原始：
![image](https://user-images.githubusercontent.com/42903751/210037099-93e4962f-ce5e-4c81-9b7a-1203d3577094.png)

我发现一个神奇的插件：https://github.com/gildas-lormeau/SingleFile ，它免费开源，能将完整的网页保存到单个离线 HTML 文件中，阅读起来和原网站一模一样！
试了几个简阅阅读模式有问题的网址，SingleFile都能正常保存下来，建议作者大大参考一下SingleFile的代码，完善一下相关功能

**Comment by xmhwws** [comment]
对了，代码框消失这个问题，在知识星球的网址也经常出现，建议修复下

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
