### ISSUE TITLE
自动化任务”当加入稍后读即导出至 joplin“运行失败（前提： Joplin已成功授权）

### ISSUE THREAD

**Issue by nfway** [Kenshin/simpread#4973]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 ** Windows 11**

- 浏览器版本 **Edge 版本 108.0.1462.54 (正式版本) (64 位)**

- 简悦版本 **2.0.0**（高级版）

- 发生问题的地址 extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect
**请描述你的问题**

自动化任务未启动。具体描述：

1. 已成功授权 Joplin
2. 设定了当加入 稍后读 ，就
3. 导出到 joplin

上述已完成，但测试把某文章加入稍后读 之后，文章未导出到 Joplin 

说明：

> 设立自动化任务的目标就是 使用 simpread 作为排版工具，收藏文章后自动保存到 Joplin。如 simpread 除了自动化任务可以达到该目的，请告知

**截图**（没图）

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

这个功能应该是没问题的，所以试试手动导入到 Joplin 能否成功？

**Comment by nfway** [comment]
> 嗨
> 
> 这个功能应该是没问题的，所以试试手动导入到 Joplin 能否成功？

手动没有问题

难道是要在自动化任务里先导出到markdown ，然后再导出的 joplin 吗

**Comment by Kenshin** [comment]
> 手动没有问题

emmm 那就奇怪了。

> 难道是要在自动化任务里先导出到markdown ，然后再导出的 joplin 吗

不需要 😂 跟这个流程无关。

***

我刚测试了下，是没问题的。
另外，加入稍后读触发快捷键的前提：使用 `d d`

**Comment by nfway** [comment]
> 我刚测试了下，是没问题的。 另外，加入稍后读触发快捷键的前提：使用 `d d`

意思是使用 浏览器 环境下的快捷键把文章加入到 稍后读 ，是无法触发自动化任务吗？🤔

**Comment by Kenshin** [comment]
> 意思是使用 浏览器 环境下的快捷键把文章加入到 稍后读 ，是无法触发自动化任务吗？🤔

如果没有进入阅读模式的话，是无法实现自动化的。

实现自动化的前提：

1. 进入阅读模式
2. 使用快捷键 `d d` 或右键菜单加入稍后读

**Comment by nfway** [comment]
> > 意思是使用 浏览器 环境下的快捷键把文章加入到 稍后读 ，是无法触发自动化任务吗？🤔
> 
> 如果没有进入阅读模式的话，是无法实现自动化的。
> 
> 实现自动化的前提：
> 
> 1. 进入阅读模式
> 2. 使用快捷键 `d d` 或右键菜单加入稍后读

感谢回复。

1. 经过使用 `dd` 快捷键后，确实实现了”导入joplin“的状态
2. 但是自动导出好像出了问题，joplin 设置好了，但是没导出到 joplin

**Comment by Kenshin** [comment]
嗨，我测试了下是没问题的。 😂 （就不录视频了。
