### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by wikiq** [Kenshin/simpread#4974]
发生问题的地址: <https://twitter.com/rh_1235/status/1608737646020554755>

**Comment by Kenshin** [comment]
可以适配这个页面，看下图跟你的是否一致？

<img width="471" alt="image" src="https://user-images.githubusercontent.com/81074/210160556-e1d98adf-024e-460a-91aa-8181958aba6f.png">

如何适配的话，看下 https://github.com/Kenshin/simpread/discussions/2923 提到的方式。
