### ISSUE TITLE
个人中心问题—阅读列表/每日回顾网页重复刷新/收藏助手收藏后无法更新到稍后读中/灵感页面即使加了dr也无法同步

### ISSUE THREAD

**Issue by Willluckdog** [Kenshin/simpread#4975]
出现的问题页面：
1.阅读列表：https://simpread.pro/@eu8685u6-78l4-ovai-5vtm-gyqj4mtawxnj/login?redirect=reading/ 不断重复刷新
2. 收藏助手：
https://simpread.pro/@eu8685u6-78l4-ovai-5vtm-gyqj4mtawxnj/add/?token=587igetq9i-5gv6fh1kz152ekcn4v319pk0ebkgpvi82gzhbspoyce324qdl6 即使收藏成功，在稍后读页面中仍然无法显示。
3. 每日回顾：https://simpread.pro/@eu8685u6-78l4-ovai-5vtm-gyqj4mtawxnj/login?redirect=daily 重复刷新
4. 灵感：
https://simpread.pro/@eu8685u6-78l4-ovai-5vtm-gyqj4mtawxnj/reviews 即使稍后读中已有dr标签，仍然不显示。
![25D1FFE9-027D-4D96-B263-61E5EDF7F1C0](https://user-images.githubusercontent.com/121739732/210159514-5affa185-6113-4189-8108-c18aa9eb6550.png)
![Uploading 3C88063B-94A6-475F-88FB-093EC81FB7CF.png…]()

**Comment by Willluckdog** [comment]
![Uploading 04E10D85-0038-441B-A149-FC794744CD05.png…]()

**Comment by Kenshin** [comment]
不要使用 `eu8685u6-78l4-ovai-5vtm-gyqj4mtawxnj` 这种奇怪的 ID，你可以登录到开放平台自己设置 ID

> 重复刷新的问题

因为你反复登录，请在隐私模式下登录。

> 即使收藏成功，在稍后读页面中仍然无法显示。

这个功能依赖与同步助手 + 坚果云，你可以先看下坚果云 Web 端里面的 simpread_config.json 是否更新了，如果更新了则说明添加成功。

关于开放平台的功能，建议看下 https://www.yuque.com/kenshin/simpread/vcmg4o 的内容（里面包含了必要的两个配置教程）
