### ISSUE TITLE
我已有高级账户，同步助手无法共通验证！求助！

### ISSUE THREAD

**Issue by sleepyheadforu** [Kenshin/simpread#4976]
已经解锁🔓高级账户，功能也可正常使用，但是开启简悦 · 同步助手时无法共通验证！求助

![Uploading iShot_2023-01-01_1
<img width="808" alt="iShot_2023-01-01_11 39 09" src="https://user-images.githubusercontent.com/103108364/210160371-039de396-cd96-443e-8dbb-4a95d6fe69a4.png">
1.38.34.png…]()
<img width="808" alt="iShot_2023-01-01_11 39 09" src="https://user-images.githubusercontent.com/103108364/210160378-7fd73fe2-ea63-426e-afbc-128dff7ee6c4.png">

**Comment by sleepyheadforu** [comment]
<img width="356" alt="iShot_2023-01-01_11 38 34" src="https://user-images.githubusercontent.com/103108364/210160445-89630c2b-9b21-4655-a4cf-bed343b3b121.png">

遗漏一张图，已经解锁🔓高级账户，功能也可正常使用，但是开启简悦 · 同步助手时无法共通验证！求助求助求助

**Comment by Kenshin** [comment]
嗨，首次绑定需要重启浏览器，但你没有重启，使用 https://www.yuque.com/kenshin/simpread/ga970q 解决。

**Comment by Kenshin** [comment]
PS：你是 2023 年我回的第一个 Issues~
