### ISSUE TITLE
如何在移动端将文章自动保存到notion中？

### ISSUE THREAD

**Issue by Chare-Dream** [Kenshin/simpread#4978]
使用场景：在阅读时会碰到一些文章是当下自己用不上的，但是可能在未来能用上，所以想把他放到自己的notion库中，方便在未来进行查询。这类文章可能在收藏时不需要进行高亮和批注，所以不需要在桌面端进行打开，只需要在移动端发现文章后快速将其保存至notion中。不直接将文章分享到notion的原因是notion抓取的页面太差了，简悦保存到notion中的页面非常美观。
问题：目前我使用telegram bot保存文章到稍后读和本地html，但是将其保存到notion中时还需要在网页端进行手工操作，属于半自动化流程。不知道有没有一种全自动化的流程呢？

**Comment by Kenshin** [comment]
嗨，暂时没有 😂 

你的需求属于服务器端行为跟浏览器端还是有很大的差异。

如果使用 iOS 系统的话，我建议试试 Goodlink 它可以保存公众号的内容，应该也具有快照功能。可以作为简悦的一个「收件箱」来扩充。

如果使用 Android 系统的话，可以试试 Kiwi，简悦可以完美的在 Kiwi 浏览器中使用，自然也可以使用导入到 Notion 插件。
