### ISSUE TITLE
会增加百度搜索结果页面的加载速度。

### ISSUE THREAD

**Issue by bigyi2013** [Kenshin/simpread#498]
会明显增加百度搜索结果页面的加载速度。将baidu.com加入黑名单后，加载速度恢复正常。

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

只是... 我没有遇到你说的问题。

另外，请问是微博上反馈给我的朋友吗？

**Comment by bigyi2013** [comment]
可能是与其他插件冲突。（毕竟我安装了好多百度美化和去广告插件）。
另外，我不用微博，所以应该不是我。

**Comment by Kenshin** [comment]
@bigyi2013 

okay ~ 如果确定不是简悦引起的话，我还是关闭它了。

微博上的反馈我到时候再重开一个 issues  😀

**Comment by bydx** [comment]
同样的困扰……而且导致浏览器开关标签变卡，只能选择关闭简悦了。
btw,我在使用油猴的去重定向和css美化插件。

**Comment by Kenshin** [comment]
@bydx

你是说访问百度吗？还是任意网页？

目前你可以用黑名单解决这个问题。

另外，下个版本会解决这种问题。

PS：周末愉快～
