### ISSUE TITLE
md+asserts导出问题

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#4980]
# Precondition
- win10 home
- browser: brave: [版本 1.48.93 Chromium: 109.0.5414.46（正式版本） （64 位）](https://brave.com/latest/)
- SimpRead: v2.2.0.520
- plug-in: 导出md,asserts格式

# Question
a. 导出md+asserts格式的选项里面,有指定添加metadata到markdown
b. 在SimpRead的选项页里面,服务->订制导出,有一个是否开启自定义markdown模版的选项,里面也可以设置markdown的metadata

问题
- 经实验,导出的md的metadata是a里面设置的内容,b没有起总用
- b在什么时候起作用
- a和b是不是冗余了
- 我导出了md和asserts,但是没有标注,请问如何导出标注.

**Comment by Kenshin** [comment]
> 导出的md的metadata是a里面设置的内容,b没有起总用

是的，插件是插件的，扩展是扩展的。你可以理解插件的配置仅作用于插件，扩展的选项无法干预到插件。

> b在什么时候起作用

因为有了 [Markdown 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3725) 慢慢会取代扩展端的功能，扩展端的功能仅仅只是作为基础功能提供给用户。

> 我导出了md和asserts,但是没有标注,请问如何导出标注.

标注暂时不支持 md + assets 的导出方案，后续会考虑加入。

md + assets 仅仅只是用来将图片本地化的一种解决方案，本质上并没有太大的关于标注的诉求。

**Comment by wieniawski-lai** [comment]
# Result
我根据[这里](https://github.com/Kenshin/simpread-configs/blob/main/obsidian%40sync/Getting%20Started.md) 的描述,重新配置好了ob和simpread,然后我就可以成功的导出md(图片是在线链接),md+asserts,以及标注到ob的文件夹了.

# Precondition
在[例子的网页上面](https://sspai.com/post/71576), 插件触发器里面有a.导入全文到Obsidian和b.导入md+asserts到Obsidian两个选项.
- 我点击a的时候,发现md文件发送到了SimpRead这个文件夹
- 我点击b的时候,发现所有东西发送到了SimpRead/output/这个文件夹,不仅仅有html文件,还有以标题命名的一个子文件夹,里面存放了md以及asserts文件
- 标注是放在SimpRead这个文件夹下面

# Question
根据上面的precondition,我仍旧有以下一些问题

0.您说的扩展的定义是SimpRead这个浏览器的扩展?插件是SimpRead的插件?
1. 为什么a和b放在不同的地方?
2. 这两个导出,都是SimpRead的插件在起作用?
3. 但是指定<PRE_DIR>/SimpRead/output这文件夹是在同步助手里面指定的.这些路径我确实没有想明白是怎么设置,以及起作用的
4. 自动化辅助增强这个插件,里面指定了很多快捷键.其本质是通过这些快捷键去调用:导入全文到Obsidian,导入md+asserts到Obsidian,以及导入标注到Obsidian?那这些快捷键的意义哪里可以找到?
5. 您给的obsidian@simpread这个例子里面,simpread_config要求和output文件夹平级,这个是为什么?(可以结合下一个问题一起看)
6. SimpRead导入到ob的时候,文件存放的路径是ob的库的路径.很多时候,(比如我)ob的库是通过webdav同步的,这就意味着simpread_config.json文件天然的通过webdav同步了.在[这个issue里面](https://github.com/Kenshin/simpread/issues/4981)您提到,确实有人和我一样通过这种方式同步了json文件.那么这个时候如果我又通过同步助手来同步了不同PC间的json文件(which you advice to, 但我暂时还没有这么做).这二者会打架吗?
7. 您提到标注不支持md+asserts的导出方案,但是就目前而言,只要路径合适,md+asserts和标注是可以实现的.虽然我暂时还不知道怎么合理的设置路径.(毕竟网页的md和标注是两个md,二者不冲突).
8. 上面提到的导入md,标注等等到obsidian是SimpRead的插件的功能是吧?那obsidian里面的SimpRead这个插件又能起到什么作用?同步json文件?
9. 如果8属实,那么同步json文件就有三种方式了,a.ob的库天然的webdav,b.同步助手的客户端,c.Ob里面SimpRead这个插件.这三者不冲突不打架吗?

谢谢

**Comment by wieniawski-lai** [comment]
我又看了一遍[自动同步](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5)的文档

上面的6和9,我可能理解的不对.一下是我新的理解

1. json文件是最重要的需要同步的东西
2. simpread不提供同步服务
3. 同步助手的客户端负责把浏览器的配置和本地json文件同步.
4. 不同PC之间通过网盘,webdav等等方式同步json文件
5. simpread本身没有webdav的接口,本身也不支持webdav
6. 如果以上都对,那我现在唯一不理解的就是ob的插件对于json同步的意义了?这个有什么用?

**Comment by wieniawski-lai** [comment]
嗯,还有几个问题没想明白,与capture到本地没有任何关系

1. 所有的稍后读的网页数据都是在本地的?
2. 我找了C:\Users\<username>\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default,这里似乎没有找到.
3. 如果是重装系统了,或者是一个全新的电脑,若干年前的数据从哪里找到?(若干年前的网页可能已经不复存在了).
4. 因为按照之前的理解,json文件只保存了稍后读的标题,标注等等,原始网页(包括图片)这些数据并没有在json文件里面.

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368806205

> 问题1

md + assets 在没有设置目录的前提是，都会保存到 `output` 文件夹，标注只所以能保存到 `SimpRead` 文件夹是因为配合库里面设置了。

定制化路径可以 [看这里](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604)。

如果你需要将

> 问题2

是的

> 问题3

在同步助手中设置。（我没理解你为什么不明白 😂 它只是一个路径而已

> 问题4

每个插件都有说明，你可以 [在这里](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E) 找到全部插件说明

> 问题5

为了可以使用 API

> 问题6

理论不存在这个问题，因为无论 `simpread_config.json` 放在哪里，都需要在同步助手中设置路径。
哪怕它放在 ob 的某个文件夹中，你自己负责同步，但指向（路径）必须要在同步助手中设置。

> 问题7

应该不行吧

> 问题8

Obsidian SimpRead Sync 是 Obsidian 的插件，用来同步来自网页的标注，以及在 Obsidian 标注的功能，关于这个插件的说明可以 [看这里](https://github.com/Kenshin/simpread/discussions/2889)。

> 问题9

不是的。

同步助手没有同步功能，只是可以读写本地的  `simpread_config.json` ，同步功能是通过第三方网盘工具（如简悦官方推荐的坚果云）实现的。

***

> https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368828617

是的，你这次理解对了 👍

> 就是ob的插件对于json同步的意义了?这个有什么用?

看上面的我给你的链接。

***

> https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368844217

> 问题1 / 2

如果使用了同步助手的同步文件夹功能的话，自然会在你设置的路径下。
否则在 Chrome 的安全沙箱里面

> 问题3

你可以将这个稍后读变成本地快照，你使用的配置库里面就包含了这个功能，`output` 文件夹里面的内容就是这些快照。

> 问题4

本地快照在 `output` 文件夹里面。

关于本地快照系统，建议看看 https://www.yuque.com/kenshin/simpread/xr9wb8b4ap5rrzba 里面的描述。（你的理解能力不错，看完基本上就彻底弄明白了 😄

**Comment by Kenshin** [comment]
你太能问了 😂 

简悦 5K+ 的 Issues，你能排前五 👍

**Comment by wieniawski-lai** [comment]
> 你太能问了 😂
> 
> 简悦 5K+ 的 Issues，你能排前五 👍

荣幸之至

我刚刚试了一下不开同步助手的客户端,进入阅读模式,他就会提示我没有开客户端

结合[本地快照系统](https://www.yuque.com/kenshin/simpread/xr9wb8b4ap5rrzba)以及您上面的描述.output这个文件夹是在客户端里面设置的,也是本地快照要导出的位置.因此就必须要开启客户端,才能将capture下来的东西存到output文件夹,从而解决数据本地化的问题.

至于重装电脑之类的,数据还在output文件夹里面,再次打开同步助手客户端,就可以将本地的数据回到Chrome里面.

即数据的本地化,根本上是靠同步助手的客户端解决的.走的7026的端口号(默认的),把数据从chrome拿下来或者传过去.

如果我的理解正确,那么为什么不把所有这些事情交给客户端呢?比如wiz笔记就可以完全只有客户端,不用和浏览器插件talk.从你客户端的安装文件来看,基本上也就包含了一个浏览器在里面.

**Comment by Kenshin** [comment]
> 如果我的理解正确,那么为什么不把所有这些事情交给客户端呢?比如wiz笔记就可以完全只有客户端,不用和浏览器插件talk.从你客户端的安装文件来看,基本上也就包含了一个浏览器在里面.

很简单

1. 简悦的全部功能基于阅读模式，而阅读模式最好的载体就是浏览器。
2. 浏览器是一个入口。
3. 虽然可以在同步助手中内置一个浏览器，但对于用户来说是个「负担」。

简悦跟 wiz 的产品逻辑不一样，wiz 是笔记类产品，简悦是信息管理类产品。

后者需要信息的载体和入口，前者本身就是入口和载体。
