### ISSUE TITLE
同步的一些疑问

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#4981]
问题
1. 由于是区中心化,localhost的设计.所有的设置都是被保存到本地simpread_config.json文件里面?
2. 标注和随后读标题也放在这个json文件里面?
3. 随后读的网页是否已经保存到了本地硬盘上?如果是,那么放在哪里了?
4. 本质上需要同步的东西就是上面提到的json文件?
5. 如果同一台PC,看了两个浏览器,同时打开了simpread.如何保证这两个的json配置是一致的?因为我遇到了丢失稍后读文章的情况,我猜测是由于我开了两个浏览器,同时保存的情况.(不确定,我没有办法复现)
6. 假设1的猜测成立,那么我是否可以通过坚果云等对json文件进行同步?把json放到obsidian里面,obsidian是通过webdav进行同步的,自然这个json文件就被同步了
7. 如果6成立,那么PC端的同步助手有什么用?或者说PC端的同步助手本身的目的是否就是为了同步json?除此之外还有什么用?
8. 我还没有实验同步问题.假如我在A电脑上做好了设置,我只需要把json文件copy到B电脑,并且导入,是不是就完成了手动的同步?各种设置,稍后读,标注都已经到B电脑上了?

谢谢

**Comment by wieniawski-lai** [comment]
9. 我又看来一遍文档,所有的配置,本身是放在浏览器的沙箱里面.因此,同步助手的作用是将这个沙箱里面的配置,同步到硬盘上一个指定的位置,然后这个同步之后的json文件再通过网盘进行不同电脑之间的同步?
10. 同步助手和浏览器的通信也是走的localhost,默认的端口是7026?这也就是需要在浏览器的SimpRead的选项卡里面验证的端口号,需要和同步助手里面的端口号一致?

**Comment by Kenshin** [comment]
嗨，你的大部分疑问都可以阅读 https://www.yuque.com/kenshin/simpread/ebwu7g 后解决。

> 问题1 / 2 / 4 / 9

是的

> 问题5

使用同步助手

> 问题6

可以这么做，有简悦用户这么干过，也就是说简悦的同步机制可以不限制任何网盘。

但这么做的话，暂时无法使用 API 相关功能。（这些问题在我给你的链接中有描述）

> 问题7

同步助手不仅仅只是提供自动同步，还有增强导出、稍后读极速版等。

> 问题8

是的，但同步不包括插件，仅包含插件的配置，因为插件太大了。

在新设备上使用从配置文件导入插件后，就能还原插件。

> 问题10

端口是默认的也就是不需要更改，用户不需要太关注这个事情。
