### ISSUE TITLE
md+assert问题后续

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#4983]
之前那个issue已经close了,

我把回复到那边的内容copy link过来
[reply0](https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368806205)
[reply1](https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368828617)
[reply2](https://github.com/Kenshin/simpread/issues/4980#issuecomment-1368844217)

**Comment by Kenshin** [comment]
不需要 😂 即便 Close 了你依然可以继续讨论，有必要我可以重开它。
