### ISSUE TITLE
不能安装超过9个插件

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#4984]
**请说明发生问题的环境**

- 操作系统 **Win10 Home**

- 浏览器版本 **Brave [版本 1.48.93 Chromium: 109.0.5414.46（正式版本） （64 位）](https://brave.com/latest/)

- 简悦版本 **2.2.0.520**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

不能安装超过9个插件

- 本来已经安装了9个插件了
- 然后通过插件管理器安装[代码增强](https://simpread.ksria.cn/plugins/details/klGUASLasg)这个插件
- 然后把模仿 Safari 阅读模式样式插件卸载,剩四个插件
- 再安装代码增强插件成功.

**Comment by Kenshin** [comment]
没有这个关系，九个只是一个提示…

你的问题应该这个问题造成的 https://www.yuque.com/kenshin/simpread/fcw60u 内含解决方案

**Comment by wieniawski-lai** [comment]
> 没有这个关系，九个只是一个提示…
> 
> 你的问题应该这个问题造成的 https://www.yuque.com/kenshin/simpread/fcw60u 内含解决方案

您这个解决方案我看过

之前我通过网页端直接安装插件能装上,然后在阅读模式里面找不到插件的设置.我搜了一大圈,找到的解决方案就是你的链接.

于是我后来所有的插件安装都是通过,插件管理器,来进行插件安装的

于是我又试了一遍
- 直接通过插件管理器安装第**10**个插件,不成功
- 关闭自动同步,再从网页端安装第**10**个插件,仍旧不成功
- 他的提示也不是提示9个,而是不要超过6个.

这个问题不是必须解决的,因为我很难用到那么多插件,现在的9个已经足够我用了.

**Comment by Kenshin** [comment]
其实肯定是没问题的，因为程序上根本就没有最大数的限制。

而且我安装了几十个插件 😂

<img width="911" alt="image" src="https://user-images.githubusercontent.com/81074/210300037-5d8c47f7-9100-4f0a-b52b-1c23455fb3be.png">

***

正如你说，这个问题跟你无关，不过你愿意折腾的话（我不建议这么做 😂）

可以重新安装简悦，然后导入你的配置文件，然后再继续增加新的插件。
