### ISSUE TITLE
Notion自动化增强插件根据标题更新属性的问题

### ISSUE THREAD

**Issue by innnnel** [Kenshin/simpread#4986]
- 操作系统 **Windows**

- 浏览器版本 **Microsoft Edge 版本 108.0.1462.54 (正式版本) (64 位)**

- 简悦版本 **2.2.0**

如果修改了稍后读的标题，再进行增强导入就会找不到文章。
问题似乎是因为不管是否修改过标题，导出到notion的始终是网页原标题，但增强导入却是以稍后读标题为准的。因此修改后增强导入就无法找到文章了。
如果我手动对notion中的页面标题进行修改，增强导入就能找到页面了
希望可以统一一下这里的逻辑。

另外是否可以考虑在notion中另增加一个属性来对页面原标题进行保存，以此来标记页面唯一性，这样我至少可以把这个属性隐藏不看。因为有些页面的原标题实在太长太丑了，强迫症忍不了😅

PS：导出标注到notion有快捷键吗？我好像没有找到，每次都要点点点有点烦

**Comment by Kenshin** [comment]
> 修改了稍后读的标题，再进行增强导入就会找不到文章。

是的。

Notion API 并没有那么方便，所以暂时只能通过标题来判断 😂

> 导出到notion的始终是网页原标题

是的，这里确实需要优化下，我先记录下，修复后告诉你

你可以暂时使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 再导入前修改标题。

另外，明确下：

1. **导入到 Notion 插件**有标题（你提到的）问题。
2. **导入到 Notion 辅助增强插件**没有问题。

> 导出标注到notion有快捷键吗

有，https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020 有详细说明。

> 是否可以考虑在notion中另增加一个属性来对页面原标题进行保存

有点意思，但可能比较麻烦，毕竟标题也有重复的问题。

但思路不错，我可以考虑用另外的方式实现。

**Comment by Kenshin** [comment]
嗨，这个问题已修复。

- 如果**使用同步助手的自动同步**，则需要使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

- 如果没有使用同步助手的自动同步，直接使用 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 升级。
