### ISSUE TITLE
重装系统之后，配置简悦插件的时候，导入配置文件，一直卡在了在导入界面

### ISSUE THREAD

**Issue by YangWaldon** [Kenshin/simpread#4987]
Win10 Edge浏览器
![image](https://user-images.githubusercontent.com/49675185/210315816-68e37e3f-8074-49dd-af3a-70fbd34eee33.png)
不知该怎么办了

**Comment by Kenshin** [comment]
1. 重启同步助手。
2. 看看 DevTools 是否有报错？如果有报错的话，需要使用 [历史记录](https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a) 还原。

**Comment by YangWaldon** [comment]
① 什么是DevTools
② 我的配置文件都是保存在OneDrive中的，而且我之前仅仅使用了同步助手的自动导出附件的功能，没有使用“自动同步”功能

**Comment by Kenshin** [comment]
> 什么是DevTools

在你截图所示的页面上，右键，然后然下图所示打开

<img width="235" alt="image" src="https://user-images.githubusercontent.com/81074/210319470-ec224303-8304-46c2-9624-12118fb89156.png">

> 我的配置文件都是保存在OneDrive中的，而且我之前仅仅使用了同步助手的自动导出附件的功能，没有使用“自动同步”功能

emmm 也就是说你导入的配置文件是重置系统后导出的？（并且这个配置文件也没有使用自动同步）如果是这样的话，不应该有截图所示的界面才对...

还是先看看你的 Devtools 是否报错后再讨论吧。

**Comment by YangWaldon** [comment]
刚才我点击插件首页的”数据清除“，然后关掉同步助手的”同步服务“，然后再次导入配置文件就成功了
① 配置文件在OneDrive中也有历史回溯功能，跟坚果云中差不多，都有历史版本记录
② 还有个问题就是，我上次遇到这个问题时是因为设备被锁了，然后我刚才去”高级账户平台“页面看，设备并没有超过3个，但是为什么我的剩余解锁次数是0呢？
![image](https://user-images.githubusercontent.com/49675185/210320961-5e9e7182-d93d-4846-bdf4-8c2e3d0a7825.png)

**Comment by Kenshin** [comment]
> 但是为什么我的剩余解锁次数是0呢？

剩余解锁次数并不会重置，也就是说你已经用过三次了。

另外，当首次升级为高级账户后会自动下载一个包含 UID 和 License 的文件（2.1.0 版），所以一般来说现在很少有用户使用这个功能了。

但 2.0.0 版则没有这个功能，有些不留意 UID 的用户因此会丢失 UID。
