### ISSUE TITLE
增加导出到思源笔记

### ISSUE THREAD

**Issue by bighaidao** [Kenshin/simpread#4988]
hi，kenshin， 能否增加一下对思源笔记的导出呢？  
目前部署了一个 docker 版本的思源笔记，感觉非常适合当前的需求。但是唯一不好的 就是素材收集太麻烦。 希望 simpread 增加个功能支撑下。 

我看了下 思源笔记有对应的 API，适配成本可能不是很高。

希望考虑下，感谢感谢

**Comment by Kenshin** [comment]
嗨，谢谢，会考虑的。

**Comment by bighaidao** [comment]
> 嗨，谢谢，会考虑的。

好的 ，好的。3ks

**Comment by Kenshin** [comment]
我关闭这个 Issues 了，关联 https://github.com/Kenshin/simpread/issues/5555

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
