### ISSUE TITLE
微博头条文章导出离线HTML文件后 图片无法正常显示

### ISSUE THREAD

**Issue by Chare-Dream** [Kenshin/simpread#4989]
- 操作系统 **MacOS**

- 浏览器版本 **Chrome Version 108.0.5359.124 (Official Build) (arm64)**

- 简悦版本 **2.2.0.520**

**请描述你的问题**

问题网页：https://card.weibo.com/article/m/show/id/2309404853842918375661?id=2309404853842918375661

问题：在阅读模式下，使用“导出为 离线HTML”功能后，本地保存的HTML文件中 图片无法正常显示

**截图**
![image](https://user-images.githubusercontent.com/79248301/210488548-5a149608-b29f-4f69-9b04-3c8ecd9f0569.png)

**Comment by Kenshin** [comment]
emmm 确实如此

应该是微博增加了对图片的限制造成的，一般来说这种情况网站不希望这个图片被正常的「转存」，所以简悦并不会太多干涉这种情况。

不过，你可以使用 [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) 将图片上传到 Notion 也一样可以保存。
