### ISSUE TITLE
不能加入到稍后读

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#4990]
我已经在PC-A上面完成了所有的设置.

现在在PC-B上面同步所有的设置.同样的操作系统和同样的浏览器.

在打开某一个网页的时候,点击加入稍后读,报错

然后打开稍后读,发现并没有加到稍后读里面

![readlater](https://user-images.githubusercontent.com/70927596/210492546-22145189-ffb7-4429-8202-451433777a53.png)

**Comment by wieniawski-lai** [comment]
我确实是让B导入的A的设备.

当然我所做的事情原不止如此,曾经我在B机器上始终装不上插件,不管是直接装还是用插件管理器装.我折腾过很多,重装浏览器,删AppData.最后我的解决办法是,先在干净的browser上装插件,再导入json.我实在不知道这其中问题在哪里,我只能说我解决了不能安装插件的问题.

理论上,我是导入的json文件,没有理由设置会不一样.

而且,加入稍后读,是一个非常基础的功能,是不需要同步助手之类的.

我明天在把A机器带到B机器旁边对比一下配置.

再者,简悦可以记录log吗?

从而方便debug

zotero就可以记录log,然后提交给zotero官方的ticket.

**Comment by wieniawski-lai** [comment]
当然,也跟我自己比较作有关系.用了一个比较小众的Brave浏览器.

我也不知道这个浏览器自己会不会有什么bug,会不会和简悦配合不好.

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4990#issuecomment-1370867303

Brave 确实有点问题，但跟你提到的问题无关。

> 加入稍后读,是一个非常基础的功能

如果你没有使用同步助手的话，几乎没有出现问题的可能性…

所以，建议还是确认下导入的配置里面是否有稍后读数据。

**Comment by wieniawski-lai** [comment]
fine, 我明天再试一下.

BTW, Opera适配简悦适配得好吗.

我为了简悦从firefox叛逃出来.反正现在还没有彻底决定用哪个浏览器.

**Comment by Kenshin** [comment]
浏览器的话，不喜欢 Chrome 可以用 Edge 其他魔改的有点严重。

如果是 Mac 的话，也可以试试 Arc

**Comment by wieniawski-lai** [comment]
> > [#4990 (comment)](https://github.com/Kenshin/simpread/issues/4990#issuecomment-1370867303)
> 
> Brave 确实有点问题，但跟你提到的问题无关。
> 
> > 加入稍后读,是一个非常基础的功能
> 
> 如果你没有使用同步助手的话，几乎没有出现问题的可能性…
> 
> 所以，建议还是确认下导入的配置里面是否有稍后读数据。

我今天又试了一遍

我在B机器手动导入了A机器的配置

我能够在B机器里面看到稍后读的所有内容.

但是还是不能在B机器上把网页加入稍后读.现象和之前一样.而且插件也装不了了.

我最后再折腾一次,您这个有log功能吗?

通过查log看为什么加入稍后读不成功.

如果这一次折腾不出来,我就换chrome(因为我还有一个linux的主机,所以即使我很反感chrome,也不能用edge)

**Comment by Kenshin** [comment]
> 但是还是不能在B机器上把网页加入稍后读.现象和之前一样.而且插件也装不了了.

试试使用快捷键 `d d` 加入稍后读。

另外，加入稍后读后：

1. 看看有什么提示？
2. 建议重启浏览器。

> 我最后再折腾一次,您这个有log功能吗?

有，但属于同步助手的功能，而且也没有关于稍后读的相关 Log 功能 😂

**Comment by wieniawski-lai** [comment]
![image](https://user-images.githubusercontent.com/70927596/210933435-dbaba033-1555-4f8a-bb83-a7580912ca40.png)

1. dd也不行,现象如上,和前面一样
2. 提示就是附件的图片
3. 浏览器重启过了

**Comment by wieniawski-lai** [comment]
嗯......

我已经换chrome了

还是不能加到稍后读,报一样的提示......

**Comment by wieniawski-lai** [comment]
嗯

我使用dd快捷键的时候,是可以把文章抓下来到本地,存成md+assert的

所以问题出在网页端SimpRead扩展本身,加不到Brave或者Chrome的沙箱

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/4990#issuecomment-1373147281

这个提示明显是除了加入稍后读外，还包含了其它的自动化方案，建议排查下。比如：是否使用了增强导出但却没有运行同步助手。

<img width="1729" alt="image" src="https://user-images.githubusercontent.com/81074/210936496-bd45a305-a5b0-43d2-9408-63a5fff31983.png">

**Comment by wieniawski-lai** [comment]
Finally, I found what is wrong, which is my mistake.

1. 不是自动化方案的问题
2. 也运行了同步助手

但是,您提醒了我,我运行了同步助手,但是没有在B机器上绑定同步助手......

Which is my mistake.

Sorry.

Thanks for your patient explanation.
