### ISSUE TITLE
稍后读丢失

### ISSUE THREAD

**Issue by ProudBenzene** [Kenshin/simpread#4991]
今天我发现我的稍后读丢失了，于是我去到坚果云里边找历史文件，找到了之前的config文件，由于之前的文件有1.7M，现在只有6k，所以蛮好找的。
找到之后下载下来，然后通过选项页倒入本地配置文件，却发现这个配置文件中也没有之前的稍后读。请问是还需要做什么额外的操作吗？

**Comment by ProudBenzene** [comment]
另外还有一个奇怪的现象，我把1.7M的配置文件传到坚果云上，之后甚至都没有用简约阅读文章，过了几分钟之后这个配置文件的大小就莫名其妙的又变成了6k，反复几次都会这样。

**Comment by Kenshin** [comment]
> 却发现这个配置文件中也没有之前的稍后读

emmmm 你是说在选项页 → 稍后读中没有任何内容？

不需要任何额外的操作，建议**重新安装简悦**，然后再通过 **选项页 → 共通 → 从本地导入配置文件** 的方式确认下。

稍后读确认无误后，还需要通过选项页 → 插件管理 → 从配置文件导入插件（因为插件太大了，所以没有放到配置文件中）。

<img width="904" alt="image" src="https://user-images.githubusercontent.com/81074/210535126-75039d83-e70a-4742-8b19-c8981bf260d1.png">

最后，看下选项页 → 共通 → 自动同步，是否开启，如果开启的话，建议**手动保存配置文件到本地**。

<img width="897" alt="image" src="https://user-images.githubusercontent.com/81074/210534907-12f55333-cd08-40f2-b8d0-f3568e869e5f.png">

然后看看你的本地 `simpread_config.json` 的 size 是否正确。

> https://github.com/Kenshin/simpread/issues/4991#issuecomment-1370642514

这个问题估计是你导入后的配置文件，没有覆盖到到本地（猜测）造成的。安
