### ISSUE TITLE
打开特定某些 React 构建的网站，页面会崩溃

### ISSUE THREAD

**Issue by Mongkii** [Kenshin/simpread#4992]
**请说明发生问题的环境**

- 操作系统 **MacOS 13.1**
- 浏览器版本 **108.0.5359.124**
- 简悦版本 **2.2.0.520**
- 发生问题的地址 https://www.notion.so/templates/collections/new-year-2023-personal

**请描述你的问题**

1. 保持简悦为启用状态
2. 打开网站 https://www.notion.so/templates/collections/new-year-2023-personal
3. 页面白屏，提示有错误。打开控制台会看到报错 `DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
4. 禁用简悦，在新窗口重新打开网站
5. 页面正常

**截图**

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8596458/210622312-f22e41e2-270f-4421-90a5-0b07fd205d1a.png">

**原因推测**

从报错信息来看，是由于无法移除 node 导致错误。原因可能是简悦先于 React 将页面某些元素移除了，使得 React 自己的调度移除失败。

**Comment by Kenshin** [comment]
嗨，很容易解决，解决方案 https://github.com/Kenshin/simpread/discussions/2347

**Comment by Mongkii** [comment]
所以这种情况是符合预期的？是否还能进一步优化这个功能，以避免该问题呢

**Comment by Kenshin** [comment]
当然需要修复，只是目前可以有办法规避。

而且并不是每个 React 构建的网站都有问题。
