### ISSUE TITLE
当 Notion 授权失效后，开启 Notion 图床导入后需要有明确提示

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4995]
哈喽，目前勾选了图床之后会一直卡在上传图片这里，有同样的问题出现吗
<img width="536" alt="image" src="https://user-images.githubusercontent.com/9612053/210920414-df0b252d-7443-4a60-af41-4a9821f6395d.png">

_Originally posted by @sisibeloved in https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4607791_

**Comment by Kenshin** [comment]
@sisibeloved

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

Notion API 会偶尔抽风，属于正常情况，试试 https://sspai.com/post/69972 能否成功？或者提供下截图对应的 URL 我瞧瞧。

**Comment by sisibeloved** [comment]
破案了，我去选项里关掉图床，发现授权已经过期了，应该是插件没有给到正确的提示

**Comment by Kenshin** [comment]
> 发现授权已经过期了

原来如此...

emmmm Notion API 确实不稳定，所以不确定是否这个原因造成的。

不知道是否可以重现这个情况，如果可以的话，我会优化下~

**Comment by htyed** [comment]
勾选图床也授权了，之前一直是好用的，最近出现的这个问题，一直卡在这里
不勾选图床时，能正常保存到notion中，只是图片没有传到notion中，是以原图片链接的形式展现的
截图中是以 https://sspai.com/post/69972 展示的
![image](https://github.com/Kenshin/simpread/assets/64642487/f07c8a49-2e44-4130-bb4e-8de987ee9277)

**Comment by Kenshin** [comment]
@htyed 

收到，因为用的是私有 API，所以估计 Notion API 日常抽风... 先观察两天~

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  解决了这个问题，详细说明 & 讨论请前往 #5917

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
