### ISSUE TITLE
obsidian转化出错或者Manual Sync之后, 暗色模式下高亮又变回很亮

### ISSUE THREAD

**Issue by Kalay1995** [Kenshin/simpread#4998]
高亮一般使用没啥问题, 但是我给标题添加如下备注之后, markdown显示yaml解析出错, 同时其他高亮标注又变回了很亮的黄色**#ffeb3b**, 离线网页正常

```
有风或者温差较大会有影响。

客机飞行云层温变较为稳定, 偏差较小, 高寒地区或者天气变化, 高度不准容易过低触山
```

此时删除备注中的回车, 用在线版功能“导入标注到obsidian”, 高亮又正常了

但是我又用了一下obsidian插件 SimpRead Sync的Manual Sync功能后, 所有标注都变回高亮黄色了

总之有两个地方会导致高亮恢复成很亮
1. 备注中有空行
2. Obsidian插件中的Manual Sync功能

win11 22H2,暗色模式

链接 https://bbs.dji.com/forum.php?mod=viewthread&tid=198531, 手动选择了全部内容

![image](https://user-images.githubusercontent.com/14127267/210966514-57ccc995-cc22-4e11-bbd6-4a6683f888bc.png)

**Comment by Kenshin** [comment]
如果你说的是截图左侧标注色的话，并不是简悦的问题，或者说是 Markdown 模板的问题。

因为左侧的标注色是专门针对于亮色的，而截图则是暗色模式，在 Obsidian 阅读界面是有问题的。

你需要使用 https://github.com/Kenshin/simpread/issues/4887 对应的方案。

> 用在线版功能“导入标注到obsidian”,

所以我怀疑你在 Markdown 模板辅助增强插件与 Obsdiain SimpRead Sync 的模板不是一套。

**Comment by Kalay1995** [comment]
> 如果你说的是截图左侧标注色的话，并不是简悦的问题，或者说是 Markdown 模板的问题。
> 
> 因为左侧的标注色是专门针对于亮色的，而截图则是暗色模式，在 Obsidian 阅读界面是有问题的。
> 
> 你需要使用 #4887 对应的方案。
> 
> > 用在线版功能“导入标注到obsidian”,
> 
> 所以我怀疑你在 Markdown 模板辅助增强插件与 Obsdiain SimpRead Sync 的模板不是一套。

确实是simpread sync插件的问题, 不过simpread sync也是obsidian高级版配置教程默认的, anyway 现在我会改了

![image](https://user-images.githubusercontent.com/14127267/211024420-52e026fc-f777-4257-9513-a5a175edecce.png)

**Comment by Kenshin** [comment]
Cool 解决就好。

配置库不可能有符合每个用户的方案，只能确保用户在最小配置下即刻使用简悦的高级功能。

所以当使用起来后遇到问题通过 Issues 讨论大部分都可解决。

**Comment by Kalay1995** [comment]
作者处理问题的速度真是快, 非常棒！

**Comment by Kenshin** [comment]
> 作者处理问题的速度真是快, 非常棒！

小事情，我每天最少都要处理 10+ 左右的 Issues，把任务（事件）拆分后，其实花不了多少时间。😄

***


方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
