### ISSUE TITLE
知乎专栏文章的公式问题（个例）

### ISSUE THREAD

**Issue by pinecho** [Kenshin/simpread#4999]
**请说明发生问题的环境**

- 操作系统 ** MacOS**

- 浏览器版本 **Edge Version 108.0.1462.54 (Official build) (arm64)**

- 简悦版本 **2.0.0**

**请描述你的问题**

在知乎专栏文章中选择导出到obsidian或离线Markdown时，会出现数学公式重复的问题。
例如导出https://zhuanlan.zhihu.com/p/448575579 后，
![image](https://user-images.githubusercontent.com/37013626/210975826-41f3f830-ae29-4260-b465-c0409b49940c.png)

已按照 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808 的说明将`zhuanlan.zhihu.com`加入延迟加载列表，并刷新设置+重启浏览器，但是再次导出时依然出现上述问题。

P.S. 在CSDN网页似乎也会出现同一问题
例如导出https://blog.csdn.net/wjpwjpwjp0831/article/details/125470648 后，
![image](https://user-images.githubusercontent.com/37013626/210977197-d7835ffb-8357-4afe-9ff7-1a2477d39a6a.png)

知乎的公式会出现2次，csdn的公式会出现3次

**Comment by Kenshin** [comment]
比如 https://zhuanlan.zhihu.com/p/413150417 就不会出现这个问题，我发上来你看下，你也可以试试这个链接是否有问题。

[矩阵论概念及定理.txt](https://github.com/Kenshin/simpread/files/10359838/default.txt)


> https://blog.csdn.net/wjpwjpwjp0831/article/details/125470648

这是 Katex 方案，简悦暂时不支持这种方式，简悦仅支持 MathJax 方案，也就是知乎公式这种。

**Comment by Kenshin** [comment]
emmm 我研究下，有点奇怪（意思）的问题。

**Comment by gongwangshen** [comment]
我也遇到了这个问题

**Comment by Kenshin** [comment]
@gongwangshen 

请提供 URL

**Comment by gongwangshen** [comment]
> 

https://zhuanlan.zhihu.com/p/44860862

**Comment by gongwangshen** [comment]
![20230314_100103_965_copy](https://user-images.githubusercontent.com/109449633/224873026-c876eb7d-4e1a-46a0-badc-1ab69d50c56a.png)

**Comment by Kenshin** [comment]
@gongwangshen 

公式的显示应该没问题

![image](https://user-images.githubusercontent.com/81074/224880279-75aac766-e153-4d19-ae34-27c5c72a9b6b.png)

这是导出，应该也没什么问题

<img width="890" alt="image" src="https://user-images.githubusercontent.com/81074/224880468-b1120dcf-eb0a-427d-adac-8e1f4b44d0c3.png">

这是我导入到 Obsidain 的文件，你可以看看 [浅谈「正定矩阵」和「半正定矩阵」.txt](https://github.com/Kenshin/simpread/files/10963698/default.txt)

如何使用知乎公式的话，请看 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808

**Comment by gongwangshen** [comment]
已解决，谢谢

**Comment by Kenshin** [comment]
@gongwangshen 

搞定就好~

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Kenshin** [comment]
但可惜的是：这个页面的问题仍旧存在，我测试了在这里提问的 Issues（超过 20+ 对应的知乎专栏的公式规则，都没问题，唯独这个 😂

它的公式结构有点问题，所以造成了这个现象，我关闭这个 issues 合并到 https://github.com/Kenshin/simpread/issues/4624 里面 Mark~
