### ISSUE TITLE
使用快捷键直接加入稍后读无法自动保存

### ISSUE THREAD

**Issue by JJcdomat** [Kenshin/simpread#5001]
如果先进入阅读模式，再加入稍后读可以触发自动化。但是直接在网页中使用快捷键加入稍后读，能正常加入稍后读，但无法触发自动化任务。

**Comment by Kenshin** [comment]
嗨，这是正常的。

当未进入阅读模式前，仅可以加入稍后读，但无法触发自动化，因为这时正文还没有提取出来。
