### ISSUE TITLE
浮标出现动效过慢，希望优化一下

### ISSUE THREAD

**Issue by holduan** [Kenshin/simpread#5004]
**请说明发生问题的环境**

- 操作系统 **Windows 11**

- 浏览器版本 **Microsoft Edge 108.0.1462.76 (正式版本) (64 位)**

- 简悦版本 **2.0.0**

**请描述你的问题**

浮标出现动效太慢，消失还可以。但动效机制太多——鼠标不同方向靠近选择的文本会触发不同动效，而且因为有一直跟随标标的机制，会有很多额外且不自然的动效，使用感受是很不利索，希望可以改进，例如增加出现在鼠标右下角的位置，缓进再短一点。

录屏用的165帧，Davinci里映射成120帧，简悦的出入动效都太长了些。

https://user-images.githubusercontent.com/80377040/211159993-4f6aa9e3-64b8-4b17-9a90-876fcfc012ef.mp4

https://user-images.githubusercontent.com/80377040/211160047-067d87ad-fb21-4b08-ad96-5566bf0c9cb3.mp4

**Comment by Kenshin** [comment]
改为下面的选项

<img width="826" alt="image" src="https://user-images.githubusercontent.com/81074/211181964-2c2454bd-3735-4c8d-b770-7dcbc8e5ee1f.png">
