### ISSUE TITLE
Obsidian SimpRead Sync无法打开原网页

### ISSUE THREAD

**Issue by byftju** [Kenshin/simpread#5005]
现象：
![image](https://user-images.githubusercontent.com/38159115/211186584-523e5e7a-a172-4e11-9d0a-9c26667ddd74.png)
进行设置后，无法打开本地的HTML文件。

![image](https://user-images.githubusercontent.com/38159115/211186689-2ba6573f-62fc-47e1-9490-a7323a44289d.png)
增强导出如下图所示。

**Comment by Kenshin** [comment]
你需要在同步助手 → 导出，设置本地快照的目录

<img width="679" alt="image" src="https://user-images.githubusercontent.com/81074/211187108-996687c6-cf26-45ba-989b-66db414de2c8.png">

- 相应的教程（说明）看这里 https://www.yuque.com/kenshin/simpread/wkswh7

- 新用户的话，可以直接使用 https://www.yuque.com/kenshin/simpread/wq35mh 方案

- Obsidian SimpRead Sync 的教程 https://www.yuque.com/kenshin/simpread/fr8zo5
