### ISSUE TITLE
obsidian全文本地保存相关

### ISSUE THREAD

**Issue by KwaBEF** [Kenshin/simpread#5007]
![image](https://user-images.githubusercontent.com/61895233/211194983-88c97aab-f038-4116-b035-a1fbe99c1b4e.png)
我保存在了obsidian的全文，包括文章和图片文件夹及标注，但是坚果云里的简悦文件夹没有同步出现，文件只在obsidian文件夹里面，导致内部链接打开是错误空白？
内部链接怎么设置成到obsidian里已保存的文件上面？

**Comment by Kenshin** [comment]
你需要的功能叫做 **知识库** 如何设置看这里 https://www.yuque.com/kenshin/simpread/wkswh7

如果使用的是 [配置库方案](https://www.yuque.com/kenshin/simpread/wq35mh) 的话，正常是自带这个功能的，如果不好使的话，需要对比下你的配置与教程有什么区别？
