### ISSUE TITLE
[Logseq] 「生成全部」的文件的目的地文件夾

### ISSUE THREAD

**Issue by lyserenity** [Kenshin/simpread#5008]
现在「生成全部」所生成的文件都导入到 `output/` 之下
但应该是依照同步助手「导出」里的设置较合理 🤣 

麻烦帮忙确认一下，感谢！

**Comment by Kenshin** [comment]
> 麻烦帮忙确认一下，感谢！

什么时候这么客气了？  🌚

**Comment by lyserenity** [comment]
> > 麻烦帮忙确认一下，感谢！
> 
> 什么时候这么客气了？ 🌚

有求于人的时候.....

**Comment by Kenshin** [comment]
怎么？解决了？ 😂

**Comment by Kenshin** [comment]
没问题的～ 😂
