### ISSUE TITLE
在有些掘金文章中使用阅读模式,代码段会重复出现

### ISSUE THREAD

**Issue by XYShaoKang** [Kenshin/simpread#501]
SimpRead: v1.1.2.5005
Chrome: v74.0.3729.157(x64)
Window10: v1903

代码段会重复出现的文章链接: https://juejin.im/entry/59e565f35188250989512689

![2019-05-19_17-01-19](https://user-images.githubusercontent.com/38753204/57980018-ebe66880-7a57-11e9-94b8-dec09464bf55.jpg)

我对比了下其他代码段不会重复的文章,发现会重复的代码段,在原始的 html 结构中使用了嵌套的`code`标签,而没有使用嵌套`code`标签的不会出现重复的现象,可能这个是导致重复的原因.

![2019-05-19_17-06-44](https://user-images.githubusercontent.com/38753204/57980080-e9384300-7a58-11e9-99d3-91b51f4dda84.jpg)

其他可能有用的信息:
1. 当我把`高级设定-> 词法分析引擎-> 纯粹模式`选项关闭时,也不会出现重复的代码段.
2. 我使用 360 极速浏览器测试了下,也同样会出现重复的代码段.

**Comment by Kenshin** [comment]
谢谢反馈以及解决办法，可以解决这个问题。

我以为只发生在 csdn 解决办法可以看 https://github.com/Kenshin/simpread/issues/500

明天会彻底解决这个问题。

**Comment by Kenshin** [comment]
此问题已经解决~ 详细请看 https://github.com/Kenshin/simpread/issues/500

我将关闭这个 issues ~
