### ISSUE TITLE
每更新一次标注或是导出md+assets到ob都会重新下载文章里的图片

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#5010]
文章加入稍后读后，开始标注，每标注一次，文章图片就在本地多一份，我确定以前是不是也是这样，只是今天发现了这个情况，不知道这个是本身就是如此还是说是个bug
<img width="657" alt="image" src="https://user-images.githubusercontent.com/3283023/211211609-31d567ee-04dc-42dc-b790-4f3e6f79f017.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/3283023/211211528-50c28dc9-19bb-46a4-8942-ce07eb47ae71.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/3283023/211211546-e6928d65-976e-4b6a-93cc-e2a4cf0a638f.png">

**Comment by Kenshin** [comment]
> 每标注一次，文章图片就在本地多一份

不算是 Bug，标注时确实有这个情况发生，因为不可能记录哪些图片是已经保存了，哪些没有保存。

在保存图片时的名称是它的 `生成时间`，所以当每次生成图片时，并不会替代原来的旧图片，所以才造成了你提到的情况。

目前也没有太好的办法。

**Comment by iblogc** [comment]
那我在标注的时候得把坚果云同步关掉，不然图片多的文章坚果云同步流量哗哗的跑:joy:，标注完开坚果云同步前再用 obsidian-file-cleaner 清理下多余图片:rofl:

**Comment by Kenshin** [comment]
我考虑了下，即便改成自增长的序号也不行，因为每次标注时的序号都要重新计算...

所以，还是使用 `obsidian-file-cleaner` 是上策 😂

**Comment by iblogc** [comment]
如果用图片的md5当文件名是否可行？

**Comment by Kenshin** [comment]
> 图片的md5

检索图片的 md5 太慢了，而且 md5 也忒大了。

其实使用原图片地址就行，但有些网页规则比较奇怪，图片 URL 是一个地址... 😂

**Comment by iblogc** [comment]
嗯，计算速度是需要考虑下，但图片只要不是非常大，计算速度应该还是可以的，我本地用python试了下，以下是试验结果（试验取1000次结果的平均值），md5也只有16位和32位两种长度，不大😂
|图片大小| 计算md5耗时|计算sha1耗时|
|---|---|---|
|336K|0.41205ms|0.62634ms|
|11M|19.387ms|15.481ms|
|33M|58.111ms|44.711ms|
|236M|394.56ms|304.56ms|

**Comment by Kenshin** [comment]
你可以试试 https://sspai.com/post/66803 里面的图片，这些图本来就很大。

还有就是当图篇较多时也需要考虑时长的问题。

毕竟你遇到的问题并不是个常规性问题，很多用户都只是用来转存的。

**Comment by iblogc** [comment]
> 你可以试试 https://sspai.com/post/66803 里面的图片，这些图本来就很大。
> 
> 还有就是当图篇较多时也需要考虑时长的问题。
> 
> 毕竟你遇到的问题并不是个常规性问题，很多用户都只是用来转存的。

这篇文章里总共95张图片，总计17.9M，导出md+assets耗时10s（纯手式秒表计算:joy:，主要耗时应该是在下载图片）。遍历读取图片计算md5耗时52.415ms，遍历读取图片计算sh1耗时44.963ms
