### ISSUE TITLE
标注输入框输入状态底色太亮，标注容易变成标记一个单词

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#5012]
# 输入框输入状态底色太亮: 
![image](https://user-images.githubusercontent.com/3938751/211233842-6f291e60-5c56-4a6d-a709-7d32c277b782.png)

# 点击保存不会退出，要再点退出
![image](https://user-images.githubusercontent.com/3938751/211233923-4344f107-0b05-4edb-880f-b8e13e091c1c.png)

# 点击这2个按钮，有时候会弹出对一个单词的标注。
![image](https://user-images.githubusercontent.com/3938751/211233999-33f0fa54-fddc-445e-99f2-ced953fc6485.png)

![image](https://user-images.githubusercontent.com/3938751/211234631-1b3354d2-ea9f-4f58-be08-93cfce647d7d.png)

**Comment by Kenshin** [comment]
这个问题仅发生在你遇到的这个 URL 上，所以需要提供 URL 给我。

**Comment by eromoe** [comment]
http://www.sefidian.com/2021/06/12/introduction-to-advanced-candlesticks-in-finance-tick-bars-dollar-bars-volume-bars-and-imbalance-bars/

**Comment by Kenshin** [comment]
将下面的代码

```
dialog-gp textarea:focus {
    background-color: unset!important;
}
```

加入到下图所示的位置

<img width="460" alt="image" src="https://user-images.githubusercontent.com/81074/211252714-0f45a384-eab5-4270-942c-36e8ad8506bb.png">

**Comment by Kenshin** [comment]
至于下图的问题

<img width="615" alt="image" src="https://user-images.githubusercontent.com/81074/211252794-eacf8afb-c77c-4ccc-abe1-91e552d37e61.png">

建议多测试下，看看能否稳定复现。比如在少数派的网页 https://sspai.com/post/69972 测试等。

如果能的话，通过 https://github.com/kenshin/simpread/issues/new 讨论。

PS：一个 Issues 仅解决一个问题，否则容易乱~ 😂

**Comment by eromoe** [comment]
这种样式问题碰到都得手动添加吗？

**Comment by Kenshin** [comment]
目前来说，只有你提到的这一例。

从我的经验看，大部分页面并不会更改这里的配置，你提供的页面比较特别...
