### ISSUE TITLE
同步助手-稍后读-快照-页面什么情况下会是暗色的页面，需要在哪里设置&暗色页面看不清文字

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#5015]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows 11**

- 浏览器版本 **Microsoft Edge 版本 108.0.1462.76 (正式版本) (64 位)**

- 简悦版本 **2.2.0**
- 同步助手版本 **1.1.4**

**请描述你的问题**
同步助手里的文章什么时候会是暗色的页面，需要在哪里设置&暗色页面看不清文字
![image](https://user-images.githubusercontent.com/3283023/211235161-b098f013-7de1-4800-bb8c-80d8d2193452.png)

**Comment by Kenshin** [comment]
emmm

你在导出时是不是就是暗色模式？

**Comment by iblogc** [comment]
是的，我刚刚看了本地的html也是暗色，看不清文字，这文章是我昨天晚上加稍后读导出的，是不是哪个设置里有跟随系统自动切换成暗色模式

**Comment by Kenshin** [comment]
1.1.4 同步助手有个新功能：

1. 当导出 HTML 是浅色状态时，会跟随系统暗色模式变化，即：系统是暗色模式时，也会变成暗色模式

2. 当导出 HTML 是深色状态时，不会跟随系统变化，也就出现了你截图所示的效果。


> 是的，我刚刚看了本地的html也是暗色，看不清文字，这文章是我昨天晚上加稍后读导出的，是不是哪个设置里有跟随系统自动切换成暗色模式

1. 选项页 → 高级设定 → 暗色模式 → 暗色模式关闭
2. 主题色改成任何浅色模式

**Comment by iblogc** [comment]
好的🤝
