### ISSUE TITLE
导入 markdown + assets 到 obsidian ，不会同步

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#5021]
测试地址比如 https://sspai.com/post/77601

我是比较早用懒人配置配置的，今天发现导出存在问题

经过观察发现
1. 导入 markdown + assets 到 obsidian ， 只会在坚果云同步目录生成文件
    -  ![image](https://user-images.githubusercontent.com/3938751/211265416-2de664b2-d881-41b5-a5aa-84b171eafd86.png)
2. 在 OB 目录下找不到文件
   ![image](https://user-images.githubusercontent.com/3938751/211265638-2626f20f-ec29-437b-85ed-c0032bbefed1.png)

3. 导入标注 到 obsidian ， 则会在 OB 目录生成文件。 
4. 在 OB 目录 删除面上的标注文件后。 再次在页面上进行标注，没有点保存，又自动生成了新文件。

很困惑

# OB 目录
![image](https://user-images.githubusercontent.com/3938751/211264742-9608f5ef-0065-4c53-84a0-04c4c873639d.png)

# 坚果云同步目录

![image](https://user-images.githubusercontent.com/3938751/211264828-173d6619-0b02-4b5f-95b6-30d23d9c8cc6.png)

# 同步助手配置

![image](https://user-images.githubusercontent.com/3938751/211264848-58fcdf59-9c4d-4169-911c-749a95485701.png)

# 扩展的导出配置

![image](https://user-images.githubusercontent.com/3938751/211264954-5247d58d-d4e7-4174-8040-b9f538db7df6.png)

**Comment by Kenshin** [comment]
> 导入 markdown + assets 到 obsidian ， 只会在坚果云同步目录生成文件

这不是 Bug，你需要在 [同步助手的增强导出设置](https://simpread.pro/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)  `assets` 方案，如下图所示

<img width="819" alt="image" src="https://user-images.githubusercontent.com/81074/211286975-8ea83d55-b840-4630-a15f-1f559529b603.png">

也就是说：

> 导入到 md + assets 方式与标注「走」的不是一个方案。

**Comment by eromoe** [comment]
没搞懂，当时为什么要设置2个文件夹我也记不清是怎么回事了。。

翻了半天文档，觉得还是比较乱，我通过下面这么多个路径才找到当时为什么要配2个地址，然后发现obsidian 里的sync 扩展配置的。

https://simpread.pro/docs/#/Sync?id=%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA

https://simpread.pro/docs/#/Sync?id=%e5%af%bc%e5%87%ba%e7%b1%bb%e5%9e%8b

https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z

https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604

https://github.com/Kenshin/simpread/discussions/2902

https://github.com/Kenshin/simpread-configs/blob/main/obsidian@sync/Getting%20Started.md

-------------

另外关于 asset 配置会比较困惑，同步助手默认导出在output 文件夹下 ，ob 看不到
很多地址乍看之下都会以为要填到坚果云的同步文件夹下。

**Comment by eromoe** [comment]
尝试替换为 local restfule api ，还是保存到了坚果云目录  困惑.?
![image](https://user-images.githubusercontent.com/3938751/211318152-e66e398f-4b5b-4b0f-a5bb-c60ae8cd3d4b.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5021#issuecomment-1375598514

确实是这样的，我理解你的想法，但不能把它们混为一谈

> 坚果云同步目录

主要是针对快照用户的方式

> obsidian 标注输出目录, 需要配置

主要针对 obsidian 用户

> md+ assets， 需要配置

这本来也是一个独立的插件 https://simpread.ksria.cn/plugins/details/BvjrJA6eh5 专门针对剪藏本地图片用户的，只是将这个功能集成到 Obsidian 插件里面了。

不过，我可以考虑优化下这个地方，但优先级不高。

> 有没有可能设计配置一个目录解决呢？

其实可以都放在 obsidian 里面，根据不同的文件夹层级，有用户这么干过，但一个目录肯定不行。

或者说只要不使用 API 功能，并不限制用户将数据放到哪里，所以可以放到一个地方，但还是要在需要配置的地方指定路径。

其实说到底：简悦的功能不是完全针对于 Obsidian 用户的，所以看着可能比较奇怪。

> https://github.com/Kenshin/simpread/issues/5021#issuecomment-1375623107

我没理解你的问题，另外不建议使用 **Local Restfule API**，这个插件有坑，部分非常长的正文无法正常导入。

**Comment by Kenshin** [comment]
总结下：你只需要留意下面两个目录就行。


<img width="685" alt="image" src="https://user-images.githubusercontent.com/81074/211456393-3cd98e59-e6a3-4eca-92de-0f287bfac01c.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/81074/211456484-4fc07aea-05a8-47cd-aa70-5e64c1931d6a.png">

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
