### ISSUE TITLE
阅读模式不会自动加载已选定的主题，需要进入阅读模式后再手动点击。

### ISSUE THREAD

**Issue by anserzhang** [Kenshin/simpread#5023]
RT

**Comment by Kenshin** [comment]
emmm 很奇怪的问题

进入 https://sspai.com/post/69972 更改后重启浏览器后再测试。

另外，是否使用了同步助手的自动同步功能？

如果还是不行的话：

1. 导出配置文件
2. 删除并重新安装简悦
3. 导入第一步的配置文件

**Comment by anserzhang** [comment]
> emmm 很奇怪的问题
> 
> 进入 https://sspai.com/post/69972 更改后重启浏览器后再测试。
> 
> 另外，是否使用了同步助手的自动同步功能？
> 
> 如果还是不行的话：
> 
> 1. 导出配置文件
> 2. 删除并重新安装简悦
> 3. 导入第一步的配置文件

解决了，把暗色模式跟随系统关掉就好了，它默认启用了黑鹫，所以其他的模式要手动点一次。

**Comment by Kenshin** [comment]
> 把暗色模式跟随系统关掉就好了，它默认启用了黑鹫，所以其他的模式要手动点一次。

是个问题... 当暗色模式时确实无法选择浅色样式 😂
