### ISSUE TITLE
导出到obsidian (通过同步助手） 能否不创建文件夹

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#5026]
目前会产生一个文件夹，希望能不创建文件夹

![image](https://user-images.githubusercontent.com/3938751/211320599-2dca9995-f417-48d5-acc3-e73796e19f72.png)

且文件名没有生效
![image](https://user-images.githubusercontent.com/3938751/211320798-bb5640cc-8119-4ee0-8595-c0f24cd06c47.png)

PS：
测试下来，下面这2个按钮的效果是一样的，都导出了`文件夹/ md+assets`
![image](https://user-images.githubusercontent.com/3938751/211321139-bc63118e-e519-4798-8200-fa1262173fa0.png)

**Comment by Kenshin** [comment]
你可以使用 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 提到的方式三

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
