### ISSUE TITLE
保存到notion一直不成功，总是最后显示强稍后再试。

### ISSUE THREAD

**Issue by YIQIFENGFAA** [Kenshin/simpread#5027]
![image](https://user-images.githubusercontent.com/79069626/211438184-cbb180b7-e138-45c6-8e71-8709b85ffb25.png)

![image](https://user-images.githubusercontent.com/79069626/211438220-fac70dee-4888-46ad-86fa-a125efec28d9.png)
按照知乎视频操作的，普通的不行，notion增强也不行，重新授权试了好几次都不行。

**Comment by Kenshin** [comment]
1. 请使用 [导入到 Notion 插件](https://github.com/Kenshin/simpread/discussions/4954)
2. 安装后重启浏览器
3. 先关闭图床功能
4. 在 在 https://sspai.com/post/69972 上测试。

如果这个 URL 没问题的话，请提供下你的 URL 给我，或者多测试几个不同的 URL

**Comment by Kenshin** [comment]
扩展端的导入 Notion 并不太好用，所以我开发了插件端。

至于 icon 的问题，在 https://sspai.com/post/69972 之类的网站是好使的，这个暂时没法修改
