### ISSUE TITLE
导入到 Notion 辅助增强  安装无反应

### ISSUE THREAD

**Issue by SeasonPilot** [Kenshin/simpread#5029]
**请说明发生问题的环境**
MacOS+chrome

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

导入到 Notion 辅助增强  安装无反应

https://simpread.ksria.cn/plugins/details/g60jwZEeqU

**Comment by Kenshin** [comment]
嗨，如果使用了同步助手的自动同步功能的话，需要使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装插件。

PS：根据你之前的 Issues 估计是这个问题了。

**Comment by SeasonPilot** [comment]
> 嗨，如果使用了同步助手的自动同步功能的话，需要使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装插件。
> 
> PS：根据你之前的 Issues 估计是这个问题了。

按照文档试了下，插件管理器 安装不上。简悦同步助手开着

**Comment by Kenshin** [comment]
不能安装不上，大概率是需要重启浏览器的地方你没有重启浏览器。

如果还是不行的话，就先手动关闭自动同步，在：选项页 → 共通 → 自动同步；然后重启浏览器；然后安装插件管理器，再通过插件管理器安装插件，安装后插件管理器会自动帮你开启自动同步，到时候重启浏览器就行。

**Comment by SeasonPilot** [comment]
> 不能安装不上，大概率是需要重启浏览器的地方你没有重启浏览器。
> 
> 如果还是不行的话，就先手动关闭自动同步，在：选项页 → 共通 → 自动同步；然后重启浏览器；然后安装插件管理器，再通过插件管理器安装插件，安装后插件管理器会自动帮你开启自动同步，到时候重启浏览器就行。

重启过了，连电脑都重启了

**Comment by Kenshin** [comment]
1. 关闭自动同步
2. 重启浏览器
3. 安装 https://simpread.ksria.cn/plugins/details/g60jwZEeqU
4. 重启浏览器
5. https://sspai.com/post/69972 右下角触发器会看到下面的截图

![image](https://user-images.githubusercontent.com/81074/212449376-ba11e6fd-3a8f-4b00-896c-5d4ed8453dab.png)

如果能的话，先配置它，确保好使后再开启自动同步并覆盖配置到本地。

**Comment by SeasonPilot** [comment]
> 1. 关闭自动同步
> 2. 重启浏览器
> 3. 安装 https://simpread.ksria.cn/plugins/details/g60jwZEeqU
> 4. 重启浏览器
> 5. https://sspai.com/post/69972 右下角触发器会看到下面的截图
> 
> ![image](https://user-images.githubusercontent.com/81074/212449376-ba11e6fd-3a8f-4b00-896c-5d4ed8453dab.png)
> 
> 如果能的话，先配置它，确保好使后再开启自动同步并覆盖配置到本地。

我看发的文档里面不是写要先安装 插件管理器？  我插件管理器安装不上。 这个辅助增强也安装不上

**Comment by Kenshin** [comment]
> 我看发的文档里面不是写要先安装 插件管理器？ 我插件管理器安装不上。 这个辅助增强也安装不上

文档是我写的，所以你听我的就行了  😂 

按照文档的写法当然没问题，但你遇到了问题，所以就没必要按照文档的方式了。

针对于你的方式 https://github.com/Kenshin/simpread/issues/5029#issuecomment-1382652450

**Comment by SeasonPilot** [comment]
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/61238101/212459025-18cee322-8933-4918-a91d-be1d91eb8eaa.png">

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/61238101/212459028-672ee591-8c43-4f0b-84a6-24608af690b8.png">

好像没有看到 触发器

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5029#issuecomment-1382674000

这个截图是安装了插件管理器后还是你使用了配置库方案后？

**Comment by SeasonPilot** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/61238101/212460169-3e986a6a-184b-4303-a8e4-9ec58355beb5.png">
没有安装 插件管理器 

配置库方案哪里可以看到是否有使用？

**Comment by Kenshin** [comment]
说乱套了 😂

我重新表述下我的思路：

1. https://github.com/Kenshin/simpread/issues/5029#issuecomment-1382674000 最后一个图是正确的，说明你关闭了**自动同步**。

2. 然后你可以安装 https://simpread.ksria.cn/plugins/details/g60jwZEeqU

3. 安装后重启浏览器。

4. 配置 Notion 与 Notion 辅助增强。

> 如果配置无误后（也就是说你测试成功后），并且你也使用了自动同步功能（只是临时关闭了它），看接下来的步骤：

1. 安装 插件管理器
2. 重启浏览器
3. 然后通过插件管理器安装 https://simpread.ksria.cn/plugins/details/tbjTx33iAA
4. 重启浏览器

这时，你会发现选项页 → 共通 → **自动同步功能被自动开启了**，说明安装成功了，以后的插件都使用插件管理器安装。

***

如果还是搞不定的话，把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5029

同时也最好能把 Notion 账户给我，我帮你配置。

**Comment by SeasonPilot** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/61238101/212464785-bcfd4140-77b5-4d7d-bc74-224ac6c22fe0.png">


试了下还是安装不上，配置文件已经发到你的邮箱了。麻烦帮忙看下吧

**Comment by Kenshin** [comment]
okay

我明天确认下。

**Comment by SeasonPilot** [comment]
> okay
> 
> 我明天确认下。

可以了吗？

**Comment by Kenshin** [comment]
1. 你的 UID 是错误的，下图就是你给我的配置文件，这个 UID 是测试用的，而不是你自己的 UID，使用这个 UID 当然会出现问题。

   <img width="438" alt="image" src="https://user-images.githubusercontent.com/81074/212799869-ea6159af-3ba7-4c41-98d0-9d44be7a58d8.png">

2. 你给我 Email 中只有 Notion 账户，并没有密码，我怎么登录 😂

3. 你给我的配置文件中也没有 https://simpread.ksria.cn/plugins/details/OpaogjT8KJ 这个插件...

**Comment by SeasonPilot** [comment]
> 

密码已发送

**Comment by Kenshin** [comment]
![](https://user-images.githubusercontent.com/81074/212799869-ea6159af-3ba7-4c41-98d0-9d44be7a58d8.png)

你的问题在于：

你使用了配置库方案，但是没有按照配置方案的要求修改... https://www.yuque.com/kenshin/simpread/odhlf2#e2eZE

![image](https://user-images.githubusercontent.com/81074/212802983-12419e1b-f425-4d05-a668-65b506a2f756.png)

把你的高级账户 UID 给我也发到邮箱里面。

**Comment by SeasonPilot** [comment]
> ![](https://user-images.githubusercontent.com/81074/212799869-ea6159af-3ba7-4c41-98d0-9d44be7a58d8.png)
> 
> 你的问题在于：
> 
> 你使用了配置库方案，但是没有按照配置方案的要求修改... https://www.yuque.com/kenshin/simpread/odhlf2#e2eZE
> 
> ![image](https://user-images.githubusercontent.com/81074/212802983-12419e1b-f425-4d05-a668-65b506a2f756.png)
> 
> 把你的高级账户 UID 给我也发到邮箱里面。

我好像还没有 UID，找了下好像没找到注册的地方呢..

**Comment by Kenshin** [comment]
> 我好像还没有 UID，找了下好像没找到注册的地方呢..

你不是高级账户？

**Comment by SeasonPilot** [comment]
> > 我好像还没有 UID，找了下好像没找到注册的地方呢..
> 
> 
> 
> 你不是高级账户？

还是我先兑换个码？
但是兑换码好像要填uid

**Comment by Kenshin** [comment]
> 兑换码好像要填uid

你可以先导出配置文件，然后在重新安装简悦，这时就会生成一个 UID...

另外，你使用的配置库均是高级账户功能... 😂

你现在遇到的大部分问题都是因为账户是 Demo 的缘故，配置库里面有详细说明，xxx-xxx 这个 Demo 使用几分钟后就会被锁，当然你也可能没有授权高级账户功能。

注意：**Notion 的导入功能基础账户就能使用**，**但配置库均是高级账户功能**，而你使用的就是配置库方案。

**Comment by SeasonPilot** [comment]
我有安装同步助手，我是保存同步助手的配置文件还是 网页上的配置文件呢？

**Comment by SeasonPilot** [comment]
> > 兑换码好像要填uid
> 
> 
> 
> 你可以先导出配置文件，然后在重新安装简悦，这时就会生成一个 UID...
> 
> 
> 
> 另外，你使用的配置库均是高级账户功能... 😂
> 
> 
> 
> 你现在遇到的大部分问题都是因为账户是 Demo 的缘故，配置库里面有详细说明，xxx-xxx 这个 Demo 使用几分钟后就会被锁，当然你也可能没有授权高级账户功能。
> 
> 
> 
> 注意：**Notion 的导入功能基础账户就能使用**，**但配置库均是高级账户功能**，而你使用的就是配置库方案。



我使用同步助手进行同步 需要高级账户吗？
目前不需要同步到notion中

**Comment by Kenshin** [comment]
> 我使用同步助手进行同步 需要高级账户吗？

当然...

**Comment by Kenshin** [comment]
https://simpread.pro/price

这是账户区别和购买地址

**Comment by SeasonPilot** [comment]
> > 兑换码好像要填uid
> 
> 
> 
> 你可以先导出配置文件，然后在重新安装简悦，这时就会生成一个 UID...
> 
> 
> 
> 另外，你使用的配置库均是高级账户功能... 😂
> 
> 
> 
> 你现在遇到的大部分问题都是因为账户是 Demo 的缘故，配置库里面有详细说明，xxx-xxx 这个 Demo 使用几分钟后就会被锁，当然你也可能没有授权高级账户功能。
> 
> 
> 
> 注意：**Notion 的导入功能基础账户就能使用**，**但配置库均是高级账户功能**，而你使用的就是配置库方案。

我有安装同步助手，我是保存同步助手的配置文件还是 网页上的配置文件呢？

**Comment by Kenshin** [comment]
> 我是保存同步助手的配置文件还是 网页上的配置文件呢？

不一定，你可以理解同步助手就一个基于本机的服务器，具体需要看你自己的设置。

同步助手的一些入门可以看 https://simpread.pro/docs/#/Sync

**Comment by SeasonPilot** [comment]
https://github.com/Kenshin/simpread/issues/5029#issuecomment-1382652450

**Comment by SeasonPilot** [comment]
> 
通过从配置文件导入插件 好像解决了问题
![image](https://user-images.githubusercontent.com/61238101/212823281-6a883bfb-0e02-4f7b-80b0-bf06b4adbab5.png)
![image](https://user-images.githubusercontent.com/61238101/212823331-a6bd02dd-0c0a-4a01-a71d-f78e76af558c.png)

**Comment by SeasonPilot** [comment]
notion 点击按键后 页面白屏
![image](https://user-images.githubusercontent.com/61238101/212824659-5b311bb2-3d51-4d20-ae2d-2e3aa4a92331.png)
![image](https://user-images.githubusercontent.com/61238101/212824785-0f07d5c2-f948-4ee2-9fc8-ecfb7fbb5c49.png)
