### ISSUE TITLE
Csdn的纯粹模式还是有问题

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#503]
![image](https://user-images.githubusercontent.com/10437293/58081101-0733ae00-7be7-11e9-89d6-52d9902a90a9.png)

出问题的url地址：https://blog.csdn.net/Xiong_IT/article/details/51394961
相应设置：
![image](https://user-images.githubusercontent.com/10437293/58081376-9214a880-7be7-11e9-91dc-1f41e13914c6.png)
![image](https://user-images.githubusercontent.com/10437293/58081423-a5277880-7be7-11e9-9039-c6cda7e93cf5.png)

**Comment by AriaLyy** [comment]
貌似重新安装 https://simpread.ksria.cn/plugins/details/klGUASLasg 这个插件就好了，😂

**Comment by Kenshin** [comment]
是的，需要重新安装即可。

我关闭此 issues 了~
