### ISSUE TITLE
notion 文档稍后读，生成的目录有缺失

### ISSUE THREAD

**Issue by SeasonPilot** [Kenshin/simpread#5030]
**请说明发生问题的环境**
MacOS+chrome

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Chrome **

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀
notion 文档稍后读，生成的目录有缺失

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
我没理解的你的问题，建议提供 URL 看看。
