### ISSUE TITLE
theinitium.com 站点文章进入阅读模式后，每次都会出现以下提示

### ISSUE THREAD

**Issue by xieft** [Kenshin/simpread#5031]
每次都要点一下“是的”，才能正常阅读，请帮忙解决这个问题，谢谢
![image](https://user-images.githubusercontent.com/35829258/211475663-edd43ca7-cba2-4237-8bda-37f59f4a9c65.png)

**Comment by Kenshin** [comment]
嗨，会考虑适配的。

**Comment by xieft** [comment]
> 嗨，会考虑适配的。

什么叫考虑，你这也太敷衍了吧？你们官方源不是这里都显示有这个吗？现在不能用还不赶紧修复吗？
![image](https://user-images.githubusercontent.com/35829258/211501021-c9f22483-81d3-430d-b87c-65f67a159118.png)

**Comment by xieft** [comment]
> 嗨，会考虑适配的。

本来不想骂你，居然还删评论，真不要脸！
