### ISSUE TITLE
notion稍后阅读，go代码块代码缩进异常

### ISSUE THREAD

**Issue by SeasonPilot** [Kenshin/simpread#5033]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Chrome**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.notion.so/test-fee5979b024745ebb527575058c5978f>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

notion稍后阅读，go代码块代码缩进异常

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/61238101/211491643-2894fd19-e219-4c91-b27c-75b025ec5165.png">

**Comment by Kenshin** [comment]
代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
