### ISSUE TITLE
知乎公式导出 Markdown 时公式重复（在阅读模式下的显示没问题）

### ISSUE THREAD

**Issue by wieniawski-lai** [Kenshin/simpread#5034]
- 操作系统 **Windows10**

- 浏览器版本 **Brave版本 1.48.108 Chromium: 109.0.5414.61**

- 简悦版本 **2.2.0**

- 发生问题的地址 https://zhuanlan.zhihu.com/p/594064002

**请描述你的问题**

稍后读公式显示不正确

**截图**
正常网页显示如下
![image](https://user-images.githubusercontent.com/70927596/211499173-38da8002-adb2-452f-9661-f71887316c19.png)

稍后读显示如下
![image](https://user-images.githubusercontent.com/70927596/211498915-b285c24c-b915-419e-b770-dc13e60864b7.png)

**Comment by Kenshin** [comment]
没有问题

<img width="682" alt="image" src="https://user-images.githubusercontent.com/81074/211503884-78f17c89-caf9-44ac-ba11-e9b190e0f7f6.png">

如何使用 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

但是在部分知乎页面上导出 Markdown 还是有点问题。

**Comment by wieniawski-lai** [comment]
是的,导出md的公式有问题
![image](https://user-images.githubusercontent.com/70927596/211512039-efaa306d-4624-4a26-9f7e-4846a2b46105.png)

**Comment by Kenshin** [comment]
okay 修复后我会通知你。

**Comment by wieniawski-lai** [comment]
今天我又碰到[知乎一篇文章](https://www.zhihu.com/question/473566915/answer/2838923748),

有些公式对,有些不对

![image](https://user-images.githubusercontent.com/70927596/211721573-b91c3bcd-5b7f-483b-af35-93f3f76e94cd.png)

**Comment by Kenshin** [comment]
okay 收到~

**Comment by wieniawski-lai** [comment]
还有一个问题是,Live Editor删除一些无用的东西之后,公式显示会不正常.

[这篇文章](https://www.zhihu.com/question/314549620/answer/707405638),在稍后读模式下是正常的
![image](https://user-images.githubusercontent.com/70927596/211737137-5bd92f6c-6b5e-41b9-b1eb-c4ddfc4c438d.png)

然后我使用Live Editor删除了二楼和三楼的内容,理论上是没有touch到一楼的文字,然后就不正常了
![image](https://user-images.githubusercontent.com/70927596/211737397-583d1659-4ab9-4ff0-8f60-eafcf89221e5.png)

事实上,只要进了Live Editor,不修改任何东西,再推出Live Editor,也会有上面一样的效果.整个公式就不正常了.

**Comment by wieniawski-lai** [comment]
事实上可以看到,进入了Live Editor模式之后,2和3的内容都不对了

比如原本2的内容是调和函数BLABLA

进入Live Editor之后,这部分内容变到了3

**Comment by Kenshin** [comment]
> Live Editor删除一些无用的东西之后,公式显示会不正常.

这是有可能，因为 Live Editor 在使用时会修改页面结构导致某些公式失败。

**Comment by wieniawski-lai** [comment]
> > Live Editor删除一些无用的东西之后,公式显示会不正常.
> 
> 这是有可能，因为 Live Editor 在使用时会修改页面结构导致某些公式失败。

嗯,我试过了,不修改也会出错

我没有想清楚原理为什么会出错

**Comment by Kenshin** [comment]
> 我试过了,不修改也会出错

试试 Live Editor 简易模式。

**Comment by lisontowind** [comment]
CSDN也有同样的问题

**Comment by Kenshin** [comment]
@lisontowind 

并不是每个 CSDN 和 知乎都有问题，所以给出 URL 方便我测试~

**Comment by lisontowind** [comment]
> @lisontowind
> 
> 并不是每个 CSDN 和 知乎都有问题，所以给出 URL 方便我测试~

https://blog.csdn.net/qq_28087491/article/details/126134823

**Comment by RealAidanJoe** [comment]
> @lisontowind
> 
> 并不是每个 CSDN 和 知乎都有问题，所以给出 URL 方便我测试~

https://zhuanlan.zhihu.com/p/580981620

**Comment by Kenshin** [comment]
@lisontowind

CSDN 的问题在于它使用了 Katex 方案，目前简悦仅支持 MathJAX 方案，这算是 Feature。

@RealAidanJoe 

你提供的知乎公式是 MathJAX 我这边导出后没有问题。

[计算理论导论（第三版）第四章：可判定性　第一节：可判定语言.txt](https://github.com/Kenshin/simpread/files/10531871/default.txt)

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
