### ISSUE TITLE
建议导出时将标题中的 ] 和 # 做替换处理

### ISSUE THREAD

**Issue by cyddgh** [Kenshin/simpread#5035]
当标题有]和 # 时，在ob中可能导致双链解析错误。
例如一下两个页面，使用开箱即用库剪藏： 
https://www.appinn.com/zimu-english-wechat-miniapp/
https://utgd.net/article/9388

涉及的简悦插件为： https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

![6ff5f685be1d1bf7de5a31bd412063b](https://user-images.githubusercontent.com/10444611/211537610-3d508ae8-44cf-4ddf-9eaa-477f23d3d300.png)

![8c4b34357e973e461120a7588d00e90](https://user-images.githubusercontent.com/10444611/211537626-ba6adaa6-ced7-4a2c-bf04-c97b5b188d49.png)

**Comment by Kenshin** [comment]
嗨，这个问题已修复。

- 如果**使用同步助手的自动同步**，则需要使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装

- 如果没有使用同步助手的自动同步，直接使用 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 升级。
