### ISSUE TITLE
导入到 Kindle 失败

### ISSUE THREAD

**Issue by junyujian** [Kenshin/simpread#5036]
补充：而且同时不能使用发送email，也是提示“导出失败，此功能为实验性功能。。。。”，这个该如何解决？ 好像更新1.1.4后就出现这个问题了。

**Comment by Kenshin** [comment]
你不用通过新建 issues 来描述你的问题.... 直接在这里回复就好。😂

PS：我稍晚些测试下再回复你，估计你个人的问题，因为仅有你自己报告了这个问题

**Comment by junyujian** [comment]
还真是我个人问题，彻底删除所有配置，重新设置后 发送kindle和邮件可以用了，谢谢您的及时回复，添麻烦了

**Comment by Kenshin** [comment]
我刚刚做完测试要回复你，这个功能是好使的，没想到就等来你的回复。

😂

没问题就好，我关闭这个 Issues 了。

**Comment by junyujian** [comment]
嗯嗯!麻烦了,

**Comment by Kenshin** [comment]
小事情 😃

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
