### ISSUE TITLE
设置了PDF高级打印方案, 想调整页边距  但是发现无效

### ISSUE THREAD

**Issue by zhuwenfa999** [Kenshin/simpread#5037]
我的设置如下:
![image](https://user-images.githubusercontent.com/73725434/211654218-0f6c691e-e195-4ff7-8011-25c8dbd6124e.png)
打印效果如下:
![image](https://user-images.githubusercontent.com/73725434/211654409-346cc657-1702-4a05-a836-d38249020857.png)
非个别html无效,是无论怎么改参数,打印出来页边距都是像上图一样.

**Comment by Kenshin** [comment]
我测试了下，是没问题的

<img width="863" alt="image" src="https://user-images.githubusercontent.com/81074/211712167-ec72bb10-3468-4ecd-8bc0-4fb01acb0349.png">

但我知道你遇到了什么问题。

版面宽度除了被你截图的参数影响外，还会受到界面的版面布局的影响。

<img width="1822" alt="image" src="https://user-images.githubusercontent.com/81074/211712268-f7709115-40fb-4d1c-a2fa-2f869d0aa3f3.png">

所以，你需要先按照上图修改，然后刷新当前页面再打印，就会得到我的一幅图了。

***

除此之外不改变版面布局的话，还有个办法，将此内容

```
body {
    margin: 20px 0!important;
}
```

放到下图所示的位置，然后保存。

<img width="607" alt="image" src="https://user-images.githubusercontent.com/81074/211712879-b102fddd-8d8e-4869-b5ef-672c3659e5b0.png">

备注：

- 20px → 上下边距（一般不用改）

- 0 → 左右边距，设置为0或其它 CSS 3 支持的值。
