### ISSUE TITLE
临时阅读模式会在简悦的服务器上保存多久？

### ISSUE THREAD

**Issue by fengyunkkx** [Kenshin/simpread#504]
临时阅读模式下会把文章内容保存到简悦的服务器上，想知道这篇文章多久会被清除呢？还是说永久留在服务器上？

**Comment by Kenshin** [comment]
当然不会是永久保存的，否则也不叫做 `临时阅读模式`

如果永久保存的话，会变成网盘的...  😂 
---

最长不会超过 5 个小时。

**Comment by fengyunkkx** [comment]
好的，感谢解答~ @Kenshin

**Comment by Kenshin** [comment]
没疑问的话，我关闭此 issues 了~
