### ISSUE TITLE
简悦助手更新1.1.4后，浏览器中打开稍后读无法使用。

### ISSUE THREAD

**Issue by SrSh-notme** [Kenshin/simpread#5040]
- 操作系统 ：win11 22h2

- 浏览器版本 ： 108.0.1462.76 (正式版本) (64 位)

- 简悦版本：2.2.0.520

简悦助手从1.1.3（64位）更新至1.14（64位）后，浏览器打开稍后读页面元素缺失；且在浏览器中打开稍后读速度缓慢，重新使用1.1.3的简悦助手后一切正常。

更新方法：在简悦助手的原文件夹完全删除简悦助手1.1.3的文件后，用简悦助手1.1.4的文件解压替代。

![Snipaste_2023-01-11_12-24-45](https://user-images.githubusercontent.com/48594308/211719650-fda5a83d-78fb-4111-b0a4-25edcf167a79.png)

BTW，简悦极速版更新后真的很不错！！

**Comment by Kenshin** [comment]
> 浏览器打开稍后读页面元素缺失；且在浏览器中打开稍后读速度缓慢，重新使用1.1.3的简悦助手后一切正常。

嗨，这个问题跟同步助手无关 😂

PS：谢谢喜欢极速版。

***

你可以试试是否正常访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css 

无法访问的话，需要点「魔法」方式。

**Comment by SrSh-notme** [comment]
> > 浏览器打开稍后读页面元素缺失；且在浏览器中打开稍后读速度缓慢，重新使用1.1.3的简悦助手后一切正常。
> 
> 嗨，这个问题跟同步助手无关 😂
> 
> PS：谢谢喜欢极速版。
> 
> 你可以试试是否正常访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css
> 
> 无法访问的话，需要点「魔法」方式。

我看是可以访问的
![Snipaste_2023-01-11_12-52-46](https://user-images.githubusercontent.com/48594308/211720729-c9c35fce-999a-45b3-809d-808cafd31a5b.png)

**Comment by SrSh-notme** [comment]
关键用回1.1.3后一切正常，很奇特。

**Comment by Kenshin** [comment]
> 关键用回1.1.3后一切正常，很奇特。

如果你是指 

![Snipaste_2023-01-11_12-24-45](https://user-images.githubusercontent.com/48594308/211719650-fda5a83d-78fb-4111-b0a4-25edcf167a79.png)

这个截图的话，是完全没有关系的 😂 

截图中是扩展端的功能，不使用同步助手也可以正常使用。

> 我看是可以访问的 ![Snipaste_2023-01-11_12-52-46](https://user-images.githubusercontent.com/48594308/211720729-c9c35fce-999a-45b3-809d-808cafd31a5b.png)

那就是你浏览器缓存的问题，稍晚或者明天再看看。
