### ISSUE TITLE
自动同步无法开启

### ISSUE THREAD

**Issue by wuwu119** [Kenshin/simpread#5041]
> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Apple M1 13.0.1 (22A400)**

- 浏览器版本 **Chrome 108.0.5359.124（正式版本） (arm64)**

- 简悦版本 **2.2.0**
- 同步助手版本*1.1.4*

- 发生问题的地址(chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#about)
![image](https://user-images.githubusercontent.com/4300766/211725875-504e67e3-d1eb-478e-af5b-50d8948a495e.png)
在配置logseq同步插件的时候，开启自动同步失败，报上图错误。前面的配置已经做完了。
升级了同步助手也还是不行。

**Comment by Kenshin** [comment]
解决了这个问题？
