### ISSUE TITLE
notion List 转换错误

### ISSUE THREAD

**Issue by SeasonPilot** [Kenshin/simpread#5043]
请说明发生问题的环境

简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

操作系统 MacOS

浏览器版本 Chrome 版本 108.0.5359.124（正式版本） (x86_64)

简悦版本 2.0.0

发生问题的地址 < https://www.notion.so/fee5979b024745ebb527575058c5978f >
请描述你的问题

请使用可以 准确定位到错误 的语句来告诉我。😀

截图

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/61238101/211816944-4adf422e-4bb3-4bb0-8457-dd477796f035.png)

**Comment by Kenshin** [comment]
嗨，这个暂时没法转换，我直接关闭这个 Issues ~

有任何适配问题，直接发到 https://github.com/Kenshin/simpread/issues/5032 里面就好。

PS：我今天看下，如果不是太麻烦，可以马上修复，否则就本周。

**Comment by SeasonPilot** [comment]
> 嗨，这个暂时没法转换，我直接关闭这个 Issues ~
> 
> 有任何适配问题，直接发到 #5032 里面就好。
> 
> PS：我今天看下，如果不是太麻烦，可以马上修复，否则就本周。

你好，请问已经修复了吗？

**Comment by SeasonPilot** [comment]
> 嗨，这个暂时没法转换，我直接关闭这个 Issues ~
> 
> 有任何适配问题，直接发到 #5032 里面就好。
> 
> PS：我今天看下，如果不是太麻烦，可以马上修复，否则就本周。

你好，请问已经修复了吗？

**Comment by Kenshin** [comment]
😂 我忘记了，这阵子在忙其它的功能...

然后我看了下，因为 Notion 并不是你理解的正常的 HTML 结构，所以这里暂时没有太好的办法解决。

简单的说，无序列表和有序列表，在 Notion 没有太好的办法区分，所以之前的做法是统一它们为无序列表。
