### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by xylen17** [Kenshin/simpread#5045]
发生问题的地址: <https://pan.baidu.com/disk/pdfview?path=%2F%E6%89%80%E6%9C%89%E6%83%85%E6%84%9F%E5%A5%97%E8%B7%AF%E7%9A%84%E6%9C%AC%E8%B4%A8%E7%89%B9%E5%BE%81%20%E6%96%87%E5%AD%97%E7%A8%BF.pdf

**Comment by Kenshin** [comment]
我没法打开这个页面，但一般来说，这类页面是不可以被适配的，我直接关闭这个 Issues 了。
