### ISSUE TITLE
导航目录无法点击跳转，更新插件后仍然无效

### ISSUE THREAD

**Issue by chiperman** [Kenshin/simpread#505]
还是那个问题，安装最新插件后，仍然在这个网页无法正常跳转https://www.cnblogs.com/PyLearn/p/7624023.html

**Comment by Kenshin** [comment]
请重新（或删除）安装 https://simpread.ksria.cn/plugins/details/UsayAKSuwe 

即可解决，我刚刚测试过，没有问题。

**Comment by Kenshin** [comment]
更新了下使用的视频，你是指左侧目录的调转吧？

![2019-05-21_18-19-53](https://user-images.githubusercontent.com/81074/58088379-26d1d300-7bf5-11e9-859c-7f9ce63aa46a.gif)

**Comment by chiperman** [comment]
![Snipaste_2019-05-21_18-22-03](https://user-images.githubusercontent.com/34889778/58088485-5b458f00-7bf5-11e9-85e4-e08dfce51fce.png)
我打开还是 这样，重新安装几次了，是不是我哪里设置有问题。

**Comment by Kenshin** [comment]
这个提示应该是旧版本造成的。

你把全部的 tab 都关闭，然后删除这个插件。（实在不行，确保删除完后，重启浏览器）

再重新安装，试试？ 如果还不行的话，把你的插件截图给我看看。

**Comment by chiperman** [comment]
![1](https://user-images.githubusercontent.com/34889778/58090933-ec6b3480-7bfa-11e9-8ea7-2098bade3937.png)
点击更新按钮显示已经是最新的版本了。

**Comment by Kenshin** [comment]
安装之前的提示步骤安装了吗？

**Comment by Kenshin** [comment]
另外，试试其它页面？还是不行的话，删除扩展再重新安装它（别忘记导出配置）

**Comment by chiperman** [comment]
我刚才重装后，完全使用默认配置，一开始可以，等我下载好目录插件后反而失效，我再一次重装后目前没有问题了。感觉不太稳定。

**Comment by Kenshin** [comment]
emmm...

「也许」知道什么问题了… 你的系统配置是什么？

可能插件的优化时间有些问题（疑似）

**Comment by chiperman** [comment]
不太明白你指的系统配置是哪方面的。

**Comment by Kenshin** [comment]
有可能是系统性能不好导致导致的（只是怀疑…）

另外，在观察下，看看还有没有问题了。

**Comment by chiperman** [comment]
前几天还行，刚才突然又不行了，可能我电脑有问题吧><

**Comment by Kenshin** [comment]
> 前几天还行，刚才突然又不行了，可能我电脑有问题吧><
> 重装插件还是不行。

任意网页都不好使？还是某个？

**Comment by chiperman** [comment]
好几个都不行。

**Comment by Kenshin** [comment]
哪好几个… 给我URL

**Comment by chiperman** [comment]
https://www.cnblogs.com/PyLearn/p/7624023.html#sr-toc-10
https://zhuanlan.zhihu.com/p/29989157#sr-toc-0
https://zhuanlan.zhihu.com/p/26401052#sr-toc-2

**Comment by Kenshin** [comment]
你试试 User Scripts 版，看看有没有这个问题？

**Comment by chiperman** [comment]
不太清楚你说的 user scripts 指的是什么。

**Comment by Kenshin** [comment]
> https://www.cnblogs.com/PyLearn/p/7624023.html#sr-toc-10
> https://zhuanlan.zhihu.com/p/29989157#sr-toc-0
> https://zhuanlan.zhihu.com/p/26401052#sr-toc-2

真是够奇怪... 下图是你提供的三个网址，我这边确实可以跳转。

![2019-05-27_10-24-09](https://user-images.githubusercontent.com/81074/58391759-bf3edc00-8069-11e9-8003-a8a8facf30e0.gif)

> 不太清楚你说的 user scripts 指的是什么。

我的意思是：你试试安装 [User Scripts 版](http://ksria.com/simpread/#lite)，看看是否也有这个问题。
如果你不了解 User Scripts 就不用试了。

***

我这边没问题，而你那边有错误，我只能猜测：由系统配置不高引起的 Bug

**Comment by chiperman** [comment]
![Snipaste_2019-05-27_12-39-46](https://user-images.githubusercontent.com/34889778/58395836-adb2ff80-807c-11e9-9a53-746c4df1e7a6.png)
我在想是不是和其他插件冲突，因为他会提示“已经启用控制栏面板，所以无法启用此功能”

**Comment by Kenshin** [comment]
晕...
你的配置也不低啊...

你在隐身模式下（确保只运行简悦，无其它扩展），安装之前跟你说的插件 https://simpread.ksria.cn/plugins/details/UsayAKSuwe

试试？

**Comment by chiperman** [comment]
不行，可能还是和我的电脑某些配置有关。应该是个例，还是麻烦你了。
谢谢你了其他方面都超级好用。

**Comment by Kenshin** [comment]
@chiperman 

没事，主要是我也不清楚为什么... 等我更新版本后，看看能否解决你这个问题吧~

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

优化了 TOC 的各种问题，我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
