### ISSUE TITLE
关于导入 Obsidian 的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5052]
# 看图说话

![1](https://user-images.githubusercontent.com/27400703/212267778-a7c0ee38-062b-4d7a-96fa-0fb207bd4e4b.png)
![2](https://user-images.githubusercontent.com/27400703/212267816-facedff7-55ed-49be-978d-aaacfd98ac26.png)
![3](https://user-images.githubusercontent.com/27400703/212267850-92e72fdf-d29b-4654-ab26-426010947d01.png)
![4](https://user-images.githubusercontent.com/27400703/212267867-8f96d9a1-8515-4044-9293-00c1aae5d352.png)
4张图 一个原网站 

1. obsidian插件导入
2.其他chrome插件导入
3.插件生成的markdown剪贴板贴入

可以看出明显的格式区别
而且导入操作复杂 要打开阅读模式 找3个小点 定位到插件按钮~~~~~~
2的其他Chrome插件就是点开 点下载

_Originally posted by @renlianfu in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-4675485_

**Comment by Kenshin** [comment]
@renlianfu

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 操作复杂 要打开阅读模式 找3个小点 定位到插件按钮

你可以使用 https://simpread.ksria.cn/plugins/details/rsd4UIcDKY

> 可以看出明显的格式区别

前两个图里面 Metadata 功能简悦也有，只是默认没有启动。

> 操作问题

不能这么比较。

***

综上，总结下：

1. 简悦不是专门为 Obsidian 设计的剪藏工具。
2. 其它扩展没有办法实现较完美的正文获取方式。
3. 简悦可以对标注的导入公式。
4. 其它扩展也没有 https://github.com/Kenshin/simpread/discussions?discussions_q=label%3Aobsidian 这么多更实际的用法。

**Comment by Kenshin** [comment]
再随便举个例子，

简悦可以识别 https://twitter.com/ruanyf/status/1613701029551538178 并导入为下图所示效果。

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/81074/212279304-15692a8d-6cfe-4085-afb1-4bbe9a50a57e.png">

**Comment by Kenshin** [comment]
提示：**你第三附图并不是使用导入到 Obsidian 插件**，下面才是使用这个插件后的效果。

最后截一个你上面提到比较图使用的图 https://sspai.com/post/71576

<img width="1828" alt="image" src="https://user-images.githubusercontent.com/81074/212299860-cdab8e7c-f8f8-452d-9196-79d2a31cd350.png">

以及标注导入效果

<img width="651" alt="image" src="https://user-images.githubusercontent.com/81074/212300198-78461438-4d08-4b41-a411-3bee39a02d3f.png">

甚至于在这个导入到 Obsidain 插件中[直接集成了 assets 功能](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604)，可以将图片保存到本地。

更不用说在 Obsidian 集成标注功能了，[B 站视频](https://www.bilibili.com/video/BV1EB4y1a75B)

***

这些专业功能对部分用户来说有点难，所以简悦也提供了直接使用的配置库方案 https://www.yuque.com/kenshin/simpread/psugef

***

虽然这么比较也不太恰当，**简悦导入到 Obsidian 不是一个简单的剪藏工具，而是给 Obsidian 用户一套真正的使用方法。**

**Comment by renlianfu** [comment]
应该是我表述不清楚 YAML区不是我想强调的点
4是原网页 1和3都是简悦的导入 
1是通过简约简悦obsidian插件导入
3是简悦直接复制markdown到剪贴板贴入的效果
2是通过Chrome 的Obsidian Web插件导入
1图简悦的插件导入 原文中的引用段落格式是缺失的
3是简悦复制的markdown导入 引用段落还在
---
使用上 简悦需要先进入阅读界面 才可以执行下一步操作 导出 复制markdown这些
Chrome 的Obsidian Web插件可以在网页直接导出 
![image](https://user-images.githubusercontent.com/27400703/212460247-56d59a05-81d6-4565-b223-3a4c124a56d6.png)
在比如MarkDownload - Markdown Web Clipper也是类似操作 
![image](https://user-images.githubusercontent.com/27400703/212460314-83829875-cf55-4653-a91e-da1b7a81d420.png)
---
我在想 如果只是剪藏的话 能不能直接把功能做在网页 
而像是标注这样高级需求 readITlater面板中使用 
或者2种需求可以切换 在第一页显示剪藏or进去阅读界面批注后再剪藏
---

**Comment by Kenshin** [comment]
还是我之前说的

> 简悦不是一个剪藏工具。

因为 **简悦会获得并优化正文，所以才比其它扩展具有更完美的正文能力**；同时简悦一直是 **基于阅读模式的信息管理工具**。

这是产品形态决定的，而不是技术。

***

非要说的话，简悦支持各种快捷键操作，可以利用一些 Quicker 制作的自动化工具：

> 实现 （通过快捷键） → 自动进入阅读模式 → （通过快捷键）自动导入到 Obsidian → （通过快捷键）自动退出阅读模式。
