### ISSUE TITLE
怎么在 ob中打开 对应的简悦页面

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5053]
视频教程是这样的
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/38575961/212369357-ffd1fb4a-c3d0-460f-aef3-1f9cbf3a393f.png">

但是我自己操作 点进那个按钮
却是这样的
<img width="829" alt="image" src="https://user-images.githubusercontent.com/38575961/212369528-93740d0b-9279-400d-82e5-17dcfd911522.png">

**Comment by Kenshin** [comment]
嗨

如果是新用户的话或没有任何稍后读数据的话，建议直接使用 https://www.yuque.com/kenshin/simpread/wq35mh 方案。

你遇到的问题因为没有给出出现问题时的截图，所以我没法判断。

不过，一般来说都是因为没有配置 https://www.yuque.com/kenshin/simpread/wkswh7 造成的。
