### ISSUE TITLE
开机时出现报错的弹框

### ISSUE THREAD

**Issue by sw6633** [Kenshin/simpread#5054]
没法上传截图。之前我换过一次同步助手的文件夹，不知道是否有关。同步助手目前能正常用，就是开机时会多这个弹框。

**Comment by Kenshin** [comment]
> 之前我换过一次同步助手的文件夹，不知道是否有关

确保你运行的新文件夹的同步助手。

> 没法上传截图。

没法截图的话，至少也要简单说下出错的内容吧 😂

**Comment by sw6633** [comment]
> 
报错内容是这个[![](https://s2.loli.net/2023/01/15/HRNEmgJPCAQxG9K.png)](url)

**Comment by Kenshin** [comment]
emmm 你隐藏掉的路径是同步助手运行的目录吗？

**Comment by sw6633** [comment]
> emmm 你隐藏掉的路径是同步助手运行的目录吗？

是的，是原来那个放同步助手的目录。

**Comment by Kenshin** [comment]
> 是原来那个放同步助手的目录。

我记得你不是说过更换过同步助手的目录吗？新的目录也是这个吗？

PS：最新版的同步助手是 1.1.4

**Comment by sw6633** [comment]
时隔近两年，出现同样的问题，但这次我知道原因和解决办法了。

原因：
①误删同步助手文件夹→②部分文件被同步助手打开所以没能删干净→③设置了开机自启→④开机时由于文件损坏无法自启导致截图中的报错→⑤文件夹删不掉（理由同②，然后开始死循环）。

解决方法：
重新下载同步助手（放在别的文件夹里），打开后关闭“自启动”，这样旧文件夹就开始删干净了，不会报错了。
【当然不删旧文件夹也不影响新下载的同步助手的使用，就是每次开机都报错+文件夹删不掉看着难受】

**Comment by Kenshin** [comment]
谢谢自救成功 👍 😂

我会把你的解决方案放到知识库里面~

> ①误删同步助手文件夹

在 Windows 中同步助手的文件夹在哪里？为什么会被误删？😂

**Comment by sw6633** [comment]
> 谢谢自救成功 👍 😂
> 
> 我会把你的解决方案放到知识库里面~
> 
> > ①误删同步助手文件夹
> 
> 在 Windows 中同步助手的文件夹在哪里？为什么会被误删？😂

文件夹的位置是用户自己决定的。误删应该是一次性清理的文件夹比较多，没注意把同步助手也给选进去了，然后又不巧又开了自启动，正常应该不会这么多巧合凑一起

**Comment by Kenshin** [comment]
> 文件夹的位置是用户自己决定的

你是说自己设置的同步文件夹？而不是同步助手的安装文件夹吧？

如果是的话，确实太巧合了  😌

**Comment by sw6633** [comment]
> > 文件夹的位置是用户自己决定的
> 
> 你是说自己设置的同步文件夹？而不是同步助手的安装文件夹吧？
> 
> 如果是的话，确实太巧合了 😌

不，就是同步助手的安装文件夹。我没有设置多端同步

**Comment by Kenshin** [comment]
> 就是同步助手的安装文件夹

在安装同步助手时应该自定义选择路径的方式？直接解压缩到某个文件夹就可以直接使用。
