### ISSUE TITLE
ob不生成源md，只有@annote

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5055]
![image](https://user-images.githubusercontent.com/38575961/212449542-ca2ee911-9e96-48b3-8ebd-f6e50ed50ca2.png)

**Comment by Kenshin** [comment]
嗨，你的问题大部分都是使用问题，所以在一个 Issues 里面讨论就行了，我集中到了 https://github.com/Kenshin/simpread/issues/5056
