### ISSUE TITLE
多个浏览器 使用简悦场景，在ob中点击 源链接，会跳到不匹配的文章里去

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5056]
多个浏览器 使用简悦场景，会有以下两个问题。请问如何解决
1.不同的文章 会有一样的序号

![image](https://user-images.githubusercontent.com/38575961/212449895-7301bf29-abeb-43f9-a766-74e23581802b.png)

2.在ob中点击 源链接，会跳到不匹配的文章里去
比如我点击第5篇 标注里的原文链接  会跳到第八篇文章

**Comment by Kenshin** [comment]
ob不生成源md，只有@annote


![image](https://user-images.githubusercontent.com/38575961/212449542-ca2ee911-9e96-48b3-8ebd-f6e50ed50ca2.png)

**Comment by Kenshin** [comment]
> 不同的文章 会有一样的序号

因为你没有最好自动同步造成的。

简单的说，需要安装下面的顺序：

1. 坚果云（或类似网盘）
2. 同步助手
3. 浏览器

这样你的数据才会更新到你的新设备上。

> 在ob中点击 源链接，会跳到不匹配的文章里去

应该还是 https://www.yuque.com/kenshin/simpread/wkswh7 没有配置好。

> https://github.com/Kenshin/simpread/issues/5056#issuecomment-1382663234

同样没有配置好 😂

***

建议严格按照 https://www.yuque.com/kenshin/simpread/wq35mh 的方式，在没有弄懂简悦机制的前提下，先不要随意更改教程中的路径设定逻辑。

等你熟悉了之后可以随意更改这些路径。

**Comment by enron2014** [comment]
> > 不同的文章 会有一样的序号
> 
> 因为你没有最好自动同步造成的。
> 
> 简单的说，需要安装下面的顺序：
> 
> 1. 坚果云（或类似网盘）
> 2. 同步助手
> 3. 浏览器
> 
> 这样你的数据才会更新到你的新设备上。
> 
> > 在ob中点击 源链接，会跳到不匹配的文章里去
> 
> 应该还是 https://www.yuque.com/kenshin/simpread/wkswh7 没有配置好。
> 
> > [#5056 (comment)](https://github.com/Kenshin/simpread/issues/5056#issuecomment-1382663234)
> 
> 同样没有配置好 😂
> 
> 建议严格按照 https://www.yuque.com/kenshin/simpread/wq35mh 的方式，在没有弄懂简悦机制的前提下，先不要随意更改教程中的路径设定逻辑。
> 
> 等你熟悉了之后可以随意更改这些路径。

------------------不同的文章 会有一样的序号

我没有多设备 也没有使用坚果云。我是 一台电脑 多个浏览器。

**Comment by Kenshin** [comment]
> 我没有多设备 也没有使用坚果云。我是 一台电脑 多个浏览器。

没有使用同步助手的自动同步功能？
