### ISSUE TITLE
阅读模式CSDN代码块问题

### ISSUE THREAD

**Issue by xmhwws** [Kenshin/simpread#5057]
链接：https://blog.csdn.net/qq_24531461/article/details/77624255

原网站：

![image](https://user-images.githubusercontent.com/42903751/212459169-bbc3aa1c-0a92-4a63-a18c-b8f136a0b060.png)

阅读模式：

![image](https://user-images.githubusercontent.com/42903751/212459184-33fa1f7b-c02b-40a5-8e9b-fca8fa50c9dd.png)

代码块问题太频繁了，知识星球代码块问题至今还未修复

**Comment by Kenshin** [comment]
代码段的问题比较麻烦，因为很多网站的高亮规则都不统一，很难找到共通方式。

我会集中在 #500 并关闭此 Issues 修复后会通知你~
