### ISSUE TITLE
无法绑定，一直显示格式错误

### ISSUE THREAD

**Issue by AC-LGTM** [Kenshin/simpread#5058]
![屏幕截图 2023-01-14 221741](https://user-images.githubusercontent.com/122683150/212478389-0463e76b-abb5-44e4-9920-dcf86fc19746.png)

**Comment by Kenshin** [comment]
使用 https://simpread.pro/code 兑换后得到的 License 是 `xxxx-xxxxxx-xxxxxx-xxxx` 这样的格式。

**Comment by Kenshin** [comment]
如果还是有问题的话，请提供你在腾讯问卷中填写的 Email 地址。
