### ISSUE TITLE
在网页端查看“阅读列表”中文章，引用块文本字体颜色太暗，影响阅读

### ISSUE THREAD

**Issue by hxylonghui2017** [Kenshin/simpread#5060]
手机端，查看“阅读列表”中文章，css样式会保持下载时的效果。
网页端，查看“阅读列表”中文章，会使用一个默认css样式，该样式中引用块文本字体颜色太暗。
![image](https://user-images.githubusercontent.com/31501299/212492099-d8508265-0c04-42cf-8029-6a1c738b7cdd.png)

**Comment by Kenshin** [comment]
> 网页端，查看“阅读列表”中文章，会使用一个默认css样式，该样式中引用块文本字体颜色太暗。

这算是正常情况（或已知 Bug），在安装简悦的网页就会出现如图所示的情况，因为简悦的样式互相干扰造成的，暂时没有太好的解决方案。

如何避免：

1. 在没有安装简悦的浏览器就可正常使用。
2. 如果本机也使用了简悦以及（同步助手）的话，可以直接使用 [稍后读 · 极速版](https://simpread.pro/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB%E6%9E%81%E9%80%9F%E7%89%88) 直接访问 http://localhost:7026/unread/ 查看本地快照。
