### ISSUE TITLE
简悦应该以视频教程为主！！因为视频是效率最高的（有音频解说、直观的画面对照）。

### ISSUE THREAD

**Issue by photoe** [Kenshin/simpread#5063]
文字版教程效率太低，应该以视频教程为主。（要么按作者认为的最简单的方法、要么就照着文字版一步一步解释和操作也行呀）。
        交流传播信息过程，视频是效率最高的（有音频解说、直观的画面）。文字文档大部分是说不清楚的、也不可能说清楚每一步。
         一个配置方案按视频教程可能10多分钟就跟着学会了！！！        但是看文字文档几天也不一一定学会（遇到有歧义 或者没写请的地方需要来回问、一来一会浪费大部分时间）。

        对于普通用户（不是计算机专业、不是程序员）来说，简悦的基础、高级操作门槛依旧很高。蜀道难、难于上青天。作者可以在电报群投票，大部分用户开始的时候一般都会几天学不会、然后弃坑几个月、半年、甚至以后也不愿意用这么难的工具了。。。
        
        大胆断言预测一下，如果有视频教程，用户数翻几倍都是最低的。广为传唱度和口碑会更加普及。

**Comment by Kenshin** [comment]
@photoe

嗨，谢谢反馈，为了方便搜索和集中管理。我把你的内容放到了 https://github.com/Kenshin/simpread/issues/4848#issuecomment-1383557126

当你收到这封邮件的时候，我已删除了这个 Issues 

😄
