### ISSUE TITLE
logseq+简悦。  侧边栏一直无法拖出。

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5064]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/38575961/212709524-88f48f41-c44a-4c7a-a4cf-ab50fed064c8.png">

不知道是简悦的问题还是logseq的问题

**Comment by Kenshin** [comment]
把右侧面板关闭，通过 Logseq 的面板打开试试。

PS：看起来好像你的右侧面板上面的部分内容超出可视范围了。

**Comment by wlioi** [comment]
![20230125_070158_791](https://user-images.githubusercontent.com/53043495/214548349-1faf3679-bf2e-46a6-954b-80c04a8a64f6.png)
@Kenshin 我也是
