### ISSUE TITLE
简悦+logseq 在右侧增加高亮标注 但是左侧 不增加对应的笔记 

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5065]
简悦+logseq 在logseq右侧增加高亮标注 但是左侧 不增加对应的笔记 

但是 如果是在浏览器里增加高亮标注，那么logseq左侧会立即生成。

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/38575961/212710426-572b256a-b724-44dd-aaa3-afa188c5439d.png">

**Comment by Kenshin** [comment]
emmm

> 如果是在浏览器里增加高亮标注，那么logseq左侧会立即生成。

把你的增强导出路径给我看下，或者确定下你的同步助手下的增强导出路径是否在 Logseq 位置？

> 在logseq右侧增加高亮标注 但是左侧 不增加对应的笔记

看看你的截图右侧面板左上角应该有个 Icon 也就是可以设置 Logseq，你的截图看不到。

**Comment by enron2014** [comment]
这是我的增强导出路径

![image](https://user-images.githubusercontent.com/38575961/212806203-6fd28d7e-4b4c-44c9-b57a-a1aa94d6e7c5.png)

**Comment by enron2014** [comment]
> emmm
> 
> > 如果是在浏览器里增加高亮标注，那么 logseq 左侧会立即生成。
> 
> 把你的增强导出路径给我看下，或者确定下你的同步助手下的增强导出路径是否在 Logseq 位置？
> 
> > 在 logseq 右侧增加高亮标注 但是左侧 不增加对应的笔记
> 
> 看看你的截图右侧面板左上角应该有个 Icon 也就是可以设置 Logseq，你的截图看不到。

这是我的增强导出路径
![image](https://user-images.githubusercontent.com/38575961/212806266-95f02578-4bd7-4ff3-8c97-25e6588834c8.png)

**Comment by enron2014** [comment]
> emmm
> 
> > 如果是在浏览器里增加高亮标注，那么 logseq 左侧会立即生成。
> 
> 把你的增强导出路径给我看下，或者确定下你的同步助手下的增强导出路径是否在 Logseq 位置？
> 
> > 在 logseq 右侧增加高亮标注 但是左侧 不增加对应的笔记
> 
> 看看你的截图右侧面板左上角应该有个 Icon 也就是可以设置 Logseq，你的截图看不到。

这是我的logseq设置
![image](https://user-images.githubusercontent.com/38575961/212806578-594233d9-6858-4929-86aa-c18bba93957a.png)

**Comment by enron2014** [comment]
> emmm
> 
> > 如果是在浏览器里增加高亮标注，那么 logseq 左侧会立即生成。
> 
> 把你的增强导出路径给我看下，或者确定下你的同步助手下的增强导出路径是否在 Logseq 位置？
> 
> > 在 logseq 右侧增加高亮标注 但是左侧 不增加对应的笔记
> 
> 看看你的截图右侧面板左上角应该有个 Icon 也就是可以设置 Logseq，你的截图看不到。

另外还想反馈一个问题 
为啥这个栏 有时候完整显示  

![image](https://user-images.githubusercontent.com/38575961/212806768-62633cfc-8fc8-4c9c-b925-f7743193c1d3.png)
有时候又是显示一半（我已经划到最上方）
![image](https://user-images.githubusercontent.com/38575961/212806833-9e94dd7b-ae5d-48af-a7e5-ed9b55bc4bfe.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384801997

这个好像是 Logseq 的锅，因为通过锚点点过去后，Logseq 的 `y` 轴会是负数，所以就造成了这种情况，目前我也没有找到解决方案 😂

> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384799608

当通过网页标注时，会更新到这个增强导出的目录中，所以才会通过 Logseq 看到。

所以，当在 Logseq 右侧标注时也会更新到增强导出的目录中，你可以看下这个 `.md` 的文件更新了吗？

> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384800871

emmm 那说明你的右侧内容是正确的...

***

综上，你的配置都没有什么问题。

是否可以稳定复现这个问题？或者重启 Logseq 与同步助手后再确认下。

**Comment by enron2014** [comment]
我试了下  我在logseq标注的时候  只有我的这个路径的文件发生了更改。  我的配置是不是还是有问题
![image](https://user-images.githubusercontent.com/38575961/212821231-98c1638c-53ac-4cf5-ae37-99484750ab62.png)

**Comment by enron2014** [comment]
> > [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384801997)
> 
> 这个好像是 Logseq 的锅，因为通过锚点点过去后，Logseq 的 `y` 轴会是负数，所以就造成了这种情况，目前我也没有找到解决方案 😂
> 
> > [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384799608)
> 
> 当通过网页标注时，会更新到这个增强导出的目录中，所以才会通过 Logseq 看到。
> 
> 所以，当在 Logseq 右侧标注时也会更新到增强导出的目录中，你可以看下这个 `.md` 的文件更新了吗？
> 
> > [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384800871)
> 
> emmm 那说明你的右侧内容是正确的...
> 
> 综上，你的配置都没有什么问题。
> 
> 是否可以稳定复现这个问题？或者重启 Logseq 与同步助手后再确认下。

我如果在网页版 增加标注的时候  这几个路径下的文件发生了改变
![image](https://user-images.githubusercontent.com/38575961/212821776-71fa84b1-4c98-44b0-8f33-b427a0219148.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384872162

这是正确的，output 是你的快照文件夹，跟 https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384799608 增强导出文件夹无关。

增强导出对应的路径内容应该会反映在 https://github.com/Kenshin/simpread/issues/5065#issue-1535092401 左侧，所以你看看下，左侧这个文件是否是在增强导出对应的目录下。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384874868

看起来也是对的。第三个文件如果更新了，并通过 Logseq 打开它，就能看到新的。

**Comment by enron2014** [comment]
> > [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384872162)
> 
> 这是正确的，output 是你的快照文件夹，跟 [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384799608) 增强导出文件夹无关。
> 
> 增强导出对应的路径内容应该会反映在 [#5065 (comment)](https://github.com/Kenshin/simpread/issues/5065#issue-1535092401) 左侧，所以你看看下，左侧这个文件是否是在增强导出对应的目录下。

左侧的文件在 pages目录下。 但是  如果右侧增加标注 并不会更新这个 md文件。 但是网页增加标注 会更新。 感觉还是有问题呀

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1385062131

没有遇到过，看起来像是 Logseq 的问题... Logseq 小问题还是挺多的 😂

> https://github.com/Kenshin/simpread/issues/5065#issuecomment-1385070435

这个问题有点奇怪，你试试把 DevTools 打开（按下图所示）

<img width="447" alt="image" src="https://user-images.githubusercontent.com/81074/212874606-1857e4a0-9d52-4ed8-b878-9a32af2de6cb.png">

然后按这个图 https://github.com/Kenshin/simpread/issues/5065#issuecomment-1384800871 点 **测试** 看看

![image](https://user-images.githubusercontent.com/81074/212876238-99147550-e9a1-45ca-8f03-e157abd8a0e1.png)

这个界面右侧有内容吗？以及你的（下图）有什么报错？

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/81074/212876324-762cf726-c8d0-4755-8bae-59c669745469.png">
