### ISSUE TITLE
同一台设备可以用两个不同版本的同步助手，两个浏览器，分别配合ob和logseq吗

### ISSUE THREAD

**Issue by enron2014** [Kenshin/simpread#5066]
同一台设备可以用两个不同版本的同步助手，两个浏览器，分别配合ob和logseq吗

按照我的理解，是不是
同步助手版本1+对应的路径1+谷歌浏览器+ob
同步助手版本2+对应的路径2+edge浏览器+logseq

是否会有冲突或者其他问题？

因为我想同时体验这两种同步标注的方案，再来决定用ob还是logseq

**Comment by Kenshin** [comment]
同一个台电脑无法运行两个同步助手。

但你的诉求可以部分解决，简单的说：

1. 简悦本身的出发点功能（如：Notion、Logseq、Obsidian 都是隔绝的）
2. Obsidain 与 Logseq 各走各的路径。

这么做有个问题：因为无论是 Obsidian 还是 Logseq 在网页标注时，都需要使用 Markdown 模板增强引擎，但这个引擎暂时只能使用一个模板。

而 Obsidian 与 Logseq 的模板是不一样的。

但 Obsidian 与 Logseq 在各种客户端的功能不受影响，因为 Obsidian 与 Logseq 都分别嵌入了一个自己的模板引擎。

只要在增强导出中分别设置 `org` 与 `md` 为不同的路径就行

```
{"extension":"md", "path":"/Users/kenshin/Documents/Obsidian/SimpRead"}
{"extension":"org", "path":"/Users/kenshin/Documents/Logseq@test/pages"}
```

我目前就是这么做的，虽然不是为了同时导出它们，但是可以方便测试。
