### ISSUE TITLE
导出pdf 和Markdown失败，显示导出失败 此功能为实验性功能

### ISSUE THREAD

**Issue by Jefferson0611** [Kenshin/simpread#5069]
- 操作系统 版本	
- Windows 10 家庭中文版
版本号	22H2
安装日期	‎2021/‎12/‎23
操作系统内部版本	19045.2486
体验	Windows Feature Experience Pack 120.2212.4190.0

- 浏览器版本 108.0.5359.95（正式版本） （64 位）

- 简悦版本 **2.2.0.520**

**请描述你的问题**

> 之前导出pdf和markdown都可以不知道为啥，更新了一下同步助手到1.1.4 现在显示导出失败,此功能为实验性功能

**截图**
<img width="917" alt="20230117_042246" src="https://user-images.githubusercontent.com/100795589/212851571-0f4578ec-6fff-4ffb-b7af-8900ef88fc55.png">

**Comment by Kenshin** [comment]
emmm

感觉是你的高级账户「掉了」，选项页 → 账户，看看是否带 🔒 如果带 🔒 的话，使用 https://www.yuque.com/kenshin/simpread/sw4m21 解决。
