### ISSUE TITLE
关于导入到 Obsidian 的一些使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5072]
Hi @Kenshin，我遇到了新的问题

Q1. output 里有抓取的快照，为啥稍后读极速版显示404， 稍后读显示非离线呢。

不知道是不是哪一步弄错了，求解决的方法

同步文件夹output有网页离线快照
<img width="794" alt="image" src="https://user-images.githubusercontent.com/74954212/213085020-1e200203-2a6b-4bfd-9124-9912e488c4d0.png">

稍后读没有离线标志
<img width="377" alt="image" src="https://user-images.githubusercontent.com/74954212/213084936-97b78176-b012-4d16-b1ac-6f6ab0a1fe7f.png">

稍后读极速版显示404
<img width="410" alt="image" src="https://user-images.githubusercontent.com/74954212/213085107-39801ce5-0553-460b-beca-a801fe6b4308.png">

Q2. 换成obsidian simpread sync方案后，我需要手动点Manual Sync才能同步标注到obsidian。不像之前用同步助手的增强导出可以试试同步。 请问有什么解决的方法吗，同时用simpread sync 和同步助手的增强导出会不会有冲突呢？

_Originally posted by @Bicheng-G in https://github.com/Kenshin/simpread/issues/5070#issuecomment-1386481403_

**Comment by Kenshin** [comment]
@Bicheng-G 

因为 https://github.com/Kenshin/simpread/issues/5070 已经描述了一个功能，所以我新建了一个 Issues 讨论你的这些疑问。

***

> output 里有抓取的快照，为啥稍后读极速版显示404， 稍后读显示非离线呢。

output 虽然有 `.html` 但是因为前面没有序号，所以还是没办法被简悦检索到，正确的快照大概是下面的长相。

<img width="410" alt="image" src="https://user-images.githubusercontent.com/81074/213090934-3a51e1e4-5ba0-49df-aba9-4ecb1d2f331a.png">

你需要对比下 https://www.yuque.com/kenshin/simpread/wkswh7 与你配置的区别，主要是这个部分 https://www.yuque.com/kenshin/simpread/wkswh7#phV3U

> 换成obsidian simpread sync方案后，我需要手动点Manual Sync才能同步标注到obsidian。不像之前用同步助手的增强导出可以试试同步

如果你安装了 obsidian simpread sync 的话，不需要使用增强导出，你可以直接使用 [导入到 Obsidian 实现](https://github.com/Kenshin/simpread/discussions/2902)。

**Comment by Bicheng-G** [comment]
Hi @Kenshin,

感谢，两个问题都已经解决了。

Q1 是序号的原因。
Q2 配置了自动化辅助增强，现在的设置是SimpRead Sync + 自动化辅助增强，目前来看满足了我的需要。 

想了解一下这种方案跟同步助手增强导出各又什么优缺点吗？
SimpRead Sync 跟 local Rest API的优缺点分别是什么呢？

谢谢

**Comment by Kenshin** [comment]
> 想了解一下这种方案跟同步助手增强导出各又什么优缺点吗？

本质上没有太大的区别，导入方式：一个是通过 SimpRead Sync 完成；一个是借助增强导出（设定目录的方式）完成。

如果只使用导入到 Obsidian + Local REST API 的插件（不建议这么用，下面会解释），并且不考虑本地快照的话，不需要使用同步助手。

> SimpRead Sync 跟 local Rest API的优缺点分别是什么呢？

前者是专门为 Obsidian 开发的 Plugin 除了你提到的功能外，也包括将简悦的标注页面嵌入到 Obsidian。
后者只是一个专门用于 REST 的 Obsidian 插件。（但有部分用户报告这个插件在导入内容非常多的前提下会失败）

综上，如果你没有专门使用 Local REST API 的需求，建议直接使用前者。

**Comment by Bicheng-G** [comment]
@Kenshin 谢谢大大耐心解答，我感觉离完美工作流又近了一步。

移动端工作流目前遇到了点困难
处理从telegram bot 发送的api 快照，稍后读和稍后读极速版表现如下：
* 稍后读极速版：:negative_squared_cross_mark:不可以把快照转成阅读模式样式，:white_check_mark:标注可以时时同步Obsidian
* 稍后读：:white_check_mark:可以把快照转成阅读模式样式，:negative_squared_cross_mark:标注可以时时同步Obsidian

目前的workaround是用稍后读打开api快照（转成阅读模式快照），再用稍后读极速版做标注（时时同步Obsidian）。请问有没有两全其美的解决方案？:joy:
