### ISSUE TITLE
新站适配：机核网

### ISSUE THREAD

**Issue by yoyumiya** [Kenshin/simpread#5073]
https://www.gcores.com/articles/149957

**Comment by Kenshin** [comment]
收到~

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/68hAvoc6pC 安装。

同时因为这个站是动态加载的，所以需要将 `cores.com` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

PS：如果在使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装此站点。
