### ISSUE TITLE
Obsidian无法导入批注问题

### ISSUE THREAD

**Issue by woo0409** [Kenshin/simpread#5076]
按照教程设置好了同步助手，安装好Obsidian的插件和简悦中导入Obsidian的插件，再网页进行批注后导入Obsidian的过程中，Obsidian确实有这个文件，但是文件是空的，导入全文至Obsidian等功能都是正常的，但就是导入批注功能导入的是一个标题正常的空文件。求开发者解答。

**Comment by Kenshin** [comment]
在存在标注的页面，进入阅读模式后，右下角触发器，打开下图所示插件

<img width="488" alt="image" src="https://user-images.githubusercontent.com/81074/213358833-50206e8b-f6ed-42cd-bda8-10961eea5854.png">

然后看下图

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/81074/213358931-1e3731d3-e1e0-4a7c-9559-53ac90a11ad3.png">


<img width="1121" alt="image" src="https://user-images.githubusercontent.com/81074/213359097-de811aaf-c23b-4e6a-8879-49ed3a706a16.png">

**Comment by iFryRice** [comment]
同遇到上述问题，截图如下：
## 1. 增强编辑插件中预览图正常
![image](https://user-images.githubusercontent.com/102138235/214615305-85a64014-fd28-4679-bf28-1d1bc3380221.png)
## 2. 导入到Ob中显示空白文档，但导入全文正常
![image](https://user-images.githubusercontent.com/102138235/214615619-8de710c8-080d-4ed4-9fb4-ca875ce6eae7.png)

**Comment by Kenshin** [comment]
@iFryRice 

请问在导入到 Obsidain 的选项中使用了哪种导出方案？

**Comment by iFryRice** [comment]
第三种，但是因为之前某些bug，ob中插件的版本号为2.1.0 
![image](https://user-images.githubusercontent.com/102138235/214747272-227f1d9d-8c4e-4c94-b30c-03294b275282.png)
![image](https://user-images.githubusercontent.com/102138235/214747408-cb187bac-f424-4a8d-bd42-a5a09def143b.png)

**Comment by Kenshin** [comment]
@iFryRice

第三种方案的话，需要留意 ob 端 simpread sync 设置的目录，可以截图给我。

**Comment by Kenshin** [comment]
@iFryRice

第三种方案的话，需要留意 ob 端 simpread sync 设置的目录，可以截图给我。

**Comment by iFryRice** [comment]
![image](https://user-images.githubusercontent.com/102138235/214793287-5027beef-1559-4a3d-9c27-6a53bd51f5fb.png)

**Comment by iFryRice** [comment]
导入的目录貌似没有问题，文档也存在，但是内容是空白的。
![image](https://user-images.githubusercontent.com/102138235/214793531-3e7c9bb3-dda3-4b08-a7a3-14e01ba05284.png)

**Comment by Kenshin** [comment]
@iFryRice

okay 看起来目录也是正确的。😂

你方便的话，

1. 可以录屏我看看是如何导入标注的？
2. 把选项页 → 服务 → 自动化与同步助手 → 导出 → 增强导出对应的内容截图给我看看。

**Comment by iFryRice** [comment]
如下，
1. 标注导出

https://user-images.githubusercontent.com/102138235/214810358-5d06e0b7-a347-4ab2-afa6-72207cf5e14f.MP4

2. 增强导出
![image](https://user-images.githubusercontent.com/102138235/214809923-efd26ea9-7992-4608-81ac-8845b2ed089d.png)

**Comment by Kenshin** [comment]
@iFryRice 

我大概知道你的问题了... 不要先标注，而是先加稍后读后再标注。

**Comment by iFryRice** [comment]
先加入稍后读然后在当前页面中标注后，导入标注到obsidian仍然没有内容...
1. 页面截图
![image](https://user-images.githubusercontent.com/102138235/215240896-051f6324-85b2-4de2-afb0-2e0b5233bf9a.png)

2. 稍后读截图
![image](https://user-images.githubusercontent.com/102138235/215240881-85762931-efc9-4f3f-8217-dcdc9e033008.png)

3. 导入到Ob
![image](https://user-images.githubusercontent.com/102138235/215240919-565e7878-d96e-4c04-a3d4-dca717e7f12e.png)

**Comment by Kenshin** [comment]
@iFryRice

好吧，只剩下一招了... 把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5076

PS：还是建议对比下 https://www.yuque.com/kenshin/simpread/fr8zo5 跟你的设置上的区别。

**Comment by iFryRice** [comment]
okok，我对比一下，麻烦了。

**Comment by Kenshin** [comment]
@iFryRice

小事情。不行就发邮件，然后告诉我，我帮你看看。

**Comment by iFryRice** [comment]
您好，导入批注为空的问题还是不知道该如何解决，邮件已发送，麻烦您了。

**Comment by Kenshin** [comment]
@iFryRice 

耽搁了太久的回复了.... 我确认完会回复你的。

**Comment by Kenshin** [comment]
解决了... 你没有开 Markdown 辅助增强模板插件的选项...

![image](https://user-images.githubusercontent.com/81074/219271308-85bda7fa-324c-4a48-a2d2-5fbbeb2914da.png)

**Comment by iFryRice** [comment]
不好意思...给您添麻烦了...
