### ISSUE TITLE
阅读模式查看MDN文档

### ISSUE THREAD

**Issue by being12345** [Kenshin/simpread#5077]
代码显示不全, 部分内容省略

**Comment by Kenshin** [comment]
嗨，MDN 这类页面其实不适合使用阅读模式。

> 显示不全

可以使用类似下图所示的方式

<img width="466" alt="image" src="https://user-images.githubusercontent.com/81074/213412259-5685362a-5f14-463a-956a-4983bf00138c.png">

> 代码端

代码段的问题会集中在 #500
