### ISSUE TITLE
知乎LaTex公式导出到notion失败

### ISSUE THREAD

**Issue by lbyxiaolizi** [Kenshin/simpread#5078]
知乎等使用$……$作为行内公式的网站导入notion时仍以$……$的形式导入，不以LaTex公式的形式出现
![image](https://user-images.githubusercontent.com/65098936/213434681-e68a876d-2b1c-43b6-8050-c8c2a1c53bd0.png)

**Comment by Kenshin** [comment]
嗨，知乎的部分公式页面确实有这个问题（但也有部分页面没问题）

最好可以提供 URL 这样我做测试时也有一些参考数据。

**Comment by lbyxiaolizi** [comment]
您好，
文章URL：
https://zhuanlan.zhihu.com/p/351079165
https://zhuanlan.zhihu.com/p/308204310

**Comment by Kenshin** [comment]
okay 假期研究下。

**Comment by Jerrypiglet** [comment]
您好，这个页面的公式也存在类似问题：解析正常 但是到出到 Notion 或者 Markdown 即混乱：

https://zhuanlan.zhihu.com/p/614008188

<img width="1392" alt="image" src="https://github.com/Kenshin/simpread/assets/4903961/b5a099c3-d053-4196-b6ed-4726c50f991b">

![image](https://github.com/Kenshin/simpread/assets/4903961/4033aec4-784a-4734-8840-e3790e000073)

<img width="1552" alt="image" src="https://github.com/Kenshin/simpread/assets/4903961/5c92a563-b51c-4b9f-8a3f-be4031273071">

感谢帮助！

**Comment by Kenshin** [comment]
@Jerrypiglet 

我这边没有问题，看下图

<img width="1368" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e6a0dbb5-ca60-4163-a6d9-249f38db7c20">

这是我导出的 `.md` 文件 [NeRF 系列工作个人总结.txt](https://github.com/Kenshin/simpread/files/11560624/NeRF.txt)

知乎公式的解决方案 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

PS：按照上面的方案设置后导出到 Markdown 到本地，如果没有问题，但导入到 Notion 有问题的话，可能是 Notion 那边的事情。

**Comment by Jerrypiglet** [comment]
@Kenshin 感谢回复！我试了一下 保存的 md 文件里面的公式做一些简单的重拍版之后是可以正常渲染的（比如 $ -> $$，然后多行的公式转换成 code block）。但是我发现阅读模式下正常的公式，在稍后读和导出成 html 之后就会混乱。不知道是什么原因？

阅读模式：

<img width="1392" alt="image" src="https://github.com/Kenshin/simpread/assets/4903961/aeb4cb31-a8ea-40d6-8323-eddad757f15d">

稍后读：

<img width="1392" alt="image" src="https://github.com/Kenshin/simpread/assets/4903961/3117a8dd-47b1-4ed7-b811-f90331f8282c">

HTML:

<img width="1170" alt="image" src="https://github.com/Kenshin/simpread/assets/4903961/91056f71-b526-4bbf-b6ca-ad06a1515aaa">


再次感谢！

**Comment by Kenshin** [comment]
@Jerrypiglet

因为知乎的公式比较特殊，所以导出 HTML 确实有些问题，所以稍后读也是一样的情况。😂

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
