### ISSUE TITLE
基础账户的导出 Kindle 失败（高级账户导入 Kindle 不受影响）

### ISSUE THREAD

**Issue by Mars0031** [Kenshin/simpread#5080]
以前是可以的，最近一直失败

https://user-images.githubusercontent.com/108248739/213719331-ea3c5f24-2312-4e10-aedb-c600e441349f.mov

**Comment by Kenshin** [comment]
嗨，谢谢录屏，但只看视频并没有什么帮助 😂

请问你使用了同步助手的 Kindle 方案？还是扩展端内置的方案？

**Comment by Mars0031** [comment]
我之前的路径是，选择动作-保存到kindle-然后会打开一个kindle支持的保存页面，可以选择相应格式导出文件，然后我再用https://easychuan.cn/上传，用kindle浏览器下载，其他的我不是很懂哈。

**Comment by Mars0031** [comment]
我之前的路径是，选择动作-保存到kindle-然后会打开一个kindle支持的保存页面，可以选择相应格式导出文件，然后我再用https://easychuan.cn/上传，用kindle浏览器下载，其他的我不是很懂哈。

**Comment by Kenshin** [comment]
嗨，我知道是什么问题了。

你一直使用的免费的 Kindle 服务，这个服务使用了第三方方案，暂时无法使用了。

但如果你使用的是简悦高级账户相关功能的话，仍可以使用。（也就是此功能不受影响）

年后我会考虑优化下这个免费的服务看看有没有更好的免费方案。

**Comment by Mars0031** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/108248739/214729969-11f4d40b-7862-4c49-b5a7-622f259a3f0d.png">
那我有个小建议，这个保存失败的提示语，应该改一下如：“此功能需升级高级账户”，然后加一个升级入口。

**Comment by Kenshin** [comment]
> BTW我在官网、插件上，都没有找到升级高级账户入口

Web 端确实「藏」的有点深，我会考虑优化的。可能是为了照顾之前 1.x 的基础账户感受。

另外，购买方式也内置到了扩展端里面，通过选项页右上角或者账户选项卡都能看到。

> 这个保存失败的提示语，应该改一下如：“此功能需升级高级账户”，然后加一个升级入口。

谢谢，挺不错的建议 😄

**Comment by Mars0031** [comment]
刚刚升级了高级版，这套操作真的，对于一般人来说，太难了，我感觉还是主要针对一些程序员的产品。。哈哈

**Comment by Kenshin** [comment]
看你需要什么功能了，大部分功能都可以直接使用。

你可以说说哪里有难度

**Comment by Mars0031** [comment]
你好，我已升级了高级版，但是还是同样“保存失败，请稍后再试”

**Comment by Mars0031** [comment]
然后装了一个简悦同步助手后
<img width="548" alt="image" src="https://user-images.githubusercontent.com/108248739/215329283-2521738d-65f7-4fdc-b97e-33cf65258a83.png">

**Comment by Kenshin** [comment]
嗨，高级账户 Epub 功能需要同步助手以及 Pandoc 才能使用，细节可以 [看这里](https://simpread.pro/docs/#/Sync?id=epub)

**Comment by Mars0031** [comment]
嗨，我通过导出epub，然后再手动导入到我的kindle上完成了。
之前的问题还是未能解决（导出到kindle），还是报错
<img width="521" alt="image" src="https://user-images.githubusercontent.com/108248739/216333925-d1631d7c-f767-4e34-a202-94961c9874ac.png">
能否帮忙看一下这个导出到kindle之后的链接是什么？因为我当时在那个服务上订阅了转码服务，1年200元人民币，我得取消续订。。谢谢了！

**Comment by Kenshin** [comment]
你应该使用了同步助手吧？如果是的话，可以直接使用发送到 Kindle 的功能。但是需要配置自己的邮箱，如何配置 https://simpread.pro/docs/#/发送到-Kindle

> 因为我当时在那个服务上订阅了转码服务，1年200元人民币，我得取消续订。。谢谢了！

你是说 https://www.fivefilters.org/push-to-kindle/ 服务吗？

**Comment by Mars0031** [comment]
我是通过配置邮箱，然后通过邮箱发送epub文件直接到kindle的

> 你是说 https://www.fivefilters.org/push-to-kindle/ 服务吗？

应该不是他呢

**Comment by Kenshin** [comment]
> 我通过导出epub，然后再手动导入到我的kindle上完成了。

我的意思是：简悦自带了导入到 Kindle 方案，你不需要这么做，直接使用导入到 Kindle 功能就好。

> 因为我当时在那个服务上订阅了转码服务，1年200元人民币，我得取消续订。。谢谢了！

至于这个服务，停不停是看你自己。不过，从我的角度考虑的话，这个价格够高...

***

总结：

1. 如果你使用了直接发送到 Kindle 的功能，则不需要 https://www.fivefilters.org/push-to-kindle/ 这个服务了。
2. 我会有时间把 https://www.fivefilters.org/push-to-kindle/ 导入功能恢复，但跟你无关，因为这只是基础账户功能。（你已经是高级账户了。

**Comment by Mars0031** [comment]
对，已经交费的第一年200元已经无法退回了，我只是把续订取消了
非常感谢你的指导，另外我好奇的是你们这个产品是几个人在做还是说你一个在弄？

**Comment by Mars0031** [comment]
https://www.designweb3.io/web3-identity-decentralized-web-applications-for-developers/
还有个问题，我把这偏文章转为epub格式，文章里面的图片只有第一张显示，其他图片都没有的，这是正常的么？

**Comment by Kenshin** [comment]
> 对，已经交费的第一年200元已经无法退回了，我只是把续订取消了 非常感谢你的指导，另外我好奇的是你们这个产品是几个人在做还是说你一个在弄？

基本上就是我自己，但有一些社区的朋友帮忙维护社区。

另外，还有一些 Obsidian Logseq 高手在提各种需求 😂

> https://www.designweb3.io/web3-identity-decentralized-web-applications-for-developers/ 还有个问题，我把这偏文章转为epub格式，文章里面的图片只有第一张显示，其他图片都没有的，这是正常的么？

如果阅读模式下也这样当然导出后就这样，反之肯定是不正常的。

不过，不知道为什么我没法导出这个 Epub... 这还是第一次遇到无法导出的情况。

**Comment by Mars0031** [comment]
阅读模式下是正常的，导出epub后只显示第一张图 😅

**Comment by Kenshin** [comment]
导出 Markdown 发到这里我瞧瞧。

**Comment by Mars0031** [comment]
[simpread-Web3 Identity _ Decentralized Web Applications for Developers – designWeb3.md](https://github.com/Kenshin/simpread/files/10671258/simpread-Web3.Identity._.Decentralized.Web.Applications.for.Developers.designWeb3.md)

**Comment by Kenshin** [comment]
我看了你导出的 Markdown 也没啥问题... 😂

还有个办法，如果你愿意折腾的话，[自定义导出](https://simpread.pro/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA) 也可以实现导出 Epub 功能。

但需要安装 [Pandoc](https://simpread.pro/docs/#/Sync?id=pandoc)

**Comment by Mars0031** [comment]
`还有个办法，如果你愿意折腾的话，[自定义导出](https://simpread.pro/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA)` 也可以实现导出 Epub 功能。

但需要安装 `[Pandoc](https://simpread.pro/docs/#/Sync?id=pandoc)`

我折腾过了，确实不行。。图片就是不出来

另外

<img width="857" alt="image" src="https://user-images.githubusercontent.com/108248739/217848605-268f732a-096e-4a88-a971-ad1c8d6852b9.png">
我的高级会员也被登出了。不知道为啥


License | 2tgs-zdglmd-4mtbbd-mxdj

**Comment by Kenshin** [comment]
登出后，可以时候 https://www.yuque.com/kenshin/simpread/sw4m21 解决。

如果对这个网页没有特别的话，别折腾了... 😂

Pandoc 的方式肯定没问题，不知道是仅仅这个 URL 无法使用？还是其它都无法使用？如果是后者的话，说明你的配置有问题。

其实还有个办法，如果使用 Obsidian 的话，它里面也有个导出 Epub 的插件，你可以使用这个方式

PS：不要把 UID / License 发上来... 这是你的账户系统 ID，我已经给你删除了。
