### ISSUE TITLE
导入 Notion 的标注会「覆盖」已经导入 Notion 的全文的问题。

### ISSUE THREAD

**Issue by youngerruan** [Kenshin/simpread#5082]
以下步骤使用配置库 Notion 高级版，并成功配置。

1. 文章点击a a，进入阅读模式
2. 点击d d，加入稍后读，此时 Notion 已经能看到全文。
3. 在阅读模式标注，此时 Notion 的全文，已经被@annote 替代。只有标注，全文被删除。

问题：应该是个 bug 吧？我不确定，但是我找了好几遍设置，翻了好久都没解决。另外也重新删除简悦插件，并重新安装，重新配置库后，问题仍然存在。

需求：希望能和导出的 html 文件一样，同时有全文和标注（两个文件），Notion 上即两个文章。谢谢！

**Comment by Kenshin** [comment]
嗨，春节好～

通常情况下，全文和标注肯定是两个名称。
后者肯定是 @annote 标题的。

我目前没有遇到你说的问题，明天再详细确认下。

**Comment by youngerruan** [comment]
嗯嗯！感谢！我也觉得应该是两个才对。但是我测试了两次都是同样的结果，会覆盖。如果需要我的配置文件，明天我附上来。
2023年1月22日 +0800 22:23 Kenshin Wang ***@***.***>，写道：

**Comment by Kenshin** [comment]
嗨，问题已经 Fixed 掉了，请按照下面的方式升级即可。

PS：只有当特殊情况下才会发生 😂

***

📈 安装与升级
---

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装。

**Comment by youngerruan** [comment]
感谢！您还是一如既往的高效～
2023年1月23日 +0800 12:32 Kenshin Wang ***@***.***>，写道：

**Comment by Kenshin** [comment]
哈哈，谢谢。

PS：我记得你的 ID 😄 已经妥妥的老用户了~
