### ISSUE TITLE
请问Firfox版本怎么找不到下载了？

### ISSUE THREAD

**Issue by maijianbang** [Kenshin/simpread#5083]
RT，看很多文章都说有Firfox版的，但是到处都找不到下载地址。

**Comment by Kenshin** [comment]
嗨，FF 版只是 1.x 的部分功能，现在是 2.x 基本上已经不适用了，所以暂时不提供 FF 版了。

**Comment by maijianbang** [comment]
> 嗨，FF 版只是 1.x 的部分功能，现在是 2.x 基本上已经不适用了，所以暂时不提供 FF 版了。

所以FF没办法用了？

**Comment by maijianbang** [comment]
能不能发个1.xx版我暂时用用？
