### ISSUE TITLE
关于开放平台的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5086]
> https://simpread.pro/@id/reading/?token=

我设置了ID和Short，登录开放平台正常，但是输入授权码还是失败，这个授权码是哪里确定的？我点遗忘密码进入的是开放平台，不知道应该在哪里设置。
PS：API测试已通过，也成功添加了收藏助手。

_Originally posted by @StrollStars in https://github.com/Kenshin/simpread/discussions/2954#discussioncomment-4764363_

**Comment by Kenshin** [comment]
@StrollStars

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

试试在隐私模式下登录。

**Comment by StrollStars** [comment]
@Kenshin 隐私模式下也需要授权码，开放平台就一个设置Short的地方，但是测试过不是了。
该页面可否新增UID登录，不然可能只能公开访问才能用了。

**Comment by StrollStars** [comment]
@Kenshin 是的，报错如下图。
![2023-01-24_233649](https://user-images.githubusercontent.com/10942225/214338151-19b79e26-f200-4668-894f-d4e15d870a4f.png)

**Comment by Kenshin** [comment]
然后使用 UID / Licese 可以登录？

把你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5086

**Comment by StrollStars** [comment]
@Kenshin 已发送，请查收。

**Comment by Kenshin** [comment]
okay 估计只能明天确认了~

**Comment by Kenshin** [comment]
我知道你的问题了 😂

你的 ID 没有设置...

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/81074/214747530-7a3bcd28-ee31-432f-86eb-ce263ad2601c.png">

因为你提到了设置了 Short 但没法登录，所以理论上肯定也设置了 ID...

我帮你把 ID 设置上了，id 发到你的邮箱里面了。

**Comment by StrollStars** [comment]
@Kenshin 感谢回我邮件，其实登录开放平台也可见。
不过问题还在，还是上面那个截图，我试了ID和Short都是截图的报错……

**Comment by Kenshin** [comment]
不可能… 😂

我用帮你设置的 ID 和 Short 都已经成功登陆了…

试试隐私模式下登陆。

**Comment by StrollStars** [comment]
@Kenshin 你登录的是开放平台还是阅读列表？开放平台是没问题，但是阅读列表不行。
我通过ID的方式进入个人中心，点击阅读列表的进入提示如下图，你看和这个有关么：
![2023-01-26_162955](https://user-images.githubusercontent.com/10942225/214790117-e4a9b5dc-5388-4f30-9eb8-ac86d6845572.png)

**Comment by Kenshin** [comment]
你在坚果云有 output 这个文件夹吗？

PS：你可以看 https://www.yuque.com/kenshin/simpread/ieu1w6 这个教程

PPS：如果不是特别强烈需求的话，等过一小段时间在使用这个功能，下下个版本的同步助手会有优化方案，我会记录这个 Issues 到时候会在这里通知你。

**Comment by StrollStars** [comment]
@Kenshin 似乎弄好了，大致流程是：
1. 通过你给的链接指导新建output文件夹
2. 通过个人中心进入阅读列表成功
3. 通过https://simpread.pro/@id/reading/?token=链接输入授权码进入失败
4. 通过https://simpread.pro/@具体ID名称/reading/链接输入授权码进入成功

结论：你说的是对的，授权码就是Short，但是它在第四步能成功但第三步失败，可能是内部处理逻辑有点问题。

附言：
1. 我是以尽量简单的方法去用简悦，因此没用同步助手。
2. 收藏助手和阅读列表每次打开都会提示安装应用，这个是不是没法取消？
3. 尽管收藏助手安装很顺利，但是分享里面找不到，不过这个问题不大，直接打开收藏也行，就是要面对上一点的麻烦。
4. 阅读列表的功能可否增加高亮、批注和标签？这样手机看完就可以直接同步到本地笔记软件了，不然到了PC端还需要再做一遍。

**Comment by Kenshin** [comment]
`@id` 需要换成你自己的 ID… 😂

> 问题1

不使用同步助手的话，理论上可以使用 API 但这样很多相关功能都无法使用。

> 问题2

目前是的，但确实需要优化。（我已经记录）

> 问题3

分享仅限 Andriod 原生版本使用且已经使用「安装功能」

> 问题4

这是 Feature 下下个版本会有此功能。

**Comment by StrollStars** [comment]
> 需要换成你自己的 ID…

但是我看收藏助手用token和自己id都行的么，还以为阅读列表也行。

> 这是 Feature 下下个版本会有此功能。

大约在何时？感觉有点遥远。

还有个问题，收藏助手收藏的文章在阅读列表能看到，扩展的稍后读里看不到么？这个跟同步助手无关吧？

**Comment by Kenshin** [comment]
> 大约在何时？

下下个同步助手版本... 很快

> 收藏助手收藏的文章在阅读列表能看到，扩展的稍后读里看不到么？这个跟同步助手无关吧？

当然有关系 😂

收藏助手 → 收藏 → 更新坚果云 `simpread_config.json` → 通过坚果云客户端 → 同步到本地 → 通过同步助手 → 被扩展端获得。

也就是说使用收藏助手后，需要使用同步助手 + 坚果云客户端才能让扩展端也看到。

建议看看 https://www.yuque.com/kenshin/simpread/ieu1w6 （这个链接里面有详细描述，我之前也给过你）

> 但是我看收藏助手用token和自己id都行的么，还以为阅读列表也行。

`https://simpread.pro/@id/` 这里的 `id` 必须要换成自己的，因为这样才是你自己的「账户」。

**Comment by StrollStars** [comment]
> 收藏助手 → 收藏 → 更新坚果云 `simpread_config.json` → 通过坚果云客户端 → 同步到本地 → 通过同步助手 → 被扩展端获得。

这同步路径有点长😂
感谢多次耐心回复我

**Comment by Kenshin** [comment]
> 这同步路径有点长😂

不是步骤长... 只是我跟你这么解释下而已。

你（用户）仅需要打开同步助手 + 坚果云客户端就行了。

当然，前提是你已经配好了 https://www.yuque.com/kenshin/simpread/ieu1w6 需要的内容。

**Comment by StrollStars** [comment]
@Kenshin 配置是都做好了，但是浏览器扩展同步要开两个桌面客户端，总觉得很奇怪。😂

**Comment by Kenshin** [comment]
> 但是浏览器扩展同步要开两个桌面客户端，总觉得很奇怪。😂

你用过 Obsidian 并且也需要使用同步功能的话，就不奇怪了 😂
