### ISSUE TITLE
动作栏图标是否改为进入/退出模式

### ISSUE THREAD

**Issue by king33yoyo** [Kenshin/simpread#509]
mac 系统，chrome 浏览器 简悦版本为1.1.2.5005，关闭此选项刷新后动作栏图标仍然是进入/退出模式。不知道为什么。

**Comment by Kenshin** [comment]
请问「关闭此选项」后是弹出这个提示吗？

![image](https://user-images.githubusercontent.com/81074/58216650-f6dc1a00-7d31-11e9-9871-6e1096c06ab8.png)

如果是的话，这是正确的。

当你关闭此功能，但开着下面这个功能的时候，就会有上述提示

![image](https://user-images.githubusercontent.com/81074/58216802-884b8c00-7d32-11e9-9559-f0a745234ddb.png)

**Comment by king33yoyo** [comment]
解决了，非常感谢

**Comment by Kenshin** [comment]
搞定就好。我关闭这个 issues 了~
