### ISSUE TITLE
油猴版本的简阅是不是不能使用了？

### ISSUE THREAD

**Issue by huang5307** [Kenshin/simpread#5096]
要安装脚本结果显示脚本已经被删除，怎么回事？

**Comment by huang5307** [comment]
![image](https://user-images.githubusercontent.com/7876228/215256954-b6ca49bb-9055-4a1b-b90e-c640ae866790.png)

**Comment by Kenshin** [comment]
嗨

暂时先下线了，因为只是 1.x 的部分功能而已，现在已经是 2.x 版本了。

会考虑有时间的时候把 2.x 的功能移植成油猴脚本。
