### ISSUE TITLE
http://www.xxbiquge.com

### ISSUE THREAD

**Issue by lujqme** [Kenshin/simpread#51]
http://www.xxbiquge.com/xclass/1/1.html 无法解析

**Comment by airycanon** [comment]
@Kenshin http://www.xxbiquge.com/**/*.html 会匹配所有的目录及子目录，把 ** 改为 * 应该就可以了，其他包含 ** 的规则应该也有同样的问题。

**Comment by Kenshin** [comment]
@airycanon
一般情况下 **/* 的匹配已经适配了相似的页面，但有些个别的，比如这个…
我回去看看，顶多把这个页面的 url 改了就行。

**Comment by nuomi1** [comment]
@Kenshin 小说的话，https://greasyfork.org/zh-CN/scripts/292-my-novel-reader 这个脚本整理了一大堆……

**Comment by Kenshin** [comment]
@nuomi1
这么多都适配的话，会吐血的… 😭

**Comment by nuomi1** [comment]
@Kenshin 给个方向而已，以后开放分组和自定义时可以参考。

**Comment by Kenshin** [comment]
@nuomi1
是个好参考。 ^_^

**Comment by Kenshin** [comment]
@lujqme 
刚刚看了下，你可以把不需要（即无法使用阅读模式） 的 URL 加入到 `排除列表` 中，这样是最简单的方案。
排除列表的说明请看 [这里]((https://github.com/Kenshin/simpread/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97%EF%BC%88-%E6%93%8D%E4%BD%9C%E6%8C%87%E5%BC%95-%EF%BC%89#%E6%9F%90%E4%BA%9B%E7%AB%99%E7%82%B9%E5%B7%B2%E7%BB%8F%E9%80%82%E9%85%8D%E4%BA%86%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%E4%BD%86%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by Kenshin** [comment]
此 issues 将关闭，有异议的话，请重新打开它。
