### ISSUE TITLE
MD 导出，包裹代码的语法格式错误

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#510]
问题url：https://my.oschina.net/gaowm/blog/514765

使用简阅导出的MD时，包裹代码的语法变成了`<pre xxxx> 代码 </pre>`：
![image](https://user-images.githubusercontent.com/10437293/58221158-2562f080-7d44-11e9-9c47-6a4ef3bfac02.png)

正确的应该是:
![image](https://user-images.githubusercontent.com/10437293/58221222-56dbbc00-7d44-11e9-8793-38f501c75e4a.png)

重现步骤：
![image](https://user-images.githubusercontent.com/10437293/58221265-7e328900-7d44-11e9-8d37-8bba2be5889d.png)

**Comment by Kenshin** [comment]
谢谢反馈。

HTML → MD 采用了第三方库，稍后我看看能否进行优化。

不过，我试过几款 MD 编辑器，均可以识别出 `<pre>`

**Comment by AriaLyy** [comment]
识别到是能识别，但是没有了语法高亮，我用的是为知笔记。。😂

**Comment by Kenshin** [comment]
好，我看看能否修复这个问题…

目前还未支持为知笔记，你一般都是如何处理的？

**Comment by AriaLyy** [comment]
我是手动将`<pre>`修改为>```xxx

**Comment by AriaLyy** [comment]
你采用的那个 HTML --> MD 第三方库貌似有很大的的问题，很多网页不得行，比如这个网址：https://blog.csdn.net/github_2011/article/details/55194212 转出来的md基本上不能用。。。
题外说一句，貌似导出html的功能出问题了，今天一直导出失败。。

**Comment by Kenshin** [comment]
@AriaLyy 

确实导出的 md 有些问题，主要是 `<xxx>` 没有别正确识别，我看看是什么问题。

另外 `导出 HTML` 目前确实无法使用，三天后（下个月）恢复。
服务器的配额超了...  😂 

同样，这个问题在下个版本升级后会解决掉。

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布，解决了此问题。

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
