### ISSUE TITLE
按照简悦手册配置logseq配置库问题

### ISSUE THREAD

**Issue by pencilboxshotmail** [Kenshin/simpread#5102]
按https://www.yuque.com/kenshin/simpread/tukkeo 所述步骤配置logseq配置库（markdown版）出现问题。
卡在“开启自动同步”，无法开启启用【同步助手】的同步方案。点击开启按钮提示“发生了未知错误，请确认你的操作是否无误”。如图。
![image](https://user-images.githubusercontent.com/111672485/215274403-6a3de0a9-7e49-42d7-a55a-c2826c755f43.png)

同步助手未使用坚果云方式，直接用raidrive挂载天翼云盘客户端替代。

**Comment by pencilboxshotmail** [comment]
通过修改同步助手同步文件夹路径为raidrive webdav地址解决了上述问题。启用同步助手自动同步方案成功。但引发新的问题：按照图示操作1. 通过同步助手覆盖本地文件。 2. 提示“同步配置文件失败”
如图。
![image](https://user-images.githubusercontent.com/111672485/215300161-333163f9-9632-427d-960c-ef299ebfc1ad.png)

**Comment by Kenshin** [comment]
> 同步助手未使用坚果云方式，直接用raidrive挂载天翼云盘客户端替代。

把同步助手相关路径的截图给我看看，下图

<img width="671" alt="image" src="https://user-images.githubusercontent.com/81074/215305564-2488f93b-606c-4054-9320-1cf375fd7eec.png">

**同步配置文件失败** 这个提示是针对同步文件夹路径设置错误而产生的。

另外，一个排查法：先把同步路径设置到一个本地正常目录下，然后重启同步助手后再测试，确保不是因为路径操作错误而产生的。

**Comment by pencilboxshotmail** [comment]
> 
已解决上述问题。讲同步目录设置到本地正常目录下，可以正常进行设置。使用时出现新问题：logseq有简悦插件，能在面板中显示简悦文章。logseq日志中不出现标准文章的相关信息，新标注也不会在logseq窗口中出现，如图。
![image](https://user-images.githubusercontent.com/111672485/215388865-5ddb95cb-16d7-418a-8a56-149496ed4a72.png)

同步助手设置路径如下图。未使用logseq@simpread文件夹作为图谱，而直接在logseq根图谱下使用，因为如果跨图谱，相关非网页简悦的资料无法形成双链接。
![image](https://user-images.githubusercontent.com/111672485/215389131-829b5fb3-7077-4bcb-9079-c2647f8958f8.png)
![image](https://user-images.githubusercontent.com/111672485/215389189-04faaa26-6381-47f2-b254-58d098d47666.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5102#issuecomment-1407991525

Logseq 的问题你可以对比你的配置与 https://www.yuque.com/kenshin/simpread/gbere7 有什么区别？

另外，第一个图有可能是正常的，右侧只是稍后读的内容。

左侧有内容的前提是：你产生了标注或 `xxxx@annote` 这样的文件，也就是说如果你设置正确的前提下，在你设定的增强导出目录（图三）中存在这个文件。

**Comment by pencilboxshotmail** [comment]
> > [#5102 (comment)](https://github.com/Kenshin/simpread/issues/5102#issuecomment-1407991525)
> 
> Logseq 的问题你可以对比你的配置与 https://www.yuque.com/kenshin/simpread/gbere7 有什么区别？
> 
> 另外，第一个图有可能是正常的，右侧只是稍后读的内容。
> 
> 左侧有内容的前提是：你产生了标注或 `xxxx@annote` 这样的文件，也就是说如果你设置正确的前提下，在你设定的增强导出目录（图三）中存在这个文件。

在增强导出目录中存在xxxx@annote` 文件，如图：
![image](https://user-images.githubusercontent.com/111672485/215443543-16f6fbce-ab29-4403-ade1-86fae649e2f8.png)

另外对比同步助手设置，发现有些缺项，如图：
![image](https://user-images.githubusercontent.com/111672485/215446340-adfd3b2c-640d-4398-b296-02887ee2921a.png)

**Comment by Kenshin** [comment]
图一已经有对应的文件了，能在 Logseq 看到吗？如果能的话，就没有问题了。

**Comment by pencilboxshotmail** [comment]
> 图一已经有对应的文件了，能在 Logseq 看到吗？如果能的话，就没有问题了。

仍然看不到。之前看不到时，就已经有对应文件了。

**Comment by Kenshin** [comment]
> 仍然看不到。之前看不到时，就已经有对应文件了。

这个 .md 用任意文本编辑器打开后能看到标注吗？如果能看到标注说明标注已经正常的保存进去了，至于你的问题就是 Logseq 部分了。

**Comment by pencilboxshotmail** [comment]
> > 仍然看不到。之前看不到时，就已经有对应文件了。
> 
> 这个 .md 用任意文本编辑器打开后能看到标注吗？如果能看到标注说明标注已经正常的保存进去了，至于你的问题就是 Logseq 部分了。

看样子就是logseq的问题了。md文件正常，还有其他非简悦md文件不能正常显示的。

**Comment by Kenshin** [comment]
Cool~ 解决就好。

你用的哪个模板？我会加上一个备注说明。

**Comment by pencilboxshotmail** [comment]
> Cool~ 解决就好。
> 
> 你用的哪个模板？我会加上一个备注说明。

一、似乎问题没有完全解决，我修改的是https://www.yuque.com/kenshin/simpread/tukkeo#jkUOq中logseq配置库（markdwon版本）中稍后读模板，如下图修改配置1，测试生成的date好像是2网页创建日期。
![image](https://user-images.githubusercontent.com/111672485/215656641-5450bbd4-0da2-490c-b941-1983b0bacfbe.png)

二、在上图点击3“生成全部”后，所有之前在修改前模板下生成的标注md文件会更新date格式，并在logseq当日日志页面正常显示如图：
![image](https://user-images.githubusercontent.com/111672485/215657009-cd3e7354-5c17-42aa-be14-5750dccd9b44.png)
![image](https://user-images.githubusercontent.com/111672485/215657086-da02f237-89f2-4230-9462-f02a8bf6364a.png)

三、但是只要在该页面中新增标注，新更新的md文件date又会变成yyyy年mm月dd日，该文章又会在logseq当日日志页面消失。如图：
![image](https://user-images.githubusercontent.com/111672485/215657397-379a3ed6-3a5b-46b1-a4b5-5c6db7128d99.png)
![image](https://user-images.githubusercontent.com/111672485/215657464-293cb917-85a9-4028-9f91-885207e3bc7b.png)

四、新开一个重新未阅读的网页阅读模式下进行标注，生成的md文件并无date字段，如下图，logseq中依然不在日志页面显示。
![image](https://user-images.githubusercontent.com/111672485/215658252-2409c631-186b-40a1-a404-297f9b19a6ab.png)

 @Kenshin 请问这是怎么回事？

**Comment by lyserenity** [comment]
你是在哪里新增标注的？暂且分为从浏览器跟 logseq 

1. 你可以先去确认一下两边的模版有没有一致
2. 简悦有时候会有同步的问题，你可以检查一下你 logseq 的模版有没有跑掉（有时候你改完，生成全部是正确的，也按了保存，但它其实跑掉了）

最后补充一下，据我所知，logseq 日志的日期要符合这个设置：
<img width="902" alt="image" src="https://user-images.githubusercontent.com/32646062/215668592-1acdea6b-db37-4e6c-bb0a-2ea27019c9a9.png">

如果不符的就不会出现在下方，所以你要检查一下。

**Comment by lyserenity** [comment]
还有一个，你有使用「[[Plugin]将标注以 MD 2.0 模板形式导出 · Issue #4320 · Kenshin/simpread](https://github.com/Kenshin/simpread/issues/4320)」这个插件吗？

如果有，你导出到 logseq 的时候要用这个，不能用：
<img width="226" alt="image" src="https://user-images.githubusercontent.com/32646062/215670680-7bd9a7be-0518-4ad2-8af2-bd2f425c60db.png">

这个使用的是内置模版，不是进阶版的 2.0

**Comment by pencilboxshotmail** [comment]
> 还有一个，你有使用「[[Plugin]将标注以 MD 2.0 模板形式导出 · Issue #4320 · Kenshin/simpread](https://github.com/Kenshin/simpread/issues/4320)」这个插件吗？
> 
> 如果有，你导出到 logseq 的时候要用插件提供的，不能用下图这个： <img alt="image" width="226" src="https://user-images.githubusercontent.com/32646062/215670680-7bd9a7be-0518-4ad2-8af2-bd2f425c60db.png">
> 
> 这个使用的是内置模版，不是进阶版的 2.0

直觉告诉我是这个内置模板的问题。
1. 我是在浏览器新增标注的。请问如何检查两边的模板是否一致？我只知道在「http://localhost:7026/unread/1?embed=logseq」里面点设置。在这个设置里我规范了一下日志日期模式，模板没有跑掉，如图：
![image](https://user-images.githubusercontent.com/111672485/215674909-51374eaa-a380-4aa6-a689-857355e204a3.png)
此时生成md文件如下：
![image](https://user-images.githubusercontent.com/111672485/215675076-e9588d51-015b-4fd3-b5f3-71b7de488aa5.png)

2. 我在浏览器网页简悦阅读模式下新增标注后，「http://localhost:7026/unread/1?embed=logseq」里面设置的稍后读模板没有跑掉，还是我修改新的。但md文件又变回了标准模板生成的，如图：
![image](https://user-images.githubusercontent.com/111672485/215674742-ac75a859-7dbf-474b-81df-b6291f2c4aaa.png)

3. 我用了「https://github.com/Kenshin/simpread/issues/4320」这个插件，之前在浏览器中简悦选项页——服务——自动化中如下设置：
![image](https://user-images.githubusercontent.com/111672485/215675490-4ec40799-0462-42cb-abf0-15999651120b.png)
应该就是这里出了问题。但我不知道怎么改？
自动化任务里删除稍后读中自动导出markdown文件选项，依然还是和上面一样，生成的是修改之前的标准模板的md文件。

**Comment by pencilboxshotmail** [comment]
> 还有一个，你有使用「[[Plugin]将标注以 MD 2.0 模板形式导出 · Issue #4320 · Kenshin/simpread](https://github.com/Kenshin/simpread/issues/4320)」这个插件吗？
> 
> 如果有，你导出到 logseq 的时候要用插件提供的，不能用下图这个： <img alt="image" width="226" src="https://user-images.githubusercontent.com/32646062/215670680-7bd9a7be-0518-4ad2-8af2-bd2f425c60db.png">
> 
> 这个使用的是内置模版，不是进阶版的 2.0

果然就是这个问题。
1.按照上面我说的思路，选择在任一网页进入阅读模式，进入 右下角“...”——动作——插件触发器——markdown辅助增强插件选项。如图：
![image](https://user-images.githubusercontent.com/111672485/215677274-427033c3-bcb2-4312-966c-5aa4755b49a7.png)

2. 修改里面的稍后读模板如下：
![image](https://user-images.githubusercontent.com/111672485/215678282-3d1772f9-b871-4578-9d4b-0d3b42ba7c8b.png)

问题解决了。。。。新生成的md文件都遵循了修改后的新模板！！！

**Comment by Kenshin** [comment]
@pencilboxshotmail 

Cool~ 解决就好，我会把时间的问题也记录到模板中。

***

**Comment by Kenshin** [comment]
@pencilboxshotmail 

我关闭这个 issues 了，这也算是挺长的 Issues 回复了 😂（一般情况下，3 ~ 4 条回复内基本上都能搞定。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by pencilboxshotmail** [comment]
> @pencilboxshotmail
> 
> 我关闭这个 issues 了，这也算是挺长的 Issues 回复了 😂（一般情况下，3 ~ 4 条回复内基本上都能搞定。
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

ok。必须五星好评。我用了很久了，高级用户，也会一直用下去。期待更多好用的优化。

**Comment by Kenshin** [comment]
哈，谢好评 😄
