### ISSUE TITLE
导出markdown或者导出到notion后，代码高亮失效

### ISSUE THREAD

**Issue by zs6** [Kenshin/simpread#5104]
- 具体表现为导出的代码段全是文本代码段，没有标记代码所使用的的语言导致markdown和notion无法高亮代码
![image](https://user-images.githubusercontent.com/45552564/215308950-deef4f29-530e-436c-823c-972e23938ec2.png)

**Comment by Kenshin** [comment]
嗨，这个暂时没法实现。

因为没办法识别出当前页面的代码是何种编译语言，所以导入后自然没有语法着色 😂
