### ISSUE TITLE
关于知识库配置的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5105]
按流程配置且正常产生导出文件，但稍后读中无法读取本地文件
![CleanShot 2023-01-29 at 15 52 59](https://user-images.githubusercontent.com/24691751/215313084-9b3a25af-22bc-4774-8f17-8e6291aa415c.png)
![CleanShot 2023-01-29 at 15 53 04](https://user-images.githubusercontent.com/24691751/215313090-33e723fd-b6b2-4b8f-8c6f-34e417efd20f.png)
![CleanShot 2023-01-29 at 15 53 15](https://user-images.githubusercontent.com/24691751/215313091-49bca962-1e17-4be6-ab07-e521e9013878.png)

_Originally posted by @JonasCynical in https://github.com/Kenshin/simpread/discussions/2146#discussioncomment-4808092_

**Comment by Kenshin** [comment]
@JonasCynical 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

第一个截图没有问题

第二个截图应该在左下角有类似下图的标识

![image](https://user-images.githubusercontent.com/81074/215314589-12b7c610-c79f-486b-81cf-f83468d827b4.png)

你可以对比下你的配置与 https://www.yuque.com/kenshin/simpread/wkswh7 区别是什么。

留意下图与你自己的配置

![image](https://user-images.githubusercontent.com/81074/215314632-b7976f12-352b-4507-bec3-91be820b45f6.png)

**Comment by JonasCynical** [comment]
所有选项已开启，严格对照配置库一模一样的配置强制同步后重启依然无法加载本地文件
![CleanShot 2023-01-29 at 16 51 47](https://user-images.githubusercontent.com/24691751/215315660-db851b2b-2b0f-4890-a1bd-eec46301b822.png)
![CleanShot 2023-01-29 at 16 52 02](https://user-images.githubusercontent.com/24691751/215315674-c2ad7e68-7ab9-4a70-9395-f89eafcd11d4.png)

**Comment by JonasCynical** [comment]
Issue resolved, 原来是复制自定义标题的时候前面多了个空格导致无法读取
![CleanShot 2023-01-29 at 17 42 32](https://user-images.githubusercontent.com/24691751/215318091-1efb36da-c9df-4282-b1a1-7fd67df24e92.png)

![CleanShot 2023-01-29 at 17 41 43](https://user-images.githubusercontent.com/24691751/215318076-9f3e092e-471f-45d6-81c9-2b0b7fba34ad.png)

**Comment by Kenshin** [comment]
原来如此 😂

解决就好~
