### ISSUE TITLE
收藏助手保存成功，阅读列表和output可以看到，稍后读和simpread_config文件中无此文章

### ISSUE THREAD

**Issue by hmywd** [Kenshin/simpread#5106]
hi老师您好
收藏助手保存成功，阅读列表和output可以看到，稍后读和simpread_config文件中无此文章。之前使用是正常的，近期突然出现这个问题，谢谢

**Comment by hmywd** [comment]
谢谢您的回复，URL的快照确实已经保存成功，可以在output中看到对应的html文件
> 说明这个 URL 的快照已经保存成功了。

查看截图中的配置是打开的。
simpread_config.json 坚果云上文件修改时间和json文件内”"update"“都更新了，但是”unrdist“中没有增加对应的内容。
> 看下你的坚果云中 simpread_config.json 是否更新了？如果更新的话，说明这个文件没有保存到你的本地。
> 对比下 [这个教程](https://www.yuque.com/kenshin/simpread/pwpnsx#TCQKB) 与你的配置有什么区别？留意下面的截图（链接中已包含）

**Comment by Kenshin** [comment]
猜测可能是互相覆盖了造成的，你可以这样测试下：

1. 关闭坚果云客户端，然后浏览器不要打开任何跟下面测试无关的 Tab 或网页
2. 使用同步助手收藏 https://sspai.com/post/69972
3. 收藏成功后会看到坚果云 Web 端的 `simpread_config.json` 更新了
4. 关闭浏览器
5. 打开坚果云（坚果云会把新的配置文件保存到本地，看下本地是否更新了）
6. 打开浏览器并查看你的稍后读。

**Comment by hmywd** [comment]
还是不行 。PC浏览器保存没问题，收藏助手就不能添加到simpread_config.json文件了。
谢谢了

**Comment by Kenshin** [comment]
坚果云 Web 端简悦的文件夹截图给我看看，应该是 SimpRead 文件夹。

**Comment by hmywd** [comment]
> 坚果云 Web 端简悦的文件夹截图给我看看，应该是 SimpRead 文件夹。

![1675172676049](https://user-images.githubusercontent.com/35159434/215776968-62c0b6c6-76b6-4b85-9c9d-c2437be7fe56.png)

**Comment by Kenshin** [comment]
@hmywd 

emmmm 我明白了... 你的 `simpread_config.json` 太大了。😂 可能触发了坚果云的限制。

PS：请问有多少个稍后读数据？

***

我会重开这个 issues，这个问题暂时没办法解决，但已经有解决方案了，因为我也遇到了这个情况。

我会尽快在2月份推出相关解决方案。不是技术上的问题的，而是同步助手的相关功能 Roadmap 都已经准备好了，不太好改动。

**Comment by Kenshin** [comment]
其实解决方案也很简单：暂时不用收藏助手即可 😂

**Comment by hmywd** [comment]
感谢，原来如此。期待之后的解决方案

**Comment by hmywd** [comment]
> @hmywd
> 
> emmmm 我明白了... 你的 `simpread_config.json` 太大了。😂 可能触发了坚果云的限制。
> 
> PS：请问有多少个稍后读数据？
> 
> 我会重开这个 issues，这个问题暂时没办法解决，但已经有解决方案了，因为我也遇到了这个情况。
> 
> 我会尽快在2月份推出相关解决方案。不是技术上的问题的，而是同步助手的相关功能 Roadmap 都已经准备好了，不太好改动。

目前是350个，可能某些标注和笔记比较多

**Comment by Kenshin** [comment]
350 不算多…

可能标注时因为页面结构导致定位文件比较大。
