### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by kynn88101** [Kenshin/simpread#5107]
发生问题的地址: <https://www.qiagen.com/zh-cn/applications/digital-pcr/beginners/dpcr-vs-qpcr>

**Comment by Kenshin** [comment]
嗨

你提供的 URL 并没有进入阅读模式的必要。

但例如 https://www.qiagen.com/zh-cn/customer-stories/dpcr-standardized-diagnostics-from-london-to-shanghai 这样的页面，可以使用下图所示的方式进入阅读模式。

<img width="668" alt="image" src="https://user-images.githubusercontent.com/81074/215410561-81325db3-f1b0-407f-9b6a-142995a2540c.png">
