### ISSUE TITLE
notion和logseq的配置包下载解押后到底该怎么操作

### ISSUE THREAD

**Issue by zephyrs311** [Kenshin/simpread#5109]
![ce50a1be40197722abeda534fff2dcd](https://user-images.githubusercontent.com/123920983/215669102-d7f99caf-8586-4dfd-98c0-b9b9243a7d74.png)
已经存在output设置好了本地快照
新下载下来解押后的文件该怎么存放使用，如何同步本地插件

**Comment by Kenshin** [comment]
Logseq 的配置包教程在 https://www.yuque.com/kenshin/simpread/tukkeo 

你的疑问都可以在上面这个链接找到，如果看了这个教程，有什么不清楚的话，请详细说明。
