### ISSUE TITLE
CodeBlock显示问题

### ISSUE THREAD

**Issue by LaelLuo** [Kenshin/simpread#511]
当页面有`CodeBlock`的时候转换的到的结果并不令人满意, 会使代码高亮效果消失, 变得不方便阅读, 如果能在保留`CodeBlock`的前提下, 统一代码高亮的风格, 效果会非常好.

**Comment by Kenshin** [comment]
代码高亮可以使用 https://github.com/Kenshin/simpread/issues/500 这个方式实现。

另外，请告知具体的 URL
