### ISSUE TITLE
所有操作都会调用失败

### ISSUE THREAD

**Issue by zephyrs311** [Kenshin/simpread#5110]
Windows

edge

- 简悦版本 **2.0.0**

所有的操作包括加入到稍后读 标注  在稍后读里打开文件都会提示错误
嗨，不小心调用失败了，请不要担心，请重新再试~

重装插件也没用
嗨，不小心调用失败了，请不要担心，请重新再试~

![image](https://user-images.githubusercontent.com/123920983/215749331-18e07a00-d0ae-4382-939a-7c6b7ab2fe4c.png)
![image](https://user-images.githubusercontent.com/123920983/215749481-1326d95d-2551-4ac7-8510-0c7cdcdeeb0d.png)

**Comment by NexZhu** [comment]
@Kenshin 请问怎么绑定扩展端的UID，同步助手里没找到绑定功能
![image](https://user-images.githubusercontent.com/4370605/220384317-db152cb4-2254-4217-ba0e-5b4260f9e11e.png)

**Comment by Kenshin** [comment]
@NexZhu

截图就有你问题的答案。

<img width="733" alt="image" src="https://user-images.githubusercontent.com/81074/220513485-85a83a15-aee8-4f44-b5d7-38dd445bded8.png">

**Comment by NexZhu** [comment]
@Kenshin 我扩展里已经绑定了高级账户，之后还是这个错

**Comment by Kenshin** [comment]
> 我扩展里已经绑定了高级账户

跟扩展端没关系，我说的是需要绑同步助手，如果你的界面跟 https://github.com/Kenshin/simpread/issues/5110#issuecomment-1439386338 一致的话，说明没有绑... 

如何使用 [请看这里](https://simpread.pro/docs/#/Sync?id=%E9%AA%8C%E8%AF%81)
