### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by gao5** [Kenshin/simpread#5112]
印象笔记授权失败，开全局，清空缓存的方法都试了，还是不行，win11系统，	Edge浏览器

**Comment by gao5** [comment]
印象笔记一直提示授权失败，win11系统，edge浏览器

**Comment by Kenshin** [comment]
嗨，谢谢反馈，不建议使用印象笔记了 😂

另外，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
