### ISSUE TITLE
导出markdown文件失败其他都可以

### ISSUE THREAD

**Issue by zephyrs311** [Kenshin/simpread#5117]
![image](https://user-images.githubusercontent.com/123920983/216062763-4a5eeec8-2d61-4db5-854a-01d441f4fdc8.png)

Windows 
edge

导出markdown文件失败
pdf html都可以
就是导出MARKDOWN
会显示导出失败，此功能为实验性功能，如有需求请提 lssues

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
用同步助手了吗？如果使用的话，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 能否解决？

另外，导出 md 是用了哪个方案？（简悦导出 md 有很多方式）

**Comment by zephyrs311** [comment]
用了同步助手，插件也安装了
![image](https://user-images.githubusercontent.com/123920983/216201173-739469f5-52cb-42e2-bc62-758e9e095fba.png)
简单这里操作也不行
自动化DD加入稍后读
自动导出到logseq也失败
全都是这个提示

**Comment by zephyrs311** [comment]
![image](https://user-images.githubusercontent.com/123920983/216209595-765f141a-1550-437a-89f7-a50c21380b9b.png)
zeng增强导出我每次点开这里 刷新确认也打开了，结果再试，他又关闭了

**Comment by zephyrs311** [comment]
> 用同步助手了吗？如果使用的话，试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 能否解决？
> 
> 另外，导出 md 是用了哪个方案？（简悦导出 md 有很多方式）
![image](https://user-images.githubusercontent.com/123920983/216209786-5d084754-8b6b-4785-a6e1-5d7196cac780.png)
![image](https://user-images.githubusercontent.com/123920983/216209807-b4807573-d1ff-4052-a382-22b282d1d1a8.png)
用了同步助手，插件也安装了
简单这里操作也不行
自动化DD加入稍后读
自动导出到logseq也失败
全都是这个提示
增强导出我每次点开这里 刷新确认也打开了，结果再试，他又关闭了

**Comment by Kenshin** [comment]
> 增强导出我每次点开这里 刷新确认也打开了，结果再试，他又关闭了

开启它，然后重启浏览器，确保配置生效。

PS：只有当多个 Tab 同时开启互相覆盖后才会出现你说的问题。

**Comment by zephyrs311** [comment]
> > 增强导出我每次点开这里 刷新确认也打开了，结果再试，他又关闭了
> 
> 开启它，然后重启浏览器，确保配置生效。
> 
> PS：只有当多个 Tab 同时开启互相覆盖后才会出现你说的问题。

这个问题解决了，按您的指导谢谢。
![image](https://user-images.githubusercontent.com/123920983/216226278-f1f3800c-6aab-4829-8e6a-03713a8d6668.png)
danz但这个还是不行，导出不了markdown
标注自动化导出都不行

**Comment by Kenshin** [comment]
试试 https://sspai.com/post/69972 这个页面

肯定还是你之前折腾配置时开启了某个功能但这个功能没有再继续后续配置它造成的。

**Comment by zephyrs311** [comment]
> 试试 https://sspai.com/post/69972 这个页面
> 
> 肯定还是你之前折腾配置时开启了某个功能但这个功能没有再继续后续配置它造成的。

这个页面我配置了 正常打开有标注

**Comment by Kenshin** [comment]
把出问题的地方录屏给我
