### ISSUE TITLE
站点管理器 登录异常

### ISSUE THREAD

**Issue by wangshuyu** [Kenshin/simpread#5118]
站点管理器----点击:登录到服务器
异常提示:  获取后台服务失败,请稍后在试

**Comment by Kenshin** [comment]
嗨，非管理员暂时无法使用这个功能，属于半下线状态 。

你需要提交新站？还是？

**Comment by wangshuyu** [comment]
1. 需要提交一个站点, 属于内部站点 不确定是否可以提交哈
2. 暂时使用坚果云同步功能也可接受
3. 站点名称:  wiki.517cdn.com

**Comment by Kenshin** [comment]
收到~

不过 `wiki.517cdn.com` 好奇问问这个站点无法直接进入阅读模式吗？

如果只是私人使用的话，不需要提交，按下面的方式即可：

1. 进入阅读模式

2. 站点编辑器
 
   <img width="480" alt="image" src="https://user-images.githubusercontent.com/81074/216946413-acaa2745-1ed8-41f7-ac84-30456032ace7.png">

3. 按照适配规则填写（前提是你需要了解一些简单的 JS 技术），然后保存即可。

    <img width="471" alt="image" src="https://user-images.githubusercontent.com/81074/216946637-5c18dff7-4e50-4bcc-8d05-b7c26bc5200c.png">
    
    
关于 **站点编辑器** 如何添加适配规则的话，[看这里](https://simpread.pro/docs/#/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8)。
