### ISSUE TITLE
购买超过三天，尚未收到邮件

### ISSUE THREAD

**Issue by handong369** [Kenshin/simpread#5123]

**Comment by Kenshin** [comment]
2月3日晚上19点左右兑换了一批，检查下垃圾箱。

把你的 Email 给我，否则我什么否不提供我怎么帮你。

**Comment by handong369** [comment]
***@***.******@***.***>


发件人: Kenshin Wang ***@***.***>
日期: 星期六, 2023年2月4日 08:36
收件人: Kenshin/simpread ***@***.***>
抄送: Dong Han ***@***.***>, Author ***@***.***>
主题: Re: [Kenshin/simpread] 购买超过三天，尚未收到邮件 (Issue #5123)

2月3日晚上19点左右兑换了一批，检查下垃圾箱。

把你的 Email 给我，否则我什么否不提供我怎么帮你。

―

**Comment by handong369** [comment]
已经检查过邮箱，确认没有收到邮件。 邮箱地址为，donghan9510@gmail.com

**Comment by Kenshin** [comment]
你的邮箱地址写错了...

<img width="480" alt="image" src="https://user-images.githubusercontent.com/81074/216752655-3515221e-fdf2-41db-bbaa-d458a11e34f5.png">

请使用截图所示的「错误邮箱」 + 202*** 后六位登录 https://simpread.pro/code   就可以兑换了。

当你收到这个 Issues 提示后，我重新给你正确的邮箱发了一封如何兑换的说明。
