### ISSUE TITLE
chrome扩展打开 d.cellmean.com 会卡死，必须禁用才行

### ISSUE THREAD

**Issue by falconchen** [Kenshin/simpread#5125]
chrome的扩展，一打开[我这个网站](https://d.cellmean.com)就卡死，半天载入不完，有些还出现提示关闭或等待，排查了半天，最后发现是这个扩展的问题，不知道是不是bug，只能禁用了。

**Comment by Kenshin** [comment]
嗨，加入黑名单就行了我明天测试下。

另外，在隐私模式下，仅启用简悦试试。

**Comment by Kenshin** [comment]
我测试了下，并没有遇到你的说的问题。

不过，你可以在黑名单中加入

```
cellmean.com
```

按下图所示即可。

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/81074/216798131-da5250ec-3a49-4b9f-aeef-89ea3c48fb7f.png">
