### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5126]
**请说明发生问题的环境**

在网站可以进入阅读模式，加入稍后读以后，无法直接解析文章进行观看标注。但是本地快照又是存在的，可以进行标注

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，暂时并不支持此类网站，我关闭这个 Issues 了。
