### ISSUE TITLE
notion的网站解析后，只有开头一点点，也试了集市里的第三方源，先显示了404，然后显示安装成功，跳转回站点管理，发现仍然没有安装

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5127]

**Comment by Nadir-Echo** [comment]
![VeryCapture_20230205102838](https://user-images.githubusercontent.com/86950349/216798456-17d4347d-de09-4d1a-a46a-4ba3084bc33f.gif)

**Comment by Nadir-Echo** [comment]
不知道为什么，想发gif，好像无法显示
![image](https://user-images.githubusercontent.com/86950349/216798471-097f5990-1a78-4a18-bfbb-ab9663308179.png)
![image](https://user-images.githubusercontent.com/86950349/216798490-f9d89142-f86f-4d4d-a67a-55091345e868.png)

**Comment by Nadir-Echo** [comment]
> [notion网站](https://www.notion.so/Zettelkasten-25627d7ce99344c487f4e42d861f9e0a)点击进入阅读模式，只显示开头一点点。站点集市点击安装，先跳出414 Request-URI，然后跳出小框说安装成功，返回简悦设置页仍然没有

https://s3.bmp.ovh/imgs/2023/02/05/24d38d8950a15cdc.gif

**Comment by Kenshin** [comment]
嗨，这是我解析后的效果

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/81074/216798986-a44c37af-68fb-4958-9a79-32ebeb01fb5e.png">

> 站点适配无法安装的问题

请问是不是使用了同步助手？如果是的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 解决。
反之没有使用同步助手的话，重启浏览器，然后根据 https://github.com/Kenshin/simpread/discussions/2106 分别安装两个规则。

安装相应站点后正确识别标识

<img width="475" alt="image" src="https://user-images.githubusercontent.com/81074/216799010-4a2edffd-74e3-4cab-a70c-28fcdba07b76.png">
