### ISSUE TITLE
关于Obsidian SimpRead Sync - 一站式文献笔记的一些疑问

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5128]
你好，Kenshin。我想询问一些关于这个Obsidian SimpRead Sync - 一站式文献笔记教程中遇到的一些问题。
1. 首先整套流程是主要依赖于坚果云的自动同步功能吗？我需要把simread的整个文件夹放在ob库下的文件夹里面吗，可以两边分开放吗？因为目前我是用的是remotely Save插件同步到腾讯云的对象存储+onedrive文件夹中。我曾经尝试过SimpRead坚果云的文件夹，ob单独分开放，当我插件中使用手动同步时可以导入标注，但是想通过某条标注查看原文显示的是404不存在。
2. 然后是同步助手的问题，不知道是哪里出了问题，昨天晚上按照教程配置完毕的时候并没有问题，今天进行阅读的时候对于notion等页面进行阅读，下载了适配站点对应的插件，将网址加入，重新点开同步后打开notion解析还是不行，打开词法分析引擎那个界面，发现两个网址不见了，我再次关闭自动同步，输入网址才可以。然后中午添加全文翻译彩云小译的api死活黏贴不进去，后来又发现是自动同步的问题，关掉自动同步，关掉浏览器，再打开才可以输入，感觉是不是坚果云的自动同步的锅，刚刚在打开导出Obsidiain选项，也是一点都改不了。
![image](https://user-images.githubusercontent.com/86950349/216808110-ba21a946-8a6f-4131-bcb5-6e5cf9004757.png)
3. 然后在阅读的时候加入稍后读，点击进入稍后读发现，稍后读并没有本地的按钮，我打开阅读模式并没有显示全文，文章好像没有下载下来。
![image](https://user-images.githubusercontent.com/86950349/216808353-b4eab9a0-168c-4ffe-9b03-dc0446eb04b2.png)
4. 所以我想了解一下这个方案整体的工作过程😂，不知道方便不方便。
当我打开阅读模式，进行批注的时候，批注可能以json格式存储在浏览器缓存中？然后我选择加入稍后读，之前配置的同步助手的导出目录output保存下载下来的本地快照、标注和mrakdown（依靠自动化配置下载）？
5. 打开稍后读，看到了浏览页面时的标注，阅读全文，增加新的标注，自动更新本地文件。
6. 这里面SimpRead.json文件有什么用吗
simread.json文件里面似乎除了对简悦配置文件的保存外好像还有一些注释的保存。  
7. 这里有个问题，如果我回到原页面，对原页面进行修改，增加批注和注释，稍后读里面是否会增加？或者说在 obsidian、稍后读和原页面任意一端进行批注的增删，其他两端是否会修改？看了一下自动化那里，好像是单边的，也就是触发加入稍后读和触发加入标注时才会更改本地文件？
8. obsidian的simpRead插件打开本地快照后标注后自动生成新的标注md和json文件覆盖本地？

在稍后读那个环节，读取的文件是本地离线文件还是坚果云端的文件？

**Comment by Kenshin** [comment]
哈，太长了 😂 我在外面，先重点回复下需要的内容，余下的内容我明天回复你。

> 问题2

这算是个 Bug，但可以通过 https://www.yuque.com/kenshin/simpread/fcw60u 来解决。

> 问题3

应该是你没有配置好本地快照文件夹（也就是知识库）功能，这是教程 https://www.yuque.com/kenshin/simpread/wkswh7 很简单，留意几个路径就行。

> 这里有个问题，如果我回到原页面，对原页面进行修改，增加批注和注释，稍后读里面是否会增加？

当然会增加

> 或者说在 obsidian、稍后读和原页面任意一端进行批注的增删，其他两端是否会修改？

如果你说的是 在 Obsidian 中继续标注的话，当然也都是双向同步。

**Comment by Nadir-Echo** [comment]
> 哈，太长了 😂 我在外面，先重点回复下需要的内容，余下的内容我明天回复你。
> 
> > 问题2
> 
> 这算是个 Bug，但可以通过 https://www.yuque.com/kenshin/simpread/fcw60u 来解决。
> 
> > 问题3
> 
> 应该是你没有配置好本地快照文件夹（也就是知识库）功能，这是教程 https://www.yuque.com/kenshin/simpread/wkswh7 很简单，留意几个路径就行。
> 
> > 这里有个问题，如果我回到原页面，对原页面进行修改，增加批注和注释，稍后读里面是否会增加？
> 
> 当然会增加
> 
> > 或者说在 obsidian、稍后读和原页面任意一端进行批注的增删，其他两端是否会修改？
> 
> 如果你说的是 在 Obsidian 中继续标注的话，当然也都是双向同步。

哈哈，好的，谢谢，先过节，剩下的过完节再说😁元宵快乐！

**Comment by Kenshin** [comment]
哈，元宵快乐~

**Comment by Kenshin** [comment]
嗨，这个页面我测试了下，是因为页面结构有问题导致加载标注失败造成的。

目前没有好的解决办法，但应该只是个例，我先 Mark 下这个问题。

**Comment by Kenshin** [comment]
哈，抱歉，刚才的回复发错 Issues 了，我直接删除了 😂

**Comment by Kenshin** [comment]
> 我需要把simread的整个文件夹放在ob库下的文件夹里面吗，可以两边分开放吗？

可以的，留意好同步助手设置的路径就行了（一共两个路径）

> 但是想通过某条标注查看原文显示的是404不存在。

下图所示的路径设置错误造成的

<img width="673" alt="image" src="https://user-images.githubusercontent.com/81074/216876501-7cbaa7d7-5182-4a84-9cff-a313d7a4d6aa.png">

> 然后在阅读的时候加入稍后读，点击进入稍后读发现，稍后读并没有本地的按钮，我打开阅读模式并没有显示全文，文章好像没有下载下来。

跟上面的问题一样，都是导出目录设置错误造成的。

> 当我打开阅读模式，进行批注的时候，批注可能以json格式存储在浏览器缓存中？

如果使用了同步助手的自动同步，则会保存在本地；否则就是 Chrome 里面。

关于配置文件的细节建议看看 https://www.yuque.com/kenshin/simpread/ebwu7g

> 这里面SimpRead.json文件有什么用吗
simread.json文件里面似乎除了对简悦配置文件的保存外好像还有一些注释的保存。

`simpread_config.json` 是用户的数据文件，你在简悦中的一切内容都保存这里，同样可以看下上面的链接。

> obsidian的simpRead插件打开本地快照后标注后自动生成新的标注md和json文件覆盖本地？

是的。

> 在稍后读那个环节，读取的文件是本地离线文件还是坚果云端的文件？

本地离线对应文件夹放在了坚果云同步目录的话，它们就是一个文件。

**Comment by Nadir-Echo** [comment]
> > 我需要把simread的整个文件夹放在ob库下的文件夹里面吗，可以两边分开放吗？
> 
> 可以的，留意好同步助手设置的路径就行了（一共两个路径）
> 
> > 但是想通过某条标注查看原文显示的是404不存在。
> 
> 下图所示的路径设置错误造成的
> 
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/81074/216876501-7cbaa7d7-5182-4a84-9cff-a313d7a4d6aa.png">
> 
> > 然后在阅读的时候加入稍后读，点击进入稍后读发现，稍后读并没有本地的按钮，我打开阅读模式并没有显示全文，文章好像没有下载下来。
> 
> 跟上面的问题一样，都是导出目录设置错误造成的。
> 
> > 当我打开阅读模式，进行批注的时候，批注可能以json格式存储在浏览器缓存中？
> 
> 如果使用了同步助手的自动同步，则会保存在本地；否则就是 Chrome 里面。
> 
> 关于配置文件的细节建议看看 https://www.yuque.com/kenshin/simpread/ebwu7g
> 
> > 这里面SimpRead.json文件有什么用吗
> > simread.json文件里面似乎除了对简悦配置文件的保存外好像还有一些注释的保存。
> 
> `simpread_config.json` 是用户的数据文件，你在简悦中的一切内容都保存这里，同样可以看下上面的链接。
> 
> > obsidian的simpRead插件打开本地快照后标注后自动生成新的标注md和json文件覆盖本地？
> 
> 是的。
> 
> > 在稍后读那个环节，读取的文件是本地离线文件还是坚果云端的文件？
> 
> 本地离线对应文件夹放在了坚果云同步目录的话，它们就是一个文件。

好滴好滴，麻烦啦！我这就去调整调整

**Comment by Kenshin** [comment]
小事情，有任意疑问随时反馈~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Nadir-Echo** [comment]
> 小事情，有任意疑问随时反馈~
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

哈，已五星评价！
