### ISSUE TITLE
搜索引擎页面未显示简悦稍后读检索结果

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5129]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
- windows10
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
brave
- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**
搜索时没显示结果。
https://www.notion.so/619b68d4a9184080a9429f24724e8c0a
这是稍后读中收藏的文章
我在google中搜索”获取信息，组织只是“，打了两个错别字，google自动匹配，然后点击“显示的是以下查询字词的结果”，这样是显示不出来的，
![image](https://user-images.githubusercontent.com/86950349/216810158-576a6e6d-e069-46e9-8b40-4d2b126e859b.png)
![image](https://user-images.githubusercontent.com/86950349/216810174-9110ba77-d7bb-4746-ae16-843769848d32.png)

但是直接搜索”获取信息,组织知识“第一次显示出来了。我刚刚想要重现一下这个场景又试了一次，现在直接搜索又不行了
![image](https://user-images.githubusercontent.com/86950349/216810249-d0ae8f7f-6c20-4a9d-a20c-c06dd64f3b74.png)
![image](https://user-images.githubusercontent.com/86950349/216810280-63d02c14-e421-48e5-ab99-eb0fc2712cc6.png)

搜索“获取信息”好像又可以
![image](https://user-images.githubusercontent.com/86950349/216810305-1ec4221d-6fb5-4aa0-a72a-6af414a6c41d.png)

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
> 我在google中搜索”获取信息，组织只是“，打了两个错别字，google自动匹配，然后点击“显示的是以下查询字词的结果”，这样是显示不出来的，

Google 可以修正错误错误后的显示逻辑跟直接输入的显示逻辑不同，简悦是根据 Google URL 的变化得到的搜索关键字。

我收藏了你给出的 URL，并在 Google 搜索 `获取信息，组织知识` 是没问题的。

![image](https://user-images.githubusercontent.com/81074/216814338-2e0ecca0-75dc-477b-9d7c-20361bb17f4f.png)

所以，建议多测试下，试试不同的搜索内容，看看是否可以稳定复现（仅限搜索标题）

**Comment by Nadir-Echo** [comment]
嗷嗷，好的，感谢

**Comment by Kenshin** [comment]
小事情 😄

**Comment by Kenshin** [comment]
方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Nadir-Echo** [comment]
> 

hhh,这就去五星评价👍

**Comment by Kenshin** [comment]
哈，抱歉，没留意到是一个人 😂

**Comment by Nadir-Echo** [comment]
> 哈，抱歉，没留意到是一个人 😂

😀
