### ISSUE TITLE
阅读模式相关使用疑问

### ISSUE THREAD

**Issue by SrSh-notme** [Kenshin/simpread#5130]
1. 稍后读界面读取已离线保存的CNKI页面有问题，会自动跳转登录；直接打开离线Html文件则没有错误。如下图，

![cnki](https://user-images.githubusercontent.com/48594308/216813306-7c9f3d0f-822c-449a-bdd3-b1986249299c.gif)

2. 公众号阅读模式格式丢失；加粗标题什么的都没有了。
原界面：
![Snipaste_2023-02-02_12-51-34](https://user-images.githubusercontent.com/48594308/216813330-1081dd55-97f1-430a-88a4-1dcd81c4f6d9.png)
解析后界面：
![Snipaste_2023-02-02_12-51-23](https://user-images.githubusercontent.com/48594308/216813334-cd06d9b6-9efc-4013-8a70-76951f4b1724.png)

**Comment by Kenshin** [comment]
> 问题1

我不太方便使用 CNKI，看看你是否可以稳定复现？

> 问题2

你可以试试换个主题，比如模式的主题，如果还是不行的话，则是：这些粗体使用了内置 CSS 样式的问题，也就是说本身这个方式就不是正确的使用方式，所以在简悦中被删除掉了。

你可以关闭下图所示的两个选项

<img width="977" alt="image" src="https://user-images.githubusercontent.com/81074/216814637-51b8225a-b9c3-4438-947f-7a49fe79769a.png">

**Comment by Kenshin** [comment]
补充下：正常显示知网的话，需要安装这个插件 https://github.com/Kenshin/simpread/discussions/3537

**Comment by SrSh-notme** [comment]
> 补充下：正常显示知网的话，需要安装这个插件 #3537
关于问题1：
问题是复现的，很神奇，理论上应该是读取本地的离线文件，但是读取离线文件后立马跳转到知网登录。知网的插件是安装的，使用也正常。就是在稍后读界面会跳转到知网登录。

关于问题2：
关闭这两个模式后，微信公众号文章标题、文字加粗等还是不会显示。

**Comment by Kenshin** [comment]
> 问题1

把这个 HTML 发给我。（需要改名为 `.txt` ）

> 问题2

把 URL 给我。

**Comment by SrSh-notme** [comment]
问题1：
[45-燃气空调于商业综合体的推广策略研究.txt](https://github.com/Kenshin/simpread/files/10659844/45-.txt)

已把后缀名从html改为txt

问题2：
https://mp.weixin.qq.com/s/PiAK7Oe0-gFmqU0Krg6W3Q

**Comment by Kenshin** [comment]
> 问题2

按照我说的是没问题的，看下图

<img width="2179" alt="image" src="https://user-images.githubusercontent.com/81074/216907112-149c7e7b-2c18-4a31-bf38-24dc46b3d795.png">

> 问题1

确实如此，可能这个 HTML 中仍含有某些特定代码，但你可以使用 http://localhost:7026/reading/45 的方式来解决，打开这个链接，然后点击进入标注模式


正常标注即可，同时会更新本地 HTML 与标注。

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/81074/216908675-13b72e2f-e191-4a82-8ffd-af5d3199d850.png">

**Comment by SrSh-notme** [comment]
> > 问题1
> 
> 确实如此，可能这个 HTML 中仍含有某些特定代码，但你可以使用 http://localhost:7026/reading/45 的方式来解决，打开这个链接，然后点击进入标注模式
> 
> 正常标注即可，同时会更新本地 HTML 与标注。
> 
> <img alt="image" width="1360" src="https://user-images.githubusercontent.com/81074/216908675-13b72e2f-e191-4a82-8ffd-af5d3199d850.png">

极速版在这标注好像只能开启连续标注才能用，不能右键标准。

就是在标准的稍后读界面里头，能不能让插件默认直接读取打开本地的html文件，在没有本地文件的情况下才做原网页的解析，不用重新再解析下，这样就不会跳转了。极速版的分类管理功能还是稍微差点。

**Comment by Kenshin** [comment]
> 能不能让插件默认直接读取打开本地的html文件，在没有本地文件的情况下才做原网页的解析

目前就是这样的，进入稍后读左下角触发器

<img width="713" alt="image" src="https://user-images.githubusercontent.com/81074/218428471-354b212f-5c63-46ac-890e-51bb7b1f965f.png">

我复现的时候就是稍后读读的本地快照。
