### ISSUE TITLE
自动化增强插件设置保存成功后刷新页面又重置了，已经关闭云盘同步

### ISSUE THREAD

**Issue by monotone** [Kenshin/simpread#5132]
![image](https://user-images.githubusercontent.com/4949550/216819243-1f7f4687-bbea-481f-80b6-520fe4289131.png)

**Comment by Kenshin** [comment]
如果关闭自动同步的话，试试修改冰保存后重启浏览器。

**Comment by Kenshin** [comment]
另外，可以使用 https://www.yuque.com/kenshin/simpread/fcw60u 彻底解决开启自动同步后插件无法保存的问题。

**Comment by monotone** [comment]
> 另外，可以使用 https://www.yuque.com/kenshin/simpread/fcw60u 彻底解决开启自动同步后插件无法保存的问题。

这个试过，之前导出到notion插件不生效就这么解决的。但是没有解决导出到notion增强插件安装后看不到的问题

**Comment by monotone** [comment]
> 

重启后还是一样的。。

**Comment by Kenshin** [comment]
应该没问题。

实在不行，就先禁用「插件管理器」然后取消自动同步，再安装需要的插件，并配置。

配置成功后再重开自动同步。

**Comment by monotone** [comment]
> 

测试了一下，就是同步助手里，同步模块的开启的情况下会导致这个自动增强插件的保存失效
