### ISSUE TITLE
如何控制导入到obsidian的时候，全文和标注在不同的目录？

### ISSUE THREAD

**Issue by monotone** [Kenshin/simpread#5133]
我看同步助手里有个增强导出目录配置，看介绍是配置成{"extension":"assets", "path":"/ xxxxx/obsidian/SimpRead/refs", "type":"page"}表示导出md格式的原文时的目录。但是实际并没有啥用。

BTW，一直有点搞不清到底导出到本地和导入到 Ob 的配置是不是共用，同步助手里的配置到底是谁对生效

**Comment by Kenshin** [comment]
> {"extension":"assets", "path":"/ xxxxx/obsidian/SimpRead/refs", "type":"page"}

这个方案是没问题，看如何使用它。
所以，你导入到 Obsidian 的方式是什么？

**Comment by monotone** [comment]
> 

为了避免出问题，我现在都是点击阅读模式-》行动-》插件触发：导入md+assets到obsidian。产生的结果跟“导入到obsidian”插件里的选项设置一样。

**Comment by Kenshin** [comment]
明天回复你，

**Comment by monotone** [comment]
> 

好的

**Comment by Kenshin** [comment]
首先实现这个功能的前提：需要安装 [导出 assets + md](https://github.com/Kenshin/simpread/discussions/4041) 这个插件。

原因：因为导入到 Obsidian + 导入方式3，使用了 Obsidian 插件 SimpRead Sync，所以无法使用你提到的 https://github.com/Kenshin/simpread/issues/5133#issuecomment-1417800620 方式。

<img width="619" alt="image" src="https://user-images.githubusercontent.com/81074/216879631-f054f02f-9941-4ec1-9279-52ad57b8b53f.png">

***

> 因为看你的动手能力不错，直接给出关键信息，留意前提，二选一：

1. 关闭同步助手的自动同步以及禁用插件管理器。

2. 已安装并配置插件管理器。

3. 在操作前重启浏览器并仅开一个 Tab e.g. https://sspai.com/post/69972

4. 你已经配置并成功可以使用 **导入到 Obsidian + 导入方式3**。

操作步骤：（其实很简单，只是我截图的比较详细而已。

1. 安装 [导出 assets + md](https://github.com/Kenshin/simpread/discussions/4041) 

2. 设定 `"type":"page"` 方式，就按照你的路径方式设置就行

   <img width="672" alt="image" src="https://user-images.githubusercontent.com/81074/216880333-7cb339ca-6e30-4c71-b382-9a3f3cd83cc4.png">

5. 关闭 Obsidian 导入全文功能

   <img width="629" alt="image" src="https://user-images.githubusercontent.com/81074/216879951-661065c1-1636-4ac3-ab36-502acfa37412.png">

6. 将 导出 assets + md 加入自动化

    <img width="543" alt="image" src="https://user-images.githubusercontent.com/81074/216880041-af7c1512-2d2d-47c4-aa26-10606ed34ada.png">

7. 选项页 → 服务 → 自动化，删除跟 Markdown 有关的任何自动化方案。

重启浏览器，并仅开一个 Tab ，检查上述步骤是否已生效，如无误的话，使用快捷键 `d d` 加入稍后读，这样就能生效了。

如下图所示：

<img width="609" alt="image" src="https://user-images.githubusercontent.com/81074/216880857-b508d151-81a6-49fc-9613-a5bb84d58b65.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/81074/216880814-b4cb9200-1dd5-406e-8f04-84ade3313505.png">
