### ISSUE TITLE
标注完成后的反向链接为什么是空的？

### ISSUE THREAD

**Issue by monotone** [Kenshin/simpread#5134]
![image](https://user-images.githubusercontent.com/4949550/216819581-0806f71a-3901-4e97-a40e-f0753b5a7c7c.png)
我的理解，反向链接是不是应该指向原文？

**Comment by Kenshin** [comment]
这里的「反向链接」是简悦中的概念，用来链接其他简悦的标注或稍后读。

不过，这个功能可能需要再「重构」下，但一般来说用户不会总到这个功能。
