### ISSUE TITLE
导入到obsidian里的原文中，没有像离线快照一样有标注

### ISSUE THREAD

**Issue by monotone** [Kenshin/simpread#5135]
![image](https://user-images.githubusercontent.com/4949550/216820047-69511e78-a319-47fb-b90c-6a056ef61fa8.png)
如图，我的理解既然原文快照的 Html 带有标注，那么导入到ob里的原文应该也能带有标注底色？

**Comment by Kenshin** [comment]
Obsidian 是 Markdown 格式，并不支持标注语法…

虽然有变种 Markdown 语法支持标注，但仍并不好用。

**Comment by monotone** [comment]
> Obsidian 是 Markdown 格式，并不支持标注语法…
> 
> 虽然有变种 Markdown 语法支持标注，但仍并不好用。

貌似markdown里可以嵌入原生html吧，是不是一种方案

**Comment by Kenshin** [comment]
算是可以的，但一般不会这么用…
