### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by wangshuyu** [Kenshin/simpread#5137]
发生问题的地址: <https://alidocs.dingtalk.com/spreadsheetv2/68KYawjgWfYeQxMy/edit?dentryKey=68KYawjgWfYeQxMy

**Comment by wangshuyu** [comment]
钉钉表格无法获取

**Comment by Kenshin** [comment]
嗨，这类页面是不会被适配的，我直接关闭这个 issues 了。
