### ISSUE TITLE
快捷键是否可以支持自定义 

### ISSUE THREAD

**Issue by wangshuyu** [Kenshin/simpread#5138]
例如: 保存到语雀操作
操作流程:  切换阅读(AA)---快捷键(SR)--语雀(YQ)
需要操作3次, 是否在阅读模式下, 按一次快捷键直接保存语雀呢, 例如: YY, 类似快捷键还是比较方便的, sr+快捷键 太憋手啦

**Comment by Kenshin** [comment]
可以试试 https://github.com/Kenshin/simpread/discussions/1600 

这么做的原因是：避免跟其它全局类的扩展产生干扰。
