### ISSUE TITLE
会员模式下, 配置同步: 是否可以支持自动同步坚果云呢

### ISSUE THREAD

**Issue by wangshuyu** [Kenshin/simpread#5139]
1. 这个同步坚果云功能是非常方便的, 我是老坚果云用户
2. 但发现会员模式, 还是需要手动点击同步,  
3. 是否可以考虑自动同步坚果云呢
4. 新的强制覆盖老配置, 这样同步就无感了 体验能好不好哈

**Comment by Kenshin** [comment]
可以实现自动同步（坚果云），详见 [自动同步](https://simpread.pro/docs/#/%E8%87%AA%E5%8A%A8%E5%90%8C%E6%AD%A5)

也就是需要同步助手，如果不需要使用同步助手的话，暂时仅支持手动同步。
