### ISSUE TITLE
markdown增强模板无法进行修改配置

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5142]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
windows10
- 浏览器版本 **e.g. Chrome 78.0.3904.108**
brave
- 简悦版本 **2.0.0**
2.0.0
- 发生问题的地址 <请填写你的地址l>
markdown增强导出页面
**请描述你的问题**
想要编辑markdown增强导出格式，可是无法粘贴模板，粘贴不上去并且一粘贴，控制台就会报一堆的错
GIF：https://s3.bmp.ovh/imgs/2023/02/06/af471025678f2943.gif
我关掉了自动同步以后，又试了两次结果也是一样的。
> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**
![image](https://user-images.githubusercontent.com/86950349/217008231-495982f4-f652-4074-b245-7ee00125d871.png)

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Nadir-Echo** [comment]
欧克，解决了，在notion下的页面会出现这个问题，换个页面进行修改就可以了....😂不着调啥bug，可能跟notion适配网站有关？

**Comment by Kenshin** [comment]
恭喜自救成功。

一般来说很多页面的 JS 都会比较霸道，尤其是国外的...

所以，简悦的大部分插件操作我都建议在少数派上测试，非常「温和」，且因为图文等因素，测试效果也是最好的，可以用来排除其它因设置造成的测试干扰。
