### ISSUE TITLE
印象笔记导入失败

### ISSUE THREAD

**Issue by yxtimes** [Kenshin/simpread#5145]
发生问题的地址: <https://sspai.com/post/77938>
少数派我记得之前是可以导入的,但不知道为什么这次不行.如果需要我提供什么信息辅助判断,可直接回复,多谢

**Comment by Kenshin** [comment]
嗨，印象笔记目前确实有点问题，我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
