### ISSUE TITLE
你好，无法授权印象笔记

### ISSUE THREAD

**Issue by zhangxunxum4** [Kenshin/simpread#515]
![未命名图片](https://user-images.githubusercontent.com/43306366/58518719-f389d800-81e2-11e9-95ff-083885cdc5fa.png)
之前授权过简悦使用印象笔记，后来重新下载chrome之后发现简悦里的授权消失了（但从印象笔记端仍然可以看到对简悦的授权）于是尝试重新授权，把印象笔记对简悦的授权取消了，还是不可以....不知道如何解决？

**Comment by Kenshin** [comment]
取消授权 → 意味着删除对应的 token
取消授权后，会有提示「也同时解除对简悦的授权」，地址在 https://app.yinxiang.com/AuthorizedServices.action

这个 token 与 `印象笔记端仍然可以看到对简悦的授权` 没有关系。

***

第三个提示，是因为 `由于临近月底导致其中一台服务器的配额满了` ...

所以这个服务关掉了... 三天后恢复。到时我会在这里通知你~  😌

**Comment by Kenshin** [comment]
嗨，授权服务已经可以使用，我将将关闭此 issue ~
