### ISSUE TITLE
关于 Obsidian SimpRead Sync 的使用疑问

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5150]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
- windwos

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>
https://www.notion.so/4d92410d370849c1be0bde496b6d60bb
**请描述你的问题**
在阅读产品沉思录对应的文章，做了对应的批注，然后加入稍后读，在稍后读中可以看到对应的标注，但是在ob中导入标注后，点击内部链接，显示404错误
![image](https://user-images.githubusercontent.com/86950349/217412791-53b23cf7-1ad4-4c02-8fee-7273b0e49375.png)

我不知道是哪一步出了问题，我删掉了稍后读里面的文章重新加入稍后读，结果是标注全没有了，ob还是404，无法显示原文。
在以往的issue中我找到了两点可能相关的问题，一个是在命名规则上我把标题开头的{{idx}}给删掉了，不知道是不是这个错误，我看了一下ob内部链接的地址最后的那部分是数字有关的东西，不知道对应的是不是就是idx。

（我检查了一下可能就是这个原因？）那么针对这个的话如果过我想清除idx，从1开始重新计算的话，我要怎么做把idx清零？强迫症难受死我了，因为之前配置这个，试过几篇文章，序号整体全部是乱的，idx还缺几个，中间还缺少了几篇文章。
第二个有可能的原因，我看了有篇issue里面写的好像是output里面只能有html文件？？我好像自动化导出的时候把md文件也放在里面了，这个有关系吗？
![image](https://user-images.githubusercontent.com/86950349/217414622-3168d9c0-d7db-4d94-82ef-9da2065f847b.png)

第二个问题是这个标注全部没有的问题，按道理来说我删除了稍后读，但是标注应该是还在的，我检查了output里面的文件，对应的文件，标注啥的都是在的，难不成是标注保留在json里面，然后加入稍后读里面，稍后读会读取json里面的标注数据，但是删除以后，json里面的标注数据也跟着一起删除了吗？

第三个问题是昨天遇到的了，标注过程中一直显示图片正在下载，这个我在关闭标注自动化中的下载离线html好像就没有问题了，但是这么一来有了个新的问题，我看了看下载下来的html，如果对应图片的链接失效了，那是不是我那个html的图片就无法显示了？这个有啥解决方案嘛？

**Comment by Kenshin** [comment]
> 点击内部链接，显示404错误

404 一般是针对快照文件夹（也就是 `output` ） 设置错误造成的。

根据下图所示

<img width="676" alt="image" src="https://user-images.githubusercontent.com/81074/217419228-ec61179f-1290-4d8c-aaf4-5eb7ad002bea.png">

检查下你自己的路径是否存在你的截图中对应的 HTML，一般叫做 `<id>-<title>.html` e.g.

`2648-告别航空传奇波音 747，「空中女王」正式谢幕.html`

关于这个功能可以看这个教程，对比下跟你有什么区别就好。

> 第二个问题

标注数据全部都保存在你的 `simpread_config.json` 里面，对标注的增删改就是操作 `simpread_config.json`  

> 第三个问题

当自动化选择离线 HTML 后，尽量不要使用标注功能，因为目前每标注一次，就重新下载一次图片。

非要这么做的话，把标注改为手动模式，当标注完毕后，手动导出标注和 HTML（这时就是离线 HTML + 标注）

**Comment by Nadir-Echo** [comment]
对，第一个问题就在于我命名导出是直接原标题导出<title>.html，id我给删掉了，那我加回来是不是应该就不会404了？

第二个问题，我删除稍后读会对simpread_config.json有影响吗？

**Comment by Nadir-Echo** [comment]
第一个问题我<id>加回来以后有没有办法把id归零我重新添加呀?

**Comment by Nadir-Echo** [comment]
第二个问题,我删除稍后读,并没有动标注,删除稍后读的话,是连着标注一起删除了是吗?

**Comment by Kenshin** [comment]
> 第二个问题,我删除稍后读,并没有动标注,删除稍后读的话,是连着标注一起删除了是吗?

是的

> 对，第一个问题就在于我命名导出是直接原标题导出<title>.html，id我给删掉了，那我加回来是不是应该就不会404了？

只要配置无误就一定没问题，你可以试试。

> 第一个问题我加回来以后有没有办法把id归零我重新添加呀?

暂时没有，ID 是个自增长的数值，不建议人为干预它，虽然我能 Get 你的点，比如 1 2 3 5 中间少了4 很难受，但其实无所谓 😂

**Comment by Nadir-Echo** [comment]
> > 第二个问题,我删除稍后读,并没有动标注,删除稍后读的话,是连着标注一起删除了是吗?
> 
> 是的
> 
> > 对，第一个问题就在于我命名导出是直接原标题导出<title>.html，id我给删掉了，那我加回来是不是应该就不会404了？
> 
> 只要配置无误就一定没问题，你可以试试。
> 
> > 第一个问题我加回来以后有没有办法把id归零我重新添加呀?
> 
> 暂时没有，ID 是个自增长的数值，不建议人为干预它，虽然我能 Get 你的点，比如 1 2 3 5 中间少了4 很难受，但其实无所谓 😂

哦哦,好的,谢谢!
