### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by babyansion** [Kenshin/simpread#5151]
发生问题的地址: <http://www.bjnsc.ceec.net.cn/art/2023/1/16/art_49993_2512772.html>

**Comment by Kenshin** [comment]
嗨，使用下面的方式即可解决。

<img width="463" alt="image" src="https://user-images.githubusercontent.com/81074/217418488-7a24cb33-f78c-4e93-bdd4-15f2f7f6e400.png">

**Comment by babyansion** [comment]
谢谢，解决了

**Comment by Kenshin** [comment]
哈，搞定就好~
