### ISSUE TITLE
导出 md + assets 格式 显示保存失败

### ISSUE THREAD

**Issue by MicroSharpAnt** [Kenshin/simpread#5153]
### 问题反馈：
我不知道问题出在哪。我使用typora记录内容，因为有将一些博客内容转为md格式并将其中的图片资源转为本地asset的习惯，所以我使用了**assets + md**这个插件。它需要我下载简悦助手，因此我也下载了，按照教程配置好了，然后测试了一些博客文档，都可以正常导出到本地。

于是我卸载了该插件，然后重新安装重新配置。依然没有效果。
我的配置如下：
操作系统：mac os 12.3 (21E230)
浏览器：版本 109.0.1518.78 (正式版本) (arm64)
插件：简悦 - SimpRead 2.2.0.520
简悦助手：1.1.4
我的设置如下：
助手设置：
![截屏2023-02-08 16 35 27](https://user-images.githubusercontent.com/49601537/217477326-a356d26d-4a37-4a37-bf13-665c729e28ee.png)

报错如下：
![截屏2023-02-08 16 37 03](https://user-images.githubusercontent.com/49601537/217477646-2dfdbe33-91e0-4781-8bf9-a9bf2500a9f6.png)

**Comment by Kenshin** [comment]
先自查下面的内容：

1. 选项页 → 账户 → 是否有加锁情况？如果有请使用 https://www.yuque.com/kenshin/simpread/sw4m21 解决。
2. 同步助手 → 通用 → 账户部分，是否存在你的 UID，如果没有说明 UID 「掉了」，重新授权

    ![image](https://user-images.githubusercontent.com/81074/217482163-0ac5ff02-d226-4f3e-8822-f307d5d5970b.png)

如果并没有问题的话：

1. 请给出 assets + md 这个插件的配置截图。

2. 在之前好使的时候，是否导出到 `output` 文件夹？

**Comment by MicroSharpAnt** [comment]
感谢作者及时的答复。
找到问题里，是简悦助手关闭了同步服务。因为我需要的功能在导出模块，同步模块写的是使网盘自动同步等功能，我暂时未用坚果云等网盘进行自动同步，所以关掉了同步服务，我没想到两者之间有依赖关系。

**Comment by Kenshin** [comment]
解决就好。

简悦不会无故出现之前好用（但感觉没有改动什么），突然就不好用的情况。

当然理论上来说这种情况也是会发生的，但只是极个别的情况造成的，甚至都算不上是概率问题，仅仅只是个例。

大多数情况都是用户改动了某些功能但自己忘记了（不自知）而已，这种情况占比大多数，也很正常。

> 关闭了同步服务

同步服务是同步助手运行的基石，大部分功能都依赖它，尤其是增强导出功能。

在后续的版本中我会逐步删除这个功能。（也就是默认是启用的。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
