### ISSUE TITLE
部分段落在阅读模式下无法自动换行

### ISSUE THREAD

**Issue by mimishy2000** [Kenshin/simpread#5155]
站点地址为：https://cloud.tencent.com/developer/article/1196220

重新选项高亮区域无效；
已同步最新官方主适配源；
页面是通过手动打开阅读模式的。

以上方法均无法解决。

**Comment by Kenshin** [comment]
嗨，这是这个页面的问题，看下图（不需要了解任何技术，单纯的比较左右两个图）

<img width="1973" alt="image" src="https://user-images.githubusercontent.com/81074/217497514-c3739c11-43c0-43dd-8458-4f15721aa05b.png">

试试下面的方式

```
sr-rd-content p {
    word-wrap: break-word;
    white-space: pre-wrap;
}
```

将上面的代码加入下图所示位置，并保存。

<img width="464" alt="image" src="https://user-images.githubusercontent.com/81074/217498396-598b0f27-fd5a-484a-a1c5-5faa51b6d87f.png">
