### ISSUE TITLE
点击稍后读，自动化并不会启动工作下载到本地

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5160]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
- windows10

- 浏览器版本 **e.g. Chrome 78.0.3904.108**
brave
- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

点击稍后读，自动化并不会启动工作下载到本地，我设置了下载markdown，html和离线html，加入稍后读后，我打开稍后读没有看到本地的图标，同样打开文件夹目录也没有对应的 文件。但是只要我进行了一处标注，标注的自动化还是工作的，会自动下载html和markdown。

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

加入稍后读自动化的前提：

1. 进入阅读模式
2. 使用快捷键 `d d`

具体细节 https://github.com/Kenshin/simpread/discussions/2362
