### ISSUE TITLE
Wikipedia的适配

### ISSUE THREAD

**Issue by Ravenightwing** [Kenshin/simpread#5161]
已经使用官方/第三方适配源，但是仍然会有一串很长的表头出现在阅读模式，希望能删除这些
<img width="960" alt="image" src="https://user-images.githubusercontent.com/73371424/217786523-0940a047-030a-4fad-875e-6f1c10e168f6.png">

*有的时候会有过长的表格，同时会影响观感
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/73371424/217786884-60b6bbf0-cc57-4021-b959-70e8fb7d3961.png">

**Comment by Kenshin** [comment]
收到，我明天看下，顺道把 URL 也给我~

**Comment by Ravenightwing** [comment]
> 

https://en.wikipedia.org/wiki/Nazi_persecution_of_the_Catholic_Church_in_Germany?useskin=vector

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，解决了此类问题。

<img width="760" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b73c24d8-41e8-4ef6-ae17-cb8b6bf06d53">

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
