### ISSUE TITLE
notion账号改变后如何更改授权账号？没有发现能更改授权的地方

### ISSUE THREAD

**Issue by littlewwwhite** [Kenshin/simpread#5166]

**Comment by Kenshin** [comment]
1. 登出你在 Notion 的账户。
2. 简悦 → 选项页 → 服务 → 关闭授权。
3. 重启浏览器
4. 登录新的 Notion 账户。
5. 简悦 → 选项页 → 服务 → 重新授权。

**Comment by littlewwwhite** [comment]
您好 notion 辅助增强 invite 步骤不显示刚刚创建的 integration 如何解决，也就是说无法邀请 integration 如何加入 notion

**Comment by Kenshin** [comment]
看这个链接下面的视频 https://www.yuque.com/kenshin/simpread/zx3bcz#K0G9x

另外，最好截图或录屏说明，这样才能准确定位你的问题。

单纯的理解你的问题：

即便是新注册的 Notion 账户也可以正常使用 integration （因为我这么使用过）除非 Notion 又改规则了...
