### ISSUE TITLE
点击登录，控制台会报错，点击不了，登录不了

### ISSUE THREAD

**Issue by Michael-py001** [Kenshin/simpread#5167]
**请说明发生问题的环境**

![image](https://user-images.githubusercontent.com/60598432/218076267-0f0b9fee-6ba7-4304-ba0c-460e6d24f8a8.png)

- 操作系统 ** Windows 10**

- 浏览器版本 **版本 109.0.1518.78 (正式版本) (64 位)**

- 简悦版本 **2.0.0**

- 发生问题的地址 extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**请描述你的问题**

点击登录，控制台会报错，点击不了，登录不了

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/60598432/218076267-0f0b9fee-6ba7-4304-ba0c-460e6d24f8a8.png)

**Comment by Kenshin** [comment]
1. 控制台保存跟你提到的问题无关。（不用理这个控制台报错...

2. 如果是新设备使用简悦的话，手动从坚果云下载到本地，再手动导入到简悦（这是最简单的方式。

PS：你截图的功能是没问题的，但最好使用方案2。

**Comment by Michael-py001** [comment]
可是这个报错的确影响到了某些地方的点击事件，这个登录不了是其中一个。
请问这是什么原因点击登录不了？点了之后右上角转了一下就没有了，控制台也没有看到发出登录请求，我一开始以为是服务器不行，过了一周再试还是这样子
方案二我有空再研究下

**Comment by Kenshin** [comment]
报错跟提到的功能无关…

登陆不了是因为需要开通 API 等相关功能才能使用，所以最好是我提到的方式。
