### ISSUE TITLE
在obsidian中进行标注后，之前保存的整片网页的md被自动删除

### ISSUE THREAD

**Issue by families** [Kenshin/simpread#5168]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows**

- 浏览器版本 **Chrome最新**

- 简悦版本 **最新**

- 发生问题的地址 <所有地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

按照官方配置教程，使用第三种方案，配合同步助手，这个流程设置完后，添加稍后读，正常导出1个html，和1个整片网页的md，然后标注，正常导出一个标注的md文件，再到obsidian中进行标注，之前保存的整片网页的md被自动删除，无法找回，最后就只剩下1个html和1个标注的md文件

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
> 之前保存的整片网页的md被自动删除，无法找回

应该不会有这个情况，除非你设置了某些功能。

1. 还是需要对比下跟官方教程在设置上的区别。

2. 多测试下，看是否可以稳定复现？比如使用 https://sspai.com/post/69972 测试。

> 再到obsidian中进行标注，之前保存的整片网页的md被自动删除

标注文件一般都是 `<id>-<title>@annote.md` 这样的名称，如果你不是这个名称，有可能会将全文 Markdown 替换。

下图是一个例子

<img width="420" alt="image" src="https://user-images.githubusercontent.com/81074/218080639-7e66382c-1afb-42e3-a0e2-aac645c550fd.png">

**Comment by families** [comment]
> > 之前保存的整片网页的md被自动删除，无法找回
> 
> 应该不会有这个情况，除非你设置了某些功能。
> 
> 1. 还是需要对比下跟官方教程在设置上的区别。
> 2. 多测试下，看是否可以稳定复现？比如使用 https://sspai.com/post/69972 测试。
> 
> > 再到obsidian中进行标注，之前保存的整片网页的md被自动删除
> 
> 标注文件一般都是 `<id>-<title>@annote.md` 这样的名称，如果你不是这个名称，有可能会将全文 Markdown 替换。
> 
> 下图是一个例子
> 
> <img alt="image" width="420" src="https://user-images.githubusercontent.com/81074/218080639-7e66382c-1afb-42e3-a0e2-aac645c550fd.png">

开始
![image](https://user-images.githubusercontent.com/25345830/218083583-9a575c92-9af5-40b9-bef8-64cef4bac578.png)
浏览器加入稍后读
![image](https://user-images.githubusercontent.com/25345830/218083824-f79826b6-c32d-4aca-8313-11e1c9b6d719.png)
浏览器上面添加标注
![image](https://user-images.githubusercontent.com/25345830/218084110-1a6b1dec-6842-40bc-8819-85a2c1cdbd6b.png)
再到obsidian标注后，自动删除了全文md文件
![image](https://user-images.githubusercontent.com/25345830/218084383-f2459bdd-6a94-4bc9-9ab1-b84634b5108d.png)

**Comment by Kenshin** [comment]
emmm 

output 里面有个 Markdown 的全文？标注在另外的文件夹中？

还是把全部相关设置都截图给我。

**Comment by families** [comment]
> emmm
> 
> output 里面有个 Markdown 的全文？标注在另外的文件夹中？
> 
> 还是把全部相关设置都截图给我。

![image](https://user-images.githubusercontent.com/25345830/218096396-162de12d-d2ee-4fd2-a3ab-2d3d11a0f3a8.png)
因为上面图片的配置，所以导出的md全文和html都在output里面，你直接告诉我怎么写同步助手那个配置，把md全文放到其他目录？我现在写的不起作用，看下面：
![image](https://user-images.githubusercontent.com/25345830/218097086-7ec35bc9-971c-4b76-b04e-8824711180d9.png)

**Comment by Kenshin** [comment]
增强导出的话，Windows 的话应该是两个斜杠 `\\`
