### ISSUE TITLE
没法按原来的颜色显示

### ISSUE THREAD

**Issue by xyxlkb** [Kenshin/simpread#517]
原本的文本有些字是标红的 可是到阅读模式之后全都变成黑色了，就没有原本的重点 
加粗倒是会有
为什么啊

**Comment by Kenshin** [comment]
请给出 URL 

> 原本的文本有些字是标红的 

如果它用了不标准的结构显示 `红字` 是会被删除的。

***

另外，你可以看看 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎) 
里面有关于 **如何显示红字** 的一些办法。

**Comment by Kenshin** [comment]
如果没有疑问的话，我关闭此 issue 了~

**Comment by QuentinHsu** [comment]
掘金小册中的“文字标红”样式，在简阅阅读模式下被移除，我在尝试关闭词法分析引擎的纯粹模式后，依旧无法显示。

对应原文的 ELement Content：

```html
<span style="color:red">内连接中的WHERE子句和ON子句是等价的</span>
```

**Comment by Kenshin** [comment]
@QuentinHsu 

`<span style="color:red">` 是会被移除的，因为它的结构不规范，换个角度说，简悦没法知道哪些 `<span style="color:red">` 是规范的，哪些不是，所以全部都移除了。
