### ISSUE TITLE
导入到notion和导入到notion增强的使用疑问

### ISSUE THREAD

**Issue by Robs87** [Kenshin/simpread#5170]
经常多配置两次就出状况了。导入到notion和自由选不同的page，而导入到notion辅助增强是要database id,如果用nt换页面，导入到notion辅助增强不换id，是不是就辅助增强用不了。实际上试了下确实是这样的。

**Comment by Robs87** [comment]
我的需求主要是根据分类，把网上、公众号上不同的文章导入不同的database，又想要导入到notion可以换page，又想要导入notion辅助增强的可以增加封面图标等功能。

**Comment by Robs87** [comment]
还有，大佬，ios端的，现在jsbox好像不能通过irl添加，然后你那个代码也复制不了，也就没法在jsbox中加阅读器，大佬，求解决下ios段的呀。顺带说下，我也买了高级账户。支持下大佬。

**Comment by Kenshin** [comment]
> 还有，大佬，ios端的，现在jsbox好像不能通过irl添加，然后你那个代码也复制不了，也就没法在jsbox中加阅读器，大佬，求解决下ios段的呀。顺带说下，我也买了高级账户。支持下大佬。

你好像在 Telegram 联络我了吧？我已经在 Telegram 回复你了。

1. 不需要 `simpread_config.json` 也能使用。
2. 随便使用任何方式将 `simpread_config.json` 传到你的 iOS 设备上就行。

> 我的需求主要是根据分类，把网上、公众号上不同的文章导入不同的database，又想要导入到notion可以换page，又想要导入notion辅助增强的可以增加封面图标等功能。

使用 https://github.com/Kenshin/simpread/discussions/4954 这个插件解决，它可以将不同的内容导入到不同的 Page。

也就是不使用扩展端的 Notion 功能而使用链接提到的插件。

**Comment by Robs87** [comment]
大佬回复的好快！

**Comment by Kenshin** [comment]
哈，一般情况下只要在工作 Issues 差不多半个小时左右就会回复。

否则的话，一天下来堆积太多反而耽误时间 😂
