### ISSUE TITLE
关于保存epub到本地的问题

### ISSUE THREAD

**Issue by niuniuyer** [Kenshin/simpread#5171]
在卸载同步助手后，使用不经过同步助手的保存为epub，提示保存至本地epub显示保存成功，但实际并未能在任何文件夹内找到
- 操作系统 **Windows10**

- 浏览器版本 ** 360极速21.01150**

- 简悦版本 **2.2.0**

**Comment by Kenshin** [comment]
嗨

>  不使用同步助手导出 Epub 的话，会有问题，因为其中的一个免费服务造成的，所以暂时无法使用非同步助手导出 Epub 方案，后续我会再找个替代方案。

至于你说的问题，在选项页 → 服务 → 增强导出，把下图这些关闭就行了。

<img width="856" alt="image" src="https://user-images.githubusercontent.com/81074/218293836-d7e434ce-e3d4-43a5-b79d-ea106385b25c.png">

另外，还有自动同步功能

<img width="866" alt="image" src="https://user-images.githubusercontent.com/81074/218293844-fa018da3-d580-414e-873d-d7ba938ff786.png">
