### ISSUE TITLE
关于语雀阅读辅助增强的疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5174]
你好，我按照步骤一步步来了但还是不行，还是原本的阅读模式样式，重复几次还是不行，步骤如下：
1. 安装语雀阅读辅助增强；
2. 把 yuque.com 添加到了 延迟加载列表；
3. 刷新页面，把网页拉到最下面；
4. 进入阅读模式 并 点击“语雀阅读辅助增强”，但依旧毫无反应。

_Originally posted by @Alice-Shi in https://github.com/Kenshin/simpread/discussions/4380#discussioncomment-4949697_

**Comment by Kenshin** [comment]
@Alice-Shi

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

建议详细描述你的问题或者截图给我，另外把出问题的 URL 也一起给我。

还有试试安装这个适配规则 https://simpread.ksria.cn/sites/details/QF22ZcE8n5

**Comment by Alice-Shi** [comment]
> 还有试试安装这个适配规则 https://simpread.ksria.cn/sites/details/QF22ZcE8n5

这个插件已经安装了呢。并且检查了插件管理的设置页面，此插件有安装成功。

昨天再测试了一下，发现了一个问题：插件运行不稳定。表现在于 有的语雀网页进入阅读模式后，在“动作”选项卡下面有**语雀阅读辅助增强插件**并运行成功(根据页面版式可知)，但有的网页却无法在在“动作”选项卡下面找到该插件，并且与打开的语雀网页文章长短无关，因为发现有的长文是ok的，有的短文反倒不ok，且感觉随机出现。

测试用的网页有：
《知识库》[🌐](https://www.yuque.com/kenshin/simpread/lglfy2)
《永久链接》[🌐](https://www.yuque.com/kenshin/simpread/egvhm7)
《一站式开通开放平台》[🌐](https://www.yuque.com/kenshin/simpread/ieu1w6)

但是今天早上打开数篇语雀网页又没有发现任何问题 😂

**Comment by Kenshin** [comment]
应该没问题的，看下图箭头所示跟你的是否一致？

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/81074/218654336-4ea35c87-44e1-4120-b3a1-3b17c4ffedbe.png">

**Comment by Alice-Shi** [comment]
> 应该没问题的，看下图箭头所示跟你的是否一致？
> 
> <img alt="image" width="1603" src="https://user-images.githubusercontent.com/81074/218654336-4ea35c87-44e1-4120-b3a1-3b17c4ffedbe.png">

一致的。没事了现在，今早的多次测试都是 ok 的，假如再次出现问题再提交 issue 🙂️

**Comment by Kenshin** [comment]
okay 再有问题随时在这里提~

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Alice-Shi** [comment]
已好评，谢谢你的及时回复呀！对了，想问一下这里 《配置库 高级版》[🌐](https://www.yuque.com/kenshin/simpread/wq35mh#ff0faf18) 用苹果 iCloud 同步可以吗？

**Comment by Kenshin** [comment]
哈哈，谢好评 😄

> 问一下这里 《配置库 高级版》[🌐](https://www.yuque.com/kenshin/simpread/wq35mh#ff0faf18) 用苹果 iCloud 同步可以吗？

可以的，只要不使用 API 功能的话，哪个网盘都无所谓。

但 iCloud 的同步感觉不是很好 😂

**Comment by moyu0** [comment]
作者你好，我按照说明安装了对应的插件和适配规则，站点集市适配源也显示启动，但是打开 https://www.yuque.com/cessstudy/kak11d/hfeef2 页面，下拉到最后，进入简阅后显示如下：
![image](https://user-images.githubusercontent.com/32016986/218776777-87c14980-9c35-4f2e-80ef-96281a2a51ce.png)

**Comment by moyu0** [comment]
> okay 再有问题随时在这里提~

作者你好，我按照说明安装了对应的插件和适配规则，站点集市适配源也显示启动，但是打开 https://www.yuque.com/cessstudy/kak11d/hfeef2 页面，下拉到最后，点击进入简阅模式后显示如下：
![image](https://user-images.githubusercontent.com/32016986/218776777-87c14980-9c35-4f2e-80ef-96281a2a51ce.png)

**Comment by Kenshin** [comment]
@Alice-Shi 

API 目前主要是为了可以在手机端收集 URL，因为有很多其它「替代方案」，所以如果你没有这方面诉求的话，完全可以不使用 API。

非要折腾的话，也不是不行，将坚果云的同步文件夹设置到 iCloud 中即可。

**Comment by Alice-Shi** [comment]
> 非要折腾的话，也不是不行，将坚果云的同步文件夹设置到 iCloud 中即可。

哇，那把 Dropbox 同步文件夹设置到 iCloud 中也行吗？

**Comment by Kenshin** [comment]
> 哇，那把 Dropbox 同步文件夹设置到 iCloud 中也行吗？

无所谓，但简悦的 API 仅支持坚果云。

不过，有其他用户反馈 iCloud 不是太好用。（我是没有这么做~

**Comment by Alice-Shi** [comment]
> 简悦的 API 仅支持坚果云。

谢谢告知，我会好好考虑的。期待简阅的 API 支持 Dropbox

**Comment by Alice-Shi** [comment]
发现一个 bug：作了标注的语雀页面，之后再次以阅读模式打开，点击标注后无法跳转到 网页对应位置
操作页面 👉 《Obsidian SimpRead Sync - 一站式文献笔记解决方案教程》🌐 https://www.yuque.com/kenshin/simpread/fr8zo5
<img width="480" alt="image" src="https://user-images.githubusercontent.com/22544951/219923406-b198e4f9-ddab-451d-8007-7e11dd309512.png">

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5174#issuecomment-1435872231

确实如此，也不算是 Bug，因为这个插件会整理语雀的内容，所以导致标注失败了。

目前暂时没有太好的解决方案，但你如果配置了 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7)，则可以使用：

1. 稍后读内标注。
2. [稍后读极速版](https://simpread.pro/docs/#/稍后读极速版) 标注

**Comment by Alice-Shi** [comment]
> 因为这个插件会整理语雀的内容，所以导致标注失败了

原来这样👌 
联想到用了 live editor 编辑的网页，当进行再次标注时，也会出现一样的问题，应该是一样的原因所致，解决方法也是一样的。

**Comment by Kenshin** [comment]
> 联想到用了 live editor 编辑的网页，当进行再次标注时，也会出现一样的问题，应该是一样的原因所致，解决方法也是一样的。那么，假如哪天网站作者 自己修改了自己的网页，也会出现一样的问题是吧？

是的，标注依赖与页面结构，如果页面结构改变了，当然标注失效了。

失效的只是定位而已，标注的信息不会有任何影响。

所以，简悦是基于本地文件系统的稍后读和标注产品，为了就是避免 404 的问题。

**Comment by Alice-Shi** [comment]
了解，那为了保持标注跳转的正常，对于语雀页面，我就在本地标注 👌

另外报一个 bug：同样是这个页面  👉 《Obsidian SimpRead Sync - 一站式文献笔记解决方案教程》🌐https://www.yuque.com/kenshin/simpread/fr8zo5
在保存为本地快照以后，打开其 `http://localhost:7026/unread/xxx` 页面，在100% 缩放视图下，**内嵌视频的显示**是不完整的 👉
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22544951/219937644-85503f1b-b94c-408b-a4ee-7fae97450713.png">
但假如缩小视图则可以 使得 整个视频完整，此时正文的字又太小啦 👉 
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/22544951/219937674-252ed48b-73d9-4b9b-ae71-5edef4719fbe.png">

**Comment by Alice-Shi** [comment]
> 简悦的 API 仅支持坚果云

但是我看 JSBox 支持的是 Dropbox 的 token 👉 《借助 JSBox，iOS 用户也可享受简悦带来的杂志般阅读体验 - 少数派》🌐https://sspai.com/post/44786。那简阅的 API 也是支持 Dropbox 的嘛？

**Comment by Kenshin** [comment]
> 但是我看 JSBox 支持的是 Dropbox 的 token 👉 《借助 JSBox，iOS 用户也可享受简悦带来的杂志般阅读体验 - 少数派》🌐[https://sspai.com/post/44786。](https://sspai.com/post/44786%E3%80%82) 那简阅的 API 也是支持 Dropbox 的嘛？

两回事 😂

1. JSBox 是早年间的作品，那个时候 Dropbox Token 还没有那么「恶心」。
2. 简悦早就说明了，目前 API 仅支持坚果云。（早年间确实支持 Dropbox）

**Comment by Alice-Shi** [comment]
这样😳 那么，现在 jsbox 还可以用吗

**Comment by Kenshin** [comment]
可以使用。

1. 我记得不需要 simpread_config.json 的话也可以直接使用。
2. 或者随便找个什么 App 把你的 simpread_config.json 放到根目录下也行。

**Comment by Alice-Shi** [comment]
可以写个具体的教程吗？
