### ISSUE TITLE
全文导入obsidian的文件后缀发生错误

### ISSUE THREAD

**Issue by CaiXuZao** [Kenshin/simpread#5175]
**发生问题的环境**

- 操作系统 **Windows 10 专业版19045.2486**

- 浏览器版本 **Chrome 110.0.5481.78**

- 简悦版本 **2.0.0**

- 简悦同步助手版本**1.1.4**

**问题：全文导入obsidian的文件后缀发生错误（发生错误前后简悦与obsidian以及同步助手配置没有改变）**
![image](https://user-images.githubusercontent.com/125122330/218360094-5639d327-8dee-4719-b885-f1673c30cef6.png)

**部分设置：**
1.模板辅助增强设置
(1) 反向链接标题：  
```
[[{{id}}-{{title}}@annote]]  
```

(2) 稍后读模板：  
``` 

---
title: "{{title}}"
alias: [<% if ( unread.note && unread.title != unread.note ) { %>"{{note}}",<% } %>"{{title}}"]
type: Simpread
tag: {{tags}}
---

# {{title}}
<% if ( unread.desc ) { %>
> [!summary] 描述
> <%- unread.desc %>
<% } %>
> [!md] Metadata
> **标题**:: "{{title}}"
> **日期**:: [[{{create|yyyy-mm-dd}}]]
<% if ( unread.refs ) { -%>
> **外部引用**:: {{refs}}
<% } %>
## Annotations
<% if ( unread.annotations.length > 0 ) { %>
{{annotations}}
<% } %>

```

(3) 标注的模板：  
```
<%
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
color = colors[ annote.color ];
-%>


> [❤❤](<{{an_int_uri}}>) <mark style="background-color: <%= color %>">Highlight</mark> {{an_tags}}
{{{html_format|>|{{an_html}}}}}
<% if (annote.note) { -%>
> - {{an_note}}
<% } %>
^sran-{{an_id}}

```
2.
![image](https://user-images.githubusercontent.com/125122330/218363914-5471b821-bdd9-4df1-ba81-414d27cd72c6.png)

3.
![image](https://user-images.githubusercontent.com/125122330/218364126-0f55d2b2-f4f7-4224-81ff-18e3549b2c46.png)

4.
![image](https://user-images.githubusercontent.com/125122330/218364137-abd96149-9d67-4faf-b575-55fbf262f659.png)

5.
![1676259625893](https://user-images.githubusercontent.com/125122330/218365242-d986b464-f24f-413c-ac08-515bddcadc37.png)

**Comment by Kenshin** [comment]
emmm

你试试加入稍后读后在导入到 Obsidian 是否仍有这个问题？

**Comment by CaiXuZao** [comment]
测试：
1.（不使用自动化操作）单独加入稍后读然后再单独导入obsidian则导入的文件正常
2.（不使用自动化操作）对文章某区域选中单独发送，导入obsidian的文件有后缀错误，并且只生成html的

**Comment by CaiXuZao** [comment]
> emmm
> 
> 你试试加入稍后读后在导入到 Obsidian 是否仍有这个问题？

测试：
1.（不使用自动化操作）单独加入稍后读然后再单独导入obsidian则导入的文件正常
2.（不使用自动化操作）对文章某区域选中单独发送，导入obsidian的文件有后缀错误，并且只生成html的

**Comment by CaiXuZao** [comment]
> 谢谢提供详细测试过程。
> 
> > 对文章某区域选中单独发送
> 
> 是选择某些区域并进入阅读模式（并没有加入稍后读）然后导入 Obsidian 吗？如果是的话，我测试了下，是没问题的。
> 
> <img alt="image" width="288" src="https://user-images.githubusercontent.com/81074/218401077-5ac666ac-c825-436d-b5b6-91ea86fa2d1f.png">
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/81074/218400970-12995c6e-25b9-4e93-bc24-9db5d1d2164c.png">
> 
> 另外 [#5175 (comment)](https://github.com/Kenshin/simpread/issues/5175#issue-1581590063) 第五个截图，有点问题。
> 
> 如果你使用了 SimpRead Sync 导入方式
> 
> <img alt="image" width="608" src="https://user-images.githubusercontent.com/81074/218401539-b14b70ef-b508-448c-a064-1e85ef80f3c6.png">
> 
> 不需要设置红框的内容，因为 SimpRead Sync 直接走了 Obsidian SimpRead Sync 插件的方式。
> 
> <img alt="image" width="658" src="https://user-images.githubusercontent.com/81074/218401625-05ca2d26-eb25-4a0b-aa69-6bfd6f5de190.png">






**抱歉，由于刚使用，实现同步功能的也是跟着别人的视频教程来的，所以自己对某些配置能产生什么功能并不太清楚，并且在描述上可能会不太准确。我重新进行了测试，并汇总了出现的现象。**

---

**测试1.**（双击A）进入阅读模式，（双击D）加入稍后阅读。
**现象：**导入obsidian的文件后缀有错误。
![Pasted image 20230213164221](https://user-images.githubusercontent.com/125122330/218421665-03f1d455-d3d8-40a5-a940-19a05aecf7b1.png)

---


**测试2.**（双击A）进入阅读模式，选择某块区域进行标注。
**现象：** 导入obsidian的文件后缀有错误，修改后缀看内容是我标注的内容。
![Pasted image 20230213165306](https://user-images.githubusercontent.com/125122330/218421906-f356996c-9e73-4326-9fa0-a27209e6d5ef.png)

---

**测试3.**（双击A）进入阅读模式，选中某块区域，导入标注到obsidian。
![Pasted image 20230213170202](https://user-images.githubusercontent.com/125122330/218421949-b6eca791-b3e4-41fc-a09d-6c29cf6f4c79.png)
**现象：** 导入obsidian的文件后缀正确，但是新建了一个文件夹并且是以全文的方式导入。
![Pasted image 20230213170441](https://user-images.githubusercontent.com/125122330/218422016-27b9bc7d-2b08-42ce-9d17-30ec1ed0a265.png)

---

**测试4.**（双击A）进入阅读模式，然后
![Pasted image 20230213171645](https://user-images.githubusercontent.com/125122330/218422061-a806b1ae-d70d-405b-b02c-76ac8be072cf.png)
![Pasted image 20230213171720](https://user-images.githubusercontent.com/125122330/218422088-c8ad698a-b0ed-4e80-bd3e-7a331704d621.png)
**现象：** 导入obsidian的文件后缀正确，但是新建了一个文件夹并且是以全文的方式导入。
![Pasted image 20230213171805](https://user-images.githubusercontent.com/125122330/218422115-86ff34ca-0121-4483-906a-d0e29c3f20ef.png)

---

**测试5.**（双击A）进入阅读模式，然后直接导入全文到obsidian
![Pasted image 20230213171720](https://user-images.githubusercontent.com/125122330/218422148-e249e2c2-be8d-4cb0-a80c-d31260aa2bf6.png)
**现象：** 导入obsidian的文件后缀正确，但是新建了一个文件夹并且是以全文的方式导入。
![Pasted image 20230213171805](https://user-images.githubusercontent.com/125122330/218422170-f0ffb6ca-007c-4630-96c5-523a1323a957.png)

---

**测试6.** 更改同步助手配置（与老师提示的一致），重复以上测试，现象一致。

**Comment by Kenshin** [comment]
这么看的话，大概率还是配置有问题，看下图

<img width="907" alt="image" src="https://user-images.githubusercontent.com/81074/218429266-9f064fa5-4c7b-4fd3-bc9b-3820033a5ac6.png">

改成

```
{{id}}{{un_title}}{{mode}}
```

**Comment by Kenshin** [comment]
> 不管是标注还是稍后读所产生文件的命名都一样并都带有@annote，

emmm 你的问题大多来源于 [如何配置知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 看这个链接，对比下跟自己的区别。

一般来说生成的文件是两个，如下图

<img width="381" alt="image" src="https://user-images.githubusercontent.com/81074/218441555-32550b77-6777-4008-8872-ed04011217f3.png">

另外使用 Obsidian 的话，也可以看看 https://www.yuque.com/kenshin/simpread/fr8zo5 里面的说明~

**Comment by CaiXuZao** [comment]
> > 不管是标注还是稍后读所产生文件的命名都一样并都带有@annote，
> 
> emmm 你的问题大多来源于 [如何配置知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 看这个链接，对比下跟自己的区别。
> 
> 一般来说生成的文件是两个，如下图
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/81074/218441555-32550b77-6777-4008-8872-ed04011217f3.png">
> 
> 另外使用 Obsidian 的话，也可以看看 https://www.yuque.com/kenshin/simpread/fr8zo5 里面的说明~

好的，明白。感谢！

**Comment by Kenshin** [comment]
小事情 😄

看你的截图，基本上弄的差不多了~

**Comment by Kenshin** [comment]
我关闭这个 issues 了，有任何问题随时在这里回复我。

***

方便的话，请帮忙对简悦五星 + 好评 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by CaiXuZao** [comment]
> 我关闭这个 issues 了，有任何问题随时在这里回复我。
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

嗯嗯，已经五星好评，再次感谢您的帮助!

**Comment by Kenshin** [comment]
🙏 👍
