### ISSUE TITLE
使用integrately保存rss文件后，配置文件出错

### ISSUE THREAD

**Issue by samz1288** [Kenshin/simpread#5179]
已经把配置文件发您邮箱，请问我还需要做些什么，谢谢你。

**Comment by Kenshin** [comment]
先试试 https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a 能否解决？

如果动手能力强的话，也可以直接使用 https://github.com/Kenshin/simpread/discussions/2727

**Comment by samz1288** [comment]
您好，使用坚果云的历史文件依然存在配置文件出错问题。
#2727中，使用重启同步助手的方法，问题依然存在；而配置文件中没有null；请问我还可以怎么做？麻烦了。

**Comment by Kenshin** [comment]
okay 

我看到你发的配置文件了，修复后我会通知你的，估计今天稍晚的时候。

**Comment by Kenshin** [comment]
嗨，我已经给你发了新的配置文件，请留意查收。（邮件内含使用方法）
