### ISSUE TITLE
CSDN文字公式格式混乱

### ISSUE THREAD

**Issue by 472714747** [Kenshin/simpread#518]
在浏览网页

https://blog.csdn.net/VictoriaW/article/details/70053790

时公式显示出错。（如下图）这里的公式是文字格式而不是图片。
图一为开启插件，图二为阅读模式。图三为禁用插件后的正常显示。

**图一**
![Snipaste_2019-06-04_17-09-03](https://user-images.githubusercontent.com/26338127/58895429-c6aa5900-86eb-11e9-93fe-29fe92e1648e.png)

**图二**
![阅读模式](https://user-images.githubusercontent.com/26338127/58895430-c742ef80-86eb-11e9-9234-d081161a623a.png)

**图三**
![正常](https://user-images.githubusercontent.com/26338127/58895432-c742ef80-86eb-11e9-87aa-35d0c2db597c.png)

**Comment by Kenshin** [comment]
谢谢反馈。

应该是没问题的，可以看下截图

![image](https://user-images.githubusercontent.com/81074/58925423-0ddf2b00-877a-11e9-9685-42315b0aa1e1.png)

***

我研究了下这个 csdn 的页面，比较奇怪（跟其它同类包含 latex 相比）它的加载规则需要等到页面完全加载成功才加载 latex （似乎比其它 csdn 的页面慢一些...）

所以，你可以把 `blog.csdn.net` 加入到 排除列表中。

等页面完全加载完毕后再进入阅读模式。

***

另外，我不太理解你说的

> 图一为开启插件，图二为阅读模式。图三为禁用插件后的正常显示。

- 图一和图三的这个插件是指什么？

上面给你看的截图是：我重置了配置文件后，加上 https://simpread.ksria.cn/plugins/details/klGUASLasg 插件的效果截图。

你可以多试试几个页面，或者按照我说的方式测试下，看看是否还有问题吗？

**Comment by 472714747** [comment]
我之前说的插件指的是拓展hhh表述不清

我关闭了自动阅读模式页面正常了。另外我发现如果使用了

https://simpread.ksria.cn/plugins/details/SumEaxStWE

公式也会丢失格式

![image](https://user-images.githubusercontent.com/26338127/58990435-ca1e0d00-87dd-11e9-973f-160c70772bc9.png)

**Comment by Kenshin** [comment]
emmm...

https://simpread.ksria.cn/plugins/details/SumEaxStWE 

这个插件应该下线了.... 这是个老版本的补丁，现在已经没用处了。

***

加载慢指的仅仅是你给出的这个页面，1.1.2.5005 有包含对 Latex 的判断代码，所以我测试过不少的 Latex 页面，唯独它是最慢的一个。

你可以多试试不同 csdn 包含 Latex 的页面，并调成自动进入阅读模式。

**Comment by Kenshin** [comment]
增加了一个 [关于 解析 LateX 页面的说明](https://github.com/Kenshin/simpread/issues/534)

此 issues 将会关闭，如有问题请重新开启它。
