### ISSUE TITLE
公众号文章阅读模式解析有问题 （因页面有空白）

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#5183]
https://mp.weixin.qq.com/s/jkQhvEotRod8s6JyIzLecw
试过关闭增强模式会好一些。

**Comment by Kenshin** [comment]
谢谢反馈，某些公众号确实在关闭增强模式会好一些，我先记录下，有进一步反馈会通知你。

 😄

**Comment by Kenshin** [comment]
嗨，这个适配问题被解决了，解决方案 https://github.com/Kenshin/simpread/issues/5839#issuecomment-1675654114

我关闭这个 Issues 了，如果有任何问题建议在 https://github.com/Kenshin/simpread/issues/5839 集中讨论。
