### ISSUE TITLE
关于开放平台的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5185]
请问已经成功授权坚果云登录，并且坚果云里面有output文件夹，也存在simpread_config.json，依然报错404请问有没有其他可能的原因？

_Originally posted by @Postedism in https://github.com/Kenshin/simpread/discussions/3020#discussioncomment-4977502_

**Comment by Kenshin** [comment]
@Postedism

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 依然报错404

具体是指什么？建议截图或者详细描述操作步骤。

**Comment by Postedism** [comment]
对不起忘记在指定提交问题处提交了，我按照一站式知识库配置教程已经完成了坚果云授权与登录，也退出账号成功用坚果云完成登录了，截图在下方。
![坚果云授权1](https://user-images.githubusercontent.com/122367129/219347030-ba4225e8-6ac1-4e17-94fb-d3e367166a7a.png)
![坚果云授权2](https://user-images.githubusercontent.com/122367129/219347056-f6a3e110-8c25-4e73-8034-19df0516f6f1.png)
我也按照问题排查指引查看了坚果云对应位置有output文件夹
![确认output文件夹](https://user-images.githubusercontent.com/122367129/219347468-c1210c20-72d7-4fdb-90ae-8991d29141e3.png)
核对过一遍简悦的操作流程，步骤没有遗漏，只是在开放平台测试这里返回404了，先谢谢Kenshin老师解答

**Comment by Kenshin** [comment]
> 对不起忘记在指定提交问题处提交了

小问题而已 😄

我是问你 404 的截图或者是操作什么时产生的？（方便录屏的话也行）

或者把你的 UID 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5185

我明天帮你看下。

**Comment by Postedism** [comment]
是在进入开放平台之后进行API测试时返回的数据，截图如下，操作是点击了API测试的链接之后，再点击send按钮，返回了错误代码404，之前发错的截图是根据教程排查的错误。

![404截图](https://user-images.githubusercontent.com/122367129/219352938-297e45c3-c1f9-437a-a283-13627c0694b4.png)

**Comment by Kenshin** [comment]
把 UID 发到我告诉你的信箱里面，我明天看下。

**Comment by Kenshin** [comment]
你的坚果云授权 Email 写错了...

是你的坚果云账户 Email 而不是其它的。😂
