### ISSUE TITLE
高级账户，在共通中无法设置与同步助手的绑定。

### ISSUE THREAD

**Issue by miliang77** [Kenshin/simpread#5187]
- 操作系统 **Win11 22H2 **

- 浏览器版本 **EDGE 110.0.1587.41**

- 简悦版本 **2.2.0.520**

- 高级账户，在共通中无法设置与同步助手的绑定。在共通中只有配置文件导出导出选项，其他无功能。
- 
![image](https://user-images.githubusercontent.com/35925755/218925583-b0e81d99-125c-45f5-ab99-ea5192ff844b.png)

**Comment by Kenshin** [comment]
emmm

你的界面有问题，看看是不是 [这个问题造成的 ](https://simpread.pro/docs/#/%E7%AE%80%E6%98%93%E6%A8%A1%E5%BC%8F)
