### ISSUE TITLE
导出笔记到Obsidian失效

### ISSUE THREAD

**Issue by Zhida-Liu** [Kenshin/simpread#5190]
如图所示，当我尝试把笔记导入obsidian时，弹出如下错误提示。
![image](https://user-images.githubusercontent.com/73575904/219294885-5ca8293b-79b7-4219-bd15-0d9d5855c65d.png)

![image](https://user-images.githubusercontent.com/73575904/219295148-d8a496ad-3687-4062-b623-2307ba57d4b1.png)

**Comment by Kenshin** [comment]
这个提示一般来说可能是

Obsidian 文件夹设置错误造成的。

<img width="618" alt="image" src="https://user-images.githubusercontent.com/81074/219299587-28ff6343-3fa1-453a-b8ca-a5f5eda078a3.png">


但导入到 Obsidian 的方式有很多，所以建议最好把 Obsidian 相关的设置都截图给我看下。

**Comment by Zhida-Liu** [comment]
好的，这是我同步助手里关于Obsidian的设置截图
![image](https://user-images.githubusercontent.com/73575904/219302731-df0cb7eb-06d1-4b26-8ec5-4157755cca5a.png)

**Comment by Kenshin** [comment]
嗨，我是说导入到 Obsidian 这个插件的截图 😂

**Comment by Zhida-Liu** [comment]
是指Obsidian的插件设置页面嘛？

**Comment by Zhida-Liu** [comment]
![image](https://user-images.githubusercontent.com/73575904/219303631-2b63a0bc-322b-4080-a3e1-172af37c2600.png)

**Comment by Kenshin** [comment]
嗨，我说的是导入到 Obsidian 选项卡里面设置的截图，例如这个链接 https://github.com/Kenshin/simpread/issues/5190#issuecomment-1432652489 对应的位置。
