### ISSUE TITLE
导入到Notion辅助增强使用问题

### ISSUE THREAD

**Issue by xchyyb** [Kenshin/simpread#5193]
![image](https://user-images.githubusercontent.com/78303344/219525569-597970d8-53b3-401b-9333-7808e7d8c670.png)
导入到Notion辅助增强一直加载但不显示界面

**Comment by Kenshin** [comment]
嗨。

多试试其它不同的页面。e.g https://sspai.com/post/69972 如果每个页面都这样就不需要测试，然后看：

1. 导入到 Notion 是否成功？需要告诉我使用了哪种导入方式（简悦目前有两种）

2. 如果导入成功，但 Notion 辅助增强不好使，请使用 https://simpreadpublish.notion.site/e784eba882da452eb8f300e6cd6b195d 重新添加了一个 Page 再做测试。

**Comment by xchyyb** [comment]
导入到notion是成功的，是用导入到notion插件导入的，使用https://simpreadpublish.notion.site/e784eba882da452eb8f300e6cd6b195d这个模板后导入到notion辅助增强又可以使用了，那我那个页面为什么不可以呢，之前一直是可以正常使用的

**Comment by Kenshin** [comment]
解决就好。

> 那我那个页面为什么不可以呢

不知道你原来的 Pag 有多少个子页面？之前有个用户包含过类似的问题，大概 1000 个左右。

所以我怀疑可能是 Notion API 爆了…

解决方案：

1. 如果原来的太多了，就新建一个，并不会有什么麻烦的「问题」

2. 把旧的 Page 里面的内容手动转移到新的里面。
