### ISSUE TITLE
使用notion增强版绑定后无法使用

### ISSUE THREAD

**Issue by emptystack1024** [Kenshin/simpread#5194]
![image](https://user-images.githubusercontent.com/104486691/219565522-0bfee034-ad7f-4c0b-ad22-ebb50cbacaa3.png)
![image](https://user-images.githubusercontent.com/104486691/219565561-ea8c7423-2c4a-495b-bf5b-ade666640b43.png)
![image](https://user-images.githubusercontent.com/104486691/219565589-ea36dae6-a595-4804-a7cc-13167b0b6ac8.png)
我都设置了
![image](https://user-images.githubusercontent.com/104486691/219565741-4194a8ff-0c0e-431f-be3c-af00fa4a667f.png)
但是保存的时候能保存，但是运行notion增强脚本时会报很多个错误

**Comment by Kenshin** [comment]
嗨，看下 https://github.com/Kenshin/simpread/issues/5193#issuecomment-1434005113 提供的一些测试和解决思路。

**Comment by emptystack1024** [comment]
我尝试了一下重新保存一个副本并进行导入，但是仍然不好用

**Comment by Kenshin** [comment]
是一直都不好用？还是之前好用，然后不好用了？

还有… 根据 https://github.com/Kenshin/simpread/issues/5193#issuecomment-1434005113 的提问回复下你的导入环境。

**Comment by emptystack1024** [comment]
一开始就不好用
不太清楚你说的是那种导入方式，我使用的是
![image](https://user-images.githubusercontent.com/104486691/219650760-da20d093-9548-4125-b3e7-fb605c67400a.png)
这里的保存到notion

**Comment by Kenshin** [comment]
直接导入能成功吗？

**Comment by emptystack1024** [comment]
可以的

**Comment by Kenshin** [comment]
那基本上就是你的配置问题了。

简悦提供了 Notion 配置包方案，e.g https://www.yuque.com/kenshin/simpread/ewaflu 里面有一个简悦官方的内置测试账户，请先使用这个账户测试，如果能导入的话，说明你的配置无误，再重新使用你自己的账户测试。
