### ISSUE TITLE
希望微信订阅号文章的阅读页面可以显示 作者、公号名称和发布日期

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5198]
希望微信订阅号文章的阅读页面可以显示 作者、公号名称和发布日期。实际上，这三个信息对于每篇文章都很重要，希望简阅的阅读页面都能够适配。

_Originally posted by @Alice-Shi in https://github.com/Kenshin/simpread/discussions/2561#discussioncomment-5011155_

**Comment by Kenshin** [comment]
@Alice-Shi 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

嗨，我新建了一个 Issues 来追踪这个 Feature

**Comment by bighaidao** [comment]
我也有这个需求，然后自己搞了一个个性化的网页适配， 也是折腾死了 希望官方能搞定

**Comment by Kenshin** [comment]
@bighaidao 

没问题，只是优先级不高，总是被忽略掉。 😂

**Comment by Alice-Shi** [comment]
> 阅读页面可以显示 作者、公号名称和发布日期。实际上，这三个信息对于每篇文章都很重要，希望简阅的阅读页面都能够适配。

非常期待呀 😃

**Comment by Jackson2002** [comment]
要是能显示作者就能自动根据名字分好类了在ob

**Comment by Kenshin** [comment]
@Jackson2002 

emmm （感觉）不是太好实现~ 或者让名字变成 `#标签` ？

**Comment by Jackson2002** [comment]
也可以啊 反正就是可以实现建仓在ob里面找自动分类

**Comment by Kenshin** [comment]
嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了，包含此功能

<img width="731" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ecd273ee-e517-4c75-8ae6-335d83ffac23">

除此之外，此插件还优化了以下内容：

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

### 关联 

https://github.com/Kenshin/simpread/issues/5852


***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
