### ISSUE TITLE
希望能适配纽约时报中文网的中英双语页面

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5199]
<div type='discussions-op-text'>

<sup>Originally posted by **Alice-Shi** February 17, 2023</sup>
测试文章👉 《人格分裂、疯狂示爱：一个令人不安的微软机器人 - 纽约时报中文网》🌐 https://cn.nytimes.com/technology/20230217/bing-chatbot-microsoft-chatgpt/dual/

Bug：阅读页面是错误的，缺少第一段落。▼
<img width="687" alt="image" src="https://user-images.githubusercontent.com/22544951/219691841-f604137a-beec-4f35-a53a-14966b68d7aa.png"></div>

**Comment by Kenshin** [comment]
嗨，会考虑的。

目前你可以使用下面的方式，基本上也能解决你的问题。

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/81074/219829053-762ab7b7-738f-48c7-817a-dd2ce02448b3.png">

下面是效果

<img width="831" alt="image" src="https://user-images.githubusercontent.com/81074/219829061-39b46c48-783e-4d9f-9b97-ee5d2007bfc1.png">

**Comment by Kenshin** [comment]
@Alice-Shi

我帮你新建了一个 Issues，并删除了原来位置的内容。

**Comment by Alice-Shi** [comment]
谢谢！👻

**Comment by Kenshin** [comment]
哈哈，小事情 😄

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Alice-Shi** [comment]
之前已经好评过啦😁

**Comment by Kenshin** [comment]
哈哈，谢谢好评  🙏  👍
