### ISSUE TITLE
部分网站格式化之后部分内容缺失

### ISSUE THREAD

**Issue by skyer0721** [Kenshin/simpread#520]
https://www.learncpp.com/cpp-tutorial/59-random-number-generation/
格式化之后下半部分都没啦

**Comment by Kenshin** [comment]
什么叫做 `下半部分都没啦` ？

你是说评论吗？如果是的话，简悦的阅读模式是不会包含评论内容的。

**Comment by skyer0721** [comment]
那估计算是预期内的
https://www.learncpp.com/cpp-tutorial/5-11-introduction-to-testing-your-code/

**Comment by Kenshin** [comment]
知道你说的意思了...

这是没办法避免的事情，不同页面有不同页面的规则，不可能有通用性。

不过，你可以使用 [重新高亮](http://ksria.com/simpread/docs/#/重新高亮) 来解决这个问题。

**Comment by Kenshin** [comment]
嗨，[1.1.3](http://ksria.com/simpread/changelog.html#1.1.3) 已经发布~

增加了 [手动框选的二次确认](http://ksria.com/simpread/docs/#/手动框选?id=二次确认) 配合 [重新高亮](http://ksria.com/simpread/docs/#/重新高亮) 来解决这个问题

我将关闭此 issues

***

除此之外，1.1.3 还增加了如下的功能：

- 更友好的 [新手入门](http://ksria.com/simpread/guide)

- 导出服务已经支持 [坚果云](http://ksria.com/simpread/docs/#/坚果云)  [语雀](http://ksria.com/simpread/docs/#/导出到生产力工具)  [WebDAV](http://ksria.com/simpread/docs/#/WebDAV)

- [消息中心](http://ksria.com/simpread/docs/#/消息中文) · [帮助中心](http://ksria.com/simpread/docs/#/帮助中心)

- [预加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=预加载机制) [延迟加载](http://ksria.com/simpread/docs/#/词法分析引擎?id=延迟加载) [智能感知](http://ksria.com/simpread/docs/#/词法分析引擎?id=智能感知) [手动高亮的二次选择](http://ksria.com/simpread/docs/#/手动框选?id=二次确认)

***

#### 优化了 

- 导出到 Markdown 的若干问题

- Onenote 授权失败过期的提示错误 

- 无法获取 知乎 Gif 的错误

- TOC 的若干问题，如某些页面的卡顿，无法跳转等

***
详细请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.3)
