### ISSUE TITLE
阅读模式代码行数错误

### ISSUE THREAD

**Issue by yoyumiya** [Kenshin/simpread#5200]
代码高亮插件启动和取消都没用。

https://www.ydlclass.com/doc21xnv/javaweb/servlet/#%E7%AC%AC%E4%B8%80%E7%AB%A0-%E5%89%8D%E7%AB%AF%E5%92%8C%E5%90%8E%E7%AB%AF%E7%9A%84%E9%93%BE%E6%8E%A5

![clipboard_20230218_174518](https://user-images.githubusercontent.com/104292656/219853792-52ed2a1f-85cb-49b3-9909-4db4d5b34d35.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题一般都比较难办，因为代码规则太多了 😂

我会集中在 #500 并关闭此 Issues 修复后会通知你~
