### ISSUE TITLE
简悦同步助手里面的稍候读设置，默认加载local本地文件的bug

### ISSUE THREAD

**Issue by hellspector** [Kenshin/simpread#5204]
如果用默认加载local离线文件
那么在网页端标注与在稍候读的标注是不会同步的，也就是说，在同步助手稍候读的标注，在网页端点击是不能跳转的
反之在网页端标注也不能在同步助手的稍候读里面点击跳转
解决办法：关闭同步助手稍候读的，默认的离线文件
![image](https://user-images.githubusercontent.com/80568889/219936565-ebafdda2-7840-402e-ad4e-b4b7f6dad027.png)

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
> 如果用默认加载local离线文件
那么在网页端标注与在稍候读的标注是不会同步的

不会的... 你可以多测试下不同的页面 e.g. https://sspai.com/post/69972 看看是否稳定复现？

测试步骤：

1. 网页端标注 → 生成本地 HTML
2. 进入稍后读（注意：这里一定要新打开稍后读或刷新稍后读），然后标注。
3. 回到网页端（注意：这里一定要新打开稍后读或刷新稍后读），会看到标注应该更新到网页端的正文。

注意：如果步骤3没有在正文找到，看下右侧侧栏是否有这个（在稍后读中）新的标注？

在极端情况下，会出现正文没有显示标注（只是没有找到标注的定位，造成这个问题的原因很多，不展开说了，跟你提的问题可能无关。

**Comment by hellspector** [comment]
标注能看到，但是点击标注无法跳转到相应位置。

**Comment by Kenshin** [comment]
> 标注能看到，但是点击标注无法跳转到相应位置。

稍后读里面？

**Comment by hellspector** [comment]
> 

稍候读里面标注的在浏览器里面不能跳转，浏览器里面标注的不能在稍候读里跳转。
