### ISSUE TITLE
支付宝购买简悦48小时后未收到授权号，检查了邮箱的垃圾箱和拦截记录里面都没有，麻烦查看下是什么情况

### ISSUE THREAD

**Issue by 452606792** [Kenshin/simpread#5207]
如题，未收到授权码

**Comment by Kenshin** [comment]
嗨，我刚刚兑换了一批，如果你填写的无误的话，应该收到 Email 了。

因为是手动兑换，所以时间不会那么 100% 精准。

如仍未看到 Email，请把支付宝订单号截图发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5207

我明天会处理。
