### ISSUE TITLE
在少数派页面同时选中文字与图片作一次标注时，会出问题

### ISSUE THREAD

**Issue by Alice-Shi** [Kenshin/simpread#5210]
实验页面👉《放弃纠结、拥抱妥协，重器轻用就是高效 - 少数派》 🌐https://sspai.com/post/71576
同时选中`文字➕图片`作高亮后，发现俩问题：
- 问题一：阅读模式页面 & Obsidian 自动生成的标记 markdown页面 会 生成两条笔记而非一条 ▼
<img width="625" alt="image" src="https://user-images.githubusercontent.com/22544951/219953251-23cfa112-5121-4059-bcb5-469f3428546b.png">

- 问题二：稍后读页面也会出错（有的时候只有文字没有图片，有的时候都有但是是分裂的状态），下图是前者 ▼
<img width="693" alt="image" src="https://user-images.githubusercontent.com/22544951/219953323-7cb86d00-1559-4e5b-97e5-72e07629d56e.png">

备注：已安装 插件 👉 《插件中心 - 简悦 SimpRead - 如杂志般沉浸式阅读体验的扩展》🌐https://simpread.ksria.cn/plugins/details/bz6jpYxm29
并且显示是正常运转的吧 ▼
<img width="391" alt="SCR-20230219-usc" src="https://user-images.githubusercontent.com/22544951/219953586-c9466acc-fd41-490e-be9b-6620bfb0ffe3.png">

**Comment by Kenshin** [comment]
okay 我明天试试。

不过，不建议标注时连同图片一起标注。

另外，当连同图片一起标注时，是会分成文本段 + 图片的多条形式。

**Comment by Kenshin** [comment]
> 问题1

这是正常的情况，上一条 Issues 说了，图 + 文字的标注形式会变成：多条。

> 问题2

我是按照下面的方式随便截图的，目前没有遇到你说的问题。

<img width="957" alt="image" src="https://user-images.githubusercontent.com/81074/220000680-17a67702-0ce2-4ecd-951f-eb2cade9739b.png">

在稍后读的预览

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/81074/220000719-977f4f58-66cf-4c01-9f6b-a4ab7433b791.png">

是没问题的。

同样导入到 Obsidian 也是没问题的。

<img width="768" alt="image" src="https://user-images.githubusercontent.com/81074/220000939-7ce33849-de15-4d13-9b99-923f2e021d5d.png">


***

当然，你说的是有可能发生的，所以上一条说了：

1. 不建议这么做（图 + 文字）的标注形式。
2. 如果要这么做的话，就让文字段落划取规整一些。

**Comment by Alice-Shi** [comment]
> 不过，不建议标注时连同图片一起标注。
> 
> 另外，当连同图片一起标注时，是会分成文本段 + 图片的多条形式。

好的了解，谢谢🌷

**Comment by Kenshin** [comment]
> 图文混合批注，越来越贴近 pdf 批注的体验

技术上说最早的版本就是这样，只是发布前让我取消了，确实忘记当时是如何考量的了 😂

下个版本会实现你说的方案。
