### ISSUE TITLE
以阅读模式打开一个新页面 并进行标注以后，如何保存全文至 html？

### ISSUE THREAD

**Issue by Alice-Shi** [Kenshin/simpread#5211]
如题，假如以阅读模式进入一个页面后，在`没有加入稍后读并依赖自动化自动下载 html 到本地的`情况下**进行了标注**，那么，则找不到方法把这篇文章的 html 保存下来。注意“动作”选项卡里的“导出html”导出的是标注的html，而不是文章的，而在稍后读页面也是同样的情况。

现在我需要时刻提醒自己，先加入稍后读以触发保存文章html到本地，再去作标记 🙁️

**Comment by Kenshin** [comment]
emmm 是这样的。

> 先标注，而后自动加入稍后读这个功能是没问题的，但：

1. 有可能有个隐性 Bug 导致你说的这个问题存在。（但我自己很难稳定复现）

2. 如果你使用了 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件的话，这么做也有问题，因为这个插件对加入稍后读时的数据结构顺序有非常强的依赖。

所以，综上：还是老老实实先加入稍后读吧 😂

***

> 那么，则找不到方法把这篇文章的 html 保存下来。注意“动作”选项卡里的“导出html”导出的是标注的html，而不是文章的，而在稍后读页

这个问题是不存在的，但留意下图的设置

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/81074/220048026-0e9ffee8-b8cb-4f08-ac22-3aa681da76dc.png">

以及我之前跟你说的 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的设置。

也就是说，当配置正确知识库后，手动导出 HTML，应该是两个文件，类似

<img width="359" alt="image" src="https://user-images.githubusercontent.com/81074/220048179-c660e4f6-48f5-44b2-ad37-89a47561cc2b.png">

**Comment by Alice-Shi** [comment]
> > 那么，则找不到方法把这篇文章的 html 保存下来。注意“动作”选项卡里的“导出html”导出的是标注的html，而不是文章的，而在稍后读页
> 
> 这个问题是不存在的，但留意下图的设置
> 
> <img alt="image" width="1250" src="https://user-images.githubusercontent.com/81074/220048026-0e9ffee8-b8cb-4f08-ac22-3aa681da76dc.png">
> 
> 以及我之前跟你说的 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的设置。
> 
> 也就是说，当配置正确知识库后，手动导出 HTML，应该是两个文件，类似
> 
> <img alt="image" width="359" src="https://user-images.githubusercontent.com/81074/220048179-c660e4f6-48f5-44b2-ad37-89a47561cc2b.png">

▲还真是😂
另外发现，假如上面选 导出时——全文(含标注)的时候，就满足我的这个需求了，因为导出的 html 页面即所需 😀
