### ISSUE TITLE
希望可以让描述图片的文字与图片一样居中对齐

### ISSUE THREAD

**Issue by Alice-Shi** [Kenshin/simpread#5213]
假如能像源页面那样居中对齐会更美观和易读
现有都是左对齐👇🏽
<img width="684" alt="image" src="https://user-images.githubusercontent.com/22544951/220233512-a0d0d44c-d162-4779-aaf9-9f74435beb79.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/22544951/220233552-5e228c73-74fa-4f14-830b-0d2503c629a4.png">

**Comment by Kenshin** [comment]
给个 URL 我瞧瞧。

**Comment by Alice-Shi** [comment]
基本每个少数派文章都是吧我印象，比如上面截图的这篇文章 https://sspai.com/post/42361

**Comment by Kenshin** [comment]
将下面的代码

```
sr-rd-content figcaption {
    text-align: center!important;
}
```

加入如图所示的地方

<img width="711" alt="image" src="https://user-images.githubusercontent.com/81074/220275784-905f14e3-f6d5-4da6-a4c0-e008f2733a0d.png">

保存后刷新当前页面。

***

PS：这个规则我会更新到配置规则中。

**Comment by Kenshin** [comment]
跟上图的解决方案一致。

**Comment by Kenshin** [comment]
你可以可以将上面的代码加入到全局样式中。

<img width="809" alt="image" src="https://user-images.githubusercontent.com/81074/222317500-f91eee69-3866-4b6f-9a09-af273c7399d1.png">
