### ISSUE TITLE
导出离线html失败

### ISSUE THREAD

**Issue by tanziow** [Kenshin/simpread#5216]
导出含有大量图片/GIF的离线html图片时失败，量级大概是400m，图片约160张，在较长一段的“图片转换中，请稍等”后就没了下文，也不会弹出保存下载等窗口；普通网站可正常导出为离线html，请速速常识和解决

**Comment by Kenshin** [comment]
嗨，给个 URL 瞧瞧。

想要实现图片本地化有很多方案，不一样非要离线 HTML，细节 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920473

**Comment by tanziow** [comment]
> 嗨，给个 URL 瞧瞧。
> 
> 想要实现图片本地化有很多方案，不一样非要离线 HTML，细节 [#4041 （评论）](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920473)

https://www.sehuatang.org/forum.php?mod=viewthread&tid=1180438&page=1，亲测保存为离线MD也不行，无限卡图片转换中

**Comment by Kenshin** [comment]
okay 我明天试试

**Comment by tanziow** [comment]
> okay 我明天试试

怎么样，而且在图片转换过程中非常卡

**Comment by Kenshin** [comment]
你这图片... 

gif 太多了，正常情况。试试不用同步助手的离线 HTML 方式。

**Comment by tanziow** [comment]
> 

就是没有使用同步助手的离线html，无法导出

**Comment by HopeLHP** [comment]
似乎只要有一个以上的gif就会卡无限图片转换中，特别是微信公众号文章，有些花里花哨的动图表情比如这个https://mp.weixin.qq.com/s/JRp1oSZIMjmFRH4QwcKkQw

**Comment by Kenshin** [comment]
@HopeLHP 

我测试了你给出的 URL 是没问题的

<img width="587" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/45641619-6473-47c8-97aa-9d0a7a480c49">

不过，你给出的 URL 并没有包含你提到的动图，而且这个 URL 的图片也很少。（猜测给错 URL 了。
