### ISSUE TITLE
导出markdown，提示未运行同步助手客户端

### ISSUE THREAD

**Issue by F1echazo** [Kenshin/simpread#5218]
Windows
之前一直使用1.10的同步助手客户端，今年使用导出功能突然出现报错，更换最新版客户端出现相同报错，且无法通过客户端内选项实现开机启动，将客户端快捷方式添加到自启动目录后可以正常启动，查看注册表启动项存在两个同步助手。
![image](https://user-images.githubusercontent.com/34188664/220500193-cd86b0c3-6ebf-4dfa-b8f9-3589d68284e7.png)

**Comment by Kenshin** [comment]
emmm 看看你的新同步助手是不是 UID 掉了？

![image](https://user-images.githubusercontent.com/81074/220514590-6c115a1d-125d-439d-a6cb-3aab25c8cc55.png)

另外，一定要确保仅运行一个同步助手，你说的那些功能在版本升级时并没有涉及到。
