### ISSUE TITLE
财新文章在阅读模式中残缺（订阅版）

### ISSUE THREAD

**Issue by wqnndt** [Kenshin/simpread#5219]
发生问题的地址 <https://china.caixin.com/2022-07-30/101920139.html>

**Comment by Kenshin** [comment]
嗨，我没办法访问这个页面，你可以试试 https://github.com/Kenshin/simpread/discussions/1554 提到的方案是否可以解决？

或者截图告诉我哪里缺失了？

**Comment by wqnndt** [comment]
谢谢

**Comment by Kenshin** [comment]
如果解决了你的问题，我关闭这个 issues 了~
