### ISSUE TITLE
outlook网页版抓取问题

### ISSUE THREAD

**Issue by sevenMZ** [Kenshin/simpread#5224]
用 outlook 看 newsletter，页面抓取的标题是【邮件 - {账户名} - Outlook】而不是邮件标题，请问是我设置不对还是只能这样抓取呢？

**Comment by Kenshin** [comment]
你的意思是在 Outlook 中使用阅读模式？

如果是的话，你说的这个情况是正常现象...因为根本没有这种适配规则 😂
