### ISSUE TITLE
保存到OneNote但是找不到了

### ISSUE THREAD

**Issue by zhaodayday** [Kenshin/simpread#5227]
您好，我想询问一下，简悦的保存到onenote功能，可以指定笔记本或者分区吗，我一不小心将onenote的云端笔记本删除了，导致现在保存成功，但是我找不到它，（之前是可以的）

**Comment by Kenshin** [comment]
> 可以指定笔记本或者分区吗

暂时不可以，但一般来说当没有笔记本的话，应该是新建一个。

PS：Onenote 的更新比较慢，你可以等一会。（我不确定，因为很久没有在用 Onenote 了。

**Comment by zhaodayday** [comment]
> > 可以指定笔记本或者分区吗
> 
> 暂时不可以，但一般来说当没有笔记本的话，应该是新建一个。
> 
> PS：Onenote 的更新比较慢，你可以等一会。（我不确定，因为很久没有在用 Onenote 了。

多谢，确实是新建了一个，我找到它了

**Comment by Kenshin** [comment]
okay 解决就好~
