### ISSUE TITLE
右下角触发器无任何响应

### ISSUE THREAD

**Issue by lance123456-del** [Kenshin/simpread#5230]
**请说明发生问题的环境**
win10

- 浏览器版本 **110.0.5481.104（正式版本） （64 位）**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html
- 
![image](https://user-images.githubusercontent.com/61313980/221070921-c526a20e-f4b7-463f-b17d-c8854156d22e.png)
在edge浏览器可以触发
![image](https://user-images.githubusercontent.com/61313980/221071056-1407943b-d72e-4f51-a969-396a092a08f9.png)
但edge浏览器无法授权为知笔记，多次操作（退出、重新登录、重启等）均没有效果

**Comment by Kenshin** [comment]
嗨，你可以看看 

- https://github.com/Kenshin/simpread/discussions/2407

- https://github.com/Kenshin/simpread/discussions/2989

另外，不要反复重开 Issues，我关闭这个 issues 后你仍可以讨论。

**Comment by lance123456-del** [comment]
非常感谢您的回复，为知笔记可以成功授权，但chrome浏览器进入阅读模式后右下角触发器没有任何响应请问有什么方案吗

**Comment by Kenshin** [comment]
> 但chrome浏览器进入阅读模式后右下角触发器没有任何响应请问有什么方案吗

留存好你的配置文件，重新安装 Chrome 并导入配置文件，然后**隐身模式下仅使用简悦的方式**，进入 https://sspai.com/post/69972 看看是不是其它扩展造成的干扰？

**Comment by lance123456-del** [comment]
您好，隐身模式下确实可以了，但发送到为知笔记特别缓慢，禁用了最近安装的扩展非隐身模式下还是不行

**Comment by Kenshin** [comment]
> 隐身模式下确实可以了

那就是你的其它扩展造成的干扰，可以试试二分法排除你的这些扩展，找到那个有问题的。

> 发送到为知笔记特别缓慢

具体如何慢？是发送时较慢？还是发送后为知笔记显示的较慢？但无论是哪种情况，应该只跟为知笔记有关系，跟简悦这边没有关系。

**Comment by Kenshin** [comment]
哈，小事情，解决就好 😄

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
