### ISSUE TITLE
当前配置文件出错导致无法打开选项页，你可以通过以下方式解决：

### ISSUE THREAD

**Issue by mr-dragon** [Kenshin/simpread#5231]
### 操作环境

`Mac M1 Chrome浏览器版本 109.0.5414.46（正式版本）beta (arm64)`

### 出现问题

当前配置文件出错导致无法打开选项页，你可以通过以下方式解决：
具体见图：

![image](https://user-images.githubusercontent.com/25114117/221086893-354c51f2-0d6a-49b1-b12f-d26c2450d2b1.png)

#### 卸载简悦、关掉浏览器、重新安装、先重置数据、再用坚果云/配置文件登录

尝试过，不可行

#### 使用坚果云历史记录配置文件

试了好几个，自测都是不行，一样到上面图片的报错页面

### 其他说明

本身这个是可用的，这是第一台绑定的授权设备。
但是由于工作需要 ，有一台win变成了 主力，所以后续都是在win上使用坚果云+同步助手，同步助手 不经常开，然后配置文件也是有同步到坚果云，看起来 更新日期是 2023-02-15

之前说语雀有文档，但是 我找不到了，当时对着弄过，无果，现在本地的同步助手关了，升级1.1.4@mac版也试过 不行

**Comment by Kenshin** [comment]
嗨，同步助手 1.2.0 发布了，内含 `simpread_config.json` 修复功能，你可以试试，在运行同步助手的前提下，进入 http://localhost:7026/database/fixed

我先关闭这个 Issues  了，有任何问题可以随时回复。

> 以下是同步助手 1.2.0 的其它功能。

## 更新日志

- [更新日志](https://simpreadpublish.notion.site/simpreadpublish/2482effc334e4df8aa3aac7da8bb8059#86c339b25b15455b9cc043044891351f)

## 新增 💄 

### [数据中心](https://simpread.pro/docs/#/数据中心)

内置了一组针对 `simpread_config.json` 的优化、修复、整理、统计工具。

#### 地址

http://localhost:7026/database

#### 预览

![image](https://user-images.githubusercontent.com/81074/220891702-b15b7551-205e-480d-aedd-9cf72de7f296.png)

#### 模块

  - [历史记录](https://simpread.pro/docs/#/数据中心?id=历史记录)

  - [修复配置文件](https://simpread.pro/docs/#/数据中心?id=修复配置文件)

  - [清理配置文件](https://simpread.pro/docs/#/数据中心?id=清理配置文件)

  - [查找重复数据](https://simpread.pro/docs/#/数据中心?id=查找重复数据)

  - [数据统计](https://simpread.pro/docs/#/数据中心?id=数据统计)

**Comment by mr-dragon** [comment]
### 扫描结果

开始检查后的结果：

![image](https://user-images.githubusercontent.com/25114117/221116211-1e8e86d5-98a2-4e60-8445-5039d65e994a.png)

### 修复后

![image](https://user-images.githubusercontent.com/25114117/221116316-5ad2fe6d-c35c-489a-a106-120482242ccc.png)


没有生效，我做了如下操作：

1. 使用1.2 同步助手，开启了，并指定了 坚果云的目录，也识别到了我的配置，能扫描出上面的 问题列表
2. 点击开始修复，重启浏览器 —— 无果
3. 卸载重装插件，从本地重新安装 crx，本地导入配置文件，直接进入 `选项卡` ，一样提示
4. 点击插件管理，点一次 提示一次配置文件出问题

**Comment by mr-dragon** [comment]
最终成功的方法：
1. 不要重置同步助手的授权，不要重置同步助手，不要重置同步助手。里面包含你的授权信息，会导致点击修复会401错误
2. 卸载简悦，重装简悦，打开：<http://localhost:7026/database/fixed>, 点开始修复，无报错再继续操作
3. 进入简悦选项页-插件管理-从配置文件导入插件-下方点确定-导入成功
4. 基本到这里就正常使用了

---
说下 如果 你的 同步助手 重置了，也就是 简悦插件对同步助手的，授权被重置了，那么 你的修复 是一定成功不了
浏览器network的这个请求 `http://localhost:7026/config` ， 会返回：`{code: 401, status: "uid"}`
此时 只能找作者帮忙修复配置文件

此时的步骤是：
1. 使用 正确的文件，卸载插件后重装，从本地导入配置文件 —— 正常
2. 从配置文件导入插件 —— 正常
3. 授权同步助手 —— 正常

**Comment by Kenshin** [comment]
哈，感谢提供「宝贵的历史经验」😂
