### ISSUE TITLE
图床插件有些图片无法上传

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5232]
我通常使用图床功能和导出HTML，来替代导出离线HTML，但是，对于有些网站来说，图床插件图片上传失败，比如今日头条的图片，或者国外网站的图片，不知道这个插件使用的什么机制。

**Comment by Kenshin** [comment]
1. 图床插件上传失败不是简悦的问题 😂 你可以提供失败的 URL 我瞧瞧。

2. 如果你使用了其它网络服务，无法是将这个图片从 A 服务器 → B 服务器，并没有「任意价值」，如果在国内的话，该 404 的图片一样会 404。

综上，最好的办法：

1. 使用自建服务
2. 使用离线方案，如离线 HTML、md + assets 方案。
3. 使用 Notion（简悦有 Notion 图床功能）

**Comment by liuyuqiangchn** [comment]
感谢，因为离线HTML下载文件会很大，所以，我用这种方式代替，我使用的是阿里云OSS，
这是国外的网站，https://www.playpcesor.com/2023/02/chatgpt-ai.html，
这是今日头条的网站，https://www.toutiao.com/article/7201087143656063543/?log_from=57fd32311e43b_1677222547529，这两个网站图片都上传失败，不知道他们是不是采取了防盗链的功能导致上传失败，另外，如果我访问需要科学上网的网站，也是不能上传成功的，我现在就这个环节跑不通，

我尝试其他的稍后阅读软件，他们会将图片也是上传到自己的服务器，上面两个网站都可以正常上传，我是个新手，不知道是不是我设置方面不对，希望得到你的帮助，万分感谢

**Comment by liuyuqiangchn** [comment]
另外，说一下为什么这个对我比较重要，我的主要用途是，通过简悦将文章发送到我的邮件中，这样可以实现多平台多设备查看，但是，如果不使用图床功能，有些网站的图片是无法显示的，比如网站防盗链的图片和国外需要科学上网的网站图片

**Comment by Kenshin** [comment]
这两个 URL 都可以使用 **离线 HTML** 导出

<img width="679" alt="image" src="https://user-images.githubusercontent.com/81074/221160679-6c135ea6-9850-4ba4-ab2d-1288cc6b03d5.png">


另外，这两个 URL 都能正常使用，**我配置的是腾讯云**。

<img width="730" alt="image" src="https://user-images.githubusercontent.com/81074/221161633-0787e4e0-a7a2-47d2-b131-07732328cb11.png">

<img width="988" alt="image" src="https://user-images.githubusercontent.com/81074/221161351-92d0ba14-81a6-44e0-b800-62f0e94cddb0.png">

PS：将图片放到自己的云存储是个好习惯。 👍 

所以，试试 https://sspai.com/post/69972 看能否上传成功？用来判断你的设置是否正确。

**Comment by liuyuqiangchn** [comment]
非常感谢，我用的是阿里云OSS，少数派是可以正常上传的，我发给你的两个网站也会显示上传成功，但是实际并没有上传进图库中，能麻烦你看看图库中有图片吗

**Comment by liuyuqiangchn** [comment]
我刚才用腾讯云测试了一下，少数派正常上传，其他网站正常上传，我发给你的两个网站还是一样，在上传的时候也会显示上传成功，但是实际并没有上传进图库中

**Comment by liuyuqiangchn** [comment]
另外，我还发现一个奇怪的问题，对于国外网站或者需要科学上网的网站，比如这个网站
https://www.playpcesor.com/2023/02/chatgpt-ai.html
https://www.vpndada.com/best-vpns-for-china-cn/
导出为离线HTML和离线markdown很正常，但是保存为Textbundle或者导出md+assets却失败，总是下载不下来图片，而如果是国内网站就没有这个问题

**Comment by Kenshin** [comment]
> 但是保存为Textbundle或者导出md+assets却失败

感觉是你代理的问题，试试开全局。因为这两个都需要通过同步助手下载图片。

> 我刚才用腾讯云测试了一下，少数派正常上传，其他网站正常上传，我发给你的两个网站还是一样，在上传的时候也会显示上传成功，但是实际并没有上传进图库中

确实如此 😂 谢谢详细测试。

应该是 PicGo 的问题，它会按照图片的名称进行上传，但好像有个 Bug 导致的，之前有用户反馈过类似的问题，PicGo 那边说会修改。
