### ISSUE TITLE
Telegram上的simpread_bot发任何信息没有反应

### ISSUE THREAD

**Issue by echogyh** [Kenshin/simpread#5235]
在telegram上向simpread_bot发/start，/help，/token，/remove都没有任何反应，我试过stop and block bot之后restart，发送这些指令，还是没有收到任何反应。
![Screenshot 2023-02-24 202245](https://user-images.githubusercontent.com/3488636/221178248-0dc0068e-69cc-4904-a127-2ef89c6d4020.png)
但是我的telegram可以正常浏览其他channel的信息，这是什么原因呢？

**Comment by Kenshin** [comment]
嗨，这个服务新月底流量用完，暂时无法使用了，预计三天后恢复。

**Comment by Kenshin** [comment]
@zhaoxian-afra 

嗨，你的问题集中到这里回复 https://github.com/Kenshin/simpread/issues/5235#issuecomment-1443766791

**Comment by Miaoyifei-mz** [comment]
@Kenshin 你好，我今天在telegram上向simpread_bot发/start，/help，/token，/remove也没有任何反应

**Comment by Kenshin** [comment]
@Miaoyifei-mz 

嗨，这个功能暂时下线了，因为会有个大版本更新，上线后会在这里通知~
