### ISSUE TITLE
检查本地快照是有的，但是数据修复显示没有任何稍后读数据。

### ISSUE THREAD

**Issue by chipsflying** [Kenshin/simpread#5236]
![image](https://user-images.githubusercontent.com/102506599/221184021-6e224628-a63f-4744-9367-5f4c316a1d3e.png)
查找重复数据的结果。
![image](https://user-images.githubusercontent.com/102506599/221184162-eb36813e-edd8-4464-bc74-66d248cec053.png)
数据修复的结果。
![image](https://user-images.githubusercontent.com/102506599/221184467-02a55de2-38e7-4257-b685-cccf6d4d52ac.png)
自动同步是打开的。
实验了下，数据统计也是读取不到数据。
浏览器是Microsoft Edge Dev。

**Comment by Kenshin** [comment]
本地快照与本地稍后读数据是两个概念。

- 本地快照 → 一般指 `output` 文件夹里面的 HTML 文件

- 稍后读数据 → 一般指 `simpread_config.json` 通过同步助手的「同步」标签下的路径一定，一般跟 output 文件夹处于同一级目录。

**Comment by chipsflying** [comment]
我发现打开稍后读，列表已经什么都没有了……
所以我的问题出在哪？如何解决呢？

**Comment by Kenshin** [comment]
> 我发现打开稍后读，列表已经什么都没有了

原来是有的？

看下你自己的同步路径下是否存在 `simpread_config.json` 吗？（下图所示位置）

<img width="668" alt="image" src="https://user-images.githubusercontent.com/81074/221331317-9c46061c-28c4-4e25-95b5-29320ee61141.png">

你之前的第二个截图提示「没有稍后读数据」就是因为 `simpread_config.json` 不存在或者对应的稍后读数据不存在的提示。

> 如何解决呢？

一般来说，使用这个功能的话，都会使用坚果云（或类似网盘），可以使用这些网盘的历史记录，利用历史记录还原。

如何还原看 https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a#gSUyk 

简悦 1.2.0 也带了历史记录，如果你使用了这个功能也可以试试简悦自己的历史记录。

***

一般来说使用「数据修复」的前提是：无法进入稍后读或选项页，所以你是因为这个原因？还是？

**Comment by chipsflying** [comment]
还原了之前的simpread_config.json，现在列表有了。谢谢！
我进入数据修复的原因是我output文件夹里一直有序号重复的情况，如：
![image](https://user-images.githubusercontent.com/102506599/221350543-2c0c8284-6a26-415b-9764-6e850788b42d.png)
打开稍后读的效果就是文不对题。

**Comment by Kenshin** [comment]
> 我进入数据修复的原因是我output文件夹里一直有序号重复的情况

查找重复数据是这个地址 http://localhost:7026/database/snapshot

你之前使用的是：修复配置文件 http://localhost:7026/database/fixed （对于你来说不需要用这个。

PS：历史记录的话，可以试试 [新功能](https://simpread.pro/docs/%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95)。

PPS：看你的 ID 也不少了，可以试试 http://localhost:7026/database/statistics 里面的 2022 报表功能，来点「成就感」😂

***

不过，在留存好 `simpread_config.json` 前提下，再试试 http://localhost:7026/database/fixed （并不是只有配置文件损坏才能使用。

看看能否重现你提到的问题，如果能复现的话，能否录屏发上来，我看看是如何产生的？

另外，这个功能也可以看下 [B站视频](https://www.bilibili.com/video/BV1b24y1J7FM/) 的视频操作。
