### ISSUE TITLE
无法使用阅读模式

### ISSUE THREAD

**Issue by HaloTT** [Kenshin/simpread#5238]
icon变红色，点击进入阅读模式，白屏，没成功过。卸载重装过，问题没改善，不知道还需要提供什么
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/30413147/221291007-ac33ab6f-7117-4df9-9250-c8c8661efe81.png">

**Comment by HaloTT** [comment]
其他网站也是如此

**Comment by HaloTT** [comment]
有时进入阅读模式后，只有一屏内容，无法滚动，所有按钮无法点击，假死

**Comment by Kenshin** [comment]
估计是其他扩展干扰造成的。
请在隐私模式下，仅启用简悦排除其他扩展干扰。

**Comment by HaloTT** [comment]
是的，确实是一个护眼插件冲突了

**Comment by Kenshin** [comment]
okay 解决就好~
