### ISSUE TITLE
在 Windows 11 使用 chrome 插件进入阅读模式后点击右下角「三个点」没有任何反应

### ISSUE THREAD

**Issue by ulic-youthlic** [Kenshin/simpread#5240]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Windows11 22H2**

- 浏览器版本 **Chrome 109.0.5414.75**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://weilining.github.io/294.html> 和 <https://juejin.cn/post/7145351315705577485> 以及我所尝试过的所有网页

**进入阅读模式后点击右下角「三个点」没有任何反应**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
<img width="349" alt="image" src="https://user-images.githubusercontent.com/121918198/221331063-3c7548b7-a2a1-40e4-b907-3fc5dba8ff59.png">

**Comment by Kenshin** [comment]
估计是其他扩展干扰造成的。
请在隐私模式下，仅启用简悦排除其他扩展干扰。

**Comment by ulic-youthlic** [comment]
在隐私模式下单独开启间悦确实能够使用，目前正在排查中😂

Kenshin Wang ***@***.***> 于2023年2月25日周六 10:30写道：
