### ISSUE TITLE
教程中提到的几种稍后读布局如何开启

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5242]
就是[此链接](https://www.yuque.com/kenshin/simpread/egd0of#219a8d76)中提到的三种，眼馋，不知道怎么用

**Comment by Kenshin** [comment]
嗨，说明文档 [在这里](https://simpread.pro/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80)
