### ISSUE TITLE
支付成功无法绑定

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5243]
RT

**Comment by Kenshin** [comment]
...

你你这样会暴露你自己定相关信息，我先删除相关信息了。

明天确认下。

**Comment by Kenshin** [comment]
另外，没有记录的原因也可能是没有提交或提交的 Email 不是你提供的。

**Comment by AugustTuan** [comment]
> 另外，没有记录的原因也可能是没有提交或提交的 Email 不是你提供的。

![image](https://user-images.githubusercontent.com/37429029/221360733-26785eac-7b85-4cc1-a99e-0d9fa3321475.png)

这是我当时支付以后，邮箱收到的短信。
我确定自己的支付宝帐号和邮箱都截图了。 
和兑换上填写的无误

**Comment by Kenshin** [comment]
能收到 Email 就没问题，即便没有收到邮件，有查到订单号就可以。

我明天确认完回复你吧…

**Comment by Kenshin** [comment]
你的 Email 没问题，只是输入的 License 错了... 至于正确是哪个？的仔细看你发的内容就知道了
