### ISSUE TITLE
自动化辅助增强失效

### ISSUE THREAD

**Issue by alan16742** [Kenshin/simpread#5244]
起因：使用简悦网络剪藏更换成了坚果云配置文件，自动化辅助就失效了。
具体表现：当输入导出快捷键“o b”后保存设置，在当前的页面有效，一旦刷新就会变成空白
如图所示![20230225213949658](https://user-images.githubusercontent.com/67932758/221360305-e0c4359d-feb4-4be1-aab5-921400fb3052.png)
后面尝试更换成本地配置文件，重装简悦扩展，重启浏览器或电脑都无效

**Comment by Kenshin** [comment]
估计是这个问题造成的 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by alan16742** [comment]
在和文档对比后，我发现只是曾经开启过同步助手，关闭同步助手已经很长时间了，所以并不存在自动同步问题。同时我按照文档操作后得到的结果与之前相同，这个问题可能并非同步助手造成。

**Comment by Kenshin** [comment]
如果是没有运行同步助手的话，在 https://sspai.com/post/71576 测试，修改自动化辅助增强的设置并保存后重启浏览器。

如果还是不行的话，就在隐身模式下，仅启用简悦来排除其他扩展干扰造成的问题。

**Comment by alan16742** [comment]
在仅用简悦扩展的情况下，发现在隐身模式下仍然是原来的结果
![20230225225015317](https://user-images.githubusercontent.com/67932758/221363526-31734ea5-1d2c-4d19-a46d-ba01b954afb0.png)
仅能在保存快捷键后作用在当前网页，但是当前网页打开自动化辅助设置也是空白，一旦切换到其他网页就是无效

**Comment by alan16742** [comment]
补充：使用同步助手应用后按照文档操作依然无效

**Comment by Kenshin** [comment]
那就很奇怪了。

1. 导出配置文件。
2. 删除并重新安装简悦。
3. 重新导入配置文件。

另外，多测试一些不同的简悦插件，看下是不是仍有这个问题？并留意下图所示的截图。

<img width="878" alt="image" src="https://user-images.githubusercontent.com/81074/221393137-d04702f8-4e96-4c34-adb9-bbe39384049e.png">

如果确认上述操作无任何问题的话，试试更换不同的浏览器。或者告诉我你的浏览器详细信息。

**Comment by alan16742** [comment]
更换成brave浏览器，发现这并非浏览器问题，问题出现原因未知。经过尝试，发现可以通过“重置当前配置文件”来重置，之后再“清除本地所有插件”，最后重新安装再将你的设置手动恢复即可解决
![20230226135953844](https://user-images.githubusercontent.com/67932758/221394958-b27980bf-5916-410e-af5c-084134984383.png)
![20230226140249462](https://user-images.githubusercontent.com/67932758/221395015-114139b3-e154-4ae2-b2b6-c4db396c8511.png)
最后效果
![20230226140548543](https://user-images.githubusercontent.com/67932758/221395098-6fbf410e-dbe4-4604-a698-bb6a8209117f.png)
重置前切记要记住你的所有设置！！！

**Comment by Kenshin** [comment]
> 更换成brave浏览器，发现这并非浏览器问题，问题出现原因未知。经过尝试，发现可以通过“重置当前配置文件”来重置，之后再“清除本地所有插件”，最后重新安装再将你的设置手动恢复即可解决

我不是告诉你测试步骤了吗... 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/81074/221396122-3668c731-3ce2-4d82-a71f-cfd230a139b8.png">

也就是说，当删除并重新安装时，你可以理解 **自动使用了“清除本地所有插件”**...

**Comment by alan16742** [comment]
昨晚确实是删除并重新安装了简悦，但是仍然无效，只是今天分开多次重置才恢复了，一次性导入我的配置文件结果自动化工具还是无效，只有手动添加设置才生效了

**Comment by Kenshin** [comment]
> 昨晚确实是删除并重新安装了简悦，但是仍然无效，只是今天分开多次重置才恢复了，一次性导入我的配置文件结果自动化工具还是无效，只有手动添加设置才生效了

不会这样的 😂 肯定还是你多做了什么（或少做了什么...

不过，解决就好。

假设是 Bug 的话，因为你不可能 100% 复现它，也很难找出这个 Bug 😂

***

重新安装简悦 → 导出配置文件 → 从配置文件导入插件，就这三个步骤。

**Comment by Kenshin** [comment]
okay 我知道了，因为你的自动化增加了一个已经被删除的服务导致的...

谢谢提示。
