### ISSUE TITLE
请问简悦的标题提取逻辑有哪些？

### ISSUE THREAD

**Issue by Alice-Shi** [Kenshin/simpread#5249]
我尝试通过一个网页的 tile 来匹配相应的下载下来的 html 文件，但是发现有一些逻辑不大明白，比如：

《ChatGPT实测记录，能代替营养师吗？》[🌐](https://mp.weixin.qq.com/s/CFTDtGtEnziKL12At7xsYw)
上面这个网页保存为 html 后的标题是 `ChatGPT 实测记录，能代替营养师吗？`
人为在`ChatGPT`后面加了一个空格；

《中国医保改革个人账户“缩水”，多地老年人抗议 - 纽约时报中文网》[🌐](https://cn.nytimes.com/china/20230224/china-health-insurance-protests/dual/)
上面这个网页保存为 html 后的标题是 `中国医保改革个人账户 “缩水”，多地老年人抗议 - 纽约时报中文网`
人为在`“缩水”`前面加了一个空格。

想问一下作者简阅提取一篇文章标题的逻辑有哪些吗？
因为我在设计自己的一个自动化流程——通过当前网页的 title 来定位和打开本地 标注模式下的 html 相关文件。思路：
1. 提取当前网页的 title 来对本地 html 进行匹配 以找到 id；
2. 合成 url `http://localhost:7026/unread/id` 并在浏览器中打开。

在许多网站中运行是没问题的，但是如上两个网站则不行，所以希望可以解决这个问题。或者是否可以给一个选项，用**原文章的标题**来命名本地导出的文件（html、标注 等等），这样我这边就不用辛苦一一适配了😂

**Comment by Kenshin** [comment]
哈哈，是这样的，其实很简单，就两点：

1. 标题的中英文，标点会自动加空格。
2. 因为保存的文件名以标题为标准，当文件名有一些特殊字符出现时，会出现无法保存的问题，所以这些特殊字符被正则掉了。

正则规则

```
    return title.replace( /:/ig, '：' )
                .replace( /\?/ig, '？' )
                .replace( /\/|\*|\||<|>|\.|,|=/ig, '_' )
                .replace( /\\/ig, '-' )
                .replace( /%/ig, '％' )
                .replace( /;/ig, '；' )
                .replace( /"/ig, '' )
                .replace( /\[/ig, '【' )
                .replace( /\]/ig, '】' )
                .replace( /#/ig, '' )
                .trim();
```

> 通过当前网页的 title 来定位和打开本地 标注模式下的 html 相关文件

你可以说说你要实现的方式细节，或许我能帮到你。如果你能检索到某些特定的 HTML 内容就能得到这个稍后读  `idx`

**Comment by Alice-Shi** [comment]
我具体的思路是这样的：

假设我们在一个`已加入稍后读 & 有html文件保存到本地的`网页 👉 《ChatGPT实测记录，能代替营养师吗？》🌐https://mp.weixin.qq.com/s/CFTDtGtEnziKL12At7xsYw

1. 用 macOS 的 Keyboard Maestro 提取 当前网页的 title 得到👉 `ChatGPT实测记录，能代替营养师吗？`
2. 用一些代码将提取到的 title 变成 `简阅的修改版 title`，这里是`ChatGPT 实测记录，能代替营养师吗？`
3. 用`简阅的修改版 title`检索 本地 output 文件夹的所有 html 文件，假如名称匹配，则提取该文件 idx
4. 用 idx 合成链接 `http://localhost:7026/unread/idx` 并在默认浏览器中打开

我遇到的无法解决的问题是第2步，不知道用怎样的代码实现。

**Comment by Kenshin** [comment]
有两个解决思路：

1. 不要获取 `title` 如果能得到你例子中的 URL，直接检索 `simpread_config.json` 就行。（我不了解 `Keyboard Maestro` 不清除它是否可以做到我说的这点。

2. 我可以出一个插件，直接显示这个稍后读的 `idx`  e.g. 在网页的标题前加入

    <img width="1014" alt="image" src="https://user-images.githubusercontent.com/81074/221465929-a77fe758-2188-418d-a9c3-f0ff05d65352.png">

    你直接读取它就行了（但还是以 `idx` 为读取目标，而不要以整个标题为读取目标）
    
***

我只是好奇：

> 假设有了这个 `Keyboard Maestro` 后，你打算在什么情况下使用它？

**Comment by Alice-Shi** [comment]
#### Why
对于一个简阅本地 note 来说，十分方便通过点击一个 link 直接定位到 源网页/ 本地稍后读页面。但假如是从源网页、在浏览器中打开的稍后读页面 打开本地相关 note，则比较麻烦。相信跟大多数用户一样，通常要经历几个步骤：
1. 复制该 源网页 / 本地稍后读页面 的标题
2. 去到 Obsidian 应用里面打开搜索栏
3. 复制粘贴搜寻 ➔ 点击目标 note
所以我尝试用 macOS 的自动化工具 Keyboard Maestro 来帮助我优化这个过程，期间发现解决不了的问题，于是在这发帖求助。

##### 或许你会好奇，为啥要在 源网页/本地 html 文件 与 对应 note(对我来说是 Obsidian 上的 note)之间切换呢？
- 比如我一边标注着某个网页，突然有想要写下的 comment，会想着跳转到该文的 Obsidian 笔记，用QuickAdd 记录下此刻自己的 comment。
- 再比如将来简阅推出了 图文夹杂的标注功能，我想快速定位到这篇网页的相关 note 来测试看看效果如何

##### 或许你再会好奇，为啥要在源网页 & 本地 html 文件之间切换呢？
比如像语雀这样，第一次进入阅读模式的标注，跳转到原文相应位置的功能 可能在第二次进入阅读模式后失效。因此为了保证所有标注的正确跳转。我会在第一次标注过后，之后每次的标注都在本地 html 上而非源网页上进行。但有的时候，又想跳转到源网页看一看文章的评论或更新（假设，比如哪天你对简阅的某个文档作了内容的增删）。

综上，我发现自己日常有个需求：在源网页、稍后读页面(本地 html 文件)、本地 note(自动添加到 Obsidian 的该文 note)之间相互切换。

#### How 如何解决这个问题呢？
我想或许可以这样，对于加入过稍后读列表的网页：
- 在进入阅读模式后，标题前面加上 idx；
- 在进入本地稍后读页面的标题前面加上 idx；
这样的话**我这边**就可以快速提取到 idx 以打开相应 Obsidian 笔记。

或者，对于加入过稍后读列表的网页：
- 在进入阅读模式后，文章第一行显示稍后读的链接 👉 `http://localhost:7026/unread/idx`
- 在本地稍后读页面里面的第一行，显示源网页链接
这样的话**所有用户**可以通过一次点击便跳转到相应页面。

**Comment by Kenshin** [comment]
> 对于一个简阅本地 note 来说，十分方便通过点击一个 link 直接定位到 源网页/ 本地稍后读页面。但假如是从源网页、在浏览器中打开的稍后读页面 打开本地相关 note，则比较麻烦。相信跟大多数用户一样

你可以直接打开  http://localhost:7026/unread 查看全部列表。

> 我想或许可以这样，对于加入过稍后读列表的网页：

这个其实跟我说的就差不多了。就是在页面某个地方加上 `idx`。

> **不过，有个地方刚才讨论的时候考虑错了，在标题上加 `idx` 会有些问题，所以思路没有改变，但具体实施就需要改变下了，我需要考虑下。**


**重要：** 换个角度说，你的诉求其实是：

> 在原网页上点击某个地方（ e.g. 某个按钮），直接打开 `http://localhost:7026/unread/idx` 是吗？

**Comment by Kenshin** [comment]
> 在稍后读页面添加原网页的链接。

这个一直都的

<img width="220" alt="image" src="https://user-images.githubusercontent.com/81074/221553539-3b679408-5eb1-4deb-9492-0e42a53d9a52.png">

> 希望在原网页的阅读模式 及 稍后读页面 都能加入 idx；

可以的

但... 跟你说的 `http://localhost:7026/unread/idx` 好像没有关系了...（还是说你刚才描述有误？

**Comment by Alice-Shi** [comment]
不好意思我概念混淆了，其实我这里▼说的**稍后读页面**意指本地 html 文件。

> 希望在原网页的阅读模式 及 稍后读页面 都能加入 idx；

而这个需求▼

> * 希望在原网页的阅读模式 及 稍后读页面 都能加入 `idx`；
> * 在稍后读页面添加原网页的链接。

应该改为 **希望 _在原网页的阅读模式页面中_ 加入 idx 和 原网页链接**。这样的话，我就可以轻松从阅读模式里提取 `idx` 跳转打开本地 note、点击原网页链接以进入原网页，同时也可以从本地 html 文件直接打开原网页了。

对了我平时基本不用 `http://localhost:7026/unread` 来查看列表。而是直接到本地 output 文件夹里面去查询。当想要以**可标注模式**打开一个本地 html 文件的时候，会用正则抓取该文件的 idx 并用浏览器打开`http://localhost:7026/unread/idx`页面。不知道有没有用户跟我一样 😂

**Comment by Kenshin** [comment]
okay 你是想：

> 在阅读模式中直接打开这个页面对应的本地快照 e.g. `http://localhost:7026/unread/idx`

后续我会考虑之前讨论的方式，以插件的形式来辅助你完成这个过程。

**Comment by Alice-Shi** [comment]
是的，期待。

并且希望在下面这个本地快照里面可以添加 原网页链接

> > 本地快照 e.g. `http://localhost:7026/unread/idx`

**Comment by Kenshin** [comment]
> 并且希望在下面这个本地快照里面可以添加 原网页链接

一直都有的 😂

<img width="404" alt="image" src="https://user-images.githubusercontent.com/81074/221749964-ed4cf694-6f02-4eb8-b46e-77f82434d172.png">

**Comment by Alice-Shi** [comment]
> 一直都有的 😂

但我不用 😜

> 我平时基本不用 `http://localhost:7026/unread` 来查看列表。而是直接到本地 output 文件夹里面去查询。当想要以**可标注模式**打开一个本地 html 文件的时候，会用正则抓取该文件的 idx 并用浏览器打开`http://localhost:7026/unread/idx`页面。不知道有没有用户跟我一样 😂

**Comment by Alice-Shi** [comment]
> 一直都有的 😂
> 
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/81074/221749964-ed4cf694-6f02-4eb8-b46e-77f82434d172.png">

我找到啦hhhhh，原来在快照的左上角

**Comment by Kenshin** [comment]
😱😓😅👍

**Comment by Alice-Shi** [comment]
> 2\. 我可以出一个插件，直接显示这个稍后读的 `idx`  e.g. 在网页的标题前加入

十分期待 😆

**Comment by baresibest** [comment]
对于网页标题的问题提问如下：
如何实现将<title>的字段和网页中的某一字段合并为标题？我这里好像无效
![1679743781923(1)](https://user-images.githubusercontent.com/3355824/227714863-714eccd6-a229-4de3-bf91-e5c0c6bd16aa.png)

**Comment by baresibest** [comment]
> 😱😓😅👍

求助。

**Comment by baresibest** [comment]
> 对于网页标题的问题提问如下：
> 如何实现将<title>的字段和网页中的某一字段合并为标题？我这里好像无效
![1679743781923(1)](https://user-images.githubusercontent.com/3355824/227715667-60aaa4de-666c-4dbf-b38d-035bed327e65.png)

**Comment by Astro-Aionia** [comment]
> 哈哈，是这样的，其实很简单，就两点：
> 
> 1. 标题的中英文，标点会自动加空格。
> 2. 因为保存的文件名以标题为标准，当文件名有一些特殊字符出现时，会出现无法保存的问题，所以这些特殊字符被正则掉了。
> 
> 正则规则
> 
> ```
>     return title.replace( /:/ig, '：' )
>                 .replace( /\?/ig, '？' )
>                 .replace( /\/|\*|\||<|>|\.|,|=/ig, '_' )
>                 .replace( /\\/ig, '-' )
>                 .replace( /%/ig, '％' )
>                 .replace( /;/ig, '；' )
>                 .replace( /"/ig, '' )
>                 .replace( /\[/ig, '【' )
>                 .replace( /\]/ig, '】' )
>                 .replace( /#/ig, '' )
>                 .trim();
> ```
> 
> > 通过当前网页的 title 来定位和打开本地 标注模式下的 html 相关文件
> 
> 你可以说说你要实现的方式细节，或许我能帮到你。如果你能检索到某些特定的 HTML 内容就能得到这个稍后读 `idx`

请问这个规则可以在简悦的偏好设置里修改吗？

**Comment by Kenshin** [comment]
@Astro-Aionia 

暂时不支持定制。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
