### ISSUE TITLE
Dropbox 授权无法跳转

### ISSUE THREAD

**Issue by Vstory** [Kenshin/simpread#5251]
**请说明发生问题的环境**

- 操作系统 
  Windows 版本22H2(0S内部版本22621.1343)

- 浏览器版本 
  Chrome 版本 112.0.5596.2（正式版本）dev （64 位）

- 简悦版本 
  2.2.0.520

**请描述你的问题**
授权Dropbox时，无法跳转认证。详情请看视频

广告拦截以及油猴插件等扩展，均不在活动中。

https://user-images.githubusercontent.com/20795557/221596198-1c195b11-d7ef-4dc3-ba56-62007804f771.mp4

**截图**

请看上述视频。

**Comment by Kenshin** [comment]
嗨，我刚才测试了下，是没问题的，建议换个浏览器试试。

不过，我不建议使用 Dropbox 作为同步盘方案，因为它的 API 改了后导致很多功能都比较「麻烦」。
