### ISSUE TITLE
Notion 高级版的一些使用疑问

### ISSUE THREAD

**Issue by icegaomu** [Kenshin/simpread#5252]
您好，关于notion高级版的配置，都只能实现文章的导入，但是一直无法实现笔记的同步，我的文件夹结构和您写的一样，以下所有配置均完全按照您的流程做的但是无法实现那个测试网页的预置笔记的查看。非常感谢您的工作，麻烦指点一下问题可能出在哪里呢？

![image](https://user-images.githubusercontent.com/78406623/221631531-cdbfa34d-abc0-4163-81a8-7b71998862ee.png)
![image](https://user-images.githubusercontent.com/78406623/221631550-8f064ac9-5a2e-4692-bd1e-9aab492e8379.png)
![image](https://user-images.githubusercontent.com/78406623/221631731-24e50418-7652-4fbe-95c6-8bb8b2a4932a.png)
![image](https://user-images.githubusercontent.com/78406623/221631774-84178fd2-d944-4bcf-a526-b3ccc5322912.png)

**Comment by Kenshin** [comment]
嗨，关于标注自动化的教程 [请看这里](https://www.yuque.com/kenshin/simpread/zx3bcz#LfsOs)

**Comment by icegaomu** [comment]
![image](https://user-images.githubusercontent.com/78406623/221743624-87771e0e-8b30-4560-87bd-6e2d5cc6d3d8.png)
关于开启了自动化之后，每次笔记的标注更新都会弹出四个窗口，感觉还是比较影响阅读体验，不知后续能否优化一下保持的提示方式，做一些静默提示，弹出的方式很容易分散注意力，非常感谢！
按照上面的教程我能够自动导入笔记了，但是他导入标注的时候前面的笔记是不会删除的就导致我有一系列的文件，请问这是什么地方授权出问题了吗？还想问一下有没有可能改为直接把标注放到原先存在的文档中，这样应该是最好的体验感谢！
![image](https://user-images.githubusercontent.com/78406623/221756121-d128bbe3-4623-4daa-88c8-b3ad000581af.png)

**Comment by Kenshin** [comment]
> 关于开启了自动化之后，每次笔记的标注更新都会弹出四个窗口，感觉还是比较影响阅读体验，不知后续能否优化一下保持的提示方式，做一些静默提示，弹出的方式很容易分散注意力，非常感谢！

会的。

> 按照上面的教程我能够自动导入笔记了，但是他导入标注的时候前面的笔记是不会删除的就导致我有一系列的文件

Notion API 并没有太好的 更新 API，所以目前的做法是：

- 删除旧的 Page
- 添加一个新的 Page

你可以在 https://sspai.com/post/69972 上面测试，测试时：

1. 关闭 Notion Page（也就是关闭 `notion.so` 这个 Tab

2. 标注时，稍微慢点（仅仅用来测试），当提示更新后，再标注一次。

然后看下更新到 Notion 的 `xxxx@annote` 仅有一个 Page。

> 还想问一下有没有可能改为直接把标注放到原先存在的文档中，这样应该是最好的体验感谢！

暂时没有，如果 Notion API 支持更好的 update 方案，简悦这边也会支持。
