### ISSUE TITLE
点击助手无反应，重装依然如此

### ISSUE THREAD

**Issue by ZED21King** [Kenshin/simpread#5256]
![image](https://user-images.githubusercontent.com/100110105/221769054-16e6ddf2-34f0-4f34-8abd-eba4bb2893fa.png)

**Comment by ZED21King** [comment]
无法打开，我也就无法导出md文档，请问如何解决

**Comment by Kenshin** [comment]
emmm

是首次使用同步助手还是升级到 1.2.0 ？你是什么系统？提供的信息太少了，我没法判断。

一般不会出现无法运行同步助手的，也就是说运行后失败的话，势必会有一些提示的等信息。

**Comment by ZED21King** [comment]
> emmm
> 
> 是首次使用同步助手还是升级到 1.2.0 ？你是什么系统？提供的信息太少了，我没法判断。
> 
> 一般不会出现无法运行同步助手的，也就是说运行后失败的话，势必会有一些提示的等信息。

我是windows11，好像也没有运行失败，主要是没有什么提示信息，本来昨天用的都好好的
![image](https://user-images.githubusercontent.com/100110105/221833207-d68eb180-92e8-4ecd-bbf8-56b257709a52.png)

**Comment by ZED21King** [comment]
> emmm
> 
> 是首次使用同步助手还是升级到 1.2.0 ？你是什么系统？提供的信息太少了，我没法判断。
> 
> 一般不会出现无法运行同步助手的，也就是说运行后失败的话，势必会有一些提示的等信息。

我已经用了好久了，本来是google浏览器再用，后来它用不了我就换了edge浏览器，谁知道用了几天它又不行了，点了没反应，也没报错

**Comment by Kenshin** [comment]
我没理解你的「问题」...

是扩展端不好使？还是同步助手？这是两个东西。

你截图指向的是扩展端...

**Comment by Kenshin** [comment]
如果是扩展端的话，试试**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by ZED21King** [comment]
> 我没理解你的「问题」...
> 
> 是扩展端不好使？还是同步助手？这是两个东西。
> 
> 你截图指向的是扩展端...
是浏览器扩展啊，我要网页用不了简悦，点击没反应，但是是可以进入阅读模式，就是不能点击按钮，弹出其他功能，很奇怪

**Comment by Kenshin** [comment]
1. 试试 https://github.com/Kenshin/simpread/issues/5256#issuecomment-1448016873
2. 如果没有使用同步助手的话，导出你的配置文件，然后再重新安装简悦后导入你的配置文件。

你之前的描述和标题都有误，一般来说「助手」指的是简悦的同步助手，这是 Desktop App 服务器端。

<img width="481" alt="image" src="https://user-images.githubusercontent.com/81074/222034127-29266e48-5651-4c4e-9284-e013ffd90759.png">

**Comment by ZED21King** [comment]
> 1. 试试 [点击助手无反应，重装依然如此 #5256 (comment)](https://github.com/Kenshin/simpread/issues/5256#issuecomment-1448016873)
> 2. 如果没有使用同步助手的话，导出你的配置文件，然后再重新安装简悦后导入你的配置文件。
> 
> 你之前的描述和标题都有误，一般来说「助手」指的是简悦的同步助手，这是 Desktop App 服务器端。
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/81074/222034127-29266e48-5651-4c4e-9284-e013ffd90759.png">

我的意思是：使用简约助手的扩展端，按键无效！！！我想使用导出功能都无法做到
![image](https://user-images.githubusercontent.com/100110105/222809363-bb795ad9-389a-4c50-a3d7-fce5d9c8733c.png)
