### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by GanMocai** [Kenshin/simpread#5262]
发生问题的地址: <http://www.gcxl.edu.cn/new/index_file2.html>

**Comment by Kenshin** [comment]
嗨，这个页面因为都是图片，所以没有使用阅读模式的必要。（不过，我也测试了一些其它方式，确实有点问题 😂

你可以试试 https://github.com/Kenshin/simpread/discussions/1554 提供的几种方案。

PS：因为这个页面比较小众且没有阅读模式需要的内容（全部都是图片），所以我关闭这个 issues 了。
