### ISSUE TITLE
同步助手开机自启以后自动最小化到托盘吗？

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5263]
如图，设置开机自启以后，每次开机，这个界面就会弹出来
是否可以设置，开机自启后，自动最小化到托盘
减少对正常使用的干扰
![image](https://user-images.githubusercontent.com/37429029/222089736-624c0010-62a2-45ba-8a88-2c36c00d1948.png)

**Comment by Kenshin** [comment]
解决方案就在你的截图中...

<img width="602" alt="image" src="https://user-images.githubusercontent.com/81074/222115888-b7d00abd-4d91-4a66-927e-fb9056399a95.png">

**Comment by AugustTuan** [comment]
> 解决方案就在你的截图中...
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/81074/222115888-b7d00abd-4d91-4a66-927e-fb9056399a95.png">

找到了，谢谢（尴尬脸

**Comment by Kenshin** [comment]
哈，小事情 😂
