### ISSUE TITLE
发现同步助手未读取到本地配置，已使用浏览器配置

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5265]
我每次下载完插件，就会弹出这个提示
![image](https://user-images.githubusercontent.com/37429029/222128022-3f56c132-61ca-4503-be50-b6c12c451c37.png)

但是我检查了一下，自己同步助手的配置是没有问题的
![image](https://user-images.githubusercontent.com/37429029/222128109-7aaaf38e-c1fc-45a1-8017-cbb98a735839.png)

![image](https://user-images.githubusercontent.com/37429029/222128172-31f022dd-6f0e-4cd8-8fba-a57ff720e430.png)

**Comment by Kenshin** [comment]
下图所示的文件不是你的配置文件.... 而是你的账户信息... 😂

<img width="273" alt="image" src="https://user-images.githubusercontent.com/81074/222128581-87116674-5d6f-44ac-8c63-2143d37d1faa.png">

关于你的问题，建议看下教程 https://www.yuque.com/kenshin/simpread/pwpnsx

**Comment by AugustTuan** [comment]
> 下图所示的文件不是你的配置文件.... 而是你的账户信息... 😂
> 
> <img alt="image" width="273" src="https://user-images.githubusercontent.com/81074/222128581-87116674-5d6f-44ac-8c63-2143d37d1faa.png">
> 
> 关于你的问题，建议看下教程 https://www.yuque.com/kenshin/simpread/pwpnsx

我按照文档的来，选择浏览器配置覆盖本地，显示配置失败
![image](https://user-images.githubusercontent.com/37429029/222131140-14ff0593-9a6b-4045-8b4f-3ab753d8dfe4.png)

![image](https://user-images.githubusercontent.com/37429029/222131087-917e6fc2-f402-4e16-b5c8-fff1406fe2bd.png)

**Comment by AugustTuan** [comment]
是因为我用的不是坚果云，而是onedrive的原因吗
