### ISSUE TITLE
新站适配：utgd.net

### ISSUE THREAD

**Issue by ychen-97** [Kenshin/simpread#5266]
如题，未适配 utgd.net.
<img width="834" alt="CleanShot 2023-03-01 at 13 47 26@2x" src="https://user-images.githubusercontent.com/95043151/222156784-389dbaed-6396-4a3e-bdc5-5280c35cbcd0.png">

**Comment by Kenshin** [comment]
可以考虑适配，适配后会通知你。

你可以试试 https://github.com/Kenshin/simpread/discussions/1554 也能解决你的问题。

**Comment by ychen-97** [comment]
感谢开发者！选中内容生成阅读模式目前可行，可以作为过渡方案！每次逛简悦github都能给我新的惊喜！

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/9aR6G3qt9y 安装。

同时因为这个站是动态加载的，所以需要将 `utgd.net` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

PS：如果在使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装此站点。
