### ISSUE TITLE
markdown模板如何修改能使标注id在编辑模式下也默认隐藏

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5267]
就是这个东西
![image](https://user-images.githubusercontent.com/69069739/222156680-07f2d62d-c61c-4cd8-be53-e712a912faa1.png)
怎样设置能让它变成这样
![image](https://user-images.githubusercontent.com/69069739/222157142-bf3d5c68-57a6-45f7-8752-d2b8947d908b.png)

之前用的模板里无效信息太多，遂改成了模板库的obsidian模板二
```
<%
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
    color  = colors[ annote.color ];
-%>
> [!<%= (annote.note? "note":"abstract")%>]+ <mark style="background-color: <%= color %>">Highlight</mark> [🧷](<{{an_int_uri}}>)[🌐](<{{an_ext_uri}}>) {{an_tags}}
{{{html_format|>|{{an_html}}}}}
<% if (annote.note) { -%>
> - 📝{{an_note}}
<% } -%>
^sran-{{an_id}}
```

改完才发现标注id不像原来那样自动放在引用里了，因为习惯使用实时预览模式所以看着有点碍事，没想到这个设置不跟配置文件走，折腾半天也没找回来原本的参考……瞎倒腾半天无果，求教

**Comment by Kenshin** [comment]
嗨，你用的哪个模板？把模板链接给我瞧瞧。

**Comment by PupupupuTong** [comment]
https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627313
这个

**Comment by PupupupuTong** [comment]
自答一下，搞定了，加个>的事，最后一行改成
`>^sran-{{an_id}}`
即可

**Comment by Kenshin** [comment]
我好像又漏掉了你的 Issues 😂 😂 😂

PS：解决就好。
