### ISSUE TITLE
看雪论坛不支持了吗？

### ISSUE THREAD

**Issue by Breathleas** [Kenshin/simpread#5269]
https://bbs.kanxue.com/thread-276252.htm

![image](https://user-images.githubusercontent.com/39123978/222309579-243af90c-2e90-4155-b36e-13938dd4f154.png)

**Comment by Kenshin** [comment]
我没办法查看这个 URL。

不过，你可以试试 https://github.com/Kenshin/simpread/discussions/1554 也能解决你的问题。
