### ISSUE TITLE
自动进入阅读模式失效？ 

### ISSUE THREAD

**Issue by ttxhxz** [Kenshin/simpread#527]
如果当前页面适配阅读模式，是否自动进入阅读模式？，这个选项已经开启，可是还是不能自动进入阅读模式

**Comment by ttxhxz** [comment]
![Snipaste_2019-06-18_00-28-00](https://user-images.githubusercontent.com/24288387/59620799-50ccd580-9160-11e9-8867-e35c5a1e23ab.png)

**Comment by Kenshin** [comment]
`自动进入阅读模式` 的前提是这个站已被适配，如果是通过智能识别适配的话，则无法自动进入阅读模式。

PS：我会更新自动进入阅读模式的一些说明文字~

**Comment by ttxhxz** [comment]
对，所以我试的是简书这个网站,但是一样不进入自动阅读模式

**Comment by Kenshin** [comment]
那应该能自动今入，才对。
你看看排除列表里面有没有简书的的域名。
另外，导出配置文件，后重置配置环境，再试试。

**Comment by ttxhxz** [comment]
可以了，我清楚数据后又卸载了一遍，然后把浏览器重新打开再下载简悦就可以了！感谢

**Comment by ttxhxz** [comment]
对了，自动进入阅读模式没问题了，但是那个从右上角把网址加入到黑名单或者排除列表都不行，必须自己去选项里面手动添加，就很繁琐

**Comment by Kenshin** [comment]
> 可以了，我清楚数据后又卸载了一遍，然后把浏览器重新打开再下载简悦就可以了！感谢

估计是之前的配置不对造成的，尤其是黑名单和排除列表。

> 对了，自动进入阅读模式没问题了，但是那个从右上角把网址加入到黑名单或者排除列表都不行，必须自己去选项里面手动添加，就很繁琐

你可以试试 `选项页 → 高级设置 → 右键菜单`

**Comment by ttxhxz** [comment]
哦哦，我一开始是通过右上角插件那里的右键菜单试的，发现不行，然后我刚刚在网页任意空白处右键菜单选到简悦里面的黑名单就可以了

**Comment by ttxhxz** [comment]
![photo_2019-06-19_14-29-07](https://user-images.githubusercontent.com/24288387/59753951-c7c8b200-92b7-11e9-800a-0a213693b095.jpg)

**Comment by ttxhxz** [comment]
![Snipaste_2019-06-19_17-28-32](https://user-images.githubusercontent.com/24288387/59754005-db741880-92b7-11e9-9b54-4763dec6acb7.png)

**Comment by ttxhxz** [comment]
![1](https://user-images.githubusercontent.com/24288387/59754074-f9da1400-92b7-11e9-91ff-378506624410.png)

**Comment by Kenshin** [comment]
点击 `右上角 简悦 icon` 是无效的，不算是 Bug ~

只有在页面点击才行...
