### ISSUE TITLE
微信公众号有的网址无法进入阅读模式

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5270]
下面这个网址
https://mp.weixin.qq.com/s/q60btDRWpjcUKch8e7-cFA
点击进入阅读模式，但是点击后没有任何反应

**Comment by Kenshin** [comment]
不过，更新下：

1. 简悦适配了公众号
2. 并不是每个公众号都有问题，但你提到的公众号并不适合使用阅读模式。
