### ISSUE TITLE
为什么每篇文章的开头都要引用第一段的内容？

### ISSUE THREAD

**Issue by ht09p6o123** [Kenshin/simpread#5271]
RT

**Comment by Kenshin** [comment]
你可以使用 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v 解决。

**Comment by Kenshin** [comment]
另外，也并不是你所说，如下图

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/81074/222399625-fecb25f1-6c95-423f-a7c8-cbe3c9d4401f.png">


但你提到的情况有可能存在，最好提供 URL 我看下。

**Comment by ht09p6o123** [comment]
我的3台不同位置的电脑都存在这个问题，无论哪个网站。  
这个BUG  非常让人生厌

https://m.mydrivers.com/newsview/894783.html
![image](https://user-images.githubusercontent.com/126762024/222414645-6153744e-9088-4ce0-8ab8-6c8164fd2b79.png)

https://news.mydrivers.com/1/894/894731.htm
![image](https://user-images.githubusercontent.com/126762024/222414880-44780c26-a001-4cf4-9c27-85e3355d55c5.png)

**Comment by ht09p6o123** [comment]
> 你可以使用 https://simpread.ksria.cn/plugins/details/vrjJ4EaJ8v 解决。

没法搞定😢
![image](https://user-images.githubusercontent.com/126762024/222415302-8c9209a5-7313-40a8-b7a3-6874d5ae7e4f.png)

**Comment by Kenshin** [comment]
这不是 Bug，而是这个页面就是这么设置的，简悦只是读取了而已。

<img width="1816" alt="image" src="https://user-images.githubusercontent.com/81074/222416347-f29583da-e518-4210-97ad-dd6575d55295.png">

> https://github.com/Kenshin/simpread/issues/5271#issuecomment-1451715284

<img width="902" alt="image" src="https://user-images.githubusercontent.com/81074/222416497-6e0a153e-cb70-4c36-bee9-3fb8e5d9f58f.png">
