### ISSUE TITLE
无法触发notion增强

### ISSUE THREAD

**Issue by setarcox** [Kenshin/simpread#5272]
macOS13.1
Chrome 110.0.5481.177    和Arc0.91.1
简悦2.2
发生问题的地址：普遍存在
问题：
1、导入notion可用，但是触发导入notion辅助增强一直在“稍后”，没法触发。换了两个浏览器都是这个问题。检查设置似乎没问题。

谢谢！
![Snipaste_2023-03-03_03-00-21](https://user-images.githubusercontent.com/48019741/222526237-da6ee077-e1c0-4262-9cc7-5b980344aa79.jpg)
![Snipaste_2023-03-03_02-58-07](https://user-images.githubusercontent.com/48019741/222526246-73f64b16-6479-4f21-8b7d-4697c50f2e6e.jpg)
![Snipaste_2023-03-03_02-59-21](https://user-images.githubusercontent.com/48019741/222526253-7ef23d89-1d0c-4b97-a22c-3e16a3ce04a4.jpg)

**Comment by Kenshin** [comment]
当你认为你的配置无误时，建议使用 [简悦官方模式](https://simpreadpublish.notion.site/e784eba882da452eb8f300e6cd6b195d) 重新建立一个 Page 测试。

之前有有用户反馈过：配置无误但无法导入的情况，是因为它的 Page 大概有 1000+ 个子项，因此可能存在查找失败的问题。
