### ISSUE TITLE
自动导出标注md至ob报错

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5273]
ob+asests功能，不知道又哪给整不对了，数据修复工具显示没问题，配置文件换回前天确定还正常那会儿的历史版本也没用
自动保存不干活了，手动按bbb就说保存失败。检查发现【自动化辅助增强】和【markdown辅助增强】两插件设置内容莫名清空，但是再根据教程https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590606 和https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627313 填回去也没变正常，还是报错。

**Comment by Kenshin** [comment]
同一个主题建议在一个 Issues 下讨论

https://github.com/Kenshin/simpread/issues/5275#issue-1608620173

**Comment by Kenshin** [comment]
如果是因为配置导致错误，建议使用 [清理配置文件](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e6%b8%85%e7%90%86%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6) 删除全部插件的数据…

另外一点：在折腾配置前，建议关闭自动同步然后等确定没问题的话，再开启自动同步并覆盖本地。

**Comment by PupupupuTong** [comment]
那还得请教一下之前的html（全文+标注）+html标注+md标注是怎么弄出来的，上回是大大你直接帮我改了配置文件发过来的，我不知道怎么弄，不敢用清理配置文件。。。说来它好像是在我今天折腾之前就不正常了，但我昨天以为是移动端稍后读有bug

**Comment by Kenshin** [comment]
试试历史记录功能，通过坚果云 or 简悦自带的历史功能，先找到你认为正确时间点的数据。

然后重装简悦，然后：

1. 导入这个配置文件
2. 选项页 → 插件管理 → 从配置文件导入插件
3. 覆盖本地配置文件

看看能否成功？

> 但我昨天以为是移动端稍后读有bug

你提到的现象跟你说的这个过程应该没关系

**Comment by PupupupuTong** [comment]
试过了，不行，退回4天前的版本插件设置也还是空的
