### ISSUE TITLE
深色模式下导出的html标注文件效果能否优化

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5274]
不知是否dark reader 插件影响，我这边深色模式下存下来的html文件效果比较诡异。全文还勉强能看，只是标题不太清楚，标注文件就整个没法看了。

（不知道怎么回事今天传图一直传不上去，只好走电报了，见谅）

**Comment by Kenshin** [comment]
在你的系统启用暗色模式后，手动把主题改为暗色模式以及选项页 → 高级设定 → 暗色模式（关闭它）

**Comment by Kenshin** [comment]
另外，请提供出问题的 URL 或者说你每个 URL 都是如此？

**Comment by PupupupuTong** [comment]
我用的都这样，百度知乎lofter都是的

**Comment by PupupupuTong** [comment]
>手动把主题改为暗色模式以及选项页 → 高级设定 → 暗色模式（关闭它）

操作过之后还是那样
![image](https://user-images.githubusercontent.com/69069739/222882579-bf0e1cbd-015b-43d2-bb26-4d6ec45cfb3f.png)
