### ISSUE TITLE
在 CSDN 的特定页面上经常性的无法使用标注功能

### ISSUE THREAD

**Issue by doggyone** [Kenshin/simpread#5276]
> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacOS**

- 浏览器版本 **Chromium Engine Version 110.0.5481.177**

- 简悦版本 **2.2.0.520**

- 发生问题的地址：https://blog.csdn.net/Estelle1412/article/details/121626794

**请描述你的问题**

已开启标注模式，但是选中文字后并没有标注，此时切换到其他网页可以使用，在其他网页上标注功能是正常的。

**Comment by doggyone** [comment]
补充一下：选中文字的情况下无法标注，反而是选图片的时候，标注的提示栏会弹出（选颜色的那行栏）

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题。

<img width="606" alt="image" src="https://user-images.githubusercontent.com/81074/222871711-2672b702-a793-4140-b225-f0ea0345ba9d.png">

试试：**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。
