### ISSUE TITLE
按照一站式logseq教程完成后，logseq的右侧栏简悦界面文章无法删除（已经把坚果云output里的html和logseq本地md删除了）

### ISSUE THREAD

**Issue by yueyehechuwuyueming** [Kenshin/simpread#5277]
![image](https://user-images.githubusercontent.com/62372246/222774482-9e0836ed-d14b-4a2f-a597-65261e5d8156.png)
logseq右侧简悦界面的文章添加后，无法删除
已经做的操作：
坚果云output文档已删除
![image](https://user-images.githubusercontent.com/62372246/222775781-79e70dbf-6653-496f-9dcc-205cb4874fdf.png)
logseq本地markdown已删除
![image](https://user-images.githubusercontent.com/62372246/222775894-ab441e65-e451-451e-a78b-1ef19a34ae2f.png)

操作系统 ：win11
简悦版本：2.2.0
logseq版本：0.8.18
<!--

**Comment by Kenshin** [comment]
> 坚果云output文档已删除

通过此方式并不能删除稍后读，右侧的内容可以在扩展端 → 稍后读中删除，但**此方式并不能删除本地快照（需手动在 `output` 里面删除）**。（下图所示）

<img width="532" alt="image" src="https://user-images.githubusercontent.com/81074/222871474-b6b5605c-5044-4e9b-abad-0d5d6163081c.png">


同步助手下个版本会在右侧界面提供删除功能，删除后也能同时删除本地快照。
