### ISSUE TITLE
无法打开菜单+导入obsidian插件问题

### ISSUE THREAD

**Issue by ElsieHu** [Kenshin/simpread#5278]
1. 最近几天我在使用简悦浏览网页时，都没有办法通过点击右下角三个点的按钮打开菜单。
2. 在使用导入obsidian插件设置保存路径时，它总是没有办法记住我最新修改的路径，也因此导致每次我都需要重新设置才能完成保存。
3. 基于2，我需要打开菜单重新设置；基于1，我无法打开菜单。因此目前我没有办法正常使用插件。

设备：MacBook Pro 2020
系统：Ventura 13.2.1
浏览器：edge
版本：110.0.1587.50 (正式版本) (arm64)
简悦版本：2.2.0

**Comment by Kenshin** [comment]
> 问题1

**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。另外，即便在这种情况下也没法打开的话，试试能否打开选项页或扩展端稍后读？

如果都无法打开说明你的配置文件有错误，在确保运行 **[同步助手 1.2.0](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-5086922)** 的前提下，打开 http://localhost:7026/database/fixed 并修复，修复后安装提示恢复即可。

> 问题2

应该是你没有安装插件管理器的问题，使用上面提到的链接就可以修复。

**Comment by ElsieHu** [comment]
1. 我无法在隐身模式下使用简悦；修复完成了，但是依然不能打开菜单；
2. 问题同上。

**Comment by Kenshin** [comment]
无法打开隐私模式的解决方案

<img width="676" alt="image" src="https://user-images.githubusercontent.com/81074/222943329-00277422-c0cb-456c-915a-71ad1783711a.png">

先排除是否是其它扩展造成的干扰问题。

**Comment by ElsieHu** [comment]
我按照这个图设置好之后，在隐私模式下打开网页，在菜单栏中确实显示了简悦图标，但是并不能使用（点了之后不能进入阅读模式）。


顺祝时祺
胡蝶


在 2023年3月5日 13:31，Kenshin ***@***.***> 写道：


无法打开隐私模式的解决方案
先排除是否是其它扩展造成的干扰问题。

**Comment by Kenshin** [comment]
> 我按照这个图设置好之后，在隐私模式下打开网页，在菜单栏中确实显示了简悦图标，但是并不能使用（点了之后不能进入阅读模式）。

再确认下：

> **是否也无法进入选项页或稍后读？**


如果都无法打开说明你的配置文件有错误，在确保运行 **[同步助手 1.2.0](https://github.com/Kenshin/simpread/discussions/4049#discussioncomment-5086922)** 的前提下，打开 http://localhost:7026/database/fixed 并修复，修复后安装提示恢复即可。

这个功能肯定可以修复的，如果没有修复，肯定是因为你没有安装修复后的提示操作。

**Comment by Kenshin** [comment]
emmm

> 我刚又试了修复，检查的结果是无需修复。附图如下。

那说明就没问题了。所以，不知道你是否方便使用一个新的浏览器测试。（我一直怀疑你的操作或其他问题造成的，跟简悦的配置（数据）文件无关。

**注意：**不要通过 Email 回复，我没法看到截图，你也不能添加附件...


**如果还是不行，**把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5278

我明天看下。

**Comment by ElsieHu** [comment]
> 所以，不知道你是否方便使用一个新的浏览器测试。

我一直都用edge，就算在新的浏览器里能用也意义不大。

之前的配图是这个。
<img width="920" alt="image" src="https://user-images.githubusercontent.com/105779039/223097803-7fe96d2d-d293-4575-b60f-83c56f991c99.png">

配置文件我发过去了（如果我理解的邮箱地址没错的话…）

**Comment by Kenshin** [comment]
> 我一直都用edge，就算在新的浏览器里能用也意义不大。

（假设）如果是新浏览器没问题就能排除配置文件的错误…所以你需要做的是：删除并重新安装简悦再导入配置文件就行了…

我明天看下你的配置文件。
