### ISSUE TITLE
语雀账号绑定失败

### ISSUE THREAD

**Issue by daydaydo** [Kenshin/simpread#5279]
语雀账号授权绑定失败

**Comment by Kenshin** [comment]
应该没问题的，请在选项页 → 服务 → 授权管理中授权。

**Comment by daydaydo** [comment]
![image](https://user-images.githubusercontent.com/69755941/222895324-f1dea5e2-4ae8-4c7f-ad81-b67dc87d6e82.png)
已尝试两天，提示“获取 语雀 授权失败，请重新获取“

**Comment by Kenshin** [comment]
emmm

是不是你的浏览器阻止了什么地方的调用？如 Cookies 或者看下 https://www.yuque.com/kenshin/simpread/tmmwhl 这个问题。

**Comment by daydaydo** [comment]
找到问题所在。简悦授权后会新建一个知识库，语雀免费版知识库上限是10个，新建不了知识库，所以授权失败。

**Comment by Kenshin** [comment]
原来如此… 😂
