### ISSUE TITLE
无法使用 Chrome Webstore 并提示 CRX_HEADER_INVALID

### ISSUE THREAD

**Issue by ijnvd123** [Kenshin/simpread#528]
话说这个浏览器是不是还不能完美支持chrome插件？
我下载下来不能用

**Comment by Kenshin** [comment]
应该不会的，我刚测试了 `Version 76.0.182.6 (Official build) Dev (64-bit)` 这个版本
我的你是 Edge 什么版本？从 Webstore 安装的吗？不好使是指什么现象？

**Comment by ijnvd123** [comment]
Package is invalid:'CRX_HEADER_INVALID'
77.0.189.3(后面一样)
我是官网下的CRX，但是我都不知道为啥它都不给我个安装机会就直接报错
头一次用chromium的浏览器，还不是很会用

**Comment by Kenshin** [comment]
可能是官网的 crx 与 Edege 不兼容造成的...

你无法通过 Chrome Webstore 下载吗？如果是的话，看看 [这篇内容](http://ksria.com/simpread/docs/#/FAQ?id=%e7%a6%bb%e7%ba%bf%e5%ae%89%e8%a3%85)  `在线下载 Chrome Webstore 方式`

**Comment by ijnvd123** [comment]
还是相同的错误……
也不知道为啥

发送自 Windows 10 版邮件应用

发件人: Kenshin Wang
发送时间: 2019年6月23日 12:12
收件人: Kenshin/simpread
抄送: 邸小朔; Author
主题: Re: [Kenshin/simpread] 问一下这个edge dev浏览器是不是不能用 (#528)

可能是官网的 crx 与 Edege 不兼容造成的...
你无法通过 Chrome Webstore 下载吗？如果是的话，看看 这篇内容 在线下载 Chrome Webstore 方式

**Comment by Kenshin** [comment]
@ijnvd123 
请看下这个解决办法 https://github.com/Kenshin/simpread/issues/528#issuecomment-504718137

**Comment by ijnvd123** [comment]
还是不能用……咱也是很迷了

发送自 Windows 10 版邮件应用

发件人: Kenshin Wang
发送时间: 2019年6月26日 9:13
收件人: Kenshin/simpread
抄送: 邸小朔; Mention
主题: Re: [Kenshin/simpread] 问一下这个edge dev浏览器是不是不能用 (#528)

@ijnvd123
请看下这个解决办法 #528 (comment)

**Comment by Kenshin** [comment]
这就奇怪了…
仅仅是简悦不好使吗？

**Comment by ijnvd123** [comment]
我没有试过别的插件，因为别的插件我都是从微软那儿装的，但是简悦没有微软商店的版本，我现在也打不开chrome的商店，只能下crx，但是不管从哪儿下的crx都装不上，报的错也是一样的/(ㄒoㄒ)/~~

发送自 Windows 10 版邮件应用

发件人: Kenshin Wang
发送时间: 2019年6月28日 8:10
收件人: Kenshin/simpread
抄送: 邸小朔; Mention
主题: Re: [Kenshin/simpread] 问一下这个edge dev浏览器是不是不能用 (#528)

这就奇怪了…
仅仅是简悦不好使吗？

**Comment by yinhaijiao** [comment]
同样是CRX_HEADER_INVALID错误……

**Comment by Kenshin** [comment]
> 我用chrome同样是CRX_HEADER_INVALID错误……
> 是不是因为chrome版本？

你试试 楼上  https://github.com/Kenshin/simpread/issues/528#issuecomment-504718137 的解决办法？

**Comment by yinhaijiao** [comment]
> > 我用chrome同样是CRX_HEADER_INVALID错误……
> > 是不是因为chrome版本？
> 
> 你试试 楼上 [#528 (comment)](https://github.com/Kenshin/simpread/issues/528#issuecomment-504718137) 的解决办法？

对，找到这个issues后里面的方法都试过了，就差翻墙直接安装了。

**Comment by Kenshin** [comment]
@yinhaijiao 

试试我通过 https://chrome-extension-downloader.com/ 下载并打包的 zip 文件，解压缩后安装。

[SimpRead-Reader-View-Chrome Web Store_v1.1.3.crx.zip](https://github.com/Kenshin/simpread/files/3796546/SimpRead-Reader-View-Chrome.Web.Store_v1.1.3.crx.zip)

**Comment by yinhaijiao** [comment]
还是不可以，同样的错误。
我的浏览器版本是78.0.3904.70（正式版本（64 位）mac。

**Comment by Kenshin** [comment]
真是奇怪.... 

要不 试试 这个页面 https://www.extfans.com/extension/ijllcpnolfcooahcekpamkbidhejabll/

**Comment by Kenshin** [comment]
刚才研究了下 Microsoft Edge 无法使用的问题。

应该是新版，增加了对这种操作的屏蔽，目前只能使用此方式 https://github.com/Kenshin/simptab/issues/81#issuecomment-550128949
