### ISSUE TITLE
有些网站保存到 notion， 不能保存全文

### ISSUE THREAD

**Issue by jerryc127** [Kenshin/simpread#5280]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**
  win10 22h2

- 浏览器版本 **e.g. Chrome 78.0.3904.108**
Microsoft Edge 110.0.1587.57 

- 简悦版本 **2.0.0**
 2.2.0

- 发生问题的地址 <请填写你的地址l>
https://juejin.cn/post/7132628898453880840
https://mp.weixin.qq.com/s?__biz=MzI0MzkxMDU1Ng==&mid=2247484882&idx=1&sn=5cb59eefd1372502857f3c61b5ad4eeb&key=59d5a3b9c96f560942b33c7915587c388a935c3b227bb5546ecc084c047710d751d9a150f0bb46a75eec79f6aeef1d73d637dd6cd825020e8a9148af0bccc5beb2f3bd2de1638a00a02b90db9663d2462681b982300404a4c29b3e65c5b812a978467158d2dd5b6d0d254deedd1459c5afe461ee390f5d75361d8b847b87451f&ascene=0&uin=NTY0MjU4MTM1&devicetype=Windows+10+x64&version=63080009&lang=zh_TW&exportkey=Asv5l5XBHAxj2Pve25PeaV4%3D&acctmode=0&pass_ticket=2IgNal%2FHY6Gwpo9x7OLjR%2FyAxKDhR4h4WVsOBBIjT5ZGYFwAqnKmkaiB4NRPQ0JN&wx_header=0&fontgear=2

**请描述你的问题**

使用notion插件保存全文到 notion, 不能保存全文

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

https://juejin.cn/post/7132628898453880840

```
比如我们要匹配拥有 “123” 中任意字符的字符串则需要使用 “[...]”, 需要匹配的字符只能取自方括号中的内容。另外我们也可以使用字符类去匹配指定范围，如[a-z]、[0-9]、[\u4e00-\u9fa5] 等。
```

这段之后就没有了

![image](https://user-images.githubusercontent.com/16351105/222900184-d4471eba-ba87-475b-83da-050370e15db6.png)

https://mp.weixin.qq.com/s?__biz=MzI0MzkxMDU1Ng==&mid=2247484882&idx=1&sn=5cb59eefd1372502857f3c61b5ad4eeb&key=59d5a3b9c96f560942b33c7915587c388a935c3b227bb5546ecc084c047710d751d9a150f0bb46a75eec79f6aeef1d73d637dd6cd825020e8a9148af0bccc5beb2f3bd2de1638a00a02b90db9663d2462681b982300404a4c29b3e65c5b812a978467158d2dd5b6d0d254deedd1459c5afe461ee390f5d75361d8b847b87451f&ascene=0&uin=NTY0MjU4MTM1&devicetype=Windows+10+x64&version=63080009&lang=zh_TW&exportkey=Asv5l5XBHAxj2Pve25PeaV4%3D&acctmode=0&pass_ticket=2IgNal%2FHY6Gwpo9x7OLjR%2FyAxKDhR4h4WVsOBBIjT5ZGYFwAqnKmkaiB4NRPQ0JN&wx_header=0&fontgear=2

```
首先我们可以经常听到说JS是一种单线程的语言，但是我们也知道JS中还是有异步任务的，如异步宏任务，异步微任务，而这些任务是怎么执行的呢？其实本质上是浏览器在接收到服务器响应过来的文本文件后，如HTML文件，只会分配一个线程来进行解析执行，如果遇见文件里像<link href="xxxxx">，<script src="xxxxx">这样还需要获取其他文件的依赖时，
```

这之后就断了

![image](https://user-images.githubusercontent.com/16351105/222900231-b3fa0323-eb95-49e0-8f2a-f6c9f652defc.png)

**Comment by Kenshin** [comment]
阅读模式如果正确的话，就没问题，所以阅读模式下有问题吗？

我明天确认下。

**Comment by jerryc127** [comment]
> 
阅读模式下没问题

就是不知道为什么不能全文保存到 notion

**Comment by Kenshin** [comment]
你试试导出 Markdown 到本地，如果还是有的话，就说明 Notion 有问题。

因为使用了私有 API，再加上 Notion 对 Markdown 的支持不是 100% 完美，理论上算是正常情况。（虽然很少见
