### ISSUE TITLE
Logseq本地快照中的自动化机器人失效

### ISSUE THREAD

**Issue by Minos-Z** [Kenshin/simpread#5281]
与Logseq联动后，标注的同步只在原网页中生效。
打开本地快照后的标注修改，不会被自动化机器人识别到，需要手动在设置里点生成全部后机器人才会生效。
自动化插件重装也是这样，请问是我哪里的配置出了问题吗？

**Comment by Kenshin** [comment]
> 打开本地快照后的标注修改，不会被自动化机器人识别到

如果你的本地快照类似这样的 URL `http://localhost:7026/unread/xxx` 需要加上后缀 `?embed=logseq` 例如下图所示

<img width="548" alt="image" src="https://user-images.githubusercontent.com/81074/222943451-1760e4dc-0e73-485f-9bde-c7a372831e80.png">

会看到有个 Icon，才说明是基于 Logseq 的本地快照，同时也要设置同步助手的增强导出，细节 [看这里](https://www.yuque.com/kenshin/simpread/gbere7#wUuuB)。
