### ISSUE TITLE
关于未读 Markdown 模板中 banner 字段的一些疑问

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#5282]
发现在手动框选知乎回答生成稍后读时，banner字段会出错

![Snipaste_2023-03-05_14-03-21](https://user-images.githubusercontent.com/74438973/222944418-b36fcd1e-aa04-44f3-8835-986c81e78d13.png)

```
---
title: "{{title}}"
alias: 
<% if ( unread.note && unread.title != unread.note ) { %>  - "{{note}}"
<% } %>  - "{{title}}"
created-date: {{create|yyyy-mm-dd'T'HH:MM:sso}}
type: Simpread
<% if (unread.img) { %>banner: "<%- unread.img %> "
banner_icon: 🔖
<% } -%>
tag: {{ |tag| | }}
idx: {{idx}}
---
```

**Comment by jy324** [comment]
![image](https://user-images.githubusercontent.com/74438973/222944357-f869f55f-2914-4c58-bac2-5634166670a3.png)

**Comment by jy324** [comment]
![image](https://user-images.githubusercontent.com/74438973/222944455-0d40c66a-69f4-43b9-8567-668b22a6df67.png)

**Comment by Kenshin** [comment]
emmm

随便给我一个出问题的 URL 我看下。

**Comment by jy324** [comment]
https://www.zhihu.com/question/381422480/answer/2907436197
比如这个，我截取他回答的文字部分生成稍后读，然后就会出现这种问题

**Comment by Kenshin** [comment]
okay 我明天确认下。

**Comment by Kenshin** [comment]
抱歉，漏掉了这个 issues 😂

不算是个 Bug，因为没有任何图片，所以应该是下图（注意：跟你的现象不一样）

<img width="810" alt="image" src="https://user-images.githubusercontent.com/81074/223082354-eb9babe7-96ad-4761-9d48-3abed0d1039f.png">

而不应该是你提到的这个。

<img width="618" alt="image" src="https://user-images.githubusercontent.com/81074/223082437-479f3a9e-3745-4773-8cde-cb8d05fe2e95.png">

你的这个问题只能拿到你的配置文件才能调查清楚。

***

不过，其实安装下面两个插件就能变相解决。

1. [题图](https://github.com/Kenshin/simpread/discussions/2487)

2. [模仿 Safari 阅读模式样式](https://github.com/Kenshin/simpread/discussions/1595)

**Comment by jy324** [comment]
![image](https://user-images.githubusercontent.com/74438973/223099183-4aca7242-2733-42b9-bfa4-1b069a8a0230.png)
我把加入稍后读的自动化从离线HTML改成HTML后就正常了...
现在不会出现错误了，banner 字段没了
![image](https://user-images.githubusercontent.com/74438973/223099761-1f765ede-b0b8-4227-9311-3de9c707ac51.png)
顺便问一下，您的Metadata这样显示是使用了什么插件吗？我的进阅读模式就不显示了...
![image](https://user-images.githubusercontent.com/74438973/223104193-c1b5637c-8d88-4209-8cae-92a1198e641f.png)

**Comment by Kenshin** [comment]
> 我把加入稍后读的自动化从离线HTML改成HTML后就正常了...
现在不会出现错误了，banner 字段没了

没想明白是怎么「实现」的 😂

> 顺便问一下，您的Metadata这样显示是使用了什么插件吗？我的进阅读模式就不显示了...

上一条跟你说了，是两个插件，留意上条内容。

**Comment by jy324** [comment]
这两个插件我都安装了，并且配置应该是没问题的，但是Metadata还是不能像您这样显示...是不是Ob设置的问题？
![image](https://user-images.githubusercontent.com/74438973/223166143-64eb0601-55bd-4496-a508-a721d5f2a345.png)
![image](https://user-images.githubusercontent.com/74438973/223166062-5726aba2-19e1-4f6f-82be-a5a9090824c9.png)

然后banner的问题我又仔细看了一下，确实还是没有配置对，保存原文的时候banner字段直接消失了，无论有图没图都没了...离线HTML就是这作用吗😂
现在想了想，应该还是配置文件的问题...我已经把它发到您的邮箱，请您看一看到底是哪里的问题。麻烦您了😁

**Comment by Kenshin** [comment]
> 但是Metadata还是不能像您这样显示

我没理解你说的「像我这样」显示是指什么？

- 如果是简悦部分的话，就是我提到的这两个插件。

- 如果是 Obsidian 的话，我没有安装其他特别的插件。

**Comment by jy324** [comment]
哦，没事🤣
我没开这个，所以Metadata显示的不大一样
![image](https://user-images.githubusercontent.com/74438973/223305764-262e5870-15ea-417b-ba81-0a37260666a7.png)

**Comment by Kenshin** [comment]
（≧0≦）//（-_-。）・・・

竟然是这个问题 😂

**Comment by jy324** [comment]
> 然后banner的问题我又仔细看了一下，确实还是没有配置对，保存原文的时候banner字段直接消失了，无论有图没图都没了...离线HTML就是这作用吗😂
现在想了想，应该还是配置文件的问题...我已经把它发到您的邮箱，请您看一看到底是哪里的问题。麻烦您了😁

当然，banner 的问题还是得请您看一下🤔

![image](https://user-images.githubusercontent.com/74438973/223312755-fdaef7e5-48e9-4cc0-947e-36d5ef2e004f.png)

**Comment by jy324** [comment]
undefined 也会导致出错吗？

**Comment by Kenshin** [comment]
> undefined 也会导致出错吗？

是的，这个暂时无解，除非我说的题图插件，即便没有图片的话，也设置一个图片，这个问题就自行解决了...

**Comment by jy324** [comment]
我觉得可以这样：
如果是 undefined 的话，就直接取消 banner 字段，整个banner不显示

**Comment by jy324** [comment]
哦，好像原文Metadata不能使用脚本是吧，那确实不能取消了🤣

**Comment by Kenshin** [comment]
> 我觉得可以这样： 如果是 undefined 的话，就直接取消 banner 字段，整个banner不显示

理论上每个字段都可以定制，所以其实是可以的，但有点麻烦，其实没有太大必要... 😂

**Comment by jy324** [comment]
行😂
对了，我再问您一个问题：
@annote 文件可以通过Manual Sync 重新生成，那么原文能不能重新生成呢？
（比如想要更改以前所有保存过的原文的格式）

**Comment by Kenshin** [comment]
> 那么原文能不能重新生成呢？

可以生成标注的原因是标注已经在简悦的数据中了。

**原文的话，除非有本地快照**，但这样的话，还是有些不妥，可能会太忙，因为从 HTML → Markdown 会损耗一些电脑性能。

如果没有本地快照的话，就完全不能了。

不过，我还是先 Mark 下这个需求。

**Comment by jy324** [comment]
根据我的测试，模仿Safari+题图时图片会选用正文的第一张图（即使方案为当前页的题图），并且如果将文章中的图片保存到本地，题图仍然会使用网络路径，会有404的风险。那么能否将离线保存的图片路径使用作banner路径呢？

**Comment by jy324** [comment]
> 原文的话，除非有本地快照，但这样的话，还是有些不妥，可能会太忙，因为从 HTML → Markdown 会损耗一些电脑性能。
>
> 如果没有本地快照的话，就完全不能了。
>
> 不过，我还是先 Mark 下这个需求。

我感觉可以先折中一下，比如重新生成Metadata之类的，原文确实不大好搞

我只是提个建议，因为我大概有点强迫症，前后不一致就会很难受😂

**Comment by Kenshin** [comment]
> 我感觉可以先折中一下，比如重新生成Metadata之类的，原文确实不大好搞

如果原文只有 Metadata 的话，没有什么意义... 😂

**Comment by jy324** [comment]
确实😂

**Comment by jy324** [comment]
> 根据我的测试，模仿Safari+题图时图片会选用正文的第一张图（即使方案为当前页的题图），并且如果将文章中的图片保存到本地，题图仍然会使用网络路径，会有404的风险。那么能否将离线保存的图片路径使用作banner路径呢？

所以现在有 banner 使用本地图片的路径 这一功能吗？😊

**Comment by Kenshin** [comment]
我猜 Obsidian 有可能不支持，但简悦这边是一定不支持的…

**Comment by jy324** [comment]
> 根据我的测试，模仿Safari+题图时图片会选用正文的第一张图（即使方案为当前页的题图），并且如果将文章中的图片保存到本地，题图仍然会使用网络路径，会有404的风险。那么能否将离线保存的图片路径使用作banner路径呢？

现在有 题图使用本地路径存储 这样的功能吗？🤔

**Comment by jy324** [comment]
好的，现在暂时没有什么问题了😎感谢K大的解惑😉

**Comment by Kenshin** [comment]
哈，老用户，小事情而已 😄

PS：基本上提过多次 Issues 或者同一个 Issues 有过多次交流的用户我都有印象。

**Comment by jy324** [comment]
我又来问问题了😂
请问，localhost:7026/reading/95
与
localhost:7026/unread/95
有啥区别吗

**Comment by jy324** [comment]
是跟配置库有关系吗

**Comment by Kenshin** [comment]
`localhost:7026/reading/95` → 阅读模式（只读，界面比较干净）

`localhost:7026/unread/95` → 标注模式（可标注）

**Comment by jy324** [comment]
![image](https://user-images.githubusercontent.com/74438973/224321929-01afc733-5b84-4ff3-9b04-5b19c23e94e5.png)
想问一下这个cmnt代表啥意思啊😂

**Comment by Kenshin** [comment]
这个是 Dataview 的语法 😂

**Comment by jy324** [comment]
但是 dataview 文档里没有cmnt这个东西😂
`contains(object|list|string, value)`说明cmnt应该是个object...
难道是用户自行定义的object？
但是也不对？反正看的挺懵的...

**Comment by jy324** [comment]
啊K大是不是事太多忘记这里了...😂
