### ISSUE TITLE
<请描述你的问题>

### ISSUE THREAD

**Issue by fdjkdf** [Kenshin/simpread#5283]
**小提示**

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.2.0**

- 发生问题的地址 <https://chat.openai.com/auth/error?error=OpenAI%27s%20services%20are%20not%20available%20in%20your%20country.%20(error%3Dunsupported_country)>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
你想表达什么？😂

**Comment by fdjkdf** [comment]
> 你想表达什么？😂

emm就是这个chatgpt的网页 进去就触发插件了 ，除了加黑名单的方法  是不是后台可以更新把这类的网站不要放进去

**Comment by Kenshin** [comment]
触发哪个插件？

如果是 [ChatGPT 辅助增强](https://github.com/Kenshin/simpread/discussions/4933) 的话，说明你没有按照规则设定。

<img width="897" alt="image" src="https://user-images.githubusercontent.com/81074/222950087-df94ef35-b88f-4dc1-a523-63d9c792c101.png">
