### ISSUE TITLE
导出离线markdown中base64图片编码，能否使用obsidian和logseq可直接预览的语法

### ISSUE THREAD

**Issue by ycbrd** [Kenshin/simpread#5287]
我将导出的离线markdown直接用obsidian打开，其无法识别base64图片。其实，如果将base64的编码直接以 `![img](base64编码)` 的语法放在正文相应位置，obsidian可以正常查看图片，但是目前这种将编码作为脚注的格式：
```
![][img]
[img]:base64编码
```
obsidian不认它，logseq也不行，不知道您可否考虑改变这一写法或允许自定义此处写法。
我注意到有一些[现成的方案的链接在这里](https://github.com/Kenshin/simpread/discussions/3241)。但是他们都需要安装一个新的软件，包括 textbundel, utools, quicker 或 hazel。**但我想如果简简单单改变图片插入的语法就能正常查看，我们应该没有必要借助另外的软件多一个转换步骤吧？**

**Comment by Kenshin** [comment]
直接使用 `assets + md` 方案就行，细节 [看这里](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604)。

**Comment by ycbrd** [comment]
> 直接使用 `assets + md` 方案就行，细节 [看这里](https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604)。

您好，这一方案与base64相比，图片与正文分离，在涉及移动和删除时比较繁琐。所以我在许多情况下，还是希望能正常显示base64图片。
