### ISSUE TITLE
知乎含公式网页解析错误。

### ISSUE THREAD

**Issue by B1INGO** [Kenshin/simpread#5290]
是否可以手动进入阅读模式，且阅读模式解析良好，这种情况可以手动将此 URL 加入到白名单 http://ksria.com/simpread/docs/#/FAQ?id=白名单 （支持主域名等多种模式）

出错的网址：https://zhuanlan.zhihu.com/p/431441795
1、可以进入阅读模式且解析正确
2、导入到obsidian和notion，只能正常显示很小一部分公式，**绝大多数公式**都是以源代码的形式显示
错误截图：
![image](https://user-images.githubusercontent.com/20365172/223098172-faff3300-fa26-4eb4-9958-a96816905590.png)

导入到obsidan的文件：[注意力机制 & 自注意力模型.zip](https://github.com/Kenshin/simpread/files/10897565/default.zip)
----

上述内容均无法解决，请告诉我需要适配的新站  🙏 

-->

**Comment by Kenshin** [comment]
知乎部分页面的公式确实存在：阅读模式良好但导入有存在时情况…

我明天确认下。

**Comment by B1INGO** [comment]
> 知乎部分页面的公式确实存在：阅读模式良好但导入有存在时情况…
> 
> 我明天确认下。

好的！

**Comment by Kenshin** [comment]
嗨，我这边应该是没问题的，看下图

<img width="850" alt="image" src="https://user-images.githubusercontent.com/81074/223305818-0a700895-fb6d-4451-866e-67e0b19ab392.png">

我把我导出的文件发上来，你看下 [注意力机制 & 自注意力模型.txt](https://github.com/Kenshin/simpread/files/10904873/default.txt)

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
