### ISSUE TITLE
语雀简悦手册中没有权限Notion链接无法打开

### ISSUE THREAD

**Issue by Yapwn** [Kenshin/simpread#5291]
- 操作系统 MacOS

- 浏览器版本 Microsoft Edge 版本 110.0.1587.63 (正式版本) (x86_64)

- 简悦版本 **2.0.0**

- 发生问题的地址  https://www.yuque.com/kenshin/simpread/uc4g3g
**请描述你的问题**

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/49093992/223127728-241900ce-f4ea-456b-9a0b-7eaaadcf73b0.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/49093992/223127909-2a216430-5e06-4a9b-b2c5-84517fb7cebd.png">

**Comment by Kenshin** [comment]
收到，应该是链接错了个导致的，我明天修复下。

**Comment by Kenshin** [comment]
okay 已修复，我关闭这个 issues 了。
