### ISSUE TITLE
导出markdown日期格式更改

### ISSUE THREAD

**Issue by Solitario119** [Kenshin/simpread#5295]
目前在使用简悦搭配Logseq导出md，想请教下如何设置导出的md中的date格式，如图一是目前的导出格式，图二是想要的logseq日期格式。希望能给出具体一些的设置过程，感谢！
![image](https://user-images.githubusercontent.com/42676347/223296923-02a2048d-c151-4229-a155-63126d1a904a.png)
![image](https://user-images.githubusercontent.com/42676347/223297021-e6e523db-4d67-43f3-b369-75e1619a9b59.png)

**Comment by Kenshin** [comment]
嗨

你可以根据 https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2577619 提到的方式测试不同的日期结构，不需要任何编程知识，仅仅只是占位符的设置。

因为你没有给出具体的模板，所以还是建议使用我提到的方式自行设置，这样方便你以后对这个模板更进一步的优化。
