### ISSUE TITLE
新站适配：界面新闻（页面布局更改导致获取重复）

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5297]
界面新闻地址：
https://www.jiemian.com/article/9021798.html
进入阅读模式后，解析不正确，会出现重复问题
尝试过关闭增强解析和纯碎模式，都无法生效

**Comment by Kenshin** [comment]
嗨，我没有遇到你提到的问题。

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/81074/223315514-9520d6b3-187d-44c0-bf22-9bc55d196844.png">

建议在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by liuyuqiangchn** [comment]
你看你图片的目录，从国资委那里，是不是重复了呢

**Comment by liuyuqiangchn** [comment]
另外，还有个问题，有的时候，我修改完简悦配置后，它提示《配置文件已更新，刷新当前页面后才能生效》，可是我刷新了多次了，还是出现这个提示

**Comment by Kenshin** [comment]
okay 收到，确实如此...

我先重开这个 issues，修复后会通知你。

**Comment by Kenshin** [comment]
嗨，这个站点已更新，请通过 https://github.com/Kenshin/simpread/discussions/2870 更新，并留意下图的说明

![SCR-20230330-pa8](https://user-images.githubusercontent.com/81074/228804557-dd38e20a-662c-4b91-b299-444ae67eca5f.png)
