### ISSUE TITLE
稍后读页面无法打开

### ISSUE THREAD

**Issue by yifeitao** [Kenshin/simpread#5299]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows 10**

- 浏览器版本 **e.g. Chrome 110.0.5481.178**

- 简悦版本 **2.2.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html>

**请描述你的问题**

>稍后读页面无法打开，chrome控制台可见js错误
Error handling response: TypeError: Cannot read properties of null (reading 'tags')
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:7:1352
    at Array.forEach (<anonymous>)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:7:1312
    at Array.forEach (<anonymous>)
    at e.value (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:7:1234)
    at r (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:1:289)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:1:16710
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:1:10667
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:1:17856

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨

你可以使用 [数据中心的修复功能](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%E4%BF%AE%E5%A4%8D%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 自行修复。

这个功能需要同步助手 1.2.0。
