### ISSUE TITLE
阅读类的新站适配

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#53]
（已删除）

**Comment by GregAMO** [comment]
求适配网易轻博客 LOFTER： lofter.com 
此站提取正文很简单，希望能用上更适合中文的阅读体验 :)

**Comment by Kenshin** [comment]
@GregAMO 
看了下  lofter.com 的 URL 结构是没问题的，但这类网站的模板有很多，会影响 html 结构，简单的找了个，虽然结构一致，我还是要再确认一下~

😄

**Comment by GregAMO** [comment]
@Kenshin 补充：不同模版问题估计不大，Lofter 这方面做得比较规矩
1.  这款批量抓取正文的扩展15年停止更新后依然正常使用中 [Lofter抓文插件](https://chrome.google.com/webstore/detail/lofter抓文插件/ilabeeklpmaacpjamehodpkgkjidnmpf/reviews)
2. Yandex 这款俄罗斯那边基于 Chromium 定制的浏览器自带阅读模式也能识别正文，应该不是特意适配的

嘛，那就期待好消息啦

**Comment by Kenshin** [comment]
@GregAMO 
okay ，我会试试你说的 [1] 这个扩展，Yandex 这个 Chromium 知道，但未使用过，它的抓取应该只是通用规则，不具体个体性。

PS：等 lofter.com 适配后，我会通知你的。 😄

**Comment by Kenshin** [comment]
@GregAMO 
lofter.com 已适配，但由于模板较多，还是存在无法 100% 覆盖的情况，虽然机率不大。
更新方法 [请看](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E6%96%B0%E5%A2%9E)
