### ISSUE TITLE
希望增加有道云笔记保存功能

### ISSUE THREAD

**Issue by duanbinbinbin** [Kenshin/simpread#530]

**Comment by duanbinbinbin** [comment]
希望增加有道云笔记保存功能

**Comment by Kenshin** [comment]
谢谢建议。
你可以看一下临时解决办法 https://github.com/Kenshin/simpread/issues/473

**Comment by zhiyakun** [comment]
> 
> 
> 谢谢建议。
> 你可以看一下临时解决办法 #473
不知道能不能增加也增加一下为知笔记的保存功能，谢谢

**Comment by Kenshin** [comment]
@zhiyakun 
当然会考虑的，只是为知笔记比较麻烦，它没有提供 API 曾经联络过他们，还未果...

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) 的功能，希望喜欢~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
