### ISSUE TITLE
框选图标点击无反应，重新安装后也不行

### ISSUE THREAD

**Issue by Hansun160** [Kenshin/simpread#5300]
![image](https://user-images.githubusercontent.com/101316557/223442974-bd54c551-b21c-49c3-86d6-abf962bdbcf7.png)

**Comment by Kenshin** [comment]
嗨，试试

隐私模式下，仅启用简悦的方式。
排除其他扩展的干扰。

**Comment by Hansun160** [comment]
与浮图秀插件冲突了，感谢

**Comment by Kenshin** [comment]
okay 解决就好，我 Mark 下这个情况。
