### ISSUE TITLE
关于 local restapi 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5301]
local restapi 导入标注，只导入了标题，标注未导入成功什么原因啊

_Originally posted by @ykf904839896 in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-5236010_

**Comment by Kenshin** [comment]
@ykf904839896 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

我需要你跟这个功能相关的地方都截图给我，否则我没办法判断。

一般来说，标注没有导入的原因：

1. 没有安装 Markdown 辅助增强插件。
2. 没有在导入到 Obsidian 启用 Markdown 辅助增强插件

<img width="608" alt="image" src="https://user-images.githubusercontent.com/81074/223614317-031d09cc-82e0-4920-9381-ff755dbd0385.png">

**Comment by ykf904839896** [comment]
检查了下都启动了，按照配置教程都配置了。但是还是不行
提个建议
1.文档混乱
2.文档一会官网，一会github
3.配置太繁琐
4.建议把同步方案文档再整理下，对于新用户直接折叠。

**Comment by ykf904839896** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/46636973/223631277-e23a5d7d-673e-4809-8020-23f8fbe8afd2.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/46636973/223631320-0342e1b2-5220-42ea-a49a-aeb0353b7d7f.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/46636973/223631416-4944bfd7-6fde-4b7d-85b7-62c84afe9618.png">
导入批注提示成功，进去页面只有标题。按照配置的全部都配置好了

**Comment by ykf904839896** [comment]
还有个问题是有时无法捕获选中事件，弹出标注面板偶现失败bug

**Comment by Kenshin** [comment]
> 还有个问题是有时无法捕获选中事件，弹出标注面板偶现失败bug

没理解... 😂 

试试按照下图所示设置

<img width="926" alt="image" src="https://user-images.githubusercontent.com/81074/223651638-567ac459-976e-48db-aeee-89ecb8d82a2f.png">
