### ISSUE TITLE
微博文章页在稍后读的阅读模式显示无法解析，在解析成功的情况下无法显示图片。

### ISSUE THREAD

**Issue by soma666** [Kenshin/simpread#5303]
安装了站点市集的微博文章适配后，可以在阅读模式下正常阅读文章。将文章加入到稍后读后，进入阅读模式，有时候会显示无法解析。在能解析的情况下无法查看图片。

在普通的阅读模式下，选择讲保存为离线html，保存后的文件无图片。

以下页面均有此问题。

https://weibo.com/ttarticle/p/show?id=2309404872676500963697
https://weibo.com/ttarticle/p/show?id=2309404808512256737748
https://weibo.com/ttarticle/p/show?id=2309404818568025080343

**Comment by Kenshin** [comment]
嗨，并不是每个加入到稍后读的页面都可以被正常解析，比如微博的就不行。

但如果你使用了同步助手的话，可以看下 [这个教程](https://www.yuque.com/kenshin/simpread/wkswh7)，可以在稍后读中显示微博内容。

**Comment by soma666** [comment]
如果要配置一站式obsidian同步的话，是先配置obsidian还是先配置知识库？

**Comment by Kenshin** [comment]
如果是新用户的话，建议直接使用 [配置库方案](https://www.yuque.com/kenshin/simpread/psugef)，里面的高级版就是针对本地快照的知识库方案。

> 如果要配置一站式obsidian同步的话，是先配置obsidian还是先配置知识库？

先配置知识库，然后再是 Obsidian，知识库是一切跟双链笔记有关功能的基础。

**Comment by soma666** [comment]
配置完知识库后微博文章依然显示无法解析
一共添加了三个稍后读，之后第一个会在列表上显示“已保存到本地”的图标
而且\SimpRead\output文件夹下没有对应文件

而且以前保存到稍后读的其他网站原来可以在阅读模式下解析的文章也显示无法解析了

**Comment by Kenshin** [comment]
假设你配置好了知识库，然后需要：

1. 使用快捷键 `d d` 加入稍后读
2. 手动导出 HTML

二选其一，这两种情况下，`output` 文件夹应该会有本地快照。

**Comment by soma666** [comment]
两个操作都不会出现本地快照
而且依旧会显示无法解析
会是什么问题？

**Comment by Kenshin** [comment]
配置错了呗 😂 仔细看你的配置跟教程有什么区别。

**Comment by soma666** [comment]
重新配置了一下我发现问题是，应该在进入阅读模式后再加入稍后读就正常了。我之前是直接在原始界面加入的。

但是虽然能正常解析，也可以在本地生成快照了。但稍后读的阅读模式下还是没有图片。

**Comment by Kenshin** [comment]
> 但是虽然能正常解析，也可以在本地生成快照了。但稍后读的阅读模式下还是没有图片。

把自动化改成离线 HTML

**Comment by Kenshin** [comment]
> 改成离线 HTML也不行，会有一个chrome提示说简悦要求文件下载权限，选择允许以后会有简悦的提示说图片已经转换下载之类的。但是进到稍后读里还是没有图片。

如果是配置了知识库，不应该通过浏览器下载，而是同步助手。（你可能还是需要检查下你的配置）

> 应该是微博文章的图片有特殊机制，从浏览器获取的图片地址单独贴到

我确认了这个问题，确实微博的图片存在这样的机制。😂

关于这点，我简单的说明下：

简悦不会违背任何导入方的规则，也就是说：**如果导入方的图片存在防盗链（如公众号），那么用户可以通过离线 HTML 或 `assets + md` 的方式解决，如果能解决，那就没问题**；反之，**即便可以通过技术手段来解决，但简悦这边也会尊重导入方的规则**。

一个例子说明下：

1. B站笔记就没法使用离线 HTML，但它可以使用 `assets + md` 方式。（因为是离线 HTML 或 `assets + md` 都是常规方案）

2. 微博这种，无论是离线 HTML 或 `assets + md` 的方式，都没法解决，那就尊重导入方的规则。（即便可以通过技术手段解决也不会这么做）

**Comment by soma666** [comment]
好的，明白了，多谢您一直回答我的问题

**Comment by Kenshin** [comment]
哈，小事情，好在毕竟还是让你配置了知识库，虽然微博不行，但大多数网站（我很少见过不行的）都没问题。

***

要是可能的话，如果没有帮你五星好评的话，请进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 

通过下图，帮忙五星 + 好评  😏 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by soma666** [comment]
已经评价，另外我又发现了一个稍后读问题。

bilibili专栏如果在自动化中选择了离线html在稍后读中的阅读模式会显示无法解析。换成html重新添加一下就正常了。

**Comment by soma666** [comment]
不是笔记，是专栏。是两个不同的产品。
另外刚才发现搜狐专栏也和新浪文章一样使用的图片防盗链的机制

**Comment by Kenshin** [comment]
直接提交 URL 

还有…这个功能已经存在很多年了，不会有任何问题，否则早就有用户反馈了。

目前我只见过：吾爱破解，微博（你告诉我的），B 站笔记，这几个而已…
