### ISSUE TITLE
先购买高级账户之后发现我之前没有登录，登录之后不知道怎么升级成高级用户

### ISSUE THREAD

**Issue by polarisink** [Kenshin/simpread#5304]

**Comment by Kenshin** [comment]
没太理解你的问题。

试试 https://www.yuque.com/kenshin/simpread/sqdl46 能否解决？

**Comment by polarisink** [comment]
购买之后没看到lisence显示界面，以为会通过邮箱发送给我，但是并没有收到类似的邮件

**Comment by Kenshin** [comment]
小事情，我关闭这个 Issues 了。
