### ISSUE TITLE
关于进入阅读模式后的一些使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5306]
进入简阅的阅读模式后，我点其他插件都不能弹出来了。

我需要点其他插件能弹出来！比如我在用简阅看文章，我想点一个叫Monica插件图标，他不弹出来了。

_Originally posted by @LyOuYang in https://github.com/Kenshin/simpread/issues/5296#issuecomment-1459618771_

**Comment by Kenshin** [comment]
@LyOuYang

因为你的问题已经跟 https://github.com/Kenshin/simpread/issues/5296 无关了， 所以我帮你新建了一个 Issues，并删除了原来位置的内容。

***

阅读模式比较特别，它会改变原文的结构，所以为了避免这种情况出现，所以简悦不会在原文上进行优化。

一般比较好的扩展都会适配这种方式，比如 Dark Reader。

还有，你提到的这个功能跟高级账户功能无关。

**Comment by LyOuYang** [comment]
> @LyOuYang
> 
> 因为你的问题已经跟 #5296 无关了， 所以我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 阅读模式比较特别，它会改变原文的结构，所以为了避免这种情况出现，所以简悦不会在原文上进行优化。
> 
> 一般比较好的扩展都会适配这种方式，比如 Dark Reader。
> 
> 还有，你提到的这个功能跟高级账户功能无关。

**Comment by LyOuYang** [comment]
Clearly Reader - 必备阅读助手。这个插件的功能和你们很像，我进入这个插件的阅读模式，点save to notion插件可以弹出来，如下图：。
你们的保存到notion插件太麻烦了，而且不自由，所以我想用save to notion。
![image](https://user-images.githubusercontent.com/38170279/223906281-566cc7fc-aacf-48be-be09-033422b5588f.png)
