### ISSUE TITLE
Notion 授权失败

### ISSUE THREAD

**Issue by SilentTiger** [Kenshin/simpread#5309]
![image](https://user-images.githubusercontent.com/764862/223993495-8e283502-a00a-4f36-b64c-7b689861e0ab.png)

![image](https://user-images.githubusercontent.com/764862/223995251-6204880a-44ac-45c6-bceb-e72248e1bc68.png)

如图一所示，尝试授权 Notion 会有右上角的提示，Notion 已经成功登录。

如图二所示，尝试授权 Notion 的时候请求发成功，response 里面有用户数据。

**Comment by Kenshin** [comment]
嗨，解决方案 https://www.yuque.com/kenshin/simpread/wwk65u

**Comment by Kenshin** [comment]
emmmm 那就奇怪了，大概率是你个人问题。

是不是你的浏览器有什么限制？

能否换个浏览器，如 Edge 测试？或者重新注册个 Notion 账户测试？
