### ISSUE TITLE
划词翻译安装后无法使用标注系统

### ISSUE THREAD

**Issue by JJcdomat** [Kenshin/simpread#5310]
- 操作系统 **Windows**

- 浏览器版本 **Chrome 110.0.5481.178**

- 简悦版本 **2.2.0**

划词翻译无法与标注同时使用。

安装划词翻译后，无论翻译与否，都会导致**选区消失**。此时虽然有标注菜单出现，并且点击后会有相关提示，但实际上没有完成标注。

右下角翻译按钮好像是用来开关生词本？所以也无法关闭划词翻译。

**Comment by Kenshin** [comment]
是的，目前是这样的 😂

解决方案看这里，随便不完美，但也能解决 https://github.com/Kenshin/simpread/discussions/5311
