### ISSUE TITLE
关于 ChatGPT 辅助增强插件的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5313]
我的问题是：装了 ChatGPT 辅助增强插件，「插件触发器」出现了，但是「ChatGPT 辅助增强选项」没有反应（其他插件的选项是没问题）。试过导出配置，卸载 SimpleRead - 重启浏览器 - 重装 Simple - 导入配置 - 重装插件，问题依然，最重要的是我没有开同步。

Brave 浏览器

_Originally posted by @chinnsenn in https://github.com/Kenshin/simpread/discussions/2342#discussioncomment-5262227_

**Comment by Kenshin** [comment]
@chinnsenn 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

这个插件只能在 https://chat.openai.com/ 下使用，因为它专属于这个网站的。

**Comment by chinnsenn** [comment]
> @chinnsenn
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 这个插件只能在 https://chat.openai.com/ 下使用，因为它专属于这个网站的。

那可能使用说明有岐义，示例中举例打开一个 少数派 的链接，进入「阅读模式 → 右下角 → 动作 → 插件触发器」
https://simpread.ksria.cn/plugins/details/8CjJLsNUKU

**Comment by Kenshin** [comment]
okay 谢谢提示，已修复。

🙏
