### ISSUE TITLE
无法使用配置文件登陆高级账户

### ISSUE THREAD

**Issue by AaronLiu992** [Kenshin/simpread#5315]
一直显示“导入成功，正在授权，请稍后”

**Comment by Kenshin** [comment]
请详细说明，比如截图。

另外，你导入的配置文件名叫什么？之前用过吗？

**Comment by jisidehuli** [comment]
> 请详细说明，比如截图。
> 
> 另外，你导入的配置文件名叫什么？之前用过吗？

您好大佬，我也遇到了同样的问题，如图，使用了共通-加载本地配置文件也不行。
![IMG_2377](https://user-images.githubusercontent.com/39455147/229482937-f4bccae1-ae78-47a0-a7f8-c725b7bc72ac.jpeg)
![IMG_2378](https://user-images.githubusercontent.com/39455147/229482953-505d019d-db56-434f-a92d-f03bd45f5b77.jpeg)
json文件里面也只有两个字符串，我对了一下和买断版发的liscen是一样的。
