### ISSUE TITLE
使用obsidian配置库无法导出到指定的文件夹

### ISSUE THREAD

**Issue by GULIDUODUO** [Kenshin/simpread#5316]
请问为何按照配置库教程设置，在阅读模式下加入稍后读后，导出的位置是在SimpRead目录下而不是导出到设定的SimpRead/output目录中？

**Comment by Kenshin** [comment]
output 的设置看下图，看看跟你的有什么区别？

<img width="669" alt="image" src="https://user-images.githubusercontent.com/81074/224468712-fdc06566-bc25-4934-8a3b-f26d792a92ab.png">

**Comment by GULIDUODUO** [comment]
![IMG_20230311_143844.jpg](https://user-images.githubusercontent.com/119158868/224469412-e5ceab90-764e-4286-8037-37575eff9684.jpg)

![IMG_20230311_143840.jpg](https://user-images.githubusercontent.com/119158868/224469413-8f2d2d26-9084-46e5-bd84-9e2eaafd70e8.jpg)

跟教程是一样的，也尝试过各种变换路径但都是只能导出到SimpRead中

开启md + assets方案设定路径时，在设定的目录中会导出一个assets文件夹和一个全文快照，但是标注文件@annote还是导出到了SimpRead目录中，请问是否正常？

还有一个问题是我加入tg讨论组时问题回答错误了导致至今无法再次搜索到群组了，能否处理一下。

**Comment by Kenshin** [comment]
导入到 Obsidain 的截图我也需要。

另外，使用了哪种导入方案？

**Comment by GULIDUODUO** [comment]
> 导入到 Obsidain 的截图我也需要。
> 
> 另外，使用了哪种导入方案？

![IMG_20230311_151218.jpg](https://user-images.githubusercontent.com/119158868/224470737-9d89eb57-03ea-4a62-ad8f-62cfdcf2db24.jpg)

![IMG_20230311_151206.jpg](https://user-images.githubusercontent.com/119158868/224470736-72a0fc0f-787c-4917-b4c2-04f78ced35d2.jpg)


直接使用的obsidian配置库

导入方案是 SimpRead Sync 插件

**Comment by Kenshin** [comment]
emmm 确认下这个地方：

> 导出的位置是在SimpRead目录下而不是导出到设定的SimpRead/output目录中？

output 里面的内容是指 `.md` 还是 `.html`  ？ 如果是前者的话，是正确的。

如果你使用了 SimpRead Sync 的方式，所以导出的 Markdown 位置收到下图的设置影响。

<img width="764" alt="image" src="https://user-images.githubusercontent.com/81074/224478489-6dd43e05-ac77-45fa-8ad0-4127ed5c79eb.png">

**Comment by GULIDUODUO** [comment]
按照目前的设置方法，edge 上通过阅读模式，加入稍后读，会同步两个文件(快照+标注)到 SimpRead 目录里边, output 文件夹并没有任何文件被导入，这样是正确的吗？

SimpRead 中的 output 文件夹的作用是什么？

刚接触简悦研究手册和配置两天了，有些地方还是理解不够，还请指点一下。

还有就是一个人遇到问题实在难熬，能否将我加到 tg 群中，qq 频道活跃度属实有点低……

**Comment by Kenshin** [comment]
> 将我加到 tg 群中

忘记了 😂 把你 Telegram ID 告诉我。

> 按照目前的设置方法，edge 上通过阅读模式，加入稍后读，会同步两个文件(快照+标注)到 SimpRead 目录里边, output 文件夹并没有任何文件被导入，这样是正确的吗？

不正确，按照你截图所示应该在 output 文件夹中。

***

PS：建议直接使用配置库方案，并且按照教程中的说明设置目录。等熟悉后，可以再按照你自己的实际情况修改。

**Comment by GULIDUODUO** [comment]
ID:Perfeots

因为我帮想建这么多库，统一都放在一个里边了

进去 tg 了我再去请教请教

**Comment by Kenshin** [comment]
我稍晚给你解封。

不过，还是通过这里讨论吧，聊天效率太低。 😂

**Comment by GULIDUODUO** [comment]
好吧，但是我也尝试过完全使用配置库进行配置，好像也是没办法导出到设定的 output ，加入稍后读后会自动同步到 SimpRead 目录中，所以一直以为自己哪个步骤错了，就一直在啃手册，也没想明白 output 存在的作用。

**Comment by Kenshin** [comment]
如果用了配置库方案的话：

- output → 应该是 HTML 文件

- md 文件应该在 Obsidian/SimpRead 文件夹下

**Comment by GULIDUODUO** [comment]
SimpRead/output 这个目录结构是固定不能改变的吗？

同步助手是同步到 SimpRead 目录，导出到 SimpRead/output 目录

那么SimpRead 和 output 这两个文件夹也不可以改名字是吗(能否改名字和能否在 SimpRead 目录下新建一个文件夹然后同步助手设定导出到此文件夹，这是我比较困惑的地方)？

**Comment by Kenshin** [comment]
都可以改变…

我的意思是：先按照既定规则先跑通，确保你自己熟悉后再定制化。

你跑不同的话，什么定制化都没意义。

配置库方案就是几个路径，其他都配好了。

**Comment by GULIDUODUO** [comment]
好的，我再熟悉熟悉，谢谢大佬

**Comment by Kenshin** [comment]
小事情~

还有个建议：

按照 https://www.yuque.com/kenshin/simpread/wq35mh 设置，然后把你自己需要填目录的地方都截图发上来。（当然，如果没有问题的话，就不用发了 😂

PS：你的 ID 已解除，可以重新进入了，别忘了填入口口令。

**Comment by GULIDUODUO** [comment]
感谢，自己重新折腾了一下，自定义目录问题已经解决。

然后又出现一个问题是，加入稍后读的文章，在 edge 端删除后，同时手动删除导出到 obsidian 库中的三个文件(两个 md ，一个 html)后，新加入稍后读的文章并导出的文件序号无法继承被删掉的序号，这是正确的吗？

**Comment by GULIDUODUO** [comment]
> 感谢，自己重新折腾了一下，自定义目录问题已经解决。
> 
> 然后又出现一个问题是，加入稍后读的文章，在 edge 端删除后，同时手动删除导出到 obsidian 库中的三个文件(两个 md ，一个 html)后，新加入稍后读的文章并导出的文件序号无法继承被删掉的序号，这是正确的吗？

请问稍后读文件导出的逻辑是什么样的

我测试了一下应该是由 edge 端"稍后读"主导，如果把以前加入的 edge 端"稍后读"文章删除掉，但是本地文件还存在的话，新加入的"稍后读"文章导出到本地后，文件会从序号1-开始重新生成，并且会直接替换掉 output 内之前的1-开头文件(文章标题不同，文件名称自然也不相同，为什么会替换掉呢？)

我记得自己折腾的时候，是有一次出现，后加入的文章序号继承了前面被删掉的序号，不知是否自己操作有误。

**Comment by Kenshin** [comment]
当你把全部的稍后读都删除，再重新加入稍后读时（这时是第一个稍后读），导出的文件会没有前面的序列号，这是个 Bug，解决方案也比较简单，不要删除全部的稍后读 😂 （至少留一个

另外，稍后读的 ID 是个自增长的序号 e.g.  `1 2 3 4` 当你删除了 `4` 后，再加入的也是 `4` 但这样就会产生一些问题：

1. 删除稍后读并不能删除本地的相关数据。

2. 再加入的 `4` 后，会出现 `4-已删除.html` 和 `4-新添加.html`。

目前的解决方案是：在同步助手 → 导出，开启下面的选项

<img width="652" alt="image" src="https://user-images.githubusercontent.com/81074/224532557-60b40680-cc2a-4924-93c7-84c05c0746c0.png">

这样以来，问题2就解决了，而问题1暂时并不会产生任何影响。

问题1也可以通过 [查找重复数据](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e6%9f%a5%e6%89%be%e9%87%8d%e5%a4%8d%e6%95%b0%e6%8d%ae) 来解决。

**Comment by GULIDUODUO** [comment]
我想明白整个配置的逻辑了，再次感谢

不过说实话我硬啃了三天，重复操作了不下10次，配置-还原-配置～，现在终于搞清楚整个流程了，并且已经把每个阶段的配置文件备份了，可以随时还原了。

最后发现其实我不太需要坚果云及衍生的其他工具(只在一个电脑使用，且有 kopia 给整个库做备份快照了)

另外一个衍生的工具就是收藏助手了，但我在安卓端配置过程中发生了一些错误，比如使用后回到扩展端加入稍后读，会提示保存错误，就没有深入学习了，待需要时再进行研究。

**Comment by GULIDUODUO** [comment]
是的，已经配置到了自己库中的路径

今天第一次配置了下收藏助手，出了一点小差错，打算慢慢再研究下，这几天独自一人反复看手册有点累了😂

**Comment by GULIDUODUO** [comment]
大佬，再请教一个问题😭

我使用的 md+assets 导出方式，为什么单单只有快照文件命名是错误的，导出的文件名都是"教程"，"教程(1)"……，一开始设置好后是正常的，使用一会就这样了

我重启浏览器和同步助手后，快照和md+assets正常了，但是不生成标注文件(md格式)

当从稍后读中进行标注，会生成标注文件，但是从md格式变成了html格式，且是导入到了和快照一个文件夹下(output)，期间未作其他设置。

![mmexport1678631370019.png](https://user-images.githubusercontent.com/119158868/224551260-2847a561-3356-4777-9cee-0d80308eaad8.png)

![mmexport1678631371608.png](https://user-images.githubusercontent.com/119158868/224551262-bc7d30be-a253-4948-b283-a0adb7325c18.png)

![mmexport1678631368730.png](https://user-images.githubusercontent.com/119158868/224551261-68d804ba-e548-493d-80da-5104dba9475d.png)

感觉我遇到的都是一些奇葩问题啊😓

**Comment by Kenshin** [comment]
简悦的功能针对阅读模式，所以受众是有区别的，有些用户是 Obsidian 有些是 Notion 等。

所以，没必要什么功能都折腾一次，有需要的时候再看来得及。

**Comment by GULIDUODUO** [comment]
> 大佬，再请教一个问题😭
> 
> 我使用的 md+assets 导出方式，为什么单单只有快照文件命名是错误的，导出的文件名都是"教程"，"教程(1)"……，一开始设置好后是正常的，使用一会就这样了
> 
> 我重启浏览器和同步助手后，快照和md+assets正常了，但是不生成标注文件(md格式)
> 
> 当从稍后读中进行标注，会生成标注文件，但是从md格式变成了html格式，且是导入到了和快照一个文件夹下(output)，期间未作其他设置。
> 
> ![mmexport1678631370019.png](https://user-images.githubusercontent.com/119158868/224551260-2847a561-3356-4777-9cee-0d80308eaad8.png)
> 
> ![mmexport1678631371608.png](https://user-images.githubusercontent.com/119158868/224551262-bc7d30be-a253-4948-b283-a0adb7325c18.png)
> 
> ![mmexport1678631368730.png](https://user-images.githubusercontent.com/119158868/224551261-68d804ba-e548-493d-80da-5104dba9475d.png)
> 
> 感觉我遇到的都是一些奇葩问题啊😓

前面5个是导出没有问题的，第6个是开始出现问题的

**Comment by GULIDUODUO** [comment]
> 大佬，再请教一个问题😭
> 
> 我使用的 md+assets 导出方式，为什么单单只有快照文件命名是错误的，导出的文件名都是"教程"，"教程(1)"……，一开始设置好后是正常的，使用一会就这样了
> 
> 我重启浏览器和同步助手后，快照和md+assets正常了，但是不生成标注文件(md格式)
> 
> 当从稍后读中进行标注，会生成标注文件，但是从md格式变成了html格式，且是导入到了和快照一个文件夹下(output)，期间未作其他设置。
> 
> ![mmexport1678631370019.png](https://user-images.githubusercontent.com/119158868/224551260-2847a561-3356-4777-9cee-0d80308eaad8.png)
> 
> ![mmexport1678631371608.png](https://user-images.githubusercontent.com/119158868/224551262-bc7d30be-a253-4948-b283-a0adb7325c18.png)
> 
> ![mmexport1678631368730.png](https://user-images.githubusercontent.com/119158868/224551261-68d804ba-e548-493d-80da-5104dba9475d.png)
> 
> 感觉我遇到的都是一些奇葩问题啊😓

现在第二个问题正常了，问题1出现了，且我手动导出为html，文件名为教程，教程-1，教程-2，教程-3……

**Comment by Kenshin** [comment]
>  问题1出现了，且我手动导出为html，文件名为教程，教程-1，教程-2，教程-3……

问题1是指什么？

**Comment by GULIDUODUO** [comment]
> >  问题1出现了，且我手动导出为html，文件名为教程，教程-1，教程-2，教程-3……
> 
> 问题1是指什么？

使用 md+assets 导出方式

①："001-简悦"中生成标注文件

②："001-简悦/output"中生成html快照

③："001-简悦/md@assets"中生成 md + assets文件

现状：

①和③文件名正常，②中生成的快照名称为"教程"

尝试手动导出为 html，导出多个文章，导出的文件名依次为"教程"，"教程-1"，"教程-2"……

**Comment by Kenshin** [comment]
> ②中生成的快照名称为"教程"

是指什么？把这个功能相关的设置截图给我看看。

**Comment by GULIDUODUO** [comment]
我想已经找出问题原因了

Obsidian 中我开启了 paste image rename 插件，这个插件功能是自动将笔记中的图片名字改为笔记的名字进行整理，但是问题的具体原理就不知道了

我先在禁用此插件恢复正常
<img width="390" alt="Snipaste_2023-03-13_22-00-59" src="https://user-images.githubusercontent.com/119158868/224725219-d3398f2d-0cc7-43f3-9b60-992ede7906a5.png">

**Comment by Kenshin** [comment]
> 是否只要在自动化中把 html 改为离线 html 

是的，但它与 `HTML` 只能二选其一，因为它们是同样的 `.html` 文件，会互相覆盖。

**Comment by GULIDUODUO** [comment]
> > 大佬，再请教一个问题😭
> > 我使用的 md+assets 导出方式，为什么单单只有快照文件命名是错误的，导出的文件名都是"教程"，"教程(1)"……，一开始设置好后是正常的，使用一会就这样了
> > 我重启浏览器和同步助手后，快照和md+assets正常了，但是不生成标注文件(md格式)
> > 当从稍后读中进行标注，会生成标注文件，但是从md格式变成了html格式，且是导入到了和快照一个文件夹下(output)，期间未作其他设置。
> > ![mmexport1678631370019.png](https://user-images.githubusercontent.com/119158868/224551260-2847a561-3356-4777-9cee-0d80308eaad8.png)
> > ![mmexport1678631371608.png](https://user-images.githubusercontent.com/119158868/224551262-bc7d30be-a253-4948-b283-a0adb7325c18.png)
> > ![mmexport1678631368730.png](https://user-images.githubusercontent.com/119158868/224551261-68d804ba-e548-493d-80da-5104dba9475d.png)
> > 感觉我遇到的都是一些奇葩问题啊😓
> 
> 现在第二个问题正常了，问题1出现了，且我手动导出为html，文件名为教程，教程-1，教程-2，教程-3……

悲催~~第二个问题开始出现，添加到稍后读，无法导出

尝试手动导出会显示导出失败

尝试做标注，会自动导出到错误的文件夹

<img width="352" alt="Snipaste_2023-03-13_23-18-37" src="https://user-images.githubusercontent.com/119158868/224747391-28b69d72-8b78-46ee-8ec8-29ba4d2c7dfd.png">
<img width="421" alt="Snipaste_2023-03-13_23-23-31" src="https://user-images.githubusercontent.com/119158868/224747402-81938929-e882-46e7-8822-7cf94df38b38.png">

**Comment by Kenshin** [comment]
> 不可以对导入 obsidian 的 md 文章进行自定义文本链接

是指什么？

应该跟你提到的现象无关....

**Comment by GULIDUODUO** [comment]
> > 不可以对导入 obsidian 的 md 文章进行自定义文本链接
> 
> 是指什么？
> 
> 应该跟你提到的现象无关....

就是我在 ob 中一个笔记里面引用加入稍后读而导入的 md 文件(md + assets目录里)，同时我对这次的引用做了自定义文本显示

比如[[[某某.md|自定义文本显示]]

我直接引用不去自定义后恢复正常了

**Comment by Kenshin** [comment]
原来如此~

***

PS：这么长的 QA，不给简悦个五星 + 「百字」点评吗？

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
哈哈，在 Chrome 还是在 Edge 评论的，明天「观摩」下。

只要是在 Issues 提的内容（无论是问题还是联系），都会 100% 回复。

**Comment by GULIDUODUO** [comment]
在 edge 上，他这个评论系统好像没有格式，全部都堆在一起，看起来太密集了

**Comment by Kenshin** [comment]
> 在 edge 上，他这个评论系统好像没有格式，全部都堆在一起，看起来太密集了

哈哈，还好。（我刚看完） 😂
