### ISSUE TITLE
安装插件不生效

### ISSUE THREAD

**Issue by Rvishny** [Kenshin/simpread#5317]
新下了插件，开通高级账号后，开通了同步功能，之后在插件中安装插件后不生效。

**Comment by Kenshin** [comment]
插件跟高级账户无关，基础账户就可以使用 99.9%    的插件。

如果你使用了同步助手，请使用 https://www.yuque.com/kenshin/simpread/fcw60u 解决。

反之，试试：选项页 → 插件管理 → 清除全部插件解决。

或者详细描述你的问题

**Comment by Rvishny** [comment]
已经解决了，需要禁用浏览器阻止广告的插件。。。不过动作中的插件触发器，在装完全文翻译插件后，等了好久，才刷新出来选项。不知道是这个插件有问题还是其他问题。毕竟其他的插件装了就可以出现。

**Comment by Kenshin** [comment]
> 不过动作中的插件触发器，在装完全文翻译插件后，等了好久，才刷新出来选项

如果没有使用同步助手的话，应该没关系，在留意下。

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
