### ISSUE TITLE
字体粗细的疑问

### ISSUE THREAD

**Issue by Fred-Chan** [Kenshin/simpread#5319]
暗黑模式中的字体过细，且切换字体之后没有变化。只能切回默认的第一个颜色主题才能恢复

**Comment by Fred-Chan** [comment]
操作系统是MacOS。这是什么特殊的设计吗？

**Comment by Kenshin** [comment]
需要提供 URL

**Comment by Fred-Chan** [comment]
> 需要提供 URL

https://sspai.com/post/77731
