### ISSUE TITLE
使用同步助手后导出失败的使用疑问

### ISSUE THREAD

**Issue by soma666** [Kenshin/simpread#5320]
https://www.sohu.com/a/423927504_100232674

可以在阅读模式下显示图片，加入稍后读时会报错

![QQ截图20230312134052](https://user-images.githubusercontent.com/10132713/224526641-5849d340-7d35-42e8-8cd9-97505855fcb3.png)

https://ngabbs.com/read.php?tid=22932567

无法在阅读模式下完整显示图片和正确排版

**Comment by Kenshin** [comment]
需要看下你的自动化设置都有什么？

这个提示跟图片无关，应该是你设置了某些跟同步助手相关的自动化，但没有正确执行。

**Comment by dofine** [comment]
同样遇到…… 自我怀疑是之前安装过某些自动化的插件，这次换了新电脑和浏览器之后没有正确配置好。

**Comment by Kenshin** [comment]
@dofine

如果你遇到了下图

![](https://user-images.githubusercontent.com/10132713/224526641-5849d340-7d35-42e8-8cd9-97505855fcb3.png)

大概率是因为没有设置同步助手的增强导出，这是 [教程](https://www.yuque.com/kenshin/simpread/wkswh7) 你可以对比下跟你的有什么区别？
