### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by Bo-Magazin** [Kenshin/simpread#5322]
RT

**Comment by Kenshin** [comment]
腾讯问卷是我自己的渠道并且没有兑换的话，可以。
其他渠道是第三方渠道，不支持。

**Comment by Bo-Magazin** [comment]
> 

怎么退呢

**Comment by Kenshin** [comment]
腾讯问卷对应的那个支付宝订单号截图，并发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5322

还有，你之前 Issues 提到的问题... 导入到 Notion 并不需要高级账户...
