### ISSUE TITLE
设置完自动化导出，无论是稍后读阅读模式还是直接标注都不生效。out文件夹无数据。插件中的动作中也没有出现自动化

### ISSUE THREAD

**Issue by Rvishny** [Kenshin/simpread#5325]
![image](https://user-images.githubusercontent.com/57344700/224613024-f8cd9209-6ef9-4d49-921f-8860ab76e36d.png)

![image](https://user-images.githubusercontent.com/57344700/224613065-00e27d08-a9c0-4eaf-b197-1375361e2bf9.png)

![image](https://user-images.githubusercontent.com/57344700/224613109-a70910ec-63e0-466a-97eb-1bce871eed4b.png)

![image](https://user-images.githubusercontent.com/57344700/224613234-c0f4d4f6-4dbf-4101-bf23-f882b951aa7c.png)

![image](https://user-images.githubusercontent.com/57344700/224613352-b801fa73-fdea-42ec-9955-9fee04ccf75f.png)

![image](https://user-images.githubusercontent.com/57344700/224613429-fbe6b6be-5747-4f1c-9098-8ca24cb01e8b.png)

![image](https://user-images.githubusercontent.com/57344700/224613606-c0968e4e-f096-4e0c-8303-ccd34de5a60f.png)

**Comment by Kenshin** [comment]
嗨，自动化的前提：

1. 进入阅读模式
2. 使用快捷键 `d d` 触发（或右键菜单）

其它方式暂时均无法使用自动化。

**Comment by Rvishny** [comment]
配置完成后，我标注了，浏览器会提示下载内容，那么我必须得把浏览器的下载目录设置为SimpRead，才能将内容下载至同步文件夹。那同步助手客户端设置的文件夹有什么用？自动化导出不能直接应用到同步助手设置的文件夹吗？


| |
张成
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2023年3月13日 13:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 设置完自动化导出，无论是稍后读阅读模式还是直接标注都不生效。out文件夹无数据。插件中的动作中也没有出现自动化 (Issue #5325) |

嗨，自动化的前提：

进入阅读模式
使用快捷键 d d 触发（或右键菜单）

其它方式暂时均无法使用自动化。

**Comment by Kenshin** [comment]
> 那么我必须得把浏览器的下载目录设置为SimpRead，才能将内容下载至同步文件夹。

还是你的设置有问题。

关于这块的设置教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by Rvishny** [comment]
我在服务中将增强导出的几个选项开启了就可以了，之前只在同步助手客户端中设置了。就差这一步，其他的之前都配置正确了。多谢


| |
张成
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2023年3月13日 14:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Kenshin/simpread] 设置完自动化导出，无论是稍后读阅读模式还是直接标注都不生效。out文件夹无数据。插件中的动作中也没有出现自动化 (Issue #5325) |

那么我必须得把浏览器的下载目录设置为SimpRead，才能将内容下载至同步文件夹。

还是你的设置有问题。

关于这块的设置教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by Kenshin** [comment]
原来是这个问题... 😂

小事，解决就好~
