### ISSUE TITLE
权限验证错误，无法使用数据中心

### ISSUE THREAD

**Issue by zjp-CN** [Kenshin/simpread#5326]
![image](https://user-images.githubusercontent.com/25300418/224622077-ad3f9509-28e0-46ae-889e-c8c944fafb13.png)

我已下载同步助手（1.2.0 win64），打开 `http://localhost:7026/database/` ，点击任何一项功能都弹出权限验证错误。

**Comment by zjp-CN** [comment]
重新授权、重启浏览器、重启助手都试过了。

**Comment by Kenshin** [comment]
应该是没有授权同步助手造成的。

打开同步助手，看你的同步助手是否如下图所示，有 UID？

<img width="686" alt="image" src="https://user-images.githubusercontent.com/81074/224623213-e17d2e98-ef0f-4a10-87cf-a096657593ed.png">

如何验证同步助手 https://www.yuque.com/kenshin/simpread/pwpnsx#oDWiV

**Comment by zjp-CN** [comment]
授权了同步助手，依然是这个问题

![image](https://user-images.githubusercontent.com/25300418/224625110-b0f9d580-f1f9-4f1d-b3c7-ceed574adc2e.png)

**Comment by Kenshin** [comment]
emmm 请继续回复以下这几个问题：

1. 你是新用户吗？或使用这个功能前刚刚升级到高级账户？

2. 这个功能需要本地存在 `simpread_config.json` （如果是的话，你应该已经配置了自动同步功能）

3. 浏览器 → 简悦 → 选项页 → 看看你的账户是不是带🔒？如果是的话，使用 https://www.yuque.com/kenshin/simpread/sw4m21 解决。

**Comment by zjp-CN** [comment]
1. 我很久以前升级到高级账户（那个时候还没有同步助手），但之后至少一年没有使用过，今天在继续使用
2. 本地存在 simpread_config.json，使用导出配置到本地，文件名为 `simpread-config-2023年03月13日 14_46_32.json`，里面有我很久以前的配置；今天我设置了坚果云，但一直无法显示正在同步，但无法成功
![image](https://user-images.githubusercontent.com/25300418/224629435-53cc61f8-2a54-493c-b19d-fc24f3990a05.png)
而且，我在同步助手设置的文件夹里面没有任何数据（“我的坚果云”是来自坚果云同步的默认文件夹）：
![image](https://user-images.githubusercontent.com/25300418/224629845-0b1be780-e5aa-4470-a8bd-e7e71b059562.png)
![image](https://user-images.githubusercontent.com/25300418/224630038-914ecbbf-539c-406b-a277-822a029f291b.png)


3. 我已经尝试过链接里的方法，依然没用

**Comment by zjp-CN** [comment]
![image](https://user-images.githubusercontent.com/25300418/224630346-634d0396-5fbc-41d1-acc3-1fff3e26cb66.png)

**Comment by zjp-CN** [comment]
![截图_20230313151050](https://user-images.githubusercontent.com/25300418/224631805-b7ba423e-f452-4108-9f12-80750b655285.gif)

**Comment by Kenshin** [comment]
这个功能需要配置 **知识库**（也就是本地存在 `simpread_config.json` 而不是你提到的  `simpread-config-2023年03月13日 14_46_32.json`

这是你需要的教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by zjp-CN** [comment]
好了，谢谢：）

**Comment by Kenshin** [comment]
okay 搞定就好~
