### ISSUE TITLE
简悦同步助手中的增强导出功能无效

### ISSUE THREAD

**Issue by JasonJarvan** [Kenshin/simpread#5327]
### 描述这个错误

我的简悦同步助手的同步文件夹是 `E:\Documents\SZhao Files\syncthing同步\Simpread简悦\output` （后面简称output）
增强导出的配置是

```
{"extension":"assets", "path":"E:\Documents\SZhao Files\syncthing同步\Obsidian\Simpread"} （以后简称Obsidian）
```

使用了 Obsidian@sync 配置库，即Obsidian高级版配置库。

在阅读模式下，“导出全文到obsidian”会导入到Simpread, 但导出md+assets到obsidian，会导入到 output.

### 复现步骤

[Video_20230313181133.zip](https://github.com/Kenshin/simpread/files/10956111/Video_20230313181133.zip)

### 其他相关说明

![image1](https://user-images.githubusercontent.com/49179818/224672681-9c0c5aa2-1fe5-4b44-ae7f-f1e2b59cb94f.png)
未开启导出全文默认用Assets。

### 操作系统

Windows10

### 浏览器

360极速浏览器X 21

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
> “导出全文到obsidian”会导入到Simpread

这是跟你的设置一样的预期。

> 但导出md+assets到obsidian，会导入到 output.

这个跟你的提到的设置并不预期。再自查下：

导入到 Obsidain 的选项，看看你的设置与下图是否一致？

<img width="601" alt="image" src="https://user-images.githubusercontent.com/81074/224675461-d4aa2d4a-129a-4a80-973b-e7db3e3a57d7.png">

另外，你是使用下图所示的方式导出 `assets + md` 吗？

<img width="449" alt="image" src="https://user-images.githubusercontent.com/81074/224676035-a65fe6f2-0926-4cd3-8cd9-cc1f41042d0b.png">

**Comment by Kenshin** [comment]
另外一点：

```
{"extension":"assets", "path":"E:\Documents\SZhao Files\syncthing同步\Obsidian\Simpread"}
```

改为

```
{"extension":"assets", "path":"E:\\Documents\\SZhao Files\\syncthing同步\\Obsidian\\Simpread"}
```

后再试试。

**Comment by JasonJarvan** [comment]
> > “导出全文到obsidian”会导入到Simpread
> 
> 这是跟你的设置一样的预期。
> 
> > 但导出md+assets到obsidian，会导入到 output.
> 
> 这个跟你的提到的设置并不预期。再自查下：
> 
> 导入到 Obsidain 的选项，看看你的设置与下图是否一致？
> 
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/81074/224675461-d4aa2d4a-129a-4a80-973b-e7db3e3a57d7.png">
> 
> 另外，你是使用下图所示的方式导出 `assets + md` 吗？
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/81074/224676035-a65fe6f2-0926-4cd3-8cd9-cc1f41042d0b.png">

不，这里我“未开启导出全文默认用Assets”，也就是开关为关闭。

是的，我是使用下图所示的方式导出的。

**Comment by Kenshin** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/81074/224680839-be8b7367-6598-484c-9fbd-a440aba9a6ef.png">

写错了吧 😂 所以应该是

```
{"extension":"assets", "path":"E:\\Documents\\SZhao Files\\syncthing同步\\Obsidian\\Simpread"}
```

之前已经有提示了，但应该还是在更重点提示下。

**Comment by JasonJarvan** [comment]
是的，

请问可以容我顺便问下，多配置库如何合并吗？比如我现在实现了obsidian@sync的配置库，如何和Notion的配置库合并一起用呢？Thanks♪(･ω･)ﾉ

**Comment by Kenshin** [comment]
> 如何和Notion的配置库合并一起用呢

使用 https://www.yuque.com/kenshin/simpread/zx3bcz 教程里面提到的就行，当配置下来后相当于 [Notion 配置的高级版方案](https://www.yuque.com/kenshin/simpread/zuptv2)。

留意教程中的几个点就行，也很简单。

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by JasonJarvan** [comment]
> > 如何和Notion的配置库合并一起用呢
> 
> 使用 https://www.yuque.com/kenshin/simpread/zx3bcz 教程里面提到的就行，当配置下来后相当于 [Notion 配置的高级版方案](https://www.yuque.com/kenshin/simpread/zuptv2)。
> 
> 留意教程中的几个点就行，也很简单。
> 
> 方便的话，请帮忙对简悦五星 + 好评 😏 是对简悦最好的回报 👍
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

OK！我也在五星好评中特别提到了您的及时回复和帮助！感谢
