### ISSUE TITLE
个人中心登陆不进去

### ISSUE THREAD

**Issue by EdisonWendy** [Kenshin/simpread#5330]
### 描述这个错误

登陆个人中心的时候输入授权码后"提示当前账户没有开通API权限或输入错误，确认输入或更换为UID或坚果云登录方案。"
![微信截图_20230314130120](https://user-images.githubusercontent.com/120798970/224897882-a3abac10-f0c6-4a54-95f2-dd6c1d9557d9.png)
![微信截图_20230314124818](https://user-images.githubusercontent.com/120798970/224897888-c70c88fd-2a85-4790-9d36-49adf756089a.png)

### 复现步骤

1.按照教程中的步骤进入了开放平台“https://simpread.pro/developer”，并设置了自己的ID和short
![微信截图_20230314130432](https://user-images.githubusercontent.com/120798970/224898511-9a3e0dfc-9efc-4d8f-8c68-008eda962da1.png)
2.打开个人中心输入授权码（我按照教程的理解即开放平台中自己设置的short）
3.登录不进去，提示我“当前账户没有开通API权限或输入错误，确认输入或更换为UID或坚果云登录方案。”
4.反复查询了教程和自己设置的short，都没有问题，不知道是哪里错了

### 操作系统

Windows

### 浏览器

Microsoft edge

### 发生问题的网址

https://simpread.pro/@id

**Comment by Kenshin** [comment]
先明确下：`https://simpread.pro/@id` 其中的 `id` 你是在开放平台下设置的 `ID`

在隐私模式下试试，如果还是有问题的话，说明你的配置环境有误。

https://www.yuque.com/kenshin/simpread/ieu1w6 对比下你的配置有什么区别？

留意下：你的坚果云 Web 版中应该存在 `simpread_config.json`

**Comment by EdisonWendy** [comment]
搞定了，我是地址栏直接输入的“https://simpread.pro/@id”
这里面的ID没有修改成我自己在开放平台上设置的ID，修改成我自己的ID就正常进入个人中心了，谢谢解惑。

**Comment by Kenshin** [comment]
😂

竟然是这个问题，解决就好，我关闭这个 issues 了。
