### ISSUE TITLE
印象笔记无法授权

### ISSUE THREAD

**Issue by kankan235** [Kenshin/simpread#5332]
### 请选择

印象笔记

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#connect

**Comment by Kenshin** [comment]
嗨，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
