### ISSUE TITLE
Obsidian的SimpRead Sync插件的在网页中打开Obsidian中的md功能失效，报错404

### ISSUE THREAD

**Issue by JasonJarvan** [Kenshin/simpread#5333]
### 描述这个错误

在Obsidian中，打开默认保存的网页中的内部连接和外部连接，都报错{"code":404,"message":"没有找到对应的内容"}
![image](https://user-images.githubusercontent.com/49179818/225294998-7211486c-089a-402a-bc90-7713f25edba8.png)

这是我的Obsidian导出插件设置：
![image](https://user-images.githubusercontent.com/49179818/225294618-795d310d-aa06-4221-a876-c5e7681943e0.png)

这是我的Obsidian 的SimpRead Sync插件的设置：其中SR config Path是：E:/Documents/SZhao Files/syncthing同步/Simpread简悦
![image](https://user-images.githubusercontent.com/49179818/225295291-ab5f6281-aa41-4256-a33d-cf015f7be9f9.png)

### 复现步骤

在Obsidian中，打开默认保存的网页中的内部连接和外部连接，都报错{"code":404,"message":"没有找到对应的内容"}
![image](https://user-images.githubusercontent.com/49179818/225294998-7211486c-089a-402a-bc90-7713f25edba8.png)

### 其他相关说明

另外想请教一下，如何在简悦中打开已保存在Ob中的文章并进行注解及其同步？

### 操作系统

Windows10

### 浏览器

360极速浏览器X 21

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
嗨

这个问题是因为你的知识库配置错误，对比 https://www.yuque.com/kenshin/simpread/wkswh7 与你的配置有什么区别？

这个教程主要关注的地方在于：路径的设置，如果你不是很明确路径的话，建议跟教程中的一致。

> 另外请问能否将简悦当做一个在线编辑器使用？例如，我有一个MD文档，能否在简悦中编辑，再实现各笔记软件导出和同步？

简悦有个插件 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 可以实现「编辑功能」，同时也可以通过 [读取外部文件](https://github.com/Kenshin/simpread/discussions/4625) 来将 `.md` 识别为网页。

算是可以解决你的需求。

**Comment by JasonJarvan** [comment]
请问是同步助手的外部文件夹需要设置到Obsidian吗？但是我昨天完成Ob的高级版配置库后，外部文件夹没写，也是没问题的

![image](https://user-images.githubusercontent.com/49179818/225298105-c06a3e04-de03-4e76-a3f3-b957c2c7282b.png)

**Comment by JasonJarvan** [comment]
> 嗨
> 
> 这个问题是因为你的知识库配置错误，对比 https://www.yuque.com/kenshin/simpread/wkswh7 与你的配置有什么区别？
> 
> 这个教程主要关注的地方在于：路径的设置，如果你不是很明确路径的话，建议跟教程中的一致。
> 
> > 另外请问能否将简悦当做一个在线编辑器使用？例如，我有一个MD文档，能否在简悦中编辑，再实现各笔记软件导出和同步？
> 
> 简悦有个插件 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 可以实现「编辑功能」，同时也可以通过 [读取外部文件](https://github.com/Kenshin/simpread/discussions/4625) 来将 `.md` 识别为网页。
> 
> 算是可以解决你的需求。

您好，我对比了 https://www.yuque.com/kenshin/simpread/wkswh7，我在配置Obisidan配置库前按照这篇文档配置过一遍，刚刚又核对了一次，完全一样。请问还有可能是哪里配置错了？

**Comment by JasonJarvan** [comment]
另外，我刚刚尝试了一遍 导出到Obsidian，以及导出md+assets到Obisidan，都能正确导出到Obsidian下的指定目录。

**Comment by Kenshin** [comment]
404 的问题在于： output 文件夹（同步助手的导出文件夹）里面应该有 `3-xxx.html` 文件，`3` 是你第一个截图中的 `id`，如果没有，就是 404

你可以确认下。

**Comment by JasonJarvan** [comment]
您好，这是我的操作录屏，展示了我的配置、文件夹内容以及如何复现。
[简悦-打开Obsidian中文档返回404错误.zip](https://github.com/Kenshin/simpread/files/10979448/-.Obsidian.404.zip)

我在output中添加了html之后，确实可以打开了。但是Obsidian的配置库的Obsidian/SimpRead下的默认文档，不是不需要html就可以打开的吗？

**Comment by Kenshin** [comment]
> Obsidian/SimpRead下的默认文档

你指的是右边的吗？「也就是第一个图所示」，如果是的话，右边的嵌入标注模式是需要本地快照的。

**Comment by JasonJarvan** [comment]
> > Obsidian/SimpRead下的默认文档
> 
> 你指的是右边的吗？「也就是第一个图所示」，如果是的话，右边的嵌入标注模式是需要本地快照的。

嗯嗯，懂了。那我在嵌入标注模式下对原文进行更改的话，更改是否不会同步到obsidian/SimpRead里的.md文档，而是会保存到output里的html快照中？
如果是的话，请问有什么办法可以实现 “对导出到Obsidian的md文档进行注解/修改，其更改全部同步到Obsidian的md文档和其@annote文档中？”

**Comment by Kenshin** [comment]
> 那我在嵌入标注模式下对原文进行更改的话，更改是否不会同步到obsidian/SimpRead里的.md文档，而是会保存到output里的html快照中？

都会的，在 Obsidian 右侧标注的时候会同时更新 `.md` 和 `.html`

注意：这种更新是「单向」的，即稍后读（右侧） → 更新到 `.md` 如果你在 `.md` 的修改也会被覆盖。

**Comment by JasonJarvan** [comment]
[简悦bug_更新原文只更新到html不到md.zip](https://github.com/Kenshin/simpread/files/10982002/bug_.html.md.zip)

录屏记录了我在ob内置浏览器中编辑原文后，更新到了output中的html，却没有到obsidian中的md。

**Comment by Kenshin** [comment]
这个功能没有问题的，需要在 Obsidian SimpRead Sync 中设置对应的目录以及模板等。

PS：大部分高级功能的正常使用流程都不会有问题，如果有早就被用户发现并提交给我了。 😂

高级版的细节步骤，你可以看下 https://www.yuque.com/kenshin/simpread/fr8zo5
