### ISSUE TITLE
简悦打开外部文件夹后,无法用阅读模式编辑文件

### ISSUE THREAD

**Issue by JasonJarvan** [Kenshin/simpread#5335]
### 描述这个错误

简悦同步助手设置外部文件夹，并通过 http://localhost:7026/static 打开外部文件夹后，无法用阅读模式编辑文件。
下面是我的录屏：

[简悦-外部文件夹简悦打开后无法阅读模式.zip](https://github.com/Kenshin/simpread/files/10979363/-.zip)

### 复现步骤

[简悦-外部文件夹简悦打开后无法阅读模式.zip](https://github.com/Kenshin/simpread/files/10979363/-.zip)

### 操作系统

Windows10

### 浏览器

360极速浏览器X 21

### 发生问题的网址

http://localhost:7026/static

**Comment by JasonJarvan** [comment]
问题已解决，原来不能用localhost,必须用127.0.0.1……

**Comment by Kenshin** [comment]
是的 😂 `localhost` 无法使用简悦的阅读模式。
