### ISSUE TITLE
博客园文章导入到obsidian中公式显示问题

### ISSUE THREAD

**Issue by gongwangshen** [Kenshin/simpread#5336]
### 描述这个错误

导入到obsidian后，在ob的编辑模式下，行间公式显示正常，行内公式无法显示；在ob的阅读模式下，行内公式显示正常，行间公式无法显示

### 复现步骤

![image](https://user-images.githubusercontent.com/109449633/225502206-382ca21d-f1e2-47e8-ab3e-14057c96b431.png)

![image](https://user-images.githubusercontent.com/109449633/225502830-a0a43faa-1901-49bf-b34f-60008f30ea3e.png)

### 操作系统

windows

### 浏览器

edge 111.0.1661.41 (正式版本) (64 位)

### 发生问题的网址

https://www.cnblogs.com/pinard/p/6251584.html

**Comment by Kenshin** [comment]
我看了下，导出的 Markdown 没有问题，这属于 Obsidian 的问题吧... 😂

**Comment by gongwangshen** [comment]
好的，我在typora里面显示正常
