### ISSUE TITLE
TTS不可用

### ISSUE THREAD

**Issue by HaloTT** [Kenshin/simpread#5337]
### 描述这个错误

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/30413147/225517650-11e14792-fe2c-442a-b955-1ce4a8df9d55.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/30413147/225517718-eab64c7f-cf6c-4bbe-b870-174332d77ea2.png">
刚安装tts插件是能用的，我选自定义之后就没声音了，后面再切回内置的那几个也没声音。

### 复现步骤

<img width="673" alt="image" src="https://user-images.githubusercontent.com/30413147/225517945-67a5d433-ea35-4da7-8374-c7b78e1309d0.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/30413147/225518059-7f0272bb-3430-4250-a76b-5dd8e729aa39.png">

### 操作系统

macOS

### 浏览器

Chrome 已是最新版本 版本 111.0.5563.64（正式版本） (arm64)

### 发生问题的网址

https://javaguide.cn/java/concurrent/java-concurrent-questions-01.html#%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%B0%83%E7%94%A8-thread-%E7%B1%BB%E7%9A%84-run-%E6%96%B9%E6%B3%95%E5%90%97

**Comment by HaloTT** [comment]
一顿操作，不知道咋了又好了，我先关闭吧

**Comment by HaloTT** [comment]
微软TTS是不是有调用频率限制

**Comment by Kenshin** [comment]
> 微软TTS是不是有调用频率限制

emmm

会偶尔有失败的情况，跟具体网络有关。（但应该无法稳定复现），如果能复现的话，请提供 URL

**Comment by HaloTT** [comment]
> > 微软TTS是不是有调用频率限制
> 
> emmm
> 
> 会偶尔有失败的情况，跟具体网络有关。（但应该无法稳定复现），如果能复现的话，请提供 URL

可能是网络问题，但是好像缺少断点重试之类的机制，读一个无限瀑布的内容时，偶尔会断掉。并且缺少指定起点朗读的功能，又从头慢吞吞的读

**Comment by Kenshin** [comment]
> 读一个无限瀑布的内容时

URL 给我看下

> 并且缺少指定起点朗读的功能，又从头慢吞吞的读

接下来会有调整的功能。（语速，断点继读等）

**Comment by HaloTT** [comment]
> 

![90fdfa2bac11b4b599ccc87fe0793da5](https://user-images.githubusercontent.com/30413147/225562786-681eb10e-41c3-4cfe-afd5-b0c39168e824.jpg)
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/30413147/225563632-0d224a23-e8e9-4c65-8aec-3a1acc37df70.png">

https://github.com/gedoor/legado
是一个手机软件放出的内网web服务，他滑倒最后又会加载出下一章，阅读模式虽然选到的正文不包含下一章，但是TTS好像会朗读到
