### ISSUE TITLE
关于 Obsidian 的一些使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5339]
向老师请教个问题：单纯加入稍后读是不是不能导出html？我是使用导入到obsidian+自动化辅助增强插件的方案，无需进入阅读模式就可以通过快捷键加入稍后读，同时自动导出全文markdown（我使用的是md+assets全文方案）。

_Originally posted by @YB-Kang in https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-5330776_

**Comment by Kenshin** [comment]
@YB-Kang 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

触发自动化的条件：

1. 进入阅读模式
2. 通过快捷键 `d d` 或者（右键菜单）

除此之外，其它方式均无法触发自动化。（比如你提到的方式）

**Comment by YB-Kang** [comment]
@Kenshin 我测试的情况是：进入阅读模式后，没有任何标注的情况下加入稍后读，无法自动导出Html。必须任意选取一段文字标注，才会弹出标注控制栏，同时自动化导出html。

---
另外，我使用「导入到 Obsidian」的方案，无需进入阅读模式，通过快捷键或右键菜单的方式加入稍后读，就可以实现自动化导出全文Markdown。

![image](https://user-images.githubusercontent.com/55050981/225574482-b948df5b-2035-47e6-b22a-ad6fa93df7a8.png)

**Comment by Kenshin** [comment]
> 进入阅读模式后，没有任何标注的情况下加入稍后读，无法自动导出Html。必须任意选取一段文字标注，才会弹出标注控制栏，同时自动化导出html。

加入稍后读后右侧有侧栏出现吗？另外把你的选项页 → 服务 → 自动化以及自动化辅助增强插件截图给我。

导出 HTML 自动化的话常规做法：服务 → 自动化需要设置 **当加入稍后读后导出 HTML**

**Comment by YB-Kang** [comment]
没有任何标注的情况下，加入稍后读后右侧没有侧栏出现。

![image](https://user-images.githubusercontent.com/55050981/225630450-39264d64-9119-4394-9702-ca6c62b11165.png)

![image](https://user-images.githubusercontent.com/55050981/225630653-f6b2d5c9-8cf5-4246-adbe-a8d1649d2be8.png)

**Comment by Kenshin** [comment]
第一个图，有个「叹号」，你暂停了它… 😂

**Comment by YB-Kang** [comment]
> 第一个图，有个「叹号」，你暂停了它… joy

可以了，我重新设置扩展端的自动化，然后重启浏览器。

现在进入阅读模式后，通过快捷键或右键菜单加入稍后读，可以自动导出本地快照。

根据我的设置也会导出 md+assets。（这个昨天不进入阅读模式也能导出，现在不可以了，不过这个不管它了）

**Comment by Kenshin** [comment]
> 根据我的设置也会导出 md+assets。（这个不进入阅读模式也能导出）

不可能 😂 你可以录屏给我瞧瞧。

**Comment by YB-Kang** [comment]
> > 根据我的设置也会导出 md+assets。（这个不进入阅读模式也能导出）
> 
> 不可能 joy 你可以录屏给我瞧瞧。

重现不了了😢，前天一直可以导出，昨天自动化导出本地快照正常后就不太行了。

不知道咋回事，但偶尔可以，我昨晚又碰到一次。

![image](https://user-images.githubusercontent.com/55050981/226098735-2a6857ee-a6a8-4efb-b9d4-2e65d380819e.png)

我一般进入阅读模式，加入稍后读会触发自动化导出本地快照和md+assets。最下面那条md+assets是在非阅读模式下导出的。

**Comment by Kenshin** [comment]
是不是你曾经进入过阅读模式（按代码的逻辑也不通啊 😂
