### ISSUE TITLE
annotation 无法保存到指定文件夹内

### ISSUE THREAD

**Issue by Mingmingshuai** [Kenshin/simpread#5342]
### 描述这个错误

标注网页后，annoted md 未存入Ob文件夹内

### 复现步骤

目前使用简悦与Obsidian联动，同步方案利用Simpreadsync, Ob已安装指定插件（dataveiw、obsidian242-BRA、Simpreadsync），目前导入全文到Ob，没有问题，Ob中也能看到保存的MD，文件 如下图
![image](https://user-images.githubusercontent.com/76103984/225882343-9f409c5a-9631-4244-9fb5-1970fe4bf6f5.png)
![image](https://user-images.githubusercontent.com/76103984/225883531-82bf0a2c-ca15-4124-829d-07f6edb3d9aa.png)

对网页进行标注，自动化部署触发，可以保存好原网页（html)和标注网页文件（annoted html），
![image](https://user-images.githubusercontent.com/76103984/225884146-60e99ad4-cf7a-4889-b406-b9659dbb4cfb.png)

但是没有保存annoted md文件 

尝试手动点击导入标记到Ob，打开文件也只是空白，如下图
![image](https://user-images.githubusercontent.com/76103984/225883158-79a03b24-ba61-4f7e-8da0-b7bbaa5142a6.png)
![image](https://user-images.githubusercontent.com/76103984/225883236-da424f43-18de-406b-b4a5-8dbfaa0fb953.png)

### 操作系统

win11

### 浏览器

Edge

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
嗨

除了 Obsidian 插件外，还需要 [Markdown 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3725)

同时导入到 Obsidian 插件需要开启下图所示的功能

<img width="614" alt="image" src="https://user-images.githubusercontent.com/81074/225887230-d0abb068-d9f6-4a9d-9805-b7207785457b.png">

另外，也可以使用 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 实现更灵活的自动化方案。

PS：上述内容可以看下 https://www.yuque.com/kenshin/simpread/fr8zo5 这个教程。
