### ISSUE TITLE
百家号的所有文章都不能适配

### ISSUE THREAD

**Issue by ht09p6o123** [Kenshin/simpread#5343]
### 需要适配的新站

https://baijiahao.baidu.com/s?id=1599423529802167462&wfr=spider&for=pc

https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_9614121448330783608%22%7D&n_type=1&p_from=4

永恒的提示：

![image](https://user-images.githubusercontent.com/126762024/225926001-76a73ec0-d454-4a72-8136-227cee9c8b7f.png)

**Comment by Kenshin** [comment]
okay 可能是它的页面结构改变了，我明天确认下。

**Comment by ht09p6o123** [comment]
### 老大，怎么了？你能抽点时间弄好这个问题吗？谢谢了

**Comment by Kenshin** [comment]
嗨，这个站点已更新，请通过 https://github.com/Kenshin/simpread/discussions/2870 更新，并留意下图的说明

![SCR-20230330-pa8](https://user-images.githubusercontent.com/81074/228804557-dd38e20a-662c-4b91-b299-444ae67eca5f.png)
