### ISSUE TITLE
由于后台异常导致恢复购买失败，请稍后再试。

### ISSUE THREAD

**Issue by cosineDaDa0623** [Kenshin/simpread#5345]
### 描述这个错误

我购买了高级账户并且绑定了设备，能在后台查到，但是我无法使用高级功能，恢复购买提示由于后台异常导致恢复购买失败，请稍后再试。请问该怎么办

### 复现步骤

![image](https://user-images.githubusercontent.com/88964258/226093887-48cfac73-2806-49c8-a177-6cd106973528.png)

### 操作系统

windows

### 浏览器

google Chrome

### 发生问题的网址

由于后台异常导致恢复购买失败，请稍后再试。

**Comment by Kenshin** [comment]
解决方案 https://www.yuque.com/kenshin/simpread/tmmwhl

**Comment by Kenshin** [comment]
或者使用 https://www.yuque.com/kenshin/simpread/ga970q
