### ISSUE TITLE
获取时出现问题导致仅获取成功了您的第一个Notion Page

### ISSUE THREAD

**Issue by name2500** [Kenshin/simpread#5346]
### 描述这个错误

获取时出现问题导致仅获取成功了您的第一个Notion Page，虽然不影响导出服务，但是很烦。。。

### 复现步骤

1.导入
2.只有第一个选项

### 操作系统

WINDOWS

### 浏览器

Edge

### 发生问题的网址

ww

**Comment by Kenshin** [comment]
嗨，解决方案 https://www.yuque.com/kenshin/simpread/wwk65u
