### ISSUE TITLE
没有收到码，无法开启高级功能

### ISSUE THREAD

**Issue by UXmiao** [Kenshin/simpread#5348]
### 请描述你的建议或任何内容

1219444386@qq.com
![image](https://user-images.githubusercontent.com/101417830/226157425-11559b7c-121f-4794-9ba4-fe73456d360d.png)

### 补充说明

已经支付了

**Comment by Kenshin** [comment]
不要同一个内容反复在不同的 Issues 提交...

如果是腾讯问卷付款的话，在付款前和付款时，都有明确说明。

<img width="903" alt="image" src="https://user-images.githubusercontent.com/81074/226161490-deb39f9a-820c-4819-a1e8-2e427fd83c68.png">

今天晚上 19点左右会收到兑换码。

***

如果是爱发电付款的话，登录你的爱发电查看私信。

**Comment by UXmiao** [comment]
11元是永久版本吗？如果不是我补差价永久的支持你










WH丶Design
***@***.***


---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2023年3月19日(周日) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 没有收到码，无法开启高级功能 (Issue #5348)




 
不要同一个内容反复在不同的 Issues 提交...
 
如果是腾讯问卷付款的话，在付款前和付款时，都有明确说明。
 

 
今天晚上 19点左右会收到兑换码。
 
 
如果是爱发电付款的话，登录你的爱发电查看私信。

**Comment by Kenshin** [comment]
是的，扩展版就是这个价格。

**Comment by UXmiao** [comment]
好的，永久版包括所有的功能(阅读模式 + 标注系统 + 稍后读)?


&nbsp;


WH丶Design
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kenshin ***@***.***&gt;; 
发送时间: 2023年3月19日(星期天) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 没有收到码，无法开启高级功能 (Issue #5348)





 
是的，扩展版就是这个价格。
