### ISSUE TITLE
稍后读中的阅读模式中相对地址的链接错误

### ISSUE THREAD

**Issue by thredreams** [Kenshin/simpread#5349]
### 描述这个错误

我觉得应该有相关的issuses但是找了半天了，没找到。
bug如题：在稍后读的阅读模式中，有些地址因为是相对地址，所以变成了相对于插件地址，于是无效了。

### 复现步骤

1. 在arxiv中打开任一篇论文简介 “https://arxiv.org/abs/2303.09461”
2. dd加入稍后读
3. 在稍后读中以阅读模式查看，发现其中的download无效了。
![image](https://user-images.githubusercontent.com/44553414/226158346-6fb79f7c-c9a8-4291-adea-d20dcd386243.png)

### 其他相关说明

可能相关的报错：
![image](https://user-images.githubusercontent.com/44553414/226158337-d85c981d-351e-4407-b1b3-da5bd2c6b4a8.png)

### 操作系统

windos

### 浏览器

edge

### 发生问题的网址

https://arxiv.org/abs/2303.09461

**Comment by Kenshin** [comment]
嗨，谢谢反馈，严格意义上说，这不算是 Bug。

1. 你可以使用这个插件 https://simpread.ksria.cn/plugins/details/TgxCzObXib 来转换为绝对链接。

2. 如果没有特殊设置的话，简悦的稍后读读的是原页面，所以即便是安装了步骤1的插件也有问题，但简悦是基于本地系统的稍后读产品。

基于第二点，如果你使用了同步助手的话，可以将简悦设置为知识库方案，当设置后，简悦的稍后读读的就是本地文件，而步骤1会让相对链接转换为绝对链接，这时的本地文件就是绝对链接。

知识库的教程 https://www.yuque.com/kenshin/simpread/wkswh7
同步助手的介绍 https://simpread.pro/docs/#/Sync

PS：如果你没有使用同步助手，也可以正常使用简悦的各种功能（跟同步助手相关的功能不算），只是个建议。同步助手相关功能更适合将简悦当作双链笔记一部分的用户。
