### ISSUE TITLE
simpread extension 中的插件在一些浏览器上不能使用

### ISSUE THREAD

**Issue by sunosh** [Kenshin/simpread#535]
例如 Microsoft Edge  Version 77.0.197.1 (Official build) dev (32-bit) , Vivaldi | 2.6.1566.44 (Stable channel) (32-bit) ，Firefox Version 67.0.4 .
能够正常进入阅读模式，但在阅读模式中无法使用插件。
测试时停用了 3 个浏览器的全部其他 extensions（ adds-on ）， Firefox 还停用了内置拦截器，统一使用 https://sspai.com/post/55394 这个网页测试。

**Comment by Kenshin** [comment]
谢谢这么详细的测试，但我没有遇到你说的问题。

你的意思是指：

- 能运行简悦，但简悦的某些插件无法使用？（具体是哪几个？

- 在上述浏览器里面无法运行简悦？（如果是这样的话，请问你是通过什么途径安装的简悦？

***

Edge

![image](https://user-images.githubusercontent.com/81074/60226896-cb63c680-98bf-11e9-9b30-86a0973ef73a.png)

![image](https://user-images.githubusercontent.com/81074/60226907-d4549800-98bf-11e9-9dfb-c0a56dc290d3.png)

***

Vivaldi

![image](https://user-images.githubusercontent.com/81074/60227074-7bd1ca80-98c0-11e9-8e24-d120981811d6.png)

![image](https://user-images.githubusercontent.com/81074/60227089-868c5f80-98c0-11e9-8f98-ff879821ee7c.png)

***

Firefox

![image](https://user-images.githubusercontent.com/81074/60227111-a4f25b00-98c0-11e9-9a11-dc3295d8693a.png)

![image](https://user-images.githubusercontent.com/81074/60227152-c9e6ce00-98c0-11e9-90ad-4befe250e2aa.png)

***

PS：截图是没有使用你说的网址，但应该没有关系，之后又使用了你说的网址测试，也没有遇到问题。

**Comment by sunosh** [comment]
这是很奇怪的，其他用户不能 reproduce the bug .
- 插件：模仿 Safari 阅读模式样式
- Chrome Web Store

**Comment by sunosh** [comment]
> 谢谢这么详细的测试，但我没有遇到你说的问题。
> 
> 你的意思是指：
> 
> * 能运行简悦，但简悦的某些插件无法使用？（具体是哪几个？
> * 在上述浏览器里面无法运行简悦？（如果是这样的话，请问你是通过什么途径安装的简悦？
> 
> Edge
> 
> ![image](https://user-images.githubusercontent.com/81074/60226896-cb63c680-98bf-11e9-9b30-86a0973ef73a.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/60226907-d4549800-98bf-11e9-9dfb-c0a56dc290d3.png)
> 
> Vivaldi
> 
> ![image](https://user-images.githubusercontent.com/81074/60227074-7bd1ca80-98c0-11e9-8e24-d120981811d6.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/60227089-868c5f80-98c0-11e9-8f98-ff879821ee7c.png)
> 
> Firefox
> 
> ![image](https://user-images.githubusercontent.com/81074/60227111-a4f25b00-98c0-11e9-9a11-dc3295d8693a.png)
> 
> ![image](https://user-images.githubusercontent.com/81074/60227152-c9e6ce00-98c0-11e9-90ad-4befe250e2aa.png)
> 
> PS：截图是没有使用你说的网址，但应该没有关系，之后又使用了你说的网址测试，也没有遇到问题。

这是很奇怪的，其他用户不能 reproduce the bug .
- 插件：模仿 Safari 阅读模式样式
- Chrome Web Store

**Comment by Kenshin** [comment]
> 包括但不限于 模仿 Safari 阅读模式样式 ，划词翻译 ，划词搜索 

任意插件均无法使用吗？另外，在 Chrome 下是否可以使用这些插件？

PS：上条 issue quote 的内容太多了，我帮你删除了下。

**Comment by sunosh** [comment]
任意插件均无法使用，在 chrome 下均可正常使用。

**Comment by Kenshin** [comment]
无法使用的具体现象是什么？
阅读模式 → 控制栏 → 插件 里面没有显示？
或者说，压根无法安装？

**Comment by sunosh** [comment]
> 无法使用的具体现象是什么？
> 阅读模式 → 控制栏 → 插件 里面没有显示？
> 或者说，压根无法安装？

- 阅读模式 → 控制栏 → 插件 里面有显示

- 安装成功
阅读模式 → 控制栏 → 插件 里面有显示，且成功安装。
无法使用指插件不生效。比如安装 划词搜索 后，在阅读模式中划词并不弹出搜索框。

通过清除数据或清除本地全部插件后，插件可以使用（三个浏览器）。
正印证了一句话：绝大多数提问的问题，提问者会在24小时内自行解决~

**Comment by Kenshin** [comment]
搞定就好~

---

这个现象有可能是 Bug （ 极端情况下的个例
你能否描述下，出现错误时的配置文件 都是通过什么方式得到的？
