### ISSUE TITLE
md + assets 方式导入到 Obsidian 时无法保存图片

### ISSUE THREAD

**Issue by systemX1** [Kenshin/simpread#5352]
### 描述这个错误

md + assets 方式导入到 Obsidian 时保存的图片都是空的，markdown正常
![image](https://user-images.githubusercontent.com/52664228/226208020-934b7ac8-7ba3-4488-9066-5b9444e5ddb6.png)

### 复现步骤

![image](https://user-images.githubusercontent.com/52664228/226208287-61cd8cb3-a74d-43ae-a448-a1b4e239755a.png)
![image](https://user-images.githubusercontent.com/52664228/226208100-1c4ef170-2af2-4a16-b6a6-b6ce5400208d.png)
![image](https://user-images.githubusercontent.com/52664228/226208141-9294fca1-a18c-4e1d-b236-14e603bc93e4.png)
![image](https://user-images.githubusercontent.com/52664228/226208167-dce30df7-d19f-4ac6-90de-2cc586f34fd9.png)
![image](https://user-images.githubusercontent.com/52664228/226208339-f5795ef7-7a7c-4889-833d-6e2d8a9c3b3a.png)

### 操作系统

win10

### 浏览器

Microsoft Edge 版本 111.0.1661.44 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/612418135

**Comment by Kenshin** [comment]
嗨，我这边没有复现。

1. 是每个 URL 都有问题？还是仅此一个？
2. 在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

另外，导入到 Obsidain 中，也有关于 assets 的设置，你没有截图给我。（虽然不更改任何 assets 的设置也可以使用，但以防万一，还是截图给我看下。

**Comment by systemX1** [comment]
> 

每个 URL 都有问题；不知道怎么在隐身模式下使用插件，但是我换成chrome canary浏览器也还是一样(同一个simpread_config.json，只有简悦一个插件)。设置完后浏览器和电脑都重启过

![image](https://user-images.githubusercontent.com/52664228/226255859-34ca1c7c-858a-4f3c-9942-cbb76b6fa2c9.png)
![image](https://user-images.githubusercontent.com/52664228/226255795-dde43602-9e06-4f53-866a-db2d321cdc65.png)
![image](https://user-images.githubusercontent.com/52664228/226255384-5af3b6e9-f1a8-47a4-b829-f77b84b5c084.png)
![image](https://user-images.githubusercontent.com/52664228/226252620-cc893adb-c0c7-4469-b401-117c03b715d4.png)
![image](https://user-images.githubusercontent.com/52664228/226252761-4955b7a5-facd-4ff9-be04-ee89cf83f824.png)
![image](https://user-images.githubusercontent.com/52664228/226252838-485e3605-f174-4342-8ad5-2df72b266c87.png)

**Comment by systemX1** [comment]
`导入全文到Obsidian`的功能是正常的。
![image](https://user-images.githubusercontent.com/52664228/226257987-4d72d3b3-e0f2-4040-98bc-69c6305474e4.png)

另外我开了vpn不知道有没有影响
![image](https://user-images.githubusercontent.com/52664228/226258137-2ab37d14-007c-43ae-a496-e0c938453a70.png)

**Comment by Kenshin** [comment]
下面这个选项没开

<img width="734" alt="image" src="https://user-images.githubusercontent.com/81074/226267123-3ef5e743-50f4-4249-a335-a72e5bf3a4c8.png">

如果你使用了下图的方式，可不用开上面的选项

<img width="345" alt="image" src="https://user-images.githubusercontent.com/81074/226267291-8f329caf-2608-4fed-a17f-ca8bfb91f803.png">

另外，你的 Obsidian 是不是有什么其它插件？（最好暂时先都禁用它们）

> 另外我在使用过程中开了vpn不知道有没有影响

有可能，关闭它们，然后在 https://sspai.com/post/69972 上测试。

**Comment by systemX1** [comment]
感谢回复，我还是放弃吧...也折腾几个小时了，用给的Obsidian模板也不行，日志甚至没有图片相关的输出

**Comment by Kenshin** [comment]
有以下几个方案：

1. 新用户的话，直接配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0

2. 如果只想使用 md + assets 方案的话，直接使用 https://github.com/Kenshin/simpread/discussions/4041

个人建议方案1

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0 **增强了对部分图片无法正常保存的问题**（如少数派）。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
