### ISSUE TITLE
notion账户授权页面即使star也仍然一直重置，无法选取页面

### ISSUE THREAD

**Issue by MaceBanana** [Kenshin/simpread#5353]
### 描述这个错误

之前是chrome上没办法安装插件，因此我将所有的插件清除然后按照一站式教程重新给chrome安装了所有插件并进行设置，但是在设置完后，我无法修改token和页面编码，同时页面的选取也开始出现问题，因此我只好又重新安装一遍chrome上的简悦以及所有插件，之后我成功修改了token和页面编码，但是页面选取始终无法成功，导致我后来原本能正常使用的edge浏览器也出现了同样的问题。

### 复现步骤

上述

### 操作系统

win10

### 浏览器

chrome 版本111.0.5563.65（正式版本）（64 位）

### 发生问题的网址

https://www.zhihu.com/

**Comment by MaceBanana** [comment]
不好意思有点神志不清，补充一下，是搭配notion的一站式配置

**Comment by Kenshin** [comment]
是不是使用了同步助手？如果是的话，最简单的办法是：

1. 先关闭同步助手的自动同步。
2. 然后设置。
3. 设置时，仅开两个 Tab，一个是测试页，一个是选项页。（当其中一个设置修改后，刷新页面，确保生效，另外一个页面也刷新。

当你的需求满足后，确认都可以使用后。

1. 重启浏览器
2. 开启自动同步，并覆盖到本地配置文件。
3. 重启浏览器后测试上面的流程是否 OK

设置后无法保存的原因有两个：

1. 修改后，因为其它 Tab 没有刷新导致配置被覆盖。
2. 使用同步助手后可能因为 https://www.yuque.com/kenshin/simpread/fcw60u 导致的
