### ISSUE TITLE
配置文件，同步插件时不包含插件的配置吗？

### ISSUE THREAD

**Issue by Yapwn** [Kenshin/simpread#5357]
### 请描述你的建议或任何内容

今天遇到了配置文件错误的问题

**Comment by Kenshin** [comment]
1. 配置文件包含插件的配置。
2. 配置文件不包含插件本身（因为插件太大了。）

所以，当导入新设备后需要手动导入插件，位置在：选项页 → 插件管理 → 从配置文件导入插件。

**Comment by Yapwn** [comment]
导入插件的时候，会自动导入插件的配置是吗？

**Comment by Kenshin** [comment]
不会。

在你原来的浏览器使用选项页 → 共通 → 导出配置文件到本地。

然后用这个配置文件导入新的浏览器试试。

**Comment by Kenshin** [comment]
确保同步助手 1.1.2 版，用出错的配置文件使用 [此方式](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e4%bf%ae%e5%a4%8d%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6)  修复。

**Comment by Kenshin** [comment]
补充下：使用同步助手的前提下。

**Comment by Yapwn** [comment]
同步助手我是一直开着的，但是我这边的版本是1.2.0，确定要1.1.2吗？
<img width="685" alt="image" src="https://user-images.githubusercontent.com/49093992/226935731-0ce7fe98-c9ce-4ff7-82fc-50fc1377009c.png">

**Comment by Kenshin** [comment]
> 在简悦插件页面通过用户配置文件导入插件时，会自动导入插件相应的配置吗？

不会，这个过程只能导入插件（本身）。使用下面的方式在导入配置文件时自动就包含了插件。

<img width="903" alt="image" src="https://user-images.githubusercontent.com/81074/227090947-5e3aa761-418f-41c6-b8cb-166e9c315391.png">

***

再说下你的问题：

> （猜测）使用同步助手后，可能是因为隐性 Bug 导致插件的配置没有成功保存到本地的配置文件中。

解决方案：使用好使的那个浏览器

1. 选项页 → 共通 → 关闭自动同步
2. 重启浏览器
3. 选项页 → 共通 → 导出配置文件到本地
4. 这时步骤1的配置文件应该含有插件
5. 将这个插件导入到新的浏览器
6. 选项页 → 插件管理器 → 导入配置文件中的插件
7. 重启浏览器
8. 随便进入个页面 e.g. https://sspai.com/post/69972 查看你的插件配置是否已经成功导入。

如果没有问题的话

1. 选项页 → 共通 → 开启自动同步，然后覆盖本地配置文件到本地。

最后在确认无误即可。

PS：然后可以使用  [此方式](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e4%bf%ae%e5%a4%8d%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6)  检查下你的配置文件有没有其它问题。

PPS：上面的步骤看着挺多，其实很简单，每个步骤一个操作，只是为了防止某些用户不了解，所以我写的比较细致。

**Comment by Yapwn** [comment]
行，我再按照你说的这个试一试
配置文件里的这个部分应该是存储插件配置的地方吧：
<img width="537" alt="image" src="https://user-images.githubusercontent.com/49093992/227130851-50a9c181-c769-477a-ae73-54eeb7e7b906.png">

**Comment by Kenshin** [comment]
> 配置文件里的这个部分应该是存储插件配置的地方吧

是的，这个截图至少说明插件的配置都在。😂

**Comment by Yapwn** [comment]
刚刚按照这个方法试了一下，还是不行，插件的配置还是没有导进去

> 解决方案：使用好使的那个浏览器
> 
> 1. 选项页 → 共通 → 关闭自动同步
> 2. 重启浏览器
> 3. 选项页 → 共通 → 导出配置文件到本地
> 4. 这时步骤1的配置文件应该含有插件
> 5. 将这个插件导入到新的浏览器
> 6. 选项页 → 插件管理器 → 导入配置文件中的插件
> 7. 重启浏览器
> 8. 随便进入个页面 e.g. https://sspai.com/post/69972 查看你的插件配置是否已经成功导入。
————————————————————————————————————————————————
刚刚顺便看了看这次的错误，和检测到的错误原因：
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/49093992/227136384-44a92e5a-6dd9-47e7-ad44-a35fbc142e33.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/49093992/227136949-6bca69a4-a5fa-4157-8ef3-a4639b40665f.png">

**Comment by Yapwn** [comment]
我直接在配置文件里找的了这条稍后读，并手动为该条稍后读添加了title，然后重新导入配置文件，配置文件可以用了，但是插件配置还是导不进去。

**Comment by Kenshin** [comment]
> 然后重新导入配置文件，配置文件可以用了

看起来应该还是没有按照我说的方式导入。（也就是没有关闭同步助手的自动同步功能，而直接导入了。）

如果你的配置文件没有问题了，可以试试删除并重新安装简悦。

**Comment by Yapwn** [comment]
我是按照你说的步骤一步步弄的（包括关闭了同步助手的自动同步功能），但就是没有效果

**Comment by Kenshin** [comment]
emmm 那不应该啊。

还有，是否是删除并重新安装插件？

如果想要验证你的操作步骤，根据 https://github.com/Kenshin/simpread/issues/5357#issuecomment-1480543767 这个页面的描述，最后一步不要开自动同步。

在没有开自动同步的前提下，看看你的插件配置是否正常？

**Comment by Yapwn** [comment]
emmm，我前一次就是删除了简悦，之后重新安装，然后再导入配置文件，那个时候简悦都是重新安装的，必不可能开同步配置，我觉得。。。

> 在没有开自动同步的前提下，看看你的插件配置是否正常？

**Comment by Kenshin** [comment]
我看你会改配置文件，直接把下图所示的地方改为 `false`

<img width="390" alt="image" src="https://user-images.githubusercontent.com/81074/227422035-06b52047-f8c1-43f1-aa7f-574881c1e665.png">

重新安装简悦然后导入，这时自动同步肯定是关闭的，如果你的配置文件还有插件配置的话， 100% 能正常导入。

再测试下。

**Comment by Yapwn** [comment]
> 我看你会改配置文件，直接把下图所示的地方改为 `false`

<img width="681" alt="image" src="https://user-images.githubusercontent.com/49093992/227679089-a48505e6-c5c8-422d-9c44-8067cd8fb4bd.png">

然而还是不行，是配置文件的插件配置有问题吗？😂

<img width="720" alt="image" src="https://user-images.githubusercontent.com/49093992/227679529-db41cc45-8aa0-452c-9f27-7484fdc48a6c.png">

我怎么能够知道上面插件ID实际对应的插件是啥？

**Comment by Kenshin** [comment]
前几天出差，漏掉了这个 issues...

比如 https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z 其中 `1VQ19jCD8Z` 就是这个插件的 ID

**Comment by TheTruthYouKnow** [comment]
令人脑溢血的官方说明，我不确定你的问题是不是和我一样，
去插件市场多安装几个插件，随便哪几个都可以，然后导出配置文件，检查配置文件插件，我的永远是这九个，如果你也一样，大概率触发了这个BUG。
![image-20230508003925484](https://github.com/Kenshin/simpread/assets/131973717/e24a51a4-1730-4d87-8cba-b526da5a9d22)
无论是重启浏览器，同步助手，手动导出配置文件还是官方的操作，你配置文件永远是这九个插件，其他的插件ID都不在。

**Comment by Kenshin** [comment]
@TheTruthYouKnow 

你的问题跟 #5357 无关... 你的问题在于：使用了同步助手的自动同步功能，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u

另外，你应该用了配置库方案，配置库文档里面有关于这个链接的详细说明...

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
