### ISSUE TITLE
标注后内部链接打开，无图片显示

### ISSUE THREAD

**Issue by Mingmingshuai** [Kenshin/simpread#5358]
### 描述这个错误

在使用自动化方案，将网页标注导入到Ob中，Ob中打开后，点击内部链接，右侧栏无图片显示

### 复现步骤

1. 已配置Obsidian配置库，已使用Simpread Sync插件，Markdown 模板辅助增强，导入全文到Ob没有问题，如下图所示
![image](https://user-images.githubusercontent.com/76103984/226535553-1b26f886-9aea-4c60-b7b1-b3e8757916db.png)
![image](https://user-images.githubusercontent.com/76103984/226535642-d192e601-229c-49d3-bfe9-9dab10c6ca97.png)
![image](https://user-images.githubusercontent.com/76103984/226535791-5b950e87-c07f-439a-9f9f-0d7b7fe46edf.png)
2. 已配置好自动化方案，利用同步助手和Simpread sync， 如下图所示
![image](https://user-images.githubusercontent.com/76103984/226535991-ef75e201-1bf8-45d1-84c5-0f08aa7cba67.png)
![image](https://user-images.githubusercontent.com/76103984/226536130-28bda4ad-04f9-441c-91c5-0f0f65fe1a5c.png)
3. 进入阅读界面后，对图片进行标注，打开后，点击内部链接，右侧展开网页中，只有文字没有图片，如下图所示
![image](https://user-images.githubusercontent.com/76103984/226536345-88e91231-e829-4636-9b98-c8bb8896b277.png)

### 操作系统

win11

### 浏览器

Edge

### 发生问题的网址

https://www.zhihu.com/question/587648959

**Comment by Kenshin** [comment]
试试 https://sspai.com/post/69972 在 Obsidian 右侧是否存在图片？另外你的这个问题能否稳定复现？

**Comment by Mingmingshuai** [comment]
已经尝试，表现一致，如图，这个问题稳定存在，已经持续一周
![image](https://user-images.githubusercontent.com/76103984/226543154-b9f24693-3961-4333-ba43-0e3915dc05f6.png)

**Comment by Kenshin** [comment]
选项页 → 服务 → 定制导出，开启下面的选项。（开启后重启浏览器，并确认选项已开启）

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/81074/226543574-0a240fee-e576-4ac2-afa3-8a251ea4567f.png">

开启后，在上图这个例子中，重新导出一次 HTML

<img width="355" alt="image" src="https://user-images.githubusercontent.com/81074/226543793-0dc69a9b-bdd0-4497-9f77-24cd518aa817.png">

直接访问 http://localhost:7026/unread/25 看看能否有图片？如果有图片的话，在通过 Obsidian 右侧查看。

**Comment by Mingmingshuai** [comment]
原本就已开启下面的选项
![image](https://user-images.githubusercontent.com/76103984/226545280-2ee56004-3ea8-4eb6-be39-2b36b742c102.png)
尝试再次导出，直接访问 http://localhost:7026/unread/25 ，仍旧无图
![image](https://user-images.githubusercontent.com/76103984/226545648-9a4960ad-63e3-4dff-8351-2d9b7ddd7c82.png)

**Comment by Mingmingshuai** [comment]
补充说明，单独打开两份html文件，显示正常
![image](https://user-images.githubusercontent.com/76103984/226546923-50093d53-0146-4589-a2e2-2b4e43921b4d.png)
![image](https://user-images.githubusercontent.com/76103984/226546943-b524ba56-e019-4752-991a-dfa14461811f.png)
另外，在localhost中打开，虽然图片不显示，但是对图片的标注后，右侧栏可以看到
![image](https://user-images.githubusercontent.com/76103984/226547121-ea962fa8-36e9-4f74-bbcc-de3883a1c001.png)

**Comment by Kenshin** [comment]
emmm 上面例子中的 `.html` 发给我。

浏览器打开 http://localhost:7026/unread/25 然后看下图所示，截图给我。

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/81074/226550699-b9eda0a9-b1db-4250-8413-3d1f26260654.png">

访问 http://localhost:7026/proxy?url=https://cdn.sspai.com/2021/11/17/02dcb3e22348318ab27890b2272242a6.png 看看返回什么？（正常应该是图片

**Comment by Mingmingshuai** [comment]
检查截图如下
![image](https://user-images.githubusercontent.com/76103984/226555096-fd4f45b8-fcb5-477c-bb03-fddb3c6df09d.png)
打开网页返回的结果如下
![image](https://user-images.githubusercontent.com/76103984/226555212-b2e3ef05-e06f-4f78-9d92-e9fa20b8a43c.png)
html文件如下
[Website.zip](https://github.com/Kenshin/simpread/files/11026344/Website.zip)

**Comment by Kenshin** [comment]
那应该没问题才对....

你在上图的基础上，按下图所示打开这个 URL 打开后应该会在浏览器中打开这个 URL，看下是否可以正常显示？如果无法正常显示的话，把这个 URL 发给我。

![image](https://user-images.githubusercontent.com/81074/226575550-0b88714a-6d45-47ba-af01-f6c6c2ae6abd.png)

另外，看下你的同步助手设置应该是下图所示

![image](https://user-images.githubusercontent.com/81074/226575696-ce5c32cd-0ae7-4204-8084-ff1b8483fbcb.png)

看看你的简悦扩展端 → 服务 → 增强导出，下图应该都开了

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/81074/226575918-e28e8e75-64ff-4fe8-a1a5-4f02e8a74964.png">

***

还有，你是不是用了什么全局的广告拦截工具 e.g. Adguard 等？

**Comment by Kenshin** [comment]
> 浏览器此前使用了Adguard, 尝试关闭插件

那就是 Adguard 的问题，把桌面端的也关了，然后重启浏览器后测试。（确保 Adguard 全部被关闭）

**Comment by Mingmingshuai** [comment]
删除了Adguard, 系统并没有安装桌面端，重启浏览器后测试问题仍然存在
