### ISSUE TITLE
无法识别csdn文章中只有一行的代码

### ISSUE THREAD

**Issue by zlxuan** [Kenshin/simpread#5359]
### 描述这个错误

在这个[xlwings文章](https://blog.csdn.net/qfxietian/article/details/123822358)中，无法识别只有一行代码的代码块，比如引用库`import xlwings as xw`这一行代码，导致后面的代码块都上移了一个，导致排版出现顺序错误

### 复现步骤

1. 打开文章连接
2. 使用简悦阅读模式

### 操作系统

windows11

### 浏览器

chrome版本 111.0.5563.65（正式版本） （64 位）

### 发生问题的网址

https://blog.csdn.net/qfxietian/article/details/123822358

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
