### ISSUE TITLE
新站适配：Microsoft Learn

### ISSUE THREAD

**Issue by Hou-yanbin** [Kenshin/simpread#5360]
### 请描述你的建议或任何内容

https://learn.microsoft.com/zh-cn/azure/cloud-adoption-framework/govern/security-baseline/#develop-governance-policy-statements

**Comment by Kenshin** [comment]
okay 我明天确认下，你可以试试 https://github.com/Kenshin/simpread/discussions/3216 提到的方案。

**Comment by Kenshin** [comment]
抱歉 😂

忘记确认了，近期在出差，没法确认了，等到下周二才行。

**Comment by Kenshin** [comment]
暂时可以使用下面的方案

<img width="862" alt="image" src="https://user-images.githubusercontent.com/81074/228125064-7b9d1737-e1f0-4e1b-ab55-39a897bd9fac.png">

同时也可以考虑适配这个站，我先记录下。

但这类页面可能适配起来不是那么完美。

**Comment by Hou-yanbin** [comment]
好的，麻烦啦，产品很棒

**Comment by Kenshin** [comment]
嗨，这个站已经更新，具体规则 [请看这里](https://github.com/Kenshin/simpread/discussions/5418#discussioncomment-5495675)
