### ISSUE TITLE
关于稍后读的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5361]
我这个也是不成功额，以为是知识库什么的没配置好，又配置了一遍，最后就是图片这情况了
![a](https://user-images.githubusercontent.com/39293756/226896898-d010b356-c145-447b-aeaa-7621de23a3b2.gif)

_Originally posted by @shitwall11 in https://github.com/Kenshin/simpread/discussions/3216#discussioncomment-5392177_

**Comment by Kenshin** [comment]
@[shitwall11](https://github.com/shitwall11)

请不要在不相关的位置提问，我帮你建了个 Issues 描述。

不过，请详细说明你的问题… 😂

**Comment by shitwall11** [comment]
可能问题是相关的，但是这个图片看起来不雅，哈哈~
问题就是选取页面中自己想要的部分内容生产稍后读，但是，不成功，本地的output下没有文件，所以，打开稍后读还是原始页面，而不是我选取的内容…
[https://github.com/Kenshin/simpread/discussions/3216](url)

**Comment by Kenshin** [comment]
那应该是知识库相关的功能没有配置好，看下这个教程 https://www.yuque.com/kenshin/simpread/wkswh7 跟你对比下。

**Comment by shitwall11** [comment]
昨天说的就是按照这个手册配的，但是，真不知道哪里设置的不够额

**Comment by Kenshin** [comment]
按照 https://github.com/Kenshin/simpread/issues/5361#issuecomment-1480660494 给的链接对应的教程，把你的相关设置截图给我

**Comment by shitwall11** [comment]
![aa](https://user-images.githubusercontent.com/39293756/227137595-bfe7c0c5-bb43-44ba-ac40-3fe6bfa88734.png)
图片太大，第二次才上传成功~

**Comment by Kenshin** [comment]
emmm

看了你的截图，我大概知道你要做什么了，有个更简单方案：

如果没有稍后读（或稍后读很少可以忽略不计）的话，建议直接使用配置库的方案 https://www.yuque.com/kenshin/simpread/any457 有三种，你使用 [离线 HTML](https://www.yuque.com/kenshin/simpread/fiyku3) 版就行。

**Comment by shitwall11** [comment]
我也发现了，我的设置没有问题，可能是操作的那个页面有点复杂，所以，导出的时候有些问题，换成其他的网页，随意剪了一段文字，就成功导出了选取的文字…

**Comment by Kenshin** [comment]
安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，然后再测试下出问题的网页

**Comment by shitwall11** [comment]
嗯，我本意不是将所有加入稍后读的页面都自动化导出，只是想在选取部分区域时才导出，刚才看到你发的剪藏时，觉得可能这不是一个很好的流程，应该把它加入稍后读，同时，标注需要的部分，这样，是不是给以后的其他知识管理工具，更好的搭配呢…
嗯，这个插件我试试先~
> 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，然后再测试下出问题的网页

**Comment by shitwall11** [comment]
嗯，thank you ~
> [tMGXrU1v0U](https://simpread.ksria.cn/plugins/details/tMGXrU1v0U) 这个插件，然后再测试下出问题的网页
插件安装上了，但是，还是不行，最后，在稍后读页面试着手动导出全文，也是不成功，可能还是得用那个剪藏库的支持才行~

**Comment by shitwall11** [comment]
嗯，thank you ~
> 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件，然后再测试下出问题的网页

插件安装上了，但是，还是不行，最后，在稍后读页面试着手动导出全文，也是不成功，可能还是得用那个剪藏库的支持才行~

**Comment by Kenshin** [comment]
怀疑是没有安装上，如果成功安装的话，打开 https://sspai.com/post/67074 应该是下图所示

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/81074/227187967-8247ea6d-ef3f-42ca-8d91-5703e3a24274.png">

如果不是的话，使用 https://www.yuque.com/kenshin/simpread/fcw60u 这个方式安装。

**Comment by shitwall11** [comment]
![image](https://user-images.githubusercontent.com/39293756/227188935-9e212b36-cde7-4e6f-b305-76e3926e11dd.png)
安装插件的问题，之前就遇到过了，后来是通过安装插件管理器安装的，最后看了下配置文件，今天是直接把插件代码写到配置文件的，plugin和pluginstore，都加了，只是插件的禁用，不会配，换新浏览器的话，禁用的插件又开启了~
不知道要怎么收集信息才能帮助，发现是哪里的问题…

**Comment by shitwall11** [comment]
哦~
前面遇到的问题还在，F12一下，有错误以为是图片加载不成功的问题，然后开了下飞机，成功加载图片，又试了一下，还是不行~

> 插件安装上了，但是，还是不行，最后，在稍后读页面试着手动导出全文，也是不成功，可能还是得用那个剪藏库的支持才行~

**Comment by shitwall11** [comment]
哦，下面的这个链接算是测试页面吧~
> https://ankiweb.net/shared/info/1807206748

**Comment by Kenshin** [comment]
如果其他页面没问题的话，先忽略它吧。🤣

我明天测试下你说的这个页面。

**Comment by shitwall11** [comment]
好的，thank you for your chat~~~

**Comment by Kenshin** [comment]
小事情。

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
谢谢 😄
