### ISSUE TITLE
添加了插件但是插件的选项没有出现在稍后读的动作里面

### ISSUE THREAD

**Issue by Diplproveably** [Kenshin/simpread#5362]
### 描述这个错误

![image](https://user-images.githubusercontent.com/111405888/227078769-6012f3f1-9cfd-4ef2-b3b8-8e67daeeabc3.png)
可以看到确实安装了导入到notion增强
![image](https://user-images.githubusercontent.com/111405888/227078792-51764074-15bf-40ce-bc32-671dc4aa22f5.png)
如图，安装了导入到notion增强，但是并没有任何关于notion增强的选项可以点

### 复现步骤

安装简悦
安装倒入到notion
安装导入到notion增强

### 操作系统

Windows

### 浏览器

版本 111.0.1661.44 (正式版本) (64 位)

### 发生问题的网址

实际上任何网站都看不到导出到notion增强的选项。https://www.zhihu.com/question/583144286/answer/2942852731

**Comment by Kenshin** [comment]
嗨，如果使用了同步助手的话，解决方案看这里 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
