### ISSUE TITLE
图床转换，完事，自动复制到剪贴板，失效

### ISSUE THREAD

**Issue by qbmiller** [Kenshin/simpread#5363]
### 描述这个错误

图床转换，转换完毕，有提示 已复制到剪贴板。
但是去粘贴，没有内容
手动去选择复制到剪贴板，就ok，图片链接也是已转换完的。

### 复现步骤

1.  按键aa 进入阅读模式
2. pp开始转换 
3. 提示
![image](https://user-images.githubusercontent.com/7335567/227095819-0c2eb7e1-1070-4dc0-940e-1da4e47cb474.png)
4. 去粘贴，内容不对. 手动去选择
5. 
![image](https://user-images.githubusercontent.com/7335567/227095963-ce8a2520-57f9-4006-bf6e-11b022b4c458.png)
就会OK ，图片链接也是OK的。

### 其他相关说明

有没可能是 picgo 什么配置等造成
本地软件 干预？

### 操作系统

macos

### 浏览器

chrome

### 发生问题的网址

http://zrrd.net.cn/1852.html

**Comment by qbmiller** [comment]
> 1. **隐身模式下仅使用简悦的方式**
> 2. 其它页面 e.g.  https://sspai.com/post/69972 是否好使？还是说仅这个页面有问题？

所有页面都有问题。  
隐身模式 竟然好使... 什么情况😂

**Comment by Kenshin** [comment]
> 隐身模式 竟然好使... 什么情况😂

被其它扩展干扰了，用二分法排除你的扩展。

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
