### ISSUE TITLE
obsidian新建仓库经过配置可以同步，但是和我原来的仓库合并后就无法同步了

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5366]
<sup>Originally posted by **lily8186** March 23, 2023</sup>
obsidian新建仓库经过配置可以同步，但是和我原来的仓库合并后就无法同步了，检查了各项设置都找不到问题，救救孩子吧</div>

**Comment by Kenshin** [comment]
@lily8186

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

你总要把相关的功能截图给我，才能判断 😂

PS：配置库主要留意各种路径就行了，没有任何多余的其它的东西了...

**Comment by lily8186** [comment]
没想到这么快就回复我了，非常感谢，相关配置截图上传了，不知道您那能看到吗，还需要什么吗
![sync](https://user-images.githubusercontent.com/76209421/227122986-3f2f7e35-3e30-4215-94d9-4bb42efb600c.png)
![ob](https://user-images.githubusercontent.com/76209421/227123026-8895ed40-8270-4301-aeeb-4ed8626f0da3.png)
![坚果云](https://user-images.githubusercontent.com/76209421/227123069-4bc121ea-4515-46eb-9278-02915963a4bf.png)
![同步助手](https://user-images.githubusercontent.com/76209421/227123096-443dbfb3-6e97-44f5-a1f2-a6e5a907afa9.png)

**Comment by Kenshin** [comment]
上面的截图没有任何一个有用信息 😂 我需要你...

1. 导入到 Obsidain 在简悦有好几种方案，你使用了哪种？（截图给我）

2. 你是通过什么方式导入到 Obsidian（我需要操作步骤）

3. 导入到 Obsidain 的插件的设置给我（需要截图）

一般来说，无法导入都是由各种路径设置造成的，所以凡是跟路径有关系的功能都可以截图给我。
