### ISSUE TITLE
支持思源笔记导入

### ISSUE THREAD

**Issue by bighaidao** [Kenshin/simpread#5369]
### 请描述你的建议或任何内容

希望能支持思源笔记导入。  这个功能提了很久了，作者还没搞。所以想自己来实现一下，但是无奈 js 没写过。 

偶然间看到插件中心有导入到 其他笔记的功能。 

所以请问下作者可以分享一个导入其他笔记的功能代码吗？  我仿造其代码试试是否可以导入思源笔记吧？

感谢感谢！ 实在是等的太久了

**Comment by Kenshin** [comment]
原计划是近期，但因为 OpenAI 的功能所以优先级降低了些。

别急 😂 除了即将要发布的功能外，这个优先级是最好的。

**Comment by bighaidao** [comment]
> 原计划是近期，但因为 OpenAI 的功能所以优先级降低了些。
> 
> 别急 😂 除了即将要发布的功能外，这个优先级是最好的。

好的 期待期待

**Comment by Yuminis98** [comment]
附议，
另外说一句，思源笔记现在的颜值是真的比以前好看太多了，完全不逊色obsidian
![image](https://user-images.githubusercontent.com/117956441/227748295-81117308-e779-4485-8ad6-b3e125988408.png)

**Comment by bighaidao** [comment]
> 原计划是近期，但因为 OpenAI 的功能所以优先级降低了些。
> 
> 别急 😂 除了即将要发布的功能外，这个优先级是最好的。

另外说一句，我的思源是部署在 nas 的 docker 上。 所以作者麻烦考虑下定制化的 ip 接口这些参数。 万分感谢

**Comment by Kenshin** [comment]
> 另外说一句，我的思源是部署在 nas 的 docker 上。 所以作者麻烦考虑下定制化的 ip 接口这些参数

嗨，可以看下 [这个连接](https://github.com/Kenshin/simpread/discussions/categories/%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B?discussions_q=is%3Aopen+category%3A%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B+label%3A%22self+built%22) 应该可以变相解决你的问题。

**Comment by Kenshin** [comment]
嗨，各位~

久等了，预计周末在这里发测试版。

我会把思源相关的功能都整理到 https://github.com/Kenshin/simpread/issues/5555 同时，有一些关于思源笔记功能的需求调研，要是有可能的话，请 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1563812818 并回复下你们的使用方式。

**Comment by Kenshin** [comment]
嗨，各位。

导入到思源笔记的插件已经可以内测了，如何使用以及讨论请前往 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566016251

**Comment by Kenshin** [comment]
哈，[导入到思源笔记 1.0.0 版发布了](https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566729722)~

我关闭这个 issue 了，如果 Docker 版有什么问题的话，可以在这个 Issues 上继续讨论。

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
