### ISSUE TITLE
建议对阅读助手增加内容过滤功能

### ISSUE THREAD

**Issue by QQ804218** [Kenshin/simpread#5371]
### 请描述你的建议或任何内容

在看文章或小说时,有些东西是不需要的,希望可以增加内容过滤功能来屏蔽定义的内容.让阅读起来更清爽

**Comment by QQ804218** [comment]
屏蔽文章中的部分文字或图片

**Comment by Kenshin** [comment]
可以使用 https://github.com/Kenshin/simpread/discussions/1554

**Comment by Kenshin** [comment]
同时也可以使用站点适配规则。

**Comment by Kenshin** [comment]
嗨

[关键词高亮与屏蔽](https://github.com/Kenshin/simpread/discussions/4416) 升级到 2.0.0，增加了**屏蔽关键词**的功能。

2.0.0 版功能
---

- `Add` [关键词屏蔽](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10037795)

- `Add` 当进入阅读模式后是否自动屏蔽关键词

- `Add` 支持 [快速添加高亮或屏蔽](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10041840)

- `Add` 调整 [高亮（或屏蔽）是触发时间](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10041752)

- `Optimize` 选项卡界面更符合 **简悦插件 2.0** 规范

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/iuIlA8bU5S) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 关联

https://github.com/Kenshin/simpread/issues/4417

***

我关闭这个 Issues 了，有任何问题随时讨论~
