### ISSUE TITLE
关于提取网页标题的问题

### ISSUE THREAD

**Issue by baresibest** [Kenshin/simpread#5379]
### 请描述你的建议或任何内容

对于网页标题的问题提问如下：
如何实现将<title>的字段和网页中的某一字段合并为标题？我这里好像无效
![1679745093300](https://user-images.githubusercontent.com/3355824/227715838-9c5883f9-230e-41f2-a7f9-bf8efefe85bc.png)

**Comment by Kenshin** [comment]
emmm 只能用 JS 实现。

请问这么做的目的是？是需要适配某些特定的网页吗？

如果你会 JS 的话，可以给你 Demo，但我目前在出差，只能下周二给你了。

**Comment by baresibest** [comment]
是的，是想保存一些政策文件，然后导入obsidian或者logseq。因为网页标题里没有文号，就不太直观。

**Comment by Kenshin** [comment]
okay 下周二给你

**Comment by baresibest** [comment]
谢谢你呀。

**Comment by Kenshin** [comment]
忘记说了，需要提供 URL 给我 😂

**Comment by bighaidao** [comment]
hi， @Kenshin  也有类似的需求。 想在标题 里加一些自定义的信息，比如来自知乎、微信 等等。谢谢

**Comment by baresibest** [comment]
暂时不用了，自己试了一下用python解析了网页，基本实现了自己的要求。

**Comment by Kenshin** [comment]
@bighaidao 

我忘了...上周在出差 😂
