### ISSUE TITLE
阅读模式代码的行号一个数一行

### ISSUE THREAD

**Issue by kitmanzheng** [Kenshin/simpread#538]
https://blog.didiyun.com/index.php/2019/02/27/etcd-raft/
![image](https://user-images.githubusercontent.com/29112075/60719484-6ad92700-9f5a-11e9-81e8-3be9b4c6e709.png)

**Comment by Kenshin** [comment]
看看选项页 → 右下角的帮助，或者 Github issues 的置顶，你会找到解决方案。

**Comment by kitmanzheng** [comment]
![image](https://user-images.githubusercontent.com/29112075/60720981-07052d00-9f5f-11e9-8232-b0d119578b1b.png)
chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#plugins?install=klGUASLasg
安装插件，100%失败，使用chrome72正式版

**Comment by Kenshin** [comment]
我刚刚测试了这个插件，并没有发生安装失败的情况。
你是什么版本的简悦？

另外，代码阅读有问题的这个问题暂时用这个插件也无法解决。

原因：这个页面用了**并不常用的代码高亮/显示** 逻辑，所以在阅读模式失败。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

此问题已经被解决了

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
