### ISSUE TITLE
请问进入稍后读以后如何默认显示阅读模式？

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5380]
### 请描述你的建议或任何内容

因为我平常标注使用的比较少，都是直接看，笔记则通过quickadd记录在思源笔记。

所以我每次进入稍后读，点击文章，第一眼看到的永远是这个界面
![image](https://user-images.githubusercontent.com/37429029/227719883-b7ddfe1b-89e6-4440-8e03-2ed540c7201e.png)

### 补充说明

如果文章没有任何标注的话，希望可以默认显示阅读模式，而不是标注模式。
如果文章有标注，默认进入标注模式

**Comment by Kenshin** [comment]
稍后读页面左下角调整。

**Comment by AugustTuan** [comment]
> 稍后读页面左下角调整。

看到了，谢谢。好多可以设置的地方🤣

**Comment by Kenshin** [comment]
哈哈，基本上 90% 以上的功能都可以设置。
