### ISSUE TITLE
如果稍后读界面已经打开就不重复开启

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5382]
### 请描述你的建议或任何内容

当我选择使用快捷键打开一个稍后读界面以后。
我后面再次使用快捷键不会激活原来打开的窗口，而是反复打开新窗口
![image](https://user-images.githubusercontent.com/37429029/227721670-3390fe08-651e-4bb2-800c-8a0966c3c602.png)

**Comment by Kenshin** [comment]
这个不是简悦的问题，因为简悦没法控制这些～

PS：你用了 Arc 浏览器吗？

**Comment by Yuminis98** [comment]
> 这个不是简悦的问题，因为简悦没法控制这些～
> 
> PS：你用了 Arc 浏览器吗？
没有，我就是chrome🤣

**Comment by Kenshin** [comment]
看截图以为是 Arc 呢。 🤣
