### ISSUE TITLE
关闭浏览器以后也可以打开稍后读

### ISSUE THREAD

**Issue by Yuminis98** [Kenshin/simpread#5384]
### 请描述你的建议或任何内容

我很喜欢简悦稍后读的这个功能， 把原本的稍后读网页变成了一个类似应用程序的界面。沉浸感要好得多

![image](https://user-images.githubusercontent.com/117956441/227722732-fd164f71-5cc0-4a07-8f0b-6fa732549724.png)

但是一旦我关掉edge浏览器以后，我就无法打开稍后读了。 
即使我把快捷键设置为全局，并且打开edge扩展后台运行
![image](https://user-images.githubusercontent.com/117956441/227722875-6033d791-0a3a-4222-8e20-30b839f75842.png)
![image](https://user-images.githubusercontent.com/117956441/227722936-25d56f2f-e805-4385-be84-d429991713d7.png)

请问一下开发者，有什么方式，可以让我在关掉edge以后，仍然可以用快捷键进入稍后读界面吗？

**Comment by Yuminis98** [comment]
要是可以在浏览器外面随时随地打开稍后读程序。那真的太方便了

**Comment by Kenshin** [comment]
可以的 [教程](https://simpread.pro/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%88%9b%e5%bb%ba%e5%bf%ab%e6%8d%b7%e6%96%b9%e5%bc%8f)
