### ISSUE TITLE
图片一直无法加载出来

### ISSUE THREAD

**Issue by Yuminis98** [Kenshin/simpread#5385]
### 请描述你的建议或任何内容

如图所示，收藏了一篇语雀的文章，但是图片无论如何都没有办法加载出来。https://www.yuque.com/winnie_926/shayu/vlnkop
转了1分钟了
![image](https://user-images.githubusercontent.com/117956441/227723339-a1121694-0e78-4c7e-91e9-f3ed65626135.png)

**Comment by Kenshin** [comment]
某些页面因为是动态加载的，所以无法在稍后读中查看，但你可以使用 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 方式解决，但需要使用同步助手。
