### ISSUE TITLE
能否支持onedrive授权

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5387]
### 请描述你的建议或任何内容

我看选项里面支持授权坚果云，dropbox，google drive，甚至有onenote。 但是就是没有找到onedrive😭
onedrive是我的主力云盘😭

**Comment by AugustTuan** [comment]
开通邮件的每日回顾，也只能用坚果云和dropbox吗？(╯°□°）╯︵ ┻━┻
![image](https://user-images.githubusercontent.com/37429029/227751880-40f4f2b1-b5e5-4074-9e17-e229754d4499.png)

**Comment by Kenshin** [comment]
准确的说只有坚果云， Dropbox 也不行。🤣

会考虑 onedrive 的，优先级不是很高。

你可以同时使用坚果云与 onedrive 
并不冲突。

**Comment by AugustTuan** [comment]
> 准确的说只有坚果云， Dropbox 也不行。🤣
> 
> 会考虑 onedrive 的，优先级不是很高。
> 
> 你可以同时使用坚果云与 onedrive 并不冲突。

我因为简悦，还专门去下载了坚果云，坚果云太贵了，一年199.😭

onedrive，电报合租群里面，48快合租，1T内存，还送全套的office365，不香吗？

**Comment by Kenshin** [comment]
坚果云免费版就够了，简悦很多用户都是 onedrive  +  坚果云方案。

将坚果云的同步文件夹放到 onedrive 里面。

另外，如果不使用 API 功能的话，什么网盘都行。

**Comment by AugustTuan** [comment]
谢谢，我下了坚果云，专门用来做简悦的同步，有1G的免费空间。
请问这个定期发送邮件，只能设置为7：10份吗？ 比如我想设置成每天早上9：00，可行吗？
![image](https://user-images.githubusercontent.com/37429029/227756219-e5d8c299-5ea5-4dfa-80c4-513158f6bfe9.png)

**Comment by AugustTuan** [comment]
> 坚果云免费版就够了，简悦很多用户都是 onedrive + 坚果云方案。
> 
> 将坚果云的同步文件夹放到 onedrive 里面。
> 
> 另外，如果不使用 API 功能的话，什么网盘都行。

话说为什么坚果云的空间这么小，即使付费了也就几十G的空间（其他的网盘都是几T

**Comment by Kenshin** [comment]
坚果云主要是做小文件传输的，很稳定，免费版之少一个月的历史记录。

需求和受众跟 onedrive 不一样。
