### ISSUE TITLE
配置自动化失败

### ISSUE THREAD

**Issue by AugustTuan** [Kenshin/simpread#5388]
### 请描述你的建议或任何内容

我按照教程[一站式知识库配置](https://www.yuque.com/kenshin/simpread/wkswh7)里面一步一步地配置了自动化流程，但是最后完全没有效果😭

导出配置
![Snipaste_2023-03-26_09-45-08](https://user-images.githubusercontent.com/37429029/227750912-0132918c-7938-4f84-8d59-7b1bcec1d5e8.png)
![Snipaste_2023-03-26_09-44-51](https://user-images.githubusercontent.com/37429029/227750951-fb52084d-1958-4dce-9009-33c6774ed7c4.png)

定制导出
![image](https://user-images.githubusercontent.com/37429029/227751068-62c2d070-1381-4a9c-8ccc-dfe5b6822ae9.png)

稍后读配置
![Snipaste_2023-03-26_09-48-21](https://user-images.githubusercontent.com/37429029/227750927-2df1b306-4280-4ca2-8d99-114164990257.png)
![image](https://user-images.githubusercontent.com/37429029/227751012-0bff7255-d134-46ca-8cac-a6352fc019d4.png)

标注配置
![Snipaste_2023-03-26_09-48-53](https://user-images.githubusercontent.com/37429029/227750933-1f8f0337-e2c1-46f8-9d6b-9027a87539a9.png)
自动化配置
![Snipaste_2023-03-26_09-49-13](https://user-images.githubusercontent.com/37429029/227750941-aee97351-d3e7-4f98-a98b-0f107ea9b31c.png)

**Comment by AugustTuan** [comment]
1.我加入稍后读以后，什么都没有发生😭😭😭😭
![image](https://user-images.githubusercontent.com/37429029/227751085-3202754c-5389-4158-8d45-89281bb440ec.png)

**Comment by Kenshin** [comment]
自动化的前提：

1. 进入阅读模式
2. 使用快捷键 d d 或者右键菜单加入

**Comment by AugustTuan** [comment]
> 自动化的前提：
> 
> 1. 进入阅读模式
> 2. 使用快捷键 d d 或者右键菜单加入

谢谢，基本成功了，就是不知道为什么单独就是github无法保存
![image](https://user-images.githubusercontent.com/37429029/227755679-53342610-8a03-43b7-ac6a-ab63642798b0.png)

![image](https://user-images.githubusercontent.com/37429029/227755703-41bd9167-8f0a-4e1c-ae99-e8383f869bdf.png)

**Comment by Kenshin** [comment]
估计需要安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by AugustTuan** [comment]
> 估计需要安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

谢谢，搞定了。终于感受到了自动化的流程是什么样子的😭

**Comment by Kenshin** [comment]
哈哈，搞定就好。

**Comment by Kenshin** [comment]
前几天出差（以此名义休假...），今天回来后整理了下 issues 们，竟然发现你在我出差期间提了 nnnnnnn 条 Issues 😂

***

不给个 五星 + 好评都对不起我这休息时间 😏 

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by AugustTuan** [comment]
> 前几天出差（以此名义休假...），今天回来后整理了下 issues 们，竟然发现你在我出差期间提了 nnnnnnn 条 Issues 😂
> 
> 不给个 五星 + 好评都对不起我这休息时间 😏
> 
> 进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 通过下图
> 
> ![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

五星好评了
![image](https://user-images.githubusercontent.com/37429029/228126604-344afbbd-0541-4205-a958-84c4b4d617bf.png)

**Comment by Kenshin** [comment]
👍  👍  👍 

等我忙完了之前说的功能，就开始思源的事情。

PS：之前有思源用户说可以将微信的内容转发给思源？你知道这个事情吗？如何做到的，可以简单说下。（或提示）

**Comment by AugustTuan** [comment]
思源的云端收集箱吗？
就是你关注他的微信，然后微信发信息 
![image](https://user-images.githubusercontent.com/37429029/228131058-9f6c455a-4f6d-454b-82ad-d8235c77b4f0.png)


然后思源这边就收到了
![image](https://user-images.githubusercontent.com/37429029/228131005-f0756c5a-f425-4582-8795-ab5dd890b83a.png)

**Comment by AugustTuan** [comment]
如果你发网址的话，就会解析成文章发送到思源

![image](https://user-images.githubusercontent.com/37429029/228131273-f2cbb15e-02da-4b74-8b75-aceaccdf148f.png)

**Comment by Kenshin** [comment]
okay 明白了~
