### ISSUE TITLE
公众号和语雀显示错误

### ISSUE THREAD

**Issue by mining-id** [Kenshin/simpread#5391]
### 需要适配的新站

这两个页面在阅读模式下显示错误（大量内容没有显示），反复刷新重试都不行
https://mp.weixin.qq.com/s/rU7x3F3tAWo7v2HwEC3Ulw
<img width="931" alt="image" src="https://user-images.githubusercontent.com/94845005/227789647-e67f339a-842e-46b4-9c2a-7ff167de2d16.png">

https://www.yuque.com/3dinternet/gpt/ts1
<img width="875" alt="image" src="https://user-images.githubusercontent.com/94845005/227789748-0edd3a45-7237-498e-b763-ab7877226fd9.png">

**Comment by Kenshin** [comment]
公众号我明天确认下。
语雀的话，看这里 https://github.com/Kenshin/simpread/discussions/4380

**Comment by Kenshin** [comment]
公众号的那篇，可以下图的方式解决 

<img width="811" alt="image" src="https://user-images.githubusercontent.com/81074/228118963-be1994f2-c7a6-4262-8c35-7253db41ee5c.png">
