### ISSUE TITLE
新站适配：微博正文

### ISSUE THREAD

**Issue by mining-id** [Kenshin/simpread#5392]
### 需要适配的新站

https://weibo.com/1644684112/4883500941182314

![image](https://user-images.githubusercontent.com/94845005/227791201-082b5f15-7f1e-4136-b7a6-0541b6ee7bf4.png)

**Comment by Kenshin** [comment]
前几天出差，刚有时间处理它。

我可以适配这个页面，但好久没玩微博了... 这个页面 https://weibo.com/1644684112/4883500941182314 属于什么？或者说我如何能找到跟它相似的？

😂

**Comment by Kenshin** [comment]
okay 适配后会通知你~

**Comment by Kenshin** [comment]
嗨，这个站已被适配，请通过 https://simpread.ksria.cn/sites/details/NWcdj6FMDU 安装。

同时因为这个站是动态加载的，所以需要将 `utgd.net` 加入到延迟加载列表，如何使用 https://github.com/Kenshin/simpread/discussions/5414

PS：如果在使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装此站点。

**Comment by mining-id** [comment]
@Kenshin 
哇，效率太高了！ 
可以正常显示了！
感谢大牛！！
