### ISSUE TITLE
Notion页面无法滚动

### ISSUE THREAD

**Issue by mining-id** [Kenshin/simpread#5393]
### 需要适配的新站

https://orangeblog.notion.site/GPT-4-8fc50010291d47efb92cbbd668c8c893

阅读模式后，页面无法滚动。
![image](https://user-images.githubusercontent.com/94845005/227795789-92343336-4551-4298-9675-1e001068d830.png)

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/2106
