### ISSUE TITLE
定制导出和markdown模板辅助增强遇到的一些问题

### ISSUE THREAD

**Issue by Solitario119** [Kenshin/simpread#5394]
### 描述这个错误

我在定制导出和markdown模板辅助增强中使用了一段相同的语法，但导出生成的markdown在logseq中却不一致，主要体现在下图红框标记部分。
图1：定制导出模板
![image](https://user-images.githubusercontent.com/42676347/227821193-2208728e-b426-48c3-b4c6-f8b85e60d49d.png)
图2：md辅助增强模板
![image](https://user-images.githubusercontent.com/42676347/227821497-1db05e49-7e70-4cba-9331-a69aad0c9b0d.png)

### 复现步骤

按上述模板，自动导出的文件是这样的：
1. 如果在浏览器阅读模式下，是按照md模板辅助增强的格式导出，没有问题，也是我想要的格式，在logseq中示例如下，能够正确切换为对应日期
![image](https://user-images.githubusercontent.com/42676347/227821955-db39a8e0-7e42-4cad-8d2c-5a19da8eecef.png)

2. 如果添加到稍后读，在稍后读内进行标记或是在logseq中利用simpread插件进行标记，导出的md是按照定制导出的格式，此时日期格式就无法正确转换了
![image_19](https://user-images.githubusercontent.com/42676347/227822449-fe36a1d5-4336-48fd-8d52-211520eaa867.png)

### 其他相关说明

我想要知道应该如何修改定制导出的模板，才能够实现在稍后读或logseq插件中标记后得到同样的导出效果，希望能得到准确答复，感谢！

### 操作系统

Windows

### 浏览器

Edge

### 发生问题的网址

https://www.jiqizhixin.com/

**Comment by Solitario119** [comment]
嗨，我目前解决了在logseq中利用插件标记导出md的问题，但是在稍后读中进行标注、导出后，格式依然存在问题，且我还没有找到相关设置，希望能得到准确答复，谢谢！

**Comment by Kenshin** [comment]
前几天出差，因为你的 Issues 比较复杂就没有马上回复。😂

***

> 我在定制导出和markdown模板辅助增强中使用了一段相同的语法，但导出生成的markdown在logseq中却不一致

这两个 Markdown 语法规则有些细微的差别，主要是日期定制上（也就是你遇到的问题），而且我建议使用 2.0 的语法规则。

> 如果添加到稍后读，在稍后读内进行标记或是在logseq中利用simpread插件进行标记，导出的md是按照定制导出的格式，此时日期格式就无法正确转换了

在稍后读中，你可以使用 [稍后读 · 极速版](https://github.com/Kenshin/simpread/discussions/3864) 在浏览器或者 Logseq 右侧直接标注，并使用 Markdown 模板 2.0 的语法规则。

这样就不用在扩展端的稍后读中使用 1.0 的语法规则了。

**Comment by Solitario119** [comment]
在稍后读或logseq右侧直接标注，就不能自动导出标注内容md了

**Comment by Kenshin** [comment]
> 在稍后读或logseq右侧直接标注，就不能自动导出标注内容md了

可以的，只要配置了就行，类似 https://www.yuque.com/kenshin/simpread/gbere7 的方案。
