### ISSUE TITLE
导入到 Notion---仅能获取第一个Notion Page

### ISSUE THREAD

**Issue by Amaake3321** [Kenshin/simpread#5395]
### 描述这个错误

1、尝试了 [https://github.com/Kenshin/simpread/discussions/1773](#1773)的所有方案，包括但不限于重装简悦插件、重新登录notion，更换电脑，在notion中收藏多个页面。
2、情况和问题汇总中的不一样，仅获取了第一个Notion Page但是点击导入提示"请先授权并设置保存的 Page 后才能使用。"\见下图
![image](https://user-images.githubusercontent.com/50546208/227824158-2c2f779b-4386-420c-b48f-585c7330a6e3.png)

### 复现步骤

环境：
/仅安装“导入到 Notion”插件/安装uBlock Origin 1.48.0广告拦截插件开启基础功能（核查无拦截第三方授权头部功能）/
具体复现步骤：(新电脑，纯净安装)
1、登录Notion，新建2-3个测试页面，均点上收藏按钮。
![image](https://user-images.githubusercontent.com/50546208/227824845-00414e91-ae0a-4c1b-bf72-613b5cccfa98.png)
2、安装简悦浏览器插件，不做任何配置，安装“导入到 Notion”插件“附加组件，不做任何配置。
3、打开任意网址，本次使用https://www.zhihu.com/question/23866990/answer/128912950，进入阅读模式，点击导入到 Notion，选择”database“页面，点击保存。
![image](https://user-images.githubusercontent.com/50546208/227825167-99d4b545-479c-4651-a223-77e003052c5f.png)
4、点击导入，发现提示"请先授权并设置保存的 Page 后才能使用"
![image](https://user-images.githubusercontent.com/50546208/227825255-9e0339d9-6449-4e13-81e5-a3607a089dd3.png)

### 操作系统

Window11 

### 浏览器

chrome v110

### 发生问题的网址

任意网址均出现此问题 https://www.zhihu.com/question/23866990/answer/128912950

**Comment by Amaake3321** [comment]
![image](https://user-images.githubusercontent.com/50546208/227825829-2aba86ef-d5f6-45ad-9817-76a45c36e246.png)
似乎请求包没抓到

**Comment by Kenshin** [comment]
解决方案 https://www.yuque.com/kenshin/simpread/wwk65u
