### ISSUE TITLE
如何设置自动化导出以MD 2.0 模板形式导出？

### ISSUE THREAD

**Issue by Solitario119** [Kenshin/simpread#5397]
### 请描述你的建议或任何内容

如何设置自动化导出以MD 2.0 模板形式导出？

**Comment by Kenshin** [comment]
1. 可以看具体例子 e.g. https://www.yuque.com/kenshin/simpread/fr8zo5

2. [Markdown 辅助增强模板的说明文档](https://github.com/Kenshin/simpread/discussions/3725) 虽然没有直接的例子，但写的很全面了，所以也可以解决你的疑问。
