### ISSUE TITLE
关于离线保存的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5398]
https://xz.aliyun.com/t/12282 先知社区的文章 离线保存图片保存失败 这边保存完了 那边图像才出来

_Originally posted by @z1n in https://github.com/Kenshin/simpread/discussions/2244#discussioncomment-5448100_

**Comment by Kenshin** [comment]
@z1n 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

稍晚看下这个问题。

**Comment by Kenshin** [comment]
我看了下这个页面确实不允许使用离线 HTML 的方案。

一般来说，简悦不会破坏某些页面规则（比如：xxx 网站不允许使用离线下载，简悦就不会使用某些方式来实现离线下载。

PS：你可以试试 https://github.com/Kenshin/simpread/discussions/4041 这个方式，如果仍不行的话，就没办法了。

PPS：无法下载并不是技术上的问题。

**Comment by z1n** [comment]
谢谢您的快速回复！  
我研究了一下 这个是阿里云块存储的防盗链 
需要加上refer Header(   -H 'referer: https://xz.aliyun.com/'
)  
这有点游走在边缘的感觉。
有没有方案直接保存浏览器加载好的图片、缓存？

md + assets 格式  方案也不得行 
问题是一样的 图片防盗链

![image](https://user-images.githubusercontent.com/15521536/228179027-f1e215d5-d3af-4167-9743-e40c40b6de36.png)

**Comment by Kenshin** [comment]
> 这有点游走在边缘的感觉。

是的 😂

从程序角度说，当然没问题。

但一般来说这么做就破坏了原网站的「规则」，类似某些可以看付费墙的网页是一样的道理，这是简悦不允许做的事情。

**Comment by z1n** [comment]
您好！有没有简越本地build教程呀 😂 想学习一下~

**Comment by Kenshin** [comment]
@z1n 

教程看 https://www.yuque.com/kenshin/simpread 也可以直接使用 [配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 方案。
