### ISSUE TITLE
＃豆瓣阅读＃阅读模式解析后无法正常显示

### ISSUE THREAD

**Issue by shenjiazhuo** [Kenshin/simpread#54]
Mac平台，chrome浏览器中，在＃豆瓣阅读＃浏览电子书时，＃简阅＃阅读模式解析后无法正常显示

**Comment by Kenshin** [comment]
之前有用户提出适配 `豆瓣阅读`，但由于豆瓣阅读的 html 结构比较另类，暂时无法适配，所有打开豆瓣阅读并不能进入阅读模式。

比如打开 https://read.douban.com/reader/column/1696110/chapter/36460494/ 是无法使用阅读模式的。

所以，我不清楚你打开了哪个 url 而进入阅读模式的，请告知。

**Comment by Kenshin** [comment]
Hi，我将关闭此 issues，如需要重新开启它。 😊
