### ISSUE TITLE
导出图片模式，无法和阅读模式下一致

### ISSUE THREAD

**Issue by yi-Xu-0100** [Kenshin/simpread#540]
网址：https://www.zhihu.com/question/19738269

阅读模式下截图效果： 
![image](https://user-images.githubusercontent.com/25523606/60765311-3042cc00-a0cb-11e9-97f6-53293b9a1584.png)

导出图片后，截取相同部分效果：
![image](https://user-images.githubusercontent.com/25523606/60765314-46508c80-a0cb-11e9-88e5-54e3eafef6af.png)

**Comment by Kenshin** [comment]
下图中多出了很多 html 代码，这应该是个 Bug （我已重现

另外，关于你说的模糊，我还真没觉得...

**Comment by yi-Xu-0100** [comment]
模糊？？？

我没提啊，只是觉得导出图片多了一段，不一样了，格式上有点问题。

？？？我看了我 github 和 telegram 的描述，应该没有提到模糊的问题，图片看起来很清楚的，谢谢回复，等待更新~麻烦了

**Comment by Kenshin** [comment]
呵呵，抱歉。
模糊的问题是另外一个 issues ... 不用理会。

**Comment by yi-Xu-0100** [comment]
新的版本修复了，我就先关闭了。

**Comment by Kenshin** [comment]
谢谢，近期应该关闭一些 Issues 但一直有些忙，耽搁了，过几天会集中清理 2.0 之前的全部 Issues
