### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by charles-jason** [Kenshin/simpread#5401]
### 描述这个错误

初次使用这个插件，发大部分打开Adblock Plus来去广告的网站，都无法使用阅读模式，会是一片全白。github无影响
如图：
![image](https://user-images.githubusercontent.com/40533716/228287424-66ffc228-d54b-4de2-81ca-3cf7bad6d752.png)

### 复现步骤

1. 启用Adblock Plus
2. 更新如下Adblock Plus推荐规则列表
![image](https://user-images.githubusercontent.com/40533716/228287751-6db1a3fb-6f30-4df2-84b5-3c262646663b.png)

3. 打开少数派、知乎、csdn、起点等网站，使用阅读模式

### 操作系统

Windows 10 22H2 x64

### 浏览器

Chrome 111.0.5563.111（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/post/39491

**Comment by Kenshin** [comment]
建议使用 https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm Adblock 当年出过问题（疑似，太久远忘记了 😂
