### ISSUE TITLE
进入阅读模式后，文章内容中所有标题丢失

### ISSUE THREAD

**Issue by richex-cn** [Kenshin/simpread#5402]
### 描述这个错误

进入文章页面后，打开阅读模式，所有标题都丢失了。

原文：

![Snipaste_2023-03-29_11-13-49](https://user-images.githubusercontent.com/25103518/228417371-4e64afdd-0cb4-4970-b118-7673a831b3ce.png)

阅读模式：

![Snipaste_2023-03-29_11-10-20](https://user-images.githubusercontent.com/25103518/228417364-11686341-abc7-4c70-8c61-8df7681ef503.png)

### 复现步骤

1. 打开文章。
2. 进入阅读模式。

### 操作系统

Windows 11

### 浏览器

Chrome 111.0.5563.146 (正式版本) （64 位） (cohort: 111_Win_146_Ramup) 

### 发生问题的网址

https://harttle.land/2016/08/08/vim-search-in-file.html

**Comment by Kenshin** [comment]
嗨

解决方案

<img width="635" alt="image" src="https://user-images.githubusercontent.com/81074/228430355-12c4c085-644a-4071-bb8d-5671fc7bb438.png">

效果如下

<img width="1809" alt="image" src="https://user-images.githubusercontent.com/81074/228430406-ec5dc3c4-40ed-42ee-8bbe-af327cb8c685.png">

**Comment by richex-cn** [comment]
请问这是什么原因造成的，想了解下日后也好留意这类情况避免丢内容 @Kenshin

**Comment by Kenshin** [comment]
这个页面没有适配，自动获取不是很完美造成的。

不过，很少遇到这类页面，一般都能正确识别。（特殊类型的页面除外）
