### ISSUE TITLE
关于内链的疑问

### ISSUE THREAD

**Issue by ky1983114** [Kenshin/simpread#5405]
### 请描述你的建议或任何内容

做为一名非程序员，进入这类地方陌生感很强啊。我是知乎用户「记忆囚徒」，我在知乎上向您咨询了关于共享链接的问题。你回复生成共享链接因为某些原因不再提供。那么我的具体使用问题更改为如何一键生成内部链接。

    

### 补充说明

 比如我在obsidian写东西，引用简悦稍后读里面一篇文章，在我已经配置好内部链接的前提下，我仍需要如下步骤：1、找到并复制内部链接的前面地址，即 http://localhost:7026/reading/  ；2、然后找到需要引用的文章，把自动生成的文章id，添加在内部链接前面地址后面，如 http://localhost:7026/reading/12345 」，并且这个步骤如果不用文章id，而用文章名，还容易出错。

这样的步骤太麻烦了，也没有一键生成内部链接的功能吗？反正是内部链接，没有共享链接的问题吧？~~

**Comment by Kenshin** [comment]
> 反正是内部链接，没有共享链接的问题吧？

是的 😂

> 比如我在obsidian写东西，引用简悦稍后读里面一篇文章

你可以使用 https://github.com/Kenshin/simpread/discussions/3350 提到的 **方案一**（也就是下图所示的内容）

<img width="897" alt="image" src="https://user-images.githubusercontent.com/81074/228515033-7c424215-54a4-45b9-8af8-aebe1c0de170.png">


***

Github Issues 只是一个 QA 系统，不仅针对 Develper 😂 我关闭这个 issues 了，你有任何疑问仍可以随时在这里跟我讨论。

另外，也可以使用 Email 回复，但我建议在 https://github.com/Kenshin/simpread/issues/5405 回复比较好。
