### ISSUE TITLE
导入到Notion提示请稍后再试

### ISSUE THREAD

**Issue by Sox-I** [Kenshin/simpread#5406]
### 描述这个错误

点击保存到notion后会提示稍后再试，控制台报错
已尝试重置配置文件，重新配置后问题仍然存在
![屏幕截图 2023-03-29 210832](https://user-images.githubusercontent.com/26356640/228546416-1413ad8c-2ae6-4155-99c8-8ca731bc2bcb.png)
name中报错信息为
TypeError: name is not a function
at a.get(eval at c(chrome-exrtension://.../bundle/contentsscripts.js:1:1)),<anomymous>:53:11135)
at a.invokeGetter(<anonymous>:3:28)

### 复现步骤

1. 进入阅读模式
2. 加入稍后读
3. 触发导入至notion流程
4. 提示请稍后再试，控制台报错

### 操作系统

windows 10

### 浏览器

Edge 111.0.1661.54 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/617425865

**Comment by Kenshin** [comment]
1. 其他网页有问题吗？e.g. https://sspai.com/post/69972
2. 使用了哪种导入方案？（ Notion）有两种导入方案

**Comment by Sox-I** [comment]
> 1. 其他网页有问题吗？e.g. https://sspai.com/post/69972
> 2. 使用了哪种导入方案？（ Notion）有两种导入方案

1. 其他网页问题也存在
2. 使用动作里的保存到Notion没有问题，但是使用Assistive Touch或者保存到稍后读的自动化流程就会报错

**Comment by Kenshin** [comment]
隐私模式下，仅启用简悦试试。
另外，用 Notion 辅助增强插件了吗？以及你用的是扩展端方案？还是插件导入方案？
