### ISSUE TITLE
无法授权印象笔记，总是失败

### ISSUE THREAD

**Issue by xiejf20** [Kenshin/simpread#541]
您好，感谢开发这么好的插件！！！想反映一下授权印象笔记的问题，非常不稳定，之前Mac上试了大概10次，终于成功了，这次在Windows 10上面，试了20多次，都无法成功，请帮忙看看谢谢。
已经尝试了以下操作：
1：重启电脑
2：清理Chrome缓存
3：关闭其他所有插件
4：登录网页版的印象笔记、Evernote，在线尝试点击授权
以上尝试都失败，总是显示下面的提示，无法跳出授权页面
<img width="348" alt="simpread" src="https://user-images.githubusercontent.com/32642948/60766291-312f2a00-a0da-11e9-9c0c-2752d2adf251.PNG">

**Comment by Kenshin** [comment]
谢谢反馈，但你的问题应该只是个例。

请保证能访问外网，或者按照以下方案试试。

导出在 mac 上面授权成功的配置文件，再导入到 win 的简悦。

需要选择开启 [此功能](http://ksria.com/simpread/docs/#/授权服务?id=授权码)

**Comment by Kenshin** [comment]
我刚刚测试了下授权，并没有发送你说的问题。
还是建议看看 https://github.com/Kenshin/simpread/issues/541#issuecomment-508991942 给出的解决方案。

**Comment by LimnN** [comment]
我也有这个问题，一直跳不出授权页，evernote和印象笔记都不行

**Comment by mobenlu** [comment]
同样问题，望解决

**Comment by Kenshin** [comment]
@mobenlu @LimnN 

抱歉，由于人数增加远超服务器配额，所以月底服务器又「跪」了…

三天后自动恢复。

**Comment by hzzza** [comment]
现在也无法进行授权

**Comment by Kenshin** [comment]
@hzzza 
上条已经解释了

> 抱歉，由于人数增加远超服务器配额，所以月底服务器又「跪」了…
> 三天后自动恢复。

**Comment by Kenshin** [comment]
@mobenlu @LimnN @hzzza

各位，印象笔记的相关功能已恢复。

**Comment by xiejf20** [comment]
> @mobenlu @LimnN @hzzza
> 
> 各位，印象笔记的相关功能已恢复。

已经解决了，今天可以成功绑定了！感谢！！！感谢！！大家赶快趁着月初去绑定吧！！

**Comment by Kenshin** [comment]
@xiejf20 

抱歉，给你造成了一定的困扰，我正在想办法扩容后台的服务。接下来会解决这个问题。

**Comment by Asarua** [comment]
...我的印象笔记账户在绑定的时候老是显示不存在用户名和邮箱是什么情况，可以直接登录的，但是在授权的时候就显示不存在

**Comment by Kenshin** [comment]
@Asarua 

用隐身模式，通过邮箱/密码 的方式看看能否登录印象笔记？

个人建议去印象笔记问问，这已不是简悦覆盖的范畴了。

**Comment by LimnN** [comment]
> ...我的印象笔记账户在绑定的时候老是显示不存在用户名和邮箱是什么情况，可以直接登录的，但是在授权的时候就显示不存在

我猜可能是国内版国际版的问题

**Comment by Asarua** [comment]
~.~，无奈

**Comment by Kenshin** [comment]
@LimnN 

简悦区分并支持 Evernote 与 印象笔记。 不过，记得 Evernote 也有中文版... 但它们不是一个帐号体系。
@Asarua 我还是觉得，你应该确定下是什么问题...

**Comment by AoZhang** [comment]
@Kenshin 两年过去了，问题还没彻底解决吗？我这里依然无法绑定，一直转圈圈：
![image](https://user-images.githubusercontent.com/3005456/129877725-64e9cd48-5f6b-4da2-9d18-e362c8a21546.png)

**Comment by Kenshin** [comment]
@AoZhang 

我也不清楚为什么你会存在这个问题，虽然我早就弃用印象笔记了，但简悦的印象笔记用户群人数也很多，目前没有其他用户反馈这个问题。

还有，已经2年过去了，替代印象笔记的有很多，早走早珍惜！

**Comment by songtengfei95** [comment]
同样问题，印象笔记无法授权，一直提示失败

**Comment by xjushi** [comment]
> 

同样问题，很久了。

**Comment by awayme** [comment]
我也有一样问题。我看了一下 控制台，授权的ui后程序去用post方法访问这个地址：https://simpread.herokuapp.com/evernote/oauth ，而实际这个地址的服务返回503错误

**Comment by awayme** [comment]
我也有一样问题。看了一下 控制台，授权程序用post方法访问这个地址：https://simpread.herokuapp.com/evernote/oauth ，而实际这个地址的服务返回503错误。另外，据我所知heroku在某些时期是被墙的，所以无法授权的人应该又两种可能造成的，一种是网络问题，一种是服务503

**Comment by nickwzy** [comment]
503错误
