### ISSUE TITLE
导出为obsidian显示此功能为实验性功能

### ISSUE THREAD

**Issue by ProudBenzene** [Kenshin/simpread#5411]
### 描述这个错误

导入一篇reddit上的文章到Ob失败，说是实验性功能。

![telegram-cloud-photo-size-5-6134388866052896052-y](https://user-images.githubusercontent.com/93238080/228735484-94f8efbd-0a17-4d08-bb60-bb229c6a20e4.jpg)

### 复现步骤

打开该网页，开启阅读模式，使用快捷键dd即可复现。

### 其他相关说明

已经安装并更新了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 插件，仍然是这个样子。

### 操作系统

macOS

### 浏览器

Arc 0.95.1

### 发生问题的网址

https://www.reddit.com/r/ObsidianMD/comments/124cd8y/my_setup_as_a_researcher_how_to_write_run/

**Comment by Kenshin** [comment]
这不是提示已经保存到 Obsidian 了吗？

<img width="395" alt="image" src="https://user-images.githubusercontent.com/81074/228747107-38377e36-5fc8-4be5-8e25-a2167531a4f3.png">

检查下你的自动化与自动化辅助增强插件。

**Comment by Kenshin** [comment]
> 打开的这个带有immersive插件翻译的阅读模式页面，再按dd，就会出现这个报错。

这个问题是因为你的标题修改了（被中文翻译），但标题含有非法字符造成的。

解决方案：可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 将标题的内容修改（去掉非中英文的字符即可）
