### ISSUE TITLE
高级pdf保存-图片不全

### ISSUE THREAD

**Issue by Kiss-World** [Kenshin/simpread#5412]
### 描述这个错误

https://sspai.com/post/78747 
想把这篇内容保存为pdf，但是图片不完整，调整图片宽度没有效果，修改参数 dpi 也没有效果
![image](https://user-images.githubusercontent.com/44720566/228745806-5c46b933-820b-45db-bf87-936137121257.png)

### 复现步骤

想把这篇内容保存为pdf，但是图片不完整，调整图片宽度没有效果，修改参数 dpi 也没有效果

### 操作系统

win11

### 浏览器

谷歌

### 发生问题的网址

https://sspai.com/post/78747

**Comment by Kenshin** [comment]
1. 请问使用了什么 PDF 方案？无论什么方案，请把相关的设置截图给我。
2. 仅仅只是这个页面有问题？还是其它页面也有问题？

**Comment by shexiaobin** [comment]
我也遇到了这个问题，导出的pdf都没有图片，`
<img width="604" alt="image" src="https://user-images.githubusercontent.com/26622879/229541272-47a43a7b-33a4-48f0-9221-ad0db18e0131.png">
`
导出网址是Confluence搭载的wiki

**Comment by Kenshin** [comment]
@shexiaobin 
需要提供

**Comment by NGNL2017** [comment]
https://sspai.com/post/78747
https://sspai.com/post/71576
mac系统，edge浏览器，同样的使用增强导出功能，图片显示不全。
下面是设置：
<img width="604" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/2f6670ed-9f43-46f7-9548-a0c8e311ec9b">
<img width="612" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/16899403-8229-45b1-ac07-ebc64b4a956c">
<img width="691" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/3de0534c-0181-4909-9f09-e68d2da7a061">

阅读模式：
<img width="1374" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/3058e212-87ff-44af-ad8d-6e1993fc66ea">
导出的pdf：
<img width="1128" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/70aaa04e-92e7-427a-b007-d9e30cf185d3">

**Comment by Kenshin** [comment]
@NGNL2017 

这是图片尺寸设置的问题，第一个截图就有关于图片尺寸的定制。

**Comment by NGNL2017** [comment]
@Kenshin 
这个[帖子](https://github.com/Kenshin/simpread/issues/5124)，还有几个说右边显示不全的issue我也看了下，打印出来和他一样的效果：
<img width="446" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/301f0b49-deae-413a-b5e3-986bdead8fff">


图片宽度参数设置为50没有任何变化，换成基础打印方案显示都是正常的，定位应该是高级打印的问题。
<img width="226" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/bc505c41-61b4-4941-aed3-3e95a368cd1c">
<img width="556" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/82c3ccc4-780f-4a0b-bd71-1a72fe52eec0">

我看了下高级打印时生成的临时html文件，里面的图片宽度是非常大的
<img width="1174" alt="image" src="https://github.com/Kenshin/simpread/assets/34783237/6dcc4b0f-c918-43bb-9829-c7d7110d9134">

**Comment by Kenshin** [comment]
@NGNL2017 

确实如此，我调查后回复你。

> 生成html这一步我不太了解是谁在做

简悦生成的，谢谢调查对我定位问题很有帮助。

**Comment by Kenshin** [comment]
@NGNL2017 

这里是个 Bug，暂时无法方便调试，但有临时解决方案，将下面的代码

```
sr-rd-content img {
    max-width: 100%;
}
```

加入到自定义中

<img width="615" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e409d3ce-bfb7-4a14-a80b-10bd00a8c62d">

PS：`100` 可更改为任意值。

即可解决。

**Comment by Kenshin** [comment]
嗨，各位。

这个 Bug 被解决了，不需要使用 https://github.com/Kenshin/simpread/issues/5412#issuecomment-1684798253 提供的方案。

直接在原位置设置修改即可

<img width="611" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/564a8e20-2c4b-4108-8612-060c72af9110">

### 升级方案

1. 没有使用同步助手的自动同步，使用 https://simpread.ksria.cn/plugins/details/Lly3mkuSPz 安装
2. 已经使用同步助手的自动同步，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

我关闭这个 Issues 了，有需要仍可以随时讨论。

**Comment by lh0830** [comment]
好评，更新插件后图片问题解决了
