### ISSUE TITLE
导入到 Obsidian 的使用疑问

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5415]
### 描述这个错误

感觉像是插件和选项页的设置打架了，一开始选项页导出html覆盖了插件的导出md，后面插件又把选项页覆盖

### 复现步骤

1. 打开一个初次浏览的网页进入阅读模式
2. 进行第一条标注
3. 到ob相应位置查看，仅有html全文（含标注）+标注，无md
4. 再进行一条标注
5. ob中出现md标注文件，含有两条标注，但之前的两个html文件不再同步更新，保持在仅有第一条标注的模样不动了
6. 继续标注，md正常同步，html继续保持仅有第一条标注的模样

### 其他相关说明

已使用过数据中心配置文件修复功能，当时显示有3个警告错误，修复之后【导入到Obsidian选项】【自动化辅助增强选项】两处设置清空，重新设好后再用数据修复功能显示无问题，但问题照旧

### 操作系统

win

### 浏览器

edge最新版

### 发生问题的网址

https://www.zhihu.com/question/592753399

**Comment by Kenshin** [comment]
我需要具体导入到 Obsidian 的相关设置截图... 以及详细导入步骤

**Comment by PupupupuTong** [comment]
![1](https://user-images.githubusercontent.com/69069739/228828451-b2931ccc-6b95-43b4-bfce-a6b3ffebc4a6.png)
![2](https://user-images.githubusercontent.com/69069739/228828493-46de9355-07fe-40e1-9ba5-4df37e962001.png)
![3](https://user-images.githubusercontent.com/69069739/228828521-b2251d93-f558-4d5c-90f1-38cb7f599afc.png)

**Comment by PupupupuTong** [comment]
试过了，结果一样

**Comment by PupupupuTong** [comment]
按DD后，ob中出现全文html和一个只有模板的md标注文件；进行第一条标注后，md消失，代之以html标注文件；再之后同前文描述

**Comment by Kenshin** [comment]
> 但之前的两个html文件不再同步更新

你在自动化里面只设置了加入稍后读后生成 HTML，而没有设置当标注时也生成 HTML

**Comment by Kenshin** [comment]
还有一点：

你没有说清楚到底是什么问题... 而直接提了复现步骤，而复现步骤也有 https://github.com/Kenshin/simpread/issues/5415#issuecomment-1490325660 这个错误。

所以，如果 https://github.com/Kenshin/simpread/issues/5415#issuecomment-1491222841 也不能解决的话，最好重新优化下你的问题描述。 😂

**Comment by PupupupuTong** [comment]
> 你在自动化里面只设置了加入稍后读后生成 HTML，而没有设置当标注时也生成 HTML

试过了，加上标注的自动化设置的话html全文（含标注）+标注可以正常运行，但没有md了

> 你没有说清楚到底是什么问题... 而直接提了复现步骤

问题就是html和md的自动导出总有一方无法完全正常运行，按 https://github.com/Kenshin/simpread/issues/5415#issuecomment-1491222841 也不能解决，而且最重要的是之前它们都是正常过的！不知道配置文件丢失找回的过程中出了什么错就又不对了！

**Comment by PupupupuTong** [comment]
如果自动化设置加上【当标注时生成html和md】
![image](https://user-images.githubusercontent.com/69069739/229032466-e4485b1d-4704-409f-b3ee-859c225c2f4f.png)

那么结果会是导出html全文（含标注）+md全文+html标注+md标注四个文件
![image](https://user-images.githubusercontent.com/69069739/229032577-29ea0330-ba9b-4d0d-91a7-5f2faf670a1e.png)
且md辅助增强插件中设定的标注模板不能生效，是这种原始样式
![image](https://user-images.githubusercontent.com/69069739/229032652-4fb01dcb-ce7d-4c94-b6d4-3899f5fadc95.png)

**Comment by Kenshin** [comment]
> 且md辅助增强插件中设定的标注模板不能生效，是这种原始样式

如果使用 Markdown 辅助增强插件的话，就不能在 [这个截图](https://user-images.githubusercontent.com/69069739/229032466-e4485b1d-4704-409f-b3ee-859c225c2f4f.png) 使用 Markdown 的自动化，会有问题。

简单的说：

1. HTML 的导出需要使用扩展端的自动化。（所以 [这个图](https://user-images.githubusercontent.com/69069739/228828451-b2931ccc-6b95-43b4-bfce-a6b3ffebc4a6.png) 的设置是正确的。
2. Markdown 的导出需要使用 Markdown 辅助增强 + 自动化辅助增强 + 导入到 Obsidian 这套方案。

总结：

1. HTML 导出走的扩展端功能
2. Markdown 导出走的插件端功能

**Comment by PupupupuTong** [comment]
> HTML 导出走的扩展端功能
> Markdown 导出走的插件端功能

那看来我一开始的理解没问题？现状就是扩展端和插件端不知为何不能同时运行，所以是这两个图 [导出到obsidian选项](https://user-images.githubusercontent.com/69069739/228828493-46de9355-07fe-40e1-9ba5-4df37e962001.png) [自动化辅助增强](https://user-images.githubusercontent.com/69069739/228828521-b2251d93-f558-4d5c-90f1-38cb7f599afc.png) 有哪里错了吗？（markdown辅助增强里就一个模板设置，应该跟这毛病无关吧）

**Comment by Kenshin** [comment]
> 那看来我一开始的理解没问题

（看你的对话）应该没问题。

把下图所示的地方先关闭

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/81074/229051804-b01b7aed-1282-4bf9-874c-52a322b94180.png">

**Comment by PupupupuTong** [comment]
关了，现在的步骤情况变成：
1. 打开一个初次浏览的网页，进入阅读模式，按dd
2. ob中出现html全文及尚无标注内容的md标注文件
![image](https://user-images.githubusercontent.com/69069739/229060077-c808dfe0-8691-4ea2-a55f-5f50678a03ec.png)
![image](https://user-images.githubusercontent.com/69069739/229060137-d8d1e56d-0a8f-4085-93ad-cfc027a0daf7.png)

3. 做第一条标注
![image](https://user-images.githubusercontent.com/69069739/229061422-56b17dfe-bf5c-4e5d-9230-78bc7a4c0282.png)

4. 到ob相应位置查看，html全文（含标注）、html标注、md标注都正常运行
![image](https://user-images.githubusercontent.com/69069739/229060630-56ca1c30-f492-4ef2-9270-32307911ef07.png)
![image](https://user-images.githubusercontent.com/69069739/229060707-91b1e992-6813-4772-a4f7-224a722897c7.png)

5. 再做一条标注
![image](https://user-images.githubusercontent.com/69069739/229061629-894c0aa7-9c53-43da-9cf6-4ddb54ed442e.png)

6. ob中md标注文件正常同步，含有两条标注，两个html文件均仅有第一条标注
![image](https://user-images.githubusercontent.com/69069739/229062013-b5e6f74e-7201-41af-8429-e7b7329260f2.png)

7. 继续标注，md正常同步，html继续保持仅有第一条标注的模样

总结：有一点变化，但核心问题没解决

**Comment by Kenshin** [comment]
> ob中md标注文件正常同步，含有两条标注，两个html文件均仅有第一条标注

这算是预期情况，因为你没有在自动化设置当 **标注改变时也导出 HTML**，在 [这个图](https://user-images.githubusercontent.com/69069739/229032466-e4485b1d-4704-409f-b3ee-859c225c2f4f.png) 的基础上去掉比标注变化时导出 Markdown（仅保留 HTML 而已）

**Comment by PupupupuTong** [comment]
强烈怀疑安卓端简悦还是有点bug，昨天操作完本来正常了，今天又双叒叕不行了。。。设置一模一样哪都没改，html标注和md标注又双叒叕有你没我有我没你了，并且通过安卓端加入稍后读的页面不做标注就无法触发自动保存html到本地，吐血ing。。。一开始有两下如果把【导入到Obsidian选项】插件里的【是否启用Markdown模板辅助增强插件？】关掉，可以同时导出按选项页定制模板的md文件，但我现在左试右试一通改回去却也没法复现了，真是要疯

**Comment by Kenshin** [comment]
不是你说的问题，当然你非要这么说的话，也没问题。

我记得之前跟你说过，如果在使用同步助手的前提下，不要同时使用手机端（浏览器）确实会有问题…

但并不是你提到的这些… 😂

**Comment by PupupupuTong** [comment]
现在把怀疑的目光投向自动化辅助增强插件，刚突发奇想手动按了一次obaa成功了，随着标注进行正确触发了几回（现在又不行了），但是第二个再试就提示“已启用控制栏面板无法实现此功能”，已经把这个插件卸载重装过了还是不行。。。我知错了我不用移动端了，以后还是微信qq发链接吧，求求好歹电脑端给我恢复正常啊(╯‵□′)╯︵┻━┻

**Comment by Kenshin** [comment]
> 我知错了我不用移动端了，以后还是微信qq发链接吧，求求好歹电脑端给我恢复正常啊(╯‵□′)╯︵┻━┻

1. 如果想要使用移动端收藏，可以试试 API 方案，细节 [看这里](https://www.yuque.com/kenshin/simpread/ieu1w6)。
2. 我认为你对配置已经很了解了，所以当出现问题时重新配置就好。（对于一个成手来说，这些配置下来 10 分种足够了）

PS：其实不要怕折腾（如果你愿意折腾的话），每次折腾完都会有新的心得 😂

**Comment by PupupupuTong** [comment]
> 如果想要使用移动端收藏，可以试试 API 方案

我用的 就是 这个 方案

> 当出现问题时重新配置就好

这不是……重新配置了……还是没好吗……
真得非得清理配置文件？

> 其实不要怕折腾（如果你愿意折腾的话），每次折腾完都会有新的心得 

确实如此，但我还有其他正事要干，反复在一个问题上耗时间真的会让人很烦躁，使用工具的初衷是为了省时间啊

**Comment by Kenshin** [comment]
1. API 方案不需要在 Kiwi 等 Android 浏览器使用.... 
2. 如果你熟悉后，有提问的时间早就解决了。
3. 是否清理文件是跟你遇到的问题有关。

还有... 如果经常坏配置文件的话（从简悦 2.0 开始我只遇到你有这个情况），其实多备份是个好习惯，坏了就用备份的。

最多损失几个稍后读（其实仍可以找回）

**Comment by PupupupuTong** [comment]
谨遵大神教诲，出问题直接重新配置，花了6小时，历经十次以上数据清理+重启，插件、服务项、ob插件已全部清空重新来过，现在变成这样了：

https://user-images.githubusercontent.com/69069739/229592023-d297655c-2e20-4a41-87b3-6ec42fc88262.mp4

真的搞不动了。。。。救命啊。。。。这玩意容错率实在低得太离谱了，我感觉我只要哪怕想动任何一丁点配置它就要出问题（虽然有时候不动也会出问题），然后永远找不到原因！现在这情况的起因只是因为我想用定制导出尝试一下文件名前的ID能否去掉，发现不好之后很快又改了回来，然后它就再也正常不了了。。。。一开始只清空了导出相关的3个插件时这情况还是概率触发，重新安装markdown辅助增强插件失败数次后（已经用了插件管理器，不行，它当时就是装不上）只好清空全部插件设置重来。我发誓所有操作都已经严格按照教程了，包括关掉自动同步、操作中只能开两个网页，然而没有卵用，bug从概率触发变成稳定触发了。。。

**Comment by PupupupuTong** [comment]
之前概率触发的时候偶尔我还来得及看一下，标注文件如果没被自动删那进去是正常的
