### ISSUE TITLE
知乎页面无法打开阅读模式

### ISSUE THREAD

**Issue by SSay1009** [Kenshin/simpread#5416]
### 描述这个错误

一开始可以正常打开阅读模式，安装了一个wkhtmltopdf插件之后，刷新配置之后就无法进入阅读模式

### 复现步骤

1. 可以打开阅读模式
2. 安装pdf辅助增强插件
3. 刷新页面配置
4. 无法进入阅读模式

### 操作系统

win10

### 浏览器

microsoft edge

### 发生问题的网址

zhihu

**Comment by Kenshin** [comment]
1. 其他页面是否也存在这个问题？
2. 在隐私模式下，仅启用简悦 试试（排除其他扩展的干扰）
3. 看下你的选项页或者稍后读能否打开？

**Comment by Test202010** [comment]
> 1. 其他页面是否也存在这个问题？
> 2. 在隐私模式下，仅启用简悦 试试（排除其他扩展的干扰）
> 3. 看下你的选项页或者稍后读能否打开？
20230402 我没有安装其他插件，也出现了一样的问题
稍后读 可以打开，右键 简悦插件 点开偏好设置 也可以正常打开选项页，但是就是打不开阅读模式，知乎、CSDN、github都不行，少数派可以打开，但是没有滚动条  #5422
