### ISSUE TITLE
iOS通过主屏幕收藏助手无法收藏微信公众号文章

### ISSUE THREAD

**Issue by CraneHuang6** [Kenshin/simpread#5420]
### 描述这个错误

iOS通过主屏幕收藏助手无法收藏微信公众号文章。
按照正常操作，也会提示收藏成功，但是无法在稍后读中找到收藏的文章。

### 复现步骤

1.复制微信公众号文章
2.回到主屏幕
3.打开收藏助手
4.点击收藏到稍后读

### 操作系统

iOS 16.4

### 浏览器

safari

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MzI5MjE4NzYzNw==&mid=2247486722&idx=1&sn=814fe4b715aab823bf90b2e95df4a2c3&chksm=ec047198db73f88e96c201119ff3df6950d22127a3a1938c8ff9ade710fc68deffb93be59168&sessionid=1680399942&subscene=93&scene=90&clicktime=1680399951&enterid=1680399951&ascene=56&devicetype=iOS16.4&version=1800222d&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&countrycode=CN&fontScale=118&exportkey=n_ChQIAhIQtRQHDurtIjdjzz26hXNezRLRAQIE97dBBAEAAAAAAPjWKrzr5dkAAAAOpnltbLcz9gKNyK89dVj0rXLDn7g8Qa5kaSjmZTFXQBvqM479zqBo%2FWCyXYas3tc5WguUWZpr0eTnT%2FZh5%2B1gUCdn%2BjtqWR5VZPduJIaxKvBgjxKCE1pvGO4xz4nXEWf2nSiykQNKbdOzzLlT3yVvJK%2F0OqGjdmCxKfTG8YcVIRkqNE9oAu3rJ%2B9g14UdbbhuT887oZIhnSDfHWzfWR7lMMp1ggUGwHFXwJ1V01IRv296h5gUIo5CeUiX&pass_ticket=%2Brk5aICCIFSoK0MSo2hOKyRu%2B7XyoK2wOyMMwaOD0Y%2Bb%2B2fkZlpoDMmkZ2uGIKUEHb93I5vVVGaaGvBPvMjq7Q%3D%3D&wx_header=3

**Comment by Kenshin** [comment]
嗨，确保稍后读可以看到的前提：

1. 开着坚果云 + 同步助手
2. 配置了 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7)

排查的方式：看看你的坚果云 Web 段的 simpread_config.json 是否更新了，如果更新的话，就是步骤1可能没开，或者步骤2中的某个选项没有开。
