### ISSUE TITLE
知乎、CSDN上使用 阅读模式 页面刷新不出来 少数派页面刷新出来后 没有滚动条

### ISSUE THREAD

**Issue by Test202010** [Kenshin/simpread#5422]
### 描述这个错误

您好 我是20230402使用简悦插件的 我在Chrome和Edge浏览器上都安装了 但是 在知乎、CSDN上使用 阅读模式 页面都刷新不出来 

### 复现步骤

输入知乎的随便一个网址，点击红色icon，页面无反应
https://zhuanlan.zhihu.com/p/43790005
![image](https://user-images.githubusercontent.com/73330797/229343813-2ebce389-562c-4f0a-a9ab-8f22f55724ea.png)

CSDN也是一样
https://blog.csdn.net/csdngeeknews/article/details/129872232
![image](https://user-images.githubusercontent.com/73330797/229344037-00a0bdf2-fba6-40e4-925c-51e6387dcf26.png)

我在 少数派网站上也测试了 阅读模式能打开页面 但是没有滚动栏 无法下滑页面，并且页面右下角出现的三个按钮，点击均无反应
![image](https://user-images.githubusercontent.com/73330797/229343855-d4f64c8e-5180-4c84-8b61-42bf18c1f749.png)

### 操作系统

Win11

### 浏览器

Microsoft Edge 版本 111.0.1661.54 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/43790005

**Comment by Test202010** [comment]
我把 Microsoft Edge 版本更新到 111.0.1661.62 (正式版本) (64 位)之后， 短暂地在知乎、CSDN上可以正常使用 阅读模式，2分钟以后，又出现上述问题了

**Comment by Test202010** [comment]
使用Google Chrome 版本 111.0.5563.147（正式版本） （64 位）也是一样的问题

**Comment by Kenshin** [comment]
看截图你应该用了某些「护眼」的扩展吧？

1. **隐身模式下仅使用简悦的方式** 
2. 关闭这些「护眼」的扩展

**Comment by Test202010** [comment]
您好 我关闭「护眼」的扩展之后 简悦插件就正常了！非常感谢！
另外，咱们 简悦插件 生态系统里 有自己的护眼插件么？望推荐！ 非常感谢！！！

**Comment by Kenshin** [comment]
没有护眼插件，不过，我可以考虑开发个类似的主题，你可以把你的护眼扩展提供给我。

**Comment by Test202010** [comment]
我目前使用的是 Screen Shader | Smart Screen Tinting
https://microsoftedge.microsoft.com/addons/detail/screen-shader-smart-scr/ogahalmmdhjhinokecoohcjkcbigokmg

我用到的功能如下：
1. 支持自定义护眼色 我用的是 #CAEACE 202 234 206
2. 可以设置 护眼色的明亮度（Darkness）
![image](https://user-images.githubusercontent.com/73330797/229390108-89fe1b6c-fc73-47db-ac76-5df3151079ca.png)
3. Shade页面 可以 分时段 调节 明亮度
![image](https://user-images.githubusercontent.com/73330797/229390274-45c02234-8271-4b29-9607-19d28a7826f8.png)

**Comment by Test202010** [comment]
我看到 简约插件 有9种主题色，很丰富。如果能自定义主题色 也能起到护眼效果。
但是，我关了护眼插件之后，页面白得亮瞎眼，然后点击简悦插件，再设置主题色，操作起来有些不方便
![image](https://user-images.githubusercontent.com/73330797/229390487-ae3a3dc7-9e3c-4f76-bb08-ade08066f07d.png)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5422#issuecomment-1493498630

okay 我研究下。

其实可以自定义主题的，只是对普通用户不太友好（需要有些 CSS 的知识）这个功能叫做 [自定义样式](https://simpread.pro/docs/#/自定义样式)，至于如何定制化的话，也可以 [看这里](https://github.com/Kenshin/simpread/issues/71)。

**Comment by Test202010** [comment]
好的 多谢！
