### ISSUE TITLE
刷新会让已授权notion失效，需要重新授权，

### ISSUE THREAD

**Issue by Ohikuy** [Kenshin/simpread#5424]
### 描述这个错误

刷新会让 是否已授权notion失效，
保存到notion提示请稍后再试，无法保存到notion

### 复现步骤

完全按教程步骤进行，做法有
1、已授权notion，是否取消授权已经开启，并选择了来自简悦的稍后读
2、在导入到notion 辅助增强选项已经填入授权的key和页面cookie
3、已经开启仅授权给该设备
4、已经尝试过卸载简悦并重装导入配置
5、已经关闭同步助手所有选择支
6、也尝试过下载同步助手并开启所有选择支
7、已经查阅过所有和notion导出失败的做法

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

各种网站 包括知乎和百度知道

**Comment by Kenshin** [comment]
1. 如果你使用了自动同步，但是已经关闭它了，不应该出问题。

2. Notion 授权的位置在哪里？（截图给我看下）

**Comment by Ohikuy** [comment]
![image](https://user-images.githubusercontent.com/33547034/229398742-f037ff4c-afe8-41f2-b50c-20e0c562b2a3.png)
有趣的事情是，如果使用保存到notion的选项是可以保存的，但选择一键导入全文到notion是失效的

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5424#issuecomment-1493553383

授权后（也就是你截图的效果）刷新页面如果仍是开启状态就没问题，建议重启浏览器。

> 如果使用保存到notion的选项是可以保存的，但选择一键导入全文到notion是失效的

截图给我

PS：文字描述会有认知误差，所以在提供功能操作时，最好是截图 + 说明 😂

**Comment by Ohikuy** [comment]
ok，以下是截图+说明

这是简悦选项截图，证明我已正确按教程要求配置，且目前并未开启自动同步
![image](https://user-images.githubusercontent.com/33547034/229399495-b9517cf9-a00f-487a-b7a8-398b3b07e961.png)
![image](https://user-images.githubusercontent.com/33547034/229399516-5f4db002-0321-42d2-95a4-3d506024ec72.png)
![image](https://user-images.githubusercontent.com/33547034/229399667-011cd6e3-2407-4a41-a7ab-30184314f04f.png)
![image](https://user-images.githubusercontent.com/33547034/229399825-4e7d244f-0737-4f81-a6ea-01dd572e3862.png)


1、这是选择一键导入到全文的情况
![image](https://user-images.githubusercontent.com/33547034/229399368-38afa9ca-a72b-4086-81bf-ff5201f743f8.png)
![image](https://user-images.githubusercontent.com/33547034/229399935-c1293f4e-4a84-463c-90db-723e78fdcbff.png)

2、这是选择同步到notion的情况
![image](https://user-images.githubusercontent.com/33547034/229399991-e202b53f-820e-4f20-ab76-9933755322f7.png)
![image](https://user-images.githubusercontent.com/33547034/229400039-76339918-ce5e-4592-bb4a-117f0a695c84.png)

目前使用2同步不影响正常使用

**Comment by Kenshin** [comment]
okay 我明白你的问题了：

导入到 Notion 是一个简悦插件，功能说明[在这里](https://github.com/Kenshin/simpread/discussions/4954)，也就是下图所示的功能。

<img width="364" alt="image" src="https://user-images.githubusercontent.com/81074/229404344-2e30125c-728a-4bed-9b45-1d61a9d0d05b.png">

扩展端 → 服务 → 授权管理里面是另外简悦内置的 Notion 导入功能，也就是你提到的这个图

![](https://user-images.githubusercontent.com/33547034/229399495-b9517cf9-a00f-487a-b7a8-398b3b07e961.png)

综上，你可以这么理解：

简悦有两个导入到 Notion 的功能：

1. 扩展端内置
2. 简悦插件

***

这是两个功能，插件的功能比扩展端的功能要更丰富，你使用这两个中的哪一个都 OK。

按照你的截图来说，你配置了扩展端的导入功能，就需要通过 [这个截图](https://user-images.githubusercontent.com/33547034/229400039-76339918-ce5e-4592-bb4a-117f0a695c84.png) 的方式导入。

而不能使用 [此截图](https://user-images.githubusercontent.com/33547034/229399368-38afa9ca-a72b-4086-81bf-ff5201f743f8.png) 的功能，这个截图对应的功能是 **导入到 Notion** 插件端功能。

***

之所以有这么个区别：

Notion 官方经常会无关「弄坏」某些 API，但是还不主动修复，所以为了避免这种被动的方案，所以有了插件端的功能。

细节可以看这个图的说明

<img width="882" alt="image" src="https://user-images.githubusercontent.com/81074/229405165-bcfbc623-9f50-4fb5-b759-aa85a85416bd.png">


这两个方案的区别

<img width="889" alt="image" src="https://user-images.githubusercontent.com/81074/229405189-95f5ec54-e3ad-41a7-96a3-2870e3aa48d5.png">

**Comment by Ohikuy** [comment]
@Kenshin 但这么看来，简悦导入notion插件的使用功能对于我来说是失效的，而我并不知道失效的原因在哪里

**Comment by Kenshin** [comment]
> 简悦导入notion插件

截图中没有体现对这个插件的设置，如果你要设置的话，看下图

<img width="554" alt="image" src="https://user-images.githubusercontent.com/81074/229410193-90ff94e5-fb0c-4872-8932-5d1c2879ef0d.png">

**Comment by Ohikuy** [comment]
good 配置此处后问题解决

**Comment by Kenshin** [comment]
okay 解决就好~

**Comment by Ai-Robots-world** [comment]
> 
你好,能跟我说说你得解决步骤吗?我也碰上和你一样的情况.
![](https://user-images.githubusercontent.com/81074/229410193-90ff94e5-fb0c-4872-8932-5d1c2879ef0d.png)
1.猜测是网页刷新导致"导入到Notion选项"失效(需要重新配置才能生效)    
2.每次刷新后"一键导入全文到Notion"会出错提示"请稍后再试"
3.刷新后通过"选择任意Notion Page导出"能正常导出
4.接第3点这时候的"一键导入全文到Notion"为正常(可导出)   刷新后表现为第2点

**Comment by Kenshin** [comment]
@Ai-Robots-world 

如果使用了同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/fcw60u 方式解决（重新安装这个插件就行了）

**Comment by Ai-Robots-world** [comment]
目前算是已经解决了.
解决的方法就是在简悦>选项页>服务 关闭notion的服务就可以了
上面作者有提到扩展端内置和简悦插件不能同时开启

**Comment by Kenshin** [comment]
> 目前算是已经解决了. 解决的方法就是在简悦>选项页>服务 关闭notion的服务就可以了 上面作者有提到扩展端内置和简悦插件不能同时开启

竟然是这种问题 😂

PS：理论上它们都可以使用，但有可能在极端情况下出现错误，而同时使用的意义也不大。
