### ISSUE TITLE
绑定Notion账号失败

### ISSUE THREAD

**Issue by hunaohunaohunao** [Kenshin/simpread#5425]
### 描述这个错误

我用的是Microsoft Edge，版本： 112.0.1722.23 (正式版本) Dev(x86_64)，安装了简约插件，插件版本是: 2 . 2 . 0 . 5 2 0
希望能保存文章到Notion，Notion在网页上已登录。
但是在我希望保存的网页上进行操作： 阅读模式-...-动作-保存到Notion-是否链接到Notion并授权，在这里会提示：授权中，请勿关闭此页，授权成功后会有提示。然后就长期无响应了,既不提示成功，也不提示失败。
我尝试在进行其他授权，授权Github是成功的，说明我本机的环境没有问题。
请看看具体是什么愿意导致的？
另外，做为一个新用户，从我的角度出发，发现简悦有两个问题：
1）文档做得不够好，不够简单到容易让新用户上手，或者很快的能找到解决方案。
2）菜单设计得也不够友好，和多数软件的操作以及菜单的功能和名称上都不太一样。

### 复现步骤

我用的是Microsoft Edge，版本： 112.0.1722.23 (正式版本) Dev(x86_64)，安装了简约插件，插件版本是: 2 . 2 . 0 . 5 2 0
希望能保存文章到Notion，Notion在网页上已登录。
但是在我希望保存的网页上进行操作： 阅读模式-...-动作-保存到Notion-是否链接到Notion并授权，在这里会提示：授权中，请勿关闭此页，授权成功后会有提示。然后就长期无响应了,既不提示成功，也不提示失败。
我尝试在进行其他授权，授权Github是成功的，说明我本机的环境没有问题。
请看看具体是什么愿意导致的？
另外，做为一个新用户，从我的角度出发，发现简悦有两个问题：
1）文档做得不够好，不够简单到容易让新用户上手，或者很快的能找到解决方案。
2）菜单设计得也不够友好，和多数软件的操作以及菜单的功能和名称上都不太一样。
希望能将简约做得能像名字一样，做得够简单，方便，实用。

### 其他相关说明

暂无

### 操作系统

macOS Monterey

### 浏览器

112.0.1722.23 (正式版本) Dev(x86_64)

### 发生问题的网址

https://sspai.com/post/68902

**Comment by Kenshin** [comment]
> 阅读模式-...-动作-保存到Notion-是否链接到Notion并授权，在这里会提示：授权中，请勿关闭此页，授权成功后会有提示。然后就长期无响应了,既不提示成功，也不提示失败。

浏览器右上角 → 右键 → 偏好设置 → 服务 → 授权管理，进行 Notion 设置

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/81074/229399422-4d5ef25b-a8ea-46f2-9177-85978befc8af.png">

**Comment by hunaohunaohunao** [comment]
现在通过设置之后可以授权notion了，并且也选择了在notion里面根据模板创建的page（并且该page已经收藏了），notion增强插件也已经安装，但是现在每次保存到notin或者是一键保存全文到notion的时候都会提示：授权已过期，请重新授权。然后去重新授权，授权完回来看还是同样的问题，又提示：授权已过期，请重新授权。请问这是怎么回事？挺希望能用起来，也能付费，但是我觉得实在问题出得太多了，一个接一个，解决问题的文档并不友好，无法很直接的找到一个解决方法。经常几个页面跳转来跳转去，发现回到原来的文档了，就是一个死循环。

**Comment by Kenshin** [comment]
一个关于 QA 的建议：文字描述会有认知误差，所以在提供功能操作时，最好是截图 + 说明 

另外，猜测跟 https://github.com/Kenshin/simpread/issues/5424#issuecomment-1493593782 是一个「问题」，所以先看下这个链接中的说明。
