### ISSUE TITLE
稍后读的编辑增加tag是以#号加入正文而非加入到tag字段

### ISSUE THREAD

**Issue by Ohikuy** [Kenshin/simpread#5426]
### 描述这个错误

![image](https://user-images.githubusercontent.com/33547034/229400898-1b20a23a-0979-4eaa-873d-5dc5b8115e91.png)

### 复现步骤

1.添加到稍后读
2.在稍后读选择编辑添加标签
![image](https://user-images.githubusercontent.com/33547034/229400973-6fbdf1b6-e14b-46c2-8d9e-08254d2a69b1.png)
3.notion标签添加到正文而tag字段是空的
![image](https://user-images.githubusercontent.com/33547034/229401056-2d4cca5e-28b3-422f-9832-244e7baf0771.png)

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

all

**Comment by Kenshin** [comment]
嗨，我没理解你的问题 😂

**Comment by Ohikuy** [comment]
![image](https://user-images.githubusercontent.com/33547034/229405478-4a825dad-86d8-433a-96b1-d3db761701d1.png)

**Comment by Kenshin** [comment]
明白了，你需要使用 https://github.com/Kenshin/simpread/discussions/3572 这个插件辅助操作。

**Comment by Kenshin** [comment]
提示下：因为我看到你提了 https://github.com/Kenshin/simpread/issues/5424 里面的截图应该已经配置了 Notion 辅助增强插件。

这个插件目前只能在网页中运行，无法在扩展端的稍后读（也就是下图）中运行

![](https://user-images.githubusercontent.com/33547034/229400898-1b20a23a-0979-4eaa-873d-5dc5b8115e91.png)

**Comment by Ohikuy** [comment]
请问你指的“在网页中”意思是阅读模式吗。如果你指的是简悦的阅读模式，阅读模式仅在标注的入口可以打tag，且此处的打tag功能也是完全失效的
![image](https://user-images.githubusercontent.com/33547034/229407226-62278df5-ca42-4705-88e6-0b5a6a500f8c.png)
此处标签连正文都未存入
![image](https://user-images.githubusercontent.com/33547034/229407078-e7bbeec2-6f84-4324-a2cb-d7efae94c765.png)

**Comment by Ohikuy** [comment]
@Kenshin 请再确认一下，此处并未解决我的问题

**Comment by Kenshin** [comment]
首先，明确下：当使用了 [Notion 辅助增强插件](https://github.com/Kenshin/simpread/discussions/3572) 后才会出现下图的效果，而这些标签是通过阅读模式下的稍后读添加的，如下图。

<img width="2307" alt="image" src="https://user-images.githubusercontent.com/81074/229411377-76cf8434-5706-46e3-84c4-b7e9e71d8ce1.png">

但这种方式仅限全文。

***

其次，你提到的标注，如果是在稍后读中的标签，也会跟上图一样，但如果是在标注中的标签，则会出现在正文中。

因为简悦的稍后读系统比 Notion database 复杂或者换个角度说，Notion database 没有很好的办法显示标注的标签（你觉得应该现在在什么地方？

***

> https://user-images.githubusercontent.com/33547034/229407226-62278df5-ca42-4705-88e6-0b5a6a500f8c.png

这个截图的提示，刷新页面后重新标注再试试。

**Comment by Ohikuy** [comment]
![image](https://user-images.githubusercontent.com/33547034/229413807-0d0f19e9-4ef8-452c-a703-69eb8bf00d90.png)
似乎仍然不能解决添加标签的问题

**Comment by Kenshin** [comment]
试试使用 https://sspai.com/post/69972 这个做测试。

**Comment by Kenshin** [comment]
还有个地方：

输入完标签后，需要回车后生效。（不过，[跟这个图](https://user-images.githubusercontent.com/33547034/229413807-0d0f19e9-4ef8-452c-a703-69eb8bf00d90.png) 的提示无关）

**Comment by Ohikuy** [comment]
![image](https://user-images.githubusercontent.com/33547034/229415837-5df7cdf0-dcba-44b6-a632-c1483a8f4344.png)
这是我的尝试结果

**Comment by Kenshin** [comment]
那就说明配置有问题...

你能导入全文后触发 Notion 辅助增强插件吗？

**Comment by Ohikuy** [comment]
可以的

**Comment by Kenshin** [comment]
😂

.... 我的意思是 导入全文后触发 Notion 辅助增强插件，然后在 Notion 中没问题，是吗？

**Comment by Ohikuy** [comment]
NO
通过一键导入notion（插件端）/同步到notion(扩展端)，可以触发Notion辅助增强插件，可成功保存到notion（此处并不会保存tag）
但是，若是通过标记划词，弹出的保存全文的路径（此处可以添加tag），触发不了Notion辅助增强插件，没有保存到notion，且提示“嗨，不小心调用失败了，请不要担心，请重新再试”
&nbsp;


然然与共生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 下午2:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 稍后读的编辑增加tag是以#号加入正文而非加入到tag字段 (Issue #5426)





 
😂
 
.... 我的意思是 导入全文后触发 Notion 辅助增强插件，然后在 Notion 中没问题，是吗？

**Comment by Kenshin** [comment]
步骤

1. 先加稍后读。
2. 然后再标注。

看看如何，或者试试手动导入标注

<img width="476" alt="image" src="https://user-images.githubusercontent.com/81074/229434374-49819af0-2af5-4222-a287-60bba745ddc1.png">

**Comment by Ohikuy** [comment]
已解决。解决方式如下：
个人解决方式是：先通过插件端/扩展端保存到notion，触发辅助增强。然后再修改tag，即可正常触发辅助增强。在之后新开的网页确认只要能触发辅助增强一次，即可修改tag。
问题已解决
&nbsp;


然然与共生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 稍后读的编辑增加tag是以#号加入正文而非加入到tag字段 (Issue #5426)





 
步骤
  
先加稍后读。
 
然后再标注。
  
看看如何，或者试试手动导入标注

**Comment by Kenshin** [comment]
> 先通过插件端/扩展端保存到notion，触发辅助增强

emmm 正常就是这样的，你之前是怎么做的？（失败的情况）

**Comment by Ohikuy** [comment]
按上面操作会提升请重新再试

**Comment by Kenshin** [comment]
> 没有先通过插件端/扩展端保存到notion，进入阅读模式后直接如下图操作

加入稍后读时，会自动导入全文到 Notion（如果你是按照教程配置的话），所以我没有理解 [这个描述](https://github.com/Kenshin/simpread/issues/5426#issuecomment-1493812806)

猜测只有两种情况：

1. 未进入阅读模式时就加入稍后读。
2. 直接在阅读模式下标注。

你用的哪种？如果都不是的话，我需要你之前的操作步骤 [这个截图](https://user-images.githubusercontent.com/33547034/229439577-b1aed43f-332a-4b6d-bc93-c131d568cb2e.png) 并不是完全的操作步骤。

当然，目前还没有用户报告过近似的问题，所以既然解决了你的问题，你也可以不用回复我的疑问。

**Comment by Ohikuy** [comment]
前提操作：1、未进入阅读模式时，并未将新文章加入稍后读；2、直接在阅读模式下标注

以下是完整的**错误操作复现**，希望这能让简悦变得更好
![image](https://user-images.githubusercontent.com/33547034/229444771-9ac44636-2723-4bcc-a428-98472b5cfe21.png)
![image](https://user-images.githubusercontent.com/33547034/229445117-a94ac4ec-f54a-45be-b1af-ed1bf1724759.png)
![image](https://user-images.githubusercontent.com/33547034/229445334-9f90e7d4-ed68-4ea8-928a-2867eb3a7d35.png)
无法保存
-----------------------------------------------------------------------------------------------------------------
以下为先通过插件端/扩展端保存到notion，触发辅助增强的**正确操作**
![image](https://user-images.githubusercontent.com/33547034/229445734-3c935d9c-8701-42a0-983c-b35003a055fd.png)

![image](https://user-images.githubusercontent.com/33547034/229446534-24464c07-8a64-4c0e-b893-0aec448fc0c0.png)
![image](https://user-images.githubusercontent.com/33547034/229446706-48681ea7-137a-435e-90fc-b5ebb38b15c9.png)
![image](https://user-images.githubusercontent.com/33547034/229446760-64f7faf8-7334-4086-bb76-9a3eaaaa87ec.png)

**Comment by Kenshin** [comment]
> 1、未进入阅读模式时，并未将新文章加入稍后读；2、直接在阅读模式下标注

okay 那就是我说的第二种方式

<img width="609" alt="image" src="https://user-images.githubusercontent.com/81074/229451454-afdc4521-47fb-4f41-b8b4-2c69d2400c40.png">

我看下如何优化。这个插件必须要依赖与加入稍后读这个「事件」，**没有加入稍后读而直接标注**肯定会有问题。

**Comment by Ohikuy** [comment]
感觉更改一下报错提示语即可
&nbsp;


然然与共生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] 稍后读的编辑增加tag是以#号加入正文而非加入到tag字段 (Issue #5426)





  
1、未进入阅读模式时，并未将新文章加入稍后读；2、直接在阅读模式下标注
  
okay 那就是我说的第二种方式
 

 
我看下如何优化。这个插件必须要依赖与加入稍后读这个「事件」，没有加入稍后读而直接标注肯定会有问题。

**Comment by Kenshin** [comment]
okay 会考虑的（确实是个简单的方案 😂
