### ISSUE TITLE
连续标注模式下如果同时选中图片和文字，图片会单独多生成一个标注

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5431]
### 描述这个错误

并且随后改颜色还默认只改单独生成的图片标注

### 复现步骤

https://user-images.githubusercontent.com/69069739/229525817-da0b37ea-e91e-4544-90c5-505aecf0758b.mp4

### 其他相关说明

并且这样以后直接在图片上点击无法呼出编辑栏，想把多生成的图片标注删掉只能去右侧标注列表编辑，然而标注列表的“>”箭头有点过于靠边过于小，滚动条一触发更是只剩一半，点起来非常之累，希望能改进

### 操作系统

win

### 浏览器

edge最新版

### 发生问题的网址

https://www.zhihu.com/question/55359386/answer/144384848

**Comment by PupupupuTong** [comment]
那有没有可能至少把 标注列表“>”按钮太难点击 和 单击图片无法呼出编辑栏 的问题解决一下？滚动条一遮挡想编辑单条标注实在太难了

**Comment by Kenshin** [comment]
我没太理解你的疑问，但你可以按照下图设置

<img width="977" alt="image" src="https://user-images.githubusercontent.com/81074/229670134-263d51fd-fe94-45e1-968b-1e7b72d1c197.png">
