### ISSUE TITLE
阅读助手建议加入自定义 Endpoint 功能

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5433]
可不可以加入自定义base_url的支持，就是把 https://api.openai.com 自定义为其他 endpoint 😁

_Originally posted by @cesaryuan in https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5511398_

**Comment by Kenshin** [comment]
@cesaryuan

嗨，我帮你新建了一个 Issues，并删除了原来位置的内容。

***

会考虑的，但可能优先级不高。

原因是：因为是基于全文的「理解」，所以后端并不只是使用了 OpenAI 的 Endpoint。

另外一点：目前这个阅读助手的后端是可以在正常网络环境下使用的。

我先 Mark 下这个需求。

**Comment by Kenshin** [comment]
@CharMingF

嗨，在这个 Issues 里面讨论定制 API 的功能。

**Comment by CharMingF** [comment]
> @CharMingF
> 
> 嗨，在这个 Issues 里面讨论定制 API 的功能。

国外访问毕竟受限，我看到有一些提供了第三方的API，虽然有一些风险，但是付费方面可能方便一些，比如看到有人部署自己的chatgpt的用这个https://api2d.com/wiki/doc ，非广告啊

**Comment by Kenshin** [comment]
@CharMingF

嗨

目前简悦的阅读助手可以正常访问，并且使用的是正规渠道，不会太出现某些账户被封的情况，所以这种方式是首选，虽然后端会消耗一定的 💰 但暂时不考虑收费，用户只需要自己提供 Token 就能使用了。

所以目前对用户来说是最少折腾的方案。

至于暂时不支持定制的原因 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1495244838 里面已经描述了。

PS：只是优先级不高而已。

**Comment by Kenshin** [comment]
嗨，因为阅读助手并不是简单的调用 OpenAI API，所以暂时阶段并没有迟迟加入自定义 API 功能，因为更改起来难度很大。

## 为什么暂时无法定制 API（阅读助手的优势）

简悦的功能与其它你看到的 Chat 类产品的功能不一样，简悦的阅读助手做的是：**帮你分析全文，并根据你的提问给出解决方案**。

简悦只所以能做到这么精准的回复你的问题，因为不仅仅只是简单的调用了 OpenAI 的服务，简悦的后端做了很多其它事情。

所以，这就是暂时无法支持 **自定义 API** 的原因。

## 简悦后端的优势

可以正常访问网络，用户仅需输入自己的 Token 即可使用。

## 自定义 API 的调研

> 你需要 **自定义 API 的原因是什么**？

因为无论是否使用了 API，都需要用户自己填入 Token （这个需要从 OpenAI 官方申请）。

所以如果因为 **怕无法访问 OpenAI 后端** 的话，**无需担心，你调用的只是简悦的后端，这个可以正常访问**。

否则的话，我想不到有需要自定义 API 的意义。

所以在这里咨询下，你需要这个功能的意义。

**Comment by liujuntao123** [comment]
自定义API并非是功能上的意义，而是因为官方的OpenAI充值渠道过于繁琐和苛刻，所以使用国内的一些转发API，更加方便，可以随时以点卡的方式充值使用。

**Comment by liujuntao123** [comment]
关于难度问题，确实可以理解作者。这里给一些粗浅的建议，OpenAI的api调用有两种方式，一种是http接口，一种是SDK包，http接口的话，不存在api地址的问题，如果是SDK包，据我了解，有一个配置叫api_base，可以改变host。如果不对的地方，欢迎指正和探讨。

**Comment by Kenshin** [comment]
> 自定义API并非是功能上的意义，而是因为官方的OpenAI充值渠道过于繁琐和苛刻，所以使用国内的一些转发API，更加方便，可以随时以点卡的方式充值使用。

你的意思是说：你不是填入 OpenAI Token 而是填入某家自己的 Token ，然后调用它家自己的服务？

**Comment by liujuntao123** [comment]
> 

对的，可以这么理解。然后他家一模一样的复刻了OpenAI 的所有api，其实本质是做了个负载均衡和转发。而且，还便宜，并且支持高并发。。。（中间具体为什么便宜我也不清楚，反正很好用就对了哈哈）

**Comment by Kenshin** [comment]
@liujuntao123 

你能上 tg 吗？我需要用你的 API  测试下。

**Comment by liujuntao123** [comment]
> 



> @liujuntao123
> 
> 你能上 tg 吗？我需要用你的 API 测试下。

https://github.com/chatanywhere/GPT_API_free,这里有免费的key可以用
![image](https://github.com/Kenshin/simpread/assets/22583601/3e5aa239-0133-45f4-baf0-a98a9ebcac09)

**Comment by shadu120** [comment]
意义重大！能解决很多墙内用户访问OpenAI的问题。
你并不需要提供API支持，提供域名自定义就可以。
参考：https://github.com/shadu120/openai-cloudflare

**Comment by Kenshin** [comment]
@shadu120 

> 能解决很多墙内用户访问OpenAI的问题。

仔细看我提到 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1621070991

**简悦官方没有这个顾虑**，唯一的事情是需要让用户自己准备 Token

***

> 你并不需要提供API支持，提供域名自定义就可以。

我的意思是：我需要测试下才能确定这个功能是否可用...

@liujuntao123 

okay 我研究下~

**Comment by shadu120** [comment]
我电报发你。

**Comment by cesaryuan** [comment]
> 因为不仅仅只是简单的调用了 OpenAI 的服务，简悦的后端做了很多其它事情

关于这个问题我的想法是只允许用户自定义OpenAI的域名就可以啦

我们公司有自己提供的OpenAI接口，而且是免费的，在这种情况下允许自定义endpoint可以省钱（

**Comment by Kenshin** [comment]
@cesaryuan 

> 关于这个问题我的想法是只允许用户自定义OpenAI的域名就可以啦我们公司有自己提供的OpenAI接口，而且是免费的，在这种情况下允许自定义endpoint可以省钱（

自定义 API 的话，必须要跟 OpenAPI 一样才行，否则没法使用。

PS：公司够大方  👍

**Comment by Kenshin** [comment]
嗨，各位。

> 自定义 API 可以内测了。

## 测试方案

1. 选项页 → 插件管理 → 禁用阅读助手

    <img width="290" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/353b322a-a288-4e69-b6d1-a6c90a36c76f">

2. 没有使用同步助手的话，直接安装 https://simpread.ksria.cn/plugins/details/TmZSYtz5lA 

3. 如果使用了自动同步，请使用 https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C 安装

## 设置

<img width="575" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/153c0e81-1a0f-4d55-bef7-b2230555e527">

## 留意

1. 你填入的是 **主域名** 例如你的 API 是 https://api.xxx.com/ 就应该填入 `api.xxx.com` ，即没有 `https://` 也没有 `/` 这类的主域名
2. 别忘记保存
3. 我测试了几个第三方 API 都没问题，如果你的 API 有问题，请随时反馈。

**Comment by shadu120** [comment]
第一步：
选项页 → 插件管理 → 禁用阅读助手

第二步：
- 没有使用同步助手：，直接安装 https://simpread.ksria.cn/plugins/details/TmZSYtz5lA
- 使用了自动同步助手：使用 https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C 安装 （先安装，后导入）https://simpread.ksria.cn/plugins/details/TmZSYtz5lA

<img width="296" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/9bed5e3b-74c0-4c3b-82b7-351ef412886d">

效果：
<img width="1241" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/9f8ac71a-263d-4d34-9351-e1ef7af79bf5">

**Comment by Kenshin** [comment]
![OpenAI@cover v2](https://github.com/Kenshin/simpread/assets/81074/03673e06-13fd-4752-b6e7-34cfcc460feb)

嗨，各位。

阅读助手 3.1.0 发布了，增加了两个新功能。

## 自定义第三方 API 服务

详细说明 👉 https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6361313

![image](https://github.com/Kenshin/simpread/assets/81074/a4eb995e-0a29-4767-962f-92d498899d1f)

## 支持 GPT-4

详细说明 👉 https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5175855

![image](https://github.com/Kenshin/simpread/assets/81074/30440609-23d2-4767-8411-2c31d8dba999)
