### ISSUE TITLE
我现在只要导入json文件，偏好设置就打不开

### ISSUE THREAD

**Issue by PenguinDang** [Kenshin/simpread#5435]
### 描述这个错误

<img width="365" alt="image" src="https://user-images.githubusercontent.com/115391259/229783308-a25aef67-ba75-45da-86c7-90499c568e34.png">
macOS 13+edge 最新+同步助手 1.2.0
我重装了系统后无法使用简悦插件，然后卸载了插件重装，此时是可以打开偏好设置的。只要恢复json文件就一直无法进入偏好设置（如上图，一直在跳动），换了很多个不同时期备份的json文件也无济于事。

### 复现步骤

1.打开edge，点击简悦插件，点击偏好设置
2.无法打开
3.卸载简悦插件，再从edge扩展商店下载，可以打开偏好设置
4.点击导入配置文件，选择配置文件后就有无法打开了。之前备份的配置文件也无法使用

### 操作系统

macOS

### 浏览器

edge

### 发生问题的网址

https://cn.bing.com/

**Comment by Kenshin** [comment]
看下同步助手的 UID是不是掉了？或者重启同步助手。

另外一点：这个现象也可能是配置文件出错造成的，但你说用了备份的配置文件，那就不应该是这个问题（仅做提示）。

**Comment by luke396** [comment]
我也出现了类似的状况, 同步助手和本地json文件会导致网页无法打开, 我的原因应该是选错了如下的选项(具体哪一个选错了,我也忘记了), 导致配置文件覆盖错误.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/77875500/237022187-715ef40d-4f9f-4dc3-a174-a709a613eeba.png">

我的解决方法: 

先关闭同步助手, 加载偏好设置网页, 这时候应该是可以加载的(此时我检查了一下, 还存在高级资格), 但是右上角会提示同步助手未开, 然后打开同步助手, 选择上面两个选项中, 左侧的选项, 将浏览器的配置文件导入到本地(在此之前, 本地的json配置文件被我手动清除), 右上角提示导入成功, 之后就可以打开偏好设置的页面了.

(这是个反复尝试出的解决方案, 可能有很多不必要的步骤, 也不排除造成数据或者配置丢失, 但总归是打开了...)

**Comment by Kenshin** [comment]
@luke396 

试试 [同步助手的修复配置文件](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e4%bf%ae%e5%a4%8d%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6) 功能。
