### ISSUE TITLE
Notion api请求成功但一直无法授权，且无错误提示

### ISSUE THREAD

**Issue by AStarlessNight** [Kenshin/simpread#5436]
### 描述这个错误

notion授权失效，出现这个弹框后，过一会弹框直接消失，F12查看notion api调用是成功的
![image](https://user-images.githubusercontent.com/67539047/230009054-3233821f-822c-4921-99b0-a81e5b4b48d8.png)

补充：webclipper可以授权成功

### 复现步骤

1. 点击notion授权
2. 出现授权中弹框
3. 弹框消失，未授权

### 操作系统

Windows11

### 浏览器

Chrome 112.0.5615.50

### 发生问题的网址

https://www.webpackjs.com/concepts/entry-points/

**Comment by Kenshin** [comment]
1. 建议在 https://sspai.com/post/69972 授权。
2. 留意 https://www.yuque.com/kenshin/simpread/wwk65u 提到的一些问题的解决方案。
