### ISSUE TITLE
开放平台API测试通过但授权码登录一直显示服务器错误

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5441]
### 描述这个错误

返回的是201
![image](https://user-images.githubusercontent.com/69069739/230341566-1e6b9d68-bb33-49d1-84db-04fc51abbd5f.png)

但是登录时
![image](https://user-images.githubusercontent.com/69069739/230341693-4df1d99e-0559-42af-9bee-f79cfb5eb4de.png)

已经等了很久了，上午就这样，现在还是如此，刚刚用邮箱登进去了一次

通过移动端收藏助手添加进稍后读的内容只在output文件夹里自动导出html，但打开稍后读并无显示
![image](https://user-images.githubusercontent.com/69069739/230344768-ac33e067-7533-4ac2-b028-8119da7d2427.png)
![image](https://user-images.githubusercontent.com/69069739/230344919-bf62e044-f53b-45bf-af8c-5da375b2007c.png)
![image](https://user-images.githubusercontent.com/69069739/230350309-a9f5d0a3-a863-498e-bf58-bc929a76a293.png)

### 复现步骤

1. 按照 https://www.yuque.com/kenshin/simpread/ieu1w6 教程配置开放平台
2. 安卓端登录
3. 通过收藏助手添加URL
4. pc端查看

### 其他相关说明

并且在PC端通过个人中心内的阅读助手打开后无法进入阅读模式

### 操作系统

win，Android

### 浏览器

edge最新版

### 发生问题的网址

https://mp.weixin.qq.com/s/vybYCh3ZyQuvXU0iN91ifA

**Comment by Kenshin** [comment]
> 已经等了很久了，上午就这样，现在还是如此，刚刚用邮箱登进去了一次

登录的话，试试**隐身模式下仅使用简悦的方式**，有可能是缓存造成的。

> 通过移动端收藏助手添加进稍后读的内容只在output文件夹里自动导出html

看看你的坚果云中 `simpread_config.json` 是否更新了？

***

PS：这两天在忙点事情，所以没有来得及改你的配置文件  😅 

PPS：你可以把你的 UID 通过 tg 发给我，我看下 API 相关的功能是否正确。

**Comment by PupupupuTong** [comment]
> 看看你的坚果云中 simpread_config.json 是否更新了？

更新了，加完URLPC就有弹窗提示（所以稍后读里不显示好奇怪啊）

> 这两天在忙点事情，所以没有来得及改你的配置文件

没事，误打误撞基本解决了（但是很想知道为什么会这样，具体过程tg已发，烦请有空过目）

> 你可以把你的 UID 通过 tg 发给我，我看下 API 相关的功能是否正确。

已发，谢谢大大

**Comment by Kenshin** [comment]
> 更新了，加完URLPC就有弹窗提示（所以稍后读里不显示好奇怪啊）

也就是本地的 `simpread_config.json` 也更新了？

假设也更新了，这时重启浏览器再确认下。

或者做个测试：先关闭浏览器，然后用手机收藏，看看本地的配置文件是否更新了。

如果更新了就打开浏览器确认稍后读。

**Comment by PupupupuTong** [comment]
![image](https://user-images.githubusercontent.com/69069739/230585804-4b715689-d5ee-4c21-a427-e16416f8c398.png)
![image](https://user-images.githubusercontent.com/69069739/230586586-dbbb4256-d635-4664-9991-28102041b20d.png)

这样应该就是本地配置文件已更新吧？

![image](https://user-images.githubusercontent.com/69069739/230586167-4f138262-39b4-46e5-a9fc-ed6a3fddb2ba.png)

output文件夹里html也存下来了（话说为什么数字会重）

![image](https://user-images.githubusercontent.com/69069739/230586403-420463fa-574e-43b4-9661-8535423b58ff.png)

但是稍后读里还是空的，重启浏览器也是这样

**Comment by Kenshin** [comment]
我看了这个 UID 对应的配置是没问题的。

你用任意文本编辑打开 `simpread_config.json` 然后搜索下 `123-` 看看能否搜索到任何内容？

另外一个地方：你的  `simpread_config.json` 有多大？
