### ISSUE TITLE
插件提示获取高级版权限

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5443]
### 描述这个错误

使用的是图床插件，并且已经是高级账号，但是，在使用过程中，提示：
扩展端需要先确保你的账号为高级账户后才能使用此功能。
![mstsc_CZ8E07qp10](https://user-images.githubusercontent.com/22015183/230430808-6e3c12dd-8004-441d-ba62-2353bd4f7ced.png)
然后就不能用了

不知道是不是插件冲突的问题，我用的其他插件是SingleFileZ，这个插件一直在用，不能卸载

### 复现步骤

试过删除图床插件，再安装上，就正常了，不过一会就又提示

### 操作系统

windows

### 浏览器

谷歌浏览器

### 发生问题的网址

没有网址

**Comment by Kenshin** [comment]
一般来说是升级完高级账户后没有重启浏览器造成的。

打开选项页，然后试试依次按顺序这两个方案：

1. https://www.yuque.com/kenshin/simpread/ga970q
2. https://www.yuque.com/kenshin/simpread/sw4m21
