### ISSUE TITLE
获取印象笔记授权失败

### ISSUE THREAD

**Issue by huang5307** [Kenshin/simpread#5444]
### 描述这个错误

新用户，使用坚果云可以，但是希望连接印象笔记却是死活无法成功，2台笔记本试了10几回了。
![image](https://user-images.githubusercontent.com/7876228/230533782-85d8357b-9fb7-49eb-b7b5-a879935a61e4.png)

### 复现步骤

步骤1，点击选项/服务/授权管理/印象笔记

### 其他相关说明

Windows 11
系统自带Edge

### 操作系统

Windows 11

### 浏览器

Edge 111.0.1661.62 (正式版本) (64 位)

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

**Comment by Kenshin** [comment]
远离印象笔记，早走早解脱。

另外，把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
