### ISSUE TITLE
使用沉浸式翻译，再进入简悦的阅读模式后，就没有翻译后的内容了

### ISSUE THREAD

**Issue by fozwolt** [Kenshin/simpread#5447]
### 请描述你的建议或任何内容

目前在外文网站使用[沉浸式翻译插件](https://github.com/immersive-translate/immersive-translate)后再点击进入简悦阅读模式，就看不到翻译的文字内容了，只能看到原文，请修复这个 bug

### 补充说明

英文网站

**Comment by Kenshin** [comment]
这不是 Bug...

把这个网站的主域名添加到 [延迟加载列表](https://simpread.pro/docs/#/%E5%BB%B6%E8%BF%9F%E5%8A%A0%E8%BD%BD%E5%88%97%E8%A1%A8)

**Comment by Kenshin** [comment]
这不是 Bug...

把这个网站的主域名添加到 [延迟加载列表](https://simpread.pro/docs/#/%E5%BB%B6%E8%BF%9F%E5%8A%A0%E8%BD%BD%E5%88%97%E8%A1%A8)
