### ISSUE TITLE
系统翻页键无法使用

### ISSUE THREAD

**Issue by jameschcc** [Kenshin/simpread#5448]
### 描述这个错误

进入阅读模式后，PgUp / PgDn 快捷键无法翻页，我的鼠标侧键绑定了这两个键，但进入阅读模式后始终无效了。
在设置里 禁用全部快捷键后 也是没有效果的。只有简约定义的键盘左右键可以翻页。
PgUp / PgDn这两个按键很常用，望修复。

### 复现步骤

1/进入阅读模式
2/按PgUp或PgDn

### 操作系统

Windows  MacOS

### 浏览器

Chrom / Edge

### 发生问题的网址

*

**Comment by Kenshin** [comment]
这不是 Bug 😂

阅读模式类的产品比较特别，因为要避免跟原页面产生「交互或被污染」，所以跟很多快捷键（类扩展都有冲突）。

另外一点，如果你在使用 `PgUp / PgDn` 翻页时，会自动刷新页面的话，当然也没有这个问题。
