### ISSUE TITLE
阅读模式下微信公众号文章出现大段空白（个例）

### ISSUE THREAD

**Issue by CraneHuang6** [Kenshin/simpread#5449]
### 描述这个错误

阅读模式下微信公众号文章出现大段空白

### 复现步骤

1.打开简悦稍后读
2.选择文章，打开源页面
3.按下AA

### 操作系统

Win10

### 浏览器

Chrome 112.0.5615.50

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=Mzg2OTY0MDk0NQ==&mid=2247501351&idx=1&sn=31597b03b587b5eaf0132f2392f581e6&chksm=ce9b79b9f9ecf0af030f54142f5639296643713edc719d3839756f2ae3d5ee514502f1378461&mpshare=1&scene=1&srcid=0406tQMP83WLyxKcbQT5w0f7&sharer_sharetime=1680787256686&sharer_shareid=1c99c323ff941ecd3c0981f22c323aaf#rd

**Comment by Kenshin** [comment]
okay 谢谢反馈，我先记录下。

**Comment by Kenshin** [comment]
嗨，这个适配问题被解决了，解决方案 https://github.com/Kenshin/simpread/issues/5839#issuecomment-1675654114

我关闭这个 Issues 了，如果有任何问题建议在 https://github.com/Kenshin/simpread/issues/5839 集中讨论。
