### ISSUE TITLE
无法加入到稍后读和同步到obsidian

### ISSUE THREAD

**Issue by WuWeiStudio** [Kenshin/simpread#5450]
### 描述这个错误

该文章在阅读模式下点击加入到稍后读时出现错误，无法加入到稍后读，无法同步到obsidian。

### 复现步骤

![Snipaste_2023-04-08_15-59-01](https://user-images.githubusercontent.com/72329860/230710721-78fa7017-4902-4585-b7af-fb4423e5725f.png)

### 操作系统

Windows11

### 浏览器

Chrome

### 发生问题的网址

https://www.cnblogs.com/ljhdo/p/13373208.html

**Comment by Kenshin** [comment]
嗨，我测试了这个页面，是可以正常导入 Obsidain 的

你给出的信息太少，我没法判断。建议：

1. 给出导入到 Obsidian 插件的全部设置截图
2. 同步助手的导出文件夹的设置截图

等跟 Obsidian 有有关联的全部相关截图。
