### ISSUE TITLE
每次打开浏览器都弹出选项页

### ISSUE THREAD

**Issue by tSounds** [Kenshin/simpread#5451]
### 描述这个错误

安装简悦插件后，每次打开edge浏览器都弹出选项页。

### 复现步骤

1.打开浏览器
2.自动弹出选项页 extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

### 操作系统

windows

### 浏览器

edge 112.0.1722.34

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

**Comment by Kenshin** [comment]
1. 是不是禁用了 Cookies？
2. 重新安装，然后什么都不要多余设置，是否还有问题？

**Comment by tSounds** [comment]
@Kenshin 插件在edge和chrome商店都装着试过，edge浏览器也重置了下，安装好就重开浏览器，还是弹出选项页。

**Comment by Kenshin** [comment]
emmm 

首先肯定是个例，所以方便的话：

> 在出问题的设备上，能否用其他浏览器试试。（用来排除因设备造成的问题）

**Comment by Kenshin** [comment]
很奇怪的问题  😂 还是第一次有用户反馈这种问题。
