### ISSUE TITLE
关于 Logseq 模板的使用疑问呢

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5452]
啊 纯小白 啥也不懂 跟着教程 https://www.yuque.com/kenshin/simpread/gbere7#sBDLV 一步步到了这里（如图）之后根本不知道怎么操作了 呜呜
<img width="810" alt="image" src="https://user-images.githubusercontent.com/122389161/230766826-1d09543c-7f4d-4864-9a13-caad57a3250f.png">

_Originally posted by @coconutwat in https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-5563499_

**Comment by Kenshin** [comment]
@coconutwat

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

什么叫做「不知道怎么操作」？详细说明...

**Comment by Kenshin** [comment]
@coconutwat

请不要在其它地方随便留言... 请在 https://github.com/Kenshin/simpread/issues/5452 讨论，谢谢。

**Comment by Kenshin** [comment]
@coconutwat

请不要在其它地方随便留言... 请在 https://github.com/Kenshin/simpread/issues/5452 讨论，其它地方的内容会并被删除。

***

建议直接使用 https://www.yuque.com/kenshin/simpread/pv5acw 官方提供的免配置方案。

**Comment by coconutwat** [comment]
免配置方案 我到开启自动同步这一步，就，由于中途开始弄免配置方案，下载logseq@md 之后 几个文件夹在我眼里没法check"同步助手设置的同步文件夹下发现 simprea_config.json 文件"这一步,因为在我眼里好几个simprea_config.json 文件，所以  进行下一步 打开http://localhost:7026/unread/1?embed=logseq 之后是404

**Comment by coconutwat** [comment]
https://www.yuque.com/kenshin/simpread/gbere7#sBDLV  其中的模版一块 我就是不知道该做什么啦，因为我都没接触过github ，这个模版库https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600 点进去该做什么？

**Comment by coconutwat** [comment]
啊 现在我删掉了所有东西 ，很心累，不知道怎么办才好，是再下载一次 从配置库开始吗 ？ 特别是加上 坚果云 什么原来有output文件改成output@origin …… 啊，完全一团浆糊了……

**Comment by Kenshin** [comment]
@coconutwat 

试试这篇教程 https://sspai.com/post/72022
