### ISSUE TITLE
请问怎么导出到kindle

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5456]
<div type='discussions-op-text'>

<sup>Originally posted by **ningyuwhut** April 10, 2023</sup>
我按照[发送到-Kindle](http://ksria.com/simpread/docs/#/%E5%8F%91%E9%80%81%E5%88%B0-Kindle) 和 [邮件服务](http://ksria.com/simpread/docs/#/%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1?id=%e9%82%ae%e4%bb%b6%e6%9c%8d%e5%8a%a1) 配置了同步助手，为啥一直导出失败？
下面这个图里面的发送邮箱地址和接收邮箱地址的区别是啥，我用的qq邮箱，为啥需要填两个邮箱呢
![image](https://user-images.githubusercontent.com/1762074/230812969-186d3d33-e385-4451-8fa8-006556cf4d8e.png)

<img width="423" alt="image" src="https://user-images.githubusercontent.com/1762074/230813241-7ed4d2fd-7cbe-4b81-bc2a-5bc90c8b1bac.png">

发送邮箱地址和接收邮箱地址我试了好几种，qq邮箱+gmail邮箱，smtp.qq.com + qq邮箱，qq邮箱+qq邮箱
</div>

**Comment by Kenshin** [comment]
@ningyuwhut 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

1. 发送和接受填一个，建议 QQ 邮箱
2. 留意 QQ 邮箱的 SMTP 密码。（不是 QQ 登录密码）

**Comment by ningyuwhut** [comment]
@Kenshin 多谢解答。
发送和接受填一个，建议 QQ 邮箱
===
发送和接受填一个是指要么写发送要么写接受吗还是两个都写同一个邮箱呢？ 
发送和接收不能只填一个，否则无法保存；两个都写相同的qq邮箱也会报之前的错误，密码那里我写的也是SMTP密码，不是qq登录密码

**Comment by Kenshin** [comment]
1. 发送和接受都填你的 QQ 邮箱
2. 都必须要填写。

**Comment by ningyuwhut** [comment]
@Kenshin 多谢，已正常导出到邮箱，但是导入到kindle好像还是不行，不清楚是否是延迟较久。而且我刚开始也试过“qq邮箱+qq邮箱”的配置组合，但是当时却一直报错，感觉像是配置没生效，后面稀里糊涂就可以了

**Comment by Kenshin** [comment]
> 但是导入到kindle好像还是不行

<img width="568" alt="image" src="https://user-images.githubusercontent.com/81074/231040965-508f8f50-0729-488e-b25d-2ca8cce2fccc.png">

不确定是否填写这个了，另外也需要在 Kindle 这边授权下。

**Comment by ningyuwhut** [comment]
@Kenshin 已经填了kindle邮箱了，kindle授权是指把上面配置的qq邮箱在亚马逊网站上配置到“已认可的发件人电子邮箱列表“吗，我晚上回家再试试。多谢！
另外，有个建议，”发送和接收填同一个邮箱“和kindle需要授权这两点其实可以加入到文档中，现在的文档写的不是很清晰~

**Comment by Kenshin** [comment]
> kindle授权是指把上面配置的qq邮箱在亚马逊网站上配置到“已认可的发件人电子邮箱列表“吗

是的

> ”发送和接收填同一个邮箱“和kindle需要授权这两点其实可以加入到文档中，现在的文档写的不是很清晰~

okay 我记录下。
