### ISSUE TITLE
进入阅读模式，标注选项消失

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5458]
### 描述这个错误

进入阅读模式，标注选项消失
![image](https://user-images.githubusercontent.com/86950349/231068205-9e79078a-2d7e-4621-8094-feac2b32feac.png)

退出阅读模式，反而出现了
![image](https://user-images.githubusercontent.com/86950349/231068441-7a108034-c12a-49d7-8adb-e1b841242c16.png)

### 复现步骤

进入本地html文件，使用简悦，进入阅读模式，会出现标注看不到的情况，但是退出阅读模式以后又会出现。好像是个bug

### 操作系统

windows10

### 浏览器

brave

### 发生问题的网址

本地使用

**Comment by Nadir-Echo** [comment]
> > 进入本地html文件
> 
> 你的本地 HTML URL 是什么样的？

file:///E:/test/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%20(2)/%E5%A4%A7%E6%A8%A1%E5%9E%8B%E6%94%B9%E5%8F%98%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F%E3%80%81%E8%8B%B1%E6%96%87%E7%89%88%E3%80%8C%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1%E3%80%8D%E3%80%81%E5%8D%AB%E6%98%9F%E9%80%9A%E4%BF%A1.html

这样的

**Comment by Nadir-Echo** [comment]
![image](https://user-images.githubusercontent.com/86950349/231099217-a9e9ee96-687b-48e1-81cd-4ae1b51e97cb.png)

**Comment by Kenshin** [comment]
简悦不支持通过 https://github.com/Kenshin/simpread/issues/5458#issuecomment-1502887986 方式读取本地文件。（主要是稍后读和标注相关功能不支持）

如果想要支持本地 HTML 的方式，请使用 [读取外部文件](https://github.com/Kenshin/simpread/discussions/4625)

**Comment by Nadir-Echo** [comment]
外部文件夹打不开
![image](https://user-images.githubusercontent.com/86950349/231102007-c19e6f2c-8f85-498a-80db-dc4fafee5b32.png)
![image](https://user-images.githubusercontent.com/86950349/231102046-2c42c862-3512-45d4-8de1-dc2158f2da55.png)

![image](https://user-images.githubusercontent.com/86950349/231102119-7ef9f1e1-44fe-4b8d-b50a-75fee8d80d96.png)

**Comment by Kenshin** [comment]
最后一个图的路径跟第一个图不一样... 是不是没有保存。

这个功能没有任何问题...

**Comment by Nadir-Echo** [comment]
很奇怪，设置的明明是C:\Users\NadirEcho\Desktop\Article\newsletter
显示的却是C:\Users\NadirEcho\Desktop\newsletter'
这是为啥
我把整个newsletter提到桌面上就可以了

**Comment by Nadir-Echo** [comment]
嗷嗷，我好像确实没保存，保存以后是可以了，这是个傻问题

**Comment by Kenshin** [comment]
小事情 😂
