### ISSUE TITLE
稍后读无任何文章显示

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5459]
### 描述这个错误

打开稍后读没有显示任何文章，但是同步助手上统计又是存在文章的，我尝试进行数据修复发现，显示无同步文件夹。
![image](https://user-images.githubusercontent.com/86950349/231083033-8b7b8497-8bce-4361-afd9-ce43a9cc509c.png)
![image](https://user-images.githubusercontent.com/86950349/231083079-55e51e1a-eb61-4e84-8021-a14298a37118.png)
![image](https://user-images.githubusercontent.com/86950349/231083151-b1f50c60-4159-4570-9f0a-beb6f287108c.png)
![image](https://user-images.githubusercontent.com/86950349/231083273-ccd3b9f6-e2e3-4eda-a90e-0e21c83995dd.png)
![image](https://user-images.githubusercontent.com/86950349/231084095-7035966a-b6da-4f2a-b0c5-661591ceb1c2.png)

同时obsidian的 sync server功能失效，无法读取新加入的稍后读文章
![image](https://user-images.githubusercontent.com/86950349/231083429-c5e5c48f-3134-4306-ba23-3a2b4cb7e4cf.png)

### 复现步骤

不知道时不时换了个同步助手的问题，我换成了1.2的版本？
按道理来讲不应该啊，我已经覆盖过了，也尝试根据配置库，重新配置了一遍，还是不行，不知道哪里除了问题，如果是直接通过

### 操作系统

windows

### 浏览器

brave

### 发生问题的网址

1

**Comment by Nadir-Echo** [comment]
同时直接查看文章，又是可以的
http://localhost:7026/reading/27

![image](https://user-images.githubusercontent.com/86950349/231084713-8618ee2b-c2ad-4f47-8991-0b44a4457b62.png)

**Comment by Kenshin** [comment]
看起来是没有配置好 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 相关功能，对比下链接中跟你的区别。

大概率是下图的功能没有开启

![image](https://user-images.githubusercontent.com/81074/231100322-099869cd-921b-45a0-81e4-9d8c3fade54a.png)

**Comment by Nadir-Echo** [comment]
![image](https://user-images.githubusercontent.com/86950349/231100946-cddd040f-c415-4d91-8f2f-80b09e77da02.png)
我这边是打开的

我在同步助手右键打开稍后读，就会提示
![image](https://user-images.githubusercontent.com/86950349/231101191-c6716bb8-d7b8-465a-9d45-e7ebae2800a8.png)

**Comment by Kenshin** [comment]
> 我在同步助手右键打开稍后读，就会提示

这功能跟你提到的无关...

建议还是按照 https://github.com/Kenshin/simpread/issues/5459#issuecomment-1502894508 提供的 URL 对比下你的配置。

**Comment by Nadir-Echo** [comment]
![image](https://user-images.githubusercontent.com/86950349/231105101-6ac3b4e0-4f03-4953-8c5e-73e251cf3bbe.png)
![image](https://user-images.githubusercontent.com/86950349/231105146-ad55b221-970b-446d-a886-9e260823b3a0.png)

我对照了一下，路径啥的都是一致的

**Comment by Kenshin** [comment]
你只截取了同步助手的图片，还有扩展端相关功能。

PS：大概率跟 https://github.com/Kenshin/simpread/issues/5458#issuecomment-1502909272 差不多，仔细点看教程的截图。

😂

**Comment by Nadir-Echo** [comment]
> 

额，好。我再对照一下。关键吧，我寒假的时候这个搞了一遍，3月底还在用，当时是用同步助手1.1啥的，稍后读功能和obsidian的功能都是可以使用的，没有问题。我换成1.2版本以后同步了一下，就没多想了。结果今天试了一下，就出问题了。按道理来说同步助手换了，我这个扩展端的功能应该是不会动的吧

我想了想，对哦，我直接拿以前的json文件覆盖了一下。确实就可以了😂

**Comment by Kenshin** [comment]
> 我换成1.2版本以后同步了一下，按道理来说同步助手换了，我这个扩展端的功能应该是不会动的吧

是的，没有任何关系。如果出现了这个问题的就是配置文件无意间被覆盖为旧的了...

> 我直接拿以前的json文件覆盖了一下。确实就可以了😂

（接上面这段的回复）然后就应该这么操作。 😂

**Comment by Kenshin** [comment]
PS

你可以使用：

1. 坚果云的历史记录
2. 同步助手的 https://simpread.pro/docs/#/历史记录

来保存你的每次改动。
