### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by VeraKwe** [Kenshin/simpread#546]
为什么所有的内置插件都安装不了呢？

**Comment by Kenshin** [comment]
清除本地全部插件后，再试试。
请看下这个链接中的解决办法。

**Comment by VeraKwe** [comment]
浏览器为Chrome 75.0.3770.100；系统为win10，简阅可运行，但是通过插件中心安装插件时均显示获取失败，请稍后再试。

在 2019-07-17 18:41:15，"Kenshin Wang" <notifications@github.com> 写道：


清除本地全部插件后，再试试。
请看下这个链接中的解决办法。

**Comment by Kenshin** [comment]
按照我说的方式也不行吗？
导出配置文件后重置试试？
如果不行的话，我在休假，回去后确认下。

**Comment by Kenshin** [comment]
请问还存在这个问题吗？
