### ISSUE TITLE
总抓取不到文章内容

### ISSUE THREAD

**Issue by iamaweiawei** [Kenshin/simpread#5460]
### 描述这个错误

我经常阅读官方文档，发现C4D的官方文档，总抓取不出来，手动标注范围，也是没有。文档链接：https://help.maxon.net/c4d/2023/en-us/Default.htm#html/6375.html?TocPath=BodyPaint%25C2%25A03D%257CUV%2520Edit%2520Menu%257C_____0
复现步骤上传大致操作，以及出现的效果

### 复现步骤

<img width="1546" alt="1" src="https://user-images.githubusercontent.com/46809176/231085746-22db9e21-44b2-4474-afd0-0c24f57871c1.png">
<img width="1481" alt="2" src="https://user-images.githubusercontent.com/46809176/231085765-9e3519b6-54a0-4142-9e01-f4010dbc33f4.png">
<img width="1916" alt="3" src="https://user-images.githubusercontent.com/46809176/231085870-f9536c5e-e5c0-4b90-b948-a4f61be121e4.png">
<img width="1920" alt="4" src="https://user-images.githubusercontent.com/46809176/231085880-8585d3b2-893d-4b84-9eed-688d9acb98f4.png">
<img width="1920" alt="5" src="https://user-images.githubusercontent.com/46809176/231085895-7875dcee-ed5d-4d52-8404-600d6fd23256.png">
<img width="1544" alt="6" src="https://user-images.githubusercontent.com/46809176/231085910-2d504562-0d2f-4506-bb0b-bf2cede2895e.png">

### 操作系统

WIN10

### 浏览器

Edge

### 发生问题的网址

https://help.maxon.net/c4d/2023/en-us/Default.htm#html/6375.html?TocPath=BodyPaint%25C2%25A03D%257CUV%2520Edit%2520Menu%257C_____0

**Comment by Kenshin** [comment]
这个页面因为使用了 `iframe` 方案，简悦不支持这种方式的阅读模式。

另外，文档类的页面其实都没有适配的必要（因为界面已经很干净了） 😂
