### ISSUE TITLE
关于在保存代码类网页到Notion的时候，一些代码符号不能识别

### ISSUE THREAD

**Issue by Space-Loon** [Kenshin/simpread#5461]
### 描述这个错误

原始页面
![before](https://user-images.githubusercontent.com/63574259/231211712-6760e2d9-6844-4307-9865-7358d47d563b.jpg)
导入到Notion后的页面
![Notion](https://user-images.githubusercontent.com/63574259/231211852-49668c9b-56c6-47bb-831d-32ddaff6e7c9.jpg)

在我使用保存到Notion的时候，遇到此类代码符号，均不能识别，望修复

### 复现步骤

1. 就是保存到Notion的常规步骤

### 操作系统

Windoes 11

### 浏览器

Edge dev

### 发生问题的网址

https://mp.weixin.qq.com/s/xTcx2JuMCx3srhF07JDp5g

**Comment by Kenshin** [comment]
嗨，你试试导出 Markdown 到本地，应该没有这个问题，所以这应该是 Notion 自身的问题。
