### ISSUE TITLE
关于移动端的使用疑问

### ISSUE THREAD

**Issue by phoenixchl1018** [Kenshin/simpread#5464]
### 描述这个错误

如图所示，希望插件在两个红框之间，加上一个“当前页面加入稍后读”功能，否则手机无法使用。（没有页面右键）谢谢。
![3b8ea2094bf4cf5a59c2a3214cbf7e7](https://user-images.githubusercontent.com/68170517/231446982-2df3d7b1-e4b7-4170-8705-775a1d322ae2.png)
反馈问题也很困难，知乎微博都暂无回复。希望有个更好的反馈方式，github反馈挺麻烦的。

### 复现步骤

点击菜单，无加入稍微阅读按钮

### 操作系统

Android

### 浏览器

chrome

### 发生问题的网址

https://github.com/Kenshin/simpread/issues

**Comment by phoenixchl1018** [comment]
感谢回复。目前点击三次才能加入稍后读。如果有个悬浮按钮像“启用标注”一键就方便了。另外希望可以自定义为加入梢为度自动保存网页，刚试了一下只保存了标题。。。

**Comment by phoenixchl1018** [comment]
批注也不行。。。其他还未测试

**Comment by Kenshin** [comment]
标注可以使用。

**Comment by phoenixchl1018** [comment]
好的谢谢，我再试试了

**Comment by Kenshin** [comment]
标注可以按照下图所示，位置在选项页 → 高级设定 → 标注

<img width="827" alt="image" src="https://user-images.githubusercontent.com/81074/231610900-6f7605ad-63c2-4d40-8096-b2f95a47005e.png">

***

几个提示：

但在移动端，不建议使用稍后读和标注相关功能，尤其是标注，其实并不太好有（不是简悦的问题，而是在移动端标注这个行为就不太适合）

加入稍后读后，留意让 kiwi 的配置同步给坚果云。（选项页 → 共通 → 强制覆盖配置文件到坚果云），然后在 PC 端再反着操作。
