### ISSUE TITLE
lightbox gallery 不生效

### ISSUE THREAD

**Issue by wylyeak** [Kenshin/simpread#5465]
### 描述这个错误

- 阅读模式下， Lightbox Gallery 选项 点击无任何反应
- 开启/关闭 标注情况下， 点击图片也无任何反应

尝试过：

- 插件完全删除， 只安装 插件管理 + Lightbox Gallery
- 插件完全删除， 只安装 Lightbox Gallery

### 复现步骤

无

### 操作系统

macOs

### 浏览器

Microsoft Edge  版本 112.0.1722.39 (正式版本) (x86_64)

### 发生问题的网址

https://sspai.com/post/71576

**Comment by wylyeak** [comment]
找到原因了： logseq@md 配置库中，  **在标注时，浮动标注栏的显示方式** 设置的是  **鼠标点击时显示** 导致上面插件不可用。

建议更新下配置库配置

**Comment by Kenshin** [comment]
嗨，这不算是 Bug，在选项页有详细说明

<img width="829" alt="image" src="https://user-images.githubusercontent.com/81074/231610733-6d54b724-e721-490d-b1ae-8050f8386b88.png">

因为这两个功能需要对同一个事件做监听并且处理... 😂
