### ISSUE TITLE
安装知乎阅读辅助增强选项后导出的PDF中公式显示异常，但是在阅读模式下正常显示

### ISSUE THREAD

**Issue by haifeng719** [Kenshin/simpread#5467]
### 描述这个错误

阅读模式下：
![image](https://user-images.githubusercontent.com/56433482/231688819-9452d5a1-6713-45be-821a-b93ab96db9b0.png)
导出的PDF：
![image](https://user-images.githubusercontent.com/56433482/231688991-486ded7f-0e57-4ff5-b56a-a0c9b256352f.png)

### 复现步骤

见上图

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://zhuanlan.zhihu.com/p/388859808

**Comment by Kenshin** [comment]
收到，这算是已知 Bug 但不太好优化…先 Mark 下

另外，使用了什么 PDF 导出方案？

**Comment by haifeng719** [comment]
> 收到，这算是已知 Bug 但不太好优化…先 Mark 下
> 
> 另外，使用了什么 PDF 导出方案？

同步助手基础打印方案

**Comment by Kenshin** [comment]
okay

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
