### ISSUE TITLE
默认样式“白练”无法显示加粗字体

### ISSUE THREAD

**Issue by jklop000** [Kenshin/simpread#547]
非常感谢Kenshin制作这么好的一款扩展。
有个小问题，默认样式“白练”在按 AA 进行阅读模式时会将“加粗”样式去除，换成“丁子色”这样的其它样式就没有这个问题。

**Comment by Kenshin** [comment]
收到，目前在休假，回去后修下。

你可以暂时使用 自定义样式 解决这个问题。

**Comment by Kenshin** [comment]
你可以在 [自定义样式](http://ksria.com/simpread/docs/#/自定义样式) 中加入如下的代码暂时解决

```
sr-rd-content strong {
    font-weight: bold!important;
}
```

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
