### ISSUE TITLE
关于 OpenAI 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5471]
没看到错误提示代码，只是提示OpenAI 服务器错误，请稍后再试。我感觉最近几天一直会弹出这个提示，应该不只是网络问题。

_Originally posted by @CraneHuang6 in https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5616763_

**Comment by Kenshin** [comment]
@CraneHuang6 

嗨，我帮你新建了一个 Issues

***

这个功能是高级账户功能，如果不是高级账户的话，因为一个 Bug 导致没有正确提示，但也无法正常使用。

进入选项页 → 右上角看看是不是高级账户掉了？

**Comment by CraneHuang6** [comment]
> @CraneHuang6
> 
> 嗨，我帮你新建了一个 Issues
> 
> 这个功能是高级账户功能，如果不是高级账户的话，因为一个 Bug 导致没有正确提示，但也无法正常使用。
> 
> 进入选项页 → 右上角看看是不是高级账户掉了？

高级账户目前还是在的，我不清楚是否是用了太多次该功能导致的了。
![image](https://user-images.githubusercontent.com/13868737/232535053-f9511eac-aee6-44ba-bbc0-cd5666b04355.png)
