### ISSUE TITLE
同步助手的使用疑问

### ISSUE THREAD

**Issue by Leslie1718** [Kenshin/simpread#5472]
### 描述这个错误

Windows已保护你的电脑
Microsoft Defender SmartScreen 阻止了无法识别的应用启动。运行此应用
可能会导致你的电脑存在风险。
更多信息

### 复现步骤

第一次我仍然运行了，结果花了一晚上配置好之后关机的时候蓝屏重启了…………………………
重启之后关机没事，第二天继续用，用到一般直接全部内容关掉给我自动重启
现在是不敢动了，但是又很需要同步到ob的功能，愁死

### 操作系统

win64

### 浏览器

edge

### 发生问题的网址

同步助手

**Comment by Kenshin** [comment]
嗨，首先…同步助手没有问题，已经发布快三年的产品了…（简悦发布五年…）

同步助手使用了 Electron 方案，会被某些 win 自带的杀毒误判。

另外，你用显卡是否是 AMD ？如果是的话确实会引起个别死机情况，但早在很久之前的版本已经解决了。

但看你的描述似乎不像这个情况。

但你给出的信息太少，没法判断，所以：

1. 是否是简悦官方提供的渠道下载？最好告知从哪里下载？
2. 下载的同步助手，浏览器，系统的详细版本以及你的硬件版本。
3. 不要启用简悦的自启功能。
4. 如果方便的话，能否更换其他设备测试？

**Comment by Leslie1718** [comment]
1. onedrive
2. 这个不太清楚，所以我就卸载重装了
3. 没开启之后，好像正常了

但是重新配置真的好复杂啊，一顿配置文件导入同步覆盖
前面几次标注的时候说账号不一致，后面直接标注卡没了
而且每次设置偏好，刚开始还能保存，后面就打回原形

又是一晚上过去……还是没有弄好这个配置库
如何一切从来啊？有没有视频教学……
电脑白痴发言

**Comment by Kenshin** [comment]
建议直接用配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0

**Comment by Leslie1718** [comment]
以上的疑问都是在配置高级版配置库的时候出现的哈哈哈

然后可能我折腾太反复了，今天又折腾好久，能同步标注了
但是没有本地快照，ob 的标注标题也不会更改，只有坚果云同步文件夹的更改了
请问是偏好设置的问题吗？

**Comment by Leslie1718** [comment]
看到ob 的标注标题要去ob的模板更改了，但是本地快照这个疑问不会解决……

**Comment by Kenshin** [comment]
> 没有本地快照

属于 `output` 文件夹的相关设定。看看你的同步助手的导出文件夹设定的位置是否是 output 文件夹？

另外，也可以看下关于这个功能的单独说明教程 https://www.yuque.com/kenshin/simpread/wkswh7

注意：这个教程对应的设置已经都在配置库里面了，所以你并不需要修改任何地方，仅仅只是留意各种路径就行了。
