### ISSUE TITLE
知网的标题识别不正确

### ISSUE THREAD

**Issue by PenguinWang123** [Kenshin/simpread#5474]
### 请描述你的建议或任何内容

在知网文章的“全文阅读”界面进入简悦，标题被识别成了“全文阅读XML”而不是原来的文章标题。

**Comment by PenguinWang123** [comment]
安装了知网辅助增强插件，还是标题识别为“全文检索”







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月17日(星期一) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 知网的标题识别不正确 (Issue #5474)





 
试试 #3537

**Comment by Kenshin** [comment]
okay 可能是它的页面结构改变造成的，我站重开 Issues

**Comment by PenguinWang123** [comment]
请问老师什么时候会优化好呀？一直被这困扰着

**Comment by Kenshin** [comment]
嗨，抱歉，漏掉了这个 Issues 😂

我已经修复了这个问题。

1. 没有使用同步助手的话，请直接 https://simpread.ksria.cn/plugins/details/yHqalbdeNq 升级。
2. 已经使用同步助手的话，请使用 https://www.yuque.com/kenshin/simpread/fcw60u 升级。

我关闭这个 issues 了~

**Comment by chenshinshi** [comment]
我这边同步助手是1.2.0最新版本，也启用了知网辅助加强插件，但标题仍然识别有误。

**Comment by Kenshin** [comment]
@chenshinshi 

emmmm 这个功能跟同步助手无关。

因为我没法真正登录知网，所以有可能我测试的页面结构跟你的不一样。

PS：如果你确定是刚刚下载并安装的知网插件的话。

否则，先使用上面链接提到的方式确保你的知网插件是最新的。

**Comment by chenshinshi** [comment]
> @chenshinshi
> 
> emmmm 这个功能跟同步助手无关。
> 
> 因为我没法真正登录知网，所以有可能我测试的页面结构跟你的不一样。
> 
> PS：如果你确定是刚刚下载并安装的知网插件的话。
> 
> 否则，先使用上面链接提到的方式确保你的知网插件是最新的。

![image](https://github.com/Kenshin/simpread/assets/125173405/8c74eb72-16ba-4f02-b475-2eccf3ab560f)
![image](https://github.com/Kenshin/simpread/assets/125173405/efce26fe-d43a-4297-994c-c75eea4a38b4)
![image](https://github.com/Kenshin/simpread/assets/125173405/e9b9c42b-116a-4121-a76a-d02789407ed2)

**Comment by Kenshin** [comment]
@chenshinshi

我稍后再确认下，如果我这边没问题的话，就说明我用的知网版本跟你不一样。

如果你有导出诉求的话，可以使用 https://github.com/Kenshin/simpread/discussions/2852 修改标题。

**Comment by chenshinshi** [comment]
> @chenshinshi
> 
> 我稍后再确认下，如果我这边没问题的话，就说明我用的知网版本跟你不一样。
> 
> 如果你有导出诉求的话，可以使用 #2852 修改标题。

好的，修改标题可以暂时解决我的问题，辛苦测试！

**Comment by PenguinWang123** [comment]
知网标题还是识别不正确，之前您更新知网插件后有段时间确实能正确识别标题了，但这两天发现又不行了，又变成“全文阅读”了

网址：https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKgchrJ08w1e7ZCYsl4RS_3ieSAMOT97BTQVH_n5oc1N-t_PLuCNszGXUHVD3zanFVHykzlYGwHaR&uniplatform=NZKPT
<img width="683" alt="截屏2023-06-09 21 47 00" src="https://github.com/Kenshin/simpread/assets/117373536/8acdc07b-df46-4b0b-a4ca-eda6676071aa">

**Comment by Kenshin** [comment]
@PenguinWang123 

好吧 😂 我有时间再确认下（我打开知网还是很麻烦的 😂

**Comment by PenguinWang123** [comment]
> @PenguinWang123
> 
> 好吧 😂 我有时间再确认下（我打开知网还是很麻烦的 😂

好的辛苦！
