### ISSUE TITLE
关于 Obsidian 的标注同步疑问

### ISSUE THREAD

**Issue by zqz365001** [Kenshin/simpread#5478]
### 描述这个错误

edge浏览器中标注，然后自动导入到obsidian中。
能正常在原始网页上标注。但是点链接跳转回localhost开头的本地的网页上下文，发现只有一个标注  或者 就没有标注。

### 复现步骤

1.正常网页标注
![image](https://user-images.githubusercontent.com/27180737/232732274-b067e744-a156-47d1-acdf-32feb5ff12ac.png)
2.obsidian中的标注数据 
![image](https://user-images.githubusercontent.com/27180737/232732162-c5f732d3-4de6-44ac-ba75-2f8b88a8283a.png)
3.能跳转回在localhost开头的本地网页，但是没有本地网页的标注和跳转上下文。
![image](https://user-images.githubusercontent.com/27180737/232732532-69a4b9f3-9b0b-4f3e-be25-34870813d691.png)

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)

### 发生问题的网址

https://cj.sina.com.cn/articles/view/5617175604/14ecf4c3401902dxpz

**Comment by Kenshin** [comment]
> 没有本地网页的标注

应该是 output 中对应 HTML 没有更新或者 `simpread_config.json` 没有更新。

你可以试试（仅测试时使用，正常无需这么操作）：重启浏览器，然后在这个页面添加一个新的标注，看看 `simpread_config.json` 是否更新了，如果更新了再打开 `localhost:7026/reading/119` 看看是否正常？

**Comment by zqz365001** [comment]
1. 操作了下，发现simpread_config.json有更新，但是只有第一个是有标注的，后面的标注就不更新。
![image](https://user-images.githubusercontent.com/27180737/232753572-726432ef-fac6-430c-ad7d-9d9a8a4ced9b.png)


2. 并且还发现新的问题。。。  再次回到原始网页标注处，右边标注的链接失效，点击无法跳转到标注的文本处，而且标注的文本也出现标注残缺（与obsidian中标注的内容不符）。
![image](https://user-images.githubusercontent.com/27180737/232752972-f63dee65-c3e6-428b-9627-d56d4b9429ca.png)

3. obsidian中的内容  
![image](https://user-images.githubusercontent.com/27180737/232753159-b4cc1ad5-c34e-4317-a5e7-1e0b38621820.png)

**Comment by zqz365001** [comment]
> > 没有本地网页的标注
> 
> 应该是 output 中对应 HTML 没有更新或者 没有更新。`simpread_config.json`
> 
> 你可以试试（仅测试时使用，正常无需这么操作）：重启浏览器，然后在这个页面添加一个新的标注，看看 是否更新了，如果更新了再打开 看看是否正常？`simpread_config.json``localhost:7026/reading/119`

我是你较早的粉丝，一直使用1.0时期的配置，就没更改过，不知道是不是简悦2.0和以前的配置有冲突了。。。

1. 操作了下，发现simpread_config.json有更新，但是只有第一个是有标注的，后面的标注就不更新。
![image](https://user-images.githubusercontent.com/27180737/232753572-726432ef-fac6-430c-ad7d-9d9a8a4ced9b.png)


2. 并且还发现新的问题。。。  再次回到原始网页标注处，右边标注的链接失效，点击无法跳转到标注的文本处，而且标注的文本也出现标注残缺（与obsidian中标注的内容不符）。
![image](https://user-images.githubusercontent.com/27180737/232752972-f63dee65-c3e6-428b-9627-d56d4b9429ca.png)

3. obsidian中的内容  
![image](https://user-images.githubusercontent.com/27180737/232753159-b4cc1ad5-c34e-4317-a5e7-1e0b38621820.png)

**Comment by zqz365001** [comment]
> > 我是你较早的粉丝，一直使用1.0时期的配置，就没更改过
> 
> 哈哈，是老用户了。
> 
> 1.0 是没有 Obsidian 功能的，你提到的都是 2.0 的功能。
> 
> > 操作了下，发现simpread_config.json有更新，但是只有第一个是有标注的，后面的标注就不更新。
> 
> 你用了什么导入到 Obsidian 的方案？我需要相关功能的全部相关截图。

乱试把问题都解决了。
1.0的时候我是照着这篇帖子：简悦 +Logseq 个人知识库搭建 _ 从零开始完全指南，配置obsidian的。


![image](https://user-images.githubusercontent.com/27180737/232795808-91e01cd2-1459-4f99-ad8c-39f9e13e37bf.png)

![image](https://user-images.githubusercontent.com/27180737/232795932-9acde8ac-ec0b-4a43-a106-6a28c36b0af6.png)

**Comment by Kenshin** [comment]
哈哈，老用户就是不一样。👍

我关闭这个 Issues 了。
