### ISSUE TITLE
配置已更新，刷新当前页面后才能生效

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5483]
### Discussed in https://github.com/Kenshin/simpread/discussions/5482

<div type='discussions-op-text'>

<sup>Originally posted by **ningyuwhut** April 20, 2023</sup>
已经好几次遇到这种情况了，也并没有一个网页多开的现象（确认了好几遍，确实没有多开），即使刷新多次也还是同样的提示，但是同时在其他网页上使用阅读模式就没有问题，是不是还有其他情况会触发这个问题呢？
<img width="510" alt="image" src="https://user-images.githubusercontent.com/1762074/233223739-94299c6f-3e63-4047-9f8c-72cf31cb9a32.png">
</div>

**Comment by Kenshin** [comment]
@ningyuwhu

嗨，请不要在非 Issues 的位置提问，我帮你新建了一个 Issues 

***

这个情况肯定是因为 URL 多开造成的。
但无论如何都可以使用重启浏览器解决。

**Comment by ningyuwhut** [comment]
请教一下，什么算是URL多开呢，出问题的页面在浏览器上确实是只打开了这一个tab，没有打开多个tab的情况。
另外，我第一次重启浏览器也并没有解决，重启第二次才解决。
另外，提issue的话像我这个问题应该选择下面哪种呢，提交bug吗，感觉也不太符合呀
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/1762074/233243318-1024836d-ead5-4e94-8d33-b4d8b116d42a.png">

**Comment by Kenshin** [comment]
> 什么算是URL多开呢

比如 https://sspai.com/post/69972 打开了多次，类似这样

<img width="492" alt="image" src="https://user-images.githubusercontent.com/81074/233250921-73bbb8a3-32e4-4917-ab62-1b2c828baad2.png">

> 提issue的话像我这个问题应该选择下面哪种

提 Bug 就行，其实没有那么严格，随便找一个也都一样。 😂

但你之前在 https://github.com/Kenshin/simpread/discussions 提问是不对的，因为 https://github.com/Kenshin/simpread/discussions 属于简悦的知识库（文档），所以并不适合提 Issues。
