### ISSUE TITLE
一直在显示请先授权并设置保存的page

### ISSUE THREAD

**Issue by baseoline** [Kenshin/simpread#5485]
### 描述这个错误

一直在显示请先授权并设置保存的page

### 复现步骤

![image](https://user-images.githubusercontent.com/131428202/233543847-230ae57d-f79b-4898-8d23-6dd938eaca2f.png)

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://www.bilibili.com/read/cv22085685

**Comment by Kenshin** [comment]
然后你没有选择打开吗？

**Comment by baseoline** [comment]
我选择了打开 然后
![image](https://user-images.githubusercontent.com/131428202/233625270-63795ae9-1a68-4d09-b90e-c4be50d25491.png)
我点击了授权之后
![image](https://user-images.githubusercontent.com/131428202/233625309-005dbd41-e4c5-4d6a-85f2-9ec9347d7243.png)
然后我保存了，再用nt快捷键还是会回到最开始的让我先授权

**Comment by Kenshin** [comment]
使用 https://www.yuque.com/kenshin/simpread/wwk65u#ERFLg 解决。

**Comment by baseoline** [comment]
![image](https://user-images.githubusercontent.com/131428202/233629059-e525f8a1-4cb6-4115-b797-8b2d6127fdb2.png)
![image](https://user-images.githubusercontent.com/131428202/233629338-c0ac5376-b07d-4ceb-a697-f20100f4f83b.png)
![image](https://user-images.githubusercontent.com/131428202/233629399-75977f4b-9ee4-40a7-82f7-b79e2671b56b.png)
![image](https://user-images.githubusercontent.com/131428202/233629444-330eb8c1-9709-40c0-846a-3b8275dc6c6d.png)
请问我这有什么不对嘛

**Comment by baseoline** [comment]
老大，我搞了六七个小时了，还是授权失败，大大救命

**Comment by baseoline** [comment]
上面我发现了pageid的错误，但是改了过来还是不可以

**Comment by Kenshin** [comment]
你之前一直在问的是导入到 Notion…

所以，这个功能成功了吗？

只有 Notion 成功了，才能继续设置 Notion 辅助增强插件。

**Comment by baseoline** [comment]
这个导入到notion没有成功，但是保存到notion可以成功
![image](https://user-images.githubusercontent.com/131428202/233650006-63bc8120-ad83-4005-ad8e-1c2a6ee261c9.png)

**Comment by Kenshin** [comment]
> 导入到notion没有成功

那就先禁用 导入到 Notion 插件

> https://github.com/Kenshin/simpread/issues/5485#issuecomment-1517711356

还有将你申请的 Token 链接到 Notion
