### ISSUE TITLE
图片无法显示，没有办法查看图片内容

### ISSUE THREAD

**Issue by sentimentIteration** [Kenshin/simpread#5486]
### 描述这个错误

我本身想要快速添加文章/视频到“稍后读”中，于是去查看帮助

查阅帮助的网址为：
http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%88%9b%e5%bb%ba%e5%bf%ab%e6%8d%b7%e6%96%b9%e5%bc%8f

我在这个网址中学习如何快速添加到“稍后读”相关内容时，发现无法查看文章中的图片，导致我没有办法知道如何具体操作。
图片如下：
![image](https://user-images.githubusercontent.com/101542405/233758299-4011c0cb-2e4c-423a-9a43-9b2aa592b544.png)
![image](https://user-images.githubusercontent.com/101542405/233758315-806aff1f-0df5-4af5-9383-9c5435ae609e.png)
点击图片之后，出现的界面如下：
![image](https://user-images.githubusercontent.com/101542405/233758322-c0099735-af13-41d9-9541-741769599aac.png)
这种绿色的图片，
![image](https://user-images.githubusercontent.com/101542405/233758357-b90dd0c8-222c-4365-9a76-6424d1e3c891.png)
点击之后结果如下：
![image](https://user-images.githubusercontent.com/101542405/233758363-f3f1b27d-e1d4-4e5a-a974-4b711d09ea53.png)

### 复现步骤

进入网址：http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80?id=panel%e6%a0%8f

然后就出现了我上述问题

### 其他相关说明

我想要知道如何能够轻松快捷的让图片清晰的显示出来。
并且帮助网站的所有图片在我的edge上都不能正常显示出来。

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.58 (正式版本) (64 位)

### 发生问题的网址

http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB-%E5%A4%9A%E7%A7%8D%E5%B8%83%E5%B1%80?id=panel%e6%a0%8f

**Comment by Kenshin** [comment]
感觉像你的 DNS 有问题，试试更换 DNS 或者用另外的浏览器试试？

还有也可能跟你是否开「全局」有关系。

你可以试试直接访问 https://s1.ax1x.com/2020/11/09/B7jSFe.md.png
