### ISSUE TITLE
打开少数派文章自动进入阅读模式怎么关闭？

### ISSUE THREAD

**Issue by Ronny200** [Kenshin/simpread#5492]
### 描述这个错误

配置了同步方案后，每次进入少数派文章就会自动打开阅读模式，其他网站还没发现

要如何关闭？在设置里面没有开启自动进入阅读模式的功能，也试过开启再关闭。

### 复现步骤

导入过基础版配置库，没有其他改动了

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

少数派

**Comment by Kenshin** [comment]
emmm 

看现象应该是把少数派加入到白名单里面了…

选项页 → 高级设定 → 白名单，看看有没有相关设置？

PS：简悦的配置库方案并没有内置这种方案。
