### ISSUE TITLE
进入阅读模式右上角的工具条经常消失咋办？

### ISSUE THREAD

**Issue by Ronny200** [Kenshin/simpread#5496]
### 描述这个错误

那个工具条可以修改标题，开启连续标注等等，一般我进网站后就会先修改标题，不然标题太长了。
不知道怎么回事，好像是我改成离线html后，进入阅读模式就发现那个工具条不见了，需要标注一下才会出现。这样保存下来的html
名字太长了，或者有什么办法让保存html读取的文件名是正文的h1标题吗？

### 复现步骤

进入阅读模式右侧没有工具条
开始标注工具条出现，可以看到工具条和标注的记号

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

sspai.com

**Comment by Kenshin** [comment]
😂

1. 你说的右上角的「条」是专门当加入稍后读（或标注）时才有的标注侧栏。
2. 没有加入稍后读或标注前，当然没有那个「条」了。

如果你在 ➋ 的时候修改标题，可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 来实现修改标题或其它地方的需求。

**Comment by Kenshin** [comment]
> 写了个脚本自动将html中图片下载到本地然后替换链接

哈，不错，蹲个脚本。

离线 HTML 是没问题的，你遇到了什么问题，可以详细说说。

**Comment by Ronny200** [comment]
> > 写了个脚本自动将html中图片下载到本地然后替换链接
> 
> 哈，不错，蹲个脚本。
> 
> 离线 HTML 是没问题的，你遇到了什么问题，可以详细说说。

离线html最大的问题就是图片=。=，base64稍微图片多一点的话，标注的时候就会不断转码。
我觉得理想状态是离线下来后类似textbundle，但是如果从阅读和看批注的感觉上来说还得是html

**Comment by Kenshin** [comment]
> 离线html最大的问题就是图片=。=，base64稍微图片多一点的话，标注的时候就会不断转码。

你的意思是指：在标注时也自动化导出离线图片？如果是的话，确实有这个问题。

不过，也可以通过 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件变相解决，细节 https://github.com/Kenshin/simpread/discussions/3596#discussioncomment-2441614
