### ISSUE TITLE
每个网页都需要重新设置assets+md

### ISSUE THREAD

**Issue by lopel** [Kenshin/simpread#5497]
### 描述这个错误

每次从一个新的网页进入阅读模式，每次重新设置assets+md模式（进入新页面选中按钮会处于未选中），同时路径会变成默认的obsidianvalue，新的网页文章每次进入阅读模式，都要重新设置

### 复现步骤

![image](https://user-images.githubusercontent.com/59417870/234140859-6fde085b-7733-40af-a9b1-5f2a5fed7b19.png)
这里不能保存设置，刷新就会丢失
比如这次进入一个知乎页面阅读模式，进入导入obsidian选项，勾选assets+md方式，设置好根目录。点保存，重点来了，下面写了请修改完刷新此页面，完全不行，一刷新就还原，得重新设置。现在有个苟且的方式：每次保存完设置后，关闭--立马使用assets+md 导入，才能有一次机会使用md+asset导入到obsidian

### 操作系统

win10_64_22H2

### 浏览器

谷歌浏览器112.0.5615.138（正式版本） （64 位）

### 发生问题的网址

https://www.sohu.com/a/253931162_160923

**Comment by Kenshin** [comment]
> 每次从一个新的网页进入阅读模式，每次重新设置assets+md模式（进入新页面选中按钮会处于未选中），同时路径会变成默认的obsidianvalue，新的网页文章每次进入阅读模式，都要重新设置

（假设）你确定这个过程设置并「点」了保存后，并刷新页面仍出现这个情况的话，接下看：

如果你使用了同步助手的自动同步功能，这算是个 Bug，解决方案 [请看这里](https://www.yuque.com/kenshin/simpread/fcw60u)。

**Comment by lopel** [comment]
感谢大佬答疑，问题解决了，同步出了问题。浏览器修改后的配置在页面刷新后，会被无情覆盖。
然后我就把同步目录下的json配置文件删了，进入插件选项页面就会提示没有配置文件，是否用浏览器配置。
选择是的，然后再生成新的配置文件，就一切走回正轨

**Comment by Kenshin** [comment]
哈，恭喜自救成功。 👍

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
