### ISSUE TITLE
AI阅读助手插件安装后AI设置选项未出现在插件触发器中

### ISSUE THREAD

**Issue by JARHEAD-LHP** [Kenshin/simpread#5498]
### 描述这个错误

![iShot_2023-04-26_00 11 25](https://user-images.githubusercontent.com/70339118/234339602-7d052a8d-fce0-4450-b185-a2d5d90f32c0.png)
![iShot_2023-04-26_00 11 39](https://user-images.githubusercontent.com/70339118/234339658-3ac71920-ca7c-45dc-838f-b38798722a7e.png)

### 复现步骤

插件管理下载安装AI阅读助手插件；
安装后AI设置选项未出现在插件触发器中，无法找到设置入口。

### 操作系统

macos

### 浏览器

edge112.0.1722.58正式版

### 发生问题的网址

https://mp.weixin.qq.com/s/UckAhDSnkTeh6LjhS88RAw

**Comment by Kenshin** [comment]
嗯？刚要回复你，已经解决了这个问题？

**Comment by JARHEAD-LHP** [comment]
@Kenshin 解决了，搜了一下以前的issue有类似问题，我在插件管理器中导入插件就好了

**Comment by Kenshin** [comment]
okay 问题是你描述中提到了【插件管理器】... 我以为你已经使用它安装了 😂

**Comment by HopeLHP** [comment]
> okay 问题是你描述中提到了【插件管理器】... 我以为你已经使用它安装了 😂

哈哈哈我指的【插件管理】是在扩展界面安装了，我没有在阅读模式界面右下角的插件管理器中安装并导入。

**Comment by Kenshin** [comment]
😅 😂 🌚
