### ISSUE TITLE
360极速浏览器安装无按钮

### ISSUE THREAD

**Issue by KuiYang2017** [Kenshin/simpread#55]
不管是卸载还是重装均不显示按钮

版本9.0.1.132

内核版本55

**Comment by Kenshin** [comment]
我在 mac 上，下午切到 win 下试试，请问你是否在 少数派上面评论了同样的问题？

**Comment by Kenshin** [comment]
@KuiYang2017 
Sorry，下午有事情，暂时没有切到 win 上面... 

不显示按钮是正常的，只有在适配的网页上才会在地址栏的右侧显示。如图

![](http://p5.qhimg.com/t0152e2e23fad6462d5.png)

比如安装后，打开 https://sspai.com/post/39491 这个页面。

PS：如果已按照我说的步骤操作过，请忽略... 我会在确认后再联络你。 😄

**Comment by KuiYang2017** [comment]
是的，少数派也提给你了。还是存在一样的问题

**Comment by Kenshin** [comment]
@KuiYang2017 
刚刚用低版本测试了一下，没有问题（地址栏右侧），发布到 360极速浏览器的时候用的是高版本。
 
![img_4308](https://user-images.githubusercontent.com/81074/28704172-70612bf6-739b-11e7-97db-987f505bb0de.PNG)

**Comment by KuiYang2017** [comment]
嗯嗯  我也不知道咋回事  现在高版本也没问题了

**Comment by Kenshin** [comment]
@KuiYang2017 
okay 没问题就好。 😄
