### ISSUE TITLE
新站适配：蚁阅

### ISSUE THREAD

**Issue by tianya778** [Kenshin/simpread#5500]
### 需要适配的新站

https://rss.anyant.com/

### 有需要请描述这个站的性质

这是一个rss订阅网站，我喜欢拿来配合着简悦使用，但是用蚁阅打开阅读模式加入稍后读，打开稍后读时，解析是失败的。
![Snipaste_2023-04-26_09-19-53](https://user-images.githubusercontent.com/32615715/234441671-0b178e5d-378d-4267-88bc-56a4541b3e77.png)

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

首先，简悦会官方适配蚁阅，目前虽然可以直接进入阅读模式，但标题等并没有完美解析。

其次，你提到的问题是因为蚁阅是动态加载的页面，没法通过你提到的方式解析，但可以使用 [此方式](https://www.yuque.com/kenshin/simpread/wkswh7) 解决，前提是需要安装同步助手。

**Comment by tianya778** [comment]
我尝试了同步助手，按照解析助手的教程设置了，还是显示解析失败，但没事，静候官方适配源。喜欢简悦的简洁，也喜欢你们的态度。

**Comment by Kenshin** [comment]
谢谢。

PS：官方适配只能让页面更完善，并不能实现你说的在稍后读查看的诉求，只有配置知识库后才行。

***

我随便加了稍后读，是可以正常使用的（暂时忽略标题的问题，等适配后就能完整显示标题了）

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/81074/234549263-0e77fbef-efd6-4f25-b9ba-f93766567fe3.png">

这是在蚁阅查看时的效果

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/81074/234549355-51234899-3394-4d20-9885-1692d0992331.png">

**Comment by tianya778** [comment]
好的，感谢回复，应该是我的原因。折腾了一晚上本地解析还是没成功，暂时放弃了😂

**Comment by Kenshin** [comment]
没事。

如果有需要的话，可以告诉我，哪个步骤出现了问题？

**Comment by tianya778** [comment]
不用了，今天静下心好好设置了一下，问题解决了(*^_^*)

**Comment by Kenshin** [comment]
哈，解决就好。  👍

**Comment by tianya778** [comment]
今天顺便尝试了一下简悦的开放平台，配置了我的ios ipad的稍后读，真的是太喜欢这个艺术品了。
另外，我平常有会使用思源笔记，不知道能不能在后续加入到功能栏可以导出？
总的来说很喜欢，并且已经和我的日常融入在一起了。
o(*￣▽￣*)ブ

**Comment by Kenshin** [comment]
喜欢简悦的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by tianya778** [comment]
已经好评了。
另外，我记得知识库设置里有一个注意事项是坚果云要优先于简悦同步助手启动是吧？
我看了这个[教程](https://zhuanlan.zhihu.com/p/97527076#:~:text=%E5%B8%B8%E8%A7%84%3E%E5%8B%BE%E9%80%89%3E%E4%BD%BF%E7%94%A8%E6%9C%80%E9%AB%98%E6%9D%83%E9%99%90%E8%BF%90%E8%A1%8C,%E8%A7%A6%E5%8F%91%E5%99%A8%3E%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE%3E%E5%8B%BE%E9%80%89%3E%E5%BB%B6%E8%BF%9F%E4%BB%BB%E5%8A%A1%E6%97%B6%E9%97%B4%3E%E9%80%89%E6%8B%A930%E7%A7%92%EF%BC%88%E8%AF%A5%E9%80%89%E6%8B%A9%E5%8F%96%E5%86%B3%E4%BA%8E%E7%94%B5%E8%84%91%E5%90%AF%E5%8A%A8%E5%BF%AB%E6%85%A2%EF%BC%8C%E8%8B%A530%E7%A7%92%E5%86%85%E6%A0%A1%E5%9B%AD%E7%BD%91%E5%8F%AF%E6%88%90%E5%8A%9F%E8%BF%90%E8%A1%8C%EF%BC%8C%E5%88%99OK%EF%BC%8C%E5%90%A6%E5%88%99%E9%80%82%E5%BD%93%E5%BB%B6%E9%95%BF%E6%97%B6%E9%97%B4%E3%80%82)，把简悦启动的时间推迟了30s，感觉教程里面也可以提示用户怎么设置这个？

**Comment by Kenshin** [comment]
不用那么特别在意顺序的事情，主要怕配置互相覆盖。

如果你的使用场景是启动浏览器的话，同步助手与坚果云先后没有那么大的问题，只要在浏览器的简悦使用前确保他们都启动了就行。

**Comment by tianya778** [comment]
我这里现在有一个问题，就是我保存的稍后读，误读了本地的内容，就导致，我收藏的内容和稍后读的内容打开有冲突。
![image](https://user-images.githubusercontent.com/32615715/235342659-4919068f-b48f-4616-b944-07194c1bf6e9.png)
内容就不是标题显示的那篇内容。

**Comment by tianya778** [comment]
> 

然后我收藏的方式是从手机端收藏的。

**Comment by Kenshin** [comment]
> 是我保存的稍后读，误读了本地的内容，就导致，我收藏的内容和稍后读的内容打开有冲突。

那就是你之前提到 https://github.com/Kenshin/simpread/issues/5500#issuecomment-1527460638 造成的。

也就是在：运行同步助手 + 坚果云之前就操作了数据导致被覆盖了。（因为坚果云仅会判断通过 simpread_config.json 的日期来判断哪个的新的）

你可以使用：

1. 坚果云的 [历史记录](https://www.yuque.com/kenshin/simpread/ikl1dnokvxakrw2a)
2. 简悦自带的 [历史记录](https://simpread.pro/docs/#/%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95)

来还原你的数据。

同时，当标号错误时，也可以使用 数据中心的 [查找重复数据](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%E6%9F%A5%E6%89%BE%E9%87%8D%E5%A4%8D%E6%95%B0%E6%8D%AE) 来精细修复。

**Comment by tianya778** [comment]
那我想问一下，就是我的电脑处于待机状态，或者关机状态，我用手机进行收藏，然后使用电脑的稍后读之前，打开坚果云和同步助手，这样应该可以吧？
o(*￣▽￣*)ブ

**Comment by Kenshin** [comment]
> 我用手机进行收藏，然后使用电脑的稍后读之前，打开坚果云和同步助手，这样应该可以吧？

是的 😄

这个流程你可以这么理解：

坚果云客户端会判断坚果云服务器上和本地的 `simpread_config.json` 哪个是新的（根据文件的更新日期），然后新的会覆盖旧的。

**Comment by tianya778** [comment]
新收藏的文章在简悦开放平台的阅读列表中显示空白，不知道是什么原因，之前的文章部分还可以看。
![image](https://user-images.githubusercontent.com/32615715/235363136-8ce20e8a-5be6-4318-8bd1-7eb4c6b0962f.png)
简悦阅读列表的读取机制我有点无法理解。

**Comment by tianya778** [comment]
![image](https://user-images.githubusercontent.com/32615715/235363187-e39aac50-5029-445a-a5d1-b5a84ce73c9a.png)
导出应该没设置错误
![image](https://user-images.githubusercontent.com/32615715/235363205-1f0e4224-494d-435b-9ecb-5530a2a1ae78.png)

**Comment by tianya778** [comment]
阅读列表有重复，我将导出的自动化中的md删了。配置了外部链接，并把output文件夹的内容清空，现在重新收藏的话，正常了(*^_^*)
![image](https://user-images.githubusercontent.com/32615715/235365426-17592b08-93dd-416d-821b-d904703638e9.png)

**Comment by tianya778** [comment]
不知道是否是收藏的太快，坚果云的output文件已经有html文件了，但是阅读列表的后三个文章显示空白了。
![image](https://user-images.githubusercontent.com/32615715/235365920-66aa1325-90b2-4b92-a4c7-8b4b06bbec55.png)
![image](https://user-images.githubusercontent.com/32615715/235365928-5e2261cb-b4bd-4a43-ae44-e3a57834bac2.png)
/(ㄒoㄒ)/~~

**Comment by Kenshin** [comment]
> 不知道是否是收藏的太快，坚果云的output文件已经有html文件了

具体怎么收藏的？详细说下你的操作步骤。

**Comment by tianya778** [comment]
我当时操作后面没显示的三篇文章时，操作的条件大概如下：
除了内部链接，其他的该配置的都配置了。
三篇文章我都是分别先打开阅读模式，然后dd，也跳出了自动化成功的提示。

今天我配置了内部链接，但没有连续收藏文章，把三篇坚果云里的未显示的文章都删了，然后重新试了一篇，现在的话，感觉没啥问题。
大概就是这样子。o(*￣▽￣*)ブ

**Comment by tianya778** [comment]
补充一下，刚刚又去测试了一下，连着收藏了两篇，流程都是打开阅读模式然后dd，然后阅读列表里面那两篇文章又是空白了，测试的博客站点网址：https://www.pseudoyu.com/

**Comment by tianya778** [comment]
我拿我自己的博客测试了一下，我的博客连续收藏就没有问题，但是测试的博客收藏了就是空白。
这是我的[博客](https://blog.awumiao.org)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5500#issuecomment-1529519766 

这个操作跟你遇到的问题无关。

> 连着收藏了两篇，流程都是打开阅读模式然后dd

1. 建议在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。
2. 可以同时打开不同的 URL，但先收藏一篇，等提示完毕后，再收藏另外一篇。

看看能否复现？

**Comment by tianya778** [comment]
在隐身模式下使用简悦就正常了😂下面是我的扩展截图：
![image](https://user-images.githubusercontent.com/32615715/235622553-7b9a1d3f-81d0-4757-bd4c-98049af53fca.png)
不知道是哪个扩展影响了简悦？

**Comment by Kenshin** [comment]
二分法，几次就能找到。

一般来说，下载相关或者改变页面内容的嫌疑比较大。

**Comment by Kenshin** [comment]
> 每日订阅的话之前我把同步助手关了反而能够每日发送，现在设置好了反倒不会发送了。

应该没关系… 😂 把自动同步关闭的话，如果坚果云云端没有得到最新的配置文件，肯定没法发送每日回顾。

**Comment by tianya778** [comment]
![image](https://user-images.githubusercontent.com/32615715/236470257-3fb9e371-0ddc-4212-85cb-e9f5bf12bfec.png)
我重新配置了谷歌邮箱之后，每次发送邮件都会报错

**Comment by Kenshin** [comment]
Gmail 可能有点问题（网络问题），建议试试 QQ 邮箱。

**Comment by tianya778** [comment]
好的，换了outlook，正常了，想问问蚁阅大概还要多久会在站点集市上架？

**Comment by Kenshin** [comment]
这两天

**Comment by tianya778** [comment]
来催更啦！更新否？

**Comment by Kenshin** [comment]
@tianya778 

本周末更新~

**Comment by tianya778** [comment]
好的，静候

**Comment by Kenshin** [comment]
抱歉，隔了这么就才想起来 😂

蚁阅已经适配了，如何使用 https://github.com/Kenshin/simpread/discussions/5602

我关闭这个 Issues 了，如有任何问题可随时在这里跟我讨论。
