### ISSUE TITLE
简悦稍后读打不开，一片白

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#5502]
### 描述这个错误

无论从扩展端、网页右键、edge应用打开都是一片白。但是在整个扩展界面都是好的，包括账户、插件管理、共通等等。
<img width="1512" alt="iShot_2023-04-26_13 44 28" src="https://user-images.githubusercontent.com/70339118/234481114-9fd9ca91-2938-44c0-93db-59f7187ec546.png">

### 复现步骤

打开稍后读

### 其他相关说明

- 重装扩展没用，在其他浏览器安装后不导入自己的配置可以打开稍后读，但是导入自己的配置后就打不开。可能是我某方面的配置问题，不确定配置了啥。
- 目前情况下在网页打开阅读模式无法启用标注。

### 操作系统

macos

### 浏览器

edge112.0.1722.58正式版

### 发生问题的网址

无

**Comment by HopeLHP** [comment]
重装扩展没用，在其他浏览器安装后不导入自己的配置可以打开稍后读，但是导入自己的配置后就打不开。可能是我某方面的配置问题，不确定配置了啥。

**Comment by Kenshin** [comment]
应该是你的配置文件出错了，用[此方式](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e4%bf%ae%e5%a4%8d%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6)

**Comment by HopeLHP** [comment]
可能的确是收藏稍后读的某个动作导致配置文件出错了。我在扩展端稍后读下面的未读列表那里删掉我刚收藏的文章（导致出错的文章）后就可以进入稍后读了。

**Comment by Kenshin** [comment]
> 我在扩展端稍后读下面的未读列表那里删掉我刚收藏的文章

okay 解决就好。使用 https://github.com/Kenshin/simpread/issues/5502#issuecomment-1522857074 提到的方式也一样可以解决。
