### ISSUE TITLE
我想用简悦把页面剪藏到flow us里请问应该怎么设置？

### ISSUE THREAD

**Issue by xingyun2022** [Kenshin/simpread#5503]
### 请描述你的建议或任何内容

按照flow us的说明没找到简悦的设置界面，是在系统更新中把这个功能去除了吗？

**Comment by Kenshin** [comment]
嗨 https://github.com/Kenshin/simpread/discussions/4772 应该已经说的很清楚了。

<img width="899" alt="image" src="https://user-images.githubusercontent.com/81074/234747665-1814989f-e91d-4aef-9882-4f4a58201035.png">
