### ISSUE TITLE
我买了高级会员，但是一直兑换不了，卡在这个页面

### ISSUE THREAD

**Issue by Henry2an** [Kenshin/simpread#5505]
### 描述这个错误

![image](https://user-images.githubusercontent.com/131963750/234830250-8f7e5f56-a3f4-4394-83b4-6e4ad5a1eab4.png)

### 复现步骤

我买了高级会员，但是一直兑换不了，卡在这个页面，转到100没成功。

### 操作系统

win10

### 浏览器

360极速

### 发生问题的网址

1

**Comment by Kenshin** [comment]
嗨

1. 这个服务在阿里云上，所以正常网络就能使用，而你做的反而会出现问题。
2. 重新绑定时提示什么？
3. 不建议使用 360极速版，请使用正常的 Chrome 内核浏览器，哪怕是 Edge。（我不确定是否是这个问题，因为没有其他用户反馈过，但 Edge 是更好的选择）
