### ISSUE TITLE
关于阅读模式下导出pdf图片显示不出来的问题

### ISSUE THREAD

**Issue by BsklWssy** [Kenshin/simpread#5506]
### 描述这个错误

我是有这样的一个需求 就是进入阅读模式 然后把pdf导入到zotero里面 但是简悦不支持直接导入zotero 所以我就直接绕一步 先导出为pdf 再手动拖进zotero里面 但是用了高级模式下面的导出pdf功能之后 导出的pdf里面图片不能完整显示 总是有几个图片显示不出来 类似下面（1.网页已经全部加载完成了 图片也全部刷新出来了 2.在阅读模式下面图片也是全部显示的 导出pdf之后就会有几张图片是这样的 3.这个网页是微信文章界面）
![image](https://user-images.githubusercontent.com/32919368/234851277-ab91762a-1077-48d8-800c-3dd3979fb972.png)

### 复现步骤

1.进入网页
2.进入阅读模型
3.导出为pdf

### 操作系统

win

### 浏览器

chrome

### 发生问题的网址

https://mp.weixin.qq.com/s/VF6adVwHAUCGjQND5ofWjQ

**Comment by Kenshin** [comment]
选项页 → 服务→ 增强导出，里面有个代理图床的功能，你开启它后重启浏览器后再试试。

**Comment by Kenshin** [comment]
是这个选项

<img width="887" alt="image" src="https://user-images.githubusercontent.com/81074/235040522-85c9b488-78f0-4be5-91fb-820dc7c72f3f.png">

**Comment by BsklWssy** [comment]
> 是这个选项
> 
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/81074/235040522-85c9b488-78f0-4be5-91fb-820dc7c72f3f.png">

我尝试了一下 还是不行 导出来的pdf里面有的图片显示不出来 而且还是随机的

**Comment by Kenshin** [comment]
emmm 估计跟你的网络环境有关系。

你应该试试 https://github.com/Kenshin/simpread/discussions/3887 这个方案。

PS：如果仅仅只是这一个有问题的话，建议忽略它 😂
