### ISSUE TITLE
CSDN单个页面不可使用插件，麻烦看一下，我也是第一次遇到，csdn其他页面无此问题。页面地址如下

### ISSUE THREAD

**Issue by Hou-yanbin** [Kenshin/simpread#5507]
### 描述这个错误

CSDN单个页面不可使用插件，麻烦看一下，我也是第一次遇到，csdn其他页面无此问题。页面地址如下https://blog.csdn.net/weixin_43092232/article/details/104555086
很奇怪，其他csdn的文章可以，第一次遇到来反馈一下哈。

### 复现步骤

1

### 其他相关说明

1

### 操作系统

Windows11

### 浏览器

chrom

### 发生问题的网址

https://blog.csdn.net/weixin_43092232/article/details/104555086

**Comment by Hou-yanbin** [comment]
嗯呢，不解决也没事，影响不大，遇到了来反馈下哈

**Comment by Hou-yanbin** [comment]
![image](https://user-images.githubusercontent.com/58129352/235070186-46865b72-e79b-4c45-995d-ffddca2a7989.png)
可以了，不知道啥情况，zu昨天不可以今天试了试可以了，

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题 😂

你可以试试在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

PS：刚测试完就发现你 Close Issues 了，虽然确实不影响其它方式的使用。 😁

**Comment by Hou-yanbin** [comment]
哈哈，谢谢开发者

**Comment by Kenshin** [comment]
小事情 😄
