### ISSUE TITLE
导入备份的配置文件，整个卡住了

### ISSUE THREAD

**Issue by Nadir-Echo** [Kenshin/simpread#5508]
### 描述这个错误

系统重装，导入配置文件后，整个插件卡住了
![image](https://user-images.githubusercontent.com/86950349/235116372-d53f7a42-6414-4381-8b72-d33a227f02b2.png)

### 复现步骤

系统重装，导入配置文件后，整个插件卡住了。

### 操作系统

windows10

### 浏览器

brave

### 发生问题的网址

-

**Comment by Nadir-Echo** [comment]
一直处于这个画面，而且，我卸了几次每次重装都是一样

**Comment by Kenshin** [comment]
嗨

首选，重启同步助手。

如果仍无法解决，则说明配置文件出错了，使用 [数据修复](https://simpread.pro/docs/#/%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83?id=%e4%bf%ae%e5%a4%8d%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6) 来修复。

**Comment by Nadir-Echo** [comment]
![image](https://user-images.githubusercontent.com/86950349/235140037-b3d2532a-33ff-4982-adf1-736bae63e4d2.png)
显示这个，好像不行。重启也试了，不行欸

**Comment by Nadir-Echo** [comment]
我最开始时没有登陆高级账户，直接同步以前的配置文件，就是那个界面一直打转。我卸载以后，重新安装，登录了高级账户后，使用坚果云同步配置文件也是一样会出问题。

**Comment by Kenshin** [comment]
这个提示说明对应的配置文件里面的 UID 不是高级账户。

如果你很久没用简悦或者简悦中没有什么特别重要的个人数据的话，建议重新安装简悦然后修改高级账户 UID 的方案。
