### ISSUE TITLE
jsbox内，用简悦下载微信公众号文章至dropbox，保存的文件名前后有不可见字符。

### ISSUE THREAD

**Issue by zhcbbs** [Kenshin/simpread#5509]
### 描述这个错误

jsbox内，用简悦下载微信公众号文章至dropbox，保存的文件名前后有不可见字符。

<img width="632" alt="image" src="https://user-images.githubusercontent.com/4313046/235313416-66ed9afe-bca4-427d-805f-450fbfd85903.png">

### 复现步骤

1.拷贝微信公众号文章链接
2.打开jsbox，点击简悦.阅读器
3.点击图标，保存至dropbox

### 操作系统

ios

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s/gWh0X3pJCDmQX_xuJXRL_g

**Comment by Kenshin** [comment]
应该只是个例吧，其它网页有这个问题吗？

PS：不建议折腾 JSBox 方案了，我在 https://github.com/Kenshin/simpread/issues/5510#issuecomment-1528962227 里面已经说明了。
