### ISSUE TITLE
[Translation Request] Is it possible to put the extension on open translation platform?

### ISSUE THREAD

**Issue by s-kk** [Kenshin/simpread#551]
Dear developer!
Hello!
I'm a foreign user of SimpRead, and it's been a very great extension. But one thing is that the translation of the extension wasn't perfect. I really like the app and I certainly would like to do the translation for you.
So is it possible to put app strings on some open translation platforms like Crowdin or something like that?
Thanks in advance!

**Comment by Kenshin** [comment]
I am very glad to have foreign friends of SimpRead.
Thank you also for taking the initiative to help SimpRead with his translation work.

The next version of SimpRead will have translation requirements.
If there is a need for translation, I will contact you here.

**Comment by s-kk** [comment]
Kindly thanks to your reply. And yeah, as you said, I'll wait. But please be quick cuz I dont really want to use translator on strings every time I want to change settings. 
Thanks a lot.
