### ISSUE TITLE
dropbox授权过一段时间，就会失效

### ISSUE THREAD

**Issue by zhcbbs** [Kenshin/simpread#5510]
### 描述这个错误

简悦与dorpbox链接授权后，不到一天，就会发生无法连接dropbox的问题，手动断开dorpbox授权，重新授权，才能继续使用。

### 复现步骤

1.在简悦插件中开启drobox授权。
2.正常使用中。
3.几个小时后，更新配置信息至dropbox，发现与dropbox同步失败，ios 上jsbox也无法正常保存文章至dropbox。
4.在简悦插件中强制断开dropbox授权。
5.重新授权dropbox
6.正常使用。
7.几个小时后，又会失效。

### 操作系统

macos

### 浏览器

edge

### 发生问题的网址

www.sina.com.cn

**Comment by zhcbbs** [comment]
https://github.com/Kenshin/simpread/discussions/3171

这个issue说，sl开头的token都是临时token，我获取的token确实是sl开头的。但是按照3171的说明，我断开授权，重新获取，总是sl开头的token，怎么解决这个问题，请指教。

**Comment by zhcbbs** [comment]
https://www.codemzy.com/blog/dropbox-long-lived-access-refresh-token

找到一篇文章，没太明白，但是确认了sl的token，只有4小时有效期。

**Comment by zhcbbs** [comment]
感觉原理是：现在dropbox会下发两个token，一个是access token，4小时就过期，还有一个是refresh token，是长期有效的，用refresh token可以定期获取新的access token。
这种机理下，需要简悦重新修改程序，才能适配。

**Comment by zhcbbs** [comment]
https://developers.dropbox.com/zh-cn/oauth-guide

Using Refresh Tokens 使用刷新令牌
Dropbox access tokens are short lived, and will expire after a short period of time. The exact expiry time of a token is returned by the [token](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token) endpoint (or the redirect URI in implicit grant) - but is generally long enough for a reasonable web session.
Dropbox访问令牌的有效期很短，并且会在短时间内过期。令牌的确切过期时间由令牌端点（或隐式授权中的重定向URI）返回，但通常对于合理的Web会话来说足够长。

If the token expires - throwing a 401 error - your application may simply re-authenticate as described above. If your token is expired, but the user is signed into Dropbox and their [approval is still valid](https://help.dropbox.com/installs-integrations/third-party/third-party-apps), the redirects will not require end-user input. A user’s approval remains valid until explicitly revoked.
如果令牌过期-抛出401错误-您的应用程序可以简单地按照上述方式重新进行身份验证。如果您的令牌过期，但用户已登录Dropbox并且他们的批准仍然有效，则重定向不需要最终用户输入。用户的批准在明确撤销之前仍然有效。

Applications that require offline access to the API - meaning using the API when the end user is not actively interacting through your app - will not be able to prompt for re-authorization. These apps may instead use long-lived [refresh tokens](https://oauth.net/2/grant-types/refresh-token/) can be used to obtain new access tokens.
需要离线访问API的应用程序——即当最终用户没有通过您的应用程序主动交互时使用API——将无法提示重新授权。这些应用程序可能会使用长期刷新令牌，可用于获取新的访问令牌。

When using refresh tokens, your call to the [/oauth2/token](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token) endpoint with the grant_type of authorization_code will return a short-lived access token and a refresh token, which should be securely stored.
使用刷新令牌时，对grant_typeauthorization_code的 /oauth2/token端点的调用将返回一个短期访问令牌和一个刷新令牌，应安全存储。

Note: you’ll need to include token_access_type=offline as a parameter on your Authorization URL in order to return a refresh_token inside your access token payload.
注意：您需要在授权URL中包含token_access_type=离线作为参数，以便在访问令牌有效负载中返回refresh_token。

To update your access token, call the [/oauth2/token](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token) endpoint - specifying your refresh_token as a parameter and using the grant_type of refresh_token. The endpoint will return a new short-lived access token and a timestamp indicating its expiration time.
要更新访问令牌，请调用 /oauth2/token端点-将refresh_token指定为参数并使用refresh_tokengrant_type。端点将返回一个新的短期访问令牌和一个指示其到期时间的时间戳。

Working with refresh tokens is easier with an SDK. Helper methods accept the refresh token, and manage this update of the short-lived access token for you.
使用SDK可以更轻松地使用刷新令牌。Helper方法接受刷新令牌，并为您管理短期访问令牌的此更新。

In the past, the Dropbox API used only long-lived access tokens. These are now deprecated, but will remain available as an option in the Developer console for compatibility until mid 2021.
过去，Dropbox API仅使用长期访问令牌。这些现在已被弃用，但将作为开发人员控制台中的一个选项继续提供，以实现兼容性，直到2021年年中。

For existing apps migrating to short-lived tokens, the token_access_type parameter on your authorization URL enables requesting short-lived tokens per-auth, allowing you to update your code without versioning issues in the Dropbox App Console.
对于迁移到短期令牌的现有应用，授权URL上的token_access_type参数允许按身份验证请求短期令牌，允许您在Dropbox应用控制台中更新代码而不会出现版本控制问题。

**Comment by Kenshin** [comment]
目前是这样的，Dropbox 弄一个临时的 Token 方案，很「烦人」...因为后台每隔一段时间刷新并获取新的 Token。

所以，因为这个缘故，暂时就不支持 Dropbox 了。😂

**Comment by zhcbbs** [comment]
你好，将来会有什么替代方案么，jsbox主要是在ios下使用，能透漏一下下一步的解决方案么？或者开发简悦的ios app。

**Comment by Kenshin** [comment]
1. 会有自己的 iOS（但优先级相对不是很高）
2. 其实可以使用 [收藏助手](https://github.com/Kenshin/simpread/discussions/2921) 来收藏（但没法直接导入到 Obsidian）

**Comment by zhcbbs** [comment]
好的，期待中。我目前暂时先用ios 快捷剪藏网页至ob。

**Comment by Kenshin** [comment]
> 好的，期待中。我目前暂时先用ios 快捷剪藏网页至ob。

怎么做到的？

**Comment by KKKZOZ** [comment]
> 目前是这样的，Dropbox 弄一个临时的 Token 方案，很「烦人」...因为后台每隔一段时间刷新并获取新的 Token。
> 
> 所以，因为这个缘故，暂时就不支持 Dropbox 了。😂

意思是现在只支持坚果云的配置同步了吗

 我看了下 @zhcbbs 提到的 `refresh token` 的机制，能不能设置为：把 `access token` ， `refresh token` 还有那个时间戳都保存在配置文件中，每次需要使用 `access token` 时，先通过时间戳检查 token 是否过期，没过期的话就正常访问，过期了的话，就先通过 `refresh token` 去更新  `access token` 和时间戳，再进行访问？

**Comment by zhcbbs** [comment]
现在新的token机制，程序上可以做，只是作者懒得支持了

---- 回复的原邮件 ----
| 发件人 | Liu ***@***.***> |
| 发送日期 | 2023年10月03日 11:40 |
| 收件人 | Kenshin/simpread ***@***.***> |
| 抄送人 | zhcbbs ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [Kenshin/simpread] dropbox授权过一段时间，就会失效 (Issue #5510) |

目前是这样的，Dropbox 弄一个临时的 Token 方案，很「烦人」...因为后台每隔一段时间刷新并获取新的 Token。

所以，因为这个缘故，暂时就不支持 Dropbox 了。😂

意思是现在只支持坚果云的配置同步了吗

我看了下 @zhcbbs 提到的 refresh token 的机制，能不能设置为：把 access token ， refresh token 还有那个时间戳都保存在配置文件中，每次需要使用 access token 时，先通过时间戳检查 token 是否过期，没过期的话就正常访问，过期了的话，就先通过 refresh token 去更新 access token 和时间戳，再进行访问？
