### ISSUE TITLE
Notion 公式的转换-知乎页面

### ISSUE THREAD

**Issue by githubwzb** [Kenshin/simpread#5511]
### 请描述你的建议或任何内容

对有Latex公式渲染脚本的页面如知乎，导出到notion后，无法自动转换为公式格式，而且有乱码。
举例如下https://zhuanlan.zhihu.com/p/106706044
此页面第一个公式的导出结果是
$\sigma^{2}=\frac{1}{N}\sum^{N}_{i=1}(Y_{i}-\mu)^2${2}={N}{i=1}(Y{i}-)^2
实际上应为
$\sigma^{2}=\frac{1}{N}\sum^{N}_{i=1}(Y_{i}-\mu)^2$

### 补充说明

如果没有api实现公式格式自动生成。只需把多余乱码删除，再次阅读时手动转换格式不是问题。

**Comment by Kenshin** [comment]
嗨，试试导出 Markdown 到本地，如果没问题的话（大概率）就说明是 Notion 本身的问题。

因为使用了私有 API 再加上 Notion 对导入方式公式支持的就不算太好造成的。

**Comment by githubwzb** [comment]
本地md是一样的。因为知乎使用了latex渲染脚本，所以复制内容会有乱码

**Comment by githubwzb** [comment]
也就是$\sigma^{2}=\frac{1}{N}\sum^{N}_{i=1}(Y_{i}-\mu)^2$**_{2}={N}{i=1}(Y{i}-)^2_** 中粗斜体部分

**Comment by Kenshin** [comment]
应该没问题，看下图

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/81074/235347622-acebec22-ea15-4279-9054-941b4d2e2e15.png">

支持知乎公式的方式 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

**Comment by Kenshin** [comment]
[总体、样本、总体方差、样本方差、抽样方差和标准误.txt](https://github.com/Kenshin/simpread/files/11361057/default.txt)

我把这个文件上传上来了，你可以看下。

**Comment by githubwzb** [comment]
OK了。谢谢

**Comment by githubwzb** [comment]
CSDN的公式有办法吗？

**Comment by Kenshin** [comment]
> CSDN的公式有办法吗？

只要是支持 MathJAX 的就行，但部分 CSDN 支持 katex 方案，暂时不支持。
