### ISSUE TITLE
请问遇到官方没有适配的站点该怎么办？

### ISSUE THREAD

**Issue by JIeJaitt** [Kenshin/simpread#5512]
### 请描述你的建议或任何内容

如果遇到了官方没有适配的网站只能提交网址供官方加入适配吗？我是一个计算机学生，平时需要翻阅大量个人博客，就有很多博主会对自己的博客做美化，导致简悦就无法生成阅读模式，或者生成的阅读模式也没法看，请问遇到这种情况该怎么办？

**Comment by Kenshin** [comment]
嗨，建议提交 URL 上来给我看看。

另外，一般来说，博客类的或者结构良好的页面都可以直接进入阅读模式的。

或者也可以试试 https://github.com/Kenshin/simpread/discussions/1554 提到的方式。

**Comment by Kenshin** [comment]
嗨，我看你 Close 了这个 Issues，是因为解决了？

**Comment by JIeJaitt** [comment]
> 嗨，我看你 Close 了这个 Issues，是因为解决了？

是的，谢谢大佬。我使用部分片段生成阅读模式的方式解决了大部分的需求。

**Comment by Kenshin** [comment]
哈，解决就好。 👍 

PS：五一多出去休息 😄
