### ISSUE TITLE
多页网页如何合并呈现&分区内容识别不全

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#5513]
### 需要适配的新站

1、https://www.shui5.cn/article/ee/50516.html
2、https://www.shui5.cn/article/99/111384.html

### 有需要请描述这个站的性质

第一个网站叫税屋，是财税行业比较知名的网站，也算一个法规知识库网站。其中有很多多页文章需要翻页查看，翻页似乎就是在第一页的url后面加上序号。简悦的阅读模式只能识别首页，所以想问一下没有办法针对多页网页合并识别。
第二个网站也是税屋，好像有些作者发布的文章呈现分区的形式，简悦识别的时候识别不全。我一般都手动识别，但是手动识别的区域也不是很理想，比如这个网站想要标题和文章内容，手动识别的区域就必须得包含最下面的其他文章链接。

**Comment by Kenshin** [comment]
okay 可以考虑适配。

你可以试试 https://github.com/Kenshin/simpread/discussions/1554 这个方式。

合并的话，你可以试试 https://github.com/Kenshin/simpread/discussions/3494 里面有合并的功能。

**Comment by Kenshin** [comment]
哈，解决就好。
