### ISSUE TITLE
在知乎上划选代码块标注并导出到notion会丢失代码内容

### ISSUE THREAD

**Issue by J0O0O0O0E** [Kenshin/simpread#5516]
### 描述这个错误

如图，单独点击代码块并标注是可以的，划选内容中包含代码块就不行。其他网站可以。
![image](https://user-images.githubusercontent.com/32154946/235907087-31b29c00-0400-4452-b11f-5eaf48e960f5.png)

### 复现步骤

1. 打开https://zhuanlan.zhihu.com/p/135951778
2. 进入阅读模式
3. 划选代码块部分标注
4. 导出标注到notion
5. notion中没有代码块部分

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://zhuanlan.zhihu.com/p/135951778

**Comment by Kenshin** [comment]
嗨

确实如此，简悦暂时不支持代码段内的任意标注，因为这种方式没法准确判断是否是代码。
