### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by anyiweb** [Kenshin/simpread#5518]
### 描述这个错误

无法安装某些插件，反复点击安装后没有显示安装成功
例如导入到flowus，notion增强等部分插件

### 复现步骤

1.进入插件中心
2.安装插件
3.跳转到插件中心，但未安装成功

### 操作系统

Windows11

### 浏览器

Chrome112.0.5615.121

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#plugins

**Comment by anyiweb** [comment]
录屏：
![11](https://user-images.githubusercontent.com/60560420/236235690-ef37aeea-8963-47d9-8945-b466999ec4de.gif)

**Comment by Kenshin** [comment]
嗨，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by anyiweb** [comment]
嘿你好，使用以上操作依然没有解决问题，请问应该如何操作？

无法安装的插件：导入到notion  https://simpread.ksria.cn/plugins/details/OpaogjT8KJ
![image](https://github.com/Kenshin/simpread/assets/60560420/b46633a0-13df-462b-930b-28dc17abda7a)

![image](https://github.com/Kenshin/simpread/assets/60560420/076cbed7-d032-47cf-9a9c-4e470a1683ab)

![image](https://github.com/Kenshin/simpread/assets/60560420/743331dd-7119-417e-ab6d-1b00dc85345f)

**Comment by Kenshin** [comment]
首先确认的是：你用没用同步助手的自动同步？

**Comment by anyiweb** [comment]
使用了，但已关闭同步功能。但似乎，gu关闭web端的自动同步功能后，会自动打开，请问如何彻底关闭自动同步功能？
![image](https://github.com/Kenshin/simpread/assets/60560420/6eb4d418-cb4c-4a65-b6f1-2dfcf6bc5177)
![image](https://github.com/Kenshin/simpread/assets/60560420/c9ace614-d090-4a21-823a-2fdaf14e9806)

**Comment by Kenshin** [comment]
> 使用了，但已关闭同步功能

.... 我给你的教程没有这么说（第一个截图）吧 😂

建议仔细看下我给你的教程 100% 可以解决。

***

1. 重启浏览器器，确保只有一个 Tab 不要开过多的 Tab
2. 然后按照 https://github.com/Kenshin/simpread/issues/5518#issuecomment-1534899143 一步步走（一共也没几步...
