### ISSUE TITLE
notion授权失败问题

### ISSUE THREAD

**Issue by AlexArtemis** [Kenshin/simpread#5520]
### 描述这个错误

![image](https://user-images.githubusercontent.com/24226784/236363786-06b0bc83-9152-48e8-9429-0d6f14b8f651.png)
最近使用导入notion时卡在第一张图像导入，一直不动。尝试重新授权，关闭后再无法授权，提示图上的错误。
![image](https://user-images.githubusercontent.com/24226784/236364118-eef3ae68-9453-4b59-bf8f-0bbe06557f3a.png)

### 复现步骤

1.偏好设置
2.连接并授权notion

### 操作系统

win11

### 浏览器

chrome 111.0.5563.111

### 发生问题的网址

https://zhuanlan.zhihu.com/p/382683271

**Comment by Kenshin** [comment]
> 问题1

无法授权 Notion 可以看 https://www.yuque.com/kenshin/simpread/wwk65u#ERFLg 提到的解决方案。

> 问题2

确保1已经授权后，试试导入 https://sspai.com/post/69972 能否成功？另外，是否开启了 Notion 图床功能？如果是的话，先关闭 Notion 图床，确保可以正常导入后再开启它。
