### ISSUE TITLE
关于导入notion的问题

### ISSUE THREAD

**Issue by lzg0419** [Kenshin/simpread#5521]
### 描述这个错误

导入notion 的过程中，一直显示在加载。
并没有提示任何错误
我下载了关于导入notion的所有插件，包括辅助增强，插件管理器
从notion中查看，确实在我table database 中的下面添加了空白一行，但是没有内容

### 复现步骤

导入notion 的过程中，一直显示在加载。
并没有提示任何错误
我下载了关于导入notion的所有插件，包括辅助增强，插件管理器
从notion中查看，确实在我table database 中的下面添加了空白一行，但是没有内容

### 操作系统

win 11

### 浏览器

Microsoft Edge  版本 112.0.1722.68 (正式版本) (64 位)

### 发生问题的网址

https://www.36kr.com/p/2243910267203206

**Comment by Kenshin** [comment]
> 一直显示在加载。

是指什么？建议截图。

除此之外，一些必要的信息。

1. 授权是否时是否提示正常？
2. 确保授权正确后，使用 https://sspai.com/post/69972 测试。
3. 在测试时，不要打开 Notion 并操作 Notion。

**Comment by lzg0419** [comment]
***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月5日 14:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 关于导入notion的问题 (Issue #5521)
        
      
    
  

Closed #5521 as completed.

**Comment by lzg0419** [comment]
已经授权了，测试页也是一样的
        一直在显示保存到notion 就是保存不进去
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月5日 14:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 关于导入notion的问题 (Issue #5521)
        
      
    
  


一直显示在加载。

是指什么？建议截图。
除此之外，一些必要的信息。

授权是否时是否提示正常？
确保授权正确后，使用 https://sspai.com/post/69972 测试。
在测试时，不要打开 Notion 并操作 Notion。

**Comment by lzg0419** [comment]
GitHub 上上传图片老是失败，我就发邮件了
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月5日 14:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 关于导入notion的问题 (Issue #5521)
        
      
    
  


一直显示在加载。

是指什么？建议截图。
除此之外，一些必要的信息。

授权是否时是否提示正常？
确保授权正确后，使用 https://sspai.com/post/69972 测试。
在测试时，不要打开 Notion 并操作 Notion。

**Comment by lzg0419** [comment]
你看到我的图片和视频了吗？GitHub 无法上传图片和视频，我保存到notion时，一直显示“正在保存到Notion，请硝等…”圆圈一直在转，存不到notion里面去
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月5日 14:37
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 关于导入notion的问题 (Issue #5521)
        
      
    
  


一直显示在加载。

是指什么？建议截图。
除此之外，一些必要的信息。

授权是否时是否提示正常？
确保授权正确后，使用 https://sspai.com/post/69972 测试。
在测试时，不要打开 Notion 并操作 Notion。

**Comment by Kenshin** [comment]
嗨，通过 Email 提交到这里的话，我是看不到的... 😂

发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5521

**Comment by lzg0419** [comment]
你好！我不太明白，这个邮箱地址是哪个？help#####simpread.pro 邮箱是什么意思？我没有看到邮箱地址？
        
        
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Kenshin ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月5日 15:28
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Kenshin/simpread] 关于导入notion的问题 (Issue #5521)
        
      
    
  

嗨，通过 Email 提交到这里的话，我是看不到的... 😂
发送到 help#####simpread.pro 邮箱里面（注意 # → @）并注明这个 Issues ID：5521
