### ISSUE TITLE
一直显示“正在保存到Notion，请稍等… ”保存不进去

### ISSUE THREAD

**Issue by lzg0419** [Kenshin/simpread#5522]
### 描述这个错误

你看到我的图片和视频了吗？GitHub 无法上传图片和视频，我保存到notion时，一直显示“正在保存到Notion，请稍等…”圆圈一直在转，存不到notion里面去

### 复现步骤

你看到我的图片和视频了吗？GitHub 无法上传图片和视频，我保存到notion时，一直显示“正在保存到Notion，请稍等…”圆圈一直在转，存不到notion里面去

### 操作系统

win 11

### 浏览器

Microsoft Edge  版本 112.0.1722.68 (正式版本) (64 位)

### 发生问题的网址

https://sspai.com/post/69972

**Comment by lzg0419** [comment]
你好！我找到问题所在了，就是因为我挂了VPN的缘故，不知道作者大大，能否修复或者解决一下这个问题？ @Kenshin

**Comment by lzg0419** [comment]
用自己本地的网络是正常的，可能和DNS有关，不知道能否克服这个问题 @Kenshin

**Comment by Kenshin** [comment]
嗨

> 你好！我找到问题所在了，就是因为我挂了VPN的缘故，不知道作者大大，能否修复或者解决一下这个问题？ @Kenshin

调用 Notion 相关 API 时，均使用了 Notion 官方 API，并没有做任何中转。

所以，建议你的在 VPN 中设置一些白名单之类的。

**Comment by lzg0419** [comment]
> 

我不知道该怎么弄，一打开clash 就不能正常保存，关闭就可以。 @Kenshin
