### ISSUE TITLE
导入obsidian问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5526]
### Discussed in https://github.com/Kenshin/simpread/discussions/5525

<div type='discussions-op-text'>

<sup>Originally posted by **Lusenlan** May  6, 2023</sup>
![image](https://user-images.githubusercontent.com/104048109/236625019-3bed9e86-7c1c-42c5-9825-cbacdc4de1ca.png)
</div>

**Comment by Lusenlan** [comment]
标记文字就会这样，保存到obsidian里也会报错，配置都是对的
![image](https://user-images.githubusercontent.com/104048109/236629380-b8cb27d7-a219-4622-9d38-0e8024a2c3a0.png)

**Comment by Kenshin** [comment]
配置对的就不能有这种提示…

**Comment by Lusenlan** [comment]
那我之前第一次试着还行，后面没用一会就不行了



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2023年5月6日(周六) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 导入obsidian问题 (Issue #5526)




 
配置对的就不能有这种提示…

**Comment by Lusenlan** [comment]
我已经运行了同步助手，它却没有反应，一直提醒我



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2023年5月6日(周六) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 导入obsidian问题 (Issue #5526)




 
配置对的就不能有这种提示…

**Comment by Lusenlan** [comment]
date的格式可以改吗？比如2023-5-1，我想把它改成2023_5_1




2353147991
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 导入obsidian问题 (Issue #5526)





 
配置对的就不能有这种提示…

**Comment by Kenshin** [comment]
1. 不要通过 Email 回复，如果带有图片等信息我是看不到的。

2. 提问的时建议详细说明你的问题，仅提问题的话，我没法帮到你 e.g. https://github.com/Kenshin/simpread/issues/5526#issuecomment-1537161557 完全不知道你的前因后果...
