### ISSUE TITLE
打开同步助手报错

### ISSUE THREAD

**Issue by tsuienpeng** [Kenshin/simpread#5527]
### 描述这个错误

打开同步助手自动弹窗，弹窗内容为：
`同步助手运行时发生了错误，错误信息： Error processing argument at index 0, conversion failure from Meta + Alt + ∂`

### 复现步骤

1. 打开同步助手主界面
2. 弹出报错弹窗

### 操作系统

macOS

### 浏览器

GoogleChrome

### 发生问题的网址

baidu.com

**Comment by Kenshin** [comment]
很奇怪的问题…

试试重新下载，并且确保在官方提供的下载渠道下载。

首次运行就保错吗？还是你配置了某些功能后这样？

**Comment by tsuienpeng** [comment]
之前一直是正常用的，配置的导出到Obsidian选项之后报错的...


在 2023年5月6日 22:32:31, Kenshin Wang ***@***.***) 写到:

很奇怪的问题…

试试重新下载，并且确保在官方提供的下载渠道下载。

首次运行就保错吗？还是你配置了某些功能后这样？

**Comment by Kenshin** [comment]
> 之前一直是正常用的，配置的导出到Obsidian选项之后报错的...

试试：删除再重新安装。

同步助手的正常运行跟它的配置无关，但跟配置数据结构的合法性有关。

所以，即便配置错了，但配置的数据结构没问题就可以访问 😂
