### ISSUE TITLE
obsidian1.2.7版本，简悦失效

### ISSUE THREAD

**Issue by archer3831** [Kenshin/simpread#5528]
### 描述这个错误

obsidian1.2.7版本，简悦失效，保存会显示保存失败，恢复到旧版本，可以使用。

### 复现步骤

1.1.2.7版本obsidian
2.简悦保存，显示保存失败
3.恢复旧版本
4.简悦保存，提示成功

### 操作系统

windows11

### 浏览器

360极速浏览器

### 发生问题的网址

baike.baidu.com

**Comment by Kenshin** [comment]
emmm 有点意思，哟稍晚测试下。

1. 任意 URL 均无法导入吗？
2. 如何导入？
3. 使用了哪种导入方案？

**Comment by Kenshin** [comment]
我测试了 1.2.7 版是没问题的。

请确保仅有一个 Obsidian 窗口，另外，把其他 Obsidian Plugin 禁用，看看能否解决？

**Comment by RyanKing1990** [comment]
同样的问题，而且每次重启，SimpRead Unreader Sync插件的设置全部丢失

**Comment by Kenshin** [comment]
@RyanKing1990 

> 同样的问题

是 1.2.7 不好使，但之前的版本好使？

> 每次重启，SimpRead Unreader Sync插件的设置全部丢失

应该是你在 Obsidian Plugin 文件夹设置时，文件名大小写的问题。

<img width="430" alt="image" src="https://user-images.githubusercontent.com/81074/236979819-404d1615-4c81-4127-abc8-fc698b92fd85.png">
