### ISSUE TITLE
导出保存到语雀，会出现图片不保存的问题。

### ISSUE THREAD

**Issue by realSummer** [Kenshin/simpread#5532]
### 描述这个错误

从掘金网站保存语雀，图片不会识别，不会保存。

### 复现步骤

1. 在 [掘金](https://juejin.cn) 打开阅读模式，
2. 动作保存到语雀
3. 语雀文档内部，文字没问题，图片不会显示，没有图片相关的内容

### 其他相关说明

无

### 操作系统

苹果系统

### 浏览器

谷歌浏览器 版本 112.0.5615.137（正式版本） (arm64)

### 发生问题的网址

https://juejin.cn

**Comment by realSummer** [comment]
阅读模式下，复制 md 到剪切板，然后在排版软件（https://editor.mdnice.com/?outId=41023f863cbd4b1db7844cf9a55fe305）里转了下格式，再粘贴到语雀可以转换成功了。显示正常了，图片也上传到语雀的图片库了。

**Comment by Kenshin** [comment]
嗨，掘金的图片因为做了比较严苛的防盗链验证，虽然可以通过技术手段解决，但简悦是会尊重源站规则。

跟不适配百度文库、微信读书是一类原因。

> 里转了下格式，再粘贴到语雀可以转换成功了

具体是怎么做的？我看看能否不破坏源站规则的前提下优化下这里。

**Comment by realSummer** [comment]
通过复制 md 内容到粘贴板，在 （https://editor.mdnice.com/） 这个网站里复制，然后点击复制到公众号（右侧边栏列表最上边的那个）然后再复制到语雀里，新建文档自动转换，就会吧图片传到语雀的图库里。对比了下文件，发现是 md 的文件格式转换了一下，书写格式变了。

**Comment by Kenshin** [comment]
嗨，mdnice 编辑器会把 Markdown 转换为 HTML，当你粘贴时，语雀会自动将这些图片再转换为语雀图床方案。

但通过我的测试来看，只有通过 mdnice 转换的 HTML 才会在语雀上被识别 😂

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案，解决了你提到的这个问题。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
