### ISSUE TITLE
logseq 插件 微信文章无法显示图片

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [Kenshin/simpread#5533]
### 请描述你的建议或任何内容

使用logseq 插件 微信文章无法显示图片
![image](https://user-images.githubusercontent.com/39046975/236726075-d00fa6c8-27a9-4242-b57a-c80d3d7b7516.png)
https://github.com/OverflowCat/logseq-simpread/issues/7

**Comment by Kenshin** [comment]
选项页 → 服务 → 定制导出，把图片代理打开

<img width="889" alt="image" src="https://user-images.githubusercontent.com/81074/236727842-9805ec5a-fc64-46ff-a080-fab329848a7a.png">

**Comment by niannianjun** [comment]
导出到obsidian也会出现相同的问题，应该如何操作？
![image](https://github.com/Kenshin/simpread/assets/131518332/09969902-972c-4132-abe1-d1eff2e4cd03)
