### ISSUE TITLE
关于导出的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5537]
1. 导入到notion时，图片时损坏的。
2. 使用同步助手保存到本地时，引用的地址是域名后面的路径，没有加上域名，所以为无法正确打开。导出其他格式也是同样的问题，最好保存本地时可以把图片也保存到本地，不然还是得联网才能加载图片。

_Originally posted by @edenz223 in https://github.com/Kenshin/simpread/discussions/4380#discussioncomment-5856883_

**Comment by Kenshin** [comment]
@edenz223

请不要在无关的地方提问。我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 问题1

需要提供 URL

> 问题2

使用离线 HTML 即可解决。

**Comment by edenz223** [comment]
> @edenz223
> 
> 请不要在无关的地方提问。我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> > 问题1
> 
> 需要提供 URL
> 
> > 问题2
> 
> 使用离线 HTML 即可解决。

因为 [4381](https://github.com/Kenshin/simpread/issues/4381#issuecomment-1214300326) 这里说到那个帖子讨论。 我试了下，公开库导出正常，加密库需要验证，所以全部失败。 建议可以加个提示用户：加密库导出图片会失败。

**Comment by Kenshin** [comment]
> 因为 https://github.com/Kenshin/simpread/issues/4381#issuecomment-1214300326 这里说到那个帖子讨论。 我试了下，公开库导出正常

你的意思是说：私有语雀库的页面进入阅读模式后，导入到 Notion 后图片无法显示？

如果是的话：

1. 你可以试试导出离线 HTML 看看图片是否可以显示？
2. 试试开启 Notion 图床功能，能否解决？

**Comment by edenz223** [comment]
> 你的意思是说：私有语雀库的页面进入阅读模式后，导入到 Notion 后图片无法显示？
导出公开文章的话，一切功能正常，但是导出加密文章时图片加载失败。
我登录账号的窗口打开图片地址可以正常打开，如果使用匿名窗口就会404。应该是语雀对加密库的图片进行了校验，你可以试试导出 需要密码访问的文章库的文章试试。

**Comment by Kenshin** [comment]
抱歉，之前漏掉了这个 Issues 😂

不过，确实如此，因为私有库的缘故，语雀用了比较严苛的图片方案，我测试了几个简悦通用方案，都没法实现。

虽然可以使用技术手段解决，但一般这种类型的页面简悦是不会特意处理的。

**Comment by edenz223** [comment]
嗯嗯，可以在插件加个提示下用户

**Comment by Kenshin** [comment]
okay 收到~ （ 谢谢提示 😄
