### ISSUE TITLE
账号被锁

### ISSUE THREAD

**Issue by julian20220130** [Kenshin/simpread#5542]
### 请描述你的建议或任何内容

购买力高级用户账号后经常被锁，提示登录了过多的浏览器，且通过自助解锁，开发者能否抽空回一下邮件，解决问题。

**Comment by Kenshin** [comment]
> 购买力高级用户账号后经常被锁

经常被锁？具体提示什么？可以自助解锁，解锁后又被锁？

建议详细描述... 😂

**Comment by julian20220130** [comment]
经常被锁指的是：当我从坚果云强制下载配置文件到本地后，提示我显示我登录超过三台设备，而实际上我仅有一台笔记本和一个台式，而且台式机上的此功能已经很久没有使用，且早已通过自助解锁方式登出所有设备。
自助解锁：三天前通过自助解锁“登出所有设备”后，强制下载配置文件到本地能够正常登录。
再次被锁：今天手残点击了“授权通过坚果云登录”，然后显示账号再次被锁，且无法自助解锁。

**Comment by julian20220130** [comment]
![未命名](https://github.com/Kenshin/simpread/assets/98684721/afa0ef56-67bd-4149-9757-f8674e829353)
显示界面如图
<img width="791" alt="iShot_2023-05-12_09 14 28" src="https://github.com/Kenshin/simpread/assets/98684721/7c9bcf8f-a825-4779-a631-2d274e539aec">

**Comment by julian20220130** [comment]
设备1、2、3均为同一浏览器（edge）的同一插件，不知道为什么会出现三个设备

**Comment by Kenshin** [comment]
我明白了...

是不是用了配置库的 Demo UID ？也就是 `xxx-xx` 的这种？如果是的话，这不是真实的 UID，当然会被锁...

在 [配置库的教程](https://www.yuque.com/kenshin/simpread/wq35mh#74e49885) 中指明了这点... 

所以：

1. 使用你自己的 UID
2. 不要使用 `xxxx-xxx`

至于如何更改自己的 UID ，上面的链接里面已经提到了。

PS：配置库有好几种方案，我只是随便找一个 Obsidian 作为例子说明。

**Comment by julian20220130** [comment]
明白了。按照我当时保存的资料，把UID修改回来了。
但是目前又遇到另一个问题：显示“您还不是高级账户，请先购买高级账户资格”。
难道我UID记错了？于是我通过license尝试找回uid，又发现找回次数超过三次……就…问题还挺多
当时兑换的license为：syxr-hgc698-mil6hz-npff。
请开发者帮忙解决。

**Comment by Kenshin** [comment]
不要随便把 Licens 放上来，这是你的密钥 .... 

你在首次绑 UID 时，就使用了 Demo UID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 当然有错误了...

你应该在 Email 联络我了？如果是的话，把 Email 告诉我，我给你一个新的 UID

**Comment by julian20220130** [comment]
好的，谢谢提醒。
邮箱：hyvipzl@vip.qq.com

**Comment by Kenshin** [comment]
okay 我帮你操作下。

你先关闭浏览器或者暂时不要使用简悦，等我的邮件，我现在帮你处理。

**Comment by Kenshin** [comment]
可以了，我把新的 UID 用 Email 告诉你了。

**Comment by Kenshin** [comment]
@mariahlamb31 

`xxxxxxxx-xxxx` 是 Demo UID 在你使用配置库以及配置库教程时，有明确说明，更换为自己的高级账户 UID 就行了。

<img width="1153" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e27598cb-5527-4e29-81a6-7502b5441bba">

**Comment by Kenshin** [comment]
@mariahlamb31

如果你没有升级到高级账户 UID 的话，就重新安装简悦，然后再使用 https://www.yuque.com/kenshin/simpread/sqdl46 升级到高级账户 UID，而后再替换。
