### ISSUE TITLE
当前账户与简悦·同步助手不一致

### ISSUE THREAD

**Issue by xavierQin** [Kenshin/simpread#5543]
### 请描述你的建议或任何内容

刚刚购买高级账号，按照教程安装ob的配置文件；选择导出后就会弹窗，不能导出；
重新安装扩展程序、重新安装同步助手，问题依旧存在

**Comment by Kenshin** [comment]
使用配置库时，需要将配置库的 UID 更换为自己的 UID 教程中有提示和说明

**Comment by xavierQin** [comment]
谢谢

**Comment by xavierQin** [comment]
你好，你说的更换UID是这一步吗，这一步我执行了
![image](https://github.com/Kenshin/simpread/assets/133442501/989d265f-871e-4f3f-8c4f-0e7db98ac7c1)

**Comment by Kenshin** [comment]
用我在 Email 中给你的 UID 替换

**Comment by Kenshin** [comment]
抱歉，上条信息发错用户了，请忽略 😂

> 选择导出后就会弹窗，不能导出；

截图或者视频等详细描述，并提供 URL

**Comment by xavierQin** [comment]
![image](https://github.com/Kenshin/simpread/assets/133442501/a67ab5ce-1405-4f9b-a25a-65fb5a54ab2f)
![image](https://github.com/Kenshin/simpread/assets/133442501/588ed2fc-e307-4ff2-9357-78511d260d46)
已经写入UID，是高级用户了，点击导出Markdown等选项，跳出弹窗提示

**Comment by Kenshin** [comment]
看看你的同步助手与你的扩展端里面的 UID 是否一致。

<img width="677" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ac471609-198f-45a4-bcd4-617ddc76fe4e">

如果不一致的话，需要重置同步助手。

**Comment by xavierQin** [comment]
谢谢，就是这里出问题了，已经解决

**Comment by Kenshin** [comment]
okay 解决就好~  👏
