### ISSUE TITLE
阅读助手问题

### ISSUE THREAD

**Issue by beianliu** [Kenshin/simpread#5546]
### 描述这个错误

使用阅读助手总结全文提示“opanai服务器错误，请稍后再试。”
昨天之前该功能是正常的。昨晚至今均提示“opanai服务器错误，请稍后再试。”

确定我的网络环境没问题，ChatGPT网页版可以正常使用，其他使用opanai API Key的浏览器扩展也均是正常的。
我今天给每一个使用API Key的浏览器扩展单独分配了一个Key，每个扩展均多次使用后。简约阅读助手的上次使用时间为“Never”，其他扩展的上次使用时间均为“2023年5月13日”。

### 复现步骤

阅读模式下按快捷键aip总结全文，提示“opanai服务器错误，请稍后再试。”

### 操作系统

win11

### 浏览器

chrome110

### 发生问题的网址

https://mp.weixin.qq.com/

**Comment by Kenshin** [comment]
okay 谢谢反馈，现在再测试下。

**Comment by beianliu** [comment]
正常了

**Comment by Kenshin** [comment]
okay 😄 服务器挂了，但没有自动重启 😂
