### ISSUE TITLE
无法解析小红书网页，之前都可以的

### ISSUE THREAD

**Issue by pandebiubiu** [Kenshin/simpread#5547]
### 描述这个错误

前天开始忽然发现小红薯网页无法解析，不能用简悦插件打开，打开后也无法显示全部文字，只能显示几个字，图片全部显示不了。换了浏览器、删掉插件重新安装，都没用。
![哈哈哈哈](https://github.com/Kenshin/simpread/assets/69087666/7dd96a7c-ca31-49ab-8e07-185dc006711a)
![哈哈哈哈哈或](https://github.com/Kenshin/simpread/assets/69087666/3d4d2dd1-0c4d-4ffc-a286-38716f5868d7)
**【图片是演示，并没有任何其它用意，随便截！举例而已！】**

### 复现步骤

打开小红书网页——点击简悦插件

### 操作系统

win

### 浏览器

edge、谷歌

### 发生问题的网址

https://www.xiaohongshu.com/explore

**Comment by Kenshin** [comment]
okay 可能是它的页面结构改变了，我先 Mark 下。

**Comment by Kenshin** [comment]
嗨，你可以这样做：

选项页 → 高级设定 → 全局 → 排除列表

将 `xiaohongshu.com` 加入其中。（如下图所示）

<img width="1216" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3b8579d9-e556-4ce0-9ab9-799cdfcb9290">

然后刷新选项页，看看是否生效，如果生效的话。

随便找个页面 e.g. https://www.xiaohongshu.com/explore/644a098a0000000013007228 手动进入阅读模式，即可。

<img width="1158" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/51a92ce0-6603-44d8-9ae1-cb85f3010974">

**Comment by pandebiubiu** [comment]
可以解析图片吗？之前一直是可以解析图片，因为小红书在其他任何地方都不可以保存图文，但是简悦之前解析出来进入阅读模式后可以保存的。
下面是我保存的样子，图片全都可以解析出来。




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年05月15日 11:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 无法解析小红书网页，之前都可以的 (Issue #5547) |

Closed #5547 as completed.

**Comment by Kenshin** [comment]
当然可以

<img width="1300" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0785fbe3-0bc1-46d5-915d-5f424700fea6">

也可以正常导入到 Notion 中

<img width="1343" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f10bd8ea-6fd3-44a4-80e5-e0788dca302d">

**Comment by pandebiubiu** [comment]
> 当然可以
> 
> <img alt="image" width="1300" src="https://user-images.githubusercontent.com/81074/238239483-0785fbe3-0bc1-46d5-915d-5f424700fea6.png">
> 也可以正常导入到 Notion 中
> 
> <img alt="image" width="1343" src="https://user-images.githubusercontent.com/81074/238239614-f10bd8ea-6fd3-44a4-80e5-e0788dca302d.png">

尝试了一下，可以诶！！！太棒了！！！

**Comment by pandebiubiu** [comment]
![301fe3cc-97db-413b-9966-c4e5fb45d6cd](https://github.com/Kenshin/simpread/assets/69087666/fcf1fe29-0d0d-4d6f-8c7c-db86e3d4ae91)
太容易出现这种错误了，EDGE和谷歌浏览器都是，必须要重新进入两三次才能正常进入阅读模式……5555……

**Comment by Kenshin** [comment]
使用下图的方案

<img width="944" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f07bba1f-3e53-48a9-a229-c0575284911d">

简单的说，等页面加载完毕后再进入阅读模式。

如果自动进入阅读模式的话，肯定有问题。

**Comment by pandebiubiu** [comment]
我是手动进入的，小红书打开网页之后我都是手动点插件，但是会有很大概率变成我发的图片那样。之前用的时候都没这个问题一直都是很流畅的，忽然它就一直跳出来这个，昨天按照你说的方法操作之后，可以解析，但是我打开网页之后无论是刚加载还是我已经等了一段时间，它都会失败，然后我后退，然后再加载就可以成功，有的时候还要失败2次才会成功………



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年05月16日 10:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 无法解析小红书网页，之前都可以的 (Issue #5547) |

使用下图的方案

简单的说，等页面加载完毕后再进入阅读模式。

如果自动进入阅读模式的话，肯定有问题。

**Comment by Kenshin** [comment]
> 之前用的时候都没这个问题一直都是很流畅的

小红书改了规则导致的，跟简悦无关。

> 但是我打开网页之后无论是刚加载还是我已经等了一段时间，它都会失败，然后我后退，然后再加载就可以成功，有的时候还要失败2次才会成功………

1. 按照 https://github.com/Kenshin/simpread/issues/5547#issuecomment-1548883102 提示操作（注意：跟我之前说的方式稍微有区别）

2. 在**隐身模式下仅使用简悦的方式** ，看看是不是其它扩展的干扰。
