### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by wuwuzhazha** [Kenshin/simpread#5548]
### 请描述你的建议或任何内容

作者你好，我在使用简约过程中发现代码没有高亮，请问是我配置错误还是软件尚未支持此功能。目标网站：http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/

**Comment by Kenshin** [comment]
嗨，简悦有个 [代码高亮插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)，但并不是非常完美，因为代码高亮规则很多。

你可以试试能否解决。

PS：这个插件只能适配部分常规高亮规则。
