### ISSUE TITLE
网页标注导入obsidian后格式存在问题

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#5549]
### 描述这个错误

http://fujian.chinatax.gov.cn/fzsswj/zfxxgkzl/zfxxgkml/tajybl001/202305/t20230508_508399.htm
这个网页标注后自动导入obsidian格式有问题，似乎因为某些特殊符号导致markdown处理处理问题。如下：
<img width="1246" alt="image" src="https://github.com/Kenshin/simpread/assets/70339118/f38e3a53-37ad-4562-accc-52cfa1d94f51">

### 复现步骤

打开网页-快捷键aa进入阅读模式-标注后自动生成html并导入obsidian

### 操作系统

macos

### 浏览器

edge112.0.1722.58正式版

### 发生问题的网址

http://fujian.chinatax.gov.cn/fzsswj/zfxxgkzl/zfxxgkml/tajybl001/202305/t20230508_508399.htm

**Comment by Kenshin** [comment]
你把这个 markdown 发上来，只看截图的话，我没明白 😂

**Comment by HopeLHP** [comment]
[46-国家税务总局福州市税务局关于市十六届人大二次会议第 1035 号建议的答复_
        建议提案办理_
        国家税务总局福州市税务局@annote.md.zip](https://github.com/Kenshin/simpread/files/11471515/46-.1035._._.%40annote.md.zip)
@Kenshin

**Comment by Kenshin** [comment]
okay 我明天看下。

PS：仅仅只是这个页面有问题？还是其它页面也有问题？

**Comment by HopeLHP** [comment]
http://fujian.chinatax.gov.cn/fzsswj/zfxxgkzl/zfxxgkml/tajybl001/202305/t20230508_508395.htm
这个页面也是，都是同一个网站。
不清楚是这个网站的问题还是恰巧这俩网页内容中包含某些字符的问题。

**Comment by Kenshin** [comment]
好，其他网站没有这个问题吧？

**Comment by HopeLHP** [comment]
没问题，试了其他网站，基本可以排除我这边设置的问题

**Comment by Kenshin** [comment]
我知道是什么问题了，因为这个 URL 的标题含有换行等特殊字符造成的。

你可以使用 https://github.com/Kenshin/simpread/discussions/2852 修改标题（去掉换行等）然后重新导出标注就行了。

**Comment by HopeLHP** [comment]
可以了，我本来也用Live Editor处理过标题，然后阅读模式下标注发现OB里面还是有问题，现在发现原来是进入阅读模式live editor处理后得dd加入稍后读再标注，这样ob里面就是liveeditor处理过后的样子了

**Comment by Kenshin** [comment]
哈，解决就好~

> 现在发现原来是进入阅读模式live editor处理后得dd加入稍后读再标注

是的，当加入稍后读时才会将阅读模式的内容转换为本地快照或者标注。
