### ISSUE TITLE
不支持代码块？

### ISSUE THREAD

**Issue by Dreampie** [Kenshin/simpread#555]
![image](https://user-images.githubusercontent.com/3667080/62351378-ddc4c600-b537-11e9-8eb7-a318ed381fb2.png)
https://blog.csdn.net/geyunfei_/article/details/78782804

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/500

建议使用简悦的 [帮助系统](http://ksria.com/simpread/docs/#/帮助中心) 以及 多看看 https://github.com/Kenshin/simpread/issues/533

 😀
