### ISSUE TITLE
希望markdown辅助增强里的模板修改后能有办法将以前导出到本地的稍后读标注也一键更新为新格式

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5551]
### 请描述你的建议或任何内容

现在只能手动一个个改，还必须将标注动一下才能触发保存到本地命令，稍后读多了十分麻烦，如果可以一键更新的话对于工作流尚未定型的新人想必也友好许多

**Comment by Kenshin** [comment]
可以的，但需要在 Obsidian SimpRead Sync 插件中操作。

<img width="1038" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e24509e7-ecb1-481c-8dde-0ec74a08aa3d">

使用时，也需要将模板也在这个插件中设置下。
