### ISSUE TITLE
建议，增加类似adblock屏蔽广告的语法规则来解析无法“感知”的文章

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5553]
### Discussed in https://github.com/Kenshin/simpread/discussions/5552

<div type='discussions-op-text'>

<sup>Originally posted by **9k01** May 15, 2023</sup>
https://guokrapp.guokr.com/article/16321
</div>

**Comment by Kenshin** [comment]
@9k01

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

这个功能是有的，看下图

<img width="479" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f3f10e6a-6f22-44f4-8178-ce05e0ecbad9">

另外，你给出的 URL 是可以正常进入阅读模式的。

<img width="1715" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8d8bb168-28ce-4af6-8256-6211f9d5e569">

**Comment by Mr-Roxe** [comment]
我试着打开了这个网页，默认是没有阅读模式的，不知道作者你是怎么弄的

**Comment by Kenshin** [comment]
> 我试着打开了这个网页，默认是没有阅读模式的，不知道作者你是怎么弄的

@Mr-Roxe 

默认当然没有阅读模式了... 需要在右上角进入

<img width="135" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/98d84741-0132-423c-966a-6346df7e59f5">

**Comment by 9k01** [comment]
你的是mac,

在windows 上不正常，主要手动选择后这个规则没有保存，导致同一个网站每次都需要手动选择
所以有了adblock的规则建议，考虑下，太麻烦的话，就算了
Microsoft Edge | 113.0.1774.42 (正式版本) (64 位)

Chromium 版本 | 113.0.5672.93
操作系统 | Windows 10 Version 22H2 (Build 19045.2965)

**Comment by Kenshin** [comment]
@9k01

我适配了这个页面，使用下面的方式更新适配规则，位置在：选项页 → 站点管理

<img width="944" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/88d53277-f814-498b-9496-fcbe1c076ba7">

更新后重启浏览器。

另外：没有适配的话，这个页面也能正常进入阅读模式。
