### ISSUE TITLE
关于腾讯问卷购买疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5554]
已付款，问卷无法提交，邮箱：mr_roxe@qq.com

_Originally posted by @Mr-Roxe in https://github.com/Kenshin/simpread/discussions/1577#discussioncomment-5902846_

**Comment by Kenshin** [comment]
@Mr-Roxe

我帮你新建了一个 Issues，并删除了原来位置的内容。

请忽略上条回复内容，以本条 https://github.com/Kenshin/simpread/issues/5554 为准。

***

1. 更换其它浏览器
2. **隐身模式下**，提交腾讯问卷。 

如果还是不行的话，发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：1577，附上支付宝付款截图（有 202*** 开头的）

然后在这里通知我。

**Comment by Mr-Roxe** [comment]
隐私模式下已提交问卷，help#simpread.pro邮箱已发送截图，Issue ID：1577为主题

**Comment by Kenshin** [comment]
能提交问卷就行了，今天晚上 19 点左右会发兑换码。
