### ISSUE TITLE
适配思源笔记

### ISSUE THREAD

**Issue by Aiviokoo** [Kenshin/simpread#5555]
### 请描述你的建议或任何内容

简悦和思源都是很好用的国产软件，希望可以强强联手。

**Comment by bighaidao** [comment]
> 哈，本周或下周。
> 
> 😄

终于看到明确的 deadline 了.😆

**Comment by bighaidao** [comment]
> [<img alt="@Kenshin" width="20" height="20" src="https://avatars.githubusercontent.com/u/81074?s=40&amp;v=4">](/Kenshin) [Kenshin](/Kenshin) changed the title ~思源笔记已经有官方的插件系统了，希望简悦可以像适配ob那样适配一下思源笔记，谢谢~ 适配思源笔记 [May 15, 2023](#event-9245167504)

哈，更新了吗？

**Comment by Kenshin** [comment]
@bighaidao 

哈，如果更新的话，我肯定会通知这里 😂 别急，已经 ing 了

**Comment by Kenshin** [comment]
嗨，各位~

久等了，预计周末在这里发测试版。

目前常规功能：

1. 导入 Markdown
2. 将阅读模式的图片 → 思源笔记 assets 文件夹
3. 导入前可选文件夹（类似 Notion 插件的效果）
4. 可在简悦中新建笔记本（以及路径）

现在想咨询下大家的使用习惯（需求），尤其是对 **笔记本 / 文件夹 / 图片资源** 这三类有什么需求？

PS：我下午可能要出现办点事情，所以不会马上实时回复大家~

**Comment by mozhux** [comment]
> 嗨，各位~
> 
> 久等了，预计周末在这里发测试版。
> 
> 目前常规功能：
> 
> 1. 导入 Markdown
> 2. 将阅读模式的图片 → 思源笔记 assets 文件夹
> 3. 导入前可选文件夹（类似 Notion 插件的效果）
> 4. 可在简悦中新建笔记本（以及路径）
> 
> 现在想咨询下大家的使用习惯（需求），尤其是对 **笔记本 / 文件夹 / 图片资源** 这三类有什么需求？
> 
> PS：我下午可能要出现办点事情，所以不会马上实时回复大家~

思源的assets文件夹如果资源没有被引用，可能会被置入未引用资源，设置-资源里可以直接删除，但有对应的api可以避免，建议了解一下避免被直接清理了。
另外就是思源里也可以直接打开浏览器，应该可以实现直接打开同步助手，这样不知道会不会有新的玩法？直接边做边同步

**Comment by Kenshin** [comment]
> 思源的assets文件夹如果资源没有被引用，可能会被置入未引用资源，设置-资源里可以直接删除

默认会导入到 `assets/simpread` 文件夹下面，也就是说全部导入到内容都放到一起... 😂

> 思源的assets文件夹如果资源没有被引用，可能会被置入未引用资源

除非对应的文章删除了，否则肯定有对应的图片引用。

> 思源里也可以直接打开浏览器

可以在思源中类似 Obsidian 内嵌 iframe 吗？类似下图

<img width="1826" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0472eb51-62b2-499f-8f7e-e229b4b7c5c2">

**Comment by mozhux** [comment]
> > 思源的assets文件夹如果资源没有被引用，可能会被置入未引用资源，设置-资源里可以直接删除
> 
> 默认会导入到 `assets/simpread` 文件夹下面，也就是说全部导入到内容都放到一起... 😂
> 
> > 思源的assets文件夹如果资源没有被引用，可能会被置入未引用资源
> 
> 除非对应的文章删除了，否则肯定有对应的图片引用。
> 
> > 思源里也可以直接打开浏览器
> 
> 可以在思源中类似 Obsidian 内嵌 iframe 吗？类似下图
> 
> <img alt="image" width="1826" src="https://user-images.githubusercontent.com/81074/241128609-0472eb51-62b2-499f-8f7e-e229b4b7c5c2.png">

已经有两个浏览器插件了，思源的自定义页签都支持这些。
![image](https://github.com/Kenshin/simpread/assets/46953371/5a849b6b-6de6-4fd4-a93e-49d1dba50bb8)
![image](https://github.com/Kenshin/simpread/assets/46953371/9834ff60-070c-4339-a0e8-b0eb0a4a3c17)

**Comment by bighaidao** [comment]
> 嗨，各位~
> 
> 久等了，预计周末在这里发测试版。
> 
> 目前常规功能：
> 
> 1. 导入 Markdown
> 2. 将阅读模式的图片 → 思源笔记 assets 文件夹
> 3. 导入前可选文件夹（类似 Notion 插件的效果）
> 4. 可在简悦中新建笔记本（以及路径）
> 
> 现在想咨询下大家的使用习惯（需求），尤其是对 **笔记本 / 文件夹 / 图片资源** 这三类有什么需求？
> 
> PS：我下午可能要出现办点事情，所以不会马上实时回复大家~

nice， 我目前是 docker 远程的思源服务。 希望能导入 markdown 就可以了（需要配置远程服务地址），如果能标注导入就更好了。

其他暂时没了

**Comment by 88250** [comment]
@Kenshin 你好，我是思源笔记的作者，目前有一个实现方面的建议，但我不太了解简悦目前的开发思路，如果说错了还请见谅。

简悦在支持思源笔记的时候对于资源文件（asset）请尽量不要直接操作文件系统，而是使用思源笔记提供的 API，比如使用思源内核提供的 API [上传资源文件](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E4%B8%8A%E4%BC%A0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6)。

如果要直接写入文件系统麻烦在实现的时候留意 assets 文件的命名，即 xxxx-{id}.xxx，这个 id 的规则是时间+7 字符随机数，随机数使用小写 [a-z] 和 [0-9]，下面是 golang 的参考实现：

```
func NewNodeID() string {
	now := time.Now()
	return now.Format("20060102150405") + "-" + randStr(7)
}

func randStr(length int) string {
	letter := []rune("abcdefghijklmnopqrstuvwxyz0123456789")
	b := make([]rune, length)
	for i := range b {
		b[i] = letter[rand.Intn(len(letter))]
	}
	return string(b)
}
```

最后，感谢你花时间为简悦接入思源笔记，真的非常感谢 ❤️

**Comment by Kenshin** [comment]
@bighaidao 

> 我目前是 docker 远程的思源服务。 希望能导入 markdown 就可以了（需要配置远程服务地址）

你是说 `http://127.0.0.1:59282/` 这个地址可以定制吗？（这是思源官方提供的默认地址）

**Comment by Kenshin** [comment]
@88250 

> https://github.com/Kenshin/simpread/issues/5555#issuecomment-1564007199

嗨，很高兴认识你，都是国内开发者应该互相帮助。😄

最初计划应该是 2022 年底，因为当时 🐑 了，休息了一段时间再加上春节期间给简悦增加了一些功能功能，所以打算在三月份开始...

后来因为 OpenAI 的一些事情，所以一直 Delay 到现在。😂

***

至于你提到的问题，我这边使用都是正规的思源 API，无需担心。

<img width="779" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/410d763f-9b10-4275-bc0a-8bcd0509b666">

**Comment by Kenshin** [comment]
@bighaidao 

> 如果能标注导入就更好了。

标注的话，其实也完全可以导入，但因为 Markdown 对标注支持的有限，所以只能像 Obsidian 那样。（原文 + 标注，两个文件）

PS：因为思源有自己的数据结构，所以不知道 @88250 有没有打算对导入内容有类似标注的功能。

**Comment by 88250** [comment]
@bighaidao @Kenshin 这个恐怕不行，思源目前没有自定义元素的能力。通过插件实现的话工作量有些大，可能会偏离简悦的开发目标，我个人觉得先解决基础需求即可。

**Comment by Kenshin** [comment]
@88250 

okay 

@bighaidao 那还是试试 Obsidian 的标注是否支持思源笔记吧，如果没问题的话，就按 Obsidian 模板。

**Comment by Kenshin** [comment]
嗨，各位：

导入到思源笔记的插件可以内测了，已发布功能：

> 基础账户功能

- [x] 导入 Markdown 全文
- [x] 将阅读模式的图片 → 思源笔记 assets 文件夹（思源图床）
- [x] 导入前可选文件夹（类似 Notion 插件的效果）
- [x] 可在简悦中新建笔记本（以及路径）

> 以及自动化（高级账户）

将 `z s y` 加入到自动化辅助增强插件。

<img width="536" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/60a567cf-de13-4645-9a10-2635a1a7ede6">

### 下图是已知功能

<img width="520" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7411e8dd-7994-437c-acc7-2e44ba11840d">

***

### 关于标注功能

**当标题相同时，不会覆盖原来的笔记，而是新增**，所以导入标注的功能（尤其是自动化）可能不太适合导入到思源笔记。

所以如果我的理解有错误，请各位经常使用思源笔记的用户帮忙指出。（目前我使用 API 时确实没法覆盖）

PS：思源笔记的标注功能和模板都完成了，但因为上面的限制，所以暂时搁置。

***

### 注意事项

1. 因为是内测版，所以插件的标题没有正式命名。
2. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
3. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

有任何反馈随时请回复到这里。

**Comment by Aiviokoo** [comment]
@Kenshin 已经体验上了，效果很棒，感谢适配。
不过我这里试了试，通过简悦存到思源里的文章中的图片资源会出现在
设置-资源（的未引用资源中），这样较容易被误删除，希望可以改进一下哟，谢谢。
之前做导入epub格式插件的作者也遇到了这个问题，后来解决了，不知道您能否通过这个看到他的解决方式
https://github.com/terwer/siyuan-plugin-importer
或者可以去思源折腾qq群问问，群号是1017854502

**Comment by Kenshin** [comment]
@Aiviokoo 

> 设置-资源（的未引用资源中），这样较容易被误删除

默认在下图所示的位置（也就是 `assets` 文件夹下）

<img width="361" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/53fe0d9f-5c60-4cee-9985-3372aec35232">

可以更改，但我不清楚正确的话是到什么地方？ 😂 我是根据 API 说明导入的位置

<img width="686" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7e3d4ecb-79c9-4ebc-a130-7e5bb5921314">

另外一点：导入的 Markdown 的图片是下图格式

<img width="1416" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/eed1ccca-a866-4027-a113-091dda55cfc5">

也就是使用了 `http://127.0.0.1:6806/assets/simread/2023-05-28/1685255628584-20230528143348-se6igwp.png` 而非 `assets/simread/2023-05-28/1685255628584-20230528143348-se6igwp.png`

不知道是否是这个问题引起的。

**Comment by Kenshin** [comment]
嗨，各位

经 @Aiviokoo 提示 https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566046121 我修复了这个问题。

<img width="1011" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b8bfc781-3ddd-4ea1-8d06-a5cd26c8fdef">

重新安装此插件即可。

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

**Comment by Kenshin** [comment]
@Aiviokoo 

如果没问题的话告诉我下。

另外，有个疑问：

> 设置-资源（的未引用资源中），这样较容易被误删除

这里的文件是否会被思源自动清理掉。

PS：如果这里的文件可以不用被清理掉的话，从某种程度上说，思源笔记也可以「变成」一个图床。

PPS：思源笔记都有什么同步方案？

**Comment by mdzz2048** [comment]
反馈一个小问题：
这个选项打开以后
<img width="404" alt="1685273523847" src="https://github.com/Kenshin/simpread/assets/86549958/eafabe51-943e-46cf-9336-47725a71bef8">
导入没有图片的文章会一直卡在这里
![image](https://github.com/Kenshin/simpread/assets/86549958/737446f2-00d8-48cb-a6da-89dfa1fd1734)
测试链接：https://zhuanlan.zhihu.com/p/433454240

**Comment by HopeLHP** [comment]
> 导入没有图片的文章会一直卡在这里

这个是不是和原来的转换为自有图床的原理一致？siyuan插件我还没用，但是转为自有图床或导出离线html，我也经常遇到这种情况，一直卡在转换界面。有时候是已经转换完成了当时通知还在，有时候是没转换完成一直卡着，只能通过关闭重开消除通知，但转换该卡还是卡着。

**Comment by Aiviokoo** [comment]
@Kenshin 
 > 设置-资源（的未引用资源中），这样较容易被误删除
这里的问题已经得到解决啦。不过的确有上述老铁反馈的这个情况发生（刷新页面后再次用快捷键sy就可以成功保存了）
![image](https://github.com/Kenshin/simpread/assets/87182333/0580f1db-eea5-4b40-a577-7687f0b21d66)


> 这里的文件是否会被思源自动清理掉。
> PS：如果这里的文件可以不用被清理掉的话，从某种程度上说，思源笔记也可以「变成」一个图床。
这里的文件不会被自动清楚，如果这里有未引用资源，将会显示在思源的 设置-资源（未引用资源）这里，可以手动清除避免占据本地或云端空间。另思源可以开新的空间（这样使用就不会影响到主空间了）
![image](https://github.com/Kenshin/simpread/assets/87182333/23125a7a-1825-46a5-b984-193ad839cab6)
![image](https://github.com/Kenshin/simpread/assets/87182333/b2894683-c0d1-4198-97e4-f9de2467c005)

> PPS：思源笔记都有什么同步方案？
思源可以使用官方的同步（这个可以选择是否上传到官方的图床中）
也可以自行配置S3或WebDAV方案，也有一些用户用Docker版的思源。
![image](https://github.com/Kenshin/simpread/assets/87182333/84c57fd0-eb38-451d-a241-29593efa6ec1)

**Comment by mdzz2048** [comment]
> ### 关于标注功能
> **当标题相同时，不会覆盖原来的笔记，而是新增**，所以导入标注的功能（尤其是自动化）可能不太适合导入到思源笔记。
> 
> 所以如果我的理解有错误，请各位经常使用思源笔记的用户帮忙指出。（目前我使用 API 时确实没法覆盖）
> 
> PS：思源笔记的标注功能和模板都完成了，但因为上面的限制，所以暂时搁置。

您指的是通过`createDocWithMd`API 创建文档会产生重复文档吗？
我觉得可以考虑通过 [块操作 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E5%9D%97)、[块属性 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E5%B1%9E%E6%80%A7) 配合 [SQL](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#sql) 实现标注的导入和更新。https://github.com/Kenshin/simpread/issues/5006#issuecomment-1374839955

---
我用 Quicker 制作过一个导入标注的动作，流程大致如下：

1. `/api/filetree/createDocWithMd`创建存放标注文档的空文档
2. `/api/block/appendBlock`依次插入所有标注，并使用`/api/attr/setBlockAttrs`设置自定义块属性
    - 比如使用`custom-simple-read-annotation-id`作为标注的 id，之后可以用 SQL 搜索这个标注

更新、删除标注：

1. `/api/query/sql`搜索指定的标注
    - 对应上面那个示例是 ：select * from attributes where name == 'custom-simple-read-annotation-id' and value == '{annotation_id}'
2. `/api/block/updateBlock`更新标注、`/api/block/deleteBlock`删除标注

PS：以上建议仅供参考，如有问题还望批评指正。

**Comment by Kenshin** [comment]
@mdzz2048 

> https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566106275

我在 18 点多的时候优化了这个地方，但不确定是否有效，如果在这个时间点之前使用的话，建议重新安装。

我明天也确认下。

**Comment by Kenshin** [comment]
@mdzz2048 

> https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566122173

okay 我研究下，感觉你这个方式不错，可以做到差值更新。

**Comment by Kenshin** [comment]
@HopeLHP 

> https://github.com/Kenshin/simpread/issues/5555#issuecomment-1566108023

你的问题跟这个 Issues 无关 😂 有需要反馈的话，建议新建个 Issues 讨论。

**Comment by HopeLHP** [comment]
> 你的问题跟这个 Issues 无关 😂 有需要反馈的话，建议新建个 Issues 讨论。

我只是觉得可能两者的实现方式原理相关哈哈哈，不过没关系，现在我就尽量避免这种操作出现在我的工作流里就行。

**Comment by Aiviokoo** [comment]
@Kenshin 
> 我大概知道了，思源似乎不太希望用户直接将文件夹作为同步盘，（比如简悦这种方式）而是使用它自己的同步方案？

思源目前不支持同步盘主要原因是可能会因为同时读写导致数据损坏或丢失，详见： https://ld246.com/article/1664442401353
官方也比较想过用第三方同步盘同步assets文件夹的文件（见这个帖子的一些讨论https://ld246.com/article/1682201840138），可能暂时还没想到办法，如果您有什么好想法或办法可以给开发者提一下，这应该会对思源带来很大的帮助。
![image](https://github.com/Kenshin/simpread/assets/87182333/96c35fd4-2b89-42c6-9750-1db55b610983)

**Comment by Kenshin** [comment]
嗨，各位。

导入到思源笔记插件升级到 0.0.3 版。

1. 解决了 @mdzz2048 提到当没有图片时无法导出的错误。
2. 增加了一个新选项。

    <img width="558" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dc2fa433-f71f-4b22-af51-9e04e46014b7">

    默认为关闭状态，专门针对思源笔记用户，开启后（需开启思源图床插件），可以将阅读模式中的图片链接也转换为思源笔记图床方案，方便后续再导出为 HTML 格式。

   如果还需要将阅读模式的内容导入到在线生成力工具 e.g. Notion 等请不要开启。

***

当前版本预计今天正式发布，标注功能可能要放在下个版本中发布。

正版版发布后我会在这里通知大家。

**Comment by bighaidao** [comment]
@Kenshin  hi，我在测试本地网络时 ok 的，但是远程网络时配置失败。麻烦帮忙看看

![image](https://github.com/Kenshin/simpread/assets/1301460/9dc3a3fe-cd54-4e21-a3a4-85dceb9e0803)


我远程思源是 ok的

![image](https://github.com/Kenshin/simpread/assets/1301460/2b286ebe-ba6b-4653-b988-4f4a099e9e23)

**Comment by Kenshin** [comment]
@bighaidao 

> 我在测试本地网络时 ok 的，但是远程网络时配置失败。

更改完后需要先保存再使用。

**Comment by Kenshin** [comment]
@bighaidao 

还有这个问题吗？因为我暂时没法测试 😂 

PS：预计下午发布它~

**Comment by bighaidao** [comment]
> @bighaidao
> 
> 还有这个问题吗？因为我暂时没法测试 😂
> 
> PS：预计下午发布它~

还有问题。 没事，我先用本地的。

估计是什么网络问题导致连接不上

**Comment by Kenshin** [comment]
@bighaidao

> 估计是什么网络问题导致连接不上

emmm 服务器地址不是 `127.0.0.1` 的吗？我看到你有个类似的截图。

这样的话，可能有点问题。

**Comment by Kenshin** [comment]
![Siyuan](https://github.com/Kenshin/simpread/assets/81074/a8f839b4-90e5-4fbe-8ae9-da73b48c888c)

嗨，各位。

导入到思源笔记的插件已发布。

### 下载地址

https://simpread.ksria.cn/plugins/details/XxuF7bPTbo

### 功能

- 定制思源笔记地址（适用于 Docker 用户）

- 新建笔记本（留空则新建 SimpRead 名称的笔记本）

- 查看并选择任意笔记本
   
- 自定义导入路径

- [思源图库](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- [assets 定制](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025979) 包括：`{{title}}` 与 `{{date}}`

- [将阅读模式的图片转换为思源图床](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6026002)

- 导入全文到思源笔记

- 快捷键

- [自动化](https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-6025982)

- 在导入前可选择任意笔记本或路径

### 如何安装

1. 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
2. 已有同步助手的用户，使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装

### 注意事项

如果你使用了 Docker 版，并且域名不是 `localhost` 的话，可能会有问题。


***

我关闭这个 issues 了，但有任何使用疑问均可继续再此讨论。 😄

**Comment by yalidabuda** [comment]
大佬，导出到思源如何把原文链接一并保存，有啥办法吗？

**Comment by Kenshin** [comment]
@yalidabuda 

emmmm 确实没有 😂 等我更新插件（后就可以了）

**Comment by yalidabuda** [comment]
> @yalidabuda
> 
> emmmm 确实没有😂等我更新插件（以后就可以了）

好嘞，大佬666

**Comment by Kenshin** [comment]
嗨，各位。

思源笔记有没有类似 Obsidian `Metadata` 的功能？这样我可以把源地址放在 `Metadata` 中，这样更美观。

**Comment by mozhux** [comment]
> 嗨，各位。
> 
> 思源笔记有没有类似 Obsidian `Metadata` 的功能？这样我可以把源地址放在 `Metadata` 中，这样更美观。

无，除了多个渲染似乎没太大区别，要不用用html块？

**Comment by Kenshin** [comment]
@mozhux 

> 无，除了多个渲染似乎没太大区别，要不用用html块？

那跟直接放在原文没有区别 😂

**Comment by mozhux** [comment]
> @mozhux
> 
> > 无，除了多个渲染似乎没太大区别，要不用用html块？
> 
> 那跟直接放在原文没有区别 😂

如果只是隐藏的话，思源是有文档属性的。可以新建自定义属性。放在文档属性中。属性名英文、属性值是链接。
![image](https://github.com/Kenshin/simpread/assets/46953371/63ce2977-224d-48f1-8591-a0171a38a42d)
![image](https://github.com/Kenshin/simpread/assets/46953371/ca3f85c4-e24e-48a7-8add-9efee6d71f3d)

**Comment by Kenshin** [comment]
@mozhux

okay 研究下，感觉 API 够呛能支持 😂

**Comment by mozhux** [comment]
> @mozhux
> 
> okay 研究下，感觉 API 够呛能支持 😂

应该是有的，有个块属性的api，后面属性会支持变成属性视图，类notion那样的数据表格，应该能利用上。

**Comment by Kenshin** [comment]
@mozhux 

> 应该是有的，有个块属性的api，后面属性会支持变成属性视图，类notion那样的数据表格，应该能利用上。

okay 我看看能否用上~

**Comment by Kenshin** [comment]
嗨，各位。

> 导入到思源笔记升级到 **1.1.0** 主要增加了

- 全新的选项卡（为以后添加新功能准备）

   ![image](https://github.com/Kenshin/simpread/assets/81074/3f989bac-4d41-4f00-9b32-44667be712bb)

- 导入后显示原文链接

   ![image](https://github.com/Kenshin/simpread/assets/81074/819cbdbe-9fd9-4ad6-a4e3-8ede0365e7bb)

**Comment by yalidabuda** [comment]
> 嗨，各位。
> 
> > 导入到思源笔记升级到 **1.1.0** 主要增加了
> 
> * 全新的选项卡（为以后添加新功能准备）
>   ![image](https://user-images.githubusercontent.com/81074/246722299-3f989bac-4d41-4f00-9b32-44667be712bb.png)
> * 导入后显示原文链接
>   ![image](https://user-images.githubusercontent.com/81074/246722446-819cbdbe-9fd9-4ad6-a4e3-8ede0365e7bb.png)

666

**Comment by yalidabuda** [comment]
666

**Comment by HopeLHP** [comment]
啥时候能有导入标注到思源笔记？或者说目前已经可以实现了吗？

**Comment by Kenshin** [comment]
@HopeLHP 

暂时没有实现，排期 ing~

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
