### ISSUE TITLE
关于 Obsidain 配置库高级版方案的使用疑问

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#5556]
### 描述这个错误

图一：![image](https://github.com/Kenshin/simpread/assets/57386018/6662d9e9-b2e1-4d34-80d6-102aa87e4768)
图二：![image](https://github.com/Kenshin/simpread/assets/57386018/bf6f266f-8ced-4909-91ec-86ff628f4dc9)
图三：![image](https://github.com/Kenshin/simpread/assets/57386018/91f81cf9-59b3-4e87-a6b3-190223e58849)
图四：![image](https://github.com/Kenshin/simpread/assets/57386018/496787c8-de04-4f84-a333-23fb7d48bd6d)

### 复现步骤

1. 设置包含Output & json配置文件的config上级目录: C:\*** Documents\obsidian@sync\Obsidian@simpread\SimpRead\config\output
2. obsidian SimpRead Sync插件配置目录为：C:/*** Documents/obsidian@sync/Obsidian@simpread/SimpRead/config
3. 尝试将标注同步到obsidian时，output文件夹下显示.md， .html等多种文件格式. （如图三）
4. 预览标注格式时，显示效果比较简陋，无法套用增强导出模板，只能ctrl+P, 搜索SimpRead下24小时以内的稍后读，才能正藏显示带模板标注的标注. （如图一&图二）
5. 一站式模板下的已保存6个标注文章，能够正常打开本地标注. （如图四）

### 其他相关说明

之前有通过电报联系过大佬，但电报绑定的手机号是阿里小号或账号因为Telegram太久没用到已经卸载，记不起账号了，有机会找回账号再通过Telegram向大佬请教.

### 操作系统

Win11

### 浏览器

Microsoft Edge: 版本 113.0.1774.42 (正式版本) (64 位)

### 发生问题的网址

https://mp.weixin.qq.com/s/zINCDw53XgMxi2RmRB12LA

**Comment by Kenshin** [comment]
感觉你的文件路径太复杂了，容易出问题。（对于初次配置来说）

看图四的话，你应该用了配置库方案，是吧？

你试试在图四的基础上在右侧增加标注，能否更新到左侧？如果能的话，说明 Obsidian 这边的设置没问题。

**Comment by mdsnalw** [comment]
> 感觉你的文件路径太复杂了，容易出问题。（对于初次配置来说）
> 
> 看图四的话，你应该用了配置库方案，是吧？
> 
> 你试试在图四的基础上在右侧增加标注，能否更新到左侧？如果能的话，说明 Obsidian 这边的设置没问题。

是的，就是用的配置库方案。那我再精简下路径，换个主目录再重新尝试下. 
另外，我尝试了在已有的文章做编辑，已经无法做任何标注了. 我还是重新按教程进行一遍配置，有问题再通过此issue做进一步反馈.

**Comment by Kenshin** [comment]
> 我尝试了在已有的文章做编辑，已经无法做任何标注了

那就是还是路径有问题。

> 有问题再通过此issue做进一步反馈.

okay

***

综上，一个建议：

`C:*** Documents\obsidian@sync\Obsidian@simpread\SimpRead\config\output` 太复杂了，新用户的话，建议把它们放在不同的地方 e.g.

- `C:*** Documents\Obsidian@simpread\SimpRead` → Obsidian 库文件
- `C:*** Documents\SimpRead` → SimpRead 文件夹，包括 `simpread_config.json` 与 `output`

然后确保配置库的路径正确，后在测试。

等熟悉了这套环境后，再按照你自己的想法优化。

**Comment by mdsnalw** [comment]
![image](https://github.com/Kenshin/simpread/assets/57386018/ea4391b5-4477-49d4-9be5-637f43c9bc7f)

> C:*** Documents\Obsidian@simpread\SimpRead → Obsidian 库文件 
- 库文件目录是选到“Obsidian@simpread”这个文件夹来添加吗，还是选到“*** Documents”？
- 如果选到**“*** Documents”**，就没办法识别到默认的4个插件. 

> C:*** Documents\SimpRead → SimpRead 文件夹，包括 simpread_config.json 与 output
- 如果选到**“Obsidian@simpread”**，“SimpRead 文件夹” 就会变成库外的内容. 

补充下相关配置截图：
![image](https://github.com/Kenshin/simpread/assets/57386018/eeabe6ea-0bef-4409-af0e-53d78a4ca07c)
![image](https://github.com/Kenshin/simpread/assets/57386018/ac73d636-5f4b-4c7d-8568-1f88da1d441d)

PS：之前已经有维持了一个相对稳定的配置库用了个把月了，不巧公司电脑出了问题，重装了，不然也不会再折腾~. 虽然保存了UID和配置文件，但好像也只能重新来过，导入配置后还是出错.

**Comment by mdsnalw** [comment]
大佬，我可以把配置库文件夹打包给你，你帮我调整下文件夹结构吗？主要是新的库，也不会有太大的空间占用. [没理解这个配置逻辑，所以走了不少弯路= =
[Obsidian.zip](https://github.com/Kenshin/simpread/files/11485128/Obsidian.zip)

**Comment by Kenshin** [comment]
> 大佬，我可以把配置库文件夹打包给你，你帮我调整下文件夹结构吗？主要是新的库，也不会有太大的空间占用. [没理解这个配置逻辑，所以走了不少弯路= =

可以，不过我来弄的话，跟配置库其实是没有区别的。 😂

还是说，你给我的 zip 也包括 Obsidian 库？

**Comment by mdsnalw** [comment]
赶上直播了，辛苦帮忙看下，老是问题出在哪里，谢谢~



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年05月16日 11:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 高级账户在网页端配置好后，无法使用增强导出模板功能 (Issue #5556) |

我尝试了在已有的文章做编辑，已经无法做任何标注了

那就是还是路径有问题。

有问题再通过此issue做进一步反馈.

okay

综上，一个建议：

C:*** ***@***.******@***.***\SimpRead\config\output 太复杂了，新用户的话，建议把它们放在不同的地方 e.g.

C:*** ***@***.***\SimpRead → Obsidian 库文件
C:*** Documents\SimpRead → SimpRead 文件夹，包括 simpread_config.json 与 output

然后确保配置库的路径正确，后在测试。

等熟悉了这套环境后，再按照你自己的想法优化。

**Comment by mdsnalw** [comment]
> 还是说，你给我的 zip 也包括 Obsidian 库？
- 就是下载的默认配置库后，我微调后的主库的压缩包，主要是如果带配置文件的SimpRead文件夹，放在库外，导入obsidian的markdown标注也在库外，不知道是不是我理解错了,不太清楚如何调整.

**Comment by mdsnalw** [comment]
> 把你的 obsidian 库和简悦的配置文件打包，发送到 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5556
> 
> 我一会帮你试试。

谢谢！那我重新回复下邮件，并调整标题

**Comment by Kenshin** [comment]
我在看你给的 `zip` .... 

有个问题，因为我是 Mac 系统，其实可以帮你调整的地方不多... 😂

这套方案，需要设置路径的地方：

1. 同步助手
2. Obsidian SimpRead Sync
3. 浏览器 Obsidian 插件（设置两个目录）

因为咱们的系统不一样，再加上1 和 2 都没有配置文件（也就是说：无法给你），所以 1 和 2 我都没法帮你设置... 

我把 Mac 下一些截图给你吧。

***

> 我的配置文件文件夹与 Obsidian 库文件夹是在不同的地方

为了方便你理解，我按照 Windows 的路径给出

### 简悦配置文件夹

 `C:\Users\kenshin\SimpRead` 下图是它的结构

<img width="294" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3292d9a2-2628-4be0-a545-bfd2559dc111">

对应的同步助手需要留意下面的路径

<img width="679" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/51fc2eff-e49d-493d-b114-b8f59b4db84d">

<img width="679" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4263f0df-179e-48bb-83ef-c6bbb60a8c6d">

### Obsidian 库文件夹

假设在 `C:\Users\kenshin\Obsidian@simpread` 下图是它的结构

<img width="287" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fde73e28-ebc9-425b-a795-5e0db899492c">

### 导入到 Obsidian 插件

根据上图所示的路径设置对应的库文件夹和目录文件夹

<img width="1640" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/70b34ab3-9987-43ff-8f95-9ccd33167690">

### Obsidian SimpRead Sync

根据同步助手给出的路径设置

<img width="1845" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c19aca95-9669-4369-9f44-3223055777c8">

**Comment by Kenshin** [comment]
另外，还有一点，留意下 ob 版本的问题 https://github.com/Kenshin/simpread/issues/5558#issuecomment-1549015672

**Comment by mdsnalw** [comment]
由衷感谢大佬，目前来看应该是Installer Version的问题，安装了1.16的obsidian就导出正常，为了保险起见，我还是先禁用更新观望一段时间，再次感谢！
![image](https://github.com/Kenshin/simpread/assets/57386018/03a39bd7-8d4f-4291-b6f5-8f2e686d67a2)
![image](https://github.com/Kenshin/simpread/assets/57386018/d99cdbf0-eed8-48b4-b77c-f489d2bc35a4)

**Comment by Kenshin** [comment]
不用，保证 Installer 低于 1.2 你仍可以正常升级到 1.2.8 
 
Installer 可以理解为「引擎」，跟 Obsidian 本身没有关系。

**Comment by mdsnalw** [comment]
> 不用，保证 Installer 低于 1.2 你仍可以正常升级到 1.2.8
> 
> Installer 可以理解为「引擎」，跟 Obsidian 本身没有关系。

明白了，多谢大佬指点，补上之前电报上答应过的Chrome上评价，虽迟但到:)
![image](https://github.com/Kenshin/simpread/assets/57386018/ad6c6e37-354d-4269-ad9d-c2c07582898a)

**Comment by Kenshin** [comment]
哈哈，谢谢评分~

原来在 Telegram 联络过我 😂

**Comment by Kenshin** [comment]
关于 Installer 1.2.8 导致无法导出的问题，我也遇到了，但又好使了... 

你可以测试以下方案：

1. 确保 simpread sync 插件的 Obsidain 仅开一个库。
2. 重启电脑

**Comment by Kenshin** [comment]
关联问题 https://github.com/Kenshin/simpread/issues/5556
