### ISSUE TITLE
微信阅读不能适配

### ISSUE THREAD

**Issue by potatoyz** [Kenshin/simpread#5557]
### 描述这个错误

使用微信阅读不能用简悦

### 复现步骤

打开微信阅读
点击插件
失败
手动高亮
失败

### 操作系统

Win11

### 浏览器

Edge

### 发生问题的网址

https://weread.qq.com/web/reader/2f632f00718f638b2f6cb74k8f132430178f14e45fce0f7

**Comment by Kenshin** [comment]
嗨，微信读书是不可以被适配的，我关闭这个 Issues 了。
