### ISSUE TITLE
Obsidan Installer 为 1.2.x 版时，无法使用简悦自动导入到 Obsidian 的问题（附解决方案）

### ISSUE THREAD

**Issue by rjs520** [Kenshin/simpread#5558]
### 描述这个错误

在更新ob1.2.7之后，简悦就无法导入全文到ob，ob1.2.7卸载之后重新安装1.1.6，就又好了，文件夹目录啥的从始至终就没边过，唯一的改变就是更新了ob

### 复现步骤

和语雀的配置库一模一样，唯一的区别就是更新了ob

### 操作系统

Windows11

### 浏览器

chrome，edge

### 发生问题的网址

https://sspai.com/prime/story/password-autogen

**Comment by rjs520** [comment]
ob卸载1.2.7再次安装1.1.6，功能恢复，但是ob总不能再也不更新吧

**Comment by Kenshin** [comment]
嗨，确实有用户提过类似的情况，但我这边没有复现过（用的也是配置库方案），我正好在研究这个问题。

> ob卸载1.2.7再次安装1.1.6，功能恢复，但是ob总不能再也不更新吧

不需要，准确的说，只要 Installer 小于 1.2 就行，但并不耽误 Obsidain 的升级，e.g. 最新版 Version 1.2.8
 
<img width="229" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3557d412-60d6-4880-8731-50276d4f1558">

你可以临时使用这种方案。

我再详细调查下，然后再回复你。

**Comment by Kenshin** [comment]
嗨，我用了配置库的 Obsidian 高级版方案，还是没有复现...

你可以试试确保仅打开 Obsidian 一个库（有 SimpRead Sync 的那个库），然后重启 Obsidain，并且按照下图所示打开

<img width="1609" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/01b5e3a2-e6fe-45ed-a033-179d9e7c5ce6">

看看有没有报错。

**Comment by Kenshin** [comment]
另外一点：

你可以试试，再重新配置一个新的环境，还是用同样的 Obsidain 配置库高级版，然后按照下面的截图改

<img width="1992" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/df5e1218-7567-4ef6-9e5d-c41188391e4e">

看看能否导入成功？

注意：一定要留存好你之前的 `simpread_config.json` （以免被覆盖）

**Comment by rjs520** [comment]
我从1.1.6直接更新到1.2.8，似乎没有这个问题了，可以导入了，可能是1.2.7独有的bug

**Comment by Kenshin** [comment]
> 我从1.1.6直接更新到1.2.8

你看下你的 Installer 是什么版本？截图给我。

**Comment by rjs520** [comment]
![image](https://github.com/Kenshin/simpread/assets/87847751/e94c7ea9-1686-42c8-82e6-09818f1e3606)

**Comment by Kenshin** [comment]
关于 Installer 1.2.8 导致无法导出的问题，我也遇到了，但又好使了... 

你可以测试以下方案：

1. 确保 simpread sync 插件的 Obsidain 仅开一个库。
2. 重启电脑

**Comment by ychen-97** [comment]
我也遇到了，我暂时用 将标注以Markdown2.0形式导出插件 （作者说一般给logseq用的），还有设置了导出目录在Obsidian的库里 代替了导出到Obsidian插件

**Comment by Kenshin** [comment]
@ychen-97 

emmm 有点意思…

这两插件应该再导入方面都代码是一模一样的。

我今天研究下。 😂

**Comment by RyanKing1990** [comment]
@ychen-97 我也想过用Markdown2.0插件来代替，obsidian本质上也就是md文件的编辑器嘛，而且使用简悦时还不用obsidian处于活动状态。
@Kenshin 大佬，通过这两个插件生成的md文件有区别吗？可不可以合二为一，这样可以增加简悦插件的适用性，基于md文件的各类笔记软件都可以使用。
我通过卸载obsidian1.2.8，重新安装1.16，后面软件更新到1.2.8，功能恢复了，可以自动导出标注md了。请问一下，这原因可能出在哪里？安装1.2.8版本，和自动更新到1.2.8又什么区别吗？

**Comment by Kenshin** [comment]
@RyanKing1990 

> 通过这两个插件生成的md文件有区别吗？可不可以合二为一

一个是给 Obsidian 用户使用的，一个是给非 Obsidian 使用的。

不过，我上条说的有问题（所以删了），这两个插件的实现方式是不一样的。

- `标注以Markdown2.0形式导出插件` 是通过同步助手的功能。
- `Obsidian 插件` 使用方案3的话，是通过 Obsidian SimpRead Sync 完成的。

> 我通过卸载obsidian1.2.8，重新安装1.16，后面软件更新到1.2.8，功能恢复了，可以自动导出标注md了。请问一下，这原因可能出在哪里？安装1.2.8版本，和自动更新到1.2.8又什么区别吗？

前几天确实有用户报告过，也就是这个 Issues 上面的内容，我也遇到了，但第二天重启电脑后，无故就好使了。

我检查了下，肯定是 Obsidian 那边的「问题」，而问题现象很有意思：

1. 在阅读模式下通讯失败（所以同步失败）
2. 在 http://localhost:7026/unread/xxx 下就没问题。
3. 在 Obsidian 右侧栏的方式也没问题。

但我没法复现...

还有一点：发生问题的时候，会频繁切换不同的 Obsidian 库吗？

**Comment by RyanKing1990** [comment]
@Kenshin 没有，我就一个库，all in one

**Comment by Kenshin** [comment]
@RyanKing1990 
 
😂 我曾经遇到一次，因为频繁更换库又复现了这个问题，但重启电脑后就没问题了。

**Comment by Kenshin** [comment]
嗨，各位，这个问题应该可以解决了。

不需要改动 Obsidian SimpRead Sync 插件，只需要修改简悦的 Obsidian 插件，修改如下：

<img width="607" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1b6f2802-dbd6-41fb-883a-522dadfdb1d4">

也就是下图

<img width="610" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e8f9d709-21b2-4273-996c-f802fde3a9d1">

然后：

1. 保存并重启浏览器，确认修改生效。
2. 重启 Obsidian
