### ISSUE TITLE
反向链接建议

### ISSUE THREAD

**Issue by SrSh-notme** [Kenshin/simpread#5560]
### 请描述你的建议或任何内容

稍后读里标注显示的反向链接

如果有本地离线html，建议优先使用本地链接，这样不论是直接访问还是markdown导出即使网页都是在的。方便归档和链接。

访问原网页的话感觉不是那么顺手。

BTW，听说思源笔记的导出马上就要出来了，哈哈哈，欢欣鼓舞啊

**Comment by Kenshin** [comment]
> 听说思源笔记的导出马上就要出来了，哈哈哈，欢欣鼓舞啊

是的，请别着急 😂 😄

> 稍后读里标注显示的反向链接

可以显示本地快照的，主要看在于模板或者说你想要在什么地方使用了。

**Comment by SrSh-notme** [comment]
> > 稍后读里标注显示的反向链接
> 
> 可以显示本地快照的，主要看在于模板或者说你想要在什么地方使用了。

![IMG_0157](https://github.com/Kenshin/simpread/assets/48594308/263d4dcc-cf6b-420d-a83f-13fd5ee5b215)

今天图片能上传了，昨天讲的不是很清楚。上图中的链接不是本地链接，而是原文网页链接。还有就是markdown 导出来的也是原文的网页链接，不能直接链接到本地文件。

![IMG_0158](https://github.com/Kenshin/simpread/assets/48594308/d5d3e556-8dfc-48ec-8ea2-fd2adeef87e6)

怎么操作才能让原文链接变成本地离线html的链接

**Comment by Kenshin** [comment]
> 图一

你用的应该是简悦自身的双链方案吧？简悦的双链方案跟是否是本地链接无关。

> 原文链接变成本地离线html的链接

你是说图二吗？但图二哪个功能的截图？😂

一般来说简悦的本地链接都是 http://localhost:7026/reading/xxx 的形式，用于导入 Obsidian / Logseq 时使用。

**Comment by SrSh-notme** [comment]
> 你是说图二吗？但图二哪个功能的截图？😂
> 
> 一般来说简悦的本地链接都是 http://localhost:7026/reading/xxx 的形式，用于导入 Obsidian / Logseq 时使用。

标注导出MarkDown文件

**Comment by SrSh-notme** [comment]
> > 图一
> 
> 你用的应该是简悦自身的双链方案吧？简悦的双链方案跟是否是本地链接无关。
> 
> > 原文链接变成本地离线html的链接
> 

对，简悦稍后读里头的双链

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5560#issuecomment-1552355415

使用简悦的反向链接导出的 Markdown ？是可以设置的，看下图效果

<img width="1229" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d6f2437f-ec8f-4a60-8663-5be28b03d337">

选项页 → 服务

<img width="1245" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b8158a84-8df4-47b3-a860-17e6e1893f10">

然后复制粘贴下面的代码上上图

```
  > 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址 [{{host}}]({{url}})

  - 描述
  > {{desc}}

  - 备注
  {{>|note}}

  - 标签
  > {{tags}}

  > 建立时间：{{create}}

  > 关联阅读：
  >
  {{> |backlinks}}

  > 外部引用：
  >
  {{> |refs}}

  ***

  {{#each}}

  - 时间
    {{an_create}}

  - 标注
  {{  >|an_html}}

  - 备注
  {{  >|an_note}}

  - 标签
    {{an_tags}}

  - 关联
  {{  |an_backlinks}}

  - 外部引用
  {{  |an_refs}}

  - 链接
    - [原链接](<{{an_org_uri}}>)
    - [内部链接](<{{an_int_uri}}>)
    - [外部链接](<{{an_ext_uri}}>)

  - 引用来源
    - [{{an_text}}](<{{an_ext_uri}}>)

  ***

  {{/each}}
```

接下来把这段代码 `[[{{id}}{{un_title}}]]` 粘贴到下图所示地方

<img width="893" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/56f83597-e10a-4f9b-bbd4-9412226fb806">

刷新当前页面（最好重启浏览器），确保上面的设置生效。

最后，重新进入稍后读中，再次调出。

### 注意

1. 这个方式的本地快照不是 HTML 而是 Markdown
2. 需要实现已经导出了反向链接对应的 Markdown
3. 此方式属于 Markdown 模板 1.0 的引擎，现在已经是 2.0 但它们的逻辑不太一样，并不是单纯的替换关系，但 2.0 是可以兼容 1.0 方案的，关于 2.0 方案的细节看 https://github.com/Kenshin/simpread/discussions/3725

简单的说，如果你需要在简悦的稍后读并使用简悦的反向链接，就使用 1.0 引擎；反之，是 Obsidian 的重度用户，就使用 2.0 引擎。
