### ISSUE TITLE
关于全文翻译插件的两点建（wang）议（xiang）

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5561]
### 请描述你的建议或任何内容

1. 能否将标题也纳入翻译范围？
2. 分段翻译能否加装中英文左右分栏显示选项？

### 补充说明

全文唯独标题没法双语对照；长段落上下排列阅读时多有不便

**Comment by Kenshin** [comment]
哈，挺好的建议，我考虑下。

> 分段翻译能否加装中英文左右分栏显示选项？

左右分栏的话，有个问题：对于导出功能来说并不友好。

**Comment by Kenshin** [comment]
哈，我想想怎么实现吧。

**Comment by Kenshin** [comment]
嗨，全文翻译升级到 1.2.0 增加你提到的功能：

1. 标题和描述加入翻译范围
2. [中英文左右分栏显示](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6046769)

同时重构了段落的获取逻辑，基本上再复杂的段落结构也可以胜任。

我关闭这个 issues 了，有任何问题仍可以随时在这里提问。

😄

**Comment by PupupupuTong** [comment]
赞美大大！！！现在盲区就剩一个侧边目录了

**Comment by Kenshin** [comment]
哈哈，目录暂时就先这样吧 😂 （ 这个不太好调整。

PS：左右栏翻译的时候有点问题，个别页面会出现无法对照的情况，这点需要留意下。

**Comment by Kenshin** [comment]
蹲个五星好评~

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
