### ISSUE TITLE
ob跳转内部链接失效

### ISSUE THREAD

**Issue by xavierQin** [Kenshin/simpread#5565]
### 请描述你的建议或任何内容

使用了导出ob的配置文件，都可以使用，就是标注的文件点击跳转内部链接的图标后，跳转的新页面显示（{"code":404,"message":"没有找到对应的内容"}）

**Comment by Kenshin** [comment]
这个页面的 URL 是多少？e.g. 来说应该是 http://localhost:7026/reading/xxx

检查下 `output` 文件夹是否存在 `xxxx` 这个标号的 HTML 文件，如果没有的话，说明本地快照没有生成。

本地快照的教程 https://www.yuque.com/kenshin/simpread/wkswh7 对比下跟你的区别是什么。

**Comment by xavierQin** [comment]
output里有快照，ob里也相应的生成了两篇笔记，一篇原文，一篇标注。但是点击跳转内部链接后，提示找不到
![image](https://github.com/Kenshin/simpread/assets/133442501/cf163764-5913-47a8-aba5-9f91cb1aa8c4)

**Comment by Kenshin** [comment]
内部链接的 id 是什么？😂

你给的信息太少了，我没法帮到你…

**Comment by PenguinWang123** [comment]
我也碰到了同样的问题，output文件夹里有本地快照文件，但是点击内部链接提示找不到。链接：http://localhost:7026/unread/43#id=1686315682956
<img width="352" alt="截屏2023-06-09 21 13 33" src="https://github.com/Kenshin/simpread/assets/117373536/a02ec555-10c2-42a9-9672-2997c9d70ce6">

**Comment by PenguinWang123** [comment]
我好像明白了，是不是要定位内部链接必须标题得要有ID数字

**Comment by Kenshin** [comment]
@PenguinWang123 

根据你给的例子，你在本地的 output 里面应该有个 `43-xxx.html` 的文件

**Comment by PenguinWang123** [comment]
> @PenguinWang123
> 
> 根据你给的例子，你在本地的 output 里面应该有个 `43-xxx.html` 的文件

所以是不是标题前面的那个数字必须要有，删了的话就无法打开内部链接了？

**Comment by Kenshin** [comment]
> 所以是不是标题前面的那个数字必须要有，删了的话就无法打开内部链接了？

是的

**Comment by qwq2020** [comment]
> 内部链接的 id 是什么？😂
> 
> 你给的信息太少了，我没法帮到你…

你好，我也遇到了这个问题，情况和楼主一样，你这里说的id怎么查？还有怎么排查404的原因呢？

**Comment by Kenshin** [comment]
@qwq2020 

方法已经给出了 https://github.com/Kenshin/simpread/issues/5565#issuecomment-1552333385

还有看下这个 Issues 的对话内容。
