### ISSUE TITLE
ob中的标注md文件没有同步

### ISSUE THREAD

**Issue by zqz365001** [Kenshin/simpread#5566]
### 描述这个错误

obsidian中的标注md文件没有同步，只同步了保存的离线文件html。查看了simpread_config.json有更新。出现这个问题前 自动更新了obsidian1.2.8，之前是可以生成md文件的。我还以为是我json配置文件出错了，导入N次，在obsidian中，还是无法生成md文件
![image](https://github.com/Kenshin/simpread/assets/27180737/072b0645-ab7c-4412-a39c-8c629bfef5ad)
![image](https://github.com/Kenshin/simpread/assets/27180737/c348dbd4-bb7f-4515-b0ea-dcf90f84eade)

### 复现步骤

进行正常的标注即可

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)
也使用了chrome  版本 113.0.5672.94（正式版本） （64 位）
### 发生问题的网址

https://zhuanlan.zhihu.com/p/343854552?simpread_mode=read

**Comment by zqz365001** [comment]
![image](https://github.com/Kenshin/simpread/assets/27180737/e52150a6-1e01-44ca-9f68-17b36d861a43)
我解决问题了。当前版本是1.2.8，安装程序版本如果是v1.1.16就能把md文件同步到obsidian中。如果当前版本是1.2.8，安装程序版本是v1.2.7就无法同步md到obsidian

**Comment by Kenshin** [comment]
嗨，确实有这个情况，但我没法复现 😂 （我也确实遇到过一次，但重启电脑后无故好使了...

细节的话，请看这里 https://github.com/Kenshin/simpread/issues/5558#issuecomment-1548960228

最简单的方案，确保 Installer 小于 1.2 就行了（并不耽误 Obsidian 的升级）。

我在研究下能否不用等 Obsidian 升级解决。

PS：这个问题跟同步助手无关，就是 Obsidian Installer 的问题。

**Comment by Kenshin** [comment]
我先关闭 这个 Issues 了，并汇总到 https://github.com/Kenshin/simpread/issues/5558 有后续的方式我会继续在这里通知的。

**Comment by zqz365001** [comment]
好的，好的😇
