### ISSUE TITLE
标注查看问题

### ISSUE THREAD

**Issue by snow-nene** [Kenshin/simpread#5568]
### 请描述你的建议或任何内容

当我在阅读模式下移动到标注的N字母上进行标注查看的时候，我发现下方的白色滚动条宽度过大，已经和下方字体发生了部分接触，请问有什么办法可以设置这个滚动条的宽度？

**Comment by Kenshin** [comment]
嗨，请截图说明 😂 

另外，单看文字说明并没有遇到你说的问题。

<img width="642" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c9b5ed93-4163-407b-b728-df0f9c8fb53e">


<img width="650" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/06dac366-55e8-4e5a-a82a-5c2f5243ae7e">

**Comment by snow-nene** [comment]
<img width="462" alt="image" src="https://github.com/Kenshin/simpread/assets/113535139/551ce7f5-5cbc-437c-ab72-abf49cde2102">
没有这种问题可能是因为文字没有达到触发长度
