### ISSUE TITLE
语雀一直不能同步

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5570]
### Discussed in https://github.com/Kenshin/simpread/discussions/5569

<div type='discussions-op-text'>

<sup>Originally posted by **rcx100** May 19, 2023</sup>
简悦已升级到高级账户，但是语雀一直不能同步，总是在连接语雀以后提示授权失败，
<img width="538" alt="111119" src="https://github.com/Kenshin/simpread/assets/4495383/e31aa3b9-3801-425f-aa07-36d87f41d1f4">
</div>

**Comment by Kenshin** [comment]
@rcx100

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

1. 此功能跟是否是高级账户无关，这是基础账户功能。
2. 请在选项页 → 服务（也就是你的截图）中授权，不要在阅读模式下授权。
3. 当授权并且确定授权成功后，重启浏览器。

**Comment by rcx100** [comment]
![image](https://github.com/Kenshin/simpread/assets/4495383/92401cfa-d685-4f61-a85c-d743ef5d21db)

按照流程来还是不行，老是提示授权失败 不知道是什么原因有排查思路吗

> @rcx100
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 1. 此功能跟是否是高级账户无关，这是基础账户功能。
> 2. 请在选项页 → 服务（也就是你的截图）中授权，不要在阅读模式下授权。
> 3. 当授权并且确定授权成功后，重启浏览器。

**Comment by Kenshin** [comment]
1. 在安装简悦时，是否做了某些权限限制？
2. 浏览器是否做了特别的设置 e.g. Cookie 验证等？

要是方便的话，最好用个全新的浏览器测试。（不需要使用高级账户，仅安装简悦，然后登录语雀，最后在简悦中授权）
