### ISSUE TITLE
配置同步长时间未响应

### ISSUE THREAD

**Issue by Qiup7664** [Kenshin/simpread#5571]
### 描述这个错误

我在公司电脑配置完插件后，回家用mac同步先前的配置失败。使用同步助手强制覆盖也失败？（导入配置后，插件无法显示后台）

### 复现步骤

1.安装完插件后，通过坚果云授权高级账户
2.从本地导入配置文件失败
3.通过同步助手同步配置
4.导入配置后，会长时间卡在过长动画。。。

### 其他相关说明

<img width="681" alt="image" src="https://github.com/Kenshin/simpread/assets/56213419/c4c2ac43-a0c1-4583-a9b1-08edb6714b53">

### 操作系统

macos

### 浏览器

chrome

### 发生问题的网址

www.baidu.com

**Comment by Qiup7664** [comment]
感觉同步助手真的很影响体验，配置过程中，会回退。最后导出的配置文件也有问题。即便是导入backup里的配置文件，依然无法使用。

**Comment by Kenshin** [comment]
> 配置过程中，会回退。

说明你的配置被互相覆盖了。建议看下 https://github.com/Kenshin/simpread/discussions/3768

> 导入配置后，会长时间卡在过长动画。。。

如果一直停留在这个界面的话，说明你的配置文件损坏，解决方案 https://www.yuque.com/kenshin/simpread/lwuterg3u83sq0b2
