### ISSUE TITLE
在ob插件中进行标注，不会更新标注的本地文件

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#5572]
### 描述这个错误

之前已经自动导入ob的标注，后续在ob插件中进行补充标注，发现坚果云Output文件夹中可以更新原文的本地快照，不会更新标注的本地文件。
不知道是不是bug，或者本来就应该这样？

### 复现步骤

1. ob中打开对应导入的标注文档
2. 点开标注的内部链接，在右侧自动打开全文+标注界面
3. 继续添加标注
4. output文件夹的原文.html文件更新，@annote.html文件不更新

### 操作系统

macos

### 浏览器

edge112.0.1722.58正式版

### 发生问题的网址

https://mp.weixin.qq.com/s/z4ObOSepVcbhC-6TvJB4GQ

**Comment by Kenshin** [comment]
嗨

是的，目前是这样的，因为更新机制的缘故，所以暂时不会生成 `@annote.html` 因为其实没有必要，因为已经存在 `@annote.md` 了。

**Comment by HopeLHP** [comment]
那我在ob简悦插件中点击手动导入的按钮，会覆盖@annote.md，它覆盖导入的Annote的来源不是@annote.html吗？这样我就不理解@annote.html快照的作用在哪？

**Comment by Kenshin** [comment]
> 这样我就不理解@annote.html快照的作用在哪？

不是每个简悦用户都使用 Obsidain... 使用 Obsidian 的用户就没有必要使用 `@annote.html` 

> 它覆盖导入的Annote的来源不是@annote.html

简悦的数据来源全部都是 `simpread_config.json`
