### ISSUE TITLE
点击导入批注进入obsidian，显示保存失败

### ISSUE THREAD

**Issue by RyanKing1990** [Kenshin/simpread#5574]
### 描述这个错误

采取的方案是同步助手、SimpRead Unreader Sync插件实现简悦阅读批注，并把数据导入obsidian。之前，用得好好的，通过简悦阅读模式，批注自动生成批注md文件和原文（含批注）html。前段时间开始，出现以下问题：
1.阅读模式下批注可以生成原文（含批注）html，但无法自动生成批注md，导入obsidian；
2.点击导入批注到obsidian显示“保存失败”

### 复现步骤

![导入obsidian插件设置](https://topspace1990.oss-cn-guangzhou.aliyuncs.com/img/202305202141059.png)
![自动化辅助增强插件设置](https://topspace1990.oss-cn-guangzhou.aliyuncs.com/img/202305202143218.png)
![同步助手设置](https://topspace1990.oss-cn-guangzhou.aliyuncs.com/img/202305202146190.png)
![扩展端-高级设定-标注](https://topspace1990.oss-cn-guangzhou.aliyuncs.com/img/202305202148170.png)
![扩展端-服务-增强导出和自动化](https://topspace1990.oss-cn-guangzhou.aliyuncs.com/img/202305202150117.png)

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s

**Comment by Kenshin** [comment]
嗨，近期是不是重新安装了 Obsidian （不是升级）

看下是否是这个问题 https://github.com/Kenshin/simpread/issues/5558#issuecomment-1549010934

**Comment by ychen-97** [comment]
这个方法或许是一个workaround https://github.com/Kenshin/simpread/issues/5558#issuecomment-1555956749
