### ISSUE TITLE
稍后读标注模式笔记排列顺序

### ISSUE THREAD

**Issue by 152j** [Kenshin/simpread#5575]
### 请描述你的建议或任何内容

希望在接下来的版本中，在稍后读做笔记划线时，默认的笔记顺序是按照原文的逻辑排序的。
即，现在，如果原文有1、2、3段，现在我如果先在1、3段划线做了笔记，然后再在第2段划线做笔记，那在标注模式中，最后展示出来的标注笔记顺序就是1、3、2
我希望的则是，当我先在1、3段做了划线笔记，再在第2段做划线笔记时，在标注模式中，它展示给我的依然是按照原文原有的行文逻辑，即1、2、3的顺序向我展示

**Comment by Kenshin** [comment]
选项页 → 高级设定 → 标注，有个选项可以按照自然段落的顺序显示。

**Comment by Kenshin** [comment]
补一个截图

<img width="943" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e830999d-aa1c-4040-a563-25d890106d56">
