### ISSUE TITLE
能否支持排序右侧浮动侧标栏？

### ISSUE THREAD

**Issue by JIeJaitt** [Kenshin/simpread#5577]
### 请描述你的建议或任何内容

如下图所示，简悦已经支持删减不需要使用的栏目了，但是我🤔️想让复制markdown内容到剪贴板功能排在最前面，我总不能把该选项前面的功能全部取消吧。所以希望能支持排序浮动栏，谢谢。

<img width="668" alt="image" src="https://github.com/Kenshin/simpread/assets/77219045/2ea7ec8b-c145-4b36-acc6-5b11707722eb">

### 补充说明

无

**Comment by Kenshin** [comment]
暂时不支持 😂

你可以使用 https://github.com/Kenshin/simpread/discussions/1600 这个方式更好些。
