### ISSUE TITLE
无法从本地文件配置登录高级账户，显示后台异常

### ISSUE THREAD

**Issue by YUE23333333** [Kenshin/simpread#5578]
### 描述这个错误

因为电脑出了些问题，刚重装了电脑，在重新登陆简阅的时候显示“由于后台异常导致恢复购买失败，请稍后再试。”重启浏览器多次重复依旧。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/134189928/1fdd6265-5fc8-4864-b66a-9eb895f3869c)
1，从本地配置文件登录
2，右上角显示成功，但是一会就会弹出这个界面，显示“由于后台异常导致恢复购买失败，请稍后再试。

### 操作系统

win10

### 浏览器

Google Chrome，版本 113.0.5672.127（正式版本） （64 位）

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#account

**Comment by Kenshin** [comment]
> 从本地配置文件登录

你导入的可能是 `simpread-内含xxx.json` 吧？如果是的话， 不应该导入这个文件。

用文本编辑器把这个文件打开，然后找到 UID 对应的内容，然后使用 https://www.yuque.com/kenshin/simpread/pkq3d1 重新授权。

**Comment by YUE23333333** [comment]
使用方案一，输入uid后仅授权登录当前设备任然显示：由于后台异常导致恢复购买失败，请稍后再试。“；
使用方案二，导出的文件uid为已经购买的uid账户，(￣﹏￣；)
大大，我这是不是没救了，/(ㄒoㄒ)/~~

**Comment by Kenshin** [comment]
把你的 `impread-内含xxx.json` 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5578

另外，在安装简悦的时候需要确保此权限 https://www.yuque.com/kenshin/simpread/tmmwhl 已开启。
