### ISSUE TITLE
简悦会导致curseforge网站页面加载空白

### ISSUE THREAD

**Issue by joamg** [Kenshin/simpread#5580]
### 描述这个错误

打开[curseforge](https://www.curseforge.com/)网站会导致页面空白, 就会出现如图这种情况, 关闭简悦即正常
<img width="1440" alt="image" src="https://github.com/Kenshin/simpread/assets/34476014/4d8a19b5-b34e-4fb6-b25d-86012e1b64c3">

### 复现步骤

打开 [curseforge](https://www.curseforge.com/) 即可

### 操作系统

macOS 11.7.3

### 浏览器

Chrome Version 113.0.5672.126 (Official Build) 

### 发生问题的网址

https://www.curseforge.com/

**Comment by Kenshin** [comment]
嗨，解决方案看下图

![image](https://github.com/Kenshin/simpread/assets/81074/d77fbbaa-a2c3-4fd2-93ac-d8b05a5b31fb)

**Comment by joamg** [comment]
关闭后, 已解决

**Comment by Kenshin** [comment]
okay 解决就好。
