### ISSUE TITLE
通过简悦插件保存掘金技术博客到“语雀”，但图片丢失

### ISSUE THREAD

**Issue by Victory-x** [Kenshin/simpread#5584]
### 描述这个错误

掘金技术博客：https://juejin.cn/post/7209625823580766264?#heading-0
通过简悦插件，保存整个文章，但是丢失里面的大量图片

### 复现步骤

1.访问网站：https://juejin.cn/post/7209625823580766264?#heading-0
2.点开浏览器简悦插件访问网站；
3.点击“动作”，保存到语雀；
4.查看语雀已保存的文章，就会发现丢失了文章里的图片。

### 操作系统

window 11

### 浏览器

Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)

### 发生问题的网址

https://juejin.cn/post/7209625823580766264?#heading-0

**Comment by Kenshin** [comment]
关于这个问题的解释，可以看 https://github.com/Kenshin/simpread/issues/5532#issuecomment-1537671813

**Comment by Victory-x** [comment]
好的，感谢感谢！

**Comment by Kenshin** [comment]
小事情 😄

**Comment by Victory-x** [comment]
最终通过简悦插件，复制Markdown到粘贴板，然后再放到Typora，最后复制到语雀也可以解决图片丢失问题。

**Comment by Kenshin** [comment]
> 最后复制到语雀也可以解决图片丢失问题。

emmm 跟 https://github.com/Kenshin/simpread/issues/5584#issuecomment-1558465782 提到的方式类似。

应该语雀得到 Typora 的内容后自动转换为它自己的网盘了。
