### ISSUE TITLE
关于同步助手的自动同步疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5587]
![1685000632897](https://github.com/Kenshin/simpread/assets/127119682/642d8698-5e22-4f30-9ff5-9cc3007fe9ff)
我明明早就把它关了，但它总是这样弹出来，不管我保存什么，总是让我重新关

_Originally posted by @huaguoxingkong in https://github.com/Kenshin/simpread/discussions/1700#discussioncomment-5997959_

**Comment by Kenshin** [comment]
@huaguoxingkong

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

显然你没有关闭...

确保关闭，然后重启浏览器

<img width="886" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/395dfefc-8f16-4943-b53d-cf096646a74c">

**Comment by huaguoxingkong** [comment]
不是的，就是经常我这边已经关闭了，但当我重新打开电脑，使用简悦时又会提醒我，然后点开设置，这个同步助手又打开了

**Comment by Kenshin** [comment]
> 就是经常我这边已经关闭了，但当我重新打开电脑

先关闭它，按上图操作，然后重启浏览器，确认是否已生效。

**Comment by Kenshin** [comment]
你之前的问题是：

关闭了选项，但同时在其它页面操作，配置互相覆盖造成的...

> 导入到notion的功能里面有没有同时导入网页链接的功能呢

什么叫网页链接？是原文吗？如果是的话，默认就支持。

**Comment by Kenshin** [comment]
导入的时候选择 database 就行了，就像下图
