### ISSUE TITLE
优化自动化调用时的提示信息

### ISSUE THREAD

**Issue by wangfenglin995** [Kenshin/simpread#5588]
### 描述这个错误

配置自动化脚本后，自动导出标注后，每次标注都会提示好几次【已成功保存】，能不能去掉这几个提示？

### 复现步骤

配置了一个自动化脚本，功能是加入标注时，保存到md和html文件
<img width="553" alt="image" src="https://github.com/Kenshin/simpread/assets/7811848/f2d9ec62-0629-419d-94a4-eee97a8b29a9">
之后。
在阅读模式下，每次标注后，都会提示4次【已成功保存】，非常影响阅读速度，吸引注意力，能不能去掉这个4提示呢？
<img width="716" alt="image" src="https://github.com/Kenshin/simpread/assets/7811848/4b6eb703-dd80-4993-929b-36137d3677dd">

### 操作系统

macOS

### 浏览器

chrome 113.0.5672.126

### 发生问题的网址

https://sspai.com/post/71658

**Comment by Kenshin** [comment]
暂时不能，但已经考虑在优化了。

**Comment by wangfenglin995** [comment]
赞，期待早日优化

**Comment by Kenshin** [comment]
嗨，[自动化辅助增强插件](https://github.com/Kenshin/simpread/discussions/3596) **更新到 1.1.1** 解决了这个问题

## 📚 新增

【当触发自动化时优化右上角提示信息】

<img width="575" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5902e5d6-e4a7-468e-bcdf-237db30c8f25">

开启后，仅在标注并触发自动化时生效，会优化：`已成功保存。` `正在保存` `已成功保存到XXX` `正在导入` 等反复出现的提示。

## 💡 注意

极端情况下，如：安装了太多的插件并使用同步助手的自动同步以及连续标注时，会在浮动工具条显示时稍有卡顿问题。

注意：仅为个例，在测试期间除了我，几乎没有用户反馈过类似问题。

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/DH9l5jblPH) 安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 关联

https://github.com/Kenshin/simpread/issues/3595

***

我关闭这个 Issues 了有任何问题随时在这里讨论
