### ISSUE TITLE
插件很好用🤞,如果美化之后可以支持vimium之类的就更好了.

### ISSUE THREAD

**Issue by 17637462979** [Kenshin/simpread#559]

**Comment by Kenshin** [comment]
抱歉，竟然忘记回复这个 issues 了...

简悦支持快捷键，而且部分与 vimium 冲突的地方均自己实现了。

详细请看：
http://ksria.com/simpread/docs/#/快捷键

如下图
![gYuukIN](https://user-images.githubusercontent.com/81074/63205435-ad079380-c0d6-11e9-90b6-cb8f0c228674.gif)

**Comment by 17637462979** [comment]
嗯嗯,可能我当时使用的正好是冲突按键😂
