### ISSUE TITLE
关于 Obsidian 配置库的疑问

### ISSUE THREAD

**Issue by Jackson2002** [Kenshin/simpread#5593]
### 请描述你的建议或任何内容

使用高级版ob配置库后 若是有大量文章 请问如何把他们按照文件夹归类 若是直接新建文件夹再次标注会生成新的标注页（在simpread跟目录下，而此时原文在子文件内部）
希望有快速分类的办法

**Comment by Kenshin** [comment]
> 若是有大量文章 请问如何把他们按照文件夹归类

你是说类似下图这样？

<img width="328" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/732a7774-6719-40c6-9847-e2228199e4a6">

如果是的话，暂时没有这样的功能，或者说没有很方便的自动选择某个阅读模式的文章在导入时选择 A 文件夹或 B 文件夹。

为什么不在 Obsidian 手动整理呢？

**Comment by Jackson2002** [comment]
就是在ob整理 如果是我将采集到文章和annote收录在一个文件夹，此时我再次在ob的简悦插件中批注这篇文章 那么将会生成一个新的annnote文件，就会有两个annote 而且这个新的annote是和旧的annote不在同一文件夹

**Comment by Kenshin** [comment]
> 就是在ob整理 如果是我将采集到文章和annote收录在一个文件夹，此时我再次在ob的简悦插件中批注这篇文章 那么将会生成一个新的annnote文件，就会有两个annote 而且这个新的annote是和旧的annote不在同一文件夹

是的，确实如此 😂

因为刚才说了，暂时没有这样的功能。

我个人建议：既然用了 Obsidian 这类双链笔记，就应该慢慢淡忘掉 folder 的方式，而多用 tag 方式。

Folder 就做几个大类就行了。

PS：随着你的收集的内容越来越多，你会发现 Folder 无法满足你的需求了。

**Comment by Jackson2002** [comment]
好吧 有没有批量TAG 功能

**Comment by Kenshin** [comment]
也暂时没有 😂

不过，这是个 Feature 。

***

PS：问下，**你已经使用了导入全文到 Obsidian 或者导入标注到 Obsidian 功能**了吧？**如果是的话，**请把你的 Obsidian 截图给我，类似下图（我需要看下你的 Obsidian 版本。

如果没有使用的话，暂时忽略这条消息。

<img width="251" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0912e514-5ae3-4c9e-9641-b840f71f36cc">

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/72c0c6b6-d590-4f03-9296-5a72cad6de28)
是的

**Comment by Kenshin** [comment]
我需要看你的 Installer 版本 😂 需要在 Obsidian About 上查看，类似下图位置

<img width="214" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4b176ba9-bc5a-40b4-bc44-1bb9bec582fb">

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/816c5baf-9c45-48d8-9a19-8d7809645660)

**Comment by Kenshin** [comment]
okay 谢谢。

因为有个别用户反馈 https://github.com/Kenshin/simpread/issues/5558 这样的情况，但我这边一直没有复现。

你可以正常使用导入到 Obsidain 包括全文和标注吧。

PS：你是什么系统？

**Comment by Jackson2002** [comment]
可以 win11专业版本

**Comment by Jackson2002** [comment]
为啥要一直开着ob才能导入成呢 不是都本地化了吗

**Comment by Kenshin** [comment]
> ob才能导入成呢

如果你使用了的是 Obsidian Unread Sync 版的话（下图），需要开着 Obsidain（这个方案「走」的是 Obsidian 插件端。）

这个方式提供了更多与 Obsidian 互动的功能。

<img width="614" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c54e38eb-1194-4137-acdd-f6f538b45d3b">

**Comment by Jackson2002** [comment]
遇到一个新问题 啥都没干
![image](https://github.com/Kenshin/simpread/assets/57218370/83b306b9-6411-413a-8b23-babda69b5346)
稍后读打不开了 阅读模式也无法标注

**Comment by Kenshin** [comment]
1. 重启同步助手。
2. 使用 http://localhost:7026/database/fixed 修复。

PS：不可能出现你什么都没有做就不好使的情况，如果确认是的话，一般第一个方式就能解决。

**Comment by Jackson2002** [comment]
已搞定 删去了上一篇采集的文章
简悦的网页和标注能导入其他软件吗

**Comment by Kenshin** [comment]
> 简悦的网页和标注能导入其他软件吗

暂时不能，你想导入什么 App 的内容？

**Comment by Jackson2002** [comment]
考不考虑 把简悦稍后读网页版做成一个独立的exe文件，在我看来 哪里阅读都没有简悦稍后读爽，可惜稍后的批注不能导入ob
我用ob只是为了备份 可惜了不能这么操作 稍后读网页算是废了 
如何调整ob内置简悦阅读模式的字体大小

**Comment by Kenshin** [comment]
> 把简悦稍后读网页版做成一个独立的exe文件

其实安装了同步助手后，访问 http://localhost:7026/unread 得到的页面其实就算是个 `exe` 不过后续会考虑把稍后读的功能集成到同步助手中。

> 可惜稍后的批注不能导入ob

确实，但你可以打开 http://localhost:7026/unread 然后在这里标注。（或者在 Obsidian 中标注）

效果比原文（阅读模式）好很多。

> 调整ob内置简悦阅读模式的字体大小

暂时没法调整。（也算 Feature）

**Comment by Kenshin** [comment]
嗨，各位，这个问题应该可以解决了。

不需要改动 Obsidian SimpRead Sync 插件，只需要修改简悦的 Obsidian 插件，修改如下：

<img width="607" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1b6f2802-dbd6-41fb-883a-522dadfdb1d4">

也就是下图

<img width="610" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e8f9d709-21b2-4273-996c-f802fde3a9d1">

然后：

1. 保存并重启浏览器，确认修改生效。
2. 重启 Obsidian

**Comment by Jackson2002** [comment]
所以你这个是推送的是修复了啥么bug

**Comment by Kenshin** [comment]
😂 这个修复跟你无关...

不过，建议改为  `http://localhost:7027` 比较安全。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/694e6aad-46d0-421a-8894-6a0ed39e8f9b)
若是公众号带有此种标识 就会在阅读模式出现很大的空白间隔 已经开启了纯净模式

**Comment by Kenshin** [comment]
> 就会在阅读模式出现很大的空白间隔

有这种情况发生，需要提供 URL （你可以试试关闭纯粹模式，看能否解决？）

**Comment by Jackson2002** [comment]
有个想法 能不能模仿bookxnote在pc上当weddav局域网数据中心
若是有平板 开发一套个软件 就能在平板上面阅读稍后读了

**Comment by Kenshin** [comment]
如果你使用了同步助手，访问 http://localhost:7026/unread 自然就能看到稍后读列表，如果在同一个局域网中，理论上也可以访问 `http://<运行同步助手的设备 IP>:7026/unread` 查看。

你可以试试。
