### ISSUE TITLE
少数派网站的文章没有自动适配显示目录大纲

### ISSUE THREAD

**Issue by PenguinWang123** [Kenshin/simpread#5594]
### 请描述你的建议或任何内容

少数派的文章本身都自带大纲 ，但在进入简悦模式后都没有目录大纲

**Comment by Kenshin** [comment]
当然都有大纲 😂 

![image](https://github.com/Kenshin/simpread/assets/81074/384391be-199f-4736-957a-6c06e35f5c42)


进入阅读模式后，右下角

<img width="477" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f4aa092a-ab35-40c1-af94-a758a1605c04">

**Comment by PenguinWang123** [comment]
> 当然都有大纲 😂
> 
> ![image](https://user-images.githubusercontent.com/81074/241517943-384391be-199f-4736-957a-6c06e35f5c42.png)
> 
> 进入阅读模式后，右下角
> 
> <img alt="image" width="477" src="https://user-images.githubusercontent.com/81074/241517291-f4aa092a-ab35-40c1-af94-a758a1605c04.png">

好謝謝！

**Comment by Kenshin** [comment]
okay 解决就好~
