### ISSUE TITLE
插件可以安装但不能触发

### ISSUE THREAD

**Issue by chipsflying** [Kenshin/simpread#5596]
### 描述这个错误

出现过这个问题，但一直没折腾，最近卸载了简悦重新安装，但问题依旧。
使用的是 Edge dev 浏览器。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/102506599/14ecccf8-2928-4fe3-a501-ed60dce459cf)
![image](https://github.com/Kenshin/simpread/assets/102506599/58767f07-65b9-4744-a09b-4b39d558db31)

### 操作系统

PC

### 浏览器

Microsoft Edge 版本 115.0.1866.1 (正式版本) dev (64 位)

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=Mzg2NzY5NzE1OQ==&mid=2247484290&idx=1&sn=0be107b950683c53e94ea31fa9261115&chksm=ceb6d4eaf9c15dfc812b1323c6d01ea264ab6d230c8a1ec727593176de295bb588914ad1921b&mpshare=1&scene=1&srcid=052685ALPiXCZ0s3UHoa9ICG&sharer_sharetime=1685110774898&sharer_shareid=b6a7fb9369615860cf6ddc91d92b3848#rd

**Comment by Kenshin** [comment]
嗨，如果使用了同步助手的话，请通过 https://www.yuque.com/kenshin/simpread/fcw60u 方式安装插件。

如果你使用的是配置库方案，按照配置库的设置说明就可以正常使用。
