### ISSUE TITLE
语雀文档转化为离线 md，提示图片转化失败

### ISSUE THREAD

**Issue by realSummer** [Kenshin/simpread#5597]
### 描述这个错误

https://www.yuque.com/cuggz/feplus/dbouy2q94dr0smn9
使用插件转化上边的链接，提示图片转化失败。

### 复现步骤

1. 打开 https://www.yuque.com/cuggz/feplus/dbouy2q94dr0smn9 这个语雀文档
2. 进入阅读模式，动作转化为离线 md 文档
3. 提示图片转化失败

### 其他相关说明

https://www.yuque.com/cuggz/feplus/cqy8az
语雀的这个链接，也是提示图片转化失败，重试了几次，最终导出了离线 md 文件

### 操作系统

苹果系统

### 浏览器

谷歌浏览器 版本 112.0.5615.137（正式版本） (arm64)

### 发生问题的网址

https://www.yuque.com/cuggz/feplus/dbouy2q94dr0smn9

**Comment by Kenshin** [comment]
嗨

1. 是否仅语雀有问题？还是其它页面均有问题？
2. 如果语雀是私有库的话，在导出时可能会有问题。

另外，不建议使用离线 Markdown 方案，因为会把图片也编码到 .md 中，导致 size 很大，大部分 Markdown 编辑器都没法正常打开。

可以使用：

1. 离线 HTML
2. [md + assets](https://github.com/Kenshin/simpread/discussions/4041) 方案
3. Bundle 方案

细节可以看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920473

**Comment by realSummer** [comment]
多谢回复，语雀的别的文章可以导出，只有偶尔的文章会出现这个问题；
使用离线 md 是想自己保存文件，防止图片丢失，我试一下方案 2；
还有个问题，离线的 html 可以再使用简悦来导出吗？

**Comment by Kenshin** [comment]
> 语雀的别的文章可以导出，只有偶尔的文章会出现这个问题

okay 

> 使用离线 md 是想自己保存文件，防止图片丢失，我试一下方案 2；

方案2是目前比较主流的使用方案。

> 离线的 html 可以再使用简悦来导出

不能，因为离线 HTML 本来包含了简悦的一些代码，再次被简悦识别会有问题。
主要是也没必要做二次导出 😂
