### ISSUE TITLE
关于 Obsidian 配置库高级版的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5598]
hello，我有个问题，就是按照文章obsidian的高级版配置完后，在网页画的标注不会自动同步到obsidian,每次需要在obsidian的简悦插件点击手动同步才行，是哪里出现问题了吗，help~~~~~各文件配置如下
![image](https://github.com/Kenshin/simpread/assets/103248651/c3196a4b-cd73-4f90-840d-798a0d8d68ec)
![image](https://github.com/Kenshin/simpread/assets/103248651/9cec51e5-a77f-4693-a853-ef6d979ca70c)
![image](https://github.com/Kenshin/simpread/assets/103248651/e37a4121-f52a-4f76-afdb-8b9d676b96a8)
![image](https://github.com/Kenshin/simpread/assets/103248651/9839d760-7a0d-41c2-b21b-4eea4c84e5ea)

_Originally posted by @Lateryzh in https://github.com/Kenshin/simpread/discussions/2889#discussioncomment-6023417_

**Comment by Kenshin** [comment]
@Lateryzh

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

至于你的问题，看看是不是因为 https://github.com/Kenshin/simpread/issues/5558 引起的？

PS：看看你的 Installer 的版本是什么？不过这个问题应该只是偶尔出现，因为我这边没法复现，所以不太好 Debug 后续会持续追踪这个情况。

把你的系统也一并告诉我。

有任何疑问你可以随时在这里跟我讨论。

**Comment by Kenshin** [comment]
嗨，各位，这个问题应该可以解决了。

不需要改动 Obsidian SimpRead Sync 插件，只需要修改简悦的 Obsidian 插件，修改如下：

<img width="607" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1b6f2802-dbd6-41fb-883a-522dadfdb1d4">

也就是下图

<img width="610" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e8f9d709-21b2-4273-996c-f802fde3a9d1">

然后：

1. 保存并重启浏览器，确认修改生效。
2. 重启 Obsidian

**Comment by Lateryzh** [comment]
谢谢大佬，我不太会用github，给您造成麻烦了，抱歉。
”修改简悦的 Obsidian 插件“解决了这个问题，另外希望一站高级版教程中加上下图配置文件夹名要和原有库一致这个内容，这个我是在别的版块看到的，差点就漏掉了这个修改，因为默认的好像是高级版下载下来的库名。
![image](https://github.com/Kenshin/simpread/assets/103248651/e41a4a2d-3663-4268-9e44-97fa024ffcd0)
同时希望原文教程中把自己有库的操作提到文章的那个步骤上来，我自己折腾完了才发现下面有写怎么处理自己有库的情况。
就是这个版块
![image](https://github.com/Kenshin/simpread/assets/103248651/9e71df2e-5bba-4ab1-88e7-3414eef8d245)
大佬可以看看是否采纳。

**Comment by Kenshin** [comment]
> 一站高级版教程中加上下图配置文件夹名要和原有库一致这个内容

emmm 因为理论上已经给大家配置好了，所以没有提，我考虑下加入上。

非要说的话，其实在 https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb 里面已经说明了。

![image](https://github.com/Kenshin/simpread/assets/81074/be9c1ad1-52fa-4bae-a30f-65464a93cb55)

> 希望原文教程中把自己有库的操作提到文章的那个步骤上来

哪个步骤？

**Comment by Lateryzh** [comment]
就是合并obsidian配置这个步骤
![image](https://github.com/Kenshin/simpread/assets/103248651/e89fb1ba-949d-4f48-b5a6-70ec0a4097c9)
虽然在大纲里也很好看到。。。emm当我没提好了

**Comment by Kenshin** [comment]
😂 

我知道了，我想想怎么改。
