### ISSUE TITLE
知乎latex公式保存到obsidian markdown会重复（个别页面）

### ISSUE THREAD

**Issue by Kalay1995** [Kenshin/simpread#5600]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/14127267/0035d02b-940c-4fab-aa2e-6506c8680d17)

如图，每次知乎保存文章到obsidian时，公式会重复保存一次。

### 复现步骤

快捷键aa阅读模式->bb保存到obsidian并保存全文。这时保存的全文就是如图样式。

### 其他相关说明

高级用户，用了自动同步方案。

如下是我的配置文件，uid已修改

[simpread_config.txt](https://github.com/Kenshin/simpread/files/11589786/simpread_config.txt)

### 操作系统

windows11

### 浏览器

edge 版本 113.0.1774.57 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/question/36339816/answer/385944057

**Comment by Kenshin** [comment]
嗨，知乎的个别页面确实存在类似的问题，我先记录下。（但部分页面却没问题 😂 ...

**Comment by see2it** [comment]
我也是遇到这种情况

**Comment by Kenshin** [comment]
@see2it 

请提供 URL

**Comment by see2it** [comment]
> @see2it
> 
> 请提供 URL

比如 https://zhuanlan.zhihu.com/p/90766406

我是套用obsidian 高级版配置库的。另外，这类带数学公式的知乎专栏文章，若选择导出为pdf，公式部分会仅仅显示为latex语法

**Comment by Kenshin** [comment]
使用下图进入阅读模式

<img width="966" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/42750662-a93a-43ca-ad0d-5cb79a314625">

然后使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/3340) 删除无用内容。

<img width="1827" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5532665d-2361-4d07-b6af-ddee7e7a4052">

导入到 Obsidian

<img width="1113" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5a25bf64-ea3e-42f7-96fe-e02db623cab5">

**Comment by see2it** [comment]
> 使用下图进入阅读模式
> 
> <img alt="image" width="966" src="https://user-images.githubusercontent.com/81074/249982804-42750662-a93a-43ca-ad0d-5cb79a314625.png">
> 然后使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/3340) 删除无用内容。
> 
> <img alt="image" width="1827" src="https://user-images.githubusercontent.com/81074/249982860-5532665d-2361-4d07-b6af-ddee7e7a4052.png">
> 导入到 Obsidian
> 
> <img alt="image" width="1113" src="https://user-images.githubusercontent.com/81074/249982935-5a25bf64-ea3e-42f7-96fe-e02db623cab5.png">

我照着复制操作还是不成功啊，甚至连Latex公式都不正常了。我还是先将就着编辑，我猜可能是因为知乎网页既有latex语法又有mathml格式，所以就重复显示了。

**Comment by Kenshin** [comment]
知乎公式的显示方式，可以看下 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890

如果你需要的话，我把导出的 Markdown 给你 [卷积公式.txt](https://github.com/Kenshin/simpread/files/11914284/default.txt)

**Comment by see2it** [comment]
> 知乎公式的显示方式，可以看下 [#2861 (comment)](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890)
> 
> 如果你需要的话，我把导出的 Markdown 给你 [卷积公式.txt](https://github.com/Kenshin/simpread/files/11914284/default.txt


> 知乎公式的显示方式，可以看下 [#2861 (comment)](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890)
> 
> 如果你需要的话，我把导出的 Markdown 给你 [卷积公式.txt](https://github.com/Kenshin/simpread/files/11914284/default.txt)

你发的这个txt里面公式的对的，我也用了比如加载延迟列表的方法也不行啊，导入ob里面还是会显示为 $某Latex公式$某Latex公式，我就手动修改为  $某Latex公式$，这样就可以了。虽然有一点麻烦，好歹还可以改过来哈哈。

**Comment by Kenshin** [comment]
emmmm 

那就有点奇怪了…你在留意下带公式的知乎还有没有这种问题。

**Comment by see2it** [comment]
> emmmm
> 
> 那就有点奇怪了…你在留意下带公式的知乎还有没有这种问题。

我在知乎专栏保存的文章都有这个问题的。

**Comment by Kenshin** [comment]
好吧 😂 我找了个干净的配置文件也没能复现你提到的情况...

**Comment by see2it** [comment]
> 好吧 joy 我找了个干净的配置文件也没能复现你提到的情况...

那就应该是我电脑系统、浏览器等的问题了

**Comment by Kenshin** [comment]
也不能 100% 是这个问题，知乎公式还是有点烦人的。

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了知乎公式的问题。


## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by see2it** [comment]
好像还是不行啊
![lll](https://github.com/Kenshin/simpread/assets/133801444/874806a4-7ee0-42ee-8bbb-fc9b8050d7f3)

**Comment by see2it** [comment]
知乎阅读辅助增强插件实测成功，感谢！

**Comment by see2it** [comment]
刚安装了“知乎阅读辅助增强插件”， 导入知乎页面到OB里，有的正常，有的还是不行啊，比如https://zhuanlan.zhihu.com/p/325939315

**Comment by see2it** [comment]
另外，我安装了wkhtmltopdf 和插件“PDF辅助增强”，在PDF辅助增强选项-选择 “同步助手高级打印方案”，导出PDF时 就报错
![pdf失败](https://github.com/Kenshin/simpread/assets/133801444/bdd3e5a0-d9cc-49b5-990c-6e28e715c960)
但是选同步助手基础打印方案，可以完美导出的。

**Comment by Kenshin** [comment]
> 刚安装了“知乎阅读辅助增强插件”， 导入知乎页面到OB里，有的正常，有的还是不行啊，比如https://zhuanlan.zhihu.com/p/325939315

我测试了下，没有问题。

<img width="926" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6c3102e3-5542-46aa-bc72-8e03998f75ec">

这是我导入到 Obsidian 的文件 [卷积公式使用详解.txt](https://github.com/Kenshin/simpread/files/12206163/default.txt)

> 另外，我安装了wkhtmltopdf 和插件“PDF辅助增强”，在PDF辅助增强选项-选择 “同步助手高级打印方案”，导出PDF时 就报错 ![pdf失败](https://user-images.githubusercontent.com/133801444/256957391-bdd3e5a0-d9cc-49b5-990c-6e28e715c960.jpg) 但是选同步助手基础打印方案，可以完美导出的。

浏览器方案顾名思义是调用浏览器，所以浏览器显示什么，它就能打印什么。但缺点是：部分导出的 PDF 没法使用高亮或选中。

至于 PDF 高级打印方案，则没有这些问题。而且这个功能也没有问题，所以建议看下 https://github.com/Kenshin/simpread/discussions/3887 里面的内容，是否可以帮到你，另外是否安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件？

**Comment by see2it** [comment]
> > 刚安装了“知乎阅读辅助增强插件”， 导入知乎页面到OB里，有的正常，有的还是不行啊，比如https://zhuanlan.zhihu.com/p/325939315
> 
> 我测试了下，没有问题。
> 
> <img alt="image" width="926" src="https://user-images.githubusercontent.com/81074/256960872-6c3102e3-5542-46aa-bc72-8e03998f75ec.png">
> 这是我导入到 Obsidian 的文件 [卷积公式使用详解.txt](https://github.com/Kenshin/simpread/files/12206163/default.txt)
> 
> > 另外，我安装了wkhtmltopdf 和插件“PDF辅助增强”，在PDF辅助增强选项-选择 “同步助手高级打印方案”，导出PDF时 就报错 ![pdf失败](https://user-images.githubusercontent.com/133801444/256957391-bdd3e5a0-d9cc-49b5-990c-6e28e715c960.jpg) 但是选同步助手基础打印方案，可以完美导出的。
> 
> 浏览器方案顾名思义是调用浏览器，所以浏览器显示什么，它就能打印什么。但缺点是：部分导出的 PDF 没法使用高亮或选中。
> 
> 至于 PDF 高级打印方案，则没有这些问题。而且这个功能也没有问题，所以建议看下 #3887 里面的内容，是否可以帮到你，另外是否安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件？

> 忘记OB的markdown不能所见所得，切换成阅读模式是完美显示的了，不好意思。
> 我是先仔细看了 #3887还安装了wkhtmltopdf的，用命令行验证了安装是没问题的，也试了添加安装路径什么的。
![jj](https://github.com/Kenshin/simpread/assets/133801444/237a87f1-c91a-4b06-bb16-3258a6c83ef9)
> 我没有选择浏览器打印方案的，而是选择上图中选项“基础方案”的。唯独选择 “同步助手高级打印方案”就不能导出PDF。

**Comment by see2it** [comment]
> > 刚安装了“知乎阅读辅助增强插件”， 导入知乎页面到OB里，有的正常，有的还是不行啊，比如https://zhuanlan.zhihu.com/p/325939315
> 
> 我测试了下，没有问题。
> 
> <img alt="image" width="926" src="https://user-images.githubusercontent.com/81074/256960872-6c3102e3-5542-46aa-bc72-8e03998f75ec.png">
> 这是我导入到 Obsidian 的文件 [卷积公式使用详解.txt](https://github.com/Kenshin/simpread/files/12206163/default.txt)
> 
> > 另外，我安装了wkhtmltopdf 和插件“PDF辅助增强”，在PDF辅助增强选项-选择 “同步助手高级打印方案”，导出PDF时 就报错 ![pdf失败](https://user-images.githubusercontent.com/133801444/256957391-bdd3e5a0-d9cc-49b5-990c-6e28e715c960.jpg) 但是选同步助手基础打印方案，可以完美导出的。
> 
> 浏览器方案顾名思义是调用浏览器，所以浏览器显示什么，它就能打印什么。但缺点是：部分导出的 PDF 没法使用高亮或选中。
> 
> 至于 PDF 高级打印方案，则没有这些问题。而且这个功能也没有问题，所以建议看下 #3887 里面的内容，是否可以帮到你，另外是否安装了 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件？

> 忘记OB的markdown不能所见所得，切换成阅读模式是完美显示的了，不好意思。
> 我是先仔细看了 #3887还安装了wkhtmltopdf的，用命令行验证了安装是没问题的，也试了添加安装路径什么的。
![jj](https://github.com/Kenshin/simpread/assets/133801444/237a87f1-c91a-4b06-bb16-3258a6c83ef9)
> 我没有选择浏览器打印方案的，而是选择上图中选项“基础方案”的。唯独选择 “同步助手高级打印方案”就不能导出PDF。

**Comment by Kenshin** [comment]
> 选择上图中选项“基础方案”的能正常导出PDF，只是选择 “同步助手高级打印方案”就不能导出PDF。

把 PDF 高级设置的相关截图给我看下。

**Comment by see2it** [comment]
> > 选择上图中选项“基础方案”的能正常导出PDF，只是选择 “同步助手高级打印方案”就不能导出PDF。
> 
> 把 PDF 高级设置的相关截图给我看下。

我刚重启了电脑，然后在 “wkhtmltopdf 的运行目录”处添加、删除都测试过，如此反复多次后忽然就成功了哈哈。（WIN7-64系统，不用指定wkhtmltopdf的运行目录）
真的是日趋完美强大的一款工具，谢谢！

**Comment by Kenshin** [comment]
> 然后在 “wkhtmltopdf 的运行目录”处添加、删除都测试过，如此反复多次后忽然就成功了

Windows 日常玄学 😂 解决就好。

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
