### ISSUE TITLE
关于插件管理器的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5605]
一点击 导入当前插件 自动同步就自动打开，导致导入插件失败。

全部清除本地数据，掉了VIP也能给我自动打开？

_Originally posted by @FLIER001

**Comment by Kenshin** [comment]
@FLIER001

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 一点击 导入当前插件 自动同步就自动打开

这个过程预期的。

通过插件管理器安装完插件后重启浏览器（仅针对你），如果需要安装新的插件，就使用插件管理器安装。

> 全部清除本地数据，掉了VIP也能给我自动打开？

这个操作并没有关于此步骤的描述。

**Comment by FLIER001** [comment]
> @FLIER001
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> > 一点击 导入当前插件 自动同步就自动打开
> 
> 这个过程预期的。
> 
> 通过插件管理器安装完插件后重启浏览器（仅针对你），如果需要安装新的插件，就使用插件管理器安装。
> 
> > 全部清除本地数据，掉了VIP也能给我自动打开？
> 
> 这个操作并没有关于此步骤的描述。

我想使用**浮动面板定制器插件**，在不开启同步助手的情况下，存在问题无法保存配置的问题：
1. 直接安装，打开进入阅读模式进行设置，发现无法保存设置；
2. 尝试使用插件管理器，会自动打开自动同步功能，但我本地没有安装简悦同步客户端，所以也行不通。

求一个解决办法

**Comment by Kenshin** [comment]
> 我想使用浮动面板定制器插件，在不开启同步助手的情况下，存在问题无法保存配置的问题

**如果你没有使用同步助手的话，**直接安装这个插件就行了。

插件管理器是解决开启自动同步后无法安装插件的解决方案，反之，如果**你没有使用自动同步与同步助手的话**，不需要使用它。

**Comment by FLIER001** [comment]
> > 我想使用浮动面板定制器插件，在不开启同步助手的情况下，存在问题无法保存配置的问题
> 
> **如果你没有使用同步助手的话，** 直接安装这个插件就行了。
> 
> 插件管理器是解决开启自动同步后无法安装插件的解决方案，反之，如果**你没有使用自动同步与同步助手的话**，不需要使用它。

不开启同步助手，不安装插件管理起，直接安装这个插件，会无法保存配置，不知这是否是个共性问题？

**Comment by Kenshin** [comment]
@FLIER001 

不开启同步助手的话是没有任何问题的。

安装插件，安装后进入阅读模式会弹出这个插件的设置，然后设置它并保存，最后（建议）重启浏览器。

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
