### ISSUE TITLE
翻译插件腾讯翻译报错

### ISSUE THREAD

**Issue by xianxixi** [Kenshin/simpread#5607]
### 描述这个错误

磊哥好, 腾讯接口时遇到这个问题, (接口本身没问题,在沙拉查词中正常用), 另外自己注册的百度接口工作正常.
![Snipaste_2023-05-30_21-23-49](https://github.com/Kenshin/simpread/assets/64732837/abb3a93f-cd84-4268-ba19-47fb3723d295)

### 复现步骤

同上

### 操作系统

Win11

### 浏览器

edge最新

### 发生问题的网址

任意

**Comment by Kenshin** [comment]
okay 我明天确认下。

**Comment by Kenshin** [comment]
嗨，这个问题已修复了。

### 修复内容

包括：

1. [划词翻译](https://github.com/Kenshin/simpread/discussions/1592)
2. [全文翻译](https://github.com/Kenshin/simpread/discussions/1593)

### 如何安装

- 没有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/XxuF7bPTbo 安装
- 已有同步助手的用户，使用 https://simpread.ksria.cn/plugins/details/Y7JxbP7B4H 或 https://simpread.ksria.cn/plugins/details/ohnTKVHz4a 安装

我关闭这个 issues 了，有任何疑问随时在这里反馈。

😄
