### ISSUE TITLE
知乎公式在稍后读页面无法成功加载？

### ISSUE THREAD

**Issue by zhoulukuan** [Kenshin/simpread#5609]
### 描述这个错误

按照github相关教程，配置了插件、站点适配以及延迟加载，发现直接进入阅读模式可以成功加载公式，但网页添加到稍后读后显示失败。
想请问下是存在bug还是设置问题？

### 复现步骤

1. 打开网页，进入阅读模式
![image](https://github.com/Kenshin/simpread/assets/16110591/d5af837d-d805-4660-8b86-e6d1efeb374f)
2. 阅读模式或者直接在网页下dd添加到shao'hou'du稍后读，显示如下
![image](https://github.com/Kenshin/simpread/assets/16110591/d8f4c042-4b07-45a9-a995-70c565fabae6)

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://zhuanlan.zhihu.com/p/29765582

**Comment by Kenshin** [comment]
嗨，在稍后读中使用的话，确实有些问题 😂 

如果你用了同步助手的话，可以试试读本地快照的方式，部分知乎页面是没问题的。

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
