### ISSUE TITLE
维基百科的公式问题

### ISSUE THREAD

**Issue by Dylnn** [Kenshin/simpread#561]
类似于issue #455 ，维基百科的公式支持不佳，望适配。
参考链接：
https://en.wikipedia.org/wiki/Information_gain_in_decision_trees

显示效果如截图：
![wikipedia](https://user-images.githubusercontent.com/5445438/63234653-dfe19100-c268-11e9-96ff-7c669cf40dc4.jpg)

原始效果见：
![original](https://user-images.githubusercontent.com/5445438/63234692-0273aa00-c269-11e9-8320-239606fac0b9.jpg)

**Comment by Kenshin** [comment]
谢谢反馈。
这是因为 维基百科 使用了其它 LateX lib 造成的解析失败。

我会试着为此增加一个  Plugin 到时会通知你。

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，修复了此问题。

<img width="624" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/985b784c-b4d6-44cf-9a54-1e14b167351b">


***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
