### ISSUE TITLE
在已经使用了obsidian的高级配置库之后，能否再制定个性导出？

### ISSUE THREAD

**Issue by PenguinWang123** [Kenshin/simpread#5610]
### 请描述你的建议或任何内容

我的主要个性导出需求是将每一条笔记摘录都自带标题名和带有在文中位置的链接

**Comment by Kenshin** [comment]
当然这次定制化，细节看这里 https://github.com/Kenshin/simpread/discussions/3725

> 将每一条笔记摘录都自带标题名

没什么必要吧，看起来会很奇怪

> 带有在文中位置的链接

高级版配置库默认就有这种方式。

**Comment by PenguinWang123** [comment]
你好，我在“markdown辅助增强”插件的模板中设置了相关模板，测试也有内容，但是导出到obsidian的内容还是没有得到模板渲染，这是为什么呢？教程里说到的“自动化辅助增强”插件我也安装了，但这是配合“导入到obsidian”动作的吗？这样的话岂不是我以前高级库自动化配置都白配置了吗？或者说能不能有一种方式让我根据高级库自动配置的默认模板自己再改动一些东西以符合我的需求呢？有这种改动模板的地方吗





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 在已经使用了obsidian的高级配置库之后，能否再制定个性导出？ (Issue #5610)





 
当然这次定制化，细节看这里 #3725
  
将每一条笔记摘录都自带标题名
  
没什么必要吧，看起来会很奇怪
  
带有在文中位置的链接
  
高级版配置库默认就有这种方式。

**Comment by Kenshin** [comment]
> 但是导出到obsidian的内容还是没有得到模板渲染，这是为什么呢？

是在阅读模式下导入吗？如果是在 Obsidian 标注的话，Obsidian SimpRead Sync 插件端也需要设置下模板。

> 教程里说到的“自动化辅助增强”插件我也安装了，但这是配合“导入到obsidian”动作的吗？

是的

> 教程里说到的“自动化辅助增强”插件我也安装了，但这是配合“导入到obsidian”动作的吗？这样的话岂不是我以前高级库自动化配置都白配置了吗？

**自动化辅助增强** 与 **导入到obsidian** 以及 **以前高级库自动化配置都白配置** 并没有直接的关系。也就是说单纯的看你描述，并不会存在 **白配置了这件事情** ... 除非你的描述有误。

> 有一种方式让我根据高级库自动配置的默认模板自己再改动一些东西以符合我的需求呢？有这种改动模板的地方吗

使用高级版配置库，里面自带了 Markdown 模板引擎以及一个配置好的模板，你直接在这个基础上修改就行了。

***

综上，无论什么样的修改，前提都要：在使用官方提供的配置库方案后正确导入的前提。

**Comment by PenguinWang123** [comment]
1.我想实现的定制导出需求格式如下：评论[高亮内容](笔记链接)&nbsp;
这样做是因为我网页看论文，这样导出的话方便后续论文的交叉引用


2.既然markdown辅助增强需要配合“导入到obsidian”动作，也就是过去基于配置库的“边划线，边自动导入到ob”无法实现了吗？因为需要多一个点击““导入到obsidian”动作”


3.我的obsidian里没有simpread的插件


4.像我这种需求，目前应该怎么解决？修改高级库模板的地方在哪里？





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 在已经使用了obsidian的高级配置库之后，能否再制定个性导出？ (Issue #5610)





  
但是导出到obsidian的内容还是没有得到模板渲染，这是为什么呢？
  
是在阅读模式下导入吗？如果是在 Obsidian 标注的话，Obsidian SimpRead Sync 插件端也需要设置下模板。
  
教程里说到的“自动化辅助增强”插件我也安装了，但这是配合“导入到obsidian”动作的吗？
  
是的
  
教程里说到的“自动化辅助增强”插件我也安装了，但这是配合“导入到obsidian”动作的吗？这样的话岂不是我以前高级库自动化配置都白配置了吗？
  
自动化辅助增强 与 导入到obsidian 以及 以前高级库自动化配置都白配置 并没有直接的关系。也就是说单纯的看你描述，并不会存在 白配置了这件事情 ... 除非你的描述有误。
  
有一种方式让我根据高级库自动配置的默认模板自己再改动一些东西以符合我的需求呢？有这种改动模板的地方吗
  
使用高级版配置库，里面自带了 Markdown 模板引擎以及一个配置好的模板，你直接在这个基础上修改就行了。
 
 
综上，无论什么样的修改，前提都要：在使用官方提供的配置库方案后正确导入的前提。

**Comment by Kenshin** [comment]
> 我的obsidian里没有simpread的插件

那就不是 [Obsidian 配置库高级版](https://www.yuque.com/kenshin/simpread/wq35mh) 方案...

> 像我这种需求，目前应该怎么解决？修改高级库模板的地方在哪里？

在下图所示的地方修改。

<img width="481" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/64581571-5975-4148-a3cd-16cad2094cf2">

***

所以，先弄明白你用的什么配置库方案，然后在上图的地方修改模板。模板的细节链接在上面都告诉你了。

**Comment by PenguinWang123** [comment]
请问能点击跳转回单条笔记吗？占位符是什么？没找到





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 在已经使用了obsidian的高级配置库之后，能否再制定个性导出？ (Issue #5610)





  
我的obsidian里没有simpread的插件
  
那就不是 Obsidian 配置库高级版 方案...
  
像我这种需求，目前应该怎么解决？修改高级库模板的地方在哪里？
  
在下图所示的地方修改。
  
 
所以，先弄明白你用的什么配置库方案，然后在上图的地方修改模板。模板的细节链接在上面都告诉你了。

**Comment by Kenshin** [comment]
全部的模板都可以做到... 配置库默认的就行，或者使用 https://github.com/Kenshin/simpread/discussions/2153#discussioncomment-2627311 也一样

<img width="2051" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6ca6269d-6349-46ad-aae3-c7cb250d3960">

**Comment by Kenshin** [comment]
如果你想看更详细的说明 https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2577612

**Comment by PenguinWang123** [comment]
{{an_int_uri}}这个占位符我试过了，它生成的这个链接点击回去是显示error的啊，不能跳转到原文位置







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 在已经使用了obsidian的高级配置库之后，能否再制定个性导出？ (Issue #5610)





 
全部的模板都可以做到... 配置库默认的就行，或者使用 #2153 (comment) 也一样

**Comment by Kenshin** [comment]
> {{an_int_uri}}这个占位符我试过了，它生成的这个链接点击回去是显示error的啊，不能跳转到原文位置

这个功能需要 [配置知识库](https://www.yuque.com/kenshin/simpread/wkswh7)，但如果你使用的是 [Obsidian 配置库高级版](https://www.yuque.com/kenshin/simpread/wq35mh) 的话（这个配置文件内置了此功能）就不需要特意配置它。

所以，这个问题的原因有两个：

1. 你没有配置正确
2. 你的配置中没有包含这个功能

最后，你需要先明确你使用了哪种配置库方案...
