### ISSUE TITLE
阅读模式 大纲（目录）如何在左上角显示？谢谢

### ISSUE THREAD

**Issue by Aiviokoo** [Kenshin/simpread#5611]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/87182333/1174b2c8-fe0c-4286-9738-a74c7c4c474d)

### 复现步骤

我也不是太清楚
我安装了这些插件
![image](https://github.com/Kenshin/simpread/assets/87182333/3454ba33-777e-4b31-bddd-4ff83e48a48f)

### 其他相关说明

任意网址都是哟

### 操作系统

win11

### 浏览器

chrome

### 发生问题的网址

https://zhuanlan.zhihu.com/p/43790005

**Comment by Kenshin** [comment]
随便进入一个页面 e.g https://sspai.com/post/71739 将下面的代码

```
sr-read toc-bg {
    display: block!important;
}

sr-read toc {
    top: 0!important;
}
```

加入到下图

<img width="477" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cb6c9489-75d8-4263-800a-9887c48d8a9d">

保存后重启浏览器，效果

<img width="1258" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/21728256-744e-4701-afcb-8baea71757a0">

**Comment by Kenshin** [comment]
> 不过我这里测试如果装了 “模仿Safari 阅读模式样式” 插件后，样式还是在中间。

emmm 我就是在这个插件下测试的，明天再确认下。

**Comment by Kenshin** [comment]
嗨，将下面的代码加入到同样的位置。

```
.simpread-read-root sr-read toc-bg {
    display: block!important;
}
sr-read toc {
    top: 0!important;
}
```

**Comment by Aiviokoo** [comment]
> ```
> .simpread-read-root sr-read toc-bg {
>     display: block!important;
> }
> sr-read toc {
>     top: 0!important;
> }
> ```

谢谢大大，非常舒适。 ❤️

**Comment by Kenshin** [comment]
哈，小事情~ 六一快乐 😄


***


方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Aiviokoo** [comment]
好耶
![image](https://github.com/Kenshin/simpread/assets/87182333/ef3ec4cc-d609-42bc-8e26-008d84b3b728)
![image](https://github.com/Kenshin/simpread/assets/87182333/0afdbf92-4383-4952-89cd-42002806fe26)

**Comment by Kenshin** [comment]
哈哈，谢谢评分  💪  👍
