### ISSUE TITLE
博客 cnblogs 不能批注

### ISSUE THREAD

**Issue by Gloryandel** [Kenshin/simpread#5612]
### 描述这个错误

[样例测试网站](https://www.cnblogs.com/liangwang/p/5210948.html)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/51497852/df09f5ed-0695-4d2e-ae5c-5c91d0d2f8f5)

### 其他相关说明

Vivaldi 浏览器（Chromium）

### 操作系统

Windows

### 浏览器

Vivaldi 浏览器

### 发生问题的网址

https://www.cnblogs.com/liangwang/p/5210948.html

**Comment by Kenshin** [comment]
确实如此 😂  可能是它的页面加了一些代码导致无法运行简悦的标注系统。

但有个简单方案：如果你 [配置了知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的话，可以解决这个问题，步骤：

1. 先加稍后读
2. 生成本地快照
3. 打开 http://localhost:7026/unread/ 找到你这篇本地快照的文章。
4. 标注

就没有问题了。
