### ISSUE TITLE
插件打开的时候与立创商城网站冲突，表现出网页无响应

### ISSUE THREAD

**Issue by LuWeiHuan** [Kenshin/simpread#5615]
### 请描述你的建议或任何内容

[list.szlcsc.com](https://list.szlcsc.com/catalog/314.html)
当打开这个网页时内容虽然加载出来，但是无法进行原件筛选，甚至直接后面提示网页无响应

**Comment by Kenshin** [comment]
嗨

你给出的 URL https://list.szlcsc.com/catalog/314.html 并没有适配阅读模式的必要。

如果 URL 并没有提供错误的话，你可以将 `szlcsc.com` 加入黑名单后重启浏览器

<img width="986" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/11d7a0cb-3b65-4bdb-bbb3-dd957372461a">
