### ISSUE TITLE
如何自动识别公众号的层级目录

### ISSUE THREAD

**Issue by Jackson2002** [Kenshin/simpread#5619]
### 请描述你的建议或任何内容

公众号一般都没有目录（难受）
事项能不能增加一个功能 比如公众号往往会有1. 2. 3.这样的层级结构能不能自动识别分段呢

**Comment by Kenshin** [comment]
有点意思，可以考虑下。

建议多给我几个类似公众号的网页做参考。

**Comment by Jackson2002** [comment]
https://mp.weixin.qq.com/s?__biz=MzIxNzgwMjQwMw==&mid=2247483991&idx=1&sn=c41327c1ad1d43f427e41dc7dcbafa72&chksm=97f5719ba082f88dff006bc235c3ac24dc377054d088c14716bde45d59f39b4630c64f951143&scene=21#wechat_redirect
https://mp.weixin.qq.com/s?__biz=MzU4NzExMTE2MA==&mid=2247641171&idx=2&sn=5708402810053bdfb42af5e1282efcff&chksm=fdfde7c4ca8a6ed28e84e228cd1a51fa9faf7363c2b1be3fceefcce93ec15771db5e2f03f9b8#rd

**Comment by Kenshin** [comment]
okay

**Comment by Jackson2002** [comment]
一个是开了词汇重排后 界面乱七八糟 很奇怪 之前跟你说过 阅读模式和稍后读（包括ob导出来md都是排版很好），反而阅读模式排版稀烂
第二个是在进行批注的时候 老是右上角弹出通知 很烦的
第三个 进入阅读模式的时候图片被拉伸 难以阅读 为啥跟网页图片效果不一样

**Comment by Kenshin** [comment]
需要提供出问题的 URL

**Comment by Jackson2002** [comment]
https://mp.weixin.qq.com/s/jqJY9SqVMzkL3sebjOHWpQ

请问 如何关闭烦人的通知？ 不是简吗

**Comment by Kenshin** [comment]
进入这个页面后并没有任何通知....

如果你遇到了提示，肯定是你操作后，所以最好截图，同时告诉我你在操作什么时提示的通知....

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/9cdd3533-2189-47e5-9a02-1867a9433f50)
wodeyishi我的意思是这个有大片空白  因为你叫我提供url（我没有引用上文 不好意思）
通知就是 每点一次标注或者导出到ob库就会弹出很多通知 （我不需要看到过程 只需要看到成功导入就行了）因为会遮挡正文

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/0f4b79e5-e8f1-4c9c-89e1-39fd782625a3)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5619#issuecomment-1581925853

看起来似乎是这个页面反复进入阅读模式后的提示。

>  每点一次标注或者导出到ob库就会弹出很多通知 （我不需要看到过程 只需要看到成功导入就行了）

这里确实需要优化，并且也在 Todo 里面了，就等排期。

> 个有大片空白 因为你叫我提供url

个别公众号确实存在这种情况，因为公众号里面夹杂了一些其它内容...

如果你经常看公众号的话，试试 https://github.com/Kenshin/simpread/discussions/3340 提到的几种方案。

**Comment by Jackson2002** [comment]
cubox可以根据批量html批量导入稍后读 伟大的简悦可以吗
![image](https://github.com/Kenshin/simpread/assets/57218370/d5ae98c1-21a7-4cd5-8bff-7ebb3b460ec0)
![image](https://github.com/Kenshin/simpread/assets/57218370/e2c0a1a9-4ee8-493d-bbfa-ff8a9b2ac639)

**Comment by Jackson2002** [comment]
https://mp.weixin.qq.com/s/Bl6AWlh7OqN-Ptnw1tcNdA

**Comment by Jackson2002** [comment]
简悦目前没有一个很好软件当做阅读器 比如在一两个月以后回看自己批注过得文章 乱七八糟的界面 （不利用阅读）
请问有没有一款软件可以接入简悦的所有文件呢 专做阅读器 比如
Omnivore
