### ISSUE TITLE
文章添加到稍后读，无法正常阅读

### ISSUE THREAD

**Issue by daisy1995** [Kenshin/simpread#5622]
### 描述这个错误

将一篇文章加入到简悦稍后读，然后在稍后读页面打开，切换到阅读模式下，无法正常显示文章
![image](https://github.com/Kenshin/simpread/assets/25699092/976cb06c-09d8-412d-9a2e-4c928603a93b)

### 复现步骤

将一篇文章加入到简悦稍后读，
然后在稍后读页面打开，
切换到阅读模式下，
无法正常显示文章

### 操作系统

win10

### 浏览器

谷歌浏览器版本 114.0.5735.91（正式版本） （64 位）

### 发生问题的网址

https://36kr.com/p/2281519507691269

**Comment by Kenshin** [comment]
部分页面因为是动态加载的，所以没办法使用此方式实现。

如果要实现这个功能的话，需要将简悦设置为「知识库」方案，这是教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by Kenshin** [comment]
另外，你可以加入少数派的文章 e.g.  https://sspai.com/post/69972 就能看到了。

PS：因为少数派的文章不是动态加载方案。
