### ISSUE TITLE
公用数据库

### ISSUE THREAD

**Issue by Jackson2002** [Kenshin/simpread#5624]
### 请描述你的建议或任何内容

一个无理取闹的问题
就是在ob和思源反复横跳
有没有办法可以让他们资料互导
或者在加入稍后读的时候同时激活导出到这两个软件

**Comment by Kenshin** [comment]
当然可以了 😂 原本就支持这么「玩」

加入稍后读：

1. 导入到 Obsidain
2. 导入到思源笔记

利用 [自动化辅助增强](https://github.com/Kenshin/simpread/discussions/3596) 插件，分别设置 Obsidian 与思源笔记的快捷键就行了。

<img width="542" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7aa9fc5f-1785-42f0-befc-c990ba4be6a2">

**Comment by Jackson2002** [comment]
我目前是配置了ob高级库 下一步需要怎么做 
有点懵逼啊 求

**Comment by Kenshin** [comment]
截图已经说的很清楚了啊。

**Comment by Jackson2002** [comment]
有个问题 使用插件管理器 安装了思源插件 问题在触发器维度不显示思源 在另一边可以禁用此插件

**Comment by Jackson2002** [comment]
奇怪 怎么突然出现了这个问题 打不开这个链接 突然全部文章都失效了

https://github.com/Kenshin/simpread/assets/57218370/902d0f0e-ce24-4c99-b5eb-1dd984cc1871

https://github.com/Kenshin/simpread/assets/57218370/399b843b-8069-4cbb-b364-59ac0b1fc3c2

**Comment by Kenshin** [comment]
> 奇怪 怎么突然出现了这个问题 打不开这个链接 突然全部文章都失效了

重启 Obsidian



> 有个问题 使用插件管理器 安装了思源插件 问题在触发器维度不显示思源 在另一边可以禁用此插件

在插件触发器能看到吗？

**Comment by Jackson2002** [comment]
电脑都重启了 没用

**Comment by Jackson2002** [comment]
无法使用ob内置稍后读

**Comment by Jackson2002** [comment]
直接配置快照倒退搞定了

**Comment by Jackson2002** [comment]
在插件触发器能看到吗？   
看不到  但是确实安装了

**Comment by Jackson2002** [comment]
现在做不到和ob一样可以导入标注吗哥 
目前已经成功 需要时刻开着思源笔记吗 就像ob一样

**Comment by Kenshin** [comment]
所以...最后到底搞定了吗？

PS：你拿 Issues 当聊天了？😂

**Comment by Jackson2002** [comment]
搞定了  
现在做不到和ob一样可以导入标注吗哥
目前已经成功 需要时刻开着思源笔记吗 就像ob一样

**Comment by Kenshin** [comment]
> 现在做不到和ob一样可以导入标注吗

思源暂时不支持导入标注。

>  需要时刻开着思源笔记吗 就像ob一样

是的。

**Comment by Jackson2002** [comment]
这种时刻开着这两个软件的背后逻辑是啥？ 不都是本地化吗 大佬有空解释解释吗

**Comment by Kenshin** [comment]
> 这种时刻开着这两个软件的背后逻辑是啥？ 不都是本地化吗 大佬有空解释解释吗

Obsidian 开着 → 简悦导入到 Obsidian 使用了 Obsidian SimpRead Sync 插件

思源开着 → 简悦导入到思源笔记是使用了思源笔记的 API

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/e7cd7042-3839-42bc-a725-e4ba49a351db)
更换了一个思源 导入api 不生效  并且提示这个 同时思源不会生成文件夹

**Comment by Kenshin** [comment]
> 导入api 不生效

思源 API 可能不稳定，重启思源和浏览器后再试试。
