### ISSUE TITLE
登录高级账户后授权显示我不是高级账户

### ISSUE THREAD

**Issue by reov** [Kenshin/simpread#5625]
### 描述这个错误

登录高级账户后授权显示我不是高级账户
![image](https://github.com/Kenshin/simpread/assets/47272954/6c33b55d-b5b8-4e63-bcfc-f0ce63d10614)

### 复现步骤

尝试使用配置文件，坚果云账户，修改uid都没有用，自助解除封锁里也只显示激活一台设备，同时解除激活后，解除激活次数由3变为0

### 操作系统

windows

### 浏览器

chrome113.0.5672.127

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by reov** [comment]
![image](https://github.com/Kenshin/simpread/assets/47272954/d512565c-6304-438b-bc51-14b31b1b135b)

**Comment by Kenshin** [comment]
> 尝试使用配置文件，坚果云账户，修改uid都没有用，自助解除封锁里也只显示激活一台设备，同时解除激活后，解除激活次数由3变为0

估计是你的 UID 错了。

你登录少数派后台找到这个订单里面有 License 得到后使用 https://www.yuque.com/kenshin/simpread/pkq3d1 方案。

如果因为设备被锁定的话，发送你的 License 到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5625

**Comment by reov** [comment]
根据找回的key内的uid修改的，修改完提示授权，点击授权即显示不是高级会员页面

**Comment by reov** [comment]
请不必把提问的人当成不看文档的小孩

**Comment by Kenshin** [comment]
1. 关闭 issues 也能继续提问... 因此我删除了重复的 Issues

2. 解决方案已经说了，需要把 License 发送到... https://github.com/Kenshin/simpread/issues/5625#issuecomment-1574840294

**Comment by Kenshin** [comment]
补充：邮件发送完毕后在这里通知我下。

**Comment by reov** [comment]
问题描述已经说过了排除了锁定，页面仅显示1台设备，而且已经是在解除锁定后重新尝试过的

**Comment by Kenshin** [comment]
解决你问题最有效的方式是：按照 https://github.com/Kenshin/simpread/issues/5625#issuecomment-1574840294 把我需要的信息（License）发给我。

**Comment by reov** [comment]
已发送

在2023年6月3日六月 下午7:22，Kenshin Wang写道：

**Comment by Kenshin** [comment]
okay 明天确认后会通知你。

**Comment by Kenshin** [comment]
你提供的 License 与 UID 都是正确的，并且我通过你的 UID 使用 https://www.yuque.com/kenshin/simpread/pkq3d1 可以正常登录并授权为高级账户。

PS：我已经把我这台设备的登录信息删除了。（并不会占用高级账户的设备）

PPS：你的账户应该之前反复解锁过，现在是正常状态。

无论你是什么方式，只要按照上面链接中的说明更改为正确的 UID 就行了。

**Comment by reov** [comment]
经过测试还是一样，修改uid会显示是否授权，但是点击授权之后弹窗显示不是高级账户，需要购买

在2023年6月4日六月 下午1:03，Kenshin Wang写道：

**Comment by Kenshin** [comment]
因为我已经测试过了，所以方便的话，最好录屏给我。

使用一个新的浏览器或（没有稍后读数据的话）重新安装简悦。

**Comment by reov** [comment]
莫名其妙解决了，本来新建的虚拟机新下的chrome也是一个故障，结果多试几次好了，宿主机的也可以了

在2023年6月4日六月 下午3:47，Kenshin Wang写道：

**Comment by reov** [comment]
猜测可能还是网络问题，这几个小时间因为节点无法访问外网修改过软路由dns设置

在2023年6月4日六月 下午3:47，Kenshin Wang写道：

**Comment by Kenshin** [comment]
emmmm

简悦的服务器都在国内，除非你做过特别的 DNS 设置，否则应该没问题的。

不过，解决就好。 😂
