### ISSUE TITLE
之前可以“aa”进入阅读模式，现在“aa”无法进入阅读模式。进入阅读模式后“ob”“sr”等等还是可以工作的。

### ISSUE THREAD

**Issue by foreverlong** [Kenshin/simpread#5627]
### 描述这个错误

之前可以“aa”进入阅读模式，现在“aa”无法进入阅读模式。进入阅读模式后“ob”“sr”等等还是可以工作的。

### 复现步骤

之前可以“aa”进入阅读模式，现在“aa”无法进入阅读模式。进入阅读模式后“ob”“sr”等等还是可以工作的。

### 操作系统

Windows10

### 浏览器

chrome

### 发生问题的网址

https://sspai.com/post/58627

**Comment by foreverlong** [comment]
重新安装了一遍简悦，解决了。

**Comment by Kenshin** [comment]
哈，自救成功。

（大概）可能是因为你的操作把快捷键设置错了。

可以在选项页 → 基础设定修改。
