### ISSUE TITLE
标注无法同步到Obsidian

### ISSUE THREAD

**Issue by suanzaozi** [Kenshin/simpread#5629]
### 描述这个错误

1. 标注无法同步到Obsidian。
2. md格式的全文无法保存到Obsidian。
3. 只有一个HTML格式的文件可以同步到Obsidian。
4. 以前保存到OB的标注，“打开当前文档的本地快照”失败，执行该命令，打开的是“new tab”。

### 复现步骤

1. 报错见图片：

![5](https://github.com/Kenshin/simpread/assets/131485512/8fbc317a-384f-47ba-b272-d5153acaf120)

![6](https://github.com/Kenshin/simpread/assets/131485512/9f7dd7b5-7671-40ac-bba0-61c11aaa038c)

![7](https://github.com/Kenshin/simpread/assets/131485512/a2337a8a-b9f7-4cf9-bdc1-eeaff564cf78)

2. 以前正常使用。有一段时间没有使用了，不知道何时出现的问题。
3. Obsidian的版本，从 1.0.3 到最新版本 1.3.5 都试过了，都不能同步标注、md全文，只有一个HTML。
4. 这个页面的方法都试过了，都无法解决。https://github.com/Kenshin/simpread/issues/5558
5. 简悦的浏览器插件试过删除配置再导入。导入到Obsidian的小插件试过重装。都无法解决。

6. 其它图片

![保存失败](https://github.com/Kenshin/simpread/assets/131485512/0b20e463-9e0d-4e96-8a64-2a87ab0eea6e)

![插件](https://github.com/Kenshin/simpread/assets/131485512/3d309f9f-4c02-4a96-bc58-f43acc994c25)

![3](https://github.com/Kenshin/simpread/assets/131485512/0da8f8cb-292d-4b7b-9750-fa4b4a54a296)

### 操作系统

win 11

### 浏览器

Edge

### 发生问题的网址

https://www.thepaper.cn/newsDetail_forward_23258098

**Comment by Kenshin** [comment]
emmm 

看错误应该是 Obsidian 端的简悦插件端口没有设置造成的，打开 Obsidian 选项看下。

或者确保 Obsidian 进运行简悦一个插件（或者重新用一个新库仅安装简悦一个插件）再试试。

**Comment by suanzaozi** [comment]
我的问题解决了，不是大佬上面说的那种问题。
是设置了OB简悦插件的延迟启动造成的，取消掉该插件的延时启动以后就好了。

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 Issues 了

> 设置了OB简悦插件的延迟启动造成的

这是什么（选项）？

**Comment by suanzaozi** [comment]
> 

OB可以通过插件或者其它一些方法，设置所安装插件的启动先后顺序。（按需要，分批次启动插件，用来加快打开ob的速度）
简悦延后启动，跟什么插件会产生冲突，这个我就不清楚了。
感谢回答！

**Comment by Kenshin** [comment]
原来如此，又了解到一些「奇怪」的插件  😏 

PS：这条回复也忒久了点 😂
