### ISSUE TITLE
阅读模式无法解析页面的标题大纲

### ISSUE THREAD

**Issue by FZ20192019** [Kenshin/simpread#5631]
### 描述这个错误

双击AA，进入阅读模式后，所展示的页面无法展示原页面的一级标题，只展示二级标题。
<img width="1902" alt="image" src="https://github.com/Kenshin/simpread/assets/53416803/363fcfd4-ae29-46dd-96f7-dde655a49531">
<img width="1903" alt="image" src="https://github.com/Kenshin/simpread/assets/53416803/80ff304a-590e-4be1-b988-e27cea051171">

### 复现步骤

1. 打开页面
2. 双击AA

### 其他相关说明

无

### 操作系统

macOS

### 浏览器

Chrome 已是最新版本 版本 114.0.5735.90（正式版本） (arm64)

### 发生问题的网址

https://docs.guandata.com/?g=Doc&m=Article&a=index&id=1&aid=454526307678552064#nav-4-H2

**Comment by Kenshin** [comment]
嗨

因为这个站没有适配，所以获取正文时出现了误差，你可以使用下图方式解决

<img width="850" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/715e97f5-01e6-45d8-a9bf-9cded22d1006">

<img width="1808" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/87a1929e-41da-4b65-846a-f3dc93012845">

关于阅读模式的更多玩法可以看看 https://github.com/Kenshin/simpread/discussions/3340
