### ISSUE TITLE
重复调用了两次API后，配置文件损坏？？

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5632]
### 描述这个错误

今天手贱，想测试一下API，结果直接导致配置文件挂了，无法进入简悦配置界面。

### 复现步骤

1.通过Postman调试API
<img width="732" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/41da7d10-7425-4a11-ae78-019bee262da6">
点击了两次Postman的Request按钮

2.返回简悦【稍后读】，文章到了，虽然渲染失败。
<img width="629" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/134482a9-0b96-4bdd-bc98-875ebbb003ab">

3.查看简悦【偏好设置】，挂了。。。
<img width="601" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/a29ae796-185c-42ed-afce-be4bb5d5b17e">

### 其他相关说明

暂无

### 操作系统

macOS Ventura 13.4

### 浏览器

Chrome Version 114.0.5735.90 (Official Build) (arm64)

### 发生问题的网址

https://mp.weixin.qq.com/s/Yy_****

**Comment by shadu120** [comment]
删除了这两行，搞定了。原因不清楚。
<img width="1031" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/7b74f964-e6bd-44ae-b980-78454877f5e0">

**Comment by Kenshin** [comment]
因为没有 `title` 造成的。

<img width="535" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8504ec04-7abe-4981-ae62-dd70a3c98c46">

但 API 文档这里需要改下... 下图的参数是在哪里获取到的？

<img width="781" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3dcb4ced-1f93-4063-b302-53507e0c4965">

PS：以后遇到这个问题可以使用 http://localhost:7026/database/fixed 自动解决。

**Comment by shadu120** [comment]
> 但 API 文档这里需要改下... 下图的参数是在哪里获取到的？

API这里获取到的：https://kb.simpread.pro/#/page/api

<img width="938" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/a0b916be-0719-4b6e-94ab-5f98dfb68319">
