### ISSUE TITLE
保存到有道云笔记必须打开有道云官网才能成功

### ISSUE THREAD

**Issue by 1332987** [Kenshin/simpread#5633]
### 请描述你的建议或任何内容

保存到有道云笔记必须打开有道云官网才能成功,这样做太过于麻烦,希望有更方便简单的办法.

**Comment by Kenshin** [comment]
并没有这种操作 😂 仅在授权时需要确保已登录有道云笔记。

授权需要在：选项页 → 服务 中授权，授权成功后，重启浏览器并查看这个授权是否成功，如果成功的话再测试保存。
