### ISSUE TITLE
两个Notion账号，简悦绑定Notion时，并没有可选择账号的选项

### ISSUE THREAD

**Issue by Arthurwu24** [Kenshin/simpread#5634]
### 描述这个错误

背景：有两个Notion账号，只想绑定其中一个账号作为内容的存储地，但是在简悦绑定Notion账号时并没有可选择绑定账号的选项，总是默认给我绑定到另一个我并不想存储内容的账号上

### 复现步骤

1. 绑定Notion账号 -- 失败，无法选择自己想要绑定的Notion账号

### 操作系统

macOS

### 浏览器

Chrome Version 113.0.5672.92 (Official Build) (arm64)

### 发生问题的网址   （任意网址均有此问题）

https://writings.stephenwolfram.com/2023/02/what-is-chatgpt-doing-and-why-does-it-work/

**Comment by Kenshin** [comment]
emmm 有意思的问题 😂

1. 你在同一个 notion.so 上登录了多个账户？
2. 导入到 Notion 有两种方案，你用的是哪种方案？（告诉我授权的位置或截图都行）

**Comment by Arthurwu24** [comment]
![111](https://github.com/Kenshin/simpread/assets/9261202/d3f119c7-4d19-48ea-9ab8-1088247e83ac) 

1. 这里是两个账号

2. 
![222](https://github.com/Kenshin/simpread/assets/9261202/0d503bd6-5e7a-4bf1-b0c3-9e2c9e33504f)

**Comment by Kenshin** [comment]
emmm

简悦用的是私有 API 并没有这种方案。

> 总是默认给我绑定到另一个我并不想存储内容的账号上

试试加 Pin 的方式能否解决？

<img width="599" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/64f49599-753d-4e6e-811a-3595371e5c36">

如果无法解决的话试试下面的方式：

假设你有两个账户 A 和 B，肯定有一个先后登录顺序（假设按照 A B 的顺序登录），如果 Notion 一直无法找到 B 的 Page，就先退出 Notion（两个都退出）

先登录 B 然后测试简悦是否可以找到你需要的 Page ，如果能的话，就授权它。

最后再登录 A。
