### ISSUE TITLE
服务-授权管理-印象笔记，有道云笔记都无法正常发起授权

### ISSUE THREAD

**Issue by mornone** [Kenshin/simpread#5635]
### 请选择

印象笔记

### 发生问题的网址

印象笔记、有道云笔记

**Comment by Kenshin** [comment]
嗨

1. 印象笔记确实有问题（但我不建议使用印象笔记，现在很多新的笔记都可以完美替代它
2. 有道云笔记的授权没问题。

**Comment by wywwzjj** [comment]
就是为了印象笔记剪藏冲的高级会员，结果用不了，有点失望

**Comment by Kenshin** [comment]
@wywwzjj 

嗨，谢谢支持简悦，留意下面几点：

1. 印象笔记基础账户就可以使用。

2. 印象笔记使用了它自己的 ENML 结构，并且 API 文档不好，所以即便可以使用，效果也原不如印象笔记自己的扩展。

3. 你可以试试 https://github.com/Kenshin/simpread/discussions/3471 这个方案，可以帮助你优化印象笔记剪藏的内容。
