### ISSUE TITLE
包含unocss的网页导致无响应

### ISSUE THREAD

**Issue by yiwangunjiaoluo** [Kenshin/simpread#5636]
### 描述这个错误

在打开包含unocss的网页时，没有使用悦读插件，网页崩溃
经排查后，关闭悦读插件，网页可以正常打开

### 复现步骤

在打开包含unocss的网页时，没有使用悦读插件，网页崩溃
经排查后，关闭悦读插件，网页可以正常打开

### 其他相关说明

没使用阅读功能时，不应该对我的网页进行干预

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

内部网址不能提供

**Comment by Kenshin** [comment]
因为没法排查，但一般下面两个方案都可以解决

1. 加黑名单（选项页 → 高级设定 → 黑名单）

2. 选项页 → 高级设定 → 词法分析引擎 → 关闭此选项

   ![image](https://github.com/Kenshin/simpread/assets/81074/935f47d8-b0b5-4016-b5c9-0680c9ac4d06)
