### ISSUE TITLE
知乎专栏阅读模式会出现文字错误的现象。

### ISSUE THREAD

**Issue by sdl165** [Kenshin/simpread#5637]
### 描述这个错误

进入知乎专栏启动阅读模式后，会出现错误内容，严重影响阅读体验，尝试多个专栏都是这样，而知乎回答阅读模式正常，不知道是否是我个人问题呢？

### 复现步骤

启动阅读模式后
![image](https://github.com/Kenshin/simpread/assets/100999040/51e57566-1ac6-48c9-8743-6ef5ed67da47)

原版
![image](https://github.com/Kenshin/simpread/assets/100999040/f771265f-76e8-4da8-870d-f7c628c2e4df)

### 操作系统

windows

### 浏览器

edge，版本 114.0.1823.37 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/market/paid_column/1388228020830855168/section/1394376859090550784

**Comment by Kenshin** [comment]
我这边没问题

<img width="1226" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bddafb48-4179-49a9-a4e2-2c8142afe706">


还有... 这个链接是什么知乎专栏 😂 知乎的链接怎么这么乱？
