### ISSUE TITLE
保存印象笔记时，网页版图片丢失

### ISSUE THREAD

**Issue by Chenxiaolannnnn** [Kenshin/simpread#564]
使用保存到印象笔记的功能时，在web端查看到的图片只剩下地址，但是在app打开，是可以正常显示图片的

**Comment by Kenshin** [comment]
估计是由于某些图片有防盗链的功能造成的，应该不是简悦的问题。

请问是个例吗？还是每篇都这样？

**Comment by Chenxiaolannnnn** [comment]
是剪藏什么值得买上面的文章发生的，目前是都是这样，web端只有图片地址，app都可以正常查看图片和网址

**Comment by Kenshin** [comment]
我刚刚测试了下，没有发生你说的问题，请看截图

![image](https://user-images.githubusercontent.com/81074/63481268-87f49580-c4c7-11e9-9911-35112232ea2f.png)

测试文章 https://post.smzdm.com/p/a5k6qrd7/

如果你那边使用测试链接没问题的话，请告知具体 URL

**Comment by Chenxiaolannnnn** [comment]
刚刚保存的时候是没有问题的，清除缓存后，或者用无痕窗口打开，图片就无法查看了

**Comment by Kenshin** [comment]
这就不是简悦的问题了。

很好奇，为什么经常清除缓存？

**Comment by Chenxiaolannnnn** [comment]
并不是经常清除缓存，我感觉应该是图片是否并没有存到了印象笔记中，因为我是使用公司的电脑存的文章，但是回到家里登录web端后发现图片都不见了，所以才使用无痕模式或者清除缓存的方式尝试了一下，因为如果是存到了印象笔记中，应该是各个浏览器登录后都能查看到图片。但是手机端又可以，所以我不知道到底是什么情况

**Comment by Kenshin** [comment]
印象笔记并不会保存图片，图片地址还是外链而已。

你说的现象，感觉上还是你浏览器之类的问题。

**Comment by Chenxiaolannnnn** [comment]
嗯，我看了一下图片地址，发现问题了。是剪藏插件收集的文章，是直接将图片转存到印象笔记上去了。简悦本质上只是保存了图片外链，但是这个外链在web无法直接预览也是很奔溃。

**Comment by Kenshin** [comment]
确实是这样的，简悦下个版本会增加此功能。

不过，你的问题确实跟图片是否外链没有关系。

**Comment by Chenxiaolannnnn** [comment]
嗯，我下个版本再试一下。印象web端应该是本身不支持外链图片的预览。麻烦了

**Comment by Kenshin** [comment]
印象笔记支持外链的预览。

请看 https://github.com/Kenshin/simpread/issues/564#issuecomment-523720969 截图所示

**Comment by Chenxiaolannnnn** [comment]
但是这仅限于收藏文章后打开把，你换一个浏览器或者换台电脑登录web图片还在么？

**Comment by Kenshin** [comment]
当然还在。

我所有通过简悦保存到印象笔记中的图片均没有任何问题。

**Comment by Kenshin** [comment]
这两天在解决遗留的问题，又看了一下你说的图片外无法显示的问题，发现我正确的描述有错误。

刚刚详细测试了下：

> 无论是简悦还是印象笔记自带的扩展，保存到印象笔记的图片 **并未为外链，而是自动转换为印象笔记的内链** e.g.  `https://app.yinxiang.com/shard/s9/u/0/res/2dcd4651-edfe-43e7-a3c5-da932693c5db.jpg`

所以 https://github.com/Kenshin/simpread/issues/564#issuecomment-524182452 这条信息描述不正确。

***

请重新确认是否还发生你说的问题？如没有任何问题，请关闭这个 issues

**Comment by Kenshin** [comment]
嗨，请确认此是否是否还存在？

***

简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
