### ISSUE TITLE
racket 官方相关的站点

### ISSUE THREAD

**Issue by kardusenor** [Kenshin/simpread#5640]
### 需要适配的新站

例如 https://htdp.org/2023-5-12/Book/index.html 网站里面代码块在阅读模式中无法正常渲染

### 有需要请描述这个站的性质

该站点文档类型是 racket 语言生态生成的文档所通用的类型

**Comment by Kenshin** [comment]
嗨，这属于代码段的问题，会集中在 #500 并关闭此 Issues 修复后会通知你~
