### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by w84556121** [Kenshin/simpread#5641]
### 请描述你的建议或任何内容

比如这个 http://www.xsbiquge.org/book/9509/12644177.html 网页，当我进入阅读模式的时候，添加标签时，按回车，会触发本网页自带的快捷键，当我按左右键调整光标位置的时候，触发本网页的翻页功能，可不可以在进入阅读模式的时候，屏蔽掉本网页的快捷键啊。

**Comment by Kenshin** [comment]
嗨，你可以使用快捷键 `d d` 加入稍后读，在稍后读中修改。

<img width="1013" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7a45cc8e-9852-4738-af17-4708cc6e47ed">

**Comment by Kenshin** [comment]
简悦的阅读模式不会干扰原页面，所以一般原页面的功能也不会干扰简悦。

所以，简悦的一个「附加功能」可以去除有网页右键限制的功能。

所以，你遇到的问题很特别，很少有用户包含这类情况。

**Comment by w84556121** [comment]
这个对于挂载在本机的网盘支持感觉有些问题，我在另一台电脑上用的好好的，自动同步啥的都没有问题，在本电脑上使用的时候，就直接同步到C:\AppData\Roaming\.ecloud\mountDisk\vfsMeta\ecloud\简悦\SimpRead\output
c盘了，

**Comment by Kenshin** [comment]
> 为啥我的两个页面相互影响

https://github.com/Kenshin/simpread/discussions/3768

**Comment by w84556121** [comment]
> 嗨，你可以使用快捷键 `d d` 加入稍后读，在稍后读中修改。
> 
> <img alt="image" width="1013" src="https://user-images.githubusercontent.com/81074/244011347-7a45cc8e-9852-4738-af17-4708cc6e47ed.png">

加入稍后读之后，标注之后，obsidian不会同步修改了，在网页端就可以，是我的问题，还是不具备这个功能呀

**Comment by Kenshin** [comment]
> 加入稍后读之后，标注之后，obsidian不会同步修改了，在网页端就可以，是我的问题，还是不具备这个功能呀

emmm

在稍后读中确实没法同步到 Obsidian
