### ISSUE TITLE
【Obsidian 配置库】标注内容自动同步到 Obsidian 功能失效

### ISSUE THREAD

**Issue by Wonz5130** [Kenshin/simpread#5642]
### 描述这个错误

大约一周前发现之前按照高级版配置的Obsidian 配置库，标注内容自动同步到 Obsidian 功能失效。但是 output 文件夹内还有自动生成的文件，不过标注多了之后也不同步了，即只保存一开始的几条标注。

昨天又卸载重装了一遍简悦插件，按照配置文档重新配置了一遍，发现还是不行。

### 复现步骤

<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/78554afc-4401-4847-953b-eb8bec40b505">

<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/a5c22d8d-c8ad-4481-ba6a-2dc9a46f3058">

<img width="250" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/fcb4308a-780b-44a2-948d-80ded03b039b">

<img width="1081" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/24e04adc-adbc-4d12-828c-a2c44cf2b129">

### 操作系统

macOS 13.4

### 浏览器

Chrome 114.0.5735.90（正式版本） (arm64)

### 发生问题的网址

https://lutaonan.com/blog/how-do-i-take-note/

**Comment by Kenshin** [comment]
导入全文的功能好使吗？如果也不好使的话，估计是这个造成的 https://github.com/Kenshin/simpread/issues/5558#issuecomment-1549015672

**Comment by Wonz5130** [comment]
导入全文功能好使，但是单独导入标注提示：保存失败。

<img width="540" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/23a6590c-a96b-48a1-a2eb-a235dce155d6">

看了 #5601 和 #5558 ，发现自己的 Obsidian 最近确实升级过，现在的版本是：

<img width="260" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/891f6445-5003-4c4d-98d8-43c190117600">

简悦的 Obsidian 插件端口已经改成 http://localhost:7027 且重启浏览器和重启 Obsidian，发现还是不行。

**Comment by Kenshin** [comment]
> 导入全文功能好使，但是单独导入标注提示：保存失败。

导入全文好使的话，就不是 Installer 的问题（ 这个问题只是个别用户会遇到，但改成 `localhost` 是比较好的方案）

***

标注错误的话，你可以试试随便找个少数派的页面，然后仅加入稍后读不要标注，在试试导入标注的功能，看提示什么错误？

**Comment by Wonz5130** [comment]
sorry，刚注意到这个选项没开（不知道是什么时候给关了）

<img width="615" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/db4aea63-a52c-4b67-ba9c-f2f1c2610a8d">

开启之后，导入标注不会报错，但是只有空白文件，没有任何标注信息，如下图，左边是新导入的，右边是之前的标注笔记：

<img width="1479" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/5a95d622-6546-4ce9-ab68-21d71c295da5">

**Comment by Kenshin** [comment]
> 导入标注不会报错，但是只有空白文件

看起来是没问题的（如果没有标注的话）

如果你的阅读模式下存在标注的话，查看下 Markdown 模板辅助增强，是不是里面的模板没有了？

**Comment by Wonz5130** [comment]
感谢 K大，果然是模板没有了，现在已经可以了。刷新了几次之后发现导入标注这个选项自己给关了（不知道是不是bug）

<img width="624" alt="image" src="https://github.com/Kenshin/simpread/assets/35889526/b08fe6b8-00c8-4644-96c6-22c27ce266ad">

> 另外，按照上图开了自动化方案，点开一篇文章进入阅读模式，标注之后并不会自动生成标注文件，需要手动按一下快捷键 bbb 才会生成相应的标注文件，之前是自动生成无须手动的。

这个也解决了，参考了 #2902 的自动化配置，原来是前几天改了快捷键。再次感谢 K大详细的文档。

**Comment by Kenshin** [comment]
okay 搞定就好  👍 

> 刷新了几次之后发现导入标注这个选项自己给关了（不知道是不是bug）

也不完全算 Bug 😂 折腾配置时留意 https://github.com/Kenshin/simpread/discussions/3768

**Comment by Kenshin** [comment]
哈，不小心在少数派上看到了你的文章。 😄

休息休息也挺好的。  👍

**Comment by Wonz5130** [comment]
哈哈 谢谢 K大关心～
