### ISSUE TITLE
obsidian配置库问题请教

### ISSUE THREAD

**Issue by yanghuatjy** [Kenshin/simpread#5645]
### 请描述你的建议或任何内容

按照教程完成配置,在线标注也很顺利同步到obsidian,但在obsidian里的本地快照上标注会自动生成另一个undefined的html文件,使得标注不显示,是还有哪设置有问题吗?

![111111.jpg](https://lsky.nanding.cf:22443/i/2023/06/08/64811f0294c32.jpg)
![222222.jpg](https://lsky.nanding.cf:22443/i/2023/06/08/64811f0331ee5.jpg)

**Comment by yanghuatjy** [comment]
> > 使得标注不显示,是还有哪设置有问题吗?
> 
> 什么意思？
> 
> > 但在obsidian里的本地快照上标注会自动生成另一个undefined的html文件
> 
> 随便进入一个页面 e.g. https://sspai.com/post/69972 然后右下角，检查下（或截图）你的自动化辅助增强插件，看看跟配置库里面的说明有什么区别？
> 
> 同步助手 → 导出 → 增强导出，看下有没有跟这个错误文件有关系的导出方案？
> 
> 选项页 → 服务 → 自动化，里面有没有跟这个 HTML 相关的设置？
> 
> 一般上面三个地方都会导致截图所示的情况，

把同步助手跟插件全部重置重新配了下正常了

**Comment by Kenshin** [comment]
okay 解决就好。  👍
