### ISSUE TITLE
支持谷歌文档的适配

### ISSUE THREAD

**Issue by ppy233** [Kenshin/simpread#5646]
### 需要适配的新站

https://docs.google.com/document/d/112HBiMNvu6TYbDUOfVRe_MS4A-fKaWYrpMlmnsiMNiA/

### 有需要请描述这个站的性质

谷歌文档无法唤出简悦,阅读模式快捷键无效,右键菜单无简悦.对`docs.google.com`加白名单也无法自动进入阅读模式

**Comment by Kenshin** [comment]
嗨，这类页面（文档类）是不会被适配的，因为涉及到版本（不是说你提交的 URL）

我关闭这个 issues 了。
