### ISSUE TITLE
支持 safari

### ISSUE THREAD

**Issue by hellozgl** [Kenshin/simpread#5647]
### 请描述你的建议或任何内容

RT
一个Safari插件已经等了三年。

**Comment by Kenshin** [comment]
嗨

1. 如果你有留意（或订阅） https://simpread.pro/subscribe 任意通知源的话 哪怕顺便瞧瞧 Issues，就知道简悦一直在更新... 😂
2. 我从未在任何场合说过简悦会优先支持 Safari
3. 简悦仍以  Chromium  为唯一最优先支持的浏览器平台。

目前 Chrome 平台上还有很多未发布以及需要优化的地方，简悦的 Chrome 版本稳定后会一并发布到 Safari 平台。

PS：Mac 平台上有很多很棒的 Chromium 的产品，如 Arc 也可以完美使用简悦。
