### ISSUE TITLE
obsidian的高级库配置已经好了，但怎么让simpread放在自己原来的库里，不要另开一个库

### ISSUE THREAD

**Issue by PenguinWang123** [Kenshin/simpread#5648]
### 请描述你的建议或任何内容

如题

**Comment by Kenshin** [comment]
https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb

配置库里面应该说的很清楚了 😂

**Comment by PenguinWang123** [comment]
我按照“如果已经存在了一些 Obsidian 插件，仅需要将 ***@***.***/.obsidian/plugins 对应的文件夹复制到你自己的 .obsidian/plugins 文件夹中。









然后打开 .obsidian/community-plugins.json 将下面的内容加入你自己的库对应的同名文件其中。
"obsidian42-brat", "simpread", "obsidian-banners", "dataview"
当完成这些操作后，重启 Obsidian 并确保只有一个存在 SimpRead Sync 库的 Obsidian 存在。（如果打开多个 SimpRead Sync 库的话，会因为端口占用无法实现自动同步）



”操作了，同步还是同步在另一个库里，没同步到我自己的库里





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] obsidian的高级库配置已经好了，但怎么让simpread放在自己原来的库里，不要另开一个库 (Issue #5648)





 
https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb
 
配置库里面应该说的很清楚了 😂

**Comment by PenguinWang123** [comment]
解决了，多刷新几遍就好了





&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] obsidian的高级库配置已经好了，但怎么让simpread放在自己原来的库里，不要另开一个库 (Issue #5648)





 
https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb
 
配置库里面应该说的很清楚了 😂

**Comment by Kenshin** [comment]
okay 解决就好~  👍

**Comment by PenguinWang123** [comment]
在高级库的前提下，我如何编辑模板能实现以下效果： 备注[高亮文本-文章标题](文本链接)&nbsp;&nbsp;
是[{{an_text}}-{{title}}]({{int_url}})吗？但这样编写了之后我无法实现这个效果
在markdown辅助增强插件中编辑模板我知道。
您的模板比较复杂，里面涉及元素太多，我也看不懂，我试了好多次都没办法根据现有模板来实现我的效果。







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] obsidian的高级库配置已经好了，但怎么让simpread放在自己原来的库里，不要另开一个库 (Issue #5648)





 
okay 解决就好~  👍

**Comment by Kenshin** [comment]
> 在高级库的前提下，我如何编辑模板能实现以下效果： 备注[高亮文本-文章标题](文本链接)
是 [{{an_text}}-{{title}}]({{int_url}}) 吗？但这样编写了之后我无法实现这个效果

弄不懂模板最好的办法是使用现成的模板 https://github.com/Kenshin/simpread/discussions/2153 （查看 2.0 模板），然后看它们是什么效果。

然后根据 https://github.com/Kenshin/simpread/discussions/3725 里面提到的定制化内容修改

另外，我也没有看懂你想要实现的方式，不要在 Email 中回复，在 https://github.com/Kenshin/simpread/issues/5648 回复。
