### ISSUE TITLE
不能进入阅读模式

### ISSUE THREAD

**Issue by huannnnnn** [Kenshin/simpread#5651]
### 描述这个错误

知乎特定文章不能进入阅读模式，提醒：配置文件已更新，刷新当前页面后才能生效。其他的文章的可以进入阅读模式，

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/89404499/920a7f10-7c89-46d9-8b2c-25ec81e648f1)

### 操作系统

Win11

### 浏览器

Microsoft Edge 版本 114.0.1823.41 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/21417080

**Comment by huannnnnn** [comment]
原来是开了两个同样的页面，已经解决问题

**Comment by Kenshin** [comment]
哈，解决就好  👍
