### ISSUE TITLE
notion无法授权

### ISSUE THREAD

**Issue by heluq** [Kenshin/simpread#5653]
### 描述这个错误

notion无法授权，显示“授权中，请勿关闭此页面，授权成功后会有提示。”后就没有动静， 这个账号是edu的，试了下另一个账号，退出重新登，可以授权

### 复现步骤

notion无法授权，显示“授权中，请勿关闭此页面，授权成功后会有提示。”后就没有动静， 这个账号是edu的，试了下另一个账号，退出重新登，可以授权

### 操作系统

WIN10

### 浏览器

edge

### 发生问题的网址

notion

**Comment by Kenshin** [comment]
emmm

简悦授权时使用了私有 API 可能在某些特殊账户下会有问题，试试 https://www.yuque.com/kenshin/simpread/wwk65u#ERFLg 能否解决？

如果不能的话，建议不要在 edu 账户下使用，你可以在正常授权的账户下使用，然后在登录一次你的 edu 账户。
