### ISSUE TITLE
访问 discuss.fresns.cn 会导致浏览器卡死

### ISSUE THREAD

**Issue by niefufeng** [Kenshin/simpread#5654]
### 描述这个错误

启用该插件后，访问 https://discuss.fresns.cn 会导致浏览器卡死至少30秒。

### 复现步骤

1. 将除了简阅之外的浏览器插件关闭
2. 访问 https://discuss.fresns.cn

### 操作系统

macOS

### 浏览器

Google Chrome 114

### 发生问题的网址

https://discuss.fresns.cn

**Comment by Kenshin** [comment]
嗨，我测试了下是没问题的（不录屏了...

你可以这样排查：**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

也可以将这个站加入到黑名单 `discuss.fresns.cn` 如何使用 [看这里](https://simpread.pro/docs/#/%E9%BB%91%E5%90%8D%E5%8D%95)。

或者试试关闭下面选项

![image](https://github.com/Kenshin/simpread/assets/81074/70af2d95-e8ae-4bae-b0e1-f3e2cbbb8b74)

**Comment by niefufeng** [comment]
@Kenshin 您好，这边使用两台Mac都试过了，隐身模式也会卡死，关掉你说的这个选项也会

我最开始的描述不太准备，只有在登录以后才会卡死（无论在哪个页面），游客状态没问题

另外也向 https://github.com/fresns/fresns 反馈了该 BUG

**Comment by Kenshin** [comment]
emmm 我随便注册了一个账户登录后，首页是没问题的，但随便进入一个页面后 e.g.  https://discuss.fresns.cn/post/VXfNim7B

确实有你说的问题，但我加黑名单后就没事了。

<img width="939" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ddff4986-99ca-41f7-a5a7-155fad8f7db4">

按上图加黑名单后，刷新页面确保生效后重启浏览器。
