### ISSUE TITLE
稍后读中的文件顺序能否重排并重新导出至本地？

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5655]
### 描述这个错误

大概是因为刚开始折腾的时候一些设置项不对/操作过快/网络不稳定等原因，稍后读中有一些序号数字被跳过了，有一些又重复了，重复的这些用ob内置插件改格式也不跟着走，很头疼

### 复现步骤

![Uploading image.png…]()

![Uploading image.png…]()

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

与网址无关

**Comment by Kenshin** [comment]
稍后读的序号是自增长的，如果有多台设备同步的话，可能会出现序号断开的情况。

虽然我能 Get 到你的想法，但其实没啥意义，不连接就不连接呗。

你可以试试 http://localhost:7026/database/snapshot 这个功能，虽然它不能解决你的问题，但可以找到缺失本地快照的稍后读以及缺失稍后读的本地快照。

**Comment by PupupupuTong** [comment]
不连接问题不大，麻烦的是重复的

![image](https://github.com/Kenshin/simpread/assets/69069739/88adf9ea-f61f-4c6e-aaca-62b4add20fe1)

像这样，好多

> 重复的这些用ob内置插件改格式也不跟着走

咋整？

**Comment by Kenshin** [comment]
有点「问题」，

这些重复的 id 在稍后读中都有记录吗？
