### ISSUE TITLE
PDF导出问题

### ISSUE THREAD

**Issue by buddyrui** [Kenshin/simpread#5656]
### 描述这个错误

任意网站pdf高级打印方案导出的英文标题单词间没空格，而且设置页边距后标题右边显示不全，而基础方案没有这个问题。另外两个方案英文标题中","会转换成"_"，而中文"，"不会。
![image](https://github.com/Kenshin/simpread/assets/15306455/929ad458-383c-4174-b055-3396cc929f83)
![image](https://github.com/Kenshin/simpread/assets/15306455/230a3ba2-7599-4e50-a433-c964f0cfc5cc)
![image](https://github.com/Kenshin/simpread/assets/15306455/79cead96-6e76-459f-87e8-e17ecd2bc35b)

### 复现步骤

1.打开任意有逗号的英文标题的网页；
2.分别用高级和基础方案导出pdf即可；
3.下图为我的高级方案边框设置。
![image](https://github.com/Kenshin/simpread/assets/15306455/3c697264-4f4f-4448-87f5-6ecb0113d15c)
![image](https://github.com/Kenshin/simpread/assets/15306455/6bcb206c-5cb1-42c0-a3a7-667b4bc0b293)

### 操作系统

Win11

### 浏览器

Edge

### 发生问题的网址

https://www.scmp.com/business/banking-finance/article/3223726/greater-bay-area-prudential-opens-first-branch-macau-joining-hsbc-life-manulife-battle-mainland

**Comment by Kenshin** [comment]
emmm 确实如此。

其它英文页面有类似的问题吗？我稍晚调查下。

**Comment by Kenshin** [comment]
嗨，这个错误被修复了，效果如下：

<img width="782" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c0e37159-b236-496b-9968-daaca2e8e0e7">

如果你觉得标题不好看的话，可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 在导出前优化下标题（去掉特殊字符，仅保留空格）即可。

因为使用了同步助手，所以请通过 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 升级。

**Comment by buddyrui** [comment]
给力，牛逼！

**Comment by Kenshin** [comment]
哈，解决就好。

小事情~


***

蹲个五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by buddyrui** [comment]
![image](https://github.com/Kenshin/simpread/assets/15306455/88a2a4d3-0b91-4038-b23a-b6c8f99a4d15)

**Comment by Kenshin** [comment]
哈，没想到是个老用户  👍
