### ISSUE TITLE
导出含 全文+标记 的markdown

### ISSUE THREAD

**Issue by garyxj** [Kenshin/simpread#5657]
### 请描述你的建议或任何内容

【当前】
可以导出仅含标记和批注的markdown文件，同时可以自定义导出的内容，如增加日期等。
【期望】
1. 可以导出全文，且全文内容可以含划线批注（字体颜色、高亮、批注）等信息的markdown。
2. 可以自定义导出的全文，如增加添加的日期，方便在obsidian内根据日期查找。
【背景】
1. 初次阅读习惯用稍后读，但二次整理使用obsidian，有时在两个文件 @annote 和 全文内来回整理。
2. @annote文件中无稍后读的颜色区分。
3. 全文内没有阅读的记录，有重复阅读的困扰。

**Comment by Kenshin** [comment]
嗨

> 初次阅读习惯用稍后读，但二次整理使用obsidian，有时在两个文件 @annote 和 全文内来回整理。 @annote文件中无稍后读的颜色区分。

> 可以导出全文，且全文内容可以含划线批注（字体颜色、高亮、批注）等信息的markdown。

Markdown 仅仅只是个文本而已，不可能有在全文包含标注的形式，即便有，也没有 HTML 正常。也就是不太可能出现颜色。

但标注中可以适当的出现颜色，可以看这里的模板 https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600

非要说的话，Obsidian 应该支持在 Markdown 中渲染 HTML，但太复杂了，也没有意义 😂

> 可以自定义导出的全文，如增加添加的日期，方便在obsidian内根据日期查找。

导入全文时支持 Metadatab 方案 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590065

> 全文内没有阅读的记录，有重复阅读的困扰。

你需要什么样的阅读记录 😂

PS：无论是全文还是 `@annote.md` 仅仅只是个 Markdown，而你大部分的需求都没法使用 Markdown 实现。

**Comment by Kenshin** [comment]
嗨，你的问题 https://github.com/Kenshin/simpread/issues/5658 放在这里就好，因为它们差不多是一样的。

另外，即便我 Close Issues 后你仍可以跟我讨论 😄

***

> 当前通过稍后读导出全文或批注是2选1，我希望导出的全文里面有高亮/颜色的批注内容。

当导出的是 HTML 时，自然会包含标注（也有颜色）；反之导出的是 Markdown 我上面已经说过了。

关于当加入稍后读导出的，建议看（以及配置）下 https://www.yuque.com/kenshin/simpread/wkswh7
