### ISSUE TITLE
live editor 加粗内容不能明显区分

### ISSUE THREAD

**Issue by WhyWhatHow** [Kenshin/simpread#5659]
## 环境:
- win 10 
-  chrome 
## 问题:
live editor 下 ,加粗  选中内容  不能加粗

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/33270266/4b51aed1-3a02-435d-b6c6-b72f07a79c2e)
加粗后的内容
```
<strong>人类可以尽快的逃离自然灾难，并且在自然灾难发生之后可以尽快重建，只不过如此而已</strong>
```
## 猜测:
- document 修改元素为添加css 配置样式, <strong >标签在部分browser中不可用.

## 可能的解决办法:
```
<strong style="
    font-weight: bold;
">人类可以尽快的逃离自然灾难，并且在自然灾难发生之后可以尽快重建，只不过如此而已</strong>
```

## By the way: 
如何在live editor 中添加标注呢? 如果不能的话,体验多多少少有些割裂.
## PS:
辛苦

### 操作系统

windows10

### 浏览器

chrome  114.0.5735.91

### 发生问题的网址

https://weekly.tw93.fun/posts/132-%E5%8F%AF%E7%88%B1%E9%9B%95%E5%A1%91/

**Comment by WhyWhatHow** [comment]
thanks ,解决问题了

**Comment by Kenshin** [comment]
哈，解决就好。👍
