### ISSUE TITLE
关于阅读助手的建议

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5661]
看来我修改后的回复被吃了，感觉我们说的是不同两件事情，我的这个请求应该不涉及到你上面提到的内容。

目前来说，如果需要使用这个助手的话，必须拥有一个OpenAI的API key，并且同时拥有直接访问OpenAI API的网络，两者缺一不可。如果这个“自定义OpenAI”域名的请求实现了的话，可以帮助大家部分解决上面提到的两个问题，使得更加容易使用这个助手。

**Comment by Kenshin** [comment]
@bobwng 

嗨，我新建了一个 Issues 用来追踪这个建议。

**Comment by bobwng** [comment]
谢谢，SimpRead很好用，也祝他做得越来越好！

**Comment by Kenshin** [comment]
嗨，一个好消息：OpenAI 调整了一些内容，并且增加了一些方便长文章检索的方案，所以你的需求的优先级可以提前了 

😄

**Comment by bobwng** [comment]
太好了！

**Comment by galendai** [comment]
感谢，期待可以自定义设置OPENAI URL, 用魔法打败魔法。。。

**Comment by Kenshin** [comment]
嗨，各位。

我在这里调研下 **使用自定义 API 的意义**，看到后请在 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1621070991 回复讨论

**Comment by Kenshin** [comment]
![OpenAI@cover v2](https://github.com/Kenshin/simpread/assets/81074/03673e06-13fd-4752-b6e7-34cfcc460feb)

嗨，[阅读助手 3.1.0](https://github.com/Kenshin/simpread/discussions/5158) 发布了

## 新功能

- `Add` [自定义第三方 API 服务](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6361313)

    ![image](https://github.com/Kenshin/simpread/assets/81074/a4eb995e-0a29-4767-962f-92d498899d1f)

- `Add` [支持 GPT-4](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5175855)

    ![image](https://github.com/Kenshin/simpread/assets/81074/30440609-23d2-4767-8411-2c31d8dba999)

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/Mv55R9uIOF) 安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

有任何疑问请前往 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1624903383 讨论，我关闭这个 issues 了~
