### ISSUE TITLE
近期出现导出到Obsidian，图片失效

### ISSUE THREAD

**Issue by Lynyh22** [Kenshin/simpread#5662]
### 描述这个错误

近期更新了简悦同步助手，以及Obsidian内的Simpread Sync插件（不清楚是因为哪一个更新引起的），开始出现导出到Obsidian的文章内图片失效的问题，此前从未出现过，如图所示
![图片显示“img-0”未创建，点击以创建](https://github.com/Kenshin/simpread/assets/94436542/37332052-61a2-4a03-a3c5-6c0e8bcfd1da)
以下为导入到Obsidian插件配置截图
![2](https://github.com/Kenshin/simpread/assets/94436542/afa3d3f3-3e2e-42c1-9550-b64d8c3c9c89)

### 复现步骤

1.进入文章阅读模式；
2.通过快捷键dd触发自动化，自动化配置如下
![企业微信截图_20230614114006](https://github.com/Kenshin/simpread/assets/94436542/b2ef3478-0761-4568-bed7-627ee4062831)
3.提示保存成功；
4.Obsidian内显示图片未创建。

### 操作系统

windows 10

### 浏览器

Chrome 113.0.5672.93（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
emmm

这个文件夹下面有图片吗？

**Comment by Lynyh22** [comment]
有的，但就是不显示。

**Comment by Lynyh22** [comment]
有的，但就是不显示。
不过我已经通过其他方法解决这个问题了：我之前是同步助手内的导出路径填写的是icloud里obsidian的文件夹路径，之前这样用着一直很正常，直到最近出现这个问题。所以我把导出路径改回了坚果云的Simpread/Output路径，就变正常了。

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 issues 了。

> 我之前是同步助手内的导出路径填写的是icloud里obsidian的文件夹路径

你的描述似乎有点问题。

你给我的截图是在选项卡中设置的路径

<img width="622" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/19387263-df1e-41c0-938d-31a8c125d47b">

但你的描述却说了在同步助手的增强导出设置的路径。

***

**在选项卡的路径的优先级比同步助手的高。**

你可以确保仅仅设置了同步助手的路径，删除选项卡中的路径，删除保存后重启浏览器确保操作生效。

反之，没有设置同步助手的增强导出路径的话，可以安装下面的方式设置。

1. 截图中的路径删除后保存（然后刷新页面，确认你的操作已生效）
2. 在同步助手的增强导出中设置路径

<img width="676" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0062e7d7-9320-4787-bd87-63e7f02211ec">

```
{"extension":"assets", "path":"/Users/xxxx/xxxx/Obsidian/SimpRead"}
```
这种方式。

**Comment by Lynyh22** [comment]
是这样，选项卡内md+assets的路径我之前是从没设置和使用过的，但是obsidian都正常显示图片。我是因为这次出现这个问题去看了各个文档，然后才尝试设置md+assets路径，情况是选项卡设置的那个路径下确实有assets文件夹，但是obsidian里还是无法正常显示图片，所以我才另外尝试了修改同步助手里的导出路径。（我说的是上面的导出路径，不是增强导出的路径）
![企业微信截图_20230616110805](https://github.com/Kenshin/simpread/assets/94436542/4239e3f4-297b-4774-9a93-dbf26fd1ff50)

**Comment by Kenshin** [comment]
> 是这样，选项卡内md+assets的路径我之前是从没设置和使用过的，但是obsidian都正常显示图片。我是因为这次出现这个问题去看了各个文档，然后才尝试设置md+assets路径，情况是选项卡设置的那个路径下确实有assets文件夹，但是obsidian里还是无法正常显示图片，所以我才另外尝试了修改同步助手里的导出路径。（我说的是上面的导出路径，不是增强导出的路径）

emmm 你现在的图片都保存在 `output/assets` 下面吗？而 `output` 也是 Obsidian 库文件夹？

**Comment by Lynyh22** [comment]
现在我已经关闭md+assets的功能了，output现在已经改为坚果云下了

**Comment by Kenshin** [comment]
> 现在我已经关闭md+assets的功能了，output现在已经改为坚果云下了

okay

PS：你暂时不需要 `md + assets` 这个功能了？

**Comment by Lynyh22** [comment]
其实我也很混乱，因为我一直以来都是关闭md+assets这个功能但是图片正常显示的，我其实不太理解我目前的状态开不开这个功能的区别。

**Comment by Kenshin** [comment]
> 关闭md+assets这个功能但是图片正常显示的

关闭这个选项后，图片是在线的。

**Comment by Lynyh22** [comment]
好的，我再摸索看看。

**Comment by Kenshin** [comment]
这个功能很简单，如何使用的话，看 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2705604

最简单的方案：

在插件中设置路径（类似你的截图），然后跟这个选项相关的都用默认值就行。

<img width="607" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/edf770d6-1728-4d10-ac9c-b78d162119a5">

修改完重启浏览器确保生效即可。
