### ISSUE TITLE
在导入思源会出现一堆代码 文字下面

### ISSUE THREAD

**Issue by Jackson2002** [Kenshin/simpread#5664]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/57218370/73531d25-5d68-484b-bbdc-3c1615654500)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/57218370/cace5c4f-57df-43d8-9b13-6285a4e2fc54)

### 操作系统

win

### 浏览器

edge

### 发生问题的网址

公众号

**Comment by Kenshin** [comment]
嗨

这串内容是图片 `base64` 编码，不是简悦的问题。

你是不是使用了 **离线 HTML** 或 **assets + md** 的功能？

在导入到思源笔记前要避免使用上面提到的这两个方案。

**Comment by Jackson2002** [comment]
是的我同时用了ob建仓库

那我要用什么方式？
再问一个 就是不嫩把标注也同步过去吗

**Comment by Kenshin** [comment]
> 就是不嫩把标注也同步过去吗

下个大版本支持。

> 是的我同时用了ob建仓库，那我要用什么方式？

你同时导入到 Obsidian 与思源笔记？

如果是的话，可以在自动化辅助增强里面把思源笔记放到 Obsidian 前面 e.g. 

<img width="534" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a7c33126-9867-4108-b540-8b6059a7542f">

但我不确定 100 % 能解决。
