### ISSUE TITLE
缺少两端对齐

### ISSUE THREAD

**Issue by fengyushu** [Kenshin/simpread#567]
宽度调整后为左对齐格式，无两端对齐选项设置，影响了阅读观感

**Comment by Kenshin** [comment]
嗨，你可以试试 https://simpread.ksria.cn/plugins/details/VCAENkqLbO 这个插件。

如果解决了你的问题，请关闭此 issus :)

**Comment by fengyushu** [comment]
收到，感谢，还没有专门看过插件



------------------ 原始邮件 ------------------
发件人: "Kenshin Wang"<notifications@github.com>; 
发送时间: 2019年8月28日(星期三) 上午9:45
收件人: "Kenshin/simpread"<simpread@noreply.github.com>; 
抄送: "风与树笑说"<294271082@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Kenshin/simpread] 缺少两端对齐 (#567)




嗨，你可以试试 https://simpread.ksria.cn/plugins/details/VCAENkqLbO 这个插件。
 
如果解决了你的问题，请关闭此 issus :)

**Comment by Kenshin** [comment]
没事，搞定就好。

插件系统确实我也没怎么宣传，目前还比较原始些。
