### ISSUE TITLE
关于稍后读页面的阅读区异常占位问题

### ISSUE THREAD

**Issue by tibbers1210** [Kenshin/simpread#5671]
### 描述这个错误

打开稍后读页面，选中阅读内容后，右侧阅读区上部被主页图片占用，同时底栏消失不显示。

### 复现步骤

1.打开稍后读主页
![image](https://github.com/Kenshin/simpread/assets/136883123/58e47a77-a138-4e8c-9c6e-4c58c16e2aa8)

2.选中某一项以阅读模式打开
![image](https://github.com/Kenshin/simpread/assets/136883123/8d94e4c7-7340-49ee-9535-0ca9e2a13a1a)

3.发现右侧阅读区，上部被稍后读主页图片占据，无法消除，同时底栏消失，无法呼出
![image](https://github.com/Kenshin/simpread/assets/136883123/1c5bcc28-a845-48bf-8464-e97f32e853e9)

### 操作系统

WIN 10 

### 浏览器

Edge版本 114.0.1823.43 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/625188310

**Comment by Kenshin** [comment]
emmm

应该是配置文件中的某个地方错误导致的。

你可以使用 http://localhost:7026/database/fixed 修复下这个配置文件。

**Comment by tibbers1210** [comment]
![image](https://github.com/Kenshin/simpread/assets/136883123/0d036060-bcf8-46bc-a691-b5d8208fe5f1)
修复完成后没有问题了，感谢解答

**Comment by Kenshin** [comment]
哈，搞定就好~  👍

**Comment by tibbers1210** [comment]
> 哈，搞定就好~ 👍

很不幸它又出现了。并且这次修复软件没有能检出问题。
引发的诱因可能是对自动化任务修改为手动执行的设置。
因为想要避免标注后频繁产出的多条【已成功导出】的打扰，又想要相对便捷的导出操作（指同时一键导出为md和html格式），所以想要把自动触发改为手动执行，查询相关教程似乎理论可行的，但是我多次修改尝试，按下图标后都没有反应。
在这两次稍后读页面异常之前，我都在尝试找出【以标注为触发项的自动导出任务】更改为【手动执行】后失效的原因，并且发现这种修改偶尔会导致图标前景色和后景色变为一致的情况。

**Comment by Kenshin** [comment]
> 引发的诱因可能是对自动化任务修改为手动执行的设置。

emmm 能稳定复现吗？

> 因为想要避免标注后频繁产出的多条【已成功导出】的打扰，又想要相对便捷的导出操作（指同时一键导出为md和html格式），所以想要把自动触发改为手动执行，查询相关教程似乎理论可行的

是可行的…理论上也应该跟你提到的现象无关。

**Comment by tibbers1210** [comment]
> emmm 能稳定复现吗？
emm 我明天再多试试几次记下过程和结果 但是要是不能先恢复原状好像没法对照实验
> 是可行的…理论上也应该跟你提到的现象无关。
确实 奇奇怪怪的 希望别是啥超稀有的“彩蛋”（虽然影响也不是特别大hh）

**Comment by Kenshin** [comment]
okay 如果能稳定复现的话，把错误的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5671

另外，如果要调整简悦配置项的话，可以看下 https://github.com/Kenshin/simpread/discussions/3768 提到的几个注意点。
