### ISSUE TITLE
知乎打开阅读模式第一段文字出现空格或横线

### ISSUE THREAD

**Issue by narouss** [Kenshin/simpread#5673]
### 描述这个错误

网页进入阅读模式后，部分文字有间距，复制后仅文本粘贴到word文档，出现空格或横线分隔符

### 复现步骤

1.网页进入阅读模式
![Snipaste_2023-06-17_22-06-00](https://github.com/Kenshin/simpread/assets/95953125/7668296f-c8bb-4a1c-9bd3-06f225e7b1c1)
2.复制文章开头粘贴到word
![Snipaste_2023-06-17_22-06-39](https://github.com/Kenshin/simpread/assets/95953125/530dd96a-7521-49db-bece-d985be23c87d)

### 其他相关说明

平时需要把文章复制到word，前一段时间还没有这个问题，近几天发现复制后前面一部分内容会出现异常空格和横线

### 操作系统

win10

### 浏览器

Chrome  114.0.5735.134

### 发生问题的网址

https://www.zhihu.com/market/paid_column/1570495549291401216/section/1588543021062184960

**Comment by Kenshin** [comment]
1. 试试隐私模式，仅启用简悦，排除其他扩展的干扰。
2. 其他知乎页面是否有这个问题？
3. 试试 https://github.com/Kenshin/simpread/discussions/3340

**Comment by Kenshin** [comment]
可能是下图造成的，但这不是简悦的问题，它原页面上就有这个东西。

<img width="1178" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5ddb9f10-e76e-4d56-9095-38cd73ce200e">

你可以试试其它页面 e.g. https://sspai.com/post/69972 应该没有这个问题。

不过，使用简悦的导出 `.docx` 是问题的。

<img width="504" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/35cfb2ec-d968-42e4-9132-45a82dbc41c8">

但这个功能需要高级账户权限以及 [配置](https://simpread.pro/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA) 下。

**Comment by narouss** [comment]
好的，多谢，我尝试一下，已订阅高级账号

**Comment by Kenshin** [comment]
okay 有任何问题都可以虽然反馈。
