### ISSUE TITLE
希望能有清除正文内链接功能的插件

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5674]
### 请描述你的建议或任何内容

![image](https://github.com/Kenshin/simpread/assets/69069739/91a3e941-5f95-411a-81d4-3f3c6b619602)
就比如这种带链接的词条，标注导出到本地也会带着链接，多数时候并不需要。希望能有办法实现一键清除全文链接和手动点选清除区块内或单个链接（其实就是无格式文本）

**Comment by Kenshin** [comment]
okay 可以考虑~  👍

**Comment by Kenshin** [comment]
嗨，[清理链接](https://github.com/Kenshin/simpread/discussions/2734) 升级到 1.0.2 版，增加了 [清理正文全部超链接](https://github.com/Kenshin/simpread/discussions/2734#discussioncomment-6371147) 功能。

![image](https://github.com/Kenshin/simpread/assets/81074/226246a5-38e8-4920-b222-49f0cf3dffe7)

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/1VIRZ7VGc3) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 有任何问题仍可以在这里跟我讨论~

**Comment by PupupupuTong** [comment]
感谢大佬！辛苦了✿✿ヽ(°▽°)ノ✿还剩一个小问题，以前带链接的标注现在成这样了

![image](https://github.com/Kenshin/simpread/assets/69069739/2f4e0221-74c5-4aaf-b5dc-1310c3b55326)

而且得逐条重新标注一次才能把本地md里的链接都清掉，有简单点的办法吗？

**Comment by Kenshin** [comment]
> 以前带链接的标注现在成这样了

这个暂时没办法 😂 标注比较特殊。

**Comment by Kenshin** [comment]
关联 Issues https://github.com/Kenshin/simpread/issues/2733
