### ISSUE TITLE
markdown模板辅助增强插件，使用的官方模板，浏览器为chrome，点测试没反应，是哪里出了问题

### ISSUE THREAD

**Issue by anchor21** [Kenshin/simpread#5675]
### 描述这个错误

markdown模板辅助增强插件，使用的官方模板，浏览器为chrome，点测试没反应，是哪里出了问题，RT

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/136314492/8f8891f7-bd94-420d-9346-3b139c180f18)

### 操作系统

Windows11

### 浏览器

Chrome版本 114.0.5735.134（正式版本）

### 发生问题的网址

每一个

**Comment by Kenshin** [comment]
嗨

1. 测试的前提：当前页面有标注。
2. 建议在 https://sspai.com/post/69972 测试，排除其它因素的干扰。

如果还是有问题的话，鼠标右键 → 检查 → 打开 Devtool 然后点测试，看看有什么报错。同时告诉我具体使用了哪个模板？

**Comment by anchor21** [comment]
已解决，原因是当前页面没有标注

**Comment by Kenshin** [comment]
okay 解决就好~
