### ISSUE TITLE
同步助手无法授权验证

### ISSUE THREAD

**Issue by archer3831** [Kenshin/simpread#5678]
### 描述这个错误

重装电脑后，配置同步助手，发现无法授权验证，看之前回答是访问同步助手服务失败的原因，但是我都设置过了，依旧不行。

### 复现步骤

启动
![Snipaste_2023-06-19_00-18-15](https://github.com/Kenshin/simpread/assets/59408395/bcc12a2c-ae55-4f48-8283-55059683cdd4)
报错
![Snipaste_2023-06-19_00-18-52](https://github.com/Kenshin/simpread/assets/59408395/b0535819-d419-4939-a803-fd453df689c4)
权限
![Snipaste_2023-06-19_00-21-58](https://github.com/Kenshin/simpread/assets/59408395/b9c378a6-b996-47ba-afe2-c11ebb77d8f8)

### 操作系统

windows11

### 浏览器

360极速浏览器

### 发生问题的网址

chrome-extension://cjbeegepjpakdhjkjclfjiigoibigipf/options/options.html

**Comment by Kenshin** [comment]
emmm

扩展端先确认下是否是高级账户权限。

另外，我看到你提示了 360浏览器，方便的话，能否试试 Edge 浏览器？

**Comment by archer3831** [comment]
彻底删除浏览器后，重新再下载之后，好了，之前可能删的不够干净。

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 issues 了~
