### ISSUE TITLE
授权到印象笔记失败

### ISSUE THREAD

**Issue by utomma** [Kenshin/simpread#568]
授权到印象笔记时，显示 获取印象笔记授权失败，请重新获取，是什么原因呢

**Comment by Kenshin** [comment]
嗨，抱歉！
这个月的人数又增加太大了，后台的一个服务器配额满了，所以只能在 1号恢复此功能。

恢复后，我会通过这里告诉你。

**Comment by Kenshin** [comment]
已经恢复，我将关闭此功能。
接下来，我要着手解决这个「麻烦了」。
