### ISSUE TITLE
请问左侧的目录要怎么关闭或者调整为靠近左侧自动展开？

### ISSUE THREAD

**Issue by anchor21** [Kenshin/simpread#5680]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/136314492/8ef9c4ce-87df-4c4c-acdd-1d79de24d3dc)

### 复现步骤

使用的是官方的obsidian高级配置库，rt

### 操作系统

Win11

### 浏览器

chrome

### 发生问题的网址

all

**Comment by Kenshin** [comment]
你截图的右下角


<img width="514" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cd009e25-ae2a-4665-be49-2e25f25e75eb">

**Comment by anchor21** [comment]
> 你截图的右下角
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/81074/246990162-cd009e25-ae2a-4665-be49-2e25f25e75eb.png">

无论我是打开红框内第三个选项还是关闭它，目录始终都在那，我想要的就是第三个选项的功能，但是不起作用

**Comment by Kenshin** [comment]
😂  你用的这个主题应该没法隐藏目录。

目前可以做到隐藏，但不会出现：鼠标以上时显示。

```
toc {
    display: none!important;
}
```

加入到下图，保存后重启浏览器。

<img width="471" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a37660d2-cc87-4ac8-896a-8b00478e331c">

**Comment by anchor21** [comment]
> 😂 你用的这个主题应该没法隐藏目录。
> 
> 目前可以做到隐藏，但不会出现：鼠标以上时显示。
> 
> ```
> toc {
>     display: none!important;
> }
> ```
> 
> 加入到下图，保存后重启浏览器。
> 
> <img alt="image" width="471" src="https://user-images.githubusercontent.com/81074/246991613-a37660d2-cc87-4ac8-896a-8b00478e331c.png">

好的我明白了，但我用的是官网上面的obsidian高级配置库

**Comment by Kenshin** [comment]
> 我用的是官网上面的obsidian高级配置库

跟什么库没关系... 配置库也只是配置的组合而已。

**Comment by anchor21** [comment]
> > 我用的是官网上面的obsidian高级配置库
> 
> 跟什么库没关系... 配置库也只是配置的组合而已。

好的作者大大，如果有时间的话请看一下我的另一个issue
