### ISSUE TITLE
关于zapier

### ISSUE THREAD

**Issue by Lao-Tz** [Kenshin/simpread#5682]
### 描述这个错误

我创建好了pocket —>简悦的zapier，测试时这些信息全发到了simpread_config.json中，没有出现在简悦的稍后读，这是为什么呢

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/93063057/a2bd6c66-4b31-406c-a959-1c8306e27178)

### 其他相关说明

因为简悦是邀请使用的，所以我无法提供zapier的邀请链接。

### 操作系统

window10

### 浏览器

edge

### 发生问题的网址

https://zapier.com/editor/197528539/draft/197528540/sample

**Comment by Kenshin** [comment]
> 测试时这些信息全发到了simpread_config.json中，没有出现在简悦的稍后读

你需要配置知识库 https://www.yuque.com/kenshin/simpread/wkswh7 也就是让简悦读取你本地 `simpread_config.json`。

我记得 Pocket 的那篇文章应该有介绍知识库这个功能。

***

PS：我看你的使用疑问比较多，你可以直接在这个 Issues 里面跟我讨论。即便我关闭 Issues 也可以继续讨论。

**Comment by Lao-Tz** [comment]
![image](https://github.com/Kenshin/simpread/assets/93063057/fb4731fb-991c-461e-8d92-413553b1b948)
我非常困惑，按要求知识库配置两遍了，离线网页好像创建不了

**Comment by Lao-Tz** [comment]
可以运行了，我不知道为什么有两个一样的简悦插件，下面那个插件无效。感谢大佬积极帮助！

**Comment by Kenshin** [comment]
> 可以运行了

Cool~

> 我不知道为什么有两个一样的简悦插件

什么意思？

**Comment by Lao-Tz** [comment]
> > 可以运行了
> 
> Cool~ 酷~
> 
> > 我不知道为什么有两个一样的简悦插件
> 
> 什么意思？

我右键`管理拓展`，两个插件也只显示一个页面，都不出新标签。之前一直是把下面那个插件固定在edge工具栏的，导致我怎么都折腾不好。后面发现我有两个插件，在另一个里都是好的，就把前面那个卸载了。

大佬再问一下，pocket不能保存全文的链接好像不会发到Zapier，
例如：http://www.cac.gov.cn/2023-06/20/c_1688910683316256.htm
我是手机端RSS的重度使用者，优质网页我大都会给做成RSS进行订阅，因此我理想的信息流是 ：
PC端：网页/RSS -> 中转稍后读（简悦、慢读）-> 开源笔记库(obsidian、Joplin等)、复习库(anki、卡片阅读)
安卓端：RSS -> 中转稍后读（简悦、慢读） -> 开源笔记库(obsidian、Joplin等)、复习库(anki、卡片阅读)
慢读的网页剪切远不如简悦，但慢读有一个比较完整的中转系统，包括安卓、PC端和云同步。
考虑到数据安全以及网页剪裁标注确实简悦更优秀，但目前简悦似乎不能作为安卓的中转，不知道未来一年内您有没有补上这个空缺的打算？

**Comment by Kenshin** [comment]
> 我右键管理拓展，两个插件也只显示一个页面，都不出新标签。之前一直是把下面那个插件固定在edge工具栏的，导致我怎么都折腾不好。后面发现我有两个插件，在另一个里都是好的，就把前面那个卸载了

你是说有两个简悦？估计用 Edeg 浏览器然后同时安装了 Edge 和 Chrome 的版本。

> pocket不能保存全文的链接好像不会发到Zapier

其实有一个更简单的方案：

将 Pocket 当作 Inbox，你可以随时将需要的内容收录到 Pocket 中（这很方便），然后在 PC 中如果有需要的时候，可以使用 https://github.com/Kenshin/simpread/discussions/3502 让 Web 端的 Pocket 可以进入阅读模式，然后最终有需要的保存到简悦，以及通过简悦当作「跳板」保存到 Obsidian 。

毕竟不是每个 URL 都需要整理到 Obsidian 端的，同时通过这种方式也非常方便的弥补在手机端剪藏的需求。

***

除此之外，Android 端还有个方案：（未开发，只是**纯粹跟你讨论下，因为你说你的手机重度使用者**。）

可以利用能运行扩展端的浏览器 e.g. Kiwi ，我会出一个插件，在 Kiwi 中进入简悦的阅读模式，然后将正文通过这个插件发送到你的坚果云 simpread_config.json 并包含本地快照。

注意：这个过程只是单向，即 Android  → PC

这样，Android 手机端只用来收集数据，然后在 PC 端可以方便做二次编辑。（如导入到 Obsidian 等）

**Comment by Kenshin** [comment]
App 是会有的，但优先级不是那么高，因为简悦大部分功能（也就是独有功能）都是以 PC 端 Web 版为基准的，如：阅读模式、标注等。

而手机端并不是一个很好的载体。

另外一点：简悦是基于本地系统的稍后读，类似 Obsidian，数据的同步（手机 → PC）是一个「问题」。

所以，最好的方式是：将手机端作为一个补充，而不是主力。

**Comment by Lao-Tz** [comment]
> App 是会有的，但优先级不是那么高，因为简悦大部分功能（也就是独有功能）都是以 PC 端 Web 版为基准的，如：阅读模式、标注等。
> 
> 而手机端并不是一个很好的载体。
> 
> 另外一点：简悦是基于本地系统的稍后读，类似 Obsidian，数据的同步（手机 → PC）是一个「问题」。
> 
> 所以，最好的方式是：将手机端作为一个补充，而不是主力。

我也考虑开始在电脑上使用RSS阅读器去追严肃论文了，您是对的！

**Comment by Kenshin** [comment]
> 我也考虑开始在电脑上使用RSS阅读器去追严肃论文了，您是对的！

👍  

不过，RSS 不是一个最好的载体（或者说是最终方案）：

1. 并不是每个可供阅读的页面都有 RSS（当然也有办法解决）
2. RSS 阅读器本身的「限制」，很难做到将有效信息提取。

所以，最好的做法是：RSS 阅读器（收集） + 简悦的方案，这样各司其职。

**Comment by Lao-Tz** [comment]
> > 我也考虑开始在电脑上使用RSS阅读器去追严肃论文了，您是对的！
> 
> 👍  
> 
> 不过，RSS 不是一个最好的载体（或者说是最终方案）：
> 
> 1. 并不是每个可供阅读的页面都有 RSS（当然也有办法解决）
> 2. RSS 阅读器本身的「限制」，很难做到将有效信息提取。
> 
> 所以，最好的做法是：RSS 阅读器（收集） + 简悦的方案，这样各司其职。

是的，目前正是这么运行的

**Comment by Kenshin** [comment]
Cool~~

给你几个阅读模式使用技巧 https://github.com/Kenshin/simpread/discussions/3340 基本上任何页面都能进入阅读模式。
