### ISSUE TITLE
导入到思源笔记插件：保存信息后依然显示需要授权

### ISSUE THREAD

**Issue by wangjinbaor** [Kenshin/simpread#5683]
### 描述这个错误

如题，保存后依然显示需要授权
![image](https://github.com/Kenshin/simpread/assets/58154171/48017901-3f44-4cb1-8b53-72275fe06039)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/58154171/9fcad79c-db35-4b64-a873-ce0f1d8a1329)
点击保存后点击导出，发现问题。重启浏览器依然出现。

### 操作系统

win10

### 浏览器

Chrome  版本 114.0.5735.134（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/prime/story/car-chip-pipeline-observations-2

**Comment by Kenshin** [comment]
输入 Token 并保存后重启浏览器，看看是否生效？

如果没有生效的话，估计你按照了同步助手，如果是的话，请通过 https://www.yuque.com/kenshin/simpread/fcw60u 来安装这个插件。

**Comment by wangjinbaor** [comment]
谢谢，已经可以了

**Comment by Kenshin** [comment]
okay 解决就好 😄


***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
