### ISSUE TITLE
按照notion blog生成器相关的配置要求进行配置，会导致“导入到 Notion 辅助增强”一直转圈

### ISSUE THREAD

**Issue by Qiup7664** [Kenshin/simpread#5684]
### 描述这个错误

我是用NotionNext部署博客，但是在按照配置文件设置完简悦后，出现“导入到 Notion 辅助增强”一直转圈的问题。我使用了两种模板，一种是简悦模板+添加NotionNext的相关参数模板，另一种是您提供的融合模板。
https://simpreadpublish.notion.site/simpreadpublish/Notion-Blog-429700433c0a490ea0bcdad7f8452d03

### 复现步骤

目前的问题我测试下来是辅助增强导出应该需要使用Name为第一列，而NotionNext需要使用title作为第一列。当我将列表名称改为Name时辅助增强导出能成功跑完，但是使用blog生成器时失败。反之，辅助增强会一直转圈，但是使用blog生成器会成功。

### 操作系统

windows

### 浏览器

chrome

### 发生问题的网址

1

**Comment by Kenshin** [comment]
嗨，我看到你关闭了这个 Issues ？ 是解决了吗？

**Comment by Qiup7664** [comment]
是的，突然可以成功导入了。可能是我哪里没有配置好

**Comment by Qiup7664** [comment]
是的 很感谢 简悦真的太好用了

Kenshin Wang ***@***.***>于2023年6月20日 周二18:08写道：

**Comment by Kenshin** [comment]
哈，谢谢喜欢简悦~  💪 


***


方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
