### ISSUE TITLE
无法导入标注到 Obsidian

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#5685]
### 描述这个错误

1. 无法自动将标注导入到 Obsidian。（手动导入也报错）
<img width="812" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/d15219aa-48b6-411a-b164-289227abca28">

### 复现步骤

1. 进入阅读模式，进行标注；

> 该问题是在某一个网页发现，然后使用 [https://sspai.com/post/69972](https://sspai.com/post/69972) 试验也是同样问题。

### 其他相关说明

1. 至少在 5 月以前是没问题，能成功自动导入。
2. 今天发现无法自动导入到 Obsidian，手动导入也提示失败。
3. 在 Obsidian 的 SimpRead Sync 插件里**使用“Manual Sync”同步成功导入**。
4. 最近安装了`Lightbox Gallery`插件。
<img width="482" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/cc773a05-9a53-4863-a55e-1bd0fd68c153">

### 操作系统

macOS

### 浏览器

Chrome 110.0.5481.177

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
大概率是这个问题 https://github.com/Kenshin/simpread/discussions/5601 造成的。
