### ISSUE TITLE
稍后读无法识别页面并下载

### ISSUE THREAD

**Issue by zxfszane** [Kenshin/simpread#5686]
### 描述这个错误

https://www.eet-china.com/mp/a83916.html   该地址页面加入到 **稍后读** 里边，之后在稍后读里边的 **阅读模式** 无法加载该页面。提示
 <b> 获取页面时出现了一些问题，请稍后再试。
如果是高级账户的话，可以开启内置解析方案，细节请看 [请看这里 ↗](http://ksria.com/simpread/docs/#/Sync?id=%E5%86%85%E7%BD%AE%E8%A7%A3%E6%9E%90) <b>

请支持解析下。

### 复现步骤

1. 将相关页面加入到稍后读
2. 打开稍后读，并选中之前新加入的页面
3. 点击阅读模式

### 操作系统

windows 11

### 浏览器

chrome  113.0.5672.127

### 发生问题的网址

https://www.eet-china.com/mp/a83916.html

**Comment by Kenshin** [comment]
嗨，一般来说如果要完美的在稍后读中查看，最好的方式是使用 **知识库** 方案（即：读取本地快照）。

你可以使用 https://www.yuque.com/kenshin/simpread/wkswh7 这个教程配置下。

PS：前提是需要使用同步助手。
