### ISSUE TITLE
新站适配：xlog.app

### ISSUE THREAD

**Issue by lshcool** [Kenshin/simpread#5689]
### 需要适配的新站

https://imfile.xlog.app/jiao-ma-tang-hui-A-New-Old-Play-2021
https://wuzhi.xlog.app/jian-yi-di-diao-shi-yong-de-shi-yong-xiao-gong-ju

### 有需要请描述这个站的性质

DIYGOD 搞的区块链博客平台 ，建议适配一下，谢谢你。

**Comment by Kenshin** [comment]
okay 这个可以有，我明天确认下。
