### ISSUE TITLE
保存博客园文章到语雀有问题

### ISSUE THREAD

**Issue by ZuulAndRibbon** [Kenshin/simpread#569]
保存时如果是有代码的话，回把代码前面的一键复制的组件也独立保存到语雀，每次都要自己手动删掉

**Comment by Kenshin** [comment]
可以把不需要显示的内容加入到 [排除列表](http://ksria.com/simpread/docs/#/FAQ?id=%e6%8e%92%e9%99%a4%e5%88%97%e8%a1%a8)
