### ISSUE TITLE
对批量html链接进行批量简藏

### ISSUE THREAD

**Issue by Jackson2002** [Kenshin/simpread#5693]
### 请描述你的建议或任何内容

对批量html链接进行批量简藏，求求

**Comment by Kenshin** [comment]
嗨，会考虑的。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/6967473e-b8c8-4eee-ab15-59bb61abc7fb)
为啥老是出现这个
烦死了 什么配置都OK  
这是简悦不稳定吗

**Comment by Kenshin** [comment]
嗨，不要在不同的 issues 讨论相似的问题 😂

> https://github.com/Kenshin/simpread/issues/5693#issuecomment-1605585204

这个问题的提示是：当前 output 下面没有对应的 HTML。（本地快照）

这个跟稳定性无关...

加入稍后读，并且能产生快照的前提：

1. 进入阅读模式
2. 使用快捷键 `d  d`

然后还需要配置相应的环境。

**Comment by Jackson2002** [comment]
我的可以 但是偶尔会失灵 因为我的ob长期住在后台
但是为啥会定期输出不了html呢 
偶尔就出问题
对于我批量剪辑的确实很烦恼

**Comment by Kenshin** [comment]
> 但是为啥会定期输出不了html呢

需要你告诉详细操作步骤。

目前没有用户反馈过这个问题（频繁无法使用）

**Comment by Jackson2002** [comment]
我就是按照aa-dd正确步骤导入ob

**Comment by Jackson2002** [comment]
而且每日回顾也弄不成 之前可以的 后面换了ob就无法使用了

**Comment by Kenshin** [comment]
> 我就是按照aa-dd正确步骤导入ob

使用这个步骤，且配置没有错误的情况下，一定能生成本地快照，所以当出现 404 的问题时，看看我问你的内容

<img width="935" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/149e1659-dd79-43ad-af1f-f26650b661f0">

当没有这个文件时，你可以重新进入原文后使用下图方式手动生成本地快照

<img width="479" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/05302d71-45c6-4aa1-8ca8-4881be2c7855">

最重要的是：**确保你能稳定复现你提到的问题，告诉我你的操作步骤**，这样我才能解决它。

***

另外，假设**极端情况下，有可能出现这个错误**：快速打开多个 URL，然后快速使用 `d d` （比如，同时开了 3 个 Tab，然后马上依次使用 `d d` ）

***

> 而且每日回顾也弄不成 之前可以的 后面换了ob就无法使用了

每日回顾跟 Obsidian 没有关系...

**Comment by Jackson2002** [comment]
假设极端情况下，有可能出现这个错误：快速打开多个 URL，然后快速使用 d d （比如，同时开了 3 个 Tab，然后马上依次使用 d d ）
我就是这样用的  所以才问您有没有一次性导入很多html链接的文章 （cubox的那个功能）
因为在更换了ob 简悦助手的配置被改写 然后就用不了  这个功能好重要 折腾了半个月也没成

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/cfe772ff-64d0-4e78-9471-cae07250363e)
![image](https://github.com/Kenshin/simpread/assets/57218370/5e0b09fd-cb9b-406c-9876-50b7db99af9f)
![image](https://github.com/Kenshin/simpread/assets/57218370/d878ba44-118b-412c-8f20-f902694ac344)

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/e0f288e9-fca0-49d3-ba54-b1ad0cc7377b)
zheg这个东西四个页面在哪里打开 找不到

**Comment by Kenshin** [comment]
> 每日回顾

更改 Obsidian 跟这个功能无关..

把你的 **UID** 和 **接收到每日回顾的邮箱** 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5693

我帮你看下。

> https://github.com/Kenshin/simpread/issues/5693#issuecomment-1605901714

至于这个情况，我没有说一定会出现这个情况，只是极端情况下这么用会有问题。

你可以适度降低操作频率看看能否改善。

简悦不是单纯的剪藏工具，简悦是基于阅读模式的产品，使用简悦的用户大部分是：有阅读诉求和笔记诉求的用户。
否则跟印象笔记有什么区别？但论剪藏来说，没有比印象笔记更适合做剪藏的，你还不如直接使用印象笔记呢，毕竟大厂...

**Comment by Jackson2002** [comment]
哈哈哈确实 咋说呢 剪辑完再阅读
是4个@吗

**Comment by Jackson2002** [comment]
一个@ 
已发送

**Comment by Kenshin** [comment]
> 每日回顾

数据这边看起来没有什么问题，但你使用了 `outlook` 邮箱，我不确定是否是这个引起的，建议都改为 `QQ 邮箱`。

另外留意下：每日回顾需要在每天 19点确保你的坚果云里面的 `simpread_config.json` 是最新的。

> 剪辑完再阅读

如果你仍用于先剪藏再阅读的话，就试着降低些剪藏速度。看看这个问题是否会消失。

**Comment by Jackson2002** [comment]
我早都改用qq了
前几天用了out
今天改为qq了
每日回顾需要在每天 19点确保你的坚果云里面的 simpread_config.json 是最新的。
没理解这句话

**Comment by Kenshin** [comment]
> 今天改为qq了

我目前看到的还是 `outlook`

> 每日回顾需要在每天 19点确保你的坚果云里面的 simpread_config.json 是最新的。

<img width="938" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/729c5e27-fe4f-4ae7-bc84-8c42557657f3">

一般来说：你只要开着坚果云并且配置了自动同步，这个文件自然就是最新的。

这个功能（每日回顾）是每天晚上 19 点 10 会通过简悦后端来检索你的坚果云账户，并查找今天的稍后读，如果有的话，就发送 Email。

**Comment by Jackson2002** [comment]
我之前没有下载坚果云软件也能同步 ？要下载？

**Comment by Kenshin** [comment]
> 我之前没有下载坚果云软件也能同步 ？要下载？

上面的截图写的很清楚了，或者 [看这里](https://simpread.pro/docs/#/%E6%AF%8F%E6%97%A5%E5%9B%9E%E9%A1%BE)。

非要说的话，不用自动同步也行，[手动同步](https://simpread.pro/docs/#/%E6%89%8B%E5%8A%A8%E5%90%8C%E6%AD%A5) 方式，每天 19 点 10 分前手动同步你的数据。

不过，基于上面你的提问，我认为你应该已经设置了同步助手这套，否则你之前提的一切功能其实都没有太大的意义。

***

简单的说，不使用同步助手的话，简悦的功能更偏向于阅读模式（以及轻度剪藏）。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/3e7b4c83-7aa1-4874-8738-ca905aa72dd5)
肯定啊

**Comment by Kenshin** [comment]
把你的发送与接收都改为 QQ 邮箱，我明天再看下。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/81168832-24e0-4343-aa18-98271a7cbbe3)

**Comment by Jackson2002** [comment]
没有后续了吗

**Comment by Kenshin** [comment]
没有任何变化，你确定保存了？

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/509121a8-89fc-493b-8546-36636aab6b2a)
y一直都是这样
不信可以远程

**Comment by Kenshin** [comment]
<img width="680" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d4580e1a-c3c8-471b-9876-47a4eb8adf88">


这里随便改个邮箱，比如 `abcdefg@qq.com` 然后保存，我看看后端是否更新了。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/3bd9bd04-17a9-4806-aceb-eb32814b75d0)
OK

**Comment by Kenshin** [comment]
emmm 可能有点问题，我需要调查下，暂时先别用这个功能。

**Comment by Kenshin** [comment]
在同步助手保存成功后有下面的提示

<img width="302" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4337f75c-0af1-4964-8bfd-d3fc7b328dba">

然后回到选项页 → 服务 → 每日回顾，然后点 **开通**

<img width="1714" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e684c5bf-fa5b-40a2-aec6-af0b5a863085">

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/a18ba566-1a91-4db0-be6e-e50faa63150f)
![image](https://github.com/Kenshin/simpread/assets/57218370/b2694903-0bd7-4145-8715-bb90bb1fdfb6)

**Comment by Kenshin** [comment]
okay 可以了，可以改为正确的邮箱了。

**Comment by Jackson2002** [comment]
![image](https://github.com/Kenshin/simpread/assets/57218370/15b8558b-f6ae-4513-8918-634fa9f19919)
k可以了不知道今晚有没有推送
我还要再开今日回顾吗一次

**Comment by Kenshin** [comment]
> 我还要再开今日回顾吗一次

其实是不用的，除非你觉得有必要，确定 QQ 邮箱和密码无误的情况下，按照 https://github.com/Kenshin/simpread/issues/5693#issuecomment-1608820847 第二图再提交下。

**Comment by Jackson2002** [comment]
没用 昨天 咋办
