### ISSUE TITLE
剪藏文章到Ob时，提示同步助手运行时发生了错误

### ISSUE THREAD

**Issue by iFryRice** [Kenshin/simpread#5694]
### 描述这个错误

在用Obsidian插件剪藏文章到ob时，提示保存成功，但是同步助手出现了如下的提示：
![image](https://github.com/Kenshin/simpread/assets/102138235/460d26c6-3fdf-4dbb-aeec-7d1c871f9c7a)

![image](https://github.com/Kenshin/simpread/assets/102138235/83a16909-1006-43a2-8901-1eae506ff0ac)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/102138235/0b1be277-47e0-4d2f-8e2e-b73fd23d6f03)
之前运行没有问题，有对插件做如下修改：
1. “md+set”方式设置了目录，但是取消目录的设置后，仍然存在当前问题；
2. “http://localhost:7026/reading/71#id=1687504625674” ob中剪藏的文章的批注跳转链接打不开，发现是“7026”（先前插件中设置的端口号为7027，将插件中的端口号进行修改，后重启电脑；

不知是否是上述两种操作引起了插件的不起作用，但是手动恢复插件的设置后，仍然不起作用。

### 其他相关说明

如果方便，还想知道我应该如何打开“http://localhost:7026/reading/71#id=1687504625674”这个链接中的文章...有下载了示例库，示例库中可以正常运作。

### 操作系统

Win11

### 浏览器

Microsoft Edge 版本 114.0.1823.58 (正式版本) (64 位)

### 发生问题的网址

https://sspai.com/post/80505

**Comment by Kenshin** [comment]
> “md+set”方式设置了目录，但是取消目录的设置后，仍然存在当前问题；

有，你是怎么设置的目录？提示错误应该就是目录设置错了

> “[http://localhost:7026/reading/71#id=1687504625674”](http://localhost:7026/reading/71#id=1687504625674%E2%80%9D) ob中剪藏的文章的批注跳转链接打不开，发现是“7026”（先前插件中设置的端口号为7027，将插件中的端口号进行修改，后重启电脑；

默认不需要修改端口，插件中的端口指的是 Obsidian Sync 端口

**Comment by iFryRice** [comment]
> 默认不需要修改端口，插件中的端口指的是 Obsidian Sync 端口
我现在把所有的端口都修改为7026，在导出全文到ob的插件中 选择了以”md+assets“方式导出，现在可以导出全文到ob，但是在导出标注的时候，提示保存失败；同时，在导出全文到ob成功后，没有了”在obsidian打开“字样。

**Comment by Kenshin** [comment]
> 我现在把所有的端口都修改为7026，在导出全文到ob的插件中 选择了以”md+assets“方式导出，现在可以导出全文到ob，但是在导出标注的时候，提示保存失败；同时，在导出全文到ob成功后，没有了”在obsidian打开“字样。

有点问题... 因为导入到 Obsidian 有很多方案，所以我需要你把相关的改动都截图给我。

**Comment by iFryRice** [comment]
- 导入到Obsidian设置：
![image](https://github.com/Kenshin/simpread/assets/102138235/204f5952-c2bd-45df-b43e-b58a7192c754)
- Markdown增强：
![image](https://github.com/Kenshin/simpread/assets/102138235/adb7e597-be1a-4ea7-8e6d-c45e8ee63635)
- Ob插件：
![image](https://github.com/Kenshin/simpread/assets/102138235/4bb0e35a-ad19-4a4d-ac5c-cd5e5dacb469)

您看还需要哪些配置吗，起初只是想搞清楚..."http://localhost:7026/reading/74#id=1687512990110"这个跳转链接在Ob为什么打不开来着...

**Comment by Kenshin** [comment]
<img width="755" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3b4add54-5b50-4a96-adc3-fc4f8051b668">

这个应该是 `7027`

<img width="746" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9394c55b-ddf2-4121-a755-bf23dba8381d">

这个看起来没问题，但如果还是不好使的话，暂时先关闭这个功能，确保能导入。

**Comment by Kenshin** [comment]
> 起初只是想搞清楚..."http://localhost:7026/reading/74#id=1687512990110" 这个跳转链接在Ob为什么打不开来着...

1. 看下 http://localhost:7026/reading/74 能否打开？
2. 你的 output 文件夹是否有 `74-xxxx.html` 这个文件。

**Comment by iFryRice** [comment]
> 这个应该是 7027

这个端口设置和 拓展配置页 以及简悦同步助手那个端口不一样嘛？

**Comment by Kenshin** [comment]
> 这个端口设置和 拓展配置页 以及简悦同步助手那个端口不一样嘛？

7027 是 Obsidian Sync 插件的端口 😂

**Comment by iFryRice** [comment]
> > 起初只是想搞清楚..."http://localhost:7026/reading/74#id=1687512990110" 这个跳转链接在Ob为什么打不开来着...
> 
> 1. 看下 http://localhost:7026/reading/74 能否打开？
> 2. 你的 output 文件夹是否有 `74-xxxx.html` 这个文件。

1. 这个网址打不开；
2. output文件夹中有和Ob同名的md文件，没有html的；这个是需要html文件嘛

**Comment by iFryRice** [comment]
> 

就是这个插件配置页应该是 7027  
![image](https://github.com/Kenshin/simpread/assets/102138235/dafb3f35-7387-43f8-a0ba-90b25580ab31)

我ob的插件 那个端口是 7026诶...
![image](https://github.com/Kenshin/simpread/assets/102138235/d03e8d40-4e21-448a-890b-feb9ce341a1f)

是这样吗...emmm，有点不太懂这些但是还想搞清楚...

**Comment by Kenshin** [comment]
`7026` → 同步助手的端口号

`7027` → Obsidian Unread Sync 端口号

这两个端口号目前来说，`7026` 暂时不要修改，`7027` 可改为除 `7026` 以外的任意端口号，也就是下图所示

<img width="817" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2cb847d6-53ba-4f10-95f3-87490ff4463f">

端口号具有唯一性，因为同步助手的不能改动，所以 Obsidian Unread Sync 就只能是 `7026` 以外的任何值。

**Comment by iFryRice** [comment]
好的，收到，以上设置修改以后，在以“md+assets”方式导出时，标注还是未能正确导出，同时，导入到ob的标题仅为文章的标题，未带有设置好的{{now}}字段。

**Comment by Kenshin** [comment]
> 在以“md+assets”方式导出时，标注还是未能正确导出

这种方式适用于导出全文，而非标注。

> 导入到ob的标题仅为文章的标题，未带有设置好的{{now}}字段。

emmm... 这么说的话，你的配置就不只是之前说的修改了一两个地方 😂 建议跟 https://www.yuque.com/kenshin/simpread/fr8zo5 对比下你的配置。（仔细点对比 😄

**Comment by iFryRice** [comment]
好的谢谢，问题都解决了...打扰大佬了...下次我先再仔细翻翻文档....Sry

**Comment by Kenshin** [comment]
哈，解决就好~  👍 

PS：老用户了，小事情。😄

**Comment by iFryRice** [comment]
您好...还想请问一个问题，我在ob中两边的标注没有实现像是介绍中的那样双向同步...相关的设置应该都是保持一致的
[自动导入标注到 Obsidian（不使用同步助手方案，轻量级方案）](https://www.yuque.com/kenshin/simpread/ifioux#GqVM4 )  

![image](https://github.com/Kenshin/simpread/assets/102138235/38254896-d6b2-48bc-a4ba-db3353564c6d)

**Comment by Kenshin** [comment]
轻量级方案肯定不是双向的... 😂 说明里面写的很清楚了

<img width="921" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f2fde4c0-e526-4691-bcb7-1e3398f34c28">

你的截图对应的功能也不应该是轻量级方案，看我刚才给你的那个链接，否则不按照我说的方案，你会越绕越乱的 😂

**Comment by iFryRice** [comment]
已经按照您上面发我的链接都配置好了，然后出现的问题是在右栏打开的快照中标注之后，没有实现标注同步到ob的这个功能😭

**Comment by Kenshin** [comment]
> 然后出现的问题是在右栏打开的快照中标注之后，没有实现标注同步到ob的这个功能

在 Obsidian 右侧标注的话，应该会有相应的 `xxx-xxxx@annote.md` 生成

1. 看看这个文件是否有更新（或生成）
2. 如果有的话，这个文件是否在对应的 Obsidian 目录中

留意 Obsidian SimpRead Sync 的路径设置

<img width="784" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/95bfd0e8-6c7d-4464-b046-befd65e417c7">

另外，在网页标注时，能否正常更新（同步）到 Obsidian ？

**Comment by iFryRice** [comment]
在网页标注时，可以正常更新；在Ob右侧标注时，貌似没有新的 `xxx@annote.md` 生成。

插件的路径设置没有问题。

另外，在同步助手中，也有做如下设置：
![image](https://github.com/Kenshin/simpread/assets/102138235/6a133a9e-dd9c-4863-a861-c2db49909ba9)

**Comment by Kenshin** [comment]
> 在网页标注时

应该会产生 `xxx@annote.md` 文件，是吧？

> 在Ob右侧标注时，貌似没有新的 xxx@annote.md 生成。

那就应该只是 Obsidian 端文件夹设置有问题

<img width="1410" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e5f81365-5097-44ad-b34d-41ffc3d00750">

按照你的截图来说，应该是下面这个路径地址

<img width="662" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c88eb18a-4cf6-41d2-9788-462b021a04ec">

**Comment by iFryRice** [comment]
okok，发现问题出在哪里了，两边标题不一样...
谢谢大佬！！！
![image](https://github.com/Kenshin/simpread/assets/102138235/0a13f172-43e0-443a-ae50-71041faa97b5)

**Comment by Kenshin** [comment]
第一个截图的日期不对，我之前给过你教程，对比下就好了~

**Comment by iFryRice** [comment]
好的~可以建议一下Ob的插件 Obsidian SimpRead Sync 中能够支持 对 {{create}}{{now}} 类似的字段进行自定义吗，如果这个需求大、也好做的话emmm 

![image](https://github.com/Kenshin/simpread/assets/102138235/520172cd-c8a3-449e-a1cb-18061fafa8cc)

**Comment by Kenshin** [comment]
> ![image](https://user-images.githubusercontent.com/102138235/248543455-520172cd-c8a3-449e-a1cb-18061fafa8cc.png)

这个图是哪里的？把链接告诉我。

另外截图上就已经明确说明了，暂时去掉了 `now` 之类的，因为有点麻烦 😂

或者说你需要使用定制 `now` 之类的做什么？

**Comment by iFryRice** [comment]
链接：[Obsidian SimpRead Sync - 一站式标注及管理解决方案 · Kenshin/simpread · Discussion #2889](https://github.com/Kenshin/simpread/discussions/2889#discussioncomment-2831868 )  

- 主要是个人习惯，比较习惯以 yyyymmdd 开头命名文件，另外，在上述设置中，因为 {{timestamp}} 字段基于当前的时间（yyyymmddHHMMss 时间戳到秒），在ob中进行批注时，每一条批注都会产生新的md文件，而不会是对原有的md文件进行覆盖。
- 如果这个时间戳可以改成到 yyyymmdd 就好啦 狗头）

**Comment by Kenshin** [comment]
你是说保存到本地的 `.md` 的文件名吗？文件名暂时不支持定制（因为跟很多功能都绑定了）

如果是内部链接方案的话，应该可以 `alias` 的方式在内部使用，类似下图的效果

<img width="1451" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5a21cf4a-5b87-4421-a371-58fd305502e8">

**Comment by iFryRice** [comment]
> 你是说保存到本地的 .md 的文件名吗？

嗯对
> 如果是内部链接方案的话，应该可以 alias 的方式在内部使用，类似下图的效果

好滴好滴，感谢🌟🌟

**Comment by Kenshin** [comment]
那就只能等下个版本考虑实现了，之前是因为这里有点麻烦，再加上本地文件名定制的空间不大，所以就按照目前的方式设置了。
