### ISSUE TITLE
关于阅读助手的建议

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5695]
请增加自定义api地址功能

_Originally posted by @liujuntao123 in https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6271605_

**Comment by Kenshin** [comment]
@liujuntao123 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

会考虑你的建议，但目前来说优先级不高。简悦的阅读助手只所以能完美的理解正文，后端做了很多事情，不仅仅只是单纯调用 API 的事情。

**Comment by liujuntao123** [comment]
嗯，我明白你的意思。不过open ai的包应该是支持自定义api url的，可以了解一下。辛苦开发，respect！

**Comment by Kenshin** [comment]
okay 但无论如何需要再加「一层」通信，可能响应速度会有些影响。

**Comment by Kenshin** [comment]
嗨，我在这里调研下 **使用自定义 API 的意义**，看到后请在 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1621070991 回复讨论

**Comment by Kenshin** [comment]
![OpenAI@cover v2](https://github.com/Kenshin/simpread/assets/81074/03673e06-13fd-4752-b6e7-34cfcc460feb)

嗨，[阅读助手 3.1.0](https://github.com/Kenshin/simpread/discussions/5158) 发布了

## 新功能

- `Add` [自定义第三方 API 服务](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6361313)

    ![image](https://github.com/Kenshin/simpread/assets/81074/a4eb995e-0a29-4767-962f-92d498899d1f)

- `Add` [支持 GPT-4](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5175855)

    ![image](https://github.com/Kenshin/simpread/assets/81074/30440609-23d2-4767-8411-2c31d8dba999)

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/Mv55R9uIOF) 安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

有任何疑问请前往 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1624903383 讨论，我关闭这个 issues 了~
