### ISSUE TITLE
简悦保存网页到为知笔记后字体会变小

### ISSUE THREAD

**Issue by yxkongfu** [Kenshin/simpread#5697]
### 描述这个错误

通过简约的保存到为知笔记的动作，把网页保存到为知笔记，网页的字体会变得很小，严重影响阅读体验。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/91581312/3d8aa712-b703-4731-a1c3-d35e9554487b)
左边为原网页，右边为保存到为知笔记后的网页

### 操作系统

win7、win10

### 浏览器

edge

### 发生问题的网址

https://www.zhihu.com/question/606044969

**Comment by Kenshin** [comment]
emmm 

1. 没觉得右侧有什么问题… 😂
2. 右侧字体应该定制过，不知道是否是这个问题造成的？
3. 只有一个页面有问题？还是每个？

目前也没有其他用户报告过类似问题。

**Comment by Kenshin** [comment]
也可以试试：更换简悦的主题。
