### ISSUE TITLE
代码高亮问题集中反馈渠道

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#570]
> 由于简悦使用了新版的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)，所以会对版面布局【按照适合中文排版的方式】进行重构。
> 
> 与此同时，也一并加入了一个 [代码高亮插件](https://github.com/Kenshin/simpread/issues/500) 来美化代码段。
> 
> 但由于代码段的高亮规则太多，所以这个插件只能满足常见的代码高亮方案，因此一旦出现未适配的情况，**会将代码显示为一行**。

这个 issues 会集中反馈这些相关性的问题，如讨论其它问题，请重开 [issues ](https://github.com/Kenshin/simpread/issues/new)

**Comment by Kenshin** [comment]
https://mp.weixin.qq.com/s/5T2XgRv_VaM65sUVVh9Qvw

**Comment by 1024th** [comment]
希望加入自定义代码高亮CSS的功能

**Comment by geekerzhou** [comment]
![image](https://user-images.githubusercontent.com/5682822/68025504-e324de80-fce7-11e9-9756-b02d00c82efd.png)
csdn 代码行号和代码分开展示了

**Comment by Kenshin** [comment]
@geekerzhou
谢谢反馈，修复后会集中通知到大家~

**Comment by Kenshin** [comment]
@geekerzhou

***

嗨，这几天准备集中修复 代码高亮 的问题。

不过，很奇怪的是，我测试了几个 CSDN 的页面均未发生问题，请问能否告知具体的 URL 

***

另外，请确保安装 [代码高亮插件](https://github.com/Kenshin/simpread/issues/500)

**Comment by geekerzhou** [comment]
安装完插件好使了
Kenshin Wang <notifications@github.com> 于2019年11月28日周四 上午11:02写道：

**Comment by AriaLyy** [comment]
csdn 底部总是显示一些图标
https://blog.csdn.net/jsqfengbao/article/details/52103439
![image](https://user-images.githubusercontent.com/10437293/71321883-30107e80-24fb-11ea-8e23-c8babb5b582e.png)

**Comment by Kenshin** [comment]
@AriaLyy 

你可以用 `隐藏列表` 实现，如下图

![image](https://user-images.githubusercontent.com/81074/71330902-6b966180-256a-11ea-820f-a35b7691823d.png)

***

另外，你看完后，请自行删除这条 issues ，有问题的话，请重新开启。（ 这个 thread 只是讨论 高亮问题的 issues
