### ISSUE TITLE
SingleFile导出的HTML文件，简悦打开后，标注模式消失了

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5701]
### 描述这个错误

SingleFile下载的HTML文件，用简悦打开后，标注模式消失了，选择内容后，有时也可以添加标注，有时又不可以
![vivaldi_sMeV1WyriU](https://github.com/Kenshin/simpread/assets/22015183/35a032c6-46c2-4ffb-a422-3f7b40a39b4c)

当退出简悦后，在当前页面，会出现标注模式
![image](https://github.com/Kenshin/simpread/assets/22015183/5b319cbf-0655-4c9b-9c9a-cc1d8d7e1bb3)

### 复现步骤

尝试了多个浏览器，重启浏览器，隐私模式，都是一样的

### 操作系统

Windows11

### 浏览器

谷歌浏览器

### 发生问题的网址

任何SingleFile下载的文件

**Comment by liuyuqiangchn** [comment]
另外，问一下，简悦上一次更新是2021年，是否有计划更新呢，感觉有一些小bug没有修复，比如，进入阅读模式速度没有那么迅速，

**Comment by Kenshin** [comment]
嗨

> 简悦上一次更新的时间

更正一下：这个时间仅仅只是主程序而已，但插件、同步助手这些，每个一段时间就会更新，如果想了解这些功能的话，建议订阅 https://simpread.pro/subscribe 或者关注简悦的 [知乎专栏](https://www.zhihu.com/column/kenshin)

所以不要以简悦的主程序为参考标准  😂

比如简悦目前最新的阅读助手（基于 OpenAI），近期更新了 10 个版本...

> SingleFile下载的HTML文件，用简悦打开后，标注模式消失了，选择内容后，有时也可以添加标注，有时又不可以

这个需求可以通过同步助手的 [外部文件](https://simpread.pro/docs/#/%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6) 实现，而这个功能就是新功能。

> 进入阅读模式速度没有那么迅速，

没有其他人反馈过类似的情况，如果你觉得有问题的话，建议 [新开一个 issues](https://github.com/kenshin/simpread/issues/new) （如有必要的画）详细说明~

**Comment by liuyuqiangchn** [comment]
好的，感谢答复，也就是说，对于通过SingleFile下载的HTML文件，目前来看，通过同步助手的外部文件来访问，这种效果是最好的是吗

**Comment by Kenshin** [comment]
> 好的，感谢答复，也就是说，对于通过SingleFile下载的HTML文件，目前来看，通过同步助手的外部文件来访问，这种效果是最好的是吗

是的~

准确的说：无论什么方式，只要是在本地的 HTML 或 Markdown 如果想标注的话，外部文件功能是最好的方案（这个功能就是为做这个事情而开发的。

**Comment by Kenshin** [comment]
补充下：如果不需要标注的话，简悦本身就支持读取本地 HTML  或 Markdown 并渲染为阅读模式。

**Comment by liuyuqiangchn** [comment]
我刚才试了一下外部文件，为什么直接打开HTML文件，生成的阅读模式有图片显示，而外部文件生成的阅读模式，图片都不显示了呢
![image](https://github.com/Kenshin/simpread/assets/22015183/77028dbd-4813-4438-9ec5-4ca99036e48a)

**Comment by Kenshin** [comment]
这个问题是因为公众号的图片有防盗链功能，所以才这样。

不过，一般使用 SingleFile 都是将图片本地化的，你没有这么做？

**Comment by liuyuqiangchn** [comment]
都本地化了，这是文件，
[1234567.zip](https://github.com/Kenshin/simpread/files/11864292/1234567.zip)

**Comment by Kenshin** [comment]
我知道是什么「问题」了 ...

可能是你开了 SingleFile 某个选项导致在进入阅读模式后，又给「渲染」回原链接了 😂

PS：我好久不用 SingleFile 但隐约记得有这个选项...

**Comment by liuyuqiangchn** [comment]
我刚才测试了一下，对于SingleFile下载的HTML文件，不管是直接打开，还是同步助手外部文件打开，进入阅读模式后，都会把图片src的base64删除

我也测试了很多的SingleFile选项，都不行

**Comment by Kenshin** [comment]
emmm

我研究了下 SingleFile 确实有点问题，我想想办法，目前暂时没有太好的办法。（但 wx 公众号以外的 HTML 一般都不受影响。

**Comment by Kenshin** [comment]
嗨，[外部访问辅助增强](https://github.com/Kenshin/simpread/discussions/5895) 插件发布了，主要解决了你提到的问题。

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/MAheFOdBhK) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5896

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~
