### ISSUE TITLE
简悦配置选项页无法打开

### ISSUE THREAD

**Issue by laybxc** [Kenshin/simpread#5702]
### 描述这个错误

如题

### 复现步骤

简悦能使用，但是无法通过各种方法打开配置选项页面

### 操作系统

Windows10

### 浏览器

chrome最新版

### 发生问题的网址

zhihu.com

**Comment by Kenshin** [comment]
嗨，一般来说都是使用了同步助手才会造成这个问题，你可以试试 http://localhost:7026/database/fixed 提到的修复方案。

**Comment by laybxc** [comment]
修复时：权限验证错误，如何解决呢

**Comment by Kenshin** [comment]
你的同步助手没有验证？

**Comment by laybxc** [comment]
验证了，上面有账户的相关信息

**Comment by Kenshin** [comment]
emmm

如果你的反馈信息和操作无误的话，大概率是你的配置文件里面的 UID 不是高级账户...

你能用文本编辑器打开 `simpread_config.json` 这个文件吗？然后找到 UID 看看对应的字段跟你的同步助手是否是一个？

**Comment by laybxc** [comment]
是同一个，并且我在很早之前曾经开通了高级账户。我找到了两个`simpread_config.json`文件，其中一个全是"xxxx"，应该是有误的版本，另一个相对正常

**Comment by Kenshin** [comment]
> 其中一个全是"xxxx"，应该是有误的版本，另一个相对正常

这个是 Demo UID 😂 如果你用的这个当然不好使了。

如果 `xxxx` 这个是新的，你可以将 UID 替换为正确的，然后修复。

**Comment by laybxc** [comment]
目前同步助手上的UID就是正确的，而不是“xxxx”

**Comment by Kenshin** [comment]
同步助手与 `simpread_config.json` 里面的 UID 需要是一样的，且不能是 `xxx` 才是正常的。

**Comment by laybxc** [comment]
目前同步助手里的UID与 simpread_config.json 里面的 UID 已经是一样的了，发现关闭同步助手后能打开选项页，打开同步助手则无法打开选项页

**Comment by laybxc** [comment]
> 修复时：权限验证错误，如何解决呢

使用该解决方案，还是这样的问题

**Comment by Kenshin** [comment]
😂 ...

把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5702

我帮你看下 UID

**Comment by laybxc** [comment]
是否收到邮件？

**Comment by Kenshin** [comment]
收到了，稍晚确认完回复你。
