### ISSUE TITLE
请问简约支持不进入阅读模式，直接将页面导出到notion之类的吗？

### ISSUE THREAD

**Issue by SinZhangQ** [Kenshin/simpread#5705]
### 请描述你的建议或任何内容

因为进入阅读模式之后，有些页面会比较奇怪，比如知乎会自动隐藏评论之类的，请问可以类似于印象笔记，直接将当前的整个页面直接保存到notion吗？

**Comment by Kenshin** [comment]
嗨，简悦的一切功能都以阅读模式为基准。只有阅读诉求的前提才使用简悦的功能（如：剪藏、标注、稍后读等）。
