### ISSUE TITLE
自动化异常：如何导出markdown？

### ISSUE THREAD

**Issue by woshishui10000** [Kenshin/simpread#5707]
### 描述这个错误

已按照教程设置导出到Logseq，但是最近突然就不行了。只能导出html，但是不能导入到Logseq。原因未知。

### 复现步骤

进入沉浸式阅读模式后，标注和稍后读都无法导出md。

### 操作系统

win11

### 浏览器

Chrome 114.0.5735.134

### 发生问题的网址

http://www.sciencenet.cn/

**Comment by woshishui10000** [comment]
![image](https://github.com/Kenshin/simpread/assets/106961264/1606ffc2-5104-4995-9097-1334717c3b92)

**Comment by woshishui10000** [comment]
<%
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
    color  = colors[ annote.color ];
%>
## [📌](<{{an_int_uri}}>) Highlights {{an_tags}}
> <%- (annote.type == 'img')? "[img]" + "(" + annote.text + ")" : '[:p {:style "background-color:' + color + '"} ' + '"' + annote.text + '"]' %>
<% if (annote.note) { %>
>> {{an_note}}
<% } %>
### reference
<%- (annote.refs)? "> refs: " + annote.refs : "" %>

> backlinks: {{href}}

**Comment by Kenshin** [comment]
> 已按照教程设置导出到Logseq

1. 导入到 Logseq 有很多方案，你说的哪种？给出链接。
2. 最近突然不好使了，在不好使之前有多久没用了？还是一直在使用？（简单的说，上次好使的时候是什么时候？）
3. 你的截图给给出的模板没有任何关系 😂

所以，最好先明确是哪种导入方式（教程）。
