### ISSUE TITLE
导入到notion报「请稍后再试」错误

### ISSUE THREAD

**Issue by galaxyhao** [Kenshin/simpread#5708]
### 描述这个错误

使用notion基础版配置库，同步到notion时，图片可以上传成功，但是最终提示「请稍后再试」。控制台查看是调用这个接口_https://www.notion.so/api/v3/submitTransaction_ 报400错误。

### 复现步骤

必现问题

<img width="1772" alt="image" src="https://github.com/Kenshin/simpread/assets/20677353/f5c9767b-0e7a-4ddd-81d5-f50d8aa65fd0">

### 其他相关说明
控制台信息

<img width="1546" alt="image" src="https://github.com/Kenshin/simpread/assets/20677353/e75eb648-260d-4464-a09d-b78cfcc3bbd8">

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

https://sspai.com/post/78705

**Comment by Kenshin** [comment]
你是开启了 Notion 图床吗？

<img width="508" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3e2514bf-06f4-4969-91ba-9267e9a2b3a3">

我测试了下是没问题的，你可以先把这个功能关闭，确保可以正常导入 Notion（来验证你的配置无误）。

**Comment by galaxyhao** [comment]
> 你是开启了 Notion 图床吗？
> 
> <img alt="image" width="508" src="https://user-images.githubusercontent.com/81074/249380839-3e2514bf-06f4-4969-91ba-9267e9a2b3a3.png">
> 我测试了下是没问题的，你可以先把这个功能关闭，确保可以正常导入 Notion（来验证你的配置无误）。
> 
> PS：这个功能肯定没问题，否则 Issues 会炸 😂

好像知道原因了，我一直点的是动作里的「一键导入全文到Notion」，点击「保存到Notion」就可以了，这两者有什么区别呀？
<img width="602" alt="image" src="https://github.com/Kenshin/simpread/assets/20677353/42673480-53b6-4036-a159-6871c11ce314">

**Comment by Kenshin** [comment]
简悦导入到 Notion 有两个方案，即：

1. 扩展端 → （选项页 → 服务 → 导入到 Notion）
2. 插件端

它们的区别可以看 https://github.com/Kenshin/simpread/discussions/4954 

所以，你需要明确你使用了哪种导入方案？
