### ISSUE TITLE
谢谢您的努力，回馈一些问题

### ISSUE THREAD

**Issue by GreenEric** [Kenshin/simpread#571]
转换成集中阅读时，有些字体的尺寸没有跟着转换过来，谨供参考

[R-blogger](https://www.r-bloggers.com/disk-frame-is-epic/)

![image](https://user-images.githubusercontent.com/24875340/64365659-37447700-d047-11e9-813b-4e34bb83eaf8.png)

**Comment by Kenshin** [comment]
谢谢反馈。
这种情况是由主题决定的，并不是你说的问题。
比如，我目前在使用的主题，是这样效果的

![image](https://user-images.githubusercontent.com/81074/64395410-c2942b80-d08c-11e9-829d-92e1d86b026f.png)

***

你说的这三处分别是： 正文、代码段以及代码块，所以自然在主题中会有不一样大小的情况。

如果你觉得需要统一的话，可以使用 [自定义样式](http://ksria.com/simpread/docs/#/自定义样式) 通过 CSS 来调校这些细节。

**Comment by GreenEric** [comment]
谢谢您，非常感谢，阅读非常愉快

**Comment by Kenshin** [comment]
周末愉快~  😄
