### ISSUE TITLE
通过手机收藏的网页,无法触发自动化导出功能?

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5711]
通过手机收藏的网页,无法触发自动化导出功能?有没有其他方式进行备份,因为之前出现过一次配置异常,恢复之后,之前的稍后读记录被删了的情况

_Originally posted by @pishizuiqiang in https://github.com/Kenshin/simpread/discussions/2921#discussioncomment-6310343_

**Comment by Kenshin** [comment]
@pishizuiqiang 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

通过手机收藏网页时，无法触发自动化。所以你应该是记错了。

**Comment by pishizuiqiang** [comment]
通过手机收藏网页之后,我收藏的内容有办法通过其他方式备份吗?

**Comment by Kenshin** [comment]
> 通过手机收藏网页之后,我收藏的内容有办法通过其他方式备份吗?

最简单的方式：进入到 PC 端，手动导出一个（如 HTML、Notion 等）
