### ISSUE TITLE
鼠标在阅读区域内和鼠标在阅读区域外，页面排版不一样

### ISSUE THREAD

**Issue by zzc1110** [Kenshin/simpread#5714]
### 描述这个错误

鼠标在阅读区域内和鼠标在阅读区域外，页面排版不一样，见下面两个图
![sp20230629_161534_655](https://github.com/Kenshin/simpread/assets/17234916/b0f74d4a-d464-4842-b873-9efe8341f748)
![sp20230629_161613_528](https://github.com/Kenshin/simpread/assets/17234916/11ddad10-ac13-4be7-9996-5bec259e84c3)

### 复现步骤

鼠标在阅读区域内外切换就可以复现

### 操作系统

macOs

### 浏览器

chrome 114.0.5735.198

### 发生问题的网址

https://mp.weixin.qq.com/s/QuIttshN59yxT94Ycq4f0A

**Comment by Kenshin** [comment]
嗨，谢谢反馈，以及精细截图与说明。  👍 

我看你截图时的阅读模式区域很小... 在较小区域下确实存在你说的情况。

不知道你是否使用了同步助手以及配置了知识库方案，如果是的话，可以试试 [稍后读 · 极速版](https://github.com/Kenshin/simpread/discussions/3864) 可能会解决你的问题。

**Comment by zzc1110** [comment]
在mac上卸载并重新安装了简悦插件，还是同样的问题。在另一台win机器上没有复现。

**Comment by Kenshin** [comment]
你截图的内容与提供的 URL 似乎不是一个，所以我没法测试。

另外，如果使用简悦的话，最好的做法是我刚才提到的：同步助手 + 本地快照的方式，虽然跟你提到的问题无关，但只要这么做才能让简悦发挥最大的作用。

作为新用户的话，可以直接使用 https://www.yuque.com/kenshin/simpread/ds8zk0 提供的配置包方案。

**Comment by zzc1110** [comment]
不好意思，截图里的文章地址是这个：https://mp.weixin.qq.com/s/vLOViGeCgNHZ79b0FOesWA
我去试一下这个方案：同步助手 + 本地快照，谢谢。

**Comment by Kenshin** [comment]
嗨，我测试了下正确的 URL 还是没有遇到，建议不纠结这个问题了 😂 

可以试试本地快照的方案。
