### ISSUE TITLE
微信公众号文章无法进入阅读模式

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#5715]
### 描述这个错误

不清楚这类文章是怎么把图片变成循环展示的，反正快捷键aa，右键进入阅读模式，都没法成功。

### 复现步骤

1. aa或右键无法进入阅读模式

### 操作系统

macos

### 浏览器

114.0.1823.51 (正式版本) (arm64)

### 发生问题的网址

https://mp.weixin.qq.com/s/unMMjJjQeI2xHqdKckpN2w

**Comment by Kenshin** [comment]
okay 明天确认下。

**Comment by Kenshin** [comment]
哈，这是个啥公众号？ 😂

这种页面当然没法进入并使用阅读模式了。

我先关闭这个 issues 如果这种类型属于正常的公众号范畴，我可以考虑适配它~

**Comment by HopeLHP** [comment]
如何定义正常的公众号？这个就是微信公众号作者发出来的文章，只是文章文字内容短了，图片多了点，图片展示方式不同了点

**Comment by Kenshin** [comment]
> 如何定义正常的公众号？

一般来说正常的公众号类似 https://mp.weixin.qq.com/s/nbO0kyZ5O-oqwLYXIA6b2w 而你给的公众号完全不一样。

完全不一样的意思是：**它里面的结构跟其它公众号不一样**。

所以这类公众号我没法适配。

PS：我很少看公众号，所以并不清楚你提供的 URL 是否有共性，否则可以忽略。

**Comment by HopeLHP** [comment]
<img width="1528" alt="image" src="https://github.com/Kenshin/simpread/assets/70339118/e8181051-5681-46d8-b8f3-131047f34acc">
这个是公众号的消息类型，一种是图文消息，还有图片消息，我们这个链接一般就是图片消息，简悦针对图文消息识别得不错，但是图片消息没法识别。

**Comment by Kenshin** [comment]
emmm 原来如此...

阅读模式本来就是为图文而实现的，如果只是图片的话，效果比较差些。

**Comment by HopeLHP** [comment]
<img width="821" alt="image" src="https://github.com/Kenshin/simpread/assets/70339118/858f1bd7-f283-4c1f-9dbf-c0907f2d6d74">
图片消息的结构就是专门的图片栏+标题+1000字以内的描述文字。
针对大量图片（比如pdf或ppt拆成图片发出），有些作者可能直接把大量图片放在正文采用图文消息混排的方式发出（观感可能不太好）；有些作者就采用图片消息，我觉得这才是对图片消息比较好的阅读方式。
大量图片的消息，像这种财税公众号还挺爱发的，只是很多作者还是采用老的办法，正文放置图片。

**Comment by Kenshin** [comment]
okay 原来如此...

我再留意下这种方式，如有需要的话，可以考虑适配它。
