### ISSUE TITLE
我对“导入全文到Obsidian”生成的笔记文件有疑问

### ISSUE THREAD

**Issue by see2it** [Kenshin/simpread#5716]
### 描述这个错误

我发现导入全文到Obsidian生成的批注文件，笔记最上方都有一段
Comments

TABLE 
    WITHOUT ID
    link(Source, dateformat(date(Source), "yyyy-MM-dd")) as Date___, 
    regexreplace(rows.Comments,"^@@\[\[.+?\]\]\s","") as "Comments"
FROM "journals"
WHERE  contains(cmnt, this.file.name)
FLATTEN cmnt as Comments
WHERE contains(Comments, this.file.name)
GROUP BY file.link as Source
SORT rows.file.day desc

不知道是不是有问题？

### 复现步骤

1.做批注
2.导入全文到Obsidian，笔记的文件名设定是默认值 {{id}}-{{title}}{{mode}}
3.在Obsidian中的批注文档查看，每一篇annote都这样。

### 操作系统

Windows 7

### 浏览器

360极速浏览器

### 发生问题的网址

任意网页

**Comment by Kenshin** [comment]
1. 你提到的这段内容跟你模板有关系...
2. 你可以在预览模式下查看
3. 你可以通过 [修改 Markdown 模板](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600) 来更换或定制你的模板

**Comment by see2it** [comment]
> 1. 你提到的这段内容跟你模板有关系...
> 2. 你可以在预览模式下查看
> 3. 你可以通过 [修改 Markdown 模板](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2635600) 来更换或定制你的模板

原来如此，谢谢了

**Comment by Kenshin** [comment]
哈，小事情。

感觉你用的似乎是配置库的现成模板，你可以根据 https://www.yuque.com/kenshin/simpread/ifioux#m48IJ 和上面提到的链接提示来修改和更换模板。
