### ISSUE TITLE
36氪

### ISSUE THREAD

**Issue by jkxing** [Kenshin/simpread#5718]
### 需要适配的新站

https://www.36kr.com/

### 有需要请描述这个站的性质

无法在简悦内部用阅读模式浏览
<img width="694" alt="image" src="https://github.com/Kenshin/simpread/assets/17963015/025dc5fb-1bfa-451c-a23b-c9a48e7b2c2d">

**Comment by Kenshin** [comment]
这个站已经适配了，但因为它是动态加载的，如果想要在稍后读中查看它，需要使用 [知识库方案](https://www.yuque.com/kenshin/simpread/wkswh7) 如果是新用户的话，可以直接试试 [配置库方案](https://www.yuque.com/kenshin/simpread/any457)
