### ISSUE TITLE
关于稍后读的一些疑问

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#5719]
### 描述这个错误

在稍后读中进行文章的修改与标注后，对应的修改没有应用于Obsidian保存的原文和annote
在图一中给这篇文章加了tag `分布式`，但Obsidian对应文章没有进行更新，没有添加该tag
![image](https://github.com/Kenshin/simpread/assets/74438973/c7a8cf82-df35-442d-bac0-2bcc818b52fd)
![image](https://github.com/Kenshin/simpread/assets/74438973/8f54f92e-ba4d-4a0c-9689-28bf344b5a27)
我其实怀疑是下面图中CSP的问题导致js代码不能执行和这次出错：
![image](https://github.com/Kenshin/simpread/assets/74438973/f3fbdc02-2a4f-420a-813c-23b1918e620d)

### 复现步骤

在Ob中通过此方法可以将修改和标注应用到annote文件中，但在稍后读中不能成功
![image](https://github.com/Kenshin/simpread/assets/74438973/d51a0788-abd3-417d-b472-967eb8ce1b7e)
![image](https://github.com/Kenshin/simpread/assets/74438973/2e222807-3926-43c1-9ec2-e22d5d52f6e9)

### 操作系统

Win11 专业版

### 浏览器

Chrome 114.0.5735

### 发生问题的网址

跟网址无关

**Comment by Kenshin** [comment]
嗨，因为在稍后读无法使用插件功能，所以在稍后读中没法实现导入到 Obsidian（标注），这是 Feature 不算是 Bug 😂

不过，我看到你应该配置了知识库，所以可以试试 https://github.com/Kenshin/simpread/discussions/3864 这个功能，跟在稍后读没有任何区别。

**Comment by jy324** [comment]
好奇问一句，在稍后读中没法使用插件是因为CSP策略吗？😢

**Comment by Kenshin** [comment]
> 好奇问一句，在稍后读中没法使用插件是因为CSP吗？😢

哈，不是，只是单纯的没有加这个功能。

在稍后读中其实不存在 CSP 问题，只有在网页端才有。

**Comment by jy324** [comment]
![image](https://github.com/Kenshin/simpread/assets/74438973/dee1fc7b-ec9a-481d-8adf-3425ebc2830d)
有的时候会显示成这样，不知道是什么问题？🤔

**Comment by jy324** [comment]
> 在稍后读中其实不存在 CSP 问题，只有在网页端才有。

稍后读里有确实有这样的问题，只不过无关紧要😂
![image](https://github.com/Kenshin/simpread/assets/74438973/99315128-7bc3-46ed-8fd3-2d9916858ebf)
![image](https://github.com/Kenshin/simpread/assets/74438973/c78eac7c-41c8-4f63-b5fe-152c6a0bfe7d)

**Comment by Kenshin** [comment]
> 稍后读里有确实有这样的问题，只不过无关紧要😂

哈哈，原来是这个问题，咱们说的不是一个事情，我是说「简悦插件不会有 CSP 的问题」。

你提到的问题严格来说不属于稍后读，当然对于普通用来说：「你说的对的，我理解错了」 😂

**Comment by jy324** [comment]
> 有的时候会显示成这样，不知道是什么问题？🤔

我这个问题被夹在中间了😂

**Comment by jy324** [comment]
![image](https://github.com/Kenshin/simpread/assets/74438973/bdf488f6-0de3-42ac-a4dd-2a69415b5537)
`http://localhost:7026/unread/752` 在这样的链接中左右翻稍后读会失败并且显示成这样

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5719#issuecomment-1617709580

emmm 是每个都这样？还是进入某个稍后读后这样？

**Comment by jy324** [comment]
某些正常，某些会这样出错

**Comment by jy324** [comment]
很玄学

**Comment by Kenshin** [comment]
应该是某个稍后读里面有些奇怪的 CSS 把这个导航「污染」了，理论上我已经很小心了... 😂

**Comment by jy324** [comment]
没有其他人碰到这样的情况吗？🤔

**Comment by Kenshin** [comment]
我收藏了 1xxx 个稍后读，目前没有，也没有其他的报告 😂
