### ISSUE TITLE
Lightbox Gallery插件将图片拉伸为同一尺寸大小很不合理

### ISSUE THREAD

**Issue by luojunv** [Kenshin/simpread#5721]
### 请描述你的建议或任何内容

Lightbox Gallery插件将图片拉伸为同一尺寸大小很不合理，导致大部分图片无法阅读。我又暂时没有找到可以更改这一属性的设置。希望能默认不改变原图尺寸。

**Comment by Kenshin** [comment]
试试 https://github.com/Kenshin/simpread/discussions/1598#discussioncomment-3480036 提到的方案，或者提供 URL 看看你的问题。
