### ISSUE TITLE
关于全文翻译的建议

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5722]
能不能支持一下Codeforces比赛网站里面的题目翻译，题目里面有那种加粗的数字之后，就不好使用翻译软件了。。。

_Originally posted by @aiyeyeyeyeye5 in https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6332376_

**Comment by Kenshin** [comment]
@aiyeyeyeyeye5

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

需要提供具体的 URL 才能判断

**Comment by aiyeyeyeyeye5** [comment]
谢谢大大，这个问题似乎不影响使用了

**Comment by Kenshin** [comment]
哈，解决就好。

明天发布全文翻译的 2.0 版，增加了一堆新功能，到时候我在这里通知你。

PS：要是有可能的话，准备好你的 ChatGPT 账户~

**Comment by Kenshin** [comment]
<img width="789" alt="Translate@cover" src="https://github.com/Kenshin/simpread/assets/81074/d1cb9c6e-f415-4c0e-b971-694b0d0879ab">

嗨，全文翻译升级到 2.0.0 版

# 新增

- `Add` OpenAI 官方源与自定义源

- `Add` [ChatGPT 源](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6119141)

- `Add` [微软翻译](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6149415)

- `Add` [谷歌翻译](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6158615)

- `Add` 当设置完翻译引擎后的测试功能

- `Add` 段落翻译增加 `Loading`

- `Add` 全文翻译进度可取消

- `Add` [一次性翻译全文](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6192919)

- `Add` [Prompt](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6193764)

# 重点

因为接入了 ChatGPT 并可以直接将全文发送给 ChatGPT，所以得到的翻译结果更精准，细节可以看  [简悦的知乎专栏](https://zhuanlan.zhihu.com/p/640958303)
