### ISSUE TITLE
关于标注的定位疑问

### ISSUE THREAD

**Issue by wrwangyue** [Kenshin/simpread#5724]
### 描述这个错误

第二次进入阅读模式时，使用了标注的那一段的标点符号会单独变颜色。
![image](https://github.com/Kenshin/simpread/assets/118095023/133c988b-99b4-4be1-8711-e027be42a531)

### 复现步骤

第一次标注正常。
退出阅读模式，重新进入时出现异常。
标点被另外上色。

### 操作系统

Windows

### 浏览器

Edge浏览器

### 发生问题的网址

https://xueqiu.com/1354233257/254615147（任意网址）

**Comment by Kenshin** [comment]
嗨，这个问题是因为定位错误造成的，简单的说，产生这个问题的原因：

1. 如果你只是标注了词重率很高的内容 e.g. 英文字母、标点符号
2. 这个页面的特殊结构就会出现截图的问题。

相对来说多出现于英文类页面，中文类也会出现但基本上是个例，并不是每个网页都有。

我先记录下。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~


解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
