### ISSUE TITLE
稍后读网站解析失败

### ISSUE THREAD

**Issue by keDesVn** [Kenshin/simpread#5725]
### 描述这个错误

稍后读网页解析失败

### 复现步骤

1. 将网页加入到稍后读中
2. 在稍后读中打开网页

### 操作系统

Windows 11

### 浏览器

edge

### 发生问题的网址

https://montysecurity.medium.com/identifying-phishing-pages-with-shodan-3fa664bd537

**Comment by Kenshin** [comment]
嗨，这算是预期行为，因为稍后读无法解析动态加载类或某些特殊的页面。

如果要实现在稍后读查看的话，需要配置知识库，这是 [一站式教程](https://www.yuque.com/kenshin/simpread/wkswh7)。
