### ISSUE TITLE
全文插件配置不知何时无故丢失

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5726]
### 描述这个错误

除了默认项的百度翻译以外的token和白名单设置都一扫空了
但是几个开关还保持原样

### 复现步骤

不该有的页面出现了图标，打开一看发现不对

![image](https://github.com/Kenshin/simpread/assets/69069739/b9bba229-9c02-4522-8d11-8df69fe478aa)

![image](https://github.com/Kenshin/simpread/assets/69069739/4a9332a9-eaf3-4170-8a86-eb4b5445ced8)

### 其他相关说明

查配置文件历史记录，没看到之前类似那样从某个节点开始文件大小突然断崖式下跌的情况
使用数据中心的修复插件，导出相关设置又双叒叕跟着一扫空了，啊，熟悉的味道，恢复出厂设置式修复

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

https://blog.csdn.net/hujy23/article/details/103124648

**Comment by Kenshin** [comment]
> 查配置文件历史记录，没看到之前类似那样从某个节点开始文件大小突然断崖式下跌的情况
使用数据中心的修复插件，导出相关设置又双叒叕跟着一扫空了，啊，熟悉的味道，恢复出厂设置式修复

如果只是修复的话，并不能将消失的插件配置找回来… 😂

至于你的问题，估计没法复现 😂 

一般来说，可能是是不是用插件管理器升级后，又点了另外一个「按钮」？明天给你截图。

左侧的是安装（升级）；右侧的是导入配置（或重置）

到你给的现象又不太一样…

好在插件的选项没几个。 😂

**Comment by PupupupuTong** [comment]
我近期并没有升级过插件

**Comment by PupupupuTong** [comment]
所以，插件的配置有办法同步吗？其他也就罢了，重新弄一遍花不了多少时间，但像白名单这种需要时间慢慢积累的莫名其妙一下子没了真的让人难以接受。。。

**Comment by Kenshin** [comment]
1. 插件的配置是同步的，也就是说保存在配置文件中（插件本身不同步）
2. 升级插件不会无故出现这种情况。（也就是说程序在升级中做了一些设置会保证不会丢失数据）
3. 但任何程序都会有 Bug。比如你遇到的情况，因为 100% 没法复现，所以也没有什么太好的方案。

非要找回你需要的数据，可以利用历史记录，比如简悦目前支持两种历史记录：坚果云与同步助手，找到一个你认为有数据的时间点，用任意文本编辑器打开这个 simpread_config.json 然后检索插件 ID。

如果你对这个步骤感兴趣的话，我可以详细描述下。

**Comment by PupupupuTong** [comment]
愿闻其详

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
