### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by zixuan2012win** [Kenshin/simpread#5729]
### 描述这个错误

问题：在网站“淘股吧”导出时会失败，失败提示信息为：导出失败，此功能为实验性功能，如有需求请提Issues。
淘股吧网站网址为：https://www.taoguba.com.cn/，操作流程已截图
![BaiduShurufa_2023-7-4_11-18-2](https://github.com/Kenshin/simpread/assets/137153620/a43fea0c-9f28-4f39-9b0d-fe26725ca083)
，请给予帮助。

### 复现步骤

1、打开淘股吧网站；
2、点击淘股吧文章；
3、打开简悦阅读模式；
4、标注自动同步到Obsidian或导出PDF等失败；
5、导出图片可以成功。

### 操作系统

WIN7

### 浏览器

360极速浏览器/32位版本

### 发生问题的网址

https://www.taoguba.com.cn/

**Comment by Kenshin** [comment]
1. 导出什么？
2. 在阅读模式下的导出有问题吗？

**Comment by zixuan2012win** [comment]
1、导出pdf、HTML等，除了图片其他格式都导出都会出现失败；
2、就是在阅读模式下导出产生的问题。

https://github.com/Kenshin/simpread/assets/137153620/97b7a003-2ebf-4d51-8d09-b8541b2402af

**Comment by Kenshin** [comment]
1. 其它页面 e.g https://sspai.com/post/69972 是否有问题？

2. 是否使用了同步助手的导出方案？还是基础导出方案？（如果是同步助手的导出方案，需要安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by Kenshin** [comment]
emmmm 我大概知道什么问题了。

安装 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 然后使用它修改标题，删除全部标题再重新输入任意你需要的内容。

然后在试试导出。

PS：我使用导出到本地的任意位置这个功能是没问题的。

**Comment by zixuan2012win** [comment]
我安装了Live Editor并尝试按照您的方案处理，但仍旧显示失败，我更换到edge浏览器重复刚才的操作还是不行.
您导出没有问题的话可否把配置文件给我发下，我按照您的配置文件进行尝试，谢谢。
另：导出PDF在其他网站没有发现问题，唯独在“淘股吧”网站有问题。

**Comment by Kenshin** [comment]
我的配置文件没有参考价值，因为帮用户测试时都是新配置文件。

留意下：如果使用了基础导出功能的话是通过浏览器下载的，下载后浏览器有时间有提示下载完成的信息。

所以，确认下是否是通过浏览器下载。

另外：**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

或者也可以试试下图所示的方式，重新生成阅读模式。

<img width="663" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1b9e040b-7b03-4a2c-9a14-21a4980ae045">

**Comment by zixuan2012win** [comment]
1、浏览器没有相应的下载提示，那应该是用的同步助手进行导出；
2、尝试把所有插件关闭，只保留简悦插件，且采用手动框选转入阅读模式，但仍旧显示失败；
3、您如何可以成功，那是我的配置有问题？但为什么其他网站可以搞定了，望指教。
我用的是Microsoft Edge
版本 103.0.1264.37 (正式版本) (32 位)
![BaiduShurufa_2023-7-4_18-54-54](https://github.com/Kenshin/simpread/assets/137153620/24160c70-89d9-4cf1-b8f7-8ca8dd270b19)

**Comment by Kenshin** [comment]
在下图辨别是否使用了增强导出功能

<img width="1695" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/77b4a35b-385a-475d-ba02-8d9b2414a806">

另外，使用增强导出功能的另外一个前提：使用了同步助手。

如果就只是这个页面有问题的话，别纠结了 😂 我直接发给你（改名为 `.html` 即可） 
[大 AI→大汽车.txt](https://github.com/Kenshin/simpread/files/11948632/AI.txt)

**Comment by zixuan2012win** [comment]
使用了增强导出
![2](https://github.com/Kenshin/simpread/assets/137153620/80939839-69a7-4a95-ae32-4b0f57651f32)
如果单是这一个页面倒也不纠结，主要是整个淘股吧网站都是这个问题，因为需要经常性阅读该网站，所以想着能解决是最好的。
另：我邮箱里直接回复您，附带附件您能否收到，想着把操作视频发下，可以对问题有一个更清晰的认知。

**Comment by Kenshin** [comment]
把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5727

但我只能明天帮你确认了。
