### ISSUE TITLE
简悦保存的知乎盐选内容怎么搞

### ISSUE THREAD

**Issue by kunpeng9** [Kenshin/simpread#5731]
### 请描述你的建议或任何内容

之前没有很仔细，仔细看了下发现是只保存了网址，没有快照
目前有900多条，盐选还有2个月就要过期了，怎么搞
![天若_20230704222334](https://github.com/Kenshin/simpread/assets/44609485/9425bb0d-127e-459f-bb4c-a2976bc49cd6)
如果都保存到本地的话，又要点几百次。
之前搞忘记了，没用自动化流程，近几天开启发现自动化好像失效了，保存到稍后读 没有保存到本地。

**Comment by Kenshin** [comment]
emmm 😂

这个没办法，简悦不是用于批量保存的工具... 

你截图的第一个稍后读就是保存在本地的。

PS：会员过期后知乎盐选已经看过的内容也没法看？（我很少充值国内的产品，完全不知道...
