### ISSUE TITLE
基于OpenAI的插件安装后没有正常显示

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5732]
### 描述这个错误

我安装了阅读助手（OpenAI语境。。。），在插件页能看到该插件，并支持禁用。
<img width="524" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/e9fb0248-d095-4885-8995-dba4c5dfe988">
但是在文章动作页，看不到该插件。。。
<img width="489" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/bc094e27-76c9-4a15-b03e-d6db06459f71">

### 复现步骤

　1.进入插件管理页
　2. 搜索插件并安装
　3. 使用插件（没成功）

### 操作系统

macOS Ventura 13.4

### 浏览器

Chrome Version 114.0.5735.90 (Official Build) (arm64)

### 发生问题的网址

https://view.inews.qq.com/k/20230704A08MNH00

**Comment by shadu120** [comment]
禁用同步助手后，重装插件生效。

**Comment by Kenshin** [comment]
嗨，你的操作不正确 😂

使用同步助手的自动同步后，需要使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装，即可。
