### ISSUE TITLE
希望基于OpenAI的阅读助手支持自定义API域名

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5733]
### 请描述你的建议或任何内容

<img width="481" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/76482143-b05f-48a6-9b8c-01f5f3cd9b90">

因为，浏览器默认不能访问openai的接口，所以，希望简悦支持自定义token的时候，支持自定义API地址。

**Comment by Kenshin** [comment]
> 浏览器默认不能访问openai的接口

你理解错了，你直接调用的是简悦的后端，所以不需要担心这个事情...

不过，会考虑定制 API 的功能。

**Comment by Kenshin** [comment]
嗨，我在这里调研下 **使用自定义 API 的意义**，看到后请在 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1621070991 回复讨论

**Comment by shadu120** [comment]
后端？那就是简悦替我转发了呗？那岂不是？。。。

**Comment by Kenshin** [comment]
> 后端？那就是简悦替我转发了呗？那岂不是？。。。

你想说什么？

有任何疑问建议先看下 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1621070991 的说明。

**Comment by Kenshin** [comment]
PS：在 Telegram 找我也行 😂

**Comment by Kenshin** [comment]
![OpenAI@cover v2](https://github.com/Kenshin/simpread/assets/81074/03673e06-13fd-4752-b6e7-34cfcc460feb)

嗨，[阅读助手 3.1.0](https://github.com/Kenshin/simpread/discussions/5158) 发布了

## 新功能

- `Add` [自定义第三方 API 服务](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6361313)

    ![image](https://github.com/Kenshin/simpread/assets/81074/a4eb995e-0a29-4767-962f-92d498899d1f)

- `Add` [支持 GPT-4](https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-5175855)

    ![image](https://github.com/Kenshin/simpread/assets/81074/30440609-23d2-4767-8411-2c31d8dba999)

## 📈 安装与升级

1️⃣ 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/Mv55R9uIOF) 安装。

2️⃣ 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

有任何疑问请前往 https://github.com/Kenshin/simpread/issues/5433#issuecomment-1624903383 讨论，我关闭这个 issues 了~
