### ISSUE TITLE
nition 授权失败

### ISSUE THREAD

**Issue by panda-cjh** [Kenshin/simpread#5734]
### 描述这个错误

nition 授权失败，一直这样，按照教程已经做了还是这样

### 复现步骤

nition 授权失败，一直这样，按照教程已经做了还是这样

### 操作系统

win10

### 浏览器

eage

### 发生问题的网址

随意

**Comment by Kenshin** [comment]
照哪个教程？怎么做了... 😂

建议提供一些更精准的描述或者看下 https://www.yuque.com/kenshin/simpread/wwk65u#ERFLg 解决方案。
