### ISSUE TITLE
安装简阅后，维基文库的正文显示不出来

### ISSUE THREAD

**Issue by 3-2** [Kenshin/simpread#5735]
### 描述这个错误

包机维基文库首页与所有条目页。

![image](https://github.com/Kenshin/simpread/assets/25643218/8bf4db63-8cda-4907-b5f4-741e9ccf24aa)

### 复现步骤

1. 安装简阅
2. 打开维基文库网站

### 操作系统

Windows 10

### 浏览器

Chrome 114.0.5735.199

### 发生问题的网址

https://zh.wikisource.org/wiki/Wikisource:%E9%A6%96%E9%A1%B5

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347
