### ISSUE TITLE
官网这个链接失效了

### ISSUE THREAD

**Issue by crazypeace** [Kenshin/simpread#5736]
### 描述这个错误

http://ksria.com/simpread/

![image](https://github.com/Kenshin/simpread/assets/665889/de2e9ba0-ab87-4128-9ad8-7927af26f127)

![image](https://github.com/Kenshin/simpread/assets/665889/58286516-e2db-4cf5-82b6-c75d383d982f)

### 复现步骤

访问官网
点击轻阅版的下载按钮
显示请求的脚本已删除

### 操作系统

win

### 浏览器

any

### 发生问题的网址

https://greasyfork.org/zh-CN/scripts/39998

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

油猴脚本暂时下线了，因为只是 1.x 的部分功能。
