### ISSUE TITLE
同步疑问

### ISSUE THREAD

**Issue by freedomspiritJohn** [Kenshin/simpread#5745]
### 请描述你的建议或任何内容

目前的自动同步方案是需要加一个本地客户端，虽然我不知道为什么这么设计，但是还需要额外开一个本地的软件才能同步，多少有点鸡肋呀。可以像暴力猴那样，直接一个webdav把所有的东西都给同步了。如果我的想方式不可行的，那就算了。

**Comment by Kenshin** [comment]
嗨

1. 你可以使用 [手动方式](https://simpread.pro/docs/#/%E6%89%8B%E5%8A%A8%E5%90%8C%E6%AD%A5)，支持坚果云，也就是你提到的 WebDAV 方案。

2. 同步助手提供的不仅仅只是同步功能，[还有很多](https://github.com/Kenshin/simpread/discussions/categories/%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)，
你可以理解通过同步助手在本地建立了一个「服务器」环境。

有兴趣的话，可以花 10 分钟左右看下 https://www.yuque.com/kenshin/simpread/ebwu7g 提到的一些解释。
