### ISSUE TITLE
微信公众号文章适配问题

### ISSUE THREAD

**Issue by 235337218** [Kenshin/simpread#5753]
### 描述这个错误

https://mp.weixin.qq.com/s?__biz=Mzg3MzgzMzMxOA==&mid=2247496926&idx=1&sn=c1184813af67f46b38388c7c143679d4&sharer_sharetime=1688823420420&sharer_shareid=ce3b9e95b9eb928695c2b195e8c869d5&notreplace=true#rd&wxwork_userid=yangfeng2000

这个微信公众号的文章会识别不出来

### 复现步骤

1.打开电脑端的微信
2.打开微信公众号
3.选择一篇文章，右键单击，选择使用默认的浏览器

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=Mzg3MzgzMzMxOA==&mid=2247496926&idx=1&sn=c1184813af67f46b38388c7c143679d4&sharer_sharetime=1688823420420&sharer_shareid=ce3b9e95b9eb928695c2b195e8c869d5&notreplace=true#rd&wxwork_userid=yangfeng2000

**Comment by Kenshin** [comment]
嗨，个别公众号确实有这个问题，你可以使用 https://github.com/Kenshin/simpread/discussions/1554 提到的方案解决。

<img width="1513" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/218738dc-33d8-4636-8d0a-521c48d11d10">
