### ISSUE TITLE
稍后读的保存内容相关

### ISSUE THREAD

**Issue by yoghurtdewdew** [Kenshin/simpread#5755]
### 请描述你的建议或任何内容

1 希望稍后读能够保留翻译插件翻译的内容，不仅仅是原文
2 我从www.sciencedirect.com存了一篇内容到稍后读，发现只存到摘要，后面的全文内容没有存到
3 在稍后读的界面找了很久原文链接

**Comment by Kenshin** [comment]
> 希望稍后读能够保留翻译插件翻译的内容，不仅仅是原文

可以的，细节 https://github.com/Kenshin/simpread/discussions/3182

>  我从www.sciencedirect.com存了一篇内容到稍后读，发现只存到摘要，后面的全文内容没有存到

可以的，需要配置知识库 https://www.yuque.com/kenshin/simpread/wkswh7

> 在稍后读的界面找了很久原文链接

<img width="341" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/849f8509-d95d-4de5-9075-fbf51e0d1443">

**Comment by yoghurtdewdew** [comment]
感谢您的及时回复！
1 我看了【彩云小译实现双语翻译并同时保持在本地】，我的插件是【沉浸式翻译】，在点击进入网页后显示了翻译，重新生成的阅读模式和重新之前都有带翻译，但是加入稍后阅读，就没了
2 我看了【一站式知识库配置】，这里面提到的是桌面端的同步助手，我暂时还没想要全都保存到本地，因为直接保存到本地可能是html文件，我的笔记app好像没法打开这些，所以我会后面考虑配置同步到某个笔记app，等稍后阅读中显示结果和格式等心满意足后，所以可能和这篇帮助文档相关性不大。我在网页上，打开稍后读，打开阅读模式，看到只存了摘要，没有继续往下存内容，也没有翻译，而我在点击网页直接进入阅读时，是有翻译而且有后面的内容的。
3 感谢！这个可以 一个page显示为一行的那种列表清爽视图吗，只显示标题就ok

**Comment by Kenshin** [comment]
> 在点击进入网页后显示了翻译，重新生成的阅读模式和重新之前都有带翻译，但是加入稍后阅读，就没了

跟什么翻译无关。😂 

阅读模式中有什么，导出到本地后就有什么，但前提是 **配置知识库** 方案。

如果你不想使用同步助手的话，这个方式肯定实现不了。

> 一个page显示为一行的那种列表清爽视图吗

稍后读暂时没有，不过已经是 Feature 了~

**Comment by yoghurtdewdew** [comment]
导出到本地？我的意思是，不捣鼓本地，直接在网页端，打开稍后读，**稍后读里面的阅读模式，里面没有全文**……这个不能有？

导出到本地是啥格式，能从本地导出到笔记app么 😂
