### ISSUE TITLE
安装站点集市失败

### ISSUE THREAD

**Issue by ccstudentcc** [Kenshin/simpread#5758]
### 描述这个错误

看视频吧，我就是正常的操作

### 复现步骤

https://github.com/Kenshin/simpread/assets/138267279/7f4d13a0-e862-4738-8233-9a6cfd938821

### 操作系统

windows

### 浏览器

chrome 114.0.5735.199（正式版本） （64 位）

### 发生问题的网址

s

**Comment by Kenshin** [comment]
嗨，是不是使用了同步助手的自动同步功能？如果是的话，解决方案 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k

**Comment by ccstudentcc** [comment]
谢谢！解决了

**Comment by Kenshin** [comment]
okay 解决就好~
