### ISSUE TITLE
代码块缺少注释内容/Missing comments in code blocks.

### ISSUE THREAD

**Issue by Sky-Walkrr** [Kenshin/simpread#576]
问题描述：
在浏览[这篇文章](https://blog.lqdev.cn/2019/07/21/springboot/chapter-thirty-eight/)的时候，进入阅读模式发现代码块里缺少了注释内容。例如文章中的 `SpringBoot 集成 RabbitMQ 实现延时队列实战` 部分第一节 `1. 编写rabbitmq配置文件（关键配置）` 的 Java 代码，所有注释内容都没有显示。由于这部分注释是有助于解读代码的，如果能正常显示就好了。

其他信息：
简阅版本 1.1.3
已安装 代码块增强插件，使用快捷键 `hhh` 重新调整了代码块还是没有显示出注释内容。

**Comment by Kenshin** [comment]
谢谢反馈，我在外面，只能明天确认下。
不过，你可以看看这篇关键问题 https://github.com/Kenshin/simpread/issues/570

**Comment by Kenshin** [comment]
谢谢反馈，我在外面，只能明天确认下。
不过，你可以看看这篇关键问题 https://github.com/Kenshin/simpread/issues/570

**Comment by Kenshin** [comment]
已经确认了，应该是插件把 `<!-- -->` 正则掉了，修复后通知你。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本


这个问题 `算是不完美的解决了` 如果在遇到此问题，可以通过 右下角 → 控制栏 → 动作 → 重新高亮 来解决。

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本


这个问题 `算是不完美的解决了` 如果在遇到此问题，可以通过 右下角 → 控制栏 → 动作 → 重新高亮 来解决。

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
