### ISSUE TITLE
https://noto.so/ 会提示Error Caused by SimpRead extension 

### ISSUE THREAD

**Issue by Abirdcfly** [Kenshin/simpread#5762]
### 描述这个错误

![CleanShot 2023-07-14 at 09 26 10](https://github.com/Kenshin/simpread/assets/5100555/a4dd51e8-0f10-4dcc-94a8-fa2e27d96788)

### 复现步骤

访问https://noto.so/ 即可

### 操作系统

macOS

### 浏览器

chrome 114.0.5735.198（正式版本） (x86_64)

### 发生问题的网址

https://noto.so/

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347

PS：我已经把这个链接对应的解决方案告诉 noto.so 了，但它可能没有加上。
