### ISSUE TITLE
网站无法批注

### ISSUE THREAD

**Issue by ccstudentcc** [Kenshin/simpread#5763]
### 描述这个错误

https://blog.csdn.net/qq_43309940/article/details/125150487
这个网站进入阅读模式，划线无法批注。清除了网站的cookie还是一样。

### 复现步骤

https://github.com/Kenshin/simpread/assets/138267279/50081ab5-e140-4ad7-b655-a57fc038c662

### 操作系统

windows

### 浏览器

chrome 114.0.5735.199（正式版本） （64 位）

### 发生问题的网址

s

**Comment by ccstudentcc** [comment]
好吧，是浏览器插件冲突了。没事了，

**Comment by Kenshin** [comment]
没问题就好，我关闭这个 Issues 了。
