### ISSUE TITLE
关于阅读模式的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5764]
您好   可以隐藏页面尾缀吗?      
非常喜欢简阅, 已升级高级账户并五星好评~
![image](https://github.com/Kenshin/simpread/assets/15666939/d2c6ab75-fed7-4e50-8916-7b8a4507e7dc)

_Originally posted by @LoinApex in https://github.com/Kenshin/simpread/discussions/1554#discussioncomment-6446804_

**Comment by Kenshin** [comment]
@LoinApex

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

谢谢喜欢简悦，PS：你在哪里的五星 + 好评？

***

你提到的问题可以通过 [自定义样式](https://simpread.pro/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决，方案如下：

将下面的代码 

```
sr-rd-footer {
    display: none;
}
```

加入到下面的位置，保存后重启浏览器。

<img width="474" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a2f4f76b-6b7c-421e-963c-3fb55bf57ef9">

**Comment by LoinApex** [comment]
![image](https://github.com/Kenshin/simpread/assets/15666939/3a37c68e-7c73-42d6-bd3b-92ee5e0401e8)
是这里吗? 现在没有看到全局样式的选项

**Comment by LoinApex** [comment]
![image](https://github.com/Kenshin/simpread/assets/15666939/3e83c911-728b-4eda-a2d8-fe11f0c2cc64)
 已更新生效, 感谢~


PS:已添加五星及好评, 感谢遇见~

**Comment by LoinApex** [comment]
![image](https://github.com/Kenshin/simpread/assets/15666939/53d22c0e-7aee-4597-8014-68708c167165)

简阅可以单独吧导出notion图标单独拿出来或者添加为快捷方式的形式方便点击操作吗?

**Comment by Kenshin** [comment]
> 简阅可以单独把导出notion图标单独拿出来或者添加为快捷方式的形式方便点击操作吗?

当然可以了 https://github.com/Kenshin/simpread/discussions/1600

> https://github.com/Kenshin/simpread/issues/5764#issuecomment-1635570712

更好的方式是我像我截图，位置在：进入阅读模式 → 右下角触发器 → 样式 里面。

> https://github.com/Kenshin/simpread/issues/5764#issuecomment-1635588673

这个截图里面的设置是你主动调整的吗？我问的是下图

<img width="492" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7ee53f84-af35-48f7-9bc8-3919911090a5">

**Comment by LoinApex** [comment]
更好的方式是我像我截图，位置在：进入阅读模式 → 右下角触发器 → 样式 里面。
-------------------
Assistive Touch 试了一下,不太好用

 我也希望是在系统按钮里面操作, 按钮我不知道如何调整, 如果可以调整我希望可以自定义需要显示的内容, 这样我找notion按钮的过程就可以简化了

**Comment by LoinApex** [comment]
不太喜欢有按钮像小广告一直贴着, 而且操作还需要移动不同的方向  ==

系统菜单如果可以定制显示的按钮就好了

这个插件找不到设置位置, 其他插件也遇到这个情况, 建议在插件管理添加统一设置入口
![image](https://github.com/Kenshin/simpread/assets/15666939/bdb29bf3-3cf2-4a66-845c-cf5e1011d91f)

**Comment by Kenshin** [comment]
> 这个插件感觉可以满足需求, 只是找不到设置位置

阅读模式比较特别，它的入口都在各个具体进入阅读模式的页面，即：阅读模式 → 右下角触发器 → 动作 → 插件触发器

**Comment by LoinApex** [comment]
我在高级控制面板设置快速暂存的之后, 设置相互控制面板之后不显示
 ![image](https://github.com/Kenshin/simpread/assets/15666939/1ea563e6-c635-4ae1-bb42-5ccc778718cf)

**Comment by Kenshin** [comment]
> 设置相互控制面板之后不显示

没理解什么意思。

**Comment by LoinApex** [comment]
> 

没说清楚, 上面修改过了, 使用[阅读模式浮动面板定制器]这个插件基本可以满足需求

**Comment by Kenshin** [comment]
> 没说清楚, 上面修改过了, 使用[阅读模式浮动面板定制器]这个插件基本可以满足需求

okay 没问题就好。
