### ISSUE TITLE
阅读模式背景色无法改变

### ISSUE THREAD

**Issue by kaipol** [Kenshin/simpread#5769]
### 描述这个错误

更改选项页的基础-阅读模式的背景色为丁子色并保存后，开启阅读模式后，背景色仍为黑色，需手动更改背景色
<img width="843" alt="image" src="https://github.com/Kenshin/simpread/assets/108178985/08328f9f-c35d-4d28-9b06-9bd6a4871623">
<img width="1215" alt="image" src="https://github.com/Kenshin/simpread/assets/108178985/2ecb82ff-407f-4935-8373-16682df74c19">

### 复现步骤

更改设置后重启过浏览器，刷新过页面，均不行

### 操作系统

Windows11

### 浏览器

Edge

### 发生问题的网址

https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md等其他网站

**Comment by Kenshin** [comment]
在选项页修改后，重启浏览器试试能否生效？

**Comment by kaipol** [comment]
不行，仍然是黑色的背景色

**Comment by Kenshin** [comment]
试试这个方式 https://github.com/Kenshin/simpread/discussions/2992

**Comment by kaipol** [comment]
可以了，感谢

**Comment by Kenshin** [comment]
okay 解决就好~
