### ISSUE TITLE
有时候看不清楚插件弹出的窗口上的字（好多个插件都有此问题）

### ISSUE THREAD

**Issue by yoghurtdewdew** [Kenshin/simpread#5770]
### 描述这个错误

有时候看不清楚插件弹出的窗口上的字（好多个插件都有此问题）
![image](https://github.com/Kenshin/simpread/assets/63794438/98ef6b52-8911-4f8f-a08c-3a9cedb19a3a)
![image](https://github.com/Kenshin/simpread/assets/63794438/db2c9e53-df67-4e58-af1a-6b0d5e825deb)
![image](https://github.com/Kenshin/simpread/assets/63794438/3258ccd9-c9fe-4292-997c-0f36b1fdb1ca)

### 复现步骤

点某个插件/动作的选项后进行设置的时候

### 操作系统

MacOS

### 浏览器

114.0.1823.67 (正式版本) (arm64)

### 发生问题的网址

https://www.sciencedirect.com/

**Comment by Kenshin** [comment]
emmm  试试在 https://sspai.com/post/69972 上查看？

**Comment by yoghurtdewdew** [comment]
> emmm  试试在 https://sspai.com/post/69972 上查看？
好像这个网站上显示正常 谢谢

**Comment by Kenshin** [comment]
出问题的是 https://www.sciencedirect.com/ 吗？

**Comment by yoghurtdewdew** [comment]
啊 我邮件里看混了以为是另一个issue里的，是的是这个网址里会混乱
