### ISSUE TITLE
维基教科书无法正常显示

### ISSUE THREAD

**Issue by igeOGIbl** [Kenshin/simpread#5771]
### 描述这个错误

https://zh.wikibooks.org/ 这个网站只要是安装简悦必显示不正确，Edge在关闭其他扩展情况下，成功复现，关闭简悦后问题没有了。

### 复现步骤

1，打开Edge
2，安装简悦
3，进入 https://zh.wikibooks.org
4，会看见正常网页闪烁一下，然后内容空白
![image](https://github.com/Kenshin/simpread/assets/100392707/3ca7fc1f-2d29-4ba4-b0c2-d817c68c5349)
下图是关闭简悦后正常显示
![image](https://github.com/Kenshin/simpread/assets/100392707/ac64b27c-10a2-4729-94b5-86fade853449)

### 操作系统

Windows 10

### 浏览器

Edge 114.0.1823.82

### 发生问题的网址

https://zh.wikibooks.org/wiki/Wikibooks:%E9%A6%96%E9%A1%B5

**Comment by igeOGIbl** [comment]
解决了，看见以前方案了 https://github.com/Kenshin/simpread/discussions/2347

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347

**Comment by Kenshin** [comment]
就是这么巧 😂

<img width="386" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4f18975e-c888-431e-b509-3613c547f8fe">
