### ISSUE TITLE
提示当前Token有可达到调用的最大次数，该怎么处理？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5773]
提示当前Token有可达到调用的最大次数，该怎么处理？

_Originally posted by @Chengjiuyou in https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-6456011_

**Comment by Kenshin** [comment]
@Chengjiuyou

我新建了 Issues 来讨论这个情况。

***

稍等一会再试试。

**Comment by jy324** [comment]
我在使用时也报这个错误😂
并且过一段时间再试也没用，每个网页都会这样
<img width="424" alt="image" src="https://github.com/Kenshin/simpread/assets/74438973/d8a643ca-8cdc-4e4d-87cb-9a7029ddc85b">
<img width="764" alt="image" src="https://github.com/Kenshin/simpread/assets/74438973/50615ded-0c65-412e-978e-a873ba8c3188">

**Comment by Kenshin** [comment]
@jy324 

emmm 是正规的 OpenAI Token 吗？如果是的话，你应该可以上 Telegram 吧？然后私聊我，我看下。

这个功能没问题的，每天都有很多人在用，否则我早就知道了。
