### ISSUE TITLE
稍后读调用本地文件有时会正文与原文不符

### ISSUE THREAD

**Issue by 9527raphael** [Kenshin/simpread#5775]
### 描述这个错误

当将网页加入到稍后读并且自动保存网页在本地且设置稍后读为优先读取本地文件后，在删除稍后读内相关网页条目并添加新的条目，新条目的正文会是之前被删除条目的正文。

### 复现步骤

1，按教程配置好内容库，设置自动化保存且优先读取本地文件。
2，添加A网页进入稍后读，同时自动保存A网页到本地。
3，稍后读中删除稍后读中的A网页，并添加B网页。
4，稍后读中打开B网页。会发现，B网页的标题是正确的，但正文是A网页的。

### 其他相关说明

查看原因是在自动保存本地文件时，本地文件名被自动编号，如：A网页的本地文件为1-(A网页名),在稍后读中删除了A网页的条目，但本地文件不会自动被删除，之后添加B网页，B网页的本地文件名标号为1-(B网页名)，稍后读在打开B网页时，并没有调用B网页的本地文件，而是调用了相同序号的A网页本地文件。

### 操作系统

macos

### 浏览器

egde

### 发生问题的网址

https://www.appinn.com/kindlecn-2024-bye/

**Comment by Kenshin** [comment]
嗨，谢谢详细测试，你可以用 [这个功能](https://simpread.pro/docs/#/Sync?id=%e5%88%a0%e9%99%a4%e6%97%a7%e6%96%87%e4%bb%b6) 解决。
