### ISSUE TITLE
添加站点适配之后，阅读模式下描述内容不跟随正文更新了

### ISSUE THREAD

**Issue by luoxiaohei** [Kenshin/simpread#578]
sr-rd-desc 标签内的内容，之前是根据当页的正文提取的，但是现在一直不变了。测试没有站点适配规则的情况下是正常的，请问是我哪里没配置好么？好像没找到相关文档。

具体现象如下图

![image](https://user-images.githubusercontent.com/7138906/64626058-ca9ef300-d41f-11e9-817f-22d06862696c.png)

**Comment by Kenshin** [comment]
谢谢反馈，建议把 URL 发上来，及 **打开当前页面的站点编辑器** 后也一并截图。

**Comment by luoxiaohei** [comment]
好的，URL 是这个，https://docs.hacknode.org/gopl-zh/ch6/ch6-02.html
目前站点编辑器是这样的
![image](https://user-images.githubusercontent.com/7138906/64662825-5d6d7b00-d47c-11e9-8db0-e08d3a364b7d.png)

**Comment by Kenshin** [comment]
请问这个站是你自己适配的吗？

`sr-rd-desc` 如果为空的话，会自动使用 
`[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]`

来获取，所以你试着填入上面的默认值，再看看。

**Comment by luoxiaohei** [comment]
是的，我参考 gitbook.com 的适配规则自己添加的适配，我在描述的输入框加了下边代码之后没有起到作用。
```
[[{$('meta[name=Description]').attr('content')||$('meta[name=description]').attr('content')}]]
```

目前的现象是，如果我在某一个页面上添加站点适配，后边其他页面的描述都会使用添加适配规则那一个页面的描述。但是我查询页面源码发现并没有这段文字，所以怀疑是不是站点适配之后使用了缓存？

我尝试清空了浏览器数据，但是没有起到作用。我使用的是 Chrome 插件。

**Comment by luoxiaohei** [comment]
在浏览器调试了下，看起来是在站点适配规则里有个 `excerpt` 的字段，内容就是添加站点规则时候的描述内容，感觉应该是这个字段影响了，但是对 js 不太熟悉，还没找到这个在哪里生成的

![image](https://user-images.githubusercontent.com/7138906/64683378-ba395780-d4b5-11e9-8930-5b750f4381ca.png)

**Comment by luoxiaohei** [comment]
在调试模式下，我在站点管理页面保存当前站点时，删掉了 `excerpt` 字段，目前已经可以做到在阅读模式下不显示摘要了。

我还没找到如何根据正文生成摘要的方法，我尝试在 `excerpt` 字段添加了代码，但是看起来并没有生效，页面只是将代码以文本形式打印出来了。

**Comment by Kenshin** [comment]
估计应该是这个字段造成的。
我大概知道是什么原因了，只是不清楚你能否稳定复现这个错误...  😅 

PS：按道理来说，这应该是个极其隐含的错误。

**Comment by luoxiaohei** [comment]
从现象上看，应该是因为在保存站点适配规则时，`Cleansite` 方法没有执行 `delete t.excerpt ` 造成的，我这边可以稳定复现这个问题。

但是目前我只能做到将 `excerpt` 字段删掉，不生成摘要，没办法做到让阅读模式像没有适配时一样自动生成摘要。求助～

好像 puread 没有提供未压缩的源码，在代码库里只找到了这个压缩的文件。

https://github.com/Kenshin/simpread/blob/384df72c0108ff7bea3ef1dfc723841f34cc97e6/src/vender/puread/puread.min.js#L1

**Comment by Kenshin** [comment]
没想到，调查的这么清楚。
基本上就是这个原因造成的。 👍 
不过，抱歉，只能下个版本解决这个问题。 😂

**Comment by luoxiaohei** [comment]
好 😄

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已解决此问题~

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
