### ISSUE TITLE
支付了2天了未收到授权码

### ISSUE THREAD

**Issue by ResolveWang** [Kenshin/simpread#5786]
### 请描述你的建议或任何内容

你好，我在2023-7-17，购买了简悦高级会员，到今天还未收到授权码。支付方式为支付宝

**Comment by YukiLx** [comment]
你需要看一下你是通过什么样的方式购买的授权码，然后去相应的平台中查看系统消息，看是否有相关的内容。
以`爱发电`为例，在购买的时候会让你填写一个手机号，实际上会使用这个填写的手机号注册`爱发电`账号。你可以使用填写的手机号登录`爱发电`，查看系统中的消息，应该会收到授权码相关的内容。
其他购买渠道可以看一下下面这个内容，里面有提到`腾讯问卷`、`爱发电`、`少数派`三个购买渠道找回授权码的方法
[Discussion-2756](https://github.com/Kenshin/simpread/discussions/2756)

**Comment by Kenshin** [comment]
@ResolveWang 

腾讯问卷不是实时发送兑换码，大概 48 小时左右，因为是半人工，一般情况下是 48 小时以内，偶尔会超过。

我已经刚刚发送了兑换邮件，如果你的 Email 填写无误的话，应该收到邮件了。

***

@YukiLx 

谢谢帮忙解答。

**Comment by ResolveWang** [comment]
你好，还有个问题想请教一下，简悦的数据同步功能我自己能关掉吗，我只想把网页存储在obsidian，因为有一些可能是敏感信息，不想同步到云上，这个怎么做呢？现在我看是点了阅读模式，然后点动作，保存到obsidian，再看上次同步时间就变成了当前时刻，这是表示已经同步到云上了吗？我也没有设置任何云盘账户

**Comment by Kenshin** [comment]
> 简悦的数据同步功能我自己能关掉吗

当然，如果你不需要这个功能的话，当然可以关闭。

> 我只想把网页存储在obsidian，因为有一些可能是敏感信息，不想同步到云上，这个怎么做呢？

所谓同步需要两个步骤：

1. 将配置文件保存到本地（文件夹）。
2. 如果这个本地文件夹恰好在某个网盘上，就实现了同步。

以你的诉求来说，在本地就行了，不需要步骤2，但也失去了多设备同步功能。

或者说，你也可以将这个文件夹设置到 NAS 上实现步骤2，也是一样的。
