### ISSUE TITLE
控制栏改进

### ISSUE THREAD

**Issue by PiscesDreamer** [Kenshin/simpread#5789]
### 请描述你的建议或任何内容

简悦功能太丰富，控制栏的滚动条有点过长。
我在使用过程中发现，想要在动作栏里设置插件的相关配置就需要拉动很长的滚动条，
这样很不合理。希望能改进下这方面，能否在右上角设置类似目录的导航条，这样就能快速到达想要修改的位置。

**Comment by PiscesDreamer** [comment]
![image](https://github.com/Kenshin/simpread/assets/81842690/78223d12-5f87-4cd1-8de2-e477c35cb3c0)

要到达插件触发器，滚动条要拉的很长

**Comment by Kenshin** [comment]
嗨，有两个解决方案：

1. https://github.com/Kenshin/simpread/discussions/1600
2. https://github.com/Kenshin/simpread/discussions/1601

都可以解决你的问题。

**Comment by PiscesDreamer** [comment]
感谢！没想到还有ios工具栏这种设计，真的太强大了，感谢作者开发的作品。

**Comment by Kenshin** [comment]
哈，小事情，解决你的问题就好。

***


方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
