### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by alab307** [Kenshin/simpread#5791]
### 需要适配的新站

网页显示不出来
https://www.electronicdesign.com/technologies/test-measurement/article/21766108/whats-all-this-femtoampere-stuff-anyhow

### 有需要请描述这个站的性质

電子設計网站

**Comment by Kenshin** [comment]
嗨，用下面的方式解决

<img width="756" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/467d38a7-3c7e-465c-b463-990053f681a3">
