### ISSUE TITLE
全文翻译插件使用 ChatGPT Web 无法返回翻译结果（7月21日因 ChatGPT API 改变造成）

### ISSUE THREAD

**Issue by OliverXian** [Kenshin/simpread#5793]
### 描述这个错误

21 July 2023:

### 复现步骤

无法返回翻译结果。
但 ChatGPT Web 中可以看到简悦送出了 New Chat 请求，对应段落也在 ChatGPT 中完成了翻译。

### 操作系统

MacOS

### 浏览器

Brave

### 发生问题的网址

https://www.irmagazine.com/

**Comment by Kenshin** [comment]
嗨，升级了 https://github.com/Kenshin/simpread-chatgpt-helper 你重新覆盖后，重启你的浏览器即可。

使用前，先测试。

<img width="598" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2537b6e2-190c-4e84-958c-0a647ef26d45">
