### ISSUE TITLE
导入logseq出错

### ISSUE THREAD

**Issue by tangmaomi** [Kenshin/simpread#5794]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/113491877/587d181d-214a-4392-b9b3-be8c104b164a)
已经登录了高级账户，仍然出现此提示

### 复现步骤

1.AA进入阅读模式
2.对选中内容进行标记
3.提示此功能为实验性功能，无法导入logseq

### 操作系统

win

### 浏览器

edge

### 发生问题的网址

www.sciencedirect.com

**Comment by Kenshin** [comment]
emmm

试试少数派的网页是否有问题。
另外，这个功能跟你的自动化或自动化辅助增强插件的设置有关系。

建议详细描述你的问题，比如使用了什么方案等。
