### ISSUE TITLE
澎湃新闻

### ISSUE THREAD

**Issue by zjh4ever** [Kenshin/simpread#5795]
### 需要适配的新站

https://www.thepaper.cn/

### 有需要请描述这个站的性质

可以在网页中进入阅读模式，但是在稍后读中打开阅读模式会显示正文解析失败

**Comment by Kenshin** [comment]
嗨，某些页面是动态加载的，所以只能通过 [配置知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 的方式实现在稍后读查看。
