### ISSUE TITLE
打开页面就会出现提示调用失败

### ISSUE THREAD

**Issue by angel126** [Kenshin/simpread#5796]
### 描述这个错误

打开浏览器标签就会出现错误
![image](https://github.com/Kenshin/simpread/assets/8450915/f93bd9c7-4432-4713-ba38-ef750a50de8f)

进入阅读模式也会出现
![image](https://github.com/Kenshin/simpread/assets/8450915/3215007a-1e2e-4e50-968e-a8ad7dace5fd)

### 复现步骤

1

### 其他相关说明

1

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://fund.eastmoney.com/gonggao/519697,AN202307201592478686.html

**Comment by Kenshin** [comment]
1. 是进入阅读模式后自动弹出这些提示？
2. 是不是你同时安装了多个简悦（ Edge 有这种方案），你可以**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。
3. 一般来说这个提示是针对自动化方面的功能，所以服务 → 自动化，停止它们。
4. 这个提示一般也用于设置了增强导出方案。
