### ISSUE TITLE
题图插件没有按照配置正常显示图片

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#5797]
### 描述这个错误

题图插件bug
前提：文章正文有图
题图插件选“正文第一个图”为题图，最终结果显示unsplash的无图页面，查看题图的 img html 标签上的 src 发现宽度变量并没有生效
![image](https://github.com/Kenshin/simpread/assets/3283023/32ab3d53-8262-4684-b7f3-bb13d69c415f)
![image](https://github.com/Kenshin/simpread/assets/3283023/89b44945-3a9f-454f-9631-2a51953e340f)

如果题图插件选“Unsplash” 则可以正常读取宽度变量，并展示 unsplash 图片
![image](https://github.com/Kenshin/simpread/assets/3283023/f0b46694-9128-41ea-9b2a-68a5f6491bef)

所以有两个问题
1. 特定条件下读取不到正文第一个图
2. 特定条件下宽度变量没有生效

还有一个问题，目前题图选项在配置上可以按照下面的优先级顺序来决定最终的题图
- 当前页题图 > unsplash
- 正文第一个图 > unsplash
那是不是可以再加一选项，我是想 当前页题图 > 正文第一个图 > unsplash 这样一个顺序，因为原文的题图一般来说肯定是最匹配当前文章的，如果原文没有题图，那正文第一个题图大概率也是比较匹配正文的，最后的unsplash基本上和正文没有关联，完全就是为了有一张图排版可能好看些的选择

### 复现步骤

具体情况如上

### 操作系统

Windows

### 浏览器

115.0.1901.183 (正式版本) (64 位)

### 发生问题的网址

https://www.yesharris.com/seo-basic/content-duplicate-issue/

**Comment by Kenshin** [comment]
😂

你用的旧版，新版在这里 https://github.com/Kenshin/simpread/discussions/2487

**Comment by iblogc** [comment]
@Kenshin 插件更新了，没有出现找不到 unsplash 图的情况，但我有一个需求不知道是插件问题还是本来就不支持
我是想不管文章第一个图尺寸够不够大，都显示为题图，我像下面这样配置就没有题图了
![image](https://github.com/Kenshin/simpread/assets/3283023/eb17616d-a491-43ae-9d44-d7f35bd5e0ba)

顺便问下，当前页题图和文章第一个图的区别是什么？
![image](https://github.com/Kenshin/simpread/assets/3283023/a11c5690-17b6-4870-bf35-c666d5c41544)

**Comment by Kenshin** [comment]
> 我是想不管文章第一个图尺寸够不够大，都显示为题图

可能有 Bug 但不确定，需要你给个 URL 瞧瞧。

> 前页题图和文章第一个图的区别是什么？

就是字面的意思，比如少数派的文章，题图和页面的第一个图是不同的图，但有些较懒的网页，这两个图是一样的。

**Comment by iblogc** [comment]
@Kenshin https://www.yesharris.com/seo-basic/content-duplicate-issue/ 这个文章

**Comment by Kenshin** [comment]
我修复了了这个问题，你在更新一次试试。

**Comment by iblogc** [comment]
更新了，可以了😆

**Comment by Kenshin** [comment]
okay 解决就好~
