### ISSUE TITLE
导出为PDF显示错误

### ISSUE THREAD

**Issue by Lusenlan** [Kenshin/simpread#5798]
### 描述这个错误

导出为PDF显示错误，调用失败

### 复现步骤

![ad1c2264b292a3f0908c8b94366fd9c](https://github.com/Kenshin/simpread/assets/104048109/9989bffe-1c40-4bed-8a4f-eaf9a5625db1)

### 操作系统

Windows

### 浏览器

Edge

### 发生问题的网址

任意网址

**Comment by Kenshin** [comment]
简悦调用 PDF 有很多方案，所以请详细说明你使用的方式，

另外，建议在 https://sspai.com/post/69972 测试，同时留意下面几个建议：

1. 试试 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
2. 使用新版方案 https://github.com/Kenshin/simpread/discussions/3887
