### ISSUE TITLE
进入阅读模式后其他浏览器扩展失效

### ISSUE THREAD

**Issue by djansun** [Kenshin/simpread#5799]
### 请描述你的建议或任何内容

进入阅读模式后 MaxAI 扩展不再生效，请问是否有解决方案？

**Comment by Kenshin** [comment]
嗨，阅读模式类产品比较特别，因为会改变页面布局，所以某些适配不那么广泛的扩展就没法使用了，比如你提到的或者某些全局键盘类扩展。

暂时没有办法，只能让它们主动支持简悦。

PS：很多知名的扩展都支持简悦。
