### ISSUE TITLE
申请适配极客学院 wiki

### ISSUE THREAD

**Issue by xhp281** [Kenshin/simpread#58]
http://wiki.jikexueyuan.com/

**Comment by Kenshin** [comment]
刚看了下，应该没有问题，但 `极客学院 wiki` 有类似 `上一页/下一页` 的功能，`1.0.1` 暂时不支持翻页的适配，下个版本 `1.0.2` 将会增加此功能。

适配后，我会通知你~

PS：1.0.2 不一定会发布，但是会放到 `测试通道`，如果对测试版感兴趣的话，[可以看看这里](http://t.cn/RKgq4hB)

**Comment by xhp281** [comment]
@Kenshin 好哒。

**Comment by Kenshin** [comment]
@xhp281 
已适配，更新方法 [请看](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E6%96%B0%E5%A2%9E)

关闭此 `issues`
