### ISSUE TITLE
[建议]能否针对 markdown 的文档，搞个浮动的目录（点击可跳转）

### ISSUE THREAD

**Issue by xjnotxj** [Kenshin/simpread#580]

**Comment by xjnotxj** [comment]
不是本身有目录哦，而是识别 h1 h2 这种，然后建个目录。

**Comment by xjnotxj** [comment]
对不起，我发现鼠标放到页面的左边竟然有自动生成的目录！平时是隐藏的。我错了。

**Comment by Kenshin** [comment]
哈哈，搞定就好，饺子多看看说明文档
http://ksria.com/simpread/docs

**Comment by xjnotxj** [comment]
@Kenshin 哈哈，我有另一个想法，如果有个配置项可以自定义目录的一级二级三级就更方便了，不然有时候自动识别目录的层级不是很正确。
比如：
h1 对应 一级目录 对应 markdown 的 `#`
h3 对应 二级目录 对应 markdown 的 `###`
h5 对应 三级目录 对应 markdown 的 `####`
