### ISSUE TITLE
对于自动同步的一些疑问

### ISSUE THREAD

**Issue by jy324** [Kenshin/simpread#5801]
### 描述这个错误

最近几天发现了几次自动同步会丢失修改，前一天修改过的标签后一天就变回去了，想知道可能是什么原因。
使用坚果云+同步助手，开机自动启动

### 复现步骤

例：
![image](https://github.com/Kenshin/simpread/assets/74438973/1cb398a1-a42c-4b53-910e-7b3ecf95964a)
在前一个配置文件中还能搜索到新添加的标签，后一个就搜索不到了，意思是修改丢失了。

### 其他相关说明

<img width="499" alt="image" src="https://github.com/Kenshin/simpread/assets/74438973/be6e459f-2265-4c63-9a93-132e33b29336">
<img width="649" alt="image" src="https://github.com/Kenshin/simpread/assets/74438973/497710ad-6b90-481e-99ae-a441700f7eab">
自动同步的设置应该是没问题的。

### 操作系统

Win11

### 浏览器

Chrome

### 发生问题的网址

无

**Comment by Kenshin** [comment]
基本上是配置文件互相覆盖造成的，比如：

1. 有多台设备的话，A 设备的新配置文件没有通过坚果云同步到 B 设备上，而 B 设备你又操作了新的数据，导致旧数据较新而覆盖新数据。

2. 单台设备的话，比如有多个 Tab 页，某个 Tab A 修改了数据，同时又修改了 Tab 选项页的数据，会造成覆盖。

注意：假设 A 和 B Tab 都加入了稍后读，同时修改 A 后再修改 B 是没问题的，但选项页的修改则不行。

细节可以看下 https://github.com/Kenshin/simpread/discussions/3768

**Comment by jy324** [comment]
好的，我试试看。😂
这几天都是在Ob里面修改稍后读数据的，以后注意一下还会不会有这样的问题。

**Comment by Kenshin** [comment]
> 这几天都是在Ob里面修改稍后读数据的

在 Obsidian 修改后 → 同步助手（写入） → `simpread_config.json` → 刷新（最好重启浏览器） → 同步助手（读取） → 最新的配置文件给浏览器。

是这样的顺序，否则就会出现配置互相覆盖的问题。

**Comment by Kenshin** [comment]
上面这个流程中，你只需要做到 **刷新（或重启浏览器）**，其它的步骤都是自动完成的。
