### ISSUE TITLE
新增功能 Markdown 定制

### ISSUE THREAD

**Issue by Testfq** [Kenshin/simpread#5803]
### 请描述你的建议或任何内容

希望增加功能：可以将内容按照已经修改的格式以markdown的形式保存在onedriver中，这样使用obsitian笔记工具，也相当于可以同步数据，最好能置顶onedriver的路径。

**Comment by Kenshin** [comment]
嗨，这个功能早在简悦 2.0 版本发布时就自带了... 😂 以下是一些相关链接。

1. [Live Editor](https://github.com/Kenshin/simpread/discussions/2852)
2. [Markdown 模板辅助增强插件](https://github.com/Kenshin/simpread/discussions/3725) 以及对应 [Markdown 模板库](https://github.com/Kenshin/simpread/discussions/2153)
