### ISSUE TITLE
思源笔记 & 知乎：仅导入一个回答

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#5805]
### 请描述你的建议或任何内容

动机：导入就像赞同，应该是针对回答的。
如果实现有困难就直接 close 吧，我没有好的想法（捂脸

**Comment by Kenshin** [comment]
嗨，你可以试试 https://github.com/Kenshin/simpread/discussions/1554  能否解决你的问题。

另外，最好方便的话，举个例子来说下。

**Comment by abd-liac** [comment]
Solved! 因为是个人认为是挺常见的情景就没例子（
感谢时间，感觉是帮助文档自己没用明白的无聊问题（

**Comment by Kenshin** [comment]
小事情，解决就好。

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
