### ISSUE TITLE
Markdown全文导出可以自定义模板吗？

### ISSUE THREAD

**Issue by ranyangpj** [Kenshin/simpread#5806]
### 请描述你的建议或任何内容

Markdown全文导出可以自定义吗？因为导出的内容需后期整理，希望将剪藏说明部分修改成：[标题](网址)这样的形式。

**Comment by Kenshin** [comment]
嗨，全文导出不支持定制化。

> 因为导出的内容需后期整理

这个需求的话，可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 在原文的基础上任意修改。
