### ISSUE TITLE
备份或同步功能

### ISSUE THREAD

**Issue by kunpeng9** [Kenshin/simpread#5808]
### 请描述你的建议或任何内容

谷歌浏览器老是默认安装在C盘，还有好多软件老是默认在C盘，快被挤爆了，前阵子使用卸载软件卸载一些以前尝试过的浏览器，谷歌浏览器内核的魔改
没注意到强力删除的扫描扫到其他地方了，不小心连带着把谷歌浏览器也给删除了
目前用的火狐浏览器

知乎盐选网页阅读体验太拉胯了，好像是之前上市附近时候买的，买了好几年了功能都没怎么优化过=使用频率不高，快过期了，赶紧保存文章
简悦保存的快1000多条，500到800还是多少来着=好几年的，稍后读全没了，怎么搞

之前发现只保存了个链接，这样的话要全部1一次性备份占用空间也不大
只是链接的话，盐选过期后就看不了了
---
没有1次性全部备份到本地的设置、之前用自动化开了设置=保存稍后读的同时保存到本地，看了一些次本地文件夹一直没有 文件
只有三五条，好像是之前手动保存到本地的，不是自动化的
同步助手没有自动保存到本地，不知道哪里有问题

谷歌浏览器再安装简悦插件登录不上去，dropbox网页老是刷新中，里面没有稍后读的备份啊，全没了！
查看数据统计只有几十条

简悦同步助手能不能增加全部导出功能=可导入谷歌浏览器收藏夹的，bookmarks.html
导入其他浏览器 火狐浏览器的书签
![图片](https://github.com/Kenshin/simpread/assets/44609485/32952956-425d-4e3a-b709-e2e0158bde87)

**Comment by Kenshin** [comment]
没理解你的问题…

你没有使用同步助手的自动同步或者定期将配置文件保存到坚果云（或 Dropbox） 吗？

只要上述任意一种都不会发生你说的问题…

还有，如果使用了同步助手的话，同步助手或者你设置的网盘都有历史记录功能…

- https://github.com/Kenshin/simpread/discussions/5748

-  https://github.com/Kenshin/simpread/discussions/3940
