### ISSUE TITLE
标注无法导入到Obsidian

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#5809]
### 描述这个错误

不管是手动导入标注到Obsidian还是加入稍后读后自动导入全部是不成功的

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/3283023/66dfb7b1-69f9-4500-8193-49deffb3270c)
![image](https://github.com/Kenshin/simpread/assets/3283023/bcb19564-d10f-4782-883f-e99fb64c3c11)
之前无法导出，后面发现是插件配置有错（但我之前一直是这样可以正常导出标注）
![image](https://github.com/Kenshin/simpread/assets/3283023/97e6c604-5ddb-4ccc-8ada-de15eb6c5812)
后面我直接把这行地址配置清掉了，使用默认的手动导入标注是显示成功了，但在Obsidian并没有找到这个标注文件
![image](https://github.com/Kenshin/simpread/assets/3283023/0ee22892-2fd9-4b15-b7a5-feb3c92be8d7)
![image](https://github.com/Kenshin/simpread/assets/3283023/4d7d8769-6a53-4896-86bf-fe7d10bf77f2)

另外，我插件里的配置同步助手的配置是不是有冲突啊，以前我感觉导出时用的是同步助手的配置，因为我不启动Obsidian也能导入全文到Obsidian
![image](https://github.com/Kenshin/simpread/assets/3283023/6365a501-7c84-4928-8084-b8f48a0cab30)
![image](https://github.com/Kenshin/simpread/assets/3283023/1f243c5b-70de-4d90-9bb9-475eb2d0a259)

### 操作系统

Windows

### 浏览器

Microsoft Edge 版本 115.0.1901.188 (正式版本) (64 位)

### 发生问题的网址

https://sspai.com/post/81470

**Comment by Kenshin** [comment]
<img width="617" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f9689529-200c-49d6-a355-e5c103eefe93">

需要改为

<img width="608" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bdb77b77-29b0-4de4-be1a-feb9463e49a9">

> 后面我直接把这行地址配置清掉了，使用默认的手动导入标注是显示成功了

没理解这段话。

> 我插件里的配置同步助手的配置是不是有冲突啊，以前我感觉导出时用的是同步助手的配置

导入到 Obsidian 有很多方案，可以不用 SimpRead Unread Sync（ Obsidian 插件）

> 因为我不启动Obsidian也能导入全文到Obsidian

如果使用导入到 Obsidian 插件的话，就必须要通过打开 Obsidian 才能导入，否则可以通过同步助手。（也就是不用打开 Obsidian）

**Comment by iblogc** [comment]
![image](https://github.com/Kenshin/simpread/assets/3283023/37386d01-627e-454e-9135-b7cfaadd3cb3)这个已经删除了，也就是现在是默认的http://localhost:7027

![Uploading image.png…]()
那如果我同步助手也配置，SimpRead Unread Sync也配置了（并且Obsidian 启动了）导入时会不会有冲突

最关键的问题是，现在手动导入标注显示成功，但实际并没有成功，标注的md文件都没生成

**Comment by Kenshin** [comment]
> 这个已经删除了，也就是现在是默认的http://localhost:7027/

没太理解，你需要按下图所示设置（如已这么设置，可忽略我的疑问，不用回复）

<img width="616" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3df01988-c39a-4eb4-a1e6-1cb9b9a0496d">

> 最关键的问题是，现在手动导入标注显示成功，但实际并没有成功，标注的md文件都没生成

你是通过下图方式导入的？如果不是的话，就按照下图所示方式手动导入一次

<img width="280" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dc1df0bf-d22b-4af3-a186-b6e3bcc9d30d">

***

提示成功，但没有找到导入，也可能是下面的问题造成的。

导入的文件夹跟你理解导入的文件夹可能不一样，比如下图所示的文件夹名称

<img width="604" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8f79115f-4ecb-43fa-bd54-7da380050fba">

与 Obsidian 不一样

<img width="286" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/63dfc962-b5e2-4463-b2dd-98822d7cfb92">

***

另外，如果 Markdown 模板辅助增强插件可以看到标注，说明标注模板没问题。

**Comment by iblogc** [comment]
解决了就是第一个地址问题，我以为留空就是默认的地址和端口😅

**Comment by Kenshin** [comment]
> 解决了就是第一个地址问题，我以为留空就是默认的地址和端口😅

..... 我就说你之前的描述比较奇怪嘛... 解决就好。
