### ISSUE TITLE
聚焦模式右下角控制栏在某些条件下无法显示

### ISSUE THREAD

**Issue by PunkaD** [Kenshin/simpread#581]
发现CSDN 的聚焦模式 提取的网页内容 和 印象笔记的剪藏插件在一般网页上的效果一致,所以想问下,CSDN的聚焦模式能不能把聚焦提取出的内容转存?

**Comment by Kenshin** [comment]
聚焦模式下可以导出到印象笔记。

**Comment by PunkaD** [comment]
> 聚焦模式下可以导出到印象笔记。

具体怎么操作呢?
右下角的工具按钮是灰色的,聚焦区域外点击会退出聚焦

**Comment by Kenshin** [comment]
抱歉，近期在休假。
不应该是灰色的…

你用的是什么版本（简悦/浏览器/操作系统）？还有方便的话，截图看看。

你可以看看 [说明文档]()

**Comment by PunkaD** [comment]
> 抱歉，近期在休假。
> 不应该是灰色的？
> 
> 你用的是什么版本（简悦/浏览器/操作系统）？还有方便的话，截图看看。
> 
> 可以你看看[说明文档](http://ksria.com/simpread/docs/#/%E5%AF%BC%E5%87%BA%E5%88%B0%E7%94%9F%E4%BA%A7%E5%8A%9B%E5%B7%A5%E5%85%B7)

![Snipaste_2019-09-21_20-28-43](https://user-images.githubusercontent.com/26647073/65373322-81b42d80-dcae-11e9-8369-cab5e2f80e24.png)
如图示,我是用的是简悦的chrome插件

**Comment by Kenshin** [comment]
这个应该是控制栏被挡住了…

你试试其它页面，如 https://sspai.com/post/52492

进入聚焦模式后再看看。

**Comment by PunkaD** [comment]
在我关闭了可能会影响页面的插件和脚本之后,目标页面也是同样的问题,只有简悦插件被启用了,chrome版本76.0

**Comment by Kenshin** [comment]
截图的问题是 z-index 造成的，你可以修改这个值，简悦支持 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

PS：正常不应该有这个问题，极个别页面曾出现过，我在外面休假，没办法棒你解决。
如果米会些 CSS 久可以解决。

**Comment by PunkaD** [comment]
我这边几乎所有网页都复现了这个问题,我发现我有一个脚本浮现了出来,他的z-index是9999999999,等大佬有时间了再搞吧

**Comment by Kenshin** [comment]
这个 z-index 是哪个脚本？应该是它的问题。

**Comment by PunkaD** [comment]
并不是,我禁用了简悦之外的所有脚本和插件后,仍然有这个问题

**Comment by Kenshin** [comment]
这不应该的，你可以试试，重置简悦，然后在隐藏模式下开启。

简悦没有设置过这个 z-index 属性值

**Comment by PunkaD** [comment]
非常遗恨,进行数据清除和重新安装后依旧存在这个问题,暂时不打扰大佬休假了,等大佬有时间再解决吧

**Comment by Kenshin** [comment]
通过自定义样式，添加如下代码：

```
sr-rd-crlbar.controlbar {
    z-index: 2147483647!important;
}

```

再试试？

**Comment by liangpengjie** [comment]
- 我也有这个问题,重装后也不起作用，把这个 `z-index: 2147483647!important;` 加入自定义样式也不行 
- 另外还有个问题，隐藏任意元素不小心把
![image](https://user-images.githubusercontent.com/38686607/68096222-526a2080-feea-11e9-951b-6c0f8a494d41.png)这个也隐藏了，该怎么恢复，找了半天没找到，只好又重装了一遍

**Comment by Kenshin** [comment]
@liangpengjie 
你给出的截图，应该是可以使用导出的情况。

**Comment by liangpengjie** [comment]
抱歉描述不清楚，我最重要的问题也是在所有页面聚焦模式下
![image](https://user-images.githubusercontent.com/38686607/68821185-91f1f300-06c8-11ea-8643-2b366f6ca672.png)
右下角两个按钮是被遮罩层遮罩的，重装试过了，也加入了这行代码，还是不起作用
![image](https://user-images.githubusercontent.com/38686607/68821246-c796dc00-06c8-11ea-8eee-af6d01fc1d16.png)
麻烦有时间看一下
环境：
Chrome 浏览器，Mac 10.15

**Comment by Kenshin** [comment]
@liangpengjie

这就很奇怪了... 应该是其它扩展引起的，你可以这样：

- 允许 简悦 在 `隐身模式` 下使用；
- 不允许其它任何扩展在 `隐身模式` 下使用；

看看是否还有问题？

**Comment by liangpengjie** [comment]
还是不可以，我刚禁用了其他所有拓展，打开隐身模式，然而还是不起作用

**Comment by PunkaD** [comment]
![Snipaste_2019-11-14_14-56-22](https://user-images.githubusercontent.com/26647073/68833675-063f8d00-06ef-11ea-808c-f5e222fa0c91.png)
![Snipaste_2019-11-14_14-56-31](https://user-images.githubusercontent.com/26647073/68833700-135c7c00-06ef-11ea-8b88-6033c01f93e0.png)
https://www.ifanr.com/app/1281014
这个页面下, 感觉聚焦模式的工具栏优先级还在网页工具栏之下

**Comment by PunkaD** [comment]
我关闭了聚焦模式,控制栏一直显示的开关后,控制栏开始正常显示了

**Comment by Kenshin** [comment]
@PunkaD 
谢谢你的反馈，我已经能正常复现这个问题，这是个 Bug 下个版本会修复 或 看看能否通过其它途径先行修复。

具体哪种方案，明天通知你。

@liangpengjie

请试试 https://github.com/Kenshin/simpread/issues/581#issuecomment-553753487 这个方式，即：

![image](https://user-images.githubusercontent.com/81074/68849802-b2906c00-070d-11ea-992c-692c3aa99ca6.png)

**Comment by liangpengjie** [comment]
@Kenshin 不起作用，还是这样的

**Comment by Kenshin** [comment]
@liangpengjie 

这不应该... 你确定没有（在隐身模式下）安装了其它扩展？

而且从你给出的截图上看，这个触发器的样式错了，这应该是别其它扩展修改导致的。

你的 Chrome 版本是什么？

**Comment by liangpengjie** [comment]
![image](https://user-images.githubusercontent.com/38686607/69226720-9122fa80-0bbb-11ea-856e-a1da4da844f1.png)
这是火狐浏览器，我刚下的，里面并没有任何拓展，结果也是这样，Chrome 的版本是`78.0.3904.97（正式版本） （64 位）`

**Comment by Kenshin** [comment]
@liangpengjie 

我好像之前已经说过了，这是个 Bug 按照下图的设置取消即可

![image](https://user-images.githubusercontent.com/81074/69300611-b4e35080-0c4e-11ea-8900-4fcb8b200121.png)

或者加入如下的 CSS 样式

```
fab-bg {
    z-index: 2147483648!important;
}
```

***

抱歉，之前一直无法重现这个问题，一直到 @PunkaD 的提示才发现。

**Comment by liangpengjie** [comment]
谢谢，改好了，一直改成阅读模式的了，😶，麻烦大佬了

**Comment by Kenshin** [comment]
@liangpengjie 

搞定就好，抱歉给你添了不少麻烦... 这个问题只能下个版本修复。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

此问题已经被解决了

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
