### ISSUE TITLE
翻译界面

### ISSUE THREAD

**Issue by 1197083908** [Kenshin/simpread#5812]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/141150456/5dcb7f27-7ca3-4327-8f23-d2de140d3dd9)
被控制界面所遮挡，完全无法使用，
狗东西

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/141150456/b312c671-c41c-4649-a30d-548de9189dd9)

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://www.cellsignal.com/products/primary-antibodies/rip-d94c12-xp-rabbit-mab/3493

**Comment by Kenshin** [comment]
😂 试试将页面缩小

<img width="270" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a1d2c04e-c897-4ac6-a479-2f7f39ed5ef4">

PS：你的分辨率有多大？
