### ISSUE TITLE
阅读模式中设置了主题，但是不生效

### ISSUE THREAD

**Issue by choko-oni** [Kenshin/simpread#5813]
### 描述这个错误

<img width="907" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/2d61579c-4edf-45e7-8278-751f16c8c2ad">
<img width="1422" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/94b12e55-3c38-4d12-b823-943b311db57e">
在阅读模式的偏好设置中设置了，再次进入阅读模式之后，选择的主题色也不生效
<img width="614" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/c65a7808-ec3f-40b9-af17-4a84ad9c31f8">

### 复现步骤

1.设置了主题颜色
2.进入阅读模式
3.主题色不生效

### 操作系统

macOS 

### 浏览器

Google Chrome 111.0.5563.64（正式版本） (arm64)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/643861125

**Comment by Kenshin** [comment]
是不是使用了暗色模式？如果是的话  https://github.com/Kenshin/simpread/discussions/2992

**Comment by choko-oni** [comment]
是的，系统设置了暗色模式，但是在阅读模式中，我想要使用白色的主题

**Comment by choko-oni** [comment]
<img width="892" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/f6ae4bdf-f176-48b4-8181-80cffb428cc1">
z在设置里我是关掉了“跟随系统主题”这一选项的，但是设置仍然不生效

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5813#issuecomment-1663174215

确实如你所说，我考虑优化下。但... 你的需求有点奇怪。

> 是的，系统设置了暗色模式，但是在阅读模式中，我想要使用白色的主题

这样不累眼睛吗？ 😂

**Comment by choko-oni** [comment]
谢谢，如果能够优化的话不胜感激，买了终身会员作为小小的支持~
简悦很好用，希望它能够做的更好！

主要是默认打开是这样：
<img width="1396" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/dda50998-28e0-42fe-ab65-cb134bb8c618">

期望能够以我的设置作为默认选项：
<img width="1430" alt="image" src="https://github.com/Kenshin/simpread/assets/10694331/5e844bcd-80e4-451c-b009-89fee9e5c27a">

主要是习惯dark模式的系统/IDE和浏览器啦………

**Comment by Kenshin** [comment]
我确认了，这算是个 Bug：

系统暗色模式 + 简悦取消随系统暗色模式的情况下，简悦无法更改主题。

***

我已经修复了这个错误，目前 模仿 Safari 阅读模式样式 为 1.0.8 版。

- 如果没有使用同步助手的自动同步的话，直接安装 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 后重启浏览器。
- 如果已经使用同步助手的自动同步的话，使用 https://www.yuque.com/kenshin/simpread/fcw60u 升级。

我先关闭这个 Issues 了，有任何问题可随时再讨论。

***

> 如果能够优化的话不胜感激，买了终身会员作为小小的支持~

谢谢支持。

**Comment by choko-oni** [comment]
动作好快，感谢！！！！

**Comment by Kenshin** [comment]
okay 解决你的问题就好~
