### ISSUE TITLE
在网页notion中进入简悦阅读所模式遇到的问题

### ISSUE THREAD

**Issue by atgnaw** [Kenshin/simpread#5814]
### 描述这个错误

1. 无法跨‘块’做标注。
2. 在右边栏中修改标题，描述，备注这一个界面，按退格键没有反应无法修改文本，在其他网页中打开阅读模式没有此问题。
3. 在notion中新建一个文本页面，似乎只要文字内容很少，进入阅读模式就会跳出“检测到文本获取异常，是否重新获取”

### 复现步骤

在我的环境中，以上所有问题都可以通过新建一个文本页面来复现

### 操作系统

windows 11

### 浏览器

Chrome 版本 115.0.5790.110（正式版本） （64 位）

### 发生问题的网址

notion.so

**Comment by Kenshin** [comment]
> 问题1

需要提供 URL

> 问题2

可能被 Notion 劫持了，之前没有这种问题，但也有办法解决，在稍后读中修改。

> 问题3

这不是问题，而是一种提示。

**Comment by atgnaw** [comment]
这是问题1的链接
 https://www.notion.so/test-d631543b98f54ddfab57f57d0c641216?pvs=4
并且导出到稍后读，一样无法跨”块“标注

**Comment by Kenshin** [comment]
> https://www.notion.so/test-d631543b98f54ddfab57f57d0c641216?pvs=4

这个 URL 无法访问~

**Comment by atgnaw** [comment]
我偶然发现如果选择发布这个页面，从发布的这个链接查看并进入阅读模式是可以进行跨块标注。但一旦复制副本到自己的notion打开则又不能跨块标注。
随后发现在notion中进入阅读模式进行标注在选择文本时一定会触发文本输入符号出现在当前块中，然后不管如何拖拉鼠标都无法进行跨块选取文本。并且就算把当前页保存到稍后读，在稍后读中尝试标注一样无法跨越块。。。
但，在notion中如果锁定当前页面，使其无法编辑，则在阅读模式下进行标注时无法出现文本输入符，就能绕开上述问题。

”4.在‘块’中按shift+Enter,进行同块换行操作，进入阅读模式后不会显示换行。“   这个问题依然存在。

链接：[https://juicy-armadillo-170.notion.site/test-d631543b98f54ddfab57f57d0c641216?pvs=4](url)

**Comment by Kenshin** [comment]
## 现象总结

1. 从发布的这个链接查看并进入阅读模式是可以进行跨块标注
2. 变成自己的 Page 可以进行跨块标注。（锁定状态）

非锁定状态确实有问题。

## 问题分析

而这个功能跟你提到的其它问题属于同一类问题，即：Notion 改版后对键盘、鼠标操作有了更霸道的「权限锁定」，当然这种方式对 Notion 没有任何问题。

但在阅读模式下，确实有问题。

## 解决方案

如果要标注时，使用简悦的 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 方案，将当前页变成本地快照，然后就完全没有这种问题了。

操作步骤如下：

<img width="513" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f556970d-88e8-435d-be4f-d3b69df94606">

<img width="1445" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/de3e5662-2e72-4e54-b86d-1deeb9377d06">
