### ISSUE TITLE
导出 PDF 的使用疑问

### ISSUE THREAD

**Issue by wang536542** [Kenshin/simpread#5816]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/77597683/7f54a34a-7499-4eef-9ee9-f04389c81dcb)

### 复现步骤

点开网页https://medium.com/authority-magazine/cheung-gary-lam-of-franklinwh-energy-storage-on-how-they-are-breaking-the-cycle-of-non-renewable-543836865987
点击聚焦模式
导出PDF 或者离线HTML

### 操作系统

WIN11

### 浏览器

Chrome

### 发生问题的网址

https://medium.com/authority-magazine/cheung-gary-lam-of-franklinwh-energy-storage-on-how-they-are-breaking-the-cycle-of-non-renewable-543836865987

**Comment by Kenshin** [comment]
请问使用了哪种 PDF 导出方案？

另外，是否安装了这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U

**Comment by wang536542** [comment]
没有安装这个插件，刚安装完了重试还是一样的问题。
简悦软件版本为 1.2.0

**Comment by Kenshin** [comment]
1. 使用了哪种 PDF 方案？
2. 试试 https://sspai.com/post/69972 是否可以导出 PDF
3. 如果使用了同步助手的话，还有个 https://github.com/Kenshin/simpread/discussions/3887 方案，你可以试试。

**Comment by wang536542** [comment]
您提供的这个网址https://sspai.com/post/69972 可以导出 PDF

但是这个反馈的网址还是报同样的错，你可以试试
https://medium.com/authority-magazine/cheung-gary-lam-of-franklinwh-energy-storage-on-how-they-are-breaking-the-cycle-of-non-renewable-543836865987

**Comment by Kenshin** [comment]
我这边没有问题，使用了 **同步助手的 PDF 基础打印方案**。

[Cheung (Gary) Lam Of FranklinWH Energy Storage On How They Are Breaking the Cycle of Non-Renewable Consumption _ by Monica Sanders _ Authority Magazine _ Jun_ 2023 _ Medium.Medium.pdf](https://github.com/Kenshin/simpread/files/12271877/Cheung.Gary.Lam.Of.FranklinWH.Energy.Storage.On.How.They.Are.Breaking.the.Cycle.of.Non-Renewable.Consumption._.by.Monica.Sanders._.Authority.Magazine._.Jun_.2023._.Medium.Medium.pdf)

所以...

1. 你使用了哪种 PDF 导出方案（这很重要，而且我应该问了三次了...
2. 如果你使用了同步助手的自动同步方案，则需要使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
