### ISSUE TITLE
插件在 repainter.app 这个网页会导致显示异常

### ISSUE THREAD

**Issue by chinnsenn** [Kenshin/simpread#5817]
### 描述这个错误

开启插件后，https://repainter.app 会显示空白

### 复现步骤

开启插件
<img width="2127" alt="Screenshot 2023-08-04 at 15 33 03" src="https://github.com/Kenshin/simpread/assets/13096352/ec71f2ad-a72d-4028-96a2-2f8f7e84bb4c">
关闭插件
<img width="2127" alt="Screenshot 2023-08-04 at 15 33 12" src="https://github.com/Kenshin/simpread/assets/13096352/4bf4c2b4-c22c-40c1-9db4-859279e65041">

### 操作系统

macOS

### 浏览器

Arc Browser Version 1.2.0 (40514) 和 Chrome Version 115.0.5790.114

### 发生问题的网址

https://repainter.app

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/2347 提到的解决方案。
