### ISSUE TITLE
果壳、简书需要更新

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Kenshin/simpread#582]
例如
https://www.jianshu.com/p/f59547fce211
https://www.guokr.com/article/61603

**Comment by Kenshin** [comment]
嗨，不好意思，前阵子在休假。
你说的这两个站都可以自动进入阅读模式。

请问你的简悦版本是多少？另外，也可以通过更新
选项页 → 共通 → 手动同步适配列表 来手动更新。

***

PS：查看最新的适配列表是否更新的技巧，选项页 → 关于 → 截至到目前为止，简悦已经适配了 **318** 类网址。

说明是最新的适配列表。

***

如果上述仍无法解决你的问题，试着 **清除全部数据** 或 **重新安装**。

**Comment by mgdgfbhevdyeh** [comment]
fixed
