### ISSUE TITLE
阅读模式无法正常显示粗体

### ISSUE THREAD

**Issue by ranyangpj** [Kenshin/simpread#5820]
### 描述这个错误

这个网址进入阅读模式后粗体等格式都没法正常显示

### 复现步骤

进入阅读模式后，粗体等格式没有显示

### 操作系统

window11

### 浏览器

chrome

### 发生问题的网址

https://mp.weixin.qq.com/s/X5Hzq8iKfobOA9DtV0vD2A

**Comment by Kenshin** [comment]
试试更换不同的主题。

另外，公众号因为使用了非正常的方式也会被简悦「删除」错误的样式。

**Comment by ranyangpj** [comment]
换了个safari的阅读模式样式插件好了

**Comment by Kenshin** [comment]
okay 解决就好～
