### ISSUE TITLE
md + asset 格式是不是一定要按照同步助手才可以导出

### ISSUE THREAD

**Issue by ranyangpj** [Kenshin/simpread#5821]
### 请描述你的建议或任何内容

在导出目录里面设置了本地目录，可是还是显示导出失败，是导出目录设置错了还是必须有同步助手才能导出？建议格式导出不要跟同步助手绑定吧，需要同步的情况下再 去设置同步。

**Comment by Kenshin** [comment]
md + assets 是必须要使用同步助手才能使用的功能，因为需要将图片保存到你指定的文件夹。

你可能需要安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 这个插件。

PS：如果使用了同步助手的自动同步功能，则需要通过 https://www.yuque.com/kenshin/simpread/fcw60u 安装。

> 建议格式导出不要跟同步助手绑定吧

同步助手不仅只是负责「同步」，还有导出和其它功能等，你可以理解内置一个「服务器」

因为要将图片保存到本地，所以需要通过同步助手才能完成。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
