### ISSUE TITLE
导出思源笔记的问题。

### ISSUE THREAD

**Issue by nangd** [Kenshin/simpread#5822]
### 描述这个错误

已经按照教程设置，但是在导出的时候提供需要授权并设置保存的笔记本。

### 复现步骤

<img width="462" alt="image" src="https://github.com/Kenshin/simpread/assets/105619248/c6ed1dd8-f6e0-42f3-821f-50f08f3553e2">
<img width="693" alt="image" src="https://github.com/Kenshin/simpread/assets/105619248/7a4acd7d-1e62-42b2-aafe-da9b34e561b5">

### 操作系统

macos

### 浏览器

chrome

### 发生问题的网址

google.com

**Comment by Kenshin** [comment]
第二个图，点导出可以使用吗？

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
