### ISSUE TITLE
Obsidian升级到1.2或1.3版本之后，网页内容保存到OB失败

### ISSUE THREAD

**Issue by alic234** [Kenshin/simpread#5824]
### 描述这个错误

Obsidian升级到1.2或1.3版本之后，网页内容保存到OB失败；回退到1.1版本之后保存成功，是不是版本不兼容？

### 复现步骤

升级OB之后出现的问题：
进入阅读模式之后，保存全文到OB提醒保存失败（1.2及1.3版本都是）
配置的是OB配置库
回退到OB1.1版本，保存成功

### 操作系统

windows

### 浏览器

edge 112.0

### 发生问题的网址

https://sspai.com/bullet/1690877465

**Comment by Kenshin** [comment]
😂 

你有多久没升级 Obsidian 这是个老 Bug 了，早就解决了。

解决方案 https://github.com/Kenshin/simpread/discussions/5601

PS：重新安装或新安装的 Obsidian 不会存在这个错误。
