### ISSUE TITLE
请问一进入阅读模式就提示手动框选是怎么回事？

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5825]
请问一进入阅读模式就提示手动框选是怎么回事？

https://github.com/Kenshin/simpread/assets/61960179/a11f7ea6-3c7c-4408-909c-64ff16b2fe84

_Originally posted by @eliotang in https://github.com/Kenshin/simpread/discussions/3340#discussioncomment-6648786_

**Comment by Kenshin** [comment]
@eliotang

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

其实你提问的地方就是答案... https://github.com/Kenshin/simpread/discussions/3340#discussioncomment-2020312

把手动确认关闭以及按照下图所示设置

<img width="871" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b8ac367f-8df3-4da1-a7e4-01b6d032f85f">

**Comment by eliotang** [comment]
我是这样子设置的，但每次进入这个链接的阅读模式都得重新框选。而且手动确认框在阅读模式无法显示在上方，只有退出阅读模式才能手动确认。

**Comment by Kenshin** [comment]
> 但每次进入这个链接的阅读模式都得重新框选

提供 URL，理论上这是正常的。

因为：

你的这个 URL 应该没有适配，但你还主动进入阅读模式，所以才有视频的效果。

另外，测试下 https://sspai.com/post/69972 是否有这个问题？如果没问题的话，就是我说的方式。

**Comment by eliotang** [comment]
少数派链接没问题，好的了解了，谢谢

**Comment by Kenshin** [comment]
okay 有需要的话，也可以提供 URL 这样判断更稳妥。
