### ISSUE TITLE
代码段增强插件: Tab长度太长

### ISSUE THREAD

**Issue by xihale** [Kenshin/simpread#5829]
### 请描述你的建议或任何内容

e.g.: https://www.cnblogs.com/hyfhaha/p/12936009.html
希望可以自己设置Tab的长度以及显示空格

**Comment by Kenshin** [comment]
嗨，谢谢建议，不错。

但代码段高亮的功能有点麻烦，至今也没有想好完整的解决方案 😂

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
