### ISSUE TITLE
阅读模式发送到邮箱/保存到kindle失败——提示为实验性功能

### ISSUE THREAD

**Issue by ll1zt** [Kenshin/simpread#5836]
### 描述这个错误

http://ksria.com/simpread/docs/#/%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1
作者你好，我根据简悦在雀语上的文档（链接如上）在同步助手以及简悦的扩展端设置好了邮件服务和发送到kindle，在进入到阅读模式后，点击导出——发送到Emai 以及 保存——保存到kindle均失败并提示为实验性功能

### 复现步骤

![8f8e48d87548b51d28223346486a83c](https://github.com/Kenshin/simpread/assets/130381763/8f0de6e4-b836-4177-9807-523a2d59cd05)

![8f8e48d87548b51d28223346486a83c](https://github.com/Kenshin/simpread/assets/130381763/a0ff7a7f-2bce-422b-8138-dbb341276a4d)

### 其他相关说明

尝试多个不同网站的文章，都为同样的问题。
尝试过在浏览器端删除简悦扩展，重新下载后导入配置没有解决

### 操作系统

windows

### 浏览器

brave

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
建议使用 QQ 邮箱测试，不要使用 Gmail 等邮箱。

**Comment by ll1zt** [comment]
> 建议使用 QQ 邮箱测试，不要使用 Gmail 等邮箱。

使用的的确是qq邮箱🤣

**Comment by Kenshin** [comment]
那就是相关配置有问题了 😂

一般是密码的问题，SMTP 不是你的 QQ 密码。如果还不行的话，建议把相关设置都截图看下。

**Comment by ll1zt** [comment]
我清空了配置，重新生成了stmp码，再按照步骤来问题解决了，之前可能是同步带来的配置导致了这个小问题。

**Comment by Kenshin** [comment]
哈，解决就好，我关闭这个 Issues 了。

下次也可以试试简悦的 [Log 日志系统](https://simpread.pro/docs/#/Sync?id=%e6%97%a5%e5%bf%97)

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)
