### ISSUE TITLE
全文和划词翻译输出的语言

### ISSUE THREAD

**Issue by turboted** [Kenshin/simpread#5837]
### 请描述你的建议或任何内容

目前全文和划词翻译 显示出来的都是简体中文，能否增加输出为繁体中文选项呢，谢谢

**Comment by Kenshin** [comment]
嗨

全文翻译可以，因为可以 [定制 Prompt](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-6193764)

但划词翻译暂时没有这个功能。
