### ISSUE TITLE
阅读模式里width=0被无视的排版问题

### ISSUE THREAD

**Issue by sasasqt** [Kenshin/simpread#5839]
update: 纯粹模式开启后会导致以下问题：

### 描述这个错误

在阅读模式下，原本width=0 的元素会无视该参数

可能的解决方案：preprocessing 删除所有width=0的元素

### 复现步骤

1. 访问 https://mp.weixin.qq.com/s?__biz=Mzg2OTY0MDk0NQ==&mid=2247503594&idx=1&sn=7962f283bd87e27fc00aa6dd62c8c9ab
  1.1 其中导致问题的源码： ![image](https://github.com/Kenshin/simpread/assets/56587914/b67780d1-5e3b-41d7-9490-78f63f62c910)
2. 进入阅读模式后导致排版问题
![image](https://github.com/Kenshin/simpread/assets/56587914/e63138ca-2c4a-4fd9-95f5-fa03a5e1a7e3)
![image](https://github.com/Kenshin/simpread/assets/56587914/74c79847-2931-4f54-a452-9cce0b18e6ad)

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

 https://mp.weixin.qq.com/s?__biz=Mzg2OTY0MDk0NQ==&mid=2247503594&idx=1&sn=7962f283bd87e27fc00aa6dd62c8c9ab

**Comment by Kenshin** [comment]
确实如此，一般仅见于公众号。

提供了很好的思路，哟看看如何优化。

**Comment by Kenshin** [comment]
嗨，这个问题已经解决了。

更新适配规则即可 https://github.com/Kenshin/simpread/discussions/2870

留意官方适配规则生效才行

<img width="477" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/51c1bb61-0835-4d92-b06d-168f853280cf">
