### ISSUE TITLE
标点'后带空格的显示bug

### ISSUE THREAD

**Issue by sasasqt** [Kenshin/simpread#5844]
### 描述这个错误

阅读模式在'标点后添加了一空格
![image](https://github.com/Kenshin/simpread/assets/56587914/eec1ebb5-b0a8-487b-812e-cde790814423)

### 复现步骤

见上

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

https://www.davidsbatista.net/blog/2017/11/12/Maximum_Entropy_Markov_Model/

**Comment by Kenshin** [comment]
okay 解决就好，因为中文和英文布局优化方案不一样，所以如果经常使用英文的话，就使用此插件。
