### ISSUE TITLE
B 站希望離線保存時能存大圖

### ISSUE THREAD

**Issue by Jiang10086** [Kenshin/simpread#5848]
### 需要适配的新站

以 [此嗶哩嗶哩專欄](https://www.bilibili.com/read/cv25390002) 為例，[原圖](https://i0.hdslb.com/bfs/article/c7c5312796530e0c8fc7e665e1c1971bc886c8b2.png) 有 6464px 寬，而保存的 textbundle 裡的圖片只有 1256px 寬，雖然我知道這是由於網頁原本就加載的小圖，但有沒有可能簡悅能自動替換成原圖呢？

### 有需要请描述这个站的性质

大家發文章的地方

**Comment by Kenshin** [comment]
okay 我知道是什么问题了。

比如你给的例子中的图片是 `https://i0.hdslb.com/bfs/article/c7c5312796530e0c8fc7e665e1c1971bc886c8b2.png@1256w_1470h_!web-article-pic.avif` 多余的 `@1256w_1470h_!web-article-pic.avif` 删除它后就是大图了。

但给你的素材太少了，方便的话，可以多给一些，我做参考。

另外一点：如果想要简单实现的话，在阅读模式下就显示这些原图，但这样可能会让页面加载变慢（毕竟图片很大），而无法在导出前改为原图。

**Comment by sasasqt** [comment]
希望支持+1
哔哩哔哩专栏至少支持如下格式：
![image](https://github.com/Kenshin/simpread/assets/56587914/9d719d99-f512-4f30-8da3-0042308e3321)
哔哩哔哩专栏图片的架构：https://www.bilibili.com/read/cv22543150/
> 后来，我们采用 HTML picture 标签提供若干 source 元素，并让浏览器根据其支持的图片格式自动选择对应的 URL：优先请求 AVIF 格式；如果浏览器不支持，则降级到 WebP；对于极少数不支持 WebP 的浏览器，则进一步降级到 JPG/PNG 格式。
> ![image](https://github.com/Kenshin/simpread/assets/56587914/616b9ba5-6562-46d7-b606-e8668aa8dd33)

格式大概是: 原始文件格式@*.[avif|webp|jpg]

**Comment by Kenshin** [comment]
@sasasqt 

Cool 我考虑下优化方案。

PS：你近期帮忙提了不少有意义的 Issues 非常感谢 😄 👍

**Comment by Kenshin** [comment]
嗨，适配列表已更新，解决了此 Issues 更新方式 https://github.com/Kenshin/simpread/discussions/2870 并留意下图的说明

<img width="885" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cfff1dc4-4a8c-4a13-9fe5-c9f5aadaa950">
