### ISSUE TITLE
授权服务器疑似出问题

### ISSUE THREAD

**Issue by nsdont** [Kenshin/simpread#585]
![image](https://user-images.githubusercontent.com/1725434/65864976-4ba93480-e3a5-11e9-8a35-a0a4b41cd4ec.png)

如图，我点击印象笔记授权一直失败

**Comment by Kenshin** [comment]
嗨，后台的服务器配额满了…
明天恢复此功能。

**Comment by Kenshin** [comment]
嗨，此功能已恢复，我将关闭 issues ~
