### ISSUE TITLE
机核的文章转码后没有图片

### ISSUE THREAD

**Issue by wonderful259** [Kenshin/simpread#5850]
### 描述这个错误

https://www.gcores.com/articles/109379
转码后显示不了图片

### 复现步骤

阅读文章的时候，直接点击简悦按钮转码。

### 操作系统

macOS

### 浏览器

Edge

### 发生问题的网址

https://www.gcores.com/articles/109379

**Comment by Kenshin** [comment]
嗨，需要安装 https://simpread.ksria.cn/sites/details/68hAvoc6pC 这个适配规则。
