### ISSUE TITLE
关于同步配置文件的问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5854]
![image](https://github.com/Kenshin/simpread/assets/104048109/abe86bdd-5e4f-459a-945c-0acfa1f08a90)
请问配置文件已最新的为主吗？，之前的配置文件可以删掉吗？为啥配置文件的文件大小没啥规律，一个大一个小

_Originally posted by @Lusenlan in https://github.com/Kenshin/simpread/discussions/5853_

**Comment by Kenshin** [comment]
@Lusenlan

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

使用同步助手 + 自动同步后 `simpread_config.json` 才是您的配置文件。（看你的文件夹结构应该是这种）

除此之外的文件应该是手动导出的配置文件。

**Comment by Lusenlan** [comment]
那这些手动导出的可以删掉吗？我想让这个文件夹简洁些



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2023年8月16日(周三) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 关于同步配置文件的问题 (Issue #5854)




 
@Lusenlan
 
我帮你新建了一个 Issues，并删除了原来位置的内容。
 
 
使用同步助手 + 自动同步后 simpread_config.json 才是您的配置文件。（看你的文件夹结构应该是这种）
 
除此之外的文件应该是手动导出的配置文件。

**Comment by Kenshin** [comment]
如果你没有任何丢失的稍后读，当然可以。

使用了自动同步，仅读写 `simpread_confg.json`

**Comment by Lusenlan** [comment]
好的感谢解答



---原始邮件---
发件人: "Kenshin ***@***.***&gt;
发送时间: 2023年8月16日(周三) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kenshin/simpread] 关于同步配置文件的问题 (Issue #5854)




 
如果你没有任何丢失的稍后读，当然可以。
 
使用了自动同步，仅读写 simpread_confg.json
