### ISSUE TITLE
导入notion 辅助增强 插件 

### ISSUE THREAD

**Issue by xinghe1555** [Kenshin/simpread#5855]
### 描述这个错误

因为在公司这边办公用的简悦好好的，家里也想安装一个

1. 可是安装后发现，总是在保存到notion后，触发`导入notion 辅助增强`失败

2. 在家里Macbook上安装后总是改不了` Notion Token` 和 `Database Page ID` ，还是用的办公用的电脑这边的 `Notion Token` 和 `Database Page ID` ，

3. 于是移除简悦后尝试也不行，后又重装chorm也不行，最后安装了简悦这个导入notion 辅助增强 插件，甚至没有了插件触发器这个选项，安装其他插件也没有插件触发器……

### 复现步骤

详细描述就是上面的。

操作完最后一个步骤后，内容可以导入notion，但是触发不了`导入notion 辅助增强` ，求解答

### 操作系统

macOS

### 浏览器

谷歌最新版本（官网下载重装的）

### 发生问题的网址

https://www.36kr.com/p/2390299001410180

**Comment by Kenshin** [comment]
插件触发器的问题，需要通过 https://www.yuque.com/kenshin/simpread/fcw60u 解决。
