### ISSUE TITLE
infoq无法加载页面

### ISSUE THREAD

**Issue by ccz0918** [Kenshin/simpread#5856]
### 需要适配的新站

https://xie.infoq.cn/article/0f4b929d9d274237a887e16e4

**Comment by Kenshin** [comment]
因为这个页面是动态加载的，所以需要将 `xie.infoq.cn` 加入到延迟加载列表，看下图

<img width="1334" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/917721df-8681-471b-9d61-a629d36f2b80">
