### ISSUE TITLE
报告点击保存无效的 bug，（标签没有被成功生成/保存）

### ISSUE THREAD

**Issue by yolio2003** [Kenshin/simpread#5858]
### 描述这个错误

<img width="572" alt="image" src="https://github.com/Kenshin/simpread/assets/352931/2a9e3838-0764-4902-ae27-a9c683b15a07">

### 复现步骤

https://github.com/Kenshin/simpread/assets/352931/2533595b-0719-498b-8c49-77f91f8e6d77

1. 想保存一些标签
2. 点击保存没有反应
3. 查看浏览器日志显示
<img width="733" alt="image" src="https://github.com/Kenshin/simpread/assets/352931/02d08ef7-001c-4f08-ad4a-4a705e07ba38">
不知道是否有关系哈

### 操作系统

macOS

### 浏览器

Chrome 116.0.5845.96（正式版本） (arm64)

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

**Comment by Kenshin** [comment]
emmmm 

在稍后读中修改标签？还是？建议录屏给我看下。

**Comment by Kenshin** [comment]
通常情况下，基本操作如果有 Bug 的话，早就被用户发现了，所以录屏是个好方案。

毕竟简悦的用户基数不小。

**Comment by yolio2003** [comment]
已经补充录屏，还是挺基础的问题，随意就复现了
ps 我尝试了关闭其他扩展，同样没有影响， bug 稳定复现

**Comment by yolio2003** [comment]
收到 辛苦啦

**Comment by Kenshin** [comment]
我看到你的视频了 😂 ... 看下图所示

<img width="503" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/55f50160-634b-49b8-b7de-fe34e9c30119">

**Comment by yolio2003** [comment]
啊 居然是因为这个，sorry 是我太不注意了！非常感谢！

提个小的建议，这里的保存按钮点击后没反应让我觉得有点点以为是哪里有问题了，不确定是否是你想要的设计效果哈。

**Comment by Kenshin** [comment]
> 居然是因为这个，sorry 是我太不注意了

小事情~

> 提个小的建议，这里的保存按钮点击后没反应让我觉得有点点以为是哪里有问题了，不确定是否是你想要的设计效果哈。

okay 收到，这里其实我也没想「明白」，因为频繁的提示也会有些「扰人」😂

不过，这算是已知需要优化的地方之一~
