### ISSUE TITLE
notion教育账户无法绑定

### ISSUE THREAD

**Issue by miniLQ** [Kenshin/simpread#5859]
### 描述这个错误

我使用的edu账号，在授权notion时，显示正在授权，但是等待很久刷新页面，开关又变成了灰色

### 复现步骤

1. 使用edu notion账号
2. 点击notion授权按钮

### 操作系统

windows 11

### 浏览器

chrome

### 发生问题的网址

NA

**Comment by Kenshin** [comment]
试试 https://www.yuque.com/kenshin/simpread/wwk65u 能否解决？

**Comment by beiminglongkun** [comment]
> 试试 https://www.yuque.com/kenshin/simpread/wwk65u#ERFLg 能否解决？

尝试链接中提到的方法，仍然不能解决

**Comment by Kenshin** [comment]
@beiminglongkun 

你是教育版？还是某些特殊类型的账户？

**Comment by beiminglongkun** [comment]
> @beiminglongkun
> 
> 你是教育版？还是某些特殊类型的账户？

教育版，直接通过教育邮箱注册的账号

**Comment by Kenshin** [comment]
@beiminglongkun 

因为我没有教育版，而且简悦的 Notion 用户数还不错，所以也没有其他用户反馈过。

建议你可以随便找个正常的账户测试，如果仍是有问题的话，只能说明你的操作有误。
