### ISSUE TITLE
md+assets插件设置导出根目录bug

### ISSUE THREAD

**Issue by LOONG001** [Kenshin/simpread#5860]
### 描述这个错误

md+assets插件设置好导出根目录，刷新后根目录消失，导致无法保存

### 复现步骤

https://github.com/Kenshin/simpread/assets/34571314/5b99dbcc-834e-4b7c-979d-509a76b09d46

### 操作系统

win11

### 浏览器

chrome116.0.5845.97

### 发生问题的网址

https://zhuanlan.zhihu.com/p/586320179

**Comment by Kenshin** [comment]
嗨，这是另外一个问题，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
