### ISSUE TITLE
两台电脑同步

### ISSUE THREAD

**Issue by fortitudelucifer** [Kenshin/simpread#5861]
### 请描述你的建议或任何内容

我查看了多端多服务器的那个解决办法还是没怎么理解。请教下开发者，我有两台电脑，我用obsidian做笔记，我一般会用三个浏览器，qq，edge和chrome，不同浏览器做不同的事，今天早上在电脑A上三个浏览器都配置好了简悦，中午想在电脑B上配置简悦，chrome失败了，说同时登陆过多浏览器，要么退出要么联系管理员，那个解决办法我看了，我电脑A和B是分开的，我两台电脑都会用来学习，但目前简悦看上去不能跨电脑同步，我不知道该怎么解决？我可以多花点钱，但不同端不能云同步，我的学习流程就不是很方便，想问问怎么解决？

**Comment by Kenshin** [comment]
嗨，我看到你 Close 了，是解决了吗？

关于同步的话，可以看下 https://www.yuque.com/kenshin/simpread/ebwu7g 里面的说明。

有任何需要随时讨论。
