### ISSUE TITLE
已经开通高级账户,但是自动同步功能任然锁定

### ISSUE THREAD

**Issue by t427794322** [Kenshin/simpread#5866]
### 描述这个错误

已经开通高级账户,但是自动同步功能任然锁定

### 复现步骤

1.购买 license
2.激活
3.无法设置自动同步

### 操作系统

macos: 10.13.6 (17G14033)

### 浏览器

版本 116.0.5845.96（正式版本） (x86_64)

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

**Comment by Kenshin** [comment]
首次升级高级账户时提示重启浏览器，但你没有这么做。

解决方案 https://www.yuque.com/kenshin/simpread/ga970q

**Comment by t427794322** [comment]
> 首次升级高级账户时提示重启浏览器，但你没有这么做。
> 
> 解决方案 https://www.yuque.com/kenshin/simpread/ga970q

不是没有重启,在共通中把配置文件导入到本地,然后右上角导入配置登录就行了,但是导入之前明明已经显示解锁高级用户了,我是 md 的 license 激活的,这应该是个 bug

**Comment by Kenshin** [comment]
> 在共通中把配置文件导入到本地,然后右上角导入配置登录就行了,但是导入之前明明已经显示解锁高级用户了

这个描述似乎有误…

方便的话，可以录屏给我看下。
