### ISSUE TITLE
弹出窗口关闭问题

### ISSUE THREAD

**Issue by Jing-Loog** [Kenshin/simpread#5868]
### 描述这个错误

安装ai助手插件和点击查看大图插件后，进入简悦阅读模式，会弹出一个窗口，但是找不到关闭按钮在哪。重新刷新后，还是会弹出，就是关不了。

### 复现步骤

![Snipaste_2023-08-26_21-34-05](https://github.com/Kenshin/simpread/assets/59569074/7a5ae1da-d4b5-4ad3-a03a-48dfe71f12db)

### 操作系统

windows

### 浏览器

谷歌浏览器

### 发生问题的网址

跟网址无关

**Comment by Kenshin** [comment]
emmm 分辨率的问题，你可以暂时把页面缩小点。

PS：你的分辨率是多大？
