### ISSUE TITLE
页面在阅读模式下无法保存到Joplin

### ISSUE THREAD

**Issue by ranyangpj** [Kenshin/simpread#5869]
### 描述这个错误

文章可以正常进入阅读模式，可以保存为离线html，但在阅读模式下无法保存到joplin，将页面保存到稍后读之后可以保存到joplin，文章网址是：http://www.50forum.org.cn/home/article/detail/id/9767.html

### 复现步骤

阅读模式下无法保存到joplin

### 操作系统

window11

### 浏览器

chrome

### 发生问题的网址

http://www.50forum.org.cn/home/article/detail/id/9767.html

**Comment by Kenshin** [comment]
嗨，其他页面有这个问题吗？如果没有的话，可能只是个例。

**Comment by Kenshin** [comment]
嗨，我没有遇到你提到的问题，我可以正常导入到 Joplin

![image](https://github.com/Kenshin/simpread/assets/81074/eb99c26e-a7ed-447e-8d07-4e0953eae7ff)

<img width="1590" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d602279b-8647-43be-817a-4e7be12a2447">

Joplin 版本

<img width="238" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c1598881-fb3e-4450-8469-007b144f12d3">

**Comment by ranyangpj** [comment]
我这里这个网站都不行，阅读模式下无法保存到joplin，显示如图
![屏幕截图](https://github.com/Kenshin/simpread/assets/26500341/bd5c3773-6f00-4563-959b-aebffe050f0d)

**Comment by Kenshin** [comment]
其他页面呢？

试试在隐私模式下，仅启用简悦的方式

**Comment by ranyangpj** [comment]
其他网站没发现问题

**Comment by ranyangpj** [comment]
隐私模式下同样会弹出保存失败的信息

**Comment by Kenshin** [comment]
重新设置下 Joplin 和简悦的 Token 

有个别用户可能是因为这个导致的。

**Comment by ranyangpj** [comment]
重置了token，还是一样，就这个网站有问题

**Comment by Kenshin** [comment]
okay 那就先这样吧 😂 问题是我边没问题

试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看能否解决？

**Comment by ranyangpj** [comment]
打开chrome控制台看到的错误信息如下：
Access to XMLHttpRequest at 'http://localhost:41184/notes?token=***' from origin 'http://www.50forum.org.cn' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5869#issuecomment-1704304477

应该是这个问题造成的，但我这边没有，我更换了不同的浏览器也没有触发 CORS 错误。

PS：CORS 错误是个常见的跨域错误。

**Comment by ranyangpj** [comment]
是否可以考虑添加一个选项，可以让用户将阅读模式下的本地缓存保存到joplin软件中，而不是从网站读取内容保存

**Comment by Kenshin** [comment]
暂时没有这种方式… 😂

你是什么系统？另外试试使用其他浏览器看看有没有问题。

**Comment by ranyangpj** [comment]
我是win11+chrome Version 116.0.5845.141，
先不折腾了，保存不了的就先用joplin自己的剪藏或者保存到稍后读再发送，就是稍微麻烦点

**Comment by Kenshin** [comment]
okay 

如果你经常使用这个功能的话，仅此一例可以忽略不计。
