### ISSUE TITLE
合并单元格转Markdown异常

### ISSUE THREAD

**Issue by ZQ2014** [Kenshin/simpread#587]
由于Markdown语法无法直接表达合并单元格，所以由合并单元格直接转化为Markdown会导致无法正常显示。
建议将存在合并单元格的表格转化为html而非Markdown。

转换获得的异常Markdown代码如下：
| 移动光标的方法 |
| --- |
| h 或 向左箭头键 (←) | 光标向左移动一个字符 |
| j 或 向下箭头键 (↓) | 光标向下移动一个字符 |

发现问题的网页：https://www.runoob.com/linux/linux-vim.html

祝好！

**Comment by Kenshin** [comment]
谢谢反馈，确如你说。

目前 HTML → MD 是一个现成的 library 我详细调查下是什么问题造成的，先记 Bug~

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，目前的做法是：只有涉及到 Table 都会被强制转换为 HTML 结构，因为大多数 Markdown Editor 都支持直接解析 Table HTML e.g Tyora

接下来会考虑对导出的 Markdown 进行定制化，如 **是否将 Table 转换为 HTML** 等选项。

所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
