### ISSUE TITLE
打开特定网页（shop.lonelyplanet.com）会卡死

### ISSUE THREAD

**Issue by Mongkii** [Kenshin/simpread#5870]
### 描述这个错误

打开网页 https://shop.lonelyplanet.com/collections/all 会卡死

### 复现步骤

1. 打开该网页 https://shop.lonelyplanet.com/collections/all，页面卡死
2. 使用Chrome的任务管理器，会看到Dedicated Worker CPU占用100
3. 禁用简悦插件后，关闭tab重新打开，网页正常进入

### 操作系统

macOS 13.4.1

### 浏览器

Chrome 116.0.5845.110

### 发生问题的网址

https://shop.lonelyplanet.com/collections/all

**Comment by Kenshin** [comment]
嗨，经测试确实如此。

不过，也很容易解决，将 `shop.lonelyplanet.com` 加入到黑名单就行了，位置在选项页 → 高级设定 → 黑名单

<img width="873" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7f4a23c2-7f54-4f88-be8b-ce18fb201793">

**Comment by Kenshin** [comment]
嗨，经测试确实如此。

不过，也很容易解决，将 `shop.lonelyplanet.com` 加入到黑名单就行了，位置在选项页 → 高级设定 → 黑名单

<img width="873" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7f4a23c2-7f54-4f88-be8b-ce18fb201793">

**Comment by Mongkii** [comment]
有办法定位到根因吗？其他网站可能也有同样问题，能彻底解决是最好的

**Comment by Kenshin** [comment]
简悦是阅读模式类产品，为了让阅读模式更快的生成而不是当用户进入阅读模式时生成，所以会在进入页面时获取正文。

简单的说，它会「检索页面」，有的时候会让某些页面误以为是「爬虫」，所以，某些网站可能对这种行为有反馈，表象就是你提到的情况，这种问题很复杂。

不过，其实不用担心，目前简悦已经运行六年，每个处理无数的页面（当然具体数字我不清楚，简悦不追踪用户数据，所以我拿不到任何数据，只是单纯的根据简悦的用户数来判断。）

截至到这个 Issues ，估计报告了不超过 10 例，完全可以忽略不计。
