### ISSUE TITLE
[Feature]同步助手的历史记录可定期清理

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5871]
### 描述这个错误

不知道是bug还是就这么设计的，只要开机哪怕完全没使用一天也会多好多backup（过于多了），分分钟把容量占满。

如果是设计如此，希望能自定义后台备份的频率，或者能设置自动清理多长时间之前的配置文件，隔不了几天就要手动删一回太麻烦了。

### 复现步骤

无

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

无

**Comment by Kenshin** [comment]
你可以随时删除这些备份，具体细节可以看 https://github.com/Kenshin/simpread/issues/5867
