### ISSUE TITLE
obsidian导入后内嵌快照标注无法同步到笔记

### ISSUE THREAD

**Issue by ZHEYESHIYU** [Kenshin/simpread#5872]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/142708826/60674a0c-ee8e-443b-9e8b-d011b1d3498d)

### 复现步骤

使用simpread sync导出的。
每个网址都是这样，只有在原网站重新进入阅读模式后快照的标记才会同步。

### 操作系统

windows

### 浏览器

chrome

### 发生问题的网址

https://www.bloomberg.com/opinion/articles/2023-08-27/china-pollution-economic-slowdown-may-cut-greenhouse-gases?srnd=opinion

**Comment by Kenshin** [comment]
嗨，我看到你 Close 它了，是解决了吗？

PS：Obsidian 主题不错，叫什么名字？
