### ISSUE TITLE
明明安装了插件，就是不显示

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5879]
### 描述这个错误

在使用同步助手的情况下，安装了两个插件，进入阅读模式后，就是看不到可用的插件。
<img width="669" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/106e6cae-e90a-4977-94a9-86c1cf48c76a">

### 复现步骤

<img width="474" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/17bb0cc6-793f-422e-8430-4242945113fc">

<img width="446" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/69a63b51-c818-47c2-a278-b822789ca946">

### 其他相关说明

简约是我用过的配置最复杂的工具，各种神器问题，经常英文同步助手把自己玩残了。
又爱又恨！

### 操作系统

macOS

### 浏览器

Chrome

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装插件。

**Comment by shadu120** [comment]
> 

我按照这方式搞了好几回。最后也不知道怎么成功的。
可以把你这句话放在插件首页……

**Comment by Kenshin** [comment]
> 可以把你这句话放在插件首页……

😂 不是每个用户都有这个问题。

> 最后也不知道怎么成功的。

（盲猜）还是没有按照步骤  🌚

**Comment by shadu120** [comment]
原来此后的每一个插件，都得这么操作，。。。我刚装自动化辅助增强又走了一遍流程。还好不是所有插件卸载从头来一遍。

**Comment by Kenshin** [comment]
不需要每个插件都这样... 😂

插件管理器里面有明确说明，仅第一个插件需要这么使用，再之后仅通过插件管理器安装插件即可。

PS：如果使用了配置库的话，也不需要这么做。

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
