### ISSUE TITLE
简悦 安卓版望作者出个安装教程

### ISSUE THREAD

**Issue by ffywhxf** [Kenshin/simpread#588]
弄了好久，终于在安卓机上装了简悦（油猴版，用火狐浏览器，非油猴版装了没显示进入简悦模式的按钮）。
但 油猴版 没有保存至 语雀 的功能，望作者添加。

**Comment by Kenshin** [comment]
谢谢反馈～

***

给你几个文档地址，希望可以帮到你。

文档中心 → http://ksria.com/simpread/docs

Andriod 版 → http://ksria.com/simpread/docs/#/Android

轻阅版 → https://github.com/Kenshin/simpread-little

当然，有可能文档有不全的情况，请告知。

***

轻阅版是以阅读模式为主要的轻量级版本，所以并没有打算加入导出到生产力工具的计划。

**Comment by 1tonsilla** [comment]
@Kenshin 您好，我今天安装了油猴版的给kiwi用的，发现每一个网页都弹出来 图标有些不方便、不美观。能否提供相关选项设置呢？（本来我使用的是普通版本的简悦，但是试了下插件在kiwi上点安装没反应，想试试油猴版的。但是好像都不支持插件）

**Comment by Kenshin** [comment]
@1tonsilla 

简悦 2.0 支持 Kiwi Browser，如果之前装过的话，请重新安装。
