### ISSUE TITLE
加入稍后读，并没有自动导入Obsidian

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5880]
### 描述这个错误

安装了导入到Obsidian插件，并在Obsidian中安装了Sync插件。

配置简悦Obsidan插件，勾选导入到稍后读自动保存到Obsidian

<img width="1059" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/bcf81c37-947c-4d42-bd01-1e04f6848a99">

### 复现步骤

访问ULRL，使用快捷键：aa， ss
发现，文章并没有导入到Obsidian。
https://mp.weixin.qq.com/s?__biz=MzI0NDA5MDYyNA==&mid=2648257179&idx=1&sn=cc3a1208e778641d5b5b50c283de0dd8&chksm=f14e80f4c63909e25b0e354ae7745a5135db08196c0723cf9a7a13adefde475e2a185bf70730&scene=132&exptype=timeline_recommend_article_extendread_samebiz#wechat_redirect

手工通过插件执行导入全文到Obsidian可以。

### 操作系统

macOS

### 浏览器

Chrome

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MzI0NDA5MDYyNA==&mid=2648257179&idx=1&sn=cc3a1208e778641d5b5b50c283de0dd8&chksm=f14e80f4c63909e25b0e354ae7745a5135db08196c0723cf9a7a13adefde475e2a185bf70730&scene=132&exptype=timeline_recommend_article_extendread_samebiz#wechat_redirect

**Comment by Kenshin** [comment]
使用快捷键 `d d` 或右键菜单加入稍后读时才会触发自动化。

**Comment by shadu120** [comment]
我描述错误，实际上执行的是`dd` ,也没有导入成功。

<img width="339" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/2ec65bcf-ac7b-4c68-92eb-564d071731d2">
https://news.ifeng.com/c/8R9U3MRpYYI

**Comment by Kenshin** [comment]
emmm 这里的描述可能有点问题。

除了开启此选项外，还需要使用自动化辅助增强

<img width="617" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f3ebf103-8ebd-4407-9b96-885b102fcfb2">

**Comment by shadu120** [comment]
这个开关和上面的自动化方案看上去没有关联关系，我以为是独立的。

**Comment by Kenshin** [comment]
这里确实需要优化下文案，优化后会通知你的~
