### ISSUE TITLE
Obsidian插件，使用SimpRead Sync导出时，文件名无法自定义

### ISSUE THREAD

**Issue by shadu120** [Kenshin/simpread#5881]
### 描述这个错误

已经安装了Obsidian插件，并启动了同步助手。
配置了SimpRead Sync导出参数，自定义文件名，但是导出时并未生效。
`{{id}}-{{title}}{{mode}}`

### 复现步骤

1.配置插件文件名格式
<img width="476" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/86b0c83f-bd62-4e26-8af2-a69b277e4fab">

2.导出文件名未生效

<img width="397" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/736f3541-dcc8-44d8-b50c-54ebbecd7887">

### 操作系统

macOS

### 浏览器

Chrome

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MzI0NDA5MDYyNA==&mid=2648257179&idx=1&sn=cc3a1208e778641d5b5b50c283de0dd8&chksm=f14e80f4c63909e25b0e354ae7745a5135db08196c0723cf9a7a13adefde475e2a185bf70730&scene=132&exptype=timeline_recommend_article_extendread_samebiz#wechat_redirect

**Comment by shadu120** [comment]
<img width="900" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/181930bd-ccb0-4972-8ccd-fa459ff4321b">

定义导出的地方也做了同样的设置。

**Comment by shadu120** [comment]
<img width="1287" alt="image" src="https://github.com/Kenshin/simpread/assets/3023471/331f39c9-5e4b-4a59-a963-0ff8fbfa3728">
Obsidian插件也有设置

**Comment by Kenshin** [comment]
定制导出这里错了

应该是 `{{id}}{{un_title}}{{mode}}` 看下图

<img width="875" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/44d642ce-70c1-45d7-98e9-edf8fd8e2d8d">

PS：如果使用了配置库方案，这里的值应该没问题。

**Comment by shadu120** [comment]
同样是定义文件名，有三个地方。区别是啥？
而且规则还不一样，这个很容易搞死人。。。
