### ISSUE TITLE
PDF导出增加页码和目录（带缩进）

### ISSUE THREAD

**Issue by holduan** [Kenshin/simpread#5886]
### 请描述你的建议或任何内容

如题，有的长文需要目录，Acrobat自动目录时不能识别由简悦导出的PDF的标题结构

![image](https://github.com/Kenshin/simpread/assets/80377040/f77e542a-9a58-4cb3-8e04-6b090f0ad3ad)

**Comment by Kenshin** [comment]
是可以的，细节请看 https://github.com/Kenshin/simpread/discussions/3887

**Comment by holduan** [comment]
> 是可以的，细节请看 #3887

谢谢，页码和目录弄好了。❤
不知道能不能指导一下，怎么在页脚中间添加一个带原文链接的网页标题呢

**Comment by Kenshin** [comment]
> 怎么在页脚中间添加一个带原文链接的网页标题呢

这个暂时没办法，但页脚是可以点击的，链接就是原文。

**Comment by holduan** [comment]
> > 怎么在页脚中间添加一个带原文链接的网页标题呢
> 
> 这个暂时没办法，但页脚是可以点击的，链接就是原文。

嗯，请问怎么加入链接呢，看了说明文档也没弄好这个

**Comment by holduan** [comment]
> 现在就自带了链接，就在页脚。
> 
> 点击原文地址没有反映吗？

选择了 **同步助手高级打印方案** ，页脚没有链接，页码也是用了**定制化**才有，倒是目录是默认有的

**Comment by Kenshin** [comment]
okay 我确认后告诉你，今天稍晚些

**Comment by Kenshin** [comment]
我确认了，确实如此，忘记加了 😂

也很容易添加它，但不知道你对样式有什么要求，目前是这样的

<img width="787" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d18c6a26-4981-46b2-9c24-c882375ec463">

**Comment by Kenshin** [comment]
第二种方案，在标题处。

<img width="877" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/017a9b68-7f20-4652-8d32-62e27d40b20d">

**Comment by holduan** [comment]
> 我确认了，确实如此，忘记加了 😂
> 
> 也很容易添加它，但不知道你对样式有什么要求，目前是这样的
> 
> <img alt="image" width="787" src="https://user-images.githubusercontent.com/81074/264565982-d18c6a26-4981-46b2-9c24-c882375ec463.png">

是把链接加在首页标题或者最后一页的页脚吗，那可以加在首页标题。
但不知道可不可以个每页页脚价格原文链接呢。场景是：阅读软件有阅读进度，不想翻页来打开原文

**Comment by Kenshin** [comment]
> 那可以加在首页标题。

那也就是 https://github.com/Kenshin/simpread/issues/5886#issuecomment-1700505715 这个方案。

你确定吗？

> 不知道可不可以再每页页脚加个原文链接呢

这个有点麻烦，我研究了下 `wkhtmltopdf` 似乎没办法实现。

PS：我先重开这个 Issues

**Comment by holduan** [comment]
> > 那可以加在首页标题。
> 
> 那也就是 [#5886 (comment)](https://github.com/Kenshin/simpread/issues/5886#issuecomment-1700505715) 这个方案。
> 
> 你确定吗？
> 
> > 不知道可不可以再每页页脚加个原文链接呢
> 
> 这个有点麻烦，我研究了下 `wkhtmltopdf` 似乎没办法实现。
> 
> PS：我先重开这个 Issues

嗯嗯，谢谢。就你提供的两种方案，第二种方案实用些。

**Comment by Kenshin** [comment]
okay 这个插件发布了，留意下面的升级方案~

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Kenshin** [comment]
如果解决了你的问题的话，我 Close 这个 Feature 了（不是在 Issues 上）

**Comment by holduan** [comment]
> 如果解决了你的问题的话，我 Close 这个 Feature 了（不是在 Issues 上）

嗯嗯，首页标题已经有原文链接，谢谢 ❤

**Comment by Kenshin** [comment]
okay 解决就好，谢谢提示这个 Bug 可能使用此功能的用户大部分都不需要溯源（毕竟 PDF 嘛...

PS：每页加页码的配置能否提供下？（省得我翻文档了 😂

***

方便的话，请帮忙对简悦五星 + 好评 😏  是对简悦最好的回报 👍

进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll`  通过下图 

![image](https://user-images.githubusercontent.com/81074/168513827-44a206d8-f757-4d61-93b5-db98297b96b1.png)

**Comment by holduan** [comment]
> 

--footer-right [page]/[topage] --footer-font-size 8 --footer-spacing 3

已在Edge上好评

**Comment by holduan** [comment]
> okay 解决就好，谢谢提示这个 Bug 可能使用此功能的用户大部分都不需要溯源（毕竟 PDF 嘛...
> 
> PS：每页加页码的配置能否提供下？（省得我翻文档了 😂

--footer-right [page]/[topage] --footer-font-size 8 --footer-spacing 3

已在Edge上好评

**Comment by Kenshin** [comment]
okay 收到，谢谢 🙏

**Comment by Kenshin** [comment]
已经将你提到的方案添加到 https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-2750058

 👍
