### ISSUE TITLE
不进入阅读模式的导出离线HTML

### ISSUE THREAD

**Issue by Losk-x** [Kenshin/simpread#5889]
### 请描述你的建议或任何内容

简悦的导出功能非常棒，但是它的离线HTML导出和SingleFile有点重复，我希望完全用SimpRead导出离线HTML文件（去掉SIngleFile），但可以让我选择导出阅读模式或原本页面的离线HTML。

### 补充说明

我知道SingleFile + SingFile Companion可以实现类似简悦 + 简约同步助手的导出效果，但太冗余了。

BTW，很多时候导出HTML比导出Markdown更好用更好看，而且Markdown更适合个人笔记。我认为导出HTML才是导出到笔记软件（例如Obsidian）的更优方案，除了HTML文件更大之外没有什么缺点。

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

但简悦不是一个剪藏工具，而是一个阅读模式工具，剪藏只是它的部分功能。

所以，暂时没法实现你的诉求。

PS：如果是 Windows 用户，可以试试这个 Quicker 脚本。

PPS：对剪藏有编辑需求的话，可以试试 https://github.com/Kenshin/simpread/discussions/3340 提到的集中方案。
