### ISSUE TITLE
CSDN代码块混论

### ISSUE THREAD

**Issue by Traserve** [Kenshin/simpread#589]
原格式：
![原格式](https://user-images.githubusercontent.com/17785306/66373711-d90b0b00-e9db-11e9-97a1-b677858fc62c.PNG)
转换后格式：
![转换后格式](https://user-images.githubusercontent.com/17785306/66373723-e0321900-e9db-11e9-96ef-4f0da5d0edd3.PNG)

**Comment by Kenshin** [comment]
谢谢反馈，近期可能是由于 CSDN 调整了高亮规则导致，我先加入到 https://github.com/Kenshin/simpread/issues/570 会集中修复。

**Comment by Traserve** [comment]
有的代码块没有这个问题，但是行号没了，应该是富文本编辑器和markdown展示效果不一致导致的吧

**Comment by Kenshin** [comment]
CSDN 每篇文章的代码高亮规则都不一样（ 也就说它们在后台使用了不同的代码高亮模块），所以适配的话，则没问题。

反之，就是这个模块的高亮规则没有被适配。 😂

**Comment by Kenshin** [comment]
嗨，这几天准备集中修复 代码高亮 的问题。

不过，很奇怪的是，我测试了几个 CSDN 的页面均未发生问题，请问能否告知具体的 URL 

***

另外，请确保安装 [代码高亮插件](https://github.com/Kenshin/simpread/issues/500)

**Comment by Traserve** [comment]
https://blog.csdn.net/csdnhyp/article/details/56841150

**Comment by Traserve** [comment]
https://blog.csdn.net/qq_35056292/article/details/80331053

**Comment by Kenshin** [comment]
@Traserve 

你给出的两个链接，请看下面截图（简悦生成

![simpread-Floyd 判圈算法（龟兔赛跑算法）记录 - y4ung - CSDN 博客](https://user-images.githubusercontent.com/81074/70107038-5a031d80-1680-11ea-8793-0ecaaffa8c35.png)
![simpread-Nginx 配置记录 - csdnhyp 的博客 - CSDN 博客](https://user-images.githubusercontent.com/81074/70107039-5a031d80-1680-11ea-85eb-8b18e133cdb2.png)

**Comment by Traserve** [comment]
![blog csdn net_csdnhyp_article_details_56841150](https://user-images.githubusercontent.com/17785306/70209171-82674680-176a-11ea-98f7-24b7f8211f91.png)
这是我自己浏览器的截图，Google Chrome版本 78.0.3904.87（正式版本） （64 位）

**Comment by Kenshin** [comment]
请确保安装 [代码高亮插件](https://github.com/Kenshin/simpread/issues/500)

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

此问题已经被解决了

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
