### ISSUE TITLE
改进对singlefile的适配x2

### ISSUE THREAD

**Issue by sasasqt** [Kenshin/simpread#5891]
### 请描述你的建议或任何内容

问题1：
通过singlefile保存的html无法通过baseuri/url来适配站点规则，但singlefile在comment里保存了原始url ($x('/html/comment()')[0])
希望适配
![image](https://github.com/Kenshin/simpread/assets/56587914/8e5a0b1d-c05d-462e-8445-fd442b327622)
![image](https://github.com/Kenshin/simpread/assets/56587914/318a42b4-f333-4303-a27e-f553b4c5ff7d)

问题2：
singlefile已保存图片为base64格式，但被simpread忽略
优先base64格式 或 优先src而不是data-src
![image](https://github.com/Kenshin/simpread/assets/56587914/bb6204f4-c1e5-4a1e-a8cd-7fa1aaee42d0)
![image](https://github.com/Kenshin/simpread/assets/56587914/4d3f990c-59d6-49ac-8863-18a9c5f6cc6b)

关联issue
https://github.com/Kenshin/simpread/issues/5701#issuecomment-1606986488

**Comment by Kenshin** [comment]
简悦有个功能，可以读取任意本地的 HTML 为阅读模式 https://github.com/Kenshin/simpread/discussions/4723

但对 singlefile 有点问题（主要是图片），我先 Mark 下~

**Comment by sasasqt** [comment]
> 简悦有个功能，可以读取任意本地的 HTML 为阅读模式 #4723

这我知道，但我这个singlefile是host在远程服务器上的

**Comment by Kenshin** [comment]
> 但我这个singlefile是host在远程服务器上的

然后以外网的形式访问？有没有我可以访问的地址给我一个，方便我测试。

**Comment by sasasqt** [comment]
已发你邮箱

**Comment by Kenshin** [comment]
okay 收到~

**Comment by sasasqt** [comment]
**问题2**/[issue#5701](https://github.com/Kenshin/simpread/issues/5701#issuecomment-1606986488) 由于扩展插件赋值顺序导致的
原始的vendors.js
```
                      , o = n.attr("src")
                      , i = n.attr("data-src")
                      ...  
                        h = l || o,
                        h = i || h,
                        h = a || h,
                        h = s || h,
                        h = u || h,
                        h = p || h,
```
修改后:
```
                      , o = n.attr("src")
                      , i = n.attr("data-src")
                      ...
                        h = l || o,
                        h = i || h,
                        h = a || h,
                        h = s || h,
                        h = u || h,
                        h = p || h,

                        **h = o || h,**

```
修复该问题

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5891#issuecomment-1702947434

哈，问题确实出在这里，也谢谢提出解决方案，不过不能这么修改。😂 （当然不是你的问题，毕竟没法看到源代码和逻辑，不过思路已经很精准了。

我想到了一个解决方案，需要验证下才行~

**Comment by Kenshin** [comment]
嗨，[外部访问辅助增强](https://github.com/Kenshin/simpread/discussions/5895) 插件发布了，主要解决了你提到的问题。

因为你在外部使用，所以需要使用 [白名单](https://github.com/Kenshin/simpread/discussions/5895#discussioncomment-6891220) 方案。

PS：你似乎把昨天共享给我的链接删除了，所以我没法测试，你可以自己试试。

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/MAheFOdBhK) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5896

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~

**Comment by sasasqt** [comment]
ip似乎被墙了 

测试了下没问题
![image](https://github.com/Kenshin/simpread/assets/56587914/c485484c-bf09-4117-bbfc-397aa92a824b)

就是得在同步助手里设置外部文件夹，不然动作 插件触发器 里不显示 外部文件辅助增强的选项

**Comment by Kenshin** [comment]
> 同步助手里设置外部文件夹，不然动作 插件触发器 里不显示 外部文件辅助增强的选项

应该没有问题。（ 只要正常设置白名单，比如加上你的 IP ）

是不是没有使用插件管理器安装？

**Comment by sasasqt** [comment]
额 是没点导入

---

希望重构插件里的location.href, location.host等方法， 以剥离域名的判断。比如用新的允许用户自定义的变量_hostname代替。

我希望host在自己服务器上的副本（左）与原网页（右）享有同样的站点适配，及插件所带来的优化。（希望把图左当作图右来对待）

![image](https://github.com/Kenshin/simpread/assets/56587914/956bcb95-f058-4989-b976-06f68a0faedf)
![image](https://github.com/Kenshin/simpread/assets/56587914/a5bf19e1-4141-4922-b43b-bf639bd4143a)

---


比如在插件 微信公众号辅助增强 中，我自行host的副本(左)就无法激活该优化
```
    if ( !location.host.endsWith( 'mp.weixin.qq.com' ) ) return;
```

希望修改成
```
    default: global _hostname=location.host;
```

在外部文件辅助增强 中:
```
     _hostname= $x('/html/comment()')[0].data.pattern.matching.url
```
![image](https://github.com/Kenshin/simpread/assets/56587914/9e79ccac-3191-4259-8b36-e32abec88538)

在微信公众号辅助增强 中:
```
    if ( !_hostname.endsWith( 'mp.weixin.qq.com' ) ) return;
```

**Comment by Kenshin** [comment]
emmm 

你提到的解决方案仅适合：将 SingleFile 访问的页面使用简悦的阅读模式时产生的问题，但并不适合普适性，所以不应该应用于具有普遍性的插件。

当然，我能 Get 到你的诉求，仅考虑诉求的话，很正常的解决方案，但解决方案需要考虑下，有想法的话会告诉你。

PS：是同行吧？😄 提供的几个解决方案都很精准，让我少走了不少测试弯路 👍（不考虑简悦自身的全局逻辑的话）

**Comment by sasasqt** [comment]
> 你提到的解决方案仅适合：将 SingleFile 访问的页面使用简悦的阅读模式时产生的问题，但并不适合普适性，所以不应该应用于具有普遍性的插件。

应该也可以适用于web.archive.org，archive.ph这类快照网站，就是不知道需求大不大

> PS：是同行吧？😄
![image](https://github.com/Kenshin/simpread/assets/56587914/c7bd33be-c445-474d-be7d-dfa0df2282a0)

**Comment by Kenshin** [comment]
哈哈，原来是你，早知道应该先 Search 下，主要是近期来了不是类似的用户，所以以为是新朋友 😂

> 适用于web.archive.org，archive.ph这类快照网站，就是不知道需求大不大

其实不大，但毕竟有实在的使用场景，所以说会考虑的。

> 主要原因是location.href/location.host啥的是只读的

不全是，你提供的解决方案已经很完美了，但仅限于使用 SingleFile 导出的方案，不具有共性。
