### ISSUE TITLE
Chrome下md + assets模式无法导出

### ISSUE THREAD

**Issue by ArvinLCoder** [Kenshin/simpread#5892]
### 描述这个错误

操作系统版本：Win11 22H2
Chrome版本：Version 116.0.5845.141 (Official Build) (64-bit)
SimpRead扩展版本：2.2.0.520
同步助手版本：1.2.0
账号类别：高级账号
问题网址：任意网址
问题详细描述：Chrome无法使用md+assets格式导出，阅读模式下点击 动作-插件触发器-导出md+assets格式，无任何反应。在同一机器上，SimpRead和同步助手配置相同的情况下，Edge浏览器可以成功导出。
SimpRead md-assets导出项配置
![image](https://github.com/Kenshin/simpread/assets/89129724/85a8e661-b9d9-406b-ab80-b1c1469b90b8)
同步助手配置
![image](https://github.com/Kenshin/simpread/assets/89129724/498b8e17-4c6d-464d-b51c-d99ad79a837c)
在Chrome中点击导出时，F12看控制台有报错，截图如下
![Snipaste_2023-09-01_12-00-17](https://github.com/Kenshin/simpread/assets/89129724/f2bcb51b-7dae-46fd-9fa8-72ccca1e0598)
点击跳转代码如下
![image](https://github.com/Kenshin/simpread/assets/89129724/9f4b895d-3ab0-412b-b233-3c006a7254b8)

### 复现步骤

问题详细描述：Chrome无法使用md+assets格式导出，阅读模式下点击 动作-插件触发器-导出md+assets格式，无任何反应。在同一机器上，SimpRead和同步助手配置相同的情况下，Edge浏览器可以成功导出。
SimpRead md-assets导出项配置
![image](https://github.com/Kenshin/simpread/assets/89129724/85a8e661-b9d9-406b-ab80-b1c1469b90b8)
同步助手配置
![image](https://github.com/Kenshin/simpread/assets/89129724/498b8e17-4c6d-464d-b51c-d99ad79a837c)
在Chrome中点击导出时，F12看控制台有报错，截图如下
![Snipaste_2023-09-01_12-00-17](https://github.com/Kenshin/simpread/assets/89129724/f2bcb51b-7dae-46fd-9fa8-72ccca1e0598)
点击跳转代码如下
![image](https://github.com/Kenshin/simpread/assets/89129724/9f4b895d-3ab0-412b-b233-3c006a7254b8)

### 操作系统

Windows

### 浏览器

Chrome  版本：Version 116.0.5845.141 (Official Build) (64-bit)

### 发生问题的网址

https://afdian.net/p/bbd6e85adfa911eab2b152540025c377

**Comment by ArvinLCoder** [comment]
追加说明，已尝试重启Chrome、同步助手，禁用所有其它Chrome扩展，都不能解决问题

**Comment by Kenshin** [comment]
试试在 https://sspai.com/post/69972 测试：

加稍后读，然后把稍后读的标题去掉非法字符或直接改为 测试标题（如下图）

<img width="361" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bc809868-d12c-44cd-a45e-a818b83496cf">

这种方式排除因标题含有非法字符导致的错误。

如果这种方式可以正常导出的话，请安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？

**Comment by ArvinLCoder** [comment]
> 试试在 https://sspai.com/post/69972 测试：
> 
> 加稍后读，然后把稍后读的标题去掉非法字符或直接改为 测试标题（如下图）
> 
> <img alt="image" width="361" src="https://user-images.githubusercontent.com/81074/264924355-bc809868-d12c-44cd-a45e-a818b83496cf.png">
> 这种方式排除因标题含有非法字符导致的错误。
> 
> 如果这种方式可以正常导出的话，请安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 看看能否解决？

按照你说的方法做了一遍，现在可以正常使用了。
但这个插件我在之前找解决方法的时候，其实已经安装上了，但也是不能导出。按照你说的方法，加到稍后读修改标题再导出没有出现问题。把插件重新安装了一遍，现在不加稍后读，直接导出也没有问题了，挺奇怪的。

**Comment by Kenshin** [comment]
okay 解决就好~

插件安装不生效的问题，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u 

大概率是这个问题造成的。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042
