### ISSUE TITLE
微信公众号下载的HTML文件图片不显示

### ISSUE THREAD

**Issue by liuyuqiangchn** [Kenshin/simpread#5894]
### 描述这个错误

我启用了微信公众号增强插件，使用的强制模式，然后导出HTML文件，直接打开HTML文件没有问题，但是，如果放到服务器打开，比如，127.0.0.1/123.html，图片就不会显示了

### 复现步骤

应该是图片防盗链的问题吧

### 操作系统

Windows11

### 浏览器

谷歌浏览器

### 发生问题的网址

任何文件

**Comment by liuyuqiangchn** [comment]
另外，这个强制模式，能不能应用到所有网站，感觉有些网站，还是原始网站方便些

**Comment by Kenshin** [comment]
> 图片防盗链的问题吧

是的，这个问题跟简悦无关，不过你可以使用简悦提供的几种将图片本地化的方案，如：导出离线 HTML 等。

> 强制模式，能不能应用到所有网站，感觉有些网站，还是原始网站方便些

目前来说重灾区就是微信公众号，但也只是部分公众号，一些良心的公众号效果还是不错的。

如果你遇到适配不良的网站，可以：

1. 提交 https://github.com/kenshin/simpread/issues/new 告诉我
2. 使用 https://github.com/Kenshin/simpread/discussions/3340 提供的方式

**Comment by sasasqt** [comment]
在html源码里加入 
```
<meta name="referrer" content="no-referrer"> 
```

**Comment by liuyuqiangchn** [comment]
谢谢，试了一下，加入这个代码，还是不行，有一部分图片出来了，不过大部分还是不行

**Comment by sasasqt** [comment]
> 不过大部分还是不行

隐身模式/flush cache 试试呢

**Comment by liuyuqiangchn** [comment]
刚试了，隐身模式也不行的

**Comment by sasasqt** [comment]
> 刚试了，隐身模式也不行的

emm
在nginx.conf里加上
```
http {

    server {

        location /proxy {
            if ($request_uri ~ "/proxy\?url=(.*)$") {
              set $url $1;
            }  
            if ($url = false) {
                return 404;
            } 
            resolver 8.8.8.8 223.5.5.5;
            proxy_set_header Referer "https://mp.weixin.qq.com";
            proxy_pass $url;
        }
    }
}
```
来重定向localhost/proxy?url=的请求

记得
```
nginx -s reload
```

**Comment by Kenshin** [comment]
嗨，[外部访问辅助增强](https://github.com/Kenshin/simpread/discussions/5895) 插件发布了，主要解决了你提到的问题。

因为你在外部使用，所以需要使用 [白名单](https://github.com/Kenshin/simpread/discussions/5895#discussioncomment-6891220) 方案。

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/MAheFOdBhK) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5896

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~
