### ISSUE TITLE
建议！应用图标进入可设置

### ISSUE THREAD

**Issue by ChromeBing** [Kenshin/simpread#59]
点击应用图标进入阅读模式，再次点击是设置界面，如果可以设置再次点击回到原页面就好了，体验很棒哦

**Comment by Kenshin** [comment]
感谢建议~
的确有些用户提出过这个方案，所以计划把这个方案放到 `下个版本` 中实现。

初步的实现逻辑：
增加一个选项 `点击 page icon 后...` `进入/退出 阅读模式` 或者 `打开设定界面` 的选项卡。

**Comment by ChromeBing** [comment]
多谢大佬


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： Kenshin Wang <notifications@github.com> 日期: 2017/8/4  18:05  (GMT+08:00) 收件人： Kenshin/simpread <simpread@noreply.github.com> 抄送： 星宇 <1069502758@qq.com>, Author <author@noreply.github.com> 主题： Re: [Kenshin/simpread] 建议！ (#59) 
感谢建议~

的确有些用户提出过这个方案，所以计划把这个方案放到 下个版本 中实现。
初步的实现逻辑：

增加一个选项 点击 page icon 后... 进入/退出 阅读模式 或者 打开设定界面 的选项卡。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Kenshin/simpread","title":"Kenshin/simpread","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Kenshin/simpread"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kenshin in #59: 感谢建议~\r\n的确有些用户提出过这个方案，所以计划把这个方案放到 `下个版本` 中实现。\r\n\r\n初步的实现逻辑：\r\n增加一个选项 `点击 page icon 后...` `进入/退出 阅读模式` 或者 `打开设定界面` 的选项卡。"}],"action":{"name":"View Issue","url":"https://github.com/Kenshin/simpread/issues/59#issuecomment-320211016"}}}

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `动作栏图标可更改为进入/退出阅读模式` ，详细请看 [更新日志](http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update)
