### ISSUE TITLE
保存到语雀 LaTeX  公式显示错误问题

### ISSUE THREAD

**Issue by bighaidao** [Kenshin/simpread#590]
保存到语雀时，所有公式显示全部错误。 

我看了下 simpread 传给语雀的数据，是LaTeX 代码，感觉需要做某种转换才能在语雀正常显示。

@Kenshin  ，麻烦看看呢？ 希望能抽时间解决下。 谢谢啊

**Comment by Kenshin** [comment]
谢谢反馈，明天确实下。

这种情况估计会有问题，不过，还是给个链接比较好。

**Comment by bighaidao** [comment]
> 谢谢反馈，明天确实下。
> 
> 这种情况估计会有问题，不过，还是给个链接比较好。

http://fancyerii.github.io/2019/06/30/xlnet-theory/ 

hi，链接如上哈。 公式比较多

**Comment by Kenshin** [comment]
谢谢提供链接。

我看了下，确如之前所说... 目前应该没有太好的解决办法。除非是能将 LaTeX → 图片 的形式，我想想办法~

先记 Bug

**Comment by bighaidao** [comment]
> 谢谢提供链接。
> 
> 我看了下，确如之前所说... 目前应该没有太好的解决办法。除非是能将 LaTeX → 图片 的形式，我想想办法~
> 
> 先记 Bug

我刚也看了下，语雀的机制是转成图片显示，不是一般网页的动态转换。 这个确实尴尬，搜了下，好像也没有公式的转换接口。。。

我去内部问一下相关技术

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，目前的做法 https://github.com/Kenshin/simpread/issues/743#issuecomment-673943952

接下来会考虑对导出的 Markdown 进行定制化，如 **是否将 Table 转换为 HTML** 等选项。

但 Markdown 的转义还存在问题，我将关闭此 issues，转义的问题解决后，我会再次通知你。

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
