### ISSUE TITLE
segmentfault网站使用简悦展示之后内容出现错乱

### ISSUE THREAD

**Issue by fclever1122** [Kenshin/simpread#5900]
### 描述这个错误

使用简悦展示网站内容之后，出现文本前后顺序不一致的问题

### 复现步骤

1. 打开网址：https://segmentfault.com/a/1190000024478811
![image](https://github.com/Kenshin/simpread/assets/126740207/b93f50f9-75a7-4b9c-a6bb-bfd3f6091971)
2. 点击简悦插件
![image](https://github.com/Kenshin/simpread/assets/126740207/78946eb7-dc56-4edf-9747-3c2ce4a62445)
3.可以看到，文章前后的内容结构变了

### 操作系统

win11

### 浏览器

chrome   116.0.5845.141（正式版本） （64 位）

### 发生问题的网址

https://segmentfault.com/a/1190000024478811

**Comment by Kenshin** [comment]
我看你关闭这个 Issues 是解决了？

阅读模式有几种使用方案 https://github.com/Kenshin/simpread/discussions/3340

**Comment by fclever1122** [comment]
问题还存在，后来想了下，是个小问题就关闭了，您可以看下上面两个对比图片，第二张图片中顶部这段文字出现了两次

**Comment by fclever1122** [comment]
> 我看你关闭这个 Issues 是解决了？
> 
> 阅读模式有几种使用方案 #3340

好的， 我看下这个说明，新用户，还不太熟悉哈哈

**Comment by Kenshin** [comment]
> 问题还存在，后来想了下，是个小问题就关闭了，您可以看下上面两个对比图片，第二张图片中顶部这段文字出现了两次

我这边没问题，试试在**隐身模式下仅使用简悦的方式**，是不是其它扩展造成的干扰。

<img width="676" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dd3eb125-cf4a-4a76-a4ac-11ff650ceb41">
