### ISSUE TITLE
授权印象笔记失败

### ISSUE THREAD

**Issue by fclever1122** [Kenshin/simpread#5902]
### 描述这个错误

授权印象笔记，一直显示失败

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/126740207/76fbb443-a728-4948-8a42-9859726573c3)

![image](https://github.com/Kenshin/simpread/assets/126740207/cf3dd3a8-b5fd-42cd-b597-118fb5a5517a)

### 操作系统

win11

### 浏览器

chrome   116.0.5845.141（正式版本） （64 位）

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#connect

**Comment by Kenshin** [comment]
嗨，印象笔记的功能暂时不考虑提供了，也建议你更换其它的笔记，如语雀等 😂

**Comment by fclever1122** [comment]
OK，感谢答复
