### ISSUE TITLE
「导入到 Notion」 指定 Code Block 的 Language

### ISSUE THREAD

**Issue by MrLeo** [Kenshin/simpread#5903]
### 请描述你的建议或任何内容

目前导入到 notion 的 Code Block 默认是 Plain Text

是否可以根据文章内 code 自动设置相同的 language，或者在插件设置里设置默认 language

**Comment by Kenshin** [comment]
😂

我也想，但这个很难，因为代码高亮规则太多了，所以很难做到...

代码段的问题会集中在 #500 并关闭此 Issues 等我想到办法后再告诉你~
