### ISSUE TITLE
关于 Logseq 能否使用本地图片的方案

### ISSUE THREAD

**Issue by taogb2020** [Kenshin/simpread#5905]
### 请描述你的建议或任何内容

![image](https://github.com/Kenshin/simpread/assets/72112574/3df2a067-ce55-4196-b5f5-a6e0578c351c)

我希望导出到logseq中的图片可以是离线本地的，而不是网络链接

### 补充说明

场景：logseq中做离线笔记

**Comment by taogb2020** [comment]
我的意思是
![image](https://github.com/Kenshin/simpread/assets/72112574/5ac440ef-1649-4c67-ab96-030e36ce0bc9)
可不可以把这个，弄到
![image](https://github.com/Kenshin/simpread/assets/72112574/1850f81a-364d-46be-805b-5d48e86c6ec5)
这个里面？
这样的话，就可以实现自动化导出了

**Comment by Kenshin** [comment]
解决方案有几种，

> 可以将本地快照改为 离线 HTML

也就是最后一个图对应的自动化里面的 HTML 都改为离线 HTML。

但这种方式的缺点是：因为是内嵌 Base64 所以在 Markdown 预览效果并不理想。

> 解决方案二

图床插件 https://simpread.ksria.cn/plugins/details/VdMfVaXlni 请使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装。

将图片上传到你自己的图床空间。（个人建议这种方式）

> assets + md

暂时没办法使用 https://github.com/Kenshin/simpread/issues/5905#issuecomment-1709331365 方案，因为完全不用，而且我记得 Logseq 也没法使用这种方式（不确定，我需要研究下。

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~
