### ISSUE TITLE
发送邮件报错

### ISSUE THREAD

**Issue by chenjinfeng95** [Kenshin/simpread#5906]
### 描述这个错误

已经在邮箱开通了smtp服务，并设置了smtp密码。试了goole邮箱,qq邮箱都是报一样的错。

### 复现步骤

1、QQ邮箱开通了smtp服务，并获得了独立密码，接收邮箱用goole邮箱和QQ邮箱接收都报错

### 其他相关说明

需不需要在接收邮箱进行其他设置，还是开启服务就可以了。我没有进行接收邮箱的配置。

### 操作系统

windows11

### 浏览器

edge

### 发生问题的网址

https://bbs.csdn.net/

**Comment by Kenshin** [comment]
emmm

试试重启同步助手，然后看下设置是否保存正常？

**Comment by Kenshin** [comment]
emmm

试试重启同步助手，然后看下设置是否保存正常？
