### ISSUE TITLE
希望可以不让标题跟着正文一起缩进

### ISSUE THREAD

**Issue by Sunshagon** [Kenshin/simpread#5910]
### 请描述你的建议或任何内容

如题，在启用缩进后，段落的小标题会跟着正文一起缩进，希望可以加点区别
起码，每一段小标题的最左端应该是要比该段首行缩进的正文要往左一点，这样显得更有层次感一些

**Comment by Kenshin** [comment]
将下面的代码

```
sr-rd-content h1, sr-rd-content h1 *, sr-rd-content h2, sr-rd-content h2 *, sr-rd-content h3, sr-rd-content h3 *, sr-rd-content h4, sr-rd-content h4 *, sr-rd-content h5, sr-rd-content h5 *, sr-rd-content h6, sr-rd-content h6 * {
    text-indent: 0px!important
}
```

加入到 https://github.com/Kenshin/simpread/issues/5911#issuecomment-1711181480 一样的地方。

效果

<img width="953" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b209a64b-2d4c-4fc6-b4c4-50af71ba0769">

你可以将 `text-indent: 0px!important` 中的 `0` 改为负数 e.g. `text-indent: -10px!important`
