### ISSUE TITLE
希望增加让大纲显示在右侧的选项

### ISSUE THREAD

**Issue by Sunshagon** [Kenshin/simpread#5911]
### 请描述你的建议或任何内容

个人感觉，显示在右侧，更顺手一些，希望大佬考虑一下

**Comment by Kenshin** [comment]
哈，这个可能不太行，因为右侧有稍后读。

不过，非要这么做的话，也不是不行，可以用自定义样式解决，我先 Mark 下，现在在外面，回头给你解决方案。

**Comment by Sunshagon** [comment]
> 哈，这个可能不太行，因为右侧有稍后读。
> 
> 不过，非要这么做的话，也不是不行，可以用自定义样式解决，我先 Mark 下，现在在外面，回头给你解决方案。

哦哦，好的

**Comment by Kenshin** [comment]
将下面的代码

```
toc {
    left: unset!important;
    right: 0!important;
}
```

加入到如下位置，保存后刷新当前页面（最好重启浏览器）

<img width="467" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3828014b-efd3-43c6-ae1d-2bb2925c6656">

效果

<img width="1058" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cfed1b6f-633d-4455-816a-712dc9c47794">

但我不建议这么做，使用起来很「难受」，因为简悦的设置都在右侧...

**Comment by Sunshagon** [comment]
> 

有点尬，因为我发现，要是让大纲显示，还得把鼠标移到右侧，才能显示🤣🤣

**Comment by Kenshin** [comment]
哈哈，是的，所以说并不好用，而且推在一起也不好看 😂

**Comment by Kenshin** [comment]
> 进入阅读模式后，原页面的第一张图片都不会显示（仅不显示第一张图，其余会显示）

肯定是你的设置造成的，把插件都禁用后重启浏览器再看下。

**Comment by Sunshagon** [comment]
> > 进入阅读模式后，原页面的第一张图片都不会显示（仅不显示第一张图，其余会显示）
> 
> 肯定是你的设置造成的，把插件都禁用后重启浏览器再看下。

我刚试了一下，全禁用、重启，还是不行，而且好像是只是少数派文章的第一张图不显示，其余的，比如知乎专栏，还没发现什么问题。

**Comment by Kenshin** [comment]
我之前让你在**隐身模式下仅使用简悦的方式** 排除其它扩展的干扰，也测试了吗？

**Comment by Sunshagon** [comment]
> 我之前让你在**隐身模式下仅使用简悦的方式** 排除其它扩展的干扰，也测试了吗？

是的。但是因为大部分插件，我都默认让他在隐身模式下执行的，所以要排除插件的影响，感觉不如直接禁用插件🤣🤣

**Comment by Kenshin** [comment]
那我没啥办法了 😂

1. 不设置自动进入阅读模式
2. 使用一个新的浏览器，然后导出配置再导入到新的浏览器中，看看能否复现。

**Comment by Sunshagon** [comment]
> 那我没啥办法了 😂
> 
> 1. 不设置自动进入阅读模式
> 2. 使用一个新的浏览器，然后导出配置再导入到新的浏览器中，看看能否复现。

感觉简悦配置的问题，因为我在edge上安装简悦，未配置下，进入阅读模式，可以显示第一张图，但是导入我的配置文件后，再进入就看不见了。

**Comment by Kenshin** [comment]
肯定是配置的事情... 😂 但配置也是你设置的，所以我才让你禁用简悦的插件们。

不建议折腾了，如果你没有什么特别的数据（稍后读），直接重置吧或保留好 UID 重新安装。

**Comment by Sunshagon** [comment]
> 肯定是配置的事情... 😂 但配置也是你设置的，所以我才让你禁用简悦的插件们。
> 
> 不建议折腾了，如果你没有什么特别的数据（稍后读），直接重置吧或保留好 UID 重新安装。

这配置有点费劲，当时照着简悦教程，断断续续搞了好久🤣🤣

**Comment by Kenshin** [comment]
emmm

把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5911

然后告诉我，我瞧瞧~

**Comment by Sunshagon** [comment]
> emmm
> 
> 把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5911
> 
> 然后告诉我，我瞧瞧～
是这个地址吗？
![image](https://github.com/Kenshin/simpread/assets/43169575/3e2b0f23-eef2-4154-a185-06c570480992)

**Comment by Sunshagon** [comment]
> emmm
> 
> 把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：5911
> 
> 然后告诉我，我瞧瞧～

是这个地址吗？
![20230909_105848_240_copy](https://github.com/Kenshin/simpread/assets/43169575/d9dddc55-f776-40a7-b42a-6ff97ed977fe)

**Comment by Kenshin** [comment]
一个 `@` ...

**Comment by Sunshagon** [comment]
> 一个 `@` ...

OK 已发送🤣🤣

**Comment by Kenshin** [comment]
我看了下你的配置问题：没有复现你提到的问题。

但你的配置文件有很多问题，简单的说：你使用了同步助手的自动同步但没有使用插件管理器安装插件，所以会有一些设置无法保存的问题。

所以不清楚是否是这个问题造成的。

所以：使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式修复，同时也务必使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式安装插件。

还有，你的配置没啥东西，几个插件而已... 完全可以重新安装和设置，比现在你和我来修复这个问题要快很多。

**Comment by Sunshagon** [comment]
> 我看了下你的配置问题：没有复现你提到的问题。
> 
> 但你的配置文件有很多问题，简单的说：你使用了同步助手的自动同步但没有使用插件管理器安装插件，所以会有一些设置无法保存的问题。
> 
> 所以不清楚是否是这个问题造成的。
> 
> 所以：使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式修复，同时也务必使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式安装插件。
> 
> 还有，你的配置没啥东西，几个插件而已... 完全可以重新安装和设置，比现在你和我来修复这个问题要快很多。

那不对啊，一开始我是没用插件管理器安装，但是后来解决了那个图片插件的问题后，我把插件都用插件管理器装了一遍啊🤣🤣配置的话，开自动同步，不得需要搞自动化什么的嘛，我记得我按照教程断断续续搞了许久来着🤣🤣

**Comment by Sunshagon** [comment]
> 我看了下你的配置问题：没有复现你提到的问题。
> 
> 但你的配置文件有很多问题，简单的说：你使用了同步助手的自动同步但没有使用插件管理器安装插件，所以会有一些设置无法保存的问题。
> 
> 所以不清楚是否是这个问题造成的。
> 
> 所以：使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式修复，同时也务必使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式安装插件。
> 
> 还有，你的配置没啥东西，几个插件而已... 完全可以重新安装和设置，比现在你和我来修复这个问题要快很多。

算了，那我重来一遍吧🤣🤣

**Comment by Kenshin** [comment]
😂

我看你的配置里面有 Notion，所以建议使用 https://www.yuque.com/kenshin/simpread/mwda8s 中的某一个（比如高级版），留意教程就行了，其它都 OK~

使用配置库方案的话，不需要单独配置插件管理器，仅留意：安装新插件的时候需要使用插件管理器安装，即可。

**Comment by Sunshagon** [comment]
> 😂
> 
> 我看你的配置里面有 Notion，所以建议使用 https://www.yuque.com/kenshin/simpread/mwda8s 中的某一个（比如高级版），留意教程就行了，其它都 OK~
> 
> 使用配置库方案的话，不需要单独配置插件管理器，仅留意：安装新插件的时候需要使用插件管理器安装，即可。

OK，多谢，麻烦了🧡🧡🧡

**Comment by Kenshin** [comment]
小事情~

配置的教程很详细了，仔细照着做，不会有任何弯路，而且同步助手那边不需要再重新设置了，所以理论上几分钟就行了。
