### ISSUE TITLE
自动导入ob时稍后读标签不导入、标注的标签多了一个#

### ISSUE THREAD

**Issue by LLchenyuan** [Kenshin/simpread#5912]
### 描述这个错误

第一个标签导入如下banner_icon：
tags：No value
i dx：54

标注导入ob后的标签如下：
📌 ">Highlight ##Game 
> 的到来，今年的暑期档正式宣告

### 复现步骤

以下是markdown增强插件模板设置参数
---
title: "{{title}}"
alias: 
<% if ( unread.note && unread.title != unread.note ) { %>  - "{{note}}"
<% } %>  - "{{title}}"
created-date: {{create|yyyy-mm-dd'T'HH:MM:sso}}
type: Simpread
<% if (unread.img) { %>banner: "<%- unread.img %> "
banner_icon: 🔖
<% } -%>
tag: {{ |tag| | }} 
idx: {{idx}}
---

# {{title}}
<%
let ifURI = "http://localhost:7026/unread/"+unread.idx
%>
> [!example]- [🧷内部链接](<<%= ifURI %>>) [🌐外部链接](<<%= unread.url %>>)    
> URI:: [🧷](<<%= ifURI %>>) [🌐](<<%= unread.url %>>) 
> intURI:: [🧷内部链接](<{{int_uri}}>)

> [!md] Metadata  
> **标题**:: [{{title}}]({{url}})  
> **日期**:: [[{{create|yyyy-mm-dd}}]]  
<% if ( unread.annotations && unread.annotations.length > 0 ) { %>
## Annotations

{{annotations}}
<% } -%>
<% if ( unread.tags && unread.tags.includes('Highlights') ) { %>
![[<%% tp.file.title %>_mentions#Highlight Mentions]]
<% } -%>
<% if ( unread.refs ) { %>
## Reference   
{{-|refs}}  
<% } %>

以下是标注的
<%
let colors = [ '#B4D9FB', '#ffeb3b', '#a2e9f2', '#a1e0ff', '#a8ea68', '#ffb7da' ],
    color  = colors[ annote.color ];
-%>
📌 ">Highlight {{an_tags}} 
{{{html_format|>|{{an_html}}}}}
<% if (annote.note) { -%>
{{an_note}}
<% } %>
^sran-{{an_id}}

测试输出为这样：
---
title: "青柠起始页"
alias: 
  - "青柠起始页"
created-date: 2023-09-07T14:22:26+0800
type: Simpread
tag:  #???? （但是实际ob并没有这个）
idx: 53
---

# 青柠起始页

> [!example]- [🧷内部链接](<http://localhost:7026/unread/53>) [🌐外部链接](<https://limestart.cn/>)    
> URI:: [🧷](<http://localhost:7026/unread/53>) [🌐](<https://limestart.cn/>) 
> intURI:: [🧷内部链接](<http://localhost:7026/reading/53>)

> [!md] Metadata  
> **标题**:: [青柠起始页](https://limestart.cn/)  
> **日期**:: [[2023-09-07]]  

## Annotations

📌 ">Highlight  
> 规设置
> 
> 搜索
> 
> 自动清空搜索栏
> 
> 搜索历史

^sran-1694068252792📌 ">Highlight ##cesces##www 
> 将其回到

^sran-1694070158280📌 ">Highlight ##测试测试/测试 
> 起始页加载时自动聚焦到

^sran-1694067746607

### 其他相关说明

我不清楚是怎么回事，可能我在复制模板使用时有地方调整了

### 操作系统

windows11

### 浏览器

edge  116.0.1938.69 (正式版本) 

### 发生问题的网址

https://limestart.cn/

**Comment by Kenshin** [comment]
这个功能跟你使用的模板有关系...

我不确定你使用了哪种模板

还有，你编辑的内容似乎有点问题，也导致我没太明白你的意思，建议重新编辑，建议使用代码端

```
xxx
```

这样更清晰。

**Comment by LLchenyuan** [comment]
我用的模板是你的   定制化ob模板一，之前是删去中间的一部分，刚刚我重新全部粘帖你的模板一，好像还是一样的。可以简单将我现在的问题理解为，标签导入ob不成功，无论是标注还是稍后读。
现在这里面的代码都是你的 定制化ob模板

**Comment by Kenshin** [comment]
1. 导入到 Obsidian 优很多方案，同时简悦也提供了配置库方案，所以具体使用了哪种方式？

2. 你提供的内容还是没法看，不过模板已经说明了，建议截图再详细说明，或者看下上条的建议，
