### ISSUE TITLE
一些非论坛界面也会莫名跳出discourse辅助增强插件的提示

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#5915]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/69069739/65fb2079-504d-4726-9c67-468b27e0cb05)

如图，遇到不止一次了，无论设置成普通页模式还是论坛页模式都会跳

### 复现步骤

打开网页进入阅读模式

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/dataview/dataview%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95/13---metadata%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B/

**Comment by Kenshin** [comment]
emmm 我明天确认下～

**Comment by Kenshin** [comment]
需要关闭下面的选项，然后使用白名单方案。

<img width="490" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c568d0a0-b24a-4502-b2eb-09cd27d48b7b">

**Comment by PupupupuTong** [comment]
> 需要关闭下面的选项，然后使用白名单方案。
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/81074/266759459-c568d0a0-b24a-4502-b2eb-09cd27d48b7b.png">

就是这样设置的，还是跳

**Comment by Kenshin** [comment]
截图给我看下~

**Comment by PupupupuTong** [comment]
![image](https://github.com/Kenshin/simpread/assets/69069739/c3479ee4-1513-4525-8e57-48975b2e27a3)

**Comment by Kenshin** [comment]
白名单填入

```
cn.logseq.com
meta.appinn.net
community.openai.com
```

然后再试试。

***

是个 Bug，我先 Mark 下，明天修复

**Comment by PupupupuTong** [comment]
> 白名单填入
> 
> ```
> cn.logseq.com
> meta.appinn.net
> community.openai.com
> ```
> 
> 然后再试试。
> 
> 是个 Bug，我先 Mark 下，明天修复

似乎好了。不过悄咪咪说一句我其实没太感知到这个插件对论坛类页面的优化具体在哪，比如百度贴吧，加进白名单也还是每楼一个『该楼层疑似违规已被系统折叠隐藏此楼查看此楼』

![image](https://github.com/Kenshin/simpread/assets/69069739/193df9ac-23b9-4593-b202-3b5af6eb13da)

**Comment by Kenshin** [comment]
这个插件仅优化 Discourse 类的论坛，并不适合百度贴吧。

**Comment by Kenshin** [comment]
嗨，这个 Bug 解决了~

***

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/hXZJKhhrMI) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
