### ISSUE TITLE
因 Notion 图床 API 异常导致无法使用的汇总

### ISSUE THREAD

**Issue by Sunshagon** [Kenshin/simpread#5917]
### 描述这个错误

无法使用 Notion 图床

![20230910_224838_691_copy](https://github.com/Kenshin/simpread/assets/43169575/12da88e9-5b2e-4099-838b-9f2a845421d9)

![20230910_224909_518_copy](https://github.com/Kenshin/simpread/assets/43169575/89bd6745-9c27-441f-bd9b-bb4d1babb7cb)

### 复现步骤

进入阅读模式，按下快捷键导入 Notion 的快捷键，然后就一直转圈

### 操作系统

Win10

### 浏览器

chrome

### 发生问题的网址

*

**Comment by Kenshin** [comment]
先把 Notion 暂时关了，具体细节 https://github.com/Kenshin/simpread/issues/4995#issuecomment-1712713977

有进一步消息我会在这里通知你。

**Comment by Kenshin** [comment]
关联 https://github.com/Kenshin/simpread/issues/4995#issuecomment-1712537585

**Comment by jadetexy** [comment]
同样的情况

**Comment by ElvisLiaooo** [comment]
+1

**Comment by Marsfree** [comment]
+1

**Comment by retanoj** [comment]
still

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！

**Comment by zzrzzr0123** [comment]
+1同样卡在了这里

**Comment by Obabull** [comment]
+1

**Comment by est7** [comment]
still stuck..

**Comment by laedda** [comment]
+1 还是卡住，谢谢回复。稍后再观察吧。

**Comment by kingzeus** [comment]
+1 同样卡住了

**Comment by Kenshin** [comment]
@Obabull 

嗨，跟你提到的应该无关，只是单纯的私有 API 改参数造成的，我仍在探索。

还是谢谢你给出的思路 😄

**Comment by key153** [comment]
+1，等处理好的消息

**Comment by zoezou353** [comment]
+1 蹲后续处理

**Comment by xinghe1555** [comment]
感谢！

**Comment by zml910724** [comment]
蹲蹲。大佬辛苦了

**Comment by MegaDom** [comment]
蹲蹲~ 大佬辛苦！

**Comment by jerryc127** [comment]
蹲蹲~ 大佬辛苦！

**Comment by zzzshare** [comment]
蹲后续

**Comment by Kenshin** [comment]
嗨，各位。

## 导入到 Notion 1.1.0 版发布了 🎉  

### ▎内置 Cloudinary 图床（用来替代 Notion 图床），国内访问速度不错，免费份额足够个人使用。为什么这么做，看下面的说明

***

## 📖  写在前面

Notion 图床使用了 Notion 私有 API（甚至于导入到 Notion 也是如此 ），但 **Notion 私有 API 并没有那么稳定，基本上 Notion 每次大的升级都会造成无法使用的问题，差不多每年 1~2 次。** 比如：

- **2022年7月23日 [标题含有 CJK 字符就会出现无法保存的问题](https://github.com/Kenshin/simpread/issues/4237)**，但好在这次事件 Notion 官方快速修复了。

- **2022年12月6日 [因为 API 后端参数修改导致无法导入到 Notion Page 的问题](https://github.com/Kenshin/simpread/issues/4849)** 导致了「坏」了很久很久（现在已经好使了）

- **2023年9月7日 [发生了 Notion 图床无法使用的问题](https://github.com/Kenshin/simpread/issues/5917)（截至到现在仍未好使）**

因为是私有 API 所以 Notion 官方的任何改动都「合理」，毕竟理论上这些 API 只有 Notion 自己用。

但对于简悦来说就非常被动了，2022年12月6日后为了杜绝这个问题，简悦发布了 [导入到 Notion 插件](https://github.com/Kenshin/simpread/discussions/4954)，脱离了扩展端，因而能更快的响应 Notion API 的无故改动，但毕竟仍受 Notion 的「制约」，进而发生了这次 Notion 图床事件，导致无法使用...

## 💡 解决方案

为了不再一次次的被动，所以在【导入到 Notion 插件 1.1.0 版】 **增加了 Cloudinary 图床方案**，不再绑定 Notion 从而彻底的解决了这个问题。

对于用户来说，仅需要注册 Cloudinary 图床，而注册一个图床的时间远比被动折腾要简单很多。

## 🔐 权限

使用 Cloudinary 图床 **需要调用简悦自己的服务器，所以仅针对高级账户权限**，如有必要 [请升级为高级账户](https://simpread.pro/price)。

## 🗂 Cloudinary 图床

[Cloudinary](https://cloudinary.com/) 是老牌的图床服务，**免费版每月 25 Credit，每个 Credit 可支持 1GB 存储或 1GB 带宽**。

相当于：**每月 13GB 存储**以及 **12GB 带宽**的图床，且**国内访问速度不错**，免费份额足够个人使用。

## 配置

请看 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995 内有详细说明。

如果你动手能力稍强的话，甚至于都不需要看任何教程，直接注册登录 &  打开 [Dashboard 页面](https://console.cloudinary.com/console) 即可，留意下图

<img width="2942" alt="2023-09-27_11-39-14" src="https://github.com/Kenshin/simpread/assets/81074/29f6003c-c45d-49df-8bc5-f10c6d76253f">

请将 ➊ ➋ ➌ 分别填入。

注意：Folder 文件夹可为空，也可为任意值（ 建议使用 `simpread` ），不必事先在 Cloudinary 创建相应目录。

## 📈 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论。

**Comment by MegaDom** [comment]
感谢大佬！已经配置成功，完美上传到了 [Cloudinary] 图床。 现在还有一个小问题，就是 服务 - 自动化中，加入稍后读触发的 保存到Notion，还是使用的 Notion图床，所以上传图片还是会卡住。

![image](https://github.com/Kenshin/simpread/assets/107259784/eb0ac0e0-eeda-4f06-946e-d64c50a67b56)

**Comment by Kenshin** [comment]
@MegaDom

不要使用（选项页中的自动化）方案，正确的方式 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4500614

**Comment by MegaDom** [comment]
> @MegaDom
> 
> 不要使用（选项页中的自动化）方案，正确的方式 [#4954 (comment)](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4500614)

哦哦好滴，现在还有一个疑惑，在用了 [Cloudinary] 图床剪藏后，打开Notion里面的文章，找一张图片右键打开原图
![image](https://github.com/Kenshin/simpread/assets/107259784/9762fcff-121d-47ac-a91e-a9c5e952b87f)

发现网址是，似乎还是知乎的图床呢：
![image](https://github.com/Kenshin/simpread/assets/107259784/cfb4aad9-1f65-4cbd-9e01-64ed18f176fc)

但在 [Cloudinary] 图床里面也确实上传了这张图的。感觉像是Notion剪藏的页面，图片直接使用了知乎图片的原网址，没有换成 cloudinary的。
![image](https://github.com/Kenshin/simpread/assets/107259784/2649085d-daeb-4056-8f65-67db4f1ad8d8)

我的理解点开原图，网址是这样 res.cloudinary.com 开头的才是使用了 cloudinary 图床呀？
https://res.cloudinary.com/dvqhm39wo/image/upload/v1695791224/simpread/ea7ac155fb532a48b8497619bbb882b00bae48be6bccc962385fe64d50b46fdc.jpg


请问是我哪里没有配置对吗？

**Comment by Kenshin** [comment]
@MegaDom

看下图，打开后使用下图的导出，导出后看看 Notion 的这篇文章链接是什么。

<img width="522" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5d2078dc-1097-487c-8b64-1d6e57b1bbb2">

**Comment by MegaDom** [comment]
还是一样的结果，不嫌麻烦的话，劳烦看一下视频。

https://github.com/Kenshin/simpread/assets/107259784/2655451e-5c30-4fab-9652-826e33937e2f

**Comment by Kenshin** [comment]
@MegaDom

试试其他网页呢？我明天再确认下

**Comment by MegaDom** [comment]
似乎只有少数派使用Cloudinary图床成功了。

- [x] 少数派
- [ ] 知乎
- [ ] 微信公众号
- [ ] b站专栏
- [ ] 百度贴吧
- [ ] 机核网

**Comment by Kenshin** [comment]
@MegaDom 

我已经解决了这个问题，是因为个别图片的 URL 含有特殊字符造成的。不过，我需要你给我提供一些 https://github.com/Kenshin/simpread/issues/5917#issuecomment-1737545512 提到的这些网站的具体地址，方便我测试。

**Comment by Kenshin** [comment]
嗨，各位。

导入到 Notion 1.1.1 发布了 😂 主要是因为 @MegaDom 发现了一个 Bug

> 因图片含有特殊字符导致 Cloudinary 上传成功了但没有正确替换的错误。

我测试了

- [x] 知乎
- [x] 微信公众号
- [x] b站专栏
- [x] 百度贴吧

均可以正常显示

***

机核网比较特别，并不是不好使，而是因为它的页面规则导致 Notion 无法正确识别进没有显示造成的，我把同样的 Markdown 放到 Obsidian 中就没问题。

这个问题放到另外的 Issues 处理吧。

也感谢 @MegaDom 的帮忙测试，才让我发现了这个情况，也吐槽下一个简单的图片地址被国内某些网站玩的面目全非...

***


## 📈 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

 @MegaDom  如果还有问题的话，单开一个 Issues 讨论吧~

**Comment by MegaDom** [comment]
> @MegaDom
> 
> 我已经解决了这个问题，是因为个别图片的 URL 含有特殊字符造成的。不过，我需要你给我提供一些 [#5917 (comment)](https://github.com/Kenshin/simpread/issues/5917#issuecomment-1737545512) 提到的这些网站的具体地址，方便我测试。

感谢！感谢！刚刚我简单测试了一下，之前提到的社区网站都正常使用图床了。不过正如你所说的，国内的其他网站图片地址因为被玩坏了，所以兼容度不高。

我就另开一个Issues具体讨论哈。

**Comment by CPXOPZ** [comment]
> 嗨，各位。
> 
> 导入到 Notion 1.1.1 发布了 😂 主要是因为 @MegaDom 发现了一个 Bug
> 
> > 因图片含有特殊字符导致 Cloudinary 上传成功了但没有正确替换的错误。
> 
> 我测试了
> 
> * [x]  知乎
> * [x]  微信公众号
> * [x]  b站专栏
> * [x]  百度贴吧
> 
> 均可以正常显示
> 
> 机核网比较特别，并不是不好使，而是因为它的页面规则导致 Notion 无法正确识别进没有显示造成的，我把同样的 Markdown 放到 Obsidian 中就没问题。
> 
> 这个问题放到另外的 Issues 处理吧。
> 
> 也感谢 @MegaDom 的帮忙测试，才让我发现了这个情况，也吐槽下一个简单的图片地址被国内某些网站玩的面目全非...
> 
> 也顺道 diss 下 Notion，其实它并不适合做剪藏，但凡结构稍微异常点，它就没法正常显示。
> 
> ## 📈 安装与升级
> * 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。
> * 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
> 
> @MegaDom 如果还有问题的话，单开一个 Issues 讨论吧~

- [ ] 简书
简书平台似乎也有同样的问题 
https://www.jianshu.com/p/29ed7ec58b83

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！

**Comment by Kenshin** [comment]
@CPXOPZ

嗨，我测试了下，不是简悦的问题。

图片可以上传到 Cloudinary，再上传到后被 Cloudinary 转换为 `.webp` 格式，然后使用私有 Notion  API 时 Notion 无法显示 `.webp` 造成的。

奇怪的是，我手动将 `.webp` 粘贴到 Notion 是没问题的，所以还是 **Notion 私有 API 本身的问题**。

### 解决方案

将 `jianshu.com` 加入到延迟加载列表，这样不会自动进入阅读模式，手动进入阅读模式后的图片格式就是正常的了

<img width="1217" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/00be4f92-12ac-43e5-b52c-45b3c20ab636">

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 升级到 1.2.0 

### 重点更新：导入到 Cloudinary 时不经过简悦自己的图片服务器

旧版 1.2.0（以上）会通过简悦的自己的服务器，优点是不需要耗费用户的设备性能；缺点是当为内网图片时无法使用；

新版 1.2.0（含），不经过简悦自己的图片服务器，解决了内网图片或某些有防盗链的图片无法上传的问题。

如：

1. 近期少数派更新了图片规则，导致无法使用旧方案上传，但版方案可以正常将少数派的图片上传到 Cloudinary

    <img width="1023" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8273730d-2cb5-45e9-9170-7fe32f800f03">

2. 内网图片无法使用此功能的问题

### 其它更新

`Fix` 导入图片如果是 `http:` 形式在 Notion 无法显示的问题

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！

**Comment by HuangMou0828** [comment]
你好，在掘金全文导出到Notion，上传到Cloudinary中总是卡在某一张图片然后就反复loading（第7张图），反复尝试都不行，只是个例，其他文章都好使，附上地址链接https://juejin.cn/post/6926822995142918152#heading-2

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！

**Comment by Kenshin** [comment]
嗨，导入到 Notion 发布了全新的 2.0 版，支持一键授权（不在有繁琐的授权过程），加持简悦完美的阅读模式，同时支持导入带标注色的全文，可以彻底解决你遇到的问题。

![](https://imgs.zhubai.love/5ccaad4e75ac4610b11c966cb45f8484_2072964972706709504.png)

# 🆕 全新 2.0 版

在 2024 年 11 月 16 日，Notion 私有 API 再次出现无法使用的问题，这让我决定**彻底弃用私有 API 方案，全面转向公开 API**。

由于采用公开 API，确保了功能的稳定性，不会再出现无法使用的情况，以下所有功能均基于 2.0 版本的描述。

# 🌟 特色

与其他同类产品相比，**简悦凭借其出色的阅读模式，可以更精准地将全文导入到 Notion**。

由于采用了公共 API，解决了 1.0 版本无法无法正确转换 LaTeX 公式的问题，并提供更安全简便的一键授权方式（相比私有 API，避免了账户泄漏风险）。

此外，还支持以下功能：

1️⃣ 在 Notion Page 显示描述、题图、Favicon、来源、标签、备注

2️⃣ 内置图床

3️⃣ 导入带标注颜色的全文 [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

4️⃣ 导入标注（支持三种方式）

5️⃣ 支持超长文章的导入、[知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229)、[表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74)（使用私有 API 的产品都存在无法使用的问题）

# 📥 导入效果

[https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897](https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897&pvs=74)

# 📚 一站式教程

[https://www.yuque.com/kenshin/simpread/zx3bcz](https://www.yuque.com/kenshin/simpread/zx3bcz)

# 📦 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

如果你需要使用简悦 + Notion 的话，可以直接看 [此配置库](https://www.yuque.com/kenshin/simpread/mwda8s) 。

# 🔌 介绍

导入到 Notion 相关功能分为两个插件：

📗 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

📘 [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU)

# 📖 功能

1️⃣ 可导入当前页面的题图、Favicon、来源等。

![img](https://imgs.zhubai.love/92778b3c8dcc4b1ab1120e1dbf780d33_2072964972706709504.png)

2️⃣ 导入正文到 Notion，因为使用了公开 API，所以可以完美适配 [知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229) · [表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74) 

3️⃣ 导入**带标注色的正文**到 Notion [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

> 此功能需要 **简悦高级账户**，可通过 [**此链接**](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/c6aa20e1b1814399b9e87b569ebdb3b5_2072964972706709504.png)

4️⃣ 内置 Cloudinary 图床

![img](https://imgs.zhubai.love/85901d6d7ed74b598b1b75ab81b59754_2072964972706709504.png)

5️⃣ 在导入可选择任意 Notion

![img](https://imgs.zhubai.love/2864ffa0f9134a4b8c99116cdf12c41f_2072964972706709504.png)

6️⃣ 同步稍后读的标签，并支持加入全局标签（即使当前页面未被标记为稍后读，也可导入已添加的全局标签）。

![img](https://imgs.zhubai.love/0cda01a5740a4c35b80391dc1ac971e5_2072964972706709504.png)

7️⃣ 添加描述（Summary）与稍后读备注（Note）

> 此功能需要 **简悦高级账户**，可通过 [此链接](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/d1d8cbad7ef94f169095039cd18b9b23_2072964972706709504.png)

8️⃣ 去除重复的 Page

![img](https://imgs.zhubai.love/58668edcf264416ea6dc2d97069ce2b0_2072964972706709504.png)

9️⃣ 导入标注

![img](https://imgs.zhubai.love/59ffe6d7a1644d83ab40f2d6bc06597e_2072964972706709504.png)

2.0 版在原来的方案（[标准模式](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)）基础上增加了两个全新的标注模板：

📗 带标注色的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f5881ada61bc11c25596f1d?pvs=74)

📘 按照标注色分类的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f58814da34fd7e2e0cb9d96?pvs=74)

![img](https://imgs.zhubai.love/fc42ca0d3dc94186b02e6737febdde51_2072964972706709504.png)

注意：上述两种标注模板需要**简悦高级账户**权限，可通过 [此链接](https://simpread.pro/price) 升级。

# 🔄 旧版本升级说明

如果你已使用 1.x 版（旧版本），首次升级后会出现如下截图，此时需重新授权 Notion 才能使用。（授权方式与上面一致）

![img](https://imgs.zhubai.love/fea50a3a372d47098655eddf70022cc7_2072964972706709504.png)

# 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可直接 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)  [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

#  🔎 关联 

https://github.com/Kenshin/simpread/issues/4955

***

有任何问题，请随时在这里讨论~

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955

**Comment by Marsfree** [comment]
你的邮件已收到，谢谢，辛苦了哈！
