### ISSUE TITLE
脚本之家 无法离线下载

### ISSUE THREAD

**Issue by cangling** [Kenshin/simpread#592]
PCI、PCI-x，PCI-E 兼容以及他们之间的区别详细图解_显卡_硬件教程_脚本之家
https://www.jb51.net/hardware/xianka/56902.html

一直转换中。

离线文件原文地址是 undefined

**Comment by Kenshin** [comment]
谢谢反馈，明天确认下。

**Comment by Kenshin** [comment]
刚测试下，没有问题。

PS：你说的「离线下载」是指导出为 HTML 到本地吗？

***

附件是离线下载的 html 文件

[simpread-PCI、PCI-x，PCI-E 兼容以及他们之间的区别详细图解_显卡_硬件教程_脚本之家.html.zip](https://github.com/Kenshin/simpread/files/3747465/simpread-PCI.PCI-x.PCI-E._._._.html.zip)

**Comment by cangling** [comment]
是使用 离线下载 插件，将图片转码base64一起保存，快捷键 dl1

又测试了下面这个页面，情况一样，提示：需要转换的图片多……稍等
https://www.jb51.net/hardware/xianka/685918.html

微信这个页面，正常，保存后6M。
https://mp.weixin.qq.com/s?__biz=MzIzNDA3MDgwNA==&mid=2649230054&idx=1&sn=6fa581c156af45465c01cc48a621547b&scene=21##

还有就是 离线插件 保存的离线文件里原文地址是 undefined。

**Comment by Kenshin** [comment]
emmm...

【离线下载】这个插件是将 图片 → base64 ，所以当图片较多(大)时，会出现这种情况。

***
`存的离线文件里原文地址是 undefined`

我再确认下，可能是 Bug

**Comment by cangling** [comment]
脚本之家的图片不多，微信那个图片多，还大，很快就保存完成了。

**Comment by Kenshin** [comment]
脚本之家的问题，应该是跨域转换图片造成的。

PS：我详细考虑下你说的这几个功能，下个版本会一起发布。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

新增加了【原生的离线下载】，此问题已解决

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
