### ISSUE TITLE
无法打开稍后读，不能删除错误的稍后读，导致现在无法标注到obsidian中了

### ISSUE THREAD

**Issue by zqz365001** [Kenshin/simpread#5920]
### 描述这个错误

我是老用户，现在标注文件有1860多，因为没打开obsidian就进行标注，导致发生标注错误，稍后读也无法打开了，最后不能进行正常标注了。我所使用的obsidian版本是  ![image](https://github.com/Kenshin/simpread/assets/27180737/72d91fed-e884-4215-822c-f0cb91249a47)

### 复现步骤

obsidian中进行的标注 ![image](https://github.com/Kenshin/simpread/assets/27180737/73caa83a-b7eb-441c-a87c-64555b1a409f)
存放到本地的html文件 ![image](https://github.com/Kenshin/simpread/assets/27180737/a1357b09-2a00-4b57-bef6-69e72bcae042)
网页中无法打开稍后读了 ![image](https://github.com/Kenshin/simpread/assets/27180737/486e4306-c50d-4467-aa48-066b2599d822)

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)

### 发生问题的网址

https://blog.csdn.net/qq_33377547/article/details/126596652

**Comment by Kenshin** [comment]
嗨，很容易解决~

1. 重启同步助手后在重启浏览器试试。（如果不行看下条）

2. 可能是因为 `simpread_config.json` 结构错误造成的，使用 https://github.com/Kenshin/simpread/discussions/5750 修复（建议先留存一份 `simpread_config.json`
