### ISSUE TITLE
进入阅读模式后无法标注

### ISSUE THREAD

**Issue by fbl1999** [Kenshin/simpread#5922]
### 描述这个错误

在阅读模式下开启标注功能, 选中文本后不能标注。之前一直能用的。
![image](https://github.com/Kenshin/simpread/assets/104347744/a3cfe6ad-0281-4924-86fa-f0fc97001bfa)

### 复现步骤

无

### 操作系统

windows

### 浏览器

Edge 116.0.1938.76 

### 发生问题的网址

https://mp.weixin.qq.com/s/_ElpqpwsiOGRmWT7Z332Nw?poc_token=HKRnAGWj1eRIUNbagnh695o6OfKDaRdXaWHwgLP7

**Comment by Kenshin** [comment]
其他页面有这个问题吗？极个别的页面存在无法标注的问题，印象中大概有两例报告。

**Comment by fbl1999** [comment]
不是个别的页面, 是所有页面, 我也尝试打开前天可以标注的页面, 现在也无法标注了.

**Comment by Kenshin** [comment]
emmm 看看是否能打开稍后读？如果不能的话，是不是使用了同步助手的自动同步功能？如果是的话。

嗨，很容易解决~

1. 重启同步助手后在重启浏览器试试。（如果不行看下条）

2. 可能是因为 `simpread_config.json` 结构错误造成的，使用 https://github.com/Kenshin/simpread/discussions/5750 修复（建议先留存一份 `simpread_config.json`

**Comment by fbl1999** [comment]
感谢开发大大, 根据第二条建议已成功解决

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 Issues 了

除了上面提到的方案，还有：同步助手的历史记录功能 https://github.com/Kenshin/simpread/discussions/5748 或者使用坚果云的历史记录功能。

可以还原任意时间点的数据。

**Comment by julian20220130** [comment]
开发大大你好，遇到同样的问题。没有使用同步助手，不能打开稍后读。在不能使用前，正在设置导出到 obsidian 插件，不知道是哪些步骤后，就无法生成标注了。点击控制面板中的“停用标注”按钮也无反应。
<img width="218" alt="iShot_2023-09-26_18 58 04" src="https://github.com/Kenshin/simpread/assets/98684721/cb513d37-6dbe-4c88-9f50-7dc9b84bfe72">

**Comment by julian20220130** [comment]
<img width="164" alt="image" src="https://github.com/Kenshin/simpread/assets/98684721/08b8e056-349b-4e52-a4e5-0420c5e01a2d">
恢复之前的设置，或者重启浏览器或者重启插件后都无法恢复到之前的状态。

**Comment by julian20220130** [comment]
还存在的。我临时的解决方案是把旧电脑上的设置强制覆盖到本机，于是能够重新标注和导入 obsidian 了。
损失是原来的配置文件中存的一些稍后读和活跃页面都没了。
请大大方便时帮忙查看怎么解决。

**Comment by Kenshin** [comment]
@julian20220130 

1. 你的稍后读能打开吗？
2. 确定没用同步助手？

PS：只要有配置文件就没多大事～

**Comment by julian20220130** [comment]
稍后读无法打开；
确定没用同步助手，使用的坚果云手动同步；
不能显示之前在进行导入到 obsidian 选项设置。

**Comment by Kenshin** [comment]
@julian20220130 

把出问题的配置文件发送到 `help@simpread.pro` 并注明 #5922 我白天看下。

**Comment by julian20220130** [comment]
麻烦问下开发大大这个问题找到解决方法了吗？我用之前的配置文件覆盖解决后，使用了一段时间今天又出现无法标注的情况了，稍后读 同样无法打开，这次是在正常使用的情况下没有任何预兆的发生。

**Comment by Kenshin** [comment]
这是因为配置文件里面的数据结构错误造成的，以我的经验来看，一般发生在两种情况：

1. 使用 API 加入稍后读

2. 手动删除自动化服务

只有在发生错误时，把配置文件发给我才能判断具体是什么问题造成的。

**Comment by julian20220130** [comment]
不太理解手动删除自动化服务是指什么，但目前来看两个操作我都没有进行过。
之前出问题的配置文件已经按发到help@simpread.pro了，坐等回复中。
本次出问题的配置文件被我覆盖掉了，所以无法发送。

**Comment by Kenshin** [comment]
okay 我明天研究下，再回复你。

**Comment by Kenshin** [comment]
嗨，抱歉，之前漏掉了这个 Issues 😂

邮件已发，请查看，应该是有一个稍后读数据出错造成的。

选项页 → 共通 → 从本地导入配置文件就行了。如果觉得仍有问题：

1. 重装简悦
2. 导入这个配置文件
3. 重启浏览器
4. 选项页 → 插件管理 → 从配置文件导出插件
5. 重启浏览器

**Comment by julian20220130** [comment]
收到~问题已解决。非常感谢开发大大！

**Comment by Kenshin** [comment]
哈，解决就好。 👍
