### ISSUE TITLE
在阅读模式中，关于目录是否应该固定在左侧的建议

### ISSUE THREAD

**Issue by AsQ335** [Kenshin/simpread#5923]
### 请描述你的建议或任何内容

在阅读模式中，能不能让目录可以被鼠标拖动，或者可以调整到上下左右、屏幕顶部末尾这种的，最好可以实现类似右上角滑动、3次点击左键这种动作，目录就能自动浮现或者隐没，可以不用转头就能看见目录就好。

**Comment by Kenshin** [comment]
进入阅读模式后，右下角，然后看下图

<img width="475" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c04232ab-815b-4dc0-92f2-afbf3e0b15d5">

至于你提到的 `鼠标拖动，或者可以调整到上下左右、屏幕顶部末尾这种的` 没有太大的意义 😂

**Comment by AsQ335** [comment]
谢谢

**Comment by Kenshin** [comment]
搞定就好~

**Comment by Kenshin** [comment]
😂 …

**Comment by AsQ335** [comment]
所以我才建议可以在中间顶部，连头都不用转动就可以看到目录☺️

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
