### ISSUE TITLE
小红书网页版适配问题

### ISSUE THREAD

**Issue by ElvisLiaooo** [Kenshin/simpread#5924]
### 描述这个错误

小红书网页版目前适配有两个问题
1. 会解析出页面中不存在的表情图片
例如链接：https://www.xiaohongshu.com/explore/6500647b000000001f03cb53?m_source=pwa
<img width="1399" alt="image" src="https://github.com/Kenshin/simpread/assets/142693478/a520fe69-a2bc-4354-a52d-fb673a0c2782">
阅读模式会解析出来
![telegram-cloud-photo-size-5-6057871575543297795-y](https://github.com/Kenshin/simpread/assets/142693478/7ddce831-e09e-414c-9e55-50f86d2de78b)
里面含有文章和评论中都不存在的表情图

2. 执行图床转换或保存到notion是莫名其妙会触发页面刷新中断整个流程

### 复现步骤

打开小红书部分文章页面进入阅读模式即可浮现
举例url：
https://www.xiaohongshu.com/explore/6500647b000000001f03cb53?m_source=pwa
https://www.xiaohongshu.com/explore/62896f390000000001024186?m_source=pwa

### 操作系统

macOS 14.0

### 浏览器

Chrome Version 116.0.5845.179

### 发生问题的网址

https://www.xiaohongshu.com

**Comment by Kenshin** [comment]
适配规则更新了，看下图

<img width="916" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bd288e6f-6815-4035-a0d3-04ce548daadb">
