### ISSUE TITLE
导入文章到obsidian提示保存失败

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#5925]
### 描述这个错误

K大你好，
最近我尝试将SimpRead的阅读配置库迁移到自己的其他库中，发现无法进行导出。然后我又将配置（主要是将目录（Simpread网页端插件目录）改成原来库的目录），结果提示保存失败. 

![image](https://github.com/Kenshin/simpread/assets/57386018/0b3da9b4-2d51-43b6-abd1-7a0834a97b56)

以下是配置目录：
![image](https://github.com/Kenshin/simpread/assets/57386018/4cb8e665-c231-4661-9989-4bf7d41bb6f2)

其中有更新obsidian installer version, 到1.3.5， 为了体验obsidian的新版Property属性功能. 

### 复现步骤

1. 参考此issuehttps://github.com/Kenshin/simpread/issues/5556，将“导入到obsidian选项”网页端插件，库目录更改成嵌入的库名称. 
2. 将SimpRead obsidian插件 复制到新的库Plugin目录下，并启用激活
3. 浏览器打开微信文章，并用Quicker快捷键模拟热键“DD”，尝试将文章导入到obsidian，出现报错：保存失败. 
4. 新库的文件夹目录“SimpRead”无法找到新文章. 
5. 在库外的SimpRead配置目录下，能找到OutPut文件夹下的新导入文章. 
![image](https://github.com/Kenshin/simpread/assets/57386018/4654fb35-11c5-45a1-afae-029ac2192035)
6. 还原浏览器Simpread插件“导入到obsidian选项”库目录为原来的库名称（使用的是复制粘贴方式，确保无误）
8. 以下是具体配置图：
9. 
![image](https://github.com/Kenshin/simpread/assets/57386018/f293aa8b-05c0-404a-9c45-b13a2209be49)
![image](https://github.com/Kenshin/simpread/assets/57386018/951b5294-70b9-4bf2-a767-7017ddee452c)

### 操作系统

Win11

### 浏览器

Edge: 版本 116.0.1938.76 (正式版本) (64 位)

### 发生问题的网址

https://mp.weixin.qq.com/s/E3pH4CZyfQLouWpxEstXWA

**Comment by Kenshin** [comment]
emmm 

把 Obsidian 结构和导入到 Obsidian 选项截图和我看下。

我上午有事外出，下午能继续看你的问题。

**Comment by mdsnalw** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年09月14日 08:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 导入文章到obsidian提示保存失败 (Issue #5925) |

emmm

把 Obsidian 结构和导入到 Obsidian 选项截图和我看下。

我上午有事外出，下午能继续看你的问题。

**Comment by mdsnalw** [comment]
> emmm
> 
> 把 Obsidian 结构和导入到 Obsidian 选项截图和我看下。
> 
> 我上午有事外出，下午能继续看你的问题。

感谢K大抽空帮忙查看问题，这个不急，您有空查看处理即可，感谢~
图一：obsidian库外结构：
![image](https://github.com/Kenshin/simpread/assets/57386018/1fc424f2-2f70-4c76-8df8-9436cea1a521)
图二：obsidian库下文件夹结构：
![image](https://github.com/Kenshin/simpread/assets/57386018/d371bd55-e251-47d4-954d-56a03835fcda)
图三：obsidian界面下文件夹结构：
![image](https://github.com/Kenshin/simpread/assets/57386018/f5409ae9-5903-4768-be59-8ba6a5aa878c)
图四：obsidian下SimpRead Sync同步插件配置（这部分没有做任何变更），同理SimpRead同步助手也是保持默认，没有变更
![image](https://github.com/Kenshin/simpread/assets/57386018/9ce06f7e-7975-4817-93f0-f51e174441e2)

**Comment by Kenshin** [comment]
<img width="619" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/539cd073-c5c1-477f-badd-fe2e2239f15f">

你在 Obsidian 插件设置中的内容应该跟上图一致。

另外，试试手动导入标注到 Obsidian

<img width="404" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/55f647e0-5a23-4952-ab8f-b982562c550b">

留意下图的设置

<img width="601" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/55a71142-470c-4883-b4ea-5b4057da76e9">

重启 Obsidian 确保只有一个库在使用。

**Comment by mdsnalw** [comment]
![image](https://github.com/Kenshin/simpread/assets/57386018/f5aa0f7b-b3f4-4942-b9e3-1feb8976623c)
配置是一致的，上图是SimpRead的浏览器端设置.
![image](https://github.com/Kenshin/simpread/assets/57386018/ea8994ba-2126-4c3b-91d5-96196fd83f28)

上图是obsidian端SimpRead同步插件设置. 
![image](https://github.com/Kenshin/simpread/assets/57386018/cbc22481-5205-430b-b104-c1d751564524)

上图是浏览器导出obsidian端设置，复查了下，也是一致的. 
目前已经禁用掉其他库的SimpRead插件，并卸载. 

![image](https://github.com/Kenshin/simpread/assets/57386018/144b93a3-11e3-440f-bc67-f2b8700ff558)

点击手动导入标注也是提示“保存”失败的报错.

**Comment by Kenshin** [comment]
我知道什么问题了... 注意下图

**Comment by mdsnalw** [comment]
端口错了吗(捂脸)，我刚关电脑，晚上检查后再回复你哈



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年09月14日 18:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 导入文章到obsidian提示保存失败 (Issue #5925) |

我知道什么问题了... 注意下图

**Comment by Kenshin** [comment]
不是端口错了，是 URL 错误了 正确的是 `http://localhost:7027`

**Comment by mdsnalw** [comment]
确实好像是我的URL链接有问题，我先尝试修改看看能否正常导入：
![image](https://github.com/Kenshin/simpread/assets/57386018/2705d1bd-6db2-4e08-b854-6c7de2d6cd45)

**Comment by mdsnalw** [comment]
目前的情况是：
1. 新添加到稍后读的指令会提示报错:(不知道重新对浏览器进行高级版取消授权和重新添加授权能否解决）
![image](https://github.com/Kenshin/simpread/assets/57386018/5f89dfb6-b80c-461d-9e53-1b8668725db3)
2. 新添加的标注文件在我的obsidian SimpRead库里面能够搜索的到了，这么来说文件保存的路径应该是没错的。
![image](https://github.com/Kenshin/simpread/assets/57386018/72ff0936-de0f-40a7-bfe6-cd2ea5f19836)
![image](https://github.com/Kenshin/simpread/assets/57386018/9563c454-cf46-49a1-a865-73855e1783c2)
3. 有个疑问，如果我需要把原文也导入到obsidian，以参考和对比，需要在网页端的SimpRead插件做什么配置？感谢！
![image](https://github.com/Kenshin/simpread/assets/57386018/c9e8c3ca-e51c-457e-9d54-d80de9b90d6b)

**Comment by Kenshin** [comment]
> 新添加到稍后读的指令会提示报错:(不知道重新对浏览器进行高级版取消授权和重新添加授权能否解决）

看下你的自动化以及自动化辅助增强插件都设置哪些自动化方案。

> 有个疑问，如果我需要把原文也导入到obsidian，以参考和对比，需要在网页端的SimpRead插件做什么配置？感谢！

导入全文到 Obsidian 不需要在自动化里面设置。如果你用了配置库方案的话，自然就包含了这个功能。或者看下图

<img width="586" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5052ce53-2a55-407a-8b72-41738ddadabf">

或者也可以看下 https://www.yuque.com/kenshin/simpread/fr8zo5 这个教程。

**Comment by mdsnalw** [comment]
> > 新添加到稍后读的指令会提示报错:(不知道重新对浏览器进行高级版取消授权和重新添加授权能否解决）
> 
> 看下你的自动化以及自动化辅助增强插件都设置哪些自动化方案。
> 
> > 有个疑问，如果我需要把原文也导入到obsidian，以参考和对比，需要在网页端的SimpRead插件做什么配置？感谢！
> 
> 导入全文到 Obsidian 不需要在自动化里面设置。如果你用了配置库方案的话，自然就包含了这个功能。或者看下图
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/81074/268163323-5052ce53-2a55-407a-8b72-41738ddadabf.png">
> 或者也可以看下 https://www.yuque.com/kenshin/simpread/fr8zo5 这个教程。

目前是都正常了哈，原文和标注都能正常导出了，大佬果然是非常给力，再次感谢！我重下新检查了下，稍后读快捷键按钮都是默认的配置。我用的Quicker动作，也是设置了一样的快捷键DD. 另外，请问下，如果我后续尝试将SimpRead迁移到新的库做统一管理，除了上面所提及的，检查路径更新，保持Windows下打开的obsidian库唯一性，和导出增强选项的快捷键设置和obsidian库目录问题，启用自动同步，应该问题不大吧？

**Comment by Kenshin** [comment]
> 如果我后续尝试将SimpRead迁移到新的库做统一管理，除了上面所提及的，检查路径更新，保持Windows下打开的obsidian库唯一性，和导出增强选项的快捷键设置和obsidian库目录问题

是的，其实了解思路后很简单，就是确保路径一致就好。

***

PS：你可以留存好配置文件，然后用一个新浏览器以及配置一个 Obsidian 库设置它们。

**Comment by mdsnalw** [comment]
> > 如果我后续尝试将SimpRead迁移到新的库做统一管理，除了上面所提及的，检查路径更新，保持Windows下打开的obsidian库唯一性，和导出增强选项的快捷键设置和obsidian库目录问题
> 
> 是的，其实了解思路后很简单，就是确保路径一致就好。
> 
> PS：你可以留存好配置文件，然后用一个新浏览器以及配置一个 Obsidian 库设置它们。

谢谢大佬解答，这是个很好的思路，我有空再研究研究这个方案哈，这个Issue可以关了哈，麻烦了~

**Comment by Kenshin** [comment]
okay 有任何问题可以随时 Issues 

https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb 这个链接是关于合并 Obsidian 库的教程，有需要你可以瞧瞧。

**Comment by mdsnalw** [comment]
收到，非常感谢👍



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2023年09月15日 18:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] 导入文章到obsidian提示保存失败 (Issue #5925) |

okay 有任何问题可以随时 Issues

https://www.yuque.com/kenshin/simpread/wq35mh#a74dcbfb 这个链接是关于合并 Obsidian 库的教程，有需要你可以瞧瞧。
