### ISSUE TITLE
操作系统win7下简悦同步助手1.2.0开启后Alt +F4关闭功能全局失效。

### ISSUE THREAD

**Issue by shanlei-yi** [Kenshin/simpread#5929]
### 描述这个错误

操作系统win7，简悦同步助手1.2.0。简悦插件2.2.0.520，Google Chrome 109.0.5414.120。
也存在全局占用 Alt +F4 的问题。因是公司电脑中短期不能升级win10。能否修复下这个问题

### 复现步骤

win7下打开简悦同步助手1.2.0后alt+f4的关闭文件或程序功能失效。
关闭简悦同步助手1.2.0后该快捷键可以使用。

### 操作系统

widows7

### 浏览器

Google Chrome 109.0.5414.120

### 发生问题的网址

无

**Comment by Kenshin** [comment]
同步助手有删除全局快捷键的功能，你找下，找不到我一会给你截图。
