### ISSUE TITLE
关于合辑的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5931]
作者你好！我又发现一个和教程不符的地方，当多选之后，并没有【加入到合辑】的按钮，其次这个合集和标签功能的区别是什么呢？标签同样可以将同主题的东西汇总
![image](https://github.com/Kenshin/simpread/assets/45447994/f66a4056-1ab2-4e33-9622-568730863237)

_Originally posted by @takeiteasyman in https://github.com/Kenshin/simpread/discussions/4519#discussioncomment-7014731_

**Comment by Kenshin** [comment]
@takeiteasyman

嗨，这个问题跟稍后读本地化无关了，所以我帮你新建了一个 Issues，并删除了原来位置的内容。

***

合辑只能加入标注或稍后读，所以你所选的位置是错的。

<img width="1199" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4be6457b-3ae2-4357-9d9b-bc510ae34ed0">

> 其次这个合集和标签功能的区别是什么呢？标签同样可以将同主题的东西汇总

你可以理解【合辑】比标签更精细化，可以在「一个页面」上查看。

**Comment by takeiteasyman** [comment]
好的，谢谢

**Comment by Kenshin** [comment]
😄
