### ISSUE TITLE
账号迁移出现问题

### ISSUE THREAD

**Issue by mining-id** [Kenshin/simpread#5932]
### 描述这个错误

1. 我是chrome的高级帐户
2. 最近在使用arc浏览器，希望可以在arc中也使用简悦
3. 我的操作是在chrome中点击“导出配置文件到本地”，然后在arc浏览器中点击“从本地导入配置文件”

<img width="952" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/18c3a6d4-2f25-47b0-863f-4e3ea52417f7">
4. 现在两端都不能使用了，具体表现在：

- chrome浏览器中，无法使用导出到notion（这是我使用简悦的主要场景），表现为一直正在保存中，重新授权notion也不行

<img width="369" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/90f0405f-ae1b-4db3-b3eb-0c1fa65f062d">

- arc浏览器中，无法安装插件，安装后，仍然显示“没有任何插件”

<img width="886" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/e0966ba1-6dab-4349-9757-1d134aa289d8">

### 复现步骤

见错误描述

### 操作系统

macos

### 浏览器

chrome、arc

### 发生问题的网址

https://baijiahao.baidu.com/s?id=1750425177065956276

**Comment by Kenshin** [comment]
> 问题 1

这不是简悦（或你）的问题，细节 https://github.com/Kenshin/simpread/issues/5917

> 问题 2

简悦选项页 → 插件管理 → 从配置文件导入插件

**Comment by Kenshin** [comment]
补充下：插件太太了，所以数据文件仅包含插件的配置数据，所以在新的浏览器需要重新导入一次~

**Comment by mining-id** [comment]
@Kenshin 
问题2解决了，感谢！
关于问题1，在反馈两个信息供参考：
- 我16日还同步了一篇公众号文章，然后是在做晚发现同步不了的
- 我按照 #5917 的引导，关闭了图床功能，然后同步的时候，还是提示上传图片中，重新授权也不行
<img width="940" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/3840b97f-afa7-4738-bbfa-cff358eb4ef2">

<img width="430" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/69846087-7e23-48dc-85cc-dea5a3731764">

**Comment by Kenshin** [comment]
关闭图床后建议重启浏览器测试。

另外，是否使用了同步助手的自动同步？

**Comment by mining-id** [comment]
@Kenshin 
1. 重启也不行
2. 没有使用同步助手，也没有自动同步
<img width="898" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/f329091a-3cbb-429b-bd42-0f54090a60e4">

**Comment by Kenshin** [comment]
emmm 录屏看下

**Comment by Kenshin** [comment]
提示下：

1. 在 https://sspai.com/post/69972 测试，把图床选项关闭，然后保存，然后重启浏览器。
2. 你是否也安装了其它插件？如果有的话，也试试能否修改它们的设置。

**Comment by Kenshin** [comment]
emmm 

你进入阅读模式后，右下角 → 动作 → 插件触发器 → 导入到 Notion 

如果有的话，说明你用的是这个方案… 打开「导入 Notion 选项」

**Comment by mining-id** [comment]
<img width="598" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/5ef3e9f0-96aa-4fb0-b047-dff2a4d4306a">
谢谢，在这里面关闭图床就正常了。
请问这个地方和扩展设置-服务-授权管理有什么区别？

后者我不用管了么？

**Comment by Kenshin** [comment]
与扩展端的区别看这里 https://github.com/Kenshin/simpread/discussions/4954

PS：除非你用了配置库方案，否则这个插件是你自己安装的...

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  解决了图床问题，详细说明 & 讨论请前往 #5917
