### ISSUE TITLE
更换浏览器后稍后读数据丢失

### ISSUE THREAD

**Issue by MediCoderHZ** [Kenshin/simpread#5933]
### 请描述你的建议或任何内容

在更换浏览器后，即使同步了配置文件，但是在新的浏览器中打开之前批注过的网站，不能同步之前的数据

**Comment by Kenshin** [comment]
旧浏览器 → 简悦选项页 → 共通 → 导出配置文件到本地

新浏览器 → 简悦选项页 → 共通 → 导入配置文件 → 会自动刷新 → 插件管理 → 从配置文件导入插件

还有，你提供的信息太少，我没法判断，最好详细描述你的操作步骤。
