### ISSUE TITLE
插件提示：插件 代码段增强( 包括: 高亮 支持 CSDN 等特殊情况的代码 )运行时出错

### ISSUE THREAD

**Issue by AsQ335** [Kenshin/simpread#5934]
### 描述这个错误

插件 代码段增强( 包括: 高亮 支持 CSDN 等特殊情况的代码 )运行时出
错，可以的话，请提交此问题 

### 复现步骤

1. 出现错误的网址：https://mp.weixin.qq.com/s?__biz=MjM5Njg5NDgwNA==&mid=2247484058&idx=1&sn=a2621bc27c74b313528eefbc81ee8c0f&chksm=a6e303a191948ab7d06e574661a905ddb1fae4a5d9eb1d2be9f1c44491c19a82d95957a0ffb6&scene=178&cur_album_id=1532487451997454337#rd

2. 出现错误的环境：win7系统 + chrome 版本 109.0.5414.120（正式版本） （64 位）
3. 
![1694998463275](https://github.com/Kenshin/simpread/assets/55351034/c3fa727d-ecf3-44d3-91a6-903c7273dc3e)

### 操作系统

win7

### 浏览器

chrome 版本 109.0.5414.120（正式版本） （64 位）

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MjM5Njg5NDgwNA==&mid=2247484058&idx=1&sn=a2621bc27c74b313528eefbc81ee8c0f&chksm=a6e303a191948ab7d06e574661a905ddb1fae4a5d9eb1d2be9f1c44491c19a82d95957a0ffb6&scene=178&cur_album_id=1532487451997454337#rd

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 我关闭此 Issues 了。

PS：代码段的问题都比较「麻烦」😂
