### ISSUE TITLE
你们的主页找氪金入口都很难找

### ISSUE THREAD

**Issue by AsQ335** [Kenshin/simpread#5936]
### 请描述你的建议或任何内容

好产品要敢于做商业化，大大方方的收钱。为爱发电，无法持久的服务用户。你们的买断制确实便宜。把高级账户入口在主页上做的浅一点
![image](https://github.com/Kenshin/simpread/assets/55351034/e92724bc-6f6a-4ee6-8684-5e76cd622363)

**Comment by Kenshin** [comment]
谢谢。😄

1. 当你下载简悦并使用简悦后就知道如何购买了。

2. 你截图的界面确实是免费使用的，因为是 1.x 时代的简悦。

3. 页面上方点击 简悦 2.0 后会有「惊喜」

**Comment by Kenshin** [comment]
再提几句：

1. 你看到的价格不是最终价格，你可以理解早鸟价。

2. 因为是基于本地的产品，所以打算是做长期，而不是短期，所以价格方面也就无所谓了。

3. 简悦目前活的很好   😏 

4. 至于入口的话，我想「有需要的自然就会发现和购买，否则购买后也会事儿很多」

**Comment by AsQ335** [comment]
在等邮件了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
