### ISSUE TITLE
关于中文和英文分开设置格式的建议

### ISSUE THREAD

**Issue by AkashikOctopus** [Kenshin/simpread#5939]
### 请描述你的建议或任何内容

大佬好，我主要将这个插件用于学术阅读和学习，平时英文默认为times new roma，中文为其他格式，但是在您的插件里面只能设置全部的字体，也就是中英文都是一个字体，能否在下一个版本中增加一个分开设置的功能呢？

**Comment by Kenshin** [comment]
嗨，你可以这样设置：随便进入一个页面的阅读模式 e.g.  https://sspai.com/post/69972

右下角 → 字体类型 → 自定义字体

<img width="474" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dc4cc2d3-d4cd-4695-8180-77525ebb62b1">

将下面的代码

```
'Times New Roman','Microsoft YaHei'
```

加入其中，留意下图的说明

<img width="909" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/97bd8f9b-0172-421f-86bd-6c53fef3728d">

***

1. 简悦有很多字体定制方案，[详细说明](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Atheme)

2. 如果上面方案失效的话  👉  [当使用了简悦自带的字体或自定义字体后无法生效的说明](https://github.com/Kenshin/simpread/discussions/1864) 你可以使用上面链接提到的 Stylus 方案。
