### ISSUE TITLE
导入到 Notion 图床问题

### ISSUE THREAD

**Issue by xinghe1555** [Kenshin/simpread#5940]
### 描述这个错误

我的设备是Mac book，浏览器是谷歌，版本 117.0.5938.62（正式版本） (arm64)
无论是关闭浏览器，还是重启电脑，都不行

### 复现步骤

1.打开文章
2.点击简悦插件，进入阅读模式
3.提示，未打开简约同步助手，此时，我打开同步助手，并刷新页面，重新进入阅读模式
4.点击「保存到notion」
5.一直卡在保存第一张图片中……

### 操作系统

macOS

### 浏览器

版本 117.0.5938.62（正式版本） (arm64)

### 发生问题的网址

https://mp.weixin.qq.com/s/FmPKPQnLGlW7SrfrQATB9Q?poc_token=HNgrCGWjg7-tAvsgcPLtj6PfcourTPGIF7Cna0uU

**Comment by Kenshin** [comment]
嗨，细节和原因请看 https://github.com/Kenshin/simpread/issues/5917 

我关闭这个 Issues 了，当有进一步消息我会在上面这个链接通知（艾特）你~

**Comment by xinghe1555** [comment]
好的 感谢！

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  解决了这个问题，详细说明 & 讨论请前往 #5917

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
