### ISSUE TITLE
卡在导出Notion界面上

### ISSUE THREAD

**Issue by Arthurwu24** [Kenshin/simpread#5941]
### 描述这个错误

在保存文章到Notion的过程中，一直卡在正在导出

![screenshot](https://github.com/Kenshin/simpread/assets/9261202/579e8c71-4fc0-4c1a-9c66-c4477b218849)

### 复现步骤

1. 打开这个网站（https://www.panewslab.com/zh/articledetails/2tx7w80g.html )
2. 使用简悦导出到Notion功能
3. 卡在了「正在上传图片到Notion，当前进度1/17」

### 操作系统

macOS

### 浏览器

Chrome Version 115.0.5790.170 (Official Build) (arm64)

### 发生问题的网址

https://www.panewslab.com/zh/articledetails/2tx7w80g.html

**Comment by Kenshin** [comment]
嗨，细节和原因请看 https://github.com/Kenshin/simpread/issues/5917 

我关闭这个 Issues 了，当有进一步消息我会在上面这个链接通知（艾特）你~

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  解决了这个问题，详细说明 & 讨论请前往 #5917
