### ISSUE TITLE
有的网页进入阅读模式后，代码域的边界显示不出来

### ISSUE THREAD

**Issue by AsQ335** [Kenshin/simpread#5942]
### 描述这个错误

有的网页进入阅读模式后，代码域的边界显示不出来
原始网页截图：
![1695092567173](https://github.com/Kenshin/simpread/assets/55351034/7dc8c39a-02dd-4c81-be43-990beab9ecdb)

阅读模式渲染效果：
![1695092546404](https://github.com/Kenshin/simpread/assets/55351034/b4433c77-8fb8-4ed3-a72e-6a7df33fe395)

### 复现步骤

打开网页即可看到

### 操作系统

win7

### 浏览器

chrome 版本 109.0.5414.120（正式版本） （64 位）

### 发生问题的网址

https://blog.csdn.net/u014044624/article/details/103896081

**Comment by Kenshin** [comment]
okay 收到，代码段的问题会集中在 #500 并关闭此 Issues 了。
