### ISSUE TITLE
小红书无法获取正文，只能提取图片

### ISSUE THREAD

**Issue by chanjeng** [Kenshin/simpread#5947]
### 需要适配的新站

https://www.xiaohongshu.com/explore/645911520000000027029008

### 有需要请描述这个站的性质

进入阅读模式，显示检测到正文获取异常，只能提取图片，无法提取正文 
适配列表已经更新到最新（386）
重启后也没有解决问题，请教如何修复，谢谢。

**Comment by Kenshin** [comment]
嗨，这个站是已经适配了，如何使用 https://github.com/Kenshin/simpread/discussions/5254

**Comment by Kenshin** [comment]
> 用edge浏览器提取就没问题，请问这与浏览器设置有关系吗？

理论上没关系，但你可以试试在 Chrome 使用 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by chanjeng** [comment]
> > 用edge浏览器提取就没问题，请问这与浏览器设置有关系吗？
> 
> 理论上没关系，但你可以试试在 Chrome 使用 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

你好，隐身模式使用确实提取了正文，看来是某些扩展干扰了，我进行排查，谢谢。

**Comment by Kenshin** [comment]
okay 你可以试试「二分法」用不了多久能定位到。
