### ISSUE TITLE
阅读模式下暗色模式下无法切换主题色

### ISSUE THREAD

**Issue by circle925** [Kenshin/simpread#5949]
### 描述这个错误

阅读模式下多项无法调整
包括
标题颜色无法随主题改变
每一条的背景色无法随主题改变，固定为白色
版面宽度无法调整
头像显示有问题
安装双击查看图片插件 图片高度无法调节

### 复现步骤

系统win11
浅色 深色模式均存在问题
浏览器chrome edge 均有问题
隐身模式关闭所有其他扩展程序可复现
已开启深色模式跟随系统
使用了同步助手
![屏幕截图 2023-09-21 033902](https://github.com/Kenshin/simpread/assets/64564837/fdfb6d0a-305e-493b-b00a-bc79b20927ed)
![屏幕截图 2023-09-21 033936](https://github.com/Kenshin/simpread/assets/64564837/f0bd79a7-4255-4773-9f61-5f457c0a2af4)

### 操作系统

win11

### 浏览器

chrome/edge

### 发生问题的网址

chiphell.com

**Comment by circle925** [comment]
回复真快！搞懂了，谢谢:D

昨天不知为啥尝试了开跟随和不开跟随，都没解决，今天关掉跟随系统就好了，可能因为昨天没尝试强刷新也没重启浏览器，设置没启用吧

**Comment by Kenshin** [comment]
小事情 😄

> 安装双击查看图片插件 图片高度无法调节

这个问题你可以试试在其它页面是否存在？ e.g. https://sspai.com/post/69972

chiphell.com 对页面的限制还挺多的。

***

暗色主题的问题，你可以试试安装 https://simpread.ksria.cn/plugins/details/tbjTx33iAA 它可以在暗色模式下调整主题。

之所以在暗色模式下无法调整主题是因为：用户本身选择了（系统的）暗色模式，然后还改成亮色的，感觉有点奇怪 😂

**Comment by circle925** [comment]
之前关掉跟随系统就好了，今天突然又变成图片上那样了，开关暗色模式跟随系统或者是win11切换成浅色模式都不解决问题。

**Comment by circle925** [comment]
所有URL
安装了，安装或卸载Safari样式插件都没效果
确认是关闭状态，重启后也无效

**Comment by Kenshin** [comment]
录屏给我我看下

**Comment by Kenshin** [comment]
有点意思…我不知道 😂 理解上没关系。

我研究下这个。
