### ISSUE TITLE
Segmentfault 因内含 SVG 图片导致阅读模式中预览效果无法按照原结构预览（个例）

### ISSUE THREAD

**Issue by t427794321** [Kenshin/simpread#5950]
### 描述这个错误

博客文章渲染变形: https://segmentfault.com/a/1190000040086769, 
环境: mbp15 寸;macos10.13;chrome; 简悦版本: 2.2.0.520

### 复现步骤

1. 打开网页
2. 进入阅读模式

### 其他相关说明

1. 打开网页
2. 进入阅读模式

### 操作系统

macos: 10.13.6 (17G14033)

### 浏览器

版本 116.0.5845.110（正式版本） (x86_64)

### 发生问题的网址

https://segmentfault.com/a/1190000040086769

**Comment by Kenshin** [comment]
嗨，这个页面含有的 SVG 在阅读模式下渲染出错造成的，暂时没有太好的解决方案 😂

PS：用 SVG 做这种的确实也少见。
