### ISSUE TITLE
配置文件出错导致无法打开选项页

### ISSUE THREAD

**Issue by WynterAC** [Kenshin/simpread#5952]
### 描述这个错误

已经尝试了所有网上的教程里的方法， 坚果云登陆/用simpread config恢复,包括修复也没办法
这是个[screen recording](https://www.veed.io/view/9a4af0c8-0f03-4c40-a77d-16d91495a31b?panel=share)， see attached file. 

### 复现步骤

https://github.com/Kenshin/simpread/assets/74800744/aaaeaef9-5a2d-4eb3-8acc-54579827af56

### 操作系统

macos Ventura Version 13.4.1 (c)

### 浏览器

 Updating Chrome Version 117.0.5938.88 (Official Build) (arm64)

### 发生问题的网址

https://www.yuque.com/kenshin/simpread/sw4m21

**Comment by WynterAC** [comment]
Resolved by reinstalling sync app

**Comment by Kenshin** [comment]
okay 解决就好 

配置文件损坏的话，可以试试 https://github.com/Kenshin/simpread/discussions/5750 提到的方案~
