### ISSUE TITLE
iOS端 JSBox配置需要会员，无法进行下去

### ISSUE THREAD

**Issue by User20220403** [Kenshin/simpread#5953]
### 请描述你的建议或任何内容

购买高级用户后希望在iOS端也能使用，但教程已不适配新版的JSBox客户端，无法配置。不论怎么点进去都要求我升级为JSBox的高级版会员才能继续使用，请问是否有解决方法？

**Comment by Kenshin** [comment]
嗨，简悦的 JSBox 版仅仅只是 1.x 的部分功能，不建议使用了。

PS：JSBox 的升级策略跟简悦无关，这是两个不同的产品。😄

**Comment by User20220403** [comment]
那请问一下现在iOS想使用简悦还有其他的配置方法吗？

**Comment by Kenshin** [comment]
暂时没有，请等待 Safari 版~

**Comment by User20220403** [comment]
好的，谢谢
