### ISSUE TITLE
关于底部的简悦banner

### ISSUE THREAD

**Issue by why50** [Kenshin/simpread#5954]
### 请描述你的建议或任何内容

感谢你的开发，简悦是我最近入手并已经付费使用的一个插件。

我喜欢极度的简洁，所以如果可以，是否能隐藏这一部分？
![image](https://github.com/Kenshin/simpread/assets/63858324/39627c2a-dc17-4023-9629-73c40546a578)

折中方案：
1，默认隐藏，鼠标移动到其上再显示
2，降低透明度
3，减少所占大小，不要占用那么大的空间，降低侵入感

但最好还是能隐藏它，让简悦更符合沉浸式阅读的理念。

**Comment by Kenshin** [comment]
嗨，你可以使用 自定义样式 解决。

将下面的代码

```
sr-rd-footer {
    display: none;
}
```

加入到下图所示的位置

<img width="470" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5c002868-fc72-43a3-aa20-42d8540dd1af">

保存后重启浏览器。

**Comment by why50** [comment]
感谢！
