### ISSUE TITLE
导入配置文件也无法登录高级账户

### ISSUE THREAD

**Issue by xiaosda** [Kenshin/simpread#5955]
### 描述这个错误

<img width="540" alt="image" src="https://github.com/Kenshin/simpread/assets/127666468/f20eeacb-bb22-46b5-8a0e-df1d26d7eb70">
始终显示导入成功，在授权中，利用坚果云登录也是种显示在登陆中

### 复现步骤

将配置文件导入后始终显示在登陆中，但登录不上

### 操作系统

windows11

### 浏览器

edge浏览器

### 发生问题的网址

登录问题

**Comment by Kenshin** [comment]
选项页 → 共通 → 从本地导入配置文件的方式。

**Comment by Kenshin** [comment]
选项页 → 共通 → 从本地导入配置文件的方式。
