### ISSUE TITLE
保存到obsidian失败

### ISSUE THREAD

**Issue by Kalay1995** [Kenshin/simpread#5957]
### 描述这个错误

同步助手自动保存或者手动保存到obsidian都会失败，最近发现，最后一次成功保存是三周前，8月30日。

### 复现步骤

1. 任何网址比如 https://www.zhihu.com/question/33870165/answer/2799501996
2. 快捷键aa dd 自动保存，会报保存失败的错，手动保存亦是。
![e089131f5edc1377a33acbe9718fd75](https://github.com/Kenshin/simpread/assets/14127267/eed86e82-920b-4d63-b375-fbb9069da5bf)
3. 换了浏览器chrome，换了obsidian库都保存失败。
4. 检查端口如下，不太懂，但是看起来好像没问题
![image](https://github.com/Kenshin/simpread/assets/14127267/df76ce59-5747-4ea5-8410-b506a62e2afe)

### 其他相关说明

[simpread_config.txt](https://github.com/Kenshin/simpread/files/12710192/simpread_config.txt)

最近更新了obsidian，version 1.4.13，不知道是否跟这个有关

obsidian Simpread Sync插件版本 2.1.1

### 操作系统

windows11

### 浏览器

edge 版本 117.0.2045.41 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/question/33870165/answer/2799501996

**Comment by Kenshin** [comment]
嗨，看下是不是这个问题造成的 https://github.com/Kenshin/simpread/discussions/5601

**Comment by Kalay1995** [comment]
> 嗨，看下是不是这个问题造成的 #5601

yes

**Comment by Kenshin** [comment]
解决就好~
