### ISSUE TITLE
保存到notion一直卡在上传图片

### ISSUE THREAD

**Issue by eicky** [Kenshin/simpread#5959]
### 描述这个错误

保存到notion一直卡在上传图片

### 复现步骤

直接动作-保存到notion

### 其他相关说明

直接动作-保存到notion

### 操作系统

macos

### 浏览器

chrome

### 发生问题的网址

任何网址都是

**Comment by Kenshin** [comment]
嗨，细节和原因请看 https://github.com/Kenshin/simpread/issues/5917#issuecomment-1712979914

我关闭这个 Issues 了，当有进一步消息我会在上面这个链接通知（艾特）你~

**Comment by Kenshin** [comment]
嗨

## 导入到 Notion 1.1.0 版发布了 🎉  解决了这个问题，详细说明 #5917
