### ISSUE TITLE
希望能增加界面样式定制化功能

### ISSUE THREAD

**Issue by vicentory** [Kenshin/simpread#596]
1、现有界面4个标签 样式、动作、站点、插件，不常用的功能希望可以在设置选项里自己选择再是否显示插件和站点两项；
2、样式标签里的行间距设置几个希望可以增加自己选择是否显示；
3、动作里的保存到很多第三方链接希望可以增加排序和定制功能，自己删除不需要显示的。
其实就是希望能改善界面样式自由定制的功能，毕竟有的功能也用不到，希望界面能更简洁，毕竟简洁才是这个插件的目的。

**Comment by Kenshin** [comment]
谢谢反馈。

下个版本会加入常用工具栏的功能，即包含了你说的这些全部功能~

**Comment by vicentory** [comment]
多谢，期待下个版本
