### ISSUE TITLE
知识星球

### ISSUE THREAD

**Issue by feixiangdao** [Kenshin/simpread#5960]
### 需要适配的新站

wx.zsxq.com
把知识星球的文章添加到稍后阅读后打开报错，“解析正文失败，可以给我提 [Issues ↗](https://github.com/Kenshin/simpread/issues/new/choose)
如果开启了 内置解析方案 的话，请多刷新几次一般可以解决。”

**Comment by Kenshin** [comment]
嗨，一般来说这种付费查看文档类的页面是不会被适配的，除非有具体「外网」可以访问的 URL 才能适配。
