### ISSUE TITLE
Markdown 增强辅助插件之定制化 Markdown 模板库问题

### ISSUE THREAD

**Issue by EdisonWendy** [Kenshin/simpread#5961]
### 描述这个错误

按照定制化模板库中的 Obsidian模板·标注嵌入模板中的全文代码和标注代码设置好了插件中的稍后读和标注模板，并且也在 Obsidian 中的 SimpRead Sync 插件中复制了对应代码，但是导入到 Obsidian 中的全文不是该模板的样式，只有标注样式是对的，不知道是哪里的设置问题，求解答！
<img width="1280" alt="截屏2023-09-26 02 27 06" src="https://github.com/Kenshin/simpread/assets/120798970/c7eda0ed-9d18-4a8f-b8d8-bc9b9224adf7">
<img width="1280" alt="截屏2023-09-26 02 23 17" src="https://github.com/Kenshin/simpread/assets/120798970/ee62666b-d996-4322-9cbd-60e9d026f939">
<img width="1272" alt="截屏2023-09-26 02 21 18" src="https://github.com/Kenshin/simpread/assets/120798970/e4dbd819-0ffd-469a-8d8e-1d76c7a771ba">
<img width="1238" alt="截屏2023-09-26 02 21 03" src="https://github.com/Kenshin/simpread/assets/120798970/4df3849e-8d83-47c7-85cb-3d201ead9294">

### 复现步骤

1.导入到 Obsidian插件、Markdown 增强辅助插件均按照教程中设置完毕，能正常从网页导出到Obsidian
2.Obsidian 和 Markdown 增强辅助中均粘贴了一样的模板代码
3.导入到 Obsidian 中的效果不对，导入全文没有按照模板格式，仅有标注（@annote）模板样式满足设置。

### 操作系统

macOS12.6.9、Windows 10

### 浏览器

chrome

### 发生问题的网址

https://www.gatesnotes.com/Firmenich-mosquito-repellents

**Comment by Kenshin** [comment]
😂

全文没有定制方案，再说全文怎么「定制」？

**Comment by EdisonWendy** [comment]
> 😂
> 
> 全文没有定制方案，再说全文怎么「定制」？

第一个unread Markdown template框里填入的不就是导入全文的模板吗？
我之前同步 Obsidian 配置库的时候，导入 Obsidian 里面的全文的样式和@annote 一样的都是有题图还有内部链接、外部链接这些，但是现在不知道动到哪里了，导入 ob 的全文的题图这些属性都没有了，不知道怎么设置回来，之前导入的全文是像下面截图中的一样的样式
<img width="1280" alt="截屏2023-09-26 10 47 27" src="https://github.com/Kenshin/simpread/assets/120798970/b1e51217-1acb-4be1-ae0d-8c76ae2af20f">

<img width="1280" alt="截屏2023-09-26 02 27 06" src="https://github.com/Kenshin/simpread/assets/120798970/eefa19a5-edd9-4fcf-aa65-cee3e9e67429">

**Comment by Kenshin** [comment]
> 第一个unread Markdown template框里填入的不就是导入全文的模板吗？

这叫做「稍后读」模板，而不是全文模板，意思是指：稍后读信息的模板定制，与其对应的叫做「标注模板」，也就是对标注的定制。

<img width="619" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6e96ac58-aae6-450e-9281-6bd78c608dee">

无论是文档还是截图中都没有任何「全文模板」的含义...

***

> 我之前同步 Obsidian 配置库的时候，导入 Obsidian 里面的全文的样式和@annote 一样的都是有题图还有内部链接、外部链接这些，但是现在不知道动到哪里了

如果你是说的是下图的话，这叫是 Metadata，可以定制，也就是我提到的「稍后读」模板，也就是会反映到 `1234-xxxx@annote.md` 里面

<img width="512" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/34f65282-b2e3-462c-a013-c06cf077b924">

如果你想定制 `12340-xxxx.md` 的话，也支持 Metadata，但是没有稍后读这么丰富，细节可以看 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590515 定制的位置在：导入到 Obsidian 插件中。
