### ISSUE TITLE
微信公众号文章光标难以准确标注

### ISSUE THREAD

**Issue by julian20220130** [Kenshin/simpread#5963]
### 描述这个错误

大概就是在特定的版面宽度下，无法从首行的首字开始标注，一不小心就会误选全文（如食品中的第一次）。但修改到特定的版面宽度后，由能够正常标注，而不会出现偏移的情况（视频中的第二次）。
此外，自动生成大纲在某些页面也不准确。

### 复现步骤

Uploading iShot_2023-09-26_2

https://github.com/Kenshin/simpread/assets/98684721/8ab99e76-58ec-4e12-a75e-2a063494e870

1.03.14.mp4…

如视频

### 操作系统

MacOS

### 浏览器

edge 最新版

### 发生问题的网址

https://mp.weixin.qq.com/s/Shun4Wzn3UeShks3yEgUFQ?sessionid=1692265018&subscene=0&ascene=0&realreporttime=1692267599917&clicktime=1692267599&enterid=1692267599&forceh5=1

**Comment by Kenshin** [comment]
okay 明天确认下，用没用 https://github.com/Kenshin/simpread/discussions/5851

**Comment by Kenshin** [comment]
另外，其他公众号有这个问题吗？

**Comment by julian20220130** [comment]
辛苦开发大大。其他微信文章也会有这个问题。另外发现，通过将浏览器窗口拖放到一定大小，也能解决标注不准确的现象。
另另 进入阅读模式后无法标注 #5922 这个问题还请开发者帮忙解决。

**Comment by Kenshin** [comment]
> 一不小心就会误选全文（如食品中的第一次）

关于你提到的问题，是已知 Bug 节后就会发布解决方案，很容易解决。

**Comment by LeungZheng** [comment]
放下了的简悦，现在看到作者的积极态度，真的非常感动。让我买了几年的简悦要重新启用了，谢谢。

**Comment by Kenshin** [comment]
@LeungZheng 

我一直都这样 😂  看看 Issues

<img width="300" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/71e453a3-d4d5-4543-aff0-e01cf783101c">

PS：每个 Issues 我都一一回复。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

这个插件可以解决此 Issues 提到的问题~


解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
