### ISSUE TITLE
导入到思源插件的图床疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5965]
插件1.1.2版本，思源版本2.10.6。导入思源，一直显示“正在将图片保存到思源图床...”，显示错误如下
![image](https://github.com/Kenshin/simpread/assets/13896259/4d0614ed-489c-4320-b942-11e9280b40dd)

如果插件设置中取消保存图片到思源，是可以正常将文章剪藏到思源笔记中

_Originally posted by @xulei-shl in https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-7118781_

**Comment by Kenshin** [comment]
@xulei-shl 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

是任意 URL 都有问题还是某个？可以试试 https://sspai.com/post/69972 是否存在这个问题？

另外，思源的版本是刚升级的？还是有一段时间了？

**Comment by xulei-shl** [comment]
- 之前是没有问题的，但当时的思源版本没有留意。
- 今天再用就失败，才查看了思源的版本（2.10.6）。
- https://sspai.com/post/69972，也不可以（思源自动更新到了2.10.7），错误提示相同。

**Comment by Kenshin** [comment]
okay 我一会试试~

**Comment by Kenshin** [comment]
插件这边确实有个 Bug 但跟你遇到的问题无关。

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

使用上面提到的方式重新安装一次，然后在测试下，理论上仍会失败，但应该有某些提示，如果有提示的话，请截图给我。

同时打开 Devtools 把错误信息详细给我看下。

***

PS：不知道为什么我没法使用 `2.10.x` 版本 😂 所以只能这样截图看下。

**Comment by Kenshin** [comment]
你的 IP 设置是这样的吗？

<img width="560" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b4cf1a11-235a-40e2-b63a-00a00335373a">


另外，是在什么环境下使用的？PC（浏览器） 还是其它方案？

**Comment by Kenshin** [comment]
嗨

我让用户帮忙测试了下 `2.10.7`有问题。

**但是 `2.10.5` 是正常的**，你可以先回退到 `2.10.5` 版本。我在跟思源方面沟通下，或者你提交下 Bug 也行。

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">
安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">

- `Fix`  当 **授权码为空** 时，无法使用思源图床的问题 https://github.com/Kenshin/simpread/issues/6311

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
