### ISSUE TITLE
Cloudinary图床验证配置成功了，但是实际在使用中notion还是不能使用Cloudinary图床

### ISSUE THREAD

**Issue by Robs87** [Kenshin/simpread#5968]
### 描述这个错误

Cloudinary图床验证配置成功了，但是实际在使用中notion还是不能使用Cloudinary图床。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/90772605/081baa41-1581-4e06-807e-5a70429a5497)
![image](https://github.com/Kenshin/simpread/assets/90772605/0ee46a69-3da3-4a61-9dfb-bab59d4d99f8)
![image](https://github.com/Kenshin/simpread/assets/90772605/93444a49-6bf9-4f9e-ba74-0ff7463523a5)
![image](https://github.com/Kenshin/simpread/assets/90772605/e92e401c-7cdf-4936-859c-70107148192a)

### 操作系统

windows10

### 浏览器

win10系统的edge

### 发生问题的网址

https://blog.csdn.net/qq_40020447/article/details/107179507

**Comment by Kenshin** [comment]
不会发生这个问题的 😂

你是如何导入的？或者试试通过下面的方式导入看看。

![image](https://github.com/Kenshin/simpread/assets/81074/59123148-9789-4885-844a-ea83d995cd8f)

**Comment by Kenshin** [comment]
补充下：因为你截图没有涉及到这块，所以我不清楚你是如何打开这个图片的，你需要在 Notion 中查看这个图片的链接。

**Comment by Robs87** [comment]
> 补充下：因为你截图没有涉及到这块，所以我不清楚你是如何打开这个图片的，你需要在 Notion 中查看这个图片的链接。

![IMG_2426](https://github.com/Kenshin/simpread/assets/90772605/8323d6f1-9538-4005-a856-a084fc1bda58)
在notion中打开刚才导入的文章，然后选一个图片那6个点

**Comment by Kenshin** [comment]
okay 你查看的方式没问题。

仔细看还有个问题没有回复我 

<img width="425" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8ae96d3a-19cf-401a-a0f3-8ec386606fe6">

你可以用 https://github.com/Kenshin/simpread/issues/5968#issuecomment-1737111575 提到的方式测试下导入到 Notoin 是否有问题。

***

再说下，正常的流程，可以看下 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4500614 的说明，包括：直接导入 & 加入稍后读时自动导入

**Comment by Kenshin** [comment]
okay 你查看的方式没问题。

仔细看还有个问题没有回复我 

<img width="425" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8ae96d3a-19cf-401a-a0f3-8ec386606fe6">

你可以用 https://github.com/Kenshin/simpread/issues/5968#issuecomment-1737111575 提到的方式测试下导入到 Notoin 是否有问题。

***

再说下，正常的流程，可以看下 https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-4500614 的说明，包括：直接导入 & 加入稍后读时自动导入

**Comment by Robs87** [comment]
> 我明天再测试下，可能是有点问题

好的，我晚上各种方法重复弄了很多次，还是不行，我正在郁闷看到你这个回复啦。明天等你消息啊，老大。

**Comment by Kenshin** [comment]
导入到 Notion 1.1.1 发布了 😂 解决了

> 图片含有特殊字符导致 Cloudinary 上传成功了但没有正确替换的错误。

我测试了

- [x] 知乎
- [x] 微信公众号
- [x] b站专栏
- [x] 百度贴吧

均可以正常显示

***

## 📈 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Robs87** [comment]
> 导入到 Notion 1.1.1 发布了 😂 解决了
> 
> > 图片含有特殊字符导致 Cloudinary 上传成功了但没有正确替换的错误。
> 
> 我测试了
> 
> * [x]  知乎
> * [x]  微信公众号
> * [x]  b站专栏
> * [x]  百度贴吧
> 
> 均可以正常显示
> 
> ## 📈 安装与升级
> * 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。
> * 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

老哥，太腻害了！我RSS和竹白都订阅了你的文章，昨天看到这个notion1.1.0特别激动，第一时间去测试了。今天就解决了！点个赞啊！

**Comment by Kenshin** [comment]
小事情~ 测试 OK 的话告诉我下 😄

用的好，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评  😏

**Comment by Robs87** [comment]
> 小事情~ 测试 OK 的话告诉我下 😄
> 
> 用的好，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😏

测试ok了，一切正常，早就好评了，我用了一年多了，简悦是我现在工作流中很重要的一个环节！

**Comment by Kenshin** [comment]
哈，谢好评 😄

PS：竟然是老用户 👍

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
