### ISSUE TITLE
使用简悦导出的为知笔记页面的图片无法离线存储

### ISSUE THREAD

**Issue by vez001** [Kenshin/simpread#5969]
### 请描述你的建议或任何内容

大家使用各种笔记或知识管理软件，相信都是为了更好的储存资料便于以后使用。这个使用需求可能是你剪藏文章的那一刻，也可能是很长一段时间之后（几天、几月或几年？）。假如你剪藏并导出了一篇文章之后，很长一段时间之后你才有使使用它的需求，可当你打开之前收藏的页面准备阅读时，却发现里面的图片一片空白，不知大家会不会很抓狂。

我本人对于收集的各种资料的脱机离线本地储藏，是有相当强的需求。毕竟网页上所携带的一些图片或者信息，随时都有可能根据网络提供商的心情被404。（也可能是微信公众号文章被删除）

使用简悦之后，发现了一个奇怪的现象，无论是使用浏览器自带的网页剪辑器，还是使用网页剪藏保存。当网页上传到服务器后，得到的都是一个完整的离线html网页。非常方便脱机使用。（见下图）
![Snipaste_2023-09-27_22-51-55](https://github.com/Kenshin/simpread/assets/142110682/a59311d7-1dc4-449b-b52c-55220c6b4b59)
![Snipaste_2023-09-27_23-25-05](https://github.com/Kenshin/simpread/assets/142110682/32575899-a58e-4ed1-baaf-176c739751e1)

可是当网页进入到简约的阅读模式之后，再使用内置的网页导出至为知笔记笔记服务器后，得到的却是一个含有 URL的还有网页。两个文件的体积大小尤为悬殊。（见下图）
![Snipaste_2023-09-27_22-54-21](https://github.com/Kenshin/simpread/assets/142110682/7856ddde-8458-46d4-a0d9-982084b64769)
![Snipaste_2023-09-27_23-25-27](https://github.com/Kenshin/simpread/assets/142110682/a23d7a97-a015-4a8e-8926-0ebf0f5fe2f4)

假如使用简约的生成临时页面功能收藏微信公众号文章的时候。网页内嵌的图片全部都被防盗链了。也不知道问题出在简悦的服务器端，还是为知笔记的服务器端？（见下图）
![Snipaste_2023-09-27_23-00-00](https://github.com/Kenshin/simpread/assets/142110682/79b290dc-2831-4819-aad6-97d28af150ef)
![Snipaste_2023-09-27_23-26-39](https://github.com/Kenshin/simpread/assets/142110682/7b535a26-f35a-4f8a-bf1a-fe740fc2b319)

这就给我带来很大的困扰，假如我想长久的保存一篇文章或者网页，我就只能使用使用浏览器的剪藏插件，可这样又会带来很多网页上的冗余内容或图片，影响我后期的查找信息和深入阅读。假如我希望保存一个干爽整洁的文章，使用简约生成阅读模式界面并收藏至为知笔记后，得到的却是一个带有文字和图片URL的网页，这样又背离了我希望长久离线保存一些网页的初衷。
希望作者大大考虑相关需求，提供一个合理的解决方案。

**Comment by Kenshin** [comment]
> 可是当网页进入到简约的阅读模式之后，再使用内置的网页导出至为知笔记笔记服务器后

因为导入到为知笔记的图片并不是你说的「离线图片」，为知笔记应该没有开放它自己的图床，如果你确保离线图片的话：

1. 简悦的 离线 HTML 方案

    <img width="165" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d342966e-e3fa-4147-8b60-6cae142f6545">

2. 简悦的 [assets + md 方案](https://github.com/Kenshin/simpread/discussions/4041)

3. 其它 [图片本地划方案](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920473)

4. [图床方案](https://github.com/Kenshin/simpread/discussions/4306)

基于你的诉求，最简单的方案：

1. 图床方案
2. 不使用 **为知笔记** 而 **直接使用离线 HTML**

**Comment by vez001** [comment]
感谢开发者百忙之中的回复，但是对您的回复还是有些不理解
1如果是使用为知自己的图床的话
查看从服务器同步过来的笔记的html代码时，为什么图片显示的是本地路径，如下图
![8102c54e-c446-445c-8e2d-b9b7255e96ea](https://github.com/Kenshin/simpread/assets/142110682/faf8bcc3-e5e1-4571-8c3f-b8f1b07da425)
这可以不可以理解为为知服务器端的图片也是以离线图片，而不是URL的形式存在
而同步同步简悦剪藏的图片时，却是以URL形式存在
2，在使用生成临时页面功能收藏微信公众号文章的时候，为什么图片全部被防盗链了，而为知或者其他笔记软件时不会，这有没有能改进优化的地方呢
谢谢

**Comment by Kenshin** [comment]
> ![8102c54e-c446-445c-8e2d-b9b7255e96ea](https://github.com/Kenshin/simpread/assets/142110682/faf8bcc3-e5e1-4571-8c3f-b8f1b07da425)

这个链接不是「本地图片」而是在线图片

> 在使用生成临时页面功能收藏微信公众号文章的时候

这是指什么？最好能截图说明下。

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论
