### ISSUE TITLE
请问如何去除页面内的自带超链接

### ISSUE THREAD

**Issue by lebonnuit** [Kenshin/simpread#597]
如题，当保存成md后倒入notion查看时发现，有非常多的页面内超链接以及词条编辑时间这样的信息，这里的**阅读场景**是**百科类网页**，如wikipedia、百度百科、智库百科等
故想问一下是否有办法自己动手，**主动清除所有页内自带超链接，只保留文字和图片本身**？

**Comment by Kenshin** [comment]
建议给我个链接看看。  😄

**Comment by H-Tung** [comment]
> 建议给我个链接看看。 😄

我看的不是百科,会计准则进入阅读模式后会给我加一堆链接,导出时也会带着,很烦
https://www.casc.org.cn/2018/0815/202815.shtml

**Comment by H-Tung** [comment]
> 建议给我个链接看看。 😄

[企业会计准则第11号——股份支付（2006）_财政部会计准则委员会](https://www.casc.org.cn/2018/0815/202803.shtml)
像是这种页面，我目前是导出markdown然后做手动正则处理的，一开始以为 [清理链接 · Discussion #2734 · Kenshin/simpread](https://github.com/Kenshin/simpread/discussions/2734) 这个插件是用来清理页面里的链接的呢……

**Comment by Kenshin** [comment]
@H-Tung 

你竟然翻到了这么老的 Issues  😂 

不过，我没理解你的需求... 你想要实现什么？页面内编辑吗？还是？

**Comment by H-Tung** [comment]
> 你竟然翻到了这么老的 Issues 😂

我记得去年上半年就找到这个issue想反映来着，后来忘了……

> 不过，我没理解你的需求... 你想要实现什么？页面内编辑吗？还是？

**方便保存页面**，这种规章页面或者百科页面我需要保存到 .md 或者 supermemo。在 _页面有大量超链接的情况下，直接保存会影响阅读_

- **目前的样式**
    - 导出 md  `[请问如何去除页面内的自带超链接 · Issue #597 · Kenshin/simpread](https://github.com/Kenshin/simpread/issues/597)` 
    - html [请问如何去除页面内的自带超链接 · Issue #597 · Kenshin/simpread](https://github.com/Kenshin/simpread/issues/597)
- **期望的样式**
`请问如何去除页面内的自带超链接 · Issue #597 · Kenshin/simpread`

去除超链接用正则乃至写个脚本当然不麻烦，live editor 里用删除格式也可以去除超链接，但是 **live editor 里用 Ctrl+A 选中全文不会弹出选单，也就没法快速去除所有链接** ，这是我处理这个问题麻烦的地方

**Comment by Kenshin** [comment]
@H-Tung 

emmm 你就是想要一个：

> 删除正文中全部的超链接，对吗？

如果是的话，我可以考虑出个插件。

**Comment by H-Tung** [comment]
确实就是这个issue最开始的要求，我表达的不太精炼，废话多了点 🤣

**Comment by Kenshin** [comment]
> 确实就是这个issue最开始的要求，我表达的不太精炼，废话多了点 🤣 辛苦了~

哈哈，没问题。我已经记录了，搞定后会通知你。

***

方便的话，请帮忙在 [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 

五星 + 评分，走一个，这是对简悦最好的帮助。 🙏  💪  😏

**Comment by H-Tung** [comment]
看到相应插件更新了，可以关 issue 了 :tada:

**Comment by Kenshin** [comment]
@H-Tung 

哈，你是怎么发现的？我还没有「发布」它？（当然指的不是代码部分）😂

**Comment by H-Tung** [comment]
> @H-Tung
> 
> 哈，你是怎么发现的？我还没有「发布」它？（当然指的不是代码部分）😂

QQ 频道7月6号你就发帖了啊？我记得还是全员通知公告栏，不然按我不爱看消息还不一定能发现……

**Comment by Kenshin** [comment]
😂 

我忘记了... 其它渠道没有发，所以我这边的标记是 **未发布** ...  🌚 

等真正发布后我再关闭这个 issues~

**Comment by Kenshin** [comment]
嗨，[清理链接](https://github.com/Kenshin/simpread/discussions/2734) 升级到 1.0.2 版，增加了 [清理正文全部超链接](https://github.com/Kenshin/simpread/discussions/2734#discussioncomment-6371147) 功能。

![image](https://github.com/Kenshin/simpread/assets/81074/226246a5-38e8-4920-b222-49f0cf3dffe7)

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/1VIRZ7VGc3) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/2733

***

我关闭这个 Issues 有任何问题仍可以在这里跟我讨论~

**Comment by Kenshin** [comment]
![image](https://github.com/Kenshin/simpread/assets/81074/3fd24bc9-4c53-43a8-99b4-1bff7d39d87e)

嗨，[维基百科辅助增强](https://github.com/Kenshin/simpread/discussions/5832) 发布了，解决了此类问题。

<img width="850" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8415bb4a-81d3-41b3-a5e6-70ef34c81e28">

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 仅保留正文，使其更转换为 Markdown 结构，去掉了一些其它元素

- 删除表格（在个别维基百科的页面中，表格是非常复杂的结构，所以生成的 Markdown 效果非常差，因此可以删除这些表格）

- 让一些在侧边的图片居中显示

- 可正常显示公式

- 删除页脚

- 清理文中链接（更利于导入到 Obsidian 不会生成多余的双向链接）

- 删除正文的全部链接

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5833

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~
