### ISSUE TITLE
导入Notion时卡“请稍等”

### ISSUE THREAD

**Issue by yzhAndy** [Kenshin/simpread#5970]
### 描述这个错误

对知乎网页，进行保存到Notion，之前一直正常并可以触发导入增强，
今天突然卡在这里，“请稍等”，排除网络和梯子失效

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/67348844/d765bd6c-1b04-4cd6-8469-48f2eb298027)

### 操作系统

windows11

### 浏览器

Chrome 版本 117.0.5938.132（正式版本） （64 位）

### 发生问题的网址

https://www.zhihu.com/question/60878189/answer/2997130458?utm_campaign=&utm_medium=social&utm_oi=929478938234662912&utm_psn=1687385102127169536&utm_source=zhihu

**Comment by Kenshin** [comment]
请升级到 1.1.1 造成的原因以及详细说明 https://github.com/Kenshin/simpread/issues/5917#issuecomment-1736627163
