### ISSUE TITLE
当少量标注（尤其是标注单词）刷新页面后会导致定位错误（个例）

### ISSUE THREAD

**Issue by slk000** [Kenshin/simpread#5971]
### 描述这个错误

标注的范围内如果有行内代码，重新进入阅读模式后，该段落里其他位置的相同内容也会被标注上

### 复现步骤

标注这两个部分：
![2023-09-28_13-16](https://github.com/Kenshin/simpread/assets/9215216/24271827-f884-4aa2-aa08-7cf9890c22a0)
再次进入之后：
![2023-09-28_13-17](https://github.com/Kenshin/simpread/assets/9215216/bda16941-bc4b-409f-ac2e-87ccdbeb3ce3)

### 操作系统

linux

### 浏览器

Edge114.0.1823.79

### 发生问题的网址

https://rentry.co/gmrxe

**Comment by Kenshin** [comment]
okay 

### 问题原因

> 当标注少量内容时，会因为词重的问题造成的，并且仅限一些结构特殊的页面。

### 解决方案

1. 如果你使用了同步助手，并且设置了本地快照（[知识库](https://www.yuque.com/kenshin/simpread/wkswh7)）方案的话，算是解决了，但还没有发布。（发布后我会在这里通知你）

2. 如果没有使用同步助手的话，暂时没法解决。

**Comment by Kenshin** [comment]
嗨，久等了~

[稍后读辅助增强](https://github.com/Kenshin/simpread/issues/5944) 经过漫长的测试，现在已经发布了  🎉  😄

解决了什么
---

使用了 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 修改了原页面的内容或 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将当前页面的图片转换为图床后会导致：**与原页面内容不同**，当再次进入这个页面时，如果仍读取原页面就【不合理】了。

此插件可以在原页面的基础上显示来自本地快照的内容，进而解决了这个问题，使用此功能后会让当前阅读模式的内容来自你的本地快照，而非【原页面】。

一般来说**配置了简悦的本地快照方案用户，建议使用此功能**。

功能说明
---

- 进入阅读模式后，将本地快照的内容还原到阅读模式

- 进入阅读模式后，当稍后读没有本地快照时自动生成本地快照

- 稍后读侧栏支持双击删除方式

- 黑名单

- [一键设置本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-7042321)

- [临时禁用本地快照](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9943469)

- [导入和导出](https://github.com/Kenshin/simpread/discussions/5943#discussioncomment-9972887)

详细说明
---

https://github.com/Kenshin/simpread/discussions/5943

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/dtIMMLktg9) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题可以在这里随时讨论~
