### ISSUE TITLE
关于Notion剪藏使用Cloudinary的问题

### ISSUE THREAD

**Issue by MegaDom** [Kenshin/simpread#5973]
### 描述这个错误

- [x] [知乎](https://www.zhihu.com/question/587939523)
- [x] [b站专栏](https://www.bilibili.com/read/cv26084317/?from=category_0)
- [x] [微信公众号](https://mp.weixin.qq.com/s/Im6VENsDJikvtFpZxuM87w)
- [x] [少数派](https://sspai.com/post/83125)
- [x] [百度贴吧](https://tieba.baidu.com/p/6596861163?frwh=index)
- [ ] [机核网](https://www.gcores.com/articles/171494) 只有一张图片使用了图床，其他的是以markdown形式插入（不过未正确显示为图片，仅显示机核原图片网址的markdown图片字符串）
![image](https://github.com/Kenshin/simpread/assets/107259784/82841422-ec81-4986-ba4d-f9fa888849b2)
- [ ] [微博](https://weibo.com/5652298665/KAfWQvbG0#comment)
- [ ] [爱范儿](https://www.ifanr.com/video/1563641)
- [ ] [chiphell](https://www.chiphell.com/article-30390-1.html)
- [x] [電腦玩物](https://www.playpcesor.com/2023/09/evernote-ai-ai-ai.html)
- [x] [workspaces](https://www.workspaces.xyz/p/288-mandy-thao)
- [x] [gamespot](https://www.gamespot.com/articles/meta-quest-3-preorder-guide-release-date-price/1100-6518013/)

总结，外网简单找的几个都能正常使用图床，中国大陆网站的图片地址似乎没有规则比较乱，难道要挨个适配？（其实目前除了微博，其他的中国大陆的网站也不太需要剪藏，我只是随便测试了一些，笑~）

### 复现步骤

正常进入阅读页面，使用notino+cloudinary图床剪藏

### 操作系统

Win11

### 浏览器

Chrome 版本 117.0.5938.132（正式版本） （64 位）

### 发生问题的网址

https://weibo.com/5652298665/KAfWQvbG0#comment

**Comment by Kenshin** [comment]
谢谢测试。👍

> https://www.ifanr.com/video/1563641

这个页面没法进入阅读模式，也没法导入... 此功能导入的图片，而非视频。其它正常的爱范儿页面我测试过，是没问题的。

> https://weibo.com/5652298665/KAfWQvbG0#comment

确实有问题，估计是微博本身的限制，这个没法「解决」。

> https://www.chiphell.com/article-30390-1.html

图片可以正常导入到简悦，同时 Markdown 也正常

```
序言

        在 RTX 4000 系移动端显卡发布之初, 七彩虹已经为我们送测过 2023 款的将星 X15 AT 系列游戏笔记本. 最近则增加了一款配置, CPU 为搭载 Intel i7-13650HX 的版本, 今天来到的就是这款新增的配置机型.

![](https://res.cloudinary.com/dvyu4sgrr/image/upload/v1695885588/simpread/0a019b121a8908ec227784a6c47d7c20f38739ef1100294ed77a3ce7264e7618.png)

***

▎本文由 [简悦 SimpRead](https://simpread.pro) 转码。
```

但导入到 Notion 确实没有图片显示，猜测是 Notion 自身的问题。

***

#### 简单的说下这个功能的「原理」：

找到正文的图片地址 → 传给简悦的服务器 → 简悦的服务器调用 Cloudinary API → 返回保存后的图片地址 → 替换原来的图片地址为 Cloudinary 图床地址。

一般出问题的地方：

1. 图片压根无法上传 e.g. 微博

2. 图片成功导入到 Cloudinary 但替换失败 e.g. 1.1.0 版本你遇到的问题。

***

所以，**问题1** 是没法解决的，但 **问题2** 可以解决，所以在遇到这个情况，看下你的 Cloudinary 里面是否有图片了，如果有的话，说明就是 **问题2**，这是你把这个网页的链接（URL）提交到这个 Issues。

一般来说，当**问题1** 发生时会有上传出错图片的数量提示。

***

关联 https://github.com/Kenshin/simpread/issues/5917

***

我先关闭这个 issues 了，有新的无法转换的问题，直接提交到这里。

**Comment by MegaDom** [comment]
感谢这么快修复bug！目前已够用了！

**Comment by Kenshin** [comment]
小事情，有任何问题随时提 😄 中秋快乐。

***

用的好，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😏

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 升级到 1.2.0 

### 重点更新：导入到 Cloudinary 时不经过简悦自己的图片服务器

旧版 1.2.0（以上）会通过简悦的自己的服务器，优点是不需要耗费用户的设备性能；缺点是当为内网图片时无法使用；

新版 1.2.0（含），不经过简悦自己的图片服务器，解决了内网图片或某些有防盗链的图片无法上传的问题。

如：

1. 近期少数派更新了图片规则，导致无法使用旧方案上传，但版方案可以正常将少数派的图片上传到 Cloudinary

    <img width="1023" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8273730d-2cb5-45e9-9170-7fe32f800f03">

2. 内网图片无法使用此功能的问题

### 其它更新

`Fix` 导入图片如果是 `http:` 形式在 Notion 无法显示的问题

***

有任何问题请在汇总页面讨论 https://github.com/Kenshin/simpread/issues/5917

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
