### ISSUE TITLE
阅读页面不能适配edge浏览器页面

### ISSUE THREAD

**Issue by rensheng01** [Kenshin/simpread#5974]
### 请描述你的建议或任何内容

使用本插件后不能适配edge浏览器的页面，弹出来的弹窗上滑或者下滑到底部点保存很困难，每次都需要将edge浏览器全屏才能看到上边的×或者下边的保存和关闭。

**Comment by Kenshin** [comment]
我没太理解你的问题… 建议告诉具体 URL 或截图
