### ISSUE TITLE
Obsidian更新到1.4.14，SimpRead Sync无法自动同步新的文档或者自动更新新的标注

### ISSUE THREAD

**Issue by fangxiangzhong** [Kenshin/simpread#5975]
### 描述这个错误

我在一台新电脑上按照教程部署了Obsidian和SimpRead，但是我发现在打开网页右击“阅读模式”并添加标注时，尽管右上角提示“保存成功”，同时本地SimpRead\output文件夹下确实存在新的html文件，但是Obsidian中并没有更新。

起初我认为是我配置错误，于是就在之前使用Obsidian电脑上尝试，发现Obsidian自动更新到1.4.14之后也出现Obsidian无法同步的情况

### 复现步骤

windows系统下，obsidian版本为1.4.14，obsidian install版本为1.4.13，按照官方教程配置

### 操作系统

Windows11 专业版 22H2

### 浏览器

Edge Version 117.0.2045.43 (Official build) (64-bit)

### 发生问题的网址

https://36kr.com/p/2450840334636935 （任意网址都会出问题）

**Comment by Kenshin** [comment]
是不是 https://github.com/Kenshin/simpread/discussions/5601 造成的。

**Comment by Kenshin** [comment]
我测试了下 你提到的版本是没问题的。

<img width="246" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/084b60ca-3a89-4361-93b4-a67ee782cd03">

包括：在浏览器中标注 & 在 Obsidian 中标注。

**Comment by fangxiangzhong** [comment]
啊好的好的，那应该是我自己的问题，我再排查一下，打扰您了，谢谢您！

祝

身体健康，工作顺利！

**Comment by Kenshin** [comment]
小事情，看下我给你的链接提到的解决方案。

**Comment by fangxiangzhong** [comment]
好的好的，谢谢哥。我在之前已经把127.0.0.1改成localhost了，但是还是存在问题。

此外，我尝试了1）更换文件夹名称和库名称，保证了所有都是英文； 2）重装Edge浏览器的简悦插件并按照教程一步步重新操作；3）在Chrome中安装此插件并尝试；4）切换端口（默认为7027），同时确保了所使用的端口没有被其他程序占用；5）重新通过插件管理器安装了“导出到obsidian”插件；6）安装旧版本Obsidian。

但是问题依然存在。即当我打开网页、右键进入阅读模式，开始做批注时右上角弹出显示“保存成功”，但Obsidian对应路径下依然没有。

会不会是windows的问题啊，，，，（筋疲力尽了，，，）

再次感谢哥

**Comment by Kenshin** [comment]
> 右键进入阅读模式，开始做批注时右上角弹出显示“保存成功”

跟 Win 肯定没有关系，这个功能很多用户，Win 的用户量应该比 Mac 多 😂

仅文字描述没有意义，建议：

1. 把全部相关设置都截图给我。
2. 看下 Markdown 模板辅助增强，能否在包含标注的页面使用这个插件的测试，看看右侧有没有任何内容？

**Comment by alex-fang123** [comment]
谢谢哥，截图如下，然后2的话，我测试过是有内容的
<img width="415" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/fe9118f8-200a-406e-a812-cda6e359f8f4">
<img width="523" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/dd86c4bb-f068-4ea5-a730-b4f1c7e8a152">
<img width="528" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/5855820d-7da1-4510-b49e-841f4be2a612">
<img width="212" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/669ca775-afb7-4597-9423-1bff4f62ecbd">
<img width="590" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/3adb23a6-4904-4357-893b-cb51726e2879">
<img width="605" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/883c4898-b6cf-4198-8f4f-b506f84a0120">
<img width="339" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/53fa09d4-c1ae-4d20-aebc-c5a66b6c39e3">
<img width="675" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/fe1f3f92-026e-4e0c-8fb6-e0bb325d0dee">
<img width="699" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/a469ab0c-6346-4c11-b88e-a9785c14c73d">
麻烦哥了，谢谢您这么有耐心！

**Comment by Kenshin** [comment]
你给出的截图都是正确的，但下面两个关键功能的截图没有给出。

<img width="479" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cfa20234-84b9-4211-8022-0980403dc761">

对比下教程，看看它们是否安装了或者里面的设置都是什么？

**Comment by alex-fang123** [comment]
您好，以下是我关于这两个插件的设置界面。Markdown辅助增强插件选项的内容是从Simpread Sync中直接复制粘贴过来的，麻烦您啦
<img width="272" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/62d0131c-70fb-42ae-bf99-0516382d1e4f">
<img width="371" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/704645cf-b406-4510-8ab8-2565b39bcea0">
<img width="1659" alt="image" src="https://github.com/Kenshin/simpread/assets/129178732/29695996-ec34-4646-98b2-c4e349a372f9">

**Comment by Kenshin** [comment]
1. 在有稍后读的页面，随便加入一些标注，然后手动导出（下图），**如果能在 Obsidian 看到说明你的配置没问题**，问题处在第二条。

<img width="481" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cb67ebbe-4a80-41d4-8e46-2fce7be01b85">

2. 自动化辅助增强有问题，你可以看下 https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-2590606 的教程

**Comment by alex-fang123** [comment]
太感谢哥了！再次为您的耐心和业务水平致谢！

**Comment by Kenshin** [comment]
哈哈，搞定就好。👍

对简悦最大的帮助是帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评。 😏 

PS：首选 Chrome 😂

**Comment by alex-fang123** [comment]
均已五星好评！再次感谢!

**Comment by Kenshin** [comment]
👍  🎉
