### ISSUE TITLE
希望黑夜模式下阅读模式的目录的字体颜色可以亮一些

### ISSUE THREAD

**Issue by shiquda** [Kenshin/simpread#5976]
### 请描述你的建议或任何内容

![image](https://github.com/Kenshin/simpread/assets/104683621/f2912178-2fed-4ccf-bca2-12ab1bde25be)
~~如图左侧，黑夜模式下目录看的不是很清楚
然而比较奇怪的是，我在阅读模式的时候来回切换黑夜和白天模式后，字体颜色又变成白色了，不知道是不是bug~~
好像解决了，把这里来回调一下好像就行了
![image](https://github.com/Kenshin/simpread/assets/104683621/b262d849-aa06-4315-984e-9405df056ce3)

**Comment by Kenshin** [comment]
嗨，恭喜自救成功，应该是这个问题造成的 https://github.com/Kenshin/simpread/discussions/2992

PS：中秋节都不好好休息？
