### ISSUE TITLE
某些网站无法使用 Cloudinary 导入

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#5978]
您好，简悦对于科研期刊网站的适配确实好太多了，但是在保存到notion中时（使用导入到notion插件），虽然使用了新的图床方案，但网站的图片仍然无法正确保存在notion中，其他的公众号、网站的图片都能正常显示。请问有没有办法解决

![img_001](https://res.cloudinary.com/dhicwlssm/image/upload/v1696081108/test/agx2txas4jb7bcadvt5k.png)

![img_01](https://res.cloudinary.com/dhicwlssm/image/upload/v1696081107/test/zeer9qgbaq675llihlut.png)
)

![img_02](https://res.cloudinary.com/dhicwlssm/image/upload/v1696081108/test/amstfukp8zp7hyz8ymal.png)

_Originally posted by @threeyears121 in https://github.com/Kenshin/simpread/discussions/2103#discussioncomment-7151699_

**Comment by Kenshin** [comment]
@threeyears121

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

#### 简单的说下这个功能的「原理」：

找到正文的图片地址 → 传给简悦的服务器 → 简悦的服务器调用 Cloudinary API → 返回保存后的图片地址 → 替换原来的图片地址为 Cloudinary 图床地址。

一般出问题的地方：

1. 图片压根无法上传 e.g. 微博

2. 图片成功导入到 Cloudinary 但替换失败

3. 图片上传了也正常替换了，但 Notion 并不支持。

***

所以**具体需要你提供出问题的 URL**

一般来说，当 **问题1** 发生时会有上传出错图片的数量提示。

**Comment by threeyears121** [comment]
> @threeyears121
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> #### 简单的说下这个功能的「原理」：
> 找到正文的图片地址 → 传给简悦的服务器 → 简悦的服务器调用 Cloudinary API → 返回保存后的图片地址 → 替换原来的图片地址为 Cloudinary 图床地址。
> 
> 一般出问题的地方：
> 
> 1. 图片压根无法上传 e.g. 微博
> 2. 图片成功导入到 Cloudinary 但替换失败
> 3. 图片上传了也正常替换了，但 Notion 并不支持。
> 
> 所以**具体需要你提供出问题的 URL**
> 
> 一般来说，当 **问题1** 发生时会有上传出错图片的数量提示。
> 
> 关联 #5917

您好，通过阅读您的回复，我想有没有办法让加载的图片直接上传到图床啊，像一些科研期刊的网站，从外网是无法完整看到论文内容的，这样就能保证在本地浏览器看到的内容即是导入到notion的内容了

**Comment by Kenshin** [comment]
> 我想有没有办法让加载的图片直接上传到图床啊

没有...

Notion 并不是一个完美的剪藏工具，它对 Markdown 的支持度较低，稍微结构复杂（或有问题）的语法规则都无法正确识，这是由众多简悦用户提交 Issues 后得出的结论。

所以你的问题仍是我提到的情况，只能通过技术手段判断具体原因。

你可以将这个页面导出为 HTML 或者 Markdown 然后传上来，我看看具体是什么问题。

或者你也可以测试下：导出 Markdown 后手动上传到 Notion 看下是否可以显示图片。

你也可以登录 Cloudinary 看下图片是否导入成功了。

**Comment by threeyears121** [comment]
经过尝试，图片无法成功上传图床，可以保存为markdown格式在本地正常显示,下面是markdown文件的链接，麻烦您看看，
[simpread-Dual-Signal Amplification Strategy for Ultrasensitive Photoelectrochemical Immunosensing of α-Fetoprotein  Analytical Chemistry.md](https://github.com/Kenshin/simpread/files/12782110/simpread-Dual-Signal.Amplification.Strategy.for.Ultrasensitive.Photoelectrochemical.Immunosensing.of.-Fetoprotein.Analytical.Chemistry.md)

**Comment by Kenshin** [comment]
你给我的 `.md` 没有含有任何有效图片链接，让我怎么判断 😂

**Comment by threeyears121** [comment]
> 你给我的 `.md` 没有含有任何有效图片链接，让我怎么判断 😂

是吗，我导出的是离线md，我再导出一个
[simpread-A carbon nanotube_quantum dot based photoelectrochemical biosensing platform for the direct detection of microRNAs - Chemical Communications (RSC Publishing)__    一种基于碳纳米管 _ 量子点的光电化学生物传感平台.md](https://github.com/Kenshin/simpread/files/12788853/simpread-A.carbon.nanotube_quantum.dot.based.photoelectrochemical.biosensing.platform.for.the.direct.detection.of.microRNAs.-.Chemical.Communications.RSC.Publishing.__._.md)

**Comment by Kenshin** [comment]
1. 我之前说了，是 HTML 或 Markdown 而不是离线 Markdown 😂

2. 我用你给我的 Markdown 测试了下，图片可以正常上传到 Cloudinary

所以

1. 你可以使用插件里面提供的测试方式测试图片是否上传成功了（用来判断你的设置）或者使用 https://sspai.com/post/69972 测试。

2. 既然图片上传成功了，我需要给再给**我 HTML** 这样我才能还原你的使用环境。

     <img width="379" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/17b3a153-a665-4144-a647-bf1d2d454265">

**Comment by threeyears121** [comment]
> 1. 我之前说了，是 HTML 或 Markdown 而不是离线 Markdown 😂
> 2. 我用你给我的 Markdown 测试了下，图片可以正常上传到 Cloudinary
> 
> 所以
> 
> 1. 你可以使用插件里面提供的测试方式测试图片是否上传成功了（用来判断你的设置）或者使用 https://sspai.com/post/69972 测试。
> 2. 既然图片上传成功了，我需要给再给**我 HTML** 这样我才能还原你的使用环境。
>      <img alt="image" width="379" src="https://user-images.githubusercontent.com/81074/272157240-17b3a153-a665-4144-a647-bf1d2d454265.png">

我导出为html文件了
[simpread-A carbon nanotube_quantum dot based photoelectrochemical biosensing platform for the direct detection of microRNAs - Chemical Communications (RSC Publishing)__    一种基于碳纳米管 _ 量子点的光电化学生物传感 (1).html.zip](https://github.com/Kenshin/simpread/files/12788974/simpread-A.carbon.nanotube_quantum.dot.based.photoelectrochemical.biosensing.platform.for.the.direct.detection.of.microRNAs.-.Chemical.Communications.RSC.Publishing.__._.1.html.zip)

**Comment by Kenshin** [comment]
我测试了是没有问题的

<img width="1348" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/da80fcf0-42bd-4e23-8523-69644bb56905">

1. Cloudinary 可以正常导入图片
2. 也可以正常在 Notion 中查看。

但

1. 我并不是在 https://pubs.rsc.org/en/content/articlelanding/2014/CC/C4CC06214K#fn1 上查看的，所以不清楚原网站是否有限制。

2. 我让你测试 Cloudinary 是否正常，你没有反馈给我。

**Comment by threeyears121** [comment]
> 我测试了是没有问题的
> 
> <img alt="image" width="1348" src="https://user-images.githubusercontent.com/81074/272196863-da80fcf0-42bd-4e23-8523-69644bb56905.png">
> 1. Cloudinary 可以正常导入图片
> 2. 也可以正常在 Notion 中查看。
> 
> 但
> 
> 1. 我并不是在 https://pubs.rsc.org/en/content/articlelanding/2014/CC/C4CC06214K#fn1 上查看的，所以不清楚原网站是否有限制。
> 2. 我让你测试 Cloudinary 是否正常，你没有反馈给我。

我试了一下，显示上传失败，不知道是不是跟这个网站有关系，阅读模式下图片都能正确显示（https://pubs.acs.org/doi/full/10.1021/ac302853y#）
![WX20231003-205721@2x](https://github.com/Kenshin/simpread/assets/33708762/ba70ac76-02b8-4852-a123-89b545930bde)
[simpread-Dual-Signal Amplification Strategy for Ultrasensitive Photoelectrochemical Immunosensing of α-Fetoprotein _ Analytical Chemistry.html.zip](https://github.com/Kenshin/simpread/files/12792685/simpread-Dual-Signal.Amplification.Strategy.for.Ultrasensitive.Photoelectrochemical.Immunosensing.of.-Fetoprotein._.Analytical.Chemistry.html.zip)

**Comment by threeyears121** [comment]
这篇文章不管是保存为epub还是onenote notion，图片都不能正常显示

**Comment by threeyears121** [comment]
> 其他网页呢？还是说就这个页面有问题？
> 
> 还有，依旧没回复我的问题…

哈哈，我是个技术门外汉，不好意思，您别着急，我以为我回复你了，图床网站没有看到论文的图片

**Comment by threeyears121** [comment]
另外下载为markdown文件上传notion图片也不能正常显示

**Comment by Kenshin** [comment]
> 哈哈，我是个技术门外汉，不好意思，我以为我回复你了，图床网站没有看到论文的图片

😂 .... 这跟技术无关，仔细看我的「提问」，我再重新说一次....

1. 看下图，测试下你的 Cloudinary 的设置是否正常。

<img width="513" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/767e1160-5a79-41d6-bf7f-d5cf27750732">

2. 如果测试通过的话，打开 https://sspai.com/post/69972 看看能否导入到 Notion

如果也成功的话，说明：

1. 你的 Cloudinary 配置没问题。

2. 正常的网站能导入，出问题的仅仅只是个例。

**Comment by threeyears121** [comment]
> > 哈哈，我是个技术门外汉，不好意思，我以为我回复你了，图床网站没有看到论文的图片
> 
> 😂 .... 这跟技术无关，仔细看我的「提问」，我再重新说一次....
> 
> 1. 看下图，测试下你的 Cloudinary 的设置是否正常。
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/81074/272487447-767e1160-5a79-41d6-bf7f-d5cf27750732.png">
> 2. 如果测试通过的话，打开 https://sspai.com/post/69972 看看能否导入到 Notion
> 
> 如果也成功的话，说明：
> 
> 1. 你的 Cloudinary 配置没问题。
> 2. 正常的网站能导入，出问题的仅仅只是个例。

验证了，是通过的，我按照简悦说明一步一步操作的

**Comment by threeyears121** [comment]
希望只是个例，我手动replace掉那些不显示的图片了

**Comment by Kenshin** [comment]
okay 只要没配置错就没问题。

Notion 还是走不少问题的，你可以多测试一些不同的网站，有问题再随时反馈。

**Comment by KennyNoDie** [comment]
针对一些非对外公开的内容，图片是禁止上传的，cloudinary图床会抓取失败，之前notion图床可以正常上传，这种情况有解决办法吗

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 升级到 1.2.0 

### 重点更新：导入到 Cloudinary 时不经过简悦自己的图片服务器

旧版 1.2.0（以上）会通过简悦的自己的服务器，优点是不需要耗费用户的设备性能；缺点是当为内网图片时无法使用；

新版 1.2.0（含），不经过简悦自己的图片服务器，解决了内网图片或某些有防盗链的图片无法上传的问题。

如：

1. 近期少数派更新了图片规则，导致无法使用旧方案上传，但版方案可以正常将少数派的图片上传到 Cloudinary

    <img width="1023" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8273730d-2cb5-45e9-9170-7fe32f800f03">

2. 内网图片无法使用此功能的问题

### 其它更新

`Fix` 导入图片如果是 `http:` 形式在 Notion 无法显示的问题

***

有任何问题请在汇总页面讨论 https://github.com/Kenshin/simpread/issues/5917

**Comment by Kenshin** [comment]
嗨

除了上面提到的 新版 Cloudinary 图床方案外，[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案，如果不想使用 Notion 的话，可以考虑这个插件。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955

**Comment by Kenshin** [comment]
嗨，[2.3.0.810](https://github.com/Kenshin/simpread/issues/7356) 发布了~

此版本提升图片的转换能力，解决了一些网站在 mv2 时代无法成功转换图片的问题，同时也支持内网图片的转换，包括：导出离线 HTML / PDF 等；在此基础上，增强了 Cloudinary 图床转换能力，自动匹配之前版本的 **本地/服务器** 方案，现在无须手动选择。

除此之外，还包含以下内容，详细说明 https://github.com/Kenshin/simpread/issues/7356

1️⃣ 新增功能 → 7 项
   - 批量补齐 / 更新多类网站的阅读适配
   - 部分站点支持「延迟加载」类规则
   - 小版本升级后加载最新官方适配列表
   - 搜索引擎匹配 2.0（支持 10 大引擎 + 嵌入/浮动双模式）
   - OneNote 适配 365 Offices 应用授权
   - 设置项支持搜索
   - 插件说明改为侧栏预览阅读

2️⃣ 修复错误 → 1 项
   - 坚果云无法使用的问题

3️⃣ 优化体验 → 8 项
   - 重构右上角登录系统（一键同步 + 自动授权）
   - 强制下载同步时稍后读覆盖、坚果云等边界情况
   - 关键词高亮与屏蔽 2.1.0
   - 阅读模式优化 1.2.0
   - 共通 → 手动同步文案更及时刷新
   - 选项页隐藏 RSS 嵌入相关入口
   - Google Drive / GitHub / 语雀 导出体验
   - WebDAV 配置保存与鉴权失败提示
   - 增强离线 HTML / 离线 Markdown / PDF 图片下载成功率
   - 「公告」类通知样式
   - 普通信息类通知颜色更清晰

4️⃣ 新增插件 → 2 个
   - [阅读统计](https://simpread.ksria.cn/plugins/details/3PHAZerSkb) → 原 高级版统计（用于英文阅读）
   - [导入到览道文档](https://simpread.ksria.cn/plugins/details/FJuWsQu3jI)

5️⃣ 更新插件 → 5 个
   - [关键词高亮与屏蔽](https://simpread.ksria.cn/plugins/details/iuIlA8bU5S) 2.1.0：支持关键词淡化等
   - [阅读模式优化](https://simpread.ksria.cn/plugins/details/xZVbwW4C5A) 1.2.0：相对路径等问题修复
   - [导入到 Obsidian](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 2.1.0：增强 Cloudinary 适配度
   - [导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 2.2.0：增强 Cloudinary 适配度
   - [图床](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 2.4.0：增强 Cloudinary 适配度

我关闭这个 Issues 了，有任何问题随时在这里讨论。
