### ISSUE TITLE
使用簡悅後的文檔不相同，可以解決嗎？

### ISSUE THREAD

**Issue by marioyin66** [Kenshin/simpread#5980]
### 描述这个错误

![截圖 2023-10-02 上午10 34 46](https://github.com/Kenshin/simpread/assets/24527079/b09bc7b5-7ca7-447d-945b-39219238c560)
![截圖 2023-10-02 上午10 35 08](https://github.com/Kenshin/simpread/assets/24527079/4acd937c-c04f-4259-bfa6-6dc4029e7db3)

同樣的網址，但是內容完全不同，請問如何解決這個問題？

### 复现步骤

1.打開網址 https://www.gvm.com.tw/article/106614
2.使用簡悅
3.出現不同原先網頁中的內容
4.請參考2個附檔，使用簡悅的前後比對
![截圖 2023-10-02 上午10 34 46](https://github.com/Kenshin/simpread/assets/24527079/2ecdbc6b-d6b1-4479-ae77-084a11e2c3c7)
![截圖 2023-10-02 上午10 35 08](https://github.com/Kenshin/simpread/assets/24527079/6db16f83-94ea-40b9-8b79-55db727a7d24)

### 操作系统

macos ventura 13.5.2

### 浏览器

chrome

### 发生问题的网址

https://www.gvm.com.tw/article/106614

**Comment by Kenshin** [comment]
嗨，你可以使用下面的方式手动进入阅读模式

<img width="632" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9fe33abb-b9bf-4fae-96d6-a5ab9fb0bb95">

除此之外，也可以看下 https://github.com/Kenshin/simpread/discussions/3340 提到的一些其它阅读模式技巧。

**Comment by Kenshin** [comment]
嗨，你可以使用下面的方式手动进入阅读模式

<img width="632" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9fe33abb-b9bf-4fae-96d6-a5ab9fb0bb95">

除此之外，也可以看下 https://github.com/Kenshin/simpread/discussions/3340 提到的一些其它阅读模式技巧。
