### ISSUE TITLE
无法启用 标注，点击后无反应

### ISSUE THREAD

**Issue by liuhognchen** [Kenshin/simpread#5983]
### 描述这个错误

进入阅读模式后，点击标注没有反应。
删除插件重装也没有反应。
删除浏览器数据也没有反应

### 复现步骤

<img width="1491" alt="image" src="https://github.com/Kenshin/simpread/assets/13975948/d0c51fbc-7f77-4a44-8870-da6699d18ef5">

### 其他相关说明

无

### 操作系统

macOS

### 浏览器

Microsoft Edge 版本 117.0.2045.47 (正式版本) (arm64)

### 发生问题的网址

https://sspai.com/post/83351

**Comment by Kenshin** [comment]
是不是使用了同步助手的自动同步？如果是的话，看下你的稍后读能否打开？如果没法打开的话，使用 https://github.com/Kenshin/simpread/discussions/5750 修复
