### ISSUE TITLE
同步助手.exe无法安装

### ISSUE THREAD

**Issue by hover163** [Kenshin/simpread#5984]
### 描述这个错误

下载应用程序安装，短暂读取后，就没有任何反应了。进程里没有，应用软件库里面也没有，看了很多办法，貌似没有看见这种情况发生，所以想问问。下载了1.2.0和初版都是相同的反应，请问有解决办法吗？谢谢!

### 复现步骤

1.官网下载各版本
2.解压
3.找到简悦·同步助手.exe
4.点击后，箭头出现小圈圈
5.无反应，重复点击.exe文件，有时右下会出现简悦LOGO小图标，不知道为什么。

### 操作系统

win10

### 浏览器

Chrome

### 发生问题的网址

无

**Comment by Kenshin** [comment]
试试右键点击右下角 logo …

**Comment by hover163** [comment]
不行，现在右下角的没有了，转成任务栏一闪而过，就自动关闭了。我把所有微软防护的软件全部应用都信任了，我在想是不是我没安装什么库软件呢，谢谢

**Comment by hover163** [comment]
> 试试右键点击右下角 logo …

不行，现在右下角的没有了，转成任务栏一闪而过，就自动关闭了。我把所有微软防护的软件全部应用都信任了，我在想是不是我没安装什么库软件呢，谢谢

**Comment by hover163** [comment]
> 试试右键点击右下角 logo …

是解压了，就算安装了吗，我弄好一阵了，有点米糊了。

**Comment by Kenshin** [comment]
> 不行，现在右下角的没有了，转成任务栏一闪而过，就自动关闭了。我把所有微软防护的软件全部应用都信任了，我在想是不是我没安装什么库软件呢，谢谢

不确定 😂 因为没有其它用户反馈过类似的问题，而且我使用的是 Mac 版。

但 Windows 不会发生无法使用的问题，当然个例有可能会存在（但仅你这一例）...

> 是解压了

解压后运行它，正常情况会出现一个设置说明。

**Comment by hover163** [comment]
我放在useer文件夹里面弄好，或者本来说就要放到用户文件夹里面，只是我不知道罢了？

**Comment by Kenshin** [comment]
> 我放在useer文件夹里面弄好，或者本来说就要放到用户文件夹里面，只是我不知道罢了？

理论上任意文件夹都行，除非你之前放的系统文件夹，理论上也行，但你应该没有赋予 `.exe` 系统管理员权限，估计是这个问题造成的。
