### ISSUE TITLE
阅读模式的自定义样式疑问

### ISSUE THREAD

**Issue by 17ever** [Kenshin/simpread#5985]
### 请描述你的建议或任何内容

![`@`THVBI40Z60I9}IC FLL2](https://github.com/Kenshin/simpread/assets/76164668/5bd4e54d-0791-45ab-bfdf-c4df069cea47)
如上图所示。搜索了一下，发现是read.jsx文件中的内容，如下图所示：
![7L60XV$7V8E8CON TNHQZFX](https://github.com/Kenshin/simpread/assets/76164668/11464b67-2ec8-44aa-8ff3-6d29dc425c26)
请问如何删除这段内容呢？似乎自定义样式、站点编辑器都无法解决，请作者赐教，打扰，感谢！

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/issues/5954#issuecomment-1732198808
