### ISSUE TITLE
在不打开Obsidian的情况下，导入无效

### ISSUE THREAD

**Issue by ernsky** [Kenshin/simpread#5986]
### 描述这个错误

在不打开Obsidian的情况下，导入无效

### 复现步骤

000

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

wx

**Comment by Kenshin** [comment]
是的，这不是 Bug...

有一个方案可以「变相」解决。如果你仅需要导出全文的话，可以使用：同步助手的增强导出，将 Markdown 直接导入到你指定的地方（即 Obsidian 库文件中） 或者 [assets + md 方案](https://github.com/Kenshin/simpread/discussions/4041)
