### ISSUE TITLE
难以关闭右上角提示，无法直接右键复制

### ISSUE THREAD

**Issue by 2003zjy** [Kenshin/simpread#5988]
### 请描述你的建议或任何内容

1.标注时候右上角会不断弹出“保存成功”的提示且我找了一圈也没找到这个提示怎么关闭。
2.无法直接右键复制，没有原来浏览器自己的右键菜单，无法实现选中快速搜索和直接复制，大大降低工作效率。

**Comment by 2003zjy** [comment]
（在阅读模式下）

**Comment by Kenshin** [comment]
> 问题1

https://github.com/Kenshin/simpread/discussions/3596

> 问题 2

因为你用了标注功能，所以划取功能被「监听」了，你可以关闭连续标注或标注。

右键菜单是可以使用的。
