### ISSUE TITLE
Wikibooks: 网页加载后内容消失

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#5989]
### 描述这个错误

开启 extension 后 `mw-content-text` 下的 `mw-parser-output` 消失.
Before
![before](https://github.com/Kenshin/simpread/assets/88515612/fdd2e462-9e5c-404c-8202-3ad8b6bde62a)

After
![after](https://github.com/Kenshin/simpread/assets/88515612/b6787b85-04ff-464c-953d-8484348f1bf9)

### 复现步骤

1. [Open Page](https://en.wikibooks.org/wiki/Main_Page)
2. 主要内容加载后消失

### 操作系统

Windows 10

### 浏览器

Edge

### 发生问题的网址

https://en.wikibooks.org/wiki/Main_Page

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347
