### ISSUE TITLE
chrome 或edge浏览器中,全新安装未配置的简悦插件导致某些网页无法正常渲染加载

### ISSUE THREAD

**Issue by gigberg** [Kenshin/simpread#5991]
### 描述这个错误

在访问维基大学的网页时,由于简悦插件导致该网页[https://en.wikiversity.org/wiki/Wikiversity:Main_Page](https://en.wikiversity.org/wiki/Wikiversity:Main_Page)无法正常加载,卸载该插件后网页正常加载,测试chrome和edge浏览器均有上述bug.

### 复现步骤

如上

### 操作系统

windows 10

### 浏览器

chrome, edge

### 发生问题的网址

https://en.wikiversity.org/wiki/Wikiversity:Main_Page

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347
