### ISSUE TITLE
（已在阅读模式）未作任何标记可以导出HTML全文，但是作了标记之后导出HTML只有标记没有全文

### ISSUE THREAD

**Issue by raincare** [Kenshin/simpread#5993]
### 描述这个错误

问题一：（已在阅读模式）未作标记时可以导出HTML全文，但是作了标记之后导出HTML，只有标记没有全文。我的个人“导出”需求是，网页阅读时直接标记和备注的想法，含在全文里一起导出，之前设置自动导出的格式是MD，看了操作说明，提示MD导出格式不支持带有标注的全文，于是改成导出HTML， 但是尝试了很多次，仍然不能导出全文，每次导出的都是标记。
问题二：加入稍后读也是一样，标记后的文章，自动导出后只有标记没有全文，我在”自动化设置“已设置两条，加入标记一条，自动导出为MD，加入稍后读一条，自动导出为HTML，但是看来只有标记导出成功，全文不行。

以上是我碰到的问题，不知道是否设置有误导致，还是在全文加标注导出的功能实现上理解有误，请K大悉心指导下，如何导出全文含标记的格式文本的具体操作步骤和具体设置，谢谢

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/132796596/de1f9f2a-2fe6-4d85-b4b2-c4e449918e58)
![image](https://github.com/Kenshin/simpread/assets/132796596/36afc9b1-0270-45d3-a9bc-a5da0f809844)
![image](https://github.com/Kenshin/simpread/assets/132796596/c945e704-4faa-400b-a259-b49e95f99ba8)
![image](https://github.com/Kenshin/simpread/assets/132796596/9241ea64-6854-4cea-a633-459a37c50caf)
![image](https://github.com/Kenshin/simpread/assets/132796596/08e365e2-d7c6-48ff-aee2-a253cf1d9662)
以上是我的设置

### 操作系统

工作办公室win7 32位，家庭mac最新版os

### 浏览器

戴尔显示器

### 发生问题的网址

https://sspai.com/post/83300

**Comment by Kenshin** [comment]
嗨

保存时即有全文，又有标注的功能在简悦这边叫做「知识库方案」，或者也可以叫「本地快照」方案。

https://www.yuque.com/kenshin/simpread/wkswh7 是这个功能的教程，你可以对比下。

重点是这个地方的设置 https://www.yuque.com/kenshin/simpread/wkswh7#phV3U

<img width="1036" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1829b6af-d9e1-4afd-87f4-5fd2b6d7aa55">

**Comment by raincare** [comment]
收到，好的，谢谢K大回复，我去尝试下

**Comment by Kenshin** [comment]
小事情~ 😄

如果不设置标题的话，也是同时保存两个文件，只是相同的名称，全文先保存，然后是标注，后者把前者覆盖了，因此你看到的是一个文件。

**Comment by raincare** [comment]
> 小事情~ 😄
> 
> 如果不设置标题的话，也是同时保存两个文件，只是相同的名称，全文先保存，然后是标注，后者把前者覆盖了，因此你看到的是一个文件。

感谢K大的提示，现在可以自动导出含标记的全文了（通过在“定制导出”模块中添加一条标题字符），但是实现路径是：一、在阅读模式下，划线标记，系统会将文章自动添加到稍后读，此时坚果云同步盘中自动导出了两个MD文件，一个是标记的MD，一个是全文（不含标记）的MD。二、进入稍后读，进入稍后读的阅读模式（非标记模式），进入文章，点击选取右上角的工具栏，导出为HTML，此时，坚果云同步盘的两个MD文件被替换成两个HTML文件，一个全文+标记的HTML，一个单独标记的HTML。
请问K大，一、导出全文（加标记）的实现路径是以上这样的吗，有没有在网页阅读模式下标注后直接可以自动导出全文加标记的方案。二、阅读文章添加标注后，系统自动添加到稍后读，请问K大这个自动操作是在哪个模块设置的，我忘了在哪，这是用户设置的还是系统默认的。三、有没有稍后读的自动同步功能（在稍后读中再编辑标记或标注后的文章，可以和同步盘保持同步）

注：我在自动化模块里的设置是“加入稍后读”执行自动导出HTML，“加入标注”自动执行导出MD，但是自动化导出的是两个MD

**Comment by Kenshin** [comment]
> 坚果云同步盘的两个MD文件被替换成两个HTML文件。

不应该存在 Markdown 被替换为 HTML 文件的情况，

> 导出全文（加标记）的实现路径是以上这样的吗，有没有在网页阅读模式下标注后直接可以自动导出全文加标记的方案。

自动化的最佳方案是：

使用快捷键 <kbd>d</kbd> <kbd>d</kbd> 加入稍后读，而后在标注，而不是直接就标注（后自动加入稍后读）。

因为自动化的构建在于产生稍后读，而你的这种做法会有点问题，使用这个流程后可能会 **自动修复** 你提到的问题。

当使用我提到的方式后：

1. 首次加入稍后读（这时没有标注），会产生两个 HTML 文件

2. 标注，会更新这两个 HTML，同时产生两个 Markdown 文件。（根据你提供的自动化设置方案）

> 有没有稍后读的自动同步功能

在稍后读中标注的话，是可以触发自动化的。

**Comment by raincare** [comment]
收到

**Comment by raincare** [comment]
> > 坚果云同步盘的两个MD文件被替换成两个HTML文件。
> 
> 不应该存在 Markdown 被替换为 HTML 文件的情况，
> 
> > 导出全文（加标记）的实现路径是以上这样的吗，有没有在网页阅读模式下标注后直接可以自动导出全文加标记的方案。
> 
> 自动化的最佳方案是：
> 
> 使用快捷键 d d 加入稍后读，而后在标注，而不是直接就标注（后自动加入稍后读）。
> 
> 因为自动化的构建在于产生稍后读，而你的这种做法会有点问题，使用这个流程后可能会 **自动修复** 你提到的问题。
> 
> 当使用我提到的方式后：
> 
> 1. 首次加入稍后读（这时没有标注），会产生两个 HTML 文件
> 2. 标注，会更新这两个 HTML，同时产生两个 Markdown 文件。（根据你提供的自动化设置方案）
> 
> > 有没有稍后读的自动同步功能
> 
> 在稍后读中标注的话，是可以触发自动化的。

请教K大，两台终端之间的稍后读可以同步吗，需要怎么设置，我的办公室和家庭的稍后读列表不一致，已经设置坚果云为同步盘，能同步导出的文件，但是稍后读界面不能同步，哪个环节设置出问题了呢？

**Comment by Kenshin** [comment]
> 请教K大，两台终端之间的稍后读可以同步吗

可以的，有手动方案和自动方案，细节的话，看下 https://www.yuque.com/kenshin/simpread/ebwu7g

**Comment by raincare** [comment]
> > 请教K大，两台终端之间的稍后读可以同步吗
> 
> 可以的，有手动方案和自动方案，细节的话，看下 https://www.yuque.com/kenshin/simpread/ebwu7g

K大，我之前两台设备都设置了同步盘和同步助手，但是稍后读还是无法同步，有没有说明办法帮我看下是哪个设置出问题了吗？

**Comment by Kenshin** [comment]
看下这个教程 https://www.yuque.com/kenshin/simpread/pwpnsx#TCQKB 重点是下面三个内容

<img width="208" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fbced7b5-120e-4ec2-84ab-cc770a1e2838">

**Comment by raincare** [comment]
> 看下这个教程 https://www.yuque.com/kenshin/simpread/pwpnsx#TCQKB 重点是下面三个内容
> 
> <img alt="image" width="208" src="https://user-images.githubusercontent.com/81074/273776139-fbced7b5-120e-4ec2-84ab-cc770a1e2838.png">

谢谢，已经找到原因，家庭电脑未设置到simpread文件夹下

**Comment by Kenshin** [comment]
Cool 解决就好 👍

PS：我关闭这个 Issues 了，有任何问题你仍可以在这里跟我讨论~
