### ISSUE TITLE
知乎文章页面导出md会遗漏部分图片

### ISSUE THREAD

**Issue by zaw007** [Kenshin/simpread#5994]
### 描述这个错误

知乎文章页面导出md会遗漏部分图片，阅读模式下内容完整，导出时不管是markdown还是离线markdown均出现图片遗漏的问题，导出html和离线html无问题，检查后发现此问题出现在文章有连续图片时，有连续图片时，导出markdown只保留了最后一张图片，检查md源码和图片，确认为内容中没有图片链接，图片目录内也没有下载图片。

### 复现步骤

文章地址：https://zhuanlan.zhihu.com/p/156964823

原文章
![image](https://github.com/Kenshin/simpread/assets/25732226/4a15ebd2-4de9-4029-bcd0-bfa554ee7ec0)
阅读模式
![image](https://github.com/Kenshin/simpread/assets/25732226/3e636c2a-51b1-4edf-a5da-2fadccd806d3)
markdown
![image](https://github.com/Kenshin/simpread/assets/25732226/791e1aaf-2d82-40d6-b2e3-2afc2563b929)

### 操作系统

Windows 10

### 浏览器

360极速浏览器X Chrome内核为95

### 发生问题的网址

https://zhuanlan.zhihu.com/p/156964823

**Comment by Kenshin** [comment]
估计是没有安装 https://github.com/Kenshin/simpread/discussions/2861 插件造成的。

**Comment by zaw007** [comment]
> 估计是没有安装 #2861 插件造成的。

这个插件装了的

**Comment by Kenshin** [comment]
这是我导入到 Obsidian 的文件（使用相同的 Markdown 引擎），你看看有没有问题。

[饥荒联机版大型攻略——生存篇.md](https://github.com/Kenshin/simpread/files/12842574/default.md)

什么都没做，就是在安装这个插件的基础上，滚动条到最下方，然后导出。

**Comment by zaw007** [comment]
> 这是我导入到 Obsidian 的文件（使用相同的 Markdown 引擎），你看看有没有问题。
> 
> [饥荒联机版大型攻略——生存篇.md](https://github.com/Kenshin/simpread/files/12842574/default.md)
> 
> 什么都没做，就是在安装这个插件的基础上，滚动条到最下方，然后导出。

这个没问题，但我同样的方法导出离线markdown、md+assets、textbundle还是有问题，仍然缺少图片

**Comment by Kenshin** [comment]
在页面的图片很多（已经 100+ 的图片了，而且很多图片 size 很小）的情况下，建议使用 **离线 HTML**。

这是我通过离线 HTML 导出的，应该没问题，但 size 太大了，我就不传上来了。

***

`离线 Markdown` 肯定不行，效果非常差，大部分 Markdown 工具都没法成功打开。

`md+assets` 与 `textbundle` 本质上是一个东西，在个别情况下会有转换失败的情况，目前报告了应该不超过 10 例。
