### ISSUE TITLE
多个浏览器使用简悦时只有一个生效，其余的均提示：当前用户不是高级账户

### ISSUE THREAD

**Issue by TheTruthYouKnow** [Kenshin/simpread#5995]
### 描述这个错误

多个浏览器使用简悦时只有一个生效，
其余的均提示：当前用户不是高级账户，
到插件的账户页面查看又提示已解锁高级账户。

所有的浏览器之前均是通过同步助手完成同步。
无论是使用同步助手的自动同步还是手动覆盖配置文件均无法解决该问题。
使用的浏览器：
chrome 83.0 
chrome 105
chrome 自动更新
edge

### 复现步骤

不知道怎么出现的怎么复现????

### 操作系统

Windows10

### 浏览器

chrome+edge+Firefox

### 发生问题的网址

https://cornradio.github.io/hugo/posts/%E8%AE%A9steam%E7%BB%95%E8%BF%87clash%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86/

**Comment by Kenshin** [comment]
因为你使用了同步助手，但在描述中并没有说明如何导入的的这些数据文件，所以试试下面的方案：

1. 先取消高级账户授权 https://www.yuque.com/kenshin/simpread/hdcwoq

2. 重启浏览器后再重新授权 https://www.yuque.com/kenshin/simpread/sw4m21

最简单的导入方案：

1. 选项页 → 共通 → 从本地的配置文件导入（找到包含正确 UID 的配置文件导入，然后简悦会自动授权。
2. 当成功授权后，选项页 → 插件管理 → 从配置文件导入插件

还有，你也没有说明是否使用了自动同步。

要是动手能力强的话，看下 https://www.yuque.com/kenshin/simpread/dgmm5q 这个流程说明。

**Comment by TheTruthYouKnow** [comment]
> 因为你使用了同步助手，但在描述中并没有说明如何导入的的这些数据文件，所以试试下面的方案：
> 
> 1. 先取消高级账户授权 https://www.yuque.com/kenshin/simpread/hdcwoq
> 2. 重启浏览器后再重新授权 https://www.yuque.com/kenshin/simpread/sw4m21
> 
> 最简单的导入方案：
> 
> 1. 选项页 → 共通 → 从本地的配置文件导入（找到包含正确 UID 的配置文件导入，然后简悦会自动授权。
> 2. 当成功授权后，选项页 → 插件管理 → 从配置文件导入插件
> 
> 还有，你也没有说明是否使用了自动同步。
> 
> 要是动手能力强的话，看下 https://www.yuque.com/kenshin/simpread/dgmm5q 这个流程说明。

无论使用何种方式导入都无法解决该问题（本地文件导入，同步助手导入），选项中使用自动同步/手动同步都试了，

目前排查出的原因是插件的所有的有关配置文件导出的功能的不完全。这个是你的插件问题了，
副本的是自动保存的，
36KB那个是同步助手覆盖本地配置文件/导出配置到本地的

![53249 Image 662x41](https://github.com/Kenshin/simpread/assets/131973717/d45967b1-3f84-48df-8d39-de1961c3e32f)

**Comment by TheTruthYouKnow** [comment]
两个文件的对比
119KB的包含插件的设置
36KB的是使用 同步助手覆盖本地配置文件/导出配置到本地 方式导出的，不包含插件设置
![Snipaste_2023-10-09_13-52-42](https://github.com/Kenshin/simpread/assets/131973717/5a9d3229-4684-4cfb-9099-bbe7b6c5980a)
