### ISSUE TITLE
导入到 Obsidian 的文章无法正常显示配图

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#5998]
### 描述这个错误

当前obsidian版本：
![image](https://github.com/Kenshin/simpread/assets/57386018/d1876f2c-b800-444f-9bc2-8931f4125183)

在网页端打开需要阅读的页面，并添加到稍后读→ 导入到obsidian后，在阅读模式下显示的banner效果，obsidian升级到带有属性版本的后，Bannner无法显示题图效果.

![image](https://github.com/Kenshin/simpread/assets/57386018/7bcce0f8-0caa-4386-8230-567df96ef60e)

### 复现步骤

由于obsidian是全局软件更新，其他库也是显示新版属性，所以无法提供旧版obsidian下的Banner题图效果截图. 

### 操作系统

Win11

### 浏览器

Edge

### 发生问题的网址

https://www.appinn.com/pin-kuaidi-code/

**Comment by Kenshin** [comment]
这不是简悦的问题，你需要在阅读视图中查看....

但 Banner 确实在 `1.4.x` 下有问题，解决方案 https://forum.obsidian.md/t/banners-plugin-that-works-with-obsidian-1-4-0-and-above/65142/3

**Comment by mdsnalw** [comment]
谢谢大佬，我已经使用了文章中的第二个方案，第一个方案通过启用自定义的CSS方法对我来说好像不奏效. 使用安装Beta版Banner插件，终于启用了Banner，效果也还算可以，聊胜于无也治愈了我的强迫症，哈哈~

![image](https://github.com/Kenshin/simpread/assets/57386018/b2260ab9-70a0-4041-a2a7-6aa66f588df1)
![image](https://github.com/Kenshin/simpread/assets/57386018/19b699cd-ad42-4c66-b2de-d765b3dd7335)

**Comment by Kenshin** [comment]
哈，解决就好~
