### ISSUE TITLE
划词翻译软件右下角悬浮窗展示bug

### ISSUE THREAD

**Issue by discalced** [Kenshin/simpread#5999]
### 描述这个错误

在简悦设置右下角控制栏自动隐藏的情况下，划词翻译插件的悬浮窗还会一直存在，不会随着其它悬浮窗一起隐藏，十分不协调，而且即使是控制栏非隐藏的设置下，这个东西一直展示在那里的意义是什么？ 又不能点击。 仅仅是提醒用户， 你安装了这个插件？

### 复现步骤

1. 安装“划词翻译”插件
2. 关闭 设置-高级设置-阅读模式-是否一直展示右下角控制栏 选项
3. bug出现
![微信截图_20231013015947](https://github.com/Kenshin/simpread/assets/1122254/74e7e848-34e6-4207-84db-1d47468395ee)

### 其他相关说明

再补充个其它问题，在这里一并说了：
阅读模式设置页面宽度之后， 拉窄浏览器宽度到一定的尺寸，里面的内容会随之被挤窄，但是外面会有很大的空白，就是文字周围的padding不变， 但是文字会越来越窄。
当然，这是因为版面宽度是按窗口比例设置的吧。
这在某些场景下会很困扰，比如我屏幕左边开着笔记软件，右边是简悦的阅读模式，这种情况下浏览器只能使用一半屏幕，这时候内容变得十分窄，我还得手动调整板面宽度到很大比例。然后，当浏览器全屏的时候，我还得调回去。
建议：增加个绝对宽度的设置，让我自己设置内容宽度的px值。

### 操作系统

windows

### 浏览器

chrome最新

### 发生问题的网址

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

**Comment by Kenshin** [comment]
> 问题1

右下角是关于加载生词本的功能，细节看下 https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499395 如果你不需要的话，可以关闭它。

这个功能是插件功能，跟右下角隐藏没有关系，但你提到的确实是个「问题」，我考虑下。

> 问题2

你可以使用 [自定义样式](https://simpread.pro/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决或者试试 https://github.com/Kenshin/simpread/discussions/2628
