### ISSUE TITLE
CocoaChina 部分文章详情页

### ISSUE THREAD

**Issue by yun0628** [Kenshin/simpread#60]
在阅读cocoaChina 上 部分详情页  适配的不是很好  希望作者可以优化下  谢谢作者的开源和努力 下面是一个文章详情的链接  
http://www.cocoachina.com/industry/20140218/7841.html
![image](https://user-images.githubusercontent.com/8709108/29011004-25096334-7b62-11e7-8a73-4d31188f230c.png)

**Comment by Kenshin** [comment]
@yun0628 
感谢肯定以及反馈~

看了一下，原因是：
简悦的阅读模式特点：识别不同页面相同结构，而给出的页面与 简悦适配的 `页面结构不一致，所以才出现了你说的问题。

### 简悦适配的页面结构
![image](https://user-images.githubusercontent.com/81074/29016088-7e1cac94-7b83-11e7-8663-c32a4138754f.png)

### 对应的页面类似 http://www.cocoachina.com/industry/20170807/20162.html
![image](https://user-images.githubusercontent.com/81074/29016141-c18b8bb2-7b83-11e7-950b-20cdbe0e733a.png)

### 出问题的页面
![image](https://user-images.githubusercontent.com/81074/29016179-e63d2cfe-7b83-11e7-9f64-923ed7e0c55a.png)

### 解决方案：
修改这个页面的高亮区域，即：
![image](https://user-images.githubusercontent.com/81074/29016288-6c2f55e4-7b84-11e7-91c1-5db263f070c7.png)

红框内容改为
```
[[{$('#detailbody').html()||$('#article').html()}]]
```
即可。
![image](https://user-images.githubusercontent.com/81074/29016540-6622167c-7b85-11e7-9b64-e957d59c3e3a.png)

**Comment by Kenshin** [comment]
我将关闭此 issues，有异议的话，请在重新打开它。
