### ISSUE TITLE
简阅的页面能否像酷安网页版那样自动适应手机屏幕？

### ISSUE THREAD

**Issue by cangling** [Kenshin/simpread#600]
我在kiwi浏览器安装了扩展，能用。但生成的页面是电脑版的，整个页面缩小了，字体也小了，要放大看。

能否像酷安网页版那样自动适应屏幕？那样离线保存的html页面(包括离线插件保存的)也能在手机上看了。

另，离线保存的MD文件是否可使用Base64编码插入图片，如这个
https://www.jxtxzzw.com/archives/1700

谢谢！

**Comment by Kenshin** [comment]
Kiwi Browser 版本身就适配了手机端，所以你说的情况，最好给我链接，方便判断。

离线下载可以试试这个插件 https://github.com/Kenshin/simpread/issues/508

**Comment by cangling** [comment]
我知道JS脚本那个适配了手机，但不能离线保存啊！
我是在 Kiwi 安装了完整版的扩展，是为了离线保存网页。但启用简阅后，页面太宽，文字都出了屏幕，字体也太小。 查看在电脑上保存的离线文件也是同样的问题。

酷安
https://www.coolapk.com/apk/com.coolapk.market

在电脑上，当把浏览器窗口缩小时（模仿手机屏幕），页面也会跟着改变，而不是出现横向滚动条。
![coolapk-2](https://user-images.githubusercontent.com/7885420/67751163-8fa65c80-fa6b-11e9-900d-d4531fa6faf6.png)

如果简阅保存的离线html文件能像这样自动适应小屏幕，那在电脑上保存的离线页面在手机上也能看了。


或者，苹果的 jsbox 版本的能否移植到安卓？

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

已增加导出到 [离线下载](http://ksria.com/simpread/docs/#/离线HTML) 的功能，另外，导出的 HTML 也适配了手机端的样式。

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by cangling** [comment]
感谢适配！
原始html离线图片需要下载授权，只看到简悦提示需要授权，但kiwi没有弹出授权窗口。

请问，能否自己修改 kiwi 的设置给简悦授权，如 about:flags，或直接修改某个配置文件？ 谢谢！

**Comment by Kenshin** [comment]
@cangling 

我关闭了当前这个 issues 又重开了一个，请在新的 issues 讨论。
