### ISSUE TITLE
导致嘉立创list子网站卡死

### ISSUE THREAD

**Issue by sclbeta** [Kenshin/simpread#6000]
### 描述这个错误

访问list.szlcsc.com网站，例如https://list.szlcsc.com/catalog/484.html
如果开启了simpleread，则网站卡死
如果关闭，则网站能够正常打开
实测是以下几个文件无法加载
![image](https://github.com/Kenshin/simpread/assets/7965247/031cb4e1-d951-4552-9fed-f4f4dcf73e05)

### 复现步骤

1. 打开simpleread
2. 访问网站https://list.szlcsc.com/catalog/484.html
3. 访问失败

1. 关闭simpleread
2. 访问https://list.szlcsc.com/catalog/484.html
3. 访问成功

### 操作系统

windows 11

### 浏览器

edge试过多个版本都有问题

### 发生问题的网址

https://list.szlcsc.com/catalog/484.html

**Comment by Kenshin** [comment]
我测试了下，没有遇到这个问题。

1. 你可以在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

2. 可以将 `szlcsc.com` 加入黑名单后重启浏览器

    <img width="901" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b823bfb0-4b2c-4715-92b4-63d2e7286f4e">
