### ISSUE TITLE
虎嗅网址加入稍后读之后，无法打开，但可以在阅读模式下打开

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#6001]
### 描述这个错误

https://www.huxiu.com/article/733405.html
https://www.huxiu.com/article/2167575.html
测试了两个地址，文章地址如上，页面加入稍后读之后，无法打开，提示“解析正文失败”，但可以在阅读模式下正常转换。

### 复现步骤

1. 使用“阅读模式”。可正常转化页面。
2. 加入到稍后读之后，无法打开，提示“解析正文失败”

### 操作系统

win10

### 浏览器

Edge 版本 117.0.2045.60 (正式版本) (64 位)

### 发生问题的网址

https://www.huxiu.com/article/733405.html

**Comment by Kenshin** [comment]
嗨，这算是「正常情况」，并不是每个网页都能在稍后读中正常查看，尤其是动态加载类的页面，解决方案是：使用简悦的本地快照方案 https://www.yuque.com/kenshin/simpread/wkswh7
