### ISSUE TITLE
代码段增强插件出错

### ISSUE THREAD

**Issue by Jason-233** [Kenshin/simpread#6003]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/80149221/d09a159b-3898-4ffa-be83-c2e811ce3363)
插件直接报错

### 复现步骤

在https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-files/cheatsheet这个网站上，我手动选择如图需要的部分，进入阅读模式后就成了图上的样子。

### 操作系统

win10

### 浏览器

Microsoft Edge 版本 117.0.2045.60 (正式版本) (64 位)

### 发生问题的网址

https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-files/cheatsheet

**Comment by Jason-233** [comment]
https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-classes/cheatsheet
这里也出现一样的问题，可能是代码段在此页上有个横向滑动窗口？

**Comment by Kenshin** [comment]
收到~

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
