### ISSUE TITLE
已经成功配置了本地加载方案，在稍后读中查看虎嗅加载图片失败

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#6004]
### 描述这个错误

如题，网址：https://www.huxiu.com/article/733405.html

已按照“一站式知识库配置”的步骤配置，自动同步导出，选择的是“html”，并且在稍后读中打开对应文章也显示local图标，但是文章中图片加载不全。最后两张图持续显示加载中。

### 复现步骤

1. 已配置“一站式知识库配置”
2. 打开https://www.huxiu.com/article/733405.html
3. 打开阅读模式
4. 在阅读模式下加载完所有的图片，并打开加入到稍后读
5. 提示全部自动保存。
6. 打开稍后读，发现文章最后两张图始终无法加载出来。
7. 重复多次仍然是这个情况。

### 操作系统

Win10

### 浏览器

Microsoft Edge版本 117.0.2045.60 (正式版本) (64 位)

### 发生问题的网址

https://www.huxiu.com/article/733405.html

**Comment by Kenshin** [comment]
你可以试试其他网站，如少数派的。
用来判断你的配置是否正常。

**Comment by Sssugus** [comment]
> 你可以试试其他网站，如少数派的。 用来判断你的配置是否正常。

在其他网站上面测试是正常的。

**Comment by Kenshin** [comment]
我这边没有问题，你可以试试将 `huxiu.com` 加入 [延迟加载列表](https://simpread.pro/docs/#/%E5%BB%B6%E8%BF%9F%E5%8A%A0%E8%BD%BD%E5%88%97%E8%A1%A8) 然后重启浏览器，**等图片全部加载完毕后再进入阅读模式，再加入稍后读**。

PS：因为你已经加入了稍后读，所以可以在 **等图片全部加载完毕后再进入阅读模式** 步骤后，手动生成一次快照

<img width="288" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9609138a-8099-4738-816b-a3a893cd3867">
