### ISSUE TITLE
网页阅读模式解析变形

### ISSUE THREAD

**Issue by t427794321** [Kenshin/simpread#6005]
### 描述这个错误

url: https://mp.weixin.qq.com/s/kE6a-4rFetYYaeR5LTDVKw

### 复现步骤

进入阅读模式: https://mp.weixin.qq.com/s/kE6a-4rFetYYaeR5LTDVKw

### 操作系统

macos: 10.13.6 (17G14033)

### 浏览器

版本 116.0.5845.187（正式版本） (x86_64)

### 发生问题的网址

https://mp.weixin.qq.com/s/kE6a-4rFetYYaeR5LTDVKw

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/5851
