### ISSUE TITLE
轻阅在greasyfork上被删除

### ISSUE THREAD

**Issue by whenham** [Kenshin/simpread#6006]
### 描述这个错误

[greasyfork](https://greasyfork.org/zh-CN/scripts/39998) 显示

> 请求的脚本已被删除。不过，这里有一些相关的脚本。

[raw.githubusercontent](https://raw.githubusercontent.com/Kenshin/simpread-little/master/src/userscript/simpread.js)加载显示

> 加载脚本依赖发生错误。

### 复现步骤

点进下载轻阅的两个链接

### 其他相关说明

暴力猴v2.15.0
chromium 版本 108.0.5359.125（Official Build, ungoogled-chromium） （64 位）

### 操作系统

windows10

### 浏览器

chromium 版本 108.0.5359.125（Official Build, ungoogled-chromium） （64 位）

### 发生问题的网址

https://greasyfork.org/zh-CN/scripts/39998

**Comment by Kenshin** [comment]
嗨，轻阅版仅仅只是 1.x 的部分功能，所以暂时不提供了。有需要请使用 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 版
