### ISSUE TITLE
同步助手安装失败问题

### ISSUE THREAD

**Issue by BubbleUpo0O** [Kenshin/simpread#6007]
### 描述这个错误

之前安装过同步助手1.2.0并且可以正常运行，但是后来每次电脑开机就会出现“A JavaScript error occurred .. ”的问题，找到根源是C盘-Appdata-temp-简悦同步助手之后我就直接将这个文件删除了，后面重新下载同步助手，不论是什么版本，win64还是win32，1.2.0还是1.1.4，全都无法打开exe程序，没有报错，就是没有任何响应。

### 复现步骤

.

### 操作系统

win64

### 浏览器

chorme

### 发生问题的网址

这个不用啦

**Comment by BubbleUpo0O** [comment]
抱歉打扰，按照 #5984 的方式解决了，文件夹移动至user下就可以了。

**Comment by Kenshin** [comment]
okay 解决就好。

PS：把非系统级的 `.exe` 放到 Windows 敏感文件夹确实不是一个好习惯。
