### ISSUE TITLE
阅读模式下公式的无法正常排版

### ISSUE THREAD

**Issue by zzrzzr0123** [Kenshin/simpread#6009]
### 描述这个错误

对于一下的网页，展开阅读模式下，公式会变得非常大，而且是分散开来的占据了这个宽度
https://mp.weixin.qq.com/s/ERCd3Qlas4jVazDxDjXqnQ
![image](https://github.com/Kenshin/simpread/assets/130990085/d4f316b8-5dde-4294-aca4-a832aea13c2d)

### 复现步骤

1.打开这个网页
2. aa快捷键，进入阅读模式

### 操作系统

Window10

### 浏览器

Chrome 117.0.5938.152

### 发生问题的网址

https://mp.weixin.qq.com/s/ERCd3Qlas4jVazDxDjXqnQ

**Comment by Kenshin** [comment]
解决方案可以看下 https://github.com/Kenshin/simpread/discussions/5851
