### ISSUE TITLE
字体类型选项失效

### ISSUE THREAD

**Issue by ravenxrz** [Kenshin/simpread#601]
感谢提供这个插件，总体使用感受非常好，但是字体类型选项却没有效果。
使用环境：Win10+Chrome 78.0.3904.70（正式版本） （64 位）

**Comment by Kenshin** [comment]
嗨，谢谢使用。

***

首先，确保这些字体已经安装在你的 PC
其次，确保 Chrome （或扩展）没有更改过字体 _某些 Chromium 变种有这种选项_

另外，确实在 PC 端偶尔存在字体无法更改的情况。

**Comment by ravenxrz** [comment]
@Kenshin 感谢回信，的确是没有安装相关字体的原因，安装后可以正常使用，在此感谢，哈哈。
