### ISSUE TITLE
疑似（代码段较多的）长文章导入到notion代码段出错

### ISSUE THREAD

**Issue by akaramatsu** [Kenshin/simpread#6010]
### 错误截图：
<img width="768" alt="image" src="https://github.com/Kenshin/simpread/assets/81050626/88ee596c-02a3-4660-b0bf-34f44b9b3ee8">
### 原文阅读模式：
<img width="699" alt="image" src="https://github.com/Kenshin/simpread/assets/81050626/3f811bd5-70a0-472c-9bd2-c97b5552f287">

把markdown正文识别为代码，把代码识别为正文，不知道如何解决

### 复现步骤

配置：notion配置库基础版
1.打开 [https://zhuanlan.zhihu.com/p/626966526]
2.aa进入阅读模式，此时一切正常
3.dd一键导入notion
4.在notion中打开保存文章，内容出错
### 错误截图：
<img width="768" alt="image" src="https://github.com/Kenshin/simpread/assets/81050626/88ee596c-02a3-4660-b0bf-34f44b9b3ee8">
<img width="699" alt="image" src="https://github.com/Kenshin/simpread/assets/81050626/7374059b-7f76-43da-8f7f-7c0fa3dfdf1c">

### 操作系统

MacOs 14.0

### 浏览器

Chrome 117.0.5938.149（正式版本） (arm64)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/626966526

**Comment by Kenshin** [comment]
嗨，你试试导出 Markdown 到本地，如果没有问题的话，基本上就是 Notion 的锅。
