### ISSUE TITLE
阅读模式缺少内容

### ISSUE THREAD

**Issue by abd-liac** [Kenshin/simpread#6012]
### 描述这个错误

[此页面](https://www.learningscientists.org/blog/2023/7/27/learning-math-from-errors)阅读模式缺少内容.
注意图片后的内容.

### 复现步骤

1. 进入阅读模式

### 操作系统

Windows 10

### 浏览器

Edge

### 发生问题的网址

https://www.learningscientists.org/blog/2023/7/27/learning-math-from-errors

**Comment by Kenshin** [comment]
嗨，试试下图的方案

<img width="613" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a712f609-78a7-48dd-918f-546cbcc23a29">

关于阅读模式的高级用法，也可以看下 https://github.com/Kenshin/simpread/discussions/3340
