### ISSUE TITLE
CSDN已购买的付费文章无法打开阅读模式

### ISSUE THREAD

**Issue by NobleFlower** [Kenshin/simpread#6013]
### 描述这个错误

无法打开阅读模式，简悦插件为灰色

### 复现步骤

先验条件：账户已订阅该专栏
1. 该专栏试读章节可以正常打开，体验良好
2. 对于后面的付费章节，尝试打开阅读模式时，弹窗
![image](https://github.com/Kenshin/simpread/assets/119724775/744a9158-f52b-48da-96d1-6d30576cd9c3)
刷新后页面无变化

### 操作系统

Ubuntu 22.04

### 浏览器

Google Chrome 版本 118.0.5993.70（正式版本） （64 位）

### 发生问题的网址

https://blog.csdn.net/weixin_39977764/article/details/123324034

**Comment by Kenshin** [comment]
> 配置文件提示信息

重启浏览器

> 无法正常使用

https://github.com/Kenshin/simpread/discussions/3340 留意 **重新高亮** 一般都能解决。
