### ISSUE TITLE
我在配置obsidian配置库高级版时遇到了问题

### ISSUE THREAD

**Issue by Crycrysmile** [Kenshin/simpread#6016]
### 请描述你的建议或任何内容

按照教程的步骤完成后，我现在在网站上标注的东西不能实时同步到obsidian中。并且无法在obsidian中打开内置链接。
<img width="809" alt="image" src="https://github.com/Kenshin/simpread/assets/148421294/c193ea4d-07be-4dc6-b322-6d0d573d8d28">
我可以通过这个按钮完成手动同步
<img width="605" alt="image" src="https://github.com/Kenshin/simpread/assets/148421294/da71d4ba-b40c-40a7-b986-206ffd281bca">
请问这是出了什么问题，我应该怎么做才能让它自动同步，并且能够在obsidian内标注？

### 补充说明

我不是很确定应该在哪里提问。这里看起来应该是用户的建议。

**Comment by Kenshin** [comment]
> 无法在obsidian中打开内置链接。

一般来说了是 本地快照 设置有问题，细节看 https://www.yuque.com/kenshin/simpread/wq35mh#d9a8f093 也把你相关截图给我看下。

**Comment by Crycrysmile** [comment]
十分感谢！在ob里无法打开内置链接的问题已经解决。
另外请问为什么它现在无法自动同步，我应该怎么做来使得它能够自动同步？

https://github.com/Kenshin/simpread/assets/148421294/d017341b-ea49-4196-8139-6cb26b0e7ea3

**Comment by Kenshin** [comment]
> 请问如果我想删除一篇应该怎么办呢？

鼠标移到任意条目

<img width="895" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bfcedfb0-9c39-4b06-937a-06bde4f97eb8">

> 在阅读界面改正标题名后，它会生成两个文件，怎样才能让它只生成一个呢？

同步助手端 → 导出，看下图

<img width="661" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a62bd9f5-7950-4c76-8c8f-3d34385e75c5">
