### ISSUE TITLE
配置好 Cloudinary 图床之后导入失败

### ISSUE THREAD

**Issue by dkpress** [Kenshin/simpread#6018]
### 描述这个错误

已经配置好了 Cloudinary 图床，验证没问题，选择“一键导入全文到 Notion”之后，Notion 里的文章内容只有一句 “undefined”

### 复现步骤

1、进入文章的阅读模式
2、右下角“更多” - “动作”
3、选择“一键导入全文到 Notion”

### 操作系统

Windows 10

### 浏览器

Chrome

### 发生问题的网址

https://sspai.com/prime/story/free-markdown-editor-2023

**Comment by Kenshin** [comment]
我测试了下是没问题的，我不确定是否是因为付费文章的问题，所以试试在 https://sspai.com/post/69972 测试。

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 升级到 1.2.0 

### 重点更新：导入到 Cloudinary 时不经过简悦自己的图片服务器

旧版 1.2.0（以上）会通过简悦的自己的服务器，优点是不需要耗费用户的设备性能；缺点是当为内网图片时无法使用；

新版 1.2.0（含），不经过简悦自己的图片服务器，解决了内网图片或某些有防盗链的图片无法上传的问题。

如：

1. 近期少数派更新了图片规则，导致无法使用旧方案上传，但版方案可以正常将少数派的图片上传到 Cloudinary

    <img width="1023" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8273730d-2cb5-45e9-9170-7fe32f800f03">

2. 内网图片无法使用此功能的问题

### 其它更新

`Fix` 导入图片如果是 `http:` 形式在 Notion 无法显示的问题

***

有任何问题请在汇总页面讨论 https://github.com/Kenshin/simpread/issues/5917

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
