### ISSUE TITLE
希望能增加配置文件导出到webDAV

### ISSUE THREAD

**Issue by kim114** [Kenshin/simpread#602]
`坚果`和`Dropbox`都有能将配置文件一键导入到`webDAV`不是更好

**Comment by Kenshin** [comment]
嗨

WebDAV 已经支持了 详细请看 http://ksria.com/simpread/docs/#/WebDAV 坚果云就是这个方案。

Dropbox 已经原生支持了，所以没必要再上 WebDAV 了。

PS：没有问题的话，可以关闭此 issues 了~
