### ISSUE TITLE
[Question] 字体渲染脚本屏蔽简悦的哪些元素可以显示真正地效果

### ISSUE THREAD

**Issue by harisonkhlil** [Kenshin/simpread#6022]
### 请描述你的建议或任何内容

用的这个[脚本](https://greasyfork.org/en/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC#guide)，和简悦的脚本有显示上的冲突，不过此脚本可以排除不想渲染的元素。

### 补充说明

简悦和字体渲染都可以用啦

**Comment by Kenshin** [comment]
简悦可以完美支持字体渲染，细节 https://github.com/Kenshin/simpread/discussions/4465 

所以我不清楚你的具体问题是什么…

**Comment by harisonkhlil** [comment]
可能我的意思不够明确，我使用这个字体渲染脚本，用来调整全局思源黑体，以及某些网站的自定义字体，但是字体渲染的优先级比简悦优先级高，简悦的自定义不生效。然而，字体渲染脚本支持排除元素，所以我想要排除简悦渲染的元素。

**Comment by Kenshin** [comment]
> 字体渲染的优先级比简悦优先级高，简悦的自定义不生效

确实如你所说。

> 字体渲染脚本支持排除元素，所以我想要排除简悦渲染的元素。

具体要排除什么，或者你需要什么效果，可以直接说。

**Comment by harisonkhlil** [comment]
正文，标题，code block

**Comment by Kenshin** [comment]
> 正文，标题，code block

这些希望使用简悦的样式？正常也可以，但有些麻烦，需要自定义样式解决。

PS：其实你的需求有点奇怪，字体渲染其实效果比简悦更好，覆盖面也更广，所以当使用这个脚本后，完全可以替代简悦。

否则希望在进入阅读模式后，直接使用简悦的样式，这样就不需要安装这个脚本了，这个脚本有个排除列表功能。

**Comment by harisonkhlil** [comment]
这么说吧，有些字体适合用来阅读，有些字体只适合浏览。
字体渲染全局是思源黑体，但是在我想要仔细评读的文章显示效果并不好，所以通过简悦的自定义来自定义我想要的字体。
虽然可以把这个文章的网站给排除，但是总不能每次打开一个想要阅读的网站都要把这个网站的排除吧。

**Comment by Kenshin** [comment]
明天告诉你解决方案，但不一样能 100% 完美。
