### ISSUE TITLE
每次选中较长语句都会卡死（个例）

### ISSUE THREAD

**Issue by innnnel** [Kenshin/simpread#6025]
### 描述这个错误

如果只选中文字似乎多一点也无妨，但是如果图片和文字一起选中的话稍微长一点就会卡住

### 复现步骤

比如选中从
小标题“4.varchar 与 char 的区别？”到“日常的设计，对于长度相对固定的字符串，可以使用 char，对于长度不确定的，使用 varchar 更合适一些。”
这一整段时，百分百卡住，整个页面无响应

### 操作系统

Windows11

### 浏览器

版本 118.0.2088.61 (正式版本) (64 位)

### 发生问题的网址

https://javabetter.cn/sidebar/sanfene/mysql.html#_66-mysql-%E6%95%B0%E6%8D%AE%E5%BA%93-cpu-%E9%A3%99%E5%8D%87%E7%9A%84%E8%AF%9D-%E8%A6%81%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%E5%91%A2

**Comment by Kenshin** [comment]
emmm 确是在特殊布局情况下会出现，但基本上为个例。

其他页面有这样的问题吗？

**Comment by Kenshin** [comment]
我测试了下，确实有点问题，但不要标注图片，仅标注文本段落就没问题

<img width="658" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/023940f3-824d-474d-b711-515568f0c5c2">
