### ISSUE TITLE
导出为 md+assets 失败，js 报错

### ISSUE THREAD

**Issue by shizhx** [Kenshin/simpread#6027]
### 描述这个错误

按照 https://github.com/Kenshin/simpread/discussions/4041 的步骤配置之后，点击 “导出 md+assets”，页面没有反应，F12 查看 console 发现有 js 报错。

### 复现步骤

1. F12 打开开发者工具
2. 点击 “导出 md+assets”

![image](https://github.com/Kenshin/simpread/assets/7520007/c5a440ab-c630-421b-8bbd-9a8f6f4a76aa)

### 操作系统

Linux

### 浏览器

Chrome 118.0.5993.70

### 发生问题的网址

https://thermalcircle.de/doku.php?id=blog:linux:nftables_packet_flow_netfilter_hooks_detail

**Comment by Kenshin** [comment]
其他页面有问题吗？如果也有问题的话，看下你的相关配置。

**Comment by shizhx** [comment]
@Kenshin 其他页面也有问题，插件配置如下：
```json
{
  "plugstorge": {
    "BvjrJA6eh5": {
      "absolute": false,
      "assets": "3",
      "custom": "",
      "idxtitle": true,
      "image": "http",
      "metadata": "---\nurl: {{url}}\ntitle: {{title}}\ndate: {{date}}\ntag: {{tags}}\nsummary: {{desc}}\n---",
      "path": "/home/user/Documents/simpleread/output/test/",
      "yaml": true
    }
  }
}
```

**Comment by shizhx** [comment]
刚刚试了一下 base64 模式，发现可以了，不知道是不是根因所在，如果是的话可以考虑加个弹框提示。

**Comment by Kenshin** [comment]
```
"path": "/home/user/Documents/simpleread/output/test/",
```

这个目录地址是真实存在的吗？

***

> 页面没有反应，F12 查看 console 发现有 js 报错。

JS 报错跟这个问题无关，也不用理这个报错。

***

因为你是 Linux 环境，因为你提到了 `base64` 方案是正确的，我不确定是否是这个系统的缘故（比如权限等问题）。

如果不使用  `base64` 的话，同步助手会得到这个图片的 URL 地址，然后加载并在同步助手端转换再保存。

某些图片有严格的防盗链限制，所以传 URL 会失败，因此才有的 `base64` 方案，所以理论上你应该是这个问题。

> 其他页面也有问题

但这个情况跟预期不符，所以确认下 https://sspai.com/post/69972 非 `base64` 方案是否正确？

> https://github.com/Kenshin/simpread/issues/6027#issuecomment-1776420993

这是预期情况（不算是问题（，你的页面中图片嵌套链接

<img width="773" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/661e20ca-4562-45f7-84f5-bfeb3796295a">

**Comment by shizhx** [comment]
@Kenshin 
1. 路径是存在的
2. sspai 这个页面一样存在问题
3. 同步助手的 7026 端口是处于监听状态的

经过 tcpdump 抓包，可以确认在点击“导出 md+assets“按钮时 7026 端口并没有数据。
但是点击其他几种导出时是能抓到数据包的，因此应该可以确认是浏览器端没有发请求给同步助手。

**Comment by Kenshin** [comment]
```
"assets": "3",
```

改为下图

<img width="521" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5993ad62-ff00-44cb-8b5b-52f872f526d6">

然后使用 https://github.com/Kenshin/simpread/issues/6028#issuecomment-1776638504 提到的方式，即使用同步助手设置路径，而不是插件端。

PS：我看你的动手能力很强，所以修改方案直接看这个链接。

**Comment by shizhx** [comment]
> ```
> "assets": "3",
> ```
> 
> 改为下图
> 
> <img alt="image" width="521" src="https://user-images.githubusercontent.com/81074/277603536-5993ad62-ff00-44cb-8b5b-52f872f526d6.png">
> 然后使用 [#6028 (comment)](https://github.com/Kenshin/simpread/issues/6028#issuecomment-1776638504) 提到的方式，即使用同步助手设置路径，而不是插件端。
> 
> PS：我看你的动手能力很强，所以修改方案直接看这个链接。

按照这个设置还是没有用，**tcpdump 没有抓到包**，说明插件端异常了，因此我怀疑还是 js 报错的原因。

**Comment by shizhx** [comment]
@Kenshin 不知查到什么原因没有？好像没看到这个插件的源码，如果没有混淆的话我倒可以帮忙除一下虫

**Comment by Kenshin** [comment]
邮件发了吗？😂

PS：发完邮件应该告诉我一声，但我忘记告诉你了（或者以为你知道  🌚

**Comment by shizhx** [comment]
@Kenshin 邮件前两天已发 :sweat_smile:

**Comment by Kenshin** [comment]
okay 明天确认 😂

**Comment by Kenshin** [comment]
嗨，我使用你提供的配置文件

1. 没有发现 https://github.com/Kenshin/simpread/issues/6027#issue-1957176480 截图中的报错。

2. 同样的配置文件可以正常导出

     <img width="318" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/889b5e7f-dabf-4d70-a21b-916429168cb8">


所以，同样的配置文件建议在 Win 和 Mac 上测试，看看是不是 Linux 的问题。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
