### ISSUE TITLE
win和mac下ob导入全文的路径问题

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#6028]
### 描述这个错误

win的导入ob全文的目录设置是D:\文档\Obsidian\xxxx\SimpOutput，mac的目录是/Users/Hope/Documents/Obsidian/xxxx/SimpOutput，但是配置文件会同步覆盖，最终的mac和win的路径都一样，必然有一端无法正常导入。
![image](https://github.com/Kenshin/simpread/assets/70339118/0b5bde35-d6eb-4d25-ab37-14cfd089a00b)

### 复现步骤

设置导入到ob-导入全文

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s/3W_AmUeQ6zsy0Zhb18dBQQ

**Comment by Kenshin** [comment]
确实是个问题，但你可以分别在 Mac 和 Win 的同步助手设置（下图所示），然后你截图所示的位置留空。

<img width="670" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5354555d-b86a-4797-8ea0-995b683fd5f3">

**Comment by HopeLHP** [comment]
`{"extension":"external", "path":"D:/文档/Obsidian/HopeOB/SimpOutput"}`
同步助手填这个对吗，全文导不进去

**Comment by HopeLHP** [comment]
可以，解决了

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 Issues 了。
