### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by woshituzhi1** [Kenshin/simpread#603]
OneNote授权失败
![TIM图片20191029191222](https://user-images.githubusercontent.com/12286922/67762354-3563c680-fa80-11e9-84ab-1ef0db882623.png)

**Comment by Kenshin** [comment]
谢谢反馈。

确保能访问 OneNote 并请告知你的环境，我明天试试。😀

**Comment by woshituzhi1** [comment]
本机测试Firefox可以正常授权,Chrome不行,安装插件也会失败
Chrome版本78

**Comment by Kenshin** [comment]
👌🏻 我明天试试。

**Comment by Kenshin** [comment]
嗨，刚测试了下，Onenote 可以正常授权。

请问你的 简悦是什么版本？

**Comment by gzy0916** [comment]
![image](https://user-images.githubusercontent.com/30331101/68542079-67abe700-03e3-11ea-894b-1b132c888afa.png)
![image](https://user-images.githubusercontent.com/30331101/68542085-74c8d600-03e3-11ea-8654-bc3b77016d21.png)
![image](https://user-images.githubusercontent.com/30331101/68542095-92963b00-03e3-11ea-94c1-621e21d0f6eb.png)
简阅1.1.3

同样onenote授权失败

**Comment by woshituzhi1** [comment]
1.13

**Comment by Kenshin** [comment]
@woshituzhi1 @gzy0916 

能正常可以访问外网吗？控制台显示什么错误？

**Comment by woshituzhi1** [comment]
可以正常访问外网,控制台报的跨域问题

**Comment by Kenshin** [comment]
@woshituzhi1 

真是奇怪... 我也是同样的 Chrome 版本，可以授权成功。

另外，你是否可以试试

- 其它 Chromium 的浏览器？

- 直接打开选项页 → 授权 的方式试试？

**Comment by Vergil-x** [comment]
自己的笔记本授权没问题，公司的电脑不行，可能还是和代理有关的问题把

**Comment by Kenshin** [comment]
@Vergil-x 

按道理不应该，Onenote 应该可以正常访问。

你是卡在哪个环节？进入到 Onenote 官网了吗？
