### ISSUE TITLE
在升级到1.4.X之后导入功能失效

### ISSUE THREAD

**Issue by Inna0915** [Kenshin/simpread#6031]
### 描述这个错误

# obsidian 信息
Obisidian 版本 v1.4.16
installrer 版本 v1.4.13

# 插件配置
![image](https://github.com/Kenshin/simpread/assets/102937421/7d42cc47-d9af-439e-bfe4-ba057a24ab53)

# chrome插件配置
![image](https://github.com/Kenshin/simpread/assets/102937421/0b84868d-dfc8-440c-b127-df2cd5e6dbcd)
![image](https://github.com/Kenshin/simpread/assets/102937421/7f93f2d3-57d8-4246-811c-f41dc610665e)

# 报错内容
![image](https://github.com/Kenshin/simpread/assets/102937421/93fa2490-abd3-45d0-92c4-7dc070055972)

### 复现步骤

1. 更新到1.4.X之后
2. 多台PC更新后都失效

### 操作系统

Windows

### 浏览器

chrome 118.0.5993.89（正式版本） （64 位）

### 发生问题的网址

https://github.com/Kenshin/simpread/issues/5531  任意网站均失效

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/5601

PS：你是有多久没用 Obsidian 了？😂

**Comment by Inna0915** [comment]
> 解决方案 #5601
> 
> PS：你是有多久没用 Obsidian 了？😂

持续在用的，只是在近期更新之后才失效，我去试试这个解决方案先

**Comment by Kenshin** [comment]
okay 一般都可以 100% 解决。
