### ISSUE TITLE
坚果云文件夹请教

### ISSUE THREAD

**Issue by raincare** [Kenshin/simpread#6032]
### 请描述你的建议或任何内容

请教K大，在开通 开放平台之后，发现坚果云的根目录出现一个simpread文件夹，不知道这个文件夹有什么用途，里面只有一个名为md的子文件夹（空的），所以很想删除，现在不确定是否是设置开放平台所致，也不知道该文件夹是否有用，请教一下K大。如果无关紧要，想删除掉，个人有点视觉完美主义。

### 补充说明

![image](https://github.com/Kenshin/simpread/assets/132796596/5899c734-dc15-493a-8d29-75cb27c13562)

**Comment by Kenshin** [comment]
嗨

`SimpRead` 不可以被删除，但里面的 `md` 可以删除，这个文件夹也不是开放平台生成的。

PS：如果没有 API 诉求的话，不建议使用这个功能。😄

**Comment by raincare** [comment]
> 嗨
> 
> `SimpRead` 不可以被删除，但里面的 `md` 可以删除，这个文件夹也不是开放平台生成的。
> 
> PS：如果没有 API 诉求的话，不建议使用这个功能。😄

收到，没有API诉求，如何根除simpread这个文件夹，手动删除会不会后续又产生出来

**Comment by Kenshin** [comment]
> 如何根除simpread这个文件夹，手动删除会不会后续又产生出来

`SimpRead` 针对简悦来说，在坚果云中是个很重要的文件夹，但如果你不使用坚果云的话，自然就不需要这个文件夹...

无论是 `SimpRead`  还是刚才提到的 `md` 都是用户操作后产生的，而这些操作都是跟坚果云有关系，或者说你本地的坚果云同步目录。

所以你不使用坚果云同步方案的话，自然不需要这些文件夹。

你的问题类似与：我主动买个锁，然后配套得到了一把钥匙，但你不需要这个钥匙也不觉得这个锁有必要，所以...你不应该买这把锁。

😂

**Comment by raincare** [comment]
收到，K大是这样的，我使用坚果云同步简悦，简悦同步文件夹设在坚果云根目录的“我的坚果云”的子文件夹simpread里面，之前同步都是正常使用的（配置文件和导出文件都是在这里），后面不知道是设置开放中心，还是稍后读什么的设置，根文件夹又出现了一个simpread文件夹，感觉重复了，所以我问下，既然有同步文件夹，是不是可以删除根目录的这个，主要怕删掉影响什么功能

**Comment by Kenshin** [comment]
> 我使用坚果云同步简悦，简悦同步文件夹设在坚果云根目录的“我的坚果云”的子文件夹simpread里面，之前同步都是正常使用的（配置文件和导出文件都是在这里）

不用纠结这里。

使用 API 的话，就必须是你最开始截图的方式，但反过来不使用 API 的话，简悦是不限制文件夹层级的，什么网盘都可以。

所以，你最开始的时候是什么方式就使用什么方式，然后因为不使用 API 删除第一个截图对应的文件夹就行了。

***

PS：其实 SimpRead 文件夹理论上是应该跟 **我的坚果云** 同级才对（也就是是你第一个图的结构），这个结构对应了下图

<img width="661" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/913748c0-1ed7-4d4a-8bc3-744e6a4c2a8b">

但你仍可以按照你自己的喜好设置文件夹位置。

**Comment by raincare** [comment]
收到，懂了，谢谢K大指点

**Comment by Kenshin** [comment]
哈，小事情。

对同步感兴趣的话，可以看下 https://www.yuque.com/kenshin/simpread/ebwu7g 里面的详细说明。
