### ISSUE TITLE
关于 zotero 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6033]
用这个插件，复制到原文 剪藏到zotero，会出现排版效果不好

_Originally posted by @karaner in https://github.com/Kenshin/simpread/discussions/5927#discussioncomment-7376607_

**Comment by Kenshin** [comment]
@karaner

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

请提供具体 URL

**Comment by karaner** [comment]
https://www.jianshu.com/p/1949c96da4c6
用的zotero 7 ，复制到原文，字体会变大很多

**Comment by Kenshin** [comment]
这是我的效果

<img width="1389" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/70ea1c74-e362-4487-ac3c-350a623710bd">

如果你觉得有问题，试试更换不同的主题。

**Comment by karaner** [comment]
![image](https://github.com/Kenshin/simpread/assets/5621973/26b8cde4-ed91-4e6c-bf1d-acdde1b91c8b)
上面是我点击“复制到原文”的效果，字体大了好多。
你说的换主题是指换简悦的阅读样式吗？

**Comment by Kenshin** [comment]
这是我导入到 zotero 的效果（不是你这个链接，我暂时没法测试，zotero 7 毕竟不太稳定。

<img width="1455" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b8bf7ec5-9827-4fee-a55f-ee2bf79b1569">

你可以缩小它。

> 换主题是指换简悦的阅读样式吗？

简悦的主题

PS：建议你试试不同的网页 e.g.  https://sspai.com/post/69972
