### ISSUE TITLE
msn新闻

### ISSUE THREAD

**Issue by Hypnos3420** [Kenshin/simpread#6037]
### 需要适配的新站

https://www.msn.cn/zh-cn/news

### 有需要请描述这个站的性质

win系统自带浏览的起始页

**Comment by Kenshin** [comment]
okay 收到，谢谢提交，适配后会通知你~

**Comment by Kenshin** [comment]
嗨，MSN 这个站点已适配完毕。

#### 如何更新

https://github.com/Kenshin/simpread/issues/6541#issuecomment-2156314697

#### 效果如下

<img width="1806" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fad680a2-6978-4418-b403-0861690e74f0">

***

我关闭这个 Issues，有任何问题请在 https://github.com/Kenshin/simpread/issues/6541 讨论
