### ISSUE TITLE
政府网站：温州市市场监督管理局

### ISSUE THREAD

**Issue by DreamerDK** [Kenshin/simpread#6038]
### 请描述你的建议或任何内容

http://wzmsa.wenzhou.gov.cn/art/2023/5/26/art_1264156_58923621.html

### 补充说明

不知道为什么，手动框选也无法适配。

**Comment by Kenshin** [comment]
试试 https://github.com/Kenshin/simpread/discussions/3340 里面的手动模式。

**Comment by DreamerDK** [comment]
> 试试 #3340 里面的手动模式。

就是使用了手动模式，但框选内容后，阅读里却没有正文。

聚焦模式似乎可以使用。

**Comment by Kenshin** [comment]
使用下面的方式就行，之前给的链接也有提到这种方案。

<img width="1052" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/60e7d8d4-5310-4e73-9318-046aac0d1816">
