### ISSUE TITLE
全文翻译ChatGPT web失效

### ISSUE THREAD

**Issue by rader124124** [Kenshin/simpread#6039]
### 描述这个错误

全文翻译翻译引擎ChatGPT(web)失效

### 复现步骤

翻译没有效果，点击「测试API」卡在「正在测试，请稍等」

### 操作系统

macOS

### 浏览器

Chrome 118.0.5993.117

### 发生问题的网址

所有网站

**Comment by Kenshin** [comment]
这个功能没问题的，一般来说留意下图所示

![486b4a728f88b846e98d5abe4b754d37](https://github.com/Kenshin/simpread/assets/81074/b0f7a4af-7426-4ea0-92ad-fbd1ee90671f)

或者截图给我看下你的配置。
