### ISSUE TITLE
关于全文翻译的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6040]
你好，我安装之后一开始都是正常使用的，但这几天不知道为什么不能使用了，1进入简悦阅读模式，选择段落后的翻译按钮，然后转圈不能成功2进入全文翻译选项，点击测试api按钮，显示正在测试，请稍后，然后就没有反应了

_Originally posted by @threeyears121 in https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-7401948_

**Comment by Kenshin** [comment]
@threeyears121

我新建了一个 Issues 讨论这个问题。

***

重新登陆你的 Web ChatGPT 再试试，我昨天使用时还没有任何问题。

也可能是 ChatGPT 结构变了，我明天再测试下。

**Comment by threeyears121** [comment]
刚刚测试了一下，重新把全文翻译和chatgpt插件安装了，测试api还是通过不了，把翻译引擎切换为百度，设置好token，可以正常通过测试，也能正常使用，在浏览器中登录使用gpt都没有问题

**Comment by Kenshin** [comment]
1. ChatGPT 与 百度没关系，百度测试通过不代表 ChatGPT 也能通过。

2. 我测试了下，确实有点问题，可能是 ChatGPT 又改动了 API 造成的，正在调查。

**Comment by Kenshin** [comment]
我这边测试遇到下面的问题

> Our systems have detected unusual activity from your system. Please try again later.

我不确定是我的 ID 有问题，还是 API 有问题，也可能是 ChatGPT （账户类）日常抽风

**Comment by threeyears121** [comment]
那只能等等，看看会不会好

**Comment by Kenshin** [comment]
是的，先观察几天。

如果你没有 ChatGPT Plus 的话，其实这个功能并没有那么好用，因为免费账户调用会比较慢。

**Comment by rader124124** [comment]
> 是的，先观察几天。
> 
> 如果你没有 ChatGPT Plus 的话，其实这个功能并没有那么好用，因为免费账户调用会比较慢。

是chatgpt调整了什么东西，前几天其他chatgpt插件都出现了问题，现在很多开发者已经适配好了。

**Comment by Kenshin** [comment]
@rader124124 

谢谢反馈。

你可以随便告诉我一个可以使用 ChatGPT Web 版的扩展（之前不好使，升级后又好使了），我瞧瞧。

**Comment by rader124124** [comment]
> @rader124124
> 
> 谢谢反馈。
> 
> 你可以随便告诉我一个可以使用 ChatGPT Web 版的扩展（之前不好使，升级后又好使了），我瞧瞧。

https://github.com/josStorer/chatGPTBox/releases

**Comment by Kenshin** [comment]
@rader124124 

嗨，你确定这个好使吗？我使用了 ChatGPT Web 默认仍无法使用。

**Comment by rader124124** [comment]
> @rader124124
> 
> 嗨，你确定这个好使吗？我使用了 ChatGPT Web 默认仍无法使用。

应该是Github更新了，Chrome还没更新。可以试试这个https://chromewebstore.google.com/detail/chatgpt-%E7%B6%B2%E7%AB%99%E5%92%8C-youtube-%E5%BD%B1%E7%89%87%E6%91%98%E8%A6%81/cbgecfllfhmmnknmamkejadjmnmpfjmp

**Comment by Kenshin** [comment]
@rader124124 

感谢，这个问题已经解决了，稍晚（或明天）发布 👍

**Comment by Kenshin** [comment]
嗨，各位。

这个 Bug 已修复，需要重新覆盖旧文件，细节 [请看这里](https://github.com/Kenshin/simpread-chatgpt-helper#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85)。

我关闭这个 Issues 了

谢谢 @rader124124 的提示。👍

**Comment by GUaaaGUaaa** [comment]
你好，今天我安装全文翻译的时候也显示调用错误Our systems have detected unusual activity from your system. Please 
try again later.
插件确定已经安装了最新版了

**Comment by Kenshin** [comment]
@GUaaaGUaaa 

这个错误是在什么时候出现的？你使用了什么翻译方式 😂

建议详细描述，或者录屏给我。

**Comment by GUaaaGUaaa** [comment]
https://github.com/Kenshin/simpread/assets/104227764/15ae59f0-a027-4b8c-81c4-1e696205f842
对不起脑子抽了没写清楚，这样能看清楚吗？
是用ChatGPT(web)翻译，在测试API的时候出现的

**Comment by Kenshin** [comment]
@GUaaaGUaaa 

okay 可能是 ChatGPT Web 又抽风了 😂 稍晚再试试，我明天测试下。
