### ISSUE TITLE
新站适配：MSN

### ISSUE THREAD

**Issue by Lantern51816** [Kenshin/simpread#6041]
### 需要适配的新站

https://chng.it/BHfS8CLqPC

### 有需要请描述这个站的性质

这似乎是edge切换地区后的首页内容的详情网站

**Comment by Kenshin** [comment]
嗨

我可以正常进入阅读模式，如果你觉得进入效果不好的话，可以试试下图所示的方式

**Comment by Lantern51816** [comment]
> 嗨
> 
> 我可以正常进入阅读模式，如果你觉得进入效果不好的话，可以试试下图所示的方式
> 
> <img alt="image" width="917" src="https://user-images.githubusercontent.com/81074/278858491-adb7f1e8-e7cf-440b-943e-d00f0c8818c9.png">

抱歉，好像是和剪贴板最新剪贴的一个网站搞混了。大大可以试试这个吗？
https://www.msn.com/en-us/movies/news/the-most-popular-book-of-every-year-since-1920/ss-AA1iEYiX?ocid=msedgdhp&pc=LCTS&cvid=a61866bd54734982a5a390381691dbe7&ei=20

**Comment by Kenshin** [comment]
okay 我明天试试。

你同样可以使用我提到的方式

**Comment by Kenshin** [comment]
收到，会适配这个站的

关联 https://github.com/Kenshin/simpread/issues/6037

**Comment by Kenshin** [comment]
嗨，MSN 这个站点已适配完毕。

#### 如何更新

https://github.com/Kenshin/simpread/issues/6541#issuecomment-2156314697

#### 效果如下

<img width="1806" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fad680a2-6978-4418-b403-0861690e74f0">

***

我关闭这个 Issues，有任何问题请在 https://github.com/Kenshin/simpread/issues/6541 讨论
