### ISSUE TITLE
关于简悦的购买形式疑问

### ISSUE THREAD

**Issue by huangyfGG** [Kenshin/simpread#6043]
### 描述这个错误

请问，目前是有简悦2.0高级账户，后续版本升级到3.0的话，还要再订阅类似3.0高级账户吗？
或者以后会不会有类似2.0 SVIP账户等更高级的订阅类型？

### 复现步骤

如问题描述

### 操作系统

全平台

### 浏览器

全平台

### 发生问题的网址

全平台

**Comment by Kenshin** [comment]
没有，看下 https://www.yuque.com/kenshin/simpread/ggokp5 里面的说明。

简悦是扩展端买断制，不是订阅制，也不是大版本升级制。
