### ISSUE TITLE
在mac下，obsidian不能自动同步已标注的文件，但是点manual sync可以同步，是什么原因

### ISSUE THREAD

**Issue by skysea82410** [Kenshin/simpread#6046]
### 描述这个错误

在mac下，obsidian不能自动同步已标注的文件，但是点manual sync可以同步，同步助手已经配置并且是最新版。

### 复现步骤

1. 在网页上进行标注
2. 同步助手自动同步标注到output文件夹
3. obsidian文件没有变化，不能自动同步
4. 在obsidian插件中点击manual sync可以同步过来

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

https://www.cnblogs.com/

**Comment by skysea82410** [comment]
我对了一下你上面说的几条，都没有问题，可以同步还是不行，这是我的目录文件，我编辑的是编号3的文件
<img width="1481" alt="image" src="https://github.com/Kenshin/simpread/assets/6860494/eff54c55-39a4-4a58-a3c2-9a779b779537">

**Comment by Kenshin** [comment]
你最后一个截图有两个目录地址：

- 右侧 → 是在 output 文件夹中，一般来说这是简悦默认的本地快照目录，除此之外，还有一些你自己生成的文件。

- 左侧 → Obsidain 的库文件夹。

总之，还是因为你的目录设置有误造成的。

你可以试试将：**你需要将左侧的 Obsidian 目录设置到右侧**，这种方式其实不是最好的方案。

另外，在开启 Obsidian 的前提下，试试访问 http://localhost:7027 看看是什么内容？
