### ISSUE TITLE
同步助手打开稍后读显示标注有问题

### ISSUE THREAD

**Issue by skysea82410** [Kenshin/simpread#6048]
### 描述这个错误

同样一篇文章用网页端打开标注显示正常，如下图：
<img width="1349" alt="image" src="https://github.com/Kenshin/simpread/assets/6860494/8820592f-b38d-40a3-bf35-6cf4e77301d4">

用同步助手内置的稍后读打开，显示异常，如下图：
<img width="1674" alt="image" src="https://github.com/Kenshin/simpread/assets/6860494/3232f0c9-8c75-43a7-9305-5c76d97744b6">

### 复现步骤

1. 用网页打开标注过的文章，进入阅读模式
2. 同样的文章用内置的稍后读软件打开

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

https://www.cnblogs.com/

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/3164

PS：建议使用更方便的 [稍后读 · 极速版](https://github.com/Kenshin/simpread/discussions/3864) 方案。
