### ISSUE TITLE
稍后读空白

### ISSUE THREAD

**Issue by Leslie1718** [Kenshin/simpread#6049]
### 描述这个错误

可以进入阅读模式，不能标注，显示“已经控制栏面板，所以无法使用此功能。”
网页可以加入稍后读，但是稍后读是空白的

### 复现步骤

![J953YU8% G(`MHSY1%3 168](https://github.com/Kenshin/simpread/assets/98525858/e7a9d965-bc66-4558-bcce-8cf9d051489e)
![C@MD2YGQUY$3U6RT@WR}YTW](https://github.com/Kenshin/simpread/assets/98525858/4693cb89-0237-4876-bcf4-43c8223b4efc)

### 操作系统

windows10

### 浏览器

edge

### 发生问题的网址

https://www.zhihu.com/question/23482738

**Comment by Kenshin** [comment]
是不是使用了同步助手的自动同步？如果是的话，使用 http://localhost:7026/database/fixed 修复你的配置文件（数据文件）。

修复后根据提示重启浏览器。

**Comment by Leslie1718** [comment]
有同步，但用的是最简单的ob配置库，没有使用同步助手

**Comment by Kenshin** [comment]
> 有同步，但用的是最简单的ob配置库

你这两句话是相悖的... 

你的上一个 Issues 我感觉是使用了 Obsidian 高级版方案，而你又说是 **ob配置库**...

所以，你到底是什么方式？

**Comment by Leslie1718** [comment]
我使用的是最简单的ob同步配置库，里面没有同步助手，还能用这个网站修复配置文件吗？
![image](https://github.com/Kenshin/simpread/assets/98525858/7ab1cc82-f791-43ca-b316-9483c5df4e6f)

**Comment by Kenshin** [comment]
> 我使用的是最简单的ob同步配置库，里面没有同步助手，还能用这个网站修复配置文件吗？

暂时不能，但会考虑让这个服务上线。

你可以把出错的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6049

然后在这里通知我，我明天帮你手动修改。

PS：如果没有特别多的数据，可以考虑重置它。

**Comment by Leslie1718** [comment]
发好啦🌹
![image](https://github.com/Kenshin/simpread/assets/98525858/f2a4bb37-7098-40a3-8829-5e0b5cd485a2)

**Comment by Kenshin** [comment]
okay 明天给你。

**Comment by Kenshin** [comment]
> 疑问1：同步的ob库只能和自己的知识体系库分开使用吗？

可以的，完全没问题，只要留意好路径就行。

> 在分开使用的情况下，我把同步的ob库里面的文件复制一些去自己的知识体系库。

我不太理解，理论上不会有任何冲突，你之前说过，你使用的 轻量级方案，但建议最好详细告诉我你使用的方式，一般来说共有三种方案 https://www.yuque.com/kenshin/simpread/psugef

> 重置数据是不是意味着同步ob库里面的文件会丢失，自己知识体系库里面的文件不会丢失，也能修改（添加大纲标题或修改文本）？

重置数据仅仅针对简悦的扩展端，并不会对 Obsidian 库里面的东西做任何改动。
