### ISSUE TITLE
阅读csdn博客时代码部分都显示了两次，但是不会显示行号

### ISSUE THREAD

**Issue by xyxlkb** [Kenshin/simpread#605]
如题，阅读csdn博客时代码部分都显示了两次，但是不会显示行号
但是导出成md格式的时候代码部分是好的，也不会显示两次

**Comment by Kenshin** [comment]
谢谢反馈，这是一个 Bug 详细可以看 https://github.com/Kenshin/simpread/issues/570 的说明。

修复后，我会在这里通知到你~

**Comment by muyanbiao** [comment]
不只是CSDN，很多网站的代码都会出现这个问题，一份代码出现两次

**Comment by Kenshin** [comment]
@muyanbiao 

方便的话，请给出个链接。

**Comment by Kenshin** [comment]
嗨，这几天准备集中修复 代码高亮 的问题。

不过，很奇怪的是，我测试了几个 CSDN 的页面均未发生问题，请问能否告知具体的 URL 

***

另外，请确保安装 [代码高亮插件](https://github.com/Kenshin/simpread/issues/500)

**Comment by muyanbiao** [comment]
CSDN的问题修复了，但发现一个新问题：用下面这个链接https://blog.cnbluebox.com/blog/2015/05/07/architecture-ios-1/，开启阅读模式后，代码段显示正常，但退出阅读模式之后，导致页面本来的代码段显示不正常，行号和代码分离。

**Comment by Kenshin** [comment]
搞定就好~ 

这应该这个插件里面的 `代码高亮` 造成的，目前应该没什么解决方案，只能手动刷新。

不过，我会研究下，看看能否有解决方案...

***

PS：我增加了一个 [常见问题汇总](https://github.com/Kenshin/simpread/issues/618) 一般性的问题都能在这里解决掉。

**Comment by xyxlkb** [comment]
代码高亮的问题修复了，谢谢你！
不过还有一个小问题，就是原网页上代码左边是有行号标志的，用了阅读模式之后代码就没有行号了。

**Comment by Kenshin** [comment]
@xyxlkb 

这应该是 `代码高亮` 插件中的配置的，我研究下这个库，不知道是否可以加上。

***

PS：这个 issues 里面竟然有两个用户，刚才突然都给我回复，我以为 Github 抽风了...

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

此问题已经被解决了

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
