### ISSUE TITLE
无法导入到本地以markdown版本

### ISSUE THREAD

**Issue by liu-junqin** [Kenshin/simpread#6050]
### 描述这个错误

https://www.sohu.com/a/418518445_100293597
无法导入到本地以markdown版本

### 复现步骤

点击导出为markdown 显示配置错误

### 操作系统

windows

### 浏览器

chrome 最新版

### 发生问题的网址

https://www.sohu.com/a/418518445_100293597

**Comment by Kenshin** [comment]
嗨

这个问题是因为这个页面的标题含有特殊字符造成的，受影响的仅仅只是 Windows

你可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 删除这个标题而后重新添加，即可解决。
