### ISSUE TITLE
小书签问题

### ISSUE THREAD

**Issue by zlxuan** [Kenshin/simpread#6051]
### 描述这个错误

看了很多帮助文档还是没配置好小书签功能，点击一键收藏是空白的，请教一下是配置哪里有问题？
![Snipaste_2023-11-02_13-06-21](https://github.com/Kenshin/simpread/assets/58515531/aa54d8a7-2803-4806-bcf5-65210e4ea8e6)
![Snipaste_2023-11-02_13-07-46](https://github.com/Kenshin/simpread/assets/58515531/b28dee6c-7b7b-4c56-9586-7f822512cca6)

### 复现步骤

1. 插件和同步助手都开启了自动同步；
2. 坚果云也同步了文件夹“SimpRead”；
3. 点击一键收藏就是空白。

### 操作系统

windows 11

### 浏览器

Chrome 版本 111.0.5563.147（正式版本） （64 位）

### 发生问题的网址

无

**Comment by Kenshin** [comment]
看下图

<img width="843" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d56f9cfd-0c14-426c-a1dd-e8469bfba4c3">

另外，这个功能需要使用同步助手的自动同步功能才行，还是建议仔细看下教程 https://simpread.pro/docs/#/Bookmarklet

**Comment by zlxuan** [comment]
> 看下图
> 
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/81074/279889444-d56f9cfd-0c14-426c-a1dd-e8469bfba4c3.png">
> 另外，这个功能需要使用同步助手的自动同步功能才行，还是建议仔细看下教程 https://simpread.pro/docs/#/Bookmarklet

感谢回复，搞了半天，终于明白了“将小书签拖拽”的小书签原来就是说的这俩按钮🤦‍♂️
![Snipaste_2023-11-02_22-53-45](https://github.com/Kenshin/simpread/assets/58515531/dd28c421-59c4-43bd-b375-f4d9d2f30bda)

**Comment by Kenshin** [comment]
😄 没关系，小事情~
