### ISSUE TITLE
集思录文章无法显示图片

### ISSUE THREAD

**Issue by szz65** [Kenshin/simpread#6053]
### 描述这个错误

集思录中的文章收藏时无法显示图片

### 复现步骤

集思录中的文章使用简悦阅读和收藏时无法显示图片

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

https://www.jisilu.cn/

**Comment by Kenshin** [comment]
嗨，使用下面的方式

<img width="1065" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f09ae599-c5f0-4c25-b4e7-9316ab6f1441">
