### ISSUE TITLE
导出后的文件名的模板可以不要simread-前缀吗

### ISSUE THREAD

**Issue by danfate** [Kenshin/simpread#6055]
### 请描述你的建议或任何内容

搜了yuque，ksria，没看到相关的文档；高级帐户+不使用同步助手，目前有地方修改吗？

**Comment by Kenshin** [comment]
嗨

导出时如果没有使用同步助手的增强导出，暂时是无法定制导出标题的。

不过，如果你是 Mac 的话，有一些自动化辅助工具可以便向解决，比如 Hazel 等。
