### ISSUE TITLE
导出仅标注模式，选择md格式时输出的文件后缀名为xxx.md@annote

### ISSUE THREAD

**Issue by vinkener** [Kenshin/simpread#6056]
### 描述这个错误

导出仅标注模式，选择md格式时输出的文件后缀名为xxx.md@annote

### 复现步骤

导出仅标注模式，选择md格式时输出的文件后缀名为xxx.md@annote

### 操作系统

windows10

### 浏览器

edge

### 发生问题的网址

https://sspai.com/prime/story/android-hdr-display-issue-explained

**Comment by Kenshin** [comment]
有可能是你的自定义标题错了…

**Comment by Kenshin** [comment]
自定义标题的定制 https://www.yuque.com/kenshin/simpread/wkswh7#phV3U

<img width="1011" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8381f6cb-022f-4033-ab61-a0f4c6518bfb">
