### ISSUE TITLE
生词本加入失败

### ISSUE THREAD

**Issue by hushilibg** [Kenshin/simpread#6057]
### 描述这个错误

就是题目说的一样，甚至更离谱比如说翻译都没了而且在加入生词之后就不翻译了，得重新开一次翻译才能出现、、、、我把那个复现截图发出来

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/100138885/699decd0-12ad-44ce-a4d7-f0bc35f10672)
![image](https://github.com/Kenshin/simpread/assets/100138885/dd1eda1a-4f5e-4acd-8cd7-6d587270a808)
![image](https://github.com/Kenshin/simpread/assets/100138885/780a74d9-b3b8-446e-8d38-43e0dd0cbae3)
（这已经点击了加入生词）
![image](https://github.com/Kenshin/simpread/assets/100138885/34238b11-3ff2-4e78-84d9-4ee91a87fa81)

### 操作系统

win10

### 浏览器

Microsoft Edge

### 发生问题的网址

https://yun.smartisan.com/#/notes

**Comment by Kenshin** [comment]
我测试了下，没有遇到你说的问题

<img width="537" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8195c9b6-9bab-4e95-8ee3-7751545fa15f">

<img width="646" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/499f66b0-2507-48a7-9e2c-63c8e3ad86f4">

**Comment by Kenshin** [comment]
所以，建议录屏描述下你的问题。
