### ISSUE TITLE
Chrome 78 下，特定 URL 无法下载 Markdown 文件

### ISSUE THREAD

**Issue by xhanb** [Kenshin/simpread#606]
访问[这个页面](https://devblogs.microsoft.com/dotnet/continuously-deploy-and-monitor-your-uwp-wpf-and-windows-forms-app-with-app-center/)进入阅读模式后，无法下载diamarkdown,报Not allowed to navigate top frame to data URL这个错

**Comment by Kenshin** [comment]
嗨，你说的是 无法下载 Markdown 吗？

我是可以下载的，如下图

![image](https://user-images.githubusercontent.com/81074/67999711-5bfc4a00-fc98-11e9-9ab1-366dbda11b73.png)

另外，附件是这个页面的 md _注意：为了能上传到这里，我已经改为 txt 格式_

[simpread-Continuously deploy and monitor your UWP, WPF, and Windows Forms app with App Center _ .NET Blog.txt](https://github.com/Kenshin/simpread/files/3796536/simpread-Continuously.deploy.and.monitor.your.UWP.WPF.and.Windows.Forms.app.with.App.Center._.NET.Blog.txt)

**Comment by xhanb** [comment]
我的还是不行。
进入文章后选择阅读模式，然后在【动作】里选择下载没有反应，而且报错。
Chrome为最新版本：
![Snipaste_2019-11-01_11-54-32.png](https://i.loli.net/2019/11/01/tfZc6eATjY24NJP.png)
![test.gif](https://i.loli.net/2019/11/01/3BMubTRqPA9x7Xy.gif)

**Comment by Kenshin** [comment]
emm 这就奇怪了。

不过，我测试的并不是 Chrome 78 （ 虽然跟这个应该没关系...） 我目前在 Win 下，只有换到 Mac 上才能测试 78 版本的情况。

你试着看看其它页面也有这个问题吗？

**Comment by xhanb** [comment]
我的环境就是win10。其他站点试了几个都好使

**Comment by Kenshin** [comment]
> 我的环境就是win10。其他站点试了几个都好使

我先记 Bug 吧，然后问问其他人，或者等我换到 78 版本后，再试试~ 谢谢反馈你的问题。

**Comment by xhanb** [comment]
我了解到可能是chrome版本的原因，最新版本有安全限制。
你抽空调试下这个bug吧。PS：很好用的工具
![Snipaste_2019-11-01_12-37-17.png](https://i.loli.net/2019/11/01/1CYLlbHojGiSN5v.png)

**Comment by Kenshin** [comment]
👌

**Comment by Kenshin** [comment]
嗨，我已换到 Chrome 78.0.3904.87 系统，依旧可以正常的下载 MD 并未发生你说的情况。

建议，在隐身模式下，并仅允许 简悦 可用，然后再试试？

**Comment by xhanb** [comment]
刚才试了下正常情况下可以了，不知道是什么原因，很诡异。如果以后再遇到类似问题的话可以先试试你提到的隐身模式。

**Comment by Kenshin** [comment]
👌 那我就先关闭这个 issues 了~
