### ISSUE TITLE
保存到 dropbox 是看我本地的代理情况还是看简悦服务的连接情况？

### ISSUE THREAD

**Issue by CY-Christin** [Kenshin/simpread#6060]
### 描述这个错误

今天我尝试使用简悦往 dropbox 同步配置，但是提示远程数据同步失败，请稍后再试。然后我登录 web 端 dropbox 是可以正常打开并查看文件的。  
然后我尝试将 `https://weekly.tw93.fun/posts/152-%E8%B5%9B%E5%8D%9A%E7%BA%A2%E6%A1%A5` 这篇文章保存到 dropbox 也失败了，但是我绑定坚果云并保存至坚果云是可以直接保存的。  
我本地的代理应该是没有问题，但是关于 dropbox 的操作都不行。

### 复现步骤

1. 打开网站  
2. 右键进入阅读模式  
3. 选择保存至 dropbox

### 操作系统

macos

### 浏览器

chrome

### 发生问题的网址

https://weekly.tw93.fun/posts/152-%E8%B5%9B%E5%8D%9A%E7%BA%A2%E6%A1%A5

**Comment by Kenshin** [comment]
嗨

Dropbox 可能有点问题…

估计很少有用户导入 Dropbox 了，因为有很多更好的方案，所以你使用它有什么是因为什么？

**Comment by CY-Christin** [comment]
> 嗨
> 
> 
> 
> Dropbox 可能有点问题…
> 
> 
> 
> 估计很少有用户导入 Dropbox 了，因为有很多更好的方案，所以你使用它有什么是因为什么？

因为我开通了dropbox 的会员，想利用起来，而且国内的那些不太放心（审查机制）。  
notion 因为客户端不好用就一直弃用了。  对了，我测了 onenote 好像也不行。

**Comment by Kenshin** [comment]
嗨，昨晚没法测试，白天我测试了下。

> Dropbox 同步盘方案

这一定是不好使的，详细说明 https://github.com/Kenshin/simpread/discussions/3171

> 导入到 Dropbox

是没问题的，我刚才测试过了，不过因为 Dropbox 生成的 Token 只是临时的，所以有效期很短，不建议这么做...

如果你桌面安装了 Dropbox（因为你说你经常使用它...），可以使用 [同步助手将 Markdown 保存到任意目录](https://simpread.pro/docs/#/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA)

PS：当然，支持的不仅仅只是 Markdown 而已，几乎全部的格式都可以。

PPS：Onenote 肯定是没问题，但可能它比较慢... 同样，我也不建议使用 Onenote...

PPPS：还是建议使用更方便的方案，因为导入到 Dropbox 的图片都是在线的。
