### ISSUE TITLE
SimpRead高级版-Live Editor点击无反馈，Obsidian端点击内部链接，文章匹配到错误的历史本地文章

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#6061]
### 描述这个错误

如图，选中文本后，无法弹出标注工具栏：
- 
![image](https://github.com/Kenshin/simpread/assets/57386018/a83ef520-37e8-4035-8d4d-53e5927700f2)

点击Live Editor或清除元素也没有任何反馈. 只有将文章加载到稍后读，能正常导入到本地，包括原文和annotator

- 
![image](https://github.com/Kenshin/simpread/assets/57386018/73ccfe70-8608-4afd-91ce-9f140e572a33)

在obsidian的本地文章，点击“内部链接”功能正常，但是匹配到其他之前标注过的文章：

![image](https://github.com/Kenshin/simpread/assets/57386018/376e3c21-dbd0-4647-bf62-0c0206a436c2)

### 复现步骤

1. 将文章通过默认浏览器打开
2. 默认已启用SimpRead浏览器插件，和简约.同步助手
3. 通过使用DD快捷键，将文章和@annote导入到obsidian本地. 
4. 尝试在浏览器端进行阅读标注无反馈
5. 尝试在obsidian本地端进行内部链接访问和阅读，超链接打开的是其他历史文章. 

### 操作系统

Win11

### 浏览器

Edge

### 发生问题的网址

https://mp.weixin.qq.com/s/gxtdl4Varq_PefcTtBoeSw

**Comment by Kenshin** [comment]
Live Editor 不好使的话，试试其他页面是否有这个问题，比如少数派的。

**Comment by mdsnalw** [comment]
> Live Editor 不好使的话，试试其他页面是否有这个问题，比如少数派的。

感谢回复，我刚才又测试了其他少数派的链接，发现应该不是个别网站的问题，

测试的链接：https://sspai.com/post/84232

测试的结果：
1. 网页可以自动识别，并进入阅读模式，但是Live Editor或其他任何按钮点击无反馈. 
![image](https://github.com/Kenshin/simpread/assets/57386018/2d8ba1bf-b2ef-437b-a137-046809a47777)
2. 文章可以正常导入到obsidian，并生成两个文档，原文和annotator
![image](https://github.com/Kenshin/simpread/assets/57386018/066c50b8-09aa-4fbd-bd63-f1e3e3edcff3)

3. 在obsidian本地点击“内部链接”，匹配的还是其他历史阅读过的文章，且在右侧没有工具栏可以进行标注
![image](https://github.com/Kenshin/simpread/assets/57386018/3ab4ae4d-a6c7-43cf-9e65-9be7c3ca3554)

发现同步助手的端口号是，7026，与网页端和obsidian端的端口不一致，这个是否也需要改成7027？
![image](https://github.com/Kenshin/simpread/assets/57386018/6146d2cf-cb3c-4dca-b4ad-71d300ccaaf9)
![image](https://github.com/Kenshin/simpread/assets/57386018/3a612fd6-ac06-4a4d-8062-1b57f607fab2)
![image](https://github.com/Kenshin/simpread/assets/57386018/43cbc09a-1d70-44d1-b742-94b025752575)

**Comment by mdsnalw** [comment]
补充下，我发现在SimpRead/output文件下，从两三天前出现问题后，就没有在出现新的文件导入了，我在考虑是否重新做下配置，如果重新配置的话，基于当前的情况如何操作才是最简单有效的呢？谢谢~

![image](https://github.com/Kenshin/simpread/assets/57386018/2e72fcca-5286-477b-b2d4-1afd7715c2f6)

**Comment by Kenshin** [comment]
> Live Editor 无法使用

可能是你没有激活（点击）下面这个按钮造成的...（我不确定，但你截图没有给出激活状态...

<img width="724" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b77cf3b7-ad47-4450-9b02-5ee124c5b7ed">

> 端口号

没问题，默认是不需要改动的。

同步助手 → `7026`

Obsidian 插件 → `7027`

> 在obsidian本地点击“内部链接”，匹配的还是其他历史阅读过的文章，且在右侧没有工具栏可以进行标注

看下你的 output 文件夹是否生成了 `7-一日一技_将 Obsidian 页面按自定义模板导出为 Word 文档.html` 这个文件。

一般来说你的这种错误都是因为路径设置错误造成的，因为我看到你没有按照官方规则设置 `1-输入/5-simpRead / 7-一日一技_将 Obsidian 页面按自定义模板导出为 Word 文档@annote`

虽然可以这么做，但在设置成功前还是建议先按照教程中提到的文件夹结构设置。

**Comment by mdsnalw** [comment]
> > Live Editor 无法使用
> 
> 可能是你没有激活（点击）下面这个按钮造成的...（我不确定，但你截图没有给出激活状态...

确实是这样子的，我重新点击了简易编辑，之后标注工具栏就出来了 
> 
> <img alt="image" width="724" src="https://user-images.githubusercontent.com/81074/281981488-b77cf3b7-ad47-4450-9b02-5ee124c5b7ed.png">
> > 端口号
> 
> 没问题，默认是不需要改动的。
> 
> 同步助手 → `7026`
> 
> Obsidian 插件 → `7027`
> 
> > 在obsidian本地点击“内部链接”，匹配的还是其他历史阅读过的文章，且在右侧没有工具栏可以进行标注
> 
> 看下你的 output 文件夹是否生成了 `7-一日一技_将 Obsidian 页面按自定义模板导出为 Word 文档.html` 这个文件。

我晚上再做了一次标注，发现能导入到我的OutPut文件夹了. 但是obsidian内部的annotator MD文档下还是没有任何备注痕迹，匹配的文章也是错的. 

![image](https://github.com/Kenshin/simpread/assets/57386018/3659d525-cf14-47ff-b2ed-622232375c8f)
![image](https://github.com/Kenshin/simpread/assets/57386018/68de9aa3-f837-4953-b86d-8d28da5e4b39)

> 一般来说你的这种错误都是因为路径设置错误造成的，因为我看到你没有按照官方规则设置 `1-输入/5-simpRead / 7-一日一技_将 Obsidian 页面按自定义模板导出为 Word 文档@annote`
> 
> 虽然可以这么做，但在设置成功前还是建议先按照教程中提到的文件夹结构设置。

好的，我改回默认路径文件夹格式名称再试下，再做进一步反馈

**Comment by mdsnalw** [comment]
感谢大佬，目前的情况是：更改了简易的obsidian内部SimpRead路径为官方格式（虽然以前用自定义的格式也是可以正常导入，但为了稳定起见，我先用官方格式，后期没问题了再做微调~），目前是能在网页正常做标注，且导入的库外的也是我配置的HTML+MD文件格式，目前主要功能都正常，我再测试看看，谢谢大佬的耐心指导~

![image](https://github.com/Kenshin/simpread/assets/57386018/76416dad-d3e1-425e-98ea-266a3075ea8d)

**Comment by Kenshin** [comment]
okay 解决就好。

再改为你自己的方案，仅需要留意路径就行，修改后最好重启，然后确认路径修改已生效，当全部路径都修改后再测试。
