### ISSUE TITLE
导出离线html后代码段字体非常小

### ISSUE THREAD

**Issue by Ronny200** [Kenshin/simpread#6064]
### 描述这个错误

修改了自定义样式后，在阅读模式下代码段一切正常，字体和大小都已经修改，
当我导出离线html后，代码段字体非常非常小，看了下css，发现被下面这段覆盖
sr-rd-content pre, sr-rd-content pre *, sr-rd-content pre div {
    font-size: 17.6px;
    font-size: 1.1rem;

求教下如何设置离线文件的字体和大小？
![20231112-184228](https://github.com/Kenshin/simpread/assets/23441656/0e59ed43-30bc-439e-b57c-7c18f22835ac)

### 复现步骤

尝试过修改自定义样式，在阅读模式下修改都不行，导出后不对版，阅读模式显示正常。

### 操作系统

win11

### 浏览器

edge,chrome

### 发生问题的网址

https://github.com/svenstaro/miniserve

**Comment by Kenshin** [comment]
试试自定义样式

```
sr-rd-content pre, sr-rd-content pre *, sr-rd-content pre div {
    font-size: 17.6px!important;
    font-size: 1.1rem!important;
}
```

放到下图所示的地方（随便进入一个阅读模式，右下角会看到）

<img width="465" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/61bfbe04-485b-4e14-ae75-dd5db9d1aa72">

**Comment by Ronny200** [comment]
感谢大佬回复，昨天我发完帖子后自己设置了css就可以了。然后忘了回帖，谢谢百忙中回复
