### ISSUE TITLE
因与其他扩展冲突导致 GitHub 打开时卡顿

### ISSUE THREAD

**Issue by lacafjh** [Kenshin/simpread#6065]
### 描述这个错误

扩展导致 GitHub 域名的所有页面打开时卡顿，进而造成整个 Chrome 浏览器卡住。

### 复现步骤

1. 试验在浏览器中关闭除 SimpRead 以外的全部扩展都无法改善 github.com 域名的网页出现的卡顿现象
2. 关闭 SimpRead 之后，尝试进入 GitHub 的存储库、Issues 页面，都不再会导致页面和浏览器卡死。

综合上述 2 点判断是和 SimpRead 某些页面内行为有关的问题。

### 其他相关说明

同时有安装「[琼斯医生](https://leopoldthecoder.github.io/doctor-jones/)」扩展，作用是将网页中文排版规范化。开始怀疑是 SimpRead 与这个扩展同时使用造成的问题，但是关闭「琼斯医生」而开启 SimpRead 并没有让卡死现象消失，因此初步排除。

### 操作系统

Windows 10 22H2 (OS build 19045.3570)

### 浏览器

Chrome 119.0.6045.124

### 发生问题的网址

github.com/*

**Comment by Kenshin** [comment]
嗨，我每天都在使用 Github 所以不可能是简悦的问题。😂

并且你也找到了原因… 是如果你不需要在 Github 使用简悦的话，试试将 github.com 加入黑名单看看能否解决？
