### ISSUE TITLE
导入obsidian中的文件夹无法转移到其他的文件夹，只能在output这个文件夹

### ISSUE THREAD

**Issue by sylviayee5** [Kenshin/simpread#6066]
### 描述这个错误

在网站的文章按aa转到阅读模式后，
选择的动作分别是
**导入全文到obsidian**和导入 **md + assets 到obsidian**，到了obsidian文件夹output中，每篇文章都有文章和一个assets的文件夹。（两个动作都尝试了）

### 问题是：
我将output收集的文章拖进我在obsidian自己的文件夹，
出现了两种状况：
1. 有些文章中的图片无法显示，assets的文件夹仍然在的，
   但是就是无法显示，会出现如下图所示：
![image](https://github.com/Kenshin/simpread/assets/115459285/7f869b72-2a88-4899-a7e4-e7ccce57ebc6)

2. 有些文章直接就会失去assets这个文件夹，无法使用。并且跑回原来output这个文件夹，在原来我自己创的文件夹中直接失去了文章，只有文件夹。。
![image](https://github.com/Kenshin/simpread/assets/115459285/5dc9e2cd-9936-49cf-a47d-14f2b7c03d4a)

### 疑问：
是我操作不对还是哪里需要设置一下呢？

### 操作系统

macOS

### 浏览器

edge

### 发生问题的网址

https://www.sohu.com/a/351499154_509371

**Comment by Kenshin** [comment]
如果你想要定制 `assets + md` 的位置，选项里面的说明应该足够清晰了

<img width="619" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0115e0b4-d90a-4776-b255-e08d7f8343fa">

上图对应的链接 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749

**Comment by sylviayee5** [comment]
> 如果你想要定制 `assets + md` 的位置，选项里面的说明应该足够清晰了
> 
> <img alt="image" width="619" src="https://user-images.githubusercontent.com/81074/282435130-0115e0b4-d90a-4776-b255-e08d7f8343fa.png">
> 上图对应的链接 [#4041 (comment)](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749)

这个目录是output那个目录吗

**Comment by Kenshin** [comment]
仔细看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749 的说明...

如果不设置的话，就是 `output` 文件夹。

**Comment by sylviayee5** [comment]
> 仔细看 [#4041 (comment)](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749) 的说明...
> 
> 如果不设置的话，就是 `output` 文件夹。

可以和output同一个文件夹吗？还是新开一个文件夹比较合适？

**Comment by sylviayee5** [comment]
> 仔细看 [#4041 (comment)](https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749) 的说明...
> 
> 如果不设置的话，就是 `output` 文件夹。

我拖动到自己文件夹里图片会消失是因为没有设置这个根目录吗？有些文章还是有图片的，有些没有。。

**Comment by Kenshin** [comment]
> 拖动到自己文件夹

我不理解你是怎么「拖」的，以及为什么要拖... 如果你想要直接导入到你的 Obsidian，就把路径设置为你 Obsidian 的位置就好了

例如下图

<img width="675" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e7de0f0d-f6e3-48b3-918f-c1d5a330bbb4">

**Comment by sylviayee5** [comment]
> > 拖动到自己文件夹
> 
> 我不理解你是怎么「拖」的，以及为什么要拖... 如果你想要直接导入到你的 Obsidian，就把路径设置为你 Obsidian 的位置就好了
> 
> 例如下图
> 
> <img alt="image" width="675" src="https://user-images.githubusercontent.com/81074/282438979-e7de0f0d-f6e3-48b3-918f-c1d5a330bbb4.png">

我设置了的。
![image](https://github.com/Kenshin/simpread/assets/115459285/96e44bcf-b998-4aca-9c3b-4da403d0c2aa)

我的意思是，我收集的文章都有不同的主题。一开始通过jianyue导出全部保存在obsidian一个文件夹里，然后我在obsidian中转移到我分好的文件夹中，就是在这个转移的过程中，原本的文章图片会跑丢。放在简悦初始导入的文件夹就没事，图片和文章都好好的。一转移就图片和文章不在一块了

**Comment by Kenshin** [comment]
emm 

https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 改为方案一（默认值）试试

如果还不行，把你需要拖完后有问题的文件打包发上来，我瞧瞧。

**Comment by Kenshin** [comment]
> 补充 https://github.com/Kenshin/simpread/issues/6066#issuecomment-1808265934 的说明

如果你想要实现拖到任意目录的诉求，就要保证导出的 md + assets 在一个文件夹中，类似下图所示

<img width="1558" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5bdefa1b-ee95-4409-944c-ff96d83e0894">

同时在 Obsidian 中需要设置下图所示的方式

<img width="615" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3a2f2ec4-7933-4edd-8091-9bf2b0e1f888">
