### ISSUE TITLE
手机端分享的微信公众号文章链接，电脑打开时无法调用简悦。

### ISSUE THREAD

**Issue by shakewell0411** [Kenshin/simpread#6068]
### 描述这个错误

将微信公众号文章从手机端分享到 文件传输助手，然后用 电脑版微信 打开 微信公众号文章的chrome网页，无法使用简悦(没有任何反应）。

### 复现步骤

将微信公众号文章从手机端分享到 文件传输助手，然后用 电脑版微信 打开 微信公众号文章的chrome网页，无法使用简悦(没有任何反应）。

### 操作系统

windows

### 浏览器

Chrome  119.0.6045.124 (正式版本) (64 位元)

### 发生问题的网址

https://mp.weixin.qq.com/s/qjnIHXGrYqK77LbIfl7FCw

**Comment by Kenshin** [comment]
嗨，你可以安装这个插件 https://github.com/Kenshin/simpread/discussions/5851 一般能解决无法适配公众号的问题。
