### ISSUE TITLE
为什么站点集市下了语雀，看到下载成功，几秒钟后页面刷新又自动删除了

### ISSUE THREAD

**Issue by Celestial32085** [Kenshin/simpread#6070]
### 描述这个错误

如下面

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/65842560/92de2967-5d50-4945-95b5-d280b3e3f3ac)
几秒钟后没了，而且转换乱了，也没有触发语雀插件
![image](https://github.com/Kenshin/simpread/assets/65842560/fefc1897-957c-4282-ac31-0ae7e424f50e)

### 操作系统

Windows

### 浏览器

edge

### 发生问题的网址

https://www.yuque.com/yuqueyonghuo2uluz/anox6e/kle7cetrykpyb2ll

**Comment by Kenshin** [comment]
1. 你给出的 URL 无法访问

2. 是否使用了同步助手的自动同步功能，如果是的话，请使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装

3. 请使用 https://github.com/Kenshin/simpread/discussions/4380 提到的插件，而不仅仅只是安装语雀适配规则。

4. 我测试了 https://www.yuque.com/kenshin/simpread/ebwu7g 是可以正常访问的。
