### ISSUE TITLE
一键导入到notion时，总是显示请稍后再试

### ISSUE THREAD

**Issue by eyun221** [Kenshin/simpread#6072]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/9376835/ce783aba-e42e-4565-aaf7-943176e06c45)

打开审查模式，发现有个notion的链接报错了，如下图
![image](https://github.com/Kenshin/simpread/assets/9376835/7685a1b5-fc4f-4d38-9fc7-85a4ff55074c)

### 复现步骤

1.打开  https://sspai.com/post/69972
2.选择一键导入全文到notion
3.出现问题

### 其他相关说明

无

### 操作系统

macos

### 浏览器

chrome 119

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
你是使用下面的方式吗？

<img width="362" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5ac789d1-dbec-425f-a297-32c0f38fbce8">

PS：这个功能没问题的，我刚测试了。
