### ISSUE TITLE
高亮字段后 无法导出配置同步到logseq

### ISSUE THREAD

**Issue by blackheufhucs** [Kenshin/simpread#6073]
### 描述这个错误

emmm  这是我前几天参考的一篇logseq与简悦同步的配置文章  https://sspai.com/post/72022  所有的步骤我保证和这篇文章没有一点差错  然后前两天  随意打开公众号几篇英语文章 高亮  确实都同步到了logseq  然后再对对应的高亮词汇做笔记  整个流程非常完美   但是今天下午我继续阅读的时候  一高亮就发生了下面的问题  它说导出失败，此功能为实验性功能，如有需求请提升issues（参考下面截图）  然后我就点击issues  就跳转到github的一个页面  我再点击第一个提交Bug  就到这儿了  我感觉应该不是dropit同步的问题  也不是坚果云的问题  不知道为什么就不能导出说是实验性功能了   应该是简悦导出的功能我不太懂   麻烦开发者大佬看看吧  我真的不太懂

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/132288670/4d2c3ce2-2591-45c4-a0ed-3b6a71668166)
主要就是这张图了   其他配置流程都在“描述这个错误”里面   所有配置过程一致的

### 其他相关说明

没有了应该  我会非常感激如果开发者大佬能看到我的问题并且尽早回复，非常感谢！！！

### 操作系统

windows10

### 浏览器

chrome最新版  应该不是浏览器的问题

### 发生问题的网址

https://mp.weixin.qq.com/s/5bNAYtKWW5reDM-TTMOZsw

**Comment by Kenshin** [comment]
嗨，这个链接对应的功能有点「过时」了，当然并不影响使用。

最新方案 https://www.yuque.com/kenshin/simpread/pv5acw

***

至于你的问题，不知道是否仅这个链接有问题？还是任意 URL 都不行，你可以试试找篇少数派的文章测试下。

**Comment by blackheufhucs** [comment]
你好！ 非常感谢还来收到我的问题对应的邮件回复，当天的问题已经确认了只是那一篇URL有问题，其他微信文章都能正常同步，至于最新方案，我会好好研究看看，感谢提供的最新方案的链接，再次感谢回复！！

发件人：Kenshin Wang ***@***.***>
发送日期：2023-11-14 22:25:41
收件人：Kenshin/simpread ***@***.***>
抄送人：blackheufhucs ***@***.***>,Author ***@***.***>
主题：Re: [Kenshin/simpread] 高亮字段后 无法导出配置同步到logseq (Issue #6073)

嗨，这个链接对应的功能有点「过时」了，当然并不影响使用。
最新方案 https://www.yuque.com/kenshin/simpread/pv5acw
至于你的问题，不知道是否仅这个链接有问题？还是任意 URL 都不行，你可以试试找篇少数派的文章测试下。

**Comment by Kenshin** [comment]
小事情，个例就好~ 

PS：你回复可够晚的了 😂

PPS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉😁👍
