### ISSUE TITLE
雪球并没有做好适配

### ISSUE THREAD

**Issue by yuanming1** [Kenshin/simpread#6074]
### 需要适配的新站

https://xueqiu.com/3621716791/260794082

### 有需要请描述这个站的性质

中文的投资网站，适用面很广

**Comment by Kenshin** [comment]
嗨，你提供的页面无需使用阅读模式，但你可以使用下图所示方式

<img width="1028" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/bfa56d12-1d01-4a02-baa0-332fa1ee9d8e">

但例如 https://xueqiu.com/9259989802/266900463 这类页面是可以直接进入阅读模式的。
