### ISSUE TITLE
段落高亮之后，保存到有道云笔记，并没有高亮部分的内容

### ISSUE THREAD

**Issue by yuanming1** [Kenshin/simpread#6075]
### 描述这个错误

段落高亮之后，保存到有道云笔记，并没有高亮部分的内容

### 复现步骤

段落高亮之后，保存到有道云笔记，并没有高亮部分的内容

### 操作系统

macos

### 浏览器

chrome 116.0.*.* 版本

### 发生问题的网址

https://mp.weixin.qq.com/s/OHuq7B-TROus28SKyZhHkQ

**Comment by Kenshin** [comment]
嗨，这是正常的情况，只有部分笔记工具如：

- Obsidian、Logseq（完美支持）

- Notion（ 部分支持）

并不是没法做，而是大部分笔记天然无法满足标注的形态。

但你可以将标注（非全文，仅标注）导入到有道云笔记中。
