### ISSUE TITLE
印象笔记一直提示授权失败

### ISSUE THREAD

**Issue by jimo37** [Kenshin/simpread#6076]
### 请选择

印象笔记

### 发生问题的网址

试了以前的issue里提到的授权网址，发现打开后提示application error

**Comment by jimo37** [comment]
![image](https://github.com/Kenshin/simpread/assets/1326980/d7786277-eb6f-4db3-90e4-9ab11ad902ec)

**Comment by Kenshin** [comment]
嗨，这个功能确实有点问题，另外我个人也不建议用户再继续使用印象笔记了，现在有很多更好，更现代的笔记工具。
