### ISSUE TITLE
在logseq插件中进行标注时，不会同步到logseq中

### ISSUE THREAD

**Issue by RobertCheng-956** [Kenshin/simpread#6077]
### 描述这个错误

在logseq中进行标注，不会同步到logseq中，但是能够同步到稍后读里面。

### 复现步骤

1. 在logseq中对内容A进行标注，不会同步到logseq中
2. 查看稍后读，发现稍后读中同步了内容A标注
3. 在稍后读中对内容B进行标注后，内容A和B就都会被同步进去。
4. 就是说，在logseq中能够标注，但是如果不到稍后读里面来进行操作，是不会直接同步的。

### 操作系统

window11

### 浏览器

chrome

### 发生问题的网址

logseq

**Comment by Kenshin** [comment]
你是使用了 https://www.yuque.com/kenshin/simpread/pv5acw 方案？还是什么其它的 Logseq 方案？需要明确说下。

或者看下 https://www.yuque.com/kenshin/simpread/gbere7 的教程对比下跟自己的区别。

根据你的描述，大致的问题是：

> 在 Logseq 的右侧标注，但在 Logseq 左侧标注没有更新？

一般来说这个问题都是路径设置造成的，你可以看下 https://www.yuque.com/kenshin/simpread/gbere7#wUuuB 的说明

***

如果我的回复跟你的问题无关，还是建议录屏给我看下。

**Comment by RobertCheng-956** [comment]
使用的是配置库方案，这几个我都对比了，没有发现问题。还有一个标注模板设置了，但是没有使用上。

https://github.com/Kenshin/simpread/assets/44940678/040ddb82-805d-4ee3-9e6d-803de7d3737f

在logseq的插件中标注后，能够同步到稍后读里面去，但是在logseq的标注md文件中，无法同步。同时在标注md文件中，也无法使用标注模板。

**Comment by Kenshin** [comment]
我看了你的视频，你的操作（以及配置）并不属于配置库方案，而是普通方案，但你确实配置了部分配置库方案（因为可以在 Logseq 打开右侧内嵌本地快照）

我不清楚你具体以哪种配置库为基准，所以需要指出你使用了哪种配置库方案。

除此之外，留意下面的几个问题：

1. 试试在正常的阅读模式下标注，能否更新到 Logseq？

2. 打开 `http://localhost:7026/unread/xxx` 这个 `xxx` 是你自己的稍后读 ID，看你的视频似乎是 `58`

**Comment by RobertCheng-956** [comment]
我最开始就是通过配置库方案设置的，就是这个链接https://www.yuque.com/kenshin/simpread/pv5acw；
我能够打开http://localhost:7026/unread/xxx这个网址，不过在这个网址里面进行标注的话是不会同步到logseq中的md文档中去的，但会同步到logseq的插件当中去。
但是，我如果在正常浏览网页过程中，进入阅读模式，然后标注的话，就可以同步到logseq中去。

**Comment by RobertCheng-956** [comment]
我刚刚还发现一个问题，就是我在 http://localhost:7026/unread/xxx 这个网址中，点击打开独立的窗口编辑标注，然后出来的简悦同步助手会显示 {"code":404,"message":"没有找到对应的内容"}

**Comment by Kenshin** [comment]
> 我最开始就是通过配置库方案设置的，就是这个链接https://www.yuque.com/kenshin/simpread/pv5acw

这个链接指向了两个方案 😂



> 我刚刚还发现一个问题，就是我在 http://localhost:7026/unread/xxx 这个网址中，点击打开独立的窗口编辑标注，

`点击打开独立的窗口编辑标注` 具体指操作哪里？

> 出来的简悦同步助手会显示 {"code":404,"message":"没有找到对应的内容"}

这是没有本地快照的提示信息，说明还是你的配置有问题，主要是路径，一般来说看下 https://www.yuque.com/kenshin/simpread/tukkeo#Vk76G 但跟你的 https://github.com/Kenshin/simpread/issues/6077#issuecomment-1814178909 的描述冲突...

***

综上，我还是建议先对比下跟教程的区别，做到 100% 一致，你的问题显示不是 100% 一致... 😂

或者你把全部相关设置都截图给我也行。

**Comment by Kenshin** [comment]
`Logseq@simpread` 可以随意更改，注意路径就行。

哈哈，解决就好，我关闭这个 Issues 。

**Comment by Kenshin** [comment]
方便的话请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉😁👍
