### ISSUE TITLE
部分网站进入阅读模式后不自动隐藏原页面

### ISSUE THREAD

**Issue by sasasqt** [Kenshin/simpread#6078]
### 描述这个错误

rt

### 复现步骤

示例网址：https://developer.nvidia.com/gpugems/gpugems2/part-i-geometric-complexity
![image](https://github.com/Kenshin/simpread/assets/56587914/245ccad2-c7d8-447a-83da-5221f71913ce)
增加 !important 后修复改问题：
![image](https://github.com/Kenshin/simpread/assets/56587914/93ee0972-4dda-4b47-9267-83fb072481ce)

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

https://developer.nvidia.com/gpugems/gpugems2/part-i-geometric-complexity

**Comment by sasasqt** [comment]
自定义全局样式里加入：
```
.simpread-hidden {
height: 0px !important;
}
```

**Comment by Kenshin** [comment]
okay 可能是这类页面「太霸道了」😂

既然解决了，我关闭这个 Issues 了。
