### ISSUE TITLE
阅读模式下，部分文字不显示

### ISSUE THREAD

**Issue by mxyq** [Kenshin/simpread#608]
链接在此  https://wangchujiang.com/linux-command/c/firewall-cmd.html

**Comment by Kenshin** [comment]
谢谢反馈...

不过，这个页面的内容也太多了，最好能直接告诉我哪里少了。  😂  😵

**Comment by mxyq** [comment]
就是 # 注释注释注释   不显示

**Comment by Kenshin** [comment]
我这边没问题

![image](https://user-images.githubusercontent.com/81074/68371134-fa951900-0178-11ea-8d1e-a6d060dab0b2.png)

请问是否使用了 https://github.com/Kenshin/simpread/issues/500 这个插件？

**Comment by mxyq** [comment]
安装了 #500 这个插件，正常了，谢谢

**Comment by Kenshin** [comment]
okay 这个插件也有些问题 https://github.com/Kenshin/simpread/issues/570 

目前还未更新这个插件，更新后，我会在这里通知到你。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

更新了词法分析引擎，此问题应该可以被解决了。

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
