### ISSUE TITLE
markdown导入obsidian 出现问题

### ISSUE THREAD

**Issue by kkkkkino123** [Kenshin/simpread#6080]
### 描述这个错误

采用导入md+assets到obsidian，其中图片到处位置方案采用方案4（自定义图片保存路径）；
出现的bug是：到导入时，会出现如图所示错误：
![image](https://github.com/Kenshin/simpread/assets/104644042/9cbdcdc0-ef64-4559-8b69-858af77a2a6e)。
我这是第二台电脑进行部署ob和简悦，同步助手似乎仍在使用我第一台电脑的图片保存路径

### 复现步骤

 1. 进入批注模式
 2. 选择导出md+assets格式
 3. 出现bug

![image](https://github.com/Kenshin/simpread/assets/104644042/7742a70d-70ce-43a1-afd7-416984929b33)

### 操作系统

window10

### 浏览器

Google chrome

### 发生问题的网址

anyone

**Comment by Kenshin** [comment]
> 我这是第二台电脑进行部署ob和简悦，同步助手似乎仍在使用我第一台电脑的图片保存路径

在新电脑需要重新设置下同步助手的路径设置。

<img width="674" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a8217833-0a77-4166-9859-b61f2abeb225">
