### ISSUE TITLE
点击导入到notion辅助增强后，会提示   Notion 辅助增强优化失败，请手动重新优化。

### ISSUE THREAD

**Issue by kola-919** [Kenshin/simpread#6081]
### 描述这个错误

在进入阅读模式后，点击notion辅助增强。过一会儿后右上角就会弹出一个 Notion 辅助增强优化失败，请手动重新优化。我没法弄好这个。

### 复现步骤

我不知道咋发图片呜呜呜呜

### 操作系统

Windows

### 浏览器

Vivaldi

### 发生问题的网址

https://zhuanlan.zhihu.com/p/87749797

**Comment by Kenshin** [comment]
嗨

1. 导入到 Notion 是否正常？

2. 无法使用增强导出的话，试试 https://www.yuque.com/kenshin/simpread/wwk65u#RIJdT 提到的方式能否解决？

**Comment by kola-919** [comment]
开发者你好！
      首先非常感谢你开发了这个插件，，让我能够保存网页，也很感谢你回复了我的问题。但是在使用插件的过程中，还是碰到了一些让我难以解决的问题，我尝试了许多遍https://www.yuque.com/kenshin/simpread/wwk65u#RIJdT&nbsp;中的解决方法，但是最后却并没有解决。我将具体说明一下我碰到的难题，如果方便的话，希望能够得到解答，非常感谢。
      我安装好了如下插件:





      授权情况如下：



      导入到辅助notion增强选项如下：



      当我点击导入到notion辅助增强，还是会出现：



      我已经确定了我的token和pageID输入正确，同时也收藏了我的页面。而且我试过插件触发器的其他功能，只有导入到notion辅助增强会出现问题。如果还需要我提供其他配置，可以和我说，万分感谢！

                       
原始邮件
                       
                     

发件人："Kenshin Wang"< ***@***.*** &gt;;

发件时间：2023/11/16 11:13

收件人："Kenshin/simpread"< ***@***.*** &gt;;

抄送人："kola-919"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Kenshin/simpread] 点击导入到notion辅助增强后，会提示   Notion 辅助增强优化失败，请手动重新优化。 (Issue #6081)




 
嗨
 
 
导入到 Notion 是否正常？
 

 
无法使用增强导出的话，试试 https://www.yuque.com/kenshin/simpread/wwk65u#RIJdT 提到的方式能否解决？

**Comment by Kenshin** [comment]
嗨，有可能请登录到 https://github.com/Kenshin/simpread/issues/6081 回复我，Email 回复是看不到任何图片的。
