### ISSUE TITLE
标注后会自动加入稍后读

### ISSUE THREAD

**Issue by rryain** [Kenshin/simpread#6082]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/144131189/e957b739-5d8c-487f-a762-d1df903ebc1b)
进入阅读模式后标注后会自动加入稍后读
``

### 复现步骤

直接打开网页，打开阅读模式
标注
被添加自动添加到稍后读了

### 其他相关说明

[config - 副本.json](https://github.com/Kenshin/simpread/files/13372472/config.-.json)改了uid
简悦设置面
![QQ截图20231116130540](https://github.com/Kenshin/simpread/assets/144131189/1636ad6f-57a5-4fb9-ac1e-2538cf51fb0e)
![QQ截图20231116130606](https://github.com/Kenshin/simpread/assets/144131189/30695f0a-fb0b-49dc-86d2-c8c7ea0f5e03)
![QQ截图20231116130632](https://github.com/Kenshin/simpread/assets/144131189/bfd4c8e4-4796-48c0-872d-76ca83596f01)

同步助手

ps:
增强导出也出错了，我不知道是不是配置问题（一开始就没成功）
{"extension":"pdf", "path":"D:\工作流\输入\SimpRead\pdf"}
{"extension":"html", "path":"D:\工作流\输入\SimpRead\html\annote", "type":"annote"}
{"extension":"html", "path":"D:\工作流\输入\SimpRead\html\html", "type":"page"}
{"extension":"assets", "path":"D:\工作流\输入\SimpRead\md+assert\md"}
{"extension":"md", "path":"D:\工作流\输入\SimpRead\md+assert\md"}
{"extension":"tts", "path":"D:\工作流\输入\SimpRead\tts"}
同步助手
![image](https://github.com/Kenshin/simpread/assets/144131189/98e7126d-ce04-4d33-aced-de622872377b)
![image](https://github.com/Kenshin/simpread/assets/144131189/eabb3583-9705-4130-be80-194bab5067e4)
![image](https://github.com/Kenshin/simpread/assets/144131189/dc47ed47-d581-4c4a-9b69-29dac386c1f2)

### 操作系统

windows

### 浏览器

 Microsoft Edge 版本 119.0.2151.58 (正式版本) (64 位)  Chrome 版本 119.0.6045.106（正式版本） （64 位）

### 发生问题的网址

csdn steckoverflow 。。。。。

**Comment by Kenshin** [comment]
这是预期（正常）情况

在没有稍后读的阅读模式，当第一次标注后即自动成为稍后读。

简悦的稍后读与标注是 **一体** 的。

**Comment by rryain** [comment]
懂了,他导入的时候没有触发"自动化" 中的稍后读(加入稍后读,导出为markdown)也是正常情况吗?

**Comment by rryain** [comment]
ok

**Comment by Kenshin** [comment]
方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉😁👍

**Comment by rryain** [comment]
好评了,顺便问一下

这个同步助手的导出设置有问题吗,我找不到其他案例参考,不知道除了什么问题.
{"extension":"pdf", "path":"D:\工作流\输入\SimpRead\pdf"}
{"extension":"html", "path":"D:\工作流\输入\SimpRead\html\annote", "type":"annote"}
{"extension":"html", "path":"D:\工作流\输入\SimpRead\html\html", "type":"page"}
{"extension":"assets", "path":"D:\工作流\输入\SimpRead\md+assert\md"}

**Comment by Kenshin** [comment]
试试改为

```
{"extension":"pdf", "path":"D:\\工作流\\输入\\SimpRead\pdf"}
```

**Comment by rryain** [comment]
ok,我多试试

**Comment by rryain** [comment]
谢谢,改好了{"extension":"pdf", "path":"D:\\工作流\\输入\\SimpRead\pdf"}
还是转义字符的问题,(疏忽大意)
{"extension":"pdf", "path":"D:\\工作流\\输入\\SimpRead\\pdf"}
{"extension":"html", "path":"D:\\工作流\\输入\\SimpRead\\html\\annote", "type":"annote"}
{"extension":"html", "path":"D:\\工作流\\输入\\SimpRead\\html\\html", "type":"page"}
{"extension":"assets", "path":"D:\\工作流\\输入\\SimpRead\\md+assert\\md"}

**Comment by Kenshin** [comment]
哈，没问题了吧？

**Comment by rryain** [comment]
没有了,谢谢

**Comment by Kenshin** [comment]
okay 解决就好~

**Comment by rryain** [comment]
b（￣▽￣）d
