### ISSUE TITLE
全文翻译、划词翻译插件无法使用ChatGPT (Web)翻译选项，一直显示正在加载

### ISSUE THREAD

**Issue by hiyoungshen** [Kenshin/simpread#6085]
### 描述这个错误

<img width="541" alt="image" src="https://github.com/Kenshin/simpread/assets/48718428/e53b74d9-0285-4773-8246-af0e5c053a1b">
<img width="1677" alt="image" src="https://github.com/Kenshin/simpread/assets/48718428/06c49e1c-7214-4154-90bd-e7dd74563d3e">

划词翻译+全文翻译都一直正在加载

### 复现步骤

1. 安装划词翻译或者全文翻译插件。
2. 进入选项页面配置使用ChatGPT (Web)翻译选项
3. 测试或是进入阅读模式后划一段进行翻译。

### 操作系统

macOS sonoma, windows11

### 浏览器

microsoft egde Version 118.0.2088.61 (Official build) (arm64)

### 发生问题的网址

https://ar5iv.labs.arxiv.org/html/2301.11916

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/6084 重复了，我关闭这个 Issues 了。

另外使用 **测试 API** 看看：其它页面有问题吗？
2.

**Comment by hiyoungshen** [comment]
API的翻译是没有问题的，另外这个issue和[#6084](
https://github.com/Kenshin/simpread/issues/6084)不是同一个问题，[#6084](
https://github.com/Kenshin/simpread/issues/6084)显示的问题不止包括翻译插件的，内置的标注也是如此

**Comment by Kenshin** [comment]
嗨，我测试了下这个问题，我这边是正常的，段落翻译和划词翻译都可以正常使用。

1. 试试其它页面（不是这个网站的）

2. 测试 API 确定正常使用？
