### ISSUE TITLE
win11（22H2 22621.2428）下载同步助手（1.2.0）后，无法打开软件

### ISSUE THREAD

**Issue by mrjayxj** [Kenshin/simpread#6086]
### 描述这个错误

win11（22H2 22621.2428）下载同步助手（1.2.0）后，无法打开软件
1、从官方世纪互联onedrive下载同步助手（1.2.0）；
2、使用bandzip解压压缩包；
3、复制压缩包至数据盘；
4、尝试打开软件（非管理员/管理员），均无法打开，鼠标转圈，无响应，转圈消失后软件未打开；
5、检查任务管理器，未找到同步助手进程。

### 复现步骤

1、从官方世纪互联onedrive下载同步助手（1.2.0）；
2、使用bandzip解压压缩包；
3、复制压缩包至数据盘；
4、尝试打开软件（非管理员/管理员），均无法打开，鼠标转圈，无响应，转圈消失后软件未打开；
5、检查任务管理器，未找到同步助手进程。

### 操作系统

windows11

### 浏览器

microsoft edge

### 发生问题的网址

https://www.cnblogs.com/aqicheng/p/14668187.html

**Comment by Kenshin** [comment]
emmm 

应该只是个例... 试试不要在系统盘（或系统路径下）使用。
