### ISSUE TITLE
PDF 高级打印方案使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6087]
mac 导出失败了，文章链接 https://sspai.com/post/71576
![image](https://github.com/Kenshin/simpread/assets/26494876/7e198c03-04b4-403b-9891-2d341bde1404)

没有做什么特殊设置，就是选择了[同步助手高级打印方案]，其他都是默认的
<img width="651" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/2156f442-66e8-43ad-824e-0f6e8abca396">

_Originally posted by @neolin0629 in https://github.com/Kenshin/simpread/discussions/3887#discussioncomment-7589673_

**Comment by Kenshin** [comment]
@neolin0629 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

这个功能需要安装 `wkhtmltopdf` 所以并不是 **没有什么特殊设置** 就可以直接使用的。

因为你没有详细描述是否安装了 `wkhtmltopdf` 所以提示下。

**Comment by neolin0629** [comment]
@Kenshin 你好，是安转了wkhtmltopdf的。我今天试了一下，还是失败。
<img width="317" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/db45a4d5-9a48-48bc-a186-b096428a9454">

**Comment by Kenshin** [comment]
emmm 当出现第一个图（右上角有失败提示）时，鼠标右键 → 检查 → 打开 Devtools

<img width="309" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/506a5cf1-1e37-4425-8886-1039827810b3">

然后把控制栏的错误信息截图给我

<img width="1283" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/916d6b50-24a4-42d2-8080-f6299d1ad36c">

**Comment by neolin0629** [comment]
是下图的样子
<img width="1339" alt="error-pdf-export" src="https://github.com/Kenshin/simpread/assets/26494876/29e9b6ce-9128-4dab-94bf-75bd448c1c4e">

**Comment by Kenshin** [comment]
<img width="473" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/df8a9fb6-8c61-471f-becc-103443d7c2aa">

上图这个路径是正确的吗？

***

看上图你应该配置了本地快照文件夹，试试导出一个本地文件到这个文件夹是否正常？与截图确保同一个网页 e.g. 应该是 https://sspai.com/post/71576

**Comment by neolin0629** [comment]
地址是这个 /Users/linnan/Nutstore Files，是不是中间有空格的原因？
<img width="391" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/741c8e83-1284-4564-9951-e21a2bce88a6">

**Comment by Kenshin** [comment]
> 手动保存可以

我所说的手动保存是指：通过简悦的增强导出，即需要设置截图所示的文件夹

<img width="681" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/16ae6420-5ad3-4fcc-a83d-07976cf66705">

你给的截图似乎不是通过简悦的增强导出方式导出，而是浏览器导出，使用简悦的导出方式是下图所示，然后并没有通过浏览器下载。

<img width="265" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9f306042-361b-4397-9f37-c6d43b40bf9b">

***

[你截图出错的地址](https://user-images.githubusercontent.com/81074/284129186-df8a9fb6-8c61-471f-becc-103443d7c2aa.png) 是通过通过同步助手设置的，也就是 [第一个图所示](https://github.com/Kenshin/simpread/assets/81074/16ae6420-5ad3-4fcc-a83d-07976cf66705)，而增强导出也使用了第一个图的方式。

因此，增强导出可以使用的话，理论上 `wkhtmltopdf` 就能使用。

**Comment by neolin0629** [comment]
明白了，是可以的。

设置如下
<img width="705" alt="config" src="https://github.com/Kenshin/simpread/assets/26494876/c1c5b298-d642-4822-b513-76d0c16cb047">

结果如下
<img width="634" alt="save_success" src="https://github.com/Kenshin/simpread/assets/26494876/a3064aeb-d955-4736-9c2d-793995951a41">

<img width="830" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/3581ea3e-7623-48bc-ac59-44ff4e167a51">

**Comment by Kenshin** [comment]
emmm 那就更奇怪了 😂 

因为你是 Mac 系统，所以安装和配置 `wkhtmltopdf` 很简单，几乎不用过多操作...

你试试把 [导出目录](https://user-images.githubusercontent.com/26494876/284175474-c1c5b298-d642-4822-b513-76d0c16cb047.png) 设置到没有空格的文件夹，随便本地什么文件夹都可以，**保存后重启同步助手确保设置生效**。

再测试 PDF 的功能，如果还是有错误，按照 [这个图](https://user-images.githubusercontent.com/81074/284124427-916d6b50-24a4-42d2-8080-f6299d1ad36c.png) 打开然后按下图所示的提示操作。

<img width="1785" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2e3fe9b0-4f0c-4ea5-9349-4fda47372f54">

**Comment by neolin0629** [comment]
"/usr/local/bin/wkhtmltopdf --margin-left 10 --margin-right 10 --margin-top 10 --margin-bottom 10 /Users/linnan/document/tmp-放弃纠结、拥抱妥协，重器轻用就是高效.html /Users/linnan/document/放弃纠结、拥抱妥协，重器轻用就是高效.pdf"

仍然失败  😂

**Comment by Kenshin** [comment]
确保 `/Users/linnan/document/放弃纠结、拥抱妥协，重器轻用就是高效.html` 存在的前提（如果不存在把之前 `output` 路径下的同名文件复制到 `/Users/linnan/document/` 一份。

然后直接在命令行中输入

```
/usr/local/bin/wkhtmltopdf --margin-left 10 --margin-right 10 --margin-top 10 --margin-bottom 10 /Users/linnan/document/放弃纠结、拥抱妥协，重器轻用就是高效.html /Users/linnan/document/放弃纠结、拥抱妥协，重器轻用就是高效.pdf
```

看看能否正常生成 PDF ？

**Comment by neolin0629** [comment]
结果提示这个，应该是成功了
<img width="1527" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/24699197-14b1-4014-817d-65d192859cc1">

**Comment by Kenshin** [comment]
我也不会了... 你应该第一个 Mac 系统出现无法使用这个功能的用户 😂 

你是什么 Mac 什么版本？同步助手安装在什么地方？

**Comment by neolin0629** [comment]
😂 Mac 版本
<img width="224" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/c2061ca3-d011-4c9d-808d-1bfa8d37095d">

同步助手就在应用程序文件夹了
<img width="714" alt="image" src="https://github.com/Kenshin/simpread/assets/26494876/c9062232-a46b-43a9-90d5-270d19424512">

**Comment by Kenshin** [comment]
😂

理论上虽然没关系，但你可以试试把同步助手转移到非应用程序文件夹中（是可以正常运行的）

**Comment by neolin0629** [comment]
还是不行，哈哈，没关系，可能就是哪里有一点点小小的问题。
基础的也够用啦，感谢你的解答。

**Comment by Kenshin** [comment]
小事情，也没帮到你。

主要是我也没招了，除了不能使用外一切测试过程都正常 😂
