### ISSUE TITLE
浮动面板如何调出？

### ISSUE THREAD

**Issue by hyjwonder** [Kenshin/simpread#6088]
### 请描述你的建议或任何内容

针对 阅读模式浮动面板定制器 #1601，具体什么时候会出现？怎么调出？还请作者明示。

**Comment by Kenshin** [comment]
<img width="689" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/72de4193-8fb9-4b1f-ad24-41e17e04e054">

这里描述的不清楚吗？点上图的 Icon 就行啊。

**Comment by hyjwonder** [comment]
Hi， 也许是我未表达清楚。我的问题是：在我的面板上，没有这个icon。请问在什么情况下，会出现这个icon？

**Comment by Kenshin** [comment]
如果使用了同步助手的自动同步功能，需要使用 https://www.yuque.com/kenshin/simpread/fcw60u

安装，每个插件的说明都有指出这点。

**Comment by hyjwonder** [comment]
您好，已按照说明尝试多次，无果。不知道什么原因。

**Comment by Kenshin** [comment]
1. 建议多回复下我的疑问，比如：你一直没有告诉我...是否使用了同步助手的自动同步？

2. 建议多截图或者录屏说明，这样给我的参考环境就比现在「一问一答」来的多... 😂

***

比如：我问你，A 好使么？你说不好使；然后我问你跟 A 相关的 B 好使吗？你说不好使，如果一次性多说些，会更精准的判断。
