### ISSUE TITLE
阅读模式下，原本规范的代码块变得不规范 ！！！

### ISSUE THREAD

**Issue by Colbyzn** [Kenshin/simpread#6089]
### 问题：

> 当我**选中原网页部分内容，右键进入阅读模式**时，原网页规范的代码块**被去掉了所有的换行符**，导致所有代码都在一行上显示；

> 而当我**不选中原网页任何内容，直接按下AA键进入阅读模式**时，虽然保留了原网页代码块的格式，但是**注释内容不见了**；

### 需求：

> 希望阅读模式下，代码块与原网页内的代码块格式及内容一致；

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/65213141/2f10f0ca-02a4-4a29-afc0-09b4540492f1)

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

https://www.frontendinterviewhandbook.com/zh/javascript-questions#%E5%92%8C%E7%9A%84%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88

**Comment by Kenshin** [comment]
嗨，这算是「预期」Bug 😂

代码段是一个很麻烦的事情，因为代码高亮规则太多了，没法统一，所以...

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

***

PS：图示不错，很棒 👍 
PPS：用是什么截（做）图 App？

**Comment by Colbyzn** [comment]
嗨，你好，感谢你的回复，谢谢你的赞赏，我使用的是FastStone截图软件

关于之前的问题：
我并没有安装代码段高亮的相关插件，对于使用【导出md + assets】功能的我来说并不需要，因为后续我会为代码块批量添加语言，然后使用prettier来格式化代码，因此，若注释内容和下一行代码挤在一行，之间没有换行符的话，是没办法正确格式化代码块的
补充：代码块都是使用<code>标签来包裹的，有些还会为该标签添加lang属性来标记其语言，我想能不能在使用【导出md + assests】功能时，也在三个反引号后面自动添加对应的语言，这样我就不需要后续再使用脚本来批量添加语言了

关于回复：
我阅读了 #500 内相关的issue，尝试使用【代码段增强插件】来解决该文章的代码块显示问题，但是效果依旧不理想，不同操作的显示结果如下：

* 选中部分内容，右键进入阅读模式 → 显示结果：依旧是内容完整，却单行显示；

* 不选中内容，按AA键进入阅读模式 → 显示结果：虽然修复了缺失的注释，但是格式丢失，变成了单行显示，而且显示位置错误；
　　
具体显示结果如下图所示：


从 Windows 版邮件发送

发件人: Kenshin Wang
发送时间: 2023年11月18日 13:13
收件人: Kenshin/simpread
抄送: Colbyzn; Author
主题: Re: [Kenshin/simpread] 阅读模式下，原本规范的代码块变得不规范 ！！！ (Issue #6089)

嗨，这算是「预期」Bug 😂
代码段是一个很麻烦的事情，因为代码高亮规则太多了，没法统一，所以...
代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

PS：图示不错，很棒 👍
PPS：用是什么截（做）图 App？

**Comment by Kenshin** [comment]
这个问题跟是否安装了 #500 无关，只是 #500 会优化各种代码段引起的问题的汇总而已 😂

至于有点「麻烦」的原因我说了，再简单的说，代码段并不都是使用 `<code>` 方案，即便使用了 `<code>` 也都不尽相同。

综上~  🌚 

PS：FastStone 可以做弧线的箭头了 👍

**Comment by Colbyzn** [comment]
我尝试了不同网站的代码块显示效果，确实如你所说，代码段是一个很麻烦的事情，有的网站正常显示，有的就不行，哈哈😂
看来只能后续进一步处理了
当然，也希望你能进继续优化代码块的显示效果
感谢的回复！

从 Windows 版邮件发送

发件人: Kenshin Wang
发送时间: 2023年11月18日 19:22
收件人: Kenshin/simpread
抄送: Colbyzn; Author
主题: Re: [Kenshin/simpread] 阅读模式下，原本规范的代码块变得不规范 ！！！ (Issue #6089)

这个问题跟是否安装了 #500 无关，只是 #500 会优化各种代码段引起的问题的汇总而已 😂
至于有点「麻烦」的原因我说了，再简单的说，代码段并不都是使用 <code> 方案，即便使用了 <code> 也都不尽相同。
综上~ 🌚
PS：FastStone 可以做弧线的箭头了 👍
