### ISSUE TITLE
字体效果会随主题颜色改变？(Question)

### ISSUE THREAD

**Issue by jkwtbmyz** [Kenshin/simpread#609]
左侧是默认主题，右侧是丁子色主题，为什么字体显示效果差距这么大呢？
另我使用插件的修改字体功能无效，跟这个有关吗？
![image](https://user-images.githubusercontent.com/17421620/68420532-7aea6700-01d7-11ea-8536-adaaccf4222f.png)

**Comment by Kenshin** [comment]
- 更换主题并不会更改字体。

- 更换字体的前提是，本机需要安装对应字体。

- 修改字体无效，会（极偶尔）出现在 Windows 某些 Chromium 浏览器，需要确保 ** Chrome （或扩展）没有更改过字体 某些 Chromium 变种有这种选项 ** 详细说明可以看看 https://github.com/Kenshin/simpread/issues/601

建议，详细告诉我你的环境，浏览器版本之类的信息。

**Comment by jkwtbmyz** [comment]
> * 更换主题并不会更改字体。
> * 更换字体的前提是，本机需要安装对应字体。
> * 修改字体无效，会（极偶尔）出现在 Windows 某些 Chromium 浏览器，需要确保 ** Chrome （或扩展）没有更改过字体 某些 Chromium 变种有这种选项 ** 详细说明可以看看 #601
> 
> 建议，详细告诉我你的环境，浏览器版本之类的信息。
> 
> PS：这是我按照你的对照，我截图的效果。另外，我个人喜欢「月白」的效果，你可以试试
> 
> <img alt="Xnip2019-11-08_10-26-14" width="2000" src="https://user-images.githubusercontent.com/81074/68444876-26fd7380-0213-11ea-82ab-920918d57182.png">

谢谢你如此迅速的回复跟解答。

- 我知道更换背景理应是不会修改字体的，但是你看我的截图，是左边视觉效果更好吧，我是想解决这个问题，我需要黄色的背景，但是显示效果不如纯白。

- 我试了全部主题，白练、卯之花色、黑鸢如上图左侧一般，其他主题都是右侧效果，线很细，不清楚。
- 即使这两个主题也有显示效果的差异，左侧白练，右侧卯之花色。
![QQ截图20191108161347](https://user-images.githubusercontent.com/17421620/68460429-d69e0a00-0242-11ea-9beb-71bdf52e7f1f.png)


- 我的环境是win10，版本 4.0.9.112（正式版本） （32 位） (Chromium 74.0.3729.169) Cent 浏览器外壳。

- 我现在首要想解决的是不同主题字体显示效果的问题，我提及切换字体失败只是希望能帮助解决问题，如果跟显示效果无关，那就不麻烦你就这个问题深入

- 不过我确实用了浏览器设置字体，虽然无效，然后我又用了Stylish插件修改字体，起作用了。提这个只是希望能让您排查故障，我现在不需要解决无法切换字体的问题，只希望能先解决显示效果的问题。

**Comment by Kenshin** [comment]
很抱歉给你带来了一些困扰，就目前而言，确实曾有 Win 下的用户反馈过字体问题，虽然都是个例。

很遗憾，截至到目前为止也没有什么确切的解决方案（主要是因为我没有遇到此问题，因此也无从下手...

另外，我目前在 Mac 下，在 Win 10 下面也使用 Cent 浏览器，并没有发生你说的问题。

目前能想到的几个解决办法：

- 安装 MacType 一个专门针对 Win 下面字体美化的工具；

- 试试其它浏览器，如：Vivaldi 等

- 你可以测试下在 Firefox or 其它Chromium 类浏览器下，是否仍旧存在此问题。

***

几个排查的方法：

- （暂时）恢复浏览器字体、系统等字体为默认设置；

- 允许 简悦 使用隐身模式；

- 禁止其它任何扩展使用隐身模式；

- 进入隐身模式，看看是否还存在这个问题？

***

至于你说的 `我的截图也存在相同问题`，应该只是字体大小不同造成的。

**Comment by jkwtbmyz** [comment]
> 很抱歉给你带来了一些困扰，就目前而言，确实曾有 Win 下的用户反馈过字体问题，虽然都是个例。
> 
> 很遗憾，截至到目前为止也没有什么确切的解决方案（主要是因为我没有遇到此问题，因此也无从下手...
> 
> 另外，我目前在 Mac 下，在 Win 10 下面也使用 Cent 浏览器，并没有发生你说的问题。
> 
> 目前能想到的几个解决办法：
> 
> * 安装 MacType 一个专门针对 Win 下面字体美化的工具；
> * 试试其它浏览器，如：Vivaldi 等
> * 你可以测试下在 Firefox or 其它Chromium 类浏览器下，是否仍旧存在此问题。
> 
> 几个排查的方法：
> 
> * （暂时）恢复浏览器字体、系统等字体为默认设置；
> * 允许 简悦 使用隐身模式；
> * 禁止其它任何扩展使用隐身模式；
> * 进入隐身模式，看看是否还存在这个问题？
> 
> 至于你说的 `我的截图也存在相同问题`，应该只是字体大小不同造成的。

谢谢 我会按照你的建议开始尝试。

**Comment by jkwtbmyz** [comment]
> 很抱歉给你带来了一些困扰，就目前而言，确实曾有 Win 下的用户反馈过字体问题，虽然都是个例。
> 
> 很遗憾，截至到目前为止也没有什么确切的解决方案（主要是因为我没有遇到此问题，因此也无从下手...
> 
> 另外，我目前在 Mac 下，在 Win 10 下面也使用 Cent 浏览器，并没有发生你说的问题。
> 
> 目前能想到的几个解决办法：
> 
> * 安装 MacType 一个专门针对 Win 下面字体美化的工具；
> * 试试其它浏览器，如：Vivaldi 等
> * 你可以测试下在 Firefox or 其它Chromium 类浏览器下，是否仍旧存在此问题。
> 
> 几个排查的方法：
> 
> * （暂时）恢复浏览器字体、系统等字体为默认设置；
> * 允许 简悦 使用隐身模式；
> * 禁止其它任何扩展使用隐身模式；
> * 进入隐身模式，看看是否还存在这个问题？
> 
> 至于你说的 `我的截图也存在相同问题`，应该只是字体大小不同造成的。

你好，问题解决了，某种程度上。

- 我试了Mactype，无效。此软件对大部分软件的字体都有改善效果，但是在浏览器里愣是看不出来，我也无力深究了。

- Vivaldi，Firefox，Chrome我都试了，无一例外，切换背景颜色都会导致文字显示效果改变，而且也是相同的某几种背景色能看，其他的都是发淡。

- 隐身模式也试过了，无效。

问题如何解决的？我安装了个你的插件，模仿 Safari 阅读模式样式，它自带淡棕色的背景色，我在主题色那里无论如何设置都是淡棕色，但是其中有几种主题色下的汉字显示正常。
即 主题色白练 = 背景白色 + 正常文字显示， 插件 = 背景淡棕色， 插件 + 主题白练 = 背景淡棕色 + 正常文字显示

我想，两种对背景颜色修改的方式导致了结果的不同，软件本体的背景色修改影响文字显示效果，插件里的背景色修改却不会。

至少我现在能开心用起来了。

希望我的经验能给你提供一点思路。

谢谢楼主！

**Comment by jkwtbmyz** [comment]
> 很抱歉给你带来了一些困扰，就目前而言，确实曾有 Win 下的用户反馈过字体问题，虽然都是个例。
> 
> 很遗憾，截至到目前为止也没有什么确切的解决方案（主要是因为我没有遇到此问题，因此也无从下手...
> 
> 另外，我目前在 Mac 下，在 Win 10 下面也使用 Cent 浏览器，并没有发生你说的问题。
> 
> 目前能想到的几个解决办法：
> 
> * 安装 MacType 一个专门针对 Win 下面字体美化的工具；
> * 试试其它浏览器，如：Vivaldi 等
> * 你可以测试下在 Firefox or 其它Chromium 类浏览器下，是否仍旧存在此问题。
> 
> 几个排查的方法：
> 
> * （暂时）恢复浏览器字体、系统等字体为默认设置；
> * 允许 简悦 使用隐身模式；
> * 禁止其它任何扩展使用隐身模式；
> * 进入隐身模式，看看是否还存在这个问题？
> 
> 至于你说的 `我的截图也存在相同问题`，应该只是字体大小不同造成的。

- 我试了Mactype，无效。此软件对大部分软件的字体都有改善效果，但是在浏览器里愣是看不出来，我也无力深究了。

- Vivaldi，Firefox，Chrome我都试了，无一例外，切换背景颜色都会导致文字显示效果改变，而且也是相同的某几种背景色能看，其他的都是发淡。

- 隐身模式也试过了，无效。

我的想法是，你的截图里左右两个主题下的“发现问题”字体大小不同，即切换主题确实会导致字体某些方面的变化，而不是毫无关联。我想这个机制可能跟导致我这边主题影响字体效果的机制是类似的，能否从这里入手呢？

**Comment by jkwtbmyz** [comment]
> 很抱歉给你带来了一些困扰，就目前而言，确实曾有 Win 下的用户反馈过字体问题，虽然都是个例。
> 
> 很遗憾，截至到目前为止也没有什么确切的解决方案（主要是因为我没有遇到此问题，因此也无从下手...
> 
> 另外，我目前在 Mac 下，在 Win 10 下面也使用 Cent 浏览器，并没有发生你说的问题。
> 
> 目前能想到的几个解决办法：
> 
> * 安装 MacType 一个专门针对 Win 下面字体美化的工具；
> * 试试其它浏览器，如：Vivaldi 等
> * 你可以测试下在 Firefox or 其它Chromium 类浏览器下，是否仍旧存在此问题。
> 
> 几个排查的方法：
> 
> * （暂时）恢复浏览器字体、系统等字体为默认设置；
> * 允许 简悦 使用隐身模式；
> * 禁止其它任何扩展使用隐身模式；
> * 进入隐身模式，看看是否还存在这个问题？
> 
> 至于你说的 “我的截图也存在相同问题”，应该只是字体大小不同造成的。

一个潜在的解决方案需要您的帮助：

我安装了“模仿 Safari 阅读模式样式”这个插件，我发现它的使用情况是在开启这个插件的条件下切换本体的背景色，不会立即生效，而是重新打开一次插件之后才会应用上新的背景色，即：
我当前设置的背景色是白色，我进入阅读模式，切换成浅棕色，此时不会立即生效，我退出阅读模式，再打开，就是浅棕色背景色。

利用这一点我发现：当我背景色是浅棕色的时候，我进入阅读模式，然后切换背景色为白色，此时背景色不会立即变化，但是字体显示效果会立即随着背景色设置改变而改变，从而达到了我想要达到的 浅棕色背景 + 正常文字显示。

![image_1](https://user-images.githubusercontent.com/17421620/68527383-1affd780-0321-11ea-8e64-35dc2cc55761.png)
（此时背景色是浅棕色因为进入阅读模式之前的主题色设置是浅棕色，我进入阅读模式之后切换背景色为白练，字体效果立即随之改变，变好了，但是背景色依旧是浅棕色）

但是这是无法重现的，因为我一旦切换了背景色为白色，下次再进入阅读模式，背景色就真的是白色了。

为何本体切换背景色的时候，实际的背景色还未切换，字体显示效果就先一步改变了？

您能否根据我描述的情况，提供一个临时或者哪怕很简陋的设定，能让我实现 浅棕 + 正常字体显示 这样的效果？ 比如这个“模仿 Safari 阅读模式样式” 里应该是有一个读取当前背景色设定的步骤，我定死为棕色，然后我本体的背景色设定成白练，那么应该能做到进入阅读模式后 背景色浅棕 + 白练对应的字体显示（正常）的效果。

我不是很懂编程，希望您别介意。

**Comment by Kenshin** [comment]
你的意思是：默认的主题字体设置你比较满意，但希望浅色的背景色？

**Comment by jkwtbmyz** [comment]
如果你说的浅色背景是指 浅棕色，那我就是这个意思。


白色背景下字体显示正常，但是切换棕色背景下字体显示就不好了，我现在想要用棕色背景。




------------------ 原始邮件 ------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 上午10:48
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"Sean"<865074228@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 字体效果会随主题颜色改变？(Question) (#609)




你的意思是：默认的主题字体设置你比较满意，但希望浅色的背景色？

**Comment by Kenshin** [comment]
请把如下代码加入

```
.simpread-theme-root, .simpread-multi-root {
    background-color: rgb(252, 245, 237);
}
```

选项页 → 高级设定 → 自定义样式 → 自定义 CSS 中

就会出现下图效果

![image](https://user-images.githubusercontent.com/81074/68729824-fbf59400-0605-11ea-8b57-7dfe8b9723c3.png)

**Comment by jkwtbmyz** [comment]
> .simpread-theme-root, .simpread-multi-root {
>     background-color: rgb(252, 245, 237);
> }

老哥你太棒咯，问题解决了~

已“请你喝咖啡”聊表心意。

不过还是想多嘴问下，你这个代码里直接设定background color跟 设置里面的修改背景色有什么区别？是这个代码的修改无法实时显示？我觉得如果很多人反馈修改背景色会影响字体显示，那不如就用这个修改方式。

祝好~

**Comment by jkwtbmyz** [comment]
> 请把如下代码加入
> 
> ```
> .simpread-theme-root, .simpread-multi-root {
>     background-color: rgb(252, 245, 237);
> }
> ```
> 
> 选项页 → 高级设定 → 自定义样式 → 自定义 CSS 中
> 
> 就会出现下图效果
> 
> ![image](https://user-images.githubusercontent.com/81074/68729824-fbf59400-0605-11ea-8b57-7dfe8b9723c3.png)

你好，似乎无法跟“模仿Safari阅读样式”共用，这个插件有自己的逻辑会掩盖我设定的背景色。
另，这个插件在知乎网站会导致内容“双重效果”，如图：
![image_3](https://user-images.githubusercontent.com/17421620/68784878-3e57b900-0678-11ea-80d0-efb7b579e342.png)
本来不用这个插件的效果已经挺好的了：
![image_5](https://user-images.githubusercontent.com/17421620/68785187-bd4cf180-0678-11ea-9a98-adff8453403c.png)


这个插件是否可以设置一个白名单？或者如果说当前页面已经有格式优化，就不加载自身的优化。

多谢！

**Comment by Kenshin** [comment]
> 不过还是想多嘴问下，你这个代码里直接设定background color跟 设置里面的修改背景色有什么区别？是这个代码的修改无法实时显示？我觉得如果很多人反馈修改背景色会影响字体显示，那不如就用这个修改方式。

简单的说，主题包含了：字体大小、背景色、前景色、字体样式，段落间距等等。

对于你来说，不是很喜欢 `丁子色` 的主题，但也并不喜欢 `默认主题` 的背景色，所以我通过自定义样式把 `丁子色` 的背景色 加入到了  `默认主题` 。

***

至于你最后一个问题，如果你对 `模仿Safari阅读样式` 不感兴趣的话，可以删除它，并使用之前的方式即可。

PS：☕不错，谢谢~

PPS：个人感觉，你还是需要类似 Mac Type 这类工具来渲染下 Windows 的全局字体效果。 😀 

PPPS：没疑问的话，我将关闭这个 issues 有需要再重新开启~
