### ISSUE TITLE
希望不进入阅读模式也可以使用简阅的其他功能，例如高亮标记之类的

### ISSUE THREAD

**Issue by haolly** [Kenshin/simpread#6090]
### 请描述你的建议或任何内容

试想一下，你用简阅看了一篇文章，退出阅读模式之后发现还有很多内容没有看到，，你基本就会在心里WTF了，如果只是不重要的信息还好，如果是重要的信息，那后果可想而知

**Comment by Kenshin** [comment]
嗨

1. 简悦是基于阅读模式的产品

2. 简悦的阅读模式主要分为：主动适配或者自动识别，无论哪种情况都是在具有大量图文的前提下。

所以

1. 有深度阅读诉求的页面才使用阅读模式，而不是什么页面都要使用。

2. 当有深度诉求的页面没有完美获取正文的话，你可以使用 https://github.com/Kenshin/simpread/discussions/3340  https://github.com/Kenshin/simpread/discussions/1554 来解决 99.9999% 的「问题」页面都能解决。

3. 如果前两点无法满足你的需求，可以提交给我，如果确实如此，简悦会主动适配这类页面。
