### ISSUE TITLE
发现进入阅读模式后屏幕无法滚动的网站

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#6094]
### 描述这个错误

如题

### 复现步骤

打开进入阅读模式

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

https://publish.obsidian.md/thesaurus/%E8%8B%B1%E8%AF%AD%E8%AF%8D%E4%B9%89%E5%88%86%E7%B1%BB%E6%95%B0%E6%8D%AE%E5%BA%93%EF%BC%88%E5%A4%A7%E5%AD%A6%E7%89%88%EF%BC%89/0%E6%9C%AC%E8%B5%84%E6%96%99%E5%BA%93%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF/%E8%87%B4%E7%BD%91%E5%8F%8B

**Comment by Kenshin** [comment]
嗨，我这边没有这个问题，不过你可以试试将下面的代码

```
html.simpread-font {
    overflow: initial!important;
}
```

加入到下图所示的地方，保存后重启浏览器

<img width="470" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3d0832e1-890a-4cbb-8939-c6eaad596ac6">

**Comment by PupupupuTong** [comment]
加进去之后可以滚动了，但是第一次打开总会弹出这个

![image](https://github.com/Kenshin/simpread/assets/69069739/fcb9e4f1-fcd9-4d4a-bdb7-e7fa751ab4f8)

**Comment by Kenshin** [comment]
因为这个站没有适配，且是动态加载。

你可以用划取的方式获取正文。
