### ISSUE TITLE
自动化同步失败

### ISSUE THREAD

**Issue by yuanming1** [Kenshin/simpread#6095]
### 描述这个错误

配置自动化导出成html，执行加入稍后读，无法执行，并且配置的自动化配置也会跟着消失

### 复现步骤

1.配置自动化方案
<img width="941" alt="image" src="https://github.com/Kenshin/simpread/assets/11457518/987f651d-255e-4f40-b8f1-aceac2fade94">
2.加入稍后读
<img width="1058" alt="image" src="https://github.com/Kenshin/simpread/assets/11457518/9712e269-1ca4-407f-8afd-20cfac56f32b">
3.执行失败
4.回头看自动化配置
<img width="1091" alt="image" src="https://github.com/Kenshin/simpread/assets/11457518/45fc1a5b-d61d-4b4a-9f5e-2a7e42c63a8d">

### 操作系统

macos

### 浏览器

chrome 116.0.*.* 版本

### 发生问题的网址

https://zhuanlan.zhihu.com/p/490737372

**Comment by Kenshin** [comment]
嗨，加入稍后读并触发自动化的条件：

1. 进入阅读模式

2. 使用快捷键 `d d` 加入稍后读才能触发自动化
