### ISSUE TITLE
高级账户购买后未收到授权码

### ISSUE THREAD

**Issue by zanchangtong** [Kenshin/simpread#6096]
### 描述这个错误

信息：支付宝付款单号后六位 698267，11月17日付款。
问题：未收到激活码，付款时提交的UID账户也未激活高级账户权限。

### 复现步骤

略

### 操作系统

windows

### 浏览器

chrome

### 发生问题的网址

略

**Comment by zanchangtong** [comment]
正常渠道是从邮件发送激活码吗？需要做的是继续等待几天吗？

**Comment by Kenshin** [comment]
你的邮件早就发了，你在腾讯问卷填写的邮件是 `chan****zan@gmail.com`

<img width="691" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d2b26cfc-bfd6-408d-960a-20a8e929f1cb">
