### ISSUE TITLE
cloudinary 图床远征失败

### ISSUE THREAD

**Issue by name2500** [Kenshin/simpread#6098]
### 描述这个错误

开了高级账号。注册了Cloudinary，我确定从dashboard复制了正确的信息。但是验证图床时总是保存失败。不知道什么原因，是cloudinary需要做额外设置么？
<img width="648" alt="194e199ab924714aee946e5b68ce82b" src="https://github.com/Kenshin/simpread/assets/48666580/cf82b8e0-a7a8-4e30-8e6a-89ff529a4df1">

### 复现步骤

打开阅读模式
关闭NOTION图床
打开Cloudinary 图床
填写Dashboard信息
验证图床
弹失败

### 操作系统

WINDOWS

### 浏览器

Edge

### 发生问题的网址

https://sspai.com/post/84504

**Comment by name2500** [comment]
填写了文件夹名称成功

**Comment by LBR-13** [comment]
> 填写了文件夹名称成功

+ 1
空着的话验证一直失败

**Comment by Kenshin** [comment]
@LBR-13 

emmm 我明天确认下，如果是的话，需要优化下～
