### ISSUE TITLE
请问标注的上限是多少？

### ISSUE THREAD

**Issue by zqz365001** [Kenshin/simpread#6099]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/27180737/de4e28d2-a7e8-4d86-956a-d6652ea94634)

目前标注2080个帖子，json配置文件是2023年11月20日的，我是最早的用户了，出现问题也是协同解决。请问标注的上限是多少，我的简悦现在出现了问题，标注能标注到备份的html，如上图，但是按aa键，原先的标注继续标注，就不见了，像是初始状态一样。恢复到如下图的2023年9月12号的json，禁用插件 两种方式 都不起作用。

![image](https://github.com/Kenshin/simpread/assets/27180737/89ab3963-3a04-4bff-ae48-63b955acae3a)

使用和禁用的插件如下图：
![image](https://github.com/Kenshin/simpread/assets/27180737/492fdd85-c603-4f86-9e73-0970b6a9dad0)
![image](https://github.com/Kenshin/simpread/assets/27180737/7167d382-c7d9-4229-86c1-9b649196e79f)

obsidian版本如下图：
![image](https://github.com/Kenshin/simpread/assets/27180737/d5833539-4c75-4d55-b61b-3c9feda43e58)

### 复现步骤

按 aa，标注后，能获取到html标注文件，在obsidian中能获取到md文件，但是edge浏览器中按 aa 接着已标注，发现原先标注的内容并没有出现，像是 没有被标注一样，请问如何解决？

抽样早期的标注帖子，500、850,、1500、1800发现 按 aa 快捷键，原先标注的知识点都不见了，备份的html和obsidian中的md文件还在。这就很神奇了，等于说当前标注和以前标注的知识点都不见了，不知道如何解决了。。。

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)

### 发生问题的网址

https://blog.csdn.net/qq_33377547/article/details/126596652

**Comment by Kenshin** [comment]
> 请问标注的上限是多少

没有任何上限 （或者说，为什么要有上限限制，不合理  😂

> 但是按aa键，原先的标注继续标注，就不见了

你的意思是，在存在标注的页面，进入阅读模式后没有标注？

如果是这种情况的话，我怀疑可能是你的配置文件有错误造成的，你可以使用 https://github.com/Kenshin/simpread/discussions/5750 提到的方式修复下配置文件。

注意：

1. 先暂停坚果云的同步。
2. 确保你的数据是最新的（因为我看到你提到了还原过一次配置文件）
3. 无论是否是最新的配置文件，都建议手动备份 `simpread_config.json` 到本地的非坚果云的任意位置。

> 按 aa，标注后，能获取到html标注文件，在obsidian中能获取到md文件，但是edge浏览器中按 aa 接着已标注，发现原先标注的内容并没有出现，像是 没有被标注一样，请问如何解决？

还有个情况也能造成这种现象：你安装了某些会干扰阅读模式结构的插件，但我不确定，最好的排除方案：在隐私模式下，仅启用简悦，然后进入阅读模式 → 快捷键 `d d` 加入稍后读 → 开始标注 → 刷新页面（隐私页面），然后再次进入阅读模式。

> 抽样早期的标注帖子，500、850,、1500、1800发现 按 aa 快捷键，原先标注的知识点都不见了，备份

1. 比如标号 500 的本地快照存在吗？
2. 你进入的原页面？还是稍后读发现标注不存在的？

***

PS：如果还是有问题的话，可以把配置文件发给我（也一样能解决）
PPS：只要你的本地快照和 `simpread_config.json` 就说明你的数据没有丢失，没有丢失的话，就都可以解决。
PPPS：这就是基于本地数据系统的好处。

**Comment by Kenshin** [comment]
补充下：

你试试直接打开稍后读，看下稍后读能否正常加载，如果能的话，大概率不是因为配置文件损坏造成的，而是因为其它扩容的干扰。

先排除掉是哪种问题造成的，然后就可以很容易解决它。

**Comment by zqz365001** [comment]
> > 请问标注的上限是多少
> 
> 没有任何上限 （或者说，为什么要有上限限制，不合理 😂
> 
> > 但是按aa键，原先的标注继续标注，就不见了
> 
> 你的意思是，在存在标注的页面，进入阅读模式后没有标注？
> 
> 如果是这种情况的话，我怀疑可能是你的配置文件有错误造成的，你可以使用 #5750 提到的方式修复下配置文件。
> 
> 注意：
> 
> 1. 先暂停坚果云的同步。
> 2. 确保你的数据是最新的（因为我看到你提到了还原过一次配置文件）
>
 3. 无论是否是最新的配置文件，都建议手动备份 `simpread_config.json` 到本地的非坚果云的任意位置。
> 

> > 按 aa，标注后，能获取到html标注文件，在obsidian中能获取到md文件，但是edge浏览器中按 aa 接着已标注，发现原先标注的内容并没有出现，像是 没有被标注一样，请问如何解决？
> 
> 还有个情况也能造成这种现象：你安装了某些会干扰阅读模式结构的插件，但我不确定，最好的排除方案：在隐私模式下，仅启用简悦，然后进入阅读模式 → 快捷键 `d d` 加入稍后读 → 开始标注 → 刷新页面（隐私页面），然后再次进入阅读模式。
> 
> > 抽样早期的标注帖子，500、850,、1500、1800发现 按 aa 快捷键，原先标注的知识点都不见了，备份
> 
> 1. 比如标号 500 的本地快照存在吗？
> 2. 你进入的原页面？还是稍后读发现标注不存在的？
> 
> PS：如果还是有问题的话，可以把配置文件发给我（也一样能解决） PPS：只要你的本地快照和 `simpread_config.json` 就说明你的数据没有丢失，没有丢失的话，就都可以解决。 PPPS：这就是基于本地数据系统的好处。


还原过一次配置文件了，没还原的配置文件错误更离谱，标注后，稍后读界面 那边页面没有被记录，而且每次重新打开edge，都是从2073开始标序号，其他的问题就没测，所以才还原到2023年9月12日的json，才发现只有这一个问题，才上来提问的

>>你的意思是，在存在标注的页面，进入阅读模式后没有标注？
是这样的。

>>>抽样早期的标注帖子，500、850,、1500、1800发现 按 aa 快捷键，原先标注的知识点都不见了，备份
>>比如标号 500 的本地快照存在吗？
>>你进入的原页面？还是稍后读发现标注不存在的？
原先的本地快照和md文件都在，就是进入阅读模式，发现标注的内容不见了，像是重新开始了一样。

如果能修复2023年11月20日昨天的配置文件最好了。不然只能修复2023年9月12日的配置文件，试试关闭edge的插件试试，然后再修复下json的配置文件看看，

**Comment by zqz365001** [comment]
> 补充下：
> 
> 你试试直接打开稍后读，看下稍后读能否正常加载，如果能的话，大概率不是因为配置文件损坏造成的，而是因为其它扩容的干扰。
> 
> 先排除掉是哪种问题造成的，然后就可以很容易解决它。

我昨天2023年11月20日的配置文件，是可以打开稍后读的，但是记录的帖子对应的序号是2072，新标注帖子不记录。每次打开edge浏览器都是从2073开始。。。
所以才还原到2023年9月12日的配置文件，不能直接打开稍后读，但是可以通过先进入偏好设置，然后打开稍后读，再单击 返回按钮，进入稍后读，从中可以看到帖子对应的序号是从1861开始

**Comment by Kenshin** [comment]
嗨

1. 留意下 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820143832 提到的两个地方。

2. https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820148267 你的回复有点乱（ Github 造成的），所以把没有的信息删除下，主要是我没看懂...


> 如果能修复2023年11月20日昨天的配置文件最好了。不然只能修复2023年9月12日的配置文件，试试关闭edge的插件试试，然后再修复下json的配置文件看看，

使用我提到的方式都可以修复，但理论上应该修复最新的配置文件，无论是哪个配置文件，改名为 `simpread_config.json` 然后使用我提到的方式修复。

**Comment by zqz365001** [comment]
> 嗨
> 
> 1. 留意下 [请问标注的上限是多少？ #6099 (comment)](https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820143832) 提到的两个地方。
> 2. [请问标注的上限是多少？ #6099 (comment)](https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820148267) 你的回复有点乱（ Github 造成的），所以把没有的信息删除下，主要是我没看懂...
> 
> > 如果能修复2023年11月20日昨天的配置文件最好了。不然只能修复2023年9月12日的配置文件，试试关闭edge的插件试试，然后再修复下json的配置文件看看，
> 
> 使用我提到的方式都可以修复，但理论上应该修复最新的配置文件，无论是哪个配置文件，改名为 `simpread_config.json` 然后使用我提到的方式修复。

还原过一次配置文件了，2023年11月20日昨天出错的，配置文件错误更离谱，标注后，稍后读界面 那边页面没有被记录，稍后读记录的帖子对应的序号是2072，每次重新打开edge，都是从2073开始标序号，其他的问题就没测，所以才还原到2023年9月12日的json，序号是从 1861开始的，才发现只有这一个问题，才上来提问的

你的意思是，在存在标注的页面，进入阅读模式后没有标注？

是这样的。

抽样早期的标注帖子，500、850,、1500、1800发现 按 aa 快捷键，原先标注的知识点都不见了，备份

比如标号 500 的本地快照存在吗？
你进入的原页面？还是稍后读发现标注不存在的？

原先的本地快照和md文件都在，就是进入阅读模式，发现标注的内容不见了，像是重新开始了一样。

如果能修复2023年11月20日昨天的配置文件最好了。不然只能修复2023年9月12日的配置文件，试试关闭edge的插件试试，然后再修复下json的配置文件看看，

**Comment by Kenshin** [comment]
我现在要出去下，下午才能回复你。

***

### 首先

先确保使用我提到的方式修改好配置文件（假设配置文件有问题），然后不要纠结 2072 / 2073 的问题，按照你的描述顶多就是丢了 2073（我不知道你在标注时，是否开了坚果云，否则理论上也不会丢失）

只有配置文件没有问题，即你可以正常的标注，测试方式：

**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰，也就是我提到的这个方式

<img width="826" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b54d2a7c-f43c-4efc-ae83-6d3eac17495b">

确保你可以正的添加稍后读和标注。

### 接下来

然后再看其它问题。

**Comment by zqz365001** [comment]
> 我现在要出去下，下午才能回复你。
> 
> ### 首先
> 先确保使用我提到的方式修改好配置文件（假设配置文件有问题），然后不要纠结 2072 / 2073 的问题，按照你的描述顶多就是丢了 2073（我不知道你在标注时，是否开了坚果云，否则理论上也不会丢失）
> 
> 只有配置文件没有问题，即你可以正常的标注，测试方式：
> 
> **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰，也就是我提到的这个方式
> 
> <img alt="image" width="826" src="https://user-images.githubusercontent.com/81074/284453525-b54d2a7c-f43c-4efc-ae83-6d3eac17495b.png">
> 确保你可以正的添加稍后读和标注。
> 
> ### 接下来
> 然后再看其它问题。

没开坚果云，一直开syncthing，不过没同步简悦的快照，目前在空转

**Comment by Kenshin** [comment]
修复好了告诉我，修复好的标准：

1. 稍后读可以正常打开
2. 可以正常添加稍后读以及标注。

等这个完毕后，再看下你提到的无法恢复标注的问题。

**Comment by zqz365001** [comment]
使用修复工具修复了2023年9月12日的配置文件，发现正常了。
为何用这个配置文件呢？主要是昨晚修改了不少标注文件，不能用2023年11月20日的配置文件了，需要手动重新标注帖子。
但也带来一个问题，obsidian的同步配置脚本不见了，使用2023年11月20日的配置文件，发现obsidian的同步配置脚本也是空的，请问如何解决呢？
![image](https://github.com/Kenshin/simpread/assets/27180737/58ec242e-b16f-4d2f-8a8c-bc2320bfaa2a)

**Comment by zqz365001** [comment]
> 修复好了告诉我，修复好的标准：
> 
> 1. 稍后读可以正常打开
> 2. 可以正常添加稍后读以及标注。
> 
> 等这个完毕后，再看下你提到的无法恢复标注的问题。



使用修复工具修复了2023年9月12日的配置文件，发现正常了。
为何用这个配置文件呢？主要是昨晚修改了不少标注文件，不能用2023年11月20日的配置文件了，需要手动重新标注帖子。
但也带来一个问题，obsidian的同步配置脚本不见了，载入2023年11月20日的配置文件或者2023年9月12日的配置文件，发现obsidian的同步配置脚本也是空的，请问如何解决呢？如下图
![image](https://github.com/Kenshin/simpread/assets/27180737/58ec242e-b16f-4d2f-8a8c-bc2320bfaa2a)

**Comment by zqz365001** [comment]
补充说明一下：由于修改了下面的脚本，所以不适用了
![9b1ade467207e6d58a8082dd1b14b8e0](https://github.com/Kenshin/simpread/assets/27180737/ac599a39-a968-4c2e-8b75-42a8f59f83b4)

**Comment by zqz365001** [comment]
搞的我头大啊，请问怎么解决呢？工作半天展不开，被这个事情搞的无语 了。。。。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820277461

如果只是这一个的话，重新复制/粘贴一份就行了，你用的哪种模板？有没有改过模板？

**Comment by Kenshin** [comment]
你其它的插件配置也没有了吗？

应该是你昨天操作造成的，如果不是昨天的操作，应该很容易回复和解决...

不过也问题不大，把 `2023年11月20日` 的配置文件和你已修复的为基准的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6099

只要是你的配置文件（标注和稍后读）数据还在，配置数据不是多大的问题。

**Comment by Kenshin** [comment]
😂

1. 在配置文件有错误的前提下改模板
2. 在配置文件错误的前提下使用 9月份的数据

并不是这套工具维护成本大，而是当你（用户）发生问题的后，最好的方法是联络我，并不是每个用户都遇到这个问题，所以对于我来说，帮用户解决这些问题是最快速有效的途径。

**Comment by zqz365001** [comment]
> 😂
> 
> 1. 在配置文件有错误的前提下改模板
> 2. 在配置文件错误的前提下使用 9月份的数据
> 
> 并不是这套工具维护成本大，而是当你（用户）发生问题的后，最好的方法是联络我，并不是每个用户都遇到这个问题，所以对于我来说，帮用户解决这些问题是最快速有效的途径。

已发。
![049E752A](https://github.com/Kenshin/simpread/assets/27180737/9f2a2784-15f0-4531-b494-3f418fe3a5c4)
，好歹也搬砖

**Comment by Kenshin** [comment]
我一直在很积极的帮你，因为我看到截图有至少 2k 的稍后读数据，你也说是老用户了。

但你昨天在错误的环境中做的很多改动有可能会让这个错误更麻烦，原本可能就是配置文件错了，用我提到的方式修复下就完事了。

而你用了 9月份的数据，我不知道 9月份到现在你是否有更新新的内容。

理论上也无所谓，之前说了只要是配置文件在就都丢不了。

***

唯一麻烦的是你昨天在错误配置文件的基础上的改动可能都没有了。

我现在看下你的数据，有消息我会告诉你。

**Comment by Kenshin** [comment]
你给了我两个文件

- `simpread_config4`
- `simpread_config最新` 

告诉我这两个文件都是什么，以哪个为基准？

**Comment by zqz365001** [comment]
是因为之前就有 稍后读错误，然后也是 使用以前的配置文件，然后用笨方法标注好了。搬砖的喜欢动手咯

**Comment by zqz365001** [comment]
最新是修复好的，4是之前的

**Comment by zqz365001** [comment]
修复好的，插件数据为空

**Comment by zqz365001** [comment]
4是之前的我加载，也显示插件数据为空

**Comment by zqz365001** [comment]
> 我一直在很积极的帮你，因为我看到截图有至少 2k 的稍后读数据，你也说是老用户了。
> 
> 但你昨天在错误的环境中做的很多改动有可能会让这个错误更麻烦，原本可能就是配置文件错了，用我提到的方式修复下就完事了。
> 
> 而你用了 9月份的数据，我不知道 9月份到现在你是否有更新新的内容。
> 
> 理论上也无所谓，之前说了只要是配置文件在就都丢不了。
> 
> 唯一麻烦的是你昨天在错误配置文件的基础上的改动可能都没有了。
> 
> 我现在看下你的数据，有消息我会告诉你。

感受到了，谢谢你，王佬

**Comment by Kenshin** [comment]
确实如此，这两个文件的 `plugstorge` （插件配置）都是空的。

你找到一个最近的 `plugstorge` 有数据的历史记录，用任意文本编辑器打开检索下就能知道是否有数据了，有数据的话类似下图

<img width="479" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d7641efe-44b6-4d1a-a2af-eadb86ccc691">

如果你闲麻烦，只要找到这个数据就行，我来帮你手动合并。

***

假设找不到任何数据也无所谓，我看了下你的这些插件：Obsidian 相关联的插件，用默认的那套即可，**唯独阅读助手需要你自己重新配置下**。

**Comment by zqz365001** [comment]
脑子现在有点晕。我按照obsidian中的简悦插件的脚图1 本来配置 图2的插件可以吗？
![image](https://github.com/Kenshin/simpread/assets/27180737/c1c1c628-9509-43df-854b-8c43f94ad59e)
![image](https://github.com/Kenshin/simpread/assets/27180737/9a47f296-af98-43c7-bc30-21d719646e6a)

**Comment by Kenshin** [comment]
> 按照obsidian中的简悦插件的脚图1 本来配置 图2的插件可以吗？obsidian中的插件是我修改后的模版

可以，它们是同一个引擎，我在文档中有说明

***

但其它插件的配置还是空的，所以还是需要找到插件的配置给我，实在不行就用默认的，让你先恢复到正常能用，然后把 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820388375 的模板复制给插件。

**Comment by zqz365001** [comment]
早期用户，经历了版本迭代，已经记不清配置了。。。现在靠着复制粘贴匹配简悦了 
![04BB5496](https://github.com/Kenshin/simpread/assets/27180737/3b46bf85-bedb-492a-b8a8-2d9f9bc0590c)

**Comment by Kenshin** [comment]
这样吧，我先帮你恢复插件到默认值，然后你先确保可以正常使用，当正常使用后再把 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820388375 Obsidian 的模板复制给简悦这边就 OK 了。

或者你现在把 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820388375 Obsidain 模板给我，我帮你确认下是否可用也行，这样你在操作时能少几个步骤。

**Comment by zqz365001** [comment]
我已经配置好了所有插件了，现在在测试一下

**Comment by Kenshin** [comment]
> 我已经配置好了所有插件了，现在在测试一下

嗯？不用我了？

**Comment by zqz365001** [comment]
暂时麻这么多了，我也是搞软件的，需要帮忙再请教。谢谢你
![04C4C8EF](https://github.com/Kenshin/simpread/assets/27180737/dfe81b08-9947-404d-a7bd-f9813bf77ebb)

**Comment by zqz365001** [comment]
md在obsidian中生成还不行，测试了两次，ε=(´ο｀*)))唉。那太感谢了

**Comment by zqz365001** [comment]
配置好的文件麻烦发一下，谢谢 zqz365011@qq.com，尝试了很多次生成到obsidian，可能配置文件不对，还是不行

**Comment by zqz365001** [comment]
麻烦发一下配置文件，zqz365011@qq.com，多次配置不成功。。。

**Comment by Kenshin** [comment]
邮件发了，细节看 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820430736 的说明。

至于你提到的 Obsidian 问题，留意下你的 Obsidian 库和文件夹名称与下图是否一致。

<img width="627" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1a3b04c6-e15b-4177-924f-c29333926f0a">

同时测试步骤也在 https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820430736 

在有标注的页面也可以测试下  Markdown 模板 看下图所示

<img width="1116" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a9d90656-0869-4bfb-bdde-422ae36a6fc5">

**Comment by zqz365001** [comment]
大佬，使用你发过来的配置文件，发现按aa键，继续标注，之前的标注内容还是消失的。。。

**Comment by zqz365001** [comment]
> 邮件发了，细节看 [#6099 (comment)](https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820430736) 的说明。
> 
> 至于你提到的 Obsidian 问题，留意下你的 Obsidian 库和文件夹名称与下图是否一致。
> 
> <img alt="image" width="627" src="https://user-images.githubusercontent.com/81074/284546353-1a3b04c6-e15b-4177-924f-c29333926f0a.png">
> 同时测试步骤也在 [#6099 (comment)](https://github.com/Kenshin/simpread/issues/6099#issuecomment-1820430736)
> 
> 在有标注的页面也可以测试下 Markdown 模板 看下图所示
> 
> <img alt="image" width="1116" src="https://user-images.githubusercontent.com/81074/284547276-a9d90656-0869-4bfb-bdde-422ae36a6fc5.png">

收到，已经能正常生成obsidian的md文档了，感谢

**Comment by Kenshin** [comment]
> 只不过现在按aa键，继续标注，之前标注的内容不能显示，修复检测也显示没有问题

你试试开启下面的选项

<img width="1051" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e3cb0590-7ded-4ad4-8865-2aaa3f30dcf7">

**Comment by zqz365001** [comment]
**谢谢**，
![007C3FEC](https://github.com/Kenshin/simpread/assets/27180737/756b9f97-c7f7-4f8b-8214-c55f0db830f6)
。
提一个小小的建议哈：万事万物都有2/8法则。20%内容 有80%常用且重要性，80%内容 有20%重要性。建议贴合一下大多数人的配置习惯，分出若干 符合常用配置文件模版，相当一个demo，傻瓜快餐化入门。

而对于有需求的人，则方便按照已经配置好的界面和大佬写的文档，进行DIY，降低心智焦虑。

**Comment by Kenshin** [comment]
哈，解决就好。

一直都有配置库的 https://www.yuque.com/kenshin/simpread/ds8zk0 也细分了很多方案。

一般来说轻量级使用简悦（尤其是仅阅读模式）不需要了解太多东西，拿来就用。只有笔记用户才需要这些。

***

老用户的话 + QA 了这么久，在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 蹲个五星 + 好评 😉😁👍

**Comment by zqz365001** [comment]
edge五星好评了，谢谢大佬

**Comment by Kenshin** [comment]
Cool~ 👍
