### ISSUE TITLE
您好，你做的很好，对我帮助很大，我想赞助发现二维码显示不全

### ISSUE THREAD

**Issue by wvisible** [Kenshin/simpread#61]

**Comment by Kenshin** [comment]
感谢捐赠~
额，我在外面，放二维码的时候测试过，应该没问题。请问是哪个付款码有问题？

**Comment by wvisible** [comment]
我这里看到的是二维码图片显示不全，二维码图片只显示了一小半，不知道是不是我的网络问题，同事那里看到也只显示一半

**Comment by Kenshin** [comment]
很感谢为此这么耐心的举动。 :+1: :+1: :+1:
有可能是你网络的问题，之前其他人的捐赠都没有问题，我直接给出了二维码的链接。 ↓

http://ojec5ddd5.bkt.clouddn.com/zhifu_m.png

**Comment by wvisible** [comment]
谢谢您的耐心解答，我只是想支持写好东西的人，但是捐赠不是很多，谢谢您

**Comment by Kenshin** [comment]
@wvisible 
感谢你的星巴克美式，今天就去消费 😉  😍
