### ISSUE TITLE
无法调用第三方API进行AI助手的使用

### ISSUE THREAD

**Issue by gaojunyang666** [Kenshin/simpread#6104]
### 请描述你的建议或任何内容

尊敬的开发者您好，我遇到了这样的问题：
![image](https://github.com/Kenshin/simpread/assets/63088548/b79d36fc-bab2-4bde-af61-2dcc5523324a)
可是我确信我进行了正确的设置，因为我在其它工具上正常使用我的中转服务（图中sk已经进行了瞎写处理）
![image](https://github.com/Kenshin/simpread/assets/63088548/fb8a5dfb-6906-4e79-b120-fca9290b84a9)

### 补充说明

如果您有空闲，请您帮我分析一下可能的原因

**Comment by gaojunyang666** [comment]
经过我的排查，问题很可能出在系统代理上，原因如下：
当我使用VPN的规则模式或者不采用VPN时运行出现如图异常
当我开启全局模式时，可以正常工作
但是我不知道怎么修复它

**Comment by Kenshin** [comment]
嗨，网络问题的话就跟简悦没关系了，你可以试试将 `api.aiwl.cc` 加入白名单？

**Comment by gaojunyang666** [comment]
好的，谢谢您，我尝试更换了代理工具，目前此问题已经解决，也希望可以帮到有类似问题的朋友。您是一位善良的开发者！

**Comment by Kenshin** [comment]
哈哈，解决就好~

QA 本身就是我（简悦）工作的一部分。😄

***

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉😁👍

**Comment by gaojunyang666** [comment]
好的！
