### ISSUE TITLE
百度百科和维基百科

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#6105]
### 需要适配的新站

https://baike.baidu.com/
https://zh.wikipedia.org/

### 有需要请描述这个站的性质

应该不用说明了吧。。。。主要是表格和侧边内容的适配比较糟糕

**Comment by PupupupuTong** [comment]
以及百度百科开头简介内容会被吞一部分

![image](https://github.com/Kenshin/simpread/assets/69069739/f9f826ab-1bcb-48fb-9b6c-81b35798c351)

![image](https://github.com/Kenshin/simpread/assets/69069739/c8df1237-551a-4625-91b8-bf3f8113e4fd)

**Comment by Kenshin** [comment]
百度百科应该是不会适配了，事多嫌麻烦。
维基百科的话，看这里 https://github.com/Kenshin/simpread/discussions/5832

PS：老用户遇到使用疑问的话，可以多翻翻 https://github.com/Kenshin/simpread/discussions

😏
