### ISSUE TITLE
很喜欢你的文章！！

### ISSUE THREAD

**Issue by huangnuonan** [Kenshin/simpread#6107]
### 请描述你的建议或任何内容

hi～我是飞书开发者广场的运营同学，之前看到你这篇文章想法很不错，正好我们广场在做征稿活动，想问问能不能收录你的文章呀 这是我的联系方式
![testaf16d74e-2070-4dc9-a99d-6ec181d234e2 jpg](https://github.com/Kenshin/simpread/assets/148539029/af2b4336-2f6c-409f-b4cf-b0106cd8d860)

**Comment by Kenshin** [comment]
嗨，谢谢喜欢，很好奇是哪篇文章？😂

我只有 Desktop 版的飞书，所以方便的话，还是加我容易些，主要是翻了翻没找到如何在 Desktop 版加入的功能...

![image](https://github.com/Kenshin/simpread/assets/81074/c1c3e5d7-84be-486b-a70a-110eec8f530c)
