### ISSUE TITLE
已开通高级账户，但验证同步助手还是无法正常显示

### ISSUE THREAD

**Issue by Justin7250** [Kenshin/simpread#6108]
### 描述这个错误

今日收到邮件已经开通了高级账户，也用license激活了，但是同步助手那里还是显示一把锁，重启浏览器问题无法解决，请问需要如何解决呢？
使用的系统是win11，浏览器是chrome，截图如下
![20231123121656](https://github.com/Kenshin/simpread/assets/145181456/431cb1b9-1d6a-4b12-84cf-fae9341529cc)
![20231123121533](https://github.com/Kenshin/simpread/assets/145181456/3e666654-70dc-411a-ab48-897091133ae4)
![20231123121610](https://github.com/Kenshin/simpread/assets/145181456/7439533f-c2eb-4276-8242-4f5b3ede9664)

### 复现步骤

同上

### 操作系统

windows11

### 浏览器

chrome

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

**Comment by Kenshin** [comment]
首次升级时会提示你重启浏览器，但你没有重启浏览器，解决方案 https://www.yuque.com/kenshin/simpread/ga970q
