### ISSUE TITLE
共通选项卡中，切换简易模式之后无法恢复高级模式了

### ISSUE THREAD

**Issue by Justin7250** [Kenshin/simpread#6109]
### 描述这个错误

共通选项卡中，切换简易模式之后无法恢复高级模式了

### 复现步骤

https://github.com/Kenshin/simpread/assets/145181456/8b67bc6e-c7a1-4620-be62-0ed86dbce32d

### 操作系统

Windows11

### 浏览器

chrome

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

**Comment by Kenshin** [comment]
在切换到简易模式后会有提示如何切换的，教程 [看这里](https://simpread.pro/docs/#/%E7%AE%80%E6%98%93%E6%A8%A1%E5%BC%8F)。

**Comment by Justin7250** [comment]
我看到了，原来是被侧边栏挡住了，隐藏左方的侧边栏出现了切换按钮，谢谢解答

**Comment by Kenshin** [comment]
小事情，解决就好。
