### ISSUE TITLE
起点中文网上阅读会显示本章说的数字

### ISSUE THREAD

**Issue by LiangSam** [Kenshin/simpread#611]
开发者你好，我最近阅读起点中文网上的小说时，后面会有数字，因为起点最近在网页添加了「本章说」（这个功能向来是只有手机客户端所有的），我关闭本章说的显示之后，在起点的网页上看见，但是当我用简悦插件后，后面的「本章说」数字依然显示，严重影响阅读体验。希望你在闲暇之余可以看一下我的问题，谢谢。
![image](https://user-images.githubusercontent.com/38411915/68590358-47565800-04c9-11ea-9f7e-b8972ac43ade.png)

**Comment by Kenshin** [comment]
嗨，这个问题应该是 页面结构发送变化造成的。

不过，我试过几个页面均未出现这个问题，请直接告诉我 URL 这样方便调试。

**Comment by LiangSam** [comment]
好的，这个是起点上的《诡秘之主》，[第一章](https://read.qidian.com/chapter/3Q__bQt6cZEVDwQbBL_r1g2/eSlFKP1Chzg1)，用简悦后就会这样，你看一看。

**Comment by Kenshin** [comment]
我这边显示没问题，估计是适配列表未升级导致的。

选项页 → 站点管理 → 手动同步适配列表

试试？

**Comment by Kenshin** [comment]
我大概知道是什么问题了...

你按照这样设置，加入如下代码

```
span[data-segid] {
    display: none;
}
```

到 站点编辑器，即可解决。

![image](https://user-images.githubusercontent.com/81074/68657144-17ad5b80-056e-11ea-80cb-9fab31779157.png)

***

PS： 站点编辑器在 右下角 → 动作 → 第二个 icon

**Comment by LiangSam** [comment]
确实解决了，十分感谢。

**Comment by Kenshin** [comment]
如果没有其它问题的话，请关闭此 issues

***

嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
