### ISSUE TITLE
导出文件标题的定制化

### ISSUE THREAD

**Issue by remoon1991** [Kenshin/simpread#6113]
### 请描述你的建议或任何内容

能否将导出前缀”simpread-”删除或者自定义，因为能用的小伙伴都会记住。

![20231125-095114-1700877073724](https://remoon-references.oss-cn-beijing.aliyuncs.com/20231125-095114-1700877073724)

希望能将”simpread-”前缀删除

**Comment by Kenshin** [comment]
使用简悦的 [增强导出功能](https://simpread.pro/docs/#/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA) 是可以定制导出标题的。

如果不使用此方式的话，可以利用 Hazel 也可以解决。

**Comment by Kenshin** [comment]
使用简悦的 [增强导出功能](https://simpread.pro/docs/#/%E5%A2%9E%E5%BC%BA%E5%AF%BC%E5%87%BA) 是可以定制导出标题的。

如果不使用此方式的话，可以利用 Hazel 也可以解决。
