### ISSUE TITLE
【新功能】添加一键收藏并分类功能

### ISSUE THREAD

**Issue by linyisan** [Kenshin/simpread#6114]
收藏的时候支持编辑说明以及最重要的标签。简悦的定位是稍后阅读，二次处理吧，它的重点放在了优化网页专注阅读上，然而我更希望它提供快速收藏的功能，可以在第一次收藏的时候加入编辑标签功能，快速对收藏进行简单分类。

**Comment by Kenshin** [comment]
一键收藏的话，早就有了，但是需要使用同步助手，细节 [看这里](https://simpread.pro/docs/#/Bookmarklet)。

只不过我不希望用户这么做，我（简悦）更希望有深度阅读诉求的网页才使用阅读模式（以及简悦的相关功能，如：稍后读、标注等）。

大部分为了收藏而收藏的基本上也不会再看。

**Comment by linyisan** [comment]
> 一键收藏的话，早就有了，但是需要使用同步助手，细节 [看这里](https://simpread.pro/docs/#/Bookmarklet)。
> 
> 只不过我不希望用户这么做，我（简悦）更希望有深度阅读诉求的网页才使用阅读模式（以及简悦的相关功能，如：稍后读、标注等）。
> 
> 大部分为了收藏而收藏的基本上也不会再看。
> 
> 综上，简悦希望是先看，然后认为有用再收藏（稍后读和标注）。

把小书签拉到浏览器地址栏上面，然后在弹出新标签中点击新建后，在浏览器的稍后阅读页里面还是没有该条保存记录。

**Comment by Kenshin** [comment]
1. 你使用同步助手的自动同步（即：本地有个 `simpread_config.json` 的文件）

2. （如果满足第一点）你试试加完后，直接打开稍后读，看看这个新加入的稍后读是否存在。

3. （如果满足第一点）使用此方式添加后， `simpread_config.json` 的更新时间应该是你添加稍后读的时间。

**Comment by linyisan** [comment]
#1401

找到原因了，前置条件需要打开浏览器的自动同步功能，在产品文档中只是一行文字说明，没有图片强调说明，容易忽略

**Comment by Kenshin** [comment]
okay 搞定就好~

PS：谢谢提示，我考虑加强这块的描述。
