### ISSUE TITLE
您好，想向您咨询关于永久链接相关的设置问题。

### ISSUE THREAD

**Issue by mumushp** [Kenshin/simpread#6118]
### 描述这个错误

您好，我想在obsidian嵌入使用您说的永久链接，因为我的一些资料保存希望是html。我希望能对本地html构建回溯链接，然后嵌入到obsidian中，方便我以后进行知识的回溯。我有一些想使用的场景及功能，我在您的教程里没找答案，特此来向您咨询。
我的想法：我想对html进行一些编辑，比如删掉一些页面内容，或者是进行批注/注释，请问需要做什么设置？希望这种编辑功能面对在线/本地html都能实现。2.对离线的html，我想能进行双向链接，引用到obsidian中，以后有需要可以进行回溯。
(针对第2点问题，我研究了您关于永久链接的教程[https://www.yuque.com/kenshin/simpread/egvhm7]，遇到了以下问题1.我在“一站式开通开放平台”这步设置里，是否只能用坚果云，我的同步网盘是onedrive，能否换成onedrive，如果能换，能否请您指导我一下，而且关于坚果云还有一个问题是我全平台同步的网盘是onedrive，那是否比如我在移动端没有下载坚果云的话就没有办法对永久链接进行回溯呢？2.您提到obsidian配置库已经设置好永久链接需要的配置，因为您的配置库里的一些功能我用不上/不太符合我个人的工作流程，所以特来向您请教如何实现永久链接的功能。)
十分感谢您能看到这里，谢谢您的帮助。
您好，我在您和其他人的对话中发现了我想要实现的功能的描述[https://github.com/Kenshin/simpread/issues/3305#issuecomment-1013684156]
『Zotero』：对【PDF】进行【标注】，且能够对【标注内容】进行编辑、引用，Markdown导出（支持原文跳转）。
『简悦』则是对【HTML】具备了同样不错的功能和体验。

我就是想要在简悦中对HTML进行【标注】，且能够对【标注内容】进行编辑、引用，Markdown导出（支持原文跳转），然后将我需要进一步处理的笔记/原文跳转的链接嵌入obsidian中，方便我在obsidian总结中能进行知识回溯。

### 操作系统

windows 10

### 浏览器

chrome

**Comment by Kenshin** [comment]
嗨

首先，这里是简悦的唯一的 QA 渠道，所以你在这里提问没有任何问题。😄

***

其次，回复下你的疑问。

因为你是 Obsidian 用户，基于你的诉求最简单的解决方案就是这个 https://www.yuque.com/kenshin/simpread/wq35mh

链接是你需要的全部功能的配置包，也就是你使用此配置包后仅需要设置路径，无需设置其它内容即可实现。

***

除此之外，基于你的诉求：**不需要开通开放平台**。

另外，我关闭这个 Issues 了，但你仍可以随时跟我讨论。

**Comment by Kenshin** [comment]
### 描述这个错误

您早上给予了我回复，建议我使用obsidian高级版配置教程，我按照您的教程操作了一遍，遇到了以下问题。

1.我自己设想的工作流程是在浏览器上，通过简悦插件进行html的批注和编辑（这些资料能本地化），然后如果有需要，我会从这些批注过的文件中，提取出我所需要的知识（并非所有批注的知识点）通过双链嵌入到obsidian中，辅助我在obsidian总结的过程中提供回溯的方式。

2.目前我按照obsidian高级版配置发现所有批注都会放在在obsidian里面，产生了很多不必要的资料。

3.我有一些之前积累的html资料，我希望它也能实现对网页中某些段落能构建双链嵌入obsidian中，方便在obsidian中回溯。

总结以上的内容，我想实现的功能是：针对一个本地化的html文件中某一段内容，我能建立起链接，嵌入ob中使得我能回溯，回溯时点击该链接能直接在ob中打开该网址。【ob中我目前使用custom frames 和 web browse这两个插件实现ob中直接能打开网页，因为您设置的内部链接格式是http://localhost:7026/reading/xxx，它是否也算一个网址，能直接在ob中打开】

这是我最迫切希望能解决的问题，我觉得这个想法很私人订制化，不知道是否会很麻烦，如果不好操作的话就算了，如果给您造成不必要的麻烦真的很抱歉，谢谢您设计这么好的插件，感谢您的阅读。


我分别进行了以下的尝试
1.obsidian高级版配置教程

2.本地快照系统的搭建，进行到链接引用【http://localhost:7026/reading/xxx】这步没法在ob上打开链接，以及不知道在【http://localhost:7026/reading/xxx】这个文件里怎么建立某个段落/知识点的双向链接

3.Obsidian 配合简悦实现方便的来源引用（网页）【https://zhuanlan.zhihu.com/p/345900114】该教程的尝试，链接复制进obsidian里没法直接在ob中打开该页面，只能关闭【ob中custom frames 和 web browse这两个插件】，然后直接跳转到浏览器打开

**Comment by Kenshin** [comment]
嗨

不要重复新建 Issues...  我关闭了 #6121 请在 #6118 讨论。

***

> 针对一个本地化的html文件中某一段内容，我能建立起链接，嵌入ob中使得我能回溯，回溯时点击该链接能直接在ob中打开该网址。

我不理解你的问题，排除掉技术（配置上的）细节，这就是简悦的功能，所以如果你没有使用这个配置库方案的话，直接使用它就行了。（但你之前的描述说已经使用了...

> 我有一些之前积累的html资料，我希望它也能实现对网页中某些段落能构建双链嵌入obsidian中，方便在obsidian中回溯。

可以，使用 https://github.com/Kenshin/simpread/discussions/4625 提到的方式，可以将任意本地 HTML 生成简悦的阅读模式，然后就能使用你需要的功能了。

> ob中我目前使用custom frames 和 web browse这两个插件实现ob中直接能打开网页，因为您设置的内部链接格式是 http://localhost:7026/reading/xxx ，它是否也算一个网址，能直接在ob中打开

如果使用了简悦的配置库方案，理论上不需要这些。（只能说理论上，需要结合你具体使用方式）

***

建议可以看下 https://space.bilibili.com/1853727625/channel/collectiondetail?sid=807741 里面关于 Obsidian + 简悦的联动方案，即便不使用，也可以简单的瞧瞧这套方案可以做什么。

**Comment by mumushp** [comment]
好的，谢谢您的回复，麻烦您了，我再看一下。
