### ISSUE TITLE
能否添加编辑功能类似print friendly & PDF这个插件一样

### ISSUE THREAD

**Issue by Wali111222** [Kenshin/simpread#6123]
### 请描述你的建议或任何内容

能否添加编辑功能类似print friendly & PDF这个插件一样，可以删除或添加文字，像word那样编辑，希望可以这样，感觉用隐藏任何元素有点一棍子打死了。谢谢。

**Comment by Kenshin** [comment]
可以的，这个功能一直都存在，名称叫做 Live Editor 如何使用 https://github.com/Kenshin/simpread/discussions/2852

关于 Live Editor 的更多用法 [看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3A%22live+editor%22)
