### ISSUE TITLE
Mac端内存占用

### ISSUE THREAD

**Issue by gitstude2023** [Kenshin/simpread#6126]
### 描述这个错误

<img width="791" alt="image" src="https://github.com/Kenshin/simpread/assets/147696497/01795aa6-cba0-4971-a8c0-0ee25813c649">
为什么这个工具占用了这么多内存？

### 复现步骤

如图

### 操作系统

macOS

### 浏览器

edge

### 发生问题的网址

无

**Comment by Kenshin** [comment]
你都使用了什么功能？
重启同步助手，然后看下初始占用，然后再观察下。

PS：这是 Electron 封装的，内存占用可能有点大，但一般只要是不太老的系统都没什么问题，优势是 M 系列的 Mac ，比如我自己的，不会有太明显感受。

**Comment by gitstude2023** [comment]
正常使用，导出同步这些。
我的是M1pro，不管什么系统，你这一个工具能占用1G多内存？

**Comment by gitstude2023** [comment]
这还不算浏览器插件的，就单纯这一个工具，我默认启动以后就放到后台不管了，你的意思是我用完你们这个插件还得定时重启是吗

> 你都使用了什么功能？ 重启同步助手，然后看下初始占用，然后再观察下。
> 
> PS：这是 Electron 封装的，内存占用可能有点大，但一般只要是不太老的系统都没什么问题（感知不到），优势是 M 系列的 Mac ，比如我自己的，不会有太明显感受。

**Comment by Kenshin** [comment]
1. 我的意思是一般情况下用户感知不到内存占用，尤其是 Mac 并且是 M 系列的 CPU。
2. 并不需要重启，比如我，只是重启能解决内存占用问题。
3. 本质上你提到问题跟简悦无关，跟 Electron 有关。（ Electron 从某种角度说相当于你的 Chrome 内存占有率的量级）

**结合你上一次的 Issues 所以是不是发生这种情况时经常使用 PDF 高级打印功能？**

综上，发生这种情况时，对于我来说：

1. 开发者（我）需要了解是否是偶发，偶发的话可以忽略不计。
2. 当不确定是否是偶发时，我给你解释了一下这种原因可能存在的情况。
3. 目前我得到的反馈应该没有人（或个别用户）反馈过内存占用问题。

PS：如果你是 M 系列的 CPU 其实完全可以不用在意这块，但每天重启一次同步助手还是有必要的。
