### ISSUE TITLE
加入稍后读的文章，在obsidian中看不到

### ISSUE THREAD

**Issue by okuc** [Kenshin/simpread#6127]
### 描述这个错误

大家好，我在浏览器插件中将当前页面加入到稍后读中，然后在同步插件的output下可以看到该页面的离线文件，但是打开obsidian中，却无法查看到，这是为什么呢？
我在同步插件中设置如下：
![image](https://github.com/Kenshin/simpread/assets/2579094/7c2e442a-0294-4b36-8baf-bde4c9db6e7e)
![image](https://github.com/Kenshin/simpread/assets/2579094/e69d9cfd-f4ba-45f0-9702-28a215312ac0)
我在obsidian中的设置如下：
![image](https://github.com/Kenshin/simpread/assets/2579094/1edb9336-4674-4f3e-bd4e-20473efd38f1)

### 复现步骤

各种配置参见上图

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

任意网址都是如此

**Comment by Kenshin** [comment]
新用户的话，建议直接使用 https://www.yuque.com/kenshin/simpread/wq35mh 方案。

PS：你给出的截图也不是全部设置 😂

**Comment by okuc** [comment]
> 新用户的话，建议直接使用 https://www.yuque.com/kenshin/simpread/wq35mh 方案。
> 
> PS：你给出的截图也不是全部设置 😂

我就是用得这个方案，只不过改了一下配置名。
还需要什么配置，麻烦说一下，我发上来
