### ISSUE TITLE
不同网站的字体大小不同？

### ISSUE THREAD

**Issue by jkwtbmyz** [Kenshin/simpread#613]
按照我的理解，既然是阅读模式，那么打开之后的字体大小应该是固定的，跟原网站的字体大小无关。
但是这里有两个网站，开启阅读模式的字体大小不同。
https://new.qq.com/omn/20191117/20191117A0G65Y00.html
https://zhuanlan.zhihu.com/p/68241747
![image_11](https://user-images.githubusercontent.com/17421620/69078590-25357a80-0a73-11ea-8cee-661ffe49de13.png)

这是firefox的效果：
![image_14](https://user-images.githubusercontent.com/17421620/69079439-ef919100-0a74-11ea-95ba-a6c04e6f270a.png)

截图不明显，但是我这里看得很明显。
是只有我设备上才有区别吗？
如果不是的话，这个字体大小差异是有意为之还是bug呢？

**Comment by Kenshin** [comment]
这是在 Chrome 上的截图效果，应该是一样的大小

![image](https://user-images.githubusercontent.com/81074/69105526-7f9bfe80-0aa6-11ea-8750-396e28158d6f.png)

建议你试试 Chrome 回头我再找个时间试试 Firefox 
目前 Firefox 的版本有些滞后，导致它们的解析引擎不一样，所以有可能出现问题。

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

我在清理 issues 请确认是否还存在问题？没有的话，请关闭 issues

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
