### ISSUE TITLE
代码段增强 插件运行出错

### ISSUE THREAD

**Issue by g199209** [Kenshin/simpread#6133]
### 描述这个错误

插件运行出错，代码段没有高亮了。

### 复现步骤

加载此插件时阅读模式打开问题网址即可。

### 操作系统

masOS

### 浏览器

Chrome

### 发生问题的网址

https://stackoverflow.com/questions/4810841/pretty-print-json-using-javascript

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

***

代码段的问题都比较麻烦，因为代码高亮规则太多了，没法判断 😂
