### ISSUE TITLE
保存到Notion时，一直显示圆圈加载

### ISSUE THREAD

**Issue by yzhAndy** [Kenshin/simpread#6136]
### 描述这个错误

1. 使用Cloudinary床图，且验证通过
![image](https://github.com/Kenshin/simpread/assets/67348844/f073ecc3-5758-40d3-bf8f-cda60979f6e1)
2. 在有图片的页面，点击“保存到Notion”，出现如下卡死
![image](https://github.com/Kenshin/simpread/assets/67348844/9e1e886c-d483-4ec3-91c1-835ae125c189)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/67348844/4713964d-ae2c-4319-88ae-2a24f5b78840)

### 操作系统

windows11

### 浏览器

Chrome 版本 117.0.5938.132（正式版本） （64 位）

### 发生问题的网址

https://jingyan.baidu.com/article/359911f521d2c417fe0306e9.html

**Comment by Kenshin** [comment]
导入到 Notion 图床的功能因为它们修改 API 导致无法使用了，请更改为 Cloudinary 图床方案。

**Comment by Kenshin** [comment]
补充下：估计是你没有开下面的选项

<img width="873" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b3dbeb3d-bfb3-4a86-839c-e2c8b585a4cf">

**Comment by yzhAndy** [comment]
1. 选项是打开的
![image](https://github.com/Kenshin/simpread/assets/67348844/9c7766f0-bd84-4b94-a1ca-4f84aef21e6e)
2. 尝试“将图片导入到床图”，出现同样问题。但考虑到验证床图成功，猜测是床图上传问题，不知道怎么解决
![image](https://github.com/Kenshin/simpread/assets/67348844/eb346b93-8146-46ba-acfc-d2e7fa2c8c4e)

**Comment by Kenshin** [comment]
okay 我明天确认下这个问题。

**Comment by Kenshin** [comment]
估计你可能点错了导入方式，应该是点下图的 Icon

<img width="454" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8d17ba1b-9ad9-44f4-800b-398922e68fab">

**Comment by Kenshin** [comment]
@zqjimlove 

把 cf 图床先关了，然后找个少数派的页面测试是否可以正常导入 Notion 

一步步排查，很容易定位到问题。

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
