### ISSUE TITLE
保存的 HTML 使用外部文件夹方案无法进入阅读模式

### ISSUE THREAD

**Issue by alan16742** [Kenshin/simpread#6137]
### 描述这个错误

利用singlefile保存的文件，无论是通过扩展设置的**允许访问url文件**还是同步助手的**外部文件夹**访问都不会正常显示

### 复现步骤

![20231202181949169](https://github.com/Kenshin/simpread/assets/67932758/00ea3e7a-d523-4f36-a279-9d49a6b1e396)
![kali-linux-2023 3-vmware-amd64-2023-12-02-18-37-18](https://github.com/Kenshin/simpread/assets/67932758/6db6819a-f338-4542-afba-80142efc45a0)

### 操作系统

win,linux

### 浏览器

edge,chrome

### 发生问题的网址

https://en.wikipedia.org/wiki/Ernest_Roberts_(Australian_politician)

**Comment by Kenshin** [comment]
外部文件夹应该没问题，把你截图的这个文件打包发上来，我明天看下~

**Comment by Kenshin** [comment]
另外一点：是个别网页？还是全部都这样？

**Comment by alan16742** [comment]
没有开启阅读模式的前提下，目前碰到的是很多非文章的页面，比如知乎，wiki，微博，部分微信文章页面也会
[file.zip](https://github.com/Kenshin/simpread/files/13536097/file.zip)

**Comment by Kenshin** [comment]
okay 我明天确认下。

**Comment by Kenshin** [comment]
我这边没有遇到你提到的问题，看下图

<img width="1815" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/af7af192-721a-49d9-8218-188ed0a14e3e">

<img width="1815" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/11e8c758-621f-4151-905b-46a955fe89cf">

就不继续截图了。

***

另外，压缩包里面的微博肯定是不好使的，因为这个页面本身就没有进入阅读模式的必要。

建议在 Windows 测试，并使用 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

同时，如果你用了外部文件夹，可以直接访问 http://127.0.0.1:7026/static/Ernest%20Roberts%20(Australian%20politician)%20-%20Wikipedia%20(2023_12_2%2018_15_44).html

这个文件就是给我的 `Ernest Roberts (Australian politician) - Wikipedia (2023_12_2 18_15_44)`

**Comment by Kenshin** [comment]
> 发现访问127.0.0.1:7026不能正常显示

应该是这个问题造成的，你试试修改 host 把这两个映射下。
