### ISSUE TITLE
控制栏可否去掉？

### ISSUE THREAD

**Issue by hoasxyz** [Kenshin/simpread#614]
有些网站在右下角有表示往上翻的朝上的箭头，控制栏刚好挡住了这个箭头导致点不了。

**Comment by Kenshin** [comment]
选项页 → 高级设定 → 聚焦模式 or 阅读模式

仔细阅读相关选项，能发现你需要的。  😀

**Comment by hoasxyz** [comment]
@Kenshin 谢谢，已经找到方案：

左键点击该扩展程序 → 可读取和更改网站数据 → 当您点击此扩展程序是时 → 刷新该网站
