### ISSUE TITLE
本地 Markdown 渲染有问题，无法加载图片

### ISSUE THREAD

**Issue by g199209** [Kenshin/simpread#6143]
### 请描述你的建议或任何内容

与 #6141 & #6142 相关联的问题，我目前使用 #6142 中提到的方法导出了离线 Markdown，在 Obsidian 中可以正常查看，然而我想用 [读取外部文件](http://ksria.com/simpread/docs/#/%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6) 的方法在浏览器阅读模式中查看时就发现有问题了：

![image](https://github.com/Kenshin/simpread/assets/15379793/5c661821-f695-46a7-887b-9119b41be6db)

1. Properties 部分的数据渲染不太正确，这是小问题，可以忽略；
2. 本地图片全部无法正确加载。

**Comment by Kenshin** [comment]
emmm

我测试了下外部文件夹读 Base64 应该是没问题的，这是我导出的一份**离线 Markdown 文件**，你可以试试。

[派早报：苹果更新 iPhone 12 软件以符合法国射频规定，最高检阐释人人影视案2.txt](https://github.com/Kenshin/simpread/files/13538620/iPhone.12.2.txt)

不过，有几个建议：

1. 不建议在 Obsidian 中使用离线 Markdown，因为会很卡，会把 Obsidian 直接卡死，我测试过除了 vs code 外其余 Markdown 编辑器并不能很好的处理这种问题。

2. 在外部文件夹中渲染包含 Metadata 的 Markdown 肯定有问题，因为我只能把 Markdown 渲染为 HTML 当然不支持 Metadata 方案。

**Comment by g199209** [comment]
> 在外部文件夹中渲染包含 Metadata 的 Markdown 肯定有问题，因为我只能把 Markdown 渲染为 HTML 当然不支持 Metadata 方案。

目前用的就是 md + asset 方案，base64 编码的离线 markdown 在 Obsidian 中没法正常渲染出来……Typora 直接拒绝打开这么大的 markdown。

我理解同步助手内部是起了个 HTTP server 吧，渲染 markdown 的时候把这类图片源设置为对应 URL 地址应该可以做到正常显示？
