### ISSUE TITLE
先知论坛的图片无法导出（高级账户开了增强，使用Textbundle也不行）

### ISSUE THREAD

**Issue by moyuwa** [Kenshin/simpread#6144]
### 描述这个错误

https://xz.aliyun.com/
![image](https://github.com/Kenshin/simpread/assets/31231318/dd57bd6e-a7a8-41a5-852a-700eb25a140c)

### 复现步骤

社区访问任意带图片文章，使用浏览器插件导出，选择导出Textbundle、或使用md+assets模式导出，导出的assets文件夹内无图片；
先知社区使用了阿里云的存储桶，需要refener等请求头参数才能正常访问图片

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://xz.aliyun.com/

**Comment by Kenshin** [comment]
okay 某些图床这么特别设置的话，确实存在这种情况。

理论上简悦仅「采集」正常的图片到本地，但像类似的方式一般不太会做「过多干涉」。

你可以试试导出离线 HTML 看能否解决。

PS：类似这样的问题反馈的不太多，只能算个例处理。
