### ISSUE TITLE
阅读模式下复制异常

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#6149]
### 描述这个错误

![copy_bug](https://github.com/Kenshin/simpread/assets/10437293/f13c7cbd-cacd-4aea-891b-b8f0ae8795b8)

### 复现步骤

有异常的网址是：
https://blog.csdn.net/linxinfa/article/details/107669242

进入阅读模式，用妙控板打算复制某段文字，移动选中的内容就会出现位置不对的问题

### 其他相关说明

无

### 操作系统

macOs

### 浏览器

edge

### 发生问题的网址

https://blog.csdn.net/linxinfa/article/details/107669242

**Comment by Kenshin** [comment]
我这边仍旧没有复现，我这边是这样的情况

<img width="400" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e01cf6ad-fdc1-455c-a98d-37b41e6aa53a">

可能是跟下面两个选项有关

![image](https://github.com/Kenshin/simpread/assets/81074/30ada822-3d5b-40c2-a5a7-13b97b7ad0c4)

**Comment by AriaLyy** [comment]
感谢回复，我试了下还是不行，我今天重新测试下，80宽度也存在问题，只要超出区域就会出现这个问题，如下面的动图所示，不知道这个操作你那边能不能复现

![copy_bug](https://github.com/Kenshin/simpread/assets/10437293/71ea92be-dc7d-4e8d-9882-208f723cbf7f)

**Comment by AriaLyy** [comment]
动图出问题了，只要鼠标移出内容区域，光标位置就异常了
![image](https://github.com/Kenshin/simpread/assets/10437293/0cd63c0d-b04d-46c8-ba7a-798bd2923d0f)

**Comment by AriaLyy** [comment]
![copy_bug22](https://github.com/Kenshin/simpread/assets/10437293/240eb87e-520c-4107-b33c-f57f1b8863ed)

**Comment by Kenshin** [comment]
有没有使用 模仿 Safari 样式插件？

另外，竖屏显示器是副？还是主的？你有几个显示器？

如果有多个的显示器的话，也可以试试 https://simpread.ksria.cn/plugins/details/noCdz57Mw6 （这个插件不是解决这个问题的，只是提示下）

**Comment by AriaLyy** [comment]
加上mbp，一共三个显示器，目前在这几个显示器上，只要超出区域都有着问题

另外，我把模仿 Safari 这个插件移除了，看起来就正常了，但是移动到目录那个位置还是存在问题

**Comment by Kenshin** [comment]
启用  **模仿 Safari 样式插件** 的前提下，将下面的代码

```
sr-read toc-bg {
    pointer-events: none!important;
}

sr-read toc {
    pointer-events: initial!important;
}
```

加入到下图的地方

<img width="458" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c6f909d8-a3aa-47c5-b45f-daa97c8a35da">

然后重启浏览器

**Comment by Kenshin** [comment]
> 点击妙控板，会直接退出阅读模式

模仿 Safari 样式插件 有个选项，关闭或开启它（我忘记什么名字了），你看下就知道了。

不确定是否是这个问题，但大概率是它。
