### ISSUE TITLE
高级账户使用疑问

### ISSUE THREAD

**Issue by yunbukenshuo** [Kenshin/simpread#6151]
### 请选择

你好，我是简悦的高级用户，目前找回UID超过三次，无法正常登录高级会员用户了，现在不知道如何处理，请管理员帮助处理一下。账号1057731460@qq.com

### 发生问题的网址

请管理员帮助处理一下

**Comment by Kenshin** [comment]
嗨

UID 找回三次是 2.0 时的功能，新版（也就是你现在使用的）版本，在首次升级为高级账户时会自动下载一个叫做 `simpread-key-内含UID，请勿遗失.json` 的文件。

这个文件会包含你的 UID 和 License，相当于一个密钥，用户可以使用这个文件里面的 UID 来恢复高级账户身份，因此理论上已经不存在找回超过三次的情况。

简悦为了保障用户隐私，并没有账户系统，而且是基于 Local first 的产品，所以我没法通过你提供的 QQ 找回。

（如果有）你可以把你的 License 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6151
