### ISSUE TITLE
导入 Notion 授权时的使用疑问

### ISSUE THREAD

**Issue by jx453331958** [Kenshin/simpread#6152]
### 描述这个错误

已授权Notion权限，且通过服务中的Notion功能可以成功保存笔记。但是使用Notion插件之后，在显示已授权的情况下还会一直提示授权。
<img width="1159" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/29aa74e9-c044-4a3a-8081-96106b11d026">

### 复现步骤

1. 随便找一个页面
2. 点击动作中的一键导入到Notion
<img width="328" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/f4c60ee9-be35-4b63-a88b-723eedf8ba9b">

### 其他相关说明

https://github.com/Kenshin/simpread/assets/26744792/e7437541-4e40-4a25-baa8-1e2dbfd37bcd

### 操作系统

macOS

### 浏览器

chrome 119.0.6045.199

### 发生问题的网址

https://github.com/Kenshin/simpread/issues/809

**Comment by Kenshin** [comment]
设置并保存后，请刷新当前页面再试试...

**Comment by Kenshin** [comment]
保存后**刷新当前页面**

<img width="310" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c0a56911-6bc3-49e2-9dd1-d1b282d7f0db">

**Comment by jx453331958** [comment]
> 保存后**刷新当前页面**
> 
> <img alt="image" width="310" src="https://private-user-images.githubusercontent.com/81074/288017927-c0a56911-6bc3-49e2-9dd1-d1b282d7f0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTA1MDQsIm5iZiI6MTcwMTc5MDIwNCwicGF0aCI6Ii84MTA3NC8yODgwMTc5MjctYzBhNTY5MTEtNmJjMy00OWUyLTlkZDEtZDFiMjgyZDdmMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE1MzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MjI2MThmYzlkNTFjNzBlYzU0MjM0NDVmNWJiNmRmN2M3OGViNjM0Yjk0NDFiYzhhNDNhN2M3NTI3ODc3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.exu81JJUXqtq-tjsHFPypCi1ERJAvILB76RHSyCSY9U">

刷过了，还重新进过页面，不过这部分没录屏，反复尝试了很多次才提的问题

**Comment by jx453331958** [comment]
> > 保存后**刷新当前页面**
> > <img alt="image" width="310" src="https://private-user-images.githubusercontent.com/81074/288017927-c0a56911-6bc3-49e2-9dd1-d1b282d7f0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTA1MDQsIm5iZiI6MTcwMTc5MDIwNCwicGF0aCI6Ii84MTA3NC8yODgwMTc5MjctYzBhNTY5MTEtNmJjMy00OWUyLTlkZDEtZDFiMjgyZDdmMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE1MzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MjI2MThmYzlkNTFjNzBlYzU0MjM0NDVmNWJiNmRmN2M3OGViNjM0Yjk0NDFiYzhhNDNhN2M3NTI3ODc3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.exu81JJUXqtq-tjsHFPypCi1ERJAvILB76RHSyCSY9U">
> 
> 刷过了，还重新进过页面，不过这部分没录屏，反复尝试了很多次才提的问题

等我明天到公司了再把这个操作完整录一下

**Comment by Kenshin** [comment]
okay 你的问题确实有点奇怪，如果方便的话，你可以用个新浏览器，新安装简悦，然后直接安装这个插件。（这个功能基础账户就能使用）

这样测试更干净些，因为这个问题「不可能」存在，否则早就有用户提问了，这个插件的用户量还不错。

但不代表你那边就一定不会发生～

**Comment by Kenshin** [comment]
我大概知道什么问题了.... 仔细留意下图的描述

<img width="607" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/52ffccad-1739-4084-bb11-27fb6114fd6e">

**Comment by Kenshin** [comment]
emmm 还有个方式

![image](https://github.com/Kenshin/simpread/assets/81074/0ae6a054-292d-4f97-a707-9a3ef8735283)

不过如果想要做仓储的话，确实不建议使用线上方案，未免以后有各种坑...
