### ISSUE TITLE
功能建议, surfingkeys的v模式选中文字后弹出悬浮栏并高亮

### ISSUE THREAD

**Issue by gfgkmn** [Kenshin/simpread#6155]
### 请描述你的建议或任何内容

重度vim模式用户, 比较喜欢键盘操作, 特别在电脑上没有笔的时候, 使用鼠标的定焦实在是很焦心, surfingkeys在简阅下工作的很好, 就是在阅读模式中需要高亮的时候, 还是需要切换至鼠标来进行操作. 

有一个建议就是如果提供一个高亮功能的编程接口, 能够使用surfingkeys来调用, 使得在比如在surfingkeys选中文字的时候, 就可以直接进行高亮, 就非常好. 

理想的使用情况是, 读文章, 使用V模式, 按两个前导字母选中要高亮的内容, 然后按下某个快捷键, 该内容高亮并像鼠标高亮一样添加到simpread的标注列表中. 

自己尝试用inspect看了一下contentjs的代码, 混淆后看不懂(本来js也不太会), 所以在这儿问问大家, 看看有没有可能实现, 或者别人有什么好的办法

**Comment by Kenshin** [comment]
嗨

你可以在 Issues 搜索下 `surfingkeys` 看下其他用户的解决方案，或许可以给你一些帮助。

今天太晚了，明天再详细确认下这个问题

**Comment by gfgkmn** [comment]
感谢回复! 

我搜了一下相关的issue,没有找到相关的问题. 详细来说, 大概是这样的话. 
![CleanShot_2023-12-06_at_03 56 51@2x](https://github.com/Kenshin/simpread/assets/4817005/884ed1e2-d659-4bef-b98b-0118eac447cb)
![CleanShot_2023-12-06_at_03 59 42@2x](https://github.com/Kenshin/simpread/assets/4817005/ae7ef45c-5696-4b52-908f-4fbabff05153)
![CleanShot_2023-12-06_at_04 00 07@2x](https://github.com/Kenshin/simpread/assets/4817005/2a86a5af-6f8e-4a43-a3f2-2eecb2e0861c)
![CleanShot_2023-12-06_at_04 00 31@2x](https://github.com/Kenshin/simpread/assets/4817005/cf686362-88ec-468e-9e0c-5fb39d47d2e4)


如上图, 已经是在简阅的阅读模式中了, 并且打开了, 连续高亮, 如果使用鼠标直接选中minus some context, 就会如下图所示直接高亮内容, 但是在使用surfingkeys的情况下, 按v进入v模式, 在不同段落的文字上显示提示, 然后按下ac键, 进入visual caret再按v键进入range选择, 使用$键选到句尾, 就出现了上面最后一图所示的选择状态, 但是却不会高亮, 也不会弹出悬浮栏, 就无法做到完全的离开鼠标. 

![CleanShot_2023-12-06_at_04 10 25@2x](https://github.com/Kenshin/simpread/assets/4817005/35ea4605-a923-4e76-bee5-fb156d31d695)

其实就是希望这里, 如果连续高亮能够同时监听到v模式的选中就好了. 退一步讲, 如果有一个接口, 使得可以在surfingkeys中自定义一个js函数来访问, 然后自定义一个健绑定也可以.

**Comment by Kenshin** [comment]
如果你的意思是指：

> 在划取状态时，也希望可以标注的话。

试试下面的方式。

<img width="751" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/43f7f2bc-62cb-4385-803d-5be76c94abba">

**Comment by gfgkmn** [comment]
感谢指点, 又仔细看了一下surfingkeys的文档和简阅的快捷键, 还是无法实现开始所指的功能. 

目前的进展是, 看到surfingkeys中的passthrough模式, 可以有一个临时穿透把键传递给下一个扩展, 但是尝试后性, 在简悦中使用鼠标选中, 和使用V模式选中是不一样的, 使用鼠标选中后, 会自动的弹出悬浮栏, 这里就可以使用快捷键进行高亮. 

但是使用V模式选中后,  悬浮栏不会自动弹出, 而且surfingkeys右下角的文字也还在, 这时即使使用passthrought穿透调用简悦的快捷健. 也是不生效的.

这似乎是surfingkeys在V模式下passthrough的问题. 也许我应该再去surfingkeys哪儿找一找答案.

**Comment by Kenshin** [comment]
😂 

好，好在 Surfingkeys 也是国内开发者的作品，之所以你能在阅读模式下使用，就是因为 Surfingkeys 专门适配了下简悦。

**Comment by Kenshin** [comment]
小事情，因为你提到了标注功能，所以多说几句。

简悦有些像 Obsidian 都是 Local first 类产品，如果动手能力强的话，可以有很多玩法。

如果是双链笔记用户的话，可以瞧瞧 https://github.com/Kenshin/simpread/discussions/2085 或者直接使用配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0

我先关闭这个 issues 了，不过你仍可以随时跟我在这里讨论 😄

***

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍
