### ISSUE TITLE
使用piclist配合图床插件，将图片上传到github图床并导入obsidian的过程中，会有个别图片挂掉

### ISSUE THREAD

**Issue by SilenceHell** [Kenshin/simpread#6156]
### 描述这个错误

刚进入阅读模式后，图片显示都是正常的，在使用piclist配合图床插件，将图片上传到github图床并导入到obsidian的过程中，会有个别图片挂掉，此时阅读模式中的个别图片会无法显示
![1](https://github.com/Kenshin/simpread/assets/20390652/85b8b10f-7a7e-4836-ac37-cabb8ff85009)
obsidian中对应的图片也无法显示
![2](https://github.com/Kenshin/simpread/assets/20390652/c4fddefa-5cd5-4f59-b0e9-e331b531721b)
此时obsidian切换到编辑模式，可以看到无法显示的图片是一串base64编码
![3](https://github.com/Kenshin/simpread/assets/20390652/a79a7d25-01bb-4f61-b673-a10cd840987f)
这样的问题，几乎每次都会遇到。

### 复现步骤

1、访问  https://blog.csdn.net/yanchenyu365/article/details/133783937
2、进入阅读模式；
2、使用图床插件配合piclist将图片上传到图床后导出文章到obsidian

### 操作系统

windows10

### 浏览器

chrome  版本 119.0.6045.160（正式版本） （64 位）

### 发生问题的网址

https://blog.csdn.net/yanchenyu365/article/details/133783937

**Comment by Kenshin** [comment]
图片**上传后会将图片在图床的地址替换原来的地址**，图裂掉的意思是：新图床的图片地址是错误的。

我的建议：

先找一个正常点的页面测试 e.g https://sspai.com/post/83006 如果这个页面的图片没问题，然后再找一个图多点的页面 e.g. https://sspai.com/post/69972 测试，如果也没问题，然后测试出问题的页面以及不同的页面。

PS：那串 base64 代码是裂图的，跟这个问题无关。

PPS：如果只是偶发的情况，看下裂图的图片在你的 Github 上是否存在（且正确），如果不存在的话说明上传错误。

PPPS：综上，我个人不太建议使用 Github 图床，因为这个图床在大部分国内的网站都没法正常访问，而且 Github 也并不是一个图床产品 😂

**Comment by SilenceHell** [comment]
> 图片**上传后会将图片在图床的地址替换原来的地址**，图裂掉的意思是：新图床的图片地址是错误的。
> 
> 我的建议：
> 
> 先找一个正常点的页面测试 e.g https://sspai.com/post/83006 如果这个页面的图片没问题，然后再找一个图多点的页面 e.g. https://sspai.com/post/69972 测试，如果也没问题，然后测试出问题的页面以及不同的页面。
> 
> PS：那串 base64 代码是裂图的，跟这个问题无关。
> 
> PPS：如果只是偶发的情况，看下裂图的图片在你的 Github 上是否存在（且正确），如果不存在的话说明上传错误。
> 
> PPPS：综上，我个人不太建议使用 Github 图床，因为这个图床在大部分国内的网站都没法正常访问，而且 Github 也并不是一个图床产品 😂

裂图的图片在 Github 上存在，但也无法正常显示。

**Comment by SilenceHell** [comment]
> > 图片**上传后会将图片在图床的地址替换原来的地址**，图裂掉的意思是：新图床的图片地址是错误的。
> > 我的建议：
> > 先找一个正常点的页面测试 e.g https://sspai.com/post/83006 如果这个页面的图片没问题，然后再找一个图多点的页面 e.g. https://sspai.com/post/69972 测试，如果也没问题，然后测试出问题的页面以及不同的页面。
> > PS：那串 base64 代码是裂图的，跟这个问题无关。
> > PPS：如果只是偶发的情况，看下裂图的图片在你的 Github 上是否存在（且正确），如果不存在的话说明上传错误。
> > PPPS：综上，我个人不太建议使用 Github 图床，因为这个图床在大部分国内的网站都没法正常访问，而且 Github 也并不是一个图床产品 😂
> 
> 裂图的图片在 Github 上存在，但也无法正常显示。 我用其他图床试试

请问裂图的问题是什么原因，应该怎么处理呢？

**Comment by Kenshin** [comment]
> 请问裂图的问题是什么原因，应该怎么处理呢？

建议先用其它图床测试下，如果没问题，但上面提到的少数派的测试页面却存在这个问题的话，就是 Github 图床本身的问题。

我没用过 piclist 不清楚它会的图片链接是什么形式？

另外一点：我看你截图中有些是正常的图片，也是传到 Github 上面的吧，把地址给我看下。

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~
