### ISSUE TITLE
关于阅读时某些字体太细希望可以简便的调节字重

### ISSUE THREAD

**Issue by Bbestyang** [Kenshin/simpread#6157]
### 请描述你的建议或任何内容

某些分级比较多的页面，分级较低但是较为重要的内容，在打开简悦时所使用的字重太小导致字体比原页面更加难以观察
![{2F6FC28E-DB36-45a4-8429-06F27825986A}](https://github.com/Kenshin/simpread/assets/149667497/e8035167-f09e-43f9-a196-8d6c7c27cafa)
![{D9BC9B61-770A-4f7c-AA2A-58C84F7982C8}](https://github.com/Kenshin/simpread/assets/149667497/22fe2604-de0f-48a4-9707-d623a8cbdbb0
淡黄色的是原页面

**Comment by Kenshin** [comment]
嗨

如果对字体有要求的话，可以看下 https://github.com/Kenshin/simpread/discussions/4465 https://github.com/Kenshin/simpread/discussions/2519 这两个方法

看下 自定义样式 (https://simpread.pro/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 里面有字重的修改

<img width="372" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4a9780b1-1fd1-43e4-aef6-622aa7ed206e">

但我仍建议使用上面提到的两个方案。
