### ISSUE TITLE
想打开选项页，但一直在转圈，进不去

### ISSUE THREAD

**Issue by Sunsh4j** [Kenshin/simpread#6161]
### 描述这个错误

无法进入选项界面
![动画](https://github.com/Kenshin/simpread/assets/43169575/79f00404-b2b6-40c2-8638-5d87bbd72ef5)

### 复现步骤

右键扩展，想进入选项界面，但是一直进不去

### 操作系统

Win10

### 浏览器

chrome、edge

### 发生问题的网址

*

**Comment by Kenshin** [comment]
重启同步助手或者同步助手没有开。

如果还不行的话，估计是配置文件损坏造成的，可以使用 https://github.com/Kenshin/simpread/discussions/5750 修复。
