### ISSUE TITLE
同步助手的使用疑问

### ISSUE THREAD

**Issue by malingshu-art** [Kenshin/simpread#6162]
### 描述这个错误

同步助手运行时发生了错误，错误信息：ENOENT:no such file or directory,.open D\E00-Efficiency叭10.简悦·同步助手-1.2.0@win64小简悦同步助手配置 Obsidian@simpread\Z-剪藏附件1702106146528.png

### 复现步骤

1.设置自动触发快捷键
o b u n
o b u u
o b a a
o b a c
2.新页面阅读模式下，按键ob后立刻弹出错误对话框
3.同步助手运行时发生了错误，错误信息：ENOENT:no such file or directory,.open D\E00-Efficiency叭10.简悦·同步助手-1.2.0@win64小简悦同步助手配置 Obsidian@simpread\Z-剪藏附件1702106146528.png

### 操作系统

win10专业版

### 浏览器

chrome120.

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
`ENOENT:no such file or directory,.open D\E00-Efficiency叭10.简悦·同步助手-1.2.0@win64小简悦同步助手配置 Obsidian@simpread\Z-剪藏附件1702106146528.png`

这句话的意思是：没有在上述路径中找到 `Z-剪藏附件1702106146528.png` 跟自动化辅助增强插件无关，**跟你的路径设置有关**。

以下是一些建议：

1. 将同步助手解压缩并重命名为 `simpread@sync` 不建议使用 `10.简悦·同步助手-1.2.0@win64小简悦同步助手配置 Obsidian@simpread` 这么长的路径...

2. 导入到 Obsidian 建议按照教程的设置路径，当配置成功后再改为自己的路径。
