### ISSUE TITLE
选项页无法打开

### ISSUE THREAD

**Issue by shijurenya** [Kenshin/simpread#6163]
### 描述这个错误

2022年用过简悦，然后好长时间没用了，但是之前的配置文件还在（付费），导入进去，就卡死在录屏的最后那个界面卡了一个多小时没动静。试了三个浏览器，都是如此。

无标题视频——使用Clipchamp制作.mp4…

### 复现步骤

未解决。

### 操作系统

Win 11。

### 浏览器

谷歌浏览器、微软。

### 发生问题的网址

没有具体网址。

**Comment by shijurenya** [comment]
Uploading 无标题视频——使用Clipchamp制作.mp4…

**Comment by Kenshin** [comment]
重启同步助手或者同步助手没有开。

如果还不行的话，估计是配置文件损坏造成的，可以使用 https://github.com/Kenshin/simpread/discussions/5750 修复。

***

PS：我看不到你的录屏，猜测是上面原因造成的，有任何问题可以随时在继续讨论
