### ISSUE TITLE
打开阅读模式选项对话框后使用 ESC 退出时顺序错误

### ISSUE THREAD

**Issue by raxpkwd** [Kenshin/simpread#6164]
### 描述这个错误

配置同步坚果云后，在调整阅读模式背景色的时候，
突然弹出了【当前配置文件出错导致无法打开选项页】的报错，提示进行重装，重新导入配置文件，
重新安装插件以后，导入报错提供的配置文件后，还是会弹出【当前配置文件出错导致无法打开选项页】的报错
![image](https://github.com/Kenshin/simpread/assets/16618445/61a64a0f-faf0-4618-8d88-86045ce7a726)

刚发现了在我电脑上可以稳定复现的方法

### 复现步骤

1.打开任一网站，在阅读模式下，点击 **插件** 按钮
![image](https://github.com/Kenshin/simpread/assets/16618445/0e76165e-aaa7-41bf-a353-6204bd635407=200x1)

2.弹出页面样式选项菜单后，按下 **ESC** 键 或 **取消** 按钮
![image](https://github.com/Kenshin/simpread/assets/16618445/51f23242-7811-49dd-ab05-f04643995897=200x1)

3.响应的操作是关闭了 **阅读模式**
![image](https://github.com/Kenshin/simpread/assets/16618445/2708af40-475f-4e9e-9c95-03926e3173d6=200x1)

4.点击 **确认** 按钮
![image](https://github.com/Kenshin/simpread/assets/16618445/0d10dd97-8064-4666-9ac1-4047cdbd294b)

5.切换到简悦选项页 **刷新**，弹出配置文件出错的报错
![image](https://github.com/Kenshin/simpread/assets/16618445/83feb8f4-1426-42b8-9599-d250854f2a6f)

#### 全流程演示
![1](https://github.com/Kenshin/simpread/assets/16618445/ebb95db4-286a-4211-9fac-be0c63ed12f9)

#### 插件版本
![image](https://github.com/Kenshin/simpread/assets/16618445/c9240a4f-cc69-4628-96d7-91ebccad0099)

#### 恢复方法

由于报错后给的文件再次导入还是会有问题，所以我是从坚果云的历史文件中找回
![image](https://github.com/Kenshin/simpread/assets/16618445/88cde452-d19a-4cd2-9ecd-a163a0dc2b47)
可以看到错误的配置文件比正常文件要小一点

#### 想法

1.可能和其他因素有关，因为好像没有搜到类似的例子
2.按 **ESC** 时，我是想用 ESC 来代替取消按钮的操作，但是响应的操作是退出阅读模式
3.点击 **取消** 时，没有关闭菜单，也是退出阅读模式
4.点击 **确认** 保存时，可能先校验一下会不会出错比较好

### 操作系统

win10 企业版 LTSC

### 浏览器

edge 版本 120.0.2210.61 (正式版本) (64 位) 当前最新版

### 发生问题的网址

http://ksria.com/simpread/docs/#/%E8%81%9A%E7%84%A6%E6%A8%A1%E5%BC%8F

**Comment by Kenshin** [comment]
okay 收到，感谢详细测试 👍 我明天复现下。

好在这算是个例，也不属于常规性操作，目前就你这一例报告，甚至我都不知道这么做能引起错误… 😂

**Comment by raxpkwd** [comment]
应该是个例，我换了一台电脑，用新的账号测试是没这个问题的，
点击取消和ESC都可以正常关闭样式选项菜单

然后用有问题的账号，另一台电脑登录，使用 chrome 浏览器测试，能够复现错误，

用最开始发现问题的电脑，关闭了其他插件，只剩 simpread 插件测试，也能复现这个错误

所以估计原因可能是在这个账号的配置文件上

**Comment by raxpkwd** [comment]
> okay 收到，感谢详细测试 👍 我明天复现下。
> 
> 好在这算是个例，也不属于常规性操作，目前就你这一例报告，甚至我都不知道这么做能引起错误… 😂

刚重置配置文件后，又重测了一下，
一步步复原之前的配置项，可以初步判断是自动同步引起的

重置后，是正常的，但只要打开自动同步，就会触发bug
同步助手版本是1.2.0，

但比较了一下打开自动同步前后的配置文件，是完全一样的

**Comment by Kenshin** [comment]
> 重置后，是正常的，但只要打开自动同步，就会触发bug

并不是同步助手的 Bug 而是同步助手读取你本地的 `simpread_config.json` 而这个配置文件里面的结构错误造成的。

至于如何产生的，根据你的上下文猜测是应该是你提交时的问题产生的。

不过，如果使用了同步助手的话，也很容易解决：

开启同步助手的自动同步（这时会出现无法进入选项页的错误，不用管它），打开 http://localhost:7026/database/fixed 根据提示操作，然后重启浏览器。

关于这个功能的详细说明 https://github.com/Kenshin/simpread/discussions/5750

**Comment by raxpkwd** [comment]
> 开启同步助手的自动同步（这时会出现无法进入选项页的错误，不用管它），打开 http://localhost:7026/database/fixed 根据提示操作，然后重启浏览器。

一开始检查出了插件错误，但可以正常运行
打开自动同步后，按复现操作后报错，
然后再打开数据修复，提示无需修复，但选项页还是报错，重启浏览器以后也是

https://github.com/Kenshin/simpread/assets/16618445/1a796c1d-f849-456a-ac95-16b8bc27f0bb

**Comment by Kenshin** [comment]
okay 

谢谢测试，通过测试可以得出：

1. 这个错误没法通过修复程序修复，再加上你的描述是也是能证明是非常规性错误。
2. 修复功能可以检测一些常规性错误，尤其是稍后读数据结构错误造成的。

所以，我的建议：

1. 可以忽略这个问题。
2. 如果你感兴趣的话，可以把错误的配置发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6164

PS：如果同一个流程仅在某个环境下出错的话，其实完全可以忽略它 😂 我关闭这个 Issues，但并不耽误咱们继续讨论它。

**Comment by raxpkwd** [comment]
好的，理解您的决定，邮件已发，
附件的配置文件是关闭了坚果云配置后导出的，
这个bug虽然这个可能是特例，但对我是100%出现的，
而且在同步的两台电脑上（edge和chrome）都能复现，
并且自动同步对我来说是必要的，每天都要手动同步难免出错，
这个bug会让我在调整样式时，无法按 ESC 和 取消 键，
所以还是希望问题能得到解决，谢谢

**Comment by Kenshin** [comment]
> 配置文件是关闭了坚果云配置后导出的

这个配置文件是关闭自动同步且导入这个配置文件一定会出错，是吧？

正常情况的话，我肯定能帮你修复好。（有无法修复的情况，基本上可以忽略不计。）

> 这个bug会让我在调整样式时，无法按 ESC 和 取消 

不太理解，按照你的描述这个错误是出现在：弹出选项卡但退出了阅读模式后再保存时产生的。

所以避免这个情况就行，不会影响你调整样式。

**Comment by Kenshin** [comment]
> 现在弹出选项菜单后，如果要关闭菜单，我能选择的只有确定键

是的，或者点击关闭也行。

> 感觉调整的效果不好，想恢复之前的样式并关闭菜单，就只能刷新整个页面来代替取消操作，比较影响阅读

我不太理解为什么经常使用这个功能，这个功能算是 1.x 遗留功能，2.x 版应该使用下面的方式。

<img width="575" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/20a146e0-76ee-455e-bd32-98643aa73cd1">

**Comment by raxpkwd** [comment]
> 我不太理解为什么经常使用这个功能，这个功能算是 1.x 遗留功能，2.x 版应该使用下面的方式。

个人习惯原因吧，如果要调整某个插件的设置，
一般会习惯性的去插件栏找，而且旧版可以点击取消来放弃修改

高级控制面板感觉也挺好的，但需要习惯下

**Comment by Kenshin** [comment]
今天有点忙，总是不在电脑旁 😂

新版方案比旧版方案好很多，主要是旧版方案属于独占，所以使用效率其实并不大，旧版方案其实是给聚焦模式使用的。

而且从用户的反馈以及我的使用感受角度上来说，理论上布局等相关功能的调整属于「短期性」行为，通常不会长时间反复修改，所以你频繁修改的原因是？

**Comment by raxpkwd** [comment]
> 所以你频繁修改的原因是

按常理来说确实应该设置好以后就不太会去动它了，这几天频繁打开使用还是因为测试
不过继续往上溯源的话应该还有一点，就是插件图标本身比较显眼，让人想要去点吧

顺便一说，第一次点会弹出【已经启用控制栏面板，所以无法使用此功能】的提示，
![image](https://github.com/Kenshin/simpread/assets/16618445/1218677d-6c57-4b26-90ce-15b466c76639)
作为用户，自然就会想要了解是什么功能无法使用，
去选项页搜索关掉相关功能后，感觉关掉确实更顺手一点就保留了，
但后面用着用着就插件就崩了，于是来反馈bug 😂

**Comment by Kenshin** [comment]
> 插件图标本身比较显眼，动画也很解压，让人想要去点吧

😂

多说一句，如果你对字体有要求的话，可以试试 https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Atheme 里面提到的几种方案~

PS：今天没时间看配置文件了，原本因为一个小事情（自己的傻 B 购物经历），现在可能要跟 12351 扯皮 😂

PPS：发现这个 Issues 也讨论很多条了 😂 如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

PPPS：我先重开这个 Issues 吧，`ESC` 退出顺序错误毕竟应该优化下~

**Comment by raxpkwd** [comment]
> 你对字体有要求的话

好嘞，我研究下 👍

**Comment by Kenshin** [comment]
嗨，抱歉，我今天才有时间看下这个问题 😂

不过... 我导入了你的给我的配置文件并没有任何问题，是可以直接使用的。

然后，我也没有复现你提到的问题

***

> 打开选项卡后保存后自动退出

https://github.com/Kenshin/simpread/assets/81074/44bf9f2e-5829-4cc6-99c8-b5c2f208b67c

> 打开选项卡后，什么都不操作，直接 `ESC` 退出，先退出的是选项卡。

https://github.com/Kenshin/simpread/assets/81074/fd3c489c-0f88-4d12-b312-7165b81b2a9c

**Comment by raxpkwd** [comment]
> 不过... 我导入了你的给我的配置文件并没有任何问题，是可以直接使用的。

感谢，这就很奇怪了，难道问题不在配置文件上吗？
我刚刚重新配了下坚果云也是一样的

如果有需要的话，不知道这个可以帮助定位吗，
比较了几个页面的控制台报错，共同的内容是这个
![image](https://github.com/Kenshin/simpread/assets/16618445/41d1b82e-5f45-4a85-95c7-95e314d2b219)
关联的js文件到这里了
![image](https://github.com/Kenshin/simpread/assets/16618445/e32e5e5c-9ae8-4547-bd0a-5c88650bbec5)

不过用了几天2.x的设置感觉也挺不错的👍
要是不方便定位的话我还是用新的好了的😂

**Comment by Kenshin** [comment]
> 感谢，这就很奇怪了，难道问题不在配置文件上吗？

（猜测）可能是这样的，我看到你给我的配置文件里面开启了自动同步功能，如果你愿意折腾的话：

1. 根据下图所示修改

   <img width="362" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8d0d616d-d7ad-40a9-9f3b-d9d9971be0d3">

2. 删除并重新安装简悦。
3. 导入这个配置文件。
4. 然后再测试你遇到的问题。

> 关联的js文件到这里了

这个错误看起来是 CSS 样式错误，来自你的全局自定义样式或者你修改的样式（不确定）

***

其实新版（肯定比旧版）更好用 😂 

PS：因为 `ESC` 的问题不存在，所以我还是关闭这个 Issues 了  🌚

**Comment by Kenshin** [comment]
> 感谢，这就很奇怪了，难道问题不在配置文件上吗？

（猜测）可能是这样的，我看到你给我的配置文件里面开启了自动同步功能，如果你愿意折腾的话：

1. 根据下图所示修改

   <img width="362" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8d0d616d-d7ad-40a9-9f3b-d9d9971be0d3">

2. 删除并重新安装简悦。
3. 导入这个配置文件。
4. 然后再测试你遇到的问题。

> 关联的js文件到这里了

这个错误看起来是 CSS 样式错误，来自你的全局自定义样式或者你修改的样式（不确定）

***

其实新版（肯定比旧版）更好用 😂 

PS：因为 `ESC` 的问题不存在，所以我还是关闭这个 Issues 了  🌚
