### ISSUE TITLE
腾讯读书PC网页

### ISSUE THREAD

**Issue by Erik-1ood** [Kenshin/simpread#6165]
### 描述这个错误

阅读网页版的时候，不能正确提取内容。

### 复现步骤

阅读网页版的时候，不能正确提取内容。

### 操作系统

windows11

### 浏览器

chrome

### 发生问题的网址

https://weread.qq.com/

**Comment by Kenshin** [comment]
嗨，这类页面是不可以被适配的，我关闭这个 Issues 了~
