### ISSUE TITLE
网页中代码块使用阅读模式后没有显示

### ISSUE THREAD

**Issue by mygithub222225** [Kenshin/simpread#6169]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/90737189/d80bb389-1aaa-4883-8987-267cc9eac1bf)
切换到阅读模式后代码块没有显示

### 复现步骤

切换到阅读模式后代码块没有显示

### 操作系统

linux

### 浏览器

brave

### 发生问题的网址

https://xiaolincoding.com/os/4_process/process_commu.html#%E7%AE%A1%E9%81%93

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
