### ISSUE TITLE
使用SimpRead Sync导入md+assets到Obsidian失败

### ISSUE THREAD

**Issue by jx453331958** [Kenshin/simpread#6170]
### 描述这个错误

使用SimpRead Sync导入md+assets到Obsidian失败。使用rest api能够成功。

### 复现步骤

https://github.com/Kenshin/simpread/assets/26744792/577847d7-4936-4f8b-947e-864493ecbd35

<img width="817" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/2e0c1d2e-8c9a-469a-98bb-8327342ec8c8">

### 操作系统

macOS

### 浏览器

chrome  120.0.6099.71（正式版本） (arm64)

### 发生问题的网址

https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-2920749

**Comment by jx453331958** [comment]
<img width="982" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/0245adc8-b48d-4086-a5a5-da3800a80df5">

**Comment by jx453331958** [comment]
有没有办法提供一个debug的手段，方便通过日志自行排查

**Comment by jx453331958** [comment]
使用md+assets插件解决了，可以忽略了

**Comment by Kenshin** [comment]
恭喜解决  🎉 

> 有没有办法提供一个debug的手段，方便通过日志自行排查

同步助手有个 [日志系统](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/discussions/2902#discussioncomment-7826789

另外，这个问题还需要解释吗？
