### ISSUE TITLE
无法识别知乎文章中的网页链接卡片

### ISSUE THREAD

**Issue by kenlee412** [Kenshin/simpread#6172]
### 描述这个错误

将知乎文章导入到obsidian中时html和md均没有网页链接卡片
<img width="869" alt="iShot_2023-12-12_18 21 44" src="https://github.com/Kenshin/simpread/assets/35394091/3563103b-f4a1-4b30-9d27-a3a777e0c56e">
<img width="1074" alt="iShot_2023-12-12_18 20 24" src="https://github.com/Kenshin/simpread/assets/35394091/acfddc60-bd64-46b1-b050-c30d33044a5c">

### 复现步骤

导出即可发现此问题

### 操作系统

macos

### 浏览器

Chrome

### 发生问题的网址

https://zhuanlan.zhihu.com/p/656444021

**Comment by Kenshin** [comment]
嗨

请安装 https://github.com/Kenshin/simpread/discussions/2861 这个插件，如果使用了同步助手的自动同步，请通过 https://www.yuque.com/kenshin/simpread/fcw60u 安装

**Comment by kenlee412** [comment]
依然无法识别链接
<img width="1476" alt="image" src="https://github.com/Kenshin/simpread/assets/35394091/161490d9-aee9-4aee-8d15-07578c59059c">

**Comment by Kenshin** [comment]
emmm 我明天确认下。

你可以多试试不同的知乎专栏，看看是否是个例。

**Comment by kenlee412** [comment]
目前打开的带内链的专栏都无法正确识别
https://zhuanlan.zhihu.com/p/502029361
<img width="1476" alt="image" src="https://github.com/Kenshin/simpread/assets/35394091/db0b6d78-6b7f-432e-b3b4-342e23905176">
<img width="850" alt="image" src="https://github.com/Kenshin/simpread/assets/35394091/34a355e7-fe04-47e9-a9cf-0263d0d6e986">

**Comment by Kenshin** [comment]
我这边没有问题

<img width="826" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fa6c3bad-daa2-4a85-8e34-82be5fd0b023">

所以你应该是没有正确安装这个插件或安装后插件设置有误，留意下 https://github.com/Kenshin/simpread/issues/6172#issuecomment-1851755817 以及 https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341890 这两个说明。

**Comment by kenlee412** [comment]
感谢！完整重装后就能正确识别了！

**Comment by Kenshin** [comment]
Cool 解决就好 👍

***

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍
