### ISSUE TITLE
「定制导出」自定义导出标题不生效

### ISSUE THREAD

**Issue by jx453331958** [Kenshin/simpread#6174]
### 描述这个错误

「定制导出」自定义导出标题不生效
chrome配置如下：
<img width="1027" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/b5913e71-524e-4162-94f2-dd03a0dc994f">

使用导出到Obsidian的插件：
<img width="1333" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/8372d222-b5c8-441d-8e64-42bee4718146">

导出后的结果：
<img width="411" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/5da859ae-d4e4-441b-a343-afdfa0b0e3b0">

---

使用保存到稍后读：
<img width="1367" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/1e2cf7b8-98a9-4bd8-b9fd-0a68cc44657b">

稍后读的标题同样没有生效：
<img width="420" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/8ced3062-e567-4ecf-8243-7d78f25b1ea1">

### 复现步骤

如上

### 操作系统

macOs

### 浏览器

120.0.6099.71（正式版本） (arm64)

### 发生问题的网址

https://juejin.cn/post/7311597716785938451?utm_source=gold_browser_extension

**Comment by Kenshin** [comment]
😂

你大概使用的方式不对：图1 和 4 是错误的。

简单的说，导入到 Obsidian 是独立于简悦的外的一套插件（流程）体系，而图 1 和 4 是扩展端的一套逻辑，适合用户简单使用。

所以，如果你要使用 **导入到 Obsidian** 这套方案的话，建议：

1. 新用户的话，直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef （你应该不算是新用户了 😂

2. 这是导入到 Obsidian 的教程 https://www.yuque.com/kenshin/simpread/fr8zo5

***

PS：为了降低难度，自定义标题虽然是「自定义」，但目前仅支持简悦官方给出的一套自定义方案，暂时不支持自主定制。

**Comment by jx453331958** [comment]
> 😂
> 
> 你大概使用的方式不对：图1 和 4 是错误的。
> 
> 简单的说，导入到 Obsidian 是独立于简悦的外的一套插件（流程）体系，而图 1 和 4 是扩展端的一套逻辑，适合用户简单使用。
> 
> 所以，如果你要使用 **导入到 Obsidian** 这套方案的话，建议：
> 
> 1. 新用户的话，直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef （你应该不算是新用户了 😂
> 2. 这是导入到 Obsidian 的教程 https://www.yuque.com/kenshin/simpread/fr8zo5
> 
> PS：为了降低难度，自定义标题虽然是「自定义」，但目前仅支持简悦官方给出的一套自定义方案，暂时不支持自主定制。

好的大佬，我试试。感觉想用简悦实现剪藏导入，有N多种用法，都不知道该按哪个教程来

**Comment by jx453331958** [comment]
> > 😂
> > 你大概使用的方式不对：图1 和 4 是错误的。
> > 简单的说，导入到 Obsidian 是独立于简悦的外的一套插件（流程）体系，而图 1 和 4 是扩展端的一套逻辑，适合用户简单使用。
> > 所以，如果你要使用 **导入到 Obsidian** 这套方案的话，建议：
> > 
> > 1. 新用户的话，直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef （你应该不算是新用户了 😂
> > 2. 这是导入到 Obsidian 的教程 https://www.yuque.com/kenshin/simpread/fr8zo5
> > 
> > PS：为了降低难度，自定义标题虽然是「自定义」，但目前仅支持简悦官方给出的一套自定义方案，暂时不支持自主定制。
> 
> 好的大佬，我试试。感觉想用简悦实现剪藏导入，有N多种用法，都不知道该按哪个教程来

可以了 参照配置库改了改

**Comment by Kenshin** [comment]
哈，老用户就是厉害（方便），给个提示即可解决 👍

> 有N多种用法，都不知道该按哪个教程来

这里有个简单的比较 https://www.yuque.com/kenshin/simpread/psugef 简单的说，如果不使用同步助手的话，选择技术版即可。
