### ISSUE TITLE
提示Notion授权失败

### ISSUE THREAD

**Issue by Arthurwu24** [Kenshin/simpread#6175]
### 描述这个错误

<img width="381" alt="image" src="https://github.com/Kenshin/simpread/assets/9261202/aa55a066-e6dc-4393-bff0-e9c7cf456d02">

导入到Notion时，提示授权失败。但进入到配置页面去进行Notion授权的时候，勾选不上，也是失败的

### 复现步骤

1. 重新授权Notion，失败
2. 进入到「配置界面」，去单独授权Notion，也是失败

### 操作系统

macOS

### 浏览器

Chrome

### 发生问题的网址

www.baidu.com

**Comment by Kenshin** [comment]
嗨

这个功能是没问题的，不过目前不建议使用此方式，请使用更好的插件方案 https://github.com/Kenshin/simpread/discussions/4954 以及 https://github.com/Kenshin/simpread/discussions/3572

也可以看下这个教程 https://www.yuque.com/kenshin/simpread/zx3bcz （不确定你是否需要这个教程的全部内容，按需设置即可）
