### ISSUE TITLE
高级帐户购买后绑定提示“一个帐户只能绑定一个密钥”

### ISSUE THREAD

**Issue by ytiange** [Kenshin/simpread#6179]
### 描述这个错误

如附件，领取兑换码后，第一次使用绑定功能，即提示一个帐户只能绑定一个密钥
尝试使用恢复功能，提示登录过多的浏览器，不确定这个提示咋来的，目前只有办公室一台电脑上用了应该，家里电脑虽然有chrome的自动同步插件，但应该不包含帐户信息吧
使用找回UID，提示License不正确？
![微信图片_20231215092641](https://github.com/Kenshin/simpread/assets/153484890/322fb626-f10e-4000-9424-0f824d5bd409)
![微信图片_202312150926411](https://github.com/Kenshin/simpread/assets/153484890/ecdf8fe7-3854-40fe-be27-d34c9653ed83)
![微信图片_202312150926412](https://github.com/Kenshin/simpread/assets/153484890/f6cb6c21-5573-4e08-b43c-23a1ce99a0e8)
![微信图片_202312150926413](https://github.com/Kenshin/simpread/assets/153484890/2048be32-6ffa-4513-9052-c28d0c36cf82)
![微信图片_202312150926414](https://github.com/Kenshin/simpread/assets/153484890/8823fc58-b885-425f-a6fd-65f462ce6e7f)
![微信图片_202312150926415](https://github.com/Kenshin/simpread/assets/153484890/37faeffe-172b-4533-9141-78c34377374d)
![微信图片_202312150926416](https://github.com/Kenshin/simpread/assets/153484890/d1990b65-37e2-49a0-92ad-39e4fbc3809c)
![微信图片_202312150926417](https://github.com/Kenshin/simpread/assets/153484890/ef40eab9-4607-4e3e-a458-e62092ba30e3)

### 复现步骤

1.领取兑换码
2.绑定，提示失败
3.尝试恢复，提示登录过多的浏览器，但只有本机在用啊，不知道一个机器上打开多个chrome算不算
4.尝试找回uid，提示兑换码不正确
UID是挺长的一串xxxx那个吗，如附件

### 操作系统

win11

### 浏览器

chrome 120.0.6099.109

### 发生问题的网址

无

**Comment by Kenshin** [comment]
嗨

你应该使用了配合库方案，配置库方案里面是 Demo UID，当然不能绑定成功，在配置库的说明中有详细说明，有也说明告诉你如何更改。

https://www.yuque.com/kenshin/simpread/wq35mh#7522249b

**Comment by ytiange** [comment]
oo  还真有可能是因为我在还没购买的时候尝试过导入配置库，当时也没备份uid，那现在也无法找回原有uid了，是配置文件-清除当前全部数据吗，这样生成新的uid，然后再去绑定即可？之前购买的时候填写的uid就是demo uid，请问会有影响吗

**Comment by Kenshin** [comment]
1. 找个新浏览器安装简悦，然后获得 UID （每个 UID 都是个唯一序列）

2. 如果没有需要留存的配置的话，重新安装简悦，然后获得 UID （每个 UID 都是个唯一序列）
