### ISSUE TITLE
减少变更通知

### ISSUE THREAD

**Issue by allinu** [Kenshin/simpread#6180]
### 请描述你的建议或任何内容

每次进行标注之后因为会触发自动化流程，然后右上角一直显示通知，大多数情况会遮挡很大一部分面积，这样很影响使用，能否减少通知频次，或者使用什么更加友好的通知方式，比如，只显示失败的操作，或者减少通知面积，减小字体，合并通知等

### 补充说明

<img width="380" alt="image" src="https://github.com/Kenshin/simpread/assets/32992109/b23ef650-caf6-4127-808f-34b0c60ad4f4">

**Comment by Kenshin** [comment]
嗨

如果你使用了自动化辅助增强插件的话，试试 https://github.com/Kenshin/simpread/discussions/3596#discussioncomment-6687745

否则的话，下个版本解决。
