### ISSUE TITLE
新站适配：MSN 中国

### ISSUE THREAD

**Issue by coffiner** [Kenshin/simpread#6181]
### 需要适配的新站

https://www.msn.cn/zh-cn/channel/topic/%E8%A6%81%E9%97%BB/tp-Y_77f04c37-b63e-46b4-a990-e926f7d129ff?ocid=binghp01

### 有需要请描述这个站的性质

新闻站，里面有比较全面的新闻内容和文章内容，并且是bing。com首页推荐的资讯内容。建议适配

**Comment by Kenshin** [comment]
okay 收到，谢谢提交，适配后会在这里通知你~

**Comment by Kenshin** [comment]
嗨，MSN 这个站点已适配完毕。

#### 如何更新

https://github.com/Kenshin/simpread/issues/6541#issuecomment-2156314697

#### 效果如下

<img width="1806" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fad680a2-6978-4418-b403-0861690e74f0">

***

我关闭这个 Issues，有任何问题请在 https://github.com/Kenshin/simpread/issues/6541 讨论
