### ISSUE TITLE
关于通过简悦自动备份文章到 DEVONthink 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6183]
这个功能我不知道改了什么配置，就是每次更改都会保存一个文件，也就是一个稍后阅读文章会在更改后添加到inbox，我忘记是不是更改了什么配置导致还是怎么样，还有我的数据库是加密的数据库，不知道这样是不是会有影响

_Originally posted by @allinu in https://github.com/Kenshin/simpread/discussions/3235#discussioncomment-7864931_

**Comment by Kenshin** [comment]
@allinu

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

我不太理解你的问题，建议详细描述~

**Comment by allinu** [comment]
@Kenshin 就是devonthink的inbox文件夹大概是这样的一个原理，放在里面的文件会被devonthink立即保存到数据库中，然后原来位置的文件，也就是inbox中就为空的了，然后每新加一条标注，都会导出一个本地文件到inbox，devonthink也就会重复操作一次，devonthink不会覆盖原来的文件，这就使得devonthink的inbox中会存在多个同名文件

**Comment by Kenshin** [comment]
emmm 我大概知道了…

你应该使用 Indexes 方式，之前的教程也是建议使用 Indexes 方案。

我没用过你提到的 Inbox 方式，可能咱们使用 devonthink 的方式不用。
