### ISSUE TITLE
加入「稍后读」之后，「自动化」导出HTML无法被触发

### ISSUE THREAD

**Issue by jx453331958** [Kenshin/simpread#6186]
### 描述这个错误

使用的obsidian@sync这个模版，直接替换uid为高级账户之后使用。
在配置了添加「稍后读」，「自动化导出HTML」之后，在页面中加入稍后读，无法触发导出HTML的任务。

### 复现步骤

开启自动化功能：
<img width="922" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/35d9cbe2-6c7e-4d1d-bd7e-23a09bd33a37">

开启自动同步：
<img width="883" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/51b1f5be-116d-4240-a970-ab5144f4de14">

Obsidian插件配置：
<img width="644" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/bbb322de-f3a6-4079-afa6-d8c5ac1f1f7b">

同步助手配置：
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/f5a37c78-c1f6-4776-8f94-c915f57f338b">

simpleread-sync配置：
<img width="797" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/bfe5e540-f41f-4925-b8f9-e82ea74612a5">

点击保存到「稍后读」：
<img width="1305" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/b068f39a-3717-46ed-86ab-152e7032a3b5">

本地自动化导出了2个Markdown文件，但是没有HTML：
<img width="672" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/15ffcb39-787e-4899-97ea-3a934cd31f04">

「稍后读」中显示的是使用了本地的文件：
<img width="380" alt="image" src="https://github.com/Kenshin/simpread/assets/26744792/04501e74-c742-4e9a-b197-1035c8f8df04">

### 其他相关说明

还有几个想咨询的问题：
1. 「稍后读」进行跨设备同步，依赖的是.md还是.html文件？
2. @annote文件是否可以自定义导出到其他目录，不和正文放到一个目录下（不然在Obsidian中总是会出现两篇相同名字的md）
3. 「导入到Obsidian选项」这个配置是只在浏览器端控制吗，感觉这里面配置的「自动化」开关修改之后，如果在简悦「偏好设置」中的自动化进行一些修改，那么「导入到Obsidian选项」的「自动化」就会被打开或者关闭，感觉是有冲突。
4. 「导入到Obsidian选项」和「simpread-sync」这个Obsidian插件的功能有什么区别，一个有「自动化」开关，另一个没有，不清楚在使用过程中，以哪个插件的配置为准

### 操作系统

macos

### 浏览器

版本 120.0.6099.109（正式版本） (arm64)

### 发生问题的网址

https://juejin.cn/post/7269952188927017015?utm_source=gold_browser_extension

**Comment by Kenshin** [comment]
> 在页面中加入稍后读，无法触发导出HTML的任务

触发自动化的条件：进入阅读模式然后使用快捷键 `d d` 。

> 「稍后读」进行跨设备同步，依赖的是.md还是.html文件？

都不是，或者说你问题的不对，简悦是 Local First 类产品，跟 Obsidian 一样，理论上是 `simpread_config.json` 以及 `ouput` 里面的本地 `.html` 文件。

> 文件是否可以自定义导出到其他目录，不和正文放到一个目录下...

理论上可以，但不建议这么做，除非你玩明白后。

> 「导入到Obsidian选项」这个配置是只在浏览器端控制吗

是的，你使用的这套方案只能在阅读模式下使用，无法在扩展端的稍后读中使用。如果使用了这套系统，就不建议在扩展端设置自动化。

但它们本质上并不冲突。

> 「导入到Obsidian选项」和「simpread-sync」这个Obsidian插件的功能有什么区别

前者是简悦的插件，负责简悦这边的导入。
后者是 Obsidian 的插件，负责简悦在 Obsidian 的使用，比如：可以集成简悦的标注系统到 Obsidian 的右侧。

它们都是有用的，缺一不可。

***

配置库是可以运行某个功能的最优化方案，对于新（或不太动手的）用户来说，这是最优解。

当然，作为动手能力强的用户来说，配置库方案仅仅只是个「基础」，在这个基础上可以有很多玩法儿~
