### ISSUE TITLE
保存到github总是提示请稍后重试

### ISSUE THREAD

**Issue by CodingYourAmbition** [Kenshin/simpread#6188]
### 描述这个错误

github授权成功后，保存到github总是提示请稍后重试，然后我就怀疑是不是token有问题，我重新生成授权后还是不行。然后我就把token和链接都删掉，都没有token,还是显示授权成功，是缓存的原因吗

### 复现步骤

授权成功后，保存，提示请稍后重试

### 其他相关说明

![3](https://github.com/Kenshin/simpread/assets/153473257/bc0ba348-c5fa-4dec-9fd5-bd7c1b609d66)

### 操作系统

chrome

### 浏览器

chrome

### 发生问题的网址

.

**Comment by Kenshin** [comment]
emmmm

在第一个图出现后，**请重启浏览器** 后再测试下。

PS：目前没有用户反馈这个情况。

**Comment by CodingYourAmbition** [comment]
我保存到语雀吧，重启不行

**Comment by CodingYourAmbition** [comment]
好了好了，可能网络的问题，谢了

**Comment by Kenshin** [comment]
okay 没问题就好，我关闭这个 Issues 😄

***

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍
