### ISSUE TITLE
稍后读中的文章无法进入阅读模式！

### ISSUE THREAD

**Issue by bmeww23** [Kenshin/simpread#6189]
### 描述这个错误

稍后读中存放的文章，在稍后读中点击阅读模式后，一直显示加载中的图标，无法正常显示。只能点击原页面查看。

### 复现步骤

1. 进入稍后读；
2. 点击任意一个文章；
3. 点击阅读模式。

### 操作系统

win10 x64

### 浏览器

chrome 版本 120.0.6099.110（正式版本）

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

**Comment by Kenshin** [comment]
嗨，你需要使用 **知识库方案**，这是一站式教程 https://www.yuque.com/kenshin/simpread/wkswh7
