### ISSUE TITLE
简悦配置的插件管理，按钮不显示

### ISSUE THREAD

**Issue by reedsu** [Kenshin/simpread#6190]
### 描述这个错误

问题1：插件管理的页面，插件的几个按钮都不会显示。如图1
![CleanShot 2023-12-19 at 13 48 07@2x](https://github.com/Kenshin/simpread/assets/17920825/083d7c6e-8bb2-454d-bc8e-d732a00ecc7c)

问题2: 动作、插件触发器，图标也都没显示。如图2
![CleanShot 2023-12-19 at 13 49 40@2x](https://github.com/Kenshin/simpread/assets/17920825/839e09ab-5a47-4710-abdb-3215501e486b)

### 复现步骤

见上方描述。
试过重新安装插件管理器，也清除过本地全部插件再重新安装，也都是一样的。

### 操作系统

MacOS

### 浏览器

Chrome 120.0.6099.109， Arc浏览器最新版本

### 发生问题的网址

无

**Comment by Kenshin** [comment]
嗨，这是因为你的网络问题造成的，你可以试试访问 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/regular.min.css 能否打开？

建议更改下你的 DNS，换用阿里云之类靠谱的国内 DNS 提供商。

**Comment by Kenshin** [comment]
补充下：

1. 第二个图在某些网站也是无法使用的，如 wx 公众号
2. 第二个图应该是旧版效果（或者你主动调整为旧版效果），新版如下


<img width="494" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/af45eb59-667f-4443-a3d4-a35aa89f7b23">

**Comment by reedsu** [comment]
好的 ，好像确实是网络的问题。
非常感谢回复～

**Comment by Kenshin** [comment]
小事情 😄

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
