### ISSUE TITLE
不同浏览器之间添加至稍后读不能同步在同一个账户里

### ISSUE THREAD

**Issue by TIMcibdy1996** [Kenshin/simpread#6193]
### 请描述你的建议或任何内容

我用谷歌浏览器使用简悦插件添加至稍后读的网址，在edge浏览器中不会出现，这是什么原因呢

### 补充说明

是需要同步配置文件吗

**Comment by Kenshin** [comment]
嗨

简悦是基于 Local first 类的产品，为了确保用户隐私最大化，所以并没有你认为的「账户」功能，细节可以看下 https://www.yuque.com/kenshin/simpread/zilk5b

但你可以使用同步助手的自动同步来实现不同设备间的数据同步功能，一站式教程可以看 https://www.yuque.com/kenshin/simpread/wkswh7

如果是新用户的话，也可以直接使用配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0
