### ISSUE TITLE
导出为md突然失效，导出提示，导出失败，为实验性功能，请问怎么回事？

### ISSUE THREAD

**Issue by gabornj** [Kenshin/simpread#6194]
### 描述这个错误

如题所示
网页导出失败

### 复现步骤

1、打开网页https://plantuml.com/zh/salt
2、点击 simpread扩展
3、右下3点，导出为markdown
4、提示大致：“导出失败，为实验性功能，请提交issue”

### 操作系统

windows10

### 浏览器

chrome 

### 发生问题的网址

https://plantuml.com/zh/salt

**Comment by Kenshin** [comment]
emmm

1. 看下你的选项页，有可能是你的高级账户「掉」了，使用此方式解决 https://www.yuque.com/kenshin/simpread/ga970q 然后重启浏览器再重新测试。

2. 如果仍有问题的话，请测试下其它页面是否同样存在问题 e.g. https://sspai.com/post/69972

简悦的导出方案有很多，建议详细说下，比如：

1. 是否使用了同步助手
2. 是通过浏览器下载？还是同步助手下载等。
