### ISSUE TITLE
阅读模式默认主题能否深浅色模式分别设置？

### ISSUE THREAD

**Issue by PupupupuTong** [Kenshin/simpread#6196]
### 请描述你的建议或任何内容

之前提过导出到本地的html文件由于阅读模式主题与系统冲突而出现颜色异常导致字看不清的问题，或许可以通过这种方式解决？

### 补充说明

另外，偏好设置界面考虑也支持深色模式吗。。。晚上打开要亮瞎了

**Comment by Kenshin** [comment]
> 偏好设置界面考虑也支持深色模式吗

😂 暂时不能，但我记得有个插件（或类似的方式）可以实现。

> `阅读模式默认主题能否深浅色模式分别设置？` 与 `之前提过导出到本地的html文件由于阅读模式主题与系统冲突而出现颜色异常导致字看不清的问题，或许可以通过这种方式解决？`

我没太理解你的问题，也就是说从我的角度理解这两段话不存在逻辑关系。

你可以直接告诉我目前遇到什么问题。

**Comment by PupupupuTong** [comment]
> 但我记得有个插件（或类似的方式）可以实现。

你指dark reader？很遗憾该插件在偏好设置界面不能生效😭

> 你可以直接告诉我目前遇到什么问题。

就是这个问题 https://github.com/Kenshin/simpread/issues/5423 ，我发现和深浅色模式切换密切相关，故作此猜测

**Comment by Kenshin** [comment]
了解了 😂 其实没啥关系。

PS：我先关闭这个 Issues 了，感觉似乎「用处」不大  🌚
