### ISSUE TITLE
导入Notion后，显示的图片尺寸过大，能否增加限制图片尺寸的设置

### ISSUE THREAD

**Issue by Sunsh4j** [Kenshin/simpread#6198]
### 请描述你的建议或任何内容

如题

### 补充说明

如题

**Comment by Kenshin** [comment]
嗨

导入到 Notion 后图片是多大的，就会显示多大，这不是简悦能控制的 😂 非要说的话是 Notion 自身的问题。

但在阅读模式下，可以使用 [这个插件](https://github.com/Kenshin/simpread/discussions/1598) 让图片显示的小点，但也无法让 Notion 改变这点。
