### ISSUE TITLE
对于有代码模块的博客网站，行数与内容显示分离

### ISSUE THREAD

**Issue by hanley99** [Kenshin/simpread#620]
对于有代码模块的博客网站，行数与内容显示分离，读起来不方便。[https://blog.csdn.net/qq_36357820/article/details/102895410](url)

**Comment by Kenshin** [comment]
谢谢反馈。

你可以使用 [【插件】代码段的专项整治，包括：高亮，代码优化，去重等](https://github.com/Kenshin/simpread/issues/500) 来解决你的问题。

同时，建议在提问时，翻翻 **Github issues 其他朋友** 是否有同样的问题。

同时 [常见问题汇总](https://github.com/Kenshin/simpread/issues/618) & `简悦 选项页 右下角` 均有多种新手入门方案。

***

当然，下个版本我会加强对某些特殊页面识别时候的用户指引。
