### ISSUE TITLE
微信公众号辅助增强已经通过插件管理器安装，但插件触发器未见到相关选项

### ISSUE THREAD

**Issue by cwbctr1** [Kenshin/simpread#6200]
### 描述这个错误

微信公众号辅助增强已经通过插件管理器安装，但插件触发器未见到相关选项

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/22217228/78334427-9277-445f-85a9-d71993b48a82)
如图，在插件管理器，已安装插件中有微信公众号辅助增强，但是右侧的插件触发器未见相关选项，同时微信公众号的公式字体异常，未见改善。
![image](https://github.com/Kenshin/simpread/assets/22217228/b679c8c3-d2d7-45b6-8426-65c36b9f38ba)

### 操作系统

macos

### 浏览器

arc浏览器与edge浏览器均试过

### 发生问题的网址

https://mp.weixin.qq.com/s/izhhZNLBoZQciZNFZkx45g

**Comment by Kenshin** [comment]
emmm

理论上严格使用插件管理器的安装方式肯定没问题... 你可以试试下面的方式

<img width="492" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ca655045-e87c-4b04-bda2-749a0d4b5a41">

**Comment by cwbctr1** [comment]
> emmm
> 
> 理论上严格使用插件管理器的安装方式肯定没问题... 你可以试试下面的方式
> 
> <img alt="image" width="492" src="https://private-user-images.githubusercontent.com/81074/292606557-ca655045-e87c-4b04-bda2-749a0d4b5a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTU4ODIsIm5iZiI6MTcwMzMxNTU4MiwicGF0aCI6Ii84MTA3NC8yOTI2MDY1NTctY2E2NTUwNDUtZTg3Yy00YjA0LWJkYTItNzQ5YTBkNGI1YTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA3MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YzlmODIyZWM4ZTMyYzI3YmIxMDUyZTkzODk2N2QxODQ5OWRkY2Y0ZWZiN2E1MTJmY2M2NjEwNDNlOWY0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Keh4dug4vQBX8C0G4jtyDUjUwd4dcWS6imktHFja29U">

通过您说的方式已解决，非常感谢。

**Comment by Kenshin** [comment]
哈，没问题就好，我关闭这个 Issues 😄

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍
