### ISSUE TITLE
导出为离线html失败

### ISSUE THREAD

**Issue by lakako** [Kenshin/simpread#6201]
### 描述这个错误

点击导出为离线html，没能成功导出html
![Uploading image.png…]()

### 复现步骤

点击导出为离线html，没能成功导出html

### 其他相关说明

edge版本：120.0.2210.91 

### 操作系统

windows

### 浏览器

120.0.2210.91 

### 发生问题的网址

https://www.zhihu.com/question/635935024/answer/3335271341

**Comment by Kenshin** [comment]
嗨

我这边没有复现，所以：

1. 其它页面知乎或少数派是否有问题？
2. 你使用了什么导出方式？是基础版功能还是同步助手的增强导出？
3. 试试安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 能否解决？
4. 在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

PS：你的截图没有上传成功，建议详细描述下你的问题。
