### ISSUE TITLE
【插件触发器】不显示

### ISSUE THREAD

**Issue by sunmua** [Kenshin/simpread#6203]
### 描述这个错误

下载了几个简悦内部插件，但是动作一栏没有【插件触发栏】，刷新重新进入阅读模式再看也没有。
![2023-12-23_17-15-45](https://github.com/Kenshin/simpread/assets/51434546/adef260e-ea24-45e9-804a-79c2ca1c28d4)

### 复现步骤

我已在谷歌确认简悦是2.0最新版本，尝试过清除了所有插件重新下载，重新进入阅读模式，点击右下角，在动作一栏里仍然没有插件触发栏出现。所以我无法进行开启某些插件比如简繁转换的操作，也无法精简动作栏其他项目。希望得到帮助，谢谢！

### 其他相关说明

其他配置：高级版＋同步已开启。

### 操作系统

win10

### 浏览器

谷歌 版本 120.0.6099.111（正式版本） （64 位）

### 发生问题的网址

任意网址例如https://medium.com/heptabase/the-best-way-to-acquire-knowledge-from-readings-abf9357814d1#c3cd

**Comment by sunmua** [comment]
https://www.yuque.com/kenshin/simpread/fcw60u 已解决，安装文章里所说下载插件管理器。再在插件管理器里复制想下载的插件链接，点安装再点导入。插件就会出现在动作栏里的插件配置器里了。
或者#2342 也讲了。

**Comment by Kenshin** [comment]
哈，恭喜自救成功，我关闭这个 Issues 👍

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
