### ISSUE TITLE
onedrive同步

### ISSUE THREAD

**Issue by TIMcibdy1996** [Kenshin/simpread#6204]
### 请描述你的建议或任何内容

你好，我遇到的问题是，电脑重装系统后稍后读保存的内容不在了。之前也下载了同步助手，是我的同步方式没有设置好的原因吗?还有一个问题是，保存网页版pdf时，OneDrive会自动删除刚保存的文件。

### 补充说明

稍后读是保存在本地，本地保存内容删除，那在不同设备上、不同浏览器上内容都没有了吗

**Comment by Kenshin** [comment]
嗨

如果你使用了同步助手的自动同步功能，在你的本地应该有个 `simpread_config.json` 文件。

你看下是否存在这个文件，并且这个文件的更新日期是否正确？

> 还有一个问题是，保存网页版pdf时，OneDrive会自动删除刚保存的文件。

使用 OneDrive 保存 PDF 时确实有点问题，但也能解决，你用的是什么 PDF 保存方案？

**Comment by TIMcibdy1996** [comment]
你好
可能我不理解同步具体是指同步哪些内容
根据我自己的使用经历，同步配置文件的功能在于，我在同一台电脑不同浏览器中稍后读的内容相同，这个是不是只和配置文件有关，没有用到同步助手
同步助手对于稍后读可以做些什么呢？是要配合自动化插件，自动导入到本地？重装系统后之前账户的稍后读内容都不在了

我想导出pdf的目的是将网页内容转化为pdf保存下来，就是点击“保存为pdf”按钮，就是一般的操作，pdf导出到onedrive，OneDrive提示已保存成功，但立马又会自动删除

**Comment by Kenshin** [comment]
> 根据我自己的使用经历，同步配置文件的功能在于，我在同一台电脑不同浏览器中稍后读的内容相同，这个是不是只和配置文件有关，没有用到同步助手

跟配置文件有关，也跟同步助手有关。

同步助手就是按照字面意思理解：负责「同步」的助手，而同步的内容就是用户的数据，包括：阅读模式等相关配置、插件配置与稍后读（标注）数据。

当然，同步助手不仅具有同步功能，还有提供了很多额外功能，如：增强导出等等。

感兴趣的话，可以看下 https://github.com/Kenshin/simpread/discussions/1700 里面的介绍 以及 它的一些 [特别需要说明的功能](https://github.com/Kenshin/simpread/discussions/categories/%E5%90%8C%E6%AD%A5%E5%8A%A9%E6%89%8B)。

> 重装系统后之前账户的稍后读内容都不在了

我不确定你是否严格按照同步助手的设置方式，如果是的话，**数据是在你本地或你在本地设置的网盘，如简悦官方推荐的：坚果云**。

严格的最低标准：是要使用同步助手的自动同步功能 [这是教程](https://www.yuque.com/kenshin/simpread/wkswh7) 我记得我给过你相关链接。

***

关于你提到的这些问题，我建议：直接使用简悦的配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0 里面直接带了 PDF 方案。

至于你对同步助手的理解，可以看下上面我提到的链接。

多设备的同步和数据间的共享，可以看下  https://www.yuque.com/kenshin/simpread/ebwu7g 里面没有教程，但是会有一些基于同步助手的使用底层逻辑。
