### ISSUE TITLE
知乎导出离线md时，公式代码重复

### ISSUE THREAD

**Issue by wedipe** [Kenshin/simpread#6205]
### 描述这个错误

我在利用简悦导出知乎的带有公式的文章时，出现了部分代码重复，例如 $A,B$ A,B 前一个包在美元符号里，后一个重复了，但没有包在美元符号里。我怀疑是正则出了什么问题。（此外，这篇文章转换过后的名字调用pandoc转换时会报错，需要修改文件名，不知道为啥）

### 复现步骤

1. 打开知乎网站https://zhuanlan.zhihu.com/p/671248198
2. 导出离线markdown
3. 上传至mathpix web app（只是一个对公式支持很好的线上markdown编辑器，但本地打开也能发现代码出问题了）
4. 然后转换过后，有问题的md源代码，我选了一段贴在其他相关说明了

### 其他相关说明

> 过不在圆上的一点 $P$P 引两条与圆相交的直线$l_1$l_1、$l_2$ l_2 ，分别与圆交于 $A、B$A、B 与 $C、D$C、D ，则有：$PA·PB=PC·PD$ PA·PB=PC·PD ，特殊地，当 $C、D$C、D 重合，即 $PC$PC 为切线时，有 $PA·PB=PC^2$PA·PB=PC^2

### 操作系统

windows

### 浏览器

edge（应该是当前最新版，因为我开了自动升级）

### 发生问题的网址

https://zhuanlan.zhihu.com/p/671248198

**Comment by wedipe** [comment]
浏览器版本： 120.0.2210.91 (正式版本) (64 位)

**Comment by Kenshin** [comment]
嗨，请使用 https://github.com/Kenshin/simpread/discussions/2861 这个插件来解决。

如果你使用了同步助手的自动同步功能，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装插件。

**Comment by Kenshin** [comment]
附一个导入到 Obsidian 的效果

<img width="835" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3fefb39d-a2cd-41fa-b0cb-ea31c723809e">
