### ISSUE TITLE
导出的离线html文件建议取消图片的点击

### ISSUE THREAD

**Issue by haolly** [Kenshin/simpread#6206]
### 请描述你的建议或任何内容

本身就是“离线”文件了，点击也没有啥用处，多次一举

**Comment by Kenshin** [comment]
没理解你的意思...什么叫做「图片的点击」？

**Comment by haolly** [comment]
> 没理解你的意思...什么叫做「图片的点击」？

就是图片带了href="xxx"

**Comment by Kenshin** [comment]
okay 明白你的意思了 😂

虽然我能 Get 到你的想法，但稍微有些绝对，或许有些用户反过来考虑，所以还是以默认为准。
