### ISSUE TITLE
起点中文网进入阅读模式之后无法滚动页面

### ISSUE THREAD

**Issue by eterlan** [Kenshin/simpread#6207]
### 描述这个错误

如题。我发现是 eagle 的插件（那个收集图片的插件）导致的，禁用插件后就没事了。
还有个问题是起点会禁用选中文字，虽然通过修改 `div app userselect`可以解决，但是仍然无法使用标注功能。

### 复现步骤

1. 下载 eagle 插件
2. 打开起点中文网
3. 进入阅读模式
4. 尝试滑动、标注

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

https://www.qidian.com/chapter/1036237650/763948610/

**Comment by Kenshin** [comment]
> 我发现是 eagle 的插件（那个收集图片的插件）导致的，禁用插件后就没事了

okay 👍

> 起点会禁用选中文字，虽然通过修改 div app userselect可以解决，但是仍然无法使用标注功能。

emmm 是这样的，简悦是阅读模式类产品，理论上仅获取正文并不会对原页面有任何功能性的改动，所以譬如：解决右键无法使用、解决无法复制粘贴等并不是简悦的功能诉求。

但部分页面在使用简悦后「症状」消失了（可以解决此问题）的原因：简悦会新建一个「层」，所以仅监控 `<body>` 段落的话简悦就不会受到影响，但如果网站监控了 `<html>` 简悦仍会处于「监控状态」。

所以，简悦并不会专门提供这些功能。
