### ISSUE TITLE
【插件管理器】通过插件管理器安装插件后选择“导入当前插件”提示“保存失败”

### ISSUE THREAD

**Issue by Wilenoch** [Kenshin/simpread#6208]
### 描述这个错误

由于既无法访问插件中心（无法点开插件详情页面，如 #2990 所述），且即使通过指定插件页面安装后也无法生效，遂采用 #2342 方法，即通过插件管理器安装（已关闭自动同步）。但安装时，在点击安装当前插件并安装完成后，再点击“导入当前插件”会同时提示“保存失败”和“已启用自动同步但没有运行同步助手”，尽管同步助手正在运行中。且在此之后，插件管理器的动作也会消失。重新安装插件管理器，仍会出现以上问题。
试图解决但已失败QAQ

### 复现步骤

1. 关闭自动同步
2. 删除本地所有插件
3. 重启浏览器
4. 参考https://www.yuque.com/kenshin/simpread/fcw60u，通过https://simpread.ksria.cn/plugins/details/UEzvAXNSe5 安装“插件管理器”
5. 在网页中试图通过插件管理器安装插件，如[导入到Ob](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z)，点击安装当前插件
6. 点击导入当前插件
7. 报错

### 其他相关说明

也许可能不一定值得注意的是，教程中示例的网页https://sspai.com/post/69972 无法触发阅读模式，其他均正常
折腾一个小时也没解决救救孩子（

### 操作系统

Win11 23H2 22635.2771

### 浏览器

CentBrowser 5.0.1002.354

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
emmm 感觉「问题」较多哦 😂

> 由于既无法访问插件中心（无法点开插件详情页面

我也遇到这个情况了... 我先研究下。（上午的时候还没有这个情况...）初步怀疑是 Chrome 版本升级造成的一些字体无法显示。

> 安装时，在点击安装当前插件并安装完成后，再点击“导入当前插件”会同时提示“保存失败”和“已启用自动同步但没有运行同步助手”，尽管同步助手正在运行中

是不是你的高级账户「掉了」试试 https://www.yuque.com/kenshin/simpread/sw4m21 然后重启浏览器再确认下。

或者你的同步助手「掉了」，如下图所示

<img width="654" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/db395b80-f692-4820-a89a-297deb405b76">

请使用下图方式重新激活同步助手

<img width="891" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2a4e4267-df66-4f43-9ed9-50a9eef1453a">

然后重启浏览器 & 同步助手。

***

当确定这些问题时，再使用插件管理器安装插件。

**Comment by Kenshin** [comment]
更新下：

不是浏览器版本升级造成的，而是  `cdn.staticfile.org` 出问题造成的，我看下联络它们。

**Comment by Wilenoch** [comment]
qaq, 不知为何现在 简悦-选项页 打不开了因此无法测试… 重装插件重启浏览器似乎也没什么效果
![image](https://github.com/Kenshin/simpread/assets/50261305/fbabda8e-4faf-4cdd-8792-8ae9aa2ac10d)

**Comment by Kenshin** [comment]
这个原因可能是：

1. 同步助手运行异常，重启同步助手并且确认同步助手被激活。

2. 数据文件损坏，可以通过 https://github.com/Kenshin/simpread/discussions/5750 修复。

不过，如果你没有稍后读的话，我建议你重新配置简悦，感觉你的简悦让你「玩坏了」… 😂

新用户的话，可以直接使用配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0

**Comment by Wilenoch** [comment]
现已解决，大概是同步助手端口被HyperV保留了，改了一下…之后直接remake用的配置库就好了
总而言之感谢回复，目前应该就只有插件中心打不开这个问题了

**Comment by Kenshin** [comment]
解决就好 👍

> 大概是同步助手端口被HyperV保留了

原来如此 😂

>  有插件中心打不开这个问题了

这不是你个人的问题 😂

问下你的网络环境，所在地（省） + 运营商是什么？

**Comment by Wilenoch** [comment]
> 问下你的网络环境，所在地（省） + 运营商是什么？

是北京电信校园网

**Comment by Kenshin** [comment]
嗨，方便的话，再试试访问 https://simpread.pro/plugins 应该可以了~

**Comment by Wilenoch** [comment]
我这边似乎还是不行，不确定是不是我自己的问题

**Comment by Kenshin** [comment]
应该是 CDN 缓存的问题造成的。

这个问题很奇怪，跟简悦无关，跟网络有关系，但我这边确实有问题，但除了你以外没有其他用户报告过这个问题。

这个问题跟  https://github.com/Kenshin/simpread/discussions/2990 是不一样的，虽然表现一样，但我已经改为国内线路了所以不存在这个情况。

过几天再看下吧，应该就自行好使了~

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
