### ISSUE TITLE
关闭阅读助手之后Assistive Touch按钮就会消失

### ISSUE THREAD

**Issue by derekxia1988** [Kenshin/simpread#6209]
### 描述这个错误

就跟标题说的一样简单明了的问题

### 复现步骤

1. 在插件里关闭阅读助手（吐槽一下阅读助手的设置界面强制弹出，且设置里没有关闭的办法，只能去插件里屏蔽插件）
2. 刷新页面，打开阅读模式，发现Assistive Touch按钮消失了
3. 启用阅读助手插件，Assistive Touch按钮回来了

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by Kenshin** [comment]
> 阅读助手的设置界面强制弹出

1. 不是强制弹出，而是每个需要配置的插件，在首次安装后会自动弹出让用户设置，以免用户找不到...

2. 阅读助手插件需要设置，否则无法使用。

> 阅读助手插件，Assistive Touch按钮回来了

我以及其他用户没有遇到过这种问题。

有可能是下面的原因产生的，但不确定，最好再详细描述下你的问题，截图或视频。

如果你使用了同步助手的自动同步功能，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装插件。

**Comment by Kenshin** [comment]
PS：老用户了，好久没有看到你提 Issues 了 😂

**Comment by derekxia1988** [comment]
确实是使用了同步助手同步的插件，我重新安装一下试试吧

**Comment by Kenshin** [comment]
> 确实是使用了同步助手同步的插件，我重新安装一下试试吧

okay 仔细留意插件管理器的使用方式就行。

***

PS：你访问插件中心 https://simpread.pro/plugins 可以正常显示 Icon 吗？如果可以的话，请告诉我你所在的省 + 运营商。

**Comment by derekxia1988** [comment]
> > 确实是使用了同步助手同步的插件，我重新安装一下试试吧
> 
> okay 仔细留意插件管理器的使用方式就行。
> 
> PS：你访问插件中心 https://simpread.pro/plugins 可以正常显示 Icon 吗？如果可以的话，请告诉我你所在的省 + 运营商。

我把阅读助手给卸载了，然后重新安装了assistive touch依然不行，我彻底找不到assistive touch的按钮了。。。另外我发现
![image](https://github.com/Kenshin/simpread/assets/28382254/66a2f583-7628-4821-989c-12c62815129f)
这里的精选插件点击assistive touch跳转到的是仿chrome webstore的论坛风格页面。

插件中心可以正常显示icon，北京，运营商不知道，公司网络，貌似所有运营商出口都有。

**Comment by derekxia1988** [comment]
新发现，我用Edge打开是这样的：
![image](https://github.com/Kenshin/simpread/assets/28382254/d2bcdcca-d1ff-4dd3-b123-7855d700622b)
在chrome上正常的

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6209#issuecomment-1870763874

应该是 Icon CDN 的问题，现在应该好使了。

> 这里的精选插件点击assistive touch跳转到的是仿chrome webstore的论坛风格页面。

是的，这是个 Bug 😂

> 我把阅读助手给卸载了，然后重新安装了assistive touch依然不行，我彻底找不到assistive touch的按钮了

理论上不可能出现这种情况，最好还是用插件管理器安装。

**Comment by derekxia1988** [comment]
![image](https://github.com/Kenshin/simpread/assets/28382254/d204ae9b-23f5-42ea-985d-6e599043528a)
插件管理器也有问题，安装了之后在动作里也不出现，我觉得我还是卸载了整个简悦试试吧

**Comment by derekxia1988** [comment]
看上去是我本地的配置全乱了，而且只要我使用坚果云登录貌似会自动同步我的配置，我清理了全部的本地配置并且不再使用坚果云登录之后我觉得现在好了。

**Comment by Kenshin** [comment]
> 看上去是我本地的配置全乱了，而且只要我使用坚果云登录貌似会自动同步我的配置

你用的同步方式？同步助手的自动同步？

PS：清理配置也包括稍后读。
