### ISSUE TITLE
关于剪藏和云存储

### ISSUE THREAD

**Issue by everlee78** [Kenshin/simpread#621]
1、剪藏不能剪藏图片，只是保存了图片链接，不方便；
2、页面以MD形式保存到坚果云，操作太繁琐，能否设定快捷键完成操作？

**Comment by Kenshin** [comment]
1. 下个版本会考虑解决这个问题；
2. 是有 [快捷键](http://ksria.com/simpread/docs/#/快捷键)

建议多看下 Github issues 置顶的几篇内容，或者翻翻文档。 😃

**Comment by everlee78** [comment]
快捷键能否设置一个开关：直接执行快捷操作，或者需要sr调出快捷操作这样可以简化操作----- 原始邮件 -----发件人：Kenshin Wang<notifications@github.com>发送时间：2019-12-07 11:16:23收件人：Kenshin/simpread<simpread@noreply.github.com>抄送：everlee78<everlee78@sohu.com>;Author<author@noreply.github.com>主 题：Re: [Kenshin/simpread] 关于剪藏和云存储 (#621)下个版本会考虑解决这个问题；是有 快捷键建议多看下 Github issues 置顶的几篇内容，或者翻翻文档。  😃—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kenshin** [comment]
阅读模式会在每个页面「工作」，因此会跟其它快捷键扩展出现未知的冲突。
所以，简悦的快捷键需要有个启动键，即你说的 <kdb>sr</kbd> 当在这个模式下，就可直接使用任意简悦支持的快捷键了。

**Comment by everlee78** [comment]
你说的都对，但是没关系啊，如果和其他快捷键冲突，用户会权衡是否改掉另外的快捷键。而有个开关，对于操作会方便很多。特别是对于像我这样的用户：我准备用你的app完全替代pocket，大量剪藏喜欢的网页放到网盘。由于需要大量剪藏操作，每个网页都SR然后剪藏，会让操作翻倍，比较累。在酷安看到一位朋友提供了一个组合替代云笔记软件，即用你的app剪藏网页配合网盘实现资料保存，然后用md编辑器实现跨平台编辑，这几天使用起来感觉特别好，比原来用各种云笔记软件舒服得多。所以，拜托简化操作吧，太重要了。----- 原始邮件 -----发件人：Kenshin Wang<notifications@github.com>发送时间：2019-12-09 10:28:57收件人：Kenshin/simpread<simpread@noreply.github.com>抄送：everlee78<everlee78@sohu.com>;Author<author@noreply.github.com>主 题：Re: [Kenshin/simpread] 关于剪藏和云存储 (#621)阅读模式会在每个页面「工作」，因此会跟其它快捷键扩展出现未知的冲突。所以，简悦的快捷键需要有个启动键，即你说的 sr 当在这个模式下，就可直接使用任意简悦支持的快捷键了。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kenshin** [comment]
抱歉，你问的问题跟另外一个人问的问题相似，所以可能在回复上弄错了...

***

1. 我想了解你说的 App 是什么？
2. 可以考虑你说的 `简化操作` 这个需求。
3. 你说的 `开关` 是指？进入阅读模式后，不经过 sr 直接操作？

**Comment by everlee78** [comment]
……app是打字手误了，是你的插件3.我觉得不进入阅读模式也可以直接剪藏操作最好啊，比如maoxian web clipper，直接按c就剪藏。当然，maoxian在剪藏上远不如你做得好，还需要手动选择剪藏区域，它比你的插件强的是可以把图片保存下来。能否这样设计：打开网页后，如果按剪藏快捷键，比如m，你的插件就直接执行剪藏阅读模式下的内容（最好是连图片也剪藏到本地）。----- 原始邮件 -----发件人：Kenshin Wang<notifications@github.com>发送时间：2019-12-11 11:38:52收件人：Kenshin/simpread<simpread@noreply.github.com>抄送：everlee78<everlee78@sohu.com>;Author<author@noreply.github.com>主 题：Re: [Kenshin/simpread] 关于剪藏和云存储 (#621)抱歉，你问的问题跟另外一个人问的问题相似，所以可能在回复上弄错了...我想了解你说的 App 是什么？可以考虑你说的 简化操作 这个需求。你说的 开关 是指？进入阅读模式后，不经过 sr 直接操作？—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kenshin** [comment]
谢谢，我会考虑你的建议。
