### ISSUE TITLE
能以 `md+assets` 的方式导出到 `GitHub` 吗？

### ISSUE THREAD

**Issue by eallion** [Kenshin/simpread#6210]
### 请描述你的建议或任何内容

我收集的文章都保存到 GitHub 备份。搜索了一下，没找到这样的方式，有些文章有图片，想以 `文章.md` 加上 `图片assets` 的形式保存到 GitHub 。

**Comment by Kenshin** [comment]
哈哈，暂时不能… 😂

你可以先保存到本地，然后使用一些自动化监控方案自动 Git 到 Github

自动化方案如： Hazel 等。

**Comment by eallion** [comment]
好的，谢谢！

**Comment by Kenshin** [comment]
小事情

https://github.com/Kenshin/simpread/discussions 里面有一些使用 Hazel 的例子，你可以参考下。
