### ISSUE TITLE
小黑盒网站适配

### ISSUE THREAD

**Issue by YU-7** [Kenshin/simpread#6217]
### 需要适配的新站

https://api.xiaoheihe.cn/v3/bbs/app/api/web/share?link_id=104629720

**Comment by Kenshin** [comment]
okay 可以考虑适配它，但请再多给我一些 URL 😂

PS：我没法从这个网站得到更多 URL 用来做适配参考。

**Comment by YU-7** [comment]
我没看仔细，多开了相同的网页，实际上是可以解析的，就是导出到obsidian有问题。
![image](https://github.com/Kenshin/simpread/assets/58320198/8a36ccda-6812-43f9-8066-7a93f8e4113d)
只有assent文件夹

**Comment by Kenshin** [comment]
没有 assets 的话，可能是它的图片有比较严苛的措施，具体我有时间时再测试下。

PS：这几天在休假～

**Comment by Kenshin** [comment]
其实是没问题的。

<img width="1098" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1886a480-a669-4443-bc31-06659a9766ad">

但这个页面是动态加载的且未适配，所以需要做下面的事情。

1. 需要将 `xiaoheihe.cn` 加入到延迟加载列表

    <img width="1212" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8b1fc960-6058-4500-87ce-87099b00e505">

2. 进入页面拉动滚动条让图片全部加载完毕。

3. 使用 Live Editor 添加标题

    <img width="1242" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0faf61da-9b96-4636-840f-b6133943eeb3">

***

PS：我先重开这个 Issues ，因为看下是否可以适配它。

**Comment by Kenshin** [comment]
> 是只有assent文件夹，我看了一下导出到obsidian是没有标题，所以会出现这个问题。

okay 那就按照我说的方式导入~
