### ISSUE TITLE
插件管理从配置文件导入插件提示5591获取失败

### ISSUE THREAD

**Issue by HopeLHP** [Kenshin/simpread#6219]
### 描述这个错误

插件管理从配置文件导入插件提示5591获取失败，但所有插件都导入进来了，但是以前设置过的插件配置全没了，需重新设置插件配置或模板
![image](https://github.com/Kenshin/simpread/assets/70339118/5419a54d-4ab6-4a46-b881-e90fa41afae9)

### 复现步骤

1、共通-从本地导入配置文件
2、插件管理-从配置文件导入插件
3、提示5591获取失败，请稍后重试
4、全部插件导入
5、打开文章进入阅读模式，全部插件弹出，里面内容为空，要填写配置

### 操作系统

win11

### 浏览器

egde

### 发生问题的网址

https://www.shui5.cn/article/b6/83326.html

**Comment by Kenshin** [comment]
你用没用同步助手的自动同步功能？

**Comment by HopeLHP** [comment]
是指这个吗，应该是用了的。
![image](https://github.com/Kenshin/simpread/assets/70339118/d620fe0c-ce2f-4398-aa60-1b477cb14c60)

**Comment by HopeLHP** [comment]
另外我共用一个配置文件的mac端都是正常的

**Comment by Kenshin** [comment]
> 另外我共用一个配置文件的mac端都是正常的

出错的配置文件和 Mac 正常的那个是同一份吗？如果是的话，在 Mac 上可以使用下图的方式

<img width="494" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b6038eb7-7a19-4446-8ae5-42b4cad58244">

将插件配置保存到本地，应该是叫做 `simpread_config.json` 这个文件，然后在新设备上导入这个配置文件。

**Comment by HopeLHP** [comment]
还是不行，估计配置文件里的插件信息是全的，但是在从配置文件中导入时出现了问题，导致提示5591

**Comment by Kenshin** [comment]
emmmm 

> 还是不行，估计配置文件里的插件信息是全的，但是在从配置文件中导入时出现了问题，导致提示5591

5591 的错误有问题，理论上不应该有这个错误提示。

***

把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6219 然后在这里告诉我。

但我这几天在休假，不知道什么时候方便确认，但确认后会在这里通知你。

**Comment by HopeLHP** [comment]
好的，已发送，麻烦了

**Comment by Kenshin** [comment]
嗨，我看了你给我的配置文件

> 5591 的错误

你的插件里面混入了一个 ID 叫做 5591 的插件（这是个不存在的插件 😂

<img width="401" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1ee92050-2f35-46ee-a115-7ec2eb811bef">

我已经把这个 `ID` 删除了，除此之外没有改动任何内容，把这个配置文件覆盖你原来 `simpread_config.json`

> 配置文件没有插件信息的问题

你给我的**配置文件里面没有包含任何插件配置**，所以你是否使用了 https://github.com/Kenshin/simpread/issues/6219#issuecomment-1872478515 提到的方式？只要使用这个功能，你的 `simpread_config.json` 会被更新，所以看下日期是否已经更新？

**Comment by HopeLHP** [comment]
突然感觉大事不好，感觉有插件配置信息的版本被覆盖回去，mac这边也啥都没有了，我去坚果云历史里找回了一版，您看看这个版本还有配置信息吗，如果有的话，能帮忙再清理一下那个配置文件吗，我邮件发你了

**Comment by Kenshin** [comment]
好，只能抽时间看下。

如果 size 有变化的话，应该没问题。

或者你有能找到 https://github.com/Kenshin/simpread/issues/6219#issuecomment-1872478515 操作后的版本也行。

**Comment by HopeLHP** [comment]
我用这版按照你说的删除了`"5591",`重新导入插件，看了一下配置都在，这个问题解决了，感谢啦
![image](https://github.com/Kenshin/simpread/assets/70339118/5277e6f8-26d1-4de2-8153-1b53f2345e91)

**Comment by Kenshin** [comment]
搞定就好。👍

用的是哪个配置文件？你给我的配置文件里面没有插件配置信息。

**Comment by HopeLHP** [comment]
我昨晚给你发了一个最新的版本，那个应该有吧？或者我发你的时候又选错了哈哈哈哈哈，反正现在导入不报错配置全都在。

**Comment by Kenshin** [comment]
> 我昨晚给你发了一个最新的版本，那个应该有吧？或者我发你的时候又选错了哈哈哈哈哈，反正现在导入不报错配置全都在。

是的，这个配置文件里面有插件配置信息。所以，你昨天给我发的配置文件是不对的。😂

而你 https://github.com/Kenshin/simpread/issues/6219#issuecomment-1872557778 的操作是正确的，所以问题解决了~

***

PS：基本上你算是今年最后一批 Issues 了 😂

如果没有帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评的话，请帮忙 😉 😁 👍

PPS：一般经常提 Issues 的老用户大多都评过分了 😄

**Comment by HopeLHP** [comment]
> PS：基本上你算是今年最后一批 Issues 了 😂
> 
> 如果没有帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评的话，请帮忙 😉 😁 👍
> 
> PPS：一般经常提 Issues 的老用户大多都评过分了 😄

哈哈哈哈，我GitHub应该是之前点过star的，edge的扩展网站之前没有想到，刚才好评了，希望简悦越来越好！！！

**Comment by Kenshin** [comment]
👍👍👍

只要 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 评分就行了  😏 

PS：元旦还不休息？还玩电脑？😂

**Comment by HopeLHP** [comment]
元旦正是加班的好时候哈哈哈

**Comment by Kenshin** [comment]
好惨 😂 难道是为了春节攒假期数？

PS：应该有至少三倍的加班费？

**Comment by HopeLHP** [comment]
审计狗，春节能放假我就谢天谢地了

**Comment by Kenshin** [comment]
> 审计

厉害啊 👍 不过你们确实一到这时候就忙 😂 好奇问问，是什么方面的审计？

**Comment by HopeLHP** [comment]
财务，主要税务，有税务方面的问题欢迎交流

**Comment by Kenshin** [comment]
👍

这个就更「高端」了。

好，我先 Mark 下，目前没有啥税务问题，但未来有可能需要个律师咨询点事情 😂

**Comment by Kenshin** [comment]
嗨，新版简悦已经彻底解决了这个问题。

***

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统 2.0

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

关于插件系统 2.0 内置插件的更多介绍 https://github.com/Kenshin/simpread/issues/7329

# 🟩 带来的好处

- 当你安装插件，进入阅读模式后没有在「插件触发器」找到对应插件的问题。
- 更换为新设备时，插件配置无故「消失」的问题。
- 插件保存后但并没有生效的问题。
- 无法安装插件的问题。
- 导入配置文件后，但没有看到插件的问题。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

- 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能
- 选项页 → 插件管理，支持插件的选项卡的设置
- 一键导入 → 所导及所见
- 安装插件后插件触发器错误的问题也自动消失（解决）了
- 阅读模式动作栏图标更清晰、更锐利（替代模糊的旧图标）
- 对话框（稍后读 / 标注 / 插件选项页）的动效更快速、UI 更现代
- 标注浮动工具栏出现更快、更轻
- 统一了扩展端与插件端下拉菜单的 UE，使其点击更顺手（点文字或箭头都能开）
- 当配置文件超过 10mb 后加入稍后读略慢时会显示「正在加入…」的提示
- 动作栏「加入稍后读」以及鼠标划取生成第一条标注时的行为与快捷键加入稍后读一致
- 修复当第一次加入稍后读时，本地快照没有 idx 的问题。
- 升级用户减少重复的新手引导（阅读模式、稍后读、高级账户导出等），包括：点过「不再提示」后，同步配置时也更不容易反复弹
- 插件管理「精选 / 常用 / 剪藏」合集扩充，常见剪藏与代码阅读相关插件更好找

# 详细说明

https://github.com/Kenshin/simpread/issues/7326
