### ISSUE TITLE
希望可以设置不启用快捷键

### ISSUE THREAD

**Issue by LiziMu2333** [Kenshin/simpread#622]

**Comment by Kenshin** [comment]
请问，是指排除列表？还是黑名单？
为什么要这个快捷键？

**Comment by LiziMu2333** [comment]
> 请问，是指排除列表？还是黑名单？
> 为什么要这个快捷键？

我指的是开启阅读模式和聚焦模式的快捷键，可以设置为禁用

**Comment by Kenshin** [comment]
因为跟其它键有冲突吗？

**Comment by LiziMu2333** [comment]
> 因为跟其它键有冲突吗？

@Kenshin 
是因为在大部分情况不需要使用阅读模式的时候，快捷键的存在并没有必要

**Comment by Kenshin** [comment]
这样会增加用户的记忆成本。
