### ISSUE TITLE
阅读模式下微信公众号的所有文章不可以使用标注

### ISSUE THREAD

**Issue by tonycxc** [Kenshin/simpread#6220]
### 描述这个错误

阅读模式下，微信公众号的所有文章不可以使用标注，选中文段后无法高亮，不出菜单；其他别的网站均可正常标注高亮，仅微信公众号文章
<img width="767" alt="截屏2023-12-30 下午10 09 58" src="https://github.com/Kenshin/simpread/assets/44918053/6d9befe2-99d6-4ec8-a8d5-0021287f239a">
<img width="831" alt="截屏2023-12-30 下午10 10 04" src="https://github.com/Kenshin/simpread/assets/44918053/e1d06dcd-d67c-4fe0-9b51-fa4c35238154">
失效。

### 复现步骤

选中文段
不出现高亮选项

### 操作系统

MacOS

### 浏览器

Chrome

### 发生问题的网址

https://mp.weixin.qq.com/

**Comment by Kenshin** [comment]
当然不可能存在这种情况… 😂

1. 隐私模式下仅启用简悦的方式，排除其他扩展的干扰

2. 禁用简悦的插件看下能否解决？用来排除简悦插件的问题（简悦没有这种插件，但以防万一）

**Comment by tonycxc** [comment]
在尝试1,2后问题依旧，并且之前微信公众号文章做过的标注，在重新刷新页面后全部消失。

**Comment by tonycxc** [comment]
同上文描述，其他网站文章的标注以及访问均不受影响。

**Comment by tonycxc** [comment]
这种情况近期才出现，以前从未有过，没有对浏览器做出其他操作。

**Comment by Kenshin** [comment]
你是不是安装了简悦的一个关于公众号的插件？

**Comment by tonycxc** [comment]
没有的
![Uploading 截屏2023-12-31 上午11.04.03.png…]()

**Comment by Kenshin** [comment]
你的截图没有显示。

还是给出的信息太少，我没法判断。

可以把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6220

**Comment by tonycxc** [comment]
[Uploading simpread-config-2023年12月31日 15_58_05.json…]()

**Comment by Kenshin** [comment]
😂

1. 你没发上来...

2. 不要在这里发，因为配置文件里面包含你的账户信息...

**Comment by Kenshin** [comment]
我看到你的邮件了。

***

我使用了你提供的配置文件，并没有遇到问题，截图

<img width="1614" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f5003bcf-9917-4456-a725-e0e5459f026f">

测试网页 https://mp.weixin.qq.com/s/OnqUXcxUyr97YbZJFV1CSA

不过，有几个地方确实需要优化：

> 请关闭简/繁体转换插件

<img width="284" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/99c48c92-ed1c-407b-9c96-0f34555d1b05">

> 请关闭无图版

无图版会对已经标注的页面产生影响，已经标注的页面不显示标注可能是这个问题造成的

<img width="279" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/765d3ea1-7217-43ba-ad3a-67a63ec463c4">

> 分栏阅读插件

同上，这个插件也会对标注产生影响，也建议关闭。

<img width="272" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4d8dfd1e-b34b-4c6d-9083-a54d3f0ed18c">

**无图版** 与 **分栏阅读** 是仅针对阅读模式的插件，不建议在标注模式下使用。

> 你给我的配置文件里面似乎高级账户权限没有开

如果你的选项页界面是下图，请按照下图的箭头选择重新授权当前账户为高级账户。

<img width="319" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a1191850-fee9-4375-90bf-b94a5e73fa26">

**Comment by Kenshin** [comment]
存了 1.8K 的稍后读 👍 感觉像是老用户 😄

留意下面的几个提示：

1. 请及时备份你的配置文件以免遗失，这是 [手动方案](https://www.yuque.com/kenshin/simpread/yvowrx#113ba404)

2. 也可以使用同步助手的自动同步功能，并辅助本地系统，将你的稍后读变为基于本地数据的方案（彻底避免了 404 问题），[这是教程](https://www.yuque.com/kenshin/simpread/wkswh7)
