### ISSUE TITLE
阅读模式下生成的目录不能下翻

### ISSUE THREAD

**Issue by Mindwells** [Kenshin/simpread#6221]
### 描述这个错误

阅读模式下生成的目录不能下翻

### 复现步骤

1.阅读模式
2.生成的目录不能下翻

### 操作系统

window11

### 浏览器

edge

### 发生问题的网址

知乎

**Comment by Kenshin** [comment]
嗨，2024年第一个 Issues 😄

知乎是简悦用户经常使用的网页，一般不会出现这种问题，所以请提供下出问题的 URL 。

**Comment by Mindwells** [comment]
https://zhuanlan.zhihu.com/p/538881498

**Comment by Kenshin** [comment]
将下面的代码

```
.simpread-font toc {
    overflow-y: auto!important;
    overflow-x: hidden!important;
}
```

加入到下图所示的位置然后重启浏览器，确保生效。

![image](https://github.com/Kenshin/simpread/assets/81074/ac953470-17c4-4cb1-893e-17f10778b1e7)

**Comment by Mindwells** [comment]
已解决，太酷了

**Comment by Kenshin** [comment]
小事情，只要提在 Issues 上的问题我都会处理的 😄

解决了 2024 年的一个 Issues 能感到用户的心情我也很高兴 👍

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

PPS：有可能是 2024年的一个五星 + 好评 😂
