### ISSUE TITLE
简悦打开后代码块有缺失

### ISSUE THREAD

**Issue by Arukas0808** [Kenshin/simpread#6222]
### 描述这个错误

简悦打开后腾讯云开发者社区文章，代码块有缺失

### 复现步骤

开启简悦前：
![tmpBEB2](https://github.com/Kenshin/simpread/assets/63109249/28867b6e-d739-40ea-bc41-7b94a67ae8fb)

开启简悦后：
![tmpFEAA](https://github.com/Kenshin/simpread/assets/63109249/dd655db5-0c4f-4845-9970-644d4a4ff07d)

### 操作系统

Windows 10 22H2 19045.3570

### 浏览器

chrome 120.0.6099.130 

### 发生问题的网址

https://cloud.tencent.com/developer/article/1953013

**Comment by Kenshin** [comment]
嗨，谢谢反馈，代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
