### ISSUE TITLE
无论利用Local REST还是Simple Read SYC插件导入标注到Obsidian均显示为空，导入全文则没问题。

### ISSUE THREAD

**Issue by zhang360896** [Kenshin/simpread#6224]
### 描述这个错误

如题，导入标注到Obsidian结果为空

### 复现步骤

进入阅读模式，点击右侧的“...”，选择“动作”，选择“导入到Obsidian”，提示“导入成功”，但进入Obsidian看到对应位置标注为空。导入全文则没有问题。
![image](https://github.com/Kenshin/simpread/assets/7602821/30a1d3e8-5d03-4b18-aa1e-954348bd8770)

![image](https://github.com/Kenshin/simpread/assets/7602821/c15f2078-19ac-4e14-bdc7-2ae535591c91)

### 操作系统

win10

### 浏览器

Chrome

### 发生问题的网址

https://zhuanlan.zhihu.com/p/432281397

**Comment by zhang360896** [comment]
已参考#5809修改为localhost，依然无法导出

**Comment by Kenshin** [comment]
> 已参考 #5809 修改为localhost，依然无法导出

跟这个无关。

你看下 Markdown 辅助增强插件里面有没有标注的模板？

细节的话，可以参考这个教程 https://www.yuque.com/kenshin/simpread/fr8zo5

**Comment by Kenshin** [comment]
另外，新用户的话，建议直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef

**Comment by zhang360896** [comment]
> 另外，新用户的话，建议直接使用配置库方案 https://www.yuque.com/kenshin/simpread/psugef

直接上传用了原生的配置库，还是全文可以导出，但是标注无法导出。现在点击“导出标注到obsidian”连提示都没了。
![image](https://github.com/Kenshin/simpread/assets/7602821/3e3aec9f-e053-40e0-937e-92d7a024353f)

![image](https://github.com/Kenshin/simpread/assets/7602821/3e3aec9f-e053-40e0-937e-92d7a024353f)

**Comment by Kenshin** [comment]
使用了哪种配置库方案？把跟教程一样的相关截图都截图给我看下。

主要用来判定你的配置与官方的异同。

**Comment by zhang360896** [comment]
> 使用了哪种配置库方案？把跟教程一样的相关截图都截图给我看下。
> 
> 主要用来判定你的配置与官方的异同。
按照教程导入的是little版本的。
![image](https://github.com/Kenshin/simpread/assets/7602821/5969d553-65a6-43f5-8550-e491c419be0a)
![image](https://github.com/Kenshin/simpread/assets/7602821/af28fb28-27a8-44a5-aab8-7361816053e2)

**Comment by zhang360896** [comment]
> 使用了哪种配置库方案？把跟教程一样的相关截图都截图给我看下。
> 
> 主要用来判定你的配置与官方的异同。

原生配置的操作都是按照教程走的，其实我个人配置的参数和插件也都是按照相关教程走的。结果都一样，可以导入全文，但是导入不了标注。是否和高级会员权限相关？昨天已在腾讯问券付费，如果可以麻烦优先处理一下license授权我试试别的配置文件

**Comment by zhang360896** [comment]
> 使用了哪种配置库方案？把跟教程一样的相关截图都截图给我看下。
> 
> 主要用来判定你的配置与官方的异同。

描述一下我的操作吧， 1、下载截图里的压缩包，解压，2、将simpread_config.json上传，3、更改UUID，4、运行Obsidian，并打开压缩包里的库，5、进入目标网页进行标注，然后点击导入标注到Obsidian，结果没有任何提示。不过点击导入全文显示成功，且可以在Obsidian里看到。

**Comment by Kenshin** [comment]
嗨，请不要重复建立相同的 Issues 我关闭 #6227 了，一并在这里讨论。

***

你的问题估计是跟高级账户权限有关系，腾讯问卷付款方法会在 19 点前进行兑换操作。

等收到可以兑换的邮件后，请根据 https://www.yuque.com/kenshin/simpread/xkuecp#htXtm 进行更换你自己的 UID 然后升级高级账户后再测试。

**Comment by Kenshin** [comment]
兑换邮件已发~

**Comment by zhang360896** [comment]
> 兑换邮件已发~
已用高级权限，效果一样，无法导出批注。
![image](https://github.com/Kenshin/simpread/assets/7602821/eaf7823f-bc49-4378-a770-bf967f65dedf)

**Comment by Kenshin** [comment]
嗨，我在休假，回复的会比较慢。

可以把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6224

**Comment by zhang360896** [comment]
> Issues ID：6224

已发送，请查阅

**Comment by Kenshin** [comment]
okay 等我能确认的时候会回复你。

**Comment by zhang360896** [comment]
> okay 等我能确认的时候会回复你。

请问何时能复现解决一下，与批注导出相关的功能都有异常，导出到hypothesis也不行。

**Comment by zhang360896** [comment]
> okay 等我能确认的时候会回复你。

现在基本简悦用不起来，我主要就是用批注功能，现在这情况实在是没法用，还望帮忙看一下。

**Comment by Kenshin** [comment]
我休假完毕。

***

你有两个问题：

其一是下图没有开启...

<img width="612" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d2491df4-f97a-48a7-8ef4-d21a2ce616d1">

其二是没有安装自动化辅助增强，所以标注时无法自动导入到 Obsidian，只能通过手动导入。

#### 建议

请直接使用 https://www.yuque.com/kenshin/simpread/wq35mh 提到的配置库方案。
