### ISSUE TITLE
无法导出md+assets

### ISSUE THREAD

**Issue by HasonHuang** [Kenshin/simpread#6228]
### 描述这个错误

错误描述：
1. 同步助手的配置突然消失了。
2. 为同步助手添加配置后，加入稍后读时，导出内容全只有 md 文件、HTML 文件，**缺少 md+assets 文件**。

> 初步观察，一切正常，唯独缺少 assets Obsidian 也存在

同步助手的增强导出：
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/e612c11d-5236-408a-8044-44c1e4bec066">

导出时浏览器的页面与控制台：
<img width="919" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/285ae4ca-2b35-4a34-b71c-fe6381ce9ba6">

导出的本地文件：
<img width="488" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/b6563065-ca7e-41e9-9f56-0ce67d115e35">

### 复现步骤

1. 激活并设置同步助手的配置
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/aef5c9ea-1b9f-42cd-9604-db22a1237d45">
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/e612c11d-5236-408a-8044-44c1e4bec066">
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/60a46f1f-3075-4da4-a8b0-c4637b1888a3">

2. 检查插件（配置文件没有丢失、修改）
<img width="516" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/770e45f5-784c-4298-b33e-acc1a5dd7253">

导出 Obsidian 的配置：
<img width="627" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/1748633c-1a64-4de1-9349-80fcc85a96e9">

3. 挑选一个网站，加入稍后读
[要加入稍后读的博客网站](https://mincong.io/2020/05/30/exception-handling-in-completable-future/)

加入稍后读：
<img width="919" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/285ae4ca-2b35-4a34-b71c-fe6381ce9ba6">

4. 查看导出文件：
<img width="488" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/b6563065-ca7e-41e9-9f56-0ce67d115e35">

### 其他相关说明

1. Mac 与 Windows 2 个设备正常使用【Obsidian 一站式方案】已经一年左右。
2. 这两天发现**同步助手的配置不见**了，浏览器**插件的配置文件正常**。
3. 前几天升级 MacOS 从 13.X 升级到 `14.2.1`，不清楚是否有影响。
4. 同步助手-增强导出的配置内容来自 Windows 设备。

### 操作系统

macOS 14.2.1

### 浏览器

Chrome 120.0.6099.129

### 发生问题的网址

https://mincong.io/2020/05/30/exception-handling-in-completable-future/

**Comment by Kenshin** [comment]
嗨，这几天在休假，明天确认下。

**Comment by Kenshin** [comment]
> 同步助手的配置不见了

同步助手的配置放在 Electron 的一个特殊文件夹中，不是简悦可以「干涉」的，所以这个问题不太好判断和调查 😂

> 前几天升级 MacOS 从 13.X 升级到 14.2.1，不清楚是否有影响。

可能有关系。

***

至于 assets 的问题，试试手动导出能否成功？之前是否一直成功？还是第一次配置它？

**Comment by HasonHuang** [comment]
> 至于 assets 的问题，试试手动导出能否成功？之前是否一直成功？还是第一次配置它？

1. 手动导出不成功。点击【导入 md + assets到 Obsidian】按钮后，仍然没有导出 assets，只有 .md 文件。
<img width="500" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/c85cadad-b5bb-4667-bf52-764dd6d8e88f">
<img width="700" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/0b5fa94f-e668-45e6-b17b-32d76eb457a7">

> 

2. 之前一直成功，直到同步助手的配置消失。

3. md+assets 自动导出功能已经使用一年了。例如：
<img width="730" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/4c8df317-828d-4bc5-8614-2fdae37476b6">

**Comment by HasonHuang** [comment]
@Kenshin 嗨，有空看一下，谢谢

**Comment by HasonHuang** [comment]
Windows 导出功能也是同样问题，无法导出 md+assets。可能是浏览器插件问题？我可以如何排查处理？

**Comment by Kenshin** [comment]
把配置文件发送到 help#####simpread.pro 邮箱里面（注意 # → @）并注明这个 Issues ID：6228 然后在这里告诉我。

但我这几天在休假，不知道什么时候方便确认，但确认后会在这里通知你。

**Comment by HasonHuang** [comment]
> 把配置文件发送到 help#####simpread.pro 邮箱里面（注意 # → @）并注明这个 Issues ID：6228 然后在这里告诉我。

已发送到 help#simpread.pro (#改为了@，只有1个@)

**Comment by Kenshin** [comment]
好，我有时间会回复你的。

最近在休假 😂

**Comment by Kenshin** [comment]
嗨，我休假完毕了。

***

我看了下你提供的配置文件，里面关于插件的配置大部分都不存在的。

<img width="346" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0c0abff4-3046-4342-b1ef-f349c6158056">

***

我根据你提到的一些信息，在你给我的配置文件基础上测试了下，是没问题的。

<img width="679" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9050648b-ba39-4764-8749-e30f4674f42e">

<img width="586" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dae0ceb7-2f4c-4051-9e34-a2fd30140e49">

**Comment by HasonHuang** [comment]
> 我看了下你提供的配置文件，里面关于插件的配置大部分都不存在的。
我从 Git history 里拷贝回配置文件里，保存，重试导出仍然无法保存 assets，请问需要配置哪些插件？

**Comment by HasonHuang** [comment]
我将插件全部卸载，然后只安装【插件管理器】，页面没有显示出来。

<img width="410" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/00a513b2-eea6-412f-848e-ff7a5e1af068">

没有显示出【插件管理器】：
<img width="521" alt="image" src="https://github.com/Kenshin/simpread/assets/11768760/813b9793-15f4-4dca-b49b-fe462cb49bad">

**Comment by HasonHuang** [comment]
请问我可以如何在保留历史笔记的情况下，重新初始化或配置简悦？

**Comment by Kenshin** [comment]
看下 https://github.com/Kenshin/simpread/discussions/5751 应该可以解决你的问题。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6228#issuecomment-1904331209

把你的 Obsidian 选项截图给我看下。

**Comment by Kenshin** [comment]
https://www.yuque.com/kenshin/simpread/chyo5a 这是 md + assets 配置库方案，你可以考虑试试。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

有任何需求可以随时在这里讨论~
