### ISSUE TITLE
维基百科页面排版问题

### ISSUE THREAD

**Issue by creamJelly** [Kenshin/simpread#6229]
### 描述这个错误

维基中文页面，阅读模式下，标题下、正文上的部分排版奇怪

### 复现步骤

页面地址：  
https://zh.wikipedia.org/wiki/%E7%BA%A2%E9%BB%91%E6%A0%91

阅读模式下，目前展示效果：
![image](https://github.com/Kenshin/simpread/assets/10293381/4d1753f0-b4e6-43f8-907c-8e3887f92d69)

预期展示效果：
红框中内容不展示，或展示时不换行

目前启用的插件列表：
![image](https://github.com/Kenshin/simpread/assets/10293381/f38a14e4-5ccb-42e2-86d5-a6b38657049e)
![image](https://github.com/Kenshin/simpread/assets/10293381/0a8184f0-85e2-40bb-95eb-1d078b1c1715)

### 操作系统

macOS

### 浏览器

chrome 版本 120.0.6099.129

### 发生问题的网址

https://zh.wikipedia.org/wiki/%E7%BA%A2%E9%BB%91%E6%A0%91

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/5832 这个方案。

**Comment by creamJelly** [comment]
> 嗨，试试 #5832 这个方案。

您好，我已经安装了

**Comment by creamJelly** [comment]
> 嗨，试试 #5832 这个方案。

您好，我已经安装了按照文章中的要求安装了维基百科辅助增强和Modern for Wikipedia 这两个插件。目前阅读模式下显示如图，辛苦帮忙看一下
![image](https://github.com/Kenshin/simpread/assets/10293381/5a8d693e-daa9-4e98-b1dc-1027e705bbfc)

**Comment by creamJelly** [comment]
https://www.cnblogs.com/qdhxhz/p/11448451.html

**Comment by creamJelly** [comment]
https://www.cnblogs.com/qdhxhz/p/11448451.html  这个地址如图所示的图片，导出pdf的时候无法导出成功，尝试多次都是裂的
现状：![image](https://github.com/Kenshin/simpread/assets/10293381/97f54246-c295-4e25-8df8-3aaa06754c2b)
预期：![image](https://github.com/Kenshin/simpread/assets/10293381/eac3234c-4a4e-4278-b194-4fa7bfdd3d06)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6229#issuecomment-1878281657

有什么问题吗？这个是图片，所以在简悦中有边框和阴影。

> https://github.com/Kenshin/simpread/issues/6229#issuecomment-1878290464

我在休假，这个问题暂时没法确认，其它网站有类似的情况吗？如果是个例的话，可以忽略不计。

也可以试试 https://github.com/Kenshin/simpread/discussions/3887 提到的解决方案。
