### ISSUE TITLE
阅读助手无法调用腾讯云搭建的oneapi

### ISSUE THREAD

**Issue by sdivens** [Kenshin/simpread#6231]
### 描述这个错误

在腾讯云上搭建了一个oneapi,获取oneapi的令牌填写到token和配置主域名后,使用ai提示服务器错误
![image](https://github.com/Kenshin/simpread/assets/16970292/19e59093-2bd9-4a26-802b-d36ea401c372)
token已脱敏处理
不知道是不是简悦的后台服务器在国外,请求国内域名请求不到
因为我使用同样的token和base_url在自己服务器上搭建的ChatGPT-NextChat是可以使用的,但是使用vercel部署的ChatGPT-NextChat则请求失败
然后我查看自己在腾讯云上搭建的oneapi的日志,当我用本地搭建的ChatGPT-NextChat请求时有日志记录,但是使用简悦AI阅读助手请求的时候没有日志记录
以上
谢谢

### 复现步骤

步骤建描述

### 操作系统

Windows10

### 浏览器

edge

### 发生问题的网址

https://zhuanlan.zhihu.com/p/641298242

**Comment by Kenshin** [comment]
如果 API 结构一样的话，理论上应该没问题。

我在休假，所以这个问题需要等到有时间时并且还需要你的配合才能确认，我先记录下。

**Comment by sdivens** [comment]
今天使用同样的请求分别请求了一下GPT和我的one-api平台,请求参数:
```json
{
    "model":"gpt-3.5-turbo",
    "stream":true,
    "messages":[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "讲一个笑话,要求最少50个字"}
  ]
}
```

我对比了一下正常的返回和的one-api的返回,发现了他们的差别:
正常的返回:
---
```plain
data: {"id":"chatcmpl-8eBkxCpfgzYpoVqVA0PxLpS3fk205","object":"chat.completion.chunk","created":1704589003,"model":"gpt-3.5-turbo-0613","system_fingerprint":"fp_cbe4fa03fe","choices":[{"index":0,"delta":{"content":"您"},"logprobs":null,"finish_reason":null}]}
data: {"id":"chatcmpl-8eBkxCpfgzYpoVqVA0PxLpS3fk205","object":"chat.completion.chunk","created":1704589003,"model":"gpt-3.5-turbo-0613","system_fingerprint":"fp_cbe4fa03fe","choices":[{"index":0,"delta":{"content":"喜"},"logprobs":null,"finish_reason":null}]}
data: {"id":"chatcmpl-8eBkxCpfgzYpoVqVA0PxLpS3fk205","object":"chat.completion.chunk","created":1704589003,"model":"gpt-3.5-turbo-0613","system_fingerprint":"fp_cbe4fa03fe","choices":[{"index":0,"delta":{"content":"欢"},"logprobs":null,"finish_reason":null}]}
data: {"id":"chatcmpl-8eBkxCpfgzYpoVqVA0PxLpS3fk205","object":"chat.completion.chunk","created":1704589003,"model":"gpt-3.5-turbo-0613","system_fingerprint":"fp_cbe4fa03fe","choices":[{"index":0,"delta":{"content":"！"},"logprobs":null,"finish_reason":null}]}
data: {"id":"chatcmpl-8eBkxCpfgzYpoVqVA0PxLpS3fk205","object":"chat.completion.chunk","created":1704589003,"model":"gpt-3.5-turbo-0613","system_fingerprint":"fp_cbe4fa03fe","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}
data: [DONE]
```

我的one-api的返回
---
```plain
data: {"id":"as-9ypatd7x3c","object":"chat.completion.chunk","created":1704589066,"model":"ernie-bot","choices":[{"delta":{"content":"好的，"}}]}
data: {"id":"as-9ypatd7x3c","object":"chat.completion.chunk","created":1704589066,"model":"ernie-bot","choices":[{"delta":{"content":"这是一个简单的笑话：为什么电脑永远不会感冒？"}}]}
data: {"id":"as-9ypatd7x3c","object":"chat.completion.chunk","created":1704589066,"model":"ernie-bot","choices":[{"delta":{"content":"因为它有“脑热”。"},"finish_reason":"stop"}]}
data: [DONE]
```
以下是他们两的返回数据的对比:

1. 我的model是`ernie-bot`,这个是百度的模型,gpt返回的是`gpt-3.5-turbo-0613`,
2. 我的返回中没有`system_fingerprint`这个key
3. 我返回的`choices`中没有`index`, `delta`中没有`logprobs`,除了最后一条返回,没有`"finish_reason":"stop"`

所以我猜测是否是简悦在后台获取接口返回数据的时候,有通过上述不一样的地方的额外筛选判断,而不是直接取返回`choices[0]`

**Comment by Kenshin** [comment]
谢谢详细测试，有可能。 😂

等我有时间时再确认。

**Comment by Kenshin** [comment]
嗨，我休假完毕了。

***

这个问题我需要你的 Token 才能测试，方便的话，可以仅简悦的 [Telegram 群](https://t.me/simpreadgroup)，然后私聊我。

**Comment by sdivens** [comment]
> 嗨，我休假完毕了。
> 
> 这个问题我需要你的 Token 才能测试，方便的话，可以仅简悦的 [Telegram 群](https://t.me/simpreadgroup)，然后私聊我。

好的,谢谢
测试信息已发,请查收

**Comment by Kenshin** [comment]
嗨，我测试了你提供 API 返回确实是正确的，但确实也可能是因为 https://github.com/Kenshin/simpread/issues/6231#issuecomment-1879902854 不同造成的问题。

但细节上还是有些区别，我这边直接看到返回了 `[DONE]` 中间并没有任何内容。

PS：还是建议使用更常规且符合 OpenAI 标准格式的第三方 API 😂
