### ISSUE TITLE
登录问题反馈

### ISSUE THREAD

**Issue by TingFeng121** [Kenshin/simpread#6232]
### 请描述你的建议或任何内容

第一点：支持授权任意webdav很好，但是我在填这个的时候，是不是直接让我输对应字段后面的就好了呢？我还要再截图才能记得我在哪个位置要填哪个字段

第二点：可以绑定坚果云，但是点击绑定的时候并不弹出输邮箱和密码的地方

想去登录页面看下能不能授权坚果云，点右上角发现没有这个选项

根据提示想“使用第三方作为登录”
套娃开始了，点击“授权你的坚果云”，提示没有授权

那我如何授权呢？
原来我还需要解除绑定当前设备
当我以为我终于可以登上的时候，我蚌埠住了，这按钮点了就是没反应的

于是我再次回到 服务-授权管理，去把坚果云的信息填到“webDAV”的选项里面
我又蚌埠住了。我特么刚从坚果云拿的密码怎么会错

最终。。。我还是没登上，服气，从十点半折腾到12点

具体内容你看我的在线文档吧这个上传的图片貌似不展示
https://docs.qq.com/doc/DSlRNZ3BYd0tzU3Ra?&u=09fccd82fcd544ceaf1cb09eaed00a1f

**Comment by Kenshin** [comment]
嗨

1. Github 可以上传图片…
2. 「登陆」功能是给高级用户准备的，主要是使用 API 的用户，简悦是基于本地的稍后读，并没有你理解的登陆和注册，类似 Obsidian 的概念。

所以，登陆功能对新用户来说，有点「麻烦」。不过，如果你使用 API 或新用户的话，不需要使用这个功能。

**Comment by TingFeng121** [comment]
但是目前这个坚果云同步就是有问题的，我登录不上且无法同步我的配置信息
![AgAABs_nN4k96Sft3lRNpI7LkiQpJJOD](https://github.com/Kenshin/simpread/assets/90266249/872671d7-d903-4a7f-a5a3-1d3d86ff402d)

**Comment by Kenshin** [comment]
截图中需要输入坚果云的 Email 与坚果云的授权码。

**Comment by TingFeng121** [comment]
是我眼瞎了hhhh，搞定了
我一直以为是点按“绑定 坚果云 的信息，然后弹窗输入的账号和授权码，都没注意上面那行，提示文字太多稍微有点不显眼了~

**Comment by Kenshin** [comment]
> 提示文字太多稍微有点不显眼了~

解决就好，可以考虑优化下。
