### ISSUE TITLE
阅读助手 openai.simp.red SSL 过期

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6233]
第一次体验这个功能,  报错信息里没有错误码.
买了GPT4, 已经正确配置了token, 自定义API是必须的不?  没看明白怎么弄
3.5 / 4 /  4 turbo都试了, 都报错   (这个功能目前大家都能正常使用嘛...?)
<img width="505" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/5de09ee2-2619-4eae-9edb-f9105d1c67b1">

_Originally posted by @QunWei-L in https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-8033068_

**Comment by Kenshin** [comment]
@QunWei-L

我新建了一个 Issues 讨论这个问题。

***

请截图说明比较好，另外，这个功能应该没有任何问题，用户量还不错。

**Comment by QunWei-L** [comment]
尝试了重启浏览器, 重启电脑之类的,  目前还是无法正常使用这个功能
有买GPT4, 今天在官网刚生成的token

以下是截图, 有哪些信息需要补充 or 哪些debug方法可以尝试的~?
<img width="822" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/29f2e9a1-5be7-4463-a493-507f0f0aea0d">
<img width="1440" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/05910554-b915-4104-a516-273ead96cac2">

**Comment by Kenshin** [comment]
我在休假，暂时没法详细测试，先 Mark 下，等时间方便时会回复你的。

不过，需要你的帮忙测试，到时候我联络你。

**Comment by QunWei-L** [comment]
好, 我再附一些信息:

尝试在"开发者工具"里观察每次网络请求,  使用"阅读助手"的时候, 有个请求看起来有SSL验证异常
<img width="492" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/505642e6-9da4-43b1-85d5-8d02fa28ed0b">
<img width="890" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/e4107817-84f4-4d98-a29f-4671dccdf4d9">

**Comment by Kenshin** [comment]
emmmm

可能有点问题，只能等我回去处理。

**Comment by Kenshin** [comment]
嗨，我休假回来了，确认了这个问题，是因为 `openai.simp.red` SSL 证书过期造成的，我已经联系了服务器提供方来解决这个问题。

有后续结论我会在这里通知你~

**Comment by Kenshin** [comment]
嗨，这个问题应该解决了，你可以重新测试下。

<img width="1211" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f07aef49-9327-4e7b-b414-121d65bb5738">

如果你那边仍有问题，说明是缓存造成的，请稍晚再确认下。

你可以直接打开 https://openai.simp.red/ 然后确认~

**Comment by QunWei-L** [comment]
看起来证书还有点异常, 提示"证书无效"https://github.com/Kenshin/simpread/issues/6271
<img width="541" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/9c7a16a4-2319-467f-9203-aff26d1a7ecc">

**Comment by Kenshin** [comment]
@QunWei-L 

不要重复建立 Issues 我关闭了 #6271 了。

我这边是没问题的 https://github.com/Kenshin/simpread/issues/6233#issuecomment-1903268936 之前说了可能是缓存的问题，稍晚再看下。

**Comment by Kenshin** [comment]
@QunWei-L 

关于 https://github.com/Kenshin/simpread/issues/6271#issuecomment-1903395920 的内容，应该还是证书问题，估计仍旧是缓存造成的。

你可以稍晚再试试，或者清除浏览器缓存后再测试。

**Comment by Kenshin** [comment]
补充下，隐私模式使用

<img width="1229" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1d8f9d5c-9ef1-4980-bb69-6941e43a997a">

非隐私模式下使用

<img width="1891" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6cc895c5-5df1-4c3d-b0c4-649b75c52d57">

**Comment by Kenshin** [comment]
@QunWei-L 

稍晚再试试吧

**Comment by QunWei-L** [comment]
目前还是无法使用, 无痕模式也会报错, 请求的status一直是pending
直接访问https://openai.simp.red/, 看起来没有证书问题了
<img width="571" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/18163c25-3673-493f-8649-0239c00a84fd">
<img width="759" alt="image" src="https://github.com/Kenshin/simpread/assets/17978275/d7df6a7e-73f2-468b-9f75-c6ea6a144d78">

**Comment by Kenshin** [comment]
我看了下后台的日志，就在刚刚还有用户在使用.... 

<img width="120" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8c4cda6f-3ff8-42fb-8b65-3362e1c37d56">

**Comment by QunWei-L** [comment]
方便我们开个zoom远程看看问题嘛?  找个您方便的时间

**Comment by QunWei-L** [comment]
网络目前测试了家里wifi和手机开流量热点, 都出现了类似的问题.

有北美的用户能正常使用的情况不?  目前感觉可能有这方面的因素

**Comment by Kenshin** [comment]
你在国外？

PS：我让 tw 的用户测试过是没问题的。

**Comment by QunWei-L** [comment]
是的, 美国

**Comment by Kenshin** [comment]
好，我研究下其他用户。
