### ISSUE TITLE
导出obsidian

### ISSUE THREAD

**Issue by Yusanshou** [Kenshin/simpread#6234]
### 描述这个错误

下载了插件以后没有这个动作 也不跳出设置界面 导致无法完成和ob联动的关键设置 

### 复现步骤

全部步骤都对，就是不跳出设置 
![屏幕截图 2024-01-07 151725](https://github.com/Kenshin/simpread/assets/153055057/17c19b84-6174-48fb-8455-7699f7f045e9)
![屏幕截图 2024-01-07 151717](https://github.com/Kenshin/simpread/assets/153055057/68b8fb6a-af44-4736-8522-9e471ae38859)
![屏幕截图 2024-01-07 151656](https://github.com/Kenshin/simpread/assets/153055057/38efdd02-479e-479f-8086-89bb6a619ecb)

### 操作系统

win

### 浏览器

edge

### 发生问题的网址

https://sspai.com/post/75567

**Comment by Kenshin** [comment]
嗨，估计是这个问题造成的。

使用同步助手的自动同步无法安装插件或插件配置无法保存的问题 → https://www.yuque.com/kenshin/simpread/fcw60u
