### ISSUE TITLE
关于 Assistive Touch 的使用建议

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6235]
输入快捷键后，无效
问题1：能不能用两个按键作为快捷键，比如：alt + 1 
问题2：在例子中，输入d d，需不需要在中间按空格。我直接输入dd，中间无空格。
问题3：在输入完快捷键后，调回功能，快捷键消失，又显示成请输入快捷键，如不选回功能，刷新页面后，但功能失效。

_Originally posted by @yjnu in https://github.com/Kenshin/simpread/discussions/1600#discussioncomment-8024288_

**Comment by Kenshin** [comment]
@yjnu 

我帮你新建了一个 Issues，并删除了原来位置的内容。

**Comment by yjnu** [comment]
> @yjnu
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。

等大佬休息完了告诉我怎么操作，麻烦了

**Comment by Kenshin** [comment]
没问题，只要记录为 `todo` 我都会一一处理。

**Comment by Kenshin** [comment]
> 问题 1

不能，你估计是理解错了这个功能，这个功能主要是为了可以在无法使用快捷键的地方（如手机端）使用的。

<img width="956" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/39ee0e9a-fe62-45f2-a9f9-5b217d358a38">

`alt 1` 这种是不行的，这里输入的快捷键必须是一个存在且已知的快捷键，比如：插件的快捷键、简悦系统的快捷键等。

> 问题 2

`d d` 中间是需要有空格的。

> 问题 3

我没太理解这个问题，但估计跟问题1有关系，所以可以忽略这个问题。

**Comment by yjnu** [comment]
懂了，不是给电脑端用的

**Comment by Kenshin** [comment]
> 懂了，不是给电脑端用的

准确的说是快捷键功能。
