### ISSUE TITLE
聚焦模式无法退出（与另外的扩展不兼容造成）

### ISSUE THREAD

**Issue by Arnolinw** [Kenshin/simpread#624]
聚焦模式下，与另一个插件保护眼睛冲突，导致进入聚焦模式后无法退出。

**Comment by Kenshin** [comment]
谢谢反馈，因为要改变页面，所以自然会跟其它改变页面的扩展会出现未知不兼容问题。
建议告诉我扩展的详细名字，我看看能否解决。

**Comment by Arnolinw** [comment]
> 谢谢反馈，因为要改变页面，所以自然会跟其它改变页面的扩展会出现未知不兼容问题。
> 建议告诉我扩展的详细名字，我看看能否解决。

扩展名： 保护眼睛

**Comment by Kenshin** [comment]
我刚才测了下，没有发生你说的问题。

不过，我怀疑是另外的 Bug 造成的，具体解决方案 https://github.com/Kenshin/simpread/issues/581#issuecomment-556893378

解决后，请告诉我下，这个 Bug 会在下个版本中修复。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

此问题已经被解决了

> 由于临近春节，所以本 issues 会在节后关闭，如已确认，请自行关闭

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg
