### ISSUE TITLE
导入 Notion 的使用疑问

### ISSUE THREAD

**Issue by zxc321zxchb** [Kenshin/simpread#6240]
### 描述这个错误

1、导入notion图床cloudinary保存，还是不行，保存到notion里面没有图片，只有文字
2、导入notion提示成功后，使用notion增强，提示：Notion 辅助增强优化失败，请手动重新优化。
3、手动点击notion增强还是不行
4、导入notion的配置库，使用插件管理器后，自动化插件维护的快捷键，刷新页面后就没了，我发现如果不使用插件管理器，则没事

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/42381259/f6ff190d-36c0-4d13-bc6b-449af621a686)

### 操作系统

m1

### 浏览器

Arc 版本1.21.3 （44713） Chromium Engine Verslon 120.0.6099.199

### 发生问题的网址

掘金

**Comment by Kenshin** [comment]
> ### 描述这个错误

1、导入notion图床cloudinary保存，还是不行，保存到notion里面没有图片，只有文字 2、导入notion提示成功后，使用notion增强，提示：Notion 辅助增强优化失败，请手动重新优化。 3、手动点击notion增强还是不行 4、导入notion的配置库，使用插件管理器后，自动化插件维护的快捷键，刷新页面后就没了，我发现如果不使用插件管理器，则没事
> 
> ### 复现步骤
> ![image](https://private-user-images.githubusercontent.com/42381259/295145895-f6ff190d-36c0-4d13-bc6b-449af621a686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTM4MjUsIm5iZiI6MTcwNDc5MzUyNSwicGF0aCI6Ii80MjM4MTI1OS8yOTUxNDU4OTUtZjZmZjE5MGQtMzZjMC00ZDEzLWJjNmItNDQ5YWY2MjFhNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjZjNGMwMWU2Y2I0ZDVjNDAzYTg1NjkzM2Q2MjgyYWViN2E2ZTNkMGZjMTQ4MjY1YjI4MmQ0YmM0NzcyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ypz8CjaIRUVSPTT4l-VQYAfXt5DTX9xstZUAWXMtlHM)
> 
> ### 其他相关说明
> _No response_
> 
> ### 操作系统
> m1
> 
> ### 浏览器
> Arc 版本1.21.3 （44713） Chromium Engine Verslon 120.0.6099.199
> 
> ### 发生问题的网址
> 掘金

**Comment by Kenshin** [comment]
1. 使用少数派测试 cl 图床
2. 先不要使用 Notion 辅助增强插件。

确保你可以正常使用导入 Notion 插件正常的前提下再考虑其它方案。

**Comment by zxc321zxchb** [comment]
少数派可以保存到notion，并且图片地址cl图床的

**Comment by Kenshin** [comment]
也就是说只有掘金无法使用？

**Comment by zxc321zxchb** [comment]
我试了试csdn，可以，目前只有掘金，我试到其他有问题的，再反馈；
插件管理那个可能是什么原因，使用插件管理加载全部插件、保存全部插件配置之后，自动化辅助增强配置的值就没了

**Comment by Kenshin** [comment]
插件管理器的问题看下 https://www.yuque.com/kenshin/simpread/fcw60u

肯定是这个问题造成的。
