### ISSUE TITLE
当页面比较大，如含有比较多图片时，保存为离线 Markdown 或离线 HTML 会静默失败

### ISSUE THREAD

**Issue by BearD01001** [Kenshin/simpread#6241]
### 描述这个错误

当页面比较大，如含有比较多图片时，保存为离线 Markdown 或离线 HTML 首先会出现“图片转换中，请稍后...”，等待一段时间后，转换图片的提示会消失，但并不会弹出保存成功的提示，会静默失败，打开 output 文件夹也没有对应的离线文件。

### 复现步骤

1. 打开一个含有图片比较多的大页面
2. 进入 simpread 的阅读模式
3. 通过右下角的悬浮菜单 [动作> 导出 > 离线 Markdown / 离线 HTML]

### 操作系统

macOS

### 浏览器

Chrome Version 120.0.6099.129 (Official Build) (arm64)

### 发生问题的网址

内网地址，不方便提供

**Comment by Kenshin** [comment]
有可能存在这种情况…大概多少图片？

我测试过 50+ 是没问题的，但也要看图片的本身大小。

不过，这个问题可能不太好解决，可以试试 https://github.com/Kenshin/simpread/discussions/4041

**Comment by BearD01001** [comment]
> 有可能存在这种情况…大概多少图片？
> 
> 我测试过 50+ 是没问题的，但也要看图片的本身大小。
> 
> 不过，这个问题可能不太好解决，可以试试 #4041

多谢回复哈，我感觉可能是被浏览器限制了，如果是这样的话确实不好解决，我试试 4041 的方法去。

**Comment by Kenshin** [comment]
如果是偶发的话，可能是电脑的性能问题。
如果是个例的话，基本上可以忽略不计。

**Comment by BearD01001** [comment]
目前看是必现的，机器是 m1 pro 32gb 内存的，平时开发都还够用。

**Comment by Kenshin** [comment]
M1 的话，系统性能没问题。
你可以找少数派的网页，它上面有一些以游记为主的文章（图片多），看看是否仍无法使用。

**Comment by Kenshin** [comment]
嗨，各位。

简悦升级了 **离线 HTML** 或 **离线 Markdown** 方案，所以此问题应该可以解决了。

### 解决方案

需要安装 [离线下载辅助增强插件](https://github.com/Kenshin/simpread/issues/6582)

### 特点

与简悦内置的离线方案在功能上保持一致，同时包括了如下的一些新特性：

1. 支持更简单的快捷键触发机制，离线 HTML 快捷键 <kbd>o</kbd> <kbd>h</kbd> 离线 Markdown 快捷键 <kbd>o</kbd> <kbd>m</kbd>，详细说明 https://github.com/Kenshin/simpread/discussions/6579#discussioncomment-9900514

2. 提供更多的 Markdown 嵌入 base64 结构 https://github.com/Kenshin/simpread/discussions/6579#discussioncomment-9900514

与内置的离线方案区别 https://github.com/Kenshin/simpread/discussions/6579#discussioncomment-9900493

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/hquTm5HDO5) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

有任何问题请随时讨论~
