### ISSUE TITLE
希望支持xlog适配

### ISSUE THREAD

**Issue by whitewatercn** [Kenshin/simpread#6245]
### 需要适配的新站

xlog是一个近期出现的开源博客系统，适配以后应该可以同时支持所有使用了xlog的博客，期待支持
官网：https://xlog.app/
我写过的一点介绍：https://www.isharkfly.com/t/xlog/14491

使用xlog的站点如：
https://xlog.whitewater.wang/%E7%90%83%E6%97%81%E5%99%A8JGA
https://diygod.cc/ohmyrss

**Comment by whitewatercn** [comment]
打扰了，看到已经适配了

**Comment by Kenshin** [comment]
把这个问题放到这里了。

我在休假，暂时没法处理，等有时间是会处理。

**Comment by whitewatercn** [comment]
> 把这个问题放到这里了。
> 
> 我在休假，暂时没法处理，等有时间是会处理。

辛苦了，不是很急的问题，静候佳音

**Comment by Kenshin** [comment]
嗨，我休假完毕了。

***

[xLog 辅助增强插件](https://simpread.ksria.cn/plugins/details/CQOOA9x5S3) 更新到 1.0.1 解决你提到的问题。

**Comment by whitewatercn** [comment]
谢谢大佬，已完美解决

> 嗨，我休假完毕了。
> 
> [xLog 辅助增强插件](https://simpread.ksria.cn/plugins/details/CQOOA9x5S3) 更新到 1.0.1 解决你提到的问题。

**Comment by Kenshin** [comment]
哈，解决就好

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

**Comment by whitewatercn** [comment]
> 哈，解决就好
> 
> 请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

哈哈早就好评了，刚上架就开始用了
写了一个小安利https://forum.beginner.center/t/topic/718

**Comment by Kenshin** [comment]
👍 谢谢。

PS：没想到是老用户  😏

**Comment by whitewatercn** [comment]
> 👍 谢谢。
> 
> PS：没想到是老用户 😏

一直轻度使用，所以很多配置不太了解哈哈

**Comment by whitewatercn** [comment]
kensin好，最近又出现了简阅和xlog的问题，
在[这个页面](https://cn.whitewater.wang/%E5%8D%8A%E6%9C%88%E6%9D%BF%E6%8D%9F%E4%BC%A4%E3%80%81%E6%92%95%E8%A3%82)用简阅导出时丢失了很多内容，导出前我已经把该页面所有图片都显示出来了

不知道如何帮助你debug
<img width="1381" alt="image" src="https://github.com/Kenshin/simpread/assets/58654928/158f312c-2c9d-4927-aa43-a80c228169d4">
