### ISSUE TITLE
建议可选关闭标注后右上角“已成功保存”提示

### ISSUE THREAD

**Issue by O2iginal** [Kenshin/simpread#6247]
### 请描述你的建议或任何内容

在开启Obsidian自动化保存后，每次标注会在页面右上角弹出动态的“已成功保存”提示。

个人认为这样的连续弹出可能影响专注阅读，能否有一个选项，可以隐藏此提示。

![image](https://github.com/Kenshin/simpread/assets/114271371/1e1037b3-5191-40d5-8c99-6ce75882f3cc)

**Comment by Kenshin** [comment]
自动化辅助增强插件里面有个选项可以关闭这个提示。
