### ISSUE TITLE
导入到Obsidian失败

### ISSUE THREAD

**Issue by FinTechCao** [Kenshin/simpread#6249]
### 描述这个错误

点击导入全文到Obsidian、导入标注到Obsidian都显示失败。
用教程中已有的案例，增减标注不会报错，但Obsidian文件夹里的md文件没有变化，output文件夹里的html有变化。
用新的页面进行标注时，output文件夹里会自动增加html文件，Obsidian文件夹中的md文件无变化。

### 复现步骤

![截屏2024-01-14 22 58 45](https://github.com/Kenshin/simpread/assets/8079985/48141786-7e99-4362-a092-264f5f0d3977)

### 操作系统

macOS 14.0

### 浏览器

Chrome 版本 116.0.5845.187（正式版本） (arm64)

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
emmmm 

需要开着Obsidian 才能让里面的 md 变化。

另外一点，你看下 Markdown 模板辅助增强插件里面有没有内容？

**Comment by FinTechCao** [comment]
是要看这个吗？
![截屏2024-01-15 22 45 54](https://github.com/Kenshin/simpread/assets/8079985/82ce3c6d-0f89-4f51-894c-9adf55981c01)
点了“测试”按钮

**Comment by FinTechCao** [comment]
我的Ob版本：Version 1.5.3 (Installer 1.4.14)

**Comment by Kenshin** [comment]
把你的配置中与路径相关的都截图给我看下，

**Comment by FinTechCao** [comment]
![image](https://github.com/Kenshin/simpread/assets/8079985/effac35d-398b-4494-aa90-c5b8494dde70)
![image](https://github.com/Kenshin/simpread/assets/8079985/cc855039-6172-4200-803b-fb19f375ddfd)
![image](https://github.com/Kenshin/simpread/assets/8079985/2ad2764f-8ca2-4459-b7a3-71fed4db5b0f)
Users/Adam/Downloads/SimpRead【Users前面没法加/，是不是这个问题导致的】

我用Windows试了，一把成功，没有问题。在macOS上就不行

**Comment by Kenshin** [comment]
路径看起来没问题，一般来说也都是 Win 出问题的几率大一些… Mac 很少出问题。

😂

PS：win 设置通过说明你的配置是没问题的。

**Comment by Kenshin** [comment]
把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6249

我目前在休假，暂时没法确认，只能等我回去（下周）再确认下。

**Comment by Kenshin** [comment]
嗨，休假完毕了~

***

我使用了你提供的配置文件，完全没有任何问题，就不截图了，测试内容：

1. 直接导入全文到 Obsidian

2. 使用 `d d` 加入稍后读后自动发送到 Obsidian

3. 在步骤2的基础上标注，标注内容也能自动更新到 Obsidian

Obsidian 版本

<img width="246" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/dc6287a0-b4a9-4973-8f7d-7fbff53ddfbf">

SimpRead Sync Obsidian Plugin 设置

<img width="775" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3fb1c3ee-613f-448a-91f8-ccf23c37cf12">

你提到的 Obsidian 路径 `Users/xxxx/SimpRead`

同步助手的 output 路径

<img width="692" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/22c3bdac-a257-4a27-9c2e-33e198c7979d">

***

#### 建议

我会 Email 给你一份配置文件，你在 Mac 上重新安装简悦，然后：

1. 导入这份配置文件
2. 选项页 → 插件管理 → 从配置文件导入全部插件
3. 重启浏览器

然后再留意下这两个路径确保一致

![image](https://github.com/Kenshin/simpread/assets/81074/f5a1de48-5e1d-4b43-8f87-c47bbb0f274e)

**Comment by FinTechCao** [comment]
还是不行……算了，我也无法理解为什么，我就用Windows上的吧，感谢感谢

**Comment by FinTechCao** [comment]
我刚才在windows上没开Ob也出现了最上面的图里的报错。
所以是不是macOS上没识别到Ob开了，是不是跟应用的什么权限有关。
我的电脑型号：Apple M1 Pro，macOS 14.0 (23A344)

**Comment by Kenshin** [comment]
跟 Mac 理论上无关，跟 Obsidian 有关系。

你的这个错误是因为调用 Obsidian SimpRead Sync 服务失败造成的，前几个版本确实存在这个错误，但理论上新安装的版本不会再发生了，这个错误的细节 https://github.com/Kenshin/simpread/discussions/5601

你可以在 Mac 上访问 http://localhost:7027/ 看看是什么结论。

另外，试试启用一个新的库，仅安装 Obsidian SimpRead Sync 看看能否解决？

**Comment by FinTechCao** [comment]
不好意思后来我忘记这件事了，直到Windows和Mac来回切换实在难受就又想挣扎一下……
在 Mac 上访问 http://localhost:7027/ ，打不开，而Windows上就正常显示SimpRead Sync server run，
看来就是macOS的环境有问题了，那有什么操作可以排查吗？有什么地方会有日志吗

**Comment by Kenshin** [comment]
> 看来就是macOS的环境有问题了

重新开一个新库安装 Obsidian SimpRead Sync 然后重启 Obsidian 确保只有一个 Obsidian 在使用，然后测试。
