### ISSUE TITLE
代码块显示不好

### ISSUE THREAD

**Issue by chelseachen007** [Kenshin/simpread#6250]
### 请描述你的建议或任何内容

![image](https://github.com/Kenshin/simpread/assets/36880000/3c6f1acf-0d5d-4684-ad5e-b108fa30e14a)

### 补充说明

https://mp.weixin.qq.com/s/stkDZ88---Ebvweddz_yHg 这个文章的代码块显示了很多无序列表，影响阅读体验

**Comment by Kenshin** [comment]
代码高亮插件有一些问题，我会考虑这个建议的。

代码段的问题会集中在 https://github.com/Kenshin/simpread/issues/500 并关闭此 Issues 修复后会通知你~
