### ISSUE TITLE
无法正确解析微信读书的网页内容

### ISSUE THREAD

**Issue by Connor-idea** [Kenshin/simpread#6253]
### 描述这个错误

![Screenshot - 2024-01-15 20 06 57](https://github.com/Kenshin/simpread/assets/48904236/52fa7aa1-a2f7-40a4-9924-bca380743699)
解析出现正文内容缺失

### 复现步骤

1.打开微信读书网站，点击进入阅读页面，点击插件解析
2.解析成功时仅可以展示书籍内容的标题
3.解析不成功时需要手动聚焦但仍然无法正确解析并且解析结果内容丢失

### 操作系统

macOS

### 浏览器

Chrome最新版本

### 发生问题的网址

https://weread.qq.com/

**Comment by Kenshin** [comment]
嗨，这类页面是不可以被适配的，谢谢提示。

我关闭这个 Issues 了。
