### ISSUE TITLE
英语阅读是否可以支持高亮特定词汇表

### ISSUE THREAD

**Issue by lagaya** [Kenshin/simpread#6257]
### 请描述你的建议或任何内容

对于英语阅读以及学习，比如可以加入托福 雅思 gre Gmat 专八等等词汇表，对应不同颜色，这样读的时候可以看到重难点词汇

**Comment by Kenshin** [comment]
这个插件有个「生词本」的功能，你可以试试 https://github.com/Kenshin/simpread/discussions/1592
