### ISSUE TITLE
导入 Notion 正文出现大量断行（跟简悦无关而是 Notion API 错误导致）

### ISSUE THREAD

**Issue by threeyears121** [Kenshin/simpread#6259]
# 遇到此问题请看这里的解释说明 https://github.com/Kenshin/simpread/issues/6259#issuecomment-1913076732

> 以下是用户提问

### 请描述你的建议或任何内容

使用简悦导入notion后，内容出现大量断行，不知道这是我设置问题还是什么问题，中英文的网站都出现了这种情况

截图如下：

![WX20240116-172015@2x](https://github.com/Kenshin/simpread/assets/33708762/504a75cc-8fa0-42e5-8cba-34a828996d67)
对应的网站如下：[https://kns.cnki.net/KXReader/Detail?invoice=J8OnYs9wcUKYnWRNcI4T1ZLHG%2FZAi3eNNqimw5LyaFnO2BK7os%2BKQehOe0rrZZWeLoq8ob6vfKZEquIKebWEBVse4Gy8uWNY60zSdLwb%2FtUPqBBUney1HpDNpzyiL66sZzjJl29l9LiGgJDwbLC9NTIn3NDTgJhSVPkjQqMj1GU%3D&DBCODE=CJFQ&FileName=SHZZ202301002&TABLEName=cjfdlast2023&nonce=567561E0F0D44351AAE2537E53D128C4&TIMESTAMP=1705247773421&uid=](url)

**Comment by nibabadebababa** [comment]
我也碰到了这个问题, 好像是原文有空格就会发生断行.

**Comment by Kenshin** [comment]
导出 Markdown 到本地然后看下是否有这个情况吗？

如果没有问题的话，就是 Notion 本身的问题。

**Comment by nibabadebababa** [comment]
> 导出 Markdown 到本地然后看下是否有这个情况吗？
> 
> 如果没有问题的话，就是 Notion 本身的问题。

导出到markdown是没问题的, 这么看应该是notion那边的问题

**Comment by threeyears121** [comment]
导出到markdown没有问题

**Comment by Kenshin** [comment]
@threeyears121 

okay 那就是 Notion 的锅，因为它们使用的是同样一套逻辑。

**Comment by Kenshin** [comment]
应该是个例吧？多试试不同的网页导入。

**Comment by threeyears121** [comment]
刚试了一下，不是个例，大部分网站都出现这个问题了

**Comment by Kenshin** [comment]
试试少数派的网页。

**Comment by threeyears121** [comment]
![WX20240116-200453@2x](https://github.com/Kenshin/simpread/assets/33708762/d757e5d1-db90-48f8-ba08-98b6fc9c5eb5)
一样的，有很多不必要的断行

**Comment by Kenshin** [comment]
@threeyears121 

你导入的有点奇怪…你确实使用的是简悦？（截图中有一些不属于简悦的阅读模式内容…）

试试在隐私模式下，仅启用简悦的方式。

**Comment by threeyears121** [comment]
InPrivate模式下，用不了简悦进入阅读模式

**Comment by threeyears121** [comment]
Inprivate 模式下保存不成功啊，总是显示正在保存，请稍后，一直保存不了
![Uploading WX20240116-203150@2x.png…]()

**Comment by Kenshin** [comment]
有点奇怪，我让其他用户测试了这个问题，是可以正常导入的。

而且在隐私模式下也可以正常使用。

建议重新设置下 Notion 或者详细描述你的使用过程…

**Comment by threeyears121** [comment]
怎么重新设置比较彻底呢，我刚关闭又重新打开 导入notion的设置，然后选择好导入的页面，结果还是没有解决问题
![WX20240117-151403@2x](https://github.com/Kenshin/simpread/assets/33708762/a361db66-40e1-416d-aaba-638b9735c369)

**Comment by Kenshin** [comment]
@Sunsh4j 

https://github.com/Kenshin/simpread/issues/6259#issuecomment-1895441616

我回去详细研究下。

> 能否在导出文件到本地后，自动打开导出路径的文件资源管理器啊

不能 Chrome 没有这种方案。 😂

**Comment by Kenshin** [comment]
@Sunsh4j 

> 扩展能和同步助手通信不，在导出完毕后，由同步助手打开导出路径？

这是可以的，但我不觉得这个方式有什么特别的意义 😂

**Comment by Kenshin** [comment]
嗨，各位。

我测试了下，直接从 Notion Import 也会出现这个问题。😂

<img width="1568" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1ae8edb2-b37b-44ed-b812-1f2c8e1fbccd">

<img width="916" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6b525c78-7447-4593-aa22-29fab82236b7">

测试文件 [派早报：OPPO 与诺基亚达成专利交叉许可协议，微软游戏部门裁员 1900 人等.txt](https://github.com/Kenshin/simpread/files/14071667/OPPO.1900.txt)

你们也可以自行找一些 Markdown 文件测试 😂

***

后续我会找 Notion 相关人员反馈下这个情况。

**Comment by lyserenity** [comment]
我测试了一下 import，的确会断行，而且如果是中文为主的文章，它好像会断在「左右都有空格」的英文附近.....

**Comment by WenchenWang** [comment]
我也出现断行了，很难受

**Comment by WenchenWang** [comment]
> 嗨，各位。
> 
> 我测试了下，直接从 Notion Import 也会出现这个问题。😂
> 
> <img alt="image" width="1568" src="https://private-user-images.githubusercontent.com/81074/300166245-1ae8edb2-b37b-44ed-b812-1f2c8e1fbccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjg4OTcsIm5iZiI6MTcwODIyODU5NywicGF0aCI6Ii84MTA3NC8zMDAxNjYyNDUtMWFlOGVkYjItYjM3Yi00NGVkLWI4MTItMWYyYzhlMWZiY2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmQwNGEzNjA5OThlNjAxODFiYTQzYWY5YWM5YjgwNzc4MjU0MzM0OTJjN2ZiMzVmNTczMDQ3NzlhNmM4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5vkR9IGqmEN5leV4YPAMPxSjXgfhGbshYuSw6Og3NIk"> <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/81074/300166284-6b525c78-7447-4593-aa22-29fab82236b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjg4OTcsIm5iZiI6MTcwODIyODU5NywicGF0aCI6Ii84MTA3NC8zMDAxNjYyODQtNmI1MjVjNzgtNzQ0Ny00NTkzLWFhMjItMjlmYWI4MjIzNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTI5MDdjYjY1YWQwNzI2ZDk2Mzc1NGU3MzY3N2ViOGYwOGQ2OWY1OGM4ZTVhNGQ5Yjg5YjczN2JmOGU2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E9FX8XdgE4nbP9lIiXrPhKq6s48_FFzc3uSCo771BEo">
> 测试文件 [派早报：OPPO 与诺基亚达成专利交叉许可协议，微软游戏部门裁员 1900 人等.txt](https://github.com/Kenshin/simpread/files/14071667/OPPO.1900.txt)
> 
> 你们也可以自行找一些 Markdown 文件测试 😂
> 
> 后续我会找 Notion 相关人员反馈下这个情况。

请问大大啥时候可以解决？很难受。。

**Comment by Kenshin** [comment]
@WenchenWang 

不是简悦的锅，以我对 Notion 以往反馈后的的调性来说，只有一个字 **等**

**Comment by WenchenWang** [comment]
@Kenshin 好好好，😭只能这样了

**Comment by iknowzxc** [comment]
这个问题解了嘛

**Comment by WenchenWang** [comment]
> 这个问题解了嘛

并没有解决，很难受

**Comment by Kenshin** [comment]
@WenchenWang @iknowzxc 

是的，没有解决。

如果解决了我会通知这里的用户，并且 Close Issues

**Comment by KennyNoDie** [comment]
有没有办法对导入的文章批量修复这些异常的换行

**Comment by Kenshin** [comment]
@KennyNoDie 

脑洞不错，但你觉得 Notion 有这种 API 吗 😂 （当然没有，它们连这种问题都懒得马上解决...

**Comment by WenchenWang** [comment]
@Kenshin 那大佬这情况啥时候可以解决？- - 好久了，有好多文章我都等解决重新导入的 - -

**Comment by nibabadebababa** [comment]
> @Kenshin 那大佬这情况啥时候可以解决？- - 好久了，有好多文章我都等解决重新导入的 - -

有一个不太批量的解决方法, 第一就是你把全文复制, 然后用ChatGPT写个prompt(大概就是解决这些换行问题), 让GPT处理完再复制回来; 第二就是你用notion自带的AI(可以淘宝买), 选中全文, 然后使用自己的prompt或者是AI自带的语法检查和修改功能, 也可以解决换行问题, 不过实测这种方法不太好用, 一段话一段话还好说, 全文选中修正效果就不太行了(说到底还是notionAI不太行).

**Comment by Kenshin** [comment]
@nibabadebababa 

哈哈，思路清奇，不过这种太「麻烦」了，治标不治本。

**Comment by SgAriFool** [comment]
我最近也发现了这个问题, 刚准备提个issue锁了一下发现原来不是我一个人有这个问题, 怎们又是notion抽风啊(恼), 印象中他们已经抽风好几次了(为了解决notion导入问题已经占用了两个插件的位置了, 哭)
我目前的一个简单的解决方案是, [复制Markdown到剪切板]->[粘贴], 但是图用的还是链接不是图床还得自己弄(

**Comment by Kenshin** [comment]
@SgAriFool 

网盘的「问题」可以解决，使用 [图床插件](https://github.com/Kenshin/simpread/discussions/4306) 将图片上传到你的网盘后会自动替换为图床链接，然后再复制到剪切板。

**Comment by SgAriFool** [comment]
今天测试了一下, 这个issue官方貌似修复了

**Comment by Kenshin** [comment]
嗨，各位。

经过 @SgAriFool 提醒以及我测试，发现这个 Bug 确实被 Notion 官方修复了 👍 **时隔 105天+**  🌚 

***

我关闭这个 Issues 了。
