### ISSUE TITLE
任意元素整页隐藏之后，无法恢复

### ISSUE THREAD

**Issue by ScorPian00** [Kenshin/simpread#626]
查看微信公众号文章时，看到有些代码，格式兼容性不好，前面有很多点，尝试 使用任意元素隐藏功能，导致整个页面都隐藏了，如何让它显示出来。更惨的是，所有微信公众号的文章，使用简悦，好像都整页隐藏了，一片空白

**Comment by liangpengjie** [comment]
![image](https://user-images.githubusercontent.com/38686607/70975059-2397ba80-20e4-11ea-8e14-61e97ad60d6f.png)
站点管理器把自定义的网址删除掉

**Comment by Kenshin** [comment]
@ScorPian00 

- 可以试试安装 https://github.com/Kenshin/simpread/issues/500 看能否解决这个问题。

- 微信公众号确实有这方面的问题，因为他属于 UGC 简悦很难用一种普世规则来判断。

建议把出现问题的公众号告诉我，我来看看

***

@liangpengjie 

你想说什么？

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

我在清理 issues 请确认是否还存在问题？没有的话，请关闭 issues

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by heloook** [comment]
> ![image](https://user-images.githubusercontent.com/38686607/70975059-2397ba80-20e4-11ea-8e14-61e97ad60d6f.png)
> 站点管理器把自定义的网址删除掉

可以了，谢谢！

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 新的方案：只能在正文中进行删除操作。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
