### ISSUE TITLE
关于自动化的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6262]
没搞懂，是进入阅读模式，然后再加入稍后读，才会自动保存吗？我没进入阅读模式，直接按DD加入稍后读，没看见自动保存？那我都aa进入阅读模式了，我再按个at，和按dd没区别了呀，

_Originally posted by @850312766 in https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-8171803_

**Comment by 850312766** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Kenshin** [comment]
@850312766

我新建了一个 Issues 讨论。

***

> 是进入阅读模式，然后再加入稍后读，才会自动保存吗？

是的，只能是这个方案，即便其他方案也能加入稍后读，但只有这个方案才能触发自动化。

**Comment by 850312766** [comment]
> @850312766
> 
> 我创建了一个问题讨论。
> 
> > 是进入阅读模式，然后再加入夜间阅读，会自动保存吗？
> 
> 是的，只能是这个方案，其他方案也可以加入稍后读，但只有这个方案才能触发自动化。

ok，老哥，我懂了，谢谢。我也是第一次用这个简悦，好多东西没搞懂 0.0

**Comment by Kenshin** [comment]
哈，小事情，有任何使用疑问随时在这里 https://github.com/kenshin/simpread/issues/new 我会 100% 解决你（用户）的的问题 😄
