### ISSUE TITLE
关于配置文件的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6264]
您好！
之前一直使用，各方面都配置了，包括同步助手和坚果云登录。
最近把插件从浏览器卸载了重装，发现登录不了。
若使用配置文件登录，会显示“配置文件解析失败，请重新确认”；
若使用坚果云登录，转圈后没任何反应，也没登录上。

如果直接从“选项也”——“通用”——“配置文件”——“从本地带入配置文件”，则会显示“上传失败，配置文件解析失败，请重新确认”。
请问一下这种情况怎么办？

_Originally posted by @operations4304 in https://github.com/Kenshin/simpread/discussions/1574#discussioncomment-8177380_

**Comment by Kenshin** [comment]
我已自己解决了。我通过坚果云将simpread_config的历史版本回溯到之前的一个版本。
但是我发现，昨天下午的5分钟之内，simpread_config的大小从23.17MB，突然变为48.78MB。今天我导入48.78MB的文件就显示“解析失败”，23.17MB的就能正常导入。
不知道是什么原因，只知道昨天下午那段时间我应该是在用简悦的。
                                                                                                                                                                                                                        谢谢！

**Comment by Kenshin** [comment]
@operations4304

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 昨天下午的5分钟之内，simpread_config的大小从23.17MB，突然变为48.78MB

可能你在标注时产生了一些方便标注定位的信息造成的，我不确定，只是有这种可能性。尤其是在做大量标注且标注页面的结构比较特殊时。

> 今天我导入48.78MB的文件就显示“解析失败”，23.17MB的就能正常导入。

你可以使用 http://localhost:7026/database/fixed 解决配置文件的错误问题。

**Comment by s1067358196** [comment]
![image](https://github.com/user-attachments/assets/dd041e46-bc36-4275-ba2d-b585c64d2969)


导入本地配置时，上传解析失败

**Comment by Kenshin** [comment]
@s1067358196 

导入的配置文件名称是什么？

**Comment by Kenshin** [comment]
> notion@enhance 和notion@base 都试过不行。我试一下重装插件。浏览器是edge

如果是下图方式导入是没问题的（我刚测试完）

<img width="937" alt="image" src="https://github.com/user-attachments/assets/cd13e0f1-7434-46d4-aadb-5712dae20b0a">

**Comment by s1067358196** [comment]
> > notion@enhance 和notion@base 都试过不行。我试一下重装插件。浏览器是edge
> 
> 如果是下图方式导入是没问题的（我刚测试完）
> 
> <img alt="image" width="937" src="https://private-user-images.githubusercontent.com/81074/367153318-cd13e0f1-7434-46d4-aadb-5712dae20b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDc2NzcsIm5iZiI6MTcyNjIwNzM3NywicGF0aCI6Ii84MTA3NC8zNjcxNTMzMTgtY2QxM2UwZjEtNzQzNC00NmQ0LWFhZGItNTcxMmRhZTIwYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2MDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGIxYjNiNzQ2NzFhOGI3ZWQ2MjQ0YWVhMGQwMmJhNjQzYzk2MzZlMjVkMjlhNjMwODgwYzgzMjYyZWZlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfbYYR1zi2dbNakp544o7NCMlBADiGqFwJKXLw3Nc2U">

可以了可以了，是我操作有误

**Comment by Kenshin** [comment]
😂

所以，你用了什么导入方式？
