### ISSUE TITLE
sonoma 14.2.1上，简阅同步助手 1.2闪退

### ISSUE THREAD

**Issue by zhongfeiLiu** [Kenshin/simpread#6267]
### 描述这个错误

sonoma 14.2.1上，简阅同步助手 1.2无法与google浏览器上的设置同步，无法查到错误

### 复现步骤

<img width="343" alt="image" src="https://github.com/Kenshin/simpread/assets/49835342/afb11861-aec8-4931-a309-fbf298a0a4f2">

### 操作系统

sonoma 14.2.1

### 浏览器

版本 120.0.6099.234（正式版本） (arm64)

### 发生问题的网址

any

**Comment by Kenshin** [comment]
嗨，我让用户测试下了 Mac Sonoma 14.3 beta 3  是可以正常运行的。
