### ISSUE TITLE
网页保存到本地不知道是不是bug还是问题

### ISSUE THREAD

**Issue by ethan1010** [Kenshin/simpread#6269]
### 描述这个错误

教程： https://www.yuque.com/kenshin/simpread/wkswh7 。从配置增强导出，往后。。。我都配置了

![image](https://github.com/Kenshin/simpread/assets/22167899/54656e03-ba88-4da3-8dfc-dfc7fffa612d)

![image](https://github.com/Kenshin/simpread/assets/22167899/4626ba73-5a10-4897-aa07-b5f338684ac5)

不填写路径output，我也尝试了
![image](https://github.com/Kenshin/simpread/assets/22167899/3a717239-5c9e-409c-b984-2c7fb0205776)

![image](https://github.com/Kenshin/simpread/assets/22167899/636febcf-eb67-4090-b973-2ffbcb58dfe5)

![image](https://github.com/Kenshin/simpread/assets/22167899/170f61a0-9141-44dd-8f36-f97e32bda45f)

![image](https://github.com/Kenshin/simpread/assets/22167899/3682581d-aba7-4444-8416-afddab11b4a9)
image.png

为了防止因为我选择离线html、离线markdonw，我改成html、markdown尝试了下。
![image](https://github.com/Kenshin/simpread/assets/22167899/1f8a723c-b2b2-44c8-9087-cb1086ba58f1)

![image](https://github.com/Kenshin/simpread/assets/22167899/ff5a4432-5128-4853-b47a-58d9f986241a)

给你截图的功夫，我又检查，和验证了配置。。。。

还是没有在output中看到缓存保存的文件。

哎。。。。配置界面能简化下吗。。太复杂了。

光分布就分布在3个界面，这样多配置点。

### 复现步骤

已经写了

### 操作系统

win 10

### 浏览器

eagle

### 发生问题的网址

无

**Comment by Kenshin** [comment]
进入阅读模式后，请使用快捷键 `d d` 的方式加入稍后读。

另外，请多加几个稍后读。

最好直接使用 https://www.yuque.com/kenshin/simpread/any457 配置库方案。
