### ISSUE TITLE
使用简悦同步至logseq时没有@annote文件

### ISSUE THREAD

**Issue by zzget** [Kenshin/simpread#6272]
### 描述这个错误

最开始是按照这篇文章（[简悦 +Logseq 个人知识库搭建 | 从零开始完全指南](https://sspai.com/post/72022)）配置的 ，第一次成功了，之后因为某个插件的原因将简悦下载后重新导入配置，然后发现将文章再进行标注时只保存了两个文件，没有 @annote的文件（缺少两个文件名含@annote的 html 和 md 文件，以至于没办法同步）

### 复现步骤

刚开始的时候是
![image](https://github.com/Kenshin/simpread/assets/113426457/3ab8f6b8-57aa-45ba-be62-a783441cf268)
现在是
![image](https://github.com/Kenshin/simpread/assets/113426457/46c9ae8f-31d2-4d09-b77f-1c8bedd09ff9)

### 操作系统

Windows 11

### 浏览器

Chrome 120.0.6099.225

### 发生问题的网址

https://sspai.com/post/74975

**Comment by Kenshin** [comment]
嗨，解决就好 👍
