### ISSUE TITLE
网站字体更改失败

### ISSUE THREAD

**Issue by Marx-one** [Kenshin/simpread#6274]
### 描述这个错误

网站：https://www.gov.cn/xinwen/2021-02/25/content_5588869.htm
上面类型的网站更改字体，字体更改不了

### 复现步骤

1.样式
2.字体类型
3.自定义字体——楷体

### 操作系统

win11

### 浏览器

谷歌

### 发生问题的网址

https://www.gov.cn/xinwen/2021-02/25/content_5588869.htm

**Comment by Kenshin** [comment]
关于字体无法更改以及解决方案 [看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Atheme)
