### ISSUE TITLE
开启插件部分网页限制问题。

### ISSUE THREAD

**Issue by s0k** [Kenshin/simpread#6275]
### 描述这个错误

访问这个地址[mediawiki ](https://www.mediawiki.org/wiki/MediaWiki/zh-hans)，发现被隐藏了一些页面。

### 复现步骤

使用插件
<img width="1553" alt="image" src="https://github.com/Kenshin/simpread/assets/35159280/67115c1c-35f1-41e6-b2d2-8fd801540263">
不使用插件
<img width="1486" alt="image" src="https://github.com/Kenshin/simpread/assets/35159280/1d5d980d-8ac1-4c2e-8b8f-7b7fd8d33397">

### 操作系统

macOS

### 浏览器

chrome 120.0.6099.234

### 发生问题的网址

https://www.mediawiki.org/wiki/MediaWiki/zh-hans

**Comment by Kenshin** [comment]
应该是这个引起的，解决方案 https://github.com/Kenshin/simpread/discussions/2347
