### ISSUE TITLE
左侧出现两个滚动条，原先处于底部的slogan，也叠加到正文上了

### ISSUE THREAD

**Issue by Sunsh4j** [Kenshin/simpread#6277]
### 描述这个错误

![recording](https://github.com/Kenshin/simpread/assets/43169575/41054a04-d28f-477b-b7a3-542ce91e19ac)

### 复现步骤

随便打开一个页面，进入阅读模式就会出现

### 操作系统

Win10

### 浏览器

Chrome

### 发生问题的网址

任意网址

**Comment by Kenshin** [comment]
这个问题应该跟简悦无关，请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6277#issuecomment-1907932892

你这个截图显然有问题… 😂

你有没有其他浏览器？如果有的话，直接安装（一个新的）简悦。
