### ISSUE TITLE
导入到思源笔记插件思源图床不可用

### ISSUE THREAD

**Issue by wangjinbaor** [Kenshin/simpread#6279]
### 描述这个错误

打开图床功能，提示调用失败，关闭正常
![image](https://github.com/Kenshin/simpread/assets/58154171/37db965a-762b-4671-b7db-ad064bd1e2ae)

### 复现步骤

如上

### 操作系统

window

### 浏览器

版本 120.0.6099.227（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/post/86118

**Comment by Kenshin** [comment]
思源笔记的版本也告诉下~

**Comment by wangjinbaor** [comment]
> 思源笔记的版本也告诉下~

v2.12.5

**Comment by Kenshin** [comment]
嗨，我测试了下，是没问题的。

不知道是否是下图没有开启？

<img width="1047" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c249c458-06cb-4dde-bbf9-c45025806d65">

1. 请问是本机导入吗？还是从网络导入？本机导入的话，改成 `http:/localhost:6806/` 后再试试。

2. 另外也可以测试下下面两个功能是否可用？

     <img width="550" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ec91a6e1-0f68-4f72-84bc-546edf90205b">

**Comment by wangjinbaor** [comment]
![tmp9D79](https://github.com/Kenshin/simpread/assets/58154171/f89210ba-5167-46e1-a8c1-e5604754387e)

![tmpA6E0](https://github.com/Kenshin/simpread/assets/58154171/4cbea79b-ffa8-48f5-9966-6dc6f965afc2)
授权跟查看已授权的笔记本可用
![image](https://github.com/Kenshin/simpread/assets/58154171/4a34b476-e523-4e1e-b532-f68e4527bdb0)
api也填写了

最后依然有问题
![image](https://github.com/Kenshin/simpread/assets/58154171/7956952f-c8cc-4d70-8c1b-573c648b97d8)
思源版本
![image](https://github.com/Kenshin/simpread/assets/58154171/4115f198-39e2-4cff-af1d-e8cd91c2a6e1)

**Comment by Kenshin** [comment]
emmm 有点意思...

你打开 DevTools 看下报错内容是什么。

**Comment by wangjinbaor** [comment]
是这个吗？
![image](https://github.com/Kenshin/simpread/assets/58154171/1827c35b-b779-4fb5-ba34-2b420e1852d4)


![image](https://github.com/Kenshin/simpread/assets/58154171/0e692b89-6b70-4020-bd31-16c7571d47b5)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6279#issuecomment-1913107228

是的，但报错很奇怪... 看起来还是你自身设置的问题，我已经让其他用户帮忙测试了。

试试 https://sspai.com/post/69972 能否导入成功？

另外 `http:/localhost:6806/` 并没有改成功，仍然是 `http:/127.0.0.1:6806/` 修改后别忘记保存。

**Comment by wangjinbaor** [comment]
https://sspai.com/post/69972 相同的报错
使用 http:/localhost:6806/ 也一样
![image](https://github.com/Kenshin/simpread/assets/58154171/69ce5543-bb72-42d9-b221-20e1d3baaf86)
会不会是思源笔记的问题，我搜到了其他issues #5965
我好像也是更新后就不行了

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6279#issuecomment-1913117288

（看起来）这个错误 401 鉴权的问题。

> 会不会是思源笔记的问题，我搜到了其他issues https://github.com/Kenshin/simpread/issues/5965

不确定，不过思源确实也挺不稳定的。但我用这边测试是没问题的，同样的版本 😂 

PS：这个 Issues 是 9月份的了，你更新后一直没用过？

**Comment by wangjinbaor** [comment]
好久没用过了，不过之前（不能确定多久之前了）用过一次没法用，然后就一直没用过了
我看看能不能找到 #5965 中可以用的版本再试一下

**Comment by wangjinbaor** [comment]
> 不确定，不过思源确实也挺不稳定的。但我用这边测试是没问题的，同样的版本 😂

这就不知道出什么问题了

**Comment by wangjinbaor** [comment]
> 我看看能不能找到 #5965 中可以用的版本再试一下

#5965 中的2.10.5版本是可以用的

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/5965 中的2.10.5版本是可以用的

好吧 😂 因为我没法复现，所以…

**Comment by wangjinbaor** [comment]
行嘞，那就先不用图床功能了，佛系哈哈😄

**Comment by Kenshin** [comment]
思源笔记可以将网络图片一键转换为本地图片的功能，只是多了一步「手动」😂

你可以问问其他思源笔记的用户看是否有这个情况吗？

PS：确实有几个用户提过这个情况，但相对思源笔记的用户数相当于「个例」

**Comment by Kenshin** [comment]
各位，不知道是否是下面的问题造成的，你们可以手动选择任一个笔记本后再测试。

<img width="556" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fb80f505-af42-4dc5-acfc-b273eb2b4023">

**Comment by wangjinbaor** [comment]
![image](https://github.com/Kenshin/simpread/assets/58154171/05acd40d-fc7a-4861-b10b-431dc7c57bf3)
昨天晚上重装了简悦，再次使用导入，图床依然不可用，基本上是排除了简悦的问题

**Comment by Kenshin** [comment]
@wangjinbaor 

😂

**Comment by ASM-YUAN** [comment]
思源v2.12.6，我也出现了这种问题，关掉图床可以保存，暂时关掉图床用了

**Comment by Kenshin** [comment]
嗨，各位。

看下 https://github.com/Kenshin/simpread/issues/6311#issuecomment-1956766304 提到的解决方案

**Comment by wangjinbaor** [comment]
根据 #6311 的解决方案，现在没问题了，谢谢大佬们

**Comment by Kenshin** [comment]
@wangjinbaor 

竟然真的是这个问题… 😂

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">
安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
