### ISSUE TITLE
导入github的时候未对非法字符剔除

### ISSUE THREAD

**Issue by epodak** [Kenshin/simpread#6280]
### 描述这个错误

gh提交时候未对标题的非法字符进行检测

### 复现步骤

https://getquicker.net/Sharedaction?code=e73058da-d089-4273-d5bd-08d82dd7cfe2
在这个网址上 gh 提交就会导致我无法pull到本地

### 操作系统

win

### 浏览器

chrome

### 发生问题的网址

https://getquicker.net/Sharedaction?code=e73058da-d089-4273-d5bd-08d82dd7cfe2

**Comment by Kenshin** [comment]
解决方案 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U
