### ISSUE TITLE
知乎公式渲染错误

### ISSUE THREAD

**Issue by xiaoxuan-yu** [Kenshin/simpread#6281]
### 描述这个错误

使用SimpRead的阅读模式阅览https://zhuanlan.zhihu.com/p/672941483 时，公式渲染出现错误
![image](https://github.com/Kenshin/simpread/assets/55308316/da78b91c-82aa-4275-91e9-fadc93ba2d37)

### 复现步骤

1. 安装 SimpRead 和知乎阅读辅助增强选项
2. 打开网页并上下滑动保证公式加载完成
3. 进入阅读模式

### 操作系统

Windows 11

### 浏览器

Microsoft Edge 120.0.2210.144 ARM64

### 发生问题的网址

https://zhuanlan.zhihu.com/p/67294148

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/2861

<img width="1333" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ff2167b4-9a84-457f-842f-fa914b771c45">
