### ISSUE TITLE
保存到noton时显示稍后重试

### ISSUE THREAD

**Issue by xchyyb** [Kenshin/simpread#6282]
### 描述这个错误

最近保存网页到notion时在显示上传到图床完成后就会显示稍后重试
![image](https://github.com/Kenshin/simpread/assets/78303344/e5fb6308-a69e-40ae-8be6-bafcd5ad69a8)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/78303344/39c21b68-33af-4bcf-8630-f4b0e8d07dc4)

### 操作系统

windows11

### 浏览器

谷歌浏览器

### 发生问题的网址

http://zhihu.geoscene.cn/article/4184

**Comment by Kenshin** [comment]
我测试了下，没有任何问题。

1. 其他页面是否存在同样问题？e.g. https://sspai.com/post/69972
2. 把 cl 图床关闭后是否可以导入成功？

**Comment by xchyyb** [comment]
所有页面都存在这个问题；
关闭图床后仍不能成功导入。

**Comment by Kenshin** [comment]
那这个问题跟 cl 网盘无关... 而是你的配置问题...

看下 https://www.yuque.com/kenshin/simpread/wwk65u 尤其是授权相关的解决方案。
