### ISSUE TITLE
导出epub 失敗

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#6284]
### 描述这个错误

目前继[#6176](https://github.com/Kenshin/simpread/issues/6176)反映PDF高级导出失败后，今天试试epub导出，又是失败😔

### 复现步骤

<img width="584" alt="Screenshot 2024-02-01 at 19 32 03" src="https://github.com/Kenshin/simpread/assets/87223257/35fa3544-cd1a-42b4-a251-e57b82e86801">

### 操作系统

macOS 14.2.1

### 浏览器

Microsoft Edge Version 122.0.2365.3 (Official build) Dev(arm64)

### 发生问题的网址

https://utgd.net/article/20513

**Comment by felix2049lou** [comment]
抱歉，找到原因了，因增强导出的自定义地址最后一个位置了一个空格，删了就正常。
<img width="236" alt="Screenshot 2024-02-01 at 20 46 07" src="https://github.com/Kenshin/simpread/assets/87223257/d76cbe35-4b5a-47e9-b18f-c5703833f351">

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 Issues 了。
