### ISSUE TITLE
尝试obsidian极速版配置方案的过程中，无法将全文以及标注导入obsidian，一直显示保存失败

### ISSUE THREAD

**Issue by XHHHX** [Kenshin/simpread#6285]
### 描述这个错误

您好，我在尝试obsidian极速版配置方案的过程中，每一步都按照教程来，包括最后测试的网页也没有问题，就是将网页导入obsidian出现问题，将全文导入obsidian和将标注导入obsidian两个选项都有问题，都显示保存失败

### 复现步骤

最后打开的测试网页截图，其已存在的标注正常显示，按道理讲应该是配置成功，如下图
![image](https://github.com/Kenshin/simpread/assets/110332199/dbe4d6f8-160b-41c1-977c-d16bddc30f1e)
但是就是在导入obsidian时，一直出现保存失败的情况，由于我不是计算机相关专业，所以不懂针对错误进行网页检查选项显示的内容，只能尽量截取相关内容
![image](https://github.com/Kenshin/simpread/assets/110332199/ca768527-ebe4-4345-83aa-79b95e02830f)
![image](https://github.com/Kenshin/simpread/assets/110332199/8428ef43-e3a7-49b1-9b69-397507c66643)

### 操作系统

win64

### 浏览器

edge

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
极速版使用了 Local REST API 方案，所以建议把与 Local REST API 相关的功能都截图给我看下。

**Comment by XHHHX** [comment]
> 极速版使用了 Local REST API 方案，所以建议把与 Local REST API 相关的功能都截图给我看下。

![image](https://github.com/Kenshin/simpread/assets/110332199/824ce091-c45a-49e4-b5dc-72c3f2a64d9c)
这是Local REST API 相关功能的截图，您看看有啥问题

**Comment by Kenshin** [comment]
还有简悦这边的设置呢 😂

留意下图的值

<img width="587" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0c1fade5-06ed-4f35-ad2d-1a5bb73c9797">

应该与简悦这边一致

<img width="609" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a7ecc595-f4de-4b6f-bbc3-be6478453fc5">

PS：第一个提示的内容是 `http://localhost:27123`

**Comment by XHHHX** [comment]
按照您的设置，我更改了一下简悦这边的设置，发现还是不行（之前我是上面那行内容，http://localhost:27123没改，现在我改成您说的了，还是不行）
下图是简悦的设置，您看看
![image](https://github.com/Kenshin/simpread/assets/110332199/112f2686-9dc0-43b2-884e-eb5c13fc3e6d)

**Comment by Kenshin** [comment]
emmm

把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6285

然后在这里告诉我，我看下。

**Comment by Kenshin** [comment]
嗨，你发完邮件没有通知我，我今天才留意到... 😂

***

不过，我使用你的配置文件（极速版）完全没有任何问题。

留意下使用步骤：进入阅读模式后，使用快捷键 <kbd>d d</kbd> 加入稍后读，然后再标注，看下是否可以通过成功？

**Comment by XHHHX** [comment]
您好，我按照您说的使用步骤发现还是不行，可以成功加入稍后读，然后进行标注后无法将标注导出到obsidian。
***@***.***\SimpRead
然后我的常规设置的文件夹是这样的，发现无法导出成功，于是我又将这个设置换成我的库名称HHH，如下
我发现还是无法导出，麻烦再您看看到底是哪里出了问题













在 2024-02-27 15:22:19，"Kenshin Wang" ***@***.***> 写道：

嗨，你发完邮件没有通知我，我今天才留意到...

不过，我使用你的配置文件（极速版）完全没有任何问题。

留意下使用步骤：进入阅读模式后，使用快捷键 d d 加入稍后读，然后再标注，看下是否可以通过成功？

**Comment by Kenshin** [comment]
请不要使用 Email 回复，无法看到截图。

另外，按照我给你的判定步骤判定，因为你的配置文件其实是没问题的，所以出问题的可能是 Obsidian 端。

确保你的 Obsidian 只运行一个。

**Comment by XHHHX** [comment]
已解决问题，应该是我之前运行了两个obsidian库导致无法导出成功以及运行一个obsidian库时导出文件夹目录太复杂的原因，十分感谢您的帮助！！！
















在 2024-02-27 22:23:13，"Kenshin Wang" ***@***.***> 写道：

请不要使用 Email 回复，无法看到截图。

另外，按照我给你的判定步骤判定，因为你的配置文件其实是没问题的，所以出问题的可能是 Obsidian 端。

确保你的 Obsidian 只运行一个。

**Comment by Kenshin** [comment]
okay 解决就好。 👍

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by XHHHX** [comment]
感谢解答，已五星好评
















在 2024-02-28 10:52:15，"Kenshin Wang" ***@***.***> 写道：

okay 解决就好。

请帮忙在 Chrome 或 Edge 五星 + 好评，以便让更多人知道

**Comment by Kenshin** [comment]
👍 😄 ❤️
