### ISSUE TITLE
添加稍后阅读有时会自动同步到本地有时不会

### ISSUE THREAD

**Issue by Xiaoqing2265** [Kenshin/simpread#6287]
### 描述这个错误

添加稍后阅读有时会自动同步到本地有时不会

### 复现步骤

1.打开网页
2.点击简悦chrome插件
3.点击 保存到简悦·稍后阅读

### 操作系统

macOS版本14.3 (23D56)

### 浏览器

6.5.3206.59 (Stable channel) (arm64) 

### 发生问题的网址

https://www.ai.pku.edu.cn/info/1088/2295.htm

**Comment by Xiaoqing2265** [comment]
按照官方文档logseq方法配置

**Comment by Kenshin** [comment]
加入稍后读并产生自动化的条件：

**进入阅读模式**并且**使用快捷键 `d d`** 加入稍后才会触发自动化。

**Comment by Xiaoqing2265** [comment]
感恩！之前没有使用dd，也会触发自动同步，平常使用Vimium，需要怎么设置，是不是可以 Assistive Touch设置快捷键。顺便问一下小飞机群怎么进不去，一直提示“抱歉，此群组已无法访问。”是被加入黑名单了吗？

**Comment by Kenshin** [comment]
> 之前没有使用dd，也会触发自动同步

肯定不行的。 😂

> 是不是可以 Assistive Touch设置快捷键

`d d` 本身就是快捷键了，你还要再设置什么？

> 顺便问一下小飞机群怎么进不去，一直提示“抱歉，此群组已无法访问。”是被加入黑名单了吗？

个别用户确实存在这个问题，我也不清楚，如果你没进去的话，肯定不是小黑屋造成的。
