### ISSUE TITLE
简悦插件会导致这个网页无法正常显示

### ISSUE THREAD

**Issue by bothyouandme** [Kenshin/simpread#6288]
### 描述这个错误

在打开特定网站时，如果开启简悦插件，会导致部分内容不显示（不显示形式为：在网页加载时，可以看到正常页容，但网页加载完后，该内容消失）

### 复现步骤

1.开启简悦插件，打开网页，可以看到，只显示了评论区
<img width="907" alt="image" src="https://github.com/Kenshin/simpread/assets/71322561/c92326a7-c5ab-419a-96c7-2dd5148d297f">
2.设置简悦插件可读取或更改网页内容权限为点击该网页时或者通过隐私模式打开(即禁用简悦插件)，可以看到，网页正常显示
<img width="910" alt="image" src="https://github.com/Kenshin/simpread/assets/71322561/978898c9-780d-4786-b06d-08e061f85379">

### 其他相关说明

简悦版本2.2.0

### 操作系统

win11

### 浏览器

chrome 121.0.6167.140

### 发生问题的网址

https://degreesoflewdity.miraheze.org/wiki/Main_Page

**Comment by Kenshin** [comment]
嗨，应该是这个问题造成的，内含解决方案。

https://github.com/Kenshin/simpread/discussions/2347
