### ISSUE TITLE
问一下本地打开的html文件，是不是无法通过dd加入稍后阅读

### ISSUE THREAD

**Issue by Xiaoqing2265** [Kenshin/simpread#6292]
### 描述这个错误

问一下本地打开的html文件，是不是无法通过dd加入稍后阅读

### 复现步骤

1.打开本地html
2.使用简悦阅读
3.使用dd加入稍后阅读，没有响应

### 操作系统

macOS版本14.3.1 (23D60)

### 浏览器

Vivaldi

### 发生问题的网址

本地html文件

**Comment by Kenshin** [comment]
是的，但如果有同步助手的话，可以使用 https://github.com/Kenshin/simpread/discussions/4723 解决。

***

PS：进入除夕还玩电脑？😂

**Comment by Xiaoqing2265** [comment]
非常感恩简悦的作者在除夕还回复，祝您新年吉祥！再进一步补充说明一下：本地有同步助手，本地的html文件是通过word导出，然后用浏览器打开，进入简悦后想通过dd添加到稍后阅读里，然后自动同步到logseq。

**Comment by Kenshin** [comment]
新年快乐 😄

> 本地的html文件是通过word导出，然后用浏览器打开

是的，使用我提供 https://github.com/Kenshin/simpread/issues/6292#issuecomment-1935416295 就能解决，但不是直接在浏览器打开你的本地 HTML，细节看我提供的链接就好。

***

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍

**Comment by Xiaoqing2265** [comment]
抱歉再叨扰一下，按照#4723操作完了，能够正常访问接口，接口返回
{"status":200,"result":[{"url":"https://www.ai.pku.edu.cn/info/1088/2295.htm","title":"古籍智能 第六讲：古籍数字化与汉字编码字符集 - 北京大学人工智能研究院","favicon":"","img":"https://www.ai.pku.edu.cn/__local/D/16/F4/392AFE3FDA17A926290DAB3751C_1573C9F9_12F7B.png","desc":"汉字字形复杂，在计算机内部传输、存储和处理时往往会遇到许多困难，在古籍出版及数字化工作中更需专门加以应对。在字形上，汉字在共时层面的累积数量越来越庞大，其中有相当一部分属于冗余成分，需要加以整理......","create":"2024年02月05日 19:44:08","idx":9,"annotations":[],"tags":[],"note":""},{"annotations":[],"create":"2024年01月26日 20:00:37","desc":"文章浏览阅读328次。此命令的作用是重建 LaunchServices 的数据库，这样重复或无效的项目就会被清理掉了。","favicon":"https://g.csdnimg.cn/static/logo/favicon32.ico","idx":8,"img":"","note":"","tags":["#Mac","#打开方式"],"title":"mac 删除右键菜单中的多余或是无效的打开方式_mac 右键无效路径","url":"https://blog.csdn.net/pilihou/article/details/134057564"}]}

如果要实现：用word写了一篇文章，然后保存成html文件，接下来该如何操作？是需要把word导出的html文件放在稍后阅读output文件？还请您给指导指导，感恩您！

**Comment by Kenshin** [comment]
嗨，抱歉，我之前给错链接了 😂 😂 😂 😂 （我说你问的怎么比较奇怪...

正确的是 https://github.com/Kenshin/simpread/discussions/4625

> 如果用word写了一篇文章，然后保存成html文件，接下来该如何操作

使用我给的正确的链接，这个问题「自动解决」。（也就是使用 Word 导出 HTML 可以直接被简悦识别为阅读模式，进而可以使用稍后读、导出等方案。

如果还是有问题的话，可以发一份 Word 导出的 HTML 上来，我抽时间瞧瞧。
