### ISSUE TITLE
飞书wiki: feishu.cn/wiki和本地html文件 在阅读模式下 图片内容缺失

### ISSUE THREAD

**Issue by Glyco-Protein** [Kenshin/simpread#6293]
### 需要适配的新站

https://zl49so8lbq.feishu.cn/wiki/XaEnw6UxTiztUBkQCm7con3Qnae

就是 开启阅读模式后 图文内容不全

### 有需要请描述这个站的性质

本地html文件,打开阅读模式后,配合使用 导入到 Notion插件的"Cloudinary 图床" 点击 一键导入后,图片在 notion页面里还是 无法正常显示的, 就是 感觉 本地图片没有成功上传进 图床里,咱也不明白,希望大佬看看能否优化,感谢

**Comment by Kenshin** [comment]
你的标题跟内容不符合啊… 😂

> 飞书的适配问题

飞书这类文档类的页面是不可以适配的，比如：微信读书，百度文库等。

> Notion 的问题

本地 HTML 的图片也是本地的吗？如果是的话应该是不行的。

**Comment by Glyco-Protein** [comment]
好滴吧
