### ISSUE TITLE
同步助手报 7026 端口占用

### ISSUE THREAD

**Issue by lsbaoouc** [Kenshin/simpread#6294]
### 描述这个错误

同步助手报7026端口占用，通过#2129进行了设置，并保证后台没有相关进程，点开同步助手，仍然报错。

### 复现步骤

1. 根据#2129将自动启动关闭，设置自启项；
2. 重启后报错，杀掉所有同步助手进程，手动启动同步助手仍旧报错；
3. 由于关闭了“启动后显示主界面”，现在也不能设置同步助手；
4. 删除并重新装了从1.0.2到1.2.0的所有版本，均不能修复。
![image](https://github.com/Kenshin/simpread/assets/109883441/dd5db1b0-d2dc-4b2b-8a1c-8468a21ef768)

### 操作系统

win11

### 浏览器

opera 106.0.4998.70

### 发生问题的网址

无关

**Comment by Kenshin** [comment]
emmm 

试试其他浏览器如 Edge 不要使用 Opera

**Comment by windingblack** [comment]
我也遇到过这个中文提示, 我的情况是由于设置了wsl开机启动, 触发了系统保留端口, 7026并没有被其它程序占用, 而是被保留了。可以通过命令确定是不是这种情况: `netsh int ipv[46] show dynamicport tcp`, [解决方案](https://github.com/docker/for-win/issues/3171#issuecomment-554587817): 执行`netsh int ipv[46] set dynamic tcp start=49152 num=16384`后重启

**Comment by lsbaoouc** [comment]
> emmm
> 
> 试试其他浏览器如 Edge 不要使用 Opera

嗯，应该不是浏览器的问题，之前opera用了有半年了。

**Comment by lsbaoouc** [comment]
> 我也遇到过这个中文提示, 我的情况是由于设置了wsl开机启动, 触发了系统保留端口, 7026并没有被其它程序占用, 而是被保留了。可以通过命令确定是不是这种情况: `netsh int ipv[46] show dynamicport tcp`, [解决方案](https://github.com/docker/for-win/issues/3171#issuecomment-554587817): 执行`netsh int ipv[46] set dynamic tcp start=49152 num=16384`后重启

感谢！确实是因为这个问题。我用了另外的命令解决的：https://superuser.com/questions/1627493/in-windows-10-how-can-we-find-out-which-applications-reserved-tcp-port-ranges-a

1. netsh int ipv4 show excludedportrange protocol=tcp
可以看到7026确实是被保留了。
2. net start winnat
net stop winnat

**Comment by Kenshin** [comment]
Cool 谢谢找到解决方案。

我会把这些放到简悦的 [知识库](https://github.com/Kenshin/simpread/discussions) 里面。

***

我关闭这个 issues 了，各位假期愉快~

**Comment by lsbaoouc** [comment]
> Cool 谢谢找到解决方案。
> 
> 我会把这些放到简悦的 [知识库](https://github.com/Kenshin/simpread/discussions) 里面。
> 
> 我关闭这个 issues 了，各位假期愉快~

感谢好用的软件和及时的反馈，假期愉快！

**Comment by Kenshin** [comment]
谢谢喜欢简悦 👍 假期应该多休息 😄

PS：如果觉得简悦好用的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评 😉 😁 👍
