### ISSUE TITLE
通过egde浏览器打开本地pdf文件，阅读模式无法打开

### ISSUE THREAD

**Issue by maxwell5566** [Kenshin/simpread#6295]
### 请描述你的建议或任何内容

想用simpread来辅助阅读本地的文件，于是想到把文件转换为pdf然后通过edge浏览器simpread插件进入阅读模式辅助阅读添加批注，但是好像这个方式行不通。
请问有没有什么办法或方式，可以实现simpread辅助阅读本地的文件并进行批注呢？

**Comment by Kenshin** [comment]
嗨

简悦无法在 PDF 下使用阅读模式以及标注，你可以使用 PDF 相关 App 进行标注。

简悦可以读取本地 HTML 细节请看 https://github.com/Kenshin/simpread/discussions/4625

**Comment by maxwell5566** [comment]
请问 用那款pdf软件可以把标注导出到obsidian里面 ，谢谢。


> 嗨
> 
> 简悦无法在 PDF 下使用阅读模式以及标注，你可以使用 PDF 相关 App 进行标注。
> 
> 简悦可以读取本地 HTML 细节请看 #4625

**Comment by Kenshin** [comment]
这个我就不知道了，请去 Obsidian 问问。

**Comment by Kenshin** [comment]
不过，我知道 Logseq 应该原生就支持 PDF 标注。
