### ISSUE TITLE
选择标注错位

### ISSUE THREAD

**Issue by windingblack** [Kenshin/simpread#6296]
### 描述这个错误

您好。我是simpread的重度用户, 也是第一波在爱发电上车会员的用户。我惊讶于定价十几米的simpread至今仍在不断迭代更新, 为此十分感谢您的坚持与付出! 
我有一个关于标注的BUG需要您的帮助。这个BUG在每个页面都会出现。且是在进入阅读模式, 并进行几次标注操作才会出现。如下图所示, 当鼠标向下拖动时, 可以正常标注, 但是当鼠标向屏幕边缘移动时会出现过度选择的情况, 会将光标下方的内容也选中
![Animation](https://github.com/Kenshin/simpread/assets/152348204/9efa8170-124e-4d26-9e65-80be99e6095b)

### 复现步骤

在进入阅读模式, 并进行几次标注操作后, 再进行标注时复现

### 操作系统

Windows 10

### 浏览器

Chrome

### 发生问题的网址

任意网址都会出现的bug

**Comment by Kenshin** [comment]
emmm

1. 截图演示时的浏览器分辨率是多少？你可以试试把浏览器缩放调小些。
2. 出问题时应该是存在标注的吧？（截图没法看出来）如果是的话，是因为右侧的标注栏遮挡造成的。

**Comment by windingblack** [comment]
感谢热心反馈。
1. 调整浏览器缩放并未解决问题。我在系统中有调整到150%的缩放。调整到100%后问题消失, 但我不适应100%分辨率: ![image](https://github.com/Kenshin/simpread/assets/152348204/f138c3fd-560a-4a2c-bc15-cf181a502abf) 
2. 出问题时存在标注。鉴于您提到右侧的标注栏遮挡。我开起了[清爽模式](https://simpread.ksria.cn/plugins/details/re3DtF0apc)隐藏侧栏, 问题消失。 但清爽模式同时去掉了标注开关, 我经常需要在网页中复制/搜索文本, 需要通过快捷键切换标注状态, 并通过标注开关确定标注是否开启,  所以这个插件可以提供一个是否隐藏标注开关的选项吗,吗,这也是我在另一个Issue[#6297](https://github.com/Kenshin/simpread/issues/6297)提到的小建议

**Comment by Kenshin** [comment]
emmm

调整分辨率不是解决方案，而是判断你的问题是否是标注栏遮挡造成的。

这个问题可以通过自定义样式解决，今天可能不方便，我先 Mark 下，过两天方便时给你解决方案。

> 我经常需要在网页中复制/搜索文本, 需要通过快捷键切换标注状态, 并通过标注开关确定标注是否开启

有个暂时的临时解决方案，可以使用快捷键 <kbd>m m</kbd> 来开启/关闭标注栏（但没有提示信息）

**Comment by windingblack** [comment]
是的, 不急。感谢热心回复, 祝您新春愉快!

**Comment by Kenshin** [comment]
嗨，我休假回来了 😄

***

我不太好复现你提到的问题，能否录屏时把整个浏览器都录上，仅仅只是一部分的话不好判断。

**Comment by Kenshin** [comment]
我把浏览器缩小到下图所示仍没有复现 😂

<img width="722" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d3c69553-02f7-4ee9-a483-cb4210bbd318">

**Comment by Kenshin** [comment]
或者把你的配置文件发给我，也可能是某些插件造成的。

发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6296

然后在这里通知我~

**Comment by windingblack** [comment]
感谢! 感觉您的版面宽度有点小, 可以把版面宽度调大。然后这个BUG并不是第一次就会出现, 要操作过几遍, 直到操作时标注栏挡住了才会出现。以下是我录制的视频, 简阅内没有任何插件, 操作的过程: 
[2024-02-27 12-24-46.zip](https://github.com/Kenshin/simpread/files/14414362/2024-02-27.12-24-46.zip)

![image](https://github.com/Kenshin/simpread/assets/152348204/5d7663ec-4f82-455f-8fbd-416df9c21761)

**Comment by Kenshin** [comment]
我看到了。 😂

理论上这不算是 Bug 因为标注栏已经遮挡了正文，约等于下面的效果

<img width="744" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f4f116ca-150a-4195-b4ad-6f6f11f0f3d7">

因为你的版面布局确实比较小，所以你可以缩进右侧栏

<img width="320" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/aa15d9d6-47ee-421f-b89c-6413a4408832">

PS：红色是调试效果，可以忽略。

**Comment by windingblack** [comment]
🆗
