### ISSUE TITLE
微博图片清晰度不够

### ISSUE THREAD

**Issue by melodyfung** [Kenshin/simpread#6298]
已关闭

**Comment by Kenshin** [comment]
好久不用微博了，给个链接瞧瞧

**Comment by melodyfung** [comment]
目前应该是没有任何剪藏和阅读类的插件能直接把微博的大图排版并收集，我试了非常多，都是缩略图，只有在微博里@我的印象笔记能收集到，能够方便的收集微博的大图在很多使用场景还满刚需的，但是这款笔记本对于我来说不是很好用
<img width="566" alt="iShot_2024-02-13_18 08 23" src="https://github.com/Kenshin/simpread/assets/101943573/4ed77d1f-f663-4501-9c18-15b94638571f">
<img width="517" alt="iShot_2024-02-13_18 08 44" src="https://github.com/Kenshin/simpread/assets/101943573/db9836cf-01f3-414a-b198-817894b9082e">
<img width="573" alt="iShot_2024-02-13_19 54 35" src="https://github.com/Kenshin/simpread/assets/101943573/0929284f-8f36-44b6-b967-fc5c54f03b23">
印象笔记能出大图排版的效果是这样，评论里@之后就会收集到“微博”这个笔记本中
<img width="1294" alt="iShot_2024-02-13_20 02 57" src="https://github.com/Kenshin/simpread/assets/101943573/a17bc00d-ac9a-46b8-841c-f7d02c17f010">
一般最好的情况都只能到这个清晰度，可能是因为那些图片点开也需要过1秒才能出来清晰的图。抓取资源图片的那类插件是原图但是不够方便。
<img width="853" alt="iShot_2024-02-13_20 09 48" src="https://github.com/Kenshin/simpread/assets/101943573/14cba3d1-c36d-4b73-ac78-5f8c942f14aa">

**Comment by melodyfung** [comment]
而且也是微博的收集，动作-保存到笔记本没有图片，试了notion和onenote
<img width="1023" alt="iShot_2024-02-13_23 51 50" src="https://github.com/Kenshin/simpread/assets/101943573/0cdfd40e-5281-4c90-8888-f3555ee45149">
<img width="731" alt="iShot_2024-02-13_23 53 07" src="https://github.com/Kenshin/simpread/assets/101943573/8073d6bc-cf35-447d-9c65-24849d4d33da">

**Comment by Kenshin** [comment]
所以，你仍没有给我任何可以测试的 URL...

**Comment by melodyfung** [comment]
https://weibo.com/2231624585/O0f3ZerL3

**Comment by Kenshin** [comment]
好，我明天看下回复你。

**Comment by melodyfung** [comment]
看来是我从一开始就误会了，没时间或有什么难处提升这方面的性能是吧，否则谁一开始想到给个链接原来是这个意思呀，还傻傻的贴那么多图，无聊，想测试的话早就随便去测了

**Comment by Kenshin** [comment]
你可以试试 https://github.com/Kenshin/simpread/discussions/3515 应该能解决你的问题。

**Comment by melodyfung** [comment]
还是没有图，过程 [https://share.weiyun.com/tBGGSM3K](url)

**Comment by Kenshin** [comment]
我随便找了个页面 e.g. https://weibo.com/2645269490/O0IO830ji 测试没问题，看下图

<img width="1234" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f24d1c49-f32b-484c-b77a-1346fd635c63">

安装正确后进入阅读模式，看下你的跟下图是否一致

<img width="480" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7afb42a2-acae-4b0f-80d7-de55a9cc42f4">

不过，图片确实不是原图，而是当前图片，这点可能需要优化下。

***

PS：微博比较复杂，所以我才反复跟你说 **请给我出问题的 URL**，简单的说：阅读模式类产品比较复杂（这也是简悦优于其它产品的优势），哪怕是同一个网站但只要不是同一个 URL 阅读模式的效果可能就不一样。

而且页面结构一旦改变（用户感知不到），就有可能适配错误。

**Comment by Kenshin** [comment]
更新下：

刚才提到的获取图片原图已经更新，请重新安装 https://simpread.ksria.cn/sites/details/NWcdj6FMDU 然后重启浏览器即可。

**Comment by melodyfung** [comment]
谢谢更新！图片非常清楚了，继续进行下一步的时候图片还是都红叉了，试了导出到notion和onenote，在简悦悦读模式下已经有图，这时右键加入到稍后读也是红叉。还有一个问题自动同步模式下（坚果云），站点集市里安装的站点就会消失显示为一个站点也没安装，阅读模式就又没有图了，所以阅读模式里显示正常是用安装站点解决的。[https://weibo.com/1737588567/O0OZzipri](url)

**Comment by melodyfung** [comment]
<img width="390" alt="iShot_2024-02-16_14 22 08" src="https://github.com/Kenshin/simpread/assets/101943573/95322666-cc6b-44f7-b27f-fe2c10667afe">
<img width="400" alt="iShot_2024-02-16_14 22 45" src="https://github.com/Kenshin/simpread/assets/101943573/415f614a-5117-4f87-a679-682362b1ae97">
<img width="343" alt="iShot_2024-02-16_14 22 36" src="https://github.com/Kenshin/simpread/assets/101943573/2e02031f-c5d3-4ece-89d4-e01d1f697262">

**Comment by Kenshin** [comment]
> 图片还是都红叉了

**如果你是说 加入到稍后读后，在稍后读查看无法显示图片的话** 这算是正常情况，微博的图片都有防盗链的功能，解决方案继续看。

根据你（并不完整的）上下文，你应该使用了同步助手的自动同步功能，所以要解决图片无法显示的问题需要使用 [本地快照方案](https://www.yuque.com/kenshin/simpread/wkswh7)

如果你没有太多稍后读（也就是新用户）的话，建议直接使用 [配置库](https://www.yuque.com/kenshin/simpread/any457) 方案。

> 站点集市里安装的站点就会消失

你需要使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 方式来安装适配站点，所以（如果条件符合）的话，建议上面的配置库方案。

**Comment by melodyfung** [comment]
站点也已经可以安装成功了，按照给出的解决方法，一度还是无法安装站点，这时把坚果云退出，又重复解决办法就可以安装成功了，不过也许是第一次尝试解决的时候细节没有做对，比如同步助手必须先于坚果云打开，开启关闭自动同步和点按覆盖到本地按钮时的顺序细节等等。

**Comment by melodyfung** [comment]
是有特殊处理所以几乎想微博实现output很难，这里的解决办法不知为何还是失败
自动化配置的是“稍后读自动输出离线html”，也试过普通html的选项；
检查了稍后读页面设置“优先加载本地已存在的html也成功勾选生效了；
试了两篇少数派的，一篇微信，和一篇微博；
微信文章还是会显示“请稍等片刻”是正常的吗，倒是有图也有local的标。
<img width="1110" alt="iShot_2024-02-19_06 46 13" src="https://github.com/Kenshin/simpread/assets/101943573/f99da2da-4299-4104-983f-428d3fc917fa">

<img width="1002" alt="iShot_2024-02-19_06 46 27" src="https://github.com/Kenshin/simpread/assets/101943573/daa31876-3a20-465f-b88d-b6d58afd8abc">
<img width="1103" alt="iShot_2024-02-19_06 47 06" src="https://github.com/Kenshin/simpread/assets/101943573/348a318e-25f8-42e3-b5cb-0d08155b4d38">
<img width="986" alt="iShot_2024-02-19_06 47 20" src="https://github.com/Kenshin/simpread/assets/101943573/b6fc67fd-20d6-4d13-9bdc-d18271e7eaf6">

**Comment by melodyfung** [comment]
![QQ20240219-071709](https://github.com/Kenshin/simpread/assets/101943573/c010aa50-22e2-4f07-b286-0b8ea3716c49)

**Comment by melodyfung** [comment]
不太明白“稍后读-自动导出html”或者“配置快照方案”对于微博图片无法output问题的解决点在哪里，
是不是首先应该检查简悦阅读页面-动作-导出html/离线html/markdown/离线markdown 这些操作，如果这些导出操作中，显示保存或转换成功时，打开导出的html或markdown文件，是无法显示的话，那就是解决不了。
这时配置坚果云同步和自动化其实不是说处理图片问题的，只是在导出为html能解决图片问题时，简化了到稍后读的流程外加方便从稍后读保存到onenote，因为直接从简悦阅读页面剪藏到onenote图片肯定是不行的···

**Comment by melodyfung** [comment]
https://zhuanlan.zhihu.com/p/549453714  --简悦插件 · 将阅读模式的图片转换为你设定的图床后自动导入到你需要的生产力工具。
参考以上教程安装了图床插件，终于把微博文字+图片成功收藏到onenote··🥳picgo配置了github图床，简悦图床插件设置图床选项onenote
<img width="429" alt="iShot_2024-02-22_07 31 42" src="https://github.com/Kenshin/simpread/assets/101943573/e6af714f-4c21-42cf-a222-b59aad42f35f">

**Comment by Kenshin** [comment]
谢谢知乎教程，等我回去后可以申请转载下。

**Comment by melodyfung** [comment]
好哒✌️🎉

**Comment by Kenshin** [comment]
哈，我回来了 😂 然后 😷 了 😂

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
