### ISSUE TITLE
阅读英文网页的时候，单引号、双引号显示不像常见英文字符 ' ”。

### ISSUE THREAD

**Issue by Lingo2018** [Kenshin/simpread#6299]
### 描述这个错误

在这个网站https://backlinko.com/google-ranking-factors 使用aa进入阅读模式，系统默认字体下，英文的单引号和双引号间隔很奇怪。
![image](https://github.com/Kenshin/simpread/assets/39526933/18259c56-7e8d-426e-a8ac-c13b608ca605)

### 复现步骤

1. 访问https://backlinko.com/google-ranking-factors
2. AA进入阅读模式
3. 查看带有单引号、双引号的字符。

### 其他相关说明

希望可以有个这种符号批量替换的功能，因为发现英文网站用这种符号的还是挺多的，但是除非特殊字体，要不然看起来比较难受。

### 操作系统

Win10

### 浏览器

Chrome Version 120.0.6099.224 (Official Build) (64-bit)

### 发生问题的网址

https://backlinko.com/google-ranking-factors

**Comment by Kenshin** [comment]
你需要安装 https://simpread.ksria.cn/plugins/details/VGUmFrRs2b （ 群里面告诉你错了 😂

安装后效果如下

<img width="615" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/442e87fc-a50b-45b7-919c-8af1465e1509">
