### ISSUE TITLE
微信公众平台下的页面无法使用阅读模式

### ISSUE THREAD

**Issue by luchenqun** [Kenshin/simpread#63]
http://mp.weixin.qq.com/debug/wxadoc/introduction/

**Comment by Kenshin** [comment]
@luchenqun 

`微信公众平台`的后台暂时无法解析，原因以及解决办法请看 https://github.com/Kenshin/simpread/issues/62

造成的原因：
`微信公众平台`的后台与公众号的 url 结构一致，所以适配列表包含了公众号，却没有注意到微信公众平台的后台。

**Comment by izhangzhihao** [comment]
http://www.infoq.com/cn/news/15
InfoQ也无法解析

**Comment by Kenshin** [comment]
@izhangzhihao 

仅是 infoq 的几个别页面无法解析。

很显然 http://www.infoq.com/cn/news/15 的页面结构与简悦可以识别的 URL，如：
http://www.infoq.com/cn/news/2017/08/Memsniff-Memcached
不一致造成的。

你可以把这个 URL 或 `news.infoq.com` 加入到排除列表中。 

@luchenqun 
我把这个 issues 的 title 改成 `微信公众平台` 页面无法解析。

**Comment by izhangzhihao** [comment]
@Kenshin 其实当简悦意识到当前页面无法使用阅读模式的时候就不作任何处理就可以绕开这个问题了吧

**Comment by Kenshin** [comment]
@izhangzhihao 
hmm  是个办法，可以加个 `当阅读模式解析失败后，是否自动退出`  的选项。
否则解析失败后，直接退出感觉比较突兀。

**Comment by luchenqun** [comment]
我觉得无法解析之后，提示之后过一段时间比如3秒自动退出，当然，这个时间如果能够自己设置是比较好的。

**Comment by Kenshin** [comment]
@luchenqun 
好想法，延时的确有必要，这样感觉不突兀！
但似乎没必要让用户选择时间，因为这不是一个主要操作。

同时也会加入我说的 `当阅读模式解析失败后，是否自动退出` 这样更直观。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> `匹配失败后，自动退出阅读模式`

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update

**Comment by Kenshin** [comment]
![Weixin](https://github.com/Kenshin/simpread/assets/81074/c7995832-3139-43fe-bfe3-0b88f6cfbd83)

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 发布了。

***

除此之外，此插件还包括如下优化和功能：

### 优化内容

- 大片空白的问题

- 个别图片变得非常巨大的问题

- 个别页面无法成功获取正文的问题

- 小红书样式无法使用阅读模式的问题

- 优化公众号公式

- 去除多余空白行的问题

### 功能

- 优化类似小红书布局的页面（默认开启）

- [强制模式](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6736529)（如果经常查看一些界面比较花哨的公众号，请开启此选项）

- [显示公众号作者等信息](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6849468)

- [去除多余空白行](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-6850107)

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

### 🎯 2.0 版宗旨

为了让阅读更加流畅，同时方便导出到其它生产力工具，让你的阅读与工作完美结合！

### 🎉 庆祝时刻

公众号辅助增强插件安装量突破 15K！感谢每一位用户的支持，让我们一起继续探索更多精彩功能！🚀 🎯

> 除此之外，2.0.0 版还包括如下优化和功能：

### 💡 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` [可识别 翻页与目录](https://github.com/Kenshin/simpread/discussions/5851#discussioncomment-10914017)

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
