### ISSUE TITLE
隐藏元素能够把简悦本身的选项隐藏

### ISSUE THREAD

**Issue by Kisunley** [Kenshin/simpread#630]
选择隐藏元素，点击完成后，想导出pdf，结果点击右边选项，然后选项也被隐藏了。

**Comment by Kenshin** [comment]
因为没有做判断，毕竟误触的可能性很低。

我先提 Bug

**Comment by Kisunley** [comment]
不是，不是误触的问题。不知道在隐藏一些元素后，还能不能进行导出等其他操作？如果可以的话是需要点击其他操作的，我就是这么想着去点击导出，然后连导出选项也隐藏了。

Kenshin Wang <notifications@github.com> 于2019年12月28日周六 上午8:18写道：

**Comment by Kenshin** [comment]
可以在 http://ksria.com/simpread/docs/#/站点管理器 把这个误适配的规则删除。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 新的方案：只能在正文中进行删除操作。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
