### ISSUE TITLE
阅读某英文网址时候引用内容没有显示在阅读模式

### ISSUE THREAD

**Issue by Lingo2018** [Kenshin/simpread#6300]
### 描述这个错误

https://backlinko.com/google-ranking-factors
这个网址使用aa进入阅读模式
在第31条有一个话语引用的模块，这个在阅读模式下无法显示文字内容
![image](https://github.com/Kenshin/simpread/assets/39526933/e3cf9d52-9aff-4033-9e52-d88f63b4620b)
![image](https://github.com/Kenshin/simpread/assets/39526933/53ad61a8-79e2-4ae9-94a0-a5b30291db65)

### 复现步骤

1. 访问https://backlinko.com/google-ranking-factors
2. 使用AA进入阅读模式
3. 找到第31条内容，其中正常有一个引用模块，有文字内容，但是在阅读模式下无法显示
![image](https://github.com/Kenshin/simpread/assets/39526933/e3cf9d52-9aff-4033-9e52-d88f63b4620b)
![image](https://github.com/Kenshin/simpread/assets/39526933/53ad61a8-79e2-4ae9-94a0-a5b30291db65)

### 操作系统

Win10

### 浏览器

Chrome Version 120.0.6099.224 (Official Build) (64-bit)

### 发生问题的网址

https://backlinko.com/google-ranking-factors

**Comment by Kenshin** [comment]
源页面的结构比较特别，并且这个站没有适配造成的，除非适配它，否则确实有点问题。

可以使用下图的方式手动生成阅读

<img width="800" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b87d4cad-cc94-4d0c-93e2-f4b4cba6ba4e">

但效果也不太完美，原因上面说了。😂

<img width="678" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7c2ad0dc-b186-492c-b279-3d0fd4396255">
