### ISSUE TITLE
将网页导出EPUB时图片缺失，并且表格错误

### ISSUE THREAD

**Issue by cyddgh** [Kenshin/simpread#6301]
### 描述这个错误

WIndows10，Edge，简悦高级用户，在将网页保存成epub时，Epub中没有嵌入图片，另外表格也不能渲染正确。
例如页面：https://bsapubs.onlinelibrary.wiley.com/doi/10.1002/ajb2.16280?af=R
另外此页面也有问题（可能需要访问权，但说明不是个例）： https://onlinelibrary.wiley.com/doi/full/10.1111/plb.13626?saml_referrer

### 复现步骤

1. 进入简悦阅读模式
2. 导出EPUB
3. EPUB中无图片，表格渲染错误

![image](https://github.com/Kenshin/simpread/assets/10444611/0c53b14b-9b80-47a9-9ad3-3c617f0ad08b)

![ba4dd2a38d0e352a92cf280d0944e2b](https://github.com/Kenshin/simpread/assets/10444611/c40c20fa-e332-4535-99b5-2b4f7724e697)

![image](https://github.com/Kenshin/simpread/assets/10444611/acaff3ba-98c2-4524-977a-afd36343fb72)

### 其他相关说明

另外，能否针对学术期刊出一个适配，让标题呈现论文的题目，而不是期刊名，并且摘要不要缩略而是全文。

![1ca9647057bda9c0b87596a03e73e26](https://github.com/Kenshin/simpread/assets/10444611/e439e40d-3cc1-4ae5-868f-0ecf9bb0f342)

### 操作系统

WIndows 10

### 浏览器

Microsoft Edge 版本 121.0.2277.112 (正式版本) (64 位)

### 发生问题的网址

https://bsapubs.onlinelibrary.wiley.com/doi/10.1002/ajb2.16280?af=R

**Comment by Kenshin** [comment]
嗨

> Epub 问题

我使用 Epub 高级打印方案（同步助手）发现确实无法显示图片，可能是导出 Epub 触发了该网站的「图片防盗链」（或类似）机制造成的。

这（算是）正常的情况，因为个别网页会有防盗链的机制，因此简悦被误伤。

所以，我改用了 [PDF 高级打印方案](https://github.com/Kenshin/simpread/discussions/3887) 发现是可以正常导出的。

[American Journal of Botany.pdf](https://github.com/Kenshin/simpread/files/14278520/American.Journal.of.Botany.pdf)

如果非要使用 Epub，有很多 PDF → Epub 的方案，虽然多了一步，但好在这种情况仅仅只是个例。

> 能否针对学术期刊出一个适配，让标题呈现论文的题目，而不是期刊名，并且摘要不要缩略而是全文。

简悦专门适配了很多期刊网站 https://github.com/Kenshin/simpread/discussions/2103 但毕竟杯水车薪，所以你可以提交一些你认为大致类的期刊。

如果想要修改标题或阅读模式的任意内容，可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 也可以试试 https://github.com/Kenshin/simpread/discussions/3340 提到的几种方案。

> 表格问题

PDF 应该没问题，Epub 的话，我不确定是否有问题（跟你的截图不太一样）

<img width="638" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c155892a-d40e-43f0-b614-47210d9b0b4b">

我也把 Epub 发上来了，你可以看下。

[American Journal of Botany.AmericanJournalofBotany.epub.zip](https://github.com/Kenshin/simpread/files/14278571/American.Journal.of.Botany.AmericanJournalofBotany.epub.zip)

**Comment by cyddgh** [comment]
如果PDF转EPUB，我就直接下载论文PDF转换即。我目前是用离线HTML，然后pandoc转epub，这样能解决图片问题。
表格那个是在另一个网页中发现的，但这两个页面都出现这样的问题。
学术期刊页面挺多，我这也很难列举。
谢谢关注。
![image](https://github.com/Kenshin/simpread/assets/10444611/7489f1a6-17d4-4258-af00-2178f06aa31b)

**Comment by Kenshin** [comment]
> 我目前是用离线HTML，然后pandoc转epub，这样能解决图片问题

ok

> 表格那个是在另一个网页中发现的，但这两个页面都出现这样的问题。

表格的话，你试试导出 Markdown 看是否有问题，或者你直接导出 Epub 看是否有问题。

如果都没有问题的话，问题就出现在你手动使用 离线 HTML → pandoc → Epub 造成的。

我想想有没有什么其它解决方案。

> 学术期刊

如果我没有目标参考的话，那就没办法了，只有 URL 参考我才能适配它们。
