### ISSUE TITLE
使用dd加入稍后阅读的本地html无法再次编辑

### ISSUE THREAD

**Issue by Xiaoqing2265** [Kenshin/simpread#6302]
### 描述这个错误

在没有加入稍后阅读之前可以通过Live Editor来编辑，使用dd加入稍后阅读的本地html是不是就无法再次编辑？

### 复现步骤

1.打开网页
2.使用简悦阅读
3.使用Live Editor编辑
4.使用dd加入稍后阅读
5.打开稍后阅读之后发现有地方还需要修改编辑。

### 操作系统

macOS 14.3.1 (23D60)

### 浏览器

Vivaldi 6.5.3206.63 (Stable channel) (arm64) 

### 发生问题的网址

任意网页

**Comment by Kenshin** [comment]
可以的，如果你使用了同步助手功能，可以利用 [此功能](https://github.com/Kenshin/simpread/discussions/3864) 实现，简单的说，打开 http://localhost:7026/unread/ 然后选择 **编辑标注** 即可。

**Comment by Xiaoqing2265** [comment]
感恩🥹太棒了！

**Comment by Kenshin** [comment]
小事情，我关闭这个 Issues 了，假期愉快~

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
