### ISSUE TITLE
使用极速版同步标注到obsidian之后，在ob里添加标签无效。不能索引也不能显示在标签列表

### ISSUE THREAD

**Issue by god-hu** [Kenshin/simpread#6303]
### 描述这个错误

极速版，使用官方同步模板，同步标注到obsidian之后，在ob里添加标签，正常显示标签样式。但是点击该标签不能索引到相关文章。并且添加的标签也不能显示在标签列表里，应该是标签无效。而在自己新建的文章里，添加标签后自动显示到标签列表。说明同步到ob的标注笔记，标签没有生效。

请检查是否也存在同样问题？应该如何解决？

### 复现步骤

![2024-02-17_165529](https://github.com/Kenshin/simpread/assets/58676167/11d89e5c-2954-48a7-a55c-ab6fd24497e1)

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://www.digitaling.com/articles/1001643.html

**Comment by Kenshin** [comment]
你需要搜索的是 `tag:#品牌`

**Comment by god-hu** [comment]
刚自己找到问题了。我把SimpRead文件夹在ob设置里忽略了。谢谢回复。这个可以关闭了

**Comment by Kenshin** [comment]
okay 解决就好，我关闭这个 Issues 了。
