### ISSUE TITLE
`已解决`   网站 导出 `pdf` `图片`不显示问题

### ISSUE THREAD

**Issue by robin758** [Kenshin/simpread#6305]
## 环境

- Edge, 最新
- SimpRead 最新, 高级版, 无任何插件
- 阅读助手 最新

## 阅读助手导出本地: `导出 pdf 图片不显示` Bug

- 演示网站: <https://github.com/lxgw/LxgwWenKai>

- 模式: 阅读模式

- **如图所示**:

![image](https://github.com/Kenshin/simpread/assets/83524955/7205f414-6eb2-4568-8c80-e4086213ab82)
![image](https://github.com/Kenshin/simpread/assets/83524955/cd4f7471-078b-438b-a52a-95136c39732e)

### 复现步骤

- 进入阅读模式, 等待加载完成, 导出 pdf
![image](https://github.com/Kenshin/simpread/assets/83524955/264a42ef-c666-41b0-8ed4-7635789fe2bd)

- 本地查看导出内容对照原内容
![image](https://github.com/Kenshin/simpread/assets/83524955/06176343-3fcc-448d-90b8-6cbac43a471d)

### 操作系统

Windows 10 Home

### 浏览器

Edge 版本 121.0.2277.112 (正式版本) (64 位)

### 发生问题的网址

https://github.com/lxgw/LxgwWenKai

**Comment by robin758** [comment]
# 更新

### **已经使用 同步助手 配合 wkhtmltox 高级导出解决**

### 留给可能有相似问题的人的 tips：

1. 事先打开简悦和简约同步助手的导出 pdf  功能（略）

3. 下载简悦 pdf 插件，wkhtmltox 解压放到指定文件架（不用下载安装版）
![image](https://github.com/Kenshin/simpread/assets/83524955/219851c5-ba36-4d34-9c77-08a6b3389629)
![image](https://github.com/Kenshin/simpread/assets/83524955/b81d7d75-08bd-4c98-9f99-df2db64ebb78)

4. 配置插件
**注意一定要注意图三的 wkhtmltox 目录设置，否则无法导出**
![image](https://github.com/Kenshin/simpread/assets/83524955/5cc596d9-85db-484d-83ff-ed447cb8c549)
![image](https://github.com/Kenshin/simpread/assets/83524955/1b448a44-058c-459e-905f-04b08e0bb1ac)
![image](https://github.com/Kenshin/simpread/assets/83524955/b19489aa-3ed1-4df7-bf26-1af6e2f97e3a)

5. Done！`效果对比`
![image](https://github.com/Kenshin/simpread/assets/83524955/b4677fe9-e1d8-479a-8de2-869f89256fa2)

![image](https://github.com/Kenshin/simpread/assets/83524955/2899f7a8-2a07-4b43-95b4-bb6c098821db)

**Comment by Kenshin** [comment]
哈，恭喜自救成功。 👍

简悦的 PDF 高级版方案确实可以覆盖大部分对 PDF 有需求的用户。

我关闭这个 Issues 了。
