### ISSUE TITLE
字体大小能否在扩大几倍，调整道100%后还是太小

### ISSUE THREAD

**Issue by dandelions** [Kenshin/simpread#6307]
### 请描述你的建议或任何内容

字体大小能否在扩大几倍，调整道100%后还是太小

**Comment by Kenshin** [comment]
1. 是每个网页都有问题？还是某个？最好截图给我看下。
2. 也可以试试在隐私模式下仅启用简悦，排除其他扩展的干扰。（因为很少有用户觉得字体比较小）
3. 可以通过 自定义样式 更改。

关于自定义样式可以有很多调整方案，细节 https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Atheme

**Comment by dandelions** [comment]
![Screenshot_20240220_215000](https://github.com/Kenshin/simpread/assets/5170835/0c024e59-eaf4-4cc1-af97-eeba87488543)
手机用的狐猴，网页字体本身有点小

**Comment by Kenshin** [comment]
手机端暂时无法更改字体，但可以通过自定义样式解决，也可以使用我之前提到的链接中的方式解决。
