### ISSUE TITLE
关于 webdav 的完全开放

### ISSUE THREAD

**Issue by robin758** [Kenshin/simpread#6308]
### 请描述你的建议或任何内容

> 先叠甲：小白，不懂编程😂
>因为考虑到 teracloud infinicloud 的 webdav 更有优势，阿里云盘也开放了 api 的缘故
> 仅仅是个建议…
> 如下

## 能否开通 webdav 的登录 api 和 webdav 开放平台的 api？

- 目前**简悦登录**的 api 接口和**开放平台**的 api 似乎只有`坚果云`和 `dropbox`可以使用
- 开放平台的 api 如果也可以用其他 webdav 就好了
- 而其他的 webdav 服务只能用于阅读模式下在线导出

**Comment by robin758** [comment]
> 嗨，API 暂时不考虑，甚至于 API 可能会大规模重构。
> 
> 备注：即便重构也不会影响用户使用，即：从用户视角是感知不到 API 重构的。

是的，😂简悦是完全不需要这些`反向的 api`(大部分用户用不到), 因为简悦的工作流应该是: `阅读 --> 批注 --> 利用 api 导出到本地或者第三方云端`.

> 所以我关闭了 issue, 哈哈. 感谢回复😁

**Comment by Kenshin** [comment]
哈，没「疑问」就好。😉
