### ISSUE TITLE
共通页面无法设置同步助手

### ISSUE THREAD

**Issue by jiuxi521** [Kenshin/simpread#6309]
### 描述这个错误

共通页面无法设置同步助手，不显示设置项

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/59546984/694c812f-f495-455c-a3e6-5daaf2b3004b)

### 操作系统

win10

### 浏览器

版本 121.0.6167.140（正式版本） （64 位）

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
因为你用了简易模式，页面左下角修改。

再调整为简易模式后会有提示…
