### ISSUE TITLE
网页有图片时使用思源笔记插件导出失败

### ISSUE THREAD

**Issue by Zonezzc** [Kenshin/simpread#6311]
### 描述这个错误

<img width="1512" alt="image" src="https://github.com/Kenshin/simpread/assets/142784058/e0cb9abb-de65-46fc-93c1-9320021447ab">
<img width="807" alt="image" src="https://github.com/Kenshin/simpread/assets/142784058/441c46ba-2f14-459b-a3ac-8248b9e085c5">

### 复现步骤

1. 打开网页，进入阅读模式
2. 使用思源笔记导出插件进行导出
3. 有图片的网页导出失败，无图片正常

### 操作系统

macOS m1

### 浏览器

Google Chrome 版本 121.0.6167.184（正式版本）(arm64)

### 发生问题的网址

https://sspai.com/post/86538

**Comment by Zonezzc** [comment]
发现这个问题的解决方法可，我之前是可以正常使用的，昨天更新的最新的思源版本 V3.0.0，访问授权码自己掉了，重新设置访问授权码后，插架使用恢复正常
<img width="1280" alt="image" src="https://github.com/Kenshin/simpread/assets/142784058/efc1acd8-6e02-498e-8147-5bef9c67cab6">

**Comment by Kenshin** [comment]
okay 解决就好。

3.0.0 版本可以访问，对吧？我可以告诉其他用户。

**Comment by Zonezzc** [comment]
关键点是『访问授权码不能为空』

**Comment by Kenshin** [comment]
okay 收到

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，重要 **增加了一些方便调试** 的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">
安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591
