### ISSUE TITLE
未找到外部链接的配置

### ISSUE THREAD

**Issue by KeisukeeLee** [Kenshin/simpread#6313]
### 描述这个错误

你好, 感谢这款很好用的simpread插件。[外部链接](https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-2691470), 请问这篇配置中的外部链接的配置在哪里, 我在扩展的选项里、Markdown模板辅助增强插件和Obsidian选项里都未发现

### 复现步骤

因为文档只提供了截图, 未找到外部链接配置项

### 操作系统

Win 10

### 浏览器

Chrome

### 发生问题的网址

undefined

**Comment by Kenshin** [comment]
嗨，我在错峰休假，不太方便回复。

但有这个功能，你需要具体如何使用？

**Comment by KeisukeeLee** [comment]
感谢回复, 节日快乐, 我找不到这张图的配置在哪, ![外部链接](https://user-images.githubusercontent.com/81074/168723984-bde33f72-7359-466d-ac55-2def4553a10b.png)

**Comment by Kenshin** [comment]
嗨，我休假回来了 😄

***

> https://github.com/Kenshin/simpread/issues/6313#issuecomment-1959379152

这个图在选项页 → 服务 → 定制导出

<img width="1732" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8b9f3636-12ae-4a4a-96b1-e5a4446c67cd">

不过，暂时不建议使用外部链接，因为这个功能有点「麻烦」😂

**Comment by windingblack** [comment]
感谢
