### ISSUE TITLE
raycast是否可以支持检索简悦的稍后读

### ISSUE THREAD

**Issue by Xiaoqing2265** [Kenshin/simpread#6317]
### 请描述你的建议或任何内容

以前使用官方提供的Alfred工作流检索简悦稍后阅读的内容，现在换用raycast是否可以适配一版能在raycast中检索。

**Comment by Kenshin** [comment]
其实是支持的，但不知道发布版本后就出现问题了… ﹋o﹋

所以等恢复后我会在这里通知你。

**Comment by Xiaoqing2265** [comment]
太棒了，辛苦了！
