### ISSUE TITLE
导入到Notion，图片异常

### ISSUE THREAD

**Issue by mining-id** [Kenshin/simpread#6318]
### 背景：
安装了导入到Notion插件
<img width="805" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/718d63dc-956d-450c-b565-71e19d54e1b5">
并且配置了Cloudinary 图床

### 问题：
**1. 可以正常导入，但显示错误**
导入这个链接：https://sspai.com/post/71576
导入过程没有提示错误，在Notion查看的时候，图片无法加载
<img width="833" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/511561ad-7066-40af-9489-edd192326464">
但查看原图的时候，可以在标签页中正常显示
<img width="704" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/156cedc8-40c0-49df-ae83-966f97c32db5">

**2. 导入过程提示错误**
导入这个链接：https://weibo.com/1704641891/O1C27rSmZ
提示错误：
<img width="793" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/355fd121-7bb4-4d26-8e36-1e81f159ba0b">

但在Notion中可以正常显示图片
<img width="799" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/b600bf7c-21b5-4f6b-96d3-7322abb96bb7">

但查看原图的时候，显示错误
<img width="750" alt="image" src="https://github.com/Kenshin/simpread/assets/94845005/9cd7c1ce-38cc-4e0b-b719-4337a2a57d21">

### 复现步骤

阅读模式→导入到Notion

### 操作系统

MacOS

### 浏览器

chrome 122.0.6261.57（正式版本） (arm64)

### 发生问题的网址

见问题描述

**Comment by Kenshin** [comment]
嗨，之前错峰休假，昨天刚回来。

关于微博无法导入 Notion 的问题我确认了，是因为微博有防盗链的限制造成的，目前暂时没有太好的解决方案（ 公众号都没有问题 😂

所以我先关闭这个 Issues 了~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
