### ISSUE TITLE
obsidian现在不支持自动同步么？

### ISSUE THREAD

**Issue by jiuxi521** [Kenshin/simpread#6319]
### 描述这个错误

我看了https://www.yuque.com/kenshin/simpread/wq35mh ，高级版配置，应该是支持自动同步的；
但是看了最新版本的说明，好像改成了手动？？

### 复现步骤

obsidian实现自动读取简悦标注

### 操作系统

win10

### 浏览器

谷歌

### 发生问题的网址

暂无

**Comment by jiuxi521** [comment]
将浏览器的标注自动同步到obsidian笔记目录

**Comment by jiuxi521** [comment]
![image](https://github.com/Kenshin/simpread/assets/59546984/1a5eddbd-5b79-4459-84fa-1627bbc85989)

**Comment by jiuxi521** [comment]
上面的图片是简悦的simpread_config.json文件

**Comment by jiuxi521** [comment]
您好，这个同步是浏览器标注后自动同步到obsidian笔记吗？

目前好像是通过**Manual Sync**进行同步的

![image](https://github.com/Kenshin/simpread/assets/59546984/ed7b65a0-5ab9-4d5d-aa25-8f2918626092)

**Comment by Kenshin** [comment]
Manual Sync 是一次性同步全部标注到 Obsidian 

配置好高级版后，在网站标注会自动同步到 Obsidian

**Comment by jiuxi521** [comment]
我现在浏览器标注后，可以保存到本地的output目录，但是无法自动同步到obsidian下的SimpReader目录，有什么好的排查方案么

**Comment by jiuxi521** [comment]
我在obsidian进行标注可以同步到简约的

**Comment by Kenshin** [comment]
排查有点「麻烦」，目前最好的方式是对比配置库，下周等回去后可以通过你的配置文件来验证。

**Comment by jiuxi521** [comment]
好的，您有需要可以随时联系我

**Comment by jiuxi521** [comment]
![image](https://github.com/Kenshin/simpread/assets/59546984/ffc8ed8b-d05f-4e8b-a233-23fd82dc8f76)
这个配置和obsidian配置文件有关么

**Comment by Kenshin** [comment]
最迟下周一联系你。

**Comment by Kenshin** [comment]
嗨，我休假回来了 😄

***

请把出问题的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6319

然后在这里回复我。

**Comment by jiuxi521** [comment]
已发送

**Comment by Kenshin** [comment]
收到，确认后会告诉你（预计下午）

**Comment by Kenshin** [comment]
我导入了你的配置文件但没有遇到你说的问题，几个地方可能要注意下：

> Obsidian 库名称

<img width="1195" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/799272b1-558a-4da7-a00b-d8e77f86e79a">

虽然可以修改为任何值，但先确保没有空格（我发现你的 Obsidian 库名称中含有空格，不确定是否是它引起的）

> Obsidian SimpRead Sync 服务是否启动

直接访问 http://localhost:7027/ 如果如下图所示说明可以正常运行

<img width="373" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/50f2da93-57f3-4df3-a7a9-877fdf642f09">

**Comment by jiuxi521** [comment]
你好，我删除了文件夹名称中的空格，还是不起作用；

但访问localhost:7027正常



发件人: Kenshin Wang
发送时间: 2024年2月27日 15:14
收件人: Kenshin/simpread
抄送: 浩子; Author
主题: Re: [Kenshin/simpread] obsidian现在不支持自动同步么？ (Issue #6319)

我导入了你的配置文件但没有遇到你说的问题，几个地方可能要注意下：
Obsidian 库名称
image.png (view on web) 
虽然可以修改为任何值，但先确保没有空格（我发现你的 Obsidian 库名称中含有空格，不确定是否是它引起的）
Obsidian SimpRead Sync 服务是否启动
直接访问 http://localhost:7027/ 如果如下图所示说明可以正常运行
image.png (view on web)

**Comment by Kenshin** [comment]
不仅只是删除空格...😂 而是让这两个图中的名字是一个，并且没有空格。

最好的方式是严格配置库先跑通你的流程，然后在根据自身来定制。
