### ISSUE TITLE
CSDN文章后有巨大点赞三连图标, 每一篇都有

### ISSUE THREAD

**Issue by bigsma11** [Kenshin/simpread#632]
https://blog.csdn.net/slx3320612540/article/details/94473158
<img width="576" alt="截屏2020-01-02上午3 19 58" src="https://user-images.githubusercontent.com/12205755/71645170-1e0ab900-2d0f-11ea-8d32-2521104b1a8e.png">

**Comment by Kenshin** [comment]
谢谢反馈。

可以使用 `隐藏列表` 来规避这些问题

```
<div class='meau-gotop-box'>
<div class='more-toolbox'>
<div class='person-messagebox'>
```

建议多看下 **控制栏**  里面的各项功能。

PS：我会同步更新适配规则
