### ISSUE TITLE
#6315 和 #6319还有些疑惑，麻烦您打开看一下，不确定是否会提示您那边 

### ISSUE THREAD

**Issue by jiuxi521** [Kenshin/simpread#6320]
### 描述这个错误

#6315 和 #6319还有些疑惑，麻烦您打开看一下，不确定是否会提示您那边 

### 复现步骤

#6315 和 #6319还有些疑惑，麻烦您打开看一下，不确定是否会提示您那边 

### 操作系统

win10

### 浏览器

chrome

### 发生问题的网址

暂无

**Comment by Kenshin** [comment]
关闭的 Issues 依然可以随时回复… 😂
