### ISSUE TITLE
标注突然不能用了，重启电脑也不行

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [Kenshin/simpread#6323]
### 描述这个错误

之前好好的，今天早上，阅读一篇文档，突然发现标注功能不生效了
<img width="1859" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/498794d5-5b90-4bcf-99a5-5b4d8f4350c4">
然后去logseq上看，发现之前剪藏的文档，标注都没有了，不高亮显示了
<img width="1711" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/daa6fcd9-9f22-46d6-ae0a-f203e2cc9e08">

### 复现步骤

之前好好的，今天早上，阅读一篇文档，突然发现标注功能不生效了
<img width="1859" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/498794d5-5b90-4bcf-99a5-5b4d8f4350c4">
然后去logseq上看，发现之前剪藏的文档，标注都没有了，不高亮显示了
<img width="1711" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/daa6fcd9-9f22-46d6-ae0a-f203e2cc9e08">

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

https://juejin.cn/post/6844903991604674568

**Comment by Kenshin** [comment]
嗨，我休假结束了，这个问题吗解决了？

**Comment by gongxianshengjiadexiaohuihui** [comment]
修复下配置文件可以，谢谢大佬，顺便问一个问题，我看了我的配置文件里面有好多内容，还有我笔记标注的内容，这个东西会越来越大吗
