### ISSUE TITLE
“微信公众平台”与“微信公众号”冲突

### ISSUE THREAD

**Issue by Marx-one** [Kenshin/simpread#6324]
### 描述这个错误

当在高级设定里面开启“如果当前页面为适配站点，是否自动进入阅读模式？”功能时，“微信公众平台”（https://mp.weixin.qq.com/）无法正常显示内容。设置排除列表和加入黑名单，只适用于当前设置，再次登录之后依旧是无法正常显示。

诉求：希望“如果当前页面为适配站点，是否自动进入阅读模式？”这个功能能够正常开启，但是在“微信公众平台”（https://mp.weixin.qq.com/）能够正常显示。
![1](https://github.com/Kenshin/simpread/assets/121099769/eb85d193-8aaf-418a-9d48-3fcb9a4b6bed)
![2](https://github.com/Kenshin/simpread/assets/121099769/b2ef89b0-89d5-426e-bb58-a53aae50eef5)

### 复现步骤

1.打开微信公众平台：https://mp.weixin.qq.com/
2.登录账号
3.页面出错

### 操作系统

Win11

### 浏览器

谷歌

### 发生问题的网址

https://mp.weixin.qq.com/

**Comment by Kenshin** [comment]
这个地方确实有问题，因为公众号后台与公众号文章是同一组域名，但页面结构不一样，所以这里不能使用自动进入阅读模式功能。

把 `mp.weixin.qq.com` 加入到排除列表，同时安装 https://github.com/Kenshin/simpread/discussions/5851 这个插件。

***

这两天在错峰休假，回复时间会延迟，下周回复。

**Comment by Marx-one** [comment]
收到，谢谢您！











                       
原始邮件
                       
                     

发件人："Kenshin Wang"< ***@***.*** &gt;;

发件时间：2024/2/23 20:13

收件人："Kenshin/simpread"< ***@***.*** &gt;;

抄送人："LH"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Kenshin/simpread] “微信公众平台”与“微信公众号”冲突 (Issue #6324)




 
这个地方确实有问题，因为公众号后台与公众号文章是同一组域名，但页面结构不一样，所以这里不能使用自动进入阅读模式功能。
 
把 mp.weixin.qq.com 加入到排除列表，同时安装 #5851 这个插件。
 
 
这两天在错峰休假，回复时间会延迟，下周回复。

**Comment by Kenshin** [comment]
小事情～
