### ISSUE TITLE
导出到notion后存在大量软换行

### ISSUE THREAD

**Issue by iknowzxc** [Kenshin/simpread#6326]
### 描述这个错误

使用导入到notion插件、导入到notion辅助增强后，导入到notion的文章每一段都被拆分成n行，行与行间均插入了软换行。同一网页3~4个月前的导入排版正常，是否是最新的版本增加了什么功能，是否可以通过设置关闭？

### 复现步骤

https://zhuanlan.zhihu.com/p/564623647
例如该网址，进入阅读模式，使用nt快捷键导入到notion后查看页面，即可看见排版问题

### 操作系统

windows

### 浏览器

chrome  122.0.6261.58

### 发生问题的网址

https://zhuanlan.zhihu.com/p/564623647

**Comment by iknowzxc** [comment]
https://github.com/Kenshin/simpread/issues/6259
同这个问题

**Comment by Kenshin** [comment]
是的，解决后我会在 #6259 通知各位。

***

这两天在错峰休假，回复时间会延迟，下周回复。
