### ISSUE TITLE
webdav服务失效了吗

### ISSUE THREAD

**Issue by MaudGuan** [Kenshin/simpread#6327]
### 描述这个错误

![1708873761153](https://github.com/Kenshin/simpread/assets/30279377/5b4b7ddc-3172-4dab-9a5a-00164073ed35)
{"name":"nas","user":"hgfdhf","password":"fdsgsgds", "url": "http://fdfsd.com:777/","format":"ofhtml"}
我填了一条nas的webdav信息，格式如上图，一直授权失败，还说第一、二个数据格式不对，我换成坚果云的webdav信息也不行，账号密码地址都是没问题的

### 复现步骤

账号密码地址都是没问题的

### 操作系统

windows

### 浏览器

chrome，edge

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

**Comment by Kenshin** [comment]
哈，看来已经成功自救了 😄

**Comment by lqstc** [comment]
怎么自救的，可以告诉下吗？

**Comment by MaudGuan** [comment]
格式要求太严格辣，仅仅是光标在下面的空行都不行

**Comment by MaudGuan** [comment]
格式要求太严格&nbsp;发送&nbsp;辣，仅仅是光标在下面的空行都不行
&nbsp;


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月11日(星期六) 晚上11:00
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Kenshin/simpread] webdav服务失效了吗 (Issue #6327)














 
怎么自救的，可以告诉下吗？

**Comment by dyp1121054136** [comment]
原来还能自定义保存的格式
