### ISSUE TITLE
配置文件使用疑问

### ISSUE THREAD

**Issue by davincilll** [Kenshin/simpread#6328]
### 描述这个错误

1.经常会出现修改配置之后在我使用浏览器快捷键（ctrl+e进入聚焦模式)后，esc无法退出，且没有右下角的选项，只能通过刷新页面退出
2.还是配置的问题，时常会出现我创建自动化方案后，一段时间后自动化方案消失
3.有时候修改配置后，进入某个页面我尝试进入阅读模式，会让我一直刷新，有时候退出浏览器后重新进入能解决，有些时候无法解决，只能重新替换配置，初始化配置解决

### 复现步骤

复现情况可能会比较复杂，
具体来说就是在修改配置后出现。不是每一次修改后都会出现上述问题。猜测可能是与配置文件的修改与同步机制有关。
我往往会进行下面配置的修改：
在以下修改前我的同步助手处于打开状态，并且各项导出功能均打开
1.将能够修改的快捷键全部置为--，并非是禁用全部快捷键（此处可能还会将一些配置修改为我习惯的配置）
2.修改浏览器快捷键ctrl+q加入稍后读，ctrl+e进入聚焦模式，ctrl+r进入阅读模式，ctrl+b进入稍后读
3.安装插件，并修改插件配置。具体来说，这些插件我是分两批安装的。第一批插件包括代码增强，大图，导出思源笔记等，此时会出现插件在阅读模式不显示的情况。此时，我去关闭了同步助手，安装了插件管理器，然后重新打开后，有概率出现错误描述中的三种情况，有时候插件管理器仍然不能在阅读模式中显示，经过重新上述操作后方显示，在插件管理器中获取所有插件保存配置到本地后，有概率仍不显示插件，需要重启浏览器，并重新进行上述操作才能显示。第二批添加的插件为自动化增强，导出长截图等（添加方式为在插件中心下载）。在插件管理器进行和第一批一致的操作后，仍不显示，只有重启浏览器刷新后才显示，有时候重启刷新后又不显示，使用云端覆盖仍是这个问题，重新进行操作方能解决。
4.修改阅读模式主题色为白色，此处修改常常存在问题，面板上保存为白色，实际上仍为黑色，只有进入阅读模式后进行切换才可进行切换，且并非是永久性的切换只针对该页面，有时候此处修改导致了错误1的情况
5.在自动化增强的时候不知为何会出现自己配置的自动化（面板中的）不见的情况，且自己在自动化增强中配置的有时也会出现自动化失败的情况（该自动化为导入思源笔记，单用导入思源笔记插件不存在问题），后面才发现不知道什么时候我的导入思源笔记选项配置被修改，导致无法导入。此处还会存在一个问题是有时候该插件不启动，即右上角没有启动信息。
6.我不太清楚我在原始界面使用快捷键ctrl+q（加入稍后读），自动化增强无法被启动，这个是暂时没有实现还是一个bug
7.如果有需要的话，可以提供我的当前的配置文件。

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://zhuanlan.zhihu.com/p/395736272(以上问题与网址无关

**Comment by Kenshin** [comment]
> 问题1

可能是 Bug 但你能稳定复现吗？

> 问题2

可能是因为配置互相覆盖造成的，你可以看下 https://github.com/Kenshin/simpread/discussions/3768 如果是这个问题的话，下次留意下就行。

> 问题3

同一个 URL 多开造成的，最简单的解决方式：重启浏览器。

**Comment by davincilll** [comment]
目前初始化配置后，关闭同步助手后再进行上述重新调整配置后基本上没有出现上述的问题了。
关于阅读模式主题色的问题，我已经找到了问题所在，是我在选项页的暗色模式保持了开启，导致调整主题颜色失效的情况
然后问题1的话，我现在已经初始化配置了，这个问题暂时还没有出现，如果出现我会发一个视频给你，然后尽可能给你一个详细的产生这个问题的步骤

**Comment by Kenshin** [comment]
> 关于阅读模式主题色的问题

现在在手机上回复，所以有些内容可能遗留了（还好找到了解决方案，也确实是这个造成的）

> 聚焦模式

确实是有 Bug 因为有用户反馈过，但无法稳定复现，一直没能成功捉 🐛

> 同步助手

你可以在关闭同步助手的自动同步前提先调整配置项，等彻底调整完毕后再开启自动同步（后重启浏览器），因为配置项很少性需要后期反复调整。

**Comment by davincilll** [comment]
目前我找到了一个复现bug的方法。
我在我的同步助手的配置备份记录中找到两个配置文件，产生的时间差在同一分钟以内。
一个配置会导致出现这个bug，一个配置没有这个bug。这里我删去了uid，如果需要的话我私发给你。
[simpread_config@20240226130103.json](https://github.com/Kenshin/simpread/files/14401264/simpread_config%4020240226130103.json)
[simpread_config@20240226130154.json](https://github.com/Kenshin/simpread/files/14401265/simpread_config%4020240226130154.json)

**Comment by davincilll** [comment]
具体复现的步骤就是启用该配置后，随便进入一个页面然后启用聚焦模式，这里我好像把插件自带的快捷键给禁掉了，没有禁用esc，设置的是浏览器快捷键ctrl+e。

**Comment by Kenshin** [comment]
okay 我明天看下你的配置文件。

PS：不需要 UID（把 UID 删除是正确操作，否则会泄漏 😂

PPS：今天修牙，折腾了挺长时间也不舒服就没用电脑。

**Comment by Kenshin** [comment]
嗨，你发的两个配置文件似乎不对吧？😂

你可以把有问题的配置文件直接发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6328

然后在这里通知我~

**Comment by davincilll** [comment]
已经发送给你了哈

**Comment by davincilll** [comment]
是编码有问题吗，我之前用手机打开看之前github上的那个链接汉字部分是乱码。
我不确定这个是我用vscode打开过程中修改了编码，还是上传到github过程中出了问题，或者是手机的问题。
这个配置文件在我电脑上是正常显示的，我打成了压缩包发你邮箱了。

**Comment by Kenshin** [comment]
我终于复现了你的问题 😂

其实有解决方案 → https://github.com/Kenshin/simpread/discussions/3167

**Comment by davincilll** [comment]
确实解决了这个问题，感谢！！！

**Comment by Kenshin** [comment]
小事情，绕了半天（其实）早就有解决方案...

因为你一直说 `ESC` 我以为是另外一个问题 😂

没问题的话，我关闭这个 Issues 了~
