### ISSUE TITLE
由于zhihu设置CSP原因导致引用外部css无法加载

### ISSUE THREAD

**Issue by 9k01** [Kenshin/simpread#633]
出错的问题代码：
https://github.com/Kenshin/simpread/blob/384df72c0108ff7bea3ef1dfc723841f34cc97e6/src/read/read.jsx#L107
解决:可以存放在插件里

CSP：
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CSP

DEVTOOLS 输出

Refused to load the stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/solid.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.zhihu.com unicom.zhimg.com captcha.gtimg.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

101163486:1 Refused to load the stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/brands.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.zhihu.com unicom.zhimg.com captcha.gtimg.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

101163486:1 Refused to load the stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/fontawesome.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.zhihu.com unicom.zhimg.com captcha.gtimg.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

**Comment by Kenshin** [comment]
谢谢反馈

`Font Awesome` 是针对 阅读模式 →  控制栏 → 站点 & 插件

这两个 Tab 内容的 icon 能否正常显示。 我找了几个 知乎 的页面，均未发生问题，e.g. https://www.zhihu.com/question/20743642

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [1.1.4](http://ksria.com/simpread/welcome/version_1.1.4.html) 版本

我在清理 issues 请确认是否还存在问题？没有的话，请关闭 issues

> 由于临近春节，所以本 issues 会在节后关闭，**如已确认，请自行关闭**

***

本次增加主要是针对 **导出服务**，下面是本次更新的重点内容：

1. 导出服务已经支持 [有道云笔记](http://ksria.com/simpread/docs/#/有道云笔记) · [为知笔记](http://ksria.com/simpread/docs/#/为知笔记) · [Notion](http://ksria.com/simpread/docs/#/Notion)

2. Mac OS 用户，简悦也可以导出到 [Bear · Ulysses](http://ksria.com/simpread/docs/#/URLSCHEME) 了

3. [截图](http://ksria.com/simpread/docs/#/截图)功能

4. 原生的 [离线下载](http://ksria.com/simpread/docs/#/离线HTML)

5. 导出到 WebDAV 的格式，除了 默认的 MD 外，先增加了 **HTML** 以及 **离线 HTML** [说明文档](http://ksria.com/simpread/docs/#/WebDAV?id=定制)

6. 将当前页面发送到「黑名单 · 白名单 · 排除列表 · 延迟列表」时可进行 [二次编辑](http://ksria.com/simpread/docs/#/右键菜单?id=url编辑器)，提供此项功能的效率。

7. 升级了词法分析引擎，包括：

  - 代码段可识别更多类型

  - 阅读模式可识别特殊结构

  - 适配站点增加 URL 的正则表达式支持

更新说明 👉 http://ksria.com/simpread/welcome/version_1.1.4.html

插件方面：

- 新增加 小说阅读辅助，详细说明 【选项页 → （右下角）消息中心】 查看

- 代码高亮插件升级到 0.0.5 解决了之前一些（反馈）问题 👉 https://simpread.ksria.cn/plugins/details/klGUASLasg

**Comment by 9k01** [comment]
哦，这个我自己修改了源文件，修改成chrome.extension.getURL引用了

**Comment by Kenshin** [comment]
👌🏻 那我关闭它了。
