### ISSUE TITLE
obsidian使用自动标注同步，内部链接跳转失败

### ISSUE THREAD

**Issue by hpsh0rk** [Kenshin/simpread#6331]
### 描述这个错误

1. 我通过标注自动同步的功能，同步成功文章了，但是里面的内部链接，调整到对应的文章。
<img width="916" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/d0750f17-10ab-4db9-8437-c31a21476a66">
对应文章里面文章属性是空的，我手动加了一个idx，好像也没作用，还怀疑是文章名没有加id，手动加上也是跳转失败，不确定是怎么判断的
<img width="684" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/b519c19b-067f-4f1e-a9c0-155e016f266a">
2. 我配置了标注的时候是同时导出html和markdown格式的，但是如上图所示，第一次导出是生效的，后面两次是不生效的
<img width="873" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/96f42afb-7d3e-4bb3-bae4-7a05bd82cc21">
3. 我配置了自定义名字，但是还是带了id，不确定是配置的地方有问题么？
<img width="801" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/8d91140a-8eb1-43a0-a7b7-7abdadc6bec7">
<img width="512" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/3403e5be-b8b9-49c3-826a-31bc0df92baa">

不知道还需要提供什么信息不，文档有点多，看了一圈没找到怎么解决。。

### 复现步骤

1

### 操作系统

macOS

### 浏览器

Arc

### 发生问题的网址

1

**Comment by Kenshin** [comment]
> 定制标题的问题

简悦虽然支持标题定制，但这里可能有点 Bug（不确定是否是你的问题）。

> 目录结构的问题

你第一个图里面的文件夹结构似乎有点问题， `output` 里面出现了 `.md` 文件，如果是跟 Obsidian 配合的话，最好确保 `output` 里面仅为 HTML，虽然不是强制性规则，但因为你出现了问题，所以提示下。

> 对应文章里面文章属性是空的问题

`idx` 只是简悦的 Matedata 理论上跟 Obsidian 应该没关系，所以你没有太理解 **内部链接跳转失败** 具体是指什么？


### 一个建议

我看你的动手能力不错，同时我看到你提交的浏览器是 Arc，建议先用一个干净的浏览器来测试这套环境，配置库肯定是没问题的，但因为涉及到很多功能的合作，所以调试有些问题。

使用 Chrome / Edge + Obsidian（新建库）完全按照 Obsidian 高级版方案设置好，然后确保这套基础流程可以跑通，然后在这套基础流程基础上在定制它。

**Comment by hpsh0rk** [comment]
自动标注后保存到路径：
<img width="373" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/2bc1cf19-4fed-4a05-98c5-4337c1607192">
打开文章，里面有个“内部链接”，点击提示找不到相应的内容：
<img width="1077" alt="image" src="https://github.com/Kenshin/simpread/assets/30871641/1215b3d6-ab38-4477-9eb3-a76b52e83df2">

另外有没有架构图之类的介绍，我比较好奇他们 浏览器插件->同步助手->obsidian怎么协同的，目前我理解是这样的
1. 当标注后，浏览器会通过http请求同步助手同步到output文件夹（另外为啥同步助手要配置“同步文件夹”和“导出路径“）
2. obsidian插件会监听同步文件夹的simpread_config.md，从而生成标注文件

**Comment by Kenshin** [comment]
看下图的说明

<img width="790" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/45ba58a8-619d-4f5c-ae48-3c5e68b37f81">

选项页 → 服务 → 定制导出，要严格按照这个格式 `{{id}}{{un_title}}{{mode}}`

<img width="898" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0954c14f-af0f-4203-b61c-9c6b3c0e7008">

进入阅读模式后，使用快捷键 <kbd>d d</kbd> 加入稍后时才会产生 `aaa-bbb.html` 的文件 e.g. `10-当 Obsidian 与时间管理相遇.html`

这时点击 **内部链接** 就能看到内容了。

**Comment by hpsh0rk** [comment]
搞定了，感谢解答，先使用一段时间再来给反馈！！！

**Comment by Kenshin** [comment]
哈，搞定就好 👍

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

***

> 有没有架构图之类的介绍

暂时没有 😂 

> 当标注后，浏览器会通过http请求同步助手同步到output文件夹

是这样的，同步助手相当于一个去中心化的服务器。

> obsidian插件会监听同步文件夹的simpread_config.md

没有使用此方式，而是跟同步助手是一个原理。
