### ISSUE TITLE
新站适配：通义千问分享对话

### ISSUE THREAD

**Issue by zyqcn** [Kenshin/simpread#6332]
### 需要适配的新站

`https://tongyi.aliyun.com/qianwen` 

### 有需要请描述这个站的性质

![image](https://github.com/Kenshin/simpread/assets/74034382/3631631b-17b3-4946-9970-e0dc6793a6b5)
分享后的网站无法保存成md文档,还有就是对话太多不支持滚动

**Comment by Kenshin** [comment]
okay 不过，请给我一个可以测试的 URL 😂

**Comment by zyqcn** [comment]
> okay 不过，请给我一个可以测试的 URL 😂

`https://tongyi.aliyun.com/qianwen/share?shareId=7497df1a-6632-44dd-9351-23d470920a4d`

**Comment by Kenshin** [comment]
okay 收到，应该可以适配 😄

**Comment by CanoNandMacaroN** [comment]
> okay 收到，应该可以适配 😄

请问适配完成了吗，是第三方源还是官方适配？
另外提个个人建议：通义千问之类的国内模型个人体验下来在纯文字的知识互动学习方面已经很好用了，可以平替GPT，希望大大能够出个辅助类插件更方便整理整个知识流🥺

**Comment by Kenshin** [comment]
@CanoNandMacaroN 
暂时没有适配，下周适配（我目前再出差）会考虑你的建议的。

**Comment by zyqcn** [comment]
> @CanoNandMacaroN
> 
> 暂时没有适配，下周适配（我目前再出差）会考虑你的建议的。👍

我用了一下,感觉还是不是特别好
![image](https://github.com/Kenshin/simpread/assets/74034382/f6c97631-5134-4f53-986e-28bad1ff1c8c)
这里你能看到,这张图片出现的次数太多

**Comment by Kenshin** [comment]
@zyqcn 

因为没有适配 😂 （已经出差回来，但是忘记适配了...

**Comment by zyqcn** [comment]
> @zyqcn
> 
> 因为没有适配 😂 （已经出差回来，但是忘记适配了...
好吧,那你完事的时候说一下哈,还有好多这种只能AI问答的网站比如星火,豆包啥的挺多呢,看看能不能顺便一并适配了

**Comment by zyqcn** [comment]
> @zyqcn
> 
> 因为没有适配 😂 （已经出差回来，但是忘记适配了...

大兄弟这个能不能先帮忙搞一下,我最近一直在使用,存下来的笔记都去删除图片有点费劲了,感谢兄弟,哪怕临时帮我解决一下哦

**Comment by zyqcn** [comment]
@Kenshin 大兄弟图片这个问题能不能先帮忙搞一下,我最近一直在使用,存下来的笔记都去删除图片有点费劲了,感谢兄弟,哪怕临时帮我解决一下哦

**Comment by Kenshin** [comment]
@zyqcn 

下周就开始 😂 （排期没轮到它

**Comment by Kenshin** [comment]
嗨，这个页面已经适配完毕（抱歉，耽搁太久了，因为某种原因导致检索时漏掉了这个 Issues... 😂

#### 如何更新

将 `tongyi.aliyun.com` 加入到延迟加载列表（选项页 → 高级设定 → 词法分析引擎）

<img width="1209" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d55967fd-4dfa-4d37-88df-6debb0b2feb6">

选项页 → 站点管理 → 官方主适配源（留意下图）

<img width="924" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0e94adad-e103-46d3-9582-10069a07abd1">

更新后请务必重启浏览器确保生效。

#### 效果如下

<img width="1816" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/67108fea-13c3-4d13-829c-2cc50cf4e234">
