### ISSUE TITLE
导入notion一直显示请稍后

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6333]
导入notion一直显示请稍后，然后就无限转圈圈，但是上午还成功导入了来着。咋回事？

_Originally posted by @349466134 in https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-8602651_

**Comment by Kenshin** [comment]
@349466134 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

我随便测试了几个 URL 并没有遇到你说的问题，所以：任意 URL 有问题？还是某个 URL 有问题？

请提供出问题的 URL

**Comment by 349466134** [comment]
任意URL
![Uploading iShot_2024-02-28_08.24.53.png…]()

**Comment by 349466134** [comment]
<img width="1303" alt="iShot_2024-02-28_08 24 53" src="https://github.com/Kenshin/simpread/assets/62539481/04c0c89a-c1bc-4ac7-b567-dd75753dc1ce">

**Comment by 349466134** [comment]
又成功了，我重新授权了一下notion page，不知道有没有关系，但是我之前授权的也是这个page没有问题，继续用用看看。

> @349466134
> 
> 我帮你新建了一个 Issues，并删除了原来位置的内容。
> 
> 我随便测试了几个 URL 并没有遇到你说的问题，所以：任意 URL 有问题？还是某个 URL 有问题？
> 
> 请提供出问题的 URL

现在又可以了，我重新授权了一下notion page。

**Comment by Kenshin** [comment]
okay 解决就好。
