### ISSUE TITLE
复制 Markdown 到剪切板的建议

### ISSUE THREAD

**Issue by yjnu** [Kenshin/simpread#6335]
### 请描述你的建议或任何内容

**问题来源：**
- 复制 Markdown 到剪切板，文本内容前会加这段话的引用“本文由简悦转码，原文地址”

**为什么对我是问题：**
1. 我复制后，到typora中修改，存为笔记，一般是用不到原网址的。
2. 我的笔记不给别人看，简悦并不起宣传作用，相信大多数人都会删除简悦。
3. 导出为文件，添加简悦还可以理解，我认为复制全文真没必要添加。

**解决建议：**
- 插件设置中增加一个开关，可人为关闭复制引用，该开关只有会员才可以关闭，既增加了会员功能，非会员复制也还有宣传作用。

**Comment by Kenshin** [comment]
这并不是用于宣传（简悦从不靠这种方式宣传），某种程度上也算是对原文「转载」的说明，这句话最重要的是有原文链接... 😂

我会考虑这个需求。
