### ISSUE TITLE
获取notion授权失败

### ISSUE THREAD

**Issue by zxtzlyt** [Kenshin/simpread#6337]
### 描述这个错误

无法获取notion授权，也尝试了OneNote，都是不行

### 复现步骤

无法授权

### 操作系统

win11

### 浏览器

chrome 122.0.6261.70

### 发生问题的网址

所有的

**Comment by Kenshin** [comment]
什么提示？录屏或截图说明下。

几个可能对你有帮助的链接：

- https://github.com/Kenshin/simpread/discussions/1567
- https://github.com/Kenshin/simpread/discussions/1773

**Comment by zxtzlyt** [comment]
目前的问题有两个：
1.在edge中无法打开阅读模式，点击图标无法进入阅读模式，右键也无法进入。[cid:7f70b2e3-8cd7-450c-94ca-96899e6b9f77]
第二个问题，chrome中又出现了无法发送到notion的情况，我之前通过卸载chrome解决过，但是现在又出现在这个问题。
***@***.***
________________________________
发件人: Kenshin Wang ***@***.***>
发送时间: 2024年2月28日 22:50
收件人: Kenshin/simpread ***@***.***>
抄送: zxtzlyt ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 获取notion授权失败 (Issue #6337)


什么提示？录屏或截图说明下。

几个可能对你有帮助的链接：

  *   #1567<https://github.com/Kenshin/simpread/discussions/1567>
  *   #1773<https://github.com/Kenshin/simpread/discussions/1773>

―

**Comment by Kenshin** [comment]
请不要在 Email 中回复，请进入 https://github.com/Kenshin/simpread/issues/6337 回复。

> 问题1

解决方案 https://github.com/Kenshin/simpread/discussions/2106

> 问题2

应该还是你的操作问题，建议详细截图（或录屏说明）。另外，注意请使用 [插件方案](https://github.com/Kenshin/simpread/discussions/4954) **不要使用选项页 → 服务内置的方案**

**Comment by zxtzlyt** [comment]
在插件中处理已解决，谢谢。应该是在服务内置方案中设置导致的。

**Comment by Kenshin** [comment]
👍 搞定就好 😄 

PS：留意不要使用扩展端的导入功能~
