### ISSUE TITLE
通过dd加入稍后阅读的本地html文件中的图片是不是需要网络才能加载？

### ISSUE THREAD

**Issue by Xiaoqing2265** [Kenshin/simpread#6339]
### 请描述你的建议或任何内容

通过dd加入稍后阅读的本地html文件中的图片是不是需要网络才能加载？如果是在线加载，能否实现离线到本地？

**Comment by Kenshin** [comment]
> 通过dd加入稍后阅读的本地html文件中的图片是不是需要网络才能加载

默认没有做任何调整的话，图片确实是原图床（也就是你说的需要网络访问）

> 如果是在线加载，能否实现离线到本地？

可以，有很多方案，如：

- 加入稍后读时，选择导出 **离线 HTML**

- 利用图床插件，将图片导出到你自己的图床后再自动加入稍后读 https://github.com/Kenshin/simpread/discussions/4306
