### ISSUE TITLE
是否可以提供部分版式默认不改变的功能？

### ISSUE THREAD

**Issue by qhiuafhdi** [Kenshin/simpread#634]
比如，不改变文章的黑体加粗，只对字体大小、字间距等进行修改？

因为在我看来，作者使用黑体加粗，对段落进行的划分等，就是在提示读者，哪些地方重要。
而如果去掉了这样的提示，读者就只能自己去找重点，这样会拉低阅读的效率。

**Comment by Kenshin** [comment]
谢谢建议。

简悦不会无故优化正文结构，比如你说的情况，如果正文使用了规范粉方式，如 `<b>` `<storage>` 之类的，自然会被保留。

再比如，正文使用了 `<xxxx style="xxxx">` 的方式则会被删除，因为这是不符合规范的方式。

***

你可以通过 选项页 → 高级设定 → 词法分析引擎 取消 `纯粹模式` 试试。

另外，建议多看下 选项页 里面有很多关于个性定制化的功能。 😀

**Comment by qhiuafhdi** [comment]
> 建议。
> 
> 简悦不会无故优化正文结构，某些你说的情况，如果正文使用了规范粉方式，如`<b>` `<storage>`之类的，自然会被保留。

感谢回复。
我试了下，似乎只有微信公众号的文章会是这样的。
关闭纯粹模式也还是没用。

**Comment by qhiuafhdi** [comment]
补充：切换默认主题色“白练”后，问题解决了。

**Comment by Kenshin** [comment]
解决就好

emmm... 感觉应该是主题的问题，但不确定是哪个地方出现了问题。

方便的话把 URL 发上来看看，顺便告诉下是哪个主题出现的问题。 😀

**Comment by qhiuafhdi** [comment]
几乎所有主题都存在对原版结构优化的问题，
[以这篇为例](https://mp.weixin.qq.com/s?__biz=MzU3Mjk1OTQ0Ng==&mid=2247484205&amp;idx=1&amp;sn=285b60e7bb8ac7732dd771fa73438215&source=41&scene=21#wechat_redirect)
其中对原版改动最小的主题是“百合”，
对比原版和使用“百合”主题，
他唯一的毛病，是会把原版字体颜色字体转为其他颜色。
比如蓝转红，红转黑。

**Comment by Kenshin** [comment]
我看了下这个链接的内容。

> 蓝转红，红转黑 的问题

![image](https://user-images.githubusercontent.com/81074/72200608-8895c480-3486-11ea-8691-01bbf5f9c445.png)

上图就是我曾说过的 **不规范的 HTML 结构** 所以在生成阅读模式时，自然会被删除。

> 你说的只有 `百合` 才会好使的解释

`百合` 主题下 `<strong>` 是包含了恰好是 **红色粗体**，其它主题并未包含颜色。（ 这也就是你看到的现象

***

结论：

- 不规范的问题，自然会被删除其样式；

- 我会考虑其它主题  `<strong>`  `<b>` 之类的样式设计。

**Comment by qhiuafhdi** [comment]
原来如此，感谢回复：）

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了（优化了一些主题的细节），所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
