### ISSUE TITLE
Medium上部分链接，保存PDF后，图片无法加载

### ISSUE THREAD

**Issue by WanDa1993** [Kenshin/simpread#6340]
### 需要适配的新站

https://devjorgecastro.medium.com/modern-android-development-in-2024-b70f194938bd

**Comment by WanDa1993** [comment]
![image](https://github.com/Kenshin/simpread/assets/16666953/1775c447-ba04-455d-9a9d-7ee8bff6636a)

**Comment by WanDa1993** [comment]
![image](https://github.com/Kenshin/simpread/assets/16666953/7134866f-9867-4a16-a0ff-ba9f242caa6f)

**Comment by Kenshin** [comment]
Medium 是比较麻烦的页面，所以阅读模式是否能显示图片？如果能的话，可以使用：

1. 浏览器自带的 PDF 导出方案
2. 简悦的 PDF 高级打印方案 https://github.com/Kenshin/simpread/discussions/3887

**Comment by WanDa1993** [comment]
![image](https://github.com/Kenshin/simpread/assets/16666953/d702769f-f874-4735-8a93-39eb303753c2)

**Comment by WanDa1993** [comment]
我在本地同步助手和插件中设置找了一圈，没找到开启的选项，麻烦作者指导一下

wkhtmltopdf 已经下载好了

**Comment by WanDa1993** [comment]
<img width="1113" alt="image" src="https://github.com/Kenshin/simpread/assets/16666953/7e581394-749e-405e-968b-fc857802301a">

**Comment by WanDa1993** [comment]
已解决，没有安装PDF增强插件

**Comment by Kenshin** [comment]
哈，解决就好 👍
