### ISSUE TITLE
使用PDF高级方案后，wkhtmltopdf ，导出PDF一直失败，打开任意网站的阅读模式都无法使用高级PDF导出

### ISSUE THREAD

**Issue by WanDa1993** [Kenshin/simpread#6342]
### 描述这个错误

原网址：
https://juejin.cn/post/7339221543992426559
![image](https://github.com/Kenshin/simpread/assets/16666953/83bd4e7f-9633-4ae7-b128-994d1884e3df)

### 复现步骤

1.点击PDF辅助增强
![image](https://github.com/Kenshin/simpread/assets/16666953/095434bc-5b00-4509-9083-deb7ebc914ed)
2.图片转换 M / N
3.图片转换成功之后即展示失败提示

### 其他相关说明

有意思的是，使用该功能是为了Medium图片导出，默认直接执行动作PDF导出，则无法显示图片

但是点击PDF辅助增强插件后，使用动作PDF导出，则之前无法显示的图片，却都可以显示了

### 操作系统

macOs

### 浏览器

Chrome

### 发生问题的网址

https://juejin.cn/post/7339221543992426559

**Comment by WanDa1993** [comment]
#6340  这是上一个问题，目前不影响使用，反馈一下

**Comment by Kenshin** [comment]
嗨，我测试了下这个页面，确实有问题。

简悦的 PDF 高级打印方案已经对图片做了常规性的本地化设置，但某些网站确实存在这个问题，比如严苛的图片防盗链等，对于这类网站的话，简悦的做法如下：

<img width="825" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/90237255-a0c5-4f83-b163-1f101954d1da">

上述内容来自 https://github.com/Kenshin/simpread/issues/6341#issuecomment-1970579429

**Comment by WanDa1993** [comment]
感谢解答，不过我有个疑惑：

- 不使用PDF增强的话，直接通过“动作-PDF导出”，图片会挂掉

- 先使用PDF增强，就算报错，再次使用“动作-PDF导出“，图片就会出现

这是因为两边图片会共用吗？另外如果后续我使用上述方式解决该问题可行吗？

**Comment by Kenshin** [comment]
PDF 辅助增强插件会将图片本地化（ base64 编码），然后再使用 **动作 → 导出 PDF** 时因为图片已经是 base64 所以可能就没问题了。

只是个巧合 😂
