### ISSUE TITLE
导入到Notion_插入很多换行符

### ISSUE THREAD

**Issue by ErikZhangGithub** [Kenshin/simpread#6344]
### 描述这个错误

任意网站导入可以成功， 但总会在导入的内容中增加很多换行符，导致排版错位，阅读体验很差。

### 复现步骤

文章地址：https://community.fs.com/article/tight-buffered-cable-vs-loose-tube-gel-filled-cable.html

阅读模式页面：
![image](https://github.com/Kenshin/simpread/assets/128197432/4531769a-8fd7-4a14-bdf7-d4efe43b6c7c)
导入后样式：
![image](https://github.com/Kenshin/simpread/assets/128197432/e89e5a47-ec7c-4168-be95-ce5701143ce6)

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://community.fs.com/article/tight-buffered-cable-vs-loose-tube-gel-filled-cable.html

**Comment by Kenshin** [comment]
嗨，这不是简悦的问题，关联问题 https://github.com/Kenshin/simpread/issues/6259

有进一步消息我会在 https://github.com/Kenshin/simpread/issues/6259 通知你~
