### ISSUE TITLE
支持订阅源管理

### ISSUE THREAD

**Issue by s-chance** [Kenshin/simpread#6345]
### 请描述你的建议或任何内容

能否提供一个类似于 wallabag 插件+wallabag 服务端的组合，用于保存网页至服务端？文档中提到的Pocket和Instapaper 似乎都不开源，不支持用户自建？

有考虑推出一个类似于 wallabag 的开源 simpread 服务端吗？

### 补充说明

适用于希望通过 rsshub + miniflux/ttrss/freshrss + simpread（包括浏览器插件和类似于wallabag的网站服务）等组合来获取互联网信息并专注于阅读的用户。

**Comment by Kenshin** [comment]
嗨，使用用途不一样。

简悦不是网页收藏工具（虽然简悦有非常强大的网页导出功能），简悦是基于深度阅读诉求的产品。所以，它不是传统意义的稍后读。

所以你可以用你喜欢的方式收集网页，然后使用简悦来实现 **沉浸式阅读**。

这里有很多用户整理的简悦使用方案 https://github.com/Kenshin/simpread/discussions/2085

不过，简悦也支持自建，但仍不是你理解的这种方式，细节可以看 https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3A%22self+built%22

你可以理解简悦是一个去中心化的产品，所有的数据都在你的本地，也无需担心隐私问题，同时还提供一般服务器才能提供的功能。

**Comment by Kenshin** [comment]
补充一点：

rsshub + miniflux/ttrss/freshrss 跟简悦并不冲突，只要是基于网页，就能使用简悦。
