### ISSUE TITLE
无法打开维基文库下的全部网站

### ISSUE THREAD

**Issue by 23ve** [Kenshin/simpread#6346]
### 描述这个错误

在打开维基文库时始终出现问题，插件会在运行几秒钟后自动让所有文字消失掉。无论是否打开阅读模式都是如此。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/92638514/1d248863-aca9-480b-8538-02606745ac7c)
如上。这一问题一年前即出现（关闭插件就能正常阅读）。

### 操作系统

win

### 浏览器

edge

### 发生问题的网址

https://zh.wikisource.org/wiki/%E6%99%89%E6%9B%B8/%E5%8D%B7073#%E5%BA%BE%E7%BF%BC

**Comment by Kenshin** [comment]
原因说明（可直接看下面的解决方案） https://github.com/Kenshin/simpread/discussions/2347
解决方案 https://github.com/Kenshin/simpread/discussions/5832
