### ISSUE TITLE
无法通过简悦导入到 Logseq

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [Kenshin/simpread#6349]
### 描述这个错误

之前是页面无法使用标注了，修复了配置文件之后可以了，然后今天发现有三篇之前标注的网页没有同步到笔记中，但是从logseq的插件里有这三篇文档，查了文件夹，html是在的，没有生成md
<img width="1685" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/1e0a6658-575b-4e32-a26e-8044714aaa57">
<img width="1305" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/1f7d6992-db50-4849-b364-14d9cc704a8a">

### 复现步骤

修复配置文件后，出现这个问题，之前都是正常的

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

无

**Comment by gongxianshengjiadexiaohuihui** [comment]
<img width="1447" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/51348172-474b-4e94-b568-b57487e14c55">

**Comment by gongxianshengjiadexiaohuihui** [comment]
<img width="989" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/9c5a257c-e190-48c8-ad23-141e77f61e83">

**Comment by Kenshin** [comment]
> 有三篇之前标注的网页没有同步到笔记中

1. 看下简悦的稍后读对应的这三篇文件是否存在标注？如果存在的话，重新手动导出即可。
2. 本地快照（ HTML 文件中）中是否存在标注？

**Comment by gongxianshengjiadexiaohuihui** [comment]
1、手动导出可以了
2、有的
    但是我新加的文章都不行了，都需要手动导出吗？这个是我的配置问题，还是什么呢

**Comment by gongxianshengjiadexiaohuihui** [comment]
而且，通过稍后读保存markdown，无法和logseq的插件联动的，只有批注内容
![Uploading image.png…]()

**Comment by gongxianshengjiadexiaohuihui** [comment]
而且，通过稍后读保存markdown，无法和logseq的插件联动的，只有批注内容
![image](https://github.com/Kenshin/simpread/assets/39046975/634d1b83-22ac-4bca-ab91-1e61c31a0a8b)

**Comment by Kenshin** [comment]
> 我新加的文章都不行了，都需要手动导出吗？这个是我的配置问题，还是什么呢

对比下你的配置跟教程有什么区别，没有相关截图我也不知道，但单看问题肯定是跟配置有关...  😂 

> 过稍后读保存markdown，无法和logseq的插件联动的，只有批注内容

这是正常的情况，只有在网页端标注才会自动导入到 Logseq 中。

***

另外，你并没有说使用哪种 Logseq 导入方案，所以最好是按照我的提示自己先排查下。

**Comment by gongxianshengjiadexiaohuihui** [comment]
我之前是通过，logseq的配置库中的markdown版本 搞的，下午，我又按照文档的流程检查了一遍，也没有什么，问题，就是上次修复了配置文件之后，突然这样了。。搞了一下午，也没有思路

**Comment by gongxianshengjiadexiaohuihui** [comment]
感觉这套东西挺好用的，就是配置太复杂反锁了，提个建议，无论同步助手也好，还是插件配置也好，是否能提供不同需求的配置文件（现在的json中，好多无关属性配置的内容，建议隔离开）供下载，大部分人的需求其实就是一套默认配置，但是从文档找东西太难找了，出了问题，也不好定位和查找，也没有日志什么的吗

**Comment by gongxianshengjiadexiaohuihui** [comment]
莫名奇妙又好了

**Comment by Kenshin** [comment]
okay 没问题就好，如果你没有修改简悦这边的配置，大概率是 Logseq 的问题。

这种多 App 的协作就有这种弊端，没有太好的解决方案。

我关闭这个 Issues 了。

***

> 无论同步助手也好，还是插件配置也好，是否能提供不同需求的配置文件

一直都有... https://www.yuque.com/kenshin/simpread/ds8zk0

> 现在的json中，好多无关属性配置的内容，建议隔离开

这是 Next Feature 会实现的。
