### ISSUE TITLE
能否顺便实现所有网页默认 dark 模式

### ISSUE THREAD

**Issue by dedoyle** [Kenshin/simpread#635]
用这个一是为了阅读舒适，二是为了护眼。平时网页都喜欢装个插件，把网页变成黑暗模式，但是这种插件又没做阅读模式。而阅读插件又不做黑暗模式，实在是希望两个功能可以合并，只装一个插件即可。

**Comment by Kenshin** [comment]
请问你说的哪个插件？

建议试试 [Dark Reader](https://darkreader.org/) 它可以渲染简悦生成阅读模式后的页面。

另外，你可以使用简悦的 `黒鸢` 和 `紺鼠` 均为暗色模式。

**Comment by dedoyle** [comment]
确实装了两个插件，一个是 dark reader，用于对所有网页开启 dark 模式。另外一个是简悦单纯用于文章美化了，也只能这样了
