### ISSUE TITLE
PDF导出时出错，

### ISSUE THREAD

**Issue by Bolun001** [Kenshin/simpread#6353]
### 描述这个错误

![PDF导出失败](https://github.com/Kenshin/simpread/assets/99233679/a5df370b-dc56-46fb-a307-fa0733a71cd8)

### 复现步骤

打开网址，进入阅读模式，点击导出PDF，此时已经打开同步助手，
但显示失败，实验性功能，
之前都是可以到处的，怎么实验以下还倒退了呢？

### 操作系统

Win11系统

### 浏览器

Edge浏览器，简阅助手1.20

### 发生问题的网址

https://mp.weixin.qq.com/s/0NkX1QYv4lALaRPgxHkf4w

**Comment by Kenshin** [comment]
之前你使用的是浏览器方案，这种方式会导致图片在两页之间，但优点就是什么网页都可以；你使用的同步助手基础导出方案，不会出现图裂的问题，但个别网页无法使用。

***

你现在使用的方式也有点旧，建议使用 [同步助手高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)

<img width="1458" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2b635fbf-0648-4a56-8a90-44220902ae73">

**Comment by Bolun001** [comment]
![image](https://github.com/Kenshin/simpread/assets/99233679/edafbe0a-de13-4cce-b9e3-13e7228b830b)
打开网页后的网盘链接失效了，可以补一下吗？

**Comment by Kenshin** [comment]
okay 谢谢提示。不过，这仅仅只是演示...

**Comment by Bolun001** [comment]
![image](https://github.com/Kenshin/simpread/assets/99233679/332e5b36-2ae5-4bc1-a4bd-4eb32d3ccbcf)
此处没有下拉框，不知道是怎么回事，此外，我将对应的插件安装到了D盘，并在对应的bin目录下进行测试，确定已经安装，但出现的界面仍然是
![image](https://github.com/Kenshin/simpread/assets/99233679/53aec3ce-e649-4e0f-b2fd-2c97195a3230)
是哪里出问题了呢？

**Comment by Kenshin** [comment]
看图

<img width="366" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c1e28ae6-cb8e-417e-b48b-05bcbd78a204">

**Comment by Bolun001** [comment]
感谢，一开始这个小三角点不动，多试了几次之后可以选择了，记录一下！
1. 使用这个功能的时候，必须开《《《同步助手》》》。此处要检查到处目录是否存在
2. 选择高级模式，会出现
![image](https://github.com/Kenshin/simpread/assets/99233679/1a241444-4102-4f73-be75-8473d51b4744)
3. 切换为同步基础打印方案后，成功导出
![image](https://github.com/Kenshin/simpread/assets/99233679/8bc12d65-927f-413e-a24c-bec7049896bd)
目前已经可以正常使用，THX， Kenshin

**Comment by Bolun001** [comment]
第二部出现的问题和这个Issue一样，https://github.com/Kenshin/simpread/issues/6212#issuecomment-1871680298
![image](https://github.com/Kenshin/simpread/assets/99233679/fcf7c6d8-d351-4660-ba83-e09ff9c07ec3)
对应的网页就是https://sspai.com/post/75567

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6353#issuecomment-1980369295

说下你的系统，同时这个问题，试试把标题改为英文，细节看下  https://github.com/Kenshin/simpread/issues/6176

修改标题为英文的方式 https://github.com/Kenshin/simpread/discussions/2852

**Comment by Bolun001** [comment]
已经解决了，记录一下，之前这部分没有填写，留白情况下会出错，
![image](https://github.com/Kenshin/simpread/assets/99233679/89e0b8cb-f6e3-426d-b45a-a06cf7ffda18)
刷l了PDF配置包之后，已经正常导出，不是标题中英文的问题，另外可以问一下，https://github.com/Kenshin/simpread/issues/6353#issuecomment-1977986843
的配置信息是？

**Comment by Bolun001** [comment]
啊！成功运行了几次之后，再次出现这个问题：
![image](https://github.com/Kenshin/simpread/assets/99233679/9b794e06-3a88-4b65-a73c-5e7aba118edb)
一开始成功导出做了这些步骤：使用https://www.yuque.com/kenshin/simpread/omehxx PDF配置，卸载重装Edge插件，然后用配置进行覆盖，同步助手也进行了修改，于是导出成功
而现在，想要再导出一篇文章，缺再次出现问题：
![image](https://github.com/Kenshin/simpread/assets/99233679/b0b7eb7f-3cd8-4f92-a612-f215a1c3d98a)
而且之前的基础导出功能也提示为实验性功能，
目前的配置文件为：
![image](https://github.com/Kenshin/simpread/assets/99233679/a85b2a3b-649b-4480-a4d1-feb43d3becce)
![image](https://github.com/Kenshin/simpread/assets/99233679/7082af45-40e4-42f3-be94-284752f5ddd0)

**Comment by Kenshin** [comment]
哈，搞定就好 👍

理肯定不是中英文的问题（因为只有几个用户疑似是这个问题造成的）但上不填写边距这些也没问题，我稍晚做个测试。

> 另外可以问一下，https://github.com/Kenshin/simpread/issues/6353#issuecomment-1977986843

就是默认配置，没有做任何更改。

PS：谢谢你的详细测试，我会通知 https://github.com/Kenshin/simpread/issues/6176

**Comment by Kenshin** [comment]
> 成功运行了几次之后，再次出现这个问题：

重启你的同步助手以及浏览器。

**Comment by Bolun001** [comment]
重启了，但还是这样的问题
![image](https://github.com/Kenshin/simpread/assets/99233679/78db948d-fb84-4378-9f19-bc772b08ea1c)
我在output目录下进入cmd，是可以把对应的html文件转为pdf的，此外，我在之前还把wkhtmltopdf加入到环境变量中，这几次保存的都是微信公众号文章。但一开始成功，后面就都不能保存成功了

**Comment by Bolun001** [comment]
![image](https://github.com/Kenshin/simpread/assets/99233679/a8218b9f-3cce-4cbf-a3bd-7e24673cd9a6)
"wkhtmltopdf --margin-left 20 --margin-right 20 --margin-top 20 --margin-bottom 20 "F:\简悦文件夹\output\tmp-3-放弃纠结、拥抱妥协，重器轻用就是高效.html" "F:\简悦文件夹\Ebook\3-放弃纠结、拥抱妥协，重器轻用就是高效.pdf""
这些是控制台报错的信息

**Comment by Kenshin** [comment]
emmm 试试添加 `wkhtmltopdf` 对应的运行目录。

PS： 很奇怪的问题，个别用户就是怎么都不行... 😂

**Comment by Bolun001** [comment]
不过，这样以来，这里又可以用了，替代方案+1
![image](https://github.com/Kenshin/simpread/assets/99233679/901b3c45-bbee-4b9f-a83a-233d1d8812cc)

**Comment by Bolun001** [comment]
> emmm 试试添加 `wkhtmltopdf` 对应的运行目录。
> 
> PS： 很奇怪的问题，个别用户就是怎么都不行... 😂

还是不行，这个报错背后，会是那些步骤出错了呢？希望可以出一个配置
![image](https://github.com/Kenshin/simpread/assets/99233679/3da19f36-79d3-43f6-8382-6d2d307dcc88)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6353#issuecomment-1982299955

这个方式使用的不是 `wkhtmltopd` 方案。

> 这个报错背后，会是那些步骤出错了呢？

简悦这套逻辑很简单，就是帮你调用 `wkhtmltopdf --margin-left 20 --margin-right 20 --margin-top 20 --margin-bottom 20 "F:\简悦文件夹\output\tmp-3-放弃纠结、拥抱妥协，重器轻用就是高效.html" "F:\简悦文件夹\Ebook\3-放弃纠结、拥抱妥协，重器轻用就是高效.pdf"` 这段代码... 

所以只要：有权限且 `wkhtmltopdf` 可以正常在全局调用就没有任何问题。

你试试：

1. 文件夹的名称改为 **全英文（不要有任何空格）**，保存后重启同步助手 & 浏览器。
2. 在命令上手动执行上面的命令 `tmp-3-放弃纠结、拥抱妥协，重器轻用就是高效.html` 随便找个 `.html` 的文件即可。

**Comment by Bolun001** [comment]
直接调用命令行也是可以的，中文或者有空格的文件夹也可以成功，那么原因是否是在生成这个tmp文件时，出现问题了呢？
![image](https://github.com/Kenshin/simpread/assets/99233679/2236eeb2-8a8c-409c-9d19-5dd9d86d14ba)

**Comment by Bolun001** [comment]
另外，在进入阅读模式时，这个网页出现了大量的空白
https://mp.weixin.qq.com/s?__biz=MjM5NjYxNDk4Mw==&mid=2650720985&idx=1&sn=f53f67895cdae088def9eeaad65b2925
希望可以看看是否普遍存在

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6353#issuecomment-1983232514

请安装这个插件 https://github.com/Kenshin/simpread/discussions/5851

***

至于 PDF  的问题，我真的不知道，否则也不会存在 https://github.com/Kenshin/simpread/issues/6176 的问题了...

看下这个用户的回复（他使用的就是你提供的思路）https://github.com/Kenshin/simpread/issues/6176#issuecomment-1982949087

**Comment by Bolun001** [comment]
目前已经可以使用了，在检查wkhtmltopdf在命令行运行正常之后，刷了新的PDF配置，（其中重新安装浏览器插件是关键）确保对应的文件夹位置都是正确的
如果还有问题
之后在pdf增强里面要配置好左右距，上下边距，全局字体可以暂时去掉（如果网络确定没问题，也可以不用去）
如果还有问题
最后在插件管理器里面，和本地配置在做一个同步
如果还有问题
重启浏览器和本地的同步助手
此时，大概率就正常使用啦

发件人: Kenshin Wang ***@***.***>
发送时间: 2024年3月7日 19:00
收件人: Kenshin/simpread ***@***.***>
抄送: Bolun ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] PDF导出时出错 (Issue #6353)


#6353 (comment)<https://github.com/Kenshin/simpread/issues/6353#issuecomment-1983232514>

请安装这个插件 #5851<https://github.com/Kenshin/simpread/discussions/5851>

________________________________

至于 PDF 的问题，我真的不知道，否则也不会存在 #6176<https://github.com/Kenshin/simpread/issues/6176> 的问题了...

看下这个用户的回复（他使用的就是你提供的思路）#6176 (comment)<https://github.com/Kenshin/simpread/issues/6176#issuecomment-1982949087>

**Comment by Kenshin** [comment]
赞！

我在出差，后续把必要信息给需要的用户。

**Comment by Bolun001** [comment]
希望可以帮到其他用户！

发件人: Kenshin Wang ***@***.***>
发送时间: 2024年3月8日 21:35
收件人: Kenshin/simpread ***@***.***>
抄送: Bolun ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] PDF导出时出错 (Issue #6353)


赞！

我在出差，后续把必要信息给需要的用户。
