### ISSUE TITLE
购买了高级账号但没有收到license

### ISSUE THREAD

**Issue by John-Chan** [Kenshin/simpread#6354]
### 描述这个错误

抱歉，找不到反馈渠道，只能发这里了。大概是3号购买的，可以通过支付宝的支付截图和购买时留的邮箱。

### 复现步骤

无

### 操作系统

无

### 浏览器

无

### 发生问题的网址

无

**Comment by Kenshin** [comment]
另外，发到这里是对的，这是简悦官方唯一的 QA 渠道，其它方式虽然也会回复，但很慢。（因为我不会每天都检查我所有的社交渠道的私信...

**Comment by John-Chan** [comment]
我还是没有收到邮件，我已经检查了垃圾邮件

订单支付信息：
- 时间是3月4号13:24分
- 订单尾号9817

**Comment by Kenshin** [comment]
emmm

我查到了你的付款信息，但我没有在腾讯问卷查到对应的信息，所以应该是：**没有在腾讯问卷填写**或**你的 Email 填写错误**或**订单号后六位填写错误**。

请在 https://wj.qq.com/s2/6918802/ffc8/ 提交，我会在今天晚上 19 点前发送兑换邮件。

***

**Comment by John-Chan** [comment]
感谢，确实忘记填写订单尾号，腾讯问卷这么拉跨吗，必填项没填也能提交的。

**Comment by Kenshin** [comment]
> 腾讯问卷这么拉跨吗，必填项没填也能提交的。

😂 ...

okay 今天 19 点后留意下你的 Email
