### ISSUE TITLE
新站适配：适配公众号图文版

### ISSUE THREAD

**Issue by HUGOSAMA1121** [Kenshin/simpread#6355]
### 需要适配的新站

https://mp.weixin.qq.com/s/TQ5CmZQ_rZXpgmMjptsJew

### 有需要请描述这个站的性质

图片是否可以获取？

**Comment by Kenshin** [comment]
可以考虑，方便的话，请多给我一些这种类型的网页。

**Comment by Kenshin** [comment]
嗨，这个功能已经完成了（忘记通知了 😂

请安装 [微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 插件（内含说明）

我关闭这个 Issues 了。
