### ISSUE TITLE
请求增加划词功能

### ISSUE THREAD

**Issue by 9k01** [Kenshin/simpread#636]
你好，请求增加划词高亮功能
https://github.com/mir3z/texthighlighter
http://mir3z.github.io/texthighlighter/demos/simple.html

```
var hltr = new TextHighlighter(document.querySelector('.simpread-read-root'),{
    keepRange: true,
    onBeforeHighlight: function(range) {
        return true
    },
    onAfterHighlight: function(range, highlightsEles, timestamp) {
        // 添加高亮
        var key = '[data-timestamp="' + timestamp + '"]'
        HIGHLIGHLASTKEY = key
        var highlightsElements = document.querySelectorAll(key)
        if (!highlightsElements.length)
            return true

        var range = document.createRange();
        var startNode = highlightsElements[0]
        range.setStart(startNode, 0);
        for (var i = 0; i < highlightsElements.length; ++i) {
            var highlightsElement = highlightsElements[i]
            highlightsElement.style.cursor = "pointer"
            highlightsElement.title = "点击清除高亮"
            highlightsElement.addEventListener('click', function() {
                highlightsElements.forEach(function(v) {
                    hltr.removeHighlights(v)
                })
            })
        }
        range.setEnd(highlightsElement, highlightsElement.childNodes.length);
        var selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(range)
    },
    onRemoveHighlight: function(hl) {
        return true
    }
});
```

**Comment by Kenshin** [comment]
谢谢建议，我会考虑此功能！

**Comment by OrdinaryYZH** [comment]
新用户表示这个功能太有用了，看文章的时候能够方便画出重点，方便之后自己做笔记！！

**Comment by Kenshin** [comment]
@9k01 
嗨，这条信息也是你的吧？https://github.com/Kenshin/simpread/issues/639

方便的话合并成一个吧。😀

另外，此功能我会有更棒的方案，如果感兴趣的话，到时候我可以给你内测版。

**Comment by 9k01** [comment]
这个我主要考虑的是本地保存为mhtml，保存成mhtml好像禁止了js功能，这种是我暂时能想到兼容性比较全面的方案了。

**Comment by Kenshin** [comment]
关联 issues https://github.com/Kenshin/simpread/issues/463

**Comment by StevenJokes** [comment]
+1

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

简悦 2.0 包含了自己的 **标注系统**，所以我将关闭此 issues

> 谢谢提供这么高的思路，简悦的标注功能才得以实现。

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
