### ISSUE TITLE
ChatGPT  需要更新适配规则

### ISSUE THREAD

**Issue by xianyu997** [Kenshin/simpread#6360]
### 描述这个错误

如题

### 复现步骤

问chatgpt
无法解析回答

### 操作系统

win11

### 浏览器

chorme

### 发生问题的网址

https://chat.openai.com/c/c08789ae-6205-4be2-b2a9-3ff6c821737d

**Comment by Kenshin** [comment]
可能是 ChatGPT 页面结构改变了，你关闭这个 Issues 的原因是？

**Comment by Kenshin** [comment]
嗨

ChatGPT 辅助增强插件更新到 **1.2.0**，主要适配了 ChatGPT 最新版界面。


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/8CjJLsNUKU) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

后续有任何问题，请在 https://github.com/Kenshin/simpread/issues/6478 集中讨论。
