### ISSUE TITLE
简化控制面板

### ISSUE THREAD

**Issue by bighear** [Kenshin/simpread#6361]
### 请描述你的建议或任何内容

1. 更精简的悬浮面板
1.1取消样式栏或者靠后放置或者隐藏
1.2聚合帮助手册入口或者下置帮助
2.更清晰的引导
2.1稍后读的加入很好，但是没有做更具体的引导，我很早就看到了这个功能，但是已知不知道能做什么
2.2自动启动阅读模式的功能很好用，但是上手比较困难，而且操作很麻烦，作为一个懒人更希望的是能够通过黑名单的方式排除而不是白名单启用。

阅读模式下的悬浮面板功能特别复杂，实际上经常用到的功能只有动作栏的导出，添加稍后读等功能。样式栏不是必须的，因为应该没有人天天改样式。帮助手册很好但是不是每天都需要且每个栏目都添加一个帮助手册的链接的。
使用简悦的最初想法是聚焦阅读，但是现在的功能太多且藏的太深了，傻瓜式的入手和简洁的界面才更容易获得大众认可。

**Comment by Kenshin** [comment]
嗨，会考虑的，不过，你可以使用：

- [Assistive Touch - 类似 iOS 的快捷浮动工具栏](https://github.com/Kenshin/simpread/discussions/1600)

- [阅读模式浮动面板定制器](https://github.com/Kenshin/simpread/discussions/1601)
