### ISSUE TITLE
csdn 的代码高亮后,会导致代码的位置错误,如该网址的组合模式的Component  接口

### ISSUE THREAD

**Issue by shaoyi-robin-zhou** [Kenshin/simpread#6362]
### 请选择

代码高亮

### 发生问题的网址

https://blog.csdn.net/A1342772/article/details/91349142

**Comment by shaoyi-robin-zhou** [comment]
![image](https://github.com/Kenshin/simpread/assets/60779124/abd23291-6297-48ef-b64d-879ab10cad2f) 关闭高亮后,正确的位置
![image](https://github.com/Kenshin/simpread/assets/60779124/8091e329-dacd-46d3-99c8-ead77db3827a)

**Comment by Kenshin** [comment]
代码高亮确实有些问题，虽然你关闭这个 Issues 😂
