### ISSUE TITLE
无法通过简悦导入到 Logseq

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [Kenshin/simpread#6363]
### 描述这个错误

[无法通过简悦导入到 Logseq](https://github.com/Kenshin/simpread/issues/6349)，这个bug再次复现了，因为上次我打开了日志，这次观察日志是重启后，我在网页上标注的内容只生成了html和标注，没有增强导出成md格式的文件到logsql的pages文件夹导致这个问题
[simpred_sync.log](https://github.com/Kenshin/simpread/files/14534320/simpred_sync.log)
<img width="1376" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/a221ff17-067b-4c29-b6ed-aacedb4dbcc6">
这是上次的bug的几篇文档，已经生成了，重启后，又标注的几篇，都没有导出md
<img width="1476" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/cc3f28d1-c23b-4612-914b-8f3e111822c5">

### 复现步骤

重启就有这个问题
这是我的增强导出配置，之前一直都是可以的
<img width="728" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/32f5509e-4687-4f33-a786-c088008a44f4">

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

无

**Comment by Kenshin** [comment]
嗨，我在出差，先 Mark 下，下周一详细确认下。

**Comment by Kenshin** [comment]
我出差回来了。

***

> 重启就有这个问题

是指什么？重启同步助手？你的意思是：设置后保存，然后好使了，但重启同步助手又不好使了？

**Comment by gongxianshengjiadexiaohuihui** [comment]
> 我出差回来了。
> 
> > 重启就有这个问题
> 
> 是指什么？重启同步助手？你的意思是：设置后保存，然后好使了，但重启同步助手又不好使了？

重启电脑后

**Comment by Kenshin** [comment]
重启电脑然后配置没有了？还是配置不变，但重启后就不好使了？

**Comment by gongxianshengjiadexiaohuihui** [comment]
> 重启电脑然后配置没有了？还是配置不变，但重启后就不好使了？

之前就不知道怎么好的，，重启电脑，理论上，我的配置是没有变化的

**Comment by gongxianshengjiadexiaohuihui** [comment]
> > 重启电脑然后配置没有了？还是配置不变，但重启后就不好使了？
> 
> 之前就不知道怎么好的，，重启电脑，理论上，我的配置是没有变化的

但是，观察日志，重启前，还有md格式的文件生成，重启后，就只有html格式的了

**Comment by Kenshin** [comment]
> 重启电脑，理论上，我的配置是没有变化的

看下重启电脑后，跟这个功能相关的配置是否改变了？

留意下

1. 自动同步标注的触发条件：使用快捷键 `d d` 加入稍后读，等出现右侧标注后再标注。

2. 打开 Markdown 模板辅助增强，手动测试能否生成标注？

**Comment by gongxianshengjiadexiaohuihui** [comment]
我发现了个问题，我按照配置库的文档配置了模版
<img width="1955" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/29d20a66-3558-4595-be45-c34dfb9adcb5">
也保存了，但是我在阅读模式的增强md模版里没有看到，这个是不是不对呀
<img width="1889" alt="image" src="https://github.com/Kenshin/simpread/assets/39046975/6a12783d-3d6b-43b6-80a7-e895aaed66a9">

**Comment by gongxianshengjiadexiaohuihui** [comment]
> 我发现了个问题，我按照配置库的文档配置了模版 <img alt="image" width="1955" src="https://private-user-images.githubusercontent.com/39046975/312007810-29d20a66-3558-4595-be45-c34dfb9adcb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzU4MTgsIm5iZiI6MTcxMDIzNTUxOCwicGF0aCI6Ii8zOTA0Njk3NS8zMTIwMDc4MTAtMjlkMjBhNjYtMzU1OC00NTk1LWJlNDUtYzM0ZGZiOWFkY2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA5MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MmIwYmQ4NDEyYTAxY2EyMjIyZjVkZDEwYTlmZTM1Y2VmZjc3MjgyYzZkNGMxOWFhNzU3YmUzYzFmYWIwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pffkFPhUBrlTJYVppoHZ6kAf0haX53wDNqRnWLjXXHs"> 也保存了，但是我在阅读模式的增强md模版里没有看到，这个是不是不对呀 <img alt="image" width="1889" src="https://private-user-images.githubusercontent.com/39046975/312008131-6a12783d-3d6b-43b6-80a7-e895aaed66a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzU4MTgsIm5iZiI6MTcxMDIzNTUxOCwicGF0aCI6Ii8zOTA0Njk3NS8zMTIwMDgxMzEtNmExMjc4M2QtM2Q2Yi00M2I2LTgwYTctZTg5NWFhZWQ2NmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA5MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MTY1YTMwYjdhNWI3MGY1YjRkYTg1MTc0OWY4Njg5N2I5YWFjN2I4NGMxODljZTAyZjI3Mjg2YmE2NWZlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AyGEc32lJhH3GMptYVMjTuzR_iEB1JJ81EB9KbkQqIQ">

我在增强模版中配置了，还是不行

**Comment by Kenshin** [comment]
> 我在阅读模式的增强md模版里没有看到，这个是不是不对呀

当然不对了... 😂

> 我在增强模版中配置了，还是不行

保存后刷新就消失了？如果是的话，可能是 https://www.yuque.com/kenshin/simpread/fcw60u 造成的（内含解决方案）

***

一个提示，在 QA 时（跟简悦无关），建议不要使用 **不行** **重启** 这类有歧义的词汇，建议直接描述，如：`不行的具体现象`，`重启是指什么？具体现象`。

这样能节省用户（你）很多时间~

**Comment by gongxianshengjiadexiaohuihui** [comment]
> > 我在阅读模式的增强md模版里没有看到，这个是不是不对呀
> 
> 当然不对了... 😂
> 
> > 我在增强模版中配置了，还是不行
> 
> 保存后刷新就消失了？如果是的话，可能是 https://www.yuque.com/kenshin/simpread/fcw60u 造成的（内含解决方案）
> 
> 一个提示，在 QA 时（跟简悦无关），建议不要使用 **不行** **重启** 这类有歧义的词汇，建议直接描述，如：`不行的具体现象`，`重启是指什么？具体现象`。
> 
> 这样能节省用户（你）很多时间~

好的，谢谢大佬，我装了插件之后，又按照配置库的方式配置了一遍，现在新增的页面是自动导出到logseq的pages里面了，但是之前中断的时间，我剪裁的几篇文章，有办法手动触发这个导出吗，我通过稍后读导出的md，和自动导出的格式不一样

**Comment by Kenshin** [comment]
> 我通过稍后读导出的md

根据 https://github.com/Kenshin/simpread/issues/6363#issuecomment-1991087999 把第一个图的内容复制给第二个图，然后通过第二个图手动导出。

或者需要重新生成的标注的原网页，进入阅读模式后再随便增加一个标注。
