### ISSUE TITLE
Windows下导出时文件名包含特殊字符无法导出

### ISSUE THREAD

**Issue by windingblack** [Kenshin/simpread#6365]
### 描述这个错误

在自定义导出标题中, 只有少数的几个关键字, 此处没有{{note}}关键字: http://ksria.com/simpread/docs/#/%E5%AE%9A%E5%88%B6%E5%8C%96%E5%AF%BC%E5%87%BA?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%af%bc%e5%87%ba%e6%a0%87%e9%a2%98
![image](https://github.com/Kenshin/simpread/assets/152348204/52510616-839a-483b-874f-1dde2e80708e)
因此在Windows下若遇到标题包含某些特殊字符, 由于文件名的限制将无法生成文件, 而由于不包含note关键字, 也难以修改文件名, 比如如下页面, 标题包含双引号无法导出: https://unix.stackexchange.com/questions/209123/understanding-ifs-read-r-line

### 复现步骤

* https://unix.stackexchange.com/questions/209123/understanding-ifs-read-r-line
* Windows下如果使用了{{title}}关键字, 任意格式的导出, 都将失败

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

https://unix.stackexchange.com/questions/209123/understanding-ifs-read-r-line

**Comment by Kenshin** [comment]
我看到你 Close Issues 了。

提示下，安装这个插件 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 即可解决~
