### ISSUE TITLE
退出chrome浏览器后，简悦账户就退出锁定了，重新进入浏览器后，需要重新登录设置简悦

### ISSUE THREAD

**Issue by yyerica** [Kenshin/simpread#6367]
### 描述这个错误

退出chrome浏览器后，简悦账户就退出锁定了，重新进入浏览器后，需要重新登录设置简悦

### 复现步骤

退出chrome浏览器后，简悦账户就退出锁定了，重新进入浏览器后，需要重新登录设置简悦，简悦里稍后读文章标注也无法同时同步到obsidian。

### 操作系统

Windows

### 浏览器

chrome浏览器 版本 122.0.6261.112

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#account

**Comment by yyerica** [comment]
是的，是关闭浏览器，刚刚又重新试了一下，重新进入浏览器后，需要重新登录设置简悦，没有提示。
我只在这台电脑的chrome浏览器登录了简悦，昨天绑定高级账户后还有设置了同步，之后每次关闭浏览器后再开浏览器就得重新登录简悦，然后还得重新设定之前的设置。









今天重新登录设置了几次不知道怎么就好了，谢谢您。


就是昨天设置好的obsidian 配置库高级 同步今天又不能用了，我自己再琢磨一下吧。


653840229
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 上午7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 退出chrome浏览器后，简悦账户就退出锁定了，重新进入浏览器后，需要重新登录设置简悦 (Issue #6367)





  
退出chrome浏览器
  
指关闭浏览器？
  
重新进入浏览器后，需要重新登录设置简悦
  
简悦具体提示什么？截图给我看下。
 
 
使用 https://www.yuque.com/kenshin/simpread/sw4m21 就可以重新授权为高级账户，同时如果用户不主动解绑的话，关闭和重开浏览器并不会改变高级账户状态。

**Comment by Kenshin** [comment]
如果要上传截图的话，请不要通过 Email 回复，请进入 https://github.com/Kenshin/simpread/issues/6367 回复。

***

因为没有看到截图，忙猜下你遇到的问题，估计是：

使用了同步助手的自动同步，但发现配置（插件配置）无法保存？如果是的话，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u

***

> 关于你提到的登录

具体是指什么？请截图说明下~

**Comment by yyerica** [comment]
昨天继续折腾了半天和ob的联动差不多配置好了，是的，是网页端的设置和同步助手的设置有冲突的地方，所有关闭浏览器后账户自动锁定了。




653840229
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 退出chrome浏览器后，简悦账户就退出锁定了，重新进入浏览器后，需要重新登录设置简悦 (Issue #6367)





 
如果要上传截图的话，请不要通过 Email 回复，请进入 #6367 回复。
 
 
因为没有看到截图，忙猜下你遇到的问题，估计是：
 
使用了同步助手的自动同步，但发现配置（插件配置）无法保存？如果是的话，解决方案 https://www.yuque.com/kenshin/simpread/fcw60u
 
  
关于你提到的登录
  
具体是指什么？请截图说明下~

**Comment by Kenshin** [comment]
okay 配置好就行。

有任何问题随时 Issues 沟通~
