### ISSUE TITLE
输入秘钥后没有反应

### ISSUE THREAD

**Issue by awwnone** [Kenshin/simpread#6368]
### 描述这个错误

在爱发电购买高级账户功能后，私信收到秘钥，输入之后谷歌浏览器整个卡住闪退，或者提示后台服务器错误

### 复现步骤

![Snipaste_2024-03-12_21-08-52](https://github.com/Kenshin/simpread/assets/69623108/bb51cef9-13d5-4664-b2d0-bde2f363ff56)
![Snipaste_2024-03-12_21-13-33](https://github.com/Kenshin/simpread/assets/69623108/7b01e305-4baa-4f34-9c53-22b857c63009)

### 操作系统

win10专业版

### 浏览器

Chrome 122.0.6261.112（正式版本） （64 位）

**Comment by Kenshin** [comment]
第二个截图就有解决方案。

或者看这里 https://www.yuque.com/kenshin/simpread/tmmwhl
