### ISSUE TITLE
语雀文档导出问题

### ISSUE THREAD

**Issue by Javennewbie** [Kenshin/simpread#6369]
### 描述这个错误

不知道是不是语雀加密文档的问题，我进入阅读模式以后， 同步助手的相关参数已经设置好，使用导出离线html功能时导出的html中图片无法显示，导出离线markdown和pdf也是同样的问题，我尝试使用导出PNG功能，提示失败，是试验性功能，请问还有其他可以尝试的方法吗？

### 复现步骤

![pro1](https://github.com/Kenshin/simpread/assets/39542960/95ed3c8f-c8b0-4052-8f59-a0505a80ed72)
![pro2](https://github.com/Kenshin/simpread/assets/39542960/c49bd8d1-ee17-436a-9172-14376014b98f)

### 操作系统

Windows

### 浏览器

Chrome 122.0.6261.70

### 发生问题的网址

语雀加密文档

**Comment by Kenshin** [comment]
嗨，你可以先安装 https://github.com/Kenshin/simpread/discussions/4380 这个插件。（跟这个问题无关，只是用来增强语雀的阅读模式效果）

虽然是加密文档，但：

1. 离线 HTML 应该没问题，所以离线 Markdown 理论上也没问题。
2. PNG 肯定不行
3. PDF 可以试试 https://github.com/Kenshin/simpread/discussions/3887 （我不确定是否可以）

**Comment by Kenshin** [comment]
> 离线HTML和离线Markdown确实存在图片无法显示的问题

emmm 那就是你提到的问题，因为是「加密」造成的。目前这种方式暂时没有任何解决方案，严格意义上说也有解决方案，但因为简悦会尊重每个页面的规则，不会强制性使用某种技术手段「破坏」。

PS：你可以理解这个页面有图片「防盗链」功能。

> wkhtmltopdf

因为浏览器打印的方式不会触发防盗链机制，所以此方式没问题，但其它方式都会触发这种所以无法使用。

PS：我关闭这个 Issues 了，有任何问题仍可随时在这里讨论~
