### ISSUE TITLE
有错别字 可能会影响用户理解 为知笔记 ？

### ISSUE THREAD

**Issue by TIM952597205** [Kenshin/simpread#637]
**小提示**

> 简悦已经服务 70K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
你说的是「为知笔记」是错别字？
https://www.wiz.cn/zh-cn
值得你拥有。
