### ISSUE TITLE
使用简悦同步助手导出功能 显示调用失败

### ISSUE THREAD

**Issue by dadada666888** [Kenshin/simpread#6370]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/119058998/8a4a76fe-0248-48b9-a1cc-6121d04e7c15)

### 复现步骤

pdf md epub 导出皆显示此问题 png可正常导出

### 操作系统

windows11

### 浏览器

Microsoft Edge 版本 122.0.2365.80 (正式版本) (64 位)

### 发生问题的网址

https://pincong.rocks/question/64280  任意网址

**Comment by Kenshin** [comment]
估计是没有安装 https://simpread.ksria.cn/plugins/details/tMGXrU1v0U 造成的。
