### ISSUE TITLE
关于 Notion 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6371]
感谢 ！  还有个问题需要解决

notion 现在安装完站点集市后，阅读模式显示目前来看是正常的，但是使用“复制到原文”内容会缺失，没法用zotero保存完整的内容。

_Originally posted by @SrSh-notme in https://github.com/Kenshin/simpread/issues/1737#issuecomment-1996763032_

**Comment by Kenshin** [comment]
@SrSh-notme

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

> 复制到原文

是指什么？最好截图给我看下。

**Comment by SrSh-notme** [comment]
![image](https://github.com/Kenshin/simpread/assets/48594308/992063e2-95b7-4757-a7a7-ba91478b5fc9)

点击“复制到原文” notion上面的文章显示不全。如下图所示
![image](https://github.com/Kenshin/simpread/assets/48594308/4d2ede49-3b84-4d1b-9791-abeb4d591852)

**Comment by SrSh-notme** [comment]
复制到原文的目的是向把网页保存的到zotero

**Comment by Kenshin** [comment]
明白你的意思了...

<img width="796" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/664c56ff-7367-4914-9365-27bf72d02c7c">

这些内容属于 Notion 独有的结构以及评论等，复制到原文有可能失效。

这不算是 Bug 因为只仅只是 Notion 的情况，跟 Live Editor 无关，不过你可以给我上图的 URL 我看下能否有什么办法解决。

**Comment by SrSh-notme** [comment]
> 明白你的意思了...
> 
> 
> 
> <img width="796" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/664c56ff-7367-4914-9365-27bf72d02c7c">
> 
> 
> 
> 这些内容属于 Notion 独有的结构以及评论等，复制到原文有可能失效。
> 
> 
> 
> 这不算是 Bug 因为只仅只是 Notion 的情况，跟 Live Editor 无关，不过你可以给我上图的 URL 我看下能否有什么办法解决。

[notion文章](https://www.notion.so/ouranswers/161d87bc0c97416cbbd8c0ebb3ab134c?pvs=4)

还有个思路，有没有可能简悦阅读模式下 能够屏蔽 notion 的评论 太花哨 又关不了

或者说曲线解决 极速版的稍后读 再简洁点 把底部的语音开关 有个选项能关掉

**Comment by Kenshin** [comment]
你给我的链接无法访问 😂

> 能够屏蔽 notion 的评论 太花哨 又关不了

评论是看不到的，但这些「黄色背景条」是可以出现在阅读模式上的。

>  极速版的稍后读 再简洁点 把底部的语音开关 有个选项能关掉

极速版稍后读可以使用 Live Editor 修改页面的内容。

**Comment by SrSh-notme** [comment]
> 你给我的链接无法访问 😂
> 
> > 能够屏蔽 notion 的评论 太花哨 又关不了
> 
> 评论是看不到的，但这些「黄色背景条」是可以出现在阅读模式上的。
> 
> > 极速版的稍后读 再简洁点 把底部的语音开关 有个选项能关掉
> 
> 极速版稍后读可以使用 Live Editor 修改页面的内容。

连接估计得邀请 😢   才能访问...........  

极速版没有Live editor 的选项
https://github.com/Kenshin/simpread/issues/6371#issuecomment-2006399120

**Comment by Kenshin** [comment]
可以使用 Live Editor

<img width="606" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0a854176-da99-4762-819e-a7b5b6c5d2ae">

注意下图

<img width="415" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f9799357-6c90-4a30-9001-bd7a70c624fb">
