### ISSUE TITLE
印象笔记授权

### ISSUE THREAD

**Issue by mychan14** [Kenshin/simpread#6372]
### 描述这个错误

一直授权失败

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/28038980/8cbc4e64-f71c-4f65-8e18-6e2003d54b3d)

### 操作系统

win

### 浏览器

edge最新版

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

**Comment by Kenshin** [comment]
嗨，确实存在授权问题，不建议使用印象笔记了，建议使用更现代的笔记 e.g. Notion Obsidian 等。
