### ISSUE TITLE
Mac系统下简悦同步助手窗口无法显示

### ISSUE THREAD

**Issue by jidewohhr** [Kenshin/simpread#6374]
### 描述这个错误

1、Mac系统版本14.4
2、同步助手版本1.2.0
3、问题描述：最近不知为何点击同步助手图标，无法显示窗口界面（后台应该还在正常运行）；到application下点击，偶尔会出现弹窗窗口，但过几秒就会消失。再进入包内容下/Users/huarong/Downloads/mac/简悦 · 同步助手.app/Contents/MacOS/简悦 · 同步助手，点击命令行图标，可以打开终端，显示信息如下：
<img width="843" alt="Snipaste_2024-03-15_10-32-37" src="https://github.com/Kenshin/simpread/assets/75867549/94ccf28b-505f-4f16-8326-6e21614f6ac2">

以下是ChatGPT的答案。但我无法解决，求助大大。

这条日志信息是关于 macOS 上的一个软件冲突问题。从提供的信息来看，涉及到的是 WebKit（一个用于渲染网页的框架）和一个名为“简悦 · 同步助手”的应用程序。具体来说，问题出现在两个不同的动态链接库（dylib）中都实现了名为 WebSwapCGLLayer 的类。这两个库分别是：

/System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib
/Applications/简悦 · 同步助手.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib
当这种情况发生时，系统不确定应该使用哪一个实现，这可能导致不稳定或异常行为，如应用程序突然退出。

### 复现步骤

1、Mac系统版本14.4
2、同步助手版本1.2.0

### 其他相关说明

无

### 操作系统

MacOS 14.4

### 浏览器

和浏览器无关

### 发生问题的网址

无

**Comment by Kenshin** [comment]
emmm 有点奇怪（麻烦）😂

> 点击同步助手图标

点击的 Dock 上的图标？还是 Menubar 上的？

一般来说是指后者，如果是后者的话，连菜单也无法显示吗？

**Comment by jidewohhr** [comment]
dock上的和启动台上的图标点击都没有反应。不会出现任何窗口（当然菜单也无法出现）。只有通过访达访问application文件夹下点击『简悦 · 同步助手』，会出现以下正常程序窗口，但10秒左右又消失了。
<img width="697" alt="Snipaste_2024-03-15_13-04-03" src="https://github.com/Kenshin/simpread/assets/75867549/9b0c668d-ae0a-4cc2-a909-66556f5b05f7">

**Comment by Kenshin** [comment]
你 Closed 这个 Issues 是因为解决了？

PS：如果没有解决试试当出现此窗口时，点击重置当前配置。

**Comment by jidewohhr** [comment]
大神，没有解决呢，Closed这个Issues是我误操作了，好像不能恢复。

**Comment by jidewohhr** [comment]
我今天在另一台电脑上怎么都不能打开程序窗口了。通过终端模式打开，显示如下命令行。
![Snipaste_2024-03-19_21-06-31](https://github.com/Kenshin/simpread/assets/75867549/f18fe932-cd66-4ae6-8a02-c39d4c5d0a73)
请教ChatGPT，给了我以下建议：
你遇到的提示信息涉及到几个不同的方面，我来逐一解释一下它们的含义和可能需要采取的措施：

- [ ] body-parser deprecated warnings: 这些警告表明你使用的软件（简悦同步助手）内部使用了body-parser中间件的某些已弃用的方法。具体而言：

使用individual json/urlencoded middlewares: bodyParser整体用法已被弃用，现在推荐使用express.json()和express.urlencoded({extended: true/false})两个独立的中间件来代替。
undefined extended: provide extended option: 当使用urlencoded中间件时，应明确提供extended选项。extended选项决定了当解析URL编码的数据时使用的库（true使用qs库，false使用querystring库）。
这些问题需要软件的开发者更新他们的代码来解决。作为用户，你可以尝试联系开发者报告这个问题，但这不会影响你立即使用软件的能力。

- WARNING: Secure coding is not enabled for restorable state: 这个警告指的是macOS应用的一个安全编码特性没有被启用。安全编码可以帮助防止恶意数据在应用恢复状态时被执行。这同样是一个开发者需要关注并解决的问题，通过实现NSApplicationDelegate的applicationSupportsSecureRestorableState:方法并返回YES来启用。

- Class WebSwapCGLLayer is implemented in both...: 这个警告说明WebSwapCGLLayer类在两个不同的库中都有实现，但是系统将只使用其中一个。这通常是由于软件中包含的一些库重复或者与系统库产生了冲突。虽然这个问题可能不会立即导致错误，但它增加了运行时问题的风险。

- SimpRead sync started and listening on port 7026: 这是一个信息性日志，表明简悦同步助手已经成功启动并在7026端口监听同步请求。这意味着你的同步服务是正常工作的。

**Comment by Kenshin** [comment]
我也不清楚为什么有这种问题，确实也有人反馈过，但都是个例，算上你估计不到五个人 😂

你看看 `7026` 端口是否被占用（即便被占用也不会有这个问题...
