### ISSUE TITLE
无法同步到obsidian，需要在插件中点一下的问题

### ISSUE THREAD

**Issue by zqz365001** [Kenshin/simpread#6375]
### 描述这个错误

使用了一段时间，就出错了，然后重新设置简悦，现在问题基本都解决了，但是同步到obsidian中，无法自动同步，需要在obsidian插件中手动点一下同步。如下图
![image](https://github.com/Kenshin/simpread/assets/27180737/d7f977cd-98c8-4826-ae11-904e72ea1b3d)
![image](https://github.com/Kenshin/simpread/assets/27180737/df1b1ef0-fc40-40fa-9874-8e6b0009e9d4)

### 复现步骤

请问如何解决呢？

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/61303678

**Comment by Kenshin** [comment]
> 同步到obsidian中，无法自动同步

emmm

先确保操作正确：在阅读模式下（非稍后读），然后使用快捷键 `d d` 加入稍后读后，再标注会自动同步。（如果已经加入稍后读则不用重复加入 😂

然后看下你的 导入到 Obsidain 与配置库 https://www.yuque.com/kenshin/simpread/wq35mh 有什么区别，主要是：

- 导入到 Obsidian 插件
- Markdown 模板辅助增强插件

这两个插件。

最后，确保你的 Obsidian 仅存在一个实例，并且打开 http://localhost:7027/ 如下图所示说明 Obsidian 服务启动正确。

<img width="327" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7d083fa5-8049-4a50-a2ba-23c7426d1ab5">

**Comment by Kenshin** [comment]
> 记得以前是进入到阅读模式，然后直接开始标注，就会自动同步到obsidian

是你记错了，一直都是我说的方案。

> 现在用一段时间，1962就出问题了

把配置文件 Email 给我，我看下。

**Comment by zqz365001** [comment]
您好，已经邮箱发送了 .  wesun@gmail.com

**Comment by Kenshin** [comment]
okay 我下午看下～

**Comment by Kenshin** [comment]
我没有权限打开你给我的配置文件，所以...

请将配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6375

PS：我记得给过你这个地址。😂

**Comment by zqz365001** [comment]
好的，已经发到邮箱了。zqz365011#qq.com (#->@)

**Comment by Kenshin** [comment]
我看了下你给我的配置文件里面没有插件配置，因为你上次就遇到了问题，建议方便的话可以「自己修复」。

我简单的跟你说下如何方便快速排查。

***

标注自动导入到 Obsidian 依赖下面三个模块：

1. 简悦在 Obsidian 插件中的服务正常启动。（可以使用 http://localhost:7027/ 查看是否正常启用）

2. Markdown 模板辅助增强插件里面是否存在模板。（可以打开此插件，然后点击「测试」看下是否正常生成）

3. 导入到 Obsidian 相关设置是否正确。（可通过 [配置库](https://www.yuque.com/kenshin/simpread/wq35mh) 对比得知）

如果在阅读模式下手动导入标注正常（说明上面三点设置正确），但标注后无法自动导入，一般是：

1. 可能是顺序有错误，正确的方式是：进入阅读模式，使用快捷键加入稍后读，然后再标注（仅限没有加入稍后读的页面）

2. 如上条没问题，则看下【自动化辅助增加插件】相关设置是否正确（可通过 [此教程](https://www.yuque.com/kenshin/simpread/ifioux#sIr9r) 对比得知）留意下图


    <img width="865" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/7edcc010-c34a-48d1-8cef-d2e22f9c4afa">


***

如果你的插件配置没有正常保存到 `simpread_config.json` 但发现阅读模式下插件的信息是全的，可以使用【插件管理器】的[手动保存配置](https://www.yuque.com/kenshin/simpread/fcw60u#dda4f3db) 方式。

**Comment by Kenshin** [comment]
补充下，我把这些排查错误汇总到了 https://www.yuque.com/kenshin/simpread/fr8zo5#I5D5O 你可以针对的看下。

**Comment by zqz365001** [comment]
配置都正确，原来是卡在 空格上面 😅。

谢谢你

**Comment by Kenshin** [comment]
哈，解决就好，我关闭这个 Issues 了 👍

***

PS：不知道是否好评了，如果没有的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
