### ISSUE TITLE
获取时出现了问题导致仅成功获取了第一个NotionPage

### ISSUE THREAD

**Issue by DFBlowing** [Kenshin/simpread#6377]
### 描述这个错误

请注意：获取时出现了问题导致仅成功获取了您的第一个NotionPage虽然不影响导出服务，但建议提Issues
![image](https://github.com/Kenshin/simpread/assets/158026372/8a6aafd2-4681-43e1-a717-7a653313fdc0)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/158026372/ef8edd6e-1d80-45ed-8f8d-e64973d3fb4b)

### 操作系统

Windows 11

### 浏览器

Edge 123.0.2420.41

### 发生问题的网址

https://zhuanlan.zhihu.com/p/672448565#:~:text=1%20%E9%A6%96%E5%85%88%E6%89%93%E5%BC%80%E4%B8%80%E4%B8%AANotion%E9%A1%B5%E9%9D%A2%EF%BC%8C%E7%94%A8%E4%BA%8E%E5%AD%98%E6%94%BE%E5%AF%BC%E5%85%A5%E5%90%8E%E7%9A%84%E8%A1%A8%E6%A0%BC%EF%BC%9B%202%20%E5%9C%A8Notion%E5%B7%A6%E4%BE%A7%E5%AF%BC%E8%88%AA%E6%A0%8F%E7%9A%84%E6%9C%80%E4%B8%8B%E6%96%B9%EF%BC%8C%E6%89%BE%E5%88%B0%E5%B9%B6%E7%82%B9%E5%87%BB%20Import%20%E6%8C%89%E9%92%AE%EF%BC%9B%203,%E5%9C%A8%E5%BC%B9%E5%87%BA%E7%9A%84%E7%AA%97%E5%8F%A3%E4%B8%AD%E9%80%89%E6%8B%A9%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E4%B8%BA%20CSV%20%EF%BC%9B%204%20%E9%80%89%E6%8B%A9%E8%A6%81%E5%AF%BC%E5%85%A5%E7%9A%84Excel%E6%96%87%E4%BB%B6%E7%84%B6%E5%90%8E%E7%82%B9%E5%87%BB%E2%80%9C%E6%89%93%E5%BC%80%E2%80%9D%EF%BC%9B%205%20Excel%E6%96%87%E4%BB%B6%E5%B0%86%E4%BC%9A%E4%BB%A5%E8%A1%A8%E6%A0%BC%E5%BD%A2%E5%BC%8F%E5%87%BA%E7%8E%B0%E5%9C%A8Notion%E9%A1%B5%E9%9D%A2%E5%BD%93%E4%B8%AD%E3%80%82

**Comment by Kenshin** [comment]
这算是正常情况…你可以使用第一个截图的里面的说明（加 Pin）的方式解决。

**Comment by Kenshin** [comment]
补一张图

<img width="666" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4fc54c0b-39b8-4f6a-8bfc-48dd6f1bc6e7">

另外，关于 Notion 的相关问题请看这里 https://www.yuque.com/kenshin/simpread/wwk65u 以及 https://github.com/Kenshin/simpread/issues/6259
