### ISSUE TITLE
知乎的数学公式无法显示

### ISSUE THREAD

**Issue by DFBlowing** [Kenshin/simpread#6378]
### 描述这个错误

页面打开阅读模式后，知乎的公式只有部分可以显示

### 复现步骤

无

### 操作系统

windows 11

### 浏览器

edge 123.0.2420.41 (正式版本) 

### 发生问题的网址

https://zhuanlan.zhihu.com/p/38573924

**Comment by DFBlowing** [comment]
![image](https://github.com/Kenshin/simpread/assets/158026372/53bdbf97-1ebd-4c1c-bb73-c932fc570297)

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2861 下图效果

<img width="1814" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6a3de729-a062-4126-8aba-db8dd337bdac">
