### ISSUE TITLE
插件触发器图标显示口，并且点击无反应

### ISSUE THREAD

**Issue by 404luke** [Kenshin/simpread#6379]
### 描述这个错误

插件触发器前几天图标显示口，但还可以点击，今天直接没有反应了，所有网页都试过都不行，我试过重安插件，导入备份配置也不行。
![PixPin_2024-03-18_10-18-12](https://github.com/Kenshin/simpread/assets/69250686/f1565753-5a9b-4891-8ea2-ff0cc6283328)

### 复现步骤

1.等插件变红
2.点击插件进入阅读模式
3.鼠标指向浮动界面
![PixPin_2024-03-18_10-21-53](https://github.com/Kenshin/simpread/assets/69250686/96059a8f-eee5-4cbd-9efa-7aeb47dfc226)

4.鼠标指向动作
5.点击插件触发器无反应

![PixPin_2024-03-18_10-18-12](https://github.com/Kenshin/simpread/assets/69250686/9d535d12-54fa-4e2c-98e8-dd91e36f9d0d)

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MzU4MDUyMDQyNQ==&mid=2247529770&idx=1&sn=933dd8052261e588cd1dd157767964d3&sessionid=1710465940#rd

**Comment by Kenshin** [comment]
如果在公众号下访问的话，确实会出现下图的情况，算是预期情况。

<img width="274" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/23671bdc-799c-4e9a-9e5f-1966a48eaaaa">

但上图这些图标是可以点击的，你是无法点击吗？

你可以试试：

1. 在其它页面 e.g. https://sspai.com/post/69972 能否点击这些图标

2. **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

3. 是否使用了同步助手的自动同步功能，如果是的话，请先确保运行了同步助手。

如果确定是点击红框中的 Icon 无反应的话

<img width="247" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/924e8e26-57ad-477c-88bc-8b6836ec7f87">

右键 → 检查，按下图所示打开它

<img width="495" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/86317972-ed74-4c44-a191-222d83459991">

然后在点击这些图标，看下是否有错误信息，如果有的话，截图给我。

**Comment by 404luke** [comment]
在其它页面 e.g. https://sspai.com/post/69972  是正常的。
隐身模式下仅启用简阅，公众号下还是不行，插件触发器任一条目都点击无反应，控制台没有任何输出，
![PixPin_2024-03-18_11-09-33](https://github.com/Kenshin/simpread/assets/69250686/b14cb197-6f3d-4c9c-b94b-4400ebc3eb7f)
公众号下其他功能是好的，仅仅插件触发器有问题。

**Comment by 404luke** [comment]
测试到这个公众号功能正常，图标不显示（预期情况）https://mp.weixin.qq.com/s/-2qnIWqWDbfCLBCAPRUjdw

**Comment by Kenshin** [comment]
> 在其它页面 e.g. https://sspai.com/post/69972 是正常的。
> 隐身模式下仅启用简阅，公众号下还是不行，插件触发器任一条目都点击无反应，控制台没有任何输出

是某个特定的公众号链接无法使用插件触发器下面的功能吗？按照你截图的例子，无法打开 **导入到 Obsidian 选项** 是吗？

同时我测试了 https://github.com/Kenshin/simpread/issues/6379#issuecomment-2002851416 提到的 URL 是没问题的。

如果只是某个特定的 URL 那暂时没有办法，你可以提供下这个 URL 我看下。

PS：你可以使用 https://github.com/Kenshin/simpread/discussions/5851 这个插件来增强公众号的使用体验（跟此问题无关，只是提示下）

**Comment by 404luke** [comment]
https://mp.weixin.qq.com/s?__biz=MzU4MDUyMDQyNQ==&mid=2247528881&idx=1&sn=9cdb0970fc29b9e1ab633fec5db9fd7e
https://mp.weixin.qq.com/s?__biz=MzU4MDUyMDQyNQ==&mid=2247528545&idx=1&sn=33e8e1cf8e27d68ebca96a5f14f240c5
这个公众号 小哈学Java，下面的文章我这边测都不行，插件触发器这个模块整个都没反应。目前就碰见这一个公众号不行，其他公众号倒是正常的。

**Comment by Kenshin** [comment]
emmm

我看了下，这个页面跟简悦（在代码上）有冲突导致的，因为也有用户提过类似的情况（印象中也是公众号），但基本上都是个例。

基本上暂时无解 😂  所以我关闭这个 Issues 了

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
