### ISSUE TITLE
infoQ写作社区无法解析

### ISSUE THREAD

**Issue by Abner1zhou** [Kenshin/simpread#6380]
### 需要适配的新站

https://xie.infoq.cn/article/79dc75b0a70f20f9cce643248

**Comment by Kenshin** [comment]
我这边没有问题

<img width="1640" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/16dc4563-5bf9-4682-a9d5-190aedac2100">

留意下下这里

<img width="442" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cb0f0d67-4c98-44e3-af9a-854f1f908465">

也可以试试 https://github.com/Kenshin/simpread/discussions/3340 提到的一些方案。
