### ISSUE TITLE
保存到notion出现授权错误

### ISSUE THREAD

**Issue by zhaoxian-afra** [Kenshin/simpread#6384]
### 描述这个错误

在所有授权都成功的前提下，保存文章时反复出现“授权已过期请重新授权”的提示，自动跳转到授权页面提示授权成功之后，到保存文章页面没有解决授权的问题。反复出现此错误。按照issue提示登出过notion，重新安装过简悦，都没能解决。我检查过我的授权没有错误。

### 复现步骤

就是正常操作，详细见截图。

### 其他相关说明

[截图.zip](https://github.com/Kenshin/simpread/files/14637430/default.zip)
我不知道怎么上传图片失败了，压缩了一下。
拜托了真的很想导入成功。我的notion账户没有问题，我先用官方插件收藏了该网址，按照简悦提供的模板修改了，再收藏，notion增强的标签导入一切都如常，问题出在没能正常导入notion。还是授权问题。不知道有没有cookie上的问题，我把拦截插件都卸载了。至于查看控制台，我不太会看，报错应该是：Failed to load resource: the server responded with a status of 401 ()

### 操作系统

Arch Linux

### 浏览器

Google Chrome 版本 122.0.6261.128（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/post/70397

**Comment by Kenshin** [comment]
嗨，建议方便的话可以录屏给我看下。

你的问题确实有点奇怪，感觉大概率是操作问题造成的。

**Comment by Kenshin** [comment]
我看了你的视频 😂 显然是操作有问题：

**不要在选项页 → 服务里面授权 Notion** 而是在插件端里面设置

![image](https://github.com/Kenshin/simpread/assets/81074/658de951-2bdc-42a9-aa21-cc927158ae7c)

使用时，请使用快捷键 `n t` 或者下图方式

<img width="450" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9069fdf4-6e55-4705-883f-7f0423be9dd6">

**Comment by Kenshin** [comment]
补充下，关于这个功能请看下 https://github.com/Kenshin/simpread/discussions/4954 的说明

PS：你的操作不知道是看了哪个教程，如果能找到这个教程的话，请告诉我下

**Comment by zhaoxian-afra** [comment]
你好！“不要在选项页 → 服务里面授权 Notion 而是在插件端里面设置”，已尝试，和此前情况如出一辙。
PS：我此前的操作是按照https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358的方案一和二进行的。至于我录屏里面的操作，我只是告知错误。表示其他地方都是授权成功，但是导入时仍不能授权。

**Comment by Kenshin** [comment]
> 我此前的操作是按照https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-1703358的方案一和二进行的

这个链接里面并没有让你在选项页授权 😂

> 已尝试，和此前情况如出一辙。

新注册一个 Notion 也不行吗？你使用的是正常的 Chrome 浏览器吗？

**Comment by Kenshin** [comment]
还有个办法，你可以新注册一个 Notion 账户，然后将账户、密码以及你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6384

然后在这里回复我，我帮你配置下。
