### ISSUE TITLE
简悦插件和screenshade不兼容

### ISSUE THREAD

**Issue by iamYZ94** [Kenshin/simpread#6386]
### 描述这个错误

今天第一次使用简悦，在体验过程中，发现使用阅读模式下，网页显示白屏。
经过查看帮助中心帖子，发现之前有反馈到简悦和screenshade不兼容问题：https://github.com/Kenshin/simpread/issues/4802
我自己尝试暂停screenshade之后，再使用简悦阅读模式，发现页面可以正常运行。
请问这个兼容问题是否解决了呢？

### 复现步骤

screenshade不关闭之前，简悦阅读模式显示白屏。
screenshade关闭后，简悦阅读模式正常。
![QQ截图20240319152230](https://github.com/Kenshin/simpread/assets/163983616/99ad2a0f-9468-4c08-a3ff-4e6f57fafbc0)
![QQ截图20240319152458](https://github.com/Kenshin/simpread/assets/163983616/3a29b1c0-7184-48b3-ba61-8a388524134d)

### 操作系统

Windows 11

### 浏览器

Google

### 发生问题的网址

https://mp.weixin.qq.com/s?__biz=MzI0ODIyNjU0OA==&mid=2247485665&idx=1&sn=675eedf43a64326e968d6a645394d2af&chksm=e9a2bf7aded5366cb80f2af4864ebd78b19f42214f4173660b4f75dc12df1d3aefe25c035548&mpshare=1&scene=23&srcid=0319x4MIFFQADHyhnLa6ZK0f&sharer_shareinfo=c6d377cbd3c19aedb115262aa9a16815&sharer_shareinfo_first=c6d377cbd3c19aedb115262aa9a16815#rd

**Comment by Kenshin** [comment]
嗨，这种问题没法解决 😂 因为根本不是简悦的问题...

简悦的阅读模式不会干扰原文，你可以理解新建了一个「层」，但 screenshade 对全局（这点很「霸道」）都有影响。
