### ISSUE TITLE
导出pdf失败，显示“此功能是实验性功能”

### ISSUE THREAD

**Issue by symphony-ciel** [Kenshin/simpread#6387]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/163986217/369605eb-c87e-4436-972e-942095b497bf)
![屏幕截图 2024-03-19 153850](https://github.com/Kenshin/simpread/assets/163986217/e6df494d-2de4-4601-8d1c-4721bfeb76f9)
想要导出pdf，显示“导出失败，此功能是实验性功能”，已下载简悦·同步助手，并配置

### 复现步骤

导出pdf，显示“导出失败，此功能是实验性功能”，已下载简悦·同步助手，为高级用户

### 操作系统

Windows11

### 浏览器

edge

### 发生问题的网址

https://www.douban.com/group/topic/223119526/?_i=0832955jpJ5FGg,0833511jpJ5FGg

**Comment by Kenshin** [comment]
一般来说，如果经常使用 PDF 功能的话，请使用 https://github.com/Kenshin/simpread/discussions/3887 方案（需要同步助手）

如果只是轻量级使用的话，直接浏览器打印就好。

PS：你可以试试其它页面是否也存在这个问题，如果其它页面没问题的，就这个 URL 基本上可以忽略（或使用我告诉你的方案基本上可以解决）

**Comment by symphony-ciel** [comment]
好的，谢谢！试了下其他页面是可以导出的，好像就豆瓣这个不行

**Comment by Kenshin** [comment]
okay 那就好 👍

某些网站会有类似图片防盗链的功能，而 PDF 导出类似这种方式所以会触发这些机制，PDF 高级打印方案也存在这个情况，但比你使用的方式更广泛性。

非要严格意义上说这种问题也能解决，但简悦的做法是：不强制性破坏任何网站的规则，默认是没有限制的肯定没问题，普通限制 PDF 高级打印方案可以解决，严格限制的话，就都不行了 😂

**Comment by symphony-ciel** [comment]
了解了，感谢解答！
