### ISSUE TITLE
market.zhihu.com 阅读模式的使用疑问

### ISSUE THREAD

**Issue by baby1128** [Kenshin/simpread#6392]
### 描述这个错误

第一个是知乎原文，第二个是切换阅读后的模式，我只框了几个、
请问是OCR的吗？错误率好高！
目前仅测试了这一个页面，其他应该相差不大。

### 复现步骤

![222](https://github.com/Kenshin/simpread/assets/31163874/e3580371-25c0-407c-81f8-ea1a99840b77)
![111](https://github.com/Kenshin/simpread/assets/31163874/09656c82-34bb-4967-b664-a950ecb845ac)

### 操作系统

Windows10

### 浏览器

Cent Browser版本 5.0.1002.354（正式版本） （32 位） (Portable) (Chromium 102.0.5005.167)

### 发生问题的网址

https://www.zhihu.com/market/paid_column/1632073760948555776/section/1635302453741293568?km_channel=search&origin_label=search

**Comment by Kenshin** [comment]
😂 知乎（各种奇怪）的页面怎么这么多...

我看了下这个页面：

1. 这个页面有阻止任何程序「注入」的功能（你可以理解这是简悦阅读模式使用的基础，虽然本质不是这样的，只是为了方便表述）

2. 这个页面是收费的（也就是有明确的知识版权）

简悦是不会主动适配这类页面的，除此之外还有：微信读书、百度文库等。

我关闭这个 Issues 了~
