### ISSUE TITLE
开启扩展后，无法查看下面提到的网站的内容

### ISSUE THREAD

**Issue by Sunsh4j** [Kenshin/simpread#6394]
### 描述这个错误

经过筛查，确认是简悦扩展导致，无法查看这个 [网址](https://www.bbc.com/zhongwen/simp/topics/ck2l9z0em07t) 的内容（该网站内的其余页面也无法查看）
已在多个浏览器上复现，结果均是如此

### 复现步骤

rt

### 操作系统

Win10

### 浏览器

chrome、edge

### 发生问题的网址

https://www.bbc.com/zhongwen/simp/*

**Comment by Kenshin** [comment]
嗨，可以试试这个解决方案 https://github.com/Kenshin/simpread/discussions/2347

细节的话，我明天再确认下。

**Comment by Kenshin** [comment]
嗨，我确认了就是这个问题，按照链接的提示就能解决，我关闭这个 Issues 了，有任何疑问随时在这里讨论~
