### ISSUE TITLE
新站适配：MSN 中国 new site

### ISSUE THREAD

**Issue by Cutiei** [Kenshin/simpread#6395]
### 需要适配的新站

https://www.msn.cn/zh-cn/news/other/hinton%E7%97%9B%E6%82%94%E6%AF%95%E7%94%9F%E5%B7%A5%E4%BD%9C-agi%E5%8D%81%E5%B9%B4%E5%86%85%E9%99%8D%E4%B8%B4%E6%88%96%E5%AF%BC%E8%87%B4-%E5%A5%A5%E6%9C%AC%E6%B5%B7%E9%BB%98-%E7%81%BE%E9%9A%BE-%E5%9B%BE%E7%81%B5%E5%B7%A8%E5%A4%B4%E8%81%94%E6%89%8B%E4%B8%AD%E5%9B%BD%E4%B8%93%E5%AE%B6%E4%B8%BAai%E5%88%92%E7%BA%A2%E7%BA%BF/ar-BB1kktrs?ocid=msedgntp&pc=NMTS&cvid=65fd8f9205b54ee0afdfbb84823c3ed9&ei=11

### 有需要请描述这个站的性质

来自EDGE浏览器默认起始页的新闻栏目，使用频率较高

**Comment by Kenshin** [comment]
okay 明天确认下。

你可以暂时使用 https://github.com/Kenshin/simpread/discussions/3340 提到的方案解决。

**Comment by Kenshin** [comment]
可以适配它，适配后我会在这里通知你~

**Comment by Kenshin** [comment]
嗨，MSN 这个站点已适配完毕。

#### 如何更新

https://github.com/Kenshin/simpread/issues/6541#issuecomment-2156314697

#### 效果如下

<img width="1806" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fad680a2-6978-4418-b403-0861690e74f0">

***

我关闭这个 Issues，有任何问题请在 https://github.com/Kenshin/simpread/issues/6541 讨论
