### ISSUE TITLE
开启 simpread 时，汇丰香港网页崩溃

### ISSUE THREAD

**Issue by zhoukuncheng** [Kenshin/simpread#6397]
### 描述这个错误

网页加载后，瞬间崩溃报错
  
- url: https://www.hsbc.com.hk/zh-cn/ways-to-bank/internet/
- Error code: STATUS_ACCESS_VIOLATION

### 复现步骤

1. 开启 simpread 扩展
2. 访问汇丰香港网页: https://www.hsbc.com.hk/zh-cn/ways-to-bank/internet/
3. 复现截图：  
![image](https://github.com/Kenshin/simpread/assets/5327960/0123d4d2-35ee-41b9-895f-d0148ddf1c6e)

### 操作系统

Window 11 23H2 22631 

### 浏览器

Chrome Version 123.0.6312.59 (Official Build) (64-bit)

### 发生问题的网址

https://www.hsbc.com.hk/zh-cn/ways-to-bank/internet/

**Comment by Kenshin** [comment]
嗨，我这边没问题

<img width="1310" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4eb4fc9b-39c8-4afb-847f-411f1e128a53">

估计是这个问题造成的，解决方案 https://github.com/Kenshin/simpread/discussions/2347
