### ISSUE TITLE
阅读模式中添加禁止点击空白就退出的选项

### ISSUE THREAD

**Issue by likemuuxi** [Kenshin/simpread#6399]
### 请描述你的建议或任何内容

阅读时，使用鼠标划来划去，会导致退出阅读模式，可能是点击阅读外面区域就退出阅读模式的逻辑导致，在设置中未找到相关选项，看到聚焦模式可以设置，希望阅读模式中也可设置是否启用点击空白退出功能

**Comment by likemuuxi** [comment]
确实用了  明天我搞下👍

**Comment by Kenshin** [comment]
哈，看来是搞定了~ 👍

**Comment by likemuuxi** [comment]
搞定了，感谢😆

**Comment by Kenshin** [comment]
小事情 😄

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by likemuuxi** [comment]
已评，简悦值得！

**Comment by Kenshin** [comment]
👍 😄
