### ISSUE TITLE
支持 hupu 论坛

### ISSUE THREAD

**Issue by zeyandeng** [Kenshin/simpread#64]
https://bbs.hupu.com/bxj

**Comment by Kenshin** [comment]
@zeyandeng 
改了名字， `1.0.2` 支持论坛类的页面，目前为测试版，将与 `1.0.3` 时一起发布，到时我会增加这个新站。

**Comment by Kenshin** [comment]
已适配~

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
