### ISSUE TITLE
BUG: 优化后的内容使用CTRL+S保存为mhtml 无法正确显示

### ISSUE THREAD

**Issue by 9k01** [Kenshin/simpread#640]
引起BUG原因，保存MHTML会强制 重新格式化 html 结构 把<sr-read> 加入到 body 里面

**Comment by Kenshin** [comment]
回头我测试下，看看什么问题。如果需要 HTML 的话，可以使用离线 HTML 功能，更方便些。

**Comment by Kenshin** [comment]
刚才测试了下，保存的 `mhtml` 会 **重新整理** `<html>` 标签中的的内容，导致失效。

结论：

1. 这不算是 Bug

2. 请不要使用此种方式。如需要请使用 **离线 HTML** 方式。

我将关闭此 issues 有需要请重新开启。 😀
