### ISSUE TITLE
关于微信公众号页面无法生成标注等问题

### ISSUE THREAD

**Issue by julian20220130** [Kenshin/simpread#6400]
### 描述这个错误

大概一周前出现如下情况：
1. 在浏览器（edge）中进入微信公众号页面，可以顺利进入阅读界面，但无法进行标注
2. esc 按键无法退出阅读模式
3. 其他网页能够正常标注和esc退出
4. 期间没有动过任何设置选项
5. 稍后读 的页面能够正常打开
6. 覆盖配置文件后依然无法解决该问题

### 复现步骤

1. 从微信浏览器点击默认浏览器打开，跳转到 edge 中打开了如下网址：https://mp.weixin.qq.com/s/DqQUBRZBJsgeuH57v1q2rQ
2. 由于设置了自动进入阅读模式，此时已经自动进入
3. 没有出现自动标注的侧栏，使用 esc 按键也无法退出阅读模式

### 操作系统

MacOS

### 浏览器

edge 最新版

### 发生问题的网址

https://mp.weixin.qq.com/s/DqQUBRZBJsgeuH57v1q2rQ

**Comment by Kenshin** [comment]
嗨，我测试了下是没问题的，进入阅读模式后使用快捷键 `d d` 加入稍后读，然后刷新此页面，进入阅读模式后仍稍后读。（本应如此）

不过，我跟你可能有个区别，即：我使用了 [微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 

1. 你可以试试安装我提到的这个插件能否解决？
2. 仅只是这一个页面？还是任意公众号均有此问题。

PS：阅读公众号建议使用 [此插件](https://github.com/Kenshin/simpread/discussions/5851) 来增强公众号的阅读模式效果。

**Comment by julian20220130** [comment]
抱歉似乎点了关闭回答？

**Comment by Kenshin** [comment]
> 抱歉似乎点了关闭回答？

没事 😄

> 现在的状况似乎是在所有微信公众号页面

试试**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by julian20220130** [comment]
谢谢作者，试过在隐身模式下开启了，恢复了正常。但遗憾的是在常规模式下，一个个关闭浏览器扩展的方式暂时还没有试出来是哪个扩展的干扰。总之谢谢！后续有结果的话再回评论区回复！再次感谢。

**Comment by Kenshin** [comment]
小事情。

一般用「二分法」来定位扩展比较快，关一半扩展，然后再关一半，以此类推。

我关闭这个 Issues 了，有问题随时联络我。

**Comment by julian20220130** [comment]
思路打开了！二分法是我从未想过的道路。这大概是工科和文科思维差别吗？
不过我最终找到了干扰的扩展，在此记录一下吧：supercpoy（破解无法复制页面）。取消在微信页面自启动的设置即可。
再次感谢！

**Comment by Kenshin** [comment]
哈，解决就好。 👍

二分法是排除法的一种「懒人」办法 😂

***

有可能的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by julian20220130** [comment]
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/a80181ac-5c37-4540-a85f-21f210cadcf2">
通过SimpRead 看微信公众号并保存标注的需求比较大，所以还是把这个 issue 发一下。
遇到一个新的问题是，极个别文章链接通过SimpRead 优化后出现了换行失效的情况，具体如图。
目前发现有两篇文章的链接是这样。
https://mp.weixin.qq.com/s/XNZsne5WdW7qhSG-MY_Nvw
https://mp.weixin.qq.com/s/TbmUke1amUyexs8-NJjMZw
有理由怀疑是公众号排版本身的问题，但开发大大看是否有方法优化？
插件安装了如下：
<img width="407" alt="image" src="https://github.com/user-attachments/assets/26e314b2-2548-4bdc-bd2c-b564417460e6">

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6400#issuecomment-2336516953

嗨，这两个链接确实有点奇葩 😂 所以解决方案是 反着来，即：将这两个 URL 加入到公众号辅助增强的排除列表

<img width="472" alt="image" src="https://github.com/user-attachments/assets/f4d4386c-437c-4e1e-9bc4-3d647efc48ed">

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/eda46bbd-8bcb-494c-a888-3cb2d9e3bcc4">

或者你也可以不自动使用，而是有优化需要的前提下：手动优化

<img width="463" alt="image" src="https://github.com/user-attachments/assets/38a1b6dd-589b-40ff-a86d-73cc1a2f68cd">

<img width="391" alt="image" src="https://github.com/user-attachments/assets/ad8e0deb-7664-4772-b530-df3a7b18d308">

**Comment by Kenshin** [comment]
另外，好奇问问，使用简悦标注后，是导出到某些笔记工具？还是？

**Comment by julian20220130** [comment]
问题解决了，感谢！可能是我的 微信公众号增强辅助 插件出了点问题，没法增加到排除列表（手动增加或者点击排除后，刷新页面又不在列表里了），最后是通过删除该插件解决的。未来有需要的话重装一下应该问题不大。
现在是简阅的深度用户，一直在通过自动化增强辅助和导出到 obsidian 等插件，将阅读标注或者全文导入到本地 ob 库，方便做知识整理。这个功能对我来说相当实用和便捷，好评！！
![image](https://github.com/user-attachments/assets/9a638f8c-43db-4829-9c89-8f67168dab7e)

**Comment by Kenshin** [comment]
哈，喜欢简悦就好。

> 手动增加或者点击排除后，刷新页面又不在列表里了

估计你需要使用插件管理器安装插件 https://www.yuque.com/kenshin/simpread/fcw60u

**Comment by Kenshin** [comment]
如果经常看公众号的话，还是需要安装这个插件的，否则阅读模式在部分公众号效果不佳。
