### ISSUE TITLE
能否匹配一下B站专栏的阅读模式

### ISSUE THREAD

**Issue by tdgwsqsdgj** [Kenshin/simpread#6407]
### 需要适配的新站

https://www.bilibili.com/read/home?from=category_0
例如
https://www.bilibili.com/read/cv17468246/?spm_id_from=333.999.collection.opus.click
https://www.bilibili.com/read/cv6202435/?spm_id_from=333.999.collection.opus.click

### 有需要请描述这个站的性质

哔哩哔哩专栏是为全体UP主开放的个人空间、自媒体平台，UP主可通过专栏平台分享自己的经验、攻略、心得等文章信息

**Comment by Kenshin** [comment]
嗨，这个页面早就已经适配了 😂

<img width="1807" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fbc9366a-b112-44a0-a4d8-1823a476b00e">

适配规则

<img width="478" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f564dd1c-2d0f-40f2-b002-6f004d63c5fe">

你可以更新适配规则 https://github.com/Kenshin/simpread/discussions/2870

我关闭这个 Issues 了，有任意疑问仍可以随时跟我讨论 😄
