### ISSUE TITLE
UserScript用户脚本版简悦即simpread-little无法安装

### ISSUE THREAD

**Issue by Mosney** [Kenshin/simpread#6408]
### 描述这个错误

鉴于没有Firefox版插件，按照[simpread-little](https://github.com/Kenshin/simpread-little)的指示使用用户脚本版简约，但目前由于greasyfork删除脚本故无法正确安装。

- https://greasyfork.org/zh-CN/scripts/39998 
  > 请求的脚本已被删除。  

- 使用 [GitHub raw](https://raw.githubusercontent.com/Kenshin/simpread-little/master/src/userscript/simpread.js) 则暴力猴会提示部分依赖JS加载失败，具体是下列这些，全都404了：
  >   @require
  >     ↗https://greasyfork.org/scripts/40172-mousetrap/code/Mousetrap.js?version=262594
  > 
  > @require
  >     ↗https://greasyfork.org/scripts/383025-bloomingmenu/code/BloomingMenu.js?version=698175
  > 
  > @require
  >     ↗https://greasyfork.org/scripts/39995-pureread/code/PureRead.js?version=770507
  > 
  > @require
  >     ↗https://greasyfork.org/scripts/39997-puplugin/code/PuPlugin.js?version=770506

### 复现步骤

N/A

### 操作系统

Windows

### 浏览器

Firefox 124.0.1

### 发生问题的网址

N/A

**Comment by Kenshin** [comment]
嗨，油猴脚本只是 1.x 的部分版本，跟现在的功能相距有些大了，所以就下线了~

**Comment by Mosney** [comment]
最新版本是转为付费才能用的模式了吗？https://simpread.pro/ 是官网吗？看了半天不知道怎么用起来，免费试用只有chrome插件是正常的，另外更新日志里来看chrome插件也很久没更新了，最近的更新全是“同步助手”，我也没太明白这个同步助手是做什么用的

**Comment by Kenshin** [comment]
1. simpread.pro 是官网...
2. 1.x 版的全部功能都可以正常使用，部分高级功能需要升级为高级账户，建议看下 https://simpread.pro/price
3. 同步助手的说明 https://simpread.pro/docs/#/Sync
4. Chrome 分为四个部分，除了扩展端以外，还有：插件端、同步助手、适配规则，基本上每周都会更新，这些部分更新日志 https://simpread.pro/changelog.html

另外，多说一句，很多使用者（跟简悦用户无关）都会有这种奇怪的思维定式：看下软件的更新日期 😂

一个产品是否更新看日期是最容易迷惑的事情，很多扩展都只是改个说明，它的日期就更新了，如果要看这个产品的活跃度最好要看 Issues（产品论坛 / QA / 评论数） 的活跃度。

那简悦来说，我截图看下进入的 Issues 数（以及 Issues 总数）

<img width="648" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/522fab95-5530-4053-8424-1075d1ff14e9">

其它维度的就「懒得」截图了 😂

**Comment by Mosney** [comment]
> 另外，多说一句，很多使用者（跟简悦用户无关）都会有这种奇怪的思维定式：看下软件的更新日期 😂

一般语境下这种现象我会认为是被大公司“客户端”无尽的KPI和更新规训的结果🤣

也就是说现在简阅免费版本有且只有chrome扩展可用对吗？

我是觉得目前网站对新手的交互体验差了些，就算我之前用过一段时间也依然看得一头雾水，搞不清楚现在应该如何安装、是否是必须付费才可使用、以及扩展端/插件端/同步助手这些东西分别都是做什么用的等等。

另外正是因为我在使用非chrome，就点击了官网最下面的用户脚本链接，但得到的结果是脚本已不存在，进而怀疑这个产品是否已经停止维护，去查看changelog确认更新时间也是个合乎逻辑的行为。

**Comment by Kenshin** [comment]
> 正是因为我在使用非chrome，就点击了官网最下面的用户脚本链接，但得到的结果是脚本已不存在，进而怀疑这个产品是否已经停止维护，去查看changelog确认更新时间也是个合乎逻辑的行为

okay 我会优化下官网 谢谢提示 （确实有误导 😂

> 是觉得目前网站对新手的交互体验差了些，就算

这个就很难把控了，每个产品都有觉得好的，也有觉得不好的（用户）。

一般你遇到的疑问大部分都是：不用直接问的朋友（非用户），但你说你已经使用过了，所以理论上不应该有这种疑问。

大部分用户最先接触的就是：阅读模式以及相关功能，这些都是免费使用的，但如果有导出诉求（一般是双链笔记用户），才会了解同步助手、与 Obsidian / Notion 这些的相关内容，而这些相关内容对新用户来说可以直接使用官方配置好的 [配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 方案
