### ISSUE TITLE
故想把simpread后的介面转90度，即打开阅读模式後內容以竖屏的样子呈現。

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#6409]
### 请描述你的建议或任何内容

每天坐在办公室的椅子平均6或7个小时后，回家还是坐在椅子，对着MacBook用simpread阅读网页及标注内容，相信这样久坐对自己的腰肌盘骨不好，故在未有iOS手机端下的simpread一直用得不多。

现在想到的方法是把MacBook内容用sidecar投射到iPad Pro上，只用鼠标的话与坐在椅子感受一致的。
![IMG_6342](https://github.com/Kenshin/simpread/assets/87223257/d07149e5-026d-4efb-bf96-a04645b80457)

目前还想再优化一下情况：MacBook屏是横的，**但iPad Pro可以竖的啊**！故想把simpread后的介面转90度，即打开阅读模式後內容以竖屏的样子呈現。

1.试了一下在[网页开发者模式下加一句代码，还能把网页转90度，](https://blog.csdn.net/u011374856/article/details/122257558)但打开阅读模式后失效。
2.想用调整” [版面宽度定制器](https://simpread.ksria.cn/plugins/details/noCdz57Mw6) “直接改把在在布局参数对调，但好像失效。这需要另新造一插件吗？

**Comment by Kenshin** [comment]
> [版面宽度定制器](https://simpread.ksria.cn/plugins/details/noCdz57Mw6) “直接改把在在布局参数对调

这个插件能解决你的问题，最开始设计这个插件的思路就是用用户问：是否可以竖屏显示...
