### ISSUE TITLE
功能建议：SimpRead 保存按钮隐藏太深

### ISSUE THREAD

**Issue by 9k01** [Kenshin/simpread#641]
SimpRead 简洁按钮很好看，但是保存到相关按钮隐藏太深了
不论看everynote还是微软的https://www.onenote.com/clipper，他们的保存按钮都是很明显的，
楼主是否可以考虑，让用户选择把常用按钮放出来不用鼠标移动上去选择？

**Comment by Kenshin** [comment]
确实有这个问题，之前有用户提过，1.1.4 暂时没有把它放到 开发列表 中，会实现此功能的。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，解决办法是增加两个辅助性的插件 #891 #892 

我将关闭这个 Issues。

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，

**Comment by CC-bit** [comment]
现在依然存在这个问题，我从购买高账到学会保存OneNote到成功在OneNote中找到那篇文章，用了1个小时，几乎是把文档读完了，其中文档目录超链接错误、几个页面来回跳转的混乱与辛苦就不说了

**Comment by Kenshin** [comment]
@CC-bit 

> 现在依然存在这个问题

如果是说保存的方式不是很明显的话，可以试试  https://github.com/Kenshin/simpread/discussions/1600 https://github.com/Kenshin/simpread/discussions/1601 这两个插件。

另外， Onenote 的保存逻辑在下个版本有个较大的升级，除此之外，目前 Onenote 也存在授权时间较短的问题（下个版本也解决了）
