### ISSUE TITLE
飞书兼容性

### ISSUE THREAD

**Issue by balandogg** [Kenshin/simpread#6410]
### 描述这个错误

飞书文档只会显示第一段

### 复现步骤

1.打开飞书文档
2.使用简悦
3.发现只有一段

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://d16rg8unadx.feishu.cn/wiki/Tqn8wOoZUid3VpkXp6fc9YvRnsc

**Comment by Kenshin** [comment]
嗨，此类页面是不会被适配的，类似如：百度文库等，我关闭这个这个 Issues 了。
