### ISSUE TITLE
最近好像在Arc不能用了

### ISSUE THREAD

**Issue by Gileet** [Kenshin/simpread#6412]
### 描述这个错误

进入阅读模式后无法访问简悦的菜单栏，选中后也无法高亮（即便开着），就是完全失灵的状态。

### 复现步骤

1. 随便打开一个网页
2. 进入阅读模式/聚焦模式

### 操作系统

macOS Somona 14.4.1 (23E224)

### 浏览器

Arc 1.35.0 (47750)

### 发生问题的网址

https://mp.weixin.qq.com/s/Ub_L0LUbWrzPMfs68OykDA

**Comment by Kenshin** [comment]
肯定跟 Arc 无关 😂

1. 是任意页面都有问题？还是某个？
2. 如果使用了同步助手的话，试试 http://localhost:7026/database/fixed 能否解决（不确定是否有此问题引起）

**Comment by Gileet** [comment]
> 肯定跟 Arc 无关 😂
> 
> 1. 是任意页面都有问题？还是某个？
> 2. 如果使用了同步助手的话，试试 http://localhost:7026/database/fixed 能否解决（不确定是否有此问题引起）

1. 任意页面都有问题
2. 没有下载同步助手桌面端也没有配置过……

**Comment by Kenshin** [comment]
你看看能否正常打开稍后读页面以及选项页？如果能打开选项页的话，导出配置文件然后发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6412

然后在这里告诉我，我帮你看下。

**Comment by Gileet** [comment]
可以打开稍后读页面以及选项页；邮件已经发送了，感谢！

**Comment by Kenshin** [comment]
okay 我明天帮你看下。（今天有事情外出了）

不过，选项页和稍后读能打开，不应该有问题才对.... 😂

**Comment by Kenshin** [comment]
我导入了你的配置文件没有任何问题...

<img width="1140" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/45f4a967-5aa0-40c5-bf1a-f3f048c47974">

注意：你把右下角的标注和菜单栏隐藏了，鼠标移到右下角后显示。

你可以试试：

1. 更好另外一个浏览器并导入这个配置文件，看是否可以使用？
2. 删除并重新在 Arc 安装简悦，导入此配置文件

无论上述哪种导入方式均在导入后需要手动导入插件数据，位置：选项页 → 插件管理 → 从配置文件导入插件。

然后建议重启浏览器确保成功。

**Comment by Gileet** [comment]
试了一遍，失败……甚至今天更新了arc还是不行。
Chrome使用是没有问题的。

**Comment by Gileet** [comment]
我把控制栏设置为一直开启，但它只是显示在那里，不能交互，点击没有反应。
![image](https://github.com/Kenshin/simpread/assets/147358596/16c43fac-e6bc-41f2-a566-d2992c331160)
标注是开着的，但是选中文本后也无法进行任何操作。
![image](https://github.com/Kenshin/simpread/assets/147358596/c9003974-8f86-4b7e-b138-f67e6e5f4b13)

另外，进入阅读模式再按Esc退出，页面会变成完全空白的，无法显示原网页，必须要刷新一下。

**Comment by Kenshin** [comment]
> 试了一遍，失败……甚至今天更新了arc还是不行。 Chrome使用是没有问题的。

1. 在 Arc 删除并重新安装简悦
2. **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

简悦有不少 Arc 的用户（包括我，虽然不怎么经常使用），目前除了你以外没有其它用户报告过类似问题。

**Comment by lyserenity** [comment]
macOS beta + Arc 1.37 

今天试了下没什么问题，不过近几个月 arc 都是我的主力，平时用没遇上什么问题。（唯一是前两个月 arc 彻底崩坏，启动即闪退，最后“彻底”卸载重新安装过一次）

**Comment by Gileet** [comment]
破案了，是这个扩展的问题，关掉就好了……
![image](https://github.com/Kenshin/simpread/assets/147358596/e7cd7574-b0b9-42b7-b7eb-20f7fb2f9aaf)

**Comment by Kenshin** [comment]
原来如此，调查方向一直是 Arc 的配置（ Arc 早期版本确实不稳定导致有无法使用简悦的情况），没想到是这个原因... 😂

PS：这个扩展已经在简悦这边报告好几次了
