### ISSUE TITLE
新站适配: 酷安动态页

### ISSUE THREAD

**Issue by viayuu** [Kenshin/simpread#6419]
### 需要适配的新站

https://www.coolapk.com/feed/53960795?shareFrom=com.coolapk.market_14.0.2&shareKey=MjQ0OWY4MWNiMGY5NjVlMDNjNjk%7E&shareUid=776655

### 有需要请描述这个站的性质

酷安的文章（图文）页可以正常适配，动态页无法获取任何信息，只有下图的信息
![image](https://github.com/Kenshin/simpread/assets/128775768/3327dbec-2f50-42c8-bde9-146bdad04094)

**Comment by Kenshin** [comment]
okay

请多给我一些类似的页面做参考

**Comment by viayuu** [comment]
> okay
> 
> 请多给我一些类似的页面做参考

https://www.coolapk.com/feed/47306998?shareKey=NTY1MDhjNGYwZTFkNjYwYTU5ZWY~&shareUid=776655&shareFrom=com.coolapk.market_14.0.2

https://www.coolapk.com/feed/54807324?shareKey=MThiMjU0MzlmNjA3NjYwYTVhMTY~&shareUid=776655&shareFrom=com.coolapk.market_14.0.2

https://www.coolapk.com/feed/54807992?shareKey=NDM1OTMzMjY0YzMxNjYwYTU5YmU~&shareUid=776655&shareFrom=com.coolapk.market_14.0.2

**Comment by Kenshin** [comment]
okay 👍 🙏

**Comment by Kenshin** [comment]
嗨，这个站点已适配完毕。

#### 如何更新

选项页 → 站点管理 → 官方主适配源（留意下图）

<img width="924" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0e94adad-e103-46d3-9582-10069a07abd1">

更新后请务必重启浏览器确保生效。

#### 效果如下

<img width="1810" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b0c144b1-5ccc-4d90-8c51-8410a0bc8354">

***

我关闭这个 Issues，有任何问题请随时在这里讨论~
