### ISSUE TITLE
标注网页中的图片时，是否可以改为存在本地？

### ISSUE THREAD

**Issue by Thinkbond** [Kenshin/simpread#6421]
### 请描述你的建议或任何内容

在标注网页中的图片时，目前会使用外链的方式保存在导出的annote md中（针对 obsidian）为防止网页失效以及离线阅读标注内容的需要，是否可以提供一个选项，将网页中的图片标注（高亮某个图片）自动下载到标注md文件的附件中。

**Comment by Kenshin** [comment]
暂时不可以 😂 但将图片保存到本地有很多方案：

1. [图床插件](https://github.com/Kenshin/simpread/discussions/4306)

2. 被保存的 App 一般也有将图片本地化的功能 e.g. Obsidian / 思源笔记均具有此功能。

3. 简悦的 [本地知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 方案（此方式需要改为 **离线 HTML**，因此建议前两种方式。

如果你只是想离线标注的图片，自己找下 Obsidian 的插件，即可解决~

**Comment by Kenshin** [comment]
嗨

[图床插件](https://github.com/Kenshin/simpread/issues/4307) 升级到 **2.0.0** 内置了 （与 导入到 Notion 一致的）Cloudinary 图床方案，解决了你提到的这个问题。

2.0.0 版介绍
---

可以将阅读模式的图片上传到你的图床中，并替换为图床的图片链接，导入后支持触发自动化方案实现导入到简悦支持的任意生产力工具的诉求，目前有以下几种导入方式：

1️⃣ PicGo 图床 → 借助 PicGo App 实现支持大多数常见的图床方案。

2️⃣ Base64 本地化图片 → 将图片转换为 Base64 字符串。

3️⃣ Cloudinary 图床 → 直接将图片上传到 Cloudinary 图床。

功能
---

1. 支持图床方案：PicGo 图床、[Cloudinary 图床](https://github.com/Kenshin/simpread/discussions/4306#discussioncomment-7172818) 与 **Base64 图片本地化** 三种方式。

2. 图片上传完毕后自动将阅读模式的图片链接转换为图床链接。

3. 图片上传完毕后自动加入稍后读

4. 图片上传完毕后支持导出方案（包括：简悦扩展端原生支持与简悦插件）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
