### ISSUE TITLE
想授权坚果云，按照说明走但没有那个选项

### ISSUE THREAD

**Issue by hybushis** [Kenshin/simpread#6422]
### 描述这个错误

选项页 → 账户 → 授权登录
    我根本没有授权登陆这一选项啊，太复杂了，然后就无法给坚果云授权
![Snipaste_2024-04-03_10-09-21](https://github.com/Kenshin/simpread/assets/45105373/92c8183f-ac95-4b3b-bfea-9d0f207aff9a)

想登个录却无门， 为何如此复杂

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/45105373/d51dee91-bdb3-4947-9a19-606d237b9af1)
这里我登录了，
然后授权，失败，    账户标签页里也没有授权登陆的条目， 和说明书完全不一样，把人弄的很晕

### 操作系统

win

### 浏览器

chrome

### 发生问题的网址

选项页

**Comment by hybushis** [comment]
![image](https://github.com/Kenshin/simpread/assets/45105373/8e4fbdbf-51c5-4120-b6d5-026ddba9f2d4)

**Comment by Kenshin** [comment]
嗨，你使用错方式了... 😂

这个方式不适合你（新用户），如果只是想授权坚果云的话，直接在选项页 → 服务 → 授权管理中授权。

PS：你是从哪个教程看到此方式的？
