### ISSUE TITLE
网页进入简悦阅读模式下，网页的表格无法显示

### ISSUE THREAD

**Issue by XHHHX** [Kenshin/simpread#6423]
### 描述这个错误

打开某个网页，进入简悦阅读模式，结果网页中的表格内容无法显示

### 复现步骤

我打开一个网页，然后点击简悦进入简悦的阅读模式，在阅读的过程中发现原网页的表格无法显示，网页由markdown编写
原网页内容：![image](https://github.com/Kenshin/simpread/assets/110332199/1f62e4ba-9ff1-4a37-a6c2-308b7c6608c1)
阅读模式下的网页内容：
![image](https://github.com/Kenshin/simpread/assets/110332199/5d9b505d-989c-4af8-b464-3541796bdc1a)

### 操作系统

windows

### 浏览器

edge 版本 122.0.2365.80 (正式版本) (64 位)

### 发生问题的网址

https://www.hello-algo.com/chapter_data_structure/basic_data_types/

**Comment by Kenshin** [comment]
emmm 因为这个站没有适配造成的。

不建议这种有交互类型的网站适配阅读模式，效果不太好。

不过，你可以使用下面的方式生成阅读模式（但仍无法满足你的需求，原因上条）

<img width="1099" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8cd1eaa2-48ac-46f9-985c-51923a75c05b">

**Comment by XHHHX** [comment]
哦哦，好的，多谢解答

**Comment by Kenshin** [comment]
小事情 😄
