### ISSUE TITLE
导入notion时，微博中的图片无法上传到Cloudinary图床

### ISSUE THREAD

**Issue by viayuu** [Kenshin/simpread#6424]
### 描述这个错误

我安装了：官方给出的notion配置库(高级版)、适配微博的站点集市。并在"导入到notion"插件中设置了Cloudinary图床。
出现问题：在其它支持的网页使用上传到notion功能，都可以正常运行，并把图片上传至Cloudinary图床；与微博相关的网页,稍后读界面正常，但在上传图片时提示"导入失败"
![image](https://github.com/Kenshin/simpread/assets/128775768/2d0e514a-40cc-4d86-9038-b81682b7e601)
保存完成后，在notion中查看，能看到图片，但图片的链接不是Cloudinary图床链接，而是新浪的图片链接，例如(https://wx3.sinaimg.cn/large/0033ImPzly1hoddo6ep7gj60rs12ywqt02.jpg)

### 复现步骤

1. 安装notion配置库，设置图床，经测试其它网页的图片都能正常上传
2. 在微博页面，打开稍后读，再保存到notion，提示图片导入失败

### 操作系统

Windows 11 24H2 26080.1

### 浏览器

Edge 123.0版本

### 发生问题的网址

https://weibo.com/2803301701/O7YmS0Tp2

**Comment by Kenshin** [comment]
嗨，关于这个问题的说明请看这里 https://github.com/Kenshin/simpread/issues/6318#issuecomment-1965708771

**Comment by Kenshin** [comment]
哈，小事情，搜索不到是正常的，因为标题没有明确指出 😂

我把之前的标题改了，不过，你的标题就足以定位问题了 👍 

PS：以后有用户搜索此问题时会定位到你这里。

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
