### ISSUE TITLE
Obsidian 选项导入失败

### ISSUE THREAD

**Issue by QoneFeng** [Kenshin/simpread#6426]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/1499678/0fc3d84f-7572-42c4-81f4-6ab985af8f54)

### 复现步骤

已经配置好，直接导入微信公众号文章报错
![image](https://github.com/Kenshin/simpread/assets/1499678/a39ae009-d887-40cc-ad1d-f2c4a07b4e9a)

### 操作系统

Windows 10

### 浏览器

chrome123.0.6312.86

### 发生问题的网址

https://mp.weixin.qq.com/s/ed8ltPn6xSF8yovke8tWYA

**Comment by Kenshin** [comment]
看截图使用的是二种导入方案？如果是的话，看下其它页面 e.g. https://sspai.com/post/69972 是否成功？

**Comment by moleoxa** [comment]
> 看截图使用的是二种导入方案？如果是的话，看下其它页面 e.g. https://sspai.com/post/69972 是否成功？

试了下我也失败了，应该是急速版的配置，翻了翻我的配置页和他一样。

**Comment by Kenshin** [comment]
@moleoxa 

你跟 @QoneFeng 是一个人？😂

**Comment by moleoxa** [comment]
> 你跟 @QoneFeng 是一个人？😂

不是，刚好看了他的 issue，于是试了试。
你可以看下我的回复编辑历史。

**Comment by Kenshin** [comment]
@moleoxa 

😂 因为你把下面这些都删除了，所以...

<img width="641" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/22b79be1-c9ba-4407-be53-5e013f8231e5">
