### ISSUE TITLE
关于维基百科的阅读模式疑问

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#6429]
### 描述这个错误

按解决方案 #5832 内的方案已安装 [Modern for Wikipedia](https://www.modernwiki.app/)及维基百科辅助增强，仍出现停用simpread 插件才能看到维基文库内容，试了在维基百科网页内，是正常显示维基百科内容（包括自动打开simpread阅读模式）

https://github.com/Kenshin/simpread/assets/87223257/c47feba1-e448-4169-a1ab-2bea1c8d3f44

### 复现步骤

停用simpread即可看到维基文库的内容。

### 操作系统

macOS 14.2.1

### 浏览器

Microsoft Edge Version 125.0.2492.1 (Official build) Dev(arm64)

### 发生问题的网址

https://zh.wikisource.org/

**Comment by Kenshin** [comment]
嗨，解决方案看这里 https://github.com/Kenshin/simpread/discussions/2347

**Comment by Kenshin** [comment]
顺道也更新了 https://github.com/Kenshin/simpread/discussions/5832 对应的说明 😂
