### ISSUE TITLE
每日回顾功能已经按照教程配置了，但是邮箱却收不到邮件。

### ISSUE THREAD

**Issue by duolago** [Kenshin/simpread#6431]
### 描述这个错误

按照每日回顾的教程已经做好了配置，却始终收不到邮件，不知道是哪里出了问题。
（教程地址：http://ksria.com/simpread/docs/#/%E6%AF%8F%E6%97%A5%E5%9B%9E%E9%A1%BE）

### 复现步骤

1.首先我在 选项页 →服务 → 授权，按照下面的设置。
![image](https://github.com/Kenshin/simpread/assets/100416005/c2658763-306b-4f86-a957-ff8edd48206a)
2.并且选项页 → 账户 → 授权登录，
![image](https://github.com/Kenshin/simpread/assets/100416005/c1455bbd-ddd5-41f9-926e-4168ec8ed7ce)
3.已经下载好了同步助手，并且验证。
![image](https://github.com/Kenshin/simpread/assets/100416005/64870b1a-a45c-4f16-90ee-d6d3e8c761c5)
4.坚果云也创建好了对应目录，和同步助手同步。
![image](https://github.com/Kenshin/simpread/assets/100416005/5662a530-dc1c-439b-9198-b91c801d2985)
5.最后也在同步助手的邮件设置里设置好了对应邮箱。
![image](https://github.com/Kenshin/simpread/assets/100416005/aecd9072-8d20-4bf6-95b5-4b4177ca0377)

但是却无法收到每日的邮件，我不知道哪边出了问题。

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

aa

**Comment by Kenshin** [comment]
接收的邮箱请留你自己的… 😂

PS：我不确定是否是这个问题造成的。

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6431#issuecomment-2042914955

emmm 这个图可能有点不完整，你可以告诉我在哪里的教程，我可以更新下这个图的说明。

发送邮箱：设置为你输入的 SMTP 密码的那个邮箱
接受邮箱：接受到每日回顾的邮箱（也就是说你想在哪个邮箱看每日回顾）

一般来说，发送邮箱和接受邮箱是一个就行。

***

但每日回顾的前提：

1. 使用同步助手的自动同步
2. 在每天晚上 19:30 确保坚果云上的 `SimpRead/simpread_config.json` 是最新的。（一般来说步骤1就能确保步骤2）

**Comment by duolago** [comment]
> > [#6431 (comment)](https://github.com/Kenshin/simpread/issues/6431#issuecomment-2042914955)
> 
> emmm 这个图可能有点不完整，你可以告诉我在哪里的教程，我可以更新下这个图的说明。
> 
> 发送邮箱：设置为你输入的 SMTP 密码的那个邮箱 接受邮箱：接受到每日回顾的邮箱（也就是说你想在哪个邮箱看每日回顾）
> 
> 一般来说，发送邮箱和接受邮箱是一个就行。
> 
> 但每日回顾的前提：
> 
> 1. 使用同步助手的自动同步
> 2. 在每天晚上 19:30 确保坚果云上的 `SimpRead/simpread_config.json` 是最新的。（一般来说步骤1就能确保步骤2）

您好，今天尝试依旧没有成功。首先您之前说的两个问题我都解决。如下图所示，我将发送邮箱地址都设为本邮箱了；且我查看了自动同步已经是同步上了。
![image](https://github.com/Kenshin/simpread/assets/100416005/263e1df1-04bd-4823-aadc-6abf04671777)
![image](https://github.com/Kenshin/simpread/assets/100416005/763d90f8-a526-4942-9141-4b82c3dff2ee)
遗憾的是仍然没有收到每日回顾的邮件，请问是哪边出了问题。

**Comment by Kenshin** [comment]
你可以看下坚果云的 simpread_config.json 的更新时间是否正常？

**Comment by duolago** [comment]
> 你可以看下坚果云的 simpread_config.json 的更新时间是否正常？

您好，现在是4月10日的00点05分，我截图了简悦的自动同步和坚果云json文件的更新时间，是对的上的。但是今晚依旧没有收到每日回顾的邮件。
![image](https://github.com/Kenshin/simpread/assets/100416005/90ab450f-47de-4b09-bf84-65897f57cc01)

**Comment by Kenshin** [comment]
emmm

> 现在是4月10日的00点05分，我截图了简悦的自动同步和坚果云json文件的更新时间，是对的上的。

你截的图不对，你应该在坚果云的 Web 版截图（但，不严格意义上说这个图应该没问题，因为我看到你的坚果云状态是开启的，但以防万一，还是按照我说的看下 Web 端的时间）

> 但是今晚依旧没有收到每日回顾的邮件。

简悦的机制是每天晚上 19点10 会检索用户的坚果云 Web 端，然后判断是否有新的稍后读，如果有就发送邮件（根据用户提交的发送邮件和接收邮件相关信息）

所以，如果你想要收到邮件，就必须要满足上面这个条件，即：

1. 你的发送邮件与接受邮件相关信息填写正确。
2. 你的坚果云相关信息填写正确。
3. 每天晚上 19点10 前确保 `simpread_config.json` 是最新的且有当天的稍后读

***

如果还是有问题的话，把你的 UID 以及每日回顾的邮箱地址发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6431

然后在这里通知我。

**Comment by duolago** [comment]
> emmm
> 
> > 现在是4月10日的00点05分，我截图了简悦的自动同步和坚果云json文件的更新时间，是对的上的。
> 
> 你截的图不对，你应该在坚果云的 Web 版截图（但，不严格意义上说这个图应该没问题，因为我看到你的坚果云状态是开启的，但以防万一，还是按照我说的看下 Web 端的时间）
> 
> > 但是今晚依旧没有收到每日回顾的邮件。
> 
> 简悦的机制是每天晚上 19点10 会检索用户的坚果云 Web 端，然后判断是否有新的稍后读，如果有就发送邮件（根据用户提交的发送邮件和接收邮件相关信息）
> 
> 所以，如果你想要收到邮件，就必须要满足上面这个条件，即：
> 
> 1. 你的发送邮件与接受邮件相关信息填写正确。
> 2. 你的坚果云相关信息填写正确。
> 3. 每天晚上 19点10 前确保 `simpread_config.json` 是最新的且有当天的稍后读
> 
> 如果还是有问题的话，把你的 UID 以及每日回顾的邮箱地址发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6431
> 
> 然后在这里通知我。

首先我查看了web端的坚果云同步时间和自动同步助手的同步时间（显然对不上，请问有什么解决办法吗）
![image](https://github.com/Kenshin/simpread/assets/100416005/6136f955-3723-416f-ae12-fbd246e27aab)
![image](https://github.com/Kenshin/simpread/assets/100416005/e63faebf-15f9-4adc-8284-cd3cb237c082)
顺便一提，简悦的同步助手是需要开机自启吗。我这次电脑没有打开同步助手，打开选项页提示这个报错
![image](https://github.com/Kenshin/simpread/assets/100416005/cb72016b-2c5a-4585-b1fe-01f31526f720)
最后我发现我按照简悦的notion导入插件装好以后，接入稍后读的自动化有问题，可以加入稍后读，但是自动化触发保存至notion时会报错提示稍后重试（但是使用标注时，自动化保存文章至notion却可以成功保存。）
![image](https://github.com/Kenshin/simpread/assets/100416005/a7c95006-05a1-4647-83ca-a63ca6d2d066)
![image](https://github.com/Kenshin/simpread/assets/100416005/46ae11d6-4d1d-4a9d-88a3-db0b723b7bfa)

**Comment by Kenshin** [comment]
> ![image](https://github.com/Kenshin/simpread/assets/100416005/6136f955-3723-416f-ae12-fbd246e27aab)

这个时间正确吗？（要跟你本地是 simpread_config.json 比较，不要跟简悦的时间比较（也就是不要跟 [这个截图](https://private-user-images.githubusercontent.com/100416005/321678087-e63faebf-15f9-4adc-8284-cd3cb237c082.png) 的时间比较）

> 顺便一提，简悦的同步助手是需要开机自启吗。我这次电脑没有打开同步助手，打开选项页提示这个报错

当然，**如果你使用了同步助手的自动同步，就必须要在使用简悦前必须保证同步助手运行**，否则会出现问题。除此之外，**也要保证启动坚果云客户端**。

不过，建议在开机后手动启动同步助手。

> 最后我发现我按照简悦的notion导入插件装好以后，接入稍后读的自动化有问题，可以加入稍后读，但是自动化触发保存至notion时会报错提示稍后重试（但是使用标注时，自动化保存文章至notion却可以成功保存。）

把 导入到 Notion 这个插件的配置截图给我看下。

**Comment by duolago** [comment]
> Reference in new issu
一、首先这是web端坚果云和本地 simpread_config.json的时间比较(显然本地的自动同步助手时间和本地的simpread_config.json时间对的上，但是web端的坚果云和simpread_config.json对不上。）
![image](https://github.com/Kenshin/simpread/assets/100416005/ded684ad-6030-4f5a-869c-4cfecdda5718)
二、请问为什么要开机手动启动同步助手而不能用开机自启，这是不是意味着我如果要用每日回顾功能，还需要每天手动开启同步助手和坚果云。
三、这是我导入到 Notion 这个插件的配置截图
![image](https://github.com/Kenshin/simpread/assets/100416005/d98902fa-c9fa-4619-bb0b-f7c1ec9cac96)

**Comment by Kenshin** [comment]
> 显然本地的自动同步助手时间和本地的simpread_config.json时间对的上，但是web端的坚果云和simpread_config.json对不上。

同步助手 以及 坚果云客户端 需要同时在运行，这样才能确保你本地与坚果云 Web 端的 `simpread_config.json` 保持一致。

> 请问为什么要开机手动启动同步助手而不能用开机自启

开机自启动在某些系统有可能会慢，所以建议手动启动...

> 这是不是意味着我如果要用每日回顾功能，还需要每天手动开启同步助手和坚果云。

当然，每日回顾的相关说明有详细描述。

> 这是我导入到 Notion 这个插件的配置截图

你确定这是你的配置截图？？😂

**Comment by Kenshin** [comment]
> 但我仍有疑问，也就是说我以后想要收到邮件，必须同时打开这三个吗，还是其中两个就可以？先后顺序有关系吗？

在这个 Issues 上面部分我应该说过了，坚果云客户端和同步助手是必须要开的（坚果云 Web 版不需要开... 😂

不过，文档确实需要在补充下  🌚 谢谢提示。

> 先后顺序有关系吗，我看有篇文档说要先开坚果云再开同步助手。

有关系，坚果云客户端和同步助手必须要先于浏览器开启，有时间你可以看下 https://www.yuque.com/kenshin/simpread/ebwu7g 里面的介绍，其实没有你想的那么「复杂」 😂

同步助手用于将浏览器的数据保存到本地；坚果云用于将这个数据同步到你的其它设备以及坚果云服务器。
每日回顾会检索坚果云服务器上你的数据，如果符合要求就发送邮件。

> 我的所有插件的截图

我让你截图的是插件配置，比如你提到的 Notion 所以截图应该是类似下图这样...

![image](https://github.com/Kenshin/simpread/assets/81074/c185592f-d4d4-4392-a021-9b71548d83cd)

**Comment by duolago** [comment]
> > 但我仍有疑问，也就是说我以后想要收到邮件，必须同时打开这三个吗，还是其中两个就可以？先后顺序有关系吗？
> 
> 在这个 Issues 上面部分我应该说过了，坚果云客户端和同步助手是必须要开的（坚果云 Web 版不需要开... 😂
> 
> 不过，文档确实需要在补充下 🌚 谢谢提示。
> 
> > 先后顺序有关系吗，我看有篇文档说要先开坚果云再开同步助手。
> 
> 有关系，坚果云客户端和同步助手必须要先于浏览器开启，有时间你可以看下 https://www.yuque.com/kenshin/simpread/ebwu7g 里面的介绍，其实没有你想的那么「复杂」 😂
> 
> 同步助手用于将浏览器的数据保存到本地；坚果云用于将这个数据同步到你的其它设备以及坚果云服务器。 每日回顾会检索坚果云服务器上你的数据，如果符合要求就发送邮件。
> 
> > 我的所有插件的截图
> 
> 我让你截图的是插件配置，比如你提到的 Notion 所以截图应该是类似下图这样...
> 
> ![image](https://private-user-images.githubusercontent.com/81074/322170829-c185592f-d4d4-4392-a021-9b71548d83cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODcwOTUsIm5iZiI6MTcxMjk4Njc5NSwicGF0aCI6Ii84MTA3NC8zMjIxNzA4MjktYzE4NTU5MmYtZDRkNC00MzkyLWEwMjEtOWI3MTU0OGQ4M2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA1Mzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MzlkODhjNGUzZGUyNWY3NDAxNjBhNjY2Y2RhNjNmMDg4MGZmZmI4ZjQwYzRlMzRhZTdkZGI2ZTUwZDdkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFsLU8v0cpOyl5glFFeVKzXHFQQxbDMUK_tyvzr-PnE)

您好我明白了，感谢解答了这么久。然后这是我找到的配置图
![image](https://github.com/Kenshin/simpread/assets/100416005/7157eac5-d2c0-471e-bd6d-d5ef24380707)
![image](https://github.com/Kenshin/simpread/assets/100416005/684f3c99-6571-402b-8015-436cc3e51eb1)

**Comment by Kenshin** [comment]
> 您好我明白了，感谢解答了这么久

没事，这个 Issues 也算是我回复较多的一个了。

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，才配的上这些 QA 😂

***

打开 https://sspai.com/post/69972 （下面的操作也请在这个 URL 测试）然后使用下图的方式

<img width="481" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/49292641-b6a4-4222-a4f8-b6e396a0d851">

看看能否正常导入，如果不能的话，说明你的 Notion 授权有问题，试试在下图所示的地方重新授权。

<img width="526" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5175a7c8-eb1d-403e-86a2-8947c02f06a0">

授权成功后，重启浏览器确保成功。

**Comment by duolago** [comment]
> > 您好我明白了，感谢解答了这么久
> 
> 没事，这个 Issues 也算是我回复较多的一个了。
> 
> 方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，才配的上这些 QA 😂
> 
> 打开 https://sspai.com/post/69972 （下面的操作也请在这个 URL 测试）然后使用下图的方式
> 
> <img alt="image" width="481" src="https://private-user-images.githubusercontent.com/81074/322184419-49292641-b6a4-4222-a4f8-b6e396a0d851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDc2NTYsIm5iZiI6MTcxMzEwNzM1NiwicGF0aCI6Ii84MTA3NC8zMjIxODQ0MTktNDkyOTI2NDEtYjZhNC00MjIyLWE0ZjgtYjZlMzk2YTBkODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE1MDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGIyYmMyNDI2MGE5M2Q3N2IzMWYzZDJlYjc3NWNmNTdiZGM4YWE4YzkzYWJmNDE3ODMxZWFhMTU4ZWUzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AELsUJciSzBRF-3eZHpbNo3RSTSBSRBHtfPYsOijNc0">
> 看看能否正常导入，如果不能的话，说明你的 Notion 授权有问题，试试在下图所示的地方重新授权。
> 
> <img alt="image" width="526" src="https://private-user-images.githubusercontent.com/81074/322184455-5175a7c8-eb1d-403e-86a2-8947c02f06a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDc2NTYsIm5iZiI6MTcxMzEwNzM1NiwicGF0aCI6Ii84MTA3NC8zMjIxODQ0NTUtNTE3NWE3YzgtZWIxZC00MDNlLTg2YTItODk0N2MwMmYwNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE1MDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMGI1YWM0ZmM0NjU3NGFlMDBjZmU5YmRlZDBhZGIxNjljMDI0NDkwZGRmNmY5NGQ0YzY0MTc3NmY0ZjVmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJ3MqUambBwfvpqpOyQaOxaemN2PuzaKAF9HEC1dpk8">
> 授权成功后，重启浏览器确保成功。

您好，我按照您的方法首先是测试了一键导入全文到notion。效果如下图所示（显然无法实现）
![image](https://github.com/Kenshin/simpread/assets/100416005/23e3d09e-6f45-43cf-bf08-62b5fba2c3e6)
但遗憾的是，我在导入到notion选项中，选择了重新授权并选择page同时完成了保存（如下图）
![image](https://github.com/Kenshin/simpread/assets/100416005/c75a9752-db7f-4145-9641-5294e71f1192)
刷新后，测试了一键导入全文到notion，仍然是一样的问题。（如下图）
![image](https://github.com/Kenshin/simpread/assets/100416005/ab777d71-3ff2-49d2-a3fe-2308ddf7b74c)
最后，我在edge上给出了五星好评，感谢作者一路的解答，真的很贴心。

**Comment by Kenshin** [comment]
> Notion 的问题

有点意思 😂 

方便的话，把你的 **配置文件** 和 **Notion 账户/密码** 发送到 `help#####simpread.pro` 邮箱里面（注意 `#####` → `@`）并注明这个 Issues ID：6431

然后在这里回复我，我帮你看下。

**Comment by duolago** [comment]
> > Notion 的问题
> 
> 有点意思 😂
> 
> 方便的话，把你的 **配置文件** 和 **Notion 账户/密码** 发送到 `help#####simpread.pro` 邮箱里面（注意 `#####` → `@`）并注明这个 Issues ID：6431
> 
> 然后在这里回复我，我帮你看下。

邮件已发

**Comment by Kenshin** [comment]
okay 这几天有点忙，今天下午或明天会给你回复。

**Comment by Kenshin** [comment]
你的配置文件应该没有问题，但可能（猜测）是操作不当造成的。

你下载我给你的配置文件后，替换下你原来的配置文件，然后重启浏览器，再试试，正常情况应该好使了。

如果还是有问题的话，试试使用下面的操作顺序。

留意：按照下图操作后，也请重启浏览器。

<img width="531" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/806d4148-74ba-48aa-982d-20476e0417d1">

PS：别忘记修改你的 Notion 密码。（修改密码不会对授权 Notion 产生影响）
