### ISSUE TITLE
Linux下使用obsidian插件保存后，页面选择“打开”，但是无法打开obsidian

### ISSUE THREAD

**Issue by ViNull008** [Kenshin/simpread#6432]
### 描述这个错误

Linux下使用obsidian插件保存后，页面选择“打开”，但是无法打开obsidian
文章实际上已经保存下来了，但是无法自动跳到obsidian界面
obsidian使用的是官网下载的appimage文件，单文件执行程序
同样的操作在win下面正常跳出obsidian并显示刚刚保存的文章

### 复现步骤

Linux下使用obsidian插件保存
页面选择“打开”
无任何反应

### 其他相关说明

obsidian下载地址
https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.12/Obsidian-1.5.12.AppImage

### 操作系统

ubuntu20

### 浏览器

Microsoft Edge 版本 123.0.2420.81 (正式版本) (64 位)

### 发生问题的网址

https://blog.csdn.net/inthat/article/details/121682317

**Comment by Kenshin** [comment]
嗨，简悦调起 Obsidian 使用的 URL Scheme 是 `obsidian://open?vault=aaa&file=bbb` 

- `aaa` → Value Name
- `bbb` → File Name

没有做任何多余的事情，你可以试试在 Linux 能否直接这么使用？

**Comment by ViNull008** [comment]
解决方法：制作一个desktop文件拷贝到/usr/share/applications中，使得obsidian可以通过系统启动即可
放好记得sudo update-desktop-database 一下。

**Comment by Kenshin** [comment]
👍 

PS：Linux 用户动手能力就是强。

我关闭这个 Issues 了。
