### ISSUE TITLE
如何把稍后读的全部文章批量进行本地备份或导出

### ISSUE THREAD

**Issue by linyisan** [Kenshin/simpread#6433]
### 请描述你的建议或任何内容

一个个去操作太繁琐了，堆积了大量文章，能否在点全选后进行批量导出操作？目前只有批量删除/归档

**Comment by Kenshin** [comment]
emmm 这好像是个悖论...

1. 当加入稍后读时会自动产生本地快照，所以不需要你提到的「备份」。

2. 简悦也没有你说的「导出」，简悦是基于本地的稍后读系统，使用了共有格式 `.html`（你可以理解类似 Obsidian，不需要将 Obsidian 的内容再导出一份 Markdown 是一个道理）

第一点需要简悦的 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 功能支持，如果你没有使用此功能的话，默认简悦不会将你的稍后读本地化，因此也没办法具有 **批量导出** 功能。

**Comment by linyisan** [comment]
> emmm 这好像是个悖论...
> 
> 1. 当加入稍后读时会自动产生本地快照，所以不需要你提到的「备份」。
> 2. 简悦也没有你说的「导出」，简悦是基于本地的稍后读系统，使用了共有格式 `.html`（你可以理解类似 Obsidian，不需要将 Obsidian 的内容再导出一份 Markdown 是一个道理）
> 
> 第一点需要简悦的 [知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 功能支持，如果你没有使用此功能的话，默认简悦不会将你的稍后读本地化，因此也没办法具有 **批量导出** 功能。

我的意思是如下图所示：
![Uploading 微信截图_20240412152741.png…]()

**Comment by Kenshin** [comment]
不行的，你的这些稍后读都没有本地快照，存在本地快照的稍后读应该类似下图所示

![image](https://github.com/Kenshin/simpread/assets/81074/aaa32c6d-f994-455f-b512-23a10ddff29e)

另外，简悦支持：当加入稍后读时自动导出 Markdown，所以仍是个悖论...

**Comment by linyisan** [comment]
> 不行的，你的这些稍后读都没有本地快照，存在本地快照的稍后读应该类似下图所示
> 
> ![image](https://private-user-images.githubusercontent.com/81074/321904737-aaa32c6d-f994-455f-b512-23a10ddff29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDM3MDcsIm5iZiI6MTcxMjk0MzQwNywicGF0aCI6Ii84MTA3NC8zMjE5MDQ3MzctYWFhMzJjNmQtZjk5NC00NTVmLWI1MTItMjNhMTBkZGZmMjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE3MzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YWE2NTRmYTYxOGYxYzllZTk4ZWQwMzJmZTI5MWY1NTRlYWQxOTEwNTlhOGVhZWZjYmY3ZTdlN2MyMzcyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jbp9Gb0PrOhAMFUVQOgLTdZ2e3FAfafkZ4rJuCKdIS8)
> 
> 另外，简悦支持：当加入稍后读时自动导出 Markdown，所以仍是个悖论...

😂这功能必须设置完增强导出、自动化等配置，然后在目标网页进入阅读模式添加到稍后阅读，等待右上角提示“已成功保存”才是真正进行本地备份/导出的动作啊；像我之前没进行本地快照的，那不得全部删除，然后一个一个进入阅读模式重新加入到稍后阅读？*进入阅读模式是这个本地快照功能前提*，对于我平时多开查询资料，想要快速本地备份，还得一个个网页等待它几秒钟进入阅读模式？
我想要它不进入阅读模式都能进行本地快照，而且对于之前已经加入稍后阅读的老数据（没本地快照）的也能进行批量手动本地快照

**Comment by Kenshin** [comment]
> 增强导出、自动化等配置，然后在目标网页进入阅读模式添加到稍后阅读，等待右上角提示“已成功保存”才是真正进行本地备份/导出的动作

新用户可以直接使用简悦官方设置的配置库方案 https://www.yuque.com/kenshin/simpread/any457

> 我想要它不进入阅读模式都能进行本地快照，而且对于之前已经加入稍后阅读的老数据（没本地快照）的也能进行批量手动本地快照

暂时没有这个功能。

***

其实你一直没有理解简悦稍后读的模式，简悦是基于本地系统的稍后读，我之前应该说过多次了。

简悦的优势在于：你的网页快照是在你本地，而不是某个稍后读的服务器，所以不会随意「丢失」，因为是在本地，隐私性归属用户所有，而不是某个稍后读。

但默认没有配置的话，是不会保存快照的，而某些线上稍后读则没有这个「步骤」。
