### ISSUE TITLE
R包说明页

### ISSUE THREAD

**Issue by HUGOSAMA1121** [Kenshin/simpread#6435]
### 需要适配的新站

https://cran.r-project.org/web/packages/GD/vignettes/GD.html

**Comment by Kenshin** [comment]
嗨，这个站可以直接进入阅读模式。

一般来说只有大众类的页面才可以官方适配。

你可以使用 https://github.com/Kenshin/simpread/discussions/1554 提到的方式，基本上都可以进入阅读模式，以及更多阅读模式用法 https://github.com/Kenshin/simpread/discussions/3340

**Comment by HUGOSAMA1121** [comment]
谢谢
________________________________
发件人: ***@***.*** ***@***.***> 代表 Kenshin Wang ***@***.***>
发送时间: 2024年4月10日 01:17
收件人: Kenshin/simpread ***@***.***>
抄送: 山海 ***@***.***>; Author ***@***.***>
主题: Re: [Kenshin/simpread] 新站适配：R包说明页 (Issue #6435)


嗨，这个站可以直接进入阅读模式。

一般来说只有大众类的页面才可以官方适配。

你可以使用 #1554<https://github.com/Kenshin/simpread/discussions/1554> 提到的方式，基本上都可以进入阅读模式，以及更多阅读模式用法 #3340<https://github.com/Kenshin/simpread/discussions/3340>

―
