### ISSUE TITLE
稍后读导出到obsidian出错

### ISSUE THREAD

**Issue by cwt2003** [Kenshin/simpread#6436]
### 描述这个错误

我在服务中设置将稍后读导出为markdown文件至obsidian中报错，可以导出html文件

### 复现步骤

这是我的自动化设置
![image](https://github.com/Kenshin/simpread/assets/141006946/00ccfa43-6ac7-4aa3-8da6-9dabd05c41dd)
前三个导出没问题，只有最后一个出错
![image](https://github.com/Kenshin/simpread/assets/141006946/ee1920c3-f949-4636-9c2b-01fc1d9efe1c)

### 操作系统

Windows

### 浏览器

edge

### 发生问题的网址

https://blog.csdn.net/qq_28351609/article/details/84574349

**Comment by Kenshin** [comment]
emmm 有点奇怪 😂 

不应该存在这个情况，因为 HTML 好使，但 Markdown 不好使。

你试试手动导出 Markdown 到本地会显示什么？

<img width="373" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2c4b240b-f159-4296-9dc3-02324a767e64">

> 导出为markdown文件至obsidian中报错

你是怎么设置路径的？

**Comment by cwt2003** [comment]
经过修改，可以通过添加到稍后读导出markdown文件，但是还是出现之前的报错。手动可以正常导出










                       
原始邮件
                       
                     

发件人："Kenshin Wang"< ***@***.*** &gt;;

发件时间：2024/4/10 18:24

收件人："Kenshin/simpread"< ***@***.*** &gt;;

抄送人："cwt2003"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Kenshin/simpread] 稍后读导出到obsidian出错 (Issue #6436)




 
emmm 有点奇怪 😂
 
不应该存在这个情况，因为 HTML 好使，但 Markdown 不好使。
 
你试试手动导出 Markdown 到本地会显示什么？
 image.png (view on web)  
导出为markdown文件至obsidian中报错
  
你是怎么设置路径的？

**Comment by Kenshin** [comment]
> 还是出现之前的报错

在操作什么时出现的？

> 手动可以正常导出 & 可以通过添加到稍后读导出markdown文件

所以，疑似（我怀疑）截图的报错不是导出 Markdown 这个功能的报错。

**Comment by cwt2003** [comment]
今天又用了一下，发现这个问题又消失了，我也没做什么修改

**Comment by Kenshin** [comment]
可能是某个 URL 的页面有问题造成的，我先关闭这个 Issues 如果再次发生此问题时，请一定要记录下出问题的：

1. URL
2. 步骤

然后随时在这里反馈 

😄
