### ISSUE TITLE
关于禁用页面的 JavaScript 时，简悦无法显示的 bug

### ISSUE THREAD

**Issue by robin758** [Kenshin/simpread#6437]
### 描述这个错误

当我需要禁用某个网站页面的 JavaScript 的时候，再利用简悦进入阅读模式，但是会出现空白的情况

> 似乎简悦也需要当前页面的 JavaScript? 

那么能否提供内置粘贴阅读功能, 或者其他的方式, 可以在页面禁用 `JavaScript` 的情况下也能使用`简悦`?

Regard!

ps: 附图一张
 
![image](https://github.com/Kenshin/simpread/assets/83524955/02e2a35c-7207-4b61-a0bf-925eeee9a22b)

### 复现步骤

1. chrome://settings/content/javascript 浏览器设置里添加某个页面为 禁用 `JavaScript`
2. 进入禁用 JavaScript 的页面, 再进入简悦阅读模式
3. 简悦阅读模式下, 页面空白
4. 恢复 `JavaScript` 并刷新, 简悦可以正常显示 

### 操作系统

Windows 10 Home

### 浏览器

Edge 版本 121.0.2277.112 (正式版本) (64 位)

### 发生问题的网址

https://www.economist.com/

**Comment by Kenshin** [comment]
简悦当然需要使用 JS 了…😂

不允许使用 JS 的话，肯定没法使用简悦。
