### ISSUE TITLE
已授权notion但是无法导出，反复跳转授权

### ISSUE THREAD

**Issue by ioeeoikiki** [Kenshin/simpread#6439]
### 描述这个错误

之前一直可以正常导出到notion，但某天在打开网页的简悦后，点击导出到notion，提示“授权已经过期，正在跳转页面”，当跳转回简悦的授权页面几秒后，提示：授权成功，并再次自动返回原网页。然而，点击导出至notion，却依旧无法导出，并反复出现上述跳转的问题。检查简悦的授权页面，发现notion已经处于授权成功状态。目前一直无法成功导出到notion。

### 复现步骤

1. 打开需要的网页，点击简悦扩展
2. 进入到简悦的阅读模式，点击导出到notion
3. 显示授权过期，并自动跳转回简悦授权中心，提示成功授权，再次跳转回原网址
4. 点击导出到notion
5. 再次提示授权过期，并跳转，循环往复此步骤

### 操作系统

Win11

### 浏览器

Microsoft Edge 版本 123.0.2420.81 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/question/55121537 （非仅限知乎，所有网站都无法导出）

**Comment by Kenshin** [comment]
嗨，你应该是授权「错」了。

不要在选项页 → 服务 → 授权管理进行授权操作，也不建议使用此方式，而是使用插件端方案：[导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954)

也就是说需要在这里授权并使用它

<img width="486" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a0ce2b41-8aa0-41b2-88b8-35cd2b0cdd85">

**Comment by ioeeoikiki** [comment]
已读说明，下载插件后，通过动作里的插件授权，可是仍然无法保存至notion，如同出现橙色提示。
![Uploading 111.png…]()

**Comment by xiefumin1** [comment]
我在#6473里面碰到的问题一模一样，但是至今edge浏览器版本更新也未能解决。因为最近edgedev版本经常闪退，我又用回了普通edge，这个问题就还是存在。插件端方案授权notion也还是会出这个问题。

**Comment by xiefumin1** [comment]
今天重新尝试发现反复卸载简悦和插件，但是notion导出里面的notion授权不会消失，一直都存在
