### ISSUE TITLE
转出到 notion 相关问题

### ISSUE THREAD

**Issue by lifesign** [Kenshin/simpread#644]
1. 目前部分文章转码到 notion 如果是表格的形式，会在 notion 生成 list view，然后 page 的 title 是 untitle，而不是一篇单独的 page
2. 在授权时，展示列表能否基于 workspace 来区分下 page，而不是现在平铺下来，尤其是在问题1存在的情况下，不太好区分。。  
3. 有一些提示 undefined 不知道是什么元素

![image](https://user-images.githubusercontent.com/2189610/73156392-a61a8d80-4118-11ea-978d-29a508973fee.png)

**Comment by Kenshin** [comment]
谢谢反馈。

> 第一个问题

这应该是 Notion 自己的机制，简悦导出的是 Markdown 的结构，至于其他问题，最好给出具体链接。

> 第二个问题

可以考虑，但我需要看看目前的 API 是否支持？Notion 并未提供 API 简悦使用了私有方式。

> 第三个问题

目前没有遇到这种情况，是否每次都有？

**Comment by lifesign** [comment]
第三个问题，每次都有，我进行了授权反授权几次操作，然后刷新重新获取，都会出现
我账号里有自己的 workspace 和加入了两个共享的 workspace

**Comment by Kenshin** [comment]
好，回头下调查。
不过，只能下个版本修复了。

**Comment by swj1442291549** [comment]
补充问题一：目前导出到Notion似乎只能在添加到非Database的页面中。
对于empty page或者有多个元素的page,可以正常导出。而如果将page设为full page database，则不能添加到database中，此时仍然可以导出，但只能通过搜索查询到，并不在database中显示

**Comment by Kenshin** [comment]
@swj1442291549

> 添加到非Database的页面

这个 `非 Database` 是指什么？或者说，`Database` 页面是指什么？
Notion 有自己的 Web Cliper 它能实现你说的吗？

**Comment by Kenshin** [comment]
@swj1442291549

我已经理解你的意思了，看看下个版本是否可以实现，谢谢建议。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

除此以外，还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
