### ISSUE TITLE
新站适配：ChatGPT Shared Links（ChatGPT 对话分享链接）

### ISSUE THREAD

**Issue by petulat** [Kenshin/simpread#6441]
### 需要适配的新站

https://chat.openai.com/share/260464de-2c33-4ac9-9d2a-e16e73d80510

### 有需要请描述这个站的性质

使用简悦Chrome插件，提示 可以访问此网站，但 **正文获取异常**。

改用 **手动框选** 方式生成正文存在的问题：
1、自动索引不准：无法正确识别每轮对话的开启，仅对对话内容中的标题格式敏感；
2、可读性低：列宽过窄。

**Comment by Kenshin** [comment]
okay 没问题。

PS：下周会集中配置一批新站 😂

**Comment by petulat** [comment]
> okay 没问题。
> 
> PS：下周会集中配置一批新站 😂

插件很优秀很好用，感谢作者持续更新！

**Comment by Kenshin** [comment]
谢谢 😄

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by petulat** [comment]
> okay 没问题。
> 
> PS：下周会集中配置一批新站 😂


> 谢谢 😄
> 
> 请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍


作者你好，预计什么时候配置这个新站呢？

**Comment by petulat** [comment]
> okay 没问题。
> 
> PS：下周会集中配置一批新站 😂

一个多月了，尚未更新 。。。

**Comment by Kenshin** [comment]
@petulat 

😂 明天必更新。（之前漏掉了这个 Issues nnnn 次

**Comment by Kenshin** [comment]
这个站已经适配了 😂

选项页 → 站点管理 → 按下图所示更新（留意下面的数字，你那边的数字需要 **大于等于** 这个值）

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/69cdfd23-52f1-44f8-8e3f-64c0695f1f4f">

重启浏览器，进入分享页，会自动进入阅读模式，如果上面设置正常的话，应该像下图一样显示

<img width="455" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/d3c5469a-9e88-443d-b50b-a3b05a81d617">

阅读模式效果

<img width="1817" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/40d9239c-ba8f-4714-b70b-ec4bf9c0a45f">

***

我关闭这个 Issues 了，有任意疑问随时在这里沟通~
