### ISSUE TITLE
导出为Markdown时，如何优雅的包含标注？

### ISSUE THREAD

**Issue by jacob2826** [Kenshin/simpread#6442]
### 请描述你的建议或任何内容

首先非常感谢作者提供了这样的一个插件，使用当天就购买了高级账户，但经过几天的研究，我还是没能将插件设置为符合我需求的状态。

我的需求比较直接：将平常阅读的文章全文，带上标注（仅高亮），保存为markdown格式。

我遇到了如下问题：
1. 导出Markdown，无法带上高亮标注，标注内容会生硬的直接插入到正文中。
2. 无法自定义Markdown导出时的元数据。我下载了插件，但我完全不知道该怎么设置，我希望在导出后的Markdown文件中，增加生成时间，去掉由简悦生成的声明（这对我自己保存没有任何价值，也更不会给产品带来什么曝光引流）。
3. 部分网站受插件影响，无法正常加载。把插件关了页面就能正常加载了，因此我一般只有在需要保存网页时，才启用插件。能否增加一个全局黑名单，或仅在用户触发时再加载插件相关资源？

**Comment by jacob2826** [comment]
以及还有一些莫名其妙的bug。
比如使用图床插件，保存图片时，偶尔会出现3个提示，查看下相册，果真传了3遍。。。
![image](https://github.com/Kenshin/simpread/assets/4012342/a7ca0531-a9bc-47cc-91d0-a1f20ae05b60)

**Comment by Kenshin** [comment]
嗨，谢谢支持简悦。

> 配置复杂的问题

阅读模式相关功能均可以直接使用不需要任何配置，如果有导出诉求的话，可以考虑官方配置好的配置库方案 https://www.yuque.com/kenshin/simpread/ds8zk0

> 导出Markdown，无法带上高亮标注，标注内容会生硬的直接插入到正文中。

Markdown 不能支持标注（因为没有这种语法，有些变种 Markdown 支持，但效果相当一般...

> 无法自定义Markdown导出时的元数据

简悦默认的 Markdown 没有此功能，因为 Markdown 本身就不具有任何元数据支持，简悦仅支持原生的各种导出方案 e.g. `.html` `.md` `.pdf` `.epub` `.textbundle` 等。

但简悦可以导出带有元数据的 Markdown，一些诸如支持 Markdown 元数据的笔记 e.g. Obsidian 思源笔记等。

比如：[导入到 Obsidian](https://github.com/Kenshin/simpread/discussions/2902)

综上，建议使用刚才提到的配置库方案（有 Obsidian 配置库）

> 部分网站受插件影响，无法正常加载

如果你指的是维基百科，解决方案 https://github.com/Kenshin/simpread/discussions/2347 如果不是的话，请加主域名到黑名单。

> https://github.com/Kenshin/simpread/issues/6442#issuecomment-2051363056

这个问题不是简悦造成的，而是 Picgo 本身的 Bug 你可以试试使用下图所示的 Picgo 插件

<img width="606" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/257d721c-9828-4cd8-84ba-f8ad66c3aed2">
