### ISSUE TITLE
新站适配

### ISSUE THREAD

**Issue by Zhiguo-Zhang** [Kenshin/simpread#6443]
### 需要适配的新站

https://colah.github.io/posts/2015-08-Understanding-LSTMs/

### 有需要请描述这个站的性质

openai 首席科学家的 blog

**Comment by Kenshin** [comment]
嗨，此站已经适配，如何使用 https://github.com/Kenshin/simpread/discussions/2287

这是进入阅读模式的效果

<img width="1237" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ffdee097-043d-4ad5-91c1-15be80e6f9b7">
