### ISSUE TITLE
IOS app 有了吗？

### ISSUE THREAD

**Issue by ArtechZhu** [Kenshin/simpread#6445]
### 请描述你的建议或任何内容

已经好几年了，不知道现在有对应 ios app 了吗？如稍后读之类的，我看官网还是跟几年前一样，没什么太大更新

**Comment by Kenshin** [comment]
嗨，我看到你之前提问过，简单的解答你的疑问。

简悦全部功能分为四个部分，除了扩展端以外，还有：插件端、同步助手、适配规则，基本上每周都会更新，这些是部分更新日志 https://simpread.pro/changelog.html

简悦是基于阅读模式的产品，更适合在 Web 端使用，在 iOS 端并没有太大的优势，所以 iOS 的优先级比较靠后。

***

一个产品是否更新看日期是最容易迷惑的事情，很多扩展都只是改个说明，它的日期就更新了，如果要看这个产品的活跃度最好要看 Issues（产品论坛 / QA / 评论数） 的活跃度。

那简悦来说，我截图看下进入的 Issues 数（以及 Issues 总数）

<img width="648" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/522fab95-5530-4053-8424-1075d1ff14e9">

其它维度的就「懒得」截图了 😂
