### ISSUE TITLE
微博专栏文章

### ISSUE THREAD

**Issue by DanShui-Yu** [Kenshin/simpread#6446]
### 需要适配的新站

https://weibo.com/ttarticle/p/show?id=2309404985043201163576

字体效果丢失

**Comment by Kenshin** [comment]
嗨，这个站已经适配了，看下图

<img width="1814" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/47162b7b-337e-463f-8f3d-6e9afd0bbe7d">

如何使用 https://github.com/Kenshin/simpread/discussions/3515 安装后重启浏览器，然后留意是否安装重启

<img width="478" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1416b33e-85e4-4995-9a15-6f3a2b978949">

**Comment by DanShui-Yu** [comment]
那斜体效果为什么都没有了呢

**Comment by Kenshin** [comment]
因为是下图造成的，简单的说：因为这个页面的 HTML 规则有问题，简悦在生成阅读模式时会严格按照正规的 HTML 规则设置。

<img width="935" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c5aac4eb-e9b5-49c1-8e5a-d299ba638549">


<img width="502" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/be0b9034-5748-49cb-a294-5395f050ba37">

**Comment by DanShui-Yu** [comment]
可以扩展下规则吗。。。我用omnivore是可以识别出来斜体的，全文导出为md到本地也是有斜体的

**Comment by Kenshin** [comment]
将下面的代码

```
sr-rd-content i {
 font-style: italic!important;
}
```

安装下图所示方式加入，然后重启浏览器。

![image](https://github.com/Kenshin/simpread/assets/81074/8e97ca4e-cf8f-47b9-b44b-9e79c098a851)

**Comment by DanShui-Yu** [comment]
解决了！感谢！

**Comment by Kenshin** [comment]
解决就好，原本就不是简悦的问题。 😂
