### ISSUE TITLE
快捷键设置

### ISSUE THREAD

**Issue by Lvesfzzy** [Kenshin/simpread#6447]
### 请描述你的建议或任何内容

是否可以不设置快捷键呢？比如我并不想用聚焦模式，但我仍然必须给它设置一个快捷键。

### 补充说明

主要其它快捷键太多的时候很容易冲突

**Comment by Kenshin** [comment]
必须可以 😂

细节 [看这里](https://simpread.pro/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE?id=%e7%a6%81%e7%94%a8%e5%85%a8%e9%83%a8%e5%bf%ab%e6%8d%b7%e9%94%ae) 以及 [这里](https://simpread.pro/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE?id=%e7%a6%81%e7%94%a8%e6%9f%90%e4%b8%aa%e5%8a%9f%e8%83%bd%e5%bf%ab%e6%8d%b7%e9%94%ae)
