### ISSUE TITLE
简悦的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6448]
### 请描述你的建议或任何内容

来自 Telegram 用户的使用疑问

> 问题1

重新安装简悦后刷新了很多次，还是无法切换阅读模式

![image](https://github.com/Kenshin/simpread/assets/81074/bf07a442-8648-4cf7-a2b3-cea0f9ec724d)

> 问题2

![image](https://github.com/Kenshin/simpread/assets/81074/c3a64cd9-21ec-4d22-be96-607bca5c9b0c)

> 问题3

![image](https://github.com/Kenshin/simpread/assets/81074/ee0b271f-7420-46fa-8599-7cebff53c6c7)

> 问题4

阅读模式标记后，默认模式里不会高亮

![image](https://github.com/Kenshin/simpread/assets/81074/fa067298-9cbf-44cf-bbc2-17f406abca8a)

> 问题5

![image](https://github.com/Kenshin/simpread/assets/81074/e14b8e20-74b3-4240-ac53-305be9d62ad1)

**Comment by Kenshin** [comment]
> 问题 1

因为同一个 URL 多开了，重启浏览器解决。

> 问题 2 & 3

这是同一类问题，代码高亮插件不是那么好使，如果你是 Developer  就会知道，有 nnnnn 种代码高亮的规则，简悦没法识别这些全部的代码高亮规则。

> 问题 4

这不是「问题」，简悦的一切都是建立在阅读模式基础上，并不会对原文有任何形式的「干扰」。

> 问题 5

这也不是「问题」，留意下图

<img width="571" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/15b809c2-12bc-4129-bacc-aef0546e4dd2">

**Comment by terranc** [comment]
看了回复，没啥『问题』了。
我只是作为『普通』用户反馈使用中遇到的问题（因为说的这些解决方案并没有在界面上给与明确的问题反馈及操作指引）。
可能极客玩家喜欢主动去看文档吧，喜欢折腾的高级用户会更喜欢。

**Comment by Kenshin** [comment]
一般来说 Developer 属于动手能力极强的用户群体。

***

阅读模式这种产品形态决定了：它没法 Cover 100% 的使用场景。

1. 你可以理解它是「寄生在其它网页上的应用」，所以会受到「宿主」的影响。
2. 阅读是个很私人的事情，有人觉得 A 的流程使用舒服；有人觉得 B 的使用方式舒服，结果就是 A 和  B 是完全互斥的行为，但这两种用户提供的思路其实都合理。

上述结论是一个 Issues 一个 Issues 积累的经验（下图）

<img width="309" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4dab148d-ed08-4629-9f4c-2ebe9d745185">

***

任何产品都没法照顾所有用户，最简单的例子就是  wx 一边「骂」它，但还得一边用它。
