### ISSUE TITLE
生成分享页一直失败

### ISSUE THREAD

**Issue by chelseachen007** [Kenshin/simpread#6449]
### 描述这个错误

<img width="976" alt="image" src="https://github.com/Kenshin/simpread/assets/36880000/477971f6-c9bd-4f03-ab5c-d69526bf9aa3">
生成分享页一直报错，找文档也没有找到相关的配置

### 复现步骤

就是点一下分享页

### 操作系统

mac

### 浏览器

chrome

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html

**Comment by Kenshin** [comment]
嗨，由于某些众所周知的原因，所以分享功能是不能再使用了 😂
