### ISSUE TITLE
edge无法使用简阅快捷键

### ISSUE THREAD

**Issue by Galaxfy** [Kenshin/simpread#6450]
### 请描述你的建议或任何内容

在edge中，只能使用浏览器级的快捷键，简悦内部的快捷键和插件的快捷键按了没反应，比如m d、Ctrl Ctrl等快捷键。我找了很久都没找到解决方法，谢谢大大解答一下

**Comment by Kenshin** [comment]
emmm

试试： **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by Galaxfy** [comment]
edge隐身模式按aa可以进入阅读模式，在已安装插件后代码不高亮，提示安装代码高亮插件。安装好看大图后双击Ctrl也没反应，鼠标右键图片后有看大图选项
![Uploading bd469e84-04b2-46b8-f5b7-343dbf38e837.png…]()

**Comment by Galaxfy** [comment]
edge隐身模式按aa可以进入阅读模式，在已安装插件后代码不高亮，提示安装代码高亮插件。安装好看大图后双击Ctrl也没反应，鼠标右键图片后有看大图选项
![bd469e84-04b2-46b8-f5b7-343dbf38e837](https://github.com/Kenshin/simpread/assets/167273537/8fa4f1c4-3b5e-4013-b21a-c590729361c3)

**Comment by Galaxfy** [comment]
谢谢大大。快捷键应该是冲突。

现在还有插件问题。
已安装插件后代码不高亮，提示安装代码高亮插件。
已安装看大图后双击Ctrl也没反应，但鼠标右键图片又有看大图选项。
![bd469e84-04b2-46b8-f5b7-343dbf38e837](https://github.com/Kenshin/simpread/assets/167273537/328bc163-73e6-4af8-8c24-4cbea6533256)

**Comment by Kenshin** [comment]
你是不是使用了同步助手的自动同步？如果是的话，需要使用 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式安装插件。

另外，代码高亮插件确实有点问题，支持度有限，并不能覆盖全部的代码高亮规则。

**Comment by Galaxfy** [comment]
谢谢，高亮问题解决了。确实是同步助手的问题。

**Comment by Kenshin** [comment]
okay 解决就好 👍

***

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
