### ISSUE TITLE
阅读模式下虎嗅图片加载异常

### ISSUE THREAD

**Issue by zieglar** [Kenshin/simpread#6451]
### 描述这个错误

阅读模式下虎嗅文章页面除了第一张图能正常加载，后续图片无法显示
阅读模式下：
![CleanShot 2024-04-17 at 18 29 11](https://github.com/Kenshin/simpread/assets/514693/3a2c93cf-3196-404b-ae28-332188b46b30)
正常页面：
![CleanShot 2024-04-17 at 18 29 28](https://github.com/Kenshin/simpread/assets/514693/54d670fd-3434-49c9-a3fc-151b4f2e4865)

### 复现步骤

打开虎嗅文章，进入阅读模式

### 操作系统

macOS 14.4.1 (23E224)

### 浏览器

Arc 版本1.38.0 (48670)

### 发生问题的网址

https://www.huxiu.com/article/2916827.html

**Comment by Kenshin** [comment]
emmm

这个站的图片使用了延迟加载方案，所以你需要按照下图所示设置

<img width="1224" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4e3d3f5c-eae5-4eea-965a-c15ac7cc5bbc">

即：将 `huxiu.com` 加入到延迟加载列表（位置在：选项页 → 高级设定 → 词法分析引擎），然后重启浏览器。

使用使用，需要将滚动条拉到最低下（让图片加载完毕）

<img width="1814" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/938d24b6-b4e1-4524-ab16-7c18c2eea057">
