### ISSUE TITLE
启用扩展时会导致 leartesstudios.com 个别页面无法打开

### ISSUE THREAD

**Issue by Keyfi0129** [Kenshin/simpread#6452]
### 描述这个错误

启用扩展时会导致部分网站打不开，网站完全黑屏，比如https://leartesstudios.com/about

### 复现步骤

启用扩展时会导致部分网站打不开

### 操作系统

Windows 10

### 浏览器

Chrome 及 edge 均有该问题

### 发生问题的网址

https://leartesstudios.com/about

**Comment by Kenshin** [comment]
估计是这个问题造成的（附解决方案） https://github.com/Kenshin/simpread/discussions/2347

**Comment by Kenshin** [comment]
嗨，我测试了下是没问题的（使用了上面提到的方案）

<img width="1817" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/db531668-2a94-4bd1-ad81-d33e8d365e5a">
