### ISSUE TITLE
[Help Wanted] 保存网页中的图片到本地的使用疑问

### ISSUE THREAD

**Issue by moleoxa** [Kenshin/simpread#6453]
### 需求
通过简悦将网页保存到本地方便日后检索。

### 症结
使用 Obsidian 配置库的极速版，导出后 md 内的图片依然是在线链接。

### 补充说明
大致翻了翻文档，不知道我的理解是否正确：
如果想保存图片文件，比如保存为 md+assets，现有解决办法必须要使用同步助手，也就是必须依赖坚果云的三方服务。

因为我不希望流程中有依赖三方|上云的服务，并且我只是希望单向导出保存到本地。请问有不依赖同步助手的方案吗？

**Comment by moleoxa** [comment]
保存图片为在线链接会遇到图片失效以及鉴权问题，比如：

![image](https://github.com/Kenshin/simpread/assets/147070258/44fe0999-0b1f-4f10-b1cf-bb76c864b780)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6453#issuecomment-2061195587

需要提供具体出问题的 URL

**Comment by moleoxa** [comment]
> 需要提供具体出问题的 URL

URL: https://www.itsk.com/thread/401141
回去复制链接的时候突然发现我也没登录 itsk，但是浏览器能看的图片导出到 Obsidian 就看不了，疑惑。
<br>
>简悦是基于本地的稍后读系统，在隐私性方面应该没有其他产品可以媲美。
为了实现用户的隐私最大化，简悦甚至没有用户系统，也就是说，我永远无法知道用户用简悦做了什么。

不，你没明白我的意思。隐私对我来说根本不重要，我就是 lyh 嘴里愿意用隐私换便利的那部分人。
我的意思是如何不依赖三方。即只要我能看到网页，即使是在局域网发布的网页，我也能在无外网的情况下把它 dump 到本地。
而不是哪天坚果云嘎了我又得重新寻找解决方案。
<br>
>你看的是什么文档？ 😂 （如果有文字上的歧义我可以优化它）

[Obsidian 配置库.高级版](https://www.yuque.com/kenshin/simpread/wq35mh)
># 准备
>2. 请先确保是 [升级为高级账户](https://www.yuque.com/kenshin/simpread/pwpnsx) 并且 [绑定了同步助手](https://www.yuque.com/kenshin/simpread/pwpnsx)。

[导出 md + assets 格式](https://github.com/Kenshin/simpread/discussions/4041)
># 前提
>此功能依赖于 同步助手 1.0.2 版，关于此版本的详细说明 [请看这里](https://zhuanlan.zhihu.com/p/525999909)。
<br>

两个帖子都提到要配置同步助手，于是不得不点击链接跳转到 [配置同步助手](https://www.yuque.com/kenshin/simpread/pwpnsx)  
># 下载坚果云
>一般来说，使用同步助手需要同时安装和配置坚果云。

这个页面里全是坚果云...
![image](https://github.com/Kenshin/simpread/assets/147070258/c294cd35-cc66-448c-a444-8e9a214b8e17)
  
阅读上面的内容后，我的理解是浏览器插件会将导出内容上传到云，然后需要一个操作系统进程把东西从云上取回来，以规避浏览器插件无权直接写入本地文件的限制。

>你提到的功能仅需要使用同步助手，不需要使用坚果云… 😅

可能是我的理解有误，但这个同步助手可以离开坚果云运行吗？

**Comment by moleoxa** [comment]
是否能直接将 md+assets 直接在扩展内打包成 zip 然后推到浏览器默认下载地址？ 

如果可以，我新起一个 issue 提 feature？

**Comment by Kenshin** [comment]
> 我的意思是如何不依赖三方。即只要我能看到网页，即使是在局域网发布的网页，我也能在无外网的情况下把它 dump 到本地。

我应该说的很清楚了 😂 

<img width="874" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2226af77-7b90-4a42-8478-62254bb5c08f">

> 可能是我的理解有误，但这个同步助手可以离开坚果云运行吗？

是的，同步助手跟坚果云本就是两个东西... 

我很难理解你为什么会弄错 😂 简悦和坚果云是两个不同的商业项目，我（简悦）为什么要依赖另外一个跟简悦没有任何关系的产品呢？完全没道理是不是...  😅 

还有你提到的文档问题 [Obsidian 配置库.高级版](https://www.yuque.com/kenshin/simpread/wq35mh) **也没有其他用户反馈过类似你的理解** 😂

Obsidian 配置库是让用户可以实现多设备同步而已，所以才使用了坚果云，换个角度说，你（用户）可以使用百度云、NAS、xxx 云都无所谓。

**Comment by Kenshin** [comment]
> 是否能直接将 md+assets 直接在扩展内打包成 zip 然后推到浏览器默认下载地址？

不能 😂 这个功能必须要依赖同步助手。

不过，我可以记录下这个需求，我研究下。（不需要提 Issues 了。

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时，同步助手 1.3.0  **增强了对部分图片无法正常保存的问题**。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

有任何需求可以随时在这里讨论~
