### ISSUE TITLE
历史记录时间显示有问题

### ISSUE THREAD

**Issue by DanShui-Yu** [Kenshin/simpread#6454]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/69069739/271e31df-88df-4e21-8500-5ff4c90300ce)

### 复现步骤

正在站点集市安装站点，安着安着后面一串已经装好的站点没了

### 其他相关说明

怀疑之前老丢东西是否也是类似原因

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

与网址无关

**Comment by Kenshin** [comment]
> 历史记录的时间问题

这肯定是没问题的 😂 简悦获取的是你系统的时间，不知道你的系统时间是否有什么特殊设置？

<img width="385" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/6b8793c9-e8d6-4d2d-a103-a175e9928e78">

> 正在站点集市安装站点，安着安着后面一串已经装好的站点没了

你需要使用 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装站点规则。

> 怀疑之前老丢东西是否也是类似原因

如果你指的是「丢」插件配置的话，因为你使用了同步助手的自动同步，所以需要使用此方式安装插件 https://www.yuque.com/kenshin/simpread/fcw60u 

跟上面安装站点集市是一样的方式。

**Comment by DanShui-Yu** [comment]
> 不知道你的系统时间是否有什么特殊设置？

完全没有，从没动过

**Comment by Kenshin** [comment]
你可以试试随便改动一些内容（比如更换主题），然后再看下历史记录的时间是否正确？
