### ISSUE TITLE
自动化辅助增强插件快捷键的配置刷新界面后消失

### ISSUE THREAD

**Issue by wulinwudi2017** [Kenshin/simpread#6456]
### 描述这个错误

从插件管理器中安装的三个插件，自动化辅助增强插件无法像其他两个插件一样保存设置（刷新界面快捷键配置就没了）
![image](https://github.com/Kenshin/simpread/assets/63772030/7fc74cf0-654d-4dd1-8c37-967961858499)

### 复现步骤

填写好快捷键保存设置，提示保存成功
![image](https://github.com/Kenshin/simpread/assets/63772030/a6c44762-521e-4335-87fc-9eb1d857a866)
刷新界面 重新打开设置没了
![image](https://github.com/Kenshin/simpread/assets/63772030/f566366d-310c-45b9-aaa4-17ac79c1d453)
也尝试关闭了同步助手也没用
![image](https://github.com/Kenshin/simpread/assets/63772030/bb417a06-8592-4fba-b5e4-a2799e5c5613)
其他两个的设置还在，所以是不是这个插件的bug？
![image](https://github.com/Kenshin/simpread/assets/63772030/de5e97d1-5c13-425c-a99b-0289f3f00540)

### 操作系统

win10

### 浏览器

google浏览器  版本123.0.6312.123（正式版本）64位

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
不是 Bug （或者说如果不使用插件管理器的话，算是 Bug）

你这个现象跟不使用插件管理器是一样的，但如果使用了插件管理器不应该存在这个情况。


你可以试试：

1. 按照插件管理器的说明重新安装插件。
2. 将插件配置全部保存到本地后重启浏览器。

    <img width="481" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1ba94fb1-6b6c-4fa9-9a49-a8a50ce43a41">

如果还是不行的话，就按照 https://www.yuque.com/kenshin/simpread/fcw60u 重新设置一遍。

**Comment by wulinwudi2017** [comment]
还有个奇怪的问题 不知道是不是这问题引起的。无法识别自动化方案
![image](https://github.com/Kenshin/simpread/assets/63772030/18bd6dcf-5b28-4d70-a417-b548d8158018)
![image](https://github.com/Kenshin/simpread/assets/63772030/fd1852d9-a6d1-41a2-96da-ce9fa665a6d5)

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6456#issuecomment-2067524549

应该有关系。

你这个配置文件是通过配置库修改的？还是自己设置的？

不过，目前看来你需要重新按照 https://www.yuque.com/kenshin/simpread/fcw60u 设置一遍。

或者如果你没有任何稍后读的话，建议直接使用简悦官方配置库方案 https://www.yuque.com/kenshin/simpread/psugef 所用配置时间跟你在这里发 QA 差不多~

**Comment by wulinwudi2017** [comment]
谢谢大哥，我这个是根据B站的这个视频来弄得，作者弄成功了 我的卡在自动化那边出问题了TT
https://www.bilibili.com/video/BV1Zt4y1g7RZ/?spm_id_from=333.880.my_history.page.click&vd_source=8a9ac5efc00d25a1f43b39e10c539d8a

**Comment by Kenshin** [comment]
这个视频没问题，但有点「老」了，官方直接有配置包方案了 😂

留意 https://github.com/Kenshin/simpread/issues/6456#issuecomment-2067530361 提到的配置建议。

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

# 📥 Chrome 应用商店地址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326

# 🔌 插件系统

插件系统是这两个版本变化最大的地方，因为 Manifest V3 完全禁止了远超加载代码，导致插件系统改为「内置」方案。

2.2.0 → 在插件中心查看/安装插件
2.3.0 → 在简悦内启用/禁用插件（没有安装/卸载的功能）

# 🟩 带来的好处

因为插件架构变化，导致 2.2.0 版在安装插件时无法在插件触发器看到插件选项的错误彻底消失了。

同时，当你迁移到新设备上，仅导入一次配置文件就完成了全部插件的设置

也就是说，虽然 2.3.0 版无法实现插件更新自由，但对用户来说带来了真 · 一键导入功能（所导即所得）

2.3.0 首批内置了 34 个插件，基本上是用户最受欢迎和关注的插件，其他插件会随着 728 版继续更新。

# 🟦 用户视角

因为是全「芯」升级，对于你来说，你的配置文件/插件设置均无感升级到 2.3.0 版。同时，使用体验更丝滑了，比如：

1️⃣ 可以方便的将你常用的服务置顶，也可以将不常用的服务隐藏，并支持搜索功能

2️⃣ 选项页 → 插件管理，支持插件的选项卡的设置

3️⃣ 一键导入 → 所导及所见

4️⃣ 安装插件后插件触发器错误的问题也自动消失（解决）了
