### ISSUE TITLE
小说网站如何去除「描述」

### ISSUE THREAD

**Issue by baizhusheng** [Kenshin/simpread#6457]
### 描述这个错误

<img width="1209" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/01811982-6902-4416-a109-923077fbea10">
如我截图中的说明。

### 复现步骤

所有的小说网站都这样。

### 其他相关说明

1. 能否自由编辑标题的大小？ 给个说明或者教程链接
2. 有些区域无法自由隐藏，就像我提交的图片中的地方，如何解决？

### 操作系统

Macos

### 浏览器

ARC

### 发生问题的网址

https://www.ddxs.info/read/183172/4929013.html

**Comment by Kenshin** [comment]
嗨，你需要使用这个插件 https://github.com/Kenshin/simpread/discussions/2620

**Comment by baizhusheng** [comment]
> 嗨，你需要使用这个插件 #2620

Thanks， 有用。

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭这个 Issues 了。

**Comment by baizhusheng** [comment]
> okay 没问题的话，我关闭这个 Issues 了。

ok 多谢
