### ISSUE TITLE
如何屏蔽特定的文字或者内容

### ISSUE THREAD

**Issue by baizhusheng** [Kenshin/simpread#6458]
### 请描述你的建议或任何内容

比如看小说的时候，会出现烦人的说明，如下图，即便当前页面去除了，后面的章节还是会出现，请问怎么一劳永逸的去除掉？
<img width="979" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/0ddee1df-001c-4f18-b94a-2da75c0f1d23">
<img width="662" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/f6168a6e-f534-4b5a-a31a-deba5b907695">

**Comment by Kenshin** [comment]
这个有点「麻烦」，其实是可以的，但可能并不能满足你的需求。

同样，我考虑下，应该可以出个新插件解决。

**Comment by baizhusheng** [comment]
非常感谢，这个不用管也OK，我有点轻微的强迫症。。。

**Comment by Kenshin** [comment]
没事，这个功能其实挺重要的，尤其是针对小说类网站，所以才考虑实时的。

因为之前也有用户提过类似的建议，但我一直没有想到如何解决。（直到你提到后我想到了一些思路）

**Comment by baizhusheng** [comment]
> 没事，这个功能其实挺重要的，尤其是针对小说类网站，所以才考虑实时的。
> 
> 因为之前也有用户提过类似的建议，但我一直没有想到如何解决。（直到你提到后我想到了一些思路）

这个插件有类似的功能，你看看能否作为参考，里面有一条是可以屏蔽某些字符
<img width="952" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/a1f04089-a757-4fff-bd30-f1ac6bcced38">

**Comment by Kenshin** [comment]
嗨

[关键词高亮与屏蔽](https://github.com/Kenshin/simpread/discussions/4416) 升级到 2.0.0，增加了**屏蔽关键词**的功能。

2.0.0 版功能
---

- `Add` [关键词屏蔽](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10037795)

- `Add` 当进入阅读模式后是否自动屏蔽关键词

- `Add` 支持 [快速添加高亮或屏蔽](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10041840)

- `Add` 调整 [高亮（或屏蔽）是触发时间](https://github.com/Kenshin/simpread/discussions/4416#discussioncomment-10041752)

- `Optimize` 选项卡界面更符合 **简悦插件 2.0** 规范

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/iuIlA8bU5S) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

## 关联

https://github.com/Kenshin/simpread/issues/4417

***

我关闭这个 Issues 了，有任何问题随时讨论~
