### ISSUE TITLE
能否增加一个“导出到Joplin”功能？

### ISSUE THREAD

**Issue by linkot** [Kenshin/simpread#646]
Joplin是一个免费的开源笔记记录和待办事项应用程序
[https://github.com/laurent22/joplin](https://github.com/laurent22/joplin)
笔记数据是掌握在自己手中可以存放到本地也可以和各种云同步,能够端到端加密。
还能使用第三方的Markdown编辑器阅读或者编辑笔记。
Joplin的网页剪辑可以允许允许第三方应用程序授权Token令牌访问Joplin。
这些功能配合简悦能特别方便把浏览的文章剪辑下来随时阅读，并始终由私人保管数据。

**Comment by Kenshin** [comment]
谢谢反馈，之前以及有朋友提过了，可以的。

但只能下个版本实现，或者我看看能否通过 `插件` 的方式实现。

**Comment by Kenshin** [comment]
@linonetwo 

谢谢对插件的喜爱，但目前暂停了个人申请插件这个需求。
你可以说下你的需求，如果并不小众，我会考虑下个功能加入这个功能。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

新版增加了对 [Joplin](http://ksria.com/simpread/docs/#/Joplin) 的支持，

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
