### ISSUE TITLE
稍后读页面无法打开阅读模式

### ISSUE THREAD

**Issue by baizhusheng** [Kenshin/simpread#6460]
### 描述这个错误

网页可以正常的打开阅读模式，但是稍后读不可以。如图所示。
<img width="1157" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/8a580eb3-3fac-4daf-957d-d1ec3092cafb">
<img width="1054" alt="image" src="https://github.com/Kenshin/simpread/assets/167600610/99080571-324e-42f5-9c15-c4f291216bbb">

### 复现步骤

同一个网站必然出现

### 操作系统

Macos

### 浏览器

ARC

### 发生问题的网址

https://user.guancha.cn/wap/content?id=619137

**Comment by Kenshin** [comment]
简悦在未做任何配置时，在内置的稍后读打开的是：这个页面的在线快照，有些网页会阻止这种行为，所以无法打开。

#### 解决方案

使用简悦的本地快照系统，即将这个页面加入稍后读时会自动生成本地快照，这是在稍后读打开的就是你在本地的文件（本地快照）

从功能需要通过助手才能使用，教程在这里 https://www.yuque.com/kenshin/simpread/wkswh7

#### 留意

如果你只是轻量级使用的话，其实不需要这么做，因为不是每个网页都无法在稍后读打开。

但一般来说简悦用户都希望将稍后读本地化（这也是简悦做为稍后读产品最特别也是最吸引人也是唯一可以这么做的产品。
