### ISSUE TITLE
导致 curseforge.com 空白

### ISSUE THREAD

**Issue by Lanyangzhi** [Kenshin/simpread#6464]
### 描述这个错误

默认配置、允许访问所有网页时导致特定网页空白
详见视频

### 复现步骤

https://github.com/Kenshin/simpread/assets/10362972/eedd2de0-8bfc-486f-9529-a3ba603f6ebd

### 操作系统

windows11

### 浏览器

edge_124.0.2478.51

### 发生问题的网址

www.curseforge.com

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347
