### ISSUE TITLE
obsidian同步报错

### ISSUE THREAD

**Issue by Osurelee** [Kenshin/simpread#6467]
### 描述这个错误

MacOS  同步助手1.2 之前在其他A电脑上同步成功，通过恢复配置在B电脑上使用，重新检查了配置，at快捷键同步时，同步助手报错 如图，实在是不知道怎么排查了，求助作者
![image](https://github.com/Kenshin/simpread/assets/45503612/6b9fb05d-ebdc-46b3-a597-e5c2651e2f59)

### 复现步骤

如描述

### 操作系统

MacOS

### 浏览器

Chrome

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Osurelee** [comment]
我是导入的离线配置文件。
不过，现在的报错又是这个了
![image](https://github.com/Kenshin/simpread/assets/45503612/507dda2c-e729-40ea-bba2-44f76688028c)

**Comment by Kenshin** [comment]
> 离线配置文件。

简悦没有「离线配置」文件的叫法.... 你是指 `simpread_config.json` 吗？

另外，无论是否导入 `simpread_config.json` 都跟同步助手截图的错误无关。

***

你的前后描述太「乱」了 😂 建议：

1. 重新描述你的问题（之前提到的问题如果没有了，请告诉我，或者之前的「不算」。

2. 请不要仅截图出错的提示，这没有任何有效信息（我没法通过这个截图知道你使用了什么功能等等）

3. 在详细描述第二点时，请告诉出问题的 URL 还是任意 URL 都有问题？

如果你的问题跟导入 Obsidian 有关系，可以考虑先看下这个教程自查下 https://www.yuque.com/kenshin/simpread/fr8zo5

**Comment by Osurelee** [comment]
不是的 ，现在还是提示保存失败，不知道因为什么，同样的配置家里的电脑就能用，唯一区别是安装了公司的一些证书和数据防泄漏工具，不知道有没有关系。搞不定，所以放弃用了，写了个py脚本半自动处理文档图片下载到本地。
![image](https://github.com/Kenshin/simpread/assets/45503612/1453e486-35e7-4f6c-b15f-dba83fa0fa5b)

**Comment by Kenshin** [comment]
> 唯一区别是安装了公司的一些证书和数据防泄漏工具，不知道有没有关系

如果确定配置文件是一致的话，那肯定是这个造成的。（因为你的这些会影响到网络环境）

> 不知道有没有关系。搞不定，所以放弃用了，写了个py脚本半自动处理文档图片下载到本地。

😂 你截图对应的功能跟你之前几次描述都没关系，这个截图对应的功能应该是 Cloudinary 图床 上传图片后的提示...

**Comment by Osurelee** [comment]
前几次的描述问题后面解决了，上图（保存失败那个）怎么也无法解决，如果对应是一个上传图床的操作，确实有可能失败，公司屏蔽了一些云存储和协作类的网站，麻烦了，谢谢

**Comment by Kenshin** [comment]
> 如果对应是一个上传图床的操作，确实有可能失败，公司屏蔽了一些云存储和协作类的网站，麻烦了，谢谢

是的，确实是开启 assets 图床造成的，你需要把下图的选项关闭

<img width="623" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0b3721c6-bf7a-408c-9f19-258d0f29f12e">
