### ISSUE TITLE
选中一段文字后整个程序卡住了

### ISSUE THREAD

**Issue by helenetdjj** [Kenshin/simpread#6468]
### 描述这个错误

选中一段文字后整个程序卡住了，无法关闭，需要重启chrome。

### 复现步骤

1.  在阅读模式下打开https://mp.weixin.qq.com/s/MVpRoZmI8ptJtb51eO2G5Q
2. 选中下面这段话：“如果你已经35+了，那接下来你需要把在职的每一天，都当成是最后一天来度过，然后疯狂的锻炼自己的综合能力，理解商业世界，积累人脉，给自己一些后路。。”
3. 程序就会卡住

### 操作系统

windows

### 浏览器

chome 124.0.6367.61

### 发生问题的网址

https://mp.weixin.qq.com/s/MVpRoZmI8ptJtb51eO2G5Q

**Comment by Kenshin** [comment]
嗨，我没有遇到你说的问题

1. 试试安装 https://github.com/Kenshin/simpread/discussions/5851 能否解决？
2. 出问题时是否开启了标注功能？

如果仍无法解决试试**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by helenetdjj** [comment]
1. 尝试安装了微信公众号辅助增强，没有解决。
2. 怎么算开启了标注功能？
3. 尝试“隐身模式下仅使用简悦的方式”，仍然会卡住。

**当前的执行流程是这样的：**
1. 打开网页https://mp.weixin.qq.com/s/MVpRoZmI8ptJtb51eO2G5Q
2. 右击进入简悦阅读模式
5. 找到这句话：“如果你已经35+了，那接下来你需要把在职的每一天，都当成是最后一天来度过，然后疯狂的锻炼自己的综合能力，理解商业世界，积累人脉，给自己一些后路。。”
6. 即使只选中了一个句号，也不会有问题，工具栏能跳出
![359a068c4b5da6736f3346ef4d945c5](https://github.com/Kenshin/simpread/assets/105281022/34d9359d-d0c7-4244-b220-88016f0c1b82)
7. 一旦选中了两个句号，就卡住了:
![f786d809400ae2eebf7e7e56d6e28f1](https://github.com/Kenshin/simpread/assets/105281022/77825399-ba8c-4010-8784-ee1904cfe6d8)

**Comment by Kenshin** [comment]
> 怎么算开启了标注功能？

下面这个图就算

![](https://github.com/Kenshin/simpread/assets/105281022/34d9359d-d0c7-4244-b220-88016f0c1b82)

***

我在开启标注模式后，确实重现了这个问题，研究了下应该是下面这个问题造成的

<img width="1503" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/264064fc-d7a7-408f-8f49-2ab91fea8b33">

### 解决方案

暂时没有好的解决方案，但你可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 把出问题的两个  `。。` 删除，然后就好使了。

<img width="1213" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/210e5bb8-dddf-4c16-bb51-775a0eb7db32">
