### ISSUE TITLE
一直卡在同步到坚果云

### ISSUE THREAD

**Issue by wumingluren** [Kenshin/simpread#6469]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/41581133/b14731e5-1e52-4990-a7b2-ff65da878efa)
不管是点击同步还是点击覆盖都一直卡在同步中，十多分钟都没反应。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/41581133/b14731e5-1e52-4990-a7b2-ff65da878efa)
不管是点击同步还是点击覆盖都一直卡在同步中，十多分钟都没反应。

### 操作系统

win11

### 浏览器

360急速x 119内核

### 发生问题的网址

无

**Comment by wumingluren** [comment]
![image](https://github.com/Kenshin/simpread/assets/41581133/6a3c6205-6abb-4ab0-a936-f9a2cd454c65)
坚果云绑定成功的时候没有创建这个目录

**Comment by wumingluren** [comment]
手动创建了这两个目录然后去同步还是不行

**Comment by Kenshin** [comment]
看下是不是这个问题造成的？

<img width="844" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/85f3c671-1b09-419a-896d-12e6c65a98ce">

**Comment by wumingluren** [comment]
> 看下是不是这个问题造成的？
> 
> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/81074/326170996-85f3c671-1b09-419a-896d-12e6c65a98ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTMzMzEsIm5iZiI6MTcxNDIxMzAzMSwicGF0aCI6Ii84MTA3NC8zMjYxNzA5OTYtODVmM2M2NzEtMWIwOS00MTlhLTg5NmQtMTJlNmM2NWE5OGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEwMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODRkM2QzYWZkYTUwYjdlNzY2MTYwZTBiZTVjNTQ5NGY1MTFiY2Q4ZDY0Mzc3MTdiNTkxODdiMGVmOGJlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aonYaF2UQPdZQcKYhtjbrrJUXBQa7oW_PaVuTAIG8Hg">

这个我配置了的，反复配置了好几遍也没有能自动在坚果云创建文件夹，最后我还手动创建了。

**Comment by wumingluren** [comment]
![image](https://github.com/Kenshin/simpread/assets/41581133/4759b821-93d2-4fb5-b8f9-abcb31dfdfc7)

**Comment by Kenshin** [comment]
坚果云输入的是你的 Email 与坚果云的授权码（注意：不是密码）

然后点授权时，如果输入无误（成功）的话会有明确提示。

不需要手动创建你提到的目录。

PS：如果方便的话，建议录屏给我看下。

**Comment by wumingluren** [comment]
> 坚果云输入的是你的 Email 与坚果云的授权码（注意：不是密码）
> 
> 然后点授权时，如果输入无误（成功）的话会有明确提示。
> 
> 不需要手动创建你提到的目录。
> 
> PS：如果方便的话，建议录屏给我看下。

![image](https://github.com/Kenshin/simpread/assets/41581133/86e9750c-94ca-4e70-b3c8-c7dd402f8e66)
点的第一下等了两分钟多都没反应，又点了一次就提示成功，之前每次也都很久然后提示成功。

**Comment by wumingluren** [comment]
> 坚果云输入的是你的 Email 与坚果云的授权码（注意：不是密码）
> 
> 然后点授权时，如果输入无误（成功）的话会有明确提示。
> 
> 不需要手动创建你提到的目录。
> 
> PS：如果方便的话，建议录屏给我看下。

找到问题了，原来用户名是邮箱，之前一直以为是应用名。
照理说之前的输入的用户名是错的，但是还每次提示绑定成功。

**Comment by Kenshin** [comment]
> 原来用户名是邮箱，之前一直以为是应用名。

😂 

> 照理说之前的输入的用户名是错

这是坚果云的 Bug （严格意义上也不算是 Bug，因为授权和 WebDAV 算两个 API，只要你输入的正确的，前者都 OK 但后者有很严格的权限。

**Comment by wumingluren** [comment]
> > 原来用户名是邮箱，之前一直以为是应用名。
> 
> 😂
> 
> > 照理说之前的输入的用户名是错
> 
> 这是坚果云的 Bug （严格意义上也不算是 Bug，因为授权和 WebDAV 算两个 API，只要你输入的正确的，前者都 OK 但后者有很严格的权限。

顺便问一下稍后读里面的内容如何备份到坚果云，目前坚果云只有一个json文件，里面只是存了稍后读的链接。
在设置和帮助文件里面没找到这块的内容，新手觉得文档好乱啊，一会是帮助文档，一会是语雀文档。

**Comment by Kenshin** [comment]
> 顺便问一下稍后读里面的内容如何备份到坚果云，目前坚果云只有一个json文件，里面只是存了稍后读的链接。

简悦的稍后读功能默认不保存用户的稍后读快照，如果你需要保存快照的话，需要同步助手，这是教程 https://www.yuque.com/kenshin/simpread/wkswh7

***

官方文档 → 基础功能（仅仅用来描述简悦扩展端的选项页上存在的功能说明）
语雀文档 → 教程合辑（你可以理解为官方文档功能的 Step by Step ）

**Comment by Kenshin** [comment]
如果是剪藏用户的话，建议直接使用简悦官方的配置库 https://www.yuque.com/kenshin/simpread/any457

**Comment by wumingluren** [comment]
> > 顺便问一下稍后读里面的内容如何备份到坚果云，目前坚果云只有一个json文件，里面只是存了稍后读的链接。
> 
> 简悦的稍后读功能默认不保存用户的稍后读快照，如果你需要保存快照的话，需要同步助手，这是教程 https://www.yuque.com/kenshin/simpread/wkswh7
> 
> 官方文档 → 基础功能（仅仅用来描述简悦扩展端的选项页上存在的功能说明） 语雀文档 → 教程合辑（你可以理解为官方文档功能的 Step by Step ）

感谢老哥

**Comment by Kenshin** [comment]
小事情，有任何问题随时 Issues

**Comment by Kenshin** [comment]
小事情，有任何问题随时 Issues

**Comment by Kenshin** [comment]
其实除了上面提到的两组文档外，还有一个专门用于简悦高阶玩家的用法合辑 https://github.com/Kenshin/simpread/discussions  🌚

**Comment by wumingluren** [comment]
> 其实除了上面提到的两组文档外，还有一个专门用于简悦高阶玩家的用法合辑 https://github.com/Kenshin/simpread/discussions 🌚

我用webhook接口添加了一条记录进去，在坚果云看到这条记录是存在的，然后在插件里面点击同步坚果云，提示的无需同步，数据一致，这是为什么呢？

**Comment by wumingluren** [comment]
强制从坚果云向下同步才拿到了刚才通过接口添加进去的一条数据。

**Comment by Kenshin** [comment]
> 我用webhook接口添加了一条记录进去，在坚果云看到这条记录是存在的，然后在插件里面点击同步坚果云，提示的无需同步，数据一致，这是为什么呢？

严格意义上说这算是个 Bug ，但一般来说 API 这个功能是用于 **同步助手的自动同步功能** 使用的，所以不会触发这个 Bug

而你提到的 https://github.com/Kenshin/simpread/issues/6469#issuecomment-2081445941 可以绕过这个 Bug 😂

不过，我觉得你的动手能力不错，如果不喜欢使用同步助手的话，可以考虑这么用，但注意的是每次在 PC 端要强制更新下你的配置文件。

**Comment by wumingluren** [comment]
> > 我用webhook接口添加了一条记录进去，在坚果云看到这条记录是存在的，然后在插件里面点击同步坚果云，提示的无需同步，数据一致，这是为什么呢？
> 
> 严格意义上说这算是个 Bug ，但一般来说 API 这个功能是用于 **同步助手的自动同步功能** 使用的，所以不会触发这个 Bug
> 
> 而你提到的 [#6469 (comment)](https://github.com/Kenshin/simpread/issues/6469#issuecomment-2081445941) 可以绕过这个 Bug 😂
> 
> 不过，我觉得你的动手能力不错，如果不喜欢使用同步助手的话，可以考虑这么用，但注意的是每次在 PC 端要强制更新下你的配置文件。

接口能不能添加一下跨域支持呢？我在飞书做了一个插件，添加到稍后读会报跨域。

**Comment by Kenshin** [comment]
> 接口能不能添加一下跨域支持呢？我在飞书做了一个插件，添加到稍后读会报跨域。

我应该做了跨域，把你需要的 API 告诉我下，同时也告诉我，你希望需要的功能以及在飞书上要做什么？如果缺失可以考虑增加此功能（只要功能需求合理）

**Comment by wumingluren** [comment]
> > 接口能不能添加一下跨域支持呢？我在飞书做了一个插件，添加到稍后读会报跨域。
> 
> 我应该做了跨域，把你需要的 API 告诉我下，同时也告诉我，你希望需要的功能以及在飞书上要做什么？如果缺失可以考虑增加此功能（只要功能需求合理）

https://api-wrap.simpread.pro/api/service/webhook/
就是这个webhook报的跨域，目前也只有添加到稍后读功能，没有做别的。

**Comment by Kenshin** [comment]
okay 我明天确认下。(我记得做了跨域）

PS：如果是 Developer 可以试试使用第三方 API 调试工具测试下。

**Comment by wumingluren** [comment]
> okay 我明天确认下。(我记得做了跨域）
> 
> PS：如果是 Developer 可以试试使用第三方 API 调试工具测试下。

我在本地开发环境已经测试好了的，就是部署上去不行。
