### ISSUE TITLE
导出到Markdown后 表格部分是html源代码，而不是Markdown的表格代码

### ISSUE THREAD

**Issue by Peter-JXL** [Kenshin/simpread#647]
例如保存https://www.cnblogs.com/wcwnina/p/8728391.html ，保存后表格部分是html代码
<table border="0">....</tbody></table>

**Comment by Kenshin** [comment]
谢谢反馈。

这应该是 Markdown 解析引擎的问题，这是个第三方的库，我先记 Bug ~

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了。

因为有些 Markdown Table 支持的毕竟有限，如嵌套就无法支持了，所以不如全部转换为 HTML，我综合的考虑了下，只有涉及到 Table 都会被强制转换为 HTML 结构，因为大多数 Markdown Editor 都支持直接解析 Table HTML e.g Tyora

接下来会考虑对导出的 Markdown 进行定制化，如 **是否将 Table 转换为 HTML** 等选项。

所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，

**Comment by skyoflovehc** [comment]
这个问题在2.x版本上还是存在的

**Comment by Kenshin** [comment]
> 这个问题在2.x版本上还是存在的

已经解决了这个问题，看这里的说明 https://github.com/Kenshin/simpread/issues/2783#issuecomment-912900513
