### ISSUE TITLE
he string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by wumingluren** [Kenshin/simpread#6470]
### 描述这个错误

使用api接口的报错提示
https://api-wrap.simpread.pro/api/service/webhook/<token>
![image](https://github.com/Kenshin/simpread/assets/41581133/02c1f5f6-1be9-4163-a4b6-654b3232532f)
![image](https://github.com/Kenshin/simpread/assets/41581133/8dabfa1d-9f93-4d4b-a23b-29a7ede79fc7)

### 复现步骤

如上

### 操作系统

win11

### 浏览器

接口操作

### 发生问题的网址

无

**Comment by Kenshin** [comment]
嗨，暂时不建议新用户使用 API 功能。

PS：因为你上一个 #6469 没有解决的话，是不太可能跑通 API 的

如果你希望了解 API 的话，可以看下这个教程 https://www.yuque.com/kenshin/simpread/ieu1w6
