### ISSUE TITLE
Notion：授权已过期，再次授权又过期

### ISSUE THREAD

**Issue by xiefumin1** [Kenshin/simpread#6473]
### 描述这个错误

在页面内不管使用简悦导入功能或者是notion导入插件功能，均提示  该页面。重新授权后，刷新进入仍然显示该现象。
![image](https://github.com/Kenshin/simpread/assets/128580269/1fca79a7-a8b8-4e08-8132-9bb944aebfa5)

使用notion解决方案12均无法解决。

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/128580269/be9390a7-7c31-40b5-aeb8-7bb4aa5c5b74)
1 打开页面
2 右下角导入到notion/插件触发导入到notion
3 显示无授权，页面自动打开简悦重新授权
4 授权成功，页面自动关闭回到文章
5 进行步骤2仍然重复显示无授权

### 操作系统

win11

### 浏览器

Microsoft Edge 版本 124.0.2478.67 (正式版本) (64 位)

### 发生问题的网址

任意网站均能复现https://mp.weixin.qq.com/s/wDp0wRoAKXioXRh0ll-AUA

**Comment by xiefumin1** [comment]
![image](https://github.com/Kenshin/simpread/assets/128580269/802f60c0-646e-42c9-a6c1-e94448673af9)
按照第二种方法测试，发现每次都会提示notion未登录。之后问题仍存在。我另一台电脑未产生这种情况，猜测是浏览器的问题。切换浏览器到edge版本 125.0.2535.6 (正式版本) dev (64 位)后问题解决。我回头换一下浏览器应该就好了

**Comment by Kenshin** [comment]
emmm原来如此 😂

出问题的浏览器是什么？

另外，也看下是否禁止了 Cookies 等。

**Comment by xiefumin1** [comment]
是Microsoft Edge 版本 124.0.2478.67 (正式版本) (64 位) 并没有禁止cookies，在其他电脑也并未复现该bug

**Comment by Kenshin** [comment]
😂 神奇...

总之，问题解决了就好，我关闭这个 Issues 有任何问题随时在这里沟通~

**Comment by Kenshin** [comment]
请在 #6473 讨论你的问题，我指下面两个回复...  😂 

https://github.com/Kenshin/simpread/issues/6439#issuecomment-2119292874  https://github.com/Kenshin/simpread/issues/6439#issuecomment-2119289709

我仍认为这只是你的 Edge 问题造成的，跟简悦无关。

> 今天重新尝试发现反复卸载简悦和插件，但是notion导出里面的notion授权不会消失，一直都存在

除非你导入的配置文件是一样的，否则不可能出现这个情况。

**Comment by xiefumin1** [comment]
> 请在 #6473 讨论你的问题，我指下面两个回复... 😂
> 
> [#6439 (comment)](https://github.com/Kenshin/simpread/issues/6439#issuecomment-2119292874) [#6439 (comment)](https://github.com/Kenshin/simpread/issues/6439#issuecomment-2119289709)
> 
> 我仍认为这只是你的 Edge 问题造成的，跟简悦无关。
> 
> > 今天重新尝试发现反复卸载简悦和插件，但是notion导出里面的notion授权不会消失，一直都存在
> 
> 除非你导入的配置文件是一样的，否则不可能出现这个情况。
我尝试过三种方式，1使用软件里面的高级版notion配置文件，2自行导出的配置文件，3不使用配置文件，直接清空配置重新安装插件。这三种方式“notion导出”里面的notion授权不会消失，是一致的，也不用重新填写token和页面，非常奇怪。这个我该如何在浏览器里面把对应的插件信息清除呢？我也觉得是edge的问题，#6439 那个老哥与我遇到问题的时间基本一致，都可能是egde的某个版本导致的。

**Comment by Kenshin** [comment]
> 我该如何在浏览器里面把对应的插件信息清除呢？

1. 登出你的 Notion 账户
2. 删除并重新安装简悦
3. 使用新的配置文件（即：重新安装后不导入你的配置文件），安装 https://github.com/Kenshin/simpread/discussions/4954
4. 安装后重启浏览器

再确认下你遇到的问题（我就不信还有问题 😂

***

注意：

1. 如果你导入的配置库的文件里面是内含一个 Demo Notion 测试账户的，所以你看到的就是已授权状态。
2. 如果你导入的自己的配置文件，这个配置文件如果授权过 Notion 自然再导入后也是授权状态。
