### ISSUE TITLE
在任何网页都无法进入阅读模式

### ISSUE THREAD

**Issue by DanShui-Yu** [Kenshin/simpread#6474]
### 描述这个错误

如题，无论使用默认快捷键AA、浏览器快捷键还是还是鼠标右键菜单都打不开阅读模式。已尝试数据中心修复，没有变化。有的网站上手动框选模式可以激活，但选完确定后还是原网页。请问该怎么办？

### 复现步骤

1. 打开浏览器
2. 打开任意网页
3. 尝试进入阅读模式
4. 无任何变化

### 其他相关说明

![image](https://github.com/Kenshin/simpread/assets/69069739/0ec30458-7255-47bd-a458-5dfb6c5aafb8)

还是很在意这3个莫名其妙的未来记录。我查过坚果云和本地的backup了，并没有日期异常的备份文件，删也不知道去哪删。

### 操作系统

win11

### 浏览器

edge最新版

### 发生问题的网址

所有网址

**Comment by Kenshin** [comment]
> 还是很在意这3个莫名其妙的未来记录。我查过坚果云和本地的backup了，并没有日期异常的备份文件，删也不知道去哪删。

简悦的历史记录结构 `simpread_config@20240430110627.json` → `20240430110627` → `2024年04月03日11:06:27` 产生的这条数据，所以对应你的未来日期则是 `simpread_config@202412311014233.json` 这个文件，你找下是否存在这个文件？

> 无论使用默认快捷键AA、浏览器快捷键还是还是鼠标右键菜单都打不开阅读模式。

1. **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰，随便找个网页 e.g. https://sspai.com/post/69972 看看是否正常？
2. 选项页和稍后读看下是否可以正常打开？

如果还是不行的话：

1. 备份好你的 `simpread_config.json`
2. 进入 http://localhost:7026/database/clean 里面有逐项修复，如：先重置 **阅读模式** 与 **聚焦模式** 的配置等。

如果还是不行，或不爱动手，可以把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6474

我帮你看下。

**Comment by DanShui-Yu** [comment]
> 所以对应你的未来日期则是 simpread_config@202412311014233.json 这个文件，你找下是否存在这个文件？
找到了！原来如此，本地显示的修改日期是24年1月1日，难怪之前没注意到

> 隐身模式下仅使用简悦的方式，排除其它扩展的干扰，随便找个网页 e.g. https://sspai.com/post/69972 看看是否正常？
1. 还是不能，跟一般网页的情况一样
2. 可以

> 进入 http://localhost:7026/database/clean 里面有逐项修复，如：先重置 阅读模式 与 聚焦模式 的配置等。
重置阅读模式配置并重启之后可以进了，但是再重启一次又不行了。。。隐私模式也不行，再反复尝试包括一键清理在内的各种清理依然不行

配置文件已发邮箱

**Comment by Kenshin** [comment]
问题解决了，是因为你的自定义站点出现一个错误的值造成的。

我给你发了正确的配置文件，请替换你的 `simpread_config.json`

**Comment by DanShui-Yu** [comment]
谢谢。不过自动化辅助增强和导出到ob的插件设置又双叒叕清空了😭这是正常现象吗

**Comment by Kenshin** [comment]
> 自动化辅助增强和导出到ob的插件设置又双叒叕清空了😭这是正常现象吗

应该不正常，不过你给我的版本就没有它们…

如果有安装插件管理器的话，重新设置一次就行了。

**Comment by DanShui-Yu** [comment]
谢谢，终于好了。不过插件设置又都清空了😂😂😂

**Comment by DanShui-Yu** [comment]
没法导出md标注到ob了😭😭😭为什么啊！html和全文都没问题，我明明按之前的设置一比一复刻的啊！

**Comment by DanShui-Yu** [comment]
有没有什么办法可以把插件设置独立备份啊😵‍💫真的是要吐了🤮🤮🤮那么多设置，说好只要弄一次的实际上都折腾多少次了，尤其是网址名单这种，好不容易收集起来的谁能记全啊

**Comment by DanShui-Yu** [comment]
为什么总是会莫名其妙的丢失配置，几天不用啥都没干也能丢，生成那么多多余的backup就是用来出错的吗？

**Comment by DanShui-Yu** [comment]
稍后读数据也会丢，标注好的文章隔段时间再进就只剩稀稀拉拉的几条标注了

![image](https://github.com/Kenshin/simpread/assets/69069739/cf738f24-a07d-41c8-a9d9-c16b6e952a36)

瞧这刚刚的数据，15分钟之内能给我丢三次。再这样下去真的只能把简悦当个全文导出器用了，本地手动修剪也比这样靠谱啊(╯‵□′)╯︵┻━┻

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6474#issuecomment-2087936709

如果安装了插件管理器的话，不会出现这个问题。

>  https://github.com/Kenshin/simpread/issues/6474#issuecomment-2087939040

同样，我不清楚你是如何操作的，任何功能都会有 Bug 这是难免的，但同样任何功能都不会经常出现 Bug，显然这不合理 😂

你可以翻翻 Issues 像你这样频繁丢数据的应该至此一个... 

所以我也不清楚你是怎么做的，最好的排查方案：

能否稳定复现，如果能稳定复现的话，请录屏。

> 稍后读数据也会丢，标注好的文章隔段时间再进就只剩稀稀拉拉的几条标注了

建议你看下 https://github.com/Kenshin/simpread/discussions/3768 是否是这个链接提到的情况造成的？

标注数据丢失也可能是因为原文的结构改变造成的，建议在 http://localhost:7026/unread/ 里面标注，不要在原文基础上标注（注意：原文结构改变并不是一个常态情况，很少会发生。

> https://github.com/Kenshin/simpread/issues/6474#issuecomment-2087941413 瞧这刚刚的数据，15分钟之内能给我丢三次

我没有通过这个图了解到丢三次这个情况，你是如何通过这个图判断丢失数据的？

#### 综上

1. 先排除是否是操作不当造成的，可通过 https://github.com/Kenshin/simpread/discussions/3768 纠正你的操作习惯。
2. 再此基础上看下是否可以复现这个错误。
3. 如果能复现的话，请录屏。

最简单的一个操作提示：

不要在多个 Tab 同时标注多个稍后读。（理论上没问题，但非常不建议这么做）

***

另外一个建议：

试试重新安装简悦，然后导入 `simpread_config.json` 看下能否彻底解决？

***

我关闭这个 issues 了，有任何问题随时跟我讨论。

**Comment by DanShui-Yu** [comment]
> 如果安装了插件管理器的话，不会出现这个问题。

一直用的插件管理器，但它就是说丢就丢没商量。。。

> 建议你看下 https://github.com/Kenshin/simpread/discussions/3768 是否是这个链接提到的情况造成的？

不是，我不调任何设置单纯一个网页连续标注也会丢，今天就是，标完关了刷新再进又是个全新的网页，稍后读都没进去（然而自动保存到本地的html好端端的）

> 标注数据丢失也可能是因为原文的结构改变造成的，建议在 http://localhost:7026/unread/ 里面标注，不要在原文基础上标注（注意：原文结构改变并不是一个常态情况，很少会发生。

我后面试试养成新习惯。。。原文结构改变包括简易编辑和 live Editor 吗？我以前碰到过修改部分原文内容之后前面的标注作废，自动 index+1 从头生成新本地文件的情况。这个标注如果没一次完成，下回又得从头再来，继续生成新文件（逼死强迫症）

> 我没有通过这个图了解到丢三次这个情况，你是如何通过这个图判断丢失数据的？

配置文件的大小突然发生改变，尤其是突然变小。通常出现这种情况就是数据丢了，我很有经验😂悲催的是就算倒回变小之前的备份配置也不一定能回来，我不可能每天都把以前的所有稍后读一一打开确认丢没丢，新加的稍后读倒是妥妥没有了，所以很多次干脆重配一遍了事，基本每次开数据中心检查配置文件都有错，尤其是第三项，麻了都。

![image](https://github.com/Kenshin/simpread/assets/69069739/0a42379e-4cdb-4faf-a2f1-6fee314bcc14)

> 再此基础上看下是否可以复现这个错误。

真的没有这样操作。。。我也不是新用户了怎么可能还犯这种低级错误。复现是复现过很多遍，但它都是猝不及防的，就像之前所说，有时候几天没用简悦，再一进阅读模式就发现这里丢那里丢了，我什么也没干，根本来不及录屏也不知道该录什么，频繁的时候周周都能给我爆，甚至一周爆两三次。我总不能每天一录十几个小时的屏吧😵‍💫

**Comment by Kenshin** [comment]
确实很诡异…你从另外一个角度考虑：如果频繁出问题，我自己这关都过不去… 😂

而且虽然有类似情况出现（个别用户提交）但都是偶发且大部分都是操作不当造成的。

像你这么频繁应该是唯一一个。

另外，你经常调整插件配置项吗？

***

今天太晚了，手机打字也不方便，我明天给你出一个解决方案再试试吧

**Comment by DanShui-Yu** [comment]
> 另外，你经常调整插件配置项吗？

并不。除了切换深浅色主题大半年基本都没怎么动过了

顺便，就在刚刚，它又双叒叕丢了。。。

![image](https://github.com/Kenshin/simpread/assets/69069739/60d38341-d034-4f0f-9646-6a614341534e)

一打开就这样

**Comment by DanShui-Yu** [comment]
![image](https://github.com/Kenshin/simpread/assets/69069739/1df0d264-54d0-4fa2-800f-92efc888e736)

下午一点半到六点四十这段时间我没用电脑，后面截止刚才也完全没有用简悦。疑惑很久的一件事是为什么在我根本没使用简悦的时段里也经常会生成新的备份？多到把我有用的备份都淹没在汪洋大海里找不到了？

**Comment by Kenshin** [comment]
> 后面截止刚才也完全没有用简悦。疑惑很久的一件事是为什么在我根本没使用简悦的时段里也经常会生成新的备份？

没有使用简悦？还是没有浏览器？

假设没有使用浏览器也没有使用简悦，当然不可能产生新数据。

***

## 重新设置

### 前提（务必严格遵循）

1. 务必要备份好你的配置文件
2. 重启浏览器，尽量关闭除了简悦以外其它扩展
3. 确保在设置时仅打开一个 Tab
4. 并不是每个插件都有问题，确认好有问题的插件（也就是配置项不存在的插件）

### 重新设置步骤

1. 先关闭同步助手的自动同步

    <img width="889" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f77963b4-2612-44b7-9e18-24009b1bd069">

2. 重启浏览器

3. 选项页 → 插件管理器 → 从配置文件导入全部插件
    <img width="916" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e575524f-18d2-4910-96aa-7e9ea23903f4">

5. 提示导入成功后重启浏览器

6. 选项页 → 插件管理器 → 找到配置项不存在的插件 → 删除它们（注意：还要删除插件管理器）

7. 重启浏览器

8. 重新安装上个步骤删除的插件（注意：一定要逐一安装）

9. 重启浏览器并打开 https://sspai.com/post/69972 （这时应该自动弹出插件设置项，然后设置，设置后保存）

10. 重启浏览器并打开 https://sspai.com/post/69972 确定此插件的配置是否保存成功，如果没问题的话，重复 8 ~ 9 步骤，一直到缺失插件安装完毕。

### 最后一步

安装插件管理器 https://simpread.ksria.cn/plugins/details/UEzvAXNSe5 ，然后按下图所示设置

<img width="490" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5c46fb53-5543-4a27-9c2c-5c1fee9de2b5">

设置完毕后，重启浏览器，打开选项页 → 共通 → 查看自动同步是否已正常打开。

### 测试

如自动同步已经正常打开，确保只有一个 Tab 的前提下进入 https://sspai.com/post/69972 随便找一个插件并修改它的配置，保存后刷新浏览器，查看此配置是否保存正常。

## 备注

其实上面提到的步骤看起来很多，但是大部分操作是多余的（如重启浏览器），但请务必确保重启浏览器，以免在配置时发生你不知道的问题造成错误。

其实上面的步骤就是 https://www.yuque.com/kenshin/simpread/fcw60u 提到的方式，只是更精细了些，为了防止你提到的各种奇葩问题。
