### ISSUE TITLE
这个网站保存成epub，图片有问题

### ISSUE THREAD

**Issue by rewvbfdhgf** [Kenshin/simpread#6477]
### 需要适配的新站

<已隐藏>

### 有需要请描述这个站的性质

这篇文章里面的很多图片，在这个网站上看没事，图片很大，但是如果我保存成epub或者pdf，在本地文件的图片就会非常小。谢谢。

**Comment by Kenshin** [comment]
嗨，我测试了下，使用 [同步助手的 Epub 打印方案](https://simpread.pro/docs/#/Sync?id=epub) ，没有问题。

1. 请告知你使用的 Epub 导出方案。（最好截图说明使用步骤以及相关设置）
2. 是仅这一个网页？还是任意？建议在 https://sspai.com/post/69972 测试下。

**Comment by rewvbfdhgf** [comment]
这个是我对epub的截图，图非常小。
![2024-05-05_23-20-52](https://github.com/Kenshin/simpread/assets/163216953/89ea87a3-d31e-4a4b-a5c1-06b577a4e663)

**Comment by rewvbfdhgf** [comment]
我用的就是原生epub，这个不用同步助手是无法使用这个原生epub功能的。
以下是我对同步助手相关的截图
![2024-05-05_23-27-25](https://github.com/Kenshin/simpread/assets/163216953/fdd91b29-74a7-41ec-af84-d42b35ad7381)

**Comment by Kenshin** [comment]
> 这个是我对epub的截图，图非常小。

emmm 确实如此。

#### 解决方案

你需要将主域名 `w****e.com` 加入到延迟加载列表，然后手动拉滚动条让全部图片均可显示后，再进入阅读模式，然后在导出 Epub 就没问题了。

<img width="1052" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/99f3235a-eb33-4df4-80cc-fcf840c63070">

导出效果

<img width="502" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cfd8fc0d-1738-4f0c-a7a8-c1eb654b4020">

**Comment by rewvbfdhgf** [comment]
成功了，谢谢

**Comment by Kenshin** [comment]
小事情，解决就好 👍 😄 

***

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 五星 + 好评，有可能务必好评下，昨天被一个无脑一星给弄恶心了... 🤯

**Comment by rewvbfdhgf** [comment]
好的
