### ISSUE TITLE
ChatGPT 需要重新适配阅读模式

### ISSUE THREAD

**Issue by rw1995** [Kenshin/simpread#6478]
### 描述这个错误

错误：Psychological Counseling Request

### 复现步骤

原文
![image](https://github.com/Kenshin/simpread/assets/37976371/f726384b-7bd8-4135-a045-a9d858f5c7f8)

错误展示
![image](https://github.com/Kenshin/simpread/assets/37976371/db40d5ef-b581-4ab0-9ca7-148695d2f3f1)

### 操作系统

win11

### 浏览器

chrome

### 发生问题的网址

chatgpt

**Comment by rw1995** [comment]
@Kenshin

**Comment by Kenshin** [comment]
收到~

 难道它又双叒叕改版了？（这半年已经适配四次了... 😂

我明天确认下，谢谢反馈... 👍

**Comment by Kenshin** [comment]
嗨，ChatGPT 辅助增强插件更新到 **1.2.0**，主要适配了 ChatGPT 最新版界面。


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/8CjJLsNUKU) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论。

**Comment by yyzxq1** [comment]
![image](https://github.com/user-attachments/assets/efb0d72a-754b-4e1c-a804-1be779f14e03)
![image](https://github.com/user-attachments/assets/4f50d143-1ead-4ba1-8b2b-7cdccb462804)
![image](https://github.com/user-attachments/assets/e5faddea-40cf-4fbc-9e4f-ced87a69a571)
@Kenshin

**Comment by yyzxq1** [comment]
获取不到chatgpt的正文，需要手动框选
![image](https://github.com/user-attachments/assets/557dc27f-df71-4645-a250-afc3ac8f95a1)
![image](https://github.com/user-attachments/assets/48fa127b-6a70-4c9d-bb65-65f8c567ee3b)
手动框选后仍然提示无法适配。
已经安装chatgpt辅助插件，同步适配站点，开启延迟加载。

**Comment by rw1995** [comment]
@Kenshin 还 chatgpt貌似又改变啦， 能否重新适配下？

**Comment by Kenshin** [comment]
@rw1995 

收到

这「货」基本上每几周就改一次 😂

**Comment by rw1995** [comment]
恐怖的维护频率
1453681314
***@***.***
---- 回复的原邮件 ----
发件人Kenshin ***@***.***>发送日期2024年11月12日 ***@***.***>***@***.***>,
***@***.***>主题Re: [Kenshin/simpread] ChatGPT 需要重新适配阅读模式 (Issue #6478)
@rw1995
收到
这「货」基本上每几周就改一次 😂

**Comment by Kenshin** [comment]
@rw1995

也可以从另外一个角度说：它「极度」不稳定  😅  🌚 （不是说它的服务，而是说它的页面呈现逻辑）
