### ISSUE TITLE
[Bug]新版本导出的配置文件日期是前一天

### ISSUE THREAD

**Issue by lirenchong** [Kenshin/simpread#648]
"version":"1.1.4"

比如现在的时间是 `2020-02-04 05:34:35`
但导出配置文件到本地写的日期是 `simpread-config-2020年02月03日 04_41_55.json` 前一天的。

![image](https://user-images.githubusercontent.com/26704289/73692873-23915f80-4710-11ea-9e59-a2eb4e6a788c.png)

最后终于在同步时候的提示框里面发现了这个 bug！

所以，之前反复在折腾的一个问题就是：因为 3 日晚上 18:36 左右有备份过一个文件，同步到坚果云。但在高级设定里做了修改后，始终提示「远程文件较新」，多个浏览器都是这样，感觉非常莫名其妙。最后是把坚果云同步里面的 `simpread_config.json` 文件删除后搞定的。

所以，问题出现于 2020-02-03 18:36 之后。

顺便建议：同步配置的时候，能不能提供一个不管三七二十一，强制把现在的配置上传上去或下载下来的两个选项？

**Comment by Kenshin** [comment]
谢谢反馈~ 

应该是 `UTC` 时间的问题... 我看下。
但这个 Bug 不影响 `同步功能` 因为既然都是 UTC 时间就没问题。

***
`强制` 上传/下载 的功能，可以考虑下。

***

祝：一切都好~

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
