### ISSUE TITLE
与维基词典冲突

### ISSUE THREAD

**Issue by DanShui-Yu** [Kenshin/simpread#6483]
### 描述这个错误

在打开简悦扩展的情况下，搜索出的结果会很快消失在界面上（并没有进入阅读模式，仅保持插件开启状态）

### 复现步骤

https://github.com/Kenshin/simpread/assets/69069739/5b8915c9-861f-427b-b477-51ab90669dca

### 操作系统

win11

### 浏览器

edge124.0.2478.80 (正式版本) (64 位)

### 发生问题的网址

https://zh.wiktionary.org/wiki/%E5%AF%BC

**Comment by Kenshin** [comment]
嗨，解决方案请看这里 https://github.com/Kenshin/simpread/discussions/2347

我关闭这个 Issues 了，有任意疑问随时回复~
