### ISSUE TITLE
notion授权失败

### ISSUE THREAD

**Issue by wsgehaishan520** [Kenshin/simpread#6489]
### 描述这个错误

<img width="1087" alt="image" src="https://github.com/Kenshin/simpread/assets/45267428/eb090c55-af30-4c24-a8f7-3c69244b4365">
成功获取到了notion 保存目录
<img width="1214" alt="image" src="https://github.com/Kenshin/simpread/assets/45267428/e121096d-181c-436e-a533-914cee77c0a3">
点导出的时候，提示授权失败
<img width="764" alt="image" src="https://github.com/Kenshin/simpread/assets/45267428/17938bab-1837-451c-80eb-82bb29d342d0">

### 复现步骤

导出配置文件到其他浏览器，比如chrom，可以成功保存，无报错。但是相同配置文件在edge里，就提示授权。在阅读下点击保存到notion，提示未授权，跳到授权页面，提示授权成功，3S退出后，保存问题依旧。edge里，阻止第三方cookie也已关闭

### 操作系统

windows 11

### 浏览器

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.

### 发生问题的网址

https://www.baidu.com/index.php?tn=mswin_oem_dg&ch=33

**Comment by Kenshin** [comment]
emmm

同样的配置在 Chrome 没问题，但 Edge 无法使用.... 有点意思。

你可以试试（Edge）：

1. 退出 Notion 账户
2. 重启浏览器
3. 登录 Notion 账户
4. 重启浏览器
5. 打开 https://sspai.com/post/69972 （只是测试而已）

开始重新授权 Notion Page 留意下面的步骤

<img width="519" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/22936b5b-bed0-4b08-9c8a-76203a7af8af">

接下来

<img width="521" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/162c88b4-233b-46a6-b104-7f915b487118">

**Comment by wsgehaishan520** [comment]
问题依旧，目前有没有已知什么插件会导致冲突吗？

**Comment by wsgehaishan520** [comment]
<img width="876" alt="image" src="https://github.com/Kenshin/simpread/assets/45267428/6f79b5dd-fa50-4413-a415-1ca5eebb2018">
这个包导致的验证不通过

**Comment by wsgehaishan520** [comment]
我对比了一下正常响应包和未正常包，发现未正常包，发包的时候并没有携带cookie导致验证失败

**Comment by Kenshin** [comment]
> 问题依旧，目前有没有已知什么插件会导致冲突吗？

okay 那就不是 Notion 账户造成的问题，[这个步骤](https://github.com/Kenshin/simpread/issues/6489#issuecomment-2104354521) 用来排除 Notion 账户问题。

> 我对比了一下正常响应包和未正常包，发现未正常包，发包的时候并没有携带cookie导致验证失败

这么看的话，还是 Cookies 造成的问题。

我感觉你的动手能力不错，所以你可以试试能否在安装一个 Edge Dev 版本的浏览器（跟你的 Edge 可以共存），然后看下是否正常？

我记得 Edge 有重置配置的功能（理论上应该也有导出配置的功能），如果 Edge Dev 没问题的话，你可以试试将 Edge 重置。

**Comment by wsgehaishan520** [comment]
我本身就是用dev版本, 失败后，卸载了dev，现在用的正式版本，并且清理了所有数据和插件。相当于全新的，但还是获取不到cookies

**Comment by wsgehaishan520** [comment]
已解决，实在找不到原因了，只能清空浏览器所有配置 了。代价很大。。。位置是C:\Users\YourUserName\AppData\Local\Microsoft\Edge\User Data

**Comment by Kenshin** [comment]
😂

PS：我记得之前也有个用户遇到过类似的情况，也是 Edge 也是类似 Cookies 无法传入。

PPS：Edge 应该具有更改账户的功能（每个账户拥有独立的 User Data）

PPPS：如果你确定没有改动过任何 Edge 配置的话，小概率是因为 Edge 的 Bug
