### ISSUE TITLE
Add keyboard support for Save to Notion

### ISSUE THREAD

**Issue by swj1442291549** [Kenshin/simpread#649]
```
        nt: {
            "kbd"  : "Nt",
            "type" : "notion",
            "desc" : "保存到 Notion",
        },
```

**Comment by Kenshin** [comment]
嗨，谢谢反馈，确实忘记加 `Notion` 的快捷键了。
我先记 Bug ~

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题**

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
