### ISSUE TITLE
站点集市安装站点后消失（附解决方案）

### ISSUE THREAD

**Issue by Xinhg** [Kenshin/simpread#6491]
### 描述这个错误

在站点集市安装站点后，自动跳回选项页，显示安装成功。两秒后自动刷新，站点消失

### 复现步骤

1. 打开站点集市
2. 安装任意站点
3. 等待表演

https://github.com/Kenshin/simpread/assets/59286221/f68057f5-76a2-452a-9206-585e69e286c1

### 操作系统

macOS

### 浏览器

Arc1.42.0

### 发生问题的网址

https://simpread.ksria.cn/sites/

**Comment by Kenshin** [comment]
嗨，是不是使用了同步助手的自动同步功能，如果是的话，解决方案 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k

**Comment by Xinhg** [comment]
OKOK，按照解决方案弄好了

**Comment by Kenshin** [comment]
哈，解决就好。
