### ISSUE TITLE
在React官网遇到的代码段增强出错问题

### ISSUE THREAD

**Issue by MusherM** [Kenshin/simpread#6497]
### 请选择

代码高亮

### 发生问题的网址

https://zh-hans.react.dev/learn/conditional-rendering

**Comment by MusherM** [comment]
出问题后的渲染页面：
<img width="1921" alt="image" src="https://github.com/Kenshin/simpread/assets/50447418/1c6fb90d-f632-4c62-881a-655cd0fdece9">

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347

我关闭这个 Issues 了，有任意问题随时在这里沟通~
