### ISSUE TITLE
求适配WSJ和经济学人站点

### ISSUE THREAD

**Issue by Murphisensei** [Kenshin/simpread#65]
大部分国外网站感觉都没有怎么适配，求博主更新啦

**Comment by Kenshin** [comment]
@Murphisensei 
目前只针对国内的常用网站做了阅读模式的配置，还未开始对非中文的网址做。
`1.1.0` 会上线社区版，到时候会将这些站进行分类以及可以自行添加新站，到时候适配阅读模式的站就会增加很多。

**Comment by Kenshin** [comment]
已适配，但由于这两个网址属于国外的新闻类网站，目前还未有关于国外网站的适配，所以等 `1.1.0` 上线后，会关闭此 `issues`

PS：基于某些众所周知的原因，所以暂时无法上线它们。

**Comment by JackChen007** [comment]
可以参考instant view。Telegram自动跳过 paywall.

**Comment by Kenshin** [comment]
@JackChen007 
🐎 意思？ 😳

**Comment by Kenshin** [comment]
关于这些方案，可以看 关联问题 https://github.com/Kenshin/simpread/issues/65

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，将关闭 issues 。

增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)

你可以暂时使用这个功能来实现阅读模式。

**Comment by Kenshin** [comment]
新增了一批新站，请更新最新的适配列表，详细操作请看 [手动更新](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%90%8C%E6%AD%A5%E9%80%82%E9%85%8D%E5%88%97%E8%A1%A8) ，此 issues 将关闭。

除此之外，还包括一批「不存在」的网站，如上述提及的，具体操作方式请看下图
![image](https://user-images.githubusercontent.com/81074/40884334-501fe6c8-6744-11e8-8d39-3ffa6ed2e41a.png)
