### ISSUE TITLE
偏好设置页面title乱码

### ISSUE THREAD

**Issue by xiefumin1** [Kenshin/simpread#6502]
### 描述这个错误

偏好设置页面title乱码，页面无法点击和刷新
![image](https://github.com/Kenshin/simpread/assets/128580269/1a40b970-6be4-4f01-9a40-4faf1c660000)

### 复现步骤

1 打开一个页面
2 点击变成阅读模式
3 导入notion
4 倒入失败，显示授权过期
5 点击插件进入偏好设置，可见乱码

### 操作系统

win

### 浏览器

egde

### 发生问题的网址

https://www.jianshu.com/p/d0b096426a0d

**Comment by Kenshin** [comment]
重启浏览器即可解决。

另外，你使用的 Notion 有些过时了，新版方案请使用 https://github.com/Kenshin/simpread/discussions/4954 提到的方案。
