### ISSUE TITLE
界面新闻阅读模式下，内容被渲染了 2 次

### ISSUE THREAD

**Issue by alexinea** [Kenshin/simpread#6503]
### 描述这个错误

目前只有界面新闻出现这个问题，样例 url:  https://www.jiemian.com/article/11171470.html

内容被渲染了两次：
![image](https://github.com/Kenshin/simpread/assets/980129/912e7046-8d7e-47f2-b222-0b736bf5a0c1)

### 复现步骤

1、打开网页
2、A A
3、阅读模式下，内容被渲染了两次

### 其他相关说明

此外，如果我对第一遍渲染的文章做了标记，那么第二遍渲染也会一并显示这个标记，如：

标题下的第一次渲染做了标记：
![image](https://github.com/Kenshin/simpread/assets/980129/85b1f335-4f2e-4e3a-85d1-a443a0afb54e)

第二次渲染中也一并出现了标记（红色为第一次渲染区域，蓝色为第二次渲染区域）
![image](https://github.com/Kenshin/simpread/assets/980129/37c6fc88-8eb0-48c2-a716-9155c0c0eac5)

### 操作系统

Windows 11

### 浏览器

Edge / Arc

### 发生问题的网址

https://www.jiemian.com/article/11171470.html

**Comment by Kenshin** [comment]
emmmm 

我这边没有复现，你可以这样排查下：

1. 请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

2. 更新适配规则（更新后重启浏览器）

   <img width="953" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/aba30c67-b5ca-4a45-a081-ca2540d2e647">

3. 确保是官方适配源

   <img width="470" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4deb695d-6e4c-45a8-9f1d-325d8f4b484e">

***

如上述方式都无法解决

1. 试着更换另外一个浏览器，仅安装简悦后测试（无需任何设置）

2. 试试把全部的插件都暂时禁用

**Comment by alexinea** [comment]
似乎是没有启用【官方适配源】的缘故，启用后就好了。

**Comment by Kenshin** [comment]
原来如此 👍 

我关闭这个 Issues 了~

PS：Issues 基于 Markdown 的讨论形式，所以具有一定条理性，而 IM 并不具有这种形式，所以没有任何条理性，线性对话，导致回复问题条目非常差劲。

***

发现是老用户了 👍 不知道评分过吗？

如果没有的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评  😉 😁 👍
