### ISSUE TITLE
新站适配：虎嗅文章页

### ISSUE THREAD

**Issue by gradypark86** [Kenshin/simpread#6507]
### 描述这个错误

虎嗅图文正文中包含括号的内容，在简悦阅读模式下缺失。
例：
1. https://www.huxiu.com/article/3046147.html
2. https://www.huxiu.com/article/3050141.html

### 复现步骤

1. 下图为第一个链接原文页面，高亮处为括号部分。
<img width="877" alt="image" src="https://github.com/Kenshin/simpread/assets/39909237/241e3af0-0a0a-4faa-aa6d-da21420d668d">

2. 以下为简悦阅读模式下，仅显示括号，括号内文字缺失。
<img width="918" alt="image" src="https://github.com/Kenshin/simpread/assets/39909237/b0ec7956-8501-49d1-9fbf-626b39e757be">

3. 下图为第二个链接原文页面，高亮处为括号部分。
<img width="876" alt="image" src="https://github.com/Kenshin/simpread/assets/39909237/adb2459c-8674-4dcc-8bd6-bb118224294b">

4. 以下为简悦阅读模式下，这个连括号都不显示了。
<img width="913" alt="image" src="https://github.com/Kenshin/simpread/assets/39909237/6078237b-70f5-4dd2-8353-a4b07053611e">

### 其他相关说明

可以看到第一篇图文括号内文字为灰色，括号本身是黑色，则简悦阅读模式显示括号。第二篇中括号本身也为灰色，则简悦阅读模式全部不展示。

### 操作系统

macOS

### 浏览器

Vivaldi 6.7.3329.31, Chrome 124.0.0.0

### 发生问题的网址

见上

**Comment by Kenshin** [comment]
谢谢反馈，确实如此，是因为这个站没有适配造成的，我会考虑适配的。

虎嗅应该适配了，但这个 URL 规则可能是新的，所以出现了这个情况，你临时使用下图所示的方式

<img width="1025" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5ce3f553-08e2-449e-8491-3f041bc14cbe">

适配后我会在这里通知你~

**Comment by Kenshin** [comment]
嗨，这个网站已适配完毕，如何更新请看下图

<img width="924" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0e94adad-e103-46d3-9582-10069a07abd1">

细节请看 https://github.com/Kenshin/simpread/discussions/2870

***

我关闭这个 Issues，有任何问题请随时在这里讨论~
