### ISSUE TITLE
访问osgeo中国的ogc标准页面显示异常,

### ISSUE THREAD

**Issue by wuqi** [Kenshin/simpread#6509]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/1532967/ebaf5373-ce11-4153-9216-e8148c55bb6f)
https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html  访问此页面,功能无法使用,正常显示在原文下面

### 复现步骤

1. 访问 https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html
2. 打开简悦
3. 复现

### 操作系统

windows10

### 浏览器

edge  vivalid

### 发生问题的网址

https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347

PS：我这边没问题。

**Comment by Kenshin** [comment]
原页面

<img width="1820" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/3b7ca00c-f82b-4211-b340-0c639de32f69">

阅读模式效果

<img width="1626" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1f5589a7-16a4-416e-b7f7-e7b9809cdaa2">

**Comment by wuqi** [comment]
> ### 描述这个错误
> ![image](https://private-user-images.githubusercontent.com/1532967/333003457-ebaf5373-ce11-4153-9216-e8148c55bb6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTMyMjQsIm5iZiI6MTcxNjUxMjkyNCwicGF0aCI6Ii8xNTMyOTY3LzMzMzAwMzQ1Ny1lYmFmNTM3My1jZTExLTQxNTMtOTIxNi1lODE0OGM1NWJiNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMDEwODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjYxMTdkOGI5MGJiZjRhYzU4OTEyZmY4YTAwZTg5MzkwZGMzZjMzOWRhOTQwOGI4Y2NlMTczMTI2MzA4ZWNiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZzpC06QqvdQpyFroEXYnpKuIzfTC9OKTj8hWOJI539w) https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html 访问此页面,功能无法使用,正常显示在原文下面
> 
> ### 复现步骤
> 1. 访问 https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html
> 2. 打开简悦
> 3. 复现
> 
> ### 其他相关说明
> _No response_
> 
> ### 操作系统
> windows10
> 
> ### 浏览器
> edge vivalid
> 
> ### 发生问题的网址
> https://www.osgeo.cn/doc_ogcstd/ogc_standard/ch02_chapter1/chapter.html

可以正常显示了,但是按钮功能依然不正常

**Comment by Kenshin** [comment]
这个暂时没法解决，这个网站阻止了一部分（你看到的图标）的显示 😂
