### ISSUE TITLE
Chrome 上 简悦聚焦/阅读模式 无响应

### ISSUE THREAD

**Issue by kanokaakiko** [Kenshin/simpread#651]
Chrome浏览器
不论是通过使用自定义的快捷键, 还是右键菜单里启动, 或者是从Chrome右上角的Extension菜单里右键启动, 不论是阅读模式还是聚焦模式, 在sspai和微信公众号页面试过, 没有任何响应.

看了之前 #420 的问题, 不知道是不是类似情况, 但是在 [https://sspai.com/post/39491](https://sspai.com/post/39491) 页面右上角没有看到红色的 icon... 并且有尝试过手动同步适配列表, 关于页面显示当前适配了 327 类网址.

有试过把其他所有extension全部禁用, 并且从Chrome设置里初始化, 然后重新安装了简悦, 但是依然打不开阅读/聚焦模式...

P.S. 不确定有没有联系, 很奇怪的事情是, 在我 Dark Reader (一个网页暗色模式的extension) disable 的情况下, 诸如微信公众号和sspai文章页面依然会是黑底白字 (即便我所有extension全部关掉后刷新页面也是如此) 这个尝试实在美国时间(我的所在地)夜间进行的. 不确定有没有影响...? 但是用 Edge浏览器打开上述网页都是白底黑字. 所以可能无关?

真的不知道是什么情况了... 之后我在MacBook笔记本上试试, 看看简悦能不能 work...

```
Windows 10 Pro 1909 Build 18363.628
Chrome 80.0.3987.87 (Official Build) (64-bit)
```

**Comment by Kenshin** [comment]
真是很奇怪的问题...

你试试访问 https://sspai.com/post/58627 然后看看 Chrome DevTools 的控制台有什么提示？把出错提示截图给我看看。

**Comment by kanokaakiko** [comment]
![image](https://user-images.githubusercontent.com/33431741/74303351-77f79900-4d27-11ea-8128-1611cd09b19a.png)
抱歉回复地很不及时, 像我之前说的, 我关掉了 Dark Reader 之后sspai页面依然是暗色调... 然后这个不知道是不是你提到的 "控制台"

![image](https://user-images.githubusercontent.com/33431741/74303446-db81c680-4d27-11ea-88e1-05ddc1cded66.png)
另外这个是在 Dark Reader 打开着的情况下↑

**Comment by Kenshin** [comment]
确实不清楚是什么原因了...

要不方便的话，试试 Edge 看看有没有这个问题？或者你把 **配置文件导出** 给我，我看看。

**Comment by kanokaakiko** [comment]
emmm 用了 Edge 浏览器打开那个sspai网页, 右下角显示绿底白字的简悦, 通过 AA 或者 AS 只会在右上角弹窗 "当前页面无法使用阅读模式"... (我没有导入之前chrome上的配置文件

这个是chrome上的配置文件↓ (改格式为.json
[simpread-config-2020年02月12日 01_40_17.txt](https://github.com/Kenshin/simpread/files/4190228/simpread-config-2020.02.12.01_40_17.txt)

好消息是我再 MacBook 上的chrome试了下, 可以正常使用

**Comment by Kenshin** [comment]
> 用了 Edge 浏览器打开那个sspai网页, 右下角显示绿底白字的简悦

？ 你是不是安装了 **简悦 · 轻阅版** ？也就是 Tampermonkey 里面看看有没有简悦？如果有的话，请不要同时使用 **插件版 与 轻阅版** 。

**Comment by kanokaakiko** [comment]
啊我有点懵了... Edge 浏览器里点击Tampermonkey 可以看到 `简悦 (Simpread) 轻阅版` 几个字, 我不知道我有没有安装插件版... 如果我有安装给怎么卸载..? (不过关键是我基本不怎么用 Edge... 这个问题解决了好像也无济于事... 我试试把 Chrome 重装一下再看看会怎么样

也辛苦开发者大大不停地解决我的问题了 (抱拳

**Comment by Kenshin** [comment]
> 点击Tampermonkey 可以看到 简悦 (Simpread) 轻阅版 几个字

自然是安装了轻阅版。

如果你不需要轻阅版的话，请从 Tampermonkey 删除，插件版就应该好使了。

**Comment by kanokaakiko** [comment]
啊我不管 Edge 了.. 我重装了 Chrome 现在可以用了... (这个终极方案都不能行的话那就真没办法了... 所以再有其他人有类似不知道是什么原因不能用的情况就建议他们重装吧...虽然比较折腾) 感谢开发者 (我是因为现在支持了导出到 Notion 所以重新想用简悦的, 谢谢开发者大大的辛勤付出~)

**Comment by Kenshin** [comment]
搞定就好。

这个问题应该是你曾经在 Edge 安装了 轻阅版 后又安装了 扩展版导致的。

没问题的话，我将关闭这个 issues 了~  😃
