### ISSUE TITLE
在使用Markdown增强辅助导出时，提示“扩展端需要先确保你的账户为高级账户后才能使用此功能。”

### ISSUE THREAD

**Issue by pencilboxshotmail** [Kenshin/simpread#6510]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/111672485/b085b619-f05d-4dc8-904d-8e03bc91b2a9)
![image](https://github.com/Kenshin/simpread/assets/111672485/75df200b-e543-43e9-8ac3-3097e6b9972b)

### 复现步骤

在使用阅读模式进行标注时，提示“扩展端需要先确保你的账户为高级账户后才能使用此功能”。标注是使用了markdown增强辅助的模板。
但是我确实是高级账户。

### 操作系统

Win11

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/

**Comment by Kenshin** [comment]
嗨

估计是你的高级账户「掉了」，请使用 https://www.yuque.com/kenshin/simpread/sw4m21 提到的方式重新授权。

注意：在授权前请重启浏览器，成功授权后也重启浏览器。

一般情况，多见于首次升级为高级账户但没有根据提示重启浏览器造成的。
