### ISSUE TITLE
在稍后读中突然出现授权提示

### ISSUE THREAD

**Issue by maxwell5566** [Kenshin/simpread#6514]
### 描述这个错误

在稍后读中突然出现授权提示，提示扩展端需要高级账户才能使用其功能，但在账户里面已显示是高级账户了。

### 复现步骤

在稍后读中突然出现授权提示，提示扩展端需要高级账户才能使用其功能，
![image](https://github.com/Kenshin/simpread/assets/104042614/1ec02a81-8403-4883-b2fa-063d8be22257)
但在账户里面已显示是高级账户了。
![image](https://github.com/Kenshin/simpread/assets/104042614/dea61c36-0f37-4560-bcf6-14c91ddaf89a)

### 操作系统

window11

### 浏览器

edge

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
可能是你的高级账户「掉」了。

使用 https://www.yuque.com/kenshin/simpread/sw4m21 重新授权，建议先重启浏览器然后再授权，授权成功后再次重启浏览器。
