### ISSUE TITLE
题图不现实了

### ISSUE THREAD

**Issue by lxmwwl** [Kenshin/simpread#6515]
### 描述这个错误

如果页面本身没有题图就不显示题图

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/124525616/f99ccd16-7d96-4dbb-bf8b-500fdb5a66c1)

### 操作系统

win11

### 浏览器

版本120.0.6099.200（正式版本）(64位)，chrome

### 发生问题的网址

所有

**Comment by Kenshin** [comment]
我这边没有遇到你的问题，随便找个页面 e.g. https://www.zhihu.com/question/626962666/answer/3505911018

<img width="1808" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/232aec41-3e08-4782-96ee-00eac21e7164">

这是我的题图选项，你可以对比下。

<img width="487" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4dc8cfdc-67ff-443b-bc52-79a3754ddb88">
