### ISSUE TITLE
授权notion无响应

### ISSUE THREAD

**Issue by FB208** [Kenshin/simpread#6522]
### 描述这个错误

授权notion无响应

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/8197476/cfa745e7-eb8c-499a-b90e-626fed6c6aab)

### 操作系统

Windows11

### 浏览器

edge

### 发生问题的网址

https://www.yuansudong.net/document/Ffmpeg/%E4%BB%8B%E7%BB%8D.html

**Comment by Kenshin** [comment]
请使用插件端方案 https://github.com/Kenshin/simpread/discussions/4954 

PS：扩展段内置的 Notion 其实也没问题。
