### ISSUE TITLE
Dropbox无法同步

### ISSUE THREAD

**Issue by Qiaofanxing** [Kenshin/simpread#6523]
### 描述这个错误

在授权Dropbox后，仍然停留在页面"此页为授权页面，授权成功后将会自动关闭"，点击同步仍然提示需要授权。Dropbox访问没有问题，且“应用”中已经能看见SimpRead
![image](https://github.com/Kenshin/simpread/assets/41269801/5a0f0236-c856-4f02-bcaf-a1c9a5df4680)
![image](https://github.com/Kenshin/simpread/assets/41269801/1b91d6ba-4cbd-41d4-a2d2-1cce49cad08a)

### 复现步骤

1.点击“同步到你的Dropbox账户”
2.弹出授权页面，且无法正常授权

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

/options/options.html

**Comment by Kenshin** [comment]
嗨，Dropbox 的授权没问题，但不建议使用 Dropbox 方案，因为 Dropbox 更改了 Token 的授权时间，非常短...
