### ISSUE TITLE
关于 safrai版无法下载问题

### ISSUE THREAD

**Issue by cyx951211** [Kenshin/simpread#6524]
### 描述这个错误

进入 https://greasyfork.org/zh-CN/scripts/39998，并选择 安装；
使用 暴力猴 的用户请使用 https://raw.githubusercontent.com/Kenshin/simpread-little/master/src/userscript/simpread.js 安装

### 复现步骤

显示已删除
进入 https://greasyfork.org/zh-CN/scripts/39998，并选择 安装；
使用 暴力猴 的用户请使用 https://raw.githubusercontent.com/Kenshin/simpread-little/master/src/userscript/simpread.js 安装

### 操作系统

macOS

### 浏览器

macOS

### 发生问题的网址

safrai

**Comment by Kenshin** [comment]
嗨，简悦暂时不支持油猴脚本了，因为这只是 1.x 的部分功能，我关闭这个 Issues 了。
