### ISSUE TITLE
Obsidian高级版无法正常导入稍后读和Annotation到配置好的Obsidian-SimpRead文件夹

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#6525]
### 描述这个错误

运行"DD"快捷键并做相应的批注后，Obsidian下的SimpRead无法查看到导入的文章，实际导出的文章是在OutPut文件夹. 
检查了所有配置，都是按照原来另一电脑的成功设置的账号来复刻的，有做相应的路径微调，但问题依旧. 

- 实际导出的路径和截图：
- D:\Obsidian\SimpRead\output
- ![image](https://github.com/Kenshin/simpread/assets/57386018/be51fdaa-2a91-4fbc-9cba-1a09ab302b63)

- 实际的Annotation效果：
- ![image](https://github.com/Kenshin/simpread/assets/57386018/eb005613-fcc9-4f30-a1f2-e78d12ca53d8)

题外话：这是我的第三遍码字，在用的Razer鼠标快捷键没设置好（原DPI键失灵），按了侧键就触发浏览器窗口关闭，并无法找回已经编辑的内容，我尽量描述完整问题，但时间有限，请见谅~

原来浏览器的SimpRead设置也是正常的，但因为Kimi的阅读助手一只无法弹出侧边栏，后来搜索后，发现需要重装Edge浏览器更新版本，无奈只能更新版本，并购买了新账号，避免出现冲突报错. 

### 复现步骤

1. 清理浏览器Cookies后 重装Simpread插件，并导入本地设置. 
2. 更改uid为新购买的高级版账号. 
3. 复刻另一台电脑的设置. 

以下是当前电脑下的Obsidian端，浏览器，和同步助手的设置截图：

- 浏览器：
- ![image](https://github.com/Kenshin/simpread/assets/57386018/43ae3d52-ca71-49ac-8813-85274e4b7914)
- ![image](https://github.com/Kenshin/simpread/assets/57386018/3fbfd49a-5c6f-4eea-840d-8262a457b22f)
- ![image](https://github.com/Kenshin/simpread/assets/57386018/551e3395-b12e-42b5-9c85-a77b1fc0469e)

- Obsidian插件：
- ![image](https://github.com/Kenshin/simpread/assets/57386018/2fe8bcc7-5222-4bb9-bddf-2fa869cb4c02)

- 同步助手：
- ![image](https://github.com/Kenshin/simpread/assets/57386018/58403ba5-ca29-4b66-9949-f290f254ef05)
- ![image](https://github.com/Kenshin/simpread/assets/57386018/436fcdfa-384d-45a7-9b79-5c01b55ec71c)

### 操作系统

Windows 11

### 浏览器

Microsoft Edge

### 发生问题的网址

https://mp.weixin.qq.com/s/D3OK4RmybB-frF0VQdHs9A

**Comment by Kenshin** [comment]
> 这是我的第三遍码字，在用的Razer鼠标快捷键没设置好（原DPI键失灵），按了侧键就触发浏览器窗口关闭，并无法找回已经编辑的内容

😂 😂 😂 

不过我记得 Github Issues 可以记录你的内容，但可能 Close 就不行了。我是不不小心触发了 Forward 和 Back ...

***

> UID 的问题

如果你知道原来那台设备的 UID 并不需要重新购买

> 明显错误的地方

<img width="699" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9a1f2909-8ace-4692-a174-99964180984d">

这个地方错了会引发：标注时无法自动保存将新的标注文件保存到 Obsidian 中。

> 其它地方

这个地方也有点问题，如果你使用的 【导入到 Obsidian 高级版】方案  `.html` 与  `.md` 应该是不同的地方。

![image](https://github.com/Kenshin/simpread/assets/81074/615dc1ff-922a-4c40-bae6-13a6f610c325)

而且还有一点，我发现你的目录  `D:\Obsidian\SimpRead\output` 简悦的 output 目录与 Obsidian 应该是两个地方，尤其是针对新用户或者初次配置的用户来说。

#### 建议

1. 修复我提到的错误
2. 按照 https://www.yuque.com/kenshin/simpread/fr8zo5 的教程排查下

如果仍不能解决，建议按照 https://www.yuque.com/kenshin/simpread/fr8zo5 的官方规则设置（也就是我提到的 Obsidian 与 SimpRead 分属两个不同的地方）

或者使用新的 UID 按照配置库 https://www.yuque.com/kenshin/simpread/wq35mh 重新弄一次，在确保正常的结构中再修改为你自己的方案。

**Comment by mdsnalw** [comment]
大佬，我自己摸索出了问题，然后目前已经导入正常了哈. 

按我自己的观察，应该是obsidian下的SimpRead目录设置的问题. 

对于我来说，SimpRead文件夹在我的Obsidian库下不是在主目录，而是在二级文件夹，所以需要在插件的“”导入到Obsidian选项“”和Obsidian下的SimpRead插件分别做修改，而且要保持一致. 

SimpRead目录：D:\Obsidian\MyIOTO\1-输入\SimpRead
“导入到Obsidian选项”：1-输入\SimpRead
Obsidian-SimpRead插件：1-输入\SimpRead

改完就一切正常了！

我也对比了我工作机上的Obsidian库，SimpRead在Obsidian下是放在主目录而不是二级文件夹，所以一切都解释的通了. 

再次感谢大佬的耐心解答~

![image](https://github.com/Kenshin/simpread/assets/57386018/c11e4154-d322-43fe-85ce-256041276180)

![image](https://github.com/Kenshin/simpread/assets/57386018/836b7449-1332-459d-b1de-9e1114ae5115)


![image](https://github.com/Kenshin/simpread/assets/57386018/ce37f53a-e63a-48cd-9103-0492fb7e66ab)

工作电脑Obsidian→ SimpRead路径：
![0204f817efbd4f09033981bae7711c5](https://github.com/Kenshin/simpread/assets/57386018/005df453-22f9-407e-b6f6-0d2888066d3f)

**Comment by Kenshin** [comment]
okay 解决就好 👍

确实需要保持一致

<img width="823" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c77ff5fa-216b-4603-84c8-1995b4657ca8">

你开始的截图跟目前这个完全不是一个目录结构...  🌚 

不过，（这么）看来目录规则基本上完全理解了 👍

**Comment by Kenshin** [comment]
哈，方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by mdsnalw** [comment]
必须的，文笔不好，我请Kimi代劳了 😁

![image](https://github.com/Kenshin/simpread/assets/57386018/edea3737-a28c-4be4-91ca-c2266360e994)

> 哈，方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by Kenshin** [comment]
你这… 😂 👍

**Comment by Kenshin** [comment]
如果方便的话，请在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 评分（好像 Edge 的评论我经常看不到...  🌚  👿  💔  😅

**Comment by mdsnalw** [comment]
哈哈，好的，下午我再通过 Chrome提交下



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2024年05月31日 11:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Kenshin/simpread] Obsidian高级版无法正常导入稍后读和Annotation到配置好的Obsidian-SimpRead文件夹 (Issue #6525) |

如果方便的话，请在 Chrome 评分（好像 Edge 的评论我经常看不到... 🌚 👿 💔 😅

**Comment by Kenshin** [comment]
👍 别忘记就好

主要刚收获一个无脑评论，有点吃苍蝇的感觉  👿 

***

而且似乎 Chrome / Edge 可以判断是否是 AI 生成 😂

所以，随便说两句就好。

**Comment by mdsnalw** [comment]
> 👍 别忘记就好
> 
> 主要刚收获一个无脑评论，有点吃苍蝇的感觉 👿
> 
> 而且似乎 Chrome / Edge 可以判断是否是 AI 生成 😂
> 
> 所以，随便说两句就好。

AI真的是无处不在了哈，刚才去翻了下Chrome，发现我已经评论过了哈，那些无脑评论有时感觉就挺3D的，别太在意~

![image](https://github.com/Kenshin/simpread/assets/57386018/4ac52522-696c-4390-be23-38ebcfac2ff7)

**Comment by Kenshin** [comment]
哈，原来是老用户 😂 👍 （Issues 可以翻到记录，一般新鲜的 ID 我都会记住，隔了太久忘记了
