### ISSUE TITLE
总是提示simpread_config冲突

### ISSUE THREAD

**Issue by maxwell5566** [Kenshin/simpread#6529]
### 描述这个错误

坚果云同步的simpread_config重视提示冲突文件，应如何处理？
![image](https://github.com/Kenshin/simpread/assets/104042614/a603c407-7c46-40a1-a2ab-29beb15da9dc)

### 复现步骤

坚果云同步的simpread_config重视提示冲突文件，应如何处理？

### 操作系统

Windows

### 浏览器

egde

### 发生问题的网址

www.baidu.com

**Comment by Kenshin** [comment]
emmm 这个冲突是因为：（举个例子）

6月3日 11:25 你在 Win10 上面使用了简悦并同时开着坚果云，这时坚果云 Web 端的时间也是 **6月3日 11:25**；
6月3日 12:25 在 Win11 上面，没有开坚果云，但同时使用了简悦，所以你本地的 `simpread_config.json`  是 **6月3日 12:25**，而后你在 Win11 上面开启了坚果云；坚果云判断这两个文件出现了分歧（时间不一样，文件内容不一样）

#### 解决方案

其实并没有完美的解决方案 😂

简单的取舍在于：**看哪个冲突没有新的稍后读，就舍弃哪个。**

如果 Win11 与 Win10 都分别有新的稍后读，你可以将这两个文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6529

然后在这里告诉我，我来手动帮你合并。

简悦的数据基于文本结构，所以很容易做合并，只是需要些动手能力而已。

**Comment by Kenshin** [comment]
### 避免这种问题的解决方案

确保在使用简悦前，务必要运行：坚果云和同步助手，即可。
