### ISSUE TITLE
安装Safari 插件后，【高级设定/阅读模式/大纲(目录)是否开启「 鼠标移动到左上角」自动显示?】的设置不起作用

### ISSUE THREAD

**Issue by Warren69** [Kenshin/simpread#653]

**Comment by Warren69** [comment]
在 edge/chrome/firefox 中测试后结果一样

**Comment by Kenshin** [comment]
嗨，谢谢反馈~

***

已经解决了，请重新安装此脚本。 确认无误后，**请关闭此 issues** ~

**Comment by Warren69** [comment]
经过重装插件、重启浏览器等测试之后发现仍有该问题存在

> 嗨，谢谢反馈~
> 
> 已经解决了，请重新安装此脚本。 确认无误后，**请关闭此 issues** ~

**Comment by Kenshin** [comment]
应该不会，我已经测试过。

你试着录屏，或者截图给我看看。

**Comment by Warren69** [comment]
https://drive.google.com/open?id=1sP4EI-XzKqxzPvok6TjAo4z7TXXUtkfz

**Comment by Kenshin** [comment]
...  😂 😂 😂

我知道原因了 👉 **咱们说的不是一件事情**

***

我以为你说的 `安装Safari 插件` 是指：由于我刚刚更新的 **[简悦 · 轻阅版](http://ksria.com/simpread/changelog.html?#us_1.1.2.200206)**，并且你的标题提到了 **Safari**，所以我调查了并证实了这个问题。

所以，我说的更新是指：**轻阅版更新了 TOC 的问题**。

***

现在回复一下你的问题：

**Safari 插件** 是正常的，在此插件下，TOC 一直存在。当然，可能你的屏幕比较下，所以在布局上出现了一些错误。

同时这个插件也没有说明（ 以后会加入插件版的说明

**Comment by Warren69** [comment]
你好，首先谢谢你的解答。
---
我想问一下，为什么在safari插件下，要设置TOC一直存在呢？

如果可以设置成自动显示的话，界面不是更加简洁美观吗？

**Comment by Kenshin** [comment]
可以考虑你的建议，等我升级这个插件后，会在这里通知你。 😀

**Comment by Warren69** [comment]
好的，谢谢作者

**Comment by Kenshin** [comment]
你可以临时使用下面的方式：

```
toc {
    width: 50px!important;
    transition: all 450ms ease 0ms;
}

toc:hover {
    width: 200px!important;
}
```

把上面的代码粘贴到 **选项页 → 高级设定 → 自定义样式** 即可。

**Comment by Warren69** [comment]
> 你可以临时使用下面的方式：
> 
> ```
> toc {
>     width: 50px!important;
>     transition: all 450ms ease 0ms;
> }
> 
> toc:hover {
>     width: 200px!important;
> }
> ```
> 
> 把上面的代码粘贴到 **选项页 → 高级设定 → 自定义样式** 即可。

已经生效了，谢谢

**Comment by Kenshin** [comment]
嗨，我更新了[ 模仿 Safari 阅读模式样式](https://simpread.ksria.cn/plugins/details/tbjTx33iAA) 

有时间确认下，没问题的话，请关闭这个 issues

**Comment by Warren69** [comment]
<img src='https://i.loli.net/2020/07/05/wD1hM9xNeviQVHK.png' title='quicker_ce7735bc-3ff2-4e78-891d-8f27e9633fad.png' />

看起来还没有生效？我已经重新安装了这个插件，发现目录依然是一直显示的

**Comment by Kenshin** [comment]
忘记说明了，更新后的插件仍旧没有你说的功能，但现在的方式是：插件会自动检测是否可以显示的下 TOC 的位置，如果显示的话，就类似下图这样

![image](https://user-images.githubusercontent.com/81074/86531248-2a581480-bef2-11ea-8e82-0f32a2621597.png)

所以，你这边还需要加上

```
toc {
    width: 50px!important;
    transition: all 450ms ease 0ms;
}

toc:hover {
    width: 200px!important;
}
```
这段代码

为了更加的美观，你可以自行调整 `width` 的值到你喜欢的状态。
