### ISSUE TITLE
插件能否升级到 Manifest v3？

### ISSUE THREAD

**Issue by czz404** [Kenshin/simpread#6532]
### 请描述你的建议或任何内容

作者您好，谷歌开始逐步清退 Chrome Manifest v2 扩展程序，我看了一下本插件就属于 Manifest v2 的，请问一下本插件能否升级为 Manifest v3 版本，如果实现难度较大的话作者有什么建议或者新方法

### 补充说明

MV2 将在本月（6 月）在个人消费者渠道中被弃用，而企业渠道将延长支持至明年 6 月

**Comment by Kenshin** [comment]
嗨，当然会升级到 V3 😂

但无需多虑，直到 2025 年才会弃用 V2

用户可以正常使用，细节看下 https://alternativeto.net/news/2024/5/google-chrome-to-phase-out-manifest-v2-extensions-starting-june-3-complete-by-early-2025/

简单的说稳定版会在 2025 年逐步禁用，开发版或测试版会有提示。

对于用户来说都是无感的。

**Comment by Kenshin** [comment]
好奇问问，你是如何得知简悦使用 V2版的？或者说你在使用 Chrome 非稳定版？

目前我在 Dev 版也没有看到相关提示。

**Comment by czz404** [comment]
> 好奇问问，你是如何得知简悦使用 V2 版的？或者说你在使用 Chrome 非稳定版？
> 
> 目前我在 Dev 版也没有看到相关提示。

chrome://extensions-internals/
中可以查看已安装扩展的 manifest_version

我看到的是这几个消息：
https://developer.chrome.com/blog/resuming-the-transition-to-mv3?hl=zh-cn
https://www.landiannews.com/archives/104227.html

>从 6 月 3 日开始 Chrome Beta、Dev 和 Canary 版安装 Manifest v2 扩展程序时将会在扩展管理中看到黄色感叹号和警告提示，告知用户该扩展程序很快将不再支持。
对于 Chrome Web Store 中已经获得精选徽章的扩展程序，如果不立即更新到 v3 则会被删除精选徽章，因此在用户搜索时展现率可能会大幅度下降。
接下来的几个月里谷歌将引导 Chrome 用户跳转到应用商店安装扩展程序的 Manifest v3 版，之后这些旧扩展将会被默认禁用，用户仍然可以手动启用，但未来将彻底被禁用无法再启动。

**Comment by Kenshin** [comment]
> chrome://extensions-internals/
中可以查看已安装扩展的 manifest_version

原来如此 👍

***

放心好了，肯定会升级的。
退一步说，用户可以使用 Edge （没有此要求）以及在 Chrome 使用开发版方案。

**Comment by Kenshin** [comment]
昨天手机打字不方便，再简单的说明下。

***

1. 这个页面我很久就知道了，因为我是 Chrome 扩展的负责人（开发者），当出现 V3 时 Chrome 会给开发者优先发送邮件，所以无论什么「风吹草动」，开发者都会比用户优先知道。

2. Chrome 官方不会在不告知开发者（并会提前很久告知）就下线任何一个扩展。（除非违法或违规）

另外，顺便解读下你提到的页面（留意标注的内容即可）

<img width="901" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c828d816-62ed-4319-b8ee-6942c22878b9">

以及

<img width="1437" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b61e37e4-cbe8-4e93-a7ca-9f29e631f91f">

***

不仅如此，也可以有「补救」方案 https://github.com/Kenshin/simpread/issues/6532#issuecomment-2145518329

**Comment by czz404** [comment]
感谢解答，现在明白多了🫡

**Comment by Kenshin** [comment]
小事情 😄 

PS：不信谣不传谣（没想到有一天竟在我的 QA 里面，还是我自己打了这么一句话...  🌚  💔  😅

**Comment by Kenshin** [comment]
嗨，我发布了一个更全面的「官方说明」，可以看下 https://github.com/Kenshin/simpread/discussions/6633

**Comment by czz404** [comment]
> 嗨，我发布了一个更全面的「官方说明」，可以看下 #6633

好的，感谢您的解答

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
