### ISSUE TITLE
新站适配：utgd.net

### ISSUE THREAD

**Issue by gexd79** [Kenshin/simpread#6533]
### 需要适配的新站

https://utgd.net/article/20753/

### 有需要请描述这个站的性质

IT,效率，软件硬件等等。多数内容需要付费成为会员才可以观看（我不是会员，对我来说有点贵）

**Comment by Kenshin** [comment]
嗨，这个站其实已经适配了，但它的规则改变造成了适配问题 😂

更新适配规则后我会在这里通知你。

PS：简悦是阅读模式类产品，无法也不可能（同时也不允许）绕过任何具有付费墙的页面。

**Comment by felix2049lou** [comment]
哈，先把非付费文章能适配好已经很不错了，支持。
刚刚想把sspai文章做一个epub合集也因图片导出失效问题，心里多想simpread每天可以有大更新（笑）

**Comment by gexd79** [comment]
谢谢，大佬辛苦~
我并没有期待咱这产品越过付费墙的想法，那只是在描述这个站的性质

**Comment by felix2049lou** [comment]
> 嗨，这个站其实已经适配了，但它的规则改变造成了适配问题 😂
> 
> 更新适配规则后我会在这里通知你。
> 
> PS：简悦是阅读模式类产品，无法也不可能（同时也不允许）绕过任何具有付费墙的页面。

若能配适好（希望可以），是不是会在哪里发出通知？

**Comment by Kenshin** [comment]
嗨，各位。

这个站已经重新适配完毕了。

**未使用同步助手的自动同步功能**用户，请直接通过 https://simpread.ksria.cn/sites/details/9aR6G3qt9y 安装。

**使用同步助手的自动同步**用户，请通过 https://www.yuque.com/kenshin/simpread/ugu11ptr2sx9zd0k 安装。

上述无论哪种方案，都请重启浏览器确保生效。

效果如下

<img width="1236" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cefb8237-5188-491d-a318-b0c90f792011">

我关闭这个 Issues 了，有任何疑问随时可以在这里讨论~

**Comment by felix2049lou** [comment]
想像不到这么这么快，可能有点吹毛求疵，其实网页第一图可用作题图，但即便用了题图插件，也加不了第一图为题图（汗）
![image](https://github.com/Kenshin/simpread/assets/87223257/a3e2796a-9683-41a7-8fc7-9f525bdd56c9)
![image](https://github.com/Kenshin/simpread/assets/87223257/2182bee7-44e1-4753-a110-9c5b2f1c80de)

**Comment by Kenshin** [comment]
@felix2049lou 

（其实）我也想... 但这个网页的题图属于个例，没法通配。

**Comment by felix2049lou** [comment]
🤯

**Comment by felix2049lou** [comment]
有没有可能做成自己上传图片做题图？

On 8 Jun 2024, at 11:03, Kenshin Wang ***@***.***> wrote:

﻿

@felix2049lou<https://github.com/felix2049lou>

（其实）我也想... 但这个网页的题图属于个例，没法通配。

**Comment by Kenshin** [comment]
> 有没有可能做成自己上传图片做题图？

没有什么太大的意义，而且毕竟在人家的地盘（不同网页）会有很多预想不到的麻烦和风险。

**Comment by felix2049lou** [comment]
发现该网页文章很都有标注及标注转跳的功能，剪裁或阅读模式时能否保留？

**Comment by Kenshin** [comment]
> 发现该网页文章很都有标注及标注转跳的功能，剪裁或阅读模式时能否保留？

不能 😂 阅读模式不需要任何可互动类的功能。（也尽量不允许）
