### ISSUE TITLE
是否有办法进一步提高文字大小

### ISSUE THREAD

**Issue by ViNull008** [Kenshin/simpread#6535]
### 请描述你的建议或任何内容

进入阅读模式后，文字已经选择到100了，但是还是觉得小，希望有办法可以进一步增大文字。

### 补充说明

笔记本的显示器分辨率比较高，即使把文字大小选择100还是有点小，如果选择在阅读模式缩放页面，又会破坏简阅自有图标的大小，造成不和谐，且有时会有排版混乱，希望能提供原生的进一步增大文字大小的方法（附图为浏览器放大页面效果，简阅自有图标变得非常大）
![image](https://github.com/Kenshin/simpread/assets/11844999/5ffca48a-e4fd-4487-9f9a-071d80185b3c)

**Comment by Kenshin** [comment]
嗨，这个功能的值确实只能到 `100` 但并不代表这个问题无法解决，可以使用 自定义样式，位置在：选项页 → 高级设定 → 自定义样式。

<img width="1221" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1bced217-4377-411b-91ea-b8163ffee191">

比如我改成更大的字体。

<img width="347" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8a596308-8b52-4c0f-9153-a5f904926aa3">

注意：修改保存后请重启浏览器确保生效。

**Comment by ViNull008** [comment]
谢谢作者，正在试着调整，请问红框中的字属于哪个模块？我在左边菜单里面没法调整它
![image](https://github.com/Kenshin/simpread/assets/11844999/18433808-884b-494a-8435-7cba3405ade7)

**Comment by Kenshin** [comment]
> 请问红框中的字属于哪个模块？我在左边菜单里面没法调整它

代码段 `Code` 

另外，关于主题（或字体）的一些高级玩法，也可以 [看看这里](https://github.com/Kenshin/simpread/discussions?discussions_q=is%3Aopen+label%3Atheme) 或许对你有所帮助。

**Comment by ViNull008** [comment]
好的 OK :+1:

**Comment by Kenshin** [comment]
如果你对字体有要求的话，其实更建议你使用 https://github.com/Kenshin/simpread/issues/6535#issuecomment-2149454976 链接提到的方案。

***

> 下面的内容非自动，纯手打... 😂

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
