### ISSUE TITLE
无法绑定坚果云等

### ISSUE THREAD

**Issue by YoungSmiles** [Kenshin/simpread#6537]
### 描述这个错误

绑定坚果云，始终显示授权不成功。

### 复现步骤

按照配置同步助手步骤，需要绑定坚果云，但始终提示不能成功。

<img width="596" alt="截屏2024-06-07 10 41 01" src="https://github.com/Kenshin/simpread/assets/172000346/b5d58446-68be-427a-b61b-1f2252f1d724">
<img width="491" alt="截屏2024-06-07 10 40 47" src="https://github.com/Kenshin/simpread/assets/172000346/865787dd-e2a4-4412-9266-e122a7f17bb4">。

如果授权Dropbox登录，又会提示密码太长无法加密什么的。
<img width="1361" alt="image" src="https://github.com/Kenshin/simpread/assets/172000346/13f735ab-f935-4b21-bff6-6b347ce20e70">

现在卡死在这里了。
另外，也期待开启Dropbox等同步。

### 操作系统

macOS（arm）

### 浏览器

Chrome 125

### 发生问题的网址

https://github.com/Kenshin/simpread/issues/new?assignees=&labels=&projects=&template=bug_report.yaml

**Comment by Kenshin** [comment]
> Dropbox 的问题

你看到的这个提示是因为 Dropbox API 修改导致的，再加上它非常短的 Token 时间，所以不建议使用 Dropbox 方案。

> 坚果云的问题

坚果云肯定是没问题的，首先排除是否是 https://www.yuque.com/kenshin/simpread/tmmwhl 问题造成的。

如果不是的话，坚果云需要在 **选项页 → 服务 → 授权管理** 里面设置，请留意输入的内容是：

1. **坚果云登录的 Email**
2. **坚果云的 WebDAV 密码（不是你的坚果云登录密码）**

授权成功后，重启浏览器确保生效。

**Comment by YoungSmiles** [comment]
原来是webdav密码，不知道那个在哪里找啊？

另外，大佬，我进到telegram群，里面需要验证名称，手一抖点错，然后，就再也进不去了…

Kenshin Wang ***@***.***>于2024年6月7日 周五11:14写道：

**Comment by Kenshin** [comment]
> 原来是webdav密码，不知道那个在哪里找啊？

https://www.jianguoyun.com/d/home#/safety 简悦的教程中有说明。

> 大佬，我进到群里面需要验证名称，手一抖点错，然后，就再也进不去了

ID 告诉我下，或者私聊也行。
