### ISSUE TITLE
小红书照片无法捕捉

### ISSUE THREAD

**Issue by Tobeprmn** [Kenshin/simpread#6538]
### 描述这个错误

在此之前，使用简悦插件进入小红书网页版的阅读模式时，阅读界面是有显示图片的，但是今天打开小红书网页版，然后使用简悦进入该网页的阅读模式后，无法看到图片了

### 复现步骤

1，进入小红书网页版某篇文章，如链接所示；
2，使用简悦插件进入该网页的阅读模式，但无法看图片了；
3，试了其他网站（知乎、CSDN）都可以看图片

### 其他相关说明

我不确定是网站限制还是插件bug

### 操作系统

windows10 22H2

### 浏览器

Edge 125.0.2535.92（正式版本）

### 发生问题的网址

https://www.xiaohongshu.com/explore/6606507f00000000120317bb

**Comment by Kenshin** [comment]
嗨，是他们的规则改变导致的，解决方案：

选项页 → 站点管理，看下图所示，操作后重启浏览器确保生效。

<img width="917" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/05774f6e-b287-4e91-a2f8-fd70dee8c5b3">

**Comment by Tobeprmn** [comment]
感谢，已成功解决！

> 嗨，是他们的规则改变导致的，解决方案：
> 
> 选项页 → 站点管理，看下图所示，操作后重启浏览器确保生效。
> 
> <img alt="image" width="917" src="https://private-user-images.githubusercontent.com/81074/337516550-05774f6e-b287-4e91-a2f8-fd70dee8c5b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzU4NDEsIm5iZiI6MTcxNzczNTU0MSwicGF0aCI6Ii84MTA3NC8zMzc1MTY1NTAtMDU3NzRmNmUtYjI4Ny00ZTkxLWEyZjgtZmQ3MGRlZThjNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA0NDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MTlkZjllMWJjZjc5YTRmMWIzOTYxNjY2NmM2ZmRkMmIxMGNmMmMwYmYyZTkzN2QxYTVlMDA5YTVlOGY4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRvUGWUHg0IEZGsGhd7FuKO-Jo3Yd0NaANldjrmXZXs">

**Comment by Kenshin** [comment]
哈，解决就好 👍

PS：如果没猜错的话，他们应该是昨天修改的规则 😂

**Comment by Kenshin** [comment]
另外，方便的话请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by Tobeprmn** [comment]
一直在小红书和B站宣传简悦，每次看到评论说配置复杂，我都会简单介绍一下。另外，真心感谢开发者，相较于其他剪藏软件，简悦功能强大，价格低廉。


> 另外，方便的话请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by Kenshin** [comment]
太感谢了。 👍

PS：说配置复杂的大部分是不了解简悦的朋友，哪怕稍微了解几分钟的话，也不会这么理解。

PPS：以后可以直接怼给他们 https://www.yuque.com/kenshin/simpread/ds8zk0 （配置库方案，几乎无任何配置）
