### ISSUE TITLE
少数派文章导出markdown后无法正常显示图片

### ISSUE THREAD

**Issue by SolitarySwan22** [Kenshin/simpread#6539]
### 描述这个错误

阅读少数派文章，使用简阅导出markdown，在obsidian里面查看，其他都正常，图片无法正常显示，编辑模式查看markdown文件，里面还是有图片的正常链接的，复制到浏览器也能正常显示，不确定是obsidian的问题还是简阅的问题。
![WX20240607-111640](https://github.com/Kenshin/simpread/assets/102399006/3770dd43-1732-4ce0-91ed-74f4080435b6)
![screenshot-20240607-111657](https://github.com/Kenshin/simpread/assets/102399006/6ab85f69-4fef-4e3b-9ac6-1de201e00107)

### 复现步骤

1、打开文章
![1](https://github.com/Kenshin/simpread/assets/102399006/6c003457-84da-4c68-b12c-b8ba8f29c6da)
2、点击简阅进入阅读模式
![2](https://github.com/Kenshin/simpread/assets/102399006/0c5200f8-7253-4fff-9c8c-8fbd48d3323c)
3、点击：导出到markdown
![3](https://github.com/Kenshin/simpread/assets/102399006/239d4025-a3e6-44ed-b915-69710b51c8e7)
4、obsidian查看文章
![4](https://github.com/Kenshin/simpread/assets/102399006/032e7bd2-dd5e-4430-aed3-02517f894e7a)

### 操作系统

macOS

### 浏览器

Microsoft Edge，版本 125.0.2535.92 (正式版本) (x86_64)

### 发生问题的网址

https://sspai.com/post/89194

**Comment by Kenshin** [comment]
嗨

我随便找了个页面测试，图片链接没问题，也就是导出是没问题的。

<img width="777" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b5c6e64d-7b83-43bf-8075-754700277b9f">

但无论是 Obsidian 还是 Typora 都无法显示... 😂  

应该是跟他们近期修改图片链接规则导致的，建议联络少数派解决。

**Comment by Kenshin** [comment]
嗨，各位。

[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 升级到 1.2.0 

### 重点更新：导入到 Cloudinary 时不经过简悦自己的图片服务器

旧版 1.2.0（以上）会通过简悦的自己的服务器，优点是不需要耗费用户的设备性能；缺点是当为内网图片时无法使用；

新版 1.2.0（含），不经过简悦自己的图片服务器，解决了内网图片或某些有防盗链的图片无法上传的问题。

如：

1. 近期少数派更新了图片规则，导致无法使用旧方案上传，但版方案可以正常将少数派的图片上传到 Cloudinary

    <img width="1023" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/8273730d-2cb5-45e9-9170-7fe32f800f03">

2. 内网图片无法使用此功能的问题

### 其它更新

`Fix` 导入图片如果是 `http:` 形式在 Notion 无法显示的问题

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

有任何问题请在汇总页面讨论 https://github.com/Kenshin/simpread/issues/5917
