### ISSUE TITLE
新站适配：MSN 新闻站

### ISSUE THREAD

**Issue by djboy214** [Kenshin/simpread#6541]
### 需要适配的新站

https://www.msn.cn/zh-cn/news

### 有需要请描述这个站的性质

Edge内置的新闻是这个站点，平时经常使用，但阅读模式抓取不了

**Comment by Kenshin** [comment]
okay 没问题，适配后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，MSN 这个站点已适配完毕。

#### 如何更新

选项页 → 站点管理 → 官方主适配源（留意下图）

<img width="924" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/0e94adad-e103-46d3-9582-10069a07abd1">

更新后请务必重启浏览器确保生效。

#### 效果如下

<img width="1806" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fad680a2-6978-4418-b403-0861690e74f0">

***

我关闭这个 Issues，有任何问题请随时在这里讨论~
