### ISSUE TITLE
简悦无法授权notion。（已加收藏并登陆notion,任然没有反应）

### ISSUE THREAD

**Issue by BenjaminTSZ** [Kenshin/simpread#6542]
### 描述这个错误

已经将Notion中的简悦稍后读页面添加到收藏夹，登陆了notion账号。在此情况下不管是简悦的哪个选项卡中点击授权，都是一直转圈圈的状态。

![343cdfc715fd3a403c192b531ccf6d3](https://github.com/Kenshin/simpread/assets/127576261/00e9ef08-5a85-45b8-a05d-2863de7393d7)
![e4bc7a1dbd6fefd42a7049feb11dc9d](https://github.com/Kenshin/simpread/assets/127576261/3fa376bd-4030-4af9-b2bc-56ac9970a83c)

### 复现步骤

1. 在Notion中复制了简悦官方Github提供的稍后读模板。
2. 登陆了Notion，将稍后读Page加入了收藏栏。
3. 点击简悦的服务-授权管理-授权notion，出现了：授权中，请勿关闭此界面，授权成功后会有提示。之后就一直没有反应了。
4. 插件中心安装了导出到Notion, 使用阅读模式-动作-导出到Notion，弹出窗口显示需要授权Notion, 点击授权，显示授权中，之后一直都在转圈圈，没有反应。
5. 检查过浏览器的Cookies设置，和简悦的解决方案一样设置任然无效。
6. 更换了其他的浏览器如Edge, 依然无法授权成功。

### 其他相关说明

想要支持简悦一波的，感觉很好用，但是无法授权Notion这个问题真的是太玄学了。这种情况找不到问题点吗？有没有其他的途径之间授权到Notion呢？
在Notion的界面，右上角设置-connection选项，里面如果能够直接搜索到简悦就好了。

### 操作系统

Windows10

### 浏览器

Chrome125.0.6422.142

### 发生问题的网址

https://simpread.pro/price.html

**Comment by Kenshin** [comment]
😂 ...

你的流程完全都是错误的。

请仔细看 https://github.com/Kenshin/simpread/discussions/4954 里面描述的内容

<img width="518" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/1280dab9-1b88-4980-9668-6a1720c7b821">

然后出现下图

<img width="521" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2c4813cd-1fc2-4d28-ad0d-e541b0699e5a">

同时也有详细说明

<img width="449" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/fdfda4eb-7c79-4890-bf7c-70e257f35e82">

**Comment by BenjaminTSZ** [comment]
Kenshin，你好啊：


我认真看了你发给我的教程，发现之前的操作都是错误的哈哈，现在能够使用的。


但是我又遇到了另外一个问题，我购买了高级账户，在爱发电平台收到了秘钥，我按照《已购必读》里面的《首次绑定》进行了操作，然后在绑定的时候输入了秘钥，回车键就显示失败，说一个账号只能绑定一个秘钥，但是我之前都没有绑定过秘钥，我也不知道是怎么回事。


这种情况要怎么处理呢？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月8日(星期六) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 简悦无法授权notion。（已加收藏并登陆notion,任然没有反应） (Issue #6542)





 
😂 ...
 
你的流程完全都是错误的。
 
请仔细看 #4954 里面描述的内容
 image.png (view on web) 
然后出现下图
 image.png (view on web) 
同时也有详细说明
 image.png (view on web)

**Comment by Kenshin** [comment]
😂

Issues 不是 Email 系统，你能收到的邮件可以理解为一个通知，所以可以进入到 https://github.com/Kenshin/simpread/issues/6542 跟我讨论。

***

> 在爱发电平台收到了秘钥，我按照《已购必读》里面的《首次绑定》进行了操作，然后在绑定的时候输入了秘钥，回车键就显示失败，说一个账号只能绑定一个秘钥

如果我没猜错的话，你的 UID（选项页 → 账户 → UID ）显示的是 `xxxxxx-xxx` 的形式，这是 Demo UID 当然不好使了，每个配置库教程里面有详细说明，随便给你找了一个 https://www.yuque.com/kenshin/simpread/wq35mh#70bff838
