### ISSUE TITLE
通过快捷指令提交到稍后读的文章，显示不正确。

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#6549]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/82427022/33b44222-00d8-40cb-91cf-8e98d90ad1dc)

使用iOS快捷指令存储到稍后读的文章，展示内容非文章内容，点击稍后读的源链接，能够跳转到正确的文章链接。

### 复现步骤

1. 少数派看到文章（ https://sspai.com/post/89418 ），点击“复制链接”；
2. 通过iOS快捷指令发送到稍后读；
3. 电脑打开后，稍后读内容与文章不匹配，点击“跳转源链接”，又能跳转到正确的链接内容。

### 操作系统

iOS18

### 浏览器

Edge

### 发生问题的网址

https://sspai.com/post/89418

**Comment by Kenshin** [comment]
emmmm

#### 产生原因

估计是 `ID` 错乱造成的。假设：使用快捷指令收藏时的 ID 为 123，但并没有使用坚果云同步到本地（或者被覆盖），而这时又在本地添加了一个新的收藏，因此 `ID` 也是 123，就会产生错误。

#### 解决方案

没有特别的解决方案，仅需要注意：同步助手 & 坚果云要先于 Chrome 运行（此方式确保了你的 PC 端是最新的数据）
