### ISSUE TITLE
安装图床插件后，无法打开图床选项

### ISSUE THREAD

**Issue by lemon22333** [Kenshin/simpread#6552]
### 描述这个错误

安装图床插件后，无法打开图床选项
<img width="554" alt="image" src="https://github.com/Kenshin/simpread/assets/143933993/0e8d7b6e-300f-4202-987c-d232b3db00a5">

### 复现步骤

1.安装图床插件
2.插件管理器，获取全部配置，保存在本地
3.点击图床有上传图片，但是选项按钮打不开

### 其他相关说明

不知道是我自己的问题

### 操作系统

macos

### 浏览器

版本 126.0.6478.61（正式版本） (arm64)

### 发生问题的网址

https://juejin.cn/post/7367620055319019559

**Comment by Kenshin** [comment]
你的步骤... 😂 

如果使用了同步助手的自动同步功能，需要使用插件管理器安装插件，这点你应该知道（体现在你提到的步骤上）

但步骤是错误的... 

步骤1 → 不能通过 URL 直接安装
步骤2 → 不需要获取全部插件... 而是通过插件管理器安装
