### ISSUE TITLE
新站适配，代码不显示

### ISSUE THREAD

**Issue by uvlydxba56648** [Kenshin/simpread#6554]
### 需要适配的新站

xiaolincoding.com

### 有需要请描述这个站的性质

计算机学习网站，阅读模式下代码不显示
![QQ截图20240615222046](https://github.com/Kenshin/simpread/assets/140759010/d3da055e-6c9e-4c12-9411-47a234985330)
![QQ截图20240615222057](https://github.com/Kenshin/simpread/assets/140759010/98ca25e6-d0bb-4cea-945f-8cd8526d6b7d)

**Comment by Kenshin** [comment]
这个网站并不是关于机器学习的（或者我没有找到），但可以考虑适配。

不过，代码段的问题算是比较麻烦的，最好给我一些包含代码段的 URL 测试。

**Comment by uvlydxba56648** [comment]
https://xiaolincoding.com/mysql/index/index_interview.html#%E6%8C%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E7%B1%BB

**Comment by Kenshin** [comment]
okay

不过，你也可以暂时使用下图所示方式

<img width="946" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9020816e-1866-4e22-b586-3ab5c039c7cf">

效果如下

<img width="1229" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f9f76d51-cf77-4bcb-9065-211a19996605">
