### ISSUE TITLE
和微软系统快捷键冲突

### ISSUE THREAD

**Issue by rewvbfdhgf** [Kenshin/simpread#6555]
### 描述这个错误

我现在是高级账户，已经使用了同步助手一段时间了，当我在文件管理器中按下ctrl +shift+N来创建新文件夹时，就会弹出这个截图，这应该是和同步助手有关的。
请问如何修改以避免冲突。
![2024-06-12_17-32-34](https://github.com/Kenshin/simpread/assets/163216953/9533a4ca-c7cc-4721-957c-afd4384c51d5)

### 复现步骤

如何写？？？已经写了

### 操作系统

Windows

### 浏览器

brave

### 发生问题的网址

没网址

**Comment by Kenshin** [comment]
emmm 很奇怪跟全局的快捷键不应该有冲突（至少其它 Windows 用户没有反馈过类似情况）

截图提示修改的地方在下图

<img width="685" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/c5d87df6-25a7-47c1-8ba1-12c24002372a">

快捷键对应的是扩展端，看下图

<img width="257" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/f8a084a9-1e2d-4878-9d76-fbf4205ff710">

可以禁用全部快捷键 

<img width="1670" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a332e215-0565-408a-9895-37f3ab9b3360">

**Comment by rewvbfdhgf** [comment]
谢谢，设置好了。

**Comment by Kenshin** [comment]
okay 解决就好 👍

我关闭这个 Issues 了~

**Comment by Kenshin** [comment]
方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

***

上述不是自动回复，而是手打~
