### ISSUE TITLE
当对一个CELL.com的论文网页保存为markdown或html文件时，会把参考文献链接的作者也保存在markdown或html

### ISSUE THREAD

**Issue by youmu-silence** [Kenshin/simpread#6557]
### 描述这个错误

当对一个CELL.com的论文网页保存为稍后读，markdown或html文件时，会把参考文献链接的作者也保存在稍后读，markdown或html中

### 复现步骤

打开网页
https://www.cell.com/cell/fulltext/S0092-8674(22)00393-2?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867422003932%3Fshowall%3Dtrue&__cf_chl_tk=g4iQuj2hmP9wX1c29w69P3QlX3cI_eJjEbXcgdynYAM-1718779570-0.0.1.1-9129#figs1

<img width="554" alt="67242748e26cc072b57361e86136779" src="https://github.com/Kenshin/simpread/assets/173247622/c714833b-a727-433e-a63a-ac594e904aba">

进入阅读模式
![image](https://github.com/Kenshin/simpread/assets/173247622/5d7e535e-94b6-472d-9ed2-6a637aa0b556)

保存为稍后读
![image](https://github.com/Kenshin/simpread/assets/173247622/5e54f91d-fb32-471f-9b3b-f02bf4b2f23b)

这个问题在这个网站的所有文章都有出现

### 操作系统

windows

### 浏览器

edge 126.0.2592.56 

### 发生问题的网址

https://www.cell.com/

**Comment by Kenshin** [comment]
我没太明白你的问题 😂 

假设你的问题是：**阅读模式下没问题，但导出 Markdown 或 HTML 时有错误** 的话，请把错误的地方圈出来，以及对应阅读模式的位置也圈出来。

**Comment by youmu-silence** [comment]
问题已修改

**Comment by Kenshin** [comment]
我没做任何事情 😂 ...
