### ISSUE TITLE
使用Local REST API同步标记到Ob无内容

### ISSUE THREAD

**Issue by powerHourse** [Kenshin/simpread#6558]
### 描述这个错误

使用Local REST API方案， 同步标记之后，Ob创建了对应文件，但是只有标题无内容，下图是ObDevTools中的内容
![iShot_2024-06-20_16 30 08](https://github.com/Kenshin/simpread/assets/13093736/53ecb766-53bb-4db4-a8d4-196f1c642f58)

### 复现步骤

1. 安装各个插件，没有一次都安装完， 失败一次找缺失的插件
2. 配置Local REST API中的token

### 其他相关说明

Ob：1.6.3
浏览器：

### 操作系统

macOS14.4

### 浏览器

chrome：125.0.6422.176（正式版本） (arm64)

### 发生问题的网址

https://sspai.com/post/72697

**Comment by Kenshin** [comment]
我测试了下，是没问题的，留意下截图的设置。

<img width="619" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/11c336f1-e68c-4a03-846a-402b351e239c">

<img width="816" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/280f1927-fa51-4f8d-a244-319b17ab1660">

***

> 安装各个插件，没有一次都安装完， 失败一次找缺失的插件

什么意思？

> DevTool 的错误提示

你能直接打开 http://127.0.0.1:8765 吗？另外 Local REST API 并没有使用 8765 这个端口...

***

PS：Local REST API 此方案不是很好，当文章过长时会出现错误。

**Comment by powerHourse** [comment]
http://127.0.0.1:8765/ 打开之后网页显示AnkiConnect v.6 ， 应该是anki插件插件的端口了，那这是冲突了？本地 配置如图
<img width="762" alt="iShot_2024-06-20_19 35 32" src="https://github.com/Kenshin/simpread/assets/13093736/6e7c9af9-6657-4568-9cdc-64bd2949bdbf">
<img width="765" alt="iShot_2024-06-20_19 35 38" src="https://github.com/Kenshin/simpread/assets/13093736/29456ff5-2574-4671-b1eb-7d57c689407c">
![iShot_2024-06-20_19 37 55](https://github.com/Kenshin/simpread/assets/13093736/5aca3875-ad23-40f1-802f-a7d8981b68ce)

**Comment by powerHourse** [comment]
Local REST API 此方案不是很好，是建议用方案3是么

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6558#issuecomment-2180464253

我不确定，但报错确实是这个端口。

> Local REST API 此方案不是很好，是建议用方案3是么

是的，新用户建议直接使用配置文件方案 https://www.yuque.com/kenshin/simpread/psugef
