### ISSUE TITLE
知乎脚注的跳转

### ISSUE THREAD

**Issue by tangwells** [Kenshin/simpread#6559]
### 请描述你的建议或任何内容

是否可能对于脚注直接在阅读模式里进行跳转

**Comment by Kenshin** [comment]
不太可以，阅读模式尽量不要这些内容，因为阅读模式需要为「导出功能」服务。

不过，你可以给出具体的 URL 我瞧瞧。

另外，也可以安装这个插件 https://github.com/Kenshin/simpread/discussions/2861 增强知乎的阅读体验。
