### ISSUE TITLE
Notion Blog 配置 Notion Next 后无法正常导入

### ISSUE THREAD

**Issue by zanezh** [Kenshin/simpread#6560]
### notion增强辅助或失败，或一直加载

标题。只要进入到增强辅助，就会有绿色底色提示进行中，然后无结果：我已按官方教程步骤反复安装卸载，重新生成id配置。下载你的初级、中级、高级配置文件并登陆你的帐号测试。都不可以

如果我使用官方的web clipper插件创建一个新的数据库后，使用辅助增强，则红色底色提示框提示失败，请我手动操作
应该是辅助增强出了问题

### 补充说明
按官方配置步骤，使用web clipper，新建数据库，辅助增强失败，也就无法激活你的notion blog插件
按官方配置，与notionnext合并，辅助增强这一步持续的进行中
Chrome 已是最新版本 版本 126.0.6478.62（正式版本） (arm64)
MacOS

_No response_

**Comment by Kenshin** [comment]
嗨，此功能没问题，因为我刚刚在使用过，再者说，如果真的有问题，简悦的 Issues 会被「炸」掉 😂

***

这种配置问题如果不截图，基本上没法判断，所以：

1. 请详细截图（不怕图截错，就怕少截图）

2. 请不要使用 Notion Next 方案，先用排除法，确保 **Notion 辅助增强插件** 可以使用，然后在判断 Notion Next 是否有问题。

3. 请根据 https://www.yuque.com/kenshin/simpread/zx3bcz 排查你的配置是否有问题。

4. 也可以看下 Notion 的一些常见问题 https://www.yuque.com/kenshin/simpread/wwk65u

**Comment by zanezh** [comment]
1 详细截图请看附件
2 我尝试了不用notion next方案，先用了notion web clipper新建了一个table view的数据库，此时辅助增强插件 **可用**
3 检查了，没问题，见附件
4 我的问题没在里面，麻烦帮忙看一下，可能是啥原因

附件说明：前面的图片说明配置没问题。
我在没有合并表格前可用辅助增强，合并表格后不可用。倒数第二张图片是合并后的notion表头。
最后一个图片是出现问题时的表现：一直有一个提示：正在触发导入到 Notion 辅助增强，请稍等

<img width="1468" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/cbdf85ca-c88b-4e87-9788-b1c0f3504918">
<img width="1474" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/033b0bc8-2d72-4efb-aafc-25eb1ea09fd3">
<img width="894" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/62ec7aad-90c0-49dc-85ff-ac0e4ea66b59">
<img width="1289" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/c40b7940-ee63-480f-ab89-5c3dcdf1476b">
<img width="1465" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/cbae4859-d358-4bac-966f-e085bef9d7d8">
<img width="542" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/b207024d-748d-41fc-9e3f-c196021dde42">
<img width="1592" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/b6f775e3-d59d-4e95-8fe5-c676191a1174">

<img width="520" alt="image" src="https://github.com/Kenshin/simpread/assets/157906186/2b0a3004-8b86-462b-9fc6-ca08849bace7">

**Comment by Kenshin** [comment]
> 我尝试了不用notion next方案，先用了notion web clipper新建了一个table view的数据库，此时辅助增强插件 可用

**也就是不使用 Notion Next 则可以正常导入？** 请确认是否是这个意思？

假设是这个意思的话，再 **结合 Notion 辅助增强插件** （则无法使用）的话，自然问题出在 Notion Next。

估计可能不是你的配置问题，可能是 Notion Next 版本升级造成的。

你的截图中并没有体现出 Notion Next 的相关设置。

**Comment by zanezh** [comment]
嗯，是这个意思，向非Notion Next的数据库辅助增强生效。问题就出在 向Notion Next表格（数据库）的同步 时
我配置的部分经过我反复检查是没问题的
可能是NN升级，像你说的。

我的NN配置的截图倒是有，不过还没到notion next配置环境变量的那一步，notion next读取notion数据库，该数据库里现在都接受不到简悦辅助增强插件的结果，谈何博客内容更新呢。所以notion next的配置我就没放出图

**Comment by Kenshin** [comment]
emmm 你可能「弄错」了 😂

如果要使用 Notion Next 就必须要使用 [Notion Blog 生成器](https://github.com/Kenshin/simpread/discussions/3776) 以及在 Notion 辅助增强插件中设置（下图）

<img width="489" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2ea7c446-a9bc-47c7-bc61-10732ca00253">

否则肯定无法使用。

***

还有... 看截图吧

<img width="845" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/b06e5e52-c090-4d29-92ed-ef4122ec059c">
