### ISSUE TITLE
关于rss和适配问题

### ISSUE THREAD

**Issue by cyx951211** [Kenshin/simpread#6562]
### 请描述你的建议或任何内容

1、rss是否会适配，如果会，什么时候能适配？
2、Safar是否会适配，如果会，什么时候能适配？

### 补充说明

rss希望能有规则筛选

**Comment by Kenshin** [comment]
> 问题1

为什么要适配 RSS 请举个例子或者详细说下 😂

> 问题2

目前仍以 Chromium 内核浏览器为准，因为这是简悦最好的平台和载体，当然会适配 Safari 但优先级不高。

**Comment by cyx951211** [comment]
rss：这不是你自己说的 你有更好的方案https://github.com/Kenshin/simpread/issues/6526#issuecomment-2143340922
会适配 Safari ：时间点呢 都几年了 哥
