### ISSUE TITLE
建议增加编辑功能

### ISSUE THREAD

**Issue by xsb0624** [Kenshin/simpread#6563]
### 请描述你的建议或任何内容

现在转化后的页面主要是标注功能。在学习场景下，很适合将原网页缩减、调整、修改为自己理解的文档。既然已经转换为markdown格式了，那么也可以加上编辑功能。

**Comment by Kenshin** [comment]
一直都有... 😂 

此功能叫做 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 与其 [衍生的用法](https://github.com/Kenshin/simpread/discussions?discussions_q=label%3A%22live+editor%22)

#### 注意

不建议修改已经标注的页面，这样会让已标注的内容无法正确定位丢失标注，所以 Live Editor 更适合在加入稍后读（或首次标注前）对页面的整理（二次加工）。
