### ISSUE TITLE
无法在添加到稍后读后自动导出至obsidian

### ISSUE THREAD

**Issue by yodaliu0414** [Kenshin/simpread#6564]
### 描述这个错误

我在今天尝试配置了一下导出obsidian。但是不知道为什么一直没有成功。
第一回合，我的配置是有同步助手、开自动同步、有插件管理器：先设置好ob，刷新，再设置自动增强，刷新，关闭浏览器，开新的页面，用快捷键加入稍后读——可以加入稍后读，但不能导出到obsidian。
后来我删除并关闭了所有同步，只保留ob和自动增强两个插件，仍然没有效果。

### 复现步骤

我完全没有头绪这个是怎么发生的，唯一的线索是每当我用快捷键将页面加入稍后读，显示加入稍后读且没有导出到ob以后，我再点击浏览器中的简悦，就一定会提示我配置已经更新，需要刷新当前界面。重新安装简悦插件也是这样。

一些情景复现：

1. 在一个网站中，没有进入简悦模式，直接用快捷键加入稍后读-无法触发导入obsidian
2. 在一个网站中，进入简悦模式，用快捷键/点击加入稍后都-可以导入obsidian

请问有可能在1这个场景中，可以直接加入稍后读并导入obsidian吗？

### 操作系统

win11

### 浏览器

edge

### 发生问题的网址

https://sspai.com/post/89678

**Comment by Kenshin** [comment]
嗨。

新用户的话，建议直接使用官方的免配置的配置库方案 https://www.yuque.com/kenshin/simpread/psugef

***

你上面提到的大部分问题是因为：在调整简悦配置项时，多开了很多 Tab，调整配置项的官方建议 https://github.com/Kenshin/simpread/discussions/3768

简单的说，仅开两个 Tab 或者当调整完配置项后重启浏览器；但更建议你直接使用配置库方案。

***

加入稍后读并自动导入到 Obsidian 的使用前提是：使用快捷键 `d d` 加入稍后读，才能触发自动化。
