### ISSUE TITLE
因 Notion 版本升级导致私有 API 变更，因此【导入到 Notion】功能无法使用的汇总（附解决方案）

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6565]
### 描述这个错误

从 2024年6月22日，有用户提示后发现导入到 Notion 功能无法正常使用

### 现象如图

<img width="340" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/a124eae6-fa45-4900-ba84-eacad37245ee">

### 使用方式

插件端 [导入到 Notion](https://github.com/Kenshin/simpread/discussions/4954) 

<img width="268" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/92d53b4a-110a-4812-be7d-3c6a933240f6">

### 受影响页面

任意 URL 均无法使用。

### 接下来

我会详细调查，尝试是否可以解决。（但如果不是简悦的问题则无法解决，Notion 已经无数次证明大部分这类问题都是它自身造成的。

#### 吐个槽

Notion 的品控是我见到最... 只要它一升级，各种 Bug 不断，感兴趣的话，围观上次事件在 2024年1月16日 https://github.com/Kenshin/simpread/issues/6259

下图是简悦收集近年 Notion 升级导致的问题。

<img width="826" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/ded3cd01-c5cf-418a-9084-b4340b5b7616">

### 操作系统

Mac

### 浏览器

Chrome

### 发生问题的网址

https://sspai.com/post/69972

**Comment by SurDark** [comment]
同样的问题，期待升级

**Comment by name2500** [comment]
同样的问题，折腾死了~求升级

**Comment by andyinzy** [comment]
notion是这样的，api使用者只要全身心投入到版本适配、修bug中就可以了，可是notion开发者要考虑的事情就很多了。
ps：notion的傲慢不是一天两天了。

**Comment by Kenshin** [comment]
@andyinzy 

确实如此，只要是 Notion 升级就会出现大量的问题，有些无解，有些问题基本上延迟 1~2 个月才被解决。（甚至于这些明显的 Bug 问题我已经跟他们官方反馈了不止一两次），下图是简悦收集近年 Notion 升级导致的问题。

<img width="832" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/23df1ce2-752b-46d0-8778-e6dc3d94d445">

**Comment by dashimu** [comment]
期待解决

**Comment by Kenshin** [comment]
嗨，各位，此问题已经解决。


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

***

我关闭这个 Issues 了，有任何问题随时在这里讨论~

**Comment by SurDark** [comment]
有效，感谢！

**Comment by LVicBlack** [comment]
有两个问题，安装插件后依然有问题

1. “保存到notion” 功能，只有标题，没有内容
2. “一键导入全文到notion”，设置界面显示授权成功，但是使用时提示失败，如下图
-- 设置成功 ![](https://cdn.jsdelivr.net/gh/LVicBlack/IMG/root/2024/07/screenshot_2024-07-03_14-25-21.png)
-- 保存时提示失败 ![](https://cdn.jsdelivr.net/gh/LVicBlack/IMG/root/2024/07/screenshot_2024-07-03_14-25-49.png)

**Comment by Lance729** [comment]
重新安装“导入到Notion”插件后，仍然无法使用，会一直卡在图床保存这里。即便是保存成功，也会一直卡住，而无法保存到notion
![image](https://github.com/user-attachments/assets/54bd3e06-0954-4cee-bb67-f2fc87bc0653)
