### ISSUE TITLE
PDF导出界面混乱

### ISSUE THREAD

**Issue by SHAWNHU0621** [Kenshin/simpread#6567]
### 描述这个错误

https://mp.weixin.qq.com/s/pQr8M7GX3SGeagkb3xnqoQ
公众号文章尝试用pdf导出放大公众号中用于装饰的小图片，影响整体排版和阅读
![屏幕截图 2024-06-24 100212](https://github.com/Kenshin/simpread/assets/156273769/8b614424-eae9-49d1-b20b-9adb480a8327)

### 复现步骤

第一步，点击导出为PDF
第二步，在打印界面看到这样的排版

### 操作系统

Windows10

### 浏览器

edge浏览器 版本 125.0.2535.67 (正式版本) (64 位)

### 发生问题的网址

https://mp.weixin.qq.com

**Comment by Kenshin** [comment]
嗨 😂

这种类型的页面就这样（不是简悦的问题，因为简悦完全没办法判断这种乱七八糟的页面）

但你可以使用 [Live Editor](https://github.com/Kenshin/simpread/discussions/2852) 删除或修改不需要的内容，然后也可以考虑使用 [微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 增强公众号的阅读模式体验。

如果使用同步助手的话，建议使用 https://github.com/Kenshin/simpread/discussions/3887
