### ISSUE TITLE
关于 Onenote 的使用疑问

### ISSUE THREAD

**Issue by vouss123** [Kenshin/simpread#6572]
### 描述这个错误

您好，网页显示成功导入到OneNote，但是却无法找到笔记，也找不到快捷笔记或者simpleread。也登入到OneNote的web端查看了，但还是找不到

### 操作系统

windows

### 浏览器

vivaldi

### 发生问题的网址

，

**Comment by Kenshin** [comment]
嗨，我已经很久不用 Onenote 了 😂

如果在导入时提示成功就没问题，但一般来说导入到 Onenote 后会有不小的一段时间延迟（具体多久不太清楚，也都是简悦用户反馈时提到的。

PS：建议使用更现代的笔记方案。
