### ISSUE TITLE
关于高亮文字的最佳实践

### ISSUE THREAD

**Issue by ViNull008** [Kenshin/simpread#6573]
### 请描述你的建议或任何内容

请教作者,我想咨询一下高亮文本的最佳实践.

我当前的理解是(可能不完全对),高亮后的文字,可以在稍后读里面汇总,这样在当天可以针对某一个topic进行集中信息汇总.
有一些问题:

1. 有一些文章可能在一段时间后就失效了,那么这种情况下,在稍后读里面还能看到吗? 即稍后读是否是缓存在某处的.

2. 如果想把高亮和ob结合,即把文章导出到本地,有没有更好的流程? 只要保存时md时,把高亮一起保存即可

3. 作者可以分享一下你设计这个功能的初衷和最佳实践吗?

感谢

**Comment by Kenshin** [comment]
嗨

> 高亮后的文字,可以在稍后读里面汇总,这样在当天可以针对某一个topic进行集中信息汇总.

严格上说并没有提到的 Topic 概念（但此方式很好，我会考虑），但汇总是有的，包括：稍后读和每日邮件提醒，但不是以标注为基准，而是以稍后读为基准（算是殊途同归），下图是 24 小时内的汇总和本周汇总

<img width="243" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/cf0aa6e8-f535-4ba1-96d5-8807426f9a58">

> 有一些文章可能在一段时间后就失效了,那么这种情况下,在稍后读里面还能看到吗? 即稍后读是否是缓存在某处的.

简悦标注的定位严苛按照文章结构定位，所以失效的原因在于：原页面的结构改变了。

解决方案：

简悦有将网页本地化的方式，你可以理解为本地快照（在简悦中叫做：知识库）当 [配置了知识库](https://www.yuque.com/kenshin/simpread/wkswh7) 后，会解决此问题。（因为已经不依赖于原页面了）

> 如果想把高亮和ob结合,即把文章导出到本地,有没有更好的流程? 只要保存时md时,把高亮一起保存即可

当然有，https://www.yuque.com/kenshin/simpread/fr8zo5 或者直接使用简悦官方的配置库方案 https://www.yuque.com/kenshin/simpread/zuptv2

> 作者可以分享一下你设计这个功能的初衷

可以看下 https://www.yuque.com/kenshin/simpread 下面的内容

<img width="1027" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/791730cc-96f4-4794-ab73-8cbf8f83287b">

或者少数派中 https://sspai.com/u/kenshin/posts 跟简悦相关的内容。

> 和最佳实践

笔记用户使用不同的笔记方案，所以会有不同的方式，因此最佳实践其实是没有的，但简悦官方总结了不少简悦用户的用法，你可以参考下 https://github.com/Kenshin/simpread/discussions/2085

**Comment by ViNull008** [comment]
感谢作者，很详细，很靠谱！

**Comment by Kenshin** [comment]
哈，能帮到你就好 👍

我关闭这个 Issues 了，有任何问题随时在这里跟我讨论~
