### ISSUE TITLE
在nga论坛进入阅读模式时图片加载失败

### ISSUE THREAD

**Issue by Tamanegii** [Kenshin/simpread#6578]
### 描述这个错误

在nga帖子中进入阅读模式，图片有概率全部变成无法显示的标志*「剩余情况则是显示前一两张图片，其余图片裂开」
似乎也只能显示第一楼的文字，无法加载下面的追加评论

### 复现步骤

 以https://bbs.nga.cn/read.php?tid=37365107 为例，在链接中进入阅读模式显示如下
![image](https://github.com/Kenshin/simpread/assets/62172738/277f4de6-9b91-4f4f-a029-0b0ea9f4aa06)
裂开的地方实际为一张布局图
刷新之后有概率出现的新样子
![image](https://github.com/Kenshin/simpread/assets/62172738/dfa152bb-1e51-4217-bfe5-66324ff86fb4)

### 操作系统

Windows11

### 浏览器

Edge

### 发生问题的网址

https://bbs.nga.cn/read.php?tid=37365107

**Comment by Kenshin** [comment]
嗨，你可以使用下面的方式实现

<img width="731" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/9a6017fc-053d-47d4-906d-83cdf8a55e80">

效果如下

<img width="1810" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/e3ab264b-d1eb-4063-a182-74af295bd05f">

**Comment by Tamanegii** [comment]
> 嗨，你可以使用下面的方式实现
> 
> <img alt="image" width="731" src="https://private-user-images.githubusercontent.com/81074/343668766-9a6017fc-053d-47d4-906d-83cdf8a55e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTU1MzUsIm5iZiI6MTcxOTQ5NTIzNSwicGF0aCI6Ii84MTA3NC8zNDM2Njg3NjYtOWE2MDE3ZmMtMDUzZC00N2Q0LTkwNmQtODNjZGY4YTU1ZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYTNjNWQzYTBiNmQyOWE5ZWViMTBjNGZmZTc2OTMxMzlhNDE0YWZlZTg5MDFjZjBlMjgzYWQxYTQ3NTJhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2obGjcjcDu5_jQKBvtoM-lZ-E6l6tI8WD-rh9SpVfmw">
> 效果如下
> 
> <img alt="image" width="1810" src="https://private-user-images.githubusercontent.com/81074/343668901-e3ab264b-d1eb-4063-a182-74af295bd05f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTU1MzUsIm5iZiI6MTcxOTQ5NTIzNSwicGF0aCI6Ii84MTA3NC8zNDM2Njg5MDEtZTNhYjI2NGItZDFlYi00MDYzLWExODItNzRhZjI5NWJkMDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzEyYTQ0ZWVkMWFkMjI2OTc3ZGUyNjJlODRmZTQwNjM2NTdkNzNiOGJkM2I5YWI2YzE4ODk0MDFhZWQ4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUVjHDIJmmUD_gK2_xAVvJJRg8A80IJMBK1FKM_NE7w">

get，感谢

**Comment by Kenshin** [comment]
okay 搞定就好，我关闭这个Issues 了，有问题随时在这里提交。
