### ISSUE TITLE
PDF 辅助增强选项中，图片宽度设置后打印pdf未能生效。

### ISSUE THREAD

**Issue by Sssugus** [Kenshin/simpread#6581]
### 描述这个错误

PDF 辅助增强选项中，图片宽度设置后打印pdf未能生效。

出现问题的网址：https://mp.weixin.qq.com/s/qLNLdi1-i5WCwpUMB21LUg

### 复现步骤

1. PDF辅助增强选项，使用同步助手高级方案；
2. 图片宽度设置为50；
![image](https://github.com/Kenshin/simpread/assets/82427022/b9135387-3e23-4959-8aa1-69ad619ddfae)

4. 打印后文档图片大小与设置图片宽度前一致，没有生效。

### 操作系统

win10

### 浏览器

edge

### 发生问题的网址

https://mp.weixin.qq.com/s/qLNLdi1-i5WCwpUMB21LUg

**Comment by Kenshin** [comment]
是仅此一个 URL 出现问题？还是任意 URL 均存在？

**Comment by Sssugus** [comment]
> 是仅此一个 URL 出现问题？还是任意 URL 均存在？

测试了另一个网址：https://www.iplaysoft.com/macos-sequoia.html，情况是一样的。

**Comment by Kenshin** [comment]
并不是每个页面都不好使 😂 只是你选择的页面本来「限制就比较多」 e.g. https://www.ifanr.com/1589508 就没问题。

你可以使用自定义样式解决

```
sr-rd-content img {
  max-width: 50%!important;
}
```

<img width="588" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/4126c3ef-f0cb-4a63-846d-213cf9aab613">

保存后再打印。

**Comment by Sssugus** [comment]
> 并不是每个页面都不好使 😂 只是你选择的页面本来「限制就比较多」 e.g. https://www.ifanr.com/1589508 就没问题。
> 
> 你可以使用自定义样式解决
> 
> ```
> sr-rd-content img {
>   max-width: 50%!important;
> }
> ```
> 
> <img alt="image" width="588" src="https://private-user-images.githubusercontent.com/81074/344364624-4126c3ef-f0cb-4a63-846d-213cf9aab613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzY2NzQsIm5iZiI6MTcxOTY3NjM3NCwicGF0aCI6Ii84MTA3NC8zNDQzNjQ2MjQtNDEyNmMzZWYtZjBjYi00YTYzLTg0NmQtMjEzY2Y5YWFiNjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE1NTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjExODE0MmVmZWUxMDBjOWE4YzRmYTYzZjIyYWMzNGIzNmU0Yzk2YWVjNzVjMGI2Nzg4NDhjYTU1NmRkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CRYGGCG57QwUG-JmHh60he6vLAoSz3zOAgJaYdFsOTs">
> 保存后再打印。

可行，完美解决了。

**Comment by Kenshin** [comment]
哈，解决就好 👍 😄
