### ISSUE TITLE
Notion 绑定异常

### ISSUE THREAD

**Issue by kaaaaai** [Kenshin/simpread#6584]
### 描述这个错误

点击 notin 绑定没有反应

### 复现步骤

<img width="1256" alt="image" src="https://github.com/Kenshin/simpread/assets/30493584/7696c5fa-d0b0-4e0b-8435-246e288ed1d6">

### 操作系统

macOs

### 浏览器

Chrome is up to date Version 126.0.6478.127 (Official Build) (arm64)

### 发生问题的网址

无

**Comment by Kenshin** [comment]
请使用此方案 https://github.com/Kenshin/simpread/discussions/4954

不要使用简悦内置方案。
