### ISSUE TITLE
无法使用同步助手

### ISSUE THREAD

**Issue by norcx** [Kenshin/simpread#6587]
### 描述这个错误

![image](https://github.com/Kenshin/simpread/assets/130429072/8fe7479f-4487-4fab-a07e-a327bbe67838)
点击同步助手，无法转到界面。
通用只有这个界面。
浏览器是[ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium)

### 复现步骤

![image](https://github.com/Kenshin/simpread/assets/130429072/8fe7479f-4487-4fab-a07e-a327bbe67838)
可能是浏览器的问题，可能是简悦的问题。

### 操作系统

window11

### 浏览器

ungoogled-chromium最新版

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

**Comment by Kenshin** [comment]
> 点击同步助手，无法转到界面。

没明白你的问题。厂

> 可能是浏览器的问题

没有用户反馈过（我理解的）类似的问题。

所以，大概率是 ungoogled-chromium 的问题。

所以…请使用 Chrome 测试，如果不喜欢 Chrome 的话，请使用 Edge 测试。

PS：我都没听过 ungoogled-chromium 😂
