### ISSUE TITLE
无法保存到notion

### ISSUE THREAD

**Issue by SnowBrok** [Kenshin/simpread#6591]
### 描述这个错误

在我使用简悦时，无法将文章保存到notion，会一直显示保存中,不光是此网站，所有的网页现在都保存不了了
![PixPin_2024-07-05_15-35-54](https://github.com/Kenshin/simpread/assets/98537307/18f66d4d-e907-49ab-9820-993ee7800259)

### 复现步骤

使用简悦点击保存全文到notion时，页面一直显示正在保存到notion，请稍等...实际上无论等了多久还是依然显示在那里，无法保存到notion，此外少数派的文章中的图片也是上传图床失败

### 操作系统

windows

### 浏览器

chrome

### 发生问题的网址

https://sspai.com/post/90154

**Comment by Kenshin** [comment]
解决方案请看这里 https://github.com/Kenshin/simpread/issues/6565

就在你提问地方的置顶 😂

<img width="1343" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/2acb2a3c-8783-4456-85af-f0ff8930ee9c">

**Comment by Kenshin** [comment]
如果所有的配置没有，肯定没有你提到的情况… 😂

建议跟 https://www.yuque.com/kenshin/simpread/zx3bcz 对比下。

**Comment by Kenshin** [comment]
Okay 👍 😄

***

如果简悦解决了你的导出问题，方便的话请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
