### ISSUE TITLE
打开 simpread.pro 较慢

### ISSUE THREAD

**Issue by zhaotd** [Kenshin/simpread#6592]
### 描述这个错误

其他网页没问题的，网络也没问题的，就是登陆这个特别慢，是不是服务器的原因呢？如果后面此插件关了，我们还能在用吗？

### 复现步骤

同上。

### 操作系统

win

### 浏览器

EDGE

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html

**Comment by Kenshin** [comment]
是不是 https://github.com/Kenshin/simpread/discussions/6590 造成的？

**Comment by Kenshin** [comment]
> 如果后面此插件关了，我们还能在用吗？

当然不会关... 😂

免费阶段都没「关」，收费阶段并且还「活的很好」，干什么要关？😂 😂 😂

**Comment by zhaotd** [comment]
> 是不是 #6590 造成的？
> 
> 此链接内含解决方案。
太厉害了，完美切精准的解决了我的问题！

**Comment by Kenshin** [comment]
😂

当遇到一些共通性问题，我都会在 https://github.com/Kenshin/simpread/discussions 发布相关解决方案~

***

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
