### ISSUE TITLE
 代码高亮识别不佳

### ISSUE THREAD

**Issue by HeWanli** [Kenshin/simpread#6599]
### 描述这个错误

部分网站进入阅读模式后，看不到代码部分

### 复现步骤

这个网站，https://modstart.com/p/34fhv7m910c3e4t1
![image](https://github.com/Kenshin/simpread/assets/10569865/a072ad97-8ca9-4973-8725-1dea80376263)
当双击下A的进入阅读模式，会看不到代码部分
![image](https://github.com/Kenshin/simpread/assets/10569865/a5b701ba-b7a8-4fb0-93f1-68f84f0c2b91)

### 操作系统

window 11

### 浏览器

Chrome 126.0.6478.127

### 发生问题的网址

https://modstart.com/p/34fhv7m910c3e4t1

**Comment by Kenshin** [comment]
嗨

这个问题不是 **部分网站会把代码行给过滤掉**  🌚  而是 **代码高亮识别不佳**

这个暂时没有很好的解决方案，因为代码高亮规则太多了，没法统一所以也没法彻底解决。

***

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~

**Comment by HeWanli** [comment]
好的，非常感谢！
