### ISSUE TITLE
建议支持除了Wikipedia以外的baike.baidu.com和baike.com

### ISSUE THREAD

**Issue by hyperdoit** [Kenshin/simpread#66]

**Comment by Kenshin** [comment]
`1.0.1` 版本的简悦支持 wikipedia.org 但不支持 baike.baidu.com 和 baike.com ...
原因是后两者的页面结构太复杂，导致无法有效解析。

**Comment by nuomi1** [comment]
Wikipedia 中，建议可选显示左侧的语言选择区，另外右侧的信息区也没有收集。

![qsmy old](https://user-images.githubusercontent.com/3739017/29742908-257cdc30-8aba-11e7-84d8-4afc77dd132c.png)

![qsmy new](https://user-images.githubusercontent.com/3739017/29742907-25481874-8aba-11e7-8fb7-180449814f69.png)

**Comment by Kenshin** [comment]
@nuomi1 
感谢建议~

由于 `阅读模式` 的定位只在 `显示大段内容、文字与图片`，所以像 wikipedia 这类的页面支持度不是很高。

- `TOC 目录` 的功能其实已经在计划中了；
- `语言选择区和右侧的信息区`，并不在计划中，如果要实现的话，只能做专门适配 wikipedia 的页面；

另外，`1.0.2` 版已经支持了论坛类的页面，详细可以看 http://ksria.com/simpread/changelog.html#1.0.2

`1.0.2` 为未发布测试版，将会跟 `1.0.3` 9月份左右一起发布。

**Comment by hyperdoit** [comment]
在Wikipedia中对于英文单词的换行支持不太友好，不知道新版本是否会支持？

**Comment by Kenshin** [comment]
@hyperdoit
具体指什么，阅读模式下有问题吗？

**Comment by nuomi1** [comment]
参考例图中的「AVL 节点数计算」，公式图片被渲染成了新一行。

![avl old](https://user-images.githubusercontent.com/3739017/29749961-780b385c-8b69-11e7-9c76-498f2c40b3be.png)

![avl new](https://user-images.githubusercontent.com/3739017/29749960-77dc4894-8b69-11e7-8e24-b13b209b657e.png)

**Comment by Kenshin** [comment]
@hyperdoit
这是个问题，因为简悦会把图片资源居中（因为美观），所以出现了这种情况。
目前简悦没太好的办法可以分辨哪些图片不需要居中。

**Comment by hyperdoit** [comment]
我的意思主要啊是像是一个词会分两行显示，不像word里会自动换行如果当前行放不下

**Comment by Kenshin** [comment]
@hyperdoit 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

这个问题可以用 `自定义样式` 来解决，具体办法： 选项 → 高级设定 → 自定义样式 → 自定义 CSS 中加入如下内容即可：

```
sr-rd-content *, sr-rd-content p, sr-rd-content div {
    word-break: break-word;
}
```

***

另外图片居中的问题我想到了解决办法，只能在下个版本中再解决了。
不过，解决办法也不是很智能，需要人工判断。
我会再加入一个 `新的标识`，凡事这个标识的图片不会在自动居中。

**Comment by Kenshin** [comment]
简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share) 

***

以下是这些页面的截图

如 https://zh.wikipedia.org/wiki/AVL%E6%A0%91

![image](https://user-images.githubusercontent.com/81074/57218935-349a2c80-7029-11e9-8c52-02b436df3b90.png)
