### ISSUE TITLE
知乎适配 question/xxxxx/answer/xxx 类页面

### ISSUE THREAD

**Issue by yi-Xu-0100** [Kenshin/simpread#660]
链接：https://www.zhihu.com/question/29745861/answer/65068214

卡死图片：
![卡死](https://user-images.githubusercontent.com/25523606/74580915-0bf58900-4fe4-11ea-8a36-56a1e8ba768a.png)

效果，无法移动页面
而且生成的临时页面可以移动，但是会包含所有的回答，以前，这样的特定答案的链接，应该只包含当前回答。不知道怎么解决，谢谢

**Comment by Kenshin** [comment]
我刚测试了下，没有遇到你说的问题。

请告知详细环境，简悦版本 等信息。

**Comment by yi-Xu-0100** [comment]
找到bug触发点了，我的知乎没有登录，刚打开这个页面没有建议登录的窗口，下滑看内容，一段距离会出现。如图：
![image](https://user-images.githubusercontent.com/25523606/74585733-f64f8600-501a-11ea-8c50-d387ca789ad0.png)

而如果刚打开这个网页，还没有下滑，也不会有这个提示，此时我直接使用简悦后，到转换后的页面，下滑阅读时，会产生卡死，弹不出这个页面，没法关闭所以无法移动。


而且这样确定相应回答的连接，也无法只产生当前回答的页面，这样会造成，我要是导出的时候，会导出很多回答的页面，我不知道是不是我没有登录的原因，如果是，能否提供没有登录的情况下的优化版本，谢谢！

**Comment by yi-Xu-0100** [comment]
我使用的是win10的Google浏览器，简悦版本1.1.4

**Comment by Kenshin** [comment]
谢谢反馈这个 Bug 已复现

可以用下面的方式解决：

```
html {
    overflow:initial!important;
}
```

复制上面代码粘贴到 选项页 → 动作 → 设定 → 第二个 icon 弹出下图的界面，粘贴到红框即可。

![image](https://user-images.githubusercontent.com/81074/74586382-da9bae00-5021-11ea-8041-410eafe57c82.png)

***

先不要关闭这个 issues 因为适配列表未包含这个方式，我需要不定期统一更新这个列表。

**Comment by yi-Xu-0100** [comment]
emmm,不知道多个答案这个问题怎么解决？
我只想看这一个回答，并导出，但是没法实现……我记得以前是行的，是知乎改变策略了嘛，造成现在没法对应适配？

**Comment by Kenshin** [comment]
> 多个答案的问题

这个是 URL 导致的，你访问 https://www.zhihu.com/question/29745861 这个地址就有论坛类页面了。

**Comment by yi-Xu-0100** [comment]
现在访问两种类型连接，生成的页面都是包含很多答案的，我想要访问答案连接时可以生成单答案页面：https://www.zhihu.com/question/29745861/answer/65068214

或者说，阅读模式可以显示多个答案，但是生成临时页面的时候，支持生成单答案，方便导出~谢谢

**Comment by Kenshin** [comment]
> 阅读模式可以显示多个答案，但是生成临时页面的时候，支持生成单答案

目前没有这样的功能，（也有可能）不会提供这样的方式。

**阅读模式** 对应了 **生成的临时页面的结构**，所以你 **需要的单页面** 方式，**用单页面** 的阅读模式即可，反之也一样。

**Comment by yi-Xu-0100** [comment]
emmm……问题是现在的单答案链接<https://www.zhihu.com/question/29745861/answer/65068214>打开后的界面如下：

![image](https://user-images.githubusercontent.com/25523606/74601005-f6f82300-50d3-11ea-9e98-928262a28455.png)

他在链接指向的答案后面，提供了**更多回答**的板块，造成阅读模式下，看到的页面效果如下：

![image](https://user-images.githubusercontent.com/25523606/74601026-2a3ab200-50d4-11ea-9c0d-0907dbbafc83.png)

我没法得到想要的单页面，希望能够对这样链接的情况做处理，使**更多回答**不会出现在阅读模式下，产生单答案的页面。

而如果链接是<https://www.zhihu.com/question/29745861>打开后的界面如下：

![image](https://user-images.githubusercontent.com/25523606/74601077-bd73e780-50d4-11ea-8e8f-ca94b495c456.png)

所有的答案出现是相连的，没有**更多回答**，两种页面是不同的。但是阅读模式下，效果是一样的。造成我无法使用**单页面**的阅读模式。

非常感谢耐心解答，知乎的版面设计可能有变更，以前这样的答案链接应该没有**更多回答**的版面，所有阅读模式下，只有一个回答，也就是单页面，现在的样式，没法很好的导出，麻烦看看能不能匹配下，谢谢！

**Comment by yi-Xu-0100** [comment]
我发现了问题，我以前保存的那次的结果是单答案的情况是有原因的。

答案链接中需要将**www**改为**www2**，如：
<https://www2.zhihu.com/question/29745861/answer/65068214>

这样的页面似乎没有任何变化，但是简悦的阅读模式下只会保留当前答案，我不知道两者有何区别，他们同样都有**更多回答**。

我算是解决了问题，但是我不知道这是怎么弄出来的。以前的那次保存，也不清楚为啥会产生这样的差别，但是幸运的是我找到了当时的记录，知乎的这个匹配问题可能没有必要，可以使用这个方法解决。

再次感谢耐心解答，谢谢！

**Comment by Kenshin** [comment]
`www2` 这个地址与 `www` 是不一样的，简悦仅仅适配了 `www` 这个页面，这就是你看到的效果。

关于你的需求，也可以这样实现。

1. 打开 https://www.zhihu.com/question/29745861

2. 进入阅读模式后，自然是论坛类页面

3. 右下角 → 选项 → 动作 → 设定 → 第三个 icon 然后重新框选你需要的高亮部分，即可。

或者找到你需要 **单页面显示** 的那条信息对应的 URL e.g. https://www.zhihu.com/question/29745861/answer/65068214 也是一样的。

**Comment by yi-Xu-0100** [comment]
> 或者找到你需要 单页面显示 的那条信息对应的 URL e.g. https://www.zhihu.com/question/29745861/answer/65068214 也是一样的。

这个在我这里是做不到的，不知道是不是bug，如图：

![image](https://user-images.githubusercontent.com/25523606/74601574-afc16080-50da-11ea-8721-04b178a98049.png)


> 关于你的需求，也可以这样实现。
>
>1. 打开 https://www.zhihu.com/question/29745861
> 
> 2. 进入阅读模式后，自然是论坛类页面
>
> 3. 右下角 → 选项 → 动作 → 设定 → 第三个 icon 然后重新框选你需要的高亮部分，即可。

这个方法**能够成功**，非常感谢~

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/74602840-01bcb300-50e8-11ea-9061-2f95188d56bb.png)

我使用了简悦的自定义适配源的方式，更新了对这个链接的适配，效果很好。现在的优先级是我的本地的适配源优先度高，可以很好的解决我的问题，如果后期官方源能够提供同样的url匹配，那就更好了~感谢~

感谢耐心解答和帮助！

**Comment by Kenshin** [comment]
嗨，谢谢对 answer 的适配，主适配源会不定期更新。

更新后，我会在这里通知你。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
