### ISSUE TITLE
无法查看腾讯文档，以下是使用中提示的步骤

### ISSUE THREAD

**Issue by wasyddd** [Kenshin/simpread#6600]
### 请描述你的建议或任何内容

1.获取正文失败，是是否使用手动框选高亮的方式获取？
2.高亮无法仍无法适配此页面，是否提交？

**Comment by Kenshin** [comment]
嗨，文档类的页面都不会被适配，因为涉及到版权，e.g. 百度文档、金山文档、飞书文档等。

我关闭这个 Issues 了~
