### ISSUE TITLE
obsidian simpread plugin 7027 服务无法启动

### ISSUE THREAD

**Issue by xozoz** [Kenshin/simpread#6601]
### 需要适配的新站

> 环境

- obsidian 1.6.5
- ob installer 1.5.12
- simpread sync 2.1.1

1. 启用插件后，按照教程，验证可用性，发现浏览器访问 http://localhost:7207 无法访问
2. 尝试在阅读模式下标注后，导入到 ob，标注，导出文件都正常，但是无法保存到 ob

<img width="807" alt="CleanShot 2024-07-10 at 13 23 44@2x" src="https://github.com/Kenshin/simpread/assets/21237993/48913b46-98cc-42ec-afe0-f6b8c6663d1c">
<img width="1436" alt="CleanShot 2024-07-10 at 13 24 18@2x" src="https://github.com/Kenshin/simpread/assets/21237993/f8eb3ac9-0dba-4748-ac0d-523c553d0dbd">

**Comment by xozoz** [comment]
已解决。

解决方案：将 plugin 配置中的 `localhost` 改为 `127.0.0.1`

原因：不可描述

**Comment by Kenshin** [comment]
😏  🌚  👏  👍
