### ISSUE TITLE
出现“此功能为实验性功能... “导出失败提示

### ISSUE THREAD

**Issue by cnshijin** [Kenshin/simpread#6606]
### 描述这个错误

原使用正常，近期出现“此功能为实验性功能... “导出失败提示，删除助手后重装也没有用

### 复现步骤

![微信图片_20240712105454](https://github.com/user-attachments/assets/fe082d65-a454-4f6f-966c-25616cbfb239)

https://github.com/user-attachments/assets/993c36b0-454f-4997-a6af-0ab078f67bdf

### 操作系统

windows11

### 浏览器

edge 126.0.2592.87 

### 发生问题的网址

www.weibo.com

**Comment by Kenshin** [comment]
1. 是不是你的高级账户掉了，试试 https://www.yuque.com/kenshin/simpread/sw4m21 然后重启浏览器

2. 试试其它页面 e.g. https://sspai.com/post/69972

3. 如果上条没问题的话，多试试非 weibo.com 的页面。

4. 这是调用哪个功能出现的？你没有详细描述...

**Comment by cnshijin** [comment]
页面保存到稍后读出现的问题

**Comment by cnshijin** [comment]
> 1. 是不是你的高级账户掉了，试试 https://www.yuque.com/kenshin/simpread/sw4m21 然后重启浏览器
> 
>     2. 试试其它页面 e.g. https://sspai.com/post/69972
> 
>     3. 如果上条没问题的话，多试试非 weibo.com 的页面。
> 
>     4. 这是调用哪个功能出现的？你没有详细描述...

刚刚试了下，确实在微博页面上出现，其他网站是正常的，谢谢！

**Comment by Kenshin** [comment]
> 确实在微博页面上出现，其他网站是正常的

估计你在加稍后读的时候也包含了导出等自动化相关操作，**但 weibo 有非常严苛的机制（之前都没问题，是近几个月他们做了一些限制导致）**，会导致这些导出失败。

简悦的做法是：会严格按照原网站的规则，不会做特别的「破坏」😂

所以，这个问题暂时无解，我关闭这个 Issues ~

**Comment by Kenshin** [comment]
补充下：应该是图片有严格规则限制。
