### ISSUE TITLE
无法安装「导入到 Notion」插件

### ISSUE THREAD

**Issue by kumokiyoshi** [Kenshin/simpread#6609]
### 描述这个错误

如图，其他的插件可以正常安装
![image](https://github.com/user-attachments/assets/5faeb30f-5d23-4f14-a610-62cd1e40dd2f)

### 复现步骤

![Snipaste_2024-07-13_15-12-31](https://github.com/user-attachments/assets/6a31ee36-f2ff-468b-bf96-75129ca1737a)
点击下载之后弹出安装界面，再定向到插件管理页面，但实际上没有安装成功。

### 操作系统

Windows 10 19045.4651

### 浏览器

Chrome 126.0.6478.127

### 发生问题的网址

SimpRead

**Comment by Kenshin** [comment]
有点奇怪

1. 你提到了插件管理器，但第一个界面中没有显示插件管理器（插件管理器也是一个插件）

2. 第二个截图中你提到的方式跟插件管理器没有关系。

所以...

1. 确定你描述中内容的准确性

2. 如果你使用了同步助手的自动同步功能，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u) 安装插件。
