### ISSUE TITLE
你们官网给的360浏览器下载的版本还是1.1.2，找不到1.1.4的版本

### ISSUE THREAD

**Issue by remotegithub** [Kenshin/simpread#661]
你们官网给的360浏览器下载的版本还是1.1.2，找不到1.1.4的版本

**Comment by Kenshin** [comment]
1.1.4 版暂时仅限 Chrome  或者可以下载离线版本，然后使用开发者模式安装。

**Comment by remotegithub** [comment]
离线下载，那个超链接点进去，页面有问题 804586880 邮箱：804586880@qq.com 签名由 网易邮箱大师 定制 在2020年02月15日 15:20，Kenshin Wang 写道： 1.1.4 版暂时仅限 Chrome 或者可以下载离线版本，然后使用开发者模式安装。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kenshin** [comment]
谢谢反馈，已修复这个问题。

你可以重新下载，或者使用下面的方式

1. 访问 https://chrome-extension-downloader.com/

2. 输入 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

3. 将下载的 crx 文件试着拖进 360 看看能否成功？

如果不成功的话，请使用之前说的方案。
