### ISSUE TITLE
开放平台的API支持新建标注吗？

### ISSUE THREAD

**Issue by gxcuit** [Kenshin/simpread#6614]
### 请描述你的建议或任何内容

开放平台的API 支持新建标注吗？ 例如我想将hypothesis 的标注，导入到简悦中。请问该如何实现呢

**Comment by Kenshin** [comment]
嗨，暂时不支持 😂

但支持从简悦 →  Hypothesis

PS：如果 Hypothesis 不是很多的话，建议先留着，这个服务也可以，虽然有部分功能不如简悦。

**Comment by gxcuit** [comment]
> 嗨，暂时不支持 😂
> 
> 但支持从简悦 → Hypothesis
> 
> PS：如果 Hypothesis 不是很多的话，建议先留着，这个服务也可以，虽然有部分功能不如简悦。

Hi, 感谢回复！
我其实是想要一个能直接web annotation的，类似与readwise reader web 插件一类的

anyway， thanks again

**Comment by Kenshin** [comment]
> readwise reader web 

即便不考虑它的价格的话，它其实并不太好用，国内的网站大部分都会抓取失败，甚至很多国外的网站亦然。

我一直是 Readwise 的用户，简悦从最初的版本就支持导入到 Readwise 中。

基于阅读模式的标注优势在于：更专注于正文，所以更适合长文 + 深度阅读的场景，再结合集成 OpenAI 的 [阅读助手](https://github.com/Kenshin/simpread/discussions/5158)  （尤其是刚刚接入了 `GPT-4o mini` 效果斐然 

😄
