### ISSUE TITLE
假期快乐；思源笔记导入问题   开启图床会导致调用失败

### ISSUE THREAD

**Issue by TangQi001** [Kenshin/simpread#6616]
### 描述这个错误

大佬可以先度过假期不用回我
这个问题算是小问题，网页文件siyuan也能自动转换
![image](https://github.com/user-attachments/assets/5abafd34-6ab0-4f3e-bf97-fe35a4908415)
开启上列设置
![image](https://github.com/user-attachments/assets/92701acd-b336-45c4-826d-e1d151428420)
导致结果如图，当不开启设置时，不会出现这个问题

### 复现步骤

1.打开图床
2.导入笔记
3.出现调用失败的问题

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://blog.csdn.net/joeyoj/article/details/136427362

**Comment by Kenshin** [comment]
嗨，竟然知道我在休假 😂 👍

你可以看下 https://github.com/Kenshin/simpread/issues/6341#issuecomment-1970579429 跟你的问题相似

**Comment by Kenshin** [comment]
试试爱范儿的网站。

否则只能等到周三了… 😂

因为台风导致航班取消了，所以全部都要延迟一天。

**Comment by Kenshin** [comment]
嗨，我这边测试了下，是没问题的 😂

测试网站 https://sspai.com/post/90755

简悦设置

<img width="654" alt="image" src="https://github.com/user-attachments/assets/adbf8606-153b-4f26-93b2-43502a7569ef">

思源设置

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/f1f49a6e-b992-4945-b08f-6d11436b95f7">

输入 Token 后，先保存然后再列出全部列表，看看是否可以正常获取列表

<img width="685" alt="image" src="https://github.com/user-attachments/assets/f29d6419-ffc7-4a71-b180-263727e313a3">

**Comment by Kenshin** [comment]
另外，我也测试了你提到的网站，仍旧没有任何问题。

所以，建议截图看下你的配置，估计是某些设置造成的，截图越详细越好~

**Comment by 879611427** [comment]
> 另外，我也测试了你提到的网站，仍旧没有任何问题。
> 
> 所以，建议截图看下你的配置，估计是某些设置造成的，截图越详细越好~
> 
> 因为毕竟偶尔有用户提过你遇到的问题。😂

我遇上了一样的问题，思源笔记更新后不报这个错了，成另一个了，这倒是无伤大雅了，在笔记本里直接下载也可以
![image](https://github.com/user-attachments/assets/e982a70f-e69a-4ea3-9843-1d57a1909f74)

**Comment by Kenshin** [comment]
> 我遇上了一样的问题

这是图片转换错误造成的，跟 @TangQi001 提到的问题不一样。

解决方案正如你说在思源笔记中手动转换。

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 版本，增加了一些方便调试的功能。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">
安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/5591

**Comment by Kenshin** [comment]
你的问题应该 https://github.com/Kenshin/simpread/discussions/5592#discussioncomment-10155344 造成的，1.1.4 版增加了针对此情况的提示信息。

我关闭这个 Issues 了，有任何问题随时讨论~
