### ISSUE TITLE
关于标题提取失败的问题

### ISSUE THREAD

**Issue by Ravenightwing** [Kenshin/simpread#6617]
### 描述这个错误

例如：
https://egh0bww1.com/posts/2023-02-23-29-how-emacs-startup/#orgnh-4 
其中的标题不显示。

### 复现步骤

打开网页，开启阅读模式

### 操作系统

macOS

### 浏览器

Chrome 126.0.6478.128 (Official Build) (arm64)

### 发生问题的网址

 https://egh0bww1.com/posts/2023-02-23-29-how-emacs-startup/#orgnh-4

**Comment by Kenshin** [comment]
嗨，我在休假，周三确认下。

个别没有适配的网站存在这个问题。

**Comment by Kenshin** [comment]
嗨，我这边看起来没有什么问题？但也可能是问题，只是我没有 Get 到，所以需要你详细指出 😂

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/1d861873-6507-4fe2-8e23-0e95a4a50e02">

**Comment by Ravenightwing** [comment]
例如这种副标题不会被显示
<img width="927" alt="image" src="https://github.com/user-attachments/assets/4c08f7f4-0f3a-4597-942e-7b2b990960be">
<img width="1526" alt="image" src="https://github.com/user-attachments/assets/81bc33ac-9523-428d-90a3-c5ae1ae284b1">
<img width="962" alt="image" src="https://github.com/user-attachments/assets/05db086d-c908-4882-98f7-69ca027a117f">
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/515cc504-2f7e-4d1d-a4e4-8554bb6d3250">

**Comment by Kenshin** [comment]
哦 😂 这个叫「目录」

这是因为这个站没有适配，自动获取时获取的不完整造成的。

可以通过适配这个站解决，但这个站属于个人站，所以你自己适配即可，适配过程如下：

<img width="352" alt="image" src="https://github.com/user-attachments/assets/4e99aa39-1532-4ca4-96e7-c1260297393c">

下图所示高亮代码为 `<main>`

<img width="466" alt="image" src="https://github.com/user-attachments/assets/05068677-c580-404c-8b63-e5248a06fa7b">

然后保存，然后刷新当前页面，就可以自动进入阅读模式了。

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/0eafba6c-17d8-417d-8a17-5971a5596a62">

同时你会看到这个适配规则

<img width="377" alt="image" src="https://github.com/user-attachments/assets/e8dfa560-bffd-418a-8b58-175e261c3cc5">

**Comment by Kenshin** [comment]
补充下：代码段的识别应该会有不完善的地方，但这是另外的问题，同时暂时没有太好的解决方案。

**Comment by Ravenightwing** [comment]
> 补充下：代码段的识别应该会有不完善的地方，但这是另外的问题，同时暂时没有太好的解决方案。

好的 感谢！

**Comment by Kenshin** [comment]
小事情 😄

**Comment by JokeenZhang** [comment]
https://juejin.cn/post/7396325195071635494
这个也识别不了标题，大佬
![image](https://github.com/user-attachments/assets/e04797be-c025-4b9e-9011-173f9e8e33ea)
