### ISSUE TITLE
面试鸭网站适配

### ISSUE THREAD

**Issue by dong9205** [Kenshin/simpread#6620]
### 需要适配的新站

https://www.mianshiya.com/bank/1791003439968264194/question/1780933295526146049

### 有需要请描述这个站的性质

网站说明: 面试题库，里边有很多免费、付费的面试题详解. 
需求: 觉得简悦的稍后读、标注可以很方便的记录记录和查看

**Comment by Kenshin** [comment]
嗨，谢谢提交 👍

这个网站需要登录，所以我暂时没法确认。

但一般来说需要登录（以及类似付费等）形式的网站简悦是不会主动适配的，因为会有版权风险。

你可以试试 https://github.com/Kenshin/simpread/discussions/3340 能否解决？

**Comment by dong9205** [comment]
## 结论
https://github.com/Kenshin/simpread/discussions/3340 可以解决页面杂乱的问题, 但是无法解决在标记、备注问题
1. 重新高亮、删除元素: 我在动作中没有看到这个选项，在其他选项框也没有找到
2. 手动模式: 这个网站不支持选中和右击😑
3. Live Editor蛮好用的，可以编辑、删除内容. 只是因为我没有用过Zotero，所以并不能保存我编辑好的内容.

## 追问
前边提到`简悦是不会主动适配`，是指可以让网站作者怎么做适配吗?

**Comment by Kenshin** [comment]
> 重新高亮、删除元素: 我在动作中没有看到这个选项，在其他选项框也没有找到

<img width="459" alt="image" src="https://github.com/user-attachments/assets/0c627481-ea68-4476-911f-0e0d21dd4a64">

> Live Editor蛮好用的，可以编辑、删除内容. 只是因为我没有用过Zotero，所以并不能保存我编辑好的内容.

Live  Editor 与 Zotero 没有关系，所谓的「保存」是指：通过简悦的导出功能（以及导出插件）导出。

> 前边提到简悦是不会主动适配，是指可以让网站作者怎么做适配吗?

只是简悦不做，用户可以自己适配，例如 https://github.com/Kenshin/simpread/issues/6617#issuecomment-2246854621 的讨论。

**Comment by dong9205** [comment]
多谢大佬的耐心回复😀

**Comment by Kenshin** [comment]
哈，小事情。

你可以试试问问这个网站的负责人，如果不违规的话，我随时愿意为此适配。

PS：假设这个页面有比较多的交互内容的话，其实也不建议适配，因为阅读模式不建议在正文区域使用交互内容。

**Comment by dong9205** [comment]
好，我尝试联系下负责人

**Comment by dong9205** [comment]
网站负责人还是很担心`内容泄露`，因为很多资源需要开通会员后才可查看，所以还是先不做适配了吧😅
