### ISSUE TITLE
优化正文存在 <blockquote> 时生成 Markdown 时的结构

### ISSUE THREAD

**Issue by 879611427** [Kenshin/simpread#6622]
### 描述这个错误

这是我要访问的网站：https://blog.csdn.net/Spade_/article/details/108698036
我不清楚这算什么格式，阅读模式下转换还可以，导入到思源笔记格式就没有了
原页面
![image](https://github.com/user-attachments/assets/10364d5f-d639-4f9c-b641-f776296121a4)
阅读模式
![image](https://github.com/user-attachments/assets/8134a53b-1cb4-474d-af91-e958f3853162)
思源笔记中
![image](https://github.com/user-attachments/assets/c2466d08-955d-45da-95db-07278a168ba5)

### 复现步骤

1.访问网站https://blog.csdn.net/Spade_/article/details/108698036
2.右键阅读模式
3.阅读模式下
![image](https://github.com/user-attachments/assets/3681dfce-d664-40c1-afb3-b4a229094bc7)

### 操作系统

Windows10

### 浏览器

Google Chrome 版本 94.0.4606.61（正式版本） （64 位） Chrome++ 1.4.2 inside

### 发生问题的网址

https://blog.csdn.net/Spade_/article/details/108698036

**Comment by Kenshin** [comment]
嗨，这个问题跟思源笔记无关，我已记录。

好在这种情况很少发生，这个格式对应的 Markdown 语法是 `>` 你可以手动修改下。

**Comment by Kenshin** [comment]
嗨

导入到思源笔记升级到 1.1.4 解决了此问题。

1.1.4 功能
---

- `Fix`  `<sr-blockquote>` 转换错误

- `Optimize` 优化了界面，加入了 `测试 API` 与 `测试图床 API` 功能

     <img width="555" alt="image" src="https://github.com/user-attachments/assets/f5cef2c5-f571-4001-ba38-6b67836283f7">

     <img width="548" alt="image" src="https://github.com/user-attachments/assets/256288ce-5f0b-48bd-94e8-1810e55a3121">
安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/XxuF7bPTbo) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。


***

我关闭这个 Issues 了，有任何问题随时讨论。
