### ISSUE TITLE
B站视频页面我想把评论区加到高亮区域，手动框选或者选定内容为高亮都不行。

### ISSUE THREAD

**Issue by fumaye1** [Kenshin/simpread#6623]
### 描述这个错误

如题

### 复现步骤

如题

### 操作系统

windows10

### 浏览器

edge

### 发生问题的网址

https://www.bilibili.com/video/BV1af421z7WK/?spm_id_from=333.1007.tianma.4-2-12.click&vd_source=e95c2229345aab17a4620b4127a94995

**Comment by Kenshin** [comment]
嗨，简悦是阅读模式类产品，包含文本和图文的排版，而视频并不属于这个范畴。

我关闭这个 Issues 了~
