### ISSUE TITLE
GIF图片无法导入到Notion

### ISSUE THREAD

**Issue by xiyan818** [Kenshin/simpread#6624]
### 描述这个错误

你好
网址链接：https://ld246.com/article/1721054026360#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E9%93%BE%E6%8E%A5%E6%96%B9%E5%BC%8F-
使用Picgo图床，阿里云oss。
其他图片都可以导入到notion，GIF图片不行。但是在图床中又可以看到GIF图片确实已经存在阿里云oss中。
总的来说，所有图片都已经上传到Picgo中，但是无法导入到Notion。
不知道是操作问题还是其他问题？

### 复现步骤

https://ld246.com/article/1721054026360#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E9%93%BE%E6%8E%A5%E6%96%B9%E5%BC%8F-
所有图片利用Picgo导入到阿里云图床，且可以在阿里云图床中看到。
Notion中无法看到GIF图，其他图片可以。

### 操作系统

Windows10

### 浏览器

Chrome

### 发生问题的网址

https://ld246.com/article/1721054026360#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E9%93%BE%E6%8E%A5%E6%96%B9%E5%BC%8F-

**Comment by Kenshin** [comment]
我没有登录无法查看这个链接。

你试试导出 Markdown 到本地，如果 Gif 没问题（应该一定没问题 😂

所以就是 Notion 的锅，这个简悦没法控制。

**Comment by xiyan818** [comment]
感谢，导入到思源笔记中GIF可以正常显示，那应该就是Notion的问题了。

**Comment by Kenshin** [comment]
okay

Notion 对 Markdown 的支持不是太完美，从重度使用者的角度考虑，不建议用户将 Notion 当作仓储使用，它更适合 Projects 类的管理。

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
