### ISSUE TITLE
保存Notion，一直没反应，同步助手也已经开启

### ISSUE THREAD

**Issue by Lusenlan** [Kenshin/simpread#6625]
### 描述这个错误

![image](https://github.com/user-attachments/assets/6522985a-f76b-4a67-9f10-55784148455a)

### 复现步骤

1.保存
2.见图

### 操作系统

Windows

### 浏览器

Edge

### 发生问题的网址

任意网址

**Comment by Kenshin** [comment]
嗨，请使用此方案 https://github.com/Kenshin/simpread/discussions/4954
