### ISSUE TITLE
找回自己的UID

### ISSUE THREAD

**Issue by yunbukenshuo** [Kenshin/simpread#6626]
### 请描述你的建议或任何内容

UID超过三次后将无法找回，我只好来这里来找你了，不太会用github。我的邮箱是1057731460@qq.com，

**Comment by Kenshin** [comment]
高级账户在首次升级后会自动下载一个配置文件 `simpread-key-内含UID，请勿遗失.json`

再加上你提到的找回三次，所以你找下这个文件。

另外，UID 就是你的 Key 不要随便公开...

**Comment by yunbukenshuo** [comment]
我们跑出来找你不是很方便，用everything软件找不到这个文件，可能我升级了系统吧，现在不知道怎么办了，只能看看你这里还有没有办法

**Comment by Kenshin** [comment]
简悦是基于本地系统的产品，为了隐私最大化，没有密码系统，类似 1P 的概念，所以用户需要自己保存好自己的密码...

简悦的用户很多，如果每个用户都这么找我，我啥都干不了了 😂

我在休假所以不确定什么时候能使用电脑，留意下你的 Email 72 小时后如果还没有收到 Email 再联系我。
