### ISSUE TITLE
访问简悦文档中心一直显示loading界面，无法正常加载

### ISSUE THREAD

**Issue by Omnipal** [Kenshin/simpread#6629]
### 描述这个错误

你好，我访问简悦文档中心一直显示loading界面，无法正常加载，不论是下载同步助手，还是文档中心，只要地址是/docs/下的，好像都打不开。

### 复现步骤

1. 打开偏好设置
2. 点击坚果云超链接或其他同步助手相关的连接
3. 新标签页开始加载，显示loading，但就一直这样，不会再有内容了

### 操作系统

Windows 11

### 浏览器

Microsoft Edge 版本 127.0.2651.74 (正式版本) (64 位)

### 发生问题的网址

http://ksria.com/simpread/docs/

**Comment by Kenshin** [comment]
嗨，请访问 https://simpread.pro/docs 速度会更快些。
