### ISSUE TITLE
【观察者】需要适配

### ISSUE THREAD

**Issue by lightasalt** [Kenshin/simpread#663]
请打开 link ，进入阅读模式，正文中混入“观察员”特色会员广告，请完善算法过滤这部分内容。
[link](https://www.guancha.cn/politics/2020_02_17_536708.shtml)

**Comment by Kenshin** [comment]
你可以用 **重新高亮** 或者等我适配这个页面后会通知你。

**Comment by binsee** [comment]
此站点文章页已经适配过了，手动同步官方适配源即可。
此issue可关闭

**Comment by Kenshin** [comment]
@lightasalt

你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
