### ISSUE TITLE
导出失败，此功能为实验性功能，如有需求请提Issues

### ISSUE THREAD

**Issue by cyx951211** [Kenshin/simpread#6636]
### 描述这个错误

<img width="354" alt="image" src="https://github.com/user-attachments/assets/7a52e8f6-d80f-4700-8bdc-8aabbab20de5"> 

### 复现步骤

日常同步。之前是正常的

### 操作系统

mac

### 浏览器

macos12

### 发生问题的网址

任意网址

**Comment by Kenshin** [comment]
1. 详细描述出现问题的步骤（越细越好）
2. 附上出问题的 URL
3. 尤其是导出相关问题，最好附上使用什么方式导出，包括：截图 / 详细步骤等。

***

你觉得你的描述我能定位到问题吗？😂

**Comment by cyx951211** [comment]
场景是在obsidian同步过程中，在阅读模式的时候标注，就出现了这个问题，所有的网页都不行，

**Comment by Kenshin** [comment]
😂

导入到 Obsidian 有很多方案，还是没有详细说明... 所以我只能给你几个建议：

1. 导入全文好使吗？
2. 这是导入到 Obsidian 的教程，你可以对比下 https://www.yuque.com/kenshin/simpread/fr8zo5 （但我不知道你使用了哪种方案，所以这个教程并不一定适合你
3. 也可能是高级账户「掉」了，试试 https://www.yuque.com/kenshin/simpread/sw4m21
4. https://github.com/Kenshin/simpread/discussions/5601
5. 请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

如果仍无法解决，请将与 Obsidian 相关的设置都截图给我。
