### ISSUE TITLE
csdn图片保存失败，直接提示导入成功失败个数

### ISSUE THREAD

**Issue by wqddg** [Kenshin/simpread#6637]
### 描述这个错误

图片无法保存成功csdn的，但是https://sspai.com/post/69972 该网址没问题。

![image](https://github.com/user-attachments/assets/173885d9-88a3-4d89-aa2b-582620655865)

### 复现步骤

1. 打开简悦
2. 一键导入全文到notion

### 操作系统

windows

### 浏览器

edge最新浏览器

### 发生问题的网址

https://blog.csdn.net/a3562323/article/details/112788197

**Comment by Kenshin** [comment]
嗨，改用下面的方式即可

<img width="550" alt="image" src="https://github.com/user-attachments/assets/be8adb39-0b89-43cc-939b-417abf51dac5">

注意：大部分场合仍然以 **本地方案** 为准 e.g. 少数派。
