### ISSUE TITLE
请求适配behance,微信订阅号网站

### ISSUE THREAD

**Issue by PaceZhou** [Kenshin/simpread#6638]
### 需要适配的新站

https://www.behance.net/gallery/109226139/_

### 有需要请描述这个站的性质

1. 详细描述出现问题的步骤（越细越好）
    1. 我打了开https://www.behance.net/gallery/109226139/_网站
    2. 我等待网页加截完成
    3. 我使aa快键进入阅读模式,发现只有文字并没有图片,于是我esc退出阅读模式
    4. 我退出使用ss进行手动框选模式,如下图
    
![image](https://github.com/user-attachments/assets/f2892304-7c7c-4fa8-b7c8-86547beefd88)
   5. 点击对号,进行阅读模式,得如下图片
![image](https://github.com/user-attachments/assets/654869a2-a272-48cc-9384-f8d8503d4488)
      文字显示图片不显示

第二个适配网站
https://mp.weixin.qq.com/s/ZXVrTFXWIMWWhWKxMdLSFg

作者使用了类似滚动相册的组件

当我使用aa进如阅读模式是可以看到图片的
但是当我转到notion后
表现如下
![image](https://github.com/user-attachments/assets/15978328-b25a-46e3-b525-df0848b6281a)

7. 附上出问题的 URL
https://www.behance.net/gallery/109226139/_

https://mp.weixin.qq.com/s/ZXVrTFXWIMWWhWKxMdLSFg

8. 请告知是个例？还是任意 URL 均有问题
bechance.net 多数网页如此

10. 尤其是导出相关问题，最好附上使用什么方式导出，包括：截图 / 详细步骤等。
我使用notion导出插件,c图床方式导出

**Comment by Kenshin** [comment]
> https://www.behance.net/gallery/109226139/_网站

本质上 behance 这类网站对图片都有版权规则，因此简悦不会主动适配它们。

> https://mp.weixin.qq.com/s/ZXVrTFXWIMWWhWKxMdLSFg 问题

请安装 https://github.com/Kenshin/simpread/discussions/5851

**Comment by PaceZhou** [comment]
那如何做呢?工作需要哦

**Comment by Kenshin** [comment]
> 那如何做呢?工作需要哦

这个问题跟 behance （这个页面）的图片是否存在版权有关系…

如果你能证明它可以用于导出到其他服务，我就会考虑官方适配。 

😂
