### ISSUE TITLE
因开启惰性加载造成的图片不显示问题

### ISSUE THREAD

**Issue by brainyoung-com** [Kenshin/simpread#6639]
### 描述这个错误

https://understandinggroup.com/ia-theory/15-geometric-properties-of-wholeness

这个网站我禁用就会显示图片，开启就会不显示图片。
chrome 最新版 macOS, M1 Max

### 复现步骤

打开就能看到
https://understandinggroup.com/ia-theory/15-geometric-properties-of-wholeness

### 操作系统

macOS

### 浏览器

Chrome 已是最新版本 版本 127.0.6533.89（正式版本） (arm64)

### 发生问题的网址

https://understandinggroup.com/ia-theory/15-geometric-properties-of-wholeness

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/2347

**Comment by Kenshin** [comment]
补一张效果

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/2703706e-862a-44ff-b195-c27f030a84cd">

**Comment by Kenshin** [comment]
补一张效果

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/2703706e-862a-44ff-b195-c27f030a84cd">

**Comment by Kenshin** [comment]
补一张效果

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/2d6eacd3-7b5c-4aa2-8ab5-cd84d79b3b08">
