### ISSUE TITLE
注入的css样式 会影响移动端rem布局

### ISSUE THREAD

**Issue by firimar** [Kenshin/simpread#664]
在没有启用的情况下,也会注入很多script  , 下面这段代码给html的 font-size 设值,会造成移动端用rem布局的页面 ,样式错乱 .
@media (pointer: coarse)
@media only screen and (max-device-width: 1024px)
<style>
.simpread-theme-root, html {
 font-size: 80%!important; 
}

**Comment by Kenshin** [comment]
谢谢反馈，确实有这样的问题。

请告知简悦的版本以及环境。

**Comment by firimar** [comment]
简悦 v1.1.4
chrome 80.0.3987.106

**Comment by Kenshin** [comment]
这是 Chrome 版的简悦，所以在手机端访问的可能性不大。
我可以先出一个插件 **临时解决** 这个问题，但最终 Fixed 还需要升级版本才行。

插件出了后，我会在这里通知你。

***

> 在没有启用的情况下,也会注入很多script

这是正常的，因为需要使用 `content_scripts` 所以必须要有这些，如果这个页面不需要使用简悦的话，可以将其加入到 **黑名单** 中，这些 `<script>` 就自动被删除了。

**Comment by firimar** [comment]
对于普通用户来说确实是的 , 但是对于web开发者就有点一言难尽了- - , 有时需要调试自己开发的网页或是研究别人的网页, 加入黑名单确实可以解决,但是是否可以在主动启用简悦后再注入这些script呢? 只是一点小提议

**Comment by Kenshin** [comment]
> 主动启用简悦后再注入这些script呢?

这个恐怕不能，因为简悦要预先分析页面，你也可以试试 **白名单** 功能。

***

另外，作为一个前端开发者，应该尽量避免使用常用浏览器作为调试工具，即便没有简悦的问题，也无法保证你安装的其它扩展也不会污染 HTML。

有两个解决办法

- 在隐身模式禁用全部的扩展，然后调试你需要的页面；

- 安装 Edge （ 这货目前与 Chrome 没有任何区别

我就是这么做的，一切都很正常，没有出现过任意意外。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题**

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
