### ISSUE TITLE
关于 Markdown 模板辅助增强插件的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6640]
您好，请问下我在标注的模板里使用{{url}} {{title}}这两个占位符总是不能识别的原因是什么呢？
![image](https://github.com/user-attachments/assets/d3c2384c-f443-4598-9054-4372b2eb7ec2)
或者我应该怎么写代码才能实现在每个标注后面都加上文章名称以及对应的本地链接呢？
如果需要更多版本信息请随时联系我，非常感谢！

_Originally posted by @liukmg in https://github.com/Kenshin/simpread/discussions/3725#discussioncomment-10259993_

**Comment by Kenshin** [comment]
@liukmg

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

单纯的截图没有意义 😂 请把你的模板发上来...

**Comment by liukmg** [comment]
好的，如下

稍后读
# [{{title}}](<{{int_uri}}>)

## Annotations
<% if ( unread.annotations.length > 0 ) { %>
{{annotations}}
<% } %>

标注

[📌](<{{an_int_uri}}>) {{an_note}}
{{{html_format|>|{{an_html}}}}} ——[{{title}}]({{url}})

**Comment by liukmg** [comment]
好的。

稍后读

```
# [{{title}}](<{{int_uri}}>)

## Annotations
<% if ( unread.annotations.length > 0 ) { %>
{{annotations}}
<% } %>
```

标注
```

[📌](<{{an_int_uri}}>) {{an_note}}
{{{html_format|>|{{an_html}}}}} ——[{{title}}]({{url}})




```

**Comment by liukmg** [comment]
@Kenshin

**Comment by Kenshin** [comment]
你写的没问题，但你的 Markdown 模板辅助增强插件可能是旧的。


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/[HD9GmoatXd](https://simpread.ksria.cn/plugins/details/HD9GmoatXd)) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Kenshin** [comment]
附上截图

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/c4ce42c8-9bcd-495c-926a-e32f6bfd63b5">

**Comment by liukmg** [comment]
好的可以了，非常感谢！

**Comment by Kenshin** [comment]
okay 解决就好。

你的插件版本是什么时候安装的？或者是否使用了配置库方案？

**Comment by liukmg** [comment]
去年年中就装了，当时好像是没有配置库方案，自己折腾的。

**Comment by liukmg** [comment]
还是前年年中，有点忘记了。

**Comment by Kenshin** [comment]
okay 

我关闭这个 Issues 了，有任何问题随时讨论。
