### ISSUE TITLE
简悦无法全文导入notion

### ISSUE THREAD

**Issue by kunkunren** [Kenshin/simpread#6642]
### 描述这个错误

在使用基础版notion配置库之后无法正常导入全文，无论是在动作列表手动选择还是使用快捷键nt均显示稍后再试，导入标注可以正常显示

### 复现步骤

https://github.com/user-attachments/assets/a7a4099c-cf29-4e91-8a9a-0c1658bc5a2c

### 其他相关说明

还有一点很奇怪的是我每次刷新选项-服务页面，授权管理都显示需要重新获取notion page

https://github.com/user-attachments/assets/89830b9f-2f63-4cf5-a74a-cad97a01f249

### 操作系统

win10

### 浏览器

edge 127.0.2651.86 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/question/663731384

**Comment by Kenshin** [comment]
> 还有一点很奇怪的是我每次刷新选项-服务页面，授权管理都显示需要重新获取notion page

**不要使用扩展端内置的 Notion** （同样，这也说我说的第二次 😂

请仔细看下 https://github.com/Kenshin/simpread/discussions/4954 相关截图以及对应的功能。

![image](https://github.com/user-attachments/assets/829e615f-8182-4fd1-a7a4-5e51edd1fa16)

***

> 视频提到的情况

**可能是你操作的问题**，刷新页面，然后使用下图的方式

<img width="271" alt="image" src="https://github.com/user-attachments/assets/833e76e4-e98e-420b-8797-26ff9036bc5e">

如果可以正常导入，那就是你的操作问题，不要使用此方式来操作。留意 https://www.yuque.com/kenshin/simpread/odhlf2#EblFz 里面的视频操作步骤。

### 重要提示

大部分（ 99% ）以上的类似提问跟你视频中的情况一致，即：开了太多的 Tab 导致配置可能会互相覆盖。

解决方案 https://github.com/Kenshin/simpread/discussions/3768 几分钟阅读完，请确保你的浏览器环境「干净」
