### ISSUE TITLE
简悦导致BBC中文网显示空白

### ISSUE THREAD

**Issue by 0xSparks** [Kenshin/simpread#6643]
### 描述这个错误

反复开启和禁用简悦试了一下，开启后BBC中文网body部分会显示空白，禁用后就没问题了，有没有好兄弟也来复现一下看看有没有这个问题

![sparksmpc_2024-08-08_16-42-57](https://github.com/user-attachments/assets/d7dfccf1-b314-4499-81cf-cd4a1476e2b2)

### 复现步骤

1.开启简约插件
2.访问 [BBC中文网](https://www.bbc.com)
3.网站body部分显示空白

### 操作系统

Windows 11

### 浏览器

Chrome

### 发生问题的网址

https://www.bbc.com

**Comment by Kenshin** [comment]
嗨，应该是 https://github.com/Kenshin/simpread/discussions/2347 造成的，不知道是否已经找到了解决方案
