### ISSUE TITLE
授权管理中无法授权印象笔记

### ISSUE THREAD

**Issue by bytedynamic** [Kenshin/simpread#6655]
### 描述这个错误

在“授权管理”中无法授权印象笔记，浏览器后台调试报错为
`https://simpread.herokuapp.com/evernote/oauth net::ERR_TIMED_OUT`

### 复现步骤

“服务”-“授权管理”-“是否连接并授权印象笔记“，无法添加印象笔记授权，浏览器后台调试报错为
`https://simpread.herokuapp.com/evernote/oauth net::ERR_TIMED_OUT`

### 操作系统

Win10

### 浏览器

Microsoft Edge 版本 127.0.2651.98 (正式版本) (64 位)

### 发生问题的网址

extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/options/options.html#connect

**Comment by Kenshin** [comment]
嗨，这个功能暂时无法使用了，请使用更现代的仓储服务 e.g. Notion、Obsidian 等。
