### ISSUE TITLE
请教关于公式如何导出到notion的问题

### ISSUE THREAD

**Issue by WindOmega** [Kenshin/simpread#6660]
### 描述这个错误

求教对于需要导出到notion的公式，需要如何操作，我检索了帮助中心的详细说明文档，但是却并未找到相关问题，关于我的疑问其截图如下，左侧为微信公众号文章，相关链接已附在问题网址中，右侧为notion的导入文章，使用的是notion一键配置库的基础版配置，可以看到原文章的公式并未出现在notion中，插件也加载的是notion一键配置库的基础版配置中的全部插件，请问应该如何解决该问题，提前感谢您的解答！
![屏幕截图 2024-08-18 204519](https://github.com/user-attachments/assets/ede35723-0ca9-4289-9f43-0325813e01fb)

### 复现步骤

1. 使用notion一键配置库的基础版配置及插件
2. 进入阅读模式
3. 导入到notion
4. 发现文章中的公式不见了

### 操作系统

windows

### 浏览器

Chrome 已是最新版本 版本 127.0.6533.120（正式版本） （64 位）

### 发生问题的网址

https://mp.weixin.qq.com/s?chksm=c15014b7f6279da19028106b99b4be97f89c90bbc0a335e825d19decc944547a6b3c0b681066&exptype=timeline_feeds_article_socialrecall_strategy_v1_tlfeeds&ranksessionid=1723983900_1&mid=2247486815&sn=8db0ee5c4ec595921aabc7b39076b499&idx=1&__biz=MzkxNjM0NDk2Nw%3D%3D&scene=169&subscene=200&sessionid=1723983899&flutter_pos=5&clicktime=1723983906&enterid=1723983906&finder_biz_enter_id=5&ascene=56&fasttmpl_type=0&fasttmpl_fullversion=7342028-zh_CN-zip&fasttmpl_flag=0&realreporttime=1723983906927&devicetype=android-31&version=28003257&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&session_us=gh_3c9bbfc89cb0&countrycode=CN&exportkey=n_ChQIAhIQ58KHAFukOky8W2E5IMmzKRLxAQIE97dBBAEAAAAAAOfrGE21bdoAAAAOpnltbLcz9gKNyK89dVj05%2Fdyl4XsDkkqYJ2XHgRngWtGTwirJR0nvefd93MeAZRwCoQc%2FHSGz%2FTL9KFZC9z%2BJ4mrqYf6AxQiy1N%2Bt2wuhFFpwlICEQnx58INzZsOvoRwSXH66mzi%2F1tAJScqAVQrIIlprOIOBfWt%2B3D4ZcFud2ko%2Fw8sFvf4eC26%2FNT%2BZ%2Bk5ZC%2Fjns8dw0ca1r8XHdrygUh1mcmpMegVLE6HsPt4ZJFnGl5mJiTN%2FneCJa0EI7NLPITB4pKexwLNDs%2Bi%2BQe4UH0%2BI2qa0gmDu%2Bo%3D&pass_ticket=N99YNaRPmJa%2BoP%2F5hK10IyWzxk0U0tBKFoOETs7A8t1BdLrVMT%2B7Qx%2BI2BYEJmai&wx_header=3

**Comment by WindOmega** [comment]
补充，在阅读模式下是可以正常看到公式的
![image](https://github.com/user-attachments/assets/32f81017-983c-43ed-9b14-33bd182b561d)

**Comment by Kenshin** [comment]
嗨，是这样的。

公式这块比较复杂，每个产品的适配度不一样，而且公式方案也五花八门，尤其是国内的网站，所以简悦为了这个问题单独做了适配，这就是你发现在阅读模式是没问题的原因。

而笔记工具就不可能想简悦这样专门为了一些网站（或小众公式规则）做适配。

所以，无论是 Notion 还是 Obsidian 都没法显示这个链接提到的公式。
