### ISSUE TITLE
新站适配：cn.logseq.com

### ISSUE THREAD

**Issue by felix-study** [Kenshin/simpread#6665]
### 需要适配的新站

https://cn.logseq.com/t/topic/438

### 有需要请描述这个站的性质

无法解析

**Comment by Kenshin** [comment]
没有问题 😂

<img width="1815" alt="image" src="https://github.com/user-attachments/assets/f38c6a07-8bbf-45ba-a282-24c3e2da4390">

解决方案 https://simpread.ksria.cn/plugins/details/hXZJKhhrMI

PS：遇到问题建议多翻翻 https://simpread.ksria.cn/plugins 或 https://github.com/Kenshin/simpread/discussions 基本上 90% 以上的形况下你是可以找到解决方案的。

**Comment by felix-study** [comment]
好的 THKS
