### ISSUE TITLE
规则适配更新：B站专栏

### ISSUE THREAD

**Issue by solairer** [Kenshin/simpread#6667]
### 描述这个错误

https://www.bilibili.com/read/cv2922069/
在两台win11电脑上该B站专栏均无法进入阅读模式，无论是直接点击已经变为红色的简约插件图标或右键进入阅读模式都不行，且没有任何响应。试过别的B站专栏，可以进入。添加进稍后读后也无法查看。
![image](https://github.com/user-attachments/assets/651c27a4-aced-462c-88f9-c4f35eecac59)
简悦用的不是很熟，不知道有没有日志之类的东西可以用来检查错误，这个点击进入阅读模式后没有任何提示，有点无从下手。

### 复现步骤

进入https://www.bilibili.com/read/cv2922069/点击简悦图标或通过右键进入阅读模式

### 操作系统

Windows 11

### 浏览器

Microsoft Edge 版本 127.0.2651.105 (正式版本) (64 位)

### 发生问题的网址

https://www.bilibili.com/read/cv2922069/

**Comment by Kenshin** [comment]
嗨，确实如此，谢谢反馈。

因为这个站的适配规则改变造成的，修复后会在这里通知你（预计明天修复）

**Comment by Kenshin** [comment]
嗨，适配规则更新了。

更新方式，留意下图的数字，更新后请重启浏览器确保生效。

<img width="968" alt="image" src="https://github.com/user-attachments/assets/e423a688-1228-4242-8a06-bf22f4b1e8eb">

***

注意：**此适配规则仅适合阅读模式**，即通过浏览器访问 https://www.bilibili.com/read/cv2922069/ 无法解决 **提到的截图问题**。

![image](https://github.com/user-attachments/assets/28563fc0-cf05-403c-b50a-8378878d2620)

截图是另外一个问题，解决方案是需要适配：知识库，这是一站式教程 https://www.yuque.com/kenshin/simpread/wkswh7

**Comment by solairer** [comment]
非常感谢，回复的很快，问题已解决。后面这个我现在也发现了，新电脑里的知识库出了问题，再配配。总之，非常感谢。

**Comment by Kenshin** [comment]
哈，小事情。

这不算是快的了 😂 因为刚下飞机不久，否则一般适配规则的问题 24 小时以内即可解决。

> 新电脑里的知识库出了问题，再配配

okay 教程已经给你了，有任何问题随时在这里提问。

***

方便的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
