### ISSUE TITLE
掘金在阅读模式下标题获取失败

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6669]
https://juejin.cn/post/7396325195071635494

这个也识别不了标题，大佬

![image](https://github.com/user-attachments/assets/e04797be-c025-4b9e-9011-173f9e8e33ea)

_Originally posted by @JokeenZhang in https://github.com/Kenshin/simpread/issues/6617#issuecomment-2304094245_

**Comment by Kenshin** [comment]
@JokeenZhang 

我帮你新建了一个 Issues，并删除了原来位置的内容。

***

这是因为掘金的适配规则改变造成的，修复后我在这里通知你~

**Comment by Kenshin** [comment]
嗨，适配规则更新了。

更新方式，留意下图的数字，更新后请重启浏览器确保生效。

<img width="968" alt="image" src="https://github.com/user-attachments/assets/e423a688-1228-4242-8a06-bf22f4b1e8eb">

**Comment by JokeenZhang** [comment]
可以了，一如既往的好用，谢谢大佬

**Comment by Kenshin** [comment]
👍 解决就好，谢谢喜欢简悦

***

如果没有评价的话，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
