### ISSUE TITLE
使用简悦时无法使用沙拉查词，一款非常强大的查词插件。即用鼠标选中一个单词或句子时不会出现沙拉图标。 系统：win10 x64  浏览器版本：chrome最新版 80.0.3987.116  简悦版本：1.1.3

### ISSUE THREAD

**Issue by TomNotchYmk** [Kenshin/simpread#668]
**小提示**

> 简悦已经服务 70K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <http://usatoday30.usatoday.com/news/health/weightloss/2010-03-30-skinnyasianwomen30_CV_N.htm>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
请不要在标题中描述问题...  😂 

***

目前这个问题 **无解**，因为简悦为了防止 `<body>` 污染，用了一些小技巧。

你可以这样做

***

使用简悦提供的插件 - [划词翻译](https://simpread.ksria.cn/plugins/details/ohnTKVHz4a) 可以在一定程度上解决这个问题。

***

或者使用 **临时页面** 来生成一个页面，这样就可以使用划词搜索了。

***

我将关闭此 issues。  😀
