### ISSUE TITLE
关于assets + md 的使用疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#6681]
md + assets 格式导出，assets目录没有抓取网页的图片，其他功能全部正常，求解 @Kenshin

_Originally posted by @yanghuatjy in https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-10475075_

**Comment by julian20220130** [comment]
<img width="530" alt="image" src="https://github.com/user-attachments/assets/846a582c-c4b0-4fef-9b37-c1738a5093a6">
<img width="583" alt="image" src="https://github.com/user-attachments/assets/57dd8612-848e-4b7d-965c-2c1ad5882ea7">
使用导出到 obsidian 插件，设置 Assets 图床，使用 md+asset导出时遇到了如上问题，最近才出现的报错弹窗（任何带图片的网页都会出现这种情况），请问应该反馈什么报错信息，如何解决或者说需要解决吗？

**Comment by Kenshin** [comment]
@julian20220130 

按照下图所示截图给我看下

<img width="326" alt="image" src="https://github.com/user-attachments/assets/24a6e681-394f-4ffa-b137-486599709b6c">

除此之外，你可以试试：

1. 出问题的 URL 或者试试随便找了一篇文章 https://36kr.com/p/2935162870504320 能否正常使用？

2. 把（图二）的选项关闭，看看是否可以正常导入到 Obsidian

**Comment by julian20220130** [comment]
https://blog.csdn.net/apex_eixl/article/details/141232727
1. 打开如上链接后，点击导入全文到 obsidian 会出现报错，错误信息如下图（不确定截图对不对）
<img width="576" alt="image" src="https://github.com/user-attachments/assets/38be23c8-79a2-4917-8ff7-8d47c5ff1cf8">
2. 换链接的话也是一样的，如果导出全文的话则会显示报错。如果只导出标注，包括标注图片，则不会显示该错误。
3. 把图二选项关闭后可以正常导入全文到 obsidian。所以导出全文到 obsidian 的功能是没有影响的。只是md+asset遇到问题。

**Comment by Kenshin** [comment]
okay 那出问题的只在图床相关功能，我需要你把这个地方的截图全部给我看下，或者说导入到 Obsidian 的截图也给我看下。

**Comment by julian20220130** [comment]
<img width="560" alt="image" src="https://github.com/user-attachments/assets/6302b8e4-d3a5-477c-9704-1ce10960a056">
谢谢开发大大，这是错误部分的全部截图。导入到 obsidian 插件的截图需要哪部分呢？
不过就目前来说，取消勾选md+asset功能后导入全文是没问题的，所以不会太影响使用（之前没取消勾选，从未成功导出过全文 hh）

**Comment by Kenshin** [comment]
> 这是错误部分的全部截图

不是这些截图 😂 看下图所示点击 **控制台** 然后再截图

<img width="272" alt="image" src="https://github.com/user-attachments/assets/840f67de-c84d-4a29-81c3-0cb10d330053">

> 我需要你把这个地方的截图全部给我看下

我的意思是导入到 Obsidian 这个插件的选项截图给我，也就是 [这个图](https://github.com/user-attachments/assets/57dd8612-848e-4b7d-965c-2c1ad5882ea7) 相关的功能（你截取的太少了，没有看到任何有效信息。

按照我截图的方式截你的图给我看下

<img width="585" alt="image" src="https://github.com/user-attachments/assets/a65b3a2a-688a-40bf-9981-7e848a1dcb58">

另外，使用此功能也需要在同步助手设置类似的目录

<img width="675" alt="image" src="https://github.com/user-attachments/assets/d518a8a6-a814-4a7e-8e05-76ee255adb3c">

**Comment by julian20220130** [comment]
谢谢开发大大的耐心回复！不是 bug 而是自己设置的问题。经过自己捣鼓，已经差不多解决了！再次感谢

**Comment by Kenshin** [comment]
哈，解决就好。 👍 👍 👍 😄

我关闭这个 Issues 了，有任何问题仍可以随时在这里提交。

方便的话，给个五星 + 好评呗  😏  [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 以便让更多人知道 😉 😁 👍

**Comment by Kenshin** [comment]
嗨

md + assets 插件更新到了 1.2.0 增加了**自定义图片保存路径的功能**，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

同时同步助手 1.3.0 增强了对部分图片无法正常保存的问题。

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

有任何需求可以随时在这里讨论~
