### ISSUE TITLE
进入阅读模式，会直接打开“查看大图”的功能（仅此网页）

### ISSUE THREAD

**Issue by JokeenZhang** [Kenshin/simpread#6682]
### 描述这个错误

如进入 https://blog.51cto.com/u_15709472/11785758 页面，这个页面有图片不能访问，在进入阅读模式后，会触发插件“点击查看大图”直接显示错误图片。我并没有点击图片，这是默认行为
![image](https://github.com/user-attachments/assets/aa25590b-a2a3-4042-98c1-d114b796c309)

### 复现步骤

1 打开网页
2 点击阅读模式
3 触发”大图模式“

### 操作系统

win11

### 浏览器

Chrome 版本 127.0.6533.120（正式版本） （64 位）

### 发生问题的网址

https://blog.51cto.com/u_15709472/11785758

**Comment by Kenshin** [comment]
嗨，我没有复现 😂 但确实可能存在这个情况。

试试按下图设置看看能否解决？

<img width="455" alt="image" src="https://github.com/user-attachments/assets/6e047c32-2861-4da2-9b03-e4f688c55ebd">

**Comment by Kenshin** [comment]
另外，不出意外的话，应该只是这一个页面有问题吧？

**Comment by JokeenZhang** [comment]
现在不会了，感谢

**Comment by Kenshin** [comment]
okay 小事情~
