### ISSUE TITLE
语雀授权不成功

### ISSUE THREAD

**Issue by choufeng2018** [Kenshin/simpread#6684]
### 描述这个错误

开启语雀授权后跳转，然后也点了授权跳回页面了，然后右上角绿色背景文字提示，不要关闭页面，授权成功会提示，但过一会儿这段文字消失后，再回到页面操作保存到语雀，还是提示要授权。

### 复现步骤

![局部截取_20240829_165045](https://github.com/user-attachments/assets/f5cf8907-ebaa-4b6e-a47e-adfeea6fb5ad)
![局部截取_20240829_165108](https://github.com/user-attachments/assets/d21e5e06-147b-4ee8-a922-9ce968c71fc1)
![局部截取_20240829_165143](https://github.com/user-attachments/assets/ab3030ff-4c39-485e-919b-438798d81edc)
![局部截取_20240829_165229](https://github.com/user-attachments/assets/651902b4-30ed-47f6-8eac-4f5ec2a44e3d)

### 其他相关说明

1、QQ频道无人响应和交流，希望可以多多互动
2、firefox浏览器知否支持，如何安装?
3、多几个高级用户授权，是不是每一个都不能同步。

### 操作系统

windows 11

### 浏览器

chrome 129 正式版本

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
嗨

请在选项页 → 服务 → 授权管理（第三个图）里面授权，授权成功后重启浏览器。（然后确认下是否已授权上。

**Comment by choufeng2018** [comment]
哦，重启浏览器后可以了，请问咱们这个插件支持firefox吗？平时用火狐的多一些

**Comment by Kenshin** [comment]
> 哦，重启浏览器后可以了，请问咱们这个插件支持firefox吗？平时用火狐的多一些

暂时仅支持 Chromium 内核浏览器

> 发现不同的内容都会自动到同一个目录里去

指定什么目录？如果说是语雀的话，暂时仅只能导入一个文件夹

你可以将这个目录当做 Inbox 然后自行整理。我更建议这么做，因为没有二次整理的话，几乎不会再整理了… 😂
