### ISSUE TITLE
一键导出全文到NOTION时图片无法正常输出

### ISSUE THREAD

**Issue by Cyber-H** [Kenshin/simpread#6685]
### 描述这个错误

按照https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995
设置好cloudinary图床之后使用一键导出全文到NOTION能导出，但是图片显示异常，如图
<img width="743" alt="微信图片_20240829191514" src="https://github.com/user-attachments/assets/e3b294b2-b05c-4462-9376-145013629b8d">

### 复现步骤

设置好图床导出

### 操作系统

WINDOWS10

### 浏览器

chrome

### 发生问题的网址

https://sspai.com/post/91834

**Comment by Cyber-H** [comment]
重新进入插件设置，发现图床设置没生效，开启时候报错
<img width="1920" alt="222" src="https://github.com/user-attachments/assets/1ba110aa-7ee1-4ae2-92c7-bf0fa7a8c63a">

**Comment by Cyber-H** [comment]
在服务那边的notion图床已经关闭，现在来试下MAC 明天再测试下WIN

**Comment by Kenshin** [comment]
> 在服务那边的notion图床已经关闭，

位置错了…不要在选项页 → 服务 → 授权管理使用 Notion 而是插件方案（你截图就是插件方案）

**Comment by Cyber-H** [comment]
![QQ_1724944035214](https://github.com/user-attachments/assets/2c6b2b96-58ee-48be-8aaf-b1f65b92b45a)

**Comment by Kenshin** [comment]
> 图片上传走完就卡在这转圈圈，等好久没反应，

应该还是你的设置造成的。

> NOTION那边是新建了个文章，但是显示无标题，里面是空的

这是正常的「步骤」，但因为你的设置错误所以没有继续成功导入。

> 选择非“简悦”页面就提示错误

简悦的一切功能都需要在阅读模式下才能使用。

***

关于你的问题有两个解决方案：

1. https://www.yuque.com/kenshin/simpread/zx3bcz 这是详细的教程，对比下跟你的设置有什么区别？

2. 新用户的话，建议直接使用 https://www.yuque.com/kenshin/simpread/mwda8s 方案。

***

> https://github.com/Kenshin/simpread/issues/6685#issuecomment-2318018468

一个提示，这个链接对应的截图显然不是简悦官方的模板，所以：在跑通这套流程前请按照官方模板和设置。

**Comment by Cyber-H** [comment]
作者好，请问 https://www.yuque.com/kenshin/simpread/mwda8s 方案。的高级版配置文件要从哪导入呢？是从共通导入覆盖我自己的软件配置吗？谢谢~主要是找不到导入入口。

**Comment by Kenshin** [comment]
> 高级版配置文件要从哪导入呢？

https://www.yuque.com/kenshin/simpread/zuptv2#hBjVT 里面应该写的很清楚了。
