### ISSUE TITLE
飞书文档 进入阅读模式 页面乱码

### ISSUE THREAD

**Issue by Hiwoniu** [Kenshin/simpread#6690]
### 描述这个错误

按下 AA 进入页面乱码

### 复现步骤

按下 AA 进入页面乱码

### 操作系统

windows

### 浏览器

谷歌浏览器

### 发生问题的网址

飞书文档

**Comment by Kenshin** [comment]
嗨，这是预期行为 😂

飞书文档等文档类页面是不会被主动适配的，除此之外还包括：百度文库、豆丁等等。

我关闭这个 Issues 了~
