### ISSUE TITLE
插件：大聲朗讀（TTS）為何轉換過久？選擇文字：繁體中文

### ISSUE THREAD

**Issue by ccfood** [Kenshin/simpread#6695]
### 描述这个错误

要進行閱讀模式的朗讀，卻一直顯示：語音內容較大，正在轉換中...

我不是沒有等待，但已過30分鐘仍無法轉換完成？

我要朗讀繁體中文內容，字數根據統計插件：925字

### 复现步骤

1.開啟閱讀模式，為繁體中文內容，字數根據統計插件：925字
2.按下浮動視窗的朗讀按鈕
3.等待插件顯示：語音內容較大，正在轉換中...
4.超過預期等待時間：30分鐘以上

圖片中的閱讀時間可以證明我已經停留該頁面超過30分鐘，朗讀插件一直無反應

![FireShot Capture 009 - 盧秀燕頻會藍要角 傳劍指黨主席 - tw news yahoo com](https://github.com/user-attachments/assets/9071d599-8f46-4546-9147-2827ca821ff7)

### 操作系统

windows 11

### 浏览器

chrome

### 发生问题的网址

https://tw.yahoo.com/

**Comment by Kenshin** [comment]
1. 这个插件需要同步助手（插件教程上有明确说明）

2. 暂时不要调整这个插件的任何选项

3. 提供出问题的 URL 或者试试 https://sspai.com/post/69972

这个插件是没问题的，但在确保上述前两点的基础上确实不一定任何网页都可以正常使用。
