### ISSUE TITLE
希望把末尾的“全文完”去掉。看起来一点也不美观。

### ISSUE THREAD

**Issue by weioyi** [Kenshin/simpread#67]
![Albert_20170826_212700.PNG](https://i.loli.net/2017/08/26/59a177313acf9.png)

**Comment by Kenshin** [comment]
目前还未有其他人反映这个问题。
如果有多人反映的话，可以在 `选项页 → 高级定制` 加个开关，默认为显示；可以选择关闭它。

由于 1.0.3 已经进入 release 阶段，所以功能冻结了。

**Comment by Kenshin** [comment]
额，其实还有一个更好的解决办法，`1.0.2` 增加了 自定义样式的功能，你可以把任何你认为不满意的地方进行修改，如图：
![image](https://user-images.githubusercontent.com/81074/29756002-7c2ad050-8bd2-11e7-8bf4-8132216671a1.png)

**Comment by ImHUan** [comment]
![qq20170828-142405](https://user-images.githubusercontent.com/385914/29761602-96b516a4-8bfc-11e7-9af6-7011a0608a5d.jpg)

简单设计了一个，是不是这样就可以既不用去掉，也不会干扰大家的阅读注意力呢？

**Comment by Kenshin** [comment]
@ImHUan 
~不错的设计 👍 

不过目前 `简悦` 支持的是中文，所以最好用中文；这个设计可以放到 `多语言版本` 时使用。

- 上面的 end 需要做成 png 才行，否则字体不支持。
- 下面的那行，虽然挺美观，但做成图片似乎不太好，否则字体样式也无法应用；最好跟文章页的字体一致；

**Comment by ImHUan** [comment]
@Kenshin 
![2017-08-29 14 53 32](https://user-images.githubusercontent.com/385914/29808243-da7fdd6a-8cc9-11e7-9c90-0eea1a7e4be5.png)
![2017-08-29 14 50 59](https://user-images.githubusercontent.com/385914/29808244-da8275f2-8cc9-11e7-9ff2-6a6b0dae1b3e.png)

哈，你的建议也不错，我按建议又设计了。希望能帮上忙。

**Comment by Kenshin** [comment]
@ImHUan 
不错哦，等发英文版时一并加上~

**Comment by Kenshin** [comment]
@weioyi 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

你可以使用 `自定义样式` 来去掉 footer，关于自定义样式的说明请看 [自定义样式](https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F#%E7%AE%80%E6%82%A6-html-%E6%A0%87%E7%AD%BE%E8%AF%B4%E6%98%8E)

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题，此 issues 关闭。

![](https://i.imgur.com/ezmWhOE.png)

同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
