### ISSUE TITLE
建议公众号在进入阅读模式后显示原始图片（而非默认压缩图片）

### ISSUE THREAD

**Issue by Mr-WiFi** [Kenshin/simpread#6701]
### 请描述你的建议或任何内容

通过简悦导入微信文章到notion中时，导入的文章图片不是原始高清图片，例如以这一篇文章为例https://mp.weixin.qq.com/s/MllsPabLaBxuIXlmOSDq1w ，在微信客户端中浏览最后一张图片时为高清原图，但是通过从浏览器打开后默认的图片链接会被降低分辨率如下https://mmbiz.qpic.cn/mmbiz_png/IXOicg347dAjEdfxCltfeNHEry3iaj6RQEsFDlDPrFOpg2CKlBIQ7pAopG7gcT7qtfPkBmumTpYDP243ghicQCSqA/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1&tp=webp ，而原始的图片链接应该是https://mmbiz.qpic.cn/mmbiz_png/IXOicg347dAjEdfxCltfeNHEry3iaj6RQEsFDlDPrFOpg2CKlBIQ7pAopG7gcT7qtfPkBmumTpYDP243ghicQCSqA/ 

因此通过浏览器的简悦插件进行文章剪藏的时候保存到图床的图片也会变成被降低分辨率的图片，所以希望能够修改保存微信图片的规则，让保存到图床的图片为高清图片。

**Comment by Kenshin** [comment]
okay 

这个问题可以通过升级 [微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 解决。

不过，我不知道任意公众号的图片都是这样的？需要调查下。

升级后会在这里通知你。

**Comment by Kenshin** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/6bb164bf-f86d-4c79-a982-f8abc885bf9b" /></p>

嗨，[微信公众号辅助增强](https://github.com/Kenshin/simpread/discussions/5851) 升级到 **2.0.0 版**

增加了显示原图的功能。

<img width="456" alt="image" src="https://github.com/user-attachments/assets/bfc2e5cc-a3c1-4881-976c-0888363a2a87">

***

> 除此之外，2.0.0 版还包括如下优化和功能：

### 2.0.0 版功能

- `Add` 显示原图

- `Add` 图片居中显示

- `Add` 可识别 翻页与目录

- `Optimize` 当使用强制模式时，图片居中设置

- `Optimize` 小红书布局方案，使其更易于阅读

- `Optimize` 去除不易于导出的内容，如：视频、音频、小程序、公众号推荐等

- `Optimize` 优化选项卡 UI 到 2.0 版

### 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/N3EznnUXeV) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

另外，也确保你的适配规则为最新，选项页 → 站点管理，然后按照下图所示更新

<img width="899" alt="image" src="https://github.com/Kenshin/simpread/assets/81074/5b6a1ab3-94a1-4ff1-b663-f68f931968e6">

按照并更新完请重启浏览器确保 100% 生效~

### 关联 

https://github.com/Kenshin/simpread/issues/5852

***

我关闭此 Issues 了，如有任何疑问仍可以继续在这里讨论~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
