### ISSUE TITLE
b站的笔记导出出现问题，b站的记笔记，直接导入obision错误

### ISSUE THREAD

**Issue by hcm0621** [Kenshin/simpread#6703]
### 描述这个错误

![image](https://github.com/user-attachments/assets/519807d2-53ab-45f9-95b5-39092dda8778)

安全性  
3
Ensure credentialed requests are not sent to CORS resources with origin wildcards
错误  
2
Response should include 'x-content-type-options' header.
错误  
辅助功能  
1
ARIA attributes must conform to valid names: Invalid ARIA attribute name: aria-description
错误  
6
Buttons must have discernible text: Element has no title attribute
错误  
1
Form elements must have labels: Element has no title attribute Element has an empty placeholder attribute
错误  
13
Form elements must have labels: Element has no title attribute Element has no placeholder attribute
错误  
7
Images must have alternate text: Element has no title attribute
错误  
3
Select element must have an accessible name: Element has no title attribute
错误  
兼容性  
1
'-webkit-mask-image' is not supported by Firefox. Add 'mask-image' to support Firefox 53+.
错误  
1
'-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+.
错误  
￼
1
A 'viewport' meta element was not specified.

### 复现步骤

![image](https://github.com/user-attachments/assets/f9a52204-0f0f-4046-a2ae-bdec1dd43907)
![Uploading 屏幕截图 2024-09-12 191937.png…]()

### 其他相关说明

![image](https://github.com/user-attachments/assets/e7f105b5-d8bc-4c8f-b128-a57e805273a2)

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://space.bilibili.com/v/note-list#%E9%BB%91%E9%A9%AC%E7%A8%8B%E5%BA%8F%E5%91%98%20-%20Linux%20%E7%B3%BB%E7%BB%9F%E7%BC%96%E7%A8%8B%20%20%20%20%20%20%20%20%20%20%20%20%20%E8%AF%B4%E4%B8%80%E4%B8%8B%E5%9C%A8%20Linux%20%E4%B8%8A%E5%86%99%E4%BB%A3%E7%A0%81%E7%9A%84%E5%85%A5%E9%97%A8%E7%9F%A5%E8%AF%86

**Comment by Kenshin** [comment]
嗨，我这边没问题，留意下图

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/43f2fd5d-bd29-4af4-920a-072ba7c195a4">

留意你的 Obsidain 左侧是否跟截图一样（黄框），如果不一样需要升级你的 Obsidian 插件。


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/1VQ19jCD8Z) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

**Comment by Kenshin** [comment]
除了这个 Issues（ #6703 ）还有 #6704 #6705 是否解决了？解决的话，请 Close 这个 issues ~

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
