### ISSUE TITLE
我发现自己未发布的b站笔记，用导出全文到obision图片会失效！

### ISSUE THREAD

**Issue by hcm0621** [Kenshin/simpread#6705]
### 描述这个错误

很奇怪！自己未发布的笔记导出全文图片打不开！但是已经发布的，是可以打开的！
![image](https://github.com/user-attachments/assets/5ed4bb28-cac1-4b32-ba5d-8950028ace0f)
![image](https://github.com/user-attachments/assets/1825c214-1c47-4dd3-8ffa-c6b8e9c5c7ff)

### 复现步骤

这个是一个bug

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://space.bilibili.com/v/note-list#%E9%BB%91%E9%A9%AC%E7%A8%8B%E5%BA%8F%E5%91%98%20-%20Linux%20%E7%B3%BB%E7%BB%9F%E7%BC%96%E7%A8%8B%20%20%20%20%20%20%20%20%20%20%20%20%20%E8%AF%B4%E4%B8%80%E4%B8%8B%E5%9C%A8%20Linux%20%E4%B8%8A%E5%86%99%E4%BB%A3%E7%A0%81%E7%9A%84%E5%85%A5%E9%97%A8%E7%9F%A5%E8%AF%86

**Comment by Kenshin** [comment]
> 自己未发布的笔记导出全文图片打不开！但是已经发布的，是可以打开的！

这是正常到… 但你使用 assets 图床方案的话，就能解决这个问题。

***

你这几个 Issues 基本上都是一个问题，无需重复建立 Issues 直接在 #6703 讨论就行
