### ISSUE TITLE
语雀无法导出到思源笔记（个例）

### ISSUE THREAD

**Issue by 879611427** [Kenshin/simpread#6706]
### 描述这个错误

语雀无法导出到思源笔记

### 复现步骤

右键阅读模式排版就是错误的，导出后也是乱的

### 操作系统

Windows

### 浏览器

chrome 版本 128.0.6613.121（正式版本）

### 发生问题的网址

https://www.yuque.com/aceld/lfhu8y/hv3rqf

**Comment by Kenshin** [comment]
嗨

首先，你需要安装 https://github.com/Kenshin/simpread/discussions/4380 这个插件

其次，并不是每个语雀页面都能 100% 转换为阅读模式的，比如你提到的页面，但 e.g. https://www.yuque.com/kenshin/simpread/ifioux 是没问题的。

语雀的页面都比较特别，里面有不少无法转换为阅读模式的干扰元素，所以没有特别好的解决方案。

建议：

1. 测试不同的页面 e.g  https://sspai.com/post/69972 用来排除是否是插件设置造成的干扰。
2. 测试其它的语雀页面 e.g https://www.yuque.com/kenshin/simpread/ifioux

如果上述没问题，说明设置无误，仅此这个页面而已。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
