### ISSUE TITLE
wkhtm下载的bin目录的文件不可以执行

### ISSUE THREAD

**Issue by hcm0621** [Kenshin/simpread#6707]
### 描述这个错误

![image](https://github.com/user-attachments/assets/3659b882-3f43-446e-8d9b-0753e1a3072f)

### 复现步骤

![image](https://github.com/user-attachments/assets/7517eb13-6afa-4bf3-a315-6f4d2da16b24)

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

无

**Comment by hcm0621** [comment]
防火墙也关闭了，版本也没有选错，但是就这样，然后去命令行也显示不出来版本

**Comment by Kenshin** [comment]
这不是简悦的问题 😂

不过，建议你截图看下 

> 去命令行也显示不出来版本

具体提示什么信息？

**Comment by hcm0621** [comment]
> 这不是简悦的问题 😂
> 
> 不过，建议你截图看下
> 
> > 去命令行也显示不出来版本
> 
> 具体提示什么信息？

系统提示“系统找不到指定的路径”
![image](https://github.com/user-attachments/assets/e34de387-807f-4e0f-81b3-f4d786cee960)
![image](https://github.com/user-attachments/assets/aad1889c-8ca8-418c-9ca1-3cf4026d9790)

**Comment by Kenshin** [comment]
建议这种问题，通过 Google 或者某些 AI 咨询下 😂

<img width="755" alt="image" src="https://github.com/user-attachments/assets/455222bd-571a-4177-bdce-e05f1265aeb2">

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
