### ISSUE TITLE
chrome  128.0.6613.138 无法直接进入稍后读

### ISSUE THREAD

**Issue by WhyWhatHow** [Kenshin/simpread#6708]
### 描述这个错误

1. `chrome 128.0.6613.138 `点击打开稍后读, 跳转到` chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#later`
而不是`**/main.html` 
同理,测试了 `edge beta` 浏览器,正常跳转到`extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/unreader/main.html`

### 复现步骤

1. `chrome 128.0.6613.138 `点击打开稍后读, 跳转到` chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#later`
而不是`**/main.html` 
同理,测试了 `edge beta` 浏览器,正常跳转到`extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/unreader/main.html`

### 其他相关说明

貌似新版的chrome,好像与这个插件的不兼容度有点高/doge

### 操作系统

windows10

### 浏览器

chrome 128.0.6613.138

### 发生问题的网址

any website

**Comment by Kenshin** [comment]
嗨

这个问题跟 **浏览器版本没关系** 😂 是跟你的设置有关系... 

试试下面的方式

<img width="250" alt="image" src="https://github.com/user-attachments/assets/e0fc4040-8e81-4e8d-9907-bd02664e2941">

然后打开选项页 → 高级设置 → 稍后读，看下图所示的设置是否跟你一致？

<img width="1701" alt="image" src="https://github.com/user-attachments/assets/93dc03e8-d07e-43b0-a7a4-d8d1793a4ea7">

***

PS：Chrome 与 Edge 确实在版本兼容性上出现了差异...

**Comment by Kenshin** [comment]
不过...

> 点击打开稍后读

具体是在哪里点击？建议截图给我看下。

**Comment by WhyWhatHow** [comment]
sry, 浪费你的时间了,抱歉,我的问题.

**Comment by WhyWhatHow** [comment]
> sry, 浪费你的时间了,抱歉,我的问题.

- reason: 简单模式

**Comment by Kenshin** [comment]
> sry, 浪费你的时间了,抱歉,我的问题.

哈，小事情 😂 你不是第一个，也永远不是最后一个  😏  🌚 

***

要真是「过意不去」的话，请帮忙给个 五星 + 好评吧~ [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 

以便让更多人知道 😉 😁 👍

**Comment by WhyWhatHow** [comment]
> > sry, 浪费你的时间了,抱歉,我的问题.
> 
> 哈，小事情 😂 你不是第一个，也永远不是最后一个 😏 🌚
> 
> 要真是「过意不去」的话，请帮忙给个 五星 + 好评吧~ [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)
> 
> 以便让更多人知道 😉 😁 👍

already did it.
