### ISSUE TITLE
Chrome浏览器进入阅读模式，退出后网页缩小的问题

### ISSUE THREAD

**Issue by crazyetiii** [Kenshin/simpread#6709]
### 描述这个错误

环境：
Chrome：128.0.6613.121（正式版本） （64 位）
系统：win10 版本22H2（操作系统内部版本 19045.4894）专业版

问题1：
网页右键进入阅读模式和使用快捷键aa进入阅读模式，两者的工具栏不一致！

问题2：
使用aa的方式进入阅读模式，点击设置按钮一次，然后使用Esc按键退出阅读模式，网页界面缩小了，此时网页的百分比还是100%，此时需要重新加载网页恢复正常。

### 复现步骤

![右键菜单进入和快捷键进入阅读模式的区别和网页会缩小的问题](https://github.com/user-attachments/assets/2d1b6481-c6b5-4ffa-aea5-b9704210d815)

### 操作系统

Win10

### 浏览器

Chrome：128.0.6613.121（正式版本） （64 位）

### 发生问题的网址

https://www.hello-algo.com/chapter_introduction/algorithms_are_everywhere/

**Comment by Kenshin** [comment]
> 问题1 & 问题2

我没有遇到 😂 

1. 请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

2. 其它页面是否也存在这个情况 e.g https://sspai.com/post/69972 如果没问题的话，估计只是个例而已。

**Comment by crazyetiii** [comment]
访问这个网址 https://sspai.com/post/69972 ,右键进入阅读模式,提示配置文件已更新，如下图

刷新页面还是会提示！！

![image](https://github.com/user-attachments/assets/230ad4aa-2980-42e5-b626-5e914400d151)

**Comment by crazyetiii** [comment]
> 访问这个网址 https://sspai.com/post/69972 ,右键进入阅读模式,提示配置文件已更新，如下图
> 
> 刷新页面还是会提示！！
> 
> ![image](https://private-user-images.githubusercontent.com/50905019/367484259-230ad4aa-2980-42e5-b626-5e914400d151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODQzMTIsIm5iZiI6MTcyNjI4NDAxMiwicGF0aCI6Ii81MDkwNTAxOS8zNjc0ODQyNTktMjMwYWQ0YWEtMjk4MC00MmU1LWI2MjYtNWU5MTQ0MDBkMTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAzMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjY2FiYTFiZDM3ZGMyOGMzOTkwMGY4MzgyZGNkNTdkZTg1ZmM2MDJlNzk3MzYxZGI5MDlmMzk4ZmFlNGZhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJAL62O1Stzp7xEJ1KZupHdV6kPYxEoLFVfeZRYW2Xo)

我把其他插件都关闭了，只留了简悦

**Comment by Kenshin** [comment]
这个提示是因为

> 同样的 URL 多开造成的

解决方案：

1. 关闭多开的 Tab
2. 重启浏览器（首选）

如果你在调整配置项的话，请看下 https://github.com/Kenshin/simpread/discussions/3768 提到的**最佳调整建议。**

**Comment by crazyetiii** [comment]
> 这个提示是因为
> 
> > 同样的 URL 多开造成的
> 
> 解决方案：
> 
> 1. 关闭多开的 Tab
> 2. 重启浏览器（首选）
> 
> 如果你在调整配置项的话，请看下 #3768 提到的**最佳调整建议。**

重启浏览器好了。

问题1 我重装了下浏览器，重装了简悦插件，同时使用了“重置当前配置文件”功能，复现不到了。
问题2 没有不正常的工具栏，也复现不到缩小的问题了

我调整的时候没有控制单一变量，所以现在不太清楚是哪个步骤导致的问题。

如果其他朋友不幸遇到这个问题，可以按照以下顺序排查。要记得每改动一次，复现下现象，可以追下到底是哪个修复的问题。
1. “重置当前配置文件”
2. 重装了简悦插件
3. 重装了下浏览器

**Comment by Kenshin** [comment]
> https://github.com/Kenshin/simpread/issues/6709#issuecomment-2350809951

这个问题就是 **同样的 URL 多开造成的** （没有其它可能性 😂

> 退出后网页缩小的问题

至于此问题，既然没有在稳定复现，可以忽略~

**Comment by crazyetiii** [comment]
好的，辛苦作者大大回复！
祝越来越好！

**Comment by Kenshin** [comment]
小事情 😄 谢谢喜欢简悦~

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
