### ISSUE TITLE
镜像gpt网站，我发现这个打印功能预览的页面会少很多！gpt网站也一样有问题

### ISSUE THREAD

**Issue by hcm0621** [Kenshin/simpread#6710]
### 描述这个错误

![image](https://github.com/user-attachments/assets/14620b5d-57e4-49c2-8a6a-1c4e9b01fb4c)
后面还有很多聊天的内容，全部没有预览到，手动框选，选了也还是很多没用

### 复现步骤

![image](https://github.com/user-attachments/assets/5df6535b-7f22-4b15-94ef-beefbd8bac68)
只预览了一句话甚至格式都变了

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://as.4933ai.vip/

**Comment by Kenshin** [comment]
如果是 ChatGPT 的话，请使用 https://github.com/Kenshin/simpread/discussions/4933

但应该不支持镜像站。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
