### ISSUE TITLE
導出.md文件後顯示找不到檔案

### ISSUE THREAD

**Issue by FuZhi-Sun** [Kenshin/simpread#6711]
### 描述这个错误

<img width="405" alt="屏幕截图 2024-09-13 234028" src="https://github.com/user-attachments/assets/99b663c5-5399-4213-b09c-03f56b06feb5">
導出成功後打開obsidian，顯示爲找不到檔案。

### 复现步骤

1.進入界面後"aa"進入閱讀模式；
2.動作-插件觸發器-導入到Obsidian選項；
3.點擊“導出”；
4.右上角彈出“已經保存到Obsidian，是否打開”，點“打開”；
5.進入Obsidian顯示找不到檔案；

### 其他相关说明

Obsidian版本爲v1.6.7;
“dd”後output中.md文件可以拖放到Obsidian

### 操作系统

Windows

### 浏览器

Edge 128.0.2739.67 

### 发生问题的网址

https://imageslr.com/2021/vim.html

**Comment by Kenshin** [comment]
嗨

一般情况这个问题跟你设置的路径有关系。

简悦支持多种导入到 Obsidian 方案，但你并没有说清楚，建议截图给我看下，我只能按照通常情况给你截图参考。


<img width="609" alt="image" src="https://github.com/user-attachments/assets/cb92db5e-5058-45f8-a94e-460383ecbcd7">

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/cc603c48-9ffd-41eb-baa2-d1b9544c42e7">

**Comment by FuZhi-Sun** [comment]
Customize base folder默認沒改……改了後好了。

**Comment by Kenshin** [comment]
okay 解决就好 👍
