### ISSUE TITLE
使用同步助手导出epub经常失败

### ISSUE THREAD

**Issue by Diplproveably** [Kenshin/simpread#6712]
### 描述这个错误

使用同步助手导出epub经常失败

### 复现步骤

1. 打开https://pubs.rsc.org/en/content/articlehtml/2016/cs/c6cs00061d
2. 进入阅读模式
3. 导出为epub

### 其他相关说明

pandoc版本：3.4
报错日志：
[2024-09-16 11:04:46.397] ERROR (on DIO-HO-laptop): write: C:\Users\32855\OneDrive\app_config\SimRead\output\Molecularimprinting-perspectivesandapplications-ChemicalSocietyReviews(RSCPublishing)DOI-10.1039-C6CS00061D.epub 
    error: {
      "killed": false,
      "code": 64,
      "signal": null,
      "cmd": "pandoc \"C:\\Users\\32855\\OneDrive\\app_config\\SimRead\\output\\.tmp_Molecularimprinting-perspectivesandapplications-ChemicalSocietyReviews(RSCPublishing)DOI-10.1039-C6CS00061D.md\" -o \"C:\\Users\\32855\\OneDrive\\app_config\\SimRead\\output\\Molecularimprinting-perspectivesandapplications-ChemicalSocietyReviews(RSCPublishing)DOI-10.1039-C6CS00061D.epub\""
    }

### 操作系统

版本	Windows 11 家庭中文版 版本号	23H2 安装日期	‎2024/‎4/‎18 操作系统版本	22631.4169 体验	Windows Feature Experience Pack 1000.22700.1034.0

### 浏览器

版本 128.0.2739.79 (正式版本) (64 位)

### 发生问题的网址

https://pubs.rsc.org/en/content/articlehtml/2016/cs/c6cs00061d

**Comment by Diplproveably** [comment]
导出md之后用typora导出成epub可以导出

**Comment by Kenshin** [comment]
其它页面 e.g. https://36kr.com/p/2950951598366856 （随便找的）可以成功吗？

如果任意页面都失败的话，说明是 `pandoc` 设置错误造成的，你可以设置下 [日志](http://ksria.com/simpread/docs/#/Sync?id=%E6%97%A5%E5%BF%97) 看看导出时发生了什么。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
