### ISSUE TITLE
关于obsidian配置库问题

### ISSUE THREAD

**Issue by visionqiu** [Kenshin/simpread#6713]
### 请描述你的建议或任何内容

按照官方教程，我成功配置了obsidian极速版配置库，但是，这是在obsidian添加了全新的库，怎么把obsidian极速版配置库整合到我原有的obsidian库？谢谢。

**Comment by Kenshin** [comment]
https://www.yuque.com/kenshin/simpread/xkuecp#uIjbn

每个配置库的教程都有说明。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
