### ISSUE TITLE
utgd网站适配

### ISSUE THREAD

**Issue by f1ooow** [Kenshin/simpread#6715]
### 需要适配的新站

https://utgd.net/article/20806

### 有需要请描述这个站的性质

关于科技、生产力

**Comment by Kenshin** [comment]
嗨，这个站已经适配过了，细节 https://github.com/Kenshin/simpread/issues/6533#issuecomment-2154085575

**Comment by f1ooow** [comment]
> 嗨，这个站已经适配过了，细节 [#6533 (comment)](https://github.com/Kenshin/simpread/issues/6533#issuecomment-2154085575)

了解，感谢回复

**Comment by Kenshin** [comment]
小事情，解决就好 😄
