### ISSUE TITLE
找回UID。

### ISSUE THREAD

**Issue by qinyuchu999** [Kenshin/simpread#6717]
### 描述这个错误

作者你好，很抱歉打扰。
由于已经找回了三次UID失效，通过找回平台邮件找回报错无法跳转，请问可以在Github留一下邮箱地址么？
感谢。

### 复现步骤

无。

### 操作系统

Win 11

### 浏览器

Chrome

### 发生问题的网址

https://github.com/Kenshin/simpread/issues/new?assignees=&labels=&projects=&template=bug_report.yaml

**Comment by Kenshin** [comment]
嗨

请把你的 License 发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6717

然后在这里告诉我~
