### ISSUE TITLE
在标注时，浮动标注栏的显示方式选择 "鼠标点击后显示"的时候， Lightbox( 点击查看大图 ) 不可用，会继续无解吗？

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#6718]
### 请描述你的建议或任何内容

<img width="827" alt="image" src="https://github.com/user-attachments/assets/80f00046-143c-439d-9437-d439e892b33a">

如题，虽知是在 "已存在标注" 同时存在才会有 Lightbox不可用。个人习惯是浮动标注栏的显示方式为 "鼠标点击后显示"最舒服，一直未见有提及通过插件更新会改变，故想知道这个情况是无解吗？

**Comment by Kenshin** [comment]
嗨，你的这个问题可以通过下面的方式解决

<img width="464" alt="image" src="https://github.com/user-attachments/assets/e37cbdb4-8377-434f-a39c-13d89ff3aa9a">

顺便我升级了 Lightbox Gallery 到 2.0.0 版

### 升级内容

- `Add` 鼠标滚轮放大/缩小图片

- `Optimize` 选项卡升级到 UI 2.0 方案

- `Fix` 图片监控行为（使用 [稍后读辅助增强插件](https://github.com/Kenshin/simpread/discussions/5943) 会导致此插件失效，新版解决了此问题）

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VQOZdNET2d) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。


关联
---

https://github.com/Kenshin/simpread/issues/825

***

我关闭这个 Issues 了，有任何疑问随时沟通~

**Comment by Kenshin** [comment]
留意下：

https://simpread.ksria.cn/plugins/details/VQOZdNET2d 已废弃，最新插件地址 https://simpread.ksria.cn/plugins/details/TmZSYtz5lA
