### ISSUE TITLE
能否在新edge浏览器里上架

### ISSUE THREAD

**Issue by lizhendong128** [Kenshin/simpread#672]
新的edge浏览器使用了谷歌内核，使用起来也不错。
希望可以在edge商店上架，那就很完美啦

**Comment by Kenshin** [comment]
谢谢反馈，会考虑上架。

另外，你可以在 Edge 上直接安装 Chrome Webstore 的。

**Comment by Kenshin** [comment]
嗨，抱歉，请不要关闭这个 issues 如果上架后我会再关闭它。

**Comment by lizhendong128** [comment]
上线了，666

**Comment by Kenshin** [comment]
必须地，我关闭这个 issues ~
