### ISSUE TITLE
适配 Linux Do或者 Discourse框架类的网站

### ISSUE THREAD

**Issue by lixiaodong007** [Kenshin/simpread#6722]
### 需要适配的新站

https://linux.do/

### 有需要请描述这个站的性质

社区论坛

**Comment by Kenshin** [comment]
嗨，你可以试试这个插件 https://github.com/Kenshin/simpread/discussions/5428

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/bdd56d4f-4521-46f3-982c-59e8d3144ef7">

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
