### ISSUE TITLE
将图片以assets形式保存到Obsidian失败

### ISSUE THREAD

**Issue by Hancisse** [Kenshin/simpread#6723]
### 描述这个错误

在知乎文章界面使用导入到obsidian，出错
![image](https://github.com/user-attachments/assets/ab4d54af-c145-4ba0-b214-2f9fca411940)

### 复现步骤

在知乎文章界面使用导入到obsidian，出错
![image](https://github.com/user-attachments/assets/ab4d54af-c145-4ba0-b214-2f9fca411940)

### 操作系统

windows

### 浏览器

Microsoft Edge 版本 129.0.2792.52 (正式版本) (64 位)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/108053853

**Comment by Hancisse** [comment]
几次尝试之后，出现了新的报错
![image](https://github.com/user-attachments/assets/ac01645b-91ce-4262-b052-beee4ccdcd7b)

**Comment by Kenshin** [comment]
嗨，我这边没问题 https://github.com/Kenshin/simpread/issues/6723#issuecomment-2377356729 的报错跟你的问题无关。

试试改为下面的选项

<img width="520" alt="image" src="https://github.com/user-attachments/assets/e6ba86c2-7fba-4d42-a781-8ba6ee728a25">

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
