### ISSUE TITLE
obsidian 的导入功能优化（在全文中支持标注）

### ISSUE THREAD

**Issue by suiyun08** [Kenshin/simpread#6725]
### 请描述你的建议或任何内容

obsidian 的导入功能是否能支持把备注和原文导入到一个文件中，而且是用markdown 标准的语法，这样使用起来更加方便，毕竟日常以阅读文本内容为主。

**Comment by Kenshin** [comment]
嗨~

我也想 😂 等 Markdown 加入了标注的标注语法简悦会第一个适配。

所以，问题不是简悦不支持，而是 Markdown 并不支持这种形式。

虽然 Obsidian 可以识别 HTML，所以我可以实现在：Markdown 混合 HTML 的方式，但这种方式仅对 Obsidian 可用，并不是标准的 Markdown 语法。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
