### ISSUE TITLE
简悦插件在谷歌浏览器下，打开掘金的文章，使用插件会没有标题，在 edge浏览器下没有这个问题。

### ISSUE THREAD

**Issue by realSummer** [Kenshin/simpread#6726]
### 描述这个错误

 1. 简悦插件在谷歌浏览器下，打开掘金的文章，使用插件会没有标题，在 edge浏览器下没有这个问题。

### 复现步骤

打开这个地址  
https://juejin.cn/post/7380185173689204746
使用简悦的插件

### 操作系统

macOS 15 

### 浏览器

谷歌版本 129.0.6668.70（正式版本） (arm64)

### 发生问题的网址

https://juejin.cn/post/7380185173689204746

**Comment by Kenshin** [comment]
嗨，这个规则改变造成的，我已经修复了。

选项页 → 站点管理，按照下图所示更新。

<img width="997" alt="image" src="https://github.com/user-attachments/assets/d964b0ee-4bbd-4ed2-8575-e2b38151f1cb">

更新后重启浏览器，然后再试试，留意下图所示

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/3842eadb-a8e0-436f-be2f-113733c0feba">

至于 Edge 的话，我不知道是如何好用的 😂 但只要确保上述情况就一定没问题。

**Comment by realSummer** [comment]
感谢
