### ISSUE TITLE
PDF生成异常

### ISSUE THREAD

**Issue by wanwuhuisu** [Kenshin/simpread#6728]
### 描述这个错误

PDF生成时，会把优化的格式也输出出来。
(https://github.com/user-attachments/assets/899a6a0f-9285-490d-972e-4e7be33ebe8c)

### 复现步骤

打开CSDN文章，开启阅读模式，通过同步助手导出PDF

### 操作系统

WINDOWS11

### 浏览器

EDGE

### 发生问题的网址

csdn

**Comment by Kenshin** [comment]
okay 明天确认下。

其他网站是否有这个问题？

**Comment by Kenshin** [comment]
我这边测试没问题，我随机找了个 CSDN 的页面 https://blog.csdn.net/dQCFKyQDXYm3F8rB0/article/details/142550453?spm=1000.2115.3001.5927

使用的 PDF 方案为 PDF [高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)

<img width="783" alt="image" src="https://github.com/user-attachments/assets/81d79f22-fe0e-44e6-a5ff-24fbc784e6de">

所以：

1. 请告知具体出问题的 URL 以及你的 PDF 导出方案

2. 请在请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

3. 试试其它网站是否也有同样的问题。

**Comment by wanwuhuisu** [comment]
好的，我今天测试也没有了，可能只是那天异常了

**Comment by Kenshin** [comment]
okay 没问题就好。

**Comment by qiuxiaomu** [comment]
我想在我开新issue之前借这里先问一下, 使用同步助手的导出功能, 或者任何功能, 都需要有坚果云吗? 我最近出现了pdf无法到处的问题.
