### ISSUE TITLE
推荐使用shadow DOM屏蔽掉外面的样式，不然很多网页的字体无法设置。

### ISSUE THREAD

**Issue by luckyliaolei** [Kenshin/simpread#673]
很多网站在p, h标签上设置了字体，比如csdn，导致自定义的字体无效，所以我认为可以使用shadow DOM技术使得插件和网页的样式之间可以互不干扰，谢谢。

**Comment by Kenshin** [comment]
谢谢建议。

CSDN 在标签上加 `style="xxxx"` 的行为是不对的，简悦做的目的就是去除这些 **不对且不标准** 的方式，自定义字体也是同样的道理。

当然，你可以在简悦中更改字体。同时，你也可以关闭简悦的 **词法分析引擎** 位置在 选项页 → 高级设定 → 词法分析引擎。

`Shadow DOM` 会考虑，但目前的技术架构不适合做这些。 😀
