### ISSUE TITLE
Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑

### ISSUE THREAD

**Issue by mdsnalw** [Kenshin/simpread#6730]
## 问题描述：

访问指定的微信公众号、知乎，小众软件，ChinaDaily等，LiveEditor无法实际对文章做任何编辑。（包括但不限于：更改标题，标注划重点，删除文章配图等）

## 参考的链接：
1. 小众软件：https://www.appinn.com/pomotroid/
2. 知乎：https://www.zhihu.com/question/669932263/answer/3790486530
3. 微信公众号：https://mp.weixin.qq.com/s/pz_Mja-nbqdwcIAkh6k91Q

## 复现步骤：
1. 访问网页文章，待插件自动识别文章，并进入阅读模式
2. 点击Live Editor工具栏的各项按钮：
- 其中Live Editor 和 简易编辑 点击无任何反应
- 点击清除元素，右上角有弹窗提醒，但无法实际删除图片
- 
![image](https://github.com/user-attachments/assets/c05616c1-5fd3-48ef-903f-378b487c0268)

3. 无法对文章做标记，划动选中文本后，不会弹出标注的颜色选项框：
- 
![image](https://github.com/user-attachments/assets/02320afd-edeb-42a7-b8d4-060a13b79be6)

4. 检查简悦同步助手正常启动，近期没有做什么更改配置的操作. 

### 操作系统

Win11

### 浏览器

Edge

### 发生问题的网址

https://mp.weixin.qq.com/s/pz_Mja-nbqdwcIAkh6k91Q

**Comment by Kenshin** [comment]
emmmm

我没有复现你提到的问题，我随便找个你提供的链接，如下图，可正常使用 Live Editor 也可正常编辑。

<img width="873" alt="image" src="https://github.com/user-attachments/assets/0f02daec-30c8-4de0-b7c3-cfbb160441ef">

> LiveEditor无法实际对文章做任何编辑。（包括但不限于：更改标题，标注划重点，删除文章配图等）

注意：

1. **标注划重点** 并不是 Live Editor 的功能，Live Editor 可以修改简悦标注的内容，但这样会在进入阅读模式后标注丢失。（也有办法解决，但这不是此问题讨论范围）

2. Live Editor 无法删除文章配图，但可以删除正文内的图片。

所以：

1. 请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

2. 重新安装 [Live Editor](https://simpread.ksria.cn/plugins/details/y8Mai5IBwN)，你提到了使用同步助手，所以需要通过 https://www.yuque.com/kenshin/simpread/fcw60u 此方式安装。

或录屏给我看下具体遇到的问题。

**Comment by mdsnalw** [comment]
好的，感谢大佬的回复，由于Github的视频大小限制，我将分两部分上传录屏。
以下是第一部分：问题再现：

https://github.com/user-attachments/assets/613e2d7d-cd8b-4b55-9dd7-5e10f7b9e15d

**Comment by mdsnalw** [comment]
第二部分 重装插件，关键的类似马克笔的颜色批注无法显示，只能清除图片等

https://github.com/user-attachments/assets/9b80d1e3-f99b-4c77-95da-4a58ca3fc741

**Comment by Kenshin** [comment]
嗨 😂

你还是没有按照我说的去做... 

<img width="934" alt="image" src="https://github.com/user-attachments/assets/911fa0bd-4818-4d48-bb3e-ff05e017d1dc">

上图告诉你了两点，第一点你没有做；第二点你没有做完...

第一点的意思是：在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。因为我感觉你的问题看起来像是被其它扩展干扰造成的。

至于你下面提到的

<img width="832" alt="image" src="https://github.com/user-attachments/assets/f9cf02dc-83e2-439d-a785-f3b6fe1a0d40">

我怀疑是你的浏览器设置了什么导致的（甚至于 Live Editor 的问题也一样）

***

如果还是没法搞定，把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6730

然后在这里回复我，我看看你的配置文件是否有问题。

**Comment by mdsnalw** [comment]
Hello~ 
第一个方法其实我是有用过的，但是切换到隐身（In Private）模式后，能支持的插件就只有一个，没有简悦插件可以选。

![image](https://github.com/user-attachments/assets/69fbeed6-720e-41cf-b594-c655a85c2f9f)

相关配置文件，已经发到你的simpread后缀邮箱了哈，后空再帮忙检查下具体问题，感谢~

**Comment by mdsnalw** [comment]
Hi 大佬，
不好意思，请问下那个配置文件的邮件有收到吗，不知道是具体什么问题导致的冲突呢？ 还请有空帮忙分析下哈，感谢~

**Comment by Kenshin** [comment]
我明天确认下～

**Comment by Kenshin** [comment]
嗨，问题解决了，是因为你的 `simpread_config.json` 里面加稍后读时加入了错误的数据造成的。

你在 Email 中将这个文件下载到并替换原来的 `simpread_config.json` 重启浏览器后即可。

PS：我关闭这个 Issues 了，有任何问题随时在讨论~

**Comment by mdsnalw** [comment]
谢谢大佬🙏，我目前无法直接查看配置文件内容，这几天我也是用另一台电脑在做阅读笔记。还想说实在不行就重装一遍 SimpRead和做设置了～ 我晚点再做下替换看看，再次感谢！～



---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 日期 | 2024年10月09日 10:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kenshin/simpread] Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑 (Issue #6730) |

嗨，问题解决了，是因为你的 simpread_config.json 里面加稍后读时加入了错误的数据造成的。

你在 Email 中将这个文件下载到并替换原来的 simpread_config.json 重启浏览器后即可。

PS：我关闭这个 Issues 了，有任何问题随时在讨论~

**Comment by Kenshin** [comment]
> 还想说实在不行就重装一遍 SimpRead和做设置了～

不需要的，给你的文件 100% 没问题。

你的问题出在：加入稍后读时因为某些误操作加入了一些 `null` 值进去，导致稍后读结构错误造成的。

原本是比较简单的问题，但一直以为你只是单纯的因为其它扩展导致 Live Editor 无法使用...  🌚

***

解决的话，**回头务必帮忙在** [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评

以便让更多人知道 😉 😁 👍

**Comment by mdsnalw** [comment]
> > 还想说实在不行就重装一遍 SimpRead和做设置了～
> 
> 不需要的，给你的文件 100% 没问题。
> 
> 你的问题出在：加入稍后读时因为某些误操作加入了一些 `null` 值进去，导致稍后读结构错误造成的。
> 
> 原本是比较简单的问题，但一直以为你只是单纯的因为其它扩展导致 Live Editor 无法使用... 🌚
> 
> 解决的话，**回头务必帮忙在** [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评
> 
> 以便让更多人知道 😉 😁 👍

我的确又注册新Google账号了，但貌似如果我点击获取插件，会直接替代当前使用的SimpRead配置吧。等我有空研究好了，在用新账号回复好评😁

**Comment by Kenshin** [comment]
> 但貌似如果我点击获取插件，会直接替代当前使用的SimpRead配置吧

不会 😂 你需要手动导入/导出你的配置，细节 [可以看这里](https://simpread.pro/docs/#/%E6%89%8B%E5%8A%A8%E5%90%8C%E6%AD%A5)

**Comment by mdsnalw** [comment]
Hey 大佬，早上好！

昨天我尝试在Chrome上评价插件，但找不到评价入口，无论是手机端桌面模式还是电脑端。意外的是，我发现在Chrome插件商店界面新注册Google账号异常简便，无需手机验证码，是个惊喜的发现~

![80e55693f1630b6b5a34e0ce987efc6](https://github.com/user-attachments/assets/499fa24d-3ad5-495d-96ec-2c79d3430b6f)


我问了下AI，并结合自己的情况，大概率是以下原因，找个时间我再试下：
![image](https://github.com/user-attachments/assets/af83bb45-a71c-4b01-8576-7a3a145992ac)

**Comment by Kenshin** [comment]
嗨，谢谢这么负责任的调查 👍

> 以下内容纯属好奇讨论而已

使用旧的 Google 账户没法在下图中看到评论入口吗？

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/87ceef19-7285-46af-b56b-070e37cec834">

**Comment by Kenshin** [comment]
另外，请问下你的 Chrome 版本是多少？

**Comment by Kenshin** [comment]
还有，你随便找一个你安装过的 Chrome 扩展，看下是否可以评论？（使用旧 Google 账户）

**Comment by Kenshin** [comment]
最后，你使用 Chrome 访问 https://chromewebstore.google.com/detail/%E7%AE%80%E6%82%A6-simpread/ijllcpnolfcooahcekpamkbidhejabll 后是否跟下面的截图一样？

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/c3ee0df2-5fce-4b96-9610-1eedddbf8e8b">

如果不一样，截图给我看下你的界面是如何显示的？

**Comment by mdsnalw** [comment]
> 嗨，谢谢这么负责任的调查 👍
> 
> > 以下内容纯属好奇讨论而已
> 
> 使用旧的 Google 账户没法在下图中看到评论入口吗？
> 
> <img alt="image" width="1177" src="https://private-user-images.githubusercontent.com/81074/377287508-87ceef19-7285-46af-b56b-070e37cec834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzI3MjQsIm5iZiI6MTcyOTEzMjQyNCwicGF0aCI6Ii84MTA3NC8zNzcyODc1MDgtODdjZWVmMTktNzI4NS00NmFmLWI1NmItMDcwZTM3Y2VjODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAyMzM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmU3ZGI4MDU3Zjg0NjM0Njg4YTdmZjUxMzRmMTU5ODRjNzkyNTRhOGFhMDk3MWZhNDU0MzhiOWNiODAyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FTbvQvgbVlu-xkWevHQlkLfY6cUiKFTrDXbGOSFwz-Y">

旧的账户可以，不过在不同位置，是在“所有评价”处的下拉框→ “我的评价”：

![c7ddd472df0422ea80eb6567f252d25](https://github.com/user-attachments/assets/432736c5-70ed-464c-ab04-c8c0d5e190b8)

**Comment by mdsnalw** [comment]
> 另外，请问下你的 Chrome 版本是多少？

这个等我下班后再确认下哈，公司虽说也有Chrome, 但Proxy插件的开发者停止对Chrome的支持了，所以没办法在公司的Chrome上科学 😂

**Comment by mdsnalw** [comment]
> 还有，你随便找一个你安装过的 Chrome 扩展，看下是否可以评论？（使用旧 Google 账户）

这是个不错的workaround👍, 等我回去再换个插件测试下👌

**Comment by mdsnalw** [comment]
> 最后，你使用 Chrome 访问 https://chromewebstore.google.com/detail/%E7%AE%80%E6%82%A6-simpread/ijllcpnolfcooahcekpamkbidhejabll 后是否跟下面的截图一样？
> 
> <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/81074/377288380-c3ee0df2-5fce-4b96-9610-1eedddbf8e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzI3MjQsIm5iZiI6MTcyOTEzMjQyNCwicGF0aCI6Ii84MTA3NC8zNzcyODgzODAtYzNlZTBkZjItNWZjZS00Yjk2LTk2MTAtMWVlZGRkYmY4ZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAyMzM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZTM3MzliN2Q5MjBhYzkxYmUwNGE0Njg2ZDNhYmZjMDdkNWQxMjY5NmY2NDg4YzVjZjJmOWVkNTQ4MTcyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HFLx-sFEBGu70vqM2meZ-Z5kiNpMMbGqIda92sBL1y0">
> 如果不一样，截图给我看下你的界面是如何显示的？

一样的，也是有这段“此扩展程序未遵循Chrome扩展程序的最佳实践，因此可能很快将不再受支持。”提示

**Comment by Kenshin** [comment]
> 旧的账户可以，不过在不同位置，是在“所有评价”处的下拉框→ “我的评价”：

okay 没问题就行（你也可以使用旧账户评价）

因为你在 https://github.com/Kenshin/simpread/issues/6730#issuecomment-2418270634 提到的情况再加上 Chrome 近期「抽风」所以才有了上面的测试~ 

🙏

> 这个等我下班后再确认下哈

okay （如果方便，能想起来就帮忙看下~

> 一样的，也是有这段“此扩展程序未遵循Chrome扩展程序的最佳实践，因此可能很快将不再受支持。”提示

Chrome 是什么版本？是什么系统？

**Comment by mdsnalw** [comment]
> 另外，请问下你的 Chrome 版本是多少？

无法做评论时的版本是：
![image](https://github.com/user-attachments/assets/6486c928-9b84-4840-9687-3b0123139bcb)

**Comment by mdsnalw** [comment]
> 还有，你随便找一个你安装过的 Chrome 扩展，看下是否可以评论？（使用旧 Google 账户）

同样版本的Chrome，切换到旧账户，下载其他插件，有显示撰写评论的选项：

![image](https://github.com/user-attachments/assets/13c9c920-b089-432f-a4c1-d83b8488eec1)

Chrome版本信息如下，系统：Win11
![image](https://github.com/user-attachments/assets/5f04d303-7831-4767-8882-6fe7643f956c)

旧账户下，到SimpRead插件评论界面，有显示“查看我的评价”：

![image](https://github.com/user-attachments/assets/2f496474-654b-4dd2-9585-1f8c6c20423f)

**Comment by mdsnalw** [comment]
多次交换测试下来，我估计应该是账号本身的问题，评价恐怕得等后续确认账号问题再补上了哈😂

旧账号：
下载完，会直接显示评论框：
![image](https://github.com/user-attachments/assets/cda0b5fa-5ac1-437f-9fc6-65805e040fa3)

新账号：
下载完，无法显示评论框：
![image](https://github.com/user-attachments/assets/25361b4e-a98c-428a-b677-a1f68f22ad17)

**Comment by Kenshin** [comment]
小事情～

**Comment by mdsnalw** [comment]
嗨，大佬，早上好！

不好意思，得Reopen这个问题，这个问题又复现了. 点击Live Editor没有任何反馈. 

![Image](https://github.com/user-attachments/assets/ca3be16a-e141-46a2-88b3-98b24274a0e6)

以下是相关测试的微信公众号链接. https://mp.weixin.qq.com/s/ke5PTJPgWEoGadNXlkf8pA

我把打包的SimpRead-Config文件发给你了，有空帮忙检查下看是什么问题，多谢~

**Comment by Kenshin** [comment]
嗨，Live Editor 可以升级到 2.0 版了 https://github.com/Kenshin/simpread/discussions/2852

另外，你试试其他页面 e.g. https://36kr.com/p/3328794710976771 是否正常？

我今天有点忙，稍晚给你看下~

**Comment by mdsnalw** [comment]
哈喽，我也在插件端把Live Editor升级到了2.0版本，用插件管理然后粘贴URL的方式升级的. 


尝试了点击Live Editor 2.0和简易编辑，都无法进入编辑文本状态，附件是最新的SimpRead-Config文件，麻烦帮忙看下，谢谢~

**Comment by Kenshin** [comment]
okay 我下午看下（抱歉，这几天简悦八周年，有点忙 🤣

**Comment by mdsnalw** [comment]
没事没事，恭喜哈，八周年庆！🎉🎉 时间过得真快，22年9月接触的Obsidian然后了解到了简悦，在23年5月提了第一个issue，前后也使用三年多了。希望SimpRead越做越好💪😄

**Comment by mdsnalw** [comment]
> okay 我下午看下（抱歉，这几天简悦八周年，有点忙 🤣

大佬，我更新到Live Editor 2.0后，目前还是无法正常使用，还是麻烦帮忙解救下吧：😂(最近用的配置文件，邮件发给你了哈）

![Image](https://github.com/user-attachments/assets/44dc99e3-030a-45ea-a991-0fb790650613)

**Comment by Kenshin** [comment]
> 我把打包的SimpRead-Config文件发给你了，有空帮忙检查下看是什么问题，多谢~

发到哪里了？我没有看到。😂

**Comment by mdsnalw** [comment]
有的，在邮件里，你再看看收件箱哈，不行等我晚上八点左右再重新发给你哈

---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2025年06月12日 16:31 |
| 收件人 | Kenshin/simpread ***@***.***> |
| 抄送人 | 皇阿玛 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Kenshin/simpread] Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑 (Issue #6730) |
Kenshin left a comment (Kenshin/simpread#6730)

我把打包的SimpRead-Config文件发给你了，有空帮忙检查下看是什么问题，多谢~

发到哪里了？我没有看到。😂

**Comment by Kenshin** [comment]
> 在邮件里，你再看看收件箱哈，

发送的 Email 地址说下。

**Comment by mdsnalw** [comment]
邮箱地址 ***@***.***

---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2025年06月12日 18:32 |
| 收件人 | Kenshin/simpread ***@***.***> |
| 抄送人 | 皇阿玛 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Kenshin/simpread] Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑 (Issue #6730) |
Kenshin left a comment (Kenshin/simpread#6730)

在邮件里，你再看看收件箱哈，

发送的 Email 地址说下。

**Comment by Kenshin** [comment]
根本看不到…

你是不是在 Email 中添加配置文件？如果是的话，不要这么做… 😂

请在上面找到我的邮件地址。

**Comment by mdsnalw** [comment]
我补发附件到你的这两个邮箱了哈，你再看下有没有收到哈. 

根据这个Issue底下的历史往来记录，我只能搜索到这两个邮箱了。今天一直想法电脑发邮件给你，但不巧一直在外面跑，跟前同事聚餐。差不多现在才有空😂

相关邮件标题是：Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑 (Issue #6730)

**Comment by Kenshin** [comment]
前一个是对的，后一个我收不到，这是 Github 的邮箱…

我明天看下

**Comment by mdsnalw** [comment]
> 前一个是对的，后一个我收不到，这是 Github 的邮箱…
> 
> 我明天看下

好的，谢谢~

**Comment by Kenshin** [comment]
嗨，正确的配置文件已经给你发过去 ，留意说明~

**Comment by mdsnalw** [comment]
今天早上替换完配置文件后，一切使用正常，还是原来的味道，感谢大佬～

---- 回复的原邮件 ----
| 发件人 | Kenshin ***@***.***> |
| 发送日期 | 2025年06月14日 13:28 |
| 收件人 | Kenshin/simpread ***@***.***> |
| 抄送人 | 皇阿玛 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Kenshin/simpread] Live Editor 点击没有反馈. 文章能正常进入阅读模式，但无法对原文做任何编辑 (Issue #6730) |
Kenshin left a comment (Kenshin/simpread#6730)

嗨，正确的配置文件已经给你发过去 ，留意说明~

**Comment by Kenshin** [comment]
哈，搞定就好。

周末愉快~

**Comment by mdsnalw** [comment]
<img width="2115" height="1238" alt="Image" src="https://github.com/user-attachments/assets/dddad55a-43f9-4a5e-b7d6-32fc40d3909f" />
大佬，不好意思，这个问题又复现了，就是给文章进行划线标注时，有时会手抖对全篇进行了划线，然后取消后，Live Editor功能就失效了，我尝试了清除浏览器Cookies和解除高级会员授权都不行，然后自己借助AI排查，也搞不定。所以需要麻烦您再帮忙检查和修复下哈。SimpRead.config 文件我会通过邮件发给你，谢谢~

Uncaught TypeError: Cannot set properties of undefined (setting 'el')
    at Object.l [as Toggle] (contentscripts.js:11:24940)
    at HTMLElement.<anonymous> (contentscripts.js:10:14296)
    at HTMLElement.dispatch (common.js:7:20091)
    at g.handle (common.js:7:16836)
    at Object.trigger (common.js:7:19191)
    at HTMLElement.<anonymous> (common.js:7:25208)
    at it.each (common.js:6:17597)
    at it.fn.init.each (common.js:6:15559)
    at it.fn.init.trigger (common.js:7:25183)
    at it.fn.<computed> [as click] (common.js:8:12657)
    at HTMLElement.eval (eval at c (contentscripts.js:6:17653), <anonymous>:584:61)
    at HTMLElement.dispatch (common.js:7:20091)
    at g.handle (common.js:7:16836)

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/5750 能否解决？
