### ISSUE TITLE
新版 Chrome 的不兼容问题

### ISSUE THREAD

**Issue by xleonzhao** [Kenshin/simpread#6732]
### 描述这个错误

更新了 Chrome 浏览器到Version 129.0.6668.70 (Official Build) (x86_64)后，会出现如下提示：

“This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.”

Chrome 建议卸载 simpread，望尽快修复。

### 复现步骤

打开网址：https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll，即可见警告信息

### 操作系统

macOS

### 浏览器

Version 129.0.6668.70 (Official Build) (x86_64)

### 发生问题的网址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

**Comment by Kenshin** [comment]
嗨，无需担心。

详细说明和解决方案 https://github.com/Kenshin/simpread/discussions/6633

**Comment by xleonzhao** [comment]
好的，谢谢

**Comment by Kenshin** [comment]
小事情 😄 

（没想到你能马上回复我，看来是个夜猫子  😏
