### ISSUE TITLE
建议可以将阅读模式的图片下载到指定目录

### ISSUE THREAD

**Issue by 0x0404** [Kenshin/simpread#6733]
### 请描述你的建议或任何内容

目前图床插件往 PicGo 图床导入图片时是直接发送图片的 URL 。但是如果图片的网站有防盗链设置（如[少数派](https://sspai.com/)），那么 PicGo 下载图片就会 HTTP403 导致导入图片失败。所以需要图床插件能先将浏览器显示的图片保存到本地，然后导入到 PicGo 中。

图床插件内置的 cloudinary 图床使用本地转换的方式，可以转存有防盗链的图片，但是 cloudinary 图床可能需要付费，而且数据不完全由自己掌控。PicGo 图床方案中 PicGo 作为中转站，后端不仅可以接七牛、腾讯云、阿里云等商业服务，也可以用自建的  [LskyPro](https://github.com/lsky-org/lsky-pro)、[Lychee](https://github.com/LycheeOrg/Lychee)等图床方案，选择灵活多样，数据完全由自己掌控，所以完善 PicGo 图床方案更有价值。

> picgo 如果能检测文件夹的话，就简单了，简悦可以下载图片到指定文件夹，然后 Picgo 检测这个文件夹的变动，有新图片加入即可上传。

目前 PicGo-Server 可以 [HTTP 调用上传具体路径图片](https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#http%E8%B0%83%E7%94%A8%E4%B8%8A%E4%BC%A0%E5%85%B7%E4%BD%93%E8%B7%AF%E5%BE%84%E5%9B%BE%E7%89%87)，如：
```Bash
curl -XPOST "http://127.0.0.1:36677/upload" \
    -d '{"list": ["/tmp/SimpRead/test.jpg"]}'
```
所以可以让图床插件先下载图片到指定文件夹，再通过 HTTP 调用上传具体路径图片到 PicGo-Server 。如果通过

> Picgo 检测这个文件夹的变动，有新图片加入即可上传

的方式上传图片，简悦无法获得上传后图片的 URL ，就无法把 URL 插入到原来的文章中（看上去无法实现图床功能）。

**Comment by Kenshin** [comment]
> 但是 cloudinary 图床可能需要付费

并不需要付费，免费版足够使用了.... 

> 而且数据不完全由自己掌控

cloudinary 与你使用的其它国内图床没有任何区别... 甚至于比你了解的全部图床都要安全。

***

我之前已经给你提过了：你提到的方式，对简悦来说太麻烦了，当然**下载图片到指定目录简悦这边可以实现**。

余下的需要 PicGo 的配合，即：监控指定文件夹的变化自动上传图片，这对于一个 App 来说太简单了，但这些功能跟简悦没有任何关系 😂

***

有个比较简单的方案，即：先导入 Cloudinary 图床，然后在导入到 PicGo 图床

<img width="558" alt="image" src="https://github.com/user-attachments/assets/d708464f-43bb-49e2-8eb6-4bd6e5818f92">

**Comment by 0x0404** [comment]
> 余下的需要 PicGo 的配合，即：监控指定文件夹的变化自动上传图片，这对于一个 App 来说太简单了，但这些功能跟简悦没有任何关系 😂 

就算 PicGo 能监控指定文件夹的变化自动上传图片，简悦也没有途径拿到这些图片的 URL 了吧，要怎么把转存后的 URL 嵌入到原来的文章中呢？

**Comment by Kenshin** [comment]
> 简悦也没有途径拿到这些图片的 URL 了吧

简悦如果能下载到本地的指定文件夹，自然就可以拿到这些数据。

不过... 这样做的话，也不需要 PicGo 监控文件夹了，我可以直接上传...

我考虑下这个功能。

***

但，我建议你直接使用我提到的方式，最简单直接。

**Comment by 0x0404** [comment]
> 先导入 Cloudinary 图床，然后在导入到 PicGo 图床

这种方式看上去可以解决防盗链图片的问题，就是操作有点繁琐。

> 简悦如果能下载到本地的指定文件夹，自然就可以拿到这些数据。

简悦下载到指定文件夹后，简悦能知道的只有图片的原始 URL 和本地路径。

PicGo 监控指定文件夹的变化自动上传图片，也不会把这些图片在图床里的 URL 告诉简悦。

所以简悦要怎么通过图片的原始 URL 和本地路径知道图片在图床里的 URL 呢？要怎么改写文章里的图片 URL 呢？😂

**Comment by Kenshin** [comment]
唉 😂

你想复杂了，我大概想明白如何做这个事情了，建议详细看下 https://github.com/Kenshin/simpread/issues/6733#issuecomment-2390390923 的描述，我应该描述的很清楚了，包括：临时解决方案。

**Comment by 0x0404** [comment]
> 你想复杂了，我大概想明白如何做这个事情了，建议详细看下 https://github.com/Kenshin/simpread/issues/6733#issuecomment-2390390923 的描述，我应该描述的很清楚了，包括：临时解决方案。

其实我还是没看明白简悦、PicGo 要怎么交互才能拿到图片在图床里的 URL ，不过大佬你想明白如何做这个事情就行了。临时解决方案我看懂了，可以先试试。

另外  cloudinary 图床使用本地转换的方式，我猜是不是  cloudinary 图床提供了接口能直接传 Based64 后的图片？PicGo 如果有接口直接传图片应该会容易很多吧。

**Comment by 0x0404** [comment]
如果有表单上传功能，图床插件的本地转换实现会容易一些吗？用[PicList](https://github.com/Kuingsmile/PicList)替换[PicGo](https://github.com/Molunerfinn/PicGo)。

> PicList的内核使用的是原版PicGo-Core基础上修改的[PicList-core](https://github.com/Kuingsmile/PicList-Core)，为云端删除等功能做了适配，同时，新增了水印添加和图片压缩/缩放/旋转/格式转换等功能，可以通过CLI命令行调用，支持通过picgo-server命令开启上传服务器，还有一些其他的功能改动。

基本可以无缝从 PicGo 迁移到 PicList ，而且 PicList 基本兼容 PicGo 。

> PicList V1.5.0以上版本提供 一键迁移功能，进入 设置页面，然后在 从PicGo迁移选项点击右侧按钮即可，迁移后请重启应用生效。

PicList 的内置 Serve 有[表单上传功能](https://piclist.cn/advanced.html#%E5%86%85%E7%BD%AE%E6%96%87%E4%BB%B6Web%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E4%BD%BF%E7%94%A8)：

> 表单上传 2.6.3+
请求方法: POST
url: http://127.0.0.1:36677/upload （此处以默认配置为例）
请求body: multipart/form-data格式，key任选，value为图片文件
即可上传。

**Comment by Kenshin** [comment]
第一次知道 PicList 我先研究下。

但某些网站的机制会阻止图片转换为 `multipart/form-data` 方式。

我先 Mark 下，调查清楚后再讨论~

**Comment by Kenshin** [comment]
嗨，目前测试通过，至少 `少数派` 与 `公众号` 的图片没问题。

后续完成后会告诉你~

**Comment by Kenshin** [comment]
嗨，图床 2.2.0 版发布了，主要增加了 PicList 图床方案。

我测试了少数派和公众号是没问题的。

我关闭这个 issues 了，有任何问题可以随时跟我讨论~


安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/VdMfVaXlni) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
