### ISSUE TITLE
無法連結 evernote 授權過程錯誤

### ISSUE THREAD

**Issue by r91085** [Kenshin/simpread#6736]
### 描述这个错误

點擊啟用之後，就跳了錯誤，也沒有跳轉出任何其他需要我授權確認的按鈕之類的

![image](https://github.com/user-attachments/assets/3517444b-a9c9-4763-b274-0829a0b0f87b)

### 复现步骤

1. 點擊 "是否連接開授權 evernote"
2. 出現前面截圖內的錯誤

### 操作系统

windows

### 浏览器

Cent Browser 版本 5.1.1130.129 (正式版本) (64 位元)

### 发生问题的网址

www.google.com

**Comment by Kenshin** [comment]
嗨，这个功能暂时下线了 😂

PS：我个人不建议用户再使用 Evernote 了。

**Comment by r91085** [comment]
明白了～

PS : evernote 走下坡了許多年，但被收購之後我覺得越來越好了

**Comment by Kenshin** [comment]
哈，我的意思不是 Evernote 不好用，我的意思是：Evernote 的 API 不好用（基本上不是给「开发者」看的 😂 完全靠猜... 使用它的 API 失败率在 70% 以上，因为它使用了一套独有的 ENML 方案，需要将 HTML → ENML，但它没有给出完备的文档..

同时 Evernote 扩展应该是我见过最好用的剪藏工具（唯一能跟简悦匹敌的）。

关于 Evernote 跟简悦的用法，你可以看下：

- https://github.com/Kenshin/simpread/discussions/3472
- https://github.com/Kenshin/simpread/discussions/3471 （重点）

我的建议是：使用简悦优化版面，再使用 Evernote 剪藏。（前提是 Evernote 用户）

**Comment by r91085** [comment]
一定要配合 Live Editor 才能使用 Evernote 擴展 是嗎？
我試起來單純的閱讀模式下，按下 Evernote 擴展 是不起作用的

**Comment by Kenshin** [comment]
> 一定要配合 Live Editor 才能使用 Evernote 擴展

如果你希望使用 Evernote 的剪藏功能，同时也可以使用简悦的阅读模式，答案如你所说。

使用 https://github.com/Kenshin/simpread/discussions/3471 的优势在于：可以利用简悦的阅读模式来获取更合理的正文结构，同时可以使用 Live Editor 做二次编辑，然后再保存会原页面，这样再使用 Evernote 剪藏的话，效果会很好。
