### ISSUE TITLE
在 SimpRead 的 output 下又有一个 output，这正常么？

### ISSUE THREAD

**Issue by feimiao** [Kenshin/simpread#6738]
### 描述这个错误

手机上收藏的稍后读在第一层 \SimpRead\output，电脑上收藏的稍后读在第二层 SimpRead\output\output

### 复现步骤

![image](https://github.com/user-attachments/assets/2ca258d3-e351-4e82-8981-df54ec4d4118)
![image](https://github.com/user-attachments/assets/c6b6b634-acf4-4a8d-8966-c934ba23eb36)
同步助手配置路径没得问题：
![image](https://github.com/user-attachments/assets/0fda18b0-4478-472f-a5ea-f05e5a85a328)
导出服务也是：
![image](https://github.com/user-attachments/assets/fac68a1b-a4ed-4346-8bd5-5df16736bdfb)

是不是我哪里理解错了？

### 操作系统

Windows 11 专业版23H2

### 浏览器

Edge 129.0.2792.65 (正式版本) (64 位)

### 发生问题的网址

https://36kr.com/p/2977813076021257

**Comment by Kenshin** [comment]
当然不正常 😂

<img width="610" alt="image" src="https://github.com/user-attachments/assets/88e94ca2-99a0-4d56-927a-1573cba86c3e">

根据上图，我感觉你设置的根目录为 `C:\Users\50358\Desktop\SimpRead\output`  所以：

在同步助手重新设置下路径，保存后重启同步助手，再试试， `simpread_config.json` 应该出现在 `C:\Users\50358\Desktop\SimpRead` 下面才是正确的。  

PS：我认为你的动手和阅读文档的能力都不错，所以建议这种错误可以自行折腾下（比如我告诉你的步骤：基本上就是常规性重置的步骤。

**Comment by feimiao** [comment]
目前并未找到原因，我并未动我的“简悦同步助手”，且原始根目录设置的确实是 `C:\Users\50358\Desktop\SimpRead` ，但第二天电脑再开时配置丢失了。我直接从 `C:\Users\50358\Desktop\SimpRead\output` 中将 simpread_config.json 配置文件导入浏览器，之后所有的配置文件调整都自动在 `C:\Users\50358\Desktop\SimpRead` 中了😭
![image](https://github.com/user-attachments/assets/e8380d58-7fa4-4eed-8763-6ad008390556)
![image](https://github.com/user-attachments/assets/56e465b8-d6d2-406a-a525-7cfa1d7fb874)

如此，在 `C:\Users\50358\Desktop\SimpRead\output` 中的 simpread_config.json 文件及 backup 文件夹岂不是都可以删除了？

另，我理解的是 `C:\Users\50358\Desktop\SimpRead\output\output` 仅存储的是“导出”的文件， `C:\Users\50358\Desktop\SimpRead\output` 中存储的是“标注”及“稍后读”文件，请问这个理解是否正确？

**Comment by Kenshin** [comment]
> 在 C:\Users\50358\Desktop\SimpRead\output 中的 simpread_config.json 文件及 backup 文件夹岂不是都可以删除了？

理论上是可以删除的。

> 我理解的是 C:\Users\50358\Desktop\SimpRead\output\output 仅存储的是“导出”的文件， C:\Users\50358\Desktop\SimpRead\output 中存储的是“标注”及“稍后读”文件，请问这个理解是否正确？

`output` 主要是：快照，包含全文和标注，以及你在同步助手增强导出里面设置的内容默认也会在这里。

一定要留意：如果配置了本地快照，一定确保 `C:\Users\50358\Desktop\SimpRead` 与 `C:\Users\50358\Desktop\SimpRead\output` 这种结构，不能是 `C:\Users\50358\Desktop\SimpRead\output\output`

不知道你的问题最终是否解决了？

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~

**Comment by feimiao** [comment]
> > 在 C:\Users\50358\Desktop\SimpRead\output 中的 simpread_config.json 文件及 backup 文件夹岂不是都可以删除了？
> 
> 理论上是可以删除的。
> 
> > 我理解的是 C:\Users\50358\Desktop\SimpRead\output\output 仅存储的是“导出”的文件， C:\Users\50358\Desktop\SimpRead\output 中存储的是“标注”及“稍后读”文件，请问这个理解是否正确？
> 
> `output` 主要是：快照，包含全文和标注，以及你在同步助手增强导出里面设置的内容默认也会在这里。
> 
> 一定要留意：如果配置了本地快照，一定确保 `C:\Users\50358\Desktop\SimpRead` 与 `C:\Users\50358\Desktop\SimpRead\output` 这种结构，不能是 `C:\Users\50358\Desktop\SimpRead\output\output`
> 
> 不知道你的问题最终是否解决了？

我把所有简悦相关的都重置了并重新进行配置，目前没遇到问题，应该算是解决了

**Comment by Kenshin** [comment]
okay 解决就好 👍
