### ISSUE TITLE
代码块提取失败

### ISSUE THREAD

**Issue by ripples-alive** [Kenshin/simpread#674]
请说明发生问题的环境

操作系统 macOS Catalina 10.15.2

浏览器版本 Chrome 80.0.3987.122

简悦版本 1.1.4

发生问题的地址 https://mp.weixin.qq.com/s/DvK1d2TqxTIEG0KJFHLM7g

页面里大部分代码块都空了（因为代码块里放的不是代码？）

**Comment by Kenshin** [comment]
微信后台使用了不同的 `代码高亮` 方案，所以在 **未支持的代码高亮方案** 下会出现问题。

修复好这个插件后我会通知你。

**Comment by ripples-alive** [comment]
好的，谢谢

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀

**Comment by Kenshin** [comment]
哈哈，谢谢这么详细的比对... 为了找这个问题（ 代码角度） 我也是快找吐了，才知道原因是什么...

> 这货在 <pre> 里面加了个图片...

![image](https://user-images.githubusercontent.com/81074/86691069-153acd00-c03b-11ea-89bf-173cb4e5af67.png)

这确实没办法判断... 完全属于结构乱用的情况。

**Comment by ripples-alive** [comment]
😂 我就是翻到最后发现有个空的代码块就仔细对比了下，实在是结构乱用也没办法了，应该一般也不会遇到。。。

**Comment by Kenshin** [comment]
😅 

这种情况确实很少发生，也没什么好办法解决，就先这样吧。 ✌🏻
