### ISSUE TITLE
一直显示正在保存到notion

### ISSUE THREAD

**Issue by dadaomamao** [Kenshin/simpread#6742]
### 描述这个错误

按照教程安装notion导入和导入增强插件后，选择保存到notion时收到了截图的错误 ，选择一键导出全文到notion时提出稍后再试
![image_2024-10-05_21-04-17](https://github.com/user-attachments/assets/b8ee9843-64a2-4437-85b7-ba77f6dd54f3)
我已经进行了
1、退出notion账号 
2、取消简悦授权
3、重启系统
4、重新登录notion账号
5、重新授权
这个操作，还是同样的错误。
由于notion界面出现了空白页，我考虑有可能是网络问题，故而使用clash tun模式 以及普通代理模式的香港ip进行了测试，依然失败 本地环境四川电信非公网ip

### 复现步骤

更换自己的Notion账户并与简悦集成
1. 退出当前Notion账户
打开Notion网站或应用
点击左下角的个人头像
选择"Log out"退出当前账户
2. 登录自己的Notion账户
在Notion登录页面输入您的邮箱和密码
或使用Google、Apple等第三方账号登录
3. 复制并设置模板
访问此模板链接
点击右上角的"Duplicate"按钮复制模板
将复制的页面重命名为"来自简悦的稍后读"
点击页面右上角的星形图标,将其添加到收藏夹
!添加到收藏夹
4. 重新授权简悦
打开简悦扩展的选项页
依次点击:服务 → 授权管理 → Notion
点击"取消授权"
然后点击"重新授权",并选择刚才创建的"来自简悦的稍后读"页面
!重新授权Notion
5. 创建Notion集成
访问 https://www.notion.so/my-integrations
点击"+ New integration"创建新的集成
填写集成名称(如"简悦集成")
选择关联的工作区
其他选项保持默认
!创建Notion集成
6. 配置集成权限
按照下图设置集成的权限:
!配置集成权限
7. 获取集成Token
完成设置后,您会看到集成的详细信息
复制"Internal Integration Token"备用
!获取Token
8. 邀请集成到页面
打开之前创建的"来自简悦的稍后读"页面
点击右上角的"..."按钮
选择"Add connections"
找到并选择刚才创建的集成
9. 获取页面ID
在浏览器地址栏中复制页面URL
URL格式类似:https://www.notion.so/abcd****xyz?v=123***789
其中abcd****xyz部分就是页面ID
!获取页面ID
10. 配置简悦插件
打开任意网页(如 https://sspai.com/post/71576)
进入简悦阅读模式
点击右下角的触发器 → 动作 → 插件触发器
找到"导入到Notion辅助增强"插件并打开其选项页
!打开插件选项
11. 填写插件配置
在插件选项页中填写:
Notion Token(第7步获取的)
Database ID(第9步获取的页面ID)
12. 测试导入
刷新当前页面
再次进入简悦阅读模式
尝试将页面导入到Notion，失败。

安装官方教程安装的notion导入 

### 操作系统

win11专业版

### 浏览器

chrome129.0.6668.90

### 发生问题的网址

zhihu.com

**Comment by dadaomamao** [comment]
请所有者关闭这条问题，无法保存的原因是没有设置图床，在设置图床后 已经成功保存

**Comment by Kenshin** [comment]
竟然是这样....

所以你的设置到底是什么情况？截图给我看下，我看看能否增加一个更合理的提示避免这种问题的发生~
