### ISSUE TITLE
知乎增强插件不显示在触发器中

### ISSUE THREAD

**Issue by dadaomamao** [Kenshin/simpread#6743]
### 描述这个错误

知乎增强插件安装后 在插件触发器中找不到该插件的配置选项 其似乎完全未启用 已经尝试重新安装插件 无效 尝试在隐身模式下单独启用简悦 无效  重启电脑 无效
![image](https://github.com/user-attachments/assets/e208fe87-fa54-424a-a1c8-ddcdb62204e9)
![image](https://github.com/user-attachments/assets/7b698554-c7b9-4eef-bd4a-07edc424ac16)

### 复现步骤

chrome版本129.0.6668.90
系统版本win11 
网络电信

### 操作系统

win11

### 浏览器

chrome版本129.0.6668.90

### 发生问题的网址

zhihu.com

**Comment by Kenshin** [comment]
开启同步助手的自动同步功能后需要使用 https://www.yuque.com/kenshin/simpread/fcw60u 安装插件。

**Comment by dadaomamao** [comment]
已经按该方案解决

**Comment by Kenshin** [comment]
okay 解决就好 👍
