### ISSUE TITLE
一个无法稳定复现的乱码问题

### ISSUE THREAD

**Issue by dadaomamao** [Kenshin/simpread#6745]
### 描述这个错误

![image](https://github.com/user-attachments/assets/a20beaa6-d8fd-4998-ac18-539aafc246f2)
如图，保存到本地的网页也出现乱码

### 复现步骤

似乎是随机出现 未发现规律 考虑最有可能的还是utf8编码 一类的系统环境问题

### 操作系统

win11专业版

### 浏览器

chrome 129.0.6668.90（正式版本） （64 位）

### 发生问题的网址

zhihu.com

**Comment by dadaomamao** [comment]
我尝试了多种方法 均无法复现该bug

**Comment by Kenshin** [comment]
okay 那我先关闭这个 Issues 有需要随时回复（并 Re-open 它）

估计是某些极端情况下出现的情况，我目前从未遇到过这种问题。
