### ISSUE TITLE
页面主体内容为视频时，不应该自动进入阅读模式

### ISSUE THREAD

**Issue by Azir-11** [Kenshin/simpread#6746]
### 请描述你的建议或任何内容

示例网站：https://www.huxiu.com/article/3544450.html

在这个网站内，主体内容是video，而不是文本，自动进入阅读模式后反而会无法浏览，还需要手动退出

**Comment by Kenshin** [comment]
嗨

这个问题是因为你使用了 **自动进入阅读模式** 造成的。

<img width="1210" alt="image" src="https://github.com/user-attachments/assets/cf98af7a-9dde-4e13-a360-0926a41f1e74">

个人不建议使用此功能，如果非要使用此功能可以配合 **排除列表** 或 **黑名单** 功能。

但我个人建议关闭此功能，使用 **白名单** 机制。


>  主体内容是video，而不是文本

想法很好，但... 简悦没办法判断这个页面是以 视频为主，还是以文字为主。
