### ISSUE TITLE
Markdown 模板辅助增强插件无法使用

### ISSUE THREAD

**Issue by feimiao** [Kenshin/simpread#6747]
### 描述这个错误

使用官方模板后，点击插件页面中的“测试”按钮缺没反应
![image](https://github.com/user-attachments/assets/b40adefc-3ab7-4b14-976d-9eff65538959)

### 复现步骤

![image](https://github.com/user-attachments/assets/bbb870ee-5941-4bfe-b4a9-d2fb9e97dd39)
用的官方模板，但是点击测试没反应
![image](https://github.com/user-attachments/assets/01be3122-1fd0-4816-a07b-b1cb64dfdd5f)
![image](https://github.com/user-attachments/assets/f4e84603-3b9d-4167-86e9-0718beae5531)
尝试更换模板后依旧点击“测试”没得反应

### 操作系统

Windows 11 专业版23H2

### 浏览器

Edge 129.0.2792.65 (正式版本) (64 位)

### 发生问题的网址

https://36kr.com/p/2977813076021257

**Comment by Kenshin** [comment]
需要在**存在稍后读的页面才能测试**（你截图没有体现这点，我没法判断）

**Comment by feimiao** [comment]
![image](https://github.com/user-attachments/assets/cae79cbd-341a-4330-b715-f9de2b8eb2e5)
已经加入稍后读了，依旧不可以，实测 https://36kr.com/p/2977813076021257 及 https://www.yuque.com/kenshin/simpread/fr8zo5 均不行。

![image](https://github.com/user-attachments/assets/198f2092-486b-459d-b0cb-6151d6b3e7ef)
比较奇怪的是这个网站 https://sspai.com/post/71576 却是可以的。

**Comment by Kenshin** [comment]
把你的 Markdown 模板给我看下，包括：稍后读和标注的。

**Comment by Kenshin** [comment]
我这边没问题，看下图留意版本号

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/394f4e4b-6280-4d04-8001-3230fff3dc7f">

另外，你在 https://github.com/Kenshin/simpread/issues/6747#issuecomment-2396369982 提到的诸如 缓存 之类的论断也都不是正确的 😂

所以，你可以试试打开 DevTools 下图所示

<img width="340" alt="image" src="https://github.com/user-attachments/assets/2d4e043a-9804-4c2c-8f79-e47c72e6768f">

然后按下图所示

<img width="482" alt="image" src="https://github.com/user-attachments/assets/2b1eba2c-1487-4a55-b54d-a3aba0379cb6">

最后在这个插件中点击测试，如果没有报错的话，上图里面会出现一些内容。如果有报错的话，请截图给我。

**Comment by feimiao** [comment]
以下是报错内容：
![image](https://github.com/user-attachments/assets/ca10d3fd-e97d-4d87-af70-31c50da4dc68)

**Comment by Kenshin** [comment]
截图的错误信息是点击 **测试** 后出现的吗？如果不是的话，我需要点击测试后出现的错误。

不过，无论如何都不是这个插件的错误，估计是你的稍后读（标注）错误造成的。

你可以试试：新建一个稍后读然后再标注一条最简单的内容，看看是否还有错误？

**Comment by feimiao** [comment]
可能就是标注的问题诶，反正我标注后可以点击 **测试** 出内容，标注前是不行的，录制相关视频如下
https://github.com/user-attachments/assets/b8694a47-c496-4e2e-b53a-e591aba7446c

**Comment by Kenshin** [comment]
> 可能就是标注的问题诶，反正我标注后可以点击 测试 出内容，标注前是不行的

我测试了只有稍后读（没有标注）的情况，也是没问题的。

***

这个模板的使用人数还不错，不会遇到你提到的各种问题...

***

如果觉得有需要的话，可以把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6747

然后在这里告诉我，我看下是什么问题。

**Comment by feimiao** [comment]
已发送到您邮箱，请查收，谢谢 🙏

**Comment by Kenshin** [comment]
https://github.com/user-attachments/assets/98be954a-f864-4b1a-b51d-307f163becc0

我这边没有任何问题... 测试的网页就是你的稍后读，也没有发现任何出错信息。

**Comment by feimiao** [comment]
我这里做了如下尝试：
1. 其他插件全部禁用
2. 重置简悦并导入我发您的配置

问题依旧，还是得先使用 “标注” 功能标注后才能正常使用 Markdown 辅助增强插件，正如前面[我录的视频](https://github.com/Kenshin/simpread/issues/6747#issuecomment-2400015329)一样。

**Comment by Kenshin** [comment]
我之前应该跟你说过 https://github.com/Kenshin/simpread/issues/6747#issuecomment-2396328530

所以你在 https://github.com/Kenshin/simpread/issues/6747#issuecomment-2400015329 的步骤就是错误的。

所以，在没有稍后读时，你为什么要使用这个插件？

😂
