### ISSUE TITLE
inoreader和notion提示监测到正文获取异常

### ISSUE THREAD

**Issue by dadaomamao** [Kenshin/simpread#6748]
### 描述这个错误

![image](https://github.com/user-attachments/assets/32081087-426f-4866-a87f-7c27124fbd0a)
![image](https://github.com/user-attachments/assets/302f1cf2-4d5c-476d-b173-4f017b347969)
![image](https://github.com/user-attachments/assets/6b2a87ae-67ae-4885-b021-0e357be4251c)
访问notion官方的一些帮助页面和inoreader阅读器的所有界面时都会出现图中的错误 把inoreader阅读器改为列表模式时页面不会直接崩溃 但是简悦完全不触发了 即使打开了rss那个选项 目前已将inoreader和notion官方的指南页面暂时加入黑名单 已经在无痕模式中单独启用简悦测试过notion指南页面 确实如此

### 复现步骤

把inoreader阅读器改为列表模式时页面不会直接崩溃 但是简悦完全不触发了 我日常用的卡片模式

### 其他相关说明

我与其他人可能的最大不同就是clash日常一直开着 走的rule模式 要不就是人在境外 要不就是软路由环境 几乎没有纯粹使用国内ip的情况 此外
![image](https://github.com/user-attachments/assets/275b0180-9f2f-40f6-9dd7-d1790ba59052)
默认开启 但测试时均已使用无痕模式单独加载简悦

### 操作系统

win11 专业版

### 浏览器

chrome版本 129.0.6668.90（正式版本） （64 位）

### 发生问题的网址

inoreader.com https://www.notion.so/zh-cn/help/guides

**Comment by dadaomamao** [comment]
一直使用Dropbox作为同步盘 没有使用坚果云

**Comment by Kenshin** [comment]
假设你所说的「崩溃」是截图上右上角的提示的话，这不是页面「崩溃」 😂

> 访问notion官方的一些帮助页面和inoreader阅读器的所有界面时都会出现图中的错误

这个提示可能是因为你开启了 **自动进入阅读模式** 引起的，细节可以看下 https://github.com/Kenshin/simpread/issues/6746#issuecomment-2396146207 的描述。

不建议使用自动进入阅读模式的功能。

> 把inoreader阅读器改为列表模式时页面不会直接崩溃 但是简悦完全不触发了

需要将 `inoreader.com` 加入延迟加载列表（位置在下图）

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/764be05b-40d2-4261-9140-c3bcf04dc743">

然后重启浏览器确保生效后，进入 inoreader.com 确保 `inoreader.com` 的 URL 结构（可能跟布局有关系）如下图所示

<img width="643" alt="image" src="https://github.com/user-attachments/assets/78bd9dba-17c3-4449-be27-d8365b0f04d5">

然后就可以正常使用阅读模式了，如下图

<img width="1807" alt="image" src="https://github.com/user-attachments/assets/18b20f48-3aa7-4e95-85aa-74f6464fb151">

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/3807ce80-6c80-4b1a-8049-c9a78e747863)
出于隐私原因 我无法截取域名 但是我已经复制域名到这里 它是https://www.inoreader.com/all_articles
我的设置是
![image](https://github.com/user-attachments/assets/604a62e9-7580-472e-85d7-bd2f6dd2d884)
设置后已经重新启动系统 并且特地将inoreader改为列表模式后 手动进入了阅读模式
![image](https://github.com/user-attachments/assets/66296edf-4eef-4076-94b0-83db821e56be)
notion页面第一次进入时依然会获取失败 但是选择重试后似乎正常获取到了  但每一个页面都需要选择重试

**Comment by Kenshin** [comment]
> inoreader

没问题了吗？

> Notion 

域名加的有点问题。

如果你需要将 Notion Page 进入阅读模式的话，需要安装 https://github.com/Kenshin/simpread/discussions/2106

留意同步助手的自动同步需要暂时先关闭自动同步功能。

**Comment by dadaomamao** [comment]
亲 按照你的解决方法 问题依旧 但是我选择将notion相关页面加入黑名单 目前感觉在notion上简悦并不刚需  反倒是一些博客类网站简悦很有用 目前的大问题是我是inoreader的重度使用者 且会有一些针对rss文章的剪藏需求 所以关于inoreader的问题继续求教。
![image](https://github.com/user-attachments/assets/662d5d89-5de4-4d9c-becd-c8f815a46aa3)
如图所示 这是在https://www.inoreader.com/all_articles这个主页上 获取不到任何结果 
![image](https://github.com/user-attachments/assets/b3973605-95e2-4b4b-a0e7-bd706a7dac36)
这是在某个单独的rss文章上打开的结果 几乎获取不到文字

**Comment by Kenshin** [comment]
> 这是在[https://www.inoreader.com/all_articles 这个主页上](https://www.inoreader.com/all_articles%E8%BF%99%E4%B8%AA%E4%B8%BB%E9%A1%B5%E4%B8%8A) 获取不到任何结果

获取不到正文难道不是正常的事情吗 😂 下图的页面压根就没有正文，如何获取？

![](https://github.com/user-attachments/assets/662d5d89-5de4-4d9c-becd-c8f815a46aa3)

简单的说，你的 URL 需要类似 `https://www.inoreader.com/article/3a9c6e74492bfabf-100` 这样才能进入阅读模式，仔细看 https://github.com/Kenshin/simpread/issues/6748#issuecomment-2396657868 的说明，我应该表述的很清楚了。

> 但是我选择将notion相关页面加入黑名单 目前感觉在notion上简悦并不刚需

同样，Notion 也是没问题的，看下图

<img width="1813" alt="image" src="https://github.com/user-attachments/assets/d32b2bc9-559e-45e9-90e7-2284ded71535">

但因为 Notion Page 包含的元素很多，同样详细说明也告诉你了 https://github.com/Kenshin/simpread/discussions/2106

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/330dd17c-ffe5-4f2f-beea-93ee2ab4e673)
这是我直接进入https://www.inoreader.com/article/3a9c6e74492bfabf-10页面的结果 没有获取到全文 我想我应该是正确理解了你的意思

**Comment by dadaomamao** [comment]
该图截的是完整的全图 也就是说 {{{接入秘塔 AI搜索}}}以下的所有内容都没有正常显示

**Comment by dadaomamao** [comment]
我已经确认 我的url 类似于URL https://www.inoreader.com/article/3a9c6e74492bfabf-100 如https://www.inoreader.com/article/3a9c6e744dd6b422- 其结果为
![image](https://github.com/user-attachments/assets/77f06ab6-7b84-4cc3-aca1-2a098ceaeb09)

**Comment by dadaomamao** [comment]
我的显示屏是笔记本外接的2k 27存显示器 不知道是否与此有关联

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/ef06dfa2-0960-44b6-817f-cda3125124bb)
此外 我已经在笔记本的本机屏幕尝试过 问题依旧

**Comment by Kenshin** [comment]
这是我进入你提供的 https://www.inoreader.com/article/3a9c6e744dd6b422- 的界面，留意我的截图箭头所示是否跟你的一致？

<img width="1819" alt="image" src="https://github.com/user-attachments/assets/b991e3f8-4dce-49ef-a659-7bb7c38b5eae">

然后接着看下图

<img width="999" alt="image" src="https://github.com/user-attachments/assets/69a225b3-ad33-4620-948b-8b201e60e547">

> 我的显示屏是笔记本外接的2k 27存显示器 不知道是否与此有关联

当然没关系了... 😂

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/37f8adac-4903-4a1f-b294-5df53232320f)
![image](https://github.com/user-attachments/assets/1c50464a-47cf-41ae-bfdb-fd054662ef5d)
![image](https://github.com/user-attachments/assets/aa44ba98-260b-4d71-9538-232a923e0272)
无效

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/7b176d18-fab6-4a89-bfb7-c22b8db38338)
测试时已经关闭所有其他插件 感觉简悦似乎已经获取到内容 但是显示器不够大的感觉

**Comment by dadaomamao** [comment]
亲爱的作者.....
我尝试访问https://www.inoreader.com/article/3a9c6e744dd6b424-20248-9 显示的结果是
![image](https://github.com/user-attachments/assets/e6b6676b-5ec7-4b2a-9c16-fee691b27597)
但是当我在该界面使用一键导入全文到notion时 导入到notion中的文章一切正常

**Comment by Kenshin** [comment]
emmm 我好像知道是什么问题了...

```
html.simpread-font {
    overflow: initial !important;
}
```

将上面的代码加入到下图所示

![SCR-20241008-qczv](https://github.com/user-attachments/assets/b87b2c04-cc05-4985-8a6d-3e81479b8dd3)

保存后重启浏览器，再试试。

**Comment by dadaomamao** [comment]
![image](https://github.com/user-attachments/assets/69192eb7-cc79-4bc5-9a25-19660d108b47)
在这样的设置下 阅读模式恢复正常 但是rss内嵌阅读模式没有启动 关于内嵌 我需要另开一个issue吗

**Comment by Kenshin** [comment]
> 在这样的设置下 阅读模式恢复正常

如果你的 Notion 设置正确的话，也同样是这个问题，也应该自动解决了。

> 但是rss内嵌阅读模式没有启动
 
你是说 https://github.com/Kenshin/simpread/issues/6735 这个问题吗？如果是的话，不用提 Issues 了，目前这个功能并不太好使，但我找到了解决方案。

解决后我会在这里通知。

**Comment by dadaomamao** [comment]
差不多就是类似的问题 进入简悦的按钮图标不存在 感觉开不开没什么区别 但这个功能也不是特别重要

**Comment by dadaomamao** [comment]
弱弱的问一句 之前那个 属于bug吗

**Comment by Kenshin** [comment]
> 弱弱的问一句 之前那个 属于bug吗

你是指 https://github.com/Kenshin/simpread/issues/6748#issuecomment-2399467429 这个问题吗？

非要严格的说，不算是 Bug。

**Comment by dadaomamao** [comment]
是的 我说的是https://github.com/Kenshin/simpread/issues/6748#issuecomment-2399467429 作者可以关闭这个问题了

**Comment by Kenshin** [comment]
> 我说的是https://github.com/Kenshin/simpread/issues/6748#issuecomment-2399467429 作者可以关闭这个问题了

等我提到的 https://github.com/Kenshin/simpread/issues/6735 问题解决后再关闭它。

**Comment by Kenshin** [comment]
emmm

这个 Issues 与 RSS 注入是两个事情，所以我还是先关闭这个 Issues 吧 😂

等这个功能可以使用后仍可以在这里通知你~
