### ISSUE TITLE
无法安装简悦的插件

### ISSUE THREAD

**Issue by chains0521** [Kenshin/simpread#6749]
### 描述这个错误

![屏幕截图 2024-10-08 021150](https://github.com/user-attachments/assets/e366a942-cd1f-480b-b448-b619988e8177)
无法添加拓展https://simpread.ksria.cn/plugins/details/VQOZdNET2d

### 复现步骤

https://simpread.ksria.cn/plugins/details/VQOZdNET2d
添加拓展,安装失败
![屏幕截图 2024-10-08 021150](https://github.com/user-attachments/assets/65bbde0e-23db-4a21-958b-38bd566baa09)

### 操作系统

windows

### 浏览器

edge

### 发生问题的网址

https://simpread.ksria.cn/plugins/details/VQOZdNET2d

**Comment by Kenshin** [comment]
嗨，解决方案看下图

<img width="997" alt="image" src="https://github.com/user-attachments/assets/8e8407bf-78dd-42e8-ae75-b96400fa30fa">

每操作完后建议重启浏览器。

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~

**Comment by chains0521** [comment]
![PixPin_2024-10-12_16-05-01](https://github.com/user-attachments/assets/66b81720-bdfe-4d08-a10b-267b8eca5b9a)
刷新也没有用,删除后连原来的拓展也下载不了,需要重装吗?账户能否同步信息

**Comment by Kenshin** [comment]
看下图

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/3cb9d7d1-127b-4eb2-a3e3-5e2979f398f8">

或者看下权限是否开了？

https://www.yuque.com/kenshin/simpread/tmmwhl

**Comment by chains0521** [comment]
权限未开,已解决,感谢!

**Comment by Kenshin** [comment]
... 😂

那你如何升级为高级账户的？（因为你的截图显示已经是高级账户了，所以理论上权限早开了~

**Comment by chains0521** [comment]
我之前设置了点击拓展才启用
