### ISSUE TITLE
愿景论坛适配

### ISSUE THREAD

**Issue by lbq1121** [Kenshin/simpread#675]
**请说明发生问题的环境**

[![54778514d7a31352f7ddab4c1836a3ea.png](https://pan.hongtu.me/img/54778514d7a31352f7ddab4c1836a3ea.png)](https://img.wang/image/Zaz7)

- 操作系统 Windows10 1909

- 浏览器版本 Google Chrome 已是最新版本 版本 80.0.3987.122（正式版本） （64 位）

- 简悦版本 **1.1.4**

- 发生问题的地址 <http://bbs.pcbeta.com/viewthread-1845812-1-1.html>

**请描述你的问题**

> 排版错误 如图所示

**截图**
[![7998b0e923.png](https://pan.hongtu.me/img/7998b0e002c0e8c8673e6130914dc923.png)](https://img.wang/image/ZuPK)
> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
谢谢反馈，这个站未加入适配列表，加入后我会在这里通知你，请勿关闭此 issues ~

PS：你也可以通过 `站点适配器` 自行加入。 😀

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
