### ISSUE TITLE
建议知乎辅助增强插件可以设置仅显示第一个答案

### ISSUE THREAD

**Issue by dadaomamao** [Kenshin/simpread#6751]
### 请描述你的建议或任何内容

我希望能优化确保在阅读模式下{{{（自动智能）识别我所看的知乎回答}}}，目前的阅读模式，似乎会把知乎问题页面下的多个回答同时纳入阅读模式，而不是我初始点进去的那个回答，而印象笔记的剪藏插件就可以做到{{{（自动智能）识别我所看的知乎回答}}} 这个功能对于一键导入notion很重要 因为我想导入notion的 只有我想要的回答 而不是该问题下的所有回答  当前即使手动框选我想要的回答 导入时也有不小的概率导入了该问题下阅读模式自动识别的好几个其他的回答。
举例如下 我需要看的回答是
![image](https://github.com/user-attachments/assets/20d8ff1f-0118-4b9c-81f4-6a84d8ca4031)
对应的知乎回答是
![image](https://github.com/user-attachments/assets/4c39cc9d-ff64-4322-80f7-467cafa5484c)
但点进去的时候 知乎界面还包含了两个其他的回答 也就是
![image](https://github.com/user-attachments/assets/00e05883-b8a0-44ff-b2e5-da150ac75a87)
在此情况下进入阅读模式 阅读模式所获取的内容为
![image](https://github.com/user-attachments/assets/118a8091-5c45-4d47-85eb-e4064be69f7f)
也就是多了两个我不想要的回答
经过我自己的几次测试，知乎进入某个特定回答时 除了我的目标答案 总是会默认再多两个答案，而我点进回答想要看的答案永远在首位，我希望增加一个功能 即从某个链接或者回答进入答案页时 阅读模式的自动获取只获取排名最靠前的那个答案

举例如下 我的时间线上 看到的内容如下
![image](https://github.com/user-attachments/assets/5280d886-8c08-4e4a-8eb8-5b643675d4de)
通过该链接进入的回答如下
![image](https://github.com/user-attachments/assets/9c4a4678-fd9c-48b2-885a-d70647a5a733)
该回答排名第一 但是其后还有两个知乎自己加上去的回答 也就是
![image](https://github.com/user-attachments/assets/801a2b44-6463-444f-8f63-86d874bfdacf)
和![image](https://github.com/user-attachments/assets/36d817cb-40ef-42b0-9c31-089a46758b55) 经过反复确认 每一个点进去的链接 都是 链接中提供的原始答案排在首位 然后会加上两个其他回答 排位位置和其他回答数量是一致的 都是链接中提供的原始答案排在首位 然后会加上两个其他回答 这时 将阅读页导入到notion中的效果如下
![image](https://github.com/user-attachments/assets/f4af7773-a7a6-4a87-8e2a-1e5804ed4057)
![image](https://github.com/user-attachments/assets/42362e9a-bac4-4d2f-9c76-759cff62c635)
也就是说 阅读页所有被识别到的三个答案都导入进去了 而不是只导入我所需要的原始答案
而当我使用SS快捷键成功手动框选答案后 阅读界面的显示是正常的
![image](https://github.com/user-attachments/assets/2d12cf68-64c8-41db-8694-a5d5b35e0fd6)

但是使用一键导入到notion功能导入的笔记仍然是
![image](https://github.com/user-attachments/assets/7d42b788-edcf-4329-b0ec-5472b507fbe3)
默认页面的三个答案
而且由于我设置了加入稍后读自动导出到notion的功能 导致手动框选这个操作在此种情况下变的极为不便 

希望作者能够增加功能 默认情况下 阅读模式只获取链接点进去的第一个回答

**Comment by Kenshin** [comment]
当遇到阅读模式不佳时，可以使用 https://github.com/Kenshin/simpread/discussions/1554 提到的解决方案，或者使用 https://github.com/Kenshin/simpread/discussions/3340 里面提到的一些更高级方案 e.g. Live Editor

知乎的页面优化你可以试试 https://github.com/Kenshin/simpread/discussions/2861

>  默认情况下 阅读模式只获取链接点进去的第一个回答

如果你进入的页面 e.g. `https://www.zhihu.com/question/xxxx/answer/xxxx` 这显然是「问答」页。

可能有人希望简悦在进入知乎后直接获取全部内容...

所以，你可以试试第一个链接提到的方案。

**Comment by dadaomamao** [comment]
用鼠标所选加入阅读模式解决了

**Comment by Kenshin** [comment]
okay

至于你的需求我考虑下，毕竟你的表述（首位答案是最重要的）是合理的~

**Comment by Kenshin** [comment]
嗨

知乎辅助增强插件升级到 2.1.0 

仅显示正文中的第一个答案

![image](https://github.com/user-attachments/assets/8b02ac61-cd88-4ee4-9607-57c80af54a78)

> 默认论坛页效果（开启前）

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/e11fd2f6-b735-4b99-b918-aff7ccfae5c5">

>开启后

<img width="1296" alt="image" src="https://github.com/user-attachments/assets/2790a864-7dde-48ec-9441-5087827701a7">

安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

关联
---

https://github.com/Kenshin/simpread/issues/2860

***

我关闭这个 Issues 了，有任何疑问随时在这里讨论~
