### ISSUE TITLE
bing AI copliot

### ISSUE THREAD

**Issue by tianhuahao** [Kenshin/simpread#6752]
### 需要适配的新站

当打开bing AI copliot聊天界面的时候总是会误触进入阅读模式
还有今天我有大部分页面不会自动变红了，只有知乎主站会变红，怎么回事

**Comment by Kenshin** [comment]
> 聊天界面的时候总是会误触进入阅读模式

你是说打开 https://www.bing.com/chat 会自动进入阅读模式吗？误触是具体指什么？请截图或者视频演示给我看下。

> 我有大部分页面不会自动变红了

是否使用了同步助手的自动同步功能？如果是的话，看看能否正常打开选项页或稍后读页面？如果打不开的话，试试进入 http://localhost:7026/database/fixed 能否自行修复？

如果你没有使用同步助手的自动同步功能，随便进入一个网页 e.g https://sspai.com/post/69972 然后使用快捷键（如果你没有更改过阅读模式的快捷键的话） `a a` 进入阅读模式。

看看能否进入？如果仍无法进入的话，在使用快捷键前按照 https://github.com/Kenshin/simpread/discussions/6753 描述打开控制台，然后再使用快捷键 `a a`  如果有报错的话，请把报错信息给我看下。

**Comment by tianhuahao** [comment]
![image](https://github.com/user-attachments/assets/5f040553-90b6-4e83-a23d-c1db035694ef)


我直接用这个手动进入了
---
误触是指在键入某些字母的时候可能会误触发这个阅读模式
![image](https://github.com/user-attachments/assets/0ef021d1-72ed-40bc-b911-9cd0b754c1c3)

**Comment by Kenshin** [comment]
>  误触是指在键入某些字母的时候可能会误触发这个阅读模式

所以你到底误触了哪些？... 😂

#### 最简单的解决方案

你可以把 `bing.com` 加入到黑名单中，然后重启浏览器确保成功。

<img width="898" alt="image" src="https://github.com/user-attachments/assets/cbb65129-5072-4de9-9333-2b14fb1f75de">

**Comment by Kenshin** [comment]
嗨，太久没有继续回复，所以我关闭这个 Issues 了，有任何疑问可以随时在这里继续讨论~
