### ISSUE TITLE
清阅版很多网站不能使用

### ISSUE THREAD

**Issue by xiaowenlv** [Kenshin/simpread#676]
连少数派都提示无法使用，暴力猴的安装地址只会显示出脚本的内容不会安装

**Comment by Kenshin** [comment]
轻阅版由于使用了 UserScript 方式，所以在某些网站会出现错误（ 比如：你说的少数派... 
所以如果经常使用简悦的话，请安装**扩展版**。 😀

**Comment by xiaowenlv** [comment]
扩展很占资源，导致网页加载慢，另外设置 界面能否改成复选框或者有开还是关的提示，这样会更好操作。

**Comment by Kenshin** [comment]
抱歉，回复晚了。

扩展版会在页面加载完才会分析页面，所以不会导致网页加载变慢。

如果你觉得变慢了，有可能是电脑的性能有些问题，因为在分析页面的时候，自然会消耗一些性能。

如果认为电脑配置没有问题，仍存在你说的情况，请重新开启这个 issues 并告知具体的 URL
