### ISSUE TITLE
这种阅读模式问题，能通过live editor功能解决还是要适配吗？

### ISSUE THREAD

**Issue by felix2049lou** [Kenshin/simpread#6761]
### 描述这个错误

站点市场没有sspai的单独的适配，所以此文章内的表格怪怪的，图片不能像原来并排显示的方式的问题，能用live editor解决吗？还是要等直接适配？

### 复现步骤

图片排版情況simpread前(右)/simpread后(左)：

<img width="1666" alt="image" src="https://github.com/user-attachments/assets/32ebc43c-0f4b-49b6-b239-162faff75002">

表格排版情況simpread前(右)/simpread用字体大小45，版面寬度90，字距行距及单詞距0后(左)：

<img width="1650" alt="Screenshot 2024-10-11 at 12 02 51" src="https://github.com/user-attachments/assets/368cc31f-05d5-4187-a65f-b0f5c136d7b6">

### 其他相关说明

~~此文章也具注釋自動轉跳的內容。(笑😄)~~

### 操作系统

macOS 15.0.1 (24A348)

### 浏览器

Microsoft Edge Version 130.0.2835.2 (Official build) Dev(arm64)

### 发生问题的网址

https://sspai.com/post/91975

**Comment by Kenshin** [comment]
> 站点市场没有sspai的单独的适配

少数派的适配规则不在站点集市而是在官方主适配源

<img width="983" alt="image" src="https://github.com/user-attachments/assets/f6441fe4-b509-45b8-bff8-d467b338508c">

而图片并非横向排列而是竖向排列是「故意」这么做的，为了导出服务。

阅读模式的适配原则：去掉任何正文内可以互动的，并且让版面布局更适合浏览以及适合导出。

> 表格排版情況simpread前

你可以试试换个主题。

另外，你的截图版面太窄了，自然本身就会出现问题。 😂
