### ISSUE TITLE
无法使用激活码

### ISSUE THREAD

**Issue by zjnbwxq** [Kenshin/simpread#6762]
### 描述这个错误

提交激活码后，显示后台服务器出现了问题，点击重试（也可能是设置造成的问题，请查看Github issues置顶）

### 复现步骤

1. 在爱发电购买获得激活码后，进入插件
2. 10-100结束后显示激活失败

### 操作系统

Win10

### 浏览器

Chrome

### 发生问题的网址

chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#account

**Comment by zjnbwxq** [comment]
全部页面可使用之后搞定了

**Comment by Kenshin** [comment]
👍 解决就好

主要是你没有给简悦足够的权限造成的 😂

在出现「服务器」错误的页面会有明显提示。
