### ISSUE TITLE
一个网页的内容使用简悦的“阅读模式”后，几乎丢失所有内容

### ISSUE THREAD

**Issue by liuqinglong110** [Kenshin/simpread#6764]
### 描述这个错误

原始网页：https://vincentqin.tech/posts/superpoint/
使用简悦的“阅读模式”后，几乎丢失所有内容。

### 复现步骤

打开原始网页，待内容加载完成后（内容比较多，多等一下）。在网页上单击鼠标右键，选择简悦-->阅读模式。
发现几乎丢失所有内容。
![微信截图_20241013114020](https://github.com/user-attachments/assets/6b405ed7-4084-4f89-a16c-f42a0a5c8788)

### 操作系统

win10

### 浏览器

chrom浏览器

### 发生问题的网址

https://vincentqin.tech/posts/superpoint/

**Comment by liuqinglong110** [comment]
chrom浏览器信息：版本 129.0.6668.100（正式版本） （64 位）

**Comment by liuqinglong110** [comment]
但是我在同样格式的另一篇文章，阅读模式就是正常的。另一篇的网址：https://vincentqin.tech/posts/superglue/
两次使用的chrome浏览器信息：版本 129.0.6668.101（正式版本） （64 位）

**Comment by Kenshin** [comment]
嗨，在未适配的页面个别情况下会出现此问题，虽然不多见，但确实存在。

在阅读模式效果不良的页面，可以使用下面的方式

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/55da946b-e710-4b47-98c5-2464c9b405a4">

效果如下

<img width="1821" alt="image" src="https://github.com/user-attachments/assets/7fd6781d-5fb3-49ba-acd5-666ef67b3bc9">

**Comment by liuqinglong110** [comment]
> 嗨，在未适配的页面个别情况下会出现此问题，虽然不多见，但确实存在。
> 
> 在阅读模式效果不良的页面，可以使用下面的方式
> 
> <img alt="image" width="1046" src="https://private-user-images.githubusercontent.com/81074/376012044-55da946b-e710-4b47-98c5-2464c9b405a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTQzODgsIm5iZiI6MTcyODgxNDA4OCwicGF0aCI6Ii84MTA3NC8zNzYwMTIwNDQtNTVkYTk0NmItZTcxMC00YjQ3LTk4YzUtMjQ2NGM5YjQwNWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEwMDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjcwMjRmOGY4NTExZDBlNTZmZmNhY2U3OWFjYzFjYzk0ODhjODE3YTNmNGQxNmEyZTNmYjZhNTQyYzgyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zj2C76a5DCnFGSJjoTzjq44p8QqRZa7guSV8yWWk0Qg">
> 效果如下
> 
> <img alt="image" width="1821" src="https://private-user-images.githubusercontent.com/81074/376012092-7fd6781d-5fb3-49ba-acd5-666ef67b3bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTQzODgsIm5iZiI6MTcyODgxNDA4OCwicGF0aCI6Ii84MTA3NC8zNzYwMTIwOTItN2ZkNjc4MWQtNWZiMy00OWJhLWFjZDUtNjY2ZWY2N2IzYmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEwMDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwN2E4NjIyZjhhY2FlY2EzZmM5ODFjYmQwM2VkMTczODA0ZGI5ODczOGQxOGI5YjZlYjBlN2YwNTkwODBlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Rt7e8DJBn4MFQOHCj4fhGhrDM5A-eqlB0784vCKUwg">

嗯嗯，我按照您的建议，确实可以把文章内容变成阅读模式了。但是文章末尾的代码块内容全都变成了一行。这种情况有什么解决方法吗？
![Uploading 微信截图_20241013180953.png…]()

**Comment by Kenshin** [comment]
> 文章末尾的代码块内容全都变成了一行。这种情况有什么解决方法吗？

暂时没有 😂 代码段是一个比较「烦人」的问题，因为代码规则太多了，没法抽取既有规则。
