### ISSUE TITLE
图床插件将图片转为Based64问题

### ISSUE THREAD

**Issue by tfyicheng** [Kenshin/simpread#6765]
### 请描述你的建议或任何内容

遇到部分网站转换图片失败，右上角提示进度卡在第一张，控制台报错，情况如图
![20241013132729](https://github.com/user-attachments/assets/38c7a644-e120-4e69-b74f-91314e0cbb53)
使用网站例如：
https://juejin.cn/post/6844903991550181390#heading-4、
https://wiill.blog.csdn.net/article/details/88604270?utm_relevant_index=2
但同网站下也有转64正常的

### 补充说明

刚开始以为是图片太大或者网络问题导致进度卡住，建议转换失败可以给个提示

**Comment by Kenshin** [comment]
嗨，我测试了下图所示的方式是没问题的

<img width="724" alt="image" src="https://github.com/user-attachments/assets/693f9c9e-be10-4ee7-b090-104f1cf2edc3">

注意：留意你的界面是否跟我一致？如果不一致请升级你的图床插件。

**Comment by Kenshin** [comment]
使用 https://wiill.blog.csdn.net/article/details/88604270 按照上图导出时确实有问题，但也有出错提示。

不过可以使用下面的方式

<img width="694" alt="image" src="https://github.com/user-attachments/assets/e1aeb989-8a74-44a6-8f9a-df5c07246631">

**Comment by tfyicheng** [comment]
你好，因为需要图片本地化导入笔记，所以我使用的方式不是上传到图床，而是Base64图片本地化，即点击 仅将图片转换为 Based64 。插件是上周安装的应该是最新的。

**Comment by Kenshin** [comment]
https://juejin.cn/post/6844903991550181390 使用

<img width="382" alt="image" src="https://github.com/user-attachments/assets/6acf08b4-0814-4995-bfd2-b710f4c05446">

是没问题的，看下图

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/2f2a040e-194d-46e9-b91f-8cf841d8ca9d">

CSDN 不行，因为它的图片有 CROS 问题导致无法使用 Base64 方案。

如果你的掘金有问题，建议请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by tfyicheng** [comment]
好的，了解
