### ISSUE TITLE
Chrome 版本 129.0.6668.101（正式版本） （64 位）目前无法使用

### ISSUE THREAD

**Issue by Poluk2001** [Kenshin/simpread#6768]
### 描述这个错误

Windwos11下 Chrome版本 129.0.6668.101（正式版本） （64 位）目前无法使用，在谷歌扩展商店也无法使用，请问这个问题是和新版本Chrome不适配还是什么问题？

### 复现步骤

扩展商店“添加”按钮处于灰色状态，红色警告为“此扩展程序未遵循 Chrome 扩展程序的最佳实践，因此已无法再使用。”

### 操作系统

Windows11

### 浏览器

Chrome 129.0.6668.101（正式版本）64位

### 发生问题的网址

https://chromewebstore.google.com/detail/%E7%AE%80%E6%82%A6-simpread/ijllcpnolfcooahcekpamkbidhejabll?hl=zh-CN&utm_source=ext_sidebar

**Comment by Kenshin** [comment]
嗨，请不要担心。

我这边的版本跟你一致，请问你访问时是下图的效果吗？

![image](https://github.com/user-attachments/assets/4879fa62-b078-4afb-9e48-8bab116dfbd5)

如果是的话，请使用 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710 解决，除了这解决方案外，还有 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575747 和 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575760

如果不是的话，可正常安装。

***

关于这个现象的说明，可以看下 https://github.com/Kenshin/simpread/discussions/6633

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
