### ISSUE TITLE
chrome升级后插件不受支持

### ISSUE THREAD

**Issue by nullhat2** [Kenshin/simpread#6769]
### 描述这个错误

就google chrome升级后，插件不可用，说的什么“这个扩展不再可用，因为它不遵循Chrome扩展的最佳实践。”
![image](https://github.com/user-attachments/assets/ff8ab7cc-9671-491e-a2ba-b04c5f8984aa)

### 其他相关说明

![image](https://github.com/user-attachments/assets/ff8ab7cc-9671-491e-a2ba-b04c5f8984aa)

### 插件版本
简悦 - SimpRead 2.2.0.520

### 操作系统

windows11

### 浏览器

chrome 129.0.6668.100

### 发生问题的网址

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

**Comment by Poluk2001** [comment]
你好，最近我也遇到这个问题，今天作者给了回复，可根据这个办法解决（目前我已解决）：https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710

**其余解决办法**： https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575747 和 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575760

**原作者的话**：“关于这个现象的说明，可以看下 https://github.com/Kenshin/simpread/discussions/6633“

**Comment by Kenshin** [comment]
@Poluk2001 

谢谢提示，但我记得回复这个 Issues 了 😂

不知道为什么我的版本是一样的，但确没有问题。

不止如此 Chrome Beta 131 都没问题。

**Comment by Kenshin** [comment]
@nullhat2 

嗨，你的截图应该可以正常使用的。

**Comment by nullhat2** [comment]
> 你好，最近我也遇到这个问题，今天作者给了回复，可根据这个办法解决（目前我已解决）：[#6633 (comment)](https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710)
> 
> **其余解决办法**： [#6633 (comment)](https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575747) 和 [#6633 (comment)](https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575760)
> 
> **原作者的话**：“关于这个现象的说明，可以看下 [https://github.com/Kenshin/simpread/discussions/6633“](https://github.com/Kenshin/simpread/discussions/6633%E2%80%9C)
> 
> 关联 #6768

嗯，这个可以解决我的问题，非常感谢。

**Comment by nullhat2** [comment]
> @Poluk2001
> 
> 谢谢提示，但我记得回复这个 Issues 了 😂
> 
> 不知道为什么我的版本是一样的，但确没有问题。
> 
> 不止如此 Chrome Beta 131 都没问题。

这个我也感觉很奇怪，我家里的电脑都没问题的，公司的就出现了问题；
我记得当时chrome同时使用2个以上的用户，多个标签页进行网页测试，其中一个google的账户提示chrome可以升级，然后我就点击升级，他将所有的标签页全部关闭进行升级，升级完成后就提示上述问题了

**Comment by nullhat2** [comment]
> @nullhat2
> 
> 嗨，你的截图应该可以正常使用的。

https://github.com/Kenshin/simpread/issues/6768
我这边使用上述方法解决的问题，感谢大佬的回复
![e340b373e8e24e9f2a555512f714fac02062cb4e](https://github.com/user-attachments/assets/78047bed-b9ec-4486-9dd8-c7e37032e91e)

**Comment by Kenshin** [comment]
这种方式肯定能解决。

PS：你们都是 Windows 版吗？

**Comment by nullhat2** [comment]
> 这种方式肯定能解决。
> 
> PS：你们都是 Windows 版吗？

我这边是 Windows 11 家庭中文版 23H2

**Comment by Kenshin** [comment]
@nullhat2 

okay 我在咨询下其它用户~

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
