### ISSUE TITLE
ios上的知乎重排似乎不太好？

### ISSUE THREAD

**Issue by LoneFireBlossom** [Kenshin/simpread#677]
我因为想把知乎上的这个回答 https://www.zhihu.com/question/22470793 导出为好看些的PDF，今天刚刚找到这个插件，研究了一番买了JSBox。不过发现不太对：
![IMG_0558](https://user-images.githubusercontent.com/50087596/75771808-a6e0b800-5d85-11ea-90a1-b70df3a3e9d7.png)

这是我在电脑端chrome上启用阅读模式的情况：
![image](https://user-images.githubusercontent.com/50087596/75771652-5c5f3b80-5d85-11ea-9032-94f807cc0df7.png)

不知道有没有可能iPad端做到和PC端一样的效果呢？

**Comment by Kenshin** [comment]
谢谢反馈。

JSBox 与 扩展版 使用了一样的 **词法分析引擎**，所以它们对页面的解析能力是一样的。

但是由于某些网站在手机端的页面展示方式与 PC 端不一样，所以有可能出现你说的情况。

***

请详细告知你使用的 JSBox 简悦版本以及是通过 **阅读模式** 还是 **阅读器模式** ？
另外，如果是阅读模式，建议在页面彻底加载完毕后再进入阅读模式。

**Comment by LoneFireBlossom** [comment]
emmm，阅读模式和阅读器模式都这样

**Comment by Kenshin** [comment]
这么早就上来？

JSBox 和 对应简悦版本是什么？以及 iOS 设备版本是什么？

**Comment by LoneFireBlossom** [comment]
软件都是最新的，因为都是昨天刚安装的
系统是iPad os 13.3.1

**Comment by Kenshin** [comment]
JSBox 版简悦如果是通过官网安装的话，版本上就没有问题。
我一会详细看看。

方便的话，你再多试试一些页面。（看图来说，感觉不像是最新的简悦版本...

**Comment by LoneFireBlossom** [comment]
<img width="1366" alt="什么是「齐次」，「非齐次」，「线性」，「非线性」？ - 知乎" src="https://user-images.githubusercontent.com/50087596/75834830-1f805c80-5df8-11ea-85cc-b441f35f711e.png">
https://www.zhihu.com/question/19816504

**Comment by zhihaofans** [comment]
@Kenshin 你好，JSBox 版简悦无法识别[知乎日报的页面](https://daily.zhihu.com/story/9721241)，在Chrome版扩展和Safari阅读器视图上都是没问题的

**Comment by LoneFireBlossom** [comment]
不是，你这个问题应该另开一个issue吧……和我的无关呀，我的不是知乎日报

**Comment by Kenshin** [comment]
@zhihaofans 
我刚测试了下，确如 @LoneFireBlossom 所说，我也可以访问。
请确保安装了最新的 JSBox 版简悦。

另外 @LoneFireBlossom 提醒是对的，假设还是没有解决问题，请 **重开一个 issues** 反之就不需要了。 😀 

***

@LoneFireBlossom 
我好像知道你的问题了，知乎 mobile 页面加载的模式与 PC 端不太一样，所以你试着这样做

> 确保你需要页面的图片全部加载完毕（也就是滚动条拉到最低下），然后再进入简悦，再看看是否可以解决？

我找了个页面 https://zhuanlan.zhihu.com/p/31426458 下面是截图

![2020-03-07 11 05](https://user-images.githubusercontent.com/81074/76135635-b8ff7680-6063-11ea-9b36-73858ce7e83c.png)

图中几个黑色字体均是图片。

**Comment by LoneFireBlossom** [comment]
额，你试试我1楼的那个链接吧，确实不行，那个链接就两个回答，肯定都加载了啊

**Comment by Kenshin** [comment]
@LoneFireBlossom 

很奇怪，你给我的
https://www.zhihu.com/question/22470793
https://www.zhihu.com/question/19816504
这两个页面我均无法加载简悦，会直接 Alert 错误

而 https://zhuanlan.zhihu.com/p/31426458 以及类似的 知乎 · 专栏 的页面均可以打开，并且也没有发生你说的情况。

***

扩展版与 JSBox 共享同样的 **词法分析引擎**，进而它们的表现上应该是一样的。

最好的办法是，你看看我给你的知乎专栏页面是否可以打开，这样才好排查。

**Comment by LoneFireBlossom** [comment]
emmm，我只发了一个链接吧，为啥你说有两个呢。
下图是你发的专栏链接我分享到简悦（不是阅读器）的显示效果。
<img width="1366" alt="一文读懂Faster RCNN - 知乎" src="https://user-images.githubusercontent.com/50087596/76228747-1827db80-625c-11ea-8f5c-44a780798d44.png">

**Comment by Kenshin** [comment]
@LoneFireBlossom 

发了截图但是截图里面没有没有任何关于 **小图未居中**  的情况...

*** 

> 我只发了一个链接吧

另外一个链接 https://github.com/Kenshin/simpread/issues/677#issuecomment-594253605

**Comment by LoneFireBlossom** [comment]
哦哦，不好意思，因为不是蓝的所以看漏了
我还需要提交什么信息么

**Comment by Kenshin** [comment]
@LoneFireBlossom 

没事... 我的意思是

1. 你给出的两个 知乎链接 我无法打开（ 很奇怪的情况...

2. 请测试我给你的链接 https://zhuanlan.zhihu.com/p/31426458 看看在你那边是否有 **小图居中** 的情况...

因为第一条的缘故，所以只能让你来测试 **第二条** 是否也存在同样的问题。

***

PS1：我可以访问第二条（给出的链接）并且也未出现 **小图居中** 的问题。
PS2：虽然都是知乎的页面，但是它们的页面布局不一样，所以最好确认 **第二条** 是否也存在此问题。

**Comment by LoneFireBlossom** [comment]
是要上传这个吗？
![IMG_0666](https://user-images.githubusercontent.com/50087596/76631893-59322f80-657d-11ea-9cee-3dd20e8ad89d.png)
![IMG_0665](https://user-images.githubusercontent.com/50087596/76631897-5b948980-657d-11ea-93e8-687ad8a2fa37.png)

**Comment by Kenshin** [comment]
@LoneFireBlossom 

你给出的截图，很显然是 **图片未加载完造成** 的。

我之前已经说过了，在图片全部加载完，测试看看...

***

PS：正确情况下不需要理会图片是否加载完，简悦会自己判断。（ 但既然是排错，所以就要再图片加载完后进入简悦

**Comment by LoneFireBlossom** [comment]
不好意思，这次应该对了
<img width="1366" alt="一文读懂Faster RCNN - 知乎" src="https://user-images.githubusercontent.com/50087596/76683281-f94f8d80-663d-11ea-8887-7e4347f354ec.png">

**Comment by Kenshin** [comment]
@LoneFireBlossom 

真是神奇... 我在研究下吧，方便的话，也可以试试这个链接，在 iPad 上访问是否有问题？

https://en.wikipedia.org/wiki/Domain_adaptation

正常的话，应该是下面的效果

![image](https://user-images.githubusercontent.com/81074/76696622-6e67a500-66c8-11ea-94bc-f96c987df496.png)

**Comment by LoneFireBlossom** [comment]
emmm，我不是这个效果。这个页面的确加载了
<img width="1366" alt="Domain adaptation - Wikipedia" src="https://user-images.githubusercontent.com/50087596/76703116-f326e300-6709-11ea-8cc1-34dc07ee8a7c.png">

**Comment by Kenshin** [comment]
@LoneFireBlossom 
确认一下 简悦的版本吧… 我（强烈怀疑）你的版本不是最新的。

**Comment by LoneFireBlossom** [comment]
emmm的确是如此，我是1.0.2版本……好尴尬。我记得我是先在别的平台安装的，然后到官网又点了几次安装。所以这种安装是不能覆盖的么……
现在显示是1.0.3，这会儿对了。

**Comment by Kenshin** [comment]
我晕… 我最早就问过你版本的事情了！

竟然浪费了半个月时间… 🤣🤣🤣

解决就好，哈哈，要不请杯☕ 吧（玩笑），聊表抱歉之意。 😎

敬那些为此死去的脑细胞们… 😓

**Comment by LoneFireBlossom** [comment]
ok
这个理由我无法拒绝

**Comment by Kenshin** [comment]
@LoneFireBlossom 

开个玩笑，如果你觉得简悦确实能解决你的问题，请杯 ☕ 我也高兴~
