### ISSUE TITLE
导出到ob失败

### ISSUE THREAD

**Issue by DanShui-Yu** [Kenshin/simpread#6776]
### 描述这个错误

![image](https://github.com/user-attachments/assets/4171ff53-71f5-4701-b4be-2db1e0cd9583)
![image](https://github.com/user-attachments/assets/150699e6-9726-4c63-a7a3-cf46283d9e7f)

### 复现步骤

进入阅读模式，标注

### 其他相关说明

ob版本v1.7.4
html可正常导出，md不行

### 操作系统

windows

### 浏览器

chrome130.0.6723.59（正式版本） （64 位）

### 发生问题的网址

https://www.cn-healthcare.com/articlewm/20230225/content-1515897.html

**Comment by Kenshin** [comment]
😂

1. 你截屏的内容也不是 Console...  如何查看 Console 可以看下 https://github.com/Kenshin/simpread/discussions/6753

2. 这是 https://www.yuque.com/kenshin/simpread/fr8zo5 你使用方案的教程，可以自查下，一般情况下，大部分发生此问题都是因为路径设置错误，

**Comment by DanShui-Yu** [comment]
清除之后是空白，不清除是这样的

![image](https://github.com/user-attachments/assets/ca14e964-1d18-4036-8b6f-3aae50e1c861)

我没有改过路径设置，上个星期还是好的

**Comment by Kenshin** [comment]
> 清除之后是空白

清除了当然就是空白的 😂 我的意思是：先清除然后在操作，这时在 DevTools 上面的显示就是你操作后的。

当然，你截图的内容说明 Markdown 模板辅助增强插件没问题，如果是标注后产生的，说明自动化也没问题。

出问题的可能是导入到 Obsidian

> 我没有改过路径设置，上个星期还是好的

1. 试试访问 http://localhost:7027/ 看看是什么？

2. 看下导入到 Obsidian 插件与 Obsidian SimpRead Sync 里面的路径设置（截图给我）

3. 或者也可以把配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6776 然后在这里告诉我~

**Comment by DanShui-Yu** [comment]
> 试试访问 http://localhost:7027/ 看看是什么？

这个链接打不开

![image](https://github.com/user-attachments/assets/c5668b83-8bbc-4a9b-95b9-c9cbd147aa55)

![image](https://github.com/user-attachments/assets/aa7b08c0-f2b5-4b1e-bba0-9fca3d0ac2ec)

![image](https://github.com/user-attachments/assets/ccd3f083-e390-4c12-99bf-2dd77e59709f)

![image](https://github.com/user-attachments/assets/d3261596-9791-4897-a1d5-3e9cb69c805c)

**Comment by Kenshin** [comment]
> 链接打不开

说明 Obsidian SimpRead Sync 无法正常运行，看下 https://github.com/Kenshin/simpread/discussions/5601 能否解决？

链接中提到的问题是一个很老的问题了，除非是 23年5月份之后就没有使用过 Obsidian 可能出现此问题。否则新版都会自动解决。

另外一点，确保你的 Obsidian 库再运行时只有一个。

**Comment by DanShui-Yu** [comment]
似乎不是这个原因

![image](https://github.com/user-attachments/assets/4b7e872c-c3ae-41dd-b0ad-921419a32f30)

![image](https://github.com/user-attachments/assets/95ee3097-3ed1-441a-a61e-f6db7b4acc09)

我几乎每天都在使用Obsidian。用简悦时运行的库只有一个。

**Comment by DanShui-Yu** [comment]
破案了，用了i18n汉化，给改出问题了

**Comment by Kenshin** [comment]
😂😂😂😂

太不容易了，具体是什么问题？

我关闭这个 Issues 了，有问题随时讨论。

**Comment by DanShui-Yu** [comment]
反正插件目录打开之后是这样的

![image](https://github.com/user-attachments/assets/6393dc21-38ee-42d1-94fd-877fbe62b5f2)

`lang` 里面是

![image](https://github.com/user-attachments/assets/7039d3e8-1b5c-4a1c-b71f-b37b4fc4d2f2)

i18n地址如下：https://gitee.com/zero--two/obsidian-i18n-translation

**Comment by DanShui-Yu** [comment]
又不行了，只能到ob里手动同步

**Comment by Kenshin** [comment]
> 又不行了，只能到ob里手动同步

用个新库测试，排除法。

**Comment by DanShui-Yu** [comment]
用只装了简悦插件的新库测试，可以。但是发现手动同步只能同步出近期的几篇文章，更早之前的出不来了

**Comment by Kenshin** [comment]
> 但是发现手动同步只能同步出近期的几篇文章，更早之前的出不来了

<img width="795" alt="image" src="https://github.com/user-attachments/assets/9dc9219b-dda3-43f7-9379-1c73f8029224">

**Comment by DanShui-Yu** [comment]
原来如此。又发现一个新问题，想不起来html的导出地址设置在哪里改了😭

**Comment by DanShui-Yu** [comment]
太奇怪了。直接复制过去的插件文件夹，在新库里一点问题没有，老库就不行；在同步助手里改路径，html只认原本老库的路径md时灵时不灵。
现在就很邪门，html、md全文都能正常进老库，就是annote不行，手动同步也同不进来了

**Comment by DanShui-Yu** [comment]
绝了，这会儿又莫名其妙的都好了……
