### ISSUE TITLE
用配置文件登录没有任何反应

### ISSUE THREAD

**Issue by justKeven** [Kenshin/simpread#6778]
### 描述这个错误

1. 我之前购买了高级账户，后来丢失了，在新电脑找回了，得到了一个json配置文件，里面有uid和lisense
2. 当我点击登录→导入简悦配置文件登录，之后在旁边有消息弹出，但是无法登录成功
![image](https://github.com/user-attachments/assets/52db6062-6a73-459d-8b66-7f66975e56a5)

### 复现步骤

![image](https://github.com/user-attachments/assets/8be70645-f115-4ec8-8064-cc9326056807)

### 操作系统

window11

### 浏览器

chrome

### 发生问题的网址

1

**Comment by Kenshin** [comment]
> 里面有uid和lisense

这个文件不是用了「登陆」的…

你用文案编辑器打开它，然后找到 UID 使用 https://www.yuque.com/kenshin/simpread/pkq3d1 恢复你的高级账户权限。

**Comment by justKeven** [comment]
非常感谢，已解决

**Comment by Kenshin** [comment]
小事情，解决就好～
