### ISSUE TITLE
obsidian simpread sync同步报错

### ISSUE THREAD

**Issue by phantasy36** [Kenshin/simpread#6785]
### 描述这个错误

![photo_2024-10-26_11-10-44](https://github.com/user-attachments/assets/8499b563-3ef5-4d6e-82c5-0606ae2778d0)
[
![photo_2024-10-26_11-10-44](https://github.com/user-attachments/assets/1f472bb6-bb77-45dd-b08a-90988de122f6)
](url)
obsidian导出选项配置测试成功，但随即弹出错误导出失败。
![photo_2024-10-26_11-15-53](https://github.com/user-attachments/assets/0d748d0f-2f32-44a3-b3a3-2ea28097d9ec)

### 复现步骤

1.所有配置按照教程设置好了。然后加入到稍后阅读没问题。
2.但是无法自动激活保存到obsidian。手动执行报错。开始时配置的local reset api报错，换了obsidian simpread sync，一样。
3.测试配置服务，都没有问题。但是同步到obsidian就报错。
<img width="620" alt="2024-10-26_111819" src="https://github.com/user-attachments/assets/38f8e4b9-e886-4740-bfff-5e4ee57ce5c0">
[
<img width="535" alt="2024-10-26_111919" src="https://github.com/user-attachments/assets/23eaffcd-78f6-4024-9e64-c6c4025773d2">
](url)

### 操作系统

Windows 11

### 浏览器

edge 130.0.2849.46 (正式版本) (64 位)

### 发生问题的网址

https://www.zhihu.com/question/2109427028?utm_division=hot_list_page

**Comment by Kenshin** [comment]
看下图

<img width="813" alt="image" src="https://github.com/user-attachments/assets/65c65edc-cb24-46c9-9d02-ad6e5c8fc14b">

<img width="737" alt="image" src="https://github.com/user-attachments/assets/19589aa0-b329-41bc-a44f-353e065047fd">

这两个地方「明显」是你自己改动造成的 😂

**Comment by phantasy36** [comment]
> 这两个地方「明显」是你自己改动造成的 😂
按照你说的改了还是一样。
<img width="439" alt="2024-10-26_144217" src="https://github.com/user-attachments/assets/953e758c-13e6-403a-a71a-45bdb750f4d4">
<img width="563" alt="2024-10-26_144231" src="https://github.com/user-attachments/assets/ef5f9c70-013d-4e29-85e2-226169f0635b">

<img width="582" alt="2024-10-26_144322" src="https://github.com/user-attachments/assets/7050de17-3d81-4a44-b25d-14548b5925e9">
<img width="630" alt="2024-10-26_144247" src="https://github.com/user-attachments/assets/32000385-b060-4604-9080-8905c0dcc8eb">

**Comment by Kenshin** [comment]
<img width="452" alt="image" src="https://github.com/user-attachments/assets/23fb68f5-5fa7-437a-af44-178839977538">

展开上面随时的，另外，访问下 http://localhost:7027/ 看看是否如下图所示

<img width="362" alt="image" src="https://github.com/user-attachments/assets/2fd84b2c-78e4-4df8-a8b4-95f1fbdcde69">

**Comment by Kenshin** [comment]
提示下：

1. 修改完毕后建议重启浏览器 & Obsidian

2. 请在 https://www.ifanr.com/1604028 （这类相对正常的网页测试）

**Comment by phantasy36** [comment]
可能是我没有重启浏览器的原因。目前访问网页提示服务正在运行，也提示推到obsidian了。但是我没有在obsidian中找到。
<img width="621" alt="2024-10-26_174450" src="https://github.com/user-attachments/assets/dac3b275-418e-4ab7-ab74-7f9c8dbd420d">
打开obsidian中的链接提示报错。
<img width="428" alt="2024-10-26_174427" src="https://github.com/user-attachments/assets/9aa9165a-93a0-4ae3-b9b0-5663f0339a88">
obsidian中插件的路径设置都为“D:/Obsidian/HHYMC/00-收件箱/SimpRead”
<img width="503" alt="2024-10-26_174713" src="https://github.com/user-attachments/assets/e6c393d8-bd82-4afe-9c18-200a6eba469e">

**Comment by Kenshin** [comment]
你改了太多的地方，稍微运行起来都是奇迹 😂 

其它不说，随便找个：最后一个截图明显就是错的

<img width="775" alt="image" src="https://github.com/user-attachments/assets/02b0228d-2d83-41a6-bd27-5a52a4c3fddc">

在改动前，请先确定确定改动的设置是干什么的，每个设置都有详细说明。

还有，最好先根据官方的规则，确保可以运行再改动，否则很难调查，因为这套流程涉及了多个 App 的协作。

#### 建议

1. 这是教程 https://www.yuque.com/kenshin/simpread/ifioux 对比下跟你的区别，请先按照官方默认规则设置。

2. 如果是新用户的话，建议直接使用官方配置库方案 https://www.yuque.com/kenshin/simpread/wq35mh

**Comment by phantasy36** [comment]
感谢指导和提醒。让我发现了问题。不是你说的这个目录的问题。1.我浏览器插件设置的库和本身实际的库名称不对应，修改为我自己的库名了。2.我将Simpread文件夹移到了库的根目录和浏览器插件配置保持一致。这样就好了。

**Comment by Kenshin** [comment]
👍👍👍

大部分问题都出在：路径设置（尤其是 Windows 用户 😂 

所以一定要确保路径（尤其我指出的几处错误，要改对~

如果对图床有要求的话，可以试试 [图床插件](https://github.com/Kenshin/simpread/discussions/4306)

我关闭这个 Issues，有任何使用疑问可以随时沟通 ~

***

请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
