### ISSUE TITLE
代码高亮插件丢代码问题

### ISSUE THREAD

**Issue by hanley99** [Kenshin/simpread#679]
网页中的代码保存到notion中的时候，出现代码丢失的情况。
比如https://blog.51cto.com/andyxu/2137046 中有如下代码firewall-cmd --zone=drop --add-rich-rule="rule family="ipv4" source address="192.168.2.208" service name="ssh" accept"

保存到notion中为：
firewall-cmd --zone=drop --add-rich-rule="rule family="ipv4" source address="192.168.2.208" service

**Comment by Kenshin** [comment]
谢谢反馈~

导入到 Notion 是 Markdown 格式，你试着导出 Markdown 到本地，确认是否也存在一样的问题。

如果存在的话，应该是这个 Markdown 解析器出现了问题。

**Comment by hanley99** [comment]
从notion导出到本地后也是缺失的。

**Comment by Kenshin** [comment]
emmm 

谢谢测试，这样的话，即便修复了，也只能下个版本了。

我明天看看是什么问题，确实很少发生这种情况。

**Comment by Kenshin** [comment]
抱歉，漏掉了 re-check...

刚才测试了下，**导出 Markdown 到本地**，而不是 **从 notion 导出到本地** 是没有问题的。

所以问题应该出在 Notion ... 你可以自己试试导出 Markdown 到本地。

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 [0.0.6](https://github.com/Kenshin/simpread/issues/500) 修复了类似的问题，但原网页无法打开了，所以我先关闭此 Issues 了。

请升级你的代码高亮插件，如又再次发生，请再告诉我。谢谢反馈~

***

更新方法：点击上面链接中的 **安装当前插件** 即可。
