### ISSUE TITLE
保存为html后，双击打开本地html快照，图片无法显示。

### ISSUE THREAD

**Issue by UIyidu9322** [Kenshin/simpread#6790]
### 描述这个错误

**问题一**：保存为html后，双击打开本地html快照，图片无法显示。
![image](https://github.com/user-attachments/assets/7236ea19-53a6-49f6-823b-e6f3815aa7c3)

**问题二**：知乎上某篇带gif的图，点击简悦按钮后进入gif全部不动了。在稍后读中会出现一些奇怪的字符。
![image](https://github.com/user-attachments/assets/d2586ab3-11f0-4de6-85e0-248983b04efd)

### 复现步骤

进入网页。
点击简悦按钮。
导出为html。

### 操作系统

win11

### 浏览器

谷歌 Version 130.0.6723.70 (Official Build) (64-bit)

### 发生问题的网址

https://zhuanlan.zhihu.com/p/36365328

**Comment by UIyidu9322** [comment]
看了之前的issuse，知乎有个专门的插件，可以解决这个问题。

**Comment by Kenshin** [comment]
👍 

恭喜自救成功 😄

今天有些事情 Issues 积攒到现在才回复 😂
