### ISSUE TITLE
标注功能一定要进入阅读模式才行么？

### ISSUE THREAD

**Issue by fanrongqitiancai** [Kenshin/simpread#6792]
### 请描述你的建议或任何内容

我喜欢在原网页上使用标注功能，我不想修改原网页的布局，如何才能在原网页使用标注功能？

**Comment by Kenshin** [comment]
嗨，只能在阅读模式中标注，你可以理解简悦的标注系统 === Web 版的 PDF 标注系统。

简悦的标注是建立在深度阅读诉求的前提下才建议使用简悦~

也就是说，简悦的全部功能都以阅读模式为基准。

原文标注因为没有上下文，所以并没有实际意义。

**Comment by fanrongqitiancai** [comment]
阅读模式会 改变原网页的布局呀，这个原网页批注功能，是否能够增加呀？急切需要。:)

**Comment by Kenshin** [comment]
暂时不会考虑。😄

**Comment by fanrongqitiancai** [comment]
这个功能很适用啊！！！代码修改的部分很多么？
