### ISSUE TITLE
notion页面无法滚动

### ISSUE THREAD

**Issue by hellolgg** [Kenshin/simpread#6795]
### 描述这个错误

在notion页面打开阅读模式，页面无法滚动，鼠标滚动无效。下面是页面链接：
https://rabbit-hole.notion.site/ed67157ce6cd4c78b89aeff33ed37598?p=f7398b215e4c43e99f127a79dde97e80&pm=s

### 复现步骤

在notion页面打开阅读模式，页面无法滚动，鼠标滚动无效。

### 操作系统

WINDOWS

### 浏览器

EDGE

### 发生问题的网址

https://rabbit-hole.notion.site/ed67157ce6cd4c78b89aeff33ed37598?p=f7398b215e4c43e99f127a79dde97e80&pm=s

**Comment by Kenshin** [comment]
解决方案 https://simpread.ksria.cn/plugins/details/xZVbwW4C5A

另外，在 Notion 使用阅读模式，建议使用 https://github.com/Kenshin/simpread/discussions/2106 此方案。

**Comment by hellolgg** [comment]
谢谢，问题已解决。

**Comment by Kenshin** [comment]
👍 解决就好~

我关闭这个 issues 了。

如果觉得好用，请帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍
