### ISSUE TITLE
sspai.com 的文章图片好像都下载不下来了

### ISSUE THREAD

**Issue by iblogc** [Kenshin/simpread#6799]
### 描述这个错误

文章地址：https://sspai.com/post/93065
不管是导出成html、pdf还是【导入md+assets到Obsidian】，图片都下载失败，测试了一下另一个网站是正常的。
导出用的是同步助手方案
![image](https://github.com/user-attachments/assets/fe379f1d-37ee-4798-8328-fe69b5d31981)
![image](https://github.com/user-attachments/assets/8dc85734-8eb0-40c4-8274-af01ac143300)

### 复现步骤

1. 打开文章页后进入简悦的阅读模式
2. 使用简悦里的导出功能

### 操作系统

windows 11

### 浏览器

Chrome 版本 130.0.6723.71（正式版本） （64 位）

### 发生问题的网址

https://sspai.com/post/93065

**Comment by Kenshin** [comment]
嗨，你需要使用 https://github.com/Kenshin/simpread/discussions/6579 才能解决~

这个「问题（及解决方案）」已经好几个月了 😂

**Comment by iblogc** [comment]
@Kenshin 装了【离线下载辅助增强】没有出现对应的选项菜单
![image](https://github.com/user-attachments/assets/bb1ec34d-f896-4a8a-ba85-031284fe4d2e)
![image](https://github.com/user-attachments/assets/45cabd3d-e07f-4c37-8dfa-ead79a490604)

**Comment by Kenshin** [comment]
按顺序导入（我不确定是否这么做了，只是提示下~

<img width="500" alt="image" src="https://github.com/user-attachments/assets/7df7e96d-ef43-44c0-9c4c-86bbc877dd56">

如果不是上面的问题，看下图

<img width="494" alt="image" src="https://github.com/user-attachments/assets/e96eeb78-421b-4a46-8a12-f1ae7bcebe35">

注意：在步骤2使用前，建议先手动备份 simpread_config.json 以免出现问题~

***

PS：是否使用 Obsidian 导出？如果是的话，不需要这个插件，直接使用导入到 Obsidian~

PPS：好久没有看到你提 Issues~

**Comment by Kenshin** [comment]
嗨，不知道是否解决了？

**Comment by iblogc** [comment]
> 嗨，不知道是否解决了？
@Kenshin 看来我以前提的 issues 有点多，让大佬记住了，哈哈😂。
解决了，之前忘了【导入当前插件】这一步操作了。不过这样的话，带图片 basse64 的md文件就有大了，有些 md 软件（如 Typora）就会因为 md 文件太大打不开。是不是后面可以再接一步，把带图片 base 64 的md 转成 md+assets。像我自己现在本地是有个脚本，每次从简悦导出离线 html 后，自动把离线html（内容里带了图片base64）里的图片 base64 转为图片文件放到html同名文件夹里，再把html里<img>标签的src更新为文件路径。现在导出的这个带 base64 的 md 文件是不是可以用样的逻辑通过同步助手来处理。

![image](https://github.com/user-attachments/assets/ea6fee60-15a5-4290-b2d6-37ab4451b38e)

**Comment by Kenshin** [comment]
> 是不是后面可以再接一步，把带图片 base 64 的md 转成 md+assets。

你可以试试 https://github.com/Kenshin/simpread/discussions/4041

同时导入到 Obsidian 也可以实现。

***

> 看来我以前提的 issues 有点多

一般跟我交流比较多的用户 ID 我都有印象。

**Comment by iblogc** [comment]
> 你可以试试 https://github.com/Kenshin/simpread/discussions/4041

这个我一直在用，就是因为这个导出不了  sspai 网站图片才用了这个 离线下载辅助增强。我意思是 离线下载辅助是不是也可以做到 md+assets，而不是 md+base64?

**Comment by Kenshin** [comment]
新版可以 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920120

仔细看这个链接的说明～

**Comment by iblogc** [comment]
啊，我蒙了啊。我最开始是说在 sspai 用 导入md+assets到Obsidian 导出图片失败，你和说我用 离线下载辅助增强 插件解决，我用这了这插件后发现下载下来的图片是base64形式放在md文件中，我说可以再做一步把base64再转成图片文件做到和 导入md+assets到Obsidian 一样的效果。然后你说用 导入md+assets到Obsidian 可以做到。😂给我绕回来了。

**Comment by Kenshin** [comment]
> 导入到 Obsidian 的选项

<img width="734" alt="image" src="https://github.com/user-attachments/assets/5e1940bf-2121-4373-88b8-a1fb13356181">

> assets + md 方案的选项

<img width="533" alt="image" src="https://github.com/user-attachments/assets/9164ebbc-0573-49d9-a151-72c1273e2313">

***

上述都是可以正常保存少数派的图片。

如果你的设置界面跟我的不一样，说明插件该升级了 😂

**Comment by iblogc** [comment]
搞定了， 感谢🙏

**Comment by iblogc** [comment]
> > 导入到 Obsidian 的选项
> 
> <img alt="image" width="734" src="https://private-user-images.githubusercontent.com/81074/382456880-5e1940bf-2121-4373-88b8-a1fb13356181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzQxMTgsIm5iZiI6MTczMDUzMzgxOCwicGF0aCI6Ii84MTA3NC8zODI0NTY4ODAtNWUxOTQwYmYtMjEyMS00MzczLTg4YjgtYTFmYjEzMzU2MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA3NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjYxYmI1ZGQxZTg0ZjQ0NDkzNzViZTZiYjRiMDkyMzM2OTY4ZjcwOTBhODlmYzc4NGQxYjU4MTg1NmMwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5TDOf15pOulImKFMC_Ttls3ZgRVUovDbL_vOhFWkhrE">
> > assets + md 方案的选项
> 
> <img alt="image" width="533" src="https://private-user-images.githubusercontent.com/81074/382456913-9164ebbc-0573-49d9-a151-72c1273e2313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzQxMTgsIm5iZiI6MTczMDUzMzgxOCwicGF0aCI6Ii84MTA3NC8zODI0NTY5MTMtOTE2NGViYmMtMDU3My00OWQ5LWExNTEtNzJjMTI3M2UyMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA3NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTgxZjIzOTFmMWJiY2FmZjM0M2M0YzJlNzZlMDU1MjQ0OGZjMWY5YzFiOWRmYmIzYzQ1MzMzZjdiYmMwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RhdGuTGnk6BA3pkarcWZuoiLtPK3Lozl1aFDJa8Zu9k">
> 上述都是可以正常保存少数派的图片。
> 
> 如果你的设置界面跟我的不一样，说明插件该升级了 😂

搞定了， 感谢🙏

**Comment by Kenshin** [comment]
😂

果然是没有升级插件造成的~

**Comment by iblogc** [comment]
不是，我之前以为这个base64就是把图片转成base64，而不是最终转成附件下载，没仔细看说明。😂

**Comment by Kenshin** [comment]
> 不是，我之前以为这个base64就是把图片转成base64，而不是最终转成附件下载，没仔细看说明。😂

😂😂😂 （我也没太仔细看你的问题，就...绕来绕去

**Comment by iblogc** [comment]
@Kenshin 好的，感谢，解决了

**Comment by Kenshin** [comment]
😂 没事~

其实... 两天前就应该可以一次性解决  🌚  😅

**Comment by Kenshin** [comment]
嗨

同步助手 1.3.0 发布了，解决了少数派等网站无法使用保存图片到本地的问题。

md + assets 插件更新到了 1.2.0 增加了自定义图片保存路径的功能，细节请看 https://github.com/Kenshin/simpread/discussions/4041#discussioncomment-3920696 里面提到的 **5️⃣ relative path**

注意：此功能需要配套同步助手 1.3.0  [下载地址](https://simpread.pro/docs/#/Sync?id=%E4%B8%8B%E8%BD%BD) & [更新日志](https://simpreadpublish.notion.site/2482effc334e4df8aa3aac7da8bb8059?pvs=25#278907a65f5880abb3b0d1c7aae9e3fd)

关联 https://github.com/Kenshin/simpread/issues/4042

注意：接下来几天内会发布导入到 Obsidian 2.0.0 版，发布后我会在这里再通知下~
