### ISSUE TITLE
建议添加 META 标签主动适配功能

### ISSUE THREAD

**Issue by osdu** [Kenshin/simpread#68]
建议添加 META 标签主动适配功能，由站点主动适配，而不需要simpread手动维护站点列表，这个尤其适用于中小网站

**Comment by Kenshin** [comment]
这个想法不错，记到 `TO-DO` 里面，由于 `1.0.3` 已经进入 release 阶段，所以功能冻结了，下个版本加入此功能。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `主动适配阅读模式` 详细请看 [主动适配阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%BB%E5%8A%A8%E9%80%82%E9%85%8D%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)
