### ISSUE TITLE
图标一直是灰色

### ISSUE THREAD

**Issue by UIyidu9322** [Kenshin/simpread#680]
更新简悦之后打开之前保存在稍后读的里面的文章，想要再打开简悦图标，打不开了，一直是灰色。
打开新手阅读里面的示范文章链接(https://sspai.com/post/39491)也是灰图标。
不知道是不是那里设置出问题了，我用的是谷歌浏览器。
感谢作者的努力，感谢答疑！

**Comment by Kenshin** [comment]
1. 选项页 → 高级设定 → 黑名单 里面有什么内容？把黑名单清空

2. 试试是否好使？

3. 如果不好使，导出配置文件

4. 清除数据

5. 看看右上角的 icon 是否为灰色

6. 如果步骤 4 没有问题的话，应该是你的配置文件出现了问题。最好对比下两个配置文件有什么区别？

 😀

**Comment by UIyidu9322** [comment]
感谢！
我按照你说的导出配置文件，然后清除了数据，再导入之后可以正确显示了。
再次感谢你的回答。
😀

**Comment by Kenshin** [comment]
搞定就好，或许是误操作导致小概率 Bug 造成的。 😂
