### ISSUE TITLE
使用简阅转为markdown格式时代码块有一部分没有提取

### ISSUE THREAD

**Issue by lqstc** [Kenshin/simpread#6800]
### 描述这个错误

我使用简阅将掘金的一篇文章转为markdown时，代码块中有一小段没有提取出来。

### 复现步骤

1、掘金文章url：https://juejin.cn/post/7247151913437937701
2、进入简阅的阅读模式后，点击“动作”，再点击“导出为markdown”
3、使用obsidian和typora打开，有一小段均不显示
<img width="1918" alt="Snipaste_2024-11-02_15-51-05" src="https://github.com/user-attachments/assets/f4e18339-3be4-4d49-bc0b-62c83945e777">
<img width="927" alt="Snipaste_2024-11-02_15-52-53" src="https://github.com/user-attachments/assets/8db3a1f0-8253-4410-853e-4cee565cf20e">
<img width="1191" alt="Snipaste_2024-11-02_15-54-23" src="https://github.com/user-attachments/assets/7c2c7ab5-9ccf-46a1-a5e6-d36cafd45a28">

### 操作系统

windows 11 24H2

### 浏览器

chrome 130.0.6723.92

### 发生问题的网址

https://juejin.cn/post/7247151913437937701

**Comment by Kenshin** [comment]
> 代码块中有一小段没有提取出来。

阅读模式正常吗？

PS：这个现象算是预期吧 😂 代码段的提取没有太好的方案。

**Comment by lqstc** [comment]
> > 代码块中有一小段没有提取出来。
> 
> 阅读模式正常吗？
> 
> PS：这个现象算是预期吧 😂 代码段的提取没有太好的方案。

嗯嗯，阅读模式显示是完整的，第一张图片就是阅读模式的截图🥳，感谢大佬的回复

**Comment by Kenshin** [comment]
> 嗯嗯，阅读模式显示是完整的，第一张图片就是阅读模式的截图

抱歉，看图不仔细 😂

我一会看下，一般情况下这类问题都是个例，也「很难」完美修复~

**Comment by lqstc** [comment]
> > 嗯嗯，阅读模式显示是完整的，第一张图片就是阅读模式的截图
> 
> 抱歉，看图不仔细 😂
> 
> 我一会看下，一般情况下这类问题都是个例，也「很难」完美修复~

好的，感谢🥳

**Comment by Kenshin** [comment]
okay 已确定~

代码段的问题会集中在 #500 并关闭此 Issues 修复后会通知你~
