### ISSUE TITLE
阅读助手配置了aip报错

### ISSUE THREAD

**Issue by zlxuan** [Kenshin/simpread#6801]
### 描述这个错误

阅读助手配置了aip报错，请问这是什么问题？
![Snipaste_2024-11-02_16-24-41](https://github.com/user-attachments/assets/59eaf1ef-af15-42b3-a41a-f32a75bc8349)

### 复现步骤

1. 阅读助手配置了aip报错

### 操作系统

windows 11

### 浏览器

Chrome 版本 111.0.5563.147（正式版本） （64 位）

### 发生问题的网址

无

**Comment by Kenshin** [comment]
emmm

你这个 Token 是 OpenAI 官方的吗？错误代码的说明

<img width="807" alt="image" src="https://github.com/user-attachments/assets/2d0082f5-74ef-4293-95a5-57995a41d422">

**Comment by zlxuan** [comment]
> emmm
> 
> 你这个 Token 是 OpenAI 官方的吗？错误代码的说明
> 
> <img alt="image" width="807" src="https://private-user-images.githubusercontent.com/81074/382459242-2d0082f5-74ef-4293-95a5-57995a41d422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzcwMjYsIm5iZiI6MTczMDUzNjcyNiwicGF0aCI6Ii84MTA3NC8zODI0NTkyNDItMmQwMDgyZjUtNzRlZi00MjkzLTk1YTUtNTc5OTVhNDFkNDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA4Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmY2IyODU3NjFjNDE2ZGZlZWQ5NzFjNzI2NzJhODliMzA5ZTNmODdiYjExMGRkZjYzYzgxMzBmYjg4MWIwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S6naxP7Wi_0cQeKTUpsvTp98Q4FvwaUwszAUWkuNqY8">

是官方的，我刚生成的key
![Snipaste_2024-11-02_16-41-02](https://github.com/user-attachments/assets/09dbdd80-93fe-4f5e-8381-dcc50b208b02)

**Comment by Kenshin** [comment]
有点意思（奇怪）...

方便把 Token 给我测试下吗？

方便的话请发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6801

然后在这里告诉我，我一会或者明天测试下~

**Comment by zlxuan** [comment]
已发送邮箱，有空麻烦查收一下

**Comment by Kenshin** [comment]
okay 看到了，有后续会在这里回复。

PS：为什么你的 Token 这么长 😂

**Comment by Kenshin** [comment]
https://platform.openai.com/docs/guides/error-codes/api-errors

原因很简单

<img width="748" alt="image" src="https://github.com/user-attachments/assets/c7568cfb-e615-46b0-a973-f31506035ea3">

我使用简悦的全文翻译插件帮你翻译了下（也是调用了 OpenAI 方案）

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/dd0d556a-05fd-4301-a19f-f254304ce2c4">

***

PS：你可以试试使用其它使用 OpenAI 的服务来测试你的 Token 😂

PPS：你可以试试简悦提供你的两种解决方案

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/822c8ba1-d926-4fd6-87ff-764684b91b61">

例如 SiliconFlow 方案 https://github.com/Kenshin/simpread/discussions/5158#discussioncomment-10354289

**Comment by zlxuan** [comment]
好的吧，谢谢，是说没有试用额度吗？但是除了这个今天刚注册的key并没有再调用过api了，看了调用情况也都是0😂

**Comment by Kenshin** [comment]
> 是说没有试用额度吗？但是除了这个今天刚注册的key并没有再调用过api了

我记得（不太确定）新注册的 OpenAI 早就没有 5$ 的额度了（有这个额度的都是早期用户。

PS：其实可以考虑阅读助手提供的两种方案。

我关闭这个 Issues 了，有任何问题随时在这里讨论~
