### ISSUE TITLE
【功能咨询】标注后自动同步到语雀了但是设置的自动同步不是这个模式

### ISSUE THREAD

**Issue by elaine-lollipop** [Kenshin/simpread#6803]
### 请描述你的建议或任何内容

1）我设置的自动同步是，加入稍后读，同步到语雀，但是现在在阅读界面，进行标注就提示同步到了语雀，我理解我还没加入稍后读。不知道是不是哪里有问题。
2）另外再咨询个功能，如果换电脑了，也是用的同样的账号登录chrome，我的语雀的高级账户如何同步呢？之前升级过高级账户后，因为插件或者电脑问题，点插件的选项一直出不来，只好删除了插件再登录，使用恢复高级账户功能，次数只剩下1次了，这个后续有什么影响吗？如果不通过这剩下的1次去做同步，怎么恢复高级账户呢？
3）还有个问题，我看了下反馈问题或者咨询的渠道，除了提issue，再就是电报群，这都有上网门槛啊，有没有国内正常能用的渠道？

**Comment by Kenshin** [comment]
> 我设置的自动同步是，加入稍后读，同步到语雀，但是现在在阅读界面，进行标注就提示同步到了语雀，我理解我还没加入稍后读。不知道是不是哪里有问题。

首次标注时，会自动加入稍后读，因此也会同步到语雀。
非首次标注（也就是当前即为稍后读模式），如果也同步到语雀，那就说明你的自动化设置了 **标注 → 语雀**，请更改下。

<img width="893" alt="image" src="https://github.com/user-attachments/assets/9bc89c7b-69a4-41dd-855e-3d42ff9060d9">

> 如果换电脑了，也是用的同样的账号登录chrome，我的语雀的高级账户如何同步呢？

简悦有自己的 [同步方案](https://simpread.pro/docs/#/%E5%90%8C%E6%AD%A5)

> 因为插件或者电脑问题，点插件的选项一直出不来，只好删除了插件再登录

插件无法同步（因为插件太大了），所以目前的方案是：导入新设备后（通过配置文件，选项页 → 共通 → 导入配置文件）的方式导入后，需要手动导入插件（选项页 → 插件管理 → 从配置文件导入插件）

注意：插件的配置可以同步（无法同步的仅仅只是插件本身）

> 还有个问题，我看了下反馈问题或者咨询的渠道，除了提issue，再就是电报群，这都有上网门槛啊，有没有国内正常能用的渠道？

Issues 国内应该可以使用，如果你有更好的反馈方案，可以告诉我。（除各种群外）

https://simpread.pro/subscribe 右下角有个 QQ 频道，也可以反馈

**Comment by Kenshin** [comment]
> 有些页面字体有加粗、标颜色或者下划线，进入阅读模式以后这些都丢掉了，不太方面查阅，这个怎么保留呢？（如下图）

试试更换不同的主题，或者提供下截图对应的 URL

一般来说这种情况多见于公众号，如果是的话，可以考虑使用这个插件 https://github.com/Kenshin/simpread/discussions/5851 解决。

> 有些图片过大，我查了下插件，只有无图的插件，没有控制图片大小的插件

https://github.com/Kenshin/simpread/discussions/1598

**Comment by elaine-lollipop** [comment]
感谢回复！
公众号优化这个插件已经装过。我这个文章是三联中读的一个专栏，我提供链接估计也打不开，需要是付费会员。
我也试了下这个公众号优化插件，也都开启了，好像没有效果，我也没有找到把当前页面加入优化范围的设置的地方。

**Comment by Kenshin** [comment]
> 我这个文章是三联中读的一个专栏，我提供链接估计也打不开，需要是付费会员

那暂时就没办法了 😂 

> 这个公众号优化插件，也都开启了，好像没有效果

开启前和开启后在界面上肯定不一样

> 我也没有找到把当前页面加入优化范围的设置的地方。

建议看下这个插件的文档说明，如果使用了同步助手的自动同步功能，需要使用 https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C 安装插件。

**Comment by Kenshin** [comment]
> 用这个插件是能看到区别的，如果是非公众号文章（文章地址非mp.wexin.qq.com这种），就没法使用了，我也阅读了插件的说明，并没有针对非公众号文章的优化使用说明。

😂 这个插件的名字说明，它只针对于公众号，其它当然不行了。

<img width="630" alt="image" src="https://github.com/user-attachments/assets/1ebd5349-6498-4c7b-a378-21ce90446174">

我以为你提到的这个页面的问题也是公众号...
