### ISSUE TITLE
关于腾讯问卷的疑问

### ISSUE THREAD

**Issue by Jedmin** [Kenshin/simpread#6807]
### 请描述你的建议或任何内容

嗨，我的兑换码还没收到，用的腾讯问卷方式买的，麻烦看下怎么肥事

**Comment by Kenshin** [comment]
嗨，腾讯问卷在不是实时发送兑换码，在付款前已经详细告知，大概 48 小时左右，因为是半人工，一般情况下是 48 小时以内，偶尔会超过。

今天晚上 19 点前你会收到兑换码的 Email ~

**Comment by Jedmin** [comment]
👌感谢



发自我的iPhone


------------------ 原始邮件 ------------------
From: Kenshin Wang ***@***.***&gt;
发送时间: 11/08/2024, 10:35
To: Kenshin/simpread ***@***.***&gt;
抄送: Jedmin ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Kenshin/simpread] 关于腾讯问卷的疑问 (Issue #6807)





 
嗨，腾讯问卷在不是实时发送兑换码，在付款前已经详细告知，大概 48 小时左右，因为是半人工，一般情况下是 48 小时以内，偶尔会超过。
 
今天晚上 19 点前你会收到兑换码的 Email ~

**Comment by Kenshin** [comment]
小事情~
