### ISSUE TITLE
导出离线html没有对应快捷键

### ISSUE THREAD

**Issue by feiyi1019** [Kenshin/simpread#681]
现在用quicker 结合简约，发现导出 离线html没有快捷键支持啊，可以加进去吗
普通html不含图，容易失效啊

**Comment by Kenshin** [comment]
离线下载为 HTML 包含了快捷键操作 → `o h`

进入阅读模式 → 快捷键 `s r` → 看下左下角的快捷键一览。

如果解决了你的问题，请关闭 issues  😀

**Comment by feiyi1019** [comment]
非常感谢高效回复，我在帮助说明里面看到快捷键一览表的，但是没有离线的，你说这个进入方式在chrome 安装插件没发现。我再琢磨琢磨。

**Comment by Kenshin** [comment]
我没理解你的意思，快捷键无法使用吗？

**Comment by feiyi1019** [comment]
https://i.loli.net/2018/09/03/5b8ca8916b26a.png
这个是在帮助这里看到的快捷键列表

我是新手，第一次使用，原来按住，号可以出现快捷键列表，官方的说明里
是这样写的： 所以有点懵
几个主要的快捷键：
, - 帮助；

**Comment by Kenshin** [comment]
哦，抱歉。

之前说的 **进入阅读模式 → 快捷键 s r → 看下左下角的快捷键一览。** 少了一个步骤 → **按 `,`**

正确的步骤 → 

> 进入阅读模式 → 快捷键 s r → 按 `,` → 看下左下角的快捷键一览。

***

另外，文档中的这个截图可能 **年久失修** 了。 😂

**Comment by feiyi1019** [comment]
还有问题请教下大神
我发现图片高度闲置了最高620px，这个有办法调整吗，有很多网页，图片是超高的，现在全部620，图片都变小了。
可以通过自定义css 调整图片高度吗？
请指点，多谢多谢！

**Comment by Kenshin** [comment]
你可以试试这个插件 👉 https://simpread.ksria.cn/plugins/details/VQOZdNET2d
