### ISSUE TITLE
插件显示已适配但未抓取正文内容

### ISSUE THREAD

**Issue by HopeLightning** [Kenshin/simpread#6810]
### 描述这个错误

如相关说明内的图片 阅读模式下只抓去了与正文无关的内容。

### 复现步骤

1 清除第三方适配的情况下 进入阅读模式——未抓取正文
2 检索第三方适配后（搜索dedao），将该站点http*://www.dedao.cn/article/* 加入第三方列表后进入阅读模式，还是未适配

### 其他相关说明

主要用于阅读课程和听书的文章内容，该站点阅读模式下仅排版了 文章开头和网页页尾的内容，正文未抓取
![Screenshot - 2024-11-11 23 57 54](https://github.com/user-attachments/assets/84e5e6ab-70d1-4517-8389-204d198495ba)

### 操作系统

Window 11

### 浏览器

Version 130.0.6723.117 (Official Build) (64-bit)

### 发生问题的网址

https://www.dedao.cn/course/detail?id=ZWyMAOLnR4xJ1vqsODX65QaE8YG29k

**Comment by Kenshin** [comment]
嗨，我看到你 Close 这个 Issues 了？是解决了？还是？

> 问题1

可以考虑使用 https://github.com/Kenshin/simpread/discussions/1554 提到的方案。

不过，一般有这种「付费墙」类的页面，简悦是不会主动适配的。

> 问题2

你可以试试切换不同的源（假设有的话）

<img width="477" alt="image" src="https://github.com/user-attachments/assets/a6204043-d0bf-408f-947d-2815179c7d5b">

**Comment by HopeLightning** [comment]
> 嗨，我看到你 Close 这个 Issues 了？是解决了？还是？
> 
> > 问题1
> 
> 可以考虑使用 #1554 提到的方案。
> 
> 不过，一般有这种「付费墙」类的页面，简悦是不会主动适配的。
> 
> > 问题2
> 
> 你可以试试切换不同的源（假设有的话）
> 
> <img alt="image" width="477" src="https://private-user-images.githubusercontent.com/81074/385123519-a6204043-d0bf-408f-947d-2815179c7d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTYyMTIsIm5iZiI6MTczMTM5NTkxMiwicGF0aCI6Ii84MTA3NC8zODUxMjM1MTktYTYyMDQwNDMtZDBiZi00MDhmLTk0N2QtMjgxNTE3OWM3ZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA3MTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjI4Zjk4YzU5Y2ZjN2NjZjI2ZjNmMWY1ZjhkMWEwZGYxNzgyZWU4MmQ3M2M2Mzg4ZWM4N2Y3ZmY1N2QxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rt8oblUYA_d8vAAPDwfmVX9JlUJclzOaRMjOTqcQc9c">

Hi 你好，我關閉是因為發現重複提交了，第二次提交的內容補充了一些信息；

感謝你的回復，通過你的指引，我使用自定義方式適配了這個網站還提交了兩個站點（原來步驟2的適配源地址因為網站地址發生了變化不適用了。）

**Thx!! You make my day.** 🙏

**Comment by Kenshin** [comment]
> 我關閉是因為發現重複提交了

okay 那直接在这里讨论就好。

> 我使用自定義方式適配了這個網站還提交了兩個站點

这种站点我之前提到了

<img width="462" alt="image" src="https://github.com/user-attachments/assets/d292628c-ffba-41fb-a3cb-b9c92e98af38">

所以，你自己适配后自己使用就好~
