### ISSUE TITLE
关于obsidian导出问题

### ISSUE THREAD

**Issue by cyx951211** [Kenshin/simpread#6812]
### 描述这个错误

obsidian导出同步问题
在阅读模式下 标注后右侧显示2条“已导出成功”，但是在obsidian文件夹中 只有"output"中有导出文件，“SimpRead”中没有

### 复现步骤

obsidian导出同步问题
在阅读模式下 标注显示2条导出成功，但是在obsidian文件夹中 只有"output"中有导出文件，“SimpRead”中没有

### 操作系统

macos14.6.1

### 浏览器

chrome

### 发生问题的网址

无

**Comment by Kenshin** [comment]
给出的信息太少，我没法判断。（导入到 Obsidian 有多种形式...

> 在阅读模式下 标注后右侧显示2条“已导出成功”，但是在obsidian文件夹中 只有"output"中有导出文件，“SimpRead”中没有

这是导入到 Obsidian 的教程，你可以对比下 https://www.yuque.com/kenshin/simpread/fr8zo5

试试手动导入方式能否成功？

<img width="384" alt="image" src="https://github.com/user-attachments/assets/0a0e2e7e-730a-46ab-b09c-8bd4279ecad9">

成功的话，说明你的配置没问题，出问题的在于自动化方面（上面的教程有说明）；反之，请仔细对比下上面的教程与你的区别。

建议：在没有跑通你的流程前，请严格安装教程的说明设置（文件夹、名称、路径等等一切）
