### ISSUE TITLE
“稍后读”中，少数派的图片不显示

### ISSUE THREAD

**Issue by sw6633** [Kenshin/simpread#6814]
### 请描述你的建议或任何内容

![ssp](https://github.com/user-attachments/assets/ac8f89e2-1a61-4a2f-b012-7d73634bcd14)
如图

1. 只有少数派的图片看不了，其他网站是正常的；
2. 只有在“稍后读”里不显示少数派的图片，阅读模式以及导出到本地软件都是正常的。

用的是win端chrome浏览器

**Comment by Kenshin** [comment]
嗨，这是因为少数派的图片鉴权造成的（你可以理解为防盗链造成的）

#### 解决方案

使用简悦的 [知识库方案（本地快照）](https://www.yuque.com/kenshin/simpread/wkswh7)，同时将图片转换其它图床的 [图床插件](https://github.com/Kenshin/simpread/discussions/4306)

#### 补充

但一般来说，我不太建议用户在稍后读（你截图）的方式查看，因为在这种模式下，无法使用简悦的插件以及浏览器的其它扩展。

**Comment by sw6633** [comment]
> 嗨，这是因为少数派的图片鉴权造成的（你可以理解为防盗链造成的）
> 
> #### 解决方案
> 使用简悦的 [知识库方案（本地快照）](https://www.yuque.com/kenshin/simpread/wkswh7)，同时将图片转换其它图床的 [图床插件](https://github.com/Kenshin/simpread/discussions/4306)
> 
> #### 补充
> 但一般来说，我不太建议用户在稍后读（你截图）的方式查看，因为在这种模式下，无法使用简悦的插件以及浏览器的其它扩展。

哈哈哈好的。不过稍后读的界面真的很舒服，不知道为啥一样的内容加到稍后读里立马就能静下心来，读得可认真了

**Comment by Kenshin** [comment]
> 不过稍后读的界面真的很舒服，不知道为啥一样的内容加到稍后读里立马就能静下心来，读得可认真了

emmmm 我也是这么觉得的  😊 

考虑下有没有什么折中的解决方案~
