### ISSUE TITLE
在同步助手中打开稍后读，报错提示请先设置稍后读的路径

### ISSUE THREAD

**Issue by iesap** [Kenshin/simpread#6815]
### 描述这个错误

在错误帮助中没有找到相关的说明。

### 复现步骤

1、运行同步助手，打开稍后读
![1731488733769](https://github.com/user-attachments/assets/63fafe3f-841f-44f5-9e48-a20e5f620ce0)
2、程序报错
![1731488705927](https://github.com/user-attachments/assets/fcfc5d8c-9c5d-4b48-9228-cb2fb3dc851f)

### 操作系统

win10专业版

### 浏览器

chrome

### 发生问题的网址

baidu.com

**Comment by Kenshin** [comment]
看下图

<img width="669" alt="image" src="https://github.com/user-attachments/assets/cafc0aaa-a364-465d-8ecf-777a8d3eb344">

但不太建议这么做了 Chrome 可能调整了方案，所以从下图进入比较好

<img width="209" alt="image" src="https://github.com/user-attachments/assets/de533306-1f22-4549-9ac5-569bfa3b02b7">

**Comment by iesap** [comment]
非常感谢，可以打开了。这个用法有点复杂。提示请在导出-稍后读-快捷键进行设置就傻瓜操作了。

**Comment by Kenshin** [comment]
😂

谢谢提示。（会按照你的建议优化）

因为角色不同，确实存在认知偏差。
