### ISSUE TITLE
无法授权 Notion（因 Notion 又双叒叕 一次更改了它的私有 API 导致）

### ISSUE THREAD

**Issue by yunxiaoli2017** [Kenshin/simpread#6817]
### 描述这个错误

按照 https://github.com/Kenshin/simpread/discussions/4954 的方法操作，无法授权 Notion，下面是尝试的两种方式。

### 复现步骤

尝试了两种方式
方式一
1. 下载 @Notion_sync 的配置文件，导入；更改 UID 授权高级用户；根据配置文件加载了插件。
2. 登出 Notion；登入 Notion；Duplicate 模版；改模版页面名字并收藏
3. 到内容网站 https://sspai.com/post/71576   可以看到一些标注，在「导入到 Notion 选项里」显示已授权（应该是授权的配置文件中自带的测试用的 Notion 账户），点击后无法重新选择，提示信息在转圈圈，console 有一项报错。如下图
<img width="2557" alt="image" src="https://github.com/user-attachments/assets/fea4cbd4-11a7-4625-9e7a-ff6abf3d5829">

方式二
1. 卸载 SimpRead 后重新安装
2. 不导入配置；更改 UID 授权高级用户；手动下载方式一里配置文件中包括的插件。
3. 登出 Notion；登入 Notion（模版页面之前已经设置好）
4. 到内容网站 https://sspai.com/post/71576   没有标注，在「导入到 Notion 选项里」显示未授权，点击后提示信息在转圈圈，console 有一项报错。如下图
<img width="2558" alt="image" src="https://github.com/user-attachments/assets/87dab323-6baf-4997-a018-75121d2df77b">

### 其他相关说明

已搜索查看了其他无法授权 Notion 的 issues，仍然没有头绪，请帮我找出问题所在，感谢帮助！

### 操作系统

macOS

### 浏览器

Chrome Version 130.0.6723.117 (Official Build) (arm64)

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
emmm 我明天确认下。

你的步骤看起来是没问题的。

**Comment by ethpony** [comment]
复议 Notion 导出，尝试两种方法，始终无法获取授权页面。

Chrome Version 128.0.6613.150  Win11 24H2 26100.2314

发生问题的网址：公众号文章

**Comment by Kenshin** [comment]
嗨，各位。

这个问题已确认，即：**因为 Notion 又双叒叕 一次更改了它的私有 API。**  🌚  💢 

为了彻底解决这个问题，我从出现问题时，就开始着手新方案，预计下周发布（原计划下周一，但因为外出有事）所以顺延到下周二。

***

关联 https://github.com/Kenshin/simpread/issues/809#issuecomment-2490951042

@Makarovsky

这个 Issues  集中讨论这个问题，包括解决方案等。

**Comment by TheBloodthirster** [comment]
咋整啊，不然导出成markdown，再手动导入notion?

**Comment by Kenshin** [comment]
@TheBloodthirster 

<img width="932" alt="image" src="https://github.com/user-attachments/assets/14ffbb17-888c-47b3-9564-143c01c469bf">

**Comment by Kenshin** [comment]
嗨，各位。

**简悦插件 · 导入到 Notion 2.0 社区预览版** 发布了，请留意下面的**【详细说明】**，有任何使用问题，请随时提交到这里。

## 📥 下载地址（社区预览版）

https://simpread.ksria.cn/plugins/details/qHQjjgBBhh

## 📝 详细说明（使用方法）

https://n.simp.red/posts/604

## ✅  正式版

在本周四发布。

**Comment by SurDark** [comment]
试用社区预览版，授权正常，第一步「上传图片到Cloudinary」正常，但第二步一直停在「正在保存到Notion，请稍等……」，最终未能保存成功。

**Comment by Kenshin** [comment]
@SurDark 

这个功能肯定没问题，所以：

1. 先取消 Cloudinary 图床，看看能否正常？

2. 提供下出问题的 URL

**Comment by SurDark** [comment]
![image](https://github.com/user-attachments/assets/a7ee2abf-1799-48d0-a497-6169a585d98f)
所有网址都是这样

**Comment by Kenshin** [comment]
@SurDark 

录屏给我看下吧。

从授权开始

**Comment by SurDark** [comment]
> @SurDark
> 
> 录屏给我看下吧。
> 
> 从授权开始

录好了，怎么传给您呢

**Comment by Kenshin** [comment]
直接发上来就行… 😂

**Comment by SurDark** [comment]
https://github.com/user-attachments/assets/c1b84ac2-76ec-4403-ae10-532e027dbfda

好的，您看下

**Comment by Kenshin** [comment]
@SurDark 

你授权的 Page 是通过简悦模板复制过去的吗？如果不是的话，肯定有问题 😂 因为简悦会导入很多属性 e.g. Favicon、题图等。

所以**需要使用简悦的模板**。

**Comment by SurDark** [comment]
> @SurDark
> 
> 你授权的 Page 是通过简悦模板复制过去的吗？如果不是的话，肯定有问题 😂 因为简悦会导入很多属性 e.g. Favicon、题图等。
> 
> 所以**需要使用简悦的模板**。

的确是模板的问题，之前没有留意到，不好意思。现在可以了，非常感谢！

**Comment by Kenshin** [comment]
@SurDark 

okay 解决就好

这是测试版，后续会加入对非简悦模板类 Page 导入时的提示。

**Comment by Kenshin** [comment]
@SurDark 

能否把之前出错的 Notion Page 共享给我，我复制一份。

因为测试了多个不同的 Page 均可以正常判断 😂

**Comment by Kenshin** [comment]
@SurDark 

okay 可以了，新版已加入了各种兼容性提示和，比如你提供的 Page 就可以正常导入了。

**Comment by est7** [comment]
@Kenshin 请问正式版插件是哪个?

**Comment by Kenshin** [comment]
@ethpony 

请先使用社区预览版 https://github.com/Kenshin/simpread/issues/6817#issuecomment-2496631230

正式版发布后我会在这里通知大家。

**Comment by Karllistark** [comment]
今天终于弄成功了！
是按照如下操作的，过程中出现了一些奇怪的问题

**Comment by Kenshin** [comment]
@Karllistark 

什么奇怪问题？

**Comment by Kenshin** [comment]
@Karllistark 

1. 如果使用社区版，其实就不用导入配置库了，因为之前使用了私有 API，所以某些用户可能在手动填写时出错，所以有了配置库。

2. 等正式版出来后，简悦会同步官方配置库的方案。（但基于第一点，其实配置库也没啥存在意义了 😂

**Comment by Karllistark** [comment]
感谢

**Comment by est7** [comment]
@Kenshin 顺便请问一下,官方 api 有上传图片的接口吗,这样我们还需要使用第三方的图床吗

**Comment by Kenshin** [comment]
@est7 

官方没有上传图片的 API 否则当 Notion 发布 API 后我就会支持，甚至于官方的「导入 API 」一塌糊涂 😂

简单的说，官方并没有所谓的导入 API，为了实现这点（社区预览版）做了很多事情。

官方没有 API 支持上传图片的逻辑也很简单，Notion 不是个图床，如果你用来当图床的话，现在没事，不代表以后没事。

使用私有 API 就是个「最大」的教训，好在我已经及时醒悟了  💢  🌚

**Comment by Kenshin** [comment]
嗨，各位。

> 久等了，正式版发布前的最后一个版本

### 📥 下载地址（Release 版）

https://simpread.ksria.cn/plugins/details/qHQjjgBBhh

### 📜 与正式版有什么区别？

功能完全一致，仅在正式版发布前移除了部分 2.0 版独有功能。

### 📦 与社区版有什么区别？

1️⃣ 修复大量语法兼容性问题，现已完美支持常规结构，并适配 [知乎公式](https://zhuanlan.zhihu.com/p/672941483)、[表格](https://sspai.com/post/94089) 及 [包含大量代码段](https://juejin.cn/post/6844903645289398280) 的页面

2️⃣ 兼容 Notion Page 的结构合理性，任何 Database 页面均可正常导入，即使未使用简悦模板

3️⃣ 转换失败时自动修正结构，确保 100% 导入成功

4️⃣ 恢复快捷导入功能，可自由导入至授权的 Notion Page

### 📢 注意事项

禁用【导入到 Notion】与【导入到 Notion 辅助增强插件】后再安装此插件

### 🐞 已知问题

无法识别多层嵌套列表（很少见的情况）

### 📅 正式版什么时候发布？

下周一（或周二）

***

感谢各位的大量使用（反馈） 😄 👍

**Comment by King-LL** [comment]
> 今天导入notion2.0社区预览版终于弄成功了！ 是按照如下操作的，过程中出现了一些奇怪的问题。 1.授权高级账户 2.导入配置库（**我一开始以为不用导入这个了，直接下载的导入notion2.0插件**），导入配置库里的插件8个 3.取消导入到notion并增强辅助这两个插件，下载导入到notion2.0插件 4.打开少数派网页，然后快捷键nt，提示要notion授权，按步骤，复制模板+☆，授权notion，选择页面。 5.图床用推荐的cloudinary，验证的时候（这里一直提示图片保存失败），我没管它直接按照填好的关键那些信息保存了 然后再次键盘nt居然成功了。 这个保存失败的提示是第一个问题，但是希望不影响结果，后面我想找那个导入notion2.0授权页面确认cloudinary图验证床成功是不是了，但是我找不到那个页面了，尴尬，我在偏好设置的“服务”里授权概念，但是这里不授权也不影响这个导入notion2.0插件。。。 第二个问题，我在第一步已经授权了高级账户，在我保存到notion成功后又弹出来黄色提示我高级功能不能用什么的，我看到我的账户确实被锁了，重新填uid后就OK了。 有可能是我的网络问题，但是结果是好的:D

必须是高级账户才可以吗？

**Comment by King-LL** [comment]
> 今天导入notion2.0社区预览版终于弄成功了！ 是按照如下操作的，过程中出现了一些奇怪的问题。 1.授权高级账户 2.导入配置库（**我一开始以为不用导入这个了，直接下载的导入notion2.0插件**），导入配置库里的插件8个 3.取消导入到notion并增强辅助这两个插件，下载导入到notion2.0插件 4.打开少数派网页，然后快捷键nt，提示要notion授权，按步骤，复制模板+☆，授权notion，选择页面。 5.图床用推荐的cloudinary，验证的时候（这里一直提示图片保存失败），我没管它直接按照填好的关键那些信息保存了 然后再次键盘nt居然成功了。 这个保存失败的提示是第一个问题，但是希望不影响结果，后面我想找那个导入notion2.0授权页面确认cloudinary图验证床成功是不是了，但是我找不到那个页面了，尴尬，我在偏好设置的“服务”里授权概念，但是这里不授权也不影响这个导入notion2.0插件。。。 第二个问题，我在第一步已经授权了高级账户，在我保存到notion成功后又弹出来黄色提示我高级功能不能用什么的，我看到我的账户确实被锁了，重新填uid后就OK了。 有可能是我的网络问题，但是结果是好的:D

必须是高级账户才可以吗？

**Comment by King-LL** [comment]
> 今天导入notion2.0社区预览版终于弄成功了！ 是按照如下操作的，过程中出现了一些奇怪的问题。 1.授权高级账户 2.导入配置库（**我一开始以为不用导入这个了，直接下载的导入notion2.0插件**），导入配置库里的插件8个 3.取消导入到notion并增强辅助这两个插件，下载导入到notion2.0插件 4.打开少数派网页，然后快捷键nt，提示要notion授权，按步骤，复制模板+☆，授权notion，选择页面。 5.图床用推荐的cloudinary，验证的时候（这里一直提示图片保存失败），我没管它直接按照填好的关键那些信息保存了 然后再次键盘nt居然成功了。 这个保存失败的提示是第一个问题，但是希望不影响结果，后面我想找那个导入notion2.0授权页面确认cloudinary图验证床成功是不是了，但是我找不到那个页面了，尴尬，我在偏好设置的“服务”里授权概念，但是这里不授权也不影响这个导入notion2.0插件。。。 第二个问题，我在第一步已经授权了高级账户，在我保存到notion成功后又弹出来黄色提示我高级功能不能用什么的，我看到我的账户确实被锁了，重新填uid后就OK了。 有可能是我的网络问题，但是结果是好的:D

必须是高级账户才可以吗？

**Comment by Kenshin** [comment]
@King-LL 

不需要，但图床需要使用高级账户，但你可以使用（另外一个）图床插件。

导入到 Notion 内置了 Cloudinary 图床方案（此功能需要高级账户）

**Comment by FirerainML** [comment]
![image](https://github.com/user-attachments/assets/bf6e0196-35bb-4664-884f-580426c8e909)
大佬，我明明copy了页面也设置好了，但简悦仍然提示我需要配置好Page才行，好崩溃。我今天搞了一下午，一开始用配置库提示没法授权，我又一路搜到这里来，然后装了社区版插件，把之前配置库全删了，但还是没法导入……

**Comment by Kenshin** [comment]
@FirerainML 

暂时不要用配置库里面的方案...

试试 **重新授权**

<img width="1283" alt="image" src="https://github.com/user-attachments/assets/07ad07dd-01be-412e-9d56-d915f2adffd5">

你的问题跟此 Issues 无关，如还有问题请通过 https://github.com/kenshin/simpread/issues/new 然后录屏给我看下。

**Comment by Kenshin** [comment]
@FirerainML

暂时不要用配置库里面的方案...

***

请重新安装这个插件，我针对你的问题做了优化，**重新安装后，需要重新授权**

**Comment by FirerainML** [comment]
@Kenshin 大佬，这次成功了，我看导出到Notion的文字图片是正常的，那请问安装这个社区版以后还需要额外下载其他的插件吗？如题图什么的。

**Comment by Kenshin** [comment]
@FirerainML 

导入到 Notion 2.0 新版内置了部分题图、Favicon、Origin 等，暂时不需要使用 **导入到 Notion 辅助增强**

但下周发布的  **导入到 Notion 辅助增强 2.0** 则需要安装（因为会提供更多新功能）

***

> 那请问安装这个社区版以后还需要额外下载其他的插件吗？如题图什么的。

这些是另外的插件，你觉得有需要就安装。

**Comment by joeyzzzhu** [comment]
按照以下步骤，还是无法授权notion，无法解决。
1.授权高级账户 2.导入配置库（我一开始以为不用导入这个了，直接下载的导入notion2.0插件），导入配置库里的插件8个 3.取消导入到notion并增强辅助这两个插件，下载导入到notion2.0插件 4.打开少数派网页，然后快捷键nt，提示要notion授权，按步骤，复制模板+☆，授权notion不成功。
此外，重新登出及登入notion，以及重新卸载简悦，也无法解决。

**Comment by Kenshin** [comment]
@joeyzzzhu 

显然你使用错插件了...  请仔细看 https://github.com/Kenshin/simpread/issues/6817#issuecomment-2522516913

**Comment by Kenshin** [comment]
嗨，各位。

![](https://imgs.zhubai.love/5ccaad4e75ac4610b11c966cb45f8484_2072964972706709504.png)

# 🆕 全新 2.0 版

在 2024 年 11 月 16 日，Notion 私有 API 再次出现无法使用的问题，这让我决定**彻底弃用私有 API 方案，全面转向公开 API**。

由于采用公开 API，确保了功能的稳定性，不会再出现无法使用的情况，以下所有功能均基于 2.0 版本的描述。

# 🌟 特色

与其他同类产品相比，**简悦凭借其出色的阅读模式，可以更精准地将全文导入到 Notion**。

由于采用了公共 API，解决了 1.0 版本无法无法正确转换 LaTeX 公式的问题，并提供更安全简便的一键授权方式（相比私有 API，避免了账户泄漏风险）。

此外，还支持以下功能：

1️⃣ 在 Notion Page 显示描述、题图、Favicon、来源、标签、备注

2️⃣ 内置图床

3️⃣ 导入带标注颜色的全文 [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

4️⃣ 导入标注（支持三种方式）

5️⃣ 支持超长文章的导入、[知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229)、[表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74)（使用私有 API 的产品都存在无法使用的问题）

# 📥 导入效果

[https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897](https://simpreadpublish.notion.site/150907a65f5881c0b4dad5ef1f635929?v=150907a65f588123b43e000cbd0e8897&pvs=74)

# 📚 一站式教程

[https://www.yuque.com/kenshin/simpread/zx3bcz](https://www.yuque.com/kenshin/simpread/zx3bcz)

# 📦 配置库

[简悦 · 配置库](https://www.yuque.com/kenshin/simpread/ds8zk0) 是简悦官方推出的一套针对新用户的极简配置方案，方便新用户用最快的方式使用简悦的各种高级服务，配置库内置了常用的双链笔记用法，如：Notion、Obsidian、Logseq、Roam Research，同时包含了简悦在阅读模式上的一些常规插件：Live Editor、题图、Safari 阅读模式等。

如果你需要使用简悦 + Notion 的话，可以直接看 [此配置库](https://www.yuque.com/kenshin/simpread/mwda8s) 。

# 🔌 介绍

导入到 Notion 相关功能分为两个插件：

📗 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

📘 [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU)

# 📖 功能

1️⃣ 可导入当前页面的题图、Favicon、来源等。

![img](https://imgs.zhubai.love/92778b3c8dcc4b1ab1120e1dbf780d33_2072964972706709504.png)

2️⃣ 导入正文到 Notion，因为使用了公开 API，所以可以完美适配 [知乎公式](https://simpreadpublish.notion.site/Random-Fourier-Features-156907a65f5881369b70c4e096f14229) · [表格及包含大量代码段](https://simpreadpublish.notion.site/ADB-156907a65f5881f6bfbac02cca3d3573?pvs=74) 

3️⃣ 导入**带标注色的正文**到 Notion [查看效果](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)

> 此功能需要 **简悦高级账户**，可通过 [**此链接**](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/c6aa20e1b1814399b9e87b569ebdb3b5_2072964972706709504.png)

4️⃣ 内置 Cloudinary 图床

![img](https://imgs.zhubai.love/85901d6d7ed74b598b1b75ab81b59754_2072964972706709504.png)

5️⃣ 在导入可选择任意 Notion

![img](https://imgs.zhubai.love/2864ffa0f9134a4b8c99116cdf12c41f_2072964972706709504.png)

6️⃣ 同步稍后读的标签，并支持加入全局标签（即使当前页面未被标记为稍后读，也可导入已添加的全局标签）。

![img](https://imgs.zhubai.love/0cda01a5740a4c35b80391dc1ac971e5_2072964972706709504.png)

7️⃣ 添加描述（Summary）与稍后读备注（Note）

> 此功能需要 **简悦高级账户**，可通过 [此链接](https://simpread.pro/price) 升级。

![img](https://imgs.zhubai.love/d1d8cbad7ef94f169095039cd18b9b23_2072964972706709504.png)

8️⃣ 去除重复的 Page

![img](https://imgs.zhubai.love/58668edcf264416ea6dc2d97069ce2b0_2072964972706709504.png)

9️⃣ 导入标注

![img](https://imgs.zhubai.love/59ffe6d7a1644d83ab40f2d6bc06597e_2072964972706709504.png)

2.0 版在原来的方案（[标准模式](https://simpreadpublish.notion.site/150907a65f588120b3c4de0e61cf9ad4)）基础上增加了两个全新的标注模板：

📗 带标注色的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f5881ada61bc11c25596f1d?pvs=74)

📘 按照标注色分类的模板 [查看效果](https://simpreadpublish.notion.site/annote-150907a65f58814da34fd7e2e0cb9d96?pvs=74)

![img](https://imgs.zhubai.love/fc42ca0d3dc94186b02e6737febdde51_2072964972706709504.png)

注意：上述两种标注模板需要**简悦高级账户**权限，可通过 [此链接](https://simpread.pro/price) 升级。

# 🔄 旧版本升级说明

如果你已使用 1.x 版（旧版本），首次升级后会出现如下截图，此时需重新授权 Notion 才能使用。（授权方式与上面一致）

![img](https://imgs.zhubai.love/fea50a3a372d47098655eddf70022cc7_2072964972706709504.png)

# 📈 安装与升级

1️⃣  【没有使用】同步助手 · 自动同步 的话，可直接 [导入到 Notion 插件](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)  [导入到 Notion 辅助增强插件](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 安装。

2️⃣  【已经使用】同步助手 · 自动同步 的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

#  🔎 关联 

https://github.com/Kenshin/simpread/issues/4955

# 👋 社区预览版用户看过来

请禁用 https://simpread.ksria.cn/plugins/details/qHQjjgBBhh 即可。

选项页 → 插件管理，按下图所示操作。

<img width="525" alt="image" src="https://github.com/user-attachments/assets/0a94735f-8b98-4f81-b218-ac137ca6dfd5">

***

有任何问题，请通过 https://github.com/Kenshin/simpread/issues/6817 讨论，我关闭这个 Issues 了~

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955

**Comment by pokemon15139** [comment]
<img width="1449" height="742" alt="Image" src="https://github.com/user-attachments/assets/764e87bc-e69d-4d93-9fa9-bc2dcfa9f0eb" />.   授权失败，获取不到notion页面，插件安装不了，每次点安装，实际上都没安装。  手动安装chrome后，恢复账户后，出现此问题，求大佬解决。
