### ISSUE TITLE
个人站-博客手动选择都无法识别内容

### ISSUE THREAD

**Issue by AlphaZ19** [Kenshin/simpread#6819]
### 需要适配的新站

https://mkblog.cn/581/

**Comment by Kenshin** [comment]
嗨，我看到你 Close 这个 Issues 了，是解决了吗？

你可以试试 https://github.com/Kenshin/simpread/discussions/1554 提到的方案~

**Comment by AlphaZ19** [comment]
> 嗨，我看到你 Close 这个 Issues 了，是解决了吗？
> 
> 你可以试试 #1554 提到的方案~

是的，我重新缩小了正文内容范围，就能正确识别了
![image](https://github.com/user-attachments/assets/2030d813-6c56-4f75-b861-33bf645aef0c)

**Comment by Kenshin** [comment]
哈，解决就好 👍
