### ISSUE TITLE
又又又一个未适配的 CSDN 代码高亮

### ISSUE THREAD

**Issue by Cyberpuncrush** [Kenshin/simpread#682]
CSDN代码块问题

**截图**
![](https://crush-typora.oss-cn-shanghai.aliyuncs.com/typora20200310203025.png)
![](https://crush-typora.oss-cn-shanghai.aliyuncs.com/typora20200310203127.png)

**Comment by Cyberpuncrush** [comment]
不好意思忘了放网址了2333
https://blog.csdn.net/weixin_43094965/article/details/82226263
个人感觉这种网页不太能被正确抓取，我在safari中也无法对其开启自带的阅读视图

**Comment by Kenshin** [comment]
谢谢反馈。

CSDN 的代码段渲染类型太多了，我至少为其适配了 5+ 种，竟然到现在还有遗漏...  😂 

等适配后升级插件就可以了，到时候我会在这里通知你。 😀

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀 

更新方法：点击上面链接中的 **安装当前插件** 即可。
