### ISSUE TITLE
“导入全文到Obsidian”功能异常

### ISSUE THREAD

**Issue by giant73** [Kenshin/simpread#6823]
### 描述这个错误

使用插件将知乎网页内容导入到Obsidian中，发现使用 “导入全文到Obsidian” 功能报错，无法导入；但是使用“导入 md + assets 到Obsidian”可以成功导入。

“导入全文到Obsidian” 功能报错：
<img width="1239" alt="全文导入obsidian" src="https://github.com/user-attachments/assets/2f63fca3-d646-4b88-841b-c6692d63a872">

“导入 md + assets 到Obsidian”功能正常：
<img width="1096" alt="PixPin_2024-11-19_15-07-30" src="https://github.com/user-attachments/assets/9c826131-2376-4515-aa4f-f09c080c876c">

### 复现步骤

在我本地，正常使用就会出现

### 操作系统

windows 11

### 浏览器

chrome

### 发生问题的网址

https://zhuanlan.zhihu.com/p/260205834?utm_source=wechat_session&utm_medium=social&utm_oi=50301696475136&utm_campaign=shareopn

**Comment by Kenshin** [comment]
我这边测试没问题。

> 但是使用“导入 md + assets 到Obsidian”可以成功导入。

因为这种方式没有使用 Obsidian SimpRead Sync 插件，而使用了同步助手。

> 用插件将知乎网页内容导入到Obsidian中，发现使用 “导入全文到Obsidian” 功能报错

截图没问题，但并没有任何有效性错误信息 😂

1. 直接方案 http://localhost:7027/ 看下是否正常
2. 测试下其它页面 e.g. https://36kr.com/p/3037311433929606

**Comment by giant73** [comment]
> 我这边测试没问题。
> 
> > 但是使用“导入 md + assets 到Obsidian”可以成功导入。
> 
> 因为这种方式没有使用 Obsidian SimpRead Sync 插件，而使用了同步助手。
> 
> > 用插件将知乎网页内容导入到Obsidian中，发现使用 “导入全文到Obsidian” 功能报错
> 
> 截图没问题，但并没有任何有效性错误信息 😂
> 
> 1. 直接方案 http://localhost:7027/ 看下是否正常
> 2. 测试下其它页面 e.g. https://36kr.com/p/3037311433929606
> 3. 建议把你的配置截图给我看下。

今天使用又恢复正常了，之前出现的问题可能是由于端口被占用了？

**Comment by Kenshin** [comment]
okay 留意仅开一个库。

我关闭这个 Issues 了
