### ISSUE TITLE
阅读模式无法正常显示目录

### ISSUE THREAD

**Issue by zhiWang10262418** [Kenshin/simpread#6824]
### 描述这个错误

原页面有标题，且是h1标签，但是打开简阅阅读模式后，怎么设置都无法显示出目录。导出后也不显示。
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/52004230-a379-4515-b23a-70ea5572ea7e">
<img width="1519" alt="image" src="https://github.com/user-attachments/assets/927d70f3-80e4-42d0-bfb0-e99134a461a5">

### 复现步骤

1. 找到有目录大纲的页面。
2. 打开简阅。
3. 查看不到目录。

### 操作系统

macOS

### 浏览器

Chrome 131

### 发生问题的网址

http://www.ifengweekly.com/detil.php?id=21681

**Comment by Kenshin** [comment]
嗨，我没法查看这个页面。😂

1. 你可以使用 https://github.com/Kenshin/simpread/discussions/1554 解决。（一般都可以正常解决）
2. 也可以考虑把可以登录的账户给我测试下，这样可以一劳永逸。

如果第二点 OK 的话，请修改一个简单的密码，然后发送到 `help#####simpread.pro` 邮箱里面（注意 `#` → `@`）并注明这个 Issues ID：6824

然后在这里通知我~

**Comment by Kenshin** [comment]
> 但是导出为PDF后目录仍无法显示，目录标题只能显示为普通文字

导出 PDF 如果要带目录的话，需要使用 https://github.com/Kenshin/simpread/discussions/3887

> 阅读模式中如何能让其自动就显示目录？按照方案一还得每次都手动选择下怪麻烦的。

我应该告诉你了，这个站没有适配，如果你访问 https://sspai.com/post/94276 自动就会有目录...

**Comment by zhiWang10262418** [comment]
你好

*目前阅读模式目录问题已经解决！谢谢。*

但是感觉您的教程 #3887 <https://github.com/Kenshin/simpread/discussions/3887>
介绍未尽详细。wkhtmltopdf这个本地插件还需要简阅浏览器端再安装"PDF 辅助增强"才行。
*希望您能完善文档！谢谢。*

*另外还有个小问题：再导出时候如何能自定义标题样式呢？*因为现在生成的PDF目录是有了，但文件中标题、正文字体都一样。*我发现阅读模式时也有此问题。*
[image: image.png]
（⬆️网站默认效果：标题、正文字体*可以*区分显示）
[image: image.png]
（⬆️阅读模式效果：标题、正文字体无法区分显示）
[image: image.png]
（⬆️生成的PDF效果：标题、正文字体无法区分显示）


Kenshin Wang ***@***.***> 于2024年11月26日周二 10:58写道：

**Comment by Kenshin** [comment]
解决就好 👍

> 介绍未尽详细。wkhtmltopdf这个本地插件还需要简阅浏览器端再安装"PDF 辅助增强"才行。

其实是有的 😂

<img width="643" alt="image" src="https://github.com/user-attachments/assets/290fc8b1-4557-4de8-b690-3d04d7cff42c">

你不需要在 Email 中回复 😂 可以进入 https://github.com/Kenshin/simpread/issues/6824 回复 😄

**Comment by Kenshin** [comment]
方便的话，请务必帮忙在 [Chrome](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll) 或 [Edge](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 五星 + 好评，以便让更多人知道 😉 😁 👍

**Comment by zhiWang10262418** [comment]
**问题已经解决**！现将解决方案梳理如下：
* 浏览器页面打开阅读模式就无法显示目录——则使用"手工选择高亮区域"解决。
* 导出的PDF中不显示目录——则浏览器简阅中再安装个小插件"PDF 辅助增强"，然后Mac本地安装个"wkhtmltopdf"插件。这样导出时点击"PDF 辅助增强"来导出就能带上目录了。

**Comment by Kenshin** [comment]
👍

清晰的反馈和总结也是让这个 Issues 这么快 Close 的原因 😄

PS：你的动手能力也很不错 👍  如 `wkhtmltopdf ` 相关的事情就没在问我 😂

> https://github.com/Kenshin/simpread/issues/6824#issuecomment-2496965964

至于这个问题，我的意思是你可以把账户和密码发送到我给你的有些，为了防止 Spam 所以邮箱格式是错误的。

<img width="820" alt="image" src="https://github.com/user-attachments/assets/a24de0cd-4e0e-438f-9103-3c6d5d626a0b">

**Comment by zhiWang10262418** [comment]
哈哈

因为我也是码农。

**Comment by Kenshin** [comment]
竟然是同行，我说交流时的逻辑性为什么这么顺 😂 👍

**Comment by zhiWang10262418** [comment]
> 竟然是同行，我说交流时的逻辑性为什么这么顺 😂 👍

已经五星好评！
<img width="960" alt="image" src="https://github.com/user-attachments/assets/d45a9fdd-e605-47bd-a140-6e0d456e797e">

**Comment by Kenshin** [comment]
哈哈，早上就看到了。

谢好评 👍

PS：顺便把你的截图删了（以防个人信息泄漏），话说你开的 Tab 实在是忒多了 😂

**Comment by zhiWang10262418** [comment]
好。谢谢。
