### ISSUE TITLE
为什么我无法安装插件，截图如下

### ISSUE THREAD

**Issue by ssssorg** [Kenshin/simpread#684]
[https://tc.yly.ink/images/2020/03/13/Snipaste_2020-03-13_14-26-41.png](url)

**Comment by ssssorg** [comment]
重装后成功

**Comment by Kenshin** [comment]
没问题的话，我关闭此 issues 了~

**Comment by ssssorg** [comment]
就是跟你说一下那个浏览器需要设置在所有网站上都可以读取和更改网站数据才行。不然就会出现插件无法下载和无法使用的问题。不知道是权限还是开发的原因






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上6:44
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"sssorg"<1819079378@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 为什么我无法安装插件，截图如下 (#684)





 
没问题的话，我关闭此 issues 了~

**Comment by Kenshin** [comment]
谢谢提醒。 👍 

正常在安装完简悦后，不需要做任何配置，就可以使用了，除非你的浏览器本身有一些 **限制条件** （印象中，仅出现在 Chromium 的变种浏览里...
