### ISSUE TITLE
站点编辑器默认提供配置与实际使用配置不符

### ISSUE THREAD

**Issue by nidongpinyinme** [Kenshin/simpread#6844]
### 请描述你的建议或任何内容

直接将站点编辑器提供的配置保存并刷新时解析结果发生变化且报错
测试网址：https://arxiv.org/html/2412.06474v1

**Comment by Kenshin** [comment]
请详细说明下 😂

**Comment by nidongpinyinme** [comment]
使用时发现了一下新问题，我新开一个详细说明
