### ISSUE TITLE
文章導入到稍後讀後稍後讀中的內容沒了

### ISSUE THREAD

**Issue by FuZhi-Sun** [Kenshin/simpread#6850]
### 描述这个错误

<img width="1280" alt="屏幕截图 2024-12-17 202150" src="https://github.com/user-attachments/assets/7e4f8277-7321-4d59-8ced-e213e998f081" />
之前的知乎網頁導入到稍後讀成功，但是在導入微博網頁後，打開稍後讀，裏面的內容全沒了，甚至名字也還原了。堅果雲中的文件還在。

### 复现步骤

1.配置edge中的知乎優化插件，導入知乎文章
2.配置chrome中的wiki插件
3.在edge中導入微博文章
（均使用了插件管理器）

### 操作系统

Windows

### 浏览器

Edge 131.0.2903.99 

### 发生问题的网址

https://www.zhihu.com/question/607453623/answer/3572828880

**Comment by FuZhi-Sun** [comment]
後來導入文章再沒有堅果雲同步了，怎麼回事呢？

**Comment by FuZhi-Sun** [comment]
後來導入稍後讀的知乎文章不但前面有網頁css，圖片還無法顯示

**Comment by Kenshin** [comment]
你使用了配置巨方案，但是没有启用自动同步。

详细对比下你的配置与配置库教程中的区别，尤其是自动同步相关。

**Comment by Kenshin** [comment]
知乎需要安装 https://github.com/Kenshin/simpread/discussions/2861

**Comment by FuZhi-Sun** [comment]
<img width="863" alt="屏幕截图 2024-12-18 002555" src="https://github.com/user-attachments/assets/d7cb2098-07e6-4459-9312-c639025d6b62" />
我的自动同步是开了的，但是仍旧不成功，还有巨方案是什么？

**Comment by FuZhi-Sun** [comment]
而且活跃列表中是我已经在output中删除的文章

**Comment by Kenshin** [comment]
> 巨方案是什么？

手机打字错误造成的误会，我想打的字是 配置**库** 😂...

> 而且活跃列表中是我在obsidian中有，但在output中删除的文章。這是同步到哪裏了

Obsidian 是另外一个系统，你在简悦中的删除操作不会反映到 Obsidian 中。

***

你先试试添加几个不同稍后读，看下 `simpread_config.json` 是否更新（判断依据是它的更新日期或 size 是否发生变化）

然后再看下稍后读中是否存在这几个新加的。

**Comment by Kenshin** [comment]
#6853 与此问题是一个... 我统一在这里回复。

这是你问题的答案...

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/17343c24-628f-45b4-8467-6647d306b444" />

**Comment by Kenshin** [comment]
你所有的问题都可以归结一个：

删除了稍后读，但你没有删除本地快照造成的。

**Comment by FuZhi-Sun** [comment]
好了，謝謝您，太麻煩您了

**Comment by Kenshin** [comment]
哈，解决就好。 👍
