### ISSUE TITLE
小红书的图片无法采集，采集的页面无法移动

### ISSUE THREAD

**Issue by PaceZhou** [Kenshin/simpread#6851]
### 需要适配的新站

https://www.xiaohongshu.com/

所有的页面

### 有需要请描述这个站的性质

使用微信公众号插件原来可以采集到小红书这样的图片展示页面，但是现在无法采集，微信公众号也有部分失效，请更新一下可以吗？
稍后读的内容无法导入NOTION

**Comment by Kenshin** [comment]
我这边测试没问题。

> 微信公众号插件原来可以采集到小红书这样的图片展示页面

这两者并没有任何关联... 微信公众号是负责微信的，不会对小红书的页面有任何影响...

请留意下图所示

<img width="469" alt="image" src="https://github.com/user-attachments/assets/cd13bf7f-a1dc-4925-b9cf-c5b6cfa4fd97" />

> 稍后读的内容无法导入NOTION

如果你说的是：选项页 → 稍后读的话，目前是这样的，因为导入到 Notion 2 是插件，暂时无法运行在此处。
