### ISSUE TITLE
知乎導出稍後讀後，稍後讀裏面的內容與要收藏的內容無關

### ISSUE THREAD

**Issue by FuZhi-Sun** [Kenshin/simpread#6853]
### 描述这个错误

<img width="1280" alt="屏幕截图 2024-12-18 114430" src="https://github.com/user-attachments/assets/e1239e67-ee5c-4982-acc3-e482ddc85e54" />
如圖，本地的文件裏的html是合適的，只有稍後讀裏不合適 

### 复现步骤

進入閱讀模式後使用知乎插件，後導入到稍後讀

### 操作系统

Windows

### 浏览器

Edge 131.0.2903.99 

### 发生问题的网址

https://www.zhihu.com/question/607453623/answer/3572828880

**Comment by FuZhi-Sun** [comment]
<img width="1280" alt="屏幕截图 2024-12-18 115140" src="https://github.com/user-attachments/assets/50e811a1-e570-41bd-b121-912e4238ab2c" />
本來的答案是這個

**Comment by Kenshin** [comment]
跟 #6850 是一个问题... 我关闭这个 issues 了，请前往 https://github.com/Kenshin/simpread/issues/6850#issuecomment-2550265734
