### ISSUE TITLE
下载离线下载网址也不可用了

### ISSUE THREAD

**Issue by poapoauu** [Kenshin/simpread#6855]
### 描述这个错误

谷歌商店已被禁用和下载，离线下载网址也不可用了

### 复现步骤

谷歌商店已被禁用和下载，离线下载网址也不可用了

### 操作系统

Window

### 浏览器

谷歌浏览器

### 发生问题的网址

无

**Comment by Kenshin** [comment]
解决方案 https://github.com/Kenshin/simpread/discussions/6633

另外，请告知你的浏览器版本，我这边是 131.0.6778.205（正式版本） (arm64) 没有此问题（截至到 2024年12月20日）

**Comment by Kenshin** [comment]
还有，请详细截图说明下你的问题（不可用具体指什么）

**Comment by poapoauu** [comment]
![企业微信截图_20241220114247](https://github.com/user-attachments/assets/5b153d22-5694-404a-bfbb-2e490953c5db)

谷歌商店被限制下载和使用

![企业微信截图_20241220114300](https://github.com/user-attachments/assets/5ec210e3-ccd4-4d27-8734-e89fa0c71e6b)

这个是谷歌浏览器版本，我的是Window平台

![企业微信截图_20241220114335](https://github.com/user-attachments/assets/a081afb2-d671-45ab-9bcd-73db4c4cb118)

这个是提供的离线下载地址也显示不存在

**Comment by poapoauu** [comment]
未在 Chrome Webstore 提交同样问题

**Comment by poapoauu** [comment]
![11111](https://github.com/user-attachments/assets/9bbef9ad-e661-4827-a84c-96521338bbf7)

离线下载地址指的是这个下载地址

**Comment by Kenshin** [comment]
谢谢提示。

不要使用离线版，请使用我给你的地址 https://github.com/Kenshin/simpread/discussions/6633

**Comment by Kenshin** [comment]
另外，是否能回忆起，你的浏览器是否是刚刚升级过？

**Comment by poapoauu** [comment]
我刚才无法使用时执行了一次升级，升级到了目前的谷歌浏览器版本，先前的浏览器版本和目前的浏览器版本都暂时无法在谷歌商店下载使用

**Comment by Kenshin** [comment]
> 先前的浏览器版本

这是什么版本？你有印象吗？

***

不过，都无所谓，使用我提供的方式可以解决。

**Comment by poapoauu** [comment]
没有印象先前版本了，是的你提供的 https://github.com/Kenshin/simpread/discussions/6633 解决方式有效，感谢！！！

**Comment by Kenshin** [comment]
> 是的你提供的 https://github.com/Kenshin/simpread/discussions/6633 解决方式有效，感谢！！！

解决就好。

其实如果有可能，建议使用 Edge 浏览器更好，因为不仅简悦，很多优秀的 Chrome 扩展都有可能出现这个问题。

**Comment by Kenshin** [comment]
还需要帮个忙，请根据下图所示

当前页面 → 右键 → 检查

<img width="430" alt="image" src="https://github.com/user-attachments/assets/dbea4886-1014-47ed-95de-3097ab4b0ad5" />

切换到 Console

<img width="416" alt="image" src="https://github.com/user-attachments/assets/1da02869-e7b3-41dd-8207-117ec1d6608d" />

输入 `navigator.userAgent` 然后得到的值复制到这里。

<img width="969" alt="image" src="https://github.com/user-attachments/assets/a8c102ee-64c5-4128-8e63-9045c719928a" />

**Comment by Kenshin** [comment]
还有，我针对你的系统和浏览器版本增加了一个提示，你帮忙看下是否在你的浏览器上打开 https://simpread.pro/ （使用隐私模式），能否出现下面的提示？

<img width="1247" alt="image" src="https://github.com/user-attachments/assets/5a919df8-0a54-4840-a488-621cd0b847e0" />
