### ISSUE TITLE
sciencedirect.com 无法进行导入到 Notion

### ISSUE THREAD

**Issue by ggbondpx** [Kenshin/simpread#6858]
### 描述这个错误

https://www.sciencedirect.com/science/article/pii/S2452199X21005934 简悦无法对该网页进行剪藏到Notion

### 复现步骤

触发剪藏到Notion后，上传图片到图床正常，但是未能触发长文章的多次导入，导致一直卡在“正在保存到Notion,请稍等”的提示中。目前简悦对相关主流文献网站的剪藏存在较大概率的失败可能，跟文献网站的类别关系不大，跟某些特定的文献网址有关系，所以感觉可能还是条件触发的问题？

### 操作系统

Win11

### 浏览器

edge

### 发生问题的网址

https://www.sciencedirect.com/science/article/pii/S2452199X21005934

**Comment by Kenshin** [comment]
嗨，我这边没有任何问题，这是导入后 Share 的页面 https://ksfavorite.notion.site/Polyphosphate-crosslinked-collagen-scaffolds-for-hemostasis-and-alveolar-bone-regeneration-after-too-163b610e696281059269d86602ea8166?pvs=73

> 但是未能触发长文章的多次导入

你提到的问题跟此情况无关，是否触发多次导入的显示并不取决于你看到的页面长度，而是 Notion 提供的「算法」（你可以这么理解）

注意：我使用的是 2.0.1 版，而你使用的是 2.0.0 版。（可能是因为这个差异，但我不确定，因为不打算测试了，下午就会发 2.0.1 版，发布后我会在这里通知你。

关联 https://github.com/Kenshin/simpread/issues/4955

**Comment by Kenshin** [comment]
嗨，[导入到 Notion](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 与 [导入到 Notion 辅助增强](https://simpread.ksria.cn/plugins/details/g60jwZEeqU) 这两个插件升级到了2.0.1 解决了此问题（注意：在这个页面仍会出现转换失败的情况，但仍然可以正常导入）

这是我 Share 的导入后的页面 https://ksfavorite.notion.site/0-1-UniApp-Vue3-TypeScript-163b610e69628193ab2bce5351f5c7d4?pvs=73

⤴️ 安装与升级
---

- 没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

🗒️  更新日志
---

### 2.0.1

-  `Optimize` 导入到 Notion Page 的锚点从 `Name` 改为 `title` 用以适配更广泛的 Database 结构

- `Fix` 几处结构错误导致异常的情况

***

我关闭这个 Issues 了，有任何问题随时讨论~

**Comment by ggbondpx** [comment]
大佬辛苦了，但是不知道是哪里出了问题，更新了两个插件到2.0.1版本后，试了多次发现剪藏的文章都是不完整的，均没有提示API限制需要多次导入，这个是我剪藏的链接：https://almondine-elf-634.notion.site/Polyphosphate-crosslinked-collagen-scaffolds-for-hemostasis-and-alveolar-bone-regeneration-after-too-16335e68cd1581f292d6d5ec725d138c?pvs=4

**Comment by Kenshin** [comment]
> 均没有提示API限制需要多次导入

这是正常的，我之前说了，并不是文章长 = 触发分页机制，不触发分页机制不代表就是错误... 😂

确实有转换失败的情况，我也在上面提到了... https://github.com/Kenshin/simpread/issues/6858#issuecomment-2557999517

但你剪藏的内容确实太少了。

1. 阅读模式下文章长度是否正常？
2. 是否使用了 Cloudinary 图床？

建议暂时关闭图床，同时确保在阅读模式下是正常的，然后请在 **隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

**Comment by Kenshin** [comment]
如果仍有问题，录屏给我看下。

**Comment by ggbondpx** [comment]
阅读模式下的文章长度以及图片显示都是没有问题的。我关闭了图床和其他所有的插件后发现问题依旧，目前发现在sciencedirect网站上的其他网页也是出现了同样的问题

**Comment by Kenshin** [comment]
😂

神奇...

导入后会显示成功的提示吗？

<img width="511" alt="image" src="https://github.com/user-attachments/assets/18e6fb2b-7a3b-4cb0-8001-1f5fde0fc3e1" />

你也可以试试 https://onlinelibrary.wiley.com/doi/full/10.1002/advs.202000412 能否导入？

如果还是不行的话，我也没什么好办法了...

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
