### ISSUE TITLE
右下角图标不显示，点击无响应

### ISSUE THREAD

**Issue by chthub** [Kenshin/simpread#686]
在这个网站（<https://seaborn.pydata.org/tutorial/color_palettes.html>）使用阅读模式，发现右下角图标显示不正常，点击无反应。Chrome浏览器，版本1.1.4。我在新版Edge下现装的一个发现也是同样的问题。不是[#216](https://github.com/Kenshin/simpread/issues/216)所说的页面缩放的问题。
截图：

![issue](https://user-images.githubusercontent.com/45276259/76609992-40ad1f80-6553-11ea-9f89-73542d3682b8.png)

**Comment by Kenshin** [comment]
这个页面的 CSS 设计有问题...

你把下面的代码加入到 自定义样式 即可解决。

```
fap i::before {
    content: initial!important;
}
```

位置在 选项页 → 高级设定 → 自定义样式 → （页面左下角）→ 自定义 CSS 就可以了。

**Comment by chthub** [comment]
> 这个页面的 CSS 设计有问题...
> 
> 你把下面的代码加入到 自定义样式 即可解决。
> 
> ```
> fap i::before {
>     content: initial!important;
> }
> ```
> 
> 位置在 选项页 → 高级设定 → 自定义样式 → （页面左下角）→ 自定义 CSS 就可以了。

问题解决，谢谢。
