### ISSUE TITLE
follow页面采用ai总结之后无法被识别

### ISSUE THREAD

**Issue by lxmwwl** [Kenshin/simpread#6860]
### 描述这个错误

![image](https://github.com/user-attachments/assets/0def8352-2c13-4704-8a0d-48253f1dfdbb)
如上图

### 复现步骤

无法识别采用ai总结后的follow页面

### 操作系统

win

### 浏览器

arc

### 发生问题的网址

https://app.follow.is/feeds/all/93243039639663617?view=0

**Comment by Kenshin** [comment]
okay 明天确认下。

**Comment by Kenshin** [comment]
嗨，确实如此，明天修复这个问题。

**Comment by Kenshin** [comment]
嗨，这个站已经被适配，更新方法。

<img width="966" alt="image" src="https://github.com/user-attachments/assets/0095be15-9a96-4e69-b19e-0f948f42556c" />

更新后请重启浏览器，我关闭这个 Issues 了，有任何事情随时再讨论~
