### ISSUE TITLE
导入到 Notion 插件无法安装

### ISSUE THREAD

**Issue by tttsong** [Kenshin/simpread#6861]
### 请描述你的建议或任何内容

为什么我下载导入notion插件跟导入notion增强版并没有弹出来设置框，自己也进不去设置框。

然后正常导入到notion不管哪个网址都失败，只能成功一个标题？

**Comment by Kenshin** [comment]
嗨

使用同步助手的自动同步功能，无法直接安装，需要通过插件管理器安装。

每个插件都有详细说明。

如果不是的话，请详细说明（截图或录屏）

**Comment by tttsong** [comment]
非常诡异，我确实开了简悦同步助手，但是并不能像你说的通过插件管理器安装notion插件。反而，我直接去插件中心安装这两个插件，却能轻松安装上。不过安装上以后依然不生效，没有设置项弹出，一切跟没安装一样
![image](https://github.com/user-attachments/assets/b4720128-6be3-416e-913e-264d05f52706)

**Comment by tttsong** [comment]
notion跟notion增强插件都安装好了，图床也授权好了，总之设置都弄好了。甚至还安装了自动化辅助增强插件，但这个插件教程完全看不懂，就没设置。然后我随便保存一篇少数派的文章到notion，结果还是走的以前没安装任何插件的老路。保存位置也是不能选择的那个老路，文章只有一个标题，啥也没有

**Comment by tttsong** [comment]
授权了一万遍还是不行
![image](https://github.com/user-attachments/assets/0620dec1-a84c-43f1-a3e3-13b2ac6a9996)
![image](https://github.com/user-attachments/assets/4195d342-a987-42f1-9a68-6874af249cf4)
![image](https://github.com/user-attachments/assets/dff9540b-ac30-4b59-ab42-c87b9fed3ddc)
![image](https://github.com/user-attachments/assets/d94d0458-d742-46d0-af5a-d46b33015b08)

**Comment by Kenshin** [comment]
最后一个截图是错误的，不应该是这个提示，正确的提示类似下图

![image](https://github.com/user-attachments/assets/5d02ecc1-1af7-45fc-afb5-89e131868558)

如果你安装正确的话，应该是下图所示的版本号

<img width="575" alt="image" src="https://github.com/user-attachments/assets/67b605af-d01c-43c8-9b65-105e47d92b2c" />

如果不是的话，说明通过插件管理器安装还是错误的。

如果无法安装的话，有两个解决方案：

1. 把你的配置文件发送到 `help#####simpread.pro` 邮箱里面（注意 `#####` → `@`）并注明这个 Issues ID：6861 然后在这里通知我~ （我帮你修复下，老用户福利）

2. 选项页 → 共通 → 关闭自动同步 → 重启浏览器 → 安装这两个插件，然后重启浏览器，确保正确安装，最后在关闭自动同步的地方，重新开启它 → 重启浏览器，再测试下。

**Comment by tttsong** [comment]
我搞定了，原因竟然是那个选择page的页面太不明显了，很难注意到是那里的锅。
但是想提一点建议，就是新版这个导入到notion好像只能导入你给的模板，这样美观是美观了（而且美中不足的是有时候有封面图片，有时候没有），但我自用的话感觉效率低了，还是更喜欢老版的那种直接导入到页面一条一条的。
![image](https://github.com/user-attachments/assets/82307f76-81a0-4ecb-be8d-07ed8304290a)

然后就是图床功能依然不够完美，测试了几条知乎的文章保存，还是会有一两张图片404，用的就是那个账号绑定的。

**Comment by Kenshin** [comment]
> 原因竟然是那个选择page的页面太不明显了

那么明显的地方... 

老用户的话，说句题外话，做为一个 QA 了 5K 多的人来说，一个建议：不要在太晚的时候折腾，我遇到的大部分在这个时间段提 Issues 的用户，他们提的「问题」，基本上都会在第二天自动自愈。

> 是新版这个导入到notion好像只能导入你给的模板，这样美观是美观了（而且美中不足的是有时候有封面图片，有时候没有

只要是 Notion Database 就行，不需要我给你的模板。

> 还是更喜欢老版的那种直接导入到页面一条一条的。

这种是非 Database Page，几年前就淘汰了。

> 图床功能依然不够完美，测试了几条知乎的文章保存

知乎的话，需要修改为下面的方式。

<img width="535" alt="image" src="https://github.com/user-attachments/assets/b1f804f8-c98d-48e2-9975-62b46c77f7b0" />

不过会考虑更自动化的方案解决它~

**Comment by tttsong** [comment]
![image](https://github.com/user-attachments/assets/a9411594-a2b5-4e51-83ae-3ead3e86a63f)
以前这个quicker动作是旧版一键导入notion。
但我发现，新版导入notion的快捷键仍然是nt没变啊，于是手动在阅读模式下按nt，保存路径正常走的是新版2.0notion。
想问一下为啥我用这个动作明明是一样的快捷键，电脑捷径按就是走旧版，人手动按就是走新版啊

**Comment by Kenshin** [comment]
> 新版导入notion的快捷键仍然是nt没变啊

新版是 `n t` 旧版 `s r n t` 当然不一样。

**Comment by Kenshin** [comment]
嗨，各位。

🎉 广受好评的 Notion 图床功能回归啦，采用官方方案后不再会出现意外失效问题。 🥳 

至此，所有导入到 Notion 的功能均已采用官方方案。😄

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/a35cdcd3-55c0-4a03-85d6-7f38d77ca0de" />

# 🔗 链接

[永久链接](https://n.simp.red/posts/630) | [GitHub](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115) | [知乎](https://zhuanlan.zhihu.com/p/1907105157159826036) | [Newsletter](https://newsletter.simpread.pro/p/export-notion-2-1-0)


# 📥 下载地址

[https://simpread.ksria.cn/plugins/details/OpaogjT8KJ](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ)

# 🖼 Notion 图床

无须任何设置，仅需开启此选项，基础账户即可使用。

![image-20250517164907504](https://res.cloudinary.com/simpread/image/upload/v1747471750/config/b5eb5809c1a082e203d5197c9591277b.png)

# 🌟 图片代理功能

2.1.0 版本新增图片代理功能，专门解决部分图片无法转换为 Notion 图床的问题。

Cloudinary 图床（本地方案）也一并加入此功能。

注意：此功能为高级账户权限，如有需要请升级你的账户。😄

> 截止到 2.1.0 版，共内置了三种图床方案：

1️⃣ [Notion 图床](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-11684115)

2️⃣ [Cloudinary 图床（本地化与服务器方案）](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7091995)

3️⃣ [图床插件](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-7092394)

![image-20250517163449366](https://res.cloudinary.com/simpread/image/upload/v1747470892/config/d8cbd7b1d13b50516509243cec27bc5f.png)

详细对比请参考 [说明文档](https://github.com/Kenshin/simpread/discussions/4954#discussioncomment-13177601)。

# 🆕 2.0 版功能回顾

[https://zhuanlan.zhihu.com/p/11575762702/](https://zhuanlan.zhihu.com/p/11575762702/)

# 📈 安装与升级

没有【使用同步助手 · 自动同步】的话，可通过 [此链接](https://simpread.ksria.cn/plugins/details/OpaogjT8KJ) 安装。

已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。

请点击 [#Notion](https://github.com/Kenshin/simpread/discussions/categories/%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E?discussions_q=is%3Aopen+category%3A%E6%8F%92%E4%BB%B6%E8%AF%B4%E6%98%8E+label%3Anotion) 查看更多用法

# 📚 引申

1️⃣ [导入到 Notion 2.0（含 Notion 辅助增强和标注自动化）](https://zhuanlan.zhihu.com/p/11575762702)

2️⃣ [简悦 · 配置库 Notion 版](https://zhuanlan.zhihu.com/p/574148267)

3️⃣ [简悦 + Notion 的一些常见用法：几种典型的导入到 Notion 方案](https://zhuanlan.zhihu.com/p/12592008409)

# 💡 关联

https://github.com/Kenshin/simpread/issues/4955
