### ISSUE TITLE
Chrome停止使用了

### ISSUE THREAD

**Issue by Maj1nBuu** [Kenshin/simpread#6862]
### 请描述你的建议或任何内容

![image](https://github.com/user-attachments/assets/340067b8-889b-4def-8529-68b78eef138a)

**Comment by Kenshin** [comment]
嗨，我看你 Close 这个 Issues 是找到解决方案了吗？

这是解决方案 https://github.com/Kenshin/simpread/discussions/6633

请问是 windows 用吗？你的 Chrome 版本是下面这个吗？

<img width="659" alt="image" src="https://github.com/user-attachments/assets/1094a2b5-48b8-410d-a4a2-8d2c9b72e856" />

如果是的话，我针对你的系统和浏览器版本增加了一个提示，你帮忙看下是否在你的浏览器上打开 https://simpread.pro/ （使用隐私模式），能否出现下面的提示？

<img width="1247" alt="image" src="https://github.com/user-attachments/assets/5a919df8-0a54-4840-a488-621cd0b847e0" />

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
