### ISSUE TITLE
chrome 提示无法使用

### ISSUE THREAD

**Issue by yuanming1** [Kenshin/simpread#6867]
### 描述这个错误

在chrome浏览器中提示已经无法使用插件
![image](https://github.com/user-attachments/assets/b8bdb478-3240-4496-9194-b89b41720d05)

### 复现步骤

在chrome中提示插件将要被删除

### 其他相关说明

![image](https://github.com/user-attachments/assets/b8bdb478-3240-4496-9194-b89b41720d05)

### 操作系统

windows

### 浏览器

Chrome  版本 131.0.6778.205（正式版本） （64 位）

### 发生问题的网址

https://chromewebstore.google.com/detail/%E7%AE%80%E6%82%A6-simpread/ijllcpnolfcooahcekpamkbidhejabll?hl=zh-CN&utm_source=ext_sidebar

**Comment by Kenshin** [comment]
嗨，解决方案 https://github.com/Kenshin/simpread/discussions/6633

**Comment by Kenshin** [comment]
嗨~

# 🎉 简悦已更新到 2.3.0 版，适配 Manifest V3 方案，已上架 Chrome 应用商店

https://chromewebstore.google.com/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

# 🔗 讨论地址

https://github.com/Kenshin/simpread/issues/7326
