### ISSUE TITLE
一键导入全文到notion时报错

### ISSUE THREAD

**Issue by beilo** [Kenshin/simpread#6868]
### 描述这个错误

![image](https://github.com/user-attachments/assets/03e3fb5e-4bf5-4d12-8de1-72a23ebea166)
[simpread-export-notion-faild@1735183149443.json](https://github.com/user-attachments/files/18249215/simpread-export-notion-faild%401735183149443.json)

### 复现步骤

一键导入全文到notion时报错

### 操作系统

macOs

### 浏览器

Chrome 已是最新版本 版本 131.0.6778.205（正式版本） (arm64)

### 发生问题的网址

https://sspai.com/post/71576

**Comment by Kenshin** [comment]
嗨，我看到你 Close Issues 了，解决了这个问题了吗？

**Comment by beilo** [comment]
解决啦 谢谢~

**Comment by Kenshin** [comment]
okay 解决就好 👍
