### ISSUE TITLE
学习通上的内容转阅读模式，单选题失效

### ISSUE THREAD

**Issue by Eulus209** [Kenshin/simpread#6869]
### 需要适配的新站

`https://mooc1.chaoxing.com/mooc-ans/mooc2/work/view?courseId=208874493&classId=104012659&cpi=372248976&workId=37087622&answerId=53786867&enc=4d61ae0af791e109f3df460b9d93e8d2`
如下图，一张为未开启阅读模式的图，另一张开启了阅读模式、
![image](https://github.com/user-attachments/assets/42858fba-a0a8-445e-87fd-1a319d29f633)
![image](https://github.com/user-attachments/assets/5724f568-f67a-4a8b-8345-47444597482a)

### 有需要请描述这个站的性质

学习网站，做完题后，期末进行复习

**Comment by Kenshin** [comment]
嗨，这类具有交互性质的网站适配阅读模式效果非常不好，同时阅读模式也并不适合此类页面的适配。

我关闭这个 Issues 了~
