### ISSUE TITLE
阅读模式下使用 Vimium C 滚动屏幕卡顿

### ISSUE THREAD

**Issue by Fffdmin** [Kenshin/simpread#687]
如题，目前无法测试是 Vimium C 亦或是 简悦自身的问题

**Comment by Kenshin** [comment]
我刚刚测试了  Vimium C 没有遇到你说的问题。

请详细描述，如给出具体页面，同时做了什么操作等...

另外，个人建议使用更广泛的 Vimium Surfingkeys 等同类型产品  😀

**Comment by Fffdmin** [comment]
## 测试网站：
- 小众软件
- 少数派
- CSDN
-----
重新进行了测试，目前在少数派网站激活阅读模式后，个别文章有提示检测到当前网站有大量图片...
没有此类提示的文章也会有浏览卡顿。随便给一个链接：https://sspai.com/post/59429
小众软件：https://www.appinn.com/pet-for-windows/（无卡顿）
CSDN：https://blog.csdn.net/luoyooi/article/details/102990113（无卡顿）

## 系统环境：
操作系统：` Windows 10 (1903)`
浏览器：` Chromium  Edge 80.0.361.66 (官方内部版本) (64 位)`

注意：以上 Issue 在鼠标和触控板模式下均为正常

**Comment by Kenshin** [comment]
> 检测到当前网站有大量图片

这是正常的提示，跟这个问题无关。

***

我也同样测试了你给出 少数派 的链接，也没有发现你说的问题...

你可以这样测试：

- 在隐身模式下，仅启用  Vimium C 与 简悦
- 看看是否还存在这个问题
- 选项页 → 高级设定 → 阅读模式 → **关闭** 大纲功能

看是否还存在这个问题？

**Comment by Fffdmin** [comment]
已解决
