### ISSUE TITLE
图床插件图片重复命名

### ISSUE THREAD

**Issue by donargreys** [Kenshin/simpread#6871]
### 描述这个错误

比如https://sspai.com/post/69972 网页的7个图片，地址都以?imageView2/2/format/webp，通过图床插件上传至piclist本地图床时，文件名都为webp，导致最后一个上传的图片覆盖前6个图片

### 复现步骤

打开https://sspai.com/post/69972 ，点击将图片导入图床，页面7个图片变为最后一个上传的图片

### 其他相关说明

目前插件编辑器https://simpread.ksria.cn/plugins/editor/ 不可用，可否提供可以自己编辑完善插件的方式

### 操作系统

macOS

### 浏览器

chrome 版本 131.0.6778.139（正式版本） (x86_64)

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
嗨，这个问题跟简悦无关，简悦只是调用接口而已。

比如 PicGo 有个 rename 的插件

<img width="612" alt="image" src="https://github.com/user-attachments/assets/49e2f603-11e7-4b0c-84ac-2cf0496bb1e8" />

插件编辑器没问题，但暂时不开放用户定制功能~

**Comment by donargreys** [comment]
图床插件是把整个图片地址包括?imageView2/2/format/webp都传给piclist了，简单的解决方法就是把参数部分去掉

**Comment by Kenshin** [comment]
参数没法去掉，你可以试试去掉少数派的图片参数看看。

**Comment by donargreys** [comment]
手工去掉图片参数是可以工作的

**Comment by Kenshin** [comment]
https://cdnfile.sspai.com/2021/11/17/d603dfc12369401e5d24eeff2c2ddb85.jpg 

你可以访问？

**Comment by donargreys** [comment]
可以打开图片

**Comment by Kenshin** [comment]
隐私模式下，打开它，然后给我截图。

**Comment by donargreys** [comment]
隐私模式下不行，可能是我油猴插件的影响

**Comment by Kenshin** [comment]
跟油猴没关系。

建议还是找下 PicList 有没有类似我提供到的 rename 插件。
