### ISSUE TITLE
想要完全关闭右键菜单，把子项都关了还有一个空的右键菜单

### ISSUE THREAD

**Issue by gzyguo** [Kenshin/simpread#688]
想要完全关闭右键菜单，但是把子项都关了还有一个空的右键菜单

**Comment by Kenshin** [comment]
谢谢反馈，确实是 Bug 只能下个版本修复了。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题**

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
