### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pluveto** [Kenshin/simpread#689]
14:1 Error in event handler: TypeError: Cannot read property 'name' of undefined
    at f (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:1:3088)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:1:4325
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:1:6034

打开一个空白网页, 比如 http://example.com/ 可重现此问题

**Comment by Kenshin** [comment]
抱歉，漏掉了这个 isssues 

我不是很理解你的意思，访问一个不存在的页面，即便出错，会有什么影响吗？

**Comment by pluveto** [comment]
在调试页面的时候, 弹出这个插件的bug比较影响心情罢了

**Comment by Kenshin** [comment]
下个版本会修复。

不过，既然是调试页面，建议不要在生成环境下调试，这样会多出很多意想不到的问题。

至少也要在 **隐身模式** 下...

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 新的方案：只能在正文中进行删除操作。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
