### ISSUE TITLE
阅读模式下csdn的一些文章存在配色异常

### ISSUE THREAD

**Issue by ZeroZhong** [Kenshin/simpread#69]
**相关链接**
* http://blog.csdn.net/usbdrivers/article/details/8103964
* http://blog.csdn.net/21cnbao/article/details/77505330

**截图**
![白色加号](https://user-images.githubusercontent.com/11427697/29765363-75208ca6-8c0d-11e7-8c27-9a21bd2cccd3.PNG)

**Comment by Kenshin** [comment]
@ZeroZhong
okay~ 我在在外面，明天给你回复。

**Comment by Kenshin** [comment]
@ZeroZhong 
像 csdn 这类的 UGC 网页在阅读模式适配上的确有些问题，比如截图的内容是由于如下原因造成的：

![image](https://user-images.githubusercontent.com/81074/29799804-cefb6f44-8c98-11e7-97f4-887698321338.png)

用户不小心加了个背景色造成的。

阅读模式如果把全部的标签都过滤的话，势必会破坏掉一些正常的配色，所以这类的页面并没有太好的办法。

以后的版本可以加入一些选项（已经在计划中了），如：
- 是否全部去除标签内的样式；
- 是否全部去除标签内的class id 等；

**Comment by Kenshin** [comment]
@ZeroZhong 

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

增加了 `自定义样式` 后，你可以方便的修改样式。
