### ISSUE TITLE
无法绑定为知笔记（即无法授权给为知笔记）

### ISSUE THREAD

**Issue by wenhuiwwh** [Kenshin/simpread#694]
- 操作系统 **Win64**

- 浏览器版本 ** 80.0.3987.132**

- 简悦版本 最新版

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#labs?auth=weizhi>

**请描述你的问题**
![P}42}3}4P[KF6QG51FKD05C.png](http://ww1.sinaimg.cn/large/b2f04ec3ly1gd1ecc44ddj21fc0f00u6.jpg)
> 无法授权给为知笔记。😀

**Comment by wenhuiwwh** [comment]
无法无法授权给为知笔记

**Comment by Kenshin** [comment]
为知笔记使用了 **私有 API** 所以在授权上会出现些问题，所以请使用以下步骤

1. 确保登录到为知笔记

2. 在确保第一步的基础上再授权

**Comment by wenhuiwwh** [comment]
你好，你提供的解决方案是不可行的

发送自 Windows 10 版邮件应用

发件人: Kenshin Wang
发送时间: 2020年3月21日 14:03
收件人: Kenshin/simpread
抄送: 王文辉; Author
主题: Re: [Kenshin/simpread] 无法绑定为知笔记（即无法授权给为知笔记） (#694)

为知笔记使用了 私有 API 所以在授权上会出现些问题，所以请使用以下步骤
1. 确保登录到为知笔记
2. 在确保第一步的基础上再授权

**Comment by Kenshin** [comment]
我刚刚测试了下，是没有问题的。
另外，也没有其他用户反馈无法绑定的问题。

**Comment by LSD08KM** [comment]
> 为知笔记使用了 **私有 API** 所以在授权上会出现些问题，所以请使用以下步骤
> 
> 1. 确保登录到为知笔记
> 2. 在确保第一步的基础上再授权

遇到同样问题，按这个方法已解决。
要注意的是，登录网页版为知笔记后，要重新打开简阅的选项页才能绑定成功（只F5刷新也会失败）。

**Comment by Kenshin** [comment]
谢谢 @LSD08KM 的提示。
但我这边其实是不需要这个步骤的...  😂 

@wenhuiwwh 你可以试试 @LSD08KM  这个方式。

PS：如果可用的话，我会通过简悦的消息中心 Push 给大家。
期待你的反馈。

**Comment by shiph0326** [comment]
方法可行，网页登陆为知笔记，然后授权。

**Comment by Kenshin** [comment]
嗨，各位，我把这些内容记录到了 https://github.com/Kenshin/simpread/discussions/2407

***

> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

注意：

1. 为知笔记的**授权时间简悦无法控制**，但**增加了过期自动重新授权的机制**。
2. 增加了为知笔记的私有部署方案

![image](https://user-images.githubusercontent.com/81074/121987877-ed67f380-cdcb-11eb-8d4e-b9d05a56bbf9.png)


## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)

## 评分

Chrome Webstore 用户请帮忙 [五星好评](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
Microsoft Edge 用户请帮忙 [五星好评](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN)

**Comment by liupeng0606** [comment]
![image](https://user-images.githubusercontent.com/9110508/176143270-dbc59847-dc62-4304-98c8-47610bdab952.png)
请问一下，我授权成功了，但是每次点击保存到为知笔记的时候，总是提示，请稍后再试

**Comment by llyzot** [comment]
![image](https://user-images.githubusercontent.com/26666662/176476316-3f18f19b-d1f8-4613-9d66-405e3636cee8.png)
按照上面的操作，确保wiz笔记在登入状态，但是还是无法授权成功
