### ISSUE TITLE
知乎的文章保存到notion的之后每张图片会多一张

### ISSUE THREAD

**Issue by hotwow** [Kenshin/simpread#695]
mac 10.15.3
chrome 82
简悦 最新版

**Comment by Kenshin** [comment]
谢谢反馈。
解决方案 👉 https://github.com/Kenshin/simpread/issues/627

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
