### ISSUE TITLE
为何Markdown文件导出的格式，不是.md，而是.txt呢？

### ISSUE THREAD

**Issue by tongsh6** [Kenshin/simpread#696]
为何Markdown文件导出的格式，不是.md，而是.txt呢？

感觉导出.md文件后，我可以直接使用vscode、markdownpad等类似的工具打开，并预览效果

**Comment by Kenshin** [comment]
**导出为 Markdown** 自然是 `.md` 格式。

请告诉发送问题的页面是什么？

**Comment by tongsh6** [comment]
![image](https://user-images.githubusercontent.com/11657239/77423736-d3c73e80-6e0a-11ea-8ffb-f6ac7a9cd7ae.png)
https://www.jianshu.com/p/937897f6f4f5

**Comment by tongsh6** [comment]
https://cdn.jsdelivr.net/gh/tongsh6/imagehosting/picgo/20200324201006.png
https://dxtz.site/Github%20%E5%9B%BE%E5%BA%8A%20+%20PicGo%20%E5%9B%BE%E5%BA%8A%E6%8F%92%E4%BB%B6%EF%BC%88VScode%E7%89%88%EF%BC%89/

**Comment by Kenshin** [comment]
并没有发生你说的问题，请看截图

<img width="1004" alt="iShot2020-03-25上午10 27 39" src="https://user-images.githubusercontent.com/81074/77495497-b97d7700-6e83-11ea-827c-5f28b468b999.png">

***

建议

- 在隐身模式下仅启用简悦，再测试。

- 看看 chrome://extensions → 简悦 → 详细信息 里面有什么不正常的地方。

- 导出配置文件后，再清除数据（ 或重新安装

**Comment by tongsh6** [comment]
为什么我只有在chrome的无痕模式下，导出的是.md格式？

**Comment by Kenshin** [comment]
这我就不清楚了，估计是你安装了其它扩展造成的问题。

你可以禁用其它扩展再试试，与 `隐身模式` 是一个意思。

**Comment by tongsh6** [comment]
解决了，是因为使用一个插件导致的，https://github.com/ShunCai/QZoneExport

**Comment by luoluoluo22** [comment]
我也遇到了导出为txt的问题，排查后发现是因为和这个插件：Free Download Manager冲突的原因，只能先关闭它后下载后文件后缀为md。不知道有没有更好的办法

**Comment by Kenshin** [comment]
@luoluoluo22 

下个版本提供更好的 Markdown 导出方式，或许会解决这个问题。

你可以留意下个版本的更新说明。（新版本近期发布。

**Comment by luoluoluo22** [comment]
好的，感谢回复。另外我发现在github网页中无法使用[s + r]的快捷键，在其他网页可以使用：


比如：我在浏览这个网页https://github.com/Kenshin/simpread，点击AA快捷键后再按AR快捷键时，没有任何反应





而在其他网址如：https://zhuanlan.zhihu.com/p/128501633。就可以使用SR








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午3:40
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"罗名扬"<1137583371@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 为何Markdown文件导出的格式，不是.md，而是.txt呢？ (#696)





 
@luoluoluo22
 
下个版本提供更好的 Markdown 导出方式，或许会解决这个问题。
 
你可以留意下个版本的更新说明。（新版本近期发布。
