### ISSUE TITLE
做开发切换到移动端模式页面会乱，本地ip添加黑名单只有全长有效，域名无效

### ISSUE THREAD

**Issue by messchow** [Kenshin/simpread#697]
http://192.168.1.66:8081/#/chat?orderid=a28152b4ffe44beda2379c0d62289

**Comment by Kenshin** [comment]
这算是一个 Bug 不过，请不要在开发环境中使用任何有 `content_scripts` 的扩展...

如非要这么做的话，有两个解决办法：

- 在隐身模式禁用全部的扩展，然后调试你需要的页面；

- 安装 Edge （ 这货目前与 Chrome 没有任何区别

我就是这么做的，一切都很正常，没有出现过任意意外。

**Comment by ggtao1983** [comment]
遇到同样问题，原来已经被Kenshin高度关注了，赞一个！

**Comment by Kenshin** [comment]
@ggtao1983 

是的，下个版本会解决。

竟然有这么多在生产环境下做开发的... 难道不怕页面被污染吗？ 😂

**Comment by ggtao1983** [comment]
> @ggtao1983
> 
> 是的，下个版本会解决。
> 
> 竟然有这么多在生产环境下做开发的... 难道不怕页面被污染吗？ 😂

啊哈哈哈，我只是一枚用户，有时候想看看页面的移动版是怎样的，所以就借用了Chrome的开发模式，发现咱们插件激活的时候就会出现整个页面缩小错乱的情况，所以一路找到了这里😂

**Comment by Kenshin** [comment]
@ggtao1983 

抱歉了，这个问题其实是个隐藏的功能，**1.1.4 增加了对手机端样式的适配**，只是没有做到在不启用简悦时候的判断。

**Comment by Kenshin** [comment]
嗨，各位，忘记通知大家了。

这个问题已经被 **1.1.4.6016** 版解决了，

PS：最新版本为 **1.1.4.6025** 自然也没有这个问题了~

我关闭这个 issues 了。
