### ISSUE TITLE
vivaldi浏览器无法保存离线html

### ISSUE THREAD

**Issue by izhouping** [Kenshin/simpread#702]
如下图，需要下载授权，但是未见授权框弹出。是适配问题还是浏览器问题？

![image](https://user-images.githubusercontent.com/43698174/77722218-17e35a80-7028-11ea-8715-37664ce13a9b.png)

**Comment by Kenshin** [comment]
我刚测试了下，是可以弹出下面的对话框

![image](https://user-images.githubusercontent.com/81074/77727141-95ad6300-7034-11ea-8c1e-e34abe5a2b48.png)

把你的环境/浏览器等详细信息告诉我下。

**Comment by izhouping** [comment]
Vivaldi | 2.11.1811.49 (Stable channel) （64 位）

操作系统 | Windows 10 OS Version 1903 (Build 18362.720)

简悦 - SimpRead | 1.14  不过选项里显示
![image](https://user-images.githubusercontent.com/43698174/77727864-2d5f8100-7036-11ea-85c1-35c38f20f963.png)

权限里没有下载
![image](https://user-images.githubusercontent.com/43698174/77727971-6a2b7800-7036-11ea-8e44-a7d3b0e331c3.png)

假设曾经出现过授权，点了拒绝，哪里可以看到或者更改？

**Comment by Kenshin** [comment]
我的也是 **2.11.1811.49 (Stable channel) （64 位）**
同样也是没有问题的。

***

> 简悦 - SimpRead | 1.14 不过选项里显示

这是个 Bug 虽然什么都不影响...  😂 

*** 

> 假设曾经出现过授权，点了拒绝，哪里可以看到或者更改？

按代码来说是没有问题的，它会每次都会重新询问。你可以试着 

- 选项页 → 导出配置 → 清除数据

- 看看能否解决这个问题？再或者重新安装试试？

- 还是不行的话，在隐身模式下使用它，看看能否弹出？

另外，你是否更改过浏览器什么关于安全之类的选项？

**Comment by izhouping** [comment]
在另一台电脑上重新安装了vivaldi和简悦，仍旧一样。（自动同步了设置）
我改过设置，所以有哪些安全选项可能影响呢？

**Comment by Kenshin** [comment]
我不经常使用 vivaldi 浏览器，具体就不太清楚了。

不知道这个浏览器是否也能导出配置 / 重置 的操作？你可以试试。

**Comment by izhouping** [comment]
![image](https://user-images.githubusercontent.com/43698174/77843380-43ed1000-71cf-11ea-8089-104035fd3093.png)
根据你的提醒，修改此项设置后，正常弹出了授权框。
非常感谢，很喜欢这个工具，请你喝杯咖啡略表心意。

**Comment by Kenshin** [comment]
原来竟然还有这种选项... 

搞定就好，希望用的愉快~
