### ISSUE TITLE
与chrome内置的谷歌翻译的取词翻译功能不兼容

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [Kenshin/simpread#707]
当开启阅读会聚焦模式时，谷歌翻译的取词翻译功能无法正常使用。

**Comment by Kenshin** [comment]
Chrome 内置有翻译取词？

有可能存在这个问题，你可以安装简悦自己的取词插件 👉 https://simpread.ksria.cn/plugins/details/ohnTKVHz4a

**Comment by Xinyu-Wu-0000** [comment]
光标选取词语后会出现谷歌翻译图标，点击后会给出词语大意。
![image](https://user-images.githubusercontent.com/57612792/77984632-b3d0d700-7344-11ea-87a1-ffa50f84f3b1.png)

![image](https://user-images.githubusercontent.com/57612792/77984510-5472c700-7344-11ea-894c-53eb626e3950.png)
我尝试一下您的建议先，谢谢！

**Comment by Kenshin** [comment]
你可以试试。

不过，你的截图中所说的 **翻译** 应该也是个扩展吧？你用的不是原生 Chrome 浏览器吧？

**Comment by Xinyu-Wu-0000** [comment]
不太懂浏览器，也可能是一个拓展吧
![批注 2020-03-31 195706](https://user-images.githubusercontent.com/57612792/78023784-db965e00-7389-11ea-9241-e0280acc7a90.png)
您的方法挺好。

**Comment by Kenshin** [comment]
emm 我可能从未用过这个功能，不过既然搞定就好。 😀
