### ISSUE TITLE
隐藏任意元素不小心把内容全部删了，无法恢复了

### ISSUE THREAD

**Issue by lazeman** [Kenshin/simpread#708]
网页地址：
http://www.liejin99.com/20200325/c618802717.shtml

成空白了，浏览器右键菜单，和简悦菜单都没有了，没办法操作，也没办法恢复。建立有个简便的返回网页功能，和重新匹配，直接放到主菜单项。

在聚集模不是空白， 但没有操作菜单。

操作菜单是复杂模式。

**Comment by Kenshin** [comment]
可以看看这个链接的操作https://github.com/Kenshin/simpread/issues/626#issuecomment-566423328

下个版本会改善 **误删自己** 的问题。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 新的方案：只能在正文中进行删除操作。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
