### ISSUE TITLE
太好用了，强烈推荐

### ISSUE THREAD

**Issue by qlbmt** [Kenshin/simpread#710]
就是作者的简阅插件官网不太好搜索到。

**Comment by Kenshin** [comment]
谢谢喜欢，方便的话，可以去 Google Webstore 给个五星好评 👉 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll/reviews

另外，很好奇 **官网不好找** 具体能说说如何不好找吗？

**Comment by qlbmt** [comment]
我之前也用过简悦，后来换电脑了再想找的时候也没想到去github找，就百度，搜索简阅，只有其他大站点的介绍，翻了几页也找不到官网地址。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 中午11:17
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"曲立彬"<331930347@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 太好用了，强烈推荐 (#710)





 
谢谢喜欢，方便的话，可以去 Google Webstore 给个五星好评 👉 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll/reviews
 
另外，很好奇 官网不好找 具体能说说如何不好找吗？

**Comment by Kenshin** [comment]
你可以搜索 简悦 或 simpread 

但是你搜索 **简阅** 占比最高的是小众软件，也算是可以找到~
