### ISSUE TITLE
EDGE浏览器（chromium）无法把文章保存到语雀

### ISSUE THREAD

**Issue by Soon1y** [Kenshin/simpread#711]
用百分浏览器和edge浏览器（版本 81.0.416.41）测试了几篇文章，发现百分浏览器都可以正常保存，edge浏览器则是一直转圈圈。
---
更正：edge的简悦也可以保存文章，转圈圈和在目录里没有找到让我误以为保存失效

**Comment by Kenshin** [comment]
嗯？

这个 issues 与 https://github.com/Kenshin/simpread/issues/700 以哪个为准？

**Comment by Soon1y** [comment]
我在下面都说明了啊





除了一直显示👇，其他的没什么问题，文章也可以正常保存，是我没有仔细查找



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 下午3:01
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"494299583"<494299583@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] EDGE浏览器（chromium）无法把文章保存到语雀 (#711)





 
嗯？
 
这个 issues 与 #700 以哪个为准？

**Comment by Kenshin** [comment]
我关闭这个 issues 并把之前的那个重新开启了。
