### ISSUE TITLE
能否提供网页字体转码功能（繁体字转简体字）

### ISSUE THREAD

**Issue by liuminglm** [Kenshin/simpread#715]
有的网站只有繁体，影响阅读速度，希望可以有自动转换简体字的功能

**Comment by Kenshin** [comment]
谢谢建议，可以考虑此功能。
实现后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，我制作了 [简繁体切换](https://github.com/Kenshin/simpread/discussions/2517) 这个插件，你可以通过安装此插件来解决。

安装地址 https://simpread.ksria.cn/plugins/details/0sZZtfBYyU
使用方法 https://github.com/Kenshin/simpread/discussions/2517

所以，我关闭这个 issues 了。
