### ISSUE TITLE
Kiwi Browser浏览器下使用会使得很多网页一进来就发生变形

### ISSUE THREAD

**Issue by junewong** [Kenshin/simpread#716]
在安卓版的kiwi browser下使用简悦扩展，效果很好，但发现只要扩展是非禁用状态，很多网页一打开就会发生变形，比如豆瓣，进入任意图书详情页，样式都会发生混乱：

![image](https://user-images.githubusercontent.com/1633512/78501732-914d1c80-778f-11ea-92c8-4a3b744295f8.png)

**Comment by Kenshin** [comment]
谢谢反馈，这是个 Bug 详细看 https://github.com/Kenshin/simpread/issues/697

我会考虑出个 Plugin 看看能否顺利解决这个问题。

**Comment by Kenshin** [comment]
嗨，忘记通知了。

这个问题已经被 **[1.1.4.6016](http://ksria.com/simpread/changelog.html#1.1.4.6016)** 版解决了，

PS：最新版本为 **[1.1.4.6025](http://ksria.com/simpread/changelog.html#1.1.4.6025)** 自然也没有这个问题了~

我关闭这个 issues 了。
