### ISSUE TITLE
保存到有道云笔记问题

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#717]
每次使用保存到有道云笔记都需要在选项里对其重新授权，否则会出现“请稍后再试！”的提示

**Comment by Kenshin** [comment]
有道云笔记使用了 私有 API 所以它的授权时间很短，但授权过期后会自动提示重新授权，如下图

![image](https://user-images.githubusercontent.com/81074/78624423-1f262600-78bc-11ea-8859-61ac814fa2f6.png)

**Comment by 1095533987** [comment]
嗯嗯 现在授权过期会显示如图所示的提示了 问题已解决 谢谢！
