### ISSUE TITLE
一个问题与建议

### ISSUE THREAD

**Issue by T-233** [Kenshin/simpread#719]
首先，十分感谢作者开发出这么好的插件！非常好用。

**一个问题：**
    大纲(目录)显示不全
![image](https://user-images.githubusercontent.com/48357458/78687499-ccce1f00-7926-11ea-8904-d9137ec52336.png)
**建议：**

1. 目录可以选择显示在右边。
2. 保存时可以把代码格式保存下来就好了。

**Comment by Kenshin** [comment]
谢谢反馈。

> 显示在右侧的话，可以通过 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决

> 代码高亮是可以保存的，只是为了降低保存文件的 size 代码高亮使用了 https://cdnjs.com/libraries/highlight.js 的 cdn 方案。

**Comment by T-233** [comment]
谢谢回复！

**Comment by Kenshin** [comment]
没有疑问的话，我关闭此 issues 了 😀
