### ISSUE TITLE
稍后阅读列表入口太深，不容易调出

### ISSUE THREAD

**Issue by wxj1819** [Kenshin/simpread#72]
插件功能非常好，之前一直用印象笔记的一款类似插件，不过下架了。该软件很不错，支持
希望稍后阅读列表可以通过快捷键调出。字体行间距可调小一些

**Comment by Kenshin** [comment]
感谢评价~
不错的想法，之前也有些用户提出过类型的需求。
由于 `1.0.3` 已经功能冻结了，所以这个需求将会在 `1.0.4` 时实现。

PS：之所以没有加更方便的入口是因为：`1.0.1` 之前的稍后读功能并不完善，但本周发布的  `1.0.3` 增加了 `导出到生产力工具` 的功能，所以稍后读变得有意义了。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
详细请看 [更新日志](http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update)
