### ISSUE TITLE
无法绑定Notion

### ISSUE THREAD

**Issue by dominolu** [Kenshin/simpread#724]
在授权绑定时，提示“获取Notion授权失败，请稍后再试”

**Comment by Kenshin** [comment]
请先确保已经登陆 Notion 然后在试试。

**Comment by dominolu** [comment]
Notion是登录状态的，就是绑定不行

**Comment by Kenshin** [comment]
我刚测试了下，没有问题。

你是什么浏览器？什么系统？另外，你的浏览器设置了什么安全权限吗？类似 cookie 之类的？

**Comment by dominolu** [comment]
macbook pro ,OS 10.14.6,chrome浏览器，没有特别安全权限设置

**Comment by Kenshin** [comment]
这很奇怪...

你要不换个 Edge 再试试？简悦也上架 Edge 了  👉 https://microsoftedge.microsoft.com/addons/detail/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN

PS：不是让你更换浏览器，而是看看到底是什么问题导致...

**Comment by kaaaaai** [comment]
@Kenshin 试了一下 Chrome 更新后还是无法授权成功，但在 edge 上就可以了，而且很快就授权成功了

**Comment by Kenshin** [comment]
@kaaaaai 

Chrome 因为是最新的 1.1.4.6022 所以会发生授权失败。

Edge 因为用了 **老方案** 所以，暂时不会产生这个问题。

***

我会彻底解决这个问题，关联 Issues 👉  https://github.com/Kenshin/simpread/issues/809

**Comment by Kenshin** [comment]
嗨，我找到个临时解决方案，细节请看 https://github.com/Kenshin/simpread/issues/809#issuecomment-648084621

如果方便的话，请使用上述链接给出的解决方案，并方便的话，请告知哪个版本的可以授权成功。

**Comment by Kenshin** [comment]
嗨，简悦 1.1.4.6025 终于发布了！

如果你是个 Notion 重度使用者的话，就会知道 Notion Web Clipper 有多不好用了...

还好的是，同样我也是 Notion 的使用者。历经一个星期三次迭代后，简悦终于完美实现 Notion Web Clipper  的全部功能了。

包括：

- 可以选择 Page 或 Database 方式导出
- 支持 Notion.so 作为图床的方式导出
- 完美实现 Database 外链

详细请看  👉  http://ksria.com/simpread/docs/#/Notion

如果你对 Notion Web Clipper 不是很满意的话，完全可以使用简悦来替代它了~ 

最后，祝你粽子节安康！

***

之前有使用 1.1.4.6025 离线包的用户，可以替换为 Chrome Webstore 版本了 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

**Comment by Charles29-huang** [comment]
更新到了2.0.0版本，只能获取到第一个Notion page

**Comment by Kenshin** [comment]
@Charles29-huang 

关于你的问题，可以参考下 https://github.com/Kenshin/simpread/issues/1288 的内容，或许对你有所帮助。 😃

**Comment by bradlisy** [comment]
All cookies allowed 的情况下，如图所示，没有其他的任何follow-up信息了。。。#1773 看了一圈好像也没有相符的情况

![image](https://user-images.githubusercontent.com/36872502/145058071-fcb3bab4-1982-49b4-ae56-da7727cac98e.png)

**Comment by Kenshin** [comment]
@bradlisy 

emmm 这个问题确实很玄学，你可以这么试试：

1. 退出你的 Notion 账户
2. 导出简悦的配置文件
3. 重新安装简悦
4. 登录你的 Notion 账户
5. 不改动任何配置直接授权

看看能否解决？另外，上面的方案最好能找个新的浏览器测试。

**Comment by bradlisy** [comment]
> 按照上述步骤，确实解决了问题。果真玄学了些。。。感谢指导~

**Comment by bradlisy** [comment]
> @bradlisy
> 
> emmm 这个问题确实很玄学，你可以这么试试：
> 
> 1. 退出你的 Notion 账户
> 2. 导出简悦的配置文件
> 3. 重新安装简悦
> 4. 登录你的 Notion 账户
> 5. 不改动任何配置直接授权
> 
> 看看能否解决？另外，上面的方案最好能找个新的浏览器测试。



> @bradlisy
> 
> emmm 这个问题确实很玄学，你可以这么试试：
> 
> 1. 退出你的 Notion 账户
> 2. 导出简悦的配置文件
> 3. 重新安装简悦
> 4. 登录你的 Notion 账户
> 5. 不改动任何配置直接授权
> 
> 看看能否解决？另外，上面的方案最好能找个新的浏览器测试。

按照上述步骤，确实解决了问题。果真玄学了些。。。感谢指导~

**Comment by bradlisy** [comment]
> @bradlisy
> 
> emmm 这个问题确实很玄学，你可以这么试试：
> 
> 1. 退出你的 Notion 账户
> 2. 导出简悦的配置文件
> 3. 重新安装简悦
> 4. 登录你的 Notion 账户
> 5. 不改动任何配置直接授权
> 
> 看看能否解决？另外，上面的方案最好能找个新的浏览器测试。

按照上述步骤，确实解决了问题。果真玄学了些。。。感谢指导~

**Comment by Kenshin** [comment]
@bradlisy 

okay 没问题就好，我把这个操作也记录到了 https://github.com/Kenshin/simpread/discussions/1773

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4

**Comment by SinZhangQ** [comment]
> @SinZhangQ
> 
> 请使用[#1773 (comment)](https://github.com/Kenshin/simpread/discussions/1773#discussioncomment-2345217) 提到的方案。

大佬这么晚还在回复，辛苦啦。试了试您新提到的方法，可以了，谢谢您。已支持会员。

**Comment by Kenshin** [comment]
@SinZhangQ 

哈哈，谢谢。如果只用 Notion 基础账户就可以。

我一般晚上都会看下 Github Issues 有方便回复的问题就回复下，毕竟这么晚还提 Issues 有可能是「真爱但卡在某个环节」的用户。😉
