### ISSUE TITLE
代码高亮无法显示代码注释

### ISSUE THREAD

**Issue by instory** [Kenshin/simpread#725]

**Comment by Kenshin** [comment]
具体 URL ?

**Comment by instory** [comment]
https://www.jianshu.com/p/7fce2955f2db 

![image](https://user-images.githubusercontent.com/17408691/79309376-c5ad9f00-7f2c-11ea-99a9-a10b7220f4b6.png)
![image](https://user-images.githubusercontent.com/17408691/79309441-e1b14080-7f2c-11ea-8333-b9f96c547200.png)

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/79326394-5d1eec00-7f45-11ea-9eb6-ef9386a9ec1b.png)

我的没有问题，确认下代码高亮插件与简悦的版本。

> 简悦在 1.1.4 版，同时代码高亮插件删除后再重装

**Comment by instory** [comment]
en 试了下mac 也没问题 可能是win的chrome用了个低版本的吧
