### ISSUE TITLE
阅读模式识别不对

### ISSUE THREAD

**Issue by EngineerLeonJ** [Kenshin/simpread#728]
- 发生问题的地址 <https://www.learningscientists.org/blog/2016/5/10-1>

**请描述你的问题**
阅读模式未能提取正文

**Comment by Kenshin** [comment]
谢谢反馈。🙏
你可以用重新高亮来解决，或者自定义这个站点。

如果是大众类的网站的话，我会不定期加入到适配列表。

**Comment by EngineerLeonJ** [comment]
好的，这种情况蛮少见的

**Comment by Kenshin** [comment]
这个站的结构太不 **规矩**... 不过，一般来说很多的 E文类的页面都存在这个问题。

简悦会着手解决这些问题。 😀
