### ISSUE TITLE
代码增强的插件我测试C和C++代码的注释不会显示

### ISSUE THREAD

**Issue by GengchenXU** [Kenshin/simpread#729]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <http://c.biancheng.net/view/2269.html>

**Comment by Kenshin** [comment]
谢谢反馈，确实如此，修复后会通知你。

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀 

更新方法：点击上面链接中的 **安装当前插件** 即可。
