### ISSUE TITLE
请求适配PMCAFF

### ISSUE THREAD

**Issue by GianisLee** [Kenshin/simpread#73]
地址: http://www.pmcaff.com/site/selection

**Comment by Kenshin** [comment]
okay 没有问题~
适配后，将会跟 `1.0.3` 在本周内一起发布。

**Comment by Kenshin** [comment]
@GianisLee 
新站已经适配~  

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

此 issues 将关闭~
