### ISSUE TITLE
要是能自定义动作放在外面就好了

### ISSUE THREAD

**Issue by Boms** [Kenshin/simpread#730]
我现在用简悦将页面保存到Notion，操作方式是“A A”->鼠标移动到"..."按钮上->动作->保存到Notion。
要是能自定义将保存到Notion放到“...”按钮上方，就可以大大提高效率了。

**Comment by Kenshin** [comment]
谢谢建议。

目前控制栏确实需要再改造改造了，功能太多导致无法个性化定制。

**Comment by kaaaaai** [comment]
Notion 有导入快捷键吗，看到其他的都有，没看到 Notion 的

**Comment by swj1442291549** [comment]
> Notion 有导入快捷键吗，看到其他的都有，没看到 Notion 的

`nt`

**Comment by Kenshin** [comment]
额，抱歉，漏掉了这个 issues

`1.1.4` 版本是忘记 Notion 的快捷键了，`1.1.4.6016` （包括以后版本）已经加入快捷键。

所以，我关闭这个 issues 了~
