### ISSUE TITLE
关于阅读模式代码获取错误

### ISSUE THREAD

**Issue by SXL66** [Kenshin/simpread#731]
在W3Cschool的网站教程中使用阅读模式会出现代码片段丢失的问题，同时由于阅读模式中代码片段背景颜色为黑色，使用高亮代码插件后部分字段会变成灰色，灰色代码段与黑色的背景不容易区分，建议换一种高亮颜色，或者开放插件代码修改让我们可以自行修改颜色。

**Comment by Kenshin** [comment]
我刚才测试了下，没有遇到你说的问题，如 https://www.w3school.com.cn/htmldom/dom_elements.asp

![image](https://user-images.githubusercontent.com/81074/79444917-69bb4700-800e-11ea-8b31-06f393740a27.png)

最好指出具体的 URL 

***

> 建议换一种高亮颜色，或者开放插件代码修改让我们可以自行修改颜色

代码高亮的颜色是 `自识别` 方案，并未做任何调整。

***

如果你了解些前端的话，可以通过自定义样式解决代码高亮的配色的问题。
另，代码高亮使用了 https://github.com/highlightjs/highlight.js 方案。

**Comment by SXL66** [comment]
我使用的是chrome，你可以试下https://www.w3cschool.cn/wkspring/xypt1icg.html
例如这是原网页中的一个代码段：

在使用了阅读模式高亮代码后呈现的效果是这样，代码与背景区分度不高

并且代码中bean的id和class部分代码缺失

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 晚上6:20
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"渊水"<1771175359@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 关于阅读模式代码获取错误 (#731)





 
我刚才测试了下，没有遇到你说的问题，如 https://www.w3school.com.cn/htmldom/dom_elements.asp
 

 
最好指出具体的 URL
 
  
建议换一种高亮颜色，或者开放插件代码修改让我们可以自行修改颜色
  
代码高亮的颜色是 自识别 方案，并未做任何调整。
 
 
如果你了解些前端的话，可以通过自定义样式解决代码高亮的配色的问题。
 另，代码高亮使用了 https://github.com/highlightjs/highlight.js 方案。

**Comment by Kenshin** [comment]
emmm 确实有点问题，我明天详细确认下。

**Comment by SXL66** [comment]
感谢，辛苦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kenshin Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 晚上7:05
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"渊水"<1771175359@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 关于阅读模式代码获取错误 (#731)





 
emmm 确实有点问题，我明天详细确认下。

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀 

更新方法：点击上面链接中的 **安装当前插件** 即可。
