### ISSUE TITLE
内容缺失问题

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#732]
![QQ截图20200416194434](https://user-images.githubusercontent.com/21174990/79452670-13083a00-801b-11ea-94a9-a8e5243ab99e.png)
![QQ截图20200416194455](https://user-images.githubusercontent.com/21174990/79452684-1b607500-801b-11ea-9a9c-f40a97c8c636.png)

在访问这个网站：https://blog.csdn.net/kongmin_123/article/details/82048392

发现进入简悦阅读模式后内容有缺失 如图

**Comment by Kenshin** [comment]
谢谢反馈，应该是代码高亮插件的锅，误将 table 识别成代码段了。

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀 

更新方法：点击上面链接中的 **安装当前插件** 即可。
