### ISSUE TITLE
看雪论坛 无法正确显示文章正文

### ISSUE THREAD

**Issue by JsHuang** [Kenshin/simpread#734]
**请说明发生问题的环境**

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://bbs.pediy.com/thread-223721.htm>

**截图**
![image](https://user-images.githubusercontent.com/5506543/79554605-e151aa80-80d0-11ea-9245-ac14d2099c35.png)
![image](https://user-images.githubusercontent.com/5506543/79554666-f62e3e00-80d0-11ea-8a51-dfe83f769d26.png)

**Comment by Kenshin** [comment]
谢谢反馈。

即便使用重新高亮也会发生错误，你可以通过自定义适配站点来手动解决。

如果这个站是大众（常见）类型的网站，我会把它加入到适配列表中的。

**Comment by binsee** [comment]
已适配: #1063

**Comment by binsee** [comment]
关联pr #1067

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
