### ISSUE TITLE
更新后每次打开chrome的时候界面都会自动弹出来怎么关闭？？

### ISSUE THREAD

**Issue by fire-xch** [Kenshin/simpread#736]

**Comment by Kenshin** [comment]
应该是 Firefox 用户吧？这个问题应该是 1.1.x 版本才有的，请升级到最新版。
目前最新版只提供了 zip 下载方案。

**Comment by fire-xch** [comment]
问题已经解决，是Chrome出了BUG没法保存插件设置，其他插件例如Momentum也没法保存，所以每次打开Chrome的时候程序都认为我是刚刚装完插件的，所以就弹出了设置页面，然后我把Chrome给重装了。感谢你的回应。

**Comment by Kenshin** [comment]
原来如此... 搞定就好。

之前 Firefox 1.1.x 版本就存在这个问题，是因为有些 Firefox 用户关闭浏览器会清除 cookie 造成的。
