### ISSUE TITLE
选项页部分乱码问题

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#737]
![QQ截图20200419142752](https://user-images.githubusercontent.com/21174990/79681187-cdca4f00-824a-11ea-9184-038862403eb0.png)

很奇怪 就是突然进入选项页，所有的一级标题全部乱码了，目前是什么原因引起的还不知道，如果有遇到同样问题且知道原因的望告知~

**Comment by Kenshin** [comment]
emmm 

我在测试阶段遇到过，而且仅是一次... 正式版从未发生过。

应该是在 **自动授权后自动弹出选项页** 时发生的吧？

目前没有什么解决办法，导出配置后，重新安装简悦。 😂

**Comment by 1095533987** [comment]
唔 好吧 不过重装倒是不用 关闭浏览器所有窗口再次打开就好了 :yum:

**Comment by Kenshin** [comment]
原来重开浏览器就行了...  😰  

谢谢提示，我关闭这个 issues 了，并放到 **常见问题** 里面。
