### ISSUE TITLE
导出为Markdown，能否将原文地址作为超链接的形式？

### ISSUE THREAD

**Issue by Peter-JXL** [Kenshin/simpread#738]
导出为Markdown，默认的是第一行的格式是： 原文地址  后面加上网站链接，例如
本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址https://mp.weixin.qq.com/sbiz..........5bb6f4#rd

如果URL太长，有点不美观，能否支持将原文地址转为Markdown的超链接形式？
例如[原文地址](https://mp.weixin.qq.com/sbiz..........5bb6f4#rd)

**Comment by Kenshin** [comment]
谢谢建议，会考虑类似的方案，确实如你所说，URL 太长的话不是很美观。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 目前的方案：取主域名，这样不会出现过长的问题了。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀

**Comment by lslz627** [comment]
建议导出 notion 的时候、也保留 本文由 简悦 SimpRead 转码， 原文地址 这样的说明

现在的情况是：

![image](https://user-images.githubusercontent.com/18484770/90312406-d56add80-df36-11ea-9434-0d4a0fe099ae.png)

点击进去原文：

![image](https://user-images.githubusercontent.com/18484770/90312426-f5020600-df36-11ea-9e42-16f25cb63d81.png)

产生这样需求的原因是：我有时候保存的时候是使用 page 的方式保存、并非使用 database 方式、所以还是需要 url 链接的

**Comment by Kenshin** [comment]
@lslz627 
可以考虑，我先记下来。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
