### ISSUE TITLE
为知笔记授权问题

### ISSUE THREAD

**Issue by TheStepOfAntonyGeek** [Kenshin/simpread#739]
输入为知笔记账号密码，提示授权失败...

**Comment by TheStepOfAntonyGeek** [comment]
想到了更好的解决办法，生成临时页面后，使用windows端的为知悬浮框上保存到为知笔记

**Comment by Kenshin** [comment]
确实是个办法，谢谢自行发现它~

不过，我在 选项页 - 帮助中心 和 Github issues 里面提到了。😀
