### ISSUE TITLE
腾讯新闻图片浏览页面

### ISSUE THREAD

**Issue by pwvictor** [Kenshin/simpread#74]
http://news.qq.com/a/20170902/056051.htm#p=1

正常的的新闻页面，不带p参数，带了P参数简悦看不了。 排除表估计要使用正则匹配功能

**Comment by Kenshin** [comment]
的确是这样，因为正则规则是

```
http://*.qq.com/a/*/*.htm
```

刚才找了好几个都没有... 什么时候会出现 `#p=1` 的情况？

**Comment by pwvictor** [comment]
http://news.qq.com/a/20170913/019097.htm#p=1   一般是图片新闻页面，主要是轮播图片的页面。首页新闻中，如果带图片的标题，就是这种页面。

**Comment by Kenshin** [comment]
@pwvictor 
okay，这个 url 的结构虽然与 `http://*.qq.com/a/*/*.htm` 一致，但它不应该进入 `阅读模式` 才对。（因为是图片轮播，并没有阅读的价值）

解决方案，请看关联问题 https://github.com/Kenshin/simpread/issues/90

我会在下个版本解决这个问题。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)
