### ISSUE TITLE
无论选择聚焦模式还是临时阅读模式，页面均没有任何变化。

### ISSUE THREAD

**Issue by MingchaoShi** [Kenshin/simpread#741]
**请说明发生问题的环境**

- 操作系统 **Windows 7**

- 浏览器版本 ** 81.0.4044.122（正式版本） （64 位）**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://blog.csdn.net/yyw_0429/article/details/82320409>

**请描述你的问题**

打开CSDN的这个页面，点击浏览器工具栏的简悦图标，无论选择聚焦模式还是临时阅读模式，页面都没有任何变化，右键选择此功能也一样。
其他网站，比如：https://sspai.com/post/39491，https://www.appinn.com/simpread-lite/，也一样。

**Comment by Kenshin** [comment]
估计是你的配置文件有问题。
选项页 → 导出配置 → 清除数据（或重新安装简悦） 

再试试。

**Comment by MingchaoShi** [comment]
清除数据后正常了，谢谢！

**Comment by Kenshin** [comment]
okay 没问题的话，我关闭这个 issues 了  😀
