### ISSUE TITLE
能否让“模仿 Safari 阅读模式样式”情况下可以切换颜色？

### ISSUE THREAD

**Issue by jkwtbmyz** [Kenshin/simpread#742]
安装了这个插件后切换背景色就无效了。

但是我还是很喜欢这个插件，我认为这个样式甚至应该作为默认的样式而不仅仅是一个插件。

那么退一步来说，能否在这个插件下也能切换背景色呢？

我之前提过另一个问题[https://github.com/Kenshin/simpread/issues/609](url)
我的设备切换背景色会影响字体显示效果，我喜欢的背景色的字体显示很难看，我听从了你的建议，自定义CSS修改了颜色。

如果您愿意解决这个issue的需求的话，希望能考虑到我上面的设定，谢谢~

**Comment by Kenshin** [comment]
看来你非常喜欢 **模仿Safari阅读样式** 这个插件。

目前确实没有随主题自动切换的功能，当然，我会考虑升级下这个插件。

在此之前，你可以如 https://github.com/Kenshin/simpread/issues/609 我教你的方式手动写 CSS 来实现。
毕竟总是切换主题并不会经常发生的。 😀

**Comment by jkwtbmyz** [comment]
> 看来你非常喜欢 **模仿Safari阅读样式** 这个插件。
> 
> 目前确实没有随主题自动切换的功能，当然，我会考虑升级下这个插件。
> 
> 在此之前，你可以如 #609 我教你的方式手动写 CSS 来实现。
> 毕竟总是切换主题并不会经常发生的。 😀

是的，我很喜欢，毕竟Safari默认就是这个界面，肯定有它的独到之处。

我确实不需要频繁切换主题，所以如果能在这个插件下设定某一个特定的颜色，那也是极好的，无法切换主题也OK，有什么简单的办法吗？

**Comment by Kenshin** [comment]
当然可以了，你可以告诉我你需要使用的主题名称。

**Comment by jkwtbmyz** [comment]
> 当然可以了，你可以告诉我你需要使用的主题名称。

主题是卯之花色，但是如我前面所说，不是喜欢这个主题的背景色，而是这个主题下我的字体显示才正常，我需要的背景色是rgb(255, 242, 226)，通过修改CSS实现的。

**Comment by Kenshin** [comment]
没理解你的意思...

> 我需要的背景色是rgb(255, 242, 226) 

这不就是 https://github.com/Kenshin/simpread/issues/609 说的问题吗？ 我已经告诉你了。

**Comment by jkwtbmyz** [comment]
> 没理解你的意思...
> 
> > 我需要的背景色是rgb(255, 242, 226)
> 
> 这不就是 #609 说的问题吗？ 我已经告诉你了。

我好像确实没说清楚，这个插件下 设置的CSS 是无效的，怎么都是白色。

我想要这个插件下还能让CSS设定的颜色生效。

**Comment by Kenshin** [comment]
你还是没有表达清楚....

> 这个插件下 设置的CSS 是无效的

我在 https://github.com/Kenshin/simpread/issues/609#issuecomment-553218862 不是已经给出方案了吗？

***

要不这样吧，你按照我的提问来说明下：

1. 你安装了 **模仿 Safari 阅读模式** 后现在是什么效果（请截图）

2. 你需要什么样的主题背景。（也就是说你需要的主题背景是什么，禁用  **模仿 Safari 阅读模式** 并切换到你需要的主题下面，再此截图

**Comment by jkwtbmyz** [comment]
安装插件是这样的，背景色无论如何切换怎么都是白色。我此时已经设定了CSS的，但是未生效。
![image_46](https://user-images.githubusercontent.com/17421620/80400987-2efabe00-88ee-11ea-82e3-17e3d577958c.png)
![image_45](https://user-images.githubusercontent.com/17421620/80400996-315d1800-88ee-11ea-895b-28132928fdd0.png)
禁用插件就是这样，无论如何切换背景色都是黄色，设定的CSS生效了。
![image_44](https://user-images.githubusercontent.com/17421620/80401423-e394df80-88ee-11ea-9c06-2e2081f288df.png)
![image_43](https://user-images.githubusercontent.com/17421620/80401435-e7286680-88ee-11ea-9457-9316fc6ca808.png)

**Comment by Kenshin** [comment]
你可以在自定义样式中加入下面的代码

```
sr-read {
    background-color: rgb(252, 245, 237)!important;
}
```

具体方法可以看 https://github.com/Kenshin/simpread/issues/609#issuecomment-553218862 这个描述。

😀

**Comment by jkwtbmyz** [comment]
> sr-read {
>     background-color: rgb(252, 245, 237)!important;
> }

谢谢，搞定了。

**Comment by Kenshin** [comment]
搞定就好。

等这个插件更新后，我会在这里通知你。 😊

**Comment by jkwtbmyz** [comment]
另，更理想的情况是两侧的底色是浅色，文字背景色是稍微深一点，现在底色都是白色，只能修改文字背景色。
![image_47](https://user-images.githubusercontent.com/17421620/80778886-6c847300-8b9c-11ea-9633-0ee488d541f1.png)
这是另一个插件的配色，还挺舒服的。
![image_48](https://user-images.githubusercontent.com/17421620/80778890-6f7f6380-8b9c-11ea-9722-08e682685921.png)

辛苦！

**Comment by Kenshin** [comment]
```
.simpread-read-root {
    background-color: rgb(239, 228, 206)!important;
}

sr-read {
    background-color: rgb(252, 245, 237)!important;
}
```

之前把你的信息漏掉了。

**Comment by Kenshin** [comment]
嗨，我更新了[ 模仿 Safari 阅读模式样式](https://simpread.ksria.cn/plugins/details/tbjTx33iAA) 主要修复了你说的这些问题。

有时间确认下，没问题的话，请关闭这个 issues

**Comment by 2019YKL** [comment]
装了Safari样式扩展插件后，打开文章都是默认一片灰，根本看不清，但是重新去点设置主题就能恢复正常，希望修复一下
![image](https://user-images.githubusercontent.com/51532948/126917609-52436083-355d-4071-860b-78e7f48d1209.png)

**Comment by 2019YKL** [comment]
![image](https://user-images.githubusercontent.com/51532948/126917652-812e260e-9dfc-437d-a40a-fc7f3431e935.png)
我在设置中弄了默认样式，但显然，这并没有生效

**Comment by 2019YKL** [comment]
![image](https://user-images.githubusercontent.com/51532948/126917721-fa7a0d2c-e01b-464f-b7fe-686aa18d48a4.png)
所装的插件只有这两个，然后浏览器是edge的版本 92.0.902.55 (官方内部版本) (64 位)

**Comment by Kenshin** [comment]
@2019YKL 

其他人没有遇到你说的问题，是不是开启了系统 or 浏览器的暗色模式？
