### ISSUE TITLE
LaTex形式的数学公式保存到本地的md文件中不适配

### ISSUE THREAD

**Issue by Ziffer-yan** [Kenshin/simpread#743]
这是在原网页中使用simpread的视图：
![网页视图](https://user-images.githubusercontent.com/33079825/80282356-96283f00-8743-11ea-885d-8bf75887fd26.jpg)
-----------------------------------------------------------------
这是md导出到本地后使用typora中打开项是的视图：
![md视图](https://user-images.githubusercontent.com/33079825/80282391-bf48cf80-8743-11ea-902d-9e27cbe11279.jpg)

**Comment by Kenshin** [comment]
谢谢反馈。
这应该是 Markdown 这个库造成的问题，目前还没有好的解决办法。

***

不过，个人觉得像 LaTex 这样的页面，还是不要存为 Markdown 比较好。因为解析的话确实有些问题。
你可以使用 **离线 HTML** 完美支持 LaTex 。

换个角度说，Markdown 支持 LaTex 应该是其使用的编辑器做的事情，而各个编辑器的行为都不太一样。

我先记 Bug 吧，如果找到好的解决方案会通知到你。

**Comment by eromoe** [comment]
现在导出含有latex 的文章还是会出现latex 未识别的情况

![image](https://user-images.githubusercontent.com/3938751/90106418-f63a0400-dd79-11ea-964a-9b590a8fc873.png)


能不能直接调用目标站点的mathjax 的函数，将每个latex 都转换成下列内容 来替换原文
![image](https://user-images.githubusercontent.com/3938751/90106469-08b43d80-dd7a-11ea-826d-aa1621c81521.png)

在导出markdown 的时候，inline latex 加上 `$...$` ,  block latex 加上 `$$ ... $$` ， 这个是目前包括印象笔记在内大部分markdown latex 支持的方式。

**Comment by Kenshin** [comment]
@eromoe 

这个问题解决了，暂时未发布，明天确认下告诉你是什么格式。

**Comment by eromoe** [comment]
噢噢！ 非常期待，这个功能真没有一个剪藏工具能实现！

**Comment by Kenshin** [comment]
@eromoe 

可以转换为为 `$$...$$`，但具体效果并不是 100% 完美，因为不同的文章在转换时有太多的不确定性了。

**Comment by eromoe** [comment]
不能用过mathjax 的 class 来指定 `$...$` 还是 `$$ ... $$` 吗？我看他是有标注的
![image](https://user-images.githubusercontent.com/3938751/90216844-3d83cb80-de32-11ea-84c3-917027e69ae4.png)

**Comment by Kenshin** [comment]
@eromoe 

没办法判断这么精细，要不你给我个上图对应的 URL 我详细研究下。

**Comment by eromoe** [comment]
sorry， 发在另一个issue 里了这里忘记贴了
https://www.cnblogs.com/RyanXing/p/9469338.html

**Comment by Kenshin** [comment]
@eromoe 

完美解决了

![image](https://user-images.githubusercontent.com/81074/90227240-ca388480-de46-11ea-9972-75eead608a87.png)

**Comment by eromoe** [comment]
WOW! Amazing! 期待发布！

**Comment by eromoe** [comment]
@Kenshin 
已经更新新版，发现转义还存在有问题 :

![image](https://user-images.githubusercontent.com/3938751/90748153-66113700-e304-11ea-9d43-3346dfca2b7e.png)

![image](https://user-images.githubusercontent.com/3938751/90748106-542f9400-e304-11ea-8c65-cd9992bc1d3d.png)

粗看下来是`=`和`[] ` 有前面会被加上斜杠，这是html 的转义吗？

**Comment by Kenshin** [comment]
@eromoe 

转义的问题，我集中到了 #1064 这个 Issues 是 Latex 的问题，所以我先关闭此 Issues，转义的解决后，会通知你。

**Comment by Kenshin** [comment]
各位，问题解决了，一个悲伤的事情是：**因为是 library 出现了问题，所以只能下个版本解决**。

不过，我试试用 **插件** 的方式绕过这个问题。

***

### 涉及到的范围

> 全部需要使用 Markdown 的地方均存在此问题。

### 如何处理

> 等我的插件来解决
