### ISSUE TITLE
浮动工具面板的 Tooltip 位置错误

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#744]
唔。。。真是一个小问题，不过有强迫症可能很难受
![QQ截图20200429175352](https://user-images.githubusercontent.com/21174990/80583368-b0636500-8a42-11ea-9e2a-b7a2a302a3d0.png)

如图，浮动的提示文字前边部分显示不完整，应该是靠近父容器边缘受影响😁

**Comment by Kenshin** [comment]
谢谢反馈。 😃 

这个问题其实在未发布的时候就发现了，但是忘记改了...  😰

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
