### ISSUE TITLE
插件编辑器新建插件无反应

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#745]
按照文档上的提示操作后，点击新建插件无反应。

![QQ截图20200429234458](https://user-images.githubusercontent.com/21174990/80617574-dace1600-8a74-11ea-85fe-173e5d39c503.png)

![QQ截图20200429234532](https://user-images.githubusercontent.com/21174990/80617599-e28dba80-8a74-11ea-8061-6538d3881019.png)

而在页面底部，会出现奇怪字样，如图所示。

**Comment by Kenshin** [comment]
谢谢反馈。🙏
目前这个编辑器有些（样式上的错误），所以暂时处于半瘫痪状态。

请问你需要实现什么样的功能？我看能否帮到你？

**Comment by 1095533987** [comment]
emmmm.....原来是这样，也没什么要实现的功能，只是平时使用得比较多，之前也提交过一些问题，有关于查看大图插件的，当然作者你一个人也处理不过来，想着看可不可以帮上什么忙😅，既然现在编辑器处于半瘫痪，那就算了。

**Comment by Kenshin** [comment]
谢谢你的热心。   🙏 
目前简悦的社区功能还比较薄弱，虽然有了些内容，对于社区用户来说并不友好，我会想办法加强这块的易用性。

我会再适当的时候，联络你。 😈  😁

**Comment by Kenshin** [comment]
嗨，插件编辑器的 Notify 提示错误已经修复了。

因为，你之前提到了 `查看大图插件` 有没有有兴趣继续这块的（插件）开发？

PS：多说下，插件中心增加了插件的详细介绍（ 来源于 Github Issue ）

**Comment by 1095533987** [comment]
太好了 我会继续去尝试解决之前遇到的问题😄

**Comment by Kenshin** [comment]
很棒，希望会有什么好玩儿的东西~

还有，如果感兴趣的话，可以尝试下 `查看大图插件` 比如：`查看当前页面的全部图片`，类似下图效果

![image](https://user-images.githubusercontent.com/81074/86448977-1671ae80-bd4a-11ea-9520-c2c5c29a447e.png)

***

当然，如果没兴趣的话，这个功能就我来实现吧。（ 你可以事先告诉我下  😀

**Comment by 1095533987** [comment]
唔 我可以尝试下，但愿我可以做出来😋

**Comment by Kenshin** [comment]
很容易的，感兴趣的话，可以试试。

但，你需要新建一个空的插件，你无法在 **查看大图插件** 这个插件的基础上修改。（因为权限的问题。

**Comment by Kenshin** [comment]
另外，你有 TG 吗？

方便的话，可以在这里联系我  👉  https://t.me/simpreadgroup 加入后直接私聊就好。

**Comment by 1095533987** [comment]
ok

**Comment by Kenshin** [comment]
我的 TG → @kenshin726

**Comment by Kenshin** [comment]
嗨，我关闭这个 Issues 了~
