### ISSUE TITLE
这里是简悦的css受原网站css的影响了吗

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simpread#746]
![QQ截图20200501104925](https://user-images.githubusercontent.com/21174990/80778323-99378b00-8b9a-11ea-8a68-fdb9ea6f26c1.png)

吓，导致在访问csdn博客网站时代码块的背景色与其它网站不同。😱

**Comment by Kenshin** [comment]
你可以用 [自定义样式](http://ksria.com/simpread/docs/#/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决，另外，这个问题应该是深色背景下代码高亮插件的 Bug

**Comment by 1095533987** [comment]
确实，加上自定义样式后可以解决问题。
![QQ截图20200501130950](https://user-images.githubusercontent.com/21174990/80783693-2257bd80-8bad-11ea-8714-611e3c7fdc8c.png)
