### ISSUE TITLE
快捷键允许设置为None

### ISSUE THREAD

**Issue by tiancheng2000** [Kenshin/simpread#747]
一般用快捷键确实很方便，直到有一天我开始玩在线打字练习…😿
（图方便改成过Ctrl+Ctrl呀、Alt+Alt，但在其他网站中就不方便了...）

**Comment by Kenshin** [comment]
你可以使用 [黑名单](http://ksria.com/simpread/docs/#/FAQ?id=%e9%bb%91%e5%90%8d%e5%8d%95) 将不需要使用简悦的站加入到黑名单中，自然快捷键就不会生效了。

**Comment by tiancheng2000** [comment]
这个work-around并不算真正满足用户需要啊😿 用户随便进一个H5游戏站点之类的，只因为装了简悦插件，就都需要手动加好黑名单才能玩吗..>_<

**Comment by Kenshin** [comment]
嗨，抱歉，简悦 2.2 发布后，这个问题已经被 Fixed 掉了，你可以将 **[全部快捷键都禁用](http://ksria.com/simpread/docs/#/%E5%BF%AB%E6%8D%B7%E9%94%AE?id=%e7%a6%81%e7%94%a8%e5%85%a8%e9%83%a8%e5%bf%ab%e6%8d%b7%e9%94%ae)**

除此之外，简悦 2.2 还包括如下更新：

***

## 本次更新内容

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)
- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)
- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)
- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)
- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)
- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)
- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)
- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)
- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)
- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)
- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)
- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)
- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)
- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)
- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 下面的教程涵盖了：稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 等，下面列举一些，更多 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

- [如何让稍后读支持读取本地缓存](https://github.com/Kenshin/simpread/discussions/2146)

- [当产生标注时，如何自动同步到本地](https://github.com/Kenshin/simpread/discussions/2220)

- [通过定制化导出功能支持导入到任意双链笔记（如：将标注导入到 Obsidian 中）](https://github.com/Kenshin/simpread/discussions/2222)

- [当简悦变成你的知识库（离线且具有永久链接）](https://github.com/Kenshin/simpread/discussions/2221)

- [巧用浮动标注栏的导出功能，可方便与双链的笔记工具联动](https://github.com/Kenshin/simpread/discussions/1851)

- [将自动化服务变成你的导出服务](https://github.com/Kenshin/simpread/discussions/2151)

- [当产生标注时，如何同时下载标注与原文](https://github.com/Kenshin/simpread/discussions/2147)

- [利用此功能可方便在双链笔记中做永久的原文链接](https://github.com/Kenshin/simpread/discussions/2152)


## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

**Comment by tiancheng2000** [comment]
Nice!~
