### ISSUE TITLE
FireFox商店里的简悦消失了

### ISSUE THREAD

**Issue by HEIHOTZU** [Kenshin/simpread#749]
如果您是点击其他网站上的链接而来，想寻找某个扩展或主题，该项目却已不可用。这可能是因为：

    开发者主动下架。他们通常会因为不再支持该扩展或主题，或已推出替代版本而这么做。
    Mozilla 已将其下架。这可能是因为在审核扩展或主题的过程中发现问题，或是该扩展或主题违反了 addons.mozilla.org 的使用条款和条件。开发者会有机会解决问题，并重新上架。

请过段时间后再尝试访问该页面，因为主题或扩展可能会再次上架。另外，也许您可以在下列扩展或主题中找到要您要找的内容，或者到我们的社区论坛寻求帮助。

**Comment by Kenshin** [comment]
嗨，你可以试试这个方案 https://github.com/Kenshin/simpread/issues/666 里面有关于它为什么下架的原因。 😀
