### ISSUE TITLE
稍后阅读建议支持pocket和instapaper

### ISSUE THREAD

**Issue by necan** [Kenshin/simpread#75]
稍后阅读建议支持pocket和instapaper

**Comment by Kenshin** [comment]
@necan 

感谢建议~

`1.0.3` 已经发布，包含的功能：`导出到生产力工具`，`发送到 Kindle`，`自定义样式`，`论坛类页面`，`分页` ，详细请看 [1.0.3 的更新日志](http://ksria.com/simpread/changelog.html#1.0.3)

- 导出的生产力工具包括：Dropbox · Onenote · Google Drive · 印象笔记 / Evernote · Pocket · Linnk
- 稍后读导出包括：Pocket · Linnk

> 但暂时不支持 instapaper ，因为它的 taken 需要 Email 申请，但一致未申请下来...

此 issues 将关闭~
