### ISSUE TITLE
notion授权成功，但转存后却找不见转存的页面

### ISSUE THREAD

**Issue by zhl111** [Kenshin/simpread#752]
#用户需要手动登录到 Notion
#授权成功后，可选择保存的文件夹注意：与其它授权不同，简悦无法自动建立对应的文件夹

我notion是登录的，存给别人了？

**Comment by Kenshin** [comment]
1. 关闭需要导入到 Notion 的页面
2. 选项页 → 高级设定 → 重新授权 Notion 
3. 授权成功后，选择相应的文件夹

有问题再重开此 issues

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
