### ISSUE TITLE
关于插件“模仿 Safari 阅读模式样式”的建议

### ISSUE THREAD

**Issue by lonely701** [Kenshin/simpread#753]
可不可以设置成点击文章四周的灰色区域退出阅读模式呢？这样就和safari一样了。

![image](https://user-images.githubusercontent.com/5812690/81408341-1028d280-910b-11ea-8e0f-fd692b3c7fda.png)

**Comment by Kenshin** [comment]
谢谢反馈，会有此功能的。

PS：发现很多用户都喜欢这个插件，准备抽时间把它在升级下。目前有些小问题。

**Comment by Kenshin** [comment]
嗨，我更新了[ 模仿 Safari 阅读模式样式](https://simpread.ksria.cn/plugins/details/tbjTx33iAA) 主要修复了你说的这些问题。

有时间确认下，没问题的话，请关闭这个 issues
