### ISSUE TITLE
希望能有颜色显示

### ISSUE THREAD

**Issue by xyxlkb** [Kenshin/simpread#757]
看文章的时候会有不同的颜色，有些红色字体就是强调的，但是用了简悦之后都是黑色的字体，会错过一些重点，希望能在简悦内也显示原本的字体颜色。
如CSDN里的一些文章：https://blog.csdn.net/erlian1992/article/details/51298276

**Comment by Kenshin** [comment]
谢谢反馈

你给出的页面中红色的设置是在 `style` 完成的，并不太符合规则，所以在生成阅读模式的时候，就被删除了。

这是没办法的事情，不是每个页面的  `style` 的规则都符合 **规矩** 。

***

如果你需要这些内容的话，可以在 选项页 → 高级设定 → 词法分析引擎 → 关闭 **纯粹模式**

**Comment by xyxlkb** [comment]
原来如此，谢谢！这个插件真的非常好用！帮了大忙



            
            
                
                    
                            
                                
                            
                            
                                xyxlkb
                            
                            
                                
                            
                    
                        
                            
                                    邮箱：xyxlkb@buaa.edu.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


            在2020年05月10日 18:50，Kenshin Wang 写道： 
谢谢反馈
你给出的页面中红色的设置是在 style 完成的，并不太符合规则，所以在生成阅读模式的时候，就被删除了。
这是没办法的事情，不是每个页面的  style 的规则都符合 规矩 。

如果你需要这些内容的话，可以在 选项页 → 高级设定 → 词法分析引擎 → 关闭 纯粹模式

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Kenshin/simpread/issues/757#issuecomment-626308248",
"url": "https://github.com/Kenshin/simpread/issues/757#issuecomment-626308248",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
