### ISSUE TITLE
希望增加不启用快捷键功能

### ISSUE THREAD

**Issue by oska874** [Kenshin/simpread#758]
希望可以不设置快捷键，

**Comment by Kenshin** [comment]
为什么不设置快捷键？

如果在某个页面不需要使用简悦的话，可以将它加入到黑名单里面

**Comment by oska874** [comment]
1. 快捷键基本不会去用，如果不是在一个网页上按键结果把simpread调出来了，根本不知道还有快捷键这个东西；
2. 按理说，快捷键就应该可以设置空，不是每个人都有需求；
3. 我用 vimum 插件，已经把按键都占用了。

**Comment by Kenshin** [comment]
简悦的快捷键分为两类：

1. 全局快捷键

2. 进入阅读模式，通过 `s r` 触发后进入快捷键模式。

 你可以设置不常用的快捷键到 `1` 如果用 `vimum` 可以不绑定分配到简悦上的快捷键。

***

当然，我会考虑下，不启用 **全局快捷键** 这个兼容  `vimum`  等模式的功能。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
