### ISSUE TITLE
kiwi browser 安装 simpread 插件失效问题

### ISSUE THREAD

**Issue by bighaidao** [Kenshin/simpread#759]
使用kiwi browser 安装简阅插件。 安装头两天一切正常。 不过过一段时间插件自动消失了。 这种情况我试了几次，都会自动消失。 很神奇。 

想请问下 作者这是插件问题还是kiwi browser 本身的逻辑问题

**Comment by Kenshin** [comment]
应该是你个人的问题。（当然也不排除是 Bug 但即便是 Bug 也是很隐秘的，否则早就被发现了...  😂 

你经常在 Kiwi Browser 导入配置吗？如果的是话，每次导入配置后，会重新清理插件。

你可以使用 **选项页 → 插件管理 → 从配置文件导入插件** 的方式重新获取配置文件里面插件。（ 而不需要再一个个的重新安装它。

你也可以说说，发生问题时前后你都做了什么操作，这样方便排错。

**Comment by bighaidao** [comment]
@Kenshin  hi，感谢回复。 不过我真的遇到几次安装插件，然后莫名其妙消失了。也没查出问题

**Comment by Kenshin** [comment]
下次遇到 `莫名其妙消失` 的话，试试 **选项页 → 插件管理 → 从配置文件导入插件** 看看能否成功导入。

我先关闭这个 issues 再遇到这个问题的话，别忘记通知我，我再开启它吧。（ 确实无法判断是什么问题造成的。
