### ISSUE TITLE
阅读模式能否去掉知乎的带货链接

### ISSUE THREAD

**Issue by GengchenXU** [Kenshin/simpread#761]
产品真的非常棒，提一个小小的意见

**Comment by Kenshin** [comment]
谢谢喜欢简悦。

> 知乎的带货链接 

是个啥...  😂 丢个链接我看下。

**Comment by GengchenXU** [comment]
https://www.zhihu.com/people/yangbingli/answers  
比如这个回答里面插的京东广告

**Comment by GengchenXU** [comment]
> 谢谢喜欢简悦。
> 
> > 知乎的带货链接
> 
> 是个啥...😂*

https://www.zhihu.com/people/yangbingli/answers比如这里面的京东广告

**Comment by GengchenXU** [comment]
> 谢谢喜欢简悦。
> 
> > 知乎的带货链接
> 
> 是个啥... 😂 丢个链接我看下。

https://www.zhihu.com/people/yangbingli/answers

这里面的京东广告

**Comment by GengchenXU** [comment]
> 谢谢喜欢简悦。
> 
> > 知乎的带货链接
> 
> 是个啥... 😂 丢个链接我看下。


https://www.zhihu.com/question/381418221/answer/1217773821

回答里面插的广告

**Comment by Kenshin** [comment]
这应该不是 广告... 这是用户自己带的链接？（ 难道确定的广告吗？

可以通过自定义样式来去除。

阅读模式 → 右下角 → 控制栏 → 动作 → 设定 → 第二个 icon 按照下图所示方式添加：

![image](https://user-images.githubusercontent.com/81074/81674850-6df94980-9480-11ea-8757-212a78701acf.png)

```
.RichText-MCNLinkCardContainer {
    display: none!important;
}
···

即可。

**Comment by GengchenXU** [comment]
> 这应该不是 广告... 这是用户自己带的链接？（ 难道确定的广告吗？
> 
> 可以通过自定义样式来去除。
> 
> 阅读模式 → 右下角 → 控制栏 → 动作 → 设定 → 第二个 icon 按照下图所示方式添加：
> 
> ![image](https://user-images.githubusercontent.com/81074/81674850-6df94980-9480-11ea-8757-212a78701acf.png)
> 
> ```
> .RichText-MCNLinkCardContainer {
>     display: none!important;
> }
> ···
> 
> 即可。
非常感谢
