### ISSUE TITLE
markdown离线下载有点问题

### ISSUE THREAD

**Issue by caodaqian** [Kenshin/simpread#763]
您好，我使用简悦时候发现了一个问题，我采用正常导出md是ok的
但是使用离线md文件导出时候，会下载一个随机的文件名，不知道是什么原因产生的
即使我使用隐身模式，去除其他插件的影响也是如此

**Comment by caodaqian** [comment]
![错误图片](https://user-gold-cdn.xitu.io/2020/5/12/172095a3e866f1ff?w=685&h=302&f=jpeg&s=72093)

**Comment by Kenshin** [comment]
这就比较奇怪了...

使用 **离线 Markdown** 的时候是否弹出申请权限的对话框？

另外，告诉下当前的环境之类的，或者看看权限是否关闭了什么。（方便的话，能否使用另外一个浏览器确认下？

**Comment by caodaqian** [comment]
您好，我重新确认了一下，发现是我chrome插件的锅，我关闭后导出正常了
> chrono下载管理器会导致离线md下载异常

**Comment by Kenshin** [comment]
👌
