### ISSUE TITLE
某网址打开出错

### ISSUE THREAD

**Issue by leechor** [Kenshin/simpread#765]
https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/

**Comment by Kenshin** [comment]
哪里出错？

**Comment by leechor** [comment]
@Kenshin 
![image](https://user-images.githubusercontent.com/2387215/81801670-5b961300-9547-11ea-8356-f9ec26000a6a.png)

**Comment by Kenshin** [comment]
我这边没有问题。

你试着升级这个插件 → 选项页 → 插件管理 → 更新本地全部插件（ 或删除重新安装它

***

另外，这个提示你可以不用理会，只是在运行插件的时候出现了问题，不影响阅读模式本身。

**Comment by leechor** [comment]
@Kenshin 更新后正常

**Comment by Kenshin** [comment]
👏  👌
