### ISSUE TITLE
请求适配丁香园网站

### ISSUE THREAD

**Issue by cresccccc** [Kenshin/simpread#77]
页面举例：http://neuro.dxy.cn/article/519318?trace=pns

感谢！

**Comment by Kenshin** [comment]
okay，没有问题。
适配好，我会关闭 此 issues 。

**Comment by Kenshin** [comment]
已适配~

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
