### ISSUE TITLE
显示网页内容不全面

### ISSUE THREAD

**Issue by wynn5a** [Kenshin/simpread#773]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **MacIntel**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/cms.html>

**请描述你的问题**

显示内容不全，只显示了网页的最后一半内容

**Comment by wynn5a** [comment]
通过站点高亮区域设置解决

**Comment by Kenshin** [comment]
哈哈，恭喜 **自救** 成功。

也谢谢你仔细看了帮助文档，很多用户都怎么看文档的... 😂
