### ISSUE TITLE
版面宽度对浏览器窗口宽度适应不佳

### ISSUE THREAD

**Issue by FWhale0** [Kenshin/simpread#774]
**请说明发生问题的环境**

- 操作系统 **Win10 64**

- 浏览器版本 **Microsoft Edge 81.0.416.77**

- 简悦版本 **1.1.4**

- 发生问题的地址（实际上已知所有页面都有此问题） <e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme>

**请描述你的问题**

>在浏览器窗口最大化的情况下，默认值为80的版面宽度可以让我很舒适地阅读，但是当我将窗口缩小到宽度只有屏幕的一半，上述版面宽度就显得过窄，此时我只能手动将版面宽度调整到95，以获得更好的体验。

**截图**

>
![最大化 80](https://user-images.githubusercontent.com/65691922/82513929-eded7680-9b46-11ea-93f5-0ceabd8c332e.png)
![缩小化 80](https://user-images.githubusercontent.com/65691922/82513931-f04fd080-9b46-11ea-9dd9-b45c9516dfc8.png)
![缩小化 95](https://user-images.githubusercontent.com/65691922/82513940-f3e35780-9b46-11ea-9007-da25a04b484f.png)

**Comment by Kenshin** [comment]
谢谢反馈。

简悦的宽度是按照 **百分比** 设置的，所以这种情况你可以自行调整。
因为你觉得适合的宽度，其他人不一样同样觉得适合，反之也一样。

如果你可以告诉我哪个页面的在这两种不同的宽度下都让你觉得舒服，我也可以参考下。 😀

**Comment by Stark-X** [comment]
考虑增加一个浏览器窗口的宽度小于某个值时应用另一个宽度值的参数？

**Comment by Kenshin** [comment]
> 考虑增加一个浏览器窗口的宽度小于某个值时应用另一个宽度值的参数？

嗨，这么做的意义是什么？没有 Get 到你的需求。

**Comment by Stark-X** [comment]
> > 考虑增加一个浏览器窗口的宽度小于某个值时应用另一个宽度值的参数？
> 
> 嗨，这么做的意义是什么？没有 Get 到你的需求。

就像这个 issue 里面的截图
我遇到的场景是，我有两个显示器，其中一个显示器是竖着的，把要看的文档页面放到这个竖着的显示器时，如果还使用原来的版面宽度值，就会使得整个版面变得很窄。为了避免看着别扭，只能手动把版面宽度调大。

**Comment by Kenshin** [comment]
> 就像这个 issue 里面的截图
> 我遇到的场景是，我有两个显示器，其中一个显示器是竖着的，把要看的文档页面放到这个竖着的显示器时，如果还使用原来的版面宽度值，就会使得整个版面变得很窄。为了避免看着别扭，只能手动把版面宽度调大。


emmm 不错的使用场景，我会用插件实现它，实现后会在这里通知你。

**Comment by Kenshin** [comment]
嗨，各位。

我制作了一个插件 [版面宽度定制器](https://simpread.ksria.cn/plugins/details/noCdz57Mw6) 基本上可以解决这个问题。

可以通过这个插件设定不同的版面宽度，如下图的方式：

![image](https://user-images.githubusercontent.com/81074/127956313-e57d1087-535a-425d-9b70-624e89a092c7.png)

所以我关闭这个 Issues 了。
