### ISSUE TITLE
 稍后读无法同步的问题

### ISSUE THREAD

**Issue by zengdw** [Kenshin/simpread#777]
插件不能在不同电脑上同步数据吗，安装的插件和稍后读这些数据

**Comment by Kenshin** [comment]
1. 插件太大，所以同步的时间会很长，所以取消了插件的同步，但同时时会同步插件的 ID

2. 稍后读会同步，（如果你同步过就知道了） **只是这里是个 Bug 导致** 判断时未加入增删稍后读后的逻辑，下个版本会解决这个问题（同时会增加一些更灵活的同步方案

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

除此以外，还增加了两个新选择：

![image](https://user-images.githubusercontent.com/81074/92318195-4c2d5f00-f03b-11ea-8c43-c8ea8614494f.png)


***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
