### ISSUE TITLE
右键菜单 全部取消后，仍然显示一级菜单

### ISSUE THREAD

**Issue by icesp** [Kenshin/simpread#779]
http://ksria.com/simpread/docs/#/右键菜单 全部取消即可。

_Originally posted by @Kenshin in https://github.com/Kenshin/simpread/issues/671#issuecomment-591355348_

问题：全部取消以后，右键菜单仍然保留一行一级菜单，只是二级菜单显示为「空」。
需求：请问有没有办法让一级菜单在右键选项里消失，不再占一行版面。

**Comment by Kenshin** [comment]
抱歉，这个是 Bug 因为引入了新的菜单项而导致的，只能下个版本修复。

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题**

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
