### ISSUE TITLE
解析丢失bug

### ISSUE THREAD

**Issue by lgf133214** [Kenshin/simpread#780]
我看自己博客的时候，往外粘代码的时候发现html中的 一个 id 丢失了。
[具体地址](https://blog.csdn.net/li18434/article/details/106440065)
发现丢失的id为 id="chat-container"
![image](https://user-images.githubusercontent.com/50295062/83325141-c01dd580-a29c-11ea-951d-f6bbaab6c745.png)
![image](https://user-images.githubusercontent.com/50295062/83325160-e04d9480-a29c-11ea-8fdb-b622d85cd3c2.png)

**Comment by lgf133214** [comment]
图片url：
https://s1.ax1x.com/2020/05/30/tQC3tS.png
https://s1.ax1x.com/2020/05/30/tQC8fg.png

**Comment by Kenshin** [comment]
谢谢反馈，确实有问题~

我看下是什么问题，修复后会在这里通知到你。

**Comment by lgf133214** [comment]
> 谢谢反馈，确实有问题~
> 
> 我看下是什么问题，修复后会在这里通知到你。

既然看到了，我也就在提个建议，解析后的a标签可不可以设置成 _blank啊，或者在配置页加上这一条。又或者是我没看到

**Comment by Kenshin** [comment]
> 解析后的a标签可不可以设置成 _blank

不能实现它，不是技术问题，而是没有意义。这么做的理由是什么？

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀
