### ISSUE TITLE
浮动工具栏没有 Tooltip

### ISSUE THREAD

**Issue by cp3alai** [Kenshin/simpread#781]
阅读模式不启用高级控制面板:
1. 只有图标,没有图标解释.建议鼠标放上去现实图标的解释
2. 鼠标放在省略号上,弹出菜单,再随便放到一个按钮上弹出子菜单,鼠标移开后,子菜单消失,主菜单还在.鼠标移出浏览器,主菜单才消失.

**Comment by Kenshin** [comment]
谢谢反馈。

`浮动控制栏` 是 1.0.0 的组件，随着功能的增加，浮动工具栏已经无法满足功能上的需求，所以才增加了 `高级控制面板`

目前在考虑未来替换掉这个功能，同时  `高级控制面板` 目前也有些问题。（ 但具体还未考虑好如何实现它。

所以这个功能暂时做 Delay 有进一步消息的话，我会在这里通知你。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了（ 浮动控制栏 增加了相应的 Tooltip ），所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
