### ISSUE TITLE
不能识别本地txt

### ISSUE THREAD

**Issue by atomfive** [Kenshin/simpread#785]
本地txt文件拖进chrome窗口，简阅图标没有变红还是灰色。
chrome版本 83.0.4103.61（正式版本） （64 位）
[恐人.txt](https://github.com/Kenshin/simpread/files/4720614/default.txt)
<img width="826" alt="截屏2020-06-03 上午9 51 32" src="https://user-images.githubusercontent.com/19386631/83587167-fc915000-a580-11ea-850b-c137639262cf.png">

**Comment by Kenshin** [comment]
进入 `chrome://extensions/?id=ijllcpnolfcooahcekpamkbidhejabll` 确保勾选下图

![image](https://user-images.githubusercontent.com/81074/83589551-90194f80-a586-11ea-86a1-538bb440cf6f.png)

再通过 Chrome 打开这个 txt 后，试试通过快捷键进入阅读模式 

另外，疑似一个 Bug 右上角的 icon 未变成红色 **但仍旧可以进入阅读模式**

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题** 新的方案：只能在正文中进行删除操作。

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
