### ISSUE TITLE
分享到 Notion 的库有很多 undefined 需要优化

### ISSUE THREAD

**Issue by hymanbaiguixiong** [Kenshin/simpread#787]
想问问能否优化一下选择保存的页面？有一些页面在选择界面无法看到，有些页面显示untitled

**Comment by Kenshin** [comment]
可以的，下个版本会修复此问题。😂

**Comment by hymanbaiguixiong** [comment]
好的好的🌚尽快

Kenshin Wang <notifications@github.com>于2020年6月4日 周四上午10:48写道：

**Comment by Kenshin** [comment]
嗨， 简悦小升级 👉  [1.1.4.6016](http://ksria.com/simpread/welcome/version_1.1.4.6016.html) 版本，主要针对 Notion databases 的支持。

简单的说，简悦可以将【当前页面保存为 Notion databases 的方式  】
目前作为 Notion导出工具来说的，应该是第一个支持 databases 方案的第三方扩展。

详细请看 👉  http://ksria.com/simpread/docs/#/Notion

同时，也一并 **修复了此问题**

除此以外， 还包括这些 🐛 👉 http://ksria.com/simpread/changelog.html#1.1.4.6016

注意：这次为小改版，仅支持静默升级，不会弹出选项页。（ 只有大版本更新时才会主动弹出选项页）

请留意版本号为 **1.1.4.6016**

***

我将关闭此 issues  😀
