### ISSUE TITLE
以 TextBundle 的结构导出和保存 MarkDown 格式

### ISSUE THREAD

**Issue by HaujetZhao** [Kenshin/simpread#788]
目前保存离线 MarkDown 的方式是，将图片 base64 编码，保存到 md 文件中。这样保证了统一性，方便复制，但一个小问题是，图片过多的话，打开会导致阅读、编辑器卡顿。

更好的一个解决方式是：使用 TextBundle 的结构。

TextBundle 是 Marked 开发者和 Ulysses 团队开发出了一种解决方法，简要解释一下，它是这样的结构：

一个叫 `文档.textbundle` 的文件夹，最简单的形式，可以是包含：

* 一个 `assets` 文件夹，用于存放图片等附件
* 一个 `text.md` 文件，用于存放文档内容。文档通过相对路径引用 `assets` 文件夹内的图片和其它媒体文件。

可以实现一个文包内，既包含 md 文档，也包含图片，预览时无需询问权限，同时又方便直接编辑，非常便捷。

每一个文档都存储在一个 textbundle（文件夹） 中，这样，即便导出，复制到其它设备、平台上，都可以用各种 markdown 编辑器打开文档，正常浏览里面的图片。

Ulysses, Bear这样的流行的写作工具，甚至是Mindnode等思维导图工具，都支持 textbundle。

考虑到导出为一个文件夹可能受到浏览器限制，可以先压缩成 zip，再导出。或者保存到 WebDav。

这里是 TextBundle 的 [官网](http://textbundle.org) 和 [详细细节](http://textbundle.org/spec)，其实实际比上述复杂些，它还有 info.json 和 textpack 等。不过这其它那些都不需要，只要导出 markdown 时都导出在一个文件夹，文档在 text.md 中，图片在 assets 文件夹中，就足够了。

**Comment by Kenshin** [comment]
emmm 好想法 👍

谢谢建议，我会考虑。主要的顾虑主要在 textbundle 支持的广泛性。

***

另外，离线 Markdown 卡顿的问题，我测试过，建议使用 vs code 来打开它，Bear Ulysses 之流的都有卡顿现象。

**Comment by JackalZhao** [comment]
> emmm 好想法 👍
> 
> 谢谢建议，我会考虑。主要的顾虑主要在 textbundle 支持的广泛性。
> 
> 另外，离线 Markdown 卡顿的问题，我测试过，建议使用 vs code 来打开它，Bear Ulysses 之流的都有卡顿现象。

其实，我跟每个 markdown 相关开发者交流的时候，都会有这样一个阶段：开发者认为 TextBundle 是一个私有格式，怕有兼容问题。

但实际上，它不是一个格式，只是一种组织文件的文件夹结构。简单的描述就是，把图片、视频、附件保存在 `assets` 文件夹中，将文本保存在 `text.md` 中，图片和附件都通过相对路径引用，再把这两样保存在一个 `文档.textbundle` 的文件夹中，这个文件夹名字后有个 `.textbundle` 是为了便于一些程序识别出这里面是一个文档。

如果有高级需求，比如要记录创建时间、来源网址、标签等，那就放到里面一个叫` info.json` 的文件中。

而对于所有的 MarkDown 编辑器，只要打开里面的 text.md ，就能正常浏览所有的内容。对于任何 md 编辑器，即使不主动支持，TextBundle 这种结构都是兼容的，因为它没有导入任何私有格式。

目前，链滴笔记也准备主动支持 TextBundle；我发邮件问过 Typora，最近给了我回信，说已有计划，将在接下来某个版本中，支持 TextBundle 和 TextPack。

所以，兼容性不会是阻力，可以放心。@Kenshin

**Comment by enokoneko** [comment]
同样希望支持TextBundle，或复制富文本，目前导入Bear的结果无法直接看到图片，仍然不如在 Safari 阅读模式下直接复制粘贴的效果。
1.0是纯过滤器，2.0希望把导出功能完善起来，真正能用上

**Comment by Kenshin** [comment]
@enokoneko 

会考虑的。导出到 Bear 没有图片的问题应该不是这个造成的，我需要研究下它的规则。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

**Comment by Moyf** [comment]
> > 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。
> 
> > 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。
> 
> > 如有任何问题，可以随时再联络我。🙏
> 
> ### 简悦 2.2.0.520 的相关介绍
> > [可以看这里](https://github.com/Kenshin/simpread/issues/2837)
> 
> ### 下载地址
> > 更多下载地址请看 https://simpread.pro/download
> 
> * [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)
> * [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)

嗨，请问现在支持导出 Textbundle 了吗
看更新说明里好像没有提到这个的样子，是不是需要自己配置自定义导出模板来实现 0 0

**Comment by Kenshin** [comment]
> 现在支持导出 Textbundle 了吗

是的，文档看这里 http://ksria.com/simpread/docs/#/Textbundle

**Comment by Moyf** [comment]
好的，我去瞧瞧~非常感谢！


Kenshin Wang ***@***.***> 于2021年12月13日周一 18:31写道：
