### ISSUE TITLE
无法保存视频标签

### ISSUE THREAD

**Issue by HaujetZhao** [Kenshin/simpread#789]
如下图，video 标签中的视频链接无法保存下来，只保存了文字：

![image](https://user-images.githubusercontent.com/19181833/83664864-2c7e3900-a5fd-11ea-8abd-e8dc971c3f84.png)

![image](https://user-images.githubusercontent.com/19181833/83664885-36a03780-a5fd-11ea-8fe8-ff5f63949b0c.png)

文章原地址：https://hacpai.com/article/1590858834437 ，供用于保存测试。

**Comment by Kenshin** [comment]
谢谢反馈。

保存视频标签的意思是 **导出到本地** 吗？如果是的话，我试了试，应该是 Markdown 有问题吧？

转换为 Markdown 使用了第三方的库，可能是这个库造成的问题。

否则，请告诉我具体保存为什么格式？

**Comment by JackalZhao** [comment]
> 谢谢反馈。
> 
> 保存视频标签的意思是 **导出到本地** 吗？如果是的话，我试了试，应该是 Markdown 有问题吧？
> 
> 转换为 Markdown 使用了第三方的库，可能是这个库造成的问题。
> 
> 否则，请告诉我具体保存为什么格式？

以 [上述提到的文章](https://hacpai.com/article/1590858834437) 为例，里面的视频标签是：

```html
<video width="100%" src="https://b3logfile.com/file/2020/05/Screenrecorder20200531005913152new-c1711d27.mp4" controls="controls" __idm_id__="644808706" class="vsc-initialized" data-vscid="n8z79zf0e">浏览器不支持该媒体的播放</video>
```

在网页上的效果是：

![image](https://user-images.githubusercontent.com/19181833/83709932-26ff0e00-a652-11ea-9bdf-79bbf9c80ef6.png)

在进入阅读模式后，视频可以正常播放，但是在 markdown 导出中，就只剩下了中间的文字，变成了：

```
浏览器不支持该媒体的播放
```

所以希望的保存方法是，将视频标签如 `<video width="100%" src="https://b3logfile.com/file/2020/05/Screenrecorder20200531005913152new-c1711d27.mp4"></video>` 这样的，转到 markdown 时：

* 以 `[video](https://b3logfile.com/file/2020/05/Screenrecorder20200531005913152new-c1711d27.mp4)` 这样的形式保存（有一些编辑器可以在预览时将这个自动识别为视频标签，比如 Vditor ）
* 或者以 <video src="https://b3logfile.com/file/2020/05/Screenrecorder20200531005913152new-c1711d27.mp4" control></video>` 这样的 html 标签保存。

这些都是以索引链接保存到了 md 文件。

如果能够实现 #788 中提到的 TextBundle 形式保存的话，就可以将视频 mp4 同时缓存到 assets 文件夹中，在 md 文件中的索引就能转换成：`[video](assets/Screenrecorder20200531005913152new-c1711d27.mp4)` 或者 `<video src="assets/Screenrecorder20200531005913152new-c1711d27.mp4" control></video>`，以后即使帖子被删了，也还可以浏览。

@Kenshin

**Comment by JackalZhao** [comment]
> 谢谢反馈。
> 
> 保存视频标签的意思是 **导出到本地** 吗？如果是的话，我试了试，应该是 Markdown 有问题吧？
> 
> 转换为 Markdown 使用了第三方的库，可能是这个库造成的问题。
> 
> 否则，请告诉我具体保存为什么格式？

如果在 markdown 解析器上有困难，或者可以尝试下 [lute](https://github.com/88250/lute)，这是一款对中文语境优化的 Markdown 引擎，支持 Go 和 JavaScript，国内全职开源开发者为 B3log 项目做的。目前用于 B3log 项目 [黑客派](https://hacpai.com/) 社区上的所有 Markdown 处理，每天处理数百万解析渲染请求，运行表现稳定。

[这里是 Lute 中文文档](https://hacpai.com/article/1567047822949) 

@Kenshin

**Comment by Kenshin** [comment]
谢谢提示，我有时间看看，如果效果不错的话，可以集成到下个办法。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，目前的做法是：只有涉及到 Video 都会被强制转换为 HTML 结构，因为大多数 Markdown Editor 都支持直接解析 Video HTML e.g Tyora

接下来会考虑对导出的 Markdown 进行定制化，如 **是否将 Table 转换为 HTML** 等选项。

所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
