### ISSUE TITLE
请求匹配中国网

### ISSUE THREAD

**Issue by wan9wu** [Kenshin/simpread#79]
http://www.china.com.cn/chinese/RS/137352.htm

**Comment by Kenshin** [comment]
okay~

适配后，会关闭此 issues。

**Comment by Kenshin** [comment]
由于 中国网 的 url 规则比较乱，所以只更新了 http://news.china.com.cn/ 如有其它需要更新的，请再告知。 

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
