### ISSUE TITLE
相对路径链接没有保存到 md

### ISSUE THREAD

**Issue by HaujetZhao** [Kenshin/simpread#791]
在这个链接中：https://portableapps.com/zh-cn

用简悦转换后：

![image](https://user-images.githubusercontent.com/19181833/83935868-33b96880-a7f0-11ea-9a93-b81afc655ba2.png)

有这样一个标签：

![image](https://user-images.githubusercontent.com/19181833/83935936-e7225d00-a7f0-11ea-87a9-812267d7bfa9.png)

它的源代码是：

```html
<a title="下载 PortableApps.com" href="/redirect/?a=PortableApps.comPlatform&amp;s=s&amp;d=pa&amp;n=The%20PortableApps.com%20Platform&amp;f=PortableApps.com_Platform_Setup_16.1.1.paf.exe"><span><strong>下载 16.1.1</strong> <em>对于 Windows, 多种语言<br>5MB 下载 / 12MB 安装尺寸</em></span></a>
```

这里面的链接是一个相对路径：

```
/redirect/?a=PortableApps.comPlatform&amp;s=s&amp;d=pa&amp;n=The%20PortableApps.com%20Platform&amp;f=PortableApps.com_Platform_Setup_16.1.1.paf.exe
```

变成绝对路径也就是：

```
https://portableapps.com/redirect/?a=PortableApps.comPlatform&s=s&d=pa&n=The%20PortableApps.com%20Platform&f=PortableApps.com_Platform_Setup_16.1.1.paf.exe
```

但是，保存到 md 文档后，变成了：

```
[**下载 16.1.1** *对于 Windows, 多种语言   5MB 下载 / 12MB 安装尺寸*]()
```

里面的链接没有了。

所以建议遇到这种相对域名的路径，可以自动转换成绝对路径。

**Comment by Kenshin** [comment]
谢谢反馈。

确实存在这个问题，仅 `图片的相对路径做了转换` 
我会考虑出个插件来解决这个问题，因为这种转换会带来很多不必要的性能影响。

**Comment by JackalZhao** [comment]
> 谢谢反馈。
> 
> 确实存在这个问题，仅 `图片的相对路径做了转换`
> 我会考虑出个插件来解决这个问题，因为这种转换会带来很多不必要的性能影响。

在转换成阅读模式的时候，这个相对路径没有被忽略掉，是可以正常点击访问的。

只是在保存的时候，把这个相对路径忽略掉了。

也就是说，阅读模式无需转换，只需要在保存和导出的时候，将相对路径转换一下就行了，对正常转换阅读模式没有任何性能影响的。@Kenshin

**Comment by Kenshin** [comment]
嗨，我使用插件的方式解决了这个问题，你可以安装这个插件  👉  https://simpread.ksria.cn/plugins/details/TgxCzObXib
安装后，刷新当前页面，再导出 Markdown 就没有问题了。

我关闭这个 issues 了~
