### ISSUE TITLE
阅读模式有部分网页保存到 md 后有部分没保存下来

### ISSUE THREAD

**Issue by JackalZhao** [Kenshin/simpread#792]
以 [这篇文章](https://hacpai.com/article/1582274499427) 为例，如下图所示的区域，里面有一些 svg 图片：

![image](https://user-images.githubusercontent.com/19181833/83941935-d0e0c500-a821-11ea-8b5d-d1fd2db4d1ec.png)

在阅读模式会变成：

![image](https://user-images.githubusercontent.com/19181833/83942051-eaced780-a822-11ea-9665-9bf624c2bdcc.png)

保存到 md 后变成：

![image](https://user-images.githubusercontent.com/19181833/83942059-fae6b700-a822-11ea-9aff-0a3a58c39d2c.png)

问题也不是太大。不知是 Feature 还是 bug。有没有办法，将没有办法完全变成 md 的，用 html 标签保存下来？

**Comment by Kenshin** [comment]
谢谢反馈。（ 近期反馈了不少建议。 😀 

这个问题是原页面造成的，看下图

![image](https://user-images.githubusercontent.com/81074/83960591-f1aa2880-a8bc-11ea-8ac7-8f5b75e2f7ef.png)

我关闭这个 issues 了，有疑问再开启。
