### ISSUE TITLE
豆瓣的这个网页看的挺难受的，希望能优化一下

### ISSUE THREAD

**Issue by TakakiRey** [Kenshin/simpread#793]
**请说明发生问题的环境**

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://book.douban.com/annotation/35257636/>

**Comment by Kenshin** [comment]
谢谢反馈。

这应该的 豆瓣阅读 的结构发生了变化造成的。

你可以通过 **手动高亮** 或 **自定义适配站点** 解决，或等我更新一批新站后自动解决。

**Comment by Jiang10086** [comment]
希望能适配一下豆瓣小组，比如https://www.douban.com/group/topic/13309683/?author=1，这么大段的文字很适合阅读模式。
简悦版本:1.1.3

**Comment by Kenshin** [comment]
@Jiang10086 

以论坛类页面的形式？还是阅读模式？如果是后者的话，直接进入阅读模式即可。

**Comment by lj123454321** [comment]
> @Jiang10086
> 
> 以论坛类页面的形式？还是阅读模式？如果是后者的话，直接进入阅读模式即可。

论坛类页面模式怎么进呀，我在豆瓣小组的帖子里进去阅读模式，发现回复都不能显示。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
