### ISSUE TITLE
希望有导出到 Github 功能（的插件）

### ISSUE THREAD

**Issue by linonetwo** [Kenshin/simpread#795]
用户提供如下信息：

- Github 仓库（包含用户名）
- 要保存到的仓库内的文件夹路径，默认为 /
- Github Personal Access Token 或 OAuth

然后就可以把导出直接通过 Github API 放到 Github 里啦！

目前 Github 是功能最强大的免费 BaaS，基于它可以做很多数据的中转处理，希望能支持一下。

**Comment by Kenshin** [comment]
谢谢建议，很好的思路。 👍 

之前有朋友反馈过，希望保存到 Github gist 里面。
Github 确实很不错，但仅保存一个配置文件是不是「大材小用」了？

当然，你可以说说可以用这种方式来实现什么？

**Comment by linonetwo** [comment]
配置文件可以到处到 gist，而网页内容可以保存到 Github 去。

首先 Firefox 好像没法下载大文件（没有弹出大文件下载授权界面，所以一直没开始下载），可以保存到 BaaS 再下载，而且也是个备份
其次我在用 [TiddlyWiki](https://github.com/linonetwo/wiki)，一个知识管理系统。它可以直接读取本地的 Markdown 文件和图片，并备份到 github。如果网页内容也保存到 github，我就可以同步到本地，并在知识管理系统里搜索看过的网页了。

**Comment by Kenshin** [comment]
cool~ 

确实是个好思路，我考虑下。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

2.0 版支持了导出到 Github ，细节 [看这里](http://ksria.com/simpread/docs/#/Github) 所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
