### ISSUE TITLE
每次打开Chrome都会弹出需要更新。/怒

### ISSUE THREAD

**Issue by xzjohy** [Kenshin/simpread#796]
每次打开Chrome都会弹出需要更新，然而还是1.1.3版本，Chrome Store 没有进行更新。每次打开很烦。
![image](https://user-images.githubusercontent.com/47711010/84612486-5be14f80-aef3-11ea-9cb9-1472b14a499c.png)

**Comment by xzjohy** [comment]
![image](https://user-images.githubusercontent.com/47711010/84612725-107b7100-aef4-11ea-8786-fe94315c8b76.png)
![image](https://user-images.githubusercontent.com/47711010/84612740-1b360600-aef4-11ea-975d-cd3d0934f671.png)
![image](https://user-images.githubusercontent.com/47711010/84612731-14a78e80-aef4-11ea-9386-7d7da3efefc0.png)

**Comment by Kenshin** [comment]
这个是因为 cookie 或 localStorage 被禁用造成的，你可以重新安装它。
另外，你的 Chrome 设置有什么不一样的地方吗？

**Comment by xzjohy** [comment]
> 这个是因为 cookie 或 localStorage 被禁用造成的，你可以重新安装它。
> 另外，你的 Chrome 设置有什么不一样的地方吗？

之前没有这样的错误，清理过浏览器记录之后就出现了

**Comment by Kenshin** [comment]
@xzjohy

1. 导出配置
2. 重新安装简悦
3. 导入配置

应该就可以了。

**Comment by xzjohy** [comment]
@Kenshin 问题解决了，谢谢！/doge
