### ISSUE TITLE
官方适配的知乎问题下，没有把问题描述加到阅读模式中，很多时候，问题描述中有许多重要的信息。

### ISSUE THREAD

**Issue by HaujetZhao** [Kenshin/simpread#797]
问题站点：https://www.zhihu.com/question/391558078/answer/1282066150

![image](https://user-images.githubusercontent.com/19181833/84619184-f8611d00-af06-11ea-8f0c-03685db5754f.png)

![image](https://user-images.githubusercontent.com/19181833/84619161-ec755b00-af06-11ea-9ab0-cd61cfd9428e.png)

**Comment by Kenshin** [comment]
谢谢反馈，会考虑升级下这个适配站点。  🙏

**Comment by binsee** [comment]
尝试进行更新适配，思路是将问题内容作为`描述`，但遇到一些问题。

- 页面上，问题内容只截取了部分，后边的省略了。这个问题已经通过分析页面，从json中提取解决了
- 简悦的内容提取模块中，对描述字段有些限制：
    - 遇到首个中文句号 `。` 时截止
    - 如果不存在中文句号，则截取前102字符，追加`......`

目前为上述限制进行了应对，但效果略有瑕疵。绕过原理是将提取的问题内容中`。`替换为`.`，然后在尾部追加`。`，以此来绕过截取。

- 打开网页后：

![image](https://user-images.githubusercontent.com/5285894/92303752-76830c00-efaa-11ea-9d13-067a06c7f641.png)


- 按 `aa` 进入阅读模式

![image](https://user-images.githubusercontent.com/5285894/92303763-987c8e80-efaa-11ea-8521-83cd105088cb.png)

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. 升级官方适配源 https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
