### ISSUE TITLE
为 Save to Notion 添加 URL meta data

### ISSUE THREAD

**Issue by swj1442291549** [Kenshin/simpread#798]
Notion官方提供的Clip工具会自动添加来源网站的URL，希望能补充这一特性。

**Comment by Kenshin** [comment]
谢谢提醒，可以考虑此方式。

**Comment by Kenshin** [comment]
简悦已升级到 **[1.1.4.6022](http://ksria.com/simpread/changelog.html#1.1.4.6022)**  此版本为刚刚发布，请在 chrome://extensions/ 确认是否为 **6022** 版本。

如果为 6022 版本的话，已包含此功能，同时增加了如下的新功能：

- 为导入到 Notion 的内容增加 **URL Meta data**

![image](https://user-images.githubusercontent.com/81074/85377155-3f848900-b56b-11ea-893b-94bdfb1f2bbe.png)

- 支持 图床方式

![image](https://user-images.githubusercontent.com/81074/85377185-4a3f1e00-b56b-11ea-96d1-63eacbd4bc42.png)

![](https://s1.ax1x.com/2020/06/22/NGcqkF.gif)

***

上述功能，详情请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.4.6022)

我将关闭此 issues  😀

**Comment by Kenshin** [comment]
嗨，抱歉，做个调查~

有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？

***

如果遇到的话，试试 **导出配置文件** 再 **清除数据**  或 **重新安装** 的方式试试。

***

> **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

**Comment by swj1442291549** [comment]
您好，

刚刚更新了，之前的授权没有问题。又试了试再另一个浏览器里尝试授权，授权成功。

**Comment by Alphabet1226** [comment]
> 嗨，抱歉，做个调查~
> 
> 有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？
> 
> 如果遇到的话，试试 **导出配置文件** 再 **清除数据** 或 **重新安装** 的方式试试。
> 
> > **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

同样遇到了这个bug，已尝试清楚数据，并且重新安装，还是无法授权notion。上个版本同样出现了这个问题。
环境是：
Chrome 83.0.4103.106 (正式版本) （64 位） (cohort: Stable)
操作系统 | Windows 10 OS Version 1809 (Build 17763.1282)

**Comment by Kenshin** [comment]
唉，抱歉，私有 API 害死人…

我先重开 issues 了。

你有什么特别的  Page 吗？

**Comment by Kenshin** [comment]
抱歉，给你带来了麻烦。

我会彻底解决这个问题，关联 Issues 👉  https://github.com/Kenshin/simpread/issues/809

**Comment by Kenshin** [comment]
嗨，我找到个临时解决方案，细节请看 https://github.com/Kenshin/simpread/issues/809#issuecomment-648084621

如果方便的话，请使用上述链接给出的解决方案，并方便的话，请告知哪个版本的可以授权成功。

**Comment by Kenshin** [comment]
@swj1442291549

解决了你的问题？

**Comment by swj1442291549** [comment]
我其实从一开始就没有Notion授权的问题。

**Comment by Kenshin** [comment]
@swj1442291549 

okay 那就没问题了。 😀

**Comment by lslz627** [comment]
> 简悦已升级到 **[1.1.4.6022](http://ksria.com/simpread/changelog.html#1.1.4.6022)** 此版本为刚刚发布，请在 chrome://extensions/ 确认是否为 **6022** 版本。
> 
> 如果为 6022 版本的话，已包含此功能，同时增加了如下的新功能：
> 
> * 为导入到 Notion 的内容增加 **URL Meta data**
> 
> ![image](https://user-images.githubusercontent.com/81074/85377155-3f848900-b56b-11ea-893b-94bdfb1f2bbe.png)
> 
> * 支持 图床方式
> 
> ![image](https://user-images.githubusercontent.com/81074/85377185-4a3f1e00-b56b-11ea-96d1-63eacbd4bc42.png)
> 
> ![](https://camo.githubusercontent.com/9adfe462814a435ea57ff5fc665ce43c0cd229fe/68747470733a2f2f73312e617831782e636f6d2f323032302f30362f32322f4e4763716b462e676966)
> 
> 上述功能，详情请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.4.6022)
> 
> 我将关闭此 issues 😀

您好、问一下啊、1.1.4.6025、这个添加 url meta data 的功能好像没有生效、需要单独的配置吗

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
