### ISSUE TITLE
“发送到Notion”后文章中的图片不自动上传

### ISSUE THREAD

**Issue by Alphabet1226** [Kenshin/simpread#799]
Notion官方的剪藏扩展剪藏后文章中的图片都是原图上传Notion，但用simpread剪藏的文章图床依然是原始图床，没有存到Notion服务器里。

简而言之就是，用simpread发送到Notion的文章中的图片不是永久保存在Notion中的，只有用“临时模式+notion官方剪藏扩展”才能让图片永久保存。

希望可以让它原始上传文章的图片。

**Comment by Kenshin** [comment]
谢谢提醒，可以考虑此方式。

**Comment by Kenshin** [comment]
简悦已升级到 **[1.1.4.6022](http://ksria.com/simpread/changelog.html#1.1.4.6022)**  此版本为刚刚发布，请在 chrome://extensions/ 确认是否为 **6022** 版本。

如果为 6022 版本的话，已包含此功能，同时增加了如下的新功能：

- 为导入到 Notion 的内容增加 **URL Meta data**

![image](https://user-images.githubusercontent.com/81074/85377155-3f848900-b56b-11ea-893b-94bdfb1f2bbe.png)

- 支持 图床方式

![image](https://user-images.githubusercontent.com/81074/85377185-4a3f1e00-b56b-11ea-96d1-63eacbd4bc42.png)

![](https://s1.ax1x.com/2020/06/22/NGcqkF.gif)

***

上述功能，详情请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.4.6022)

我将关闭此 issues  😀

**Comment by Kenshin** [comment]
嗨，抱歉，做个调查~

有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？

***

如果遇到的话，试试 **导出配置文件** 再 **清除数据**  或 **重新安装** 的方式试试。

***

> **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

**Comment by Alphabet1226** [comment]
> 嗨，抱歉，做个调查~
> 
> 有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？
> 
> 如果遇到的话，试试 **导出配置文件** 再 **清除数据** 或 **重新安装** 的方式试试。
> 
> > **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

同样遇到了授权失败的问题，清楚数据和重新安装都无效。
环境是：
chrome 83.0.4103.106 (正式版本) （64 位） (cohort: Stable)
操作系统 | Windows 10 OS Version 1809 (Build 17763.1282)

**Comment by Kenshin** [comment]
唉，抱歉，私有 API 害死人…

我先重开 issues 了。

你有什么特别的  Page 吗？

**Comment by Alphabet1226** [comment]
> 唉，抱歉，私有 API 害死人…
> 
> 我先重开 issues 了。
> 
> 你有什么特别的 Page 吗？

啊，请问特别的Page是指什么呢？
可能是因为我的Pages全部都是shared而非private的原因吗？

**Comment by Kenshin** [comment]
抱歉，给你带来了麻烦。

我会彻底解决这个问题，关联 Issues 👉  https://github.com/Kenshin/simpread/issues/809

**Comment by Alphabet1226** [comment]
> 抱歉，给你带来了麻烦。
> 
> 我会彻底解决这个问题，关联 Issues 👉 #809

别这么说，您能开源并且让大家免费使用如此优秀的作品本就是一件伟大的事情，怎么能算麻烦是带来麻烦呢，应该我们感谢您带来如此优秀的产品才对。

**Comment by Kenshin** [comment]
嗨，我找到个临时解决方案，细节请看 https://github.com/Kenshin/simpread/issues/809#issuecomment-648084621

如果方便的话，请使用上述链接给出的解决方案，并方便的话，请告知哪个版本的可以授权成功。

**Comment by Kenshin** [comment]
嗨，简悦 1.1.4.6025 终于发布了！

如果你是个 Notion 重度使用者的话，就会知道 Notion Web Clipper 有多不好用了...

还好的是，同样我也是 Notion 的使用者。历经一个星期三次迭代后，简悦终于完美实现 Notion Web Clipper  的全部功能了。

包括：

- 可以选择 Page 或 Database 方式导出
- 支持 Notion.so 作为图床的方式导出
- 完美实现 Database 外链

详细请看  👉  http://ksria.com/simpread/docs/#/Notion

如果你对 Notion Web Clipper 不是很满意的话，完全可以使用简悦来替代它了~ 

最后，祝你粽子节安康！

***

之前有使用 1.1.4.6025 离线包的用户，可以替换为 Chrome Webstore 版本了 https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4

**Comment by efaun** [comment]
@Kenshin 遇到了新的问题, 上传图片的提示框一闪而过, 文章能保存成功, 但是图片没有上传到notion, 使用的还是原始链接, 重新安装插件也不行

https://user-images.githubusercontent.com/13315821/192104136-54f70fae-be65-4a0b-b401-a346fd9208a3.mp4
