### ISSUE TITLE
无法将图片保存到印象笔记

### ISSUE THREAD

**Issue by aliali-li** [Kenshin/simpread#80]
如题，文章的图片在阅读模式中能正常显示，但通过授权保存到印象笔记之后，就只剩下文字。
测试过 UISDC、VICE、SSPAI 这三个站点，都有这个问题。

**Comment by Kenshin** [comment]
@aliali-li 

1.0.3 只支持 `将 markdown 保存到 印象笔记`，暂时不支持图片保存。

另外，由于印象笔记使用了 自己独有的标签格式，而其文档有不全面，所以 `保存 Markdown 到印象笔记`  不是很完美，偶尔出现无法保存的情况。个人建议使用 Onenote 保存。

**Comment by Kenshin** [comment]
@aliali-li 
如果没有疑问的话，请关闭此 issues  😄

**Comment by aliali-li** [comment]
好的。GitHub 还不太会用，给您添麻烦了，烦请谅解。
再次感谢您的回复。

**Comment by Kenshin** [comment]
客气了，其实也是保存的时候没有太说清楚。
望使用愉快！
