### ISSUE TITLE
Notion授权问题

### ISSUE THREAD

**Issue by hymanbaiguixiong** [Kenshin/simpread#801]
我发现更新后我的授权自动消失，且点击授权后没有反应，我可以授权其他软件，唯独notion不可以
![image](https://user-images.githubusercontent.com/59363725/84891874-2c873a00-b0cf-11ea-8196-2b6f60fe3662.png)

**Comment by Kenshin** [comment]
请再次授权，然后请查看下 Chrome Devtool 有没有什么报错？

另外，你的 Page 中是否存在他人的？

**Comment by hymanbaiguixiong** [comment]
好的我试试 发件人: Kenshin Wang发送时间: 2020年6月17日 20:44收件人: Kenshin/simpread抄送: hymanbaiguixiong; Author主题: Re: [Kenshin/simpread] Notion授权问题 (#801) 请再次授权，然后请查看下 Chrome Devtool 有没有什么报错？另外，你的 Page 中是否存在他人的？—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kaaaaai** [comment]
我也碰到了同样的问题

**Comment by Kenshin** [comment]
@kaaaaai 
按照我说的提示，有什么报错信息吗？

**Comment by kaaaaai** [comment]
@Kenshin 
是这个吗？
![image](https://user-images.githubusercontent.com/30493584/85112195-d7baff00-b247-11ea-80fe-07ecd0f5c625.png)
```javascript
ssl.google-analytics.com/ga.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
vendors.js:3 Uncaught TypeError: Cannot read property 'value' of undefined
    at vendors.js:3
    at Array.forEach (<anonymous>)
    at vendors.js:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (vendors.js:3)
    at u (common.js:6)
    at Object.fireWith [as resolveWith] (common.js:6)
    at n (common.js:7)
    at XMLHttpRequest.<anonymous> (common.js:7)
```

**Comment by Kenshin** [comment]
@kaaaaai 

有可能，请问你的 Notion 有来自其它人的 Page 吗？或者说私有的？

**Comment by kaaaaai** [comment]
@Kenshin 有吧，我的主要工作空间有一些 duplicate 过来的页面，然后里面的一级目录都是私有的。有些二级目录是开放的。
然后还加入了一些其他人的工作空间，有几个都是私有的

**Comment by Kenshin** [comment]
@kaaaaai 

就是这个问题造成的，下个（这周内会出一个）补丁版本会解决这个问题。

抱歉，由于 Notion 使用了私有 API 造成测试覆盖不全面。

**Comment by kaaaaai** [comment]
@Kenshin

**Comment by kaaaaai** [comment]
@Kenshin

**Comment by kaaaaai** [comment]
@Kenshin 
不用抱歉~开发出那么好用的插件，应该收到大大感谢😜

**Comment by Kenshin** [comment]
简悦已升级到 **[1.1.4.6022](http://ksria.com/simpread/changelog.html#1.1.4.6022)**  此版本为刚刚发布，请在 chrome://extensions/ 确认是否为 **6022** 版本。

如果为 6022 版本的话，已修复此问题，同时增加了如下的新功能：

- 为导入到 Notion 的内容增加 **URL Meta data**

![image](https://user-images.githubusercontent.com/81074/85377155-3f848900-b56b-11ea-893b-94bdfb1f2bbe.png)

- 支持 图床方式

![image](https://user-images.githubusercontent.com/81074/85377185-4a3f1e00-b56b-11ea-96d1-63eacbd4bc42.png)

![](https://s1.ax1x.com/2020/06/22/NGcqkF.gif)

***

上述功能，详情请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.4.6022)

我将关闭此 issues  😀

**Comment by Kenshin** [comment]
嗨，抱歉，做个调查~

有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？

***

如果遇到的话，试试 **导出配置文件** 再 **清除数据**  或 **重新安装** 的方式试试。

***

> **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
