### ISSUE TITLE
在csdn，掘金等网站中，阅读模式下代码块字体和英文单词显示过小，代码段自定义样式无效

### ISSUE THREAD

**Issue by zjjysbd** [Kenshin/simpread#803]

**Comment by zjjysbd** [comment]
![image](https://user-images.githubusercontent.com/38010048/85203507-d5889b80-b340-11ea-9e4a-8cca30383c07.png)
![image](https://user-images.githubusercontent.com/38010048/85203512-dcafa980-b340-11ea-85c3-6a222e692226.png)

**Comment by Kenshin** [comment]
你是说 `<code>xxxx</code>` 中的内容吗？

可以使用 **自定义样式** 或 **适配站点** 的自定义样式。

不生效的的原因是不是没有加 `!important` ？

**Comment by zjjysbd** [comment]
我加了!important,是这样 设置的：
![image](https://user-images.githubusercontent.com/38010048/85266712-d5a2ab80-b4a6-11ea-9cf2-06af44990e7e.png)
可是显示的效果还是 这样：
![image](https://user-images.githubusercontent.com/38010048/85266698-cf143400-b4a6-11ea-8c3d-4814cb87d392.png)
非常实用的插件，谢谢

**Comment by zjjysbd** [comment]
对了，我不用高亮插件时候，代码字体大小也是不变化

**Comment by Kenshin** [comment]
第二张图：

```
font-size: 30px!important
```

去掉 `<30>`  中的  `<` 和 `>` 

另外，第一张图，去掉 `!important`

**Comment by zjjysbd** [comment]
问题解决，非常感谢，这个作品很棒！

**Comment by Kenshin** [comment]
搞定就好~  💪
