### ISSUE TITLE
无法连接 Notion

### ISSUE THREAD

**Issue by NpengTsui** [Kenshin/simpread#805]
- 操作系统 **MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

Notion 连接授权一直不成功

**Comment by Kenshin** [comment]
谢谢反馈，这应该是 1.1.4.6016 产生的一个 Bug 下周会修复，细节请看 https://github.com/Kenshin/simpread/issues/801#issuecomment-646554011 （往下的讨论。

**Comment by Kenshin** [comment]
简悦已升级到 **[1.1.4.6022](http://ksria.com/simpread/changelog.html#1.1.4.6022)**  此版本为刚刚发布，请在 chrome://extensions/ 确认是否为 **6022** 版本。

如果为 6022 版本的话，已修复此问题，同时增加了如下的新功能：

- 为导入到 Notion 的内容增加 **URL Meta data**

![image](https://user-images.githubusercontent.com/81074/85377155-3f848900-b56b-11ea-893b-94bdfb1f2bbe.png)

- 支持 图床方式

![image](https://user-images.githubusercontent.com/81074/85377185-4a3f1e00-b56b-11ea-96d1-63eacbd4bc42.png)

![](https://s1.ax1x.com/2020/06/22/NGcqkF.gif)

***

上述功能，详情请看 [更新日志](http://ksria.com/simpread/changelog.html#1.1.4.6022)

我将关闭此 issues  😀

**Comment by Kenshin** [comment]
嗨，抱歉，做个调查~

有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？

***

如果遇到的话，试试 **导出配置文件** 再 **清除数据**  或 **重新安装** 的方式试试。

***

> **方便的话，请告诉我，你的 Notion 授权 是否好使** ？

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
