### ISSUE TITLE
Edge浏览器设置页面乱码

### ISSUE THREAD

**Issue by swj1442291549** [Kenshin/simpread#807]
在更新到版本后1.1.4.6022，使用Microsoft Edge浏览器，在simpread设置页面出现部分文字乱码。如下图所示：

<img width="842" alt="CleanShot 2020-06-23 at 18 56 12@2x" src="https://user-images.githubusercontent.com/14990247/85383381-399aa200-b583-11ea-969e-735a9ba66b94.png">

使用Chrome无此问题。

---
Edge version: 83.0.478.54
Chrome version: 83.0.4103.116

**Comment by Kenshin** [comment]
重启浏览器，即可。

如果没有问题的话，请关闭此 issues ~

***

另外，如果你是 Notion 用户的话（不经常使用 Notion 的话，请忽略以下内容）请帮忙做个调查：

有用户提到 **1.1.4.6022 Notion 授权失败** 的问题，不知道是否发生问题的环境是什么？

***

如果遇到的话，试试 **导出配置文件** 再 **清除数据**  或 **重新安装** 的方式试试。

***

> **方便的话，请告诉我，你的 Notion 授权 是否好使** ？
