### ISSUE TITLE
会自动为页面添加css

### ISSUE THREAD

**Issue by JunVincetHuo** [Kenshin/simpread#81]
假如一开启插件就会自动添加一大堆css，如何禁止他不添加css

**Comment by Kenshin** [comment]
这些 CSS 在未开启阅读模式时不会对当前页面生效。

目前有什么影响吗？如果有的话，下个版本可以增加个黑名单。

**Comment by JunVincetHuo** [comment]
还是会生效的，我在控制台看到，无论阅读模式是否开启，这些CSS还是添加进去了，我自己开发的时候受到了影响，不知道为什么。

**Comment by Kenshin** [comment]
我的名字已经很特别了 😓 哪个名字？

**Comment by JunVincetHuo** [comment]
可能是有一个carousel的变量名。。。反正我把他全删了就没事了~

**Comment by Kenshin** [comment]
hmm…
carousel 应该之在 option 才对，明天我检查下吧。
你把疑似的名字告诉我。

**Comment by JunVincetHuo** [comment]
暂时只发现这个~~

**Comment by Kenshin** [comment]
的确是 `carousel` 造成的，我先记 bug 了，Fixed 后跟下个版本一起发布。如果对你的项目有影响的话，要不你先改个名字，要不暂时不要使用 `简悦` 。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
