### ISSUE TITLE
接入 觅道文档

### ISSUE THREAD

**Issue by zmister2016** [Kenshin/simpread#816]
你好，我是 MrDoc觅道文档（项目地址：<https://github.com/zmister2016/MrDoc>，示例站点：<http://mrdoc.zmister.com>）的作者，这是一个基于`Python`编写的`Markdown`在线文档系统。

我在MrDoc的交流群中得知了`简悦`，在体验使用之后感觉这个工具特别棒。

想通过编写插件的方式，让`简悦`支持内容导入到MrDoc，但是看[#646 ](https://github.com/Kenshin/simpread/issues/646)中说暂停了个人申请插件的需求。

不知道如何才能实现在`简悦`中集成MrDoc？

--------

MrDoc 目前通过用户在个人中心生成用户token的方式来支持如下功能：

- 获取文集列表；
- 新建文档；
- 上传图片；

假设MrDoc地址为<http://mrdoc.zmister.com>，用户token为123456，那么：

- 获取文集列表的url为：<http://mrdoc.zmister.com/api/get_projects/?token=123456>，请求方法`GET`
- 新建文档的url为：<http://mrdoc.zmister.com/api/create_doc/?token=123456>，请求方法`POST`
- 上传图片的url为：<http://mrdoc.zmister.com/api/upload_img/?token=123456>，请求方法`POST`

期待你的回复！

**Comment by Kenshin** [comment]
嗨，你好，很高兴能联系我。

目前 **插件编辑器** 存在一些问题，所以我暂停了申请要求。 😶 

具体接入我来实现就好，首先看下能否用 **插件** 的方式接入；不行的话，就把它 **内置到** 简悦的导出服务。

**Comment by zmister2016** [comment]
@Kenshin 感谢回复！需要我这边提供接口文档之类说明吗？

**Comment by Kenshin** [comment]
目前暂时不需要。

此功能会随着下个版本一起发布，Coding 时的时候，如有需要我再联络你~  😀

**Comment by zmister2016** [comment]
@Kenshin 好的，感谢感谢~

**Comment by Kenshin** [comment]
嗨，我这两天开始做 `MrDoc` 的集成，目前的想法是做成： `动作`（即：以 [简悦 · 插件](https://simpread.ksria.cn/plugins/)）的形式。

我刚刚注册了下 http://mrdoc.zmister.com/user/register/ 发现需要注册码。
不知道能否给予一定的测试环境？

PS： 有可能的话，使用我的 Github 邮箱地址，作为登录名即可。

**Comment by zmister2016** [comment]
@Kenshin 已经为您添加了一个用户，用户名：fxblog@gmail.com ，初始密码：123456 。用户API相关接口说明文档：http://mrdoc.zmister.com/project-54/doc-389/   感谢您的关注

**Comment by Kenshin** [comment]
太棒了，谢谢 🙏🏻
为了安全性，我把上条部分内容删除了。

还有个事情，能否给我提供一个白色的 icon ？

**Comment by zmister2016** [comment]
@Kenshin 好的，白底的 icon 图片地址 http://mrdoc.zmister.com/media/202007/mrdoc_logo_1594169962.png，如果不合适的话，我再重新制作一个。

**Comment by Kenshin** [comment]
基本上就是这样了，不过只能跟下个简悦版本一起发布~  😀 

![2020-07-09_18-52-28](https://user-images.githubusercontent.com/81074/87031790-2be94b80-c216-11ea-8df6-a2d8c1ece958.gif)

PS：暂时没上图床系统，因为简悦还未支持图床，这个功能也可以作为插件实现它。

**Comment by Kenshin** [comment]
基本上就这样了，不过，只能随着下个版本发布。

![2020-07-10_12-52-00](https://user-images.githubusercontent.com/81074/87118208-54705480-c2ad-11ea-9ac4-294e62b4bdf3.gif)

为了这个功能，我顺道给插件系统添加了套 UI 系统...  😱 

***

另外，图床的功能暂时没加，这个后续也会考虑加上。

**Comment by zmister2016** [comment]
@Kenshin  太棒了！期待新版本的发布。后续如果还有什么需要的，可以随时联系我。

**Comment by Kenshin** [comment]
@zmister2016 

嗨，新版已经发布了，另外是否有简悦 · 高级账户资格，没有的话，我赠你一枚。

所以我关闭这个 Issues 了。 😀

**Comment by lazzman** [comment]
> 图床的功能

请求添加：图床的功能
