### ISSUE TITLE
简悦插件中心无法登陆

### ISSUE THREAD

**Issue by yungfei** [Kenshin/simpread#818]
使用简悦的时候有个问题，就是开启阅读模式无法加载其他chrome查词插件，但是简悦的插件中心似乎也有点问题，提示500：服务器出错。这该如何解决呢？

**Comment by Kenshin** [comment]
正在排查，请稍等我的通知。

**Comment by Kenshin** [comment]
插件中心可以访问了。

***

> 开启阅读模式无法加载其他chrome查词插件

目前是这样的，由于简悦的机制导致的，你可以使用 **临时阅读模式** 来解决这个问题，或者安装简悦自己的 [划词翻译](https://simpread.ksria.cn/plugins/details/ohnTKVHz4a)

**Comment by yungfei** [comment]
谢谢你，很感谢你的付出，他确实不错。
