### ISSUE TITLE
能不能自定义添加网页

### ISSUE THREAD

**Issue by samyzny** [Kenshin/simpread#82]
如题

**Comment by Kenshin** [comment]
目前还不能自己添加，下个版本 `1.1.0`  会增加此功能。😌

**Comment by MagisDing** [comment]
现在medium.com还没有加入适配列表，希望自定义添加功能能早日实现。

**Comment by Kenshin** [comment]
@MagisDing
1.1.0 会提供此功能。
即将发布的 1.0.4 包含了一个彩蛋，也可以添加。

**Comment by Kenshin** [comment]
1.1.0 已经发布，将关闭此 issues~  😀
