### ISSUE TITLE
阅读模式下代码注释无法显示

### ISSUE THREAD

**Issue by p5ydn0** [Kenshin/simpread#828]
你好，感谢你的分享。我非常喜欢。

**问题描述：**

我的问题是，在浏览该 [文章](https://www.jianshu.com/p/21fb596ed86c) 的时候 ，在阅读模式下代码块中的代码无法显示注释；导出为 markdown 格式后的文件中也同样没有代码注释。

**已尝试：**

* 已启用 [代码段增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)，但是删除插件后问题仍然存在。
* 在提此 issue 之前我已阅读该 issue：[代码块缺少注释内容/Missing comments in code blocks. #576](https://github.com/Kenshin/simpread/issues/576)，但是仍然没有得到解答。

**环境：**

* 简悦 Version：1.1.4.6025
* Chrome Version：83.0.4103.116（正式版本） （64 位）
* macOS Version：10.15.5 

谢谢。

**Comment by Kenshin** [comment]
谢谢反馈 & 自查

给你带来了困扰，这应该是简悦自身的 Bug 我先记下了，修复后（应该是下个版本）会在这里通知你。

**Comment by Kenshin** [comment]
嗨，**[代码增强插件](https://simpread.ksria.cn/plugins/details/klGUASLasg)** 已更新到 0.0.6 修复了此问题，我将关闭此 issues 如有疑问，请重新开启它。 😀 

更新方法：点击上面链接中的 **安装当前插件** 即可。
