### ISSUE TITLE
授权后仍无法保存页面（已解决）

### ISSUE THREAD

**Issue by hwthwu** [Kenshin/simpread#83]
在设置中操作完成账户授权以后，如果尝试再次授权会出现是否重新授权的提示说明是授权成功的，但是刷新设置页授权开关会自动关闭而且在阅读模式里仍无法保存页面到授权的账户，pocket、印象笔记等第三方授权均无法保存，浏览器为chromium内核的QQ浏览器。

**Comment by Kenshin** [comment]
提示授权成功返回到设置页面，会有个时间差，因为 oAuth 还需要再操作一步，如果再这个时候刷新页面，会出现 `false` 的情况。
PS：我看到你改为了 `已解决` 是如何解决了？
