### ISSUE TITLE
今天更新了配置，微信公众号文章排版有些问题

### ISSUE THREAD

**Issue by aLIEz-xue** [Kenshin/simpread#832]
RT

**Comment by aLIEz-xue** [comment]
https://mp.weixin.qq.com/s?__biz=MzU1NjgwNTExNQ==&mid=2247485861&idx=2&sn=96bf9267514ade73bf9de5b956840c95&chksm=fc3e3731cb49be27965d47d035b95c49f7e91d1ed54d21107c9ff000f2cc19aff92108783ebd&mpshare=1&scene=23&srcid=0708zS481rXnjCpijgQc5cRx&sharer_sharetime=1594167604687&sharer_shareid=58e01ae8c225d1a89348cc405fafebec#rd

**Comment by Kenshin** [comment]
谢谢反馈

请问更新了什么配置？
觉得排版有什么问题？

建议截个图说明

另外，第一个段的内容我删了。
