### ISSUE TITLE
保存到语雀无限等待

### ISSUE THREAD

**Issue by ciddiaz** [Kenshin/simpread#839]
[您好，将网页内容保存到语雀时，其实在几秒钟内就已经保存成功，可以在语雀看到，但是右上角“请等待”的提示框会转动并且留存很久很久，反正是半个小时也不见消失，这样会不知道何时保存成功，无法确定是否能够关闭，造成时间浪费，希望能够解决！
![Snipaste_2020-07-16_08-43-04](https://user-images.githubusercontent.com/45554715/87613748-d2ff4300-c740-11ea-9070-a42181fd012c.png)

**Comment by Kenshin** [comment]
嗨，你好，我刚刚测试了下没有遇到你说的问题。
请问你的简悦版本是多少？以及试试重新授权语雀？
另外，在发生此问题的时候，看看 Chrome DevTools 的打印信息有什么错误？

**Comment by wxjer** [comment]
控制台报错：
vendors.js:3 Uncaught TypeError: o.toLowerCase is not a function
    at Object.<anonymous> (vendors.js:3)
    at u (common.js:6)
    at Object.fireWith [as rejectWith] (common.js:6)
    at n (common.js:7)
    at XMLHttpRequest.<anonymous> (common.js:7)
 
common.js:7 跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json 的跨源响应 https://www.yuque.com/api/v2/repos/1353567/docs。有关详细信息，请参阅 https://www.chromestatus.com/feature/5629709824032768。

**Comment by Kenshin** [comment]
@wxjer 

请问是什么环境？系统和 Chrome 都告诉下。

**Comment by ciddiaz** [comment]
我这边也是这条信息，前面还有一句：
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' blob: *.zhihu.com g.alicdn.com qzonestyle.gtimg.cn res.wx.qq.com open.mobile.qq.com 'unsafe-eval' unpkg.zhimg.com unicom.zhimg.com captcha.gtimg.com captcha.guard.qcloud.com pagead2.googlesyndication.com cpro.baidustatic.com pos.baidu.com dup.baidustatic.com i.hao61.net 'nonce-6653c56e-1895-49c0-9a42-8cf474e03e37' hm.baidu.com zz.bdstatic.com www.googletagmanager.com resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

简悦版本 1.1.4.6025
Chrome版本 84.0.4147.89
系统版本 Windows 10 家庭中文版 1903

**Comment by Kenshin** [comment]
emmm

很奇怪，按道理不应该，不过，可以修复此问题。

但只能下个版本发布了。

**Comment by synozhang** [comment]
我也遇到了类似的问题，保存到语雀无限等待。感谢作者大大解答

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，某些浏览器会产生 CORS 的错误，现在应该没问题了，我将关闭这个 Issues
***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
