### ISSUE TITLE
印象笔记保存失败

### ISSUE THREAD

**Issue by luoxiaoji** [Kenshin/simpread#84]
首先是授权几次才功能，明明提示成功，选项中显示还是不成功的，不知为何。
重启几次正常授权成功了，可能是延迟？

然后再保存笔记一直提示保存失败，让我过来提交issues

**Comment by Kenshin** [comment]
感谢提 issues :)

- 保存失败的原因请看 [授权服务 · 印象笔记保存失败](https://github.com/Kenshin/simpread/wiki/授权服务#印象笔记保存失败)
 _根据上述提示，方便的话，请告知 url 地址，我再单独适配_

- 授权的问题是因为当调回到 `选项页` 后，还需要再操作一步（再次调用 印象笔记 API），所以有可能会出现时间差，需要等待几秒钟（视网络情况）
  _当然，这个过程其实应该有提示最好，我会考虑这方面的体验性。_

**Comment by rosuH** [comment]
@Kenshin 
印象笔记保存失败。
附链接：
[重新认识 AndroidStudio 和 Gradle, 这些都是你应该知道的](http://mp.weixin.qq.com/s?__biz=MzIwNjQ1NzQxNA==&mid=2247483946&idx=1&sn=da2458e2e6cd87115adec58ac0b0d3c6&chksm=97201d03a05794150a48bf3c0586b11c355c541dcd5b0f76dcad7fd1304d080459e6564d8298&mpshare=1&scene=1&srcid=10174B3djddcTcxfdRP3VyqP#wechat_redirect)

**Comment by Kenshin** [comment]
@rosuH 
刚看了下，这是 `微信订阅号` 的文章，微信公众号由于基于 UGC，订阅号的文章里面会加入稀奇古怪的标签与 img，在适配阅读模式时都挺麻烦，更何况变态的 ENML 了，下图是转换失败的原因：

![image](https://user-images.githubusercontent.com/81074/30255197-47c158b2-9667-11e7-853e-401f50bcfef9.png)

PS：不是我不喜欢 `Evernote` 而是自从我丢失了几篇内容后，义无反顾的投到了 `Onenote` 了，如果你也有此意的话，提供几个建议：

- 如果没有 "洁癖" 的话，其实不用将 Evernote 的内容全部迁移到 Onenote ；
- 基于上条，只需要大致记住哪些内容是在 Evernote 即可；
- Onenote 的缺点是没有 标签系统；
- 基于上条，我的做法是将 Onenote 设置与 Evernote 一样的笔记本；每个笔记本中的分区对应了 Evernote 的标签（但这里只能是一个标签）；

总之的做法是：尽量保证 Evernote 与 Onenote 的结构一致即可。

**Comment by rosuH** [comment]
@Kenshin 感谢您的回复！
但是请教一下，该如何解决 Onenote 的 **同步问题**？即便挂了代理依旧感觉回天乏术...
以前看过可以改 host 解决的，但是没留意就找不到了...

**Comment by Kenshin** [comment]
@rosuH 
这是个麻烦事儿，有两个解决办法：
- 科学上网
- 使用 Web 版...

因为我有多台电脑，所以只有一台是有 Client 端，其余都是 Web 端，而且它的 Web 端最近刚刚改版，越来越接近 Native 端的使用体验了。

祝早日脱离苦海 ~ 😁

**Comment by rosuH** [comment]
@Kenshin 还是得科学上网解决问题。
此外，请问简悦 --> Onenote 的默认笔记本是否可以更改？
查看了 wiki 之后没有看到相关设定。还是应该在 Onenote 中修改呢？Thk.

**Comment by luoxiaoji** [comment]
OneNote 在你说完之后我尝试使用了一下，各种登录失败，翻墙也各种不适应，所以还是放弃了。。

**Comment by rosuH** [comment]
@luoxiaoji 在路由器部署代理就不会不适应了。

**Comment by Kenshin** [comment]
@luoxiaoji 
额，`爱国上网` 也不行吗？

@rosuH 
目前 `不支持更改 Onenote 保存位置` ，因为如果这么做的话，UI 会比较复杂，目前没有想好怎么办 😭 所以暂时都是放在了 `快速笔记`（默认）里面。

**Comment by rosuH** [comment]
@Kenshin Got you~

**Comment by wisesky** [comment]
Evernote 保存就能成功，快速浏览了代码，发现Evernote和印象笔记的保存代码是复用的，遂认为应该是印象笔记部分传递API链接部分可能传错了，于是在read.jax -> read.onService() 中
![image](https://user-images.githubusercontent.com/3850079/30465885-8fba9522-9a0c-11e7-89c4-fdf1edf949b9.png)发现只有evernote，之后
![image](https://user-images.githubusercontent.com/3850079/30465902-a8d4e8f0-9a0c-11e7-8277-621b297f8575.png)这一段把id = evernote ，可能对
![image](https://user-images.githubusercontent.com/3850079/30465923-d78ea410-9a0c-11e7-9a6d-8870fee374fe.png)中exp[id]获取evernote 或者 印象笔记 API链接获取产生影响，自己修改代码发现缺少一点相关bundle等文件无法测试，望作者能验证我等猜想

**Comment by Kenshin** [comment]
@wisesky 
感谢方案~
`印象笔记 与 Evernote` 的确是同一个 class，我会 review 你说的部分。

之前测试过，同一篇文章可以同时保存到 `印象笔记 与 Evernote`，请问这个问题是偶发？还是每次都有？也请告知发生错误的 url。

**Comment by wisesky** [comment]
我的环境是Mac+Chrome，目前我自己印象笔记没有一次成功保存过(包括但不限于
https://www.ibm.com/developerworks/cn/analytics/library/iot-deep-learning-anomaly-detection-1/index.html?simpread_mode=read，ibm developworkds
http://geek.csdn.net/news/detail/235465, csdn page
https://zhuanlan.zhihu.com/p/29333076, 知乎专栏
https://www.zhihu.com/question/63651462/answer/223981662， 知乎回答
https://movie.douban.com/subject/26634179/?from=showing， 豆瓣简介
）
,Evernote自己只试过几次没出现失败的情况，毕竟Evernote用的不多，不是主力生产工具，推荐给朋友简单的使用Win7/10 + 360极速浏览器／Chrome 的印象笔记也反映印象笔记无法保存，URL暂未提供
在 2017年9月15日，12:57，Kenshin Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


@wisesky<https://github.com/wisesky>
感谢方案~
印象笔记 与 Evernote 的确是同一个 class，我会 review 你说的部分。

之前测试过，同一篇文章可以同时保存到 印象笔记 与 Evernote，请问这个问题是偶发？还是每次都有？也请告知发生错误的 url。

**Comment by Kenshin** [comment]
保存时如出现以下错误

![image](https://user-images.githubusercontent.com/81074/30469839-f99747ba-99b7-11e7-975d-4409d80e5bbf.png)

大多是因为 HTML 转换 ENML 失败导致，比如，你给出的 url http://geek.csdn.net/news/detail/235465

失败信息：
![image](https://user-images.githubusercontent.com/81074/30469924-42fd710e-99b8-11e7-9e2f-e5bfebd9be5f.png)

***
因为 `印象笔记 与 Evernote` 是同一个 class ：
![image](https://user-images.githubusercontent.com/81074/30470060-de4f1c16-99b8-11e7-95ff-6214e52da4a4.png)

印象笔记 的 type 是 `yinxiang`，而 `exp['yinxiang']` 是不存在的，所以需要改成 `evernote`， 即 `exp['evernote']`，也就是你给出这段含义：

![image](https://user-images.githubusercontent.com/3850079/30465902-a8d4e8f0-9a0c-11e7-8277-621b297f8575.png)

`exp.VerifySvcWrapper` 的含义： 确保 `chrome local storage` 的 type 存在值
![image](https://user-images.githubusercontent.com/81074/30470271-a134985a-99b9-11e7-8b3f-e56652ba1d41.png)

type 是区分 `印象笔记 与 Evernote` 的，但 `export[id]` 不区分。

***

建议使用  https://sspai.com/post/39491 试试 `印象笔记 与 Evernote` ，看是否能正常保存。

**Comment by wisesky** [comment]
谢谢作者指导，我也测试了好几遍才发现了，还是ENML的原因，那几次Evernote保存成功，但是印象笔记没有保存成功的问题今天测试却没有重现出来，可能是之前一直挂着科学上网导致Evernote访问速度比印象笔记快的缘故，所以跟Evernote 与 印象笔记的创建笔记代码无关，结论还是XHTML 转 ENML 元素的关系，不好意思给作者带来困扰，有机会仔细研究下代码，希望能修复这个功能，毕竟冲了印象笔记 高级会员，不得不继续用一年！！！同时表示以后充值，一定按月付费 -_-
在 2017年9月15日，15:06，Kenshin Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


保存时如出现以下错误

[image]<https://user-images.githubusercontent.com/81074/30469839-f99747ba-99b7-11e7-975d-4409d80e5bbf.png>

大多是因为 HTML 转换 ENML 失败导致，比如，你给出的 url http://geek.csdn.net/news/detail/235465

失败信息：
[image]<https://user-images.githubusercontent.com/81074/30469924-42fd710e-99b8-11e7-9e2f-e5bfebd9be5f.png>

________________________________

因为 印象笔记 与 Evernote 是同一个 class ：
[image]<https://user-images.githubusercontent.com/81074/30470060-de4f1c16-99b8-11e7-95ff-6214e52da4a4.png>

印象笔记 的 type 是 yinxiang，而 exp['yinxiang'] 是不存在的，所以需要改成 evernote， 即 exp['evernote']，也就是你给出这段含义：

[image]<https://user-images.githubusercontent.com/3850079/30465902-a8d4e8f0-9a0c-11e7-8277-621b297f8575.png>

exp.VerifySvcWrapper 的含义： 确保 chrome local storage 的 type 存在值
[image]<https://user-images.githubusercontent.com/81074/30470271-a134985a-99b9-11e7-8b3f-e56652ba1d41.png>

type 是区分 印象笔记 与 Evernote 的，但 export[id] 不区分。

________________________________

建议使用 https://sspai.com/post/39491 试试 印象笔记 与 Evernote ，看是否能正常保存。

**Comment by Kenshin** [comment]
@wisesky 
没关系的~

我之前已经不止一次的吐槽过 Evernote 的文档了... 没办法，为了保证转换较成功，前前后后浪费了2天的时间来做各种的可能性，最后才有了现在的情况。（ 估计保守的说，50% 的成功机率）

感兴趣的话，可以看看 
https://github.com/Kenshin/simpread/blob/master/src/service/site.js  
`html2enml` 函数，是关于 HTML → ENML 的代码。

**Comment by Kenshin** [comment]
Hi，没有疑问的话，我将关闭此 issues，如需要重新开启它。 😊
