### ISSUE TITLE
保存到notion一直提示：授权已过期，请重新授权

### ISSUE THREAD

**Issue by artxia** [Kenshin/simpread#843]
版本是Chrome商店安装的 1.1.4.6025

一直在授权，授权完了点保存又提示过期。从没保存成功过。

如图：

![image](https://user-images.githubusercontent.com/50513568/87749162-7a0bd980-c82a-11ea-8b60-290df9108a20.png)

**Comment by Kenshin** [comment]
不要在这里进行授权操作。
选项页 → 高级设定 → 授权管理。

PS：没问题的话，请关闭这个 Issues ~

**Comment by artxia** [comment]
> 不要在这里进行授权操作。
> 选项页→高级设置→授权管理。
> 
> PS：没问题的话，请关闭这个问题〜

我是先在授权管理进行授权，再打开文章页面进行的保存。
这个提示是在先授权后出现的

**Comment by artxia** [comment]
经过测试，发现是cookie的设置问题。
如图只能选前两个，不能选后两个。也就是不能设置为阻止第三方cookie

![image](https://user-images.githubusercontent.com/50513568/87764492-104ef800-c849-11ea-85da-66ce196110e2.png)

**Comment by Kenshin** [comment]
嗨，谢谢提示。

因为 Notion 的授权没有 API 所以只能依赖与 Cookie 我会在帮助文档中更新这段内容。

**Comment by keepthinkingit** [comment]
果然问题在我 , 给 notion 发了封邮件 , 等 api 支持吧 .

**Comment by Kenshin** [comment]
@keepthinkingit 

额？你的这个 Issues 提问者也是一个人？

**Comment by keepthinkingit** [comment]
> @keepthinkingit
> 
> 额？你的这个 Issues 提问者也是一个人？

我跟提问者不是同一个人 . 今天想起来有这个问题在这里找到了答案 . 因为我 chrome 也是不给第三方 cookie 权限的 .

**Comment by Kenshin** [comment]
@keepthinkingit 

不给 Cookies 肯定是不行的，不过，我也可以考虑是否添加手动设置（即自动步骤获取 Cookies ）的选项。

**Comment by Kenshin** [comment]
嗨，我增加了一个新的导入到 Notion 插件，非常适合 Notion 用户使用。

## 名称及下载地址

**[导入到 Notion 辅助增强：从简悦导入到 Notion 后自动添加题图、标签、来源等](https://github.com/Kenshin/simpread/discussions/3572)**

## 功能

增强导入到 Notion 的内容，包括：增加 favicon、题图、同步稍后读标签、添加自定义标签等功能。

![pika-2022-03-23T08_29_21 901Z](https://user-images.githubusercontent.com/81074/159837023-94d00602-a582-4045-b57c-685fbc7c226b.png)

## 视频

https://user-images.githubusercontent.com/81074/159435586-59b9f62e-6eff-492c-8410-218b3047df16.mp4

**Comment by Kenshin** [comment]
> 嗨，[导入到 Notion 辅助增强](https://github.com/Kenshin/simpread/discussions/3572) 更新了 1.1.0 版本，增加了导入标注到 Notion，细节可以 [看这里](https://github.com/Kenshin/simpread/discussions/3572#discussioncomment-2484020)，比扩展端提供的导出标注方案更加强大和智能。


# 视频

https://user-images.githubusercontent.com/81074/161916609-8399487c-053f-4506-ac8c-f3f3d96acb4f.mp4
