### ISSUE TITLE
全文翻译，划词翻译，划词搜索插件不工作。

### ISSUE THREAD

**Issue by BopSun** [Kenshin/simpread#846]
以上插件不工作，没有全文翻译的悬浮图标，划词后也没有任何提示。

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

Chrome 浏览器，安装了沙拉查词扩展。

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win10**

- 浏览器版本 **Chrome 84.0.4147.89（正式版本） （64 位）**

- 简悦版本 **1.1.4**

- 发生问题的地址 https://www.bbc.com/news/world-us-canada-53450820

**Comment by Kenshin** [comment]
嗨，因为你重提了 Issues 所以我把之前的 https://github.com/Kenshin/simpread/issues/820 对应的问题删除了。

我在外面，你可以多试试不同的页面，均不好使吗？

**Comment by mhh0318** [comment]
Microsoft Edge 
版本 84.0.522.40 (官方内部版本) (64 位)
也有同样问题，沙拉查词跟Google翻译均无法工作。

**Comment by Kenshin** [comment]
@mhh0318 

`沙拉查词` 和 `Google翻译 ` 无法工作的问题跟这个 Issues 无关，这是因为简悦使用了特殊的方式，为了避免 CSS 污染。

**Comment by mhh0318** [comment]
> @mhh0318
> 
> `沙拉查词` 和 `Google翻译 ` 无法工作的问题跟这个 Issues 无关，这是因为简悦使用了特殊的方式，为了避免 CSS 污染。

多谢答复！

**Comment by Kenshin** [comment]
@mhh0318 

沙拉查词有个方式可以绕过这个问题，你可以翻翻它的 Github Issues 或帮助文档。

另外，如果不是需求量很大的话，也可以试试简悦自带的查词方式 https://simpread.ksria.cn/plugins/details/ohnTKVHz4a

**Comment by Kenshin** [comment]
# [全文翻译](https://github.com/Kenshin/simpread/discussions/1593)

更新到了 1.1.0 版，增加了下面的新功能：

- `Add` [进入阅读模式后自动启用与白名单](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444778)

- `Add` [段落翻译](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3444569)

- `Add` [DeepL](https://github.com/Kenshin/simpread/discussions/1593#discussioncomment-3492095) 

## 视频

https://user-images.githubusercontent.com/81074/187115523-1aa65c8e-599d-40cf-8737-bbb17b692038.mp4

***

# [划词翻译](https://github.com/Kenshin/simpread/discussions/1592) 

更新到 1.0.0 版，增加了一些适合英语学习者的新功能，包括：

- `Add` 多种翻译引擎

- `Add`选项页

    - 划词后以何种方式翻译，包括：鼠标移动上 · 鼠标点击 · 自动翻译。

## 生词本

[**生词本**](https://github.com/Kenshin/simpread/discussions/1592#discussioncomment-3499298) 是 1.0.0 增加的功能，也是最重要的功能，通过生词本，可以快速标记当前的生词，并且自动显示翻译结果。

## 视频操作

https://user-images.githubusercontent.com/81074/187348845-d36e46f0-c9ec-4f30-b6b5-d2078fbcafbd.mp4
