### ISSUE TITLE
配置界面部分文字描述 字体过小

### ISSUE THREAD

**Issue by kuyagic** [Kenshin/simpread#848]
插件版本 1.1.4.6025
浏览器 Chrome  85.0.4183.26 (Official Build) (64-bit) 和 Edge Version 83.0.478.28 (Official build) (64-bit)

设置界面的 包括不限于高级设定下的 部分设置描述字体过于小.已排除本地字体问题. 元素审查看到字体就 7.5px

![image](https://user-images.githubusercontent.com/1469330/87873600-83956d00-c9f5-11ea-966b-f8074965a90f.png)

![image](https://user-images.githubusercontent.com/1469330/87873606-8ee89880-c9f5-11ea-82d2-ccffaa8ebc68.png)

![image](https://user-images.githubusercontent.com/1469330/87873618-9e67e180-c9f5-11ea-8ceb-602363c26a7e.png)

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
