### ISSUE TITLE
使用离线下载html长时间为下载问题

### ISSUE THREAD

**Issue by crazyshark** [Kenshin/simpread#849]
http://www.louisvv.com/archives/2282.html   这个页面离线下载html长时间无响应

**Comment by Kenshin** [comment]
谢谢反馈，这是 Bug 因为 title 中的多了 `:` 造成的，已修复，只能下个版本发布了。

你可以手动将标题中的 `:` 通过 DevTool 删除掉，来规避这个问题。

**Comment by cf3b7S** [comment]
测试发现如果 title 中包括英文问号 `?` 也会出现该问题

**Comment by Kenshin** [comment]
谢谢反馈，下个版本发布，到时候在这里通知你。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，

**Comment by Kenshin** [comment]
嗨，我解决了这个问题，你可以安装相应的插件，细节请看 https://github.com/Kenshin/simpread/issues/1093
