### ISSUE TITLE
与「收趣」扩展冲突问题，在标题上出现「将中的收藏导入收趣」字眼

### ISSUE THREAD

**Issue by HueLiu** [Kenshin/simpread#85]
![](https://i.loli.net/2017/09/08/59b21dcf6ba47.png)
![](https://i.loli.net/2017/09/08/59b21ddff11bf.png)

如图所示，会出现「将中的收藏导入收趣」的字眼，应该是和扩展有处理的冲突了，适当屏蔽一下相关字眼。

另外，「收趣」是国内类似于pocket的东西，对国内的网站适配比较好，可以尝试与其合作。
[收趣官网](https://shouqu.me/)
[收趣扩展地址](https://chrome.google.com/webstore/detail/shouqu/ofmcnfnfchmhlchdifeobmjjhmkijpnf)

**Comment by HueLiu** [comment]
补充一下，这是在IT之家中出现的情况。其他网站貌似是没有问题的（暂时没有发现其他问题）

**Comment by Kenshin** [comment]
感谢反馈~

可以修改 `ithome` 的站点适配器，规则如下：
进入 `阅读模式` → `右侧控制栏` → `设定` → `标题栏` 的内容修改为如下：
```
[[{$('.post_title').find('h1').text()}]]
```
即可解决，如图：
![snipaste20170908_130731](https://user-images.githubusercontent.com/81074/30196933-d99a0414-9496-11e7-8b71-bbda59956c60.png)

另外，收趣 没有提供 API，我会联络它们，看看能否集成。
