### ISSUE TITLE
阅读模式无法识别到正文,手动框选之后也不行.沉浸模式下没有问题

### ISSUE THREAD

**Issue by charles-slangelec** [Kenshin/simpread#850]
**小提示**

> 简悦已经服务 70K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **1.1.4**

- 发生问题的地址 <https://blog.csdn.net/21cnbao/article/details/106110693>

**请描述你的问题**

> 阅读模式无法识别到正文,手动框选之后也不行.沉浸模式下没有问题

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

![image](https://user-images.githubusercontent.com/16753703/87904476-f142a700-ca90-11ea-92af-97a57e86bddd.png)

**Comment by Kenshin** [comment]
谢谢反馈。
我刚测试了 **手动框选** 应该可以识别正文。

CSDN 中的个别页面存在无法识别的情况，但一般来说都可以通过手动识别或框选生成正文的。

请确认下~

**Comment by charles-slangelec** [comment]
是的,手动选择可以了.&nbsp;
之前应该是我手动框选,选择错了. 我选择了整个中间的区域,包括了文章的标题了.


--------------原始邮件--------------
发件人："Kenshin Wang "<notifications@github.com&gt;;
发送时间：2020年7月20日(星期一) 下午3:16
收件人："Kenshin/simpread" <simpread@noreply.github.com&gt;;
抄送："zhsun "<charles.sun@slangelec.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [Kenshin/simpread] 阅读模式无法识别到正文,手动框选之后也不行.沉浸模式下没有问题 (#850)
-----------------------------------

 

 
谢谢反馈。
 我刚测试了 手动框选 应该可以识别正文。
 
CSDN 中的个别页面存在无法识别的情况，但一般来说都可以通过手动识别或框选生成正文的。
 
请确认下~

**Comment by Kenshin** [comment]
okay 那我关闭这个 Issues ~  😀

**Comment by charles-slangelec** [comment]
好的好的~ 谢谢您编写的这款阅读插件, 感觉非常棒哦!!&nbsp;

--------------原始邮件--------------
发件人："Kenshin Wang "<notifications@github.com&gt;;
发送时间：2020年7月20日(星期一) 下午4:24
收件人："Kenshin/simpread" <simpread@noreply.github.com&gt;;
抄送："zhsun "<charles.sun@slangelec.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [Kenshin/simpread] 阅读模式无法识别到正文,手动框选之后也不行.沉浸模式下没有问题 (#850)
-----------------------------------

 

 
okay 那我关闭这个 Issues ~

**Comment by Kenshin** [comment]
客气，祝你用的愉快！
