### ISSUE TITLE
在线版无法使用,/trans返回405

### ISSUE THREAD

**Issue by lx200916** [Kenshin/simpread#853]
![image](https://user-images.githubusercontent.com/44310445/88251668-111ada80-ccde-11ea-8b55-ca807187e26a.png)

**Comment by Kenshin** [comment]
emmm
这个服务的配额满了，只能下个月初恢复... 到时候我会在这里通知你。

谢谢提示~

**Comment by Kenshin** [comment]
嗨，此问题已修复，（应该）不会再出现类似的问题了。 😅

**Comment by AlexYuan** [comment]
这个服务还能继续使用吗？还是url变了？ @Kenshin
