### ISSUE TITLE
【站点】知乎-每日新知

### ISSUE THREAD

**Issue by nuomi1** [Kenshin/simpread#86]
https://www.zhihu.com/remix/columns/1/tracks/889524457457205249/reference

目前知乎没有给出「每日新知」的 Web 入口，只有从 Android 分享可以得到链接，连 iOS 都不可以……

**Comment by Kenshin** [comment]
这都行 😱😰👍 
适配完通知你～

**Comment by Kenshin** [comment]
刚更新了一批新站，但未包含此 url，原因：

- 除了这篇文章外，我竟未找到其它类似 `知乎-每日新知` 的 url 😷

- 这个 url 里面的 html 结构太乱了（ 竟然比微信公众号还乱...）暂时适配失败...

**Comment by nuomi1** [comment]
也好，等知乎出 Web 入口。

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，将关闭 issues 。

增加了 `临时阅读模式` 可支持任意页面，详细请看 [临时阅读模式](https://github.com/Kenshin/simpread/wiki/%E4%B8%B4%E6%97%B6%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)

你可以暂时使用这个功能来实现阅读模式。

**Comment by Kenshin** [comment]
每日新知 应该被知乎下线了，所以我将关闭此 issues

***

另外，简悦已升级到 [1.1.2.5005](http://ksria.com/simpread/welcome/version_1.1.2.5005.html) 版本，增加了全新的 [词法分析引擎](http://ksria.com/simpread/docs/#/词法分析引擎)

解决了此类问题，详细说明请看

- [LaTeX 解析](http://ksria.com/simpread/docs/#/词法分析引擎?id=latex-识别)

- 某些图片被错误居中的情况；

- 识别图片的相对地址；

- 去掉一些无用的多余空行；

以及增加了一些新功能：

- [更加方便的右键菜单](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#menu)

- [分享卡](http://ksria.com/simpread/welcome/version_1.1.2.5005.html#share)
