### ISSUE TITLE
聚焦模式的导出功能可以增加离线 Markdown 和离线 html 吗？

### ISSUE THREAD

**Issue by loveshizuka** [Kenshin/simpread#861]
简悦很棒！我一般使用它做信息备份，将正文内容导出为离线 Markdown。按理通过聚焦模式，手动精确选取正文内容后，直接导出离线内容最为方便，但偏偏没有导出离线 Markdown 和 离线 html 的选项，只能使用阅读模式导出离线内容。可如果智能选取的正文内容不合适，还得重新选择正文内容选区，再次回到阅读模式后才能保存离线内容。
所以，能在聚焦模式下增加导出离线 Markdown 和 离线 html 的选项吗？非常感谢~！

**Comment by Kenshin** [comment]
谢谢反馈。

已修复此问题，下个版本发布~

**Comment by loveshizuka** [comment]
非常感谢！

**Comment by Kenshin** [comment]
请不要关闭这个 Issues 等发布新版后我再关闭它。 😀

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，目前 **聚焦模式与阅读模式在导出服务的支持上几乎是一样的。**

所以我将关闭此 issues

***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
