### ISSUE TITLE
保存到语雀存在问题

### ISSUE THREAD

**Issue by nageshuizeii** [Kenshin/simpread#864]
![image](https://user-images.githubusercontent.com/16527235/88996066-d4269780-d31e-11ea-81b0-6d8a0028ee72.png)
成功保存到语雀后，提示仍然在保存中，且该提示不自动消失

**Comment by Kenshin** [comment]
关联问题 https://github.com/Kenshin/simpread/issues/839 已经解决，下个版本发布。

**Comment by Kenshin** [comment]
嗨，[简悦 2.0](https://sspai.com/61996) 发布了，半个月前就发布了此版本，但一直没有时间来 Close issues 

这个问题被 2.0 Fixed 掉了，某些浏览器会产生 CORS 的错误，现在应该没问题了，我将关闭这个 Issues
***

简悦 2.0 包含了以下的一些新功能：

- [标注系统](http://ksria.com/simpread/docs/#标注)

- [稍后读 2.0](http://ksria.com/simpread/docs/#稍后读)

更多功能可以访问 https://simpread.pro/welcome/version_2.0.0.html

***

两个福利提示：

- 简悦 2.0 拥有了全新的 **[高级账户](https://simpread.pro/price.html)** 系统，目前正在特价中，价格即将上涨，如果对其高级功能感兴趣的话，也可以试试。

- Edge 也更新到 2.0 版本 👉  [microsoftedge.microsoft...](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc) 目前正在简悦内部搞一个抽奖活动，在 **选项页 → 消息中心** 查看规则细节，
