### ISSUE TITLE
无法下载插件

### ISSUE THREAD

**Issue by luxunL** [Kenshin/simpread#867]
提示XXXXXXXXXXXXXXX(一串码)获取失败，请稍后再试。但是隔了几天再试还是不行。

**Comment by Kenshin** [comment]
详细说明下。

1. 下载什么插件？
2. 如果能截图的话，请截图。
3. 在哪里下载？告诉我 URL

**Comment by luxunL** [comment]
所有插件都不能下载
https://simpread.ksria.cn/plugins/
在这里点击安装插件
![image](https://user-images.githubusercontent.com/55991650/89092434-62188600-d3e4-11ea-98a2-d858c4b661d2.png)
会跳转到这里
![image](https://user-images.githubusercontent.com/55991650/89092461-8a07e980-d3e4-11ea-801f-f32546a2f390.png)

**Comment by Kenshin** [comment]
告诉我你的系统以及 Chrome 和 简悦版本。
方便的话，能否停止到其它插件（ 虽然应该没关系，但以防万一）

***

另外，刚测试了下，我这边没问题，同时也没有其它人反馈，应该只是你的个例。

**Comment by luxunL** [comment]
win10 
chrome 版本 81.0.4044.138（正式版本） （64 位）
简悦 1.1.4.6025

停止其他插件后依然没有改变

**Comment by Kenshin** [comment]
导出配置文件后，重新安装 or 清除全部数据。

当出现错误时，按 `F12` 把后台报错信息给我看看。

**Comment by luxunL** [comment]
已经解决  删除插件 重新安装后可以正常下载插件。没有出现错误。感谢您的帮助！

**Comment by Kenshin** [comment]
@luxunL 

搞定就好。不过，可能是 Bug 只是比较隐形而已。

以后也可以试试 **选项页 → 插件管理 → 清除本地全部插件** 估计也有同样的效果。

因为很难调查它，我先关闭 Issues 了。  😃
