### ISSUE TITLE
知乎某个页面发送到 kindle 的时候显示保存文件失败（已解决）

### ISSUE THREAD

**Issue by luoyepiaoling** [Kenshin/simpread#87]

**Comment by Kenshin** [comment]
是无法跳转？还是发送失败？
最好详细描述，顺便把 url 告诉我。

**Comment by luoyepiaoling** [comment]
url：https://www.zhihu.com/question/27681852
访问https://simpread.herokuapp.com出现404错误

**Comment by Kenshin** [comment]
你访问 
https://sspai.com/post/40754 再试试。
另外确保 https://simpread.herokuapp.com 可以访问（或许需要科学上网），假设还不好使，我明天再看下。

**Comment by Kenshin** [comment]
今早刚刚试了试，我这边没有问题。请确认上条 comment 的内容。
![image](https://user-images.githubusercontent.com/81074/30254933-6a6cce3a-9664-11e7-8f8a-4088fd9f2178.png)

**Comment by luoyepiaoling** [comment]
https://simpread.herokuapp.com 网站访问出现问题。（已翻墙）

![Uploading 屏幕快照 2017-09-11 16.55.23.png…]()

**Comment by luoyepiaoling** [comment]
再次尝试了一下，可以正常推送了。怀疑可能是墙的问题。

**Comment by luoyepiaoling** [comment]
非常感谢，希望简阅越做越好！

**Comment by Kenshin** [comment]
https://simpread.herokuapp.com  访问成功后就是截图所示 😢  哈哈
okay 估计可能是墙抽风了，其实 heroku 偶尔也会不稳定。
搞定就好~ 我将关闭此 issues 。
