### ISSUE TITLE
请问保存到语雀的网页图片是离线的还是源图片链接引用？

### ISSUE THREAD

**Issue by loveshizuka** [Kenshin/simpread#874]
正在测试简悦保存到语雀的功能，无法确定图片是否为离线保存至语雀，特来咨询。

查看过简悦使用文档，没有关于”保存到语雀“的说明，只是提到保存为 Markdown。

测试中，在语雀文档“浏览”状态下查看已保存的网页剪辑中的图片，发现好像语雀只是对源图片进行代理，而没有将图片上传到它的存储。而在语雀文档”编辑“状态下查看图片代码，只是源图片的链接。所以，从简悦保存到语雀的网页图片，只是一个链接，并没有将图片离线到语雀存储吗？

如有可能，希望简悦将保存到语雀网页中的图片进行离线，这样剪辑的网页对知识归档才更加完整和有保障。感谢！

**Comment by Kenshin** [comment]
保存到语雀的图片应该自动转换为它的图床了，如

https://cdn.nlark.com/yuque/0/2020/png/353945/1596767421972-8a411fe9-2a34-4431-91a4-12ab435bf0e5.png

编辑状态下确实如你所说，所以我也不是 100% 确认这件事情。

***

我测试了下，发现个有意思的情况，如这篇文章 https://sspai.com/post/61932 保存到语雀后就出现上面的地址（看起来像是它自己的图床）

但是另外一篇测试文章的图片地址就是原链接...

所以，你如果有 Blog 之类的可以自己做个测试。

**Comment by loveshizuka** [comment]
搭建了个临时 wordpress，写好文章，上传图片，之后简悦保存至语雀。

查看”浏览“状态下的语雀文章网页代码，图片 src 使用源是类似图片代理的网址，之后 301 跳转到以 cdn.nlark.com 开头的图片地址。当删除 wordpress 媒体库中图片后，语雀文档中的图片确实仍可显示。但，，

以下是简悦剪辑到语雀中的文档图片地址 html 代码 :
`<img data-role="image" src="/api/filetransfer/images?url=https%3A%2F%2Fpict.example.com%2Fwp-content%2Fuploads%2F2020%2F08%2F1.jpg" data-raw-src="https://pict.example.com/wp-content/uploads/2020/08/1.jpg">`
代码中， 'src' 中为图片代理地址，'data-raw-src' 中为抓取图片源地址。

****

新建语雀文档，通过编辑界面**上传**图片。此时的图片地址 html 代码：
'<img data-role="image" src="https://cdn.nlark.com/yuque/0/2020/jpeg/2395805/1596791234321-b8657d15-b680-4c67-ad26-079988888ece.jpeg" data-raw-src="https://cdn.nlark.com/yuque/0/2020/jpeg/2395805/1596791234321-b8657d15-b680-4c67-ad26-079988888ece.jpeg">'
此时，'src' 和 'data-raw-src' 中的图片地址均为语雀图片源地址。

****

经过代码对比，个人得出的结论：
使用简悦保存到语雀的网页内容，其中的图片，语雀并未上传至它的图床进行离线保存，仅仅使用图片代理形式，通过 cdn 中转了源图片。
虽然在测试中删除源图片，语雀文档中的图片仍可访问，估计只是因为边缘 cdn 的缓存，缓存多久不得而知。假设一旦 cdn 中图片的缓存过期，当再次访问保存到语雀的文档时，此时 cdn 才将再次抓取 'data-raw-src' 地址中的源图片，可因为源图片已删除，语雀 cdn 抓取不到源图片，也就无法在文档中显示图片。

看来语雀现阶段不适合我用作资料收集整合，白瞎了10G的存储和还不错的撰写体验，有些小失望。只能老老实实用的回为知笔记。。

**Comment by Kenshin** [comment]
谢谢这么详尽的测试。

你也可以使用 Notion 作为你的资料收集整理 App 在简悦中可以将源图片转换为 Notion 图床的功能。

这个 Issues 暂时不关闭了，作为一个 Feature 存在吧。

**Comment by Kenshin** [comment]
![PicGo](https://user-images.githubusercontent.com/81074/182798678-f318f7b7-d637-4faa-acd4-5c1dd2f73710.png)

嗨，简悦增加了 **图床插件** 支持支持国内大多数的图床服务：七牛、腾讯云、阿里云、又拍云、Github、SM.MS、Imgur 图床等，并支持当前转换为图床后，可自动选择一个导出服务，包括：触发插件的动作、导出到本地、导出到生产力工具、Webhook、WebDAV。

详细说明👉https://github.com/Kenshin/simpread/discussions/4306


所以，我关闭此 Issues 了
