### ISSUE TITLE
希望增加“自动加载下一页”，或在阅读视图中保留“下一页”按钮。

### ISSUE THREAD

**Issue by nkh0472** [Kenshin/simpread#876]
我在阅读观察者网时遇到了这样的一个问题，以https://www.guancha.cn/daju/2020_08_07_560520.shtml为例：
原来的网页底部是这样的：
![image](https://user-images.githubusercontent.com/67589323/89722396-cad2b480-da1b-11ea-8e90-815aa9d13250.png)
但开启阅读模式之后：
![image](https://user-images.githubusercontent.com/67589323/89722402-e3db6580-da1b-11ea-9202-58ebc97c7ab4.png)
很多网页中，读到底部甚至都不知道文章内容还有下一页就直接关掉了。

所以或许可以提供以下几种解决方案：
1.保留网页原来的下一页按钮；
2.实现自动加载下一页或自动加载余下全文按钮。

**Comment by Kenshin** [comment]
嗨，谢谢反馈。

1. 简悦有翻页功能，但需要手动适配它（ 也就是说，目前无法类似阅读模式一样自动识别翻页
2. 自动加载的功能也一样（即，无法自动识别。

接下来会考虑加入自动翻页的功能，但仍旧无法自动识别多页面的情况，这也是我一直没加此功能的原因。

**Comment by vicentory** [comment]
http://cn.nikkei.com/industry/management-strategy/41940-2020-09-04-01-54-53.html，这个网站也是这样有多个页面，是否可以把这个自动加载下一页的功能研究一下，可以是自己输入下一页网站，或者是自主选择是否加载下一页，因为这个下一页网址链接也很简单，就是在当前网址后面增加几个符号就可以。http://cn.nikkei.com/industry/management-strategy/41940-2020-09-04-01-54-53.html?start=1

**Comment by Kenshin** [comment]
@vicentory  

自动下一页的功能，技术不是太难，难点是 **不同的翻页逻辑都不一样**，所以还是没有太想好如何自动识别 **下一页到底是哪一页** 这个事情。
