### ISSUE TITLE
与 Surfingkeys 快捷键冲突

### ISSUE THREAD

**Issue by warmerq** [Kenshin/simpread#88]
之前启用 SimpRead 阅读模式后, Surfingkeys 的快捷键依然有效. 这让我非常欣喜. 
后来似乎 SimpRead 升级后, 就失效了.

SurfingKeys 版本号: 0.9.7
SimpRead 版本号: 1.0.3
操作系统: Mac Sierra
Chrome 版本: 60.0.3112.113

想问一下, 看有没有解决办法.

**Comment by Kenshin** [comment]
感谢反馈~
简悦升级时并没有修改任何关于 `快捷键` 的功能，所以不清楚为何... 调查后再通知你。

**Comment by Kenshin** [comment]
![image](https://user-images.githubusercontent.com/81074/30257144-80b47a24-9675-11e7-9639-8abd2e4a9bd6.png)


我刚刚测试了下，至少绝大部分功能可以使用，建议你修改下 简悦 `聚焦模式 与 阅读模式` 的快捷键，再试试。

不能使用的功能：（仅仅是简单的测试）

>模拟 `鼠标点击` 类的操作。

原因：
- `阅读模式` 为了防止 CSS 污染，所以并没有在 `<body>` 而是在 `<html>` 节点下，所以基于判断 `<body>` 节点下的扩展在阅读模式下都不好用。

- `聚焦模式` 虽然节点在  `<body>` 下，但不清楚为什么不好使...

解决方案：
> 我发现这个扩展是国人开发的，我试着联络他，看看能否单独适配 `简悦`

**Comment by Kenshin** [comment]
给 Surfingkeys 提了个 [issues](https://github.com/brookhong/Surfingkeys/issues/478) 希望可以解决这个问题，这样的话，再有同类问题，我可以让他们转投 Surfingkeys

**Comment by Kenshin** [comment]
Surfingkeys 新版已经发布，修复了之前提出的问题，如下图：

![image](https://user-images.githubusercontent.com/81074/30790096-788a271e-a1dc-11e7-8bef-5d652e539e5f.png)

此 issues 将会关闭~

**Comment by CQUTWangHong** [comment]
为啥我现在两个插件都开启，结果用快捷键打不开简悦的聚焦模式和阅读模式，我两个插件的快捷键都是默认的。

环境：
SurfingKeys 版本号: 0.9.60
SimpRead 版本号: 1.1.4
操作系统: Mac catalina
Chrome 版本: 70.0.3538.102

**Comment by Kenshin** [comment]
@CQUTWangHong 

（估计）你需要在 Surfingkeys  取消对简悦的快捷键的 **监控**。
