### ISSUE TITLE
部分 网页的阅读模式下 导出离线 html 文件 没有扩展名

### ISSUE THREAD

**Issue by kuyagic** [Kenshin/simpread#880]
现象
在 [这个网页](https://chinadigitaltimes.net/chinese/2020/08/%E4%BD%95%E4%BC%9F%EF%BC%9A%E4%B8%AD%E5%9B%BD%E6%98%AF%E5%A6%82%E4%BD%95%E6%8E%A7%E5%88%B6%E4%BD%8F%E6%96%B0%E5%86%A0%E7%96%AB%E6%83%85%E7%9A%84%EF%BC%9F%EF%BC%88%E5%85%A8%E6%96%87%EF%BC%89/) 下使用阅读模式 然后导出离线html 后 没有扩展名

同时在建立这个issue之前我又去 [这个页面](https://bh.sb/post/55165/) 导出试了下 也是没有扩展名

扩展版本 `1.1.4.6025 `
安装的插件 `无`
安装源   `Chrome商店`

**Comment by loveshizuka** [comment]
我这测试了下，一切正常，都有 html 扩展名。可能是你系统环境的问题。

**Comment by Kenshin** [comment]
@kuyagic

确如 @loveshizuka 所说，我也没有遇到这个问题，估计是跟你装了其它扩展或 Chrome 设置有关。
你可以在隐身模式下（仅启用简悦）的情况下，试试。

**Comment by kuyagic** [comment]
下图是我在 隐私模式下 测试的结果 依然没有扩展名. 我系统是英文的 
chrome 版本Version 86.0.4209.3

![image](https://user-images.githubusercontent.com/1469330/90086557-477fce80-dd4d-11ea-9b9d-245f466f0678.png)

**Comment by loveshizuka** [comment]
难道是 chrome v86 版本和简悦的兼容问题？我的最新版也才 v84。。

**Comment by loveshizuka** [comment]
@kuyagic

用用看 Chromium 的 Edge ，内核也是 v84。已排除了扩展冲突，如果 Edge 下正常，应该就是 v86 和简悦的兼容问题了。

**Comment by kuyagic** [comment]
@Kenshin 
@loveshizuka 
使用了如图 配置的 edge 结果依旧

![image](https://user-images.githubusercontent.com/1469330/90090504-c4fc0c80-dd56-11ea-9ee4-e73ba5c044e3.png)

**Comment by Kenshin** [comment]
@kuyagic 
我测试了 Edge 版本 86.0.601.1 (官方内部版本) Dev (64 位) **没有遇到** 你说的情况...

你可以在 Edge 仅安装简悦且不修改任何简悦配置的情况下，试试？

**Comment by kuyagic** [comment]
@Kenshin 尝试了卸载扩展后重新安装  然后 直接不做任何配置 然后  保存离线html
 依旧没有扩展名. 好神奇(

**Comment by loveshizuka** [comment]
这么看来，我觉得有两种可能。一是外部应用导致，不排除，但可能性不大。二是简悦不能很好的支持英文系统，算是一个 bug 吧。

而且我离线下来的 html 文件名还是以中文文章标题命名的，你这只是类似 uuid 的文件名，是有问题。

可以试试将 Chrome 设置中的”语言“加一个”中文“排到第二看看。

还不行的话，只能等老大解决 :)

**Comment by kuyagic** [comment]
@loveshizuka  这是我 Edge 的 Language 顺序
![image](https://user-images.githubusercontent.com/1469330/90091877-135eda80-dd5a-11ea-827b-339b4f175732.png)

**Comment by loveshizuka** [comment]
@kuyagic

我试着在虚机中装了个英文 win10，英文的 chrome v84，简悦离线 html 功能正常，没出现你的这种情况。搞不懂了。。

**Comment by kuyagic** [comment]
@loveshizuka 我也不懂了 我虚拟机 啥都没 全新edge + 扩展 就没问题 我估计可能还是我装了啥下载插件的关系 但是 隐私模式又正常 就很迷
![image](https://user-images.githubusercontent.com/1469330/90093168-7b62f000-dd5d-11ea-95ac-f7ed93a78881.png)

**Comment by kuyagic** [comment]
我知道问题了 是一个叫 Ant Download Manager 插件导致的文件名是GUID 禁用就可以了. @Kenshin @loveshizuka

**Comment by Kenshin** [comment]
@kuyagic 

搞定就好。`Ant Download Manager ` 猜测它控制的是 `Download API` 所以在隐身模式下也不一样。

@loveshizuka 
谢谢帮忙测试 🙏

***

更正一点  😀 

> 简悦不能很好的支持英文系统

这个不存在的，因为都是 UTF-8 编码而已，只要中文能正常显示就不会是这个问题。
