### ISSUE TITLE
印象笔记 导出失败

### ISSUE THREAD

**Issue by eromoe** [Kenshin/simpread#882]
Hello,

终于找到一个功能最全的剪藏工具了，这个真的太厉害了！

在授权印象笔记的时候多次授权失败， 重新授权 转跳到印象笔记页面会显示重新授权，重复了几次后授权成功。
但是在剪藏
https://www.cnblogs.com/RyanXing/p/9469338.html
的时候又出现了问题，无法导出到印象笔记，请问如何解决？

PS: 其实我更希望有一键剪藏功能，现在要多点几下，如果有剪藏版的插件就太好了

**Comment by Kenshin** [comment]
谢谢反馈，你说的场景跟简悦阅读模式不同，所以不能实现它。

当然，你的诉求我会考虑。

另外，关于授权的问题，应该不会出现这种情况，否则很多人都会反馈给我了。

我明天试试，你也可以通过选项页来重新授权试试。

**Comment by Kenshin** [comment]
我关联了这个问题，所以关闭当前这个 Issues 了。
