### ISSUE TITLE
是否可以增加保存到 wolai 的功能？

### ISSUE THREAD

**Issue by 0xAC7** [Kenshin/simpread#889]
很喜欢类似 notion 的笔记软件，但是奈何要科学上网。
最近发现了 wolai 这款软件，感觉挺好的。
网址：https://www.wolai.com/
不知道可不可以增加保存到 wolai 的功能。

**Comment by Kenshin** [comment]
我个人对这种 Copy 类的网站没什么好感度。
纯技术类的角度说，需要 API 的支持。

我先关闭这个 Issues 了，等它有 API 且你还再用的话，请再告诉我。😃

**Comment by 0xAC7** [comment]
好的，了解了。

**Comment by Kenshin** [comment]
谢谢理解。 😃
