### ISSUE TITLE
请求适配纽约时报中文网

### ISSUE THREAD

**Issue by yesorno** [Kenshin/simpread#89]
https://cn.nytimes.com/
纽约时报本身的阅读体验较为糟糕。
感谢作者。

**Comment by Kenshin** [comment]
感谢~

其实这个站已经适配了，但由于适配列表在 `七牛云` 里面，所以这个不存在的站有可能会连累 `适配列表` 被七牛下线...

关联问题 https://github.com/Kenshin/simpread/issues/65

解决办法：
`1.1.0` 会上线自定义适配列表功能，到时你可以添加自己信任源的列表到 `简悦`

**Comment by yesorno** [comment]
期待。谢谢。

**Comment by Kenshin** [comment]
😁  谢谢理解~

还有一个办法，如果你可以修改 host 的话，我可以提供这些站的适配列表，这样这些不存在的网站就能访问了。

唯一的问题是：无法通过远程更新。

所以，如果不是很急的话，还是等 `1.1.0` 上线。 😈  😏

**Comment by yesorno** [comment]
我还是等1.1.0上线吧。这样简单一些。

Kenshin Wang <notifications@github.com>于2017年9月12日周二 下午4:00写道：
