### ISSUE TITLE
知乎专栏（貌似很多网站都这样）gif，视频显示不正常

### ISSUE THREAD

**Issue by xiajunwen1007** [Kenshin/simpread#894]
### 设备信息：
操作系统：win10
浏览器：edge最新版
插件版本：1.1.4
其余信息：已关闭浏览器插件和简悦插件
### 问题描述：
  非常喜欢大大的插件，现在基本上看东西都会直接用简悦生成阅读模式。无意中发现gif和视频都无法在阅读模式显示，比较影响阅读，不知道大大有没有意向解决。看过之前的issues发现知乎gif显示问题已经解决，但是实测发现貌似又不行了。
### 问题复现
  https://zhuanlan.zhihu.com/p/127874326 这篇知乎专栏里面有gif和视频，生成阅读模式后都无法查看。
### 截图
  gif无法显示：
![image](https://user-images.githubusercontent.com/49160447/90404858-8ad39780-e0d5-11ea-9dc4-24be0841909b.png)

**Comment by Kenshin** [comment]
嗨，谢谢反馈。
之前说的 **gif 问题解决了** 指的是生成后 gif 会有多张图片的问题，而非你提的问题。

我简单的看了下，可以解决，只是暂时以插件的形式来发布，解决后会通知你的。

**Comment by binsee** [comment]
使用如下适配规则可解决：

```json
{
    "name"    : "zhuanlan.zhihu.com",
    "url"     : "https://zhuanlan.zhihu.com/p/",
    "title"   : "<h1 class='Post-Title'>",
    "desc"    : "",
    "include" : "[[[(function(){$('.ztext-gif').each(function(){if(this.src.match(/.jpg$/))this.src=this.src.replace(/.jpg$/,'.gif')});return $('.Post-RichText');}())]]]",
    "exclude" : [
        ""
    ]
}
```

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues

**Comment by Kenshin** [comment]
嗨，我这几天整理了知乎相关的全部问题，如果经常使用知乎的话，建议看下。

修复/优化的内容包括：gif 动画 / 知乎公式 / 问答页的描述 / 图片重复 / 惰性加载图片等。

### 如何配置

1. https://github.com/Kenshin/simpread/discussions/2870

2. 安装此插件 https://github.com/Kenshin/simpread/issues/2860

3. 更多细节请看 https://github.com/Kenshin/simpread/discussions/2869

**Comment by Kenshin** [comment]
![zhihu@cover](https://github.com/Kenshin/simpread/assets/81074/d100f3c2-c70d-44f1-9abb-6a3221a83ef6)

嗨，[知乎辅助增强插件](https://github.com/Kenshin/simpread/discussions/2861) **升级到 2.0.0**，基本上彻底解决了你提到的这个问题。

## 2.0.0 功能说明

- `Add` [检查和添加 `zhihu.com` 到 延迟加载列表](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-3341808)

- `Add` [优化知乎问答页](https://github.com/Kenshin/simpread/discussions/2861#discussioncomment-6390836)，更适合导出

- `Optimize` 更新以及去掉了一些过时（错误的）链接和描述

- `Fix` 导出含有公式的页面为 HTML 无法显示公式的错误

- `Fix` 在稍后读无法查看知乎公式的错误

- `Fix` 导出含有公式的页面为 PDF 无法显示公式的错误（需使用 [PDF  高级打印方案](https://github.com/Kenshin/simpread/discussions/3887)）

## 截图

> 包括：导入到 Obsidian 、PDF 、在稍后读查看知乎公式、导出 HTML 等。

![pika-1688973561715-1x](https://github.com/Kenshin/simpread/assets/81074/947a2680-16a4-471c-ba1e-7519f510abb0)

![pika-1688973547744-1x](https://github.com/Kenshin/simpread/assets/81074/b2ebac73-d18f-434d-8a47-61332da61dbe)

![pika-1688973529299-1x](https://github.com/Kenshin/simpread/assets/81074/33e1ce95-74fe-445f-8c1c-c2ad28123ba2)

![pika-1688973515027-1x](https://github.com/Kenshin/simpread/assets/81074/6a04e49b-ef3f-4371-8559-31c4e1ec37e5)

![pika-1688973508763-1x](https://github.com/Kenshin/simpread/assets/81074/f26d370b-b9ba-4572-b7a5-03f755a84cf1)

## 关联

https://github.com/Kenshin/simpread/issues/2860

## 安装与升级

- 没有【使用同步助手 · 自动同步】的话，可通过[此链接](https://simpread.ksria.cn/plugins/details/IfgbkkZCOZ) 安装。

- 已经【使用同步助手 · 自动同步】的话，请使用 [插件管理器](https://www.yuque.com/kenshin/simpread/fcw60u#ymS1C) 安装。
