### ISSUE TITLE
选项页显示错误的未读消息数量

### ISSUE THREAD

**Issue by binsee** [Kenshin/simpread#899]
- 操作系统 **Win10 x64**

- 浏览器版本 **Chrome 84.0.4147.125**

- 简悦版本 **2.0.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html>

**问题描述**

本地消息中心内所有消息都已经已读，但仍然显示`3`条未读。

![image](https://user-images.githubusercontent.com/5285894/90676590-d7ae9e00-e28e-11ea-88fe-b9f6e56e33c9.png)

查看项目源码后发现问题出在云端消息数据错误`（notice数量比最大id要小）`。

### 关键代码段：

- 判断未读消息数量

https://github.com/Kenshin/simpread/blob/48eff3cd99b7a8a2e8b82c928086bd64dab9c319/src/options/options.js#L390-L406

- 更新本地的消息缓存

https://github.com/Kenshin/simpread/blob/48eff3cd99b7a8a2e8b82c928086bd64dab9c319/src/module/notice.jsx#L78-L82

- 插件内配置的云端消息服务url

https://github.com/Kenshin/simpread/blob/48eff3cd99b7a8a2e8b82c928086bd64dab9c319/src/service/storage.js#L464-L467

发现已安装插件**(chrome商店版)**和源码用的地址不一样

```js
//当前chrome商店版插件内如下
  return {
    latest: "http://sr.ksria.cn/notice/latest",
    message: "http://sr.ksria.cn/notice/message.json"
  }
```

### 当前情况

当前本地配置记录如下:

```json
"notice": {
  "latest": 18,
  "read": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 24, 21, 23]
},
// read成员数为21
```

云端返回数据：
URL | 返回数据
----|----
https://static.simp.red/notice/latest | **源码内置** 返回 `23` 
http://sr.ksria.cn/notice/latest  | **商店插件** 返回 `24`  
https://static.simp.red/notice  | **源码内置** 返回数组成员18个 
http://sr.ksria.cn/notice/message.json |  **商店插件** 返回数组成员18个

当前返回消息id序列为： `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 21, 23]`

### 逻辑验证

https://github.com/Kenshin/simpread/blob/48eff3cd99b7a8a2e8b82c928086bd64dab9c319/src/options/options.js#L395-L398

1. 在 `L395` ，`storage.notice.latest=18` 比云端 `latest=24` 小
2. 因此显示未读消息数量为 `24 - 21=3`

即当前截图看到的

![image](https://user-images.githubusercontent.com/5285894/90676590-d7ae9e00-e28e-11ea-88fe-b9f6e56e33c9.png)

### 结论

问题最终还是在于云端的message.json记录中，撤销了几条消息。
而代码中是以云端的消息数量与`latest`一致为前提的，因此出现了逻辑bug，导致此次问题。

**Comment by Kenshin** [comment]
嗨，谢谢帮我 Debug 清楚了，而且很耐心的贴出了 Debug 全过程，你不休息吗？  😅 
不过，这个问题暂时只能下个版本修复了。

当初确实没有考虑到删除 message.json 的业务流程，所以才出现了这个错误。

关于代码不一致的是因为我还没有提交到 Github repo 而已。

以 http://sr.ksria.cn/notice/latest 为准。

**Comment by binsee** [comment]
夜猫子的熬夜日常（想了想发际线😬）


另外有一个问题，保存文章的时候，文章标题是文件名，但不会在markdown开头以一级标题体现。如果保存后，修改了文件名/文章标题，会丢失原始文章标题，因此有的时候我会手动在前边加一级标题。
我比较希望能加上一级标题的，如果有必要我另外开个issue。

**Comment by Kenshin** [comment]
emmm 建议开个 Issues 
抱歉，今天有点忙，回复晚了。
因为首发，所以一下子多了一堆高级账户的用户，各种提问，忙的有点抽筋。 😅

**Comment by binsee** [comment]
不必抱歉，issue本来就不应该是即时回复的。我去另外开个issue

**Comment by Kenshin** [comment]
嗨，我关闭这个 Issues 了~

PS：没想到这个是你提的。 😄
