### ISSUE TITLE
可以不显示右下角的按钮吗？

### ISSUE THREAD

**Issue by adeweb** [Kenshin/simpread#9]
![image](https://user-images.githubusercontent.com/6858999/27111768-f78854b2-50e4-11e7-8cda-d512bf3841f9.png)
真正的无干扰阅读状态下，右下角的大红色按钮显得特别耀眼，建议可以配置鼠标经过才显示。(图中的按钮)

**Comment by Kenshin** [comment]
下个版本可以加个开关，但目前反映这个问题的还没有其他人。 👍

**Comment by adeweb** [comment]
@Kenshin 好滴。可能是我强迫症。:)

**Comment by Kenshin** [comment]
版本 `1.0.1` 已发布，关闭此 `issues`，
解决办法：可以将此 `控制栏` 隐藏。
更新日志，请看 [这里](http://ksria.com/simpread/changelog.html#1.0.1)
