### ISSUE TITLE
新浪科技的某些页面使用阅读模式后无法解析

### ISSUE THREAD

**Issue by Ac-heron** [Kenshin/simpread#90]
http://tech.sina.com.cn/mobile/n/n/2017-09-13/doc-ifykusey9506991.shtml

**Comment by Kenshin** [comment]
这是正常的，因为 sina 只适配了如下几个站：
![image](https://user-images.githubusercontent.com/81074/30355750-ebeab5e8-97fa-11e7-8174-d1e4125a1746.png)

但不应该提示这个信息，这点在下个版本会改善。（无法适配后，不停留在下面这个界面，改为以 notify 提示），因为下图这个界面有些误导。
![image](https://user-images.githubusercontent.com/81074/30355787-182f3a84-97fb-11e7-8de0-1e544c3debac.png)

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。

现在的做法

> 匹配失败后，自动退出阅读模式，并启动临时阅读模式，可继续生成阅读模式的页面。

并增加了  
> `匹配阅读模式失败后启动 临时阅读模式` 的选项，详细请看 
http://ksria.com/simpread/welcome/version_1.0.4.html#ohter-update
