### ISSUE TITLE
更新标题有些小问题

### ISSUE THREAD

**Issue by SeaZhang** [Kenshin/simpread#901]
![image](https://user-images.githubusercontent.com/2841360/90705814-625ebf80-e2c6-11ea-9e97-8c3093dd52db.png)

**Comment by Kenshin** [comment]
谢谢反馈。

不清楚你是从哪个版本更新的，我测试过应该是没问题的，可能是个隐性 Bug 我再留意留意，先留着这个 Issues

**Comment by SeaZhang** [comment]
之前版本没太注意，今天打开电脑，浏览器这块弹出自动更新到新版本的提示看到的。

**Comment by Kenshin** [comment]
似乎没有人再提这个问题，我先关闭这个 Issues 了。
有问题我再重开。
