### ISSUE TITLE
Edge及账户相关问题

### ISSUE THREAD

**Issue by TMily** [Kenshin/simpread#902]
- Edge 商店尚未发布2.0版，是在审核中？

- 目前Edge可以安装Chrome商店的2.0版扩展，但是设置页面只显示菜单栏不显示内容无法操作，Edge版本：Version 86.0.613.0 (Official build) canary (64-bit)

![image](https://user-images.githubusercontent.com/3784599/90708037-78bb4a00-e2cb-11ea-87bb-c75916069dd4.png)

- 关于账户的登录与退出需要更详细一些的说明，现有的说明只有绑定激活码和退出账户，但是我没在设置页面找到退出按钮，是需要先绑定高级账户？其次退出后如何登录呢，我记得激活码绑定到账户后就失效了，那么如何在不同的设备/浏览器间迁移账户呢

- 此外最新版扩展设置页面账户中邮件地址项似乎没有适配GMail的加号语法
![image](https://user-images.githubusercontent.com/3784599/90708327-1282f700-e2cc-11ea-9a38-1ca6ac124d10.png)

**Comment by Kenshin** [comment]
已解决。
