### ISSUE TITLE
简繁转换

### ISSUE THREAD

**Issue by RoyLi-Pvt** [Kenshin/simpread#903]
有没有可能添加简繁转换功能呢？
现在Chrome有个扩展叫新同文堂可以进行简繁转换但是启用简阅会导致转换失效，有没有可能内置简繁转换或者与之兼容？
https://chrome.google.com/webstore/detail/new-tong-wen-tang/ldmgbgaoglmaiblpnphffibpbfchjaeg

**Comment by Kenshin** [comment]
谢谢建议，会使用插件来解决，解决后我会通知你的。

**Comment by Kenshin** [comment]
嗨，我制作了 [简繁体切换](https://github.com/Kenshin/simpread/discussions/2517) 这个插件，你可以通过安装此插件来解决。

安装地址 https://simpread.ksria.cn/plugins/details/0sZZtfBYyU
使用方法 https://github.com/Kenshin/simpread/discussions/2517

所以，我关闭这个 issues 了。

**Comment by RoyLi-Pvt** [comment]
仔细测试了下发现转换不全
转换前:在被心神不寧狀態極差的小胖子連坑四把後
转换后:在被心神不寧状態极差的小胖子连坑四把后
预期的结果:在被心神不宁状态极差的小胖子连坑四把后
