### ISSUE TITLE
无法激活高级会员的解决办法

### ISSUE THREAD

**Issue by crazyacking** [Kenshin/simpread#906]
刚才升级了2.0，我购买了高级会员，但在激活时报错：后台服务器出现了问题，点击重试。
![image](https://user-images.githubusercontent.com/11402371/90710280-9dfe8700-e2d0-11ea-9633-44312244fc92.png)

**Comment by Kenshin** [comment]
请再重新试试。服务器在国内，应该没问题的。
可能是使用的人比较多... 这几天是首发，所以人数会激增很多。

**Comment by crazyacking** [comment]
> 请再重新试试。服务器在国内，应该没问题的。
> 可能是使用的人比较多... 这几天是首发，所以人数会激增很多。

目前还是不行，后端服务太弱鸡了==，建议提升高可用性啊

**Comment by Kenshin** [comment]
除了你没人反馈这个问题...
稍后再试试。

**Comment by LyndonDing** [comment]
@Kenshin @crazyacking 我改了下这，解决了，之前是”点击时“ 现在如截图所示
![image](https://user-images.githubusercontent.com/15058452/90727078-4a526480-e2f5-11ea-8cf1-0044bdfc0acf.png)

**Comment by crazyacking** [comment]
@LyndonDing 赞，确实是这个问题，更改后能够激活成功了，感谢！ cc @Kenshin 可以关闭issue了

**Comment by Kenshin** [comment]
okay 各位，已关闭。
