### ISSUE TITLE
购买了 高级账户，但导入配置后，高级账户失效，重新绑定显示授权码已使用

### ISSUE THREAD

**Issue by o-ut-man** [Kenshin/simpread#907]

**Comment by Kenshin** [comment]
1. 购买后请重启浏览器，细节 https://github.com/Kenshin/simpread/issues/908

2. 完成上步后，再试试导入配置

**Comment by o-ut-man** [comment]
已按照说明操作（清除所有配置-重启-导入），还是不行


| |
z
|
|
zhengzhouxun@yeah.net
|
签名由网易邮箱大师定制
在2020年8月20日 12:01，Kenshin Wang<notifications@github.com> 写道：

购买后请重启浏览器，细节 #908

完成上步后，再试试导入配置

**Comment by Kenshin** [comment]
你给我发邮件（ kenshin####ksria.com ），然后邮件包含 uid 与 license 我来看下。

**Comment by Holly-White** [comment]
我的也是这样。今天发邮件找回uid后，重新导入后，uid是之前的但是高级帐户还是失效状态。

**Comment by Kenshin** [comment]
@Holly-White 

> 今天发邮件找回uid后

我给你发过邮件吗？现在不用发邮件的方式找回 UID 了，使用下面的方式找回：
【简悦 · 高级账户自助找回平台】 地址 https://simpread.pro/reset （内含使用方法）

请留意：因为 License 与 UID 为私密信息，但平台为开放平台，虽然 License 与 UID 仅你自己知道，但为了确保安全，一共只能 最多找回三次

**找回后，导入正确 UID 的配置文件后，通过 选项页 → 账户 → 恢复购买 来恢复，而非其它方式**。

请重新确认下。

**Comment by Kenshin** [comment]
@o-ut-man 

抱歉，前几天确实太忙了，有些 Issues 没有跟踪，请问现在可以了吗？
