### ISSUE TITLE
浮动工具栏动画效果优化

### ISSUE THREAD

**Issue by AriaLyy** [Kenshin/simpread#909]
这东西的出现动画看起来太难受了，能否增加一个关闭动画的功能，😂
![image](https://user-images.githubusercontent.com/10437293/90712716-39462b00-e2d6-11ea-8a44-847e4ca35fb7.png)

**Comment by Kenshin** [comment]
不需要动画？
暂时没提供，只能下个版本考虑。

**Comment by AriaLyy** [comment]
是的，这个动画看起来很难受..

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
