### ISSUE TITLE
设置页面最下面的两个按钮总是不能完整显示

### ISSUE THREAD

**Issue by jincheng555** [Kenshin/simpread#91]
<img width="1045" alt="wx20170913-102109 2x" src="https://user-images.githubusercontent.com/6647675/30356767-784aba8e-986d-11e7-95f0-242974606001.png">

**Comment by Kenshin** [comment]
额，估计是分辨率太小导致... 没太关于小分辨率的情况 😢 下个版本改善~
话说，你是什么分辨率？

**Comment by jincheng555** [comment]
苹果13寸的MBP
<img width="668" alt="wx20170913-110651 2x" src="https://user-images.githubusercontent.com/6647675/30357884-b9f94be8-9873-11e7-98e4-ecd2204177ce.png">

**Comment by Kenshin** [comment]
okay~
下个版本会加入 `折叠 UI`功能 以及 `分辨率` 支持~

**Comment by jincheng555** [comment]
这个弹出窗口判断一下当前屏幕的尺寸就行，自适应一下~

**Comment by Kenshin** [comment]
久等了...
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，修复此问题，此 issues 将会关闭。
