### ISSUE TITLE
[Feature Request]增加常用按钮

### ISSUE THREAD

**Issue by derekxia1988** [Kenshin/simpread#911]
一个小的建议，能不能增加选项让用户添加常用按钮到阅读模式主界面上，比如我如果需要保存文章则需要打开菜单然后将标签页切换到动作然后再去查找，感觉有点麻烦:joy:

**Comment by Kenshin** [comment]
可以试试 https://github.com/Kenshin/simpread/issues/891 和 https://github.com/Kenshin/simpread/issues/892

这两个插件，基本上满足你的需求了。

没异议的话，关闭这个 Issues

**Comment by derekxia1988** [comment]
好像是可以哦，我试试
