### ISSUE TITLE
我已经购买并激活会员了，但是还是无法使用合辑和马克笔标注等功能

### ISSUE THREAD

**Issue by ottopan** [Kenshin/simpread#918]
- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 
![image](https://user-images.githubusercontent.com/18224971/90753412-2732af80-e30b-11ea-9479-28367d55d4af.png)
![image](https://user-images.githubusercontent.com/18224971/90753224-e5a20480-e30a-11ea-9f4b-79e816fabaa9.png)
![image](https://user-images.githubusercontent.com/18224971/90753290-fd798880-e30a-11ea-8625-0061f1441d52.png)

**Comment by Kenshin** [comment]
请按照 https://github.com/Kenshin/simpread/issues/908 给出的解决方式再试试。

搞定后，请关闭这个 Issues
