### ISSUE TITLE
快捷添加稍后读的建议

### ISSUE THREAD

**Issue by lurui45** [Kenshin/simpread#919]
看到作者推出2.0后，就付费购买了。
使用过程中有些问题，具体如下：
1. 稍后读的进入路径是否太繁琐，我第一次进稍后读找了半天，需要 右键图标->点击选项->点击稍后读 才能进入，是否有更快捷的办法。

2. 部分页面阅读模式适配出现问题，但是在稍后读页面显示又挺正常。

![snipaste_20200820_1747](https://user-images.githubusercontent.com/9017003/90755208-7d085700-e30d-11ea-8226-01c30fbbe7ac.PNG)

![snipaste_20200820_1749](https://user-images.githubusercontent.com/9017003/90755226-80034780-e30d-11ea-99bc-f9174ff56221.PNG)

3. 如何使阅读模式下文章中的图片靠左对齐？

**Comment by Kenshin** [comment]
谢谢付费支持。

> 入口的问题

会考虑你的建议，但确实没什么好想法。

问题的页面最好给我个 URL

> 图片靠左对齐

目前没有这个选项，为什么这么设计？居中不好看吗？

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，详细 [请看这里](http://ksria.com/simpread/docs/#/%E7%A8%8D%E5%90%8E%E8%AF%BB?id=%e5%a4%9a%e7%a7%8d%e7%9b%b4%e8%be%be%e5%85%a5%e5%8f%a3)

![image](https://user-images.githubusercontent.com/81074/100059437-0d52bc80-2e66-11eb-8ddd-a81644e4e4f3.png)

![image](https://user-images.githubusercontent.com/81074/100059460-15126100-2e66-11eb-91a3-5273e69b6cb6.png)


***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
