### ISSUE TITLE
发现一个网站某些标题颜色与背景色相同

### ISSUE THREAD

**Issue by CrazyGrin** [Kenshin/simpread#92]
>简阅版本 : 1.0.3
>chrome版本 : 60.0.3112.90
>网页地址 : [http://www.cnblogs.com/dowinning/archive/2012/04/19/json-jsonp-jquery.html](url)
>系统 : win10

颜色模式:
丁子色 白练 娟鼠 ,其他模式显示正常

**Comment by Kenshin** [comment]
感谢反馈，我明天会看下。
一般情况下类似 cnblogs 这种 UGC 的网站，用户在录入内容的时候，会带有一些背景色等的情况，如果遇到这种情况一般可以使用 `自定义样式解决`

关联问题 https://github.com/Kenshin/simpread/issues/69
自定义样式 https://github.com/Kenshin/simpread/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by CrazyGrin** [comment]
感谢 , 我没有认真的看之前的issue
那我就把这个issue关闭了: )

**Comment by Kenshin** [comment]
没关系的，毕竟 issues 已经关闭了～
搞定就好。
