### ISSUE TITLE
代码行显示有问题

### ISSUE THREAD

**Issue by Bogdanxin** [Kenshin/simpread#922]
![image](https://user-images.githubusercontent.com/56074524/90778844-b651be80-e32f-11ea-9c7d-15c09778de34.png)
如上图，代码行总是看起来很别扭，每一行的行标和字符铁的太近了，想知道该怎么解决？
原来的样式如下：
![image](https://user-images.githubusercontent.com/56074524/90779035-f31db580-e32f-11ea-8c3e-254b32e8b8a0.png)
这是来自微信公众号的文章，不知道能否解决

**Comment by Kenshin** [comment]
装代码高亮插件试试，是不是跟另外一个 Issues 重复了？

重复的话，关闭这个吧
