### ISSUE TITLE
关于代码增强插件问题

### ISSUE THREAD

**Issue by Bogdanxin** [Kenshin/simpread#923]
今天尝试安装一个增强插件，但是安装好几次总是安装不上（过程如下图），请问这是个什么原因呢
![dPGu3uB8KQ](https://user-images.githubusercontent.com/56074524/90780815-08471400-e331-11ea-9f02-de1601c553a3.gif)

**Comment by Kenshin** [comment]
什么提示？
看看这里设置是否正确？

![](https://user-images.githubusercontent.com/81074/90757097-c0fc5b80-e30f-11ea-9c02-4f79634a2bf7.png)

**Comment by Bogdanxin** [comment]
![image](https://user-images.githubusercontent.com/56074524/90782754-d2565f80-e331-11ea-8445-704982dbd8dd.png)
我看了，确实是“所有网站上”

**Comment by Kenshin** [comment]
安装不了是什么提示？

**Comment by Bogdanxin** [comment]
刚才发的gif图，什么也没有提示，就是没有安装上😂

**Comment by Kenshin** [comment]
选项页 → 插件管理 → 清除全部插件

试试

**Comment by Bogdanxin** [comment]
ok了谢谢
