### ISSUE TITLE
标注侧栏颜色文字需要调整

### ISSUE THREAD

**Issue by ottopan** [Kenshin/simpread#924]
![image](https://user-images.githubusercontent.com/18224971/90837157-c09da800-e383-11ea-9167-b2dd894ad799.png)
浅色＋白字，可读性极差，需要考虑文字对比度，考虑到色弱色盲用户的使用

**Comment by Kenshin** [comment]
谢谢反馈，下个版本解决这个问题。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
