### ISSUE TITLE
Microsoft Edge 商店大概什么时间可以更新到2.0？

### ISSUE THREAD

**Issue by kawnnor** [Kenshin/simpread#925]
Microsoft Edge 商店还是1.1.4版本，有更新计划吗？

**Comment by Kenshin** [comment]
下周不忙的时候就会上架。
建议你先使用 Chrome 版，上架后我会在这里通知你。

**Comment by Kenshin** [comment]
嗨，Edge 已更新到 2.0 我将关闭这个 Issues  😃
