### ISSUE TITLE
消息中心显示2条消息未读，但是消息列表全部显示已读

### ISSUE THREAD

**Issue by linmii** [Kenshin/simpread#926]
问题如标题描述。
另外提个建议：消息中心的消息能将最新的消息放到最上面吗？按消息时间从上到下由近到远排列

![image](https://user-images.githubusercontent.com/17309471/90843003-31988c00-e393-11ea-8742-2cbac0b85081.png)
![image](https://user-images.githubusercontent.com/17309471/90843044-4a08a680-e393-11ea-9557-55553af0a905.png)
![image](https://user-images.githubusercontent.com/17309471/90843063-542aa500-e393-11ea-8dd6-bbcf14ba70e4.png)

**Comment by Kenshin** [comment]
是的，这是个 Bug 关联问题 https://github.com/Kenshin/simpread/issues/899

**Comment by Kenshin** [comment]
这样的话，我先关闭这个 Issues 了，修复后我会通知你的。
