### ISSUE TITLE
需求：根据标签整合浏览和导出摘抄的句子或图片

### ISSUE THREAD

**Issue by ottopan** [Kenshin/simpread#928]
![image](https://user-images.githubusercontent.com/18224971/90844732-2ba4aa00-e397-11ea-9a82-988b4bde9454.png)
如图所示，我想把多篇包含的例子的书摘汇集导出，完成进步的信息整合，文章的界限就可以弱化了，变成了同一类的信息整合

**Comment by Kenshin** [comment]
没问题的话，我关闭这个 Issues
有需要，请再重开。
