### ISSUE TITLE
提示密钥已被使用，应如何解决？

### ISSUE THREAD

**Issue by zuzu16** [Kenshin/simpread#929]
少数派上的订单号: SSPAI0200820000000338

绑定时，提示此密钥已被使用，点击重新确诊或者联系管理员

应如何解决？谢谢！！！

**Comment by Kenshin** [comment]
首次绑定吗？还是已绑定过了？

**Comment by zuzu16** [comment]
我记得我昨天绑定了，今天开机后，提示简悦更新，然后发现没有绑定，我又重新绑定，就出现这样的提示了。


| |
Zhu Jianfang
|
|
zhujf@yeah.net
|
签名由网易邮箱大师定制
在2020年8月21日 11:00，Kenshin Wang<notifications@github.com> 写道：

首次绑定吗？还是已绑定过了？

**Comment by Kenshin** [comment]
> 我记得我昨天绑定了，今天开机后，提示简悦更新

不应该，你昨天绑定的时候，就是 2.0 才对，否则无法绑定。

可以找回的，请放心。不过，最好确认上面我说的内容。 😀

**Comment by zuzu16** [comment]
我昨天绑定后，再去开通同步功能，但是同步是否成功没有查验。
还有我通过支付宝也购买过一次，少数派购买一次，目前使用的是少数派的注册码。

那就是绑定过，但是目前这台电脑是非绑定状态！

**Comment by Kenshin** [comment]
你的意思是

1. 昨天在原来的电脑绑定过。

2. 今天打算在新的电脑重新绑定？

是这个意思？

**Comment by zuzu16** [comment]
还是这台电脑。昨天绑定过，今天来简悦出现升级提示信息，处于未绑定状况，我重新绑定， 出现的那个提示。

我又重新在少数派上购买了一个，目前已经绑定好了。麻烦你了！

**Comment by Kenshin** [comment]
> 还是这台电脑。昨天绑定过，今天来简悦出现升级提示信息，处于未绑定状况，我重新绑定， 出现的那个提示。

额，你把出问题的 sn 发邮件到 kenshin###ksria.com 附上这个 sn 的购买凭证，我帮你找回。

**Comment by zuzu16** [comment]
kenshin###ksria.com???


这是邮箱吗？


| |
Zhu Jianfang
|
|
zhujf@yeah.net
|
签名由网易邮箱大师定制
在2020年8月21日 11:18，Kenshin Wang<notifications@github.com> 写道：

还是这台电脑。昨天绑定过，今天来简悦出现升级提示信息，处于未绑定状况，我重新绑定， 出现的那个提示。

额，你把出问题的 sn 发邮件到 kenshin###ksria.com 附上这个 sn 的购买凭证，我帮你找回。

**Comment by Kenshin** [comment]
kenshin###ksria.com 
### 替换为 @

***

我不想我的邮箱外泄，这是很正常的处理方法...

**Comment by Kenshin** [comment]
我给你回复邮件了，没问题的话，请关闭这个 Issues 吧  😀
