### ISSUE TITLE
oschina排版错误（显示不全）

### ISSUE THREAD

**Issue by dreacter** [Kenshin/simpread#93]
https://www.oschina.net/question/2272683_245529
oschina的问答区只能显示提问，不能显示回答。

**Comment by Kenshin** [comment]
额，这是因为还未适配论坛类页面造成的...

![image](https://user-images.githubusercontent.com/81074/30373805-2ff13c1a-9848-11e7-888c-69ca96a335c2.png)

适配后，我会通知你~

**Comment by Kenshin** [comment]
刚更新了一批新站，但未包含此 url，原因：

- 这个站的 html 与绝大多数论坛类页面的结构差别太大，暂时没办法适配。

等到后续改善。

**Comment by dreacter** [comment]
谢谢回复。
同时发现了一个可能有bug的网页。
http://blog.csdn.net/lankin2013/article/details/10198051
整个网页好像被作为一大段代码进行显示。

**Comment by Kenshin** [comment]
感谢提示~
这个页面其实没问题，下图所示：

![image](https://user-images.githubusercontent.com/81074/30509858-5ef772a8-9aec-11e7-8c8d-8f8589091374.png)

全部的内容都包含在 `<pre>` 下了，所以应用到 `阅读模式` 自然是这个样子 😓 

PS：像这类 UGC 的页面难免出现奇怪的问题，毕竟这些内容都是人录入的，而非模版生成。😡
