### ISSUE TITLE
同步配置文件失败

### ISSUE THREAD

**Issue by shyrz** [Kenshin/simpread#931]
- 操作系统 macOS Catalina 10.15.6
- 浏览器版本 Chrome 86.0.4209.3
- 简悦版本 2.0.0
- 发生问题的地址 chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html#common

我在多个平台使用简悦，使用兑换码在 Windows 10 升级高级账户后，其他平台无法使用 Dropbox 的配置文件覆盖本地配置，报错如图

![image](https://user-images.githubusercontent.com/5728981/90848212-e4bab280-e39e-11ea-9504-883017a4fd65.png)

同时，JSBox 版简悦也无法从 Dropbox 成功导入配置文件

**Comment by Kenshin** [comment]
我好久没用 Dropbox 了（但前阵子做测试时使用过），你可以用坚果云试试。（这个应该没问题，我一直在使用它。

我不确定是否是 API 出现了错误，我需要确认下。

PS：如果 JSBox 也一样出现问题的话，估计 API 的概率较大。

**Comment by Kenshin** [comment]
刚测试过，绑定和同步都没问题，请再多试几次。

**Comment by shyrz** [comment]
我解绑 Dropbox 账户并重新绑定，再次尝试「同步到你的 Dropbox 账户」和「强制覆盖配置文件到本地」失败，报错如图：

![image](https://user-images.githubusercontent.com/5728981/90868459-717a6600-e3c9-11ea-9733-d0d7eebdcad6.png)

于是我上传了 Dropbox 同步到本地的配置文件，能成功导入，再次解绑并重新绑定后问题解决了。
