### ISSUE TITLE
稍后阅读->阅读模式: 失败

### ISSUE THREAD

**Issue by JACKCHEN99** [Kenshin/simpread#932]
以前没怎么用简约, 刚买了高级账号来试一下. 我把 掘金的文章加入稍后阅读, 然后进入稍后阅读的阅读模式, 显示"啊哦, 出了点小状况", 是还不支持掘金吗?
![image.png](https://i.loli.net/2020/08/21/kJVBdSwsFxKCi1T.png)

**Comment by Kenshin** [comment]
这是正常的，因为有些页面确实无法通过此方式加载，你可以告诉我具体的 URL 先记 Bug

**Comment by Kenshin** [comment]
如何了？没问题的话，我关闭这个 Issues
有需要，请再重开。
