### ISSUE TITLE
【bug】导出文件（md/html/epub/pdf）失败

### ISSUE THREAD

**Issue by taseikyo** [Kenshin/simpread#935]
https://www.cnblogs.com/glory0727/p/9857511.html
如下图所示导出为 md/html 失败，后面试了下导出 epub/pdf 这些也都不行，点击都没反应😥
![preview](https://user-images.githubusercontent.com/23132915/90862906-bb128300-e3c0-11ea-8134-b742b6ab5c60.gif)

**Comment by Kenshin** [comment]
我测试了下，没有发现你说的情况，请确认下。

**Comment by taseikyo** [comment]
重装之后就没问题了 很奇怪😂
