### ISSUE TITLE
高级账户登录

### ISSUE THREAD

**Issue by NGNL2017** [Kenshin/simpread#936]
我在mac的chrome浏览器使用crx扩展进行了账号的绑定，现在切换到商店下载的扩展，无法识别激活。一个激活码只能激活一次，又没有账号密码登录的方式，如何多浏览器激活呢？

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/908

目录 3和4 可以解决你的问题。

**Comment by NGNL2017** [comment]
已解决，但觉得通过同步配置的姿势不太优雅。正常应该注册一个账号，在服务器端检测三台设备使用，就像印象笔记一样。

**Comment by Kenshin** [comment]
会考虑你的建议。

因为简悦没有账户系统，所以最好的办法就是通过配置（UID）来实现同步。虽然感觉有些奇怪，但弄清楚后会很简单。
