### ISSUE TITLE
简悦样式在保存到坚果云或语雀时丢失

### ISSUE THREAD

**Issue by 446020169** [Kenshin/simpread#938]

**Comment by Kenshin** [comment]
这是正常的，因为是以 Markdown 导出的，自然没有样式。

**Comment by 446020169** [comment]
有些文章自带的加粗效果，字体加大的效果，在简悦阅读模式下可正常显示，但保存到坚果云或语雀时就失去了加粗效果、或者字体加大效果。

**Comment by 446020169** [comment]
这些样式 在markdown格式下应该是可以实现的

**Comment by Kenshin** [comment]
> 有些文章自带的加粗效果，字体加大的效果，在简悦阅读模式下可正常显示，但保存到坚果云或语雀时就失去了加粗效果、或者字体加大效果。

你可以导出它们为 Markdown 看看是否还在？

**Comment by 446020169** [comment]
加粗标题等格式在导出的markdown下正常存在，但有些在语雀中丢失了。还有简悦阅读百合主题色时，加粗变成了深红色加粗，这种更醒目，这个主题色非常赞，但是在保存到语雀时，能否保留这种格式呢？
