### ISSUE TITLE
充电头网无法正常使用simpread

### ISSUE THREAD

**Issue by yenan3** [Kenshin/simpread#939]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win10企业版1703版本15063.2108**

- 浏览器版本 ** 84.0.4147.125（正式版本） （64 位）**

- 简悦版本 **2.0.0**

- 发生问题的地址 <http://www.chongdiantou.com/wp/archives/46552.html>

**请描述你的问题**

> 开启简悦阅读状态后，没有正文了

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。
![image](https://user-images.githubusercontent.com/60581695/90868232-25c7bc80-e3c9-11ea-9c35-e909cb523e8f.png)

**Comment by Kenshin** [comment]
谢谢反馈，确实有点问题，适配完成后我会通知你。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

***

我将关闭此 Issues
