### ISSUE TITLE
希望增加只对特定网站组自动使用阅读模式的功能

### ISSUE THREAD

**Issue by woncode** [Kenshin/simpread#94]
现在如果开启自动进入阅读模式的话，只能定义不需要自动进入阅读模式的网站，但是我想只对某些特点网站使用阅读模式，并且要访问这些网站的时候自动进入阅读模式。希望能增加自定义一个自动进入阅读模式的网址集合的功能，当且仅当进入这些网址时才自动进入阅读模式。

**Comment by Kenshin** [comment]
你的意思是需要个 `白名单` ？
目前的排除列表类似 `黑名单` 概念。

**Comment by woncode** [comment]
是的

**Comment by Kenshin** [comment]
okay 可以考虑这个需求，先记 `TO-DO`

**Comment by woncode** [comment]
好的，期待，辛苦了！

**Comment by Kenshin** [comment]
[简悦 1.0.5](http://ksria.com/simpread/changelog.html#1.0.5) 发布，已增加【白名单】功能，此 issues 将会关闭。

关于这个功能的描述请看 http://ksria.com/simpread/welcome/version_1.0.5.html#whitelists
