### ISSUE TITLE
关于"最多三台设备"的疑问

### ISSUE THREAD

**Issue by JACKCHEN99** [Kenshin/simpread#941]
- 可能是我的理解能力有问题, 我看了你们的解释, 还是不明白"最多3台设备"的意义. 
- 我的理解是可以在3台电脑上激活高级账户? 但我测试在第二台电脑输入高级账户密钥, 就显示"已被使用"
- 那么我3台电脑(台式机/苹果本/win本), 还要买3个高级账号吗? 
- 或者我要先在A电脑退出, 然后才能在B电脑激活?  那么这个3台到底是什么意思?

**Comment by Kenshin** [comment]
我又补充了 #908 的内容，基本上可以解释你的疑惑，我关闭这个 Issues 了。

有疑问再重开。

**Comment by TheTruthYouKnow** [comment]
@Kenshin 
#908 两台绑定了高级账户的设备，哪怕同时使用简悦的阅读模式，只要不是同时使用高级账户范围内的下列功能，就不会被锁定。
并没有对功能列举。
指的是哪些？比如我edge看cheatguide（旧版本chrome会进不去）并且保存md+assets，chrome(旧版本，支持flash)看政策文件，同时也保存md+assets？

**Comment by Kenshin** [comment]
@TheTruthYouKnow 

> 并没有对功能列举。

高级账户的功能... 你可以看 https://simpread.pro/price

> 比如我edge看cheatguide（旧版本chrome会进不去）并且保存md+assets，chrome(旧版本，支持flash)看政策文件，同时也保存md+assets？

md + assets 当然是高级账户功能。如果这是两台设备的话，不能同时使用。如果这是一台设备的两个浏览器，则没有问题。
