### ISSUE TITLE
跟网站样式冲突了

### ISSUE THREAD

**Issue by ksky521** [Kenshin/simpread#943]
发现`.carousel`这个class跟网站样式冲突，建议：
1. 样式做下css module处理，class名字不要污染原网站；
2. 只检测是否可进入阅读模式，不插入样式等多余代码，等点击icon之后再插入

https://github.com/Kenshin/simpread/blob/7117a77b8fe7ce6c68a60a1c2cc740b4b8914c94/src/vender/carousel/carousel.css#L8

**Comment by ksky521** [comment]
又遇见一个问题，就是我用到的「沙拉查词」在阅读模式下划词翻译没icon了，我没细看，初步怀疑也是样式冲突导致的。我尝试安装simpread的划词和翻译插件，报错了：
![image](https://user-images.githubusercontent.com/1073262/94102024-b7f92f80-fe63-11ea-9f5a-082b54181c2f.png)

**Comment by Kenshin** [comment]
> 又遇见一个问题，就是我用到的「沙拉查词」在阅读模式下划词翻译没icon了，我没细看，初步怀疑也是样式冲突导致的。我尝试安装simpread的划词和翻译插件，报错了：

沙拉查词在简悦中是无法使用的，你可以试试 https://github.com/Kenshin/simpread/issues/1177 提供的几种方案（包括：沙拉查词的解决方案

另外，保错的问题，你可能需要 **选项页 → 插件管理 → 清除本地全部插件** 后再安装。

***

PS：`.carousel` 已修复，下个版本发布。另外，给我一个邮箱，我给你发 License （抱歉，之前忘记这个事情了...   😫

**Comment by ksky521** [comment]
ksky521@gmail.com

**Comment by Kenshin** [comment]
邮件已发，未防泄漏你的邮件，我顺道删除了之前的 comment  😀

**Comment by Kenshin** [comment]
嗨，简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

此问题已 Fixed 我关闭这个 Issues 了~
