### ISSUE TITLE
卸载了之后没法再重新安装之后高级用户没了

### ISSUE THREAD

**Issue by link-ding** [Kenshin/simpread#944]
以及如何在另外一个设备上也同步到高级用户

**Comment by Kenshin** [comment]
不知道解决你的问题了吗？

简悦上线了 **简悦 · 高级账户自助找回平台** https://simpread.pro/reset 可自主找回。

**Comment by Kenshin** [comment]
嗨，没问题的话，我关闭这个 Issues 了，有需要请再重开。
