### ISSUE TITLE
瘾科技网站, 图片在文章前面的时候, 阅读模式只会从文字内容开始

### ISSUE THREAD

**Issue by lynnlake** [Kenshin/simpread#95]
比如这个例子:
http://cn.engadget.com/2017/09/14/mario-odyssey-bundle/

**Comment by Kenshin** [comment]
这是正常的，因为：
![image](https://user-images.githubusercontent.com/81074/30424865-d83cbb0a-990c-11e7-9d73-5045ae4272ae.png)

图片并没有包含在 `高亮区域` 里面，如果想要实现你说的方式，可以修改 `高亮区域`，修改办法请看 [站点适配器](https://github.com/Kenshin/simpread/wiki/%E7%AB%99%E7%82%B9%E7%BC%96%E8%BE%91%E5%99%A8#%E5%A6%82%E4%BD%95%E5%AE%9A%E5%88%B6%E5%8C%96)


但我不建议修改，因为 瘾科技 的页面结构比较乱。很容易高亮出其它内容。（ 当然你可以试着修改。）
