### ISSUE TITLE
PDF 导出后支持二次编辑

### ISSUE THREAD

**Issue by Dave-pan** [Kenshin/simpread#956]
**如图instapaper导出pdf时高亮可以正常导出**
![image](https://user-images.githubusercontent.com/61072063/90952210-57f22080-e494-11ea-942b-ddbac117478b.png)

**简悦的PDF导出就有些问题，高亮消失，和悬浮遮挡希望可以修复一下**
![image](https://user-images.githubusercontent.com/61072063/90952350-83c1d600-e495-11ea-859f-42e9fe17bf9e.png)

**Comment by Kenshin** [comment]
@Dave-pan 

嗨，抱歉，忘记通知了，简悦 2.1 发布了，增加了原生 PDF 导出方案，但在 Mac 下有些小问题，附上临时解决方案 https://github.com/Kenshin/simpread/discussions/1772

**Comment by Kenshin** [comment]
补充下：

使用同步助手导出 PDF 的话，**悬浮球遮挡** 的问题不存在了。
