### ISSUE TITLE
刚刚购买高级账户，我找不到我的账户名是什么，我如何在另一台机器上登陆高级账户？

### ISSUE THREAD

**Issue by wyhily** [Kenshin/simpread#957]
搞了一个多小时没搞明白，烦的要死
说一个账户可以使用3台机器，我死活找不到登陆方法
到底是我蠢还是设计有问题？

**Comment by wyhily** [comment]
高级用户登陆不上去了，真的太难了，不适应你们的账户模式，请帮助我解决








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kenshin/simpread"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月22日(星期六) 晚上7:00
收件人:&nbsp;"Kenshin/simpread"<simpread@noreply.github.com&gt;;
抄送:&nbsp;"岳桦"<16656129@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kenshin/simpread] 刚刚购买高级账户，我找不到我的账户名是什么，我如何在另一台机器上登陆高级账户？ (#957)





 
高级账户的话，可以看看 #908 问题3/4 😀
 
这些内容都放在了 Github Issues 置顶里面。

**Comment by Kenshin** [comment]
如何帮助？
如果丢失配置文件的话，请发邮件到 kenshin##ksria.com （## → @），附上 
License （文字）与购买凭证（图片）

另外，你可以查看 https://github.com/Kenshin/simpread/issues/new/choose 里面有一些常见的新手帮助。
