### ISSUE TITLE
得到web网页适配

### ISSUE THREAD

**Issue by CharMingF** [Kenshin/simpread#959]
**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <https://www.biji.com/article/WqavDm012GolV7BlqKxPjEy8zdk73Q>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

得到的web版本自动适配失败，只有显示标题，不显示正文信息。

重新进行选择高亮区域后，内容感觉不是很完整，查看源代码，其网页直接将每段放在了div标签里，请求适配下。

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

除此以外，还需要 **手动将下面的内容加入到延迟加载列表**，加入方式：**右键菜单 → 简悦 → 加入到排除列表**，如下图

![image](https://user-images.githubusercontent.com/81074/92322079-b35e0a00-f061-11ea-8634-a0e49aaec1a5.png)

加入主域名 `biji.com`

![image](https://user-images.githubusercontent.com/81074/92322091-c4a71680-f061-11ea-8e39-6565d35740f5.png)

如果右键菜单没有 **延迟加载列表**，请在 **选项页 → 高级设定 → 右键菜单** 开启它

***

我将关闭此 Issues
