### ISSUE TITLE
请求适配巴比特站点

### ISSUE THREAD

**Issue by 9E307** [Kenshin/simpread#96]
巴比特有些文章需要导出为PDF随时查看，但是使用导出功能需要进入阅读模式。而该插件暂且不支持该网站，麻烦您有时间后抽空适配一下，甚为感谢。

**Comment by 9E307** [comment]
另外还有一个建议是阅读模式下，建议对菜单按钮的每一个图标增加一个鼠标悬停显示名称介绍。不然初次使用的时候可能不太明白每个按钮是用作于什么，需要根据图标来猜测。

**Comment by Kenshin** [comment]
是这个网址吗？
http://www.8btc.com/
看了下，只有 `资讯` 这块可以使用 `阅读模式`。

PS：下个版本会把 `导出功能` 加入到 `聚焦模式`。

**Comment by 9E307** [comment]
对的，就是这个网站。辛苦了哦！

**Comment by Kenshin** [comment]
okay，这几天集中增加一批新站，到时候会通知。

另外，关于这个建议
> 另外还有一个建议是阅读模式下，建议对菜单按钮的每一个图标增加一个鼠标悬停显示名称介绍。不然初次使用的时候可能不太明白每个按钮是用作于什么，需要根据图标来猜测。

icon 有 tooltip 提示，如下图

![image](https://user-images.githubusercontent.com/81074/30462190-a5d63434-9989-11e7-9132-d9836b457129.png)

但有朋友反映，tooltip 有极小概率无法显示的情况，关联问题 https://github.com/Kenshin/simpread/issues/97

**Comment by Kenshin** [comment]
已适配~

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。

**Comment by 9E307** [comment]
抱歉我已经手动同步适配站点列表了，打开巴比特后右上角显示已经更新适配列表要求刷新生效，刷新依然要求刷新，我无法进入阅读模式和聚焦模式。然后我清除了插件的数据再同步适配站点列表，进入巴比特就只能使用聚焦模式，阅读模式依然显示当前没有适配。

**Comment by Kenshin** [comment]
应该没问题的，只能周一再帮你看了。

重新安装再试试（以下步骤），确认版本是 1.0.3

关闭全部标签 → 卸载 → 重启浏览器 → 安装 → 同步适配列表 → 查看关于选项卡 → 确认是 209 个适配列表

再打开试试。

**Comment by 9E307** [comment]
重启一次浏览器就可以了，版本是最新的。不过我发现还有个问题就是巴比特的网站并不是所有页面都可以适配。我主要看的是他们的翻译专栏。比如这个：http://www.8btc.com/wiki/bitcoin-a-peer-to-peer-electronic-cash-system
这个页面就只能使用聚焦模式而不能使用阅读模式，难道不可以整个域名内的网页适配吗。目前主要是想用该插件的导出功能，只好静待您发布下一个版本假如聚焦模式的导出功能了。
毕竟不是所有网站您这都能有精力全适配到，所以增强聚焦模式的功能让用户自己划定范围阅览我觉得是一个比较省心的方式。

**Comment by Kenshin** [comment]
页面的适配跟页面的结构有关。

通常情况下，页面结构不同，说明页面的类型不同，也就是 url 不同。
没有万能的适配方式，否则就是传统的阅读模式。

未来会上线自己添加功能。

另外，我之前询问过了，我发现资讯页面可以适配？所以只适配了资讯页面。

你要的页面，下次会再适配。

**Comment by Kenshin** [comment]
已适配 http://www.8btc.com/wiki 类页面~   💪 

请 [手动更新](https://github.com/Kenshin/simpread/wiki/站点编辑器#如何新增) ，此 issues 将关闭。
