### ISSUE TITLE
如何在 chrome 之外添加文章到稍后读？

### ISSUE THREAD

**Issue by cf020031308** [Kenshin/simpread#960]
是否有 API 或从其它应用如 instapaper 同步文章过来的方法？

目前看来好像添加文章只能先在浏览器中打开，然后 dd。但是我很多时候是在手机（安卓）上收集的链接。

我举个例子，比如我手机看到一篇公众号文章不错，但需要精读，因此想添加到稍后读里面，是否有直接保存的方法？或者更通用一点，我已经复制了这篇文章的 URL，如何添加到简悦的稍后读里？

今天购买稍微使用了一下，觉得标注和稍后读特别适合精读文章，因此打算把之前的精读流程从 evernote 迁到简悦，但就是来源的收集感觉很不便。或者是我还没用熟，望指教。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
