### ISSUE TITLE
导出到印象笔记失败

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#966]
问题如上，如果有同样类似的问题，请发到这个 Issues 下面。

关于印象笔记的一些设想关联可访问 https://github.com/Kenshin/simpread/issues/302

**Comment by Kenshin** [comment]
https://github.com/Kenshin/simpread/issues/916

**Comment by park314** [comment]
不只是保存到印象笔记失败，在2.0.0的chrome插件中点击保存到任何站点都没有反应，包括暂存到pocket

**Comment by Kenshin** [comment]
嗨，打扰下~

我把印象笔记失败的问题 [统一到这里](https://github.com/Kenshin/simpread/issues/302) 方便管理。

因此我将关闭此 Issues ~
