### ISSUE TITLE
控制栏 Tooltip （偶发）无法显示

### ISSUE THREAD

**Issue by 9E307** [Kenshin/simpread#97]
在使用的过程中，发现有的网站进入阅读模式之后，点击菜单按钮，鼠标放到每一个图标上可以显示该图标的功能名称，而有的就没有显示，比如小众软件的网站我测试了几次都是这种情况，只有图标而没有文字说明。

**Comment by Kenshin** [comment]
感谢反馈~
额，刚试了下，还真是... 回头看下什么问题，先记 Bug...

**Comment by Kenshin** [comment]
简悦最新版 `1.1.1` 已经解决了这个问题
同时，新增功能可以 [访问这里](http://ksria.com/simpread/welcome/version_1.1.1.html)
