### ISSUE TITLE
适配InfoQ 写作平台

### ISSUE THREAD

**Issue by xialei2200** [Kenshin/simpread#976]
xie.infoq.cn 无法适配

**Comment by Kenshin** [comment]
谢谢提示，适配好会通知你。

**Comment by Kenshin** [comment]
嗨，适配列表已经更新，你可以通过下图的方式更新它

**选项页 → 站点管理 → 手动更新适配列表**

![image](https://user-images.githubusercontent.com/81074/92321884-34b49d00-f060-11ea-93be-9176563770be.png)

同步后，适配应该是

![image](https://user-images.githubusercontent.com/81074/92321934-ab519a80-f060-11ea-95be-93d3cf53e43a.png)

除此以外，还需要 **手动将下面的内容加入到延迟加载列表**，加入方式：**右键菜单 → 简悦 → 加入到排除列表**，如下图

![image](https://user-images.githubusercontent.com/81074/92322079-b35e0a00-f061-11ea-8634-a0e49aaec1a5.png)

加入主域名 `xie.infoq.cn`

![image](https://user-images.githubusercontent.com/81074/92322185-5747b580-f062-11ea-9e2b-b5aef611771b.png)


如果右键菜单没有 **延迟加载列表**，请在 **选项页 → 高级设定 → 右键菜单** 开启它

***

注意：因为这个页面为动态加载，所以无法使用自动进入阅读模式的功能，需手动进入（快捷键/右键菜单/右上角 icon 均可进入

***

我将关闭此 Issues
