### ISSUE TITLE
关于稍后读的归档的一些想法

### ISSUE THREAD

**Issue by tianchenmao** [Kenshin/simpread#978]
稍后读的文章一旦归档，它所持有的标签会从标签栏里消失。对于像我这样把稍后读当做知识整理合集来使用的人来说（这个功能确实很棒，大赞作者），归档的使用成本远大于它提供的功能。我不清楚作者设计归档时的本意，文档中说归档就相当于已读，如果仅出于这个目的的话，我觉得不如就把归档当成隐含的标签来处理，保留已归档文章的标签，使用户依然能通过标签栏层层索引到它，而为了体现归档的属性，可以在这类文章上打一个归档的戳，并提供筛选器让用户决定是否在标签栏中显示已归档的文章，如果为了保持设计的一致性，可以设置默认为不显示归档，然后把设置自由给予用户。
说的有些杂乱，希望作者大大海涵，祝简悦越来越好！

**Comment by Kenshin** [comment]
没事的，这几天太忙了，回复晚了。

归档你可以理解为 **这个稍后读我整理完了，暂时用不到了**，它的英文名称 **archive** 

如果我写成 **已读** 的话，确实有些歧义。

不知道这么解释，是否可以理解了？

**Comment by tianchenmao** [comment]
感谢作者解惑，这两天刚发现简悦神器，连着提了几个issue，给您增加工作量了（哈哈）。

**Comment by Kenshin** [comment]
没事，只要是能提建议，我都很高兴。
如果没有异议的话，我关闭这个 Issues 了，有想法再重开。

**Comment by warmscar** [comment]
跟楼主有同样的需求，归档后文章就会从标签列表里消失，甚至标签也会因为下边的文章被归档而消失。这样在查找某个历史文章的时候就没法通过标签更容易的找到了。开发者大大可以考虑加一个归档后不改动标签树结构的选项吗😁

**Comment by Kenshin** [comment]
@warmscar 

emmm 我研究下其它具有此功能的产品都是怎么做的。

谢谢各位的反馈，我先重开这个 Issues 吧

**Comment by warmscar** [comment]
苹果的 AppStore 里有个 Marklist 的 APP 做的还是挺不错的，大佬可以去看看，不知道能不能有所参考。归档文章后不影响原来的标签树结构可能更符合大多数人的使用习惯。 辛苦啦🍺

**Comment by Kenshin** [comment]
@warmscar 

谢谢提示，有时间看下。

**Comment by Kenshin** [comment]
各位，我考虑了下，结合近期也有些朋友反馈了有些关于 **归档** 的建议。

我会把**归档后的内容也作为检索条件**，在某些方面，确实目前的归档跟很多人的理解中的归档不太一样。

当然，只能下个版本发布了。

**Comment by JasJia** [comment]
同样的诉求，期待下一个版本，谢谢啦！

**Comment by Kenshin** [comment]
@JasJia 

谢谢，会考虑的。

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，请看下图

![image](https://user-images.githubusercontent.com/81074/100058311-00cd6480-2e64-11eb-901e-1205b65785cc.png)

简单的说，即便是归档了，也能在 **标签里面** 找到。

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
