### ISSUE TITLE
阅读模式标注开启时 Ctrl + A 无法取消全选

### ISSUE THREAD

**Issue by tianchenmao** [Kenshin/simpread#979]
- 操作系统 **Ubuntu 16.04**

- 浏览器版本 **Chrome 84.0.4147.105**

- 简悦版本 **2.0.0**

**在阅读模式下，标注开启的情况下，ctrl +A 全选会直接使简悦崩溃（所有操作失效），会导致当前标签页unresponse，风扇疯狂旋转，CPU占用率从2%飙到108%（来自top命令），同时chrome会弹出错误报告。**
![Screenshot from 2020-08-24 12-46-32](https://user-images.githubusercontent.com/56330247/91004960-28fcbb80-e608-11ea-8863-19b04e0aa3a3.png)
错误报告忘截了，不过也没有太多有价值的信息。

**Comment by Kenshin** [comment]
谢谢反馈，我在 Mac 版本 84.0.4147.125 没有遇到这个问题，但确实 ctrl + a 有点问题。但不会出现你说的情况。
请确认是否每个页面都有这样的问题。

**Comment by Kenshin** [comment]
补充下：
Mac 在 ctrl + a 的表现为无法取消被选中的这些内容。

我个人觉得使用这个情况的概率很小。

**Comment by tianchenmao** [comment]
无法取消被选中的内容也是Ubuntu下的情况之一，经过确认，并非所有网页都会出现这种情况，但当网页内容较多时会出现这种情况（怀疑是否所选中的内容过多以致超出了最大承受额）您可以在Mac上以内容较大的网页进行试验，比如我上面图片所使用的阮一峰老师的ES6教程（笑）。

**Comment by Kenshin** [comment]
嗨，我测试了 https://es6.ruanyifeng.com/#docs/destructuring 这个页面的 ctrl + a

仍旧没有你说的情况发生，但确如我所说   **ctrl + a 的表现为无法取消被选中的这些内容**

我先记 Bug 吧，当作` low 的优先级来处理`。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
