### ISSUE TITLE
会影响起点首页页面布局[CSS 注入]

### ISSUE THREAD

**Issue by ljhui** [Kenshin/simpread#98]
进起点中文网首页时发现有一个编辑推荐栏出现显示问题，在其他浏览器上或关闭所有扩展正常显示如下图：
![2](https://user-images.githubusercontent.com/16174049/30461044-8a0f4ba4-9980-11e7-9e68-50354c201467.png)
但启用simpleread后首页这个编辑推荐显示只有一半：
![1](https://user-images.githubusercontent.com/16174049/30461061-bff3012a-9980-11e7-8267-29ec69099b75.png)
我使用的fedora 26 ,chrome Version 61.0.3163.79 (Official Build) (64-bit),按理说简阅在中文网首页未启用，怎么会影响网页布局呢？我开始也不确定是简阅造成的，因为用的chrome插件多，只能一个个试，发现只有使用了简阅才会这样。不过这只是个小问题，不影响使用，无意中看小说发现的，不知道怎么回事

**Comment by Kenshin** [comment]
感谢反馈~
问题已经找到，关联问题 https://github.com/Kenshin/simpread/issues/81 

下个版本解决。 😀

**Comment by Kenshin** [comment]
简悦 `1.0.4` 已发布，已解决此问题，将关闭 issues 。
