### ISSUE TITLE
代码高亮插件导致 <!-- [[[read_end]]] --> 文章内容解析不全

### ISSUE THREAD

**Issue by uchuhimo** [Kenshin/simpread#980]
当文章内容在源码中存在`<!-- [[[read_end]]] -->`时，要么只解析到read_end之前的部分，要么只解析到之后的部分；在删除源码中的`<!-- [[[read_end]]] -->`后，内容显示正常。
示例网页：https://www.infoq.cn/article/WSVm8IS1rz67Urf1Z4Fi
实际内容：
![微信截图_20200824131221](https://user-images.githubusercontent.com/7040313/91006256-7cbcd400-e60b-11ea-9723-22818fd8a72e.png)
解析结果：
![微信截图_20200824131309](https://user-images.githubusercontent.com/7040313/91006313-94945800-e60b-11ea-8290-d2d588b99863.png)
可以看到前言部分消失了。
源码中可以看到`<!-- [[[read_end]]] -->`：
![微信截图_20200824131443](https://user-images.githubusercontent.com/7040313/91006383-ce655e80-e60b-11ea-81f5-db206fbcbf08.png)
手动删掉`<!-- [[[read_end]]] -->`后，解析结果正常：
![微信截图_20200824131544](https://user-images.githubusercontent.com/7040313/91006436-f0f77780-e60b-11ea-8811-5b4d99af105a.png)

**Comment by uchuhimo** [comment]
应该不止是插件的问题，我把插件禁用之后也会出同样的问题。
示例网页：https://www.infoq.cn/article/zyEa5aBEVzUN41Z6qygV
原网页内容：
![微信截图_20200831090929](https://user-images.githubusercontent.com/7040313/91674096-d5d7bb00-eb69-11ea-9fe8-6c0df34ff74f.png)
解析结果：
![微信截图_20200831090721](https://user-images.githubusercontent.com/7040313/91674103-dcfec900-eb69-11ea-9b7c-3ae217d6d4ac.png)
插件已经禁用：
![微信截图_20200831090954](https://user-images.githubusercontent.com/7040313/91674119-e6883100-eb69-11ea-9f29-3a80853b4a72.png)

**Comment by Kenshin** [comment]
@uchuhimo 

emmm 这个算正常的，因为解析的时候会因为结构不合理被误伤，所以最好配合高亮插件。
明天详细研究下，谢谢反馈。

**Comment by Kenshin** [comment]
> 嗨，抱歉早就应该提示此 Issues 已经修复了，但因为一些原因一直耽搁到现在。

此问题可以通过 **[2.2.0.520](http://ksria.com/simpread/changelog.html)** 彻底解决。

## 简悦 2.2.0 请注意

嗨，如果你是 2.2.0 用户，当前版本也修复了 2.2.0 时的一些错误，如：[特定条件下任意页面自动进入阅读模式](https://github.com/Kenshin/simpread/issues/2159) [引起无法使用维基百科的问题](https://github.com/Kenshin/simpread/issues/2163) [聚焦模式无法使用导出服务](https://github.com/Kenshin/simpread/issues/2180) [未启用标注模式无法复制](https://github.com/Kenshin/simpread/issues/2199)

## 本次更新内容

> 本次更新了 **6 Features** ，解决了 **150+ Issues**。
> 更新内容是有史以来最多的一次，如果你对目前的稍后读工作流并不满意的话，希望可以看完下面这些更新。

> 这只是我认为有必要重点介绍的功能，除此以外还有很多小功能没有介绍。

- [构筑稍后读的数字花园](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader)

- [全「新」的稍后读](http://ksria.com/simpread/welcome/version_2.2.0.html#unreader2)

- [更易用的标注](http://ksria.com/simpread/welcome/version_2.2.0.html#annote)

- [无处不在的导出服务](http://ksria.com/simpread/welcome/version_2.2.0.html#export)

- [定制化 Markdown 与 HTML](http://ksria.com/simpread/welcome/version_2.2.0.html#custom)

- [Webhooks 与 自定义导出](http://ksria.com/simpread/welcome/version_2.2.0.html#webhooks)

- [导出服务自动化](http://ksria.com/simpread/welcome/version_2.2.0.html#automated)

- [开放平台](http://ksria.com/simpread/welcome/version_2.2.0.html#developer)

- [自动聚焦模式](http://ksria.com/simpread/welcome/version_2.2.0.html#autofocus)

- [手动模式](http://ksria.com/simpread/welcome/version_2.2.0.html#manul)

- [自动暗色模式](http://ksria.com/simpread/welcome/version_2.2.0.html#darkmode)

- [同步助手 1.0.1](http://ksria.com/simpread/welcome/version_2.2.0.html#sync)

- [更智能的词法分析引擎](http://ksria.com/simpread/welcome/version_2.2.0.html#puread)

- [针对科研工作者的网站适配](http://ksria.com/simpread/welcome/version_2.2.0.html#science)

- [快捷键可取消或停用](http://ksria.com/simpread/welcome/version_2.2.0.html#shortcuts)

## 一些 2.2.0 相关性的教程

> 稍后读 · 导出的定制化 · 自动化 · 如何与双链笔记联动 Notion / Logseq / Obsidian 等，详细说明 [请看这里](https://github.com/Kenshin/simpread/discussions/2085)。

## 更新日志

> 如果你想看 2.2.0 到底增加了哪些功能的话，可以看

1. [http://ksria.com/simpread/welcome/version_2.2.0.html](http://ksria.com/simpread/welcome/version_2.2.0.html)
2. [http://ksria.com/simpread/changelog.html](http://ksria.com/simpread/changelog.html)

## 一个建议

> 如条件允许，请一定要订阅 [简悦的发布渠道](https://t.me/simpread) 或 [这里](https://simpread.pro/subscribe) 或 [通知中心](http://ksria.com/simpread/docs/#/通知中心)

> 简悦会在每个大版本发布或不定期会推送简悦的相关信息，也请订阅 [Newsletter](https://www.getrevue.co/profile/kenshin)
