### ISSUE TITLE
无法适配当前页面

### ISSUE THREAD

**Issue by richa-sophia** [Kenshin/simpread#981]
发生问题的地址: <https://www.growingio.com/solutions/retention>

**Comment by zyeking** [comment]
该网页进入阅读模式后代码片段就没了：https://xueyuanjun.com/post/21534

**Comment by Kenshin** [comment]
@richa-sophia 
抱歉，你给出的页面没有使用阅读模式的必要。

@zyeking 
谢谢反馈，代码高亮的问题放错位置了。

我关闭这个 Issues @zyeking 可以到 https://github.com/Kenshin/simpread/issues/500 提代码高亮的问题。
