### ISSUE TITLE
高级账户问题

### ISSUE THREAD

**Issue by Ekkosun** [Kenshin/simpread#983]
解锁了高级账户，有些功能仍无法使用，提示未解锁权益，例如稍后读的合辑功能

**Comment by Kenshin** [comment]
请访问 https://github.com/Kenshin/simpread/issues/908

并留意 #1和2 的说明，也多看看选项页的其它帮助性内容，如消息中心 帮助中心 等，都会解决你的疑问。

**Comment by Ekkosun** [comment]
问题解决了，感谢
