### ISSUE TITLE
kenshin.github.io 访问 404

### ISSUE THREAD

**Issue by taofu328** [Kenshin/simpread#986]
https://pages.github.com/  能正常访问，但是进行授权返回kenshin.github.io页面都是404，使用代理也不行,比如语雀授权后返回
```
找不到 kenshin.github.io 的网页找不到与以下网址对应的网页：https://kenshin.github.io/simpread/auth.html?code=zKqwpU3jKmzeEDctwW10ZxlaFtNinHiGWBt1g7Sp&state=yuque_authorize
HTTP ERROR 404

```

**Comment by Kenshin** [comment]
很奇怪，加代理应该没问题的。

你看看能否 `ping kenshin.github.io`

**Comment by Kenshin** [comment]
另外，请告诉你的网络环境。

**Comment by taofu328** [comment]
`ping kenshin.github.io`  被解析到`127.0.0.1`。我的DNS是`114.114.114.114`.使用`nslookup kenshin.github.io`后恢复正常可以访问了。搜了一下github.io被解析到127.0.0.1的不是个例，比如v2ex的这个贴[https://www.v2ex.com/t/696315](url)
