### ISSUE TITLE
BUG：标注模式下选中文字无法复制

### ISSUE THREAD

**Issue by TakakiRey** [Kenshin/simpread#987]
- 操作系统 **Windows**

- 浏览器版本 **Chrome  84.0.4147.135**

- 简悦版本 **2.0.0**

**标注模式下选中文字无法复制**

**Comment by Kenshin** [comment]
谢谢反馈。

因为选中就高亮之类的操作，所以复制功能就被屏蔽了，没有什么好办法可以解决，你需要 **手动关闭 右下角 icon** 来实现选中复制/粘贴

**Comment by AriaLyy** [comment]
表示也遇到了同样的问题...

**Comment by Kenshin** [comment]
@AriaLyy 

你留言的上条，没特效药。 😂

**Comment by AriaLyy** [comment]
@Kenshin 给大佬点赞，强迫症患者的福音

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
