### ISSUE TITLE
阅读模式无法正常使用

### ISSUE THREAD

**Issue by kikiz1** [Kenshin/simpread#989]
操作系统: macOS Catalina s10.15.5 
浏览器: Google Chrome 版本 84.0.4147.135（正式版本） （64 位）
网址 : csdn博客 、www.dgtle.com等
问题: 使用阅读模式只显示背景图,也不显示 手动框选 和 控制面板 (在我的使用过程中,大部分网站都存在这个问题).
只有将网页加入 稍后读 中可以正常使用阅读模式
![image](https://user-images.githubusercontent.com/65056394/91111488-3753e180-e6b3-11ea-95ed-056e23b02e9b.png)

**Comment by Kenshin** [comment]
最好指出具体的 URL

另外，也试试在 **隐身模式下，仅启用简悦** 来排除是否是因为其它扩展干扰造成的问题。

**Comment by kikiz1** [comment]
问题已解决,太感谢您了,发现是“Screen Shader | Smart Screen Tinting”插件干扰的问题.

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。

**Comment by Kenshin** [comment]
搞定就好，我关闭这个 Issues 了。
