### ISSUE TITLE
已经是高级账户了，稍后阅读的合辑功能无法打开，提示我开高级账户。

### ISSUE THREAD

**Issue by lunasea57** [Kenshin/simpread#990]
我的邮箱yeshun520@gmail.com  （简悦里留的邮箱也是这个）

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **e.g.  Windows MacOS**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <请填写你的地址l>

**请描述你的问题**

> 请使用可以 **准确定位到错误** 的语句来告诉我。😀

**截图**

> 一图胜千言，所以方便的话，可以试着贴图。

**Comment by Kenshin** [comment]
请仔细阅读 #908 目录 1和2 描述的内容
