### ISSUE TITLE
已经是高级账户但是无法使用简悦稍后读的【合辑】功能。

### ISSUE THREAD

**Issue by lunasea57** [Kenshin/simpread#991]
如图
![微信截图_20200825094411](https://user-images.githubusercontent.com/50014647/91113247-ab908400-e6b7-11ea-8f86-7ede7a3ecd6c.png)
![微信截图_20200825094434](https://user-images.githubusercontent.com/50014647/91113255-b1866500-e6b7-11ea-8991-59a55a1ca9ae.png)

> 简悦已经服务 100K  的用户，所以你的很多问题，或许已经被前人解决了，所以试着看看以下几个列表中的内容：

- [用好 Github issues 能解决你大部分的疑问](https://github.com/Kenshin/simpread/issues/533)

- [常见问题汇总](https://github.com/Kenshin/simpread/issues/618)

- [代码段的专项整治](https://github.com/Kenshin/simpread/issues/500)

***

> 如上述内容无法解决你的问题，那么请将上述内容删除，并按照下方的提示书写~  😀 

**请说明发生问题的环境**

> 简悦包含了很多平台的版本，所以为了方便定位，建议告诉我一些必要信息

- 操作系统 **Win32**

- 浏览器版本 **e.g. Chrome 78.0.3904.108**

- 简悦版本 **2.0.0**

- 发生问题的地址 <chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/options/options.html

**Comment by Kenshin** [comment]
请仔细阅读 https://github.com/Kenshin/simpread/issues/908 目录 1和2 描述的内容
