### ISSUE TITLE
无法绑定坚果云

### ISSUE THREAD

**Issue by lunasea57** [Kenshin/simpread#992]
如图
![微信截图_20200825094721](https://user-images.githubusercontent.com/50014647/91113423-22c61800-e6b8-11ea-8193-b00e0598d26e.png)
![微信截图_20200825094745](https://user-images.githubusercontent.com/50014647/91113426-248fdb80-e6b8-11ea-95ed-29a024c16567.png)

**Comment by Kenshin** [comment]
绑定后有什么提示？

**Comment by lunasea57** [comment]
点击绑定后，提示正在绑定，过一会儿提示消失，也没有绑定成功。

*------------------------------------------------------------只能谈情，不能说爱。*


Kenshin Wang <notifications@github.com> 于2020年8月25日周二 上午9:57写道：

**Comment by Kenshin** [comment]
抱歉，这几天有点忙，我刚测试了下，应该没有问题。

请确认你的简悦是否是按照下面的设置

![image](https://user-images.githubusercontent.com/81074/91281881-2abab080-e7bb-11ea-911c-fdd7e978cc6e.png)

-----

我尊重每个提 Issues 的用户，但由于近期 Issues 太多了，所以没办法进行有效追踪，如果我确定这个 Issues 并不是一个有效问题（或建议）的话，我会关闭这个 Issues

同时也会对这个 Issues 进行反馈，如果有必要的话，你可以随时再开启它。  😉
