### ISSUE TITLE
更改默认标注样式以及其它建议

### ISSUE THREAD

**Issue by Colacola121** [Kenshin/simpread#995]
1. 好像不能自定义头像 2. 希望可以更改默认的标注样式，我想把默认的标注样式改成手绘风格，但是好像不可以

**Comment by llinfeng** [comment]
+标题不能标注

**Comment by Kenshin** [comment]
标题太乱，不合规，改了。

1. 未来会考虑，但优先级会极低，因为没啥用。

2. 下个版本提供

3. 标题没必要标注，我有更好的方案。

**Comment by Kenshin** [comment]
> 嗨，抱歉，这个 Issues 早就应该关闭了，我正在整理并关闭一些 **2.2.0.520** 已经修复的功能。

> 如果你收到这个邮件，并已经升级到 **2.2.0.520**，请忽略。否则，请看下当时提的问题是否真的解决了。

> 如有任何问题，可以随时再联络我。🙏

### 简悦 2.2.0.520 的相关介绍

> [可以看这里](https://github.com/Kenshin/simpread/issues/2837)


### 下载地址

> 更多下载地址请看 https://simpread.pro/download

- [Chrome Webstore](https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll)

- [Edge 外接程序](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc)
