### ISSUE TITLE
标记和稍后读的同步问题——他们保存在哪里？能同步的设备，有何数量限制？

### ISSUE THREAD

**Issue by llinfeng** [Kenshin/simpread#996]
1. 没搞懂标记（高亮、划线和加notes）的内容是咋存储的——同步到Dropbox里面？还是Chrome的cache里面？【这个算“高级内容”？】
2. 标记过的内容，能在“五台设备”上面都同步？我试了一个[这个链接](http://people.ischool.berkeley.edu/~hal/Papers/writing-economics.html)，也不是简阅不适配还是咋，每次aa之后都要重新标记阅读区域；而且，在第二台电脑上，之前标记的内容并没有完全同步。第二台电脑也“恢复了高级账户”。

3. 稍后读的入口感觉不是很好发现哎——需要添加个书签才好打开。问题：这个链接会变吗？`chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/unreader/main.html`
4. 还有，“同步稍后读的内容”，是不是会受限于“三台设备”？我感觉在两个解锁高级功能的Windows电脑之间，同步“稍后读”的内容都有困难——下面是两个有相同“账号/标识hash”的稍后读界面——两头儿分别添加的内容，看起来没有得到同步。
![image](https://user-images.githubusercontent.com/5890407/91115843-1d85b080-e659-11ea-8695-82e291255a3b.png)

**Comment by Kenshin** [comment]
有几个问题不错，我考虑放到 QA 里面。

***

> 没搞懂标记（高亮、划线和加notes）的内容是咋存储的——同步到Dropbox里面？还是Chrome的cache里面？【这个算“高级内容”？】

1. 保存到 Chrome local storage（ Chrome 沙箱）

2. 使用 **同步** 的方式才会将数据保存到你的「网盘」

> 标记过的内容，能在“五台设备”上面都同步？

同步不受到高级账户的限制，任何情况都可以使用。

> 稍后读的入口感觉不是很好发现 ...

1.  链接不会变，你可以加书签

2. 页面的任意位置 → 右键菜单 → 简悦 → 打开稍后读 或 加入到稍后读，细节请看 [右键菜单](http://ksria.com/simpread/docs/#/%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95)

> 同步稍后读的内容 ...

只有手动同步方案，即 A 浏览器 → （手动）同步到网盘 → B 浏览器（手动）同步到 B 浏览器本身，这样 A 浏览器的数据就到 B 浏览器里面了。

**Comment by llinfeng** [comment]
存储方式搞清楚了，看起来“配置文件”不光是界面参数，还包括“稍后读”的记录啥的——手动同步起来好麻烦哎，还是覆盖同步——两边有diff，目前是直接覆盖了哦。【顺序是：PC1-浏览器1按下2，再跑去PC2-浏览器2按下3】，因为是覆盖同步，PC2-浏览器2里面的diff，就被覆盖啦  || 欢迎付费的**自动同步**+**增量同步**功能 😊

![image](https://user-images.githubusercontent.com/5890407/91118955-1d3ce380-e660-11ea-8416-05b94fe4c50d.png)

再：发现[这个issue](https://github.com/Kenshin/simpread/issues/447#issuecomment-679452532)里面提到的“自定义 CSS”配置，并不能同步：需要在每天机器/浏览器上单独配置？

**Comment by Kenshin** [comment]
手动同步不麻烦，只是多点了一步而已。

A 设备不用前 → 同步（点一下）
B 设备使用前 → 同步（点一下）

即可。

增量的方案坑太多了，看看 iCloud 同步就知道了。

未来会考虑，自动上传的功能

**Comment by Kenshin** [comment]
没其它问题的话，我先关闭这个 Issues 了。

**Comment by Kenshin** [comment]
自定义样式可以保存，你可以再试试。

另外，配置文件这个词确实有些歧义，会考虑改下。
